### ISSUE TITLE
[4.0] Frontend search completely broken

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29985]
### Steps to reproduce the issue

**This is a regression since Joomla 4.0.0 Beta 2 as beta 2 was working.**

Install Joomal 4.0-dev
Login to super admin
Click Install next to Blog Sample Data
Click ok in JS popup
Click Components -> Smart Search -> Index
Click Index button 
Click Menus -> + next to Main Menu
Click Select (Menu Item Type)
Click Smart Search 
Click Search 
Enter menu Title "Search" 
Click Save and close

Go to front end and navigate to new menu Search item

Search for "blog"

### Expected result

Search results! 

<img width="875" alt="Screenshot 2020-07-05 at 13 55 47" src="https://user-images.githubusercontent.com/400092/86533196-3e3a5100-bec7-11ea-9dbd-ae425e5d03bd.png">

### Actual result

Page refreshes, no search results, no refilled input box with search query

<img width="880" alt="Screenshot 2020-07-05 at 13 54 37" src="https://user-images.githubusercontent.com/400092/86533178-15b25700-bec7-11ea-930d-1b3875a90901.png">

### System information (as much as possible)

PHP 7.4.7 Safari on Mac

### Additional Information

Now go and hack your DOM and change the method="get" to method="post" in the search form and then click search - TADA!!!

However, it should, and was working with a GET request until recently.

**Comment by PhilETaylor** [comment]
This is related to SEF Urls. 

Disable SEF Urls and it works fine. 

Therefore I'll offer up my nginx configuration (as per https://github.com/joomla/joomla-cms/pull/29303)  of 

```
## Enable SEF URLs
# Joomla API application
location /api/ {
	try_files $uri $uri/ /api/index.php?\$args;
}
# Joomla public frontend application
location / {
	try_files $uri $uri/ /index.php?\$args;
}
## -- End
```

**Comment by PhilETaylor** [comment]
Tested with official Joomla 3 docker images (using Joomla 4.-dev code) and it works as expected with and without SEF and with and without .htaccess, so this is a nginx specific issue...

**Comment by PhilETaylor** [comment]
ok this problem is with the nginx configuration provided by @nikosdion in #29303 - sorry Nic :) 

When you have 

`/index.php?\$args`

in your `try_files` in nginx location blocks and then go to a url of 

`http://127.0.0.1/index.php/search?q=blog`

you get an Input object of 

<img width="339" alt="Screenshot 2020-07-05 at 14 46 18" src="https://user-images.githubusercontent.com/400092/86534192-506bbd80-bece-11ea-942c-51230da82683.png">

as soon as I remove the `\` I get the expected result input of the below and search works again.

<img width="340" alt="Screenshot 2020-07-05 at 14 46 03" src="https://user-images.githubusercontent.com/400092/86534204-65e0e780-bece-11ea-9ad0-69a9569bc523.png">


Therefore the problem is that the advice for nginx users in #29303 is slightly wrong :)

**Comment by PhilETaylor** [comment]
Also going to post https://docs.joomla.org/Nginx here, as that documents nginx config with Joomla, and has no `\` before the `$args` :)

**Comment by PhilETaylor** [comment]
Closing as nothing to "fix" per se because ultimately its just a typo in the advice given in #29303, if Nic can update that then people (like me) will not copy and paste the wrong thing again :)

**Comment by nikosdion** [comment]
@PhilETaylor Thanks for the heads up! I had copied the code from Admin Tools... forgetting that since it was a PHP heredoc I had escaped dollar signs. I updated the comment in #29303 by removing the backslashes. Can you please give it another try?

**Comment by PhilETaylor** [comment]
Without the slashes it works as expected and search works again as per the debug in https://github.com/joomla/joomla-cms/issues/29985#issuecomment-653891076

Thanks Nik - I just did not want others to fall over the same issue I had :)

**Comment by nikosdion** [comment]
No problem. I totally fat fingered that copy and paste 😆

**Comment by PhilETaylor** [comment]
Could be worse, it could have been in the htaccess.txt and not in some Nginx config that not many people will use ;-) 

/me goes hunting in the htacces.txt next hahahaha
