### ISSUE TITLE
[4.0] Joomla 4 installer always creates backup tables overwriting older backup tables with no warning

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29986]
### Steps to reproduce the issue

install Joomla 4 with a db prefix of `jos_` - complete the installation.

delete `configuration.php`

install Joomla 4 with a db prefix of `jos_` - complete the installation 

Inspect database - note new tables prefixed `bak_jos_`

Make a known change in a table with a prefix `bak_jos_` 

delete `configuration.php`

install Joomla 4 with a db prefix of `jos_` - complete the installation 

### Expected result

No existing tables with a `bak_jos_` prefix are OVERWRITTEN leading to data loss.

Installation to fail if existing table exists 

Expect to be asked if I want to `backup or remove existing tables` like Joomla 3

### Actual result

Note you are never asked (like Joomla 3) if you want to backup or remove existing tables. They are backed up regardless if found. 

any existing tables with a `bak_jos_` prefix are OVERWRITTEN leading to data loss.

### Additional comments

Joomla 3 screenshot from documentation
![image](https://user-images.githubusercontent.com/400092/86533371-92920080-bec8-11ea-9522-45a9afbe5e5e.png)

**Comment by Quy** [comment]
Duplicate #18835?

**Comment by PhilETaylor** [comment]
"23 Nov 2017"... so buried into oblivion...
