### ISSUE TITLE
[4.0] PLG_FINDER_QUERY_FILTER_BRANCH_S_ROOT

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29988]
### Steps to reproduce the issue

Install Joomal 4.0-dev
Login to super admin
Click Install next to Blog Sample Data
Click ok in JS popup
Click Components -> Smart Search -> Index
Click Index button
Click Menus -> + next to Main Menu
Click Select (Menu Item Type)
Click Smart Search
Click Search
Enter menu Title "Search"
Click Save and close

Go to front end and navigate to new menu Search item

Type search terms: "blog"
Click Advanced Search 
Select "Types" in Search By Type
Click Search button

### Expected result

No untranslated placeholders

### Actual result

`Assuming blog is required, and with Types as PLG_FINDER_QUERY_FILTER_BRANCH_S_ROOT , the following results were found`

<img width="858" alt="Screenshot 2020-07-05 at 14 55 31" src="https://user-images.githubusercontent.com/400092/86534344-983f1480-becf-11ea-9c66-786801f64d46.png">

selecting other items can also get you:

<img width="860" alt="Screenshot 2020-07-05 at 14 58 35" src="https://user-images.githubusercontent.com/400092/86534395-0be12180-bed0-11ea-85a3-351a806eb055.png">

**Comment by brianteeman** [comment]
confirmed

**Comment by Quy** [comment]
@Hackwar

**Comment by brianteeman** [comment]
I am unable to replicate this anymore

**Comment by PhilETaylor** [comment]
Reopening because... I can today.

To replicate follow instructions in https://github.com/joomla/joomla-cms/issues/30967

Then go to the Advanced Search button, then change the "Search by type" dropdown to "Types"

Then press search. 

<img width="900" alt="Screenshot 2020-10-07 at 01 48 29" src="https://user-images.githubusercontent.com/400092/95275001-35974500-083f-11eb-96de-d7c2fc0e6809.png">

**Comment by PhilETaylor** [comment]
I also don't think that Types, Languages, Authors and Categories should be in the dropdowns as options right? These *ARE* the types, for example Author dropdown should have a list of authors and all right? 

If you select these headers in each dropdown you can get untranslated


> Assuming philtaylor is required, and with Types as PLG_FINDER_QUERY_FILTER_BRANCH_S_ROOT , and with Languages as PLG_FINDER_QUERY_FILTER_BRANCH_S_ROOT , and with Authors as PLG_FINDER_QUERY_FILTER_BRANCH_S_ROOT , and with Categories as PLG_FINDER_QUERY_FILTER_BRANCH_S_ROOT 

<img width="220" alt="Screenshot 2020-10-07 at 01 58 07" src="https://user-images.githubusercontent.com/400092/95275506-8f4c3f00-0840-11eb-9fed-433ccfc6db7e.png">
<img width="235" alt="Screenshot 2020-10-07 at 01 58 17" src="https://user-images.githubusercontent.com/400092/95275514-9410f300-0840-11eb-8d95-01f9cd11996a.png">

**Comment by PhilETaylor** [comment]
replicated again today by accident.

**Comment by Hackwar** [comment]
#33907 fixes this.

**Comment by PhilETaylor** [comment]
Thanks for looking into this￼
