### ISSUE TITLE
[4.0] frontend button icons wrong colours

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29989]
### Steps to reproduce the issue

Install Joomal 4.0-dev
Login to super admin
Click Install next to Blog Sample Data
Click ok in JS popup

Go to front end and 

Login as super admin

click Template Settings menu item

### Expected result

Save and cancel buttons with correct background colour and correct icon colour distinguishable from the background colour 

### Actual result

![Screen Recording 2020-07-05 at 03 04 PM](https://user-images.githubusercontent.com/400092/86534505-ddb01180-bed0-11ea-926c-1f663442abb8.gif)

### System information (as much as possible)

Safari on Mac

Joomla 4.0-dev @ 1f2460343242bda97a6a3458fd2f5c38124d4cd9

**Comment by brianteeman** [comment]
Can not replicate Chrome on Windows

![image](https://user-images.githubusercontent.com/1296369/86537578-eb24c600-bee7-11ea-8c8a-7a27ddc6a56c.png)

**Comment by PhilETaylor** [comment]
well I can even see the CSS that has a green color when inspected safari and chrome on Mac:

<img width="1066" alt="Screenshot 2020-07-05 at 18 33 58" src="https://user-images.githubusercontent.com/400092/86538485-34781400-beee-11ea-8ee2-005053b57ab3.png">


<img width="1593" alt="Screenshot 2020-07-05 at 18 36 11" src="https://user-images.githubusercontent.com/400092/86538534-70ab7480-beee-11ea-863a-1d29438c4518.png">

which comes from css/blocks/_icons.scss

<img width="371" alt="Screenshot 2020-07-05 at 18 37 56" src="https://user-images.githubusercontent.com/400092/86538576-b405e300-beee-11ea-8bd0-dd6a969f35db.png">

**Comment by brianteeman** [comment]
found the "problem"

With debug on - ie it is loading the non minified assets then I see the class

Can you check and see if the problem "goes away" with debug off using the minified assets

**Comment by PhilETaylor** [comment]
totally different computer (now on the laptop) and I get the same

<img width="515" alt="Screenshot 2020-07-05 at 18 47 51" src="https://user-images.githubusercontent.com/400092/86538790-190e0880-bef0-11ea-9e33-7de4e44d89cc.png">

These are all fresh installs from git, with `jinstall` asset build and then straight install - no debug mode.

One of my chrome screenshots above shows that its using` template.mi...` so assume that's the minified assets

**Comment by chmst** [comment]
Confirmed for firefox and edge on win10 (debugging is on)
<img width="572" alt="tinyMCE-frontend-buttons-colours" src="https://user-images.githubusercontent.com/1035262/86541528-e8d56280-bf0d-11ea-9695-d13f478aa9c2.PNG">

**Comment by infograf768** [comment]
Firefox Macintosh. Debug off or on. Can confirm.
Same issue for Cancel which has a red icon
```
.fas.fa-times, .icon-unpublish {
    color: #d9534f;
}
```

Same indeed when editing an article.

Or we choose btn-secondary (which has a white background, effect similar to backend), or we modify the icon colour to white. In the second case we would need a specific colour for Save & Close

**Comment by infograf768** [comment]
Using btn-secondary would give
<img width="463" alt="Screen Shot 2020-07-06 at 08 06 55" src="https://user-images.githubusercontent.com/869724/86560976-cd934300-bf5f-11ea-83c1-1ff873b8432b.png">

**Comment by infograf768** [comment]
@coolcat-creations 
What do you think?

**Comment by SharkyKZ** [comment]
Would be great if we didn't apply custom styling using generic icon selectors.

**Comment by N6REJ** [comment]
all that is needed is to apply .text-white to the buttons that have non-white background as I discussed with @chmst

**Comment by N6REJ** [comment]
pr https://github.com/joomla/joomla-cms/pull/30278
