### ISSUE TITLE
[4.0] Templates: Switching between-templates override error

### ISSUE THREAD

**Issue by angieradtke** [joomla/joomla-cms#29981]
If we have a second installed template that uses com_content overrides including customized xml-files and assign  it to default and then we choose an alternative layout for e.g. featured in the menu, everything works fine.

If we now switch back to the default template, Joomla will still use the overrides of the previously selected template,

-  even if we delete the menu -item and make a new one, 
-  even if  we deactivate the template the second template
-  even if we  clear the cache.

Bye Angie

**Comment by brianteeman** [comment]
This sounds similar to an issue raised by @coolcat-creations for J3

Is this new behaviour in J4

**Comment by angieradtke** [comment]
If I update the template code via backend erverything works well.
If I change the files directly, the view and the files are not updated.
I hope  that this is not intentional, it would be the developer's horror.

**Comment by angieradtke** [comment]
sometimes the bug sits in front of the computer
