### ISSUE TITLE
[4.0] Select Tag styled different on frontend modals

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29994]
### Steps to reproduce the issue

Install Joomal 4.0-dev @ 1f24603
Login to super admin
Click Install next to Blog Sample Data
Click ok in JS popup

Go to front end and

Login as super admin

click Welcome to your blog
Click cog -> click edit (to edit the article)

Click "CMS Content" button in editor
Select Contact
Click Filter options

### Expected result

All select boxes to be same heights and styled same-ish

### Actual result

![Screen Recording 2020-07-05 at 03 33 08 PM](https://user-images.githubusercontent.com/400092/86535019-41d4d480-bed5-11ea-8fa5-79895e345748.gif)

### System information (as much as possible)

safari on Mac

**Comment by PhilETaylor** [comment]
Click "CMS Content" button in editor
Select Article
Click Filter options

Even worse :) 

<img width="1320" alt="Screenshot 2020-07-05 at 15 37 36" src="https://user-images.githubusercontent.com/400092/86535058-7779bd80-bed5-11ea-8799-c33d68d0fa9a.png">

**Comment by ghost** [comment]
Both Issues confirmed.

**Comment by brianteeman** [comment]
Can be closed as both issues have been resolved elsewhere
