### ISSUE TITLE
[4.0][RELEASE BLOCKER] frontend modals missing all assets - did someone remove the base tag?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29998]
### Steps to reproduce the issue

Install Joomal 4.0-dev @ 1f24603
Login to super admin
Click Install next to Blog Sample Data
Click ok in JS popup

Go to front end and

Login as super admin

click Welcome to your blog
Click cog -> click edit (to edit the article)

click Versions button

### Expected result

Styled modal

### Actual result

The modal loads, but without assets, so looks unstyled 
All the assets are 404 as they are appended to the url and dont use the correct base URL. 

<img width="1584" alt="Screenshot 2020-07-05 at 16 14 06" src="https://user-images.githubusercontent.com/400092/86535751-9169cf00-beda-11ea-98c6-841a7e20c84b.png">

### System information (as much as possible)

safari on Mac

YES! I have blown away REPEATEDLY my install and reinstalled and recompiled assets many times to resolve this issue but still it persists.

### Additional comments

I also saw this earlier too on the frontend again when trying to change the template logo by using the sample content Template Settings link, but then I thought that resolved itself... very very strange. 

<img width="1598" alt="Screenshot 2020-07-05 at 15 12 44" src="https://user-images.githubusercontent.com/400092/86535769-aba3ad00-beda-11ea-9e21-412a0156ed5b.png">

**Comment by PhilETaylor** [comment]
The problem is that the iframe src is not prefixed with the correct path when using SEF 

The src should start with a / 

```
 <iframe class="iframe" src="index.php?option=com_contenthistory&amp;view=history&amp;layout=modal&amp;tmpl=component&amp;field=jform_contenthistory&amp;item_id=com_content.article.3&amp;9e389e2a5c6f59784b8e730bd71c35a7=1" name="Versions" title="Versions" height="100%" width="100%"></iframe>
```

**Comment by PhilETaylor** [comment]
Another example.

Enable SEF with SEF rewrite this time. (Issues above were with standard SEF on Rewrite off) 

Login to frontend as super admin 

Edit a module

note url of edit page is 

`http://127.0.0.1/index.php?option=com_config&view=modules&id=16&Itemid=101&return=aHR0cDovLzEyNy4wLjAuMS9jb21wb25lbnQvY29uZmlnP3ZpZXc9bW9kdWxlcyZpZD0xJnJldHVybj1hSFIwY0Rvdkx6RXlOeTR3TGpBdU1TOD0%3D`

Just click save

notice url is now different AND notice the console log message with a 404 

url now:
`http://127.0.0.1/component/config?view=modules&id=16&return=aHR0cDovLzEyNy4wLjAuMS9jb21wb25lbnQvY29uZmlnP3ZpZXc9bW9kdWxlcyZpZD0xJnJldHVybj1hSFIwY0Rvdkx6RXlOeTR3TGpBdU1TOD0=`

404 trying to load following url (as it has `/component/`in it incorrectly)

`http://127.0.0.1/component/index.php?option=com_modules&task=module.orderPosition&8436244716061d6595485618fb70d7c5=1&client_id=0&position=sidebar-right`

**Comment by brianteeman** [comment]
Tested with SEF in all three modes and cannot replicate this in any of them

SEF OFF
SEF ON
SEF ON With URL rewriting

**Comment by PhilETaylor** [comment]
And what we server? Apache ? Nginx?

**Comment by brianteeman** [comment]
Apache/2.4.41 (Win64) mod_fcgid/2.3.10-dev
--

**Comment by chmst** [comment]
All works fine for me
Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.6 Server at localhost Port 80
in firefox and edge<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29998">issues.joomla.org/tracker/joomla-cms/29998</a>.</sub>

**Comment by PhilETaylor** [comment]
I believe it might be a nginx issue.

I have blown away and started from scratch multiple times using my nginx development docker platform (which I use daily for all the other reports). 

If I hook up the same files with the `php -S 0.0.0.0:80` development web server I cannot replicate the problem.

**Comment by PhilETaylor** [comment]
Actually - I take that back. INSPECT YOUR RESPONSES and you will see they are wrong - but work.  This is what I get with a `php -S 0.0.0.0:80` server when I press the versions button


<img width="1622" alt="Screenshot 2020-07-05 at 18 31 06" src="https://user-images.githubusercontent.com/400092/86538410-d21f1380-beed-11ea-80cc-f7644c119f41.png">

Look carefully at the URL in green.   note the `/index.php/index.php?` 

Do you have that on yours? If so this is invalid (even though it works for you).

**Comment by brianteeman** [comment]
> Do you have that on yours? If so this is invalid (even though it works for you).

No

![image](https://user-images.githubusercontent.com/1296369/86538599-dac41980-beee-11ea-8ac3-5b10795caa9e.png)

**Comment by PhilETaylor** [comment]
Stranger and stranger. Yours could be affected by a sub folder. 

I get `/index.php/index.php?` with both Nginx and the PHP Development server which rules out nginx.

**Comment by PhilETaylor** [comment]
linking https://github.com/joomla/joomla-cms/issues/29990 as that's defo related to this one.

**Comment by PhilETaylor** [comment]
Im now on a totally different computer - my laptop

Git checkout
`jinstall` which is `rm -rf administrator/templates/atum/css; rm -rf templates/cassiopeia/css; rm -rf media/; rm -rf node_modules/; rm -rf libraries/vendor/; composer install; npm ci; git checkout -- libraries/vendor/.htaccess`
docker-compose up (gives me Nginx/mysql8/php7.4.7)
install as normal
login to admin - install sample data
login to frontend - click template settings - click select 

<img width="1915" alt="Screenshot 2020-07-05 at 18 51 27" src="https://user-images.githubusercontent.com/400092/86538893-d4cf3800-bef0-11ea-812c-865986e50db9.png">


Im at a loss ...

**Comment by PhilETaylor** [comment]
Ok apache seems to be working for Versions in Chrome and Safari

but for Template Settings select image, with apache, I get a JS issue in Chrome only (not safari) when using apache

<img width="1583" alt="Screenshot 2020-07-05 at 19 32 16" src="https://user-images.githubusercontent.com/400092/86539657-3fcf3d80-bef6-11ea-901d-dd4ba5faf4c4.png">

**Comment by PhilETaylor** [comment]
regardless, the getting of `/index.php/index.php?` in urls seems to be the root issue here, as the "root" is not correct and thus assets are getting loaded from the wrong place. Replicated on two different Macs with totally different configs. Im stepping away (need to be a dad) and will look again from a third computer in the morning.

**Comment by PhilETaylor** [comment]
PR incoming... found the issue... fixed the issue.
