### ISSUE TITLE
[4.0] On launching menu modal all filter options are shown

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29997]
### Steps to reproduce the issue

Install Joomal 4.0-dev @ 1f24603
Login to super admin
Click Install next to Blog Sample Data
Click ok in JS popup

Go to front end and

Login as super admin

click Welcome to your blog
Click cog -> click edit (to edit the article)

Click "CMS Content" button in editor
Select Menu

### Expected result

Filter options are hidden by default

### Actual result

<img width="965" alt="Screenshot 2020-07-05 at 15 53 52" src="https://user-images.githubusercontent.com/400092/86535368-bc9eef00-bed7-11ea-97d6-2a25de90700f.png">

### System information (as much as possible)

safari on mac

### Additional comments

Compare with the other modals from CMS Content dropdown and you will see all the other modals have filter options closed at launch

<img width="930" alt="Screenshot 2020-07-05 at 15 54 14" src="https://user-images.githubusercontent.com/400092/86535373-c9bbde00-bed7-11ea-8d9b-b412acba587c.png">

<img width="911" alt="Screenshot 2020-07-05 at 15 54 25" src="https://user-images.githubusercontent.com/400092/86535382-d04a5580-bed7-11ea-8676-5c2cdc515e7a.png">

**Comment by infograf768** [comment]
Confirmed.

**Comment by Quy** [comment]
PR #32066

**Comment by infograf768** [comment]
@Quy 
tks. forgot about that one. :)
