### ISSUE TITLE
[4.0] Frontend image select modal url paths incorrect

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29990]
### Steps to reproduce the issue

Install Joomal 4.0-dev @ 1f2460343242bda97a6a3458fd2f5c38124d4cd9
Login to super admin
Click Install next to Blog Sample Data
Click ok in JS popup

Go to front end and

Login as super admin

click Template Settings menu item

Click Select button to select a new logo

Note modal looks odd, open debug console in browser and try again, note 404 errors for bad urls to assets

### Expected result

media manager loads

### Actual result

<img width="1598" alt="Screenshot 2020-07-05 at 15 12 44" src="https://user-images.githubusercontent.com/400092/86534670-fec53200-bed1-11ea-9501-053ec03a7fad.png">

**Comment by brianteeman** [comment]
As with your other front end issues - can not replicate

**Comment by PhilETaylor** [comment]
This is defo related to https://github.com/joomla/joomla-cms/issues/29998

because in Chrome (with PHP Development Server - not nginx) Im getting 

`http://127.0.0.1:81/index.php/working-on-your-site/index.php?option=com_media&tmpl=component&asset=com_config&author=&fieldid={field-media-id}&path=local-0:/`

as an iframe path....
