### ISSUE TITLE
[4.0] No placeholder in filter box in module select 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29996]
### Steps to reproduce the issue

Install Joomal 4.0-dev @ 1f24603
Login to super admin
Click Install next to Blog Sample Data
Click ok in JS popup

Go to front end and

Login as super admin

click Welcome to your blog
Click cog -> click edit (to edit the article)

Click "CMS Content" button in editor
Select Module
Click Filter options

### Expected result

All filter boxes should be labeled or have a placeholder saying what they are for

### Actual result

One input box with no label or placeholder

<img width="890" alt="Screenshot 2020-07-05 at 15 46 22" src="https://user-images.githubusercontent.com/400092/86535226-b2c8bc00-bed6-11ea-8f76-fdbe22f13e79.png">

```html
<input type="text" name="filter[position]" id="filter_position" value="" class="form-control" list="filter_position_datalist" onchange="this.form.submit();">
```

### System information (as much as possible)

safari on mac

**Comment by PhilETaylor** [comment]
`position` should be a dropdown of positions and not a free text box. 

searching in this box for `top` doesnt show `menu-top` unless you actually search for the EXACT position name.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29999.
