### ISSUE TITLE
[4.0] Unhandled Promise Rejection: Error: Nothing selected

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29991]
### Steps to reproduce the issue

Install Joomal 4.0-dev @ 1f24603
Login to super admin
Click Install next to Blog Sample Data
Click ok in JS popup

Go to front end and

Login as super admin

click `Welcome to your blog`
Click cog -> click edit (to edit the article) 

Click "CMS Content" button in editor 
Select Image 
DONT SELECT AN IMAGE 
click "Insert Image:

### Expected result

No console errors 

### Actual result

(Ignore the first two errors in screenshot - that's TinyMCE and Safari upstream issue)

`Unhandled Promise Rejection: Error: Nothing selected`

<img width="749" alt="Screenshot 2020-07-05 at 15 21 40" src="https://user-images.githubusercontent.com/400092/86534790-3ed8e480-bed3-11ea-9c00-6abb52d8b77b.png">

### System information (as much as possible)

safari on Mac

**Comment by SharkyKZ** [comment]
Fixed in https://github.com/joomla/joomla-cms/pull/30066.
