### ISSUE TITLE
[4.0] Select boxes favour accessibility over actually showing the value

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#29995]
### Steps to reproduce the issue

this example is from the frontend select article modal in wysiwyg but I have seen other examples 

The problem is that the actual values in the dropdown as squashed and char-wrapped just to allow the "Press to select" text to be shown with no wrapping at all. 

### Expected result

No idea... but wrapping a word after 6 chars doesnt seem right. 

### Actual result

<img width="180" alt="Screenshot 2020-07-05 at 15 38 30" src="https://user-images.githubusercontent.com/400092/86535107-b871d200-bed5-11ea-976b-72d5479e3ee2.png">

![Screen Recording 2020-07-05 at 03 40 28 PM](https://user-images.githubusercontent.com/400092/86535123-ed7e2480-bed5-11ea-9d24-e2d375ae7889.gif)

**Comment by Quy** [comment]
@ciar4n Can you provide a PR for the frontend? Thanks.

**Comment by ghost** [comment]
Issue confirmed.

**Comment by Quy** [comment]
This is no longer reproducible. See #28658.
