### ISSUE TITLE
[4.0] Cannot restore article version on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30002]
### Steps to reproduce the issue

install Joomla 4 and create an article
login to frontend as super admin
edit the article you create and save it multiple times
click versions
select one of your older versions
click restore

### Expected result

Older version is restored.

### Actual result

Home page loads, older version is not restored

### System information (as much as possible)

safari on Mac

To get versions to work I have to use SEF Urls with SEF Rewrite else https://github.com/joomla/joomla-cms/issues/29998

never installed sample data - just manually created article

**Comment by chmst** [comment]
Confirmed in a local installation with a sample data text. SEF off and on makes no difference<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30002">issues.joomla.org/tracker/joomla-cms/30002</a>.</sub>

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30004.
