### ISSUE TITLE
[4.0] error untranslated on registration page

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30009]
### Steps to reproduce the issue

Install Joomla 4.0-dev with sample data
Enable User Registration 
Enable Lang debug (for testing)

On frontend click "Create an account" 
Dont complete the form
Click Register button
See red error message 
Note that "error" is lowercase and not translatable

### Expected result

`**Error**`

### Actual result

error

<img width="731" alt="Screenshot 2020-07-05 at 21 51 09" src="https://user-images.githubusercontent.com/400092/86542037-e4a74600-bf09-11ea-8ed4-5ee2e6cb1e3a.png">

### System information (as much as possible)

safari on mac

**Comment by PhilETaylor** [comment]
same on the forgotten password page and forgotten username page 

<img width="595" alt="Screenshot 2020-07-05 at 22 20 42" src="https://user-images.githubusercontent.com/400092/86542454-d1967500-bf0d-11ea-99c2-1ca506e75b5f.png">

**Comment by infograf768** [comment]
I can partly solve this by using in validate.js
```
          } else {
            message = Joomla.JText._('JLIB_FORM_CONTAINS_INVALID_FIELDS');
          }

          error = {
            [Joomla.JText._('ERROR')]: [message] // INSTEAD of error:[message]
          };
          Joomla.renderMessages(error);
        }
```
and adding
`Text::script('ERROR');`
in `FormvalidateAssetItem.php` method `public function onAttachCallback(Document $doc)`
```
	public function onAttachCallback(Document $doc)
	{
		// Add validate.js language strings
		Text::script('JLIB_FORM_CONTAINS_INVALID_FIELDS');
		Text::script('JLIB_FORM_FIELD_REQUIRED_VALUE');
		Text::script('JLIB_FORM_FIELD_REQUIRED_CHECK');
		Text::script('JLIB_FORM_FIELD_INVALID_VALUE');
		Text::script('ERROR');
	}
```
But I get the `info` blue color which is the default...

<img width="889" alt="Screen Shot 2020-07-06 at 09 04 37" src="https://user-images.githubusercontent.com/869724/86565251-c53f0600-bf67-11ea-8ca8-2035411cadfb.png">

This issue may not only exists for this specific error, but for all js trigered errors as far as I could see.

**Comment by brianteeman** [comment]
@infograf768 its easier than that

Just add the following to the registration form etc

```
// Load JavaScript message titles
Text::script('ERROR');
Text::script('WARNING');
Text::script('NOTICE');
Text::script('MESSAGE');

```

**Comment by infograf768** [comment]
You are correct. Now remains to find out where it also has to be added.
Why not add these in the template index.php so to not bother anymore. That is what we do for installation.

**Comment by infograf768** [comment]
will do patch in index.php

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/30022
