### ISSUE TITLE
[4.0] Two factor Icon mouseover zebra rows incorrect when row selected 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30000]
### Steps to reproduce the issue

Install Joomla 4.0-dev

Visit your post installation messages and enable 2FA plugin 
Navigate to Users -> Manage 
select a user

mouse over the rows

### Expected result

When row selected Two Factor column respects that

### Actual result

![Screen Recording 2020-07-05 at 04 42 55 PM](https://user-images.githubusercontent.com/400092/86536345-a6486180-bede-11ea-97ca-cf825e213cfe.gif)

### System information (as much as possible)

safari on Mac

**Comment by PhilETaylor** [comment]
#30000 !!!! woot woot !

**Comment by brianteeman** [comment]
Can not replicate this on chrome on windows

![tfa](https://user-images.githubusercontent.com/1296369/86537766-70f54100-bee9-11ea-8e4d-bf5bf0b92846.gif)

**Comment by PhilETaylor** [comment]
Did you actually tick a checkbox/select on a row??

**Comment by brianteeman** [comment]
No - because your instructions did not say that. 

I can replicate it now

**Comment by PhilETaylor** [comment]
Read my instructions again - “select a user”

**Comment by brianteeman** [comment]
fix incoming

**Comment by brianteeman** [comment]
see #30003
