### ISSUE TITLE
[4.0] frontend template settings in Google Chrome/Firefox

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30005]
### Steps to reproduce the issue

> In summary: Unless you have a current admin session (logged into admin) you cannot use the media manager on the frontend to select images in Template Settings or add images using CMS Content button in the WYSIWYG Editor when editing content.

# To replicate MAKE SURE YOU ARE LOGGED OUT OF THE ADMIN CONSOLE !!!!!!

# this should be a release blocker for sure.

Install with sample data - login as super admin to frontend

Click Template Settings

Click Select 

### Expected result

no console error message 

### Actual result

<img width="1599" alt="Screenshot 2020-07-05 at 20 29 50" src="https://user-images.githubusercontent.com/400092/86540603-95a7e380-befe-11ea-99e5-348821eff112.png">

**Comment by PhilETaylor** [comment]
To rule out git and asset build I used last nights nightly build and I can replicate this with that.

**Comment by PhilETaylor** [comment]
ok got to the bottom of this - its an ACL thing - when the model loads it fires an Ajax call to 

http://127.0.0.1/administrator/index.php?option=com_media&format=json&task=api.files&path=local-0:/

which obviously (as we are not in /administrator/) fails with: 

```json
{
    "error": true,
    "code": 403,
    "message": "You don't have permission to access this. Please contact a website administrator if this is incorrect."
}
```

**Comment by PhilETaylor** [comment]
# **to replicate MAKE SURE YOU ARE LOGGED OUT OF THE ADMIN CONSOLE !!!!!!**

**Comment by PhilETaylor** [comment]
# **this should be a release blocker for sure.** 

In summary: Unless you have a current admin session (logged into admin) you cannot use the media manager on the frontend to select images in Template Settings or add images using CMS Content button in the WYSIWYG Editor when editing content. 

This has taken almost a whole day to identify :)

**Comment by infograf768** [comment]
Confirmed. Set as release blocker indeed.

**Comment by infograf768** [comment]
Same issue evidently when editing an article and chosing Image XTD in CMS Content

**Comment by PhilETaylor** [comment]
Yes - like I say in my summary ;-)

**Comment by infograf768** [comment]
LOL

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30617.
