### ISSUE TITLE
[4.0] TinyMCE - simple preset

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30014]
### Steps to reproduce the issue

1. Go to your Plugin Manager and open TinyMCE
2. Click the `medium` and `advanced` preset buttons

You'll notice below the TinyMCE toolbar changes based on the preset chosen.

3. Click the `simple preset` button

### Expected result

A TinceMCE toolbar containing a few options, similar to: https://www.tiny.cloud/docs/demo/basic-example

### Actual result

Toolbar is empty

**Comment by brianteeman** [comment]
Confirmed

**Comment by Quy** [comment]
@Fedik Can you see why clicking `Use simple reset` results in no buttons in toolbar? Thank you.

![30014](https://user-images.githubusercontent.com/368084/92332396-b7befe80-f032-11ea-95d7-99b953fe58ce.png)

**Comment by Fedik** [comment]
I suspect the array key should be called `toolbar1` instead of `toolbar` at
https://github.com/joomla/joomla-cms/blob/54d78e9b717b7a8b23a8aeb02817384fdaa6fdd0/plugins/editors/tinymce/tinymce.php#L999-L1008
as for other presets 

but I cannot test currently, will check some time later

**Comment by Quy** [comment]
@Fedik You are correct! Thank you! See PR #30583
