### ISSUE TITLE
[4.0] User Menu - Accessibility Settings

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30013]
### Steps to reproduce the issue

This was performed on a fresh install of J4 with testing sample data.
The `System - Additional Accessibility Features` plugin is therefore **disabled** by default.

- Click the `User Menu` (top right) and go to `Accessibility Settings`

### Expected result

There shouldn't be link for `Accessibility Settings` if the plugin is disabled.

### Actual result

The link directs you to your profile settings

**Comment by brianteeman** [comment]
The plugin is something different to that menu link.

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/86567148-c1f54b80-bf62-11ea-91da-aa585deb2267.png)

**Comment by C-Lodder** [comment]
What does that link do then?

Having enabled the plugin, I'm being show the following warnings in Firefox:

> Accessibility: speech to text isn't supported in this browser or in http protocol (https required) accessibility.min.js:1:2859

> Accessibility: grayHues isn't supported in firefox
