### ISSUE TITLE
[4.0] Two icons on some buttons

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30018]
### Steps to reproduce the issue

1. Go to `/administrator/index.php?option=com_installer&view=install`
2. Go to the `Install from Web` tab
3. Click any extension

### Actual result

There are 2 icons on the buttons.

![screeny](https://user-images.githubusercontent.com/2019801/86569607-8eb4bb80-bf66-11ea-99a8-57cddf5a0bdc.png)

**Comment by brianteeman** [comment]
Thats because they are links to external websites that open in a new window and we have a css rule that matches that

**Comment by C-Lodder** [comment]
So multiple icons are expected?

**Comment by brianteeman** [comment]
i am just explaining wht it happens. Not commenting on if it is correct

**Comment by Quy** [comment]
Please test PR #30148

**Comment by Akashrajpoots14** [comment]
Hi, Sir, I want to work on this issue

**Comment by ghost** [comment]
@Akashrajpoots14 you can make a pull request without allowing by another.

**Comment by infograf768** [comment]
It is not possible to correct this directly in core.

**Comment by chmst** [comment]
I expect that this rule is not applied on buttons.

**Comment by brianteeman** [comment]
> It is not possible to correct this directly in core.

Yes it is. It is just changing the css rule

**Comment by ghost** [comment]
I want to work on this issue

**Comment by gaurav24072002** [comment]
Hey ! I am interested to solve this issue  but when I go to the required instruction everything looks fine to me . @C-Lodder Please see the screenshot:
![gsoc1](https://user-images.githubusercontent.com/77109758/111348399-2a75fa00-86a6-11eb-8044-3a244b5331ee.JPG)

If you want to say something else please can you define specifically...😅
And I would be more then happy to solve the issue...

**Comment by himanshu007-creator** [comment]
> Hey ! I am interested to solve this issue but when I go to the required instruction everything looks fine to me . @C-Lodder Please see the screenshot:
> ![gsoc1](https://user-images.githubusercontent.com/77109758/111348399-2a75fa00-86a6-11eb-8044-3a244b5331ee.JPG)
> 
> If you want to say something else please can you define specifically...😅
> And I would be more then happy to solve the issue...

looks good @gaurav24072002 , have a look <a href="https://github.com/joomla/joomla-cms/pull/30148">HERE</a>.  Working on this issue is simpler and it would be good to see you work on it😉.
I was working on it previously but found the discussion above unresolved. Ask about the desired layout and send a PR . ^_~

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/111351448-179a0000-867b-11eb-9bf8-86fa5fe7887a.png)

**Comment by brianteeman** [comment]
Are you sure that you were looking at **Joomla 4**

**Comment by himanshu007-creator** [comment]
In joomla 4 , 2 ICONS ARE VISIBLE. 
doubt:- 
Now we have to remove one of the icon or place the external link icon on the right side of text?

**Comment by drmenzelit** [comment]
I would say, we don't need the icon for external link here

**Comment by brianteeman** [comment]
@drmenzelit Then you might as well remove the icon from all buttons and links. The icon is not there as decoration. It exists to fulfil an accessibility requirement to indicate if a link will open in a new browser window.

**Comment by chmst** [comment]
I suggest to remove the decorative buttons - then it looks like this: The links are external links, the green button is a button, not a link becaus it opens a message and does not address another site at once.

![grafik](https://user-images.githubusercontent.com/1035262/111359826-49679280-868c-11eb-95a9-e54947771d3f.png)

**Comment by brianteeman** [comment]
The green button is multi-purpose and it depends on the actual extension on what it is and what it does.

**Comment by chmst** [comment]
Ok, my suggestion  is - let the green button as it is, but remove the deorative icons from link buttons, let only the generated external-link icons. 
This is a very easy fix in the layout.

**Comment by drmenzelit** [comment]
> @drmenzelit Then you might as well remove the icon from all buttons and links. The icon is not there as decoration. It exists to fulfil an accessibility requirement to indicate if a link will open in a new browser window.

sorry, I forgot...

**Comment by infograf768** [comment]
As the code producing these supplementary icons is NOT in core, the only way I found was to override it in _icon.scss.
```
diff --git a/administrator/templates/atum/scss/blocks/_icons.scss b/administrator/templates/atum/scss/blocks/_icons.scss
index 122bb50..863add6 100644
--- a/administrator/templates/atum/scss/blocks/_icons.scss
+++ b/administrator/templates/atum/scss/blocks/_icons.scss
@@ -86,2 +86,10 @@
   fill: var(--white);
 }
+
+#jed-container .icon-download::before {
+  content: "";
+}
+
+#jed-container .icon-list::before {
+  content: "";
+}

```
<img width="683" alt="Screen Shot 2021-03-17 at 10 27 59" src="https://user-images.githubusercontent.com/869724/111445278-8aeb5280-870b-11eb-92a5-4aa6f3a147b8.png">

### Note:
Did not test modifying in `.../build/media_source/plg_installer_webinstaller/scss`
But it would be better to modify the code where it is produced.

**Comment by ReLater** [comment]
Or move the external icon ::after and not ::before.

**Comment by infograf768** [comment]
> Or move the external icon ::after and not ::before.

Why not, but we have no power to do it in core...

**Comment by NikitaEmberi** [comment]
Hi, I want to work on this issue but not really understanding where exactly would it be feasible to change the code in order to reflect changes. I have been trying but stuck. Can someone please help me on this like where is it coming from? Thanks.

**Comment by gaurav24072002** [comment]
I was getting the three button when I used Joomla 3.x version but when I installed Joomla 4 I only got the download button !!
![gsoc2](https://user-images.githubusercontent.com/77109758/111517038-a2adef80-877a-11eb-8764-2953e2ab4287.JPG)

can anyone help me if I am missing something ?

**Comment by drmenzelit** [comment]
@gaurav24072002 the screenshot shows the page of BreezingForms in the Extensions Directory... what I you trying to do?

**Comment by NikitaEmberi** [comment]
I removed  .icon-download:before, .icon-list:before, .icon-share-alt classes . Now it looks like this:
![image](https://user-images.githubusercontent.com/59737567/111538681-fcbaaf00-8792-11eb-8c54-4e4c0e80fb4f.png)
Would this be fine?

**Comment by ashuydv** [comment]
Can I work on fixing this issue??

**Comment by gaurav24072002** [comment]
I made `a[target=_blank]:before` as display: none; and it looked like this:
![image](https://user-images.githubusercontent.com/77109758/111581087-a6735d80-87de-11eb-96a5-7335be93e56d.png)

Now we don't have two icon . Is this fine ?

**Comment by infograf768** [comment]
@gaurav24072002 

I think your solution is fine.

Adding in  `/administrator/templates/atum/scss/blocks/_icons.scss`


```
#jed-container a[target=_blank]:before {
  content: '';
}
```
or
```
#jed-container a[target=_blank]:before {
  display: none;
}
```
Then running npm ci
would do the job.

EDIT: But, as it may be needed for a11y as @brianteeman says, if we want 2 icons, one on each side, then the changes may have to be done in the specific external app and not in core.

**Comment by infograf768** [comment]
The code to modify is here
https://github.com/joomla/install-from-web-server/blob/4479cb21830d8a6a1e898e8c4394f4ea2bd29859/components/com_apps/layouts/apps/j4/extensions_full.php#L120-L143

**Comment by gaurav24072002** [comment]
@infograf768 Thanks for you help.. I am on it..

**Comment by infograf768** [comment]
Modifying in the external app to get 2 icons will also require some padding

<img width="598" alt="Screen Shot 2021-03-18 at 11 11 11" src="https://user-images.githubusercontent.com/869724/111609655-cf91ef00-87da-11eb-9075-e2d4d1bfdf1c.png">

Taking off the icon is maybe the simplest way there.

**Comment by drmenzelit** [comment]
After some discussions in the maintainer team, we think the best way to solve this issue is to move the external link icon after the text of the button: decorative icon - text - external link... That is more or less standard in web.

**Comment by C-Lodder** [comment]
lol

**Comment by gaurav24072002** [comment]
But what I suggested also looked fine according to me but it's ok we can also move the external icon towards right of text . can you please assign this issue to me . as I am working on this issue for long and I know the code base of it.

**Comment by rdeutz** [comment]
@gaurav24072002 we don't use assiging so often, I assign issues/PR to not forget what I have to look at. You can make a PR and set it to draft that should be enough, if you then mention the issue in your PR people can see that you are working on it.

**Comment by gaurav24072002** [comment]
ok sure 😅

**Comment by gaurav24072002** [comment]
Hey! can anyone please tell me where to find the SCSS file of extensions??

**Comment by rdeutz** [comment]
Closing because we have a PR #32851
