### ISSUE TITLE
[4.0] Link to workflows?

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30012]
### Steps to reproduce the issue

Perhaps I'm losing the plot, but I thought there used to be a sidebar menu item directing you to `com_workflow`.

Having installed a fresh copy of J4 with testing sample data, I see how way to access Workflows, other than using a direct URL:

> /administrator/index.php?option=com_workflow&view=workflows&extension=com_content

**Comment by brianteeman** [comment]
Workflows is not enabled by default now. To enable it (and get the link) go to the integrations tab of the articles configuration

**Comment by C-Lodder** [comment]
I see.

That works
