### ISSUE TITLE
[4.0] Sidebar scrolls with the page

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30019]
### What needs to be fixed

To demonstrate this on a long page, go to `administrator/index.php?option=com_installer` and click the `Install from Web` tab.

If you scroll down the page, the left sidebar moves out of the viewport, therefore if you wish to access the menu, you must scroll all the wayto the top.

### How would you fix it

Left sidebar should be sticky, just like the toolbar

**Comment by PhilETaylor** [comment]
Are yew allowed to log issues for the `Install from web` component when using in Joomla 4? if so I have a tonne of them :)

**Comment by C-Lodder** [comment]
This isn't related to `Install from Web`. Just used it as an example for a long page.

Not sure if Install from Web issues should be raised here or on the component repo.

**Comment by Quy** [comment]
Related #29360

**Comment by Quy** [comment]
Closing as duplicate.

**Comment by C-Lodder** [comment]
@Quy - The other issue refers to the system settings menu, where as I'm referring to the main sidebar menu

**Comment by brianteeman** [comment]
Please test #30853
