### ISSUE TITLE
[4.0] JS error when disabling all installer plugins

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30017]
### Steps to reproduce the issue

1. Go to your Plugin Manager
2. Disable the following plugins:
  - Installer - Install from Folder
  - Installer - Install from Upload
  - Installer - Install from Web
  - Installer - Install from URL

3. Go to `administrator/index.php?option=com_installer&view=install`

### Actual result

> Uncaught TypeError: document.getElementById(...) is null   --- media/com_installer/js/installer.min.js

> Uncaught TypeError: i[0] is undefined --- media/vendor/joomla-custom-elements/js/joomla-tab.min.js

The first error also occurs when you only have `Installer - Install from Upload` disabled.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30162.
