### ISSUE TITLE
Image transparency problem with the library joomla-cms/libraries/src/Image/

### ISSUE THREAD

**Issue by impressionestudio** [joomla/joomla-cms#30026]
### Steps to reproduce the issue
The plugin https://github.com/ttc-freebies/plugin-responsive-images is using this library "joomla-cms/libraries/src/Image" in order to create many smaller images for mobiles of jpg and webp format. 

### Expected result
Normally the transparent areas in the PNG images should stay transparent.

### Actual result
**When using PNG images with transparency, the transparent areas change to black.**

### System information (as much as possible)
Joomla v. 3.9.19

### Additional comments
Is there a way to fix this issue because png image with transparency are very common.

**Comment by SharkyKZ** [comment]
Thanks for the report but the issue is in the plugin. Closing as non-core issue.

**Comment by impressionestudio** [comment]
Thank you for the specific answer in the relative issue of the plugin.
