### ISSUE TITLE
[4.0] Sample data links result in 404

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30021]
### Steps to reproduce the issue

1. Install J4 with testing sample data
2. In the frontend, go to `Sample Sites` from the top menu
3. In the Article, click the `Fruit Shop` or `Australian Parks` links

![Untitled](https://user-images.githubusercontent.com/2019801/86572942-8f9c1c00-bf6b-11ea-9b9b-b2cb72ea0cc7.png)

### Expected result

Directed to an article

### Actual result

404 - Component not found

**Comment by brianteeman** [comment]
That is for the testing sample data which is not distributed with joomla. It is massively out of date and there are lots of issues similar to this. 

See #25777
