### ISSUE TITLE
[4.0] Auto removing $root_user gives Invalid controller class: config

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30029]
### Steps to reproduce the issue

install Joomla 4
manually edit `configuration.php` add:

```php
public $root_user = 'admin';
```

Login to the admin console 

Note the message (Says its an ERROR message, should be a "Smack you in the face" Warning though, its not an error... 

<img width="1074" alt="Screenshot 2020-07-06 at 12 59 15" src="https://user-images.githubusercontent.com/400092/86591127-d77d6c00-bf88-11ea-9e41-e32bf8e9d993.png">

Click the link `Select here to try to do it automatically.`

### Expected result

Note the message (Says its an ERROR message, should be a "Smack you in the face" Warning though, its not an error... 

Clicking the link removes the $root_user param in `JConfig` / `configuration.php`

### Actual result

<img width="1260" alt="Screenshot 2020-07-06 at 13 02 24" src="https://user-images.githubusercontent.com/400092/86591181-f4b23a80-bf88-11ea-9128-927c1a7422b5.png">

**Comment by ReLater** [comment]
Please test https://github.com/joomla/joomla-cms/pull/30031

**Comment by PhilETaylor** [comment]
I already PRed #30030 - but #30031 probably better,
