### ISSUE TITLE
[4.0] Contact - link options

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30020]
### Is your feature request related to a problem? Please describe.

1. Go to `administrator/index.php?option=com_contact&view=contacts`
2. Click on any existing contact or create a new one
3. Click the `Display` tab
4. Navigate to the `Link options` section

### Describe the solution you'd like

Currently, users have the ability to add 5 links (A, B, C, D, E).
I'd suggest using subform fields, allowing users to add as many links as they like.

![screeny2](https://user-images.githubusercontent.com/2019801/86571460-5bbff700-bf69-11ea-805b-2a8cc04f1b4d.png)

**Comment by brianteeman** [comment]
Don't we then have the same problem as with the articles links - what happens to existing data

**Comment by C-Lodder** [comment]
Existing data can be moved over to subform fields
