### ISSUE TITLE
[4.0] [cassiopeia] Grid messed up on error page

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30023]
### Steps to reproduce the issue

1. Go to `index.php/index.php?Itemid=243` (this will trigger a 404)

### Actual result

The grid seems to be messed up on the error page.
For example, the `back to top` button is above the main content

![grid](https://user-images.githubusercontent.com/2019801/86574307-8b70fe00-bf6d-11ea-87b7-2a86469cc1f0.png)

**Comment by infograf768** [comment]
Confirmed

**Comment by ghost** [comment]
https://github.com/joomla/cassiopeia/pull/101 is merged > this issue close?

**Comment by Quy** [comment]
Fixed PR #31520
