### ISSUE TITLE
Error message during Clean-Template Installation

### ISSUE THREAD

**Issue by shor-ty** [joomla/joomla-cms#30035]
### Steps to reproduce the issue
Install the simple Test-Template from https://Holzmann-cfd.com/tmp/templateHolzmannCFD.tar.gz

### Expected result
No error message during installation.

### Actual result
Error

COM_TEMPLATES_ERROR_TEMPLATE_FOLDER_NOT_FOUND

### System information (as much as possible)
Linux - Ubuntu 20.04
Apache2 2.4.41
PHP 7.4.3

### Additional comments
If you don't get an error message, it is probably related to my directory access attributes in /var/www/html
However, everything works as expected. I just want to inform you about that error message.

**Comment by ReLater** [comment]
Addition: This is a J4 issue, not J3.

**Comment by ReLater** [comment]
The error is thrown here:
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_templates/src/Model/TemplateModel.php#L250

Joomla searches for a `html/` folder inside template folder `templates/holzmanncfd/` (line 242). But there is none.

I don't know if it's a must since Joomla 4 to provide a `html/` folder in template installation packages(????)

**Comment by ReLater** [comment]
Addition: If it's a must then the message `COM_TEMPLATES_ERROR_TEMPLATE_FOLDER_NOT_FOUND` is misleading because the template folder exists (but not the subfolder `html/`).

**Comment by shor-ty** [comment]
Yes, this is a J4 issue from the Beta 2 release. I thought that I added it somewhere. However, thanks for the hint. I just wanted to inform you about this circumstance. The error message is really misleading and if the sub-folder should exist, it should be changed.

Tobi

**Comment by ReLater** [comment]
@shor-ty 
Pleasee don't remove the template link above and please don't change that template package.

I prepare a PR.

**Comment by ReLater** [comment]
Please test https://github.com/joomla/joomla-cms/pull/30036

**Comment by alikon** [comment]
closing as we have a pr #30036  to test

**Comment by shor-ty** [comment]
Can we change the path of the tar file to .com/forum/joomla/templateHolzmannCFD.tar.gz

I will otherwise keep the »tmp« path alive.

**Comment by chmst** [comment]
@shor-ty as it is already RTC - you can change directories. Thank you!
