### ISSUE TITLE
Jdoc include on multiple line will not render

### ISSUE THREAD

**Issue by hube12** [joomla/joomla-cms#30034]
### Steps to reproduce the issue
Take any templates that use jdoc include such as that:
` <jdoc:include type="modules" name="topbar6" style="fav"/>`
Break it into 2 different lines:
```html
 <jdoc:include type="modules" name="topbar6"
                                                              style="fav"/>
```
This is still correct syntax however the parser fail on it and will not render the module.

### Expected result

The parser should discard the carriage return and read to the end fo the tag.

### Actual result
The parser dont read the whole tag and just stop rendering

### System information (as much as possible)
Joomla 3.9.19 
Windows 10

### Additional comments
This bug happened when editing a template inside phpstorm and using the reformat tool that with the hard wrapping at 120 columns will split deep enough include into 2 lines.

**Comment by ReLater** [comment]
One would have to change this regular expression
https://github.com/joomla/joomla-cms/blob/3.9.19/libraries/src/Document/HtmlDocument.php#L746

Adding a `s` modifier for including newlines, too.

But this will go on: Between `jdoc:include` and `type=` exactly 1 white space is allowed. Must be replaced by something like `\s+`

I'm not a "performance expert" and not able to decide if it's worth to change this restricitive regular expression.

Aren't there possibilities in phpStorm to define reformat/rearrange exclusions?

**Comment by hube12** [comment]
@ReLater I fixed my linter in phpstorm but i was just surprised that was the issue when i started debugging it.

**Comment by joomdonation** [comment]
As the author of this issue came up with a solution, and no-one else has reported the same issue, I think it is not necessary to make change to the regex (which could introduce unexpected behavior-bugs). With that said, I'm closing this issue so that we can spend time on other more important one. Thanks !
