### ISSUE TITLE
[4.0] Dependencies outdated again

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30033]
|Package                           |Current |Latest|
|----------------------------------|--------|------|
|@babel/core                       |7.10.1  |7.10.4|
|@babel/plugin-transform-classes   |7.10.1  |7.10.4|
|@babel/plugin-transform-runtime   |7.10.1  |7.10.4|
|@babel/preset-env                 |7.10.1  |7.10.4|
|@claviska/jquery-minicolors       |2.3.4   |2.3.5|
|@fortawesome/fontawesome-free     |5.13.0  |5.13.1|
|autoprefixer                      |9.8.0   |9.8.4|
|codemirror                        |5.54.0  |5.55.0|
|css-loader                        |3.5.3   |3.6.0|
|eslint                            |7.1.0   |7.4.0|
|eslint-config-airbnb-base         |14.1.0  |14.2.0|
|eslint-plugin-import              |2.20.2  |2.22.0|
|fs-extra                          |9.0.0   |9.0.1|
|jquery-migrate                    |3.3.0   |3.3.1|
|karma                             |5.0.9   |5.1.0|
|metismenujs                       |1.2.0   |1.2.1|
|postcss                           |7.0.31  |7.0.32|
|sass-loader                       |8.0.2   |8.0.2|
|tinymce                           |5.3.1   |5.4.0|
|vue-loader                        |15.9.2  |15.9.3|
|vuex                              |3.4.0   |3.5.1|
|walk-sync                         |2.1.0   |2.2.0|
|webpack-cli                       |3.3.11  |3.3.12|

**Comment by brianteeman** [comment]
we get the point - you want this to be automatic.

**Comment by C-Lodder** [comment]
Couldn't care less anymore. Just raising the issue

**Comment by Quy** [comment]
#30248
