### ISSUE TITLE
[4.0] Transitions in Actions list with Enable Workflows = No

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30041]
### Steps to reproduce the issue

Set Enable Workflows = Yes in Articles -> Options -> Integration
Enable Plugin
Do some experimentation with Workflows.
Set Enable Workflows to No
Select Articles or Featured Articles
Select an Article Checkbox
Open the Actions Toolbar button

### Expected result

No Transitions

### Actual result

Transitions before normal actions

### Additional comments

transitions is set before calling test for workflow_enabled:
See line 89ff in Featured/HtmlView for example:

		$this->transitions   = $this->get('Transitions');
		$this->vote          = PluginHelper::isEnabled('content', 'vote');

		if (ComponentHelper::getParams('com_content')->get('workflow_enabled'))
		{
			PluginHelper::importPlugin('workflow');

			$this->transitions = $this->get('Transitions');
		}

**Comment by brianteeman** [comment]
Is this not what you are seeing?

![image](https://user-images.githubusercontent.com/1296369/86766209-1de2d180-c042-11ea-9900-b335106665b8.png)

![image](https://user-images.githubusercontent.com/1296369/86766215-20ddc200-c042-11ea-8574-e778ee3fc97c.png)

**Comment by SharkyKZ** [comment]
It's on Featured Articles page only. @ceford do you want to make a PR?

**Comment by ceford** [comment]
I would prefer someone else to do the PR. I have only ever done one and it will take me hours to remember what to do and bring my clones up to date. I really should to do PRs more often!

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30042.
