### ISSUE TITLE
Featured toggle does not update ucm_content on article list view

### ISSUE THREAD

**Issue by grantg182** [joomla/joomla-cms#30049]
### Steps to reproduce the issue
Click the Featured icon in the admin articles list view; the article is now featured. View the ucm_content table, note core_featured value remains 0 (zero). Click to Edit the article; note it shows as 'Featured', but if you click Save, the ucm_content record now shows core_featured value of 1 as expected.

### Expected result
core_featured should update to '1' when featured is selected from article list view.

### Actual result
ucm_content.core_featured value remains 0 if article featured is enabled from article list view. Similarly, the value remains 1 if article featured is disabled from the same list view. Only the Edit view appears to update ucm_content, which breaks displaying featured articles only in tag views.

### System information (as much as possible)
Joomla 3.9.19.

**Comment by SharkyKZ** [comment]
When changing state this is handled by a plugin. But no event is triggered when featured state.

**Comment by brianteeman** [comment]
Unless I am very much mistaken this is no longer relevant as creating an article no longer creates an associated entry in the ucm_content table

**Comment by Hackwar** [comment]
Indeed, that table is now only used for tagging and nothing more.

**Comment by brianteeman** [comment]
So it can be closed then
