### ISSUE TITLE
Session errors  and webAuth errors -server error 500 generated

### ISSUE THREAD

**Issue by interfacedesign** [joomla/joomla-cms#30046]
### Steps to reproduce the issue
new install

### Expected result

Joomla site to work

### Actual result

Errors

 [07-Jul-2020 14:11:11 UTC] PHP Warning: session_start(): Failed to initialize storage module: user (path: /opt/alt/php74/var/lib/php/session) in /home/interf15/public_html/J4-b2/libraries/vendor/joomla/session/src/Storage/NativeStorage.php on line 478
[07-Jul-2020 16:12:12 UTC] PHP Fatal error: Trait 'Joomla\Plugin\System\Webauthn\PluginTraits\AjaxHandler' not found in /home/interf15/public_html/J4-b2/plugins/system/webauthn/webauthn.php on line 34

**Comment by richard67** [comment]
Would you please be so kind and provide some system information? The corresponding head line in our issue template is not there for decoration only. Most important info would be the Joomla version.

**Comment by PhilETaylor** [comment]
> J4-b2

Two things.

1) The session error is normal if your database is down and not working

2) Webauthn is new in Joomla4, so this is Joomla 4. `AjaxHandler` is a valid class and loads correctly when I test. I have done lots of testing with Webauthn over the last month and not replicated this error once. 

Without information on what you did to break it, this should just be closed.

**Comment by alikon** [comment]
@interfacedesign  please add the requested info
without info this will be closed in a week

**Comment by richard67** [comment]
Well it was clear to me it must be a J4 because of webauth, but it was not clear which one and which history it has. Especially if it has been updated from a J4 alpha version or a nightly build from before Beta 1, because as elaborated at many other places here and in the support forum, that is not supported.

**Comment by Quy** [comment]
Closing due to no response from user.
