### ISSUE TITLE
Request Image Browser for Tiny MCE Edit Image Pop Up in Article and Module Manager screens

### ISSUE THREAD

**Issue by sdrawdenek** [joomla/joomla-cms#30048]
### Steps to reproduce the issue

Default content editor = Tiny MCE

Edit Image Pop Up in Article and Module Manager screens does not enable you to browse for and preview an image.

Custom Module screen does enable you to browse for an image.

Is it possible for image browsing and selection to be enabled for Tiny MCE?

This has been possible for several years using JCE free (now Lite) version.

### System information (as much as possible)

J4 Beta 2 for Testing

### Additional comments

JCE is of course an excellent extension and offers lots of additional utility beyond image browse and install.

Many would still want to use it.

But I am trying to minimise the number of extensions I need to rely on when using Joomla!

**Comment by sdrawdenek** [comment]
Apologies if this on reflection is in the wrong category (issues).

If it should be in Pull Requests would someone oblige?

Don't think I can do this as a general contributor.

**Comment by brianteeman** [comment]
A pull request is when you are submitting code

**Comment by ReLater** [comment]
Maybe I don't understand your request? If an image is already inserted in the editor text:
- Select it.
- Click "CMS Content" > "Image" and I can exchange the image with preview.

If I want to insert a new image:
- Click "CMS Content" > "Image"

**Comment by sdrawdenek** [comment]
Hope the images explain - TinyMCE does not offer a Preview. JCE does. 

Could TinyMCE also offer a preview as part of default Joomla! ?

![tiny-mce-edit-image-pop-up](https://user-images.githubusercontent.com/67973568/87158459-afa74480-c2b7-11ea-9435-d45eebecd84a.png)

![jce-image-manager-pop-up](https://user-images.githubusercontent.com/67973568/87158469-b2099e80-c2b7-11ea-84d4-40086696fb73.png)

**Comment by ReLater** [comment]
Make it like I described it in https://github.com/joomla/joomla-cms/issues/30048#issuecomment-656079000 ! Use the Joomla image button!

As far as I see and understand we can not change the TinyMCE behavior of its image button. That's the reason why there is the Joomla button "CMS Content" > "Image"

**Comment by ReLater** [comment]
![10-07-_2020_15-31-51](https://user-images.githubusercontent.com/20780646/87160072-a66fa500-c2c2-11ea-8c7d-102891536b49.jpg)

**Comment by richard67** [comment]
We already have that in J3, just it is not grouped in a "CMS Content" pull-down menu:
![j3-cms-image_1](https://user-images.githubusercontent.com/7413183/87220994-00c34100-c369-11ea-958c-3c439827435d.png)

**Comment by richard67** [comment]
Closing as not a Joomla core issue.

If you wish the TinyMCE image dialog to be extended, feel free to submitt a feature request at [https://github.com/tinymce/tinymce/issues](https://github.com/tinymce/tinymce/issues).

As an alternative to TinyMCE's image dialog you can use the Joomla's image dialog as described in comments above.

**Comment by richard67** [comment]
Closing as not a Joomla core issue.
