### ISSUE TITLE
New menu item; single article

### ISSUE THREAD

**Issue by hans3horns** [joomla/joomla-cms#30055]
### Steps to reproduce the issue
Create new article
Create new menu item
Select Single article
Popup for selecting article

### Expected result
Chosen article gets selected

### Actual result
No article gets chosen, closing the popup leaves the article field open
Chosing to create the article in this step does select that newly created article

### System information (as much as possible)
Joomla 4.0.0. beta 2 / local development: PHP 7.3.9; MySQL 5.7.26

**Comment by Quy** [comment]
Unable to reproduce. Please test with nightly builds: https://developer.joomla.org/nightly-builds.html

**Comment by astridx** [comment]
I can't confirm that with the current branch. Do you see JavaScript errors?
[systeminfo-2020-07-09T10 06 02+02 00.txt](https://github.com/joomla/joomla-cms/files/4895350/systeminfo-2020-07-09T10.06.02%2B02.00.txt)

**Comment by todordev** [comment]
That is a problem with wrong upgrade to beta. I had the same problem after copying latest code from the repository to my project.
You should replace your code with clean nightly build and install Joomla from scratch to solve that problem.

**Comment by hans3horns** [comment]
I followed Quy's and ITPrims's suggestion and updated to the latest nightly build. The problem is solved. I can now make en new menu item with a existing single article..
