### ISSUE TITLE
[4.0] PHP OpCache issue with autoloading after installing an extension

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#30050]
### Steps to reproduce the issue
Enable PHP OpCache on the server

Install an extension that uses the new service provider architecture

### Expected result
As soon as the extension is installed it works normally

### Actual result
Classes are not auto loaded and found by the PHP process. 
For example the main \Extension\NameComponent.php file and related class Vendorname\Component\Componentname\Administrator\Extension\ComponentnameComponent that is loaded in the services.php file is not found and an error occurs.

After a few seconds the OpCache refreshes and reloading the page the component starts to work normally.

### System information (as much as possible)
Linux server
PHP 7.4
OpCache enabled

### Additional comments
The problem does not happen when PHP OpCache is disabled
Probably this should be a release blocker.

**Comment by joeforjoomla** [comment]
![image](https://user-images.githubusercontent.com/17835460/86854689-30e4b880-c0b9-11ea-8379-b96771bd5831.png)

**Comment by PhilETaylor** [comment]
Probably just needs a `opcache_reset();` somewhere after the install completes right ?

**Comment by joeforjoomla** [comment]
Yes @PhilETaylor, indeed an opcache_reset(); after the install completes would solve the problem.

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/30054

**Comment by joeforjoomla** [comment]
Closing as we have PR
