### ISSUE TITLE
3/4 When $root_user defined in configuration.php, message on login screen

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30051]
### Steps to reproduce the issue

add `public $root_user = 'admin';` in your /configuration.php of a Joomla3/4 site
Navigate to /administrator/

### Expected result

No notification on login screen

### Actual result

It says Im logged in - Im not.
It says I can click to automatically remove the value - I can't

<img width="1598" alt="Screenshot 2020-07-08 at 09 05 28" src="https://user-images.githubusercontent.com/400092/86893927-40382600-c0fa-11ea-81f2-493c66a417ef.png">

<img width="440" alt="Screenshot 2020-07-08 at 09 23 59" src="https://user-images.githubusercontent.com/400092/86895731-d1100100-c0fc-11ea-9367-d22d1ca5cf66.png">

**Comment by toivo** [comment]
@PhilETaylor unable to reproduce in an out-of-the-box Beta3-dev of 8 July with no patches applied.  No luck in 3.9.19 either, the message is displayed only after I have logged in.   <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30051">issues.joomla.org/tracker/joomla-cms/30051</a>.</sub>

**Comment by PhilETaylor** [comment]
Sorry for the mis information. 

On debugging it looks like one of the mySites.guru tools (that is in development) had removed the setting value, but not removed the class property from `JConfig`

I have replicated again in Joomla 4 just now by setting `public $root_user = null;` in global config. 
I have replicated again in Joomla 3 just now by setting `public $root_user = '';` in global config.

**Comment by PhilETaylor** [comment]
in Joomla 4 (as that's the code open on my screen) the check starts with 

`if (property_exists('\JConfig', 'root_user'))` 

these explaining the behaviour Im seeing with `null` and `''`

**Comment by toivo** [comment]
@PhilETaylor Now saw the message in the admin login page of Joomla4 after using an empty root user in configuration.php: ` public $root_user = '';` 
		
Managed to get rid of the message in the above situation by adding a default value to the preceding get(), right or wrong:
`// Safety check for when configuration.php root_user is in use.`
`$rootUser = $this->get('root_user', 'this-user-does-not-exist');`

Maybe the should separate the two use cases more clearly, first when a Super User is already logged in and then when someone wants to login to the back end. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30051">issues.joomla.org/tracker/joomla-cms/30051</a>.</sub>

**Comment by PhilETaylor** [comment]
could just go for a smaller change (as `'this-user-does-not-exist'` might actually exist ;-) )

`if (property_exists('\JConfig', 'root_user') && $rootuser)`

This would then cover `""`, `''`, `null` and `false` :-)

**Comment by toivo** [comment]
You are right, that works but it would introduce a bug because the variable is not `$rootuser` but `$rootUser` ;-)
`if (property_exists('\JConfig', 'root_user') && $rootUser)`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30051">issues.joomla.org/tracker/joomla-cms/30051</a>.</sub>

**Comment by PhilETaylor** [comment]
Ah well - blame typing the comment on iphone ;-)

**Comment by PhilETaylor** [comment]
#30057 for Joomla 3 - and pray George is still bubbling up these fixes into the Joomla 4 codebase :)
