### ISSUE TITLE
[4.0] Custom field sorting - bottom only

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30073]
### Steps to reproduce the issue

I have 5 Articles custom fields, 1 without a category, 1 and 3 in named categories. I need to change the order for front end purposes.

### Expected result

In the list of fields I should be able to drag a field up or down.

### Actual result

I can only drag a field to the bottom of the list.

### System information (as much as possible)

Firefox and Chrome on Mac OS X.

### Additional comments

Not too cumbersome with a list of 5 but would be unusable with a long list.

**Comment by ceford** [comment]
Correction - read Group for Category.

I have 5 Articles custom fields, 1 without a Group, 1 and 3 in named Groups. I need to change the order for front end purposes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30073">issues.joomla.org/tracker/joomla-cms/30073</a>.</sub>

**Comment by astridx** [comment]
I can confirm this. I had a fresh installation and then I created this custom fields.
![Articles Fields test Administration](https://user-images.githubusercontent.com/9974686/87245635-2f174e00-c447-11ea-96aa-b4f8f01240be.png)
After that I changed the fields so, that they do not belong to a group. This did not solve the problem.

**Comment by richard67** [comment]
Changing status to "Confirmed".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30073">issues.joomla.org/tracker/joomla-cms/30073</a>.</sub>

**Comment by richard67** [comment]
Does it work in J3? Or do we have the same issue there, too?

**Comment by ceford** [comment]
Moving a field up and down works normally in Joomla 3. I see one difference: The J3 Fields list has an up/down sort order indicator AND a double arrow sort by this column indicator.

![image](https://user-images.githubusercontent.com/1560390/87249658-3004ab80-c458-11ea-9230-b13397d56ca1.png)

In J4  the Fields list has only an up/down indicator and the grab handles are only highlighted in the up mode:

![image](https://user-images.githubusercontent.com/1560390/87249791-19128900-c459-11ea-95e7-96be3732da45.png)

**Comment by Quy** [comment]
This is happening with all list views. See #23905.

**Comment by Quy** [comment]
Please test PR #30094
