### ISSUE TITLE
No Action Log entry for Joomla update

### ISSUE THREAD

**Issue by LukeDouglas2** [joomla/joomla-cms#30074]
### Steps to reproduce the issue

Not any. 

### Expected result

Expected a record

### Actual result

No record

### System information (as much as possible)

N/A

### Additional comments
I really like the action log but I have noticed that when an update is done on Joomla core, there is no entry in the action log.  I think this was simply an oversight somewhere prior to 3.9.20 release candidate

It does add a record if you change the update component.

"User LukeDouglas changed settings of the component Joomla! Update"

**Comment by alikon** [comment]
Good point
IMHO we should log that "event/action" especially when we are in a use case where there are more than 1 super admin

but i would like to know feedback from @HLeithner , @zero-24,  @wilsonge  before to make a pr

**Comment by HLeithner** [comment]
Entry would always make sense to me. If someone create a pr for 3.9.21 I would merge it.

**Comment by alikon** [comment]
please test #30157
