### ISSUE TITLE
Cannot select article on menuitem - single article

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#30082]
### Steps to reproduce the issue
Create several articles under a category
Create menu item - single article
Select article

### Expected result
Article selected

### Actual result
In the modal window with articles it is not possible to select an article. Nothing happens when pressing the article title.

### System information (as much as possible)
Fresh install of Joomla beta 2
PHP 7.3

### Additional comments
I have created one category, so two categories in total. I cannot select neither of the articles regardless if they are in category Uncategorized og the new category.

**Comment by Quy** [comment]
Duplicate #30055. Please test with nightly builds: https://developer.joomla.org/nightly-builds.html
