### ISSUE TITLE
[4.0] PHP Mcrypt extension alternative

### ISSUE THREAD

**Issue by mumia7575** [joomla/joomla-cms#30084]
### Is your feature request related to a problem? Please describe.
PHP mcrypt Extension is required for using the Joomla\CMS\Crypt\Cipher\CrytoCipher class and it's alias JCryptCipherCrypto.
I have not see the class implementation but quoting from PHP Mcrypt "This feature was DEPRECATED in PHP 7.1.0, and REMOVED in PHP 7.2.0.". We can install mcrypt extension however this is not advisable since:

"ext/mcrypt ¶
The mcrypt extension has been abandonware for nearly a decade now, and was also fairly complex to use. It has therefore been deprecated in favour of OpenSSL or Sodium, where it will be removed from the core and into PECL in PHP 7.2."

### Describe the solution you'd like
Replace mcrypt with openSSL or Sodium (available as of PHP 7.2.0, since joomla 4.0 requires PHP 7.2.5).

### Additional context
Security concerns about using abandonware for encrypting algorithms. It makes no sense to install on purpose an extension that's deprecated, when there are better alternatives included, like openSSL and Sodium on PHP >7.2.

**Comment by Quy** [comment]
Duplicate, Please comment in #29830.
