### ISSUE TITLE
[4.0] Extension uninstall with FTP - Form lyout

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#30081]
### Steps to reproduce the issue
Set FTP in the global configuration to yes.

Got to system - manage - extension

In the following screen (manage extension) a form for ftp account data is injected. 

### Expected result
The form looks like other cards in backend layouts.

### Actual result
An ugly layout with a layout table, not sufficient for a11y. 

![screen shot 2020-07-12 at 12 49 43](https://issues.joomla.org/uploads/1/0080b38f4ebfd42d3df744fd87f17226.png)

**Comment by hans2103** [comment]
@chmst sorry... cannot activate FTP settings without adding credentials. 
After adding credentials and trying to save I get an error. 

```
An error has occurred.
0 Undefined class constant 'ONLY_BLOCK_DEFINED_TAGS'
```

using Google I stumbled upon a solution ... https://issues.joomla.org/tracker/joomla-cms/29634
Seems you had a similar issue and solved it running `composer install`

Now I can activate FTP without adding the FTP credentials. 

I can confirm the actual result. An ugly layout not sufficient for a11y<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30081">issues.joomla.org/tracker/joomla-cms/30081</a>.</sub>

**Comment by Quy** [comment]
PR #30156
