### ISSUE TITLE
unable to create sqlite cache 

### ISSUE THREAD

**Issue by Ind20** [joomla/joomla-cms#30086]
### Steps to reproduce the issue

unable to sqlite cache and getting this error in cache log

`Deprecated: Array and string offset access syntax with curly braces is deprecated in /libraries/joomla/database/driver.php on line 1950`
`Deprecated: Array and string offset access syntax with curly braces is deprecated in /libraries/joomla/database/driver.php on line 2026`
`Deprecated: Array and string offset access syntax with curly braces is deprecated in /libraries/src/Filesystem/Path.php on line 148`
`Deprecated: Array and string offset access syntax with curly braces is deprecated in /libraries/src/Filesystem/Path.php on line 151`
`Deprecated: Array and string offset access syntax with curly braces is deprecated in /libraries/src/Filesystem/Path.php on line 154`
`Warning: session_cache_limiter(): Cannot change cache limiter when headers already sent in /libraries/joomla/session/handler/native.php on line 235`

### System information (as much as possible)

i have this system config

![Screenshot 2020-07-13 at 10 18 20 AM](https://user-images.githubusercontent.com/52099125/87272006-9ccc8400-c4f2-11ea-9994-ba10e39b89d0.png)

**Comment by SharkyKZ** [comment]
Please update your Joomla! version. This was fixed in 3.9.13.
