### ISSUE TITLE
Joomla 4.0 API issue: \Joomla\CMS\Table\User::store($updateNulls=TRUE) instead of FALSE

### ISSUE THREAD

**Issue by beat** [joomla/joomla-cms#30107]
I have found a major B/C API issue here:

https://github.com/joomla/joomla-cms/blob/1c63746721cbd92efb731d0dae76163580cd2a1c/libraries/src/Table/User.php#L339

1. This is inconsistent/incompatible with declarations of parent classes Table and TableInterface, and thus breaks the defined PHP interface.
2. More importantly, this also breaks B/C, and Community Builder when saving user profile in frontend, when changing e.g. just the name, but keeping password same (and thus the corresponding $user->password null, which generates an exception and corresponding fatal Error "Column 'password' cannot be null". And an ugly workaround would mean to read the hashed password and re-store it on update.

**Comment by SharkyKZ** [comment]
Closing as there is PR https://github.com/joomla/joomla-cms/pull/30108.
