### ISSUE TITLE
UX bug in administrator -> global configuration menu

### ISSUE THREAD

**Issue by sabersaberi2** [joomla/joomla-cms#30101]
### Steps to reproduce the issue
hi
i have more than 1000 joomla usergroups.when i want load global configuration menu it is very slowly to load.
because it want to load two "Text Filter" and "Permissions" tabs with huge usergroups.

### Expected result
maybe it need to be as default usergroup menu that you can see in the Administrator->Users->Groups via pagination setting.

### Actual result

it is very slowly for me and when i want save Global Configuration page, if i leave or close or timeout my browser window, my joomla give error in the next try to load Global Configuration :
Error decoding JSON data: Control character error, possibly incorrectly encoded

and some extensions not work correctly such as Fabrik

**Comment by richard67** [comment]
@sabersaberi2 Would you please provide some system information? At least the Joomla version we should know. The corresponding sections in a new issue is not there for nothing. And we are not able to read people's minds. Thanks in advance.

**Comment by brianteeman** [comment]
You will have multiple problems with this number of usergroups - not just in the global configuration

It is trying to save a value for each individual group which will take some time so you will have performance issues in the admin and possibly timeouts which can only be addressed by changing the php max execution time

The second problem is that by default php has a value of 1000 for input_vars. Very unhelpfully if you try to save something that has more than that number of fields it will appear to save but will actually only save the first 1000 which can lead to data corruption.

You can see the values of this in the system info

Changing the values is something you have to do at the server level and your web host will be able to help you change those php settings.

I dont really see what can be done here at the joomla level

**Comment by richard67** [comment]
@sabersaberi2 Please provide system information as mentioned above, e.g. Joomla version and PHP limits like max_execution_time, memory_limit and max_input_vars. Otherwise we have to assume it is not a Joomla core issue but poor server configuration, and we will close this issue after a week or so.

**Comment by alikon** [comment]
without providing the information required this issue will be closed in 1 week

**Comment by brianteeman** [comment]
@richard67 technically it is a joomla issue but not something that we can solve with the architecture we have and my idea to display a message about max_input_vars was rejected

**Comment by Quy** [comment]
Related #19804

**Comment by sabersaberi2** [comment]
Hi and excuse me for late
I use Joomla 3.9.2 (I understand you want maybe say must update but it seems not relevant to this problem) and php7.2.
Joomla on my own VM and I can increase each php variable, but it is not correct way. Problem is many time to load and save that page. I can increase each of max_input_var and max_execution_time and others... But it take too time ever and problem not resolved.
Before implement this number of usergroups, I want to get some advice 2 years ago from forums.joomla.org in this link:

https://forum.joomla.org/viewtopic.php?f=706&t=968250&p=3552416#p3552416

But nobody advice me for probability problems.
My problem is not maybe not save or my php limitation. My problem is I must wait 5 minute to load config page and other 5 minute to save my change. I use directly configuration.php to solve my problem temporary. I hear any other advice. Thank you...

**Comment by brianteeman** [comment]
With 1000 user groups there is no solution available

**Comment by sabersaberi2** [comment]
@brianteeman 
Thank you for explicit reply.
Please say me :
Also Is there exist any Joomla problem with 500000 user registration and 200 Acl?

**Comment by C-Lodder** [comment]
I tested with 1000 user groups and attempted to load the Global Config page on my localhost.

**Total time:** 22.48 seconds

`administrator/index.php?option=com_users&view=groups` still loads fast if I attempt to load all user groups.

The "time to interactive" can be solved by using Ajax to fetch the `Text Filters` and `Permissions`

**Comment by brianteeman** [comment]
@C-Lodder and the time to save?

**Comment by richard67** [comment]
> The "time to interactive" can be solved by using Ajax to fetch the `Text Filters` and `Permissions`

Any volunteers to make a Pull Request? Ajax is beyound my knowledge, so I'm not the one. @C-Lodder Could you work on that?

**Comment by C-Lodder** [comment]
@brianteeman It would mean reengineering how Joomla saves paremeters...e.g only the ones that have been altered.

@richard67 I'll pass :)

**Comment by brianteeman** [comment]
@C-Lodder thats what I thought. Changing the load time doesnt really help if there are still issues with saving which is why this has never been addressed before.

**Comment by C-Lodder** [comment]
@brianteeman Just tested and saving actually doesn't take long. Was around 3 seconds.

Remember that the `Permissions` are ajax based already and get saved on the fly

**Comment by dgrammatiko** [comment]
Just a reminder that there was a proposal to solve this huge scaling issue: https://github.com/joomla/joomla-cms/pull/14268 but was rejected (I don't know if it was personal preference or PD decision, can't find any mentions in the minutes)

**Comment by chmst** [comment]
related also to this one in j3 #14896<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30101">issues.joomla.org/tracker/joomla-cms/30101</a>.</sub>

**Comment by chmst** [comment]
Closing this as it is duplicate with https://github.com/joomla/joomla-cms/issues/19804 which is labelled for j4
