### ISSUE TITLE
Sub field dropdown

### ISSUE THREAD

**Issue by bobbla** [joomla/joomla-cms#30105]
### Steps to reproduce the issue
Create a new Article field
Choose sub form field
Dropdowlist

### Expected result
Should be list of options

### Actual result
No options in list

### System information (as much as possible)
Joomla 4 Beta 2

**Comment by brianteeman** [comment]
Subfields creates a list from existing fields. So you must define those fields first.

![image](https://user-images.githubusercontent.com/1296369/87534669-3f6d3a00-c68e-11ea-900e-6c8adbc45a8f.png)

![image](https://user-images.githubusercontent.com/1296369/87534672-4136fd80-c68e-11ea-959a-3bad9adf7bd7.png)

**Comment by Quy** [comment]
See #28389 and the Help page for its usage.
