### ISSUE TITLE
[3+]root_user warning displayed twice in com_media

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30106]
### Steps to reproduce the issue

add `public $root_user ='admin';` to /configuration.php in Joomla 3

got to http://example.com/administrator/index.php?option=com_media

### Expected result

one error message not two

### Actual result

<img width="1289" alt="Screenshot 2020-07-15 at 12 53 15" src="https://user-images.githubusercontent.com/400092/87542040-2ff3ee00-c69a-11ea-9adb-7f925ba4647e.png">

**Comment by ReLater** [comment]
Confirmed.
3.9.21-dev nightly

**Comment by infograf768** [comment]
is’nt that related to the use of iframes? (not on desktop to check for now)

**Comment by PhilETaylor** [comment]
yes probably

**Comment by brianteeman** [comment]
For me this is a won't fix. If the user followed the instructions in the message then they will never get to a page like this.

**Comment by PhilETaylor** [comment]
The root problem is that Joomla has no concept of "This is a partial view" (even though tmpl=component) and so things get rendered twice. This is just another example like https://github.com/joomla/joomla-cms/issues/29652 

> Plugins should respect the `&tmpl=component` part of the url and not load in a modal - UNLESS they are needed for functionality inside that modal.

**Comment by PhilETaylor** [comment]
This one can be "fixed" easily though. It could load like the Post Installation Message warning, and only load on the admin home page. 

Thinking about it the "stats gathering" message could also be restricted to the admin homepage too, as that gets annoying
