### ISSUE TITLE
[3.9.20] Articles versioning ignores custom fields

### ISSUE THREAD

**Issue by PixedBo** [joomla/joomla-cms#30109]
I don't know if this is intended... anyway:

### Steps to reproduce the issue

Brand new joomla 3.9.x installation

Test 1) create an article, assign a custom field to it. Modify the custom field several times
Test 2) create an article, assign a custom field to it. Modify che content and the custom field several times

### Expected result

Test 1) more versions for each custom field modification
Test 2) more versions of the article with both content and custom field saved

### Actual result

Test 1) no versions saved
Test 2) i have several version but when i rollback only content changes. Custom fields are last version only

### System information (as much as possible)

PHP Built On | Linux jmhlrs42.dnshosting.local 2.6.32-642.6.2.el6.x86_64 #1 SMP Wed Oct 26 06:52:09 UTC 2016 x86_64
-- | --
Database Type | mysql
Database Version | 5.5.5-10.0.23-MariaDB-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.2.5
Web Server | Apache/2
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.9.20 Stable [ Amani ] 14-July-2020 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0

### Additional comments

I've made a search in github issues but found nothing.. i don't know if this behaviour is intended or i'm missing something to configure... thanks

**Comment by Quy** [comment]
Duplicate #15700
