### ISSUE TITLE
Subform validation rule not found

### ISSUE THREAD

**Issue by chrisdavenport** [joomla/joomla-cms#30115]
### Steps to reproduce the issue

Set up a form with a subform field, making sure that
`validate="subform"`
is included.

Fill in the form and submit it.

### Expected result

Form is handled without error.

### Actual result

Error:
Joomla\CMS\Form\Form::validateField() rule `subform` missing.

### System information (as much as possible)

Joomla 3.9.20 (although problem also occurs on earlier versions).

### Additional comments

The problem is that the file /libraries/src/Form/Rule/SubFormRule.php should be renamed to /libraries/src/Form/Rule/SubformRule.php (note the lowercase "f" in "subform".

**Comment by richard67** [comment]
That will bring us back to the good old file rename problem when updating on Windows and old and new name only differ in case. @SharkyKZ Any idea how to solve this?

**Comment by SharkyKZ** [comment]
Use `validate="SubForm"`?

**Comment by chrisdavenport** [comment]
Strangely, that actually works!  I have amended the documentation here: https://docs.joomla.org/Subform_form_field_type

Thanks @SharkyKZ

**Comment by SharkyKZ** [comment]
I'm not sure if this is the right long term solution though. We probably want to have consistent casing of `Subform`.

**Comment by chrisdavenport** [comment]
True, but that's a rabbit hole I don't have time to go down at this moment.
