### ISSUE TITLE
[4.0] dropdown save-group hover background

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30116]
### Current behaviour
![image](https://user-images.githubusercontent.com/1296369/87725941-15af3280-c7b6-11ea-9745-ebead8494239.png)

### Expected behaviour
![image](https://user-images.githubusercontent.com/1296369/87726035-34adc480-c7b6-11ea-8fb2-fbc8a6537cf1.png)

**Comment by adj9** [comment]
I confirm the result with the mouse pointer on an entry, but if I remove the pointer the result I have is this:
<img width="423" alt="Schermata 2020-07-18 alle 16 30 11" src="https://user-images.githubusercontent.com/5918444/87854781-84a29d80-c914-11ea-916e-b802dd94e4e9.png">

**Comment by Quy** [comment]
Please test PR #30618
