### ISSUE TITLE
[4.0] Dropdown-item - corners

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30117]
### Current behaviour
![image](https://user-images.githubusercontent.com/1296369/87726269-9a9a4c00-c7b6-11ea-8af7-66b361056a04.png)

### Expected behaviour
![image](https://user-images.githubusercontent.com/1296369/87726336-b9004780-c7b6-11ea-966a-ea69b69370b4.png)

PS showing this with the hover as it stands out more but its present without the hover as well

**Comment by Quy** [comment]
PR #30596
