### ISSUE TITLE
[4.0] In Articles:Fields add No Field Group to -Select Field Group- option

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30114]
### Steps to reproduce the issue

You need a good selection of Fields in different groups to check this problem I guess it applies to Users and Contacts as well as Articles. 

In the Administrator menu go to Content -> Fields
Open the -Select Field Group- Filter Option
You can select any Field Group except No Field Group - it does not exist

### Additional comments

The first element in the drop-down list has an ampty value "" - if I change it to 0 and Search again I get just the fields with no groups - just what I am asking for. Looks easy!

**Comment by brianteeman** [comment]
> You can select any Field Group except No Field Group - it does not exist

Correct and expected

Look at the next filter for categories there is no option for "no categories" either

**Comment by Quy** [comment]
Changing to `0` will not work as filtering on other filters will only search for fields with no groups assigned.

**Comment by ceford** [comment]
Right now, in Joomla 3 and 4, front-end ordering of fields does NOT use the Field Group - I have tried changing Field Group order and looked at the code where it happens, in administrator/components/com_fields/src/Model/FieldModel.php (in 4). So the order in the Fields list is what counts. Improved after the recent fix to drag direction but still a tad tricky to use if your Zoo has a lot of different creatures. 

The 0 suggestion was just to show that something would work, -1 or -999 if you like.

I am being a nuisance to make sure I understand how Fields and Field Groups are supposed to work so I can explain them to others. I don't want to hold up Joomla 4 Release. If this issue is not valid then let us close it and make best use of what we have.

**Comment by Quy** [comment]
I don't consider you being a nuisance at all. Thank you for taking on the task of documenting it. It is very much appreciated!!

I can see adding a `No Group` option. Otherwise, assign these non-group fields to a group as a temporary fix.

**Comment by ceford** [comment]
I put the no group fields in a named group - good tip. I now have a first group (Bio Data) and a last group (More Info) common to all Nature Articles. The middle group is specific to an article sub-category of a Nature category, lots of them. So Flowers, Birds, etc. Got it all into the desired order in the Fields list. I added a Bird Data field group and an Eggs field. That appeared at the top of the Fields list but I need it below the Bio Data group. I could only drag Eggs to the bottom of the list but if I set the list length to 5, so there was more than one page and the last group was on a subsequent page, that worked. I guess ordering by Field Group then Field might be too tricky for dragging. One residual problem: how to avoid Bio Data and More Info tabs appearing in Articles not in the Nature category.

**Comment by Quy** [comment]
> One residual problem: how to avoid Bio Data and More Info tabs appearing in Articles not in the Nature category.

Edit the field and assign categories to it.

**Comment by ceford** [comment]
Yes - I tried that. I put the first and last groups in a Nature category and a middle group in a Flowers (say) sub-category. With an Article in the Flowers Category I was expecting the edit form to inherit fields from Nature but it doesn't. So I needed to include every sub-category in the first and last groups. Good enough for a few, but I thought 10 or 20 just did not seem right.

**Comment by ceford** [comment]
I am away for a couple of weeks so I think it best to close this issue and come back another time with a wish-list of improvements to com_fields.
