### ISSUE TITLE
Multilingual Associations not found

### ISSUE THREAD

**Issue by champ8644** [joomla/joomla-cms#30125]
### Steps to reproduce the issue

Multilingual Associations not found under component tab 

### Expected result

Multilingual Associations found under component tab / or in the Extensions/Manage

### Actual result

![image](https://user-images.githubusercontent.com/37543482/87777385-92dcb500-c853-11ea-8e41-c452f449fac7.png)
![image](https://user-images.githubusercontent.com/37543482/87777400-9c661d00-c853-11ea-8d47-c29062138df7.png)

### System information (as much as possible)

I am using joomla 3.9.20
php 7.3

### Additional comments

I have tried to re-update Joomla 3.9.20 with https://downloads.joomla.org/cms/joomla3/3-9-20 but Multilingual Associations is still not found

**Comment by chmst** [comment]
Please ask this in https://forum.joomla.org. Close this as it is not a Joomla issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30125">issues.joomla.org/tracker/joomla-cms/30125</a>.</sub>

**Comment by SharkyKZ** [comment]
Which version did you update from? And did you try `Discover` functionality in Extension Manager?
