### ISSUE TITLE
[4.0] Unused minicolors override

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#30120]
There is a currently unused override of minicolors (`administrator/templates/atum/scss/vendor/minicolors/minicolors.scss`). The file should be called `jquery.minicolors`, not `minicolors`. But if we make it usable, the styling breaks because of missing image file used by imported vendor's CSS file.

The build script would need to either copy the images to override directory or update the path.

Or we manually make CSS rule overrides but that's not a good long term solution, considering other vendor files could have the same issue.

**Comment by brianteeman** [comment]
To make it work is much easier than that
1. remove the import from the override
`@import "../../../../../../node_modules/@claviska/jquery-minicolors/jquery.minicolors";
`

2. add the override to the template.scss
`@import "vendor/minicolors/minicolors";
`

**Comment by dgrammatiko** [comment]
> remove the import from the override

This is wrong, it destroys any caching advantages, eg the code will be always invalidated per template scss updates even if it didn't change. That's not how assets should be treated.

> The build script would need to either copy the images to override directory or update the path.

There are 2 options:
- add a resolver for the path in the scss (you can copy it from Bootstrap, etc)
- Inline as base64 the image, which is better for perf
