### ISSUE TITLE
[4.0] Pagebreak Slider don't open

### ISSUE THREAD

**Issue by Aragorn77** [joomla/joomla-cms#30121]
### Steps to reproduce the issue
Using Pagebreak in an article and plugin pagebreak set to "Sliders"
"Tabs" are working fine.

### Expected result
Sliders open the page.

### Actual result
Sliders open the page and closing it immediately again.

### System information (as much as possible)

Joomla 4.0 Beta 3 dev, nightly build
Running on Debian
PHP Version 7.4.7
Apache/2.4.38

**Comment by ReLater** [comment]
I can't confirm on Windows 10
Browsers:
- current Firefox
- current Edge (chromium)
- current Chrome
- current Vivaldi

**Comment by ChristineWk** [comment]
Can't also not confirm. In this example 3rd & 4th text opened:

![pagebreak](https://user-images.githubusercontent.com/15275917/87815838-9c234d00-c866-11ea-9a23-dbc803027e5a.JPG)

**Comment by chmst** [comment]
Me too, sliders open correctly on win10, php version 7.4.3. Tested with firefox and edge.
@Aragorn77 can you check the Console, if there is a javascript error? Could you test with different browserss?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30121">issues.joomla.org/tracker/joomla-cms/30121</a>.</sub>

**Comment by Aragorn77** [comment]
Ok, it 's working with the Cassiopeia template. I installed and used the Protostar template, that is the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30121">issues.joomla.org/tracker/joomla-cms/30121</a>.</sub>

**Comment by alikon** [comment]
thank you for reporting back

**Comment by brianteeman** [comment]
Personally I would say that this needs investigating and then documenting in the upgrade things to watch section

**Comment by alikon** [comment]
well there is a new team https://volunteers.joomla.org/teams/frontend-template-working-group 
i hope that they can do it
