### ISSUE TITLE
Features used are not available in PHP 5.3.1 which is the claimed minimum supported PHP version

### ISSUE THREAD

**Issue by izharaazmi** [joomla/joomla-cms#30124]
[`Throwable`](https://www.php.net/manual/en/class.throwable.php) is available only in `PHP7`
https://github.com/joomla/joomla-cms/blob/e52de3138929c28b98729e06f077cea47ec252d0/plugins/system/redirect/redirect.php#L84

<br>

<br>

[`array_column`](https://www.php.net/manual/en/function.array-column.php) is available only in `PHP 5 >= 5.5.0, PHP 7`
https://github.com/joomla/joomla-cms/blob/e52de3138929c28b98729e06f077cea47ec252d0/plugins/system/redirect/redirect.php#L252

**Comment by brianteeman** [comment]
Reference https://github.com/joomla/joomla-cms/pull/9270

**Comment by mbabker** [comment]
Using `instanceof Throwable` or `catch Throwable` is fine regardless of PHP version, PHP doesn’t hard fail if you use non-existing classes or interfaces in these cases.

Joomla ships with a number of polyfill libraries to enable use of PHP functions introduced after 5.3.  `array_column()` is one of those polyfilled functions.

Issue can be closed, there is no bug to address.

**Comment by SharkyKZ** [comment]
Closing as stated above.
