### ISSUE TITLE
Joomla 4: Class 'ContentModelArticlesCore' not found

### ISSUE THREAD

**Issue by RedDustSnow** [joomla/joomla-cms#30133]
### Steps to reproduce the issue
When Trying to create an Article (either direct or via Create Menu) I get the following Error "Class 'ContentModelArticlesCore' not found"
Category creation is possible but not Article.
* Running JCE and Admin Tools.

### Expected result
Article Creation.

### Actual result
Failed to load resource: the server responded with a status of 500 (Internal Server Error) 
.../administrator/index.php?option=com_content&task=article.add

### System information (as much as possible)
Server: LiteSpeed
Database Version	5.6.48-cll-lve
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version 7.3.20

**Comment by RedDustSnow** [comment]
PHP Version 7.3.20
Dbase: 5.6.48-cll-lve
Server:LiteSpeed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30133">issues.joomla.org/tracker/joomla-cms/30133</a>.</sub>

**Comment by alikon** [comment]
there is no such `ContentModelArticlesCore`  class in joomla core
so your issue may depend probably from : 

> Running JCE and Admin Tools.


closing as no core issue

**Comment by RedDustSnow** [comment]
Thanks alikon, removed them.

Looked further and it was actually PWT ACL component.

I will let them know.
