### ISSUE TITLE
[RFC] Deprecated or rewrite JArchiveZip because of "Zip Functions" deprecation

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#30136]
### Problem identified
Deprecate the procedural API of ext/zip in PHP 8.0
Link: http://git.php.net/?p=php-src.git;a=commitdiff;h=f3b1f342c887073012f4ca7c1bc1b5259ce4cedc

### Proposed solution
Deprecate and replace with other lib or rewrite to use ZipArchive class interface

### Open questions
What todo?

**Comment by richard67** [comment]
What other lib could we use instead?

**Comment by SharkyKZ** [comment]
See draft using ZipArchive https://github.com/joomla-framework/archive/pull/20.

**Comment by Quy** [comment]
Close per #31246?

**Comment by SharkyKZ** [comment]
Keep this open until `joomla-framework/archive` is updated.

**Comment by Quy** [comment]
@SharkyKZ OK to close per PR #31428?

**Comment by SharkyKZ** [comment]
Yes, closing.
