### ISSUE TITLE
Subform allows for media upload on the first item only

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#30139]
### Steps to reproduce the issue
I am using a custom module with a subform with a media field.
The first field will allow me to save a file but any after that the button does not work with this error
Here's a video
https://youtu.be/2zwh2Tvayb4

### Expected result
Can upload/select media files for each repeated field.

### Actual result
Can only do the first one and receive console error
Uncaught TypeError: this.querySelector(...).open is not a function
    show http://localhost/joomla4/media/system/js/fields/joomla-field-media.min.js:1

### System information (as much as possible)
[systeminfo-2020-07-19T14 07 51+02 00.txt](https://issues.joomla.org/uploads/1/152c4c028bf7614ce2a6235ec42f9e27.txt)

**Comment by Quy** [comment]
Duplicate #26711?

**Comment by uglyeoin** [comment]
Crap.  Yes it is, also opened by me!  What an idiot.  I'll upload the video to the other one.
