### ISSUE TITLE
Last item on web installer breaks out of the box

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#30138]
### Steps to reproduce the issue
System > Install (/administrator/index.php?option=com_installer&view=install)

### Expected result
All items styled the same

### Actual result
Last item breaks out of the box.
https://nimb.ws/UFcI4w

I believe it is possibly because of the image.  The images all appear to vary in size and shape.
Some other items with larger images do it too.  https://nimb.ws/CcXi9Z

I initially wondered why we had this section as a box within a box which is what lead me to this finding.  Can we remove the outer box?  https://nimb.ws/kB9Fxy

### System information (as much as possible)
[systeminfo-2020-07-19T14 07 51+02 00.txt](https://issues.joomla.org/uploads/1/4d983ac711d669e5b7fc039d40eae149.txt)

**Comment by chmst** [comment]
Not only the last item but every item with an image higher than others. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30138">issues.joomla.org/tracker/joomla-cms/30138</a>.</sub>

**Comment by Quy** [comment]
Please test PR #30140
