### ISSUE TITLE
[4.0] API Issues.

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#30130]
### Steps to reproduce the issue
Doing a GET request for a single Article or Group of Articles doesn't return all the data.
In this case, I am going to specifically report Meta Data and Meta Desc.

### Expected result
Should return all the data that's available in the UDPATE and CREATE API request.

### Actual result
```
    "data": {
        "type": "articles",
        "id": "9",
        "attributes": {
            "typeAlias": "com_content.article",
            "id": 9,
            "asset_id": 110,
            "title": "Title of Article goes here",
            "state": 1,
            "created": "2020-07-10 13:55:11",
            "language": "*",
            "tags": {
                "2": "test",
                "3": "test2"
            },
            "text": "<p>My text</p> "
        },
        "relationships": {
            "category": {
                "data": {
                    "type": "categories",
                    "id": "8"
                }
            },
            "author": {
                "data": {
                    "type": "users",
                    "id": "30"
                }
            }
        }
    }
```

### System information (as much as possible)
Joomla 4 Beta 2

### Additional comments
You can update **metadesc** and **metakey** using API but you don't know what the value of those keys are in an existing article.

**Comment by Quy** [comment]
Please see  #27569

**Comment by chetanmadaan** [comment]
Thank YOU! sorry for not searching earlier.

**Comment by alikon** [comment]
@chetanmadaan  please test #30134

**Comment by chetanmadaan** [comment]
Roger that! Give me a few hours please.

**Comment by chetanmadaan** [comment]
Hi @alikon I had a look and it looks good. Get's us what we need.

Before:
![image](https://user-images.githubusercontent.com/3968575/87851146-0ae2c380-c8c4-11ea-9a86-3acd90565148.png)

After:
![image](https://user-images.githubusercontent.com/3968575/87851151-133afe80-c8c4-11ea-881a-2fdf21cd6a9e.png)

Thank You!

**Comment by alikon** [comment]
please mark successfully tested on https://issues.joomla.org/tracker/joomla-cms/30134

**Comment by chetanmadaan** [comment]
Done deal!

**Comment by chetanmadaan** [comment]
I see some other limitations in the API, I'll be adding different todo for them all :).
