### ISSUE TITLE
Initial ACL Configuration does not allow for Users with Access Level "Manager" to configure 2FA in Backend

### ISSUE THREAD

**Issue by le-jou** [joomla/joomla-cms#30147]
### Steps to reproduce the issue
- Enable "Enforce Two Factor Authentication" for Backend
- Create a new user with Access Level "Manager"
- Login to backend with new user

### Expected result
- Get redirected to 2FA settings page

### Actual result
- Message: "You don't have permission to access this. Please contact a website administrator if this is incorrect."

### System information
Joomla 4.0.0-beta2

### Additional comments
This is no big deal because the user can edit the settings from the frontend profile page, but there he does not get prompted that he is required to configure 2FA in order to access the backend.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30152.

**Comment by le-jou** [comment]
This fixes the issue with the permission. But when saving the settings I always get redirected again to this page, with 2FA still disabled.
