### ISSUE TITLE
menu do not select an article

### ISSUE THREAD

**Issue by enqoo** [joomla/joomla-cms#30153]
### Steps to reproduce the issue
BUG: Joomla4 beta2 the menu Single Article do not select an article.

**Comment by chmst** [comment]
Please give more information. Which error message? Is your article and the category published? Please describe your problem in detail, add screenshots or maybe a video of your problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30153">issues.joomla.org/tracker/joomla-cms/30153</a>.</sub>

**Comment by enqoo** [comment]
please watch this images![screen shot 2020-07-21 at 10 15 38](https://issues.joomla.org/uploads/1/bf8de5474e554ea616af13a44c9030ee.png), select article no response . thanks.![screen shot 2020-07-21 at 10 15 38](https://issues.joomla.org/uploads/1/7602482d95fc6c458b5e215a0a91ada5.png)![screen shot 2020-07-21 at 10 15 39](https://issues.joomla.org/uploads/1/23db7a80e20e9ecd9d6f0df7e851011f.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30153">issues.joomla.org/tracker/joomla-cms/30153</a>.</sub>

**Comment by enqoo** [comment]
![screen shot 2020-07-21 at 10 16 15](https://issues.joomla.org/uploads/1/56ced41ec4bb791906e3815f94b6c004.png)
![screen shot 2020-07-21 at 10 16 19](https://issues.joomla.org/uploads/1/819351b2271dbe69e17166913de1c61e.png)
![screen shot 2020-07-21 at 10 16 35](https://issues.joomla.org/uploads/1/398107929710798395826fd32accbc43.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30153">issues.joomla.org/tracker/joomla-cms/30153</a>.</sub>

**Comment by Quy** [comment]
Duplicate #30055. Please test with nightly builds: https://developer.joomla.org/nightly-builds.html
