### ISSUE TITLE
[4.0] Blog Layout - Columns Missing

### ISSUE THREAD

**Issue by RedDustSnow** [joomla/joomla-cms#30151]
New to "Issue Tracker" so not sure if this has been spotted (surely it has)
### Steps to reproduce the issue
Trying to set Blog Layout Column number (either via menu of Article Global Options) there is no field for number of columns. But it does list in Help. 

### Expected result
Either via menu or Articles options, there is should be a field to select number of columns for Blog Layout. 

### Actual result
No field, but there is a spacer (page source)

### System information (as much as possible)
PHP Version	7.3.20
Web Server	LiteSpeed
-
Chrome and Opera

### Additional comments
See screen Grab![screen shot 2020-07-21 at 01 34 48](https://issues.joomla.org/uploads/1/ee91cb77d1e76087e08f62b61bdcfa8d.png)

**Comment by infograf768** [comment]
Confirmed. Looking at it now.

**Comment by SharkyKZ** [comment]
Duplicate https://github.com/joomla/joomla-cms/issues/27478.

Columns option was replaced by modifier classes. See PR https://github.com/joomla/joomla-cms/pull/18319 for more details.

**Comment by infograf768** [comment]
@SharkyKZ 
I fail to understand what one shall enter in the Blog Class field when editing a blog menu item.
Example: where are the possible classes to use with Cassiopea? This is very confusing...

**Comment by SharkyKZ** [comment]
See #18319 for some Cassiopeia classes.

**Comment by infograf768** [comment]
As I said it is very confusing
Looking at the Cassiopea css IN the PR, I see some stuff like
`blog-items.columns-2`
or
`.blog-items.masonry-2`

Are these classes to enter in the field?
Why can't we have a dropdown of the possible classes to use per template?

**Comment by infograf768** [comment]
Is it only this?

<img width="627" alt="Screen Shot 2020-07-21 at 09 17 27" src="https://user-images.githubusercontent.com/869724/88024491-10921080-cb33-11ea-99e7-0cbc33fab7cb.png">

**Comment by SharkyKZ** [comment]
>Why can't we have a dropdown of the possible classes to use per template?

Because it should be possible to use any classes you want.

>Is it only this?

Yes, this should work.

**Comment by RedDustSnow** [comment]
Yep works.

Should be able to set it globally (not just via menu each time).IMHO

**Comment by infograf768** [comment]
No hint whatsoever of what to do...
Bye Bye non specialists...

**Comment by RedDustSnow** [comment]
@infograf768 ... that is what I am getting at.  Needs to be easy and intuitive nowadays or you lose uptake as they look to other CMS.

**Comment by infograf768** [comment]
One possible solution to be of help to users: the usable classes should be added BY the template provider in a way or another, including Cassiopea, so that we get a dropdown with classes possible per template present (with separations per template as we get for modules positions).
Possibility should be added indeed to enter a custom class.

**Comment by brianteeman** [comment]
This is why we have had a release blocker issue for this for a very long time. Sadly no one has really looked at anything to do with the front end of joomla

**Comment by marcodings** [comment]
The frontend template has not had the TLC it deserves, thats why a working group was established last week to have a contemporary cassiopeia at release of J4.

Areas of attention

- design
- documentation
- backward compatibility
- functionality
- acessibility
- layouts & overwrites
- performance
- misc

The working group is looking for contributors, starting with a teamlead
