### ISSUE TITLE
[3.9.] UX Issue - Selecting Menutype after Permission resets permission

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#30165]
### Steps to reproduce the issue
Create a new Menu item
Select Permission
Select any Menutype

### Expected result

Permission is still set

### Actual result
Permission is reset to public

### System information (as much as possible)

Joomla 3.9.

### Additional comments
That actually happens to me quite often since ever - I think it would be an improvement to fix the selection there.

**Comment by Quy** [comment]
Duplicate #22150
