### ISSUE TITLE
[3.9] Missing typecasting SQL query plugin privacy actionlogs

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#30164]
### Steps to reproduce the issue

File: \plugins\privacy\actionlogs\actionlogs.php:

See line 45:
->where($this->db->quoteName('a.user_id') . ' = ' . $user->id);

### Expected result

->where($this->db->quoteName('a.user_id') . ' = ' . (int) $user->id);

### Actual result

Missing typecasting SQL query.

### System information (as much as possible)

Joomla! 3.9.21-dev Development [ Amani ] 14-July-2020 15:50 GMT

### Additional comments

See https://docs.joomla.org/Secure_coding_guidelines

@zero-24

**Comment by zero-24** [comment]
Can you send a PR with the proposed change?

**Comment by sandewt** [comment]
>Can you send a PR with the proposed change?

@zero-24 

Done.

**Comment by alikon** [comment]
please test #30173
