### ISSUE TITLE
[4.0] Single Article menu item

### ISSUE THREAD

**Issue by croatian-coast** [joomla/joomla-cms#30161]
### Steps to reproduce the issue
Add a Menu item, try to select a article, unable to select article due to javascript:void(0) in href 

### Expected result

Expected to select an article from popup.

### Actual result

Unable to click or select an article inside popup

### System information (as much as possible)

Joomla 4.0 Beta-2 default installation

**Comment by SharkyKZ** [comment]
Duplicate #30055. Please test with nightly builds: https://developer.joomla.org/nightly-builds.html.
