### ISSUE TITLE
[3.9] menu item alias always redirected from the menu

### ISSUE THREAD

**Issue by pulsarinformatique** [joomla/joomla-cms#30166]
Hi
in a site you  have a first url : /link-to-article 
plese create a menu item alias (/menu-item-alias) based on this first url

please set the REDIRECT toggle (in the alias menu item) to NO

both /link-to-article  and /menu-item-alias  do work  in front end

BUT  in the front end if we click on the menu item alias we are automatically redirected to /link-to-article

This shouldn't be

Thanks

Cyril

**Comment by SharkyKZ** [comment]
Expected behavior. Redirect option only decides whether to redirect to real menu item when alias is accessed directly. Menu module always points to real menu item.
