### ISSUE TITLE
[4.0] Webauthn image is 4359px x 3260px 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30180]
### Steps to reproduce the issue

view 3 images in https://github.com/joomla/joomla-cms/tree/4.0-dev/build/media_source/plg_system_webauthn/images

### Expected result

A small image optimised dimensions and file size 

### Actual result

4359px x 3260px !!

Performance tools show this as an overhead of over 200kb+ per image

![webauthn-black](https://user-images.githubusercontent.com/400092/88383616-be572680-cda2-11ea-88ab-1c8edc4e97b5.png)

### Additional comments

Maybe run a full repo image optimiser over all the new Joomla 4 images, as has been done over Joomla 1/2/3 images over the years ...

**Comment by brianteeman** [comment]
ouch - good spot

**Comment by Quy** [comment]
PR #30846
