### ISSUE TITLE
[4.0] Templates : Edit style - unsaved menu assignments

### ISSUE THREAD

**Issue by shim-sao** [joomla/joomla-cms#30182]
### Steps to reproduce the issue
Save a template style with menu assignments (4.0-beta-3-dev)

### Expected result
Template style saved with menu assignments

### Actual result
None of the menu assignments are saved

### System information (as much as possible)
Joomla 4.0-beta-3-dev - Linux - PHP 7.4.8 - MySql 5.7.28

### Additional comments

In the Administrator StyleModel.php function Save, replace in the 2 queries :

```
->whereIn($db->quoteName('checked_out'), [null, $userId])
```

by something like :

```
->where($db->quoteName('checked_out') .' IS NULL OR ' . $db->quoteName('checked_out') . ' = :userid')

->bind(':userid', $userid, ParameterType::INTEGER)
```

I think maybe there is something wrong in the query with `whereIn` php `null` and the mysql check `IS NULL`

`= NULL` or `IN (NULL)` may not work sometimes

`->where($db->quoteName('checked_out') . '= NULL')` => not work

`->whereIn($db->quoteName('checked_out'), [null])` => not work

**Comment by SharkyKZ** [comment]
Your fix is correct. Do you want to submit a PR?

**Comment by shim-sao** [comment]
Ok, thank you, it's done.

**Comment by Quy** [comment]
PR #30183 Thanks.
