### ISSUE TITLE
[4.0] Loading indicator for login screen?

### ISSUE THREAD

**Issue by Harmageddon** [joomla/joomla-cms#30186]
### Steps to reproduce the issue

1. Open the backend login screen.
2. Enter your credentials.
3. Press "Log in".

### Expected result
After clicking "Log in", while we wait for a response, something should indicate that there is ongoing work in the background.

### Actual result
Between clicking the button and receiving the answer that leads to either changing to the backend control panel, or to displaying an error message, nothing indicates that something is happening.

The login process is handled via AJAX in the background. Maybe due to my old laptop that has to run my local server, the time between request and response is high enough to be noticeable for me. It's not a big issue, but even after having used J!4 many times and having logged into the backend many times, I'm still irritated for a second every time I hit the log in button, thinking "Oh, nothing changes after clicking, I must have misclicked or made a mistake."

Can we maybe add a small indicator, like a loading circle or bar on or next to the button while the AJAX request is being processed?

**Comment by C-Lodder** [comment]
If I rightly remember, there is a PR to remove the Ajax functionality as it's of no benefit.

**Comment by ChristineWk** [comment]
@C-Lodder this one? https://issues.joomla.org/tracker/joomla-cms/29571<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30186">issues.joomla.org/tracker/joomla-cms/30186</a>.</sub>

**Comment by C-Lodder** [comment]
Yup, that's the one

**Comment by Harmageddon** [comment]
@C-Lodder @ChristineWk Ah, thank you! Wasn't aware of that one. I'm going to follow the discussion there.
I'd still like to leave this here open, because it is not clear from the PR whether it is actually going to be merged, or instead the AJAX mechanism should be optimized.

**Comment by brianteeman** [comment]
As the ajax login was removed I guess this can be closed
