### ISSUE TITLE
Problem with alternative layout (param option category_layout)

### ISSUE THREAD

**Issue by rolandalsace** [joomla/joomla-cms#30198]
Hi.

Joomla 3.9.20

It's seems that the alternative layout param is never user.

For exemple : 

1) for com_content category view, in the template i duplicate all the files blog*.* in the template folder /templates/my_template/html/com_content/categoy. with the new name blog1*.*

2) i change the layout in com_content / categories / option, tab Category to my template layout blog1

3) when i display the categorie, it's always the layout of name "blog" wich is used.

I think there is a problem in /librairies/src/MVC/View/CategoryView.php in lines 222, 226 where the : 
elseif ($layout = $category->params->get('category_layout'))
if is misplaced.

Perhaps it should be placed in the before level as else of the 
if (isset($active->query['layout']))

Others problems, this alternative layout blog1 defined in the template is not detected in com_content categories and category menu parameters ("choose a layout")

Regards.

**Comment by SharkyKZ** [comment]
Layout option in Category tab is used to set the default layout for categories that do not belong to any menu item. Categories that do belong to a menu item take the layout from the menu item. In this case you'd have to create a menu item of Articles -> Blog1 type.

Layout option in the menu item is meant for articles belonging to the menu item.

**Comment by joomdonation** [comment]
As explained by @SharkyKZ , this is expected behavior. The layout selected in active menu item has higher priority than the layout selected in the category itself.

I'm closing this issue as it is working as expected.
