### ISSUE TITLE
[4.0] - [API] User Groups and Access Levels should be accessible via API!

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#30203]
### Steps to reproduce the issue
There is NO API that let's us access the names of user groups and access levels for the site. com_content API returns the ID's of access level but there is no way to turn those ID's into readable text. This is also useful while creating new users and giving the ability to select User Groups for the user.

### Expected result
User Groups and Access Levels should be available via the API
Even if creation is not possible, it's fine but listing of ID's with names should be possible.

### Actual result
No such API exists!

### System information (as much as possible)
Joomla 4 Beta 2.

### Additional comments
If needed, most likely for @alikon

**Comment by alikon** [comment]
please test #30210

**Comment by chetanmadaan** [comment]
Testing now!

**Comment by chetanmadaan** [comment]
Confirmed. Works!
