### ISSUE TITLE
[3.9] Articles in different languages can't have same alias

### ISSUE THREAD

**Issue by SniperSister** [joomla/joomla-cms#30201]
### Steps to reproduce the issue
Configure a multilingual site and create an article with "testarticle" as alias. Assign it to language 1. Now create a second article, assign it to language 2 and use the same alias.

### Expected result
Article is created

### Actual result
Error is shown

### Additional comments
The exact same behavior works fine for menu items, so the CMS is behaving inconsistently here – that's why I would consider this as a bug.

**Comment by brianteeman** [comment]
Are they in the same category?

**Comment by infograf768** [comment]
The code prevents indeed to save articles with same alias in same category, whatever the language.
```
		if ($table->load(array('alias' => $this->alias, 'catid' => $this->catid)) && ($table->id != $this->id || $this->id == 0))
		{
			$this->setError(\JText::_('JLIB_DATABASE_ERROR_ARTICLE_UNIQUE_ALIAS'));

			return false;
		}
```

It would be interesting to allow saving, when multilingual is on AND the category is set to ALL languages, articles tagged to different languages with same alias. Will look at that. We must be sure there will not be any unwanted consequences.

**Comment by SharkyKZ** [comment]
Related https://github.com/joomla/joomla-cms/pull/28968.

**Comment by infograf768** [comment]
@SharkyKZ 
Indeed. That is what I meant by unwanted consequences.
Closing as already discussed.
