### ISSUE TITLE
[4.0] - [API] - Media Manager should be exposed via API!

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#30205]
### Is your feature request related to a problem? Please describe.
The com_content API returns the links for images used in the articles but if it's not possible to change to a different image than the API (atleast the update API) is of little to no use as it only allows removing the image from existing articles and via API we don't know what images are available in the media manager.

### Describe the solution you'd like
API for com_media and have a listing of all the images/folders as it's in the backend with ability to upload new and remove existing images.

### Additional context
Tagging @alikon @richard67 for suggesions.

**Comment by alikon** [comment]
i'm afraid i can't help here iirc mostly js/vue  code
cc @wilsonge

**Comment by Quy** [comment]
Duplicate #27244
