### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated - redux

### ISSUE THREAD

**Issue by terryburg** [joomla/joomla-cms#30215]
I think my issue is identical to #25834 but I thought that was resolved. Was it, or is that still forthcoming?

In my dev environment with all error reporting on I receive 

"Deprecated: Array and string offset access syntax with curly braces is deprecated in \libraries\vendor\joomla\string\src\phputf8\utils\unicode.php on line 46
Error: Failed to start application: Failed to start the session"

Code at line 46 is:  $in = ord($str{$i});

### System information (as much as possible)

Joomla 3.9.20 (an upgrade not fresh install)
PHP 7.4.8
WAMP on Windows machine

### Additional comments

Thank you.

**Comment by alikon** [comment]
it seems has been fixed in https://github.com/joomla-framework/string/releases/tag/1.4.3
ping  @HLeithner

**Comment by SharkyKZ** [comment]
This specific instance was fixed after 1.4.3 was released.

**Comment by alikon** [comment]
so we just need to tag a new 1.4.4 or ?

**Comment by HLeithner** [comment]
@wilsonge can you do the release on strings please?

**Comment by wilsonge** [comment]
done

**Comment by Quy** [comment]
@HLeithner OK to close per PR #31428?

**Comment by HLeithner** [comment]
Yes thx
