### ISSUE TITLE
Iconover never used in "custom" button function

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#30211]
### Problem identified
file:
[ToolbarButton.php](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Toolbar/ToolbarHelper.php)

seems the $iconOver created in 
https://github.com/joomla/joomla-cms/blob/6d0c5c06f69cf26e8261baeab812caa3a6eecf30/administrator/components/com_templates/src/View/Template/HtmlView.php#L250

	public static function custom($task = '', $icon = '', $iconOver = '', $alt = '', $listSelect = true, $formId = null)
	{
		$bar = Toolbar::getInstance('toolbar');

		// Strip extension.
		$icon = preg_replace('#\.[^.]*$#', '', $icon);

		// Add a standard button.
		$bar->appendButton('Standard', $icon, $alt, $task, $listSelect, $formId);
	}

### Open questions
How do we address this.  I'm not sure where/how it is/should be used.

**Comment by brianteeman** [comment]
$iconOver    The image to display when moused over.

**Comment by N6REJ** [comment]
> $iconOver The image to display when moused over.

correct, however, it doesn't & can't since the icon is never passed to the button.
Thats my point

**Comment by infograf768** [comment]
Indeed. Same in 3.x.
Useless param. It is a remaining of... Joomla 1.5...

**Comment by infograf768** [comment]
1.5
```
/**
	* Writes a custom option and task button for the button bar
	* @param string The task to perform (picked up by the switch($task) blocks
	* @param string The image to display
	* @param string The image to display when moused over
	* @param string The alt text for the icon image
	* @param boolean True if required to check that a standard list item is checked
	*/
	function custom( $task='', $icon=NULL, $iconOver='', $alt='', $listSelect=true ) {

		$icon 	= ( $iconOver ? $iconOver : $icon );
		$image 	= JHTML::_('image.site',  $icon, '/images/', NULL, NULL, $alt );

		if ($listSelect) {
			$message = JText::sprintf( 'Please make a selection from the list to', JText::_( $alt ) );
			$message = addslashes($message);
			$onclick = "javascript:if (document.adminForm.boxchecked.value == 0){ alert('".  $message . "');}else{submitbutton('$task')}";
		} else {
			$onclick = "javascript:submitbutton('$task')";
		}

		?>
		<td>
			<a class="toolbar" onclick="<?php echo $onclick ;?>">
				<?php echo $image; ?></a>
		</td>
		<?php
	}
```

**Comment by N6REJ** [comment]
then we should deprecate that option and remove all the existing $iconOvers from the toolbarhelper:: calls?

**Comment by infograf768** [comment]
OR add it into all possible occurrence of toolbar and modify the js to use it?

**Comment by infograf768** [comment]
I tested modifying
`ToolbarHelper::custom('template.cropImage', 'fas fa-crop', 'fas fa-crop', 'COM_TEMPLATES_BUTTON_CROP', false);`
by taking off one of the `, 'fas fa-crop'`

and the result is that the icon loses its opacity and can't be clicked i.e. disabled.

**Comment by infograf768** [comment]
It works again if I use
`ToolbarHelper::custom('template.cropImage', 'fas fa-crop', 'whatever', 'COM_TEMPLATES_BUTTON_CROP', false);`

weird...

**Comment by N6REJ** [comment]
where would the js be that creates the button?

**Comment by infograf768** [comment]
It also works fine with
`ToolbarHelper::custom('template.cropImage', 'fas fa-crop', '', 'COM_TEMPLATES_BUTTON_CROP', false);`

There are so many files concerned by toolbar that It's confusing.
Libraries/src/
![Screen Shot 2020-07-30 at 08 12 20](https://user-images.githubusercontent.com/869724/88887324-791c7400-d23c-11ea-81ba-c8b3cc150267.png)

Layouts
![Screen Shot 2020-07-30 at 08 14 21](https://user-images.githubusercontent.com/869724/88887470-bbde4c00-d23c-11ea-9fe0-ebe9fe2364d7.png)

The js is created in media/system/js/ (from build/system/js/)
![Screen Shot 2020-07-30 at 08 16 39](https://user-images.githubusercontent.com/869724/88887655-1b3c5c00-d23d-11ea-973a-99774b8f0b0f.png)

**Comment by N6REJ** [comment]
discussion moved to https://github.com/joomla/joomla-cms/pull/31211.  Going to need input on best solution.
