### ISSUE TITLE
[4.0] - [API] - Single User API pull doesn't return same results as Joomla backend.

### ISSUE THREAD

**Issue by chetanmadaan** [joomla/joomla-cms#30220]
### Steps to reproduce the issue
to a GET API request to:
{{base_path}}/api/index.php/v1/users/{userid}

You get a post with the users information

### Expected result
The actual result should include all the information that's visible in the backend including but not limited to:
Registration Date
Last Visit Date
Last Reset Date
Password Reset Count
Receive System Emails
User Status

The above are just for the account details tab. I don't if we want or should extend this to the other tabs such as Basic Settings.

### Actual result
The current results is:
```
{
    "links": {
        "self": "http://localhost/joomla4/api/index.php/v1/users/815"
    },
    "data": {
        "type": "users",
        "id": "815",
        "attributes": {
            "groups": {
                "8": 8
            },
            "id": 815,
            "name": "First Last",
            "username": "admin",
            "email": "someone@someone.com"
        }
    }
}
```

### System information (as much as possible)
Joomla 4 Beta 3

### Additional comments
tagging @alikon

**Comment by alikon** [comment]
please test #30239 

apart for

>  don't if we want or should extend this to the other tabs such as Basic Settings
