### ISSUE TITLE
[3.10] view templates folders in 3.10 vs 4.0

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#30226]
4.0 uses `/com_component/tmpl` folder while 3.9 and 3.10 `/com_component/views`

Will 3.10 has this behaviour preserved?

In this case a component can have `/views` folder with views for Joomla 3 and `/tmpl` for Joomla 4 (nice feature for 3 +4 compatibility).

**Comment by zero-24** [comment]
Hi,

what do you mean by `Will 3.10 has this behaviour preserved?`?

As far as I know you can still use the `old` component structure from 3.x in 4.x too.

**Comment by Denitz** [comment]
3.10 is supposed to have "Joomla! 4 compatibility layer"

I wonder if this layer will allow loading templates from /tmpl component folders automatically or not?

Currently, it's not. This helps to keep the separate view templates for both 3.10 and 4.x (/views and /tmpl) and we can support multiple J! versions in a single component.

But if this behaviour is changed in 3.10, we are wasting time now developing such multi-version support.

**Comment by HLeithner** [comment]
It's the way around, components that are working in J 3.10 will work in 4.0 too.
If everything from j4 would work in j3 we wouldn't need j4 ;-)
