### ISSUE TITLE
[4.0] COM_WORKFLOW_BASIC_WORKFLOW visible in initial Workflow Title

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#30229]
### Steps to reproduce the issue
Activate Workflows.
Go to Content - Workflows
"Basic Workflow" is visible.
Click on the workflow to go to the Edit screen.
Here you find "COM_WORKFLOW_BASIC_WORKFLOW", not "Basic Workflow". I can change and save this and everything works, but it is confusing 
First I thought it was a not translated String, but I think it is Initial SQL which is wrong.
The same happens with Basic Stage: "COM_WORKFLOW_BASIC_STAGE" is showing.
![screen shot 2020-07-30 at 07 50 33](https://issues.joomla.org/uploads/1/3a9cb962f4c2a587121c3c38241f1aed.png)
### Additional comments

![screen shot 2020-07-30 at 07 50 34](https://issues.joomla.org/uploads/1/7818a8e651035fc9a36e12b3ae1b70f3.png)

**Comment by infograf768** [comment]
If I remember well, remains to do for these what we have done for custom admin menus, i.e. show the translation below.

<img width="1231" alt="Screen Shot 2020-07-30 at 10 01 59" src="https://user-images.githubusercontent.com/869724/88897597-d8ce4b80-d24b-11ea-9498-fdb05f0fc0ff.png">

**Comment by infograf768** [comment]
Making patch now

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/30231

**Comment by infograf768** [comment]
@MartijnMaandag 
Please test patch.

**Comment by MartijnMaandag** [comment]
@infograf768 
Well I tried.
Installed patchtester. When I Apply the Patch I get "The patch could not be applied either due to missing connection to the server or missing patch on the server."
It takes to mutch time now, I will go on translating and correcting the Joomla4  helpscreens ;-)

**Comment by infograf768** [comment]
No p. it’s rtc now.
