### ISSUE TITLE
[4.0] Media: file and local not translated

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#30230]
### Steps to reproduce the issue
Install another Language (Dutch available: https://www.joomlacommunity.nl/downloads/joomla-4/90-nederlands-taalpakket-nl-nl-joomla-4-0-0-beta )
Go to Media and hit the Information i.
Select an image.
There are some items which can't be translated, I don't know if this is intentional.

**Comment by MartijnMaandag** [comment]
![screen shot 2020-07-30 at 08 41 10](https://issues.joomla.org/uploads/1/635dda3cce3aea99c346c6f7258bb485.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30230">issues.joomla.org/tracker/joomla-cms/30230</a>.</sub>

**Comment by infograf768** [comment]
I'm afraid these would be very difficult to translate. They are not translated in English either.
they are the root path `local-0:/` for the `item.directory` and `dir` or `file` for the `item.type` in the js and vue.

**Comment by chmst** [comment]
Maybe a stupid question, but is this an important information for the user? If not, we could remove it. Sometimes we show text or information which is redundant.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30230">issues.joomla.org/tracker/joomla-cms/30230</a>.</sub>

**Comment by infograf768** [comment]
I have a patch to translate `dir` and `file`.
local can't be translated and should not anyway.
See https://github.com/joomla/joomla-cms/pull/30243
