### ISSUE TITLE
Can't upgrade v 3.9.20 to 3.10 Alfa

### ISSUE THREAD

**Issue by fgonc124** [joomla/joomla-cms#30235]
### Steps to reproduce the issue

I changed Joomla component Update options to "Testing" and minimum to "Alfa"

### Expected result

I expected to get a message to uograde to 3.10 Alfa

### Actual result
I get this message "You already have the latest Joomla version, 3.9.20."

### System information (as much as possible)

Linux
Joomla 3.9.20
PHP 7.3
MySQL 5.6.43 (PDO)

### Additional comments
I forced the upgrade using zip file and it worked. But don't hav3 Pre-pgrade check" component

**Comment by ChristineWk** [comment]
> I changed Joomla component Update options to "Testing" and minimum to "Alfa"

I think, you have to use Update Channel: Custom URL & https://update.joomla.org/core/nightlies/next_minor_list.xml

**Comment by fgonc124** [comment]
Thanks

With that change it points to https://developer.joomla.org/nightlies/Joomla_3.10.0-alpha2-dev-Development-Update_Package.zip	.

I wanted Joomla_3.10.0-alpha1-Alpha-Update_Package.zip
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30235">issues.joomla.org/tracker/joomla-cms/30235</a>.</sub>

**Comment by richard67** [comment]
@fgonc124 @ChristineWk The custom URL mentioned above is for the nightlies. For 3.10 releases (including alphas, betas, ...) there is no dedicated update channel yes, as far as I know, so you indeed have to download the zip and use the "Upload & Update" tab of the Joomla Update component.

@zero-24 Please confirm if I'm right or correct if I'm wrong.

**Comment by ChristineWk** [comment]
You mean this steps here: https://www.joomla.org/announcements/release-news/5816-joomla-4-0-0-beta3-and-joomla-3-10-alpha1.html:
Go to the Joomla Update Component Options and switch the Update Channel to “Testing” and the Minimum Stability option to “Alpha”.
Update to 3.10 alpha1 using the Joomla Update Component.

https://github.com/joomla/joomla-cms/releases/tag/3.10.0-alpha1

So sorry, as I'm using the Nightlies. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30235">issues.joomla.org/tracker/joomla-cms/30235</a>.</sub>
@richard67 Yes, I saw it afterwards :-)

**Comment by richard67** [comment]
@ChristineWk @fgonc124 Ah, maybe I am wrong indeed, and it is enough to change minimum stability. Let's see what @zero-24 sais. I am not 100 % sure right now.

**Comment by fgonc124** [comment]
I followed the "https://www.joomla.org/announcements/release-news/5816-joomla-4-0-0-beta3-and-joomla-3-10-alpha1.html" and that does not work

Using the custom URL mentioned above , I get https://developer.joomla.org/nightlies/Joomla_3.10.0-alpha2-dev-Development-Update_Package.zip .

If I update using the alpha2-dev link, I get the "Pre-Upgrade check" component.

If I use the zip file from https://github.com/joomla/joomla-cms/releases/tag/3.10.0-alpha1 I don't get the "Pre-update check" component

THanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30235">issues.joomla.org/tracker/joomla-cms/30235</a>.</sub>

**Comment by zero-24** [comment]
Seems I have missed that chagne from the updater files. I have just added this change here to the update server: https://github.com/joomla/update.joomla.org/pull/175

Now there is the update showed up when you have the following configuration:
![image](https://user-images.githubusercontent.com/2596554/88956783-296e9480-d29e-11ea-8b91-1e57299fb4d5.png)

![image](https://user-images.githubusercontent.com/2596554/88956812-35f2ed00-d29e-11ea-8a40-5748fdd417a2.png)

> If I update using the alpha2-dev link, I get the "Pre-Upgrade check" component.

Updating from 3.9.x to 3.10.0-alpha1 does not show the Pre-Update-Check. This is something that we added with 3.10 so this only shows up starting from 3.10 and when updating from 3.10 to 4.x

**Comment by richard67** [comment]
@zero-24 Thanks a lot, you are the best.

 @fgonc124 Could you check if it works now for you, and if yes, close this issue? Depending on your webserver and servers on the way it may take a while until you see the update due to cached XML files.

**Comment by fgonc124** [comment]
Until now I get the same message "You already have the latest Joomla version, 3.9.20."![screen shot 2020-07-30 at 18 38 15](https://issues.joomla.org/uploads/1/8153ac135f649767a05a077b450d85ff.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30235">issues.joomla.org/tracker/joomla-cms/30235</a>.</sub>

**Comment by fgonc124** [comment]
I will try later<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30235">issues.joomla.org/tracker/joomla-cms/30235</a>.</sub>

**Comment by richard67** [comment]
@fgonc124 What happens if you go to Extensions - Manage - Update, use the "Clear Cache" button and then check in Joomla Update component again for updates using the "check for updates" button? Funny detail, but also the core updates are cached in database with the mechanism of the extensions installer ;-)

**Comment by zero-24** [comment]
Did you hit the 'check for updates' button in com_joomlaupdate?

**Comment by fgonc124** [comment]
zero-24 Of course hit the 'check for updates' button in com_joomlaupdate

I also cleared the cache.

richard67 I get the same message.![screen shot 2020-07-30 at 18 48 42](https://issues.joomla.org/uploads/1/17a7ee498b421b523f03b69c834d12b6.jpg)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30235">issues.joomla.org/tracker/joomla-cms/30235</a>.</sub>

**Comment by fgonc124** [comment]
Am I the only one having this problem?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30235">issues.joomla.org/tracker/joomla-cms/30235</a>.</sub>

**Comment by zero-24** [comment]
hmm it is working on my side for sure. Can you try to access the updater XML directly in the browser: https://update.joomla.org/core/test/list_test.xml and check that this line is in there?

![image](https://user-images.githubusercontent.com/2596554/88962511-d220f200-d2a6-11ea-8d35-9f2cd2a61356.png)

When you cleaned the update cache in joomla I can only think of an CDN cache issue.
Can you also check that the core update server is not unpublished (Extensions - Manage - Updatesites)

**Comment by richard67** [comment]
@zero-24 @fgonc124 I can reproduce the problem on a current, clean staging branch, which has version "3.9.21-dev". No update found after update channel has been changed to "Testing" and minimum stability to "Alpha" or "Development". In the browser the XML looks as you show above, and the extension_test.xml with the updates doesn't look wrong to me either, but maybe I am blind.

**Comment by richard67** [comment]
Ok, with staging = "3.9.21-dev" the `targetplatformversion="3.9.20` will not match. Have to test later with a true 3.9.20.

**Comment by zero-24** [comment]
Ah ok will update the updateserver to `targetplatformversion="3.9"` than please give me and the cache a few minutes.

**Comment by richard67** [comment]
@zero-24 Cool, sounds good, that helps with the "-dev" versions.

But I have tested meanwhile on a copy of my private website on shared hosting, a true 3.9.20, and I am offered the update with the 3.10.0-alpha1. I did that some 1 or 2 minutes ago and assume you haven't changed the XML yet. I had update channel = Testing and min. stability = Development.

@fgonc124 So for me it seems to work with a 3.9.20.

**Comment by zero-24** [comment]
I have just pushed the changes here: https://github.com/joomla/update.joomla.org/pull/176 can take up to 10 minutes until the CDN's are updated.

**Comment by richard67** [comment]
@zero-24 I have just tested your change, it was already available here and now it works with 3.9.21-dev, too. Thanks.

**Comment by fgonc124** [comment]
Zero-24 I see this
![image](https://user-images.githubusercontent.com/26040543/88978203-26cc6900-d2b7-11ea-8519-ec08e627c2b8.png)

Is diferent from what ou see

**Comment by ChristineWk** [comment]
@fgonc124 
Yes, because: 

> 
> 
> Ah ok will update the updateserver to `targetplatformversion="3.9"` than please give me and the cache a few minutes.

**Comment by fgonc124** [comment]
Hi

I keep seeing the wrong xml file

![screen shot 2020-07-31 at 08 23 24](https://issues.joomla.org/uploads/1/e34bfaaf12a86989d3ba164236afecf3.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30235">issues.joomla.org/tracker/joomla-cms/30235</a>.</sub>

**Comment by richard67** [comment]
@fgonc124 It's correct with respect to the last correction, which @zero-24 's screenshot did not show yet: the third extenion from bottom has targetplatformversion="3.9" and offers the "3.10.0-aplha1" update. Before the last change it was targetplatformversion="3.9.20", that you can't see anymore of course, but the changed and correct record is there in your screenshot.

**Comment by fgonc124** [comment]
Richard I don't want to bother you with this subject. I'm not understading what xml should report.

Zero24 xml file showed version="3.10.0-alpha1" targetplatformversion="3.9.20

mine shows version="3.10.0-alpha1" targetplatformversion="3.9

Which one is correct?

I installed joomla on my pc with Wamp and I can't upgrade also. I get the same xml.

**Comment by richard67** [comment]
@fgonc124 It should be clear from the comments above:

First I noticed that the targetversion is not suitable for development versions like e.g. 3.9.21-dev in this comment here [https://github.com/joomla/joomla-cms/issues/30235#issuecomment-666610358](https://github.com/joomla/joomla-cms/issues/30235#issuecomment-666610358).

Then @zero-24 said he corrects this in his answer here: [https://github.com/joomla/joomla-cms/issues/30235#issuecomment-666612882](https://github.com/joomla/joomla-cms/issues/30235#issuecomment-666612882).

This correction has changed the XML in the way as I've described it in my previous comment.

So what's not understandable with that?

**Comment by richard67** [comment]
Sorry, had to correct the links in my previous comment, so in the first email notification they were wrong. But now they are correct.

**Comment by fgonc124** [comment]
Richard. I'm just trying to learn. I thought that targetplatformversion should be  targetplatformversion="3.9.20"

**Comment by richard67** [comment]
@fgonc124 "3.9.20" covers exactly that version. "3.9" covers any 3.9.x version, from 3.9.0 to whatever will come. As it shall be possible to update any 3.9.x version to 3.10, the change of the targetplatformversion to "3.9" is correct. Finally, just to complete the explanation on how it works: "3" would cover all "3.x.y" versions.

**Comment by fgonc124** [comment]
Richard thank you

 I can't upgrade. 

Don't waste your time.  Can't understand why this does not sugest 3.10 Alpha 1.

I have the problem  with my host server and with local installion

I'll try another aproach. If I have success I let you know

Thanks

**Comment by fgonc124** [comment]
Richard.
 I was using my company network wich has proxy server. I disconnect from network and accessed to a hotspot and now this works.

Using wifi connection I get this

![joomlaupd_03](https://user-images.githubusercontent.com/26040543/89029835-25d32000-d327-11ea-9ca5-ee3d354fdf1b.JPG)


Thanks for your help

**Comment by richard67** [comment]
@fgonc124 That's why I don't like proxies ;-)
