### ISSUE TITLE
PHP print only one row

### ISSUE THREAD

**Issue by bulalalie** [joomla/joomla-cms#30232]
### Steps to reproduce the issue
I write PHP script to tracerout some IP addr on  article but only print one raw output. On the other hand,I copy the script to other PHP environment , it display all rows.

It cloude display one row so my script is working.
### System information (as much as possible)
this is my PHP script
![screen shot 2020-07-30 at 09 53 43](https://issues.joomla.org/uploads/1/c40396e868b311716772ac8482affbac.png)

**Comment by infograf768** [comment]
Please use the forum for such questions. This is not Joomla core related.
closing
