### ISSUE TITLE
[4.0] 'onAfterRenderModules' doesn't allow buffer modification

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#30244]
### Steps to reproduce the issue

Register own handler for `onAfterRenderModules` event and try to modify the `$buffer` passed as first argument.

### Expected result

`$buffer` is passed by reference in event trigger and should be allowed to be modified by plugins.

### Actual result

No modifications are applied because we can't access `Joomla\Event\Event` argument by reference.

### Additional comments

Either `Joomla\Event\Event` should allow argument modifications by reference, or `onAfterRenderModules` event should use object argument with buffer property returned by `ModulesRenderer::render()` (but this breaks BC).

**Comment by Denitz** [comment]
Actually all events with non-object arguments passed by reference are affected.

**Comment by SharkyKZ** [comment]
I think you have to use event's `setArgument()` method to set the new value. Like here:

https://github.com/joomla/joomla-cms/blob/c91326ced947a2109d9cb1a178034b0e78f74c4f/plugins/quickicon/joomlaupdate/src/Extension/Joomlaupdate.php#L142

**Comment by Denitz** [comment]
Yes, looks like working!
