### ISSUE TITLE
Update Patchtester

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#30257]
### Steps to reproduce the issue
Got Information for Update to: Joomla Patchtester 4.0.0-rc3

### Expected result
Update was successful, but error message:

### Actual result
An error has occurred. 1146 Table 'xyz_patchtester_pulls_labels' doesn't exist

### System information (as much as possible)
Joomla CMS 
Joomla! 4 Content Management System. 
Site 
File 
No Problems 
4.0.0-2020-05-29 
‎4.0.0-beta4-dev 
Joomla! Patch Tester 
Component for pull request management testing 
Administrator 
Component 
No Problems 
4.0.0 
‎4.0.0-rc3 

### Additional comments
It's not possible to use Patchtester now.

But I think, found the reason for: https://github.com/joomla-extensions/patchtester/releases:

Update warning

Any previous installation of the Joomla! Patch Tester must be uninstalled as this release contains some major changes due to the addition of showing Github labels.

Prior to uninstalling you may want to make a backup of your Github token so it is easy to restore it.

But why is there no "Pre-warning"?
Will try to install completely new.

**Comment by Quy** [comment]
Please post issue to https://github.com/joomla-extensions/patchtester. Thanks.

**Comment by ChristineWk** [comment]
sorry about. Thanks. https://github.com/joomla-extensions/patchtester/issues/290
