### ISSUE TITLE
[4.0] SearchTools Clear button with date field remains disabled

### ISSUE THREAD

**Issue by heleneross** [joomla/joomla-cms#30270]
### Steps to reproduce the issue
On banners / tracks page in admin open filter options and select a date (but leave all the combo boxes empty) the clear button remains greyed out/disabled
Even after pressing the Enter key to submit the form it remains disabled

### Expected result
Clear button is enabled

### Actual result
Clear button remains disabled

### System information (as much as possible)
Joomla! 4.0.0-beta3-dev
PHP 7.3.8
running on localhost
Chrome 84.0.4147.89
Safari 13.1.2

**Comment by brianteeman** [comment]
Cannot replicate - probably fixed elswehere

**Comment by brianteeman** [comment]
Can someone please close this as stated above or if I am wrong then update the issue.

**Comment by Quy** [comment]
It is reproducible.

![30270](https://user-images.githubusercontent.com/368084/152701196-6d86f45a-246f-4fac-9cb5-2ae99839f551.png)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38089 . Thanks in advance.
