### ISSUE TITLE
[4.0] Accessibility Icon in System - Additional Accessibility Features 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#30277]
### Steps to reproduce the issue
Open the Plugin. 
In the bottom right corner is a wheelchair icon. 

![screen shot 2020-08-04 at 16 19 31](https://issues.joomla.org/uploads/1/851c3174645f9225b664d79ace90ca73.png)

This maybe should signal accessibility 
but the official icon for that is fa-universal-access, not the wheelchair

![screen shot 2020-08-04 at 16 19 46](https://issues.joomla.org/uploads/1/4e619cd44e4458f359cee8904001b732.png)

**Comment by richard67** [comment]
I remember that icon from an other issue and think it is generated by the browser, if I remember right (not 100 % sure but some 99 %). So we might not really be able to influence it.

**Comment by chmst** [comment]
Thank you. I'll close this and try to contact the right instance.

**Comment by brianteeman** [comment]
You can easily change the icon and it is documented here https://ranbuch.github.io/accessibility/#icon-image

However I _think_ you are mistaken about an official icon for accessbility - This is the official icon see  http://www.riglobal.org/wp-content/uploads/2016/03/RI-Fact-Sheet-Symbol-of-Accessibility.pdf

**Comment by brianteeman** [comment]
@richard67 sorry not 99% right but 99% wrong ;)

**Comment by richard67** [comment]
I see. Well at least it's not Joomla.

**Comment by richard67** [comment]
@chmst If we can change the icon as Brian linked in his comment above, maybe reopen the issue?

**Comment by chmst** [comment]
@brianteeman about "official" - I have seen several attempts in this direction and thougt that this "da Vinci" won. Of course, everyone knows what the wheelchair icon means but in our context, the wheelchair itself is no handicap.

**Comment by brianteeman** [comment]
AFAICT the only "official" icon is the one currently in use. The one you propose here is an os-x icon for universal access. There is also a _proposed_ icon http://accessibleicon.org/ but I've not seen any update there for  several years. I dont really care what icon is used as I'm not a a fan of any type of badge. Of the three they all have merits.  I have linked to the instructions for how to change it

**Comment by chmst** [comment]
It is not a Joomla issue. So I close this
