### ISSUE TITLE
[4.0][a11y][UX] Administrator login page frozen with JSON.parse error after session time out in Chrome

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#30274]
### Steps to reproduce the issue
Install 4.0.0-beta4-dev with default settings.  
Login to the back end and enable the plugin System - Additional Accessibility Features. 
Set 'Site Section' to 'Administrator (Back End)'.
Log out.
Wait until the session has timed out after 15 minutes.
Type in username and password, click 'Log in'.

### Expected result
The page displays a message "Your session has timed out.  Please reload or refresh the page to continue."

### Actual result
The login request is not sent and no error message is displayed.
The javascript Console shows JSON.parse error: Uncaught SyntaxError: Unexpected token < in JSON at position 0 

### System information (as much as possible)
Joomla 4.0.0-beta4-dev of 4 August on Wampserver 3.2.2 and PHP 7.4.8
Google Chrome v84 - error
Microsoft Edge v84 - no error
Firefox v79 - no error

### Additional comments
![screen shot 2020-08-04 at 15 12 37](https://issues.joomla.org/uploads/1/3d8095b05653c755c7bf2d7cd86a54e8.jpg)

Javascript JSON.parse error:
Uncaught SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at onSuccess (admin-login.min.js?8ab02e6f440297c5c60ef859413a6b42:1)
    at XMLHttpRequest.d.onreadystatechange (core.min.js?8ab02e6f440297c5c60ef859413a6b42:1)

This error occurs only when the plugin System - Additional Accessibility Features is enabled.
A meaningful message should be displayed instead of a frozen login page.  
This is an important UX consideration for those webmasters who need the Accessibility features.
****

**Comment by brianteeman** [comment]
I can not replicate this. Perhaps it was solved when the ajax login functionality was removed. Are you able to retest please

**Comment by Fedik** [comment]
this can be closed, there is no `JSON.parse` anymore #29571
