### ISSUE TITLE
[J3.9.20] Improve UX of changing articles (or other items) in Menuitem

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#30289]
_my obligatory disclaimer for this weeks issues :-)_
I am currently teaching a class of kids in working with Joomla. So here and there always the same mistakes happen where we can learn from. If a new user comes into such situations the frustration can be high. But we can help them not to make such mistakes.

### What needs to be fixed
If you open a menu item where an article is already connected to you have the possibility to edit or clear. There is a soooo often mistake that the user clicks on edit to select another article.

### Why this should be fixed
To avoid users overwriting their existing contents because they think they create a new one here
To Avoid users to make a wrong click

### How would you fix it
Maybe having different labels if possible.
"Edit Article" and "Clear to relink" or similar? Any other idea to improve that?

**Comment by brianteeman** [comment]
I dont see how it could be any clearer. The fact that when you click on edit and get an article full of content that you would have to erase should make it obvious you are not creating something new.

I think the problem you are facing is two fold
1) are they actually creating articles with content or just the headings for now with a view to adding content later
2) a matter of education that joomla is not wordpress and that a menu item is not an article but a link to an article

**Comment by coolcat-creations** [comment]
For some people edit is the same task as change. So if the button says edit I also would expect to edit the link and not the article because I am In the menu item. 
Best solution would be to have a edit article and change link button instead of „clear“ why do we force two clicks here to select something new?

**Comment by brianteeman** [comment]
> why do we force two clicks here to select something new?

No idea - it does seem strange but maybe I need more coffee

**Comment by infograf768** [comment]
Clear may also be used to really Clear and not Change. For example in Associations if we do not want an item to be anymore associated.

**Comment by brianteeman** [comment]
Then it should not be using the same field

**Comment by coolcat-creations** [comment]
> Clear may also be used to really Clear and not Change. For example in Associations if we do not want an item to be anymore associated.

Would be good to have a change button there too, it does not make sense to clear an article because the menu item cant be saved anyway without an association.

**Comment by infograf768** [comment]
> it does not make sense to clear an article because the menu item cant be saved anyway without an association.

It makes real sense to totally clear an association if not desired. We need the clear button, at least for Associations. Clearing there totally clears the former associated item in the association table.

It indeed does make sense to only have a Change article (a variation of Select in fact) when we edit a Single Article menu item.

> Then it should not be using the same field

It can use the same field, once modified as I have done here.

I prepared a patch here which does not touch the associations as I do add an element in the field

I get for an existing id

<img width="1120" alt="Screen Shot 2020-08-07 at 12 41 47" src="https://user-images.githubusercontent.com/869724/89638111-8cb68300-d8ab-11ea-96b2-fa78d7515e1f.png">

For a new menu item
<img width="1160" alt="Screen Shot 2020-08-07 at 12 42 20" src="https://user-images.githubusercontent.com/869724/89638189-ace64200-d8ab-11ea-88a5-f75f0695a19b.png">

And I keep for associations

<img width="1494" alt="Screen Shot 2020-08-07 at 12 21 34" src="https://user-images.githubusercontent.com/869724/89636372-cd60cd00-d8a8-11ea-8a19-cdb72e46afb2.png">


This can be done for other items too.
It is only useful when the field is required evidently, which is the only case concerned here in core for articles. So it is B/C.

Here is a zip of the .diff. Can make PR if desired.
[j4_change.diff.zip](https://github.com/joomla/joomla-cms/files/5040950/j4_change.diff.zip)

**Comment by ssnobben** [comment]
Thks Coolcat-creations for making UX/UI user tests for improving & understanding Joomla. Cool! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30289">issues.joomla.org/tracker/joomla-cms/30289</a>.</sub>

**Comment by infograf768** [comment]
In fact this proposed PR in the zip above is for 4.0-dev, but can do same for 3.x
@HLeithner What you think?

**Comment by HLeithner** [comment]
I hate the current behavior so much I'm full in favor adding the select button again. But I'm not alone.
Not sure why we need a 'change' button and extra acl for it?

**Comment by infograf768** [comment]
Explained in private we need a new button because of the `hidden` class.
Making now PR for J4. Then can be decided if we backport.

**Comment by infograf768** [comment]
Closing. Please test https://github.com/joomla/joomla-cms/pull/30331
