### ISSUE TITLE
Options tab display in Tags - Admin template

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#30285]
### Steps to reproduce the issue
Go to Components - Tags 
Edit an existing Tag or create a new.
Go to the Options TAB.
![screen shot 2020-08-05 at 12 05 27](https://issues.joomla.org/uploads/1/85a63d6537fbb3f78ba81dc798822682.png)

**Comment by Quy** [comment]
Duplicate #29254
See PR #29706

![30285](https://user-images.githubusercontent.com/368084/89417231-444c6900-d6e3-11ea-9df4-366438ea10b4.png)
