### ISSUE TITLE
Global configuration wipes out settings for a given component

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#30282]
### Steps to reproduce the issue
1. Open your favourite database editor
2. Open the table `#__extensions`
3. Filter the list on `name = 'com_users'`
4. Copy-paste the content of the `params` column into your favourite editor
5. Checkout the `4.0-dev` branch
6. Run `npm install`
7. Login to backend
8. Go to Users -> Manage
9. Click on the Options
10. Open tab `Password options`
11. Set Minimum Length to 4 by typing in 4 into the field
12. Click on Save
13. See the Success message and the Minimum Length changed back to 12
![image](https://user-images.githubusercontent.com/359377/89392255-94d6bd00-d709-11ea-9a5e-539987af8e2a.png)
13. Go back to your database editor
14. Reload the table
15. See that the `params` column is empty. Your settings have been wiped.

### Expected result
An error that the minimum length must be at least 12

### Actual result
A success message and my settings wiped

### System information (as much as possible)
Joomla 4.0 git checkout

### Additional comments
This is caused by several issues:
1. https://github.com/joomla/joomla-cms/blob/d7451e644001e6fbdb85abf0c87c9c34bae2602c/administrator/components/com_config/src/Controller/ComponentController.php#L112
On this line it false states that the messages are enqueued by the validate method. The validate method doesn't queue messages.
2. https://github.com/joomla/joomla-cms/blob/d7451e644001e6fbdb85abf0c87c9c34bae2602c/administrator/components/com_config/src/Controller/ComponentController.php#L119
On this line we set the redirect but we don't actually perform the redirect so it continues saving the result. The result is actually false. This causes the data wiping.

**Comment by brianteeman** [comment]
> An error that the minimum length must be at least 12

Why would that be expected?

**Comment by brianteeman** [comment]
Ah I see the problem


```
		<field
			name="minimum_length"
			type="number"
			label="COM_USERS_CONFIG_FIELD_MINIMUM_PASSWORD_LENGTH"
			min="8"
			step="1"
			default="12"
			validate="number"
		/>
```

The min of 8 only applies to the up/down arrows on the field and you can still type 4
The validation is only that its a number and not that it 8 or more

**Comment by brianteeman** [comment]
The same error happens on other fields which have a maximum value and you type a value greater than that

**Comment by roland-d** [comment]
This was just a "lucky" find. The real issue is the failing of the form validation causing the system to store an empty value in the `params` field. Combined with a success message, a user may think that all is dandy.

**Comment by chmst** [comment]
I am in doubt about accessibility of this kind of input field. Why not use the dropdowns?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30282">issues.joomla.org/tracker/joomla-cms/30282</a>.</sub>

**Comment by roland-d** [comment]
@chmst That is another discussion and not relevant to this issue. This behavior can be found with any configuration option that fails form validation. I am just using this one as it shows how to reproduce the issue.

**Comment by Bakual** [comment]
> I am in doubt about accessibility of this kind of input field. Why not use the dropdowns?

It's a native HTML5 element, nothing we invented ourself. I wouldn't expect accessibility issues with that by itself.

**Comment by richard67** [comment]
>        On this line we set the redirect but we don't actually perform the redirect so it continues saving the result. The result is actually false. This causes the data wiping.

@roland-d Can it be there is just a `return false;` missing after the `$this->setRedirect(...);`? I've had a similar issue at another place in past and fixed it that way.

P.S.: Same at other places, e.g. if we catch an exception when writing fails.

**Comment by roland-d** [comment]
@richard67 As far as I saw, we need to redirect at this point but just adding that is not enough because there are no messages queued.

**Comment by SharkyKZ** [comment]
Use `$model->getError()` to get the message. Although there are some other issues like not storing/loading values from user state after validation fails.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/31105.
