### ISSUE TITLE
[3.9.20] - Admin Module Order is not working inside Custom Module

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#30286]
### Steps to reproduce the issue
- Go into the backend to Modules and select the context Administrator
- Create a new Custom Module and save (apply) it
- Change the Order of the field to be shown on first place (the dropdown says actually that it
's at the top
- Save and close

### Expected result
The module should be at the top

### Actual result
The module is not at the top and you can't select the order inside the module, you have to order it by module order

### System information (as much as possible)

J 3.9.20

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24

**Comment by coolcat-creations** [comment]
Hi Brian, did you test if it really does not apply anymore before closing ?

**Comment by brianteeman** [comment]
Yes of course, unlike others I do actually read and test. I followed your exact instructions in joomla 4 and the order works as expected.

![image](https://user-images.githubusercontent.com/1296369/187068967-c313b9e4-74bd-4be1-a2ef-4b81c6b0cd41.png)

![image](https://user-images.githubusercontent.com/1296369/187068971-9cfb93a9-c3d1-40f3-ac47-d3052668b8fd.png)

**Comment by coolcat-creations** [comment]
Thank you, that was not clear from the message before for me.

**Comment by coolcat-creations** [comment]
I made some testing in the last days too, maybe it helps: https://docs.google.com/spreadsheets/d/1yo4cRfs7iM1FoyF0zmBhRnj28hC9ell5GFKKEcblExc/edit#gid=0 I see that you tested a lot of those too @brianteeman

**Comment by brianteeman** [comment]
Thanks - didnt know about that. But I'm not doing any more

**Comment by bembelimen** [comment]
This problem still exists for me:

![grafik](https://user-images.githubusercontent.com/1229869/187077449-c2b46699-e384-4176-87f0-3ad23cbb355e.png)

![grafik](https://user-images.githubusercontent.com/1229869/187077466-4a702cdb-d66d-44b9-b5ef-c3671a9fcfb7.png)

**Comment by brianteeman** [comment]
ah I think I see the problem and why we are seeing different things. The problem is with the installation data not setting an order for the modules. I had moved modules before this test using drag and drop and that forces the real order to be saved.

## Example
Clean Install
![image](https://user-images.githubusercontent.com/1296369/187079968-43fccba1-b858-459a-8b93-f183dc5aef23.png)

After a single drag and drop
![image](https://user-images.githubusercontent.com/1296369/187080034-c0397d67-96dd-41f4-852c-fcf2ed2d4203.png)

**Comment by brianteeman** [comment]
So this only effected modules in the cpanel position and only if you had not previously changed the order of the mdoules. 

There is a pr now for testing #38633
