### ISSUE TITLE
[4.0] Installation - wrong error-alert after installation

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#30299]
### Steps to reproduce the issue
On the newest version of j4.0 the minimum password length is 12 characters. 

Start a fresh installtion.
Enter a password for your super user with less than 12 characters.
Click on install.
An error-alert concerning the database and a warning concerning the password length appear.
Enter a 12-character password
Click installation
An error alert "Installation failed" appers.

But the installation is made corrctly.

### Expected result
A warning that the password is too short and a red bordered password field.

Also expected: after entering a long password, the installation runs as usual.

### Actual result
![screen shot 2020-08-06 at 08 20 52](https://issues.joomla.org/uploads/1/7e20e1723859636f68eed10156b5bdef.png)

The warning is expected but the error alert is somehow misleading and probably scares novice user :)

### System information (as much as possible)
Newest version

### Additional comments
Working on win10, xampp, mariaDB

**Comment by chmst** [comment]
Comment: Adding the Information (12 chars minimum) to the password description would help.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30299">issues.joomla.org/tracker/joomla-cms/30299</a>.</sub>

**Comment by brianteeman** [comment]
You can change the text to
Set the password for your Super User account (minimum 12 characters)

But that will still leave the vaildation to be fixed

**Comment by brianteeman** [comment]
The error alert has been restyled so shouldnt be as confusing. It is now much clearer that there are actually two error messages being displayed

**Comment by chmst** [comment]
Cloing this issue as the message is clear now
