### ISSUE TITLE
Custom registration Email step needs to be added

### ISSUE THREAD

**Issue by miladox** [joomla/joomla-cms#30293]
I need an extra email step in registration.
after user registered, once user clicks on joomla registration validate link in their email. i want them to get an other (1 more email to be added) email too.

so when user registers gets an email with validation link (which joomla already has) > then after clicking on that they get another email which i will customize the body later (this part i need to be added)

can someone help me please ?

**Comment by brianteeman** [comment]
Please use the forum https://forum.joomla.org
