### ISSUE TITLE
 Auto Logout/ Session timeout is not working in JOOMLA 3.6.4

### ISSUE THREAD

**Issue by Rajanshrgill1355** [joomla/joomla-cms#30296]
I have trouble making my admin panel automatically logout once session is expired. Currently the session logout time is set to 5 minutes but it did not automatically redirect to login page and i am having troubling finding solution for the same. 

A little help from a genius mind will be appreciated.  

Cheers

**Comment by toivo** [comment]
Joomla 3.6.4 was released almost four years ago and its End of Life 3.6 was on 25 April, 2017, when the first version of Joomla 3.7 was released.  

Please create a topic in the Joomla! Support Forum at [General Questions/New to Joomla 3.x](https://forum.joomla.org/viewforum.php?f=706).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30296">issues.joomla.org/tracker/joomla-cms/30296</a>.</sub>
