### ISSUE TITLE
[3.9.20] Sample Data is not localized and different structure than regular Joomla

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#30292]
### What needs to be fixed
The Sample Data module and the contents are not localized in de-DE (is this an issue towards Jgerman?)
Additionally the Home item is not Featured items like in install sample data, it should be the same in both.

### Why this should be fixed
Because not experienced users, like for example kids that start to learn a CMS are not that good in english yet to understand. We need to get them on board.

### How would you fix it
Localize it :-)

**Comment by infograf768** [comment]
For the translation of the Blog Sample Data plugin, it depends on the German Translation Team. Not core related.

That Blog Sample Data plugin adds a blog as its title says (+ some other menu items). It does not create a Home page. It is totally different from the sample_blog.sql at install time. It was designed this way.

**Comment by infograf768** [comment]
@zero-24 for what concerns translation of the plugin.

**Comment by zero-24** [comment]
As for the German Translation this is a `known problem` and tracked here: https://github.com/joomlagerman/joomla/issues/851

**Comment by zero-24** [comment]
I just come accross this ticket again and will close here in reference to the ticket at our repo: https://github.com/joomlagerman/joomla/issues/851 as this is not a core problem but on us / JGerman who did not translated that plugin / files yet.
