### ISSUE TITLE
[4.0] User menu -> Accessibility Settings: doesn't show accessibility settings

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#30295]
### Steps to reproduce the issue
User menu (in the top - right edge of the control panel) -> Accessibility settings show only the user profile without accessibilty settings

### Expected result
![screen shot 2020-08-05 at 17 12 00](https://issues.joomla.org/uploads/1/b449519fcee64edf5df3a973e958e4ec.jpg)

### Actual result
![screen shot 2020-08-05 at 17 09 39](https://issues.joomla.org/uploads/1/9b4bad76b655de03e61e20bcfab5d3eb.jpg)

### System information (as much as possible)
Joomla 4.0.0beta, PHP 7.3

**Comment by alikon** [comment]
confirmed

**Comment by Quy** [comment]
See PR #29226

**Comment by brianteeman** [comment]
I already reported this as broken

**Comment by brianteeman** [comment]
See original report #30217
