### ISSUE TITLE
[4.0] Wrong colors for image field Clear button

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#30300]
### Steps to reproduce the issue
Edit article => Image and Links
Edit Category=> Options

### Actual result
The Clear button X is hardly visible: background and color are variations of reds.
Color is `color: #c52827;`
Background is: `background-color: #a32120;`

<img width="729" alt="Screen Shot 2020-08-06 at 10 21 51" src="https://user-images.githubusercontent.com/869724/89509064-1b090700-d7cf-11ea-8dcd-47b06ec9ce38.png">

@N6REJ

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30278.

**Comment by infograf768** [comment]
right, forgot...
