### ISSUE TITLE
[4.0] No actions offered for Privacy: Information Requests

### ISSUE THREAD

**Issue by BertaOctech** [joomla/joomla-cms#30304]
### Steps to reproduce the issue

You need a site with a registered user.
As superadmin, from joomla backend, go to Users / Privacy: Information Requests
Create a request to remove the user data

### Expected result

I expect some actions offered for the request, so I can remove the user's data

### Actual result

I cannot see how to attend the request, no actions are offered

![imagen](https://user-images.githubusercontent.com/4395383/89552280-3c3c1880-d80c-11ea-88a1-dc03f2a809bb.png)

### System information (as much as possible)

Setting | Value
-- | --
PHP Built On 	| Linux linuxcillo.collaradawebs.es 4.4.132-53-default #1 SMP Wed May 23 06:57:07 UTC 2018 (036cd2f) x86_64
Database Type 	| mysql
Database Version 	| 10.4.11-MariaDB
Database Collation 	| utf8mb4_general_ci
Database Connection Collation 	| utf8mb4_general_ci
Database Connection Encryption 	| None
Database Server Supports Connection Encryption 	| No
PHP Version 	|7.2.29
Web Server 	|Apache/2.4.43 (Unix) OpenSSL/1.1.1f PHP/7.2.29 mod_perl/2.0.8-dev Perl/v5.16.3
WebServer to PHP Interface 	|apache2handler
Joomla! Version 	|Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT
User Agent 	|Mozilla/5.0 (X11; Linux x86_64; rv:76.0) Gecko/20100101 Firefox/76.0

**Comment by brianteeman** [comment]
thats because the request is still pending

**Comment by BertaOctech** [comment]
Thank you Brian, I apologize. 
I confirmed the request and the buttons appeared.

**Comment by brianteeman** [comment]
No need to apologise - it confused me the first time too
