### ISSUE TITLE
[4.0] Unable to use addCustomTag()

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#30308]
### Steps to reproduce the issue
Unable to use `addCustomTag()`.

Add the following within the head tag of the frontend template.

```
<?php 
$document = JFactory::getDocument();
$document->addCustomTag('<style>body {transform: rotate(180deg)}</style>'); 
?>
```

### Expected result
Page displays upside down

### Actual result
No change

**Comment by SharkyKZ** [comment]
`$document` is undefined. Inside template files you should use `$this->addCustomTag()` because `$this` is the current document.

**Comment by ciar4n** [comment]
@SharkyKZ Yep my bad. I have updated the testing details and results. Still an issue regarding addCustomTag().

**Comment by SharkyKZ** [comment]
Are you still getting the same issue?

**Comment by ciar4n** [comment]
No error message but the custom tag is still not added.

**Comment by SharkyKZ** [comment]
I can't reproduce the issue and I suspect you're not using Cassiopeia. Maybe Lightning?

**Comment by ciar4n** [comment]
Issue was on Cassiopeia. I'll close this. It can be re-opened if replicated.
