### ISSUE TITLE
Media (administrator) can't  insert   article Intro Image  with CDN external link picture

### ISSUE THREAD

**Issue by ymqjh** [joomla/joomla-cms#30305]
### Steps to reproduce the issue
![screen shot 2020-08-07 at 03 33 11](https://issues.joomla.org/uploads/1/a45f5de5d5a1a472f62174f882818091.jpg)
1. Create a new article
2. Switch to image and links
3. Select intro image
4. Images must be uploaded, no external link image option

In joomla 3 version, network pictures are a regular feature, I think 4.0 should not be removed. And most of the websites with larger data are in use, please add it!

**Comment by Quy** [comment]
Duplicate #28852
