### ISSUE TITLE
[4.0] Error 500 when sorting "Recent Articles" by modified date

### ISSUE THREAD

**Issue by Harmageddon** [joomla/joomla-cms#30309]
### Steps to reproduce the issue
1. Create some articles if you haven't already.
2. Open the backend dashboard.
3. Edit the (backend dashboard) module "Recently Added Articles".
4. Set the order to "Recently Modified First".
5. Refresh the backend dashboard.

### Expected result
Articles should be displayed in order of the modified date.

### Actual result
The backend dashboard displays:

> Error 500 Unknown column 'modified DESC, created' in 'order clause'

### System information (as much as possible)
PHP 7.2
Joomla! 4.0-dev as of today, also replicated by other users in beta-3.

### Additional comments
Issue was originally reported by user winterman at the German support forum: https://forum.joomla.de/thread/12211-error-500-in-4-0-0-beta3/

**Comment by ChristineWk** [comment]
Also the backend layout is corrupted:
![screen shot 2020-08-07 at 11 20 53](https://issues.joomla.org/uploads/1/3f43ee06ef1388533f6ae8be8d1ce192.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30309">issues.joomla.org/tracker/joomla-cms/30309</a>.</sub>

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30312.
