### ISSUE TITLE
[4.0] Query explain feature is broken due to DB changes, and queryMonitor limitation  

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#30318]
### Steps to reproduce the issue

Enable debug plugin and enable "Query explain" feature. 
In the Debugbar, in Query tab you should be able to see Explain , near the every "select" query.
But it show empty table. @alikon  comment: https://github.com/joomla/joomla-cms/issues/25675#issuecomment-605413380

### The reasons

The reasons is that the plugin run EXPLAIN without required params, and so database return SQL error.
https://github.com/joomla/joomla-cms/blob/e5db43948ed703492c99fa1f932247a9f611b058/plugins/system/debug/debug.php#L524-L529

It would be easy to fix but the problem in QueryMonitor, it does not log a bound params.
https://github.com/joomla-framework/database/blob/4cda5d73eb55ac8a596f261aac08a33d658421fb/src/QueryMonitorInterface.php#L26-L28

So first need to fix  QueryMonitor, then can get this issue fixed.

**Comment by richard67** [comment]
@alikon What do you think? Should this be a release blocker? I think it could be one, but I am not sure.

**Comment by richard67** [comment]
Related framework issue see https://github.com/joomla-framework/database/issues/214 . Thanks @Fedik .

**Comment by Fedik** [comment]
I would set it "release blocker", because if we not fix QueryMonitor before the release, later it will be harder to fix because a backward compatibility problems.

**Comment by alikon** [comment]
yes for me release blocker

**Comment by HLeithner** [comment]
How can a debug function be a release blocker?

**Comment by richard67** [comment]
A debug function is something essential for core and extension and whatever else on J4 developers.

Debugging database queries should also be possible when using prepared statements.

**Comment by wilsonge** [comment]
Agreed

**Comment by Fedik** [comment]
please test #30580
