### ISSUE TITLE
[4.0] Articles latest: 500 Unknown column 'modified DESC, created' in 'order clause'

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#30310]
### Steps to reproduce the issue
informed from joomla forum: https://forum.joomla.de/thread/12211-error-500-in-4-0-0-beta3/?postID=75601#post75601
Go to:
Home-Dashboard > Modules > Administrator
Recently Addes Articles
Articles Latest
Change from: Recently Added First to: Recently Modified First

### Actual result
will add screenshots via github
500 Unknown column 'modified DESC, created' in 'order clause'

### System information (as much as possible)
Joomla 4.0.0-beta4-dev (resp. Beta3)

### Additional comments
to "solve" it temporarily: Switch back to: Recently Added First

**Comment by alikon** [comment]
same as #30309
