### ISSUE TITLE
bs4 update

### ISSUE THREAD

**Issue by 1337180** [joomla/joomla-cms#30319]
UPDATE bootstrap 4 in next beta release for 4.5.2 for bug fixes

**Comment by richard67** [comment]
Bootstrap is not covered by PR #30248 for dependency updates, so this here seems to be a valid issue to me.

**Comment by brianteeman** [comment]
it should be in #30248

**Comment by richard67** [comment]
#30248 Should be updated anyway meanewhile, or be replaced by a new one. I think we should leave this issue here open as long as bootstrap dependency update to 4.5.2 is not covered by any PR.

**Comment by richard67** [comment]
I've left a comment in #30248 about adding bootstrap update and pinged the author. So let's see what happens.

**Comment by richard67** [comment]
Closing as having a new Pull Request. Please test #30334 . Thanks in advance.
