### ISSUE TITLE
[4.0] Admin Sidebar Dashboard button background

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#30321]
### What needs to be fixed
When you are on a dashboard page the relative sidebar item menu have class `class="mm-active"` and it become gray.
But only the `a` item become gray, not the entire `<span class="menu-dashboard"> `as :hover

![immagine](https://user-images.githubusercontent.com/906604/89713824-85ba6e00-d99a-11ea-9a37-403742abee8a.png)

### Why this should be fixed
for usability

### How would you fix it
Instead:
```
.main-nav li .menu-dashboard > a > .fas, .main-nav li .menu-quicktask > a > .fas {
	display: inline-flex;
	align-items: center;
	padding: 0.9rem;
}
```
use:
```
.main-nav li .menu-dashboard > a, .main-nav li .menu-quicktask > a {
	display: inline-flex;
	align-items: center;
	padding: 0.9rem;
}
```

### Side Effects expected
![immagine](https://user-images.githubusercontent.com/906604/89714056-51e04800-d99c-11ea-8c01-64e9dee5c1ec.png)

**Comment by richard67** [comment]
Closing as there is a Pull Request to solve this issue: #30322 .
