### ISSUE TITLE
Document solution for 3.x upgrades using btn-groups and switcher

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#30325]
This issue tracks the comment here https://github.com/joomla/joomla-cms/pull/29462#issuecomment-662747131 looks like there's no super easy way to deal with switch and button groups in the same class for 3.x -> 4.x migrations. This tracks that with the aim of provided a documented working example of some code that will work in 3.x and 4.x

**Comment by SharkyKZ** [comment]
Since https://github.com/joomla/joomla-cms/pull/30078 this can be used:

>class="btn-group btn-group-yesno"
>layout="joomla.form.field.radio.switcher"

That is while switcher doesn't support custom classes.

**Comment by zero-24** [comment]
This has been documented here: https://docs.joomla.org/J3.x:Joomla_3.10_Backports
