### ISSUE TITLE
[4.0] UserHelper::removeUserFromGroup Does not work

### ISSUE THREAD

**Issue by veperr** [joomla/joomla-cms#30324]
Using Namespace: Joomla\CMS\User\UserHelper
the function UserHelper::removeUserFromGroup
simply does not work

### Steps to reproduce the issue
1) create a group, get groupId
2) create a user, get userId
3) add user to group
4) try to remove user from group using:
      UserHelper::removeUserFromGroup($userId, $groupId)

### Expected result
The User would be removed from the group

### Actual result
The user is not removed from the group

### System information (as much as possible)
Ubuntu 20.04.1 LTS
Apache 2.4.41
PHP 7.4.3
Joomla 4.0 beta 3

### Additional comments
The following custom function I wrote works:
private function removeUserFromGroup($userId, $groupId){
    $user = User::getInstance($userId);
    // 		    $user = new User($userId);
    // 		    $user->load($userId);
    $userGrps = Access::getGroupsByUser($userId, false);
    
    unset($userGrps[array_search($groupId, $userGrps)]);
    
    $user->groups = $userGrps;
    $user->save();
    
    // Store the data.
    if (!$user->save())
    {
        $this->setError($user->getError());
        
        return false;
    }
    return $user->id;
}

Thank you!

**Comment by alikon** [comment]
i cannot confirm, i've tested with CLI
![Screenshot from 2020-08-12 10-01-07](https://user-images.githubusercontent.com/181681/89990522-ce1ba980-dc82-11ea-8f58-63bf5c340c95.png)

**Comment by alikon** [comment]
ouch wait .... 
despite the  successfull removed message  that user is still in that usergroup ....

**Comment by alikon** [comment]
please test #30355
