### ISSUE TITLE
[3.x] Codemirror update

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30338]
Codemirror needs to be updated as its several point releases out of date.

There is a script that has been used in the past to generate the update https://github.com/okonomiyaki3000/joomla-codemirror-builder

However I just tried and got errors - and I dont have time/skill/interest in working out the error.

**Comment by C-Lodder** [comment]
what errors?

**Comment by C-Lodder** [comment]
Try running `npm i -g grunt` and then running `grunt`.

**Comment by brianteeman** [comment]
> Try running npm i -g grunt and then running grunt.

I had tried that first

> what errors?

Fatal error: cb.apply is not a functionill install loadCurrentTree

**Comment by C-Lodder** [comment]
https://github.com/nodejs/help/issues/2874#issuecomment-663661148

**Comment by brianteeman** [comment]
google gave me that as well and i tried it before opening this issue

option1 didnt work and i dont have time for option 2

that why i posted so someone else can try

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30370.
