### ISSUE TITLE
[3.x] User Notes not removed

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30349]
#### Part 1
Create a new user
In the admin add a note for the user
Verify that the user note appears in the list of all user notes
Verify that the button below the username in the userlist shows a note for this user

#### Part 2
Delete the user

### Expected result
User deleted and note deleted

### Actual result
User deleted and not remains but not associated with any user obviously

![image](https://user-images.githubusercontent.com/1296369/90009249-a5e97600-dc95-11ea-8333-fd8bb133bf99.png)

**Comment by sandewt** [comment]
I can confirm this issue.

System information:
Joomla! 3.9.21-dev Development [ Amani ] 14-July-2020 15:50 GMT<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30349">issues.joomla.org/tracker/joomla-cms/30349</a>.</sub>
