### ISSUE TITLE
[4.0] Password reset not working in backend

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#30354]
Thank you @karo3.

### Steps to reproduce the issue
Add a new user to user groups registered and manager or admin, set "password reset required".

### Expected result
If the user wants to login in backend, he gets the profile and can change the password (as in 3.9.20)

### Actual result
Error 403: You don't have permission to access this. Please contact a website administrator if this is incorrect.

![screen shot 2020-08-12 at 20 47 46](https://issues.joomla.org/uploads/1/65cb11827f95e21bfab689ba54f5dda4.png) 

### Additional comments
In Frontend, it works as expected, the user can change the password.

**Comment by brianteeman** [comment]
what is the url you are redirected to?

**Comment by chmst** [comment]
I don't understand the question, sorry. You mean if I click on the "Return to dahsboard"?

**Comment by chmst** [comment]
administrator/index.php?option=com_users&task=user.edit&id=666

**Comment by brianteeman** [comment]
So I think it's the same problem I created and discussed here #25440

Which btw was fixed incorrectly and removed the per user accessibility settings

**Comment by brianteeman** [comment]
Can you recheck please as this should have been resolved

**Comment by brianteeman** [comment]
I have checked again and this is definitely resolved and can be closed
