### ISSUE TITLE
[4.0] Text Filter default setting for guest should be No HTML

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#30351]
### Steps to reproduce the issue
In Joomla 3.9.19 the security settings has been updated for the text filters. Guest, public and registred should be default "no html".
In Joomla 4.0 beta4-dev ist the default setting for guest is set to "default blacklists" instead of "no html"

### Expected result
![screen shot 2020-08-12 at 12 41 07](https://issues.joomla.org/uploads/1/1b23173b638753287831850ba06d8eaf.jpg)

### Actual result
![screen shot 2020-08-12 at 12 40 54](https://issues.joomla.org/uploads/1/75b4446b548d44ef6c05a45f1cb0727b.jpg)

**Comment by brianteeman** [comment]
That change will be bubbled up into j4 when recent j3 changes are ported
