### ISSUE TITLE
[4.0] Notification in Workflow can't be read by not administrator user

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#30361]
In the transition part of the Workflow component it is possible to create notifactions for users, which have to take the next step in the workflow. The information about the generation of new notification is sent by email which contains  a link to the backend. The notification system is only accessible for administrators, so that users which have only a user group based on Registered can't read the notification.

There should be an option to send the whole notification per email, so that also not administrator user can read it.

**Comment by brianteeman** [comment]
@paternax I'm not sure what the use case would possibly be for a non-administrative user to receive the email. However I can see that workflows is not using the new mail templates which it probably should and that would resolve the problem. If no one beats me too it I will take a look at this

**Comment by paternax** [comment]
For example  frontend editors who submit new blog posts could be informed about the change of stages.

**Comment by brianteeman** [comment]
ah - i see the problem now.

The email received is as folllows

```
The status of an Article has been changed 

Title: Typography, changed by Brian Teeman, new state: Basic Stage. 

Please log in to http://localhost/joomla-cms/administrator/index.php?option=com_messages&view=message&message_id=5 to read your message.
```


> There should be an option to send the whole notification per email, so that also not administrator user can read it.

The **_problem_** is that there is no extra text to that email. It is complete but the link that a non-admin user cannot use suggests that there is something more that they can not see.

**Comment by brianteeman** [comment]
You can "fix" this for now by creating a language override for COM_MESSAGES_NEW_MESSAGE_BODY

**Comment by brianteeman** [comment]
Please test #35693

**Comment by richard67** [comment]
Closing as having a pull request. Please test #35693 . Thanks in advance.
