### ISSUE TITLE
Joomla 4 Beta 3 — Smart Search bad output

### ISSUE THREAD

**Issue by vintzl** [joomla/joomla-cms#30368]
### Steps to reproduce the issue

Setup Smart Search, then write some content, especially as categories and plugins.

Finally do some searches and get the result.

### Expected result

Clean urls displayed for categories and plugins content displayed properly.

### Actual result

Categories url look like this:
- `?view=article&id=1:home&catid=2`

instead of this something like this:
- `/somecategory` (as the actual url, especially as "Search Engine Friendly URLs" is activated)

And plugin content should be returned properly, instead of something like:
`{loadposition someposition}`

### System information (as much as possible)
Joomla Beta 3 from here :
- https://github.com/joomla/joomla-cms/releases/tag/4.0.0-beta3

### Additional comments
Tested with a clean install…

**Comment by Quy** [comment]
Can you please test again with Beta 5? https://github.com/joomla/joomla-cms/releases/tag/4.0.0-beta5

**Comment by vintzl** [comment]
Now, **only the home page** still have this problem, and is displayed like this:
- /?view=article&id=1:accueil&catid=2

**Comment by brianteeman** [comment]
Is that article accessible by any menu item?

**Comment by vintzl** [comment]
Yes, as this is the home page, it is accessible by the main menu.

**Comment by toivo** [comment]
SEF URLs work all right in Beta6-dev, as long as the option 'Remove IDs from URLs' has been set in Content - Options - Integration - Routing.

**Comment by bembelimen** [comment]
No it does not work, because the onPrepareContent plugin trigger is not called in the search results, so {loadmodule xxx} etc. are not parsed.

**Comment by HLeithner** [comment]
@vintzl Same as in #31572 

The behavior is expected because you don't have a category menu item nor a single article menu entry. In this case it uses the default menu item "featured" and adds the needed parameter (view, category and article id)

If it's not this behavior please reopen this issue.

**Comment by vintzl** [comment]
Ok, I will check this, but I did a mistake as plugin content should be returned properly, but I still get something like:
{loadposition someposition}
