### ISSUE TITLE
Joomla 3 Error

### ISSUE THREAD

**Issue by diddipoeler** [joomla/joomla-cms#30374]
When installing Jooma 3.9.19 I get the following error:

Warning: Cannot declare class jregistry, because the name is already in use in /www/htdocs/w00861a1/fussballineuropaj15/jupgrade/joomla_3/libraries/loader.php on line 685

Fatal error: Uncaught TypeError: Argument 1 passed to JErrorPage::render() must be an instance of Exception, instance of Error given in /www/htdocs/w00861a1/fussballineuropaj15/jupgrade/joomla_3/libraries/cms/error/page.php:30 Stack trace: #0 [internal function]: JErrorPage::render(Object(Error)) #1 {main} thrown in /www/htdocs/w00861a1/fussballineuropaj15/jupgrade/joomla_3/libraries/cms/error/page.php on line 30

**Comment by richard67** [comment]
@diddipoeler I've allowed myself to translate the first sentence of your issuse description from German to English.

Please in future report here in English language.

Thanks in advance.

**Comment by richard67** [comment]
@diddipoeler And is it really a 3.9.19? If so, please try with latest 3.9.20. If the error still persists, report back details on your environment: Which server OS, which database type and version, and finally which PHP version.

**Comment by richard67** [comment]
P.S.: I did not have such a problem when I had tested new installations of 3.9.19 or 3.9.20 on Linux server with MySQL 8.0 or PostgreSQL 11.7 database and PHP 7.3.

**Comment by brianteeman** [comment]
core joomla has no such file as
/libraries/cms/error/page.php

**Comment by richard67** [comment]
> core joomla has no such file as
> /libraries/cms/error/page.php

That's correct.

@diddipoeler Have you installed an extension which adds this file (by the way to a place where a 3rd party extension should not add files)? Or is that some kind of a custom error page?

**Comment by richard67** [comment]
Setting status to "Information required".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30374">issues.joomla.org/tracker/joomla-cms/30374</a>.</sub>

**Comment by richard67** [comment]
@diddipoeler Other question: The folder name "fussballineuropaj15" sounds like something with a Joomla 1.5 (because of the j15 at the end). But you write you haven't updated, you've made a new install. Is that installation of J 3.9 in a subfolder of a J1.5? Or was the folder used for a J 1.5 before and has not been empty before installing J 3.9, so that there are still some old files from Joomla 1.5 or old extrensions present?

**Comment by alikon** [comment]
i'm going to close this one for lack of response
it can be reopened when the required info will be avalaible
