### ISSUE TITLE
[4.0]Personalize Cassiopeia at least

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#30376]
Hello everyone, I don't know what that represents for work. I am not a developer. But Cassiopeia must have at least the same settings as the Protostar template. Otherwise, there may not be a migration from Joomla 3.9 to 4. This is a minimum to find our main and secondary colors. Please take into account this request which seems very important to me.

![cassiopeia](https://user-images.githubusercontent.com/26197929/90309854-5fda1f80-deec-11ea-8516-30c9dea20957.jpg)

**Comment by sandewt** [comment]
For your information: [[4.0] Templates](https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#Templates)

**Comment by Magnytu2** [comment]
Thank you very much, I did not know this information. But that does not answer my request. For the purpose of switching from Joomla 3.9> 3.10> 4 it is necessary at least that users can find the same possibilities and without entering the code.

**Comment by sandewt** [comment]
>But that does not answer my request

Your proposal seems like a good idea. :thumbsup:

I can't really imagine that this hasn't been thought about yet.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30376">issues.joomla.org/tracker/joomla-cms/30376</a>.</sub>

**Comment by N6REJ** [comment]
That really isn't the way templates work.  Each template has its own module positions, styling, etc.  I WOULD NEVER EVER allow joomla to modify my template!  
Adding a primary/secondary form field for color is fine but don't expect it to be a turnkey upgrade imo.

**Comment by chmst** [comment]
Please be patient. We are aware of this problem and are working on it.

**Comment by drmenzelit** [comment]
Color and font switch have been added on the Cassiopeia repository

**Comment by Quy** [comment]
Please test PR #31520
