### ISSUE TITLE
[4.0] Redis Caching fails ungracefully when server down, or incorrectly configured. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30378]
### Steps to reproduce the issue

Joomla 4.0-dev 

Correctly configure caching to a redis server. Reload any Joomla page - see it caches and no issues. 

Turn off the redis server OR edit /configuration.php and change 

`public $redis_server_host = 'yourredisserver.com';`
to
`public $redis_server_host = 'redisDOWN';`

reload the /administrator/ url 

### Expected result

Joomla handles this failure with grace. 

Joomla doesn't display any Notices or Warnings. 

### Actual result
<img width="1401" alt="Screenshot 2020-08-15 at 13 54 49" src="https://user-images.githubusercontent.com/400092/90312748-e697f800-defe-11ea-843a-ca1b8bfc4afc.png">

**Comment by wilsonge** [comment]
Fix for the undefined variable notice https://github.com/joomla/joomla-cms/pull/31121

I'm not really sure if there's a way to catch the php warnings that get thrown (it's the same in the session driver too for that part)

**Comment by PhilETaylor** [comment]
> I'm not really sure if there's a way to catch the php warnings that get thrown (it's the same in the session driver too for that part)

Correct. This is a problem way up the stack of Joomla, where the session retrieval is done. For example if the db server is down and sessions are being saved in the db, then again we get PHP warnings and a hard to catch 500 error which is hard to report the REAL reason for the error. 

I spent a bit of time on this when looking at the new red screen fatal error handler and could not resolve this.

**Comment by wilsonge** [comment]
Ok i think I'm going to close this as a won't fix.

And more in line of technically it's very tricky without underlying redis driver changes to fix this than because I don't want to.

**Comment by wilsonge** [comment]
If anyone does come up with a solution more than happy to consider it clearly. But without a concrete suggestion hard to see how to take this forward

**Comment by PhilETaylor** [comment]
Basically 2 things.

1. We need to catch and not display PHP Warnings. I think I have a solution for this but I doubt anyone will like it, but its needed.

2. We need to sort out the fatal error handler so that we display the correct Exception and not the wrong Exception, based on my experience with implementing the new Symfony Fatal Red Screen of death, the lower end of that handling is simply wrong and needs some love. 

By we, I probably mean, Me. 

This is not restricted to the Redis Server being unavailable - the same kind of thing happens whenever a PHP Warning is displayed before a Session starts (as well as when the session storage is down) - as evidenced when playing with the FTP Layer recently.
