### ISSUE TITLE
[4.0]  Undefined index: templateInherits 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30379]
### Steps to reproduce the issue

Joomla 4.0-dev
see https://github.com/joomla/joomla-cms/issues/30378 to replicate this 
Forking this one message as its unrelated to Redis.

```
Notice: Undefined index: templateInherits in /application/libraries/src/Document/HtmlDocument.php on line 809
```

### Expected result

No undefined indexes, no notices output

### Actual result

```
Notice: Undefined index: templateInherits in /application/libraries/src/Document/HtmlDocument.php on line 809
```

**Comment by dgrammatiko** [comment]
PR https://github.com/joomla/joomla-cms/pull/30384
