### ISSUE TITLE
[4] deprecated DocBlock correct? 

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#30386]
### Steps to reproduce the issue
- See https://github.com/joomla/joomla-cms/blob/4.0-dev/components/com_content/helpers/icon.php#L18 (and others).

`@deprecated 5.0 Use the class \Joomla\Component\Content\Site\Service\HTML\Icon instead`

### Expected result
????

- `@deprecated 5.0 Use the class \Joomla\Component\Content\Administrator\Service\HTML\Icon instead`

????

**Comment by SharkyKZ** [comment]
Not correct.

**Comment by richard67** [comment]
@SharkyKZ Sorry, what's not correct? The deprecation string? Or the solution proposed above? I assume the first, but it's not 100 clear to me. If the first: Is the proposed correction here correct? Or maybe in shorter words: Do you want to make a PR? ;-)

**Comment by SharkyKZ** [comment]
The first.

**Comment by richard67** [comment]
@ReLater Wanna make a PR?

**Comment by ReLater** [comment]
Will do

**Comment by ReLater** [comment]
see pr https://github.com/joomla/joomla-cms/pull/30389
