### ISSUE TITLE
[4.0] Admin template screwed on error

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30380]
### Steps to reproduce the issue

Joomla 4.0-dev

Throw an exception somewhere in Joomla /administrator/  

```
throw new \Exception('Test');
```

### Expected result

A header of height 20-40px as normal. 

### Actual result

The blue header is the size of the view port, scrolling down you can see the rest of the page, including the error 

![Screen Recording 2020-08-15 at 02 03 pm](https://user-images.githubusercontent.com/400092/90312939-3aefa780-df00-11ea-9266-236206f9d24f.gif)

### System information (as much as possible)

Safari on mac

### Additional comments

`templateInherits` issue is forked to https://github.com/joomla/joomla-cms/issues/30379 so ignore that in this.

**Comment by dgrammatiko** [comment]
PR https://github.com/joomla/joomla-cms/pull/30384

**Comment by PhilETaylor** [comment]
PR #30384 is for `templateInherits` message only? or does that also fix the header ?

**Comment by dgrammatiko** [comment]
@PhilETaylor it seems that it fixes both
<img width="1680" alt="Screenshot 2020-08-16 at 14 45 12" src="https://user-images.githubusercontent.com/3889375/90334676-aa809800-dfcf-11ea-8c7d-a6988341e39d.png">

FWIW I already had this fix ready: https://github.com/joomla/joomla-cms/pull/30359/files#diff-bcf9301c645f039de7e125ee3c4658baR809

**Comment by PhilETaylor** [comment]
Cool :) Thanks.
