### ISSUE TITLE
[3.10] Joomla Version module

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#30381]
### Steps to reproduce the issue
Upgrade to 4 Beta

In 3.10 this module's position is `footer` and in 4, it is `status`.

### Expected result
Version should be displayed in the upper right corner.

### Actual result
No version is displayed.

**Comment by infograf768** [comment]
I guess this can be solved by an sql update.

**Comment by richard67** [comment]
> I guess this can be solved by an sql update.

Yes, if the module can be clearly identified in a `WHERE` clause (what I think should be the case). Shall I try to make a PR?

**Comment by richard67** [comment]
@Quy Would following be sufficient?

```
UPDATE `#__modules` SET `position`='status' WHERE `module`='mod_version' AND `client_id`=1;
```

Or should we also include the old position in the condition in case someone has published another mod_version somewhere else?

```
UPDATE `#__modules` SET `position`='status' WHERE `module`='mod_version' AND `client_id`=1 AND `position`='footer';
```

**Comment by richard67** [comment]
Or do we need to restrict it even more?

**Comment by infograf768** [comment]
imho, if someone has set the mod_version in another position, it may anyway not fit to Atum.
Therefore I am rather in favor of 
```
UPDATE `#__modules` SET `position`='status' WHERE `module`='mod_version' AND `client_id`=1;
```

**Comment by richard67** [comment]
Closing as having a pull request. Please test #30383 .
