### ISSUE TITLE
[4.0] Menu item "Compact List of Tagged Items". Cannot select tags.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#30385]
### Steps to reproduce the issue
- Nightly build of today without testing datas.
- Create some tags. In my case there weren't any.
- Add some tags to articles.
- Create a new menu item of type "Compact List of Tagged Items"

### Expected result
- I can select tags in field "Tag"

### Actual result
- No tags displayed in field "Tag"

![16-08-_2020_15-16-02](https://user-images.githubusercontent.com/20780646/90335232-a5bde300-dfd3-11ea-9770-81610ca7308e.jpg)

### System information
- Current Firefox, Windows 10.

**Comment by SharkyKZ** [comment]
You have to type in at least 3 characters (this number can be configured in `com_tags`).

**Comment by brianteeman** [comment]
> You have to type in at least 3 characters (this number can be configured in com_tags).

If true then the hint text is wrong

**Comment by ReLater** [comment]
> If true then the hint text is wrong

And if true: A user has to know the tags by rote? I think that's really bad UIX. I use circa 25 on my site and know 5 by rote ;-)

If something is argueing against a dropdown list here maybe a modal selection would be a nice idea.

**Comment by ghost** [comment]
> … a dropdown list here maybe a modal selection would be a nice idea.

true

**Comment by infograf768** [comment]
I have set this issue as a release blocker
See https://github.com/joomla/joomla-cms/issues/31348

Sorry as I did not see this one before. Closing this one to not keep duplicate.
