### ISSUE TITLE
[4.0] multiple error messages

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30391]
### Steps to reproduce the issue
Try to do an install but with multiple errors
eg a short user password and invalid mysql details

### Expected result
Nicely formatted error messages. Each on their own line

### Actual result
![image](https://user-images.githubusercontent.com/1296369/90344245-c9068380-e00f-11ea-9178-46a2c1944f1a.png)

**Comment by infograf768** [comment]
Good find. Not sure yet how to solve.

**Comment by infograf768** [comment]
Overlooked indeed...
Only way I found is to get rid of flex.
In this case, I can get 

<img width="719" alt="Screen Shot 2020-08-17 at 10 15 33" src="https://user-images.githubusercontent.com/869724/90373721-a9547700-e072-11ea-9483-0d4c8c185ead.png">

Certainly still better than the older one but we lose the saved space.

What do you think?
@brianteeman @wilsonge @SharkyKZ

**Comment by infograf768** [comment]
I can also get this after modifying the js a bit

<img width="777" alt="Screen Shot 2020-08-17 at 12 53 30" src="https://user-images.githubusercontent.com/869724/90388826-baa87e00-e088-11ea-8c1a-8ff9c4efa3ea.png">

**Comment by brianteeman** [comment]
That's much better.

**Comment by infograf768** [comment]
Closing as we have a patch 
https://github.com/joomla/joomla-cms/pull/30401
