### ISSUE TITLE
[4.0] 2FA not enabled correctly when using link in post install message

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30398]
### Steps to reproduce the issue

Install Joomla 4.0-dev
Login
Visit Post Installlation Messages 
Click Enable two factor authentication button

<img width="898" alt="Screenshot 2020-08-17 at 12 26 25" src="https://user-images.githubusercontent.com/400092/90391397-ff321a80-e084-11ea-85c5-3dfa728bba67.png">

EDIT: ENABLE YOUR JOOMLA CACHE in Joomla Global Config

Go to plugins and note that the plugins ARE ENABLED 

Go to your User Menu -> Edit Account 

### Expected result

Two Factory Authentication Tab available

### Actual result

No Two Factory Authentication Tab available

HOWEVER, then go and edit and SAVE (with no changes) the 2fa plugins again, then the tab will be available.

Im *guessing* the SQL that the "Enable two factor authentication" button runs is not setting all fields in the db correctly - is this a null issue again?

**Comment by SharkyKZ** [comment]
I can't reproduce the issue. The query only updates one column. I don't see how null values could be an issue here:

https://github.com/joomla/joomla-cms/blob/0ebb8a62ea6b9569db0a452b132907a85541ac71/plugins/twofactorauth/totp/postinstall/actions.php#L54-L60

**Comment by alikon** [comment]
the only thing which could be wrong is that the enabled field is declare as  
```sql
`enabled` tinyint(3) NOT NULL DEFAULT 0,
```

https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/sql/mysql/base.sql#L121

so

`->set($db->quoteName('enabled') . ' = ' . $db->quote(1)) `

should be 


`->set($db->quoteName('enabled') . ' = 1') `

**Comment by PhilETaylor** [comment]
Enable Joomla Cache. Test again. = Broken. 

Its a caching issue. The cache needs flushing after the enabled is changed - else it doesn't show the tab

**Comment by alikon** [comment]
please test #30416
