### ISSUE TITLE
[4.0] Workflow - Notification were not sent

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#30396]
There is a problem with the system notifications in workflow. You have a workflow with  several users who belong to usergroups based on registered (no administrators),
So they should not receive "normal" system messages. Therefore the option "Receive System Emails" is set to "No" in the user configuration. In the transitions of the workflow the users which should receive messages are selected.

But the users receive no notifications.
If you set the option "Receive System Emails" is set to "Yes" in the configuration of the users, the users receive all notification from all transitions (and the system messages)

### Steps to reproduce the issue
Set up a workflow scenario like. https://docs.joomla.org/Publishing_Workflow/Scenarios/en but set the option "Receive system messages" to "No" in the user configuration

![screen shot 2020-08-17 at 09 04 16](https://issues.joomla.org/uploads/1/995acdd45d9ad3164788923d80c4cf5a.jpg)

Set "Send Notification" to "Yes" in the transitions and select the Usergroups / Users which should receive the notification

![screen shot 2020-08-17 at 09 04 31](https://issues.joomla.org/uploads/1/26e643239a9571ba1277b60f0dfd930f.jpg)

### Expected result
The user/usergroup members should receive the notifications

### Actual result
No user receive a notification

If you set the option "Receive system messages" to "yes" in the user configuration of the users involved in the workflow, each user get all notifications of the workflow. Not only the ones he is selected in the transition.

### System information (as much as possible)
Joomla 4.0.0-beta4-dev
PHP 7,3

**Comment by richard67** [comment]
Is this a duplicate to your previous issue #30395 ?

**Comment by paternax** [comment]
Yes, when saving I get an error and everything was lost. I couldn't see the issue in the issue tracker so I did it again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30396">issues.joomla.org/tracker/joomla-cms/30396</a>.</sub>

**Comment by richard67** [comment]
I can see them both in the tracker now. Maybe the tracker was just a bit busy ;-)

If you can see them both, too, just chose the one which is not up to date regarding your last changes and close it.

If there is still a problem, please report back here and I'll try to help.

Thanks in advance.

**Comment by paternax** [comment]
How can I close an issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30396">issues.joomla.org/tracker/joomla-cms/30396</a>.</sub>

**Comment by richard67** [comment]
Either on GitHub with a button at the bottom, or in the issue tracker when using the "edit" button, then changing the state to "Closed" in the dropdown at the left hand side, then scrolling down and entering a suitable comment in the text field at the bottom below the text field with the issue description, then using the "Save" button.

Or just let me know here which one is to be closed, then I can close it for you.

**Comment by paternax** [comment]
It was opened twice by mistake
