### ISSUE TITLE
[3.10>4.0] Missing tabs in Global Configuration

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#30393]
### Steps to reproduce the issue
Upgrade 3.10 to 4
Go to Global Configuration 

### Expected result
![tabs](https://user-images.githubusercontent.com/368084/90353414-fbf24c80-dffa-11ea-8cf6-48bdfdc700db.png)

### Actual result
![no-tabs](https://user-images.githubusercontent.com/368084/90353417-feed3d00-dffa-11ea-8387-613ba97770f1.png)

**Comment by richard67** [comment]
Confirmed. Used the current 3.10-dev branch and updated to J4 nightly of tonight using custom URL and Live Update.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30393">issues.joomla.org/tracker/joomla-cms/30393</a>.</sub>

**Comment by richard67** [comment]
@Quy Do you think it could be related to files not being deleted by script.php? It's a while ago (last Beta I think) when that lists of files and folders to be deleted were updated last time. Or is it just a CSS issue? I don't think it's a database problem.

**Comment by richard67** [comment]
Stange. A few minutes ago I've logged out from the updated installation which I have used for replicating this issue. Now I've logged in again and the tabs are there.

**Comment by Quy** [comment]
Tabs do appear after logging again the next day. Perhaps close this?

**Comment by richard67** [comment]
Not sure.

**Comment by richard67** [comment]
I think it's a valid issue.

**Comment by Quy** [comment]
No longer reproducible.
