### ISSUE TITLE
[4.0] Article can't be saved in the frontend after editing

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#30403]
Frontend User (User Group: registered) creates a category blog article which gets automatically the category from the menu item settings. Then the article is saved by the user. If the user opens the article for editing again it isn't possible to save the article because of a warning comes up: "Field required: Category"
If you look in the administration, the article has the correct category.

### Steps to reproduce the issue
1.	Create an user from the usergroup “registered”
2.	Create a category named “blog” and set the permissions “Create” and “Edit” for the user to “Allowed”
3.	Create a menu item from type: "category blog" and use the category “blog” you just created
4.	Create a menu item from type: “create article”, in the options set “specific category” to "yes" and select the category “blog” in “choose a category”
5.	Login in at the frontend with your registered user
6.	Create an article, save the article
7.	Click at the “edit” icon, open the article again and save try to save it

### Expected result
The article is saved

### Actual result
It is not possible to save the article because there is a warning: Field required: Category

![screen shot 2020-08-17 at 14 36 15](https://issues.joomla.org/uploads/1/9a5c057946d3840f50735b3d53f9cacf.jpg)

If you look in the backend the article has the correct category “blog”

![screen shot 2020-08-17 at 14 37 55](https://issues.joomla.org/uploads/1/0eeed60028dac8134827a64cbe4af370.jpg)

### System information (as much as possible)
Joomla 4.0 beta-dev

**Comment by brianteeman** [comment]
#29233

**Comment by richard67** [comment]
Closing as duplicate report, see #29233 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30403">issues.joomla.org/tracker/joomla-cms/30403</a>.</sub>
