### ISSUE TITLE
[4.0] Message width

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30404]
### Steps to reproduce the issue
You can see this for example after applying a patch with com_patchtester

![image](https://user-images.githubusercontent.com/1296369/90414563-dcfdc400-e0a7-11ea-87ef-209d9c2258f4.png)

### Expected result

Something much neater perhaps like
![image](https://user-images.githubusercontent.com/1296369/90414726-0dddf900-e0a8-11ea-88c6-541049eaf497.png)

**Comment by infograf768** [comment]
Not sure we can do as the title can be quite different form one language to the other.

**Comment by Quy** [comment]
or use icons?

**Comment by brianteeman** [comment]
sure it can be done by setting the width of the alert-heading

**Comment by chmst** [comment]
I like the idea of having same width and use icons, the text as sr-only.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30404">issues.joomla.org/tracker/joomla-cms/30404</a>.</sub>

**Comment by infograf768** [comment]
> sure it can be done by setting the width of the alert-heading

Some words in some languages are 14-15 (maybe more did not look all possibilities) letters for "Warning" in English which is 7 letters. Russian "предупреждение" is 14 letters. French "Avertissement" is 13, etc.
It would require at least `width: 11rem;` and we could get rid of
```
    display: flex;
    flex-direction: column;
    justify-content: center;
    align-content: center;
```

Example
<img width="281" alt="Screen Shot 2020-08-29 at 11 02 52" src="https://user-images.githubusercontent.com/869724/91633281-43a7a980-e9e7-11ea-8bcf-5e3311cce3b6.png">

This will give something like this in English

<img width="251" alt="Screen Shot 2020-08-29 at 11 04 12" src="https://user-images.githubusercontent.com/869724/91633297-65a12c00-e9e7-11ea-914f-d0979912c3f6.png">

and in Traditional Chinese
<img width="270" alt="Screen Shot 2020-08-29 at 11 05 13" src="https://user-images.githubusercontent.com/869724/91633320-95e8ca80-e9e7-11ea-9c64-d97865eb7f81.png">

Therefore it would work, although increasing the heading width in an important way for languages using only short words.
Note: when reducing window size to mobile, using 11rem as width is not enough to keep same size when multiple messages. We would need at least 15rem. I ignore why without further research.

**BUT** we do have indeed an issue in the present setting for Chinese for example or any language using separate glyphs. Glyphs are displayed vertically as they are separate.

<img width="178" alt="Screen Shot 2020-08-29 at 11 10 25" src="https://user-images.githubusercontent.com/869724/91633400-448d0b00-e9e8-11ea-8f06-0433e0a38ce4.png">

That is a bug imho.

Therefore why not icons indeed if we agree on which ones to use and test also with Monochrome

For example something like (or variants to fit with with background colors/greys and keep contrast)

Error

![Screen Shot 2020-08-29 at 10 41 52](https://user-images.githubusercontent.com/869724/91633026-65079600-e9e5-11ea-911c-a73ee6155b77.png)

 Warning

![Screen Shot 2020-08-29 at 10 40 30](https://user-images.githubusercontent.com/869724/91633023-5b7e2e00-e9e5-11ea-9c89-282c4e85be07.png)

 Message

![Screen Shot 2020-08-29 at 10 46 52](https://user-images.githubusercontent.com/869724/91633033-6c2ea400-e9e5-11ea-84bd-9dbf0639f8dd.png)

 Info

![Screen Shot 2020-08-29 at 10 39 48](https://user-images.githubusercontent.com/869724/91633020-4dc8a880-e9e5-11ea-98b0-4fa6bd2e1e58.png)

**Comment by infograf768** [comment]
Remains to find a way to modify the js to use icons and sr-only when the layout is not used.
We have now
```
if (typeof title !== 'undefined') {
        titleWrapper = document.createElement('div');
        titleWrapper.className = 'alert-heading';
        titleWrapper.innerHTML = Joomla.Text._(type) ? Joomla.Text._(type) : type;
        messagesBox.appendChild(titleWrapper);
      }
```
In the layout it is easier
I can get for example
<img width="182" alt="Screen Shot 2020-08-29 at 11 55 25" src="https://user-images.githubusercontent.com/869724/91634212-f62f3a80-e9ee-11ea-9ea3-d69908544e8d.png">

with code produced
<img width="609" alt="Screen Shot 2020-08-29 at 12 03 11" src="https://user-images.githubusercontent.com/869724/91634306-b74db480-e9ef-11ea-805e-c77471506956.png">

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/30516
Closing as we have a patch
