### ISSUE TITLE
[4 beta 3] Multilingual demo installation

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#30405]
Hello, I've tried twice to install a Joomla 4 beta 3 in multilanguage locally, but twice there is an installation error.

![Control_Panel_-_Joomla_4_Beta_3_-_Administration](https://user-images.githubusercontent.com/26197929/90422268-ecd2d380-e0ba-11ea-97b3-370547c087b0.jpg)

**Comment by infograf768** [comment]
This just means what it says: you need to have at least 2 languages and their content languages installed.
It will not work for en-GB only.

**Comment by Magnytu2** [comment]
Sorry, but I have already installed the multilanguage demo without having installed two languages first. The installation system did it on its own.
And if that's the case, it doesn't make sense to show the installation of a demo on a site with only one language here.

**Comment by infograf768** [comment]
> Sorry, but I have already installed the multilanguage demo without having installed two languages first. The installation system did it on its own.

Certainly not. How would it know which languages you need?
You maybe had installed French during J installation and you don't remember.

As we now have specific plugins for sample data, if we were not showing the multilingual one to people that don't know there is that possibility, it would be almost useless.
Therefore, it throws an error and tells you what to do.
If you don't want to do what it tells, I can't help you.

I close this issue as it is not an issue.

**Comment by Magnytu2** [comment]
Excuse me, I could be wrong. As you say it is a memory.
When to hide a multilingual demo, it is my penalty to hide the Workflow. It also works. If you hide it, users won't know it exists.
But that's okay, I managed a multilingual installation with J4 and after the demo. Thank you to all of you.

**Comment by brianteeman** [comment]
As expected. I raised this issue a year ago. It was ignored then as a non issue. A user comes along with the same comment and you close it again. ;(

**Comment by Magnytu2** [comment]
For your information: I found out why my multilingual demos usually work. If I start from a brand new Joomla from joomla.fr and so I download two languages. 
If I start from Joomla.org there is only one language. 
Maybe you just need to install both languages (fr and eng) on .org and you get around the problem?
