### ISSUE TITLE
[4.0] Installation Password Length

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30406]
### Steps to reproduce the issue
Install joomla

### Expected result
Instant notification that the password doesnt meet the minimum length criteria of 12 characters

### Actual result
No notification until the form is submitted.

### Additional comments
Viewing the source of the paassword field shows a min length of 4

`<input type="password" name="jform[admin_password]" id="jform_admin_password" value="" autocomplete="new-password" class="form-control required form-control-danger invalid" maxlength="99" required="" data-min-length="4" aria-invalid="true">
`

**Comment by brianteeman** [comment]
The problem looks like it starts here
https://github.com/joomla/joomla-cms/blob/0ebb8a62ea6b9569db0a452b132907a85541ac71/libraries/src/Form/Field/PasswordField.php#L157

**Comment by infograf768** [comment]
Imho it uses the minimum defined here as we are in installation client.
https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Form/Rule/PasswordRule.php#L50

		$minimumLength    = isset($element['minimum_length']) ? (int) $element['minimum_length'] : 12;

**Comment by brianteeman** [comment]
If it did then it would not be generating the code I showed for the field.

The line you showed is for the validation on submit

**Comment by infograf768** [comment]
If I do not mistake this element would work only when the meter is used as otherwise the js is not used and these parts of the code are ignored.

Basically `strengthmeter="true"` is not present in the installation password field

```
if ($meter)
{
	$wa->useScript('field.passwordstrength');
```

**Comment by infograf768** [comment]
To test, I added `strengthmeter="true"` to setup.xml
And indeed it accepts passwords of 4 characters minimum
![passwordstrength_installation](https://user-images.githubusercontent.com/869724/90600224-74712d00-e1f6-11ea-8283-dea59de49ed6.gif)

If I modify to `$this->minLength    = 12;` then, curiously although the green bar is not complete, we get a success message under the meter.

![passwordstrength_installation_12](https://user-images.githubusercontent.com/869724/90600864-93bc8a00-e1f7-11ea-800b-26aa6da40583.gif)

Therefore I guess something is wrong in the meter somewhere...

@zero24

**Comment by Quy** [comment]
Partial fix in #30424 except for that it is still possible to go to the next page if password doesn't meet the minimum length criteria of 12 characters to be fixed in a separate PR unless someone can propose a solution.

**Comment by brianteeman** [comment]
Closing as per #30424
