### ISSUE TITLE
Bootstrap 5 hurry

### ISSUE THREAD

**Issue by 1337180** [joomla/joomla-cms#30410]
Joomla! 4 got to be finnaly huge. There will be Bootstrap 5 in the end of the year. I know its alpha1 version, but alpha 2 is around the corner. Whatever. How about to stydu alpha versions and when will be beta out you can upgrade/replace Bootstrap to 5. In the end of the year there will be Joomla! 4 with bootstrap 5 ready to future.
This steps are easy to reproduce.

**Comment by ReLater** [comment]
Please read related https://github.com/joomla/joomla-cms/issues/29944#issuecomment-654227683

BS 5 is still alpha. Nobody knows for sure when a RC or stable version will come.
