### ISSUE TITLE
[4.0] Tags - Options: Layout is not responsive

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#30423]
### Steps to reproduce the issue
Create a new tag
Click on tab options
change the width of the browser window from 768 to ~ 1600 Pixel

### Actual result
![screen shot 2020-08-19 at 19 10 47](https://issues.joomla.org/uploads/1/5201bc08926c6f003f7377cea0b5a915.jpg)

### System information (as much as possible)
4.0.0-beta4-dev

**Comment by Quy** [comment]
Duplicate #30285
