### ISSUE TITLE
Disable super admin gives error message

### ISSUE THREAD

**Issue by gwsdesk** [joomla/joomla-cms#30427]
### Steps to reproduce the issue
Try to disable _another_ super admin by clicking the disable button next to that super

### Expected result
disabled

### Actual result

Error message pops up: "Error
The email address you entered is invalid. Please enter another email address."

This is actually correct since that account has no email in its profile. However if that is the case I would expect by clicking the green button on the admin overview names etc to open the profile so an email can be added. However I do think that with or without email the disable function on the overview page should work even without an email?

### Additional comments

This is actually correct since that account has no email in its profile. However if that is the case I would expect by clicking the green button on the admin overview names etc to open the profile so an email can be added. However I do think that with or without email the disable function on the overview page should work even without an email?

**Comment by brianteeman** [comment]
How were you able to create a user with no email address?

**Comment by gwsdesk** [comment]
Directly with the mysql script as published on "documentation.joomla.org
"password recovery" (admin2/secret)

**Comment by brianteeman** [comment]
For me this is something we should not address as whenever someone edits the database directly there can be all sorts of issues

**Comment by joomdonation** [comment]
Agree with @brianteeman. I just tried and could disable other super users without any problem in latest Joomla 4.2. So this is an invalid issue (we do not have responsibility when someone changes data directly via database), I'm closing.
