### ISSUE TITLE
utf8 mysql/mariadb

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30425]
I've searched but I couldnt find the answer

When setting up a new server for joomla what are the correct/ideal settings for

collation_connection
collation_database 
collation_server

@richard67

**Comment by richard67** [comment]
Ideal for Joomla would be all 3 are `utf8mb4_unicode_ci`.

The database collation is only a default used when during a create table statement no character set and collation is speficied. We do that for all core tables, but some 3rd party extensions might not do that.

**Comment by brianteeman** [comment]
Thanks - should this be documented somewhere? Recommended settings?

**Comment by richard67** [comment]
In my opinion yes. But it‘s a recommendation. Joomla work also work with different settings. You only risk that 3rd party extensions make problems if they make join or union in sql statements with core tables and have a character set and collation which doesn’t fit, so you get illegal mix of character set or collations error.

**Comment by brianteeman** [comment]
so for my own education is there any problem with 

MariaDB [(none)]> SHOW VARIABLES LIKE 'collation%';
+----------------------+-------------------+
| Variable_name        | Value             |
+----------------------+-------------------+
| collation_connection | utf8_general_ci   |
| collation_database   | latin1_swedish_ci |
| collation_server     | latin1_swedish_ci |

**Comment by richard67** [comment]
Not with the core. Only possibly problems with 3rd party extensions when they use the database default and make joins or union statements in sql. This can be the case e.g. with old 3rd party smart search plugins, I recently had such a case when I helped with a forum issue.

**Comment by astridx** [comment]
Is there any advantage to use `utf8_general_ci` or `latin1_swedish_ci` instead of `utf8mb4_unicode_ci`?

**Comment by richard67** [comment]
> Is there any advantage to use `utf8_general_ci` or `latin1_swedish_ci` instead of `utf8mb4_unicode_ci`?

No. Don’t use utf8 without mb4 as character set if the dB supports utf8mb4 for a Joomla database, and so don‘t use utf8_general_ci, and the Swedish Latin stuff has historic reasons.

**Comment by richard67** [comment]
Ok, there would be an advantage that utf8 needs less space that utf8mb4, and the singlebyte Latin character set needs less space than utf8. But the disadvantages mixing these character sets with the utf8mb4 of the core as mentioned before are more serious than the disk space aspects, I would say.
