### ISSUE TITLE
[4.0] Fieldset descriptions need rendering to be more consistent

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#30432]
### What needs to be fixed

In the global configuration, tab descriptions (corresponding to the fieldset's 'description' attribute in the xml file of each component) have an information icon and can contain html tags. 
Descriptions in module instances, for instance, do not show the icon and cannot contain html tags. 

### Why this should be fixed

For consistency and for improving the format of the info given to the users.

### How would you fix it

in the _joomla.edit.params_ layout:

- add the icon before the fieldset description
`<span class="fas fa-info-circle" aria-hidden="true"></span><span class="sr-only"><?php echo Text::_('INFO'); ?></span>`

- remove the escaping of the description.

### Side Effects expected

None.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/30435
