### ISSUE TITLE
[4.0] All fieldsets should be able to show a description

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#30433]
### What needs to be fixed

When fieldsets are children of a fieldset, descriptions are not rendered, if they exist.
This is the case, for instance, when configuring module instances.

### Why this should be fixed

To better inform the users. Having a possible description explaining the use of the fields within the fieldset can improve understanding.
It will also be consistent with com_config which allows for descriptions for all fieldsets.

### How would you fix it

In the _joomla.edit.params_ layout, add a bloc for the fieldset description if it has a parent and is not a grand child.

### Side Effects expected

None.

**Comment by obuisard** [comment]
Code suggested:

```
if (!$isGrandchild && $hasParent)
{
	echo '<fieldset id="fieldset-' . $name . '" class="options-form ' . (!empty($fieldSet->class) ? $fieldSet->class : '') . '">';
	echo '<legend>' . $label . '</legend>';

	// Include the description when available
	if (isset($fieldSet->description) && trim($fieldSet->description))
	{
		echo '<div class="alert alert-info">';
		echo '<span class="fas fa-info-circle" aria-hidden="true"></span><span class="sr-only">' . Text::_('INFO') . '</span> ';
		echo Text::_($fieldSet->description);
		echo '</div>';
	}

	echo '<div class="column-count-md-2 column-count-lg-3">';
}
```

**Comment by infograf768** [comment]
I know the possible code ;)
I meant how to test it? Please suggest a modification in a module to have such fieldsets.
Thanks

**Comment by infograf768** [comment]
Code would be modified here for the layout
https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/edit/params.php#L117-L122

**Comment by obuisard** [comment]
There is no use case in the core.
What I suggest is to be able to show a description in any fieldset like in the following example:

![Possible fieldset child description](https://user-images.githubusercontent.com/5964177/90916177-9e6d4f80-e3ae-11ea-8e28-39d30fec240e.jpg)

**Comment by obuisard** [comment]
To test in the core:
- open the mod_articles_category.xml
- in the fieldset 'filtering' separate the fields by putting them inside 2 fieldsets
- add a description attribute to the fieldset 'filtering'

```
<fieldset name="filtering" label="MOD_ARTICLES_CATEGORY_FIELD_GROUP_FILTERING_LABEL" description="Top most description">

<fieldset name="filtering_child1" label="Child 1" description="Child description 1">
[some fields]
</fieldset>
<fieldset name="filtering_child2" label="Child 2" description="Child description 2">
[the remaining fields]
</fieldset>

</fieldset>
```

Without the updated code, the descriptions won't show. With the updated code, they will.

**Comment by infograf768** [comment]
Closing as we have patch
https://github.com/joomla/joomla-cms/pull/30450

for both here and https://github.com/joomla/joomla-cms/issues/30433
