### ISSUE TITLE
COM_LANGUAGES_FIELD_LANG_CODE_LABEL

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#30438]
### Steps to reproduce the issue
This languagestring and the value:

COM_LANGUAGES_FIELD_LANG_CODE_LABEL="URL Language Prefix"

I am not native English but it must be Suffix? Or like in Joomla 3.x: "URL Language Code" ![screen shot 2020-08-21 at 10 17 16](https://issues.joomla.org/uploads/1/6e4ecaac1b1449017221c92587b44045.png)

**Comment by infograf768** [comment]
Totally agree. This change makes no sense. 3.x was fine.

**Comment by infograf768** [comment]
Making PR. Also reinstating the description as it is an important hint.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/30440
