### ISSUE TITLE
[4.0] Display of the registration button

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#30442]
### Steps to reproduce the problem
Frontend registration of a Joomla user

### Expected result
button below the e-mail address field must have the same space above as the login button on the right

### Current result
the button is glued at the top
![Créer_un_compte-3](https://user-images.githubusercontent.com/26197929/90897821-febbbb80-e3c5-11ea-92a3-589288181c9c.jpg)

**Comment by Quy** [comment]
Duplicate #29138. Labels and button are affected.

**Comment by Magnytu2** [comment]
@Quy Why close? There is no connection between the two problems! I'm talking about the space between the button and the control.

**Comment by Quy** [comment]
It is a duplicate issue relating to `control-group`. Once padding is added to this class, it will fix the spacing issue.

![30442](https://user-images.githubusercontent.com/368084/90915400-4fb2bc00-e394-11ea-9c1c-1c64321d1f1f.png)

**Comment by Quy** [comment]
Thank you for testing/reporting!
