### ISSUE TITLE
Error in registration.xml to map translation label 

### ISSUE THREAD

**Issue by nono1974** [joomla/joomla-cms#30448]
### What needs to be fixed

The file \components\com_users\models\forms\registration.xml is buggy and not referencing the right Label and Description of translation. 

		<field
			name="password1" 
			type="password"
			label="COM_USERS_PROFILE_PASSWORD1_LABEL"
			description="COM_USERS_DESIRED_PASSWORD"
			autocomplete="off"
			class="validate-password"
			field="password1"
			filter="raw"
			size="30"
			validate="password"
			required="true"
		/>

		<field
			name="password2"
			type="password"
			label="COM_USERS_PROFILE_PASSWORD2_LABEL"
			description="COM_USERS_PROFILE_PASSWORD2_DESC"
			autocomplete="off"
			class="validate-password"
			field="password1"
			filter="raw"
			message="COM_USERS_PROFILE_PASSWORD1_MESSAGE"
			size="30"
			validate="equals"
			required="true"/>

### Why this should be fixed

It should be fixed because not mapping the right things (it is like a copy and paste mistake)

### How would you fix it

I would replace 
label="COM_USERS_PROFILE_PASSWORD1_LABEL"
by
label="COM_USERS_REGISTER_PASSWORD1_LABEL"

and replace 
label="COM_USERS_PROFILE_PASSWORD2_LABEL"
by
label="COM_USERS_REGISTER_PASSWORD2_LABEL"

It seems to have similare confusion in the rest of the form

### Side Effects expected
It is confusing to amend the translation fileld (xx_XX.com_users.ini) and tune the registration form to make it more explicit.
Some users don't have the reflex to pass the mouse on the name field to display the modal and get stuck to register...it seems to be obvious but some clients don't know how to...it is the hard life UX vs client exeperience !

**Comment by infograf768** [comment]
1. There are some changes for this file in this PR (which is RTC). See https://github.com/joomla/joomla-cms/pull/30437
2. The constant is common to profile.xml and registration.xml. No need for 2 different constants. Only the value counts.

**Comment by infograf768** [comment]
Closing as expected in J3 as well as J4.
