### ISSUE TITLE
[4.0] Module Articles Latest show unpublished and trashed articles

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#30445]
### Steps to reproduce the issue
Create a category with a least 5 articles, unpublish and trash some of them
Create Module Articles Latest for this category
Choose a frontend position and publish the module
The problem occurs with all "order" Options
![screen shot 2020-08-21 at 15 23 25](https://issues.joomla.org/uploads/1/f3db452b0868244e7eacced947463859.jpg)
Don't login on the frontend

### Actual result
The module shows also articles which are unpublished or trashed
![screen shot 2020-08-21 at 15 26 55](https://issues.joomla.org/uploads/1/47abaacbfe8fa0c95e2f21452e634ad5.jpg)

![screen shot 2020-08-21 at 15 26 15](https://issues.joomla.org/uploads/1/fe618168c238176d50ce459d643b5bb3.jpg)

### System information (as much as possible)
Joomla 4.0 beta

**Comment by brianteeman** [comment]
I can not replicate this.

**Comment by chmst** [comment]
I can replicate it. 
The filter.condition is not set to 1 = published in the module helper. Setting the filter helps at once but I think that the filter condition has more implications and the model articles (and featured) need a review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30445">issues.joomla.org/tracker/joomla-cms/30445</a>.</sub>

**Comment by chmst** [comment]
Please test #30459 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30445">issues.joomla.org/tracker/joomla-cms/30445</a>.</sub>

**Comment by Quy** [comment]
Please test PR #30459
