### ISSUE TITLE
[4.0] Display of the registration button

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#30443]
### Steps to reproduce the problem
Frontend registration of a Joomla user

### Expected result
button below the e-mail address field must have the same space above as the login button on the right

### Current result
the button is glued at the top
![Créer_un_compte-3](https://user-images.githubusercontent.com/26197929/90897927-2579f200-e3c6-11ea-928e-98c8103c1abe.jpg)

**Comment by jeckodevelopment** [comment]
Closing as duplicate of #30442
