### ISSUE TITLE
Description not visible when I hover over labels.

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#30451]
### Steps to reproduce the issue
I can't imagine nobody saw this before. Maybe this is double, then sorry (can't find an issue).

Go to (By example) Users and select a User. 
If you hover a label there is no description visible. Tried in Chrome, Firefox and Edge.
This in on every detail screen.

**Comment by Quy** [comment]
This is intentional. Please see PR #22165.

**Comment by brianteeman** [comment]
There is no description on hover because there is no description to display.

**Comment by infograf768** [comment]
Closing as intentional.
Please, if you see a place where we do need descriptions if the label is not enough, as we did here https://github.com/joomla/joomla-cms/pull/30440 , create a new issue.

**Comment by MartijnMaandag** [comment]
I do understand and support the accessibility issue from @brianteeman  [#22165](https://github.com/joomla/joomla-cms/pull/22165) 
We now have a large number of descriptions that are no longer used, but are still present in the language files and need to be translated and approved.
I understand that @infograf768  has now made the description visible for one case [#30440](https://github.com/joomla/joomla-cms/pull/30440).
I am not technical, but is it possible to make this solution general and use @infograf768 's solution wherever the hover was shown in Joomla 3.x?
If we don't need the description, we can delete the languagestring.

**Comment by brianteeman** [comment]
@MartijnMaandag 
To the best of my knowledge there are no descriptions that are not used
To the best of my knowledge where there is a description it is displayed on screen and not as a hover/tooltip

Please can you let me know the details of any description that is still present and is not displayed on the screen as that is definitely a bug and should not happen.

> I understand that @infograf768 has now made the description visible for one case #30440.

This was done by adding the string and not "making it visible"

>I am not technical, but is it possible to make this solution general and use @infograf768 's solution wherever the hover was shown in Joomla 3.x?

That already exists. Any description is displayed on screen

> If we don't need the description, we can delete the languagestring.

They should already be deleted - I deleted thousands

Are you using an update language file?

**Comment by MartijnMaandag** [comment]
You are completely right. I found the tooltip in Joomla 3.x very useful for inexperienced users and missed them in Joomla 4. I just thought they weren't shown anymore. A solution as I mentioned would have been more beautifull.

**Comment by infograf768** [comment]
@MartijnMaandag 
As you use crowdin, the deleted description strings are no more present and therefore do not need to be approved.

As I said above, many of these descriptions were redundant with the label.
If you miss really an important one, please let it know.
