### ISSUE TITLE
[4.0] Missing JHELP strings

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30457]
### Steps to reproduce the issue

There are 5 new Help links for Administrator Modules status position items. Select any one and click the Help button. 

### Expected result

A help page

### Actual result

A 404 page

### Additional comments

I have created the pages and now we need the following link translations in en-GB/joomla.ini - can someone fix this?

JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_FRONTEND="Extensions_Module_Manager_Admin_Frontend_Link"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_MESSAGES="Extensions_Module_Manager_Admin_Messages"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_POST_INSTALLATION_MESSAGES="Extensions_Module_Manager_Admin_Post_Installation_Messages"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_STATUS_USER="Extensions_Module_Manager_Admin_Status_User"
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_VERSION="Extensions_Module_Manager_Admin_Version"

Note that the new Help pages have to be 'translated' before they appear instead of 404. I will ask the translation team to see to that.

**Comment by brianteeman** [comment]
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_VERSION
this string is used twice in error

mod_loginsupport
mod_version

I will prepare a PR to fix that and the strings - so you will need to create an additional page for
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_LOGIN_SUPPORT=Extensions_Module_Manager_Admin_Login_Support"

**Comment by brianteeman** [comment]
See #30458

**Comment by ceford** [comment]
I have created Extensions_Module_Manager_Admin_Login_Support source. Thank you. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30457">issues.joomla.org/tracker/joomla-cms/30457</a>.</sub>
