### ISSUE TITLE
[4.0] module tabs column breakpoint

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#30454]
### What needs to be fixed
Create a custom module in the Joomla backend.
Go to Options tab
There is different layout on different browser:

Firefox 79.0 (64 bit) @ Ubuntu 20.04
![image](https://user-images.githubusercontent.com/906604/90960557-bde5a480-e4a2-11ea-8a34-30d6955d831d.png)

Chrome 84.0.4147.125 (Build ufficiale) (a 64 bit) @ Ubuntu 20.04
![image](https://user-images.githubusercontent.com/906604/90960565-c63ddf80-e4a2-11ea-8812-ce9e763eaed9.png)

### Side Effects expected
Same layout horizontal or vertical, but the same on the same screen size

**Comment by paternax** [comment]
I confirm this issue for 4.0.0-beta4-dev.
It could be the CSS column-count bug in Chrome<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30454">issues.joomla.org/tracker/joomla-cms/30454</a>.</sub>

**Comment by Quy** [comment]
This won't be an issue if/when PR #29706 is merged.

**Comment by Quy** [comment]
Fixed in PR #32422. Thanks for reporting.
