### ISSUE TITLE
Syntax with curly braces is deprecated in lessc.php

### ISSUE THREAD

**Issue by xillibit** [joomla/joomla-cms#30452]
### Steps to reproduce the issue

When a component use the library /libraries/vendor/leafo/lessphp/lessc.inc.php on Php 7.4.x, there are this kind of errors : 

> Deprecated: Array and string offset access syntax with curly braces is deprecated in [APACHE2.4.X-DATA-PATH]/libraries/vendor/leafo/lessphp/lessc.inc.php on line 749
 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in [APACHE2.4.X-DATA-PATH]/libraries/vendor/leafo/lessphp/lessc.inc.php on line 1860
 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in [APACHE2.4.X-DATA-PATH]/libraries/vendor/leafo/lessphp/lessc.inc.php on line 2519
 
> Deprecated: Array and string offset access syntax with curly braces is deprecated in [APACHE2.4.X-DATA-PATH]/libraries/vendor/leafo/lessphp/lessc.inc.php on line 2573

### Expected result

No errors

### Actual result

Errors showed above

### System information (as much as possible)

Php 7.4.x
Joomla! 3.9 and 3.10

**Comment by brianteeman** [comment]
This is a vendor supplied library and we are using the latest release. So it can't be solved in Joomla but would have to be solved upstream.

**Comment by ReLater** [comment]
Just BTW...
leafo/lessphp is dead since years. https://github.com/leafo/lessphp/issues/543 
oyejorge/less.php , too. https://github.com/oyejorge/less.php/issues/371

**Comment by ReLater** [comment]
Addition: And the issue reported here is not the only one concerning leafo/lessphp. There are many many others.

**Comment by xillibit** [comment]
so in this case i close this issue
