### ISSUE TITLE
[4.0] Module re-select image

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#30453]
### Steps to reproduce the issue

1. Create a custom module
2. Go to "Options" tab
3. Select a Background Image
4. Try to select a different image (the modal doesn't appear)
5. Remove the image with the X button
6. Try to select an image (the modal doesn't appear) 

### Expected result
You can change the image

### Actual result
The modal doesn't appear
![image](https://user-images.githubusercontent.com/906604/90960241-94c41480-e4a0-11ea-9572-c3ce0fb5fd67.png)

### System information (as much as possible)
Nightly Joomla of Saturday, 22 August 2020 02:00:33 UTC
Firefox 79.0 (64 bit) @ Ubuntu 20.04
Chrome 84.0.4147.125 (Build ufficiale) (a 64 bit) @ Ubuntu 20.04

### Additional comments
I create a custom module with 2 image and another module with repeatable filed with media.
After you select an image the other image can't selected (images for different fields, but the same page).

**Comment by dgrammatiko** [comment]
I can't replicate, can you please share if you have any console errors in the browser?

**Comment by infograf768** [comment]
Confirmed.
`Uncaught TypeError: this.querySelector(...) is null
    show http://localhost:8888/sample/joomla40/media/system/js/fields/joomla-field-media.min.js:1`

in the non minified file
`joomla-field-media.js:252:12`

**Comment by dgrammatiko** [comment]
@infograf768 can you please enable debug to get the line number that throws the error?

**Comment by infograf768** [comment]
`      this.querySelector('[role="dialog"]').open();`

**Comment by dgrammatiko** [comment]
can you try this:
```js
    show() {
      const button = this.querySelector(this.buttonSaveSelected);
      const modal = `imageModal_${this.input.id}`;
      const modalElement = this.querySelector(modal);

      if (!button || !modalElement) {
        throw new Error('Misconfiguaration...');
      }

      modalElement.open();

      Joomla.selectedFile = {};

      button.addEventListener('click', this.onSelected);
    }
```

build/media_source/system/js/fields/joomla-field-media.w-c.es6.js around line 194

**Comment by infograf768** [comment]
To replace entirely
```
    show() {
      this.querySelector('[role="dialog"]').open();

      Joomla.selectedFile = {};

      this.querySelector(this.buttonSaveSelected).addEventListener('click', this.onSelected);
    }
```

??

**Comment by dgrammatiko** [comment]
yes, replace the whole show function

**Comment by infograf768** [comment]
`Uncaught Error: Misconfiguaration...`

**Comment by infograf768** [comment]
have to go. will be back later.

**Comment by dgrammatiko** [comment]
Please test https://github.com/joomla/joomla-cms/pull/30455
