### ISSUE TITLE
[4.0] Error Message when changing status of an article which has set tag(s)

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#30465]
### Steps to reproduce the issue
Create an article
Set a tag in the article and save
Go to the articles overview and change the status. It appears the error message: Error, Unknown column 'core_checked_out' in 'where clause'
By changing the status in the article itselef the message doesn't appear

### Actual result
![screen shot 2020-08-24 at 14 39 06](https://issues.joomla.org/uploads/1/c8c503f1a3893140f59ee94769289cde.jpg)

### System information (as much as possible)
4.0.0-beta4-dev

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30466.
