### ISSUE TITLE
[3.10] SimplePie - Update Information Unavailable 

### ISSUE THREAD

**Issue by bato3** [joomla/joomla-cms#30472]
### Steps to reproduce the issue

I am trying to update joomla (by update channel) to 3.10.0-alpha1(from 3.9, originally from 1.5), but the SimplePie library is blocking the update process.

##### Update Information Unavailable

Extension Name | Extension Type | Update Compatible Version | Currently Compatible Version | Installed Version
-- | -- | -- | -- | --
SimplePie | Library | No Compatibility Information | No Compatibility Information | 1.2

Data from  sql
```sql
INSERT INTO `jos37_extensions` (`extension_id`, `package_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`) VALUES
(101, 0, 'SimplePie', 'library', 'simplepie', '', 0, 1, 1, 1, '{\"name\":\"SimplePie\",\"type\":\"library\",\"creationDate\":\"2004\",\"author\":\"SimplePie\",\"copyright\":\"Copyright (c) 2004-2009, Ryan Parman and Geoffrey Sneddon\",\"authorEmail\":\"\",\"authorUrl\":\"http:\\/\\/simplepie.org\\/\",\"version\":\"1.2\",\"description\":\"LIB_SIMPLEPIE_XML_DESCRIPTION\",\"group\":\"\",\"filename\":\"simplepie\"}', '', '', '', 0, '0000-00-00 00:00:00', 0, 0);
```

### System information (as much as possible)

- Joomla! 3.10.0-alpha1
- Apache/2.4.39 (Win64) OpenSSL/1.0.2s PHP/7.4.9 
-  10.3.15-MariaDB - mariadb.org binary distribution, cp1252 West European (latin1) 

### Additional comments
~~[Info] Finally I choose update by web-upload, but this don't finish correctly (database update)~~ I thought Joomla 4 was a problem, so I installed it via file-upload...

**Comment by bato3** [comment]
This could be error on finish migration to `3.10.0-alpha1` from latest 3.9 stable.

//confirmed, this was last stage migration to `3.10.0-alpha1`

**Comment by brianteeman** [comment]
I dont see anything in the information you provided to indicate that update is blocked

**Comment by bato3** [comment]
During update to `3.10` on stage [/administrator/index.php?option=com_joomlaupdate&view=update&layout=finaliseconfirm](#) i can't finalize upgrade because extension `SimplePie` was listed in section **Extensions Pre-Update Check** *Update Information Unavailable* 

I start update from `v 3.6.4`.

I have this extension marked as protected on my panel (uninstall option is disabled). This could be some relic from Joomla 1.5 migration.

**Comment by zero-24** [comment]
Finalise confirm should just ask you for your SU Login Informationen

**Comment by zero-24** [comment]
Seems your upgrade failed to apply this sql changes that would have dropped the entry from the database: https://github.com/joomla/joomla-cms/blob/d3fb98cb9ba20a6e03b78ba7ee269b336c04862f/administrator/components/com_admin/sql/updates/mysql/3.6.0-2016-05-06.sql

**Comment by bato3** [comment]
Okay, looks like version 3.10 is doing some testing that version 4 doesn't.

OT: @zero-24  you could point me to a code that is responsible for these tests. Thanks in advance.

**Comment by zero-24** [comment]
What kind of tests you are looking for?

**Comment by bato3** [comment]
@zero-24 About `Extensions Pre-Update Check`. 

Several of my extensions also fail this test. And I wanted to see what needs to be improved in them. I've corrected everything [joomla-namespace-checker](https://github.com/vortrixs/joomla-namespace-checker) showed, but it still failed the test.

**Comment by zero-24** [comment]
Can you show me the results of the pre upgrade checker? The only checks we do there is with the updater and whether you mark your updates as compatible with 4.x or not. We do not do any code checks on the extensions.

**Comment by bato3** [comment]
Unfortunately, I did not keep those data.

Thank you for your help, I will check how to correct it in the manifest.

**Comment by zero-24** [comment]
Take a look here: https://github.com/zero-24/plg_system_httpheader/blob/master/update.xml

This is the tag we check in the upgrade checker: https://github.com/zero-24/plg_system_httpheader/blob/master/update.xml#L22

Once we finde one for [4.x](https://github.com/zero-24/plg_system_httpheader/blob/master/update.xml#L43) we show the result   in the checker. Feel free to reach out to me when you need more help on that.
