### ISSUE TITLE
Could not delete data via privacy removal request due to missing CSRF token

### ISSUE THREAD

**Issue by ldemirova** [joomla/joomla-cms#30478]
### Steps to reproduce the issue
1. Create some privacy request for removal of data.
2. Login into admin panel and open the view of this request (https://<hostname>/administrator/index.php?option=com_privacy&view=request&id=1).
3. Try to delete the data via "Delete Data" button.

### Expected result
The data is deleted.

### Actual result
Empty window with only "The most recent request was denied because it had an invalid security token. Please refresh the page and try again." is displayed.

### System information (as much as possible)
I am using Joomla 3.9.20.

### Additional comments
It looks like the CSRF token is not passed while deleting trough this button.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30479.
