### ISSUE TITLE
[4.0][CLI] Database check / database migration / update verification

### ISSUE THREAD

**Issue by bato3** [joomla/joomla-cms#30477]
### Describe the solution you'd like
In the simplest version, a CLI implementation of `implementation /administrator/index.php?option=com_installer&view=database` from J3.

They could also do integrity checks the database and the data, clear old dictionaries, re-index search metadata...

### Additional context
I'm try update Joomla, but it failed. The database update process did not complete correctly. Some tables are missing, some columns are missing.

**Comment by richard67** [comment]
> I'm try update Joomla, but it failed. The database update process did not complete correctly. Some tables are missing, some columns are missing.

@bato3 Is this just the use case for your feature request? Or did you really have failed update, and this issue here is related to that?

**Comment by bato3** [comment]
This is an idea that I came up with when I had trouble updating the database.

Currently there is an export / import option. `Fix` is missing. The best option would be "integrity check".

**Comment by alikon** [comment]
please test #42568
