### ISSUE TITLE
J3.9.21 - Class 'Joomla\CMS\Layout\BaseLayout' not found

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30483]
### Summary

I've just updated one of my sites from 3.9.20 to 3.9.21 and directly after the update process, the site threw an error:

> Warning: Class '\Joomla\CMS\Layout\FileLayout' not found in /xxxxx/libraries/loader.php on line 663

> Error: Class 'Joomla\CMS\Layout\FileLayout' not found: Class 'Joomla\CMS\Layout\BaseLayout' not found

### System information (as much as possible)

Joomla: 3.9.21
PHP: 7.4

**Comment by HLeithner** [comment]
Is this in frontend or backend or always,  do you have a complete stacktrace for us?

**Comment by alikon** [comment]
curious me too, i've updated a couple of intranet sites from 3.9.20 to 3.9.21 ----  fully core ie without any templates..... and with postgresql without a glitch ......

**Comment by C-Lodder** [comment]
@HLeithner Both backend and frontend. Wasn't able to get a full stack trace for some reason.
I eventually managed to update by deploying it manually.

Couldn't replicate my local instance, so I'll close this for now
