### ISSUE TITLE
[4.0] A question about JHelp strings

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30487]
### Steps to reproduce the issue

As an example, go to Users -> User Actions Log and click the Help button

### Expected result

A Help page title related to the title of the page it helps, in this case User Actions Log.

### Actual result

The help page title says Components Actionlogs

### Additional comments

There are quite a lot of pages where the title has little resemblance to the page it helps. I have been working on the Help pages with a member of the translation team. In this case we have moved the original page to User Actions Log and created a redirect page with the original name. This also for the default /en and /nl versions. The snag is that the English version is delivered with the title of the redirect page (the original title). Non English versions work OK because the page title is translated as a Display Title. So to make this work properly we need to ask for the keystring to be changed:

JHELP_COMPONENTS_ACTIONLOGS="Components_Actionlogs" to JHELP_COMPONENTS_ACTIONLOGS="User Actions Log"

So my question is should we also ask for the key to be changed to match? I anticipate there will be a bundle of such changes to make. And when completed we can delete the redirect files. So no changes just now. Just comments on this suggestion.

**Comment by brianteeman** [comment]
This is more a question for the docs team

**Comment by ceford** [comment]
This issue has been resolved with the renaming of all of the Help files and commit of new strings.
