### ISSUE TITLE
Update server for 3.9 Nightly Builds is broken (wrong link in XML)

### ISSUE THREAD

**Issue by dmitriy-cloudaccess** [joomla/joomla-cms#30484]
XML with update links https://update.joomla.org/core/nightlies/next_patch_extension.xml contains wrong download url.
Download URL https://developer.joomla.org/nightlies/Joomla_3.9.22-dev-Development-Update_Package.zip is incorrect, file isn't downloadable.

**Comment by zero-24** [comment]
Yes ist is because the repo has not yet been reset to development state but the XML is correct the nighly build version isnt. cc @HLeithner

**Comment by HLeithner** [comment]
Thanks for the report, I will fix this shortly.

**Comment by HLeithner** [comment]
Fixed, thx tobias
