### ISSUE TITLE
[4.0] Joomla Help - Cache: Clear Expired Cache not used in Joomla 4

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30488]
### Steps to reproduce the issue

Go to Help -> Joomla Help
Scroll down to Cache: Clear Expired Cache
Select it

### Expected result

A Help page

### Actual result

A Help Page ... But...

### Additional comments

I don't think that page is used in Joomla 4.

**Comment by brianteeman** [comment]
That is correct. Expired cache is not part of the clear cache page in joomla.

I will do a PR to fix the joomla end. Probably needs to have any content for expired cache added to the clear cache page on the docs

**Comment by brianteeman** [comment]
see #30490
