### ISSUE TITLE
[4.0] Tabs do exceed the viewport in options

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#30486]
### Steps to reproduce the issue
- Install DPCalendar from [here](https://joomla.digital-peak.com/download/dpcalendar-development/dpcalendar-development-7-4-4-7980)
- Log in on the back end
- Open DPCalendar options

### Expected result
Tabs do not exceed the viewport.

### Actual result
Tabs do exceed the viewport.

### System information (as much as possible)
Joomla 4 Beta 3

**Comment by Quy** [comment]
Duplicate #28799
