### ISSUE TITLE
Admin cache not cleaned on module changes

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#30492]
### Steps to reproduce the issue

Enable Joomla conservative caching.
Publish/unpublish/edit/trash any administrator module in `cpanel` position

### Expected result

The module appears/disappears/etc in admin dashboard

### Actual result

No changes are applied in admin dashboard.

### Additional comments

`com_modules` cache group is not deleted in admin cache.

**Comment by Quy** [comment]
Please test PR #30565
