### ISSUE TITLE
[4.0] Upload zip on Cpanel alert Virus

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#30494]
### Steps to reproduce the issue

On Cpanel file manager try to upload zip of full version Joomla 4

### Expected result

As 3.9.22 I expect file is uploaded without errors:
![immagine](https://user-images.githubusercontent.com/906604/91418374-550b7d00-e852-11ea-8032-3f65b7d9eb4f.png)

### Actual result

Uploading alert a Virus in the ZIP file:
![immagine](https://user-images.githubusercontent.com/906604/91418430-6c4a6a80-e852-11ea-8edf-0d23f1f40a35.png)

### System information (as much as possible)

Cpanel  86.0.22

### Additional comments

I'm sure it is a false positive, but didn't undertood wich is the file that generate it

**Comment by zero-24** [comment]
Maybe because it includes JS files?

VirusTotal seems to be fine with it: https://www.virustotal.com/gui/file/91b30e5a1098299cf431f6185f3d6bd204e116e842f766d573c0833eda67ee37/detection

**Comment by Razzo1987** [comment]
The hosting say that the problem is
in `administrator/components/com_templates/tmpl/template/default_updated_files.php` that contains on line 59:

`<?php echo base64_decode(`

**Comment by infograf768** [comment]
Full line is
`<a href="<?php echo Route::_('index.php?option=com_templates&view=template&id=' . (int) $value->extension_id . '&file=' . $value->hash_id); ?>" title="<?php echo Text::_('JACTION_EDIT'); ?>"><?php echo base64_decode($value->hash_id); ?></a>`

We have 121 occurrences in core of `base64_decode(`

**Comment by richard67** [comment]
Ping @SniperSister ;-)

**Comment by SniperSister** [comment]
@Razzo1987 base64_decode is a legitimate function call, the alert is a false positive

**Comment by Razzo1987** [comment]
@SniperSister I know it is a false positive. I write it in my first post...
I think we have a problem if cPanel (852,423 live websites) can't upload Joomla 4 zip file.

No one have a contact directly with cPanel?

**Comment by zero-24** [comment]
> No one have a contact directly with cPanel?

Your host is a customer of cPanel right? That might be the fastest way to get contact with them

**Comment by Razzo1987** [comment]
@zero-24 They have proposed to put the directory under control exclusions.
But it's a patch for my account, not a permanent fix.

@ggenovino also reports me the same problem (different hosting).

In the Joomla 3 version the function `base64_decode` is never used?

**Comment by zero-24** [comment]
> In the Joomla 3 version the function base64_decode is never used?

It is also used in Joomla 3 as this is total valid method to use ;) Example is the tempalte manager

**Comment by Razzo1987** [comment]
I'm doing some test.

**Comment by Razzo1987** [comment]
@SniperSister can you help me with the non-regression test on this PR?
https://github.com/joomla/joomla-cms/pull/30529
