### ISSUE TITLE
[3.X][plugin][actionlog] change the action to joomlaupdate to show the old version (before the update) as well as the new version (after the update)

### ISSUE THREAD

**Issue by sozzled** [joomla/joomla-cms#30499]
### Is your feature request related to a problem? Please describe.

Refers to https://github.com/joomla/joomla-cms/pull/30407 and to forum discussion [here](https://forum.joomla.org/viewtopic.php?f=9&t=981716&p=3612796#p3612458) and [here](https://forum.joomla.org/viewtopic.php?f=9&t=981716&p=3612796#p3612796)

### Describe the solution you'd like

Additionally, if possible, the action log to show the "old" version that J! was updated from as well as the new version that J! was updated to.

### Additional context

See also forum discussion [here](https://forum.joomla.org/viewtopic.php?f=9&t=981716&p=3612796#p3612458) and [here](https://forum.joomla.org/viewtopic.php?f=9&t=981716&p=3612796#p3612796)

**Comment by brianteeman** [comment]
Please summarise the forum comments here.

**Comment by zero-24** [comment]
I guess it is about:
>> It might be nice to see what version of Joomla (or updated extensions) one updated from—that may be asking the impossible—

> I actually think it should be rather easy since we now where the actual version is stored or are stored (for older versions) So me think it should be just (?) another call to the version file(s) to scan for the present installed version and present it in the logs
>
>Maybe a post on issues.joomla.org would be helpful?

https://forum.joomla.org/viewtopic.php?f=9&t=981716&p=3612796#p3612796

**Comment by alikon** [comment]
If we can  find some consensus if this is a welcome feature, and in what J! version this change can should be done .... why not

**Comment by alikon** [comment]
@sozzled can you change the title of the issue, please, so it's more easy to understand the request

**Comment by sozzled** [comment]
Done.  Is that better?

**Comment by alikon** [comment]
above my english skills to answer your question , but surely better than before, thank you, at least for me is as simple as you have performed an update from version A to version B  core or extensions
i'm hoping that have caught you

**Comment by sozzled** [comment]
Correct.

First idea is to modify the actionlog plugin and change the language constant (in the file **../administrator/language/en-GB/en-GB.plg_actionlog_joomla.ini**)

`PLG_ACTIONLOG_JOOMLA_USER_UPDATE="User <a href='{accountlink}'>{username}</a> updated Joomla from %s to {version}"`

where %s is the string containing the old J! version.

Does that make sense?

We can look at updates to extensions later.

**Comment by alikon** [comment]
please test #30714

**Comment by sozzled** [comment]
Thanks very much, @alikon.  Because other people have already tested and confirmed that the PR works, we'll leave things at that and see how it works when the next release of J! happens. :smiley:
