### ISSUE TITLE
[4.0] Joomla Help - Search: Not used in Joomla 4

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30504]
### Steps to reproduce the issue

Go to Help -> Joomla Help in the Administrator Menu
Scroll down the list to Search

### Expected result

That item should not be there - it is not used in Joomla 4

### Actual result

It is there and displays a page copied from Joomla 3 some years ago.

### Additional comments

Strings are present in administrator and api ini files.

**Comment by brianteeman** [comment]
ok - leave it to me

**Comment by brianteeman** [comment]
See #30506
