### ISSUE TITLE
[4.0] Joomla Help - Index column height

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30507]
### Steps to reproduce the issue

Go to Help -> Joomla Help in the Admin menu
Scroll down to the bottom of the list of Help pages
Click one of the Users links.

### Expected result

Something happens

### Actual result

Nothing appears to happen because the iframe containing the Help page is out of sight

### Additional comments

I made the div containing the index the same height as the iframe and scrollable with this inline style:
style="max-height:2100px; overflow-y:scroll"
which appears to do what I need

I have been using this page a lot and this scrolling is driving me nuts! I previously raised an issue suggesting a Javascript solution. I think this is better. I will close the previous issue.

**Comment by brianteeman** [comment]
try max-height:100vh

**Comment by ceford** [comment]
Yes that is better - the index div is easy to use.

**Comment by Quy** [comment]
PR #31092
