### ISSUE TITLE
media path error when options saved

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#30500]
### Steps to reproduce the issue
Navigate to Content >>> Media ... Options
Change the 'Maximum size'
Save

### Expected result
Get message saved

### Actual result
Error
Invalid field: Path to Files Folder
Invalid field: Path to Images Folder

### System information (as much as possible)
Wamp localhost

### Additional comments
This only happens on Wamp localhost not on a remote Host
It happens on fresh 3.9.21 installs and sites updated to 3.9.21

**Comment by SharkyKZ** [comment]
~~Please test PR https://github.com/joomla/joomla-cms/pull/30502.~~

**Comment by SharkyKZ** [comment]
@joomla/security Can you take a look at this? What's the logic in checking that path is equal to path put through `JPath::clean()`?

**Comment by zero-24** [comment]
It is intended to not be out of the root folder for example. What from the path did clean filter that causes the issue?

**Comment by SharkyKZ** [comment]
This line fails because `JPath::check()` runs path through `JPath::clean()` and then it's compared to original non-cleaned path:

https://github.com/joomla/joomla-cms/blob/715eed2f8020763ac7e62717ec552eb522959c45/libraries/src/Form/Rule/FilePathRule.php#L65

So any slash/backslash or duplicate slash discrepancies fail here.

**Comment by zero-24** [comment]
> So any slash/backslash or duplicate slash discrepancies fail here.

yes when it is not a valid path right?

**Comment by Webdongle** [comment]
It worked before the update.  Can you compare how it was before and after the update then fix it?

**Comment by zero-24** [comment]
> It worked before the update. Can you compare how it was before and after the update then fix it?

can you show me the value for that field that you use and that cause issues for you?

**Comment by Webdongle** [comment]
![media options 03](https://user-images.githubusercontent.com/1115202/91589840-515f1f80-e952-11ea-9340-a432bc6efd6e.jpg)
Vhange value of Maximum Size (in MB) and save or just save.  Only fails on wamp localhost not live site or or test site on subdirectory of live site.  One user in the forum has reported that it also fails on  xampp localhost

**Comment by SharkyKZ** [comment]
>yes when it is not a valid path right?

No, it always fails on Windows because slash is used instead of `DIRECTORY_SEPARATOR` in the rule. Changing this alone is not enough because if value contains a slash (e.g. `images/banners`) this still fails on Windows even though Windows supports both slashes and backslashes.

**Comment by zero-24** [comment]
Ok will take a look into it.

**Comment by zero-24** [comment]
@SharkyKZ 

> Hm, no, this isn't right.

why this ins't right? That would be my solution too.

**Comment by zero-24** [comment]
I mean this PR: https://github.com/joomla/joomla-cms/pull/30502

**Comment by zero-24** [comment]
we could also include a str_replace of `/` and `\` with directory seperator to be sure. What do you think?

**Comment by Webdongle** [comment]
@SharkyKZ 
> No, it always fails on Windows because slash is used instead of `DIRECTORY_SEPARATOR` in the rule. Changing this alone is not enough because if value contains a slash (e.g. `images/banners`) this still fails on Windows even though Windows supports both slashes and backslashes.

But it worked upto J3.9.20, it's only emerged since J3.9.21.  Spot the difference between the path in J3.9.2.0 and J2.9.21 and that is where the problem is.  One of the PR's altered the way the path was written

**Comment by zero-24** [comment]
> But it worked upto J3.9.20, it's only emerged since J3.9.21. 

Yes with 3.9.21 we added the path validation rule.

**Comment by zero-24** [comment]
So we have to make sure that path validation rule works correctly

**Comment by SharkyKZ** [comment]
I'm just trying to understand what's the purpose of comparing original path with path put through `JPath::clean()`. Should we just return true if `Path::check()` passes without throwing exceptions?

**Comment by zero-24** [comment]
> Should we just return true if Path::check() passes without throwing exceptions?

That work in that case too. The other check was there to make sure that the path is also passing Path::clean()

**Comment by zero-24** [comment]
@SniperSister @bembelimen can we get your inputs here? Whether we should do that additional check (that has than to be fixed that it passes on valid paths)

**Comment by SniperSister** [comment]
> Should we just return true if Path::check() passes without throwing exceptions?

Sounds good to me

**Comment by zero-24** [comment]
@SharkyKZ do you want to do an PR for that or should I?

**Comment by Webdongle** [comment]
I can test a patch when one is created.

**Comment by SharkyKZ** [comment]
@zero-24 You can do.

**Comment by zero-24** [comment]
PR is: https://github.com/joomla/joomla-cms/pull/30521 Thanks!

**Comment by Nubro01** [comment]
I had this problem on one of my three websites. I noticed that on the site where the problem occured the configuration.php was set to readonly.
Resetting it did not seem to work. After checking security and comparing it with the other two, it stayed readonly unchecked.

I tried setting configuration.php on the 2nd site to readonly and that also now gave the same error, as did the 3th site, which I did not touch?

Rebooting ,clearing cash, nothing helped. Finnally found this issue, so it seems to happen only in 3.9.21
First site has "images\" the other two "images" Checking the media on the first site shows the full system path on the bottom of the browser, the other two just show subfolder name, when present.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30500">issues.joomla.org/tracker/joomla-cms/30500</a>.</sub>

**Comment by Nubro01** [comment]
typo, firsts site has "images\" not "images"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30500">issues.joomla.org/tracker/joomla-cms/30500</a>.</sub>

**Comment by Nubro01** [comment]
not a typo, backslash disappears after enter.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30500">issues.joomla.org/tracker/joomla-cms/30500</a>.</sub>

**Comment by zero-24** [comment]
Hi @Nubro01 yes this is an know issue that is going to be fixed in the next release. You can apply this change until the next release is out: https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/30521.diff
