### ISSUE TITLE
[4.0] JHELP Unused Strings

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30509]
### Steps to reproduce the issue

Code review: The following strings are in joomla.ini but they are not used and there are no associated Help pages:
JHELP_COMPONENTS_COM_CHECKIN_OPTIONS
JHELP_COMPONENTS_COM_PLUGINS_OPTIONS
JHELP_COMPONENTS_INSTALLER_UPDATESITE_EDIT
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_ONLINE
JHELP_EXTENSIONS_MODULE_MANAGER_ADMIN_UNREAD
JHELP_MENUS_MENU_ITEM_CONTACT_CREATE
JHELP_MENUS_MENU_ITEM_USER_LOGOUT

**Comment by brianteeman** [comment]
The first two need to be created on the docs site
The page should be identical (except for title) with https://help.joomla.org/proxy?keyref=Help40:Components_Cache_Manager_Settings&lang=en

**Comment by ceford** [comment]
Got that - will do.

**Comment by ceford** [comment]
There is a snag. It turns out that https://docs.joomla.org/Help4.x:Components_Check-in_Configuration and 
https://docs.joomla.org/Help4.x:Components_Plug-in_Manager_Options already exist. I don't have permission to move them because they have been translated. I have created two new Help pages:
https://docs.joomla.org/Help4.x:Components_Checkin_Options 
https://docs.joomla.org/Help4.x:Components_Plugins_Options
and would like to have the Help key strings changed accordingly. I have it in mind to change a number of help file names to more compatible with Page Titles. For example, I note that Options is better than Configuration and the term Manager seems to be out of favour, except in keys.

**Comment by brianteeman** [comment]
@ceford this is all stuff you should take up with the docs team

**Comment by ceford** [comment]
I recently joined the docs team and I have taken it up with them. They seem content to let me get on with it! Nobody is saying No but nobody is saying Yes either.

**Comment by brianteeman** [comment]
@ceford what is the status with this issue now?

**Comment by ceford** [comment]
This issue is resolved with a complete new set of Help file names - already merged.

**Comment by ceford** [comment]
And thanks for the reminder - I had completely forgotten this one.
