### ISSUE TITLE
[4.0] Webauthn > Error in CredentialsCreation.php on line 92

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#30517]
### Steps to reproduce the issue
- Install J4 at launch.joomla.org
- open User-Account
- Tabs are below each other; "W3C Web Authentication (WebAuthn) Login" show Error:
![Screenshot_2020-08-30 Error 0](https://user-images.githubusercontent.com/70466955/91654932-440a7800-eaad-11ea-90ee-a6e8aa938a10.png)

### Expected result
no Error

### Actual result
see "Steps to reproduce the issue"

### System information (as much as possible)
php: Linux lamp120.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 #1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
dbserver: mysql
dbversion: 5.7.30-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.3.19
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

### Additional comments
CredentialsCreation.php line 92:
![Screen Shot 2020-08-30 at 09 58 33](https://user-images.githubusercontent.com/70466955/91655036-31447300-eaae-11ea-9d0d-7ebe92e45cb4.png)
Site Name is by default empty. Enter a Site name or deactivate Plugin "System - WebAuthn Passwordless Login" the Error is gone.

**Comment by zero-24** [comment]
@Formatio-hippocampi Thanks for your report! Please check out this PR here: https://github.com/joomla/joomla-cms/pull/30520
