### ISSUE TITLE
Joomla pagebreak and class sytem-pagebreak still not working properly

### ISSUE THREAD

**Issue by Notebit** [joomla/joomla-cms#30518]
### Steps to reproduce the issue
The issue was already reported in 2009 and it seems that it was fixed back to the date, but in the last versions of Joomla I can still see it
https://developer.joomla.org/joomlacode-archive/issue-14525.html
The fix suggested in 2009 still works fine to me and it allow to have the correct title and heading generated even using JCE

### Expected result
-having pagebreak creating proper title and header for article sub-pages even if class="system-pagebreak" isn't added at the end of the tag
<hr class="system-pagebreak" title="The page title" alt="The first page" />

### Actual result

Using JCE, it adds class="system-pagebreak" at the beginning and pagebreak plugin doesn't generate the title and heading for sub-pages

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30519.
