### ISSUE TITLE
[4.0] Fatal error on Multilingual site load

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30512]
### Steps to reproduce the issue

I first met this problem on clicking the Admin Title bar 'Open Front end in New Window' icon. The new window says: 'The page isn’t redirecting properly. Firefox has detected that the server is redirecting the request for this address in a way that will never complete. This problem can sometimes be caused by disabling or refusing to accept cookies.'. 

I can reproduce it: open Google Chrome and delete all cookies. Then use this URL: http://localhost/j4beta2/index.php  - sometimes comes back with a trailing / - generates that error message. So try this url: http://localhost/j4beta2/index.php/en/ - and that works. 

I am updating my nightly build almost every day. This is a multilingual site used for testing.

### Additional comments

I stepped through with the debugger to here:

[[type] => 8, [message] => Trying to get property 'sef' of non-object, [file] => /Users/ceford/Sites/j4beta2/plugins/system/languagefilter/languagefilter.php, [line] => 235]

**Comment by ceford** [comment]
Setting site Error Reporting to Maximum I also get this:
( ! ) Notice: Undefined index: nl-NL in /Users/ceford/Sites/j4beta2/plugins/system/languagefilter/languagefilter.php on line 455

I installed nl-NL for testing the Admin interface. I have not created any content with it. The page kept reloading  error messages until stopped manually.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30512">issues.joomla.org/tracker/joomla-cms/30512</a>.</sub>

**Comment by infograf768** [comment]
Please post screenshots of
1. the Multilingual Status module
2. the Content Languages manager and check the URL Language Code (sef) for each content language. You may just be missing it for a language.

Updating Nightly builds may also be the problem as well as not creating any Home menu item for your nl-NL language.

**Comment by infograf768** [comment]
EDIT: I am pretty sure it is due to a missing URL Language Code.
This means we need to add an error in the Multilingual Status module as it does not check that aspect.

**Comment by brianteeman** [comment]
Isnt it a required field?

**Comment by ceford** [comment]
Item 1:
![image](https://user-images.githubusercontent.com/1560390/91663013-096d0380-eade-11ea-947d-bbe2e8934664.png)

**Comment by infograf768** [comment]
> Isnt it a required field?

It is. I guess the poster has done a mistake, or happened what is solved here: https://github.com/joomla/joomla-cms/pull/30496

Now, obviously if the site is not set correctly as posted above, all will be broken. ROTFLOL

**Comment by ceford** [comment]
Item 2:
![image](https://user-images.githubusercontent.com/1560390/91663104-ae87dc00-eade-11ea-9ebf-44586ad956b7.png)

**Comment by infograf768** [comment]
@ceford
This is not the Content Languages Manager. It is the Installed Languages Manager.
But anyway, your site is totally wrongly implemented for multilingual.

**Comment by ceford** [comment]
I installed nl-NL to see the Dutch translations of Help screens. I don't remember when I made nl-NL the default language. I had no need to do that - I selected it in the Admin login screen.

**Comment by infograf768** [comment]
@ceford 
You should NEVER set the languagefilter plugin on when the site is not prepared as multilingual.
backend help does not need the language filter to be set to Yes.
Closing this as a non issue.

**Comment by ceford** [comment]
Item 2: 
![image](https://user-images.githubusercontent.com/1560390/91663196-4f769700-eadf-11ea-837a-18bc2f023db9.png)

**Comment by ceford** [comment]
If the language set up is all wrong it follows installation of the multi-language data set and lots of patch testing. Installation of nl-NL was very recent.

**Comment by infograf768** [comment]
You have the url language code, but the rest is missing. 
If you want to test multilingual, make sure you installed the languages in a clean site and then use the Multilingual Sample Data module in the dashboard to create a fully simple multilingual site.

**Comment by infograf768** [comment]
<img width="695" alt="Screen Shot 2020-08-30 at 17 43 07" src="https://user-images.githubusercontent.com/869724/91663309-505ff680-eae8-11ea-94f5-b892d2d4503b.png">

**Comment by ceford** [comment]
That is what I did - but back at Beta1 or 2 stage. Time for a clean install! Sorry to waste your time.

That term 'Manager' is not present in the Admin interface other than in the Help Screens - confusing!

**Comment by infograf768** [comment]
No p. :)

**Comment by ceford** [comment]
Where does that Testing Sample Data come from?

**Comment by infograf768** [comment]
It is only present on dev. It will not be released with stable.
