### ISSUE TITLE
[4.0] Filter in categorylist broken 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#30515]
### Steps to reproduce the issue
Have a MenuItem category List, Choose Display Select "show" .

The css if the filter is broken

![screen shot 2020-08-29 at 19 10 17](https://issues.joomla.org/uploads/1/7dc3a6418c342eb2a5dd9f78cfef69dd.png)

**Comment by paternax** [comment]
I can confirm the issue with a current 4.0-dev branch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30515">issues.joomla.org/tracker/joomla-cms/30515</a>.</sub>

**Comment by Quy** [comment]
Duplicate #29504
