### ISSUE TITLE
On some sites the Components menu entry "com_joomlaupdate" is not translated?!

### ISSUE THREAD

**Issue by gituser5555** [joomla/joomla-cms#30526]
On some sites the Components menu entry "com_joomlaupdate" is not translated?!

Go to /administrator/index.php?option=com_installer&view=manage
![pic](https://user-images.githubusercontent.com/70518663/91716345-c5d2d200-eb8f-11ea-9819-a201e21620cb.png)

Go to /administrator/index.php?option=com_installer&view=update
![pic2](https://user-images.githubusercontent.com/70518663/91716347-c66b6880-eb8f-11ea-97c3-2b773fa3a959.png)

Joomla! Version: Joomla! 3.9.21 Stable [ Amani ] 25-August-2020 15:00 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
PHP Version: 7.4.9

Installed languages
Title | Native Title | Language Tag | Default | Version | Date | Author | Author Email | ID
-- | -- | -- | -- | -- | -- | -- | -- | --
  | English (United Kingdom) | English (United Kingdom) | en-GB |   | 3.9.21 | August 2020 | Joomla! Project | admin@joomla.org | 600

**Comment by zero-24** [comment]
Hi

please enable debug and language debug mode and check wether the com_joomlaupdate language file is loaded or that you have any kind of issues.

**Comment by gituser5555** [comment]
Thx for the hint

There are 3 not loaded language files but they belong to third party extensions and seem not relevant.

Under untranslated strings there are some entries. especially:
COM_JOOMLAUPDATE="joomlaupdate"

On a working site there is addionally loaded:
**Loaded** : JROOT/administrator/language/en-GB/en-GB.com_joomlaupdate.sys.ini

That is missing if the translation doesnt work.
But why could that be?

**Comment by zero-24** [comment]
hmm what happens when you disable the 3rd party extensions that have the language loading issues?

> But why could that be?

hmm would it be possible to share a backup in private (tobias.zulauf[at]community.joomla.org) so we could analyse the issue? It is hard to debug and fix an issue where it can not be reproduced on a clean install.

**Comment by ghost** [comment]
Can a maintainer please assign the label "Information Required"?

**Comment by Hackwar** [comment]
We didn't get back any information for 2 years. Closing this one.
