### ISSUE TITLE
[4.0] Module newsflash - not possible to add tags on the fly

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#30525]
### Steps to reproduce the issue
Make a module artilce_news, enter new tags in the tags input field.

### Expected result
Tags are stored

### Actual result
Tags are ignored

### Additional comments
Maybe related to this issue #27985

**Comment by SharkyKZ** [comment]
Expected behavior.

**Comment by SharkyKZ** [comment]
Actually the UI needs to be tweaked not to allow entering custom tags in the field at all.

**Comment by brianteeman** [comment]
It wouldnt make sense to be able to do that here

**Comment by brianteeman** [comment]
@chmst could you please clarify what it is you want to do here. I read it that you want to be create tags "on the fly" here just as you can for an article. If that's what you meant then it wouldn't make any sense to add a tag here.

**Comment by brianteeman** [comment]
reminder

**Comment by brianteeman** [comment]
please test #38087

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38087 . Thanks in advance.
