### ISSUE TITLE
Multi-Domain / Multi-Site

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#30530]
### Is your feature request related to a problem? Please describe.
Currently, there is no easy way to add 2 or more domains to one installed @Joomla CMS.

### Describe the solution you'd like
I propose to add a new setting to Joomla - to allow the CMS to work with two or more domains at the same time.

**The following functions would be very helpful:**

1. Ability to select a domain (or several domains) on which the `Article` will be published. With the option to select the main domain (for which there will be link `rel=canonical`)
2. Ability to select a domain (or multiple domains) on which the `Category` (and `Tags`) will be displayed. With the option to select the main domain (for which there will be link `rel=canonical`)
3. Ability to select a domain (or several domains) on which the `Module` will be published.
4. The ability to create a `Home` page for each domain related to CMS.
5. The ability to create any page in the site `Menu` (with the choice of one or more domains on which the menu item will be published)
6. Ability to select a default site `Template` for each domain (front-end)

**General:**

- One database for all domains
- One CMS setup for all domains
- One `Control Panel` for all domains
- A single database with users for all domains (users will not need to register again on another domain)

### Additional context
I saw this [announced](https://www.joomla.org/announcements/release-news/5819-the-day-after-joomla-4-0-planning-the-future.html) for Joomla 4.2 This is a highly anticipated feature. I will be able to create networks of sites on similar topics.

**Comment by bembelimen** [comment]
Hi @sanek4life 
thanks for your insight. Are you a developer?

**Comment by 4digitalworld** [comment]
> 
> 
> Hi @sanek4life
> thanks for your insight. Are you a developer?

I'm not a developer. I just shared my thoughts on what this function can be

**Comment by joomleb** [comment]
@sanek4life right now it is something you can do by using SEBLOD - [features](https://www.seblod.com/features) > [how to](https://www.seblod.com/resources/manuals/advanced/setting-up-multi-sites)

**Comment by brianteeman** [comment]
@bembelimen I've been playing with j2xml and the approach it takes might be useful - just swapping out the xml engine for the new api

**Comment by bembelimen** [comment]
@brianteeman could you elaborate a bit on this please? I thought j2xml is an import/export extension?

**Comment by ghost** [comment]
similaer: #27121

**Comment by Quy** [comment]
Duplicate
