### ISSUE TITLE
[4.0][com_fields] Selector markup

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#30532]
### Steps to reproduce the issue
Fields under Articles and Contacts have field selectors dropdown (Articles, Category) and (Contact, Mail, Category) respectively, but not under Users, thus, there is markup but no dropdown menu to reference.

Go to Users > Fields and Users > Field Groups
View page source.

For label, it has `context`, but is it meaningful/provides context?

### Actual result
```
<div class="js-stools-field-selector">
	<div class="sr-only">
		<label id="context-lbl" for="context">
	context</label>
	</div>
	</div>
</div>
```

**Comment by brianteeman** [comment]
it should not be there

**Comment by Quy** [comment]
No longer an issue.
