### ISSUE TITLE
[4.0] Frontend: Select Language disabled (Module, Article)

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#30533]
### Steps to reproduce the issue
- Clean install J4
- Shared Sessions "Yes"
- Frontend: open Module
- Select Language is disabled:
![Screen Shot 2020-09-01 at 08 16 16](https://user-images.githubusercontent.com/70466955/91804125-86f25a00-ec2b-11ea-84b3-e93f82df7a1d.png)

Same at Article.

### Expected result
Select Language enabled
### Actual result
Select Language disabled
### System information (as much as possible)
php: Linux lamp121.cloudaccess.net 2.6.32-673.8.1.lve1.4.3.1.el6.x86_64 #1 SMP Thu May 5 16:06:47 EDT 2016 x86_64
dbserver: mysql
dbversion: 5.7.29-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.3.19
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0
### Additional comments
Clean install J3 Select Language is enabled in Frontend.

**Comment by infograf768** [comment]
Is your J4 site set as multilingual?

**Comment by ghost** [comment]
Yes, done by "Multilingual Sample Data":
![Screen Shot 2020-09-01 at 08 43 49](https://user-images.githubusercontent.com/70466955/91811258-822fa500-ec2f-11ea-8937-0e5f887558ce.png)

**Comment by SharkyKZ** [comment]
This is intentional and same as in J3:

https://github.com/joomla/joomla-cms/blob/4e2a6e0190f865c7b40edc46de8b6c6d9bc28062/components/com_config/view/modules/tmpl/default.php#L33-L37

Although done in a totally wrong way.

**Comment by infograf768** [comment]
Here, in J3, as well as in J4, when the site is multilingual, the language cannot be changed in frontend, shared session or not. This is on purpose to avoid messing with the site.
J3 site
<img width="585" alt="Screen Shot 2020-09-01 at 08 48 24" src="https://user-images.githubusercontent.com/869724/91811616-126dea00-ec30-11ea-9bc0-f4655282e32e.png">

**Comment by infograf768** [comment]
oops, @SharkyKZ was faster

**Comment by infograf768** [comment]
> Although done in a totally wrong way.

Could you elaborate?

**Comment by ghost** [comment]
Thanks @infograf768 @SharkyKZ for Information.

**Comment by jiweigert** [comment]
Good time to do it in the right way. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30533">issues.joomla.org/tracker/joomla-cms/30533</a>.</sub>

**Comment by SharkyKZ** [comment]
@infograf768 First, forms shouldn't never be manipulated in the view. This should be done in the controller or the model. Otherwise changes are not reflected when validating. Secondly, setting `readonly` attribute even in the right place doesn't prevent field modification. Value can still be manipulated through DOM. In general form validation is broken all over 😕 .

**Comment by infograf768** [comment]
We should do something.
It is an important piece of information to know to which language the module was tagged when editing it. Or the article.

**Comment by ghost** [comment]
Reopen for "do it in the right way".

**Comment by infograf768** [comment]
@Formatio-hippocampi 
This issue should not be re-opened as its description is not related to the issue described by @SharkyKZ

**Comment by brianteeman** [comment]
> . In general form validation is broken all over

I've said that for two years but no one listens
