### ISSUE TITLE
[4.0] Frontend: "Edit module"-Icon on "Smart Search" in Position "Search" is not shown

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#30547]
### Steps to reproduce the issue
- Install J4
- append Smart Search-Module to Position "Search"
- "Edit module"-Icon is not shown on Frontend.

### Expected result
"Edit module"-Icon is shown on Frontend.

### Actual result
"Edit module"-Icon is not shown on Frontend.

### System information (as much as possible)
php: Linux lamp110.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 #1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
dbserver: mysql
dbversion: 5.7.30-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.3.21
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

### Additional comments
- Move "Search"-Module on Position "sidebar-right" the "Edit module"-Icon is shown
- Move another Module (ie Blog-Menu) on Position "Search" the "Edit module"-Icon is shown.

#### Update
Same for Module-Type "Breadcrumbs" in Position "Breadcrumbs".

**Comment by infograf768** [comment]
Confirmed

**Comment by brianteeman** [comment]
The problem is not with the module but with the module chrome.

Any module position with a chrome of none does not have the markup required to trigger the frontend editing script because the layout frontediting_modules.php is not triggered onmodules with a chrome of none

**Comment by brianteeman** [comment]
This has been resolved elsewhere and can be closed

![image](https://user-images.githubusercontent.com/1296369/115993334-35d41380-a5ca-11eb-8823-fdf3208b17c6.png)
