### ISSUE TITLE
[4.0] Fix field not inherited by sub-categories

### ISSUE THREAD

**Issue by david19161** [joomla/joomla-cms#30542]
### Steps to reproduce the issue
Create category Cat1
Create Sub-Category of Cat1, Cat2
Create Article TestArticle, place in category Cat2
Create Field TestField assign to Cat1
Open Article TestArticle

### Expected result
TestField should be available (inherited from Cat1)

### Actual result
TestField is not available

### System information (as much as possible)
joomla_4.0.0-beta4-dev-Development-Full-Package - nightly : 2020-08-31

### Additional comments
Result after fix below:
TestField is available, fields are inherited by sub-categories correctly

File : administrator\components\com_fields\src\Model\FieldsModel.php
Line : approx 242 in function getListQuery()

change
$db->quoteName('fc.category_id') . ' IN 
(' . implode(',', $query->bindArray(array_values($categories), ParameterType::INTEGER)) . ')' .

To
$db->quoteName('fc.category_id') . ' IN (' . implode(',', $query->bindArray(array_values($categories), ParameterType::INTEGER)) . ')' .

I would have opened a pull request for this but found github too complicated.

**Comment by ghost** [comment]
Issue can be closed as there is #30557
