### ISSUE TITLE
[4.0] Templates Customise Wrong Help Screen

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30544]
### Steps to reproduce the issue

Go to System -> Site Template -> Select Cassiopeia Details and Files
Click the Help item in the Toolbar - The Help screen is for this page.
Select a file to edit
The Toolbar changes - Click the Help item - Unchanged

### Expected result

There is a Help screen for the Edit Source page but it is not being used:
https://docs.joomla.org/Help4.x:Extensions_Template_Manager_Templates_Edit_Source

### Actual result

The Help page used has the wrong Toolbar description
https://docs.joomla.org/Help4.x:Extensions_Template_Manager_Templates_Edit

### Additional comments

The string keys to look for are:
JHELP_EXTENSIONS_TEMPLATE_MANAGER_TEMPLATES_EDIT
JHELP_EXTENSIONS_TEMPLATE_MANAGER_TEMPLATES_EDIT_SOURCE
This problem seems to be inherited from Joomla 3

**Comment by brianteeman** [comment]
Personally I would just have one help page

**Comment by ceford** [comment]
I have revised the used Help screen so that serves a dual purpose.
