### ISSUE TITLE
Fieldtype MEDIA should not only allow Images, but also PDF, ZIP and all other formats that com_media allows

### ISSUE THREAD

**Issue by Robdebert** [joomla/joomla-cms#30548]
### Steps to reproduce the issue
create a new component or module and use a default joomla formfield with the type "media". See he media form field type provides modal access to the media manager for the choice of an image. 

Make sure, that uploading PDF or XLS or other files then images are allowed in com_media: /administrator/index.php?option=com_media&folder= (click on options at the top right).

### Expected result
In the overlay, a user can select and upload the same file(types) as he can in /administrator/index.php?option=com_media (example: PDFs, XLS, ZIP):
![image](https://user-images.githubusercontent.com/1737455/91974745-84bcf800-ed1e-11ea-9859-bd602bef8a94.png)

### Actual result
Only image-types are allowed and seen in the overlay:
![image](https://user-images.githubusercontent.com/1737455/91974726-77a00900-ed1e-11ea-9c96-55ed90b64d77.png)

### System information (as much as possible)
Joomla 3.9.19

### Additional comments
See the doc: https://docs.joomla.org/Media_form_field_type. In the upper part of the text, it says: "he media form field type provides modal access to the media manager for the choice of an image. ". But the media-management also allows different file-types to upload. That depends on the configuration-settings for allowed file-extensions or mime-types.

The media-fieldtype should also make use of these settings, so Users can select PDF-Files for example.

See also these search-results:

- https://forum.joomla.org/viewtopic.php?t=700953
- https://github.com/joomla/joomla-cms/issues/10871 -> The problem is, that the answer from Brian is not sufficient, because com_media allows MEDIA and not only Images. So this formfield-type should use the same. The dropdown-select-field is not a good solution, because users cannot upload files directly in the modal-window, as they can in the media-field.
**That's why i think, updating the media-fieldtype to use the com_media Parameters would be a very good solution.**

(my internal Link: https://trello.com/c/yRl1I97D/com_media_upload_error)

**Comment by Robdebert** [comment]
Addon: I was even able to upload a PDF in the modal overlay of the media-field, but it still shows not after uploading:

![image](https://user-images.githubusercontent.com/1737455/91977887-96ed6500-ed23-11ea-8bb2-a4bb0d14e23a.png)

Btw: The one file you can see in this screenshot is a jpg.

**Comment by Quy** [comment]
Duplicate #19954

**Comment by Robdebert** [comment]
@Quy  Why was this ticket closed? It is NOT Solved. See https://github.com/joomla/joomla-cms/issues/19954#issuecomment-478921137 -> There was a discussion, but that was also closed too early.

It seems issue-reports are getting closed far too early, without asking the author of the ticket, if the solution is ok for them.
Because still, this problem is not solved in any joomla-version. And no PR was ever accepted.

**Comment by ghost** [comment]
similaer: #26408

**Comment by Robdebert** [comment]
> similaer: #26408
but not releveant :-) That ticket is about something else, than i described.
