### ISSUE TITLE
Show PHP version alert to Super Users only

### ISSUE THREAD

**Issue by rubenreyes2000** [joomla/joomla-cms#30541]
### Is your feature request related to a problem? Please describe.
Currently the PHP version alert generated by the `phpversioncheck` plugin is shown to all users logged in to the backend (administrator).

### Describe the solution you'd like
Display the alerts generated by the `phpversioncheck` plugin only to Super Users, the same way that the plugins `extensionupdate` and `joomlaupdate` work.

Specifically change `plugins/quickicon/phpversioncheck/phpversioncheck.php` line 225 to

```
if (!JFactory::getUser()->authorise('core.manage', 'com_installer'))
```

or

```
if (!JFactory::getUser()->authorise('core.admin'))
```

**Comment by brianteeman** [comment]
This way they will hopefully nag their sys admin to update php

**Comment by ReLater** [comment]
Solution:
- Create an Access Level for Super Users only if it doesn't exist already.
- Set "Access" to this group in plugin phpversioncheck.

**Comment by rubenreyes2000** [comment]
@brianteeman that makes sense but, in that case `extensionupdate` and `joomlaupdate` should behave the same way. I understand where you are coming from with this approach, and I know that many admins need that kind of push. However, I don't think unnecessarily annoying or worrying non-technical users makes for a good user-experience. Specially when these alerts show up many months before there is any danger or issue.

@ReLater that's a good workaround, thank you. But it's a lot of work when managing many sites for clients. It would be better if Joomla doesn't show alerts that are really not appropriate for all users to see.

**Comment by ReLater** [comment]
> that's a good workaround, thank you. But it's a lot of work when managing many sites for clients. It would be better if Joomla doesn't show alerts that are really not appropriate for all users to see.

When you install a fresh Joomla the Super User access level is already there. So I see just some clicks as "work" (even if you have to create that view level on your own). I see more awkward work and confusion for others if Joomla would establish your solution because there are also users that want it like it is. Your solution is a one-way street.

**Comment by rubenreyes2000** [comment]
I am sure this is **the** change that will cause confusion, and that the inconsistent behavior is then justified.
While I am disappointed such a minute change for improving UX would not be consider, I thank you for taking the time to respond. Most OSS projects don't even do that. I will close this now since no action will be taken.

**Comment by ReLater** [comment]
> since no action will be taken.

I don't have to decide that. I'm just arguing from my point of view. Provide a pr and you will see if production leads are willing to merge it!
