### ISSUE TITLE
[4.0] Combo box lists empty

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#30540]
### Steps to reproduce the issue
Create a new tag and try to select a "parent"

![tags](https://user-images.githubusercontent.com/1838041/91856829-be82f580-ec6f-11ea-9229-4a17f1abbce7.gif)

### Expected result
The "parent" list to show the existing tags.

### Actual result
The "parent" list is empty

### System information (as much as possible)
4.0.0-beta4-dev

## Addition
Possibly this is a general issue with the comboboxes. I am having the same issue, when i try to select tags inside articles and in the comboboxes inside various modules.
The options show only after typing (searching) them.

**Comment by Quy** [comment]
Expected behavior. See https://github.com/joomla/joomla-cms/issues/26679#issuecomment-544162823
