### ISSUE TITLE
[4.0] in 2 column layout of edit article or edit menu items the fields are cut between at 976px- 

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#30545]
In the two column layout of the first tab in editing articles, categories and menu items the fields in the right column are cut or stick out of their section in a window range between 976 px - 1300 px

### Steps to reproduce the issue
Content -> Articles -> open an article -> Tab Content
Vary the width of the browser window between 976 Pixel and 1400 Pixel

### Actual result

![screen shot 2020-09-02 at 09 51 03](https://issues.joomla.org/uploads/1/45c252a14dff4b343ee56fe5a7f1ebe1.jpg)

**Comment by ghost** [comment]
#### Confirmed starting on 992px:

![Screen Shot 2020-09-03 at 09 27 10](https://user-images.githubusercontent.com/70466955/92084958-6f040d00-edc8-11ea-96bb-ff26326d5e1d.png)

#### "Tags"-Field wider than other Fields below 1467px:

![Screen Shot 2020-09-03 at 09 38 15](https://user-images.githubusercontent.com/70466955/92085698-7972d680-edc9-11ea-8ee1-04327d8f541e.png)


### System information
version: Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

**Comment by Quy** [comment]
Duplicate #27907
