### ISSUE TITLE
[4.0] in mobile view icon for menu and additional accessibility features overlap

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#30551]
In mobile view the icons for the main menu and the icon for the additional accessibility features are overlaping
### Steps to reproduce the issue
- Enable Plugin: System - Additional Accessibility Features 
- mobile view
- scroll to bottom

### Actual result
![screen shot 2020-09-02 at 17 14 13](https://issues.joomla.org/uploads/1/24b3dda968643c5a3a0f09acdb79f36f.jpg)

**Comment by brianteeman** [comment]
Thanks for finding and reporting that - please test #30552
