### ISSUE TITLE
[4.0] Repeatable Custom field

### ISSUE THREAD

**Issue by leoalv** [joomla/joomla-cms#30556]
The repeatable custom field is the most loved and used in Joomla 3.X, in the alpha versions of Joomla 4 it seemed that they were going to keep it, but in the beta version it is no longer there and it was replaced by subfield.
Do you plan to reintegrate the repeatble custom field? Is there a way to migrate these fields to the new subfield?

Currently doing a migration this gives an error.

### Steps to reproduce the issue

- Create a repeatable custom field in joomla 3.9.21
- Create a article using this custom field in Joomla 3.9.21
- Upgrade to Joomla 3.10. alpha
- Upgrade to Joomla 4.0.beta3

### Expected result

The repeating field should work.

### Actual result

It is not possible to create articles, and it shows errors in the section of custom fields

### System information (as much as possible)

`Warning: Declaration of PlgFieldsRepeatable::onCustomFieldsPrepareDom($field, DOMElement $parent, JForm $form) should be compatible with Joomla\Component\Fields\Administrator\Plugin\FieldsPlugin::onCustomFieldsPrepareDom($field, DOMElement $parent, Joomla\CMS\Form\Form $form)`

### Additional comments

When the repeatable field was checked in Joomla 3.10 alpha, it was working fine. The problem is in Joomla 4.0 beta3. so it is necessary to know what will happen with this. Thank you

**Comment by zero-24** [comment]
hmm on upgrade that field should be uninstalled and convert to the subform field: https://github.com/joomla/joomla-cms/pull/28319

So it seems that migration did not happen for some reason to be investigated.

**Comment by micker** [comment]
Hello i didnt find any Doc about migration to subfield some link ?

**Comment by zero-24** [comment]
Well the intention is that this migration is done on upgrade as mention in the PR linked above. I did not had time to check what goes wrong on upgrade that this does not happen.

**Comment by zero-24** [comment]
I have just confirmed that this migration script seems not work correctly after the upgrade the field is still `repeatable` and not converted to ``subform` it seems only one new editor field is created on upgrade. @Hackwar can you take a look here?

![image](https://user-images.githubusercontent.com/2596554/92307807-43844c80-ef99-11ea-8b4a-91b793a72a25.png)

**Comment by Llewellynvdm** [comment]
@Hackwar @wilsonge to me it looks like a migration fail higher in the execution, that affects/prevents the repeatable fields update to complete. I will run a few more passes on this to check until where we have the execution stack of the migration working as expected. Here is the path I have been going about five times now already...

# Running a test going from v3.9.22 -> v4.0.0-beta5-Beta
![image](https://user-images.githubusercontent.com/5607939/97377813-8abbf900-18c9-11eb-8d9b-7e8467d90a95.png)
![image](https://user-images.githubusercontent.com/5607939/97377835-97d8e800-18c9-11eb-956b-821a013a270a.png)
![image](https://user-images.githubusercontent.com/5607939/97377870-a6bf9a80-18c9-11eb-995d-c15bb739ac45.png)
### Start Migration to Joomla_3.10.0-alpha3-Alpha
![image](https://user-images.githubusercontent.com/5607939/97377940-d9699300-18c9-11eb-95dc-780a9fd118c2.png)
![image](https://user-images.githubusercontent.com/5607939/97377978-ea1a0900-18c9-11eb-956e-8c7e1959fe32.png)
![image](https://user-images.githubusercontent.com/5607939/97377989-ef775380-18c9-11eb-93e3-5d6cf5cd28a6.png)
![image](https://user-images.githubusercontent.com/5607939/97378025-03bb5080-18ca-11eb-9d2f-1503f4825104.png)
![image](https://user-images.githubusercontent.com/5607939/97378035-0ae25e80-18ca-11eb-8a09-289fae4c5b1a.png)
### Start Migration to Joomla_4.0.0-beta5-Beta
![image](https://user-images.githubusercontent.com/5607939/97378130-47ae5580-18ca-11eb-80d3-bca3e0a1a209.png)
![image](https://user-images.githubusercontent.com/5607939/97378146-54cb4480-18ca-11eb-83c8-d2389bb40f27.png)
![image](https://user-images.githubusercontent.com/5607939/97378183-72001300-18ca-11eb-9528-24b01f448e5f.png)
![image](https://user-images.githubusercontent.com/5607939/97378263-9cea6700-18ca-11eb-97d0-755e6e66178c.png)
![image](https://user-images.githubusercontent.com/5607939/97378297-b7244500-18ca-11eb-9973-5e009901a8cf.png)
![image](https://user-images.githubusercontent.com/5607939/97378315-c5726100-18ca-11eb-8aa6-6513c97dffd3.png)
![image](https://user-images.githubusercontent.com/5607939/97378445-02d6ee80-18cb-11eb-96e8-a5b9448f7cd2.png)
### Repeatable Field was not updated
![image](https://user-images.githubusercontent.com/5607939/97378536-3580e700-18cb-11eb-97b5-3ec1f063a763.png)
### Trying to open the article with the Repeatable Field Fails, and I can also not create a new article 
![image](https://user-images.githubusercontent.com/5607939/97378687-9c9e9b80-18cb-11eb-9dea-f2ceacec3760.png)
![image](https://user-images.githubusercontent.com/5607939/97378723-b213c580-18cb-11eb-9c6a-dbd4191a2789.png)
![image](https://user-images.githubusercontent.com/5607939/97378726-b50eb600-18cb-11eb-841b-aa465664e778.png)
![image](https://user-images.githubusercontent.com/5607939/97378740-c22ba500-18cb-11eb-9017-3a055422d8ac.png)

**Comment by wilsonge** [comment]
Fixed the fatal on upgrade. Now the field migrates to a subform field - and other articles can correctly create data. However the existing 3.x data doesn't get upgraded - which requires fixing still (hence this remains open)

**Comment by Llewellynvdm** [comment]
Thanks for this update, was waiting for this fix on the upgrade path, will now take a closer look at this.

**Comment by joomdonation** [comment]
I created PR https://github.com/joomla/joomla-cms/pull/32611 to migrate data. Hopefully we can close this Release Blocker issue :).

**Comment by chmst** [comment]
Closing as we have a PR.
