### ISSUE TITLE
Make [Web Site Privacy] and [Terms & Conditions] on the same line with one confirmation tick

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#30562]
### Is your feature request related to a problem? Please describe.
If plugins `System - Privacy Consent` and `User - Terms and Conditions` are enabled on the site, then during the registration of a new user, two new fields appear, where the user must `✓` check the consent box.

![изображение](https://user-images.githubusercontent.com/3662519/92126765-3d5f6600-ee09-11ea-9b0f-759f9d79cc76.png)
![изображение](https://user-images.githubusercontent.com/3662519/92127234-c5de0680-ee09-11ea-8284-98c6c5027bb0.png)

### Describe the solution you'd like
Make `Web Site Privacy` and `Terms & Conditions` on the same line with one `✓` confirmation tick.

Something similar as in this screenshot:
![изображение](https://user-images.githubusercontent.com/3662519/92127372-ea39e300-ee09-11ea-9679-1f75e041f106.png)

### Additional context
It will be more convenient and user-friendly. I've seen this on so many sites. I made a screenshot on the site [Billboard.com](https://www.billboard.com/)

**Comment by jiweigert** [comment]
Hi,

I did agree, that it would be more convenient, but at least for germany, you have to be able to have a distinct choice to agree to Web Site Privacy and/ or Terms & Condititions and further to allow/ deny the usage of cookies.

Those websites, which uses a one-click approach usually want to trick the user into a "all or nothing" approach, for whatever reasons (advertising/ tracking/ etc).

I do support a optional solution, where the admin can decide, if he want to have a combined "one-click-solution" like you promote or a "per option choice" like it is currently implemented.

Germany/ EU is not the world and in other parts of the world, there are not as strict regulations, so a choice between both variants would be great!

Kind regards,

Jörn-Ingo Weigert<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30562">issues.joomla.org/tracker/joomla-cms/30562</a>.</sub>

**Comment by N6REJ** [comment]
This can be controlled with a module override.
From an ecommerce site perspective you would never want the two combined as your TOC will be very different then your privacy policy.
same thing with a medical site or government site here in the states.
closing as this isn't an issue.

**Comment by brianteeman** [comment]
> This can be controlled with a module override.

it can't

Still agree its not a good idea to do

**Comment by 4digitalworld** [comment]
> 
> 
> This can be controlled with a module override.
> From an ecommerce site perspective you would never want the two combined as your TOC will be very different then your privacy policy.
> same thing with a medical site or government site here in the states.
> closing as this isn't an issue.

you are talking about the United States, and I just gave you an example of the largest music site from the United States, where it is done as in the screenshot - [https://www.billboard.com/](https://www.billboard.com/)

I mean, you mark with one tick, but in the text there will be links to 2 documents. user can click on both documents and read (these are 2 different articles). I am not saying that it will be one document (one link).

I know the documents may differ, but I did not say that one checkbox is one document. There will be text and in the text there will be links to 2 different documents. Did you understand me correctly? I have seen this on very large popular sites in the US. I think that sites in the US would not use this if it was illegal.

**Comment by 4digitalworld** [comment]
Well, let's see how the largest online store in the US @amzn uses the registration page on the site!

They don't even ask the user to tick the consent box - they just wrote a text with information that the user agrees with these documents. It looks a lot more user friendly.

![изображение](https://user-images.githubusercontent.com/3662519/92261083-8be03380-eee1-11ea-9ff8-fc55ddafd686.png)

` By creating an account, you agree to Amazon's Conditions of Use and Privacy Notice. `

If this approach were illegal, then Amazon would have received lawsuits long ago.
