### ISSUE TITLE
[4.0] Media  Manager - Maximum file size set to "0" is not unlimited; it is zero

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#30567]
If you set the maximum file size in the Media Manager Options to 0 it is not treated like "no limit", it is treated like zero.
### Steps to reproduce the issue
- Media Manager
- Options: set Maximum Size (in MB) to 0
![screen shot 2020-09-04 at 08 30 25](https://issues.joomla.org/uploads/1/7683102aff3946acb7dc12e686c1f109.jpg)
- Upload a small image
- You get the error: you are not You are not authorized

**Comment by ghost** [comment]
Issue confirmed.

### System Information
php: Linux lamp131.cloudaccess.net 3.10.0-714.10.2.lve1.5.17.el6h.x86_64 #1 SMP Mon Apr 30 13:48:47 EDT 2018 x86_64
dbserver: mysql
dbversion: 5.7.24-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: false
phpversion: 7.3.21
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

**Comment by Quy** [comment]
Please test PR #30572
