### ISSUE TITLE
[4.0] Media Manager - Message for exceed file size is misleading

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#30566]
If you exceed the maximum file size, which is set in the options of media manager you get the message: You are not authorized
This is misleading, because it is not a problem of permission. Better would be a message like: File size exceeds maximum allowed size        

### Steps to reproduce the issue
Media Manager - Options (default max size is 10MB)
Upload an image with more than 10 MB![screen shot 2020-09-04 at 08 15 36](https://issues.joomla.org/uploads/1/1074c873277c4fd700b2a54b02093bcb.jpg)

**Comment by ghost** [comment]
Issue confirmed.

### System Information
php: Linux lamp131.cloudaccess.net 3.10.0-714.10.2.lve1.5.17.el6h.x86_64 #1 SMP Mon Apr 30 13:48:47 EDT 2018 x86_64
dbserver: mysql
dbversion: 5.7.24-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: false
phpversion: 7.3.21
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

**Comment by Quy** [comment]
Duplicate #25379
