### ISSUE TITLE
[List All Categories]: The page does not load when multilanguage is enabled.

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#30561]
### Steps to reproduce the issue

1. enable `Multilingual`
2. create menu item `List All Categories`
3. select the language for the menu item - `All`
4. try to go on the site to this menu item
5. the menu item does not load, error `ERR_TOO_MANY_REDIRECTS` appears in the browser
![изображение](https://user-images.githubusercontent.com/3662519/92124761-dccf2980-ee06-11ea-9473-7d90b16ba193.png)

### Expected result
we must go to the site and see a page with all the `categories` of the site

### Actual result
the page cannot load and the browser shows error `ERR_TOO_MANY_REDIRECTS` 

### System information (as much as possible)
Joomla 3.9.21, 5.5.65-MariaDB, PHP 7.2.32 

### Additional comments
when there was no multilanguage on my site, then this menu item worked correctly and when entering this page I saw all the categories of the site.

**Comment by infograf768** [comment]
I can't reproduce the error.
BTW, only the categories tagged to the language used in frontend and to language ALL would show.

**Comment by 4digitalworld** [comment]
> 
> 
> I can't reproduce the error.
> BTW, only the categories tagged to the language used in frontend and to language ALL would show.

On my site there are `categories` for which I have set the language `en-GB`, `ru-RU` and `All`. All pages and categories are displayed correctly on the site. This is the only page on my site that is not working - the page cannot load, I do not know why this is happening.

I see this error in the browser after I could not load this page:
![изображение](https://user-images.githubusercontent.com/3662519/92129480-3f76f400-ee0c-11ea-813d-1041eb02d5ef.png)

**Comment by ghost** [comment]
Can't confirm Issue.

**Comment by brianteeman** [comment]
I guess this unconfirmed issue can be closed as there has been no update for 24 days. It can always be reopened if updated with further information.

**Comment by brianteeman** [comment]
please close
