### ISSUE TITLE
joomla.form.field.subform.repeatable-table subform layout is broken

### ISSUE THREAD

**Issue by webchun** [joomla/joomla-cms#30579]
### Steps to reproduce the issue
I tried to create a subform for module using joomla.form.field.subform.repeatable-table subform layout and found that the UI is broken![screen shot 2020-09-06 at 07 46 18](https://issues.joomla.org/uploads/1/2c0b77605710b499a39682f620c2d29f.jpg)

### System information (as much as possible)
Joomla 4 Beta 3

**Comment by Quy** [comment]
Duplicate #29241
