### ISSUE TITLE
[4.0] mod_articles_news: "Linked Titles: Use Global" append "Yes" or "No"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#30584]
Problem | Solution
---- | ----
mod_articles_news: "Linked Titles: Use Global" the global setting isn't shown: | Global setting is shown like in Articles:
![Screen Shot 2020-09-07 at 10 20 34](https://user-images.githubusercontent.com/70466955/92364763-d5a06800-f0f3-11ea-8a87-8045a5bc4ad6.png) | ![Screen Shot 2020-09-07 at 10 21 49](https://user-images.githubusercontent.com/70466955/92365007-01235280-f0f4-11ea-9ca0-fbb44ee4238c.png)

**Comment by ghost** [comment]
### Additional context
Same in J3:

![Screen Shot 2020-09-08 at 07 05 36](https://user-images.githubusercontent.com/70466955/92435169-f1fade00-f1a1-11ea-8e96-f00eef5ce5c1.png)

**Comment by brianteeman** [comment]
Use Global is not available in any module
