### ISSUE TITLE
COM_LANGUAGES_ERROR_SEF

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#30586]
### Steps to reproduce the issue
The new language string has the value:
COM_LANGUAGES_ERROR_SEF = "<br />The \"URL Language Code\" should have only alphanumeric characters and dashes (-).<br />To use UTF-8 characters, \"**Unicode Alias**\" should be set to \"Yes\" in Global Configuration."

The label in the Global Configuration is:

COM_CONFIG_FIELD_UNICODESLUGS_LABEL = "Unicode Alias**es**"

### Expected result

The same name.

**Comment by infograf768** [comment]
oops

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/30589
closing as we have a PR
