### ISSUE TITLE
[4.0] Invalid Help screen key in Edit Category

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30587]
### Steps to reproduce the issue

In a mult-lingual site with sample data:
Go to Content -> Categories and select Uncategorised
In the Category edit form set Language to All.
Select the Associations button in the Toolbar - There is a Notice
Select the Help button in the Toolbar

### Expected result

A Help page popup

### Actual result

A 404 popup

### Additional comments

The Help key is shown in the popup url bar: JHELP_COMPONENTS__CATEGORY_EDIT
I think it should be JHELP_COMPONENTS_CONTENT_CATEGORY_EDIT

**Comment by ghost** [comment]
confirmed.

**Comment by brianteeman** [comment]
In that very specific circumstance I can confirm the problem
No idea how to fix it myself but its probably 
https://github.com/joomla/joomla-cms/blob/82a852196a26ede4eab178622b691b12987013f2/administrator/components/com_categories/src/View/Category/HtmlView.php#L261-L271

**Comment by ceford** [comment]
I think the situation is worse than I thought. After selecting the Associations button in the Toolbar with Languages set to All (I keep forgetting to do that) the page comes back with this in the url bar:
http://localhost/j4b4d/administrator/index.php?option=com_categories&view=category&layout=edit&id=2com_content
so it has lost the extension= before com_content. The other buttons should not work properly either, although they appear to.

**Comment by ceford** [comment]
I have resubmitted this as #30603
