### ISSUE TITLE
[4.0] Wrong link for Help in User Actions Log Options

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30591]
### Steps to reproduce the issue

Go to Global Configuration -> User Actions Log
Select the Help button

### Expected result

A Help screen for the Options page

### Actual result

The Help screen for the User Actions Log page.

### Additional comments

The ini file says:
JHELP_COMPONENTS_COM_ACTIONLOGS_OPTIONS="Components_Actionlogs"
It should be
JHELP_COMPONENTS_COM_ACTIONLOGS_OPTIONS="Components_User_Actionlogs_Options"

**Comment by brianteeman** [comment]
~In j3 it is Components_Actionlogs~
Sorry missed it was for the options - good spot

**Comment by alikon** [comment]
closing as we have a pr  #30594
