### ISSUE TITLE
[4.0] No Help button in Toolbar for New Module

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#30590]
### Steps to reproduce the issue

Go to Site or Administrator Modules and select the New button in the Toolbar.
The screen displays Select a Module Type and a list of modules.

### Expected result

A Toolbar with a Help button

### Actual result

No Help button

### Additional comments

There is a Help screen inherited from Joomla 3 that appears to be designed for all modules:
https://docs.joomla.org/Help4.x:Extensions_Module_Manager_Edit
In Joomla 4 each module type has its own Help screen. 

Is the missing Help button an oversight? Could it be used here - needing a revision to the quoted Help screen?

**Comment by brianteeman** [comment]
I dont see a need for a help button on that page and there isnt one in j3 either

**Comment by ceford** [comment]
OK - Closing.
