### ISSUE TITLE
[4.0] css minify missing classes

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30599]
any class that is in the format
`[id="filter[search]-desc"]`

ie one that begins with the [ character is missing from the minified template css

Its easy to confirm just by searching for the class above in both the casseiopeia template.css and template.min.css

This is a release blocker

**Comment by brianteeman** [comment]
The problem is with the minifier (uglifycss) as I tested with another minifier (https://www.minifier.org/) and it works correctly

**Comment by SharkyKZ** [comment]
I can't confirm this. This is present in `template.min.css`, both in nightly and git clone:

    [id="filter[search]-desc"]{bottom:100%}

**Comment by brianteeman** [comment]
not on my computer

**Comment by Quy** [comment]
I can't reproduce it either. It is there in the download package you reported in the other PR. 
https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/30588/downloads/35307/

**Comment by infograf768** [comment]
No problem here either. See https://github.com/joomla/joomla-cms/pull/30588#issuecomment-689317663

**Comment by brianteeman** [comment]
maybe its a windows issue?

**Comment by Quy** [comment]
I’m using Windows.

**Comment by brianteeman** [comment]
I can no longer replicate this. weird.
