### ISSUE TITLE
Blocking user for a certain time

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#30602]
### Is your feature request related to a problem? Please describe.
My site was created 12 years ago and 12K users have registered on it during this time. Unlike the sites that people made on other CMS, on my site I could not block a user only for a certain time (`week`/`month`/`year`), I could only block a user forever and without specifying a reason for blocking.

I recently found out that one user of my site got very upset because I blocked him 10 years ago on my site. I don't even remember the reason why I blocked it. After that, I decided to unblock all users who have been blocked in the last 12 years on my site. I have unblocked almost 500 users on the site. After 10-12 years, I don't even remember the reason why I blocked them on the site, but I remember exactly that 99% of the users I blocked, I did not want to block for more than a `week`/`month`, but I did not have such an opportunity.

### Describe the solution you'd like
I propose adding to @Joomla the ability to block a user for a specific time (`week`/`month`/`year`/`forever`) and the ability to specify a `reason for blocking` so that the `user`, when trying to enter the site, sees the reason for blocking.

### Additional context
If there is user registration in Joomla, there are fields for users, then it should be possible to block the user, but not forever, but only for a certain time! Not every user should be blocked forever, this is not correct. I saw in other CMS the ability to block a user for a `certain time`, but for some reason this is not in Joomla.

It might look something like this:
![изображение](https://user-images.githubusercontent.com/3662519/92583788-8432dd00-f29b-11ea-8dbd-34b19d6b2b60.png)

The code for this has already been created, you can see here [https://github.com/joomla/joomla-cms/pull/9945](https://github.com/joomla/joomla-cms/pull/9945)

**Comment by SharkyKZ** [comment]
Given the lack of social features in Joomla, I'd leave this to 3rd party extensions.

**Comment by brianteeman** [comment]
> the ability to specify a reason for blocking 

There is now the user notes which is perfect for that

**Comment by 4digitalworld** [comment]
> 
> 
> > the ability to specify a reason for blocking
> 
> There is now the user notes which is perfect for that

yes, it would be possible to show the blocked user the message from this note (I also thought about this idea)


> 
> 
> Given the lack of social features in Joomla, I'd leave this to 3rd party extensions.

the same can be said about user registration on the site (front). Why do I need to register on the site if it can be given to third-party extensions?

but the problem is that I have not seen any third-party extensions that would allow you to block a user for a certain time. I think that for third-party extensions to have such an opportunity, it must be in the CMS and the third-party extensions will simply synchronize this function with the CMS.

@Joomla has a user registration system, but there is no function of temporary blocking of users. This is the most incomprehensible thing about this CMS.

**Comment by 4digitalworld** [comment]
@brianteeman This can be done in Joomla in the following way:

1. If the user does not have an eternal ban (but only temporary), then the user can still `Login` the site, but at the top of the site he will see something like this message: "You are blocked until September 21, 2020. Reason (this is a field from the `note`): Obscene messages".
2. The user is temporarily moved to the `Guest` or `Public` group until September 21, 2020, thus the user is limited to all functions available to registered users.

**Comment by brianteeman** [comment]
I am sure we have had this exact discussion before. I won't participate it in again. Joomla is designed to be extended. That seems to satisfy everyone but you who wants everything specific to your website in the core. That's never going to happen.

Moderators this should be closed and locked.

**Comment by jiweigert** [comment]
At sanek4life,

you could write a cron-script, which you let run periodically every 12/24hrs, which check on the user note a special "marker"
(like #blocked24# (one day), compare it to the time when blocked and unblock it by SQl-command/ joomla clie when the 24hrs are over..

just an idea. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30602">issues.joomla.org/tracker/joomla-cms/30602</a>.</sub>

**Comment by rdeutz** [comment]
This is nothing we need in core, you can easily do with it extensions.
