### ISSUE TITLE
Missing format specifiers in installation language files

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#30604]
### What needs to be fixed

There are some strings with missing or invalid variable format specifiers. Some examples:

https://github.com/joomla/joomla-cms/blob/a14330dc9e20ba449d9ae91fe403d232e32fbdcc/installation/language/bn-BD/bn-BD.ini#L192

https://github.com/joomla/joomla-cms/blob/a14330dc9e20ba449d9ae91fe403d232e32fbdcc/installation/language/hi-IN/hi-IN.ini#L183

https://github.com/joomla/joomla-cms/blob/a14330dc9e20ba449d9ae91fe403d232e32fbdcc/installation/language/vi-VN/vi-VN.ini#L159

This doesn't cause an issue but space should probably be after HTTP:

https://github.com/joomla/joomla-cms/blob/a14330dc9e20ba449d9ae91fe403d232e32fbdcc/installation/language/kk-KZ/kk-KZ.ini#L340

### Why this should be fixed

Passing these to `sprintf()` results in invalid strings being outputted and causes errors on PHP 8.

### How would you fix it

Add missing format specifiers.

### Side Effects expected

No.

**Comment by Bakual** [comment]
That should be told the respective translation teams as they need to take care of it in their source files.
@infograf768 Do you want to take care of this?

**Comment by infograf768** [comment]
will look what we can do

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/30609
closing as we have a patch
