### ISSUE TITLE
[j4] repetable / subfield migration and ux problem

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#30614]
hello i start to migrate light dev for j4 where used repetable field
i know that will be abondonned but i didn't find in document how to do a migration
https://docs.joomla.org/Custom_fields_type:_Subfields speak only about output and not xml file ... any ressources ?
and other return .. the columns mode for options is completly broken when we use this type of field
![image](https://user-images.githubusercontent.com/2539440/92919609-13252e00-f431-11ea-8697-bd0f8251b303.png)

**Comment by Quy** [comment]
Duplicate #29241

**Comment by micker** [comment]
hello @Quy  yes i am agree for ux but not for repatable migration field .. state isn't clear ... that already exist, migration system is ok for subfoem ? where i can found xml reference for subform ?
thanks for any help

**Comment by Fedik** [comment]
https://docs.joomla.org/Subform_form_field_type

**Comment by micker** [comment]
Cool thanks i will test
