### ISSUE TITLE
[j4]Hide and show option in menu link

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#30610]
the option to display article title in the menu link  is realy strange
![image](https://user-images.githubusercontent.com/2539440/92692232-25756e00-f344-11ea-9f2d-b1d8afa6550d.png)
we can't see text maybe need a radio button instead of select list ?

**Comment by ghost** [comment]
Can't confirm:

![Screen Shot 2020-09-10 at 09 13 23](https://user-images.githubusercontent.com/70466955/92693438-efd18480-f345-11ea-8085-fdb999894b7b.png)

#### System Information

php: Linux lamp131.cloudaccess.net 3.10.0-714.10.2.lve1.5.17.el6h.x86_64 #1 SMP Mon Apr 30 13:48:47 EDT 2018 x86_64
dbserver: mysql
dbversion: 5.7.24-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: false
phpversion: 7.3.21
server: Apache
sapi_name: cgi-fcgi
version: Nightly Build @ Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

**Comment by micker** [comment]
can you set hide not defaut for me its red

**Comment by ghost** [comment]
Hide | Show
-- | --
![Screen Shot 2020-09-10 at 09 40 56](https://user-images.githubusercontent.com/70466955/92696164-c9154d00-f349-11ea-842d-20d9baa88a29.png) | ![Screen Shot 2020-09-10 at 09 42 13](https://user-images.githubusercontent.com/70466955/92696330-fe219f80-f349-11ea-839e-840c3e04cc29.png)

**Comment by micker** [comment]
yes => 3dth party bug
