### ISSUE TITLE
[4.0] Frontend editing not allowed below super user

### ISSUE THREAD

**Issue by Harmageddon** [joomla/joomla-cms#30628]
### Steps to reproduce the issue
1. Create a user in the "Administrator" (not Super User!) group.
2. Enable frontend module editing and allow frontend module editing for the "Administrator" group.
3. Log in to the Administrator account in frontend.
4. Try to edit a module in frontend.

### Expected result
The module edit screen should be shown.

### Actual result
Error 403: You don't have permission to access this.

### System information (as much as possible)
PHP 7.2
Tested with 4.0-beta3 and current 4.0-dev (a1990fff0b).

### Additional comments
Reported by user LukasHH at https://forum.joomla.de/thread/12433-j4-beta-3-frontend-bearbeitung-module-führt-zu-403-fehler/. Confirmed by @ChristineWk and myself.

Not sure when this bug was introduced, but it worked in 3.x, and still works in staging.

**Comment by infograf768** [comment]
The default for anyone below superuser is "Not Allowed."
<img width="847" alt="Screen Shot 2020-09-13 at 16 29 30" src="https://user-images.githubusercontent.com/869724/93020649-7f916000-f5de-11ea-8528-fb8c7abef8a0.png">

It's the same in 3.x

<img width="1169" alt="Screen Shot 2020-09-13 at 16 31 33" src="https://user-images.githubusercontent.com/869724/93020678-a485d300-f5de-11ea-87bc-5cd6af86c01c.png">

Once defined as Allowed in the Options, an Administrator can edit modules in frontend.

**Comment by Harmageddon** [comment]
> Once defined as Allowed in the Options, an Administrator can edit modules in frontend.

For me, this doesn't work. I set it to "allowed" in the options of "Modules" (step 2 of the description above).
Does it work on your 4.0 site?

**Comment by infograf768** [comment]
yep.

**Comment by ghost** [comment]
Issue confirmed:

![Screen Shot 2020-09-13 at 17 57 54](https://user-images.githubusercontent.com/70466955/93022774-3a275f80-f5eb-11ea-9af6-f6bae76b35e2.png)

#### System Information

php: Linux lamp10.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.4.el6h.x86_64 #1 SMP Thu Nov 15 04:53:17 EST 2018 x86_64
dbserver: mysql
dbversion: 5.7.29-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.3.21
server: Apache
sapi_name: cgi-fcgi
version: NightlyBuild - Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

**Comment by infograf768** [comment]
Tested again and I confirm... Sorry.

**Comment by infograf768** [comment]
<img width="871" alt="Screen Shot 2020-09-13 at 18 08 07" src="https://user-images.githubusercontent.com/869724/93022995-62638e00-f5ec-11ea-94c9-d04f31839153.png">

<img width="853" alt="Screen Shot 2020-09-13 at 18 09 05" src="https://user-images.githubusercontent.com/869724/93023001-68f20580-f5ec-11ea-8a58-9126a150842c.png">

<img width="317" alt="Screen Shot 2020-09-13 at 18 09 32" src="https://user-images.githubusercontent.com/869724/93023021-6f807d00-f5ec-11ea-92e9-76bac2616178.png">

**Comment by infograf768** [comment]
But then, **after clicking the icon**
`403 You don't have permission to access this. Please contact a website administrator if this is incorrect. `

**Comment by infograf768** [comment]
So, confirmed indeed

**Comment by infograf768** [comment]
Please test modifying this line
https://github.com/joomla/joomla-cms/blob/0e5b6cf6568b45f107c2fd8bd34d1202441561f7/components/com_config/src/Dispatcher/Dispatcher.php#L37

to
`if (!$this->app->getIdentity()->authorise('module.edit.frontend', 'com_modules.module.' . $mod->id))`

**Comment by infograf768** [comment]
This works for all modules but the menu modules
grr

**Comment by ChristineWk** [comment]
@infograf768 

I changed above line accordingly and it looks OK for menue modules.

**Comment by infograf768** [comment]
@ChristineWk 
yep. I had to resave global config to get a correct result on my test site.
Will do PR.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/30636

closing as we have a patch

**Comment by infograf768** [comment]
Reopening as PR does not work

**Comment by Harmageddon** [comment]
New / extended PR approach: #30779. I hope it works this time.

**Comment by alikon** [comment]
please test #30779
