### ISSUE TITLE
Jommlas 3.9.21 [com_fields] Contact-Mail Custom field issue after joomla 3.8.3 

### ISSUE THREAD

**Issue by stbrandon2020** [joomla/joomla-cms#30627]
### Steps to reproduce the issue
Have the same problem as nader24 in #20195 now in Joomla 3.9.21 PHP 7.3
I had 2 contacts on my page and i made 2 different catagory for mail-custom-fields and made also different custom field for each catagory and contact it. I never tried in former versions, but in 3.9.21 it doesn't work. If i select the category in the fields nopes is shown. If i select *all in category or Main Contact its showing on both contact-forms.

### Expected result
All solutions i found under #20195 are now in code for 3.9.21. Hope somebody have an idea?

### System information (as much as possible)
Joomla 3.9.21  PHP 7.3.13

**Comment by ghost** [comment]
Can't confirm.

### System information
php: Linux lamp10.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.4.el6h.x86_64 #1 SMP Thu Nov 15 04:53:17 EST 2018 x86_64
dbserver: mysql
dbversion: 5.7.29-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.3.21
server: Apache
sapi_name: cgi-fcgi
version: NightlyBuild - Joomla! 3.9.22-dev Development [ Amani ] 26-August-2020 08:12 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

**Comment by stbrandon2020** [comment]
Is it fixed with 3.9.22 ?
Not yet in 3.9.21.

**Comment by ghost** [comment]
> Is it fixed with 3.9.22 ?

I don't know. 
I test Issue on "version: NightlyBuild - Joomla! 3.9.22-dev Development [ Amani ] 26-August-2020 08:12 GMT" like written in https://github.com/joomla/joomla-cms/issues/20195#issuecomment-382499644 and can't confirm it.

**Comment by stbrandon2020** [comment]
Now on 3.9.22. Still the same error. 
I think it never worked. Is there anyone who successfully created contact fields with different categories in 2 different contact forms?
