### ISSUE TITLE
Upgrade from 3.9.21 to 3.10 Alpha - Error in default.php at line 1410. Update to 

### ISSUE THREAD

**Issue by rgtr** [joomla/joomla-cms#30622]
### Steps to reproduce the issue
Set Update Options to Testing, Alpha.
Updates ok. 
But throws a warning message " trying to get property "version"of non-object in c:\xampp\ .. \administrator\components\com_joomlaupdate\models\default.php on line 1410 "
Message in green reads: your site has been updated. Your Joomla version is now Joomla 3.10.0-alpha1.
See screenshot attached

Akeeba backup used and restored ok.
Update Options set to Custom URL, and path to https://update.joomla.org/core/test/310to4_list.xml
Checks appear ok - See screenshot attached
Appears to update, but message as follows: "This template is not available for display"
See screenshot attached

Presumably this relates to the property error before.

### Expected result

Two successful upgrades

### Actual result
Both Upgrades had errors, the second one fatal.

### System information (as much as possible)

Windows 7 Professional - SP1
XAMPP Control Panel v3.2.3
Apache/2.4.38 (Win64) Open SSL/1.1.1b PHP 7.2.16
Using Google Chrome - Latest Version

### Additional comments
This web site originated in Joomla 1.5 and has been updated ok over the years.
Have tried on a web site created last year which also fails

**Comment by rgtr** [comment]
Just repeated the above on fasthostingdirect [stackcp]. Upgrade to 3.10 Alpha works for both old [started at J 1.5] and new sites. However, when updating to 4.0 Beta 3 ... CRASH. Browser title says Error 0, message is Error - The template for this display is not available. with "Call to undefined method Joomla\CMS\Filesystem\File::read()".

So a bug ... and lucky it's raining so no gardening !

Guess the earlier bug was due to Win 7.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30622">issues.joomla.org/tracker/joomla-cms/30622</a>.</sub>

**Comment by rgtr** [comment]
Attempting to upgrade a site to 4.00 Beta 3 on Stack CP
First I uploaded / installed Joomla_4.0.0-beta3-Beta-Full_Package.zip
It seemed to install ok, and then crashed with the same template error.

Next I tried to do a new install ... 
Created a database, uploaded the zip, and extracted.
Started ok ... and then CANNOT use localhost which effectively means that is it blocked ...

Richard<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30622">issues.joomla.org/tracker/joomla-cms/30622</a>.</sub>

**Comment by Quy** [comment]
Please try again using this custom URL `https://developer.joomla.org/nightly-builds.html` from https://developer.joomla.org/nightly-builds.html

**Comment by Quy** [comment]
https://www.joomla.org/announcements/release-news/5822-joomla-4-0-0-beta4-and-joomla-3-10-alpha2.html

**Comment by rgtr** [comment]
hi
thanks.
delayed due to gout flare
r

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by rgtr** [comment]
Hi 

Thanks for all the support.

I have today successfully updated my first web site created in Joomla 1.5. And then one created in Joomla 3.7 [I think].
The cleanup process is all important. It included removing " nav_pills" from the menu configuration. I also removed AkeebaStrapper rev699A630-1420553182 as there was a later one.

The next step is to allocate everything to the new positions in Cassiopaea in the usual manner.

Brilliant job.

Thanks.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30622">issues.joomla.org/tracker/joomla-cms/30622</a>.</sub>
