### ISSUE TITLE
[4.0] Popovers in Frontend Modules and Menus 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#30639]
### Steps to reproduce the issue
You need an installation with at least one module. 
Enable the editing of modules and menus (Backend - global configuration).
Login as super user to the frontend. 

All items (aticles, menuitems) now can be edited from here.

### Expected result
An edit icon near the item, no popvers.

### Actual result

Edit is possible via a bootstap popover, which appears on hovering the item. 

![screen shot 2020-09-14 at 12 58 28](https://issues.joomla.org/uploads/1/5f6540adc4d33eea28605e32f006e006.png)

**Comment by brianteeman** [comment]
For reference the popover link is for the menu edits

**Comment by sandewt** [comment]
I confirm this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30639">issues.joomla.org/tracker/joomla-cms/30639</a>.</sub>

**Comment by chmst** [comment]
@brianteeman In J4 we did not want popvers any more, or am I wrong?

**Comment by brianteeman** [comment]
@chmst correct - we dont want them

**Comment by bembelimen** [comment]
@brianteeman do you have an idea what could be a solution?

(And for reference: @joomla/joomla-accessibility-team-jat )

**Comment by carcam** [comment]
Adding the edit link next to each item might be a bit overwhelming but it's what I think could work best in this situation. I actually think the popover is redundant in any case...

Maybe we could add an "Edit links" button next to the edit module button that enables those edit links...

**Comment by chmst** [comment]
I tried visble Edit Buttons. 
1) it is overwhelming in big menus
2) The edit buttons are rather small, on smaller devices and touch screens it is hard to click it. 
3) With a new line for the edit icon, the menus become too big

I imagine an accordion or two tabs if a user may edit menu Items. 
The one is for normal use
the other has links to the menuItem edit screen instead of link.

This could be made accessible. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30639">issues.joomla.org/tracker/joomla-cms/30639</a>.</sub>

**Comment by brianteeman** [comment]
How about something like the following which would be permanently displayed to the appropriate user and not just on hover.

### Module only
![image](https://user-images.githubusercontent.com/1296369/103426346-b486ea00-4bb0-11eb-8b3e-31e06395c6ba.png)

### Module and Menu
![bits2](https://user-images.githubusercontent.com/1296369/103426507-e5b3ea00-4bb1-11eb-9864-0d46565e8b8d.gif)

**Comment by brianteeman** [comment]
I should have something to submit tomorrow. I misunderstood the menu link as a menu not an item so I couldnt finish it today.

It will be accessible AND javascript free

**Comment by brianteeman** [comment]
See #32070
