### ISSUE TITLE
Installation page loops back to itself, no errors printed anywhere!

### ISSUE THREAD

**Issue by AlainKnaff** [joomla/joomla-cms#30635]
### Steps to reproduce the issue
1. Download Joomla
2. Unzip Joomla
3. Fix permissions (why the hell are these wrong in the first place?)
4. Visit the newly created site
5. Fill in first page (site name, description, mail, password)
6. Click next.

### Expected result
It should move on to the next page ("(2) Database"). If for some reason it can't, it should say WHY. Hey, the version number has a leading 3, not a leading 0. By now, the developers should KNOW that we need diagnostics!

### Actual result
Same page ("(1) Configuration") is redisplayed, WITHOUT ANY INDICATION WHATSOEVER went wrong.

### System information (as much as possible)
Ubuntu 20.04

### Additional comments
Googling around, the forums seem to be full of similar issues ("white page of death", etc.), but NO workable solution. Why is this still a thing in a 3.x version? Wouldn't now be the perfect time to get these fixed for good?

**Comment by brianteeman** [comment]
That's really not the way to go about asking for help

When you say "fix permissions" what exactly do you mean. I've never touched file permissions

You mention "white page of death" in your additional comments which is an indication of a php error with a server setting of display errors off but you dont describe this happening to you so I dont know why you have mentioned this unrelated item.

There is a reason that it asked you for System information (as much as possible) when you submitted the report

**Comment by AlainKnaff** [comment]
> That's really not the way to go about asking for help

Well, obviously I did get some response... Which is already much better than some other projects. Thanks :-)

> When you say "fix permissions" what exactly do you mean.

find . -name "*.php" -print0 | xargs -0 chmod u+x

> I've never touched file permissions

Well, in the zip file (why not a tar?), all files were lacking the execute bit, producing permission errors...

> You mention "white page of death" in your additional comments which is an indication of a php error with a server setting of display errors off but you dont describe this happening to you so I dont know why you have mentioned this unrelated item.

It is related inasmuch it is a case of another failure without message... But "stuck on first page loop" also finds lots of stuff (... but without workable solutions unfortunately :-( )

**Comment by ChristineWk** [comment]
> It is related inasmuch it is a case of another failure without message... But "stuck on first page loop" also finds lots of stuff (... but without workable solutions unfortunately :-( )


Means what?
Why do you make point 4 before point5?
https://docs.joomla.org/J3.x:Installing_Joomla

**Comment by AlainKnaff** [comment]
> Why do you make point 4 before point5?

Point 4: "Visit the newly created site" = short hand for visited the URL of the site to be created. Yes, at that point it is not a site yet.
Point 5: Fill in first page (site name, description, mail, password) => indeed, once I went the the site's URL, I get correctly redirected to the installation directory where I can fill in the form. So far so good.

But the issue is "point 6". Rather than getting to the next form (where I would enter database configuration), I keep getting sent back to the first form.

Now where was there a mix-up in order here? Maybe I'm misunderstanding something here, but to me these 2 points look correctly ordered... or how would you have done it differently?

In any case, there are no messages that explain me why I can't move on at point 6, and that is the big issue here.

**Comment by ChristineWk** [comment]
To continue on the installation (with next, e.g. database etc.) you will get a message at the top.
You hv to delete a txt file from the installation file.

**Comment by AlainKnaff** [comment]
> To continue on the installation (with next, e.g. database etc.) you will get a message at the top.
Unfortunately, there is no message at the top, except an unrelated warning about deprecated syntax with curly braces in libraries/vendor/joomla/string/src/phputf8/utils/unicode.php on line 46

> You hv to delete a txt file from the installation file.
Thanks for the tip. So I removed all .txt files under the installation directory, and then clicked next, I still got back to the same page.

**Comment by ChristineWk** [comment]
> > You hv to delete a txt file from the installation file.
> > Thanks for the tip. So I removed all .txt files under the installation directory, and then clicked next, I still got back to the same page.
All txt files? There is only one there, to delete. If done, then you can go back to installation view. Check data base entries again. It can happen, that the field of PW of database, is blank.

**Comment by AlainKnaff** [comment]
> All txt files? There is only one there, to delete.

Ok, so which one would that be? As you didn't specify, I just removed them all (most were called README.txt or LICENSE.txt, so I figured this should be safe).

> If done, then you can go back to installation view.

Problem is, I don't want to get *back*, I want to *move*on*

> Check data base entries again. It can happen, that the field of PW of database, is blank.

How can database entries possibly be the problem? The problem happens before I even get a chance to fill in any database related information. And yes, I did set up the database user with a non-blank password.

**Comment by ChristineWk** [comment]
Don't know by heart, but it's a long file with some numbers/characters<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30635">issues.joomla.org/tracker/joomla-cms/30635</a>.</sub>

**Comment by AlainKnaff** [comment]
> Don't know by heart, but it's a long file with some numbers/characters

No file matching that description was available :-(

**Comment by brianteeman** [comment]
tar is available if you prefer it
https://downloads.joomla.org/cms/joomla3/3-9-21

Still dont see why you need to change the permissions of the files - no one else does

**Comment by Fedik** [comment]
you have a problem with your server configuration,

> Fix permissions (why the hell are these wrong in the first place?)

because you have an incorrect server configuration

**Comment by shim-sao** [comment]
If you have to fix permissions, it's because you upload the files by connecting a user on an another user directory.
I often do this with root on local but when apache want to access files, it is not authorized to write or execute the files because it's not the good user/owner.
Owner ```root``` on ```other_username```, it's why you do ```chmod u+x```.

If you don't want this **you must be connected with the user that own the directory**... this is better for the security of the files.

It's the same for all CMS

**Comment by travisrisner** [comment]
Do you happen to use Cloudflare as DNS? I have encountered this issue numerous times since one of the last few releases. I've found the fix is to disable Cloudflare's proxy services for the install, then enable it again once installed.

**Comment by travisrisner** [comment]
@AlainKnaff, I was reminded of this while installing a site again today. Do you happen to utilize Cloudflare for DNS on your domain name(s)?

**Comment by AlainKnaff** [comment]
> @AlainKnaff, I was reminded of this while installing a site again today. Do you happen to utilize Cloudflare for DNS on your domain name(s)?

Thanks for your message. Nope, I don't use Cloudflare, and operate my own DNS.

As for the problem, I'm starting to hunt down all $app->redirect() calls, and add error_log() calls before them, to get a better visibility what is going on. Just wondering why these aren't there by default...

**Comment by Hackwar** [comment]
Since this is related to J3 and J3 is EOL in terms of bugfixes, I'm closing this one. If you still have this issue with J4, then please open another issue.
