### ISSUE TITLE
Category list doesn't display all categories

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#30643]
### Steps to reproduce the issue
Install Joomla with Sample data learn Joomla
Create a new Top level Category and several child Categories
Edit Category list all categories menu item ... set to show empty categories, all levels and category Titles

### Expected result
All Categories should be listed.

### Actual result
'Sample Data-Articles' is not shown in the list
The new Categories you created are not in the list.

**Comment by ghost** [comment]
Can't confirm:

Backend | Frontend
--- | ---
![image](https://user-images.githubusercontent.com/70466955/93170134-e1f57800-f726-11ea-8550-a50533483650.png) | ![image](https://user-images.githubusercontent.com/70466955/93170148-e9b51c80-f726-11ea-8fbf-5751542b47ed.png)

**Comment by SharkyKZ** [comment]
@Webdongle are you editing `Article Categories` menu item that was installed with sample data? It has `Sample Data-Articles` selected as root category which is why `Sample Data-Articles`, `Uncategorised` and newly created categories are not shown.
