### ISSUE TITLE
Syntax Error in preconfigured htaccess.txt file

### ISSUE THREAD

**Issue by otpfiste** [joomla/joomla-cms#30649]
### Steps to reproduce the issue
Preconfigured htaccess.txt has an important security error, the following is wrong:
&lt;IfModule autoindex&gt;

### Expected result
Please correct to:
&lt;IfModule mod_autoindex.c&gt;

### Actual result
IndexIgnore *
-> never executed!!

### System information (as much as possible)
All apache web servers

### Additional comments
Please update also documentation:
https://docs.joomla.org/Preconfigured_htaccess

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/security/policy

**Comment by richard67** [comment]
@otpfiste Are you sure that it is a syntax error?

According to [https://httpd.apache.org/docs/trunk/en/mod/core.html#ifmodule](https://httpd.apache.org/docs/trunk/en/mod/core.html#ifmodule) both is possible, use the module identifier or the file name:

> The module argument can be either the module identifier or the file name of the module, at the time it was compiled. For example, rewrite_module is the identifier and mod_rewrite.c is the file name.

**Comment by richard67** [comment]
Hmm, but according to [https://httpd.apache.org/docs/2.4/mod/mod_autoindex.html](https://httpd.apache.org/docs/2.4/mod/mod_autoindex.html), the module identifier is "autoindex_module" and not just "autoindex", so that could really be a problem.

**Comment by otpfiste** [comment]
Before reporting I tested it with just "autoindex" and it's not working. I suggest to change it to the more common module-file form like the other IfModule directives in htaccess.txt.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30649">issues.joomla.org/tracker/joomla-cms/30649</a>.</sub>

**Comment by HLeithner** [comment]
@zero-24 can you have a look please?

**Comment by SharkyKZ** [comment]
Nothing to look at, report is correct. Please test PR https://github.com/joomla/joomla-cms/pull/30655.
