### ISSUE TITLE
J 4.0 "lazy-loading" with php7-4 causes warning

### ISSUE THREAD

**Issue by schultz-it-solutions** [joomla/joomla-cms#30647]
### Steps to reproduce the issue
The "lazy-loading" method "image" (defined in .../libraries/src/HTML/HTMLHelper.php ) creates PHP warnings, when images are loaded without the $attribs 

I belief, the reason is that  $attribs is set to NULL, if not provided in the method-call, and adding an array-element "loading" to a NULL value causes this warning (in PHP 7.4).

### Expected result
no PHP warning

### Actual result

Warning: Illegal string offset 'loading' in .../libraries/src/HTML/HTMLHelper.php on line 693

### System information (as much as possible)
PHP 7.4.9
Joomla! 4.0.0-beta4-dev Development [ Mañana ] 29-July-2020 18:21 GMT 

### Additional comments

method definition in .../libraries/src/HTML/HTMLHelper.php

	public static function image($file, $alt, $attribs = null, $relative = false, $returnPath = 0)

**Comment by SharkyKZ** [comment]
Duplicate issue https://github.com/joomla/joomla-cms/issues/30615
