### ISSUE TITLE
com_contact does not display Tags on Category menu view

### ISSUE THREAD

**Issue by leetempest** [joomla/joomla-cms#30640]
### Steps to reproduce the issue
Create a new tag within the contacts component. Add a new contact and add the tag. Create a Menu item, Contacts » List Contacts in a Category. Then view from frontend. All contact information is displayed but tags are not

### Expected result
Should see tags rendered with contact details

### Actual result
No tags rendered with contact details

### System information (as much as possible)
3.9.21, no template over ride using core contact tmpl files

**Comment by ghost** [comment]
Can't confirm (if you mean com_fields as shown in title):

![Screen Shot 2020-09-14 at 15 52 06](https://user-images.githubusercontent.com/70466955/93094548-53d7ae00-f6a2-11ea-8fc8-e4967e2c68c7.png)

**Comment by leetempest** [comment]
Apologies, I got the title incorrect, yes I agree custom fields do display but assigning tags to a contact and then trying to display them does not.

**Comment by ghost** [comment]
Issue confirmed.

**Comment by alikon** [comment]
unable to replicate
![Screenshot from 2020-09-14 18-08-28](https://user-images.githubusercontent.com/181681/93110254-5d1e4600-f6b5-11ea-86c3-17337216357c.png)

**Comment by leetempest** [comment]
Alikon, Yes it displays when viewing a specific contact but it does not display when using the Contact Category menu list view.

**Comment by alikon** [comment]
sorry  just to understand....
 in the  Expected result you wrote 

> Expected result
Should see tags rendered with contact details

 but you mean that tags should be displayed here ?
![Screenshot from 2020-09-14 18-50-40](https://user-images.githubusercontent.com/181681/93114767-4f6bbf00-f6bb-11ea-943c-6fa6ff9ad481.png)

**Comment by ghost** [comment]
In Menu ```List Contacts in a Category``` no Tags to show/hide are available.
Contact | Menu
--- | ---
![Screenshot_2020-09-15 Contacts Edit - fw - Administration](https://user-images.githubusercontent.com/70466955/93172681-9a251f80-f72b-11ea-8c49-232face6d5eb.png) | ![Screenshot_2020-09-15 Menus Edit Item - fw - Administration](https://user-images.githubusercontent.com/70466955/93171994-57167c80-f72a-11ea-9e6f-969142a0a483.png)

#### Frontend
![Screenshot_2020-09-15 Contact(1)](https://user-images.githubusercontent.com/70466955/93172318-ee7bcf80-f72a-11ea-97fe-a0b650206d46.png)

**Comment by infograf768** [comment]
Folks, I am finishing up a new display for the List Contact Category.
Will include tag in it.
Screenshot coming.

**Comment by infograf768** [comment]
FYI, List Article Category does not display the article tag either.

**Comment by infograf768** [comment]
The issue is more related to the fact that we can't get the `$this->item->tags->itemTags` value as this would require an important refactoring of the ContactModel (as well for Articles btw), rather than a parameter to display or not the Tag.

**Comment by ghost** [comment]
related #24551

**Comment by brianteeman** [comment]
I wpuld mark this as expected behaviour

**Comment by Hackwar** [comment]
I agree and I'm closing this one.
