### ISSUE TITLE
5 Signs of Differentiating Pro & Scam Essay Writing Services

### ISSUE THREAD

**Issue by Kenny-Carter** [joomla/joomla-cms#30657]
[Signs of Differentiating Pro & Scam Essay Writing Services.pdf]### Steps to reproduce the issue
[Signs of Differentiating Pro & Scam Essay Writing Services.pdf](https://issues.joomla.org/uploads/1/3294d11444846b314e355f6afa749177.pdf)

**Comment by Formatio-hippocampi** [comment]
Spam

**Comment by Formatio-hippocampi** [comment]
i have reported @Kenny-Carter
