### ISSUE TITLE
J4 update to joomla beta4 wrong

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#30660]
update to beta4 does not work at all. Starting update vai administrator installs beta3 though telling it would update to Beta4. After update process ends successfully site has been updated from beta3 to beta3!!!   
Seems that update-url is wrong - pointing to beta3? 

![update-info](https://user-images.githubusercontent.com/69053785/93319265-f5c8d900-f80f-11ea-9b80-29a0320f6a63.png)

if using beta4-update zip-file from https://github.com/joomla/joomla-cms/releases/tag/4.0.0-beta4  I get  this (seems that my site has been broken/destroyed):

**Oops! An Error Occurred
The server returned a "500 Whoops, looks like something went wrong.".

Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.**

**Comment by zero-24** [comment]
Hi the update URL has just been corrected here: https://github.com/joomla/update.joomla.org/commit/f08e9668f29526f1a077839a9c287bd0ad41683e (might take some time until it is updated via the CDN)

> if using beta4-update zip-file from https://github.com/joomla/joomla-cms/releases/tag/4.0.0-beta4 I get this (seems that my site has been broken/destroyed):

Did you upgraded via the steps described here: https://docs.joomla.org/J4.x:Upgrade_to_4.0_Beta_4 ?

**Comment by ChristineWk** [comment]
Maybe history behind?

https://github.com/joomla/joomla-cms/issues/30365 > https://github.com/joomla/joomla-cms/pull/30373<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30660">issues.joomla.org/tracker/joomla-cms/30660</a>.</sub>

**Comment by jschmi102** [comment]
hi,
did not check  https://docs.joomla.org/J4.x:Upgrade_to_4.0_Beta_4, as doing update via admin console. After having updated database tables, update now worked
