### ISSUE TITLE
[Joomla 4] Update Error

### ISSUE THREAD

**Issue by diddipoeler** [joomla/joomla-cms#30661]
I got this error in update form 4dev to 5dev:

Unknown column 's.inheritable' in 'field list'

DatabaseDriver->setQuery(object(MysqliQuery)) in /www/htdocs/w0086dfc/joomla40/libraries/src/Application/AdministratorApplication.php (line 264)

                )
                    ->bind(':style', $admin_style, ParameterType::INTEGER);
            }
            $query->order($db->quoteName('s.home'));
            $db->setQuery($query);
            $template = $db->loadObject();
            $template->template = InputFilter::getInstance()->clean($template->template, 'cmd');
            $template->params = new Registry($template->params);

**Comment by HLeithner** [comment]
https://docs.joomla.org/J4.x:Upgrade_to_4.0_Beta_4

**Comment by wetken** [comment]
I'm between a rock and a hard place with this. I'm trying to update from 3.10 to 4.1
When I try the update I get an error message telling me "Unknown column 's.inheritable' in 'field list'".
If I follow the suggested workaround and add the column and try the update again, it fails trying to implement 3.10.0-2020-08-10.sql which wants to add this field, but it is now already there.
It would be recoverable if only I had a list of the other .sql files that remain to be implemented.
Is the only way to compare the before database with a virgin 4.1 database and make the changes by hand?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30661">issues.joomla.org/tracker/joomla-cms/30661</a>.</sub>
