### ISSUE TITLE
[4.0] com_media: Frontend show empty folder "images"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#30665]
### Steps to reproduce the issue
Append Image to Article in Frontend:
Frontend | Backend
-- | --
![image](https://user-images.githubusercontent.com/70466955/93426613-b0161a00-f8bc-11ea-825c-27954ff361a4.png) | ![image](https://user-images.githubusercontent.com/70466955/93426592-a5f41b80-f8bc-11ea-97d4-1fcb648a7443.png)

### Expected result
Frontend show folder ```images```.

### Actual result
Frontend show empty folder ```images```.

### System information (as much as possible)
php: Linux lamp10.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.4.el6h.x86_64 #1 SMP Thu Nov 15 04:53:17 EST 2018 x86_64
dbserver: mysql
dbversion: 5.7.29-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.3.21
server: Apache
sapi_name: cgi-fcgi
version: NightlyBuild - Joomla! 4.0.0-beta5-dev Development [ Mañana ] 15-September-2020 19:15 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

**Comment by SharkyKZ** [comment]
I can't reproduce the issue. If you updated from an older nightly, try clearing browser cache.

**Comment by ghost** [comment]
Saw Issue first time yesterday, update nightly today, tried another browser, same issue.

**Comment by infograf768** [comment]
Can't reproduce issue either.
I suggest you install a brand new nightly or beta4, not update.

**Comment by ghost** [comment]
>  I suggest you install a brand new nightly or beta4, not update.

Update nightly > nightly isn't save? 

> To always use the latest version and test the update component you can use this custom update server: https://update.joomla.org/core/nightlies/next_major_list.xml
(https://developer.joomla.org/nightly-builds.html)

**Comment by richard67** [comment]
> Update nightly > nightly isn't save?

Definitely not granted to be safe, e.g. because files and folders to be deleted are not updated in script.php with every nightly build.

**Comment by ghost** [comment]
- fresh install at launch.joomla.org: Same issue on Frontend.
- update on nightly build: Same Issue on Frontend.
- create new folder in frontend not possible:
![Screenshot_2020-09-17 Home](https://user-images.githubusercontent.com/70466955/93449827-83223100-f8d5-11ea-8aac-7b3fd1bd30ea.png)

**Comment by Quy** [comment]
I am not able to reproduce these issues on cloudaccess.host with a clean install.

**Comment by ghost** [comment]
Close having issue as only one.

**Comment by ghost** [comment]
Reopen cause: Set in ```Global Configuration``` > ```Site``` > ```Add Suffix to URL``` on ```No``` Issue is gone. By default ```Add Suffix to URL``` is ```Yes```.

**Comment by SharkyKZ** [comment]
I can see where this is coming from but not sure if the change should be reverted or JS improved to build better URLs.

**Comment by SharkyKZ** [comment]
Going to revert this for now. But ultimately JS should not expect only non-SEF URLs to be used.

See PR https://github.com/joomla/joomla-cms/pull/30688.
