### ISSUE TITLE
[4.0]Tabs in configuration not 'wrapping'

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#30667]
### Steps to reproduce the issue
install an extension with a lot of tabs in the configuration

### Expected result

When tabs don't fit the screen size, they should be wrapped
![screen shot 2020-09-17 at 10 49 43](https://issues.joomla.org/uploads/1/03be77f8f37c480c2ac1172e64bf6701.jpg)

### Actual result

tabs do not wrap but disappear off screen
![screen shot 2020-09-17 at 10 48 04](https://issues.joomla.org/uploads/1/569fd1059d2637959318ba8f83062d9b.jpg)

**Comment by ghost** [comment]
Issue confirmed.

**Comment by richard67** [comment]
Duplicate issue to #28799 ?

**Comment by Quy** [comment]
Duplicate

**Comment by Ruud68** [comment]
as you can see in the screen image of 'expected' (where it is working correct) this is a one line css fix, not sure if that will also fix #28799 looking at the time that issue is open and the amount of discussion there

**Comment by Ruud68** [comment]
@Formatio-hippocampi   can you test the above PR? if you need help please let me know.

**Comment by ghost** [comment]
test only by Patchtester.

**Comment by Ruud68** [comment]
Yeay, well that will not work :( I can sent you the two css files that have the change, is that an option?

**Comment by Ruud68** [comment]
@Formatio-hippocampi download the two css files from here: https://office.onlinecommunityhub.nl/nextcloud/s/3BfxFeAjXAmpb2B
and then copy them to [site root]/administrator/templates/atum/css/vendor/joomla-custom-elements
