### ISSUE TITLE
Page Break plugin : open by default with Slider presentation style

### ISSUE THREAD

**Issue by Nuyonuyonoina** [joomla/joomla-cms#30670]
### Steps to reproduce the issue
Add a page break in an article. In Content - Page Break plugin, set Presentation Style > Sliders. Then display your page.

### Expected result
Closed slider.

### Actual result
Slider is open.

### System information (as much as possible)
Joomla 3.9.21. Tested with different templates and editors.

**Comment by SharkyKZ** [comment]
If you're talking about the first page always being displayed, this is expected behavior.

**Comment by SharkyKZ** [comment]
OK, I think I see the issue. Second page (first slider) is open but it shouldn't be.

**Comment by ghost** [comment]
```Pages```has another behaviour than ```Sliders```and ```Tabs```:
Pages | Sliders | Tab
-- | -- | --
![image](https://user-images.githubusercontent.com/70466955/93566056-b4116d00-f98c-11ea-9a1b-80173493857a.png) | ![image](https://user-images.githubusercontent.com/70466955/93566076-bffd2f00-f98c-11ea-96bb-e6225ae468fd.png) | ![image](https://user-images.githubusercontent.com/70466955/93566105-cab7c400-f98c-11ea-9da6-61772a8c3348.png)

**Comment by Hackwar** [comment]
I've checked this and the code has since been changed. The sliders are closed by default now, especially with Bootstrap 5. Since this issue thus is solved, I'm closing this issue.
