### ISSUE TITLE
[4.0] JCLOSE not translated in alert

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#30682]
### Steps to reproduce the issue
Go to System > Redirects
Use browser's inspector to hover over close icon.
See markup for untranslated text.

![jclose](https://user-images.githubusercontent.com/368084/93652194-0e302380-f9c9-11ea-8795-3988ee76232b.png)

**Comment by ghost** [comment]
Issue confirmed.

**Comment by sandewt** [comment]
I confirm this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30682">issues.joomla.org/tracker/joomla-cms/30682</a>.</sub>

**Comment by infograf768** [comment]
In fact this is happens everytime a message is displayed whether in redirects or save success, etc.
Code is in `/media/vendor/joomla-custom-elements/js/joomla-alert-es5.js

3 strings are concerned
JCLOSE
JOPEN
JOK

We can create the strings for `JOPEN` and `JOK` (and use some existing ones for close, for example `JLIB_HTML_BEHAVIOR_CLOSE="Close"`

As these alerts are used everywhere (back and frontend) and they are js, we have to declare them somewhere.
Any idea where?

`Text::script('JLIB_HTML_BEHAVIOR_CLOSE', true);`
`Text::script('JOPEN', true);`
`Text::script('JOK', true);`

**Comment by infograf768** [comment]
Found out, will make patch, creating also the 3 strings and adding the declaration in message .php

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/30684

Closing as we have a patch
