### ISSUE TITLE
[4.0] Contact - Link options: Rename 1 Label, append missing Label

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#30685]
### Steps to reproduce the issue

- Go to ```administrator/index.php?option=com_contact&view=contacts```
- Click on any existing contact or create a new one
- Click the ```Display```-tab
- Navigate to the ```Link options```-section

![Screenshot_2020-09-19 Contacts New - fw4 - Administration](https://user-images.githubusercontent.com/70466955/93661721-5ba8a100-fa5a-11ea-8d24-85a18ff10e61.png)

1. Rename ```Link D Label``` > ```Link B Label```
1. Append missing ```Link D Label```

### System information (as much as possible)
php: Linux lamp121.cloudaccess.net 2.6.32-673.8.1.lve1.4.3.1.el6.x86_64 #1 SMP Thu May 5 16:06:47 EDT 2016 x86_64
dbserver: mysql
dbversion: 5.7.29-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.3.21
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.0.0-beta5-dev Development [ Mañana ] 15-September-2020 19:15 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

### Additional comments
related #30020

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30687.
