### ISSUE TITLE
[4.0] Category Sub-Heading Position is Wonky

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#30699]
### Steps to reproduce the issue
With the Category Title set to display, and a Page Sub-Heading added, the sub-heading appears before the Category Title and on the same line.
Should it not appear AFTER the Category Title and on another line.
See screenshot.
Category Title = Category Blog Layout
Sub-Heading = This is a page sub-heading in the wrong location!!!

Both are invoked and set to publish.

However, the sub-heading is BEFORE the Category Title and ON THE SAME LINE.

This should not be the case.

Order should be:
Category Title
Page Sub-heading
![screen shot 2020-09-20 at 13 57 33](https://issues.joomla.org/uploads/1/9efde463ade926b0e7a8c66871299cad.jpg)

### Expected result
Two titles, main title above the sub-heading.

### Actual result

See screenshot attached.

### System information (as much as possible)

Latest Joomla! 4 Beta nightly build.

**Comment by chmst** [comment]
See https://issues.joomla.org/tracker/joomla-cms/30422

It is about backward compatibility. 

About the subtitle in an extra line: In the first attempt I too wantd to have the subtitle in another line. But this is an error. Subtitles are used for adding Information to a title. In printed media you often will find such a subtitle following immediatedly the title, but in another font, font-size or font-color. 

These subtitles are a case for customised layouts (overrides). No matter what Joomla implements, half the users want it the other way around. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30699">issues.joomla.org/tracker/joomla-cms/30699</a>.</sub>

**Comment by 200MPHMEDIA** [comment]
I think I know what a "sub-title" is.
The program, is if you set the Category name to display AND have a sub-title, they appear on the same line as:

Custom Heading
[sub-title text][Category Title]

The Category title should appear BEFORE the sub-title:

Custom Heading
[Category Title]
[Sub-Title]

Or, the protocol should be "if" a sub-title, the Category Title does not show.

But this doesn't fly well if you want a Category Title with a sub-title with or without a Custom Heading.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30699">issues.joomla.org/tracker/joomla-cms/30699</a>.</sub>

**Comment by 200MPHMEDIA** [comment]
Line 2 "program" should be "problem"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30699">issues.joomla.org/tracker/joomla-cms/30699</a>.</sub>

**Comment by brianteeman** [comment]
I can't find a Page Sub-Heading

**Comment by brianteeman** [comment]
Can someone tell me where this page sub-headinng is?

**Comment by brianteeman** [comment]
This was opened 4 years ago. In the absence of the requested information this should be closed. It can always be re-opened if the information is provided
