### ISSUE TITLE
Skip To behaviour on Popups

### ISSUE THREAD

**Issue by adj9** [joomla/joomla-cms#30691]
I briefly introduce the Skip To which is not very well known. it is a pop-up menu to use Joomla from the keyboard and get access to the area of interest faster. Entering the administrative area
1. Click tab 
2. Click the down arrow
<img width="303" alt="1" src="https://user-images.githubusercontent.com/5918444/93670439-b2829a80-fa9b-11ea-96b9-ac025bfa142c.png">

This menu appears at the top left

### Steps to reproduce the issue
In a PopUp, for example, to insert the image, you need to double click the tab button.

<img width="1181" alt="2" src="https://user-images.githubusercontent.com/5918444/93670552-78fe5f00-fa9c-11ea-95b0-9fd9f2258d8c.png">

### Expected result
I expect that it is not necessary to type the tab button twice to go to the second step.

### Actual result
In a PopUp, you need to double click the tab button.

**Comment by richard67** [comment]
@brianteeman Could you have a look on this issue as you are very familiar with the Skip To thing? Thanks in advance.

**Comment by brianteeman** [comment]
The main problem is that we are NOT using real modals but are instead loading an iframe and as a result loading everything again

**Comment by richard67** [comment]
Is there any way to fix it without changing from iframes to real modals (what I expect to happen with version 5 maybe ;-) )?

**Comment by brianteeman** [comment]
Not as far as I am aware. This is a longstanding architectural problem which no one has ever been interested in fixing. Finally now that people can SEE the issue they are waking up to the fact that using the iframe is wrong

**Comment by PhilETaylor** [comment]
Also you can see the Skip To Menu on mobile by pulling down... unexpected.

![Screen Recording 2020-10-06 at 10 55 02 pm](https://user-images.githubusercontent.com/400092/95264334-0bd22400-0827-11eb-9ad9-bfe1dee45c92.gif)

**Comment by brianteeman** [comment]
@Fedik is there perhaps something we can do with webassetsmanager here. The problem is that the modal is an iframe of the component.php in the template and this loads a full set of assets

I'm wondering if there is a way to unset an asset on the component.php page

This problem is not just for the skipto plugin but some other system plugins as well

**Comment by Fedik** [comment]
> I'm wondering if there is a way to unset an asset on the component.php page

yes sure, If the asset was loaded before template file (before rendering of component.php):
```php
if ($wa->assetExists('script', 'blabla'))
{
  $wa->disableScript('blabla');
}
```

**Comment by brianteeman** [comment]
this has been resolved

**Comment by Quy** [comment]
PR #31863

**Comment by ghost** [comment]
@richard67 here you see again, why reminders for you maintainers and members of bug squad team are necessary (https://github.com/joomla/joomla-cms/pull/32006#issuecomment-766612591.

**Comment by alikon** [comment]
Dear @gostn,
most of maintainers and members of bug squad team if not all, are volunteers, and they do their best in their free time, if you think that you can do it better and/or have more free time , then please step up and ask to join a team

**Comment by ghost** [comment]
> Please stop to tell us maintainers and JBS members what we shall do. We know it by ourselves.

Joomla means ´All together´, not ´You have to be a member of team´.
