### ISSUE TITLE
Unable to gain access to front end site in off line mode

### ISSUE THREAD

**Issue by R-R-M** [joomla/joomla-cms#30698]
### Steps to reproduce the issue
I have installed a clean copy of Joomla 4 beta 4
Using PHP 7.4
Mac Safari web browser, don't think the issue is limited to this browser.
Website set to offline mode.
Session Lifetime set to 15 minutes.

I left the site alone for longer than 15 minutes and clicked to view the front end, I then get the message (session time expired so continue to log back in) I then get another message (Warning
The security token did not match. The request was aborted to prevent any security breach. Please try again.)
I can currently login and out of the back end but not able to login to the front end. This has happened twice on two different test sites

**Comment by R-R-M** [comment]
I would be interested to know if anybody else's experience this. This issue still remains on my site so tried to use Akeeba admin tools to purge all logged in users. But Akeeba admin was unable to purge users. I have reported this to Akeeba, the related issues might be due to the same problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30698">issues.joomla.org/tracker/joomla-cms/30698</a>.</sub>

**Comment by ghost** [comment]
Can't confirm. After session time out in Backend can login by frontend.

### System information

php: Linux lamp120.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 #1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
dbserver: mysql
dbversion: 5.7.30-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.3.21
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.0.0-beta5-dev Development [ Mañana ] 15-September-2020 19:15 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

**Comment by alikon** [comment]
unable to confirm too
PHP                             Linux php 4.19.76-linuxkit #1 SMP Tue May 26 11:42:35 UTC 2020 x86_64
Database Type	                mysql
Database Version	        8.0.21
Database Collation	        utf8mb4_0900_ai_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	Yes
PHP Version	                7.4.10
Web Server	                Apache/2.4.46 (Unix) OpenSSL/1.1.1d
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 4.0.0-beta5-dev+pr.30717 Development [ Mañana ] 15-September-2020 19:15 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.102 Safari/537.36

**Comment by R-R-M** [comment]
Interesting... Thanks for the feedback, it's a basic clean setup so wasn't expecting any issues so early on. No external plugins when this first started. Will try a new user account.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30698">issues.joomla.org/tracker/joomla-cms/30698</a>.</sub>

**Comment by R-R-M** [comment]
OK so your feedback lead me to think this is not a bug and have pursued other avenues. Foolishly I have not updated the template login page. The issue with Akeeba admin tools not purging still exists but will take that up with them.

THIS REPORT CAN BE DELETED!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30698">issues.joomla.org/tracker/joomla-cms/30698</a>.</sub>

**Comment by alikon** [comment]
ok closing
