### ISSUE TITLE
j4 beta 5 JLIB_JS_AJAX_ERROR_OTHER

### ISSUE THREAD

**Issue by no-matter-0** [joomla/joomla-cms#30709]
### Steps to reproduce the issue
install J4 beta 5

### Actual result
error JLIB_JS_AJAX_ERROR_OTHER

### System information (as much as possible)
MAMP 5.7 on MAC

###

Impossible to install Joomla 4 beta 5

**Comment by alikon** [comment]
please report if some more explicative info from the browser console

**Comment by brianteeman** [comment]
This should be closed as there is not enough information to even attempt to replicate

**Comment by PhilETaylor** [comment]
apparently I replicated it and duplicated an issue - sorry - here: https://github.com/joomla/joomla-cms/issues/30896
