### ISSUE TITLE
[4.0] Category Blog Layouts Wonky

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#30700]
### Steps to reproduce the issue
See attached screen shot.

### Actual result
Note the Link to Articles are horizontal, clumped together. They should appear as a vertical list of links, Yes?

When going to the 2 page, or next - the layout regurgitates the initial layout setup. Is that what it is intended to be, replicating the class layouts set for the main screen of the Menu Link Item?

### System information (as much as possible)

Latest Beta5 nightly.![screen shot 2020-09-20 at 14 01 23](https://issues.joomla.org/uploads/1/c9afdba6b318fbab06632887b5616634.jpg)

**Comment by chmst** [comment]
Confirmed.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30700">issues.joomla.org/tracker/joomla-cms/30700</a>.</sub>

**Comment by chmst** [comment]
Pleas test the #30788. It resolves the issue that links are in a line and not separated.

**Comment by gostn** [comment]
> When going to the 2 page, or next - the layout regurgitates the initial layout setup. Is that what it is intended to be, replicating the class layouts set for the main screen of the Menu Link Item?

There should be a different layout between first and following pages in blog-view. Example: 
- first page "1 article full width, next 2 articles in 2 columns"
- all other pages 2 columns.

**Comment by chmst** [comment]
Can you confirm that your first issue with the links is solved by PR #30788?

Then we can work on your second issue. In general it is better to open one tracker item for one issue.

**Comment by brianteeman** [comment]
> When going to the 2 page, or next - the layout regurgitates the initial layout setup. Is that what it is intended to be, replicating the class layouts set for the main screen of the Menu Link Item?

Assuming I understand you correctly then it has always been the case that the layout on page 2 etc is the same as page 1

So if you set
Leading 1, columns 2, links 4 then its the same on all the pages from that menu link

**Comment by ghost** [comment]
Confirm solved issue "links":

> ![image](https://user-images.githubusercontent.com/78906980/116224303-cc324180-a750-11eb-9203-c7386c50dad0.png)



@chmst 

> Then we can work on your second issue. In general it is better to open one tracker item for one issue.

I can open an new issue for part 2 if you wan't.

**Comment by brianteeman** [comment]
yes please open a new issue for part 2 and close this one

**Comment by ghost** [comment]
Issue for part 2 #33739, so someone can close now this issue for solved part 1 (Link to Articles horizontal).
