### ISSUE TITLE
[4.0.0b4] Updates Are Available is aggressively cached.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30702]
### Steps to reproduce the issue

Install old Akeeba Backup for Joomla 4
Note that the update checks on the Home Dashboard page of Joomla 4.0.0 beta 4 is red and says one update is available.
Click the red box
Apply the Akeeba Backup update successfully
Revisit the Home Dashboard page 
Note its still reporting 1 update and is still red
Click the red box
Note "There are no updates available at the moment. Please check again later."
Click "Clear Cache" button
Return to Home Dashboard
Note its still reporting 1 update and is still red

### Expected result

After applying an update the cache of the quick icon is cleared
After clicking clear cache in com_installer&view=update that the cache of the quick icon is cleared

### Actual result

as detailed above
<img width="658" alt="Screenshot 2020-09-20 at 15 33 36" src="https://user-images.githubusercontent.com/400092/93713904-dce55e00-fb56-11ea-98ff-2508a5ec0b36.png">

I found no GUI way of clearing the cache for the quick icon. 

### System information (as much as possible)

Joomla 4.0.0 beta 4 on a standard cPanel account

**Comment by infograf768** [comment]
I do not have this issue in for a language pack.
But I had to first Clear Cache in the update page to see the language update as it was set to 6 hours per default in the Options.

**Comment by brianteeman** [comment]
Shouldnt the cache be cleared after an update?

**Comment by PhilETaylor** [comment]
The expectation is that after an extension is installed, that the quick icon shows accurate information. Ie. that the action of installing an update automatically clears the quick icon cache. 

However, as explained, even if I clear the update cache manually, the quick icon cache remains unaffected and still shows that updates are available. 

I have been able to replicate this on many Joomla 4 sites with the latest Akeeba update.

**Comment by ahotzler** [comment]
If I update 20 different Joomla! 3 installations at once, in tabs in the same browser, then after the update all Joomla! pages continue to show me an - already installed - update. Have now resigned myself to it.

**Comment by PhilETaylor** [comment]
Cannot replicate today

**Comment by altrasoluzione** [comment]
Hi, I'm still having the updates issue. Are there any news about this problem?

I've updated the 8 extensions and cleaned cache but Control Panel keeps showing me (and to the Customer too!) that there are pending updates.

Thank you very much!

![image](https://user-images.githubusercontent.com/22329855/166954829-11203fe2-71a3-4eec-961d-24b3a5609519.png)
