### ISSUE TITLE
Non-uniform Tags field width

### ISSUE THREAD

**Issue by rx112358** [joomla/joomla-cms#30706]
### Steps to reproduce the issue
1. Create a new article in the site, 4.0 beta version.
2. Go to category.
3. Check the width of the tags field.

### Expected result
The width of the tags field is same as the other fields.

### Actual result
The width of the tags field is not the same.
![image](https://user-images.githubusercontent.com/53977169/93736309-f935d900-fbf0-11ea-9d31-bb1c515c6faa.png)

### System information (as much as possible)
Win 10, Firefox browser

**Comment by ghost** [comment]
duplicate report #27907
