### ISSUE TITLE
[4.0b4] Category has x layout issues

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30703]
### Steps to reproduce the issue

Login to frontend of Joomla 4.0.0b4 as super admin 
Edit any article
Select the publishing Tab
Note the dropdown for Category
Note the X next to the arrows down selector - far too close

### Expected result

X to be somewhere else and not so close to the dropdown

### Actual result

<img width="848" alt="Screenshot 2020-09-20 at 15 41 18" src="https://user-images.githubusercontent.com/400092/93714038-becc2d80-fb57-11ea-91fe-929657eca794.png">

### System information (as much as possible)

Safari on Mac 
<img width="372" alt="Screenshot 2020-09-20 at 15 41 10" src="https://user-images.githubusercontent.com/400092/93714035-b83db600-fb57-11ea-93be-7284c9afa752.png">

**Comment by infograf768** [comment]
Macintosh, whatever the browser, I confirm.

**Comment by infograf768** [comment]
this is due to this css 
```
.choices__button_joomla::before {
    position: absolute;
    top: 0;
    right: 0;
    bottom: 0;
    left: 0;
    display: block;
    text-align: center;
    text-indent: 0;
    content: "\00d7";
}
```
If I correct with
```
.choices__button_joomla::before {
    position: absolute;
    top: 0;
    right: 2rem;
    bottom: 0;
    left: auto;
    display: block;
    text-align: center;
    text-indent: 0;
    content: "\00d7";
}
```
it displays fine
(Evidently for RTL it would be the opposite)

<img width="876" alt="Screen Shot 2020-09-20 at 18 48 12" src="https://user-images.githubusercontent.com/869724/93716793-e4fec700-fb71-11ea-8fab-35c30fe2e556.png">


Will look if no unwanted consequence and make PR if not.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/30710
Change is a bit different from proposed above as it was concerning `choices[data-type*="select-one"]`

Closing as we have a patch.
