### ISSUE TITLE
[4.0] Atum Template JS - untranslated string

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#30708]
### Steps to reproduce the issue

https://github.com/joomla/joomla-cms/blob/44d1794fab4f350d6569861c399149bff230f0f8/build/media_source/templates/atum/js/template.es6.js#L137

`More Elements` should be translated?

**Comment by brianteeman** [comment]
Any  idea where/if this is displayed?

**Comment by infograf768** [comment]
It is displayed when window is reduced and we have an ellipsis to dropdown the elements that don't fit anymore in Header.

![Screen Shot 2020-09-21 at 10 20 39](https://user-images.githubusercontent.com/869724/93745654-2d5ec900-fbf4-11ea-94e7-839ed81651e0.png)

So, yes, it should be a constant and translated, in the whole template.

**Comment by infograf768** [comment]
something like
`headerMoreBtn.setAttribute('title', Joomla.Text._('JGLOBAL_MORE_ELEMENTS'));`

create the string
and then add `Text::script('JGLOBAL_MORE_ELEMENTS');` in index.php I guess.

**Comment by brianteeman** [comment]
Thanks @infograf768 I will make a PR - I just couldnt see it in action

**Comment by C-Lodder** [comment]
Closing for https://github.com/joomla/joomla-cms/pull/30720
