### ISSUE TITLE
404 Error page redirect

### ISSUE THREAD

**Issue by rx112358** [joomla/joomla-cms#30705]
### Steps to reproduce the issue

Enter a random user name and password to a newly created site 4.0 beta version, without creating a user account.

### Expected result
Error on the home page is displayed with a message to indicate that either user name or password is incorrect or account has not been created.

### Actual result
Redirect to 404 error page with the message,

Not Found

The requested URL /component/users/login.html was not found on this server.

### System information (as much as possible)

Win10 , Firefox browser

**Comment by ReLater** [comment]
Confirmed (when "Use URL Rewriting" is active).

Updated nightly 4 of today. PHP 7.4.

**Comment by SharkyKZ** [comment]
Maybe forgot to rename `htaccess.txt` to `.htaccess`?

**Comment by ReLater** [comment]
> Maybe forgot to rename htaccess.txt to .htaccess?

Not forgotten in my case.

**Comment by ReLater** [comment]
I can't reproduce the issue anymore with current nightly (updated several times since last test).

**Comment by brianteeman** [comment]
Should be closed as not reproducible
