### ISSUE TITLE
[j4] Color field in subform ux problem

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#30711]
### Steps to reproduce the issue
create a color field in subform
set color
popup selecteur is under row
![2020-09-21_09h53_50](https://user-images.githubusercontent.com/2539440/93743458-6137ef80-fbf0-11ea-8f2d-f23fbda99020.png)

**Comment by micker** [comment]
and maybe we can have a smaller imput ?
![image](https://user-images.githubusercontent.com/2539440/93743674-bbd14b80-fbf0-11ea-8142-763e9d5f88d3.png)

**Comment by Quy** [comment]
Please test PR #32422
