### ISSUE TITLE
[4.0] Icons missing in debug

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#30719]
### Steps to reproduce the issue

Go to System > Global configuration > System
Activate Debug System, Save & Close
Go to Articles
Open up the Console by clicking the Joomla! Logo on the bottom left corner (if not already opened)
Go to Queries

![debug](https://user-images.githubusercontent.com/368084/93778172-7013a780-fbda-11ea-8c8c-b55c349d2075.png)

### System information (as much as possible)
In Chrome, icons are not visible, but in Firefox, shown as missing icons.

**Comment by brianteeman** [comment]
Confirmed

**Comment by Quy** [comment]
PR #30749
