### ISSUE TITLE
[j4] accesibility link in backend is the same of editor

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#30718]
Hello
link to acessibility option = user profil 
![2020-09-21_15h22_54](https://user-images.githubusercontent.com/2539440/93772193-d4585a80-fc1e-11ea-8b78-47490c81ef0e.png)
but no option ... on profil 
bug ?

**Comment by ghost** [comment]
duplicate report of #30217

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/29226.

**Comment by micker** [comment]
sorry !
