### ISSUE TITLE
[4.0] [Cassiopea] overwrited  bootstrap `.table-sm` class

### ISSUE THREAD

**Issue by bato3** [joomla/joomla-cms#30715]
### What needs to be fixed
Boostrtap calss `.table-sm` introduce condensed table layout.

`cassiopea/scss/vendor/bootstrap/_table.scss` overwrites it by definition
```scss
.table {
  th,
  td {
    padding: 8px;
```

### Why this should be fixed
Because it overwrite `$table-cell-padding` and `$table-cell-padding-sm` variables

### How would you fix it
Remove `padding: 8px;` and use instead  `$table-cell-padding`, `$table-cell-padding-sm` variables

### Side Effects expected

None

**Comment by richard67** [comment]
Closing as having a pull request. Please test #30740 .
