### ISSUE TITLE
[4.0] Edit profile on frontend, cancel button reloads page

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30722]
### Steps to reproduce the issue
Create an edit profile menu item

### Expected result
When you Press save or Cancel the user is redirected somewhere (perhaps the view profile)

### Actual result
When you Press save or Cancel the edit profile page is reloaded

### Additional comments
This was first reported by @PhilETaylor #20485 and supposedly fixed but it is still present.

The same issue is present in J3 but it definitely did not happen earlier in the life of J3

**Comment by brianteeman** [comment]
It is only fixed in J4 if a view profile menu exists - that "fix" doesnt work in J3 :(

**Comment by ghost** [comment]
related #29313

**Comment by brianteeman** [comment]
closing as a duplicate
