### ISSUE TITLE
[4.0] `Send Private Message` give wrong Error

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#30726]
### Steps to reproduce the issue
- login as Member of `Administrator`-Group
- answer a Message from a `Super User` by click on `Send`
- get 2 Warnings:
![Screen Shot 2020-09-22 at 08 39 59](https://user-images.githubusercontent.com/70466955/93851839-2ba70b00-fcb1-11ea-963d-1b5d87434b29.png) 
**but**:
- `Super User` got Message

### Expected result
Send private Message without Warning.

### System information (as much as possible)
php: Linux lamp120.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.7.el6h.x86_64 #1 SMP Mon Dec 17 12:02:35 EST 2018 x86_64
dbserver: mysql
dbversion: 5.7.30-cll-lve
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 7.3.21
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.0.0-beta5-dev Development [ Mañana ] 15-September-2020 19:15 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.13; rv:80.0) Gecko/20100101 Firefox/80.0

**Comment by richard67** [comment]
The "Send Test Mail" at the bottom of "Global Configuration - Server" works?

I ask because the "Could not start mail function" normally is shown when the mailer can't be started, e.g. because the local malining system hasn't been set up right.

**Comment by ghost** [comment]
> The "Send Test Mail" at the bottom of "Global Configuration - Server" works?

Yes.

**Comment by alikon** [comment]
unable to reproduce

**Comment by ghost** [comment]
> unable to reproduce

do you send only one message or more?

**Comment by infograf768** [comment]
Can't reproduce either. Sent only one message.

**Comment by ghost** [comment]
Both Messages came on second private Message (Answer) for first time.

**Comment by ghost** [comment]
Closing as Issue didn't happen again now.
