### ISSUE TITLE
Accessibility functionality when inverting colours

### ISSUE THREAD

**Issue by R-R-M** [joomla/joomla-cms#30723]
### Steps to reproduce the issue
Switch on accessibility
Choose invert colours
Choose text to speech

When the user clicks to read aloud a block of text there is no visual aid to show what is being read out

### Expected result
A dashed border in white would fix this there is a great demo of this here: https://www.equalweb.com

### Actual result
Dark background with no reference to anything

### System information (as much as possible)
Joomla 4 beta 4

**Comment by ghost** [comment]
duplicate report of #30598

**Comment by chmst** [comment]
close duplicate
