### ISSUE TITLE
Installer should stop me from moving to Setup Database Connection if password requirement is not met.

### ISSUE THREAD

**Issue by simmonsr** [joomla/joomla-cms#30721]
### Steps to reproduce the issue
Install Joomla and enter username / password with less than 12 characters and select Setup Database Connection.

### Expected result
Instead of allowing me to move to Database Connection, I should be prompted to correct my password.

### Actual result
It moves on to Database Connection options. At which point I don't get prompted about correcting password until later in installation

### System information (as much as possible)
Joomla 4 beta 4.
PHP 7.2

**Comment by Quy** [comment]
Duplicate #30406
