### ISSUE TITLE
"URL invalid" is not translatable

### ISSUE THREAD

**Issue by jaimestuardo** [joomla/joomla-cms#30732]
### Steps to reproduce the issue

- SEF enabled

- Load a page: https://www.example.com/anytext.html

### Expected result

Message according to language, for example, "404 URL inválida".

### Actual result

"404 URL invalid"

### System information (as much as possible)

Joomla 3.9.21

### Additional comments

By searching for "URL invalid" in Joomla files, I found only one reference, line 238 of \libraries\src\Router\Router.php

    `throw new RouteNotFoundException('URL invalid');`

That text is not translatable. I tried by adding the line URL invalid="URL inválida" in es-ES.ini file but no avail.

Notice that this happens only in route problem because the URL ends with html. If I write, for example, https://www.example.com/sfsfsdg the error shown is JERROR_PAGE_NOT_FOUND which is translatable.

**Comment by infograf768** [comment]
Confirmed. Making patch.

**Comment by brianteeman** [comment]
@infograf768 errors in library files are not usually translatable

**Comment by infograf768** [comment]
Same file has
https://github.com/joomla/joomla-cms/blob/11ec5292d3e9a89e363b163808dd054e6bc2baf9/libraries/src/Router/Router.php#L193

**Comment by brianteeman** [comment]
OK. I didnt see that one I just saw all the other non-translated strings

**Comment by brianteeman** [comment]
@infograf768 did you forget to make the patch?

**Comment by infograf768** [comment]
On my list.

**Comment by brianteeman** [comment]
long list?

**Comment by brianteeman** [comment]
Must be a very long list

**Comment by brianteeman** [comment]
Gave up waiting - please test #31486
