### ISSUE TITLE
[4.0][plg_actionlogs] self activate account

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#30735]
### Steps to reproduce the issue
see here please: https://issues.joomla.org/tracker/joomla-cms/30725
Testing Instructions

Turn on the registration on the site and the Self value for parameter New User Account Activation.
Register on the site with a real email address. Follow all instructions to activate your account.
Go to the User Actions Log section and pay attention to the lines.
### Actual result
![screen shot 2020-09-22 at 21 00 57](https://issues.joomla.org/uploads/1/24d9efe3017d7f476aced899a46ff18c.jpg)

### System information (as much as possible)
Joomla! 4.0.0-beta5-dev Development [ Mañana ] 15-September-2020 19:15 GMT

### Additional comments
maybe missing apprx. line 49 in /administrator/language/en-GB/en-GB.plg_actionlog_joomla.ini similar to: https://github.com/joomla/joomla-cms/commit/fe0501a349242e7be8d6d45397a1021261cc0ed8
and:
and here to add apprx. 7 lines: 637-643 in /plugins/actionlog/joomla/joomla.php
similar to: https://github.com/joomla/joomla-cms/commit/547fef76143ebb81aabbe53482e0f85632c62eb7

**Comment by richard67** [comment]
@ChristineWk I am confused. We have PR #30725 which solves the issue with duplicate action log entries for 3.9. When that will be merged into staging, it will after that sooner or later be also merged up into 3.10-dev and 4.0-dev. What do you want to achieve with this issue here?

**Comment by ChristineWk** [comment]
> 
> @ChristineWk I am confused. We have PR #30725 which solves the issue with duplicate action log entries for 3.9. When that will be merged into staging, it will after that sooner or later be also merged up into 3.10-dev and 4.0-dev. 

sorry, I didn't know that. Will close. Be patient. Thank you.

**Comment by Harmageddon** [comment]
> What do you want to achieve with this issue here?

@richard67 I wasn't aware either of the fact that all bugfixes for 3.x will eventually be merged into 4.x (although it makes sense when thinking about it). For issues we fix in 4.x, we create separate backport PRs for 3.x. So it's not obvious to everyone why this shouldn't hold the other way round - and if it's not obvious to me as a developer, it is sure not obvious to non-developer users. 
Not advocating to reopen here or anything, I was just a bit irritated by the harshness in your comment.

**Comment by richard67** [comment]
@Harmageddon @ChristineWk Sorry, wasn't meant to be harsh. Honestly sorry if it sounded so.

Sometimes we make a separate issue for J4 as a reminder when there is one for staging which will be merged up in future.

But we use clear description for that in the PR, e.g. a reference to that PR.

But the description here was so unclear to me that it took me a while to get what was the issue.

**Comment by ChristineWk** [comment]
> 
> 
> @Harmageddon @ChristineWk Sorry, wasn't meant to be harsh. Honestly sorry if it sounded so.
> 
OK ...
 
> But the description here was so unclear to me that it took me a while to get what was the issue.

Thats' why I also was searching & checking the (I think so) relevant lines before making this Issue. 
Different lines between Joomla 3 and 4. See: Additional comments above. 

@ Harmageddon: Thanks for your investigation.

**Comment by richard67** [comment]
@ChristineWk It would have been sufficient to refer to the J3 PR, like you did, and then just write "This issue is a reminder that we need the same change in J4".
