### ISSUE TITLE
[4.0] Global check-in does not clear check_out=0

### ISSUE THREAD

**Issue by mahagr** [joomla/joomla-cms#30731]
### Steps to reproduce the issue

- Run SQL command: `UPDATE #__menus SET checked_out=0 WHERE client_id=0`
- Click on System > Maintenance > Global Check-in

### Expected result

You should be able to check-in menu items.

### Actual result

> There are no tables with checked out items or there are no tables with checked out items that match your search.

You can restore your DB by: `UPDATE #__menus SET checked_out=DEFAULT WHERE client_id=0`

### System information (as much as possible)

Joomla 4.0.0-beta4

### Additional comments

If any of the tables, say `#__menu`, contains items saved with older Joomla 3.9 component, they may have items with `check_out` being 0. Unfortunately, a few Joomla models only check against user_id and NULL, meaning that the items may/will be semi-locked forever with no way to update them.

`administrator/components/com_checkin/src/Model/CheckinModel.php` should be changed to check against something else than >=0. In fact, I don't think that WHERE clause is needed at all.

**Comment by richard67** [comment]
@SharkyKZ Could you have a look on this issue?

**Comment by SharkyKZ** [comment]
We can check if checked_out column is nullable like we do with the date.

**Comment by richard67** [comment]
> We can check if checked_out column is nullable like we do with the date.

Sounds good. Do you wanna make a PR?

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30747.
