### ISSUE TITLE
[4.0] Smart search module suggestions, below the search button

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#30745]
### Steps to reproduce the issue
In the smart search module enable both the suggestions and the search button.

### Expected result
The suggestions to go above the button, since their drop-down is closing once we select one

### Actual result
Below the button.

![Screenshot_smart_search](https://user-images.githubusercontent.com/1838041/94008295-73aa5880-fdab-11ea-8033-2cce3cffe8a5.png)

### System information (as much as possible)

4.0.0 beta5-dev

**Comment by hans2103** [comment]
I have tested this on 7047a4e8dca7501a91fe9de0a95daab33e71f522 and cannot reproduce

<img width="1015" alt="Schermafbeelding 2020-09-24 om 12 53 19" src="https://user-images.githubusercontent.com/639822/94136252-f2af9780-fe64-11ea-82b0-e610948af0ab.png">

**Comment by ghost** [comment]
Issue confirmed:
![Screen Shot 2020-09-24 at 13 06 26](https://user-images.githubusercontent.com/70466955/94137524-d0b71480-fe66-11ea-9350-d08aa4bc484d.png)

**Comment by chmst** [comment]
Issue confirmed: win10, firefox, surface laptop, 
![grafik](https://user-images.githubusercontent.com/1035262/94140922-4ffb1700-fe6c-11ea-999e-477ec7d9ba72.png)

**Comment by HLeithner** [comment]
closed because of PR #31827
