### ISSUE TITLE
[4.0] Smart search module suggestion selection with keyboard

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#30744]
### Steps to reproduce the issue
Enable "suggestions" from the smart search module and try to select one with the keyboard.

### Expected result
Selection

### Actual result
No selection
![Profile-20200923T143853](https://user-images.githubusercontent.com/1838041/94007899-c7687200-fdaa-11ea-8a1d-ec6357004189.gif)

### System information (as much as possible)

4.0.0-beta5-dev

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32798 . Thanks in advance.
