### ISSUE TITLE
[4.0] Correct some spelling mistakes in comments

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#30741]
### Problem identified
I was looking at PR #30724 where "Dummymethod" has been corrected to "Dummy method" but I noticed that "fullfill" in the same line is incorrect. It should either be "fulfil" (English UK) or "fulfill" (English US).

Additionally, in the Joomla copyright information the word "License" has the US spelling. I was under the impression that Joomla was using UK English for its spelling, so "License" should be "Licence".

This applies to both front and back ends.

### Proposed solution
1. Change "fullfill" to "fulfil" wherever it occurs
2. Change "License" to "License" wherever it occurs

**Comment by brianteeman** [comment]
oops my mistake on fulfil I will fix that now
I dont want to correct the spelling of License as there are external software tools that all assume the american spelling

**Comment by richard67** [comment]
Closing as having a pull request for the `fulfil` change. Please test #30742 .

For the `License` spelling see the comment above for the reasons not to change.

**Comment by richard67** [comment]
@Scrabble96 Additional info: Of course there are much more occurrences of `fulfill` than fixed by PR #30742 on an installation, but all these belong to external libraries, and in J4 we don't have them in our sources, so the PR covers all we can do.

**Comment by Scrabble96** [comment]
Thank you both @brianteeman and @richard67
