### ISSUE TITLE
[4.0] Contact: Keep link-label and -url together

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#30752]
### What needs to be fixed
- open `/index.php?option=com_contact&view=contact&layout=edit`
- click tab `Display`
- Label and Url of `B` and `D` shown in different columns:
![Screenshot_2020-09-24 Contacts New - 424 - Administration](https://user-images.githubusercontent.com/70466955/94107095-10690680-fe3d-11ea-85cc-fb9455121bbf.png)

### Why this should be fixed
better UX

### How would you fix it
fix like #30020 or keep label and url together.

### Side Effects expected
don't know.

**Comment by richard67** [comment]
Related pull request: #29706 . If that will be accepted, this here will not be an issue anymore. If not, we have to find another way to solve it.

**Comment by richard67** [comment]
@Formatio-hippocampi Or am I wrong with my previous comment and this issue here is about frontend editing?

**Comment by ghost** [comment]
You're right, issue is about backend.

**Comment by Quy** [comment]
Fixed in PR #32422. Thanks for reporting.
