### ISSUE TITLE
[4.0] Problem with User Permissions

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#30757]
### Steps to reproduce the issue
Create a new User Group and create a User, assign into the group.
Set "permissions" for the Group and set EDIT STATE to "not allowed."  
Both EDIT and EDIT OWN should be allowed.
Log into Back-End as the user, not the Super User - assuming Back-End access was allowed in permissions.
After creating an Article, the user cannot edit the State/Status of their own Content Item.
The Status option is also not changeable by the User in the Article Workspace.
Alternatively, if the "permission" for EDIT STATE is set to "Allowed," the User in the Group not only can change the Status of their own Content Item, but can change the State/Status of ALL others.  This is problematic in that the "permissions" should be limited to "their own" Content Items, and not that created by others. Thus the resulting possible EDIT STATE action is not consistent with the ACL setting to force the user to only be able to change "their own" content settings, and under no circumstances, any created by others.

### Expected result
User should be able to change only the Status of "own" Content, and not of any others not within the same Group.

### Actual result
User in Group can change ALL Status settings of ALL OTHER content if EDIT STATE is Allowed.

### System information (as much as possible)

Latest Joomla! 4 build on Linux Server, WHM/cPanel, MySQL database.

### Additional comments

Within the "Permissions" terminology, should "Change State" not be "Change Status" to be consistent with the naming convention of the settings within Content items with respect to their published/unpublished option?

**Comment by SharkyKZ** [comment]
Is this different from J3?

**Comment by brianteeman** [comment]
@200MPHMEDIA Please can you respond to the question from @SharkyKZ

**Comment by brianteeman** [comment]
After 1 month without response this really should be closed
