### ISSUE TITLE
Frontend com_menus list of items is missing menutype filter

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#30753]
### Steps to reproduce the issue

Edit article in frontend, click Menu editor button

### Expected result

See the list of menu items with menutype (Menu) filter

### Actual result

There is no menutype filter, compare the modal output when you edit article in backend

The issues is that frontend filter_items.xml form is missing "menutype" field and frontend is missing joomla.searchtools.default layout override

**Comment by richard67** [comment]
I'm not sure, but it could be desired behavior, e.g. for security reasons, that one can edit only that menu. But that's just a guess. Let's wait for feedback of people who know this better than I do.

**Comment by Denitz** [comment]
No, the items from all menus can be visible, the menutype filter is completely logic here.

**Comment by richard67** [comment]
I see, and for Joomla 4 it is already fixed with #30087 .

@Denitz Which version is your issue referring to? I assume current 3.9.21. Is that right?

**Comment by Denitz** [comment]
@richard67 Yes, exactly, 3.9.21

**Comment by richard67** [comment]
@infograf768 Do you think we (preferrably you 😄 ) could back-port #30087 to 3.x? Or was there a reason why it was made only in 4.0-dev?

**Comment by infograf768** [comment]
Do you mean we should get in frontend
<img width="973" alt="Screen Shot 2020-09-24 at 10 42 04" src="https://user-images.githubusercontent.com/869724/94122368-c0953a00-fe52-11ea-8580-989c7b1941b2.png">

If yes, PR is simple. Can do. Does not even need css tweaks.

**Comment by richard67** [comment]
Looks good. @Denitz I guess that would solve your issue?

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/30755

Please test.
