### ISSUE TITLE
[4.0] Show a message after a logout

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#30767]
### Steps to reproduce the issue

Improve proposal: new feature.

### Expected result

There is showing a message after a logout. (Optional)

![screen shot 2020-09-25 at 12 43 12](https://issues.joomla.org/uploads/1/8824289acbedb453468ea389b32a1a6a.png)

### Actual result

There is NOT showing a message after logout.

### System information (as much as possible)

Is not applicable.

### Additional comments

Earlier I wanted to introduce this in Joomla 3.x.
Apparently there was no need for that.
See #19477.

I want to re-evaluate this new feature for J4. @Quy.

**Comment by sandewt** [comment]
The easiest way is to add a small piece of code to the system plugin logout.
But I don't know if that's allowed !?
In any case, it seems to work fine.

\plugins\system\logout\logout.php

```
public function onUserLogout($user, $options = array())
{
	if ($this->app->isClient('site'))
	{
		// Create the cookie.
		// .....

		// Get a message after logout.
		if ((int) $this->params->get('show_message', 1)) // option
		{
			$this->app->enqueueMessage(Text::_('PLG_SYSTEM_LOGOUT_MESSAGE'), 'message');
		}
	}

	return true;
}
```

**Comment by adj9** [comment]
The login message may be useful. I would also set a login message.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30767">issues.joomla.org/tracker/joomla-cms/30767</a>.</sub>

**Comment by sandewt** [comment]
>The login message may be useful. I would also set a login message.

But then as an option in the settings..

**Comment by infograf768** [comment]
To consider:
When logging out from a page which access was restricted to the group the user was set to, we get an error page as a 404.

**Comment by brianteeman** [comment]
enqueue message should still work

**Comment by sandewt** [comment]
For a simpler and better control structure, the `User - Joomla! plugin` seems now to be a better option.

Moreover, it is now possible to generate a `login and/or a logout message` for the `backend and frontend`.

file: \Joomla\plugins\user\joomla\joomla.php

```
public function onUserLogin($user, $options = [])
{
	....

	// Show a message when the user is actually logged in.
	if ((int) $this->params->get('message_login', 0) && Factory::getUser()->get('id') > 0)
	{
		$this->app->enqueueMessage(Text::_('PLG_USER_JOOMLA_MESSAGE_LOGIN'), 'message');
	}

	return true;
}

public function onUserLogout($user, $options = [])
{
	...

	// Show a message when the user is actually logged out.
	if ((int) $this->params->get('message_logout', 0) && Factory::getUser()->get('id') === 0)
	{
		$this->app->enqueueMessage(Text::_('PLG_USER_JOOMLA_MESSAGE_LOGOUT'), 'message');
	}

	return true;
}

```

![new_feature_messages_1](https://user-images.githubusercontent.com/9271775/94365119-a1a2dc00-00ce-11eb-82f0-9a0992b5d0ee.png)
![new_feature_messages_3](https://user-images.githubusercontent.com/9271775/94365193-22fa6e80-00cf-11eb-8798-419f20ad4ff0.png)
![new_feature_messages_2](https://user-images.githubusercontent.com/9271775/94365196-2b52a980-00cf-11eb-80a0-9c55edac55c7.png)

**Comment by HLeithner** [comment]
Actually I think you don't need an option for logout and the location should be in the com_users controller logout function no need to do this in the joomla user plugin.

I see no useful information in a login message but ok.

**Comment by sandewt** [comment]
>Actually I think you don't need an option for logout and the location should be in the com_users controller logout function no need to do this in the joomla user plugin.

Sounds logical, but I know more about plugins. Hence.
The changes I suggest here with built-in controls are very easy to implement.
I know that shouldn't be an argument.

> I see no useful information in a login message but ok.
> The login message may be useful. I would also set a login message.

[EDIT] Much of such logic is handled in the plugins!

**Comment by sandewt** [comment]
Question: Where are the `return true` statements handled in the (com_users) controller?

file: \Joomla\plugins\user\joomla\joomla.php
```
public function onUserLogin($user, $options = [])
{
	....	

	return true;
}

public function onUserLogout($user, $options = [])
{
	....

	return true;
}
```

**Comment by sandewt** [comment]
>Question: Where are the return true statements handled in the (com_users) controller?

In the meantime I found out that this functionality can easily be put in \components\com_users\src\Controller\UserController.php for the frontend.

Backend? Necessary?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30767">issues.joomla.org/tracker/joomla-cms/30767</a>.</sub>

**Comment by sandewt** [comment]
Placing the logic in `UserController.php` and changing `config.xml` let's see:

- Frontend Login Message (default = Hide)
- Frontend Logout Message (default = Hide)

## Users: Options
![new_feature_messages_4](https://user-images.githubusercontent.com/9271775/94422630-aecfd180-0187-11eb-889f-b818c36f05a1.png)

[EDIT] Hide should be No

**Comment by alikon** [comment]
please test #30834
