### ISSUE TITLE
Language constants missing

### ISSUE THREAD

**Issue by Luchen6** [joomla/joomla-cms#30764]
### Steps to reproduce the issue
Convert basic Joomla 3.9.21 site to 3.10.0 to 4.0.0

See Post installation messages

### Expected result
Title and description of message

### Actual result
See only language constants
PLG_PLG_RECAPTCHA_VERSION_1_POSTINSTALL_TITLE and PLG_PLG_RECAPTCHA_VERSION_1_POSTINSTALL_BODY
TPL_HATHOR_MESSAGE_POSTINSTALL_TITLE and TPL_HATHOR_MESSAGE_POSTINSTALL_BODY
COM_CPANEL_MSG_JOOMLA40_PRE_CHECKS_TITLE and COM_CPANEL_MSG_JOOMLA40_PRE_CHECKS_BODY
COM_CPANEL_MSG_HTACCESSSVG_TITLE and COM_CPANEL_MSG_HTACCESSSVG_BOD

### Additional comments
![Capture01](https://user-images.githubusercontent.com/6205641/94256731-872ffd80-ff2a-11ea-90ae-f28681884768.JPG)

**Comment by brianteeman** [comment]
Those message really should not be displayed in j4

**Comment by Quy** [comment]
Thanks for reporting. This will be handled in #28863.
