### ISSUE TITLE
No name of site

### ISSUE THREAD

**Issue by adj9** [joomla/joomla-cms#30762]
### Steps to reproduce the issue
Yesterday I opened a website with the Nightly Builds of the Day. I noticed that on the button to go to the frontend there was no text, in fact the Site Name field of the global configurations was empty. 

With the HTML inspection of the administrative panel there was no text.

### Observation
Without text, the speech function of the System - Additional Accessibility Features plugin reads nothing. This is for HTML not formatted correctly.

### Expected result
I expect a default text.

### Actual result
At the start of the site there was no text, so it was added and appears. 

### System information (as much as possible)
- Web site

**Comment by ghost** [comment]
I guess you start a J4-Site at cloudaccess.

**Comment by adj9** [comment]
Yes with Cloudaccess.
With tonight's Nightly Builds do you know if there are any changes to the name of the site?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30762">issues.joomla.org/tracker/joomla-cms/30762</a>.</sub>

**Comment by ghost** [comment]
Its an Issue of the provider, so write a ticket at cloudaccess.

**Comment by chmst** [comment]
As @Formatio-hippocampi said it is not an issue of the joomla cms.
