### ISSUE TITLE
Improvement for the Joomla 4 installer

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#30774]
### Is your feature request related to a problem? Please describe.
When you click on the "install" button, after entering the basic data (the name of the database, the login and password of the administrator), a large @Joomla logo appears and it starts to flicker.

I do not understand at what stage the installation process of my Joomla is currently. I don't see the install percentage.

![изображение](https://user-images.githubusercontent.com/3662519/94338559-f0cc0c80-fffb-11ea-893e-e611ea03dbad.png)

### Describe the solution you'd like
I propose to change this moment and make the usual progress bar with displaying the percentage of installation of Joomla 4. This would be much better than what we have now. This shimmery logo without any information is a very bad decision.

### Additional context
It might look like this:

![изображение](https://user-images.githubusercontent.com/3662519/94338579-2cff6d00-fffc-11ea-90a4-ea4aebd84e31.png)

**Comment by ReLater** [comment]
How do you measure the percentages of the installation steps in a reliable way?

**Comment by jiweigert** [comment]
> How do you measure the percentages of the installation steps in a reliable way?

In relation of already done steps to steps which are still have to be done?
I dont have a problem, when a progress bar get recalculated, because of the choices i've made and so jump over otherwise necessary steps..


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30774">issues.joomla.org/tracker/joomla-cms/30774</a>.</sub>

**Comment by brianteeman** [comment]
I assume that @sanek4life is expecting a progress bar that is updated while the sql is imported (that's what is happening at this point) and not a progress bar that is an indication of the which step they are at

**Comment by 4digitalworld** [comment]
> 
> 
> I assume that @sanek4life is expecting a progress bar that is updated while the sql is imported (that's what is happening at this point) and not a progress bar that is an indication of the which step they are at

yes, that's what I mean. I installed Joomla 4 (beta 4) on the local computer and this moment when the logo started flickering took a couple of minutes. I wanted to make sure that the installation did not hang and everything was OK, but I did not see the indicator (in percentage) how much has already been completed and how much is still left.

I didn't know if it was a local computer problem or something else because I didn't see the completion percentage.

**Comment by ReLater** [comment]
> expecting a progress bar that is updated while the sql is imported

That's what I meant, too. And how do you want to measure that reliably? Stopping at 33% for felt minutes like Windows sometimes? ;-) Or being too early at 100% and nothing happens for a minute then because the environment is slow? ;-) Left time: 5 days 12h because of a average calculation? For me the irritating effect of percantage progress bars and informations like these is the same at the end of the day.

**Comment by 4digitalworld** [comment]
> 
> 
> > expecting a progress bar that is updated while the sql is imported
> 
> That's what I meant, too. And how do you want to measure that reliably? Stopping at 33% for felt minutes like Windows sometimes? ;-) Or being too early at 100% and nothing happens for a minute then because the environment is slow? ;-) Left time: 5 days 12h because of a average calculation? For me the irritating effect of percantage progress bars and informations like these is the same at the end of the day.

The problem is that now it is not at all clear whether the installation is in progress or this is a problem with the database, because this flickering was for a couple of minutes and I wanted to restart the Joomla installation process.

For example, there is such an indicator every time the @kunena is updated.

**Comment by chmst** [comment]
When I run an installation, I see the logo for about 6 seconds. So the important question for me is: how can your installation need minutes? 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30774">issues.joomla.org/tracker/joomla-cms/30774</a>.</sub>

**Comment by 4digitalworld** [comment]
> 
> 
> When I run an installation, I see the logo for about 6 seconds. So the important question for me is: how can your installation need minutes?
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/30774](https://issues.joomla.org/tracker/joomla-cms/30774).

when everything is fine with your web server, then you see this logo for a few seconds.

I installed Joomla on my local computer and I had to wait a couple of minutes. I didn't know if the installation was in progress or if there was some problem, so this indicator is very important to understand if there is a problem during the installation of Joomla.

the user should see that everything is in order, or the speed is very slow, but the installation is still in progress. 

anyway - this flicker is the worst solution I've ever seen. I have installed a lot of software on my computer and various components on the site and have never seen a flickering logo.

always during installation, I saw a panel with percentages (or a progress bar, how much is still left before installation).

it happens that hosting or any software product can slow down the installation process (which I encountered), so it is always important to show the progress bar (with percentages). I don't understand why this was not done during the development of Joomla 4.

**Comment by chmst** [comment]
I understand your issue with the rotating logo. You want to know where exactly your process stops. 
I think, bar with percentatges are rather useless. Some products show as text what happens and I could imagine that for a futher version. 

> I don't understand why this was not done during the development of Joomla 4.

Because you were not here to help!

**Comment by 4digitalworld** [comment]
Maybe it's not even about how many percent I want to see, maybe it's even a matter of whether the installation process has stopped?

I remember how it was with one component for Joomla, when the installation process simply stopped and this **was visible on the progress bar**, which did not budge for a couple of hours. Such errors happen in web servers, and to see this, you just need a progress bar.

**Comment by Quy** [comment]
PR #29376
