### ISSUE TITLE
[4.0] [RFC] Remove Vote plugin

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30771]
As far as I can tell it currently does not work
The code is not accessible at all and would need an extensive rewrite
It is currently disabled by default. 

Let's just kill it

**Comment by HLeithner** [comment]
No way at this point but good to know that it's broken so it is a release blocker. We can move it to joomla-extensions but if have to work anyway.

**Comment by SharkyKZ** [comment]
What's the problem with it?

**Comment by sandewt** [comment]
See #30193 - [4.0] Improvement proposal Vote Plugin<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30771">issues.joomla.org/tracker/joomla-cms/30771</a>.</sub>

**Comment by adj9** [comment]
I have enabled the plugin and nothing appears on the articles. Inserting it for public articles.

**Comment by alikon** [comment]
@adj9 enabling the plugin is not enough you also need to set show for _**Voting**_ in the Articles: Options

**Comment by sandewt** [comment]
>I have enabled the plugin and nothing appears on the articles. Inserting it for public articles.

Articles: Edit > Options > Voting -> Show

If necessary, click on the title link of the relevant article.

[EDIT] Oops, it has already been answered (2 minutes before).

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30771">issues.joomla.org/tracker/joomla-cms/30771</a>.</sub>

**Comment by brianteeman** [comment]
> I have enabled the plugin 

or you could have also incorrectly just enabled the options in the article. you have to do both and magically know you have to do both. At a minimum the options in the article should not be displayed if the plugin is not enabled.

Now that you have it enabled try to vote. Hint you cant

**Comment by alikon** [comment]
cannot confirm that you cannot vote
![Screenshot from 2020-09-26 19-05-12](https://user-images.githubusercontent.com/181681/94346194-4a97fb00-002b-11eb-969a-e2c98ff9450b.png)

![Screenshot from 2020-09-26 19-06-01](https://user-images.githubusercontent.com/181681/94346208-5c799e00-002b-11eb-9020-780fa3748ec0.png)


surely it needs more care, as you already said 

> The code is not accessible at all and would need an extensive rewrite

but i wouldn't remove it from core

**Comment by micker** [comment]
The vote plugin cant be use with article schema... Google only allow to use it with product microdata...  It Can be interesting to allow to choose micro data type in item not ?

**Comment by brianteeman** [comment]
I see now that voting can only be done on the full article view and not on the blog view.

I also see that until there are some votes the paragraph with the required metadata is not displayed at all on the blog view 
![image](https://user-images.githubusercontent.com/1296369/94349380-cac65c80-003b-11eb-9af2-4e5fab68e1ae.png)
