### ISSUE TITLE
Add link to user profile from Article

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#30777]
### Is your feature request related to a problem? Please describe.
When plugin `User - Profile` is enabled, you cannot select the option in plugin `Content - Contact` for the link to to the @Joomla user's profile.

![изображение](https://user-images.githubusercontent.com/3662519/94341869-a2c40280-0015-11eb-85c2-90b175c9aae9.png)

![изображение](https://user-images.githubusercontent.com/3662519/94341818-3943f400-0015-11eb-834d-64924df2fce5.png)

### Describe the solution you'd like

I suggest adding a fourth option to the current list - Joomla `User Profile Link`.

### Additional context
Anyone can register on the site that Joomla uses. Thus, it would be logical if there was an opportunity to provide a link to the author of the article, who has a profile on the site.

**Comment by SharkyKZ** [comment]
There are no public user profile pages. Users can only see their own profile.

**Comment by ReLater** [comment]
Hm, the user profile is hidden from other users in the frontend and I think with good cause. We had already the discussion several times if user data should be displayed in the frontend and as far as I remember this idea was always refused.

**Comment by 4digitalworld** [comment]
> 
> 
> Hm, the user profile is hidden from other users in the frontend and I think with good cause. We had already the discussion several times if user data should be displayed in the frontend and as far as I remember this idea was always refused.

I think the solution would be a privacy level to display each `User Profile` field

- all site visitors
- only registered users
- only me

**Comment by 4digitalworld** [comment]
> 
> 
> There are no public user profile pages. Users can only see their own profile.

Joomla has built-in support for profiles and built-in private messaging system. This could be combined to fully display user profiles on the site and communicate between site users through private messages.

**Comment by brianteeman** [comment]
No need for that in the core

**Comment by ReLater** [comment]
All this has been discussed several times in the past... Use a community system or similiar... would be my recommendation.

**Comment by ReLater** [comment]
> I think the solution would be a privacy level to display each User Profile field
> 
>     all site visitors
>     only registered users
>     only me

As always: Waiting for a pr! It's not that easy like you describe it. You need a confirmation for nearly each field in the user profile. Not just "all or nothing". I think com_users data should stay private.

**Comment by jiweigert** [comment]
I would disagree to other comments before rejecting the idea..
Having a Users profile "overview" site, where the user or, for a default the Administrator, can provide basic information would be great and from my proffessional experience in the past, CMS-Systems like Silkroad Participant Server / Contentserver had those User-Profile frontend Profiles buildin.
It would be a good step forward to have it in the core(-plugin) and be more comparable to professional systems. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30777">issues.joomla.org/tracker/joomla-cms/30777</a>.</sub>

**Comment by brianteeman** [comment]
Maintainers - can you please make a decision on this. If its not going to be addressed (I personally dont think it should be) then it should be closed @zero-24 @HLeithner @wilsonge @rdeutz

**Comment by HLeithner** [comment]
I don't see a use case to show user accounts in frontend. If you need this we have com_contact for this. 

I'm not against a messaging system (we already have one) but I don't see an urgent need for this. (btw. that's offtopic)

A good or at least a basic comment system would be more useful. (also offtopic ;-) 

Anyway I close this for now. Could be reopened as always or create a new discussion. Or better make a proposal with a complete concept.
