### ISSUE TITLE
Rename default category "Uncategorised" as "Articles" for new installations.

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#30775]
### Is your feature request related to a problem? Please describe.
During the first installation of @Joomla, the default category `Uncategorised` is automatically created. This name `Uncategorised` looks ugly and each administrator gives a new name for this category (or deletes it and creates others).

![изображение](https://user-images.githubusercontent.com/3662519/94338758-6e444c80-fffd-11ea-8b0b-769643b2e33b.png)

### Describe the solution you'd like
I suggest renaming the default category from `Uncategorised` to `Articles` for all new Joomla installations. This title looks more friendly to new users.

![изображение](https://user-images.githubusercontent.com/3662519/94338774-8e740b80-fffd-11ea-932e-8bc6fdb6d958.png)

### Additional context
I saw that this is the name of the default category in CMS Drupal. I think it is a good idea.

**Comment by HLeithner** [comment]
Makes sense to me

**Comment by infograf768** [comment]
Then should be similar for all default components using categories.

**Comment by 4digitalworld** [comment]
> 
> 
> Then should be similar for all default components using categories.

I think it would be really more convenient. For example `Banners`, `Contacts` and `Feeds`.

**Comment by jiweigert** [comment]
I'm in favor to this too, renameing ```Uncategorized``` to something more convenient...
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30775">issues.joomla.org/tracker/joomla-cms/30775</a>.</sub>

**Comment by dgrammatiko** [comment]
> I suggest renaming the default category from `Uncategorised` to `Articles`

`Uncategorised` is the ROOT category and renaming it to `Articles` is totally misleading, at least for those who understand how Joomla is structuring the content.

My 2c

**Comment by Bakual** [comment]
I'm sorry, but "Uncategorised" is NOT the root category. It is just a default category.

**Comment by alikon** [comment]
uncategorized at least for my understanding, means exactly what it is, uncategorized ... so it's up to the site owner to put in those uncategorized items in a more categorized category, depending upon they crtiterion

**Comment by Bakual** [comment]
Technically, the item isn't uncategorized. Since a category is in fact assigned 😀
"Unspecified" would be more accurate. But "Articles" would indeed also be a nice default name.

**Comment by alikon** [comment]
discussing about sex of angels is not an important matter imho... uncategorized is like a default... you would like Unspecified instead... fine for me .... but it doesn't change too much the whole picture... you need to know what it is for,  despite a more friendly/unfriendly name
we have more important aspects to cover....

**Comment by 4digitalworld** [comment]
> 
> 
> uncategorized at least for my understanding, means exactly what it is, uncategorized ... so it's up to the site owner to put in those uncategorized items in a more categorized category, depending upon they crtiterion

I remember the time when it was possible to create an article in **Joomla 1.5**, and then the article was really **without a category**, and then a new version of **Joomla 2.5** was released and all articles "without a category" were automatically transferred to the **default category** with the name `Uncategorised`.

So yes, the title "`Articles`" would make more sense, because these are articles, not content without a category.

`Uncategorised` is a category and this name is not correct and **not user friendly**.

To be honest, I never liked the default name `Uncategorised` and I always renamed it. I think that all Joomla users have come across this. I think it would be a smarter move to make a **normal name for the default category**, because **it is a category**, because now when creating a new article we must always specify a category, we cannot create an article without specifying a category.

**Comment by brianteeman** [comment]
It has never been possible in Joomla to create an article without a category. 

It was possible in very early versions of mambo where there was something called static content

**Comment by brianteeman** [comment]
Maintainers - can you please make a decision on this. If its not going to be addressed (I personally dont think it should be) then it should be closed @zero-24 @HLeithner @wilsonge @rdeutz

**Comment by chmst** [comment]
"default category" would be a better name and could serve for every component.

**Comment by HLeithner** [comment]
I think "Uncategorised" is good enough for that use case  (getting renamed after installation). I don't think we find the perfect name that doesn't need to be renamed. Also the fact that the Article or Banner or what ever is not yet in a "correct/real" category is also expressed with this name.

If someone comes with a good proposal for all use cases (all joomla components and a good default for 3rd party extensions) we can reopen this again or create a discussion. Also a ready to go PR would make the thing easier.

So in the meantime I close this.
