### ISSUE TITLE
[4] admin ux form idea

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#30773]
Hello i find some issue about 2bor 3 column display  in joomla backend especialy when WE use subform
Css Can be a solution but maybe too hard solution
Maybe i have a flexible solution
Adding a New form élément not for display a input but a design élément to force to change Line
Like an hr or other HTML élément
with this all component creator Can manage column option in his backend
What do you think ?

**Comment by Quy** [comment]
https://github.com/joomla/joomla-cms/pull/29706#issuecomment-706742657

**Comment by Quy** [comment]
Duplicate #29241
