### ISSUE TITLE
[4.0] installation sql missing params

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30782]
On installation I expected all the params for an extension to have a value in extensions table.

While checking to see what the value for Remove IDs from URLs was I noticed that there are many options missing. Technically I suppose its not a major problem as if its not set in the db then joomla will use the default. Still it seems that something that should be fixed to me - unless I am missing something

**Comment by SharkyKZ** [comment]
Related discussion https://github.com/joomla/joomla-cms/issues/20563.
