### ISSUE TITLE
[4.0] Remove IDs from URLs

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30783]
### Steps to reproduce the issue
On a clean install the option for Remove IDs from URLs is set to off. Surely we should be defaulting to on now for joomla 4

**Comment by brianteeman** [comment]
really no one? Not even @Hackwar wants people to see his work,

**Comment by Fedik** [comment]
I thought it already like that :smile: 
I would say this really should be done, before release

**Comment by gostn** [comment]
> really no one?

4 thumbs up isn´t no one.

**Comment by Fedik** [comment]
it not about "thumbs up", but about "implement it" :wink:

**Comment by brianteeman** [comment]
Closed as I created a pr #31370
