### ISSUE TITLE
[4] Strange module selection.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#30798]
### Steps to reproduce the issue
- Maybe issue is not related to J4 core but I don't know for sure.
- Updated a J 3.9.21 stepwise to Joomla 4 (current nightly).

- Deactivate a module extension on `Extensions > Manage` where a module exists on `Site Modules` (image 000).
- Go to `Site Modules` and select some modules.
- I can select modules without issues one by one that are ordered in the list before "Newsletter".

- See images 001 to 003 for modules that are ordered after module "Newsletter".

- Green arrow: Here I clicked (select and deselect).
- Orange arrow: The wrong selection afterwards.

#### image 000

![000](https://user-images.githubusercontent.com/20780646/94471427-751fba80-01c9-11eb-8549-4fa892be9bb2.jpg)

#### image 001

![001](https://user-images.githubusercontent.com/20780646/94471578-b1531b00-01c9-11eb-8714-28173aedd59c.jpg)

#### image 002

![002](https://user-images.githubusercontent.com/20780646/94471624-c16afa80-01c9-11eb-9154-9237ac92cf16.jpg)
 002

#### image 003

![003](https://user-images.githubusercontent.com/20780646/94471668-d3e53400-01c9-11eb-9d32-145a040bcf55.jpg)

### System information (as much as possible)
System Information
Setting	Value
PHP Built On	Windows NT DELL-M6800 10.0 build 19041 (Windows 10) AMD64
Database Type	mysql
Database Version	10.4.11-MariaDB
Database Collation	utf8mb4_general_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	No
PHP Version	7.3.16
Web Server	Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.16
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 4.0.0-beta5-dev Development [ Mañana ] 15-September-2020 19:15 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36  **Edg/85.0.564.63**

**Comment by ReLater** [comment]
I have tested it now with a pure online nightly Joomla 4 and it has exactly the same issue.
- Create modules in Position "breadcrumbs" or so if you have no demo data installed.
- Create a modul "Articles Category".
- Go to "Extensions manager" and deactivate "Articles Category" extension.
- Go back to modules manager.
- Fiddle like described in previous https://github.com/joomla/joomla-cms/issues/30798#issue-710490466

![04-10-_2020_05-44-50](https://user-images.githubusercontent.com/20780646/95006516-bbc84700-0605-11eb-8e41-7dd37d5e3733.jpg)

Additional find: One can't reorder the deactivated module with Drag&Drop.

**Comment by gostn** [comment]
Issue confirmed.

Select ´popular tags´ select also ´search´. happens below disabled module, not above.

![image](https://user-images.githubusercontent.com/71960554/95009880-7e73b180-0625-11eb-9d73-e77e5b979972.png)

**Comment by Quy** [comment]
@dgrammatiko Can you please advise changes to the following code to only add the click event to rows containing a checkbox input? Thank you!

```
  class JMultiSelect {
    constructor(formElement) {
      this.tableEl = document.querySelector(formElement);

      if (this.tableEl) {
        this.boxes = [].slice.call(this.tableEl.querySelectorAll('input[type=checkbox]'));
        this.rows = [].slice.call(document.querySelectorAll('tr[class^="row"]'));
        this.checkallToggle = document.querySelector('[name="checkall-toggle"]');

        this.onCheckallToggleClick = this.onCheckallToggleClick.bind(this);
        this.onRowClick = this.onRowClick.bind(this);

        if (this.checkallToggle) {
          this.checkallToggle.addEventListener('click', this.onCheckallToggleClick);
        }

        if (this.rows.length) {
          this.rows.forEach((row) => {
            row.addEventListener('click', this.onRowClick);
          });
        }
      }
    }
```

```
<tr class="row0" data-draggable-group="none">
  <td class="text-center">
  </td>
</tr>
<tr class="row1" data-draggable-group="none">
  <td class="text-center">
   <label for="cb3"><span class="sr-only">Select </span></label><input autocomplete="off" type="checkbox" id="cb3" name="cid[]" value="130" onclick="Joomla.isChecked(this.checked);">
  </td>
</tr>
```

**Comment by dgrammatiko** [comment]
@Quy sure, the problem is that for disabled rows the checkbox **needs to render with a disabled attribute instead of skipping it**. Basically  the conditional  here https://github.com/joomla/joomla-cms/blob/d1d0091e804c09ce09ad7f3ef8695b840543acfb/administrator/components/com_modules/tmpl/modules/default.php#L97-L99 is wrong. It always need to render a checkbox but if the row is disabled the checkbox needs to also have a disabled attribute (eg `<?php echo HTMLHelper::_('grid.id', $i, $item->id); ?>` needs to return always a checkbox but if needed with a disabled attribute)

**Comment by Quy** [comment]
Added the disabled attribute to checkbox. Clicking the checkbox does not toggle it, however, clicking the row/check all items checkbox toggles the checkbox.

![30798](https://user-images.githubusercontent.com/368084/97504191-9fcd7200-1933-11eb-8f57-23f2d480cebc.png)

**Comment by dgrammatiko** [comment]
you need something like:
https://github.com/joomla/joomla-cms/blob/282fd17f2024e456463a181001bbd7c26ebb7acc/build/media_source/system/js/multiselect.es6.js#L68

```js
      if (this.boxes[currentCheckBox].disabled) {
        return;
      }
```

**Comment by Quy** [comment]
Almost there. The disabled checkbox can still be toggled using the Check All Items checkbox at the top. Thank you!

**Comment by brianteeman** [comment]
This appears to be resolved now as the last issue reported is no longer valid and this should be closed

**Comment by ReLater** [comment]
If you say so I believe it ;-)

**Comment by Quy** [comment]
This is reproducible.

Install Testing Sample Data.
Go to System > Manage > Extensions
Search and disable Wrapper - Site.
Go to System > Manage > Site Modules
Click Wrapper row.
The checkbox below it is checked.

**Comment by ReLater** [comment]
Thanks @Quy  for reopening! I have confused this with another selection failure pr (menu assignment)

**Comment by brianteeman** [comment]
What am I doing wrong then

![modules](https://user-images.githubusercontent.com/1296369/119173845-b702b700-ba5f-11eb-95d4-411ebe9fb74b.gif)

**Comment by dgrammatiko** [comment]
@brianteeman try to select the next module after the disabled one

**Comment by brianteeman** [comment]
ah - it selects the next two. got it now

**Comment by infograf768** [comment]
See demo of problem here in the NOTE
https://github.com/joomla/joomla-cms/pull/34238#issuecomment-850249636

**Comment by infograf768** [comment]
Why don't we simply do
```		
						<td class="text-center">
							<?php echo HTMLHelper::_('grid.id', $i, $item->id, false, 'cid', 'cb', $item->title); ?>
						</td>
```

imho, it does not matter if we can tick the disabled item checkbox and use Actions as it does not change its disabled status.

**Comment by brianteeman** [comment]
thats not a good solution as it provides a negative user experience which was the entire point in the checkbox being removed in the first place.

**Comment by bembelimen** [comment]
TBH, I'm more surprised when the checkbox is removed at all, because then I have to think and guess and have to make a connection: no checkbox? why? mhh, because it's disabled (says the icon at least).

If there would be an disabled checkbox with information why it's disabled, then I don't have to think myself...

**Comment by infograf768** [comment]
> thats not a good solution as it provides a negative user experience which was the entire point in the checkbox being removed in the first place.

Certainly less negative than what we have now. The module can anyway be edited although it is disabled. Taking off the checkbox makes no sense.

Concerning the explanation, I guess using a real tooltip as proposed here would do the job.https://github.com/joomla/joomla-cms/pull/34238#issuecomment-850249636

**Comment by dgrammatiko** [comment]
> thats not a good solution as it provides a negative user experience which was the entire point in the checkbox being removed in the first place.

Whoever removed the checkbox for the disabled items did a very poor job as they broke at least 3 scripts: drag and drop, multiselect and select all. Can it be done without a checkbox for disabled items? Yes but all 3 scripts need to be adjusted and honestly, it's far easier to bringback the checkbox as I already guided @Quy in my comments above

**Comment by bembelimen** [comment]
> 
> 
> > thats not a good solution as it provides a negative user experience which was the entire point in the checkbox being removed in the first place.
> 
> Whoever removed the checkbox for the disabled items did a very poor job as they broke at least 3 scripts: drag and drop, multiselect and select all. Can it be done without a checkbox for disabled items? Yes but all 3 scripts need to be adjusted and honestly, it's far easier to bringback the checkbox as I already guided @Quy in my comments above

+ Deletion of this entry is also not possible anymore...

**Comment by infograf768** [comment]
The use of `<?php if ($item->enabled > 0) : ?>` for the checkbox was introduced in J3.5.0
https://github.com/joomla/joomla-cms/pull/8020

**Comment by chmst** [comment]
If a component is disabled, we remove the link in the menu to this component. No Tooltip, no ghost componetnt - disabled means disabled. Why not hide disabled module instances from the list?

**Comment by dgrammatiko** [comment]
> Why not hide disabled module instances from the list?

Actually, I wouldn't expect the `list all modules` to display only rows for modules that are enabled. In fact, I would expect when a module row indicated that the module is disabled and I enable (publish) that row then the module will be enabled automatically instead of having to go to the extensions to enable the module and come back to publish the row. It seems that we're making things hard for no reason

Also if you hide rows like that in case I uninstall a module I have no way to remove any remaining related data in the database

**Comment by chmst** [comment]
I see this: A disabled module is not in the select screen (com_modules&view=select). 
Because it is disabled and may not be used - maybe old PHP version or whatever the reason is for the administrator.  
If another user could publish it in the same way as a unpublished module in (com_modules&view=modules), this would be contrary to the intention of disabling the module.

**Comment by chmst** [comment]
In any case, re-adding the checkbox and disabling it so that no action is possible would at least solve the problem of the missing checkbox

**Comment by infograf768** [comment]
> In any case, re-adding the checkbox and disabling it so that no action is possible would at least solve the problem of the missing checkbox

Except, as @bembelimen rightfully remarked, that one can't delete the instance of the module concerned via the admin UI.
Very different from not displaying the menu link to the component.

**Comment by chmst** [comment]
Just saying: In j3 disabled module items are not shown in the list. It is true that the items remain as ghost in the database.

**Comment by infograf768** [comment]
The difference in J3 is that a blocked module can't be disabled.
Therefore the test should be done with a non-blocked module.

**Comment by ReLater** [comment]
> In j3 disabled module items are not shown in the list.

In my case they are shown:
![29-05-_2021_11-18-07](https://user-images.githubusercontent.com/20780646/120065078-cab9a900-c06f-11eb-9e59-97827bba3317.jpg)

**Comment by infograf768** [comment]
Yep. Same for Most Read because it is not blocked.

<img width="392" alt="Screen Shot 2021-05-29 at 11 20 54" src="https://user-images.githubusercontent.com/869724/120065129-18361600-c070-11eb-9813-fd78af01b284.png">

**Comment by infograf768** [comment]
J3 list of protected modules

<img width="639" alt="Screen Shot 2021-05-29 at 11 23 02" src="https://user-images.githubusercontent.com/869724/120065184-503d5900-c070-11eb-8919-916c9d67d436.png">

**Comment by Fedik** [comment]
I have added checkbox, please test #34273

**Comment by Fedik** [comment]
closing it, because PR
