### ISSUE TITLE
[4.0] Popular Tags - Cloud view - number of items should stay next to the tag

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#30795]
In the **cloud view** of the module **Popular Tags** the the line break separates sometimes the number of articles and the associated tag. This is irritating, because the visitor doesn't see which number belongs to the tag
![screen shot 2020-09-28 at 10 34 51](https://issues.joomla.org/uploads/1/ab72a635cda56c3979135617d35724b2.jpg)
### Steps to reproduce the issue
- Publish the module "Tags - Popular "
- Set "Display Number of Items" to "Yes"
- Set on the advanced tab "Layout" to "Cloud"
- Set some tags in your articles

### Expected result
The number of items is always on the right side of the tag

**Comment by chmst** [comment]
I have reolved this in the cassiopeia template. Could you pleas test https://github.com/joomla/cassiopeia/pull/148? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30795">issues.joomla.org/tracker/joomla-cms/30795</a>.</sub>

**Comment by chmst** [comment]
Closing this as we have a PR

**Comment by Hackwar** [comment]
This has since been fixed in 4.x. The tags are wrapped in a span with class tag and that class is an inline-block.
