### ISSUE TITLE
[4.0] [a11y] Error in profile edit form, username 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#30794]
### Steps to reproduce the issue
Open a profile Edit form in the frontend. 
Inspect code.

### Expected result
No a11y error

### Actual result
![screen shot 2020-09-28 at 10 04 25](https://issues.joomla.org/uploads/1/4f6ec99acea44e1ba7f989028a2a027f.png)

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30796.
