### ISSUE TITLE
Templating - fontawesome not loaded correctly

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#30793]
### Steps to reproduce the issue
create a new template using the Web Assets
$wa  = $this->getWebAssetManager();
$wa->useStyle('template.test.ltr');

in the joomla.asset.json file :smile: 
"assets": [
    {
      "name": "template.test.ltr",
      "type": "style",
      "uri": "template.css",
      "dependencies": [
        "fontawesome"
      ]
    },

### Expected result
to load the library Fontawesome from the joomla core

### Actual result
load the media/vendor/fontawesome-free/css/fontawesome.min.css file, but the @font-face is missing

no FA icon is working in the page, because the font is not declared :smile: 
@font-face{font-family:Font Awesome\ 5 Free;  ... also for the Brand

in Cassopeia, the font-face is included in the template.min.css file, but if we load FA from the core, it shall be loaded correctly also with the font-face. Else we shall declare the font-face each time, for each template/extension and this is not correct

### System information (as much as possible)
4.0.0 beta 4

**Comment by N6REJ** [comment]
thanks for reporting this.
This is happening because they (fa ) expect you to load the fontset yourself.
```
  <!-- reference your copy Font Awesome here (from our CDN or by hosting yourself) -->
  <link href="/your-path-to-fontawesome/css/fontawesome.css" rel="stylesheet">
  <link href="/your-path-to-fontawesome/css/brands.css" rel="stylesheet">
  <link href="/your-path-to-fontawesome/css/solid.css" rel="stylesheet">
```

**Comment by ReLater** [comment]
> but if we load FA from the core, it shall be loaded correctly also with the font-face. Else we shall declare the font-face each time, for each template/extension and this is not correct

I agree. Joomla has the webfonts packed. Therefore their should be additional CSS that can be used as additional dependencies to decide which fonts to load (or not load) from /media/ folder.

**Comment by ced1870** [comment]
> This is happening because they (fa ) expect you to load the fontset yourself.
may be but in joomla asset there is 1 dependency, "fontawesome". It shall call all the needed CSS to make it work. Not only a part of it ...
as per the FA doc, you must copy and load the 3 files to make it work. They don't say to load only one file

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30793">issues.joomla.org/tracker/joomla-cms/30793</a>.</sub>

**Comment by particthistle** [comment]
Having tested #31096 today during Pizza Bugs & Fun, I've suggested whether @N6REJ should look at how to implement this in Cassiopeia, which would then give an example for template developers to use it in Joomla 4.

Or is this just something to document for developers/implementers to be aware of that FontAwesome is now included in Joomla 4 and you can access the files locally from the atum admin template (end solution may see them need to be moved from atum template to a library location and be called from there?)

**Comment by N6REJ** [comment]
@ced1870 how is J! supposed to know which fontset you want?  far, fas, fab? or is it supposed to load all 3 and create tons of bloat?
I don't understand WA but I do understand FA and its a 2 part solution.

**Comment by ced1870** [comment]
when you use the Web Assets Manager to load the depency "fontawesome", it is supposed to load it. Else what is the goal of it ?
This is loaded as joomla library, to avoid to load your own files yourself. 
May be that there shall be few options like 
"dependencies": ["fontawesome-all"]
"dependencies": ["fontawesome-regular"]
"dependencies": ["fontawesome-solid"]
...

this way we could load only the needed one as you suggested

**Comment by N6REJ** [comment]
someone like @Quy will have to address that.  I don't understand WA at all.

**Comment by Quy** [comment]
@Fedik

**Comment by Fedik** [comment]
I guess should be used 
`node_modules/@fortawesome/fontawesome-free/css/all.css`
instead of
`node_modules/@fortawesome/fontawesome-free/css/fontawesome.css`

need to update build stuff,
I will check some time later

**Comment by N6REJ** [comment]
@Fedik how does that tie in with the fact that modules/articles that have icons use fa icons.

**Comment by Fedik** [comment]
what do you mean?

**Comment by N6REJ** [comment]
since, for example, com_content & mod_login, use fa icons wouldn't FA be automatically available for the template too?

**Comment by Fedik** [comment]
please test #31364

**Comment by richard67** [comment]
Closing as having a pull request. Please test #31364 .
