### ISSUE TITLE
[j4] bug:  no defaut content if we use html editor for email template

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#30809]
hello it strange email template allow to create our template its very cool ... we can send email in html cool 
thanks @Hackwar 
 but when we edit it no tiny editor ... strange not ?
![image](https://user-images.githubusercontent.com/2539440/94658763-87057880-0303-11eb-82d5-b59503bf680c.png)

**Comment by brianteeman** [comment]
The original post was completely rewritten making my answer irrelevant so I have removed it

**Comment by micker** [comment]
ok cool i found a bug
wihout html
![image](https://user-images.githubusercontent.com/2539440/94718844-9829a600-0352-11eb-93e5-8e831ae9097f.png)

with html
![image](https://user-images.githubusercontent.com/2539440/94718911-b4c5de00-0352-11eb-9244-1196036eb1d5.png)

both
![image](https://user-images.githubusercontent.com/2539440/94719003-d8892400-0352-11eb-84c4-707f743271ad.png)

if we use html mode we lost content
i rename the issue

**Comment by Quy** [comment]
Duplicate #27619?

**Comment by micker** [comment]
for me this is a bug not an ux problem because when we use html editor we need to load content in text area as the plain text mode

**Comment by joomdonation** [comment]
Closing this issue because look like the issue was fixed elsewhere. The content is loaded when you edit the HTML body of the email template (see this attached screenshot)

![Edit-Mail-Template-Joomla-4-OK-Administration](https://user-images.githubusercontent.com/977664/114301076-46c25680-9aed-11eb-94c2-7d324bea53f8.png)
