### ISSUE TITLE
DMCA form for Joomla

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#30817]
### Is your feature request related to a problem? Please describe.
@Joomla already has the ability to delete user data through form `GDPR`, but it does not provide for the ability to delete individual `user generated content` (UGC) at the request of copyright holders, if the user publishes something that may violate copyright.

Depending on Joomla settings, `users` can register on the site and publish `articles` (`user generated content`) without administrator approval, so users can publish articles that violate copyright.

### Describe the solution you'd like
I suggest adding a `DMCA` form to Joomla.

### Additional context
[https://en.wikipedia.org/wiki/Digital_Millennium_Copyright_Act](https://en.wikipedia.org/wiki/Digital_Millennium_Copyright_Act)

You can see what this form looks like with examples:

[https://github.com/contact/dmca](https://github.com/contact/dmca)
[https://tumblr.com/dmca](https://tumblr.com/dmca)
[https://help.twitter.com/forms/dmca](https://help.twitter.com/forms/dmca)

**Comment by jeckodevelopment** [comment]
Hello, wouldn't a regular contact form be enough for the purpose?
I think that a manual check is needed and that the removal couldn't really be automated, unless the process unpublishes the content (instead of trashing it).

**Comment by 4digitalworld** [comment]
> 
> 
> Hello, wouldn't a regular contact form be enough for the purpose?
> I think that a manual check is needed and that the removal couldn't really be automated, unless the process unpublishes the content (instead of trashing it).

such a form may contain consents, which must be confirmed by the copyright holder, as in the screenshot below.

naturally, the site administrator will manually consider complaints and make a decision (content will not be automatically removed from the site without the administrator's decision), this will be the same as with form `GDPR`

![изображение](https://user-images.githubusercontent.com/3662519/94694484-91dcff00-033d-11eb-8e5b-7733a8af9e26.png)

**Comment by brianteeman** [comment]
Once again this is something that you need for your web site and its not something everyone needs for their web site. If the contact form is not sufficient there are very many form extensions available for Joomla that you can use, both free and commercial.

This should be closed. Joomla is designed to be extendable!!

**Comment by alikon** [comment]
fully agree

**Comment by jeckodevelopment** [comment]
Even if it's closed, i just want to mention that you can create this kind of forms even with the standard contact form (com_contacts), using custom fields. Otherwise you can create easily a form with any form extension.
I agree with Brian and Nicola, it looks like a very specific request that is not really "generally used".
