### ISSUE TITLE
[4.0] RFC accessibility checker

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30815]
Is there any interest in having an accessibility checker in the core. It would have two modes
Mode 1 an xtd-editor plugin that would check the content in the editor 
Mode 2 a site plugin that could be enabled (like debug mode) for checking the full page in the frontend

It's not that hard to create these but I don't want to invest time in this if its not going to be in the core. This is part of the EU funded  research project for improving the process of creating accessible content by authors https://accessibilitycluster.com/about

**Comment by 4digitalworld** [comment]
any **accessibility** check is very much needed! I support it!

**Comment by jeckodevelopment** [comment]
Imho it would be really helpful, especially for those site owners that should ensure their site are accessible.

**Comment by brianteeman** [comment]
It would absolutely not ensure a site is accessible. 

It is an aid to a content creator to highlight some accessibility issues

**Comment by alikon** [comment]
please correct me if i'm wrong,  but as far that i can see, at _some level_ we are already involved  (as subcontractor)
![Screenshot from 2020-09-30 19-37-00](https://user-images.githubusercontent.com/181681/94720196-729d9c00-0354-11eb-9300-52b45f1f7d31.png)

**Comment by brianteeman** [comment]
Yes I am representing JandBeyond EV on this project (politics prevented it saying joomla or joomla promoting it)

The aim of the project is mainly in researching and identifying key needs and areas where all cms can benefit. The project might eventually produce some code examples but that's not the main aim.

The research conducted in stage one of the project identified numerous needs by content authors and we are working on testing and evaluating the possibilities for improving each one of those. Not all of them apply to Joomla or we already address those issues. 

This is just the first of two issues I intend to open where we can implement solutions. The code would not be from the project but it is as a result of the research.

Hope that clarifies things a little.

**Comment by alikon** [comment]
thinking about this, it could be integrated with the Workflow too, and/or with a scheduled CLI command for reporting failure on the whole site pages

**Comment by brianteeman** [comment]
yes exactly. Doesn't look like anyone is interested though in improving the accessibility of content :(

**Comment by ghost** [comment]
>  Doesn't look like anyone is interested

i´m interested and 3 thumbs up on the opening comment so how much have to comment that interest is viewable?

**Comment by alikon** [comment]
the only thing that i can do more, is to add a point in the next PDT meeting agenda to discuss to have  this feature planned for 4.1

**Comment by alikon** [comment]
i'm playing with this https://github.com/p1ho/accessibility-checker even if it have a lot of composer 2.0 deprecation notice
what external libraries/tools do you have in mind ?

**Comment by ceciogit** [comment]
it would be great! also the scheduled cli command to generate a report..

**Comment by rdeutz** [comment]
We discussed this at the last production department meeting and we are basically in favor of such an addition to the cms. We decided to give this firstly to the accessibility team to get them involved at an early stage. We are hoping that we can say something more concrete after the next meeting.

**Comment by brianteeman** [comment]
Ah so we dont have open contribution to joomla any more. Good to know

**Comment by brianteeman** [comment]
Shame as the code could have been provided by the end of the week

**Comment by alikon** [comment]
this time i'm fully with you

**Comment by rdeutz** [comment]
@brianteeman you said "It's not that hard to create these but I don't want to invest time in this if its not going to be in the core."

You asked you got an answer, how this is "Ah so we dont have open contribution to joomla any more. Good to know"

You can make a PR as anyone can.

**Comment by richard67** [comment]
@brianteeman Please think it over and reopen.

**Comment by brianteeman** [comment]
Sorry I think something must be lost  in translation. 
I asked a question about investing time to create this code. The response you gave (as I read it) is that the accessibility team are going to do it.  So I closed the RFC as the reply has been given. This code will be provided by the accessibility team.

**Comment by richard67** [comment]
Hmm, as far as I understood their task is to check if this is something for the core, not to implement it.

**Comment by brianteeman** [comment]
That is not how I read Roberts statement although obviously I was not in the meeting. Maybe it will be ready for joomla 5

**Comment by richard67** [comment]
Well, of course I might have misunderstood it.

**Comment by richard67** [comment]
I wasn't in the meeting either.

**Comment by alikon** [comment]
i was in that meeting and that was my perception too...
probably i'm not too much skilled on spoken english nor on written
ok that's my fault....

**Comment by brianteeman** [comment]
> i was in that meeting and that was my perception too...

@alikon as the person who was there whose perception are you agreeing with ?

**Comment by alikon** [comment]
for my understanding, we need to wait for "Godot" to have the green light 
p.s.
obviosly i'm wrong

**Comment by softforge** [comment]
I was in the meeting Nicolas and when it was raised all in production was positive. You asked if Production would be behind an accessibility tool being in J4.1 and the answer was yes, not no, not maybe but yes.
It was then suggested, rightly that the accessibility team would be asked their opinion and we even said that the response back to Brian would be in 2 weeks in the next meeting but that a message should be written to show it was positive and it would be forthcoming so it was not thought to be ignored. 

Why you then add the Godot bit (which is a brilliant play. I got to see Patrick Stewart, Ian McKellen perform Samual Becketts brilliant piece on nonsense and it was an evening to remember) I don't know as we said it would be a definitive answer by the next meeting and as far as all in the meeting were concerned it was positive. There is no need to sow discord and it is a misrepresentation of the meeting to say other than that.

**Comment by softforge** [comment]
In answer to the point about the accessibility team. My understanding was that we were informing them of the offer and asking their views. Nothing more. Certainly not tasking them with any code. Just keeping teams informed so that there is no duplication of efforts. But I can see no reason why anyone would not be in favour of such a tool and it would have to be a strong and reasoned argument to change my personal sentiment. Its exactly what I need and would be a godsend in my day job.

**Comment by brianteeman** [comment]
> You asked if Production would be behind an accessibility tool being in J4.1 and the answer was yes, not no, not maybe but yes.

Actually I made no mention of a version

> It was then suggested, rightly that the accessibility team would be asked their opinion

Shame they didnt take the opportunity to comment on the RFC .

Obviously Robert's message was lost in translation as it did not appear that it was just an opinion being asked for. 

Why it would take 2 weeks for anyone to give an opinion on the principle of adding a function is completely beyond me. But then I guess thats why J4 is now 3 years late.

**Comment by softforge** [comment]
So I think there is a fair bit of "lost in translation". 
Agreed that now the accessibility team are aware of this they can respond directly rather than wait two weeks for a response to production.
The main thing which does seem to get lost sometimes is we are all trying to make Joomla better. We have an accessibility team which have those aims at their heart and Brian who is a champion of accessibility and has informed many of us over the years. We have changed how we do Joomla London meetings from zoom to google meet with captions because of his talk at JAB and it has resulted in more able to join the meetings.
There are differences of opinion as in all things but as long as we take the time to explain and base opinions on facts we should move forward on this.

**Comment by brianteeman** [comment]
> Agreed that now the accessibility team are aware of this they can respond directly rather than wait two weeks for a response to production

Silly me for assuming that the accessibility team looked at github and/or the issue tracker and noticed something with accessibility in the title.

**Comment by softforge** [comment]
That last comment is not in the spirit of cooperation or calming this down. Please all, cooperate on the goal which I thought was to get an accessibility tool in Joomla. I am sure the accessibility team will give a view in a day or two and then we can look at the facts and not speculation.  I for one would really love to see Joomla known for being top in accessability

**Comment by zwiastunsw** [comment]
Gentlemen. What is it? Volunteer @brianteeman :100:  reports that he will make a much-needed accessibility checker code in a week and you are wondering if you can agree and give yourself 2 weeks for the JAT opinion?
Brian, don't be offended. This is a very good idea! Who will do it if you don't?

**Comment by carcam** [comment]
Well, in case anyone has any doubt, @joomla/joomla-accessibility-team-jat (JAT)  thinks this is a great idea and we support @brianteeman on this and we would love to help him made this happen ;)

**Comment by brianteeman** [comment]
So why did you need 2 weeks or to be involved? Never mind - will have to work on it next week now

**Comment by brianteeman** [comment]
See #31090
