### ISSUE TITLE
Module Class not added in output of mod_custom when Module Style 'inherited' (and using {loadposition})

### ISSUE THREAD

**Issue by EvDoorne** [joomla/joomla-cms#30822]
### Steps to reproduce the issue
- Publish a mod_custom module in a position that is generated via the {loadposition position_name} code.
- Set a class in the field 'Module Class' under the 'Advanced' tab of the module.
- Set the Module Style to 'Inherited' (which is the default setting).

### Expected result
Output `"<div class="mod-custom custom">"` has the user set Module Class added, 
i.e. `"<div class="mod-custom custom my-custom-class">"` .

### Actual result
The user set Module Class is not added, the output remains `"<div class="mod-custom custom">"`.

### System information (as much as possible)
- J!4 beta 4
- Cassiopeia template

### Additional comments
Custom class(es) set in the Module Class field will be generated:
- when setting the Module Style to 'default (template: Cassiopeia)';
- when publishing the module in a module position that is defined in templateDetails.xml.

**Comment by johnwinston1** [comment]
erterter[pending artilce.docx](https://issues.joomla.org/uploads/1/ab74d1f3d9f1c329a9432e406653ed03.docx)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30822">issues.joomla.org/tracker/joomla-cms/30822</a>.</sub>

**Comment by gostn** [comment]
comment above spam?

**Comment by drmenzelit** [comment]
If the module position has no style set it is an expected behaviour. The module chrome "none" doesn't render the div where the module class should be.

**Comment by EvDoorne** [comment]
Thank you Viviana, I would agree with you if the Module Style was set to 'none' . But the Module Style is set to 'inherited'. Here, using the Cassiopeia template, the surrounding div `"<div class="mod-custom custom">"` is generated but the Module Class is omitted in that div, wether the Module Class is set or not.

**Comment by drmenzelit** [comment]
Which style has the position (in index.php) where you want to have the module? If the position has style: none, then the module will inherit it.

**Comment by cloudfaction** [comment]
setting the style to html5 does the trick. however, i agree, when inherited is used, you would expect to see the custom style applied. now this only works with html5 as module style. Even more, the bootstrap size only work when html5 is selected, of not setting bootstrap size has no effect.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30822">issues.joomla.org/tracker/joomla-cms/30822</a>.</sub>

**Comment by mtechoh** [comment]
This appears to still be an issue. mod_custom default template doesn't reference the module class at all:

<div id="<?php echo $modId; ?>" class="mod-custom custom">

And unless I'm missing something, most of the mod_* items ignore the module class and don't attempt to make moduleclass_sfx available.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30822">issues.joomla.org/tracker/joomla-cms/30822</a>.</sub>

**Comment by drmenzelit** [comment]
"Inherited" means the module will take the style defined in the template position
`<jdoc:include type="modules" name="bg" style="none" />`
If the position has `style="none"` the module will be loaded without chrome around. That is expected behavior.

**Comment by mtechoh** [comment]
Perhaps this is just an adjacent issue, then, but re-read my comment and check the code in mod_custom/tmpl/default.php (and others). No individual module instance style is possible in the template on 4. This was possible in 3 and there was code there to pull the style from the module instance. Adding that code back in an override makes it possible again.

**Comment by plamenstoyanov** [comment]
Thank you, mtechoh! Your solution solved the issue:  class="mod-custom custom <?php echo $params->get('moduleclass_sfx') ?>"

**Comment by thodorisgo** [comment]
J5 with Cassiopeia and the issue is present and pretty annoying.
By default custom module has the inherited style selected. So it takes extra steps for the user to apply custom classes.
Regards

**Comment by brianteeman** [comment]
inherited style is correct. the problem is that in many of the position in the template it is set to use style none.
