### ISSUE TITLE
[4.0] [debuger bar] Show queries arguments

### ISSUE THREAD

**Issue by bato3** [joomla/joomla-cms#30826]
### Is your feature request related to a problem? Please describe.
In the Queries tab (Debugger bar): currently queries in the form of:
```sql
SELECT `id`,`name`,`rules`,`parent_id`
FROM `jos37_assets`
WHERE `name` LIKE :asset OR `name` = :extension OR `parent_id` = 0
```
Please add argument values so that I know what `asset` and `extension` are.

### Describe the solution you'd like
I propose a solution from the knex.js logger: after the query there is an array with values.

![example](https://user-images.githubusercontent.com/11570/94775063-64389a00-03bf-11eb-923f-290fb05d9f4d.png)

### Additional context
It would be nice if we could reduce the number of occurrences of `preparedArray n`...
```sql
SELECT `id`,`name`,`rules`,`parent_id`
FROM `jos37_assets`
WHERE `name` IN (:preparedArray1,:preparedArray2,:preparedArray3,:preparedArray4,:preparedArray5,:preparedArray6,:preparedArray7,:preparedArray8,:preparedArray9,:preparedArray10,:preparedArray11,:preparedArray12,:preparedArray13,:preparedArray14,:preparedArray15,:preparedArray16,:preparedArray17,:preparedArray18,:preparedArray19,:preparedArray20,:preparedArray21,:preparedArray22,:preparedArray23,:preparedArray24,:preparedArray25,:preparedArray26,:preparedArray27,:preparedArray28,:preparedArray29,:preparedArray30,:preparedArray31,:preparedArray32,:preparedArray33,:preparedArray34,:preparedArray35,:preparedArray36,:preparedArray37)
```

Joomla! Version | 4.0.0-beta4
-- | --
PHP Version | 7.4.9
Database | 10.3.15-MariaDB

**Comment by alikon** [comment]
this has been already solved  https://github.com/joomla/joomla-cms/pull/30717
![image](https://user-images.githubusercontent.com/181681/94776011-30f70a80-03c1-11eb-8261-5fd538ec7c17.png)
