### ISSUE TITLE
Improving Your Paragraphs

### ISSUE THREAD

**Issue by jefforwell** [joomla/joomla-cms#30835]
### Steps to reproduce the issue

[6.pdf](https://issues.joomla.org/uploads/1/2a1f58769e8e3b1b72639c26bc0e2e9f.pdf)

**Comment by alikon** [comment]
@zero-24  please ban this one too

**Comment by zero-24** [comment]
I'm on mobile now but will ask the maintainers to block him.

**Comment by rdeutz** [comment]
done
