### ISSUE TITLE
Joomla 4 template styles color pickers are jumpy

### ISSUE THREAD

**Issue by stevejburge** [joomla/joomla-cms#30848]
### Steps to reproduce the issue

When editing template styles for Atum, the color pickers jump around and can't be used

This is the admin URL: /index.php?option=com_templates&view=style&layout=edit&id=10

I try to select the "Special Color" box:

<img width="1313" alt="before" src="https://user-images.githubusercontent.com/3868028/94857306-4b4fd900-03ff-11eb-905c-0ba6eb0f3042.png">

And the whole screen jumps around:

<img width="1328" alt="after" src="https://user-images.githubusercontent.com/3868028/94857354-5efb3f80-03ff-11eb-8aee-478821926e8a.png">

I can make this work only by narrowing the screen to mobile width:

<img width="538" alt="Screen Shot 2020-10-01 at 4 02 06 PM" src="https://user-images.githubusercontent.com/3868028/94857431-7a664a80-03ff-11eb-8029-5d083d18d8d4.png">

**Comment by Quy** [comment]
Duplicate #29955. Thanks for the report.
