### ISSUE TITLE
[4.0] Change the size of the template name font in module position selector

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#30844]
### Is your feature request related to a problem? Please describe.
In the cpanel > Content > Site Modules when choosing a module position, the font used for the name of the templates, e.g. 'Cassiopeia' and 'New template' are smaller than the position and harder to see:

![PR30760-03](https://user-images.githubusercontent.com/36987494/94818653-42a6d500-03f6-11eb-9956-521c91948469.jpg)

### Describe the solution you'd like
Enlarge and possibly bold the font

### Additional context
I can find the code that controls this in an installed site on line 242 in atum/css/vendor/choicesjs/choices.css; it has a font-size of 12px whereas the list of module positions is 14px but I can't find that line in the original code on github. However, I understand that vendor code can't be changed directly so some custom css to change this will be required, but as I have no idea how the build works, I can't suggest a suitable location.

**Comment by brianteeman** [comment]
Please test #30890
