### ISSUE TITLE
Media manager - image selection not working

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#30840]
### Steps to reproduce the issue
1/ Go into an article >> intro image >> select >> it opens the media manager
2/ click on the box to select an image (do not click the image, just the box)
3/ click "select" button of the modal to apply your image

- Note that if you click the image (and not the select box on the image) , it works as expected
- same issue with the "image" button in the editor

### Expected result
to select the image

### Actual result
nothing, the modal closes but the image is not added in the field

### System information (as much as possible)
joomla 4 beta 4

**Comment by drmenzelit** [comment]
I can confirm this. You have to click on the image or open the image to get it selected.

**Comment by Quy** [comment]
It will be fixed. See https://github.com/joomla/joomla-cms/pull/30784#issuecomment-700571337

**Comment by Quy** [comment]
Please test PR #31427
