### ISSUE TITLE
5 Things to Keep in Mind When Writing Essays

### ISSUE THREAD

**Issue by jefforwell** [joomla/joomla-cms#30841]
### Steps to reproduce the issue

[5 (1).pdf](https://issues.joomla.org/uploads/1/e01e83e482afa0c50c0316996daf7a68.pdf)

**Comment by chmst** [comment]
Spam<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30841">issues.joomla.org/tracker/joomla-cms/30841</a>.</sub>
