### ISSUE TITLE
[4.0] Upgrade don't disable old extensions

### ISSUE THREAD

**Issue by bato3** [joomla/joomla-cms#30843]
### Steps to reproduce the issue

Upgrade from Joomla! 2.x (1.5) to 4.0 beta 4

### Expected result

Disable / remove & cleanup native extensions removed in Joomla 4

### Actual result
On extension list i have eg.: `com_search`

### Additional comments
From report https://github.com/joomla/joomla-cms/issues/30472 I know that Joomla 3.10 should check if there are any problems, but as I was doing the current migration, it didn't stop me... And I should have a message that there is no compatible version of `simplepie`extension. (Today I compare clean i migrated extensions list, and I remembered that he should remove them)

**Question**: *Could it be that these checks are only performed for `$debug = true`?*

**Comment by zero-24** [comment]
The pre upgrade checker does not block anything it is 'just' an info tool for you to plan the mirgation right now.

**Comment by ReLater** [comment]
Concerning com_search: see https://docs.joomla.org/Joomla_3.x_to_4.x_Step_by_Step_Migration#Notes_on_Search_.28com_search.29

> Notes on Search (com_search)

> Search (com_search) will be decoupled in Joomla 4.x. Search (com_search) will migrate to Joomla 4. After migration, you'll need to update it to the Joomla 4.x version via com_installer. It will continue to be maintained, but more the same way a third-party extension is by receiving updates via com_installer. It is recommended to use Smart Search (com_finder) going forward. Search will still be available at https://extensions.joomla.org/category/official-extensions/ .

I'm not sure if it's this repository: https://github.com/joomla-extensions/search

All I know is that com_search doesn't break the backend on updates from Joomla 3 to 4. Haven't tested more yet.

**Comment by zero-24** [comment]
> I'm not sure if it's this repository: https://github.com/joomla-extensions/search

Yes it is that repo :)

**Comment by Hackwar** [comment]
com_search is not removed from existing sites. We don't want to break them. com_search will have a 4.0-compatible version, which we are going to maintain until Joomla 5.0. It is correct that com_search is not removed on update.

**Comment by bato3** [comment]
There is no secret, most people take the system "as is", without further thought. I would suggest a step to summarize about extensions not natively found in Joomla! 4. (Separated into "deprecated" and "self-installed")

The minimum number of cases update will be done by the person who installed the earlier version. Such a list would help me determine if I still want to use them.

**Comment by brianteeman** [comment]
A list is now provided with detailed information in the pre-update check. It was not available at the time of this report

**Comment by bato3** [comment]
I am unable to verify this now. I can publicize the base, but the "moment" will it take before the necessary files is uncovered.

**Comment by Quy** [comment]
Closing. If there are specific migration issues, please open new issues. Thanks.
