### ISSUE TITLE
Installation of joomla-4 beta4,5 failed.

### ISSUE THREAD

**Issue by fujisawa2238** [joomla/joomla-cms#30861]
### Steps to reproduce the issue
Installation of joomla-4

### Expected result
I'm beginner of Joomla.
joomla-4 (including Beta version) can be installed using the same 
system environment and procedure as Joomla 3.x.

### Actual result
Beta2-5versions of J-4 all failed in the single installation work.
I get an attached error at the final stage of installation.

However, the following are not included in the J-3 installation.
-Connection Encryption: One-way authentication
-Verify Server Certificate: NO

This server is a system environment where the J-3.9 version has been 
successfully installed.
Does J-4 have any different operating conditions for MySQL?

### System information (as much as possible)
PHP Built On 	FreeBSD
Database Type 	mysql  Version 	5.7.28-log
PHP Version 	7.4.9
Web Server 	Apache 

### Additional comments
If'Verify Server Certificate: YES' is correct, what is the CA for'path to CA'?

**Comment by HLeithner** [comment]
The Server verification is for the TLS connection between mysql server and the webserver. If you don't have an TLS certificate on your server installed or don't have TLS activated you don't need this option.

**Comment by fujisawa2238** [comment]
Hello, Harald
thank you for your advice.
I understand the meaning of "Verify Server Certificate".
My server was set up for testing, so I haven't set up TLS / SSL.
Therefore, the setting of "No" is fine here.

Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30861">issues.joomla.org/tracker/joomla-cms/30861</a>.</sub>

**Comment by alikon** [comment]
@fujisawa2238 if resolved then please close the issue

**Comment by fujisawa2238** [comment]
Dear,alikon
No, I haven't solved any of my problems.
Because I still can't install the beta version of Joomla-4.
I afraid that the beta version of J-4 has a different installation environment from J-3.x.
If so, please tell me what kind of system environment I should set. PHP or MySQL?

To make matters worse, even if a stable version of Joomla-4 comes out, I can't install it in my system environment.
I request that the J-4 installation environment be the same as J-3.x.

regards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30861">issues.joomla.org/tracker/joomla-cms/30861</a>.</sub>

**Comment by alikon** [comment]
joomla 4 cannot have the same system requirements as joomla 3 

the minimum technical requirements for Joomla 4 are:

    PHP 7.2.5
    MySQL 5.6 (Note: The minimum MySQL version can be subject to change during the lifetime of Joomla 4 if necessary)
    PostgreSQL 11.0
    Minimum browser version set to n-2
    End of support of Internet Explorer


if you still experiencing issues please post on on https://forum.joomla.org
