### ISSUE TITLE
[4] "Your YubiKey is already linked to your user account" twice

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30874]
### Steps to reproduce the issue

Enable Yubikey on an account in admin console of Joomla 4
Edit your account ->Two Factor Authentication Tab

Note "Your YubiKey is already linked to your user account" is said twice.

### Expected result

"Your YubiKey is already linked to your user account" once

### Actual result

"Your YubiKey is already linked to your user account" twice

<img width="1574" alt="Screenshot 2020-10-02 at 18 09 11" src="https://user-images.githubusercontent.com/400092/94950508-a7d3f680-04da-11eb-9d55-f416bb453e87.png">

**Comment by brianteeman** [comment]
please test #30879
