### ISSUE TITLE
[4] Menu selection model toolbars misaligned

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30878]
### Steps to reproduce the issue

Add an article in Joomla 4 admin 
Click CMS Content in wysiwyg editor
select Menu
Note modal pop up loads 

### Expected result

The "Select Menu" dropdown on the same line as the rest of the filters 

### Actual result
Actual result not dependant on screen size 

<img width="1373" alt="Screenshot 2020-10-02 at 19 07 10" src="https://user-images.githubusercontent.com/400092/94955473-81b25480-04e2-11eb-89b5-8a125bf0237c.png">

### System information (as much as possible)

safari on mac

**Comment by brianteeman** [comment]
Intended behaviour - see the non-modal views
