### ISSUE TITLE
[4] Tags Options Layout Issues

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30884]
### Steps to reproduce the issue

Go to create a new Tag in Joomla 4 Admin.
Go to the Options Tab

### Expected result

Layout is responsive, and works in all breakpoints.

### Actual result

Half a huge 27" Mac monitor it looks fine:

<img width="1569" alt="Screenshot 2020-10-02 at 20 03 51" src="https://user-images.githubusercontent.com/400092/94960213-677c7480-04ea-11eb-9979-a6a7c3f31ee5.png">

any size more common/realistic the fields start to overlap 

1600x1200 you start to see the left selector start to break up 

<img width="480" alt="Screenshot 2020-10-02 at 20 05 15" src="https://user-images.githubusercontent.com/400092/94960352-a5799880-04ea-11eb-9e0c-9fd50ce865ae.png">

1280x1024 overlapping occurs

<img width="1269" alt="Screenshot 2020-10-02 at 20 07 02" src="https://user-images.githubusercontent.com/400092/94960483-e2458f80-04ea-11eb-8975-46cce7450ad9.png">

1024x768

<img width="1009" alt="Screenshot 2020-10-02 at 20 08 00" src="https://user-images.githubusercontent.com/400092/94960555-02754e80-04eb-11eb-853e-74f5d70d19c5.png">

### System information (as much as possible)

safari on Mac

**Comment by Quy** [comment]
Duplicate #30423. Pending PR #29706
