### ISSUE TITLE
[4] Uploading and overwriting media generates blank space instead of messages

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30880]
### Steps to reproduce the issue

Joomla 4 admin
Media Manager

## one way:
Drag 4 files from your desktop to drop in the media manager
Note they upload ok
Drag the same 4 files from your desktop to drop in the media manager
Note you get asked if you want to overwrite - say ok 4 times
note the huge blank space at the top of the page now

## Another one way:

Select 4 items (holding down shift to multi select them)
Click delete
Click delete in warning popup
Note flashing as messages are added
Note blank space above "Item Deleted" message
Note that if you select 40 items then the space is then 10x the size 

## Video 

Too large for Github. view here: https://screenshot.phil-taylor.com/2Nuj2Kgz

### Expected result

Any messages should be shown 
if there are 10 items deleted then message should say "10 items deleted" and not show 10 x "Item deleted"
"blank space" should not be there, 

### Actual result

As explained above. 

screenshot with highlighted dragger the space to revel blank area divs:

<img width="1406" alt="Screenshot 2020-10-02 at 19 26 42" src="https://user-images.githubusercontent.com/400092/94957179-42393780-04e5-11eb-8f8b-2b6bb17d25b9.png">

### Additional comments

In source, there are a messages in that "blank space" just not visible

<img width="810" alt="Screenshot 2020-10-02 at 19 23 06" src="https://user-images.githubusercontent.com/400092/94956866-c2ab6880-04e4-11eb-8546-0e08cf5e8fd3.png">

**Comment by brianteeman** [comment]
I can confirm the bug. The problem is that instead of the alert being destroyed it is set to display:none

It doesnt happen all the time which is even more weird

**Comment by Quy** [comment]
Related #29152

**Comment by Quy** [comment]
Please test PR #32868
