### ISSUE TITLE
[4] validation error messages on frontend wrapped/something rendering wrong

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30883]
### Steps to reproduce the issue

Edit an article using Joomla 4 FRONTEND as super admin
Go to the Publishing tab
Click X to remove the category
Click Save

### Expected result

"One of the options must be selected" should be all on one line. 

### Actual result

<img width="869" alt="Screenshot 2020-10-02 at 19 55 47" src="https://user-images.githubusercontent.com/400092/94959548-49fadb00-04e9-11eb-8d43-24a60e289235.png">

Interestingly when trying to select the text to copy into this issue I then got:

<img width="372" alt="Screenshot 2020-10-02 at 19 56 13" src="https://user-images.githubusercontent.com/400092/94959599-5ed76e80-04e9-11eb-87e2-53ebfeb20386.png">

and on blur I then got

<img width="359" alt="Screenshot 2020-10-02 at 19 56 43" src="https://user-images.githubusercontent.com/400092/94959625-6860d680-04e9-11eb-87b4-c1a14474fdb3.png">

### System information (as much as possible)

Safari 14.0.1 on Mac big sur developer beta 9

**Comment by brianteeman** [comment]
Can not replicate on any windows browser. Maybe a mac safari thing?

**Comment by gostn** [comment]
Safari Version 13.1.2 (13609.3.5.1.5), iMac: Click on ´x´ dont remove category.

**Comment by PhilETaylor** [comment]
Cannot replicate today in Safari 15.4
<img width="718" alt="Screen Shot 2022-03-06 at 22 11 49" src="https://user-images.githubusercontent.com/400092/156944268-9b3a6cd3-923c-4902-bac0-1240f5347a5d.png">
