### ISSUE TITLE
[4] Link Image Selector allows selecting non-images

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30881]
### Steps to reproduce the issue

can be reproached in many places, but quickest is to create a new Article in Joomla 4 Admin 
Go to the Images and Links Tab
Click Select to launch Media Manager
Select a non-image, like a 4Mb CSV file
(enter title of the article to complete validation)
Click Save

<img width="704" alt="Screenshot 2020-10-02 at 19 47 10" src="https://user-images.githubusercontent.com/400092/94958822-13709080-04e8-11eb-8e95-e21a33a5d4fc.png">

### Expected result

Image selected should fail validation before the article saves, maybe "non image types" should not selectable in the first place? but certainly it should be validated "as an image" on save of the article because the value of this field is used on the frontend and is rendered in HTML. 

### Actual result

Article saves. 

If this was a menu link we were creating, we could choose a "link image" using the same kind of component widget, then on the frontend we would end up with html like 

<img width="325" alt="Screenshot 2020-10-02 at 19 46 30" src="https://user-images.githubusercontent.com/400092/94958751-f9cf4900-04e7-11eb-9eea-e623c8a3c3c7.png">
<img width="536" alt="Screenshot 2020-10-02 at 19 46 41" src="https://user-images.githubusercontent.com/400092/94958770-018eed80-04e8-11eb-8d75-d4cdee2e4eae.png">

**Comment by richard67** [comment]
At least it is loaded lazy, the csv file ;-)

**Comment by PhilETaylor** [comment]
> At least it is loaded lazy, the csv file ;-)

Which itself was only allowed to be uploaded due to another bug haha

**Comment by dgrammatiko** [comment]
FWIW once https://github.com/joomla/joomla-cms/pull/30784 merged  I'm planing to expand the media field for any supported type (keeping things backwards compatible, hopefully)

**Comment by Quy** [comment]
Please test https://github.com/joomla/joomla-cms/pull/34634#issuecomment-869232143
