### ISSUE TITLE
[4] Manage Content Security Policy Reports Link

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30887]
### Steps to reproduce the issue

Joomla 4 admin -> System menu -> Manage module is this by default:

<img width="436" alt="Screenshot 2020-10-02 at 20 34 07" src="https://user-images.githubusercontent.com/400092/94962602-a14f7a00-04ee-11eb-92c3-4984a4cba35f.png">

Clicking on Manage -> Content Security Policy

## Expected result

Expect to be taken somewhere to mange the Content Security Policy of the site (I.e expect to be editing the `System - HTTP Headers` plugin which is where the Content Security Policy is configured

## Actual result 

Im taken to the `Content Security Policy Reports` com_csp component which doesn't allow me to "Manage my Content Security Policy" at all, but allows me to see reports only.

**Maybe rename the link to be `Content Security Policy Reports` instead of `Content Security Policy` ?**

**Comment by zero-24** [comment]
In Joomla 4 the CSP is configured in the components options not in the plugin.

So to me the link to the component is right.

For sure we can change the string when there is a better suggested.

Maybe we could add a message in the component pointing to the options when nothing is configured yet? What do you think?

**Comment by PhilETaylor** [comment]
> in Joomla 4 the CSP is configured in the components options not in the plugin.

Sorry you are wrong. 

well this is what is in the options of the component:

<img width="980" alt="Screenshot 2020-10-02 at 21 15 33" src="https://user-images.githubusercontent.com/400092/94966019-723c0700-04f4-11eb-8797-b4708f7a49af.png">

What this controls is this header:

```
content-security-policy-report-only: default-src 'self'; report-uri http://127.0.0.1:4444/index.php?option=com_csp&task=report.log&client=site
```


but the **actual policy** is in the plugin

<img width="1222" alt="Screenshot 2020-10-02 at 21 16 28" src="https://user-images.githubusercontent.com/400092/94966082-90a20280-04f4-11eb-9402-8d9a324b5326.png">

The link in the Manage list of links is text "Content Security Policy" and therefore I WOULD ASSUME that is where I go to Manage my Content Security Policy... not to view my reports or set my `content-security-policy-report-only` header

**Comment by zero-24** [comment]
> > in Joomla 4 the CSP is configured in the components options not in the plugin.
> 
> Sorry you are half  wrong.  :-) 
> 
> well this is what is in the options of the component:
> 
> <img width="980" alt="Screenshot 2020-10-02 at 21 15 33" src="https://user-images.githubusercontent.com/400092/94966019-723c0700-04f4-11eb-8797-b4708f7a49af.png">
> 
> What this controls is this header:
> 
> ```
> content-security-policy-report-only: default-src 'self'; report-uri http://127.0.0.1:4444/index.php?option=com_csp&task=report.log&client=site
> ```

Yes and there you can also switch to custom and auto mode and that is the suggested way to implement CSP in 4.x ;-)

> **If this option is DISABLED (in the component options) then the `content-security-policy` header (controlled by the plugin) is STILL SENT!
> 
> If this option is ENABLED, To CUSTOM and REPORT ONLY turned off - then it hijacks the output of  `content-security-policy` header and overrides the plugin!!** 
> 
> The **actual policy** (the content-security-policy header)  is in the plugin

Well the plugin can overwrite the setting from the compo ent that is right but the option to do so is called 'forced header' right?


> 
> <img width="1222" alt="Screenshot 2020-10-02 at 21 16 28" src="https://user-images.githubusercontent.com/400092/94966082-90a20280-04f4-11eb-9402-8d9a324b5326.png">
> 
> The link in the Manage list of links is text "Content Security Policy" and therefore I WOULD ASSUME that is where I go to Manage my Content Security Policy... not to view my reports or set my `content-security-policy-report-only` header
> 

As mention above the siggested way to configure the header is com_csp's options.

> 
> **HOWEVER (edit)** 
> 
> it seems that you can set `content-security-policy` by disabling report-only in the component options which is overriding the http headers plugin... 
> 
> **so now we have two things trying to control one header? How confusing!** 
> 

Well there are two places to allow to set an pre existing header that bypasses com_csp but the usual user should use com_csp to manage and configure the CSP header.

**Comment by PhilETaylor** [comment]
Cool... hope all that is documented in a way idiots like me can follow along and understand  ;-)

**Comment by zero-24** [comment]
Why is this closed? I only tried to explain the intended stuff. I'm happty to improve UX where needed and would be very happy for your input here.

**Comment by PhilETaylor** [comment]
> Why is this closed? I

Because I accept that I was wrong and did not understand how things were expected to work. It makes sense now that you have taken time to explain, thanks.

**Comment by zero-24** [comment]
> Cool... hope all that is documented in a way idiots like me can follow along and understand  ;-) 

It is (one of the few 4.x stuff that is documented) but i'm happy to improve the docs where need.

So please share your input and possible improvments.

**Comment by PhilETaylor** [comment]
I guess the bit - for me at least - that never made sense was hiding the "setting up of the CSP" in the component options... and having the main component be the reporting management...

**Comment by PhilETaylor** [comment]
And I wrongly assumed the HTTP Headers Plugin was the correct and definitive way to set all these fiddly custom headers, now I understand what the "Force" in "Force Http Headers" means... it means override any other previously set header value for this header.

**Comment by zero-24** [comment]
Do you have a suggestion how we can impeove that?

The main reason for the current look and feel is that we used the structure that we have for other places too. For example the redirect component + plugin.

**Comment by zero-24** [comment]
> And I wrongly assumed the HTTP Headers Plugin was the correct and definitive way to set all these fiddly custom headers, now I understand what the "Force" in "Force Http Headers" means... it means override any other previously set header value for this header. 

Well as it bases on my 3.x plugin there it was the place for all headers but to make sure all options are in the right spot we moved the csp options stuff to com_csp.

**Comment by PhilETaylor** [comment]
Well my feedback, take it or leave it, is that Joomla needs to do better **"Empty State Design"**.

I.e: Rather than going to a page, and seeing a blank list of nothing, with a message "no matching results", Joomla could have a page that that introduces the feature, gives links to documentation, explains the basics and gives a call to action... 

This would be much better. VERY easy to do and would add value to Joomla for those new to using Joomla (or a new feature) or idiots like me...

Comparing: 

<img width="1157" alt="Screenshot 2020-10-02 at 22 05 20" src="https://user-images.githubusercontent.com/400092/94969904-6f90e000-04fb-11eb-9fe8-863031d357c8.png">


I personally like the Examples at DigitalOcean - but this is just an example to prove how much more helpful this is than just "no matching results",

<img width="1264" alt="Screenshot 2020-10-02 at 22 02 36" src="https://user-images.githubusercontent.com/400092/94969660-0b6e1c00-04fb-11eb-98f5-a4cf69936877.png">

**Comment by PhilETaylor** [comment]
Another bad empty state is the redirects component that mentioned - it starts like this: 

<img width="1322" alt="Screenshot 2020-10-02 at 22 12 23" src="https://user-images.githubusercontent.com/400092/94970346-66ecd980-04fc-11eb-83e0-4fc88f766eb1.png">

A big red error message... "but I just installed Joomla 5 mins ago... why have I got big red errors?!?!?"......

I then have to do three clicks to open a modal change a setting, save and close a modal... just to enable something else somewhere else... and then Im STILL LEFT ON A PAGE that says the The Redirect System Plugin is disabled. until I reload the page manually.... Bad experience.

**Comment by zero-24** [comment]
Agree can we re open this issue here and re label it as UX issue for the empty state? Adding more info and links to the docs etc makes sense to me.

**Comment by PhilETaylor** [comment]
Up to you. Design, lipstick and paint are my worse dev qualities... I don't have all the answers, but its a no brainer I think to improve the default empty state design for all components.... Its such a quick win for little effort.

**Comment by zero-24** [comment]
Thanks will have a look into that and come back here.

**Comment by zero-24** [comment]
> Up to you. Design, lipstick and paint are my worse dev qualities... I don't have all the answers, but its a no brainer I think to improve the default empty state design for all components.... Its such a quick win for little effort. 

For now i would start with com_csp but i think it can be adopted for other components later too. Lets see what i can come up with.

**Comment by PhilETaylor** [comment]
Lead and Im sure others will follow :-) 

At the moment the out of the box experience (without demo data) is a bunch of left menu items that all lead to blank pages saying "no matching results" :-) 

A single HTML page of helpful information, links, an illustration maybe, and a call to action is all that is needed... and a single if statement in PHP (if rows ==0 then load the empystate view :) ... zero b/c breaks ... big win ...

**Comment by PhilETaylor** [comment]
for inspiration here are two screenshots from an unnamed "service I might own" ;-) it can be as simple as these, but with helpful links and text specific for the component. 

<img width="1005" alt="Screenshot 2020-10-02 at 22 28 39" src="https://user-images.githubusercontent.com/400092/94971318-ae746500-04fe-11eb-9823-ad9e18890943.png">
<img width="996" alt="Screenshot 2020-10-02 at 22 28 31" src="https://user-images.githubusercontent.com/400092/94971320-afa59200-04fe-11eb-8b3e-db38824bb060.png">

**Comment by zero-24** [comment]
Thanks its noted

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/33264
