### ISSUE TITLE
[4] Ajax Login Bug when site unstable/erroring

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30898]
### Steps to reproduce the issue

Another Ajax bug on admin login 

Load the /administrator/ page.

Edit /administrator/index.php and place a `die();` after the opening `<?php` - doing this replicates "bug" on your site, it could be a php warning, or an exception in a plugin, or any PHP error. Most common is a plugin outputting PHP Notices or warnings... 

Try to login 

Note that you get ZERO FEEDBACK now, no error messages are shown. You try to click Login In again and no feedback... you are now at a loss as why you cannot login. 

This is because the JSON response to the AJAX request is malformed and Joomla's JS doesn't handle it with a try/catch block

### Expected result

Visual "there was a problem" kind of message... [JLIB_JS_AJAX_ERROR_OTHER](https://github.com/joomla/joomla-cms/issues/30896) even :) 

### Actual result

No feedback - except a console.log error message 

`SyntaxError: JSON Parse error: Unexpected EOF`

<img width="395" alt="Screenshot 2020-10-03 at 00 06 12" src="https://user-images.githubusercontent.com/400092/94976248-4167cc00-050c-11eb-9021-b3fbfc243fb5.png">

You can change the die() statment - lets output some text, make your /administrator/index.php be this now `<?php arghhhh ` and you will now get the more common error:

`SyntaxError: JSON Parse error: Unrecognized token '<'`

<img width="413" alt="Screenshot 2020-10-03 at 00 08 46" src="https://user-images.githubusercontent.com/400092/94976351-9efc1880-050c-11eb-9127-6ca045ffeb29.png">

### Additional Information 
There was a PR for [4.0] Remove AJAX for login #29571 ... which would make this issue null and void by removing ajax

**Comment by PhilETaylor** [comment]
This is almost a duplicate of https://github.com/joomla/joomla-cms/issues/27786 - we came to the same conclusion - proof that this issue has already causing " I spent two days trying to figure out what happened" type moments :)

**Comment by Fedik** [comment]
please check #30992

**Comment by alikon** [comment]
pleaset test #30992
