### ISSUE TITLE
[4][Accessibility] Increase font size + Highlight Links = creates horizontal layout issue

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30894]
### Steps to reproduce the issue

Login to Joomla 4 admin as your super admin and edit yourself in Users -> Manage

 administrator/index.php?option=com_users&view=users

Note that everything fits within the browser viewport.
<img width="1599" alt="Screenshot 2020-10-02 at 23 31 27" src="https://user-images.githubusercontent.com/400092/94974752-67d73880-0507-11eb-9c3d-9febd4bd58ba.png">

Enable Increase Font Size
Enable Highlight Links
(ok for giggles enable Monochrome and High Contrast too, but you can replicate without those enabled)
Save

You are now back at the Users list administrator/index.php?option=com_users&view=users

Note now that the table of users doesn't fit on the screen whereas it used to (it has some content off the screen to the right) 

<img width="1600" alt="Screenshot 2020-10-02 at 23 31 13" src="https://user-images.githubusercontent.com/400092/94974756-69a0fc00-0507-11eb-880b-403e593cdd14.png">

Also note that ALL OTHER COMPONENTS correctly fit within the browser width - its only the list of users in com_users that doest. 

Eg:
<img width="1599" alt="Screenshot 2020-10-02 at 23 32 30" src="https://user-images.githubusercontent.com/400092/94974805-92c18c80-0507-11eb-94fd-e1a047c7c2e6.png">

### Expected result

Enabling accessibility features should not make the page wider so that it floats outside the browser viewport, it should wrap in squeeze in, or do what the other views are doing correctly. 

### Actual result

As explained above

### System information (as much as possible)

Safari on mac

**Comment by chmst** [comment]
This independent of underlining links. 

It occurs only on the users view becaus there is no space to waste or compress.
Increasing the font size in the browser is correct and hides some columns.

The issue is caused by the accessibility plugin (as many other issues ...).

**Comment by PhilETaylor** [comment]
Im going to close this in favour of the new Table Options toggles.
