### ISSUE TITLE
[4][Media Manager] TypeError: undefined is not an object (evaluating 'this.$refs.actionToggle.focus')

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30891]
### Steps to reproduce the issue

Joomla4 admin -> Content -> Media 

(Check you are on the Images tab in the breadcrumbs, the top most folder, if you have been messing before).

Reload the page manually to ensure you are all JS loaded. 

Double click on "Banners" folder... hold mouse steady.... folder will load... move mouse = JS error logged.

TypeError: undefined is not an object (evaluating 'this.$refs.actionToggle.focus')

### Expected result

No console errors

### Actual result

TypeError: undefined is not an object (evaluating 'this.$refs.actionToggle.focus') each time. 
![Screen Recording 2020-10-02 at 11 01 57 pm](https://user-images.githubusercontent.com/400092/94973363-64da4900-0503-11eb-88d0-ff95613df531.gif)

<img width="698" alt="Screenshot 2020-10-02 at 22 57 03" src="https://user-images.githubusercontent.com/400092/94973297-32305080-0503-11eb-9a4c-84ec40dbe283.png">

### System information (as much as possible)

safari on mac

**Comment by richard67** [comment]
Closing as having a pull request. Please test #30917 .
