### ISSUE TITLE
[4] JLIB_JS_AJAX_ERROR_OTHER

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30896]
### Steps to reproduce the issue

Load your Joomla 4 admin login page at /administrator/

go and stop your web server.... 

try and login

### Expected result

A translated error message of some sort telling me something in "plain English" 

### Actual result

`JLIB_JS_AJAX_ERROR_OTHER`

<img width="879" alt="Screenshot 2020-10-02 at 23 58 07" src="https://user-images.githubusercontent.com/400092/94976001-6871ce00-050b-11eb-9573-b095c0a3797c.png">

Because **obviously** request failed because the web server is stopped. 

### System information (as much as possible)

safari on mac

**Comment by Quy** [comment]
Duplicate #30709

**Comment by PhilETaylor** [comment]
My report is better ;-) with steps to replicate and a screenshot :)

**Comment by zero-24** [comment]
I have just closed the other issue.

**Comment by infograf768** [comment]
We can get that one solved by adding
`Text::script('JLIB_JS_AJAX_ERROR_OTHER');` in `/administrator/templates/atum/login.php`

<img width="1156" alt="Screen Shot 2020-10-03 at 11 54 44" src="https://user-images.githubusercontent.com/869724/94988693-70fbf000-056f-11eb-878a-f5aeb8af77f7.png">

It may not be enough (see https://github.com/joomla/joomla-cms/issues/30709), but it works here.
Shall I make a patch?

**Comment by PhilETaylor** [comment]
> Shall I make a patch?

I need a T-shirt https://github.com/joomla/joomla-cms/pull/30909

**Comment by infograf768** [comment]
You will get your T-shirt ;)

**Comment by PhilETaylor** [comment]
No I won't. Due to the changes made to combat spam, **Joomla is no longer an "Ineligible Repository"** for Hacktoberfest 2020 because they have not added the "hacktoberfest" topic to the repository.

https://hacktoberfest.digitalocean.com/hacktoberfest-update
