### ISSUE TITLE
[4] Author Login Sample Data Link on 404 page in wrong position

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30893]
### Steps to reproduce the issue

previous history https://github.com/joomla/joomla-cms/issues/20372 was resolved, on all pages - except the 404 error page

Install Sample Data and then generate a 404

<img width="1237" alt="Screenshot 2020-10-02 at 23 21 12" src="https://user-images.githubusercontent.com/400092/94974291-fd71c880-0505-11eb-9407-18f04ddd83c0.png">

### Expected result

The author login remains bottom left like the main pages

### Actual result

The author login jumps to top right above main menu module and now has the up arrow again.

**Comment by chmst** [comment]
The error-page has been re-worked in the last days. If you are interested in this work in progress: you can find the repo here: https://github.com/joomla/cassiopeia
Your issues should be resolved there.

**Comment by PhilETaylor** [comment]
The joy of multiple repositories for a single monolithic project :-(
