### ISSUE TITLE
[4] Tags select box width breaks responsive design nature

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30895]
### Steps to reproduce the issue

Two ways - first is how I first saw it.

1) Users -> User Notes -> New -> +Create (Category) = Modal 

**Depending on your screen width and responsive breakpoint verses screen your results will differ.**

Screenshot taken on maximised browser on half the 27inch iMac screen. Approx Browser window size: 1600 x 1566 on Screen size: 3200 x 1800 - **I.e a HUGE SCREEN for a browser**

<img width="539" alt="Screenshot 2020-10-02 at 23 40 10" src="https://user-images.githubusercontent.com/400092/94975144-a0c3dd00-0508-11eb-9fa1-f0e417e0bce9.png">

2) This way is better for testing as you can "squeeze your browser" to different breakpoints to see the effect. The tags select box is much worse than the others and I think the only one that needs fixing.

Users -> User Notes Categories -> New 

![Screen Recording 2020-10-02 at 11 42 45 pm](https://user-images.githubusercontent.com/400092/94975271-129c2680-0509-11eb-9b1f-4974f8e59190.gif)

### Expected result

That layout is sensible for all responsive breakpoints, and when loaded in modal windows 

### Actual result

Described above. 

### System information (as much as possible)

Safari on Mac

**Comment by Quy** [comment]
Duplicate #27907

**Comment by PhilETaylor** [comment]
Ha my search skills are crap tonight... I never searched for "choices" :-)
