### ISSUE TITLE
[3.9] [4.0] Allow creating or renaming of .min.css files

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#30908]
### Is your feature request related to a problem? Please describe.
This applies to both J3.9x and J4B5. I haven't listed it as a bug as it's obviously been around for a while. 

There may be a good reason for it, but if you try to create or rename a file that contains two full stops (periods/dots) - e.g. oldfile.min.css - this is not possible within the "Templates: Customised (name of template)" area.

Instead, you get this message:

"Invalid file name. Please choose a file name with a-z, A-Z, 0-9, - and _."

Joomla 3x
![error-j3](https://user-images.githubusercontent.com/36987494/94990599-44e36d80-0575-11eb-9bf2-33d73f33b84b.jpg)

Joomla 4B
![error-j4](https://user-images.githubusercontent.com/36987494/94990601-4a40b800-0575-11eb-9cef-a9ed2aa28626.jpg)

The only way to amend or create files with this naming structure is to either amend it via the domain's control panel file manager or amend/upload them via FTP. It's quite likely that users with access to the file editor within Joomla may not have access to the domain's control panel or file manager or access via FTP.

**EDIT: It is possible to upload a file with a name such as newfile.min.css using the template editor upload facility:**
(But I also notice that the 'Close' button doesn't close the popup. Only X at top right or Esc key on keyboard works).

![upload-new-file](https://user-images.githubusercontent.com/36987494/94993197-3900a700-0587-11eb-8232-0041f3e029fb.jpg)

### Describe the solution you'd like
Allow the saving of file names with extra full stops within the Joomla editor.

**Comment by brianteeman** [comment]
This was originally put in place to address a security issue

**Comment by zero-24** [comment]
Do you have in mind what security issue @brianteeman ?

**Comment by brianteeman** [comment]
yes

**Comment by zero-24** [comment]
ok please send the details to me so i can have a look. maybe we find a way to still allow .min.css fieles

**Comment by SharkyKZ** [comment]
Duplicate https://github.com/joomla/joomla-cms/issues/26641.

**Comment by brianteeman** [comment]
Not related to that issue at all

**Comment by brianteeman** [comment]
@zero-24 did you have time to take a look

**Comment by brianteeman** [comment]
@joomla/security

**Comment by HLeithner** [comment]
I see no security reason to not allow . in the name in this case. maybe limit it to not the first character and not 2 dots after each other but in the end you can upload php files to every security here is only cosmetic.

Beside that it's maybe better to add .min.css and .min.js as extension, the template editor is for changing some template files so it has a limited scope and shouldn't be a full featured file manager (my opinion).

**Comment by brianteeman** [comment]
**It is a security issue.** It was addressed by the JSST at the time (2013 iirc) for some additional publicly available info see the comments here when a bug in that security fix was addressed https://github.com/joomla/joomla-cms/pull/2739#issuecomment-31332797

**Comment by HLeithner** [comment]
you can upload a .php file, now tell me that a . in the filename is a bigger security issue.

**Comment by brianteeman** [comment]
I dont debate security issues in public. The double file extension is a well known vulnerability.

**Comment by N6REJ** [comment]
so simple solution.  all abc.min.css abc.min.js etc.  not just any old abc.xyz.123

**Comment by brianteeman** [comment]
> so simple solution. all abc.min.css abc.min.js etc. not just any old abc.xyz.123

shakes head in dismay

**Comment by brianteeman** [comment]
Please test #38458

**Comment by brianteeman** [comment]
Please close as we have a pull request
