### ISSUE TITLE
[4.0] Installer doesn't work if root directory is not writeable

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#30916]
### Steps to reproduce the issue

make document root none writeable to the php process

### Expected result

Create the configuration.php and allow to download it

### Actual result

Error message with no continue button

![image](https://user-images.githubusercontent.com/1497730/95016907-5d778480-0656-11eb-93d9-4a03dd9fe5c2.png)

**Comment by PhilETaylor** [comment]
Duplicate for sure :) 

https://github.com/joomla/joomla-cms/issues/29618

https://github.com/joomla/joomla-cms/issues/20774

**Comment by HLeithner** [comment]
True ;) thanks
