### ISSUE TITLE
Warning: count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#30919]
### Steps to reproduce the issue
Turn up error reporting to development

### Expected result
No errors or warnings.

### Actual result
Warning: count(): Parameter must be an array or an object that implements Countable in /home/********/public_html/plugins/content/fields/fields.php on line 97

### System information (as much as possible)
[systeminfo-2020-10-04T21 15 16+01 00.txt](https://issues.joomla.org/uploads/1/d8e64117c7ac4defd911b012e29ae486.txt)

### Additional comments
PHP 7.3.22

**Comment by zero-24** [comment]
> Warning: count(): Parameter must be an array or an object that implements Countable in /home/******/public_html/plugins/content/fields/field

it seems the important part is missing from that message the filename and the line ;)

**Comment by uglyeoin** [comment]
> 
> 
> > Warning: count(): Parameter must be an array or an object that implements Countable in /home/******/public_html/plugins/content/fields/field
> 
> it seems the important part is missing from that message the filename and the line ;)

Yes, odd that I managed that!  I have corrected.

**Comment by zero-24** [comment]
hmm how did you trigger that message? Seems this is the case once here: https://github.com/joomla/joomla-cms/blob/staging/plugins/content/fields/fields.php#L95 the return from `FieldsHelper::extract($context);` is `NULL`

And that is only the case when the context is not correct as it looks like:
https://github.com/joomla/joomla-cms/blob/a80d9d9e63d44faea6ee1d57185769beea420b26/administrator/components/com_fields/helpers/fields.php#L41

**Comment by ceciogit** [comment]
hi @uglyeoin im tryin to replicate the issue without success. can u tell me where are you while this error comes up?
i am asking because i have maximum error reporting enabled but do not see this error anywhere.

**Comment by uglyeoin** [comment]
It turns out another component was calling the content which cause this issue.  I had turned it off but the other component was cached (Smart Slider 3).
