### ISSUE TITLE
FoF and PHP 8

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#30920]
FoF has an error on PHP 8 caused by incompatible function signature:

https://github.com/joomla/joomla-cms/blob/a80d9d9e63d44faea6ee1d57185769beea420b26/libraries/fof/layout/helper.php#L28

https://github.com/joomla/joomla-cms/blob/a80d9d9e63d44faea6ee1d57185769beea420b26/libraries/src/Layout/LayoutHelper.php#L65

If we add the missing argument, this fixes the error for us but classes extending `FOFLayoutHelper` remain broken unless they add it as well.

Another option is to break class inheritance and inline `Joomla\CMS\Layout\LayoutHelper` into `FOFLayoutHelper`. It's technically a B/C break but should be less painful.

**Comment by HLeithner** [comment]
Adding the parameter would be the proper way but since our FOF version is deprecated anyway and people have to migrate way from it (native or new version) it seems better for j3 to inline the debug function and remove the inheritance

**Comment by SharkyKZ** [comment]
Looking more into it, inlining could be problematic because of static `$defaultBasePath` property.

**Comment by HLeithner** [comment]
hmm that's true so we have to extend the parameter, it also is only a problem for extensions want to support php8 correct?

**Comment by SharkyKZ** [comment]
It causes an error only on PHP 8. On older versions it emits either a warning or strict standards notice.

**Comment by SharkyKZ** [comment]
Closing as having Pull Request https://github.com/joomla/joomla-cms/pull/30922.
