### ISSUE TITLE
[4.0] Intro-Image-float dont work

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#30924]
Issue of @gostn https://github.com/joomla/cassiopeia/issues/158 

### Steps to reproduce the issue

Add intro images in articles, use align left  / right . Then make a blog layout for these articles. 

### Expected result
Images are pulled left or right as in J3.

### Actual result
The float right/left of images is ignored in the blog containers.

**Comment by ciar4n** [comment]
As floated items are ignored on a flex item (https://www.w3.org/TR/css-flexbox-1/#ref-for-propdef-float), there is only 2 possible solutions..

1. Revert https://github.com/joomla/joomla-cms/pull/18319
2. Re-open https://github.com/joomla/joomla-cms/pull/17402

**Comment by adj9** [comment]
Setting the Arctic image to the right or left does not change what you see in the frontend. This on J4 connects to the standard template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30924">issues.joomla.org/tracker/joomla-cms/30924</a>.</sub>

**Comment by Quy** [comment]
Related #17399

**Comment by hans2103** [comment]
@ciar4n issue #17402 is your PR. Can you reopen it yourself?
Or copy all changes into a new PR?

I think it's a good idea to move the image to it's own JLayout. 
Doing so we can add extra options like lazyloading, wrapping it into a figure, adding figcaption.
Moving it to a JLayout will make my life as a frontender easier.

**Comment by ciar4n** [comment]
@hans2103 Done.. https://github.com/joomla/joomla-cms/pull/31017

**Comment by alikon** [comment]
please test #31017
