### ISSUE TITLE
[4.0] plg_authentication_gmail - phantom plugin

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30928]
### Steps to reproduce the issue
Upgrade joomla 3.10alpha to joomla 4beta

### Expected result
the gmail authentication plugin is removed

### Actual result
The files are gone but the record in #__extensions remains which results in

![image](https://user-images.githubusercontent.com/1296369/95116872-9ccdd000-073f-11eb-8186-781226b071d5.png)
![image](https://user-images.githubusercontent.com/1296369/95116909-a7886500-073f-11eb-9c86-3511121e41e3.png)

![image](https://user-images.githubusercontent.com/1296369/95115940-2f6d6f80-073e-11eb-9e61-70bd9883b2eb.png)

And attempting to _uninstall_ gives

![image](https://user-images.githubusercontent.com/1296369/95115986-414f1280-073e-11eb-8551-34d0394406e8.png)

**Comment by richard67** [comment]
Maybe just an update SQL script missing? Or was there some reason why it hasn't been added?

**Comment by richard67** [comment]
In opposite to the mod_search issue we can be sure that the gmail authentication plugin shall be removed, right?

**Comment by zero-24** [comment]
Well actually i'm not sure whether removing it on upgrading is a good idea given that some sites might use that plugin for auth? So by that upgrade we would keep that users out? We might need to revert the removal and do it similiar to com_weblinks and not fully remove / unistall it from the site.

**Comment by richard67** [comment]
Well, that's the other option. But can we be sure the old plugin continues to work on a J4?

**Comment by zero-24** [comment]
It would have to get its own update server maybe already in 3.10? And removed from the core extensions array. On a quick look i would say it should work on 4.x but i have not tested it to be fair.

**Comment by brianteeman** [comment]
It is correct that it is removed. I guess you forgot about

https://developer.joomla.org/news/724-removal-of-the-gmail-authentication-plugin-as-of-joomla-4-0.html

The bug is that while the files are removed the record in the extension table has not been removed.

**Comment by brianteeman** [comment]
That is why I wrote under expected result "the gmail authentication plugin is removed"

**Comment by richard67** [comment]
Am working on a PR for adding the SQL updates.

**Comment by zero-24** [comment]
> It is correct that it is removed. I guess you forgot about

Ups yes totally forgot that blogpost 👍

**Comment by richard67** [comment]
Closing as having a pull request. Please test #30941 .
