### ISSUE TITLE
[4.0] Webauthn button icon

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30936]
Currently you can not see the icon at all on the button on the admin login screen

![image](https://user-images.githubusercontent.com/1296369/95181789-a09f3800-07bb-11eb-94bc-c105711d6758.png)

This is a combination of
1. the image variant being used is webauthn-black.png
2. css inherited from the logo image `.view-login .login img`

And of course it would be better not as a 200px png (PR #30846) or an svg

**Comment by Quy** [comment]
See #29733

**Comment by jiweigert** [comment]
> And of course it would be better not as a 200px png (PR #30846) or an svg

I'm sure you meant 200kb file size, not 200px ... as you stated in the PR..<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30936">issues.joomla.org/tracker/joomla-cms/30936</a>.</sub>

**Comment by N6REJ** [comment]
duplicate #29733
