### ISSUE TITLE
[4.0] webauthn login button [a11y]

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#30937]
The icon that is supposed to be displayed on the webauthn button (when fixed to be visible see #30936 ) is a decorative image so should not have an alt description. Or at most an alt description that describes the image.

The current alt description for the image is `Login without a password using the W3C Web Authentication (WebAuthn) standard in compatible browsers. You need to have already set up WebAuthn authentication in your user profile.`

This is obviously not a description of the image and anyone using a screen reader has to listen to this very long message before they can proceed.

**Comment by Quy** [comment]
See #29734

**Comment by PhilETaylor** [comment]
The alt text has now been removed completely by someone somehow 

<img width="1109" alt="Screenshot 2021-01-12 at 23 11 13" src="https://user-images.githubusercontent.com/400092/104385631-80ee7d00-552b-11eb-965f-5f107804eaa1.png">

Probably when it was changed from a (huge) image to a SVG.
