### ISSUE TITLE
Joomla\CMS\WebAsset\WebAssetManager::addInline() issues

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#30933]
### What needs to be fixed

`Joomla\CMS\WebAsset\WebAssetManager::addInline()` is documented as accepting `WebAssetItem` (it should probably be `WebAssetItemInterface`) or string and has broken code for handling `WebAssetItem` but is typehinted to accept only `string`.

Also wrong type of exception is thrown (although code is currently unreachable).

**Comment by Fedik** [comment]
makes sense :) 
it need to remove typehint, as it for `registerAsset()`

**Comment by Fedik** [comment]
I just noticed, there one more issue, related to it.
I will make a patch when will get some time.

**Comment by Fedik** [comment]
please test #30986
