### ISSUE TITLE
Wrong manifest file on component update

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#30934]
### Steps to reproduce the issue
Update AcyMailing from a lower version than 6.15 to the version 6.16
This issue doesn't appear on every website

### Expected result
AcyMailing should be working

### Actual result
We have an error due to a folder that we rename in the administrator folder in which we have the router.
So the website is down

### System information (as much as possible)
Joomla 3 

### Additional comments
It looks like there is cache for the manifest file that we can't erase before the update

**Comment by zero-24** [comment]
Hmm there is a 'rebuild the manifest cache' button in the backend extension list? Does that fix the issue?

**Comment by ghost** [comment]
Well we can't access the website because there is a fatal error so we can't access to this button.

Maybe there is a way to erase this cache in the update script?

**Comment by zero-24** [comment]
we do this already but just for core extensions.

You can have a look into the /administator/components/com_admin/script.php line 381

**Comment by brianteeman** [comment]
@PhilETaylor is this resolved by your recent pr?

**Comment by PhilETaylor** [comment]
> This issue doesn't appear on every website

Does it only appear on servers that have opcache enabled or opcache configured with aggressive caching values ?

**Comment by brianteeman** [comment]
Sorry I meant the one that addresses the installer issues

**Comment by PhilETaylor** [comment]
No that [Joomla 3 PR was about extra_query](https://github.com/joomla/joomla-cms/pull/32862#) and installing extensions with Download IDs and the other was about [rebuilding the update sites](https://github.com/joomla/joomla-cms/pull/33040) cache

Both of those are already merged in Joomla 3.9.26 and r[eady for testing in the release candidate](https://github.com/joomla/joomla-cms/releases/tag/3.9.26-rc).

This reported issue sounds more like an opcache issue. There is a [Joomla 3 PR](https://github.com/joomla/joomla-cms/pull/32918) (which feels incomplete based on the massive effort on theJoomla 4 one of the same kind) which can be tested to see if it fixes this issue.

Else, there is not a lot to go on here. We need a better issue report with the error message and server configurations in order to fully ensure we replicate the correct issue.

**Comment by PhilETaylor** [comment]
@remiAcyba Please provide a direct link to " AcyMailing - a lower version than 6.15" and please provide the server configuration (from Joomla admin system information) that this problem happens on

**Comment by ghost** [comment]
Hi, 

Sorry for the late answer, here is AcyMailing stater 6.14.1.
For the Joomla configuration, I can't give you a precise one, you can take the default one.

The issue was with the folder library in the administrator/components/com_acym
We renamed it into libraries but some clients had issues because the folder didn't rename correctly.
[com_acymailing_starter.tar.gz](https://github.com/joomla/joomla-cms/files/6294572/com_acymailing_starter.tar.gz)

**Comment by ghost** [comment]
Hi again,

We just had another issue and I think this is also linked to the manifest cache.

We will soon release version 7.5.0 of AcyMailing and on the update we had an issue.

If you want to reproduce:
1 - Install version 7.4.1 
[starter_v7.4.1_2021-04-22_09-21-18.tar.gz](https://github.com/joomla/joomla-cms/files/6356314/starter_v7.4.1_2021-04-22_09-21-18.tar.gz)

2- Install our beta version for 7.5.0
[com_acymailing_starter.zip](https://github.com/joomla/joomla-cms/files/6356321/com_acymailing_starter.zip)
On the installation, you should have warnings about`ACYM_STARTER`, `ACYM_ESSENTIAL`, `ACYM_ENTERPRISE` constants not existing.

The thing is that they exist, we added them into our helper file in `back/helpers/helper.php`, which is include in the update file: `install.class.php`

Here is an example of the Joomla information on one of the site: 
![image](https://user-images.githubusercontent.com/27214405/115673441-ea610180-a34c-11eb-8a6e-91d9f1c6d0db.png)

**Comment by PhilETaylor** [comment]
Ive not tested yet, but surely if these new constants are in the NEW package you are just installing, they they will not yet be loaded until the next page load - unless you force them to be loaded manually before using them? - that's how Joomla works.

**Comment by PhilETaylor** [comment]
oh hang on - they are not LANGUAGE CONSTANTS but PHP define's.... 

Please provide your PHP Opcache Settings from PHP.ini

**Comment by PhilETaylor** [comment]
also please merge PR from https://github.com/joomla/joomla-cms/pull/32918 to your Joomla 3 site and test again - does that fix it?

**Comment by brianteeman** [comment]
This should be closed for the reasons stated above
