### ISSUE TITLE
An error has occurred while fetching the JSON data: HTTP 0 status code

### ISSUE THREAD

**Issue by no-matter-0** [joomla/joomla-cms#30940]
### Steps to reproduce the issue
New Joomla 4 beta 5 installed trying to login admin panel 

### Actual result

An error has occurred while fetching the JSON data: HTTP 0 status code.

### System information (as much as possible)

MAMP 5.7 on mac localhost server
mysql 5.7.26
php 7.4.2
browser Safari or Chrome = same error

### Additional comments

the super user was not created during install process
I created one with mysql  and add it to user group  8  , but I am still getting the same error

**Comment by no-matter-0** [comment]
The only JavaScript error I get is :failed to load resource : network connection lost

Joomla 3.x works perfectly

**Comment by PhilETaylor** [comment]
> Joomla 3.x works perfectly

This has nothing to do with Joomla 3 - AJAX Login was only added in Joomla 4

> The only JavaScript error I get is :failed to load resource : network connection lost

Then you are correctly receiving the right error message.

The other question I asked is "where it’s going"? What is the URL of your site, and what was the URL that the Ajax request went to - you can view this in the network inspector. Is your web server even still running for example.

**Comment by no-matter-0** [comment]
In the network inspector I get 
index.php in red
Domaine 192.168.178.51
Type xhr 

Same error if I change the domain for localhost

**Comment by no-matter-0** [comment]
It’s always failed to load the resource 
I have no idea what type xhr is

**Comment by PhilETaylor** [comment]
xhr is an Ajax request .. this is the correct type

I cannot replicate what you see, the message you get is correct because your request cannot load a valid response from your server.

**Comment by no-matter-0** [comment]
i have no idea what to do
Joomla 4 beta 3 was working

**Comment by no-matter-0** [comment]
but there is also a problem because the super user was not created during install process

**Comment by PhilETaylor** [comment]
Well the only [change I proposed that was merged](https://github.com/joomla/joomla-cms/pull/30909) was to translate the error message that you now get, the actual code remains the same as it was, except the error message is now translated.

**Comment by no-matter-0** [comment]
I cant login at all

**Comment by richard67** [comment]
@no-matter-0 Have you made a new installation like your issue description says? Or have you updated the Joomla 4 beta 3 which was was working to the new version? I ask because sometimes people write about installing when they mean to install an update.

And where did you find Joomla 4 Beta 5? The latest release was Joomla 4 Beta 4. Or did you install a nightly build, which currently has version 4 Beta 5**-dev**, which means "development on the way to Beta 5"?

**Comment by no-matter-0** [comment]
its a new J4 beta 5 downloaded yesterday  https://developer.joomla.org/nightly-builds.html

**Comment by richard67** [comment]
as i said it is bot a beta 5, it is a beta 5-dev!

And again: You have made a new installation of it, using the https://developer.joomla.org/nightlies/Joomla_4.0.0-beta5-dev-Development-Full_Package.zip ? Or have you made an update using the https://developer.joomla.org/nightlies/Joomla_4.0.0-beta5-dev-Development-Update_Package.zip ? You have not clearly answered that.

**Comment by no-matter-0** [comment]
Sorry but I repeat it now for the 3rd time it is a NEW installation  full package of course

**Comment by richard67** [comment]
Now it is clear. But it was not that clear before, that's why I had asked. After I had asked the first time, you only said where you had downloaded it from.

**Comment by no-matter-0** [comment]
I did  a new installation because the update didn't work, with and update I got a woop ! something went wrong message
therefore I started from the ground with a new one

**Comment by PhilETaylor** [comment]
I have spent over an hour looking at this now, and I cannot replicate that bug with the current cc1e81dd051da7e81dc431f885872667d6951c31

The error message is correct for the fact that you are reporting that the AJAX request failed to load resource with "network connection lost"

Maybe if you sent us some screenshots of your site (including the URL bar) and the console log and the network inspector with request/responses then I can make another guess.

**Comment by PhilETaylor** [comment]
Here is an example - can you send me a screenshot from your computer of this exact panel please. 

I made this screenshot by stopping my web server after installation and after loading the admin login page then trying to login knowing there was no web server running. 

<img width="1591" alt="Screenshot 2020-10-06 at 20 49 00" src="https://user-images.githubusercontent.com/400092/95252865-8134f900-0815-11eb-80c0-25cf4a945803.png">

**Comment by no-matter-0** [comment]
the final error is failed to load resource : network connection lost
but I do screenshots now

**Comment by no-matter-0** [comment]
url is http://192.168.178.51:8888/ymages.com/administrator/

**Comment by PhilETaylor** [comment]
but this is on your local machine? is the IP address correct? should it not be 127.0.0.1 ? maybe your web server is not listening on that IP or port ?

**Comment by no-matter-0** [comment]
https://ibb.co/9nLLCjX
https://ibb.co/cb3v0Yg

**Comment by no-matter-0** [comment]
my server works perfectly with joomla 3
and with 127.0.0.1:8888/ymages.com/administrator/ its exactly the same
I am using a true local ip to access my localhost from iphone or ipad too

**Comment by PhilETaylor** [comment]
Click on the red index.php to bring up the HEADERS tab please - and screenshot that.

**Comment by no-matter-0** [comment]
if i click on the red index I get
Résumé
URL: http://192.168.178.51:8888/ymages.com/administrator/index.php
État: —
Source: —

Demande
Content-Type: application/x-www-form-urlencoded
Accept: */*
Referer: http://192.168.178.51:8888/ymages.com/administrator/
Origin: http://192.168.178.51:8888
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15
X-Requested-With: XMLHttpRequest
X-Ajax-Engine: Joomla!
X-CSRF-Token: 05097adb1c594a39974e8264b2b57ec6

Réponse
Aucun en-tête de réponse = no answer

Données de la demande
Type MIME: application/x-www-form-urlencoded
format: json
username: web@ymages.com
passwd: xxxxxx
option: com_login
task: login
return: aW5kZXgucGhw
05097adb1c594a39974e8264b2b57ec6: 1

**Comment by PhilETaylor** [comment]
ok so what have I tested

 - custom port numbers (because that can cause cross origin issues)
 - using email address as a username (because @ in a url would cause issues sometimes)
 - installations in a sub folder (because bad base/routing could forget those)
 - non local IP addresses over LAN (to ensure its only working on localhost) 
 - accessing and login from iPhone over lan

And I cannot replicate your issue - sorry. 

The only thing I can suggest is blowing everything away and starting a new install from scratch. As you said, you had issues installing, which I never had either, so Im going to guess you have a corrupted install somehow.

**Comment by richard67** [comment]
Is there already an .htacess file in the Joomla root folder when installing? If so: Any special rules there?

**Comment by no-matter-0** [comment]
this is my 3rd install with current beta 5 with same results but maybe you are not on mac and MAMP , that could be the issue
ill try an install on my distant server

thanks anyway for your time

**Comment by PhilETaylor** [comment]
I am on a Mac. 

I don't use MAMP, I use a docker composed stack of independent containers and I have tested with Apache and NginX configurations based on the Joomla defaults for both.

**Comment by no-matter-0** [comment]
no htaccess , its htaccess.txt

but asI said it is not the only problem, when I installed there were no user at all , users table was empty

**Comment by no-matter-0** [comment]
ill try with beta 6 when it comes 
beta 3 was working

**Comment by PhilETaylor** [comment]
What are the exact version numbers of the stack in your MAMP ? (Apache PHP and Mysql version numbers)

**Comment by Fedik** [comment]
> HTTP 0 status code.

Sounds like PHP fatal error.

Before continue debugging make sure you have: error_reporting: E_ALL and display_errors: On

**Comment by no-matter-0** [comment]
MAMP 5.7  :
Apache 2.2.34
Nginx 1.13.2
MySQL 5.7.26
PHP 7.4.2
APC 3.1.13/APCu 4.0.11 & 5.1.18
eAccelerator 0.9.6.1
XCache 1.2.2 & 3.2.0
Xdebug 2.2.7, 2.4.1, 2.5.5 & 2.9.2
Perl 5.24.0
mod_perl 2.0.11
Python 2.7.13
mod_wsgi 3.5
mod_python 3.5.0
Ruby (with Rails) 2.3.7 (4.2.7)
phpMyAdmin 4.9.3
phpLiteAdmin 1.9.7-1
Freetype 2.6.5
OpenSSL 1.0.2o
t1lib 5.1.2
curl 7.65.1
jpeg 9b
libpng 1.6.27
tiff 4.0.6
Ghostscript 9.20
ImageMagick 6.9.6-2
Imagick 3.1.2 & 3.4.3
gd 2.2.3
zlib 1.2.8
ICU 56.1 (Unicode 8.0)
libXML2 2.9.4
libxslt 1.1.28
gettext 0.19.6
libidn 1.17
iconv 1.14
mcrypt 2.5.8
OAuth 1.2.3 & 2.0.4
YAZ 5.16.0 & PHP/YAZ 1.2.3

**Comment by PhilETaylor** [comment]
> Sounds like PHP fatal error.

No. If it were an error message or a 500 HTTP error then you would get [this different bug](https://github.com/joomla/joomla-cms/issues/30898):

<img width="434" alt="Screenshot 2020-10-06 at 21 33 50" src="https://user-images.githubusercontent.com/400092/95257089-b6444a00-081b-11eb-806c-8ed5b05cb6d8.png">

The `HTTP 0 status code.` means that the web server was dead, not responding at the url at all.

**Comment by no-matter-0** [comment]
they are on
error_reporting: E_ALL
display_errors: On

**Comment by no-matter-0** [comment]
my php logs are empty
but my apache logs
[Tue Oct 06 21:48:54 2020] [notice] Digest: generating secret for digest authentication ...
[Tue Oct 06 21:48:54 2020] [notice] Digest: done
[Tue Oct 06 21:48:54 2020] [notice] FastCGI: process manager initialized (pid 4307)
[Tue Oct 06 21:48:54 2020] [notice] Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.4.2 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.24.0 configured -- resuming normal operations
[Tue Oct 06 21:49:07 2020] [notice] child pid 4328 exit signal Illegal instruction (4)
[Tue Oct 06 21:49:28 2020] [notice] child pid 4335 exit signal Illegal instruction (4)
[Tue Oct 06 21:51:52 2020] [notice] child pid 4358 exit signal Illegal instruction (4)
[Tue Oct 06 21:53:39 2020] [notice] child pid 4418 exit signal Illegal instruction (4)
[Tue Oct 06 21:58:58 2020] [notice] child pid 4572 exit signal Illegal instruction (4)
[Tue Oct 06 22:01:04 2020] [notice] child pid 4611 exit signal Illegal instruction (4)
[Tue Oct 06 22:38:17 2020] [notice] caught SIGTERM, shutting down
[Tue Oct 06 22:38:32 2020] [notice] Digest: generating secret for digest authentication ...
[Tue Oct 06 22:38:32 2020] [notice] Digest: done
[Tue Oct 06 22:38:32 2020] [notice] FastCGI: process manager initialized (pid 5270)
[Tue Oct 06 22:38:32 2020] [notice] Apache/2.2.34 (Unix) mod_wsgi/3.5 Python/2.7.13 PHP/7.4.2 mod_ssl/2.2.34 OpenSSL/1.0.2o DAV/2 mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_perl/2.0.11 Perl/v5.24.0 configured -- resuming normal operations
[Tue Oct 06 22:38:51 2020] [notice] child pid 5274 exit signal Illegal instruction (4)

**Comment by PhilETaylor** [comment]
<img width="987" alt="Screenshot 2020-10-06 at 21 39 39" src="https://user-images.githubusercontent.com/400092/95257601-75990080-081c-11eb-8e1d-46a3a6a1e1f6.png">

I have just install MAMP from scratch, installed nightly, and set up Joomla with no errors - and then I can login with no errors either...

**Comment by no-matter-0** [comment]
If I try to login in frontend i get Safari cannot open the page because the server closed the connexion

**Comment by PhilETaylor** [comment]
> If I try to login in frontend i get Safari cannot open the page because the server closed the connexion

And there we have it. Your server is crashing. This is not a Joomla issue. This is what would cause a `HTTP 0 status code.`

**Comment by PhilETaylor** [comment]
In MAMP switch to nginx and see if that works instead of Apache.

**Comment by richard67** [comment]
Yes, server log clearly shoes server crash and restart.

**Comment by no-matter-0** [comment]
PhilETaylor  thats crazy if you can install it on MAMP  with same config ? php 7.4.2 ?

**Comment by PhilETaylor** [comment]
Im on macOS Big Sur though... I was actually surprised MAMP worked at all on this hahahaha - yes 7.4.2

**Comment by no-matter-0** [comment]
with nginx I get An error has occurred while fetching the JSON data: HTTP 502 status code. Bad Gateway
and i cant login

**Comment by PhilETaylor** [comment]
502 bad gateway normally means nginx had issues talking to PHP - which, if PHP is crashing on your machine, would be the underlying issue. 

Downgrade the PHP to the other version supplied by MAMP and try that with apache and nginx on your machine

**Comment by richard67** [comment]
Does that fit somehow? [https://unix.stackexchange.com/questions/253465/php-app-crashes-child-pid-exits-with-illegal-instruction-4](https://unix.stackexchange.com/questions/253465/php-app-crashes-child-pid-exits-with-illegal-instruction-4)

**Comment by richard67** [comment]
It sais:
> This is caused by the last update from CentOS for the nss package. It also caused apache to panic. Here are the steps to downgrade the package:

**Comment by richard67** [comment]
Ok, I know it's not CentOS, but the rest seems to fit.

**Comment by no-matter-0** [comment]
with apache and php 7.3.9 it WORKS !!!!

**Comment by no-matter-0** [comment]
thats a problem at least on my mac pro with php 7.4.2

**Comment by PhilETaylor** [comment]
well Im pleased we got to the bottom of it. 7.4.2 is quite old now anyway with the latest being 7.4.11 :)

**Comment by richard67** [comment]
@no-matter-0 So it's clear now it's a server setup and not a Joomla CMS issue? If so, could you close this issue at the end? Thanks in advance.

**Comment by no-matter-0** [comment]
thanks a ton !

**Comment by no-matter-0** [comment]
how do i close it ?

**Comment by richard67** [comment]
Button "Close with comment" at the bottom of the issue on github .. it just needs to enter come comment.

**Comment by richard67** [comment]
Thanks @PhilETaylor for having analysed this issue. It's not true that we all hate you 😉 .

**Comment by PhilETaylor** [comment]
To be honest, I was more worried [that my latest merged PR](https://github.com/joomla/joomla-cms/pull/30909), which was related to this exact error message, screwed something up and I have the professional integrity to ensure that was not the case haha

**Comment by richard67** [comment]
That is what always happens to me when I have done some PR for database and some issues come up with updating, and I feel same responsible in those cases even if it was not me at the end.
