### ISSUE TITLE
Bootstrap 5 alpha2

### ISSUE THREAD

**Issue by 1337180** [joomla/joomla-cms#30942]
### Steps to reproduce the issue
download
https://blog.getbootstrap.com/2020/09/29/bootstrap-5-alpha-2/

### Expected result
minor rewrite because of bootstrap 5 own javascript

### Actual result
bootstrap 5 from beggining to end of life.

### System information (as much as possible)
Joomla! 4 beta 5

### Additional comments
please be mindfull

**Comment by HLeithner** [comment]
Duplicate of #30805
