### ISSUE TITLE
_QQ_ do not work

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#30943]
### Steps to reproduce the issue

use the _QQ_ string in a language file to write a double quote

### Expected result

a double quote

### Actual result

_QQ_ is rendered like this, instead of a double quote

### System information (as much as possible)

Joomla 4 beta 4

**Comment by Quy** [comment]
See #19030. Please post your string to review.

**Comment by brianteeman** [comment]
Also see https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#Language

**Comment by ced1870** [comment]
thank you Brian, I did not notice that. Closed for me 👍

**Comment by zero-24** [comment]
Closing as requested
