### ISSUE TITLE
[4][iPhone] Article Status Text Unreadable 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30948]
### Steps to reproduce the issue

Navigate to the Add Article page on a Joomla 4 site while using an iPhone 11 Safari in Portrait mode running iOS 14

### Expected result

<img width="519" alt="Screenshot 2020-10-06 at 22 23 23" src="https://user-images.githubusercontent.com/400092/95261587-919fa080-0822-11eb-904a-d6936359416a.png">

### Actual result

![IMG_2246](https://user-images.githubusercontent.com/400092/95261457-5604d680-0822-11eb-821c-47fb3c586e87.PNG)

### System information (as much as possible)

 iPhone 11 Safari in Portrait mode running iOS 14

**Comment by PhilETaylor** [comment]
![Uploading Screenshot 2020-10-06 at 22.52.08.png…]()

**Comment by PhilETaylor** [comment]
<img width="555" alt="Screenshot 2020-10-06 at 22 52 28" src="https://user-images.githubusercontent.com/400092/95264032-9f572500-0826-11eb-9712-b4d95af76b22.png">

**Comment by N6REJ** [comment]
PR created https://github.com/joomla-projects/custom-elements/pull/147

**Comment by brianteeman** [comment]
I dont have an iphone but testing with an emulator for all iphones I am unable to replicate this. Perhaps it has been resolved elsewhere?

**Comment by N6REJ** [comment]
@brianteeman not afaik.. I can retest but until custom-elements does the fix I doubt its resolved.

**Comment by brianteeman** [comment]
Can you still replicate the issue because I cannot with an iPhone emulator?

**Comment by brianteeman** [comment]
Can someone please test with an iphone and see if this is still an issue. None of the emulators I have tried have a problem. No point keeping this open if its no longer reproducable

**Comment by PhilETaylor** [comment]
I just bought a brand new iPhone 12 today, as soon as the software update is done I'll test this again

**Comment by PhilETaylor** [comment]
This issue seems to be resolved. 

However in testing this I found 3 other issues :-(
