### ISSUE TITLE
[4][Mail Templates] Save failed with the following error: Data too long for column 'language' at row 1

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30957]
### Steps to reproduce the issue

Edit a Mail Template in Joomla 4 admin

Change the language code manually in the URL 

Eg

http://example.com/administrator/index.php?option=com_mails&view=template&layout=edit&template_id=plg_user_joomla.mail&language=en-GBfrerferferferferf

Click save

### Expected result

Input validation on the language code before it gets anywhere near a mysql query

### Actual result

`Save failed with the following error: Data too long for column 'language' at row 1`

<img width="930" alt="Screenshot 2020-10-07 at 00 23 56" src="https://user-images.githubusercontent.com/400092/95270443-66717d00-0833-11eb-9dfd-379aafe88d2c.png">

### Additional Information

If you use `&language=A` the mail template saves - this also should be stopped, as A is not a valid input for language code! And this is persisted to the database! 

<img width="420" alt="Screenshot 2020-10-07 at 00 25 36" src="https://user-images.githubusercontent.com/400092/95270559-a89abe80-0833-11eb-91e0-f6c406d9cbaa.png">

**Comment by brianteeman** [comment]
data validation issues again

**Comment by wilsonge** [comment]
PR https://github.com/joomla/joomla-cms/pull/31835
