### ISSUE TITLE
[4] Who edits a file with just 20 lines showing?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30955]
### Steps to reproduce the issue

Edit a file in Joomla 4 template manager

### Expected result

A useable editing experience
A drag-to-resize textarea? or just a lot more lines than 20! 

### Actual result

20 lines of code max.... 

<img width="1600" alt="Screenshot 2020-10-07 at 00 05 57" src="https://user-images.githubusercontent.com/400092/95269227-e5b18180-0830-11eb-92ff-8ef64d77832e.png">

<img width="1595" alt="Screenshot 2020-10-07 at 00 06 58" src="https://user-images.githubusercontent.com/400092/95269299-0974c780-0831-11eb-9300-7031a66e5ab8.png">

### System information (as much as possible)

safari on Mac

**Comment by brianteeman** [comment]
Agreed!!

**Comment by brianteeman** [comment]
Please test #30990
