### ISSUE TITLE
[4] FileSystem-local plugin allows saving of -None Selected-

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30958]
### Steps to reproduce the issue

in Joomla 4 edit the plugin `FileSystem - Local`

Add multiple folders and select a few ` - None Selected -` from the drop down

Save

### Expected result

The  ` - None Selected -`  are removed from the list

### Actual result

Saved 

<img width="1176" alt="Screenshot 2020-10-07 at 00 35 38" src="https://user-images.githubusercontent.com/400092/95271224-3dea8280-0835-11eb-85d4-49ba0b9f1d63.png">

which then gives an error if trying to use media manager:

<img width="914" alt="Screenshot 2020-10-07 at 00 38 30" src="https://user-images.githubusercontent.com/400092/95271304-75f1c580-0835-11eb-9e8e-9578c99b9304.png">

**Comment by brianteeman** [comment]
another validation issue :(

**Comment by Quy** [comment]
PR #30987
