### ISSUE TITLE
[4] Return to dashboard link wrong

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30952]
### Steps to reproduce the issue

Generate an error - use https://github.com/joomla/joomla-cms/issues/30951 until that one is resolved.

Note that my site is installed at `http://127.0.0.1:4444/`

Note that this error page's URL is `http://127.0.0.1:4444/administrator/index.php?option=com_media&task=file.edit&id=0`

Note the error page is this:

<img width="704" alt="Screenshot 2020-10-06 at 23 13 09" src="https://user-images.githubusercontent.com/400092/95265652-84d27b00-0829-11eb-9eea-fc79b17c3943.png">

Click on `Return to dashboard` button

### Expected result

Returns me to "Home Dashboard" at URL `http://127.0.0.1:4444/administrator/`

### Actual result

I am returned to `http://127.0.0.1/administrator/` which doesn't work as my server is on port 4444

html is

```html
<div class="col-md-12">
					<h1>An error has occurred.</h1>
					<blockquote class="blockquote">
						<span class="badge badge-secondary">0</span>
						Invalid controller class: file					</blockquote>
										<p>
						<a href="/administrator" class="btn btn-secondary">
							<span class="fas fa-dashboard" aria-hidden="true"></span>
							Return to Dashboard</a>
					</p>
				</div>
```

### System information (as much as possible)

safari on Mac

**Comment by brianteeman** [comment]
Please test #31032

**Comment by brianteeman** [comment]
I closed the pr as I realised it was working exactly the same with the pr. AND I am unable to replicate the problem at all

![404](https://user-images.githubusercontent.com/1296369/95654595-e5e3a280-0af8-11eb-8325-e8938634777a.gif)

**Comment by PhilETaylor** [comment]
is it because you are in a sub folder too ?

**Comment by PhilETaylor** [comment]
broken for me in a subfolder too :(

**Comment by PhilETaylor** [comment]
What is the HTML markup of your button when it is rendered please?

**Comment by PhilETaylor** [comment]
**So Im happy to accept that this is no longer an issue.** 

ok I think this is a caching issue - a very very strange one. 

What happens when you click on the button is a relative navigation to "/administrator" WITH NO TRAILING slash.

In my network inspector I see it CORRECTLY navigates to http://127.0.0.1:4444/subfolder/administrator and then that responds with a 301 Redirect to http://127.0.0.1/subfolder/administrator/ INCORRECTLY.

What is more crazy is that the 301 Redirect is CACHED and being served from "disk cache" even though I have the network inspector open and Disable Cache enabled in the browser. 

Why on earth there would be - ON TWO DIFFERENT MACS - a "disk cached" redirect from http://127.0.0.1:4444/subfolder/administrator to http://127.0.0.1/subfolder/administrator/ is beyond me at the moment.

Also why it would also not work on other port numbers too is beyond me. 

And also why it does it in Firefox, THAT I ONLY DOWNLOADED TODAY is again beyond me. 

So Im happy to accept that this is no longer an issue. 

Sorry for wasting your time. 

This could also be a nginx issue: https://serverfault.com/questions/351212/nginx-redirects-to-port-8080-when-accessing-url-without-slash in reverse, although this person says its a browser issue and has been reported in chrome https://github.com/d3/d3-request/issues/28
