### ISSUE TITLE
[Action logs] Invalid controller class: file

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30951]
### Steps to reproduce the issue

upload some media using media manager in Joomla 4

navigate to the "Home Dashboard"

Note the latest actions:

<img width="654" alt="Screenshot 2020-10-06 at 23 11 31" src="https://user-images.githubusercontent.com/400092/95265543-4b017480-0829-11eb-981b-d7dee682b352.png">

Click on the Image name 

### Expected result

View an image? 

### Actual result

url is http://example.com/administrator/index.php?option=com_media&task=file.edit&id=0

```
An error has occurred.
0 Invalid controller class: file
```
<img width="629" alt="Screenshot 2020-10-06 at 23 11 57" src="https://user-images.githubusercontent.com/400092/95265571-58b6fa00-0829-11eb-86fa-caa6843a1928.png">

**Comment by wilsonge** [comment]
I've removed J4 from the title as it's equally applicable on j3

**Comment by wilsonge** [comment]
Fix https://github.com/joomla/joomla-cms/pull/31836
