### ISSUE TITLE
[4] Undefined offset when manipulating admin urls in Mail Templates

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30956]
### Steps to reproduce the issue

Fake url after login to Joomla admin

example.com/administrator/index.php?option=com_mails&view=template&layout=edit&template_id=NOSUCH&language=en-GB

### Expected result

404 Error
and/or
No PHP Notices

### Actual result

Notice: Undefined offset: 1 in /application/administrator/components/com_mails/src/View/Template/HtmlView.php on line 86

Notice: Undefined offset: 1 in /application/administrator/components/com_mails/tmpl/template/edit.php on line 31

<img width="1067" alt="Screenshot 2020-10-07 at 00 20 51" src="https://user-images.githubusercontent.com/400092/95270209-f7942400-0832-11eb-870e-e01c0858a830.png">

**Comment by wilsonge** [comment]
Fix here https://github.com/joomla/joomla-cms/pull/31699
