### ISSUE TITLE
[4][mobile] Mail Templates Needs Mobile Review

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30950]
### Steps to reproduce the issue

Visit com administrator/index.php?option=com_mails&view=templates on a mobile device

### Expected result

like the rest of Joomla 4, nicely laid out and responsive to the screen size 

### Actual result

unresponsive table 

![Screen Recording 2020-10-06 at 11 08 14 pm](https://user-images.githubusercontent.com/400092/95265322-e0e8cf80-0828-11eb-989e-fe6987fcb8c0.gif)

**Comment by brianteeman** [comment]
Please test #31823
