### ISSUE TITLE
[4] No de-duplication of force headers in System - HTTP Headers Plugin

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30962]
### Steps to reproduce the issue

Joomla 4
Edit the `System - HTTP Headers` plugin

Click Green + button several times
Ensure all of the headers are the same (you can leave them at Content-Security-Policy if you like) 
Click Save and Close

### Expected result

Either de-duplication or a validation error because its insane to reconfigure a header twice as the headers can/should only be output once. 

### Actual result

GIGO. It saves without deduplication

<img width="1228" alt="Screenshot 2020-10-07 at 01 04 35" src="https://user-images.githubusercontent.com/400092/95272746-15648780-0839-11eb-95cc-9195b766a919.png">

The header with `ONE` as a value is overwritten and not output (correctly) 

<img width="592" alt="Screenshot 2020-10-07 at 01 04 01" src="https://user-images.githubusercontent.com/400092/95272735-0da4e300-0839-11eb-86e6-0a9868ddbdd8.png">

**Comment by zero-24** [comment]
Agree will look into it. What can also happen is that the server sets some headers on the server level like htaccess or the config file of nginx that could result into dublicate headers.

**Comment by PhilETaylor** [comment]
I accept that, but that's beyond joomlas control.

**Comment by zero-24** [comment]
Agree but will look into the issue reported here.

**Comment by zero-24** [comment]
@PhilETaylor please check this PR as a first step: https://github.com/joomla/joomla-cms/pull/31128

**Comment by brianteeman** [comment]
as #31128 was merged what is left to do here?

**Comment by PhilETaylor** [comment]
Closing
