### ISSUE TITLE
[4] Extension - Namespace Updater can be disabled.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30964]
### Steps to reproduce the issue

In Joomla 4 the `Extension - Namespace Updater` plugin has text:

`Warning! This plugin must be enabled as it runs on extension install, update and deletion.`

However it is totally possible to disabled it ! :-) 

<img width="1197" alt="Screenshot 2020-10-07 at 01 21 30" src="https://user-images.githubusercontent.com/400092/95273634-742b0080-083b-11eb-9350-8203f2b2b7e1.png">

### Expected result

In ability to disable this plugin like it states, or better language that explains what will happen if its disabled and why that's bad enough to scare me to never disable it (also noting that I could disable it in the plugin list view with a single click and never see this warning!)

### Actual result

This plugin can be disabled.

**Comment by brianteeman** [comment]
Not really any different to authentication plugins

**Comment by PhilETaylor** [comment]
Authentication plugins are designed to be enabled or disabled at the will of the site admin. They are optional plugins. 

This `Namespace Updater plugin`, by its own admission, is designed never to be disabled.

**Comment by richard67** [comment]
@wilsonge Is it true? Has this plugin to be always enabled? If so, I can make a PR to fix the "protected" value for that plugin. Or is just that text wrong and in fact it CAN be disabled when only using namespaced extensions?

**Comment by zero-24** [comment]
> Is it true? Has this plugin to be always enabled? If so, I can make a PR to fix the "protected" value for that plugin. Or is just that text wrong and in fact it CAN be disabled when only using namespaced extensions?

I would say go with the protected step for now as this seems to be required even for namespaced extensions.

**Comment by brianteeman** [comment]
Sorry to clarify - with the authentication plugins there is a similar message warning you that you must have one authentication plugin enabled. I assumed that it would be the same here that a user might want/need to use a different namespace plugin

> I would say go with the protected step for now as this seems to be required even for namespaced extensions.

Really? My quick test doesnt have any problem with it disabled

**Comment by zero-24** [comment]
> Really? My quick test doesnt have any problem with it disabled

Have you installed an extension that uses its own namespaces?

> Sorry to clarify - with the authentication plugins there is a similar message warning you that you must have one authentication plugin enabled. I assumed that it would be the same here that a user might want/need to use a different namespace plugin

hmm I hardly see anyone using a different namespace update plugin.

**Comment by richard67** [comment]
> Sorry to clarify - with the authentication plugins there is a similar message warning you that you must have one authentication plugin enabled.

A "one of n" rule for "enabled" we can't force with the "protected" column of the extensions table in database.

**Comment by richard67** [comment]
My knowledge on namespace mapping is too little, so I wait for instructions. I am the database guy who can make the necessary SQL. But I'd prefer to have feedback from @wilsonge .

**Comment by brianteeman** [comment]
Daft question perhaps but if this has no options and it must always be enabled why is it even a plugin

**Comment by zero-24** [comment]
I agree seems @yvesh had the same idea in the intial version too:

> As when the plugin is not enabled this can break the entire site, we should reevaluate protecting plugins / extensions OR move it to the installer etc.

https://github.com/joomla/joomla-cms/pull/16403

**Comment by wilsonge** [comment]
I did consider just hard adding this into the events system to be honest. But generally most people prefer an approach of having customisation.

As mentioned this plugin is basically responsible for regenerating the namespace map files when extensions using namespaces (there will only be a few to start with I assume) are installed/updated. If extensions rely on autoupdating then this plugin needs to exist.

**Comment by PhilETaylor** [comment]
The plugin can still be disabled today, however, even when disabled, if the autoload_psr4.php is deleted, Joomla will still regenerate it on first page load - and not crash the site as it used to.

The ability then to disable the plugin is correct - and a configurable part of Joomla - that allows an admin to control if the mapping is updated on install/uninstall of extensions. 

Of course you would be mad to disable it - but the option is there - what has been fixed since this issue was open, was the complete crashing of the site if autoload_psr4.php was not available, now, Joomla silently recreates it on first page load.
