### ISSUE TITLE
[4] Content Security Policy not catching googleapis

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30963]
### Steps to reproduce the issue

Joomla 4 with sample blog content installed
Enable com_csp with settings: 

<img width="958" alt="Screenshot 2020-10-07 at 13 12 07" src="https://user-images.githubusercontent.com/400092/95329361-b89bb800-089e-11eb-82ac-12081fb2a114.png">

Browse the frontend of the site a bit
Login to the frontend and edit an article
Browse the admin console of the site a bit

Return to com_csp - this gives us 9 reports - publish them all **(because a user doesnt understand what hes doing and just wants it to work)**

<img width="1262" alt="Screenshot 2020-10-07 at 13 14 06" src="https://user-images.githubusercontent.com/400092/95329581-13351400-089f-11eb-934c-a64a0d2fef76.png">

Click Options
Set mode to Automatic
Set Report-Only to no
Save

Now I cannot even run JS on the page :) 

```
Content-Security-Policy: default-src 'self' 'self' data; frame-ancestors 'self' ; default-src 'self' ; script-src 'self' 'nonce-YjE3NWEyMmYzYTM3YjNjZjYzNmZmYWNmYTQyNTA2ZmRlOGJjOTAxMDVkNDJmMTFhYmRmNWVjZDdlN2MwZTllNzA0YThmYjdjODUwM2EwYTRlZjVlY2ZkZTE0NDRkMDNjZDg0NWVlZjI3M2QzZmFkYjNjYjYyOTc1NWU0MzQxNDk='; style-src 'self' 'nonce-YjE3NWEyMmYzYTM3YjNjZjYzNmZmYWNmYTQyNTA2ZmRlOGJjOTAxMDVkNDJmMTFhYmRmNWVjZDdlN2MwZTllNzA0YThmYjdjODUwM2EwYTRlZjVlY2ZkZTE0NDRkMDNjZDg0NWVlZjI3M2QzZmFkYjNjYjYyOTc1NWU0MzQxNDk='
```

<img width="1600" alt="Screenshot 2020-10-07 at 13 18 12" src="https://user-images.githubusercontent.com/400092/95329880-90608900-089f-11eb-8d39-5a22ec6b5316.png">

**Comment by zero-24** [comment]
Hmm that generated header looks strange can you show me the list of aproved reports from com_csp?

**Comment by PhilETaylor** [comment]
I have updated the issue... I screwed it good and proper this time haha

Im guessing you are not meant to just publish enable all the reports :-) but thinking like a user, that is what people will do.

There is also no way now to "disable" the header because the admin console cannot work with no JS 

Maybe a plain HTML rescue button would be a good idea..

Anyway, Im not sure this is a valid issue that needs fixing. More a "I broke it by acting like a user"....

**Comment by PhilETaylor** [comment]
Actually I can get to options to disable it, but I cannot click the circles to unpublished reports until I disable the header.

**Comment by zero-24** [comment]
> Actually I can get to options to disable it, but I cannot click the circles to unpublished reports until I disable the header. 

By Default the backend should not be affected by the headers as the default is site only. Have you changed that option?

Please re open here so we can keep track of the issue. That component is far from perfekt and your feedback and tests are very good so we can see and discuss how and where to improve.

**Comment by zero-24** [comment]
@PhilETaylor can we please follow up on this one and re open here sonwe can start identifing and fixing the problems reported here?

**Comment by PhilETaylor** [comment]
I was waiting until I had time to revisit and replicate and redocument this issue which I still have not had time to do. Reopening now anyway.

**Comment by zero-24** [comment]
Great. Thanks and no need to hurry i just wanted it reopen and you on board that it does not get lost. The replicate and redocument steps would be great so we can also see what settings you had etc. But again no need to hurry on this. :+1:

**Comment by PhilETaylor** [comment]
Maybe its just me not understanding what "detect" mode is meant to be doing.

Im assuming that if I enabled "detect" mode and go and browse around the site, the site will ping the reporting URL with every asset that would have been blocked, and which needs to be whitelisted in the CSP - and then I can just visit the rules and publish them all to get a decent CSP ... that's what a user would do Im pretty sure. 

Here is a video: https://www.youtube.com/watch?v=RTi_ahlFbjc

Also note towards the end of the video where the SVG for the green "Configuration saved" message should be is not there.

<img width="313" alt="Screenshot 2020-10-08 at 21 56 17" src="https://user-images.githubusercontent.com/400092/95514018-289b6280-09b3-11eb-8f18-01c371157ba4.png">

**Comment by zero-24** [comment]
Please check: https://github.com/joomla/joomla-cms/pull/31132 and thanks for that video it helped a lot to understand and see the issue with Safari vs Chrome :D

**Comment by zero-24** [comment]
> Im assuming that if I enabled "detect" mode and go and browse around the site, the site will ping the reporting URL with every asset that would have been blocked, and which needs to be whitelisted in the CSP - and then I can just visit the rules and publish them all to get a decent CSP ... that's what a user would do Im pretty sure.

Just to confirm yes that is the intended process. But in this case the directive passed to the reporter was not vanilla but also included more stuff than intended so that caused some issues.

**Comment by zero-24** [comment]
I have now also added a special handling for data reports to that PR too. So for now i would like to close here in reference to the PR mention. Thanks!
