### ISSUE TITLE
[4][com_finder] COM_FINDER_MAPS_N_ITEMS_FAILED_PUBLISHING

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30965]
### Steps to reproduce the issue

Install Joomla 4 
INSTALL "Blog Sample Data"
Navigate to Components -> Smart Search -> Content Maps
Select all 
Click Actions
Click unpublish - Note: `10 maps unpublished.`
Select all 
Click Actions
Click publish 

### Expected result

`10 maps published`

### Actual result

Untranslated `COM_FINDER_MAPS_N_ITEMS_FAILED_PUBLISHING` error message and nothing published

Also note now clicking on a red X, I cannot publish one at a time either - same untranslated  error

<img width="767" alt="Screenshot 2020-10-07 at 01 24 35" src="https://user-images.githubusercontent.com/400092/95273984-79d51600-083c-11eb-9da1-481b6fab2eae.png">

**Comment by brianteeman** [comment]
Cant confirm the exact error you got but I can 100% confirm that there is a problem and it would appear to relate to the publishing of second level items happening before the publishing of first level items - and I can confirm the untranslated error

**Comment by infograf768** [comment]
> it would appear to relate to the publishing of second level items happening before the publishing of first level items

Confirmed.

**Comment by brianteeman** [comment]
Please see #31393 for a pull request fixing the untranslated strings only

**Comment by Hackwar** [comment]
This should be fixed (more or less) with #33885

**Comment by PhilETaylor** [comment]
thanks
