### ISSUE TITLE
[4][com_finder] Enabling statistics and empty search gives false results

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30967]
### Steps to reproduce the issue

Install Joomla4
Install blog sample data
Login to admin
Components->SmartSearch->Index->index button
Components->SmartSearch->Statistics->options button
Enable: Gather Search Statistics
Enable: Allow empty search (IM ASSUMING THIS MEANS: You can search for "")

Navigate to a search box on the frontend of your site

http://example.com/index.php/component/finder/search

search for "PhilTaylor"

### Expected result

No results because PhilTaylor is not talked about in your content items. 

### Actual result

<img width="879" alt="Screenshot 2020-10-07 at 01 45 48" src="https://user-images.githubusercontent.com/400092/95274860-d76a6200-083e-11eb-8bf5-54e9f7f61ce3.png">

**Comment by brianteeman** [comment]
I am assuming that the name of the user admin is Phil Taylor

The author is part of the taxonomy in smart search. To confirm this go to the smart seach component and check the content maps. You should see a map entry for Phil Taylor with a parent of author.

(not saying its right or wrong to just explaining how smart search works)

**Comment by PhilETaylor** [comment]
You assume wrong. My admin usernames "name" is also "admin"

"PhilTaylor" exists no where in my database. It's not a users name, alias, or otherwise used at all on the site. It was just a poor illustration of a generic text string. Sorry if it's use deflected from the actual bug. 

You can replicate the reported by searching with any random text string you like as long as it's a single word without spaces

**Comment by brianteeman** [comment]
In that case I can not confirm your findings

![image](https://user-images.githubusercontent.com/1296369/95324929-5f308a80-0898-11eb-8646-7094befc1d76.png)

**Comment by PhilETaylor** [comment]
Well now Im in the office, so totally different machine in a totally different location, I follow the instructions to the letter in the opening post of this issue and I can still replicate the issue on this iMac too. 

(dockerised)  mysql 5.7 version just in case that makes a difference. 

Video from installing :  https://screenshot.phil-taylor.com/4guJmyXp

<img width="914" alt="Screenshot 2020-10-07 at 12 48 56" src="https://user-images.githubusercontent.com/400092/95327120-7b81f680-089b-11eb-8f0f-6d0dfa6a9011.png">

**Comment by brianteeman** [comment]
> Enable: Allow empty search 

Sorry I missed that part. That is the key to replicating the bug

> (IM ASSUMING THIS MEANS: You can search for "")

From memory its related to using the advanced search filters without a search term. But clearly its not working at all

**Comment by Hackwar** [comment]
Here is a fix: #31040
