### ISSUE TITLE
[4][com_finder] Expand all closes first accordion level

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30966]
### Steps to reproduce the issue

Joomla 4 -> install blog sample data
Index your content with Smart search 
publish all your maps
Create a new Smart Search Filter 
Click Expand all button 

### Expected result

All accordion panels open

### Actual result

First panel closes
The rest open

![Screen Recording 2020-10-07 at 01 34 13 am](https://user-images.githubusercontent.com/400092/95274299-4d6dc980-083d-11eb-9a1f-84f6cc9f5f17.gif)

**Comment by Hackwar** [comment]
Here is your fix: #31073
