### ISSUE TITLE
[4.0] WebAssets where to register and use with respect to the system plugin events.

### ISSUE THREAD

**Issue by ahamed** [joomla/joomla-cms#30976]
### Problem identified
I have a system plugin. Previously in `3.x` the plugin initiated in the `onAfterRoute` event. In this event, the plugin attaches scripts/styles to the document and finally render the `HtmlDocument` like
```php
$doc->render(false, ['template' => 'mytemplate', 'file' => 'component.php'])
```
Now for converting to the J4 beta I need to register and use styles/scripts using `WebAssetManager`. But attaching assets at the `onAfterRoute` event says-

```console
Call to a member function getWebAssetManager() on null
```
And also in some events says that the *"**WebAssetManager is locked, you came late**"* something like this.
So my question is, at plugins where to **Register and Use** WebAssets and where not to.

**Note: I don't want any template-specific assets i.e. any assets from atum or cassiopeia. I just need my own assets and own HTML to render after hitting a specific route.**

**Comment by Fedik** [comment]
You doing something hacky.

> Call to a member function getWebAssetManager() on null

And that the result.

In normal runtime the asset can be registered between onAfterRoute and onBeforeCompileHead.
But preferable between onAfterDispatch and onBeforeRender

**Comment by ahamed** [comment]
> In normal runtime the asset can be registered between onAfterRoute and onBeforeCompileHead.
> But preferable between onAfterDispatch and onBeforeRender

I've registered the assets at the `onAfterDispatch` event. But cannot use this
```php
$doc->render(false, []);
```
method instead I've used
```php
$doc->setBuffer($content, 'component');
```
And for rendering the the `component.php` file instead of the `index.php` file I've just set the input `tmpl=component` at the `onAfterRoute` event like-

```php
Factory::getApplication()->input->set('tmpl', 'component');
```
And now it's working.

**Comment by Fedik** [comment]
I suspect you have override joomla Document and some other classes, that why it not worked.

Please close the issue if it fixed.
