### ISSUE TITLE
[4][Media Manager] Transparency is not preserved when cropping image

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30975]
### Steps to reproduce the issue

Joomla 4 Admin 
System -> Site Templates -> "Cassiopeia Details and Files" -> images folder -> system folder -> 

Select any of the png files

note that its a transparent png

Click crop 

### Expected result

Transparency is preserved 

### Actual result

Before:
![rating_star](https://user-images.githubusercontent.com/400092/95278774-dcccaa00-0848-11eb-9748-cf48d37838a4.png)

After:
![rating_star](https://user-images.githubusercontent.com/400092/95278784-e35b2180-0848-11eb-83c9-84b221e15b71.png)

### System information (as much as possible)

Safari on Mac in a docker image

**Comment by PhilETaylor** [comment]
Same happens with RESIZE button

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/30977 (for staging).
