### ISSUE TITLE
[4] Template with no templateDetails.xml causes PHP Notice

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30974]
### Steps to reproduce the issue

easiest way is to delete your templateDetails.xml for the default template, 

Then Admin -> System -> Site Templates -> "Cassiopeia Details and Files"

Look at your PHP log

### Expected result

No notices

### Actual result

`php_1        | NOTICE: PHP message: PHP Notice:  Undefined property: Joomla\CMS\Object\CMSObject::$description in /application/administrator/components/com_templates/tmpl/template/default_description.php on line 27
`

**Comment by PhilETaylor** [comment]
<img width="1340" alt="Screenshot 2020-10-07 at 02 48 39" src="https://user-images.githubusercontent.com/400092/95278236-a17dab80-0847-11eb-927a-32880fba766c.png">

**Comment by brianteeman** [comment]
If you are missing required files isnt this to be expected ?

**Comment by PhilETaylor** [comment]
If it's required then you should not be able to delete it using joomla admin console - you should be stopped from doing so

It's not a required file. There are many custom templates created on joomla sites without this file.

It **should** be a required file - but it's not enforced at all

**Comment by HLeithner** [comment]
Closing we have a pull request #31047
