### ISSUE TITLE
[4] Menus in Joomla Admin unordered

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#30970]
### Steps to reproduce the issue

Create several menus in Joomla 4 admin by installing the Sample Data and then creating yourself an A and a Z menu.

Look at how Joomla orders the menus in the left menu

Discuss the rights and wrongs of the order.

### Expected result

No idea.

Maybe the "Home" flagged menu first, and the rest in A-Z order?

### Actual result

It seems the latest menu created is put at the top of the list

<img width="353" alt="Screenshot 2020-10-07 at 02 16 51" src="https://user-images.githubusercontent.com/400092/95276466-2d410900-0843-11eb-880d-ceed81f8ac64.png">

**Comment by PhilETaylor** [comment]
same issue on the menus dashboard 

<img width="1260" alt="Screenshot 2020-10-07 at 02 19 12" src="https://user-images.githubusercontent.com/400092/95276597-84df7480-0843-11eb-8b68-0288fa33d244.png">

**Comment by infograf768** [comment]
They are ordered by ID descending and there is no way that I know to reorder them in the `index.php?option=com_menus&view=menus` manager.

<img width="1613" alt="Screen Shot 2020-10-07 at 07 23 25" src="https://user-images.githubusercontent.com/869724/95290658-0fd56480-086e-11eb-954b-3d70325991ef.png">

**Comment by PhilETaylor** [comment]
As most peoples main (home) menu by default will be the first one created at install time, this means that it will get buried over time further and further down the list :-( 

Seems like an oversight that menu items cannot be ordered and that the most important menu is not top and foremost

A quick win would be to reverse the order, home menu first and the Id asc but a way to set the exact order would be better

**Comment by ghost** [comment]
> but a way to set the exact order would be better

Agree
