### ISSUE TITLE
[RFC] Rename some function arguments in preparation for PHP 8

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#30988]
### Problem identified

With the introduction of [named arguments](https://wiki.php.net/rfc/named_params) in PHP 8, changing function argument names becomes a B/C break. Until PHP 8 is released, we can update existing function signature with new argument names.

### Proposed solution

We should convert existing snake_case arguments to camelCase to better follow our coding standards.
We should review other arguments and rename them if they are unclear or inaccurate.

If not done before PHP 8 is released, the next opportunity would be the next major Joomla! version. That is assuming we do want to add this feature to our B/C promise.

### Open questions

Should this be done against staging or 4.0?

**Comment by zero-24** [comment]
Given that 3.9.23 will be the first version eith explizit PHP8 support i would recommend to do any change we want to do now.

Just to avoid any confusion for extension devs. This does not affect any of your extension code yet. Named arguments are opt-in and renaming arguments are only being an issue once named arguments are live. So renaming them now woth the first version that supports PHP8 is fine in my opinion as this is the first version you could build your PHP8 only extension on.

The only very rare case of issue would be that you already have a PHP8 only extension on 3.x that ises named arguments and we are changing just that argument that you where used in your extension. But given no release has benn officially tagged for PHP8 yet and the masshosters do not have PHP8 yet i would say it would be a fair change now to make the future usage consitent.

**Comment by zero-24** [comment]
Cc @HLeithner @wilsonge

**Comment by HLeithner** [comment]
I'm in favor for fixing our argument naming but don't think that we should give a b/c promise on named arguments till j4 or later

**Comment by Llewellynvdm** [comment]
Making the changes as soon as possible is the wise thing to do. Specially since PHP 8 is due [November 26, 2020](https://stitcher.io/blog/new-in-php-8).

**Comment by jiweigert** [comment]
Being first time in the front row of implementing new programming language changes of PHP 8 would actually surprise me to see in Joomla, so I'm definitely in favor to see it happen.

**Comment by zero-24** [comment]
I would say after sharing this within all groups and only getting positive feedback I would say we can go for a set of PRs to change the arguments as susggested. @SharkyKZ

**Comment by PhilETaylor** [comment]
This kind of change should be merged for this exact reason. 

https://github.com/joomla/joomla-cms/pull/29812

**Comment by HLeithner** [comment]
No that's not the same or better it's the same because now we have no b/c break for php 8 but for #29812 we would add a b/c break if we did it wrong.

**Comment by zero-24** [comment]
Or better that PR should be send against staging so we can include it in the first release that supports PHP8

**Comment by HLeithner** [comment]
sorry my fault I thought the #29812 changes array keys but it doesn't so it should be ok

**Comment by zero-24** [comment]
> sorry my fault I thought the #29812 changes array keys but it doesn't so it should be ok

So it should be done against staging right? As when it comes with 4.x it would be a b/c break right?

**Comment by PhilETaylor** [comment]
"Rename some function arguments in preparation for PHP 8" = exactly what #29812 does at the same time as fixing a decade old typo. 

> Or better that PR should be send against staging so we can include it in the first release that supports PHP8

Well considering some files in #29812 don't even exist in Joomla 3 I don't see how that would be possible :)

**Comment by zero-24** [comment]
> Well considering some files in #29812 don't even exist in Joomla 3 I don't see how that would be possible :)

Well than they still can be patched with 4.x as this is new API == no B/C break. But the existing ones have to be changed in 3.x before the first official PHP8 supported version.

 > Plus the lack of interest in #29812 already shows that getting it past the post might be hard :)

Well you know how fast it can go. ;) In this case as this has to be done before the next 3.x release I think we find testers for that too.

**Comment by SharkyKZ** [comment]
PR for `libraries/src` directory https://github.com/joomla/joomla-cms/pull/31148.

**Comment by shoulders** [comment]
Can I also refer you to the Database column names which has a `camelCase` / `snake_case` issue

https://github.com/joomla/coding-standards/issues/269

**Comment by PhilETaylor** [comment]
"That is assuming we do want to add this feature to our B/C promise."

Cross posting https://github.com/joomla/joomla-cms/issues/31424 for interest.

**Comment by HLeithner** [comment]
@SharkyKZ are we finished with this issue and can we close it?

**Comment by HLeithner** [comment]
I expect that is done, thank you very much @SharkyKZ for creating the PRs
