### ISSUE TITLE
com_weblinks continues to display items after finish publishing date has passed

### ISSUE THREAD

**Issue by sjrapid** [joomla/joomla-cms#30994]
### Steps to reproduce the issue
Add a weblink with a finish publishing date < today
View weblinks from the front end

### Expected result
Link with finish publishing date < today should not be seen (or marked as 'expired' or similar for admin users)

### Actual result
link is displayed with no marking 

### System information (as much as possible)
Joomla 3.9.22
PHP 7.3.23
Browser:  Firefox
Template:  Protostar

**Comment by ReLater** [comment]
Hello @sjrapid 
Please post your issue in this repository: https://github.com/joomla-extensions/weblinks/issues

and close here then.

Thank you!
