### ISSUE TITLE
JTable::store(true) to update NULLs fails if assets are tracked

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#30995]
### Steps to reproduce the issue

Create custom table class with assets (property `$asset_id` is required) and try to execute `parent::store(true)`.

Or just edit `libraries/src/Table/Content.php`, replace at the bottom `return parent::store($updateNulls);` with `return parent::store(true);` to emulate the real case, next try to save an article.

### Expected result

Save without errors.

### Actual result

See error.

### System information (as much as possible)

Joomla 3.9.22

### Additional comments

The issue is that `JTable::store()` uses `$updateNulls` param for saving asset table instance as well and it will fail due to NULL `alias` property which is missed in `#__assets` table.

**Comment by Quy** [comment]
PR #30996
