### ISSUE TITLE
[3.9.22] Tab panels in user profile don't work

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#31001]
### Steps to reproduce the issue
1. Upgrade Joomla to 3.9.22 (I can't currently test if this also occurs on fresh install)
2. Log into backend
3. Click the "My profile" icon in the top right, select "Edit Account"
4. Attempt to change tabs

### Expected result
Able to easily switch the active tab

### Actual result
Tabs are unchanged

### Additional comments
I tested what would happen if I went to the users component and entered my profile from there, and tabs work as expected.
I checked the web console, and there are no visible errors or warnings.

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/31002.

**Comment by HLeithner** [comment]
as another workaround you can activate a two factor plugin

**Comment by HLeithner** [comment]
Regression documented [here](https://docs.joomla.org/J3.x:Unuseable_tab_panels_in_user_profile)
