### ISSUE TITLE
[4] com_content Empty Trash Issues.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31004]
### Steps to reproduce the issue

Go and trash two articles 
Use filter options to show trashed items
Note that the "Empty Trash" button is greyed out - There is no way to purge ALL items from the trash 
Select a trashed item - note now you can use "Empty Trash" button - but it only deletes the selected item and doesn't purge all trashed articles 

Also, while you have a trashed item selected, click Actions button, note that Trash is a selectable action in there... but this item is ALREADY trashed! 

### Expected result

Empty Trash button is a purge all trashed articles button

No "Trash" Action when items are already in the trash and when filtered by trashed items.

### Actual result

As explained above.

<img width="735" alt="Screenshot 2020-10-08 at 22 40 08" src="https://user-images.githubusercontent.com/400092/95516498-3ce15e80-09b7-11eb-8ee0-d145945f83f1.png">

**Comment by brianteeman** [comment]
> Note that the "Empty Trash" button is greyed out - There is no way to purge ALL items from the trash

![phil](https://user-images.githubusercontent.com/1296369/95516673-83cf5400-09b7-11eb-85d4-996f6f06679d.gif)

**Comment by PhilETaylor** [comment]
Its greyed out until you select items.... 

Its not a purge button, its a Trash item button and acts just like the Trash Action does... It makes no sense that its called "Empty Trash"

When I empty my trash cans, I don't take out one thing only. I tip up the trash can and empty it all... PURGE....

**Comment by PhilETaylor** [comment]
I see Joomla 3 has this strange behaviour too...

**Comment by PhilETaylor** [comment]
ok lets ignore the "Empty Trash" actually really being a "delete this item" from the db ... 

The other bug in this issue remains too.

**Comment by PhilETaylor** [comment]
> The other bug 

Expected result = No "Trash" Action when items are already in the trash and when filtered by trashed items.

**Comment by infograf768** [comment]
I agree it would be nice to take of the Actions => Trash when filtered by Trashed.

In the articles view for example we could have something like
```
				if (Factory::getApplication()->input->get('filter')[2] !== '-2')
				{
					$childBar->trash('articles.trash')->listCheck(true);
				}
```
Because we get a sequential array
`["filter"]=> array(5) { ["search"]=> string(0) "" ["featured"]=> string(0) "" ["published"]=> string(2) "-2" ["language"]=> string(0) "" ["level"]=> string(0) "" }`

Me not php good enough to fetch by `published` key ;) 

<img width="442" alt="Screen Shot 2020-10-09 at 08 28 48" src="https://user-images.githubusercontent.com/869724/95550650-822e7c00-0a09-11eb-8636-f647f2ed1dcc.png">

**Comment by HLeithner** [comment]
As first step can we rename "Empty Trash" to "Delete" ?

**Comment by PhilETaylor** [comment]
That makes more sense yes, but it can also then be put into the Actions menu too, as its a normal action (unlike a purge task that it assumed it is when not in the action dropdown)

**Comment by HLeithner** [comment]
Yes I know but till someone modify the action array (because this interacts also with the workflow) a button text change in the first place would "reduce" the issue

**Comment by infograf768** [comment]
> As first step can we rename "Empty Trash" to "Delete" ?

Not sure about that. Macintosh has used "Empty Trash" for ever and I have never seen any comments on forum about this wording creating confusion.

![Screen Shot 2020-10-11 at 16 52 48](https://user-images.githubusercontent.com/869724/95681851-59adaa00-0be2-11eb-93a4-b11b8db02145.png)

**Comment by PhilETaylor** [comment]
You ARE confused and that proves my point nicely :-)

Empty trash on a mac PURGES EVERYTHING IN TRASH - you don't need to select anything 

That's my point. In joomla you can safely assume Empty Trash means to PURGE EVERYTHING IN TRASH but that's NOT WHAT it does in joomla

In joomla Empty Trash button just deletes SELECTED ITEMS ONLY from the trash.

**Comment by infograf768** [comment]
yeah. after siesta confusion...

**Comment by infograf768** [comment]
Concerning the dropdown Trash choice when filtered by Trash, see https://github.com/joomla/joomla-cms/pull/31074

**Comment by brianteeman** [comment]
This looks like it has been resolved elsewhere - please check and confirm

**Comment by PhilETaylor** [comment]
all good. ta.
