### ISSUE TITLE
[3.9] Warnings of missing XML manifests on Joomla Update 

### ISSUE THREAD

**Issue by jiweigert** [joomla/joomla-cms#31000]
On each Joomla update i get two warnings about missing plugin Manifest XMLs for two already deinstalled plugins containing the Sampledata for example Content (plg_sampledata / plg_sample_blog)

Seems, there is no check in the update script if those plugins are installed and not removed.

### Steps to reproduce the issue
1. Setup a Joomla 3.9.20 install.
2. Login as Administrator
3. Deinstall the Sampledata-Plugins plg_sampledata & plg_sample_blog (?)
4. Check for Joomla Update & install Update Joomla 3.9.21
5. Recognize the Warning about missing manifest XMLs of the before deinstalled plugins

### Expected result

No warning

### System information (as much as possible)
Joomla! 3.9.22 Stable [ Amani ] 6-October-2020 15:00 GMT

**Comment by zero-24** [comment]
> Deinstall the Sampledata-Plugins plg_sampledata & plg_sample_blog (?)

hmm IIRC it is not intended for core plugins to be uninstalled. Given that the files for that plugins should come back on the update maybe just partally that could result into other issues.

**Comment by jiweigert** [comment]
> hmm IIRC it is not intended for core plugins to be uninstalled. 

Why should the SampleData-Plugins not be deinstalled? AFAIK, they add only some sample menu/ categories/ articles to the system.
Deinstalling them shouldn't do any harm unless someone decide to deinstall them after creating custom menues/categories/articles
And even then, the only drawback are only some unused id's.

I see no reason, why I should not deinstall them (and the demo-images under /images/) to have no wasted space or just a clean system.

**Comment by Fedik** [comment]
> I see no reason, why I should not deinstall them

the answer is:

> ... the files for that plugins should come back on the update



> have no wasted space or just a clean system.

you save nothing, but add headache on next update

If you do not need some core extension then better just disable it.

**Comment by jiweigert** [comment]
Fedik, Your answer still not explain, why they are mandatory installed and considered as core plugins.

They provide sampledata for first time users or developers and for a first time install that is ok,
but they are not neccessary for core functions.

At least I would expect, that the presence of them are checked on update
 - When they are not present, the user is asked if he want to re-install them
 - When they are present, be updated through the update process.

But just assuming nobody removes them and just calling update-scripts to (re-)install by partly install them, that should be not be the case.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31000">issues.joomla.org/tracker/joomla-cms/31000</a>.</sub>

**Comment by Fedik** [comment]
> Your answer still not explain, why they are mandatory installed and considered as core plugins.

Because on next update the files of uninstalled plugin will be restored.
Update process does not check what is removed, it just override old files with files.

> When they are not present, the user is asked if he want to re-install them

To do this is need to review/rewrite update process, and much of other changes.
Personally I think it not worth 5kb of saved space. I always can disable what I not use, that enough.

**Comment by jiweigert** [comment]
To be honest,

because of the nature of a
 
"Plugin" (installing something new into a system 
and "Extension" (extend a already available Core-Funktion by adding more features to it),  

I would expect, to deinstall any of these, because "Core"-Functionality would provide a minimal functionality to install those for more functionality.. means also I can deinstall them at any time and stillö have a working backend and bare Frontend-functionality through a basic website.



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31000">issues.joomla.org/tracker/joomla-cms/31000</a>.</sub>

**Comment by jiweigert** [comment]
> To do this is need to review/rewrite update process, and much of other changes.

That is something I would strongly recommend, because revisiting / optimizing the Installer/ Updater to something where an Administrator can decide, which plugins / extensions are installed would lead to, at best, a sleek system and if any "de-installed" plugin/ extension is required when installing a 3rd-party plugin/extension, that could be lookedup and reinstalled automatically.

A core functionality of joomla (plugin/ extension) should never be listed as plugin or extension, because as I wrote before, that naming implies that I can deinstall / deactivate them at any time without loosing Core funtionality.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31000">issues.joomla.org/tracker/joomla-cms/31000</a>.</sub>

**Comment by HLeithner** [comment]
Technically a core plugin is exactly the same as a 3rd party plugin. The only different is how it gets updated.

Since we make no different between core and 3rd party we have much less code to maintain and 3rd party developer can do exactly the same thing like core (of course there are exceptions because not everything is handled in a plugin or extension).

Extending the update to ignore not installed extensions sounds great but will not happen anytime soon.

I'm closing this issue as won't fixed.

**Comment by jiweigert** [comment]
> Technically a core plugin is exactly the same as a 3rd party plugin. The
only different is how it gets updated.

I don't deny that those technically are the same, but this raise the
question, why those essential "core" plugins/ extensions can still be able
to

- be selected in the deinstall area?
- be able to be "de-installed" and in the process are leaving parts still
in the filesystem?

when they should be technically the same as 3rd-party plugins / extensions?

Taking that argument, it should not even be possible for core plugins or
extensions to de-installed, as this is the current situation, because when
deinstalled, they don't show up in the backend anymore.

So either prevent any deinstalling for core plugins and extensions shipped
through Joomla

or

Handle core plugins/ extension like any other 3rd-party plugins because
they are the same.

Just closing and living with the current situation is the worst choice in
my opinion.

Harald Leithner <notifications@github.com> schrieb am Do., 8. Okt. 2020,
21:08:

**Comment by richard67** [comment]
In Joomla 4 you won't be able anymore to uninstall them.

For Joomla 3 it would have been a b/c break that's why we haven't done that in 3.

**Comment by jiweigert** [comment]
Thanks Richard,
for that info. +1

I can't really see why deinstalling would be a bc break, especially with a
modal like "Core plugin/ extension - proceed when you know what you're
doing!"
Especially in this harmless case of sample data.
But blocking from deinstalling is a first, good step.
Still, the installer/ updater in my opinion need more flexibility and logic.

Simple reason is, that if something is not installed, it can't be provide
any harm in case of a security issue.

And yes, I've seen systems, were plugins/ extensions were enabled for
testing purposes and later be used to attack the system. Not installing
them would had prevented that (or a watchdog script, which warns about
enabled, but unused plugins/ extensions...)

Richard Fath <notifications@github.com> schrieb am Do., 8. Okt. 2020, 22:06:
