### ISSUE TITLE
[4] com_redirect trash logic issues

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31005]
### Steps to reproduce the issue

first see issues in https://github.com/joomla/joomla-cms/issues/31004

2 more logic bugs.

Next lets look at com_redirect 
Add a few links in the Redirects component
Select all links
Note that the Actions menu has an "Empty Trash" action ? (Strange as https://github.com/joomla/joomla-cms/issues/31004 as an Empty Trash BUTTON not action!!) 
Select all links, and click actions, and click empty trash - Confirm ok then get "Delete not permitted." ??????

<img width="283" alt="Screenshot 2020-10-08 at 22 34 25" src="https://user-images.githubusercontent.com/400092/95515983-6d74c880-09b6-11eb-8868-b817e0b750be.png">

ok I think, so its true the selected items cannot be trashed if Im dumb and select "Empty Trash" - but nooooooo.... the trash is also NOT EMPTIED! 

Also why is "Empty Trash" an action in the Actions submenu, and only available once I select a link.... strange... 

So lets now filter on trashed items 

note there is no "Empty Trash" BUTTON like there is in Articles views.....

Select ONE trashed link
Select Actions 
Select "Empty Trash" 

### Expected result

EXPECT all to be removed 

### Actual result

but only one is removed, the one selected.

### Additional comments

So "Empty Trash" doesn't PURGE all the trashed items, it only deletes the selected trashed item?

**Comment by brianteeman** [comment]
> So "Empty Trash" doesn't PURGE all the trashed items, it only deletes the selected trashed item?

Yes thats exactly what it does. It has always worked this way.

Com_redirect has an **additional** Purge disabled button. This is because after a while of the plugin collecting urls you could end up with thousands of records (by default as disabled) and so you can one click remove them.

**Comment by PhilETaylor** [comment]
Just because something has always worked this way doesn't mean its right. 

The other bug remains.

**Comment by brianteeman** [comment]
> Just because something has always worked this way doesn't mean its right.

No but its the expected and documented behaviour - if you want to have a "purge all" then that would be a new feature/button. Nothing wrong with that and its been asked before. I even had a PR for it in the past.

**Comment by PhilETaylor** [comment]
> The other bug remains.

That is:

> Note that the Actions menu has an "Empty Trash" action ? (Strange as #31004 as an Empty Trash BUTTON not action!!)
> Select all links, and click actions, and click empty trash - Confirm ok then get "Delete not permitted." ??????

<img width="283" alt="Screenshot 2020-10-08 at 22 34 25" src="https://user-images.githubusercontent.com/400092/95517269-95652b80-09b8-11eb-8bc9-d83a49680ed7.png">

**Comment by brianteeman** [comment]
This looks like its been resolved elsewhere - please check and close if confirmed

**Comment by PhilETaylor** [comment]
yup fixed. ta.
