### ISSUE TITLE
Joomla cookies are assigned to root path even if site is in a subfolder

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#31013]
Joomla cookies are assigned to root path even if site is in a subfolder.

This means that if you have several Joomla installations under one domain, they will all use the same cookies and, for example, "think" that your joomla_user_state is "logged_in" in all sites even if it may be just logged in one site.

This can create all kind of conflicts and unexpected behaviors.

### Steps to reproduce the issue

1. Create a Joomla site in a subdirectory such as www.mysite.com/joomlainstall/
2. After logging in, check the stored cookies (joomla_user_state, session cookie, joomla_remember_me...)

### Expected result

They should be assigned to the proper root path of the specific installation "/joomlainstall/"

This allows you to have separate cookies for each separate installation under the same domain.

### Actual result

They are currently assigned to the root path of the whole domain "/"

**Comment by SharkyKZ** [comment]
Have you tried setting Cookie Path in Global Configuration?

**Comment by AndySDH** [comment]
@SharkKZ I haven't, but I guess that's for custom uses.

By default it should definitely default to the path of the Joomla installation rather than the root of the domain, otherwise you would have to customize it on each site manually.

**Comment by Bakual** [comment]
That's exactly the setting you need and it defaults to root because that is usually the right value for most sites.

**Comment by joomdonation** [comment]
As answered by @SharkyKZ and @Bakual , you can use Cookie Path to handle this use case when it is needed. For now, I'm closing this issue.
