### ISSUE TITLE
Random Image Module: Allow fluid images and modern classes

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#31026]
### Steps to reproduce the issue
Add an image module to your site, where images are small. You want to have the images with width: 100%.

Make a module with width 100%, and have images with width 800px. You cannot set the image class and if you set the width to 2000px, it is set back to the image width 
![grafik](https://user-images.githubusercontent.com/1035262/95649775-8927be00-0adf-11eb-9876-c6f8ea7325f4.png)

### Expected result
You can define an image class

### Actual result
Images are in the original size.

### System information (as much as possible)
Te same in staging and 4.0

**Comment by Quy** [comment]
Duplicate #22065?

**Comment by adj9** [comment]
By changing the field Width (px) the size of the random image changes. I don't understand the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31026">issues.joomla.org/tracker/joomla-cms/31026</a>.</sub>

**Comment by chmst** [comment]
@Quy not quite duplicate but it goes in the same direction. 
The input field for width accepts only pixel. 
The whole module is made before the age of mobile devices ;) 

@adj9 
I have added information to the description,

**Comment by adj9** [comment]
I have resumed the issue.

The module put it in the top-a nominal position.

With the Width (px) = 2000 - the image does not change, I confirm.

HTML inspect of modul 
<img width="816" alt="Schermata 2020-10-20 alle 11 43 29" src="https://user-images.githubusercontent.com/5918444/96569914-03b7c100-12ca-11eb-8f5e-96764988c26d.png">

There isn a class of img but there is class module.

**Comment by chmst** [comment]
Please test #32075<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31026">issues.joomla.org/tracker/joomla-cms/31026</a>.</sub>

**Comment by ghost** [comment]
can be closed as having pr #32075
