### ISSUE TITLE
[4.0] Beta3 to Beta4 update fails

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#31023]
### Steps to reproduce the issue
Install beat3 and try to update via Updater to Beata4

### Actual result
SQL Error Unknown column 's.inheritable' in 'field list'

![updateerror](https://user-images.githubusercontent.com/12803406/95614269-8046d600-0a66-11eb-8c4d-84ac3a22a88e.jpg)

**Comment by Quy** [comment]
Duplicate #30661
