### ISSUE TITLE
[4.0] Tag Options - CSS Class for tag link cause lost of class "badge" and "badge-info"

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#31025]
If you set a "CSS Class for tag link" in the tags individual options, the tags loose the classes "badge" and "badge-info". They now have only the new taglink class. I would expect that the tag link class is an additional class to the default classes of the tags.

### Steps to reproduce the issue
- Create a new tag
- Set a CSS Class for tag link in the Options of the tag
- Set a Tag in an article
- Look at the tag in the article

![screen shot 2020-10-09 at 18 19 48](https://issues.joomla.org/uploads/1/896c9ee7fb56a6ceeb22b730cf987610.jpg)

### Expected result
The tag link class should be an additional class to the default classes of the tags.

### Actual result

The Tag with the class has no style, because the classes are gone

![screen shot 2020-10-09 at 18 20 36](https://issues.joomla.org/uploads/1/dbe096ed9f59b1cd3c4988e6c7407989.jpg)

**Comment by chmst** [comment]
This is an important question. 
If there is a class field for something, image or module or whatever ... is it intended that the class replaces all class entries or should it be appended to existing classes?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31025">issues.joomla.org/tracker/joomla-cms/31025</a>.</sub>

**Comment by carcam** [comment]
adding the classes just after the existing ones will allow to use current styling and avoid them with your own css if you want. I think classes should be added and not used as a replacement.

Also we need to consider that in other areas of Joomla (menus and modules) the classes were directly added (with no spaces) to the elements. Probably the behaviour should be the same in all other parts.

**Comment by SharkyKZ** [comment]
It's fine as it is. If you want to have a common class for all tags, create a layout override and add it there.

**Comment by brianteeman** [comment]
The behaviour should be consistent. You should not need an override to get consistent behaviour

**Comment by brianteeman** [comment]
It is easy to fix but it should be noted first that this behaviour in j4 is the same as in j3

**Comment by drmenzelit** [comment]
Please test #32491
