### ISSUE TITLE
Menu with GUEST access level not visible

### ISSUE THREAD

**Issue by alfredojdd** [joomla/joomla-cms#31031]
### Steps to reproduce the issue
New menu item
Set GUEST access level

### Expected result
No logged user -> menu visible

### Actual result
No logged user ->Menu hidden
Checked with several browsers

### System information (as much as possible)
W10, laragon, php 7.4.7, Joomla 4 beta 4

### Additional comments
Maybe it's my fault, but do not find the error.....

**Comment by ghost** [comment]
cant confirm.

### Backend:

![image](https://user-images.githubusercontent.com/71960554/95648791-431c2b80-0ada-11eb-9c2d-e0f1b80cfaef.png)


### Frontend:

![image](https://user-images.githubusercontent.com/71960554/95648824-71017000-0ada-11eb-9509-305d088b50e3.png)


### System information

![Screen Shot 2020-10-10 at 09 20 51](https://user-images.githubusercontent.com/71960554/95648763-16681400-0ada-11eb-98de-97c0e02118ce.png)

**Comment by alfredojdd** [comment]
With Public access:
![image](https://user-images.githubusercontent.com/17855375/95649277-0c93e000-0add-11eb-8fe5-4967b780c284.png)
Menu working:
![image](https://user-images.githubusercontent.com/17855375/95649315-33521680-0add-11eb-9637-169cb44ff26b.png)

With GUEST access:
![image](https://user-images.githubusercontent.com/17855375/95649342-5d0b3d80-0add-11eb-976c-cb391d7e76f1.png)
Menu hidden;
![image](https://user-images.githubusercontent.com/17855375/95649381-7f04c000-0add-11eb-971f-790c3bc6015e.png)

**Comment by brianteeman** [comment]
Make sure that you have everything set correctly in the users component options

![image](https://user-images.githubusercontent.com/1296369/95649457-5bd61280-0ad5-11eb-9a68-de9f471c831d.png)

**Comment by alfredojdd** [comment]
Yeah! Works! It was set to public
Thanks!!!!
The question is: why, I suppose that by default, Guest User Group is set to Public?

**Comment by ghost** [comment]
>  The question is: why, I suppose that by default, Guest User Group is set to Public?

on a fresh install (today) the guest user group is set in user-options on ´guest´.

**Comment by alfredojdd** [comment]
Ok. Thanks to all.
