### ISSUE TITLE
[4] Change more editor icons

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31034]
Change icons in CMS CONTENT dropdown to be consistent with Joomla 4 icons

Forked from https://github.com/joomla/joomla-cms/pull/30892 as that was already RTC. 

<img width="916" alt="Screenshot 2020-10-10 at 11 35 37" src="https://user-images.githubusercontent.com/400092/95652961-c8104080-0aec-11eb-929e-e559f3f9ee2d.png">

// @brianteeman

**Comment by N6REJ** [comment]
I imagine its caused by having a mix of svg & fontawesome icons.

**Comment by brianteeman** [comment]
nope nothing to do with that. its just using different icons

**Comment by brianteeman** [comment]
@PhilETaylor if we didnt have 4 different icons in use it would be easy ;)

![image](https://user-images.githubusercontent.com/1296369/96413642-d85aa680-11e3-11eb-8b45-3568cc9535a2.png)

![image](https://user-images.githubusercontent.com/1296369/96413697-ec060d00-11e3-11eb-8d2c-0cc1edff4e00.png)

![image](https://user-images.githubusercontent.com/1296369/96413744-fc1dec80-11e3-11eb-8886-e2e93796685c.png)

![image](https://user-images.githubusercontent.com/1296369/96413780-09d37200-11e4-11eb-9d30-6096d9cbed5c.png)

![image](https://user-images.githubusercontent.com/1296369/96413809-1bb51500-11e4-11eb-94ae-740ed797058b.png)

![image](https://user-images.githubusercontent.com/1296369/96413843-2b345e00-11e4-11eb-8b20-682c29395a46.png)

![image](https://user-images.githubusercontent.com/1296369/96413910-4901c300-11e4-11eb-8c34-12a13e5bd767.png)

**Comment by brianteeman** [comment]
They've all been done except for articles which is a complex case and I'm not sure if it needs to be changed

**Comment by PhilETaylor** [comment]
cool thanks
