### ISSUE TITLE
[4.0] Error message when you save an article without Created Date

### ISSUE THREAD

**Issue by todordev** [joomla/joomla-cms#31046]
### Steps to reproduce the issue
1. Go to the tab "Publishing" of an article.
2. Remove the value of Created Date.
3. Save the article.

### Expected result
I expect the property "created" to be validated. It could be one of the following results.

- The system should show us error message about that "It is not allowed to save an article without valid value for Created Date".
- The system should generate and set value to the property "created".
- If already have valid created date, the system should keep it and show error message about invalid value provided by the user.

### Actual result
The system shows error message.
"Save failed with the following error: Incorrect datetime value: '' for column `joomla`.`m6bk9_content`.`created` at row 1"

![Screenshot](https://user-images.githubusercontent.com/1272206/95676236-404a3500-0bc5-11eb-950b-249702ff349d.png)

### System information (as much as possible)
PHP 7.4.11
Joomla! 4.0.0-beta5-dev
Database Server: MariaDB 10.4.11

**Comment by PhilETaylor** [comment]
Please, what EXACT Mysql version are you running?

**Comment by todordev** [comment]
Database Server: MariaDB 10.4.11

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/31273.
