### ISSUE TITLE
[4] 2 API controllers can throw a not found "Exception\ResourceNotFound"

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31063]
### Steps to reproduce the issue

Code review.

Here: 
https://github.com/joomla/joomla-cms/blob/88c20731f66ca439ac8d62991b4974279e42387a/api/components/com_plugins/src/Controller/PluginsController.php#L58

And here: 
https://github.com/joomla/joomla-cms/blob/88c20731f66ca439ac8d62991b4974279e42387a/api/components/com_contenthistory/src/Controller/HistoryController.php#L81

We have an Exception of `Exception\ResourceNotFound` being thrown in the namespace `Joomla\Component\Contenthistory\Api\Controller`

Neither phpStorm or I can work our where this missing `Joomla\Component\Contenthistory\Api\Controller\Exception\ResourceNotFound` class is, or if its a mistake, what class should be used as the thrown exception.

**Comment by SharkyKZ** [comment]
It should be `Joomla\CMS\MVC\Controller\Exception\ResourceNotFound`.

**Comment by wilsonge** [comment]
What @SharkyKZ said - I guess someone copy/pasted from the parent ApiController class

**Comment by PhilETaylor** [comment]
I've not had time to revisit this myself - but clearly it needs changing to be correct

**Comment by PhilETaylor** [comment]
#31081
