### ISSUE TITLE
Update Component fail from 3.9.20 to 3.9.22

### ISSUE THREAD

**Issue by brucew2013** [joomla/joomla-cms#31077]
### Steps to reproduce the issue
1. Login to Joomla backend.
2. Update Notification appears
3. Click button
4. Component opens
5. Click button to update

Same happens when opening **Joomla! Update** component from menu.

### Expected result
Update process to begin

### Actual result
Broken page results to https://[domain name URL]/administrator/index.php
HTTP ERROR 500

### System information (as much as possible)
**Server Information**
Processor Information
Total processors: 2
Intel(R) Xeon(R) CPU E5620 @ 2.40GHz
Speed
2400.084 MHz
Cache
12288 KB
**Operating System**
CENTOS 7.8 kvm [host] v90.0.14
**Memory Information**
[    0.000000] Memory: 1904740k/2047856k available (7672k kernel code, 392k absent, 142724k reserved, 6049k data, 1876k init)
**System Information**
Linux host.alcoholjustice.org 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
**Platform**
PHP Built On	Linux host.alcoholjustice.org 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64
Database Type	mysql
Database Version	5.5.5-10.0.31-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.3.23
Web Server	LiteSpeed
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 3.9.20 Stable [ Amani ] 14-July-2020 15:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by Quy** [comment]
Please post in Joomla Forum https://forum.joomla.org/viewforum.php?f=710 and report back if a bug is found. Thanks.
