### ISSUE TITLE
Installer Progress Bar broken

### ISSUE THREAD

**Issue by blueline86** [joomla/joomla-cms#31075]
### Steps to reproduce the issue
Install a component using Upload Package File 

### Expected result
The progress bar should display the current file upload progress 

### Actual result
The progress bar stays at 0% through the upload. 

### System information (as much as possible)
MySQL 5.6.49
PHP 7.4.11
Apache
litespeed
Joomla! 4.0.0-beta5-dev Development [ Mañana ] 15-September-2020 19:15 GMT
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36

## Additional comments
In core.js there does not appear to be support for uploadProgressCallback

**Comment by blueline86** [comment]
@chmst this is actually a slightly different problem. The other posts are relating to installing Joomla. This relates to installing components and is a simple progress bar of the file upload not SQL install which will is working in Joomla 3 but broken in 4.

**Comment by blueline86** [comment]
Adding the below `onBefore `should fix this. 

```
Joomla.request({
        url: uploadUrl,
        method: 'POST',
        perform: true,
        data: data,
        headers: {
          'Content-Type': 'false'
        },
        onBefore: function(xhr) {
          
            progressBar.style.width = 0; //progressBar.css('width', 0);
            progressBar.setAttribute('aria-valuenow', 0); //progressBar.attr('aria-valuenow', 0);
			percentage.textContent = '0'; // percentage.text(0);

			// Upload progress
			xhr.upload.addEventListener("progress", function (evt) {
				if (evt.lengthComputable) {
					var percentComplete = evt.loaded / evt.total;
					var number = Math.round(percentComplete * 100);
					progressBar.style.width = number + '%'; //progressBar.css('width', number + '%');
					progressBar.setAttribute('aria-valuenow', number); //progressBar.attr('aria-valuenow', number);
					percentage.textContent = number; //percentage.text(number);

					if (number === 100) {
						dragZone.setAttribute('data-state', 'installing'); //dragZone.attr('data-state', 'installing');						
					}
				}
			}, false);

			return xhr;
            
        },
```

**Comment by ghost** [comment]
Confirm the issue. 

Upload per drag and drop show below screen until upload is finished:

![Screenshot_2021-05-28 Extensions Install - sql - Administration](https://user-images.githubusercontent.com/78906980/119940405-6b846780-bf8f-11eb-925d-40c02e3d1e93.png)

Upload per ![image](https://user-images.githubusercontent.com/78906980/119940666-d2098580-bf8f-11eb-81e1-98cdd939291f.png) give the animation in browser tab with the 2 points shown instead the favicon.

**Comment by Fedik** [comment]
please test #34745
