### ISSUE TITLE
[4.0] Bug in TagsHelper query

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#31094]
### Steps to reproduce the issue
Create a tag.
Assign this tag to some articles.
Unpublish one of these articles.
Create a Compact List of Tagged Items menu item and display in frontend for this tag.

Code contains to check the `core_state`
https://github.com/joomla/joomla-cms/blob/704452016b44bedb1a970ce8bce3268c4d04ed02/components/com_tags/tmpl/tag/list_items.php#L92-L96

The problem is that we never get the core_state if it is set to 0 as only items published are displayed.

The code was drastically modified in J4 vs J3 in the `libraries/src/Helper/TagsHelper.php` by the PR https://github.com/joomla/joomla-cms/pull/27107 which got rid of the `core_state` array.

We have 2 solutions;
1. We do not check anymore for `core_state` in the layout. 
2. We reinstate the query fetching for the possible array and publish up/down

@SharkyKZ

**Comment by SharkyKZ** [comment]
This hasn't changed since J3. State filter is hardcoded here:

https://github.com/joomla/joomla-cms/blob/09b46f782673fcb23c4c9d9fac240b2ba01ca332/components/com_tags/models/tag.php#L251

**Comment by infograf768** [comment]
@SharkyKZ 

> State filter is hardcoded here:

Understand. Therefore it is not necessary to check for core_state in the layout. Will make PR.


BUT we have another issue due to https://github.com/joomla/joomla-cms/pull/27107 
You got rid of publish up and publish down
This means that an item can be Published but not available to display in these cases but is yet displayed => 404.

The modules have kept this case. For example TagsSimilarHelper.php still contains
```
			->extendWhere(
				'AND',
				[
					$db->quoteName('cc.core_publish_up') . ' IS NULL',
					$db->quoteName('cc.core_publish_up') . ' = :nullDateUp',
					$db->quoteName('cc.core_publish_up') . ' <= :nowDateUp',
				],
				'OR'
			)
			->bind(':nullDateUp', $nullDate)
			->bind(':nowDateUp', $now)
			->extendWhere(
				'AND',
				[
					$db->quoteName('cc.core_publish_down') . ' IS NULL',
					$db->quoteName('cc.core_publish_down') . ' = :nullDateDown',
					$db->quoteName('cc.core_publish_down') . ' >= :nowDateDown',
				],
				'OR'
			)
			->bind(':nullDateDown', $nullDate)
			->bind(':nowDateDown', $now);
```

Here the article `articletest_publish_later` is displayed in the compact list as well as in the normal list, but should not

<img width="675" alt="Screen Shot 2020-10-15 at 09 52 51" src="https://user-images.githubusercontent.com/869724/96093394-5f4e0d00-0ecc-11eb-9148-beaac281b43a.png">

But, it is not displayed in the Similar Tags Module, which is correct

<img width="839" alt="Screen Shot 2020-10-15 at 09 49 37" src="https://user-images.githubusercontent.com/869724/96093529-8b698e00-0ecc-11eb-83da-1130a3529bf2.png">


In https://github.com/joomla/joomla-cms/pull/27107 , I can see

<img width="1161" alt="Screen Shot 2020-10-15 at 10 01 10" src="https://user-images.githubusercontent.com/869724/96094225-66c1e600-0ecd-11eb-91da-ab25ce85ce5e.png">

Can you correct that?

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/31097.

**Comment by infograf768** [comment]
Closing as #31097 solves the issue. Thanks.
