### ISSUE TITLE
Empty trash can in Component Tag - organization of standard elements

### ISSUE THREAD

**Issue by adj9** [joomla/joomla-cms#31101]
### Steps to reproduce the issue
Go to the trash can in the Tag component and any other one (example articles)

#### Tag
Empty trash is in Actions button

#### Article (or other)
Empty trash is in  toolbar part of Atum template

### Question
To have a standard toolbar, should the "Empty Trashcan" button be inserted in the toolbar on all components?

**Comment by chmst** [comment]
Duplicate #31004
