### ISSUE TITLE
[4.0] Single Contact display: mysqli_stmt error

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#31104]
### Steps to reproduce the issue
Create a superuser contact.
Create another contact. 
(The super user should be the author of some articles.)

Create a Single Contact menu item displaying the superuser contact.

Make sure the `Contact Select List` OR the `User Articles` parameters are set to show.

<img width="854" alt="Screen Shot 2020-10-16 at 09 05 33" src="https://user-images.githubusercontent.com/869724/96224093-4bb7aa80-0f8f-11eb-94c4-9be2f38e97bb.png">

Display the contact in frontend.

### Expected result
A Select box is displayed.
A specific part lists articles

### Actual result
[16-Oct-2020 07:01:18 UTC] PHP Warning:  mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement in `root/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php on line 420`

and no display with error 0

@SharkyKZ @richard67

**Comment by richard67** [comment]
Maybe @alikon could have a look on it, too?

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/31107.
