### ISSUE TITLE
[4.0] Change password error message

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#31113]
### Steps to reproduce the issue
I set the "force password change" option for a user. The user loggs in into the backend and gets directly redirected his/her profile. Now tries to set a new passwort:
![grafik](https://user-images.githubusercontent.com/1229869/96270099-7e7f9400-0fcb-11eb-9be2-57146cac0ce2.png)

The user can't save as long as the password does not fullfill the requirements, but I can't see anywhere, what are the requirements.

### Expected result
See, what I'm missing in my password.

### Actual result
I have to guess

**Comment by brianteeman** [comment]
#30906 might help to resolve this

**Comment by richard67** [comment]
... might have helped ... it’s closed meanwhile.

**Comment by brianteeman** [comment]
closed because the suggested bug fix to complete it doesnt work

**Comment by brianteeman** [comment]
Please see #31217
