### ISSUE TITLE
[4.0] webauthn button 'killing' #seo

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#31112]
### Steps to reproduce the issue
go to a front-end page where the login module is present (with the authentication button present)

the image in the button is way to big and is scaled down by css

### Expected result
an icon in the button that is not scaled down by more then 10%

### Actual result
an icon in the button that is scaled down with 16700% (from 4359px to 26px)
![screen shot 2020-10-16 at 13 15 58](https://issues.joomla.org/uploads/1/eae81824178a73b095a64ec527b0f76e.jpg)

![screen shot 2020-10-16 at 13 14 53](https://issues.joomla.org/uploads/1/1c8d173881607f6c93904795b92c25c0.jpg)
### Additional comments
these images (media/plg_system_webauthn/images) should be reduced in size.

**Comment by SharkyKZ** [comment]
Already fixed in https://github.com/joomla/joomla-cms/pull/30846.

For further improvements see PR https://github.com/joomla/joomla-cms/pull/31028.

**Comment by Ruud68** [comment]
I am a bad searcher as it turnes out :) Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31112">issues.joomla.org/tracker/joomla-cms/31112</a>.</sub>
