### ISSUE TITLE
[4.0]  mod_article_news readmore missing string

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31117]
### Steps to reproduce the issue
create a module of type  mod_article_news readmore 
and make sure that you set it to show readmore
publish the module on a page that is NOT com_content

### Expected result
readmore links displayed

### Actual result
string is not translated
![image](https://user-images.githubusercontent.com/1296369/96301355-fad79e80-0fee-11eb-9b3a-b3e66dad7870.png)

### Additional comments
This was caused by my PR #30780 which switched to make sure the layout was used. However the layout requires the com_content language file.

The switch to use the layout was correct. So we have to either 
1. change the strings to global strings
or
2. always load the com_content language string with the module
or
3. add the strings to the module language file
```
COM_CONTENT_READ_MORE="Read more ..."
COM_CONTENT_READ_MORE_TITLE="Read more: %s"
COM_CONTENT_REGISTER_TO_READ_MORE="Register to read more ..."
```

**Comment by richard67** [comment]
I vote for global strings.

**Comment by brianteeman** [comment]
See #31123
