### ISSUE TITLE
[4.0] MenuItem: Access Levels for ComponentViews did not work!

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#31125]
### Steps to reproduce the issue
Create a menu item, like Content CategoryList or any other
Route Link: index.php?option=com_content&view=category&id=2
SET ACL to "Registered" 
![grafik](https://user-images.githubusercontent.com/12803406/96334211-4f226300-106f-11eb-8e6f-b8bddfac1f8d.png)

Check as guest by open route link.

### Expected result
ACL Should block tha whole view!
Redirect to login and display a ACL note maybe?

### Actual result
The view is displayed without any restrictions!

### System information (as much as possible)
Joomla 4.0 Beta4

### Additional comments
These effects also with other components, tetsted with 
com_content, single contact
Route Link: index.php?option=com_contact&view=contact

You can test these with any component.

![grafik](https://user-images.githubusercontent.com/12803406/96334332-3bc3c780-1070-11eb-811b-2d902cd9c961.png)

**Comment by SharkyKZ** [comment]
This is more or less expected.

**Comment by chmst** [comment]
Is it the same behaviour as in J3? 
If the article is public, then you can see it in public, using the link. 
Otherwise the article must be set to view level "Registered"
Or did I miss something?

**Comment by HRIT-Florian** [comment]
You're right, right. Thought it was, sorry.
It's a little ambiguous, but that's the logic.
