### ISSUE TITLE
[4.0] Batch copying articles: tags not copied

### ISSUE THREAD

**Issue by crimle** [joomla/joomla-cms#31127]
### Steps to reproduce the issue
Open or create an article 
Add a tag
Save and close the article
Copy this article using the bach function
- Action to Perform = Copy
- Add Tag = Keep original tags
Open the copy of the article that has just been created

### Expected result
The copied articles tag is also in this article  

### Actual result
The tag has not been copied

**Comment by HRIT-Florian** [comment]
Issue confirmed

**Comment by gostn** [comment]
J3, J4, ? > System information (as much as possible)

**Comment by HRIT-Florian** [comment]
confirmed in Joomla! 4.0.0-beta4 Beta

**Comment by adj9** [comment]
I don't know where I can get the copy option

The batch window is this
![Schermata 2020-10-17 alle 13 11 10](https://user-images.githubusercontent.com/5918444/96335650-6fa3ea80-107a-11eb-8f9d-83c8cfa97ed8.png)

**Comment by crimle** [comment]
Pull down «Copy or Move to Category»
