### ISSUE TITLE
[4.0] Plugin System Actionlogs lang strings not loaded when disabled

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#31122]
### Steps to reproduce the issue
Looks like a normal behavior for any plugin, BUT the strings need to be loaded when the Action Logs - Latest module is displayed in backend (usually in CPanel)

### Expected result
<img width="537" alt="Screen Shot 2020-10-17 at 10 06 26" src="https://user-images.githubusercontent.com/869724/96331821-acfb7e80-1060-11eb-9d3a-c3a931d46f7e.png">

### Actual result
<img width="581" alt="Screen Shot 2020-10-17 at 10 07 05" src="https://user-images.githubusercontent.com/869724/96331811-96552780-1060-11eb-960a-e22eef03013a.png">

Only solution I found was to add in joomla.ini the strings concerned:
```
; Common content type log messages
PLG_SYSTEM_ACTIONLOGS_CONTENT_ADDED="User <a href=\"{accountlink}\">{username}</a> added new {type} <a href=\"{itemlink}\">{title}</a>"
PLG_SYSTEM_ACTIONLOGS_CONTENT_ARCHIVED="User <a href=\"{accountlink}\">{username}</a> archived the {type} <a href=\"{itemlink}\">{title}</a>"
PLG_SYSTEM_ACTIONLOGS_CONTENT_DELETED="User <a href=\"{accountlink}\">{username}</a> deleted the {type} {title}"
PLG_SYSTEM_ACTIONLOGS_CONTENT_PUBLISHED="User <a href=\"{accountlink}\">{username}</a> published the {type} <a href=\"{itemlink}\">{title}</a>"
PLG_SYSTEM_ACTIONLOGS_CONTENT_TRASHED="User <a href=\"{accountlink}\">{username}</a> trashed the {type} <a href=\"{itemlink}\">{title}</a>"
PLG_SYSTEM_ACTIONLOGS_CONTENT_UNPUBLISHED="User <a href=\"{accountlink}\">{username}</a> unpublished the {type} <a href=\"{itemlink}\">{title}</a>"
PLG_SYSTEM_ACTIONLOGS_CONTENT_UPDATED="User <a href=\"{accountlink}\">{username}</a> updated the {type} <a href=\"{itemlink}\">{title}</a>"
```

Any better idea?

**Comment by brianteeman** [comment]
Wont your proposal mean that the same has to be done for all the actionlog plugins? And even if that is done it would not solve the issue for any 3pd actionlog plugins

**Comment by infograf768** [comment]
We indeed need another way, this is why I did not make a PR but an issue.

**Comment by infograf768** [comment]
I found a solution.


`ActionlogsHelper::loadActionLogPluginsLanguage();` is loading ONLY the language files of the actionlogs plugins (**enabled or disabled**) which are in the `actionlog` folder.
It totally ignores the actionlogs system plugin.

We have
https://github.com/joomla/joomla-cms/blob/690bf5fe2a6e11a56421c5c5ad84487d28b11b97/administrator/components/com_actionlogs/src/Helper/ActionlogsHelper.php#L282-L310

It forces loading `com_privacy` language file though.

Shall not we also force `plg_system_actionlogs.ini` lang file?

If I add 
```
		// Load plg_system_actionlogs too
		$lang->load('plg_system_actionlogs', JPATH_ADMINISTRATOR);
```
issue solved.

@wilsonge @HLeithner 
What do you think?

**Comment by HLeithner** [comment]
Since we have already this method it looks straight forward to add the system plugin to it.

**Comment by infograf768** [comment]
tks, will do

**Comment by infograf768** [comment]
Closing as we have a patch https://github.com/joomla/joomla-cms/pull/31745
