### ISSUE TITLE
[4.0] Minimum number of password characters cannot be set to less than 8

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#31139]
### Steps to reproduce the issue
Go to: Users - Manage - Options and set 5 into "Minimum Characters" form field option. When saving the options, this parameter will be set to 12

![image](https://i.imgur.com/ckeWwc4.png)

### Expected result
When setting the parameter to 5, it will be set to 5

### Actual result
When setting the parameter to 5, it will be set to 12

### System information (as much as possible)
‎Joomla! 4.0.0-beta5-dev, PHP 7.2.34, DB 10.4.14-MariaDB

### Additional comments
If this is not a bug, I can imagine, this should be some kind of security feature, but setting options is made by super users - administrators. I think, administrators should be able to set values they need, not values that someone else thinks are correct.

Jan

**Comment by ChristineWk** [comment]
Hi Jan,

as I remember, it has been changed. See also: https://issues.joomla.org/tracker/joomla-cms/30473<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31139">issues.joomla.org/tracker/joomla-cms/31139</a>.</sub>

Found also this Issue: https://issues.joomla.org/tracker/joomla-cms/30397

**Comment by PhocaCz** [comment]
Hi Christine, thank you for the link.

**Comment by PhocaCz** [comment]
Anyway, I get two the same instances of J! 4 (Beta5) and

1) first instance does not display warning and change the value to default (from 5 to 12, when Save & Close is used, there is no warning)

![img](https://i.imgur.com/f4wJyWH.gif)

2) second instance displays a warning

![img](https://i.imgur.com/dC6fU5h.gif)

In first instance, there were applied some patches, so I assume, the second instance is the latest J! 4 development state, so at least, displaying of warning is OK here.

Jan

**Comment by Quy** [comment]
Duplicate #30397
