### ISSUE TITLE
[4.0] Empty Alt descriptions [a11y]

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31138]
An alt text provides an accessible description of an image. Most of the time you should always have one. You should never not have any alt because then assistive technology such as a screenreader will announce the filename. See the October Joomla Magazine article on this ( published on Tuesday, 20 October 2020)

In the rarer situation that the image is purely decorative then it is acceptable to have an empty alt text which should be `alt=""`. 

Currently there are several places in Joomla where if you are too lazy to enter a text description of the image joomla will insert `alt=""` While this does prevent the filename being read aloud it is not good practice as you are preventing a significant % of your readers being able to access all the content. If the content author performs an accessibility check of their site then _most_ checkers will not report any errors or warnings about missing descriptions as it sees the `alt=""`

We should be doing everything to encourage the use of alt text descriptions and one method used by some other cms is that the  alt text input field is required so you have to enter a description in order to insert the image OR you have to check a box that says its is a decorative image and should use an empty `alt=""`

I am not sure about making it required (although I have done on a site I manage) but I am definitely in favour of 
1. Not defaulting to `alt=""` if there is no text entered
2. Having a check box that must be checked if it is a decorative image and then outputting `alt=""`

This way we still allow the user to have an empty alt AND we allow the user to check their site for missing descriptions.

![chrome_2020-10-17_13-38-39](https://user-images.githubusercontent.com/1296369/96350961-6afa2900-10b0-11eb-9f21-2e0263451951.png)

**Comment by richard67** [comment]
Makes sense to me.

**Comment by adj9** [comment]
On this wake I realized that it is necessary to redefine the Random image module.
Now the alt is spelled out by the file name, but it is not necessarily appropriate for the multimedia content. If it is possible to have the reader of the accessibility plugin read the alt is nice. I haven't seen the technical part yet. :)

**Comment by chmst** [comment]
It surely makes sense to ask for attention on alt - texts. 
But do we really want to add an additional input field to every image? So that blind users or keyboard users have more to do? 
I suggest to add a hint to the field, but no additional checkbox.

**Comment by brianteeman** [comment]
@chmst without the extra field the problem is as follows. Maybe you have a better solution to fixing this

1. User creates a description
output is alt="the description"

2. User deliberately does not add a description as its decorative only
output is alt=""

3. User too lazy to add a description
here there must be no alt at all

I do not see how you can achieve point 2 and point 3 without the extra field

**Comment by zwiastunsw** [comment]
It is not true that there can be no alt at all. It must be either:
- alt="the description"
- alt=""

Currently, point 2 is achieved without any work.

**Comment by brianteeman** [comment]
Please stop and think for a second about exactly what I am saying before shooting from the hip without thinking. (check the code - I made some of the errors because I didnt consider the consequences)

You are correct that the only valid values for alt are 
- alt="the description"
- alt=""

What I am saying is that it is not correct to **automatically** use alt="" when there is no description entered. 

As you know alt="" means it is a decorative image which does not require an alt description and should be ignored by assistive technology

Every other image (most of them) should have a description and it is **not** valid to have an alt="" for those images

marking an image as decorative should be an _active and deliberate_ choice. it should not be what happens when a lazy developer doesnt enter any text. (thats what happens now in some places).

Lets look at see what wave says about an image without alt

![image](https://user-images.githubusercontent.com/1296369/96374406-7e69ca80-116a-11eb-8f1d-de219777b993.png)

Now look at what wave says about an image with alt=""
![image](https://user-images.githubusercontent.com/1296369/96374480-fafca900-116a-11eb-89ab-c6e921fd55cb.png)

oh look it doesnt say anything even though you and I both know that it almost certainly should have a description. So the lazy developer is able to pass the tests and doent even know their content is invalid because the code says that assistive technology should ignore the image. 

To the best of my knowledge only html_codesniffer even flags this as something you should check

As we continue to educate users about people first web design and the benefits of using an accessibility checker we are failing them by automatically using alt="" as they will never know they should be improving their code.

**Comment by zwiastunsw** [comment]
Report a warning in the new plugin - Accessibility checker. 

PS And learn to discuss things, not ad personam.

**Comment by zwiastunsw** [comment]
What you propose is applied in Microsoft Word 365 and Adobe Acrobat Pro (marking images as decorative), because when there was no alternative description, the image was still reported by some assistive technologies. 
I checked ATAG, I did not find a guideline there that would justify such a solution. Maybe B.2.2.1 Accessible Option Prominence (WCAG),  But that would be over-interpretation.

**Comment by brianteeman** [comment]
There is nothing to discuss. I am right and you are wrong ;)

We have a difference of opinion. I believe that we should not hide errors. You are saying it is ok to hide errors.

We both have the same aims (I hope) making Joomla a leader in producing accessible content. Instead of ranking 3rd I want us to rank first. We will never achieve that by hiding errors. We can only do that by educating users and giving them the tools to produce accessible content.

**Comment by zwiastunsw** [comment]
No, we don't hide errors. There is no error here. The author decides whether to add an alternative text or not.
When you make a plugin to the editor and it will report a warning, it will be OK.
However, additional unnecessary activity also causes a problem with accessibility, as Chrstiane wrote about. 
I understand your intentions, but the proposed solution is the wrong pattern design.

**Comment by brianteeman** [comment]
> The author decides whether to add an alternative text or not.

Exactly correct. But currently they are not making a decision

**Comment by zwiastunsw** [comment]
He makes a decision. If he types, he decides. If he doesn't enter, he also decides.
If you want to be helpful, you can add a hint to explain the field. But I don't think it is necessary.

**Comment by brianteeman** [comment]
#fail

**Comment by brucelawson** [comment]
Blank alt should be a deliberate choice ("confirm this image is purely decorative" or somesuch) rather than the default. (I've just spent a month sorting out a client site because their marketing team didn't understand what 'image description' meant so ignored it for 700+ images, leading to an expensive law suit and remediation by me)

**Comment by carcam** [comment]
I know that it's not recommended to use filenames in alt descriptions, but why instead of having that checkbox (which means an extra click), don't we just automatically fill in ALT text with image filename on image selection?

In practice that will be the same as no alt text for a screen reader and I think it might help people see they need to write a better alt text for their images.

**Comment by zwiastunsw** [comment]
From the point of view of usability: an additional activity. 
From the point of view of accessibility: nothing is guaranteed. If someone doesn't want to fill in, he or she will mindlessly point out that it is a decorative image. 
If the decision is to be more conscious:
a) add a tip, for eg. Accessibility hint: Pass on the content of the image or leave it blank when the image is only a decoration
b) check with the accessibility checker (which I hope will be created), and give a warning.

**Comment by zwiastunsw** [comment]
If you add an additional checkobox, the result will only be that:
- the user will check this box often thoughtlessly
- you will need to add additional error handling - response to unchecked field and no alternative text

**Comment by chmst** [comment]
I repeat myself .. the description now is not informative and should be changed. But a checkbox is additional work for everyone. I asked some customers (and they work for organsiations for disabled persons). 
The editors always say: the intro image is decorative and enter nothing which results in alt="". A11y tools  will mention this as error, no matter if it is intended or not. 
I recommend a better label and an additional description.

**Comment by carcam** [comment]
@chmst 
>  I recommend a better label and an additional description.

I think this is the simplest and best approach as it avoids the extra check and allows people to know they are adding "decorative" images

**Comment by brianteeman** [comment]
> . But a checkbox is additional work for everyone. 

No it is only additional work for those people who do NOT add a description

**Comment by brianteeman** [comment]
> the user will check this box often thoughtlessly

as opposed to thoughtlessly ignoring the description all together - no problem there

> you will need to add additional error handling - response to unchecked field and no alternative text

that's super easy and not a valid reason

**Comment by brianteeman** [comment]
> I know that it's not recommended to use filenames in alt descriptions, but why instead of having that checkbox (which means an extra click), don't we just automatically fill in ALT text with image filename on image selection?

> In practice that will be the same as no alt text for a screen reader and I think it might help people see they need to write a better alt text for their images.

How will people see they need to write a better alt text. An accessibility checker will not report any error and how many users will test their site with a screen reader - which would be the only way they would know - other than a user complaining

**Comment by carcam** [comment]
@brianteeman yes, using filename as alt is a bad idea. I agree

In any case I don't see the need on adding the checkbox as it will add an extra check with not a valid reason as right now this works as expected.

A better labeling and description seems the way to go to raise awareness about A11y.

**Comment by brianteeman** [comment]
No it does not work as expected. All it does is to make it pass a test.

I thought you were the accessibility team not the pass a test team

**Comment by carcam** [comment]
I'm sorry to read that comment @brianteeman I would love to keep having a smart discussion about a11y without insults if possible 😉.

You have raised a good point with this issue, but we think a checkbox is an overkill. Current behaviour is fine from a technical point of view and having a better label and description will probably be much better for a11y than adding more technical stuff.

In any case if you want to provide a different explantion that could enlightened us and show why this checkbox is needed, we would love to keep checking into this.

Best!!

**Comment by brianteeman** [comment]
I have already explained it but you say its too much work

I have also reached outside of Joomla to get the opinion of an acknowledged expert in the field and he confirms what I said

> Blank alt should be a deliberate choice ("confirm this image is purely decorative" or somesuch) rather than the default. (I've just spent a month sorting out a client site because their marketing team didn't understand what 'image description' meant so ignored it for 700+ images, leading to an expensive law suit and remediation by me)

The EU funded accessibility project https://accessibilitycluster.com/ also confirms that it should be a positive choice to mark an image as decorative.

webaim also confirm that every image should have a description https://webaim.org/techniques/alttext/

Other CMS do exactly what I propose

I don't know what more I can do to convince you that you are wrong, that the current behaviour is not fine from a technical point at all.  I did not just come up with this crazy idea. This is what accessibility experts say is the correct thing to do.

**Comment by zwiastunsw** [comment]
Other CMS do not do exactly what you suggest. I know some (but maybe there are those who do). Among them you probably know Wordpress. Yes, there is a hint and a link to the decision tree in the W3C guide.
Bruce Lawson rightly wrote that this should be a RATHER conscious decision. This does not mean, however, that the decision will only be made if someone additionally confirms it with a checkbox. Such an additional step is recommended in WCAG in forms that send important legal, financial, etc. data.

**Comment by brianteeman** [comment]
... and that is why wordpress is acknowledged as being terrible for accessibility

**Comment by brianteeman** [comment]
> Bruce Lawson rightly wrote that this should be a RATHER conscious decision. This does not mean, however, that the decision will only be made if someone additionally confirms it with a checkbox. 

How else can you make a conscious decision? I am all ears if you know of a way to determine that it is a conscious decision to leave a field blank as opposed to a field just being missed or ignored. When you tell me how to determine that then I will write the code.

**Comment by richard67** [comment]
We can make a global config option "Ignore all accessibility requirements", and if it's set to Yes we could hide all alt text fields in backend ;-)

....

Don't kill me now, it was a joke ;-)

**Comment by brianteeman** [comment]
That is what we do right now and the accessibility team think that is ok ;(

**Comment by zwiastunsw** [comment]
Add to all fields of the Title checkbox: I confirm that this title describes the content because WCAG requires the title to describe the content. 
Add to all checkboxes when you have only one optional checkbox option: I confirm that this checkbox next to it wasn't selected deliberately. 
etc
Excuse me, I'm finishing my participation in this discussion.

**Comment by brianteeman** [comment]
> Excuse me, I'm finishing my participation in this discussion.

Great - Maybe we can make some progress with accessibility in Joomla now.

**Comment by zwiastunsw** [comment]
The fact that you are rude, everyone knows that. You don't have to keep reminding us about it. I am filing a complaint against you to the Joomla Board of Directors for violating basic rules: https://www.joomla.org/about-joomla/the-project/code-of-conduct.html

**Comment by brianteeman** [comment]
it is simply frustration that gets the better of me when I am hitting my head against a brick wall.

**Comment by richard67** [comment]
It was not my aim to provoke anything with my silly joke above. If I did: Honestly sorry.

**Comment by brianteeman** [comment]
I wonder if I changed the title to say Empty Alt Descriptions [SEO] it would have more impact with people

**Comment by mgifford** [comment]
As a Drupal accessibility maintainer I can say that Drupal goes further than what Brian is suggesting that Joomla do. Drupal requires users to enter alt text or alternatively has them explicitly confirm it is a decorative image. It should never be the default that an author who simply neglects to enter alt text should have that be assumed to be intentionally a decorative image.

**Comment by carcam** [comment]
@brianteeman 
> I have already explained it but you say its too much work

Well, but we state is not that it is too much work. We say that it adds an unnecesary action. We agree that you raised a good point, but our approach is much more about informing the user about this than adding a checkbox. I have not read your consideration for this approach.

> I don't know what more I can do to convince you that you are wrong, that the current behaviour is not fine from a technical point at all. I did not just come up with this crazy idea. This is what accessibility experts say is the correct thing to do.

We agree that this is an issue, we just do not agree on how to address it. As you know better than me, there are no technical guidelines to address some a11y issues and we have to do our own interpretation of the guidelines.

Our proposal from JAT is that instead of adding an extra checkbox which will definitely make the UX more complex, redefine the label and descriptions for these images. This will be definitely more informative and even could help to raise awareness.

Adding an extra checkbox for something that happens out of the box is making the interface more complex and has its counterside regarding accessibility. Adding an informative text or having a better description is simpler and provides more benefits.

**Comment by carcam** [comment]
Also @brianteeman, you mention on your first message about making the field compulsory and to be honest, we are more into explore this kind of approach.

For instance we could show an error if the alt is empty and then show the checkbox or allow a way to submit the form like adding double quotes or a white space to the form.

**Comment by brianteeman** [comment]
> I have not read your consideration for this approach.

It is clear from my response and the response of everyone not on the joomla accessibility team that your suggestion is not a good approach.

> redefine the label and descriptions for these images. 

Already did that in the very first post - see the image

> even could help to raise awareness.

As your proposal still hides the problem from an accessibility checker then it will not raise awareness. It will do the opposite.

> Adding an extra checkbox for something that happens out of the box

It should not be happening out of the box. that is the fundamental point that everyone outside of the JAT is saying

> and has its counterside regarding accessibility. 

such as?

> provides more benefits.

As everyone outside of the JAT has stated your approach does not.

>  you mention on your first message about making the field compulsory and to be honest, we are more into explore this kind of approach.

Jeez - that is exactly what it does. I was just being nice and not forcing it to be required. But instead of saying that you and the rest of the JAT team attack everyone and tell respected accessibility leaders like @brucelawson that he is wrong.

Instead of looking at the proposals you just look at who made them and then go on the attack.

I suppose the one good thing is that you have made more comments on joomla accessibility in github today than in the last 6 months (and yes that is unashamedly a dig)

**Comment by brianteeman** [comment]
Anyway I am going to close this. @zwiastunsw has been absolutely clear that he is correct and that this proposal is wrong and that everyone who says it is correct is also wrong. so I'm closing this and going back to reading my book and will just write a blog post

**Comment by richard67** [comment]
> We say that it adds an unnecesary action.

It add an action only for the case that you explicitly want to have an empty alt text for a decoration only image, with will be by far the minority of all images you add in content.

For the good guys who are already used in entering good alt texts for their images, there is no additional step.

**Comment by zwiastunsw** [comment]
Who wrote that Bruce Lawson was wrong and where? This is only written in your text.
See the solution in Drupal. You have a mandatory field. You have to type the alt text or "". Do exactly the same and then it will be fine. Your proposal is bad. Why - I wrote it.

**Comment by carcam** [comment]
@brianteeman Thanks for your reply.

At JAT we have not even suggested @brucelawson is wrong. Actually @marcodings told us he will be helping us in the future and we are eager for this collaboration, but I don't think he is meaning we have to add a checkbox to Joomla:

> Blank alt should be a deliberate choice ("confirm this image is purely decorative" or somesuch) rather than the default.

As I have stated several times on my comments: you raised a good point, we just think it needs a different approach to the solution.

**Comment by zwiastunsw** [comment]
> I am not sure about making it required (although I have done on a site I manage) but I am definitely in favour of

@brianteeman: Finally, you are inconsistent. You write yourself that you are not sure, but you strongly support it. You ask for a discussion. You are getting a discussion. Because we take what you write seriously. Instead of discussing, you insult because it does not agree with your idea. You use unfair eristic tricks. You benefit from the fact that you are fluent in language. And you do it with full awareness. This is despicable.

**Comment by HLeithner** [comment]
I'm locking this for the moment because the discussion is only off topic and personal, we can back to this topic later.
