### ISSUE TITLE
[4.0] joomla-alert

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#31135]
### Steps to reproduce the issue
1. Install Joomla 4 and do not select any option about basic statistics. 
2. Go to Extension install > Upload Package file
3. Upload a not valid zip file (an image for example)
4. Upload an extension

### Expected result
See the result (fail in case of not valid or success in case is valid).
Similar at when you try to save an article without title or user without info

### Actual result
The alert of collect statistic override the result

**Comment by brianteeman** [comment]
That's easy to resolve. Just complete the statistics collection

**Comment by brianteeman** [comment]
This should be closed as a non-issue
