### ISSUE TITLE
Uncaught TypeError: Cannot read property 'body' of null

### ISSUE THREAD

**Issue by Fritz-RT** [joomla/joomla-cms#31157]
I find several threads open about this, although they don't match to the contacts functionality.
I posted on the RT forum where they directed me to report this joomla bug to you.
https://rockettheme.com/forum/joomla-template-citadel/285290-uncaught-typeerror-cannot-read-property-body-of-null

### Steps to reproduce the issue
CREATE menu Item Type: Single Contact

### System information (as much as possible)
joomla 3.9.22
PHP 7.3.23
MySQL 5.5.5-10.3.25-MariaDB
multilingual website (all flags are green)

### Additional comments
Hoster ROCHEN
joomla website with Rockettheme Gantry5 Template (latest upgrades)

**Comment by jiweigert** [comment]
Not really helpful to post a URL into a members only forum.
Can you copy your error description from the forum into the Joomla ticket?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31157">issues.joomla.org/tracker/joomla-cms/31157</a>.</sub>

**Comment by Fritz-RT** [comment]
Here the thread:
>>
Uncaught TypeError: Cannot read property 'body' of null
Can you confirm that this error is in responsibility of the joomla cms?
I find several threads open on GitHub about this, although they don't match to the contacts functionality...
***
Yep, report to Joomla.
Regards, Mark.
<<
![error-joomla-forum](https://user-images.githubusercontent.com/20479536/96445666-93009e00-1210-11eb-9945-145652b6b009.jpg)

**Comment by ReLater** [comment]
It looks like you're using a Wrapper module or the Wrapper component on that page. Is the iframe content loaded correctly?

https://github.com/joomla/joomla-cms/blob/3.9.22/media/com_wrapper/js/iframe-height.js#L4

**Comment by Quy** [comment]
Closing due to no response.

**Comment by Fritz-RT** [comment]
Forgive me Bryan! I haven't received your post notification. I receive jet the closing note from Quy.

The iframe works well (the booking engine you see below); it was integrated according to the gantry5 procedure as a custom particle. However, I noticed that the error is given only by chrome (Vers. 86.0.4240.111 - 32 bit) and not by firefox. I have to assume that, once again, the responsibility lies with a standard imposed by this browser rather than a coding error.
