### ISSUE TITLE
Incomplete removal of PSR0 support in JLoader

### ISSUE THREAD

**Issue by SniperSister** [joomla/joomla-cms#31159]
### Steps to reproduce the issue
In J4, the psr0 support in JLoader has been removed by removing the corresponding loader method:
https://github.com/joomla/joomla-cms/commit/7b9e1fcfbc19923a862d1d0794b4d994ab884aef#diff-91bf39a138bdc0126d116d281764e6278d2945cd29f5bec5374e7b2493dff585

However, code using that loader now silently fails in J4 as the rest of the code has not been adjusted to the removal, see: https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/loader.php#L441

@wilsonge @laoneo has this just been overlooked? Or did this happen on purpose?

### Expected result
Exception being thrown if psr0 is used.

### Actual result
"Silent" fail of class loading.

**Comment by laoneo** [comment]
overlooked

**Comment by laoneo** [comment]
Please test #31188.
