### ISSUE TITLE
Documentation: CustomFields wrong method

### ISSUE THREAD

**Issue by nadjak77** [joomla/joomla-cms#31167]
### Steps to reproduce the issue

https://docs.joomla.org/J3.x:Adding_custom_fields/Implement_into_your_component/en
![grafik](https://user-images.githubusercontent.com/37655645/96545890-8f6d2580-12a9-11eb-8203-622fa121b773.png)
the method setValue do not exist.
It has to be setFieldValue() with the arguments $fieldID, $item->id and value

### Expected result
description with setFieldValue()

### Actual result

description with setValue()

### Additional comments
Thanks for changing

**Comment by SharkyKZ** [comment]
Updated. Thanks for reporting.
