### ISSUE TITLE
Custom field "Image list" don't use custom image path from media parameters

### ISSUE THREAD

**Issue by PascalNetenvie** [joomla/joomla-cms#31162]
### Steps to reproduce the issue
Create a new "files" folder at root, then create an "images" sub-folder in it, then create a "test" sub-folder in it.
Result should be : website_root/files/images/test
Change images path in media manager parameters to : files/images

Setup a new custom field, select "images list" type and try to choose test from folder parameter in first tab.

### Expected result
We should see "test" folder in list.

### Actual result
We get "website_root/images" content in list.

### System information (as much as possible)
Joomla 3.9.22.
Linux Debian 9.

**Comment by SharkyKZ** [comment]
Image list field has no relation to Media component.

**Comment by PascalNetenvie** [comment]
Sorry but it have ...
![2020-10-20_02-26-33](https://user-images.githubusercontent.com/8863533/96525636-c7f60a80-127b-11eb-99db-92b7ceb2cf9e.png)

**Comment by SharkyKZ** [comment]
The description is wrong.

**Comment by PascalNetenvie** [comment]
Ok but if we are logic it should be like this ...
Almost all extensions or function that need to get an image look for this parameter's value ...
Whatever i fixed this problem with symbolic link on server but it should be more easy ...

**Comment by SharkyKZ** [comment]
See PR https://github.com/joomla/joomla-cms/pull/31170 for correcting the string.

I don't see why we're forcing this to be a subdirectory in images folder. Would make sense to allow other directories. But this should not be tied to `com_media` in any way.

**Comment by PascalNetenvie** [comment]
Ok for the string correction.
But why this should not be tied to com_media in any way ?

**Comment by jiweigert** [comment]
I guess simply because someone could use a different media(-manager),but still would have to use part of its configuration (image path)?
Having a string(-list) in either configuration.php (or db-like) of image-dirs would help to create a array of dirs for public images..

 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31162">issues.joomla.org/tracker/joomla-cms/31162</a>.</sub>

**Comment by PascalNetenvie** [comment]
Ok i understand the idea but as the only one place to configure media root and images path are in com_media,
why not rely on it ??

**Comment by PascalNetenvie** [comment]
Or there should be a path parameter in field ...

**Comment by infograf768** [comment]
@SharkyKZ 
I guess the filesystem plugin and adapter could be used in J4 to allow the paths proposed for this plugin.
Hard work or possible?
