### ISSUE TITLE
[4.0] Language Debug stars in sample data

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#31160]
### Steps to reproduce the issue
Enable language debugging on a fresh installation, then install sample data (blog or testing).

### Expected result
Titles and texts are stored as usual

### Actual result
Titles and texts have surrounding ** from language debugging

### Additional comments
Blog sample data are work in progress in cassiopeia, but this is also in testing sample data and probably also in J 3.x

**Comment by infograf768** [comment]
confirmed

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/33209

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33209 . Thanks in advance.

**Comment by PhilETaylor** [comment]
PR rejected as as a "won't fix"

**Comment by brianteeman** [comment]
The rejection was wrong!!!

**Comment by brianteeman** [comment]
Please re-open this as the PR was rejected

**Comment by brianteeman** [comment]
Please test #44624

**Comment by richard67** [comment]
Closing as having a pull request. Please test #44624 . Thanks in advance.
