### ISSUE TITLE
Orphaned menu item causes module menu assignment to break

### ISSUE THREAD

**Issue by waveywhite** [joomla/joomla-cms#31161]
### Steps to reproduce the issue
1. Create a menu tree with child menus
    e.g:
   menu1
     |-parent
       |-child
  menu2
    |-menuitem
    |-anotheritem

2. Somehow (not sure how our site admins did this), remove the parent to orphan the child menu
   menu1
       |-child
  menu2
    |-menuitem
    |-anotheritem
3. Go to com_modules and create a new module
4. Attempt to assign the module to a specific menu item

### Expected result
You can assign the module to a specific menu item

### Actual result
The menu item tree goes haywire due to too many close tags being rendered in the HTML

### System information (as much as possible)
Joomla 3.9.21
PHP 7.2.24-0ubuntu0.18.04.7

### Additional comments
The error appears to be in administrator/components/com_modules/views/module/tmpl/edit_assignment.php . The code assumes that you can only go up one level at a time but can go down multiple levels. So, if the assumption is broken you end up with too many close tags.

**Comment by brianteeman** [comment]
If you rebuild the menu does the problem resolve itself?

![image](https://user-images.githubusercontent.com/1296369/96568570-00b7d300-12c0-11eb-9c0f-c15a321b82ae.png)

**Comment by waveywhite** [comment]
Hi Brian,

I just tried it on a duplicate of that site and it doesn't resolve the issue. The orphaned menu item remains in that state and the module menu assignment is still broken. What does resolve it is trashing the problem menu item. Presumably, re-parenting it would also work.

-David.

**Comment by chmst** [comment]
I thought, this was resolved years ago, so that a menuitem cold not be trashed if there were articles in any menu item in the tree.

**Comment by waveywhite** [comment]
Can a menuitem be moved to another menu without its children? It looks like this could have happened.

There seems to be two issues, the first is that somehow the website admins managed to orphan menu items, and the second is the assumption in com_modules that orphaned menu items can't exist.

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc [@zero-24](https://github.com/zero-24)
