### ISSUE TITLE
500 whoops error on set up

### ISSUE THREAD

**Issue by Flying-Badger** [joomla/joomla-cms#31173]
### Steps to reproduce the issue
Just installed Joomla 4.0.0 Beta 3
Chose to go to my site after removing installation folder

### Expected result
To go to home page with new installation

### Actual result
Got the following message;

Oops! An Error Occurred
The server returned a "500 Whoops, looks like something went wrong.".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by ChristineWk** [comment]
Maybe relevant: https://docs.joomla.org/J4.x:Upgrade_to_4.0_Beta_4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31173">issues.joomla.org/tracker/joomla-cms/31173</a>.</sub>

**Comment by chmst** [comment]
Please give System information (as much as possible). And if you make a new installation: use the newest beta.

**Comment by Quy** [comment]
Please test with the nightly builds: https://developer.joomla.org/nightly-builds.html

**Comment by adj9** [comment]
It happened to me too with beta5. The error appears to me even if I access the backeend. 
If I don't remove the installation folder, I can safely access the site. 
Has something been changed?

**Comment by SharkyKZ** [comment]
Please enable debug in `configuration.php` and post stack trace.

**Comment by jwaisner** [comment]
@Flying-Badger Please post requested information.
