### ISSUE TITLE
Create uniform payment interface layer in J! 4

### ISSUE THREAD

**Issue by EricdeWaal** [joomla/joomla-cms#31172]
Each extension (shops, memberships, tickets, forms) currently has it's own payment plugins.
One for each credit card, one for PayPal, bank gateways, etc. 
As a user, if the e-commerce extension does not support the preferred way of payment in my country, I can only hope there is a third party system which can act as an intermediate. Most provide plugins for some e-commerce extensions, but not all. In a small country this limits the possibilities.
The way payments are now handled in Joomla! makes me think of ancient MS DOS times, where each program needed to have it's own printer driver for each printer.

Would it be possible to have an intermediate, Joomla! core layer for the communication with the e-commerce extension, and where payment plugins can be used to communicate to the outside world?

It would make life a lot easier for the extension makers, they can focus on the e-commerce extension itself.
And it would be a lot more interesting to develop a plugin for the smaller and more exotic ways of paying since they can be used for all extensions.

**Comment by SharkyKZ** [comment]
Not likely. See discussion https://github.com/joomla/joomla-cms/issues/24746.

**Comment by EricdeWaal** [comment]
@SharkyKZ Well, I must admit that I overlooked the thread that you mentioned above.
On the other hand, what was suggested there goes a lot further than what I meant.

My idea is just a core api, where the e-commerce extensions send their uniform payment initiation to (currency, amount, ordernumber etc). And which of the installed payment plugins should handle it further.
The plugin (which can be made by the e-commerce extension or any third party) contacts the gateway, handles the payment and sends back the (uniform) results to the e-commerce extension. Maybe writes a log.
That way any e-commerce extension can use any payment method installed.

So no big amounts of code that are rusting away, just an easier way (interface) to connect the e-commerce and payment extensions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31172">issues.joomla.org/tracker/joomla-cms/31172</a>.</sub>

**Comment by dgrammatiko** [comment]
Let me re post my answer to the previous (similar) request:
> @mbabker is right not only for the reasons stated above but mainly because the W3C already solved this problems for us (devs) with the payment API:
> https://caniuse.com/#feat=payment-request
> 
> https://developer.mozilla.org/en-US/docs/Web/API/Payment_Request_API
> 
> It would be nice to check the state of the web periodically, things do evolve...


And just add that **if ever** Joomla implements something about payment that can **only** be based on payment-request: https://caniuse.com/#feat=payment-request

**Comment by EricdeWaal** [comment]
@dgrammatiko this might take years to become a standard, if it succeeds at all.
And it only works if everybody from browsers to merchants (our e-commerce extensions) to banks, credit card companies, PSP's etc adopt this way of handling payments. Might takes ages or not happen at all.

**Comment by Quy** [comment]
@HLeithner Move to Discussions?

**Comment by HLeithner** [comment]
not possible at the moment, github doesn't allow moving issues to discussion since a couple of days

**Comment by HLeithner** [comment]
I'm closing this and can be reopened in discussions again.
