### ISSUE TITLE
Joomla Update on Joomla 4: Check for updates sends me back to the site's frontpage.

### ISSUE THREAD

**Issue by nikosdion** [joomla/joomla-cms#31187]
### Steps to reproduce the issue

Log in to Joomla 4 beta 4 backend.

Go to System, (Update) Joomla and click on Check for Updates.

### Expected result

Updates are checked and I'm back to Joomla Update (/administrator/index.php?option=com_joomlaupdate).

### Actual result

Updates are checked and I'm in the frontend of the site (/index.php?option=com_joomlaupdate) which of course throws a 404 error with an equally confusing success message reading "Checked for updates".

**Comment by ghost** [comment]
Cant confirm, got:

![Screen Shot 2020-10-21 at 13 37 39](https://user-images.githubusercontent.com/71960554/96714587-a80d3680-13a2-11eb-8c93-105a0902a7ba.png)

**Comment by nikosdion** [comment]
I am on beta 4. Could this be the issue? Similar problems in other components with beta 2 were solved somewhere between beta 3 and 4.

**Comment by brianteeman** [comment]
Can't confirm either using nightly

**Comment by nikosdion** [comment]
Probably just a beta 4 issue. I'll close this issue, then. Thank you for the feedback!
