### ISSUE TITLE
[4.0] Misleading tooltips in overviews when workflow is enabled

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#31183]
### Steps to reproduce the issue
Enable workflow, got to Articles overview.
When workflow is enabled, setting status and featured is only possible via transitions. 

### Expected result
Buttons for status changes are diabled
Tooltips say "change status via transition".

### Actual result
![workflow-tooltips](https://user-images.githubusercontent.com/1035262/96707671-7abb8b00-1398-11eb-9ac1-8903cd302246.gif)

**Comment by brianteeman** [comment]
Not so much a misleading tooltip (which BTW should not be a popover)  as the wrong information. There would need to be a different message when the item is in a state that can be featured and and when it is in a state when it can not be featured

**Comment by chmst** [comment]
exactly

**Comment by brianteeman** [comment]
I guess this can be closed as there is more information on the same problem in  #33574

**Comment by brianteeman** [comment]
Close ?

**Comment by chmst** [comment]
thank you - yes it  is resolved.
