### ISSUE TITLE
Wrong font size in backend, revisited

### ISSUE THREAD

**Issue by nikosdion** [joomla/joomla-cms#31184]
As I had already reported months ago, the default font size in Atum is too big. Yes, I understand that's the default Bootstrap and browser size albeit technically it's not exactly that.

First of all, Bootstrap 4's SCSS does allow you to set a different base font size instead of 1 rem. It's documented in it. Setting it to 0.875rem seems to be a better default and in line with literally every other site out there. I tried to file a PR to do that on the fly as we had discussed but I was told it's wrong even though that's exactly what we had agreed on AND what Bootstrap 4 recommends doing.

Furthermore, changing the font size from the browser's settings is not a viable solution for two reasons:

1. It affects all sites, not just Joomla. Since all other sites using rems instead of absolute pt/px sizes set a base font size between 0.8 rem and 0.9 rem they end up with type too tiny for me to read.
2. Chromium-based browsers such as Google Chrome, Microsoft Edge, Opera, Brave etc DO NOT have the option to change the based font size beyond "small", "medium", "large". The step from "medium" (16pt) to "small" is massive. One is too big to fit in the laptop display, the other is too small to read without a magnifying glass.

I honestly think that the right solution is changing the base font size as Bootstrap recommends. Since this is not something you want to consider I am asking you to find a magic solution. I am not going to participate further in the discussion as I've already told you why it's a problem and you have already rejected my solution (even though you agreed to it initially – and then you have the gall to tell me I'm "difficult" on Twitter, sigh). All I want is to be able to freaking use Joomla 4's backend WITHOUT having to add custom CSS. Is it too much to ask?

**Comment by brianteeman** [comment]
see #31191

**Comment by nikosdion** [comment]
Your PR doesn't change the font size, it only changes the calculations in SCSS. You'd still need to recompile Atum's SCSS every time you want a different font size and it'd apply globally (all users) which we said it's wrong when we discussed in length about it between April and September.

The only _viable_ way to make it all work correctly that *I* can see is having a base font size given as a client-side variable e.g. `var(--joomla-base-font-size)` with a default of `1 rem` set **in the template options**. A control in the accessibility settings could change that variable the same way you've been able to change colors in Joomla 3 (and Atum, only that user-facing controls were yanked away).

This of course means that the calculations in your PR would have to be removed from SCSS side and done client-side. If I'm not mistaken (haven't checked) you could do something like `$h1-font-size:                     calc(var(--joomla-base-font-size) * 1.65);`. I am not sure if SCSS would like you for doing that because I _THINK_ (without having checked; I may be wrong) that BS4's SCSS expects to see a compile-time calculated value there.

If using the var trick doesn't work then what you did is half of the solution, the other half being setting the font-size of the html element in CSS to modify the value of the rem unit. This is why my PR was doing exactly that but it was rejected. So my conclusion is that if you can't use var calculations in CSS you are completely sodden because changing the backend size requires recompiling SCSS and applies to all users, shooting down accessibility.

FWIW I have written a small plugin which sets the HTML element's font-size and I'm happy using that on my own site. I just want to know what the CSS luminaries in this community think is the best solution. Recompiling SCSS, accessibility be damned? Client-side calculations? Changing the HTML font size? Or nothing at all because who cares if real world people can use Joomla on real world computers which are primarily laptops (especially now, during the necessary work from home environment due to the Covid-19 pandemic)? I am asking because I heard as many opinions in my PR and not a single person would have the balls to come out and say "this is what we have to do and this is why, here are the references".

**Comment by brianteeman** [comment]
Ah I didnt realise you wanted it to be user defined

**Comment by nikosdion** [comment]
I can recompile SCSS anytime I please. It's how I am doing my custom J4 front end template. It doesn't make sense for Atum though. My changes would possibly be overwritten every upgrade and it would force all admins to use the same font size. That would be shooting our feet w.r.t. accessibility.

**Comment by brianteeman** [comment]
I am very confused. 

> I honestly think that the right solution is changing the base font size as Bootstrap recommends.

thats what i did

**Comment by nikosdion** [comment]
OK, let me expand even though it's just a revisit of the discussion we had between April and September. 

Bootstrap says that you can change the base font size and everything else will follow suit. They tell you that you can use either rems or fixed point units BUT they advise against fixed units for accessibility reasons,. Fair enough.

First problem in Atum: changing the base font size doesn't make other sizes follow suit. That's what you fixed. Awesome. It's necessary and I wholeheartedly support merging that change.

Second problem. Atum is multi-user and each one has a different font size preference. _As we had earlier discussed, months ago,_ this makes ANY arbitrary font size decision wrong for some users. Something like 0.875rem would be great for the overwhelming majority of users (because Joomla would be the same scale as everything else on their computer) BUT would annoy people who prefer larger font sizes and stubbornly refuse to change their OS or browser scale (zoom level).

So, based on our discussions here on this repo in the past, we cannot change the base font size to anything other than 1 rem because of this stark minority. I think that's a cop out. But this being the consensus of the loudest voices in the room I shut up and rolled with it.

This means that the only way to move forward, as you had said yourself, is to have the base font size be part of the accessibility settings of Joomla. This is what I implemented, because this is what you all asked me to. When I submitted the PR the same people were telling me that implementing exactly what they asked me to do is all sorts of wrong. I closed the PR because that sounded like crazy and I don't have time for crazy. Apparently some people think that makes me "unreasonable" and "impossible to work with".

So I am asking these geniuses to come up with a solution to the impossible situation where they are asked to do X without doing X because X is simultaneously the solution they propose and a bad idea they reject. Come on, let me see how you can be reasonable and easy to work with under these conditions.

As for what I personally believe the best technical solution is: the base font size in SCSS should be 0.875rem and everything should be based off that size (your fix). This makes Joomla consistent with literally EVER. SINGLE. OTHER. REAL. WORLD. SITE. I. VISIT. WITH. MY. BROWSER. This means I need to only worry about one (1) scale for all sites. Not have a separate browser just for Joomla 4's backend. If there are any users who can't use the OS-level accessibility settings they can use the browser's zoom level. Of course it applies to all sites and gets us back to the problem that other sites are affected but AT LEAST since Joomla is in the same scale as other sites and user's eyesight doesn't magically get better or worse based on which site they are on they will only need to set the zoom level ONCE, FOR ALL SITES. But maybe this solution is too simple and elegant to be included in an over-engineered design-by-committee mess of a CMS like Joomla. Dunno. I will let the blathering geniuses figure it out.

**Comment by brianteeman** [comment]
I do not see the need for this to be made configurable in the admin. I dont believe that you would have been suggesting it should be configurable if it had been at 0.875 originally. So we should just check and complete #31191 and stick with that.
