### ISSUE TITLE
[4.0] JS validation for required fields did not work for multiple checkboxes and list field types

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#31194]
### Steps to reproduce the issue
Add a multiple form field to an xml and load the field in a validate form view

XML Field like:
`
<field name="test" type="checkboxes" multiple="true" required="true">
    <option value="test1">test1</option>
    <option value="test2">test2</option>
</field>
`

Then try to submit and you see, that the client side form js validation did not work

### Expected result
JS Feedback "required field" should be shown

### Actual result
Nothing, form submits without any error

### System information (as much as possible)
Joomla! 4.0.0-beta4 Beta [ Mañana ] 15-September-2020 13:46 GMT 

### Additional comments
Same problem on list field type

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/31196.
