### ISSUE TITLE
Unable to reorder featured articles on an Ipad / Iphone

### ISSUE THREAD

**Issue by dandpclements** [joomla/joomla-cms#31192]
Featured articles are reordered using a drag and drop tecnhnique. This doesnt work on an iPad. In a prior joomla  release (2.5?) I believe reordering was possible as it used up / down buttons or a number sequence? 

With the development of tablets it is now perfectly feasible to manage a site from a tablet as opposed to a pc. However this is one limitation that stops full maintenance being possible 

 

### Expected result

Able to reorder featured articles

### Actual result

Nothing happens on ipad

**Comment by brianteeman** [comment]
Should be closed as a duplicate
