### ISSUE TITLE
__construct return false do not avoid plugin loading

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#31208]
### Steps to reproduce the issue
return false in a plugin constructor function "__construct"

### Expected result
the plugin shall not be loaded with the "JPluginHelper::importPlugin($group)" function

### Actual result
the plugin is loaded, even if the constructor returns false

### System information (as much as possible)
tested with Joomla 4 beta 4 >> problem
tested with Joomla 3 >> it works as expected

**Comment by SharkyKZ** [comment]
Duplicate issue https://github.com/joomla/joomla-cms/issues/24913.
