### ISSUE TITLE
[4.0] Remove obsolete Bootstrap classes in forms and fields

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#31218]
Forms (e.g. login form from com_user) and fields (layouts/joomla/forms/renderfield.php) are still using classes from Bootstrap 2: control-group, control-label, controls

That should be changed to classes from Bootstrap 4: form-group without extra div for label and input
https://getbootstrap.com/docs/4.5/components/forms/

**Comment by hans2103** [comment]
oh boy.. that's a nice one to solve

**Comment by brianteeman** [comment]
ITs  not an easy one. There is both markup and css to change AND we would need to keep the existing css for extensions - its too late in the process to change that and force extensions to update

**Comment by PhilETaylor** [comment]
This is one of only 2 outstanding issues flagged with the Joomla 4.0 Milestone. Please can we move the milestone else Joomla 4 Milestone will never reach 100%. Thanks.

**Comment by drmenzelit** [comment]
Done

**Comment by coolcat-creations** [comment]
Can this issue be closed? If not: What's the prefered solution?
Extension Devs could maybe use the @extend Command to apply their classes on the (probably) new markup.

**Comment by chmst** [comment]
@drmenzelit is this still an issue for you?

**Comment by drmenzelit** [comment]
As Brian wrote, it is too late for Joomla 4. We will need to reconsider this for Joomla 5. I'm closing this for the moment.

**Comment by coolcat-creations** [comment]
Why closing and not labeling for Joomla 5 with a release blocker? Otherwise it would be again too late or forgotten.
