### ISSUE TITLE
[4.0] /vendor/ disappeared from /libraries/

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#31239]
Any reason why /vendor/ folder disappeared from /libraries/ folder in github package?

**Comment by SharkyKZ** [comment]
You have to run `composer i` and `npm i` to install dependencies and compile assets when running from Git clone.

**Comment by ghazal** [comment]
Ah  OK . Thank you.
I am struggling with composer 2 (2.0.2) (see #31234)
I guess you mean composer install and npm install (I use npm ci) ?

**Comment by ghazal** [comment]
I'll close this issue. My question was stupid. 
Nevertheless there is a version pb with phpcodesniffer.
