### ISSUE TITLE
[4.0] Composer 2 and phpcodesniffer-composer-installer pb

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#31234]
Just installed Composer 2 (v.2.0.1). 
Looks like it requires phpcodesniffer-composer-installer v0.7.

But composer.lock is still requiring phpcodesniffer-composer-installer v0.6.2 and Composer 2 doesn't like it.

Ref : Support Composer 2.0 by jrfnl · Pull Request #111 · Dealerdirect/phpcodesniffer-composer-installer
https://github.com/Dealerdirect/phpcodesniffer-composer-installer/pull/111/files

**Comment by HLeithner** [comment]
Please use composer 1 for now.

**Comment by ghazal** [comment]
OK. I upgraded correctly phpcodesniffer-composer-installer to 0.7 but it initiated another issue.
So I am closing this one.
