### ISSUE TITLE
Edit Article Layout CSS problem on small screen laptops

### ISSUE THREAD

**Issue by pnkr** [joomla/joomla-cms#31230]
### Steps to reproduce the issue
Create or edit an article
At my laptop, Lenovo Yoga 530, at the sidebar, the tag select appears wider than the rest and goes out of the border.
![screen shot 2020-10-25 at 10 09 25](https://issues.joomla.org/uploads/1/5180aebd6c180527994f5695dedf445c.jpg)

The CSS problem is at this css class:

.control-group .controls {
    position: relative;
    flex: 1;
    min-width: 210px;
}

a more safe option it would be this

.control-group .controls {
    position: relative;
    flex: 1;
    min-width: 210px;
    max-width: 100%;
}

With this second approach it cannot get out of the main area borders.

**Comment by ghost** [comment]
Duplicate #27907
