### ISSUE TITLE
[4.0] Scrollbar on list in  Global Configuration

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#31232]
Is this expected?

![image](https://user-images.githubusercontent.com/1497730/97107339-482ace80-16c7-11eb-8bc9-62b81721846b.png)

**Comment by Quy** [comment]
Due to PR #31092 so you don’t have to scroll the page down to see the other menu items but can be considered an issue on a large monitor as reported in #31147.

**Comment by bembelimen** [comment]
Yep, expected behaviour.
