### ISSUE TITLE
Accessibility options 

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#31240]
### Steps to reproduce the issue
Activate the Accessibility plugin.

A strang thing is that the 'Accessibility Options' are not accessable (can't reach it with the TAB button).
This is for both the backend and the frontend.

And even if you open the options you can't Tab through the options itself.

Second: The 'Close' and 'Reset' options can't be translated.

**Comment by jwaisner** [comment]
@MartijnMaandag can you provide information such as the Joomla Version you are using when this occurs?

**Comment by MartijnMaandag** [comment]
It is about Joomla 4.
I understand accessibility is an important thing in Joomla 4.
I do have a friend who is almost blind. When I see him accessing a site he is using the TAB-key to move through screens. Every item he reaches whith a TAB is read by a screenreader, so he can hear whats on the screen.
Every item which he can't reach with a the TAB-button he can't 'see'.
That's what I meant with my issue.

I did have a closer look at the accessability of the backend.
On the Articles detail screen (Content) it is impossible to reach the tabs "Images and links", "Options", "Publisching", "Configure Edit Screen" and "Permissions" with the TAB-key. So a blind person will never find these tabs. 
I think there is a accessibility team within Joomla, can they have a look at this?

**Comment by hans2103** [comment]
- Joomla 4
- Go To Content > Articles > Open an article to edit.
- Press tab key on your keyboard until tab with title = Content has focus.
- You can press as many tab as you want, but never reach tab with title = Images & Links

<img width="1483" alt="Schermafbeelding 2020-11-09 om 20 51 57" src="https://user-images.githubusercontent.com/639822/98589379-761a3080-22cd-11eb-87a9-4bef41365806.png">

update: just found out that using the arrow key I can toggle between tabs. 
I'm not blind or ever using keyboard to navigate... But does a keyboard user know that the arrow key has to be used when on an `<ul>` with `role="tablist"`?

**Comment by hans2103** [comment]
Back to the original issue 


- Joomla 4 administrator
- Go to System > Plugins
- Activate "System - Additional Accessibility Features"
- A wheelchair icon appears bottom left on my admin.
- I am not able to reach that button using only my keyboard. 

That seems to be the issue... accessibility button is not reachable
It does not appear in the SkipTo links

**Comment by brianteeman** [comment]
Looks like I forgot to enable the hotkeys
https://ranbuch.github.io/accessibility/

**Comment by richard67** [comment]
Closing as having a pull request. Please test #31372 .

**Comment by richard67** [comment]
Ah, no need to test anymore, it has already enough good tests and is ready to commit.
