### ISSUE TITLE
[4] Differently compiled CSS in atum template.(min.).css

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#31244]
### Steps to reproduce the issue
I'm confused that in today's nightly the [new SCCS from 30873](https://github.com/joomla/joomla-cms/pull/30873/files) is compiled differently:

#### atum/css/template.css:
`background-attachment: initial !important;`

#### atum/css/template.min.css:
`background-attachment: scroll !important;`

### Expected result
- In both `*.css`: `background-attachment: initial !important;`

### Actual result
- Different values for `background-attachment:`

**Comment by ghost** [comment]
That is fine: The initial CSS keyword applies the default value of a property to an element. initial is the same as scroll in this case

**Comment by ReLater** [comment]
But why not in both CSS files? All rules should be identical for debug purposes.

**Comment by astridx** [comment]
I do not know why, but:  That is made by [cssnano](https://cssnano.co/docs/optimisations/reduceinitial) in the file `joomla-cms4/build/build-modules-js/stylesheets/scss-transform.es6.js `
And this runs only for `*.min.css` - only makes sense for minfied

**Comment by brianteeman** [comment]
I would say that this is intended and expected behaviour

**Comment by ReLater** [comment]
> I would say that this is intended and expected behaviour

I'm leaving this issue with a LOL...

**Comment by infograf768** [comment]
I guess we can close this.
