### ISSUE TITLE
[4.0] Backend - new/edit screen - right panel: size of select fields

### ISSUE THREAD

**Issue by max123kl** [joomla/joomla-cms#31258]
### What needs to be fixed
(1) The width of the selection fields should not exceed the right margin if the displayed string is slightly longer and the window is narrow. In the best case, the fields should be equally wide (see blue line).

![designfehler](https://user-images.githubusercontent.com/853497/97431270-53c20380-191a-11eb-8bf5-43b2494cfe9c.png)

### Why this should be fixed
The checkmark in the selection field could disappear completely – then the selection field is no longer functional.
The strings in some translations are much longer than the English ones.

### How would you fix it
The height of the checkboxes could be variable and do allow a conditional line break (like in figure 2).

### Side Effects expected
The overall height of the right panel will increase. But this should not be a problem when displaying.

**Comment by ghost** [comment]
5th duplicate report #27907
