### ISSUE TITLE
[4.0] FontAwesome is loaded twice

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#31257]
### What needs to be fixed

For some reason FontAwesome is still stuffed in main template files but it should be (and is) loaded from media/vendor directory.

### Why this should be fixed

Bad code, bad frontend performance.

### How would you fix it

Remove from `template.css`.

### Side Effects expected

No.

**Comment by N6REJ** [comment]
@SharkyKZ can you clarify please?  I see that its loaded in <header> but don't see that happening in the code.
Removing it from /template.scss crashes FA

**Comment by SharkyKZ** [comment]
This is only in Cassiopeia. Atum loads it correctly only once.

Closing as  there is PR https://github.com/joomla/joomla-cms/pull/31262.
