### ISSUE TITLE
[3.10] Warning - Could not delete folder

### ISSUE THREAD

**Issue by TorbjornN** [joomla/joomla-cms#31259]
### Steps to reproduce the issue
In the Joomla Update Component Option, switched the Update Channel to “Testing” and the Minimum Stability option to “Alpha”. Then updated to Joomla version 3.10.0-alpha3.

### Expected result
Update to 3:10 without warning

### Actual result
Updated the Joomla version to 3.10.0-alpha3. Update seems OK. Got this warning :
"WARNING
Joomla\CMS\Cache\Storage\FileStorage::_deleteFolder JFolder: :delete: Could not delete folder. 
Path: .../cache/gantry5/g5_helium"

### System information (as much as possible)
Joomla 3.9.22, Gantry 5, Helium template

### Additional comments
I will delete cahe manually and continue update to 4 using custom url.

**Comment by zero-24** [comment]
Hmm can you provide me a backup to tobias.zulauf[at]communiy.joomla.org or a clear step by step with your setup and gantry so i can take a look and try to debug? Can you check that permissions are given to that folder in your system?

**Comment by TorbjornN** [comment]
Gantry 5 Helium is a no-no at the moment.
![joomla4_Gantry_Helium_not_supported](https://user-images.githubusercontent.com/18717358/97464347-b5916600-1938-11eb-94a3-4b0dc1629561.JPG)

I'll have to start again from 3.9.22

**Comment by zero-24** [comment]
> Gantry 5 Helium is a no-no at the moment.

Is that template marked as `ready for 4.x`? Seems they are using isAdmin that got removed from 4.x and should now be isClient("administrator");

**Comment by zero-24** [comment]
As for the issue mention above about the cache stuff it seems we had similiar issues in the past that where timing issues on cleaning the cache? (thanks @ChristineWk)

https://github.com/joomla/joomla-cms/issues/18517

**Comment by tramber91** [comment]
Hi
For info
>"RocketTheme is working to ensure its current and growing Gantry 5 library of templates will receive updates for Joomla 4. We hope to provide package downloads of our Gantry 5.5 framework soon, which will be compatible with the beta and stable versions of Joomla 4."
*dixit RocketTheme*

So need to wait about Gantry **5.5** for *Gantry 5 template* (Gantry 5.4.36 today) and recheck.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31259">issues.joomla.org/tracker/joomla-cms/31259</a>.</sub>

**Comment by ghost** [comment]
@TorbjornN please close issue
