### ISSUE TITLE
Wrong PHP version find by Joomla 7.2.34 instead of 7.3.34

### ISSUE THREAD

**Issue by shim-sao** [joomla/joomla-cms#31260]
### Steps to reproduce the issue
The php version find by Joomla is wrong for php 7.3

Install PHP 7.3
Command line `php-v` : 7.3.34
Go to Joomla system information : 7.2.34

### Expected result

System information : 7.3.34

### Actual result

System information : 7.2.34

### System information (as much as possible)
Multiple server on Linux local or provider
Centos 7 / Fedora 32 and others distributions

**Comment by zero-24** [comment]
Hi can you check what the php info output on that server looks like

**Comment by brianteeman** [comment]
command line php is often a different version

**Comment by shim-sao** [comment]
Thank you for responses.

I'm not agree, the version should always be the same (if you don't use multiple install).
 
The version is now the same on my local computer after a reboot.
Sorry about that, It's completely my fault, we have to restart Apache.

I have therefore just noticed that some provider such as OVH do not restart Apache after a PHP version change.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31260">issues.joomla.org/tracker/joomla-cms/31260</a>.</sub>

**Comment by brianteeman** [comment]
The version of PHP available from the command line has 100% nothing to do with the version of PHP loaded as a module. These are completely separate things.

**Comment by shim-sao** [comment]
I know ;)
It's why the provider OVH doesn't make its job. I didn't pay attention until I got the alert in Joomla (end of 7.2 support...)  and reinstall my own Centos in local.
I need to contact them to report changes made on the cpanel and CLI to Apache conf.

_CLI vs apache.conf_

**CentOs/Fedora** :
```
sudo yum-config-manager --disable remi-php72
sudo yum-config-manager --enable remi-php73
```

**Windows** : this kind of thing can't happen for me because I do all manually (no Xamp), the same folder specified on the _environment variables_ and the _apache.conf_, that's all for only one PHP version installed.

On all cases, Apache need to be restarted, it's logical.

It can always help someone who comes across this post

**Comment by brianteeman** [comment]
> On all cases, Apache need to be restarted, it's logical.

Thats not true - php cli runs without any reference to apache. Why would it. 

The example change you post is just one way to change the php version and its highly unlikely ovh do it that way. 

So while it helped you the post is unlikely yo help anyone else

**Comment by shim-sao** [comment]
I never say CLI and apache.conf have reference eachother on the contrary.

I think that I express myself badly in writing and that therefore you do not understand what I want to explain

On all cases (Linux, Windows, Mac) = when you change something on the apache.conf _(I don't talk about CLI at all)_
Apache need to be restart, so don't forget it. You can't say it's not true.
If you can do it without restart it, I really want to learn how.

With a simple update of PHP, Linux do the changes alone on http restart, on Windows I write by hand the changes, I can specify the repository I want and it is not necessary the same as the CLI, same thing, restart apache to take changes. 

It's why, on OVH mutual account, after change of PHP version in the cpanel (only one choice 7.3, ONE VERSION FOR ALL THE ACCOUNT), the CLI is correct but the changes are not made in their apache conf, it's not my fault and I have no verified it on Joomla or WordPress (yes my client use WordPress too) before having the Joomla alert like I said.

I can't check/change apache conf or restart apache or what you want because it's not a private server.

It's like you specify a new version in environment variable and don't change the old in the apache conf.

It can help someone in OVH with the same problem : Contact OVH to do the changes. After, I really don't care what they are doing it's not my problem, the problem it's that is not working. I don't really think I'm the only one in this case. How many OVH clients ? 
It can happen on another provider, who know them all ?

It can help someone who make a simple PHP update or change the apache conf and forget to restart apache because apache still use the modules specified at start. 

I'm talking to specify the same repository of PHP for CLI and apache conf. No multiple version.

Whith Ionos, you can affect differents versions by site and I have no problem with it. The CLI version is also different because like you say, it's 2 different things.
