### ISSUE TITLE
[3.9] User still listed as logged in after Session Time

### ISSUE THREAD

**Issue by jiweigert** [joomla/joomla-cms#31269]
Trying to make my life easy, I enabled **Shared Sessions: Yes** in Backend with a default **Session Lifetime of 15 Min**utes.

Already seen that there are Sessions listed under Logged-In Users for my Account,
I think that this should not happen with a Session lifetime of 15 Minutes.

### Steps to reproduce the issue
1. Set **Session Lifetime** to default (15 Min) or another small value.
2. Set Shared Session: to **Yes**
3. To be sure, set Session Handler to **PHP** 
![screen shot 2020-10-29 at 14 23 04](https://issues.joomla.org/uploads/1/f7f0f16b8e2621d4bef25b4fc0e8a4a9.png)

4. Save settings and logout
5. Login back into backend and check Frontend that youre logged in there too (by enabling Frontend editing for example).
6. Log out and wait longer to be sure that Session Lifetime expired
7. Login back into backend and recognize that you're still listed under Logged-In Users with  your (expired?) session.
 

### Expected result
No listed Logged-In Users after Session Lifetime is expired in Backend.

### Actual result
Sessions of several days are still listed as logged in under Logged-In Users in Backend
![screen shot 2020-10-29 at 14 21 57](https://issues.joomla.org/uploads/1/ce7b55be4ddb7b83c149e804ade15e1e.png)

### System information (as much as possible)

Setting	Value
 
PHP Built On		Linux www39.your-server.de 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
Database Type		mysql
Database Version	5.7.32-1
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version		7.4.11
Web Server		Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version		Joomla! 3.9.22 Stable [ Amani ] 6-October-2020 15:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent		Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36

### Additional comments
The List of Logged-In Users (Sessions) seems also not be sorted by the Timestamp.

**Comment by jiweigert** [comment]
Backend should be added as well to the Categories, because the Logged-In Users are on default only visible there.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31269">issues.joomla.org/tracker/joomla-cms/31269</a>.</sub>

**Comment by ReLater** [comment]
Isn't that the job of plugin "System - Session Data Purge" where you have settings for session data cleanup?

**Comment by jiweigert** [comment]
I just can say, that the behaviour before I changed to **Share Session** to Yes, was different and I saw only my own session (current), when I was logged in.

When I click on delete icon, no matter how old, I get logged out of the backend and the sessions listed were deleted.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31269">issues.joomla.org/tracker/joomla-cms/31269</a>.</sub>

**Comment by jiweigert** [comment]
My expectation is, a) Session time is responsible for all sessions.

b) when I want to delete an older Session, I do not get logged out of the current one.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31269">issues.joomla.org/tracker/joomla-cms/31269</a>.</sub>

**Comment by jiweigert** [comment]
@ReLater  : 
> Isn't that the job of plugin "System - Session Data Purge" where you have settings for session data cleanup?

That is not a what I wanted and have an issue with it.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31269">issues.joomla.org/tracker/joomla-cms/31269</a>.</sub>

**Comment by ReLater** [comment]
> That is not a what I wanted and have an issue with it.

Yes. I've understood that meanwhile with your later addition "I get logged out of the backend".

**Comment by MacJoom** [comment]
I think this is not a real issue since in the action log only real user actions are logged - expired sessions are not, but i agree that the title "Logged-in users" is not accurate - expired sessions are not taken into consideration - same behaviour in Joomla 4  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31269">issues.joomla.org/tracker/joomla-cms/31269</a>.</sub>

**Comment by alikon** [comment]
i agree let's close this
