### ISSUE TITLE
Minor Layout issue with Forgot Username / Forgot Password screen

### ISSUE THREAD

**Issue by AMurray2016** [joomla/joomla-cms#31263]
### Steps to reproduce the issue
Click the forgot username / forgot password link in Cassieopia (links in the Login module).

### Expected result
Should have some spacing between input field and submit button
![screen shot 2020-10-29 at 01 11 52](https://issues.joomla.org/uploads/1/2411971ad8e2df5e269c31e6dc8993a9.jpg)

### Actual result

No spacing between form elements: see [Example page showing problem](https://j40testsrvr.murraywebs.biz/index.php/component/users/reset?Itemid=101 "Example Page")

![screen shot 2020-10-29 at 01 11 46](https://issues.joomla.org/uploads/1/5a69e6cd13f03e1ed8dc2fc528605039.jpg)

### System information (as much as possible)

Joomla 4 Beta 5 (release 27.10.2020)
PHP 7.4.11

Noticed issue using: 

Edge  86.0.622.51
Google Chrome 81.0.4044.113 
Firefox: 82.0.1 (64-bit)

### Additional comments
Using Firebug (I mean the developer tool in Firefox), found the class name .form-control (I think in template.css).  Suggested fix, add margin-bottom:15px to the input field.

Didn't see any other similar issue on GITHUB.

**Comment by ghost** [comment]
Duplicate report #29138
