### ISSUE TITLE
[4.0] Burger icon broken at least for the mobile view header toggle in Cassiopeia since PR #30707

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#31261]
### Steps to reproduce the issue

Install latest 4.0-dev branch which includes PR #30707 (from tomorrow on you can also use a 4.0 nightly).

In backend, mode the Main Menu module to module position "menu".

Or publish another module in the header area, e.g. Smart Search module on position "search".

In frontend, reduce the windows size until the burger button should be shown.

### Expected result

Burger button.

### Actual result

Button with wrong "bars" icon, which show a bars diagram.

![2020-10-28_01](https://user-images.githubusercontent.com/7413183/97489529-efc22e00-195f-11eb-98f6-469817131649.png)

### System information (as much as possible)

Current 4.0-dev after merge of #30707 (or from tomorrow on also 4.0 nightly build).

### Additional comments

I'm hungry, I want the burger back.

**Comment by richard67** [comment]
Ping @hans2103 or @N6REJ .

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/31265
