### ISSUE TITLE
Error Messages While Unpacking Version 4 Beta 5

### ISSUE THREAD

**Issue by tboome** [joomla/joomla-cms#31278]
I received 3 errors while unpacking the Full_Package.tar file on a Windows 10 Pro install using the AMPPS.  I'm not an expert in if this message is coming generated due to AMPPS or Joomla but thought I would report it.  

### Steps to reproduce the issue
Install AMPPS
Create DB
Download Joomla and copy to Folder on www
Extracted tar file with 7-Zip

### Expected result
No problems flagged

### Actual result
See attachment

### System information (as much as possible)
Windows 10 Pro x64 Build 19041.572
AMPPS 3.9
Apache
PHP-7.3
MySQL![screen shot 2020-10-30 at 21 58 55](https://issues.joomla.org/uploads/1/290013846381bb99379dd61a1e5ddb43.png)
### Additional comments
I was able to install Joomla without any error messages and so far I have not run into any problems.

**Comment by richard67** [comment]
I can reproduce that with any of the tar.gz or tar.bz2 archives. When unpacking the tar file on Windows, I get the same error messages.

When comparing the result of the unpacked tar with the unpacked zip, the 3 files mentioned above have a size greater than zero in the unzip result but have a size of zero in the untar result.

These files seem not to be really necessary, so the installation should be ok, I think.

@wilsonge Can it be that the tar command used in our build script doesn't properly resolve these symbolic links? And why are these 3 files packed into the 4 Beta packages?

**Comment by brianteeman** [comment]
Doesnt look like these should be in the build

**Comment by zero-24** [comment]
> @wilsonge Can it be that the tar command used in our build script doesn't properly resolve these symbolic links? And why are these 3 files packed into the 4 Beta packages?

That tar command in question is: https://github.com/joomla/joomla-cms/blob/staging/build/build.php#L97

But i agree that we should not package stuff that we dont need yarm-lint and var-dump-server seem to me to be dev tools? Not sure about the generate-defuse-key thing. But I would say we dont use it in joomla.

**Comment by brianteeman** [comment]
As we dont package the libraries/vendor/bin folder in releases I think this can be closed

https://github.com/joomla/joomla-cms/blob/a17ef734eb05e7814489916a1c41c1ffc551afd9/build/build.php#L116

**Comment by richard67** [comment]
Correct, we excluded that from the build a while ago. Closing for reasons stated above.
