### ISSUE TITLE
[4.0] Icons for Joomla version, open front and user missing in admin panel Beta6

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#31270]
### Steps to reproduce the issue
Install J4B6 Nightly from 29/10/2020
Log into admin panel

### Expected result
To see icons top right:
![admin-icons-beta5](https://user-images.githubusercontent.com/36987494/97592314-6ad72300-19f8-11eb-87d2-25af206c815a.jpg)

### Actual result
Missing icons
![admin-icons-beta6](https://user-images.githubusercontent.com/36987494/97592343-71659a80-19f8-11eb-92f3-ea08298a679f.jpg)

**Comment by ghost** [comment]
Can´t confirm issue.

**Comment by Scrabble96** [comment]
UPDATE: It seems it was a Firefox for Windows issue as Chrome and Edge ok, but just as I was checking the FF version number, it installed an update and the problem has gone away.

Closing.
