### ISSUE TITLE
[4] Modules. Menu Assigment. Select sub-items selects all.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#31277]
### Steps to reproduce the issue
- I have several site menus. See image (green arrows).

![1](https://user-images.githubusercontent.com/20780646/97751633-e61cff80-1af2-11eb-9bd2-9ba124827ce3.jpg)

---------

- Edit a module > Tabulator "Menu Assignment".
- Set `Module Assignment`: "On the pages selected".
- Click `Assign to Menu Items`: "None", to deselect all items.
- Click button to select/deselect sub-items of a menu and click on "Select" See image (orange arrow).

![2](https://user-images.githubusercontent.com/20780646/97751704-0ea4f980-1af3-11eb-8958-f5969fe610ba.jpg)

### Expected result
- Only sub-items of relevant menu are selected (here "Bibliografie").

### Actual result
- All sub-items of other menus are also selected. See image (red comments).

![3](https://user-images.githubusercontent.com/20780646/97751822-401dc500-1af3-11eb-9527-d85782bd6ada.jpg)

### System information (as much as possible)
- Joomla 4, current nightly, 30 October 2020 02:00:25 UTC.
- XAMPP7.3, Windows 10
- Current Edge chromium, current FF

### Additional comments
- Similiar behavior inside the same menu with select feature used for sublevels. See image (red comment).

![4](https://user-images.githubusercontent.com/20780646/97752274-fc778b00-1af3-11eb-9e55-ca371bc56794.jpg)

**Comment by gostn** [comment]
Issue confirmed.

**Comment by brianteeman** [comment]
Confirmed

**Comment by ghost** [comment]
Also menu item type `Alias` get selected:

> ![image](https://user-images.githubusercontent.com/78906980/116248203-f2190f80-a76b-11eb-9c49-beafff38516f.png)

Deselect works on any menu for all menus.

**Comment by ghost** [comment]
Isn't this a release stopper?

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/33911 should fix it. Please test. Thanks.
