### ISSUE TITLE
[4.0] Composer v1 drone

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31281]
I guess we need a similar update for drone as #31225 

@HLeithner

**Comment by richard67** [comment]
@HLeithner As far as I could see today, this has been fixed meanwhile, and it just needs to update all 4.0 PR's to latest 4.0-dev of the CMS, right? Or am I wrong?

**Comment by zero-24** [comment]
Or trigger the builds again when i understood it correctly given that the change was on the docker image and not in our main branch.

**Comment by richard67** [comment]
So this issue can be closed?

**Comment by HLeithner** [comment]
Yes I fixed it yesterday in the docker images.

**Comment by richard67** [comment]
Thanks!

**Comment by alikon** [comment]
what this mean in regard of the already submitted pr's  ?

**Comment by richard67** [comment]
It just needs to restart drone, no need to update branches, if PRs are not older than a few weeks.

**Comment by alikon** [comment]
look at this one https://ci.joomla.org/joomla/joomla-cms/29862 as an example

**Comment by richard67** [comment]
> look at this one https://ci.joomla.org/joomla/joomla-cms/29862 as an example

In such a case, last drone run so long ago that results have been deleted by the cron job, it needs an update to the branch to trigger drone again. this can be a fake update, e.g. some comment or new line, which later can be rolled back, or it can be an update to the latest changes in base branch in the CMS.
