### ISSUE TITLE
Issue with field attribs in content table.

### ISSUE THREAD

**Issue by sonvnn** [joomla/joomla-cms#31284]
### Steps to reproduce the issue
I am trying to create a gallery with Joomla Content but I got error when I add too much data to attribs field. I check content table and realize that it is varchar(5120) and my jsonencode is too long.

### Expected result
I would like to change attribs to LONGTEXT

**Comment by SharkyKZ** [comment]
Won't fix. See discussion https://github.com/joomla/joomla-cms/pull/25702.
