### ISSUE TITLE
LanguageAdapter still trying to install pdf_fonts - to deprecate 3.9, 3.10, 4.0

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#31286]
### Steps to reproduce the issue
We don't use pdf_fonts in core language since 1.6
Code was not taken off since. 😄 

https://github.com/joomla/joomla-cms/blob/a907b4cf0c4f8135fd7e5404428c9acdd9b7cec8/libraries/src/Installer/Adapter/LanguageAdapter.php#L264-L276

@zero-24

**Comment by zero-24** [comment]
3.9 PR: https://github.com/joomla/joomla-cms/pull/31287 / 4.0 PR: https://github.com/joomla/joomla-cms/pull/31288

thanks  @infograf768
