### ISSUE TITLE
[4.0] Missing JS-protection in .htaccess in case of directly opening a .svg file

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#31298]
### Steps to reproduce the issue

Missing JS-protection in .htaccess [4.0] in case of directly opening a .sgv file.
This script is present in [3.x].

### Expected result

Following script is present in htaccess [4.0].

```
## Disable inline JavaScript when directly opening SVG files or embedding them with the object-tag
<FilesMatch "\.svg$">
  <IfModule mod_headers.c>
    Header always set Content-Security-Policy "script-src 'none'"
  </IfModule>
</FilesMatch>
```

### Actual result

Script is NOT present in htaccess.

### System information (as much as possible)

[4.0]

### Additional comments

This script is present in [3.x]. See #30221.

**Comment by brianteeman** [comment]
Code committed in to j3 will be eventually merged in to j4

**Comment by sandewt** [comment]
> Code committed in to j3 will be eventually merged in to j4

@zero24

**Comment by Quy** [comment]
See https://github.com/joomla/joomla-cms/issues/31291#issuecomment-720136551

**Comment by zero-24** [comment]
Not eventually but definitely this is true for all bugs fixed in the 3.x series. I would propose to have one ticket thats than marked as release block and not have one per bug fixdd in 3.x

**Comment by Quy** [comment]
#31300

**Comment by zero-24** [comment]
Thanks @Quy was about to do that issue my self but just saw youbdid already. :+1:

**Comment by sandewt** [comment]
Thanks all.
