### ISSUE TITLE
Installing language - unable to detect manifest file / Direct downloads - Unhandled PropelException

### ISSUE THREAD

**Issue by pieter-groeneweg** [joomla/joomla-cms#31309]
When installing a language from the administrator environment ie. Dutch, following message appears.

`Error Unable to detect manifest file.`

When trying the direct download on http://joomlacode.org/gf/project/jtranslation3_x/frs/?action=FrsReleaseBrowse&frs_package_id=6406

after some while it shows

```
Unhandled PropelException [wrapped: Could not connect [User Info: host=xxx.xxx.xxx.xxx dbname='xxxxxx' user='xxxxxx' password='*********'] [User Info: Array]]
#0 /opt/gforge.git/lib/core/om/BaseLanguagePeer.php(203): Propel::getConnection('gf5')
#1 /opt/gforge.git/lib/core/om/BaseLanguagePeer.php(183): BaseLanguagePeer::doSelectRS(Object(Criteria), NULL)
#2 /opt/gforge.git/lib/core/om/BaseLanguagePeer.php(165): BaseLanguagePeer::doSelect(Object(Criteria), NULL)
#3 /opt/gforge.git/www/gf.php(113): BaseLanguagePeer::doSelectOne(Object(Criteria))
#4 {main}
```

I replaced the IP and such for xxxx, but they do show.

I am on 3.9.22 
PHP 7.3.24
Apache 2.4.45
MySQL (mariadb) 10.1.47

I am not the only one: https://forum.joomla.org/viewtopic.php?f=711&t=982856

**Comment by Knock-Out** [comment]
I confirm. Italian language.

![Extensions  Install Languages - Joomla + Gantry - Administration](https://user-images.githubusercontent.com/24791536/98141490-f7855380-1ec6-11eb-83c4-6aa451cb55b9.png)

Same thing the direct download.

![Cattura](https://user-images.githubusercontent.com/24791536/98141900-72e70500-1ec7-11eb-80df-1ed96c886115.JPG)

**Comment by alikon** [comment]
should be a temporary problem due to a server down where are stored the languages packages

**Comment by Knock-Out** [comment]
Now, its works!

![Cattura](https://user-images.githubusercontent.com/24791536/98154161-a54b2f00-1ed4-11eb-88ac-8ece280717ac.JPG)

**Comment by Knock-Out** [comment]
Now it works!

![image](https://user-images.githubusercontent.com/24791536/98154196-b85dff00-1ed4-11eb-84da-7174360ccc3b.png)

**Comment by alikon** [comment]
thanks for feedback
