### ISSUE TITLE
[4.0] Installer header - logo and link 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#31304]
### Steps to reproduce the issue
Install Joomla

### Expected result
The header shows a logo left and a white question mark right

### Actual result
![grafik](https://user-images.githubusercontent.com/1035262/97979380-5a93bf00-1dcf-11eb-8f8e-77b5acf641a2.png)

**Comment by brianteeman** [comment]
The problem with the missing logo comes from the change to use flex and the `j-install logo` css class #27684

Sorry but my css is not good enough to work out how to display the image AND keep the text centered

**Comment by N6REJ** [comment]
should be easy enough to fix, I'll give it a look momentarily

**Comment by N6REJ** [comment]
closed as we have a pr https://github.com/joomla/joomla-cms/pull/31310
