### ISSUE TITLE
Error when updating from 3.10 alpha to 4.0 Beta 5

### ISSUE THREAD

**Issue by elpescador-nl** [joomla/joomla-cms#31305]
### Steps to reproduce the issue
I followed the steps to upgrade from 3.9.22 to 4.0 beta 5 using the steps described in this article: https://www.joomla.org/announcements/release-news/5825-joomla-4-0-0-beta5-and-joomla-3-10-alpha3.html

1. Go to the Joomla Update Component Options and switch the Update Channel to “Testing” and the Minimum Stability option to “Alpha”.
2. Update to the latest 3.10 alpha using the Joomla Update Component.
3. Now please switch the Update Channel to “Custom URL” and set the Custom URL to “https://update.joomla.org/core/test/310to4_list.xml”
4. Now you get the update to the latest 4.0 beta release.

### Expected result
I would expect the update to complete without errors.

### Actual result
Update to 3.10 alpha goes all well. Updating from 3.10 alpha to 4.0 beta 5 results in an error while doing the update: _ERROR: Could not open /application/public/media/mod_languages/images/si_lk.gif for writing._
After this error the update stops and the result is a broken installation of Joomla! version somewhere in between 3.10 and 4.0.

<img width="1031" alt="Joomla_Update_-_verbs_cat_-_Administration" src="https://user-images.githubusercontent.com/5052937/98005857-d141b400-1df1-11eb-87d5-b0587e180869.png">

### System information (as much as possible)
- PHP: 7.4.10 (php-fpm)
- DB: 5.5.5-10.4.14-MariaDB-1:10.4.14+maria~focal
- Webserver: nginx 1.19.2

All runs locally in Docker containers on MacOS as host.

**Comment by zero-24** [comment]
Hmm can you confirm the permisson of that file and that your site has still space left? And can you reproduce that issue?

**Comment by elpescador-nl** [comment]
The file _/application/public/media/mod_languages/images/si_lk.gif_ does not exist in my current stable 3.9.22 version, whereas it exists in the upgrade package. Other files like _si.gif_, _es_es.gif_, _es.gif_ in the same folder exist in the installed version as well as the upgrade package.
The folder _/application/public/media_ is writable (like all other folders) and there is still plenty of disk space.

I've "successfully" reproduced this same issue twice.

**Comment by zero-24** [comment]
Hmm that does not look correct will take a look into it myself.

**Comment by SharkyKZ** [comment]
The file is being deleted by update script. Also in the past the file was named `si_LK.gif`. Added to https://github.com/joomla/joomla-cms/pull/30802.

**Comment by zero-24** [comment]
Ah so it it a timing issue for the deltion and than re creation?

**Comment by SharkyKZ** [comment]
No, the correctly cased file is also in the deleted files list. Not sure if removing it from the list is going to solve the issue. On case insensitive filesystem it's still going to be deleted.

**Comment by zero-24** [comment]
That has been fixed here: https://github.com/joomla/joomla-cms/pull/30802 right?

**Comment by SharkyKZ** [comment]
In #30802 these files are removed from delete list and added to case sensitive rename list. I can't say if this fixes the issue mentioned here. I can't reproduce the issue myself, so can't test it.

@elpescador-nl Could you by chance test #30802 to see if it fixes your issue? You'd need to update to the package provided in that PR before upgrading to 3.10.

**Comment by elpescador-nl** [comment]
@SharkyKZ, yes I'd be glad to test #30802 . I can test it from an existing 3.9.22 installation. How can I update with a PR like this one?

**Comment by elpescador-nl** [comment]
As I mentioned in my 3.9.22 the file _/media/mod_languages/images/si_lk.gif_ was missing. I don't know why; it isn't a fresh installation and it might have vanished through incremental updates or maybe it has never been there.
I copied the file from an installation zip _Joomla_3.9.22-Stable-Full_Package.zip_ and now the entire updating process works just fine.

**Comment by zero-24** [comment]
hmm i would say the update should not file when an file that should be deleted is not there.

**Comment by SharkyKZ** [comment]
To test #30802 you'd need to download the package from https://ci.joomla.org/artifacts/joomla/joomla-cms/staging/30802/downloads/37346/ and update using it before updating to 3.10 and then to 4.0.

**Comment by wilsonge** [comment]
PR in https://github.com/joomla/joomla-cms/pull/32006
