### ISSUE TITLE
Move Cassiopeia "Banner" module position outside/below header

### ISSUE THREAD

**Issue by steve-ynt** [joomla/joomla-cms#31317]
## Problem

The "banner" module position in the Cassiopeia template is a child element of the header. This is fine when the template setting for "Sticky Header" is set to No. But checking Sticky Header to Yes, the banner position is stuck along with the header. This makes the banner position only suitable for very short images or content.

Otherwise, the sticky header/banner area consumes a very large percentage of the viewport height, making for a very poor user experience.

## Solution

I think it would be better to have the banner position outside of the header, just before the Top-A position. This would make the sticky header more usable in conjunction with the banner module

**Comment by brianteeman** [comment]
You are quite correct and the good news is that this change has already been made in the dedicated repo for improving the template and will be merged soon.

**Comment by ghost** [comment]
repo: https://github.com/joomla/cassiopeia
