### ISSUE TITLE
[4.0] Smart Search results ignore pagination settings

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#31316]
### Steps to reproduce the issue
Go to the Smart Search menu item > Advanced and disable the pagination.

![finder_menu_item](https://user-images.githubusercontent.com/1838041/98268111-cd01cc00-1f94-11eb-92cd-38bf307d7e2e.png)

### Expected result
Pagination not to be shown at all.

### Actual result
Pagination is there

![finder_results](https://user-images.githubusercontent.com/1838041/98268255-fa4e7a00-1f94-11eb-84ce-7cacc25a290a.png)

### System information (as much as possible)
Joomla 4.0.0-beta6-dev

**Comment by gostn** [comment]
Can´t confirm:

![image](https://user-images.githubusercontent.com/71960554/98328323-c192bd00-1ff5-11eb-9267-a57b17c1f308.png)

### System Information
![image](https://user-images.githubusercontent.com/71960554/98328377-e38c3f80-1ff5-11eb-888d-71a1cfa5684b.png)

**Comment by Hackwar** [comment]
@gostn You don't have enough results to warrant a pagination.

**Comment by gostn** [comment]
@Hackwar you´re right, shame on me.

**Comment by brianteeman** [comment]
See #31390
