### ISSUE TITLE
[4.0] xtd-editor image plugin regression from 3.x [a11y]

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31319]
In Joomla 3 when using the xtd-editor image plugin you are able to enter an alt text description of the image

![image](https://user-images.githubusercontent.com/1296369/98300292-fcbecd00-1fb0-11eb-9b33-b783dd453cbd.png)

In Joomla 4 there is no option for this and the only way you are able to enter an alt text description of the image to toggle the editor into source code view and manually enter it. Not very user friendly :(

![image](https://user-images.githubusercontent.com/1296369/98300574-5e7f3700-1fb1-11eb-89fc-662e2504b137.gif)

For me this is a serious regression and is a release blocker

as requested cc @carcam

**Comment by micker** [comment]
Maybe need a second step (modal) for alt  and description ?

**Comment by infograf768** [comment]
This is a major flaw. Setting as release Blocker. Not only for the a11y aspect but also for float and caption.

**Comment by carcam** [comment]
Thanks @brianteeman for reporting this!! Added to our list of items to check before J4.

Also thanks @infograf768 infeed this is an RC!!

**Comment by dgrammatiko** [comment]
Please test #31425
