### ISSUE TITLE
[RFC][4.0] Set context limitation to Finder's search

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#31313]
### Problem identified
The finder's search is very generic. It returns items of any type in it's results (e.g. categories, articles, contacts, etc.).
Although this is versatile, it has many limitations.

#### Functional
For example what if we have a blog section with content articles and an e-shop section (utilizing an e-commerce component). We will possibly need a distinct search, in each of our site's sections, which return different type of items (blog categories or articles in the 1st case and product categories or products in the 2nd case).

#### Presentation
Another limitation applies to the presentation of the results. Would be probably better if we can present the products, in their own layout, which also displays an image and a price and the blog articles their own way.

### Proposed solution

A context/type parameter in the finder's menu item, based on which the suggestions and the results will be returned.

A layout setting in the finder's menu item where we can set our layout. This together with the selected ItemId in the search module, can let us display results in specific layouts per type after a search.

**Comment by brianteeman** [comment]
>  It returns items of any type in it's results 

That's the whole point of the Filters option in finder

**Comment by sakiss** [comment]
> That's the whole point of the Filters option in finder

But the filters need to be applied after the results are fetched. 
Why should the user gets irrelevant results to what he/she is looking for, in the 1st place?

Though your point gives me an idea for the technical solution. 
We may can set predefined/default values to the filters, based on the results menu item.

**Comment by brianteeman** [comment]
> But the filters need to be applied after the results are fetched.

NO - in the component you can create any type of filter
In the menu item you can set the menu item to use whatever filter you want

Its all there you just have to use it ;)

**Comment by sakiss** [comment]
Thanks for the reply.

> NO - in the component you can create any type of filter
> In the menu item you can set the menu item to use whatever filter you want
> 
> Its all there you just have to use it ;)

That means that i can set the search to return for example only articles or only tags (without applying any filter afterwards) ?

**Comment by brianteeman** [comment]
yes, quicker to try yourself than waiting for a reply

**Comment by sakiss** [comment]
I ask because i cannot find such a feature. 
Either i am missing something or does not work as described previously. 
I suppose that you are referring to the setting "Search Filters" in the menu item.

![finder_filter](https://user-images.githubusercontent.com/1838041/98359695-4a7b1a00-2031-11eb-9d12-1fc8b14d03c4.png)

![search_filter](https://user-images.githubusercontent.com/1838041/98359780-68e11580-2031-11eb-9d7e-470279a30fb7.png)

![search_results](https://user-images.githubusercontent.com/1838041/98359882-8ada9800-2031-11eb-9a97-2316b48b528c.png)

**Comment by brianteeman** [comment]
Working for me with the following settings

![image](https://user-images.githubusercontent.com/1296369/98959258-04bfc500-24fb-11eb-9676-23f69277f3e4.png)

![image](https://user-images.githubusercontent.com/1296369/98959275-0a1d0f80-24fb-11eb-9a8f-75575f209d8d.png)

![image](https://user-images.githubusercontent.com/1296369/98959292-0db09680-24fb-11eb-8d9f-e72bd3410c6a.png)

**Comment by Hackwar** [comment]
Tested as well and works as expected.
