### ISSUE TITLE
[4.0] jQuery Chosen Plugin text vars not mulitlingual

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#31314]
### Steps to reproduce the issue

media\vendor\chosen\js\chosen.jquery.js

```
    AbstractChosen.default_multiple_text = "Select Some Options";

    AbstractChosen.default_single_text = "Select an Option";

    AbstractChosen.default_no_result_text = "No results match";
```

The text strings are hard coded to the chosen.jquery.js and not translateable.

Affects chosen select, multiple fields

###
Would suggest to implement Joomla.Text._('

### System information (as much as possible)
 Joomla! 4.0.0-beta5 Beta

**Comment by Fedik** [comment]
the fix even more easy, do not use chosen :wink:

**Comment by bembelimen** [comment]
1. Chosen is an external library => we don't change here anything
2. That are the default values => you can overwrite them easily by your script giving the correct values

Otherwise:

> 
> the fix even more easy, do not use chosen 😉

**Comment by brianteeman** [comment]
A more constructive comment would be
For Joomla 4 it is recommended that you use choices.js instead
You can see how this is implemented in the select module position

**Comment by HRIT-Florian** [comment]
Many thanks for the feedback
