### ISSUE TITLE
[4.0] Category workflow

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31324]
### Steps to reproduce the issue
Check that workflow is **not** enabled for articles
![image](https://user-images.githubusercontent.com/1296369/98362277-dcc8f100-2024-11eb-8b0f-050b81d7c110.png)

Create a new category

### Expected result
No mention of workflows

### Actual result
![image](https://user-images.githubusercontent.com/1296369/98362408-139f0700-2025-11eb-9bd1-51937f72bf5f.png)

**Comment by chmst** [comment]
Closing this as there is a PR, please test  #31374

**Comment by chmst** [comment]
Pleease test  #31374
