### ISSUE TITLE
[J4] incorrect worflow for media manager to insert file

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#31320]
On j4 beta in article edition
its realy strange we didn't a button to add file .. only image
but if we use image we can upolad pdf or image or any media field ...
very confusing for end user
![image](https://user-images.githubusercontent.com/2539440/98301090-8b841780-1fba-11eb-88df-7e6022f41a74.png)
i think we can have 2 solutions
=> rename button to add image => add media, and change title of popup and allow to load file link
=> adding a new link in dropdown
![image](https://user-images.githubusercontent.com/2539440/98301402-fa617080-1fba-11eb-87d5-9671293d3fb5.png)

other return, its realy strange to have cms content to load file or image ... not user friendly

**Comment by Quy** [comment]
Duplicate #30881

**Comment by micker** [comment]
not duplicate ...
for now we can't upload a pdf an do link on text with new media manager simply !
no understandable button to allow this and function doesn't works, its not a lazy problem

**Comment by Quy** [comment]
See https://github.com/joomla/joomla-cms/issues/30881#issuecomment-703099110

**Comment by micker** [comment]
yes but no a good idea to use a link to image in dropdown if  we can use it it for pdf for example ... not sure it good to mixe issue ... but your are the boss ..
@dgrammatiko duplicate ?

**Comment by dgrammatiko** [comment]
@micker there are many bugs with the current selection process in the media manager as revealed also in https://github.com/joomla/joomla-cms/pull/30784 but before any patch will be done that PR needs to be merged. So please go and test...

**Comment by micker** [comment]
Ok i will try asap

**Comment by micker** [comment]
@wilsonge @dgrammatiko the problem already exist in last beta impossible to add a file without many manipulation

**Comment by micker** [comment]
No news about this ? We cant propose a good CMS without adding file in content :smile:

**Comment by ghost** [comment]
> No news about this ? We cant propose a good CMS without adding file in content 😄

@micker I'm not sure if you see https://github.com/joomla/joomla-cms/issues/30881#issuecomment-703099110 as @Quy  suggested where @dgrammatiko wrote: "I'm planing to expand the media field for any supported type"

**Comment by micker** [comment]
RC is comming and no news about this ... no plan ?

**Comment by Quy** [comment]
Please test PR #34634
