### ISSUE TITLE
Menu search: Helptext missing on hover the search filter

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#31335]
### Steps to reproduce the issue
1. Login to joomla admin panel
2. Click on menu
3. Go to all menu
4. Hover on the search icon

### Expected result
Just like other menu search help text eg , user, banner, articles - All menu search bar should have help text

### Actual result
Help text is missing

### Additional comments
In banner list - we have help text on search 
In article list - we have help text on search
In User list - we have help text on search

**Comment by uthorat** [comment]
Please find the attachement for above isue![screen shot 2020-11-07 at 09 19 30](https://issues.joomla.org/uploads/1/e89199783dfb19e096a2b9ec9631c5aa.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31335">issues.joomla.org/tracker/joomla-cms/31335</a>.</sub>

**Comment by brianteeman** [comment]
Please test #31336

**Comment by adj9** [comment]
I don't understand what you expect as an expected result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31335">issues.joomla.org/tracker/joomla-cms/31335</a>.</sub>
