### ISSUE TITLE
[4.0] Joomla Registration Form UI Issue.

### ISSUE THREAD

**Issue by shinderohanoffical** [joomla/joomla-cms#31337]
![screen shot 2020-11-07 at 09 34 50](https://issues.joomla.org/uploads/1/2a4ba0b9bc86dae4d53efc090dce9b83.png)### Steps to reproduce the issue
1: Create Joomla user registration form menu.
2: Go to site click on 'Registration' menu.
3: Below password field you will see the Grey extra line(Please find attached screenshot)

**Comment by adj9** [comment]
It's not a frontend problem. The line when compiling the password defines its difficulty ...

Please close the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31337">issues.joomla.org/tracker/joomla-cms/31337</a>.</sub>
