### ISSUE TITLE
For color field in custom fields color picket is not rendered on the form

### ISSUE THREAD

**Issue by ankush-maherwal** [joomla/joomla-cms#31339]
### Steps to reproduce the issue
1) Create a custom field of type "color" in com_content
2) Try to create an article and check the fields tab for the custom field of type "color"

### Expected result
The custom color field should show a color picker

### Actual result
The custom color field shows a text input

### System information (as much as possible)
Operating System: Ubuntu 20.04
Browser: Chrome

![Articles - joomla4beta5 - Administration](https://user-images.githubusercontent.com/19546819/98437911-3eb05600-210c-11eb-853c-c7a03a84333b.gif)

**Comment by manojLondhe** [comment]
Do add [4.0] in title for J4 issues @ankush-maherwal

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/31356.
