### ISSUE TITLE
[4.0] Extra fields are not getting displayed on user registration form frontend

### ISSUE THREAD

**Issue by snehal0904** [joomla/joomla-cms#31334]
### Steps to reproduce the issue
- Enable user registration from user config
- Create a registration form menu
- create a custom/extra field from users. For example - Company Name
- Go to frontend, Registration form

### Expected result
An extra field should display on the registration form

### Actual result
An extra field is not getting displayed on the registration form

### Additional comments
- It was working in Joomla 3.9.x

**Comment by brianteeman** [comment]
What are the permissions for the field?
![image](https://user-images.githubusercontent.com/1296369/98437652-d3e72680-20db-11eb-8ba6-819019c974dc.png)

And what is the setting for rendering
![image](https://user-images.githubusercontent.com/1296369/98437664-f9743000-20db-11eb-85eb-0fd3eed2b7d5.png)

**Comment by manojLondhe** [comment]
Custom fields not showing up at front-end even after All permissions are set as "Allowed".
Fields appear in admin edit user form though.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31334">issues.joomla.org/tracker/joomla-cms/31334</a>.</sub>

**Comment by brianteeman** [comment]
Either we are all missing something or you have discovered a release blocker

@infograf768 @richard67 could you take a look please

**Comment by richard67** [comment]
I'm not really deep into permissions stuff .. but maybe @SharkyKZ could have a look on it?

**Comment by SharkyKZ** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/31366.
