### ISSUE TITLE
[4.0] Default value of subform field is not applied

### ISSUE THREAD

**Issue by pjdevries** [joomla/joomla-cms#31331]
### Steps to reproduce the issue

- Add a `subform` field to an arbitrary form or use an existing `subform` field.
- Add a `default` value to the field definition.
- Remove any field value(s).
- Refresh the form.

### Expected result

Default value(s) showing up in the form.

### Actual result

No default value(s) showing up in the form.

### System information (as much as possible)

Joomla! 4.0 beta 5

### Additional comments

The default value is not applied.

**Comment by Quy** [comment]
PR #31332
