### ISSUE TITLE
[4.0] User action log - When user clicks on media file redirect to error page "0 Invalid controller class: file "

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#31338]
### Steps to reproduce the issue
1. Login to joomla admin panel
2. Go to media 
3. Upload some images
4. Go to user action log
5. Observe the log and open the log which related to media

### Expected result
User should be able to open the images 

### Actual result
Error get displayed "0 Invalid controller class: file " 

![screen shot 2020-11-07 at 09 33 17](https://issues.joomla.org/uploads/1/87ac3510b2d9c629c17c3c9fbd1d9ec8.png)

**Comment by infograf768** [comment]
Confirmed

<img width="682" alt="Screen Shot 2020-11-07 at 10 40 00" src="https://user-images.githubusercontent.com/869724/98437917-950a9e00-20e6-11eb-9b30-405a006586dc.png">

Link here is of type
`http://localhost:8888/newfolder/joomla40/administrator/index.php?option=com_media&task=file.edit&id=0`

**Comment by adj9** [comment]
Click on the image name to display the error<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31338">issues.joomla.org/tracker/joomla-cms/31338</a>.</sub>

**Comment by Quy** [comment]
Duplicate #30951
