### ISSUE TITLE
[4.0] Media - For blank folder,provide the text message "No media files added" 

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#31340]
### Steps to reproduce the issue
1. Login to admin panel
2. Go to media
3. Create new folder or open the folder which dont have media files
4. Observe 

### Expected result
Instead of white screen, provide the text message or any help text 

### Actual result
Only white screen displays and checkbox is selected

![screen shot 2020-11-07 at 09 44 43](https://issues.joomla.org/uploads/1/2bffb56138cc1eb19afc2f0d72af447a.png)

**Comment by uthorat** [comment]
One more issue tagging here only, if user searches the string and result found, Message is missing
![screen shot 2020-11-07 at 10 26 32](https://issues.joomla.org/uploads/1/031123f4e9315bc990223cbb78dba63f.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31340">issues.joomla.org/tracker/joomla-cms/31340</a>.</sub>

**Comment by meinhoonharsh** [comment]
I want to work on this Isssue

**Comment by meinhoonharsh** [comment]
I want to work on this Issue

**Comment by ghost** [comment]
@meinhoonharsh you can work on an issue as there is nobody who can allow or disallow.

**Comment by ghost** [comment]
@meinhoonharsh 
> I want to work on this Issue

please read https://github.com/joomla/joomla-cms/issues/31540#issuecomment-811070565

**Comment by rajputanuj31** [comment]
I tried to do the following changes in  joomla-cms\media\com_media\js\media-manager.js  inside **script$p** function
```
      var temp = document.getElementsByClassName("media-browser-grid");
      var msg="No Media Files";
      if (this.$store.getters.getSelectedDirectoryContents.length === 0) {
        if(temp[0].innerText.length===0){
          const hed=document.createElement("h3");
          hed.innerHTML=msg;
          temp[0].appendChild(hed);
        }
          this.$refs.mediaToolbarSelectAll.checked = false;
      }
      else {
        if(document.getElementsByTagName("h3")[0].innerText===msg){
          document.getElementsByTagName("h3")[0].remove();
        }
      }
```
But I could not find the media folder in the original repository. How can I tackle this issue.

**Comment by rajputanuj31** [comment]
I have made changes in joomla-cms\media\com_media\js\media-manager.js in **script$p**
```
      var temp = document.getElementsByClassName("media-browser-grid");
      var msg="No Media Files";
      if (this.$store.getters.getSelectedDirectoryContents.length === 0) {
        if(temp[0].innerText.length===0){
          const hed=document.createElement("h3");
          hed.innerHTML=msg;
          temp[0].appendChild(hed);
        }
          this.$refs.mediaToolbarSelectAll.checked = false;
      }
      else {
        if(document.getElementsByTagName("h3")[0].innerText===msg){
          document.getElementsByTagName("h3")[0].remove();
        }
      }
```
But I could not find media folder in original repository. How can I tackle this issue.

**Comment by R4d104ct1v1ty** [comment]
is this issue still open?

**Comment by aayuushh365** [comment]
Hey there @brianteeman , I have been going through this issues and I think  I can solve the issue as per mentioned condition. Could you please assign this to me ?🚀🚀

Or should I create an MR for this directly ?😀🚀🚀

**Comment by carlitorweb** [comment]
@aayuushh365 just create the PR, and mention in the PR template is a fix for this issue. You will see there the section when you create the PR

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39518 . Thanks in advance.
