### ISSUE TITLE
[4.0] [Media] Unable to sort the media files from the media list

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#31347]
### Steps to reproduce the issue
1. login to admin panel
2. Go to media
3 Observe the list of media files
4. Try to sort them

### Expected result
User should be able to sort the result by name, date

### Actual result
There is no option of sorting the list

### Additional comments
Just like other component user should be able to sort the media list by name, date![screen shot 2020-11-07 at 10 50 04](https://issues.joomla.org/uploads/1/a816e2a37429feb1c47eccc1c4873734.png)

**Comment by brianteeman** [comment]
Do we have a label "re-evaluate for 4.1" ?

**Comment by HLeithner** [comment]
We have many labels but no 4.1 re-evaluate... added the new Feature label and ping @bembelimen

**Comment by dgrammatiko** [comment]
@Quy can we close this one with https://github.com/joomla/joomla-cms/pull/39732
