### ISSUE TITLE
[4.0] Media folder: No limitation for addition of folder in media due to that UI get broken

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#31342]
### Steps to reproduce the issue
1. Login to admin panel
2. Go to media
3. Create a new folder 
4. Keep adding a subfolder
5. Observe the UI

### Expected result
User should have some limitation for the addition of folder OR UI should not get broken if the user keeps add folder

### System information (as much as possible)
No limitation for adding folder
Due to no limiation UI got broken![screen shot 2020-11-07 at 10 02 30](https://issues.joomla.org/uploads/1/40b7920e024c59cddb6db6778435da52.png)

**Comment by brianteeman** [comment]
same as #30959
