### ISSUE TITLE
[4.0] [Backend]  In Banners: Clients details page Contact column is  displaying blank value

### ISSUE THREAD

**Issue by MeghaBiranje** [joomla/joomla-cms#31345]
### Steps to reproduce the issue
1. log in to the backend 
2. Goto Components-> Banners -> Clients
3. Click the New button and fill the form
4. While filling the form add tabs/spaces in "Contact Name" which is the required field.
5. Click on Save and close button 
6. You can see the contact column for our added client is blank.

![screen shot 2020-11-07 at 10 25 37](https://issues.joomla.org/uploads/1/b9460e0325e2885c70055b846fb6b6ae.png)

**Comment by brianteeman** [comment]
The name field should be validated on save 

```
		if (trim($this->name) === '')
		{
			$this->setError(Text::_('JLIB_CMS_WARNING_PROVIDE_VALID_NAME'));

			return false;
		}
```

**Comment by brianteeman** [comment]
please test #31411
