### ISSUE TITLE
[4.0][Media] Media search is inconsistent as compared to other search present in joomla

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#31346]
### Steps to reproduce the issue
1. login to admin panel
2. Go to media
3. Observe the search

### Expected result
Search filter should be same all over the places

### Actual result
Search filter is different in media component

### Additional comments
1. Remove the 3 dots present
2. Add the clear option
3. Add help text

![screen shot 2020-11-09 at 10 33 46](https://issues.joomla.org/uploads/1/466e569be001939f8ba70fc7f071ab9d.png)

**Comment by dgrammatiko** [comment]
This should be closed as #31451 was merged

**Comment by richard67** [comment]
Closing as stated above
