### ISSUE TITLE
[4.0] [Media] Cancel button color is inconsistent when user try to rename the folder

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#31344]
### Steps to reproduce the issue
1. login to admin panel
2. Go to media
3. Create a new folder or edit the already created folder
4. Rename the folder
5. Observe the cancel button color

### Expected result
Cancel button color should be red

### Actual result
Cancel button color is black

![screen shot 2020-11-07 at 10 13 35](https://issues.joomla.org/uploads/1/1ea842218b0a424788153b5615a5ee2c.png)

**Comment by infograf768** [comment]
@uthorat 
Please add [4.0] to title of issue when it concerns 4.0.

**Comment by brianteeman** [comment]
Where is it inconsistent? As far as I can see it is always black

**Comment by uthorat** [comment]
Why it should black? Cancel should be in red color. Adding a screenshot for your reference.

@brianteeman - The media manager section only has this black color on the cancel button.This needs to be chanage. Cancel / delete button should be in red color. 
![screen shot 2020-11-09 at 04 34 06](https://issues.joomla.org/uploads/1/dbc365affc3e0d4e0d4646f88eec6f72.png)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31344">issues.joomla.org/tracker/joomla-cms/31344</a>.</sub>

**Comment by brianteeman** [comment]
Look at all the modal buttons

**Comment by N6REJ** [comment]
@brianteeman he means consistent with UI overall theme.  Personally I agree with him.
Without hover its just plain white.
![image](https://user-images.githubusercontent.com/1850089/100730398-9ea6bf00-338f-11eb-894a-4cbde4ddb672.png)

**Comment by meinhoonharsh** [comment]
I want to work on this Issue. But after all these conversation happened previously, I am bit confused that changes will be considered or not

**Comment by dgrammatiko** [comment]
This should be closed as it's fixed in 5.1
<img width="368" alt="Screenshot 2024-07-22 at 10 02 32 PM" src="https://github.com/user-attachments/assets/f6f4931a-8bf3-4667-ae4b-c2a36cb3913e">

**Comment by Hackwar** [comment]
@dgrammatiko says it is fixed. I'm trusting @dgrammatiko on this... If it is still an issue, please open a new ticket ... and blame it on @dgrammatiko 😜
