### ISSUE TITLE
[4.0]Admin view -Article Filter-Tag Filter - Unable to view pre-defined tag or assigned tags to articles as Jooma 3x 

### ISSUE THREAD

**Issue by jaisheela** [joomla/joomla-cms#31348]
### Steps to reproduce the issue
Go to Admin view
Move to Content Menu
Go to Articles
Check Article filters
Tag filter shows no tags (No results match) 

### Expected result

It should show the tags created for filtering the article as in it should have predefined tags

### Actual result
 
I have created  8 tag but it says "no results match" 

### System information (as much as possible)

Joomla 4
![notag](https://user-images.githubusercontent.com/16459454/98439217-5e4c7c00-2116-11eb-8dab-71ac51d5b878.png)
![tag](https://user-images.githubusercontent.com/16459454/98439230-7d4b0e00-2116-11eb-8989-3277f5a2ceac.png)
 
MySQL 5.7.32-0ubuntu0.18.04.1

PHP Version | 7.3.12-1+ubuntu18.04.1+deb.sury.org+1

**Comment by jaisheela** [comment]
![Uploading joom3x.png…]()

**Comment by jaisheela** [comment]
![Uploading joom3x.png…]()

**Comment by infograf768** [comment]
Confirmed.
In J3 we have

<img width="418" alt="Screen Shot 2020-11-07 at 18 29 27" src="https://user-images.githubusercontent.com/869724/98447694-3ca7c080-2127-11eb-8d32-1741983a977f.png">

@wilsonge

**Comment by infograf768** [comment]
Setting as release blocker

**Comment by ghost** [comment]
Are the tags shown if you enter 3 letters
 https://github.com/joomla/joomla-cms/issues/30385#issuecomment-674540757 ?

**Comment by infograf768** [comment]
yes, only the tags which fit, very different from J3

**Comment by SharkyKZ** [comment]
Expected behavior as already explained in https://github.com/joomla/joomla-cms/issues/30385 and in many other issues.

**Comment by richard67** [comment]
Expected behaviour regarding how these "fancy selects" work, i.e. it is not a bug what has been observed here.

But that doesn't mean there is no issue. You have to look up the names of tags somewhere else to know which 3 characters could be suitable. Or can you type ANY 3 characters, matching or not, to see the available tags? I think no. It's a functional downgrade compare to "normal "multiselects, and it's bad UX, too.

**Comment by regularlabs** [comment]
This is SOOO user-unfriendly!

Apart from it being ridiculous to have to search for tags to show them (which is not implied anywhere), there are bugs to this approach.
Tags with 1 or 2 letters: can't look them up.
In the tag assignment field (article edit): type 2 letters and save will use the existing tag if it already exists. But no feedback anywhere if it does or not.
There in NO way to assign a 1-letter tag to an article. But it is possible to create 1 letter tags in the Tag manager.

**Comment by brianteeman** [comment]
No matter if as a developer you expect it or not - this is not correct.

**Comment by richard67** [comment]
Well, the "no results match" is definitely wrong.

**Comment by regularlabs** [comment]
"Dear mister Web Dev, for our Citroën car parts site we try to create tags, like C1 and C3 and DS 7. After losing a day thinking it was our fault we finally found a way to select the "DS 7" tag by writing it in full in the tag select field. But the C1 and C3 tags never appear".

"Oh, you can create them. You just can't search or select them. That is how it is meant to be. Tags need at least 3 characters."

"I thought you said Joomla is a mature web platform."

"Well, I recommend we build your site on Joomla 3, as it was no issue there."

"What about you just go away and we let someone else build it on Wordpress!"

**Comment by regularlabs** [comment]
(Ok, I'll crawl back into my own coding space and shut up 😁 )

**Comment by richard67** [comment]
They have to rename their cars to something longer ;-)

**Comment by SharkyKZ** [comment]
> 
> 
> This is SOOO user-unfriendly!
> 
> Apart from it being ridiculous to have to search for tags to show them (which is not implied anywhere), there are bugs to this approach.
> Tags with 1 or 2 letters: can't look them up.
> In the tag assignment field (article edit): type 2 letters and save will use the existing tag if it already exists. But no feedback anywhere if it does or not.
> There in NO way to assign a 1-letter tag to an article. But it is possible to create 1 letter tags in the Tag manager.

You can change this with `Minimum Search Length` option in Tags component configuration.

**Comment by infograf768** [comment]
I still consider this as a release blocker.
Do we really need this `fancy selects` for tags?

**Comment by infograf768** [comment]
In fact, there is a solution: Instead of chosing `AJAX`, one can choose `Nested` in Tags configuration...

<img width="713" alt="Screen Shot 2020-11-12 at 10 23 52" src="https://user-images.githubusercontent.com/869724/98921106-32901400-24d1-11eb-982a-c25aaa4af3c8.png">

Maybe `Nested` should be default.

**Comment by brianteeman** [comment]
This _problem_ applies everywhere that this select script is used. not just for tags

**Comment by infograf768** [comment]
Everywhere?
What about Category field?

<img width="951" alt="Screen Shot 2020-11-12 at 17 54 46" src="https://user-images.githubusercontent.com/869724/98970412-355e2980-2510-11eb-9c61-7af83a8f7699.png">

Or Select Author filter?

**Comment by HLeithner** [comment]
Created a solution that hopefully fits all needs at #31481 

Closing this.
