### ISSUE TITLE
[4.0] [Backend] Right hand side bar is not align during edit of menu items

### ISSUE THREAD

**Issue by MeghaBiranje** [joomla/joomla-cms#31341]
### Steps to reproduce the issue
1. Login to Joomla admin panel
2. Go to modules in that go to Login Form module
3. Now in Login Redirection Page option select menu.
4. After that click on edit and see the right sidebar is not align properly.

![screen shot 2020-11-07 at 09 47 01](https://issues.joomla.org/uploads/1/1008e331725205217b6fef806ed62db5.png)

**Comment by ghost** [comment]
6th duplicate report #27907

**Comment by infograf768** [comment]
Closing as duplicate.
