### ISSUE TITLE
[4.0]Accessibility Options Admin view- Use of big cursor does not impact on Help menu link

### ISSUE THREAD

**Issue by jaisheela** [joomla/joomla-cms#31343]
### Steps to reproduce the issue
1) Go to admin panel
2) Enable plugin System - Additional Accessibility Features
3) Click on Accessibility Options enable in left hand side
4) Choose the option big cursor
5) hover Cursor to Help menu

### Expected result

The cursor should be big.

### Actual result

Cursor gets small after hovering to the Help menu

### System information (as much as possible)

MySQL 5.7.32-0ubuntu0.18.04.1

PHP Version | 7.3.12-1+ubuntu18.04.1+deb.sury.org+1

**Comment by adj9** [comment]
I'm on the latest Nightly Builds and I can't find this option in the accessibility menu.

The big cursor can be used with the Additional Accessibility Features plugin.

How did you find the option? Are you referring to Joomla 4?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31343">issues.joomla.org/tracker/joomla-cms/31343</a>.</sub>

**Comment by jaisheela** [comment]
Yes I am on Joomla 4

**Comment by jaisheela** [comment]
![screenshot-ttpllt-php73 local-2020 11 07-16_11_01](https://user-images.githubusercontent.com/16459454/98438937-e0877100-2113-11eb-9763-0398bbdab29f.png)

**Comment by brianteeman** [comment]
Unable to replicate

![image](https://user-images.githubusercontent.com/1296369/98957697-61ba7b80-24f9-11eb-8d9d-1d97bc71151b.png)

![image](https://user-images.githubusercontent.com/1296369/98957700-62eba880-24f9-11eb-8df4-da3b3ad5d3e0.png)

**Comment by Quy** [comment]
Closing as not reproducible.
