### ISSUE TITLE
[4.0] Joomla logo is not visible - while login as a admin user having "Administrator" group assigned.

### ISSUE THREAD

**Issue by Kaustubharas** [joomla/joomla-cms#31350]
### Steps to reproduce the issue
1. Login as admin user having "Super User" group and create a user say "admin" and assign "Administrator" group to this user.
2. Now, login with the new user created with group "Administrator" and observe.

Observation - 

1. Logged in user with group Super User -  Joomla Logo is visible
![screen shot 2020-11-07 at 11 09 21](https://issues.joomla.org/uploads/1/00b43b6b9a85ac8345382c4c617eb35e.png)

2. Logged as user with group Administrator - Joomla Logo is not visible 
![screen shot 2020-11-07 at 11 11 08](https://issues.joomla.org/uploads/1/77a49af3a22c242fd577dde4c8e171e0.png)

### Expected result

For any user logged to admin side, logo should be visible.

### Actual result

For users having "Administrator" group assigned, Logo is not visible.

**Comment by infograf768** [comment]
I do not confirm this.
<img width="1183" alt="Screen Shot 2020-11-07 at 12 14 54" src="https://user-images.githubusercontent.com/869724/98439552-e456cb80-20f2-11eb-8b08-4d29468bffc5.png">

**Comment by Kaustubharas** [comment]
@infograf768 - I see your build as 4.0.0.beta6. I have tested and reported this on 4.0.0-beta5 which is the latest available build on Github. https://github.com/joomla/joomla-cms/releases<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31350">issues.joomla.org/tracker/joomla-cms/31350</a>.</sub>

**Comment by Kaustubharas** [comment]
I confirm it's working on 4.0.0.beta6.
