### ISSUE TITLE
[Backend]  In Banners: Clients details page Client Name is blank so we can't edit

### ISSUE THREAD

**Issue by MeghaBiranje** [joomla/joomla-cms#31355]
### Steps to reproduce the issue
1. log in to the backend
2. Goto Components-> Banners -> Clients
3. Click the New button and fill the form
4. While filling the form add tabs/spaces in "Name" which is the required field.
5. Click on Save and close button
6. You can see the client column for our added client is blank so we can't edit it.

![screen shot 2020-11-07 at 13 35 28](https://issues.joomla.org/uploads/1/e86583e208a740b13f8313f40a9e5d52.png)

**Comment by adj9** [comment]
Confirmed :) 
The field is obliged. Requires a control for the space: ' '.

For the new article there is a check
![Schermata 2020-11-07 alle 15 22 43](https://user-images.githubusercontent.com/5918444/98443710-5dfbb300-210d-11eb-8de5-5cfeed9d1521.png)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31355">issues.joomla.org/tracker/joomla-cms/31355</a>.</sub>

**Comment by richard67** [comment]
@MeghaBiranje Is this fixed by your PR #31354 ? Or is that something else?

**Comment by MeghaBiranje** [comment]
I am sending this fix in another PR.

**Comment by MeghaBiranje** [comment]
I am sending this fix in the same PR.

**Comment by brianteeman** [comment]
Please test #31411
