### ISSUE TITLE
[4.0][administrator/site module]-While adding modules if there is no search result found , message is missing for the same

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#31351]
### Steps to reproduce the issue
1. Login to admin panel
2. Go to Site/administrator modules
3. Click on New module
4. Search the module name which is not present
5. Observe the result screen

### Expected result
User should get the message that "No result found match to query"

### Actual result
Blank screen displays

### Additional comments
for consistency, we can use the message which is present in other search section ie  " No Matching Results![screen shot 2020-11-07 at 11 52 28](https://issues.joomla.org/uploads/1/bf797abd19c75ffb6cb61f19370de09e.png)"

**Comment by rajatRS** [comment]
Hey @uthorat I got what you are mentioning here and may I proceed to change this message :)

**Comment by bembelimen** [comment]
@rajatRS any progress so far? If you want, feel free to add it.

**Comment by himanshu007-creator** [comment]
> ### Steps to reproduce the issue
> 1. Login to admin panel
> 2. Go to Site/administrator modules
> 3. Click on New module
> 4. Search the module name which is not present
> 5. Observe the result screen
> 
> ### Expected result
> User should get the message that "No result found match to query"
> 
> ### Actual result
> Blank screen displays
> 
> ### Additional comments
> for consistency, we can use the message which is present in other search section ie " No Matching Results![screen shot 2020-11-07 at 11 52 28](https://camo.githubusercontent.com/7b7b7e13033d5f8710c0e5b28416c42f20cd0e90b507350790db8d66ccffee85/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f62663739376162643139633735666662366362363166313933373064653039652e706e67)"

Hi  @uthorat , I tried to replicate the same by following the instructions. <strong>IT WORKS FINE WITHOUT DISPLAYIMG ANY BLANK SCREEN</strong>

![2021-02-21 (3)](https://user-images.githubusercontent.com/65963997/108621947-da679700-745b-11eb-86c0-6b5a156926ba.png)

**Comment by brianteeman** [comment]
You missed step 3

**Comment by himanshu007-creator** [comment]
> You missed step 3

yes, now i got it. I would like to work on  it, can you help me locate the file that needs to be modified?

**Comment by brianteeman** [comment]
If I could help you I would have fixed it ;)

**Comment by joomdonation** [comment]
@himanshu007-creator  I think you would have to work on two files:
- administrator/components/com_modules/tmpl/select/default.php : To add the text which will be displayed when no module found
- And media/com_modules/js/admin-module-search.js , display the text above when no module found and hide it if there are modules returned.

**Comment by himanshu007-creator** [comment]
![2021-02-24](https://user-images.githubusercontent.com/65963997/109021466-eb750a00-76e0-11eb-86e3-38a1d0d3a172.png)

@joomdonation  Sir , i was able to add the text which will be displayed when no module is found.
But i am unable to fix the javascript part. 
My approach:-
- Create an error message and make it hidden
- use javascript to test the condition , module found or not
-  toggle the visibility of this error message depending on it

**Comment by richard67** [comment]
Closing as having a pull request. It has already 2 good tests and so it RTC (ready to commit). See #32657 .
