### ISSUE TITLE
[4.0] Admin View >> Contents >> Fields >> Displaying duplicate category options in detail page 

### ISSUE THREAD

**Issue by priyankaSahutekdi** [joomla/joomla-cms#31352]
### Steps to reproduce the issue
Go to Admin view
Move to Content Menu
Go to  fields 
Click at new 
Select all 
### Expected result
The system should display only on the option the category dropdown 

### Actual result
The system display two 'All' option under category dropdown  

### System information (as much as possible)
![Articles-New-Field-Administration](https://user-images.githubusercontent.com/53821500/98440370-54c71200-211e-11eb-843d-6ca551015a67.png)

Joomla 4 
PHP Version | 7.3.12-1+ubuntu18.04.1

**Comment by adj9** [comment]
Confirmed :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31352">issues.joomla.org/tracker/joomla-cms/31352</a>.</sub>

**Comment by infograf768** [comment]
It's worse than that.
We also still get `All` when selecting a specific category

<img width="406" alt="Screen Shot 2020-11-07 at 17 54 39" src="https://user-images.githubusercontent.com/869724/98447077-70ccb280-2122-11eb-8f39-832ff4784133.png">

This comes from the fact that multiple is set to true.
@dgrammatiko @Fedik

**Comment by Fedik** [comment]
hm, that because choices.js use empty option as placeholder, and **All** is empty:
https://github.com/joomla/joomla-cms/blob/0e316b3ed2341c17e50ef0bca78fb1d1ef4c2c2e/administrator/components/com_fields/forms/field.xml#L39-L41

changing to `<option value="0">JALL</option>` will fix it, but I am not sure about any side effect

**Comment by Fedik** [comment]
I have opened issue jshjohnson/Choices/issues/912

**Comment by Fedik** [comment]
pleas test #31365

**Comment by Fedik** [comment]
I think it can be closed, or?
