### ISSUE TITLE
[4.0] Search toolbar is not aligned properly for some menu sections -  Modules, field, field groups

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#31353]
### Steps to reproduce the issue
Login to admin panel
Go to Site/administrator modules
Observe the search toolbar
Click field/ field group
Observe the search toolbar

### Expected result
Search toolbar should be aligned to top

### Actual result
Search toolbar is not aligned to top

![screen shot 2020-11-07 at 12 05 22](https://issues.joomla.org/uploads/1/0daa88b3ed77e28af96e385cb379ba07.png)

![screen shot 2020-11-07 at 12 05 22](https://issues.joomla.org/uploads/1/4386dc875cc87963f0edc4d7dd48a224.png)![screen shot 2020-11-07 at 12 05 23](https://issues.joomla.org/uploads/1/3ccb4d2d3bb1e9f36911905b90be6120.png)

**Comment by ghost** [comment]
Duplicate report #31010

**Comment by richard67** [comment]
Closing as duplicate report, see #31010 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31353">issues.joomla.org/tracker/joomla-cms/31353</a>.</sub>
