### ISSUE TITLE
[4.0] atum template reduced-motion css breaks menus

### ISSUE THREAD

**Issue by david19161** [joomla/joomla-cms#31368]
### Steps to reproduce the issue

1. In Windows 10 Ensure the option: Settings > Ease of Access > Display > Show animations in Windows. is UNCHECKED
2. Open Joomla 4 site as administrator
3. Try to open/close the drop-down menus in sidebar left

### Expected result
Menus open/close/toggle correctly

### Actual result
Menus dont open/close/toggle correctly

### System information (as much as possible)
Joomla_4.0.0-beta6-dev-Development-Full_Package (nightly build : 2020-11-09) installed with Wamp on Windows 10

### Additional comments
Problem appears to be with the recently added
CSS rule : @media (prefers-reduced-motion: reduce) {...} in the administrator atum template CSS

Comment this out and all works fine again.
I am not clever enough to determine why this css rule does not work or I would submit a patch to github

**Comment by richard67** [comment]
Duplicate to #31242 ? Please check and if so, close this issue here.

**Comment by david19161** [comment]
Yes. Closing. it is a duplicate of #31242.

**Comment by richard67** [comment]
Thanks for checking.
