### ISSUE TITLE
[4.0] Category-list: Redundant texts in table cells, no scope=row"

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#31367]
### Steps to reproduce the issue
Have a look on a category list, where table headers are visilbe.

### Expected result
The table cells do not repeat redundant text as "written by" in column author or "hits" in column hits IF there is a table header.

### Actual result
<img width="501" alt="redundat" src="https://user-images.githubusercontent.com/1035262/98486684-2a10b280-221f-11eb-85a4-a68f64f8eb28.PNG">

**Comment by brianteeman** [comment]
It does this because there is an option not to display the column headers IIRC

**Comment by gostn** [comment]
- If there is a table header, the table cells do not repeat "written by" in column `author` or "hits" in column `hits`,
- If there is no table header, the table cells do repeat "written by" in column `author` or "hits" in column `hits`.

**Comment by chmst** [comment]
@gostn this is expected result. But the layout does not make a difference in texts if the param show_headings is set or not. 

Additionally the table is not accessible, as there is no scope ="row".

**Comment by infograf768** [comment]
@chmst 
can make patch. to get:

<img width="745" alt="Screen Shot 2020-11-09 at 11 26 50" src="https://user-images.githubusercontent.com/869724/98529912-8525c200-227e-11eb-8d0c-2c28815d2bc4.png">

<img width="745" alt="Screen Shot 2020-11-09 at 11 26 24" src="https://user-images.githubusercontent.com/869724/98529917-86ef8580-227e-11eb-950f-c8ed1df8b059.png">

Questions: 
do we need all the `headers="categorylist_whatever"`
Shall the scope row be added to each `<td>` ?

**Comment by chmst** [comment]
Thank! I don't think that we need the classes - and the scope="row" is on the title, so covering the whole line in the table

**Comment by brianteeman** [comment]
Does it still need to be `hits: 14` when there is a header> Wont it be enough and consistent for that to be just `14`

**Comment by chmst** [comment]
@brianteeman yes, I think so too, The "hits" then is redundant. I have not tried all possible columns.

**Comment by infograf768** [comment]
will also take care of hits

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/31373
