### ISSUE TITLE
[3.x] metadata.xml does not exist - remove entry from the manifest for com_contact

### ISSUE THREAD

**Issue by shoulders** [joomla/joomla-cms#31375]
## 1
There is a line that references a file called `metadata.xml` in `com_contact`, this file does not exist so the entry needs removing.

https://github.com/joomla/joomla-cms/blob/8758c0a3d25b2d6a603cd5c94babfcb770dc0c57/administrator/components/com_contact/contact.xml#L27

## 2 
There is a reference to a folder that does not exists

https://github.com/joomla/joomla-cms/blob/8758c0a3d25b2d6a603cd5c94babfcb770dc0c57/administrator/components/com_contact/contact.xml#L55

**Joomla! Version |** Joomla! 3.9.22 Stable [ Amani ] 6-October-2020 15:00 GMT
**Joomla! Platform Version |** Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by ReLater** [comment]
<strike>I can't confirm the first find "metadata.xml"
but the second one "elements"
in current staging branch.</strike>

Confirmed.

**Comment by ReLater** [comment]
Corrected my previous comment.

**Comment by alikon** [comment]
test #31412
