### ISSUE TITLE
An Actionlog translation string is not correctly converted into UPPERCASE

### ISSUE THREAD

**Issue by shoulders** [joomla/joomla-cms#31378]
If you look at the line

https://github.com/joomla/joomla-cms/blob/ab62797b7c167964bb09c09d29290ecca7383170/plugins/actionlog/joomla/joomla.php#L451-L452

The translation string is not correctly converted in to a fully UPPERCASE string like

https://github.com/joomla/joomla-cms/blob/ab62797b7c167964bb09c09d29290ecca7383170/plugins/actionlog/joomla/joomla.php#L400-L401

## Notes
- So just adding `strtoupper()` to this  `onExtensionAfterUpdate()` to match the similiar functions `onExtensionAfterUninstall()` and `onExtensionAfterInstall()` in this class will fix this. 
- The lack of this `strtoupper()` might cause the key lookup to fail.

**Comment by SharkyKZ** [comment]
This shouldn't really be an issue because related methods in language class run keys through `strtoupper()`.

**Comment by shoulders** [comment]
true, but it should match the other methods/statements. 😄

**Comment by infograf768** [comment]
We have multiple examples of this kind of code.
`$this->toc[$key] = Text::_('COM_ADMIN_HELP_' . $value);`
`Text::_('COM_BANNERS_FIELD_VALUE_' . $purchaseTypes[$params->get('purchase_type')])`
`$label = empty($fieldSet->label) ? 'COM_CONFIG_' . $name . '_FIELDSET_LABEL' : $fieldSet->label; ?>`
`$lang_key    = 'PLG_FINDER_STATISTICS_' . str_replace(' ', '_', $type->type_title);`
`<?php echo Text::_('COM_PRIVACY_HEADING_REQUEST_TYPE_TYPE_' . $item->request_type); ?>`

etc. etc.

if we start adding `strtoupper()` to all such occurrences in core, this would add quite a work.

Welcome to propose patch.

**Comment by shoulders** [comment]
@infograf768 

- Not sure what you are showing me, all I know is that this method's code does not match its neighbours in the same class, which it should.
- The rest of the similiar statements in this class have strtoupper().
- Literally it just needs `strtoupper()` adding.

`Welcome to propose patch` = I dont know how to and I discovered this whilst building my first component so i need to finish that before learning something else. 😄

**Comment by infograf768** [comment]
The samples above comes from core code in various places where `strtoupper()` is not used but it's working fine as @SharkyKZ righfully commented.

**Comment by ReLater** [comment]
> true, but it should match the other methods/statements

I would remove strtoupper() from other methods (consistency and less code) if nothing fails then.

**Comment by brianteeman** [comment]
This should be closed if no one is going to create the pr

**Comment by HLeithner** [comment]
We have a pull request #33072
