### ISSUE TITLE
Joomla 4 web api {"errors":[{"title":"Forbidden"}]}

### ISSUE THREAD

**Issue by studio16** [joomla/joomla-cms#31371]
### Steps to reproduce the issue
Joomla 4 installed, all api related plugins enabled
Created a token in de admin
Tried both basic authentication 
"Authorization: Basic ".base64_encode($user.':'.$pass),
and with token
"Authorization: Bearer TokenFromSuperadmin",

### Expected result
results in json format

### Actual result
{"errors":[{"title":"Forbidden"}]} on all requests

### System information (as much as possible)
Joomla! 4.0.0-beta6-dev Development [ Mañana ] 27-October-2020
php 7.3
10.4.15-MariaDB-1:10.4.15+maria~bionic

### Additional comments
Tried it with Postman and with an actual php (using curl) on the same server

**Comment by alikon** [comment]
quite sure it can be explained here: https://github.com/joomla/joomla-cms/pull/27021#issuecomment-553544402

**Comment by studio16** [comment]
Thanks, that did the trick

**Comment by alikon** [comment]
closing

**Comment by brianteeman** [comment]
Does this need adding to the docs?

**Comment by alikon** [comment]
i think so
