### ISSUE TITLE
[4.0] Option "Number of columns" in List All Tags doesn't work

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#31388]
### Steps to reproduce the issue
Create some tags.
Create a menu item of type "List All Tags".
Play with the option "Number of Columns".

### Expected result
The tags are showed in columns as set in the options.

### Actual result
The tags are all in one column, but depending of the settings there is 1 or more ul lists holding the tags.

Columns: 7 (one ul with 3 li elements)
![grafik](https://user-images.githubusercontent.com/9153168/98932328-7d188d00-24df-11eb-9471-2a02db78321a.png)

Columns: 1 (3 ul with 1 li element each)
![grafik](https://user-images.githubusercontent.com/9153168/98932375-8d306c80-24df-11eb-9e1b-fb448537bed1.png)

**Comment by adj9** [comment]
<b> HTML inspect </b>
![Schermata 2020-11-14 alle 16 40 54](https://user-images.githubusercontent.com/5918444/99151032-a3355d00-2698-11eb-9200-931415d96cd7.png)


In this case the row tab5 is wider. It's Bootstrap problem?

**Comment by N6REJ** [comment]
for w/e reason the columns value is treated as rows.  So when you say 3 columns, it's returning 3 ROWS.  This is being caused by .css
![image](https://user-images.githubusercontent.com/1850089/99373641-42b84280-2887-11eb-9ede-37f1aa54b86f.png)
I'm looking into the best fix.

**Comment by N6REJ** [comment]
layout looks totally different in chrome then in FF.  This is effecting https://github.com/joomla/cassiopeia/issues/209 also.
Started a PR.. https://github.com/joomla/joomla-cms/pull/31422
