### ISSUE TITLE
[4.0] [com_fields] Site display dl rather than ul?

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#31385]
### Steps to reproduce the issue

See the forum discussion: https://forum.joomla.org/viewtopic.php?f=803&t=982946

Does anyone know why custom fields are set as list items in a bulleted list? The preceding fields (by default) are set as definition terms in a definition list. 

### Expected result

Best would be for custom fields to have same styling as standard fields.

### Actual result

Custom fields are bulleted. Standard fields are not.

### Additional comments

It can be done with overrides and styles. BUT the default ought to be best for novices - all the same.

**Comment by brianteeman** [comment]
It is not about how they are styled but what is the meaning of those lists. A definition list and an unordered list have different semantic meanings. In this case the type of list is semantically correct.

**Comment by ceford** [comment]
For completeness here is a screen shot:

![image](https://user-images.githubusercontent.com/1560390/98893151-c7771b00-2499-11eb-81ac-53a4962e4e2a.png)

So which list is semantically correct? Is it the dl or the ul? And what should we tell users, especially novices, who would like to see a single list?

**Comment by brianteeman** [comment]
Each is semantically correct they are separate lists

**Comment by ceford** [comment]
Can you explain why the first list is a dl and the second is a ul? The only reason I can think of is that dl lists do not contain sub-lists while ul lists may. But I have not found a way to generate a sub-list with the available fields. It seems to me that both are lists of attributes of an article. So why different list types?

**Comment by brianteeman** [comment]
UL is just a list with no specific meaning
DL is a description list of (in this case) the article

see
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/ul

**Comment by ceford** [comment]
I know what they are. What I am asking is why one or other was chosen in this instance. And more specifically why different types of list. It looks like it could be different coders personal preferences. It would make more sense (to me) if both lists were dl or ul. And re-coding the ul as dl would be an incredibly simple change.

**Comment by 200MPHMEDIA** [comment]
The problem with this is that the Fields in Field Groups when used within Articles, by default, is a bulleted list, and every field is preceded by a bullet - including images!!!  Every singly type of Field format, when used and invoked within the Field Group within the Article, ALL display a preceding bullet, even when the Field Label is set to "hide."  Novice or beginning users would have no way of know how to cure this with a class insertion.  The default should be a list display WITHOUT bullets, in traditional list display for the types of form fields available.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31385">issues.joomla.org/tracker/joomla-cms/31385</a>.</sub>

**Comment by 200MPHMEDIA** [comment]
Here is a screenshot of the issues with BULLETS preceding Fields in Field Groups.  This is the "default" and it should be no-bullet vs. a disc.![screen shot 2020-11-12 at 15 15 04](https://issues.joomla.org/uploads/1/c0b13949d43f706a5ed237940a6c65f3.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31385">issues.joomla.org/tracker/joomla-cms/31385</a>.</sub>

**Comment by ceford** [comment]
So I found issue #27567: **[4.0] Accessibility definition lists** where dl was changed to ul. I am not convinced our usage for the display of fields warranted the change. My reference: https://www.w3.org/WAI/tutorials/page-structure/content/#lists

**Comment by brianteeman** [comment]
@200MPHMEDIA the display of the bullet or not is just css - its nothing to do with if a dl or ul is used

@ceford Not really my job to convince and I've learned not to try. It is a dl because the items in that list are used to describe the article eg this article was written by george on wednesday. The fields are part of the article. They dont describe the article therefore they are a ul.

**Comment by 200MPHMEDIA** [comment]
What?  There is an affirmation that a default bullet before all Fields in Field Groups within Articles is OK?  That position isn't correct.  The fields, by default should not be a bulleted list.  Period. Full Stop.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31385">issues.joomla.org/tracker/joomla-cms/31385</a>.</sub>

**Comment by ceford** [comment]
With this explanation:

@brianteeman: It is a dl because the items in that list are used to describe the article eg this article was written by george on wednesday. The fields are part of the article. They dont describe the article therefore they are a ul.

It seems to me a compromise is possible. If the custom fields are part of the article the user ought to be able to choose how they are displayed. Either a ul or dl or something else. That ought to be easily done with a list form field.

**Comment by 200MPHMEDIA** [comment]
How about just NOT putting any bulleted list css that will invoke at that point.  Or force a no bullet css that can be overridden in the class if desired.  Just don't display the silly things by DEFAULT.  It looks so unprofessional and graphically ludicrous, especially with an image field, etc.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31385">issues.joomla.org/tracker/joomla-cms/31385</a>.</sub>

**Comment by brianteeman** [comment]
Guys

A dl doesn't mean it doesn't have bullets
A ul doesnt mean it does have bullets

Those are css styling issues that should be handled in the template

Changing from DL and UL is not correct - full stop- just because you want or dont want bullets. It's exactly the same as not using H1 because you want big text in the middle of the page

Removing the bullet is as simple as adding the following line to your template

`ul.fields-container {list-style: none;}`

**Comment by ceford** [comment]
Ok - let us leave it at that. I will work something into the documentation. We need to remove padding too:

ul.fields-container {list-style: none; padding-left: 0;}

**Comment by brianteeman** [comment]
No reason for you not to raise it as a css style issue. I have no opinion on that. I am just explaining that dl and ul are correct markup

**Comment by ceford** [comment]
I think users migrating from Joomla 3 would appreciate that. Do you have a suggestion on where it might be placed? I was thinking _legacy.scss - with a comment on why it is there.
