### ISSUE TITLE
StringHelper not used in `ContactModelContact` class but  is referenced

### ISSUE THREAD

**Issue by shoulders** [joomla/joomla-cms#31383]
https://github.com/joomla/joomla-cms/blob/ab62797b7c167964bb09c09d29290ecca7383170/administrator/components/com_contact/models/contact.php#L13

this class comes up as unused in my Netbeans IDE and I cannot find in this file where it is used in this class

I think this should be removed

**Comment by Quy** [comment]
Please test PR #31403
