### ISSUE TITLE
Object relocation in new tags Options tab

### ISSUE THREAD

**Issue by adj9** [joomla/joomla-cms#31402]
### Steps to reproduce the issue
Go to:
- New tag
- Options tab

Dimension window: 1273 × 1001
In full screan mode (with iMac) there is no object overlap.

### Expected result
I do expect the overlap between the image preview and the filels.
### Actual result
I do not expect the overlap between the image preview and the filels.
![Schermata 2020-11-14 alle 15 41 13](https://user-images.githubusercontent.com/5918444/99149866-e2f84680-2690-11eb-8c26-e762d2a036b7.png)

### System information (as much as possible)
- Website
- Chrome v. 86.0.4240.193 (Build ufficiale) (x86_64)
- mac OSX v. 10.15.7

**Comment by Quy** [comment]
PR #31810

**Comment by Quy** [comment]
Fixed in PR #32422. Thanks for reporting.
