### ISSUE TITLE
getWebAssetManager() on null when calling JHtml::_('jquery.framework') from onAfterRoute()

### ISSUE THREAD

**Issue by mavrosxristoforos** [joomla/joomla-cms#31415]
### Steps to reproduce the issue

Install any system plugin (or edit an existing one to test it) and write (or modify an existing onAfterRoute() function)
```
  public function onAfterRoute() {
    JHtml::_('jquery.framework');
  }
```

### Expected result

jQuery added in document scripts.

### Actual result

Error: 0 Call to a member function getWebAssetManager() on null
Location: JROOT\libraries\src\HTML\Helpers\Jquery.php:48

### System information (as much as possible)

Joomla 4 Beta 5
PHP 7.2.10

### Additional comments

I believe that the PHP version is irrelevant, as well as any other system information.
This occurs at JROOT\libraries\src\HTML\Helpers\Jquery.php, line 48
```
46:  public static function framework($noConflict = true, $debug = null, $migrate = false)
47:  {
48:    $wa = Factory::getApplication()->getDocument()->getWebAssetManager();
```

The document property of the Application object is null.
Same happens both in the front-end (SiteApplication) and the back-end (AdministratorApplication).
Maybe it's not supposed to work at that point anyway, but it worked on Joomla 3, so I thought I should mention it.

**Comment by Fedik** [comment]
hmhm, that because Document not exists in Application until dispatch happen

https://github.com/joomla/joomla-cms/blob/52cf46e2f7b8f7154df799514303097aa1911d79/libraries/src/Application/SiteApplication.php#L135-L146

I would suggest just move your JHtml::_('jquery.framework'); to onAfterDispatch event

**Comment by joeforjoomla** [comment]
@Fedik yes that's the reason, but this issue could potentially break several sites, it would be ideal to provide a legacy way to have it working.

**Comment by mavrosxristoforos** [comment]
@Fedik Yes, I tried that and it seems to work. Also `onBeforeCompileHead()`. However, I thought it was worth mentioning somewhere, because it worked differently on Joomla 3.

@joeforjoomla I agree.

**Comment by joomdonation** [comment]
Closing this issue hear because the user who reported this issue had solution for this problem. Anyone has similar issue, please look at @Fedik answer above https://github.com/joomla/joomla-cms/issues/31415#issuecomment-728154802
