### ISSUE TITLE
Please change the type "text" with "longtext" for the params field in the "extensions" table.

### ISSUE THREAD

**Issue by nhamphap2002** [joomla/joomla-cms#31429]
### Steps to reproduce the issue

I have a lot of user groups and I go to "Global Configuration" and save the configuration it will get "Error decoding JSON data: Syntax error". Because the field "params" does not contain all the strings

![screen shot 2020-11-19 at 03 49 37](https://issues.joomla.org/uploads/1/49f75d6714dd227a15800b55a12d27cb.png)

**Comment by richard67** [comment]
We have had several similar issues, see https://github.com/joomla/joomla-cms/pull/25702#issuecomment-515012127 .

Do you have some 3rd party extension saving all this data in the extensions table?

**Comment by Quy** [comment]
@wilsonge @HLeithner Close as won’t fix?

**Comment by wilsonge** [comment]
Yes per the issues referenced
