### ISSUE TITLE
[3.9] unused field in com_contact contact.xml form

### ISSUE THREAD

**Issue by shoulders** [joomla/joomla-cms#31437]
The following field does not appear to be used in **com_contact** anywhere and I do not understand what the `@` sign is for either.
https://github.com/joomla/joomla-cms/blob/a5b37ed5b199b7489e9f91b35a47209947d41c02/administrator/components/com_contact/models/forms/contact.xml#L301-L306

The JTEXT reference is:
https://github.com/joomla/joomla-cms/blob/a5b37ed5b199b7489e9f91b35a47209947d41c02/administrator/language/en-GB/en-GB.com_contact.ini#L26

I have done a text search in **com_contact** I have and cannot find this `text_details`

## What now

I think this should be removed

## Other notes

it appears to be an issue in J4 (but I have not looked properly at J4)
https://github.com/joomla/joomla-cms/blob/c6332d48dab0fce0d4903f206dc979e2c2c59a12/administrator/components/com_contact/forms/contact.xml#L271-L276

JTEXT
https://github.com/joomla/joomla-cms/blob/c6332d48dab0fce0d4903f206dc979e2c2c59a12/administrator/language/en-GB/com_contact.ini#L19

## System Details

Setting | Value
-- | --
 
PHP Built On | Windows NT E6540 10.0 build 19041 (Windows 10) AMD64
Database Type | mysql
Database Version | 5.5.5-10.4.10-MariaDB
Database Collation | utf8mb4_unicode_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.12
Web Server | Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.12
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.9.22 Stable [ Amani ] 6-October-2020 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:82.0) Gecko/20100101 Firefox/82.0

**Comment by Bakual** [comment]
Looks indeed like a leftover. It got introduced with https://github.com/joomla/joomla-cms/commit/6234151121a601d3659f2d4da9b2eab441699223, but that was just some sync merge of another branch.
The language string itself goes back even further (year 2010).

So I think this field indeed can be safely removed. Do you want to prepare a PR?

**Comment by shoulders** [comment]
@Bakual if you are asking me to prepare a PR I have not got to that stage of my coding development yet. I am just building my first component, so maybe after I have graduated from that i can start doing these. 😄 

Also this issue is present in J3 and J4

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/31439

**Comment by shoulders** [comment]
@bakul #31439 looks good I would also remove COM_CONTACT_EDIT_DETAILS translation

https://github.com/joomla/joomla-cms/search?q=COM_CONTACT_EDIT_DETAILS

it is present in 3 places
