### ISSUE TITLE
[3.9] html tags (ex "ed from "Content - Confirm Consent" plugin's "Short Privacy Policy" field

### ISSUE THREAD

**Issue by altrasoluzione** [joomla/joomla-cms#31430]
### Steps to reproduce the issue

The goal is to provide a clickable link to an external Privacy Policy (ex. Iubenda) directly in "Short Privacy Policy" without have to create a "Privacy Article" but, if I insert in the field any html code (please find attached image), it is removed as soon as I save the plugin settings.

### Expected result

HTML tags should be left alone so that a link to privacy policy can be inserted directly directly in "Short Privacy Policy" field

### Actual result

HTML code (<a href=...</a>) is removed as soon as I save the plugin settings.
The text in the attached example becomes "Accetto il trattamento dei dati personali così come indicato nella Privacy Policy." as soon as plugin is saved.

### System information (as much as possible)

Joomla 3.9.22

**Comment by brianteeman** [comment]
you can create a language override for the string PLG_SYSTEM_PRIVACYCONSENT_NOTE_FIELD_DEFAULT

**Comment by altrasoluzione** [comment]
The idea is correct but the right string is PLG_CONTENT_CONFIRMCONSENT_FIELD_NOTE_DEFAULT
I've done it and it seems it's working.
Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31430">issues.joomla.org/tracker/joomla-cms/31430</a>.</sub>

**Comment by altrasoluzione** [comment]
...but it would be easier if the plugin accepted html :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31430">issues.joomla.org/tracker/joomla-cms/31430</a>.</sub>
