### ISSUE TITLE
ability to remove up/down arrows from a number field

### ISSUE THREAD

**Issue by shoulders** [joomla/joomla-cms#31441]
### Is your feature request related to a problem? Please describe.
Currently all rendered number fields have the up/down arrows on them. The arrows can be removed by CSS if needed but this is template/css based.

**With Arrows**
![image](https://user-images.githubusercontent.com/319997/99833497-ff492700-2b59-11eb-882c-2957fa6f3d82.png)

**Without arrows**
![image](https://user-images.githubusercontent.com/319997/99833534-0d974300-2b5a-11eb-93e5-52eb7039cf4e.png)

### Describe the solution you'd like
I would like an option that you can configure in the field configuation so this option was not template/css dependant.

Maybe call the new option `arrows="false"`

```xml
<field
    name="id"
    type="number"
    label="JGLOBAL_FIELD_ID_LABEL"
    description="JGLOBAL_FIELD_ID_DESC"
    default="0"
    class="readonly"
    size="10"
    readonly="true"
    arrows="false"
/>
```
### Additional context
You can use the following css to remove the arrows:

```css
style="appearance: textfield"
```
There is not an option I have found https://docs.joomla.org/Number_form_field_type

**Comment by Quy** [comment]
Duplicate #30885. Thanks for the report.
