### ISSUE TITLE
[3.x - 4.0]  Options and Publishing

### ISSUE THREAD

**Issue by rinka88** [joomla/joomla-cms#31455]
1) I think I need to swap places. Since Publishing parameters are more important than Options. Options can be configured globally. And don't touch.
For the author, the meta date settings are more important than the options.
![Screenshot_4](https://user-images.githubusercontent.com/40716604/99885109-7236c880-2c54-11eb-8f73-93d6e34aef7f.png)

2) There are 2 lines in the tab below
read more text and browser page title
They must be transferred to the Publications tab along with Meta Date. They are closer than options.
And some users don't even know that there is such a string. If you transfer to the Publication together with the Meta date, then I think it will be more visible to everyone for the title of the page browser header and the button to read more text.
![Screenshot_3](https://user-images.githubusercontent.com/40716604/99885110-74992280-2c54-11eb-9181-6a0d4898300b.png)

**Comment by bembelimen** [comment]
See #23233 and especially #15833 for a similar discussion, perhaps you can go there and help improving it?
