### ISSUE TITLE
Database Settings - Password DB

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#31452]
### Steps to reproduce the issue
Go to the Backend > Global Configuration > Server > Database Settings
Try to use a different DB (Example: a DB of a empty Joomla installation).
You can't specify the DB password (in FTP configuration you can)

### Expected result
![image](https://user-images.githubusercontent.com/906604/99882311-bf4c7780-2c1f-11eb-9a19-5457d2ac0ae8.png)

### Actual result
![image](https://user-images.githubusercontent.com/906604/99882316-ca070c80-2c1f-11eb-88f5-21f684a4a5f5.png)

### Additional comments
On save Joomla must check if the new connection parameters work correctly (like in the installation setup) and the save the info.
The issue is for J3 and J4.

I think without the password the other DB fields is pointless.

**Comment by ne4lh** [comment]
joomla 4 added this code
administator/components/com_config/forms/application.xml

 <field
     name="db_password"
     type="password"
     label="COM_CONFIG_FIELD_DATABASE_PASSWORD_LABEL"
     required="true"
     validate="password"
     force="on"
     filter="raw"
  />

admin language file
COM_CONFIG_FIELD_DATABASE_PASSWORD_LABEL="Database Password"
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31452">issues.joomla.org/tracker/joomla-cms/31452</a>.</sub>

**Comment by ne4lh** [comment]
[j4.txt](https://issues.joomla.org/uploads/1/17ca05627038a122f28e0836ec5f177c.txt)

did post the first time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31452">issues.joomla.org/tracker/joomla-cms/31452</a>.</sub>

**Comment by HLeithner** [comment]
Closing because we have a pr #31672
