### ISSUE TITLE
A space inside the link when create menu item alias

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#31466]
I noticed a space inside the link when you create a menu item alias.
Screenshots:
<img width="340" alt="Снимок экрана 2020-11-23 в 17 50 17" src="https://user-images.githubusercontent.com/3432048/99976541-9f9a8800-2db4-11eb-99d6-493a068990c2.png">

<img width="334" alt="Снимок экрана 2020-11-23 в 17 51 33" src="https://user-images.githubusercontent.com/3432048/99976547-a1644b80-2db4-11eb-93fb-7c904cd245eb.png">

Need to move the space from URL to the right.

**Comment by hans2103** [comment]
Steps to reproduce:

- Create a new menu item of type = `System Links > Menu Item Alias`
- Press the button `Select` on _Menu Item_
- A modal popup appears and compare the result of the provided sceenshot

I can reproduce the issue. 

![Schermafbeelding 2020-11-24 om 13 37 53](https://user-images.githubusercontent.com/639822/100095119-50a72e00-2e5a-11eb-8d29-8ca1f6777ec3.png)

**Comment by hans2103** [comment]
Created PR https://github.com/joomla/joomla-cms/pull/31474 to solve the issue. 
@Sulpher can you please test the created PR?

**Comment by alikon** [comment]
please test #31474 and/or #31475
