### ISSUE TITLE
User menu item class in administrator menu

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#31463]
I've created an additional menu in the administrator panel:
<img width="1027" alt="Снимок экрана 2020-11-23 в 10 58 13" src="https://user-images.githubusercontent.com/3432048/99939485-34808f80-2d7b-11eb-8edb-67ff4bfd00c4.png">

And added class for menu item:
<img width="860" alt="Снимок экрана 2020-11-23 в 10 58 20" src="https://user-images.githubusercontent.com/3432048/99939500-3cd8ca80-2d7b-11eb-8611-f16dd8e72983.png">

But it take no effect.
I see the following code:

```
<li>
<a class="no-dropdown" href="index.php?option=com_jshopping">Магазин</a>
</li>
```
There should be **btn btn-large btn-primary** where is **no-dropdown**

My suggestion is to make such a feature and we can get:
<img width="993" alt="Снимок экрана 2020-11-23 в 11 03 39" src="https://user-images.githubusercontent.com/3432048/99939640-93460900-2d7b-11eb-892c-4b9c07f52845.png">

**Comment by brianteeman** [comment]
confirmed - and also with the first field link description

**Comment by infograf768** [comment]
The menu item params are just ignored for backend menu items.
They are for frontend mod_menu in its helper `.../modules/mod_menu/src/Helper/MenuHelper.php`

But for backend the params are not fetched

**Comment by N6REJ** [comment]
worked for me.
![image](https://user-images.githubusercontent.com/1850089/100728783-98afde80-338d-11eb-9925-2409df0879fb.png)

**Comment by brianteeman** [comment]
I think there may be a mistranslation in Russian that is causing the problem.
That field is only to add a class to any icon that is used.
It is not a class for the entire link

**Comment by Sulpher** [comment]
> I think there may be a mistranslation in Russian that is causing the problem. That field is only to add a class to any icon that is used. It is not a class for the entire link

It comes from the original J3 word:
<img width="920" alt="Снимок экрана 2022-06-18 в 21 24 27" src="https://user-images.githubusercontent.com/3432048/174454796-e216e12d-e72d-4883-9bbf-1c65401aedcf.png">

**Link class** - I thought it is kind of `<a class="">` 

J4 has the right definition: Link Icon Class
