### ISSUE TITLE
Question about Users Authorise function

### ISSUE THREAD

**Issue by roscofil** [joomla/joomla-cms#31472]
Hello all,

First, pls forgive my limited experience here as I'm by no means a core Joomla dev: 

I am cstomizing the Joomshopping component for a website I manage and I ran reently into an interesting question: In JoomShopping, some tools are only available to admins using the $user->authorise function.
However, it turns out that if Superusers can view and access these tools, it is not true for Administrators.

Codeline involved is: $access["module_name"] = $user->authorise('core.admin', 'com_jshopping')==1;

With core.admin being set, the administrator cannot use the tool whereas the superuser can.

The only way I could make it work is by changing the line to:

$access["module_name"] = $user->authorise('core.manage', 'com_jshopping')==1;

First question is: am I misunderstanding anything or making any mistake here?
Second question is: if I make a mistake can somebody tell me how to fix this, otherwise what happens here?

Thanks

Philippe

**Comment by Bakual** [comment]
This is the issue tracker for Joomla Core. It's not a support forum.
For support questions you can use http://forum.joomla.org/ or https://joomla.stackexchange.com/ or the developer of the extensions you're having troubles with.

**Comment by roscofil** [comment]
True, except that, if I’m right, there’s no “development” or “customization” zone on http://forum.joomla.org/ and since this is linked to a basic functionality of Joomla, the extension developer will kick me out.

De : Thomas Hunziker <notifications@github.com>
Envoyé : mardi 24 novembre 2020 12:43
À : joomla/joomla-cms <joomla-cms@noreply.github.com>
Cc : roscofil <roscofil@live.fr>; Author <author@noreply.github.com>
Objet : Re: [joomla/joomla-cms] Question about Users Authorise function (#31472)


This is the issue tracker for Joomla Core. It's not a support forum.
For support questions you can use http://forum.joomla.org/ or https://joomla.stackexchange.com/ or the developer of the extensions you're having troubles with.

**Comment by Bakual** [comment]
> True, except that, if I’m right, there’s no “development” or “customization” zone on http://forum.joomla.org/

You can also use https://groups.google.com/g/joomla-dev-general if that fits you more.

> since this is linked to a basic functionality of Joomla, the extension developer will kick me out.

I'm sure he could still help you. You're still wrong here.

**Comment by roscofil** [comment]
>> I'm sure he could still help you. You're still wrong here.

Nice and gentle way to welcome new folks….

**Comment by Bakual** [comment]
Sorry for that harsh response.
I've pointed you to four different better suited places where you can get the help you want.

**Comment by roscofil** [comment]
Thx

De : Thomas Hunziker <notifications@github.com>
Envoyé : mardi 24 novembre 2020 13:05
À : joomla/joomla-cms <joomla-cms@noreply.github.com>
Cc : roscofil <roscofil@live.fr>; Author <author@noreply.github.com>
Objet : Re: [joomla/joomla-cms] Question about Users Authorise function (#31472)


Sorry for that harsh response.
I've pointed you to four different better suited places where you can get the help you want.

**Comment by HLeithner** [comment]
@roscofil you have to give "Configure ACL & Options" rights to the administrator and should ask Joomshopping maintainer to change this if you feel it's wrong.
