### ISSUE TITLE
[3.x] Publising a tag in the backend overview doesn't work

### ISSUE THREAD

**Issue by may33** [joomla/joomla-cms#31479]
Hello,

I report an issue saw today on my latest Joomla version 3.9.23 (it also occurs on the former one): on the backend tags list manager, there is no way to publish the tag: when you select "Publish," it gets "Archived" value. So, on the tag components items, when asked to select a tag, none of the created ones is found. Is it a bug or does anything needs to be enabled in order to make them working well?

Looking forward for a feedback, best regards.

**Comment by pe7er** [comment]
@HLeithner Thanks for moving the issue to the right repo!

**Comment by brianteeman** [comment]
I  am unable to replicate this

![tag](https://user-images.githubusercontent.com/1296369/100148513-c4fec300-2e94-11eb-9ac5-969fd949414d.gif)

**Comment by may33** [comment]
Hi there, thanks for answering. We do not know; on our site it does not work but we saw many ones reported that issue. In case you want to check it on our side, we can send you the link.
________________________________

**Comment by may33** [comment]
No solutions for that? :)

**Comment by HLeithner** [comment]
can you make a screen cast like brian and maybe tell us which extensions you are using.

But basically this looks like a question for the forum because it doesn't seem to be a bug in joomla

**Comment by chmst** [comment]
Maybe I know what your problem is. The two Buttons for publishing and the one other changes are near together.
![grafik](https://user-images.githubusercontent.com/1035262/100928622-be043000-34e6-11eb-9ba1-fd7cf9d36a6a.png)

So maybe you clicked on the archive button instead of the red unpublished button as I did right now, trying to replicate your problem.

**Comment by may33** [comment]
hello there, thanks for answer. Unfortunately, this is not the problem for it happens also when selecting correctly "publish."
________________________________

**Comment by chmst** [comment]
Then I cannot confirm the issue for the joomla core. Which extension is it?

**Comment by may33** [comment]
we are not using any tags extension, just trying to set up the native one and we saw this issue that did not occur on the older Joomla versions
________________________________

**Comment by chmst** [comment]
As we cannot confirm this problem, we need more information. Can you please post a video?

**Comment by may33** [comment]
Hello. We do apologize for late reply, but we are discontinuous cause the covid restrictions.
Anyway, in case it may be useful, we can send you the backend credentials to check it directly.
Best regards.
________________________________

**Comment by brianteeman** [comment]
There really is no point in keeeping this open

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As no one has been able to replicate this issue this should be closed.

cc @zero-24
