### ISSUE TITLE
[3.9] Category with only root parent raises a warning message

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#31473]
### Steps to reproduce the issue
* Blog layout showing category "uncategoriesed" with an article.
* Null object Warning is visible

### Expected result
No Error

### Actual result
Warning: Attempt to read property "id" on null in components/com_content/views/category/view.html.php on line 270

### System information (as much as possible)
3.9.23 with php8-rc5

### Additional comments
Maybe only a php8 issue

**Comment by chmst** [comment]
Trying to reproduce this in php 8 , J3.9.23, but I don't get a notice. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31473">issues.joomla.org/tracker/joomla-cms/31473</a>.</sub>

**Comment by PhilETaylor** [comment]
I get this. PHP 8.0.2-dev. Joomla 4 beta 6

<img width="917" alt="Screenshot 2021-01-08 at 23 30 24" src="https://user-images.githubusercontent.com/400092/104074996-7e2d1880-5209-11eb-8778-f4822c6ea004.png">


My set up was for https://github.com/joomla/joomla-cms/issues/31925 and then I just clicked the Category that was linked to http://127.0.0.1/index.php?view=category&id=2

**Comment by rjharishabh** [comment]
@PhilETaylor where can find Joomla 4 repo.
I have cloned Joomla 3.x repo, but I want to work on some known issues related to Joomla 4.x

**Comment by drmenzelit** [comment]
After cloning you need to check out the 4.0 branch

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/README.md

**Comment by rjharishabh** [comment]
Thanks sir

**Comment by pank1999** [comment]
i want to contribute and try to resolve this issue please assign this task to me

**Comment by alikon** [comment]
unable to replicate this with php 8 in 3.9.26-dev

**Comment by joomdonation** [comment]
@PhilETaylor Could you please check to see if you still get this error with latest Joomla 4.0-dev? I could not re-procedure this issue anymore

**Comment by PhilETaylor** [comment]
I cannot replicate this, in todays (8f9fac668cb27489c85daa9301d0cb383f96a5ba) Joomla `staging` branch, based on the "Steps to reproduce the issue" provided by @HLeithner in opening this issue last year.

However, This same problem was reported by me in Joomla 4 (https://github.com/joomla/joomla-cms/issues/31925) and was replicated by others and ultimately fixed (https://github.com/joomla/joomla-cms/pull/32027) in Joomla 4 in January 2021

The [fix used there](https://github.com/joomla/joomla-cms/pull/32027/files) was to cast to `(int)`

As its complaining that `$category` is null, and as `$category` is derived from `$category = $this->category->getParent();` we have to assume that the Uncategorised category parent is not ROOT like it should be in a normal set up.

I have exhaustively tested this, making wild assumptions, deleting the root category etc, and I have been unable to replicate it in Joomla `staging` today. 

As this report was made on 24th November 2020 I have reverted to commit 435d780d9a87504267256033c5f6fb984f713ff9 which was the "Prepare Joomla! 3.9.23 release" commit to test as well. 

Using that commit, and my current custom PHP 8.0.3 version, with full error reporting set to development in Joomla and maximum in PHP.ini I am unable to replicate this issue at all.

**Comment by joomdonation** [comment]
@PhilETaylor Actually, after looking carefully at the code, I can re-procedure the issue myself. The error happens when there is no menu item created to one of the options:

- List All Categories
- Category List
- Category Blog

And category is accessed via Articles - Categories module. The actual error causes by some changes in php 8:

- Before php 8: $cateogory->id > 1 return false for root category ($category->id has value 'root')
- With php 8, $cateogory->id > 1 return true for root category, so the code inside if block runs and we have the warning.

**Comment by joomdonation** [comment]
So I made two PRs: one for staging https://github.com/joomla/joomla-cms/pull/32767 and one for 4.0-dev https://github.com/joomla/joomla-cms/pull/32768 . We can close this issue now.

**Comment by alikon** [comment]
please test #32767 and #32768
