### ISSUE TITLE
Php 8 gives a warning on cpanel backend.

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#31483]
### Steps to reproduce the issue

Set php to 8.

Login and you will see the warning on top, if you have enabled error reporting.

### Expected result

no warning.

### Actual result

Warning: FOFModelBehavior::onBeforeBuildQuery(): Argument #1 ($model) must be passed by reference, value given in \libraries\fof\utils\observable\event.php on line 63

### System information (as much as possible)

Joomla! 3.9.23

**Comment by alikon** [comment]
as a reference see #31446

**Comment by alikon** [comment]
please test #31537

**Comment by maximsamoilov** [comment]
I have the same problem on php 7.4, joomla 3.9.22, 3.9.23

**Comment by jameswadsworth** [comment]
Same issue with Joomla 3.9.23 and below on PHP 7.4.12. Will test patch #31537

**Comment by joomlaweby** [comment]
I have the same problem with php 7.3.25 and joomla 3.9.23

**Comment by HLeithner** [comment]
@maximsamoilov @jameswadsworth and @joomlaweby can you please test #31600 easiest way is to download https://ci.joomla.org/artifacts/joomla/joomla-cms/staging/31600/downloads/38100/Joomla_3.9.24-dev+pr.31600-Development-Update_Package.zip and mark you test as success or fail on https://issues.joomla.org/tracker/joomla-cms/31600

please do this till monday thanks
