### ISSUE TITLE
[4.0] Ordering fields ?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31488]
We have three fields for ordering and each one has a different ui as shown below. We should pick one UI and stick to it

### Plugin 
administrator\components\com_plugins\src\Field\PluginorderingField.php

![image](https://user-images.githubusercontent.com/1296369/100291789-a1ac4480-2f76-11eb-99f6-9a28edd9222d.png)

### Module
layouts\joomla\form\field\moduleorder.php

![image](https://user-images.githubusercontent.com/1296369/100291871-da4c1e00-2f76-11eb-9140-f3bf6f7c1fd1.png)

### Menu
administrator\components\com_menus\src\Field\MenuOrderingField.php

![image](https://user-images.githubusercontent.com/1296369/100291911-f6e85600-2f76-11eb-9496-4310d400be29.png)

**Comment by ghost** [comment]
I suggest ´menu´. There is also issue #30047 for using ´- first -´ and ´-last-´

**Comment by ghost** [comment]
I suggest Module

**Comment by ghost** [comment]
> I suggest Module

why?
