### ISSUE TITLE
Why do we use the  ID of the category for checking permissions in toolbar of an item?

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#31484]
### Problem identified
I like to understand, why we use the  ID of the category for checking permissions in toolbar of an item: https://github.com/joomla/joomla-cms/blob/4c4fef0f4510c1b5d4c6f3db30e39826813b7e13/administrator/components/com_banners/src/View/Banner/HtmlView.php#L103
If I check [blame](https://github.com/joomla/joomla-cms/blame/4.0-dev/administrator/components/com_banners/src/View/Banner/HtmlView.php#L103) I only see a very old PR "ACL Issues when user has edit (but not create) permission in…". I do not know how to open this PR.

### Open questions
Why do we use the  ID of the category for checking permissions in toolbar of an item 
and
is there a way to open old PRs?

**Comment by wojsmol** [comment]
AFor old PRs part please see https://developer.joomla.org/joomlacode-archive/

**Comment by astridx** [comment]
Thank you @wojsmol 
But I can not find an entry "ACL Issues when user has edit (but not create) permission in…" in joomlacode-archive. What is my mistake?
I can see the changed files here: https://github.com/joomla/joomla-cms/commit/467c3dccf492ac1f6faf3e5a3e92a67d906db681 
But I can not see the conversation. If I click on the issue link an other PR is opend - a newer one with the same number #27766.

**Comment by bembelimen** [comment]
To understand your question: which check would you expect?

I assume, the permission will follow the default behaviour: component => category => item and as the item has no ACL, it sticks to the category.

**Comment by chmst** [comment]
I only can see that the banners themselves i.e. the table #__banners has no field asset_id. So if someone may edit a category it is assumed that he can edit also the banners.
Maybe that this code was written before Joomla was on github.

**Comment by brianteeman** [comment]
https://developer.joomla.org/joomlacode-archive/issue-27766.html

**Comment by Bakual** [comment]
The reason is exactly as @chmst wrote. Since there is no asset tracking on item level (which is the case for eg banners), the next best thing is checking the assigned category.
I use the same behavior in my extension for the same reason.

**Comment by chmst** [comment]
@astridx is still an issue?

**Comment by astridx** [comment]
I think I understood it now. There is no special reason why there is no asset tracking in com_contact and com_banners at item level. It's just not implemented. Correct?

**Comment by Bakual** [comment]
Most likely one didn't see any advantage for item permissions at the time. As long as you don't need to allow edits for a single banner (or contact) only, it is sufficient to track it on category level.
