### ISSUE TITLE
Smart search - Advanced filter 'categories' not language related?

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#31496]
### Is your feature request related to a problem? Please describe.

We have a multilingual website (fr/en) that uses article categories that have EN, FR or both set as 'language' in the category options, When we index the articles in the smart search the categories are indexed but the index does not store any information about the categories language setting believe. So when use the advance filters on the smart search component all categories (EN/FR or both) are shown in the category filter, I would expect only to see the categories that match the selected language by the user...

We have created a workaround by adding EN/FR filters to the search menu items. We checked only the categories that should be shown for EN of FR users. This works, but the downside is that when we re-index the Smart search the filters are 'reset' and we need to remember to select the categories again in the filters.

### Describe the solution you'd like
It would be nice if the index could store info about the language the article categories are attached to so the advanced filter only shows categories that match the users language choice.

**Comment by Hackwar** [comment]
I guess you are talking about Joomla 3.9. We wont be changing this for 3.x anymore, but please have a look at Joomla 4.0, where quite a lot of work has been put into Smart Search. I'm not saying that the multi language part is perfect yet, but it should be a lot better than what is in 3.x.

**Comment by jjnxpct** [comment]
OK, thanks. We'll just work with the filters for now until we upgrade the website to J4.
