### ISSUE TITLE
[4.0] Review Joomla Update Compatibility

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#31490]
Merging https://github.com/joomla/joomla-cms/pull/29524 had tonnes of conflicts with current J4. For now I've dropped the new code in but it's going to need:

- [x] Removal of jquery'ing
- [x] Migration of classes from bootstrap 2 to bootstrap 4
- [ ] Review if there needs to be any further cleanup that we've done in J4 extensions

**Comment by brianteeman** [comment]
I cleaned up the codestyle in #31493 so it is at least easy to read for anyone working on the above

**Comment by brianteeman** [comment]
oh - boy - this needs a complete rewrite

**Comment by wilsonge** [comment]
Javascript needs a lot of work for sure. Anything specific from your side that gave that reaction?

**Comment by wilsonge** [comment]
Done some more cleanup. At least some of the stuff is beginning to functionally work again.

**Comment by joomdonation** [comment]
Made PR https://github.com/joomla/joomla-cms/pull/32602 to remove jQuery dependency for pre-update check. Do we want to remove jQuery from https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/com_joomlaupdate/js/update.es5.js , too ?

**Comment by wilsonge** [comment]
Ideally yes but don't think that's a release blocker level. Just need to make sure everything works and is styled properly for the preupdate checker. Then can downgrade the rest to a regular issue

**Comment by wilsonge** [comment]
OK Functionally things seem to work again. I'm leaving the issue open because it probably still needs further code review. But I'm removing the release blocker tag

**Comment by brianteeman** [comment]
and what about the FTP stuff?
Thats part of the update component and there has been nothing proposed for that at all

**Comment by wilsonge** [comment]
What's broken with the FTP stuff? As far as I'm concerned nothing should have changed there between J3.x and 4.x?

**Comment by brianteeman** [comment]
> What's broken with the FTP stuff? As far as I'm concerned nothing should have changed there between J3.x and 4.x?

For a start if you select FTP then you dont get prompted for the ftp username and password

**Comment by joomdonation** [comment]
> For a start if you select FTP then you dont get prompted for the ftp username and password

PR https://github.com/joomla/joomla-cms/pull/32799 should fix that issue.

**Comment by dgrammatiko** [comment]
please close
