### ISSUE TITLE
[4.0] Should com_media include svg as a legal extension by default?

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#31498]
### Steps to reproduce the issue

Look in administrator/components/com_media/config.xml
The upload extensions field does not include svg among the defaults although it can be added in Media Options

Is there some good reason for that? Or could it be included by default.

**Comment by brianteeman** [comment]
Search this issue tracker and you will find the good reason

**Comment by ceford** [comment]
I did some searching before asking - but clearly no enough. It seems the answer is that it is a security issue. I was thinking of adding something to the help screen to explain how to add svg images and what the security implications are. I still don't have a clear picture of the last. More to look up.
