### ISSUE TITLE
Joomla frontend editing missing option Flat view

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#31491]
Problem
Joomla frontend editing missing option Flat view

joomla frontend editing missing option to change from tab view to change to flat view?

Now we need to use 
![Untitled](https://user-images.githubusercontent.com/75063159/100323180-03e46400-2fce-11eb-8b35-49a462ad93d1.jpg)
 the different tabs to access editor, publishing, language, and metadata for the article

How can we get flat view, we dont want to use the different tabs, we want to see flat view and open

Solution
Joomla frontend editing option Flat view

Open questions

How to implenent Joomla frontend editing option Flat view or just to make quick fix to make it posible and see if it gives benefit to joomla community

**Comment by chmst** [comment]
You can make a template override of the edit view and remove the tabs.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31491">issues.joomla.org/tracker/joomla-cms/31491</a>.</sub>

**Comment by ghost** [comment]
@chmst could you provide code for template override of the edit view whick I can test on Joomla version, 3.9.23 Protostar template?
Whick file is responsible for edit view in joomla Protostar template?

**Comment by brianteeman** [comment]
There is an article in https://magazine.joomla.org by Sander Potjer about this

**Comment by ghost** [comment]
Brian I can't find article on this so could you provide code for template override of the edit view whick I can test on Joomla version, 3.9.23 Protostar template?
Whick file is responsible for edit view in joomla Protostar template?

**Comment by brianteeman** [comment]
https://magazine.joomla.org/all-issues/september-2014/creating-an-article-in-joomla-has-never-been-this-easy

For any further help please use the forum

**Comment by chmst** [comment]
Closing this as it is not a joomla issue. @HerBauer as your name seems to be german, you also can have a look here https://www.j-over.de/de/template-overrides.

**Comment by ghost** [comment]
In my opinion it is joomla issue and it should be open for discusion why joomla community don't have flat view in joomla?

**Comment by ghost** [comment]
@chmst as your name seems to be german, you also can write in german if you dont want to use english 

Whick file is responsible for edit view in joomla Protostar template? Couse its seems brian provided outdated information not relevant to joomla 3.9.23 Protostar template?

there is no file name or path in joomla 3.9.23 Protostar templat to find this file whick brian mentions in his links

**Comment by chmst** [comment]
In github everyone writes English (or kind of ... ;) )
The file is not in protostar as long as you don't make an override of the file components/com_content/views/form/tmp/edit.php in your template.

**Comment by ghost** [comment]
@chmst danke, so whick code removes the tabs in edit.php ?

**Comment by brianteeman** [comment]
This is not the place for this discussion

**Comment by ghost** [comment]
brian if you dont want to help joomla community please dont post in this issue



still no answer what code removes the tabs?

**Comment by brianteeman** [comment]
@HerBauer 400+ people receive emails on every issue comment - This is the place for the development of joomla not for customisation of individual sites
This issue was answered by the magazine article. As requested please use the forum for discussion

**Comment by ghost** [comment]
brian just unsubscribe from these comments, couse you are the only one who dont want to help joomla community on this issue

strange you false claim the issue is answered but still no answer what code removes the tabs?

everone who is new here in joomla development is greeted by angry brian? only brians issues are for development and other new users need to fork or just customize and dont share with joomla community'?

I thout this issue is for open discusion

sorry 400+ people , hope you not angry 

I feel very depressed now

**Comment by Bakual** [comment]
@HerBauer please stop the discussion here.
Brian is fully right, this isn't a discussion forum, it's a core issue tracker. And it was already said that it is not a core issue. And you even got pointed to the right solution for your issue (which also isn't the purpose of this issue tracker).
