### ISSUE TITLE
[4.0] Error in media field

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#31509]
### Steps to reproduce the issue
Try to add an image to a menuItem or to the offline page.

### Expected result
The image is selected and the image name is stored in the parameter images. 

### Actual result
The image is not stored as filename but with additional text.
Example: 
	public $offline_image = 'images/headers/maple.jpg?joomla_image_width=700&joomla_image_height=180';

and no image is shown in the frontend

**Comment by dgrammatiko** [comment]
@chmst please test #31511 That was my fault
