### ISSUE TITLE
J 3.9.23 breaks SMTP authentication

### ISSUE THREAD

**Issue by mravunko** [joomla/joomla-cms#31507]
### Steps to reproduce the issue
Upgrade to 3.9.23

### Expected result
SMTP function works correctly

### Actual result
Could not start mail function.

### System information (as much as possible)
Setting 	Value
 
PHP Built On 	Linux web2 4.19.0-12-amd64 #1 SMP Debian 4.19.152-1 (2020-10-18) x86_64
Database Type 	mysql
Database Version 	5.5.5-10.3.25-MariaDB-0+deb10u1
Database Collation 	utf8mb4_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.3.19-1~deb10u1
Web Server 	Apache/2.4.38 (Debian)
WebServer to PHP Interface 	fpm-fcgi
Joomla! Version 	Joomla! 3.9.22 Stable [ Amani ] 6-October-2020 15:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0 

### Additional comments

After update from Joomla! 3.9.22 Stable to 3.9.23 the SMTP auth stopped working. When sending test email with the following settings:
SMTP server smtp.sendgrid.net
SMTP port 25
TLS authentication

Direct downgrade to v. 3.9.22 fixed the problem.
I suppose that the new way displaying the password breaks the feature. 
We use the system email account with external mass email plugin to send newsletter. The plugin also stopped working.

**Comment by ghost** [comment]
duplicate #31482

**Comment by richard67** [comment]
Closing as duplicate, see #31482 . @gostn Thanks for finding the issue and reporting the duplicate.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31507">issues.joomla.org/tracker/joomla-cms/31507</a>.</sub>
