### ISSUE TITLE
[4.0] Cassiopeia manifest error causes Customise - Copy Template install error

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#31508]
### Steps to reproduce the issue

Go to System / Site Templates / Cassiopeia Details and Files
Select the Copy Template button in the Toolbar

### Expected result

I don't know - I was revising the Help screen and needed to find out.

### Actual result

An error message.

### Additional comments

![screen shot 2020-11-27 at 14 20 24](https://issues.joomla.org/uploads/1/fc333770582bbf92f9d2ba37703d16b0.png)

**Comment by ChristineWk** [comment]
Can't confirm. 
![screen shot 2020-11-27 at 15 14 47](https://issues.joomla.org/uploads/1/9d6d6cdb2965803510a59e9405dcd316.jpg)
![screen shot 2020-11-27 at 15 15 01](https://issues.joomla.org/uploads/1/130b8f11c0c683b49240a8e1e897c923.jpg)
**![screen shot 2020-11-27 at 15 16 14](https://issues.joomla.org/uploads/1/86fad22eb3d3634c9ea1522135e11a50.jpg)**
Did you check tmp folder?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31508">issues.joomla.org/tracker/joomla-cms/31508</a>.</sub>

**Comment by ceford** [comment]
Looked in the /tmp folder and the template is there - all the folders and files. But, I cut off my screen shot too soon - the missing file is favicon.ico and I have been messing about with that whilst testing the new svg icons. Looking into that...

**Comment by ceford** [comment]
In the github source, the template manifest lists favicon.ico with other template root files but the favicon.ico file is not present - it is in the images folder. On my site, if I copy it from there to the template root the Copy Template works. So I think this is a bug - either the manifest file is wrong or the missing favicon.ico is wrong.

**Comment by dgrammatiko** [comment]
@ceford please test https://github.com/joomla/joomla-cms/pull/31512
