### ISSUE TITLE
Emailed activation link goes to homepage instead of activating user

### ISSUE THREAD

**Issue by Dimik2020** [joomla/joomla-cms#31522]
### Steps to reproduce the issue
Register as a new user on Joomla! and have New User Account Activation set to Self. 

### Expected result
Receive an email from Joomla! to click on link to verify account. The link is supposed to take you to a page on the originating Joomla! site to activate the email address and give you a confirmation.

### Actual result
You go to the homepage and the user isn't activated. 

### System information (as much as possible)
Joomla 3.9.23
PHP 7.3
MySQL 5.7

**Comment by infograf768** [comment]
Can''t reproduce.
Have you set the parameters correctly?
<img width="515" alt="Screen Shot 2020-12-13 at 07 48 41" src="https://user-images.githubusercontent.com/869724/102005252-b2e7a600-3d17-11eb-8b71-45bd124089c0.png">
Is your admin receiving mail correctly?

**Comment by Quy** [comment]
@Dimik2020 Closing due to no response.
