### ISSUE TITLE
[4.0] Blog sample data issue for Persian when Multilingual sample data is installed before

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#31538]
### Steps to reproduce the issue

Install Persian language.
Install multilang sample data.
Then switch to Persian in admin and try to install Blog sample data.

It does not work
```
Uncaught TypeError: b.querySelector(...) is null

    sampledataAjax  http://localhost:8888/sample/joomla40/media/mod_sampledata/js/sampledata-process.min.js?6ad06aece6e4c0db10a477e15b85f220:1

    sampledataApply  http://localhost:8888/sample/joomla40/media/mod_sampledata/js/sampledata-process.min.js?6ad06aece6e4c0db10a477e15b85f220:1

    d  http://localhost:8888/sample/joomla40/media/mod_sampledata/js/sampledata-process.min.js?6ad06aece6e4c0db10a477e15b85f220:1

    d  http://localhost:8888/sample/joomla40/media/mod_sampledata/js/sampledata-process.min.js?6ad06aece6e4c0db10a477e15b85f220:1

    d  http://localhost:8888/sample/joomla40/media/mod_sampledata/js/sampledata-process.min.js?6ad06aece6e4c0db10a477e15b85f220:1

    EventListener.handleEvent*  http://localhost:8888/sample/joomla40/media/mod_sampledata/js/sampledata-process.min.js?6ad06aece6e4c0db10a477e15b85f220:1

    <anonymous>  http://localhost:8888/sample/joomla40/media/mod_sampledata/js/sampledata-process.min.js?6ad06aece6e4c0db10a477e15b85f220:1

sampledata-process.min.js:1:551

    sampledataAjax  http://localhost:8888/sample/joomla40/media/mod_sampledata/js/sampledata-process.min.js?6ad06aece6e4c0db10a477e15b85f220:1

    sampledataApply  http://localhost:8888/sample/joomla40/media/mod_sampledata/js/sampledata-process.min.js?6ad06aece6e4c0db10a477e15b85f220:1

    d  http://localhost:8888/sample/joomla40/media/mod_sampledata/js/sampledata-process.min.js?6ad06aece6e4c0db10a477e15b85f220:1

    (Async: EventListener.handleEvent)
    d  http://localhost:8888/sample/joomla40/media/mod_sampledata/js/sampledata-process.min.js?6ad06aece6e4c0db10a477e15b85f220:1

    forEach  self-hosted:206

    d  http://localhost:8888/sample/joomla40/media/mod_sampledata/js/sampledata-process.min.js?6ad06aece6e4c0db10a477e15b85f220:1

    (Async: EventListener.handleEvent)
    <anonymous>  http://localhost:8888/sample/joomla40/media/mod_sampledata/js/sampledata-process.min.js?6ad06aece6e4c0db10a477e15b85f220:1

    <anonymous>  http://localhost:8888/sample/joomla40/media/mod_sampledata/js/sampledata-process.min.js?6ad06aece6e4c0db10a477e15b85f220:1
```

NOTE: not installing multilang SD but installing Persian blog SD works.
Installing French/German blog does work after multilang is installed.

This was working a few weeks ago

**Comment by infograf768** [comment]
EDIT: After quitting FF and trying again, It succeeded.
Looks like we have a js cache issue. 
But why does it happen only with Persian here is the question.

@Fedik @dgrammatiko

**Comment by dgrammatiko** [comment]
> But why does it happen only with Persian here is the question.

Does the HTML part of the module change depending on the language (eg class,id alters depending the language)? Reason: the script fails to find elements that needs in order to function as expected (your 1st line of the error)

**Comment by Fedik** [comment]
Hard to say, maybe a browser cache from previous older installation.
Does it still happens, or all good?

**Comment by chmst** [comment]
I had this too but don't remember if it was related to multilingual. I just had to reload the screen, wait a second and repeat and all was fine. I thought it was caused by the debug modus which makes the loading of the site slow.  (win 10, FireFox)

**Comment by infograf768** [comment]
Will test again tomorrow. with a clean site and opening a new browser. 
What was weird was that I never got the problem with other languages than Persian and that I did not have the problem when installing directly the Persian blog SD (i.e. without installing first the multilingual SD.

**Comment by infograf768** [comment]
I can't reproduce this morning. Closing.
