### ISSUE TITLE
[J3.9.23] problems when trying to edit an article

### ISSUE THREAD

**Issue by hgh-esn** [joomla/joomla-cms#31543]
Hi there,
I hope anyone can help me.
I updated my Joomla site from J3.9.20 to the act. J3.9.23. and all runs well, but when editing an article I run into these issues. I activated site-tracing and get this output 

**In the backend:**

Selecting an article via the articles-listview to edit.
Call to a member function getTable() on bool

.../libraries/src/MVC/Controller/FormController.php:362
Call stack
#	Function	Location
1	()	JROOT/libraries/src/MVC/Controller/FormController.php:362
2	Joomla\CMS\MVC\Controller\FormController->edit()	JROOT/libraries/src/MVC/Controller/BaseController.php:710
3	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT/administrator/components/com_content/content.php:21
4	require_once()	JROOT/libraries/src/Component/ComponentHelper.php:402
5	Joomla\CMS\Component\ComponentHelper::executeComponent()	JROOT/libraries/src/Component/ComponentHelper.php:377
6	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/AdministratorApplication.php:101
7	Joomla\CMS\Application\AdministratorApplication->dispatch()	JROOT/libraries/src/Application/AdministratorApplication.php:159
8	Joomla\CMS\Application\AdministratorApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:196
9	Joomla\CMS\Application\CMSApplication->execute()
	JROOT/administrator/index.php:51

**In the frontend** 
... I get this issue:

0 - Class 'ContentModelArticle' not found

Tracing in frontend does not work well, because of very much statements to run thru.

Can anyone help me to fix this?

Greetings HGH

**Comment by toivo** [comment]
Also posted to the Forum as topic https://forum.joomla.org/viewtopic.php?f=706&t=983292
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31543">issues.joomla.org/tracker/joomla-cms/31543</a>.</sub>

**Comment by ghost** [comment]
close this cause its a double issue on forum too

**Comment by HLeithner** [comment]
@hgh-esn was this a update problem on your site? If I read the forum correctly you fixed it by adding the missing files. I'm closing this for now if the problem still exists please reopen the issue
