### ISSUE TITLE
[3x] and [4.0] RTL does not change names of sidebar-left and sidebar-right but does move physical position

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#31541]
### Steps to reproduce the issue
View (change if necessary) the site in RTL mode.

### Expected result
sidebar-left and sidebar-right (and their equivalents in J3) should stay on the left and right respectively.
Allocate a module to the sidebar-right position and it should display on the right and the reverse for sidebar-left position.

### Actual result
sidebar-left moves to the right and sidebar-right moves to the left.

### Additional comments
It may be for J3x that it's too late to change anything, but perhaps this could be addressed for J4.

**Comment by chmst** [comment]
It is intended and correct that the sidebars change their position. 
Maybe "sidebar-first" and "sidebar-second" following the direction of eye movement in the respective languages? 
@infograf768

**Comment by brianteeman** [comment]
In protostar the positions in the template are called position-7 and position-8. Only in the english language file are they given the left and right strings. This was done deliberately because of the language direction

In cassiopeia the positions are called sidebar-left and sidebar-right. This is incorrect if the value of the language moves them. Left is still Left in arabic. So yes sidebar-first or sidebar-primary is the correct direction neutral terminology

**Comment by chmst** [comment]
I would like to do this but it must be planned with other changes in the installation database, as were already mentioned in the cassiopeia repo.

**Comment by richard67** [comment]
We could name the module positions `sidebar-right-when-ltr-or-left-when-rtl` and `sidebar-left-when-ltr-or-right-when-rtl` ;-)

(forgive me my silly joke)

**Comment by Scrabble96** [comment]
> 
> 
> We could name the module positions `sidebar-right-when-ltr-or-left-when-rtl` and `sidebar-left-when-ltr-or-right-when-rtl` ;-)
> 
> (forgive me my silly joke)

Or maybe some code that reverses all sidebar-right to sidebar-left (and vice versa) when RTL is selected. But that would need the template's index.php and the templateDetails.xml to change as well.

**Comment by richard67** [comment]
No, we should do like Brian suggested and either use `sidebar-first`and `sidebar-last` or `sidebar-primary` and `sidebar-secondary`.

But the first will maybe make people ask "if there is a first and a last, is there also something in the middle", and the second will maybe not be clear enough. But I don't have a better idea.

**Comment by richard67** [comment]
For 4.0 see #31542 .

For 3.0 it would be a bc break, I think.

**Comment by brianteeman** [comment]
It is not needed in 3.x as explained above

**Comment by richard67** [comment]
Closing as having a pull request. Please test #31542 .
