### ISSUE TITLE
SMTP settings no longer working, PHP mail used instead as fallback

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#31546]
### Steps to reproduce the issue
We use SMTP settings (Global configuration - > Server ->Mail Settings) to e-mail CMS messages. This has been workin OK, but now (since last Joomla update??) when we send a test message we get a message like this: 
The email was sent to ************ but using PHP Mail as fallback. You should check that you've received the test email.

### Expected result
The email should be send using the SMTP settings and not fall back using PHP mail.

### Actual result
PHP mail is used.

### System information (as much as possible)
Joomla 3.9.26
PHP 7.4.11

### Additional comments
has the PHP mail fallback always been there? I have not noticed it before. I only remember a warning when the SMTP settings were not correct when sending a test mail from the backend.

**Comment by jjnxpct** [comment]
Ah, wait. I found a change in Joomla that causes this 'issue'. It seems because of a security fix you need to enter the password in the (greyed-out) password field before sending the test (don't save first). I guess having the password in the form is not secure and so the password is not actually used when sending the test. I have tired this an now SMTP is used OK. 

So to test SMTP: Save the SMTP settings, then fill out the password in the password field, (don';t save) send a test mail. This gives a message that the mail has been send using SMTP. And not the fallback message.

It might be good to inform the backend user about this somehow. May with some info below the test button? But because this is Joomla 3 probably no more changes will be made...

**Comment by ghost** [comment]
duplicate #31482
