### ISSUE TITLE
[3.9] Joomla\Image on php 8.0 not able to load the image

### ISSUE THREAD

**Issue by xillibit** [joomla/joomla-cms#31552]
### Steps to reproduce the issue

On Php 8.0 try to create the Image object with the class Joomla\Image like that :

`$file = "C:\Users\xillibit\git\joomla-cms-39/media/kunena/avatars/users/myimage.jpg" 
$image = new Image($file);`

The issue coming from this call in Image class line 679 : 

`$handle = imagecreatefromjpeg($path);`

On php 8.0 it doesn't returns a ressource but an [object](https://php.watch/versions/8.0/gdimage) : 

` object(GdImage)#876 (0) { } `

### Expected result

No exception like on Php 7.4.13

### Actual result

Exception : Unable to process JPG image. in C:\Users\xillibit\git\joomla-cms-39\libraries\vendor\joomla\image\src\Image.php on line 143

### System information (as much as possible)

Windows 10 20H2
Php 8.0.0 with gd, fileinfo and exif enabled
Joomla! 3.9.24-dev (sync from git)

**Comment by richard67** [comment]
Closing as having a pull request: #31554 .

**Comment by HLeithner** [comment]
Reopen this because the PR was wrong and reverted...

**Comment by HLeithner** [comment]
closed we have a new PR #31663
