### ISSUE TITLE
[4.0] Outdated classes after the last merge

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#31558]
### Steps to reproduce the issue

Cast a vote with the vote plugin.

### Expected result

No error message.

### Actual result

![screen shot 2020-12-02 at 16 12 47](https://issues.joomla.org/uploads/1/6cfa3ceda9bffd96c66984867fec66ff.png)

### System information (as much as possible)

Joomla! 4.0.0-beta6-dev Development [ Mañana ] 27-October-2020 19:54 GMT

### Additional comments

File: ..\components\com_content\src\Controller\ArticleController.php
Line 442:
```
// Don't redirect to an external URL.
if (!JUri::isInternal($url))
{
     $url = JRoute::_('index.php');
}
```

Please take a look: @wilsonge

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/e1d5dd29785b4af3f41fa1e0f5e495d89e71056f - Thanks for the report!
