### ISSUE TITLE
[4.0] Fix query to use prepared statements

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#31560]
https://github.com/joomla/joomla-cms/commit/51c50838ee9101191008c0e595e1ae975c52e45c#diff-664f22540552ccb73f1d9f0cb0942fdbc74ed99e6777ce3c9c43190825f482a9R350

Had a particularly complicated query that needs moving to a prepared statement. Hopefully one @alikon or @richard67 can look at?

**Comment by HLeithner** [comment]
Doesn't look like that it needs converted because all variables are cast to integer.

Edit: forget this part. the code is good as it is and comment can be removed
_-The order part looks like some escaping is missing, but the mention comment can be removed-_

**Comment by richard67** [comment]
Agree, I see not need to convert to prepared statements here.

**Comment by wilsonge** [comment]
I thought our aim/sales pitch for J4 was everything was using prepared statements? I mean I'm happy to close if you guys want though

**Comment by richard67** [comment]
It NEVER was MY aim that EVERYTHING uses prepared statements.
