### ISSUE TITLE
[4.0] Problem with user session

### ISSUE THREAD

**Issue by todordev** [joomla/joomla-cms#31562]
There is a problem with user session after upgrade.

### Steps to reproduce the issue
Upgrade to latest branch 4.0-dev.
Update composer packages.

### System information (as much as possible)
MariaDB 10.4.14
Apache/2.4.46 (Win64) 
PHP/7.4.13 

![Screenshot](https://user-images.githubusercontent.com/1272206/100971115-f6cff380-353e-11eb-8d20-a5948ce8e13a.png)

**Comment by HLeithner** [comment]
George merged #31561 by accident

**Comment by SharkyKZ** [comment]
PR https://github.com/joomla/joomla-cms/pull/31563.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #31563 .
