### ISSUE TITLE
[4.0] Media component upload default values

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#31568]
### Steps to reproduce the issue

Look at the code in administrator/components/com_media/config.xml:
upload_extensions contains a number of filetype extensions, including doc but not docx AND
upload_mime contains some values that are wrong or antiquated (excel, x-zip) and is missing a lot that go with the upload_extensions.

Also I can't find whether **Path to Files Folder** and **Path to Images Folder** actually do anything.

I would offer to fix it but it looks like a Work in Progress. And I would offer to write some documentation but that would just highlight the shortcomings. So thinking of a plugin + library override for my personal purposes.

**Comment by brianteeman** [comment]
Good luck with getting an answer. I tried last year and its still open and unanswered #23972

**Comment by brianteeman** [comment]
twice this week users had this problem. eg https://forum.joomla.org/viewtopic.php?f=811&t=990362&p=3646609#p3646609

**Comment by csbalazs** [comment]
I also got into this problem today. Maybe someone wants to fix it?

**Comment by Quy** [comment]
Related #37669
