### ISSUE TITLE
[4.0] Wrong icon for icon-play?

### ISSUE THREAD

**Issue by Harmageddon** [joomla/joomla-cms#31571]
### Steps to reproduce the issue
While updating a test site from J3 to J4, I noticed an odd icon. The class is `icon-play`, which should result in a play button triangle. But it resolves to expand arrows, similar to https://fontawesome.com/icons/expand-arrows-alt?style=solid.

To see the icon, navigate to `administrator/index.php?option=com_joomlaupdate&view=update&layout=finaliseconfirm`. You don't need to actually run the update, just look at the buttons below the login form.

### Expected result
A play icon, like in J3. For comparison:
![icon-play-j3](https://user-images.githubusercontent.com/1410135/101071376-d2a2ff80-359c-11eb-82c0-8c07d1cbc47d.png)

### Actual result

![icon-play-bug](https://user-images.githubusercontent.com/1410135/101070258-64aa0880-359b-11eb-8f53-d6cd159a4261.png)

### System information (as much as possible)
Mozilla Firefox, Joomla! `4.0-dev`

### Additional comments
It's not restricted to the update form, you can also just use something like `<span class="icon-play"></span>` somewhere on the site.

**Comment by brianteeman** [comment]
Please test #31574
