### ISSUE TITLE
[4.0]Search Engine Friendly URLs does not work - Joomla 4 Beta 5

### ISSUE THREAD

**Issue by necsoiu** [joomla/joomla-cms#31572]
### Steps to reproduce the issue
In joomla Admin interfece I have activated:
**Search Engine Friendly URLs
Use URL Rewriting**

### Expected result

The SEF URL should be as "/first-article"

### Actual result
The URL's still have the same format:

"/?view=article&id=2:first-article&catid=2"

### System information (as much as possible)
Installed fresh Joomla Beta 5 on:
Ubuntu 20.04
Apache2.4
PHP 7.4
PHP-FPM
mod_rewrite enabled
htaccess.txt renamed to .htaccess

### Additional comments

It seems that URL ReWriting is working as It removes index.php from the URL's

**Comment by Quy** [comment]
Duplicate #30368?

**Comment by bembelimen** [comment]
Where is the link? menu? article?

**Comment by toivo** [comment]
This works all right in Beta6-dev from https://developer.joomla.org/nightly-builds.html.
Did you set the option 'Remove IDs from URLs' in Content - Options - Integration - Routing?

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31572">issues.joomla.org/tracker/joomla-cms/31572</a>.</sub>

**Comment by toivo** [comment]
@Quy - #30368 is about Smart Search output. Smart Search in Beta6-dev presents the URLs of found articles in SEF format, for example:
http://joomla4/blog/your-template?highlight=WyJ0YWczIl0=
http://joomla4/blog/my-article?highlight=WyJ0YWczIl0=

The URL of the actual search results page is displayed as http://joomla4/component/finder/search?q=beetroot&Itemid=101&Itemid=103. 
Add a menu entry of the type 'Smart Search' - Search (The default Search layout) to a menu, which operation changes the URL of the search page to http://joomla4/search?q=beetroot which looks acceptable as a SEF URL.

This behaviour looks all right.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31572">issues.joomla.org/tracker/joomla-cms/31572</a>.</sub>

**Comment by HLeithner** [comment]
@necsoiu The behavior is expected because you don't have a category menu item nor a single article menu entry. In this case it uses the default menu item "featured" and adds the needed parameter (view, category and article id)

If it's not this behavior please reopen this issue.

**Comment by infograf768** [comment]
If the situation is as described by @HLeithner the solution is to always have, even if set to hidden, a "List All Categories" menu item.
