### ISSUE TITLE
[3.9.10][4.0][upgrade]Some post-installation messages not translated

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#31580]
### Steps to reproduce the issue
Install Joomla 3.9.10 Alpha4-dev.
Download Joomla 4.0 Beta6-dev.
Components - Joomla! Update - Upload & Update, choose file, click 'Upload & Install'

### Expected result
Post-installation messages are translated.

### Actual result
Post-installation messages are not translated:
![screen shot 2020-12-04 at 15 47 50](https://issues.joomla.org/uploads/1/1511dc3ea519b677c09494b137f66b05.png)

### System information (as much as possible)
Windows 10, Wampserver 3.2.4, Apache 2.4.43a, MySQL 8.0.20, PHP 7.4.13
Joomla 3.9.10 Alpha4-dev Full of 4 December, Joomla 4.0 Beta6-dev Update of 4 December

### Additional comments
These post-installation remain untranslated in the upgraded 4.0 site.

**Comment by Quy** [comment]
Duplicate  #26109

**Comment by toivo** [comment]
@Quy, @zero-24 - based on #26109, I must assume that those post-installation messages are going to be deleted in the upgrade.

**Comment by zero-24** [comment]
They should be i assume

**Comment by toivo** [comment]
Tested 3.10.0-alpha4-dev upgrade to 4.0.0-beta6-dev using Nightly Builds of 20 December with PHP 8.0.0.
This issue remains the same:  some post-installation messages are not translated and should be removed.
