### ISSUE TITLE
[3.9.10][4.0][upgrade]Upgrade shows message about extension table items to check-in

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#31582]
### Steps to reproduce the issue
Install Joomla 3.9.10 Alpha4-dev.
Download Joomla 4.0 Beta6-dev.
Components - Joomla! Update - Upload & Update, choose file, click 'Upload & Install'

### Expected result
Database tables are updated with no messages or at most with a message confirming that the tables have been updated.

### Actual result
Maintenance: Global Check-in displays a message about a large number of table items to be checked-in:
![screen shot 2020-12-04 at 16 02 58](https://issues.joomla.org/uploads/1/06308e0cec32e5a4c08c6843b37fac38.png)

### System information (as much as possible)
Windows 10, Wampserver 3.2.4, Apache 2.4.43a, MySQL 8.0.20, PHP 7.4.13
Joomla 3.9.10 Alpha4-dev Full of 4 December, Joomla 4.0 Beta6-dev Update of 4 December

### Additional comments
The website works, even without clicking System - Global Check-in, then selecting the message and pushing the button 'Check-in', which displays '216 items checked in'.  Ideally the rows in the extensions would be checked-in automatically.

**Comment by toivo** [comment]
Tested 3.10.0-alpha4-dev upgrade to 4.0.0-beta6-dev using Nightly Builds of 20 December with PHP 8.0.0.
This issue remains the same:  216 items in the extensions table remain to be checked in.

**Comment by Quy** [comment]
Duplicate #34362. Closing as the other has additional info. Thanks for the report.

**Comment by richard67** [comment]
Thanks @Quy for identifying the duplicate. I should have searched for "upgrade" and not for "update" only, then I would have found it.

**Comment by richard67** [comment]
@toivo Please test #34433 . Thanks in advance.
