### ISSUE TITLE
[4.0] User experience issue with subfields

### ISSUE THREAD

**Issue by snehal0904** [joomla/joomla-cms#31588]
### Steps to reproduce the issue
1. Crete a new field for user/article
2. Choose the field type as Subfield
3. Add a note if the field's dropdown is empty

### Expected result
Note, to create fields.

### Actual result
Users![screen shot 2020-12-05 at 08 44 58](https://issues.joomla.org/uploads/1/76a47946f7d33823e14b1ac251c62ff1.png) will confuse if no other fields exist.

### Additional comments

![screen shot 2020-12-05 at 08 47 23](https://issues.joomla.org/uploads/1/36436abbca9d0051197e942675ad144c.png)

**Comment by bembelimen** [comment]
Duplicate: https://github.com/joomla/joomla-cms/issues/31587
