### ISSUE TITLE
[3.9.10][4.0][upgrade]After upgrade to 4.0 Options tabs are missing

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#31584]
### Steps to reproduce the issue
Install Joomla 3.9.10 Alpha4-dev.
Download Joomla 4.0 Beta6-dev.
Apply PR #31575 to the upload package.
Components - Joomla! Update - Upload & Update, choose file, click 'Upload & Install'

### Expected result
Content - Articles - Options displays all tabs.
Menus - All Menu Items - Options displays all tabs.

### Actual result
Content - Articles - Options does not display any tabs.
Menus - All Menu Items - Options does not display any tabs.
![screen shot 2020-12-04 at 16 52 21](https://issues.joomla.org/uploads/1/bbff2a3baddf889b86c42cccd17d9ed0.png)

### System information (as much as possible)
Windows 10, Wampserver 3.2.4, Apache 2.4.43a, MySQL 8.0.20, PHP 7.4.13
Joomla 3.9.10 Alpha4-dev Full of 4 December, Joomla 4.0 Beta6-dev Update of 4 December (PR#31575 applied)

### Additional comments
All the tabs are displayed after logout and login back to the back end.  Even though this happens, the first login session after the upgrade should display all the Options tabs or give a clear message for the admin user to logout and login to have full access.

**Comment by brianteeman** [comment]
sounds like a cache problem

**Comment by HLeithner** [comment]
Since this is the first time (with my pr) you use the 3.10 session and not a new 4.0 maybe some parameters are wrong or missing.

**Comment by toivo** [comment]
@brianteeman - cleared cache both in Joomla and Chrome, no difference
@HLeithner - sounds like that may explain the behaviour, maybe a new forced login would give better UX for the upgrade <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31584">issues.joomla.org/tracker/joomla-cms/31584</a>.</sub>

**Comment by brianteeman** [comment]
@toivo Do you still have this problem?

**Comment by toivo** [comment]
@brianteeman I will test the upgrade from 3.9.10 and post the result asap.

**Comment by toivo** [comment]
This particular problem is gone.  Tested 3.10.0-alpha4-dev upgrade to 4.0.0-beta6-dev and both Menu and Content options showed the normal tabs.

The other issues are still there: 
#31583 - System - Setup - Global Configuration displays only the Site tab 
#31582 - 216 items in _extensions remain to be checked in
#31580 - Some post-installation messages are not translated

**Comment by brianteeman** [comment]
Please close this issue then and update the other issues

**Comment by toivo** [comment]
@brianteeman ok, thanks
