### ISSUE TITLE
[4.0] Create fields category UI issue.

### ISSUE THREAD

**Issue by shinderohanoffical** [joomla/joomla-cms#31586]
### Steps to reproduce the issue
1: Go to Content->Fields

2: Create new Field.

3: Category field is going outside the frame.

### Expected result
1: Category field should inside the frame like other fields.

### Actual result

1: Category field is going outside the frame.

### Additional comments

![screen shot 2020-12-05 at 07 23 28](https://issues.joomla.org/uploads/1/1114912ca38df9093857af1323ce6ac4.png)

**Comment by ghost** [comment]
6th duplicate report #27907

**Comment by brianteeman** [comment]
@gostn all the more reason to fix it

**Comment by ghost** [comment]
true cause it takes every time longer to search for #27907 :-)

**Comment by kk9** [comment]
Tested on PHP 7.3.21<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31586">issues.joomla.org/tracker/joomla-cms/31586</a>.</sub>

**Comment by drmenzelit** [comment]
Already reported in #27907
