### ISSUE TITLE
[4.0] User experience issue with subfields

### ISSUE THREAD

**Issue by snehal0904** [joomla/joomla-cms#31587]
### Steps to reproduce the issue
1. Crete a new field for user/article
2. Choose the field type as Subfield
3. Add a note if the field's dropdown is empty

### Expected result
Note, to create fields.

### Actual result
Users![screen shot 2020-12-05 at 08 44 58](https://issues.joomla.org/uploads/1/76a47946f7d33823e14b1ac251c62ff1.png) will confuse if no other fields exist.

**Comment by adj9** [comment]
In the backend I have this screenshot:
![Schermata 2020-12-05 alle 12 44 55](https://user-images.githubusercontent.com/5918444/101241611-e4e58080-36f7-11eb-871e-951d55bf898a.png)


The repetable field is missing and I have today's Nightly Builds.

Did you lean on a PR?

**Comment by snehal0904** [comment]
@adj9 In the screenshot, it seems you have selected type as "Text". Create a field with type Subfields

**Comment by adj9** [comment]
Its OK, true!

**Comment by Quy** [comment]
Related #28389

**Comment by brianteeman** [comment]
Is this still an issue as there have been quite a lot of changes to the subfield in the last few months?

**Comment by joomdonation** [comment]
Thanks @brianteeman. This should not be an issue anymore because if there are no fields like in this issue, the system will show a warning message to tell users that they need to create some standard fields first before creating Subform field.

Closing this issue for now.
