### ISSUE TITLE
[Backend]  Dash is added in status dropdown while creating a Article.

### ISSUE THREAD

**Issue by MeghaBiranje** [joomla/joomla-cms#31593]
### Steps to reproduce the issue
1. Goto backend and create a new article.
2. In the status dropdown dash "---" is displayed.
![screen shot 2020-12-05 at 12 31 20](https://issues.joomla.org/uploads/1/057c2aa62c4f0f0101fd2f3aa5f0d3b5.png)

**Comment by HLeithner** [comment]
Which version do you use?

**Comment by brianteeman** [comment]
This is intentional

**Comment by bembelimen** [comment]
Not really, it looks like the workflow is not active there, so the dropdown is wrong. If workflow is on:
![grafik](https://user-images.githubusercontent.com/1229869/101244498-2fbac480-3707-11eb-9a63-3d9c892ae06c.png)

If workflow is disabled:

![grafik](https://user-images.githubusercontent.com/1229869/101244506-3a755980-3707-11eb-971a-414104eeaa88.png)

But it looks like a really old version.

**Comment by MeghaBiranje** [comment]
I am using Joomla version-  4.0.0-beta1-dev

**Comment by bembelimen** [comment]
https://developer.joomla.org/nightly-builds.html here is the latest version to test.

**Comment by HLeithner** [comment]
@MeghaBiranje please use latest beta (5) or better use nightlies as @bembelimen mentioned
