### ISSUE TITLE
[Backend]  Dash is present in dropdown list of status while publish or unpublish the article from list view

### ISSUE THREAD

**Issue by MeghaBiranje** [joomla/joomla-cms#31595]
### Steps to reproduce the issue
1. Goto backend in the article list view
2. While publishing or unpublishing the article from the list view.

![screen shot 2020-12-05 at 13 29 39](https://issues.joomla.org/uploads/1/cbc55bfd781883a2660f686e97a258b3.png)

**Comment by brianteeman** [comment]
Yes this is intentional
