### ISSUE TITLE
[4.0] Category form - display user Id instead of name in created by field 

### ISSUE THREAD

**Issue by snehal0904** [joomla/joomla-cms#31592]
### Steps to reproduce the issue
1. Edit category -> go to publishing tab
2. Created by field display user Id instead of username

### Expected result
Display name of user instead of ID

### Actual result
Displaying User Id ![screen shot 2020-12-05 at 12 11 37](https://issues.joomla.org/uploads/1/7916e34fc20c8fbb374fe156b206430a.png)

**Comment by ghost** [comment]
you get this using https://launch.joomla.org/ as provider don't wanna change this ´cause its a beta´. its on all default ´uncategorised´-categories (not only for articles).

**Comment by brianteeman** [comment]
This is not a joomla bug.

**Comment by chmst** [comment]
Thank you for testing, @snehal0904 ! You are very attentive and it is great to meet you. But this times it is not a bug in Joomla and so I close this issue.
