### ISSUE TITLE
[Backend]  In media design margin issue.

### ISSUE THREAD

**Issue by MeghaBiranje** [joomla/joomla-cms#31594]
### Steps to reproduce the issue
1. Goto backend in media create a folder with a longer name.
2. click on a parent folder and see the margin design.
![screen shot 2020-12-05 at 12 52 12](https://issues.joomla.org/uploads/1/8a5228492014acebffab9edae8a3611c.png)

**Comment by brianteeman** [comment]
Duplicate report #30959
