### ISSUE TITLE
[4.0] Blog Sampledata Text

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#31596]
### Steps to reproduce the issue
The following string seems to be not correctly worded:
https://github.com/joomla/joomla-cms/blob/eb29c453d6ad87c13c71182a5cbfbf830b6abbd8/administrator/language/en-GB/plg_sampledata_blog.ini#L31

A translator raised the following question:

"selecting the Working on Your Site, Template Settings link in the top menu (visible when you login"
I do see this in the right menu, not in the top menu, and "Template settings" is not part of "Working on your site", or will this change?

### Additional comments
Anyone can shed some light on this? Or is the text historically wrong due to various changes in the template?

**Comment by Bakual** [comment]
Same for https://github.com/joomla/joomla-cms/blob/eb29c453d6ad87c13c71182a5cbfbf830b6abbd8/administrator/language/en-GB/plg_sampledata_blog.ini#L24

"There is a link to your site administrator in the top menu"
In the right menu

**Comment by chmst** [comment]
Thank you,  this has been forgotten during changes for the newer version.

**Comment by Bakual** [comment]
@chmst Will you do a PR for changing it?

**Comment by infograf768** [comment]
I am also wondering if it should be specified in their description that both sample data are specific to the default Cassiopea template.

**Comment by brianteeman** [comment]
... and that it uses workflows

**Comment by Bakual** [comment]
Closing as we have a PR
