### ISSUE TITLE
PHP 8 - Trying to access array offset on value of type bool

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#31598]
### Steps to reproduce the issue
/administrator/index.php?option=com_installer&view=update
Try to update an "old" extension that will result in "Error updating COM_INSTALLER_TYPE_TYPE_."

### Expected result
No PHP Warning

### Actual result
[Sun Dec 06 11:42:14.535136 2020] [php:warn] [pid 10524:tid 1808] [client ::1:58021] PHP Warning:  Trying to access array offset on value of type bool in C:\\xampp3\\htdocs\\test-php8\\administrator\\components\\com_installer\\models\\update.php on line 451, referer: http://localhost/test-php8/administrator/index.php?option=com_installer&view=update
[Sun Dec 06 11:42:14.535136 2020] [php:warn] [pid 10524:tid 1808] [client ::1:58021] PHP Warning:  Trying to access array offset on value of type bool in C:\\xampp3\\htdocs\\test-php8\\administrator\\components\\com_installer\\models\\update.php on line 454, referer: http://localhost/test-php8/administrator/index.php?option=com_installer&view=update
[Sun Dec 06 11:42:14.535136 2020] [php:warn] [pid 10524:tid 1808] [client ::1:58021] PHP Warning:  Trying to access array offset on value of type bool in C:\\xampp3\\htdocs\\test-php8\\administrator\\components\\com_installer\\models\\update.php on line 464, referer: http://localhost/test-php8/administrator/index.php?option=com_installer&view=update
[Sun Dec 06 11:42:14.535136 2020] [php:warn] [pid 10524:tid 1808] [client ::1:58021] PHP Warning:  Trying to access array offset on value of type bool in C:\\xampp3\\htdocs\\test-php8\\administrator\\components\\com_installer\\models\\update.php on line 469, referer: http://localhost/test-php8/administrator/index.php?option=com_installer&view=update
[Sun Dec 06 11:42:14.535136 2020] [php:warn] [pid 10524:tid 1808] [client ::1:58021] PHP Warning:  Trying to access array offset on value of type bool in C:\\xampp3\\htdocs\\test-php8\\administrator\\components\\com_installer\\models\\update.php on line 486, referer: http://localhost/test-php8/administrator/index.php?option=com_installer&view=update
[Sun Dec 06 11:42:14.535136 2020] [php:warn] [pid 10524:tid 1808] [client ::1:58021] PHP Warning:  Trying to access array offset on value of type bool in C:\\xampp3\\htdocs\\test-php8\\administrator\\components\\com_installer\\models\\update.php on line 495, referer: http://localhost/test-php8/administrator/index.php?option=com_installer&view=update
[Sun Dec 06 11:42:14.535136 2020] [php:warn] [pid 10524:tid 1808] [client ::1:58021] PHP Warning:  Trying to access array offset on value of type bool in C:\\xampp3\\htdocs\\test-php8\\administrator\\components\\com_installer\\models\\update.php on line 498, referer: http://localhost/test-php8/administrator/index.php?option=com_installer&view=update
[Sun Dec 06 11:42:14.535136 2020] [php:warn] [pid 10524:tid 1808] [client ::1:58021] PHP Warning:  Undefined array key "extractdir" in C:\\xampp3\\htdocs\\test-php8\\administrator\\components\\com_installer\\models\\update.php on line 501, referer: http://localhost/test-php8/administrator/index.php?option=com_installer&view=update

### System information (as much as possible)
xampp-windows-x64-8.0.0-0-VS16-installer.exe
Windows 10
PHP 8.0.0
Joomla 3.9.23

**Comment by jsubri** [comment]
Not only PHP8, I've the warnings on PHP 7.4 too

**Comment by HLeithner** [comment]
Hi @jsubri

could you please edit line 448 with `var_dump($package)` because it looks like th extraction of the package fails and we don't check if the unpacking was successful.

Can you upload the extension package you want to install?

thx

**Comment by jsubri** [comment]
bool(false)  
[pkg_maximenuckparams_4.1.1.zip](https://github.com/joomla/joomla-cms/files/5655213/pkg_maximenuckparams_4.1.1.zip)

**Comment by infograf768** [comment]
php 7.3.9
with J3 I do get a possible update and then get `Error updating COM_INSTALLER_TYPE_TYPE_`
in J4 with php 7.39 no update shows in the manager,

**Comment by HLeithner** [comment]
@jsubri can you try this with the latest nightly ? maybe the extension installation pr fixes this too.

**Comment by jsubri** [comment]
@HLeithner , I've applied Joomla! 3.9.24-dev  with the nightly "Tuesday, 08 December 2020 03:00:08 UTC" 
Edited: same error on PHP not 7.3.4 but **7.4**

**Comment by N6REJ** [comment]
I've tested this everyway I can think of and can't replicate it.

**Comment by infograf768** [comment]
I confirm the warnings in the php error log on php 7.4.2 with J 3.9.24-dev

**Comment by infograf768** [comment]
Patch coming

**Comment by infograf768** [comment]
Closing as we have a patch
Please test https://github.com/joomla/joomla-cms/pull/31620
