### ISSUE TITLE
[4.0] Article preview display 404

### ISSUE THREAD

**Issue by snehal0904** [joomla/joomla-cms#31590]
### Steps to reproduce the issue
1. Create an article with a future publishing date and save.
2. Click on the preview button
3. popup display 404 page

### Expected result
- Future publish date article should display in the preview
- Currently, it looks like only the article detail view link is passed for the review

### Actual result
Geeting 404 for an article with future publishing date

**Comment by ghost** [comment]
duplicate report #24132
