### ISSUE TITLE
[Backend]  At filters while closing filters the dropdown arrow changes to up arrow.

### ISSUE THREAD

**Issue by MeghaBiranje** [joomla/joomla-cms#31591]
### Steps to reproduce the issue
1. Goto administrator and open any list view.
2. Click on Filter Option, the dropdown arrow needs to change up arrow.   
![screen shot 2020-12-05 at 12 08 30](https://issues.joomla.org/uploads/1/9b125e4de9ce2e42f874032bd96e1514.png)

### Expected result
After opening the filters the dropdown arrow needs to change to an up arrow.

**Comment by brianteeman** [comment]
While I understand you this would be non-standard behaviour. A select dropdown arrow doesn't change https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select

**Comment by drmenzelit** [comment]
As Brian stated, that is not an issue, select dropdown arrows don't change the orientation.
