### ISSUE TITLE
[4.0][php8] Can't install sample blog data

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#31603]
### Steps to reproduce the issue
install clean system using php8
attempt to install sample blog data.

### Expected result
Sample blog data installs

### Actual result
Throws hidden error ( even with max debug on ) after installing a single tag.
![image](https://user-images.githubusercontent.com/1850089/101289122-25103600-37c0-11eb-8732-d3a201cc7d5c.png)

### System information (as much as possible)

[systeminfo-2020-12-06T12_36_19-06_00.txt](https://github.com/joomla/joomla-cms/files/5649331/systeminfo-2020-12-06T12_36_19-06_00.txt)

**Comment by drmenzelit** [comment]
Related: #31564 , #31566

**Comment by chmst** [comment]
https://github.com/joomla/joomla-cms/issues/31564#issuecomment-739778137
