### ISSUE TITLE
[3.9][PHP 8]PHP warning in com_admin - Edit Account: Cannot access offset of type string on string

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#31610]
### Steps to reproduce the issue
Go to System - Control Panel.
Click Super User – Edit Account.
Go to any tab, for example User Profile and edit something, then click Save.
Or do not change anything and click Save.

### Expected result
No warnings or errors.

### Actual result
Message displayed: 0 Cannot access offset of type string on string
PHP error log:
[07-Dec-2020 12:10:42 UTC] PHP Warning:  Uninitialized string offset 0 in C:\www\joomlatest\administrator\components\com_admin\models\profile.php on line 145

### System information (as much as possible)
Windows 10, Wampserver 3.2.4
Apache 2.4.43a, MySQL 8.0.20, PHP 8.0.0

**Comment by N6REJ** [comment]
I cannot replicate the issue using php8 & staging.
@toivo any extensions installed or settings changed from default?
![image](https://user-images.githubusercontent.com/1850089/101360153-e67f8780-3862-11eb-95cc-e557f73647a6.png)

**Comment by toivo** [comment]
@N6REJ The earlier test site had a few extensions, but then I installed J3.9.23 from scratch, set up standard .htaccess and SEF, set error reporting to 'Maximum', went to Super User - Edit Account, clicked Save and got exactly the same PHP warning.

I will now download 3.9.24-dev and see what happens.  Should've done that in the first instance...

![screen shot 2020-12-07 at 15 03 10](https://issues.joomla.org/uploads/1/0ce68aaee8870e55454d8de5d49de562.jpg)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31610">issues.joomla.org/tracker/joomla-cms/31610</a>.</sub>

**Comment by toivo** [comment]
@N6REJ - ran the update using the 3.9.24-dev patch package and got the same PHP warning in Edit Account - Save.  I'll now install 3.9.24-dev from scratch and try again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31610">issues.joomla.org/tracker/joomla-cms/31610</a>.</sub>

**Comment by Fedik** [comment]
it something with twofactor
https://github.com/joomla/joomla-cms/blob/60183c4c5831e5e7df3aa59ad9fd72b3d6a93c94/administrator/components/com_admin/models/profile.php#L142-L150

I guess you need to have it enabled, or previously used, to get this issue

**Comment by toivo** [comment]
@Fedik @N6REJ - just confirmed that the issue occurs also in an out-of-the-box 3.9.24-dev, where the only change in the default configuration was the level of error reporting 'Maximum'.  

The only Super User was not updated before testing Edit Account.  The only enabled authentication plugins are Cookie and Joomla. Therefore it looks like the user data has incorrect default value.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31610">issues.joomla.org/tracker/joomla-cms/31610</a>.</sub>

**Comment by Fedik** [comment]
> Therefore it looks like the user data has incorrect default value.

yeah, looks like
It seems default should be 'none', but $data['twofactor'] is empty.
I have no idea where it comes from.

**Comment by N6REJ** [comment]
the field is hidden
```
	<!-- Used to get the two factor authentication configuration -->
	<field
		name="twofactor"
		type="hidden"
	/>
```

**Comment by N6REJ** [comment]
why am I not getting the error.. hmmmm

**Comment by Fedik** [comment]
> why am I not getting the error

It can be seen only in PHP logs (if it enabled)
The error happens on "save" action, and following redirect will reload the page, that why.

**Comment by Fedik** [comment]
btw, it not strict for php 8 version, but general mistake somewhere

**Comment by Fedik** [comment]
@zero-24 can you please have a look? it seems was your changes https://github.com/joomla/joomla-cms/commit/085f2042825b2aa73d46aa5fc2eb6869d078a28b

I not very know this part, I suspect it need to check `if (!empty($data['twofactor'])` or populate default value when it empty

**Comment by toivo** [comment]
@Fedik - the warning does not occur in PHP 7.4.13<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31610">issues.joomla.org/tracker/joomla-cms/31610</a>.</sub>

**Comment by zero-24** [comment]
> @zero-24 can you please have a look? it seems was your changes https://github.com/joomla/joomla-cms/commit/085f2042825b2aa73d46aa5fc2eb6869d078a28b
> 
> I not very know this part, I suspect it need to check `if (!empty($data['twofactor'])` or populate default value when it empty

Well its based on the pre existing code. So when there are new issues with PHP8 it dhould be fixed there too.

**Comment by toivo** [comment]
@zero-24 - isn't this a new issue with PHP8 or am I missing something?  Is it not possible to trace the origin of the incorrect default value and/or fix the code now?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31610">issues.joomla.org/tracker/joomla-cms/31610</a>.</sub>

**Comment by zero-24** [comment]
I have not checked the code myself i just wanted to mention that when there is an patch done here the other part should be taken care of too.

When we can find the root cause that would be even better for sure.

**Comment by toivo** [comment]
@zero-24 Ok, thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31610">issues.joomla.org/tracker/joomla-cms/31610</a>.</sub>

**Comment by Fedik** [comment]
@toivo do you have same issue on joomla 4? on j4 will be file UserModel.php (instead of profile.php) and line around 262

**Comment by toivo** [comment]
The Save button works all right in 'Edit Account' in J4 Beta6-dev of 8 December in PHP 8.0.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31610">issues.joomla.org/tracker/joomla-cms/31610</a>.</sub>

**Comment by bayareajenn** [comment]
Could not duplicate the problem in 3.9.23 and PHP 8.0.0. Error reporting is set to Dev. Changed username and Editor separate times. User saved just fine. No 0 error. Saved without making any change(s). User saved fine. No 0 error.

**Comment by alikon** [comment]
i've been able to replicate  see #31628  for a solution

**Comment by ghost** [comment]
@alikon close this issue as you made a pr?
