### ISSUE TITLE
[4.0] com_contact Can't hide "no contacts" message and "subcategories" title in category and categories list

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#31614]
### Steps to reproduce the issue
Create a category and some subcategories in components -> contacts
Create a menu item of type
Contacts » List Contacts in a Category and / or
Contacts » List All Contact Categories

### Expected result
You can hide the "no contacts" message and the "subcategories" title

### Actual result
You can't hide these things, because there are no parameters in com_contact to do so.

Contacts use the global category view and there it is already possible to hide the "subcategories" title. The Content component has the needed parameter to hide the "subcategories" title and also a parameter to hide the "no articles" message in blog layout for example.

![grafik](https://user-images.githubusercontent.com/9153168/101494212-524b1880-3967-11eb-8a08-d9568d148459.png)

### System information (as much as possible)
Joomla 4.0.0-beta6-d

### Additional comments
PR is on the way ;-)

**Comment by Quy** [comment]
PR #31615
