### ISSUE TITLE
banner problem joomla 4.0 beta 6 from 08-12-2020

### ISSUE THREAD

**Issue by citroen1968** [joomla/joomla-cms#31623]
### Steps to reproduce the issue
install banner and module  then in front end there is no banner images

### Expected result
Change to image and the banner container is there but there is no image tag

**Comment by chmst** [comment]
~~Please test #31624~~

**Comment by chmst** [comment]
Please test #31624

**Comment by chmst** [comment]
Closed as there is a PR
