### ISSUE TITLE
[4.0][PHP 8]Joomla! Update - Upload & Update fails at 90%

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#31634]
### Steps to reproduce the issue
Install J4 Beta6-dev Full version of 11 December from Nightly Builds.
Download J4 Beta6-dev Update of 11 December from Nightly Builds.
Go to System - Global Configuration – Server and set Error Reporting to ‘Maximum’.
Select 'Yes' in Logging - Log Almost Everything.
Run System – Update – Joomla – Upload & Update

### Expected result
Joomla! Update is completed.

### Actual result
Joomla! Update reports an error at 90%
ERROR: Invalid AJAX data
**Fatal error**: Uncaught ValueError: Path cannot be empty in C:\www\joomla4\administrator\com_joomlaupdate\restore.php:874
Stack trace attached.

### System information (as much as possible)
Windows 10, Wampserver 3.2.4
Apache 2.4.46a, MySQL 8.0.22, PHP 8.0.0

### Additional comments
The same update works all right in PHP 7.4.13.
**Stack Trace**
![screen shot 2020-12-11 at 09 32 54](https://issues.joomla.org/uploads/1/4fc309b427d57e34130cad373e453ae3.png)
![screen shot 2020-12-11 at 09 33 14](https://issues.joomla.org/uploads/1/e7abd797d23bd1df2f0c707c729429ea.png)
![screen shot 2020-12-11 at 09 33 39](https://issues.joomla.org/uploads/1/3c98ed7fc3d28d91640962db9a647d7b.png)
![screen shot 2020-12-11 at 09 34 16](https://issues.joomla.org/uploads/1/05382c8b86e7bf389fe7f067f75acd89.png)

**Comment by alikon** [comment]
probably solved in 3.x with #31442 but didn't check yet

**Comment by toivo** [comment]
@alikon Just tested Upload & Update in 3.9.24-dev using PHP 8.0.0 and the update finished all right.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31634">issues.joomla.org/tracker/joomla-cms/31634</a>.</sub>

**Comment by ghost** [comment]
@toivo looks like issue can be closed.

**Comment by toivo** [comment]
@gostn what makes you think it can be closed? 3.9.24-dev is not Beta6-dev, where is the PR that fixes this issue in J4?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31634">issues.joomla.org/tracker/joomla-cms/31634</a>.</sub>

**Comment by ghost** [comment]
> probably solved in 3.x with #31442 but didn't check yet
> @alikon Just tested Upload & Update in 3.9.24-dev using PHP 8.0.0 and the update finished all right.

thats made me think but overlooked the issue is about j4.

**Comment by wilsonge** [comment]
Can you try testing again since I've merged all the staging code into 4.x

**Comment by toivo** [comment]
@wilsonge   Thanks, now the update using the Upload & Update tab finished all right with today's Beta6-dev update.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31634">issues.joomla.org/tracker/joomla-cms/31634</a>.</sub>

**Comment by wilsonge** [comment]
Awesome - thanks! I'm going to close this then. We can open a fresh issue in the future because we'll be sure we have the code from staging so it would be an unrelated issue
