### ISSUE TITLE
[4.0] Duplicate Main Menu

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31642]
![image](https://user-images.githubusercontent.com/1296369/101993543-6a969c80-3cb3-11eb-8356-c619095ea772.png)

After installing the sample data you have two menus with the same description

**Comment by chmst** [comment]
resolved here https://github.com/joomla/joomla-cms/pull/31604/commits/7a11d19d7db39c84d349c853a36309e9549a71c9

**Comment by brianteeman** [comment]
thanks @chmst
