### ISSUE TITLE
[com_fields] Can't edit own field in backend when 'edit.own' is set for user group

### ISSUE THREAD

**Issue by PeterTHM** [joomla/joomla-cms#31649]
### Steps to reproduce the issue

1. In backend go to: System->Global Configuration->Articles->Permissions
2. Set the acl permissions for a user group with backend access to :
  Create->Allowed
  Edit->Denied
  Edit Own->Allowed
  Edit Custom Field Value->Allowed
3. Create a field group as Super User
4. Create a field within this group as Super User
5. Login as user of the resticted group
6. Create a field within the previously created article field group
7. Return to article fields list view

### Expected result

1. The field created by the super user should not beeing editable for the restricted user.
2. The field created by the restricted user should be **editable for both**.

### Actual result

1. Works
2. The field created by the restricted user is displayed as **selectable for it's creator** but when the user
  clicks on it, he will get a permission denied error.

![image](https://user-images.githubusercontent.com/6030715/102082936-17d3f680-3e13-11eb-8123-3a0976dc7338.png)

### System information (as much as possible)
Joomla 3.9.23

### Additional comments
Maybe thats just a naming mistake:

The field controller in com_fields administrator section trys to get the user id of the fields creator by the field records 'created_by' attribute, which is not present in the db. Instead the db field holding the creator id is **'created_user_id'**.

https://github.com/joomla/joomla-cms/blob/f60e03ff2d7e8a7810b6604aad441925451d4f3d/administrator/components/com_fields/controllers/field.php#L102

**Comment by ghost** [comment]
Confirmed the issue, test on Joomla4 - nightly build:

> ![grafik](https://user-images.githubusercontent.com/78906980/114705218-c8052d80-9d27-11eb-834e-c81ec0f33ef0.png)

**Comment by joomdonation** [comment]
Thanks @PeterTHM for the propose code. Thanks @sandramay0905  for checking and confirming the issue. I made PR https://github.com/joomla/joomla-cms/pull/33129 to solve the issue. Please test.
