### ISSUE TITLE
[4.0] Deprecated:  Function zip_*

### ISSUE THREAD

**Issue by frostmakk** [joomla/joomla-cms#31648]
### Steps to reproduce the issue
Install extension.

### Actual result
Lots of Deprecated messages in error log regarding zip functions.

### System information (as much as possible)
4.0.0-beta6-dev Nightly build, PHP 8.0

### Additional comments
Maybe do a #31246 in the 4.0 library as well?

**Comment by Quy** [comment]
Related #31300

**Comment by Bakual** [comment]
@frostmakk Just for your information: All PRs merged into `staging` end up in `4.0-dev` as well. It just takes some time till they are merged up.

**Comment by wilsonge** [comment]
Everything should now be up to date
