### ISSUE TITLE
(J4 beta 6 dev) Image format change with the new Cassiopeia template.

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#31647]
I am currently testing the night version J4 beta 6 dev on 12/13/2020. After importing an image into the media manager and changing the image to 16: 9 format. I notice that this image is defocused in square format in front.

![Capture d’écran 2020-12-13 à 17 29 12](https://user-images.githubusercontent.com/26197929/102017701-c40cd300-3d68-11eb-8503-c8594d074d72.png)

**Comment by infograf768** [comment]
Can't reproduce here.

**Comment by drmenzelit** [comment]
I can confirm the issue
![grafik](https://user-images.githubusercontent.com/9153168/102220524-3c969f80-3ee1-11eb-8703-d1d51dfb08f6.png)
The problem is that the image has height and width set, the template define img as max-width: 100% but the height: auto is missing.

**Comment by drmenzelit** [comment]
Please check PR #31667
