### ISSUE TITLE
[4.0] Instructions in Joomla Docs for  template:edit style don't work

### ISSUE THREAD

**Issue by citroen1968** [joomla/joomla-cms#31653]
### Steps to reproduce the issue
administrator => Templates: Styles (Site) => cassiopeia - Default=>button help,
https://help.joomla.org/proxy?keyref=Help40:Templates:_Edit_Style&lang=en
Atum Colour Settings,Atum Image Settings,

.header .logo.small {
       width: 3rem;
   }

### Expected result
cassiopeia Colour Settings, cassiopeia Image Settings.

.container-header .navbar-brand img {
    width: 3rem;}

### System information (as much as possible)

mamp 5.27, php version 7.4.2 beta 6 08-12-2020![screen shot 2020-12-14 at 18 47 41](https://issues.joomla.org/uploads/1/73a399a1c0fdd73278d7e54719bb1463.png)

**Comment by brianteeman** [comment]
The instructions you are showing are for the admin template Atum

**Comment by rdeutz** [comment]
closing this because wrong documentation used
