### ISSUE TITLE
[4.0][PHP 8] Backport to framework

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#31664]
https://github.com/joomla/joomla-cms/pull/31168 needs backporting to the framework libraries. This tracks that as a release blocker

**Comment by nibra** [comment]
Done.
* https://github.com/joomla-framework/database/pull/220
* https://github.com/joomla-framework/facebook-api/pull/7
* https://github.com/joomla-framework/session/pull/47

The other packages were already fixed.

**Comment by wilsonge** [comment]
Awesome - thanks!
