### ISSUE TITLE
[4.0] Sample data search

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31678]
I think it would be a good idea to have a hidden menu item for search in the sample data plugin. This will showcase
- hidden menu items (people still recommend hidden menus)
- how to control which modules appear on the search page
- SEF urls for search instead of /component/search

Not got my head around the plugin yet or I would have done a PR

**Comment by chmst** [comment]
Not sure if I can add or remove modules in search, it is not as easy especially if multilingual is used. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31678">issues.joomla.org/tracker/joomla-cms/31678</a>.</sub>
