### ISSUE TITLE
[4.0] Saving in Global Configuration results in invalid File

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#31679]
The security fixes around Global Configuration has caused password fields to save with an invalid value in configuration.php breaking the entire site.

Reproduction Steps:
- Install copy of J4
- Navigate to Global Config
- Click save
Instant 500 error. Check the values of the password fields in configuration.php and they're all invalid (aside from the db password) e.g.

`public $ftp_pass = ;`

You can reset them to all be an empty string to restore the site manually

**Comment by richard67** [comment]
Closing as having a pull request. Please test #31683 .
