### ISSUE TITLE
[4.0] Joomla update error - class JFactory not found

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#31682]
### Steps to reproduce the issue
Start with Beta6-dev of 16 December with Blog Sample Data. 
The only additional extension is Joomla! Patch Tester, but no patches are currently applied.
Download Joomla_4.0.0-beta6-dev-Development-Update_Package.zip from Nightly Builds.
Run update from System - Update - Joomla - Upload & Update

### Expected result
Joomla update is completed.

### Actual result
An error has occurred.
0 Class 'Joomla\Component\Joomlaupdate\Administrator\Controller\JFactory' not found

Call stack
#	Function	Location
1	()	JROOT\administrator\components\com_joomlaupdate\src\Controller\UpdateController.php:122
2	Joomla\Component\Joomlaupdate\Administrator\Controller\UpdateController->install()	JROOT\libraries\src\MVC\Controller\BaseController.php:729
3	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:146
4	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()	JROOT\libraries\src\Component\ComponentHelper.php:389
5	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT\libraries\src\Application\AdministratorApplication.php:142
6	Joomla\CMS\Application\AdministratorApplication->dispatch()	JROOT\libraries\src\Application\AdministratorApplication.php:185
7	Joomla\CMS\Application\AdministratorApplication->doExecute()	JROOT\libraries\src\Application\CMSApplication.php:266
8	Joomla\CMS\Application\CMSApplication->execute()	JROOT\administrator\includes\app.php:63
9	require_once()	JROOT\administrator\index.php:36

### System information (as much as possible)
Windows 10, Wampserver 3.2.4
Apache 2.4.46a, MySQL 8.0.22, PHP 8.0.0 or PHP 7.4.13

### Additional comments
Joomla update worked all right on 16 December.  Now the error occurs straight away. Otherwise the Beta6-dev test site is working normally.

**Comment by toivo** [comment]
Correction: the update was run in PHP 7.4.13, not in PHP 8.0.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31682">issues.joomla.org/tracker/joomla-cms/31682</a>.</sub>

**Comment by sandewt** [comment]
See [#31666] - Use Factory::, not JFactory<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31682">issues.joomla.org/tracker/joomla-cms/31682</a>.</sub>

**Comment by toivo** [comment]
@sandewt In any case, something had gone out of whack in the last day but it does not seem to be an issue, based on the subsequent test: 

Install Beta6-dev of 9 December from scratch.
System – Update – Joomla – Upload & Update
Select Joomla_4.0.0-beta6-dev-Development-Update_Package.zip of 17 December.
Joomla update is completed normally.
Run Upload & Update again, using Joomla_4.0.0-beta6-dev-Development-Update_Package.zip of 17 December.
Joomla update is completed normally.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31682">issues.joomla.org/tracker/joomla-cms/31682</a>.</sub>

**Comment by wilsonge** [comment]
This should have been fixed by https://github.com/joomla/joomla-cms/pull/31666  a couple of days ago
