### ISSUE TITLE
[4.0] Color Picker rendering / splitted over columns when last field in column

### ISSUE THREAD

**Issue by marcorensch** [joomla/joomla-cms#31695]
### Steps to reproduce the issue

Create a blank module
Add a new fieldset (to place the fields in a custom tab)
Add some fields
Add a field of type color that it is the last of the fieldset OR the last in a column AND is hidden on load (showon)

### Expected result

The color picker is rendered as always

### Actual result

In Chrome: the colorpicker is "splitted" over two columns
![screen shot 2020-12-17 at 21 12 45](https://issues.joomla.org/uploads/1/17355e2403dde515a1e27aa837146c00.png)

In Safari the colorpicker "kills" the next column -> fields from content 3 gets moved to column 2:
![screen shot 2020-12-17 at 21 25 14](https://issues.joomla.org/uploads/1/851f501ab53328b7e63dd004258e0cb7.png)
![screen shot 2020-12-17 at 21 25 29](https://issues.joomla.org/uploads/1/9e7ded1a5025946159ca5ced9e742f4c.png)

### System information (as much as possible)

Joomla 4 Beta 5
The color field has a showon attr and is hidden on load

Chrome: Colorpicker splits
Safari: When colorpicker is open the next field moves from column 3 to column 2 (may be needed to investigate with another issue because the columns rendering is different with safari (3 fields goes into three columns in chrome it places this 3 fields in 2 columns) then it is with chrome)...

### Additional comments
Any information how to control the columns behavior?
Did yet not find any docs about it.

**Comment by Quy** [comment]
Related #29955

**Comment by marcorensch** [comment]
Created #31696 for different rendering in Chrome & Safari<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31695">issues.joomla.org/tracker/joomla-cms/31695</a>.</sub>

**Comment by Quy** [comment]
Please test/confirm that this is no longer an issue in the nightly builds. Thanks.

https://developer.joomla.org/nightly-builds.html

**Comment by Quy** [comment]
See PR #32422
