### ISSUE TITLE
[4.0] sample data

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31690]
After installing the sample data I am seeing a few issues

1. The typography link in the custom module is non-sef (I think this may be because it is missing the catid)
2. checking the menu items you can see that the single article items have a double id
`index.php?option=com_content&view=article&id=&id=11`
![image](https://user-images.githubusercontent.com/1296369/102538432-2be25700-40a4-11eb-8658-e5857a54abd9.png)

@chmst

**Comment by chmst** [comment]
Thanks a lot for testing. I will repair it asap.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31690">issues.joomla.org/tracker/joomla-cms/31690</a>.</sub>

**Comment by brianteeman** [comment]
discovered while trying to work out how to build sampledata ;)

**Comment by chmst** [comment]
It's not easy :) please test #31711
