### ISSUE TITLE
[4.0] Form Columns rendered different between Chrome & Safari

### ISSUE THREAD

**Issue by marcorensch** [joomla/joomla-cms#31696]
### Steps to reproduce the issue
Create a module and add some fields in a custom fieldset.
You should at least got three columns for the fields.

### Expected result
fields got placed over the three columns and are on the same place on each browser.

### Actual result
Different rendering in Chrome & Safari (Windows not tested)
Chrome:
![screen shot 2020-12-17 at 21 31 05](https://issues.joomla.org/uploads/1/fd966d6e2b2fbdcd3c8096ef495537ee.png)
Safari:
![screen shot 2020-12-17 at 21 31 31](https://issues.joomla.org/uploads/1/bac5455627c7f91908ad6e7db62f707c.png)

Classnames looks good no console errors visible...

**Comment by Quy** [comment]
Related #30454?

**Comment by marcorensch** [comment]
yes its related
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31696">issues.joomla.org/tracker/joomla-cms/31696</a>.</sub>

**Comment by drmenzelit** [comment]
It is a J3 or J4 issue?

**Comment by brianteeman** [comment]
J4

**Comment by Quy** [comment]
Fixed in PR #32422
