### ISSUE TITLE
[4.0] Changing the menuItem Type resets all other input

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#31693]
### Steps to reproduce the issue
Open a menu item for edit.
Change the title (and other input, if you want).
Then click on the menuType button. A modal appears and you can select a menu Type. Close the modal window.

### Expected result
As in J3, the new menuType is set and the other input remains unchanged

### Actual result
When closing the modal window, all input is reset to the original values.

**Comment by bembelimen** [comment]
> ### Expected result
> 
> As in J3, the new menuType is set and the other input remains unchanged

This is also an issue in J3, because the params (that are the one which get reset) are not handled properly.

**Comment by brianteeman** [comment]
Am I missing something - I cant replicate this

![menu](https://user-images.githubusercontent.com/1296369/119161545-5a989b00-ba51-11eb-9bb2-af44e5ae034c.gif)

**Comment by chmst** [comment]
Indeed - this issue seems to be resolved by one of the changes in the last time. Thanks for that hint, I close the issue.
