### ISSUE TITLE
Articles by authors

### ISSUE THREAD

**Issue by leoalv** [joomla/joomla-cms#31700]
We have known for a long time that Joomla articles are very limited, that was partly solved with the arrival of tags and then the extra fields. But a chronic and most requested need is to be able to show galleries articles by an author.

An author page is necessary with the list of his articles, as if other CMS have it.

**Is there a plan to integrate this?**

**Comment by drmenzelit** [comment]
It is already possible to create an author's page using the contact component.
Some weeks ago Daniel Dubois and me created some tutorials for this: 
https://www.web-eau.net/blog/how-to-create-an-author-page-in-joomla
https://www.dr-menzel-it.de/blog/override-challenge-autor-seite
