### ISSUE TITLE
[4.0] com_csp URL 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31709]
See https://github.com/joomla/joomla-cms/discussions/31641 for details

There is a bug in com_csp in that it is only showing the domain root which is not the same as the site root AND it is not showing the actual url

![screenshot](https://user-images.githubusercontent.com/1296369/102262468-0c63f680-3f0b-11eb-93b6-5876242a7df1.png)

**Comment by bembelimen** [comment]
Just for documentation, as I'm not sure why it's done that way:
[here the full URL is available](https://github.com/joomla/joomla-cms/blob/4.0-dev/components/com_csp/src/Controller/ReportController.php#L113-L114) but only the domain is saved. As @zero-24 did a lot of changes here, perhaps he can explain?

**Comment by zero-24** [comment]
Solution is here: https://github.com/joomla/joomla-cms/discussions/31641#discussioncomment-221691 ;-)

We just need to have someone with the time to make a PR with that changes.

**Comment by bembelimen** [comment]
Two things I don't like at the solution:
1. it uses ```parse_url``` instead of ```Uri``` (internal checks etc.)
2. Wildly saving a full url with all parameters looks for me like a good way to open up a gate for potential XSS as any URL can be send in the request + there is a high potential that an admin opens the url to check the page for the stuff, because the list is really lacking important information (which script etc)

**Comment by zero-24** [comment]
Agree feel free to send a PR that uses uri vs parse_url.

> Wildly saving a full url with all parameters looks for me like a good way to open up a gate for potential XSS as any URL can be send in the request + there is a high potential that an admin opens the url to check the page for the stuff, because the list is really lacking important information (which script etc)

Agree on the XSS stuff any ideas to solve it?

There is an issue open on the CSP specs site. Right now we could only get a short part of the script but not the full or even better the script hash to whitelist it.
https://github.com/w3c/webappsec-csp/issues/378

**Comment by brianteeman** [comment]
With 
- the absence of URL being displayed
- the lack of info about which script
- the potential for serious xss issues if the url is displayed
- the absence of any helpful information suitable for the typical Joomla user
this should be removed from 4.0 and pushed back to 4.1. Its just nowhere near release ready sadly

**Comment by brianteeman** [comment]
Trying to use this in the real world and even on a site that only has five pages the reports are completely useless

![image](https://user-images.githubusercontent.com/1296369/108543393-eed15580-72dc-11eb-9548-e17cf54184ef.png)

**Comment by zero-24** [comment]
Agree thats the reason i proposed the change that still allows the full url to be shown as before the other PR.

**Comment by rdeutz** [comment]
closing as we have a PR #32893
