### ISSUE TITLE
[3.9.24rc] Logic of send test mail is broken now

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31715]
### Steps to reproduce the issue

Use Correctly SMTP settings in your Joomla config in Joomla 3.9.x site

Upgrade to Joomla 3.9.24 RC 

Go to Joomla Global Config, see the settings are all there, password "appears" there as asterisks, so you click "Send Test Email" EXPECTING the credentials previously stored to be used, because you DID NOT click Modify and set a new password.

That is a reasonable assumption that a USER of Joomla (not a developer) would make. The button is there, I should be able to use it as advertised. 

### Expected result

Email Sent by SMTP with stored credentials, as I did not click "modify" button next to password

### Actual result

The email is sent by PHP mail as a fall back because I did not put a NEW password for SMTP in the config form 

### Additional comments

This is a logic regression caused by the changed in 3.9.24 and WILL CAUSE additional support forum posts and bug reports after release unless addressed. 

The fix is to ONLY show the Send Test Mail button when it is logically to do so, I.e when a change has been made to a field, like the password.

**Comment by PhilETaylor** [comment]
This was also reported https://github.com/joomla/joomla-cms/issues/31546#issuecomment-736384923 by @jjnxpct but was ignored.

**Comment by HLeithner** [comment]
closed because we have a pr #31724

@PhilETaylor can you please test this pr
