### ISSUE TITLE
[3.9.24rc] New Password Lock button, along with validation error, causes session persistent issues

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31716]
### Steps to reproduce the issue

Install Joomla 3.9.24rc
Go to Joomla Global Config
Click Modify next to Database Password
DON'T enter a password
Click Save
see correct error "Could not connect to database."
Note database password is now locked and blank
Navigate to another Joomla admin url, lets say go and view your menu items for example)
Return to Joomla Global Config (for example, to make a changing to another config setting like site name)
Click SAVE

### Expected result

No error

### Actual result

Error
Could not connect to database.

### Additional comments

This is because Joomla stores failed form submissions in the session to re-populate the form ...

**Comment by HLeithner** [comment]
Thanks for the report I will look into it.

**Comment by HLeithner** [comment]
Closing we have a PR #31728

Can you have a look @PhilETaylor
