### ISSUE TITLE
Failed update leaves files in tmp folder 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31721]
### Steps to reproduce the issue

Joomla 3
Install pkg_maximenuckparams_4.1.1.zip from https://github.com/joomla/joomla-cms/files/5665353/pkg_maximenuckparams_4.1.1.zip

Then go to Update Manager, select the update and click Update

Note that it fails - lets accept that fact. 

### Expected result

That the error message doesn't refer to the system generated tmp file name of "index.php_option_com_dms_task_doc_download_id_129_updater_true" which is meaningless to the user

No files remain in the Joomla Tmp Folder

### Actual result

index.php_option_com_dms_task_doc_download_id_129_updater_true is left in the tmp folder 

`index.php_option_com_dms_task_doc_download_id_129_updater_true` is mentioned in the error message 

<img width="913" alt="101621292-dc51ba80-3a15-11eb-8030-7f3e85da0b1c" src="https://user-images.githubusercontent.com/400092/102662140-21908d80-4176-11eb-8426-773ad008149d.png">

The leftover file in the tmp folder is a HTML file and can be rendered by direct access eg: https://www.phil-taylor.com/tmp/index.php_option_com_dms_task_doc_download_id_129_updater_true

<img width="1579" alt="Screenshot 2020-12-18 at 21 17 35" src="https://user-images.githubusercontent.com/400092/102662288-759b7200-4176-11eb-8a75-7f5a52fcd8f7.png">

**Comment by infograf768** [comment]
I was also wondering about quoting the broken file when I did https://github.com/joomla/joomla-cms/pull/31620
@HLeithner Remember: I was wondering about that. Your position was "adding the filename can help to identify the problem"

**Comment by HLeithner** [comment]
You are right I expected that's the file from the uncompressed pkg.zip and not the downloaded file it self. 

@infograf768 can you make a pr incl. removal of the temp file please?
