### ISSUE TITLE
[3.9.24RC] Media Manager issues 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31725]
### Steps to reproduce the issue

In Joomla 3.9.24RC admin -> Edit an article 
Images and links tab
Click SELECT to launch the Media Manager to select a new Intro Image

### Expected result

Not what I see haha

### Actual result

![Screen Recording 2020-12-18 at 09 48 02 pm](https://user-images.githubusercontent.com/400092/102664561-f8bec700-417a-11eb-865a-d0cab7448ee4.gif)

### System information (as much as possible)

Safari on MacOS
PHP 8.0.2-dev

**Comment by HLeithner** [comment]
Can you please check another browser?

**Comment by PhilETaylor** [comment]
Its ok on Google Chrome on MacOS

its broken on Safari on iPad 
its broken on safari on MacOS

**Comment by HLeithner** [comment]
ok thanks maybe @Fedik can have a look at this?

**Comment by PhilETaylor** [comment]
![image](https://user-images.githubusercontent.com/400092/102666528-1db53900-417f-11eb-9887-5c9de8b872e4.png)

**Comment by infograf768** [comment]
same with php 7.x.x ?

**Comment by infograf768** [comment]
I confirm issue with php 7.3.9 Safari Version 12.1.2 (12607.3.10)

**Comment by infograf768** [comment]
We have a `style="display: none;"` in the select.

Without it we get
<img width="1052" alt="Screen Shot 2020-12-19 at 07 29 25" src="https://user-images.githubusercontent.com/869724/102682726-0badb780-41cc-11eb-8e53-94c4815238e5.png">

But it is working fine when using the images xtd...

**Comment by Fedik** [comment]
I do not have a safari, cannot check, sorry,

> We have a style="display: none;" in the select.

Hm, does it use Choosen.js ? Maybe after some safari update that broke this lib.

**Comment by infograf768** [comment]
After multiple tests and trying to modify through console the scss, or quitting Safari, killing session, result tests are not clear. I sometimes get a correct display, sometimes not. Confused...

**Comment by infograf768** [comment]
@Fedik 
Screenshots

<img width="843" alt="Screen Shot 2020-12-19 at 10 21 46" src="https://user-images.githubusercontent.com/869724/102685899-22f89f00-41e4-11eb-9ab1-57c07254c72c.png">

<img width="763" alt="Screen Shot 2020-12-19 at 10 22 09" src="https://user-images.githubusercontent.com/869724/102685911-30158e00-41e4-11eb-9d2c-44850962ffe8.png">

**Comment by Fedik** [comment]
yea, it is Choosen.js, hm hm
I suspect it cannot calculate correct size on safari, or something

**Comment by Fedik** [comment]
in theory same issue should be in all j3.x.x in safari, because we do not change anything in j3.9.24 for this view

**Comment by Fedik** [comment]
@infograf768 to disable choose, just remove this line :)
 https://github.com/joomla/joomla-cms/blob/4172b68dac980a85c6070511622322006e98fb5b/administrator/components/com_media/views/images/tmpl/default.php#L21-L23

**Comment by infograf768** [comment]
Well, not so nice for other browsers.

for both xtd and media field

Safari after change

<img width="777" alt="Screen Shot 2020-12-19 at 11 06 46" src="https://user-images.githubusercontent.com/869724/102686860-ce0c5700-41ea-11eb-9557-058869ad7051.png">

<img width="876" alt="Screen Shot 2020-12-19 at 11 07 05" src="https://user-images.githubusercontent.com/869724/102686863-d795bf00-41ea-11eb-996c-c68b35efaabe.png">

Firefox BEFORE change
<img width="560" alt="Screen Shot 2020-12-19 at 11 08 53" src="https://user-images.githubusercontent.com/869724/102686874-ec725280-41ea-11eb-97c1-e0716b362c7a.png">

<img width="936" alt="Screen Shot 2020-12-19 at 11 09 09" src="https://user-images.githubusercontent.com/869724/102686878-f2683380-41ea-11eb-89c9-1c2e273b871d.png">

Firefox AFTER change

<img width="753" alt="Screen Shot 2020-12-19 at 11 08 10" src="https://user-images.githubusercontent.com/869724/102686886-0318a980-41eb-11eb-8e6d-b5de896344c6.png">

<img width="931" alt="Screen Shot 2020-12-19 at 11 08 25" src="https://user-images.githubusercontent.com/869724/102686894-1af02d80-41eb-11eb-841f-ee27e6e8bf8f.png">


Chrome after change

<img width="326" alt="Screen Shot 2020-12-19 at 11 15 12" src="https://user-images.githubusercontent.com/869724/102686954-a10c7400-41eb-11eb-8a50-10987d669176.png">

**Comment by Fedik** [comment]
> Well, not so nice for other browsers.

yeah, I agree

**Comment by Fedik** [comment]
maybe @dgrammatiko can have a look, he have safari :)

**Comment by dgrammatiko** [comment]
> in theory same issue should be in all j3.x.x in safari, because we do not change anything in j3.9.24 for this view

Well, it's not the case for 3.9.23 as I already tested it there. For the RC I have to setup a local env (new PC here) and it will take some time

**Comment by dgrammatiko** [comment]
Sorry it seems I can't replicate it either with the latest Safari or Safari Technology Preview on Big Sur
![Screenshot 2020-12-21 at 19 12 24](https://user-images.githubusercontent.com/3889375/102808423-96ef9e80-43c0-11eb-95b0-7b13c75921e6.png)
![Screenshot 2020-12-21 at 19 12 07](https://user-images.githubusercontent.com/3889375/102808433-99ea8f00-43c0-11eb-844a-38b0f22da4fa.png)

Please clean your cache **and** clear the history then try again (it might be a hiccup on some css file)

**Comment by PhilETaylor** [comment]
I replicated it on my iPad and on my iMac, independently... 

If no one else can replicate it then no bother.

**Comment by dgrammatiko** [comment]
@PhilETaylor you don't have to close it as it could be a legitimate bug. I just d/l the RC and couldn't replicate it. Maybe it needs some specific criteria?

**Comment by PhilETaylor** [comment]
Im going to the kids bedroom to use her iMac... its never had Joomla installed. Fingers crossed.

**Comment by PhilETaylor** [comment]
Im guessing a width of 2px is not correct... 
<img width="460" alt="Screenshot 2020-12-21 at 18 27 56" src="https://user-images.githubusercontent.com/400092/102809656-4a08c980-43ba-11eb-8ca5-ffcd3874d9a5.png">

**Comment by dgrammatiko** [comment]
That should be 220px

**Comment by PhilETaylor** [comment]
Broken on Firefox on macOS

<img width="1170" alt="Screenshot 2020-12-21 at 18 32 51" src="https://user-images.githubusercontent.com/400092/102810070-f945a080-43ba-11eb-88b1-8f25ece7cff3.png">

**Comment by PhilETaylor** [comment]
Its a PHP 8 issue. wow...

As soon as I run it in PHP 7.4/7.3/7.2 it works fine...

**Comment by dgrammatiko** [comment]
@PhilETaylor I'm also on PHP 8.0 here

**Comment by PhilETaylor** [comment]
try running it with the command line php server 

`php -S 0.0.0.0:80`

I can replicate it every time in Firefox and Safari when using that with PHP 8.0.2-dev - but still confused why this is a PHP issue.

**Comment by PhilETaylor** [comment]
In fact I lie, my command line is not docker, so its running stable released 8.0.0 and not any funky 8.0.2-dev which I use in docker.

100% replicate-able now, using `php -S 0.0.0.0:80` development server with brew installed php 8.0.0

**Comment by dgrammatiko** [comment]
Can you try something: 
https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/html/formbehavior/chosen.php
change to 
```php
$options_str =  "";
```

**Comment by dgrammatiko** [comment]
*change line 29 to

**Comment by PhilETaylor** [comment]
Slightly different as the search icon is brought back on screen

<img width="238" alt="Screenshot 2020-12-21 at 19 13 38" src="https://user-images.githubusercontent.com/400092/102813395-a4a52400-43c0-11eb-8375-47800f499955.png">

**Comment by dgrammatiko** [comment]
@PhilETaylor you might want to step into https://github.com/joomla/joomla-cms/blob/12830b3d5bbfd9fe0969635ccddb81cf3bbcfd8f/administrator/components/com_media/models/manager.php#L61
and check the final string returned from here. I'm still unable to reproduce it here, sorry 🤷‍♂️

**Comment by PhilETaylor** [comment]
I can no longer replicate this on any browser with `staging` today. If someone else that used to be able to confirm this, can also see its working today then we can just ignore this issue and close this.
