### ISSUE TITLE
[3.9] overuse of console.warn?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31727]
### Steps to reproduce the issue

Without trying to invoke the JS gods on this...

while useful in development (in uncompressed js files) the console.warn messages are also showing up on live sites... do we really want to be doing that? its bad practice to output to the console log in production right? 

These messages are actually only trigged just before a page "unloads" when a user clicks a button so are rarely seen anyway, unless the log is preserved between navigations

### Expected result

Silence. Nothing logged on a live site using the compressed js files. 

### Actual result

<img width="511" alt="Screenshot 2020-12-18 at 22 00 36" src="https://user-images.githubusercontent.com/400092/102665496-cf069f80-417c-11eb-9658-a818eb5a5275.png">

<img width="1163" alt="Screenshot 2020-12-18 at 22 03 33" src="https://user-images.githubusercontent.com/400092/102665543-ec3b6e00-417c-11eb-8709-e175dc200f7c.png">

**Comment by Fedik** [comment]
Here you asked to much :wink: 

Well, all j3 js minified manually, by people who doing PR, here is no any fancy build tool that may allow to do it.
Just forget it

**Comment by PhilETaylor** [comment]
> Just forget it

Closed.
