### ISSUE TITLE
[3.9.24RC] No User Button wrapping 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31726]
### Steps to reproduce the issue

3.9.24RC Admin Console, edit an article, Publishing tab, click blue/white button to launch a user select modal

### Expected result

`- No User -` 

### Actual result

My 27" screen is large enough nothing should wrap! :-) 
```
- No User
-
```

<img width="1730" alt="Screenshot 2020-12-18 at 21 52 40" src="https://user-images.githubusercontent.com/400092/102664768-679c2000-417b-11eb-9eb1-8232db06d70b.png">

### System information (as much as possible)

Safari on MacOS

**Comment by HLeithner** [comment]
Can you please check another browser?

**Comment by PhilETaylor** [comment]
Its ok on Google Chrome on MacOS

its broken on Safari on iPad 
its broken on safari on MacOS

**Comment by HLeithner** [comment]
ok thanks maybe @Fedik can have a look at this?

**Comment by PhilETaylor** [comment]
![Uploading 102666546...]

**Comment by PhilETaylor** [comment]
![image](https://user-images.githubusercontent.com/400092/102666564-358cbd00-417f-11eb-86be-75ac5cdae9c2.png)

**Comment by infograf768** [comment]
PHP version?

Can't reproduce on 7.3.9 Safari Version 12.1.2 (12607.3.10)

**Comment by Fedik** [comment]
people should stop using safari :smile:

**Comment by PhilETaylor** [comment]
PHP version is 8.0.2-dev built from source on 18th December, but I doubt the PHP version is at fault.

The screenshot above is on an iPad, the first screenshot was on my iMac (Safari Version 14.0.3 (16610.4.2) on MacOS 1.2 Beta (20D5029f)

**Comment by Fedik** [comment]
> but I doubt the PHP version is at fault

I am not sure, but I suspect it also choosen.js issue, as in issue about media #31725

**Comment by PhilETaylor** [comment]
Tested today with macOS latest beta - Safari Version 14.1 (16611.1.21.161.3) and its still as per the opening report

I cannot replicate in Firefox or Google Chrome today

**Comment by ghost** [comment]
Safari 13.1 (old MacOS 10.13), php 8.0.3:

> ![Bildschirmfoto 2021-04-17 um 17 38 51](https://user-images.githubusercontent.com/78906980/115118621-61407800-9fa4-11eb-8281-b8de2e85d271.png)

**Comment by PhilETaylor** [comment]
Give up, there are bigger fish to fry and Joomla 3 is dead￼
