### ISSUE TITLE
[4.0] Choices scss cassiopeia

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31738]
The scss overrides for the choices library are out of sync between atum and cassiopeia. As a result the filters when editing an article look different. 

/me not good enough to fix this

## Atum
![image](https://user-images.githubusercontent.com/1296369/102717595-418d9180-42db-11eb-9a38-f47ecd478870.png)

## Cassiopeia
![image](https://user-images.githubusercontent.com/1296369/102717599-4c482680-42db-11eb-9f13-92dd1f132802.png)

**Comment by infograf768** [comment]
Concerns the xtd articles.

It's even worse when selecting multiple stuff. below for categories.

Atum

<img width="1125" alt="Screen Shot 2020-12-22 at 09 27 26" src="https://user-images.githubusercontent.com/869724/102866731-081e6880-4438-11eb-9015-0a4305c78bd0.png">

Cassiopea

<img width="1060" alt="Screen Shot 2020-12-22 at 09 28 04" src="https://user-images.githubusercontent.com/869724/102866777-1c626580-4438-11eb-8382-a06b73b3c4f2.png">

**Comment by chmst** [comment]
Closing this as we have a PR
