### ISSUE TITLE
#27851 backport needed to staging

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#31747]
### Steps to reproduce the issue
Got to
/administrator/index.php?option=com_templates&view=styles
edit Beez3 index.php

### Expected result
No PHP Warning:  Trying to access array offset on value of type null
administrator\\components\\com_templates\\views\\template\\tmpl\\default_modal_resize_body.php on line 21
administrator\\components\\com_templates\\views\\template\\tmpl\\default_modal_resize_body.php on line 31

### Actual result
PHP Warning

### System information (as much as possible)
XAMPP
PHP 8.0
Joomla 3.9.24-rc

**Comment by Quy** [comment]
PR #31749
