### ISSUE TITLE
[4.0] Uncaught TypeError

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31741]
### Steps to reproduce the issue
Open chrome developer tools so that you can see any errors
Make sure that you have an article field created. If not create one.

### Expected result
No console errors

### Actual result
```
Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at HTMLDocument.a (batch-language.min.js?1cb4b4bb071e6b5db876b60a3b31bbe9:1)
a @ batch-language.min.js?1cb4b4bb071e6b5db876b60a3b31bbe9:1
```

### Additional comments
This was tested on a monolingual en-gb site with sample data

**Comment by bembelimen** [comment]
Hi @brianteeman ,
what do you mean with "article field" a normal custom field?

**Comment by brianteeman** [comment]
I meant a custom field for articles - sorry i wasnt clear

![image](https://user-images.githubusercontent.com/1296369/103182160-26a1bb00-48a1-11eb-8bca-ed04a66e6cd2.png)

![image](https://user-images.githubusercontent.com/1296369/103182164-31f4e680-48a1-11eb-88ed-05954f37c845.png)

**Comment by bembelimen** [comment]
Thanks, found the error. I think you found a bigger issue than it seems on the first glimse. I tried to fix it in the PR.
