### ISSUE TITLE
English language string in mass mails

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#31740]
### Steps to reproduce the issue

COM_USERS_MAIL_FIELD_EMAIL_DISABLED_USERS_LABEL="Send to Disabled Users"

@brianteeman can we change this to "Blocked Users" or another word than disabled? In context with users the word looks not correct.

**Comment by brianteeman** [comment]
I agree it is not the correct word at all

Not sure its a function that we should actually have either

**Comment by brianteeman** [comment]
Please test #31742

**Comment by chmst** [comment]
Thanks
