### ISSUE TITLE
[4.0] Color custom field as text in front-end

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#31753]
### Steps to reproduce the issue
Assign a color field in an article and check it in the front-end.

### Expected result
Colored element (square, circle, whatever)

### Actual result
Color in hex. text format

![color_custom field front-end](https://user-images.githubusercontent.com/1838041/102913054-e5677080-4486-11eb-820b-60934fa2d01c.png)

### System information (as much as possible)
Joomla 4.0 beta6

**Comment by C-Lodder** [comment]
I think the HEX is expected, so it can be used accordingly. Not sure what benefit a "Coloured element (square, circle, whatever)" would be.

**Comment by drmenzelit** [comment]
You can create an alternative layout for the color field and render a div container with the color value of the field. 

![grafik](https://user-images.githubusercontent.com/9153168/103030912-0d290800-455d-11eb-8a30-ef044bbfbb8d.png)

That is an example I created for a tutorial.

**Comment by drmenzelit** [comment]
The tutorial is in German, but maybe you can Google translate it
https://www.hosteurope.de/blog/custom-fields-fuer-fortgeschrittene-parameter-und-alternative-layouts-fuer-custom-fields/

**Comment by sakiss** [comment]
Thank you for the replies.

I was hoping to integrate that in the core, since a hex. code does not mean a lot to a regular user.

I can prepare a PR, if it has chances to get merged.

**Comment by bembelimen** [comment]
The hex code is exactly the expected result, as @C-Lodder pointed out, a coloured element does not make much sense in a generic way. To make is specific, just mkae an override and build your own element.

**Comment by sakiss** [comment]
> a coloured element does not make much sense in a generic way

Still do not understand how the hexademical code makes more sense, than the visual color.
