### ISSUE TITLE
[4.0]Site fails with 'Trait "Joomla\Plugin\System\Webauthn\PluginTraits\AjaxHandler" not found"'

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#31752]
### Steps to reproduce the issue
Download Joomla_4.0.0-beta6-dev-Development-Full_Package.zip from Nightly Builds.
Install Beta6-dev Full package of 22 December.
Remove the installation folder.
Rename htaccess.txt as .htaccess
Go to front end.
Go to back end.

### Expected result
No error messages.

### Actual result
Both front end and back end report an error:
Fatal error: Trait "Joomla\Plugin\System\Webauthn\PluginTraits\AjaxHandler" not found in C:\www\joomla4\plugins\system\webauthn\webauthn.php on line 34

### System information (as much as possible)
Windows 10, Wampserver 3.2.4
Apache 2.4.46a, MySQL 8.0.22, PHP 8.0.0

**Comment by toivo** [comment]
Repeated the same installation in the same environment but using PHP 7.4.13 and I was able to login normally.  No error messages.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31752">issues.joomla.org/tracker/joomla-cms/31752</a>.</sub>

**Comment by toivo** [comment]
Logged out, changed the PHP version to 8.0.0 and was able to login again and the website works all right.  It seems that the issue occurs only if the installation was done using PHP 8.0.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31752">issues.joomla.org/tracker/joomla-cms/31752</a>.</sub>

**Comment by toivo** [comment]
Repeated the same installation with Beta6-dev Full package of 23 December using PHP 8.0.0 and the installation completed successfully.

This PR can now be closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31752">issues.joomla.org/tracker/joomla-cms/31752</a>.</sub>

**Comment by ghost** [comment]
you can close this issue as opener yourself.

**Comment by alikon** [comment]
thanks @toivo  for the feedback
