### ISSUE TITLE
[4.0] Tags Module shows tags from other languages

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#31754]
### Steps to reproduce the issue
1. A multi-lingual site is required (for the example i will use English and German).
2. Create a tag and set "English" in the language field.
3. Create an article in German and assign the previously created tag.
Btw. Loading tags in different language than the article's one, seems buggy.
4. Create and enable a Tags module.
5. Check your front-end in the German language.

Tags
![tags_be](https://user-images.githubusercontent.com/1838041/102916719-ac31ff00-448c-11eb-8404-d9100e0068a0.png)

Article assignment
![article_tags](https://user-images.githubusercontent.com/1838041/102916726-b05e1c80-448c-11eb-83f0-3002b4751488.png)

### Expected result
The tags in languages other than the site's language not to be loaded.

### Actual result
It shows tags from all the languages, that were assigned at least in 1 article.

![tags_fe](https://user-images.githubusercontent.com/1838041/102916736-b48a3a00-448c-11eb-8f37-9bf4de519b3b.png)

### System information (as much as possible)

Joomla4.0 beta6

### Additional comments
Language Filter : Current in the com_tags configuration

**Comment by chmst** [comment]
As long as an atricle is not saved, the system cannot know for which language you are writing, so how should it select a language for tags? I think that this is normal behaviour.

**Comment by bembelimen** [comment]
Go to the Tags options in the backend and set the "language filter" to "Current" to have the expected behaviour (ofc the language detection should set to "browser" in the language plugin):

![grafik](https://user-images.githubusercontent.com/1229869/103181804-8306d980-48a5-11eb-8f7e-808124390768.png)

**Comment by sakiss** [comment]
@bembelimen I already pointed that the "Language Filter" is set to current.

Plz read the post and try to reproduce the issue, before closing it.

**Comment by bembelimen** [comment]
I did and it works as expected:

![grafik](https://user-images.githubusercontent.com/1229869/103213400-db71c180-490d-11eb-8229-172103c1c4c4.png)

German:
![grafik](https://user-images.githubusercontent.com/1229869/103213434-ed536480-490d-11eb-866a-a7474929d0f4.png)

English:
![grafik](https://user-images.githubusercontent.com/1229869/103213448-fc3a1700-490d-11eb-8d30-1990fd1bc780.png)

**Comment by sakiss** [comment]
@bembelimen plz follow the instructions as mentioned in my post.
The tag needs to be in different language than the article.

**Comment by infograf768** [comment]
I can't reproduce the issue either on last 4.0-dev

Tag is created (using sample data)  Language: en-GB

<img width="1161" alt="Screen Shot 2020-12-29 at 11 32 39" src="https://user-images.githubusercontent.com/869724/103277551-9ca14180-49c9-11eb-8f8c-58dbaf9fd426.png">

Article assigned to French has multiple tags, one is the tag above.

<img width="343" alt="Screen Shot 2020-12-29 at 11 34 41" src="https://user-images.githubusercontent.com/869724/103277673-dd995600-49c9-11eb-9a91-5891ee30353f.png">

Displaying the article in frontend (French interface) gives:

<img width="1177" alt="Screen Shot 2020-12-29 at 11 35 41" src="https://user-images.githubusercontent.com/869724/103277774-0c173100-49ca-11eb-9571-02c2c652f2a5.png">

As you can see the `Love (en-GB)` tag is just ignored.

I suggest you test with last nightly build.
https://developer.joomla.org/nightly-builds.html

**Comment by sakiss** [comment]
I could replcate it also using the latest nightly built and in a freshly git cloned installation.

![tags_be2](https://user-images.githubusercontent.com/1838041/103291995-94f79200-49f5-11eb-8638-fe811f40f500.png)

![tags_fe_2](https://user-images.githubusercontent.com/1838041/103292006-9cb73680-49f5-11eb-961f-966d24658bbb.png)


In the example above the "Tagen (de-DE)" is not loaded despite it is assigned in a German article while the "Yellow (en-GB)" shows up while the site's language is Geman.

Not sure if i am missing something in order for you to reproduce it.
If anyone else can check it, would be fine.

Language Filter: Current

**Comment by ghost** [comment]
@sakiss I couldn't get the behaviour you get. 

Only if i set in tag-options the language filter to `All` the english-tag is shown in popular tag-module and article on german language-site.

**Comment by Quy** [comment]
Please test PR #37721. Thanks.
