### ISSUE TITLE
Bug joomla in field colon: before value 

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#31777]
Steps to reproduce the issue

Create new field. Use this field.

Expected result

field withoutcolon value

Actual result

field withoutcolon: value

why : is displayed?

System information (as much as possible)

Safari on MacOS
PHP 8.0

**Comment by drmenzelit** [comment]
The : is part of the label of the field. You can put the label off or create an alternative layout for the field and change the way it is rendered.

**Comment by richard67** [comment]
Closing as expected behaviour.

**Comment by chnnst** [comment]
Can you please provide more infos / screenshots how to put the : off ?

**Comment by infograf768** [comment]
I have explained in the Discussion how to override this.
