### ISSUE TITLE
[4.0] Media crop plugin

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31773]
### Steps to reproduce the issue
select an image in the media manager and then the edit icon
in the first tab click into the x-axis or height boxes and try to change the value

![bits](https://user-images.githubusercontent.com/1296369/103032180-5a09e000-4557-11eb-9a35-42f1627d1d1e.gif)

**Comment by brianteeman** [comment]
Same problem with the resize plugin
![bits](https://user-images.githubusercontent.com/1296369/103032324-ad7c2e00-4557-11eb-8b3a-95e453551fed.gif)

**Comment by bembelimen** [comment]
That's an chrome issue (works with firefox). The box shadow appears on the bottom left of the previous column when ```:focus``` is set on the input field. I tried to change the CSS attributes on the element, but nothing triggered a change.

Are you more successful?

**Comment by brianteeman** [comment]
@bembelimen nope sadly not - hence I created an issue instead of a pr

**Comment by brianteeman** [comment]
Closed as this was resolved elsewhere the redesign of fields
