### ISSUE TITLE
[3.9] Incorrect display of the number of administrators in the control panel

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#31770]
### Steps to reproduce the issue
Just use the "User Status" module in the control panel for a while. Observe the number of administrators in the control panel.

### Expected result
According to the module parameter:

```
MOD_STATUS_FIELD_SHOW_LOGGEDIN_USERS_ADMIN_DESC="Show the number of users logged-in to the Backend."
MOD_STATUS_FIELD_SHOW_LOGGEDIN_USERS_ADMIN_LABEL="Logged-in Backend Users"
```
I expect to see the actual number of admins at the moment.

### Actual result
Administrator logins are summarized (presumably).
Clearing the browser cache, reducing the session time does not affect the indicator.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/102998808-8fe79e00-4530-11eb-883c-2c0e0c7ca9b0.png)

I have 2 super administrators on my site. Only they can log in to the control panel.

### System information (as much as possible)

- Joomla 3.9.23
- PHP 7.3.25

**Comment by drmenzelit** [comment]
I checked several websites and I can't reproduce the issue.
Do you have the problem in more than one website? Is your database ok? Check Extensions -> Database

**Comment by Kostelano** [comment]
The database is fine. The problem is reproduced on all sites.

I figured out the situation a little. So.

For convenience, in the general site settings, you can set the session time = 1 minute. Then log into the admin panel every 1.5 minutes (for example). In my case, the number of administrators increases, since every 1.5 minutes I enter my username / password.

The problem "goes away" as soon as we directly log out of the account, and not just close the tab. In this case, the number of administrators in the control panel is immediately "reset". Log in again - the number is correct (= 1 administrator, because we are now alone in the control panel). If we again do not LOG OUT from the account, but simply close the tab and re-authorize in the control panel after 1.5 minutes, the number of administrators will increase again.

I cannot say that this is a serious bug, but in my opinion the logic of the module's operation is incorrect. not all of them perform the EXIT from the control panel. More often they just close the tab. Accordingly, the meaning of this parameter with the current logic is questionable.

**Comment by ReLater** [comment]
This is a reproducible and known issue on some Joomla sites. Try to adapt the settings in "System - Session Data Purge" to run the session cleanup more often!

**Comment by ReLater** [comment]
Check also: Plugin "User - Joomla!" > "Force Logout for all Sessions?"

**Comment by Kostelano** [comment]
I'll play around with the probability / divisor parameter and give some feedback. But I'll tell you right away that there were default values (1/100).

As for the second question, all parameters are set to YES.

**Comment by ReLater** [comment]
> But I'll tell you right away that there were default values (1/100).

Which means: Run the session cleanup on 1% of page requests.

A 1/1 or 100/100 means: Run the session cleanup on every page request which can become a performance issue on larger sites with lots of users.

**Comment by Kostelano** [comment]
Yes, setting 1/1 completely solved the problem described above. The site is very simple and small, 1/1 is fine for it.

Considering that the problem is solved, I close it.
@ReLater, thanks for the help with the solution.
