### ISSUE TITLE
Alternative layout doesn't work when articles inside a blog menu item

### ISSUE THREAD

**Issue by morphinestyle** [joomla/joomla-cms#31796]
### Steps to reproduce the issue
Change default article layout to any CUSTOM-LAYOUT (globally or locally into article).
Create a menu voice with a blog item (containing article TEST-ARTICLE).
On frontend, click on any TEST-ARTICLE article related link to load article TEST-ARTICLE.

### Expected result
Joomla! should load TEST-ARTICLE article with the CUSTOM-LAYOUT, as set.

### Actual result
Joomla! ignore any setting for custom layout, and load TEST-ARTICLE with the Joomla! default layout.

### Additional comments
Some users tried to solve modifying application.php -and/or- site.php:
https://forum.joomla.org/viewtopic.php?f=619&t=671239

**Comment by chmst** [comment]
Please describe exactly how you have implemented your custom layout. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31796">issues.joomla.org/tracker/joomla-cms/31796</a>.</sub>

**Comment by drmenzelit** [comment]
You need to select the alternative layout for the articles in the blog menu item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31796">issues.joomla.org/tracker/joomla-cms/31796</a>.</sub>

**Comment by morphinestyle** [comment]
I created a test.php file inside templates/g5_helium/html/com_content/article (i use Gantry, but it doesn't even work with the same procedure using default Protostar template and selecting a "test2.php" inside protostar/html/com_content/article).
In the general options I have selected test.php as the default layout.
When the BLOG menu item is activated my alternative layout file test.php is not working, loading standard article content.
When i disable the BLOG menu item my alternative layout become working again, and test.php is loaded correctly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31796">issues.joomla.org/tracker/joomla-cms/31796</a>.</sub>

**Comment by morphinestyle** [comment]
This is how it works ...
Indeed, the management of the template and layout for the "sub-pages" is unnecessarily complex in certain circumstances.
So this isn't an issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31796">issues.joomla.org/tracker/joomla-cms/31796</a>.</sub>

**Comment by drmenzelit** [comment]
No, it is not an issue. I'm closing this now.
