### ISSUE TITLE
[4.0] Strange minified files in installation template folder

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#31790]
### Steps to reproduce the issue
Build the CSS/JS files with ```npm i```

### Expected result
Clean files

### Actual result
![grafik](https://user-images.githubusercontent.com/1229869/103182757-193efd80-48ae-11eb-8e6d-ee0e32d4339e.png)

![grafik](https://user-images.githubusercontent.com/1229869/103182760-21973880-48ae-11eb-9a12-550cb37dfe9d.png)

### Additional comments
@dgrammatiko maybe?

**Comment by dgrammatiko** [comment]
Bloody DOS, changing https://github.com/joomla/joomla-cms/blob/c82eb53bea7a5ca3583e80ff0449262fcecf4a91/build/build-modules-js/compilecss.es6.js#L69 to 
```js
if (file.match(/\.css/) && (!file.match(/\/template(s)?\//) || !file.match(/\\template(s)?\\/))) {
```
should do the trick.

**Comment by bembelimen** [comment]
Thank you @dgrammatiko

**Comment by infograf768** [comment]
I guess it is windows only issue?
