### ISSUE TITLE
[4.0] Progress bar doesn't update on extension

### ISSUE THREAD

**Issue by mwweb** [joomla/joomla-cms#31797]
### Steps to reproduce the issue
Drag and drop extension package to extension installer

### Expected result
Progress bar would update to show progress

### Actual result
It appears that nothing is happening

### System information (as much as possible)
Database Version 5.7.24
Apache 2.4.35
Joomla Version 4.0.0-beta5
Browser: Chrome!

**Comment by chmst** [comment]
Which extension package do you want to install? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31797">issues.joomla.org/tracker/joomla-cms/31797</a>.</sub>

**Comment by Quy** [comment]
Closing due to no response.
