### ISSUE TITLE
[4.0] Article Info "Split" Setting Working Incorrectly

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#31802]
### Steps to reproduce the issue
With all Article Details displayed by default "above" the Article text, when selecting "Split" as the option, only 1 of the details line items drops below the Article Text.  When using Tags, and selecting "Split," the Tab and only 1 detail item drops below.

### Expected result
What/where is the control that indicates how many items, or the actually break points of the "Split" setting.
Should the Tag go below and the Details remain above.  The action of only one detail item dropping below on a "Split" setting appears irrational.
When Details and Tags are active in an Article, what should be the expected results of a "Split" setting.

**Comment by 200MPHMEDIA** [comment]
Typo Correction: "..."Split," the **Tab** and only 1 detail item drops below." should read "..."Split," the **Tag** and only 1 detail item drops below.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31802">issues.joomla.org/tracker/joomla-cms/31802</a>.</sub>

**Comment by drmenzelit** [comment]
Here you can see which lines will be displayed above and below:
https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/content/info_block.php

**Comment by chmst** [comment]
It is the same  as in j3 
![grafik](https://user-images.githubusercontent.com/1035262/103302939-160a5580-4a05-11eb-826e-d136ca2ca2a1.png)

**Comment by 200MPHMEDIA** [comment]
Thanks to both of you for assisting in isolating the "split" question.  Perhaps a bit more care should be made in the HELP screens to identify at which detail the "split" will occur.  Of course, most Help screens are simple regurgitation of the visually obvious and are lacking in any helpful guides for new users, such as blog column ordering, etc. etc.  This list is pretty long in that regard.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31802">issues.joomla.org/tracker/joomla-cms/31802</a>.</sub>

**Comment by chmst** [comment]
@200MPHMEDIA Thanks for your feeback! I'll close the issue here. Would you like to contribute to documentation and add this information? Or report the issue there? https://github.com/joomla/joomla-websites/issues/new?title=%5Bjdocs%5D%20
