### ISSUE TITLE
[4.0] Multi Column Order Missing

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#31801]
### Steps to reproduce the issue
In the Article Options, for the Blog/Featured Layout Options, the MULTI COLUMN ORDER selector is missing.
The Help Screen for this indicates that a MULTI COLUMN ORDER selector should be present.

### Expected result
Expected to see the MULTI COLUMN ORDER selector as one of the layout options.

**Comment by 200MPHMEDIA** [comment]
More ... if the Page Layout is governed/set by the Layout Class settings for the Menu Link Item, then the Help Screen indicating the settings are on the Article Options settings should be corrected with instructions on setting the Blog Classes, and a table to the settings that can be applied.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31801">issues.joomla.org/tracker/joomla-cms/31801</a>.</sub>

**Comment by drmenzelit** [comment]
See PR #31570

**Comment by richard67** [comment]
> See PR #31570

Yes, and that PR is for issue #27478 , and that issue has been reported by the same author than this one here.

@200MPHMEDIA Do you think it's helpful for us if the same issue is reported again and again so we have to find the duplicates? It causes us additional work.

**Comment by ghost** [comment]
we don´t need trolls

**Comment by richard67** [comment]
> we don´t need trolls

@gostn What are you referring to?

**Comment by ghost** [comment]
as you wrote its not helpful if the same issue is reported again and again.

**Comment by richard67** [comment]
Yes, but being a troll is something else.

**Comment by richard67** [comment]
https://en.wikipedia.org/wiki/Internet_troll

**Comment by ghost** [comment]
the same issue reporting again and again is in my opinion trolling but if you have another opinion its ok for me. I don't wanna discuss this cause other get mails for each comment, but the topic isn't really important for me as for you.

**Comment by chmst** [comment]
Closing this as it is duplicate and a PR is work in progress.
