### ISSUE TITLE
[4.0] Content - Page Navigation Ordering database error

### ISSUE THREAD

**Issue by david19161** [joomla/joomla-cms#31803]
### Steps to reproduce the issue
1 create a category blog menu
2 create an article and put in on the category blog menu made in step 1
3 set article global options->shared->Date for Ordering to Modified
4 goto frontend of site, select category blog menu made in step 1 then select article made in step 2

### Expected result
Article can be viewed ok

### Actual result
ERROR 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'THEN `a`.`created` ELSE `a`.`modified` END DESC' at line 5

### System information (as much as possible)
Joomla_4.0.0-beta6-dev-Development-Full_Package.zip 2020-12-29

### Additional comments
The error is coming from Content - Page Navigation plugin.

**Comment by alikon** [comment]
please test #31808
