### ISSUE TITLE
[4.0] Media field search for editor modals causing JS error

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#31816]
### Steps to reproduce the issue
Use a media field in a plugin or component view such as a menu item edit page.

### Expected result
No JS errors

### Actual result
JS errors, the file joomla-image-select.js is looking for options 'xtdImageModal'' in the Joomla.optionsStorage["xtdImageModal"] that are part of the editor modals and xtd buttons

### System information (as much as possible)

4.0 Beta 6 Dev

### Additional comments
![image](https://user-images.githubusercontent.com/17835460/103415092-f5670a80-4b80-11eb-90ca-31b762d923f1.png)

![image](https://user-images.githubusercontent.com/17835460/103414941-50e4c880-4b80-11eb-8613-84fa738f229e.png)

**Comment by infograf768** [comment]
Can you try the same trick as here?
https://github.com/joomla/joomla-cms/pull/31779/files

**Comment by joeforjoomla** [comment]
Yes @infograf768 this trick works.
Change from: if (MediaXTDElements.length) {
to: if (MediaXTDElements) {

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/31819

please mark your test OK here https://issues.joomla.org/tracker/joomla-cms/31819
