### ISSUE TITLE
Call to undefined method Joomla\CMS\Application\AdministratorApplication::isSite()

### ISSUE THREAD

**Issue by pioprzyb** [joomla/joomla-cms#31825]
### Steps to reproduce the issue
Installed new extention

### Expected result

No error

### Actual result

Error on both front and admin page. Unable to navigate in admin:

**Error:
Call to undefined method Joomla\CMS\Application\AdministratorApplication::isSite()**

### System information (as much as possible)

Joomla 4.0 Beta

**Comment by Quy** [comment]
Please test with the latest nightly builds: https://developer.joomla.org/nightly-builds.html

**Comment by brianteeman** [comment]
The code in the extension is not compatible with joomla 4. 

CMSApplication::isSite and CMSApplication::isAdmin have been removed as with the addition of the ConsoleApplication and ApiApplication can give misleading results. Please use CMSApplication::isClient (available from Joomla  3.7). See [the docs](https://docs.joomla.org/J3.x:Discover_on_which_client_your_extension_code_is_running)
