### ISSUE TITLE
[4.0] Media Manager UX/UI - resizing/jumping of content

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#31820]
### Steps to reproduce the issue
Go to **Media Manager** - **Resize** tab, click to change the width and change the width interactively.

### Expected result
The source image stays in some fixed box (size will be changed inside the box) and the content outside the source image will not change - will be not moved, will not jump, etc.

### Actual result
Now, all the content moves and jumps, see GIF:

![img](https://i.imgur.com/785Dw8W.gif)

https://i.imgur.com/YhYqXfu.gif

### System information (as much as possible)
Joomla! 4.0 ‎- 4.0.0-beta5

**Comment by Quy** [comment]
Related #29156
