### ISSUE TITLE
[4.0] Media xcf makes folder content inaccessible

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#31837]
### Steps to reproduce the issue

Place a file containing an xcf extension in one of the images sub-folders - this is the extension used by The Gimp and is included in the com_media default configuration.

### Expected result

Something sensible.

### Actual result

An error message and the folder content is not displayed.
![screen shot 2021-01-02 at 09 52 23](https://issues.joomla.org/uploads/1/ac2a46fcf9f894bd01c78c686b81c56e.png)

### Additional comments

I have found so many problems with the media manager I decided to work on a different approach using a much more standard Joomla component design. Please see https://github.com/ceford/j4xdemos-media-cat if you are interested. I am not sure how far I will take it.

**Comment by brianteeman** [comment]
Issue confirmed using the sample image from https://stendhalgame.org/wiki/File:Sample-column.xcf

Not really a priority as xcf is an obscure image format that will not display in a web browser

**Comment by wilsonge** [comment]
As it stops all images in the folder from loading it's actually slightly more priority (and I'm sure there's more image types PHP can't parse - so patch here: https://github.com/joomla/joomla-cms/pull/31845)
