### ISSUE TITLE
com_finder default_result doesn't show body of articles that have not both introtext and fulltext

### ISSUE THREAD

**Issue by kuehn-innerste** [joomla/joomla-cms#31848]
### Steps to reproduce the issue

1. create an article with the title "Hello finder", without introtext but with fulltext that contains several random sentences and the word "foobar"
1. call `php cli/finder_indexer.php`
1. search for "foobar"

### Expected result

In the results page I want to see the title "Hello finder", followed by the description of the article, with the word "foobar" highlighted

### Actual result

In the results page we see the title "Hello finder", but no description of the result 

### System information (as much as possible)

Database Type: 	mysql  
Database Version: 	5.6.45  
Database Collation:	utf8_general_ci  
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.4.3
Web Server 	Apache/2.4.41 (FreeBSD) OpenSSL/1.0.2s mod_fcgid/2.3.9
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.9.23 Stable [ Amani ] 24-November-2020 15:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0 

### Additional comments

I found the source of this issue in components/com_finder/tmpl/search/default_result.php:33: the `&&` operation only turns true if both parts are true. It should be replaced by the `||` operation.

In theory I would expect every article to have introtext and fulltext. In reality this is not a save assumption. On the site where I found this someone committed articles without introtext.

**Comment by richard67** [comment]
Closing as having pull request #31849 .
