### ISSUE TITLE
[4.0] Color Picker - surrounding content elements jump

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#31843]
### Steps to reproduce the issue
Similar to https://github.com/joomla/joomla-cms/issues/31695 or https://github.com/joomla/joomla-cms/issues/30711

Content jumps when selecting color picker, see:

![img](https://i.imgur.com/dqQEpdA.gif)

Just try to change the color settings in template styles.

### Expected result
Color picker should not not affect surrounding html output

### Actual result
Color picker affects surrounding html output

### System information (as much as possible)
Joomla! 4 Beta5
Chrome browser
Windows

**Comment by ChristineWk** [comment]
Hi Jan,

Confirmed: Chrome
Not confirmed: FF

4.0.0-beta6-dev / Database-version 4.0.0-2020-12-20

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31843">issues.joomla.org/tracker/joomla-cms/31843</a>.</sub>

**Comment by Quy** [comment]
Duplicate #29955?

**Comment by HLeithner** [comment]
Yes it's the same, closing this
