### ISSUE TITLE
[4.0] Media Manager Imagecrop- image zoom when resize browser window

### ISSUE THREAD

**Issue by jsr4id** [joomla/joomla-cms#31859]
### Steps to reproduce the issue

Go to **Media Manager - crop tab**, resize your browser window.

### Expected result

The image and the surrounding div should adapt to the browser size and not be zoomed.

### Actual result

Please see:
![chrome-capture](https://user-images.githubusercontent.com/19953956/103619505-2c973c00-4f32-11eb-972a-a7a9f1c7ddbd.gif)

### System information (as much as possible)

Joomla! 4.0.0-beta6-dev 
Chrome: Version 87.0.4280.88 

### Additional comments

The same behavior can be observed when zooming in and out (CTRL + mouse wheel).

**Comment by jsr4id** [comment]
Can someone recreate and label this?

**Comment by drmenzelit** [comment]
I can confirm the issue.

**Comment by PhilETaylor** [comment]
also note values turn to NaN and JS console errors:

<img width="1484" alt="113941135-7c69f580-97f6-11eb-93a8-338c89b98d84" src="https://user-images.githubusercontent.com/400092/113941512-20ec3780-97f7-11eb-89d7-be4d8b45ee72.png">

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34885 . Thanks in advance.
