### ISSUE TITLE
URL Rewrite Not Working After upgrade to Joomla 3.9.23

### ISSUE THREAD

**Issue by moojit65** [joomla/joomla-cms#31855]
On a release prior to 3.9.23 verify the URL Rewrites are working in SSL mode.  Upgrade to latest version and observe that URL rewrites not working on SSL pages.  If SSL is turned off on entire site and URL rewrites are enabled, URL rewriting works, only when SSL is required for entire site does it not work.

**Comment by HLeithner** [comment]
in 3.9.22 this works?

Which url rewrites do you mean .htaccess?

**Comment by moojit65** [comment]
Under Joomla control panel

global configuration -> "Use URL Rewriting" = YES

global configuration -> Server -> Force HTTPS = "Entire Site"

This combination no longer works.

**Comment by moojit65** [comment]
The upgrade was a bigger gap, not 3.9.22 -> 3.9.23.  How do I view 
update history to tell you the version I upgraded from?

**Comment by HLeithner** [comment]
if you use action log you have a chance that it is listed there but if the gap is bigger we don't know the version you updated from.

Is it possible that it was before 3.9.7 (released June 2019)?

**Comment by moojit65** [comment]
Yes, that's sounds close, I upgrade infrequently.

**Comment by ReLater** [comment]
> How do I view update history to tell you the version I upgraded from?

If action log is not activated in your Joomla:

If a file ` joomla_update.php` exists in ypur Joomla log folder you can find comments like

> 2020-11-25T23:52:54+00:00	INFO 77.13.168.203	update	Update started by user Super User (462). **_Old version is_** 3.9.23-dev.

in it

**Comment by moojit65** [comment]
found it in these logs

Old version is 3.9.15

**Comment by HLeithner** [comment]
can you give an example which redirect doesn't work? or could you link the site?

**Comment by moojit65** [comment]
https://www.storagewerks.net/index.php/products/datamover-storage

works now -> 
https://www.storagewerks.net/index.php/products/datamover-storage

use to work -> https://www.storagewerks.net/products/datamover-storage

**Comment by HLeithner** [comment]
Did you only upgraded Joomla or did you changed also something on the server? because it looks more like the .htaccess redirect doesn't work

**Comment by moojit65** [comment]
upgraded php to v7.3 from v5.4x

upgraded Apache to 2.4.6

upgraded OpenSSL to 1.0.2k-fips

**Comment by HLeithner** [comment]
That's a large update, please check if the .htaccess file still exists and get executed

**Comment by moojit65** [comment]
.htaccess is there w/ a 2018 date, there's a new htaccess.txt with 
Jan/2019 date corresponding with update?

**Comment by HLeithner** [comment]
I'm not so sure if the .htaccess file is loaded by apache could you change the line `IndexIgnore *` to `In dexIgnore *` then you should get a 500 internal server error. if this if you don't get an internal server error the .htaccess file is not loaded

**Comment by moojit65** [comment]
no 500 internal server error after making this change and I can access 
web pages

**Comment by HLeithner** [comment]
Then is is not a Joomla issue, it seems it's a problem with your server configuration. Please ask in the forum or at apache for help.

I'm closing this for now, you can reopen it if you find out that Joomla is the problem, but I think if you fix the .htaccess not loaded problem that Joomla works as you expect.
