### ISSUE TITLE
Unpublish category makes its custom field tab disappear and data erased

### ISSUE THREAD

**Issue by shawnhy** [joomla/joomla-cms#31869]
### Steps to reproduce the issue
Step1. Create an article sub-category under Uncategorised, named sub.
Step2. Create a category's custom field group, named test.
Step3. Create a text type category's custom field (or watever type), assign to category "Uncategorised".
Step4. Fill in category sub's custom field. Then unpublish the category and close.
Step5. Click into category sub's edit page. The test tab is disappeared.
Step6. Publish category sub, the tab comback but all data erased.

### Expected result
Un-publishing a category with custom field should work like un-publishing an article. 

### Actual result
Unpublish category makes its custom field tab disappear and data erased

### System information (as much as possible)
Joomla! 3.9.23, or eariler
php7.3x
MariaDB10.5.8-

### Additional comments
It will be alright if assign the custom field to ALL categories, or child category (sub).
This also happens in J4.0.0 beta4

**Comment by shawnhy** [comment]
Correct Step3. 
Create a text type category's custom field (or watever type), assign to category "**uncategorised**".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31869">issues.joomla.org/tracker/joomla-cms/31869</a>.</sub>

**Comment by ghost** [comment]
Issue confirmed on Joomla 4 - nightly build. 

I also assigned the custom field to the mentioned custom field group `test` but i guess this makes no difference in the behaviour.

**Comment by joomdonation** [comment]
I tried but could not procedure the issue. Could anyone tries to re-procedure it?

**Comment by brianteeman** [comment]
I cant reproduce this following the instructions
