### ISSUE TITLE
[3.9] Wrong download links in XMLs

### ISSUE THREAD

**Issue by dmitriy-cloudaccess** [joomla/joomla-cms#31860]
This issue is similar to #25487 and #25133
https://update.joomla.org/core/nightlies/next_patch_list.xml has wrong download links.
version pointed in the XML is 3.9.24-dev.
Expected value is 3.9.24-rc
Update server doesn't work because of that.

**Comment by wilsonge** [comment]
Copying @HLeithner 

But I *think* this is expected. The nightly folder always points to the latest nightly. It doesn't point to any tagged releases (e.g. RC's - although all the RC code should in the -dev build)

**Comment by HLeithner** [comment]
Yes that's expected, the nightlies doesn't use RC tags.

RCs should be at https://github.com/joomla/update.joomla.org/blob/master/www/core/test/list_test.xml but actually not for the current rc, todo should be 3.9.24-rc2 released this will end up in test/list_test.xml

Does this answer your question?

**Comment by dmitriy-cloudaccess** [comment]
It doesn't answer the question.
https://update.joomla.org/core/nightlies/next_patch_list.xml and
https://update.joomla.org/core/nightlies/next_patch_extension.xml links supposed to contain links to the latest available nightly build.
However links inside those XML-s are broken. Automatic update not possible.

**Comment by wilsonge** [comment]
Ahh @HLeithner you need to reset to development https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Version.php#L89

**Comment by HLeithner** [comment]
aah yes you are right I will fix this soon.

**Comment by HLeithner** [comment]
@dmitriy-cloudaccess should be fixed now, thanks

**Comment by dmitriy-cloudaccess** [comment]
@HLeithner The issue is back again.

**Comment by HLeithner** [comment]
fixed again... thx
