### ISSUE TITLE
[4.0] Help pages look ugly

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#31866]
I did a PR upstream to address the lack of space https://github.com/joomla/help.joomla.org/pull/20 

If someone could merge that it would really help. 

thanks

**Comment by HLeithner** [comment]
this should be fixed in the cms? This would also effect j3 or?

**Comment by brianteeman** [comment]
It can't be fixed in the cms because the way the page is served.

Because of the subtlety of the change  and the way the page is laid out in J3 there is no observable change in J3

**Comment by brianteeman** [comment]
Thanks for merging
