### ISSUE TITLE
HTML5 validator warning when using addScriptDeclaration or addStyleDeclaration

### ISSUE THREAD

**Issue by yild** [joomla/joomla-cms#31877]
### Steps to reproduce the issue

1. Set $this->setHtml5(true); in template index.php.
2. Use code:
```
 $doc = JFactory::getDocument();

 $doc->addScriptDeclaration();
 $doc->addStyleDeclaration();
```
ie. used in plugins.

3. Validate rendered page at ie. validator.w3.org.

### Expected result

No warnings after page validation when using HTML5.

### Actual result

Validation warnings with messages like:

The type attribute is unnecessary for JavaScript resources.
The type attribute is unnecessary for Style resources.

ATM functions addScriptDeclaration() and addStyleDeclaration() doesnt use $doc->isHtml5(); value to generate correct html code.

### System information (as much as possible)

Tested on Joomla! 3.9.22

**Comment by C-Lodder** [comment]
The `type` attribute isn't required for HTML5. If it's not present, the browser will treat it as a classic JS script.
You can be course set it to `type=module` or something else, depending on the type of script you're writing.

Same goes for `type=text/css` on `<style>` elements. It's simply not required.

I'd refrain from using `validator.w3.org` as it's seriously outdated.

**Comment by brianteeman** [comment]
Please retest and change the doc type to html5
![image](https://user-images.githubusercontent.com/1296369/103897945-1df48480-50ec-11eb-8780-4d744af34620.png)

**Comment by ghost** [comment]
@yild what is your experience using above comments?

**Comment by brianteeman** [comment]
This should be closed as the question as asked and answred

**Comment by Fedik** [comment]
answered
