### ISSUE TITLE
[4.0]b6 Smart search in front - Search Suggestions

### ISSUE THREAD

**Issue by mrownicki** [joomla/joomla-cms#31882]
### Steps to reproduce the issue
If you publish smart search module and enabled "Search Suggestions" site give you The requested page can't be found.
### Expected result

fix it.

### Actual result

not working.

Error:

0 Undefined method enableasset in class Joomla\CMS\WebAsset\WebAssetManager

### System information (as much as possible)

PHP 7.4.13

Joomla 4.0 beta 6

**Comment by chmst** [comment]
I cannot replicate this error. Have you installed 3rd party extensions?

**Comment by mrownicki** [comment]
> I cannot replicate this error. Have you installed 3rd party extensions?

No.

I have 2 filters but is turn off. 
I add some logging. 
`2021-01-11T08:30:08+00:00	CRITICAL 31.xxx.xxx.xxx	error	Uncaught Throwable of type BadMethodCallException thrown with message "Undefined method enableasset in class Joomla\CMS\WebAsset\WebAssetManager". Stack trace: #0 /home/xvqmcyxf/public_html/j4/templates/cassiopeia/html/mod_finder/default.php(55): Joomla\CMS\WebAsset\WebAssetManager->__call('enableasset', Array)
#1 /home/xvqmcyxf/public_html/j4/modules/mod_finder/mod_finder.php(46): require('/home/xvqmcyxf/...')
#2 /home/xvqmcyxf/public_html/j4/libraries/src/Dispatcher/ModuleDispatcher.php(54): include('/home/xvqmcyxf/...')
#3 /home/xvqmcyxf/public_html/j4/libraries/src/Dispatcher/ModuleDispatcher.php(57): Joomla\CMS\Dispatcher\ModuleDispatcher::Joomla\CMS\Dispatcher\{closure}('/home/xvqmcyxf/...', NULL)
#4 /home/xvqmcyxf/public_html/j4/libraries/src/Helper/ModuleHelper.php(293): Joomla\CMS\Dispatcher\ModuleDispatcher->dispatch()
#5 /home/xvqmcyxf/public_html/j4/libraries/src/Helper/ModuleHelper.php(166): Joomla\CMS\Helper\ModuleHelper::renderRawModule(Object(stdClass), Object(Joomla\Registry\Registry), Array)
#6 /home/xvqmcyxf/public_html/j4/libraries/src/Document/Renderer/Html/ModuleRenderer.php(97): Joomla\CMS\Helper\ModuleHelper::renderModule(Object(stdClass), Array)
#7 /home/xvqmcyxf/public_html/j4/libraries/src/Document/Renderer/Html/ModulesRenderer.php(48): Joomla\CMS\Document\Renderer\Html\ModuleRenderer->render(Object(stdClass), Array, NULL)
#8 /home/xvqmcyxf/public_html/j4/libraries/src/Document/HtmlDocument.php(589): Joomla\CMS\Document\Renderer\Html\ModulesRenderer->render('sidebar-right', Array, NULL)
#9 /home/xvqmcyxf/public_html/j4/libraries/src/Document/HtmlDocument.php(895): Joomla\CMS\Document\HtmlDocument->getBuffer('modules', 'sidebar-right', Array)
#10 /home/xvqmcyxf/public_html/j4/libraries/src/Document/HtmlDocument.php(660): Joomla\CMS\Document\HtmlDocument->_renderTemplate()
#11 /home/xvqmcyxf/public_html/j4/libraries/src/Application/CMSApplication.php(1011): Joomla\CMS\Document\HtmlDocument->render(false, Array)
#12 /home/xvqmcyxf/public_html/j4/libraries/src/Application/SiteApplication.php(804): Joomla\CMS\Application\CMSApplication->render()
#13 /home/xvqmcyxf/public_html/j4/libraries/src/Application/CMSApplication.php(272): Joomla\CMS\Application\SiteApplication->render()
#14 /home/xvqmcyxf/public_html/j4/includes/app.php(63): Joomla\CMS\Application\CMSApplication->execute()
#15 /home/xvqmcyxf/public_html/j4/index.php(36): require_once('/home/xvqmcyxf/...')
#16 {main}
`
I have this error in b5 update b6. Maybe there is nothing to rely on to upgrade from version to version.

**Comment by infograf768** [comment]
afaik we have no `mod_finder` 0verride in J4 Cassiopea core.
Your error shows:
`Stack trace: #0 /home/xvqmcyxf/public_html/j4/templates/cassiopeia/html/mod_finder/default.php(55)`

**Comment by mrownicki** [comment]
@infograf768 
Yes now working. I tested earlier versions through the beta maybe then I was doing something and forgot about it. And I just overwritten the files and that was left.
OK> Close.
Ps. now. delete all and install clean.
