### ISSUE TITLE
[4b6] Inconsistent experience with dropdown

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31889]
### Steps to reproduce the issue

In safari - Joomla 4 beta 6

The experience with dropdowns is inconsistent

Some are highly styled and some are browser styled

The experience is inconsistent. 

Furthermore, some dropdowns "look styled" but when clicked fall back to browser style and even float way above the dropdown trigger click

### Expected result

Consistency of experience

### Actual result

https://user-images.githubusercontent.com/400092/104022227-ed7a1c80-51b7-11eb-9750-d69bdef5d642.mp4

https://user-images.githubusercontent.com/400092/104022363-17cbda00-51b8-11eb-88c6-45d9ae3f2fed.mp4

### System information (as much as possible)

Safari on macOS Big Sur

**Comment by chmst** [comment]
No video visible. Is this still an issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31889">issues.joomla.org/tracker/joomla-cms/31889</a>.</sub>

**Comment by PhilETaylor** [comment]
View the video on GitHub.
