### ISSUE TITLE
[4b6] media/jui/images/ajax-loader.gif 404 not found

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31888]
### Steps to reproduce the issue

Joomla b4 beta 5 to beta 6 update

after upgrade (login again) and navigate to the Joomla Update page

https://example.com/administrator/index.php?option=com_joomlaupdate

### Expected result

No 404

### Actual result

https://example.com/media/jui/images/ajax-loader.gif 404 not found.

<img width="1608" alt="Screenshot 2021-01-08 at 13 38 06" src="https://user-images.githubusercontent.com/400092/104021490-c242fd80-51b6-11eb-8b90-4303dfe671e8.png">

(Note other JS error is documented here https://github.com/joomla/joomla-cms/issues/31883) 

### System information (as much as possible)

linux based hosting
file is not there

**Comment by wilsonge** [comment]
This is all related to https://github.com/joomla/joomla-cms/issues/31490 I suspect
