### ISSUE TITLE
[4b6] Email validation inconsistent on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31891]
### Steps to reproduce the issue

Compare the "Forgot your password" and "Forgot your username" validation of the email address on the frontend of Joomla 4 beta 6

### Expected result

Consistency 

### Actual result

The Email Address validation on "Forgot your username" is Javascript based and onBlur of the field, you cannot submit the form until the field value is validated by JS.

<img width="283" alt="Screenshot 2021-01-08 at 14 11 04" src="https://user-images.githubusercontent.com/400092/104024649-5e6f0380-51bb-11eb-9029-3702f5542e5c.png">

The Email Address validation on "Forgot your password" has no onBlur Javascript validation, and only validates after the form is submitted.

<img width="500" alt="Screenshot 2021-01-08 at 14 11 36" src="https://user-images.githubusercontent.com/400092/104024705-7181d380-51bb-11eb-8b14-429d826f4f54.png">

### System information (as much as possible)

Safari on Mac

### Additional comments
no JS errors in console.

**Comment by wilsonge** [comment]
PR https://github.com/joomla/joomla-cms/pull/31897
