### ISSUE TITLE
[3] User Enumeration on frontend "Forgot your username"

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31893]
### Steps to reproduce the issue

Joomla 4 beta 6 tested
Frontend click "Forgot your username"

Enter a syntax valid email address of a non-registered user - Eg No-Such-Email@example.com
Click Submit

### Expected result

"If a user was found with that email address, then we have sent them an email"

### Actual result

User Enumeration ability based on response. 

"Reminder failed: User not found."

<img width="360" alt="Screenshot 2021-01-08 at 14 22 22" src="https://user-images.githubusercontent.com/400092/104025707-ee617d00-51bc-11eb-9683-b990b4c094fb.png">

### Additional comments

Note that if you use a email address of a registered user you get a different message

<img width="510" alt="Screenshot 2021-01-08 at 14 22 44" src="https://user-images.githubusercontent.com/400092/104025766-0507d400-51bd-11eb-8d7c-72d57474c4d8.png">

**Comment by wilsonge** [comment]
Again the remind model is line for line the same as j3 so likely exists there too and not j4 specific

**Comment by PhilETaylor** [comment]
ok well Ive emailed security@joomla.org ... fingers crossed they make it for Joomla 3.9.24 as well then....

**Comment by PhilETaylor** [comment]
Its insane that this type of security issue has been around for years though....

**Comment by wilsonge** [comment]
Ancient PR https://github.com/joomla/joomla-cms/pull/30787
