### ISSUE TITLE
[4b6] Override created message twice 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31894]
### Steps to reproduce the issue

Create an override in Joomla 4 admin 

### Expected result

"Override created in /templates/cassiopeia/html/mod_banners"

### Actual result

Two messages - one is enough! 

<img width="1031" alt="Screenshot 2021-01-08 at 14 28 36" src="https://user-images.githubusercontent.com/400092/104026432-ce7e8900-51bd-11eb-9fec-3d288783b081.png">

**Comment by HLeithner** [comment]
Good first issue hint.

remove the if in file administrator/components/com_templates/src/Controller/TemplateController.php on line 418 and only keep the function to createOverride.

**Comment by joomdonation** [comment]
Made PR https://github.com/joomla/joomla-cms/pull/32340 to fix this small issue.

**Comment by alikon** [comment]
please test #32340
