### ISSUE TITLE
[4b6] TypeError: null is not an object (evaluating 'document.getElementById('totp-qrcode').innerHTML = qr.createImgTag(4)')

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31890]
### Steps to reproduce the issue

Install Joomla 4 beta 6
Login to FRONTEND as Joomla admin
Navigate to VIEW (not edit) your profile on the FRONTEND

### Expected result

No JS errors 

### Actual result

TypeError: null is not an object (evaluating 'document.getElementById('totp-qrcode').innerHTML = qr.createImgTag(4)')

<img width="777" alt="Screenshot 2021-01-08 at 13 57 06" src="https://user-images.githubusercontent.com/400092/104023327-68900280-51b9-11eb-8819-3d474f3b44b8.png">

### System information (as much as possible)

Safari on mac

### Additional comments

2FA IS NOT set up for this user

**Comment by wilsonge** [comment]
Fix https://github.com/joomla/joomla-cms/pull/31907
