### ISSUE TITLE
[4b6] A cell must be a TableCell, a scalar or an object implementing "__toString()", "array" given.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31896]
### Steps to reproduce the issue

Joomla 4 beta 6 tested 

`php joomla.php config:get`

### Expected result

No php errors

### Actual result

`A cell must be a TableCell, a scalar or an object implementing "__toString()", "array" given.`

<img width="1138" alt="Screenshot 2021-01-08 at 16 53 07" src="https://user-images.githubusercontent.com/400092/104042150-0099e600-51d2-11eb-9039-c3a103fe7125.png">

### System information (as much as possible)

Standard cPanel based server running PHP `PHP 7.4.13 (cli) (built: Dec 23 2020 11:21:05) ( NTS )` command line

**Comment by wilsonge** [comment]
![image](https://user-images.githubusercontent.com/1986000/104042945-ff1ced80-51d2-11eb-89fa-4e2f9e776e4c.png)

Cannot reproduce (screenshot continues but I'm redacting the rest of my settings :) ). I need some more information. My guess is it's something related to the exact contents of the config file or something :/

There's a bunch of PHP Notices if you run this without having a valid install. But not that symfony error

**Comment by brianteeman** [comment]
Cannot reproduce
![image](https://user-images.githubusercontent.com/1296369/104044266-fc22fc80-51d4-11eb-8152-e22155330b68.png)

**Comment by PhilETaylor** [comment]
well the only thing I have done otherwise is install Akeeba Backup.

**Comment by PhilETaylor** [comment]
yup something strange in configuration.php 

```
public $execution = array('datetime' => '2020-06-29 22:34:47', 'timestamp' => 1593470087, 'microtimestamp' => 1593470087.0546);
```

Closing as no idea what/who managed to get that into configuration.php!

**Comment by brianteeman** [comment]
No idea why @SharkyKZ re-opened this issue. The reporter closed it and without any further details re-opening it 1 month later makes no sense

**Comment by PhilETaylor** [comment]
Unless some idiot (like me) adds an array to JConfig, then this issue is resolved. As soon as someone adds an array to a setting in Joomla Global config, then this will occur again.

**Comment by PhilETaylor** [comment]
PR https://github.com/joomla/joomla-cms/pull/32971
