### ISSUE TITLE
[4][CLI] update:joomla:remove-old-files incorrectly states "files removed"

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31901]
### Steps to reproduce the issue

Repeatedly run the CLI command 

`php cli/joomla.php update:joomla:remove-old-files`

### Expected result

After the first run (or even on the first run depending on the actual result) it should say NO files removed, because the command has NOT removed files. 

### Actual result

Command's success message always states that "Files removed" which is factually incorrect. Nothing was removed. 

<img width="852" alt="Screenshot 2021-01-08 at 17 36 58" src="https://user-images.githubusercontent.com/400092/104046534-21653a00-51d8-11eb-9926-40a658f3853f.png">

### System information (as much as possible)

```
PHP 7.4.13 (cli) (built: Dec 23 2020 11:21:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
```

**Comment by alikon** [comment]
closing as we have a pr #31943
