### ISSUE TITLE
[4b6] CodeMirror Editor doest init correctly when page loads on a different tab

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31908]
### Steps to reproduce the issue

Joomla 4 beta 6 admin console.

### Set Default Editor to CodeMirror

Edit an article - save it.
Click Publishing tab. 
Click Save and close.
Click article name to edit it again
Note that we (correctly) are on the Publishing tab
Click content tab

Note:
 - No line numbers 
 - no text

Click into the content area 
Note: 
 - Line numbers now show
 - Truncated content now shows
 
Click refresh (browser window) (or as in video below, Save, to refresh the page and have it load with the content tab active)
Note: Article text loads as expected

**This effects the frontend too.** 

### Expected result

as above

### Actual result

https://user-images.githubusercontent.com/400092/104049630-309ab680-51dd-11eb-8624-b723a60d48f7.mp4

### System information (as much as possible)

Safari on macOs

**Comment by cloudfaction** [comment]
sorry!

**Comment by PhilETaylor** [comment]
Don't be sorry ;) Can you replicate this exactly as I describe?

**Comment by cloudfaction** [comment]
yes, but also my problem, that the line number overlap.

**Comment by brianteeman** [comment]
Please test #32083
