### ISSUE TITLE
[4] Calling Joomla /index.php using PHP command line gives errors.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31902]
### Steps to reproduce the issue

install Joomla 4 as normal

At command line run 

`php index.php`

(Thats the /index.php file and not a command file or anything in /cli, do not be confused)

(Believe it or not, People do this. They use it for things like cron jobs in custom extensions etc)

### Expected result

Nothing returned from the request (like Joomla 3) 

### Actual result

```
Notice: Undefined index: HTTP_HOST in /home/joomla4beta1/public_html/libraries/src/Uri/Uri.php on line 103
<script>document.location.href="https:\/\/..\/index.php";</script>
```

<img width="791" alt="Screenshot 2021-01-08 at 17 40 25" src="https://user-images.githubusercontent.com/400092/104046834-9afd2800-51d8-11eb-8cfa-436bfec2041a.png">

### System information (as much as possible)

```
PHP 7.4.13 (cli) (built: Dec 23 2020 11:21:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
```

**Comment by wilsonge** [comment]
Also the case in J3. I don't consider this a bug

**Comment by PhilETaylor** [comment]
Factually incorrect. Joomla 3 doesn't do this. 

Any PHP notices are a bug in Joomla to be resolved.
