### ISSUE TITLE
[4] Calling Joomla /api/index.php using PHP command line gives errors.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31904]
### Steps to reproduce the issue

Joomla 4
` php api/index.php`

### Expected result

No errors. Maybe a "you should use http and not cli for this endpoint" message

### Actual result

```
Notice: Undefined index: HTTP_HOST in /home/joomla4beta1/public_html/libraries/src/Uri/Uri.php on line 103
 is not a valid HTTP method.#
```

<img width="775" alt="Screenshot 2021-01-08 at 17 46 49" src="https://user-images.githubusercontent.com/400092/104047408-7fdee800-51d9-11eb-9768-038a51314442.png">

### System information (as much as possible)

```
PHP 7.4.13 (cli) (built: Dec 23 2020 11:21:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
```

**Comment by wilsonge** [comment]
This is no different to either the admin or main index.php in any Joomla version. I don't consider this a bug.

**Comment by PhilETaylor** [comment]
Well you are simply wrong. 

look at line 2 of the output. 

` is not a valid HTTP method.`

This is an invalid response and should be correctly.
