### ISSUE TITLE
[4b6] After enabling Mail Templates Format = both, Test Mail no longer works

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31919]
### Steps to reproduce the issue

Install  Joomla 4b6
in admin -> System -> Mail Templates -> Options -> set Mail Format = Both
Go to Joomla Global Config
Click Test Mail

### Expected result

An email is sent with php mail.

### Actual result

scroll up and see message:

<img width="535" alt="Screenshot 2021-01-08 at 21 29 14" src="https://user-images.githubusercontent.com/400092/104065995-90528b00-51f8-11eb-8c5a-6bb088d4cdc9.png">

**Comment by HLeithner** [comment]
@Hackwar can you have a lock at this please?

**Comment by Fedik** [comment]
Same error if set  Mail Format to "HTML".

The reason that there no HTML template, for the test message, for `com_config.test_mail`. 
Same error will be for all emails without HTML template, in `administrator/index.php?option=com_mails&view=templates`,
And vice versa, when Mail Format to "plaintext" but email template for "plaintext" is empty.


I guess we need some kind of fallback in `Joomla\CMS\Mail\MailTemplate`, something to:
```php
// Html fallback from plaintext
if (!$mail->htmlbody && $mail->body)
{
  $mail->htmlbody = nl2br($mail->body)
}

// Plaintext fallback from HTML
if (!$mail->body && $mail->htmlbody)
{
  $mail->body = strip_tags(str_replace(['<br>', '<br />'], "\n", $mail->htmlbody));
}
```

This will work if one of template is missing, and fail when both templates is empty (that is okay).

@Hackwar what do you think? I can try to make a PR

**Comment by Hackwar** [comment]
@Fedik If you have the time, please be my guest. It would be greatly appreciated. I'm currently struggling to get stuff like this done.

**Comment by Fedik** [comment]
please test #32118
