### ISSUE TITLE
[4b6] Mail Templates SMTP Authentication Doesn't use new Password hiding

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31917]
### Steps to reproduce the issue

Edit/create a new Mail Template with custom SMTP setting options

### Expected result

SMTP Authentication password should not be retrieved and should be replaced with the new modify button found in Joomla Global Config

<img width="859" alt="Screenshot 2021-01-08 at 21 25 39" src="https://user-images.githubusercontent.com/400092/104065692-15897000-51f8-11eb-9322-7e4cab988b80.png">

### Actual result

<img width="668" alt="Screenshot 2021-01-08 at 21 24 26" src="https://user-images.githubusercontent.com/400092/104065669-0acedb00-51f8-11eb-8717-52b3b934fedc.png">

**Comment by ghost** [comment]
In `Global Configuration` > `Server` > `Mail` is only `Modify`, no Password hiding:

![grafik](https://user-images.githubusercontent.com/78906980/114535065-f1eb2100-9c4f-11eb-912d-828b936a00bb.png)

**Comment by PhilETaylor** [comment]
This issue is about the field in the new "Mail Templates" extension feature and not the Joomla Global Configuration,.

**Comment by brianteeman** [comment]
Please test #33727
