### ISSUE TITLE
[4b6] Once image is inserted to content, it can no longer be edited to change details

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31910]
### Steps to reproduce the issue

Add an image into your content using the CMS Content -> Image feature in TinyMCE

Add the Image Description, Image Class, Figure Class and Figure Caption and enabled lazyloading

Save the article. 

Change your mind and return to the article.

Instinctively double click the image to edit its details.

### Expected result

A user experience that is easy to use for Joomla Content Admins to modify image information previously easy to edit. 
A web interface to modify things that were previously input in a web based form interface. 

### Actual result

Cannot edit previously added images Image Description, Image Class, Figure Class and Figure Caption or enable/disable lazy load without editing HTML source code in View Source mode.

**Comment by PhilETaylor** [comment]
hmm Joomla has a saving grace in TinyMCE that the image can be right clicked and then TinyMCE allows SOME of the details to be changed, but not all of the details.

<img width="509" alt="Screenshot 2021-01-08 at 18 38 33" src="https://user-images.githubusercontent.com/400092/104051861-b9ffb800-51e0-11eb-9885-98e4280bedf9.png">
<img width="567" alt="Screenshot 2021-01-08 at 18 38 30" src="https://user-images.githubusercontent.com/400092/104051866-bbc97b80-51e0-11eb-8664-97f348ef3b6d.png">

**Comment by bembelimen** [comment]
Also this extra parameter box in the media manager really looks bad...

**Comment by PhilETaylor** [comment]
I have another open issue for that

**Comment by Quy** [comment]
Please see https://github.com/joomla/joomla-cms/pull/34634#issuecomment-871449065

**Comment by brianteeman** [comment]
That comment has nothing to do with the issue

**Comment by PhilETaylor** [comment]
"That comment" has been deleted, leaving your comment meaning the wrong comment now :) hah

**Comment by brianteeman** [comment]
see #36962
