### ISSUE TITLE
[#30781] Small changes to jForm and jField to allow for repeatable form elements

### ISSUE THREAD

**Issue by christianostrem** [joomla/joomla-cms#3192]
I have encountered encountered several issues with the new repeatable field.
1) Its not possible to have multiple repeatable field on a administration page. Only the last one will work. This is becurse of the repeatable.js which is badly written and dosent allow to fields.

2) The fields thats inside the repeatable field is showing in a tab even tough the field has hidden as parameter.

3) The divs that created as popup when you click the button arent removed from the dom when you are finished saving data which can create memory leaks.

4) Its not possible to edit data when you have more than 4 fields inside the repeatable field on a smaler screen. (Not reponsive.)

5) I also want to suggest that the fields become sortable.

My suggestion is to completely rewrite the repeatable.js to support all of these issues.

**Comment by brianteeman** [comment]
Can this be closed now as "handled elsewhere" ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3192">issues.joomla.org/joomla-cms/3192</a>.</sub>

**Comment by brianteeman** [comment]
After over two months without response for the requested information I am closing this issue at this time. It can always be reopened if further information is provided as had been requested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3192">issues.joomla.org/joomla-cms/3192</a>.</sub>
