### ISSUE TITLE
[4b6] unwritable log_path generates out of memory errors 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31921]
### Steps to reproduce the issue

Using the bug in https://github.com/joomla/joomla-cms/issues/31920 set the $log_path value to a folder which Joomla has no write permissions outside of JPATH_BASE

Eg: `../../../../../../../../../test`

On a Mac, setting this to `/test` will also break it, but `/` is interpreted as JPATH_BASE for some reason

### Expected result

Its just logging, so should fail gracefully, or at most with a warning. 

### Actual result

```

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 69632 bytes) in /Users/phil/Downloads/Joomla_4.0.0-beta6-Beta-Full_Package/libraries/src/Log/LogEntry.php on line 121

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 65536 bytes) in /Users/phil/Downloads/Joomla_4.0.0-beta6-Beta-Full_Package/libraries/vendor/symfony/error-handler/Error/OutOfMemoryError.php on line 14

Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 65536 bytes) in Unknown on line 0
```

**Comment by joomdonation** [comment]
PR PR https://github.com/joomla/joomla-cms/pull/32339 should address this issue adds some validation to make sure log_path  is valid/writable and should address this issue.

**Comment by alikon** [comment]
please test #32339
