### ISSUE TITLE
[4b6] Path to log folder is not validated as a valid path

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31920]
### Steps to reproduce the issue

In Joomla 4 beta 6 global configuration set the "path to log folder" to `!@£$%^&*(%$£@!±@£$%^&*()&^%`

### Expected result

Expect that to be flagged as invalid or at least cleaned up

### Actual result

folder actually gets created and used 

<img width="332" alt="Screenshot 2021-01-08 at 21 33 08" src="https://user-images.githubusercontent.com/400092/104066317-21296680-51f9-11eb-9cbb-e9f7710a73ad.png">

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/32339 should address this issue

**Comment by alikon** [comment]
please test #32339
