### ISSUE TITLE
[4b6] role=presentation? when an image is decorative only. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31924]
### Steps to reproduce the issue

Using the media managers new "No description" tick box when selecting an image gives markup of

`<p><img src="images/joomla_black.png" alt="" /></p>`

<img width="332" alt="Screenshot 2021-01-08 at 22 26 31" src="https://user-images.githubusercontent.com/400092/104071231-a2d0c280-5200-11eb-93d7-38dae3b1128a.png">

however if you then right click that inserted image in TinyMCE (because intuitive double click does nothing) 

<img width="298" alt="Screenshot 2021-01-08 at 22 27 47" src="https://user-images.githubusercontent.com/400092/104071273-bf6cfa80-5200-11eb-86f1-ca1a355800b2.png">

and select "Image" context menu item you get another popup with "Image is decorative" unchecked

<img width="532" alt="Screenshot 2021-01-08 at 22 28 22" src="https://user-images.githubusercontent.com/400092/104071314-d3b0f780-5200-11eb-8906-59da9b2963cf.png">

If I then check that checkbox and click save the generated markup is now

`<p><img role="presentation" src="images/joomla_black.png" alt="" width="225" height="50" /></p>`

So the question is, should the Joomla Media Manager be adding ` role="presentation"` when the "No description" checkbox is ticked?

**Comment by PhilETaylor** [comment]
Tagging @brianteeman as it seems you were close to this?

**Comment by PhilETaylor** [comment]
This would also apply I guess to the rendering of other images with other checkboxes like these:

<img width="772" alt="Screenshot 2021-01-08 at 22 32 32" src="https://user-images.githubusercontent.com/400092/104071627-749fb280-5201-11eb-9e05-7d54799d7482.png">

**Comment by brianteeman** [comment]
role=presentation is an alternative method to alt=""

However its not as widely supported so the current code from joomla is perfectly correct<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31924">issues.joomla.org/tracker/joomla-cms/31924</a>.</sub>

**Comment by brianteeman** [comment]
This should be closed as not an issue

**Comment by chmst** [comment]
I wanted to move it to discussion but seems that github is not ready for that

**Comment by PhilETaylor** [comment]
The issue is that joomla now has two totally different ways of doing the same thing (marking an image as decorative only) that are incompatible with each other. 

Enabling through media manager doesn't add the role so tinymce doesn't believe it's a decorative image.

The quick fix would be for joomla to add the alt and the role. From my googling that is not invalid syntax and just covers all bases.

If tinymce is going to remain shipped as the default editor it makes sense to be compatible with its features 

Moving issues to discussions is a feature that has been revoked by GitHub after they found that comments were lost during the process occasionally. I hear they are recoding and that feature will return.
