### ISSUE TITLE
[4b6] Inconsistent logo sizes

### ISSUE THREAD

**Issue by alejandrovega** [joomla/joomla-cms#31936]
### What needs to be fixed
The size of the J logo in the instalation pages is about **276.8** x **55.01**:

![Joomla! - Installer page](https://user-images.githubusercontent.com/9896498/104084894-fba85700-5210-11eb-8de5-be7f4fd3c911.png)

The size of the J logo in the login page is now **148.2** x **26**:

![Joomla! - Login page](https://user-images.githubusercontent.com/9896498/104084909-22668d80-5211-11eb-9276-b29460611b0d.png)

### Why this should be fixed
After the installation process is completed, and now in the login page the dimensions cause a "jump feeling" between 2 interfaces.

### How would you fix it
To provide more consistency regardless of the process _(since we are talking about the same CMS, same default interface, different page)_, the sizes must be the same.

Of course the login page will be different if a user decides to change the template in the future, but at least this one, the template provided by default should be more consistent between the installation process and the login page.

**Comment by himanshu007-creator** [comment]
I would like to work on this issue. Please guide me how to get started.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32632 . Thanks in advance.
