### ISSUE TITLE
Get name inconsistancies in base controller and base model

### ISSUE THREAD

**Issue by venomdev** [joomla/joomla-cms#31934]
### Problem identified
The way I name my controllers and models are {{ComponentName}}Controller{{ControllerName}} and {{ComponentName}}Model{{ModelName}} so something like FruitStoreControllerApples and FruitStoreModelApples.

What I've noticed is using getName() in the model returns Apples and getname() in the controller returns FruitStore, this means every controller returns FruitStore instead of the intended controller name.

here's the 2 lines in question

Controller: https://github.com/joomla/joomla-cms/blob/bd4a56ea40047113a8d8b2ceb2689542f9c03a7e/libraries/src/MVC/Controller/BaseController.php#L773

Model: https://github.com/joomla/joomla-cms/blob/bd4a56ea40047113a8d8b2ceb2689542f9c03a7e/libraries/src/MVC/Model/BaseDatabaseModel.php#L414

### Proposed solution
I believe it's a simple regex fix

**Comment by joomdonation** [comment]
Although the method is getName(), it is actually used to return name of the component. If you **fix** it, everything will be broken. See some of it usages and you will understand:

- https://github.com/joomla/joomla-cms/blob/staging/libraries/src/MVC/Controller/AdminController.php#L81
- https://github.com/joomla/joomla-cms/blob/staging/libraries/src/MVC/Controller/BaseController.php#L836
....

So better leave it as how it is for now.

**Comment by richard67** [comment]
Closing as expected behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31934">issues.joomla.org/tracker/joomla-cms/31934</a>.</sub>

**Comment by venomdev** [comment]
Thanks for the clarification, I've since used the model name for my needs.
