### ISSUE TITLE
[J4-Beta7] lack of <span itemprop = "name"> tag in the Articles - Categories module

### ISSUE THREAD

**Issue by adj9** [joomla/joomla-cms#31942]
### Steps to reproduce the issue
Add Articles - Categories  module 
- Local pose: Top-a

Frontend side you have the list of categories with the bulleted list, but the category name is not on the bulleted list line

# FrontEnd & HTML inspection
![Schermata 2021-01-09 alle 16 48 09](https://user-images.githubusercontent.com/5918444/104096111-cb0cff80-529a-11eb-9bd1-11629c71bde4.png)

# Solution
Adding `<span itemprop="name">`

### Actual result
Text in line with the point

**Comment by brianteeman** [comment]
I can confirm the problem but I don't see how you're suggestion would fix it.
Surely all it needs is a new class, something like
```
.mod-articlescategories h4 {
    display: inline-block;
}
```

@drmenzelit

**Comment by brianteeman** [comment]
This should be closed as fixed with #31958

**Comment by richard67** [comment]
Closing as it is fixed already with pull request #31958 . Feel free to re-open if this is wrong.
