### ISSUE TITLE
Wrong placemanet of menu module edit icon

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#31975]
### Steps to reproduce the issue
Create a menu and connect a menu module. Set the modules layout to "Dropdown"
Place the module in position "menu"
Add 2 parent menuitems to the menu. Add 2 subitems to the last parent menuitem (The one to the right)
Log in - frontend.
Hold the mouse over the menu

### Expected result
The edit icon should be a little to the right of the last dropdown icon

### Actual result
The edit icon is right on top of the icon for the last dropdown, which means you cannot navigate to the submenuitems
![edit-icon-problem](https://user-images.githubusercontent.com/1399437/104119375-28529080-532f-11eb-91a7-23385e67dc76.jpg)

### System information (as much as possible)
Joomla 4 - beta 6
Cassiopeia template

**Comment by chmst** [comment]
Please attach your screen or whatever it is via the file upload. I have no access to your image.

**Comment by rbuelund** [comment]
Did that now in the post

**Comment by chmst** [comment]
Thank you. This is a known issue and we are working on it. https://github.com/joomla/cassiopeia/issues/87

**Comment by ghost** [comment]
@rbuelund thiis issue should be closed by the comment of @chmst above.
