### ISSUE TITLE
[J4-Beta7] Discrepancy between nightly build distro and github's

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#31979]
In Articles Edit, on github's distribution, tag The Author is missing:

(I used Sample Data Testing to fill it with articles and menus)

Github distrib
![j7_github](https://user-images.githubusercontent.com/490245/104122131-7d000680-5343-11eb-980c-ccbd531bf3e8.png)

nightly_build's
(I used Sample Data Blog to fill it with articles and menus)
![j7_nightly_build](https://user-images.githubusercontent.com/490245/104122122-6e195400-5343-11eb-9bda-2b718dd5c074.png)

### System information (as much as possible)
PHP 8

**Comment by brianteeman** [comment]
"The Author" comes from custom fields in the sample data plugin

**Comment by wilsonge** [comment]
As above this is just the difference between the sample data plugins

**Comment by ghazal** [comment]
I had not figured out that this is a custom field.
This a good example of what can be done with CF.
Thank you.
