### ISSUE TITLE
J4 BETA 6 - extract main menu & search position from the header .

### ISSUE THREAD

**Issue by hitaly** [joomla/joomla-cms#31973]
### Steps to reproduce the issue : 
1- add the main menu module to menu position .
2- add the search module to search position 

the main menu and the search is inside the blue header and under the logo .
the blue header become big and ugly . 

to solve this problem : 
Fix 1 : 
move the search & main menu to be Next to the logo and make the logo more small . and make the search Height more small .
fix 2 : 
extract main menu & search position from the header to be under the header div .
then add option to fixed the main menu & the search (the user can fixed header position only or fixed header and main menu + serach with 2 options to choose)!

### Actual result : 

**FIX 1**

![screen shot 2021-01-09 at 20 19 06](https://issues.joomla.org/uploads/1/01022b091d5d20a2a184ee726af45b2e.jpg)

**FIX 2**

![screen shot 2021-01-09 at 20 19 08](https://issues.joomla.org/uploads/1/4bb63eb93a50c91127aab2e7c2a3682d.jpg)

**Comment by jwaisner** [comment]
@hitaly this report is not a bug and is normal. You can change these positions by changing the module positions to get the layout you would like. You can also post on the forum if you need assistance in setting the template how you would like.
