### ISSUE TITLE
 [J4-Beta7] Assign a color to Menu "Home"

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#31980]
### Is your feature request related to a problem? Please describe.

No change of color for the icon when selecting a new Menu as "Home".

### Describe the solution you'd like

My personal option would be a change of color. Easier to identify.

Say, like:

```
.icon-home{
    color: orange !important;
}
```

**Comment by brianteeman** [comment]
Please test #33298

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33298 . Thanks in advance.
