### ISSUE TITLE
[4.0] Send Test Mail: SMTP Error! Could not authenticate

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#31981]
### Steps to reproduce the issue
Install Beta7-dev of 10 January.
Global Configuration - Server - Mail Settings
Set up SMTP using smtp.gmail.com, 587, STARTTLS, SMTP Authentication, a Gmail address and an application specific password, as instructed in the tutorial [How do I use Gmail as my mail server?](https://docs.joomla.org/How_do_I_use_Gmail_as_my_mail_server%3F "How do I use Gmail as my mail server?")
Click 'Send Test Mail'.

### Expected result
The test mail is sent successfully.

### Actual result
Error message: SMTP Error! Could not authenticate.

### System information (as much as possible)
Windows 10, Wampserver 3.2.4, Apache 2.4.46a, MySQL 8.0.22, PHP 7.4.13

### Additional comments
This function used to work previously and the same settings work now in 3.9.24-rc2 in the same workstation.

**Comment by toivo** [comment]
Please note that there seems to be a separate issue with logging. Global Configuration - Logging - Log Almost Everything was selected, the plugin System - Debug was enabled and mail category selected but no log entries were recorded.  The file administrator/logs/everything.php had not even been created.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31981">issues.joomla.org/tracker/joomla-cms/31981</a>.</sub>

**Comment by toivo** [comment]
The issue is limited to the Send Test Mail function.  The SMTP mail settings work all right because an Account Details email was sent and seen in the Gmail Sent folder after a new user was created from the back end.  

In spite of the initial issues in an out-of-the-box Beta7-dev site, the Debug function is now writing the details of the SMTP dialogue to the log file.  Here is an extract from the log everything.php with the details of the failed authentication attempt after the button Sent Test Mail was pressed.  The second file contains the SMTP authentication from the Account Details email. The email addresses were replaced.

Failure: [j4-smtp-authentication-error.txt](https://issues.joomla.org/uploads/1/4748862a1322d0b847e46e9d17013b99.txt)
Success: [j4-smtp-authentication-ok.txt](https://issues.joomla.org/uploads/1/4d15f7c0a305226b7643bc75abaed57d.txt)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31981">issues.joomla.org/tracker/joomla-cms/31981</a>.</sub>

**Comment by HLeithner** [comment]
Closing we have a pull request #31999

**Comment by campones** [comment]
hello 

was this fixed? i migrated to a new server and took that opportunity to update my joomla cms from .21 to .25 and I can't send any test smtp email, despite it's working on the former server.

**Comment by ghost** [comment]
> was this fixed?

@campones Looking at the pull request #31999 for this issue you can see it was merged:

> ![grafik](https://user-images.githubusercontent.com/78906980/114971085-f136d280-9e7b-11eb-8307-c2167bb14e0e.png)
