### ISSUE TITLE
[4b6] Pagination when used with search is showing and is redundant 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31986]
### Steps to reproduce the issue

Joomla 4 beta 6
Login to admin ->System -> Manage Plugins 
Set pagination limit to 5 items
Click number 10 in the pagination at the foot of the items to move to page 10
Search for "stat"

### Expected result

1 search result 

No pagination footer showing 10 pages and forward and back arrows

### Actual result

1 search result 

Pagination footer showing 10 pages and forward and back arrows
Pagination page links when clicked just reload the page 

<img width="1312" alt="Screenshot 2021-01-10 at 17 23 35" src="https://user-images.githubusercontent.com/400092/104130427-95364c80-5368-11eb-9e97-74a37b88143a.png">

**Comment by brianteeman** [comment]
Can not replicate

![image](https://user-images.githubusercontent.com/1296369/104131466-68853380-536e-11eb-8f81-4d94ca41007a.png)

**Comment by brianteeman** [comment]
Sorry I missed part of the test instruction
> Click number 10 in the pagination at the foot of the items to move to page 10

Issue confirmed

**Comment by bembelimen** [comment]
Closed as having a PR
