### ISSUE TITLE
[4b6] Content Vote Plugin no longer honoured when rendering an article.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31987]
### Steps to reproduce the issue

With `Testing Sample Data` installed to Joomla 4 beta 6
Enable the `Content - Vote` plugin in Joomla admin 
Visit any article on the frontend

### Expected result

The functionality provided by the `Content - Vote` plugin to be shown

### Actual result

No vote functionality

<img width="905" alt="Screenshot 2021-01-10 at 17 29 40" src="https://user-images.githubusercontent.com/400092/104130590-71273b00-5369-11eb-8ce4-a0edb303236f.png">

**Comment by brianteeman** [comment]
You forgot to set Show voting in the article options

![image](https://user-images.githubusercontent.com/1296369/104131392-ef85dc00-536d-11eb-90b0-6250fb242d8d.png)
![image](https://user-images.githubusercontent.com/1296369/104131400-f7458080-536d-11eb-98b6-17ebed7f5607.png)

**Comment by PhilETaylor** [comment]
yup - I had wrongly assumed the testing data had that on, I was wrong. Sorry.
