### ISSUE TITLE
[j4b6] banner_cradle.jpg URL Invalid in testing article

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31992]
### Steps to reproduce the issue

Install Testing Sample Data in Joomla 4 beta 6

visit the frontend -> All front end views (on right) -> Single Article

### Expected result

Image shows

### Actual result

Missing image with URL http://127.0.0.1:4444/index.php/images/sampledata/parks/banner_cradle.jpg

<img width="588" alt="Screenshot 2021-01-10 at 18 08 38" src="https://user-images.githubusercontent.com/400092/104131552-e2b5b800-536e-11eb-819e-a3ded6efe6e4.png">

### Additional comments

At first I thought it was related to https://github.com/joomla/joomla-cms/issues/31989 but it is not. Regardless of SEF setting this image doesn't load.

**Comment by PhilETaylor** [comment]
Same here in the "Article Category List"

<img width="607" alt="Screenshot 2021-01-10 at 18 12 26" src="https://user-images.githubusercontent.com/400092/104131636-74252a00-536f-11eb-9684-f27fb5289de9.png">

**Comment by PhilETaylor** [comment]
Image shows in edit mode on frontend 

<img width="652" alt="Screenshot 2021-01-10 at 18 14 09" src="https://user-images.githubusercontent.com/400092/104131659-ab93d680-536f-11eb-9234-df5448c18dfb.png">

**Comment by brianteeman** [comment]
The testing data is broken in too many ways to list.

Its not shipped with Joomla - just on github

**Comment by brianteeman** [comment]
The image doesn't load because it is no longer shipped with Joomla

**Comment by PhilETaylor** [comment]
cough cough https://github.com/joomla/joomla-cms/blob/4.0-dev/images/sampledata/parks/banner_cradle.jpg

**Comment by PhilETaylor** [comment]
Even my screenshot clearly shows it when editing the article - the image is there, the url is invalid because it has index.php in it

**Comment by brianteeman** [comment]
its a bug that its not been removed

**Comment by PhilETaylor** [comment]
Is there a plan to fix the testing data? you have been saying how bad it is for years now.

Sounds like a perfect little Google Summer of Code job....
