### ISSUE TITLE
[j4b6] Login Form Menu Item in Testing Data invalid

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#31991]
### Steps to reproduce the issue

Install Joomla 4 beta 6 with the latest Testing Sample Data

Visit frontend on in the right menu click Login Form

<img width="448" alt="Screenshot 2021-01-10 at 18 00 36" src="https://user-images.githubusercontent.com/400092/104131404-fad90780-536d-11eb-9056-5ac387f89f0b.png">

### Expected result

Link goes to the login form

<img width="642" alt="Screenshot 2021-01-10 at 18 04 06" src="https://user-images.githubusercontent.com/400092/104131439-3ecc0c80-536e-11eb-92b3-bf40dc774cfd.png">

### Actual result

<img width="743" alt="Screenshot 2021-01-10 at 18 03 53" src="https://user-images.githubusercontent.com/400092/104131434-3673d180-536e-11eb-8723-d39171425c5b.png">

### Additional comments

Note in Admin it thinks its a tag!?

<img width="204" alt="Screenshot 2021-01-10 at 18 02 22" src="https://user-images.githubusercontent.com/400092/104131413-05939c80-536e-11eb-9bcb-18127f7f5fe6.png">

**Comment by brianteeman** [comment]
The testing data is broken in many many ways. Please do not report issues with it.
