### ISSUE TITLE
[4b6] No custom class by mod_custom

### ISSUE THREAD

**Issue by Lovntola** [joomla/joomla-cms#32018]
### Steps to reproduce the issue

Add a custom modul with a Module Class paramter like XXX under Advanced.

### Expected result

the output shall be :
`<div class="mod-custom customXXX" ...`
or better:
`<div class="customXXX" ...`
I can't see any benefit to add mod-custom additional

### Actual result

`<div class="mod-custom custom" ...`

### System information (as much as possible)

the new code in J4 for mod_custom is in the default.php:
```
<div class="mod-custom custom" <?php if ($params->get('backgroundimage')) : ?> style="background-image:url(<?php echo $params->get('backgroundimage'); ?>)"<?php endif; ?>>
	<?php echo $module->content; ?>
</div>
```

before in J3 it was:
```
<div class="custom<?php echo $moduleclass_sfx; ?>" <?php if ($params->get('backgroundimage')) : ?> style="background-image:url(<?php echo $params->get('backgroundimage'); ?>)"<?php endif; ?> >
	<?php echo $module->content; ?>
</div>
```

### Additional comments
This is my first issue report on github, so I hope this report is okay.

**Comment by Quy** [comment]
See PR #17447

**Comment by Lovntola** [comment]
So far I understand is this of Bootstrap. So **$moduleclass_sfx** will complete remove too?
Sorry for my limited knowledge is there a workaround with the [Module Style] filed that a User can add a variable with a override?
I know many website owner use this for highlight a content part. And cascading Div's in the modul is not the best solution IMHO.

BTW: This is my first Issue, Are there any actions on my part necessary to close this?

**Comment by alikon** [comment]
you can close it yourself...anyway i'll do it
