### ISSUE TITLE
[4.0] Blog Layout

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32012]
Can someone please explain how a user is supposed to create a blog layout from the available options ;listed below

![image](https://user-images.githubusercontent.com/1296369/104239480-79a77080-5452-11eb-84c4-97e86261198e.png)

How do I create a simple blog view (the default from J3 and before) of 1 featured article, 4 intro articles in 2 columns and 4 links

Before answering - you can use any help or docs published at Joomla.org

**Comment by chmst** [comment]
Field descriptions are missing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32012">issues.joomla.org/tracker/joomla-cms/32012</a>.</sub>

**Comment by brianteeman** [comment]
From the little I can find the only possible descriptions would be template specific and not generic

**Comment by leoalv** [comment]
I don't know if the new Leading Class and Blog class fields are really necessary, any override can be done by adding a class in the PAGE GLASS field.

I propose adding the column options for desktops, tablets and phones. Because in J3 if you choose 3 columns on the tablets it gets too squashed.

**Comment by brianteeman** [comment]
@leoalv I believe that is resolved if you know the super secret classes that can be used here. But until someone is so kind as to actually tell the world what they are .......

**Comment by drmenzelit** [comment]
If this PR https://github.com/joomla/joomla-cms/pull/31570  get merged, we will have global classes that can be used by template developers to set columns again.
Since it is not finished, it is difficult to write it in the docs.

**Comment by brianteeman** [comment]
It's not about template developers. Its about site builders.

**Comment by leoalv** [comment]
I've always had problems with columns and many end users don't even know CSS and always ask how to solve their needs. Since then I work with an Override for Blog view and they no longer ask about the column issue. Maybe it does not matter but here I leave you the capture of how it looks.

![blog_columns](https://user-images.githubusercontent.com/5317182/104361556-9a1e0c00-54e0-11eb-8687-e30dc3a8bf32.png)

**Comment by Harmageddon** [comment]
> If this PR #31570 get merged, we will have global classes that can be used by template developers to set columns again.
> Since it is not finished, it is difficult to write it in the docs.

Hmm, not exactly. #31570 only updates the settings from J3 to the CSS classes that already exist in Cassiopeia. The columns-X and masonry-X classes already exist and can be documented and used.

**Comment by drmenzelit** [comment]
My bad, I misinterpreted the PR

**Comment by drmenzelit** [comment]
We need to copy the explanations from here https://github.com/joomla/joomla-cms/pull/18319 to the docs

**Comment by brianteeman** [comment]
> We need to copy the explanations from here #18319 to the docs

That really is not enough

It was never expected that the current situation would be the final UI https://github.com/joomla/joomla-cms/pull/18319#issuecomment-341984096

**Comment by brianteeman** [comment]
How is this not a release blocker?

A major piece of joomla functionality is currently completely unusable

**Comment by alikon** [comment]
> How is this not a release blocker?

maybe much more a document blocker
:smiley:

**Comment by brianteeman** [comment]
Thinking this can be resolved by documentation is wrong.

**Comment by chmst** [comment]
We had a anlternative PR #https://github.com/joomla/joomla-cms/pull/30910 
It was less sophisticated and brought back dependencies , which is less flexible.

**Comment by brianteeman** [comment]
#27478 should be re-opened. It was a release blocker and was only closed as there was a PR but that has been closed so the Release Blocker has not been resolved.

**Comment by alikon** [comment]
#27478 reopened

**Comment by frostmakk** [comment]
From a user perspective, this is how I would like this to work in principle.
Put the templates available modifier classes in to the templateDetails.xml, in groups they belong to.
If other template providers want to use this functionality they can do the same.

In each of the blog class fields there should be a "build" button.
This button open a dialogue form with a dropdown listing the installed front end templates.
If the selected template does not have modifier classes in the xml, inform the user that this is not available for this template.
Else, populate the dialogue form with radio buttons in groups as defined in the xml.

Column Layout
* none
o columns-1
o columns-2
o columns-3
etc etc
-----------------------------
Styling
* none
o boxed
-----------------------------
Image Location
* none
 o image-left
o image-right
o image-bottom
------------------------------

When the user has selected the preferred option in each group and hit the ok button, the selected modifier classes are written to the class field and the dialogue close.

**Comment by 200MPHMEDIA** [comment]
This is the issue that we raised a year ago, under the concept that "new users" have not idea about "classes" and their use, and the Blog Layout should have column and ordering controls built in [no classes needed], just like previous Joomla versions.  The configuration of the layouts should be controlled by selectable fields and not "classes' that novice users know nothing about.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32012">issues.joomla.org/tracker/joomla-cms/32012</a>.</sub>

**Comment by richard67** [comment]
So we have now issue #27478 and this one here, both release blockers, and both about the blog layouts, only maybe with different idea about what would be the right way to solve it. Isn't that duplicate somehow, or am I missing something? Does it need 2 issues for that?

**Comment by alikon** [comment]
just merged the #27478  here

**Comment by AlisonAMG** [comment]
This is absolutely a release blocker. And for me a J4 blocker. I don't get involved in Git but had to come and speak up about this. This takes my control as a site builder without big coding skills and leaves me at the mercy of a template to say how many columns my articles will be displayed in. How on earth is this not a massive break for migration?

**Comment by jeckodevelopment** [comment]
Agree with @AlisonAMG 
Removing the choice of the number of column makes the whole menu system loosing flexibility

**Comment by rdeutz** [comment]
I think we need to have the J3 Blog layout as legacy view for an easier update from J3. I think I am not the only one who has used a blog as base and made some overwrites for specific reasons. If we only have the css way (not a bad one to be clear) it will put some more burden on the shoulders of sitebuilder to migrate to J4.

**Comment by brianteeman** [comment]
sadly my pleas on the importance of this have fallen on deaf ears for  3 years, ever since the counters were  destroyed by people who believe you must be a front end designer and css guru to be allowed to build a web site with joomla

**Comment by sonnemondundsterne** [comment]
In my opinion, the main problem is that here the design is mixed with the logic. These settings belong to the template not to the component.

**Comment by brianteeman** [comment]
@sonnemondundsterne I suggest you think a little bit harder

**Comment by alikon** [comment]
imho this is, barely a release blocker for j4 
..cause..
no one will update to j4  from j3 on day-0
will  you do it?

**Comment by leoalv** [comment]
@sonnemondundsterne Your idea is not correct, this solution has to be implemented in the component, because com_content is not only used to display a simple blog, it is used for much more along with custom fields. And the number of columns setting is important and should remain no matter what templates you use.

I really don't understand, when you want to implement something so necessary to improve Joomla they refuse, claiming that they don't want to break anything. And when should they keep something so basic and necessary there if they don't mind breaking thousands of sites. Are they really in favor of the users? Or are they against? because if what they are talking about is that to use Joomla you have to be NASA Engineers, then let's burn everything and let's go.

**Comment by brianteeman** [comment]
@alikon it is NOT about upgrades.

**Comment by redelevencreative** [comment]
Cat blog menu link currently is amazing. Great options for a site builder to change layouts without having to delve into code

**Comment by frostmakk** [comment]
> this is, barely a release blocker for j4

Nobody in their right mind would release a new car model without a decent paint job and all the gauges and switches in place. 
I could swear there was a steering wheel here before. Maybe it's mind controlled now?
Where have all the UI people gone?

**Comment by StefanSTS** [comment]
Honestly, if the numbers of columns are not there anymore it might be better to remove the blog layout altogether and let's use the category layout only.

Suggestion 1:
Or we could just add the old number fields and have a native blog layout with simple choices for column numbers in simple drop downs. Like when children try to change it, they can do it.
Give these numbers as params to the template and let the template do the rest (classes).

Suggestion 2:
Keep the Blog Class(es) additionally, but rename them:
"Blog Class (Leading Articles)" to "Leading Articles Class",
it's the class for the leading articles,
"Blog Class" to "Intro Articles Class",
it's the class for the intro articles.

Don't call a child "Arthur" and then refer to it as Toni.

**Comment by brianteeman** [comment]
@rdeutz something like this
![image](https://user-images.githubusercontent.com/1296369/112815972-c9243280-9078-11eb-9194-9c5c16da9d05.png)

**Comment by brianteeman** [comment]
Closed - please see #32943
