### ISSUE TITLE
MySQL query_cache_type is deprecated in MySQL 5.7 and removed in 8.0

### ISSUE THREAD

**Issue by nikosdion** [joomla/joomla-cms#32019]
Joomla is setting the MySQL `query_cache_type` server system variable when Site Debug is set to Yes. However, this server system variable is [deprecated in MySQL 5.7](https://dev.mysql.com/doc/refman/5.7/en/query-cache-configuration.html) and removed as of MySQL 8.0.

When using Joomla with the PDOMySQL driver **and** the Site Debug feature is enabled **and** an extension tries to close the system database connection (which forces it to reconnect) you get an **uncatchable** Fatal Error:

```
Fatal error: Uncaught PDOException: SQLSTATE[HY000]: General error: 1193 Unknown system variable 'query_cache_type' in /.../libraries/joomla/database/driver/pdomysql.php on line 160
```

Wrapping the code that recycles the MySQL connection in a try-catch doesn't work, even if the caught exception type is Throwable.

The only solution is to fix Joomla's database driver.

On Joomla 3 this is found in the following code locations:

* https://github.com/joomla/joomla-cms/blob/4172b68dac980a85c6070511622322006e98fb5b/libraries/joomla/database/driver/mysql.php#L100-L108
* https://github.com/joomla/joomla-cms/blob/4172b68dac980a85c6070511622322006e98fb5b/libraries/joomla/database/driver/mysqli.php#L192-L200
* https://github.com/joomla/joomla-cms/blob/4172b68dac980a85c6070511622322006e98fb5b/libraries/joomla/database/driver/pdomysql.php#L158-L166

This has already been fixed on Joomla 4.

I consider this a very high priority issue since there is no viable workaround in third party code (as I said, try/catch fails to catch the exceptions thrown by PDO). Not closing the connection is not an alternative, e.g. when we need to share the PDOMySQL resource with a third party database driver. Sharing the internal resource is desirable instead of using the connection information from JConfig to open a new connection because opening yet another MySQL connection from the same PHP process to the same server is disallowed on many live hosts.

I know that probably nobody will care enough to fix it. I am filing this issue just to have public proof that the Joomla project was made aware of the issue, its nature and its solution.

**Comment by richard67** [comment]
It was not corrected in J4, it is vice versa: The issue has never been created in J4. It came into J3 with PR #20322 .

Maybe the best would be just to revert the relevant part of that PR? I don't understand anyway what's so bad in having query cache on in debug mode when it is also on in not debug mode.

**Comment by nikosdion** [comment]
So, it's worse than what my cursory glance through the code already uncovered, huh? Joomla never ceases to surprise me, in this case very negatively.

Regarding your comment, I can understand the thought process behind that misguided PR, even though I don't agree with it at all. If you are on MySQL 5 and you have the query cache enabled you could plausibly see some skewed query timings if you are doing a lot of slow selects returning very small result sets from tables which don't change often. Of course if you are actually interested in doing some profiling on your database _you should disable query cache on the server, not the client_ to begin with, like all of us profiling our queries routinely do. As a result this PR should have never been filed and for _at least_ this reason it should have never been accepted.

Let alone the fact that this PR was accepted **in 2018**. This is FIVE (5) YEARS after MySQL 5.7, which deprecated the query cache, was released and TWO (2) YEARS since MySQL 8.0 which removed the query cache was released. People who supposedly know about how databases work allegedly went over the code and attached their successful tests, despite the fact that they are endorsing a feature which uses a MySQL feature which has been deprecated and subsequently removed from MySQL itself, doing that without even a MySQL version check! Someone else pushed that merge button posthaste with no further scrutiny or accountability.

The project policy of merging after receiving any two allegedly successful tests from any two random GitHub accounts was introduced circa 2012, if memory serves, as a code quality assurance policy. However, it runs counter to the stated goal for anything other than trivial and quick HTML output fixes. If it's anything low level or architectural things get routinely broken as a result of this policy and nobody is ultimately accountable. Not the person submitting the PR, not the people submitting their test results, not the maintainer that pressed that merge button. This is insane! This is a policy with far reaching implications, including security. I've been saying that for years. Anyway, I digress.

I have been able to work around this issue in my code by detecting if it's Joomla 3, PDOMySQL is being used and the MySQL version is 8.0 or later (or completely unknown in which case I assume the worst case scenario of 8.0 or later). In this case I just tell Joomla's DB driver to disable its debug mode which resolves the issue.

**Comment by richard67** [comment]
So we could fix it this way

[https://github.com/joomla/joomla-cms/compare/staging...richard67:staging-leave-query-cache-alone-on-debug](https://github.com/joomla/joomla-cms/compare/staging...richard67:staging-leave-query-cache-alone-on-debug)

or that way

[https://github.com/joomla/joomla-cms/compare/staging...richard67:staging-fix-query-cache-in-debug-mode](https://github.com/joomla/joomla-cms/compare/staging...richard67:staging-fix-query-cache-in-debug-mode)

@wilsonge @HLeithner @zero-24 What would you prefer?

**Comment by zero-24** [comment]
Closing here now as there is now an PR: https://github.com/joomla/joomla-cms/pull/32028 please comment and test there so we can get this fixed. Thanks!

**Comment by richard67** [comment]
@zero-24 My PR is still in draft status because testing instructions need to be written, and for today I am too tired. So I suggest we leave this issue open until the PR is ready.

Update: I also think about modifying the test for availability of the query cache. So my PR is still work in progress.

**Comment by richard67** [comment]
Re-opening because PR is not ready yet.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32028 (even if it might not be the solution you like). Thanks in advance.
