### ISSUE TITLE
[3/4] PlgSystemStats should be disabled if user selects never

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32022]
### Steps to reproduce the issue

Joomla 3/4 asks for stats collection after installation.

A user can answer with a click on "NEVER" button

However this just sets a flag in the params of the plugin

### Expected result

The plugin is then disabled on clicking NEVER, so that it doesn't take up any processing time/power/cpu/ms on page load ever again to ensure Joomla remains running a peak performance but the user has the option to reenable the plugin at any time

Don't store the NEVER as a param, because if the plugin is enabled again, you want it to ask the question again so that ALWAYS or ONCE can be chosen. 

### Actual result

The PlgSystemStats plugin loads on every page load, runs some checks, takes some time, and in the end doesn't even send stats because we have said never. 

There are 7 different `if` statements run in onAfterInitialise/onAfterDispatch, several of these have 2 conditions to check, objects to retrieve etc...

Retrieving the params from the database is an extra db query that's not needed if NEVER is selected.

**Comment by infograf768** [comment]
Makes sense. But no idea how to modify as it requires a major rewrite.

**Comment by PhilETaylor** [comment]
Could just throw in a SQL query here https://github.com/joomla/joomla-cms/blob/d0b4022db5b78b97db20d4aab81968f7a7865a62/plugins/system/stats/stats.php#L157 to unpublished the plugin?

**Comment by brianteeman** [comment]
Presumably it should also therefore be unpublished if a user selects to send data once immediately after the data is sent

**Comment by PhilETaylor** [comment]
PR https://github.com/joomla/joomla-cms/pull/33150
