### ISSUE TITLE
[4b6] Accessibility Options Menu: "Grey Hues" and "Speech to Text" aren't shown in Firefox

### ISSUE THREAD

**Issue by AK-CCM** [joomla/joomla-cms#32025]
### Steps to reproduce the issue

Activate the plugin "System - Additional Accessibility Features" and click on the floating blue wheelchair icon.

### Expected result

Firefox should display the options "Grey Hues" and "Speech to Text" in the accessibility options menu too.

### Actual result

Firefox doesn't show these two menu items. In Edge (Chromium) these are visible.

### System information (as much as possible)

PHP Built On: Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Database Type: mysql
Database Version: 5.7.30-log
Database Collation: utf8_general_ci
Database Connection Collation: utf8mb4_general_ci
Database Connection Encryption: None
Database Server Supports Connection Encryption: Yes
PHP Version: 7.4.14
Web Server: Apache
WebServer to PHP Interface: cgi-fcgi
Joomla! Version: Joomla! 4.0.0-beta6 Beta [ Mañana ] 7-January-2021 18:42 GMT
User Agents:
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
Microsoft Edge/87.0.664.75 64-bit (Chromium based)

**Comment by brianteeman** [comment]
This is because firefox does not support them

**Comment by chmst** [comment]
Closing this as it is not an issue for Joomla
