### ISSUE TITLE
[4b6] User Menu: tab or section with accessibility settings is missing

### ISSUE THREAD

**Issue by AK-CCM** [joomla/joomla-cms#32023]
### Steps to reproduce the issue

The menu item "Accessibility Settings" in the "User Menu" links to "My Profile Details" but no accessibility settings are shown.

### Expected result

A tab or section with accessibility settings should be shown (please scroll to the middle of the linked page):
https://magazine.joomla.org/all-issues/july-2020/joomla-4-and-accessibility-give-back-the-web-to-everyone

### Actual result

No tab or section with accessibility settings is available.

### System information (as much as possible)

PHP Built On: Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Database Type: mysql
Database Version: 5.7.30-log
Database Collation: utf8_general_ci
Database Connection Collation: utf8mb4_general_ci
Database Connection Encryption: None
Database Server Supports Connection Encryption: Yes
PHP Version: 7.4.14
Web Server: Apache
WebServer to PHP Interface: cgi-fcgi
Joomla! Version: Joomla! 4.0.0-beta6 Beta [ Mañana ] 7-January-2021 18:42 GMT
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0 
Also tested with: Microsoft Edge/87.0.664.75 64-bit (Chromium based)

**Comment by brianteeman** [comment]
This was fixed the other day with #31884
