### ISSUE TITLE
[4] Possible to delete templates index.php file

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32026]
### Steps to reproduce the issue

forked from comment https://github.com/joomla/joomla-cms/pull/31710#issuecomment-759331245

https://user-images.githubusercontent.com/400092/104435443-4bc24900-5584-11eb-955f-3e82b441b255.mp4

### Expected result

It should be impossible to delete index.php in the web interface, like it is impossible to delete joomla.asset.json

### Actual result

index.php can be deleted - see video.

### Additional comments

// @wilsonge

**Comment by PhilETaylor** [comment]
should COM_TEMPLATES_ERROR_ASSET_FILE_DELETE not be talking about the "asset file" of `joomla.asset.json` though? and not index.php ?

**Comment by HLeithner** [comment]
I'm impressed that we try to save the user doing dumb things but OK if we protect the Json we also should protect the index.php, beside that you already said that the language file mentions the wrong filename. Should be an easy fix.

**Comment by PhilETaylor** [comment]
Someone has already changed the language file now to correct it. https://github.com/joomla/joomla-cms/pull/31939

**Comment by brianteeman** [comment]
The problem would be that if you prevent someone deleting the file you also prevent them renaming the file so that they can create a completely new index.php perhaps for a new template design

**Comment by PhilETaylor** [comment]
You don't rename index.php, you copy it to create a new file.

A site with no active template index.php will be down, and in be in error.

**Comment by brianteeman** [comment]
> A site with no active template index.php will be down, and in be in error.

Only if its the template in use

**Comment by wilsonge** [comment]
Oops. This was a bug in my previous commit. Should be fixed with https://github.com/joomla/joomla-cms/commit/97a832950eac45efa2f4987ce2c4dbfece62b02e

**Comment by PhilETaylor** [comment]
Confirmed fixed

And to be clear @brianteeman I was not asking for a new feature, I was reporting that an existing feature was no longer working and was broken. 

The code was already there 

```php
	if (base64_decode(urldecode($file)) == '/index.php')
		{
			$this->setMessage(Text::_('COM_TEMPLATES_ERROR_INDEX_DELETE'), 'warning');
			$url = 'index.php?option=com_templates&view=template&id=' . $id . '&file=' . $file;
			$this->setRedirect(Route::_($url, false));
		}
```

<img width="841" alt="Screenshot 2021-01-14 at 12 59 40" src="https://user-images.githubusercontent.com/400092/104593980-679f1b00-5668-11eb-8d13-5041155409fd.png">

**Comment by PhilETaylor** [comment]
The feature to prevent index.php being deleted was added in 2013 - gulp

```
03-Oct-2013 Michael Babker
  + [#31266] GSoC 2013 - Improved Template Manager.  Thanks Ram Tripathi
```
