### ISSUE TITLE
Tell me why the `<base>` tag repeats the address of the site itself?

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#32031]
Tell me why the **`<base>`** tag repeats the address of the site itself? 
**[https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base)**
The tag description says, the address is used to indicate relative links. Why if the site address "http://joomla-site.com/menuitem/article" then the **`<base>`** tag also has an address "http://joomla-site.com/menuitem/article"? relative links of styles, scripts, and images don't work! What if the CMS is installed in a child folder of the domain "http://site.com/joomla/" here, in general, no relative link will work, scripts and styles with relative paths will not be loaded. When developing, I got out of the situation only with absolute paths. But not everything has to sculpt an absolute path?
**`<link href="/css/style.css" >`**
and 
**`<script src="/js/script.js">`**
these paths should work even when the CMS is installed in a subfolder of the domain. http://site.com/joomla/ and the enabled seo mode should not be a hindrance to the operation of the site.. even the admin panel must have the same base address, since scripts and styles are used from the media folder of the application.

_Originally posted by @korenevskiy in https://github.com/joomla/joomla-cms/discussions/31714_

**Comment by bembelimen** [comment]
Why opening an issue, when you have a discussion already?
In Joomla! 4 is the base tag removed: https://github.com/joomla/joomla-cms/pull/25077
If you want to fix it for Joomla! 4, please create a PR, but otherwise let's stick to the discussion.
