### ISSUE TITLE
[4] Toggle Menu doesn't persist

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32032]
### Steps to reproduce the issue

Login to Joomla 4 admin 
Click Toggle Menu to collapse the left menu
refresh the page - note the left menu stays collapsed
Click Articles Quick Icon -  note the left menu stays collapsed
If you have any Articles, click one to get to the edit page, click Close to return to the list of articles -  note the left menu stays collapsed

Next, hover over the left menu, hover over the Content Icon - Click it - menu opens, that's expected.

Now refresh the page (or click a left menu item) 

### Expected result

Menu collapses again on page load
Menu stays collapsed until interacted with
Menu stays collapsed until disabled by clicking Toggle Menu

### Actual result

Menu stays open forever now until you click Toggle Menu again. 

### System information (as much as possible)

Safari on Mac.

### Additional comments

Note if you press the Home dashboard, HELP or SYSTEM left menu items when the menu is collapsed, the pages load their content correctly, AND THE MENU STAYS COLLAPSED as expected.

**Comment by HLeithner** [comment]
I don't see that as unexpected because you open a submenu (looking at the "Toggle Menu" switch which changes to open) for me it's more a pain that the menu animates the closing animation.

**Comment by PhilETaylor** [comment]
My expectation based on other apps with collapsable left menu's is that the `Menu stays collapsed until the collapse feature is disabled by clicking Toggle Menu`... so maybe its just me?

Remembering that the people collapsing the menu are likely to be on smaller devices too, so keeping the menu open would be a pain for them

I agree, the animation is annoying.

**Comment by ghost** [comment]
As @PhilETaylor wrote i would also expect in the described scenario:

> Menu collapses again on page load

**Comment by PhilETaylor** [comment]
Subjective I guess. Persistence would be nice.
