### ISSUE TITLE
[j4] [ui] editor modal size problem in page break

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#32041]
in editor when we load page break we load a big modal for 2 fields ...
![image](https://user-images.githubusercontent.com/2539440/104698143-2ca4f200-5711-11eb-9d75-0a3d9ab74c5c.png)
too many space for cursor ...
can we do dynamic height of modal for better display or its not good for ay11n ?

**Comment by chmst** [comment]
The iframe size for the modal is always the same, not only for page break.  It is adapted to the he screen size, no matter how many items are found.

**Comment by micker** [comment]
Ok dommage not realy good for eyes ...

**Comment by infograf768** [comment]
Closing as expected behavior.
