### ISSUE TITLE
[4]media manager header space after upload

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#32040]
### Steps to reproduce the issue

upload an image on media manager modal

### Expected result

A modal with a message

### Actual result

A big space on header, that doesn't hidden if we close the message
![image](https://user-images.githubusercontent.com/2539440/104697329-e4d19b00-570f-11eb-842a-4635aea95053.png)

![image](https://user-images.githubusercontent.com/2539440/104697415-03379680-5710-11eb-9e64-a065142adac1.png)

**Comment by Quy** [comment]
Duplicate #30880

**Comment by micker** [comment]
Yes i will close
