### ISSUE TITLE
Tag form field published attribute is not effective

### ISSUE THREAD

**Issue by boddunan** [joomla/joomla-cms#32065]
### Steps to reproduce the issue
Create a form field for tag type as below.

`<field name="tags" type="tag" label="JTAG" description="JTAG_DESC" multiple="true" published="1"></field>
`

This will show unpublished tags as well.

### Expected result

It should show only tags with the published status 1

### Actual result

Shows all tags including unpublished

### System information (as much as possible)

Reproducible in both Joomla 3 and Joomla 4

### Additional comments

Root cause:
src/Form/Field/TagField.php line 130
`$published = $this->element['published'] ?: array(0, 1);`

This returns an object with the attribute name as 0

However, the value was checked for numeric and array types as shown below.

```
// Filter on the published state
if (is_numeric($published))
{
  $published = (int) $published;
  $query->where($db->quoteName('a.published') . ' = :published')
    ->bind(':published', $published, ParameterType::INTEGER);
}
elseif (\is_array($published))
{
  $published = ArrayHelper::toInteger($published);
  $query->whereIn($db->quoteName('a.published'), $published);
}
```

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/issues/32065

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32332 . Thanks in advance.

**Comment by richard67** [comment]
PR is #32332 .
