### ISSUE TITLE
[4.0] Sub menu items [a11y]

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32068]
### Steps to reproduce the issue
Install the blog sample data and then log in as an admin

![image](https://user-images.githubusercontent.com/1296369/104837343-c0aac100-58ab-11eb-8c91-9296b0a73393.png)

![image](https://user-images.githubusercontent.com/1296369/104837362-e46e0700-58ab-11eb-84d1-8a4ed7f653d8.png)

The submenu is shown so there should not be any aria-hidden

This needs to be addressed when both the submenuitems are set to show or hide in the module settings

![image](https://user-images.githubusercontent.com/1296369/104837401-1aab8680-58ac-11eb-9190-1eaba47187ad.png)

**Comment by brianteeman** [comment]
Basically when sub-menu items are displayed then the aria-hidden must be removed

**Comment by richard67** [comment]
It is done by the js here: https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/mod_menu/js/menu.es6.js . Seems something's going wrong there.

**Comment by brianteeman** [comment]
I will have to pass on trying to fix it then as js is not my thing

**Comment by richard67** [comment]
I don't even understand why the default menu layout loads that js.

**Comment by chmst** [comment]
Maybe for the frontend editing of menuitems?

**Comment by brianteeman** [comment]
> Maybe for the frontend editing of menuitems?

nope thats all in frontediting.js that I am trying to kill

**Comment by chmst** [comment]
I have an idea how to do it but If you are working there, I let it to you.

**Comment by brianteeman** [comment]
@chmst no I am not looking at this as its not related to the frontend-editing and anyway I have reached the end of what I have the skills to do with that pr

**Comment by chmst** [comment]
Sorry, a misunderstanding. I was trying to kill the frontend editing of menuItems where you have opened a draft. 

I don't know why mod_menu/js/menu.es6.js sets aria-hidden.

**Comment by brianteeman** [comment]
> Sorry, a misunderstanding. I was trying to kill the frontend editing of menuItems where you have opened a draft.

happy to kill that

**Comment by Krshivam25** [comment]
Hi, @brianteeman is this issue is still open can I work into this.?

**Comment by ghost** [comment]
@Krshivam25 

(Edit, 2021-04-13:)
> is this issue is still open

Looking at the Dev-Tools/Inspector shows the issue @brianteeman reported. (Edit-End.)

> can I work into this.?

please read https://github.com/joomla/joomla-cms/issues/31540#issuecomment-811070565

**Comment by brianteeman** [comment]
Closing as this appears to have been resolved elsewhere
