### ISSUE TITLE
[4] "1 moderate severity vulnerability" urijs  <=1.19.3

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32073]
### Steps to reproduce the issue

`npm i`

### Expected result

No security issues 

### Actual result

```
node_modules/urijs

1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

urijs  <=1.19.3
Severity: moderate
Hostname spoofing via backslashes in URL - https://npmjs.com/advisories/1595
```

### System information (as much as possible)

macOS

### Additional comments

`npm audit fix` fixes the problem but increments the `lockfileVersion` to `2` and touches almost every line so probably not what you want me to submit as a PR... maybe someone more experienced in `npm` can advise.

**Comment by brianteeman** [comment]
1. We need a proper system to deal with these - they happen all the time and we shouldnt be doing this manually
2. Its not audit fix that is changing it to lockfile 2 but your version of node

**Comment by PhilETaylor** [comment]
` node -v
v15.6.0`

I.e "up to date" :-)

**Comment by brianteeman** [comment]
Exactly but until this is changed
```
  },
  "engines": {
    "node": ">=10.19",
    "npm": ">=6.13.4"
  },
```

**Comment by wilsonge** [comment]
Technically it's the npm version rather than node. npm 7 contains the new package lock (but is shipping with node 15 by default). If you swap back to the npm LTS version (6.14.11) then you'll get package v1. And yes indeed we should update package.json to stop people trying with npm 7 for now until npm 7 goes stable

**Comment by brianteeman** [comment]
my mistake confusing the node and npm as the cause

**Comment by wilsonge** [comment]
Fixed the package. I don't wanna upgrade my npm version to find out what breaks tonight having just merged the bs5 stuff. so leaving this open to cover that

**Comment by brianteeman** [comment]
I think this can be closed now @wilsonge

**Comment by brianteeman** [comment]
This should be closed as it is resolved
