### ISSUE TITLE
Codemirror overlaps code on chrome

### ISSUE THREAD

**Issue by cloudfaction** [joomla/joomla-cms#32074]
### Steps to reproduce the issue

use a module with a code mirror field, and use chrome

### Expected result

see the code you want to edit

### Actual result

the code-mirror line numbers(gray on left) overlap the actual code

### System information (as much as possible)

chrome / Mac OS / Joomla 4 B7

### Additional comments

See screenshot
![Screenshot 2021-01-18 at 17 28 31](https://user-images.githubusercontent.com/9592171/104940873-9db70480-59b2-11eb-9966-50815c77017f.jpg)

**Comment by cloudfaction** [comment]
add css to .CodeMirror-scroll: 
.CodeMirror-Scroll{ padding-left: 30px }
fixed it for me.

**Comment by PhilETaylor** [comment]
duplicate of one of my reports.

**Comment by PhilETaylor** [comment]
see https://github.com/joomla/joomla-cms/issues/31908

**Comment by brianteeman** [comment]
Could not replicate on windows using chrome

![image](https://user-images.githubusercontent.com/1296369/105029742-a5c28300-5a4a-11eb-85f1-fb9ed723193e.png)

**Comment by brianteeman** [comment]
Correction I see the problem now and its apparently quite a common issue with codemirror. https://github.com/codemirror/CodeMirror/issues/3098#issuecomment-147022207

I am looking at the suggestions

**Comment by brianteeman** [comment]
Please test #32083

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32083 . Thanks in advance, and thanks for reporting.
