### ISSUE TITLE
Errors after updating from Joomla 3.10 Alpha 2 to Joomla 4 Beta 4 

### ISSUE THREAD

**Issue by GODpleasers** [joomla/joomla-cms#32089]
### Steps to reproduce the issue

So after taking the steps to upgrade from Joomla 3.10 Alpha 2 to Joomla 4 Beta 4 I get a error in both the front end and the back end. 

### Actual result
Back end error see image...

![screen shot 2021-01-20 at 00 31 21](https://issues.joomla.org/uploads/1/cd9a4244cc63b1284770a358bf397186.png)

Front end error
https://issues.joomla.org/uploads/1/47acd43e7391ed196580eb2056109369.png

https://issues.joomla.org/uploads/1/cd9a4244cc63b1284770a358bf397186.png

**Comment by GODpleasers** [comment]
Front end error...![screen shot 2021-01-20 at 00 38 11](https://issues.joomla.org/uploads/1/f43cf92aab360fc4da9978766e0f1f9f.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32089">issues.joomla.org/tracker/joomla-cms/32089</a>.</sub>

**Comment by zero-24** [comment]
Hi @GODpleasers 

this is an known and already documented issue: https://docs.joomla.org/J4.x:Upgrade_to_4.0_Beta_4, that docs page als has the documentation on how to fix the issue.

**Comment by GODpleasers** [comment]
https://docs.joomla.org/J4.x:Upgrade_to_4.0_Beta_4

How do you do what that link says?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32089">issues.joomla.org/tracker/joomla-cms/32089</a>.</sub>

**Comment by zero-24** [comment]
In the how to fix section you find the cide to execute on the database most likely this is phpmyadmin.

**Comment by GODpleasers** [comment]
Oh OK i went to phpmyadmin clicked on the data base and the SQL tab and entered the commands in the article. And it didn't change any thing. Why is this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32089">issues.joomla.org/tracker/joomla-cms/32089</a>.</sub>

**Comment by zero-24** [comment]
Have you replaced `#__` with your database prefix as mention on the docs page?

**Comment by GODpleasers** [comment]
> 
> 
> Have you replaced `#__` with your database prefix as mention on the docs page?

Yes in Joomla! 3.10.0-alpha4 the exact codes i entered (one line at a time) were...
ALTER TABLE `jos0p_extensions` ADD COLUMN `custom_data` text NOT NULL;
ALTER TABLE `jos0p_template_styles` ADD COLUMN `inheritable` tinyint(1) NOT NULL DEFAULT 0;
ALTER TABLE `jos0p_template_styles` ADD COLUMN `parent` varchar(50) DEFAULT '';`

and all 3 of them gave the same type of error message and the the J4 update came off with the same error when it was done.
![php my admin error](https://user-images.githubusercontent.com/13956002/105210728-4626af00-5b00-11eb-90b6-94ece07da247.PNG)

**Comment by zero-24** [comment]
Ah ok understood now. That statments are not the problem but there seems to be a plugin installed that is not yet Joomla 4 compatible can you show us the 3.10 pre upgrader checker results? You might can get a deeper look into what is causing the issue by enabeling debug mode.

**Comment by GODpleasers** [comment]
> 
> 
> Ah ok understood now. That statments are not the problem but there seems to be a plugin installed that is not yet Joomla 4 compatible can you show us the 3.10 pre upgrader checker results? You might can get a deeper look into what is causing the issue by enabeling debug mode.

Oh can you please come take a look for your self we will give admin access for this.

**Comment by zero-24** [comment]
Better please create a backup and send it to tobias.zulauf[at]community.joomla.org

**Comment by GODpleasers** [comment]
It would help if you could  take a look we have tried this about :-( 1000 times  it seems like :-(  with no success.

**Comment by GODpleasers** [comment]
> 
> 
> Better please create a backup and send it to tobias.zulauf[at]community.joomla.org

Sorry Don't under stand how to send this.

**Comment by zero-24** [comment]
Please create a backup and send me the zip file so that i can run and test that system and try to reproduce the issue mention here.

**Comment by GODpleasers** [comment]
> 
> 
> Please create a backup and send me the zip file so that i can run and test that system and try to reproduce the issue mention here.

Don't understand how to do this I know how to do a akeeba backup that's about it.

**Comment by zero-24** [comment]
yes please do a backup and send it to the mail mentiond :)

**Comment by GODpleasers** [comment]
> 
> 
> yes please do a backup and send it to the mail mentioned :)

I don't think we can email that big of a file size what do we do?

**Comment by zero-24** [comment]
Please upload the package to: https://cloud.tobias-zulauf.de/index.php/s/CisFSyj3NFjQF4R

**Comment by GODpleasers** [comment]
Would it be easier if you logged into our back end and took a look?
> 
> 
> Please upload the package to: https://cloud.tobias-zulauf.de/index.php/s/CisFSyj3NFjQF4R

Ok its uploading as we speak. Taking a while.

**Comment by GODpleasers** [comment]
How long should it take to upload?
The file size  is 1.50 gb

**Comment by GODpleasers** [comment]
Hello zero-24 

That will not upload, anyhow as I was saying wouldn't it be quicker if you could just log in to our back end and take a look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32089">issues.joomla.org/tracker/joomla-cms/32089</a>.</sub>

**Comment by GODpleasers** [comment]
Hello any one there that can log in to our back end and take a look at why this wont work?

**Comment by zero-24** [comment]
My best guess is that there is an extension installed that is not yet Joomla 4 compatible and is breaking the upgrade process. Please disable all non-core extensions (tip sort the extensions by ID and disable any that have an ID that higher than 10000) than do the upgrade and check whether the upgrade itself worked. When that is the case enable the 3rd party extensions step by step and see once it breaks. Than please contact the developer of that extension that breaks the site for you whether they are planing to do a Joomla 4 version of the extension.

When the upgrade run successfully than this is most lickly not an issues within the core system. When you need special assistance with your installed extensions that cause a problem please check the forum: https://forum.joomla.org

**Comment by GODpleasers** [comment]
> 
> 
> My best guess is that there is an extension installed that is not yet Joomla 4 compatible and is breaking the upgrade process. Please disable all non-core extensions (tip sort the extensions by ID and disable any that have an ID that higher than 10000) than do the upgrade and check whether the upgrade itself worked. When that is the case enable the 3rd party extensions step by step and see once it breaks. Than please contact the developer of that extension that breaks the site for you whether they are planing to do a Joomla 4 version of the extension.
> 
> When the upgrade run successfully than this is most lickly not an issues within the core system. When you need special assistance with your installed extensions that cause a problem please check the forum: https://forum.joomla.org

I have tried disabling all 3rd party extensions with no luck.

**Comment by GODpleasers** [comment]
I just tried disable any that have an ID that higher than 10000 and still no luck.

This is obviously a bug in the upgrade that only you can fix.

An rate now it says 
Error
The template for this display is not available.
An error has occurred.

    0 Call to undefined method Joomla\Database\Mysqli\MysqliDriver::query()

**Comment by zero-24** [comment]
Please send the access data to an dedicated dev site to my mail posted above.

> The template for this display is not available.

Thats (right now) is expected and should be gone with the next navigation.

> An error has occurred.

please post a stacktrace (enable debug mode)

**Comment by GODpleasers** [comment]
> 
> 
> Please send the access data to an dedicated dev site to my mail posted above.
> 
> > The template for this display is not available.
> 
> Thats (right now) is expected and should be gone with the next navigation.
> 
> > An error has occurred.
> 
> please post a stacktrace (enable debug mode)

So I cant enable debug or any thing else since the upgrade made it totally unusable.

I'm having do restore the previous version it will,take a while.

Can you remind me of the e-mail again please?

**Comment by zero-24** [comment]
tobias.zulauf[at]community.joomla.org

**Comment by GODpleasers** [comment]
> 
> 
> tobias.zulauf[at]community.joomla.org

Just emailed it did you get it?

**Comment by zero-24** [comment]
I have just checked the site and can confirm that there are 160 extensions listed as not joomla 4 compatible (most of them are part of a bigger package). Once all 3rd party extensions are disabled the upgrade runs without any problem. So please review that list of extensions and contact the devbelopers where and when you can get a version thats joomla 4 compatible. There is not much as we can do from the core for now.

**Comment by GODpleasers** [comment]
> 
> 
> I have just checked the site and can confirm that there are 160 extensions listed as not joomla 4 compatible (most of them are part of a bigger package). Once all 3rd party extensions are disabled the upgrade runs without any problem. So please review that list of extensions and contact the developers where and when you can get a version thats joomla 4 compatible. There is not much as we can do from the core for now.

Thanks can you disable the 160  or extensions that you think are not J4 compatible for us or standing in the way?

We've tried that Several times with no luck  it would be helpful if you could. 

Then we will take a backup and try the upgrade again.

**Comment by zero-24** [comment]
I already did that. The site you sended me is now running the latest 4.0 development release. I have send you the list of extensions i disabled. In the end everything that has an ID above 10000.

I can not help any future from this point as it all depends on the extensions and its developers to provide extentsions you can use within joomla 4.

**Comment by GODpleasers** [comment]
> 
> 
> I already did that. The site you sended me is now running the latest 4.0 development release. I have send you the list of extensions i disabled. In the end everything that has an ID above 10000.
> 
> I can not help any future from this point as it all depends on the extensions and its developers to provide extentsions you can use within joomla 4.

Thank you your good wont bother you again except for the only other thing i need that list of everything that was disabled so i can test and check them off as I go.

**Comment by zero-24** [comment]
I have send it to you via mail already :-)
