### ISSUE TITLE
[4.x] SEF permalink Profile URLs

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#32080]
Hi guys,
to let users to have SEF permalink Profile URLs to their Profile page like: https://site.com/John-Ping is really a must on Joomla 4

Till few months ago Mike Feng has developed for years a small plugin for it: https://www.simbunch.com/products/profileurl
But, I don't know what happened to him, it's been 9 months since he literally disappeared !

Please, Do anyone know anything about Mike?

**Comment by ghost** [comment]
Closing #32046 which you opened 4 days ago and set the same comment here again isn't helpful. Better ask on Forums.

**Comment by bembelimen** [comment]
There is no profile link in Joomla! core.

**Comment by joomleb** [comment]
@bembelimen to add it in Joomla Core is the **feature request** I posted here...

**Comment by alikon** [comment]
then please post here https://github.com/joomla/joomla-cms/discussions

**Comment by joomleb** [comment]
Hi @alikon 
grazie da Panama (telematicamente ci conoscemmo quando naque Joomla).
I added the discussion [here](https://github.com/joomla/joomla-cms/discussions/32086)
