### ISSUE TITLE
[4.0] Codemirror keymaps (js)

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32085]
### Steps to reproduce the issue
In the codemirror plugin options select one of the alternative keymaps

### Expected result
Editor loads with that keymap

### Actual result
Editor fails to load completely
```

vim.min.js?57e071a1bc4c0d83a6fb396de6efee90:1 Uncaught ReferenceError: CodeMirror is not defined
    at vim.min.js?57e071a1bc4c0d83a6fb396de6efee90:1
    at vim.min.js?57e071a1bc4c0d83a6fb396de6efee90:1
(anonymous) @ vim.min.js?57e071a1bc4c0d83a6fb396de6efee90:1
(anonymous) @ vim.min.js?57e071a1bc4c0d83a6fb396de6efee90:1
codemirror.min.js:1 Uncaught (in promise) TypeError: Cannot read property 'attach' of undefined
    at Object.keyMap (codemirror.min.js:1)
    at new Sl (codemirror.min.js:1)
    at Sl (codemirror.min.js:1)
    at Function.Sl.fromTextArea (codemirror.min.js:1)
    at joomla-editor-codemirror.min.js:1


```

**Comment by Quy** [comment]
Duplicate #29178

**Comment by dgrammatiko** [comment]
Probably the solution is here: https://github.com/joomla/joomla-cms/pull/23426/files#diff-1ae7d38a00585728880c44a33b57e666285099ba9879ffc55b91cdb7f43fadb1R77-R83

PS. NO it's not, ignore me

**Comment by brianteeman** [comment]
> PS. NO it's not, ignore me

After an hour of playing I realised that too.
