### ISSUE TITLE
Site Title not displayed on 404-Errorpage Title

### ISSUE THREAD

**Issue by Harry5001** [joomla/joomla-cms#32097]
### Steps to reproduce the issue
Use Cassiopeia as Frontend Template. Login to Backend, open default Template Style for Frontend and select Advanced-Tab. Define a Title to be displayed instead of logo. Save settings. Open Frontend site and provoke a 404-Error to display 404-Errorpage.

### Expected result
Defined title should be displayed at top of page as on normal pages.

### Actual result
Cassiopeia Logo is displayed on top of page.

![Ashampoo_Snap_2021 01 21_19h09m14s_005_](https://user-images.githubusercontent.com/16017787/105393036-2edce400-5c1c-11eb-82a7-7e51a4e6bf84.png)

![Ashampoo_Snap_2021 01 21_19h07m00s_002_](https://user-images.githubusercontent.com/16017787/105392950-140a6f80-5c1c-11eb-88ed-d9a2b9aca93b.png)

### System information (as much as possible)
Joomla 4 BETA 6, Cassiopeia Template

**Comment by drmenzelit** [comment]
Thank you for your report, we will check the code asap.

**Comment by drmenzelit** [comment]
Closing this as we have a PR #32100
