### ISSUE TITLE
[4.0] Sub-Menu Items not displayed after BETA 6

### ISSUE THREAD

**Issue by Harry5001** [joomla/joomla-cms#32092]
### Steps to reproduce the issue
Create a Menu-Item containing a Sub-Menu Item
Open the Frontend where Menu is displayed and select the designated Menu-Item

### Expected result
The Sub-Menu Item should be displayed

### Actual result
The Sub-Menu Item is not displayed

### System information (as much as possible)
Issue occurs with Joomla 4 BETA 6, was okay in BETA 5 before rework of Template Cassiopeia in BETA 6.

**Comment by chmst** [comment]
I cannot replicate this issue. Submenus are diesplayed as usual. Please check your settings for published, view level and module params.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32092">issues.joomla.org/tracker/joomla-cms/32092</a>.</sub>

**Comment by richard67** [comment]
@Harry5001 How did you create the menu item in which menu?

Can you post a screenshot of the menu module's parameter, so we can see the settings for
- Base Item
- Start Level
- End Level
- Sub-menu Items

And in the "Advanced" parameters of the menu module, is there a menu class set? E.g. if there is menu class "menu-horizontal" set, but in the module parameters "Sub-menu Items" is set to "No", then it is default behaviour, because "Sub-menu Items"="No" doesn't make sense for a dropdown menu.

**Comment by Harry5001** [comment]
@richard67 Thank you for your answer. Here are some screenshots of the settings of the menu module's parameter as well as the menu itself. I cannot find an issue with these. The site worked fine with BETA 5 and after upgrading to BETA 6 the submenu item was not shown anymore. By the way it did not matter if the setting "Sub-menu items" was set to show or not, the submenu item was always shown when the main item has been selected. If "Sub-menu items" was set to "show" then the submenu items were always shown, no matter which main menu item has been selected. Now in no case the item is shown.

![Ashampoo_Snap_2021 01 20_22h05m00s_001_](https://user-images.githubusercontent.com/16017787/105235973-3fce1c80-5b6c-11eb-9d88-572dd448a7ea.png)

![Ashampoo_Snap_2021 01 20_22h05m23s_002_](https://user-images.githubusercontent.com/16017787/105236020-42307680-5b6c-11eb-817e-92edb596b0f5.png)

![Ashampoo_Snap_2021 01 20_22h05m35s_003_](https://user-images.githubusercontent.com/16017787/105236011-4197e000-5b6c-11eb-9919-350c54cbc2c6.png)

![Ashampoo_Snap_2021 01 20_22h06m04s_004_](https://user-images.githubusercontent.com/16017787/105236003-4197e000-5b6c-11eb-8b78-fa0ec7e60166.png)

![Ashampoo_Snap_2021 01 20_22h07m48s_005_](https://user-images.githubusercontent.com/16017787/105235996-40ff4980-5b6c-11eb-8927-2ac4a9ee0887.png)

![Ashampoo_Snap_2021 01 20_22h09m37s_006_](https://user-images.githubusercontent.com/16017787/105235985-4066b300-5b6c-11eb-9394-745c3f20bf37.png)

**Comment by richard67** [comment]
@Harry5001 Hmm, screenshots indeed look ok to me. Question: Does that issue also happen when the menu module is at some other position outside the hedaer area, i.e. not on position "menu" or "search" but e.g. on one of the the sidebar positions (in this case the menu will be vertical) or e.g. on main-top or top-a (also vertical)?

Update: I've just tested myself and it is indeed only a problem in the header area.

**Comment by richard67** [comment]
Could be even by purpose, because in the header area it will not really look good with sub-menu items expanded and not using a dropdown menu.

**Comment by ChristineWk** [comment]
Tried with Joomla 4.0.0-beta-7-dev
Submenue wasn't visible - until I changed the layout to: Dropdown (see your 3rd screenshot).
In addition I remembered this PR: https://issues.joomla.org/tracker/joomla-cms/31520 (metismenu).

![screen shot 2021-01-20 at 22 10 24](https://issues.joomla.org/uploads/1/e02084d6731b12499fe687721453de17.jpg)
![screen shot 2021-01-20 at 22 10 38](https://issues.joomla.org/uploads/1/4aca3add9f3f12a0c9076c60ab71d6e4.jpg)

(Menu class: menu-horizontal used e.g. for footer menu).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32092">issues.joomla.org/tracker/joomla-cms/32092</a>.</sub>

**Comment by chmst** [comment]
Did you copy the template while working with an older version?

**Comment by richard67** [comment]
@chmst I could reproduce the issue here on a clean, new, current 4.0-dev installation in the header area. The footer I haven't tested yet, but I assume we have the problem there, too.

**Comment by richard67** [comment]
It's a CSS issue ... the submenu items are there in HTML markup, they only have a "display: none" style from the template.css, very likely coming from the _header.scss.

**Comment by Harry5001** [comment]
> 
> 
> @Harry5001 Hmm, screenshots indeed look ok to me. Question: Does that issue also happen when the menu module is at some other position outside the hedaer area, i.e. not on position "menu" or "search" but e.g. on one of the the sidebar positions (in this case the menu will be vertical) or e.g. on main-top or top-a (also vertical)?
> 
> Update: I've just tested myself and it is indeed only a problem in the header area.

@richard67 As far as I can say, the menu IS in the position "menu", but despite of that no sub-menu item is visible in standard settings (see following screenshot). The previous screenshot skips the top most area of the site in order to prevent to show the title of the site.

![Ashampoo_Snap_2021 01 21_18h42m51s_001_](https://user-images.githubusercontent.com/16017787/105389813-985af380-5c18-11eb-829d-753a25c6abcf.png)

**Comment by ghost** [comment]
@Harry5001 i test your issue and got the impression, that https://github.com/joomla/joomla-cms/issues/32092#issuecomment-763983722 by @ChristineWk is right, which i test with and without the field `Layout: Dropdown`. 

Or do i understand your issue wrong?

**Comment by Harry5001** [comment]
@sandramay0905 As I said, I could not get the sub-menu item displayed no matter which setting I chose. I have the menu in Position "menu" (see previous post). As far as I understood the whole thing, @richard67 found a CSS-issue that caused this strange behavior?

**Comment by brianteeman** [comment]
The css issue that @richard67 refers to is when the module is in the header position so that doesn't apply to you.

The problem is very simple - from your screenshots I can see that you have the layout set to default and not dropdown - which is what everyone else has also told you. Please change that and report back. 

![image](https://user-images.githubusercontent.com/1296369/114520719-a0379c00-9c39-11eb-8e81-02be251472a3.png)

**Comment by chmst** [comment]
In the right sidebar the submenus are visible. It is intended to have no submenu items in the horizontal top menu, except with layout "dropdown"

**Comment by Harry5001** [comment]
@brienteeman I tried that setting but as this comes as a special "feature" from cassiopeia template (metismenu) and also had its very own look, I had discarded this alternative. As you can see in following screenshots the dropdown has some kind of different layout style and additionally the drop down arrows "cut off" the fonts design at the end of every item, even if there is not dropdown arrow displayed. Further study and correction of CSS would be necessary to use this method on my side in the hope to be able to solve these issues. I would prefer to have the former available technique of the dropdown available where the fonts style was taken over to the dropdown. Unfortunately I do not have a appropriate screenshot of that former version.

![menu](https://user-images.githubusercontent.com/16017787/114529275-13490e80-9c4a-11eb-8632-76ef0e05840e.png)

![menu_2](https://user-images.githubusercontent.com/16017787/114529288-1643ff00-9c4a-11eb-8403-190bd8cf38a7.png)

**Comment by brianteeman** [comment]
So it's not a bug in Cassiopeia but in your own template?

**Comment by Harry5001** [comment]
@brianteeman I use cassiopeia template.

Another thing that I think to remember is, that it was possible to setup the dropdown arrows in the initial variant were only visible when the corresponding parent menu item was selected but not before. In the "metismenu" variant the dropdown is always visible or never (in latter case a sub-menu item can never be selected).

**Comment by richard67** [comment]
> Another thing that I think to remember is, that it was possible to setup the dropdown arrows in the initial variant were only visible when the corresponding parent menu item was selected but not before. In the "metismenu" variant the dropdown is always visible or never (in latter case a sub-menu item can never be selected).

@Harry5001 That's desired behaviour and good UX. Check available dropdown menus on whatever website you can find, and they will in 99.99% of all cases always show that a dropdown is a dropdown, and not only when you have navigated to the particular parent menu item.

**Comment by Harry5001** [comment]
@richard67 Okay, if that is the desired behavior, and my site is one of the one in a thousand in which a different behavior would be more appealing, so be it. What remains was the problem described in my [https://github.com/joomla/joomla-cms/issues/32092#issuecomment-818590587](https://github.com/joomla/joomla-cms/issues/32092#issuecomment-818590587)

**Comment by chmst** [comment]
@Harry5001 this is caused by your individual design of the font. If you use a font with shadows, you must have a user.css and add some padding aoround your .metismenu a.
But this is better to ask in forum.joomla.de (if you are german). 
I close this for now, it is not a bug in joomla.

**Comment by Harry5001** [comment]
> 
> 
> @Harry5001 this is caused by your individual design of the font. If you use a font with shadows, you must have a user.css and add some padding aoround your .metismenu a.
> But this is better to ask in forum.joomla.de (if you are german).
> I close this for now, it is not a bug in joomla.

Thank you very much for your help. You always learn something new. Also when it's the right time to set up and test a new website with a new version and when it's just too early for something like that. I will do things differently in the future.
