### ISSUE TITLE
[4.0] Custom fields disabled in registration form

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#32096]
### Steps to reproduce the issue

In Users create a new Field Group
Create a couple of text fields and assign them to the newly created group. In Field Options set Editable in Both
In the front end open the User Registration page

### Expected result

Two extra fields. I used 'First name' and Last name'. The fields are present in the form. But

### Actual result

The fields are disabled and I could not find any way to enable them.

### System information (as much as possible)

Beta7-dev from 2021-01-20

**Comment by ceford** [comment]
Idiot - did not notice it can be set in Permissions

**Comment by alikon** [comment]
it happens to all of us
