### ISSUE TITLE
Upgrading to Joomla 3.9.24 is preventing pages from loading

### ISSUE THREAD

**Issue by kamaleshdubey** [joomla/joomla-cms#32108]
### Steps to reproduce the issue
1. Upgrade to Joomla 3.9.24.
2. Perform one of the following tasks from Admin Panel:
a. De-activate/Unpublish a Module
b. De-activate/Unpublish an Extension
c. Install a new Extension
3. Visit the Website URL on a browser (Edge/Chrome/Firefox/Brave).

We have tried this with the following Modules/Extensions:
i. Phoca Cart - 2.a & 2.b.
ii. Skyline Snow Falling - 2.a & 2.b.
iii. Balbooa Forms - 2.c.

### Expected result
The webpage should render correctly.

### Actual result
1. In case of 2.a & 2.b above, the pages where the Module related to the concerned Extension is added, do not load.
2. In case of 2.c above, only 404 page seems to load (when manually appending an incorrect destination page to the URL).

### System information (as much as possible)
PHP Built On	Linux uk24.siteground.eu 3.12.18-clouder0 # 1 SMP Tue Oct 9 18:14:47 EEST 2018 x86_64
Database Type	mysql
Database Version	5.6.40-84.0-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.3.23
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.9.23 Stable [ Amani ] 24-November-2020 15:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.141 Safari/537.36 Edg/87.0.664.75

### Additional comments
While searching for pointers online, I came across another user who is facing a similar issue with Breezing Forms [here](https://crosstec.org/en/forums/coding-consultancy-ideas/129189-issues-with-joomla-3-9-24.html?start=0) 

Regards
Kamalesh.

**Comment by brianteeman** [comment]
As you are hosted at siteground have you
1. cleared there extremely aggressive supercacher

**Comment by Quy** [comment]
Closing due to no response and possibly a hosting issue.
