### ISSUE TITLE
Joomla.request destroying FormData in POST request

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#32106]
### Steps to reproduce the issue

A quick pseudo code:
JS:
```javascript
var data = new FormData();
data.append('foo', 'bar');

Joomla.request({
 url: 'bla/bla/request/url',
 data: data
});
```

PHP side:
```php
var_dump($_POST);
```
Using FormData: https://developer.mozilla.org/en-US/docs/Web/API/FormData/Using_FormData_Objects

### Expected result

The dump should contain array with foo => bar

### Actual result

The dump contain random string;

### A reason

The reason of this bug is that `Joomla.request` force `'Content-Type', 'application/x-www-form-urlencoded'` for all POST data:
https://github.com/joomla/joomla-cms/blob/7b1d2ecc427182cc0ca2caa23d81cc5b85be00ac/media/system/js/core-uncompressed.js#L962-L965

However the Content-Type should be `multipart/form-data; boundary={boundary string}`. By default browser will set it correctly unles other specified.

So we should not force `application/x-www-form-urlencoded'` for all POST data.

**Comment by dgrammatiko** [comment]
I'll say deprecate the `Joomla.request` and use the Native `fetch`. 
Just for the record I think I was publicly against these (also Events) wrappers...

**Comment by Fedik** [comment]
pull request #32119
