### ISSUE TITLE
"Decrease font size" option for accessibility settings

### ISSUE THREAD

**Issue by maggus** [joomla/joomla-cms#32114]
**I would like to ask you to add a `decrease font size` option the accessibility settings.**

In the new Atum template everything seems to be "big", especially font size, buttons and lists. It is hard to get an overview over all possible settings at once, for example when creating a new article.

![screen shot 2021-01-23 at 00 01 14](https://issues.joomla.org/uploads/1/cce433a5df163857b49473eadbb7cb73.png)

Also, in the article options area I need to scroll down and down to to reach all settings. A smaller font-size, smaller gutter, smaller form elements etc. could reduce that problem.

![screen shot 2021-01-23 at 00 04 58](https://issues.joomla.org/uploads/1/f3591c5ecbbb4afad2805def2fd3fbb9.png)

I think a good bunch of people prefer getting a good overview to reading every single element in a large font size. It's good for accessibility for all people but bad for daily work. It takes to much time to scroll down and down in order to place one certain setting...

**Comment by chmst** [comment]
You can decrease font size via the accessibility plugin, your browser or an own user.css.

**Comment by ahotzler** [comment]
Hi Christiane, schade, dass wir uns so lange nicht gesehen haben.

I have activated the plg_system_accessibility and set the "Site Section" to "Admin. (Backend), but I don't see any toolbar and I can't do anything with the given key combination "CTRL+ALT+A". Do you have any idea what I am doing wrong?

**Comment by ghost** [comment]
@ahotzler i enabled the plugin on back- and frontend and got on both a new symbol (here for Frontend):

Symbol | Menu
---- | ----
![grafik](https://user-images.githubusercontent.com/78906980/114381790-d28ac000-9b8b-11eb-9048-cc7178d7d489.png) | ![grafik](https://user-images.githubusercontent.com/78906980/114381466-71fb8300-9b8b-11eb-863c-b80f18baa3ef.png)


I guess the issue is solved.

**Comment by chmst** [comment]
@ahotzler (looking forward to meet you again ,hopefully in summer) - sorry for late answer. 
Could you re-test? As @sandramay0905 writes, when the plugin is enabled, there is the a11y symbol and clicking on it (or alt + ctrl + a) opens a menu with a11y options. 
If not: Which browser are you using? Are there error messages on console?

**Comment by brianteeman** [comment]
This really should be closed as it has been answered
