### ISSUE TITLE
[3.9.24] [4.0.0-beta6] com_content ACL selected catid is not recognized

### ISSUE THREAD

**Issue by LukasHH** [joomla/joomla-cms#32117]
### Steps to reproduce the issue
I have a user group that is allowed to create, edit and publish articles in the frontend for a specified category.

User group is below "Registered", global permission are "inherited". Special permissions are "allowed" in the category.
![screen shot 2021-01-23 at 09 41 34](https://issues.joomla.org/uploads/1/2c86b7d89b110846925ccc462a8cd8d1.jpg)

### Actual result:
If a user of this group wants to create a new article, then the fields for publishing are not available.
![screen shot 2021-01-23 at 09 37 13](https://issues.joomla.org/uploads/1/ff95f09e51a09e70470bf0a4b6b36d08.jpg)

If this user wants to edit an existing article, then the fields for publishing are available and can change them.
![screen shot 2021-01-23 at 09 37 11](https://issues.joomla.org/uploads/1/a8faf72f6adba6eee633c60384a9657b.jpg)
### Expected result:
For a new post, the fields for publishing should also be available if this is set in the category permissions.

### System information (as much as possible)
Joomla 3.9.24
PHP 7.4

### Additional comments
My investigation has shown that the selected category is not recognized and therefore not its permissions.
My instructions for the authorization [https://it-conserv.de/blog/berechtigungen-fuer-ein-verein.html](https://it-conserv.de/blog/berechtigungen-fuer-ein-verein.html "Berechtigung für einen Verein")

**Comment by Sieger66** [comment]
I can confirm this issue.
See also #17812<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32117">issues.joomla.org/tracker/joomla-cms/32117</a>.</sub>

**Comment by LukasHH** [comment]
In version **4.0.0-beta6** there is the same problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32117">issues.joomla.org/tracker/joomla-cms/32117</a>.</sub>

**Comment by LukasHH** [comment]
Create a new article in **version 4.0.0-beta6** with the same settings and without enabled workflow.
![screen shot 2021-01-26 at 20 30 28](https://issues.joomla.org/uploads/1/f7056b95f1515dff4a391f2b2f5d28a2.jpg)

The state field is showing, but is disabled. After save is the state of this article not published.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32117">issues.joomla.org/tracker/joomla-cms/32117</a>.</sub>

**Comment by LukasHH** [comment]
version 4.0.0 beta6 extended<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32117">issues.joomla.org/tracker/joomla-cms/32117</a>.</sub>

**Comment by JulianR-HR** [comment]
We can confirm this issue as well. In addition to the already pointed out topics, our users within the special journalists-group are not even able to go into any created article in the backend.

As a superuser, I'm able to do all the stuff I need to do within an article, but with any other permission, I'm not even able to edit the article (see second screenshot below).

![screen shot 2021-01-26 at 21 23 49](https://issues.joomla.org/uploads/1/fd02fde84edce7560448a137096a95ef.png)
![screen shot 2021-01-26 at 21 26 24](https://issues.joomla.org/uploads/1/9b8859c3ead8ad998044897a0feaa448.png)
![screen shot 2021-01-26 at 21 28 30](https://issues.joomla.org/uploads/1/fd65f629ba7e235642248ebaf09b7f0b.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32117">issues.joomla.org/tracker/joomla-cms/32117</a>.</sub>

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/32468 should handle this issue properly for Joomla 4.

**Comment by richard67** [comment]
@joomdonation Would the fix for J3 be the same? If so, it might be better to fix it in staging, which will later be merged up to 3.10-dev and 4.0-dev anyway. Or is the fix a kind of B/C break so we can't do it in J3?

**Comment by joomdonation** [comment]
@richard67 The PR contains some improvement to our existing code (which I don't want to make change to to staging right now)

I will see if I can make a fix for staging with minimum change needed. If Yes, I will submit a separate PR for staging.

**Comment by richard67** [comment]
I understand, thanks for feedback.

As this issue here is for J3, too, I suggest we leave it open until it's clear what we will do for J3.

**Comment by joomdonation** [comment]
OK. PR https://github.com/joomla/joomla-cms/pull/32470 submitted for staging.

**Comment by richard67** [comment]
Closing as having 2 pull requests. Please test #32470 for staging and #32468 for 4.0-dev. Thanks in advance.
