### ISSUE TITLE
template  button "option" returns to wrong caller on button "close" without changes

### ISSUE THREAD

**Issue by det13** [joomla/joomla-cms#32128]
### Steps to reproduce the issue
go to system/templates:Templates(site) with shown "cassiopeia-details an files"
choose button "options"
select button "close" whitout doing any changes

### Expected result
should return to system/templates:templates(site)  with cassiopeia shown

### Actual result
returns to system/templates:styles(site)

### System information (as much as possible)
actual Joomla 4.0.0 Beta6 with sample Blog data installed an languages english(en-GB) and germna(de-DE)

### Additional comments
when selecting button "save&close" from Templates:templates(site) and button "options"
returns correctly to templates:templates(site)

**Comment by drmenzelit** [comment]
I can confirm. But we have the same behaviour in J3.

**Comment by brianteeman** [comment]
The same incorrect behaviour happens in other components eg com_menus

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/32330 should address this issue. Please test

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32330 . Thanks in advance.
