### ISSUE TITLE
RunntimeException After Installation

### ISSUE THREAD

**Issue by tboome** [joomla/joomla-cms#32129]
### Steps to reproduce the issue
After installation, select the share statistics with Joomla

### Expected result
RuntimeException:  Could not send site statistics to remote server:  Invalid data submission![screen shot 2021-01-23 at 16 00 30](https://issues.joomla.org/uploads/1/4cfa4cc9dbc49b325f8f108f05b35613.png)

**Comment by Quy** [comment]
Duplicate #32005. Please comment in the other issue. Thanks for testing/reporting.

**Comment by PhilETaylor** [comment]
PR https://github.com/joomla/joomla-cms/pull/33149
