### ISSUE TITLE
[4.0] Subform Field in table layout overlapping

### ISSUE THREAD

**Issue by marcorensch** [joomla/joomla-cms#32139]
### Steps to reproduce the issue
Create at least 7 fields and include a field of type subform and layout "joomla.form.field.subform.repeatable-table" as one of the first fields. The Backend will break the fields into multiple columns. If the Subform contains more then one field the content gets overlapped by the second or third column.

### Expected result
the table will break into a new row or even better the field gets rendered outside of the gridcols.

### Actual result
overlapping issue:
<img width="833" alt="Bildschirmfoto 2021-01-24 um 10 59 13" src="https://user-images.githubusercontent.com/11912135/105626981-00d1ec80-5e34-11eb-805d-c09165ad20d4.png">

### System information (as much as possible)
Joomla 4 beta 6

### Additional comments
Llewellynvdm has already done an interesting implementation of the form rendering in ComponentBuilder may he can help improve the actual "_mess_" about columns & control of them in the module backend. In ComponentBuilder you are able to assign fields as you like in a grid.

**Comment by Fedik** [comment]
That is usual issue with a big tables, no mater if it in `subform` or in another place.

> the table will break into a new row or even better the field gets rendered outside of the gridcols.

why it should break? It a `table` it does not break https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table


If you have a loot of fields, do not use table layout.

**Comment by marcorensch** [comment]
@Fedik : like every responsive table breaks? every  col is a row too... 

i‘m sorry but it does not change the fact that we got a unconfigurable three / two cols grid in backend forms for tablets and desktops which makes the subform table view unusable as you can see i have only 2 colums in the subform table view and it breaks the view already 


and yes in the meantime i wrote some custom css for my module backend but that should not be the solution.

**Comment by Quy** [comment]
Duplicate #29241. Thanks for the report.

**Comment by Fedik** [comment]
@marcorensch  the subform table layout was made to be a table, no more no less.
Do not expect from the table more than ...  table :wink: 

If you need some kind of grid then probably need to code a grid layout. I do not mind if someone will make it for Joomla core.
