### ISSUE TITLE
Loadmoduleid not working Joomla 4 beta 7 php 8

### ISSUE THREAD

**Issue by breebee** [joomla/joomla-cms#32149]
### Steps to reproduce the issue
Create custom module with content, create article, load article with module {loadmoduleid 120} or with mod_login or with position

** Disable all plugins except joomla authentication and cookie plugin, using default Cassiopeia template. 

### Expected result
Module loads inside article

### Actual result
Empty content

### System information (as much as possible)
Running joomla 4, beta 7, php fpm 8.0 with nginx mariadb (joomla upgraded from beta 5 - 6 - 7, only tested load module with beta 6 and 7.

### Additional comments
One side note, regular labs modules anywhere with a blank component is much better rather then modules within just articles. If its interesting for the joomla architecture you guys should consider to remove the article dependency and make joomla much more flexible. Maybe include a blank component as well for the RC.

**Comment by ReLater** [comment]
> Disable all plugins except joomla authentication and cookie plugin, using default Cassiopeia template.

> Empty content

plg_content_loadmodule must be enabled.

EDIT: If it's enabled I can't confirm this issue with current nightly J4 package and PHP8. `{loadmoduleid xyz}` works as expected.

**Comment by breebee** [comment]
I may have had a syntax problem, I have no clue why its working right now and not before.. I truly apologize for opening this ticket, and thank you for the quick response!
