### ISSUE TITLE
Akeeba Strapper

### ISSUE THREAD

**Issue by rgtr** [joomla/joomla-cms#32142]
### Steps to reproduce the issue
Moved a site that started in Joomla 1.5 to Joomla 4 beta 6
Moved a ite started in Joomla 3.9
Both have had Akeeba Admin tools and Backup from the start

### Expected result
both went well

### Actual result
backups etc.

### QUESTION
the older site has Akeeba Strapper, the newer one doesn't ... do I need it ?

### Additional comments
J4 is great. 5 sites done, 3 to go ... attempting to determine what is possible and what is not

Richard

**Comment by brianteeman** [comment]
You should ask akeeba as that is from them and not part of the joomla core

**Comment by rgtr** [comment]
Just tried to uninstall akeeba backup ... from the old site - got a whoops !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32142">issues.joomla.org/tracker/joomla-cms/32142</a>.</sub>

**Comment by ghost** [comment]
@rgtr please ask akeeba and close this issue as its not a joomla-core-issue.
