### ISSUE TITLE
[4.0] npm error on install code ELIFECYCLE

### ISSUE THREAD

**Issue by skurvish** [joomla/joomla-cms#32145]
### Steps to reproduce the issue
fresh install from 4.0-dev repo, npm ci step

### Expected result
Successful completion.

### Actual result
11855 verbose argv "/usr/bin/node" "/usr/local/bin/npm" "ci"
11856 verbose node v10.19.0
11857 verbose npm  v6.14.3
11858 error code ELIFECYCLE
11859 error errno 1
11860 error joomla@4.0.0 install: `node build/build.js --copy-assets && node build/build.js --build-pages && npm run build:bs5`
11860 error Exit status 1
11861 error Failed at the joomla@4.0.0 install script.
11861 error This is probably not a problem with npm. There is likely additional logging output above.
11862 verbose exit [ 1, true ]

**Comment by brianteeman** [comment]
please update node

**Comment by skurvish** [comment]
That appears to have solved the problem. Thank you.
