### ISSUE TITLE
[4.0] Patchtester View links invisible

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#32157]
### Steps to reproduce the issue

Open patchteseter in lateste Nightly build that uses Bootstrap 5.

### Expected result

The links to Github and Joomla Issues Tracker should be visible

### Actual result

The links are invisible

### System information (as much as possible)

Beta7-Dev nightly after 2021-01-23

### Additional comments

badge-xxxx needs to be bg-xxxx (or both for compatibility?)

**Comment by brianteeman** [comment]
This is the wrong place to report an issue with patchtester. Please close it here and report it at https://github.com/joomla-extensions/patchtester
