### ISSUE TITLE
[4.0] Tinymce plugin options bootstrap 5

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32152]
here is no "bootstrap.js.bundle" asset of a "script" type in the registry.

It is not possible to open the tinymce plugin settings due to this line

https://github.com/joomla/joomla-cms/blob/ad3e0d95a7a45b44889fdba173da27eabed1bb84/layouts/plugins/editors/tinymce/field/tinymcebuilder.php#L64

As this was originally added by @fedik and now _broken_ after changes to bootstrap js by @dgrammatiko can you guys take a look please.

**Comment by Fedik** [comment]
> As this was originally added by @Fedik 

This was just move to WebAssetManager. Bootstrap was there before.
Used for tabs.
I have no idea what there now, with BS5.

**Comment by brianteeman** [comment]
Closed (and it wasn't a release blocker)

**Comment by infograf768** [comment]
Why closing it? it is really broken...

**Comment by infograf768** [comment]
An error has occurred.

    0 There is no "bootstrap.js.bundle" asset of a "script" type in the registry. 
    
    and then multiple errors in console.

**Comment by infograf768** [comment]
forget it. there is a pr, was not obvious...
