### ISSUE TITLE
[4.0] [atum-bs5] Mobile menu toggle doesn't work

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#32161]
### Steps to reproduce the issue

View the backend on a small device and attempt to open the main menu by clicking the toggle

![Screenshot_2021-01-26 Home Dashboard - Joomla 4 - Administration](https://user-images.githubusercontent.com/2019801/105819347-f9375280-5faf-11eb-8adb-3abded8e2516.png)

### Expected result

Opens the main menu

### Actual result

Nothing happens

### System information (as much as possible)

- 4.0-dev HEAD (after npm i)

**Comment by dgrammatiko** [comment]
#32168

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32168 . Thanks in advance.
