### ISSUE TITLE
[4.0] [atum-bs5] Some other toggle doesn't work

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#32162]
### Steps to reproduce the issue

1. Go to one of the edit views in the backend
2. Reduce viewport width down to that of a mobile
3. Try and click on the cog button (top-right)

![Screenshot_2021-01-26 Users - Joomla 4 - Administration](https://user-images.githubusercontent.com/2019801/105819777-88dd0100-5fb0-11eb-84e6-df95df1335b5.png)

### Expected result

Does something

### Actual result

Does nothing

**Comment by dgrammatiko** [comment]
https://github.com/joomla/joomla-cms/pull/32168

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32168 . Thanks in advance.
