### ISSUE TITLE
[4.0] CSP article link

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#32163]
### Steps to reproduce the issue

1. Go to `administrator/index.php?option=com_config&view=component&component=com_csp`
2. Click the "Content Security Policy (CSP)" link

### Expected result

I would have thought this should direct users to https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP, but instead it links to https://scotthelme.co.uk/content-security-policy-an-introduction/

Is that wise?

**Comment by zero-24** [comment]
Well the article from scott is more directed to users, But I have no strong opinions here feel free to send a PR to change it.

**Comment by egranty** [comment]
The article from scott discussed is obsolete and contains wrong info. For example:
_`*://*.scotthelme.co.uk:*` would match any scheme on any subdomain of `scotthelme.co.uk`._
The special character `*` [is not allowed in sheme-part](http://csplite.com/csp/test62/#test). 

Mozilla's docs contains some inaccuracies too, but it's kept up to date and have a multi-lang support. I vote for MDN!

**Comment by zero-24** [comment]
PR here: https://github.com/joomla/joomla-cms/pull/32195 Thanks!
