### ISSUE TITLE
[4.0] [cassiopiea] Edit text not visible in footer

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#32164]
### Steps to reproduce the issue

1. In your Global Config, enable "Inline Editing" for modules
2. Go to the frontend of your site
3. Look at the footer `Edit` button

### Expected result

"Edit" text visible

### Actual result

"Edit" text invisible

![Untitled3](https://user-images.githubusercontent.com/2019801/105821561-e8d4a700-5fb2-11eb-9273-de1091d74227.png)

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/a3100d199cf811152c03fae32fa67ef9feb964ba
