### ISSUE TITLE
[4.0] Frontend module edit buttons needs a major styling cleanup

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#32170]
### Steps to reproduce the issue
I think we slightly rushed the merge of https://github.com/joomla/joomla-cms/pull/32070

At least on my macbook the buttons unfortunately overlap text and menu items in cases (I guess it might be better on larger screens)

### Current view
<img width="1280" alt="Screenshot 2021-01-26 at 17 49 57" src="https://user-images.githubusercontent.com/1986000/105883750-1ba48c80-5fff-11eb-9958-f12e19e86de7.png">
<img width="361" alt="Screenshot 2021-01-26 at 17 50 07" src="https://user-images.githubusercontent.com/1986000/105883756-1e06e680-5fff-11eb-8cfa-ad6a5d84a534.png">

The height of the buttons overlaps the title area - and looks scruffy. The buttons overlap text in some places (e.g. the menu - and that actually makes them unusable as the menu is on top of the button)

### System information (as much as possible)
Chrome 87, 13 inch macbook

//cc @brianteeman

**Comment by brianteeman** [comment]
As  in the original PR I explicitly stated that it needed better css. I also stated that due to poor markup certain buttons were appearing in the wrong place. There was noting wrong with the PR. The problem with the css and markup existed before and I asked for assistance.

**Comment by wilsonge** [comment]
I am aware. But it got merged. And I don't believe there are followup issues to track improving the CSS/markup. So this adds it.

**Comment by brianteeman** [comment]
Well your direct commits are no better

**Comment by wilsonge** [comment]
Also true

**Comment by richard67** [comment]
The dilemma is that if we use absolute positioning, it always might overlap here or there because we can't know the look of every kind of module to provide styling for it, but if we use relative positioning so the edit buttons don't overlap anything, the modules need more space and so the look of the site may change much, compared to not edit mode.

**Comment by chmst** [comment]
A clean solution is adding the edit button to every module in the right place. No generic solution.

**Comment by ciar4n** [comment]
@brianteeman Is displaying the 'edit' text required?

**Comment by richard67** [comment]
@wilsonge Shall we fix the [RTL issues mentioned by JM](https://github.com/joomla/joomla-cms/pull/32070#issuecomment-765315926) with the cleanup? Or shall we meanwhile make a PR just to fix RTL with what we have now, and do the cleanup after that?

**Comment by brianteeman** [comment]
> @brianteeman Is displaying the 'edit' text required?

desired not required

**Comment by ceford** [comment]
I duplicated this report because I searched the tracker using Cassiopeia as a keyword an did not find anything relevant. Something that occurred to me later: It would be nice to have a master Toggle button to to toggle all the Edit buttons and links on/off.

**Comment by drmenzelit** [comment]
@ceford you can switch off the frontend editing for modules and / or menus in the global configuration.

**Comment by chmst** [comment]
@ceford your idea is interesting - I too had the intention to suggest a master toggle on frontend. How do you think could it be made self explaining. Especially regarding B/C and all the different permissions.

**Comment by brianteeman** [comment]
It could be done like the accessibility plugin. But as we could end up with several of this type of thing we could group them together like the screenshot below. Then it is extendable by third parties as well

![image](https://user-images.githubusercontent.com/1296369/109430945-bb3cac80-79fb-11eb-9093-3d32de04718e.png)

**Comment by chmst** [comment]
Sounds interesting - but  implementing this is above my level in php/js. And not sure concerning B/C

**Comment by rdeutz** [comment]
closing because we have a PR #32757
