### ISSUE TITLE
SmartSearch (com_finder) can't find content containing compound words

### ISSUE THREAD

**Issue by Elfangor93** [joomla/joomla-cms#32186]
### Steps to reproduce the issue
1. Install fresh Joomla 3.9.x
2. Create 4 Articles containing the following content:
  - Article 1: article, sea, water, longboat, sunshine
  - Article 2: article, wave, boat, beach, sunglass
  - Article 3: article, sand, sun, iceboating, sailing
  - Article 4: article, sandstone, sunburned, desert, camel
3. Activate "Content - Smart Search" plugin
4. Index content (Backend - Components - Smart Search - Index)
5. Create frontend menu item type "Smart Search - Search"
6. Switch to frontend and go to the page of your created menu item
7. Search with the search term "boat"

### Expected result
Article 1, Article 2 and Article 3 showing up in the search results

### Actual result
Only Article 2 showing up in the search results

### System information (as much as possible)
XAMPP for Windows 7.2.28
Database Type MariaDB
Database Version 10.4.11-MariaDB
Database Collation utf8_general_ci
Webserver Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.4.9
Joomla! Version Joomla! 3.9.24

### Additional comments
With the com_search component i am able to generate the expected result. Com_search finds the three articles (Article 1, Article 2 and Article 3) as expectet.
In my understanding, the com_finder is the more advanced search and should deliver at least as good results as the com_search.

**Comment by alikon** [comment]
if you activate the "Content - Smart Search" plugin after the articles creation, then for getting results  you need to run INDEX from smart seach backend

**Comment by Elfangor93** [comment]
`Index content (Backend - Components - Smart Search - Index)`
Thats what I described in step 4.

The index was created of course.

**Comment by alikon** [comment]
Oh sorry, missed that

**Comment by chmst** [comment]
In J3, com_finder is not reliable, helas. 
In J4, com_finder has been completely reworked and and now it is a good and reliable tool. So the recommendation is using com_search in J3 and com_finder in J4.

**Comment by alikon** [comment]
the same behaviour in J4
![Screenshot from 2021-01-31 09-02-18](https://user-images.githubusercontent.com/181681/106378196-1b134980-63a3-11eb-9062-be491360028e.png)

**Comment by chrisdavenport** [comment]
Are you using the stemmer?

**Comment by brianteeman** [comment]
I can confirm this on j3 (not tested on j4 as you have shown its the same)

Yes stemmer is enabled

**Comment by chrisdavenport** [comment]
I suspect the explanation might be that "longboat" and "iceboating" don't share the same stem with "boat" according to the stemmer.

**Comment by alikon** [comment]
for those about this matter...see  #32236 too

**Comment by alikon** [comment]
let's continue on #32236
