### ISSUE TITLE
[4] Login: WebAuthn-Img shows alt

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#32182]
### Steps to reproduce the issue

![Untitled](https://user-images.githubusercontent.com/71960554/106245322-9098e180-620c-11eb-924d-31516f56111b.png)

### System information (as much as possible)

Test on launch.joomla.org, installation of today.

![image](https://user-images.githubusercontent.com/71960554/106246944-2df51500-620f-11eb-904f-d7a1fa712d28.png)

**Comment by chmst** [comment]
I cannot replicate this issue.

**Comment by ghost** [comment]
Safari:
![Screen Shot 2021-01-29 at 10 55 48](https://user-images.githubusercontent.com/71960554/106260360-a0babc00-6220-11eb-8aa6-fa9e9752bdce.png)

**Comment by infograf768** [comment]
Can't reproduce
<img width="303" alt="Screen Shot 2021-01-29 at 17 21 22" src="https://user-images.githubusercontent.com/869724/106300230-7edc2c00-6256-11eb-830e-d7e00bd979f5.png">

**Comment by ghost** [comment]
menu, not form as shown in screenshots on firefox and safari.

![106260360-a0babc00-6220-11eb-8aa6-fa9e9752bdce](https://user-images.githubusercontent.com/71960554/106301713-52c1aa80-6258-11eb-9c6b-79749ca91b26.png)

**Comment by infograf768** [comment]
That was not clear in the instructions.

Issue confirmed.

**Comment by ghost** [comment]
> That was not clear in the instructions.

The firefox-screenshot show clear the layout of menu, the safari-screenshot show clear the breadcrumbs.

**Comment by infograf768** [comment]
Please do not argue:
the breadcrumbs does not mean anythying.
also the module could have been displayed elsewhere...

Firefox:
<img width="1256" alt="Screen Shot 2021-01-29 at 18 03 20" src="https://user-images.githubusercontent.com/869724/106304982-5e16d500-625c-11eb-8986-441f7887e7c4.png">

**Comment by infograf768** [comment]
Safari

<img width="1234" alt="Screen Shot 2021-01-29 at 18 17 48" src="https://user-images.githubusercontent.com/869724/106306434-59532080-625e-11eb-8efa-d48e86bc9ffb.png">

**Comment by infograf768** [comment]
@N6REJ 

Looks like we have an issue here. Can you look at it?

**Comment by ghost** [comment]
@infograf768 Please do not argue.

**Comment by infograf768** [comment]
Closing as we have a pr https://github.com/joomla/joomla-cms/pull/32196
