### ISSUE TITLE
[4] Install language: Class 'Joomla\Component\Installer\Administrator\Model\JUri' not found

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#32183]
### Steps to reproduce the issue
test french, german (de):

![image](https://user-images.githubusercontent.com/71960554/106245822-6d226680-620d-11eb-9781-a46fce3fa573.png)

### System information (as much as possible)

Test on launch.joomla.org, installation of today.

![image](https://user-images.githubusercontent.com/71960554/106246863-1322a080-620f-11eb-91e4-fae81e9a9351.png)

**Comment by alikon** [comment]
please test #32184
