### ISSUE TITLE
Large Joomla throbber doesnt conform to brand guidelines

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32187]
### Steps to reproduce the issue

installing Joomla 4 you get a throbber

<img width="909" alt="Screenshot 2021-01-29 at 11 59 02" src="https://user-images.githubusercontent.com/400092/106273329-5fc7a500-622a-11eb-9f51-522ed1f874bc.png">

### Expected result

the colours of the Joomla logo should match the trademark brand guidelines

https://www.joomla.org/images/logos/Joomla_Brand_Manual_10-02-2005.pdf

### Actual result

The red is not red.

Also it could be argued that the faded colours are also against the guidelines, but then it would not be a throbber...

**Comment by dgrammatiko** [comment]
> The red is not red.

That's due to opacity, not much that can be done here unless the backdrop is another element (div)

**Comment by PhilETaylor** [comment]
The red is not red when at its fullest colour opacity.. 

(Even making a throbber out of a brand mark is also against the guidelines... but I doubt Joomla will enforce its own rules on itself, its too busy chasing others for misusing the mark)

**Comment by PhilETaylor** [comment]
```
@keyframes jspinner {
  0%, 40%, 100% {
    opacity: .3;
  }
  20% {
    opacity: 1;
  }
}
```

so it reaches `#f44321` for a try amount of time... .

So is this a won't fix then?

**Comment by Fedik** [comment]
backdrop can be rgba(255, 255, 255, 0.3), instead of use the opacity

**Comment by chmst** [comment]
Despite of colours - it looks jerky. I have no solution, so cannot complain, but wohld like a smooth decent ring.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32187">issues.joomla.org/tracker/joomla-cms/32187</a>.</sub>

**Comment by dgrammatiko** [comment]
> but wohld like a smooth decent ring

The initial version was with actual SVG and the animation Joomla -> heart by Noemi but the old guard was insisting on keeping this thing (which is not even responsive, the width/height are fixed)... Sad panda

**Comment by PhilETaylor** [comment]
bigger fish to fry - doubt this will be resolved here.
