### ISSUE TITLE
Duplicate of note field with J4 Backend. I use Autum Template.

### ISSUE THREAD

**Issue by ashik685** [joomla/joomla-cms#32189]
### Steps to reproduce the issue

```
<field
						name="note_test"
						type="note"
						class="alert alert-success"
						label="Note About Module"
						description=""
						filter="raw"
/>
```

If you use on your extension backend. Then on template view it does duplicate. I mean it shows twice.

Ref : 

https://docs.joomla.org/Note_form_field_type

### Expected result

It should shows a single note field.

### Actual result

But it shows double note field.

### System information (as much as possible)

I am using 4.0.0-alpha11

Administrator Template : Autum

**Comment by Quy** [comment]
Please test with the nightly build. https://developer.joomla.org/nightly-builds.html
