### ISSUE TITLE
[4.x] Where are the tooltips?

### ISSUE THREAD

**Issue by skurvish** [joomla/joomla-cms#32191]
### Steps to reproduce the issue

Open a new article in the administration. Click on the Options tab. Hover mouse over any of the labels.

### Expected result

Tooltip popup with description as in J3.

### Actual result

Nothing. There is no popover markup in the html. Was this a planned change for J4?

**Comment by brianteeman** [comment]
The mainly useless tooltips have been removed. In a few cases where the information was important then they are displayed on screen below the field. The alias field is an example of this

**Comment by skurvish** [comment]
OK. Good to know. Thanks.
