### ISSUE TITLE
[4.0] Missing bottom border in modal

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#32190]
### Steps to reproduce the issue
Edit an article.
Click Publishing tab.
Click User icon.

Create a new menu item.
Select Single Article type.
Click Select button.

### Actual result
![select-user](https://user-images.githubusercontent.com/368084/106305436-8c22f780-6211-11eb-951f-a104bc571e6e.png)

![select-article](https://user-images.githubusercontent.com/368084/106305456-91804200-6211-11eb-9c73-94c72e3cdcdb.png)

**Comment by brianteeman** [comment]
Its coming from the tbody-icon class 

https://github.com/joomla/joomla-cms/blob/83d1e49f45c5d93688a7024b0dbd2795cfe9380e/administrator/templates/atum/scss/blocks/_icons.scss#L7-L11

**Comment by NikitaEmberi** [comment]
I would like to work on this issue. Can this issue be assigned to me? Thanks.

**Comment by drmenzelit** [comment]
You don't need to ask for permission nor to be assigned to an issue. You can create a PR directly.

**Comment by NikitaEmberi** [comment]
I am completely new to open source contribution. Thanks for informing.

**Comment by NikitaEmberi** [comment]
Is this issue solved? Because the behaviour shown in image above does not appear in my forked repository.
It shows something like this:
![image](https://user-images.githubusercontent.com/59737567/111364854-c5c39b00-86b7-11eb-8d9c-6e4f3c19af0b.png)
![image](https://user-images.githubusercontent.com/59737567/111364921-dbd15b80-86b7-11eb-8081-fc67e54105cc.png)

**Comment by brianteeman** [comment]
@NikitaEmberi You are checking Joomla 3. This is a problem in Joomla 4

**Comment by NikitaEmberi** [comment]
Oh my bad. I upgraded to joomla 4 but the behaviour shown in above image seems to be resolved
![image](https://user-images.githubusercontent.com/59737567/111374648-5ce22000-86c3-11eb-902a-9352088e4086.png)

**Comment by Quy** [comment]
It is still an issue using Windows Firefox 86.0.1.

**Comment by Quy** [comment]
@NikitaEmberi The issue is that `tbody-icon` should not be in `td` but in a separate `span` instead. Please find all instances to fix.

\administrator\components\com_contact\tmpl\contacts\modal.php

Before:
```
						<td class="text-center tbody-icon">
							<span class="<?php echo $iconStates[$this->escape($item->published)]; ?>" aria-hidden="true"></span>
						</td>
```
After:
```
						<td class="text-center">
							<span class="tbody-icon">
								<span class="<?php echo $iconStates[$this->escape($item->published)]; ?>" aria-hidden="true"></span>
							</span>
						</td>
```

**Comment by NikitaEmberi** [comment]
@Quy thanks for your help. It helped me solve the issue.

**Comment by Quy** [comment]
@NikitaEmberi There are more like this. Please do a find and fix. Thanks.

**Comment by NikitaEmberi** [comment]
@Quy sir there were merge conflicts with the pr issued. Do I need to solve them? I see this issue is now closed...

**Comment by Quy** [comment]
@NikitaEmberi The procedure is to close the issue when there is a PR for it.
