### ISSUE TITLE
[4.0] Joomla.initialiseModal is not a function in admin-multilangstatus.js

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#32199]
### Steps to reproduce the issue
Enable multi language, open the backed, and look in browser console

### Expected result
no error

### Actual result
error 
```
Uncaught TypeError: Joomla.initialiseModal is not a function
    at HTMLDocument.<anonymous> (admin-multilangstatus.js:25)
```

### System information (as much as possible)
 latest 4.0-dev branch

### Additional comments

I suspect something with modals after migration to BS5

**Comment by dgrammatiko** [comment]
@Fedik #32205
