### ISSUE TITLE
[4.0] Bug in published method in Joomla\CMS\HTML\Helpers\Grid class

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#32219]
### Steps to reproduce the issue
The method published in Joomla\CMS\HTML\Helpers\Grid https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/HTML/Helpers/Grid.php#L190 is used to render published/unpublished icon and allow users to click on to unpublish/publish an item (usually used on list views backend)

If you look at the code of the method, it looks for tick.png and publish_x.png icon under images/admin folder of administrator template, however, these icons are not available in the admin template for Joomla 4, so it is not rendered properly anymore

### Expected result
The published/unpublished icon is displayed to allow clicking on to change state of the record

### Actual result
The published/unpublished icon is not being displayed

### Additional comments
Use published method from Joomla\CMS\HTML\Helpers\JGrid to replace this old method.

**Comment by ghost** [comment]
> usually used on list views backend

if i understand correct this is solved:

> ![grafik](https://user-images.githubusercontent.com/78906980/114296731-325e6980-9aad-11eb-96c6-1981c3995583.png)

**Comment by joomdonation** [comment]
Thanks for checking but it is not. This is an old PHP class not used by Joomla core but maybe still uses by third party extensions (but I guess they already migrated code to use new class JGrid already). This is a low priority issue to me

**Comment by ghost** [comment]
> This is an old PHP class not used by Joomla core but maybe still uses by third party extensions

I guessed that something other is meant than `The published/unpublished icon is not being displayed` cause if the icons not displayed there are more issues about this reported.

**Comment by joomdonation** [comment]
Guess I'm the only one faced this issue, and I have solved this issue in my own extensions long time ago, I'm closing this issue.
