### ISSUE TITLE
[4.0] dropdown icons

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32213]
shouldnt they be fixed width ?

![image](https://user-images.githubusercontent.com/1296369/106368854-dd7fd380-6344-11eb-90fc-46fef6997394.png)

![image](https://user-images.githubusercontent.com/1296369/106368856-df499700-6344-11eb-8cf3-fccbd2e5a947.png)

**Comment by Quy** [comment]
Yes so the labels can be aligned.

**Comment by brianteeman** [comment]
closed see #32243
