### ISSUE TITLE
[4.0] Tags Similar Module - Blank

### ISSUE THREAD

**Issue by ciar4n** [joomla/joomla-cms#32224]
### Steps to reproduce the issue

Enable 'tags similar' module. Nothing rendered. Admittedly this is not a module I am familiar with but regardless of settings I presume I should at least get a module title.

### Expected result
Something

### Actual result
Nothing even if title enabled. `countModules` comes back as true so in the frontend I get a blank space where I expect to have a module

**Comment by brianteeman** [comment]
#24879 means that you get nothing at all if there are no similar tags

Obviously you will only get similar tags if you are on a single article

With the sample data installed - 
- if you are on a blog page then you have two modules displayed at the bottom of the page in position bottom-b
- if you are on a single article page you have **three** modules displayed

![image](https://user-images.githubusercontent.com/1296369/106456778-ea581080-6485-11eb-9eb4-2d29eda4668f.png)

![image](https://user-images.githubusercontent.com/1296369/106456707-cf859c00-6485-11eb-86c8-019c0c4c1cda.png)

**Comment by ciar4n** [comment]
I get that but if no similar tags exist, should the module title still not be displayed? I would expect the following....

![image](https://user-images.githubusercontent.com/2803503/106517466-7131db00-64d0-11eb-9614-245743d6a172.png)

But instead, we get this because `if ($this->countModules('sidebar-left'))` is returning true...

![image](https://user-images.githubusercontent.com/2803503/106517729-ca017380-64d0-11eb-9980-b411499ef938.png)

**Comment by chmst** [comment]
It is a matter of taste, some want the module with title, some want no module at all. 
Which for me looks like an error in html if a columns is empty and also if the content is wmpty. 
Maybe we can display a text in the module "No similar tags found"?

**Comment by brianteeman** [comment]
@chmst - that was the previous behaviour.

While testing this issue I realised that this current behaviour is completely correct. Similar tags is different to other modules. 

Using the Sample data as an example. We have a menu item for a blog category. The similar tags will **never** have any matches if displayed on the category page. But the only way to have a similar tags module on the article page is to assign the module to the blog category menu item.

**Comment by ciar4n** [comment]
Ideally then I guess the `if ($this->countModules())` statement should return false if the tags similar module is empty.

**Comment by brianteeman** [comment]
The entire point of this code change was to prevent the blank space. (which it does on the sample data). If it doesnt then thats a bug. Could you please share the template code so we can try and debug

**Comment by ciar4n** [comment]
I believe the above example is pretty much using the sample data ('testing' data on cassiopeia). I disabled all other modules in the `sidebar-left` position with the exception of the tags similar module (I positioned it there if not already done so).

**Comment by brianteeman** [comment]
ok - taking a look. It does sound like a bug

**Comment by brianteeman** [comment]
Confirming its a bug as far as I am concerned - i have an idea

**Comment by brianteeman** [comment]
> Ideally then I guess the if ($this->countModules()) statement should return false if the tags similar module is empty.

So it turns out that the code exists.

If you change 
`if ($this->countModules('position))`
to
`if ($this->countModules('position', true))`

This code was added to Joomla 4 by @fedik https://github.com/joomla/joomla-cms/pull/19416

I guess we all forgot it existed and learned something new today

**Comment by ciar4n** [comment]
Nice.. that one is certainly news to me and resolves this issue. 👍

**Comment by ciar4n** [comment]
I'll create the PR

**Comment by brianteeman** [comment]
the PR for what?

**Comment by ciar4n** [comment]
https://github.com/joomla/joomla-cms/pull/32234 ?

**Comment by chmst** [comment]
Closing as we have a PR
