### ISSUE TITLE
[4.0] media field preview empty

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32227]
### Steps to reproduce the issue
in global configuration change site offline to yes

### Expected result
preview of image which as its not set yet is the blank default

### Actual result
it tries to load a non-existent file. 

```
		<div class="field-media-preview">
			 <div id="jform_offline_image_preview_empty">No image selected.</div>
			 	 <div id="jform_offline_image_preview_img">
			 	 	 <img src="" alt="Selected image." id="jform_offline_image_preview" class="media-preview" style="max-width:200px;max-height:200px;">
			 	 </div>	
		</div>
```

![image](https://user-images.githubusercontent.com/1296369/106401578-c57b8300-641c-11eb-9d19-bb2c4c492754.png)

### Additional comments
I suspect this is a javascript issue a

**Comment by dgrammatiko** [comment]
@brianteeman is this still valid?

**Comment by brianteeman** [comment]
No looks like you fixed it somewhere
