### ISSUE TITLE
[4.0] Error Access to undeclared static property: Joomla\CMS\HTML\Helpers\Bootstrap::$scripts 

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#32228]
### Steps to reproduce the issue

Open System | Extension| Install (http://localhost:8090/pr/4.0-dev/administrator/index.php?option=com_installer&view=install)

### Expected result

You can install an Extension

### Actual result

You see error Access to undeclared static property: Joomla\CMS\HTML\Helpers\Bootstrap::$scripts 

### System information (as much as possible)

php: Linux 2205f8e21331 5.4.0-58-generic #64-Ubuntu SMP Wed Dec 9 08:16:25 UTC 2020 x86_64
dbserver: mysql
dbversion: 5.6.51
dbcollation: latin1_swedish_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: false
phpversion: 7.4.13
server: Apache/2.4.29 (Ubuntu)
sapi_name: apache2handler
version: Joomla! 4.0.0-beta7-dev Development [ Mañana ] 7-January-2021 18:55 GMT
useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:84.0) Gecko/20100101 Firefox/84.0

### Additional comments

Same for index.php?option=com_config&view=component&component=com_content

**Comment by ReLater** [comment]
confirmed

Error is thrown by `JROOT/libraries/src/HTML/Helpers/Bootstrap.php:535` 

I think this has been fixed by https://github.com/joomla/joomla-cms/pull/32217/files
Why simple if it works with complicated B\C breaking code, too? ;-) Simply declare old behavior as bug ;-)

**Comment by richard67** [comment]
@astridx Could you check if #32217 fixed this issue?

**Comment by ghazal** [comment]
Issue fixed here.
Tks.

**Comment by richard67** [comment]
Closing as having been fixed with PR #32217 . Feel free to re-open the issue if this is wrong.
