### ISSUE TITLE
Cannot move categories in batch to another category

### ISSUE THREAD

**Issue by rytechsites** [joomla/joomla-cms#32233]
### Steps to reproduce the issue
Category component
select some categories
click on batch
in the 'category' drop down all that is listed is 'root'

### Expected result
should list available categories

### Actual result
![batch-root](https://user-images.githubusercontent.com/17861472/106530970-5a34be00-64bb-11eb-8eb8-685ee2b7370b.png)

### System information (as much as possible)
Joomla! 3.9.24
PHP Version 7.3.26

### Additional comments
Batch for articles works fine.

**Comment by brianteeman** [comment]
Nice bug you found there. Its only showing the unpublished categories

**Comment by joomdonation** [comment]
The bug causes by PR https://github.com/joomla/joomla-cms/pull/31536 . I made PR https://github.com/joomla/joomla-cms/pull/32235 to fix it.
