### ISSUE TITLE
[4.0 ] custom favicon.ico not shown / not used

### ISSUE THREAD

**Issue by det13** [joomla/joomla-cms#32241]
### Steps to reproduce the issue
put custom favicon.ico in directory /templates/custom-template or /templates/cassiopeia when actual

### Expected result
browser should show custom favicon in tab-title ( firefox ) of the front-end

### Actual result
favicon from /media/system/images is shown

### System information (as much as possible)
actual windows 10 pro build, joomla 4 beta 6 running on xampp

### Additional comments
when iconfiles ( favicon.ico, joomla-favicon.svg, joomla-favicon-pinned.svg ) in /media/system/images are renamed or deleted, the custom favicon.ico in /templates/cassiopeia or /templates/custom-template is used and shown in front-end

**Comment by ghost** [comment]
Have you tried another browser as its a known issue of firefox that another favicon takes time to be shown.

**Comment by dgrammatiko** [comment]
> when iconfiles ( favicon.ico, joomla-favicon.svg, joomla-favicon-pinned.svg ) in /media/system/images are renamed or deleted, the custom favicon.ico in /templates/cassiopeia or /templates/custom-template is used and shown in front-end

You shouldn't delete/rename files in the media/system folder, you're not the owner of those files!
If you want to override the favicons just copy the files [ favicon.ico, joomla-favicon.svg, joomla-favicon-pinned.svg ]to cassiopeia/images and edit them **there**. In this folder **you** are the owner of the files

**Comment by chmst** [comment]
Closing as it is a question for forum.joomla.org
