### ISSUE TITLE
[4.0b7] Contact Tags not shown on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32246]
### Steps to reproduce the issue

4.0b7
Login to admin 
Create a contact with a tag of "myTag"
Link to that contact using a menu item
View that contact on the frontend 

### Expected result

Tags icon followed by the tags list including "myTag"

### Actual result

<img width="499" alt="Screenshot 2021-02-02 at 20 36 51" src="https://user-images.githubusercontent.com/400092/106659409-99840d00-6596-11eb-95fb-b4629f717c20.png">

**Comment by chmst** [comment]
Please test #32351. Closing this as there is a PR
