### ISSUE TITLE
[4.0b7] Article Meta Keywords are not rendered on frontend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32249]
### Steps to reproduce the issue

Create an article in the admin of 4.0b7 ensuring you give a value for  Keywords
<img width="748" alt="Screenshot 2021-02-02 at 20 53 32" src="https://user-images.githubusercontent.com/400092/106661103-b9b4cb80-6598-11eb-8a33-23a17fb8ed2c.png">

Link to that article on the frontend, and view the source

### Expected result

```
<meta name=”keywords” content=”bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb” />
```

### Actual result

No keywords tag (note description tag is shown) 

### Additional comments
https://help.joomla.org/proxy?keyref=Help40:Articles:_Edit&lang=en states these keywords are "To help Search Engines and other systems classify the content of the Article." which they cannot be helping as they are not rendered

**Comment by brianteeman** [comment]
The help page is out of date and incorrect. It is deliberate to rename this to keywords and not to render them.

The field is retained for other uses such as the "related articles" module

**Comment by richard67** [comment]
See also https://github.com/joomla/joomla-cms/pull/25258 .
