### ISSUE TITLE
[4.0b7] IFrame Wrapper URL Not validated.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32245]
### Steps to reproduce the issue
was https://github.com/joomla/joomla-cms/issues/18725 closed with no action

Create a menu item of type iframe wrapper - set url to be something thats certainly not a url 

### Expected result

Validation error message

### Actual result

Menu Item Saved

<img width="1183" alt="Screenshot 2021-02-02 at 20 28 44" src="https://user-images.githubusercontent.com/400092/106658725-8ae92600-6595-11eb-923e-76f07fd7b038.png">

**Comment by PhilETaylor** [comment]
same with Menu Item Type = URL

<img width="1200" alt="Screenshot 2021-02-02 at 21 12 56" src="https://user-images.githubusercontent.com/400092/106663312-73ad3700-659b-11eb-9502-87ce7ce2581e.png">

**Comment by brianteeman** [comment]
Someone might have fixed it for you if you hadnt closed the original issue

![image](https://user-images.githubusercontent.com/1296369/106663498-b242f180-659b-11eb-9144-67582b08cad1.png)

**Comment by PhilETaylor** [comment]
> Someone might have fixed it for you if you hadnt closed the original issue 

Its not about me. No one is fixing anything "for me". Im not asking, or demanding, anyone to do anything. Im simply reporting the issues. Like or not. I don't care.

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/32342 should fix the first part of this issue. For the URL of Menu Item Type URL, I'm afraid of it is hard to fix/validate because look like we also accept relative/none-sef URL there, so maybe we will have to rely on Administrators to enter valid url.

**Comment by ghost** [comment]
@joomdonation is right, the first part about `IFrame Wrapper URL Not validated` is solved.

Should the issue be closed and a new one created about `Menu Item Type URL Not validated`?
