### ISSUE TITLE
[4.0b7] frontend Display Template Options page doesn't save input

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32254]
### Steps to reproduce the issue

In Joomla 4.0b7 admin Create a menu item of type "Display Template Options"
Logout
visit frontend and login as super admin
click "Display Template Options" menu item 
Change everything... click save

### Expected result

Expect all inputs to be saved, and applied. And feedback:

<img width="862" alt="Screenshot 2021-02-02 at 21 34 30" src="https://user-images.githubusercontent.com/400092/106665618-72313e00-659e-11eb-86d8-5e0fae7ccdab.png">

### Actual result

Feedback as expected. 

**No details are actually saved though. Form resets to the defaults.**

### System information (as much as possible)

Safari on Mac

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/32281

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32281 . Thanks in advance.
