### ISSUE TITLE
[4.0b7] Site name before title in breadcrumbs

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32253]
### Steps to reproduce the issue

Joomla 4.0 beta 7 
In Global Configuration -> SEO set "Site Name in Page Titles" = BEFORE

(in this example "mySiteName" is my site name) 
### Expected result

ONLY page titles ie `<title></title>` tags are prepended with the site name

Expect the site name never to be prepended to any breadcrumb

### Actual result

When the menu item clicked is a link of the type "Compact List of Tagged Items", or "Tagged Items" the breadcrumbs prepend the site name to the last crumb
<img width="631" alt="Screenshot 2021-02-02 at 21 27 31" src="https://user-images.githubusercontent.com/400092/106664808-7ad54480-659d-11eb-9052-e587bd06a6e6.png">

Note they DONT when viewing an article which is expected.

<img width="588" alt="Screenshot 2021-02-02 at 21 28 01" src="https://user-images.githubusercontent.com/400092/106664861-89bbf700-659d-11eb-8d5f-9695eb132009.png">

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/32301

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32301 . Thanks in advance.
