### ISSUE TITLE
[4.0b7] Inconsistant placement of frontend action buttons

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32250]
### Steps to reproduce the issue

Edit an article on the frontend 

Edit a module position on the frontend

Edit other things.. 

Compare the placement of the action buttons. (Save, Save and close, Cancel) 

Here is the list that needs to be consistent, so choose either Top or bottom and change the others, and fix the icons

| Edit Screen | Location Of Buttons Currently | Buttons | Also |
| ------------- | ------------- | ------------- | ------------- | 
| Article  | Bottom | Save Save&Close Cancel  |
| Module  | Top | Save Cancel Versions |
| Profile  | Bottom | Save Cancel | No tick on save, no cross on cancel
| Template Settings  | Top | Save Cancel |
| Site Settings  | Top | Save Cancel |
| Contact | Bottom | Save Cancel | No cross on cancel  |

### Expected result

Consistency. Either the action buttons (Save, Save and close, Cancel) are at the TOP of the page, or at the bottom. 

### Actual result

Some views (Editing a module) have the buttons at the top of the page

Some views (Editing content, Creating a contact) have the buttons at the bottom of the page.

**Comment by richard67** [comment]
@PhilETaylor Do you remember any other edit views beside the module edit which have the buttons at the top? Or in other words: Does PR #32703 seem complete to you?

**Comment by PhilETaylor** [comment]
#close

No idea sorry, I’ve slept since then :)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32703 . Thanks in advance.

**Comment by richard67** [comment]
Re-opening the issue since it turned out that the PR doesn't solve all inconsistencies.

**Comment by atharva20-coder** [comment]
can anyone attach an image of the issue, please?

**Comment by ghost** [comment]
@atharva20-coder look at the mentioned pull request #32703.

**Comment by PhilETaylor** [comment]
Here is the list that needs to be consistent, so choose either Top or bottom and change the others, and fix the icons

| Edit Screen | Location Of Buttons Currently | Buttons | Also |
| ------------- | ------------- | ------------- | ------------- | 
| Article  | Bottom | Save Save&Close Cancel  |
| Module  | Top | Save Cancel Versions |
| Profile  | Bottom | Save Cancel | No tick on save, no cross on cancel
| Template Settings  | Top | Save Cancel |
| Site Settings  | Top | Save Cancel |
| Contact | Bottom | Save Cancel | No cross on cancel  |

**Comment by brianteeman** [comment]
#33294 and #33295 should complete this PR

**Comment by richard67** [comment]
> #33294 and #33295 should complete this PR

You mean this issue ;-)

Closing as having 2 pull requests. Please test #33294 and #33295 . Thanks in advance.

**Comment by PhilETaylor** [comment]
Thanks
