### ISSUE TITLE
[4.0b7][Release Blocker] Frontend Editor has no access to media manager 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32259]
### Steps to reproduce the issue

as a super admin create a menu link of type "Create Contact"

On the frontend login as an EDITOR and click menu item "Create Contact"

For the Image field click Select 

<img width="890" alt="Screenshot 2021-02-02 at 22 07 33" src="https://user-images.githubusercontent.com/400092/106669098-10270780-65a3-11eb-92a5-49227163d3b7.png">

### Expected result

If the image field is there, and a select button is there, then the expectation is that it can be used to select media from the media manager.

### Actual result

Because the EDITOR doesn't have "Access Administration Interface" enabled by default in ACL, they cannot access Media Manager.

NOTE JS Console error `TypeError: undefined is not an object (evaluating 'e.filter')`
NOTE the media manager modal opens, but displays no contents
NOTE the Ajax request response is 

```json
{
    "error": true,
    "code": 403,
    "message": "You don't have permission to access this. Please contact a website administrator if this is incorrect."
}
```

### Another path:

Edit an article on the frontend as an EDITOR 
In the WYSIWYG Select CMS Content - > Image, to launch model - then same Actual Result. 

### Additional comments

Similar to https://github.com/joomla/joomla-cms/issues/30005 but probably different root cause

**Comment by chmst** [comment]
Should be resolved now. Could you test #32357 please?

**Comment by infograf768** [comment]
Not resolved by https://github.com/joomla/joomla-cms/pull/32357
`Uncaught TypeError: e is undefined mediamanager.min.js:13:72151`

**Comment by infograf768** [comment]
Would the solution concerning https://github.com/joomla/joomla-cms/issues/32259 be some change in the layout?

Something like
```
diff --git a/layouts/joomla/form/field/media.php b/layouts/joomla/form/field/media.php
index 8dd8cd1..177957a 100644
--- a/layouts/joomla/form/field/media.php
+++ b/layouts/joomla/form/field/media.php
@@ -53,4 +53,12 @@
 $attr .= !empty($onchange) ? ' onchange="' . $onchange . '"' : '';
 
+// Access check
+$user = Factory::getApplication()->getIdentity();
+
+if (!$user->authorise('core.manage', 'com_media'))
+{
+	$disabled = true;
+}
+
 switch ($preview)
 {

```

which would give
<img width="844" alt="Screen Shot 2021-02-11 at 11 34 16" src="https://user-images.githubusercontent.com/869724/107625834-31e85480-6c5d-11eb-9cdb-9d8a04ebdac0.png">

<img width="865" alt="Screen Shot 2021-02-11 at 11 33 56" src="https://user-images.githubusercontent.com/869724/107625841-33b21800-6c5d-11eb-955b-7c06a851925a.png">

**Comment by infograf768** [comment]
### Note
The problem also exists when using the image xtd...
Setting as Release blocker.

**Comment by wilsonge** [comment]
PR https://github.com/joomla/joomla-cms/pull/32479
