### ISSUE TITLE
[4.0b7] Floating border to be removed, or completed.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32255]
### Steps to reproduce the issue

Joomla 4.0b7 admin console 

Create some menu items - whatever... 

System. -> Site Template Styles -> cassiopeia - Default -> Menu Assignment Tab

### Expected result

no floating border at the bottom

<img width="509" alt="Screenshot 2021-02-02 at 21 41 13" src="https://user-images.githubusercontent.com/400092/106666350-642fed00-659f-11eb-882f-30080c6185bc.png">

### Actual result

<img width="656" alt="Screenshot 2021-02-02 at 21 40 41" src="https://user-images.githubusercontent.com/400092/106666290-4f535980-659f-11eb-8c7b-c2504d6b7ee9.png">

### System information (as much as possible)

safari on Mac

### Additional comments

Joomla 3 example:

<img width="408" alt="Screenshot 2021-02-02 at 21 41 42" src="https://user-images.githubusercontent.com/400092/106666437-80338e80-659f-11eb-8eb8-f91b47359de4.png">

**Comment by chmst** [comment]
Please test #32361
