### ISSUE TITLE
[4.0b7] Search breadcrumbs entity decode

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32265]
### Steps to reproduce the issue

Joomla 4.0b7
go to /index.php?option=com_finder&view=search
search for `hasn't`
NOTE the breadcrumbs

### Expected result

<img width="456" alt="Screenshot 2021-02-02 at 23 18 51" src="https://user-images.githubusercontent.com/400092/106675460-073b3380-65ad-11eb-919d-0d8fb3e997d7.png">

### Actual result

<img width="552" alt="Screenshot 2021-02-02 at 23 18 31" src="https://user-images.githubusercontent.com/400092/106675400-f985ae00-65ac-11eb-96d7-b7731c2444be.png">

### Additional comments

Yes I know its _probably_ for security so I can't search for `<script>alert('xss');</script>` etc, but there are ways to ensure security and still render  `hasn't` correctly eg:

<img width="486" alt="Screenshot 2021-02-02 at 23 21 13" src="https://user-images.githubusercontent.com/400092/106675636-5da87200-65ad-11eb-8bb1-3f536b98df76.png">

**Comment by Quy** [comment]
PR #32266
