### ISSUE TITLE
[4.0b7] console.log('SkipTo loaded...');

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32260]
### Steps to reproduce the issue

Can we nuke this?

```js
console.log('SkipTo loaded...');
```

No idea where the source is coming from but its compiled into media/vendor/skipto/js/skipto.js and skipto.min.js

We must be modifying the source somehow as there is Joomla name spacing in it. 

### Expected result

Nothing in console.log

### Actual result

<img width="862" alt="Screenshot 2021-02-02 at 22 24 02" src="https://user-images.githubusercontent.com/400092/106670772-609f6480-65a5-11eb-83e7-1fafde9f8113.png">

unneeded debug information output

**Comment by dgrammatiko** [comment]
We need to make a PR on their repo, again 😄

**Comment by PhilETaylor** [comment]
oh does it have history then haha ?  I saw the Joomla specific lines above the console.log so assumed you were modifying their code anyway and could easily nuke this ?

```js
 // Initialize skipto menu button with onload event
  window.addEventListener('load', function() {
    SkipTo.init(window.SkipToConfig ||
                window.Wordpress ||
                ((typeof window.Joomla === 'object' && typeof window.Joomla.getOptions === 'function') ? window.Joomla.getOptions('skipto-settings', {}) : {})
                );
    console.log('SkipTo loaded...'); // jshint ignore:line
  });
```

**Comment by PhilETaylor** [comment]
It would be a shame to leave this one, just as we get rid of the jQuery.Migrate console.log that has been following Joomla console logs around for the last decade ;-)

**Comment by dgrammatiko** [comment]
Yeah man, I added those: https://github.com/paypal/skipto/pull/69 😉
I'll try to nuke it but you know it's their call

**Comment by PhilETaylor** [comment]
Ta - will nuke this issue for now then as can't really do anything here.

**Comment by dgrammatiko** [comment]
For reference https://github.com/paypal/skipto/pull/79

**Comment by PhilETaylor** [comment]
Thanks.

**Comment by dgrammatiko** [comment]
@PhilETaylor https://github.com/paypal/skipto/pull/79 was merged so now we have to wait for their next release

**Comment by brianteeman** [comment]
I will push a new release shortly as there are some other bugs fixed upstream

**Comment by dgrammatiko** [comment]
@brianteeman npm says that last release was 19 days ago
