### ISSUE TITLE
Remove programmers terms from error messages: "Could not bind profile data"

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32263]
### Steps to reproduce the issue

Attempt to change your password to the same password when an admin has flagged your account as "requires password reset"

Receive error message:

> Profile could not be saved: Could not bind profile data: You can't reuse your current password, please enter a new password.

### Expected result

Another one of those where we can clean up the language to remove developers language. (like the other issues to remove PHP Class names and method names from error messages shown to frontend users) 

"binding profile data" means nothing to a user changing their password in Joomla.

"bind" is a PHP Programmers term (in Joomla) for mapping the incoming request to a PHP object and validating the object against some rules. 

The error message would make sense without the "Could not bind profile data" part of the error message

> Profile could not be saved: You can't reuse your current password, please enter a new password.

### Actual result

<img width="864" alt="Screenshot 2021-02-02 at 22 51 51" src="https://user-images.githubusercontent.com/400092/106673257-4071a480-65a9-11eb-9db6-0c4aa424f355.png">

**Comment by Quy** [comment]
PR #32268
