### ISSUE TITLE
[4.0b7] Column Drift again

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32261]
### Steps to reproduce the issue

Safari on macOS Big Sur
Login to admin of 4.0b7 and create new menu item of type "Create Article"
Go to Options tab and resize browser to get three column display
Toggle the Custom Redirect on Cancel

### Expected result

No column drift/jumping

### Actual result

https://user-images.githubusercontent.com/400092/106671315-3306eb00-65a6-11eb-95c5-2f157d3ac58c.mp4

Note that in 2 column mode it doesn't jump around

https://user-images.githubusercontent.com/400092/106671372-4d40c900-65a6-11eb-8251-be1304a86863.mp4

### System information (as much as possible)

Safari on macOS Big Sur

**Comment by brianteeman** [comment]
As there is an open pr to switch to single columns do we need this kept open. It's just one of many examples of the columns idea being a bad one
