### ISSUE TITLE
[4.0b7] User action log link error when created new contact category

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32264]
### Steps to reproduce the issue

Joomla 4.0 beta 7 -> Components -> contacts -> contacts-> New 

ENTER
 - Name = myNewContact
 - Category = click x, select the dropdown and then type myNewContactCategory AND PRESS ENTER
 - Click Save and Close
 
Navigate ->Users -> User Action Log

NOTE: "User admin added new category myNewContactCategory"

CLICK on hyperlinked myNewContactCategory

### Expected result

Edit screen of the new category

### Actual result

<img width="344" alt="Screenshot 2021-02-02 at 23 05 56" src="https://user-images.githubusercontent.com/400092/106674490-3a7cc300-65ab-11eb-90e5-31fd896863ac.png">

```
An error has occurred.
0 Invalid controller class: category
```

With debug=true full trace:
```

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:178
2 | Joomla\CMS\Dispatcher\ComponentDispatcher->getController() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:145
3 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
4 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:142
5 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:185
6 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:266
7 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63
8 | require_once() | JROOT/administrator/index.php:32


```

My url is http://127.0.0.1:4444/administrator/index.php?option=com_contact&task=category.edit&id=19

**Comment by joomdonation** [comment]
I can confirm the issue and made PR https://github.com/joomla/joomla-cms/pull/32280 to fix it.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32280 . Thanks in advance.
