### ISSUE TITLE
[3.9.24] Problem with “Privacy > Request > Email Data Export”

### ISSUE THREAD

**Issue by sxzctzppyw** [joomla/joomla-cms#32272]
I get the following error when trying to send data to the user.
```
The security token did not match. The request was aborted to prevent any security breach. Please try again".
```
I don't know what it can be caused by. Admin Tools uninstalled.
Here is a video to demonstrate.
https://drive.google.com/file/d/1Vyjs5MNUp5wuO7CtD71gs3aZJSr2SsAx/view

**Comment by ghost** [comment]
Ask on https://forum.joomla.org/ as this repository is for developing.

**Comment by sxzctzppyw** [comment]
I found solution.
In my opinion this is a bug.
```
administrator/components/com_privacy/views/request/view.html.php:150
JRoute::_('index.php?option=com_privacy&task=request.emailexport&id=' . (int) $this->item->id . $return),
```

It looks like the token is not being sent.

```
fix
JRoute::_('index.php?option=com_privacy&task=request.emailexport&id=' . (int) $this->item->id . $return.'&'. JSession::getFormToken() .'=1'),
```
Working. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32272">issues.joomla.org/tracker/joomla-cms/32272</a>.</sub>

**Comment by joomdonation** [comment]
@sxzctzppyw It is a valid fix to me. Could you please a PR to get this issue fixed for next Joomla release?

**Comment by richard67** [comment]
@joomdonation It seems @sxzctzppyw had a problem with making the PR, starting with having not forked the repository on GitHub. Maybe you can make a PR?

**Comment by joomdonation** [comment]
OK @richard67 . PR created https://github.com/joomla/joomla-cms/pull/32299

**Comment by richard67** [comment]
Closing as having a pull request (PR). Please test #32299 . Thanks in advance, and thanks @joomdonation for the PR.
