### ISSUE TITLE
[4.0] btn-group radio doesn't work

### ISSUE THREAD

**Issue by OctavianC** [joomla/joomla-cms#32275]
### Steps to reproduce the issue
- Go to `Content > Fields` and press `New`
- Set `Title` to `Radio Test`
- Set `Type` to `Radio (radio)`
- Under radio values, press the plus button twice to add two items: One with `Text` set to `No` and `Value` set to `0` and another one with `Text` set to `Yes` and `Value` set to `1`
- Make sure under the `Options` tab that `Field Class` is set to `btn-group`. It is by default.
- Press `Save`
- Go to `Articles` and press `New`
- Under the `Fields` tab a `Radio Test` will appear.

### Expected result
Clicking on either `No` or `Yes` will toggle between the two buttons.

### Actual result
Clicking on any value doesn't show the button being selected. The input does change, but there's no visual feedback.

**Comment by chmst** [comment]
Confirmed. Also removing the class "btn-group" does not solve the issue.

**Comment by brianteeman** [comment]
Both radio are being given the same class

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32367 . Thanks in advance.
