### ISSUE TITLE
[4.0] sample data menus

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32270]
@chmst @richard67 I remember having a discussion about changing the name of the author menu to admin menu. I cant find the link to that discussion right now but I think it was a mistake - what was the problem we were solving by renaming the menu? Maybe there is a better option?

![image](https://user-images.githubusercontent.com/1296369/106679637-073f3180-65b5-11eb-9b68-1c879d9ada82.png)

**Comment by chmst** [comment]
The was no problem, the only reason was that the name "author menu" is not only visible for the user goup "author" but to every "special" user with access to the backend.
It is  always possible for users to add modules with equal name in frontend and backend.

**Comment by brianteeman** [comment]
But its still called "Author Menu" in the front end 

![image](https://user-images.githubusercontent.com/1296369/106729766-c7546a80-6605-11eb-9007-bfc646412808.png)

I think calling the menu "Admin Menu" is confusing when you look at this of menus

**Comment by chmst** [comment]
Now as you say it .. the title of this module is not shown in the frontend, so nobody noticed, but this looks confusing for newbies.
 
The question is: change the module title to "Admin Menu" or change the menu item title - or both. 
I don't mind - but the name "Author " looks for me like a antique. It has nothing to do with authors.

**Comment by brianteeman** [comment]
How about a compromise and renaming the menu and the module title to "Special Menu"

It won't be confused as an /administrator menu
It is the same as the view level to avoid confusion with the name of the access level

**Comment by richard67** [comment]
Here the history for the records: https://github.com/joomla/cassiopeia/pull/203

**Comment by chmst** [comment]
Added to #31711

**Comment by richard67** [comment]
@chmst Does that PR close this issue?

**Comment by chmst** [comment]
I think so, at it is wat you both have suggested.
