### ISSUE TITLE
[4.0] Unused code

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32284]
As far as I can tell this code is never used as the breadcrumb seperator is set by css

https://github.com/joomla/joomla-cms/blob/06b1c3b2073a3ab9d5e1b1402062c742ecbc8d0a/modules/mod_breadcrumbs/src/Helper/BreadcrumbsHelper.php#L77-L86

**Comment by richard67** [comment]
Maybe https://github.com/joomla/joomla-cms/blob/staging/modules/mod_breadcrumbs/mod_breadcrumbs.php#L20 ?

**Comment by brianteeman** [comment]
@richard67 thats J3 ;)

**Comment by richard67** [comment]
Ah yours is for J4 I just see. Need more coffee.

**Comment by richard67** [comment]
In J4 it is indeed not used anywhere in the core. But maybe it's intended to be used by 3rd party stuff?

**Comment by brianteeman** [comment]
It was but I dont see how it really can be used now. The module used to have an option to select what you wanted to use for the seperator and it was used for that. As there is no option anymore and this is a module specific helper I cant see how any 3rd party stuff could use it. If they wanted to offer seperator options etc then it would have to be in a complete module and not a simple override

**Comment by simbus82** [comment]
So, now we can't change the breadcrumb separator in J4.
![image](https://user-images.githubusercontent.com/1375730/106784964-33a68c80-664d-11eb-8761-91bab1d3a130.png)

For me it's a bug.

**Comment by chmst** [comment]
@simbus82 Separators should be set via css., also for accessibility

**Comment by simbus82** [comment]
Should... by which rule? Never heard, yet I use a lot of different CMS.
It's inside a module, so i need to many setting for adapt it assigning different "styles" per page. Like in Joomla 3: so it's a step back.

Can you explain me what accessibility has to do with choosing the breadcrumbs separator, please?

**Comment by chmst** [comment]
It was a recommentation from a blind a11y expert, not a rule, because screen readers use to read also the separators, if they are not hidden by an aria attribute, I think CSS is good practice. 
 
But I don't know why this option has been removed.

**Comment by infograf768** [comment]
@chmst 
See https://github.com/joomla/joomla-cms/pull/32297 for RTL breadcrumbs and more.

**Comment by brianteeman** [comment]
closing as once again a perfectly sensible issue has been taken completely off track
