### ISSUE TITLE
[4.0] UnknownAssetException: There is no "bootstrap.dropdown" asset of a "script" type in the registry.

### ISSUE THREAD

**Issue by skurvish** [joomla/joomla-cms#32285]
### Steps to reproduce the issue

I updated my copy of J4 from git this morning (past git update was from Jan 26) and now I get this error when trying to access the Administrator.

### Expected result

Administrator opens.

### Actual result

Get this error.  Below is the call stack. Is there a database update that needs to be done for Bootstrap 5 such that a git pull is insufficient to update?

Joomla\CMS\WebAsset\Exception\
UnknownAssetException
in /var/www/html/libraries/src/WebAsset/WebAssetRegistry.php (line 132)
WebAssetRegistry->get()
in /var/www/html/libraries/src/WebAsset/WebAssetManager.php (line 257)
WebAssetManager->useAsset()
in /var/www/html/libraries/src/WebAsset/WebAssetManager.php (line 181)
WebAssetManager->__call()
in /var/www/html/libraries/src/HTML/Helpers/Bootstrap.php (line 232)
Bootstrap::dropdown()
in /var/www/html/libraries/src/HTML/HTMLHelper.php (line 322)
HTMLHelper::call()
in /var/www/html/libraries/src/HTML/HTMLHelper.php (line 154)
HTMLHelper::_()
in /var/www/html/administrator/modules/mod_user/tmpl/default.php (line 19)
require('/var/www/html/administrator/modules/mod_user/tmpl/default.php')
in /var/www/html/administrator/modules/mod_user/mod_user.php (line 16)
include('/var/www/html/administrator/modules/mod_user/mod_user.php')
in /var/www/html/libraries/src/Dispatcher/ModuleDispatcher.php (line 54)
ModuleDispatcher::Joomla\CMS\Dispatcher\{closure}()
in /var/www/html/libraries/src/Dispatcher/ModuleDispatcher.php (line 57)
ModuleDispatcher->dispatch()
in /var/www/html/libraries/src/Helper/ModuleHelper.php (line 293)
ModuleHelper::renderRawModule()
in /var/www/html/libraries/src/Helper/ModuleHelper.php (line 166)
ModuleHelper::renderModule()
in /var/www/html/libraries/src/Document/Renderer/Html/ModuleRenderer.php (line 97)
ModuleRenderer->render()
in /var/www/html/libraries/src/Document/Renderer/Html/ModulesRenderer.php (line 48)
ModulesRenderer->render()
in /var/www/html/libraries/src/Document/HtmlDocument.php (line 589)
HtmlDocument->getBuffer()
in /var/www/html/libraries/src/Document/HtmlDocument.php (line 895)
HtmlDocument->_renderTemplate()
in /var/www/html/libraries/src/Document/HtmlDocument.php (line 660)
HtmlDocument->render()
in /var/www/html/libraries/src/Document/ErrorDocument.php (line 140)
ErrorDocument->render()
in /var/www/html/libraries/src/Error/Renderer/HtmlRenderer.php (line 76)
HtmlRenderer->render()
in /var/www/html/libraries/src/Exception/ExceptionHandler.php (line 128)
ExceptionHandler::render()
in /var/www/html/libraries/src/Exception/ExceptionHandler.php (line 71)
ExceptionHandler::handleException()
in /var/www/html/libraries/src/Application/CMSApplication.php (line 299)
CMSApplication->execute()
in /var/www/html/administrator/includes/app.php (line 63)
require_once('/var/www/html/administrator/includes/app.php')
in /var/www/html/administrator/index.php (line 32)

**Comment by richard67** [comment]
After `git pull` you have to run `composer install` and `npm ci`. Did you do that?

**Comment by skurvish** [comment]
Yes, that corrected the problem. I did not know these steps needed to be done after a pull. Perhaps a note should be added to the readme.md file. It is clear that they need to run when you first pull to create the local repo, but doesn't indicate that this must be repeated on subsequent pulls.

Thanks for the heads up.

**Comment by richard67** [comment]
I think it's clear that one has to run composer or npm again if some dependency has been update in sone of their lock files.

Can we close this issue?

**Comment by skurvish** [comment]
Well it wasn't clear to me but OK. Closing this issue.
