### ISSUE TITLE
[4.0] PHP 8 fatal error with Mail Template

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#32287]
### Steps to reproduce the issue
Open an article in edit mode

Close it

### Expected result
Record checked in with no errors

### Actual result
Fatal error

![image](https://user-images.githubusercontent.com/17835460/106754760-a30c8400-662d-11eb-99b0-ef4bd5ca4689.png)

**Comment by richard67** [comment]
@joeforjoomla Could you check if PR #32118 solves this issue, too?

**Comment by joeforjoomla** [comment]
Yes @richard67 it solves the issue
