### ISSUE TITLE
[4.0]Beta 7 incorrectly displays content 

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#32296]
my test-site is multilingual (German and english).
After update from beta 6 to beta 7 content in german language is correctly setup whereas content in english language overlaps right module.  
see attached sample...

![screen shot 2021-02-04 at 08 53 29](https://issues.joomla.org/uploads/1/285eeeaaec101e156c55d21b45542512.jpg)

**Comment by webchun** [comment]
I think it's because of that part of 'code' in your content _({rgraph_chat...)_ that is probably using pre tags and break the template. Please add screenshot for german language too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32296">issues.joomla.org/tracker/joomla-cms/32296</a>.</sub>

**Comment by jschmi102** [comment]
hi,
you are correct, nothing to do with languages - causer is the pre-tag. But anayway this should not cause overlapping. Rather should set/use max-width of content-column (as it did with Beta 6 and bootstrap 4).  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32296">issues.joomla.org/tracker/joomla-cms/32296</a>.</sub>

**Comment by chmst** [comment]
@jschmi102
 Are you sure that this was ok in with Beta 6 and bootstrap 4? I think that this is independent of the bootstrap version.

**Comment by jschmi102** [comment]
hi,
did not check problem with beta6. But I think you are right, it is not a bootstrap problem but rather a styling problem of casiopeia template. Using a pre-html tag should not break template formatting. To correct this  e. g I  enclosed article within a div-element like  `<div class="container">` then problem disappeared. (Intead of setting width of element in pixel).

**Comment by drmenzelit** [comment]
@jschmi102 Can you please test https://github.com/joomla/joomla-cms/pull/32322 ?

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32322 . Thanks in advance.
