### ISSUE TITLE
[4.0] BS5: cassiopeia RTL CSS maybe broken: BS5 has auto LTR classes.

### ISSUE THREAD

**Issue by HRIT-Florian** [joomla/joomla-cms#32295]
Check these, float-left n -right does not apply any more!

https://github.com/joomla/joomla-cms/blob/89bb7e801943d090d2bc71fc31e88e57ed8d86a7/templates/cassiopeia/scss/template-rtl.scss#L8

**Comment by Quy** [comment]
See #32113

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/32297

**Comment by wilsonge** [comment]
@infograf768 you haven't removed that class in your PR :)

**Comment by infograf768** [comment]
indeed. needs another pr but there should be more classes to delete/modify in template-rtl.scss (input-group- whatever)
may need help for that. :)

**Comment by brianteeman** [comment]
This can be closed. At this time we're not using the automatic rtl part of bs5
