### ISSUE TITLE
[4.0]Beta 7 Loss of multilanguage article content

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#32308]
Hello everyone, I created an article in Fr, then from this article I created the article in rlation in En. I have saved and tested ok. By wanting to return to the possibility of modification, the article is empty. No image, no title, no content. However, when viewing the article, there are indeed both in Fr and En.

https://youtu.be/j98boop69Ds

**Comment by infograf768** [comment]
This has been solved in 4.0-dev
See https://github.com/joomla/joomla-cms/pull/32271#issuecomment-772398596
Closing
