### ISSUE TITLE
Can't update ACL Group after error

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#32305]
### Steps to reproduce the issue
Please see the video

https://user-images.githubusercontent.com/1850089/106943443-10cab580-66eb-11eb-9286-3da385d2c527.mp4

### Expected result
allows you to select new group from list after changing name of group

### Actual result
no list displayed

### System information (as much as possible)

J! 3.9.24

### Additional comments
reported by Alison Meeks.

**Comment by N6REJ** [comment]
update: rp states "if you back out using 'cancel' and start again it works."

**Comment by brianteeman** [comment]
What javascript errors are there in the console?

**Comment by N6REJ** [comment]
the rp doesn't have the technical knowledge to answer that question.
That can easily be answered by testing her report, as we should be doing, and examining it ourselves.

**Comment by joomdonation** [comment]
Please see PR https://github.com/joomla/joomla-cms/issues/32305 . It should address this issue

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32341 . Thanks in advance.

**Comment by richard67** [comment]
> Please see PR #32305 . It should address this issue

@joomdonation You have linked the issue and not the PR ;-)

**Comment by joomdonation** [comment]
Oh, my bad :(.

**Comment by richard67** [comment]
No problem.
