### ISSUE TITLE
[3.9x] and [4.0] itemscope

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#32316]
I have 4.0.0-beta-7 installed. I am currently investigating how best to use itemscope and its properties on my sites, so I had a look at Cassiopeia to see how it's used there.

### What needs to be fixed
I discovered that if you have a menu item with an article or blog in the `<main>` section, the first `<div>` looks something like this with a browser's inspector:

`<div class="com-content-article item-page" itemscope="" itemtype="https://schema.org/Article">`

### Why this should be fixed

It should be `itemscope` without the `=""`, i.e.
`<div class="com-content-article item-page" itemscope itemtype="https://schema.org/Article">`

It's the same in J3.9x

See [https://schema.org/docs/gs.html](url) showing how it should be used.

### How would you fix it

In this file [4.0-dev] joomla-cms/components/com_content/tmpl/article/default.php it is correct, so I don't know when or how the extra `=""` is being added or how to fix it.

### Side Effects expected
None

**Comment by brianteeman** [comment]
Dont use inspector. Use view source instead to check.

**Comment by Scrabble96** [comment]
> 
> 
> Dont use inspector. Use view source instead to check.

Ok. Rather confusing, though.
