### ISSUE TITLE
[3.9] Character is missing in search result title 

### ISSUE THREAD

**Issue by biowan** [joomla/joomla-cms#32319]
### Steps to reproduce the issue
When a result title contains character single/double quote character ('/"), the last character of the title will be cut.

### Expected result

My friend's pencil

### Actual result

My friend's penci

### System information (as much as possible)

The problem is from the highlight method in the script /components/com_search/views/search/view.html.php

### Additional comments

I observe this problem in my current Joomla in version 3.9.24, I don't know if the problem was early.
At the moment, I remove the title highlighting to replace the ligne 165,

  $result->title   = $rowTitleHighLighted;
by
  $result->title   = $rowTitle;

**Comment by infograf768** [comment]
Looks related to the `_smartSubstr` method

**Comment by infograf768** [comment]
In fact it comes from

https://github.com/joomla/joomla-cms/blob/c2570c22a698ed47dd8342b4b87a8df3cc6b9d36/administrator/components/com_search/helpers/search.php#L263-L269

This takes off the single quote.
If we change to
`return preg_replace("/[\"^]([a-z])/ui", '\1', $str);`

it should work.

Please test.

@joomla/cms-maintainers 
Any undesired consequences to that change?

**Comment by biowan** [comment]
Hi, 

Thank you for the reply. 
I tested, it's work fine for single quote. So I have the same problem with the double quote. So I changed the line : 

`return preg_replace("/([a-z])/ui", '\1', $str); `

:smiley: 

Thank you and have a nice day.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32319">issues.joomla.org/tracker/joomla-cms/32319</a>.</sub>

**Comment by richard67** [comment]
> I tested, it's work fine for single quote. So I have the same problem with the double quote. So I changed the line :
> 
> `return preg_replace("/([a-z])/ui", '\1', $str); `

Then it seems to me the preg_replace is not needed at all. Or am I missing something? @infograf768 What do you think?

**Comment by biowan** [comment]
😄 
@richard67 I think you are right. I didn't read all the line.
So I replace all the line and it works fine : 
`return $str ; `

**Comment by richard67** [comment]
The question is if that is right and desired. I have no idea.

**Comment by biowan** [comment]
Just know that the method call `remove_accents($str)`, It must remove accent characters, but I've never used `ui` in regex yet.

**Comment by infograf768** [comment]
u is for unicode dependent
i is for ignore case

**Comment by infograf768** [comment]
Also, 

`$str = JLanguageTransliterate::utf8_latin_to_ascii($str);`
is the part that takes off accents from the latin1 and latin2 strings

**Comment by richard67** [comment]
So what do we need the regex for? If we remove single and double quotes from the pattern, it will remain `return preg_replace("/[^]([a-z])/ui", '\1', $str);`, i.e. strip off any `^`. Would that be right and sufficient?

**Comment by richard67** [comment]
But then the `^` should be escaped, i.e. `preg_replace("/[^]([a-z])/ui", '\1', $str);`. Or was that meant to be the beginning of the string? Then it should be `preg_replace("/^([a-z])/ui", '\1', $str);`, but then the `preg_replace` is useless, or not?

**Comment by saumyahada** [comment]
Hey! I am just beginning to work on open source can you guide me please?

**Comment by drmenzelit** [comment]
@saumyahada welcome to Joomla and thank you for trying to contribute to open source. 
First thing: github is the place to share code, create issues (when something doesn't work as expected) and pull requests (the solution to the bug), but it is not the place to ask support questions. You can start reading the Joomla documentation (https://docs.joomla.org) and you can use the forum to ask questions (https://forum.joomla.org).

If you are a student wanting to apply to GSoC, you should contact the team (https://docs.joomla.org/GSoC_2021)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32639 . Thanks in advance.
