### ISSUE TITLE
[4.0] Extension issue : SP Page BUilder 3.7.9

### ISSUE THREAD

**Issue by AMurray2016** [joomla/joomla-cms#32324]
### Steps to reproduce the issue

1. Create a page in SP Page Builder.  Save and publish the page.
2. Create a menu item, type SP Page Builder >> Page.
3. Click "select" button to open the page list to select the item for the menu item.

### Expected result
Modal window opens to select the page for the menu item on clicking "Select" (highlighted illustrated below)

### Actual result
Cannot select the SPPB page for the menu item (modal window doesn't open).  Menu item can't be saved as that field is required.

![screen shot 2021-02-06 at 02 38 32](https://issues.joomla.org/uploads/1/3aae08d1cae4adcaf43cde2260f5a322.png)

### System information (as much as possible)

Joomla 4 Beta 7 (https://github.com/joomla/joomla-cms/releases/tag/4.0.0-beta7)
Helix Ultimate Template Alpha 4 (https://www.joomshaper.com/blog/helix-ultimate-2-0-alpha-4)
SP Page Builder (Pro) 3.7.9 (https://extensions.joomla.org/extension/sp-page-builder/)
PHP 7.4.11

### Additional comments

I'm not sure that this is a problem with this Beta 7 of Joomla 4 or if it's SP PB or the Helix template.
I've posted the same query on the developer's site (JoomShaper): https://www.joomshaper.com/forum/question/1468 and also in Joomla Forum(https://forum.joomla.org/viewtopic.php?f=715&t=984578)

Thanks.

**Comment by chmst** [comment]
Thank you, you did right posting your issue in the fomums. This is the right place and I close it here.

**Comment by ssnobben** [comment]
HI I can confirm this issue tested yesterday

Select Page Doesnt Work Sp Pagebuilder 3.7.9 And Joomla 4 B8. Nothing happens when you click on icon Select.
