### ISSUE TITLE
[4.0] Javascript exception accessing Global Configuration

### ISSUE THREAD

**Issue by skurvish** [joomla/joomla-cms#32320]
### Steps to reproduce the issue

Open the Global Configuration in the Administrator

### Expected result

Configuration opens and displays the various tabs.

### Actual result

Configuration opens but does not display the tabs, you only see the Site information page.

### System information (as much as possible)

Running current git update from a few moments ago. Did run comp[oser install and npm ci after update.

### Additional comments

The exception is: 
[1612542096676.log](https://github.com/joomla/joomla-cms/files/5933851/1612542096676.log)

Other components access to configuration options display the tabs correctly. It is only the Global Configuration that is having this problem.

**Comment by dgrammatiko** [comment]
Clean your browser's local storage/cookies. This is due to the fact that you have some J3 in the same domain and J3 is using some weird key-value data for the tab memory functionality.

**Comment by skurvish** [comment]
Now why didn't I think of that?? Thank you. works correctly now.
