### ISSUE TITLE
[4.0] Bêta 7 multilanguage association not possible

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#32328]
I am building a test site with the latest version of Joomla 4 beta 7. I created two menu links in Fr and En, but could not link them. When I click on the select a target button, the list remains empty.

![Capture d’écran 2021-02-06 à 16 00 25](https://user-images.githubusercontent.com/26197929/107121858-f7fe0380-6894-11eb-94fa-176ae7d76b3d.png)

**Comment by infograf768** [comment]
You already posted about that.
It is solved in 4.0-dev
See my reply https://github.com/joomla/joomla-cms/issues/32308#issuecomment-773861149

**Comment by Magnytu2** [comment]
No it is not the same thing. Here I am on a menu association.

**Comment by Magnytu2** [comment]
On peut voir que ça fonctionne bien juste avant.

![Capture d’écran 2021-02-06 à 17 38 00](https://user-images.githubusercontent.com/26197929/107124129-36e68600-68a2-11eb-874a-40bd3d3cc3c2.png)
