### ISSUE TITLE
[4.0] mod-menu: class "active" for parent item not treated consistantly

### ISSUE THREAD

**Issue by Homepage-lrv** [joomla/joomla-cms#32327]
### Steps to reproduce the issue
A menu at position "left" is build by using:
<jdoc:include type="modules" name="left" style="table" />
It contains three modules for position "left" with some items having sub-menu's and others not 

### Expected result
By clicking on the menu- or sub-menu-items the class "active" is expected to be present at the parent item as follows:
Initially, all parent-items should have classes "deeper parent", none should have "active"
If a parent item is clicked on the classes should be "active current deeper parent"
If a child item is clicked on the parent's class should be "current deeper parent"

### Actual result
For the first module the behavior is as described.
For the second module the first item ALWAYS has the "active", regardless which item at which module is chosen, even at initial start, where no item should be "active".
For the third module no parent item ever receives the "active", regardless which item is chosen.

### System information (as much as possible)

Einstellung 					Wert
PHP erstellt für 				Linux Basement 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64
Datenbanktyp 					mysql
Datenbankversion 				10.3.27-MariaDB-0+deb10u1
Datenbankzeichensatz 				utf8_general_ci
Datenbankverbindungszeichensatz 		utf8mb4_general_ci
Database Connection Encryption 			Keine
Database Server Supports Connection Encryption 	Nein
PHP-Version 					7.4.14
Webserver 					Apache/2.4.38 (Debian)
PHP-Interface für den Webserver 		apache2handler
Joomla!-Version 				Joomla! 4.0.0-beta7 Beta [ Mañana ] 2-February-2021 19:23 GMT
Browsererkennung 				Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0 

### Additional comments

It seems, that this behavior was already present in joomla 3.9

**Comment by chmst** [comment]
@Homepage-lrv could you please check if this issue remains if you add a  tag-ID to the menu (in tab "advanced")? J3 or J4

**Comment by Homepage-lrv** [comment]
Since I'm not sure whether the attached email was send to the right 
address I forward it to "reply.githug.com" too.

Kindest regards,

Jörg Norrmann



-------- Weitergeleitete Nachricht --------
Betreff: 	Re: [joomla/joomla-cms] [4.0] mod-menu: class "active" for 
parent item not treated consistantly (#32327)
Datum: 	Sat, 6 Mar 2021 12:03:16 +0100
Von: 	Homepage ***@***.***>
An: 	Christiane Maier-Stadtherr ***@***.***>



Hi,

sorry for my late answer, I was out of home for a while.

I'm not sure whether I got your request right, I couldn't find a tab 
"advanced" at the single menu entries, but only for the modules of the 
three main blocks of the menu at position "left" (see 
www.laboerregattaverein.de (under Joomla 3.9.25, updated today)).

I added a "Menü-Tag-ID" there for all three Modules in the menu at 
position "left" (see attached picture), but it didn't change anything, 
the behavior stays the same as described.

I will do this test with my local copy of this webpage under J4 later on 
to, but that may take a little bit more time.

Kindest regards,

Jörg

Am 25.02.21 um 21:48 schrieb Christiane Maier-Stadtherr:
> @Homepage-lrv could you please check if this issue remains if you add 
> a tag-ID to the menu (in tab "advanced")? J3 or J4
>

**Comment by Homepage-lrv** [comment]
Since I'm not sure whether the attached email was send to the right 
address I forward it to "reply.githug.com" too.

Kindest regards,

Jörg Norrmann



-------- Weitergeleitete Nachricht --------
Betreff: 	Fwd: [joomla/joomla-cms] [4.0] mod-menu: class "active" for 
parent item not treated consistantly (#32327)
Datum: 	Wed, 10 Mar 2021 18:32:44 +0100
Von: 	Homepage ***@***.***>
An: 	Christiane Maier-Stadtherr ***@***.***>



Moin,

I checked your request for J4 (4.0.0-beta7) too, the added "Menü-Tag-ID" 
doesn't change anything, the class "active" behaves different for the 
three Modules of my menu at position "left".

Kindest regards,

Jörg



-------- Weitergeleitete Nachricht --------
Betreff: Re: [joomla/joomla-cms] [4.0] mod-menu: class "active" for 
parent item not treated consistantly (#32327)
Datum: Sat, 6 Mar 2021 12:03:16 +0100
Von: Homepage ***@***.***>
An: Christiane Maier-Stadtherr ***@***.***>



Hi,

sorry for my late answer, I was out of home for a while.

I'm not sure whether I got your request right, I couldn't find a tab 
"advanced" at the single menu entries, but only for the modules of the 
three main blocks of the menu at position "left" (see 
www.laboerregattaverein.de (under Joomla 3.9.25, updated today)).

I added a "Menü-Tag-ID" there for all three Modules in the menu at 
position "left" (see attached picture), but it didn't change anything, 
the behavior stays the same as described.

I will do this test with my local copy of this webpage under J4 later on 
to, but that may take a little bit more time.

Kindest regards,

Jörg

Am 25.02.21 um 21:48 schrieb Christiane Maier-Stadtherr:
> @Homepage-lrv could you please check if this issue remains if you add 
> a tag-ID to the menu (in tab "advanced")? J3 or J4
>

**Comment by ghost** [comment]
@Homepage-lrv i guess "reply.githug.com" is wrong as the url is github.com.

**Comment by garkell** [comment]
I think I've stumbled onto this problem whist testing my component in J4 RC.
When using a side menu item to display a list of items in my component, the list displays and the title of the page is as per the menu item name which is what is expected.
When I select some filtering option to filter my list, the active menu is no longer as set from the initial choice but defaults back to the home page setting and any subsequent choices within this listing remains on the home page setting as the active menu.

**Comment by Hackwar** [comment]
@garkell unfortunately no. Your issue has nothing to do with this.

**Comment by Hackwar** [comment]
I tried to replicate the original issue, but for me all of this works as expected. Only those menu items which are actually active do get that class. Closing this issue here. If you still have the problem, please report back either here or in a new issue. Since this would be a pretty major issue and I've not seen any other reports in this regard in the last few years, could this maybe be related to your template and not Joomla itself?
