### ISSUE TITLE
[4.0] Bêta 7 Space between modules

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#32331]
The space between two modules are too large, they should be reduced from 4rem to 1rem, perhaps a lot less.

![Capture d’écran 2021-02-06 à 16 26 58](https://user-images.githubusercontent.com/26197929/107122516-6abcae00-6898-11eb-81b7-49e8fdf9bb1d.png)

**Comment by richard67** [comment]
Closing as duplicate issue. See #32165 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32331">issues.joomla.org/tracker/joomla-cms/32331</a>.</sub>
