### ISSUE TITLE
[4.0b7] Many warnings

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#32344]
### Steps to reproduce the issue

Install Beta 7 and activate all errors.

### Expected result

No warnings

### Actual result

Many warnings. For example

![error](https://user-images.githubusercontent.com/73401898/107150064-3f9b9280-695c-11eb-86ae-dcaa517c4396.PNG)

**Comment by chmst** [comment]
Your installation seems to be defect, there is a mixture of german and english texts. How did you make your installation? in a new directory? With a new database?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32344">issues.joomla.org/tracker/joomla-cms/32344</a>.</sub>

**Comment by ghost** [comment]
Yes, I made a new installation in a new directory and I installed the language in the install process. So the language files are the ones from 3x. I used a new database.

**Comment by infograf768** [comment]
Please do a phpinfo to know which implementation of iconv you have.

If it is not libiconv there could be an issue

Normal is
<img width="1060" alt="Screen Shot 2021-02-08 at 08 40 32" src="https://user-images.githubusercontent.com/869724/107189306-779ce700-69e9-11eb-8545-dc712bd99c8b.png">

**Comment by infograf768** [comment]
> there is a mixture of german and english texts

That is normal as the de-DE pack is a j3 one and does not contain all new J4 strings. ;)

**Comment by ghost** [comment]
@infograf768 Thank you. That is my php.ini. 
![iconv](https://user-images.githubusercontent.com/73401898/107195415-999a6780-69f1-11eb-9f01-5dfde660b6b2.png)

Is there a list with all Technical Requirements for Joomla? 
https://downloads.joomla.org/technical-requirements did not list this.

On this server is a Joomla 3 Website that had no issue. I do not find something for iconv under https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4/de

**Comment by PhilETaylor** [comment]
This is a bug in Alpine linux it seems and not Joomla.
