### ISSUE TITLE
[4.0b7] Error installing Blog Sample Data

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#32343]
### Steps to reproduce the issue

Install Beta 7 and try to install Blog Sample Data

### Expected result

Sample Data are installed

### Actual result

Error. I made the screenshot with German language, but it is the same in English

![sample](https://user-images.githubusercontent.com/73401898/107149959-c56b0e00-695b-11eb-9b7f-c4e481cc429e.PNG)

**Comment by chmst** [comment]
Related to #32344<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32343">issues.joomla.org/tracker/joomla-cms/32343</a>.</sub>

**Comment by ghost** [comment]
> Related to #32343
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/32343](https://issues.joomla.org/tracker/joomla-cms/32343).

Related to what? This is #32343, right?

**Comment by richard67** [comment]
@chmst Please and correct your reference to the related issue or PR. Above you referred to this issue here itself.

**Comment by chmst** [comment]
Closing this as it is related to #32344
