### ISSUE TITLE
[4.0b7] Bootstrap Carousel not working

### ISSUE THREAD

**Issue by JoomDirk** [joomla/joomla-cms#32349]
After updating to J40b7 the bootstrap carousel ist not working any more. I changed the bootstrap 4 carousel-code to the new bootstrap 5 "data-bs-ride" like it is decribed [Your text to link here...](https://getbootstrap.com/docs/5.0/components/carousel/ "here"). Any ideas?

**Comment by dgrammatiko** [comment]
Works fine in the testing component: https://github.com/dgrammatiko/bs5 ( BS5Tests.zip ) https://github.com/dgrammatiko/bs5/blob/main/test_component/site/tmpl/carousel/default.php

**Comment by JoomDirk** [comment]
Thx a lot,
I made a clean install of J4beta7 with cassiopeia template, installed your bs5test.zip, everything worked fine (alerts, dropdown, acoordion, ...) except the carousel. no sliding, no response by clicking on next, ...
Any idea?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32349">issues.joomla.org/tracker/joomla-cms/32349</a>.</sub>

**Comment by dgrammatiko** [comment]
@JoomDirk actually there's a bug fixed with https://github.com/joomla/joomla-cms/pull/32352

Please test

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32352 . Thanks in advance.

**Comment by JoomDirk** [comment]
Hi Dimitris,

 

everything works fine now! Good work and thx a lot!

 

Dirk

 

Von: Dimitris Grammatikogiannis <notifications@github.com> 
Gesendet: Sonntag, 7. Februar 2021 23:30
An: joomla/joomla-cms <joomla-cms@noreply.github.com>
Cc: JoomDirk <dirk.vollmar@schulraeteverband.de>; Mention <mention@noreply.github.com>
Betreff: Re: [joomla/joomla-cms] [4.0b7] Bootstrap Carousel not working (#32349)

 

@JoomDirk <https://github.com/JoomDirk>  actually there's a bug fixed with #32352 <https://github.com/joomla/joomla-cms/pull/32352> 

Please test
