### ISSUE TITLE
[4.0b7] Install not user friendly

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#32345]
### Steps to reproduce the issue

Install Beta 7 on a server and the database is not on the same server.

### Expected result

When the warning, that you have to delete file in installation folder pop up, you see this warning.

### Actual result

You are on the bottom of the installation routine and wonder, why the install does not continue. You have to scroll up manually.

![filedelete](https://user-images.githubusercontent.com/73401898/107150115-7ffb1080-695c-11eb-9283-5a50e0d807c6.PNG)

**Comment by Quy** [comment]
Duplicate #29325. Thanks for the report.
