### ISSUE TITLE
[4.0] admin template, article-view - custom-fields-layout 

### ISSUE THREAD

**Issue by angieradtke** [joomla/joomla-cms#32355]
![fields](https://user-images.githubusercontent.com/1172403/107204169-a3759800-69fc-11eb-9b57-a173365ae041.png)

**Admin-template- Article view**
The  custom fields are displayed in two or three columns -  depending on the browser size.  This  style leads to overlaps, depending on which and how many fields are used. A single-column display would be better. This is not so sexy at first, but  it is more  flexible.
...
<fieldset id="fieldset-fields-0" class="options-form "><legend>Fields</legend><div class="column-count-md-2 column-count-lg-3">.....

Remove the classes (column-count-md-2 column-count-lg-3) will fix the issue 
<fieldset id="fieldset-fields-0" class="options-form "><legend>Fields</legend><div class="">.....</div>

**Comment by PhilETaylor** [comment]
apparently there is a PR to remove all columns in the backend... columns have caused a lot of issues.

**Comment by PhilETaylor** [comment]
apparently there is a [PR to remove all columns](https://github.com/joomla/joomla-cms/pull/31810) in the backend... columns have caused a lot of issues.

**Comment by angieradtke** [comment]
> 
> 
> apparently there is a [PR to remove all columns] 
oh thanks .-)

**Comment by Quy** [comment]
Please test PR #31810
