### ISSUE TITLE
[4.0] Debug does not display on frontend error page

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#32354]
### Steps to reproduce the issue
Enable debug in back-end
Log as admin in frontend
Enter a fake url in frontend

### Expected result
Error page is loaded.
Debug should display at bottom of page

### Actual result
Debug does not display although we do have
`	<jdoc:include type="modules" name="debug" style="none" />`
in error.php

**Comment by dgrammatiko** [comment]
Debug is **NOT** using the template position https://github.com/joomla/joomla-cms/blob/c2570c22a698ed47dd8342b4b87a8df3cc6b9d36/plugins/system/debug/debug.php#L347 Also requires a logged in Admin user

**Comment by infograf768** [comment]
I am logged as Admin.

How to solve this?

**Comment by infograf768** [comment]
code is in line 346
`echo str_replace('</body>', $debugBarRenderer->renderHead() . $debugBarRenderer->render() . '</body>', $contents);`

and the whole code is present before `</body>` in page source.

**Comment by dgrammatiko** [comment]
Do you have any errors in the browser's console?

**Comment by infograf768** [comment]
Many

```
Uncaught ReferenceError: jQuery is not defined
    <anonymous> http://localhost:8888/newfolder/joomla40/media/vendor/debugbar/debugbar.js:4
debugbar.js:4:5
10:55:18.428
Uncaught TypeError: PhpDebugBar.utils is undefined
    <anonymous> http://localhost:8888/newfolder/joomla40/media/vendor/debugbar/widgets.js:14
    <anonymous> http://localhost:8888/newfolder/joomla40/media/vendor/debugbar/widgets.js:583
widgets.js:14:18
10:55:18.428
Uncaught TypeError: PhpDebugBar.Widget is undefined
    <anonymous> http://localhost:8888/newfolder/joomla40/media/vendor/debugbar/openhandler.js:13
    <anonymous> http://localhost:8888/newfolder/joomla40/media/vendor/debugbar/openhandler.js:202
openhandler.js:13:5
10:55:18.428
Uncaught TypeError: PhpDebugBar.utils is undefined
    <anonymous> http://localhost:8888/newfolder/joomla40/media/plg_system_debug/widgets/info/widget.min.js:1
    <anonymous> http://localhost:8888/newfolder/joomla40/media/plg_system_debug/widgets/info/widget.min.js:1
widget.min.js:1:20
10:55:18.428
Uncaught TypeError: PhpDebugBar.utils is undefined
    <anonymous> http://localhost:8888/newfolder/joomla40/media/plg_system_debug/widgets/sqlqueries/widget.min.js:1
    <anonymous> http://localhost:8888/newfolder/joomla40/media/plg_system_debug/widgets/sqlqueries/widget.min.js:1
widget.min.js:1:20

etc.
```

**Comment by dgrammatiko** [comment]
> jQuery is not defined

There you go. Add before https://github.com/joomla/joomla-cms/blob/c2570c22a698ed47dd8342b4b87a8df3cc6b9d36/plugins/system/debug/debug.php#L223

```php

JHtml::_('jquery.framework');
```

**Comment by infograf768** [comment]
You are quoting staging.
I am speaking of 4.0

**Comment by infograf768** [comment]
If I add `HTMLHelper::_('jquery.framework');` on top of error.php, then it works.

**Comment by dgrammatiko** [comment]
Weird the jQuery is defined as dependency here: https://github.com/joomla/joomla-cms/blob/9d38cbf15d75dc0c9cbf1a66be4db5f94d930492/plugins/system/debug/debug.php#L209

Do you have a js file loaded in the browser with path `media/plg_system_debug/js/debug.min.js` ?

**Comment by infograf768** [comment]
No, in index.php (where it works) as well as error.php
I have at bottom of page
`<script type="text/javascript" src="/newfolder/joomla40/media/vendor/debugbar/debugbar.js" defer></script>`

EDIT: In fact I have them in index.php, not in error.php

**Comment by Fedik** [comment]
It worked for me yesterday, without errors. Today not tested.
Any changes in 4.0-dev branch happen recently? :)

**Comment by infograf768** [comment]
@Fedik, have you tested with error.php?

**Comment by Fedik** [comment]
ahh, I misunderstood, sorry, 
yeah it broken on 404 page

**Comment by Fedik** [comment]
okay I see, 
That because it is DocumentError and it a different Document instance from initial.
debug.js attached to original DocuemtHtml, but "on error" the error handler proceed DocumentError

I will try to look later, how to fix that.

**Comment by infograf768** [comment]
You mean
` * @todo   Change this renderer to use JDocumentHtml instead of JDocumentError, the latter is only used for B/C at this time
`
in
`/libraries/src/Error/Renderer/HtmlRenderer.php`

?

**Comment by Fedik** [comment]
Nope, this one https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Document/ErrorDocument.php

**Comment by Fedik** [comment]
hm, or maybe Yes
well, it confusing   :smile:

**Comment by Fedik** [comment]
but the document instance changes in https://github.com/joomla/joomla-cms/blob/9d38cbf15d75dc0c9cbf1a66be4db5f94d930492/libraries/src/Exception/ExceptionHandler.php#L123-L127

need to change how the plugin attach the script

**Comment by infograf768** [comment]
OK

**Comment by Fedik** [comment]
please test #32358
