### ISSUE TITLE
[4.0] User Field - bootstrap not definded in com_contact

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#32368]
### Steps to reproduce the issue
Backend, com_contact. Try to add a new contact and select a linked user.

### Expected result
A modal opens for selecting the user

### Actual result
<img width="1225" alt="user-field" src="https://user-images.githubusercontent.com/1035262/107385854-95ef0980-6af3-11eb-8e9f-001ce08e24d5.PNG">

### Additional comments
Related to #32193

**Comment by dgrammatiko** [comment]
Cant replicate it, did you run `npm install`?
<img width="1789" alt="Screenshot 2021-02-09 at 23 11 18" src="https://user-images.githubusercontent.com/3889375/107435240-2fd2a880-6b2c-11eb-8f24-37af600211bf.png">

**Comment by dgrammatiko** [comment]
Also, please remove the Release blocker. Even if the whole com_contacts was broken that wouldn't be a release blocker 😄

**Comment by chmst** [comment]
@dgrammatiko You have another componente. In Menus, it is ok.
Please test com_contact, add a new contact.

**Comment by dgrammatiko** [comment]
![Screenshot 2021-02-10 at 11 29 47](https://user-images.githubusercontent.com/3889375/107497836-54ae3680-6b93-11eb-95da-ddfcfc279c20.png)

**Comment by laoneo** [comment]
Getting a similar JS error when using the user field in DPCalendar:
![image](https://user-images.githubusercontent.com/251072/107498135-abb40b80-6b93-11eb-9279-5e18774b4637.png)

Has it something to do with #32146. Using that branch to test.

**Comment by dgrammatiko** [comment]
> Getting a similar JS error when using the user field in DPCalendar:

@laoneo this is expected as your modal has a bad id `#.` 
There are 2 PRs for this https://github.com/joomla/joomla-cms/pull/32146 and https://github.com/joomla/joomla-cms/pull/32357 (the second is a 1-1 restore to J3 for the tabs, accordion and modals)

EDIT: so, it turns out my tests were based on #32357 thus I couldn't reproduce. Please test #32357

**Comment by richard67** [comment]
@chmst Does #32357 solve this issue for you?

**Comment by chmst** [comment]
Solved with  #32357
