### ISSUE TITLE
[4.0] Yes/No buttons on click not persistent

### ISSUE THREAD

**Issue by cloudfaction** [joomla/joomla-cms#32366]
### Steps to reproduce the issue

Add a yes/no button to your module

### Expected result

When clicking on yes, it should stay green, when clicking on no it should stay red, even before save.

### Actual result

The color change is on-click, but on release it reverts. Only after save the color is changed

### System information (as much as possible)

J4 B7 / OSX / Google Chrome

### Additional comments

The problem arose when upgrading to BS5, i guess it is a BS5 issue.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32367 . Thanks in advance.
