### ISSUE TITLE
[4.0] PHP 8.0 com_finder array issue / solution review

### ISSUE THREAD

**Issue by breebee** [joomla/joomla-cms#32370]
### Steps to reproduce the issue
Use smart search component on the frontend with a test query

### Expected result
Show search results

### Actual result
0 array_merge() does not accept unknown named parameters 

### System information (as much as possible)
Joomla 4 Beta 8 - Dev
PHP 8.0 - fpm
NGINX

### Additional comments
I have fixed / bypassed error as follows

components/com_finder/src/Model/SearchModel.php line 289

- $include = call_user_func_array('array_merge', $this->includedTerms);
+ $include = call_user_func_array('array_merge', array_values($this->includedTerms));

**Comment by richard67** [comment]
@breebee Do you want to make a pull request?

**Comment by breebee** [comment]
Go for it :)

**Comment by richard67** [comment]
Ok, will make PR.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32371 . Thanks in advance.
