### ISSUE TITLE
Batch processing menu-items unable to select target menu-item

### ISSUE THREAD

**Issue by Pinkeltje** [joomla/joomla-cms#32375]
### Steps to reproduce the issue
Select a menu and all its items then try to batch move them to another menu and menu-item

### Expected result
Being able to select target menu-item

### Actual result

Only possible to select menu (no items)

### System information (as much as possible)
Joomla 3.9.24

### Additional comments
Works in 3.9.22 (not tested with 3.9.23)
**3.9.22**
![3_9_22](https://user-images.githubusercontent.com/8941310/107508220-f9834080-6ba0-11eb-9122-c92bcc89cf8d.jpg)
**3.9.24**
![3-9-24](https://user-images.githubusercontent.com/8941310/107508223-fa1bd700-6ba0-11eb-9826-5c725b9defed.jpg)

**Comment by brianteeman** [comment]
I can confirm the problem. For anyone trying to replicate this you will find that only menu items that are unpublished are available to select (so if you have no unpublished items you get the display reported)

**Comment by joomdonation** [comment]
Thanks @brianteeman. That reminds me a similar issue which I fixed before. I made PR https://github.com/joomla/joomla-cms/pull/32380 to fix this small issue.

**Comment by brianteeman** [comment]
It would be a good idea to find the pr that broke this

**Comment by joomdonation** [comment]
The issue causes by this PR https://github.com/joomla/joomla-cms/pull/31536

**Comment by brianteeman** [comment]
A perfect example of why we need automated tests

**Comment by alikon** [comment]
please test #32380
