### ISSUE TITLE
Allow installation of sample data WITHOUT workflow turned on

### ISSUE THREAD

**Issue by rogercreagh** [joomla/joomla-cms#32387]
### Is your feature request related to a problem? Please describe.
If you are considering migrating to J4 from J3 you might do a test J4 install and install the sample data in order to have something to play with.

Currently the sample data (at least for sample blog) gets installed with workflow turned on.

This is very confusing for someone used to J3 who expects to simply write and publish.

### Describe the solution you'd like
Provide two versions of sample data to install - one with workflow turned on, and one with it turned off. Allow the user to choose.

I suggest that the default choice should be with workflow off, as that is less likely to cause Confusion Helplessness Upset and Doubt (CHUD) for a person used to the existing Joomla way.

### Additional context
Workflow is something of an advanced feature requiring considerable investment in time to tweak it to match your, or your organisation's, way of working. Clearly it is a powerful and useful enhancement for some, but for others it is an unnecessary layer of complexity. Just because it is new is not a good reason to force it down people's throats. Some of the content of the non-workflow sample data could perhaps usefully explain what workflow is and where to turn it on.

**Comment by chmst** [comment]
To make users happy, swithing off workflows would be an easy fix. But I want to get #31711 tested and merged first.

**Comment by dgrammatiko** [comment]
@chmst please take a look at https://github.com/dgrammatiko/sloth-pkg/tree/main/plg_sampledata The way sampledata is handled right now is awkward

**Comment by chmst** [comment]
Please test #31711.

Closing this as there is a PR.
