### ISSUE TITLE
Performance issue with fetching all records from the assets table

### ISSUE THREAD

**Issue by boddunan** [joomla/joomla-cms#32388]
### Steps to reproduce the issue
Access any article on the site

### Expected result
The page loads without adding heavy load on the database

### Actual result
Almost all rows related to articles in the assets table are being fetched. Following the query logged by mysql slowquery.

```
# Time: 2021-02-11T18:22:27.975760Z
# User@Host: @ localhost []  Id:    53
# Query_time: 51.411838  Lock_time: 0.001211 Rows_sent: 10978  Rows_examined: 11010
SET timestamp=1613067696;
SELECT `id`,`name`,`rules`,`parent_id`
FROM `jos_assets`
WHERE `name` LIKE 'com_content.%' OR `name` = 'com_content' OR `parent_id` = 0;
```

This query is being logged from `preloadPermissions` method in the file `libraries/src/Access/Access.php`

### System information (as much as possible)
Ubuntu 20.04, Joomla 3.9.24, PHP 7.4

**Comment by chmst** [comment]
Related? #28132<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32388">issues.joomla.org/tracker/joomla-cms/32388</a>.</sub>

**Comment by boddunan** [comment]
Related but not the same. I am more concerned about why all the rows needs to be fetched from assets table than the query performance. You may add full text index or another index but the fact remains - it fetches all records in assets table. If you see my query, it fetched 10k records for showing any article which is overkill for a CMS plaform that serve thousands of pages.

**Comment by rdeutz** [comment]
Closing because it's a dublicate of #28132, it's the same problem that we fetch all rows and an index will not help for like queries
