### ISSUE TITLE
[4.0b7] Difficulty customizing the Cassiopeia template

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#32386]
Following the creation of the user.css file, the latter is not always taken into account. The template.min.css file always has priority.
The user.css file should always be the reference file for easy CSS modifications please.

![Capture d’écran 2021-02-11 à 18 26 23](https://user-images.githubusercontent.com/26197929/107675512-6fb69e80-6c98-11eb-9236-c2e21ae51093.png)

**Comment by drmenzelit** [comment]
I cannot confirm this. As you can see in my screenshot I've created a user.css with definitions for the header and I was able to override the definitions coming from the template itself:
![grafik](https://user-images.githubusercontent.com/9153168/107681248-1c941a00-6c9f-11eb-9ec4-77dfabe50895.png)

**Comment by drmenzelit** [comment]
And here with your example for `<dd>`
![grafik](https://user-images.githubusercontent.com/9153168/107682599-d3dd6080-6ca0-11eb-9c1e-610e4ddaa40b.png)

**Comment by drmenzelit** [comment]
Are you sure you saved the changes in the user.css before loading the page again?

**Comment by Magnytu2** [comment]
sorry, i cleared my browser cache and it works ... sorry.
