### ISSUE TITLE
[J4.0] accessibility plugin - textToSpeech only en-US

### ISSUE THREAD

**Issue by JoomDirk** [joomla/joomla-cms#32381]
The great accessibility-plugin is only using the english language in textToSpeech and speechToText.

It would be great to change the code in /plugins/system/accessibility/accessibility.php (fill in the bold code):

$document->addScriptOptions(
'accessibility-options',
'labels' => [
'menuTitle'           => Text::_('PLG_SYSTEM_ACCESSIBILITY_MENU_TITLE'),
'increaseText'        => Text::_('PLG_SYSTEM_ACCESSIBILITY_INCREASE_TEXT'),
'decreaseText'        => Text::_('PLG_SYSTEM_ACCESSIBILITY_DECREASE_TEXT'),
'increaseTextSpacing' => Text::_('PLG_SYSTEM_ACCESSIBILITY_INCREASE_SPACING'),
'decreaseTextSpacing' => Text::_('PLG_SYSTEM_ACCESSIBILITY_DECREASE_SPACING'),
'invertColors'        => Text::_('PLG_SYSTEM_ACCESSIBILITY_INVERT_COLORS'),
'grayHues'            => Text::_('PLG_SYSTEM_ACCESSIBILITY_GREY'),
'underlineLinks'      => Text::_('PLG_SYSTEM_ACCESSIBILITY_UNDERLINE'),
'bigCursor'           => Text::_('PLG_SYSTEM_ACCESSIBILITY_CURSOR'),
'readingGuide'        => Text::_('PLG_SYSTEM_ACCESSIBILITY_READING'),
'textToSpeech'        => Text::_('PLG_SYSTEM_ACCESSIBILITY_TTS'),
'speechToText'        => Text::_('PLG_SYSTEM_ACCESSIBILITY_STT'),
'resetTitle'          => Text::_('PLG_SYSTEM_ACCESSIBILITY_RESET'),
'closeTitle'          => Text::_('PLG_SYSTEM_ACCESSIBILITY_CLOSE'),
],
'icon' => [
'position' => [
$direction => [
'size' => '0',
'units' => 'px',
]
]
],
'hotkeys' => [
'enabled' => true,
'helpTitles' => true,
],
**'textToSpeechLang' => '[language of the Site]',
'speechToTextLang' => '[language of the Site]',**
]
)

Thx a lot!

**Comment by brianteeman** [comment]
Please test #32389
