### ISSUE TITLE
[4.0] RTL: skipto separator alignment

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#32395]
### Steps to reproduce the issue
Install Persian language.
Add to the admin persian language folder this file
[plg_system_skipto.txt](https://github.com/joomla/joomla-cms/files/5971356/plg_system_skipto.txt)

Note: some strings are not translated (Aside, Header, Form)

(Change .txt to .ini)

Make sure skipto system plugin is set to be used on site (or both).

Load site with Persian as default language. Click on Tab and then Enter

### Expected result

the resulting css produced from the skipto.js produces
```
.skip-to [role="separator"] {
    font-weight: 700;
    text-align: left;
    color: #1a1a1a;
}
```
It should be aligned right in RTL
as the skipto css is loaded after any other css, it is impossible to correct this in template-rtl.css

### Actual result

<img width="337" alt="Screen Shot 2021-02-12 at 12 22 37" src="https://user-images.githubusercontent.com/869724/107762258-06cd3600-6d2d-11eb-94a9-558d91dd4139.png">

I guess it is an oversight by the vendor.

**Comment by brianteeman** [comment]
> as the skipto css is loaded after any other css, it is impossible to correct this in template-rtl.css

Just put this as the end of the template-rtl.scss file - worked for me

```
.skip-to [role=separator] {
    text-align: right !important;
}

```

**Comment by infograf768** [comment]
`!important` is indeed the key word.

**Comment by infograf768** [comment]
Closing as we have a patch
https://github.com/joomla/joomla-cms/pull/32405
