### ISSUE TITLE
[4.0b7] Added menu position and language flag

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#32398]
Hello, I don't know if I am doing it in the right place.
The Cassiopeia template header lacks position to the right of the Logo. I would like to be able to add a location for a second menu and or language change flags stuck to the right. I'm trying to figure out the CSS Grid, but to no avail. Can you correct me please?
Thank you

![Menu2](https://user-images.githubusercontent.com/26197929/107777172-cbd5fd00-6d42-11eb-9581-55fbdfbdc9a5.jpg)

**Comment by ReLater** [comment]
You, ve inserted a new
`<?php if (....) :`

but didn't close it with a 
`<?php endif; ?>`

**Comment by richard67** [comment]
@Magnytu2 Why don't you just use the module position "search" for the language switcher? You can put more modules on it, not only the smart search module, and by ordering you can control which comes at the top.

**Comment by bembelimen** [comment]
@Magnytu2 could you please ask this support questions in the forum at: [forum.joomla.org](https://forum.joomla.org)? The issue tracker is only for issues of the CMS.

**Comment by infograf768** [comment]
Cyril, merci de bien comprendre les rôles très différents des forum et de github.
Je ferme ce sujet. Bienvenue pour toute présentation d’un bogue. 😉

**Comment by Magnytu2** [comment]
@infograf768 @richard67 @bembelimen Sorry excuse me. But on the forum I ask where my question. I am not sure I will reach the developers of Cassiopeia and who could answer my question precisely.
I find it a shame to leave all this space to the right of the Logo without being able to add a menu, social network links, or flags for languages.
