### ISSUE TITLE
[4.0] Joomla-alert JS

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32394]
On a clean install I am seeing both the es5 and the min version of the joomla-alert javascript being loaded

![image](https://user-images.githubusercontent.com/1296369/107762753-645d8480-6d25-11eb-852f-5910c81ad7b2.png)

cc @fedik @dgrammatiko

**Comment by dgrammatiko** [comment]
Expected, modern browsers will load the `type=module` and older browsers the `nomodule`. The same pattern is also repeated for Bootstrap components and there's a PR https://github.com/joomla/joomla-cms/pull/32315 to move all the rest js scripts to use this pattern (the `type=module` is es6+).

**Comment by brianteeman** [comment]
Thanks for the explanation - learnt something new. Might be worth documenting this as I am sure it will come up again.
