### ISSUE TITLE
[4.0] Extensions - Joomla

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32402]
What does this plugin do because the name and description dont match

![image](https://user-images.githubusercontent.com/1296369/107808211-1fefda00-6d61-11eb-8894-5fd2ba02cee0.png)

**Comment by richard67** [comment]
Well it doesn't manage the update sites, so the text is misleading, you are right.

But it is used to manage the update site ;-)

We use this extension to link the update site for the core to an extension id.

**Comment by richard67** [comment]
And it has helper routines for managing update sites:

https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/extension/joomla/joomla.php#L64

https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/extension/joomla/joomla.php#L147

...

So maybe the description is not that wrong.

**Comment by chmst** [comment]
Maybe: "Helps managing the update sites of extensions"?

**Comment by brianteeman** [comment]
My problem is that the original and your proposed description dont match the title

**Comment by brianteeman** [comment]
Extension - **Finder**
Manage the common words in **Smart Search.**

Extension - **Namespace Updater**
Automatically builds and updates the **administrator/cache/autoload_psr4.php** file that is used to autoload extensions.

Extension - **Joomla**
Manage the update sites for **extensions**.

Hopefully you can see by my highlights that the title of the first two extension plugins refers to their specific tasks. So I would assume from the title that **Extension - Joomla** is managing the update sites for the core of joomla and not for extensions.

@richard67 is saying that it is managing the update sites for core AND extensions. If thats correct then I would suggest
Extension - Updates
Manage the update sites. (replace the word manage with something more specific perhaps)

I

**Comment by Hackwar** [comment]
How about 
Manage the update sites for extensions and Joomla.
