### ISSUE TITLE
[4.0] Joomla.asset.json 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32404]
1. If you use the copy template feature for the cassiopeia template all the references to cassiopeia in the joomla.asset.json file are maintained.
- Does that matter?
- Shouldnt they be renamed to the same value as the one you input when you copy the template?

2. Is there any documentation explaining how to use this file? What its purpose is etc etc. All I can find is https://docs.joomla.org/J4.x:Web_Assets which is way over my head. From what I have been able to deduce there are various joomla.asset.json all of which are loaded before the one for the template. So I am guessing that anything in the template joomla.asset.json file is either specific to that template and/or an override for the previous files.

I found a bit more information in the json-schema https://developer.joomla.org/schemas/json-schema/web_assets.json

If its technically possible to add comments to the joomla.asset.json file then it would be really helpful for anyone looking at cassiopeia as an example to build their new template with.

PS so far building a new site in j4 with bs5 has been a dream and lighthouse loves it. 99/100/100/100

**Comment by dgrammatiko** [comment]
> If you use the copy template feature for the cassiopeia template all the references to cassiopeia in the joomla.asset.json file are maintained.

That should be fine, we only have to move the cassiopeia and atum to the new template mode (the one that supports child templates). I have to finish the work here https://github.com/joomla/joomla-cms/pull/30359 In case that the templates finally ship with the legacy mode and someone forks the template then the  file ` joomla.asset.json ` needs to be adjusted

> PS so far building a new site in j4 with bs5 has been a dream and lighthouse loves it. 99/100/100/100

you can get 100 across the board with https://github.com/joomla/joomla-cms/pull/32141 😉
