### ISSUE TITLE
TAG safe as copy

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#32406]
### Steps to reproduce the issue
* copy a tag with "safe as copy"

### Expected result
* copy of the tag with additional "(2)" in the title and new alias with additional "-2-"
* the tag is depublished (like articles and categories, created with "safe as copy")

### Actual result
* copy of the tag with additional "(2)" in the title and new alias with additional "-2-"
* the tag is PUBLISHED

### System information (as much as possible)
j!3.9.24

### Additional comments
the expectet result base on the funkcionality from articles and categories

**Comment by chmst** [comment]
Cannot confirm. Title and alias get a number. 

Published is mentioned in #32407

**Comment by joomdonation** [comment]
Please test https://github.com/joomla/joomla-cms/pull/32454 . (Tag will be unpublished on Save as Copy).
