### ISSUE TITLE
TAG modifie and safe as copy

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#32407]
### Steps to reproduce the issue
* open an existing tag
* modifie the title
* safe as copy

### Expected result
* a new tag with a new alias, based on the new (modified title)
* a new tag with status unpublished

### Actual result
* a new tag with the old alias
* the new tag ist directly published

### System information (as much as possible)
j3.9.24

### Additional comments
* the expected result has to follow the concept with articles and categories (new alias and status unpublished)

**Comment by chmst** [comment]
@hytsch If I perform your steps in J3.9.24 and J4.0 dev, I can confirm that the tag is copied and published. It should be unpublished. 

But:
If the alias remains unchanged, Joomla adds a number to the alias
If the alias is changed or automatically set, it is stored as usual.
This is expected behavoiur. What is wrong?

**Comment by joomdonation** [comment]
@chmst The right behavior is if Admin change Title of the tag without changing Alias before pressing Save as Copy, the Alias of the created tag should be created base on the changed Title (same as how we handle Alias for article). PR https://github.com/joomla/joomla-cms/pull/32454 should fix that behavior.
