### ISSUE TITLE
[4.0] Image editing value ignored

### ISSUE THREAD

**Issue by barsan-md** [joomla/joomla-cms#32403]
### Steps to reproduce the issue
Create an article and insert an image. Right click on the image to modify its settings. Modify the values of the vertical or horizontale space (-70px for example). Click save and reopen the same dialog. The value you inserted will appear without the px, just -70. Try to modify it by inserting -80. Won't change.
![Cattura](https://user-images.githubusercontent.com/14260975/107827503-301ab000-6d87-11eb-83ff-ecc38f792683.PNG)

### Expected result
Either the value shown when reopening is -70px or it will accept -80 as a valid input

### Actual result
The value doesn't change

### Additional comments
Not sure if related to Joomla or just the editor though.
With positive values works correctly

**Comment by ghost** [comment]
Issue confirming.

**Comment by brianteeman** [comment]
> Not sure if related to Joomla or just the editor though.

The tinyMCE does not let you have negative values here. You can confirm this using their demo site
https://www.tiny.cloud/docs/demo/full-featured/#fullfeaturednon-premiumplugins

Sorry but there is nothing Joomla can do about that

**Comment by barsan-md** [comment]
But it works if you insert a negative value with "px". The issue is that it is incoherent to show an integer value (without "px") in Vertical or Horizontal space text input while in reality the value is in pixel, it works if you use pixel but doesn't if you use integer. The problem is that an integer is what you are suggested to use.

![Screenshot_20210508-092650](https://user-images.githubusercontent.com/14260975/117530836-9d815a00-afdf-11eb-9b8b-aecb764f2152.png)

On mobile it uses an integer only keyboard but you still can paste px text.

Anyway I guess you can close if it is a tinymce only issue. Thanks

**Comment by brianteeman** [comment]
Please close
