### ISSUE TITLE
[3.9.24] Language no longer available "Polish" and many others.

### ISSUE THREAD

**Issue by mrownicki** [joomla/joomla-cms#32414]
### Steps to reproduce the issue

Today I install fresh 3.9.24 J! 
And I don't see my language to install. "Polish"
![screen shot 2021-02-14 at 10 13 09](https://issues.joomla.org/uploads/1/0ab24501897c45ef1fa28fb2969d352d.png)
Total number is 74 languages. I remember there were over 100+

Does it have to do with JoomlaCode?
How to fix GLOBAL for all users in my country?

### Expected result

FIX

**Comment by chmst** [comment]
Could you re-test please? In my applications polish is available. Maybe the server was not available for a time?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32414">issues.joomla.org/tracker/joomla-cms/32414</a>.</sub>

**Comment by mrownicki** [comment]
Hmm Now is ok. 

I refresh several times an event install on the other server. 

It turns out that it's ok. You can close it.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32414">issues.joomla.org/tracker/joomla-cms/32414</a>.</sub>

**Comment by ghost** [comment]
@mrownicki you can close the issue because you have opened it.

**Comment by chmst** [comment]
Closing as resolved
