### ISSUE TITLE
Add a multi-language support on the main page of joomla. As it is accessed all over the world, people should understand all the contents of website.

### ISSUE THREAD

**Issue by sujit-jaunjal** [joomla/joomla-cms#32410]
### What needs to be fixed
Multi-language support

### Why this should be fixed
So that more users can access this site and follow it.

### How would you fix it
Use the google translate api and place it at proper place on the mainpage.

### Side Effects expected
Other UI component's space might be reduced while implementing translate box.

**Comment by richard67** [comment]
This repository here is for handling the CMS software. But your issue seems to be for the websites of Joomla. If this is the case, then here is the wrong place for that, and the right place would be https://github.com/joomla/joomla-websites .

**Comment by chmst** [comment]
Hi @sujit-jaunjal - it is great that you want to contribute in Open Source Projects. Do you want to participate in the Joomla GSoC 2021 Project? We can add you to our chatromm for potential students. Just let us know.

**Comment by sujit-jaunjal** [comment]
> Hi @sujit-jaunjal - it is great that you want to contribute in Open Source Projects. Do you want to participate in the Joomla GSoC 2021 Project? We can add you to our chatromm for potential students. Just let us know.

Hey sure ! I'm aiming for this since few days, are you an outsider or any member of the organization ?

**Comment by chmst** [comment]
We kindly invite you to read https://docs.joomla.org/GSoC_2021_Project_Ideas. Here you find instructions for joining us.

**Comment by richard67** [comment]
There is still my question unanswered if this issue is about out websites or about the CMS code, and close if not about the CMS code.

**Comment by ReLater** [comment]
Just BTW: Google translater and others provide horrible results. In the end nobody will understand others when it goes crosswise in a discussion translated by Google. I never would implement it here on GitHub. Use DeepL in your browser!

**Comment by richard67** [comment]
So or so it is not an issue of the Joomla CMS core. Closing.
