### ISSUE TITLE
[4.0b7] Display problem of articles in the contact card

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#32417]
I am on a test site

On a contact card, the layout of the list of articles for a contact is not good. We should add a space with a "/ or -" separation and remove the background gradient please.

![Capture d’écran 2021-02-14 à 12 38 37](https://user-images.githubusercontent.com/26197929/107875848-788ab880-6ec2-11eb-9713-db7d8e67b2d4.png)

**Comment by drmenzelit** [comment]
Please test #32420
