### ISSUE TITLE
This is not implemented, as it is not possible to implement Argon2i with acceptable performance in pure-PHP

### ISSUE THREAD

**Issue by bybilgili** [joomla/joomla-cms#32428]
This is not implemented, as it is not possible to implement Argon2i with acceptable performance in pure-PHP

hello ; how can i fix this

**Comment by richard67** [comment]
See https://github.com/joomla/joomla-cms/issues/27375 

> You need to install `ext/sodium` through PECL or compile PHP with Argon support enabled (both of which require `libsodium` installed).
> 
> The `sodium_compat` library cannot polyfill all functions in pure PHP, you have hit one of those cases.

@bybilgili Does that help you? Please report back so we know if we can close this issue, or close it yourself if the above hint helped you to msolve it. Thanks in advance.
