### ISSUE TITLE
Editor field type crashes the menu item editor

### ISSUE THREAD

**Issue by xjdfhbv** [joomla/joomla-cms#32425]
### Steps to reproduce the issue
Add an editor field to the default.xml for any existing menu item of any core or other component, then try to create a new menu item using the modified form.

e.g. Open /components/com_content/tmpl/article/default.xml and somewhere in the Basic options fieldset, add:

`<field name="xxx" type="editor" label="xxx" buttons="true" hide="readmore,pagebreak" />`

You must include the "buttons" or "hide" attributes for the problem to occur.

Now try to create a new menu item of type Articles, Single Article, and go to the Options tab. The toolbar buttons no longer function.

### Expected result
Should see the new editor field and the toolbar buttons should work.

### Actual result
Toolbar buttons are dead. Cannot save or cancel.

### System information (as much as possible)
Joomla! 4.0.0-beta7

### Additional comments
Without the "buttons" or "hide" attributes, the problem does not occur.

**Comment by drmenzelit** [comment]
I don't know the use case for such a field, but I can confirm the weird behaviour: buttons and / or hide lead to the inclusion of some elements with modal classes, which interfere with the view, fields and buttons are not clickable anymore.

**Comment by xjdfhbv** [comment]
There are many third party components that allow the addition of text as part of a menu item. This needs to be fixed.

**Comment by brianteeman** [comment]
> There are many third party components that allow the addition of text as part of a menu item. This needs to be fixed.

Can you give an example so that it makes testing easier please.

**Comment by xjdfhbv** [comment]
Here's one of mine:
https://extensions.joomla.org/extension/vertical-markets/booking-a-reservations/rentalot/
Just install it and try to create a menu item of type Rentalot, Classic Availability Page. As soon as you go to the Options tab, the toolbar buttons die.

**Comment by joomdonation** [comment]
Tried again with today nightly build and the issue is gone. @xjdfhbv could you please try again?

**Comment by xjdfhbv** [comment]
Yes I confirm that this problem is gone in beta 8 today. Thank you very much. This can be closed.
