### ISSUE TITLE
Module badge insertion

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#32438]
In the first version of Cassiopeia, we can insert badges in modules and I believe even in menus.
Today I try to do it but impossible with the codes found in bootstrap.

![badges](https://user-images.githubusercontent.com/26197929/108099213-9ef85180-7084-11eb-83ad-334a3e5d12c2.jpg)

**Comment by brianteeman** [comment]
Bootstrap 5 changed badge-secondary to bg-secondary
https://getbootstrap.com/docs/5.0/components/badge/

**Comment by Magnytu2** [comment]
@brianteeman sorry
I know I lack the skill. But I can not.
And it should work in the menu too?

![Capture d’écran 2021-02-16 à 18 46 32](https://user-images.githubusercontent.com/26197929/108101488-935a5a00-7087-11eb-9443-d5c1b6d7728d.png)

**Comment by brianteeman** [comment]
Please use the forums for support

**Comment by Magnytu2** [comment]
Yes I understand and have already tried several posts on the joomla.org forum. There is no Joomla 4 section and no one is responding anymore. I will try on the joomla facebook page. I often feel alone using Joomla 4 for testing.

**Comment by richard67** [comment]
Closing as not a core issue.
