### ISSUE TITLE
[4.0b7] Save & Close Split button borders wrong

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32433]
### Steps to reproduce the issue

Install Joomla 4 beta 7 and navigate in admin console to creating a new article

Note the Save & Close button (with clean glasses on...) 

### Expected result

<img width="328" alt="Screenshot 2021-02-16 at 14 16 50" src="https://user-images.githubusercontent.com/400092/108074904-a0645280-7061-11eb-87cf-826a56e88e7e.png">

### Actual result

<img width="320" alt="Screenshot 2021-02-16 at 14 14 47" src="https://user-images.githubusercontent.com/400092/108074699-6bf09680-7061-11eb-9f54-ba7d5baea8c6.png">

### System information (as much as possible)

Safari on Mac

**Comment by dgrammatiko** [comment]
@ciar4n could you help here? Basically, this comes probably by this reverse order: https://github.com/joomla/joomla-cms/blob/46216f83e16ea193825e478cbda9c7f793801be2/layouts/joomla/toolbar/dropdown.php#L45

**Comment by brianteeman** [comment]
iirc i fixed this for rtl
maybe I broke something

**Comment by ciar4n** [comment]
PR created... #32440

Not sure of the reason for the button reversal here... I'll assume its a good one :)

> iirc i fixed this for rtl
> maybe I broke something

Nope. Looks like this is a result of the Bootstrap version bump

**Comment by dgrammatiko** [comment]
>  I'll assume its a good one :)

it was, had to do with the dropdown logging an error, something weird with the way these buttons are built.
Thanks

**Comment by dgrammatiko** [comment]
@ciar4n is it too much to ask to remove also the inline style and place it in the scss?

**Comment by ciar4n** [comment]
Sure... done! 👍
