### ISSUE TITLE
[4.0b7] masonry display different between browser

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#32439]
On the Chrome browser the blog display in masonry begins with the iamges at the top. With the Firefox browser the display is random and can start with text? 

To see my test site: http://www.magnytudeweb.com/fnak.com/

Chrome :
![Capture d’écran 2021-02-16 à 19 02 52](https://user-images.githubusercontent.com/26197929/108103350-1c729080-708a-11eb-863c-add6cfbfe7d8.png)

Firefox :
![Capture d’écran 2021-02-16 à 19 03 05](https://user-images.githubusercontent.com/26197929/108103387-298f7f80-708a-11eb-8a83-f81e396e0ce5.png)

**Comment by ciar4n** [comment]
PR created... #32441
