### ISSUE TITLE
Joomla error after activating error reporting "development"

### ISSUE THREAD

**Issue by marco910** [joomla/joomla-cms#32430]
Hi everyone,

I've just activated error reporting in the backend on my Joomla website and set it to development.

After that, I'm getting the following error when trying to access the front- and backend. 

```
Deprecated: Array and string offset access syntax with curly braces is deprecated in /libraries/joomla/database/driver.php on line 1950

Deprecated: Array and string offset access syntax with curly braces is deprecated in /libraries/joomla/database/driver.php on line 1950

Deprecated: Array and string offset access syntax with curly braces is deprecated in /libraries/joomla/database/driver.php on line 1950

Deprecated: Array and string offset access syntax with curly braces is deprecated in /libraries/joomla/database/driver.php on line 1950

Deprecated: Array and string offset access syntax with curly braces is deprecated in /libraries/joomla/database/driver.php on line 1950

Deprecated: Array and string offset access syntax with curly braces is deprecated in /libraries/joomla/database/driver.php on line 2026

Warning: session_name(): Cannot change session name when headers already sent in /libraries/joomla/session/handler/native.php on line 128

Warning: session_cache_limiter(): Cannot change cache limiter when headers already sent in /libraries/joomla/session/handler/native.php on line 235
Error: Failed to start application: Failed to start the session because headers have already been sent by "/libraries/joomla/database/driver.php" at line 1950.
```

### System information (as much as possible)
Joomla 3.9.8
PHP 7.4
MySQL database

### Additional comments
I already tried to disable error reporting in the config file, but this didn't solve the problem.

**Comment by Fedik** [comment]
are you sure you have 3.9.24?
there no any code at these lines, that can cause error:
https://github.com/joomla/joomla-cms/blob/4a6f30eb2a419976a2a3aaa6c73a89f56e1f0343/libraries/joomla/database/driver.php#L1945-L1954

It also may happen that your installation is corrupted.

**Comment by marco910** [comment]
The Joomla installation is an existing one, that I have updated today. After that, it ran without any errors. And then, after activating error reporting, the above error happend.

**Comment by marco910** [comment]
I just restored the Joomla site from a backup I created today. And tried to activate error reporting. After that, the same problem happens.

When I try to disable error reporting in the config file I don't have permission to update the file. I have to copy the content and create a new one. Then the site is working and no error occures.

My current Joomla version is 3.9.8

**Comment by Fedik** [comment]
Yes, that what I thought, your installation was corrupted. 

Try update again to 3.9.24. But upload update the files manually via FTP, then go to backend `administrator/index.php?option=com_installer&view=database` and push "Database fix" button.

**Comment by marco910** [comment]
That sounds possible. In the backend it says that Joomla is up to date.

Before updating manually I will make a backup and the update manually.

**Comment by marco910** [comment]
I've updated Joomla manually and now the problem and the problem no longer occurs when I enable error reporting.

Thanks for your help @Fedik !
