### ISSUE TITLE
[4.0] Bootstrap 5 - Cassiopeia - Responsive Fonts

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32449]
One of the key features of BS5 is the use of RFS (responsive font size) however cassiopeia is overriding all of that. It would be a real shame if this key feature of BS5 was not available with cassiopeia.

I'm wondering why we are even changing the font sizes for cassiopeia from the bootstrap defaults anyway. Unless there is a very very good reason then the BS5 defaults should be used (plus its less code to maintain)

**Comment by softforge** [comment]
https://getbootstrap.com/docs/5.0/getting-started/rfs/
Good point!

**Comment by brianteeman** [comment]
There are similar issues with the zindex
Cassiopeia is duplicating some and others that cassiopeia adds are conflicting.

From Bootstrap
> // Warning: Avoid customizing these values. They're used for a bird's eye view
// of components dependent on the z-axis and are designed to all work together.

**Comment by drmenzelit** [comment]
You have to take in account that Cassiopeia was created 2017... As last year the Cassiopeia Working Team modified and improved things, we didn't know that BS5 would be implemented. Now we have to make improvements again...

**Comment by brianteeman** [comment]
Of course - that is why I am creating an issue for it.

**Comment by brianteeman** [comment]
Closed as this was resolved in #32467
