### ISSUE TITLE
[4.0b7] CSS construction of Cassiopeia

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#32443]
Hello, I am using Joomla 4 for a styling exercise. While browsing the CSS files, I do not find the same codes between the template.css files from Cassiopeia and the bootstrap.css file from Bootstrap 5 beta 2. however the template.css file is clearly identified as Bootstrap 5.0.0-beta2. I find it sad not to take advantage of the xxl width? Does building in CSS Grid prevent this?

![Capture d’écran 2021-02-17 à 09 21 53](https://user-images.githubusercontent.com/26197929/108176918-da396580-7102-11eb-8ec6-9cd3c2c08e43.png)

**Comment by drmenzelit** [comment]
Please test PR #32446
