### ISSUE TITLE
[4.0] Admin menu freezes with prefers-reduced-motion

### ISSUE THREAD

**Issue by xjdfhbv** [joomla/joomla-cms#32445]
### Steps to reproduce the issue
On a desktop computer, enable "prefers-reduced-motion" mode on your browser. There are various ways to do that. Google it.
- On the main left menu, click "System".
- Then click "Components". The Components menu opens.
- Then click any component that has sub-menu entries, e.g. Banners, Contacts, News Feeds, or Smart Search. Nothing happens. The sub-menus do not open.
- Click Tags or Multilingual Associations. Items without sub-menu entries work ok.
- Now click Banners or any of the other previously dead items. One item (only) will now open.

There are many other manifestations of the problem and many other ways to reproduce it. The above is just one reliable example.

### Expected result
The menu system should be capable of working with prefers-reduced-motion.

### Actual result
As described above, the menu is virtually unusable with prefers-reduced-motion.

### System information (as much as possible)
Joomla! 4.0.0-beta7 and at least as far back as beta4. The problem occurs in all recent versions of Chrome, Firefox, Safari and Edge.

### Additional comments
Removing the "transition-duration:0s!important;" at line 14510 of Atum template.css prevents the problem occurring, although that is not an acceptable solution because the animation is not suppressed. 

Changing that line to "transition-duration:0.0001s!important;" also prevents the problem and is a better solution for people who need reduced motion. 

Obviously it would be better to find out why the problem occurs with transition-duration:0s and fix that.

**Comment by richard67** [comment]
Same as issue #31242 ? Or at least related?

**Comment by xjdfhbv** [comment]
Yes, #31242 looks like a related issue, with the same workaround.

**Comment by richard67** [comment]
Related? Or duplicate? If duplicate, this issue should be closed as such.

**Comment by xjdfhbv** [comment]
I would say related but different.

**Comment by Quy** [comment]
How is it different? Your suggested solution is similar to the suggested one in the other PR. https://github.com/joomla/joomla-cms/issues/31242#issuecomment-716858517

**Comment by xjdfhbv** [comment]
Ok, our descriptions are different but it's probably the same issue. Personally, if I was the developer looking into this, I'd want to see both issues, but it's up to you if you want to close it.

**Comment by richard67** [comment]
Closing as duplicate report. See #31242 . But thanks for reporting, that helped us to put it back on our radar. I hope we can solve it.
