### ISSUE TITLE
Joomla Ajax Module getAjax() method not found

### ISSUE THREAD

**Issue by webchun** [joomla/joomla-cms#32455]
### Steps to reproduce the issue
I tried to modify mod_articles_latest by adding support for ajax. Because of unresolved issue in #32136 I added dummy helper.php to include ArticlesLatestHelper.php and added getAjax function into ArticlesLatestHelper.php.
But everytime I tried to access this url ``index.php?option=com_ajax&module=articles_latest&method=get&format=json`` it always returned ``{"success":false,"message":"Method getAjax does not exist.","messages":null,"data":null}``

I think this is still related to namespaced module's issue because when I tried to comment ``namespace Joomla\Module\ArticlesLatest\Site\Helper;`` and rename Helper Class name from ``ArticlesLatestHelper`` to ``ModArticlesLatestHelper`` it returned ``{"success":true,"message":null,"messages":null,"data":"yes it works"}``

### System information (as much as possible)

Joomla 4 beta 7

**Comment by webchun** [comment]
Sorry mistakenly marked the issue as critical, should be Urgent or Medium<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32455">issues.joomla.org/tracker/joomla-cms/32455</a>.</sub>

**Comment by Quy** [comment]
Please test PR #32291

**Comment by joomdonation** [comment]
We have new PR here https://github.com/joomla/joomla-cms/pull/32633 . Maybe this issue could be closed?

**Comment by alikon** [comment]
yes
