### ISSUE TITLE
[4.0] mod_version appearance

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#32453]
### Steps to reproduce the issue
add mod_version to your dashboard

### Expected result

aligned icon and standardized text height, similar than mod_stats_admin

![image](https://user-images.githubusercontent.com/5349333/108266480-6df24c80-716a-11eb-8a3f-be0ff2747234.png)

### Actual result

![image](https://user-images.githubusercontent.com/5349333/108266209-1bb12b80-716a-11eb-9c42-d0ec789c13d8.png)

### System information (as much as possible)

4.0 Beta 8 , PHP 8, Windows, Firefox, Chrome

**Comment by jsubri** [comment]
snipet code for administrator\modules\mod_version\tmpl

![image](https://user-images.githubusercontent.com/5349333/108425629-00622100-723b-11eb-94ef-b73d9c787eb2.png)

inspired from administrator\modules\mod_stats_admin\tmpl
Happy to test a PR

Update: Insert code not rendered :-(  replaced with a picture

**Comment by chmst** [comment]
@jsubri this module was made for the heading area of the template atum. For usage as an independent module you need another module. 
Same for other modules in the header of atum.

**Comment by jsubri** [comment]
Valid point. However this was not intuitive to me, the Position is defaulted to cpanel.

When you come from J3 it is designed to work best in the footer

Maybe updating the MOD_VERSION_XML_DESCRIPTION to indicate which Position it shall be assigned to.

![image](https://user-images.githubusercontent.com/5349333/108530870-58019a80-72d6-11eb-88dc-47c2f82b1156.png)

**Comment by infograf768** [comment]
> Maybe updating the MOD_VERSION_XML_DESCRIPTION to indicate which Position it shall be assigned to.

+++

**Comment by Quy** [comment]
Please test PR #32464. Thanks.
