### ISSUE TITLE
Smart search: indexing of unpublished content

### ISSUE THREAD

**Issue by peterhulst** [joomla/joomla-cms#32458]
### Steps to reproduce the issue
Unpublish an article. Start a complete new indexing.
The indexing also processed unpublised articles.
However an unpublished article can only be found in case it is published again.
(i tried to excluded articles for the indexing by unpublishing before indexing, but that did not work. 

### Expected result
Unpublished articles (or concept articles) are not indexed, until they are published (again). 

### Actual result
Unpublished articles ar indexed

### System information (as much as possible)
3.9.24

**Comment by richard67** [comment]
@Hackwar Could you have a look on this?

**Comment by Hackwar** [comment]
Content should land in the index regardless of them being published or not. However the index should not show them in the search results if you don't have access to them. So unless you are logged in as a user with publishing privileges (for example Super Administrator), you shouldn't see them in the results in the frontend. Can you confirm that they do show up for you in the frontend?

**Comment by brianteeman** [comment]
It was definitely a problem (a long time ago) that they appeared in the suggestions but I thought that was fixed.

**Comment by peterhulst** [comment]
Thanks for replying. 
When unpublished, it does not show in the search result. **So that behaviour is as expected**.

However: I had a problematic article for indexing, so I unpublished it. That did not help (the indexing was still problematic), so I was suprised

When inlogged in as a super user, it also does not show up in the search results when unpublished. **So that behaviour is as NOT expected**.

Regards,
Peter

**Comment by PhilETaylor** [comment]
> When inlogged in as a super user, it also does not show up in the search results when unpublished. So that behaviour is as NOT expected.

that is expected - as the article is unpublished, so correctly doesn't show in search results. 

this issue can be closed
