### ISSUE TITLE
[4.0] Disable Components

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32456]
### Steps to reproduce the issue
In Extensions Manager you can disable a component.
If you disable a component that is displayed in the sidebar components menu then the link is removed from there and from the components dashboard.
You can disable Contacts to see

If you disable a component that is not displayed in the sidebar components menu but is instead displayed on the system dashboard then no changes are made. The link is still displayed in the dashboard and if you click on it you will obviously get an error.

You can disable CSP to confirm this

### Expected result
A disabled component is removed from the admin wherever it is displayed

### Actual result
Only components in the sidebar are removed when disabled

**Comment by chmst** [comment]
Closing as we have a PR
