### ISSUE TITLE
[4.0b7] Adding icons and dabge in cassiopeia

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#32460]
I have tried everything for two days. The insertion of badges or icons in menus or modules does not work. I think as it was in cassiopeia versions in Joomla 4 alpha it should work.

![erreur-de-badge](https://user-images.githubusercontent.com/26197929/108399681-a9e4ea80-721a-11eb-86f0-17f3337751a3.jpg)

**Comment by brianteeman** [comment]
I am not really sure what you are trying to do but the way that you add an icon to a menu item in Joomla 4 is identical to Joomla 3

![image](https://user-images.githubusercontent.com/1296369/108408850-75bef900-721d-11eb-85c7-c8ad88932e53.png)

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/108409056-a737c480-721d-11eb-9bcf-b9784701656e.png)

**Comment by drmenzelit** [comment]
The problem with the method is that it changes the font of the link or title...

**Comment by brianteeman** [comment]
I know but the poster said it's not possible. And with a layout overide you can resolve the font face

**Comment by drmenzelit** [comment]
That is right :-)

**Comment by Magnytu2** [comment]
lol, you are right, I will modify the text of my problem:
I am unable to add icons and badges to the cassiopeia template. 2 days that I research, that I ask questions on Facebook or the forum. I have today downloaded and installed almost all alpha versions of Joomla 4 to find this information. So: please without referring me to a CSS course or anything else, would you agree to give me a solution and share your powers with me. I will make good use of it by making a video tutorial for example. Please just a screenshot for me. :)

**Comment by brianteeman** [comment]
There are at least 5 articles on the first page of google on this but here you are

![before](https://user-images.githubusercontent.com/1296369/108418939-c9cfda80-7229-11eb-900d-d33da90b1109.gif)

**Comment by infograf768** [comment]
I would be curious to know how the OP added at one point a badge next to a module title

**Comment by Magnytu2** [comment]
Hello, it's great thanks to you I'm moving forward a bit. Thank you very much. But that opens me questions.
- I tried to use icons from Bootstrap 5 https://icons.getbootstrap.com/icons/house/
- The Font Awesome icons work but the font changes, in the menu as for the modules, why? Do I have to create a new bug question?
- Can you also give me a simple screenshot for adding a badge?
My goal is to add to the left of "search" a magnifying glass and to the right an "advanced" badge.
Thanks again for your precious help.

![Capture d’écran 2021-02-19 à 09 17 15](https://user-images.githubusercontent.com/26197929/108478292-97a79280-7294-11eb-99dc-aca373949446.png)

**Comment by brianteeman** [comment]
I am sorry but I answered your question because you said you had done this successfully in a previous beta but it no longer worked. This is not the place to give you support in how to build and customise a website

**Comment by Magnytu2** [comment]
@brianteeman Hello sorry, all my questions are not for me. But good for all the Joomla community. I don't gain anything by spending hours testing Joomla 4. I'm not a web professional.
And I just wanted to say that in 2017, the version of Joomla 4 alpha allowed us to install a demo version and to view all the positions of modules and their enrichment of colors, icons and badges.
As Joomla 4 becomes more complex to use, we need to create a more complete documentation base.

**Comment by Magnytu2** [comment]
Finally, I have just found part of what I am trying to reproduce with Cassiopeia. In November 2017, Joomla 4 alpha 2 was released with a full demo version of module positions and enrichment. And there was a "demo-module" CSS Class. can we reproduce such a demo for Cassiopeia at installation? It would be a great help for all.
![Capture d’écran 2021-02-19 à 11 21 29](https://user-images.githubusercontent.com/26197929/108491938-d8a7a300-72a4-11eb-97b3-1eaccbfdc832.png)
![Screenshot_2021-02-19 Home](https://user-images.githubusercontent.com/26197929/108491974-e2310b00-72a4-11eb-9670-867b55d5074c.jpg)

**Comment by brianteeman** [comment]
So that is showing the use of a badge in content not in the title which is what you have been describing.

There is nothing special there at all. Nothing unique to joomla. It is just regular html markup to use bootstrap classes.

**Comment by Magnytu2** [comment]
Yes you are right, and I apologize. And yet it seems so logical to me. Don't you think it would be nice to be able to easily do this on the menu as in the modules to the right of the title?

**Comment by drmenzelit** [comment]
You can do it with overrides. I know, maybe not so easy for new users, but Joomla can't have parameters for all ideas one can have ;-)

**Comment by Magnytu2** [comment]
@drmenzelit You are probably right, I am still disappointed. I thought it would be easy to add badges to menu links, like module titles.
I realize that indeed it is not easy and expected in Cassiopeia. And above all, I don't have the skills to develop the template.
Can we still correct the change of font next to the Font Awesome icons?

**Comment by Magnytu2** [comment]
I just managed to adapt some colors to the modules. I will completely redo all module positions like J4 alpha 2.
![Capture d’écran 2021-02-19 à 15 18 40](https://user-images.githubusercontent.com/26197929/108518535-f4bd3b80-72c8-11eb-8dbd-f8371175bd58.png)

**Comment by Magnytu2** [comment]
Small exercise to master the positions of Cassiopeia modules in Joomla! 4 with: borders, backgrounds, badges ... Thanks for your help.
![Screenshot_2021-02-19 Accueil(2)](https://user-images.githubusercontent.com/26197929/108562173-c3139700-72ff-11eb-995d-8f21c4a30135.png)

**Comment by infograf768** [comment]
I guess we now can close this as it is not a core issue. Thanks.

**Comment by mariantanase** [comment]
> 
> 
> The problem with the method is that it changes the font of the link or title...

This is a known issue ? 
Or is a different method to add icons to menu items without change the font ? (no layout override please!)

**Comment by Magnytu2** [comment]
Vous devez suivre ceci : https://github.com/joomla/joomla-cms/issues/32471

**Comment by mariantanase** [comment]
> 
> 
> Vous devez suivre ceci : #32471

I see that, but it seems that someone close that issue without provide a PR fix.
For my point of view is a Cassiopeia bug.

**Comment by ghost** [comment]
@mariantanase #32471 is a open issue

**Comment by mariantanase** [comment]
> 
> 
> @mariantanase #32471 is a open issue

thanks
