### ISSUE TITLE
Bug with admin template with custom fieldset property

### ISSUE THREAD

**Issue by ashik685** [joomla/joomla-cms#32475]
### Steps to reproduce the issue

When I add a custom fieldset name and add field types there, it looks like a mess. But in joomla 3 it looks in a good way.
So it is very important to make sure not only basic but also on custom fieldset name design looks good with administrator template.

### Expected result
It shoud shows fields nicely under custom fieldset name

### Actual result

But it looks like a messy in design. Joomla Team must a look at this.

**Comment by chmst** [comment]
Could you please add a screenshot?

**Comment by ashik685** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/11609996/108605096-3ab6f400-73dc-11eb-8b6c-3555ff2377af.png)

**Comment by ashik685** [comment]
It should be 1 column , otherwise, if I use btngroup as you see, I can not position them with selectbox or textbox.

it shows very bad

**Comment by ashik685** [comment]
Also field type note issue still not solved, it duplicate itself.

**Comment by Quy** [comment]
Fixed in PR #32422.

Please test using the nightly builds: https://developer.joomla.org/nightly-builds.html
