### ISSUE TITLE
No Trash Action when Status filtered

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#32472]
### Steps to reproduce the issue

- Go in backend to Article page.
- Select status in filter Publish or Archived or All
- Select an article
- Open Action 

### Expected result
You have option to trash item
![immagine](https://user-images.githubusercontent.com/906604/108600528-f0ac1f00-7397-11eb-9ade-ce2f4fa413da.png)

### Actual result
No Trash Option:
![immagine](https://user-images.githubusercontent.com/906604/108600535-f7d32d00-7397-11eb-9fc8-3df58a115e89.png)

**Comment by joomdonation** [comment]
It causes by a small typo in the code. PR #32474 should fix it.
