### ISSUE TITLE
Admin template on install (missing or misconfigured)

### ISSUE THREAD

**Issue by leerlemoniii** [joomla/joomla-cms#32478]
### Steps to reproduce the issue
fresh install of the Joomla, go to admin

### Expected result
admin site should work and look correctly

### Actual result
template is set to look for the isis template on the admin, but that template is not in the zip file.  
Either it is expected that the template should be one of the other templates (protostar/beez3/system) and that should be set by the install, or the isis theme should come in the install.

In the very least there should be a warning that you need to install this theme from
https://github.com/asika32764/joomla-bootstrap3-isis-template

at the end of the install process.

### System information (as much as possible)
I have run this on multiple systems (windows/linux/mac) using nginx, and mariadb usually.  But also on apache mysql

**Comment by chmst** [comment]
@leerlemoniii the backend template isis is part of the joomla package, no need to donwload or install something extra. 
Which error dod you get? Have you tried to clear your browser cache? 

Please ask this question in the forum.joomla.org.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32478">issues.joomla.org/tracker/joomla-cms/32478</a>.</sub>

**Comment by leerlemoniii** [comment]
the isis template is not in the download .zip package, and it is not in the
git repo as far as I can tell either.
in the browser the error was that the isis directory (and files etc.) could
not be found.

getting the isis files and putting them in the template directory fixed
immediately.
here is an snipp of the unzipped package as I downloaded it.  So maybe this
was left out of the build system accidentally, but it is not in the
download from joomla site.
[image: image.png]

**Comment by leerlemoniii** [comment]
looking further at this.. the isis is in the admin template directory, but
the system seems to be looking at the main template directory.

**Comment by leerlemoniii** [comment]
I again removed my isis template from the main template directory and got
the following errors in the browser
[image: image.png]

**Comment by chmst** [comment]
The Code of the isis template is here: https://github.com/joomla/joomla-cms/tree/staging/administrator/templates/isis
And it is in every downloaded Joomla package of version 3. 

So sorry I don't understand what you are doing. Where did you download your Joomla package? from here  https://downloads.joomla.org/?

**Comment by leerlemoniii** [comment]
yes I downloaded from https://downloads.joomla.org/

I think the real problem is that for some reason the admin is using the
themes from the path
/templates
when I think the admin should be using them from the path
/administrator/templates
in which case you are correct the isis theme is in that path, but that is
not where it is trying to get the files from.
I will when I have some time try and dig through the code to figure why is.

thanks for the attempts to help anyways :)

**Comment by richard67** [comment]
Did you unpack the zip into an empty folder? Or was there some .htaccess file present? Or is there something else doing strange redirects? There are some extensions available to hide the admin area so it can’t be reached with the normal URL. Maybe something left of such tools? Or maybe a security feature by the provider, also something doing strange redirects?

**Comment by richard67** [comment]
I only can guess. Never heard of such a strange error before.

**Comment by richard67** [comment]
Next question: The folder where Joomla is unpacked to and then installed, is it the root folder of the domain? Or is it a sub-folder?

**Comment by brianteeman** [comment]
This really should be a question for the forum

**Comment by richard67** [comment]
Agree.

@leerlemoniii Please use https://forum.joomla.org/ to get help with your issue. Thanks in advance.
