### ISSUE TITLE
Custom Category Fields Losing Data If Unpublished - Not Displaying Fields Unless Published

### ISSUE THREAD

**Issue by SafetNS** [joomla/joomla-cms#32489]
### Steps to reproduce the issue
1. Create a Category:
   1.1. Navigate to Content > Categories > New
   1.2. Set the category title and then click 'Save & Close'. No other field entry is required.

2. Create a new custom field: Navigate to Content > Fields.
   2.1. Navigate to Content > Fields
   2.2. Select filter dropdown at the top of the page (which defaults as Articles) and select Cateogry.
   2.3. Click (+)New to create a new field.
   2.4. Set the title, remove 'All' from the Category field, and add the newly created category. The field type will default to text. Save & Close.

3. Navigate back to the newly created category (Content > Categories) and select it for editing.
   3.1. You will notice the new 'Fields' tab appear with your new field. Enter some data into the new field and Save.
   3.2. Now change the publication 'Status' to 'Unpublished' and then save.
   3.3. Notice the bug: the 'Fields' tab has disappeared. It will return if you change the status to 'Published' and click 'Save' again. The data however, will now have been cleared.
   

### Expected result

At stage 3.3 the 'Fields' tab and the custom field should remain after saving the status as 'unpublished'.  One can reproduce a desirable outcome only if they leave the 'All' option in the Category field on stage 2.  In other words, changing the category to a specific category will create this undesired outcome.

### Actual result

At stage 3.3, the custom 'Fields' tab should remain, along with its data, regardless of the 'Published/Unpublished' Status.

### System information (as much as possible)

Joomla! 3.9.21 
PHP 7.3.23

**Comment by chmst** [comment]
@SafetNS I tried to reproduce this issue. Strange enough .. I followed your description several times and always the field was correct - but suddenly I had the issue you described here. 
But could not replicate it again. Can you remember anything what could be the context?

**Comment by ChristineWk** [comment]
Tried also several times and can't reproduce point: 3.3
Still shown under: Fields > Category > Status: x (set to unpublished) > type text >

 ![screen shot 2021-03-13 at 11 05 24](https://issues.joomla.org/uploads/1/d44fdb83e61dca5af3f7f227905ac59c.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32489">issues.joomla.org/tracker/joomla-cms/32489</a>.</sub>

**Comment by ChristineWk** [comment]
OK, tried again, because I forgot 1 step. 

![screen shot 2021-03-13 at 19 30 07](https://issues.joomla.org/uploads/1/d16dad4a9efdf190736f2c2b0b782781.jpg)

Category One: Set to unpublished > Field one not shown:
![screen shot 2021-03-13 at 19 32 09](https://issues.joomla.org/uploads/1/2bc1b64afd1bab5691ca322925eb3b2e.jpg)

Category Two: Set to published > Field two is shown
![screen shot 2021-03-13 at 19 32 47](https://issues.joomla.org/uploads/1/9a4e6fe89ec46adb2c26c1dce01bfbd5.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32489">issues.joomla.org/tracker/joomla-cms/32489</a>.</sub>

**Comment by joomdonation** [comment]
I'm closing this issue because Joomla 3 is now in maintenance mode and will only receive security fixes, not bugs fixes. This is the same with other issue reported for Joomla 4 https://github.com/joomla/joomla-cms/issues/31869. If that is valid, we will fix it for Joomla 4.
