### ISSUE TITLE
enable Paste as plain text function by default

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#32499]
### Is your feature request related to a problem? Please describe.

using ctrl+v j4 users paste a lot or garbage

### Describe the solution you'd like

enable Paste as plain text function by default, and that way simply remove all formatting, styling, links and etc.

**Comment by brianteeman** [comment]
I am assuming that you are referring to the tinymce wysiwyg editor ?

If so then there are a lot of paste configuration options that could be enabled (https://www.tiny.cloud/docs/plugins/opensource/paste/) 

The ability of tinymce to strip out garbage is so much better in tinymce v5 used in J4 that on a personal level I wouldn't want it to be disabled by default.

**Comment by ghost** [comment]
Which is way over my head. From what I have been able to deduce there are not possible in tinymce wysiwyg to not let users not to use ctrl+v command.

And if user use ctrl+v all formatting, styling, links and etc. remain. Formatting is not removed in tinymce.

**Comment by drmenzelit** [comment]
Closing this as it is not an issue. Feel free to open a discussion topic or ask in the forum for help with the configuration of TinyMCE.
