### ISSUE TITLE
Squash.io integration?

### ISSUE THREAD

**Issue by emiquelito** [joomla/joomla-cms#32495]
### Is your feature request related to a problem? Please describe.

It's not currently possible for Joomla Developers to quickly check the fully deployed branch of code for each PR, and in isolation.

### Describe the solution you'd like
Hello Joomla Community!

I'm with [Squash.io](https://www.squash.io/) and we wanted to support the Joomla project by providing on-demand test environments for each Pull Request (i.e: a complete staging environment for each PR, running your full stack). Our service is free for Open Source projects like Joomla and we would be able to increase our standard limits as needed to provide great user experience for Joomla developers and contributors.

Here is how it works, you push a branch of code, create a Pull Request and Squash automatically posts as comment with a unique URL where you can test the branch changes in isolation (it usually takes just a few minutes for an environment to spin up):

![squash-url](https://user-images.githubusercontent.com/98694/108773052-0c8bfe00-751b-11eb-8fad-7334b11b80bf.png)

Squash can also spin up a new environment for each commit within a PR, and give you a pass or fail if it can receive a success HTTP response. You can also run any existing front-end tests (Selenium, TestCafe, etc) on top of this Squash environment.

![squash-check2](https://user-images.githubusercontent.com/98694/108773348-6ee4fe80-751b-11eb-92e3-d9262192264e.png)

### Squash setup

Let me know if you like the idea of using Squash on this project. If so, we would be happy to create a Pull Request with a Squash YAML file so you don't have to invest any time on this.

**Comment by Llewellynvdm** [comment]
How many instances would be made available to us?

**Comment by emiquelito** [comment]
@Llewellynvdm thanks for reaching out. I'd suggest starting with 20 concurrent environments (for the regular test environments) and grow this number as needed. We can also allocate the same amount (on top of the regular environments) for the [automated checks](https://www.squash.io/docs/automated-checks/), if that's of interest.  

Let me know what you think, we are happy to accommodate enough concurrency to support the community and ensure a great user experience.

**Comment by Hackwar** [comment]
Hello @emiquelito, thank you for your offer, but I don't think we need the service Squash provides right now. Considering our numbers and the setups we have otherwise, it seems unlikely that we would find a solution that works for both you and us.

**Comment by bembelimen** [comment]
As @Hackwar said...

**Comment by emiquelito** [comment]
Hey @Hackwar and @Llewellynvdm I hope all is well, it's been a while since our last discussion.

Are you currently happy with your process of testing each Pull Request from an end user perspective? would it be helpful to have an automated way for commissioning full stack deployments so you can test each branch in isolation (including on different PHP or MySQL versions, etc)?

Lots have changed on our end and I'd be happy to offer unlimited environments to support Joomla, we love Open Source and would like to give back to the community.

We have used Joomla in the past and we would be happy to provide integration samples (Squash uses a standard YAML file) so you don't have to spend time on this.

Thanks

**Comment by Hackwar** [comment]
I answered here: [#37414](https://github.com/joomla/joomla-cms/discussions/37414)
