### ISSUE TITLE
[4.0] PHP8 Undefined array key "blog_class"

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#32493]
### Steps to reproduce the issue
Install Joomla_4.0.0-beta7-Beta-Full_Package.zip followed by "Upload & Update" with the same file. 

### Expected result
No warnings

### Actual result

Undefined array key "blog_class" on 2 lines

https://github.com/joomla/joomla-cms/blob/ee672c01642f41c4e35e7907bf572040247c858e/administrator/components/com_admin/script.php#L7087

https://github.com/joomla/joomla-cms/blob/ee672c01642f41c4e35e7907bf572040247c858e/administrator/components/com_admin/script.php#L7089

### System information (as much as possible)
J4B7 Windows 10, PHP8

**Comment by chmst** [comment]
@Harmageddon could you please have a look here?

**Comment by alikon** [comment]
please test #32547

**Comment by Harmageddon** [comment]
Thank you @jsubri for your report and @chmst for the ping! :-) See #32547.
