### ISSUE TITLE
Tagline field longer than 43 characters on Cassiopeia

### ISSUE THREAD

**Issue by mariantanase** [joomla/joomla-cms#32507]
### Steps to reproduce the issue
Go to admin area > System > Site Template Styles > Cassiopeia-default
Insert a fairly long text on the **Tagline** field (more than 43-44 characters).

### Expected result
![Screenshot_2021-02-24 Home](https://user-images.githubusercontent.com/3976174/108999382-7edb1a80-76a2-11eb-97fe-31ea368ced4c.png)

### Actual result
![cassiopeia-on-mobile](https://user-images.githubusercontent.com/3976174/108999265-5a7f3e00-76a2-11eb-8305-655d0b1c4eac.png)

### System information (as much as possible)
Joomla 4.0.0-beta8-dev
PHP 7.4.4

### Additional comments
Incorrect display on mobile devices when the length of the tagline field in the template is longer than 43 characters.
It seems that the white-space:nowrap instruction from .navbar-brand class it causing this unexpected issue.

**Comment by richard67** [comment]
Ping @drmenzelit : Seems to be a CSS issue. Could you have a look on it? Thanks in advance.

**Comment by drmenzelit** [comment]
Please test #32509
