### ISSUE TITLE
site Article frontend submit set default language bug

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#32513]
site Article frontend submit set default language

Testing instructions

monolingual site where back-end language English UI is used for the back-end part as default language

frontend language French

monolingual site where French UI is used for the site part as default language

Create menu item to set to use category and its subcategories and several other categories, but not all categories.

Let users submit articles from frontend only in French language

The problem is we get these options: All, English, French. And default is shown as All.

We want to see default language French as in this picture, but we get All.
![1](https://user-images.githubusercontent.com/76512236/109134375-a4c5f500-775e-11eb-9667-b6ecd4fe1b7c.png)

Maybe someone knows where is this code ? In what file ? What line?
(What code makes default All, or French or English?)

new j3.24 site, default Protostar template

**Comment by ghost** [comment]
Maybe we should update documentation on this , because no answer in forum.

**Comment by infograf768** [comment]
Where is your forum post?

**Comment by brianteeman** [comment]
1. You have the language filter plugin enabled. For a monolingual site you do not need this - and this is the cause of all your problems
2. Go to the installed  languages page `administrator/index.php?option=com_languages&view=installed` and make sure that you have set French as the default language for the admin and english as the default language for the site
3. unpublish the language switcher site module

Job done

**Comment by infograf768** [comment]
English for admin and French for site ;)
Also, once done , the language chosen in the Create article menu item is totally useless and will have no impact on your site.

**Comment by infograf768** [comment]
Then if you want your users to NOT be confused, make an override of `/components/com_content/views/form/tmpl/edit.php`
Modify 
```
			<?php echo JHtml::_('bootstrap.addTab', $this->tab_name, 'language', JText::_('JFIELD_LANGUAGE_LABEL')); ?>
				<?php echo $this->form->renderField('language'); ?>
			<?php echo JHtml::_('bootstrap.endTab'); ?>
```
with
```
			<?php echo JHtml::_('bootstrap.addTab', $this->tab_name, 'language', JText::_('JFIELD_LANGUAGE_LABEL')); 			<?php echo JHtml::_('bootstrap.addTab', $this->tab_name, 'language', JText::_('JFIELD_LANGUAGE_LABEL')); ?>
			<?php echo JHtml::_('bootstrap.addTab', $this->tab_name, 'language', JText::_('JFIELD_LANGUAGE_LABEL')); ?>
				<?php $this->form->setFieldAttribute('language', 'default', 'fr-FR'); ?>
				<?php $this->form->setFieldAttribute('language', 'readonly', true); ?>
				<?php echo $this->form->renderField('language'); ?>
			<?php echo JHtml::_('bootstrap.endTab'); ?>
				<?php $this->form->setFieldAttribute('language', 'readonly', true); ?>
				<?php echo $this->form->renderField('language'); ?>
			<?php echo JHtml::_('bootstrap.endTab'); ?>
```

You will get
<img width="499" alt="Screen Shot 2021-02-25 at 11 21 07" src="https://user-images.githubusercontent.com/869724/109139254-9aeec280-775b-11eb-8dcc-858d24848419.png">

**Comment by ghost** [comment]
Language switcher site module is not created, do we need to create it ? and then unpublish?

It is set english as the default language for the admin and French as the default language for the site

I see:
Language Code is unpublished, do we need to enable it?
Language Filter is unpublished

Also I see Content languages
English is unpublished
French is published

**Comment by infograf768** [comment]
Use forums
https://forum.joomla.org/viewforum.php?f=711

**Comment by drmenzelit** [comment]
@chnnst check the plugin System - Language Filter, that should be disabled

**Comment by drmenzelit** [comment]
Closing this as it is not a bug. Feel free to ask for help in the forum.
