### ISSUE TITLE
Folder «installation» not being deleted

### ISSUE THREAD

**Issue by crimle** [joomla/joomla-cms#32516]
### Steps to reproduce the issue

- Download Joomla 4.0.0-beta7-dev as a zip file
- unpack zip file locally 
- upload files to webserver using FTP
- start installation by using any webbrowser
- at step 5 «Congratulations! Your Joomla! site is ready.» choose «Install additional languages»
- select «German DE» 
- in the next step select «German DE» as default language (2x)
- click [Set default language]
- now click the red button [Remove "installation" folder]

### Expected result

The folder [installation] should have been removed.

### Actual result

The folder [installation] is still there.

### System information (as much as possible)

Joomla 4.0.0-beta7-dev
PHP 8.0.1
MySQLi 10.2.33-MariaDB-log 

### Additional comments

This happens when you choose an additional language towards the end of installation.
If at step 5 you do not choose an additional language but immediately click [Remove "installation" folder] the folder [installation] will b removed all right.

**Comment by infograf768** [comment]
Can't confirm this on 4.0-dev as of today.

**Comment by crimle** [comment]
There is an error in the tag «Build: 4.0.0-beta8-dev». I was using Joomla 4.0.0-beta7-dev downloaded today from https://github.com/joomla/joomla-cms/releases/tag/4.0.0-beta7. I did three test-installations with this package: 
1. choosing an additional language towards the end of installation.
2. NOT choosing an additional language towards the end of installation.
3. choosing an additional language towards the end of installation.

Installation 1 and 3 the folder "installation" was not deleted.

**Comment by Quy** [comment]
@crimle Please test using the Joomla nightly builds: https://developer.joomla.org/nightly-builds.html

**Comment by crimle** [comment]
I was testing again with the nightly build right now. 
Despite my clicking the red button [Remove "installation" folder] the folder was NOT deleted.
Please note: the error only occurs, when choosing an additional language towards the end of the installation.
See attached screenshot.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32516">issues.joomla.org/tracker/joomla-cms/32516</a>.</sub>

**Comment by chmst** [comment]
Confirmed on a fresh 4.0 dev.
Install a laguage and SET IT AS DEFAULT. Then the installation folder remains after delete button.

**Comment by infograf768** [comment]
@chmst 
I did that setting French as default for admin and site.
I had my test site folder open on the desktop and saw the installation folder being deleted.
My test was done locally.

**Comment by infograf768** [comment]
Please open Console to see any js error

**Comment by dgrammatiko** [comment]
The delete is not working on a dev env, it's not a bug

**Comment by chmst** [comment]
Delete is working if no language is selected or the language is not set as default. I tested several times on win 10, xampp, php 7.4.
I performed the tests in a local environment, always the same directory

**Comment by chmst** [comment]
So either it is a bug that the folder ist deleted as @infograf768 and I can see, or it is strange that the folder remains in some situations as @crimle and I have seen ... as long as we are in development is makes no difference.

**Comment by brianteeman** [comment]
@dgrammatiko the difference between a dev and release is that you do not have to delete the installation folder. You should still be able to its just not required

**Comment by infograf768** [comment]
The point here is not that it does not have to be deleted on the dev.
The OP says the button does not work. My tests here show that it works in the conditions stated (install language, make it as default).
The event here is present and the js is working as should.
Maybe a permissions issue? Not sure as I can’t reproduce.

**Comment by infograf768** [comment]
MAMP Macintosh Firefox PHP 7.4.2
Here are some screenshots.

<img width="813" alt="Screen Shot 2021-02-26 at 08 20 48" src="https://user-images.githubusercontent.com/869724/109268894-03957800-780c-11eb-8c54-8a9f7d2654b0.png">

![deletefolder](https://user-images.githubusercontent.com/869724/109268923-0f813a00-780c-11eb-8658-0be2a68acff2.gif)

Console result


<img width="1405" alt="Screen Shot 2021-02-26 at 08 23 09" src="https://user-images.githubusercontent.com/869724/109268966-1e67ec80-780c-11eb-9baf-8aaff0f7a69f.png">

**Comment by crimle** [comment]
@infograf768
Did you just select «German (Germany)» using the radio buttons? 
Or did you click the [Set default language] button afterwards?
And after that the [Remove "installation" folder?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32516">issues.joomla.org/tracker/joomla-cms/32516</a>.</sub>

**Comment by infograf768** [comment]
Oops.. I did not use the set default language button

testing again

**Comment by infograf768** [comment]
I confirm the bug and console does not show any error...

**Comment by infograf768** [comment]
@dgrammatiko @Fedik 
Looks like the issue is in the remove.js

**Comment by Fedik** [comment]
I not tested, but js  just showing the result. And because the response is 200 it thinks that all is okay.

The bug may be due this `TODO`:
https://github.com/joomla/joomla-cms/blob/60f2f0d793faf86ccda52ee2569fbebaf12277cc/installation/src/Controller/InstallationController.php#L267-L277

If there any error happen during `InstallationController::delete()` it should return error response, but it just stays silent.

**Comment by Fedik** [comment]
Additionally, this section totaly ignored (because that `TODO`):

https://github.com/joomla/joomla-cms/blob/60f2f0d793faf86ccda52ee2569fbebaf12277cc/installation/src/Controller/InstallationController.php#L261-L266

**Comment by infograf768** [comment]
### Note
The Remove Installation folder button only exists if we are in development...

```
<?php if ($this->development) : ?>
<div  class="alert flex-column mb-1"  id="removeInstallationTab">
<span  class="mb-1 font-weight-bold"><?php  echo Text_('INSTL_SITE_DEVMODE_LABEL'); ?></span>
<button  class="btn btn-danger mb-1"  id="removeInstallationFolder"><?php  echo Textsprintf('INSTL_COMPLETE_REMOVE_FOLDER', 'installation'); ?></button>
</div>
<?php endif; ?>
```
If I set the Version param to `stable`, then it does not show at all.

Then if I test without installing extra languages and just click Complete and Open (site or admin), the installation folder is not deleted at all and we do not get to site or admin
we have a real mess here

**Comment by C-Lodder** [comment]
I'm having issues with this.

J4 beta 7 installation on live environment.

1. Clicking the `Remove Installation Folder` doesn't remove the folder
2. After removing it manually, the frontend loads, but the backend redirects to `site.com/installation/index.php`

**Comment by ghost** [comment]
I just checked a page that I had installed with Joomla Beta 7 online. I added a second language here, which is the default language. **The installation folder was not deleted.** I did not check this at the time of installation.

Just now I tested this again locally. If you select another language and set it as default, then the installation folder is not deleted. There is also no hint or error displayed. You click the delete button and assume that the directory is deleted. You can continue to navigate to site or admin normally.

I'm sure there are a few installations that are online and their webmasters don't read this issue. What happens with this? Is there any way to ensure that the directory is deleted in a future update?

**Comment by dgrammatiko** [comment]
> Then if I test without installing extra languages and just click Complete and Open (site or admin), the installation folder is not deleted at all and we do not get to site or admin
we have a real mess here


I'll bet that the session is different on the last page than the one on the previous page. I thought this was fixed...


EDIT: can someone test the following: add

```js
Joomla.replaceTokens(successresponse.token);
```

after https://github.com/joomla/joomla-cms/blob/0553bdb85a6880879c066d532a2b33f8e0119082/installation/template/js/remove.js#L97

**Comment by infograf768** [comment]
@dgrammatiko 
Does not work here.

There are also other problems to solve when this one is done.

**Comment by dgrammatiko** [comment]
> Does not work here.

Yes it needs also passing the token from the PHP side `$r->token = $app->getFormToken();` in both set and setdefault functions on `installation/src/Controller/LanguageController.php`

**Comment by infograf768** [comment]
@dgrammatiko 
Alas this does not work here.

**Comment by Fedik** [comment]
@dgrammatiko is right, it a session issue, server response for `task=installation.removeFolder`:

![Screenshot_2021-03-01_20-07-42](https://user-images.githubusercontent.com/1568198/109539452-01604180-7aca-11eb-87e4-aa112a7bda22.png)


Plus javascript issue because it should show that there an error to User

**Comment by infograf768** [comment]
@dgrammatiko 

Please provide patch as a priority. This is an important Release Blocker.
Other notables errors:
The `Remove Installation Folder` button is only displayed when we are in -dev version

The Important Alert 
`INSTL_COMPLETE_REMOVE_INSTALLATION="PLEASE REMEMBER TO COMPLETELY REMOVE THE INSTALLATION FOLDER.<br />You will not be able to proceed beyond this point until the &quot;%s&quot; folder has been removed. This is a security feature of Joomla!"`
is absent from 4.0.

IMHO, we need to modify the remove/default.php to
```
					<div class="alert flex-column mb-1" id="removeInstallationTab">
						<?php if ($this->development) : ?>
							<span class="mb-1 font-weight-bold"><?php echo Text::sprintf('INSTL_SITE_DEVMODE_LABEL', 'installation'); ?></span>
						<?php else : ?>
							<span class="mb-1 font-weight-bold"><?php echo Text::sprintf('INSTL_COMPLETE_REMOVE_INSTALLATION', 'installation'); ?></span>
						<?php endif; ?>
						<button class="btn btn-danger mb-1" id="removeInstallationFolder"><?php echo Text::sprintf('INSTL_COMPLETE_REMOVE_FOLDER', 'installation'); ?></button>
					</div>
```

and modify strings to something like
`INSTL_SITE_DEVMODE_LABEL="We detected development mode.<br>The \"%s\" folder should be deleted if you are not testing on localhost."`
`INSTL_COMPLETE_REMOVE_INSTALLATION="PLEASE REMEMBER TO COMPLETELY REMOVE THE INSTALLATION FOLDER.<br>You will not be able to proceed beyond this point until the \"%s\" folder has been removed. This is a security feature of Joomla!"`

We have also to make sure that, after setting Default Languages by using the `Set default language` button, the final page is no more including the choice to install new languages and setting Default again as we would get in another token issue.

**Comment by dgrammatiko** [comment]
@infograf768 not before finishing the Child templates UI...

**Comment by joomdonation** [comment]
Look like the solution is:

- Add **Joomla.replaceTokens** as @dgrammatiko suggested at https://github.com/joomla/joomla-cms/issues/32516#issuecomment-787519689
- Somehow, we will have to pass the new token on this ajax Request https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/template/js/remove.js#L39

@dgrammatiko @Fedik Do we have a javascript API to get the token from the hidden input, something like **token = Joomla.getToken();** ? I tested by using the code

```
if (form) {
	var data = Joomla.serialiseForm(form);
}
else 
{
     var	data = {};
}
```

then pass that data in ajax request https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/template/js/remove.js#L39 and it works. But I know it is not nice to use that code.

**Comment by Fedik** [comment]
> Do we have a javascript API to get the token from the hidden input

nope, a new token should come from ajax response I think,
something like in comment @dgrammatiko https://github.com/joomla/joomla-cms/issues/32516#issuecomment-787893219

**Comment by Fedik** [comment]
but confusing part is why it changes after set default language,
I cannot find a reason

**Comment by dgrammatiko** [comment]
There is an api Joomla.refreshToken() iirc which takes it from the hidden input

**Comment by Fedik** [comment]
that something new :smile:

**Comment by dgrammatiko** [comment]
It’s a useless piece of code that used only in the installation but still bloating core.js. I mean it’s not the only useless thing in that file 😀

**Comment by dgrammatiko** [comment]
@joomdonation adding the token should be way easier in this case:
```js

// Get the token from the previous response and save it as `token`
Joomla.request({
	method: "POST",
	// Then just append it here
	url: Joomla.installationBaseUrl + '?task=installation.removeFolder&format=json&' + token + '=1',
	perform: true,
	// token: true,
	headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
	onSuccess: function () {
		const customInstallation = document.getElementById('customInstallation');
		customInstallation.parentNode.removeChild(customInstallation);
		const removeInstallationTab = document.getElementById('removeInstallationTab');
		removeInstallationTab.parentNode.removeChild(removeInstallationTab);
	},
	onError: function (xhr) {
Joomla.renderMessages({ error: [xhr] }, '#system-message-container');
	}
	}
);
```

**Comment by joomdonation** [comment]
@dgrammatiko I know adding the token is easy. I was asking to see if we have an easy way to get the token from previous response instead of having to:

- Serialize the whole form inputs and pass it in ajax request like this:

```javascript
var form = document.getElementById('languagesForm');
			
if (form) {
    var data = Joomla.serialiseForm(form);
}
else
{
   var data = {};
}
```

- Or will we have find the token manually, similar with with Joomla.replaceTokens:

```javascript
Joomla.replaceTokens = function (newToken) {
    if (!/^[0-9A-F]{32}$/i.test(newToken)) {
      return;
    }

    var elements = [].slice.call(document.getElementsByTagName('input'));
    elements.forEach(function (element) {
      if (element.type === 'hidden' && element.value === '1' && element.name.length === 32) {
        element.name = newToken;
      }
    });
  };
```

**Comment by joomdonation** [comment]
> but confusing part is why it changes after set default language,
> I cannot find a reason

@Fedik As I understand, for each ajax request, we generate a new token https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/src/Response/JsonResponse.php#L35 , that's why the old token is not valid anymore.

**Comment by Fedik** [comment]
hm, I see now, that explain everything,
so as @dgrammatiko said, this section should update/store the token:
https://github.com/joomla/joomla-cms/blob/d14dcd9f48b8bc22cfebbb076cf99cc4914ab8dc/installation/template/js/remove.js#L96-L101

The token also should be updated in ScriptOptions registry:
```javascript
Joomla.loadOptions({'csrf.token': successresponse.token})
```
because Joomla.request() pick it from there for POST request:

https://github.com/joomla/joomla-cms/blob/d14dcd9f48b8bc22cfebbb076cf99cc4914ab8dc/build/media_source/system/js/core.es6/ajax.es6#L65-L70

Then this basically should be done after every request,  if we update session token every time.

**Comment by joomdonation** [comment]
**Joomla.loadOptions** is what I'm looking for :).

**Comment by richard67** [comment]
@dgrammatiko @joomdonation @Fedik It is a pleasure to me to see how you are working together. These are the times when I love to be here. We are community, free, from all over the world. Thanks a lot for that.

**Comment by infograf768** [comment]
Can't wait to test a working PR ;)

**Comment by dgrammatiko** [comment]
@joomdonation to recap here:

- in php you need to add $r->token = $app->getFormToken(); in both `set` and `setdefault` functions on installation/src/Controller/LanguageController.php
- Adjust the set language js https://github.com/joomla/joomla-cms/blob/d14dcd9f48b8bc22cfebbb076cf99cc4914ab8dc/installation/template/js/remove.js#L90-L105:

```js
function updateToken(token) {
  let options = Joomla.optionStorage;
 options['X-CSRF-Token'] = token;
  Joomla.loadOptions(options)
}

      Joomla.request({
        method: 'POST',
        url: `${Joomla.installationBaseUrl}?view=setup&frontendlang=${frontendlang}&administratorlang=${administratorlang}&task=language.setdefault&format=json`,
        perform: true,
        token: true,
        headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
        onSuccess(response) {
          const successresponse = JSON.parse(response);
          if (successresponse.messages) {
            Joomla.renderMessages(successresponse.messages, '#system-message-container');
updateToken(successresponse.token) 
          }
        },
        onError(xhr) {
          Joomla.renderMessages({ error: [xhr] }, '#system-message-container');
const successresponse = JSON.parse(response); // This might need a try/catch
updateToken(successresponse.token) 
        },
      });
```

That should be all 4-5 lines of code needed here


EDIT Oops the Joomla object needs to be invoked here

**Comment by joomdonation** [comment]
@dgrammatiko It would be simpler than that if **Joomla.loadOptions** works as @Fedik mentioned. I will give it a try later today.

**Comment by dgrammatiko** [comment]
@joomdonation actually what I posted was wrong, the token needs to be updated using `Joomla.loadOptions`

**Comment by joomdonation** [comment]
@dgrammatiko Yes, **Joomla.loadOptions** is the way to go. Tested and it worked.

**Comment by joomdonation** [comment]
OK. I made PR https://github.com/joomla/joomla-cms/pull/32599 which should fix this issue. Maybe more changes will be needed, but the PR should fix this reported issue for now.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32599 . Thanks in advance.
