### ISSUE TITLE
4.0 Dark Mode

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#32523]
### Steps to reproduce the issue

Is there a way that the Casiopea template integrates by default a dark mode as well as its corresponding switch for users from the frontend?

**Comment by dgrammatiko** [comment]
You will be able to do that once cassiopeia transitions to the new template mode (child templates) with a simple override using https://github.com/vinorodrigues/bootstrap-dark-5 instead of the default bootstrap

**Comment by Stuartemk** [comment]
> You will be able to do that once cassiopeia transitions to the new template mode (child templates) with a simple override using https://github.com/vinorodrigues/bootstrap-dark-5 instead of the default bootstrap

This is excellent news! Only what is not resolved is a togle or switch so that the user can change the template or mode from the frontend. Thank you very much @dgrammatiko

**Comment by dgrammatiko** [comment]
@Stuartemk there are plenty such switchers: https://github.com/dgrammatiko/dark-switch, https://github.com/GoogleChromeLabs/dark-mode-toggle/blob/master/src/dark-mode-toggle.mjs You only have to copy the switch to the child template and edit the HTML to include it, pretty straight forward

**Comment by 4digitalworld** [comment]
@Stuartemk I wrote about this earlier - [https://github.com/joomla/joomla-cms/issues/26772](https://github.com/joomla/joomla-cms/issues/26772)
