### ISSUE TITLE
[4.0] Cassiopeia edit buttons and font weights

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#32536]
### Steps to reproduce the issue

Login to front end as user with edit permissions.

### Expected result

Something pretty

### Actual result

Something pretty awful:
![screen shot 2021-02-27 at 10 19 06](https://issues.joomla.org/uploads/1/34b1d146d198f614f5553e42ae58afea.png)

### System information (as much as possible)

I have a repo clone that I have just updated with Eclipse / Egit and run npm ci.

### Additional comments

The button that overlies Typography is almost unusable. I think these edit buttons should somehow be more discreet.

I note that the Cassiopeia template has set the heading weights to a variable that comes out as 700 on my screen. That cramps the module titles and I think it looks better at the default 500. 

I know these are just gripes - but I think worth a mention.

**Comment by Quy** [comment]
Duplicate #32170. Thanks for reporting.
