### ISSUE TITLE
[4.0] PHPMailer error when saving new article in frontend

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#32537]
### Steps to reproduce the issue
Create a user as author.
Create a Create Article menu item set to special access.
Log in frontend as the author user.
Create the article and save,

### Expected result
Save goes OK and a mail is sent to users with sendmail set to 1

### Actual result
<img width="1077" alt="Screen Shot 2021-02-27 at 10 34 08" src="https://user-images.githubusercontent.com/869724/109385116-b986c200-78f1-11eb-9d65-122d5b6a1920.png">

### Additional comments
ref: https://github.com/joomla/joomla-cms/pull/32520

**Comment by joomdonation** [comment]
@infograf768 I checked and could not confirm this error. The email is working OK for me. Maybe the language on your installation is broken? Could you please check and make sure this language item is available in your installation https://github.com/joomla/joomla-cms/blob/4.0-dev/language/en-GB/com_content.ini#L68 ?

**Comment by infograf768** [comment]
Will test on a new clean site

**Comment by infograf768** [comment]
weird.

On my former test site (the one with the error), the Message is correctly displayed in the message manager (otheradmin is an author) but mail is not sent (empty message body)
<img width="874" alt="messageOK" src="https://user-images.githubusercontent.com/869724/109411364-ded30900-79a1-11eb-89f1-b36ce42a37b3.png">

On a brand new clean site no apparent problem.

closing
