### ISSUE TITLE
Call to undefined method Joomla\CMS\Factory::getACL()  after update to Joomla 4 Beta 7

### ISSUE THREAD

**Issue by ABSclub** [joomla/joomla-cms#32545]
### Steps to reproduce the issue
New clone of live system Joomla 3.9.24, CB 2.5.0 latest build, CBSubs 2.5.0 running on localhost under XAMPP.
Extensions used Akeeba backup, Kunena Forum, JEvents

Followed update procedure described in the Joomla announcement. Pre-update check indicated need to update file_fof30 to version 3.7.4 (which I couldn't find out how to do). 

### Expected result
Update from Joomla 3.9 to Joomla 4 with some minor visual differences/difficulties.

### Actual result
Logged in to backend without a problem. Could not load frontend at all, receiving the error message Call to undefined method Joomla\CMS\Factory::getACL()

**Comment by ChristineWk** [comment]
To be sure: You made the update from Joomla! 3.10?
https://www.joomla.org/announcements/release-news/5833-joomla-4-0-0-beta7-and-joomla-3-10-alpha5.html

fof30 belongs to Akeeba. 

https://github.com/akeeba/fof/tree/development

> Logged in to backend without a problem. Could not load frontend at all, receiving the error message Call to undefined method Joomla\CMS\Factory::getACL()

https://issues.joomla.org/tracker/joomla-cms/12257

**Comment by ABSclub** [comment]
Yes, I definitely did. I went from Joomla 3.9 to 3.10 Alpha 5 via the Testing Update Channel with Alpha Stability, then to Joomla 4 Beta 7 via the Custom URL Channel. I followed the instructions exactly. After I got the error I looked up file_fof30 and ascertained that it is used by Akeeba, is now deprecated but cannot be uninstalled. I am going to try again today, uninstalling Akeeba before I update to Joomla 4 to see if that removes the problem.

I am not a developer - just a user with a lot of IT experience.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32545">issues.joomla.org/tracker/joomla-cms/32545</a>.</sub>

**Comment by chmst** [comment]
Kunena Forum, JEvents - can you check if these extension are available for J4? The re-install test should give you some information.
Every test helps. so thank you for reporting.

**Comment by ABSclub** [comment]
I always check compatibility and system requirements in advance of an upgrade (it can save a lot of hassle!).

 

I have confirmed that JEvents, Akeeba Backup and Akeeba Admin Tools are available for J4.

 

Since I last checked, it seems that Kunena have downgraded their J4 compatibility to ‘experimental’ after Joomla decided to implement Bootstrap 5.

**Comment by chmst** [comment]
@ABSclub I have no doubt that you checked the availability of extensions, but available does not always mean "without errors". So the question is: Is it an issue for Joomla or for a extension?

**Comment by alikon** [comment]
`getACL() `  is deprecated
https://github.com/joomla/joomla-cms/blob/228b1dcc0e9073ef2509cbd4165338d29f71bf2b/libraries/src/Factory.php#L311-L330
