### ISSUE TITLE
Footer modules responsive view

### ISSUE THREAD

**Issue by cloudfaction** [joomla/joomla-cms#32553]
### What needs to be fixed

Cassiopeia (DEV8 version) Placing more than 1 module in footer: Responsive, they do not stack but stay next to each other

### Why this should be fixed

Responsive view, they should be below each other

### How would you fix it

Add css: `.footer .grid-child {display:flex; flex: 1 1 300px; flex-direction: column}`

### Side Effects expected

2 or more modules published in footer, will be below each other in responsive view, instead of next to each other

**Comment by chmst** [comment]
Closing as we have a PR.
