### ISSUE TITLE
[4.0] Login Alias - sampledata

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32556]
### Steps to reproduce the issue
Install sample data

In the footer there is a Login Menu link => example.com/login

### Expected result
When you are logged in then it says logout and send you to example.com/log-out

### Actual result
None of the expected results

### Additional comments
You cant use an alias to get the dynamically changing state of a com_isers login link.
Best to change the current footer link to be guest access and to create a new footer link which is an alias to the existing dedicated logout menu item at the registered level

Also a good example for people to see this technique of displaying content to guests only etc

Sorry I tried to create a PR for this but the sample data plugins are still a mystery to me

**Comment by chmst** [comment]
https://github.com/joomla/cassiopeia/issues/202 
I had made the change already - in blog sample data it is no problem, but the 403 after logout should be resolved first.

Make a login link for guest
and a logout link for registered.
Then login - and then logut - and you get tht 403 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32556">issues.joomla.org/tracker/joomla-cms/32556</a>.</sub>

**Comment by chmst** [comment]
My bad - I have found the error with wrong redirect urls. Please test #31711 (new commited fix).



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32556">issues.joomla.org/tracker/joomla-cms/32556</a>.</sub>

**Comment by chmst** [comment]
Closing as this should be fixed with pr #31711
