### ISSUE TITLE
[4.0] [atum] Login page on mobile is too long

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#32560]
### Steps to reproduce the issue

Visit the backend login page on a mobile device or reduce your viewport width.

### Expected result

Login form **inside** the viewport

### Actual result

Login form **outside** of the viewport

![screeny](https://user-images.githubusercontent.com/2019801/109620863-428c3c00-7b32-11eb-8b9e-8f28be59b2e8.png)

**Comment by infograf768** [comment]
Confirmed.

**Comment by infograf768** [comment]
Looks related to
```
.sidebar-wrapper {
    z-index: 1010;
    min-height: calc(100vh - 69px);  // by commenting this it solves the issue here.
    background-color: var(--atum-sidebar-bg);
    box-shadow: 0 2px 4px rgba(0,0,0,.16),0 2px 4px rgba(0,0,0,.23);
}
```

I guess it should be overriden for the loginform

**Comment by infograf768** [comment]
Maybe modifying 
https://github.com/joomla/joomla-cms/blob/705ce67c714bbcd364a3fcb7e13863fb4e5e4147/administrator/templates/atum/scss/blocks/_login.scss#L178-L185

to

```
  .container-main,
  .sidebar-wrapper {

    @include media-breakpoint-down(md) {
      flex: 1 0 100% !important;
      max-width: 100% !important;
      min-height: auto;
    }
  }
  ```
  
  @drmenzelit

**Comment by Quy** [comment]
Duplicate #29119

**Comment by drmenzelit** [comment]
@infograf768 your code will help. But I'm wondering about the order of the elements: in the css the sidebar is defined with order: 2 for small displays
```
@include media-breakpoint-down(md) {
  order: 2;
}
```
but it is overwritten from the class `order-0`
So I'm not sure what to do...

**Comment by infograf768** [comment]
As I am not familiar with “order”, don’t know either.

**Comment by drmenzelit** [comment]
Closing this as we have a PR #32634
