### ISSUE TITLE
[3.9.25- Additional Information link

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32563]
![image](https://user-images.githubusercontent.com/1296369/109684600-565a9100-7b78-11eb-8cde-f46b3186cb11.png)

The link for additional information is obviously wrong and gives a 404

https://www.joomla.org/announcements/release-news/XXXX-joomla-3-9-25.html

**Comment by HLeithner** [comment]
Fixed now thanks

**Comment by djvaez2** [comment]
<a href="http://www.aircoler.ir" rel="dofollow">aircoler.ir </a>
<a href="http://www.airsell.ir" rel="dofollow">airsell.ir </a>
<a href="http://www.ajooran.ir" rel="dofollow">ajooran.ir </a>
<a href="http://www.ajoorsofal.ir" rel="dofollow">ajoorsofal.ir </a>
<a href="http://www.ajorbrick.ir" rel="dofollow">ajorbrick.ir </a>
<a href="http://www.ajornamaesfahan.ir" rel="dofollow">ajornamaesfahan.ir </a>
<a href="http://www.ajornasoz.ir" rel="dofollow">ajornasoz.ir </a>
<a href="http://www.ajorsofalesfahan.ir" rel="dofollow">ajorsofalesfahan.ir </a>
<a href="http://www.ajorsofali.ir" rel="dofollow">ajorsofali.ir </a>
<a href="http://www.ajorsofalin.ir" rel="dofollow">ajorsofalin.ir </a>
<a href="http://www.ajorsoofal.ir" rel="dofollow">ajorsoofal.ir </a>
<a href="http://www.ajorsoofalin.ir" rel="dofollow">ajorsoofalin.ir </a>
<a href="http://www.alamasi.ir" rel="dofollow">alamasi.ir </a>
<a href="http://www.alinclub.ir" rel="dofollow">alinclub.ir </a>
<a href="http://www.alshargh.ir" rel="dofollow">alshargh.ir </a>
<a href="http://www.alumparsco.ir" rel="dofollow">alumparsco.ir </a>
<a href="http://www.aminplatin.ir" rel="dofollow">aminplatin.ir </a>
<a href="http://www.ardakanhebelexx.ir" rel="dofollow">ardakanhebelexx.ir </a>
<a href="http://www.bad20.ir" rel="dofollow">bad20.ir </a>
<a href="http://www.banhcooler.ir" rel="dofollow">banhcooler.ir</a>
<a href="http://www.barytine.ir" rel="dofollow">barytine.ir </a>
<a href="http://www.bloockleca.ir" rel="dofollow">bloockleca.ir </a>
<a href="http://www.bricksofal.ir" rel="dofollow">bricksofal.ir </a>
<a href="http://www.coler-baneh.ir" rel="dofollow">coler-baneh.ir </a>
<a href="http://www.colersara.ir" rel="dofollow">colersara.ir </a>
<a href="http://www.coolerair.ir" rel="dofollow">coolerair.ir </a>
<a href="http://www.coolerbane1.ir" rel="dofollow">coolerbane1.ir </a>
<a href="http://www.coolerbaneh1.ir" rel="dofollow">coolerbaneh1.ir </a>
<a href="http://www.cooleriranian.ir" rel="dofollow">cooleriranian.ir </a>
<a href="http://www.coolershap.ir" rel="dofollow">coolershap.ir </a>
<a href="http://www.dalahooiran.ir" rel="dofollow">dalahooiran.ir </a>
<a href="http://www.damsanat.ir" rel="dofollow">damsanat.ir </a>
<a href="http://www.dehghanscopsang.ir" rel="dofollow">dehghanscopsang.ir </a>
<a href="http://www.divarmasaleh.ir" rel="dofollow">divarmasaleh.ir </a>
<a href="http://www.eutobacco.ir" rel="dofollow">eutobacco.ir </a>
<a href="http://www.hebelex-lica.ir" rel="dofollow">hebelex-lica.ir </a>
<a href="http://www.hebelexco.ir" rel="dofollow">hebelexco.ir </a>
<a href="http://www.hebelexx.ir" rel="dofollow">hebelexx.ir </a>
<a href="http://www.hebelexyazd.ir" rel="dofollow">hebelexyazd.ir </a>
<a href="http://www.hmohkamkar.ir" rel="dofollow">hmohkamkar.ir </a>
<a href="http://www.iranfilmsaveh.ir" rel="dofollow">iranfilmsaveh.ir </a>
<a href="http://www.iranpokeh.ir" rel="dofollow">iranpokeh.ir </a>
<a href="http://www.kashiyazd.ir" rel="dofollow">kashiyazd.ir </a>
<a href="http://www.kgchem.ir" rel="dofollow">kgchem.ir </a>
<a href="http://www.kishairline.ir" rel="dofollow">kishairline.ir </a>
<a href="http://www.kishchips.ir" rel="dofollow">kishchips.ir </a>
<a href="http://www.kolerbaneh.ir" rel="dofollow">kolerbaneh.ir </a>
<a href="http://www.koolerbaneh.ir" rel="dofollow">koolerbaneh.ir </a>
<a href="http://www.lica-hebelex.ir" rel="dofollow">lica-hebelex.ir </a>
<a href="http://www.licablock.ir" rel="dofollow">licablock.ir </a>
<a href="http://www.madanpokeh.ir" rel="dofollow">madanpokeh.ir </a>
<a href="http://www.mahakpakhsh.ir" rel="dofollow">mahakpakhsh.ir </a>
<a href="http://www.masaleh20.ir" rel="dofollow">masaleh20.ir </a>
<a href="http://www.masalehanlin.ir" rel="dofollow">masalehanlin.ir </a>
<a href="http://www.masalehdivar.ir" rel="dofollow">masalehdivar.ir </a>
<a href="http://www.matiz.ir" rel="dofollow">matiz.ir </a>

<a href="http://www.memart24.ir" rel="dofollow">memart24.ir </a>
<a href="http://www.metaliz.ir" rel="dofollow">metaliz.ir </a>
<a href="http://www.modernmosaic.ir" rel="dofollow">modernmosaic.ir </a>
<a href="http://www.modmoz.ir" rel="dofollow">modmoz.ir </a>
<a href="http://www.moozayeek.ir" rel="dofollow">moozayeek.ir </a>
<a href="http://www.mozaeic.ir" rel="dofollow">mozaeic.ir </a>
<a href="http://www.mozaiec.ir" rel="dofollow">mozaiec.ir </a>
<a href="http://www.mozayek.ir" rel="dofollow">mozayek.ir </a>
<a href="http://www.ngo22.ir" rel="dofollow">ngo22.ir </a>
<a href="http://www.nikatek.ir" rel="dofollow">nikatek.ir </a>
<a href="http://www.ogneral.ir" rel="dofollow">ogneral.ir </a>
<a href="http://www.palizceram.ir" rel="dofollow">palizceram.ir </a>
<a href="http://www.parszoroof.ir" rel="dofollow">parszoroof.ir </a>
<a href="http://www.plccenter.ir" rel="dofollow">plccenter.ir </a>
<a href="http://www.pokeghorveh.ir" rel="dofollow">pokeghorveh.ir </a>
<a href="http://www.pokeh24.ir" rel="dofollow">pokeh24.ir </a>
<a href="http://www.pokehahmadabad.ir" rel="dofollow">pokehahmadabad.ir </a>
<a href="http://www.pokehco.ir" rel="dofollow">pokehco.ir </a>
<a href="http://www.pokehforoshi.ir" rel="dofollow">pokehforoshi.ir </a>
<a href="http://www.pokehghooeveh.ir" rel="dofollow">pokehghooeveh.ir </a>
<a href="http://www.pokehghorve.ir" rel="dofollow">pokehghorve.ir </a>
<a href="http://www.pokehiran.ir" rel="dofollow">pokehiran.ir </a>
<a href="http://www.pokehmadani-ghorveh.ir" rel="dofollow">pokehmadani-ghorveh.ir </a>
<a href="http://www.pokehmomtaz.ir" rel="dofollow">pokehmomtaz.ir </a>
<a href="http://www.pokehonlin.ir" rel="dofollow">pokehonlin.ir </a>
<a href="http://www.pokehsanati.ir" rel="dofollow">pokehsanati.ir </a>
<a href="http://www.pokelica.ir" rel="dofollow">pokelica.ir </a>
<a href="http://www.pokesanati-lica.ir" rel="dofollow">pokesanati-lica.ir </a>
<a href="http://www.robocis.ir" rel="dofollow">robocis.ir </a>
<a href="http://www.sakhtemane20.ir" rel="dofollow">sakhtemane20.ir </a>
<a href="http://www.sangscoop.ir" rel="dofollow">sangscoop.ir </a>
<a href="http://www.sangscop.ir" rel="dofollow">sangscop.ir </a>
<a href="http://www.savehrolling.ir" rel="dofollow">savehrolling.ir </a>
<a href="http://www.scoopsang.ir" rel="dofollow">scoopsang.ir </a>
<a href="http://www.scopmohkamkar.ir" rel="dofollow">scopmohkamkar.ir </a>
<a href="http://www.scoppars.ir" rel="dofollow">scoppars.ir </a>
<a href="http://www.scopsang.ir" rel="dofollow">scopsang.ir </a>
<a href="http://www.scopsangdehghan.ir" rel="dofollow">scopsangdehghan.ir </a>
<a href="http://www.scopseramic.ir" rel="dofollow">scopseramic.ir </a>
<a href="http://www.scopstone.ir" rel="dofollow">scopstone.ir </a>
<a href="http://www.sheyp00r.ir" rel="dofollow">sheyp00r.ir </a>
<a href="http://www.sofalbrick.ir" rel="dofollow">sofalbrick.ir </a>
<a href="http://www.sofalinajor.ir" rel="dofollow">sofalinajor.ir </a>
<a href="http://www.soofalinajor.ir" rel="dofollow">soofalinajor.ir </a>
<a href="http://www.spiletcooler.ir" rel="dofollow">spiletcooler.ir </a>
<a href="http://www.stonescop.ir" rel="dofollow">stonescop.ir </a>
<a href="http://www.taraznahid.ir" rel="dofollow">taraznahid.ir </a>
<a href="http://www.toostire.ir" rel="dofollow">toostire.ir </a>
<a href="http://www.tycoelectric.ir" rel="dofollow">tycoelectric.ir </a>
<a href="http://www.zmsco.ir" rel="dofollow">zmsco.ir </a>
<a href="http://www.arouco.ir" rel="dofollow">arouco.ir </a>
<a href="http://www.gspn.ir" rel="dofollow">gspn.ir </a>
<a href="http://www.joomshopping.ir" rel="dofollow">joomshopping.ir </a>
<a href="http://www.taminsanatco.ir" rel="dofollow">taminsanatco.ir</a>
<a href="http://www.xn--mgbv0dm10cxga.com" rel="dofollow">xn--mgbv0dm10cxga.com</a>
<a href="http://www." rel="dofollow"></a>
<a href="http://www.pokehmadani.com" rel="dofollow">pokehmadani.com</a>
<a href="http://www.xn--jhbb5nrg.com" rel="dofollow">xn--jhbb5nrg.com</a>
<a href="http://www.pokehmadani.com" rel="dofollow">pokehmadani.com</a>
<a href="http://www.xn--mgbv0dm10cxga.com" rel="dofollow">xn--mgbv0dm10cxga.com</a>
<a href="http://www.sangscop.com" rel="dofollow">sangscop.com</a>
<a href="http://www.mozaiec.com" rel="dofollow">mozaiec.com</a>
<a href="http://www.izogammarkazi.ir" rel="dofollow">izogammarkazi.ir</a>
<a href="http://www.izogamedelijan.ir" rel="dofollow">izogamedelijan.ir</a>
<a href="http://www.pipe20.ir" rel="dofollow">pipe20.ir</a>
<a href="http://www.polikaloleh.ir" rel="dofollow">polikaloleh.ir</a>
<a href="http://www.xfast.ir" rel="dofollow">xfast.ir</a>
<a href="http://www.hyperupvc.ir" rel="dofollow">hyperupvc.ir</a>
<a href="http://www.mihanupvc.ir" rel="dofollow">mihanupvc.ir</a>
<a href="http://www.pashmshisheh.ir" rel="dofollow">pashmshisheh.ir</a>
<a href="http://www.kavehsim.ir" rel="dofollow">kavehsim.ir</a>
<a href="http://www.simkaveh.ir" rel="dofollow">simkaveh.ir</a>
<a href="http://www.robocis.com" rel="dofollow">robocis.com</a>
<a href="http://www.jamaliasansor.ir" rel="dofollow">jamaliasansor.ir</a>
<a href="http://www.mihanasansor.ir" rel="dofollow">mihanasansor.ir</a>
<a href="http://www.isfahanston.ir" rel="dofollow">isfahanston.ir</a>
<a href="http://www.sangston.ir" rel="dofollow">sangston.ir</a>
<a href="http://www.stonesang.ir" rel="dofollow">stonesang.ir</a>
<a href="http://www.sofalinajor.com" rel="dofollow">sofalinajor.com</a>
<a href="http://www.ajorsofalin.com" rel="dofollow">ajorsofalin.com</a>
<a href="http://www.iranmoghava.ir" rel="dofollow">iranmoghava.ir</a>
<a href="http://www.mooghava.ir" rel="dofollow">mooghava.ir</a>
<a href="http://www.ariaparsco.ir" rel="dofollow">ariaparsco.ir</a>
<a href="http://www.ariaparsco.com" rel="dofollow">ariaparsco.com</a>
<a href="http://www.gallia.ir" rel="dofollow">gallia.ir</a>
<a href="http://www.medicaa.ir" rel="dofollow">medicaa.ir</a>
<a href="https://yaransabz.com" rel="dofollow">yaransabz.com</a>
<a href="https://ajor-store.com" rel="dofollow">ajor-store.com</a>
<a href="https://online-site.ir" rel="dofollow">online-site.ir</a>
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32563">issues.joomla.org/tracker/joomla-cms/32563</a>.</sub>

**Comment by sozzled** [comment]
The wrong "additional information" linkl has not updated on any of my pre-J! 3.9.24 websites.  How has this matter been fixed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32563">issues.joomla.org/tracker/joomla-cms/32563</a>.</sub>

**Comment by infograf768** [comment]
@sozzled 
should be really solved now

**Comment by sozzled** [comment]
Thanks, J-M.  It's working now.
