### ISSUE TITLE
[4.0] User profile after login via com_users

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#32561]
### UX of user profile should be improved
When a user wants to log in via com_users (not via user module) he/she sees the following useless profile. 

<img width="619" alt="profile1-j4" src="https://user-images.githubusercontent.com/1035262/109638192-fbac3f80-7b4d-11eb-8332-6bf94acca699.PNG">

[ ] So why not show at once the profile form if the token must be set? 
[ ] If nothing is to do: write a message like "Welcome, you are logged in -  you can change settings with the button above"
[ ] css for dl-horizontal should be added 
[ ] Instead of the useless "Website default" say what is the default.  
[ ] The hint "save your profile for getting a token" is misleading - the user first has to klick the "edit" button 
[ ] Make the profile-edit  button a real button

**Comment by bembelimen** [comment]
[ ] Going on the login page (by clicking a link) and login should not redirect to the profile but to the last visited page...

**Comment by chmst** [comment]
The screen for menuItem of type login is bad UX.

<img width="1188" alt="login-redirect" src="https://user-images.githubusercontent.com/1035262/109873040-82a40980-7c6d-11eb-8da2-dd9dc2737269.PNG">

As a new user (and in my case as a very old user but with few users in frontend) it seems that the redirect url is set to home, so seems to be correct.  That the SELECT button changes to EDIT after a selection is made is not selfexplaining.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33603 . Thanks in advance.
