### ISSUE TITLE
Extension issue, sp page builder  and JD page builder

### ISSUE THREAD

**Issue by worker106** [joomla/joomla-cms#32576]
### Steps to reproduce the issue
See at #32324 

1 Create a page with SP Page Builder, save it
2 Go to the Joomla menu. 
3 Choose main menu
4 click Home
5 menu item type: click select
6 Menu item Type: Choose SP Page Builder, than page
7 Select Page: ( Select a page ) click on Select

follow the same steps with JD Page Builder 1.11.2

### Expected result
Modal window opens to select the page for the menu item on clicking "Select" #32324 

The modal pop up open to select the page of the menu item

### Actual result
Modal windows to choose page from the page builders do not open. So i can not choose de desired item for the menu
The result is the same in both Page Builder

### System information (as much as possible)
Joomla 4 Beta 7
Sp page builder 3.7.9
JD page builder 1.11.2

Tested with:
Xampp
Apache 2.4.46
Mysql MariaDB 10.4.17
PHP 7.4.15
last Test Joomla 4 Beta 8 dev, nightly build March 9

### Additional comments
i tested this issue with Joomla 4 Beta 6, with this two page builders, there it works fein, the modal window open and i can choose the page of the page builder for the menu item

![screen shot 2021-03-05 at 16 34 04](https://issues.joomla.org/uploads/1/6382c7afc2473ff3d4677e6f4d01a772.png)

**Comment by Quy** [comment]
Please test using the nightly builds: https://developer.joomla.org/nightly-builds.html

**Comment by ssnobben** [comment]
HI I can confirm this issue tested yesterday

Select Page Doesnt Work Sp Pagebuilder 3.7.9 And Joomla 4 B8. Nothing happens when you click on icon Select.

**Comment by worker106** [comment]
I tested it with the Nightly Build  March 04, it do not works with this build<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32576">issues.joomla.org/tracker/joomla-cms/32576</a>.</sub>

**Comment by worker106** [comment]
Tested the issue again with the nightly Build Joomla 4 Beta 8 05 March. The is still there<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32576">issues.joomla.org/tracker/joomla-cms/32576</a>.</sub>

**Comment by rdeutz** [comment]
closing, seems to me an issue with the used extension, because the modal works with core extensions like com_content
