### ISSUE TITLE
[3.9.25] Joomla 3.9.25 was released with __DEPLOY_VERSION__ placeholders...

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32578]
On code review of [Joomla 3.9.25 distributed Zip file](https://downloads.joomla.org/cms/joomla3/3-9-25/Joomla_3.9.25-Stable-Full_Package.zip?format=zip) there are multiple places where `@since __DEPLOY_VERSION__ ` is located and not replaced.

There are SIX `__DEPLOY_VERSION__` in the distributed Joomla 3.9.25 stable zip.

Eg: /administrator/components/com_banners/models/banners.php and other files modified in https://github.com/joomla/joomla-cms/commit/2387bb05a11232245dde236859e1896189b62f0d

```
/**
	 * Method to validate the form data.
	 *
	 * @param   JForm   $form   The form to validate against.
	 * @param   array   $data   The data to validate.
	 * @param   string  $group  The name of the field group to validate.
	 *
	 * @return  array|boolean  Array of filtered data if valid, false otherwise.
	 *
	 * @see     JFormRule
	 * @see     JFilterInput
	 * @since   __DEPLOY_VERSION__
	 */
	public function validate($form, $data, $group = null)
	{
```

## Further issue to be resolved 

Then **after the Joomla 3.9.25 release**, the commit "Reset to dev" https://github.com/joomla/joomla-cms/commit/2387bb05a11232245dde236859e1896189b62f0d then replaced `__DEPLOY_VERSION__` with `3.9.26`

However this is **now factually incorrect**, as the code was actually in 3.9.25 and released, but the `__DEPLOY_VERSION__` was not replaced prior to release.

Someone needs to go through the commit at https://github.com/joomla/joomla-cms/commit/2387bb05a11232245dde236859e1896189b62f0d and manually correct the version numbers :-( 

<img width="975" alt="Screenshot 2021-03-03 at 20 18 50" src="https://user-images.githubusercontent.com/400092/109866832-b24b1580-7c5d-11eb-95a1-059221c8b0b5.png">

<img width="826" alt="Screenshot 2021-03-17 at 17 53 19" src="https://user-images.githubusercontent.com/400092/111514471-affeb600-8749-11eb-9f7c-68d54b6c8349.png">

**Comment by vivek286** [comment]
I want to work on it

**Comment by alikon** [comment]
or just run  `/usr/bin/php /path/to/joomla-cms/build/bump.php -v 3.9.whatever`
before packging 
https://github.com/joomla/joomla-cms/blob/staging/build/bump.php#L324 should do the trick

**Comment by PhilETaylor** [comment]
or... you could **read the actual text of the issue** to understand that would then make it even more factually incorrect /faceplam

**Comment by PhilETaylor** [comment]
What ACTUALLY needs doing:
 
 - Six places in staging need `__DEPLOY_VERSION__` manually replacing with `3.9.25`
 - The places in staging that have `3.9.26` need to be manually replaced with `3.9.25`

**Comment by alikon** [comment]
me neither, 
i'm just guessing what has gone probably wrong or in a wrong order

**Comment by brianteeman** [comment]
More time is spend discussing it and posting screenshots than it would take to fix it

**Comment by PhilETaylor** [comment]
@HLeithner I assume knows what he did wrong I assume, it looks like there was an issue with the copyright year, and so the release was prepared, changed and then prepared again without thought to the knock on effects... and with the last min addition to security fixes. 

This issue documents the knock on effects and what is needed to ensure that the integrity of the `@since` tags is resolved. 

<img width="577" alt="Screenshot 2021-03-17 at 18 01 59" src="https://user-images.githubusercontent.com/400092/111515599-e426a680-874a-11eb-90b4-b74db83b6136.png">

**Comment by PhilETaylor** [comment]
#32731
