### ISSUE TITLE
[4.0] Media version hashes

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32573]
From my understanding all css and js files are loaded with a media query string which is used for cache-busting. Ignoring the question of if the string is created correctly I am seeing some files that only have a version number as the query string or none at all. Is that intended behaviour

![image](https://user-images.githubusercontent.com/1296369/109778057-497f8100-7bfc-11eb-9bb1-587ea721c0c6.png)

**Comment by Fedik** [comment]
Yes, that correct, the assets from /media/vendor contains ?version
Core assets (and other with undefined version property) contains "media version hash" 
The fonts does not contain anything because they loaded by CSS files.

upd: ref comment https://github.com/joomla/joomla-cms/pull/22435#discussion_r221471301

**Comment by Fedik** [comment]
hm, joomla-alert.css should have a version, same as joomla-alert.js, need to look

**Comment by Fedik** [comment]
> joomla-alert.css should have a version

well, it have, but some files is doubled on your screenshot, same for color_standart.css

**Comment by brianteeman** [comment]
> Core assets (and other with undefined version property) contains "media version hash"

Shouldn't every file that is in the user editable area eg /templates have a full hash

**Comment by Fedik** [comment]
> Shouldn't every file that is in the user editable area eg /templates have a full hash

that what I meant, they will have a hash, unless the asset have a specified "version" property https://github.com/joomla/schemas/blob/6f1d84553cff3ff050c29f4c19f58b63bd483ae8/json-schema/web_assets.json#L41-L45

it like this:
1 version property does not exists (or set to `auto`) => use hash, eg file.css?hash
2 version property is empty or set to `false` => no hash, no version query
3 version property has a version value => version value in query, eg file.css?version

case 1 is all core and custom assets, including /templates
case 3 all assets from /media/vendor
case 2 custom assets by someone, there no such in Joomla, but can be added by extensions

**Comment by brianteeman** [comment]
So in my screenshot the following are missing a hash 
- color-standard 
- fontawesome
- joomla-alert

**Comment by Fedik** [comment]
woff2 is a font file, it loaded by browser from parsing CSS, it depend how font-face defined in CSS files, not by Joomla

> color-standard, joomla-alert

If you look on your screenshot you will see they are doubled in some reason, one with version and another without:
![image](https://user-images.githubusercontent.com/1568198/109790372-0207ed80-7c1a-11eb-8860-4a63e9df34b8.png)

I not sure why, looks strange, does they also doubled in the page source HTML?

**Comment by Fedik** [comment]
> fontawesome.css

have a version instead of hash, because the asset defined in /media/vendor, and then file.css overriden in 
`templates/cassiopeia/css/vendor/fontawesome-free/fontawesome.min.css`

upd. after this patch #32541 it will have a hash instead of version

**Comment by brianteeman** [comment]
joomla-alert is not a double. one is in media and the other in the template

**Comment by Fedik** [comment]
why they twice?
to me it looks wrong, can be a bug, need to check

**Comment by dgrammatiko** [comment]
> joomla-alert is not a double. one is in media and the other in the template

I think this one is overridden, eg the template has a valid override of the original (in the media/vendor folder) file. Maybe that's a bug.

A few days ago I did this https://github.com/joomla/joomla-cms/pull/32485 that creates a version hash per static asset (right now only js) which actually is derived from the actual content of the file. It should be way more efficient than invalidating EVERYTHING on each update

**Comment by dgrammatiko** [comment]
One more thing about the fonts, we're doing it WRONG, we need a plugin like https://www.npmjs.com/package/postcss-url-versioner I will do a PR (unless someone is faster here)

EDIT We also need a similar solution for images ( I mean the ones in a SRC attribute)

**Comment by brianteeman** [comment]
I will leave you guys to work out a solution. Not something I can help with. Sorry

**Comment by dgrammatiko** [comment]
@brianteeman here's the solution for the urls: https://github.com/joomla/joomla-cms/pull/32574

**Comment by Fedik** [comment]
about doubled **joomla-alert**, someone who familiar with styling should fix this:
https://github.com/joomla/joomla-cms/blob/5185266c50004b5fb550bec276250c44e886ce15/templates/cassiopeia/scss/vendor/joomla-custom-elements/joomla-alert.scss#L1-L3

it produce css import, and so an extra request:
![image](https://user-images.githubusercontent.com/1568198/109838611-fd116100-7c4e-11eb-8463-3aa00df3601a.png)


**color-standard** I cannot reproduce, I have only 1 and it is hashed

**Comment by dgrammatiko** [comment]
> about doubled joomla-alert, someone who familiar with styling should fix this

Just remove the `.css` ?

**Comment by Fedik** [comment]
may be, may be, not sure why it is not included, something scss specific?

**Comment by dgrammatiko** [comment]
Works for me here

**Comment by brianteeman** [comment]
Resolved elsewhere
