### ISSUE TITLE
[3.9.25] Joomla! Update page has broken link 'Additional Information'

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#32572]
### Steps to reproduce the issue
Update Joomla 3.9.24 to 3.9.25.
Go to Extensions - Joomla! Update.
Click 'Check for Updates'.  
The message 'Checked for updates' is displayed.  Under the heading 'No Updates Available' there are two links, 'Reinstall package URL' and 'Additional Information'.  
Click the link 'Additional Information'.

### Expected result
Some relevant information is displayed.

### Actual result
The link points to https://www.joomla.org/announcements/release-news/XXXX-joomla-3-9-25.html and the page shows '404 Category not found'

### System information (as much as possible)
The issue reproduced in localhost site running Wampserver 3.2.4 with PHP 8.0.2 and the link to 'Additional Information' is broken.

### Additional comments
A remote Linux site with PHP 7.4.14 does not show  information under the heading 'No updates available', only "You already have the latest Joomla version, 3.9.25".
The issue was first reported by a Joomla! Forum user in the 3.9.25 Announcement Discussion at 
https://forum.joomla.org/viewtopic.php?f=9&t=985110&p=3625731#p3625716 - saying the link is broken "in all of my website".

**Comment by infograf768** [comment]
Apparently this should have been solved
https://github.com/joomla/joomla-cms/issues/32563#issuecomment-789074401

But I tested here and it is not.

**Comment by PhilETaylor** [comment]
This is because the XML has not been updated (did anyone flush the CDN cache?)

The publicly visible XML still has the invalid link at https://update.joomla.org/core/sts/extension_sts.xml

```xml
<update>
<name>Joomla! 3.9</name>
<description>Joomla! 3.9 CMS</description>
<element>joomla</element>
<type>file</type>
<version>3.9.25</version>
<infourl title="Joomla 3.9.25 Release">
https://www.joomla.org/announcements/release-news/XXXX-joomla-3-9-25.html
</infourl>
<downloads>
<downloadurl type="full" format="zip">
https://downloads.joomla.org/cms/joomla3/3-9-25/Joomla_3.9.25-Stable-Update_Package.zip
</downloadurl>
<downloadsource type="full" format="zip">
https://github.com/joomla/joomla-cms/releases/download/3.9.25/Joomla_3.9.25-Stable-Update_Package.zip
</downloadsource>
<downloadsource type="full" format="zip">
https://update.joomla.org/releases/3.9.25/Joomla_3.9.25-Stable-Update_Package.zip
</downloadsource>
</downloads>
<tags>
<tag>stable</tag>
</tags>
<sha256>
2e5b1df6f0c182eef4419d1017c811e4ba2db6c1bcbe8ac6d9216725d090465f
</sha256>
<sha384>
4d53e46a7c9d27144a8cd31aa15d312e13602d238418fc6517778c03d25a2d07c50e1247f5e5a8275ed330a70a174dfd
</sha384>
<sha512>
8d3e322de2b8b3114724d4d3b58f3fad3b505943a56bb521aa67776af2856befdbc49b531e097d096b3241eecdd6177bd65bc141e923a76aab0740006d0490ba
</sha512>
<maintainer>Joomla! Production Department</maintainer>
<maintainerurl>https://www.joomla.org</maintainerurl>
<section>STS</section>
<targetplatform name="joomla" version="3.[789]"/>
<php_minimum>5.3.10</php_minimum>
</update>
```

**Comment by HLeithner** [comment]
Fixed it a second time sorry now it works...
