### ISSUE TITLE
[4.0] Beta 7 - Buttons in button groups not reacting

### ISSUE THREAD

**Issue by marcorensch** [joomla/joomla-cms#32588]
### Steps to reproduce the issue

Open a module that uses a button group as parameter setting in the backend (has class btn-group and btn-group-yesno set as attribute).

### Expected result
When toggling a button the actual status is visible.

### Actual result
The clicked status gets reconized and will be saved on save. But there is no visual change of this parameter status when you click the button. 

### System information (as much as possible)
Joomla 4.0 Beta 7

Local MAMP installation

### Additional comments
No JS Error visible in the console
worked for sure till Beta 5 - new Bootstrap related issue?

**Comment by infograf768** [comment]
Please post screenshots of this behavior.

**Comment by marcorensch** [comment]
https://user-images.githubusercontent.com/11912135/110106878-7f626800-7daa-11eb-81ca-c442ee903d2a.mov

Screenshots cannot show the issue that good so i created a short clip.

And before you talking about the repeatable subform: 
It does not matter if the _btn-group styled_ field is inside a repeatabe subform or not.

**Comment by mavrosxristoforos** [comment]
I confirm this problem on local WAMP with every btn-group, btn-group-yesno field or option, in both component forms and module options.
A solution for Yes/No fields is to add layout="joomla.form.field.radio.switcher" in the field xml, but that is not backwards compatible. Maintaining Joomla 3 compatibility is a strong requirement for extension devs right now, especially when we cannot have if-else conditions, which is the case for XMLs.
I also remember that it still worked until Beta 6.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32588">issues.joomla.org/tracker/joomla-cms/32588</a>.</sub>

**Comment by Quy** [comment]
Fixed in #32367.

Please test with nightly builds: https://developer.joomla.org/nightly-builds.html

**Comment by mavrosxristoforos** [comment]
That fixed it for me. Thanks!

**Comment by Quy** [comment]
@mavrosxristoforos Thank you for confirming! Closing as fixed.
