### ISSUE TITLE
Article menu item failing

### ISSUE THREAD

**Issue by trogladyte** [joomla/joomla-cms#32584]
### Steps to reproduce the issue
Make an article.
Make a menu item to that article using Single Article element.
Click menu item.

I made 2 separate menu items, referencing different articles. Both throw 404 errors. Making either one of those articles "Featured" then setting the menu item to Featured Articles displays the article as expected.

**Comment by infograf768** [comment]
System information (as much as possible) ?

**Comment by ghazal** [comment]
J 3.9.x or J 4.0 ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32584">issues.joomla.org/tracker/joomla-cms/32584</a>.</sub>

**Comment by trogladyte** [comment]
4 beta 7.
PHP 7.4.15

**Comment by chmst** [comment]
I cannot replicate this error on j4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32584">issues.joomla.org/tracker/joomla-cms/32584</a>.</sub>

**Comment by brianteeman** [comment]
Sounds like a sef/htaccess setup issue

**Comment by trogladyte** [comment]
SEF set to off, using a vanilla Joomla install, just the way I always start a Joomla site. Never happened before with current/previous versions.

**Comment by chmst** [comment]
@trogladyte I have no clue what happened, but maybe you could renew your installation? Or can open the console and look for js errors?

**Comment by trogladyte** [comment]
Turned on Debug and Maximum error reporting. The 500 pages are giving:

behavior::caption not found.
/home/wwwckde/public_html/iancfi/libraries/src/HTML/HTMLHelper.php:149

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/HTML/HTMLHelper.php:149
2 | Joomla\CMS\HTML\HTMLHelper::_() | JROOT/templates/ian-cfi-march-2021/html/com_content/article/default.php:24
3 | include() | JROOT/libraries/src/MVC/View/HtmlView.php:429
4 | Joomla\CMS\MVC\View\HtmlView->loadTemplate() | JROOT/libraries/src/MVC/View/HtmlView.php:218
5 | Joomla\CMS\MVC\View\HtmlView->display() | JROOT/components/com_content/src/View/Article/HtmlView.php:260
6 | Joomla\Component\Content\Site\View\Article\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:692
7 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/components/com_content/src/Controller/DisplayController.php:125
8 | Joomla\Component\Content\Site\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
9 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
10 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/components/com_content/src/Dispatcher/Dispatcher.php:55
11 | Joomla\Component\Content\Site\Dispatcher\Dispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
12 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:206
13 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:245
14 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:266
15 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:63
16 | require_once() | JROOT/index.php:32

**Comment by joomdonation** [comment]
@trogladyte The problem comes from your override layout JROOT/templates/ian-cfi-march-2021/html/com_content/article/default.php 

Remove that override will solve the issue.

**Comment by trogladyte** [comment]
Thanks Tuan, and apologies everyone - seems **I** created the issue! I'll talk with the dev about it.

**Comment by joomdonation** [comment]
@trogladyte Just for your information, the error happen because you call JHtml::_('behavior.caption') in the code of that override layout. That method was Deprecated in Joomla 3 and removed in Joomla 4, thus you are getting that error. From backward in-compatible changes documentation https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#Manual_Include_Behavior_Removed 

>The caption.js file has been removed from Joomla. Use the native HTML elements figure and figcaption. (You can look at JLayout in layouts/joomla/content/intro_image.php for an example).

As this is not Joomla! issue, please close this issue.

**Comment by timpennington** [comment]
I am getting a similar error:

An error has occurred.
500 behavior::calendar not found.
Call stack
#	Function	Location
1	()	JROOT/libraries/src/HTML/HTMLHelper.php:149
2	Joomla\CMS\HTML\HTMLHelper::_()	JROOT/plugins/content/jssearchjobs/jssearchjobs.php:28
3	require_once()	JROOT/libraries/src/Extension/ExtensionManagerTrait.php:219
4	Joomla\CMS\Application\CMSApplication->loadPluginFromFilesystem()	JROOT/libraries/src/Extension/ExtensionManagerTrait.php:160
5	Joomla\CMS\Application\CMSApplication->loadExtension()	JROOT/libraries/src/Extension/ExtensionManagerTrait.php:94
6	Joomla\CMS\Application\CMSApplication->bootPlugin()	JROOT/libraries/src/Plugin/PluginHelper.php:235
7	Joomla\CMS\Plugin\PluginHelper::import()	JROOT/libraries/src/Plugin/PluginHelper.php:193
8	Joomla\CMS\Plugin\PluginHelper::importPlugin()	JROOT/libraries/src/MVC/Model/FormBehaviorTrait.php:176
9	Joomla\CMS\MVC\Model\ListModel->preprocessForm()	JROOT/libraries/src/MVC/Model/FormBehaviorTrait.php:117
10	Joomla\CMS\MVC\Model\ListModel->loadForm()	JROOT/libraries/src/MVC/Model/ListModel.php:445
11	Joomla\CMS\MVC\Model\ListModel->getFilterForm()	JROOT/administrator/components/com_installer/src/View/Updatesites/HtmlView.php:79
12	Joomla\Component\Installer\Administrator\View\Updatesites\HtmlView->display()	JROOT/administrator/components/com_installer/src/Controller/DisplayController.php:74
13	Joomla\Component\Installer\Administrator\Controller\DisplayController->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:730
14	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
15	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()	JROOT/libraries/src/Component/ComponentHelper.php:389
16	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/AdministratorApplication.php:143
17	Joomla\CMS\Application\AdministratorApplication->dispatch()	JROOT/libraries/src/Application/AdministratorApplication.php:186
18	Joomla\CMS\Application\AdministratorApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:278
19	Joomla\CMS\Application\CMSApplication->execute()	JROOT/administrator/includes/app.php:63
20	require_once()	JROOT/administrator/index.php:32<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32584">issues.joomla.org/tracker/joomla-cms/32584</a>.</sub>

**Comment by joomdonation** [comment]
@timpennington The error comes from a third party plugin content jssearchjobs which you are using on your site. That plugin uses a method which is removed in Joomla 4. You should disable that plugin for now and contact the developer of that plugin and ask him to fix it. It's not an issue with Joomla core .

**Comment by simonevecchi** [comment]
please i have the same error [here](https://www.savemedcoasts2.eu/j3/index.php/en/project/overview "here")

can help me please to know where is the problem?
plugin?
css?

thank so much to everything<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32584">issues.joomla.org/tracker/joomla-cms/32584</a>.</sub>

**Comment by drmenzelit** [comment]
@simonevecchi that is a closed issue. If the explanations here don't help you to solve the problem, please open a post in the forum: forum.joomla.org
