### ISSUE TITLE
Activate Content Plugins

### ISSUE THREAD

**Issue by trogladyte** [joomla/joomla-cms#32583]
### Steps to reproduce the issue
In a module, go to the Advanced tab. The toggle on mine (PageBuilderCK module) was set to ON, but will not accept OFF. 

I have some PHP to add the current year to the copyright. {?php echo date("Y"); ?} In Joomla 3 this works fine as long as I have the DirectPHP plugin installed and published, and Activate Content Plugins is turned ON. In Joomla 4 this combo does not work. The code shows, but not the date, even with DirectPHP published. https://extensions.joomla.org/extension/directphp/ - I see that the plugin has not been updated for 6 years, so maybe there's the problem.

Also, who do I give feedback on the new admin layout?

**Comment by infograf768** [comment]
DirectPHP is not compatible with Joomla 4. (I made here a compatible version which required quite a few modifications)

If you want to discuss J4 admin template please post in https://github.com/joomla/joomla-cms/discussions
Closing as this is not a joomla core issue.
