### ISSUE TITLE
[4.0] com/mod_wrapper uses deprecated iframe attributes

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#32598]
### Steps to reproduce the issue

https://github.com/joomla/joomla-cms/blob/4.0-dev/components/com_wrapper/tmpl/wrapper/default.php#L36-L37

and

https://github.com/joomla/joomla-cms/blob/4.0-dev/modules/mod_wrapper/tmpl/default.php#L25-L26

Both the `scrolling` and `frameborder` are deprecated attributes, so I'd suggest removing these lines of code and also removing any associated parameters for them

**Comment by richard67** [comment]
@zero-24 As you made PR #32596 for the same iframe wrappers, do you think you can make another one for this issue here?

**Comment by zero-24** [comment]
Well removing that options can be done but should be independent from the PR mention.

**Comment by richard67** [comment]
Yes, independently of course.

**Comment by Megh05** [comment]
@C-Lodder @richard67 I am interested to work on this issue. Thank you!

**Comment by richard67** [comment]
@Megh05 Just to it, no need to ask for permission ;-)

**Comment by PhilETaylor** [comment]
Please test #32913

**Comment by richard67** [comment]
Closing as having a pull request. Please test #32913 . Thanks in advance.
