### ISSUE TITLE
[com_content] 'Category View' loads all items on mysql

### ISSUE THREAD

**Issue by trananhmanh89** [joomla/joomla-cms#32612]
### Steps to reproduce the issue
- Site has a category with ~ 30 items
- Site has only one menu item
- Set that menu to any component but not com_content
- Acess category listing by using url `index.php/component/content`
- Open link of category that has ~ 30 items

### Expected result
- As you see, there is no menu with category type, so listing limit should use global config

### Actual result
- As i check, `list.limit` is 0, so joomla will get all items of that category at a time

### System information (as much as possible)
- Joomla 3.9.25
- php 7.2
- mysql 5.7
- os windows 10 - 20H2

### Additional comments
- this issue causes php run out of memory on site has many articles ( in my case is ~ 20,000 items)

**Comment by chmst** [comment]
Your Joomla Version surely is 3.9.25?

**Comment by trananhmanh89** [comment]
> Your Joomla Version surely is 3.9.25?

Oh, sorry.
I correct my info

**Comment by Quy** [comment]
Duplicate #18529?

**Comment by trananhmanh89** [comment]
> Duplicate #18529?

Yeah, same issue, but different way to achieve it

**Comment by rdeutz** [comment]
closing because it is a of duplicate #18529
