### ISSUE TITLE
[4.0] "Live update" tab is wider than others in mobile view

### ISSUE THREAD

**Issue by Bond97** [joomla/joomla-cms#32627]
### Steps to reproduce the issue
1. Install Joomla 4.0.0 beta 8-dev latest
2. Set update server to nightly builds
3. Do "check updates" on update page
4. Joomla will be show "Live update"
5. Use latest version Opera browser for Android to view this page
6. You might use "mobile view" in desktop browsers, but it seems to view same results.

### Expected result

All tabs like "pre-update check", "live update" and "upload and update" are displayed correctly (responsive)

### Actual result

![Screenshot_20210310-081829_Opera](https://user-images.githubusercontent.com/78050514/110620355-f97b5e00-81a9-11eb-80d4-29cb96b7a6db.jpg)

### System information (as much as possible)
Android 9, Opera 62.0.3146.57357, Samsung A8, Joomla 4.0.0 beta 8-dev latest, PHP 7.4.

**Comment by richardandersonss** [comment]
[Straightforward and Easy Procedure to Get an ESA Letter - 2021 Guide.pdf](https://issues.joomla.org/uploads/1/b47bec14d629a41416056a9edd8e66dd.pdf)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32627">issues.joomla.org/tracker/joomla-cms/32627</a>.</sub>

**Comment by krishnasinghdev** [comment]
Will you give me chance to do this ?

**Comment by richard67** [comment]
@GODFATHER0054 No need to ask for permission. Just make a pull request.

**Comment by sksuryan** [comment]
![image](https://user-images.githubusercontent.com/42460131/111651349-270c7b00-882c-11eb-927d-073a16bca9d6.png)

@Bond97 looks pretty responsive to me, not sure what's causing it. I have tested it using Microsoft Edge and Mozilla Firefox.

**Comment by brianteeman** [comment]
@sksuryan exactly as the title says

**Comment by sksuryan** [comment]
![image](https://user-images.githubusercontent.com/42460131/111654736-07c31d00-882f-11eb-84b7-a158bab07e51.png)
![image](https://user-images.githubusercontent.com/42460131/111655234-7902d000-882f-11eb-882d-0ecccb21bcc9.png)

oh my bad sorry, I saw the screenshot and thought it was overflowing, but even in that case @brianteeman I think it's just because it was selected. Otherwise, it's totally fine.

**Comment by Bond97** [comment]
According to recently merged PR "Admin UI Repaint" this issue is fixed
![20210506_155728](https://user-images.githubusercontent.com/78050514/117301960-d0164000-ae83-11eb-9b32-eb5d11e139a3.jpg)
