### ISSUE TITLE
[4.0] Module Style is not applied, if the template name contains "-"

### ISSUE THREAD

**Issue by jos-webservices** [joomla/joomla-cms#32621]
### Steps to reproduce the issue

- copy the Cassiopeia template and name the new template something conatining a "-", e.g. "cassio-peia"
- make the new template style (e.g. "cassio-peia - Default") your new default
- try to apply "Module Styles" of this template - it will not work

### Expected result
Module Styles are applied for templates containing "-" in their name

### Actual result
Module Styles are not applied
![grafik](https://user-images.githubusercontent.com/62727059/110543499-af9f6300-812a-11eb-8c16-9af995f968f2.png)

### System information (as much as possible)
![grafik](https://user-images.githubusercontent.com/62727059/110542946-fb9dd800-8129-11eb-8f68-6f9538b210ac.png)

**Comment by krishnasinghdev** [comment]
Will you give me chance to do this ?

**Comment by drmenzelit** [comment]
@GODFATHER0054 you don't need to ask for permission, you can provide a pull request for this issue, if you want. It will then be reviewed and tested, and hopefully accepted :-)
Thank you for contributing!

**Comment by chmst** [comment]
Assigned to @GODFATHER0054 - good luck :)

**Comment by richard67** [comment]
@jos-webservices If you attempt to copy a template, there is a text shown below the field where you enter the new name, and this text tells to use only letters, numbers and underscores.

![2021-03-13_1](https://user-images.githubusercontent.com/7413183/111025467-a2ad9880-83e4-11eb-9066-d276aabf77e8.png)

This means you shall not use dashes or hyphens "-".

So from my point of view the bug is that you can save the new template with a name which contains a "-" despite of what the text says, or the text is wrong.

The same applies to Joomla 3 by the way, you get the same text there, telling you shall use only letters, numbers and underscores.

@GODFATHER0054 Please check this comment, too, before making a fix which goes the wrong way.

**Comment by brianteeman** [comment]
> So from my point of view the bug is that you can save the new template with a name which contains a "-" despite of what the text says, or the text is wrong.

The text is correct. The problem is that there is no filtering or checks on the input. A simple pattern of [A-Za-z0-9_] would be correct but it will need to have some form of error message as well

**Comment by richard67** [comment]
> The text is correct. The problem is that there is no filtering or checks on the input. A simple pattern of [A-Za-z0-9_] would be correct

Then my first assumption was right, and we need to fix that in this way.

> but it will need to have some form of error message as well

When using a validation rule or creating a new validation rule for that, and add a `validation=...` for that field in the form XML, the error message will always be "Invalid field so-and-so", with "so-and-so" being the field title. I think that's sufficient.

**Comment by brianteeman** [comment]
The field is NOT in an xml file it is directly in `administrator\components\com_templates\tmpl\template\default_modal_copy_body.php`

**Comment by richard67** [comment]
Oh, I see. Thanks.

**Comment by brianteeman** [comment]
It probably should be extracted into an xml

**Comment by joomdonation** [comment]
We actually perform server side validation already https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_templates/src/Controller/TemplateController.php#L153-L154

However, we are using **cmd** filter for **$newName**, so it accepts other characters such as .,-

I haven't tested but I think changes that two lines of code to the below code should help

```php
$newNameRaw = $this->input->get('new_name', null, 'string');
$newName    = preg_replace('#[^a-zA-Z0-9_]#', '', $newNameRaw);
```

The two names will then be compared at https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_templates/src/Controller/TemplateController.php#L189 and will throw an error to prevent the template from being copied.

**Comment by richard67** [comment]
@joomdonation That makes sense to me and should work. If it's the right way to fix it: I don't know.

Funny detail: On my private website I use a copy of the Protostar template, which has a "-" in its name, so either the description text telling to use only characters, numbers and underscores was not there at this time, or I have ignored it. So when I migrate my site to J4 I'll have to fix that.

**Comment by joomdonation** [comment]
@richard67 I don't work with templates, so I don't know, too. I just propose code because we display the message **Letters, numbers and underscore only**

**Comment by richard67** [comment]
Sure, and I agree. Only am thinking if there are maybe some B/C aspects.

**Comment by brianteeman** [comment]
I have looked into the history and from day this copy template functionality was added in Joomla 2.5  there was the description about no dashes https://developer.joomla.org/joomlacode-archive/issue-28472.html

**Comment by richard67** [comment]
So I might have ignored that at that time.

So we can safely add a validation for it in J4, right?

**Comment by brianteeman** [comment]
yes

**Comment by richard67** [comment]
@joomdonation Go for it please.

**Comment by brianteeman** [comment]
OR we spend time working out how to fix the identiified issue here and any others that may appear by allowing the -

I suspect that the reason we dont allow it was because it was "too hard" to find out why the - broke things

**Comment by richard67** [comment]
I'm open for both, the latter (make it work with "-" I would prefer for private reasons ;-) )

**Comment by jos-webservices** [comment]
> I have looked into the history and from day this copy template functionality was added in Joomla 2.5 there was the description about no dashes https://developer.joomla.org/joomlacode-archive/issue-28472.html

Sorry for ignoring that and bringing up this issue instead. I think input validation for the copy name would be the right approach.

**Comment by jos-webservices** [comment]
> I suspect that the reason we dont allow it was because it was "too hard" to find out why the - broke things

Didn't have a look at the code yet, however from checking why it didn't work for me: I suspect the reason for not allowing "-" is the way the module style is saved in the DB. It is saved as [TemplateName]-[ModuleStyle]. Now, if TemplateName has a "-", dividing the two becomes difficult.

**Comment by joomdonation** [comment]
You are right. The module style is saved in **[TemplateName]-[ModuleStyle]** format, see https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Form/Field/ChromestyleField.php#L159 for reference

It is then processed here https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Helper/ModuleHelper.php#L193-L195

Basically, we are using **-** character to separate between template and module style and it causes this restriction. For now, I think it is too late to change this separator, so the best thing we can do is adding validation to prevent creating template which contains "-" in the name. If we all agree with that, I can make a PR later.

**Comment by brianteeman** [comment]
agreed - please make a pr

**Comment by richard67** [comment]
Agree too.

**Comment by joomdonation** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/34196 . Thanks.
