### ISSUE TITLE
Install error when use (configuration.php-dist  --> configuration.php)

### ISSUE THREAD

**Issue by qiaofeng1227** [joomla/joomla-cms#32644]
### Steps to reproduce the issue
OS: CentOS7.9
refer to: 
https://github.com/joomla/joomla-cms/blob/staging/installation/configuration.php-dist
/**
 * @package    Joomla.Installation
 *
 * @copyright  Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved.
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 *
 * -------------------------------------------------------------------------
 * THIS SHOULD ONLY BE USED AS A LAST RESORT WHEN THE WEB INSTALLER FAILS
 *
 * If you are installing Joomla! manually ie not using the web browser installer
 * then rename this file to configuration.php eg
 *
 * UNIX -> mv configuration.php-dist configuration.php
 * Windows -> rename configuration.php-dist configuration.php
 *
 * Now edit this file and configure the parameters for your site and
 * database.
 *
 * Finally move this file to the root folder of your Joomla installation eg
 *
 * UNIX -> mv configuration.php ../
 * Windows -> copy configuration.php ../
 *
 */

### Expected result
![image](https://user-images.githubusercontent.com/43192516/110772468-987d8400-8296-11eb-970e-2d50d5807d99.png)

### Actual result
![image](https://user-images.githubusercontent.com/43192516/110772521-a7fccd00-8296-11eb-8132-0fc9bd822bf8.png)

### System information (as much as possible)
```
[Thu Mar 11 17:01:28.926716 2021] [proxy_fcgi:error] [pid 32208:tid 32208] [client 43.128.22.14:55662] AH01071: Got error 'PHP message: PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /data/wwwroot/joomla/libraries/joomla/session/handler/native.php on line 260'
[Thu Mar 11 17:01:29.737936 2021] [proxy_fcgi:error] [pid 32196:tid 32196] [client 43.128.22.14:55668] AH01071: Got error 'PHP message: PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /data/wwwroot/joomla/libraries/joomla/session/handler/native.php on line 260'
[Thu Mar 11 17:01:30.020371 2021] [proxy_fcgi:error] [pid 32178:tid 32178] [client 43.128.22.14:55670] AH01071: Got error 'PHP message: PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /data/wwwroot/joomla/libraries/joomla/session/handler/native.php on line 260'
[Thu Mar 11 17:01:30.207716 2021] [proxy_fcgi:error] [pid 32202:tid 32202] [client 43.128.22.14:55672] AH01071: Got error 'PHP message: PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /data/wwwroot/joomla/libraries/joomla/session/handler/native.php on line 260'
[Thu Mar 11 17:01:30.904079 2021] [proxy_fcgi:error] [pid 32173:tid 32173] [client 43.128.22.14:55678] AH01071: Got error 'PHP message: PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /data/wwwroot/joomla/libraries/joomla/session/handler/native.php on line 260'
[Thu Mar 11 17:01:32.139939 2021] [proxy_fcgi:error] [pid 32713:tid 32713] [client 43.128.22.14:55686] AH01071: Got error 'PHP message: PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /data/wwwroot/joomla/libraries/joomla/session/handler/native.php on line 260'
[Thu Mar 11 17:01:32.203635 2021] [proxy_fcgi:error] [pid 32208:tid 32208] [client 43.128.22.14:55688] AH01071: Got error 'PHP message: PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /data/wwwroot/joomla/libraries/joomla/session/handler/native.php on line 260'
[Thu Mar 11 17:01:38.188105 2021] [proxy_fcgi:error] [pid 32196:tid 32196] [client 43.128.22.14:55706] AH01071: Got error 'PHP message: PHP Warning:  session_start(): Failed to read session data: user (path: /tmp) in /data/wwwroot/joomla/libraries/joomla/session/handler/native.php on line 260'

```

**Comment by qiaofeng1227** [comment]
![image](https://user-images.githubusercontent.com/43192516/110773251-80f2cb00-8297-11eb-94cb-faf45d9800c9.png)
There is not data in database joomla

**Comment by qiaofeng1227** [comment]
How to install without wizard?

**Comment by drmenzelit** [comment]
Can you please explain what are you trying to do?

**Comment by ReLater** [comment]
> There is not data in database joomla

FIRST you must install/fill the database on your own. See `joomla.sql` here https://github.com/joomla/joomla-cms/tree/staging/installation/sql for your database server type. And before you do that you have to replace `#__` with your database table prefix, e.g. `mx56r_` in that file. See `public $dbprefix` in configuration.php

This is not a Joomla core issue. Something for a forum.

**Comment by Fedik** [comment]
> How to install without wizard?

For clear/new installation you should use "wizard", it will not work without.
Unless you restoring the site from backup.

**Comment by richard67** [comment]
Closing as not a core issue for the reasons stated above. Feel free to ask for support in the support forum https://forum.joomla.org/ .

**Comment by qiaofeng1227** [comment]
> > There is not data in database joomla
> 
> FIRST you must install/fill the database on your own. See `joomla.sql` here https://github.com/joomla/joomla-cms/tree/staging/installation/sql for your database server type. And before you do that you have to replace `#__` with your database table prefix, e.g. `mx56r_` in that file. See `public $dbprefix` in configuration.php
> 
> This is not a Joomla core issue. Something for a forum.

Thank you very much for your reply.
