### ISSUE TITLE
[4] UX field display in ultrawide screeen

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#32643]
### Steps to reproduce the issue

open of config element with 34" screen
the display on field isn't perfect

### Expected result

![image](https://user-images.githubusercontent.com/2539440/110758621-01d8a500-824d-11eb-8618-344d7d8e8e9b.png)

### Actual result

![image](https://user-images.githubusercontent.com/2539440/110758647-0735ef80-824d-11eb-9b6c-8eaa2f4df215.png)

**Comment by Quy** [comment]
Duplicate #27672. Thanks for the report.

**Comment by micker** [comment]
thanks @Quy
