### ISSUE TITLE
[4.0] LDAP and Composer

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32652]
[LDAP support in PHP is not enabled by default. ](https://www.php.net/manual/en/ldap.installation.php)

### Expected result
Composer install runs successfully

### Actual result
Composer fails with 

>   Problem 1
>     - Installation request for joomla/ldap 2.0.0-beta -> satisfiable by joomla/ldap[2.0.0-beta].
>     - joomla/ldap 2.0.0-beta requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
>   Problem 2
>     - Installation request for symfony/ldap v5.2.1 -> satisfiable by symfony/ldap[v5.2.1].
>     - symfony/ldap v5.2.1 requires ext-ldap * -> the requested PHP extension ldap is missing from your system.
> 
> 

### Additional comments
If the host doesn't have LDAP support enabled on their server then a composer install is not possible

**Comment by alikon** [comment]
`composer install --ignore-platform-reqs`
didn't help ?

**Comment by brianteeman** [comment]
That worked - thanks. I did not know about that option

**Comment by alikon** [comment]
https://docs.joomla.org/Special:MyLanguage/J4.x:Setting_Up_Your_Local_Environment

**Comment by brianteeman** [comment]
although it installed with that option (yes I know I should have RTFM) i was getting 500 errors everywhere. 
as soon as i remove those packaged from composer no 500 errors
