### ISSUE TITLE
[4.0] Missing string JFIELD_MEDIA_CONFIRM_TEXT

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32655]
In #30784 the following string was added however it was not added to the language files

https://github.com/joomla/joomla-cms/pull/30784/files#diff-ffc48fe23d772f6461955e77801148ec01945822ae6574126b6cece7f7bccd26R117

Not sure what it is supposed to be

**Comment by dgrammatiko** [comment]
I think it's redundant, the script is not using it (probably should have been removed with https://github.com/joomla/joomla-cms/pull/31425) : https://github.com/joomla/joomla-cms/blob/ccced138e8123ee8ab6c819ceed2ddc1296f2972/build/media_source/system/js/fields/joomla-image-select.w-c.es6.js#L44-L54

**Comment by brianteeman** [comment]
Closed see #32658
