### ISSUE TITLE
[4.0] Modal Popup not working

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#32665]
### Steps to reproduce the issue
Use one of samples from bootstrap V5 (https://getbootstrap.com/docs/5.0/components/modal/)

### Expected result
Modal Popup opens according sample

### Actual result
Modal popups do not work at all (no javascript errors or any other error reported) 

### System information (as much as possible)
Joomla 4.0 Beta 7 with Casiopeia Template)

### Additional comments
Modal works fine with Joomla 3.9

**Comment by dgrammatiko** [comment]
Can you provide the code you used and didn't work? Joomla has numerous modals and all of them are totally functional

**Comment by jschmi102** [comment]
this is a sample which is working with Joomla 3.9.25 and not with Joomla 4.0-beta7 (I changed '< and >')

&lt;!-- Trigger the modal with a button --&gt;
&lt;button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#popup_modal"&gt;Show Modal&lt;/button&gt;&lt;!-- Modal --&gt;
&lt;div id="popup_modal" class="modal fade" role="document"&gt;
  &lt;div class="modal-dialog modal-lg" style="width:450px;"&gt;
    &lt;!-- Modal content--&gt;
    &lt;div class="modal-content"&gt;
      &lt;div class="modal-header"&gt;
        &lt;button type="button" class="close" data-dismiss="modal" title="Close"&gt;&times;&lt;/button&gt;
        &lt;span class="modal-title"&gt;This is a Modal&lt;/span&gt;
      &lt;/div&gt;
     &lt;div id="popup_modal_body" class="modal-body"&gt;Woohoo, you're reading this text in a modal!&lt;/div&gt;
    &lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;

**Comment by dgrammatiko** [comment]
The HTML by itself WILL NEVER WORK, you need to have also the js in the output. Joomla has helper functions for these: 
`HTMLHelper::_('bootstrap.modal');` ref: https://github.com/joomla/joomla-cms/blob/e317fe221b00d67b9e72cc9c4a359e829f20830d/libraries/src/HTML/Helpers/Bootstrap.php#L275

In Joomla 4 you have to **explicitly** add the interactive component you need.

**Comment by jschmi102** [comment]
hi,
Wiith Joomla 3 a user could add html-code in an article which creates a modal popup (this was my sample). Do you mean this is not any more possible with Joomla 4? Is there a solution for this?

**Comment by dgrammatiko** [comment]
READ my comment again: `In Joomla 4 you have to explicitly add the interactive component you need.` You have to load whatever you need either in the component/module or in the template.

**Comment by jschmi102** [comment]
hi, 
pls. advise how I should use this - I added "HTMLHelper::_('bootstrap.modal');" in my php-code but this did not cause adding bootstrap modal jjavascript libs. (could not find docs about this for Joomla4).

**Comment by dgrammatiko** [comment]
Did you added also the namespaced part? HTMLHelper is namespaced and needs to be added with the casual `use Joomla\CMS\... ; `

Also, I have no clue where you try to add this or what is your file you're editing. I've asked you to provide the code and you just pasted some generated HTML, not very helpful...

**Comment by jschmi102** [comment]
hi,
HTML-code for modal popup is genned by my content plugin. For Joomal of course I am adding only namespaced libs (for htmlhelper: . "use Joomla\CMS\HTML\HTMLHelper;").  Code logic is
1. HTMLHelper::_('bootstrap.modal');
2. Generate modal html 
3. return

**Comment by dgrammatiko** [comment]
FWIW your data attributes are wrong, check the bootstrap 5 docs

**Comment by jschmi102** [comment]
what do you mean with "data attibutes".  If joomal4 does not provide bootstrap modal support per default any modal-html won't work.  For me It seems that calling "HTMLHelper::_('bootstrap.modal" does not provide modal support.

**Comment by jschmi102** [comment]
hi,
I tried with original samples from bootstrap 5. This seems to work. I'll check what to change (or what is different) compared to version 3 or 4.

**Comment by brianteeman** [comment]
As @dgrammatiko said it is the data attribute

If you look at your code you posted above they are data-something
If you lok at the bootstrap 5 docs and the code you copied from there they are data-bs-something

The problem is not Joomla it is your misreading of the documentation

**Comment by jschmi102** [comment]
hi,
Thank you all for your help! But if there had been some short info about migrating to bootstrap and Joomla 4, this could have helped to avoid to run into problem. For example:
1. Note - if you are using interactive features of bootstrap you will have to define them using HTMLHelper methods (e.g. "HTMLHelper::_('bootstrap.modal')" for modal support) to have the needed Javascript libraries added.
2. Keep in mind that bootstrap V5 is not upwards compatible with previous versions, therefore you will have to check or change your HTML-code, javascript-code and related style-sheets.

**Comment by dgrammatiko** [comment]
> But if there had been some short info about migrating to bootstrap and Joomla 4,

Joomla is an open source project based on contributions, so why don't you update those missing info to help also other devs?
