### ISSUE TITLE
improper alignment of buttons

### ISSUE THREAD

**Issue by srishty-07** [joomla/joomla-cms#32667]
### What needs to be fixed
1)improper padding of close button and edit button in edit module in frontend 

2)on hover over an icon in the navbar we can add a color change or increase in icon size on hover  of that icon in navbar.

![1](https://user-images.githubusercontent.com/70388131/111034537-32cafc80-843c-11eb-9fa4-c293dcb7de93.jpg)

actual :

![2](https://user-images.githubusercontent.com/70388131/111034545-3b233780-843c-11eb-9a31-63180550ce34.jpg)

 

expected :

![3](https://user-images.githubusercontent.com/70388131/111034551-437b7280-843c-11eb-96a8-af138ef5d662.jpg)
![4](https://user-images.githubusercontent.com/70388131/111034552-44ac9f80-843c-11eb-95c4-5c19f6487b3c.jpg)

### Why this should be fixed
good UI

### How would you fix it
by adding margins and CSS properties in the classes using media queries

### Side Effects expected
nothing

### Are you working on this issue
yes

**Comment by chmst** [comment]
@srishty-07 thanks a lot for starting this. 
I will assign this to you.
Your issue has several tasks and you could make several PRs - one for every part, this makes testing easier. 

For working on the Edit buttons - this is a bit difficult and there is a big issue https://issues.joomla.org/tracker/joomla-cms/32170.

**Comment by srishty-07** [comment]
sure @chmst ma'am ,
I am working on it.

**Comment by chmst** [comment]
Closing as we have a PR #32667
