### ISSUE TITLE
[4.0] Can't save configuration.php changes

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32661]
Open global configuration and make any change and then try to "save and close"

Nothing happens and the javascript console shows the following error
```

Uncaught TypeError: Cannot read property 'toASCII' of undefined
    at Object.exec (validate.min.js?6fbe5f648d8f06284b4402d09e9c776a:formatted:48)
    at t.value (validate.min.js?6fbe5f648d8f06284b4402d09e9c776a:formatted:161)
    at validate.min.js?6fbe5f648d8f06284b4402d09e9c776a:formatted:170
    at Array.forEach (<anonymous>)
    at t.value (validate.min.js?6fbe5f648d8f06284b4402d09e9c776a:formatted:169)
    at Object.t.submitbutton (core.min.js?6fbe5f648d8f06284b4402d09e9c776a:1)
    at HTMLElement.executeTask (joomla-toolbar-button.min.js?6fbe5f648d8f06284b4402d09e9c776a:1)
```

**Comment by chmst** [comment]
Works for me on the 4.0 dev branch.

**Comment by brianteeman** [comment]
I just did a completely fresh checkout, composer install and npm install and the same problem

**Comment by chmst** [comment]
Which browser? I am on win10, fresh installations with php 7.4 and php 8, chrome and firefox, but no problems.  
npm version 7.5.6
composer version 2.0.8 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32661">issues.joomla.org/tracker/joomla-cms/32661</a>.</sub>

**Comment by joomdonation** [comment]
I am using today nightly build and also could not see this problem.

**Comment by brianteeman** [comment]
I think it is related to the versions of software installed by composer and npm - I am checking this now

**Comment by richard67** [comment]
@brianteeman Maybe there are some remainders of previous installs or tests which are not removed when pulling the branch from remote? In this case, an `git checkout .` and then a `git clean -d -x -f` before pulling again would clean that up. It will remove all what doesn't belong to the sources, i.e. also installed extensions, languages, old compilation results, so after that it needs again a composer install and npm ci and to make a new installation.

**Comment by brianteeman** [comment]
thats exactly what I am doing right now ;)

**Comment by brianteeman** [comment]
Whatever it was has gone now.
