### ISSUE TITLE
[4.0] com_mails filters not translated

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32675]
### Steps to reproduce the issue
Go to the new mail templates components found on the system page
Set the number of items to display at anything less than the total number of items eg 5
open the filter options
click on the select component filter to see the options

### Expected result
All the text is translated strings ie "USERS" not "com_users"

### Actual result
ONLY the text for items on the current page is translated
When you change page or apply a filter then once again only the text for the items on that page is translated

### Comment
It is as if the *.sys.ini files are not loaded but language debug says they are

### Demo
![mails](https://user-images.githubusercontent.com/1296369/111053230-e098d400-8459-11eb-8dac-6fcdf78cd09e.gif)

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/32687 should fix this issue.

**Comment by brianteeman** [comment]
Closed as we have a pr
