### ISSUE TITLE
[4.0] Template menu bar not properly aligned 

### ISSUE THREAD

**Issue by Megh05** [joomla/joomla-cms#32679]
### What needs to be fixed

![image](https://user-images.githubusercontent.com/53462448/111058504-099a8280-84b5-11eb-91ed-886e729cbd32.png)

This is some extra white space on the top right corner of the mail template page

### Why this should be fixed

Good UI

### How would you fix it

By applying proper CSS

**Comment by sanket9787** [comment]
Try this
 width=100% 
in css file
if error is still there please provide me the code I will cheque it

**Comment by brianteeman** [comment]
I cannot replicate this

![image](https://user-images.githubusercontent.com/1296369/111062034-60e12880-849e-11eb-9380-dc727ba7ede9.png)

**Comment by Quy** [comment]
Please test PR #32689
