### ISSUE TITLE
[4.0] Mail Templates - add tags

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32676]
### Steps to reproduce the issue
In the new mail templates component found on the system dashboard. Click to create a mail template

![image](https://user-images.githubusercontent.com/1296369/111053388-391ca100-845b-11eb-9a7d-6bd1f355da90.png)

On the template page click on the button to edit the body

![image](https://user-images.githubusercontent.com/1296369/111053401-59e4f680-845b-11eb-9344-0c42f7054c4f.png)

You can now see the message body and a list of available tags

![image](https://user-images.githubusercontent.com/1296369/111053420-797c1f00-845b-11eb-9428-1a3ce4088e11.png)

### Expected result
As each of the available tags is presented as a link I expect them to do something when you click on them. Such as inserting the tag into the message body at the cursor

### Actual result
Nothing happens. No errors in the console. Just nothing

### Additional comments
Once again a useless new component that was accepted before it was ready and the developer disappears without resolving outstanding issues.

**Comment by rdeutz** [comment]
Closing because we have a PR #32681
