### ISSUE TITLE
[4.0] Mail Templates - Language filter

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32677]
### Steps to reproduce the issue
In the new mail templates components that can be found on the system dashboard is a language filter

![image](https://user-images.githubusercontent.com/1296369/111053512-4be3a580-845c-11eb-8f45-51187e170abf.png)

This shows all the available languages PLUS the special ALL language

The ALL should not be there because in this completely non-standard UI you can never have any mail template that is for the ALL language. It is not possible at all so the option to filter by it is pointless

**Comment by Megh05** [comment]
> ### Steps to reproduce the issue
> In the new mail templates components that can be found on the system dashboard is a language filter
> 
> ![image](https://user-images.githubusercontent.com/1296369/111053512-4be3a580-845c-11eb-8f45-51187e170abf.png)
> 
> This shows all the available languages PLUS the special ALL language
> 
> The ALL should not be there because in this completely non-standard UI you can never have any mail template that is for the ALL language. It is not possible at all so the option to filter by it is pointless

So all we have to do is to remove the ALL Language filter from the dropdown... Right?

**Comment by Megh05** [comment]
@brianteeman Sir can you please help me out by providing the name of the PHP file used. Thank You!

**Comment by infograf768** [comment]
I guess you can delete this line
```
			<option value="*">JALL</option> // Kill this line

````

in

https://github.com/joomla/joomla-cms/blob/50443ffc31fd6781618020778bb96fcbfb4792f9/administrator/components/com_mails/forms/filter_templates.xml#L13-L21

**Comment by Megh05** [comment]
@infograf768 Thank You, Sir!

**Comment by rdeutz** [comment]
closing because we have a PR #32684
