### ISSUE TITLE
[4.0] Calendar field bug?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32694]
I don't know if this is a bug in joomla or in my brain

I have a form with a calendar field
I have javascript that does a calculation on the value of the field and inserts the value into a new field

The javascript is triggered by `fieldname.addEventListener("change",`

If I manually enter a date in the field then the javascript is triggered and everything is good
If I select a date with the datepicker then the javascript is never triggered (no console errors)

Is it me or is it a bug in the calendar field

**Comment by Fedik** [comment]
that a bug, 
if I right remember there was an issue about it (maybe for j3)

**Comment by Megh05** [comment]
@Fedik Yes rightly said; .addEventListner(), .triger() or change() are not currently working with jQuery. You can try by using .dispatchEvent() or .on() instead.

**Comment by brianteeman** [comment]
Glad to hear that its not my brain failure

**Comment by brianteeman** [comment]
@Megh05 no jquery is being used

**Comment by brianteeman** [comment]
@fedik any ideas how to fix it?

**Comment by Fedik** [comment]
Try like in this comment https://github.com/joomla/joomla-cms/issues/17515#issuecomment-628026800

but like this:
in calendar.js:
```
this.inputField.dispatchEvent(new CustomEvent('change', {bubbles: true, cancelable: true}));
```

then in your code you should be able to use:
```
yourField.addEventListener("change", ...
```

I not tested, in theory should work

**Comment by brianteeman** [comment]
Thanks I will take a look tonight

**Comment by Fedik** [comment]
btw, the Issue from 2017,
well, that need to fix someday :smile:

**Comment by richard67** [comment]
> btw, the Issue from 2017,
> well, that need to fix someday 😄

I suggest we do it in 2023 😉

**Comment by brianteeman** [comment]
@fedik it works!!!!

I am not going to submit a PR for this as I would probably put it in the wrong place etctetc and it will be quicker for you to add the oneliner than for us to go back and fro discussing changes that I dont understand

**Comment by Fedik** [comment]
please test #32755

**Comment by alikon** [comment]
closing as we have a pr #32755
