### ISSUE TITLE
Add Button margins when update

### ISSUE THREAD

**Issue by mariantanase** [joomla/joomla-cms#32700]
### Steps to reproduce the issue
When upgrading from Joomla 4 Beta 7 to the current nightly build, you are prompted to enter credentials before continuing.
The two buttons (**Cancel** and **Install**) are attached. No margin or padding between them.

### Actual result

![screen shot 2021-03-16 at 09 26 30](https://issues.joomla.org/uploads/1/5cda17c241681bfa9877125c3204a5ca.png)

### System information (as much as possible)
Joomla_4.0.0-beta8-dev
PHP 7.4.13

**Comment by anonymous0807** [comment]
Sir, let me get a chance to fix this issue.

**Comment by alikon** [comment]
maybe reading this one #32697  may help

**Comment by richard67** [comment]
Whoever wants to fix this issue mind the round corners of the button: When having space between the buttons, it will need all 4 corners of each button to be round.

**Comment by JajateeNandineeSahoo** [comment]
I want to fix the issue but don't know where is the code this issue. Could anyone help me and tell what is the path to get the code?

**Comment by shitesh2607** [comment]
I am working on this issue.

**Comment by infograf768** [comment]
Suggestion:
```
diff --git a/administrator/components/com_joomlaupdate/tmpl/upload/captive.php b/administrator/components/com_joomlaupdate/tmpl/upload/captive.php
index bc7b120..78bc0f9 100644
--- a/administrator/components/com_joomlaupdate/tmpl/upload/captive.php
+++ b/administrator/components/com_joomlaupdate/tmpl/upload/captive.php
@@ -85,12 +85,12 @@
 		<div class="control-group">
 			<div class="controls">
-				<div class="btn-group">
+				<button type="button" class="btn">
 					<a class="btn btn-danger" href="index.php?option=com_joomlaupdate">
 						<span class="icon-times icon-white" aria-hidden="true"></span> <?php echo Text::_('JCANCEL'); ?>
 					</a>
-					<button type="submit" class="btn btn-primary">
-						<span class="icon-play icon-white" aria-hidden="true"></span> <?php echo Text::_('COM_INSTALLER_INSTALL_BUTTON'); ?>
-					</button>
-				</div>
+				</button>
+				<button type="submit" class="btn btn-primary">
+					<span class="icon-play icon-white" aria-hidden="true"></span> <?php echo Text::_('COM_INSTALLER_INSTALL_BUTTON'); ?>
+				</button>
 			</div>
 		</div>
```
<img width="791" alt="Screen Shot 2021-03-17 at 09 29 03" src="https://user-images.githubusercontent.com/869724/111437426-5ecbd380-8703-11eb-8544-83564cd2dad2.png">

**Comment by JajateeNandineeSahoo** [comment]
> I am working on this issue.

Okay, no problem but I just want to know that can't I work on this issue? Is it that only a single person can work on a single issue?

**Comment by mariantanase** [comment]
> 
> 
> I want to fix the issue but don't know where is the code this issue. Could anyone help me and tell what is the path to get the code?

I'm sorry to tell you this, but how can you fix this issue when you don't know where to find the code to fix ?

**Comment by chmst** [comment]
@JajateeNandineeSahoo you can work on this issue - everyone can work on every issue. As soon as you make a pullrequest which solves the problem, the issue will be closed and we test your PR.

**Comment by JajateeNandineeSahoo** [comment]
> > I want to fix the issue but don't know where is the code this issue. Could anyone help me and tell what is the path to get the code?
> 
> I'm sorry to tell you this, but how can you fix this issue when you don't know where to find the code to fix ?

Actually I'm new to open source and I don't know much about it. I'm just started learning it and I thought that may be someone would have written the path to find the code.

**Comment by infograf768** [comment]
the path is easy. look above : https://github.com/joomla/joomla-cms/issues/32700#issuecomment-800896215

**Comment by drmenzelit** [comment]
Closing as we have a PR #32716

**Comment by infograf768** [comment]
My proposal above https://github.com/joomla/joomla-cms/issues/32700#issuecomment-800896215 is wrong.

**Comment by infograf768** [comment]
Maybe this will be OK

https://github.com/joomla/joomla-cms/pull/32716#issuecomment-801703473


Reopening

**Comment by drmenzelit** [comment]
I'm closing the issue since it is the expected behaviour of a btn-group to have the buttons together without space between them: https://getbootstrap.com/docs/5.0/components/button-group/

Feel free to re-open if you think the btn-group is wrong here.
