### ISSUE TITLE
Create a cookie management system to manage cookies as required by GDPR and other privacy regulations.

### ISSUE THREAD

**Issue by Ritwik880** [joomla/joomla-cms#32719]
### Is your feature request related to a problem? Please describe.
When the cookie is set on the client’s browser , it can persist for days , months or years , This makes it easy to save user preferences & visit information , The cookies are stored on the client’s hard disk , so , if the server crashes , the cookies are still available .

### Describe the solution you'd like
First, we create a function that stores the name of the visitor in a cookie variable:

function setCookie(cname, cvalue, exdays) {
  var d = new Date();
  d.setTime(d.getTime() + (exdays*24*60*60*1000));
  var expires = "expires="+ d.toUTCString();
  document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
}

**Comment by brianteeman** [comment]
The title of this request has nothing to do with the content of the request.

**Comment by joeforjoomla** [comment]
This is a troll, close it.
