### ISSUE TITLE
[4.0] Visibility issue on hover

### ISSUE THREAD

**Issue by srishty-07** [joomla/joomla-cms#32711]
### Steps to reproduce the issue
Open the Joomla backend , and in the navbar on the top hover on any icon , hover effect is almost invisible

![image](https://user-images.githubusercontent.com/70388131/111441449-58525180-872d-11eb-9ad4-9b86fb2765eb.png)

### Expected result

![image](https://user-images.githubusercontent.com/70388131/111456861-8049b100-873d-11eb-9b4b-b310a80cd76b.png)

### Actual result
1) before hover :
![image](https://user-images.githubusercontent.com/70388131/111441546-6e601200-872d-11eb-8801-1a44b54a66f5.png)
2) on hover :
![image](https://user-images.githubusercontent.com/70388131/111441573-73bd5c80-872d-11eb-8a4a-bf9df62dfdd7.png)

### System information (as much as possible)

Joomla 4.0.0 beta8-dev

### Additional comments
any of the three changes can be performed for visibility:
1) We can either change the background color on hover .
2) Can change the box-shadow.
3) Increase the size of icon .

### Are you working on this issue
YES

**Comment by drmenzelit** [comment]
@srishty-07 can you please edit the title of the issue and add [4.0] so it is clear which Joomla version this issue is about? Thanks

**Comment by hitesh-coder** [comment]
can i work on this issue?

**Comment by srishty-07** [comment]
> can i work on this issue?
> 
> 

I'm already working @hitesh-coder

**Comment by chmst** [comment]
@hitesh-coder Everyone can work on every issue. But as you see, @srishty-07 is already on it. 

I like the light background in your example, @srishty-07

**Comment by drmenzelit** [comment]
Closing this as we have a PR #32726
