### ISSUE TITLE
Article tag URL does not redirect to “Compact List of Tagged Items” Menu Item when other language except from All is selected in the menu item

### ISSUE THREAD

**Issue by gkleissiaris** [joomla/joomla-cms#32717]
### Steps to reproduce the issue
• Install a basic Joomla! 3.9.25
• Installed languages: Greek and English
• Enable multilingual function
• Create a Greek and an English Main Menu
• Create example tags for each language
• Create a category and sub-category for each language
• Create example articles for each subcategory and attach example tags to them
• Create menu items for each language and “Compact List of Tagged Items” Menu Items pointing to example categories with a specific tag
• Click on an article tag URL and see where it redirects when the menu item has a language other than All (wrong redirection) and when it has All (correct redirection)

### Articles created:
![image](https://image.prntscr.com/image/n5prd00DRnega8SsfUyD7Q.jpg)
Image: https://prnt.sc/10o97nl

### Categories created:
![image](https://image.prntscr.com/image/esfYtLYoSoSkW88D7BnZDw.jpg)
See image: https://prnt.sc/10o98xd

### Tags created:
![image](https://image.prntscr.com/image/3xsDvD5vT1uV3W1H4tferw.jpg)
Image: https://prnt.sc/10o99gs

### Menu items created:
![image](https://image.prntscr.com/image/agYSHVXLSPujMv38T8Yv8w.jpg)
Image: https://prnt.sc/10o9a1m

### Expected result
When visiting /en/news-en/projects-en page, article tag URL should redirect to related “Compact List of Tagged Items” menu item, that is /en/news-en/projects-en/projects-with-label-02-en page
![image](https://image.prntscr.com/image/mUwIU05-TOibYiKBr3By_w.jpg)
Image: https://prnt.sc/10o937p

### Actual result
Label 01 tag that has English language selected in its menu item redirect to URL /en/component/tags/tag/label-01 instead of the correct URL, as the Label 02 tag that has All language selected in its menu item and redirects to correct URL /en/news-en/projects-en/projects-with-label-01-en.
![image](https://image.prntscr.com/image/Q_AVcMrFQiWJaaOCSiijaA.jpg)
Image: https://prnt.sc/10o9aup

### System information
Joomla! 3.9.25
PHP Version: 7.3.27
Web Server: Apache
Database Version: 5.5.5-10.2.37-MariaDB
Search Engine Friendly URLs: Yes
Use URL Rewriting: Yes
No other extensions installed

### Additional comments
I don't know if this is a bug or if i haven't setup something correctly. Please advise.

**Comment by gkleissiaris** [comment]
As I said before in my previous message, if you want to just overcome the problem and have the tags’ link pointing to the correct URL (a “Compact List of Tagged Items” menu item) that is **/en/news-en/projects-en/projects-with-label-02-en** page and not **/en/component/tags/tag/label-01 page**, you should just change the language of the “Compact List of Tagged Items” menu item from English to All. That should do the trick, even if it is considered a bug.

But if you want to redirect a tag URL to a “Single Article” menu Item, the following should do the trick, even if it may be considered a bug and not the correct way to do it, but I haven’t found any other way. If anyone else has another better way, please advise.

### Redirect tag URL to a “Single Article” Menu Item
**1. Create a new “Single Article” menu item with English language:**

![image](https://image.prntscr.com/image/7uqfoTU-Shqivfj5HXPsRw.jpg)
Image: https://prnt.sc/10u4z8n

**2. Create a new “Compact List of Tagged Items” menu item with All language  and same alias and the previous**

![image](https://image.prntscr.com/image/ockXEYPuTP_1EM6ENrjLaw.jpg)
Image: https://prnt.sc/10u5228

**3. In page "Projects", the tag URL now points to "Single Article" menu item "Projects with Label 01":**

![image](https://image.prntscr.com/image/IEDZnhNUSpGvj_vF4oWRKg.jpg)
Image: https://prnt.sc/10u53vy

![image](https://image.prntscr.com/image/cZ15ZuhURdGM_c2ksCIrIw.jpg)
Image: https://prnt.sc/10u54nm

**Comment by infograf768** [comment]
What is the language filter parameter used in Tags Options?

<img width="723" alt="Screen Shot 2021-03-24 at 11 21 23" src="https://user-images.githubusercontent.com/869724/112294529-3871df00-8c93-11eb-8945-3b6f7da3dc6c.png">

**Comment by gkleissiaris** [comment]
> 
> What is the language filter parameter used in Tags Options?
> 

The default, "All". I didn't change it. Should I use "Current"? I didn't know there was such an option.

**Comment by ghost** [comment]
> Should I use "Current"? I didn't know there was such an option.

@gkleissiaris have you tried, whats the result?

**Comment by ghost** [comment]
Can someone give the issue a label "Information required"?

**Comment by ghost** [comment]
Simlar issue but for J4: #31754

**Comment by gklis** [comment]
> 
> 
> > Should I use "Current"? I didn't know there was such an option.
> 
> @gkleissiaris have you tried, whats the result?

Yes I did, with the same results.

**Comment by gklis** [comment]
> 
> 
> Can someone give the issue a label "Information required"?

I suppose an administrator should do that, right?

**Comment by ghost** [comment]
@gklis 

> Yes I did, with the same results.

Thanks for the information, no label now needed. 

I will setup a site and try to get your issue.

Edit: Now i have seen your 

> I don't know if this is a bug or if i haven't setup something correctly. Please advise." 

Do i understand correct you haven't asked in the [forum](https://forum.joomla.org/)?

**Comment by gklis** [comment]
> Do i understand correct you haven't asked in the [forum](https://forum.joomla.org/)?

No I haven't.

**Comment by ghost** [comment]
> I will setup a site and try to get your issue.

Please ask first on the forum, thank you :-)

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc [@zero-24](https://github.com/zero-24)
