### ISSUE TITLE
[4] Code cosmetic. com_content article default.php

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#32725]
### Steps to reproduce the issue
- See https://github.com/joomla/joomla-cms/blob/4.0.0-beta7/components/com_content/tmpl/article/default.php#L43
- - ` && $this->item->pagination` can be removed. "If it's not empty then it is and we don't have to check again if it is."
- See https://github.com/joomla/joomla-cms/blob/4.0.0-beta7/components/com_content/tmpl/article/default.php#L49-L51
- - Remove comment or does anybody understand what we can group here and how?
- - Opening `(` and closing `)` brackets  around the whole `OR` block can be removed.

**Comment by rdeutz** [comment]
> If it's not empty then it is and we don't have to check again if it is.

agreed

> Remove comment or does anybody understand what we can group here and how?

I think it's there from an older version, can be removed

> Opening ( and closing ) brackets around the whole OR block can be removed.

agreed

Can you make a PR?

**Comment by ReLater** [comment]
I'll do when I find time. Maybe some days... Against which branch?

**Comment by rdeutz** [comment]
> Against which branch?

4.0-dev

**Comment by saumyasarkar11** [comment]
> > Against which branch?
> 
> 4.0-dev

I have made the requested PR

**Comment by drmenzelit** [comment]
Closing as we have a PR #32746
