### ISSUE TITLE
Simplify PHP version reported

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32721]
### Steps to reproduce the issue

Based on actual feedback today from "a normal user" of Joomla. 

install old PHP version and visit admin to see the PHP end of life warning, with a NORMAL EVERY DAY USER of Joomla eyes (not as a PHP developer or expert) 

### Expected result

 - We have detected that your server is using **PHP 7.2.34** which is obsolete 

### Actual result

<img width="852" alt="Screenshot 2021-03-17 at 18 16 20" src="https://user-images.githubusercontent.com/400092/111517365-e5f16980-874c-11eb-9183-0806255c7535.png">

 - We have detected that your server is using **PHP 7.2.34-8+ubuntu18.04.1+deb.sury.org+1** which is obsolete 

The `+ubuntu18.04.1+deb.sury.org+1` just confuses and makes no sense 

### System information (as much as possible)

PHP 7.2.34-8+ubuntu18.04.1+deb.sury.org+1 obviously :)

**Comment by brianteeman** [comment]
To be clear are you saying that just the version number should be simplified or that the entire message should be simplified to your expected result.

I agree with the php version being simplified 

I do not agree that the message itself should be truncated

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/32722
