### ISSUE TITLE
Hovering effect on user menu

### ISSUE THREAD

**Issue by gaurav24072002** [joomla/joomla-cms#32737]
we should add a hovering effect on ``user menu`` button to make it more accessible for user to open it rather then clicking it to open.

![gsoc user menu](https://user-images.githubusercontent.com/77109758/111680774-9001ec00-8848-11eb-98fc-9076b897402e.JPG)
 
![gsoc user menu2](https://user-images.githubusercontent.com/77109758/111681036-dce5c280-8848-11eb-9516-e13662db70be.JPG)

**Comment by richard67** [comment]
@gaurav24072002 You mean hover effect on the button which opens the menu? Or on the single menu items? For the buttons there is already a pull request to change it: #32726 .

**Comment by gaurav24072002** [comment]
@richard67  I mean whenever we hover our mouse cursor on user menu icon it itself will open the drop down menu for user rather then clicking on it.

**Comment by richard67** [comment]
@gaurav24072002 Then you should write that. You wrote you want a hover effect, and that's something else. And why do you think it is more accessible?

Bootstrap came away from their drop down menus opening on hover. @brianteeman Do you know what was the reason? I don't remember if right now.

**Comment by richard67** [comment]
> @gaurav24072002 Then you should write that. You wrote you want a hover effect, and that's something else.

Ah, I just see I was reading a bit too fast, you wrote it at the end of the sentence.

But still I think it's not a good idea.

**Comment by gaurav24072002** [comment]
But I have seen many websites with this feature and it looks very handy for a user too...

**Comment by richard67** [comment]
From [https://getbootstrap.com/docs/4.0/components/dropdowns/](https://getbootstrap.com/docs/4.0/components/dropdowns/), just the first paragraph in section "Overview" at the top :

> They’re toggled by clicking, not by hovering; this is an intentional design decision.

Following the link behind the "intentional design decision" there leads to:

https://markdotto.com/2012/02/27/bootstrap-explained-dropdowns/

This explains it, and I agree with it: It is bad UX if something needs to be clicked and something else react already when hovering, and they appear the same so you can't see what happens when.

**Comment by richard67** [comment]
By the way, just in case you don't know yet: Joomla doesn't only allow the default templates which come with the release. Joomla allows to use template from 3rd party on frontend and backend.

So there is no need for making the default templates shipped with the release to match everybody's taste (which is impossible anyway).

If someone is not happy and wants dropdown which opens on hovering or whatever, he or she might find another template which fulfills these needs.

And in Joomla you can make overrides.

So it does not need to make such changes in the core.

Just my opinion.

**Comment by chmst** [comment]
Such hovering effects are not used in JoomlaThey are nice and fancy but they are not a11y. How sees or hears a blind user what happens?
Hover effects are also  bad for users with motoric disabilities who use keyboard or cannot move the mouse as we do.
