### ISSUE TITLE
[4.0] Media Manager cant insert in content unless logged in as admin

### ISSUE THREAD

**Issue by david19161** [joomla/joomla-cms#32734]
### Steps to reproduce the issue
1. Ensure you are not logged into site administrator
2. Login to front-end of site as super user
3. Edit any article and click Image in the CMS Content dropdown to bring up Media Manager
4. Select and attempt to insert any image

### Expected result
Image is inserted into content

### Actual result
Nothing happens.
Using browser console in Firefox shows [HTTP/1.1 403 Forbidden]

### System information (as much as possible)
Joomla_4.0.0-beta8-dev-Development-Full_Package - 2021-03-18

### Additional comments
Works if you are logged into administrator backend
Same happens on latest versions of Chrome, Edge

**Comment by PhilETaylor** [comment]
hmmm... this echos some of the media bugs I reported, and others fixed, before...

**Comment by PhilETaylor** [comment]
hmmm... this echos some of the media bugs I reported, and others fixed, before... 

https://github.com/joomla/joomla-cms/issues/32259 
https://github.com/joomla/joomla-cms/issues/30005

related?

**Comment by david19161** [comment]
Yes Phil, I saw your previous reports and wondered why the issue had been closed

This particular issue is maybe caused by the administrator path being hard-coded into the iamge select endpoint as follows:

file : media/system/js/fields/joomla-image-select.js
line : 195

const apiBaseUrl = `${Joomla.getOptions('system.paths').rootFull}administrator/index.php?option=com_media&format=json`;
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32734">issues.joomla.org/tracker/joomla-cms/32734</a>.</sub>

**Comment by PhilETaylor** [comment]
that was changed in some places like `build/media_source/system/js/fields/joomla-field-media.w-c.es6.js` in https://github.com/joomla/joomla-cms/pull/30617/files

Maybe one instance was missed.

Paging @SharkyKZ who worked on that.

**Comment by Jenniline** [comment]
Hi @PhilETaylor and @david19161. My name is Jenniline Ebai I am applying for GSOCI 2021 under the Media Manager project. I notice that this issue directly relates to the project. I will like to work on this issue and use it to get acquainted with the Media Manager Project. I have read the discussion and I have tried to understand what this issue means please can you give me some description and direction to work on this issue? Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32734">issues.joomla.org/tracker/joomla-cms/32734</a>.</sub>

**Comment by PhilETaylor** [comment]
This should be a release blocker like the others were. (@infograf768 @wilsonge)

**Comment by PhilETaylor** [comment]
@Jenniline welcome. This might not be a good starting issue as it has history, everything you need to know is linked in this issue, and the two previous issues that have already been resolved. It might be that @SharkyKZ missed one instance of the hard coded path. I steer clear of JS in Joomla so I'll be of no help here :)

**Comment by Jenniline** [comment]
okay Thanks

**Comment by infograf768** [comment]
@david19161 
You are correct. Taking off `administrator/` in that line solves the issue. 

Edit: also wrong path

```
diff --git a/build/media_source/system/js/fields/joomla-image-select.w-c.es6.js b/build/media_source/system/js/fields/joomla-image-select.w-c.es6.js
index b15f09b..fbc3807 100644
--- a/build/media_source/system/js/fields/joomla-image-select.w-c.es6.js
+++ b/build/media_source/system/js/fields/joomla-image-select.w-c.es6.js
@@ -191,5 +191,5 @@
     }
 
-    const apiBaseUrl = `${Joomla.getOptions('system.paths').rootFull}administrator/index.php?option=com_media&format=json`;
+    const apiBaseUrl = `${Joomla.getOptions('system.paths').baseFull}index.php?option=com_media&format=json`;
 
     Joomla.request({

```
PR welcome.

**Comment by rdeutz** [comment]
Closing because we have a PR #32825
