### ISSUE TITLE
[4.0] Modal Batch in users is not complete

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#32735]
### Steps to reproduce the issue
In users - manage select one or more users and click the action "batch".

### Expected result
A modal like in J3, where actions on the selected group can be performed. 
<img width="504" alt="j3-users-batch" src="https://user-images.githubusercontent.com/1035262/111656698-0da70700-880b-11eb-9ec8-f535d7ce4dd4.PNG">

### Actual result
Missing actions for groups
<img width="419" alt="j4-users-batch" src="https://user-images.githubusercontent.com/1035262/111656758-1d265000-880b-11eb-9eda-938a92e8a89d.PNG">

### Additional comments
https://github.com/joomla/joomla-cms/issues/32732

**Comment by joomdonation** [comment]
@sksuryan Do you want to take this one? Look like these lines of code are missing https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_users/views/users/tmpl/default_batch_body.php#L41-L43

Just add the above lines of code below this line https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_users/tmpl/users/default_batch_body.php#L45 should address the issue.

**Comment by sksuryan** [comment]
> 
> 
> @sksuryan Do you want to take this one? Look like these lines of code are missing https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_users/views/users/tmpl/default_batch_body.php#L41-L43
> 
> Just add the above lines of code below this line https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_users/tmpl/users/default_batch_body.php#L45 should address the issue.

sure will do!

**Comment by alikon** [comment]
please test #32749
