### ISSUE TITLE
batch process in "users" doesn't assert, that a user is at least member of one group

### ISSUE THREAD

**Issue by gorgonz** [joomla/joomla-cms#32732]
### Steps to reproduce the issue
- create a new user
- verify, that the user is member of public
- now select this user and push button "batch"
- In the dialog select "public" as group, activate option "delete from group" and password option "no action"
- execute

### Expected result
an error message like "the user must be member of at least one group"

### Actual result
the batch is done and the user is member of no group

### System information (as much as possible)
seen with J3.9.25

### Additional comments
creating a new user will not allow this, so the message text from there is usable ;-)

**Comment by ghost** [comment]
Confirm issue.

> ![image](https://user-images.githubusercontent.com/78906980/115249113-98d82d00-a128-11eb-999f-70f463fc4812.png)

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

A pull request for testing in Joomla 4 has been created. Please test #38596

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38596 . Thanks in advance.
