### ISSUE TITLE
[3] Export Selected as CSV Button Wrap

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32741]
### Steps to reproduce the issue

Probably a `won't fix` this late in the development cycle of Joomla 3.x but reporting anyway.

Install Joomla 3.9.25
Enable Action Logs and browse around to generate some actions
Visit Users -> Action Log
Look at the toolbar

### Expected result

No wrapping of the "Export Selected as CSV" button

### Actual result

<img width="698" alt="Screenshot 2021-03-18 at 21 30 15" src="https://user-images.githubusercontent.com/400092/111700329-275b4500-8831-11eb-8815-fe9c338a544b.png">

Its not screen size dependant

Looks like its the font size here: 
https://github.com/joomla/joomla-cms/blob/8f9fac668cb27489c85daa9301d0cb383f96a5ba/administrator/templates/isis/css/template.css#L2277

If I make that 13px it no longer wraps... strange. 

### System information (as much as possible)

Safari on mac

**Comment by Akashrajpoots14** [comment]
Hey ! I am interested to solve this issue but when I go to the required instruction everything looks fine to me . @C-Lodder  Please see the [screenshot:
<img width="775" alt="joomla3 25 bug" src="https://user-images.githubusercontent.com/73773797/111797895-e0834480-885c-11eb-85d2-ede481f4e338.png">

**Comment by PhilETaylor** [comment]
Try safari on Mac

**Comment by PhilETaylor** [comment]
@infograf768 you have a mac right?

**Comment by ghost** [comment]
Confirm issue.

> ![image](https://user-images.githubusercontent.com/78906980/115248315-ddaf9400-a127-11eb-9b0b-82a0dbeca767.png)

**Comment by PhilETaylor** [comment]
Joomla 3 - no one cares anymore.

**Comment by Akashrajpoots14** [comment]
i dont have mac
