### ISSUE TITLE
Subform field type buttons are too close to each other

### ISSUE THREAD

**Issue by philip-sorokin** [joomla/joomla-cms#32751]
### What needs to be fixed

Add a space between the buttons.

### Why this should be fixed

On mobile devices, it's almost impossible to press on such buttons.

### How would you fix it

Add a margin.

### Side Effects expected

No.

![2021-03-19_23-54-07](https://user-images.githubusercontent.com/11632367/111843628-9492d700-8912-11eb-90e6-636931980150.png)

**Comment by hitesh-coder** [comment]
@philip-sorokin could you please provide steps to reproduce this issue

**Comment by philip-sorokin** [comment]
@hitesh-coder just create a subform field with several inputs.

**Comment by brianteeman** [comment]
I believe this was resolved with #32873

**Comment by Quy** [comment]
Buttons are larger now with #32873. Thanks for the report.
