### ISSUE TITLE
A progress bar after installing demo data is not collapsing

### ISSUE THREAD

**Issue by philip-sorokin** [joomla/joomla-cms#32750]
### What needs to be fixed

The progress bar must be hidden once the data is installed.

### Why this should be fixed

Visible active progress bar is confusing users, they think the installation is not over and waiting.

### How would you fix it

Just hide this progress bar right after installation.

![2021-03-19_23-53-20](https://user-images.githubusercontent.com/11632367/111843017-77113d80-8911-11eb-92d4-ac1d192da1c0.png)

### Side Effects expected

Absolutelly none.

**Comment by ghost** [comment]
This is a duplicate Report of closed Issues #24459, #25963.

**Comment by 200MPHMEDIA** [comment]
Agree.  Experience the same issues when installing Sample Data.  No finality of installation of sample data obvious on screen.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32750">issues.joomla.org/tracker/joomla-cms/32750</a>.</sub>

**Comment by brianteeman** [comment]
Are the words "Blog sample data has been installed" not obvious enough?

**Comment by philip-sorokin** [comment]
@brianteeman you can stop the animation to make the progress bar inactive when the installation is done. The animation makes we think the installation is not over. It's reporting: "Something installed 100%", but we see the active bar and think it's going to install something else.

**Comment by brianteeman** [comment]
Not everyone sees the animation

**Comment by philip-sorokin** [comment]
I have associacions with a buggy soft in Windows, it holds on 100% and not finishing.

**Comment by ghost** [comment]
Isn't it enough to get a different background for the last Message `Blog Sample data has been installed.`?

**Comment by Quy** [comment]
Please test PR #33100.
