### ISSUE TITLE
Radio buttons with J3 attributes "showon" and classes "btn-yes-no" are not working.

### ISSUE THREAD

**Issue by philip-sorokin** [joomla/joomla-cms#32752]
### Steps to reproduce the issue

1. Create a radio form field, add the classes "btn-group btn-yes-no".
2. Create several another fields, for example, text or number. Set them all attributes: showon="mainField:2".

### Expected result

Hidden fields are hidden on initialization. They appear when pressing right radio button.

### Actual result

They are not hidden and not appearing, radio buttons are not switching and changing classes to become green or red.

### System information (as much as possible)

Google Chrome desktop browser.

### Additional comments

None.

**Comment by Quy** [comment]
Please test using the nightly builds: https://developer.joomla.org/nightly-builds.html

**Comment by anurag806** [comment]
we need to recreate the radio button

**Comment by Quy** [comment]
Fixed in #32367. Please test using the nightly builds. https://developer.joomla.org/nightly-builds.html

**Comment by philip-sorokin** [comment]
It's more beautiful in Joomla! 3. Why didn't you implement slideUp/slideDown animation? What this outline on the picture for?
![image](https://user-images.githubusercontent.com/11632367/112755808-03df8980-8feb-11eb-9d56-9a25f4bf55b0.png)
