### ISSUE TITLE
Edit button appears twice in front-end

### ISSUE THREAD

**Issue by hitesh-coder** [joomla/joomla-cms#32772]
## Steps to reproduce this issue
Open joomla frontend page and at the top-right corner you will see two edit button appearing

### What needs to be fixed
<img width="1440" alt="Screenshot 2021-03-21 at 3 37 50 PM" src="https://user-images.githubusercontent.com/58116679/111901095-e4c98080-8a5b-11eb-8a7b-dfc593e0d717.png">

### Why this should be fixed
I Think it is a mistake that edit button is appearing twice

### System information (as much as possible)
Google Chrome desktop browser.

### Side Effects expected
None

**Comment by brianteeman** [comment]
This is a known bug and its a layout problem not a duplicate button which you will see if you click on both buttons. One is for the module settings of the main menu module. The other is for the modules settings of the breadcrumbs module

**Comment by ghost** [comment]
@hitesh-coder see https://github.com/joomla/joomla-cms/pull/32757#issuecomment-803300900

**Comment by rdeutz** [comment]
not a bug or dublicate
