### ISSUE TITLE
[4] Dragging item causes icons to misplace

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32788]
### Steps to reproduce the issue

Try to drag a menu item or content item in Joomla 4 admin 

### Expected result

circle based icons retain their inner icons

### Actual result

circle based icons inner icons are offset to the bottom and right of the circle - easier to see in this video:

![Screen Recording 2021-03-21 at 08 20 33 pm](https://user-images.githubusercontent.com/400092/111919678-21f53900-8a83-11eb-84f5-2298a96bb982.gif)

### System information (as much as possible)

Safari on Mac tested.

**Comment by brianteeman** [comment]
Confirmed on chrome windows

**Comment by chmst** [comment]
Confirmed on firefox

**Comment by rs4231199** [comment]
I am working on this.

**Comment by PhilETaylor** [comment]
#32889
