### ISSUE TITLE
[4.0-dev] [PHP 8.0.0] Creation of Articles hangs

### ISSUE THREAD

**Issue by jwaisner** [joomla/joomla-cms#32787]
### Steps to reproduce the issue

1. Have a setup using PHP 8.0.0
2. On a clean install, attempt to create an article
3. Notice the browser seems to be doing something but nothing happens
4. Check MySQL database and see the article has been added to the database
5. Go back to backend and check articles. Notice no articles listed.

I was able to change to PHP 7.4.13 and the issue went away so seems to be something within PHP 8.0.0

### Expected result

Article should be created successfully not only in the database but also displayed in the backend article manager.

### Actual result

Article created in database but no article is shown in the backend article manager.

### System information (as much as possible)

OS: Windows 10
PHP: 8.0.0
Database: MySQL 8.0.16
Apache: 2.4.41
Joomla!: 4.0-dev

**Comment by PhilETaylor** [comment]
Im sorry I cannot replicate this with PHP 8.0.3 and `4.0-dev` - Do you have any Javascript Console Error messages or PHP error logs ?

<img width="530" alt="Screenshot 2021-03-21 at 20 09 57" src="https://user-images.githubusercontent.com/400092/111919351-7697b480-8a81-11eb-8bd0-e1d66e347ea5.png">

**Comment by jwaisner** [comment]
Yes, the close button does return me to the list of articles. I am not seeing any errors in JS console. PHP log has no errors to report either.

**Comment by joomdonation** [comment]
I'm using PHP 8.0.1 and could not replicate this, too. It is working well for me.

**Comment by jwaisner** [comment]
Hmm... Looks like this issue only occurs with 8.0.0 then. Does anyone have that version to test against to confirm it isnt something (other than version) that is breaking the setup?

**Comment by PhilETaylor** [comment]
I have now built PHP 8.0.0 from source in a docker container, and although I have several installation issues relating to mysql adapter and pdo adapters to now raise, I still cannot replicate any issue with saving of articles in PHP 8.0.0 exact version

<img width="541" alt="Screenshot 2021-03-22 at 18 13 08" src="https://user-images.githubusercontent.com/400092/112038195-76a7bb00-8b3a-11eb-9a20-4b7131c96725.png">

<img width="1213" alt="Screenshot 2021-03-22 at 18 13 37" src="https://user-images.githubusercontent.com/400092/112038217-7a3b4200-8b3a-11eb-8c11-28f3d652298e.png">

**Comment by jwaisner** [comment]
Okay, looks like something in my IDE then with PHP 8.0.0. Closing this as it is not a bug.
