### ISSUE TITLE
[4][Mobile] Action toggle icon covers search go button

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32794]
### Steps to reproduce the issue

On iPhone 11 Pro iOS 14.3 (and I assume all small screens, indeed Safari on Mac squashed does it) 

The Cog Icon for the collapsed action buttons menu overlaps the search button meaning people with fat fingers (cough) cannot press the search button

### Expected result

Useable 

### Actual result

<img width="476" alt="Screenshot 2021-03-21 at 21 52 01" src="https://user-images.githubusercontent.com/400092/111922112-047a9c00-8a90-11eb-9e31-33723d6c6745.png">

### System information (as much as possible)

 iPhone 11 Pro iOS 14.3 (Simulated)

**Comment by hitesh-coder** [comment]
hey @PhilETaylor instead of adding padding i think we should make cog icon smaller and place it at top-right corner. As this problem appears at more places i think this would be best way. If this sounds good please let me know i would love to try this or any other suggestion you would prefer

**Comment by manakwadhwa2002** [comment]
@PhilETaylor this pull request resolves this issue #32819.

**Comment by drmenzelit** [comment]
Closing as we have 2 PRs #32819 #32818

**Comment by drmenzelit** [comment]
We go with #32810 , please test it if possible. Thanks.
