### ISSUE TITLE
[4][Mobile] New Edit Mail Template screens not mobile friendly

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32797]
### Steps to reproduce the issue

 iPhone 11 Pro iOS 14.3 (Simulated)

System -> Mail Templates -> select one, and create a new template for it

### Expected result

The ability to create/edit Mail Templates while on small mobile devices

### Actual result

The EDIT toggles are below the fields and the screen is extremely wide on a small phone, no padding 

<img width="480" alt="Screenshot 2021-03-21 at 22 13 11" src="https://user-images.githubusercontent.com/400092/111922595-a3a09300-8a92-11eb-9ad2-acdcc849c96b.png">

The experience is a lot better on an iPad

![Image 2021-03-21 at 10 14 01 pm](https://user-images.githubusercontent.com/400092/111922630-c468e880-8a92-11eb-8790-9e8ffe114c5c.jpg)

**Comment by codeswithroh** [comment]
Could you help me find the code-base for this problem ?

**Comment by PhilETaylor** [comment]
PR #32810
