### ISSUE TITLE
[4][Mobile] Form validation error message not in view

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32795]
### Steps to reproduce the issue

When on mobile, and completing a form, and attempting to submit it, there is no on screen feedback that the form failed validation unless one closes the button action drawer and scrolls all the way up the page, or seeks out the validation error field.

### Expected result

The button action drawer closes on button press
Scroll into view the first field that is in error or scroll to top to show generic error message that the submission has failed.

### Actual result
Bad example video, assume the validation message was initially scrolled off screen :-) 
![Screen Recording 2021-03-21 at 09 56 58 pm](https://user-images.githubusercontent.com/400092/111922252-b7e39080-8a90-11eb-8d72-30c339828e16.gif)

### System information (as much as possible)

 iPhone 11 Pro iOS 14.3 (Simulated)

**Comment by brianteeman** [comment]
Not just on mobile. The same problem exists on desktop views
