### ISSUE TITLE
Change copyright text of branches and align it with staging branch

### ISSUE THREAD

**Issue by manakwadhwa2002** [joomla/joomla-cms#32801]
### What needs to be fixed
Add text to the Readme.md file of other branches and align it with staging branch in order to maintain symmetry amoung all branches. 

### Why this should be fixed
It look good in reading the documentation of any version of any branch.

### How would you fix it
Add the text to readme.md file

### Side Effects expected
No side effects expected

**Comment by brianteeman** [comment]
1. Changes made in branches are merged up so you dont need to create the same pull request for each branch
2. as of Joomla 4 we are only using the start date
3. You would also need to update the readme.txt

**Comment by richard67** [comment]
Closing as there is a pull request for this issue (which might be closed, too, because it's wrong).
