### ISSUE TITLE
radio button broken in J4Beta7

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#32804]
### Steps to reproduce the issue
use a standard radio button with the css class "btn-group" as it was in Joomla 3 and Joomla 4 earlier beta

### Expected result
to work

### Actual result
it dislays nice but on click the active button is not rendered correctly. The default value is still active

### System information (as much as possible)
Joomla 4 Beta 7

### Additional comments
it seems related to the Javascript that does not manage the "active" state, it uses a "has-success" state instead

**Comment by Quy** [comment]
Fixed in #32367. Please test using the nightly builds. https://developer.joomla.org/nightly-builds.html
