### ISSUE TITLE
Readme.md file in the staging branch need copyright modification from 2020 to 2021

### ISSUE THREAD

**Issue by manakwadhwa2002** [joomla/joomla-cms#32800]
### What needs to be fixed
Readme.md file in the staging branch need copyright text change from 2020 to 2021

### Why this should be fixed
As this is year 2021 not 2020 so it needs to be updated

### How would you fix it
Simply change the text in readme.md file in staging branch

### Side Effects expected
No side effect expected

**Comment by rdeutz** [comment]
done https://github.com/joomla/joomla-cms/commit/1b07d3ccd6a968e924a6f8064a4cd8c88503311c

closing
