### ISSUE TITLE
Users page is too wide

### ISSUE THREAD

**Issue by mariantanase** [joomla/joomla-cms#32820]
### Steps to reproduce the issue
1. Fresh Joomla 4.0.0 beta 8 dev
2. In admin backend, go to "Users". The details page user list is too wide and need to make horizontal scroll.

### Actual result
![screen shot 2021-03-23 at 09 29 39](https://issues.joomla.org/uploads/1/58584d9253ac28a44a31b4dddd191214.png)

### System information (as much as possible)
PHP 7.4.13
Screen resolution: 1280 x 1024

**Comment by PhilETaylor** [comment]
Gets even worse if you enable the 2FA features as another column is added. 

Discussions:
https://github.com/joomla/joomla-cms/discussions/31915
https://github.com/joomla/joomla-cms/discussions/32549

**Comment by sksuryan** [comment]
Interesting, because I worked on a similar issue with the mail template, but I'm not able to reproduce this one.

**Comment by Yash-g17** [comment]
@mariantanase  I'd love to solve this  can you please assign this to me ?

**Comment by PhilETaylor** [comment]
The Joomla Project doesn't assign issues to contributors in that way. Just work on it and submit a PR :-) 

https://github.com/joomla/joomla-cms/blob/staging/.github/CONTRIBUTING.md

**Comment by Yash-g17** [comment]
@PhilETaylor How do I figure out which file this issue is pointing towards ?

**Comment by PhilETaylor** [comment]
There appears to be a certain breakpoint where the horizontal scroll takes place. 

https://user-images.githubusercontent.com/400092/112767389-68f8a680-900e-11eb-9907-9c0b0d10d5a1.mp4

**Comment by meinhoonharsh** [comment]
> @PhilETaylor How do I figure out which file this issue is pointing towards ?

@PhilETaylor I am also wants to know, How can we find  which we have to edit to make changes in something we want, I got css, scss and js files through the get parameters in the URL, but unable to find the HTML for anything

**Comment by PhilETaylor** [comment]
Sorry, Its not for me to teach you the Joomla architecture or how to use the search :) 

Start your quest in the 4.0-dev branch here: https://github.com/joomla/joomla-cms/tree/4.0-dev/administrator/components/com_users/tmpl/users

**Comment by meinhoonharsh** [comment]
@PhilETaylor Thank you, It helped alot 😁

**Comment by ghost** [comment]
@Yash-g17  
> How do I figure out which file this issue is pointing towards ?

please read https://github.com/joomla/joomla-cms/issues/31540#issuecomment-811070565

**Comment by ghost** [comment]
@mariantanase can you please update the title with "[4.0]"? Then it shows in the issue-list what joomla-version your title belongs. Thanks.

**Comment by noxidsoft** [comment]
![2021-04-10 11_51_25-Window](https://user-images.githubusercontent.com/729135/114254596-ae947680-99f3-11eb-8007-6863bfac228c.jpg)
Be aware the issue is not just the table (userList) but it is the whole container-main that seems to be affected. I'm looking at it now, not sure if I'll fix it.

* with further testing it does seem that the table is the culprit. If I change class="table" to class="table-responsive" everything snaps back into place.

**Comment by sandramay0905** [comment]
@mariantanase can you please add "4.0 " to the title so its easier to know in issues-view what version is meant?

**Comment by PhilETaylor** [comment]
Just to confirm the new template look/style has not resolved this when 2fa plugins are enabled - its still an issue

<img width="1609" alt="Screenshot 2021-05-06 at 21 57 05" src="https://user-images.githubusercontent.com/400092/117364649-12587500-aeb6-11eb-812f-a447d6b46bff.png">

**Comment by mariantanase** [comment]
I can confirm that with the latest nightly build, the issue is still there.

![Screenshot_2021-05-25 Users - Joomla 4 Demo - Administration](https://user-images.githubusercontent.com/3976174/119521538-87afbb00-bd7b-11eb-8ca5-812cc4f78232.png)

**Comment by Quy** [comment]
PR #35286 and #35295 should have solved this issue.

**Comment by Quy** [comment]
Please test PR #36591.

**Comment by PhilETaylor** [comment]
Its still too wide... but now you can disable columns - that's not a fix.

**Comment by Quy** [comment]
Related #32912

**Comment by brianteeman** [comment]
This really should be closed as "wont fix"
The only way to fix it would be to remove columns and as the decision on which column to remove is subjective we have provided the functionality now for an admin to decide for themselves
