### ISSUE TITLE
[4.0] Form data lost when create category fail

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#32829]
### Steps to reproduce the issue
1. Access to administrator area of your site, try to create a new category
2. In the **Alias** field, enter one of the existing Alias (so that category could not be created)

### Expected result
Error displayed, but previous entered data is kept so that we just have to correct the wrong data and save the category again

### Actual result
Error displayed, all the entered data is erased and we have to enter all data again.

### System information (as much as possible)
Joomla 4 nightly build.

**Comment by brianteeman** [comment]
I think we have had a similar report before regarding the menus

**Comment by Krshivam25** [comment]
Hi @joomdonation I would like to contribute please let me know how to start

**Comment by rdeutz** [comment]
@Krshivam25 this is not how it works. Usualy an issue report is something "Hey I found this". If the reporter knows how to fix it, he/she could have made a PR with a fix. So to start to look into this:

* try to reproduce the issue
* find the code who is resposible
* try to fix it
* make a PR

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/32959
