### ISSUE TITLE
Search title results have N chars cutted at the end of string for each quote ou double quote 

### ISSUE THREAD

**Issue by z3-zalox** [joomla/joomla-cms#32837]
### Steps to reproduce the issue
Search an article with quote or double quote on title
example: Foo bar's text

### Expected result
The title result have all chars printed on results
result example: Foo bar's text

### Actual result
actual result example: Foo bar's tex

**Comment by ReLater** [comment]
I think there's already a solution for and this issue can be closed.
Please test https://github.com/joomla/joomla-cms/pull/32637 and mark it as successfully tested (if it works) to bring it in next Joomla 3.9 release.
