### ISSUE TITLE
[3.9.25] missing file /administrator/manifests/packages/pkg_weblinks.xml 

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#32836]
### Steps to reproduce the issue
I use Watchful.net to monitor my Joomla websites.
On my latest scan it's telling me that it is missing a core file:
/administrator/manifests/packages/pkg_weblinks.xml 

### Expected result
Not sure. Is it supposed to be there?

### Actual result
No sign of the file in that location

### System information (as much as possible)
J3.9.25, Linux Litespeed web server, PHP 7.3.27,

But also the same on a Joomla installation on a Linux Apache webserver

### Additional comments
I've seen this topic mentioned before, but it's all quite old.

**Comment by ghost** [comment]
Isn't weblinks an decoupled extension?

**Comment by Scrabble96** [comment]
> 
> 
> Isn't weblinks an decoupled extension?

I've no idea what 'weblinks' is. The file in question can be found in the Core files here, though.

**Comment by alikon** [comment]
no as it is not a core extension, but you can find it here https://github.com/joomla-extensions/weblinks/blob/master/src/administrator/manifests/packages/pkg_weblinks.xml

**Comment by Scrabble96** [comment]
Um, what's this then?

![image](https://user-images.githubusercontent.com/36987494/112357760-bb149180-8cc7-11eb-8f5a-ee595509d417.png)

**Comment by alikon** [comment]
oops :fearful: 
my bad didn't check that
i can guess a refuse ?

**Comment by Scrabble96** [comment]
Sorry, I don't know what a 'refuse' means in this context.

**Comment by alikon** [comment]
weblinks should be decoupled from core iirc...

**Comment by wilsonge** [comment]
Weblinks file is present in update packages as we didn't install it on old sites. But it should be available to update to a j4 compatible version

**Comment by wilsonge** [comment]
See the 4.0-dev branch here https://github.com/joomla-extensions/search

**Comment by ghost** [comment]
@wilsonge does your answer mean that the missing core file mentioned by @Scrabble96 is expected? Sorry, i don't understand the meaning.

**Comment by Hackwar** [comment]
Yes, the missing file is okay. Depending on the age of the site and if you kept or uninstalled the weblinks extension, that file can be present or not. This issue can be closed.
