### ISSUE TITLE
Smart Search result: Wrong content type sorting

### ISSUE THREAD

**Issue by slepoy1** [joomla/joomla-cms#32843]
### Steps to reproduce the issue
In backend > plugins > finder, I sorted plugins to display "Users" at the end of list:
1. Smart Search - EasyBlog Posts
2. Smart Search - EasySocial Videos
3. Smart Search - EasySocial Albums
4. Smart Search - EasySocial Groups
5. Smart Search - EasySocial Users

### Result
But in fact (IN FRONTEND), in search results the latest items is 3. “Smart Search - EasySocial Albums”.

### Expected result
I expected to see 5. “Smart Search - EasySocial Users” at the end (Albums should be before Users).

### Actual result
So, I suppose Joomla doesn't respect backend sorting and it is a bug?

### System information (as much as possible)
Latest Joomla!

**Comment by Hackwar** [comment]
Smart Search sorts results by relevance. The order of the finder plugins has no influence on the order of the search results. The finder plugins are never executed during searching. They are only used to populate the index. This is not a bug, but expected behavior.

**Comment by HLeithner** [comment]
As hannes said that's expected but relevance could be adjusted by the indexing plugin
