### ISSUE TITLE
[4.0] Uncaught TypeError: input is null

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#32852]
### Steps to reproduce the issue

Log in to the backend.
Edit your profile.
Go to J`oomla API Token` tab.
Click `Save` button to generate token.
Click the `Copy` button.
View browser's console.
See error.

### Actual result

```
Uncaught TypeError: input is null
    copyToClipboard http://localhost/joomla-cms-4.0-dev/media/plg_user_token/js/token.js?2223806412ac1f62b6b460bceca7f0dd:42
```

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/32853 should fix this issue.
