### ISSUE TITLE
Created Date changes on every save if timezone is other than UTC

### ISSUE THREAD

**Issue by forrestkirby** [joomla/joomla-cms#32856]
### Steps to reproduce the issue

- install Joomla! with Blog Demo Data and German language pack
- set Time Zone in Global Configuration 🠖 Server to `Berlin`
- note the current time and create a new category
- edit the category and view the *Publsihing* tab: the *Created Date* will be the actual creation date + 1 hour
- save the category (without having edited anything)
- view the *Publsihing* tab again: the *Created Date* will now be the actual creation date + 2 hours

[Screencast illustrating the issue](https://www.screencast.com/t/oZgcZcLLY6Oc)

### Expected result

Created Date does not change on save.

### Actual result

Created Date changes on save if timezone is other than UTC.

### System information (as much as possible)

PHP Built On | Linux dd45920 4.15.0-136-generic #140~16.04.1-Ubuntu SMP Wed Feb 3 18:51:03 UTC 2021 x86_64
Database Type | mysql
Database Version | 5.7.28-nmm1-log
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.4.14
Web Server | Apache
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 3.9.25 Stable [ Amani ] 02-March-2021 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36

### Additional comments

Here are some similar issues, however I am not sure whether they are related.

#30343
#20807
#20271
#14284
#12329

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/32857 should fix this issue. Please test.

**Comment by forrestkirby** [comment]
PR #32857 fixes the issue, thank you!
