### ISSUE TITLE
Mail() Error on Password reset

### ISSUE THREAD

**Issue by ChrisDGFr** [joomla/joomla-cms#32858]
### Steps to reproduce the issue

Reset Password form or Login reminder

### Expected result
A mail is sent to the user.

### Actual result
Announcement
Can't launch the mail function.

Error
Unable to send the e-mail.

### System information (as much as possible)
Joomla! 3.9.21 and 3.9.25 on PHP 7.3.27.

### Additional comments

I have configured Joomla to send mail with the mail() function. The test of sending mail works.
Sending "contact form" works.

This error appeared recently.

**Comment by saumyasarkar11** [comment]
> ### Steps to reproduce the issue
> Reset Password form or Login reminder
> 
> ### Expected result
> A mail is sent to the user.
> 
> ### Actual result
> Announcement
> Can't launch the mail function.
> 
> Error
> Unable to send the e-mail.
> 
> ### System information (as much as possible)
> Joomla! 3.9.21 and 3.9.25 on PHP 7.3.27.
> 
> ### Additional comments
> I have configured Joomla to send mail with the mail() function. The test of sending mail works.
> Sending "contact form" works.
> 
> This error appeared recently.

Add [3.9] in the PR title

**Comment by saumyasarkar11** [comment]
Add [3.9] in the PR title

**Comment by richard67** [comment]
> Add [3.9] in the PR title

@saumyasarkar11 No, that's not necessary here. We only do that for issues specific to Joomla 4 or 3.10.

**Comment by saumyasarkar11** [comment]
> > Add [3.9] in the PR title
> 
> @saumyasarkar11 No, that's not necessary here. We only do that for issues specific to Joomla 4 or 3.10.

Ok, got it

**Comment by ChrisDGFr** [comment]
Mail() works [in password reset] when sending from site@<mysite>.fr to site@<mysite>.fr 
but not from site@<mysite>.fr to <mysite>@gmail.com<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32858">issues.joomla.org/tracker/joomla-cms/32858</a>.</sub>

**Comment by ChrisDGFr** [comment]
Mail() works [in password reset] when sending from site@mySite.fr to site@mySite.fr
but not from site@mySite.fr to mySite@gmail.com

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32858">issues.joomla.org/tracker/joomla-cms/32858</a>.</sub>

**Comment by ChrisDGFr** [comment]
Sending a Contact form works perfectly.![screen shot 2021-03-25 at 17 50 29](https://issues.joomla.org/uploads/1/16502aa2b39083ea90ed1b0261e1600f.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32858">issues.joomla.org/tracker/joomla-cms/32858</a>.</sub>

**Comment by ahotzler** [comment]
I tried to reproduce the problem, Joomla 3.9.25, PHP 7.3.27, PHP mail, Password Reminder "view=reset".

For me everything worked as expected

**Comment by PhilETaylor** [comment]
> Mail() works [in password reset] when sending from site@mySite.fr to site@mySite.fr but not from site@mySite.fr to mySite@gmail.com

This sounds like your webhost doesn't allow relaying mail 

ALL of Joomla's mail goes through the Mail Layer in Joomla, all emails are sent the same way. Therefore if the test mail works then all should work.

Can you try setting your email address in Joomla Global Config to the `mySite@gmail.com` email you are truing and attempt to send a test email to that email (not password reset - a test email using the Test Mail button.)

**Comment by ahotzler** [comment]
> > Mail() works [in password reset] when sending from [site@mySite.fr](mailto:site@mySite.fr) to [site@mySite.fr](mailto:site@mySite.fr) but not from [site@mySite.fr](mailto:site@mySite.fr) to [mySite@gmail.com](mailto:mySite@gmail.com)
> 
> This sounds like your webhost doesn't allow relaying mail

Doesnt make sense, he wrote "The test of sending mail works."

**Comment by PhilETaylor** [comment]
> Doesnt make sense, he wrote "The test of sending mail works."

The "The test of sending mail works." because he is sending from site@mySite.fr to site@mySite.fr

I want to know if it works sending to an OFF SERVER domain name like gmail.com

**Comment by ahotzler** [comment]
Ok, now i understand what you mean. Would such a behaviour end in: "Can't launch the mail function."?

**Comment by PhilETaylor** [comment]
In my testing.. yes.

**Comment by ahotzler** [comment]
Ok, thanks, I didn't expect that.

**Comment by ChrisDGFr** [comment]
I added the statement "JLog::add('my error message', JLog::ERROR)" at the beginning of the PHPMailer::mailSend function.
I have a log when the function is called from a contact form, but not from the com_users module.
Bad luck!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32858">issues.joomla.org/tracker/joomla-cms/32858</a>.</sub>

**Comment by PhilETaylor** [comment]
Password reset uses:

```php
		// Send the password reset request email.
		$return = JFactory::getMailer()->sendMail($data['mailfrom'], $data['fromname'], $user->email, $subject, $body);
```


Contact form uses:

```php
		$mail = JFactory::getMailer();
		$mail->addRecipient($contact->email_to);
		$mail->addReplyTo($email, $name);
		$mail->setSender(array($mailfrom, $fromname));
		$mail->setSubject($sitename . ': ' . $subject);
		$mail->setBody($body);
		$sent = $mail->Send();
```

The `sendMail()` method simple sets the params and then calls `send` method. So they are both using the same code eventually to send.

"Can't launch the mail function" is not a exact phrase used anywhere in Joomla or phpMailer so I assume that is translated. What is the exact phrase used in your language on the screen - send a screenshot.

**Comment by PhilETaylor** [comment]
Also please run this test: 

> Can you try setting your email address in Joomla Global Config to the mySite@gmail.com email you are truing and attempt to send a test email to that email (not password reset - a test email using the Test Mail button.)

Im still convinced this is a hosting issue.

**Comment by ChrisDGFr** [comment]
That is the exact phrase.
![Image 111](https://user-images.githubusercontent.com/4035917/113182584-5c18c480-9253-11eb-9d1d-47f3b813eac2.jpg)

**Comment by PhilETaylor** [comment]
Well that is being raised by phpMailer when it cannot sed using the linux `mail` function (E.g a web hosting issue) Do you have `safe_mode` enabled in PHP?

https://github.com/joomla/joomla-cms/blob/afc196adc65a83458a35277b00d4ff5018b40450/libraries/vendor/phpmailer/phpmailer/class.phpmailer.php#L1524

The actual mail command is in this function on lines 700 and 702 of libraries/vendor/phpmailer/phpmailer/class.phpmailer.php, So remove the error suppressor `@` before the word `@mail` and then repeat your tests with error reporting set to development/maximum in Joomla global Config and debug mode on and see if any further error is output now that the command is not suppressed. 

https://github.com/joomla/joomla-cms/blob/afc196adc65a83458a35277b00d4ff5018b40450/libraries/vendor/phpmailer/phpmailer/class.phpmailer.php#L688

```php
    private function mailPassthru($to, $subject, $body, $header, $params)
    {
        //Check overloading of mail function to avoid double-encoding
        if (ini_get('mbstring.func_overload') & 1) {
            $subject = $this->secureHeader($subject);
        } else {
            $subject = $this->encodeHeader($this->secureHeader($subject));
        }

        //Can't use additional_parameters in safe_mode, calling mail() with null params breaks
        //@link http://php.net/manual/en/function.mail.php
        if (ini_get('safe_mode') or !$this->UseSendmailOptions or is_null($params)) {
            $result = mail($to, $subject, $body, $header);
        } else {
            $result = mail($to, $subject, $body, $header, $params);
        }
        return $result;
    }
```

**Comment by PhilETaylor** [comment]
Also try running mail independently of Joomla by creating a test.php file with this in it:

```php
<?php
error_reporting(E_ALL);
ini_set('display_errors',1);
mail('youremail@gmail.com','subject','test');
```

and then run that and see if there are any errors.

**Comment by ChrisDGFr** [comment]
I think I found the problem.

**Works :**

From email : site@mySite.fr
Reply to email : site@mySite.fr

**Do not work :**

From email : site@mySite.fr
Reply to email : mySite@gmail.com

From email : mySite@gmail.com
Reply to email : mySite@gmail.com

It seems that com_users takes "Reply to email" as "From email".

**Comment by PhilETaylor** [comment]
Cough Cough. This is not a Joomla issue. This is a hosting issue.

> Im still convinced this is a hosting issue.

>This sounds like your webhost doesn't allow relaying mail

**Comment by ChrisDGFr** [comment]
It seems normal that the site mySite.fr can not send mail from the domain gmail.com.

**Comment by ChrisDGFr** [comment]
Com_users should use the sender designated to it: site@mySite.fr.

**Comment by PhilETaylor** [comment]
It does. It uses the `$mailfrom` value from global config. 

https://github.com/joomla/joomla-cms/blob/afc196adc65a83458a35277b00d4ff5018b40450/components/com_users/models/reset.php#L457

**Comment by ChrisDGFr** [comment]
How do you explain that :

**Works :**

From email : site@mySite.fr
Reply to email : site@mySite.fr

**Do not works :**

From email : site@mySite.fr
Reply to email : mySite@gmail.com

**Comment by PhilETaylor** [comment]
I do not know who your site is configured. I do know what the code states. 

What are the VALUES you have set in your Joomla global Configuration?

**Comment by PhilETaylor** [comment]
> From email : site@mySite.fr

If that is the value in your Joomla Global Config for the Mail Sending - So Joomla is correctly using the same FROM address. And correctly changing the Reply from address on emails that might need a reply, and your webhost is rejecting those - because that's also what spammers do. 

I see nothing that needs fixing here in Joomla.

**Comment by PhilETaylor** [comment]
> This error appeared recently.

Code doesn't change :) webhost configurations and spam controls change :-)

**Comment by ChrisDGFr** [comment]
Here are pictures of the different configurations and their consequences.
![Image 116](https://user-images.githubusercontent.com/4035917/113189243-44ddd500-925b-11eb-8244-8d79de385714.jpg)
![Image 119](https://user-images.githubusercontent.com/4035917/113189306-57f0a500-925b-11eb-93cc-f1fb3cccefd3.jpg)
![Image 122](https://user-images.githubusercontent.com/4035917/113189333-62ab3a00-925b-11eb-9b9a-e19966a14ea5.jpg)

**Comment by PhilETaylor** [comment]
![image](https://user-images.githubusercontent.com/400092/113190930-d6961400-9254-11eb-8812-f01f7057264c.jpeg)

So your failure is failing to send using the `mail` function on your webhost, an email FROM a gmail.com address ... again, this is your webhost probably stopping you with spam controls on what addresses you can send from with PHP Mail. This is totally normal for a webhost to stop spamming this way. 

If you want to use your gmail.com account email as the sender or reply, then use SMTP mail (which has better debugging and error messages) and even configure it to [send mail using the Gmail SMTP servers](https://docs.joomla.org/How_do_I_use_Gmail_as_my_mail_server%3F).

**Comment by ChrisDGFr** [comment]
You know what, I am going to add a Forwarder from site@clapiedsrando.fr to clapiedsrando@gmail.com.

**Comment by PhilETaylor** [comment]
Run this as a test

```php
<?php
error_reporting(E_ALL);
ini_set('display_errors', 1);

$to      = 'clapiedsrando@gmail.com';
$subject = 'the subject';
$message = 'hello';
$headers = 'From: clapiedsrando@gmail.com' . "\r\n" . 'Reply-To: clapiedsrando@gmail.com' . "\r\n";

mail($to, $subject, $message, $headers);
```

**Comment by ChrisDGFr** [comment]
The difference between image 1 (success) and image 2 (failure) is not "From email" but "Reply to Email".

**Comment by PhilETaylor** [comment]
Correct. I know that. But you are not listening. This is not Joomla's fault if your webhost is blocking you from having a Gmail address in the headers. 

[RUN THE TEST](https://github.com/joomla/joomla-cms/issues/32858#issuecomment-811307123) I have asked you to and report if it works or errors please.

**Comment by ahotzler** [comment]
> ...
> 
> So your failure is failing to send using the `mail` function on your webhost, an email FROM a gmail.com address ... again, this is your webhost probably stopping you with spam controls on what addresses you can send from with PHP Mail. This is totally normal for a webhost to stop spamming this way.
> 
> If you want to use your gmail.com account email as the sender or reply, then use SMTP mail (which has better debugging and error messages) and even configure it to [send mail using the Gmail SMTP servers](https://docs.joomla.org/How_do_I_use_Gmail_as_my_mail_server%3F).

What Phil says is correct. The whole discussion has become completely pointless.

**Comment by alikon** [comment]
matter for https://forum.joomla.org/ imho

**Comment by PhilETaylor** [comment]
I tried to help :)

**Comment by richard67** [comment]
> I tried to help :)

@PhilETaylor You could have fixed 5 bugs in the mean time 😜
