### ISSUE TITLE
[4.0] subfields terminology

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32860]
I was doing some work today with the new subfields and I found it quite difficult to explain. I think that instead of saying

"This plugin lets you create new fields of type 'subfields' in any extension where custom fields are supported."

We change it so that field is called subform and the fields inside it are just fields

"This plugin lets you create new fields of type 'subform' that contains other fields in any extension where custom fields are supported."

![image](https://user-images.githubusercontent.com/1296369/112465337-856db800-8d5c-11eb-8447-b00d9ceed5fb.png)

@AndySDH your thoughts?

**Comment by AndySDH** [comment]
Thanks for tagging me :)

I can agree, subform can sound better than "subfields / "sub fields" terminology.

subform was actually the original name (https://github.com/joomla/joomla-cms/pull/22446#issuecomment-431360034), but then a discussion arised that it was already used by an extension (https://github.com/joomla/joomla-cms/pull/22446#issuecomment-429035134). Then again, that extension has not been updated in 3 years, so it may not even make J4.

I personally have nothing against renaming it to subform, sounds good.

**Comment by brianteeman** [comment]
Please test #32864
