### ISSUE TITLE
[4] Something broke Joomla 4 Global Config tabs in 4.0-dev

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32867]
### Steps to reproduce the issue

` git reset --hard`
` git pull`
`git checkout 4.0-dev`
`rm -rf administrator/templates/atum/css; rm -rf templates/cassiopeia/css; rm -rf media/; rm -rf node_modules/; rm -rf libraries/vendor/; composer install; npm ci;` 

Gives commit
f6004739b367f65f2f4c6ee1fdfa70f7ed7dff0b

visit Joomla Admin -> Global Configuration 

### Expected result

Tabs and no JS error

### Actual result

No Tabs and JS error

`SyntaxError: The string did not match the expected pattern.`

<img width="793" alt="Screenshot 2021-03-25 at 21 19 56" src="https://user-images.githubusercontent.com/400092/112545230-de1a7080-8daf-11eb-8f64-bf8d27af8244.png">

**Comment by PhilETaylor** [comment]
@dgrammatiko ?

**Comment by PhilETaylor** [comment]
restarted Safari and seems ok now... very very strange

**Comment by dgrammatiko** [comment]
Aggressive Browser caching? (the dev env shares the same mediaversion hash no matter how many git checkouts you did, the hash is based on the JVersion which basically is the same for the 4.0-dev)

**Comment by PhilETaylor** [comment]
Maybe, Ive had a few issues recently with Safari though (Im running the beta version of macOS) 

forgive me, this is not a bug, and I should have restarted my browser before reporting (although I did checkout many different revisions and rebuild from scratch several times!)
