### ISSUE TITLE
Receiving 'Error due to concurrent publishing operation!' when trying to publish 

### ISSUE THREAD

**Issue by Rossig66** [joomla/joomla-cms#32872]
When trying to publish on Joomla version 1.0.15 I keep getting the error message 'Error due to concurrent publishing operation!'

No other user is online or has tried to publish, only me. I was able to successfully publish an hour before the error first appeared but have been unable to since seeing it. It occurred yesterday morning and has been ongoing since ..... please help!

Please see attached the error messgage

**Comment by rdeutz** [comment]
Joomla 1.x is out of support for pretty much 12 years and for such question we have a forum https://forum.joomla.org/ but I have my doubts that you find someone who can help you.
