### ISSUE TITLE
[4.0] Field Layouts 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32874]
#32422 introduced a range of utility classes that can be used to set the width and layout of fields... This was essential because some pages with columns (eg template styles) just didnt work and the fields would jump around so we switched to a single column 

So now we need a plan to apply the utility classes throughout the admin to resolve some issues such as 100% width input fields not being accessible or particularly usable

**Comment by rdeutz** [comment]
I would say we make it component by component, so that we don't run into too much merge conflicts. I think the first step should be a list where we have to change things

**Comment by Magnytu2** [comment]
I don't know if this is the right place. But as you touch once again the administration template. Are you going to put the fields back into two or three columns? The user experience is really nagative to build and extend all the fields to use Joomla !. For example, even with a 32" 4K screen, I cannot have the image and the settings on the same view.
<img width="2540" alt="Capture d’écran 2021-04-16 à 17 37 53" src="https://user-images.githubusercontent.com/26197929/115052117-ddbc5380-9edd-11eb-881f-638b6cfe39a1.png">

**Comment by brianteeman** [comment]
the answer is no not multiple columns as they dont work
but yes to not full width

**Comment by PhilETaylor** [comment]
Eg <img width="1591" alt="Screenshot 2021-04-22 at 18 09 10" src="https://user-images.githubusercontent.com/400092/115758637-418bc400-a397-11eb-901d-808ecbaee8d1.png">

**Comment by brianteeman** [comment]
Closed due to lack of interest
