### ISSUE TITLE
Joomla 4 website's backend not working after renaming htaccess.txt to .htaccess

### ISSUE THREAD

**Issue by Mohamed1308** [joomla/joomla-cms#32892]
Hello.
I got a issue after renaming htaccess.txt to .htaccess in the public_html folder of my Joomla 4 website (https://www.freepetsitters.com). I renamed it in order to get rid of "index.php" in the URLs.
### Steps to reproduce the issue
1. Download Helix Ultimate 2 Beta 1 Quickstart Package (https://github.com/JoomShaper/helix-ultimate/releases/tag/v2.0.0-beta.1), upload it to the public_html folder of your website, unzip it and then follow the standard Joomla installation procedure.
2. Upgrade your website to Joomla 4 Beta 7.
3. Set "Use URL Rewriting" to "Yes" (In the Global Configuration tab of the Joomla administrator panel).
4. Rename htaccess.txt to .htaccess in the public_html folder of your website.
5. Delete the cookies and website data, then refresh the Joomla administrator panel's tab.
### Expected result
The website's backend looking like it was (before renaming htaccess.txt to .htaccess) and working fine.
### Actual result
The administrator panel looking weird and not working (There is no interactivity when clicking on any button).
### System information (as much as possible)
**LiteSpeed-based server**
PHP: 7.3 lsphp
Joomla: 4 Beta 7
Helix Ultimate: 2 Beta 1
### Additional comments
Here is what I got in the logs file:
`WARNING ...	assets	No asset found for com_modules.module.92, falling back to com_modules`

I also don't think that the problem is related to the website's template (Helix Ultimate 2 Beta 1) since the issue only occurs for the backend and not the frontend.

**Comment by AMurray2016** [comment]
I've left a comment on the Joomla forum about this: https://forum.joomla.org/viewtopic.php?f=803&t=985622&p=3627757#p3627757.  In essence: Quick-starts are not the recommended way to install Joomla. 

For your testing, I would use the J4 nightly build, then install Helix Ultimate 2.0 Beta 1 through Extension Manager, and avoid the quick-start package altogether; Joomshaper should provide this Beta 1 release as a stand-alone template install package on their GITHUB site.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32892">issues.joomla.org/tracker/joomla-cms/32892</a>.</sub>

**Comment by Mohamed1308** [comment]
Hello @AMurray2016.
As I have already mentioned on https://forum.joomla.org/viewtopic.php?f=803&t=985622&p=3627766, I also got the problem after using a J4 Full Package (In my case, Joomla 4 Beta 5) without installing Helix Ultimate.

**Comment by Fedik** [comment]
It not a Joomla! issue. Ask for support in the extension developers.

> The administrator panel looking weird and not working (There is no interactivity when clicking on any button).

the extension is "hacking" joomla runtime

> WARNING ... assets No asset found for com_modules.module.92, falling back to com_modules

And this is another confirmation.

**Comment by richard67** [comment]
@Fedik In the forum post the author states he has tried with a regular Beta 5 and without the Helix Ultimate.

**Comment by richard67** [comment]
@Mohamed1308 Did you also read the FAQ for Joomla 4 Beta 5? It tells that there is an extra step to do in SQL, e.g. in phpMyAdmin.

Please report back if you had followed these instructions or not, and please do as advised in the support forum and try with the latest Joomla 4 Beta, which is Joomla 4 Beta 7 and can be found here: https://github.com/joomla/joomla-cms/releases/tag/4.0.0-beta7 , and report back the result here and in the forum. Thanks in advance.

**Comment by richard67** [comment]
P.S.: Joomla 4 Beta 7 doesn't need that additional SQL step.

**Comment by PhilETaylor** [comment]
> LiteSpeed-based server PHP: 7.3 lsphp

LiteSpeed is not officially supported by the Joomla Project (although its **mostly** a direct replacement for Apache, and even Rochen, who host joomla.org use it for Joomla.org, still... its not officially supported by the Joomla Project https://downloads.joomla.org/technical-requirements) - just a FYI as there are differences.

**Comment by ghost** [comment]
@Mohamed1308 any news on your issue?

**Comment by Mohamed1308** [comment]
@Fedik I got the same issue after using the Joomla 4 Beta 7 Full Package (https://github.com/joomla/joomla-cms/releases/tag/4.0.0-beta7) without installing Helix Ultimate, so it really is a Joomla problem and it isn't related to any extension.

@richard67 The problem still persists with Joomla 4 Beta 7. I installed J4 on an empty website (https://www.dv2025.com) via the Beta 7 Full Package (https://github.com/joomla/joomla-cms/releases/tag/4.0.0-beta7) and the result was similar after renaming htaccess.txt to .htaccess (The backend not working and looking strange). In addition to that, the problem is also present in the frontend for https://www.sitename.com, but it isn't for https://sitename.com (So, https://www.dv2025.com looks strange, but https://dv2025.com doesn't).
I didn't install Helix Ultimate in the website, thus the problem isn't related to it.

**Comment by ghost** [comment]
@Mohamed1308 thanks for your answer. i do now every day a fresh install using launch.joomla.org. The first thing i do is renaming htaccess.txt to .htacccess and i never got your issue. Hope this help to find whats happen.

**Comment by Fedik** [comment]
@Mohamed1308 My previous comment was wrong.

As @PhilETaylor  already wrote in one comment before:
> LiteSpeed is not officially supported by the Joomla Project 

To make it work you have to configure .htaccess for LiteSpeed server.

**Comment by PhilETaylor** [comment]
> The administrator panel looking weird and not working (There is no interactivity when clicking on any button).

Unless you can accurately communicate WHAT was wrong, then this issue should be closed. 

Just saying something is "looking weird and not working" is not good enough. 

I "look weird and not working" most of the time... it doesn't mean there there is a problem with me... oh wait... 

Open up your browsers console, report any Javascript errors, check the the network tab, refresh the page and report any network assets that come back as red/404/403/500 errors in the list. Better still send screenshots of the complete network panel for us to interpret with our experience.

**Comment by joomdonation** [comment]
The javascript / css files on the site are being blocked and that's the reason causing the error. We just don't know why it is blocked 
<img width="940" alt="errors" src="https://user-images.githubusercontent.com/977664/114297879-69e50a00-9add-11eb-956d-23722a2d3a54.png">

**Comment by PhilETaylor** [comment]
These are not blocked. 

`ERR_CONTENT_DECODING_FAILED` means that they are being double gzipped and therefore corrupted. 

This is not a Joomla issue, this is a hosting issue. 

If the hosting is already zipping JS files, then Joomla doesn't need to. This is up to the user to configure their site correctly or their server correctly.

**Comment by joomdonation** [comment]
@PhilETaylor Do you have any tip for him? Or should we tell him to contact hosting provider and ask them to check?

**Comment by PhilETaylor** [comment]
Simple, remove the last section in .htaccess. Its not needed on this webhost because the server configuration already has been configured to gzip js files. 

https://github.com/joomla/joomla-cms/pull/33097

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33097 . Thanks in advance.
