### ISSUE TITLE
Administrator login form doesn't follow Post/Redirect/Get pattern

### ISSUE THREAD

**Issue by rjharishabh** [joomla/joomla-cms#32895]
### Steps to reproduce the issue
* Login to Administrator with incorrect credentials
* Refresh the page and the error message was there. 

### Expected result
The error message should be disappeared after refreshing the page.

### Actual result

https://user-images.githubusercontent.com/61203226/112757660-62673080-9008-11eb-910d-30dc2754efc9.mp4

### System information (as much as possible)
PHP 8.0.3
Chrome  on Windows 10

**Comment by PhilETaylor** [comment]
Please test #32897

**Comment by rjharishabh** [comment]
Yeah, thanks
