### ISSUE TITLE
[4.0] Column 'ordering' cannot be null when restoring original version

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#32890]
### Steps to reproduce the issue
Create a new article.
Click `Save` button.
Edit article.
Click `Save`  button.
Edit article.
Click `Versions` button.
Click on a version.
Click `Restore` button.

### Actual result
> Column 'state' cannot be null

**Comment by brianteeman** [comment]
is this with workflow enabled?

**Comment by Quy** [comment]
Yes. However, when workflow is disabled, there is a different message.

> Column 'ordering' cannot be null

**Comment by brianteeman** [comment]
there is a release blocker for versions and workflow

**Comment by PhilETaylor** [comment]
Confirmed. Can you confirm this was tested in PHP 8? 
<img width="511" alt="Screenshot 2021-03-27 at 18 20 39" src="https://user-images.githubusercontent.com/400092/112730498-cf57c900-8f29-11eb-8a80-5b15047f4c6c.png">

**Comment by Quy** [comment]
PHP 7.4.9

**Comment by PhilETaylor** [comment]
Please confirm your CANT restore the original version but your CAN restore subsequent versions

**Comment by Quy** [comment]
I can restore versions except for the last one listed.

**Comment by PhilETaylor** [comment]
The "last one listed" is "the first version created when you first create the article"... when the ordering is 0 in the db...

**Comment by Quy** [comment]
I confirm your assessment.

**Comment by PhilETaylor** [comment]
trying to restore the original version of a Category gives other null warnings

<img width="732" alt="Screenshot 2021-03-27 at 19 01 49" src="https://user-images.githubusercontent.com/400092/112731410-f369d900-8f2e-11eb-9af8-d6684bbf79bc.png">

**Comment by PhilETaylor** [comment]
Ive debugged this but now Im in a loop and I cannot fight my way out, it seems that "ordering" on an Article being inserted to the db gets coverted from a 0 to NULL deep in the process for updating the assets tables.. in libraries/src/Table/Nested.php there is 

```php
$oldDispatcher = clone $this->getDispatcher();
		$blankDispatcher = new Dispatcher;
		$this->setDispatcher($blankDispatcher);

		$result = parent::store($updateNulls);

		// Restore previous callable dispatcher state:
		$this->setDispatcher($oldDispatcher);
```

Before the store, the ordering is 0 and after the store its NULL, which is then passed the the versioning plugin using the onTableAfterStore event...

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/issues/32890 should fix the issue for both category and article. I don't know how workflow works, so I don't set default value for state field to avoid it causes un-expected behavior. For workflow enabled, maybe a different PR would be needed.

**Comment by Quy** [comment]
Thanks!

**Comment by PhilETaylor** [comment]
Correct PR number is #32932
