### ISSUE TITLE
[4] com_finder limitations on number of authors and categories

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32900]
### Steps to reproduce the issue

My site (thanks to [Overload](https://github.com/nikosdion/overload)) is huge. 

I (could) have 20,000 different Authors. 
I (could) have 20,000 different Categories. 

The actual number is irrelevant. 

The point is that a menu item pointing to Smart Search will load ALL the author names into the HTML and all the Category names into the HTML

The Problem:
**This makes the browser unresponsive, or makes the selection of a single author or category a slow huge task. The browser struggles to load the elements when clicked** 

They are all loaded on page load into the HTML regardless of if advanced search is being used. 

### Expected result

Great user experience on large Joomla sites. 

### Actual result

Bad user experience on large Joomla sites. 
This makes the browser unresponsive, or makes the selection of a single author or category a huge task. 

### System information (as much as possible)

Am I being unrealistic with 20,000 authors? maybe, but the same applies to 100 & 10000. Joomla should still be able to perform and not grind the browser to a halt. 

### Additional comments
Here is a dump of a HUGE database for you https://www.phil-taylor.com/HUGE.sql.gz (Joomla admin u: admin p: adminadminadmin)

**Comment by Hackwar** [comment]
Would #36867 be an acceptable fix for this to you?

**Comment by Hackwar** [comment]
There has been no response from @PhilETaylor, but I guess #36867 is an acceptable solution for the problem. So I would ask to close this one.
