### ISSUE TITLE
[4][com_finder] Authors are not sorted a-z or any way

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32901]
### Steps to reproduce the issue

Lots of authors ! 

Visit Smart Search menu item on frontend

View the authors dropdown 

### Expected result

A-Z on name? on Surname(probably not doable as could be an author alias which is just a string) ?

### Actual result

<img width="448" alt="Screenshot 2021-03-28 at 19 11 44" src="https://user-images.githubusercontent.com/400092/112762833-d0f0c200-8ff9-11eb-961e-3c9313940340.png">

### Additional comments
Here is a dump of a HUGE database for you https://www.phil-taylor.com/HUGE.sql.gz (Joomla admin u: admin p: adminadminadmin)

**Comment by meinhoonharsh** [comment]
I want to work on this Issue

**Comment by meinhoonharsh** [comment]
I am unable to reproduce this Issue
.
When I click on Smart Search
I can see only four Options in dropdown 
>Index
>Content Maps
>Filter
>Search Terms
may be I was having a lack of Something or anything else, could you  please help

**Comment by PhilETaylor** [comment]
You need to add some articles and index them.

**Comment by PhilETaylor** [comment]
Or use the database provided I the issue which is huge and has a lot of articles and different authors...
