### ISSUE TITLE
[4] Voting set to bottom is after pagination

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32909]
### Steps to reproduce the issue

Enable `Content - Vote` plugin with Bottom option selected
Enable `Voting` in Article options
Visit an article 

### Expected result

Content then voting then pagination

### Actual result

Content then pagination then voting

<img width="1029" alt="Screenshot 2021-03-28 at 20 55 48" src="https://user-images.githubusercontent.com/400092/112766061-fdabd600-9007-11eb-8975-784e68dad7ac.png">

### category view 
<img width="1021" alt="Screenshot 2021-03-28 at 20 56 04" src="https://user-images.githubusercontent.com/400092/112766066-07353e00-9008-11eb-948d-116750ff53b6.png">

**Comment by Quy** [comment]
PR #32914

**Comment by rjharishabh** [comment]
@Quy Please re-open this issue as the PR has been closed.
