### ISSUE TITLE
[4] Page loader overlay position on install from url screen

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32916]
### Steps to reproduce the issue

In Joomla 4 admin attempt to install Akeeba Backup for Joomla 4 using the Install From URL method

https://www.akeeba.com/download/akeeba-backup/8-0-2/pkg_akeeba-8-0-2-core-zip.zip

### Expected result

The page overlay to have the Joomla logo somewhere near the middle of the screen

### Actual result

<img width="1594" alt="Screenshot 2021-03-28 at 22 51 38" src="https://user-images.githubusercontent.com/400092/112769526-7ebf9900-9019-11eb-8f17-73e14118ffb7.png">

### System information (as much as possible)

safari on mac

**Comment by rs4231199** [comment]
Confirmed on Edge(chromium based) Windows

**Comment by rs4231199** [comment]
Im working on this

**Comment by saumyasarkar11** [comment]
I don't find this on google chrome

**Comment by rs4231199** [comment]
@PhilETaylor 
Is this the expected behavior?
![image](https://user-images.githubusercontent.com/43215292/113090242-f7377d00-9206-11eb-92a3-04c36b5127e3.png)

Or should it cover the whole screen?

edit: I think it is right because this is the way it shows in Joomla-3.

**Comment by rs4231199** [comment]
> I don't find this on google chrome

@saumyasarkar11
That is probably because of the screen size. Zoom out up to 25%, then test it.

**Comment by PhilETaylor** [comment]
> Or should it cover the whole screen?

No idea.

**Comment by PhilETaylor** [comment]
#32940
