### ISSUE TITLE
[4.0] Missing images ?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32929]
The images referenced in the css below do not exist. Not sure if this is a missing files problem or a bad css problem

https://github.com/joomla/joomla-cms/blob/ec5c72b21109906080673c2888838240e95df288/administrator/templates/system/scss/system.scss#L38-L69

**Comment by richard67** [comment]
Looks like either a copy and paste issue or an upmerge issue, or some old historical stuff from times when the Atum template was created.

Images with such names only exist in 3.x:

```
richard@vmkubu02:~/lamp/public_html/joomla-cms$ find ./ -type f -name "notice*\.png"
./administrator/templates/hathor/images/notice-alert.png
./administrator/templates/hathor/images/notice-note.png
./administrator/templates/hathor/images/notice-info.png
./templates/beez3/images/system/notice-alert.png
./templates/beez3/images/system/notice-note_rtl.png
./templates/beez3/images/system/notice-alert_rtl.png
./templates/beez3/images/system/notice-note.png
./templates/beez3/images/system/notice-info.png
./templates/beez3/images/system/notice-info_rtl.png
./media/system/images/notice-alert.png
./media/system/images/notice-note.png
./media/system/images/notice-info.png
./media/system/images/notice-download.png
richard@vmkubu02:~/lamp/public_html/joomla-cms$
```

In the 4.0-dev branch are no images with names like `notice*.png`.

**Comment by richard67** [comment]
Hmm, no upmerge issue. This file `joomla-cms/administrator/templates/system/scss/system.scss` has been added with PR #31221 . => Ping @dgrammatiko .

**Comment by dgrammatiko** [comment]
All these files are totally useless. I mean frames (not iframes!!!) are not supported anymore. Actually I was thinking to totally remove the system templates and patch the one place where these things are used (as fallbacks) with a prerendered html (as we re doing for the other hard fails)

**Comment by Fedik** [comment]
This is from joomla 2.5, or even older 1.5
At that time we did not have layouts system. This style was loaded to keep styled "important parts" in fallbacks when the default template do not have index.php or component.php.

In joomla 4 the messages styles loaded with layout 
https://github.com/joomla/joomla-cms/blob/ec5c72b21109906080673c2888838240e95df288/layouts/joomla/system/message.php#L43-L45

I think whole part with `#system-message` in `system.css` can be removed, or even whole system.css.

**Comment by Piyussshh** [comment]
@brianteeman I checked the images directory there were no such images named "notice-alert.png", "notice-note.png"

**Comment by brianteeman** [comment]
@Piyussshh thats exactly what I said

**Comment by Piyussshh** [comment]
> @Piyussshh thats exactly what I said
Then this is a missing file problem

**Comment by brianteeman** [comment]
Closed as we have a PR
