### ISSUE TITLE
[4.0.0-beta7] Problem with expand the left menu in admin side.

### ISSUE THREAD

**Issue by variax73** [joomla/joomla-cms#32934]
### Steps to reproduce the issue
1. Log as s Administrator.
2. Go to System->Administrator Modules.
3. Search "Admin Menu" (Id=12).
4. Duplicate them.
5. Publish them.
6. Collapse left menu ("Toggle Menu" switch). Showing narrow menu with icons only.
7. Click any icon from duplicated module - menu don't expand. Menu expands correctly only in first module.

### Expected result
Left menu expands for each modules added in position "menu".

### Actual result
Left menu expands correctly only in first module added in position "menu".

### System information (as much as possible)
OS:
- Windows 10 with last update

Browsers:
- Microsoft Edge Wersja 89.0.774.63 (Oficjalna kompilacja) (wersja 64-bitowa)
- Firefox Version 87.0
- Internet Explorer 11

**Comment by PhilETaylor** [comment]
I reported something similar and was told it was "by design"

**Comment by Shivanshuvyas** [comment]
Left menu expanded for one second for each module added.

**Comment by variax73** [comment]
No. Menu expand only for first module. Second and other don't expand menu.
