### ISSUE TITLE
Protostar: Buttons in button groups sometimes more separated from each other

### ISSUE THREAD

**Issue by gerryfrancis** [joomla/joomla-cms#32946]
### What needs to be fixed

Protostar (Joomla! version 3.x).

Buttons (`<label>` class `.btn`) within button groups are separated from each other with a 1 pixel gap occupied by their respective side frames when the HTML block includes other (`<input>`) lines in between.

This is an example of a button group when editing a module in the Protostar frontend:

![grafik](https://user-images.githubusercontent.com/51095533/113159021-92971500-923c-11eb-8617-06f13c943c81.png)

This is the underlying HTML code:

```
<fieldset id="jform_published" class="btn-group radio">
	<input type="radio" id="jform_published0" name="jform[published]" value="1" checked="checked">
	<label for="jform_published0" class="btn active btn-success">Published</label>
	<input type="radio" id="jform_published1" name="jform[published]" value="0">
	<label for="jform_published1" class="btn">Unpublished</label>
	<input type="radio" id="jform_published2" name="jform[published]" value="-2">
	<label for="jform_published2" class="btn">Trashed</label>
</fieldset>
```

### Why this should be fixed

Although editing is not broken in any way, it is neither intended nor transparent why alignment of buttons behaves differently.

This is an example of a button group that displays correctly:

![grafik](https://user-images.githubusercontent.com/51095533/113161026-4947c500-923e-11eb-9bc9-0195f1443bb7.png)

### How would you fix it

It seems that the CSS rule to close the gap does not apply in this scenario. I am no expert in CSS/LESS, but I believe that
```
.btn-group > .btn + .btn {
	margin-left: -1px;
}
```
should be replaced either with
```
.btn-group > .btn + input + .btn {
	margin-left: -1px;
}
```
or with
```
.btn-group > .btn ~ .btn {
	margin-left: -1px;
}
```
(different selector to address all `.btn` class elements on the same level).

### Side Effects expected

None.

### Personal remark

There may be other CSS/LESS rules with `+` selector affected when confrontated with additional HTML code lines between the elements. Besides, I do not know which (template) files other than `template.css` must be edited as well.

**Comment by anshi8269** [comment]
Can u please give the link to the website where the button separates differently?
or a pic when they get separated.
Actually, I didn't get the HTML file so I can see the problem.

**Comment by brianteeman** [comment]
@anshi8269 Everything you need to resolve this is in the post. If you don't understand that then it's probably not the right issue for you to work on.

**Comment by ChristineWk** [comment]
@anshi8269

It belongs to: editing a module in the Protostar frontend.

Actual Result:

![screen shot 2021-04-01 at 10 47 47](https://issues.joomla.org/uploads/1/3df8be2213bf7ade60c136638d0dd43c.jpg)


Expected Result:

![screen shot 2021-04-01 at 10 48 35](https://issues.joomla.org/uploads/1/308791432428cdde0fde6365336cf3c2.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32946">issues.joomla.org/tracker/joomla-cms/32946</a>.</sub>

**Comment by gerryfrancis** [comment]
Thanks to everyone for your commitment!

@ChristineWk That is correct, maybe I should have highlighted the info in the first place.

**Comment by joomdonation** [comment]
Joomla 3 is now in maintenance mode and only security bugs fixes, so changes like this won't be implemented anymore. Therefore, I'm closing this issue.

**Comment by gerryfrancis** [comment]
@joomdonation Never mind, it is just a minor cosmetic issue. Thanks for closing! :+1:
