### ISSUE TITLE
[4.0] Site Settings - front end

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#32950]
### Steps to reproduce the issue
Install the sample data and login to the frontend as a super user
Go to the site setting menu item or the template settings menu
Make any change
Save

### Expected result
The itemid is still the same - ie the big home page module is not displayed

### Actual result
there is no itemid so the big home page module is displayed

### Note
Verified that there is no itemid after the form is saved by repeating with SEF disabled

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/32960 should address this issue.
