### ISSUE TITLE
[4.0] None minified scripts are loaded

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#32957]
### Steps to reproduce the issue
- Open the back end.
- Open /administrator/index.php?option=com_config.
- Set debug mode to false in the Joomla configuration.
- Save.
- Open Network tab in dev tools.

![image](https://user-images.githubusercontent.com/251072/113291475-6094ba00-92f3-11eb-89ba-b1a9c68bad7a.png)

### Expected result
Only minified scripts are loaded.

### Actual result
Carousel is loaded none minified and dom.js is loaded in none minified version and minified.

### System information (as much as possible)
Latest 4.0 dev.

### Additional comments
Not sure if this is related to #32429 and https://github.com/joomla/joomla-cms/pull/32300.

Pinging here @dgrammatiko.

**Comment by dgrammatiko** [comment]
The code seems ok here: https://github.com/joomla/joomla-cms/blob/db414e7de7d0b9ceaf768ab145c9c6f91c714ad1/build/build-modules-js/javascript/build-bootstrap-js.es6.js#L19-L24

I can't replicate it with the default scripts on the page (the carousel is not in that view). Did you use HTMLHelper to load the scripts (eg using the `boostrap.carousel` helper: https://gist.github.com/dgrammatiko/efb3de4aa7cab4813a244f93f73cc0fd)?

![Screenshot 2021-04-01 at 14 17 51](https://user-images.githubusercontent.com/3889375/113292657-17456a00-92f5-11eb-837b-0a6935dbc567.png)
![Screenshot 2021-04-01 at 14 17 18](https://user-images.githubusercontent.com/3889375/113292660-17de0080-92f5-11eb-8553-de3957c00768.png)

**Comment by brianteeman** [comment]
Is this still an issue for you as I cannot replicate it

![image](https://user-images.githubusercontent.com/1296369/127821986-d8a9f386-eb67-4367-bc50-b7730b2109f2.png)

**Comment by laoneo** [comment]
Nope, issue is gone along the way.
