### ISSUE TITLE
[4][CLI] Cannot delete users

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32966]
### Steps to reproduce the issue

php cli/joomla.php  user:add
test
test
test@example.xom
6

php cli/joomla.php  user:delete
test
yes

### Expected result

User just created is deleted. 

### Actual result

Bug 1:
` The "session.handler" service has not been created, make sure you have created the "session" service first.`

Bug 2:
The `Delete users` in yellow appears AFTER you have entered a username when it should be the first thing shown after typing the command like it is when you add a user. 

Full context, first adding, then deleting a user:

<img width="1145" alt="Screenshot 2021-04-02 at 16 34 23" src="https://user-images.githubusercontent.com/400092/113429996-4c26ef00-93d1-11eb-88c2-315dd488b461.png">

### System information (as much as possible)

`4.0-dev`

**Comment by PhilETaylor** [comment]
Note that the user **IS DELETED** despite the error message

**Comment by richard67** [comment]
Possibly bug 1 comes from the merged PR #29007 , i.e. the CLI needs to be adjusted to that.

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/33145

**Comment by richard67** [comment]
Closing as having a pull request.

**Comment by PhilETaylor** [comment]
Please reopen for someone else to attempt now that this PR was/is reverted.

**Comment by richard67** [comment]
Re-open as stated in previous comment.
