### ISSUE TITLE
[4][cli] conflicting messages with extension:discoverinstall

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32967]
### Steps to reproduce the issue

php cli/joomla.php extension:discoverinstall

### Expected result

a single message saying that there were no extensions discovered.

### Actual result

Two messages, one is a yellow warning and one is an OK.

<img width="870" alt="Screenshot 2021-04-02 at 16 37 17" src="https://user-images.githubusercontent.com/400092/113430230-b3dd3a00-93d1-11eb-9dd8-5c8710cde533.png">

### System information (as much as possible)

`4.0-dev`

**Comment by PhilETaylor** [comment]
Unlike the web interface this command doesn't "discover" and return a list - it just blindly installs anything it finds which is bad as the expectation is that it would be like the web interface. 

Possibly consider breaking this up into two commands, one for discovering and one for installing, maybe even with a `--installall` param on the discover command to blindly install all it finds.

Thus thoughts

**Comment by brianteeman** [comment]
> Unlike the web interface this command doesn't "discover" and return a list - it just blindly installs anything it finds which is bad as the expectation is that it would be like the web interface.

I thought we had this discussion before?

**Comment by PhilETaylor** [comment]
nothing found https://github.com/joomla/joomla-cms/issues?q=is%3Aissue+CLI+author%3APhilETaylor+is%3Aclosed but I would not be surprised.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/31524#issuecomment-735441632

**Comment by PhilETaylor** [comment]
> Does this find the extensions or does it install them?

Well that's the point. It does both, blindly installing anything it finds. My point is that is not really what we (Joomla) should be looking to do and that the command should be broken up or improved,

**Comment by astridx** [comment]
If you want to install an extension specifically, then you can give the id. Then only this one will be installed.

**Comment by brianteeman** [comment]
but how do you find out which ones are available?

**Comment by PhilETaylor** [comment]
Its still a totally different expectation to the admin console. 

There should be a 

"Discover" = "List of discovered extensions"
"install All" = "installs all discovered extensions"
"install a single extension" = "installs a single discovered extension"

At the moment the default is just to discover and install all. I say that's the wrong expectation. Just running the command should give a LIST of discovered extensions, else where am I to get the ID from to install... 

But all this is all mute anyway, because it doesn't EVEN WORK - it doesn't discover anything at the CLI !!! 

<img width="897" alt="Screenshot 2021-04-02 at 19 21 28" src="https://user-images.githubusercontent.com/400092/113442810-a2ebf300-93e8-11eb-8f96-d8bc58e371a8.png">

<img width="1064" alt="Screenshot 2021-04-02 at 19 21 38" src="https://user-images.githubusercontent.com/400092/113442833-aaab9780-93e8-11eb-8bbd-cedab073b270.png">

**Comment by laoneo** [comment]
[Here](https://github.com/Digital-Peak/DPDocker/blob/b4eafb116f7dd2ffa7f8d005885e6158d80e15d8/webserver/scripts/discoverapp.php#L23-L51) you can see what I had to do to find, discover and install the extensions before I setup Joomla in DPDocker. Perhaps it helps.

**Comment by alikon** [comment]
please test #33749
