### ISSUE TITLE
[4.0] Article: "Associations" on hover hard to read

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#32978]
### What needs to be fixed
In an multilanguage Article hover on an also available Language:

![Bildschirmfoto 2021-04-03 um 09 59 50](https://user-images.githubusercontent.com/78906980/113472570-8b525000-9464-11eb-9a58-4ccee4cb0159.png)

### Why this should be fixed
Hard to read

### How would you fix it
More Difference between Letters and Background.

### Side Effects expected
Don't know.

### System Information
![grafik](https://user-images.githubusercontent.com/78906980/113473015-2fd59180-9467-11eb-9b6f-9be2f8fcc014.png)

**Comment by infograf768** [comment]
Confirmed. So used to use flags I guess nobody tested using lang code there.

**Comment by infograf768** [comment]
First aspect to change is to get this
<img width="460" alt="Screen Shot 2021-04-03 at 11 53 58" src="https://user-images.githubusercontent.com/869724/113474973-4e418a00-9473-11eb-93eb-b253097fe9f0.png">


This to let choose when we have languages for different countries: de-DE, de-AT, etc. and correct useless whitespace between badges.

Code would be
```
<dd class="association">
	<span class="icon-globe icon-fw" aria-hidden="true"></span>
	<?php echo Text::_('JASSOCIATIONS'); ?>
	<?php foreach ($associations as $association) : ?>
		<?php if ($displayData['item']->params->get('flags', 1) && $association['language']->image) : ?>
			<?php $flag = HTMLHelper::_('image', 'mod_languages/' . $association['language']->image . '.gif', $association['language']->title_native, array('title' => $association['language']->title_native), true); ?>
			<a href="<?php echo Route::_($association['item']); ?>"><?php echo $flag; ?></a>
		<?php else : ?>
			<?php $class = 'badge bg-secondary badge-' . strtolower($association['language']->lang_code); ?>
			<a class="<?php echo $class; ?>" title="<?php echo $association['language']->title_native; ?>" href="<?php echo Route::_($association['item']); ?>"><?php echo $association['language']->lang_code; ?></a>
		<?php endif; ?>
	<?php endforeach; ?>
</dd>
<?php endif; ?>
```

then we have an issue with the hover colour. Remark that in backend managers we have no hover.
Looking at it now.

**Comment by infograf768** [comment]
What do you think about this?

![assoc_front](https://user-images.githubusercontent.com/869724/113484254-a0040780-94a7-11eb-88e2-fd83fecd6b1b.gif)

EDIT: same modifications for list category

![assoc_front-list](https://user-images.githubusercontent.com/869724/113484682-e35f7580-94a9-11eb-9204-8bbf74e1cfc1.gif)

**Comment by brianteeman** [comment]
remark that there is no "on-hover" when it is flags

**Comment by ghost** [comment]
> What do you think about this?

Looks fine for me.

**Comment by brianteeman** [comment]
According to the bootstrap 5 documentation badges should no longer have focus or hover styles for links. https://getbootstrap.com/docs/5.0/components/badge/

**Comment by infograf768** [comment]
the PR (to come) will change badges to buttons.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/32992 closing
