### ISSUE TITLE
Smart Search will sometimes return a Blank Page when the Joomla Cache is used

### ISSUE THREAD

**Issue by JimHolloman** [joomla/joomla-cms#32976]
### Steps to reproduce the issue
Go to:
https://savannahgavisitors.com/

Enter "segway" into the Search Box.
### Expected result
Returns 5 Results as expected (AOK)

Then, enter "Segway" into the Search Box.
### Actual result
Returns a BLANK PAGE (BUG!)

### System information (as much as possible)
Joomla 3.9.25 and PHP 7.4.
Has occurred on two different sites.

### Additional comments
Smart Search will sometimes return a Blank Page if Joomla Caching is turned ON.
Has occurred on 2 different sites.
Correct results has always been seen when Joomla Caching is turned OFF.
In the above example, if Joomla Caching is turned OFF, then "Segway" will return 5 results as expected -- the same as "segway".
It appears that Joomla caching is causing the Smart Search to return a Blank Page on rare occasions.
No Caching extensions is being used.

Cache Settings:
Cache Handler: File
Path to Cache Folder: [NOT SPECIFIED, USING DEFAULT]
Cache Time: 15 Minutes
Platform Specific Caching: NO
System Cache: ON - Conservative caching

Bug confirmed 2 April, 2021 at 8:30pm EST USA (GMT - 5).

A copy of the website can be provided if needed (about 40 MB ,jpa file).

**Comment by PhilETaylor** [comment]
A blank page is an error page. In Joomla Global Configuration, turn on Debuging and set Error Reporting to maximum and repeat your test and report the PHP error back here please.

**Comment by JimHolloman** [comment]
Debug Mode does not produce an error.

PHPInfo.php shows memory_limit  768M for both local value and master value.

The Screaming Frog program will often show 1-5 500 errors, but sometimes no 500 errors.

**Comment by PhilETaylor** [comment]
Did you " set Error Reporting to maximum" in Joomla Global Config? or did you just enable Debug mode?

Screaming Frog ? The SEO Audit tool? that would be totally unrelated.

**Comment by JimHolloman** [comment]
1) I spent about an hour on the phone today (Tues) with Brandon at InMotion. 

2) He said that there is no caching layer for Joomla -- only for WordPress. However, I am not confident that such a statement if valid. How would the caching software be able to differentiate?

3) We increased the PHP Memory to 512M -- no success.

4) Bandon was seeing the same issues at his location. I am seeing the issues on 3 different desktop computers at my location; with both Firefox and Chrome.

5) The issue is very intermittent. About 15-20 percent of the time the correct results is returned.

6) On my Firefox Browser I am getting Blank Pages. My Chrome Browser is showing '500' Errors instead. Occasionally, both browsers will show the correct results.

7) Brandon repeatedly said that the problem must be with Joomla. But, the problem does not appear with WampServer nor with GoDaddy (thus far). And, it did not appear in the past with InMotion.

8) I switched to PHP Ver. 7.2 (old version) for Charleston, and tested. No success. And, yep, I did clear both the Joomla and FF Cache before testing.

9) Charleston (charlestonscvisitors.com) is failing more consistently than Asheville (ashevillencvisitors.com).

10) There is no example of a PHP Error being raised with Debug turned ON. The results has always been either a Blank Page or a 500 Error.

11) I currently have Joomla Caching turned ON for both Asheville and Charleston.

12) If it would help for you to have admin access to one of the sites, let me know and I will provide it. Charleston might be the better choice.

13) This is going to be a very tough problem to resolve.

**Comment by JimHolloman** [comment]
> Did you " set Error Reporting to maximum" in Joomla Global Config? 

I did " set Error Reporting to maximum". And, I tried Debug Mode again today with the same results.

**Comment by JimHolloman** [comment]
> My words "If it would help for you to have admin access to one of the sites, let me know and I will provide it."

I can also provide a .jpa copy of a site sans the images that would not be needed.

**Comment by JimHolloman** [comment]
A week ago on the Savannah site (savannahgavisitors.com), the term "segway" would consistently return 5 Results and the term "Segway" would consistently fail. 

I tried a few minutes ago and both terms consistently fail on Firefox (Blank Pages).

On Chrome, 'segway" returned 5 Results on first attempt.
Refresh -- Success.
Clear the cache on Chrome.
Refresh -- Success.
--------
Try "Segway".
HTTP ERRPR 500 returned.
Reload
HTTP ERRPR 500 returned.
--------
Back Button to previous Page.
Enter: XXXXXX
No returns Found
--------
Enter: Segway
HTTP ERRPR 500 returned.
--------

###

**Comment by brianteeman** [comment]
The forum really is the best place for help on this. If I was to **guess** then I would suggest that the index for finder is corrupt and you should rebuild it.

**Comment by PhilETaylor** [comment]
> This is going to be a very tough problem to resolve.

With the right experience, no probably not, but this is not the place for support or consultancy sorry. 

A blank page is an error page. But you have disabled error_reporting and display_errors so the error is not output to the screen. Simple. There are ways to debug that so that the error is shown.

A decent webhost would be providing a PHP Error Log file as well (error_log) 

A decent webhost would know how to debug PHP errors. hint: Its rare to find a decent webhost, most only have skills to ensure a server is online, and collect their recurring passive income. 

> Brandon repeatedly said that the problem must be with Joomla. 

Webhosts love to pass the buck. The problem is likely to be with Joomla, but because the server is configured a certain way. 

>  both terms consistently fail on Firefox (Blank Pages).

This will not be browser dependant, PHP runs on the server and its a PHP error not a frontend browser related problem

**Comment by brianteeman** [comment]
>>This is going to be a very tough problem to resolve.

>With the right experience, no probably not, but this is not the place for support or consultancy sorry.

💯 Couldnt agree more

**Comment by JimHolloman** [comment]
A week ago on the Savannah site (savannahgavisitors.com), the term "segway" would consistently return 5 Results and the term "Segway" would consistently fail. 

I tried a few minutes ago and both terms consistently fail on Firefox (Blank Pages).

On Chrome, 'segway" returned 5 Results on first attempt.
Refresh -- Success.
Clear the cache on Chrome.
Refresh -- Success.
--------
Try "Segway".
HTTP ERRPR 500 returned.
Reload
HTTP ERRPR 500 returned.
--------
Back Button to previous Page.
Enter: XXXXXX
No returns Found
--------
Enter: Segway
HTTP ERRPR 500 returned.
--------

###

> 
> 
> The forum really is the best place for help on this. If I was to **guess** then I would suggest that the index for finder is corrupt and you should rebuild it.

It has been rebuilt many times.

**Comment by JimHolloman** [comment]
> A blank page is an error page. But you have disabled error_reporting and display_errors so the error is not output to the screen. Simple. There are ways to debug that so that the error is shown.

Can you tell me how to enable them? 

I certainly did not intentionally disable them. And, I set the parameters in the Global Configuration as you instructed.

> A decent webhost would be providing a PHP Error Log file as well (error_log)

I will check with InMotion. Do you know of any decent webhosts for Joomla? It appears that it is time to change hosts again!

**Comment by ReLater** [comment]
> I set the parameters in the Global Configuration as you instructed.

Joomla fires a
```
error_reporting(E_ALL);
ini_set('display_errors', 1);
```
then. But the webhost can forbid these changes in PHP. Ask them. And also ask them for the PHP error_log file; how to activate it, where to find it.

**Comment by JimHolloman** [comment]
> 
> 
> > I set the parameters in the Global Configuration as you instructed.
> 
> Joomla fires a
> 
> ```
> error_reporting(E_ALL);
> ini_set('display_errors', 1);
> ```
> 
> then. But the webhost can forbid these changes in PHP. Ask them. And also ask them for the PHP error_log file; how to activate it, where to find it.

Many thanks, ReLater, for the useful information.

The last word from InMotion is that the latest versions of Joomla are not compatible with the Apache software on the server -- that is set up to support WordPress. 

This makes the 3rd time I have encountered this brick wall. The previous one was with HostGator -- and that was only 13 months ago. Does anyone else recognize this as a legitimate Joomla issue? Perhaps one eye should remain open -- so as to see see what is happening to Joomla on the homefront.

Joomla’s decline illustrated in one chart. By Steven Zeegers on Mar., 29, 2021
https://joomla-and-more.com/2021/03/29/joomlas-decline-illustrated-in-one-chart/

**Comment by JimHolloman** [comment]
> 
> 
> > > This is going to be a very tough problem to resolve.
> 
> > With the right experience, no probably not, but this is not the place for support or consultancy sorry.
> 
> 100 Couldnt agree more

Then why are you making a useless post? A display of arrogrance, and high-mindness, is never pretty.

You could have said something useful like, "I would recommended that you try the Joomla forum with this issue."

Okay, now you can go ahead and ban me from the ____ (whatever this is).

**Comment by PhilETaylor** [comment]
> The last word from InMotion is that the latest versions of Joomla are not compatible with the Apache software on the server -- that is set up to support WordPress.

Ive said it before and I'll say it again. Webhosts lie to cover their incompetence. 

Joomla is compatible with Apache. All modern versions. 

What this really says is your webhost has crippled Apache to suit their own aims and in the process has created issues. 

> Does anyone else recognize this as a legitimate Joomla issue?

No. Not unless you can product an error message. If you want me to produce the error message to prove its your webhost then email me at phil@phil-taylor.com.

**Comment by brianteeman** [comment]
>  The last word from InMotion is that the latest versions of Joomla are not compatible with the Apache software on the server -- that is set up to support WordPress.

I find that very hard to believe

**Comment by JimHolloman** [comment]
> 
> 
> > The last word from InMotion is that the latest versions of Joomla are not compatible with the Apache software on the server -- that is set up to support WordPress.
> 
> Ive said it before and I'll say it again. Webhosts lie to cover their incompetence.
> 
> Joomla is compatible with Apache. All modern versions.
> 
> What this really says is your webhost has crippled Apache to suit their own aims and in the process has created issues.
> 
> > Does anyone else recognize this as a legitimate Joomla issue?
> 
> No. Not unless you can produce an error message. If you want me to produce the error message to prove its your webhost then email me at [phil@phil-taylor.com](mailto:phil@phil-taylor.com).

I understand your points -- and I appreciate the offer.

> What this really says is your webhost has crippled Apache to suit their own aims...

Seems reasonable to me; especially if you change "crippled" to "tweaked".

At this point, error messages are of no significance. By its own assertion, InMotion does not currently support the latest versions of Joomla. I have to accept that as a totality. The support person, Sean Mu, suggested that I revert to an earlier version of Joomla and give it a try.

Sean did create a Ticket and said he would escalate the issue. I asked him to inquire as to the feasibility of separating Joomla and Wordpress onto separate servers -- and not have both on a shared server. Being one that has been 'burnt' by applying updates that were not needed, I can appreciate the reluctance of any hosting company to mess with (change, update, modify, tweak, etc.) a server to satisfy a small percentage of its customer base. If 98 percent of the accounts on a server are sailing along smoothy, then why risk doing something that could cause problems to accommodate the other 2 percent. Makes sense to me. Continuous change is an open door to unexpected problems. And, that is the state that we are currently in with software; continuous change.

**Comment by JimHolloman** [comment]
> 
> 
> > The last word from InMotion is that the latest versions of Joomla are not compatible with the Apache software on the server -- that is set up to support WordPress.
> 
> I find that very hard to believe

It may not be believable. It may be a big, black, lie. But, does that matter?

Once a hosting company makes the decision not to support Joomla, software compatibilities become mute.

Here are two facts:

1) It is no fun moving to a different hosting company every year. And, yes, that tell me that they support Joomla before I create an account.

2) People using WordPress apparently do not encounter this particular problem -- of being told to "get lost -- we don't want you". I have needed very little support. Therefore, I have not been a drain on their personnel.

**Comment by brianteeman** [comment]
The most likely scenario regarding the inability to enable php display of errors is that the hosting company has disabled it as wp users complained abut the number of errors being displayed on their sites. So its not that the host doesnt support joomla or that they have optimised it for wp. I doubt anyone who made the decision to disable php debug display even considered any impact it would have on any other software. So its ignorance (and stupidity) that lead them to do that and not a conscious decision not to support a platform. In fact I bet that if the senior people were aware then they would not have approved the change. Most hosts when they say "we dont support x" mean "we dont provide tech support on using x"

**Comment by PhilETaylor** [comment]
I offered to take a personal look to obtain the real issue here, but no one has contacted me.

**Comment by JimHolloman** [comment]
> 
> 
> I offered to take a personal look to obtain the real issue here, but no one has contacted me.

Did someone need to contact you?

Here is my feedback to InMotion Hosting via the cPanel:
http://jlhpgms.com/inmotion.txt

Thanks for the help.

**Comment by JimHolloman** [comment]
> The most likely scenario...

> So its ignorance (and stupidity)...

Or, perhaps just a lack of knowledge and experience; words that are less harsh than 'ignorant' and 'stupid'. Being uniformed does not make one 'stupid'.

Here is my feedback, and attempt to reach the 'senior people' at InMotion Hosting. It was submitted via the cPanel:  http://jlhpgms.com/inmotion.txt

The thing that is most concerning is the pattern. If more and more hosts decide not to support Joomla on shared servers, it does not bode well for Joomla's future.

I have a very small business site (https://mikesonmain.com/) on Joomla 3.9.23 running on the InMotion shared server and I have not been able to cause a failure with the Smart Search. So, I am of the current opinion that something likely changed in the code for Smart Search between Ver. 3.9.23 and Ver. 3.9.25 of Joomla that gave rise to the incompatibility. I do not suspect that anything was 'crippled' on the server to cause any issues with Joomla. 

When I have time I might compare the Smart Search code in 3.9.23 and 3.9.25 and see if I can identify a relevant change.

Thanks for the help.

**Comment by brianteeman** [comment]
As suspected - inmotion have disabled by default all php error reporting
https://www.inmotionhosting.com/support/website/troubleshoot-php-errors/

**Comment by PhilETaylor** [comment]
> Did someone need to contact you?

[The offer was there](https://github.com/joomla/joomla-cms/issues/32976#issuecomment-815306221). I would have asked you to complete the secure form at fix.mySites.guru and I would have debugged the issue for FREE to get the actual error message. Then if it 

1) Were a real Joomla issue - we would know what to fix, would have a stack trace and something to actually base work on

2) Were a web hosting issue - I could document it, and tell you what to tell your webhost.

3) Were an indexing issue/caching issue/other issue - give you advice. 

It seems that you are more happy slagging off Joomla and defending your webhost than actually getting to the bottom of your "issue". 

> I have a very small business site (https://mikesonmain.com/) on Joomla 3.9.23

So by your own admission you are running a version of Joomla two versions out of date with well known security vulnerabilities fixed in later versions. 

>  I am of the current opinion that something likely changed in the code for Smart Search between Ver. 3.9.23 and Ver. 3.9.25

Nothing has changed of importance. Your opinion is not backed by fact. 

 - /components/com_search for 15 months - see https://github.com/joomla/joomla-cms/tree/staging/components/com_search
 - /administrator/components/com_search for 5 months see https://github.com/joomla/joomla-cms/tree/staging/administrator/components/com_search and that change was limiting offsets https://github.com/joomla/joomla-cms/pull/31444
 - /plugins/finder for 10 months, and that was just doc block changes 
 - /administrator/components/com_finder - 12 days ago, and then 3 months ago, but again nothing major changed https://github.com/joomla/joomla-cms/tree/staging/administrator/components/com_finder

**Comment by JimHolloman** [comment]
> As suspected - inmotion have disabled by default all php error reporting
> https://www.inmotionhosting.com/support/website/troubleshoot-php-errors/

Many thanks for the link. I tried turning ON PHP Error Logging and Error Display via the php.ini parameters yesterday without success. I did noticed that PHP error_logging was not enabled.

I will try again following the steps in the article. It would be good to determine the cause of this incompatibility.  I have to wonder:

1) Could a change to the Joomla code be made that would avoid this compatibility issue. I believe I saw on one of the official Joomla sites that changes were made for PHP 8 improvements in Version 3.9.25. Yet, we are not using PHP 8 (using PHP 7.4).
2) Is it likely that this issue will also appear on other shared servers (other than InMotion). As you know, nearly all of the shared hosting companies are focused on WordPress and therefore optimize their servers for WordPress; including server layer caching. While beneficial to WordPress, server layer caching may cause a conflict with Joomla caching. IMHO, there is a too much difference between the needs (requirements) of WordPress and Joomla to intermingle them on the same shared server. IMO, it is asking for trouble. And, if and when trouble occurs, Joomla will be viewed in the same manner as Kudzu; like an unwanted intruder.

**Comment by PhilETaylor** [comment]
> Could a change to the Joomla code be made that would avoid this compatibility issue.

Well first we need to establish the ROOT CAUSE - you assume its a "compatibility issue" but this has not been proved yet. 

> Is it likely that this issue will also appear on other shared servers (other than InMotion)

Again that depends on the ROOT CAUSE. 

> server layer caching may cause a conflict with Joomla caching

No. 

> there is a too much difference between the needs (requirements) of WordPress and Joomla to intermingle them

Again you are wrong. I, and many other hosting companies, successfully have WordPress and Joomla sites, running blazingly fast, on the same infrastructure.

**Comment by PhilETaylor** [comment]
Also - your webhost has `mod_security` enabled with a ruleset that blocks and filters input and output.

For example, a CURL request to your site returns with a `406 - Not Acceptable` page... meaning your webhost is blocking the request in `mod_security` with their selection of rules. 

```
curl https://savannahgavisitors.com/component/finder/search\?q\=segway\&Itemid\=101

<html><head><title>Error 406 - Not Acceptable</title><head><body><h1>Error 406 - Not Acceptable</h1><p>Generally a 406 error is caused because a request has been blocked by Mod Security. If you believe that your request has been blocked by mistake please contact the web site owner.</p></body></html>%
```

**Comment by JimHolloman** [comment]
> [The offer was there](https://github.com/joomla/joomla-cms/issues/32976#issuecomment-815306221). 

I did respond to one of the Emails:

From: Phil E. Taylor <notificastins@gethub.com>

And, offered to provide you with access to the backend as well as a .jpa copy of the website. I don't know if it reached you or not.

> ...and defending your webhost than actually getting to the bottom of your "issue".

Very interested in getting to the bottom of the issue. I have no interest in either blaming the webhost (InMotion) nor defending the webhost. But, I do like to give the "benefit of any doubt" to everyone.

> Yet you state that your webhost tells you they have modified Apache in a way that now doesn't support Joomla.

I don't recall making such a statement. InMotion's position is that a change in the recent versions of Joomla is responsible for the issue.

> So by your own admission you are running a version of Joomla two versions out of date...

True -- on 2 very small websites. And, with several backup copies. I don't see any connection with the Smart Search problem. The websites with the Smart Search problem are using Joomla 3.9.25. In contrast, the 2 sites running Joomla 3.9.23 seem to be doing fine. 

> Also - your webhost has mod_security enabled with a ruleset that blocks and filters input and output.

This is "over my head".  I don't know what the connection is between mod_security and Smart Search? And, I have never used curl. I am not as knowledgeable as people like yourself -- and many others.

**Comment by PhilETaylor** [comment]
> From: Phil E. Taylor notificastins@gethub.com

There are two spelling mistakes in that email alone. 

Please send me your complete site details, including FTP, using the form at https://fix.mySites.guru/now and I'll take a look for free! Im now interested to reveal the truth about this. 

A JPA will be no good. I need to see the site "in-situ" on its hosting, the hosting that in conjunction with the site creates "the issue".

**Comment by JimHolloman** [comment]
> > From: Phil E. Taylor [notificastins@gethub.com](mailto:notificastins@gethub.com)
> 
> There are two spelling mistakes in that email alone.
> 
> Please send me your complete site details, including FTP, using the form at https://fix.mySites.guru/now and I'll take a look for free! Im now interested to reveal the truth about this.
> 
> A JPA will be no good. I need to see the site "in-situ" on its hosting, the hosting that in conjunction with the site creates "the issue".

Thank you. Will do late tonight or tomorrow.

>  Im now interested to reveal the truth about this.

 GOOD!

**Comment by PhilETaylor** [comment]
So I have taken a look at your (rather messy) webspace and hosting.

I could see that com_finder was generating Zero byte cache files, which would be reused causing a blank screen with a 200 response. This is strange. 

I have removed ALL CUSTOM php.ini, .user.ini and PHP modifications in .htaccess.

I then used cPanel to correctly upgrade your PHP version to 8.0.3 and set what sane defaults I would use in PHP configuration.

```ini
allow_url_fopen = On
display_errors = Off
enable_dl = Off
file_uploads = On
max_execution_time = 30
max_input_time = 60
max_input_vars = 1000
memory_limit = 124M
post_max_size = 124M
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php80"
upload_max_filesize = 124M
zlib.output_compression = Off
```

Since then I was unable to replicate this blank page issue. Every test I conducted after cleaning up your php settings, and upgrading PHP, and setting sane defaults for PHP configuration, resulted in a successful search of the term "Segway" and I never got a single blank page after me work.

**Comment by JimHolloman** [comment]
> So I have taken a look at your (rather messy) webspace and hosting.
> 
> I could see that com_finder was generating Zero byte cache files, which would be reused causing a blank screen with a 200 response. This is strange.
-------- Remainder clipped by Jim Holloman  --------

Phil,

You are amazing. I am astonished that you had the issue resolved so quickly.

It is wonderful to see the Smart Search working again.

I subscribed to the management of one site and want to replace Charleston with Savannah. I sent you a PM via the Contact Form. Your management site is great! But, there is no rush. Charleston is dead -- while Savannah might still have some potential.

Many thanks for the help -- and the resolution,

Jim Holloman

**Comment by PhilETaylor** [comment]
I just love the lies web hosts give to cover their incompetence. 

> The last word from InMotion is that the latest versions of Joomla are not compatible with the Apache software on the server -- that is set up to support WordPress.

LMAO. I have proved this to be factually incorrect now.
