### ISSUE TITLE
[4.0] Search: Style for Dropdown-Fields "Start Date" and "End Date" missing

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#32982]
### What needs to be fixed
At Page "Search" of an default Installation the Dropdown-Fields "Start Date" and "End Date" looks like a Style is missing:

![Ohne Titel](https://user-images.githubusercontent.com/78906980/113477711-0f680000-9484-11eb-9655-d5edc6888ae4.png)

### Why this should be fixed
Should'nt these Dropdown-Fields "Start Date" and "End Date" look like other Dropdown-Fields like "Search by Type"?

### How would you fix it
Apply same class like Dropdown-Fields "Search by Type".

### Side Effects expected
i don't know

### System Information
![113473015-2fd59180-9467-11eb-9b6f-9be2f8fcc014](https://user-images.githubusercontent.com/78906980/113477675-c2842980-9483-11eb-819e-ed002b269d13.png)

**Comment by brianteeman** [comment]
confirmed

**Comment by brianteeman** [comment]
This is _partially_ solved by adding the correct class `form-select` to the select found in `administrator\components\com_finder\src\Service\HTML\Filter.php` but it looks to me that this markup should not be present in that file at all anyway. By locating the markup there it means it cannot be overridden and therefore the markup will always be bootstrap specific which is not the intention.

**Comment by ghost** [comment]
Thanks @rjharishabh for the pull request #33220, closing this issue.

**Comment by ghost** [comment]
@rjharishabh do you have a comment on https://github.com/joomla/joomla-cms/issues/32982#issuecomment-812880799 by @brianteeman about markup and overridden so this don't get lost?
