### ISSUE TITLE
[4B7] user loose user groups after password reset via frontend

### ISSUE THREAD

**Issue by joni142** [joomla/joomla-cms#32981]
### Steps to reproduce the issue
If a user attempt to use the "forgot password" function at the frontend, the assigned user groups are lost.
Only the public group is active.

Normally the user groups should not be changed by an usage of the "forgot password" function.

**Comment by brianteeman** [comment]
Can not confirm

**Comment by JereSten** [comment]
Yes i have the same issue.
After resetting the password all user group assignments are gone. Very annoying... i have to reassign all the users to the groups every time they reset their passwords.
I also noticed that the joomla log displays that a new user is being registered instead of a password reset. Maybe Joomla tries to register the existing user once more when the forgot-password function is used? Accordingly all user groups are overwritten.

PS: I have no extensions installed

**Comment by brianteeman** [comment]
If this was happening with just core user management then there would be thousands of reports. What extensions do you have installed - especially any plugins or components to manage login.

**Comment by joni142** [comment]
No extensions are installed.
Tried it with a fresh joomla installation too, same problem.
After using the "forgot password" function the user group assignments are changed.

pictures from a fresh joomla installation
before:
![image](https://user-images.githubusercontent.com/34376674/113479204-f8c6a680-948d-11eb-9159-114a8618ee04.png)

after:
![image](https://user-images.githubusercontent.com/34376674/113479213-0714c280-948e-11eb-89c1-4b56a910cc3e.png)

**Comment by brianteeman** [comment]
I see that you now have updated the title to indicate that this report is for joomla 4. I had assumed from the way that you wrote that you were referring to a live site and therefor a joomla 3 site

**Comment by brianteeman** [comment]
I have done a few tests. In each test there has been a change in the assigned user groups although not consistently the same groups. 

### Before
![image](https://user-images.githubusercontent.com/1296369/113483597-33cfd680-949c-11eb-8a12-dc3d2cec8c57.png)

### After
![image](https://user-images.githubusercontent.com/1296369/113483626-582bb300-949c-11eb-9693-28bc9eecc760.png)

![image](https://user-images.githubusercontent.com/1296369/113483656-7a253580-949c-11eb-9947-affb30691e9a.png)


In addition as can be seen in the screenshots the user account is no longer marked as active.

Both of these are very serious issues so thank you for reporting them and I apologise again for misunderstanding that you were referring to joomla 3.

@richard67 please upgrade this to a release blocker

@joomla/security please review this as its a clear security issue

**Comment by joomdonation** [comment]
I can confirm the issue. Just tried and see the same error. I will look at it.

**Comment by brianteeman** [comment]
@joomdonation I double checked it a few times on J3 and no problem with the groups there

**Comment by joomdonation** [comment]
I only check on J4 as the reported issue is for J4.

**Comment by joomdonation** [comment]
So here is what I found:

1. A quick fix would be change this line of code https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Table/User.php#L173 to

```php
->whereIn($this->_db->quoteName('id'), array_values($this->groups));
```

2. However, the root of the error seems causes from our database package DatabaseQuery class, method bindArray. I will try to make a PR to framework repo to fix this root error.

**Comment by PhilETaylor** [comment]
This should be a release blocker surely right?

**Comment by PhilETaylor** [comment]
This looks like a PHP 8 issue. Please report your PHP versions.

**Comment by joni142** [comment]
My PHP version is 7.4.14

**Comment by PhilETaylor** [comment]
ok cool maybe I was wrong then, well the [proposed fix](https://github.com/joomla-framework/database/pull/247) of using `array_values()` has been the fix for a lot of PHP 8 compatibility issues.

**Comment by brianteeman** [comment]
not php 8

**Comment by PhilETaylor** [comment]
PR #32990

**Comment by PhilETaylor** [comment]
#32990 was merged, please remove the release blocker tag on this issue.
