### ISSUE TITLE
Turning off System Cache does no turn off Caching

### ISSUE THREAD

**Issue by JimHolloman** [joomla/joomla-cms#32989]
Edit: In the Title, "no turn off" --> "not turn off". 

### Steps to reproduce the issue

Go to: System --> Global Configuration --> System (Tab) --> System Cache under Cache Settings

And set System Cache to OFF.

### Expected result
Caching to be disabled.

### Actual result
The 'Page' continues to be cached; requiring the cache to be manually cleared between every change to the content in order to view the results.

Go To: Extensions --> Manage --> Manage 
Both Cache and "System - Page Cache" are both 'Protected' and cannot be disabled.

Update: Per brianteeman, 3 April, 2021 : 
Disable 'System - Cache' in Plugins. 
A tip worth knowing until the Configuration Option to turn OFF caching is fully functional and will disable Page caching.

### System information (as much as possible)
Joomla 3.9.25 with PHP 7.4

### Additional comments
My weird experience:

On Desktop Computer #1, I rearranged the order of the Main Menu items. Had to clear the cache and repeat the process three times before the change finally took effect on the frontend (yes, I cleared the Firefox browser each time).

I then went to Desktop Computer #2, cleared the Firefox cache, and loaded the website. There was no update -- the menu items were still in the previous order. Went into the backend of the website on Computer #2 and the order of the menu items were correct. Closed the backend, cleared Firefox cache, and loaded the website again (frontend). The menu items were then correct. I do not understand this behavior. Is it perhaps some caching functionality at the remote server?

**Comment by PhilETaylor** [comment]
Are you hosting on Siteground?

Did you previously have caching enabled, then disabled it when you were making changes, and when you disabled caching in Joomla Global Configuration, did you then go and CLEAR the ALREADY cached items in the com_cache? Even with Joomla Global Configuration caching =off, if there are cache files already built they will be used. Ive reported this before and was told it was by design.

**Comment by brianteeman** [comment]
> Both Cache and "System - Page Cache" are both 'Protected' and cannot be disabled.

You can do from Extensions> Plugins

> I do not understand this behavior. Is it perhaps some caching functionality at the remote server?

As Phil said that can be the case. Siteground for example have their own caching layer on their servers

**Comment by JimHolloman** [comment]
> 
> 
> Are you hosting on Siteground?
> 
> Did you previously have caching enabled, then disabled it when you were making changes, and when you disabled caching in Joomla Global Configuration, did you then go and CLEAR the ALREADY cached items in the com_cache? Even with Joomla Global Configuration caching =off, if there are cache files already built they will be used. Ive reported this before and was told it was by design.

Are you hosting on Siteground? No. I am using InMotion Hosting.

Did you previously have caching enabled (YES), 
then disabled it when you were making changes (YES), 
and when you disabled caching in Joomla Global Configuration, 
did you then go and CLEAR the ALREADY cached items in the com_cache? (YES)

Even with Joomla Global Configuration caching = OFF, if there are cache files 
already built they will be used. Ive reported this before and was told it was 
by design (NOT SURPRISED).

While it would be good to have the current items in the System Cache purged when you turn OFF caching, it is not surprising to me that two separate steps are required. For one thing, it could take several seconds to clear a large cache. That might seem awkard on the Configuration Page when all you are trying to do is set a switch -- unless a Pop-Up would advise that the cache is being cleared. Then, the clearing function would need to advise the Configuration Screen when the clearing has been completed so that the Pop-Up would close. That is a good bit of work and code to avoid one step.

**Comment by JimHolloman** [comment]
> You can do from Extensions> Plugins

Thanks brianteeman.

**Comment by PhilETaylor** [comment]
Inmotion hosting are getting as bad as SiteGround in my experience. :-) 

Ask your webhost what caching layers they are using on your account. 

https://www.inmotionhosting.com/support/edu/wordpress/nginx-cache-management/
https://www.inmotionhosting.com/support/edu/cpanel/cache-manager-cpanel/

**Comment by brianteeman** [comment]
I am guessing this can also be closed now that @PhilETaylor fixed the inmotion hosting

**Comment by JimHolloman** [comment]
> I am guessing this can also be closed now that @PhilETaylor fixed the inmotion hosting

While they are both related to caching, the two issues are completely independent.

1) The InMotion issue involved com_finder creating an empty cache that would result in a White Page being returned -- but no errors -- and therefore no indication of any problem.

2) This issue involves the fact that the "page" continues to be cached after Caching is turned OFF in Global Config. It is my contention that System --> System Tab --> System Cache being set to "OFF - Caching disabled" should inhibit the "page" from being cached. 

Since it doesn't, steps to clear the cache to check the results of changes to the content are required; greatly slowing down the updating process. Otherwise, the Page, even when refreshed in the browser, continues to show the previous state (as pulled from the cached page) -- and not the updated content.

At some point in the past, turning off caching in Global Config did inhibit the caching of "page".

**Comment by PhilETaylor** [comment]
> This issue involves the fact that the "page" continues to be cached after Caching is turned OFF in Global Config. It is my contention that System --> System Tab --> System Cache being set to "OFF - Caching disabled" should inhibit the "page" from being cached.

If there is already a Joomla cache (files in /cache) when you disable Joomla Global configuration, it is my understanding they can still be used until you actually purge them, regardless of the setting you disabled in Joomla Global Config. This is by design if I remember correctly. 

I have tested both your domains that I know about today and they both have the header:

`Expires: Wed, 17 Aug 2005 00:00:00 GMT` 

which probably means Joomla cache is not enabled, and no server cache is enabled. This expires header would also stop your browser caching.

Do you have a site that you can - every time - replicate this issue?

**Comment by JimHolloman** [comment]
> If there is already a Joomla cache (files in /cache) when you disable Joomla Global configuration, it is my understanding they can still be used until you actually purge them, regardless of the setting you disabled in Joomla Global Config. This is by design if I remember correctly.
> 
> I have tested both your domains that I know about today and they both have the header:
> 
> `Expires: Wed, 17 Aug 2005 00:00:00 GMT`
> 
> which probably means Joomla cache is not enabled, and no server cache is enabled. This expires header would also stop your browser caching.
> 
> Do you have a site that you can - every time - replicate this issue?

-------------------------------------------------------------------------------------

Thank you for taking a look at this issue. I sent you a PM with login credentials for Charleston.

1) I can replicate this - every time - on both Charleston and Savannah -- and other Joomla sites as well.

2) The setting in the System Config. is "ON - Conservative Caching".

3) It APPEARS that Firefox is caching the contents (see my PM).

-------------------------------------------------------------------------------------

1) Do you have any ideas as to the source of the Expires Header with a date of 17 Aug 2005? I see nothing in my .htaccess file that would cause this.

2) Are other Joomla users not encountering this behavior? I don't want to be so weird!

3) Is there anything weird about InMotion Hosting that could be causing this?

4) Let me know if you need additional information. I am very interested in seeing this time wasting issue resolved.

**Comment by PhilETaylor** [comment]
As I told you by email then:

**What you describe is the correct behaviour of Joomla.** 

Please read: https://docs.joomla.org/Cache

In general, you can think of Joomla having 3 levels of cache, increasing in aggresiveness

 - Conservative caching
 - Progressive caching
 - Page caching

To disable Page Caching - To switch this off, go to administrator Extensions / Plugins, find the System – Page Cache plugin, and disable it.

**Comment by PhilETaylor** [comment]
> "System - Page Cache" are both 'Protected' and cannot be disabled.

"System - Page Cache" is disabled by default on new Joomla 3 installs and can be configured and toggled published/unpublished.

<img width="783" alt="Screenshot 2021-04-13 at 21 59 19" src="https://user-images.githubusercontent.com/400092/114620484-8894fd80-9ca3-11eb-8821-40f5a5d78d23.png">

**Comment by JimHolloman** [comment]
> As I told you by email then:
> 
> **What you describe is the correct behaviour of Joomla.**
> 
> Please read: https://docs.joomla.org/Cache
> 
> In general, you can think of Joomla having 3 levels of cache, increasing in aggresiveness
> 
>     * Conservative caching
>     * Progressive caching
>     * Page caching

> To disable Page Caching - To switch this off, go to administrator Extensions / Plugins, find the System – Page Cache plugin, and disable it.

Thanks for the link. I will close this issue.

Some final comments, if I may:
1) I believe that in some previous versions of Joomla, turning Caching OFF inhibited "page' caching. 
2) It would be nice to have that behavior. However, I understand that such a change will likely be considered an "enhancement" for J4 rather than a J3 issue.
3) I will likely forget to enable the Page Cache plugin once I disable it.

And, what about authors and contributors that do not have Admin access? Does caching interfere with their ability to review and proof changes to the content?

**Comment by JimHolloman** [comment]
> > "System - Page Cache" are both 'Protected' and cannot be disabled.
> 
> "System - Page Cache" is disabled by default on new Joomla 3 installs and can be configured and toggled published/unpublished in the PLUGINS MANAGER (not in Extensions -> Manage)
> 
I got it!  I have closed this issue.

I wonder if it be feasible to add an option in the System Configuration --> System Tab to also turn ON and OFF "page" caching? That would avoid having to go to 2 different places to enable or disable caching. And, it would be much more intuitive. IMHO, it would be good to have one place to turn ALL caching ON or OFF.

**Comment by brianteeman** [comment]
The cache settings in global configuration and the cache settings in the page cache plugin are completely unrelated - they do different things.

> I believe that in some previous versions of Joomla, turning Caching OFF inhibited "page' caching.

No nothing has changed

> I will likely forget to enable the Page Cache plugin once I disable it.

You almost certainly dont need it. It is really only suitable for a site that is virtually static

> And, what about authors and contributors that do not have Admin access? Does caching interfere with their ability to review and proof changes to the content?

No - unless you are using page cache - see my previous comment.

> Do you have any ideas as to the source of the Expires Header with a date of 17 Aug 2005? I see nothing in my .htaccess file that would cause this.

Yes this is set by Joomla and is nothing to do with your htaccess (geeky answer to why that date it is the date that joomla began)

> I wonder if it be feasible to add an option in the System Configuration --> System Tab to also turn ON and OFF "page" caching? That would avoid having to go to 2 different places to enable or disable caching. And, it would be much more intuitive. IMHO, it would be good to have one place to turn ALL caching ON or OFF.

If you are working on a site that is so static that poage cache is useful then you wont need to be turning anything on and off.

Just don't use page cache plugin. You dont need it. Your sites will not benefit from it.

**Comment by JimHolloman** [comment]
> The cache settings in global configuration and the cache settings in the page cache plugin are completely unrelated - they do different things.
---- Text clipped by Jim Holloman ----
> Just don't use page cache plugin. You dont need it. Your sites will not benefit from it.

Thanks, Brian.
