### ISSUE TITLE
[4] * ?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32996]
### Steps to reproduce the issue

Joomla global config in Joomla 4 admin 

What is the `*` next to the Cache Time for ?

There is no popover help text etc... 

<img width="925" alt="Screenshot 2021-04-04 at 14 24 36" src="https://user-images.githubusercontent.com/400092/113510198-946d1b00-9551-11eb-868a-bc79aa5d9cfc.png">

**Comment by Quy** [comment]
It means `required`.

**Comment by PhilETaylor** [comment]
I need more sleep obviously.
