### ISSUE TITLE
[4.0] Blog Sample Data: Textlink `Typography` should load Menu `Typography`

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#32991]
### What needs to be fixed
Install Blog Sample Data. 

#### At `Home` user get a huge Picture with Text and Button `Typography`:

> ![Ohne Titel](https://user-images.githubusercontent.com/78906980/113503257-f8331c00-9530-11eb-91b1-f9c7054290c5.png)

The Button-Link is `index.php?option=com_content&view=article&id=11` and the Article loads in the same Menu. 

#### The Menu `Typography` has the Link `typography.html` and load the Article:

> ![Ohne Titel](https://user-images.githubusercontent.com/78906980/113503648-8ad4ba80-9533-11eb-82cb-1234564c7c04.png)
 

### Why this should be fixed
Because the Picture is so huge it looks like no Article is loaded cause user has to scroll down to find the Article.

### How would you fix it
Change Button-Link to load Menu `Typography`.

### Side Effects expected
Don't know.

**Comment by chmst** [comment]
Closing because this is resolved here #31711 please test.
