### ISSUE TITLE
[4] Post Install Actions for totp run useless sql on every page load

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32995]
### Steps to reproduce the issue

Joomla 4.0-dev
enable debug mode
Visit any admin console page and view the queries run in the debug toolbar

### Expected result

Caching so that a useless query is not run on every page load

### Actual result

SQL is run on every page load, that by default, actually returns ZERO rows (as 2fa is disabled by default) 

```
SELECT *
FROM `jos_extensions`
WHERE `type` = 'plugin' AND `enabled` = 1 AND `folder` = 'twofactorauth'
```

<img width="1071" alt="Screenshot 2021-04-04 at 14 10 50" src="https://user-images.githubusercontent.com/400092/113509832-946c1b80-954f-11eb-90cc-8fc67ca8989a.png">

**Comment by imbilashpaul** [comment]
where is the code

**Comment by PhilETaylor** [comment]
so today I (re-)learned that Joomla doesn't have a caching layer that's of use, unless "caching" is enabled in global config... this sucks, (what I'll call) object caching for things like this should be "a thing" so that we can speed up joomla and stop making Joomla recalculate things on each page load - especially when nothing has changed. These internal caches should not be connected/related to the caching layer for the frontend.

**Comment by PhilETaylor** [comment]
Fixing this is not as easy as first thought...
