### ISSUE TITLE
[4] Highlight CSS missing.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#32997]
### Steps to reproduce the issue

Joomla `4.0-dev`
Create an article with the word "create" and the word "admin" in the body text.
Ensure the `System - Highlight plugin` is enabled
View the article on the frontend
Then append the url you are on with `?highlight=WyJjcmVhdGUiLCJhZG1pbiJd` 

`WyJjcmVhdGUiLCJhZG1pbiJd` = base64encode of the array `["create","admin"]`

View the source code. 

### Expected result

The words `admin` and `create` to be highlighted. 

### Actual result

The HTML source is there, but no css is applied to "highlight" the terms.

```html
<span class="highlight" rel="create">create</span>

<span class="highlight" rel="admin">admin</span>
```

### System information (as much as possible)

Safari on mac

**Comment by RahulJha393** [comment]
Hey !! I would love to contribute to this. How can I share my code to help you highlighting the terms (i.e. "create" and "admin") . Kindly guide me

**Comment by prajjwal1231** [comment]
Hey @PhilETaylor 
I would like to contribute in this issue Pls assign it to me
& can you brief me in which color you want it to be highlighted.

**Comment by infograf768** [comment]
@PhilETaylor 
the css exists but there is an error in it. Error comes from finder.css

we have
```
.result__item .highlight::before {
    content: '';
    position: absolute;
    z-index: -1;
    top: 50%;
    left: 50%;
    -webkit-transform: translate(-50%, -50%);
    -ms-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
    width: calc(100% + 6px);
    height: calc(100% + 2px);
    background: hsla(60, 100%, 50%, .5);
    pointer-events: none;
    border-radius: 3px;
}
```
Looks like taking off `z-index: -1;` solves the issue. z-index can't work here as the body background is set to white.

![highlight](https://user-images.githubusercontent.com/869724/113545953-63d9bf80-95eb-11eb-9945-5843351dd89f.gif)

Change has to be done in
https://github.com/joomla/joomla-cms/blob/3ff6d0ccefb8f936349a9627db5d28ecab137b81/build/media_source/com_finder/css/finder.css#L116

**Comment by RahulJha393** [comment]
I have done the changes https://github.com/RahulJha393/joomla-cms/commit/2f951b832cee31baeaa85cf855b92a97842ef4cf 
hope this solves the issue

**Comment by infograf768** [comment]
@RahulJha393 
This is the wrong place. The issue is for J4 and not J3/staging

The change would have to be done in https://github.com/joomla/joomla-cms/blob/3ff6d0ccefb8f936349a9627db5d28ecab137b81/build/media_source/com_finder/css/finder.css#L116

Then make a PR towards 4.0-dev
and then use npm to test.

**Comment by infograf768** [comment]
Another solution is to add `z-index: -2;` to the body.
@drmenzelit @chmst What do you think?

Ref which created this issue: https://github.com/joomla/joomla-cms/commit/5725cbfb2ad60b37582f371a2a0a1c4700f21a72#diff-a4d0ce450acf901b0a318d7e5dd759f1d3167cbc756c0be6c98bb1d125ed23db

**Comment by RahulJha393** [comment]
@infograf768 Oops! OK let me check this out

**Comment by infograf768** [comment]
@RahulJha393 
Let's wait feed back from @drmenzelit @chmst

**Comment by drmenzelit** [comment]
`z-index: -2` for body can have unexpected side effects, so I think removing `z-index: -1` for `highlight` should be ok. 
The finder.css file was refactored by @hans2103 some months ago.

**Comment by infograf768** [comment]
@RahulJha393 
You got your answer. You can make the PR. :)

**Comment by infograf768** [comment]
@RahulJha393 
Will you do the PR ?

**Comment by ghost** [comment]
@prajjwal1231 
> I would like to contribute in this issue Pls assign it to me

please read https://github.com/joomla/joomla-cms/issues/31540#issuecomment-811070565

**Comment by himanshu007-creator** [comment]
if @prajjwal1231  is inactive, so should i proceed with the PR?

**Comment by drmenzelit** [comment]
@himanshu007-creator first come, first serve ;-)

**Comment by rjharishabh** [comment]
@infograf768 
I am not getting any CSS that is applied to the ```highlight``` class. Is there anything that is missing.

![highlight](https://user-images.githubusercontent.com/61203226/114268574-5d9a7780-9a1f-11eb-8cf9-ad3c599ee7e0.JPG)

**Comment by dgrammatiko** [comment]
Please test: https://github.com/joomla/joomla-cms/pull/33089
