### ISSUE TITLE
[4.0] mod_loginsupport news url

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#33017]
### Steps to reproduce the issue

Go to the Administrator login page. At the bottom left there is a link to Joomla! News - try it.

### Expected result

Joomla news page

### Actual result

Joomla main page

### Additional comments

Is the label wrong or the link wrong. Or do we need an extra link for both? The link is in line 49 of

joomla-cms/administrator/modules/mod_loginsupport/mod_loginsupport.xml

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/33058
