### ISSUE TITLE
[4.0] autoload_psr and ftp

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33019]
I dont have the ability to test this but I am fairly certain that the recent change to not store the ftp password will mean that on a site that needs to use ftp to write files it will never be able to update the autoload_psr file

**Comment by PhilETaylor** [comment]
I vote for the FTP layer to die.

**Comment by brianteeman** [comment]
so do I but Nik and a few others insisted it was needed

**Comment by PhilETaylor** [comment]
[4] Allow in-memory autoload_psr4.php #33263

**Comment by brianteeman** [comment]
closing this as its documented elsewhere now
