### ISSUE TITLE
Contact Category Layout is missing from Menu Options

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#33016]
You can set a Contact Category Layout at a Global Configuration Level (under Contact -> Category -> Choose a Layout).

You can also set a Contact Category Layout at a Category Level (under Options -> Layout)

But this option is missing at a Menu-Level.

### Steps to reproduce the issue

- Create a Menu of type "List Contacts in a Category"
- Go to "Category" tab

### Expected result

- There should be a "Layout" option to pick the Contact Category Layout

### Actual result

- There is no Layout option

**Comment by AndySDH** [comment]
Looks like this is not a bug, you need to create a new menu type xml to use an alternative category layout, BUT ONLY if that category has a menu item assigned. So I guess intended behavior, but very confusing.

See proofs of user confusion (topics and comments):

https://forum.joomla.org/viewtopic.php?t=750018
https://forum.joomla.org/viewtopic.php?t=844520

Especially this quote sums it up:

> So it appears the only time an alternative layout that you specify in the category options will have any effect is if that category has no menu item.
That makes no freaking sense.
Couple that with no way to select an alternative layout in the menu item.
And it really makes even more no freaking sense.

Also brought up in: https://github.com/joomla/joomla-cms/issues/21800

**Comment by MacJoom** [comment]
Closed as not a bug.
