### ISSUE TITLE
[4] jQuery in libraries/src/HTML/Helpers/Behavior.php

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#33022]
### Steps to reproduce the issue
- See JQuery script in https://github.com/joomla/joomla-cms/blob/4.0.0-beta7/libraries/src/HTML/Helpers/Behavior.php#L176-L191

### Expected result
- As far as I've understood jQuery dependencies shall be removed from core code.

**Comment by Fedik** [comment]
yeap, `legacy/highlighter.js` also have jQuery dependency currently,

**Comment by Fedik** [comment]
check that PR #33089
