### ISSUE TITLE
[4.0]extensions install and ftp

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33020]
### Steps to reproduce the issue
Enable and configure ftp in global configuration

Go to extensions: install and the ftp login details tab

### Expected result
Username is the ftp username
Password is empty

As can be seen on the joomlaupdate screen below
![image](https://user-images.githubusercontent.com/1296369/113569950-43216200-960b-11eb-9779-1f242ee1bf94.png)

Or Username and ftp are empty as can be seen on the ftp tab in global config
![image](https://user-images.githubusercontent.com/1296369/113570173-b5924200-960b-11eb-9daf-8af7f588ab27.png)

### Actual result
The fields are autofilled based on the user login name
![image](https://user-images.githubusercontent.com/1296369/113570032-6a782f00-960b-11eb-854a-92d44beba56f.png)

**Comment by PhilETaylor** [comment]
Dont shoot me, but is that your browser autofilling the fields?  is that what the blue background is showing?

**Comment by ghost** [comment]
@brianteeman i don't get the result you describe above, at `Extensions: Install` fields `Username`and `Password` are empty.

**Comment by brianteeman** [comment]
Sorry both of you I wasn't clear. Yes they are the browser autofilling the fields. The difference between the autofill is that the fields have different names. That is what I was highlighting but didnt explain it well enough obviously

**Comment by ghost** [comment]
No need for sorry, brian. 

I guess i understand not correct but if you mean the difference in username `brian_db1` and `brian` by the autofill i can't confirm cause at `Extensions: Install` the field is empty. 
Maybe i need to activate a autofill-function in firefox to test correct?
