### ISSUE TITLE
[4.0] renamed @param ??

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33027]
@wilsonge In this commit you renamed the `@param` from JForm to Form

https://github.com/joomla/joomla-cms/commit/3975a321102236231967f7f2b056838be0ee66a8

There are a gazillion similar instances - should they be updated as well ? 
And what about `@var`

**Comment by wilsonge** [comment]
Sorry just saw this - yes - and thankyou for doing it!
