### ISSUE TITLE
List Limit missing from Contact Category View

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#33021]
The Contact Category View is missing the ability to set the default number of contacts to display on the page.

This option is present for a lot of menu items in Joomla, such as category list, tags, single contact articles, etc.

However, it's missing for the Contact Category view. This instead just uses the "Default List Limit" in Global Configuration, with no way to set a different one per menu item.

This has been an "issue" for a long time, see: https://joomla.stackexchange.com/questions/582/how-do-i-change-how-many-contacts-to-display

Not sure why this view was left "stranded", without this option... Any way this setting can be implemented for this view as well?

**Comment by AndySDH** [comment]
So this was already reported here: https://github.com/joomla/joomla-cms/issues/29866

The option was added in Joomla 4 here: https://github.com/joomla/joomla-cms/pull/23710

But then it was removed again (!) here: https://github.com/joomla/joomla-cms/pull/30904

/facepalm emoji

**Comment by chmst** [comment]
My2Cent: This must be consistent - either all lists have it, or none.

**Comment by brianteeman** [comment]
#30904 is definitely wrong. If we can set the number of articles to be displayed independently of the global list limit then we should be able to do the same for contacts,

Should be relatively easy to resolve. @chmst I can do that or did you tagging it JBS mean that you/someone is working on it

**Comment by brianteeman** [comment]
To be clear #30904 was fixing a bug as the original code from #23710 was not correct

**Comment by brianteeman** [comment]
Please see #33050
