### ISSUE TITLE
Joomla4.07 Installation Error!

### ISSUE THREAD

**Issue by jeansh** [joomla/joomla-cms#33030]
### Steps to reproduce the issue
( ! ) Fatal error: Uncaught Error: Call to undefined method JLoader::setup() in /var/www/html/*/libraries/bootstrap.php on line 34
( ! ) Error: Call to undefined method JLoader::setup() in /var/www/html/*/libraries/bootstrap.php on line 34

php7.4.16  Joomla4.07B

Installation Error, please help me! Thanks!

**Comment by ssnobben** [comment]
Have you installed the latest beta build? 

If not try to install that one first and come back with more info about your deploy environment & server settings too.

**Comment by jeansh** [comment]
I download Joomla 4.0 Beta 7  from https://github.com/joomla/joomla-cms/releases/tag/4.0.0-beta7.
and  php info:
![图片](https://user-images.githubusercontent.com/32347628/113667662-b1395800-96e3-11eb-9386-a8d0e6b7cbf0.png)

**Comment by ssnobben** [comment]
This seems not like a developer problem but better doing a FPA ( Forum Post Assistant) first also in Joomla community support forum ie https://forum.joomla.org/viewforum.php?f=708&sid=a09dcce46c1273ed4761f7b7fe670805  

So do a FPA and ask help there will be the way forward for you and the first step.

Have you use/install Joomla before ?bcs there is no single report that you cant install this version without problem.

Cheers!

**Comment by jeansh** [comment]
I've been using Joomla for years but just started using Joomla 4&nbsp; and wanted to test the new version.
&nbsp;I couldn't register for Forum successfully so I submitted Joomla Issue.


thanks







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "joomla/joomla-cms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月6日(星期二) 下午2:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [joomla/joomla-cms] Joomla4.07 Installation Error! (#33030)





 
This seems not like a developer problem but better doing a FPA ( Forum Post Assistant) first also in Joomla community support forum ie https://forum.joomla.org/viewforum.php?f=708&amp;sid=a09dcce46c1273ed4761f7b7fe670805
 
So do a FPA and ask help there will be the way forward for you and the first step.
 
Have you use Joomla before?
 
Cheers!

**Comment by ssnobben** [comment]
Ok good then you know its not installation problem of Joomla 4 beta 7 in general but some issues with your installation environment. 

So register and join the Joomla forum bcs its great support there for this kind of questions/help and do a FPA for fastest help for people to analyse your problem(s).

All the best!

**Comment by richard67** [comment]
Closing due to reasons stated in previous comments. Feel free to re-open if it turns out closing was a mistake.
