### ISSUE TITLE
IcoMoon Fonts - expand , contract

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#33036]
### Steps to reproduce the issue

Use the following IcoMoon icons:
class="large-icon icon-expand-2"
class="large-icon icon-contract-2"

### Expected result

Display as documented here:
https://docs.joomla.org/J3.x:Joomla_Standard_Icomoon_Fonts

There appears to be no equivalent J4 page.
Still expect the same result.

### Actual result

As screenshot1.png
Extract of the HTML is screenshot2.png

icon-basket is showing instead of icon-contract-2

### System information (as much as possible)

Windows 10 client and Apache server.
PHP 8.0.3
Browser : firefox & chrome
Joomla template : cassiiopeia

### Additional comments
Same code was ok on J3.

**Comment by richard67** [comment]
@hans2103 Could you have a look on that? Or should I ping the bear? Thanks in advance.

**Comment by brianteeman** [comment]
check the mapping build/media_source/system/scss/icomoon should be pretty self explanatory for you to work out @BrainforgeUK

**Comment by BrainforgeUK** [comment]
Seems to have got confused with IcoMoon and FontAwesome.
The cassiopeia template uses FontAwesome ... the component a mix!

Using this link as a cheatsheet:
[https://fontawesome.com/icons?d=gallery&p=2&m=free](https://fontawesome.com/icons?d=gallery&p=2&m=free)

Changed the HTML to use this.
`class="fa fa-compress-arrows-alt"`
