### ISSUE TITLE
[J4] Radio Buttons: Visually not clear which is selected

### ISSUE THREAD

**Issue by regularlabs** [joomla/joomla-cms#33049]
When using the class="btn-group" on a form element with type="radio", it is not clear which option is actually selected:

<img src="https://user-images.githubusercontent.com/13553242/113850699-04baad00-979b-11eb-84cf-00e88a39c2c8.png" width="185"/>

You win a prize if you can tell which option is selected in the btn-group example: A or B?
Well, answer is B.

I suggest changing the styling to use blue for the selected option. And make the not-selected option(s) somewhat gray:

<img src="https://user-images.githubusercontent.com/13553242/113852224-9d056180-979c-11eb-92b9-764bebbf4b1d.png" width="131"/>

PS: radio buttons not using the switcher layout currently don't work in beta release. But is fixed in #32367

**Comment by chmst** [comment]
What you would like as solution?  Isn't it a de-facto-standard that dark means "selected"?

In J3 we have for example this,which for me is more confusing.
![grafik](https://user-images.githubusercontent.com/1035262/114205836-04691000-995b-11eb-90f5-fb37a1681280.png)

**Comment by regularlabs** [comment]
As you can see in the animated radio switcher: dark is NOT the selected option!

**Comment by regularlabs** [comment]
![image](https://user-images.githubusercontent.com/13553242/114210114-ac80d800-995f-11eb-8c26-4cca8cfd0314.png)

**Comment by regularlabs** [comment]
A simple solution:
Set the labels inside `.btn-group.radio` to `opacity: .5;`, and set the active labels back to `opacity: 1;`.
![image](https://user-images.githubusercontent.com/13553242/114266309-f1574e00-99f5-11eb-94fb-8c2956e7bea2.png)

**Comment by AndySDH** [comment]
The blue color on the selected option instead of gray would be better as well, as of the original post by Peter

**Comment by brianteeman** [comment]
Please submit a pr

**Comment by regularlabs** [comment]
Seeing this would need a change in the css, I am at a loss.
There is no `media` folder in the repo and no idea where the template.scss grabs the necessary styles from or where to change the source btn-group styling.

**Comment by brianteeman** [comment]
I guess you need to find a real developer to help you use composer, npm and git :)

**Comment by regularlabs** [comment]
I guess so. So my job is done here. I reported the issue. If someone wants to fix it, fine. If not, 🤷🏻‍♂️

**Comment by Bakual** [comment]
For reference:
The source files for the media files are usually here: https://github.com/joomla/joomla-cms/tree/4.0-dev/build/media_source
However for templates, they are in the respective template folder (https://github.com/joomla/joomla-cms/tree/4.0-dev/templates/cassiopeia/scss and https://github.com/joomla/joomla-cms/tree/4.0-dev/administrator/templates/atum/scss
This is done so they end up in the distributed CMS and people can reuse them for their own templates.

**Comment by regularlabs** [comment]
Thanks, I got that for.
This whole styling is too baked in to bootstrap. So I am dropping this.
