### ISSUE TITLE
[4.0] Popovers in Category list header, missing ordering indication

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#33048]
### Steps to reproduce the issue
Open a Category list in frontend, hover the headline.

### Expected result
The ordering direction of columns is indicated by an arrow as in backend tables.
No popvers.

### Actual result
<img width="783" alt="popovers-frontend" src="https://user-images.githubusercontent.com/1035262/113842585-15ffbb80-9793-11eb-85b4-8199d4bd89ed.PNG">

**Comment by ghost** [comment]
Confirming the issue.

**Comment by YatharthVyas** [comment]
I could narrow down the issue to https://github.com/joomla/joomla-cms/blob/f4ac18829fad6eadd7260ac2f951aca0c7da459b/libraries/src/HTML/Helpers/Grid.php#L65 
Here, if I remove `class="hasPopover"` then the popover no longer appears, and the sorting works as intended.

![output)](https://user-images.githubusercontent.com/53610833/114264359-11900880-9a08-11eb-8eeb-cd776e8489f2.gif)

However, this helper (grid.sort) has been used in the following files as well:
- components\com_contact\tmpl\category\default_items.php
- components\com_contact\tmpl\featured\default_items.php
- components\com_content\tmpl\category\default_articles.php
- components\com_tags\tmpl\tag\list_items.php

So, if the popover is unnecessary for these other tables too then this will be an easy fix. If not, should I look for a different helper to render the category list header?

I would be glad to submit a PR fixing this.

**Comment by chmst** [comment]
Popover is unneccessay in all views. A PR will be welcome!

**Comment by chmst** [comment]
Closing as we have a PR

**Comment by YatharthVyas** [comment]
Please re-open this issue as the PR has been closed.

**Comment by Quy** [comment]
@chmst Please confirm this is fixed with PR #39643.

**Comment by Quy** [comment]
Closing as this is no longer an issue.
