### ISSUE TITLE
[4.0] Collapse in categories view doesn't work if navbar is not present

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#33042]
### Steps to reproduce the issue
Create a menu in position `menu`
Create some categories with subcategories and some articles.
Create a menu item of type `List All Categories in an Article Category Tree` 

Go to the categories page. You will see a list of categories and a + symbol in the category with a subcategory (Blog)
![grafik](https://user-images.githubusercontent.com/9153168/113733629-ef8e4180-96fa-11eb-9324-3175c3f907be.png)

When you click on the + symbol the category expands and you see the subcategory (General)
![grafik](https://user-images.githubusercontent.com/9153168/113733778-12b8f100-96fb-11eb-80eb-28a7dc937d6a.png)

**Now unpublish the menu**

### Expected result
The expand / collapse function works

### Actual result
The expand / collapse function doesn't work

### Explanation
The `com_content/tmpl/categories/default.php` file loads a script for accordion `$wa->useScript('com_categories.shared-categories-accordion');` that only changes the `aria-label` and the `icon` depending on the status expanded or collapsed. 
The collapse function itself is on a Javascript from Boostrap (`vendor/bootstrap/collapse.min.js`), that is not being loaded in the view.
In Cassiopeia the collapse Javascript is being loaded when a menu is published in the position `menu`. 
`<nav class="navbar navbar-expand-md">
	<?php HTMLHelper::_('bootstrap.collapse', '.navbar-toggler'); ?>
...
`
That is why the collapse in the categories list only works if the menu is present.

### Solution

- Load the collapse script from Bootstrap in the view or
- Create an own collapse / accordion function (e.g. extend the functionality of the `com_categories.shared-categories-accordion` script). A good example can be found here: https://inclusive-components.design/collapsible-sections/

**Comment by chmst** [comment]
Related to #33037, the buttons needs a complete redesign on layout and function

**Comment by drmenzelit** [comment]
I'm working on a solution. PR coming soon

**Comment by drmenzelit** [comment]
Closing as we have a PR #33052
