### ISSUE TITLE
Add effects in "readmore" button !!

### ISSUE THREAD

**Issue by jaiswalpalak** [joomla/joomla-cms#33053]
I want to improve Readmore button present in Joomla! Announcements because it is looking very ordinary so I want to make it more catchy ! please assign me this..
![Screenshot (512)](https://user-images.githubusercontent.com/78416508/113913767-52b2cd80-97fa-11eb-84f1-46dbd1db4715.png)

**Comment by drmenzelit** [comment]
What you are trying to change is on the joomla.org website. You can't solve it in this repository. And you don't need to be assigned to an issue, you can directly submit a PR. The correct repository for your issue / PR is https://github.com/joomla/joomla-websites/
