### ISSUE TITLE
No "Add new Authenticator" for WebAuthn Login (J4B6)

### ISSUE THREAD

**Issue by Dr-Sommer** [joomla/joomla-cms#33056]
### Steps to reproduce the issue
In user Interface klick on "W3C Web Authentication" 

### Expected result
To see the  "Add new Authenticator" Button to add Authenticator

### Actual result
No "Add new Authenticator" Button

![webauth1](https://user-images.githubusercontent.com/979639/113935711-25185500-97f7-11eb-9aa8-bfd645858842.jpg)

![webauth2](https://user-images.githubusercontent.com/979639/113935745-2fd2ea00-97f7-11eb-9e24-0c4d96de53dc.jpg)

### System information (as much as possible)
J4b6
Debian Buster 10
PHP 7.3
ISPConfig
Apache/2.4.38

Thank you in Advance

**Comment by PhilETaylor** [comment]
Are you on a `https://` prefixed url which is a standard requirement for authentication with WebAuthn

**Comment by PhilETaylor** [comment]
Either of the PHP extensions GMP or BCmath must be loaded to add authenticators - can you confirm you have one of these PHP Extensions installed?

**Comment by Dr-Sommer** [comment]
Hi Phil, Thx for your Time ;)

1. Yes, I`m using  "lets encrypt" for HTTPS

2. Yes, GMP and BCmath seems to be installed:

Here is the Output from PHP -m :

`[PHP Modules]
apc
apcu
bcmath
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
gmp
hash
iconv
imagick
imap
intl
json
libxml
mbstring
memcache
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
pspell
readline
recode
Reflection
session
shmop
SimpleXML
soap
sockets
sodium
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlrpc
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
`

not a clue why the Button is not visible...  ;(

**Comment by ChristineWk** [comment]
Found this, if relevant? #29731<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33056">issues.joomla.org/tracker/joomla-cms/33056</a>.</sub>

**Comment by PhilETaylor** [comment]
Do you have a javascript error in your console. 

The only reason the button would not show should be if you dont have GMP or bcmath installed.

**Comment by PhilETaylor** [comment]
`PHP -m`

Thats at the command line - which could and often does have a different list of PHP modules. 

Anyway, you would get a red warning if they were not installed above where the button should be.

**Comment by ReLater** [comment]
> J4b6

There is a newer version or test with a nightly build.

> Either of the PHP extensions GMP or BCmath must be loaded to add authenticators - can you confirm you have one of these PHP Extensions installed?

Looks like solved meanwhile. See https://github.com/joomla/joomla-cms/pull/30316#issuecomment-678646090

**Comment by PhilETaylor** [comment]
that upstream fix would have fixed a JS alert saying you could not add when you had touched your device. Different problem to this.

**Comment by Dr-Sommer** [comment]
Ok, I did read out the "info.php" File:

![image](https://user-images.githubusercontent.com/979639/113942037-82fd6a80-9800-11eb-9e0d-995bb50597c5.png)

Seems that both Extensions are working..

**Comment by Dr-Sommer** [comment]
@PhilETaylor : there are also no Errors in the Console...

**Comment by PhilETaylor** [comment]
Please run this in a PHP file:

```php
if ((function_exists('gmp_intval') === false)){
echo "A";
} else {
echo "B";
}
if ((function_exists('bccomp') === false)){
echo "C";
} else {
echo "D";
}

```

what does it output?

**Comment by Dr-Sommer** [comment]
Showes:

bool(true) bool(true)

**Comment by PhilETaylor** [comment]
ok the only other place that sets `allow_add` to false is if you are trying to edit A DIFFERENT USERS webauthn keys - this is not allowed.

**Comment by Dr-Sommer** [comment]
Ah, OK.... I`m trying it as ADMIN to a Registered User! So is this the Error?
How can I do it as Registered User?

Thank you so much.. ;)

**Comment by PhilETaylor** [comment]
You, logged in as admin, cannot add webauthn for other users. This is by security design of webauthn standards.

**Comment by Dr-Sommer** [comment]
So if  I Try it as regisered User on Frontend, I get this message:

`The specified username does not correspond to a user account that has enabled passwordless login on this site.`

**Comment by Dr-Sommer** [comment]
Is there a manual I can use? ThX

**Comment by PhilETaylor** [comment]
> The specified username does not correspond to a user account that has enabled passwordless login on this site.

You first have to be logged in as a user, and add the Key. Then logout and then you can use the key. If the user has no keys enabled then you get the message above.

**Comment by PhilETaylor** [comment]
also see https://magazine.joomla.org/all-issues/december/passwordless-authentication-for-secure-fast-easy-logins-in-joomla-4 which was written by Nic.

**Comment by Dr-Sommer** [comment]
AAhhh... THERE IT IS!!! ;) ;) The Add Button is in the Users Profile.. ;) 

Thank You sooo much, Phil.. <3 
Understanding this was a challenge for me... ;)
I'll finish now the config and post a small HOWTO for Dummys like me... ;)

THAANNK  YOOUU!!  (Struggling for Days.. ;))  )

**Comment by PhilETaylor** [comment]
Im busy adding a warning if you are not logged in as the user so you can see it in future (and others can not fall into this trap)

**Comment by PhilETaylor** [comment]
<img width="1593" alt="Screenshot 2021-04-07 at 23 50 01" src="https://user-images.githubusercontent.com/400092/113944165-010b4280-97fc-11eb-976d-3d5bb89eb71e.png">

**Comment by Dr-Sommer** [comment]
This is GREAT, Phil... ;)
As Admin I`m used to do everything in Joomla and if there is no warning (and in this case then no +Button) leaves me totally confused....  ;)

**Comment by Dr-Sommer** [comment]
Ok, Easy Step by Step Howto:
1. Log out from front and Backend
2. log on as the User you want to activate webauth (I assume you`ll do it on the frontend)
3. DO NOT TRY THIS AS ADMIN FOR ANOTHER USER!! See above....
4. Now you will see your Profile Data
5. Klick on EDIT PROFILE
6. Scroll down to "Add new Authenticator" 
7. Authenticate your USB Key

This should be it... ;)

I`m, trying to use the build in [Webauth from Firefox](https://stackoverflow.com/questions/52445624/how-to-use-webauthn-without-key-fob),  (Softkey) but this its not working as easy as I expected....  so I have to research more bout it...

**Comment by PhilETaylor** [comment]
Buy a Yubikey and never look back! https://www.yubico.com/je/quiz/

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33064 . Thanks in advance.

**Comment by PhilETaylor** [comment]
@Dr-Sommer please test https://github.com/joomla/joomla-cms/pull/33064 so that it has a chance of being merged :)
