### ISSUE TITLE
[4] tooltips detached from their correct positions in Category List

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33057]
### Steps to reproduce the issue

Frontend with the sample data (not sure which ) creates a Category List. 

Login as super admin on front end to get edit buttons in the Category list

Hover over the icons next to the edit link and look at where the popovers are. 

### Expected result

No popovers, or popovers close to the mouse cursor

### Actual result

Popovers off the screen to the right hand side

https://user-images.githubusercontent.com/400092/113936895-5b060b00-97f0-11eb-8de5-006df62d9f41.mp4

### System information (as much as possible)

safari on Mac

**Comment by Quy** [comment]
Duplicate #33047?

**Comment by infograf768** [comment]
See PR https://github.com/joomla/joomla-cms/pull/33066
