### ISSUE TITLE
[4] Resizing screen when editing image causes preview issue

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33061]
### Steps to reproduce the issue

Hard to explain - watch video

This is on the Edit Image page in Media manager when resizing the browser to "get a better view"

### Actual result

https://user-images.githubusercontent.com/400092/113940817-fd74bd00-97f5-11eb-90f1-b9818606db9a.mp4

Also note that the JS values turn to NaN and there are console errors if you keep messing with the screen width 

<img width="1484" alt="Screenshot 2021-04-07 at 23 10 10" src="https://user-images.githubusercontent.com/400092/113941135-7c69f580-97f6-11eb-93a8-338c89b98d84.png">

### System information (as much as possible)

safari on Mac

**Comment by Quy** [comment]
Duplicate #31859?
