### ISSUE TITLE
[4] media manager destroys images when cropping

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33063]
### Steps to reproduce the issue

I was convinced this was just me - but can you replicate it?

Go to Media Manager in Joomla 4 admin 

Click to Edit the joomla_black.png file

When on the CROP tab, just keep pressing save, save save save until the 4 fields show NaN

Takes 3-6 clicks. 

Then you have destroyed the image. and if you have error reporting to maximum you get in your Ajax from the save, and on the next refresh of the page 

```
Notice: exif_imagetype(): Error reading from /application/images/joomla_black.png! in /application/libraries/src/Helper/MediaHelper.php on line 74

Notice: getimagesize(): Error reading from /application/images/joomla_black.png! in /application/libraries/src/Image/Image.php on line 185
```

Is it me?

**Comment by himanshu007-creator** [comment]
@PhilETaylor , ✅ confirmed same behaviour ( chrome on windows )

![proof](https://user-images.githubusercontent.com/65963997/114066518-70933780-98b9-11eb-8c52-bfb50d85cef6.gif)

**Comment by PhilETaylor** [comment]
The more I play with the crop/resze/rotate the more times I notice NaN javascript errors in the text fields.

**Comment by Magnytu2** [comment]
@PhilETaylor This is an error that has been pointed out several times from memory. #32326

**Comment by PhilETaylor** [comment]
> @PhilETaylor This is an error that has been pointed out several times from memory. #32326

And yet still unresolved :)

**Comment by Magnytu2** [comment]
@PhilETaylor  Yes and as soon as you use the media manager with more than 12 images it's the same. The media manager is not solid. The display of fields over the entire width is too large. And I find that its use from an article is even more fragile and I very often find myself without illustrations.

**Comment by ceford** [comment]
After the joomla_black.png file gets corrupted the Media screen stops working completely. Three clicks to kill a major component of Joomla 4! This needs to be marked a **release blocker.** Ordinary users will not know they have to deleted the corrupted file using something other than com_media to get it to work again.

**Comment by PhilETaylor** [comment]
> After the joomla_black.png file gets corrupted the Media screen stops working completely. 

I tried to fix that and it was rejected #33141

**Comment by PhilETaylor** [comment]
IIRC its only broken if you have error reporting set to anything other than none.

**Comment by brianteeman** [comment]
I am unable to replicate this now. There have been a lot of changes in the js since this issue was opened - probably solved there
