### ISSUE TITLE
[4] media manager cannot cope with broken images

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33062]
### Steps to reproduce the issue

https://user-images.githubusercontent.com/400092/113942022-17170400-97f8-11eb-88a3-f4164ed1eccc.png

Download this broken image and place in your /images folder as broken.png

Set error reporting to maximum in Joomla global config 

Visit media manager in the backend.

### Expected result

Media Manager works

### Actual result

Ajax call has warning:

```
<br/>
<b>Notice</b>
:  exif_imagetype(): Error reading from /application/images/broken.png! in 
<b>/application/libraries/src/Helper/MediaHelper.php</b>
 on line 
<b>74</b>
<br/>
<br/>
<b>Notice</b>
:  getimagesize(): Error reading from /application/images/broken.png! in 
<b>/application/libraries/src/Image/Image.php</b>
 on line 
<b>185</b>
<br/>
```

**Comment by ghost** [comment]
Confirm that after upload of broken.png media manager don't work. I don't know how to see a ajax call but in console got:

![grafik](https://user-images.githubusercontent.com/78906980/114133929-2173f380-9907-11eb-9d70-b8ee78a78d26.png)

After removing broken.ong media manager works again, so i guess the above message is caused by broken.png.

**Comment by PhilETaylor** [comment]
@richard67 please reopen. Seems I no longer have rights to reopen my own closed issues.

**Comment by PhilETaylor** [comment]
My two attempts at fixing this have been rejected by the maintainers. Therefore I bow out and someone else can fix it. Im not wasting anymore time on it.

**Comment by richard67** [comment]
I haven’t rejected anything.

**Comment by PhilETaylor** [comment]
Apologies for the plural use of the word "maintainers" :) ...
