### ISSUE TITLE
[4] Rotate angle preset buttons do not update the angle 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33070]
### Steps to reproduce the issue

Edit an image in Joomla 4 media manager

### Expected result

When I click on 0/90/180/275 the Angle field should update with that figure and the image preview should rotate.

### Actual result

![Screen Recording 2021-04-08 at 02 43 05 pm](https://user-images.githubusercontent.com/400092/114037384-dad7b800-9878-11eb-89d3-0f12bf62bbd3.gif)

### System information (as much as possible)

safari on mac

**Comment by himanshu007-creator** [comment]
✅confirmed same behaviour on chrome ( windows ).

**Comment by PhilETaylor** [comment]
Paging @dgrammatiko - looks like a quick bs5 fix needed here?

**Comment by dgrammatiko** [comment]
Check #33071

**Comment by alikon** [comment]
please test #33071
