### ISSUE TITLE
[4.0] <joomla-field-fancy-select> only show placeholder hint together with multiple

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#33075]
### Steps to reproduce the issue

1. Open com_contact and check the search tools

2. Delete line `multiple="true"` in https://github.com/joomla/joomla-cms/blob/03c1bf19acb1ca992c3151d7e7ec87e6ef1cb5e4/administrator/components/com_contact/forms/filter_contacts.xml#L41

2. Open com_contact again and check the search tools

### Expected result

You see the _placeholder hint_ regardless of whether multiple is selected.

### Actual result

You only see the _placeholder hint_ together with `multiple`. So it is not possible to filter for the first option in the first attempt. The filter only works when an option changes.

### System information (as much as possible)

php: Linux php74 5.8.0-48-generic #54~20.04.1-Ubuntu SMP Sat Mar 20 13:40:25 UTC 2021 x86_64
dbserver: mysql
dbversion: 10.5.9-MariaDB
dbcollation: utf8mb4_unicode_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: false
phpversion: 7.4.16
server: Apache/2.4.46 (Unix) OpenSSL/1.1.1k
sapi_name: fpm-fcgi
version: Joomla! 4.0.0-beta8-dev Development [ Mañana ] 2-February-2021 20:02 GMT
useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0

**Comment by brianteeman** [comment]
Not sure what your issue is. the layout you are referring to only makes sense to use when it is a multiple select. If you wanted the category field to be a single select then you would change the xml to the following

```
		<field
			name="category_id"
			type="category"
			label="JCATEGORY"
			extension="com_content"
			hint="JOPTION_SELECT_CATEGORY"
			onchange="this.form.submit();"
			published="0,1,2"
			>
			<option value="">JOPTION_SELECT_CATEGORY</option>
		</field>
```

![image](https://user-images.githubusercontent.com/1296369/114135189-cd661080-9900-11eb-9294-094c44073947.png)

**Comment by astridx** [comment]
Thank you @brianteeman . 

You are right. I used the Category Field as a template for my own field and didn't think any further. 

But actually you didn't need the multiple option with  `<joomla-field-fancy-select>` then and it just confuses because it has to be there and it has to be true, right?

**Comment by brianteeman** [comment]
No problem
