### ISSUE TITLE
This happens here too after login in admin, but not always.

### ISSUE THREAD

**Issue by imbilash** [joomla/joomla-cms#33088]
This happens here too after login in admin, but not always.

<img width="1250" alt="Screen Shot 2021-04-10 at 08 03 49" src="https://user-images.githubusercontent.com/869724/114260163-649b9880-99d3-11eb-9ef5-7f8b569c361f.png">

_Originally posted by @infograf768 in https://github.com/joomla/joomla-cms/issues/33083#issuecomment-817085464_

**Comment by peterhens** [comment]
good info[The Best Discounted Gaming Products In 2021.pdf](https://issues.joomla.org/uploads/1/7a8aee4ec3d5a62ad0b6caad21ebe810.pdf)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33088">issues.joomla.org/tracker/joomla-cms/33088</a>.</sub>

**Comment by ghost** [comment]
please delete spam https://github.com/joomla/joomla-cms/issues/33088#issuecomment-817129775

**Comment by peterhens** [comment]
> please delete spam [#33088 (comment)](https://github.com/joomla/joomla-cms/issues/33088#issuecomment-817129775)

Not a spam idiot
