### ISSUE TITLE
[4.0] Upload & Update: Keep size-info together

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33095]
### What needs to be fixed
At `Joomla Update` information about `Maximum upload size` and `Selected file size` :

> ![Screenshot_2021-04-11 Joomla Update - sandramay09050406 - Administration](https://user-images.githubusercontent.com/78906980/114293117-d63b1b80-9a93-11eb-86d4-c94c54a140df.png)

### Why this should be fixed
Infos shouldn't be so far from each other.

### How would you fix it
Keep them in one line below the filename.

### Side Effects expected
Don't know.

**Comment by chmst** [comment]
It depends on your screen / windows size, if and where the line breaks.

**Comment by chmst** [comment]
please test  #33116
