### ISSUE TITLE
[4.0] change template style

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33098]
I can detect the active template style in a frontend template with
`$app->getMenu()->getActive()->template_style_id;`

This will return values of `0` if it is the default template style or the `id` if a style has been assigned to the menu

But is there a way that I can change the templatestyle in the template when a condition is met
eg
```
$option   = $app->input->getCmd('option', '');
if ($option == 'com_content') {
change the templatestyle to template_style_id=12
}
```

**Comment by dgrammatiko** [comment]
Once https://github.com/joomla/joomla-cms/pull/32710 is merged you could recreate an object for templateParams (basically the db values for the style) and call that function with the template name and the obj you just created

**Comment by brianteeman** [comment]
I'm sure there must be a way to it now. It can be done in a plugin but I wanted to try and just do it in the template itself.

**Comment by dgrammatiko** [comment]
It's a little more complicated.  the `?template=foo` is working because there is code to support it here: https://github.com/joomla/joomla-cms/blob/443f5933a3c9336f37f992d855b61b09a5f4e21e/libraries/src/Document/HtmlDocument.php#L704
but there is no such code for the styles. Also, styles are stored in the db so there's a need for a db query to set the styles to another Id.

**Comment by brianteeman** [comment]
Getting the style is the easy part and in my case I know what the id of the style is that I want to use

**Comment by Fedik** [comment]
it a bit tricky, you have 2 option:
1) change input `templateStyle` in `onAfterRoute`: `$app->input->set('templateStyle', 10)`;
2) set your own template and its params `onAfterDispacth`, the params should be loaded from your Template Style:
```php
$template = ... some code to load template name and params
$app->set('theme', $template->template);
$app->set('themeParams', $template->params);
```

**Comment by brianteeman** [comment]
thank you

**Comment by brianteeman** [comment]
I have it working as a plugin - just can't get it to work directly in the template php - guess thats not possible

**Comment by Fedik** [comment]
> just can't get it to work directly in the template php

you mean in template index.php/component.php?
well, yea, there it will not work, because the params (template style) loaded before this file executed.

Need to be a plugin.
