### ISSUE TITLE
[4.0] Mail Templates edit options

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33105]
What is the purpose of the edit subject and edit body options with the default being off for both.

I cant see any reason for them both not being editable by default or any reason for them ever to be non editable.

What am I missing?

**Comment by Fedik** [comment]
This is kind of "Default Value" vs "User Value".
I have commented it in https://github.com/joomla/joomla-cms/issues/27619#issuecomment-812426613

**Comment by brianteeman** [comment]
Closing as there is a PR to rewrite the mail templates to be something useful<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33105">issues.joomla.org/tracker/joomla-cms/33105</a>.</sub>
