### ISSUE TITLE
[4.0] Resizing browser in Article Edit View causes the article preview text box to go blank

### ISSUE THREAD

**Issue by YatharthVyas** [joomla/joomla-cms#33101]
### Steps to reproduce the issue
1. Visit the Administrator Panel
2. From the sidebar, navigate to Content -> Articles
3. Open one Article in Edit mode
4. Resize the browser's **width** such that it crosses the **935px** mark

### Expected result
Nothing should happen to the text box.

### Actual result
![result](https://user-images.githubusercontent.com/53610833/114307680-61e99200-9afe-11eb-873b-6a63d0906447.gif)

### System information (as much as possible)
Google Chrome on Windows 10
Native Screen Resolution: 1920 x 1080
Screen Size: 15.6 inch

### Additional comments
This isn't a major issue and refreshing the page fixes it. 
Toggling the editor displays the HTML stringify-ed code but reverting back to the preview mode doesn't fix it.
A somewhat related issue was reported in https://github.com/joomla/joomla-cms/issues/24547 and was closed. 
Chrome console shows no errors/warnings

**Comment by Krshivam25** [comment]
By default, <input> and <textarea> elements don’t change size based on the content they contain. In fact, there isn’t any simple HTML or CSS way to make them do that. Kinda funny, as that seems like a reasonable use-case.

**Comment by brianteeman** [comment]
@Krshivam25 that may or may not be true but its completely irrelevant to the reported issue

**Comment by Quy** [comment]
Fixed in #34813.

**Comment by YatharthVyas** [comment]
Thank you
