### ISSUE TITLE
[4.0] Add highlighting several articles by shift button

### ISSUE THREAD

**Issue by Bond97** [joomla/joomla-cms#33119]
### Is your feature request related to a problem? Please describe.
I've testing PR #33100 and think, it's might be better add new function as described in title.

### Describe the solution you'd like

My feature request based on standard function on File Explorers on Windows OS or Linux OS.
When user need to highlight some articles, 7-10 or more, for example, it might be hard clicking on each button to highlight it.

Maybe it will be better to make this function - user highlight first article, then highlight last article holding the `Shift` button. 
So, all needed articles are highlited with 2 clicks on mouse.

### Additional context

I don't know, maybe that request are exist already. But in search on github I didn't find mention about it.

**Comment by brianteeman** [comment]
Is it the same as #25500  ?

**Comment by Bond97** [comment]
@brianteeman I think, yes. Do I need to close this issue?

**Comment by ghost** [comment]
Yes, should be closed to avoid duplicated issues.

**Comment by Bond97** [comment]
Ok, thanks!
