### ISSUE TITLE
3.9.26 update

### ISSUE THREAD

**Issue by peteruoi** [joomla/joomla-cms#33122]
Sorry if i am in a hurry. Is it normal that my sites can't find the updatE? Is it a cdn problem? Or do i just have to wait?

**Comment by Bond97** [comment]
I think, that it need some time, that CDN is updated.

You can always use manual update by following update package from github.

**Comment by peteruoi** [comment]
I know i can do a manual update. I just found it weird that both a site in america and in italy couldn't find the update after 10 minutes. And i saw something in the release notes about update (maybe totally irrelavant). When i see the update i'll close the issue asap :)

**Comment by peteruoi** [comment]
updates arrived!
Thank you all!!!
