### ISSUE TITLE
[4.0] Required Field problem with atum style

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33125]
### Steps to reproduce the issue
Open the Atum template style and delete the values for each of the inputs in the colour tab and then save

### Expected result
The style is saved and the default values from the xml are used. (this is how you get back to default after messing up your colours)

### Actual result
![image](https://user-images.githubusercontent.com/1296369/114621368-84b5ab00-9ca4-11eb-854b-c17dfdadaf0c.png)

Cannot save as there is a required field error. No field is displayed as required. No field is highlighted. checking the templatedetails.xml no field is set to be required there either

(this is tested with current 4.0dev branch)

**Comment by ghost** [comment]
Confirm the issue, result is: 

> ![grafik](https://user-images.githubusercontent.com/78906980/114656997-5c06d300-9cef-11eb-9380-a95666c21e99.png)

**Comment by brianteeman** [comment]
Must have been resolved elsewhere
