### ISSUE TITLE
Got error Invalid Login with 3.9.26 update

### ISSUE THREAD

**Issue by austre** [joomla/joomla-cms#33135]
I logged at adminsitrator area, start a Live Update or uploaded the 3.9.26 file.

Like other updates, i expect that should complete successfully. But, an error about Invalid Login comes out.

PHP 7.3
Apache 2
Debian 9.1
![image](https://user-images.githubusercontent.com/4764413/114793954-e0923980-9d61-11eb-988d-516ac98a2792.png)

**Comment by ChristineWk** [comment]
similar: #23201<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33135">issues.joomla.org/tracker/joomla-cms/33135</a>.</sub>

**Comment by austre** [comment]
Using Firefox update works, like @jikometrix said at https://github.com/joomla/joomla-cms/issues/23201#issuecomment-567050398

Thanks @ChristineWk
