### ISSUE TITLE
[4.0] Provide the Vote Plugin with a counter

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#33137]
### Steps to reproduce the issue

This is an improvement proposal. In the hope it wil be useful.

### Expected result

![screen shot 2021-04-15 at 06 35 47](https://issues.joomla.org/uploads/1/985d5a899345419319902abb11d628a3.png)

The plugin has a counter.
See the number of votes next to the stars.
In this case (4). Next case (5). And so on.

### Actual result

The plugin has NOT a counter

### Additional comments

Code: see file `rating.php` line 93

`<?php echo $img; ?>`
becomes
`<?php echo $img . '<span class="text-muted">  (' . $rcount . ')</span>'; ?>`

**Comment by ghost** [comment]
`Vote 5` looks like the user should give 5 stars. I would say that the info `(4)` is enough as user know that 5 comes after 4 ;-)

**Comment by sandewt** [comment]
To avoid a misunderstanding (4) has nothing to do with the number of stars.
At some point, for example, after 140 votes, the counter will indicate (140).

**Comment by sandewt** [comment]
Possible alternative:

![vote_after_2](https://user-images.githubusercontent.com/9271775/114831271-7adb9700-9dcd-11eb-954b-c1b8ce38ff99.png)

This means: rating_sum / rating_count = 14 : 4 = 3.5 stars

**Comment by sandewt** [comment]
Possible alternative (2):

![vote_after_3](https://user-images.githubusercontent.com/9271775/114835739-2dadf400-9dd2-11eb-987f-3d33d18ddfae.png)

**Comment by PhilETaylor** [comment]
PR https://github.com/joomla/joomla-cms/pull/33143

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33143 . Thanks in advance.
