### ISSUE TITLE
Backup On Update not working?

### ISSUE THREAD

**Issue by racingkars** [joomla/joomla-cms#33167]
### Steps to reproduce the issue
Update to new version

### Expected result
Making backup before updating

### Actual result
No backup made, just updating

### System information (as much as possible)
Linux on Qnap NAS

**Comment by alikon** [comment]
you should do it manually before update not a core issue

**Comment by racingkars** [comment]
Thnx, Then it's probably an Akeeba issue.... Sorry, i wasn't aware....
