### ISSUE TITLE
[4.0] Blog-View: Vote-Stars need padding

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33164]
### What needs to be fixed
- Install "Blog Sample Data", 
- enable vote-plugin having position `Top`or `Bottom`,
- enable in article options view vote,
- view menu `Blog`.

Top | Bottom
--- | ---
![image](https://user-images.githubusercontent.com/78906980/115993825-d29bae80-a5d4-11eb-9d13-f11e8e5021fa.png) | ![image](https://user-images.githubusercontent.com/78906980/115993671-1b069c80-a5d4-11eb-9356-60195994e4e0.png)

### Why this should be fixed
Both positions should have same padding.

### How would you fix it
Don't know.

### Side Effects expected
Don't know.

**Comment by ChristineWk** [comment]
If correct, I don't know, but temporary got spaces with:

div.content_rating img {
padding: 0.1rem;  
}
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33164">issues.joomla.org/tracker/joomla-cms/33164</a>.</sub>

**Comment by sandewt** [comment]
Related to:

#32919 | [4.0] css changes in voting plugin
#32914 | [4.0] Pagination set to bottom after voting<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33164">issues.joomla.org/tracker/joomla-cms/33164</a>.</sub>

**Comment by sandewt** [comment]
See line 84 file: ...\plugins\content\vote\tmpl\rating.php

Now
`<div class="content_rating" role="img" aria-label="<?php echo Text::sprintf('PLG_VOTE_STAR_RATING', $rating); ?>">`

Add the class`item-content`

`<div class="item-content content_rating" role="img" aria-label="<?php echo Text::sprintf('PLG_VOTE_STAR_RATING', $rating); ?>">`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33164">issues.joomla.org/tracker/joomla-cms/33164</a>.</sub>

**Comment by rjharishabh** [comment]
I am unable to reproduce this issue. Don't know what I am missing?

**Comment by ghost** [comment]
@sandewt can you please add #33337 to" in https://github.com/joomla/joomla-cms/issues/33164#issuecomment-825571773 as its also about vote if i understand your comment correct.

**Comment by sandewt** [comment]
>See line 84 file: ...\plugins\content\vote\tmpl\rating.php

@sandramay0905 

Oops, my suggestion does NOT work in the position: TOP
This results in two paddings.

![issue-vote](https://user-images.githubusercontent.com/9271775/116070728-43060680-a68d-11eb-906a-4f3450e12c50.png)

**Comment by rjharishabh** [comment]
I am not able to reproduce this issue. 
Don't know what I am missing?

**Comment by rjharishabh** [comment]
Please test #33340 with both scenarios #33164 and #33337.
Let me know from you.

**Comment by sandewt** [comment]
>I am not able to reproduce this issue.
Don't know what I am missing?

Empty your browser cache

**Comment by ghost** [comment]
@rjharishabh pull request #33340 didn't solve this issue.

**Comment by sandewt** [comment]
>I am not able to reproduce this issue.
Don't know what I am missing?

Oops I understand you, I am showing here that my proposal above does not work.

**Comment by rjharishabh** [comment]
I am getting this.

![voting](https://user-images.githubusercontent.com/61203226/116078346-1addce00-a6b4-11eb-8b3d-0eb846ce0027.JPG)

**Comment by sandewt** [comment]
>I am getting this.

True, but it doesn't work on top

**Comment by rjharishabh** [comment]
on top

![top vote](https://user-images.githubusercontent.com/61203226/116080459-ba03c500-a6b6-11eb-92ed-e53ebd3e072b.JPG)

**Comment by ghost** [comment]
@rjharishabh please look at blog-view, not article-view.

**Comment by rjharishabh** [comment]
@sandramay0905 
Can you share the page URL?

**Comment by ghost** [comment]
Sure, its the blog-menu of sample data: ~https://sandramay09051.joomla.com/en/blog.html~ (terminated)

**Comment by sandewt** [comment]
File line 95 - ... : \components\com_content\tmpl\category\blog_item.php

Move the div tag.

Change this 
```
</div>

<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
<?php echo $this->item->event->afterDisplayContent; ?>
```
To
```
<?php // Content is generated by content plugin event "onContentAfterDisplay" ?>
<?php echo $this->item->event->afterDisplayContent; ?>

</div>
```

I don't know if this change works fine everywhere.

**Comment by sandewt** [comment]
@sandramay0905 please test #33426

**Comment by ghost** [comment]
Close because of pull request #33426
