### ISSUE TITLE
[j4] media manage - article we can't add file or pdf

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#33171]
### Steps to reproduce the issue
setp 1 create an item
step 2 use joomla button to add element
step 3 try to add other thing than image ... PDF etc
we can't !!!

![image](https://user-images.githubusercontent.com/2539440/115105997-75fc1c00-9f62-11eb-9eff-a83050e28955.png)

we can't publish a cms without forgot this simple action !
For solution is :
- extend and rename image button
- adding a file button

![image](https://user-images.githubusercontent.com/2539440/115106034-b360a980-9f62-11eb-8553-e72eca865be2.png)
For me a issue blocker

**Comment by ghost** [comment]
@micker isn't it the same in your issue #31320?

**Comment by micker** [comment]
Ahhh yes i forgot it i will close it but Can you tag the old issue for me its a beta blocker

**Comment by ghost** [comment]
> Can you tag the old issue for me

What do you mean?

**Comment by richard67** [comment]
We don’t beta blockers anymore because J4 is already in beta phase.

And this or the older issue is for sure NOT a release blocker.

**Comment by richard67** [comment]
Closing as duplicate, details see previous comments.
