### ISSUE TITLE
[4b7] Parameter description "Connect Password" is duplicated (Authentication - LDAP)

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33175]
### Steps to reproduce the issue
Open the "Authentication - LDAP" plugin parameters, note that the description of the "Connect Password" parameter is duplicated.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/115119486-3e689080-9fb1-11eb-9e85-b9a43b48c19a.png)

**Comment by Quy** [comment]
Fixed in #32691. Thanks for the report. 

Please test using the nightly builds: https://developer.joomla.org/nightly-builds.html
