### ISSUE TITLE
[4.0] Files uploaded to templates with upper case extensions don't appear in folder tree.

### ISSUE THREAD

**Issue by particthistle** [joomla/joomla-cms#33179]
### Steps to reproduce the issue
- Prepare a file and have an uppercase file extension eg sample.PNG
- System > Site Templates (or Administrator Templates)
- Click on template to modify template files
- Click New File to upload the new file to the template

### Expected result
Uploaded file appears in the template folder tree so you can further perform actions on the file.

### Actual result
File is uploaded, and success message is displayed, but the file does not appear in the folder tree.
![image](https://user-images.githubusercontent.com/5515866/115143699-36315380-a08c-11eb-99bd-059df666ac96.png)

### Additional comments
Occurs with any file type where the extension is uppercase.

Though you can add the upper case extensions to your list of allowed extensions to fix it, this is not necessarily the best solution, and instead perhaps the extension needs to be converted to lower case on upload?

Discovered while testing https://github.com/joomla/joomla-cms/pull/33087

**Comment by ghost** [comment]
Upload 1.PNG show now:

> ![image](https://user-images.githubusercontent.com/78906980/116781353-91971480-aa82-11eb-8606-93de7b36bdba.png)

As user its hard to know that the file-extension has to be lowercase.

**Comment by brianteeman** [comment]
please test #34065

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34065 . Thanks in advance.

**Comment by brianteeman** [comment]
Please re-open

**Comment by richard67** [comment]
Re-opening as the pull request has been closed.

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/34095 should address this issue. Please test, thanks !
