### ISSUE TITLE
[3.9.26] Admin article search tools not displaying correctly and/or disappear

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#33172]
### Steps to reproduce the issue
Open Joomla admin in iPad
Navigate to articles - in Landscape mode
Tap down-arrow for 'Search Tools'

### Expected result
Where direct input is required (i.e. not a drop-down), would expect to see:
- Select Category -
- Select Access -
- Select Author -
- Select Tag -

### Actual result
The above only display '0 Items'
![iPad-admin-article-search-tools](https://user-images.githubusercontent.com/36987494/115110013-0e999880-9f71-11eb-854f-f08ef9672f10.jpg)

ALSO: on both iPad (portrait view) and Windows 10 desktop with a narrow browser window, the search tools close and there's no option to open them again:

![windows-narrow-browser](https://user-images.githubusercontent.com/36987494/115110062-4e608000-9f71-11eb-8a2f-53cf45ab856a.jpg)

### System information (as much as possible)
Joomla 3.9.26 (although the first screenshot shows 3.9.25, the issue remains)
PHP 7.3.27
Server LiteSpeed

iPad - 5th gen, software 14.42, Safari browser (up-to-date)
Desktop - Windows 10 Pro, Firefox (up-to-date)

**Comment by ghost** [comment]
Confirm issue #2: Admin article search tools disappear =< 767.

> ![image](https://user-images.githubusercontent.com/78906980/115246194-f454eb80-a125-11eb-9894-1ccfcafa00e7.png)

**Comment by Quy** [comment]
I cannot reproduce `0 items` using iPad Air 2 with OS 15.2.1.

**Comment by Quy** [comment]
Closing as non reproducible.
