### ISSUE TITLE
[4b8-dev] Images in the installation of the examples of Joomla! 4

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#33187]
Good morning all. I have been testing almost all versions of Joomla for some time now! 4. And I can never thank you enough for all your hard work. To make Joomla! 4 more modern and design how about using these images in the installation of the examples of Joomla! 4. I find the effect of his feminine faces very beautiful and above all it gives an effect of promise to Joomla !, a view of the future.

I can show you two Joomla! 4 with the two examples in line so that you can better imagine it.

![Home_J4_1](https://user-images.githubusercontent.com/26197929/115151823-ea23e600-a06e-11eb-9b17-8fd31e166143.jpg)
![Screenshot_2021-04-18 Blog](https://user-images.githubusercontent.com/26197929/115151916-4ab32300-a06f-11eb-883e-cd963a8dd9e4.png)

**Comment by richard67** [comment]
This is definitely not an issue. Moving to discussions.
