### ISSUE TITLE
[4b8-dev] Invalid field type in plugin "System - Page Cache"

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33183]
### Steps to reproduce the issue
Go to the "System - Page Cache" plugin parameters. Please note that the menu item exclusion field does not look correct.

I was expecting something like multiple choice like in other fields.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/115145554-d79fb180-a05a-11eb-9928-ad90202bb738.png)

### System information (as much as possible)
Joomla 4 Beta 8 Dev from 18 April 2021 02:00:22 UTC

**Comment by chmst** [comment]
Confirmed, field of type menuitem lets select multiple menuItems in J3.x

**Comment by ReLater** [comment]
Also doesn't work when I add
`layout="joomla.form.field.list-fancy-select"`

Maybe related issue: https://github.com/joomla/joomla-cms/issues/31249

**Comment by Fedik** [comment]
It looks correct, it display `<select multiple>` as it set in XML. The "fancy select" is optional thing.
However, to have a fancy select in this field need to fix `GroupedlistField`

And yes, it related to #31249, but of course not the same.

**Comment by Fedik** [comment]
Please test #34091
