### ISSUE TITLE
[4][PHP8] Directive track_errors which caused $php_errormsg to be available has been removed.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33185]
170 uses in Joomla 4 - mainly in libraries, 63 in upstream packages

https://www.php.net/manual/en/reserved.variables.phperrormsg.php

Version | Description
-- | --
PHP 8.0.0 | Directive track_errors which caused $php_errormsg to be available has been removed.
PHP 7.2.0 | Directive track_errors which caused $php_errormsg to be available has been deprecated.

<img width="448" alt="Screenshot 2021-04-18 at 15 58 15" src="https://user-images.githubusercontent.com/400092/115150120-e6886300-a05e-11eb-816e-81e941b02c1c.png">

**Comment by richard67** [comment]
So we should use `error_get_last()` and get the `'message'` element where we now use `$php_errormsg`, right?

**Comment by PhilETaylor** [comment]
docs comments also say:
> If an error handler (see set_error_handler ) successfully handles an error then that error will not be reported by this function.

so that will need testing too, 

Maybe something like this which we use for deprecated errors in libraries/bootstrap.php might work for Notice/Warnings - no idea - not tested - looks like a nicerway to handle warnings and errors and would allow us to remove all `@` suppression in Joomla 4?

`
set_error_handler(['Joomla\CMS\Exception\ExceptionHandler', 'handleUserDeprecatedErrors'], E_USER_DEPRECATED);
`
