### ISSUE TITLE
At default settings, Login Page w. Guest Access produces error "You Cannot View This Resource"

### ISSUE THREAD

**Issue by BartelBe** [joomla/joomla-cms#33195]
### Steps to reproduce the issue
Create a login page: Select -> users -> login unchained
Leave [default] settings unchanged
Set Access Level to Guest

### Expected result
User login should result error free

### Actual result
Malformed error message appears: 
×
Error
You are not authorised to view this resource.
Apart from the error message display, everything works as expected.

### System information (as much as possible)
PHP Built On 	Linux nlhb52619ds 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1 (2021-03-19) x86_64
Database Type 	mysql
Database Version 	5.5.5-10.3.27-MariaDB-0+deb10u1-log
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	7.4.16 and also on 8.0.3
Web Server 	Apache
WebServer to PHP Interface 	fpm-fcgi
Joomla! Version 	Joomla! 3.9.26 Stable [ Amani ] 13-April-2021 15:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:87.0) Gecko/20100101 Firefox/87.0 

### Additional comments
When setting the login page REDIRECTION to any existing website page, the login procedure happens CORRECTLY without throwing an error message.

**Comment by richard67** [comment]
@BartelBe Is it the same issue as #29161 ? If so, and I think it is, then it is expected behaviour. Please check the discussion in that issue and let us know if you are ok with it. If so, you or we can close this issue here. Thanks in advance.

**Comment by richard67** [comment]
P.S.: Especially this comment explains it well: https://github.com/joomla/joomla-cms/issues/29161#issuecomment-631135633

**Comment by BartelBe** [comment]
Right, same as #29161.  
All true, but for usability sake, you can avoid all the fuzz (for the webmaster without the thorough experienced based troubleshooting) by simply requiring to select a page, instead of defaulting to an error situation in case of guest access.
