### ISSUE TITLE
Frontend: "Edit Menu" open Module if "Edit Module" is set to "Administrator"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33199]
#### Backend
1. Open global configuration , set `Inline Editing` to `Modules & Menus`
2. Open module options, set `Edit Module` to `Administrator`
#### Frontend
1. Login, click on an `Edit menu item`-button
2. Module of this menu open in Backend

### Expected result
Menu open in backend

### Actual result
Module open in backend

### System information (as much as possible)
> ![image](https://user-images.githubusercontent.com/78906980/115345881-b8feff00-a1af-11eb-9e49-b2537ec9f2c8.png)

### Additional comments
If user change `Edit Module` to `Site` it works as expected.

**Comment by ghost** [comment]
In Joomla4 it works without this issue.

**Comment by richard67** [comment]
> In Joomla4 it works without this issue.

Good to know. Am curious if it still will work on J4 when the merge of changes from the 3.10-dev branch up to 4.0-dev will be finished in the next days.

I'll keep an eye on it.

**Comment by ChristineWk** [comment]
> 
> 
> > In Joomla4 it works without this issue.
> 
> Good to know. Am curious if it still will work on J4 when the merge of changes from the 3.10-dev branch up to 4.0-dev will be finished in the next days.
> 
> I'll keep an eye on it.

I'm not sure: Relevant? #30779
