### ISSUE TITLE
Joomla 4 - Main Menu drop down not working

### ISSUE THREAD

**Issue by zainimohd** [joomla/joomla-cms#33201]
### Steps to reproduce the issue

In Joomla 3 - Main Menu drop down was working
Once upgraded to Joomla 4, the Main Menu drop down no longer working.

Anyone else has this experience ?

**Comment by brianteeman** [comment]
Without further details its completly impossible to answer

**Comment by ChristineWk** [comment]
agree with @brianteeman 

Check this PR please: #32092, e.g. Layout settings etc.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33201">issues.joomla.org/tracker/joomla-cms/33201</a>.</sub>

**Comment by chmst** [comment]
Closing as there was no more information
