### ISSUE TITLE
Old version joomla 3.x throwing error

### ISSUE THREAD

**Issue by rangerlp** [joomla/joomla-cms#33202]
### Steps to reproduce the issue
I have an old Joomla version 3.4 I believe. I want to update but I'm getting this error:

Fatal error: Class Joomla\Registry\AbstractRegistryFormat contains 2 abstract methods and must therefore be declared abstract or implement the remaining methods (Joomla\Registry\AbstractRegistryFormat::objectToString, Joomla\Registry\AbstractRegistryFormat::stringToObject) in /home2/xxxxxx/public_html/apexthermal/libraries/vendor/joomla/registry/src/AbstractRegistryFormat.php on line 79

thanks for looking at this.

**Comment by brianteeman** [comment]
Please use the forum for support https://forum.joomla.org

**Comment by richard67** [comment]
@rangerlp You have to update in steps, see https://docs.joomla.org/J3.x:Upgrading_from_Joomla_3.4.x_to_3.5/en for details. And as said above, this here is for reporting bugs and not for asking support questions. You might find already answers in our forum,  https://forum.joomla.org , and if not, sign up if not done yet and ask there. Thanks for your understanding.
