### ISSUE TITLE
[4.0] Failed to initialize plugin: jdragndrop TypeError: r is not a constructor

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#33217]
Edit article. See Console.

 Failed to initialize plugin: jdragndrop TypeError: r is not a constructor
   tinymce.js:20061:25

**Comment by dgrammatiko** [comment]
@infograf768 browser?
Did you run `npm ci`?

**Comment by infograf768** [comment]
The test site was corrupted.
