### ISSUE TITLE
[4] 1Password injects into choicesjs/dropdowns

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33211]
### Steps to reproduce the issue

On the edit article screen of Joomla 4

https://user-images.githubusercontent.com/400092/115466122-87c21580-a227-11eb-938d-ff2ca4906c50.mp4

### Expected result

No injection of 3d party password vaults into select boxes

### Actual result

As per video. The 1Password.com apps inject into the select boxes. 

### System information (as much as possible)

Safari on mac.

### Additional comments

Posting here and also cross posting to 1Password Support directly as Im sure there is something both projects can do to improve this.

**Comment by brianteeman** [comment]
You might want to post it upstream to choicesjs as well

**Comment by Fedik** [comment]
well, here is nothing that we can do,
the browser extensions can hajack the site page as they want, and that what they did :smile:

**Comment by PhilETaylor** [comment]
There was loads that we could do and the reason that this issue was opened was so that we could collaborate with the upstream projects to resolve this and track its progress￼

I guess you're not interested in that which is sad.￼

**Comment by PhilETaylor** [comment]
https://1password.community/discussion/113698/how-to-stop-1password-x-suggesting-emails-in-a-form-field

**Comment by Fedik** [comment]
> we could collaborate with the upstream projects to resolve this and track its progress

Closing this issue does not stop anyone from collaborating with the upstream :wink: 
But it is clearly not a Joomla bug, and not even choicesjs issue.
