### ISSUE TITLE
[4.0] Backend: `Delete`-Button at 1st or 2nd place

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33215]
### What needs to be fixed
Delete a file in "media-manager" and in "template" show modal having `Delete`-Button in different place:

#### media-manager

> ![media-manager](https://user-images.githubusercontent.com/78906980/115529677-639c1e00-a293-11eb-8a30-a834d3efe3f5.png)

#### template

> ![template](https://user-images.githubusercontent.com/78906980/115529778-77478480-a293-11eb-9f8e-0469c8052cbd.png)

### Why this should be fixed
I guess buttons should be in same order.

### How would you fix it
Always first?

### Side Effects expected
Don't know.

**Comment by YatharthVyas** [comment]
Issue confirmed.

I was studying this issue and found that all the action buttons tend to be on the right side and the cancel button is towards the left. I've added a few examples below. My proposed solution would be to move the **delete button** to the **right** in media-manager

## Media Manager

![image](https://user-images.githubusercontent.com/53610833/115595246-52372e00-a2f4-11eb-8fa1-4ae0505f9709.png)
![image](https://user-images.githubusercontent.com/53610833/115595313-65e29480-a2f4-11eb-8a2c-1ddc4ccfefec.png)


## Template

![image](https://user-images.githubusercontent.com/53610833/115595539-ab9f5d00-a2f4-11eb-979f-9dec8b95b048.png)
![image](https://user-images.githubusercontent.com/53610833/115595605-be199680-a2f4-11eb-816b-4b5123837bd7.png)

**Comment by ghost** [comment]
Thanks @YatharthVyas for pull request #33221, closing issue.
