### ISSUE TITLE
[4.0] Codemirror multiple text area when modifying window size

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#33229]
### Steps to reproduce the issue
Select CodeMirror as default editor.
Create an article.

### Actual result

![whattheheck_codemirror](https://user-images.githubusercontent.com/869724/115675194-abcc4680-a34e-11eb-887d-ecfee7d73f0d.gif)

**Comment by ghost** [comment]
Confirm Issue, test on nightly build.

**Comment by brianteeman** [comment]
We had this reported before but it was in the template editor. Look for the PR that fixed it there and apply here

**Comment by ghost** [comment]
@brianteeman pull request #30241?

**Comment by brianteeman** [comment]
Yes thats the one

**Comment by infograf768** [comment]
Looks like indeed this solves the issue

```
diff --git a/build/media_source/plg_editors_codemirror/js/joomla-editor-codemirror.w-c.es6.js b/build/media_source/plg_editors_codemirror/js/joomla-editor-codemirror.w-c.es6.js
index ecef691..e99ae93 100644
--- a/build/media_source/plg_editors_codemirror/js/joomla-editor-codemirror.w-c.es6.js
+++ b/build/media_source/plg_editors_codemirror/js/joomla-editor-codemirror.w-c.es6.js
@@ -42,4 +42,10 @@
     const that = this;
 
+    // Check if instance exists to avoid duplication on resize
+    if (this.instance !== '') {
+      Joomla.editors.instances[this.element.id] = this.instance;
+       return;
+    }
+
     // For mode autoloading.
     window.CodeMirror.modeURL = this.getAttribute('mod-path');

```

**Comment by dgrammatiko** [comment]
That's not the correct solution since the problem is not in CodeMirror, a similar issue exists with tinyMCE #33101
The problem is that tabs are actually moving DOM elements when switching from tabs to accordion therefore the proper solution would be to fix the tabs to **not** move the DOM elements.

**Comment by PhilETaylor** [comment]
>  a similar issue exists with tinyMCE

> We had this reported before but it was in the template editor. 

The problem with the template editor, when using out of the box configuration (tinymce) still remains today unresolved.

**Comment by dgrammatiko** [comment]
> using out of the box configuration

What do you mean here? Can you provide an example?

**Comment by brianteeman** [comment]
I thought it was fixed as well but I can confirm its broken

![issue](https://user-images.githubusercontent.com/1296369/115771965-7b17fb80-a3a6-11eb-8d9d-dbeb478c6d8b.gif)

**Comment by dgrammatiko** [comment]
Yeah, that's from tabs and the stupid mode change to accordion. I shouldn't have pushed that stupid code...

**Comment by PhilETaylor** [comment]
Its been like this for quite some time... I reported it in 2018... https://github.com/joomla/joomla-cms/issues/22778

**Comment by infograf768** [comment]
So... What now?

**Comment by Quy** [comment]
Please test PR #34813
