### ISSUE TITLE
3.9.26 won't install

### ISSUE THREAD

**Issue by dagroupinc** [joomla/joomla-cms#33224]
### Steps to reproduce the issue
Tried installing 3.9.26 manually (upload and extract) as well as with softoculous (automated install by hosting provider) and can't get to the Joomla installation screen.

### Expected result
Joomla Installation screen

### Actual result
**Manual Install Error Message:**
Error: Call to undefined function Joomla\CMS\Language\simplexml_load_file(): Call to undefined function simplexml_load_file()
**Soctoculous Install Error Message:**
Warning: session_start(): Failed to read session data: user (path: /tmp) in /home2/dagroup/public_html/new4/libraries/joomla/session/handler/native.php on line 260
Error: Failed to start application: Failed to start the session

### System information (as much as possible)
**Database server:**
Server version: 5.6.41-84.1 - Percona Server (GPL), Release 84.1, Revision b308619
**Web server:**
Database client version: libmysql - 5.6.43
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 7.3.27

### Additional comments
The hosting provider hasn't been able to provide a solution

**Comment by ChristineWk** [comment]
I don't know your server and not experienced with server etc. 

1st one maybe: https://techglimpse.com/undefined-function-simplexml_load_file-php/

2nd one: Check database data with your configuration.php:

public $dbtype = 'mysqli';
	public $host = 'hostname';
	public $user = 'username';
	public $password = 'password';
	public $db = 'databasename';<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33224">issues.joomla.org/tracker/joomla-cms/33224</a>.</sub>

**Comment by dagroupinc** [comment]
1) yes have verified that simplexml is installed
2) yes also checked the configuration.php file

It's weird that the hosting provider's 'easy install' presents an error also and doesn't present the Joomla install screen.

**Comment by brianteeman** [comment]
easy install - not easy upgrade ;)

**Comment by dagroupinc** [comment]
Brian—agreed. I've never used it for that reason alone but this time we did as a test to see if we could get it to install — No go so I guess that points to a server side issue? Maybe a 3.9.26 clean install issue? I've successfully **updated** all of our other Joomla sites to 3.9.26 but this is a new installation.

**Comment by ChristineWk** [comment]
Ah, I see now: https://docs.joomla.org/Installing_Joomla_using_an_Auto_Installer

Believe me, it's not fantastic :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33224">issues.joomla.org/tracker/joomla-cms/33224</a>.</sub>

**Comment by ReLater** [comment]
> yes also checked the configuration.php file

Maybe I misunderstand that(?)
If there's already a configuration.php in Joomla root it's the expected bahavior that you don't get an installation screen.

**Comment by dagroupinc** [comment]
There is only one config file that was installed when we unzipped Joomla

**Comment by ReLater** [comment]
There shouldn't be a file `configuration.php` (exactly named like that) in the directory where you extracted the Joomla package. It blocks the installation routine. `configuration.php` will be created during installation.

**Comment by dagroupinc** [comment]
We typically remove that after completing the installation.

Additional information: We had a 3.9.25 install running on PHP 5.4 — when we updated PHP to 7.3 everything went south. Now we can't install anything no matter the PHP version.

**Comment by ReLater** [comment]
> We typically remove that after completing the installation.

Becomes more confusing now.

If you remove  `configuration.php`  AFTER installation Joomla won't work. It's an essential file.

I talked about the situation BEFORE you install Joomla via browser.

**Comment by dagroupinc** [comment]
the config file is in the directory - web hosting believes it is a server-side issue.

**Comment by ReLater** [comment]
Maybe a misunderstanding. Extracting is a step before starting the installation for me.

Extract the ZIP package: A file named `configuration.php` is "forbidden" in the folder.

Then comes the installation in the browser and the file is created AUTOMATICALLY in the end. And never should be removed (or moved without deeper skills).

**Comment by ReLater** [comment]
> the config file is in the directory 

When you talk about "config file" do you mean configuration.php?

If you extract an official Joomla-3.9.26 in an empty folder there is no configuration.php.

**Comment by dagroupinc** [comment]
Yes—we have been installing Joomla for 12 years. In this case, following our unzipping of Joomla and database configuration we do NOT get the Joomla install screen—instead, we get the following error message:

Error: Call to undefined function Joomla\CMS\Language\simplexml_load_file(): Call to undefined function simplexml_load_file()

• All our problems began after we updated a 3.9.25 Joomla site from PHP 5.4 to 7.3
• We get a similar error message if we auto install with softoculous.
• Yes config = configuration.php file (note Joomla doesn't create a configuration.php when you unzip—only during Joomla installation process)
• Hosting provider has verified that simplexml is installed

**Comment by PhilETaylor** [comment]
> Error: Call to undefined function Joomla\CMS\Language\simplexml_load_file(): Call to undefined function simplexml_load_file()

Simple. the php-xml package is NOT installed for the PHP version actually running. 

> Hosting provider has verified that simplexml is installed

Webhosts lie. Repeatedly. To cover their incompetence. 

Upload a file with `<?php phpinfo(); ` in it, and then look for XML in that - you will see that its not there... then tell your webhost to install php-xml package for your PHP version. 

If you are using a cPanel based server - then it might also be that you have not selected this PHP Extension for your account, even though "its installed" on the server.

**Comment by PhilETaylor** [comment]
> Warning: session_start(): Failed to read session data: user (path: /tmp) in  /home2/dagroup/public_html/new4/libraries/joomla/session/handler/native.php on line 260
Error: Failed to start application: Failed to start the session

This is a bad error message that confuses. However the REAL PROBLEM you have if you get this error message is that PHP/Joomla cannot communicate to your database server with the credentials provided. 

Neither of these issues are something to fix in Joomla core and so this should move to the Joomla Forum for support issues.

**Comment by dagroupinc** [comment]
> Simple. the php-xml package is NOT installed for the PHP version actually running.

PhilETaylor — can you provide details on how to resolve this?

**Comment by PhilETaylor** [comment]
No. Every webhost will have their own way, every web control panel will have their own way, web hosts that dont expose this to users will have to install it for you - you need to talk to your webhost, this is not a Joomla issue. 

The simple fact is that your server doesn't meet the [minimum system requirements for Joomla](https://downloads.joomla.org/technical-requirements).

**Comment by dagroupinc** [comment]
PhilETaylor— Could this be the source of the issue (note that the loaded configuration files is 70 and 73 is the versiion running:

**Configuration File (php.ini) Path** | /opt/cpanel/ea-php73/root/etc
**Loaded Configuration File** | /opt/php70/lib/php.ini

**Comment by brianteeman** [comment]
> you need to talk to your webhost,

**Comment by dagroupinc** [comment]
LOL that doesn't seem to be helpful at the moment. If I knew exactly what the problem and fix was—then I could push and make some headway.

Instead, I wait for days.

**Comment by brianteeman** [comment]
Phil has told you exactly what the problem is and how to resolve it

**Comment by brianteeman** [comment]
@quy please close as not a joomla bug

**Comment by dagroupinc** [comment]
I'll shut up but the hosting provider does meet the minimum requirements for php, mysql, and apache.

**Comment by Quy** [comment]
Please ask help in [Joomla Forum](https://forum.joomla.org/). Thanks.
