### ISSUE TITLE
[4.0] Alt in image modal

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33232]
Use the xtd editor image button in an article.
Click on an image
Observe that the Alt text button appears
Click on the pencil to edit the image
Observe that the Alt text button obscures some of the toolbar (redesigned in ##33231)
The Alt text button should not be present on this view

![issue](https://user-images.githubusercontent.com/1296369/115699148-4d5a9480-a35d-11eb-9484-b80b2997428f.gif)

**Comment by ghost** [comment]
Issue confirmed, test on nightly build.

**Comment by brianteeman** [comment]
alt is still present but moved and is less obtrusive
