### ISSUE TITLE
[4][FTP Layer] Cannot save template file modifications

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33239]
### Steps to reproduce the issue

Install Joomla 4 on a server that requires the use of the FTP Layer (see #31857)

Navigate System -> Site Templates -> Cassiopeia Details and Files -> index.php

Click Save

### Expected result

File is saved.

### Actual result

FTP logs a tmp file upload:

```
Thu Apr 22 16:58:25 2021 [pid 75051] CONNECT: Client "::ffff:127.0.0.1"
Thu Apr 22 16:58:25 2021 [pid 75050] [www-ftp] OK LOGIN: Client "::ffff:127.0.0.1"
Thu Apr 22 16:58:25 2021 [pid 75052] [www-ftp] OK UPLOAD: Client "::ffff:127.0.0.1", "/tmp/bb2fa7e9933b1b1096cd4ee9a625476e", 0.00Kbyte/sec
Thu Apr 22 16:58:25 2021 [pid 75052] [www-ftp] OK DELETE: Client "::ffff:127.0.0.1", "/tmp/bb2fa7e9933b1b1096cd4ee9a625476e"
```

The ACTUAL index.php file is NOT written/updated

Then there is a yellow warning (ignore the red warning - that is from https://github.com/joomla/joomla-cms/issues/33238) 

<img width="787" alt="Screenshot 2021-04-22 at 17 59 33" src="https://user-images.githubusercontent.com/400092/115754955-ae518f00-a394-11eb-8617-9c2fce1985b2.png">

NOTE the permissions are read with `Path::getPermissions($filePath)` which DOESNT take into account the FTP Layer

NOTE that saving is also failing because of another `is_writable` call
https://github.com/joomla/joomla-cms/blob/16f08f1d4bb84ca8528d37bd506b15974a925450/administrator/components/com_templates/src/Model/TemplateModel.php#L999

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/33079#issuecomment-816889839

**Comment by PhilETaylor** [comment]
Following [the projects decision to remove the FTP Layer](https://github.com/joomla/joomla-cms/pull/33390#issuecomment-830000434) from Joomla 4 - this can now be closed.
