### ISSUE TITLE
[4.0] Frontend: "Edit Module"-Button float away if module style is not "card"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33233]
### Steps to reproduce the issue
1. Login at frontend,
2. Change module-style to `html5` and save.

#### Examples
Inherited | html5
---- | ----
![Bildschirmfoto 2021-04-22 um 12 58 46](https://user-images.githubusercontent.com/78906980/115703890-f1970800-a36a-11eb-93b9-f85975a16de2.png) | ![Bildschirmfoto 2021-04-22 um 12 30 54](https://user-images.githubusercontent.com/78906980/115703932-fe1b6080-a36a-11eb-9915-acf3eb28adc2.png)
![Bildschirmfoto 2021-04-22 um 12 59 02](https://user-images.githubusercontent.com/78906980/115704127-463a8300-a36b-11eb-8f78-d2e1aa0d8738.png) | ![Bildschirmfoto 2021-04-22 um 12 32 10](https://user-images.githubusercontent.com/78906980/115704143-4cc8fa80-a36b-11eb-885e-4842c6ccf194.png)

### Expected result
"Edit Module"-button stay at same position.

### Actual result
"Edit Module"-button change position.

### System information
![image](https://user-images.githubusercontent.com/78906980/115704589-d973b880-a36b-11eb-8864-e5c041a6d4a3.png)

### Additional comments
Styles `Inherited` and `Cards` works as expected. Related pull request #32757.

**Comment by richard67** [comment]
@rdeutz As you had fixed these buttons with PR #32757 : Do you have an idea what could be the reason that it doesn't work e.g. with the html5 module style? Or is that more an issue with CSS priorities, something for @drmenzelit ?

**Comment by drmenzelit** [comment]
The "problem" is that the class `card` has a position `relative` defined, modules with other chromes has no position defined. There are a lot of combinations: different styles (html5, none...) and different module tags (article, aside....). So we have to find a way to define position `relative` to all elements inside a module.
