### ISSUE TITLE
[4.0] Menu item type wrapper setback.

### ISSUE THREAD

**Issue by frostmakk** [joomla/joomla-cms#33235]
After merging of #32342 it is no longer possible to use relative paths in the URL field of the Iframe wrapper.
This is a major deterioration of the wrappers usefulness.

Nightly Build 4.0.0-beta8-dev-Development-Full_Package.zip Thursday, 22 April 2021 02:00:57 UTC

**Comment by brianteeman** [comment]
What is your use case for wrapping a link on your own site inside itself?

**Comment by frostmakk** [comment]
To show something not made with Joomla inside an Iframe in Joomla.

**Comment by brianteeman** [comment]
So why not use the real url?

**Comment by frostmakk** [comment]
That has to be changed when the site is moved to localhost or anywhere else?
That is not good coding practice.

**Comment by reburg67** [comment]
In the Iframe Wrapper module it is still possible to set a relative URL without using `http://`.
But it is not possible in an Iframe Wrapper Menu Item. I see no logic in that.
Although I set the option "Auto Add" to false, `http://` is automatically added. Therefore I cannot use the same site on my production server and on the test environment. Please change this behaviour.

**Comment by chmst** [comment]
Closing as there is a PR. Please test https://github.com/joomla/joomla-cms/pull/37547

**Comment by Skrol29** [comment]
Local links (in iFrame and other) are useful when Joomla is part of a packaged solution.
So I confirm this was a problem for us too.

Glad you have fixed this problem !
Thank you,<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33235">issues.joomla.org/tracker/joomla-cms/33235</a>.</sub>
