### ISSUE TITLE
[4][FTP Layer] use of is_writable when FTP Layer needed causes false error messages

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33238]
### Steps to reproduce the issue

Install Joomla 4 on a server that requires the use of the FTP Layer (see #31857)

Go to Joomla Global Config and save

### Expected result

When checking if folder paths are writable, consideration should be given to the FTP Layer status. 

Global configuration is saved 
Green feedback message

### Actual result

ApplicationModel.php uses `is_writable` to check paths, which returns false (as FTP is needed to write to folders!) 
https://github.com/joomla/joomla-cms/blob/77522078cafd994963b50d7867dd90a8c766519d/administrator/components/com_config/src/Model/ApplicationModel.php#L752

<img width="619" alt="Screenshot 2021-04-22 at 17 42 41" src="https://user-images.githubusercontent.com/400092/115752819-63cf1300-a392-11eb-8933-50d01df1755d.png">

**Comment by PhilETaylor** [comment]
This also effects the Template manager because in TemplateModel.php there is another `is_writable`

https://github.com/joomla/joomla-cms/blob/77522078cafd994963b50d7867dd90a8c766519d/administrator/components/com_templates/src/Model/TemplateModel.php#L395

<img width="969" alt="Screenshot 2021-04-22 at 17 57 10" src="https://user-images.githubusercontent.com/400092/115754516-2c616600-a394-11eb-80ae-d16b9b6780f0.png">

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/33079#issuecomment-816889839

**Comment by PhilETaylor** [comment]
56 occurrences of `is_writable` to manually review... to ensure each use is FTP Aware... 

<img width="787" alt="Screenshot 2021-04-22 at 18 07 20" src="https://user-images.githubusercontent.com/400092/115755808-a5ad8880-a395-11eb-9c9c-9a1d6a3d8f0f.png">

**Comment by brianteeman** [comment]
Dont waste your time

**Comment by PhilETaylor** [comment]
Im documenting the issues ... that's all... then no one can say it was not tested... 

Easier to make a decision based on facts then... although good decisions are slow it seems...

**Comment by brianteeman** [comment]
@PhilETaylor before you go any further can you see if any of this is possible in J3. I don't believe it is as it failed when I tried. If that is correct then its even more of a waste of time to implement something in J4 if no one is currently using it

**Comment by PhilETaylor** [comment]
that was my plan after food later :)

**Comment by richard67** [comment]
I've put the FTP layer on the agenda for our JBS meeting tomorrow, and maybe our team lead can carry that to the PLT to discuss it there again.

**Comment by brianteeman** [comment]
So another month delay then :(

**Comment by richard67** [comment]
I want the opposite, I want to speed up decision and not cause another delay.

**Comment by richard67** [comment]
I.e. nobody should wait for that. But we should soon re-evaluate if we really need to keep the FTP layer and drop it if we can.

**Comment by brianteeman** [comment]
We have to wait. If the decision is to remove it then why waste time fixing something no one uses

**Comment by brianteeman** [comment]
and its been on the release blocker list for 3 years
