### ISSUE TITLE
[4][FTP Layer] Filesystem based Sessions do not work.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33237]
### Steps to reproduce the issue

Install Joomla 4 on a server that requires the use of the FTP Layer (see https://github.com/joomla/joomla-cms/pull/31857)

Go to Joomla Global Config and set Session Handler to be filesystem 

### Expected result

Sessions work as normal. 

### Actual result

The /var/www/html/sessions folder is created with 755 permissions. configuration.php is saved over FTP correctly. 

FTP Log:
```
Thu Apr 22 16:35:26 2021 [pid 24478] [www-ftp] OK LOGIN: Client "::ffff:127.0.0.1"
Thu Apr 22 16:35:26 2021 [pid 24480] [www-ftp] OK MKDIR: Client "::ffff:127.0.0.1", "/var/www/html/sessions"
Thu Apr 22 16:35:26 2021 [pid 24480] [www-ftp] OK CHMOD: Client "::ffff:127.0.0.1", "/var/www/html/sessions 755"
Thu Apr 22 16:35:26 2021 [pid 24480] [www-ftp] OK UPLOAD: Client "::ffff:127.0.0.1", "/var/www/html/configuration.php", 3574 bytes, 10873.00Kbyte/sec
```

No files are seen in that folder

next page load gives error message:

<img width="1412" alt="Screenshot 2021-04-22 at 17 35 54" src="https://user-images.githubusercontent.com/400092/115751814-739a2780-a391-11eb-96d7-b63f3e6ab71f.png">

### Additional comments

**If I manually 777 the /var/www/html/sessions folder then the page can load.**

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/33079#issuecomment-816889839

**Comment by PhilETaylor** [comment]
Following [the projects decision to remove the FTP Layer](https://github.com/joomla/joomla-cms/pull/33390#issuecomment-830000434) from Joomla 4 - this can now be closed.
