### ISSUE TITLE
[4] Edit article options screen facepalm

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33240]
### Steps to reproduce the issue

What have we done to deserve this... 

A list of "options" not A-Z, not sectioned, just almost in a random list 100% wide 

### Expected result

Not this. Not 1 column of 100% width select boxes... come one... we are better than this... 

### Actual result

<img width="1591" alt="Screenshot 2021-04-22 at 18 09 10" src="https://user-images.githubusercontent.com/400092/115756341-04730200-a396-11eb-9402-d3fc1f78eae3.png">

### System information (as much as possible)

Safari on mac

**Comment by brianteeman** [comment]
#32874
