### ISSUE TITLE
[4][FTP Layer] Folder Permissions screen incorrect states folders are unwritable.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33245]
### Steps to reproduce the issue

Install Joomla 4 on a host that requires the use of the FTP Layer.

This screen should take into account if the FTP Layer is enabled, and report if a folder is unwritable ONLY if its unwritable when tested using the FTP Layer.

It makes no sense to report the folder Unwritable, when infact it is writeable by the `Filesystem` API class if the FTP credentials are correct. 

### Actual result

<img width="1367" alt="Screenshot 2021-04-22 at 18 41 24" src="https://user-images.githubusercontent.com/400092/115761551-5ae23f80-a39a-11eb-8314-22e911441e19.png">

**Comment by brianteeman** [comment]
If my memory is correct this screen has always been this way

**Comment by PhilETaylor** [comment]
Doesn't mean its right though :)

**Comment by brianteeman** [comment]
I was making an observation
