### ISSUE TITLE
[4.0] Blog sample data: Description say "a workflow" will be installed

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33257]
### Steps to reproduce the issue
Last version of blog sample data don't install a workflow, but description is:

> ![Ohne Titel](https://user-images.githubusercontent.com/78906980/115834411-7cccd800-a415-11eb-9d96-3fd093f8ce09.png)

### Expected result
Description show correct informations.

### Actual result
Description show incorrect information.

### System information
![grafik](https://user-images.githubusercontent.com/78906980/115818233-a299b300-a3fc-11eb-90b1-2f02ef8a17b5.png)

**Comment by brianteeman** [comment]
It is installed it is just not enabled by default.

**Comment by ghost** [comment]
Thanks @brianteeman i had the message understand wrong.
