### ISSUE TITLE
[4] Far too easy to delete recursively a folder with all the files it contains with no warning 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33252]
### Steps to reproduce the issue

Navigate to System -> Site Templates -> Cassiopeia Details and Files -> manage folders

Select a folder - click delete

### Expected result

At least a warning... 

### Actual result

https://user-images.githubusercontent.com/400092/115772459-0beed700-a3a7-11eb-8fae-0b63bbc4178d.mp4

**Comment by Quy** [comment]
Duplicate #30973?

**Comment by PhilETaylor** [comment]
I guess great minds think alike ;-0
