### ISSUE TITLE
[4] Message on failed sending email during registration has strange concat of phrases.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33271]
### Steps to reproduce the issue

Try to register on the frontend of Joomla 4 when mail is not set up - so that the registration mail fails. 

The site admin gets a "Private Message" telling them that the email was not sent. 

The message of that private message has some weird concat of sentences. 

### Expected result

"An error was encountered when sending the user registration email. The user who tried to register is: adam"

### Actual result

"An error was encountered when sending the user registration email. The error is: The user who tried to register is: adam"

<img width="934" alt="Screenshot 2021-04-23 at 20 56 48" src="https://user-images.githubusercontent.com/400092/115923636-702c9c00-a476-11eb-81b7-45715a604808.png">

**Comment by alikon** [comment]
please test #33276
