### ISSUE TITLE
[4.0] Error: parts is null. Undefined

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#33277]
### Steps to reproduce the issue
Firefox Macintosh
Browse backend pages. Look at console.

This error displays, apparently at random.

<img width="1565" alt="Screen Shot 2021-04-24 at 09 16 39" src="https://user-images.githubusercontent.com/869724/115950830-e3b5c400-a4dd-11eb-9705-bce1886ab181.png">

**Comment by dgrammatiko** [comment]
It's from debugbar (probably, can't replicate it here) either the `languagestrings` or the `sqlqueries`:
![Screenshot 2021-04-24 at 20 37 46](https://user-images.githubusercontent.com/3889375/115969437-370b2f00-a53d-11eb-9e6b-6b791399e7e9.png)

**Comment by infograf768** [comment]
This happens even when debug is not enabled.

**Comment by dgrammatiko** [comment]
Next time it happens can you post what's in your localStorage and sessionStorage ?

**Comment by brianteeman** [comment]
I guess this never happened again and can be closed

**Comment by brianteeman** [comment]
can be closed please
