### ISSUE TITLE
[4.0] Backend: Change Language to German show HTML-Code

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33280]
### What needs to be fixed
After change to german:

> ![image](https://user-images.githubusercontent.com/78906980/115956723-b4fc1580-a4fe-11eb-8162-4921a6f14767.png)

### Why this should be fixed
There should no html be shown

### How would you fix it
Use correct syntax.

### Side Effects expected
No

**Comment by brianteeman** [comment]
Probably/Possibly a typo in the german language files. @tecpromotion can you check please

**Comment by dgrammatiko** [comment]
> There should no html be shown

This is probably a side effect of the HTML sanitization. Probably some German language string contains illegal HTML

**Comment by tecpromotion** [comment]
Thanks. Will check and fix.

**Comment by chmst** [comment]
Closing as it is for German language only

**Comment by tecpromotion** [comment]
@sandramay0905 please use the latest release https://github.com/joomlagerman/joomla/releases/tag/4.0.0v1-beta7
It no longer contains HTML. Switching without installing the German language package or installing completely in German will load an outdated language package.

**Comment by ghost** [comment]
@tecpromotion i use a fresh installation by launch.joomla.org + 3 languages (french, german, persian) and after switch backend language from english to german i got today the same issue.

**Comment by tecpromotion** [comment]
@sandramay0905 unfortunately, this is not yet possible at this point in time. Language packages still have to be installed under Joomla 4. When switching, only an old Joomla 3 package is accessed.

**Comment by infograf768** [comment]
The error comes from using wrong double quotes. Instead of straight double quotes, we have curly double quotes.
Weirdly enough, it does not show in 3.9

we should have  
`COM_LANGUAGES_MSG_DEFAULT_LANGUAGE_SAVED="[...]/<span style=\"text-decoration: underline; color: red;\">[...]"
`
But we have
`<span style=\“text-decoration: underline; color: red;\“><strong>Warnung:</strong></span>`

@tecpromotion : I suggest to release a corrected 3.9.26.2 pack.

**Comment by infograf768** [comment]
@sandramay0905
German pack has been updated and issue corrected.

**Comment by ghost** [comment]
Thanks @infograf768. I was coming here cause i have seen it at this moment and wanted to report :-)
