### ISSUE TITLE
[4] Toolbar::versions(): Argument #2 ($itemId) must be of type int, null given

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33289]
### Steps to reproduce the issue

Install Joomla 4
Trash all your Content Categories (Including the default uncategorised) 
Attempt to create a new article. 

### Expected result

Ability to create a new article or a warning that you need to create at least one category first. 

### Actual result

```
An error has occurred.
    0 Joomla\CMS\Toolbar\Toolbar::versions(): Argument #2 ($itemId) must be of type int, null given, called in /application/administrator/components/com_content/src/View/Article/HtmlView.php on line 209 
```

<img width="1588" alt="Screenshot 2021-04-24 at 20 21 09" src="https://user-images.githubusercontent.com/400092/115970503-9fa4dc80-a53a-11eb-90cc-00c304d8ac53.png">

**Comment by dgrammatiko** [comment]
> (Including the default uncategorised)

The form shouldn't even load if there are no categories. The existence of at least one category is dictated by the architecture and honestly, I m quite impressed that you're the first one finding this bug after 15 years...

fwiw I would throw an error if the categories count is 0 for the given component. My 2c

**Comment by PhilETaylor** [comment]
I only deleted all of my categories to get a blank state for testing of the new blank slate feature 🤦‍♂️

I am probably the first person ever to delete all of their categories, including the default category that is added when you install Joomla

**Comment by ReLater** [comment]
That's a bug only in Joomla 4.

When there's no category in Joomla 3 a category "Uncategorised" is created automatically when you create the first article.

**Comment by brianteeman** [comment]
What is happening in J3 is that the category is being created on the fly

**Comment by PhilETaylor** [comment]
[4] Only show versions toolbar button if the article has been saved at least once #33412
