### ISSUE TITLE
Joomla 4 - cassiopeia - collapsible navbar interfers with some menu modules

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#33293]
### Steps to reproduce the issue

Add a 3rd part menu module to site.
Such as MenuCk
maximenuck-pro_9.1.11.zip
mobilemenuck-pro_1.3.3.zip

### Expected result

When viewed on PC as window width is reduced except the mobile menu burger bar image to kick in.

### Actual result

Something else kicks in and messed up what MenuCK is trying to do.
Turns out it its the bootstrap collapse code in the cassiopeia temlate (index.php and error.php).

### System information (as much as possible)

Joomla 4 Beta 7
PHP 7.4

### Additional comments

I suggest![screen shot 2021-04-25 at 08 25 48](https://issues.joomla.org/uploads/1/70a0177315d8353948dc518131c608a2.png) a 'collpsiblenavbar' option be added to cassiopeia.
```
if ($this->params->get('collapsiblenavbar', 1)) :
    HTMLHelper::_('bootstrap.collapse', '.navbar-toggler');
    ?>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-bs-toggle="collapse" data-bs-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="<?php echo Text::_('TPL_BFUKCASSIOPEIA_TOGGLE'); ?>">
        <span class="icon-menu" aria-hidden="true"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
        <jdoc:include type="modules" name="menu" style="none" />
    </div>
    <?php
else :
    ?>
    <div id="navbar">
        <jdoc:include type="modules" name="menu" style="none" />
    </div>
    <?php
endif;
```

**Comment by BrainforgeUK** [comment]
For those confused by the image location in above ... I wrote -

I suggestscreen a 'collpsiblenavbar' option be added to cassiopeia.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33293">issues.joomla.org/tracker/joomla-cms/33293</a>.</sub>

**Comment by dgrammatiko** [comment]
> I sugges a 'collpsiblenavbar' option be added to cassiopeia.

The functionality doesn't even belong to the template, it's the menu' module responsibility. At the end of the day, templates should only compose the component of the current route and all the modules that are enabled for that route...
