### ISSUE TITLE
[4] Messages do not replace, they append

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33306]
### Steps to reproduce the issue

Joomla 4 -> Content -> Media

Click Delete
Click Delete
Click Delete
Click Delete
Click Delete
Click Delete

### Expected result

One message, that is replaced each time. 

### Actual result

Multiple messages appended each time

<img width="633" alt="Screenshot 2021-04-25 at 14 27 08" src="https://user-images.githubusercontent.com/400092/115995222-54d6a380-a5d2-11eb-9cd8-1f1979579469.png">

### Additional comments

Paging @dgrammatiko

**Comment by dgrammatiko** [comment]
> Multiple messages appended each time

Com_media needs multiple messages whenever an action is applied with a payload of 1+n files. Probably the code can be refactored for the single file. But in this case, it is just a case that the `Joomla.renderMessages()` is called with the wrong arguments (we can clear the old messages, default is not to iirc)

**Comment by dgrammatiko** [comment]
This should be closed as the behaviour has been fixed

**Comment by richard67** [comment]
Closing as stated above. Feel free to re-open if this is wrong.
