### ISSUE TITLE
[4] Post Installation Messages Hide/Reset is not Component Aware. 6 Problems.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33307]
### Steps to reproduce the issue

Install Joomla 4.0-dev
Run this SQL to add a fake post installation message (change the db prefix!) 

```sql
INSERT INTO `o07n8_postinstall_messages` (`postinstall_message_id`, `extension_id`, `title_key`, `description_key`, `action_key`, `language_extension`, `language_client_id`, `type`, `action_file`, `action`, `condition_file`, `condition_method`, `version_introduced`, `enabled`)
VALUES
	(99, 210, 'TEST', 'TEST', '', 'com_cpanel', 1, 'message', '', '', '', '', '4.0.0', 1);
```

Visit the Post Installation Message screen and follow through:

 - Load page, note its Joomla CMS in the dropdown and you see its messages shown
 - Select Atum Administrator template from the drop down - see there is one message
 - While we are on the "Atum Administrator template" selected page, click Hide all messages button
 - Note the page reloads back to the Joomla CMS page and all the Joomla CMS Messages are HIDDEN **(Problem 1).**
 - Select Atum Administrator template from the drop down - see there is one message (**Problem 2**, it should have been hidden)
 - While we are on the "Atum Administrator template" selected page, click Hide this message button
 - Note that we are now showing messages for Joomla CMS and not "Atum Administrator template" **(Problem 3)** 
 - Select Atum Administrator template from the drop down - see there is no message (Correct). 
 - Click RESET MESSAGES 
 - Note that we are now showing messages for Joomla CMS and not "Atum Administrator template" **(Problem 4)**
 - Note that we are now showing messages for Joomla CMS, when we reset messages for "Atum Administrator template" **(Problem 5)**  
 - Select Atum Administrator template from the drop down - see there is no message **(Problem 6 - they were reset so should be showing!).** 

### Expected result

The reset and the hide all messages should be taking into account the value in the drop down and only modifying the messages for that component, and then redirecting back to the correct page with the same component in the dropdown

### Actual result

if you have more than one component in the dropdown, the hide/reset buttons on any other page other than Joomla CMS page, only reset and hide the messages for Joomla CMS, and you land back on the Joomla CMS page. The hide/reset buttons when pressed on other components pages (when other component is selected in the dropdown) do not effect the currently selected component. 

### System information (as much as possible)

safari on mac but probably unrelated to browser.

### Additional comments

Probably broken on Joomla 3 too - not tested.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33338 . Thanks in advance.
