### ISSUE TITLE
Carousel BS5 doesnt works 

### ISSUE THREAD

**Issue by web-eau-net** [joomla/joomla-cms#33305]
### Steps to reproduce the issue
1. Create a custom HTML module
2. Copy/paste any BS5 carousel example code in it
3. Publish the module 

### Expected result
The carousel must work on frontend

### Actual result
The carousel doesnt works

### System information (as much as possible)
Joomla 4.0.0-beta8-dev
Opera 75.0.3969.218

### Additional comments
https://getbootstrap.com/docs/5.0/components/carousel/

**Comment by ghost** [comment]
similar #32349

**Comment by dgrammatiko** [comment]
Just pasting HTML will not work, you need to tell Joomla that it needs to load the particular component: https://gist.github.com/dgrammatiko/efb3de4aa7cab4813a244f93f73cc0fd

**Comment by web-eau-net** [comment]
Thanks for the link, I'll look.
Just wonder how the thousends of no-professional Joomla users will use it.

**Comment by dgrammatiko** [comment]
@ceford already created something for end users: https://docs.joomla.org/J4.x:Using_Bootstrap_Components_in_Joomla_4

**Comment by web-eau-net** [comment]
Nice, thanks for this link

**Comment by Quy** [comment]
Closing as not an issue.
