### ISSUE TITLE
BS display properties dont work in footer module position

### ISSUE THREAD

**Issue by web-eau-net** [joomla/joomla-cms#33303]
### Steps to reproduce the issue
1. Create a custom HTML module and publish it in footer module position
2. Add any other display property (like "d-block d-sm-none") in suffix CSS class 

### Expected result
The module should not be displayed on devices larger than XS (as example mentionned)

### Actual result
The module is dsplayed on XXL 

### System information (as much as possible)
Joomla 4.0.0-beta8-dev
Opera 75.0.3969.218

### Additional comments
The display propreties seems to works in others module position of Cassiopeia, like bottom-b or bottom-a

**Comment by brianteeman** [comment]
This is because the position (as with some others) incorrectly has a module chrome of none. So there is no code to output the property you set. 

Every module position should have a module chrome set even if the only thing in that chrome is the code to support the default module options.

**Comment by brianteeman** [comment]
This can be resolved by the user selecting a different chrome for that module

![image](https://user-images.githubusercontent.com/1296369/155686850-c3ab3df3-c20b-4463-a985-e298cdf53da8.png)

**Comment by brianteeman** [comment]
can be closed
