### ISSUE TITLE
[4.0] Media Manager - can't create a folder

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33308]
I was trying to test https://github.com/joomla/joomla-cms/issues/29499 about how the error message handling could be improved when trying to create a duplicate folder.

It appears that its not possible to create a folder now at all [**UPDATE**well it is but not that you would know as it requires a pge refresh]

### When trying to create a valid new folder
```
media-manager.min.js?1a2f5e54e529a8a6967abe611c76c5f5:1 Uncaught TypeError: Joomla.renderMessages is not a function
    at Notifications.notify (media-manager.min.js?1a2f5e54e529a8a6967abe611c76c5f5:1)
    at Notifications.success (media-manager.min.js?1a2f5e54e529a8a6967abe611c76c5f5:1)
    at onSuccess (media-manager.min.js?1a2f5e54e529a8a6967abe611c76c5f5:1)
    at XMLHttpRequest.o.onreadystatechange (core.min.js?1a2f5e54e529a8a6967abe611c76c5f5:1)
```
### When trying to create a duplicate folder 
As above plus
`core.min.js?1a2f5e54e529a8a6967abe611c76c5f5:1 POST http://localhost/joomla-cms/administrator/index.php?option=com_media&format=json&task=api.files&path=local-0:/ 409 (Conflict)`

**Comment by PhilETaylor** [comment]
I can create folders at the moment with the latest 4.0-dev checkout

But like you I cannot create a duplicate (not that it should be possible, but the error message should be better visible)

<img width="900" alt="Screenshot 2021-04-25 at 17 04 45" src="https://user-images.githubusercontent.com/400092/116000509-75a9f380-a5e8-11eb-917f-6924866c9f40.png">

**Comment by PhilETaylor** [comment]
Also there is a `console.log("error....`  in media-manager.min.js that needs removing as Joomla should never be logging to the console, paging @dgrammatiko

**Comment by PhilETaylor** [comment]
Ive updated #29499  with todays testing for you @brianteeman

**Comment by PhilETaylor** [comment]
This should be closed. It is possible to create folders. 

Its not possible to create folders with names that already exist, and that is already recorded accurately in #29499 from June 2020
