### ISSUE TITLE
[4] Align error message icon with first line of error/warning/info message

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33309]
### Steps to reproduce the issue

"Most" flash error/warning/info messages are a single line of text

### Expected result

Pixel Perfection™

The 
<img width="44" alt="Screenshot 2021-04-25 at 17 15 13" src="https://user-images.githubusercontent.com/400092/116000858-d38b0b00-a5e9-11eb-88a3-04066302c7e5.png">
in the left of the message to be in line with the first line of text - thus in the middle of the coloured block when the error message is a single line, and in line with the first sentence if the error message is longer than one line of text 

### Actual result

<img width="950" alt="Screenshot 2021-04-25 at 17 12 51" src="https://user-images.githubusercontent.com/400092/116000820-adfe0180-a5e9-11eb-9709-17cd07b71de1.png">

<img width="656" alt="Screenshot 2021-04-25 at 17 16 31" src="https://user-images.githubusercontent.com/400092/116000910-ff0df580-a5e9-11eb-8e95-24332ba682ad.png">

### System information (as much as possible)

safari on mac.

### Additional comments

Needs to be fixed generically so applies to all error/warning and info messages

**Comment by dgrammatiko** [comment]
Will fix this on https://github.com/joomla/joomla-cms/pull/33234

**Comment by brianteeman** [comment]
To be clear is this what you want
![image](https://user-images.githubusercontent.com/1296369/117431359-0a81ea80-af21-11eb-8bd8-84488df1f75a.png)

its just a padding issue

**Comment by PhilETaylor** [comment]
99% of the messages in Joomla on a normal screen width are one line messages so if padding works then great.

Does it still work correctly (in line with the first sentence) when:

 - On a small screen so one sentence is wrapped
 - On a multi sentence message

**Comment by brianteeman** [comment]
no this change would not make the icon in line with the first sentence. Not convinced that it would be better or more correct. BS5 keeps it centered by default

![image](https://user-images.githubusercontent.com/1296369/117509187-b78c4f80-af81-11eb-9b4d-1d98144886f8.png)

**Comment by dgrammatiko** [comment]
> BS5 keeps it centered by default

These are not Bootstrap...

**Comment by brianteeman** [comment]
I know it was more a comment to say that the statement that it would be more correct if it was aligned with the top sentence was not necessarily true
