### ISSUE TITLE
[4] Consider removing the Release News from Post Installation Messages

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33312]
### Steps to reproduce the issue

When you view the "Post-installation Messages for Joomla CMS" page, **it is always slow-er to load** as it has to go out and retrieve and render the RSS feed of release news. 

This also doesn't appear to be cached. 

"Release news from the Joomla! Project" really has nothing to do with "Post-installation Messages for Joomla CMS"

When viewing "Post-installation Messages for Joomla CMS" there is no reason to be shown what the latest release news is, it has nothing to do with what the messages are.

It would make more sense that a CACHED version of the "Release news from the Joomla! Project" was a toggle-able module on the Home Dashboard (if it must be anywhere). 

<img width="1602" alt="Screenshot 2021-04-25 at 17 41 18" src="https://user-images.githubusercontent.com/400092/116001673-77c28100-a5ed-11eb-846f-b652f8cbb612.png">

**Comment by richard67** [comment]
Agree.

**Comment by PhilETaylor** [comment]
[4] Remove release news from post installation messages screen #33324
