### ISSUE TITLE
No input for caption

### ISSUE THREAD

**Issue by rjharishabh** [joomla/joomla-cms#33315]
### Steps to reproduce the issue
Try to insert an image in the article.

`Article` -> `Insert` -> `Image`

### Expected result
There should be an input for caption.

### Actual result
No input for caption.
The caption for the image is `Caption` now

![caption](https://user-images.githubusercontent.com/61203226/116003443-9b9cbb80-a61b-11eb-899f-815b342489c3.JPG)

### System information (as much as possible)
‎4.0.0-beta8-dev
Chrome on Windows 10
PHP 8.0.3
MySQLi 10.4.18-MariaDB

**Comment by brianteeman** [comment]
This is indeed confusing but its the way tinyMCE does it and its not something we can change

[image_caption](https://www.tiny.cloud/docs/plugins/opensource/image/#image_caption)
This option lets users enable captions for images. When this option is enabled the image dialog will have an extra checkbox called “Caption”. When a user checks the checkbox the image will get wrapped in an HTML5 figure element with a figcaption inside it. The user will then be able to type caption content inside the editor.

**Comment by rjharishabh** [comment]
Thanks, @brianteeman I got it
And there is not a `browse button`  in `Source` to add an image directly from the computer.

**Comment by brianteeman** [comment]
Correct which is why 99% of people dont use that and use the image button found under cms content

![image](https://user-images.githubusercontent.com/1296369/116005184-b829fb00-a5fd-11eb-8259-e10ce3587bbf.png)

**Comment by rjharishabh** [comment]
Thanks
