### ISSUE TITLE
[4.0] Blank state icons

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33328]
Am I missing something here as all the blank state use the same icon and there is no means to change it

https://github.com/joomla/joomla-cms/blob/f2cd94f14daacb6274deff78062ac4bbc0b10c37/layouts/joomla/content/blankstate.php#L31

**Comment by PhilETaylor** [comment]
I will fix it tomorrow. It was an oversight by @Bakual refactoring

**Comment by Bakual** [comment]
Oops, so we need to add the icon to the displayData and make it fallback to "article" if none is specified.

**Comment by PhilETaylor** [comment]
Yup a quick simple fix

**Comment by Bakual** [comment]
Fixed it: https://github.com/joomla/joomla-cms/pull/33332

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33332 . Thanks in advance.
