### ISSUE TITLE
[4] 4.0-dev is borked because of subform 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33326]
### Steps to reproduce the issue

Go to Fields in Joomla 4.0-dev admin 

<img width="924" alt="Screenshot 2021-04-25 at 21 37 40" src="https://user-images.githubusercontent.com/400092/116008850-8f5e3180-a60e-11eb-9666-9c018834e54a.png">

Seems to be related to changes in #33262

**Comment by PhilETaylor** [comment]
@joomdonation

**Comment by richard67** [comment]
@PhilETaylor Have you run the database updates?

**Comment by richard67** [comment]
... or made a new installation?

**Comment by PhilETaylor** [comment]
hahahahahahahhahahah zzzzzzzzzzz

**Comment by richard67** [comment]
Hmm, that PR didn't have any database update ... but it could have been another one for the subfields subforms thing.

**Comment by PhilETaylor** [comment]
Confirmed that when I reinstall from scratch everything seems to be working - phew - sorry for the false alarm, Im going to take that as a sign to log off... byyyyyeeeee
