### ISSUE TITLE
[4.0] Missing Delete button frontend

### ISSUE THREAD

**Issue by rjharishabh** [joomla/joomla-cms#33321]
### Steps to reproduce the issue
* Log In to the frontend
* Go to Template Setting in Author Menu module or Visit `http://localhost/joomla-cms/index.php/create-a-post/template-settings`
* Click `Select`

### Expected result
There should be a `Delete` button.
Also, there should be some margins between buttons.

### Actual result
`Delete` button is missing and no margins applied to buttons.

![no_delete](https://user-images.githubusercontent.com/61203226/116005726-e8858f80-a625-11eb-8b3c-eb417c172c8d.JPG)

### System information (as much as possible)
‎4.0.0-beta8-dev
Chrome on Windows 10
PHP 8.0.3
MySQLi 10.4.18-MariaDB

**Comment by PhilETaylor** [comment]
> Log In to the frontend

As who? With what access rights?

**Comment by richard67** [comment]
@rjharishabh What shall the delete button do? Delete the folder (if empty)? For deleting single images you have to use the "..." button of each image. And deleting the folder you are currently in will not be allowed as long as it contains files.

**Comment by rjharishabh** [comment]
> > Log In to the frontend
> 
> As who? With what access rights?

Admin

**Comment by richard67** [comment]
> > > Log In to the frontend
> > 
> > 
> > As who? With what access rights?
> 
> Admin

Admin? Or super user? You know that's not the same in Joomla (in opposite to Windows).

**Comment by rjharishabh** [comment]
Because in backend, there is a `delete` button. 
Use is to delete multiple images at once.

**Comment by richard67** [comment]
Ah, I see. Silly me.

**Comment by brianteeman** [comment]
The fix for the toolbar styling is the same as https://github.com/joomla/joomla-cms/pull/33231/files

**Comment by rjharishabh** [comment]
> The fix for the toolbar styling is the same as https://github.com/joomla/joomla-cms/pull/33231/files

This is in backend

**Comment by rjharishabh** [comment]
Issue for frontend.

**Comment by brianteeman** [comment]
fix is the same

**Comment by rjharishabh** [comment]
PR #33330
