### ISSUE TITLE
[4.0] Vote: Need padding-bottom in article-view having picture

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33337]
### What needs to be fixed
As title say:

Picture | Text
---- | ----
![Ohne Titel](https://user-images.githubusercontent.com/78906980/116056933-9886e700-a67e-11eb-8ac2-ffd4b63bc308.png) | ![Ohne Titel 2](https://user-images.githubusercontent.com/78906980/116057086-bce2c380-a67e-11eb-9be8-2df226ff9bab.png)

### Why this should be fixed
Look better.

### How would you fix it
Append higher padding-bottom-value.

### Side Effects expected
Don't know.

**Comment by rjharishabh** [comment]
Please test #33340

**Comment by ghost** [comment]
closing as having pull request #33340
