### ISSUE TITLE
[4.0.0-beta8-dev] [Multilingual] - Multilingual data sample 404 error

### ISSUE THREAD

**Issue by JavierABEduca** [joomla/joomla-cms#33343]
### Steps to reproduce the issue

1. Fresh installation (cloudnet) ---> OK
2. Spanish language extension intallation es-ES_joomla_lang_full_3.9.18v1 ---> OK
3. Multilingual Sample Data intallation ---> OK

### Expected result

1. Showing flags in home page ---> OK
2. Switching to Spanish in home page ---> KO (404 NOT FOUND)
3. Moving to english article ---> KO (404 NOT FOUND)

### Actual result
The requested URL /es.html was not found on this server.

### System information (as much as possible)

PHP Built On	Linux lamp102.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 x86_64
Database Type	mysql
Database Version	5.7.33-cll-lve
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	Yes
PHP Version	7.3.27
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 4.0.0-beta8-dev Development [ Mañana ] 2-February-2021 20:02 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.85 Safari/537.36

**Comment by ghost** [comment]
As far as i know only 3 languages can now be installed in j4, please look at #21806

**Comment by richard67** [comment]
Just I wanted to post the same.

Other languages can be installed but they might not be working.

Closing as duplicate to #21806 , because the issue here will be solved with the other one will be solved.

**Comment by infograf768** [comment]
Folks, this is abnormal.
If the op has installed the Spanish pack as an extension, it should be considered the same as the 3 packs we can install in j4.

I will test tomorrow.

Btw, i would not use .html in links

**Comment by richard67** [comment]
Re-opening due to previous comment. Sorry for the confusion.

**Comment by infograf768** [comment]
I can't reproduce the issue on 4.0-dev

1. Installed fresh Joomla 4.0-dev and then French, German and Persian language.
2. Logged in admin and installed the Spanish pack http://joomlacode.org/gf/download/frsrelease/21486/165589/es-ES_joomla_lang_full_3.9.18v1.zip using extension install.
3. Installed Multilang sample data
4. Set url rewriting and .htaccess
5. Even tested with `Add Suffix to URL` (.html)

All is working perfectly fine.
"Cloudnet" issue ?

**Comment by ghost** [comment]
@JavierABEduca do you still have the issue?

**Comment by JavierABEduca** [comment]
The issue will be closed. The problem was the .htaccess .

**Comment by richard67** [comment]
@JavierABEduca Thanks for feedback.
