### ISSUE TITLE
Error in Fields menu (backend)

### ISSUE THREAD

**Issue by rjharishabh** [joomla/joomla-cms#33367]
### Steps to reproduce the issue
`Users` > `Fields` And `Content` > `Fields`

### Expected result
The error should not occur

### Actual result
Error : 500
` Unknown column 'a.only_use_in_subform' in 'field list'`

![error-field](https://user-images.githubusercontent.com/61203226/116187257-ce8d9f00-a742-11eb-8c03-a746e20278d9.JPG)

### System information (as much as possible)
‎4.0.0-beta8-dev
PHP 8.0.3
Chrome & Firefox on Windows 10
MySQLi 10.4.18-MariaDB

**Comment by joomdonation** [comment]
Hello

Could you please install Joomla4 nightly build and check it again?

**Comment by rjharishabh** [comment]
@joomdonation 
There are two Which I have to download

Joomla_4.0.0-beta8-dev-Development-Full_Package.zip
Joomla_4.0.0-beta8-dev-Development-Update_Package.zip

**Comment by joomdonation** [comment]
For more information, the field was added in this PR https://github.com/joomla/joomla-cms/pull/33096/ . Not sure how you updated your site, but maybe the issue happens because the SQL update script is not executed

Install nightly build or execute this SQL command to your database should solve the issue:

```sql
ALTER TABLE `#__fields` ADD COLUMN `only_use_in_subform` tinyint(1) NOT NULL DEFAULT 0;
```

(Of course replace #__ with table prefix used in your database)

**Comment by joomdonation** [comment]
In your case, maybe download the full package Joomla_4.0.0-beta8-dev-Development-Full_Package.zip and setup the site from scratch would be better (or execute the SQL command manually as mentioned above)

**Comment by ghost** [comment]
Can't confirm on a installation today via launch.joomla.org.

![image](https://user-images.githubusercontent.com/78906980/116189124-c9235b00-a728-11eb-8fe1-7dbaead9db29.png)

**Comment by rjharishabh** [comment]
It's not on nightly-builds
It's on git installation

**Comment by rjharishabh** [comment]
Thanks @joomdonation 
After executing the SQL command, the error was resolved
