### ISSUE TITLE
[4.0] [REMINDER] Remove migration script for blog layout

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#33379]
### Steps to reproduce the issue

After merging the new params for blog layout, the script https://github.com/joomla/joomla-cms/pull/31570 canbe removed

**Comment by himanshu007-creator** [comment]
I would like to work on this issue.

**Comment by chmst** [comment]
Closing as we have a PR

**Comment by brianteeman** [comment]
As this is closed please remove the release blocker tag
