### ISSUE TITLE
[4.0] There is no uniform style in legends

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33378]
### Steps to reproduce the issue
Go to any user's profile settings. Note that some of the options tabs have LEGENDS, some do not. This can also be found on other parameter pages in the Joomla control panel. It makes sense to lead to a single style. 

**For example**

![Screenshot_1](https://user-images.githubusercontent.com/8440661/116291557-64561800-a79d-11eb-9fa1-db0a468fcbcf.png)

**Comment by ghost** [comment]
@Kostelano Can you please post screenshots which show english backend? Its easier for people to follow and understand they don't speak russian :-)

**Comment by Kostelano** [comment]
@sandramay0905 No problem - for the future. I additionally wrote what I am talking about :)

**Comment by Kostelano** [comment]
PR https://github.com/joomla/joomla-cms/pull/33389
