### ISSUE TITLE
[4.0] Incorrect textarea field class in email templates

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33382]
### Steps to reproduce the issue
Go to the letter templates, click on any template and pay attention to the outline of the textarea type field. Then click on the field, you will see a thick line instead of a neat, pretty, pretty border.

![Screenshot_3](https://user-images.githubusercontent.com/8440661/116298632-599f8100-a7a5-11eb-925d-5b99bee19fd0.png)

The field class should be like this:
`class="form-control valid form-control-success"`

Actual value:
`class="valid form-control-success"`

**Comment by PhilETaylor** [comment]
PR https://github.com/joomla/joomla-cms/pull/33395

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33395 . Thanks in advance.
