### ISSUE TITLE
[4.0] After deleting the last item, the empty state layout still has filter for trashed items activated

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#33386]
### Steps to reproduce the issue

The following describes the issue for com_content, but we have it elsewhere, too.

It is like that on J3 since long time and so some kind of expected behaviour, i.e. not been introduced by the new empty states in J4.

But I think it's confusing and annoying the user, so we should take a chance to change that with J4.

1. Have some articles so the articles list view in backend shows items.
2. Trash all articles.
3. Filter for trashed items.
4. Select all trashed articles and empty trash.
Result: The empty state layout is shown. No filter tool bar is shown, but there is still the filter for trashed items active, as you will see in the next step-
5. Use the "New" button to create a new article.
6. See that the status of the new article is "Trashed".
7. Change it to "Published".
6. Use the "Save & Close" button.
Result: The article list view is shown, The filter tool bar is visible, the filter for trashed items is set, and so the new article is not shown. That's confusing.

Alternatively you could skip step 6, then the article would be visible but have "Trashed" status, that's the same annoying.

### Expected result

When the last item is deleted so that the empty state layout is show, all active filters are cleared.

### Actual result

See above steps to reproduce.

### System information (as much as possible)

Current 4.0-dev.

### Additional comments

This issue has not been introduced by the empty states like I first thought because I didn't remember that this issue was confusing me long time ago in J3.

**Comment by richard67** [comment]
P.S. I am not 100% sure, but I think I remember it was working right before the empty state formerly called blank state layouts were introduced.

**Comment by PhilETaylor** [comment]
This is exactly how it works currently - you are right. The Empty State code makes no changes to the filter state at all. So if your last filter selection was Trashed, then you would remain filtered with Trashed when you clicked the add new button. 

This is no different to how it was before.

Before Empty States, if you selected Trashed, and clicked NEW in the toolbar, your new article would have Trashed status selected. 

Im not saying this is how it should be, it can of course be improved, but this has not been broken or changed by Empty State Design.

**Comment by richard67** [comment]
I'm not sure if it was like that before.

**Comment by PhilETaylor** [comment]
I am off to bed, I will let you test and see that it has been this way forever :-) 

There simply is no code in any of the new empty state changes to make any changes to the filter state, we just leave it alone.￼

**Comment by brianteeman** [comment]
nothing to do with empty state

**Comment by richard67** [comment]
> This is no different to how it was before.

> nothing to do with empty state

Confirmed. Was like that also on Beta 7, I've just tested.

@brianteeman Do you know if we have already an issue for that?

**Comment by richard67** [comment]
Closing for now. Sorry for the confusion.

**Comment by brianteeman** [comment]
@richard67 its this way by design and has always been this way. Watch this

![modal](https://user-images.githubusercontent.com/1296369/116314326-daab4800-a7a6-11eb-9d9c-8b307998829c.gif)

**Comment by richard67** [comment]
I know meanwhile.

**Comment by richard67** [comment]
Re-opening the issue since I still think it is weird behaviour confusing the user, even if it is like that on J3 since ages.

I remember now it had confused me in past, and then I had forgotten about it, it seems.

Will change description and maybe title, too, so it's clear it was not introduced by the empty states.

**Comment by richard67** [comment]
I think when empty state is detected, filters should be reset/unset first before hiding the filter and any other unneeded buttons.

**Comment by PhilETaylor** [comment]
> I think when empty state is detected, filters should be reset/unset first before hiding the filter and any other unneeded buttons.

Go for it.

**Comment by richard67** [comment]
> > I think when empty state is detected, filters should be reset/unset first before hiding the filter and any other unneeded buttons.
> 
> Go for it.

@PhilETaylor I don't really know how to do that. Would have to investigate it first. Maybe you can do it faster?

**Comment by PhilETaylor** [comment]
> I think when empty state is detected, filters should be reset/unset first before hiding the filter and any other unneeded buttons.

Added in #33471

**Comment by richard67** [comment]
Closing as having a pull request.
