### ISSUE TITLE
[4.0] Cassiopeia: Language switcher need higher contrast for setting "Full Language Names"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33388]
### What needs to be fixed
Set module "Language switcher" to any position having dark background (here `topbar`) and setting like:

Setting | Colour Standard | Colour Alternative
-- | -- | --
![Screenshot_lang-module](https://user-images.githubusercontent.com/78906980/116349447-51b8fe80-a7f0-11eb-8d01-c9499db2b530.png) | ![Screenshot_lang-topbar1](https://user-images.githubusercontent.com/78906980/116349462-5e3d5700-a7f0-11eb-9195-d7e19be9c1dd.png) | ![Screenshot_lang-topbar2](https://user-images.githubusercontent.com/78906980/116349484-672e2880-a7f0-11eb-830b-bd9b6971bbd6.png)

### Why this should be fixed
Better contrast to read.

### How would you fix it
Colour get light if background is dark and vice versa.

### Side Effects expected
Don't know.

**Comment by infograf768** [comment]
It is impossible to know what will be the background color in this configuration.

Default Cassiopea link color is
```
a {
    color: var(--cassiopeia-color-link);
}
```

Therefore I guess anyone wanting to use the switcher on a dark background with this precise configuration will have to create a css override.

For example
```
div.mod-languages a {
  color: #fff;
}
```
I would say: won't fix on this one.

**Comment by drmenzelit** [comment]
Closing with PR #33394
