### ISSUE TITLE
[4.0] subhead noshadow CSS missing (frontend)

### ISSUE THREAD

**Issue by rjharishabh** [joomla/joomla-cms#33392]
### Steps to reproduce the issue
* Log In to the frontend
* Go to Template Setting in Author Menu module or Visit `http://localhost/joomla-cms/index.php/create-a-post/template-settings`
* Click `Select`

### Expected result
There should be `CSS` declaration for the class `subhead noshadow`

### Actual result
No `CSS` declaration for the class `subhead noshadow`

![class-without-property](https://user-images.githubusercontent.com/61203226/116395533-ded87380-a841-11eb-8ca4-bf0fdc8f8b14.JPG)

### System information (as much as possible)
PHP 8.0.3
MySQLi 10.4.18-MariaDB

**Comment by brianteeman** [comment]
Basically the code in /templates/atum/scss/blocks/__toolbar.scss needs to be replicated in cassiopeia

**Comment by rjharishabh** [comment]
working on it

**Comment by rjharishabh** [comment]
PR #33403
