### ISSUE TITLE
Add minimum number of characters for indexing a word [com_finder]

### ISSUE THREAD

**Issue by chivitli** [joomla/joomla-cms#3340]
I'd like to work on an improvement to com_finder, so that we can choose what should be the minimum character number of a word, so that it would be indexed. At the moment we index everything, like "I" or "is", which doesn't seem like an optimal solution. Unfortunately, after digging a little bit, I realized that com_finder is quite complicate, so I was wondering does anyone have a deeper knowledge of it, and could point me where to look, and would it be too complicated to add such parameter?

**Comment by roland-d** [comment]
@chivitli There has been no update since last year and there is no code here, I am going to close this request. Feel free to re-open this request or create a new request when ready. Thank you for your contribution.
