### ISSUE TITLE
Itemprop="name" disappearing on the frontend

### ISSUE THREAD

**Issue by michelle042021** [joomla/joomla-cms#33408]
### Steps to reproduce the issue
Hi support,
I created https://schema.org/FAQPage for my page. I have added all the stuff properly but for some reason when i run the code on google snippet, its missing itemprop="name" from the question.

https://search.google.com/test/rich-results?id=SE4dH1lvgQtcvEAhhlzLTQ

The code is added in the backend using JCE plugin and the code is there in the backend but in front end it showing missing. 

I did contact the plugin manager and he is unable to resolve the issue. I will request someone to have a look and assist me.

view-source:https://www.southafricancasinos.co.za/online-casino-reviews/springbok-casino.html

### Actual result
The actual result should be displaying the result without any error.

**Comment by richard67** [comment]
I can't find any FAQ page with that kind of structured data on the page provided by that link. @michelle042021 Could you provide more information about how you add that structured data (schema.org/FAQPage), where you can see it in backend and which of the pages on frontend should show that data?

**Comment by brianteeman** [comment]
This really should be handled in the forum

**Comment by richard67** [comment]
Exactly that's what I'm trying to find out, to be sure it is not a cure issue.

**Comment by michelle042021** [comment]
Hi Richard, 

Thanks for the reply.

This is the page i have added faq's - https://www.southafricancasinos.co.za/online-casino-reviews/springbok-casino.html
I have added the schema for the faqs question.

I have added the following code 


<div class="cont-faq" itemscope="itemscope" itemtype="https://schema.org/FAQPage">
		<div class="block_faq">
			<div class="item" itemscope="itemscope" itemtype="https://schema.org/Question" itemprop="mainEntity">
				<h3 class="question faqs_homepage-1" itemprop="name">Is Springbok Casino legal in South Africa?</h3>
				<div class="answer" itemscope="itemscope" itemtype="https://schema.org/Answer" itemprop="acceptedAnswer">
					<div itemprop="text">
						<p class="answer faq_cot">All <strong><a href="https://www.southafricancasinos.co.za/" title="online casinos">online casinos</a></strong> are illegal in South Africa. The law forbids any website from offering real money gambling games and slots to South African residents. Only sports betting is legal online. But many offshore casinos freely accept South African players, simply because it is 100% safe. Players are not targeted by authorities. And since Springbok is based outside South Africa, the authorities leave them alone as well. You can safely play and win real Rand at this casino!&nbsp;&nbsp;</p>
					</div>
				</div>
			</div>
		</div>
		
		
</section>

The output should be displaying with no error message. The google snippet testing tool is giving me a error message itemprop="name" missing.

https://search.google.com/test/rich-results?id=uAasbOz7cQ305U5emu_FpA

@brianteeman i wasn't able to find any help from anywhere so at the end i decided to check here. There is no particular forum for this, i think helping anyone won't be a issue.

 ![screen shot 2021-04-30 at 04 27 32](https://issues.joomla.org/uploads/1/8874d577e4df141fee86874753ef1def.jpg)







<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33408">issues.joomla.org/tracker/joomla-cms/33408</a>.</sub>

**Comment by brianteeman** [comment]
This really should be closed. It was a non-core forum support issue and is now 1 year old

**Comment by richard67** [comment]
Closing for reason stated in previous comment.
