### ISSUE TITLE
[4.0] Behaviour plugins

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33418]
### Steps to reproduce the issue
J4 has two new plugins - behaviour tags and behaviour versions that have a description of
Allows ~content~ items to be tagged.
Allows ~content~ items to be versioned.

### Expected result
~1. From the description I expect that disabling the plugins will remove the ability to version or tag a content item but that it still is possible to version or tag another item such as a contact.~
2. If I can't version an item then I would expect not to see a versions button in the toolbar or a version note field
3. If I did add a version note and then save I would expect to get some sort of message instead of the note being silently discarded
4. If I can't tag an item then I would expect not to see the tag field where I can select an existing tag
5. If I can tag an item and then save  I would expect to get some sort of message instead of the tag being silently discarded

### Actual result
~1. The plugins apply everywhere not just content~
2. version button displayed and active 
3. version note field displayed but cannot be updated
4. tags field is displayed where it appears that I can select a tag or even create a new one

### Why?
Why do we even have these plugins
If we do have these plugins I would expect them to be applied per component and configured in the integration tab of the component
~At an absolute minimum the description of the plugin should be updated to show that they apply to all items not just content items~

_Updated after #33420_

**Comment by PhilETaylor** [comment]
> Why do we even have these plugins

The plugins only provide themselves the the onTable* hooks for Tables that implement the `TaggableTableInterface` or `VersionableTableInterface`

In order for these features to work 1) The plugins must be published 2) The PHP Classes need to implement the interfaces.

The only tables that implement these interfaces, and therefore have these features are: 

Component | VersionableTableInterface | TaggableTableInterface
----------- | ----------- | ----------- 
Content | Yes | Yes
Banners | Yes | No
Banner Clients | Yes | No
Contacts | Yes | Yes
Newsfeeds | Yes | Yes
Tags | Yes | No
User Notes | Yes | No
Categories | Yes | Yes

As you can see this is not the full list of Joomla components, I guess its a half implemented set of features.

**Comment by brianteeman** [comment]
> As you can see this is not the full list of Joomla components, I guess its a half implemented set of features.

Well it wouldnt make sense to tag a tag ;)

None of this explains why its a plugin or explains the broken behaviour described

> The use of the word "content" in the phrase "Allows content items to be tagged" is applied to mean "The royal content" and not as in "Content = Articles"

Easy enough for us who speak english. I wonder how many translated sites will maintain that distinction

**Comment by PhilETaylor** [comment]
> None of this explains why its a plugin or explains the broken behaviour described

I was not involved in its creation, but it seems to be a plugin so it can be easily disabled. But as you rightly state, this only disables the `onTable*` hooks and not the actual Form fields and buttons in an extension's views - yet. 

Broken = Half implemented. 

> Easy enough for us who speak english. I wonder how many translated sites will maintain that distinction

We have the same things of "The royal content" in the left menu - where "Content" is the top level and "Articles" and other things are below it

<img width="298" alt="Screenshot 2021-04-30 at 08 46 48" src="https://user-images.githubusercontent.com/400092/116664669-ae531f80-a990-11eb-9c33-3c70e1fe835d.png">

**Comment by brianteeman** [comment]
> At an absolute minimum the description of the plugin should be updated to show that they apply to all items not just content items

#33420 for that part

**Comment by PhilETaylor** [comment]
as a test of the concept, please test #33422
