### ISSUE TITLE
[4.0] com_menus: If set "Toggle Menu" too much scroll down is possible

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33421]
### Steps to reproduce the issue
As title say on all com_menus views:

> ![image](https://user-images.githubusercontent.com/78906980/116665507-28d46d00-a99a-11eb-8580-7f08b9b1b5e2.png)

### Expected result
Behaviour like if not "Toggle Menu" is set.

### Actual result
Too much space scrollable.

### System information (as much as possible)
![image](https://user-images.githubusercontent.com/78906980/116665733-6638fa80-a99a-11eb-9e99-2cc70ebbcd26.png)

### Additional comments
On other components like com_content i tried all works as expected.

**Comment by Krshivam25** [comment]
@sandramay0905 I'm unable to reproduce this issue in the local repo. Please clarify this more.

**Comment by ghost** [comment]
I'm sorry, @Krshivam25 i don't know how to describe better.

**Comment by brianteeman** [comment]
@sandramay0905 I couldn't replicate it either. Could you try making a screen recording of it. You can use [liceCap](https://www.cockos.com/licecap/) or similar

**Comment by ghost** [comment]
Thanks @brianteeman for the help. I'm using now licecap:

![1](https://user-images.githubusercontent.com/78906980/116689427-6516c600-a9b8-11eb-9b19-0957dca28c3c.gif)

Same result on safari.

**Comment by brianteeman** [comment]
I can now replicate the error. I have no idea how to fix it but I will explain the issue so hopefully someone else can do.

Create a lot of menus. 
When you open and close the menu with the toggle expanded you will see that the page length is updated.
When you toggle the sidebar to collapsed then the entire sidebar collapses both vertically and horizontally BUT the main body height does not update

![demo1](https://user-images.githubusercontent.com/1296369/116691655-0733af80-a9b3-11eb-8b8a-0f5bafab9df4.gif)

**Comment by ghost** [comment]
Issue has gone using pull request #33100. If the pr is merged, i will close the issue.

**Comment by ghost** [comment]
Closing, #33100 is merged.

**Comment by ghost** [comment]
Reopen as issue is back.

**Comment by ghost** [comment]
Closed again as issue today don't exist :-)
