### ISSUE TITLE
[4.0] Style of the page navigation links is different from the hover style on other buttons

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33438]
### Steps to reproduce the issue
Go to plugins, set the display of elements on one page, for example to 20. Go down to the very bottom of the page, pay attention to the page navigation links.

If we take into account that usually the behavior of the HOVER changes the style of the button to a darker one, then I would prefer to see the same behavior here. Compare with how it should be in the filter above on the same page.

![Screenshot_3](https://user-images.githubusercontent.com/8440661/116737064-6fa57f80-a9f9-11eb-846b-122dfc91ed9a.png)

**Comment by brianteeman** [comment]
> If we take into account that usually the behavior of the HOVER changes the style of the button to a darker one,

I dont think there is such a thing as a usual behaviour.

For reference this is exactly the same as the bootstrap default https://getbootstrap.com/docs/5.0/components/pagination/#disabled-and-active-states

For me there is nothing to fix here

**Comment by Kostelano** [comment]
Thanks for the link. Now I see. Closed.
