### ISSUE TITLE
[4.0] Inseparable buttons on the Joomla update page

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33430]
### Steps to reproduce the issue
Go to System - Update (Joomla) - Download and Updates tab, select the update package, click the download button. Note that the buttons on the new page are inseparable. 

![Screenshot_6](https://user-images.githubusercontent.com/8440661/116731170-09692e80-a9f2-11eb-8e94-f1c8c4ada191.png)

**Comment by Kostelano** [comment]
Also, the Login header looks a little ridiculous. It either needs to be stylized or removed altogether. And so it is clear what the fields are below.

**Comment by brianteeman** [comment]
Thank you very  much for testing and reporting this issue. However a recent decision was made to remove the ftp layer from joomla 4 and that will include this view.

**Comment by joomdonation** [comment]
@brianteeman Actually, this is not related to FTP. It is the screen which is displayed after admin upload an update package. It is used to validate username and password of admin before processing upload and update. This screen is still there after removing FTP layer from com_joomlaupdate.

**Comment by Kostelano** [comment]
Maybe I don't understand something. This is a site on the local host + there is not a word about FTP in the Joomla update tab. This is a common tab that allows you to update Joomla using a package on your local PC.

**Comment by brianteeman** [comment]
mea culpa

**Comment by Kostelano** [comment]
PR https://github.com/joomla/joomla-cms/pull/33446
