### ISSUE TITLE
[4.0] Large indentation of checkboxes in mass mailing

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33434]
### Steps to reproduce the issue
Go to Users - Mass mailing, note that the indentation of the checkboxes is quite large. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/116735792-ae3a3a80-a9f7-11eb-8663-fdb86b661ace.png)

**Comment by ghost** [comment]
Confirm the issue.

**Comment by Hackwar** [comment]
With #39374 this issue has become obsolete.
