### ISSUE TITLE
[4.0] Update site cannot be edited

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33439]
### Steps to reproduce the issue
Go to System - Update sites, select any site, click on the Actions - Edit buttons. You will be taken to a new page, but I was unable to make changes to the update site - the fields are not available.

Perhaps the restriction applies only to sites from the Joomla package.

Unfortunately, I don't have a Joomla 4 extension handy that has an update site out of the box to test the behavior there.

![Screenshot_4](https://user-images.githubusercontent.com/8440661/116739132-007d5a80-a9fc-11eb-9040-103bc8c609f9.png)

**Comment by brianteeman** [comment]
> Perhaps the restriction applies only to sites from the Joomla package.

correct

**Comment by Bakual** [comment]
Not correct. The same happens with my own component (you can try yourself with https://github.com/Bakual/SermonSpeaker/releases/tag/6.0.0-beta2).

Looking at the code, the name, type and location fields are declared as readonly:
https://github.com/joomla/joomla-cms/blob/7b9449d4d7c7ba4a06cb1618ccd175a02d294dcb/administrator/components/com_installer/forms/updatesite.xml#L8-L25

So I assume you are only meant to edit the additional `extra_query` field (if used by the extension).

Maybe @roland-d can say more?

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/116742045-bcd02400-a9ee-11eb-8394-1b09b1e2d484.png)

**Comment by Kostelano** [comment]
Even if the restriction for the sites of the Joomla package is implemented, then it is necessary to somehow indicate it clearly for the user. It is possible to use the lock icon specifically for these update sites. Similar to how it is implemented in Extension Management.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/116742060-84851180-a9ff-11eb-9b21-9d33ab71f956.png)

**Comment by roland-d** [comment]
The edit screen is indeed for managing the download key for that extension. There should not be a need for end-users to modify the update server details.

> Even if the restriction for the sites of the Joomla package is implemented, then it is necessary to somehow indicate it clearly for the user.

I am not sure what you are asking here but the lock icon has a completely different goal. When you have an extension and a download key you will go to the edit screen on an update site, there is no other reason to go there.

**Comment by Bakual** [comment]
It's just pretty pointless to offer editing an updatesite where you can't edit anything:
![image](https://user-images.githubusercontent.com/1018684/116743112-bfd01200-a9f8-11eb-933f-2b1c97fd25af.png)

So maybe only offer that possibility for those extensions which have a download key? Would make a better UX I guess.

**Comment by Kostelano** [comment]
@roland-d Now (when you explained) I understand WHAT this button specifically implies. The point is that ordinary users of Joomla do not run around the forums with the question "something does not work" for the sake of such a simple thing :). If editing is intended only for entering a key, then it makes sense to make the button inactive for extensions that do not use an access key. Or, alternatively, rename the button to something like "Edit Key". Anyway, it seems to me that the current state of the page / function needs a little work.

**Comment by roland-d** [comment]
Feel free to make the changes you wish.

**Comment by alikon** [comment]
iirc in the orginal gsoc project it was editable
please test #33460
