### ISSUE TITLE
[4.0] Process and Cancel buttons are in the wrong order

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33435]
### Steps to reproduce the issue
Go to System - Redirects, click the bulk link processing button. Note that the buttons in the modal window are not positioned correctly. The classic option is usually the Cancel button at the very end of the button bar. 

![Screenshot_2](https://user-images.githubusercontent.com/8440661/116736200-3ddfe900-a9f8-11eb-9819-ec24c3ca22d5.png)

**Comment by brianteeman** [comment]
This needs careful consideration as there are many modals with this layout. eg for modules and menus

**Comment by ghost** [comment]
@Kostelano #33221 was merged with `Cancel`-Button first, maybe its not clear if the button has to be at the end?

**Comment by Kostelano** [comment]
@sandramay0905 Perhaps in the case where there is a CANCEL and DELETE button, it looks fine. But now we have the CANCEL button in all modal windows first, which in my opinion is not correct. Yes, it should be at the end of the button bar.

**Comment by Kostelano** [comment]
https://github.com/joomla/joomla-cms/issues/33701
