### ISSUE TITLE
[4.0] No legend in private messages - My settings

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33431]
### Steps to reproduce the issue
Continuing theme https://github.com/joomla/joomla-cms/issues/33378, I inform you about another place where there is no LEGEND. At the moment, I no longer find such places.

@YatharthVyas, I am reaching out to you because you have already made corrections in this regard and you might want to add another modic one too :). Thanks anyway for your participation.

So, in the control panel go to private messages - My settings.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/116732433-7cbf7000-a9f3-11eb-83cb-073da01ae782.png)

**Comment by YatharthVyas** [comment]
@Kostelano Thanks for notifying me!

I hope this is the correct legend text: 
https://github.com/joomla/joomla-cms/blob/7b9449d4d7c7ba4a06cb1618ccd175a02d294dcb/administrator/language/en-GB/com_messages.ini#L9
![image](https://user-images.githubusercontent.com/53610833/116735696-86a19d00-aa0c-11eb-9683-0acf26cb07a3.png)

The name of this view is 'config' which matches with the name `COM_MESSAGES_CONFIGURATION`. I also ran a file lookup and this language Text wasn't used anywhere so I figured it must be placed here.

**Comment by Kostelano** [comment]
Thank you. It might be better to use a new constant that won't bind to the component's settings header. Something like: My Settings or Basic Settings .

**Comment by YatharthVyas** [comment]
> Thank you. It might be better to use a new constant that won't bind to the component's settings header. Something like: My Settings or Basic Settings .

I hope I understood it correctly, The language constant bound to the header is: 
https://github.com/joomla/joomla-cms/blob/69a1a5896bb848fea7b658de178c80b6bf9c5dc9/administrator/language/en-GB/en-GB.com_messages.ini#L75

and the new one which I've used is: 
https://github.com/joomla/joomla-cms/blob/7b9449d4d7c7ba4a06cb1618ccd175a02d294dcb/administrator/language/en-GB/com_messages.ini#L9
This, `COM_MESSAGES_CONFIGURATION` is not used anywhere else so do you still suggest I make a new constant? Or should I rename the above to:
`COM_MESSAGES_CONFIGURATION:"My Settings"`
to ensure it is not bound to the header but matches it's text

**Comment by Kostelano** [comment]
Specifically, the colon in the legend confuses me. But this is just my humble opinion :). Therefore, I would prefer to leave "My settings".

**Comment by Kostelano** [comment]
PR https://github.com/joomla/joomla-cms/pull/33442
