### ISSUE TITLE
[4.0] [Media] Directory created but not actually created

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33449]
### Steps to reproduce the issue
Go to Media Manager and try to create a directory with Russian letters, for example, "ыыыыыыыы". You will receive a message that the directory has been successfully created, however no directory has actually been created :). 

![Screenshot_2](https://user-images.githubusercontent.com/8440661/116752383-2a3f7d00-aa0e-11eb-88c6-d3220419b22b.png)

**Comment by brianteeman** [comment]
issue confirmed

**Comment by PhilETaylor** [comment]
This is not a com_media issue.

**Comment by PhilETaylor** [comment]
opps hit enter too soon.

The problem is with the CMS Filesystem Library.

`ыыыыыыыы` is passed to `File::makeSafe`

But that returns an empty string. 

This in turn in com_media is resolved to `/path/to/images` which it then silently tries to great, but obviously its already there.

**Comment by brianteeman** [comment]
yes
![image](https://user-images.githubusercontent.com/1296369/116754751-307b2c80-aa01-11eb-80b2-90dc488969e4.png)

**Comment by PhilETaylor** [comment]
and for transliterator_transliterate how about the `Intl` Extension ?

**Comment by brianteeman** [comment]
[systeminfo-2021-04-30T21_16_47+00_00.txt](https://github.com/joomla/joomla-cms/files/6408112/systeminfo-2021-04-30T21_16_47%2B00_00.txt)

**Comment by PhilETaylor** [comment]
So that's the problem then, Your platform doesn't have ICONV and INTL PHP extension as needed by `File::makeSafe` in order to transliterate the text to a safe useable folder name of yyyyyyyyy

**Comment by PhilETaylor** [comment]
PR https://github.com/joomla/joomla-cms/pull/33451 to provide better messaging

**Comment by brianteeman** [comment]
confirming that enabling both extensions does result in a folder being created

**Comment by Kostelano** [comment]
PR https://github.com/joomla/joomla-cms/pull/33451
