### ISSUE TITLE
[4.0] No border rounding on button hover behavior

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33443]
### Steps to reproduce the issue
To be honest, I don't know if the problem is in Bootstrap or specifically in Atum's styling, but I noticed that when the hover behaves for the Save and New buttons, there is no border rounding. 

![Screenshot_3](https://user-images.githubusercontent.com/8440661/116745374-a54f6600-aa03-11eb-89cf-a1f6d9f07ef5.png)
![Screenshot_4](https://user-images.githubusercontent.com/8440661/116745377-a5e7fc80-aa03-11eb-8531-9efbd6359b08.png)

**Comment by ghulamrabbani883** [comment]
![This is not happening in my admin panel](https://user-images.githubusercontent.com/65941307/116772379-36f2be00-aa6c-11eb-944a-f3231e3cddf1.png)
This is not happening in my admin panel, I think everything is right.

**Comment by ghost** [comment]
Confirming issue.

@ghulamrabbani883 Create a new module to get the issue. Your screenshot is different to the one by @Kostelano cause it shows 2 submenus (+ `Save to Menu`). If you create a new module and open submenu you see only `Save & New`.

**Comment by Kostelano** [comment]
> This is not happening in my admin panel, I think everything is right.

No, not okay. This only shows up when we have 1 dropdown button. Two buttons are fine.

**Comment by brianteeman** [comment]
it is missing the box-shadow that is applied to the toplevel buttons when they are focussed and active



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33443">issues.joomla.org/tracker/joomla-cms/33443</a>.</sub>

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33483 . Thanks in advance.
