### ISSUE TITLE
[4] Filter Tags can kill categories overview 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#33445]
### Steps to reproduce the issue
You should have one or more categories and tags (install blog sample data).
Open categories. Open Filter and filter for a tag. If nothing is found, the "New-Page" appears. 
No chance to get back to categories overview. 

### Expected result
If nothing is found, I expect a message as usual 

### Actual result
Result: The "New-Page" appears. 
No chance to come back to categories overview.

**Comment by rjharishabh** [comment]
@chmst  Am I doing something wrong to reproduce the issue

https://user-images.githubusercontent.com/61203226/116749957-59121f00-aa1f-11eb-87b7-2878bf39603a.mp4

**Comment by brianteeman** [comment]
Its a bug but hardly a release blocker

**Comment by brianteeman** [comment]
@PhilETaylor @bakual This is a bug in the emptystate code for categories

**Comment by Bakual** [comment]
I think this has to be fixed here:
https://github.com/joomla/joomla-cms/blob/6f98135cb5a64f354c97edd567bf3abdac83661d/administrator/components/com_categories/src/Model/CategoriesModel.php#L503-L510

Either clear also the "join", or maybe better just start with a new query instead of manipulating the existing one.

**Comment by Bakual** [comment]
Btw same issue exists for other views where you can filter by tags (or probably any joined table property).

**Comment by PhilETaylor** [comment]
ok ok ok give me a moment.

**Comment by PhilETaylor** [comment]
Please test [4] remove join from isEmptyState calculation sql #33453

**Comment by PhilETaylor** [comment]
This can be closed, and certainly is not a release blocker.

**Comment by Quy** [comment]
Thank you!
