### ISSUE TITLE
[4.0] No styling of the time buttons on the calendar

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33447]
### Steps to reproduce the issue
Go to any component (for example, added a new banner), where there is the date / time of the item's publication. Open the calendar - the time buttons are not stylized. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/116750697-8359e180-aa0b-11eb-9603-e30cdd77f875.png)

**Comment by ghulamrabbani883** [comment]
I don't think it needs to be styled

**Comment by ghost** [comment]
Confirming issue. 

Firefox on Mac:

> ![image](https://user-images.githubusercontent.com/78906980/116772808-a4452580-aa51-11eb-8a60-67ecf0976f33.png)

Maybe a solution like #33220

**Comment by Quy** [comment]
Closing as #36933 is more comprehensive.
