### ISSUE TITLE
[4.0] Different styles of tabs in permissions and access levels

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33440]
### Steps to reproduce the issue
Open the System - User Permissions (Groups) page, click the New button. Then open the System - User Permissions (Access levels) page, click the New button.

Compare the tab styles on these pages.

![Screenshot_5](https://user-images.githubusercontent.com/8440661/116741228-bc3f8980-a9fe-11eb-9d31-ef36f88e4778.png)

![Screenshot_6](https://user-images.githubusercontent.com/8440661/116741240-bfd31080-a9fe-11eb-8bb2-4e7339604367.png)

The second option doesn't quite fit the page style. The same story is observed on the page AFTER updating Joomla.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/116741294-d11c1d00-a9fe-11eb-9131-5d4a1393ebc0.png)

**Comment by drmenzelit** [comment]
Closing with PR #33473
