### ISSUE TITLE
RIPS Vulnerability scanning has something to report

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33455]
Drone is not happy 

```
Failure: Number of issues exceeds sum threshold (1/0)
--
27 | Please contact the security team at security@joomla.org
28 | Progress: [============================] 100%

```

All builds now failing:

<img width="834" alt="Screenshot 2021-04-30 at 23 17 02" src="https://user-images.githubusercontent.com/400092/116759422-33c6e600-aa0a-11eb-9eef-5064efa13b94.png">

**Comment by PhilETaylor** [comment]
@joomla/security @SniperSister

**Comment by zero-24** [comment]
There where two reports both false positive.
