### ISSUE TITLE
[4.0] [Mass Mail Users] Infinite repeating error when clicking the Submit button

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33450]
### Steps to reproduce the issue
Go to Users - Mailing list, try to send the mail, but do not enter the subject / text of the message. Each time you click the SUBMIT button, a new error message will be displayed.

![Screenshot_3](https://user-images.githubusercontent.com/8440661/116753128-47288000-aa0f-11eb-986d-c148a4401eed.png)

I can say for sure that in some other component in a similar situation (today I don’t remember exactly where), the error message is not duplicated, but one "hangs" until the required condition is met.

**Comment by rjharishabh** [comment]
Similar issue #33306

**Comment by Kostelano** [comment]
Also, you need to change the message type to Warning as a minimum. Now - just information for the user.

**Comment by brianteeman** [comment]
@Kostelano you just beat me to adding that bug to this issue

**Comment by brianteeman** [comment]
If anyone wants to fix this then its the javascript in `build\media_source\com_users\js\admin-users-mail.es6.js` that needs to be ammended

**Comment by ghost** [comment]
~@Kostelano your report reminds on an issue reporte by @PhilETaylor, can you have a look if its the same? issue is #33306~

Edit because of comment below, thanks @brianteeman.

**Comment by brianteeman** [comment]
@sandramay0905 similar result different cause

**Comment by PhilETaylor** [comment]
Why is this form not validating on blur like other forms? why is it waiting to validate after the form is submitted? Is that just because no one has applied the Javascript based validation on this page and it was overlooked?

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33485 . Thanks in advance.

**Comment by Kostelano** [comment]
Can we open it up again?

PR https://github.com/joomla/joomla-cms/pull/33485 was closed unfortunately.

**Comment by rjharishabh** [comment]
Please open this issue

**Comment by Hackwar** [comment]
I created a PR with #39374. Closing this issue.
