### ISSUE TITLE
Side navbar of Contact, News feed, Smart search not working properly

### ISSUE THREAD

**Issue by ghulamrabbani883** [joomla/joomla-cms#33459]
![not opening properly](https://user-images.githubusercontent.com/65941307/116772528-53432a80-aa6d-11eb-8e59-807081fbf084.png)
This is not opening properly, I mean the side navbar is not working properly. Let me help to fix this bug.

**Comment by rjharishabh** [comment]
@ghulamrabbani883 
Please provide the steps to reproduce the issue.

**Comment by ghulamrabbani883** [comment]
Inside components you will find this side navbar. By the way almost all the side navbar is not working properly.

**Comment by brianteeman** [comment]
It is not clear what you mean - it seems to be fine. Please record a short demo of the problem you are seeing. You can use a free tool called [licecap ](https://www.cockos.com/licecap/)

**Comment by rjharishabh** [comment]
> Inside components you will find this side navbar. By the way almost all the side navbar is not working properly.

On my side, it's fine

**Comment by PhilETaylor** [comment]
The sidebar, collapses it’s open sub menus on certain screens when you would expect it to stay highlighting a sub menu item. I reported this over a year ago.

**Comment by brianteeman** [comment]
Examples?

**Comment by PhilETaylor** [comment]
> Examples?

Actually it looks a lot better than it used to be - the two I can replicate today are:

Home Dashboard -> Content -> Media -> Loads the Media Manager, Left menu collapses with no item highlighted

Home Dashboard -> System -> Click anything, and System is dehighlighted and menus closed.

**Comment by brianteeman** [comment]
>  I reported this over a year ago.

and it was fixed over a year ago

**Comment by PhilETaylor** [comment]
> and it was fixed over a year ago 
 I give up. I already said I confused this issue with #32032 - no one is perfect.

**Comment by ghost** [comment]
@ghulamrabbani883 Do you still have the issue using the [nightly build](https://developer.joomla.org/nightly-builds.html) too?

**Comment by ghulamrabbani883** [comment]
nothing
