### ISSUE TITLE
[4.0] Frontend: Colour theme "Alternative" show red save- and cancel-button

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33463]
### What needs to be fixed
As title say:

Standard | Alternative
-- | --
![Screenshot_2021-05-01 Template Settings](https://user-images.githubusercontent.com/78906980/116776205-7ec31680-aa67-11eb-9118-f978b2a895d4.png) | ![Screenshot_2021-05-01 Template Settings(1)](https://user-images.githubusercontent.com/78906980/116776209-871b5180-aa67-11eb-9782-920a72fab898.png)

### Why this should be fixed
Different Colours for different actions.

### How would you fix it
Another colour for the Cancel-button.

### Side Effects expected
Don't know.

**Comment by Shubham-com** [comment]
@sandramay0905 Please provide steps to reproduce this issue. Where you got this layout.

**Comment by ghost** [comment]
@Shubham-com Set Colour theme "Alternative" in the template style and open for example the template style in the frontend. You can also open a module or article in frontend.

**Comment by rjharishabh** [comment]
@sandramay0905 It's not perfect red as in Cancel.
It's an `Alternate theme` color

**Comment by saumyasarkar11** [comment]
I don't find any problems like all the blue coloured stuff turn into lighter red including header and all. Since cancel and save are two different shades of red, I think its more or less fine

**Comment by drmenzelit** [comment]
The alternative colour layout for Cassiopeia was only an example on how to do that. If someone has a better idea for a colour schema, please create a PR.
The "save" button has the class `btn-primary` so it will take the colour that is defined as primary in the template.

**Comment by richard67** [comment]
Closing as intended behaviour due to the previous comments.

**Comment by ghost** [comment]
I thought its an UX- and a11y-issue cause the contrast in colour between the buttons is much lower than in the standard-theme.

Sorry to waste your time cause you are the experts, i'm only a user ;-)

**Comment by richard67** [comment]
@sandramay0905 In general you are right, it's just the alternative colour scheme being more a kind of example and not really ready to use.

**Comment by brianteeman** [comment]
> and not really ready to use.

It should be

**Comment by ghost** [comment]
> more a kind of example and not really ready to use.

Thanks for the info, @richard67 I don't wanna hurt someone who have build these alternative colour scheme and invest much time. It's not really ready to use – would this be communicated? If not i fear people will judge Joomla! once again. 

Maybe better to not delivere the alternative scheme? Or rename it like "experimental"? Or deliver it with 4.1 and in a ready-to-use-status?
