### ISSUE TITLE
[4.0] Use of Deprecated attributes in table

### ISSUE THREAD

**Issue by rjharishabh** [joomla/joomla-cms#33467]
### Steps to reproduce the issue
View Source 

https://github.com/joomla/joomla-cms/blob/cc70dbddd29ca586c87574f5a4486e60d28bee9b/layouts/chromes/table.php#L16

### Actual result
cellpadding and cellspacing are deprecated attributes

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/table

**Comment by richard67** [comment]
@rjharishabh Feel free to make a pull request to fix it.

**Comment by brianteeman** [comment]
That definitely should not be there.

**Comment by rjharishabh** [comment]
PR #33469
