### ISSUE TITLE
[4.0] Parentclass not responsive on medium screen size

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#33480]
### Steps to reproduce the issue
With the classes introduced in #32488 it  is fun ordring the tabs new.
I tried with article options now and had this view. 

![grafik](https://user-images.githubusercontent.com/1035262/116805776-f311be80-ab28-11eb-93e4-aac029a57fe3.png)

On small screens (700 px about ) it is responsive. 
![grafik](https://user-images.githubusercontent.com/1035262/116805802-1472aa80-ab29-11eb-8fd2-81dfae603b9f.png)

Use the file from https://github.com/joomla/joomla-cms/issues/33480#issuecomment-830770033 to replicate theis screen.

### Expected result
Responsive also on medium size screens. 

### Actual result
On my laptop it seems that more breakpoints are needed. 
![grafik](https://user-images.githubusercontent.com/1035262/116805759-daa1a400-ab28-11eb-80cb-297be9ed387b.png)

**Comment by brianteeman** [comment]
@chmst could you share that file so its quicker for people to replicate

**Comment by chmst** [comment]
I try 
[default.zip](https://github.com/joomla/joomla-cms/files/6410975/default.zip)

components/com_content/tmpl/article/default.xml

**Comment by brianteeman** [comment]
thank you

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34145 . Thanks in advance.
