### ISSUE TITLE
[4] Control + Option + 9 x 2

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33493]
### Steps to reproduce the issue

Joomla 4 admin console
Press Control + Option + 9
Press Control + Option + 9 again

### Expected result

No clipping of text on right next to the 9

### Actual result

<img width="473" alt="Screenshot 2021-05-02 at 21 32 01" src="https://user-images.githubusercontent.com/400092/116826829-f4290700-ab8d-11eb-8080-b2dfe9924b0f.png">

### System information (as much as possible)

safari on mac

**Comment by Kostelano** [comment]
The same situation in Windows + Firefox.

**Comment by brianteeman** [comment]
confirmed - the box-shadow css is not correct. I will work on this either here or upstream

**Comment by brianteeman** [comment]
Please check #34119 turns out the text being truncated was not a skipto issue

**Comment by richard67** [comment]
Can this issue be closed because PR #34119 solves it? Or is there something remaining?

**Comment by PhilETaylor** [comment]
Closed
