### ISSUE TITLE
[4] Attempt to read property "state" on bool

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33494]
### Steps to reproduce the issue

(Standard error reporting to maximum) 

Index your content with Smart Search Index
Delete all your Content Maps (experience other bug here https://github.com/joomla/joomla-cms/issues/33490)
Create frontnend menu item pointing to search
Navigate to that menu on the front-page
Search for asdfs

### Expected result

No results
No PHP errors

### Actual result

<img width="1015" alt="Screenshot 2021-05-02 at 21 36 15" src="https://user-images.githubusercontent.com/400092/116826922-73b6d600-ab8e-11eb-9412-8c95dabdbdef.png">

**Comment by brianteeman** [comment]
Unable to replicate - maybe it was fixed elsewhere?

**Comment by Hackwar** [comment]
Should be fixed in the meantime.

**Comment by Hackwar** [comment]
@PhilETaylor can you check this again so that we either further investigate or we can close this?

**Comment by PhilETaylor** [comment]
Cannot replicate 8 months after opening.
