### ISSUE TITLE
[4] Deleting content maps only deletes a few (a tree branch) at a time when all is selected

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33490]
### Steps to reproduce the issue

Go to Content Maps -> Select All -> Click Delete

### Expected result

All are deleted

### Actual result

Some are deleted (the first top level parent and its children) only. 

Watch:

https://user-images.githubusercontent.com/400092/116826140-70215000-ab8a-11eb-85db-46aade6d8e19.mp4

**Comment by ghost** [comment]
Confirm the issue.

**Comment by PhilETaylor** [comment]
#33771
