### ISSUE TITLE
[4.0] Article-Image: List need more Space

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33501]
### What needs to be fixed
As title say:

Fine | Need more space
-- | --
![image](https://user-images.githubusercontent.com/78906980/116866561-e6b26200-ac0b-11eb-992a-c383fb71a31b.png) | ![image](https://user-images.githubusercontent.com/78906980/116866482-c5ea0c80-ac0b-11eb-9985-760dd80165c6.png)

### Why this should be fixed
Look better if bullets have more space to the image.

### How would you fix it
Don't know.

### Side Effects expected
Don't know.

**Comment by ChristineWk** [comment]
I think it's here:
![screen shot 2021-05-03 at 12 29 32](https://issues.joomla.org/uploads/1/38edd3813bb2b98404ea921c0e04273a.jpg)

figure.float-start {
    margin-right: 1em;
}<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33501">issues.joomla.org/tracker/joomla-cms/33501</a>.</sub>

**Comment by ghost** [comment]
Thanks for your comment, @ChristineWk I was asking me why the indent of the bullet-list gets lost if there is an pic. I would expect that the indent is always the same.

**Comment by chmst** [comment]
If you use inspect you will see that padding is always the same. But floating is a pain, it was in J3 and is in J4. Soe I have used a trick for sample data. Please hava look on #33559
