### ISSUE TITLE
[4.0] Menu item with access permission throws 404 instead of redirect to logon page.

### ISSUE THREAD

**Issue by Flowman** [joomla/joomla-cms#33500]
### Steps to reproduce the issue

This is done on a multi language site.

Create a menu item with access permission of registered.
Try to access the URL directly in frontend when not logged in.
404 is thrown.

Joomla 3.9 usually redirected the user to the login page. Has this behaviour changed in Joomla 4? Or maybe cloudaccess is broken.

### Expected result

Redirected to login page.

### Actual result

404 is thrown.

### System information (as much as possible)

PHP Built On | Linux lamp106.cloudaccess.net 3.10.0-962.3.2.lve1.5.24.5.el6h.x86_64 #1 SMP Thu Nov 22 10:07:47 EST 2018 
7.3.27
Joomla! 4.0.0-beta8-dev Development [ Mañana ] 2-February-2021 20:02 GMT

**Comment by joomdonation** [comment]
@Hackwar Could you take a look at this issue? Seems the behavior is different with what we are having with Joomla 3.

**Comment by joomdonation** [comment]
OK. I made PR https://github.com/joomla/joomla-cms/pull/33638 to fix it. Please test.
