### ISSUE TITLE
[4] Admin Module - Login Form 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33525]
### Steps to reproduce the issue

You can add the Admin Module - Login Form  to your admin dashboards - this makes literally no sense! 

Also it states you cannot unpublish it - this is a lie, you can, you can click the cog and click unpublish ;) 

<img width="308" alt="Screenshot 2021-05-04 at 00 02 35" src="https://user-images.githubusercontent.com/400092/116943782-2c9f1280-ac6c-11eb-99eb-9cd69b94672f.png">

<img width="1597" alt="Screenshot 2021-05-04 at 00 03 42" src="https://user-images.githubusercontent.com/400092/116943797-3294f380-ac6c-11eb-8895-33d363fc73bf.png">

**Comment by rjharishabh** [comment]
PR #33534

**Comment by brianteeman** [comment]
Not every module is designed to work everywhere. Just as it would be crazy if you put the popular articles module in the toolbar position. The only thing that does need to be changed is the language string. Changing the text from "it can't be" to "it should not be"

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/33534
