### ISSUE TITLE
[4] Frontend statistics module layout

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33526]
Could do with the badges being right aligned?

<img width="355" alt="Screenshot 2021-05-04 at 00 09 21" src="https://user-images.githubusercontent.com/400092/116944260-0a59c480-ac6d-11eb-89c5-26dc2fc69428.png">

**Comment by brianteeman** [comment]
Please test/try this when the module is correctly set to be 50% width of the screen. (your install isn't quite up to date so go to the module and set the bootstrap width to 12)

**Comment by PhilETaylor** [comment]
This is on the frontend. In the right column of the frontend.

**Comment by PhilETaylor** [comment]
<img width="1597" alt="Screenshot 2021-05-04 at 08 34 39" src="https://user-images.githubusercontent.com/400092/116972871-94c51700-acb3-11eb-93c2-d846ba9db50a.png">

**Comment by brianteeman** [comment]
sorry mea culpa. Commenting on so many admin modules I missed this was for the frontend

**Comment by ghost** [comment]
@PhilETaylor can you please close the issue as pr #33533 is meanwhile merged?
