### ISSUE TITLE
[4] PHP 8 named parameters issue - Cannot edit content with 3rd party editor

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33529]
### Steps to reproduce the issue

Install JCE
Enable JCE in Global Config
Edit an article

### Expected result

Ability to edit an article

### Actual result

PHP 8 has named parameters!!! This I believe is a Joomla PHP 8 issue and not one to blame JCE for! 

Note that the error and stack trace point to a Joomla set of files and not JCE - **so please DONT close this or write it off as a JCE issue without debugging!!!** If it effects JCE, its probably going to effect other editors ... 

<img width="1596" alt="Screenshot 2021-05-04 at 00 18 21" src="https://user-images.githubusercontent.com/400092/116944887-417ca580-ac6e-11eb-9d74-0a47e9929646.png">

### System information (as much as possible)

PHP 8+ its broken

With PHP 7.4 it works perfectly.

<img width="1240" alt="Screenshot 2021-05-04 at 00 30 24" src="https://user-images.githubusercontent.com/400092/116945601-fcf20980-ac6f-11eb-8f82-aef06f231f4d.png">

### Additional comments

@ryandemmer @widgetfactory

**Comment by ryandemmer** [comment]
Thanks @PhilETaylor 

I've just run a little test where I clear the contents of all methods in the plugins/editors/jce.php file, and disabled all other JCE plugins, and the above error still occurs.

This is obviously not caused by any process within JCE.

**Comment by PhilETaylor** [comment]
It kinda is and kinda is not a JCE issue. But its one that Joomla should fix too.

It will only happen on PHP 8 due to the name arguments feature and the way Joomla calls the JCE method with `call_user_func`

its because JCE is missing the `$params` from its method - but equally Joomla should be able to cope with that.

**Comment by joomdonation** [comment]
If JCE has $params parameter in `onDisplay` method, the error would not happen. The code in Joomla has been there for sometime, so we could also that it is something JCE should fix to be compatible with PHP 8 :).

**Comment by ryandemmer** [comment]
Oh I see! An easy fix for me then.

I blame it on the fact that yesterday was a bank holiday here, so today is basically a Monday... ;)

**Comment by joomdonation** [comment]
@ryandemmer Yes, an easy fix for you and I'm sure you won't complain about it :).

**Comment by ryandemmer** [comment]
> If JCE has $params parameter in `onDisplay` method, the error would not happen. The code in Joomla has been there for sometime, so we could also that it is something JCE should fix to be compatible with PHP 8 :).

Yeah you are right. Fixed in the next update.

**Comment by PhilETaylor** [comment]
or Joomla could call `$this->_editor->onDisplay(...$args)` which would not cause a PHP 8 named arguments issue

**Comment by ryandemmer** [comment]
> or Joomla could call `$this->_editor->onDisplay(...$args)` which would not cause a PHP 8 named arguments issue

😂

**Comment by ssnobben** [comment]
Should be fixed now for JCE Pro 2.9.7 Beta 7 updated. 
Changelog Beta 7 Fixed
    -Attempting to load the editor in Joomla 4 with PHP 8 would produce an error.
    -Setting a comma seperated mediatype value, eg: mediatype="jpg,jpeg" for a custom Media - JCE field would produce an invalid mediatype list.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33529">issues.joomla.org/tracker/joomla-cms/33529</a>.</sub>

**Comment by PhilETaylor** [comment]
same thing different place https://github.com/joomla/joomla-cms/pull/35675

**Comment by alexandreelise** [comment]
Thanks @PhilETaylor for helping Joomla! being PHP8.0 compliant. When I see that PHP8.1 should come out in november and we need to do that again. Hopefully it won't break that much since it's a minor version  PHP8.1. Take care you all Super Joomlers!

**Comment by dgrammatiko** [comment]
Please close

**Comment by PhilETaylor** [comment]
The "more correct" fix is to modernise the code to ensure that it takes into account PHP 8 features, including Named Parameters, although there seems little appetite for that in the Joomla code base.

We should stop telling 3pd to fix their stuff - again, and implement a more bullet proof solution in Joomla which is simple to remove calls to call_user_func* functions or, pass those functions a non-keyed array by using the array_values() fix to strip the keys.

See also https://github.com/joomla/joomla-cms/pull/35675

But once again Joomla doesnt care about modernising the codebase and prefers to get 3pd to work around the limitations.
