### ISSUE TITLE
[4] Admin Module - Post Installation Messages

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33524]
### Steps to reproduce the issue

Add the Admin Module for Post Installation Messages to an admin dashboard. Note this is what the module says it does:

<img width="304" alt="Screenshot 2021-05-04 at 00 00 18" src="https://user-images.githubusercontent.com/400092/116943601-d205b680-ac6b-11eb-9b1b-bfda0d47f07f.png">

### Expected result

A list of the messages, not a bell and the number looking weird

### Actual result

<img width="666" alt="Screenshot 2021-05-04 at 00 02 05" src="https://user-images.githubusercontent.com/400092/116943689-fbbedd80-ac6b-11eb-955d-21e5f0c5b963.png">

I think this is because this is the module used in the toolbar maybe? but still - it promises one thing and delivers another

**Comment by brianteeman** [comment]
Not every module is designed to work everywhere. Just as it would be crazy if you put the popular articles module in the toolbar position. The only thing that does need to be changed is the language string. Changing the text from "shows the latest" to "shows the count and links to the latest"

**Comment by brianteeman** [comment]
Please test #33625
