### ISSUE TITLE
[4] Admin Module Link To Frontend style/icon issues

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33520]
### Steps to reproduce the issue

Add an Admin Module of type link to frontend to an admin dashboard

https://user-images.githubusercontent.com/400092/116942703-011b2880-ac6a-11eb-8b12-e179515d5375.mp4

### Expected result

A link to the frontend - maybe prepended with a single icon

### Actual result

<img width="1309" alt="Screenshot 2021-05-03 at 23 52 12" src="https://user-images.githubusercontent.com/400092/116943006-9f0ef300-ac6a-11eb-8e4f-2aa4bfccb5a8.png">

A link to the frontend - prepended with two icons and a spacing issue

### System information (as much as possible)

safari on mac

**Comment by rjharishabh** [comment]
PR #33535

**Comment by brianteeman** [comment]
Please see #34064 - maintainers (or you) can decide if its a fix or not

**Comment by richard67** [comment]
If someone asks me, the PR is a sufficient fix.

**Comment by PhilETaylor** [comment]
I would say that the PR "solves" enough to get away with closing this issue, but I dont like the fact that we have a module that cannot be reused and is highly specific to a certain place at a certain time.

For example, I might want to display the Joomla version somewhere else, in the footer, on my site, or anywhere

Maybe these modules that are ONLY used to build the Joomla admin interface should be locked/hidden from being reused elsewhere...
