### ISSUE TITLE
[4] Admin Module Feed Display doesn't display feed images right

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33523]
### Steps to reproduce the issue

Add a new Admin Module of type Feed Display with feed with images in its feed - use url https://rss.art19.com/apology-line for example right now. 

### Expected result

All images in RSS feeds are constrained by the proportions of the module

### Actual result

<img width="1605" alt="Screenshot 2021-05-03 at 23 56 54" src="https://user-images.githubusercontent.com/400092/116943388-628fc700-ac6b-11eb-8bc7-c5757a52ec46.png">

**Comment by ghost** [comment]
Confirming this issue, thanks for finding this @PhilETaylor :-)

**Comment by rjharishabh** [comment]
Please test #33543
