### ISSUE TITLE
[4] Admin Module Joomla! Version Information layout issues

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33522]
Add admin module Joomla! Version Information to a dashboard - see the stretched output and icon/version disconnected

<img width="1309" alt="Screenshot 2021-05-03 at 23 52 12" src="https://user-images.githubusercontent.com/400092/116943025-ab934b80-ac6a-11eb-98ee-a1750f4ba0d3.png">

**Comment by rjharishabh** [comment]
PR #33535

**Comment by brianteeman** [comment]
Not every module will work in every position. Just as you cant expect the popular articles wont wok in the icon position

**Comment by PhilETaylor** [comment]
When you click Add Module to the dashboard then it should only show the modules that do make sense, and not those that don't make sense to add to a dashboard. Probably (not checked) one simple if statement Im guessing - if in a modal then dont show modules that make no sense on a dashboard

**Comment by PhilETaylor** [comment]
...for core modules, obviously for 3rd party admin modules it would be harder to distinguish them

**Comment by brianteeman** [comment]
currently that would be impossible to achieve

**Comment by PhilETaylor** [comment]
I swear sometimes you tell me something is impossible just so that I will prove its possible... oh well.

**Comment by brianteeman** [comment]
that was why the sentence began with "currently"
