### ISSUE TITLE
[4] Behind Load Balancer radio button change needed now merged from Joomla 3

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33527]
### Steps to reproduce the issue

Joomla Global Config -> Server Tab

<img width="924" alt="Screenshot 2021-05-04 at 00 11 34" src="https://user-images.githubusercontent.com/400092/116944416-60c70300-ac6d-11eb-87cd-019941d2d1d2.png">

**Comment by brianteeman** [comment]
please test #33539
