### ISSUE TITLE
[4] Select a module type search box size tiny on some breakpoints

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33521]
### Steps to reproduce the issue

Click to add a module to an admin dashboard at different browser sizes 

https://user-images.githubusercontent.com/400092/116942896-6242fc00-ac6a-11eb-92c4-75b5144c4fde.mp4

### Expected result

A search box that is not so tiny at some breakpoints and should be aligned to the centre or left

### Actual result

tiny search box at some breakpoints - aligned off centre

### System information (as much as possible)

safari on mac

**Comment by brianteeman** [comment]
~Can you see if its still a problem for you with the repainted template. I couldnt seem to replicate it myself~

Scrub that - its still a problem but just in the modal
