### ISSUE TITLE
[4] Versions modal toolbar all blue buttons

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33531]
### Steps to reproduce the issue

Click Versions when editing an existing article 

### Expected result

Toolbar in keeping with Joomla style

### Actual result

All blue icons including delete
Mouseovers to grey-ish

<img width="1302" alt="Screenshot 2021-05-04 at 00 32 23" src="https://user-images.githubusercontent.com/400092/116945684-362a7980-ac70-11eb-940e-10a3f6bacd7e.png">

**Comment by rjharishabh** [comment]
PR #33532

**Comment by alikon** [comment]
please test #33532
