### ISSUE TITLE
Slow Joomla Websie

### ISSUE THREAD

**Issue by tpss** [joomla/joomla-cms#33537]
Hi,

   I have working on joomla website. When I have update the joomla version and php version the site show slow response. When i have placed an order and get the response after 1 to 2 min. Please let me know the solution.

Thanks

**Comment by ghost** [comment]
Sorry to hear your problem. Can you please ask at https://forum.joomla.org/ cause here is the place for developing of joomla.

Please close the issue.

**Comment by ssnobben** [comment]
This is a typical WP et al tribe spam to discourage Joomla. There is no url no info for this nonsens post. 

Joomal 4 is extremly fast! And real people that need a very good cms that is flexible, fast, secure for any company, organsation, blog or project knows that. :)  

Close this spam.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33537">issues.joomla.org/tracker/joomla-cms/33537</a>.</sub>

**Comment by chmst** [comment]
Closing until more and precise information is given
