### ISSUE TITLE
PR Calendar change event #32756 causes onchange event handler to fire twice

### ISSUE THREAD

**Issue by GeraintEdwards** [joomla/joomla-cms#33538]
### Steps to reproduce the issue
Edit the file administrator/components/com_content/forms/article.xml and find the publish_up field at line 129 and add the attrtribute

onchange="alert(0);"

to this field and then edit and article and change the publish_up field (using the date picker)

### Expected result

alert(0) message is fired once

### Actual result

alert(0) message is fired twice

**Comment by alikon** [comment]
please test #33540
