### ISSUE TITLE
[4.0] [Cassiopeia] Template Settings: invalid button class

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33546]
### Steps to reproduce the issue
Install the demo data (for example), go to the frontend, log in, select the Template Settings item in the right menu, pay attention to the button for choosing a logo.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/117041188-5fe8ac80-ad13-11eb-90d5-a26952a5149c.png)

In addition, when choosing a logo in the modal horse, "stuck together" buttons were found.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/117041541-a938fc00-ad13-11eb-9d54-800ad20a99da.png)

Joomla Beta8-dev (night build)

**Comment by rjharishabh** [comment]
For buttons in Toolbar PR #33403

**Comment by rjharishabh** [comment]
This class is used in Javascript files, not CSS

**Comment by ghost** [comment]
### Button class is now solved:

> ![image](https://user-images.githubusercontent.com/78906980/117452434-0b784380-af44-11eb-99a2-804344ff5b02.png)

### "Stuck together"-buttons:
Pull request #33403 is in the meantime ready to commit.
