### ISSUE TITLE
[4.0] [Cassiopeia] Editing a module: extra <hr> tag

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33547]
### Steps to reproduce the issue
Install the demo data, go to the front-end and click on edit any module. Note that there is an extra `<hr>` tag at the very end of the parameter list.

![Screenshot_3](https://user-images.githubusercontent.com/8440661/117044349-01253200-ad17-11eb-93bb-9617a6cd14b9.png)

Joomla Beta8-dev (night build)

**Comment by chmst** [comment]
Closing this as there is a PR
