### ISSUE TITLE
[4] Blog layout all categories selector

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33556]
### Steps to reproduce the issue

Create a new menu item in Joomla 4 admin -> Select Blog Layout Tab -> look at the category selector

### Actual result

<img width="1076" alt="Screenshot 2021-05-05 at 10 58 29" src="https://user-images.githubusercontent.com/400092/117124970-e394ae80-ad90-11eb-940b-36282cd4c1d6.png">

**Comment by brianteeman** [comment]
Took me a while to find it but this is actually the features articles menu item not blog category

**Comment by brianteeman** [comment]
The problem comes because of the default value - not sure how to fix it though

**Comment by chmst** [comment]
The same for archived articles. 
Archived articels an featured articles should use the field in the same way both should have the field category in the details tab,
A possible solution is to use the same field definition as in filters.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37140 . Thanks in advance.
