### ISSUE TITLE
[3.9] _jsonEncode in table not working with object

### ISSUE THREAD

**Issue by Flowman** [joomla/joomla-cms#33553]
### Steps to reproduce the issue

When storing a object to the table and _jsonEncode is set on the table, it will fail with 'Cannot use object of type stdClass as array'.

It is because only supports arrays but the rest of the bind function supports both arrays and objects. https://github.com/joomla/joomla-cms/blob/2b7a904b9f981a4526e7ffa05c4aa83bbfc39617/libraries/src/Table/Table.php#L602

This has been fixed in 4.0

### Expected result

Storing the data should be successful. 

### Actual result

Error 'Cannot use object of type stdClass as array'

### System information (as much as possible)

Joomla 3.9.26

**Comment by richard67** [comment]
In J4 it was fixed with #25761 . Unfortunately that PR doesn't tell anything about it in its title or description, it just mentions tests being added :-(
We should back-integrate the fix for handling objects from that PR into 3.10-dev.
I'll prepare a PR soon.

**Comment by richard67** [comment]
The pull request with a fix for this issue for 3.10 is almost ready. It only needs testing instructions, but that would need to write some little PHP class and test program. @Flowman  Do you have some extension which we could use for testing?

**Comment by richard67** [comment]
PR is #33558 .

**Comment by Flowman** [comment]
@richard67 not really. I got this quiz or lms component I am building but its to large. 

But I know the changes you are doing is working, as I did the same hack to the core on my test site.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33558 . Thanks in advance.

**Comment by richard67** [comment]
New pull request is #33633 for 3.9. Please test. Thanks in advance.
