### ISSUE TITLE
Atom template login issues

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#33567]
Hi guys, 
PHP 7.4.16 + Joomla 4 beta 7 + screen 16:9 - 1366 x 768 px

**1** - As you can see [from my image](https://photos.app.goo.gl/kX7xUD7coWyp7bZg6 "from my image") there is a lot of blank space wasted that is causing an unnecessary vertical scrolling
Solution = to delete part of the blank spaces to avoid, as far as possible, vertical scrolling on smaller screens

**2** - also the small triangle user icon, [here the image](https://photos.app.goo.gl/mr8z2j1kyagy5MfW6 "here the image"), it is really unnecessary and it is causing just an awful layout
Solution 0 to delete it and leave just the user icon

**Comment by ghost** [comment]
you can put your images in your comment.

**Comment by brianteeman** [comment]
see #33570 for part 1

I dont agree with you on part 2

**Comment by brianteeman** [comment]
I closed #33570 as this has now been resolved elsewhere with the repainted atum template just merged

**Comment by brianteeman** [comment]
I am guessing part 2 is no longer relevant either?
![image](https://user-images.githubusercontent.com/1296369/117279007-2e79f900-ae59-11eb-9097-e608d72fa1fc.png)

**Comment by richard67** [comment]
I agree with @brianteeman to disagree with @joomleb on part 2 ;-)

The arrow icon is there to show that it is a dropdown.

**Comment by joomleb** [comment]
Hi guys, 
many thanks for the answers:

1 - Thanks

2 - It seems polite of me to explain my simple point of view:
- Today Web menas Touch and Mobile (often small screens) 
- as a matter of fact Joomla 4 promise to bring 
- -- "...Brand new User Interfaces: (backend and frontend): intuitive and logical, easy to understand and use..." 
- -- "...Web Services: Make your content accessible to other websites and for easy mobile app creation..."
- -- "...A cleaner and more powerful codebase:..."
- The first step to do it is to keep all as simple as possible, to don't waste energies and "screen space"
- About UI the Material Design is a very good example
- ...etc
So, for me in 2021, to have to add the "fas fa-chevron-down" to say people to open (in that case, the user icon) it has no any sense for me because all the Google Apps (Gmail, Maps, Photo, Chrome...) have just the circle user icon in the same position, there is nothing to "teach" / "explain" to the users, is so intuitive, is part of our life... the Geroglific is back :)
It is like to waste languages strings / your precious energies  and time / UI screen space, by adding the word "search" to the "fas fa-search", really in the 2021 have no sense anymore....
Just it

**Comment by chmst** [comment]
agree. From developers point fo view it is a big difference whether a link goes to another page or if a button expands a dropdown. But not for the user.

**Comment by brianteeman** [comment]
I am still convinced that this is not a bug and that the down arrow is absolutely required to indicate that its a dropdown and not a button

**Comment by Hackwar** [comment]
I agree that this is not a bug. Closing this one.
