### ISSUE TITLE
[4.1] add a link to the Jooma icon 

### ISSUE THREAD

**Issue by srishty-07** [joomla/joomla-cms#33561]
### Problem identified
![image](https://user-images.githubusercontent.com/70388131/117181889-53d41c00-adf3-11eb-84d2-928e67717b51.png)
![image](https://user-images.githubusercontent.com/70388131/117181908-5a629380-adf3-11eb-9317-85f6491294ba.png)
 
There is no link added to the Joomla icon on these pages.

### Proposed solution
Though we can go back to the main home page by  clicking the buttons like save, save and close, I think,
A link should be added, redirecting the user to the main home page of Joomla.

**Comment by brianteeman** [comment]
It is deliberate that there is no link on an edit page as this would result in the record being locked

**Comment by srishty-07** [comment]
> It is deliberate that there is no link on an edit page as this would result in the record being locked

Thanks @brianteeman , for telling the reason .
