### ISSUE TITLE
[4.0] Backend: Module-cog need space

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33566]
### What needs to be fixed
If title is long it gets to close to cog (example use sample data):

![image](https://user-images.githubusercontent.com/78906980/117243798-2d849f80-ae38-11eb-8a55-b4320ecccbe4.png)

### Why this should be fixed
Look better if title is automatic in 2 lines if the text is near the cog.

### How would you fix it
Margin/padding around cog.

### Side Effects expected
Don't know.

**Comment by rjharishabh** [comment]
Makes the title long

![title-cog](https://user-images.githubusercontent.com/61203226/117245216-1655aa00-ae58-11eb-9085-e08a54f068df.JPG)

**Comment by ghost** [comment]
> Makes the title long

Sorry, i don't understand what you mean.

**Comment by ghost** [comment]
Closing, pull request #33569 fix the issue.
