### ISSUE TITLE
[4] footer items on mobile - swap sides

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33565]
### Steps to reproduce the issue

Use Joomla 4 on mobile

Confusing to (my tiny brain to) have a left hand menu (normally) now become a right hand burger, and a top right menu now become a bottom left menu - would recommend swapping the right burger with the left ep... for consistency so that the left bottom click is the main menu (that is normally on the left when full screen) 

https://user-images.githubusercontent.com/400092/117196080-f4b7dc80-addd-11eb-8d93-ca05395ab74e.mp4

**Comment by brianteeman** [comment]
as someone who is right handed I appreciate that this major functionality is positioned on the right

**Comment by PhilETaylor** [comment]
Then at least make it configurable because not everyone is right-handed￼

**Comment by brianteeman** [comment]
yes please lets have more options

**Comment by PhilETaylor** [comment]
Really, all they need to be positions in the template that can be assigned modules to. Simple￼. Even you could probably do it.￼

**Comment by brianteeman** [comment]
no one said it was hard

**Comment by PhilETaylor** [comment]
Let me label this an accessibility issue then (which it is), and then maybe you'll be interested￼
