### ISSUE TITLE
[4][atum] Fieldset Legends no longer clear they are a Fieldset Legend

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33571]
Extensions installer 

Fieldset Legends no longer clear they are a Fieldset Legend and just duplicate content below it. 

<img width="776" alt="Screenshot 2021-05-06 at 10 12 12" src="https://user-images.githubusercontent.com/400092/117272971-988f9f80-ae53-11eb-8923-17b7616d6b45.png">
<img width="710" alt="Screenshot 2021-05-06 at 10 12 09" src="https://user-images.githubusercontent.com/400092/117272975-99c0cc80-ae53-11eb-83f9-a13ba4944e0f.png">

**Comment by rjharishabh** [comment]
If this is the URL `http://localhost/joomla-cms/administrator/index.php?option=com_installer&view=install` then In my repo this issue is not present

![folder_install](https://user-images.githubusercontent.com/61203226/117278101-14064680-ae7e-11eb-9775-646a54b9db91.JPG)
![URL_install](https://user-images.githubusercontent.com/61203226/117278106-15d00a00-ae7e-11eb-9279-cbf9ce10bab1.JPG)

**Comment by PhilETaylor** [comment]
well your screenshots also dont show the right tabs so Im guessing you have not updated your 4.0-dev repo since the new admin template changes were merged today.

**Comment by brianteeman** [comment]
It's also an issue when there are multiple fieldsets on the page as you can no longer easily see where one starts and the other ends

**Comment by PhilETaylor** [comment]
> It's also an issue when there are multiple fieldsets on the page as you can no longer easily see where one starts and the other ends

Example of that is the integration tab of Options for Articles:

<img width="1297" alt="Screenshot 2021-05-06 at 11 02 18" src="https://user-images.githubusercontent.com/400092/117280504-92e98800-ae5a-11eb-8e5a-34d7ae9e3c86.png">

**Comment by rjharishabh** [comment]
Now updated

**Comment by PhilETaylor** [comment]
Miscellaneous Information x 3

<img width="724" alt="Screenshot 2021-05-06 at 18 02 15" src="https://user-images.githubusercontent.com/400092/117337385-38215200-ae95-11eb-8073-18142a252adf.png">

**Comment by brianteeman** [comment]
Please test #33729
