### ISSUE TITLE
[4.0] Redirect: Uncaught TypeError: this._element is undefined

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#33579]
### Steps to reproduce the issue
Go to System > Redirects
Click Redirect System Plugin link.
See browser's console.

### Actual result
> Uncaught TypeError: this._element is undefined modal.js:538:5

**Comment by dgrammatiko** [comment]
@Quy can you confirm that the markup is something similar to this (the important bit is the `data-bs-toggle` here):

![Screenshot 2021-05-06 at 18 47 35](https://user-images.githubusercontent.com/3889375/117335531-8c2f3500-ae9b-11eb-98a2-3054b6e13b87.png)

It works fine here without any errors so maybe you are using a language that has not updated the string yet?

**Comment by Quy** [comment]
Same as yours except for the attributes order.

![33579](https://user-images.githubusercontent.com/368084/117336713-5d8c6c80-ae51-11eb-9600-60669f91fcf7.jpg)

**Comment by Quy** [comment]
It appears to be an issue when no entries (empty state).

**Comment by dgrammatiko** [comment]
> It appears to be an issue when no entries (empty state).

Ok, I will check where that could be failing

Edit: so there's a flaw in the empty state pages. The empty page overrides completely the default layout which in this case skips the rendering of the markup for the Modal and also skips loading the appropriate scripts. @PhilETaylor can we move the call for the empty page layout inside the default layout with the appropriate conditional? The other solution is to also pass the modal markdown to the empty page layout (less ideal as it won't be overridable). Another solution is to refactor the whole Modal factory but this is a bit bigger scope...

**Comment by PhilETaylor** [comment]
or just change the link to be `/administrator/index.php?option=com_plugins&filter[search]=System%20-%20Redirect`

**Comment by dgrammatiko** [comment]
> or just change the link to be /administrator/index.php?option=com_plugins&filter[search]=System%20-%20Redirect

Actually, the link right now opens a modal for editing the state so you don't have to navigate away and come back. I don't mind changing the href but I guess there will be ppl that will complain that we destroying Joomla, etc... 😀

**Comment by PhilETaylor** [comment]
Modals within modals on mobile soon break this workflow :)

**Comment by PhilETaylor** [comment]
There was a modal thing in empty state, forget which view its in... one mo

**Comment by PhilETaylor** [comment]
Search Joomla for "formAppend" and you will see the example where I had to append 'bootstrap.renderModal' for com_redirect

**Comment by PhilETaylor** [comment]
>  @PhilETaylor can we move the call for the empty page layout inside the default layout with the appropriate conditional?

No. This is how I did it originally - and it lasted a few hours before @Bakual came along and said "lets use a layout instead" :-)

**Comment by dgrammatiko** [comment]
> No. This is how I did it originally

I think we need to bring this bac, the modal for this link is rendered here: https://github.com/joomla/joomla-cms/blob/b19e7e2a79d1fbb4a93846b32b6000128320d902/administrator/components/com_redirect/tmpl/links/default.php#L28-L52

**Comment by Bakual** [comment]
Umm, just add that part also to the emptystate layout of com_redirect. What is the problem? We do the same already for the batch modal.

**Comment by PhilETaylor** [comment]
Already one step ahead :) 

<img width="1597" alt="Screenshot 2021-05-06 at 19 35 13" src="https://user-images.githubusercontent.com/400092/117348534-3611c000-aea2-11eb-9d67-c4b814e7e5f0.png">

**Comment by Bakual** [comment]
Faster: https://github.com/joomla/joomla-cms/pull/33588 :-p

**Comment by PhilETaylor** [comment]
<img width="785" alt="Screenshot 2021-05-06 at 19 36 31" src="https://user-images.githubusercontent.com/400092/117348662-60637d80-aea2-11eb-9678-c0e029c4ef61.png">

RTC quick ;-)

**Comment by Bakual** [comment]
Details :-p

**Comment by Quy** [comment]
PR #33588. Thanks.
