### ISSUE TITLE
[4.0] Atum - Header Logo

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#33577]
.header .logo img, .header .logo svg

### Actual result
see screenshot afterwards 
### System information (as much as possible)

4.0.0-2021-05-01 | ‎4.0.0-beta8-dev from today
-- | --

### Additional comments
Maybe is it only me? :-)

**Comment by ChristineWk** [comment]
Actual - Backend:
![screen shot 2021-05-06 at 11 20 15](https://issues.joomla.org/uploads/1/b45d9ee23591d51d31239dcce361e71c.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33577">issues.joomla.org/tracker/joomla-cms/33577</a>.</sub>

**Comment by YatharthVyas** [comment]
I had this issue but it got fixed when I restarted my XAMPP server:
![image](https://user-images.githubusercontent.com/53610833/117290530-8a5d7580-ae8b-11eb-9bc2-6f7df24e2d3d.png)

Could you try these:
- Clear Cache 
- Restart Server

**Comment by ChristineWk** [comment]
@YatharthVyas 

Thank you. What an easy and quick fix :-) Before, I was searching the CSS etc.
Therefore I will close. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33577">issues.joomla.org/tracker/joomla-cms/33577</a>.</sub>

**Comment by piotr-cz** [comment]
Duplicate of #33889 (Fixed with reloading with browser cache clear)
