### ISSUE TITLE
[4.0] [Atum] Display of the prompt "Please fill in this field" is broken 

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33587]
### Steps to reproduce the issue
For example, go to Control Panel -> Users (Fields), create a new field and try to save it without entering any information.

The tooltip will be displayed in the wrong place + large enough font size. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/117346411-5fd1e380-aeb0-11eb-81bd-fd80ab35b85c.png)

**Comment by Kostelano** [comment]
This behavior is observed everywhere I try to save an element without a name / title.

**Comment by ghost** [comment]
Confirm the issue.

**Comment by brianteeman** [comment]
Please test #33623

**Comment by alikon** [comment]
closing as we have a pr
