### ISSUE TITLE
[4] Versions toolbar now very colourful 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33585]
### Steps to reproduce the issue

Hit versions toolbar button to get model

### Expected result

Toolbar in keeping with Joomla "standard" look (Colourful icon, plain text, colour on hover, text colour inverse on hover) 

### Actual result

<img width="1294" alt="Screenshot 2021-05-06 at 18 04 20" src="https://user-images.githubusercontent.com/400092/117337839-c85f9700-ae95-11eb-89e9-cbc22c1b39cb.png">

### System information (as much as possible)

safari on mac

**Comment by brianteeman** [comment]
please test #33616

**Comment by alikon** [comment]
closing as we have a pr

**Comment by PhilETaylor** [comment]
Please reopen after the spoilt child threw his toys out his pram after submitting a PR that did not address the problem.

**Comment by PhilETaylor** [comment]
[4] Correctly implement Joomla toolbar in Versions popup #33632
