### ISSUE TITLE
[4][Atum] Unloading of tool tips gives unflattering unstable flicker

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33589]
This example on the Articles list view, but probably a global issue. Also quite slow to load the tooltip too. Video is in realtime.

Safari on mac.

https://user-images.githubusercontent.com/400092/117349194-03b49280-aea3-11eb-8a44-7496f19f8575.mp4

**Comment by Quy** [comment]
PR #33557 will replace BS popover with css.

**Comment by PhilETaylor** [comment]
thanks I'll test that later
