### ISSUE TITLE
[4][Mail Templates?] User Action Log emails are HTML sent in plain text. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33586]
### Steps to reproduce the issue

Install Joomla 4.0-dev 
Login to admin as your admin
Go to top right and Usermenu -> edit your account -> User Action Logs Options
Email Notifications =  Yes 
Check all boxes
Save and close
Content -> Articles -> New -> Give it a title -> save and close

Go check your emails. 

### Expected result

Either a HTML email sent in HTML mode or a plain text email sent in plain text mode with no HTML markup 

### Actual result

HTML email sent in plain text mode with HTML markup

Full email source:

```
Content-Type: text/plain; charset=utf-8
Date: Thu, 6 May 2021 17:32:17 +0000
From: joomla4 <phil@phil-taylor.com>
MIME-Version: 1.0
Message-ID: <ezRVdWZWtPaBuioIUwMWsIKIrpWtfoeMjAX5DYxJc@localhost.localdomain>
Received: from localhost.localdomain by mailhog.example (MailHog)
          id ScxpOquk3uhHASxBGlCDwG8y3974VdzRbAq5K6gajOI=@mailhog.example; Thu, 06 May 2021 17:32:17 +0000
Return-Path: <phil@phil-taylor.com>
Subject: Latest User Actions
To: "phil@phil-taylor.com" <phil@phil-taylor.com>

Latest User Actions
------
This is the latest action performed by a user on your website.

 Action | Date | Extension | Name
 User <a href="http://127.0.0.1:4444/administrator/index.php?option=com_users&task=user.edit&id=570">admin</a> added new article <a href="http://127.0.0.1:4444/administrator/index.php?option=com_content&task=article.edit&id=1">erv</a> | 2021-05-06 17:32:17 UTC | Articles | admin

```

**Comment by ghost** [comment]
Confirm the issue.

**Comment by joomdonation** [comment]
With the way action logs work (contains link to access to the item), should we always use HTML email for it?

**Comment by PhilETaylor** [comment]
>  should we always use HTML email for it?

Depends if Mail Templates is going to stay for Joomla 4. If Mail Template is staying, then these emails should be configurable in Mail Templates and therefore a plain text version and a HTML version need to be available at the whim of the site admin.
