### ISSUE TITLE
[4] Collapsing title bar movement after page load

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33584]
### Steps to reproduce the issue

Its cute at first but grows annoying quickly

Movement after page load should be minimised for many reasons, this one serves no purpose.

As the page loads the top left collapses, pulling over the title 

(To be clear, im not talking about the left menu, but the very top toolbar) 

### Expected result

Minimal movement after page load

### Actual result

https://user-images.githubusercontent.com/400092/117337094-d9f46f00-ae94-11eb-80e8-73ae4fdf1150.mp4

### System information (as much as possible)

Safari on mac

**Comment by ghost** [comment]
Cannot confirm it (safari, firefox /mac):

![1](https://user-images.githubusercontent.com/78906980/118647059-35055a80-b7e1-11eb-84a7-b778be33aa8a.gif)

**Comment by PhilETaylor** [comment]
Thats because @dgrammatiko broke it (or fixed it?)  in a recent PR :)

**Comment by ghost** [comment]
@dgrammatiko Thanks for fixing the issue :-)

**Comment by brianteeman** [comment]
Shouldnt this be closed then ?
