### ISSUE TITLE
[4] Media clear button

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33583]
One for you @dgrammatiko probably a quick fix for you :) 

<img width="313" alt="Screenshot 2021-05-06 at 17 56 05" src="https://user-images.githubusercontent.com/400092/117336704-68b4bc00-ae94-11eb-887c-98afeda0917f.png">

When this custom element loads without any image already selected, there is the red/white X button that is redundant. 

Would be nice to hide that button until the element has an image selected? Because at the moment its not "disabled" but clicking it makes no sense and does nothing :)

**Comment by dgrammatiko** [comment]
on my list

**Comment by PhilETaylor** [comment]
Ta

**Comment by laoneo** [comment]
Please test #34620.
