### ISSUE TITLE
[4.0] Displaced element color selection box

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33596]
### Steps to reproduce the issue
Go to Plugins - Editor (Codemirror), pay attention to the parameters - the color selection block is slightly offset relative to the field line.

Not sure if it was intended that way.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/117361282-826cf800-aec2-11eb-8710-c630537d2333.png)

**Comment by PhilETaylor** [comment]
same on edit template styles page too 

<img width="699" alt="Screenshot 2021-05-06 at 22 26 19" src="https://user-images.githubusercontent.com/400092/117367451-1d150900-aeba-11eb-92b9-86a4fbcb98cb.png">

**Comment by brianteeman** [comment]
please test #33611
