### ISSUE TITLE
[4.0] Centered Cards a bit broken in Atum

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#33592]
### Steps to reproduce the issue
I use a centered Bootstrap card in my component where I have an icon as header and text as body. This used to look fine together with `text-center`.
With https://github.com/joomla/joomla-cms/pull/33100, the header icon is now aligned left.
From what I see, the reason comes from this line here: https://github.com/joomla/joomla-cms/blob/b19e7e2a79d1fbb4a93846b32b6000128320d902/administrator/templates/atum/scss/vendor/bootstrap/_card.scss#L28

### Expected result
![image](https://user-images.githubusercontent.com/1018684/117352922-d5897f80-aeaf-11eb-8fc4-00cb51006737.png)

### Actual result
![image](https://user-images.githubusercontent.com/1018684/117352428-49775800-aeaf-11eb-9252-d966a17b70e0.png)

### Additional comments
I'm not sure if this was an intentional change by @ciar4n that each instance of cards are changed. Maybe he only wanted to change specific uses?

**Comment by Bakual** [comment]
Btw, also the background of the header is now white, while it was a bit greyish before. Imho it looked better with the slightly different background color, but I'm no designer - so won't argue 😄 
Merely wondering if that was intentional as well.

**Comment by ciar4n** [comment]
Yes the card header was changed to flex with the recent repaint. Flex was just better suited for handling the multiple header elements in some of the cpanel cards,

As its a flex container you can use the BS `m-auto` class on the element you wished centered (presuming this is the only element in the header). You can also add the BS class `justify-content-center` to the card header instead.

**Comment by ciar4n** [comment]
Just going back a bit, it looks like the white card headers have been there for a while. Im not sure at what point they changed.

**Comment by Bakual** [comment]
Thanks, I'll try then with the other classes you mentioned.
The white card headers were part of your PR or some commits after it. My first screenshot is the state of the repo directly before the merge of your PR 😃

**Comment by Bakual** [comment]
The suggested classes worked for re-centering the header, that's fine.

> Just going back a bit, it looks like the white card headers have been there for a while. Im not sure at what point they changed.

@ciar4n As for the color I did some investigations. It was defined as white for the cpanel cards before (using the variable `card-bg`). You expanded that to all cards within `.content` (which is the component area) in your repaint PR. Previously it used the BS5 default color (using `card-cap-bg`) for those.

**Comment by Bakual** [comment]
I'm closing this issue as I have a solution
