### ISSUE TITLE
[4][Atum] Private Message Toolbar Layout

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33591]
### Steps to reproduce the issue

Have at least one unread message

### Expected result

padding maybe?

### Actual result

<img width="771" alt="Screenshot 2021-05-06 at 19 54 03" src="https://user-images.githubusercontent.com/400092/117350813-e7b1f080-aea4-11eb-9bde-51275b63036d.png">

### System information (as much as possible)

safari on mac

**Comment by PhilETaylor** [comment]
hmm when compared with the number of Post Installation Messages - maybe this is an optical illusion due to the square edges of the envelope? 

<img width="562" alt="Screenshot 2021-05-06 at 19 56 32" src="https://user-images.githubusercontent.com/400092/117351102-3bbcd500-aea5-11eb-830a-e75d4a035dc6.png">

**Comment by brianteeman** [comment]
the bell is 14px wide
the envelope is 16px wide

So it is partially an optical illusion but it can also be resolved by using the fixed width version of the icons

**Comment by brianteeman** [comment]
Please test #33622

**Comment by alikon** [comment]
it took me sometime to get this "_optical illusion_"  :smile:
