### ISSUE TITLE
[4] Left Menu collapsing when it should stay open

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33590]
### Steps to reproduce the issue

Despite @brianteeman being convinced this was fixed "over a year ago" this remains a problem. 

I'll use this issue to document them as I come across them. 

### Expected result

When using a component, for which there is a sensible left menu, the left menu should stay highlighted in the left menu when using that component and sub screens of that component, and filters within that component. 

### Actual result

Menu collapses completely - top level menu items still visible, nothing selected.

**Comment by PhilETaylor** [comment]
First example is 

Joomla Admin -> Content -> Media = expect the media manager to open and the left menu to still be on Content -> Media highlighted. 

<img width="960" alt="Screenshot 2021-05-06 at 19 46 35" src="https://user-images.githubusercontent.com/400092/117349842-c7cdfd00-aea3-11eb-9ad0-4c874a256d7e.png">

**Comment by PhilETaylor** [comment]
Content -> Fields -> Select category in the drop down -> Select articles in the dropdown = menu collapses

<img width="834" alt="Screenshot 2021-05-06 at 19 48 01" src="https://user-images.githubusercontent.com/400092/117350029-fcda4f80-aea3-11eb-89a2-6cc9dbbd75f7.png">

**Comment by PhilETaylor** [comment]
Home Dashboard -> Click Remove or Export in Privacy Dashboard

<img width="635" alt="Screenshot 2021-05-06 at 19 49 42" src="https://user-images.githubusercontent.com/400092/117350219-38751980-aea4-11eb-923e-de21b21348bd.png">

Expect menu to be like this 

<img width="822" alt="Screenshot 2021-05-06 at 19 50 04" src="https://user-images.githubusercontent.com/400092/117350277-49be2600-aea4-11eb-8bb1-3cc0a1e715bb.png">


But its still collapsed like this:

<img width="780" alt="Screenshot 2021-05-06 at 19 50 34" src="https://user-images.githubusercontent.com/400092/117350317-56db1500-aea4-11eb-9b35-0f8b28bc4056.png">

**Comment by PhilETaylor** [comment]
Home Dashboard -> "No urgent privacy requests" green square 

<img width="695" alt="Screenshot 2021-05-06 at 19 51 54" src="https://user-images.githubusercontent.com/400092/117350480-8558f000-aea4-11eb-8aec-d98723fe33f7.png">

**Comment by PhilETaylor** [comment]
Basically anything under System menu item, that doesn't have a corresponding left menu item component, should also keep the System menu highlighted... maybe.

**Comment by PhilETaylor** [comment]
Any page where you click Options... So Content -> >Articles -> Options... the left menu collapses, instead of staying lets say on Articles.. 
<img width="1117" alt="Screenshot 2021-05-06 at 20 01 33" src="https://user-images.githubusercontent.com/400092/117351656-dddcbd00-aea5-11eb-8279-c6843091cdce.png">

**Comment by PhilETaylor** [comment]
basically any URL that uses a filter as a url param

http://127.0.0.1:4444/administrator/index.php?option=com_newsfeeds&filter[category_id]=5&filter[published]=1&filter[level]=1

This link is found by clicking the number under the tick on the News feeds categories page

<img width="1598" alt="Screenshot 2021-05-06 at 20 03 24" src="https://user-images.githubusercontent.com/400092/117351858-21372b80-aea6-11eb-9e98-dbbab02aa4da.png">

Leads correctly the newsfeeds component, but the menu collapses and doesn't stay open at Newsfeeds

<img width="920" alt="Screenshot 2021-05-06 at 20 03 34" src="https://user-images.githubusercontent.com/400092/117351912-3318ce80-aea6-11eb-83bb-4b366cacf9ff.png">

**Comment by PhilETaylor** [comment]
When you get a Private Message (from Mr User Action Logs) 

<img width="871" alt="Screenshot 2021-05-06 at 20 06 51" src="https://user-images.githubusercontent.com/400092/117352198-9c98dd00-aea6-11eb-9965-f432fcbdb9b8.png">


then you click to read it:

<img width="898" alt="Screenshot 2021-05-06 at 20 07 08" src="https://user-images.githubusercontent.com/400092/117352215-a589ae80-aea6-11eb-81ab-21c8d78f5b85.png">

**Comment by PhilETaylor** [comment]
Components -> Smart Search -> Content Maps -> Click the number of published indexed content (green box here) 

Sorry about the colour scheme... 

<img width="1571" alt="Screenshot 2021-05-06 at 22 43 41" src="https://user-images.githubusercontent.com/400092/117369226-8a299e00-aebc-11eb-816f-8c3ce59d2ffc.png">

Then you see left menu collapses 

<img width="1600" alt="Screenshot 2021-05-06 at 22 44 08" src="https://user-images.githubusercontent.com/400092/117369252-94e43300-aebc-11eb-9c56-82574b1d814c.png">

**Comment by brianteeman** [comment]
I've found the root problem - hopefully during my sleep I will dream up the solution

**Comment by brianteeman** [comment]
@PhilETaylor please test #34465 it addresses everything apart from categories which is a different root cause

**Comment by PhilETaylor** [comment]
Thanks.

Ive tested this today, its not perfect (as you clearly state) but is a million times better. I'll close the #33590 and document any left over issues overtime
