### ISSUE TITLE
[4.0] [B7] RSS Feed module

### ISSUE THREAD

**Issue by klucon** [joomla/joomla-cms#33594]
### Steps to reproduce the issue
Add Feed Display to site module. Enter your RSS feed address ( I was tested: http://www.mkrumlov.cz/rss/ ), set Word Count e.g. to 5, set position e.g. bottom-a and save.

### Expected result

Limit max words count 5

### Actual result

No limit, show all words  from RSS feed
![admin](https://user-images.githubusercontent.com/52053019/117357671-85152080-aeb5-11eb-939d-36561526b837.png)
![site_rss_feed](https://user-images.githubusercontent.com/52053019/117357674-86464d80-aeb5-11eb-8043-d1beebe0aca9.png)

### System information (as much as possible)

Joomla 4 beta 7, xampp on linux v 8.0.0

**Comment by brianteeman** [comment]
The word count refers to the number of words in the description. In your feed there are no descriptions just very long titles

**Comment by klucon** [comment]
I am sorry, i thought it also covered the title link.
