### ISSUE TITLE
[4.0] Link icon and link must be together

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33595]
### Steps to reproduce the issue
In my case, an example of a page in Russian, in yours, as an option, you can resize the browser window so that the link icon "separated" from the link.

Considering that the icon is generated by the system (we do not add it manually), the link should be wrapped to a new line only with its icon.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/117358190-872fad00-aebe-11eb-98ad-2ae2218fd09f.png)

**Comment by brianteeman** [comment]
please test #33621

**Comment by alikon** [comment]
closing as we have a pr

**Comment by ghost** [comment]
@Kostelano can you please share screenshots showing english backend? So i can find easier where to test the pr, thanks.

**Comment by Kostelano** [comment]
Now I'm not at home at the PC. You can check the PR by selecting any page that has a link. Then just play with the size of the browser window and see the behavior of the icon link.

Brian demonstrated this perfectly in PR.

**Comment by ghost** [comment]
> by selecting any page that has a link

Thats was i have asked: Which page so i don't have to search. 

> Brian demonstrated this perfectly in PR.

Right, but on a dummy text so i'm lost :-)

**Comment by sandewt** [comment]
@sandramay0905 

>Thats was i have asked: Which page so i don't have to search.
>Right, but on a dummy text so i'm lost :-)

Go to Languages: Edit Override
 
Language Constant: `COM_CONTENT_SAVE_SUCCESS`
Text: `This is a dummy text that the icon stays with the link <a href="http://issues.joomla.org" target="_blank" rel="noopener">when it</a> wraps on the line ending.`

Edit and save an article.

**Comment by ghost** [comment]
@sandewt Thanks for your comment, it helped me.
