### ISSUE TITLE
[4] Drop zone of media manager is small on a large screen by default

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33604]
### Steps to reproduce the issue

Media Manager -> attempt to drag and drop upload an image

### Expected result

Whole white area to be the drop zone

### Actual result

Only the rows where there are already files/folders is the drop zone, dropping outside this zone will open the image in the browser full screen like the browser has navigated to it.

https://user-images.githubusercontent.com/400092/117366227-577da680-aeb8-11eb-8f34-d2ef4382a1c4.mp4

**Comment by brianteeman** [comment]
Thought I had fixed it but it didnt change the height of the dropzone just the outline

![image](https://user-images.githubusercontent.com/1296369/117375286-9581c700-aec6-11eb-9057-8148f0e69ac9.png)

**Comment by PhilETaylor** [comment]
in fact this gets worse.

Create a new folder and try to drop an image in it... 

Watch


https://user-images.githubusercontent.com/400092/117466178-539a6480-af4a-11eb-8927-ea6188dcd8e1.mp4

**Comment by brianteeman** [comment]
Please test #33688

**Comment by alikon** [comment]
closing as we have a pr #33688
