### ISSUE TITLE
[4] Site dashboard + signs not reflecting colour scheme changes. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33605]
### Steps to reproduce the issue

System -> Administrator TEmplate Styles -> atum - Default -> Choose your hue value for the dark template colour - choose something else for all values.

### Expected result

"most things" would reflect the new scheme, for example when clicking "Add module to dashboard" you see my purple scheme has purple + signs.. 

<img width="611" alt="Screenshot 2021-05-06 at 22 19 32" src="https://user-images.githubusercontent.com/400092/117366758-2651a600-aeb9-11eb-8249-31cec023f182.png">

### Actual result

However on the Home Dashboard they are hard coded to blue.

<img width="637" alt="Screenshot 2021-05-06 at 22 19 52" src="https://user-images.githubusercontent.com/400092/117366793-31a4d180-aeb9-11eb-88cd-1a69a2d61eb6.png">

### System information (as much as possible)

safari on mac but unrelated

**Comment by brianteeman** [comment]
I think this is fixed with #33607 by using the variable and not a hard coded colour

**Comment by alikon** [comment]
see #33607
