### ISSUE TITLE
Data export email subject line/content switch

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33600]
### Steps to reproduce the issue

When you email a data subject their data export they get an email with a very long subject line and three words + the site name in the mail body. 

### Expected result

Consider swapping the body and subject line? 

### Actual result

<img width="1444" alt="Screenshot 2021-05-06 at 21 54 51" src="https://user-images.githubusercontent.com/400092/117364457-d32a2400-aeb5-11eb-9684-b8daafd389b3.png">

### System information (as much as possible)

tested on Joomla 4 but probably a Joomla 3 issue too.

**Comment by brianteeman** [comment]
Please test #33613

**Comment by alikon** [comment]
closing as we have a pr
