### ISSUE TITLE
[4] Set Colour to monochrome doesn't reset background colour to mono

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33602]
### Steps to reproduce the issue

System -> Administrator TEmplate Styles -> atum - Default -> select different colours and also set colour to monochrome like mine:

<img width="1567" alt="Screenshot 2021-05-06 at 22 08 33" src="https://user-images.githubusercontent.com/400092/117365716-9eb76780-aeb7-11eb-894f-759dae3fe87d.png">

Click Save & close

### Expected result

monochrome background - white? grey? but not pink... 

### Actual result

Pink....

<img width="1601" alt="Screenshot 2021-05-06 at 22 09 20" src="https://user-images.githubusercontent.com/400092/117365786-b858af00-aeb7-11eb-98da-40ada88b3afc.png">

### System information (as much as possible)

safari on mac but probably unrelated

**Comment by brianteeman** [comment]
It looks like the problem is that the svg background pattern isnt being used anymore. @ciar4n is that intentional?

**Comment by PhilETaylor** [comment]
lol **my fault again it seems** as I said I disliked the pattern (as I have said for years), and the pattern was showing through Empty State Icons and Learn Mode buttons which apparently are transparent - so I guess he removed the pattern without thinking others might like it - I don't have time to go through Githubs pagination of comments to find the links.

**Comment by brianteeman** [comment]
Please test  #33636

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33636 . Thanks in advance.
