### ISSUE TITLE
[4.0] Redirect: Show success message after enabling

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#33609]
### Steps to reproduce the issue
Go to System > Redirects
Click Redirect System Plugin link.
In modal, change Status to Enabled.
Click Save & Close button.

### Expected result
![redirect-plugin-success](https://user-images.githubusercontent.com/368084/117370108-c50ae200-ae7a-11eb-89c1-4b24bd74fc46.jpg)

### Actual result
![redirect-plugin](https://user-images.githubusercontent.com/368084/117370112-c76d3c00-ae7a-11eb-94ab-53f138cdc675.jpg)

**Comment by PhilETaylor** [comment]
Isn't this because you are doing all the work in the model but the parent page doesn't reload after you save and close the modal?

**Comment by PhilETaylor** [comment]
@Bakual @dgrammatiko ;-) ?

**Comment by Quy** [comment]
Duplicate #34333
