### ISSUE TITLE
[4] One more color chooser needed for template styles.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33606]
### Steps to reproduce the issue

System -> Administrator TEmplate Styles -> atum - Default ->  choose something else for every value.
<img width="464" alt="Screenshot 2021-05-06 at 22 46 43" src="https://user-images.githubusercontent.com/400092/117369541-f4dad980-aebc-11eb-883a-8cd748a3803a.png">

### Expected result

The ability to change the WHITE TEXT for the left menu and the Top title/modules bar.

### Actual result

Cant change the WHITE TEXT for the left menu and the Top title/modules bar.

Everything white in this screenshot cannot be controlled - everything else can be.

If I wanted RED instead of white text I cannot do that. Seems a shame as everything else is configurable. 

<img width="1602" alt="Screenshot 2021-05-06 at 22 45 57" src="https://user-images.githubusercontent.com/400092/117369449-d674de00-aebc-11eb-8be7-9131e64221ce.png">

### System information (as much as possible)

safari on mac

**Comment by brianteeman** [comment]
You will need to swap the use of the variable $white with the existing variable --atum-text-light and then also check the hover state as sometimes that is also using $white (as seen on the filter button)
