### ISSUE TITLE
[4][Atum] Toggle Menu sticks out like a blue bandaid when style color changed

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33601]
### Steps to reproduce the issue

System -> Administrator TEmplate Styles -> atum - Default -> Choose your hue value for the dark template colour - choose something else

### Expected result

"Everything" looks kinda like that "something else colour" (my screenshot is 328 color) 

### Actual result

Toggle Menu stays Blue. 

<img width="1598" alt="Screenshot 2021-05-06 at 22 02 57" src="https://user-images.githubusercontent.com/400092/117365349-13d66d00-aeb7-11eb-9e8c-d1ed72421c67.png">

NOTE that the Toggle Menu color is controlled by the LINK COLOUR on the edit page... I guess this issue depends whether you think "Toggle Menu" is a Link, or something that should reflect the template colour like the rest of the left menu does. 

### System information (as much as possible)

safari on mac but not related

**Comment by brianteeman** [comment]
Please test #33713
