### ISSUE TITLE
[4.0] Cassiopeia: Dropdown don't work

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33617]
### Steps to reproduce the issue
1. Install a nightly build,
2. Install blog sample data,
3. Open frontend,
4.  Try to open sub-menus of "Help" and "Sample Layouts".

### Expected result
Open sub-menus.

### Actual result
Don't open sub-menus.

### System information (as much as possible)
![image](https://user-images.githubusercontent.com/78906980/117411116-86753600-af13-11eb-9b34-346dda5d7d94.png)

**Comment by Shubham-com** [comment]
@sandramay0905 Could you please share your screenshot of this issue,so that it is better to understand. I think everything is fine at my end.
![Screenshot (49)](https://user-images.githubusercontent.com/66332826/117418266-d74b5580-af38-11eb-9669-53f01628d801.png)

**Comment by ghost** [comment]
There is not so may to show. Its like your screenshot but without the submenu:

![image](https://user-images.githubusercontent.com/78906980/117418988-5d0cd800-af1c-11eb-9afc-9847e781be71.png)

**Comment by richard67** [comment]
Confirmed. Browser inspector shows the submenu items (li, ul) are there and visible, you just can't see them => must be a CSS thing.

No js errors in console, no 404 in network, so assets are all found and js seems to be working.

**Comment by chmst** [comment]
@Shubham-com when did you build your application? I have the latest 4.0 dev, fresh installed with composer and npm.

**Comment by richard67** [comment]
Same for me, current 4.0-dev from right now, new installation.

**Comment by richard67** [comment]
We found the culprit: It is PR #33560 . @YatharthVyas it needs some more precise CSS selector in order not to hit ALL ul elements, also those from menus and sub-menus.

**Comment by Shubham-com** [comment]
> @Shubham-com when did you build your application? I have the latest 4.0 dev, fresh installed with composer and npm. 

@chmst Could you please share the latest 4.0 Dev application.I have build it around 3 weeks before.

**Comment by richard67** [comment]
@Shubham-com https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment .. use a git client, pull the latest 4.0-dev from the cms repository, use composer and npm.

**Comment by Shubham-com** [comment]
@richard67 thanks.

**Comment by richard67** [comment]
The problem and its cause already have been identified, and as far as I know someone is already working on a solution.

**Comment by richard67** [comment]
We cannot ship J4 with broken pull-down in frontend => Release Blocker for me.

**Comment by chmst** [comment]
Closing as there is a PR. Please test #33624
