### ISSUE TITLE
[4.0] [Atum] In 403 page template there is wrong displaying site name when it is long than 9-10 characters

### ISSUE THREAD

**Issue by Bond97** [joomla/joomla-cms#33612]
According to check issue #33599 I found new issue, that describes in title.
### Steps to reproduce the issue
Rename your testing site to my example;
For additional information check #33599 in following section

### Expected result

Sitename does not go beyond the block

Or it will be better, I think, make another PR to move sitename in 403 error template to right corner (highlighted red colour).
![изображение](https://user-images.githubusercontent.com/78050514/117377020-fd420d00-aeda-11eb-8135-337ded8cd8d7.png)

### Actual result
![изображение](https://user-images.githubusercontent.com/78050514/117376697-5f4e4280-aeda-11eb-96b6-3551d820d098.png)

### System information (as much as possible)

Latest nightly Joomla 4.0.0-beta8-dev, Firefox 89.0b8.

**Comment by brianteeman** [comment]
Probably the same cause as #33599

**Comment by ciar4n** [comment]
PR created.. #33654
