### ISSUE TITLE
[4.0] Sidebar "sub items" overflow when expanding/toggle menu

### ISSUE THREAD

**Issue by simbus82** [joomla/joomla-cms#33627]
### Steps to reproduce the issue
Try to Toggle sidebar menu in Joomla 4 backend.
You see the "submenu" rendered before the full sidebar.

Can be solved with an "overflow: hidden" to the sidebar wrapper _.sidebar-wrapper_.

### Expected result
![issue-solved-joomla](https://user-images.githubusercontent.com/1375730/117433543-de1f9b80-af2b-11eb-9256-278e22196b5e.gif)

### Actual result
![issue-joomla](https://user-images.githubusercontent.com/1375730/117433556-e37ce600-af2b-11eb-8e7f-bac5f101b156.gif)

### System information (as much as possible)
Nightly Joomla 4.0 2021-05-07 - Chrome 90

### Additional comments
PR for this issue #33628

**Comment by ghost** [comment]
Can you please look if #28260 is the same issue?

**Comment by simbus82** [comment]
> Can you please look if #28260 is the same issue?

I think the code is changend a lot since that issue. But now with yesterday "restyle" and with this little patch, the expand/collapse is working very well.

**Comment by brianteeman** [comment]
unfortunately not. You have also hidden the flyout menu items when the sidebar is collapsed

Without this PR
![image](https://user-images.githubusercontent.com/1296369/117436935-723b3400-af27-11eb-80d0-0123f6e14c8c.png)

With this PR
![image](https://user-images.githubusercontent.com/1296369/117436975-7ff0b980-af27-11eb-8ddb-cb50305ce331.png)

**Comment by simbus82** [comment]
You are right!
I try to see if the patch can be done differently!

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33628 as soon as it has been fixed (see discussion there). Thanks in advance.
