### ISSUE TITLE
[4.0] [a11y] atum - links in lists have no underline 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#33629]
### Steps to reproduce the issue
Have a look on the system view or on other dashboards where lists and tables are mixed.

### Expected result
All links are underlined.

### Actual result
![grafik](https://user-images.githubusercontent.com/1035262/117438227-900d9680-af31-11eb-9823-9c01a9160985.png)

**Comment by ciar4n** [comment]
Thank you @chmst. PR created.. #33808
