### ISSUE TITLE
[4.0] Add module to dashboard - save and close button is missing

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#33630]
### Steps to reproduce the issue
Go to a dashboard, Click "add a module".
Select a module, for example logged-users
A Modal opens for mdoule settings

### Expected result
There is a save button like in former version: 
![grafik](https://user-images.githubusercontent.com/1035262/117439215-de6f6500-af32-11eb-87d7-5817fd23af06.png)

### Actual result
Save and Close button missing

![grafik](https://user-images.githubusercontent.com/1035262/117439381-0f4f9a00-af33-11eb-800d-459f890908db.png)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33631 . Thanks in advance.

**Comment by rjharishabh** [comment]
Please reopen this issue as it's an important issue to be resolved as quickly as possible.
Thanks

**Comment by PhilETaylor** [comment]
If anything should be a release blocker, this should.

**Comment by joomdonation** [comment]
Could we solve it by:

1. Give the Save & Close button an ID like `btnModalSaveAndClose` 
2. Then add some inline javascript to https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_modules/tmpl/module/modal.php to remove `hidden` class from that button to make it shows. Something like:

```php
use Joomla\CMS\Factory;

/** @var \Joomla\CMS\WebAsset\WebAssetManager $wa */
$wa = Factory::getApplication()->getDocument()->getWebAssetManager();
$wa->addInlineScript('
    document.addEventListener("DOMContentLoaded", function() {
        saveCloseButton = window.parent.document.getElementById("btnModalSaveAndClose");
        saveCloseButton.classList.remove("hidden");        
    });
');
```

@Fedik @dgrammatiko Could that be solution?

**Comment by Fedik** [comment]
@joomdonation a bit hacky but yes that should work

for note: 
The root of the issue that the buttons should be within the frame, not parent.
I will add this to collection #32473 :smile:

**Comment by joomdonation** [comment]
@Fedik We have the buttons there https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_modules/tmpl/module/modal.php#L13-L15 , but they are hidden for some reasons.

**Comment by Fedik** [comment]
> but they are hidden for some reasons.

Yeap, they hidden because they does not need on "first step" where User should select the module, 
and after User made a choose the frame reloads and  the parent does not know it. That why I wrote in #32473 that all buttons should be rendered within the frame instead of parent, but it is for future improvement.

For now your suggestion should work.

**Comment by joomdonation** [comment]
OK. Thanks. @rjharishabh As you tried to work on this issue before, do you want to give it a try base on suggestion at https://github.com/joomla/joomla-cms/issues/33630#issuecomment-835691242 ?

**Comment by rjharishabh** [comment]
Thanks @joomdonation please test PR #33631

**Comment by alikon** [comment]
closing as we a have a pr #33631
