### ISSUE TITLE
[4.0] Tag field exceed boundary of page

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#33639]
### Steps to reproduce the issue
Try to add or edit an article. See this attached screenshot
![tag_field_issue](https://user-images.githubusercontent.com/977664/117530778-37a9c800-b009-11eb-8f49-d4d695fe4529.png)

### Expected result
Tag field is rendered within the page.

### Actual result
Tag field exceed boundary of the page

### System information (as much as possible)
Joomla 4 nightly build

### Additional comments
Maybe it happens on small screen? My laptop is 14 inch, with screen screen resolution 1920x1080.

**Comment by adj9** [comment]
Confirmed!!! Even with new template<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33639">issues.joomla.org/tracker/joomla-cms/33639</a>.</sub>

**Comment by srishty-07** [comment]
![image](https://user-images.githubusercontent.com/70388131/117538308-3daca280-b023-11eb-9962-96d695238e38.png)

default: 25ch
should change to : 15ch

**Comment by Quy** [comment]
Duplicate #27907

**Comment by brianteeman** [comment]
This should be closed as a duplicate

**Comment by joomdonation** [comment]
OK. Closing. But hope we could get it fixed soon.
