### ISSUE TITLE
[4.0] Add module javascript error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33634]
### Steps to reproduce the issue
Click on the add module to dashboard
OR Click on add module from the menu

### Expected result
no javascript errors

### Actual result
```
admin-module-search.min.js?3155e5428bfda4df9c5208e09a8c624b:1 Uncaught TypeError: Cannot read property 'classList' of null
    at HTMLInputElement.<anonymous> (VM5941 admin-module-search.min.js:1)
    at VM5941 admin-module-search.min.js:1
    at VM5941 admin-module-search.min.js:1

```

**Comment by joomdonation** [comment]
I think it causes by repaint PR. The message added on this PR https://github.com/joomla/joomla-cms/commit/858ff264237b1286b70ba9f026a730442550ef90#diff-3579939374cbf445c74b89952a2315ec62eede0cc2bc9f572869bf782c4929eeR53-R56 was removed

Could you please help checking to see if it is valid and add it back? Thanks.

**Comment by joomdonation** [comment]
@sksuryan Can you look at it and re-add the missing HTML code from your original PR back?

**Comment by joomdonation** [comment]
Closing because PR https://github.com/joomla/joomla-cms/pull/33679 solves this issue.
