### ISSUE TITLE
[4.0] Different multi-select behavior in media manager

### ISSUE THREAD

**Issue by rjharishabh** [joomla/joomla-cms#33637]
### Steps to reproduce the issue
Try to do multi-select in media-manager and articles
There is a difference.

**In media manager**
Clicking on a selected item, selects that items, and deselect all others

https://user-images.githubusercontent.com/61203226/117526325-14b7ed80-afe2-11eb-88fa-d0fdd413d1fc.mp4

**In articles**
Clicking on a selected item, deselects that items without change in selected items

https://user-images.githubusercontent.com/61203226/117526314-fb16a600-afe1-11eb-8537-9e66296797a6.mp4

### Expected result
There should not be a difference, IMO behavior in media manager should be the same as articles.

### Actual result
There is a difference in the behavior.

### System information (as much as possible)
PHP 8.0.3
MySQLi 10.4.18-MariaDB
Windows 10

### Additional comments
I don't know, whether it's intentional behavior of media manager or not.

And it's opposite to we have in Joomla 3

**Comment by eopws** [comment]
> **In media manager**
> Clicking on a selected item, selects that items, and deselect all others

It also creates impossibility of choosing two items. Only one or all of them

**Comment by rjharishabh** [comment]
> It also creates impossibility of choosing two items. Only one or all of them

you can choose two items using Shift key

**Comment by eopws** [comment]
> > It also creates impossibility of choosing two items. Only one or all of them
> 
> you can choose two items using Shift key

Another difference in behavior

**Comment by eopws** [comment]
> I don't know, whether it's intentional behavior of media manager or not.

According to the code in %Joomla 4 root%\media\com_media\js\media-manager.js line 9939 it is intentional behavior.

**Comment by rjharishabh** [comment]
> > > It also creates impossibility of choosing two items. Only one or all of them
> > 
> > 
> > you can choose two items using Shift key
> 
> Another difference in behavior

Yes

**Comment by sluc69** [comment]
V.4 beta 7

1. Cannot delete images.
2. scrolling creates a vibrating stationary images
3. only one selected image of multiple selected images imported in the editing document.
4. cannot upload docs 
5. The left side property popup when selecting an image is obscuring the top left image.
6. etc...

Have you ever used Quantum Manager extension in 3.x? That is what I call a MEDIA MANAGER
In the meantime I'm using FF explorer extension as fallback

**Comment by brianteeman** [comment]
https://github.com/joomla-projects/media-manager-improvement/issues/459

**Comment by rajputanuj31** [comment]
Hello
 @brianteeman @Quy @rjharishabh I made few changes please have a look. For these changes I modified two files

`administrator\components\com_media\resources\scripts\components\browser\items\item.es6.js`
`administrator\components\com_media\resources\scripts\components\browser\items\row.vue`

I just want to know is I am working in right direction??

https://user-images.githubusercontent.com/115709571/216137597-66fd6408-5af1-43b7-bf5c-92901d402391.mp4

**Comment by richard67** [comment]
Closing as having a pull request. See #39785 .

**Comment by richard67** [comment]
Re-opening because the pull request has been closed.

**Comment by richard67** [comment]
Closing again as there is a new pull request. Please test #39824 . Thanks in advance.
