### ISSUE TITLE
strange path

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#33642]
### Steps to reproduce the issue
Create category as a child of Uncategorised called cat2
Create a test article set to the new category
Create a test article 2 Category-uncategorised/page

Create a Category list Article menu item for the new category
create a single article menu item for the first test article not the second.

from front end click the category list menu item and then the pages listed

### Expected result
The url for both should be cat2/_page_

### Actual result
The url for the article with no menu item shows category-uncategorised/_page_

### System information (as much as possible)

Joomla 3.9.26
Article >>> options >>> integration ... Routing Modern, Remove ID's from URLs YES

### Additional comments

Interestingly if you set the menu item category blog not list and link from there then both article urls are cat2/_page_

**Comment by richard67** [comment]
Which Joomla version? I see nowhere any hint if J3 or J4.

**Comment by Webdongle** [comment]
Sorry added it via issues.joomla.org and put 3.9.26 in the 'build' field.  Perhaps someone can edit the title

**Comment by richard67** [comment]
@Webdongle I've added it to the description. You've done it right with the build field in the tracker, I should have checked that. But it's better to tell it also in the description so we can better see it on GitHub. The "[4.0]" or "[3.10]" in the title we normally use only for those future versions, or sometimes "[3.x]" if it is clear that an issue is only for 3 but not for 4.

**Comment by ghost** [comment]
@Webdongle It don't have to be in the title, system information is in the comment please. The title should be meaningful so people can easy understand what's the topic.

**Comment by Webdongle** [comment]
Ah yes thanks.  Added more info to OP.
As for J4 not tried it on that

**Comment by brianteeman** [comment]
Why would you expect Joomlaa to be creating the same url for two different pieces of content

**Comment by Webdongle** [comment]
> 
> 
> Why would you expect Joomlaa to be creating the same url for two different pieces of content

Because they are both in the same category and linked to from the same list.  Having one url with the category name and the other with the parent category in the url is inconsistent.

**Comment by Hackwar** [comment]
I'm sorry, but this seems more like a misconfiguration and at the same time we have changed the routing so much, that this is not reproducible. I'm closing this for now. If you still have this issue, please open a new ticket.
