### ISSUE TITLE
[4] Mail Templates have whitespace inconsistencies

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33658]
### Steps to reproduce the issue

Just some examples:

1) Edit Actionlogs: Notification Mail - en-GB - see space before 

```
 Action | Date | Extension | Name
```

2) Messages: New message - en-GB

https://user-images.githubusercontent.com/400092/117550079-1ca17d00-b036-11eb-8887-e504533b6a35.mp4

3) Users: Password Reset - en-GB - space before 

```
 {LINK_TEXT} 
```

4) inconsistent paragraph breaking, intended link again (link not indented on "Users: New account with self-activation - en-GB" so choose one way or the other!)

<img width="1108" alt="Screenshot 2021-05-08 at 19 48 08" src="https://user-images.githubusercontent.com/400092/117550118-5bcfce00-b036-11eb-80a5-35ae7578d64e.png">

5) Users: New account with self-activation - en-GB - inconsistent paragraph breaking

```
Hello {NAME},

Thank you for registering at {SITENAME}. Your account is created and must be activated before you can use it.
To activate the account select the following link or copy-paste it in your browser:
{ACTIVATE} 

After activation you may login to {SITEURL} using the following username and the password you entered during registration:

Username: {USERNAME}
```

### Expected result

No whitespace to the left of items

### Maybe

Just go through all the texts once again and make them as beautiful as a freshly brewed pot of coffee.

**Comment by richard67** [comment]
Closing as having a pull request which is already RTC, see #33686 . Feel free to re-open this issue if the PR doesn't solve it completely.

**Comment by PhilETaylor** [comment]
wow, I go to bed, and everything is fixed by the time I wake up - love it.

**Comment by richard67** [comment]
> wow, I go to bed, and everything is fixed by the time I wake up - love it.

@PhilETaylor GSoC students make it possible 😉
