### ISSUE TITLE
[4] Mail Template Search only searches part of the data 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33659]
### Steps to reproduce the issue

System -> Mail Templates

Search for "Global"

or search for "Privacy: Request Removal of Data"

### Expected result

"Global Configuration: Test Mail" to show in search results

or "Privacy: Request Removal of Data" to show in the search results

### Actual result

No matching results

This is because the TITLE of the email message is NOT searched 

It seems the only column searched is the ID

Also the popover says to prefix with ID: to search the id, but if you search for "com_messages.new_message" it finds the email without searching for "ID:com_messages.new_message"

**Comment by PhilETaylor** [comment]
Actually the search will never work - because I type in my english word, and Joomla compares that with `COM_ACTIONLOGS_EMAIL_SUBJECT` which is hardcoded in the database.

You can only search for templates you already have an override for

**Comment by brianteeman** [comment]
That is why it says "Search in mails. Prefix with ID: to search for a template ID."

I agree its badly worded. It is supposed to be read as
Title = Search in mails
Instruction = Prefix with ID: to search for a template ID.

I think

**Comment by PhilETaylor** [comment]
> You can only search for templates you already have an override for

If you have an override for COM_ACTIONLOGS_EMAIL_SUBJECT with a new subject line of "askjdgas" you can then search for "askjdgas" and it will show you that override. 

but if you are searching for "Actionlogs: Notification Mail" (the title of the email) then it will not find it

**Comment by joomdonation** [comment]
As you can see, we use language key to store subject of the email, so it is just searchable. The same with user actions logs, I think.

**Comment by PhilETaylor** [comment]
> As you can see, we use language key to store subject of the email, so it is just searchable. 

The problem is that the database table is used for two things. 

1) The list of available mails that can be customised
2) The users, language specific, customised template for an email.

The 1) is using language strings like COM_ACTIONLOGS_EMAIL_SUBJECT, 
The 2) is using the English (or other lang) plain text sentence.

My work on redoing the Mail Template Overrides means that you will never see the 1) in a searchable list view any longer, they will be Add Cards only. 

<img width="1312" alt="Screenshot 2021-05-09 at 11 44 44" src="https://user-images.githubusercontent.com/400092/117569123-faead900-b0bb-11eb-88a4-7a3346cd39ea.png">


This means the "search" to find a template to override will be the place this will need fixing, 

This is important because no one is going to be searching for "com_privacy.notification.admin.export" they will be searching for a few words like "Request Export"

Also, although the current message states "Search in mails. Prefix with ID: to search for a template ID." the code is looking for lowercase "id:" so another bug there. 

Im on the case with the rewrite... so just ignore this issue for now.

**Comment by joomdonation** [comment]
@PhilETaylor I think you should ping some of of our maintainers to look at your propose solution first or just make a PR quickly to show the idea to see if it could be excepted. That could save your time in case it is not accepted.

**Comment by PhilETaylor** [comment]
see the video at https://github.com/joomla/joomla-cms/issues/33657
