### ISSUE TITLE
[4.0] [Mail Templates] Language filter, indentation and attachment logic

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33655]
I will allow to describe several points / questions in one issue, since I am not sure that some of them have problems.

### Steps to reproduce the issue
1. The logic of the language filter on the templates page is not clear. I have English (default) and Russian installed on the demo site. When I select en-GB in the filter, it does not find anything for me. It seems strange to me. When I select ru-RU, I find 1 template - the one that I edited. Maybe I don't understand something - please explain to me.

![Screenshot_4](https://user-images.githubusercontent.com/8440661/117548966-76a74000-b040-11eb-91c6-c1cb72f6289a.png)

~~2. It is necessary to add indents from the "reset" buttons. See screenshot for understanding.~~

RESOLVED https://github.com/joomla/joomla-cms/pull/34517

![Screenshot_1](https://user-images.githubusercontent.com/8440661/117548973-8030a800-b040-11eb-90b6-ea1dfe1972b6.png)

![Screenshot_2](https://user-images.githubusercontent.com/8440661/117548975-8161d500-b040-11eb-84d6-19c7ec6ee306.png)

~~3. At the bottom of the page, in the ATTACHMENTS field, there is a USE DEFAULT option. What is it for?~~

RESOLVED https://github.com/joomla/joomla-cms/pull/33682

![Screenshot_3](https://user-images.githubusercontent.com/8440661/117548980-8f175a80-b040-11eb-8e3a-ab9426209d7e.png)

**Comment by brianteeman** [comment]
> The logic of the language filter on the templates page is not clear. I have English (default) and Russian installed on the demo site. When I select en-GB in the filter, it does not find anything for me. It seems strange to me. When I select ru-RU, I find 1 template - the one that I edited. Maybe I don't understand something - please explain to me.


You are correct it doesn't work the same as anything else (it should do :( )

The logic is that there is a mail template set for ALL languages and if you want to you can create additional versions for each language.

**Comment by Kostelano** [comment]
I will leave a link where I described the problems with the search.

https://github.com/joomla/joomla-cms/issues/33657#issuecomment-835469368

**Comment by joomdonation** [comment]
#3 is addressed by this PR https://github.com/joomla/joomla-cms/pull/33682

**Comment by PhilETaylor** [comment]
1 will be fixed in my rewrite, as it will have an Empty State

Follow the progress here https://github.com/joomla/joomla-cms/issues/33657

**Comment by Quy** [comment]
Please test PR #34517 for # 2.

**Comment by Kostelano** [comment]
I'll close it, since only point 1 remained unresolved, which, apparently, is still the expected behavior. Because Being on the page of templates, in principle, we see all languages of letters at once. Another question is that most likely we do NOT need this filter.
