### ISSUE TITLE
[4] TypeError: undefined is not an object (evaluating 'l.nonCoreCriticalPlugins.length')

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33653]
### Steps to reproduce the issue

4.0-dev today

Visit administrator/index.php?option=com_joomlaupdate

### Expected result

No JS errors 

### Actual result

TypeError: undefined is not an object (evaluating 'l.nonCoreCriticalPlugins.length')

<img width="876" alt="Screenshot 2021-05-08 at 18 57 35" src="https://user-images.githubusercontent.com/400092/117548883-46a37100-b02f-11eb-935e-f2792cb73e9f.png">

### System information (as much as possible)

safari on mac

### Additional comments
@dgrammatiko sorry not sorry :) ;-)

**Comment by dgrammatiko** [comment]
Haha that's probably not me here :)

**Comment by PhilETaylor** [comment]
Im not saying its your fault - Im saying you have more of a chance of fixing it than I do haha

**Comment by dgrammatiko** [comment]
Check #33677

**Comment by joomdonation** [comment]
Closing as there is PR https://github.com/joomla/joomla-cms/pull/33677. Thanks @dgrammatiko.
