### ISSUE TITLE
[4] en-GB verses en-US?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33663]
after running the commands to build everything from git, recently Ive been getting build_incomplete.html and fatal-error.html as modified files. 

The only difference is the language 

<img width="909" alt="Screenshot 2021-05-08 at 20 30 58" src="https://user-images.githubusercontent.com/400092/117551169-4fe70a80-b03c-11eb-9fe9-8e986cb38962.png">

Im not aware of having chosen a default language yet, is this something that needs fixing?

**Comment by dgrammatiko** [comment]
This is my mistake, I forgot to order the languages when I redid the tooling. It's an easy fix
replace https://github.com/joomla/joomla-cms/blob/ddc1380b082ee24a9b1416c0685a95a2321fbf9c/build/build-modules-js/error-pages.es6.js#L115

with 
```js
const sortedJson = Object.fromEntries(Object.entries(global[`${name}Obj`]).sort());
const jsonContent = `window.errorLocale=${JSON.stringify(sortedJson)};`;
```

fwiw I've tried to change this in another PR https://github.com/joomla/joomla-cms/pull/33170/files but that one has other issues with the CI...

**Comment by PhilETaylor** [comment]
[4] en-GB verses en-US - order the languages #33674

**Comment by dgrammatiko** [comment]
BTW ordering is irrelevant on the runtime as the object is used by using the key (eg `en-GB`)
