### ISSUE TITLE
[4] Menu icons black on view/component not found error page

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33667]
http://example.com/administrator/index.php?option=com_foo where com_foo is not installed.

https://user-images.githubusercontent.com/400092/117551841-1d3f1100-b040-11eb-964e-d73d8d98b11e.mp4

**Comment by Kostelano** [comment]
I confirm. I have the same.

**Comment by ciar4n** [comment]
Possibly resolved by https://github.com/joomla/joomla-cms/pull/33654 ?

**Comment by Kostelano** [comment]
@ciar4n Yes, updating the new build fixed the issue. Thank you.

**Comment by ciar4n** [comment]
@Kostelano Great... thanks for confirming

**Comment by PhilETaylor** [comment]
well it fixes the color of the icons, but something is now messing with the top 

https://github.com/joomla/joomla-cms/issues/33687

<img width="1602" alt="Screenshot 2021-05-09 at 11 19 15" src="https://user-images.githubusercontent.com/400092/117568494-73e83180-b0b8-11eb-8c94-e9624d7a5ef8.png">
