### ISSUE TITLE
[4.0] Link to create an account: missing an icon?

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33662]
### Steps to reproduce the issue
Log in to the control panel, in the settings of the USERS component, allow registration. Also activate the site login module for the frontend.

Go to the frontend. In the authoring module, pay attention to the registration link. Missing an icon or ...? 

![Screenshot_2](https://user-images.githubusercontent.com/8440661/117550787-d60a4d80-b04a-11eb-86e1-c01a245c0167.png)

**Comment by brianteeman** [comment]
good spot. looks like there are lots of similar occurance

**Comment by brianteeman** [comment]
Please test #33676

**Comment by alikon** [comment]
closing as we have a pr #33676
