### ISSUE TITLE
[4.0] Plugin link = modal window

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33669]
### Steps to reproduce the issue
Go to PLUGINS, disable System - Redirect plugin. Go to SYSTEM - REDIRECTIONS. On the new page, you will see a notification that the System - Redirect plugin must be enabled. Click on the plugin link - a modal window will open, you can easily enable the plugin, save everything and stay on the same (NEEDED for you) page.

Off-top
By the way, the CLOSE button in the modal window does not change the background on mouse hover.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/117552914-f213ec00-b056-11eb-91de-5f21664f45a7.png)

Now disable the System - Language Filter plugin. Go to COMPONENTS (left) - ASSOCIATIONS. You will see a similar notification, but, firstly, in a different style (WARNING), and secondly, clicking on the plugin link will redirect you to a new page in the same window. There is no modal window. On the new page (plugin parameters) you can enable it, save it and find yourself in a completely different place where you would like to be.

The gist of my writing is that the logic for linking to the plugin on the multilingual associations page should be the same as in the redirects. Those. open in a modal window. It is very convenient.

**Comment by Kostelano** [comment]
I wrote and remembered that we have the same problem in the smart search component when the Content - Smart Search plugin is disabled.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/117553151-7ca91b00-b058-11eb-928a-c600841f51d4.png)

**Comment by brianteeman** [comment]
> The gist of my writing is that the logic for linking to the plugin on the multilingual associations page should be the same as in the redirects. Those. open in a modal window. It is very convenient.

Agreed. Just needs someone to write the code

**Comment by Kostelano** [comment]
For memory - in one place. Suddenly you get lucky and someone implements it :).

The same story is in Control Panel -- Privacy Dashboard. When the plugin is disabled, there is a link to it by ID. Opens in a new window, not modal, similar to the problems described above.

![Screenshot_6](https://user-images.githubusercontent.com/8440661/117883014-92fee300-b2b3-11eb-8b91-16adad57f0bf.png)

**Comment by Kostelano** [comment]
> 
> 
> I wrote and remembered that we have the same problem in the smart search component when the Content - Smart Search plugin is disabled.
> 
> ![Screenshot_2](https://user-images.githubusercontent.com/8440661/117553151-7ca91b00-b058-11eb-928a-c600841f51d4.png)

https://github.com/joomla/joomla-cms/pull/34449

Thanks @brianteeman.

Remained similar behaviors for multilingual associations and (would be ideal) the personal data panel.

**Comment by brianteeman** [comment]
can you double check its still needed for multlingual as I thought the component only worked now when the plugin is enabled

**Comment by Kostelano** [comment]
Yes you are right. I forgot there was a recent change to the display of the associations component if the plugin is NOT enabled.

Well, it turns out that the personal data panel remains. Since this is more a wish, not a mistake + the fact that several wishes are mixed in the Issue, I will close the problem.

Thank you.
