### ISSUE TITLE
[4] Template image upload not possible

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33661]
### Steps to reproduce the issue

THINK LIKE A USER NOT A DEVELOPER

System -> Site Templates -> Cassiopeia Details and Files -> New File

Select the images folder on the left.

click Choose File, choose an image from your computer, click upload. 

<img width="1294" alt="Screenshot 2021-05-08 at 20 04 16" src="https://user-images.githubusercontent.com/400092/117550484-9470a700-b038-11eb-92f4-b360a8286713.png">

### Expected result

THINK LIKE A USER NOT A DEVELOPER

Expect that the file is uploaded to the images folder with the same filename and extension as the original file. 

THINK LIKE A USER NOT A DEVELOPER

### Actual result

THINK LIKE A USER NOT A DEVELOPER

<img width="994" alt="Screenshot 2021-05-08 at 20 05 10" src="https://user-images.githubusercontent.com/400092/117550514-b538fc80-b038-11eb-9a92-043531676f9a.png">

### System information (as much as possible)

THINK LIKE A USER NOT A DEVELOPER

### Additional comments

THINK LIKE A USER NOT A DEVELOPER

**Comment by brianteeman** [comment]
not sure what you are asking for here. I'm a user not a mind reader

**Comment by PhilETaylor** [comment]
Then read what I wrote. I spelled it out. It's impossible to upload images when the expectation is that you should be able to. Nothing says that you can't.

**Comment by brianteeman** [comment]
> Nothing says that you can't.

Because you should be able. Its a bug.

**Comment by brianteeman** [comment]
The way that you wrote it suggested that you want a better error message to say that you cant upload an image.

The problem is not the error message. The problem is a bug in joomla preventing you from uploading

**Comment by brianteeman** [comment]
And its not actually a bug. 
The problem comes from when the webp support was added. This required a data change in the db. You will not get those changes applied unless you do an upgrade or clean install. The database structure fix cant change data. OR open the template options and press save. Any of those will resolve the "bug" and you can happily upload images.

**Comment by PhilETaylor** [comment]
I tested that theory - I reinstalled from scratch... and now I still cannot upload png files (screenshots) 

However, the message is complaining about "not being a valid file name", although this is a valid file name, Im guessing Joomla doesn't like the multiple periods in the file name. 

`Screenshot 2021-05-09 at 11.32.29.png`

I can upload `test.png`

**Comment by PhilETaylor** [comment]
Reopening as `Screenshot 2021-05-09 at 11.32.29.png` file can be uploaded with com_media, so it should be legal and valid to upload it using template manager too.

**Comment by brianteeman** [comment]
You're right. I forgot about the double dot. That is a restriction put in place several years ago for security

**Comment by brianteeman** [comment]
Or blocked in both if the security issue is still valid

**Comment by brianteeman** [comment]
Related issue #30908

**Comment by brianteeman** [comment]
In J3 you do get the correct error message
![image](https://user-images.githubusercontent.com/1296369/118108046-6f34bd80-b3d7-11eb-883c-4de3e1365e92.png)

**Comment by PhilETaylor** [comment]
That is the same error message as joomla 4￼
