### ISSUE TITLE
[4.0] Error while running cli commands

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33665]
### Steps to reproduce the issue

Run
`php joomla.php `
in subfolder cli

### Expected result
I see possible commands like explainded herer: https://docs.joomla.org/J4.x:CLI_Update#Using_the_CLI_Update

### Actual result

```
j4dev/cli$ php joomla.php 
Symfony\Component\ErrorHandler\Error\UndefinedFunctionError^ {#146
  #message: "Attempted to call function "simplexml_load_file" from namespace "Joomla\CMS\Language"."
  #code: 0
  #file: "/srv/www/joomla/j4dev/libraries/src/Language/LanguageHelper.php"
  #line: 680
  trace: {
    /srv/www/joomla/j4dev/libraries/src/Language/LanguageHelper.php:680 {
      Joomla\CMS\Language\LanguageHelper::parseXMLLanguageFile($path)^
      › // Try to load the file
      › $xml = simplexml_load_file($path);
      › 
    }
    /srv/www/joomla/j4dev/libraries/src/Language/LanguageHelper.php:572 { …}
    /srv/www/joomla/j4dev/libraries/src/Language/Language.php:193 { …}
    /srv/www/joomla/j4dev/libraries/src/Language/LanguageFactory.php:32 { …}
    /srv/www/joomla/j4dev/libraries/src/Language/CachingLanguageFactory.php:43 { …}
    /srv/www/joomla/j4dev/libraries/src/Service/Provider/Application.php:122 { …}
    /srv/www/joomla/j4dev/libraries/vendor/joomla/di/src/ContainerResource.php:176 { …}
    /srv/www/joomla/j4dev/libraries/vendor/joomla/di/src/Container.php:96 { …}
    /srv/www/joomla/j4dev/cli/joomla.php:74 { …}
  }
}

```

**Comment by richard67** [comment]
@agi-code Can it be that your PHP doesn't include XML support? It is listed in the technical requirements for Joomla: https://downloads.joomla.org/technical-requirements#footnote-3xPHP :

`(Zlib Compression Support, XML Support, INI Parser Support, JSON Support, MB Language = Default)`

**Comment by PhilETaylor** [comment]
Also note that you need these PHP extension enabled on your CLI version of PHP and you cannot rely on the system information displayed in Joomla as that runs a different PHP configuration than your CLI PHP

**Comment by ghost** [comment]
Thank you @PhilETaylor and @richard67
