### ISSUE TITLE
reCAPTCHA themes are not responsive

### ISSUE THREAD

**Issue by skibulk** [joomla/joomla-cms#3366]
In reference to /plugins/captcha/recaptcha/

Even in a responsive website template, when the page width is less than 300px the captcha gets cut-off, making it difficult to submit any form. For a pre-made responsive theme, see https://github.com/chrisvanpatten/responsive-recaptcha

**Comment by brianteeman** [comment]
Closing at this time as a Known Issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3366">issues.joomla.org/joomla-cms/3366</a>.</sub>
