### ISSUE TITLE
[4] click, close module, highlighted still 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33672]
### Steps to reproduce the issue

Click Add module to the dashboard 
See modal launch 
Change your mind and hit ESC or close module

### Expected result

"add module to the dashboard" is no longer highlighted with hover state colours (although I think its still like this due to being active?) 

### Actual result

https://user-images.githubusercontent.com/400092/117554062-33070300-b04d-11eb-9114-19657b343120.mp4

### System information (as much as possible)

safari on mac

**Comment by dgrammatiko** [comment]
> Change your mind and hit ESC or close module

This is expected, modals on close should handle back the focus to the element that opened them. It's according to the a11y specs

**Comment by PhilETaylor** [comment]
Excellent - thanks.
