### ISSUE TITLE
[4.0] Tabs do not work with HTML title

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#33675]
### Steps to reproduce the issue
```
<?php

$title = '<img src="...">';

echo HTMLHelper::_('uitab.startTabSet', 'myTab', ['active' => 'active-1']);
    echo HTMLHelper::_('uitab.addTab', 'myTab', 'active-1', $title);
        echo 'Test1';
    echo HTMLHelper::_('uitab.endTab');
    echo HTMLHelper::_('uitab.addTab', 'myTab', 'active-2', $title);
        echo 'Test2';
    echo HTMLHelper::_('uitab.endTab');
echo HTMLHelper::_('uitab.endTabSet');

?>
``` 
### Expected result
Clicking on the image changes the tab.

### Actual result
```Uncaught TypeError: e.target.hash is undefined (joomla-tab.js:233:32)```

### Additional comments
Solution: https://github.com/joomla-projects/custom-elements/issues/164

@dgrammatiko

**Comment by dgrammatiko** [comment]
There are way more serious problems with tabs and alerts, hopefully https://github.com/joomla/joomla-cms/pull/33234 will sort things out

FWIW the title should be expected ALWAYS to be text, not HTML. If you need to add icons, CSS is extremely viable

**Comment by bembelimen** [comment]
Hi @dgrammatiko , thanks for your answer. I needed flexible images, defined by the user in the article. So I think it's not unlikely to have sometimes HTML there.
