### ISSUE TITLE
[4.0] [Smart Search: Search Filters] No blank page

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33670]
### Steps to reproduce the issue
Go to Components - Smart Search - Search Filters, there is no blank page like other pages. Is she not needed here?

![Screenshot_1](https://user-images.githubusercontent.com/8440661/117553374-f55ca700-b059-11eb-8c1f-5601c7031430.png)

https://github.com/joomla/joomla-cms/issues/33266

**Comment by Bakual** [comment]
@PhilETaylor You want to do one here as well?

**Comment by PhilETaylor** [comment]
I think I will add one here, the text is meaningful without one, but I cannot see any reason why an Empty State should not be applied here for consistency now we have gone all in on them.

**Comment by Kostelano** [comment]
Like. This is currently the only page that does not have a blank state, but has a NEW button.

**Comment by PhilETaylor** [comment]
PR https://github.com/joomla/joomla-cms/pull/33733
