### ISSUE TITLE
[4] add module search filter is persistent 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33673]
### Steps to reproduce the issue

THINK LIKE A USER NOT A DEVELOPER

Click "add module to the dashboard"
Search for Action 
click Action Logs -Latest 
(you can't save but thats another issue being dealt with else where) https://github.com/joomla/joomla-cms/issues/33630
Close modal
hard refresh the page.
Click "add module to the dashboard"

### Expected result

THINK LIKE A USER NOT A DEVELOPER

Search is empty ready to be used again. All available module types are shown. 

### Actual result

THINK LIKE A USER NOT A DEVELOPER

"As an admin, I have just added the action logs module to the dashboard, and the reason I have clicked "add module to the dashboard" again is to add a different module to the dashboard but first I find I need to delete what I searched for before... which is a pain.. "

https://user-images.githubusercontent.com/400092/117554205-15866900-b04e-11eb-973e-dff5a01c2d9d.mp4

### Additional comments

THINK LIKE A USER NOT A DEVELOPER

**Comment by dgrammatiko** [comment]
It seems that this was intended: https://github.com/joomla/joomla-cms/blob/ddc1380b082ee24a9b1416c0685a95a2321fbf9c/build/media_source/com_modules/js/admin-module-search.es6.js#L98-L108

**Comment by brianteeman** [comment]
Depends on the scenario. If your filter had produced multiple results you would want to return to the same filtered list to try the other modules. its the same with filtering everywhere else. Just seemed particularly odd to you as you had a filter result with just one match

**Comment by brianteeman** [comment]
For me this is working as intended and desired.
