### ISSUE TITLE
[4] Refactor Installer Warnings & Post Installation messages to be System Messages.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33671]
### Steps to reproduce the issue

For Joomla 4.1 possibly?

Installer Warnings (Renamed Information -> Warnings in Joomla 4) = 10 hard coded system checks, mainly about PHP configuration and folder writable issues. Each has a check, and if the check fails, has a warning to the site admin

Out of the box Joomla has (normally) at least 1 Installer Warnings to read straight away... depending on hosting might have a second too. You dont get to see these warnings on the installer pages any more, and they are hidden. They dont have their own top tool bar warning block and although are more silly to ignore, are often ignored because the Post Installation Messages are more in-the-face of a Joomla admin. 

Post Installation messages (Also called Information -> Installation Messages, in Joomla 4) = unlimited number of messages from Joomla (and 3rd parties) that (can) have a check, and if that check fails, has a warning to the site admin with instructions on what to do next. 

Out of the box Joomla has (normally) 3 Post Installation messages to read straight away... 

---- 

Both are essentially the same thing. They are trying to get the attention of a busy site admin and slap them around the face with some information about something they should know about, and can do something about. 

I propose to refactor the installer messages to be post installation messages, and rename the feature System Messages which can then continue to function just like Post Installation messages do today. Possibly add a flag INFO/WARNING/ERROR to the messages too

Also propose to add new messages for not meeting the optional/requirements of Joomla - such as XML, zip, iconv, intl extensions etc... 

Also propose to make messages delete-able. There is no point in having a "Welcome to Joomla" and "stats collection in joomla" post installation message in the database until 2050..

**Comment by brianteeman** [comment]
4.1

**Comment by brianteeman** [comment]
Not all post-install messages have a conditional check. some are just informational text

**Comment by PhilETaylor** [comment]
> Not all post-install messages have a conditional check. some are just informational text

Correct, all the more reason they should be allowed to be deleted and not just "hidden to spend eternity in the database"...

**Comment by PhilETaylor** [comment]
Database not being up-to-date, is another example of some warning/error￼ being completely hidden and not in your face and should be added to the new system messages alerts￼
