### ISSUE TITLE
[4.0] Install from web: Style of Warning missing

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33680]
### What needs to be fixed
As title say

![image](https://user-images.githubusercontent.com/78906980/117561199-d62f3b00-b094-11eb-940c-b0a364407190.png)

Should be styled like

![image](https://user-images.githubusercontent.com/78906980/117561233-3a51ff00-b095-11eb-9e49-dc2b8345a282.png)

### Why this should be fixed
Same look of warning.

**Comment by ghost** [comment]
Closed because of pull request #33743

**Comment by rjharishabh** [comment]
Please test #33743

**Comment by ghost** [comment]
@rjharishabh i have tried but didn't get the warning anymore so i can't test.
