### ISSUE TITLE
[4] Top of error page messed up

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33687]
http://example.com/administrator/index.php?option=com_foo where com_foo is not installed.

<img width="1602" alt="Screenshot 2021-05-09 at 11 19 15" src="https://user-images.githubusercontent.com/400092/117568485-6763d900-b0b8-11eb-8a54-4e0f6ad88272.png">

**Comment by YatharthVyas** [comment]
Issue confirmed

**Comment by PhilETaylor** [comment]
@ciar4n this was caused by ddc1380b082ee24a9b1416c0685a95a2321fbf9c

**Comment by dgrammatiko** [comment]
Please test https://github.com/joomla/joomla-cms/pull/33689

**Comment by alikon** [comment]
closing as we have a pr #33689
