### ISSUE TITLE
[4] Download key quick icon colouring

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33698]
### Steps to reproduce the issue

install a Joomla 4 compatible extension that requires a download key to update. 

### Expected result

If a download key is missing, thats a warning and so should not be blue
Once all download keys are added, that should be green. 

### Actual result

<img width="626" alt="Screenshot 2021-05-09 at 14 09 33" src="https://user-images.githubusercontent.com/400092/117573532-5921b700-b0d0-11eb-8d99-9097c8af808c.png">
<img width="634" alt="Screenshot 2021-05-09 at 14 09 18" src="https://user-images.githubusercontent.com/400092/117573534-5aeb7a80-b0d0-11eb-962c-d9c6c51373c9.png">

**Comment by brianteeman** [comment]
confirmed

all the other quickicons use js to add the class

**Comment by Quy** [comment]
Please test PR #34312. Thanks.
