### ISSUE TITLE
[4] brand logo not collapsing when left sidebar collapsing. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33690]
### Steps to reproduce the issue

Easier to see than explain 

https://user-images.githubusercontent.com/400092/117569955-fc1e0500-b0bf-11eb-9a07-5c95b85540d4.mp4

**Comment by ghost** [comment]
Can you please look at #33660 cause it looks like same report.

**Comment by PhilETaylor** [comment]
duplicate https://github.com/joomla/joomla-cms/issues/33660
