### ISSUE TITLE
[4] After installing extension, feedback is lost 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33697]
### Steps to reproduce the issue

Install a Joomla 4 compatible extension

### Expected result

The name of the extension, and any feedback is clearly shown 

### Actual result

The name of the extensions is un-styled following the admin UI repaint. 

<img width="1046" alt="Screenshot 2021-05-09 at 14 02 36" src="https://user-images.githubusercontent.com/400092/117573370-5e323680-b0cf-11eb-9675-a9d032386656.png">

**Comment by eopws** [comment]
> The name of the extension, and any feedback is clearly shown

Where do you want the name to be shown?

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33781 . Thanks in advance.
