### ISSUE TITLE
[4] Joomla 5.5.5 Update Now!

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33694]
### Steps to reproduce the issue

fake everything to get a Joomla update available 

### Expected result

No idea. Is is really a red in your face error message? or should it be a yellow not-so-in your face warning?

`Joomla 5.5.5 is now available.`

`Joomla 5.5.5 is now available. Update now!`

`There is a Joomla update available, upgrade asap`

No idea. 

### Actual result

An update should not be red. Red is reserved for error states. 

<img width="633" alt="Screenshot 2021-05-09 at 13 41 22" src="https://user-images.githubusercontent.com/400092/117572774-51f8aa00-b0cc-11eb-956f-237b488704a6.png">

**Comment by dgrammatiko** [comment]
I think it's all about the available space, maybe `Update to version 5.5.5`

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33706 . Thanks in advance.

**Comment by richard67** [comment]
I just see the PR solves the text but not the colour. Re-opening.

@PhilETaylor But to be honest: For me the colour is absolutely fine. In future, when 4.0 will be productive, missing an update will mean possibly missing security fixes, that's why it is red and always was red. I hope we can convince you and you close this issue. I prefer convince to force, that's why I leave it to you.

**Comment by PhilETaylor** [comment]
I think the text was more important to resolve on the colour.

I wonder what colour an extension update available is? Can't check now as I'm in bed.￼

**Comment by richard67** [comment]
@PhilETaylor Extension update is red, too.

**Comment by ceford** [comment]
As an experiment I changed the background colour of an Updates notice to var(--info):
![image](https://user-images.githubusercontent.com/1560390/117626779-5de97800-b16f-11eb-9468-4058dd66a86b.png)
Not saying I like it - just that it is something other than red or greeen.

**Comment by brianteeman** [comment]
it should be red
