### ISSUE TITLE
[4] Download key rendering merge mistake. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33699]
### Steps to reproduce the issue

Ok this is my fault for improving Joomla 3, and then it being upmerged to Joomla 4.

Install a Joomla 4 compatible extension that requires a download key. 

Go to  System -> Update sites

### Expected result

See that `dlid=`  - thats not needed in Joomla 4, and has been merged from Joomla 3 unneededly. The padding after it too needs to go. 

### Actual result

<img width="587" alt="Screenshot 2021-05-09 at 14 15 31" src="https://user-images.githubusercontent.com/400092/117573648-0694ca80-b0d1-11eb-8f76-b4607640f051.png">
<img width="596" alt="Screenshot 2021-05-09 at 14 15 20" src="https://user-images.githubusercontent.com/400092/117573649-085e8e00-b0d1-11eb-89c8-d159a36eafed.png">

**Comment by brianteeman** [comment]
please test #33705
