### ISSUE TITLE
[4] Urgent Privacy Request Error message with undefined and broken button. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33696]
### Steps to reproduce the issue

Generate some privacy requests ... wait 30 days... 

or run this SQL to give you the same thing:

```sql
INSERT INTO `jos_privacy_requests` (`id`, `email`, `requested_at`, `status`, `request_type`, `confirm_token`, `confirm_token_created_at`)
VALUES
	(1, 'asdfasd@asdas', '2011-05-09 12:53:18', 0, 'export', '$2y$10$XfdBZSSZMDuhyvHFhJq7e.AUXMtrPOojvcNDEPVWZnOQjKBJfOkum', '2021-05-09 12:53:18'),
	(2, 'asdfasd@asdas', '2011-05-09 12:53:18', 1, 'export', '', '2021-05-09 12:53:53'),
	(3, 'asdfasd@asdas', '2011-05-09 12:53:18', 1, 'remove', '', '2021-05-09 12:53:58');
```

Visit Home Dashboard 

### Expected result

A warning that there are overdue requests

### Actual result

An error, with an undefined message and a broken button. 

<img width="1307" alt="Screenshot 2021-05-09 at 13 56 56" src="https://user-images.githubusercontent.com/400092/117573242-b3217d00-b0ce-11eb-9863-1243a3708477.png">

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33735 . Thanks in advance.
