### ISSUE TITLE
[4][Media] Uploading zip/tar.gz/svg files gives generic error message

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33702]
### Steps to reproduce the issue

Attempt to upload a small zip file by drag and drop to the media manager

### Expected result

A message that might tell me something about the reason for the "error occurring"

"I'm dreadfully sorry, we do not allow zip files to be uploaded because their extension is disallowed in the options - but you can go to options and change this"

"Oi you, dont be a fool! We are restricting uploads to only images because you dont have fileinfo/MIME magic installed. Install either, or disable Restrict Uploads in options"

"mime type failed check" 

### Actual result

Two ajax requests are fired. One is suspect and is to `blob:http://127.0.0.1:4444/fe446368-63dd-4d7e-b290-f6f55953d564` and one is a POST to `http://127.0.0.1:4444/administrator/index.php?option=com_media&format=json&task=api.files&path=local-0:/` which results in 

```json
{"success":false,"message":"","messages":null,"data":null}
```

and because it was not a success, and there was no message - Joomla gives this unhelpful generic message:

<img width="1006" alt="Screenshot 2021-05-09 at 14 47 29" src="https://user-images.githubusercontent.com/400092/117574543-815fe480-b0d5-11eb-86ff-d00e851e9321.png">

**Comment by brianteeman** [comment]
From what I can tell all the code and strings exist in libraries\src\helpers\mediahelper.php but its never getting passed across to the javascript this component uses
