### ISSUE TITLE
[4] Joomla session not working when redis db number not 0

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33704]
### Steps to reproduce the issue

Have a working Joomla installation with redis set up for session management in Joomla global config. As per

<img width="922" alt="Screenshot 2021-05-09 at 15 25 09" src="https://user-images.githubusercontent.com/400092/117575678-c63a4a00-b0da-11eb-96a3-d06545262576.png">

Enjoy Joomla nice and fast... 

Then your sysadmin comes along and asks you to use Redis database number 3

So you login and you change the Redis Database to 3 and save. Of course you get logged out, thats normal, but then you can no longer login!!! 

Joomla doesn't allow you to ever login again while the Redis Database number is not 0

### Expected result

Joomla can use any configured redis database for session management. 

### Actual result

Joomla doesn't allow you to ever login again while the Redis Database number is not 0

**Comment by alikon** [comment]
funny cache with redis is working on db <> 0

**Comment by alikon** [comment]
related to #30377

**Comment by PhilETaylor** [comment]
that guy must be good...
