### ISSUE TITLE
Responsive Issues on different screen sizes

### ISSUE THREAD

**Issue by deveshprasad** [joomla/joomla-cms#33717]
### Intro

My name is Devesh Prasad. I want to contribute to the GSOC 21 project of Joomla that is to add a frontend inline editing feature, after successful installation of code files in the localhost to get familiar with the codebase I have shortlisted some frontend responsive issue which can help me later on with the project of inline editing.
So, I would like to work on these issues.

### 1
![screen shot 2021-05-09 at 19 06 03](https://issues.joomla.org/uploads/1/17bc405527c5c2e23942b3befba68de2.png)

### 2
![screen shot 2021-05-09 at 19 06 03](https://issues.joomla.org/uploads/1/3826548fb831c33e8b6acc4db97b8d22.png)!

### 3
![screen shot 2021-05-09 at 19 06 03](https://issues.joomla.org/uploads/1/86927870f1ec43fa7ac34c3e9abe5cd4.png)!

### 4
![screen shot 2021-05-09 at 19 06 03](https://issues.joomla.org/uploads/1/781c99a3da4a11b76cdef80c2e62f18c.png)!

### 5
![screen shot 2021-05-09 at 19 06 03](https://issues.joomla.org/uploads/1/5a6fbb8c84dc45c5cfe4416f9840e9a4.png)

### Expected result

Responsive issues mentioned above to be solved with improved familiarity with the codebase.
By working on the margin and padding and other frontend issues as per the timetable I have mentioned in my GSOC proposal.

### Proposal Timeline Mentioned
Proposal link: https://docs.google.com/document/d/1a_Ix_XVIiXLxm1Teu-G5s_BU0DzWtgb5Q43F2VTkVA4/edit?usp=sharing

### Name: Devesh Prasad
Email: deveshprasad99911@gmail.com

**Comment by Bond97** [comment]
I confirmed responsive issue 2, it happens when you use mobile view of Atum template and the resolution is less than the default mobile view in Firefox or Chromium-based browser. 

@ciar4n did a great job to repaint Admin UI, but he write, that media manager needs much more work to be fully responsive in mobile view.

**Comment by deveshprasad** [comment]
### **To solve issue 1 above**
Which approach should I follow, 
1) By adding bootstrap margins to all the three buttons that is " m-1 " in all the three buttons as adding it on an individual will affect the alignment and gap ratio between all three buttons.
2) By using media queries in the SCSS  file so that when the screen size is a mobile view, the never button should have a top margin.

![1](https://user-images.githubusercontent.com/63739986/117768448-05d67280-b250-11eb-8733-6fcfde83cba6.png)

**Comment by laoneo** [comment]
I have also one:
![image](https://user-images.githubusercontent.com/251072/117772679-b7b57500-b237-11eb-9922-64a7ed0c0bce.png)

**Comment by deveshprasad** [comment]
![13 05 2021_15 45 42_REC](https://user-images.githubusercontent.com/63739986/118330296-3440a000-b525-11eb-98d9-bb90eea5cf2f.png)
![13 05 2021_20 50 17_REC](https://user-images.githubusercontent.com/63739986/118330304-373b9080-b525-11eb-915d-b45e3b4813f2.png)

One more button margin issue

**Comment by richard67** [comment]
Closing as having a pull request. See #33895 .

**Comment by richard67** [comment]
See also #33899 .

**Comment by laoneo** [comment]
Does #33899 solve all issues mentioned here? If not, then I would leave this issue open till everything is resolved.

**Comment by deveshprasad** [comment]
### **To solve this issue:**

![2](https://user-images.githubusercontent.com/63739986/118445717-6fe98e80-b70c-11eb-9b4f-8dfe892123e2.png)
![17 05 2021_02 10 20_REC](https://user-images.githubusercontent.com/63739986/118445725-711abb80-b70c-11eb-8c3a-4f2bf34daf41.png)

### **To solve this  issue** 
**We need to go to the:**

**media->com_media->css->media-manager.css and media-manager.min.css
media->com_media->scss->components->_media-browser.scss**

**The folder media is mentioned in the gitignore file.**

**Can someone guide me with the git command lines I should follow to update these files and pushing them ?**

**Comment by YatharthVyas** [comment]
@deveshprasad 
Maybe this is what you are looking for:
https://github.com/joomla/joomla-cms/tree/4.0-dev/build/media_source/com_media/scss

Any changes you make here will have to be compiled for them to reflect in your local website. For that, you can use `npm run build:css` command in the root folder

**Comment by richard67** [comment]
@deveshprasad The media folder is filled by the build script (some of the js files in the "Build" folder) with what is in the `build/media_source` folder. The path below that folder stays the same, i.e. `build/media_source/com_media` belongs to `media/com_media`. The necessary command to compile the scss or js (the latter is not really compiled but linted and transscripted) you can find here: https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment .
