### ISSUE TITLE
[4] Cache handler options not hidden when caching disabled.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33716]
### Steps to reproduce the issue

System -> Global Config => system

Turn System cache = On (Conservative), Select Redis as a cache handler. -> select System Cache = off. 

Note Redis options still visible

Save 

Note Redis options still visible

Save and close -> reopen global config 

Note Redis options still visible

### Expected result

If caching is disabled all handler options should be hidden too. 

### Actual result

<img width="917" alt="Screenshot 2021-05-09 at 19 58 17" src="https://user-images.githubusercontent.com/400092/117583759-ea108680-b100-11eb-9b03-cf4520d48790.png">

**Comment by brianteeman** [comment]
Please test #33777

**Comment by alikon** [comment]
closing as we have a pr #33777
