### ISSUE TITLE
[4.x] Refactor Batch processing of redirects 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33714]
### Steps to reproduce the issue

System -> Redirects. 
Create some redirects
Note the Batch Update Selected URLs button. 

This is one of those UI's that is totally alien to Joomla admin, **it should be a toolbar button, that links to a modal view**. That would be more in keeping with Joomla Admin UI.

An example of that would be batch processing the users. 

### Expected result

Consistency.

An example batch process from Users is this:

https://user-images.githubusercontent.com/400092/117583462-31961300-b0ff-11eb-875b-60f3a3568523.mp4

### Actual result

![image](https://user-images.githubusercontent.com/400092/117583422-04e1fb80-b0ff-11eb-9c86-e86fde1708d9.gif)

**Comment by Quy** [comment]
Related #25489

**Comment by Quy** [comment]
#25489

> This allows us to have required attributes for batch and a corresponding xml form definition for future use in the API.
> Right now you basically can't have required fields in batch fields due to issues such as that in #25442
