### ISSUE TITLE
[4.0] Featured Articles-view: Undefined index id in action-button.php line 27

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33725]
### Steps to reproduce the issue

As title say:

> ![image](https://user-images.githubusercontent.com/78906980/117629989-03eeaf80-b17b-11eb-951a-ba85bdc6863d.png)

### Expected result

No Notice.

### System information (as much as possible)

> ![image](https://user-images.githubusercontent.com/78906980/117630419-752e6280-b17b-11eb-9f9d-aaf43f51d9c6.png)

**Comment by himanshu007-creator** [comment]
Confirmed the issue.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33738 . Thanks in advance.
