### ISSUE TITLE
[4.0] Finder can't search for non-english queries

### ISSUE THREAD

**Issue by nozaro33** [joomla/joomla-cms#33721]
Hi all, I know that currently most languages aren't available in Joomla 4 beta, so maybe this issue won't be bothered until Joomla 4 RC. I had a test site update from Joomla 3 -> 4, so my site has English and Chinese. 
 
### Steps to reproduce the issue

Multilanguage Joomla 4 Beta 8 site
Create content for English and other non-english Language (In my case, Chinese)
Use finder to search for content
When on English version of site, can search for non-english queries like (ex: 周佳宥), but when you filter switch to Chinese, the query can only find english terms, and cannot find any queries that aren't in Chinese (English queries work) . Screenshot attached below

### Expected result

Can search for any terms whether english or not, or on which language filter the site is currently activated on. 

### Actual result
As mentioned, you cannot search for non-english queries when on the "non-english" language filter, but can when on the english version of site.

### System information (as much as possible)

Joomla! 4.0.0-beta8-dev Development [ Mañana ] 2-February-2021 20:02 GMT
Linux cp39.secserverpros.com 2.6.32-042stab124.2 #1 SMP Fri Sep 1 20:42:18 MSK 2017 x86_64
mysql 5.6.39

### Additional comments

I'll be happy to help tackle this issue, but will need some guidance on where to start. 

Both using the exact same query: 周佳宥 (chou chia yu) 
Search result when on "Chinese" site
<img style="border:1px solid #ccc" width="916" alt="Screen Shot 2021-05-10 at 10 19 21" src="https://user-images.githubusercontent.com/25219289/117599036-955e2180-b17b-11eb-8115-8d17436b59af.png">
<hr>
Search result on "English" site
<img style="border:1px solid #ccc"  width="1129" alt="Screen Shot 2021-05-10 at 10 19 35" src="https://user-images.githubusercontent.com/25219289/117599040-98f1a880-b17b-11eb-9a96-a664e0a01c3b.png">

**Comment by ghost** [comment]
Site using en-gb and fa-ir. Sample data for multilingual and for blog are installed (blog for both languages).

#### Search for "قالب شما (fa-IR)" on

fa-ir | en-gb
-- | --
![image](https://user-images.githubusercontent.com/78906980/117607392-2b824f80-b15c-11eb-8303-7e9ee53fb2d3.png) | ![image](https://user-images.githubusercontent.com/78906980/117607503-63899280-b15c-11eb-9124-6d5f8737360f.png)

If i understand your issue correct it works with persian languae, not chinese. Maybe it depends on non-available language-packet for chinese as you wrote in your comment.

**Comment by nozaro33** [comment]
Yes, I guess that's probably the issue. If I add &l=en-GB to the query (url), then it can find the terms correctly.   So probably just an issue for non-available languages?

**Comment by ghost** [comment]
i think you may interested on #21806 and can close the issue in the meantime?

**Comment by Hackwar** [comment]
I will review that soon

**Comment by Hackwar** [comment]
I've taken a look at this and to me right now this works as expected. Can you check if this has been solved in the meantime?

**Comment by Quy** [comment]
Closing until additional info is provided.
