### ISSUE TITLE
[4.0] (backend) Articles - unable to unpublish

### ISSUE THREAD

**Issue by rjharishabh** [joomla/joomla-cms#33728]
### Steps to reproduce the issue
`Dashboard` > `Content` > `Articles`

`Click on published icon to unpublish`

`Nothing happens`

### Expected result
`The article should be unpublished`

### Actual result
Nothing happens

![unpublish](https://user-images.githubusercontent.com/61203226/117642613-1e3d8300-b1a5-11eb-97ff-d1f9facb72ab.gif)

### System information (as much as possible)
PHP 8.0.3
MySQLi 10.4.18-MariaDB
Chrome & Firefox on Windows 10

**Comment by ghost** [comment]
If you use workflow you unpublish it via the stage-icon (open a drodown). 

There are issues open about the showing of Status an Featured and using workflow (as far as i remember @brianteeman and @chmst wrote about).

**Comment by rjharishabh** [comment]
> If you use workflow you unpublish it via the stage-icon (open a dropdown).

I know, but here in the tooltip, it is mentioned that `Select to unpublish`

**Comment by himanshu007-creator** [comment]
I am unable  to reproduce this.

![record](https://user-images.githubusercontent.com/65963997/117647901-36180580-b1ab-11eb-9c36-909d482b33b6.gif)

**Comment by ghost** [comment]
@himanshu007-creator you have to enable workflow.

**Comment by ghost** [comment]
@rjharishabh 

> I know, but here in the tooltip, it is mentioned that `Select to unpublish`

Yes, and there are other issues about that and how to solve it :-)

**Comment by ghost** [comment]
@rjharishabh now i found what i mean: #33575

**Comment by richard67** [comment]
Can we close this issue as duplicate to #33575 ?
