### ISSUE TITLE
[4.0] Joomla Help Index Page

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#33722]
### Steps to reproduce the issue

Go to Administrator / Help / Start Here - Joomla! Help
Scroll down to near the bottom of the long list and click an item there

### Expected result

Something should happen

### Actual result

Nothing appears to happen because the Iframe with the new help page has been loaded out of sight.

### Additional comments

I previously had a fix committed for this issue using a scrolling div for the index. The css for this has been removed in the recent round of template clean up. I now have a different solution using scroll to top on selecting any help item. For my testing I have put this in the com_admin/tmpl/help/default.php like so:

```/** @var Joomla\CMS\WebAsset\WebAssetManager $wa */
$wa = $this->document->getWebAssetManager();
$content = "
document.addEventListener('DOMContentLoaded', function(event) {
	let helpIndex = document.getElementById('help-index');
	let links = helpIndex.querySelectorAll('a');
	links && links.forEach(element => {
		element.addEventListener('click', event => {
			window.scroll(0,0);
		});
	})
});
";
$wa->addInlineScript($content);
```
Is that best, or should it be in one of the Javascript files?

**Comment by sandewt** [comment]
See #33644<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33722">issues.joomla.org/tracker/joomla-cms/33722</a>.</sub>

**Comment by dgrammatiko** [comment]
> Is that best, or should it be in one of the Javascript files?

Please use a file, don't use inline scripts

**Comment by alikon** [comment]
please test ~~#33724~~
 sorry #33742

**Comment by sandewt** [comment]
> please test #33724

Should be:

please test #33742

**Comment by alikon** [comment]
oops
