### ISSUE TITLE
[4.0] Category Blog: Different layout for first and following pages

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33739]
### Is your feature request related to a problem? Please describe.

This is a partial redo of #30700. As there where 2 issues reported and one of them solved, the redo is about the second one. 

The original comment by @200MPHMEDIA:

> When going to the 2 page, or next - the layout regurgitates the initial layout setup. Is that what it is intended to be, replicating the class layouts set for the main screen of the Menu Link Item?

### Describe the solution you'd like

If i understand @200MPHMEDIA correct he wants the possibilty for a different layout for first and following pages in blog-menu.

**Comment by brianteeman** [comment]
As I stated in the other issue this is the expected behaviour
