### ISSUE TITLE
[4.0] [Media] Infobar: "local-0:/" in folder

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33736]
### Steps to reproduce the issue
Go to Media Manager, select any available folder and click on the **I** icon (behind the search field).

The FOLDER line displays a strange `local-0:/`.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/117656431-0237e280-b1a1-11eb-9aca-21a718254c9e.png)

In addition, the block of information must be lowered by 1px.

```
.media-infobar {
top: 48px;
...
}
```

![Screenshot_2](https://user-images.githubusercontent.com/8440661/117656637-44612400-b1a1-11eb-88ee-5b154c187f3c.png)

**Comment by PhilETaylor** [comment]
`displays a strange local-0:/`

Its not strange. Its the local adapter. Joomla 4 supports multiple adapters (for example. you could have an Amazon S3 adapter) - I have yet to see a working adapter other than local though I know others are working on them.

**Comment by Kostelano** [comment]
Thanks for the answer.
Is there any benefit to the average user in this information?

**Comment by PhilETaylor** [comment]
> Is there any benefit to the average user in this information? 

Ive repeatedly asked myself the same question now for many years. I guess there is, **if** you have multiple adapters.

**Comment by Kostelano** [comment]
Thanks for the answer.
Since this is not an issue, I close it.
