### ISSUE TITLE
[4.0] Joomla! Update Notification plugin

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33758]
The field description says
> A comma separated list of the email addresses which will receive the update notification emails. The addresses in the list MUST belong to existing users of your site who have the Super User privilege

The code says

>  * Sends out an email to all Super Users or a predefined email address 

/me confused

**Comment by joomdonation** [comment]
The way it works is that:

- If you do not enter any emails in **Super User Emails** parameter of the plugin, all Super Users will receive update notification
- If you enter some emails into **Super User Emails** parameter of the plugin, only Super Users who has these emails will receive notification (basically, some kind of Super Users filter)

Not sure if that's the information you are looking for?

**Comment by brianteeman** [comment]
Thats how I thought it works which means that the code comment "or a predefined email address" is confusing because that predefined email address must also be that of a Super User.

**Comment by brianteeman** [comment]
See #33766
