### ISSUE TITLE
[4] The size of the top bar (Brand/Title/Buttons in blue) changes from a list view to an edit view

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33755]
The size of the top bar (Brand/Title/Buttons in blue) changes from a list view to an edit view :-) 

https://user-images.githubusercontent.com/400092/117728740-bb1e1180-b1e1-11eb-9d76-5cff15f75ddd.mp4

@ciar4n

**Comment by brianteeman** [comment]
Please test #33756

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33756 . Thanks in advance.
