### ISSUE TITLE
[4.0] Webauthn doesn't work on offline page

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#33779]
### Steps to reproduce the issue
1. Activate Webauthn
2. Set the website into offline mode
3. Try to login with Webauthn

### Expected result
You see a the Webauthn button and can login

### Actual result
No Webauthn button.

**Comment by PhilETaylor** [comment]
[4] Implement extra buttons to offline page #33793

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33793 . Thanks in advance.
