### ISSUE TITLE
[4] Reminder to update joomla-framework/session 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33778]
@wilsonge 

reminder to update joomla-frameowrk\session from 2.0.0-beta tagged 5 Jun 2020 to ensure that [the redis session issue](https://github.com/joomla-framework/session/pull/51) is resolved in Joomla 4.

https://github.com/joomla-framework/session/compare/2.0.0-beta...2.0-dev

**Comment by richard67** [comment]
It first needs a new beta release or tag version there before we can update it here.

**Comment by PhilETaylor** [comment]
This issue, once closed, will fix: [4.0] Redis Session Management broken. #30377

**Comment by richard67** [comment]
Solved with commit https://github.com/joomla/joomla-cms/commit/94c17f75cfb3be891f119964f8ecdd3c002f53a3 . Thanks @wilsonge .
