### ISSUE TITLE
[4.0] Multilingual Associations enabled by default

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#33784]
### Steps to reproduce the issue
Do a new installation with only one language.
Go to Components > Multilingual Associations.
See warning:
> You can't create Multilingual Associations if the site is not set as multilingual and/or Associations is not enabled in the Language Filter plugin.

### Expected result
 `Multilingual Associations` not to be enabled by default unless more than one language is installed.

**Comment by brianteeman** [comment]
I have said this since the day multilingual associations was introduced. The response has always been "but how would someone know that its possible". An argument I have always said is simply wrong.

🍿

**Comment by joomdonation** [comment]
Let's go with easy solution https://github.com/joomla/joomla-cms/pull/33815 for now.

**Comment by ghost** [comment]
The Options are shown even the multilingual associations are not visible by the now closed pr #33815. Comparing to "Redirect-Plugin" its the same, so i guess its expected?

**Comment by brianteeman** [comment]
Why is this still open? The PR was merged.

> The Options are shown even the multilingual associations are not visible

That allows you to configure it before it is visible

**Comment by joomdonation** [comment]
Closing because the PR was merged.
