### ISSUE TITLE
[4.0] Alerts invisible after error / information during installation

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#33782]
### Steps to reproduce the issue
Probably this is a duplicate, but cannot find a similiar issue.
It is not userfriendly that alerts and messages are invisible on top of the screen when an installation breaks. 

### Expected result
If the installation breaks and alerts are shown, the screen scrolls up to the top.

### Actual result
The screen remains unchanged, nothing happens. As a user I am waiting ... and waiting .. and waiting

**Comment by richard67** [comment]
Related issue: #29461 .

**Comment by richard67** [comment]
Closing as duplicate, see issue #29325 .
