### ISSUE TITLE
[4.0] Increase the size of the plus icons

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33797]
### Steps to reproduce the issue
It is rather a proposal. It seems to me that in the context of everything "big", the size of the plus signs should be increased by removing the `icon-xs` class.

Even on my small monitor, these pluses seem tiny.

![Screenshot_8](https://user-images.githubusercontent.com/8440661/117869767-e36e4480-b2a3-11eb-99d2-ffb30bf02143.png)

**Comment by brianteeman** [comment]
Nothing to do with accessibility

**Comment by Kostelano** [comment]
Indirectly still connected. Why is everything so huge? Atum can hardly be called a "compact" design.

Ok, fixed in title and text.

**Comment by brianteeman** [comment]
it is still nothing to do with accessibility. I am sick of accessibility being used as a reason/explanation/excuse there was absolutely nothing to do with accessibility in the size of anything. those were design choices by the people who made the template.

**Comment by brianteeman** [comment]
As you can see from the last iteration of the template the plus was styled completely different. The change was a design decision by @ciar4n 

Propose a change by all means but please stop blaming accessibility

![image](https://user-images.githubusercontent.com/1296369/117875485-21ff0180-b29a-11eb-8331-09b0b0e6335c.png)

**Comment by PhilETaylor** [comment]
The whole ROW is clickable. 

You dont need to click the + icons. 

The + icons are the same size as the text, which looks about right to me, as the whole row, including the whitespace, is all clickable.

**Comment by brianteeman** [comment]
Yes you do. Click on the text you get the list. Click on the + you get new

**Comment by Kostelano** [comment]
Why suddenly? Clickable line - to the corresponding list further. Plus = element creation.

UPD
At the same second.

**Comment by brianteeman** [comment]
Actually Phil is almost correct there is a bug in that the flex-grow class on the link makes the link target very big

**Comment by brianteeman** [comment]
there are a few css bugs in that one line. preparing a fix

**Comment by brianteeman** [comment]
As I was fixing other issues on that line I changed the size of the icon as requested at the same time. I never objected to your issue just your statement about accessibility

**Comment by Kostelano** [comment]
Thank you. I see. No problems :)
