### ISSUE TITLE
[4.0] Secret way to reinstall core files

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33796]
### Steps to reproduce the issue
I wanted to reinstall the core Joomla core files. I went to System - Joomla (Updates), then clicked the Check for updates button and finally got to the page for reinstalling the kernel files.

Is there an easier and less secret way to get to this page? I suggest placing a corresponding button on the panel so that any administrator can see the page if necessary.

I am at a loss to give a title to such a button, but during the discussion we will decide.

![Screenshot_7](https://user-images.githubusercontent.com/8440661/117869020-f5031c80-b2a2-11eb-8025-376d6f8920e2.png)

I will note that I know about this method from Joomla 3. But how can a new user know about it?

**Comment by Bond97** [comment]
Maybe to solve this - auto-check for updates if nightly build channel is installed in custom url.

Or add information about date and time to xml file on update url. And com_joomlaupdate will be check date and time besides package and name version.

Note: 2 ways above- it's for update nightly version old to new, for example 1 April to 2 April.

How about reinstall version in one day- I don't know, how to simplify that process. Maybe with corresponding button, as suggested on issue.

**Comment by PhilETaylor** [comment]
shhh - its a secret feature :)

**Comment by Fedik** [comment]
It not hidden feature.
The button label shown depend from last version in update XML. 
If it the same as installed then it show "Reinstall", when available more new version it will show "Update".

The reason that we cannot show "Reinstall' from begining, because we need to pre-load XML from update server.
If I nothing missed.
