### ISSUE TITLE
[4] Media Manager cannot edit/rename image in list mode

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33791]
### Steps to reproduce the issue

Go to media manager, enable list mode, select an image

### Expected result

Toolbar button allowing Edit and Rename? or at least "some way" without having to go back to preview mode. 

### Actual result

Absolutely no way to rename or edit an image from the list view 

<img width="1311" alt="Screenshot 2021-05-11 at 18 47 00" src="https://user-images.githubusercontent.com/400092/117861382-48687100-b289-11eb-9836-0d32fe7ffcdf.png">

**Comment by brianteeman** [comment]
Duplicate report #33647
