### ISSUE TITLE
[4] Media Manager cannot sort columns

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33790]
### Steps to reproduce the issue

Add 100000 images to a folder (ok, add a few) 

Go to the Media Manager, enable list mode

### Expected result

Ability to sort A-Z by name, or any other column. 

### Actual result

No Ability to sort A-Z by name, or any other column. 

https://user-images.githubusercontent.com/400092/117861158-07705c80-b289-11eb-9390-21d611251cc5.mp4

**Comment by brianteeman** [comment]
duplicate #31347 ?
