### ISSUE TITLE
[4.0] btn-secondary for Close button

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33795]
### Steps to reproduce the issue
Go to the control panel - menus, create a new (or edit the existing) menu item. Go to the Module Assignment tab, click on any of the modules.

The pop-up window for the CLOSE button is missing the btn-secondary class. 

![Screenshot_4](https://user-images.githubusercontent.com/8440661/117867728-68a42a00-b2a1-11eb-8587-eb3c69657359.png)

By the way, there are several files where only the "btn" class is used.

![Screenshot_5](https://user-images.githubusercontent.com/8440661/117868262-0bf53f00-b2a2-11eb-9890-6d42a3dbe505.png)

**Comment by PhilETaylor** [comment]
The modal buttons are also in the wrong order https://github.com/joomla/joomla-cms/issues/33701

**Comment by Kostelano** [comment]
This is the case everywhere. I closed a similar issue of mine after you posted an issue on button order.

**Comment by eopws** [comment]
> CLOSE button is missing the btn-secondary class.

Maybe btn-danger class?

**Comment by Kostelano** [comment]
> Maybe btn-danger class?

Not sure. I compared with, for example, PR https://github.com/joomla/joomla-cms/pull/33775.

**Comment by Kostelano** [comment]
PR https://github.com/joomla/joomla-cms/pull/34153.
