### ISSUE TITLE
[4.0] No border rounding on button hover behavior

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33792]
### Steps to reproduce the issue
Go to Control Panel -- Menus -- Manage (panel on the right). Click on any of the modules. A drop-down item on hover has no rounding of its borders. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/117865586-c7b46f80-b29e-11eb-89c2-3a2295602847.png)

**Comment by brianteeman** [comment]
My css isnt strong enough to fix this but the issue is coming from   `administrator\templates\atum\scss\blocks\_header.scss`

```

  &.first:not(.last) {
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }

  &.last:not(.first) {
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }

  &:not(.first):not(.last) {
    border-radius: 0;
  }
```

it probably needs a class for :onlychild

**Comment by Kostelano** [comment]
Clicking on a line in editing / unpublishing a module - in the same place.

![Screenshot_3](https://user-images.githubusercontent.com/8440661/117878330-541a5e80-b2ae-11eb-88d8-a43bfc677390.png)

**Comment by infograf768** [comment]
As of today, the "tip" for the menu module is NOT what is described by the OP.

I get here, when clicking on the down arrow

<img width="358" alt="Screen Shot 2021-05-12 at 12 00 29" src="https://user-images.githubusercontent.com/869724/117957464-64682300-b31a-11eb-94c1-8d319b9d14a6.png">

**Comment by brianteeman** [comment]
@infograf768 when you hover over the Author Menu you will see that it is then black with square corners

**Comment by infograf768** [comment]
Oh, when hovering the tip to edit the module... Got it.

**Comment by brianteeman** [comment]
Sorry I reference the wrong scss file it should have been `administrator\templates\atum\scss\vendor\bootstrap\_dropdown.scss`

**Comment by brianteeman** [comment]
Please test #34059

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34059 . Thanks in advance.
