### ISSUE TITLE
[4.0] [Atum] Permissions: moving a list item on hover

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33798]
### Steps to reproduce the issue
Go to the permissions tab for any extension. Please note that when you hover the mouse cursor over a group of users, a slight shift of the list item occurs.

I don't know if it was intended that way, but it doesn't look very good.

If ok, please close Issue. I'm not sure.

In addition, the movement of the mouse makes the menu jump. 

![Screenshot_9](https://user-images.githubusercontent.com/8440661/117871428-0994e400-b2a6-11eb-8145-825400f9fc02.png)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33871 . Thanks in advance.
