### ISSUE TITLE
[4.0] Users: New Field Group: publishing tab is col-md-6

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33800]
### Steps to reproduce the issue
Go to field groups (for example, for users), create a new field group. The publication tab uses `col-md-6`, which is visually inappropriate.

![Screenshot_11](https://user-images.githubusercontent.com/8440661/117874142-4f9f7700-b2a9-11eb-83c2-4ff1b9ff0709.png)

**Comment by Kostelano** [comment]
It's the same story when creating fields.

**Comment by ciar4n** [comment]
PR created.. #33806
