### ISSUE TITLE
[4.0] Components Dashboard: 5th list item in smart search

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33807]
### Steps to reproduce the issue
Go to the control panel, in the menu on the left select the panel of all components. Please note that there is a 5th item in the list in the smart search block.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/117876576-321fdc80-b2ac-11eb-9d35-ea340f0a13d9.png)

**Comment by rjharishabh** [comment]
I also cannot replicate this -  Chrome and Firefox on windows

![dashboard components](https://user-images.githubusercontent.com/61203226/117918604-f5ce9980-b308-11eb-985c-060a3df748c3.JPG)

**Comment by Kostelano** [comment]
It’s strange. I have a naked Joomla, which I update with nightly builds and sometimes to test individual PRs.

Ok, while I close it.

**Comment by ghost** [comment]
>  I have a naked Joomla, which I update with nightly builds

Have done this before and got similar experience. Now i install daily joomla new via launch.joomla org and make a backup. After every pr via prebuild package a do a restore.
