### ISSUE TITLE
[4.0] Vertical line doesn't extend to the bottom

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#33809]
### Steps to reproduce the issue
Go to Global Configuration > Articles > Categories
When content is shorter than sidebar nav, the vertical line/divider doesn't extend to the bottom.

### Actual result

![global-configuration](https://user-images.githubusercontent.com/368084/117878286-73879c00-b25a-11eb-9d5e-fec388f397c7.jpg)

**Comment by ghost** [comment]
Confirm this issue.

**Comment by eopws** [comment]
Do you have the same problem in other components?

**Comment by Quy** [comment]
Yes, when the content is shorter than the sidebar nav.

**Comment by Quy** [comment]
Closing per PR #33821. Thanks for the PR.
