### ISSUE TITLE
Privacy: Information Requests: icon / checkbox is missing

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33810]
### Steps to reproduce the issue
Go to Control Panel - Users - Privacy. Click on the link "Published Request Form Menu Item", create a request for yourself.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/117879316-7eb8e700-b2af-11eb-8dc8-a2fd723006d4.png)

Go to confidentiality again. Note that my action cell is empty.

Unfortunately, now I cannot remember from the experience of Joomla 3 what should be there. Perhaps the icon / checkbox is missing, it should be checked.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/117879361-8d9f9980-b2af-11eb-9d9b-c431a50b0e23.png)

**Comment by PhilETaylor** [comment]
This is by design. 

The email address will have received an email, once that email is read and the link clicked in it to confirm the request, then the admin can take actions. They will appear as icons there.

**Comment by Kostelano** [comment]
Thanks for the clarification, closed.
