### ISSUE TITLE
[4.0] Users: Banners: New Client: metadata tab is col-12 col-lg-6

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33813]
### Steps to reproduce the issue
Short. By analogy with https://github.com/joomla/joomla-cms/issues/33800.

![Screenshot_7](https://user-images.githubusercontent.com/8440661/117883937-b5ddc700-b2b4-11eb-85e0-4ef785e4a949.png)

**Comment by rjharishabh** [comment]
PR #33816
