### ISSUE TITLE
[4.0] Private Messages: you can write (answer) to yourself

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33812]
### Steps to reproduce the issue
After creating a personal data request like in issue https://github.com/joomla/joomla-cms/issues/33810, you can now send yourself a message.

You, as an administrator, have received a notification that a user has requested data.

![Screenshot_4](https://user-images.githubusercontent.com/8440661/117880313-a52b5200-b2b0-11eb-9a43-480e45f15cb5.png)

You can read the notification and reply to yourself. Yes, I agree that this is pointless and nonsense. But that's a catch.

The system should issue an error message when sending such a response.

You are simply not on the list of users to which you can send a message. And here - you are already entered into the field.

![Screenshot_5](https://user-images.githubusercontent.com/8440661/117881056-7792d880-b2b1-11eb-994a-b344bb728fe6.png)

**Comment by chmst** [comment]
Why? Do you think that it destroys something? Fo example I could use it like a  To do lists where I can append new items, for example.

**Comment by PhilETaylor** [comment]
Because this has always been the way by design.

You cannot send a message to yourself. Try it and you will see.

Therefore you should not be able to reply to yourself.￼

**Comment by brianteeman** [comment]
This should be a release blocker ;) ;)

**Comment by chmst** [comment]
Therefore I want to be able to send a messeage to myself :)
