### ISSUE TITLE
[4.0] Smart Search: New Filter: select switch not working + language constant problem

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33814]
### Steps to reproduce the issue
Install demo data, go to smart search and index the site content. Then go to smart search filters and create a new filter.

In my case, I found that the `PLG_FINDER_QUERY_FILTER_BRANCH_S_AUTHOR` language constant is not displayed (it is in the localization files) + the selection switch does not work (I noted which one in the screenshot).

![Screenshot_8](https://user-images.githubusercontent.com/8440661/117885379-744e1b80-b2b6-11eb-89e9-5d3446d975ee.png)

**Comment by ghost** [comment]
### Confirm part 1 "Toggle select":

Only red marked Button `Toggle Selection` works

> ![image](https://user-images.githubusercontent.com/78906980/117935037-9a4ddd00-b303-11eb-827a-4673248f6152.png)

Click on other Buttons bring

> ![image](https://user-images.githubusercontent.com/78906980/117935518-12b49e00-b304-11eb-8103-9e5882f92cec.png)


Can't confirm part 2 "Language constant" as shown in screenshot above.

**Comment by eopws** [comment]
@Kostelano Can you provide more system information, please?

**Comment by PhilETaylor** [comment]
Paging @dgrammatiko ... he loves to eat jQuery for breakfast :)

**Comment by dgrammatiko** [comment]
Check #33921
FWIW the invalid HTML is way worse than the use of jQuery. We have to educate people better (hopefully the history won't point back to me... 🤣
