### ISSUE TITLE
4.0 Difference in height of visibility button and password input 

### ISSUE THREAD

**Issue by deveshprasad** [joomla/joomla-cms#33823]
### Steps to reproduce the issue

Go to the main joomla website page and view on mobile view

### Expected result

![10 05 2021_20 55 28_REC](https://user-images.githubusercontent.com/63739986/117997238-6e147980-b360-11eb-8dee-4676cfd58fa4.png)

### Actual result

![11 05 2021_21 10 38_REC](https://user-images.githubusercontent.com/63739986/117997244-6f45a680-b360-11eb-93c8-7580bc930a6f.png)

### Additional comments

A very unnoticable issue but still an important one .

**Comment by eopws** [comment]
1. Where is the place, you got the problem?
2. What is on screenshot that you provided in "System information" section?
3. If you provided screenshot where everything is fine, that probably means that you solved the issue, so why don't you open a pull request?

**Comment by rjharishabh** [comment]
Please add 4.0 in the Title of the issue and change the System information

**Comment by deveshprasad** [comment]
@eopws I have opened a pull request solving it just want to confirm on which branch should I work?
1)Login form on the joomla main webpage

**Comment by richard67** [comment]
Closing as having a pull request. See #33824 .
