### ISSUE TITLE
[4.0] Click to check the checkbox in Languages: Overrides

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33826]
### Steps to reproduce the issue
Go to language constant overrides, create any override. In the list of overrides, there is no script for selecting a line by clicking on a line by analogy with, for example, https://github.com/joomla/joomla-cms/pull/33413. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/118015408-e842ff00-b35c-11eb-8f69-34398c60d24b.png)

@rjharishabh

**Comment by rjharishabh** [comment]
@Kostelano Thanks 
please test PR #33828
