### ISSUE TITLE
[4.0] Two scss files of the Atum template have the same content for large parts

### ISSUE THREAD

**Issue by eopws** [joomla/joomla-cms#33829]
### Problem identified
Have you ever noticed that /administrator/templates/atum/scss/vendor/bootstrap/_form.scss from line 18 to line 48 and /administrator/templates/atum/scss/blocks/_form.scss from line 78 to line 108 have the same styles?

The main file template.scss connects both of them and they are connected only in that file, so we can reduce one of those files.

### Proposed solution
Delete styles from one of those files.

**Comment by richard67** [comment]
@eopws I was so free to adjust the title of this issue a bit so it's easier for us to categorize and to be found by the right experts.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #33834 . Thanks in advance.
