### ISSUE TITLE
[4.0] Sample data blog - templates

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33832]
This string PLG_SAMPLEDATA_BLOG_SAMPLEDATA_CONTENT_ARTICLE_1_INTROTEXT needs updating/correcting as highlighted

To totally change the look of your site you will probably want to install a new template. **In the Systems menu on the Install module, select Extensions from the list and then go to the Install tab.** There are many free and commercial templates available for Joomla.

**Comment by chmst** [comment]
please test #33866

**Comment by brianteeman** [comment]
thanks @chmst
