### ISSUE TITLE
[4.0] function setSeparator

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33831]
As far as I can tell this function is never used and should be deprecated and marked for deletion

**Comment by PhilETaylor** [comment]
`@since   1.5`

Just old baggage... phpStorm says its not used so get rid of it :)

**Comment by chmst** [comment]
remove ;)

**Comment by brianteeman** [comment]
shouldnt it be first marked as deprecated?

**Comment by brianteeman** [comment]
Closed see #33913
