### ISSUE TITLE
Custom field param of subform type not accesible in component as com_fields inserted custom field.

### ISSUE THREAD

**Issue by mperaya** [joomla/joomla-cms#33838]
### Steps to reproduce the issue
On joomla 3.9.26 I have programmed a new custom field witch uses a subform type param.
When I add this field to any group and I want to see the field layout result, it has no access to the subform type param at all in the component context, for example, com_content. The other custom params are all ok.
The subform param and their values are shown and managed with no problem on the joomla custom fields interface.

### Expected result
Equals all other kind of params... date, text, number, etc. I think a subform type param must to be recognized for the custom field infraestructure for be used in any other logic we need to program.

### Actual result
All standar params types are recognized ok. Only the subfom type is ignored an not shown, nor accessible.

### System information (as much as possible)
Joomla 3.9.26 on linux debian buster with apache and php 7.3

### Additional comments
I have overloaded the onCustomFieldsPrepareDom on my own field to force to add the subform type param as a field attribute for use in other parts of the logic.
The param values are readed and stored with the joomla custom field interface with no problems. Only they are not accessible at all in the field usage on a commponet like content without the overloaded onCustomFieldsPrepareDom function.

**Comment by eopws** [comment]
Could you provide step-by-step instruction on how to reproduce the issue?

**Comment by joomdonation** [comment]
I'm closing this issue the issue was reported for Joomla 3 and no further information provided after being requested for more 1.5 years to allow us to understand the issue and check to see if it is valid

Feel free to re-open the issue if it is still valid for latest Joomla 4. But please give us more information so that we can understand the actual issue. Thanks !
