### ISSUE TITLE
[4.0] [Media] Save without page reload + strange editing logic

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33843]
### Steps to reproduce the issue
Go to Media Manager, select any image to edit.

1. For example, on the rotation tab, make changes to the image quality and degrees (use the buttons 0/90/180/270). Press the RESET button. The image returns to its original position, but the indicators themselves in the fields are in place (unchanged).

2. If you click on the button to save the image, this will happen, as practice has shown, but without reloading the page. At the same time, there is no information / progress bar for the user.

3. Does the image quality change work ONLY in combination with other parameters? If I make changes only to the quality (reduce, for example, to 10), after saving the image does not change the file size (respectively, the quality too). If, along with decreasing the quality, I make any other changes (rotation, cropping, etc), the image changes. Why can't I make only quality changes? The size of the image width / height may suit me.

![Screenshot_3](https://user-images.githubusercontent.com/8440661/118161412-37a23180-b428-11eb-990d-2c0399475455.png)

4. Arrows in the fields do not work - no focus on them (everywhere according to Joomla 4). In Joomla 3, these arrows work.

![Screenshot_4](https://user-images.githubusercontent.com/8440661/118161856-c020d200-b428-11eb-8599-6b7f4a579942.png)

**Comment by YatharthVyas** [comment]
I was able to reproduce all 3 of these. Issues confirmed.

**Comment by eopws** [comment]
Quality inputs are not synchronized. Is it ok?
![test](https://user-images.githubusercontent.com/42320170/119386538-5b8b3000-bcd0-11eb-858a-1670dd9690bd.gif)

**Comment by eopws** [comment]
> 1. Arrows in the fields do not work - no focus on them (everywhere according to Joomla 4). In Joomla 3, these arrows work.

Hmm. Weird, but my arrows work..

**Comment by Kostelano** [comment]
@eopws What browser are you using?

I just installed a fresh installation from the latest nightly build and the arrows on Mozilla are not working for me. Nowhere.

**Comment by eopws** [comment]
> @eopws What browser are you using?

Google Chrome version 90.0.4430.212 (Official Build) (64-bit)

**Comment by eopws** [comment]
> I just installed a fresh installation from the latest nightly build and the arrows on Mozilla are not working for me. Nowhere.

I have installed my Joomla about a week ago. Maybe arrows went broken in one of new PRs?

**Comment by brianteeman** [comment]
the arrows come from the browser. some browsers display them all the time. other browsers display them on focus

**Comment by Kostelano** [comment]
No, I have already changed the setting several times. This is definitely not the last PRs.

@brianteeman Right now the arrows are NOT working in Joomla 4, but they are working in Joomla 3. Mozilla.

**Comment by eopws** [comment]
> I just installed a fresh installation from the latest nightly build and the arrows on Mozilla are not working for me. Nowhere.

Confirmed. They don't work in Firefox.
I don't know why I made a gues that it was a PR.

**Comment by Kostelano** [comment]
@eopws Now try it in Joomla 3. It's okay there.

**Comment by eopws** [comment]
> @eopws Now try it in Joomla 3. It's okay there.

Yes, but they work a little bit weird, I have to aim on that arrow!

**Comment by eopws** [comment]
> 3\. Does the image quality change work ONLY in combination with other parameters?

Probably yeah. Look at input name's.

![resize](https://user-images.githubusercontent.com/42320170/119389683-a27b2480-bcd4-11eb-97ae-4ea7d221d19d.png)

![quality](https://user-images.githubusercontent.com/42320170/119389704-a7d86f00-bcd4-11eb-88fd-2b836d4476d3.png)

> Quality inputs are not synchronized. Is it ok?

That's also an answear to my question

**Comment by eopws** [comment]
> 3\. If, along with decreasing the quality, I make any other changes (rotation, cropping, etc), the image changes.

That's is probably right behaviour as the quality input defines kind of "loosing quality" when resize, crop, rotate.

> Why can't I make only quality changes?

It is a new feature that should be in a separate issue.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34885 . Thanks in advance.
