### ISSUE TITLE
[4] Vertical tabs not pixel perfect and jump with mouseover

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33847]
### Steps to reproduce the issue

Mainly used on the permissions tab in config screens

Mouse over

### Expected result

All heights maintain so no twitching

### Actual result

https://user-images.githubusercontent.com/400092/118176266-1c83f180-b429-11eb-8ced-acb732c9c5ea.mp4

### System information (as much as possible)

safari on mac

**Comment by brianteeman** [comment]
duplicate #33798 ?

**Comment by PhilETaylor** [comment]
damn these kids are reading my mind each day...
