### ISSUE TITLE
[4] back to top link causes excessive footer space

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33845]
### Steps to reproduce the issue

Enable the back-to-top link in the default template settings on the frontend. 

Scroll down.

### Expected result

No additional whitespace or margin added to the bottom of the page

### Actual result

Considerable (depending on viewport size) white space added to the bottom of the page 

Watch:

https://user-images.githubusercontent.com/400092/118175544-26592500-b428-11eb-88bf-e8a2d8e0aa50.mp4

### System information (as much as possible)

safari on mac

**Comment by ghost** [comment]
Issue confirmed for safari/mac, not so much space like @PhilETaylor showed.

No issue for firefox/mac.

**Comment by PhilETaylor** [comment]
> not so much space

Like I said, it depends on the screen size you have (depending on viewport size), I work (mainly) on a huge 27 inch iMac screen at the highest resolution it can cope with. If I make my browser smaller and test, I get less whitespace like you said.

**Comment by brianteeman** [comment]
I can't replicate this on chrome/windows and looking at the css it is all based on the viewport already

**Comment by chmst** [comment]
No problem on win10, no problem on android.

**Comment by hans2103** [comment]
issue confirmed with Safari on Mac. No issue on other browsers... ~~I'll try to make a fix~~ (nu success yet)

**Comment by brianteeman** [comment]
Is safari the new IE?

**Comment by PhilETaylor** [comment]
Can no longer replicate

<img width="1270" alt="Screen Shot 2022-03-06 at 23 16 17" src="https://user-images.githubusercontent.com/400092/156946516-f3b51552-a7b5-4cd6-a5ba-8e2900f19307.png">
