### ISSUE TITLE
[4.0] cachetime and cache_path in configuration hidden

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#33842]
### Steps to reproduce the issue
- When you disable caching in Joomla configuration the fields cachetime and cache_path will be hidden by showon events.

### Expected result
- Never hidden because are used by the Cache class used e.g. by plg_system_cache and lots of 3rd extensions and codes taht use these basic settings.

### Additional comments
- It happened intentionally that these fields are not hidden. There were already discussions in the past.

**Comment by PhilETaylor** [comment]
@brianteeman possibly my fault maybe?

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/33716 ?

**Comment by PhilETaylor** [comment]
actually looking at #33777 I dont think this one was my fault - phew :)

**Comment by brianteeman** [comment]
>There were already discussions in the past.

link ?

**Comment by PhilETaylor** [comment]
This broke this https://github.com/joomla/joomla-cms/pull/27806

**Comment by ReLater** [comment]
> link ?

Really? You want me to look for old issues to prove an obvious issue? I know this change was supposed to be made in Joomla 3 and was NOT merged. Who knows when. Or maybe it was a feature request... 

These settings are not only used for the System Cache in Global Configuration. Maybe we should think about a clearer separation of 1) GLOBAL cache settings and 2) "Sytem Cache" settings. We should reorder them and separate them by a divider or whatever.

Maybe a clearer description that these settings are (sometimes) two pairs of boots.

...if you really think there must be hidden something. I don't know if this issue is relevant for other hidden elements, too.

**Comment by PhilETaylor** [comment]
It also seems `cache_path` is not correctly implemented in places like action logs and log rotation, which, if `$clientid` (I.e administrator) then the [code ASSUMES a hard coded /administrator/cache folder](https://github.com/joomla/joomla-cms/blob/afc3dff9d36b904046421cbfeb5f22c9b2aa35cb/plugins/system/actionlogs/actionlogs.php#L345) to use rather than any user specified `cache_path`
