### ISSUE TITLE
[4] module edit button in wrong place

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33849]
### Steps to reproduce the issue

Install Joomla 4 
Move the breadcrumbs module to the footer template position
Login to frontend as admin

### Expected result

Expect to see the edit icon on the right of the footer to allow editing the breadcrumbs module

### Actual result

Icon it top right corner, popover message is inline with the footer

https://user-images.githubusercontent.com/400092/118178502-ee53e100-b42b-11eb-942c-16914a2da1d6.mp4

### System information (as much as possible)

safari on mac

**Comment by ghost** [comment]
Looks like duplicate/similar issue of #33233

**Comment by PhilETaylor** [comment]
duplicate #33233
