### ISSUE TITLE
[4] Loading fonts ... message padding bottom

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33846]
### Steps to reproduce the issue

Edit template settings on frontend

Note the padding on the bottom of warning about fonts... 

Also this needs some kind of heading/explanation as its out of place, and certainly not Joomla's responsibility to explain what the legal implications should be! It also should not be an `alert alert-warning` which is an Alert Message. Maybe more a blue message, or the blue expanded message like 

<img width="859" alt="Screenshot 2021-05-13 at 20 20 47" src="https://user-images.githubusercontent.com/400092/118176002-be570e80-b428-11eb-92f4-150f5298c09b.png">

### Actual result

<img width="1198" alt="Screenshot 2021-05-13 at 20 19 36" src="https://user-images.githubusercontent.com/400092/118175859-8e0f7000-b428-11eb-8c96-233262096632.png">

**Comment by brianteeman** [comment]
please test #33851
