### ISSUE TITLE
Bootstrap won't go away.

### ISSUE THREAD

**Issue by ptrongithub** [joomla/joomla-cms#33852]
# I know you are hung-up on Bootstrap, buy **_please provide a means of completely disabling Bootstrap!_**

I find that Bootstrap simply gets in the way of creating a truly custom template. I am constantly having to create CSS overrides before I can use any of my code, and Bootstrap's CSS is still there. Adding a CSS Reset adds more code to create/download, and Bootstrap's CSS is still there. I may not use all of Bootstrap, yet Bootstrap's CSS is still there. Not to mention the irrelevant Bootstrap JS.

Things are bad enough with the inconsistencies in HTML between core Joomla and all of the extensions. E.g. what is a button? Is it an <input type="button">, <button>, or <a class="button>. I don't need Bootstrap cluttering things.

I would like to be able to use CSS Grids, Flexboxes, etc., but Bootstrap can get in the way. I would like to use Font Awesome for icons, but Bootstrap can get in the way.

**Not everyone likes Bootstrap.**

**Comment by HLeithner** [comment]
At least in j4 it should be possible to override all Layouts so you get rid of bootstrap. If anything is missing please report it in an issue.

I'm closing it for now but you can reopen if you think I missed something.
