### ISSUE TITLE
[3.9] Discover install error: Call to a member function children() on null

### ISSUE THREAD

**Issue by pranaymirchandani** [joomla/joomla-cms#33862]
### Steps to reproduce the issue
1) discover a module for installation by clicking on extensions->Manage->discover
2) select the extension and click install

### Expected result
Module should install

### Actual result
Get the error below 👎 

An error has occurred.
0 Call to a member function children() on null
C:\xampp\htdocs\libraries\src\Installer\Adapter\ModuleAdapter.php:161
<html>
<body>

Call stack
--
# | Function | Location
1 | () | JROOT\libraries\src\Installer\Adapter\ModuleAdapter.php:161
2 | Joomla\CMS\Installer\Adapter\ModuleAdapter->getElement() | JROOT\libraries\src\Installer\InstallerAdapter.php:339
3 | Joomla\CMS\Installer\InstallerAdapter->discover_install() | JROOT\libraries\src\Installer\Installer.php:633
4 | Joomla\CMS\Installer\Installer->discover_install() | JROOT\administrator\components\com_installer\models\discover.php:202
5 | InstallerModelDiscover->discover_install() | JROOT\administrator\components\com_installer\controllers\discover.php:46
6 | InstallerControllerDiscover->install() | JROOT\libraries\src\MVC\Controller\BaseController.php:710
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\administrator\components\com_installer\installer.php:19
8 | require_once() | JROOT\libraries\src\Component\ComponentHelper.php:402
9 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT\libraries\src\Component\ComponentHelper.php:377
10 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:101
11 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:159
12 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:203
13 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\index.php:51

</body>
</html>

### System information (as much as possible)

<html>
<body>
<legend style="display: block; width: 1479.2px; padding: 0px; margin-bottom: 18px; font-size: 19.5px; line-height: 36px; color: rgb(51, 51, 51); border-width: 0px 0px 1px; border-top-style: initial; border-right-style: initial; border-left-style: initial; border-top-color: initial; border-right-color: initial; border-left-color: initial; border-image: initial; border-bottom-style: solid; border-bottom-color: rgb(229, 229, 229); font-family: &quot;Helvetica Neue&quot;, Helvetica, Arial, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">System Information</legend>

Setting | Value
-- | --
 
PHP Built On | Windows NT DESKTOP-SAIL3J8 10.0 build 19041 (Windows 10) AMD64
Database Type | mysql
Database Version | 5.5.5-10.1.26-MariaDB
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.13
Web Server | Apache/2.4.41 (Win64) OpenSSL/1.1.1c PHP/7.3.13
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.9.26 Stable [ Amani ] 13-April-2021 15:00 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.72 Safari/537.36

</body>
</html>

**Comment by richard67** [comment]
@pranaymirchandani Which module did make these problems?

**Comment by PhilETaylor** [comment]
<img width="76" alt="Screenshot 2021-05-14 at 11 08 32" src="https://user-images.githubusercontent.com/400092/118255905-bb016880-b4a4-11eb-8e59-c5838498c166.png">
New profile pic - who dis?

**Comment by richard67** [comment]
> New profile pic - who dis?

@PhilETaylor Its 2 years older than the previous one, but closer to reality since I don't shave anymore.

**Comment by PhilETaylor** [comment]
Im guessing this file had an invalid XML with no files defined

https://github.com/joomla/joomla-cms/blob/08f0a31a849a52d0163a2262eac9a686af8996fd/libraries/src/Installer/Adapter/ModuleAdapter.php#L161

Please post the full XML file for the module here.

**Comment by PhilETaylor** [comment]
> Its 2 years older than the previous one, but closer to reality since I don't shave anymore.

I have to keep updating mine to make me look balder and fatter every 6 months ;-)

**Comment by pranaymirchandani** [comment]
> @pranaymirchandani Which module did make these problems?

Hi Richard, 

a custom module 


`<?xml version="1.0" encoding="utf-8"?>
<extention type="module" version="3.9" client="site" method="upgrade">
	<name>mod_mwprofile_search_filters</name>
	<files>
		<filename module="mod_mwprofile_search_filters">mod_mwprofile_search_filters.php</filename>
	</files>
</extention>`

Fixed it my bad this is where the problem was i misspelled extension as extention
<extension type="module" version="3.9" client="site" method="upgrade">
</extension>

**Comment by PhilETaylor** [comment]
same happens with that XML in Joomal4 

<img width="1597" alt="Screenshot 2021-05-14 at 11 20 47" src="https://user-images.githubusercontent.com/400092/118257389-7ecf0780-b4a6-11eb-8f45-439895106513.png">

**Comment by pranaymirchandani** [comment]
caused by a typo sorry

**Comment by PhilETaylor** [comment]
`extention` doesnt look right ;-)

**Comment by PhilETaylor** [comment]
This probably should still be resolved, also the admin template is destroyed by the error :-(
