### ISSUE TITLE
[4.0] Unused modal ?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33860]
Can anyone tell me where `administrator\components\com_fields\tmpl\field\modal.php` is used

**Comment by PhilETaylor** [comment]
Considering it looks like this I doubt its being used else someone (me, you, someone) would have stumbled upon it in the last year and cleaned it up

I can find no code that would generate this url. 

<img width="1147" alt="Screenshot 2021-05-14 at 11 18 14" src="https://user-images.githubusercontent.com/400092/118257121-2992f600-b4a6-11eb-86a1-3be2dd95b341.png">

**Comment by brianteeman** [comment]
Thought so - thanks for confirming

**Comment by brianteeman** [comment]
Closed see #33864
