### ISSUE TITLE
[4.0] Descriptions in parameters about nothing

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33875]
### Steps to reproduce the issue
Go to the parameters of each component. Please note that there are blocks with descriptions of parameters that are "about nothing". I suggest deleting them. Specifically here:

**Installer: Options**
**Joomla Update: Options**
**Module: Options**
**Smart Search: Options** : Smart Search
**Smart Search: Options** : Index
**Template: Options**
**Users: Options** : Mass Mail Users

No, they do not interfere. But at the moment in the parameters there are many where there is NO block of parameter descriptions. And in the above description extensions there is "just like that".

**Comment by PhilETaylor** [comment]
You mean these blue boxes?? Im confused.?

<img width="1598" alt="Screenshot 2021-05-14 at 19 14 14" src="https://user-images.githubusercontent.com/400092/118312015-9fb84c80-b4e8-11eb-8a03-2caf157a7ccb.png">
<img width="1596" alt="Screenshot 2021-05-14 at 19 13 47" src="https://user-images.githubusercontent.com/400092/118312016-a0e97980-b4e8-11eb-8e03-0d84b89d8408.png">

**Comment by Kostelano** [comment]
Exactly!

**Comment by brianteeman** [comment]
As explanation they were introduced some time ago because some fieldsets had them and it was felt that it "looked better" if they all had them

**Comment by Kostelano** [comment]
In such a case, we should add similar blocks to other parameters. Otherwise, out of sync.

But if on the tabs, for example, of articles, the hint literally helps us (especially for a beginner, information about a possible change in the menu), then on the indicated pages the hint does not provide any useful information.
