### ISSUE TITLE
[4.0] Tooltips and Tabstops in Articles list

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#33872]
### Steps to reproduce the issue

Have a look at the Articles list page and note the following:

1 The tooltips for the article title and category title differ from the actual title by the word **Edit**. Is this realy worth it - there are plenty of sources that imply not. The link title might be omitted. The author link does not have a title.
2. The Stage, Featured and Status icons show tooltips on hover but only the first has a tabstop that shows on focus. The other two are disabled so inacessible to keyboard users although they work onclick.
3. In the top menu bar only two of the four items show visible focus although all four have titles.

I am really looking for some documentation or guidelines on how or when to use titles and tooltips. And if none exist I am offering to compose something given guidelines by those who know.

### Expected result

Consistency and Accessibility

### Actual result

Chaos?

**Comment by brianteeman** [comment]
1. they should not be tooltips at all
3. Not sure which you refer to but multlingual status is wrong it is an a when it should be a button

**Comment by ceford** [comment]
On 1, what I meant was that the link title attribute differs from the link text by **Edit**. It could be just the word Edit or not there at all for all the help it is.

**Comment by brianteeman** [comment]
and I stand by the comment that they should not have been changed to a tooltip. there is zero point in it

**Comment by ceford** [comment]
I am referring to the titles before that wrong pr illustrated here:

![image](https://user-images.githubusercontent.com/1560390/118297274-d3d64200-b4d5-11eb-93ab-142bd263f469.png)

This shows a Tooltip (right or wrong) on the Stage icon and a title (browser displayed) on the article title. 

I just want to know where are our guidelines that tell developers what to use where.

**Comment by brianteeman** [comment]
I've already answered that
https://github.com/joomla/joomla-cms/pull/33865#issuecomment-841194914

**Comment by ceford** [comment]
Closing as I have learned enough to understand the issues.
