### ISSUE TITLE
[4.0] Content size inconsistent in Tooltip

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33876]
### Steps to reproduce the issue
Install demo data. Go to Control panel --- Content (Featured Articles). Please note that the size of the content in tooltips is different, see the screenshot (scale 1:1).

![Screenshot_1](https://user-images.githubusercontent.com/8440661/118309953-a3eb6680-b4f6-11eb-9b5a-96aa73158754.png)

**Comment by brianteeman** [comment]
Can not confirm

![image](https://user-images.githubusercontent.com/1296369/118334487-9f7a7a00-b505-11eb-939c-7290cded0f80.png)

![image](https://user-images.githubusercontent.com/1296369/118334550-bf11a280-b505-11eb-93b7-9637b32c1f47.png)

**Comment by Kostelano** [comment]
It is even visually visible that the font differs in size.

For some reason, the block pulls the styles of the `small` class with a font size of `.8rem`.

**Comment by infograf768** [comment]
Confirmed

Can't reproduce for Articles manager

![tipsize](https://user-images.githubusercontent.com/869724/118350990-b5b22580-b559-11eb-9197-70f8595463f1.gif)

Can reproduce for Featured Manager and difficulties to show tooltip

![tipsizefeatured](https://user-images.githubusercontent.com/869724/118351085-1fcaca80-b55a-11eb-830d-3d01b53cea62.gif)

**Comment by infograf768** [comment]
This is due to 
https://github.com/joomla/joomla-cms/blob/0290ae2e8029b112206577d8e98371a61ac8e687/administrator/components/com_content/tmpl/featured/default.php#L218

But taking off `small` does not solve the difficulty to display the tip on hover.

Comparing Articles manager and Featured Manager show important differences.

Featured Manager

```
<?php if ($workflow_enabled) : ?>
								<td class="article-stage">
									<div class="d-flex align-items-center tbody-icon small">
									<?php
									$options = [
										'transitions' => $transitions,
										'title' => Text::_($item->stage_title),
										'tip_content' => Text::sprintf('JWORKFLOW', Text::_($item->workflow_title)),
										'id' => 'workflow-' . $item->id
									];

									echo (new TransitionButton($options))
										->render(0, $i);
									?>
									</div>
								</td>
								<?php endif; ?>
```

Articles Manager

```
<?php if ($workflow_enabled) : ?>
								<td class="article-stage text-center">
								<?php
								$options = [
									'transitions' => $transitions,
									'title' => Text::_($item->stage_title),
									'tip_content' => Text::sprintf('JWORKFLOW', Text::_($item->workflow_title)),
									'id' => 'workflow-' . $item->id
								];

								echo (new TransitionButton($options))
									->render(0, $i);
								?>
								</td>
								<?php endif; ?>
```

I guess the solution (I tested) is replace the format in Featured Manager by the one used in  Articles Manager.

**Comment by brianteeman** [comment]
sorry it was late and I was testing articles not featured. 

I can submit a PR to fix it shortly if @infograf768 doesnt do it first. Its a simple fix

**Comment by infograf768** [comment]
Please do. Fix above is indeed simple.

**Comment by brianteeman** [comment]
Please test #33894

**Comment by alikon** [comment]
pr to test #33894
