### ISSUE TITLE
[4] Cannot preview article when site is offline

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33874]
### Steps to reproduce the issue

Set site offline in Joomla Global Config
Edit an article as admin user in /administrator/
Click Preview

### Expected result

Should be able to preview articles while the site is offline, without being logged into the frontend

### Actual result

Modal shows the site offline message and a login page

### System information (as much as possible)

Don't know how it used to be on Joomla 3, was it like this or different.

**Comment by brianteeman** [comment]
> Don't know how it used to be on Joomla 3, was it like this or different.

Preview did not exist

**Comment by richard67** [comment]
So we can close this because it's not an issue in J3, and in J4 it will be solved with #33879 ?

**Comment by PhilETaylor** [comment]
yup - thanks
