### ISSUE TITLE
Atum Joomla logo display issue on Firefox

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#33889]
### Steps to reproduce the issue

4.0.0-beta8-dev nightly 13.05.2021
Windows 10 - Firefox 88.0.1 (64 bits)

### Expected result

Same as Edge / Chrome

![image](https://user-images.githubusercontent.com/5349333/118331841-765be880-b509-11eb-8c2b-5507b1665fd7.png)

### Actual result

![image](https://user-images.githubusercontent.com/5349333/118331607-17966f00-b509-11eb-8bb9-27c2d3d2e55b.png)

**Comment by Kostelano** [comment]
Clear your browser cache, refresh the page.

**Comment by PhilETaylor** [comment]
@dgrammatiko is this because of something you have been doing with the sidebar?

**Comment by jsubri** [comment]
All, my bad.
I upgraded from 3.9 to 3.10 then 4.0, hit a browser cache.
closing
