### ISSUE TITLE
[4.0] Radio buttons in batch processing of menu items

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33890]
### Steps to reproduce the issue
Go to the menu items of any menu, select one item and click the Actions - Batch processing buttons. The radio buttons are broken.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/118333340-32baac00-b514-11eb-9dff-a88780ad6e95.png)

How this is implemented, for example, in batch processing of categories:

![Screenshot_2](https://user-images.githubusercontent.com/8440661/118333452-685f9500-b514-11eb-9388-13eebf895e36.png)

**Comment by Kostelano** [comment]
Fields - Batch: _To Move or Copy your selection please select a group (The author)_

![Screenshot_3](https://user-images.githubusercontent.com/8440661/118333665-c2f8f100-b514-11eb-8bef-996cb3737ed5.png)

**Comment by ghost** [comment]
Confirm both issue.

Fields also for articles-category, users and contacts (contact, mail, category).

**Comment by Kostelano** [comment]
PR https://github.com/joomla/joomla-cms/pull/33900.
