### ISSUE TITLE
[4.0] [Presets] Help & System Dashboards preset is not stylized

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33898]
### Steps to reproduce the issue
Go to the Admin Menu module (control panel), select the **Help Dashboard** preset in the settings and evaluate the main page of the control panel. The panel on the left has lost its styles.

I'm not sure if this should be so.

![Screenshot_3](https://user-images.githubusercontent.com/8440661/118355176-637ffd00-b577-11eb-8407-5665cb1defe7.png)

Then select the **System Dashboard** preset. The situation is similar.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/118355246-ab068900-b577-11eb-9768-527a29e00304.png)

These are the only presets that are not stylized.

**Comment by brianteeman** [comment]
The problem is not that it is unstyled. The problem is that left padding on the normal menu is coming from the icon which has a width of 1.25em and a margin of .85rem.

I have no idea how to resolve this but that is the explanation which hopefully will help someone

**Comment by Kostelano** [comment]
PR https://github.com/joomla/joomla-cms/pull/33923.
