### ISSUE TITLE
[4.0] Module: After status-change on admin-module screen switch to "Site"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#33891]
### Steps to reproduce the issue

Below you see:

1. User switch to `Administrator`,
2. Unpublish a admin-module,
3. Joomla automatic switch to `Site`,
4. User switch back to `Administrator`,
5. Publish module,
6. Joomla automatic switch to `Site`:

![1](https://user-images.githubusercontent.com/78906980/118348690-5a2d6b00-b54c-11eb-8c3a-03710e450e3f.gif)

### Expected result

Stay on screen after action on module.

### Actual result

Screen switch after action on module.

### System information (as much as possible)

> ![image](https://user-images.githubusercontent.com/78906980/118348807-04a58e00-b54d-11eb-81b7-4cfe20d27512.png)

### Additional comments

This don't happen using dropdown-fields for changing order, …

**Comment by joomdonation** [comment]
Thanks for reporting @sandramay0905. Guess it causes by my recent PR fixed other modules filter issue. PR https://github.com/joomla/joomla-cms/pull/33892 should address it. Please test.
