### ISSUE TITLE
[4.0] Links to restore menus are not stylized

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#33896]
### Steps to reproduce the issue
Go to the Menu Manager, select the control panel area - it will be empty there. Create a new menu, name it whatever you want. After saving the menu, add the module (on that page there is a link to create a module in the modal window), publish the module in the MENU position of the Atum template and set the Check Menu parameter value to YES.

A warning will appear in the control panel with a link to restore the menu. Click on it.

Links to restore the menu will appear on the left in the panel. These links differ in indentation and lack of icons.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/118354879-da1bfb00-b575-11eb-89d7-e0db20af53eb.png)

![Screenshot_2](https://user-images.githubusercontent.com/8440661/118354880-db4d2800-b575-11eb-9a85-e377ff75ac1f.png)

**Comment by PhilETaylor** [comment]
Nice to see people testing the edges of Joomla, the parts that most others dont test very often!

**Comment by brianteeman** [comment]
The problem is not that it is unstyled. The problem is that left padding on the normal menu is coming from the icon which has a width of 1.25em and a margin of .85rem.

I have no idea how to resolve this but that is the explanation which hopefully will help someone

**Comment by Kostelano** [comment]
PR https://github.com/joomla/joomla-cms/pull/33923, which corrects issue https://github.com/joomla/joomla-cms/issues/33898, also solves this problem, but with certain points. Pay attention to the screenshot - now we have an indent, which is different from the items with icons.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/118409240-13e22400-b692-11eb-8a1a-9c2f37261f5a.png)

Can we come up with icons for these items so as not to use the conditional indent from the new PR?

@eopws please take a look at this too if you have the time. Thank you.

**Comment by eopws** [comment]
> Can we come up with icons for these items so as not to use the conditional indent from the new PR?

If we add icons it would look well on Joomla Main menu preset.
On other hand on Help Dashboard preset (in which list items have no icons) it would have the same problem as you described.
Hard situation.
I propose to add indentations to my PR.
But if anyone has a better idea, please, tell it.

**Comment by eopws** [comment]
> PR #33923, which corrects issue #33898, also solves this problem, but with certain points. Pay attention to the screenshot - now we have an indent, which is different from the items with icons.

Fixed.

**Comment by Kostelano** [comment]
PR https://github.com/joomla/joomla-cms/pull/33923.
