### ISSUE TITLE
[4] ToolbarHelper::editList doesn't check if multiple items are selected

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33905]
### Steps to reproduce the issue

This is a pure PHP issue, that doesn't effect Joomla core, but Joomla core provides and exposes this API for others to use.

A developer can add an edit button on a List view to allow editing of items. [In fact the default `addToolbar` method in the `MVC` layer of Joomla also provides this edit button ](https://github.com/joomla/joomla-cms/blob/b12c4c669dddcf050fb274e39818ab54754d475c/libraries/src/MVC/View/ListView.php#L232)

You can replicate this by adding `ToolbarHelper::editList('article.edit');` to the Articles `HtmlView.php` toolbar and then checking all your articles and then clicking edit.

### Expected result

When using `ToolbarHelper::editList('article.edit');` API, the page checks with javascript how many items are checked, before submitting the form. 

The expected behaviour is like this (in the versions modal)

https://user-images.githubusercontent.com/400092/118362670-5fa8a680-b588-11eb-8352-ebe309a0e0bd.mp4

If more than one item is checked, then you are told to only select one item to edit

### Actual result

No validation of the checkboxes number checked, and form submits and the edit page of the first item checked is loaded. 

https://user-images.githubusercontent.com/400092/118362640-31c36200-b588-11eb-829a-80f2b07ba740.mp4

**Comment by eopws** [comment]
> When using `ToolbarHelper::editList('article.edit');` API, the page checks with javascript how many items are checked, before submitting the form.

Maybe it's better to make the button disabled when more than one checkbox checked?

**Comment by chmst** [comment]
This was already 2008 when I made my first Joomla installation. Nobody had a problem with that until now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33905">issues.joomla.org/tracker/joomla-cms/33905</a>.</sub>

**Comment by brianteeman** [comment]
Actually I've always had a problem with it and its been reported several times but always rejected

**Comment by PhilETaylor** [comment]
>  reported several times but always rejected

I dont know why - it is clearly wrong and should be fixed. However now that Joomla 4 no longer has any edit buttons, it might be just as easy to deprecate the edit toolbar completely instead.

**Comment by joeforjoomla** [comment]
The edit button for an items list is used widely by extensions developers, but the behavior has always been almost the same on J3. The only difference is that J4 does not enable the edit button when the check all checkbox is clicked, but only when single items are selected one by one. Then the first item is edited. Probably it would be the time to make this behavior consistent in J4, for example introducing a JS validation... i guess that the best option would be to prevent the form to submit if there are multiple items selected.

**Comment by PhilETaylor** [comment]
Probably a quick easy fix in JS for @dgrammatiko :)

**Comment by dgrammatiko** [comment]
> Probably a quick easy fix in JS for @dgrammatiko :)

I'll call @Fedik for this one :)
