### ISSUE TITLE
[4.0] components dashboard multilingual associations

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#33903]
In #33815 @joomdonation hid the multilingual associations from the components menu if the site is not multilingual. However it is still present on the components dashboard

**Comment by joomdonation** [comment]
@brianteeman Could you let me know where I can see it? I think we need to make similar change to https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/modules/mod_submenu/src/Menu/Menu.php#L103 but I don't see where it is displayed. If you see it and could me that PR, that would be great.

**Comment by richard67** [comment]
@joomdonation See here:

![2021-05-15_1](https://user-images.githubusercontent.com/7413183/118358491-4fd89480-b57f-11eb-8728-adfd813f9e1a.png)

**Comment by brianteeman** [comment]
Beat me to it.

**Comment by joomdonation** [comment]
Thanks, see it now. Maybe @brianteeman could help. If not , I will do that later (a bit busy with my own work at the moment).

**Comment by brianteeman** [comment]
I would have done it myself but I couldnt work out where that was being generated. Its not urgent

**Comment by joomdonation** [comment]
OK. I thought I mentioned about where we could put the code to solve the issue at https://github.com/joomla/joomla-cms/issues/33903#issuecomment-841641420 . I made the https://github.com/joomla/joomla-cms/pull/33904 , it should solve the issue. Thanks for reporting (I still don't know all the Joomla! features yet :( )

**Comment by brianteeman** [comment]
I understand what code is needed. I just couldnt find out where to put it ;)

**Comment by joomdonation** [comment]
I mentioned that it should be put here https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/modules/mod_submenu/src/Menu/Menu.php#L103 in my earlier comment :)
