### ISSUE TITLE
[4.0] Suggestion to hide the empty div when no results match the Add Module search

### ISSUE THREAD

**Issue by YatharthVyas** [joomla/joomla-cms#33912]
### What needs to be fixed

Visit Backend -> Site Modules (or Admin Modules) -> Add New Module -> Enter a search query which doesn't match any result
Along with the 'No match found' alert, an empty card div is also displayed
Also, this can also be encountered by clicking on 'Add a module to the dashboard' modal button for the admin home dashboard.

![image](https://user-images.githubusercontent.com/53610833/118386706-08154400-b637-11eb-9cc6-da1816cb7397.png)

### Why this should be fixed

For consistency
If you observe the searchtools page for modules (or anything similar), it only shows a message when no modules match your query and no empty table

![image](https://user-images.githubusercontent.com/53610833/118386797-91c51180-b637-11eb-97e4-ce3d2f256fa6.png)

### How would you fix it

The search works based on a JavaScript function in [this file](https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/com_modules/js/admin-module-search.es6.js).
Maybe a boolean could be used to track whether any matches exists or not and that could be used as a condition to toggle the hidden class.

![image](https://user-images.githubusercontent.com/53610833/118386924-7d354900-b638-11eb-9ff2-ff099e2b4ed1.png)

### Side Effects expected
I think none

**Comment by himanshu007-creator** [comment]
@YatharthVyas i think this will be good!

**Comment by chmst** [comment]
Good for me

**Comment by YatharthVyas** [comment]
Closing in favor of PR #33919
