### ISSUE TITLE
Event Issues in com_modules

### ISSUE THREAD

**Issue by h2974** [joomla/joomla-cms#33914]
In my plugin the onContentPrepareForm event does not identify com_modules.modules.filter and 
the onContentPrepareData event does trigger for context com_modules.modules any more.

**Comment by joomdonation** [comment]
@h2974 Could you please explain more details about the problem you are having? Recently, we appends Client ID to context to fix filter issues when Client is switched from Admin to Site and vice versa. The PR is here https://github.com/joomla/joomla-cms/pull/33763

Maybe that change causes issue with your plugin (in case you set model states via com_modules.modules.filter key)

**Comment by h2974** [comment]
For example: I am using 

`if ($context === 'com_modules.modules')` in event `onContentPrepareData`

of my plugin that should only run in modules list. This does not work any more.

According the documentation this should work: https://docs.joomla.org/Plugin/Events/Content#onContentPrepareData

**Comment by joomdonation** [comment]
Could you please give us more information? What is the purpose if the plugin? If it is possible, please attach your plugin here so that we can review to see if it causes by some changes we made into Modules Management recently. Thanks

**Comment by richard67** [comment]
Information required, see previous comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33914">issues.joomla.org/tracker/joomla-cms/33914</a>.</sub>

**Comment by Quy** [comment]
Closing due to no response with requested information.
