### ISSUE TITLE
[4.0] Possible Bug with ordering value in ArticlesModel query

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#33936]
### Steps to reproduce the issue
I haven't had time to look at it yet but in ArticlesModel, we have two ordering fields in the query without using Alias, and it could cause wrong ordering value returned, thus causes error with Drag and Drop ordering in Articles management

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/src/Model/ArticlesModel.php#L255
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_content/src/Model/ArticlesModel.php#L276

If someone could figure out why we need that ordering data (especially from #__content_frontpage table), that would be great.

**Comment by dgrammatiko** [comment]
> If someone could figure out why we need that ordering data (especially from #__content_frontpage table)

Isn't this the messy `featured items`?

**Comment by joomdonation** [comment]
> Isn't this the messy featured items?

I haven't had a chance to read the code myself carefully yet. However, because of this bug, the wrong ordering value for each article will be used on articles view, mean re-ordering articles in article management won't work properly. (I found this issue why trying to test the PR https://github.com/joomla/joomla-cms/pull/33937 )

**Comment by richard67** [comment]
> > If someone could figure out why we need that ordering data (especially from #__content_frontpage table)
> 
> Isn't this the messy `featured items`?

@dgrammatiko Yes, `#__content_frontpage` is the table for that messy thing .. the table of which I wish it never had been created. The columns could have been added to the content table. This would maybe waste a few kilobytes space on a big table where the columns would be used only for a few % of all data, but it would have saved us from so much trouble. Well, all I can say is .. it wasn't me 😄

**Comment by joomdonation** [comment]
I don't understand why we need an extra table `#__content_frontpage` like this. But I guess it is too late for us to do the removal, so I made PR https://github.com/joomla/joomla-cms/pull/34025 to fix this issue for now.
