### ISSUE TITLE
[4.0] External link in installation message (a11y)

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#33931]
### Steps to reproduce the issue
Install a new joomla on a webspace with servername "localhost". The message contains an external link and the "external link" icon should be added

![grafik](https://user-images.githubusercontent.com/1035262/118539205-6e8d8580-b74f-11eb-8891-5c5a10b08d71.png)

**Comment by brianteeman** [comment]
The external link icon is only applied to _blank links

**Comment by richard67** [comment]
@chmst Your description is wrong.

You wrote:

> Install a new joomla on a webspace with servername "localhost".

But to get that message it should be:

> Install a new joomla on a webspace with servername _**not**_ equal to "localhost" or "127.0.01" or "::1".

**Comment by chmst** [comment]
I don't understand? 
I installed in my webspace and entered servername = 127.0.01 and got the message.

**Comment by richard67** [comment]
The check is here: https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/src/Helper/DatabaseHelper.php#L381

The PR which added it back in J4 is here: https://github.com/joomla/joomla-cms/pull/27360

No idea why you see that message if you had used "localhost" or "127.0.0.1".

**Comment by richard67** [comment]
But normally on a webspace from a provider, the database server is not localhost or 127.0.0.1.

**Comment by richard67** [comment]
Maybe you mix up the webserver name and the database server name?

**Comment by richard67** [comment]
The database server name entered in the installation form is relevant for this check, not the webserver's host name.

**Comment by chmst** [comment]
Hosting is not my field of experience ;) As a user I can enter only one servername during installation - it is the name of the database server. 
127.0.01 is always an option - but probably depends on the server configuration.
The issue was the link in the message, and it is resolved with #33933.

**Comment by richard67** [comment]
Closing as having a pull request.
