### ISSUE TITLE
[4.0] Narrow column width in list view of media manager

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#33943]
### Steps to reproduce the issue
Go to Content > Media
Click List icon.
Go to sampledata > parks > landscape

### Actual result
![mm-list](https://user-images.githubusercontent.com/368084/118663967-f3a38980-b7a5-11eb-8cf7-0cd4675951d4.jpg)

**Comment by eopws** [comment]
Please, test PR #33945

**Comment by chmst** [comment]
Closing as there is a PR
