### ISSUE TITLE
[4] setBuffer called incorrectly in /libraries/src/Cache/Cache.php

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#33966]
### Steps to reproduce the issue

https://github.com/joomla/joomla-cms/blob/418de6eba4319e8e32dde4a3342203a6d8e249be/libraries/src/Cache/Cache.php#L564

This block of code is using 

```php
$document->setBuffer($contents, 'module', $name);
```

whereas the `setBuffer` method signature is:

```php
/**
	 * Set the contents of the document buffer
	 *
	 * @param   string  $content  The content to be set in the buffer.
	 * @param   array   $options  Array of optional elements.
	 *
	 * @return  Document instance of $this to allow chaining
	 *
	 * @since   1.7.0
	 */
	public function setBuffer($content, $options = array())
	{
		self::$_buffer = $content;

		return $this;
	}
```

### Expected result

methods called correctly

### Actual result

this code probably doesn't work at all.

**Comment by Fedik** [comment]
> this code probably doesn't work at all.

This  works, there is fallback code in `DocumentHTML`  https://github.com/joomla/joomla-cms/blob/953818438a60087536ec913a7a11dcd8c4c7ad17/libraries/src/Document/HtmlDocument.php#L603-L618

But better update that part of course.

**Comment by PhilETaylor** [comment]
well nothing to fix - just a strange way to approach b/c :)
