### ISSUE TITLE
Class not found for 'Edit account' and 'Accessibility settings'

### ISSUE THREAD

**Issue by Kurantje** [joomla/joomla-cms#34026]
### Steps to reproduce the issue
Login to the backend
Click top right 'user menu'
Click 'Edit Account' or 'Accessibility Settings'

### result
An error has occurred.
0 Class 'Joomla\Component\Admin\Administrator\Service\HTML\Directory' not found

### System information (as much as possible)
Fresh install of 4.0.0-beta7

**Comment by ghost** [comment]
Cannot confirm the issue. Can you please update using the latest [Nightly Build](https://developer.joomla.org/nightly-builds.html) and try again?

**Comment by rjharishabh** [comment]
Cannot confirm

**Comment by Kurantje** [comment]
@sandramay0905: problem not appearing in latest nightly build version: Joomla! 4.0.0-beta8-dev Development [ Mañana ] 2-February-2021 20:02 GMT<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34026">issues.joomla.org/tracker/joomla-cms/34026</a>.</sub>

**Comment by ghost** [comment]
> problem not appearing in latest nightly build

Thanks for confirming, please close the issue.

**Comment by joomdonation** [comment]
Closing because the issue is invalid for nightly build.
