### ISSUE TITLE
[4.0] Radio button (switcher) functionality

### ISSUE THREAD

**Issue by rjharishabh** [joomla/joomla-cms#34047]
### Steps to reproduce the issue
Any radio button that has a switcher class
![switch](https://user-images.githubusercontent.com/61203226/119015764-db568900-b9b6-11eb-9aef-a2ad49ba29ec.JPG)

### Expected result
When we click `No` label, the button will be checked and the label changed to Yes,
as well as when we click `Yes` label, the button will be off, and the label changed to No

### Actual result
When we click `No` label, the button will be checked, and label changed to Yes,
but when we click `Yes` label, nothing will be changed.

![switcher](https://user-images.githubusercontent.com/61203226/119015850-f0cbb300-b9b6-11eb-8fd4-bf5ea208edb4.gif)

**Comment by brianteeman** [comment]
> Please think like a user, not a developer

Think like a developer and you would see that its a bug

> Maybe there some a11y issue, I don't know

Dont blame a11y for everything. This bug actually breaks accessibility

**Comment by rjharishabh** [comment]
> > Please think like a user, not a developer
> 
> Think like a developer and you would see that its a bug
> 
> > Maybe there some a11y issue, I don't know
> 
> Dont blame a11y for everything. This bug actually breaks accessibility

I don't know, whether this is a bug or not (As a  developer). Maybe there some reasons for doing this way.

But as a user, I will definitely consider it as a bug

**Comment by brianteeman** [comment]
# It's a BUG

**Comment by brianteeman** [comment]
To be absolutely clear - clicking on any of the labels should change the state

**Comment by eopws** [comment]
The radio button is made in a weird way itself.

![img](https://user-images.githubusercontent.com/42320170/119023357-6da46000-b9aa-11eb-9ca0-5c2a20a0fb82.png)

It uses two inputs (what for?) and two labels. I suppose it happens because of the "No" label overlaps the "Yes" label.
I think it's better to remake a radio button at all.

**Comment by brianteeman** [comment]
> It uses two inputs (what for?) and two labels.

How else do you have two radio

> I suppose it happens because of the "No" label overlaps the "Yes" label.
I think it's better to remake a radio button at all.

Please dont

**Comment by eopws** [comment]
> Please dont

Ok, I will try to search another ways to solve the issue =)

**Comment by eopws** [comment]
> It uses two inputs (what for?) and two labels. I suppose it happens because of the "No" label overlaps the "Yes" label.
> I think it's better to remake a radio button at all.

Oops, I got my error, for some reason I was thinking that the radio button is a checkbox button. I feel so ashamed.
I gotta be more careful. Please never mind..

**Comment by dgrammatiko** [comment]
> How else do you have two radio

With a single button. Button can have a boolean value (0/1, true,false, etc) and also is better for A11Y with aria-pressed, eg
```html
<button type="button" aria-pressed="true">  
  Notify by email
</button>  
```

There's a nice explanation: https://www.smashingmagazine.com/2017/09/building-inclusive-toggle-buttons/

or you can check my dark theme swither live: https://codepen.io/dgrammatiko/pen/bGNXVQQ?editors=1010
repo: https://github.com/dgrammatiko/dark-switch

**Comment by brianteeman** [comment]
but then thats not b/c in any way and forces changes that are not required on everyone.

anyway the issue here is that it used to work correctly and now it doesnt

**Comment by dgrammatiko** [comment]
@brianteeman my response was purely educational and I was responding to the gsoc student. I'm not suggesting such a change at this point of j4...

My bad: I quoted the wrong text in my reply

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34085 . Thanks in advance.

**Comment by eopws** [comment]
> ![image](https://user-images.githubusercontent.com/42320170/119182169-3f428580-ba7b-11eb-98b0-63fc07bee584.png)


@rjharishabh can you please tell how did you make the gif?

**Comment by rjharishabh** [comment]
> @rjharishabh can you please tell how did you make the gif?

@eopws I just convert mp4 to gif online

**Comment by brianteeman** [comment]
> @rjharishabh can you please tell how did you make the gif?

Use licecap - it is free and available for all operating systems

**Comment by eopws** [comment]
@rjharishabh @brianteeman, thanks
