### ISSUE TITLE
[4.0] Preview of Cassiopeia: Position "Debug" miss background colour

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34041]
### What needs to be fixed
In `Templates: Styles (Site)` select `Preview` (enable it in template-options):

![image](https://user-images.githubusercontent.com/78906980/118975215-11264e00-b974-11eb-8a6b-766099a2eabe.png)

### Why this should be fixed
User can read position and style.

### How would you fix it
Background colour behind text like in other positions.

### Side Effects expected
Don't know.

**Comment by himanshu007-creator** [comment]
@sandramay0905 , can you please check again? i am unable to reproduce this issue. Followed all steps, in my machine it displayed as expected.

**Comment by brianteeman** [comment]
I can't replicate it either. What module is it?

**Comment by ghost** [comment]
I can't replicate it either too on a fresh installation, so closing and thanks for your comments.
