### ISSUE TITLE
Modules Menu Assignment Tab messed up

### ISSUE THREAD

**Issue by mdigerat** [joomla/joomla-cms#34056]
### Steps to reproduce the issue
Short description of problem: Starting with Main Menu being messed up all other page selections below this are seriously out of sorts on prime, as seen in Fig.1 HFU Test is fine as shown in Fig.2.[HFU-PrimeMenuAssignmentTab.pdf](https://issues.joomla.org/uploads/1/91e0b6406ddcb3ea739975218d5891fe.pdf)
1. create new module and assign to page(s)

### Expected result
2. for the module to be created and have menu assignment tab be orderly

### Actual result
3. menu assignment tab is all messed up; please refer to attache root cause analysis.

### System information (as much as possible)
uploaded .txt file for system info[systeminfo-2021-05-20T17_58_40+00_00.txt](https://issues.joomla.org/uploads/1/84e38f3c74992a59f0c4fa5890b1fb4a.txt)

**Comment by brianteeman** [comment]
the plugin referred to in your analysis is not a core plugin

**Comment by alikon** [comment]
please ask support to the plugin developer

**Comment by mdigerat** [comment]
I am confused;
The menu assignment tab within any/all modules is not core functionality?
So if I install 'core' joomla there will be no menu assignment tab as in
attached graphics?
No wonder our clients are migrating to other platforms.
Thanks
Kel

Regards -
*Kelley David Cole - *
*<mobile> 609.471.9213*
*<eMail> ***@***.***> | <LinkedIn>
<http://www.linkedin.com/pub/kelley-david-cole/2/212/639/> | <Beyond>
<http://www.beyond.com/Kelley-Cole-NJ?preview=1> | <Google+>
<https://plus.google.com/+KelleyCole> | <Twitter>
<https://twitter.com/KelleyDavidCole>*

**Comment by mdigerat** [comment]
On this page on your site it states where to assign module(s) to pages -
this is what we are experiencing our trouble with.

https://docs.joomla.org/How_do_you_assign_a_module_to_specific_pages%3F

Thanks
Kel
Regards -
*Kelley David Cole - *
*<mobile> 609.471.9213*
*<eMail> ***@***.***> | <LinkedIn>
<http://www.linkedin.com/pub/kelley-david-cole/2/212/639/> | <Beyond>
<http://www.beyond.com/Kelley-Cole-NJ?preview=1> | <Google+>
<https://plus.google.com/+KelleyCole> | <Twitter>
<https://twitter.com/KelleyDavidCole>*

**Comment by brianteeman** [comment]
The problem is that you posted a report that stated a problem with a plugin. 

That may be a red herring. I dont know I dont have that plugin.

The two times I have seen the menu assignment page being messed up like that (on my own personal site) was once when a plugin did something (but I forget what) and was resolved by removing the plugin. The second time was down to the lft/rgt values in the database for the menu being "messed up" somehow and was resolved by going to the menu manager and clicking on rebuild

**Comment by mdigerat** [comment]
Ok, I'll check it out.
Apologies for any confusion.
I have Parkinson's and explaining myself or making proper selections
sometimes difficult at best.
No new plugins recently.
Will look into dB.
We did a site refresh by an outside contractor that had not used joomla.
Did things in megamenu that should have been run through my team first.
Thanks again.
Regards -
*Kelley David Cole - *
*<mobile> 609.471.9213*
*<eMail> ***@***.***> | <LinkedIn>
<http://www.linkedin.com/pub/kelley-david-cole/2/212/639/> | <Beyond>
<http://www.beyond.com/Kelley-Cole-NJ?preview=1> | <Google+>
<https://plus.google.com/+KelleyCole> | <Twitter>
<https://twitter.com/KelleyDavidCole>*
