### ISSUE TITLE
[4.0] Set default language [a11y] [ui]

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34083]
### Steps to reproduce the issue
Install joomla and at least one additional language
When you have completed and got the Congratulations message you are asked to set a default language

### Expected result
Accessible information, can be navigated with keyboard and screen reader, clearly labelled etc

### Actual result
A table with no caption so you do not know what the table is for. (the text you can see is a paragraph outside of the table and may not be announced depending on screen reader mode).

This is not a table. It is a form with  two fieldsets each with three possible options and it is coded as a table for layout purposes only and we all should know that you dont do that

It is also confusing because the button at the top will take you to a new page to Install Additional Languages but the button at the bottom which is visually identical is the submit for the form

![image](https://user-images.githubusercontent.com/1296369/119173403-2330eb00-ba5f-11eb-8997-50593b9f4d11.png)

**Comment by Milo-W** [comment]
I have this problem that I choose the default language, the user has both languages "default language" setting... and yet, it's not the one that's default. I think I saw this bug earlier, even in Joomla 3 but automatically went to change the user's language to proper one.
However, now, in J4, it bugs me more and I won't change users' languages, I want to leave them "default" but the default setting can't be set really. It ignores it and switches to English.
Is it really a bug or what?

**Comment by chmst** [comment]
First I must understand your problem. I think that it is not related to this issue.

You install several languages, let's say English, French and German.
Then you set German as default for the backend and French as default for the frontend. 

What is wrong now for the user? Could you please post a few screenshots?

**Comment by Milo-W** [comment]
And now user has "default"
and when he/she logs in - both languages are English, not the default for the page (like in your example).

**Comment by infograf768** [comment]
All depends on the parameters set in the Users Options.

<img width="535" alt="Screen Shot 2021-11-06 at 11 12 36" src="https://user-images.githubusercontent.com/869724/140606016-84479b89-03d6-45ca-9bd0-b463250595f4.png">

If Frontend Language is set to Yes, when the user is creating the account, the language has to be selected. Default is NOT a choice.

Frontend
<img width="1053" alt="Screen Shot 2021-11-06 at 11 01 03" src="https://user-images.githubusercontent.com/869724/140605757-67f28556-f339-4146-b5f1-96d0aeb27abd.png">

If set to No, the user will automatically get the site default language.

In the backend, the choice is always possible.
<img width="855" alt="Screen Shot 2021-11-06 at 11 03 28" src="https://user-images.githubusercontent.com/869724/140605775-7699945b-7496-4db7-9a63-a84aa5b38139.png">

**Comment by infograf768** [comment]
Note: @Milo-W this question is unrelated to the original post... Please use the forum.
