### ISSUE TITLE
[4.0] Category Blog menu item type parameters layout

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#34081]
### Steps to reproduce the issue
Create a menu item to link to **Category Blog** menu item type, look at **Blog Layout** tab to change menu item parameters.

### Expected result
The layout looks good.

### Actual result
The layout looks mess. See this attached image
![category-blog-menu-option](https://user-images.githubusercontent.com/977664/119166544-f4c80580-ba88-11eb-9080-da6c966afff2.png)

### System information (as much as possible)
Joomla 4 nightly build

### Additional comments
Could one of our contributors with frontend take a look at this and make sure it is sorted before RC release?

**Comment by chmst** [comment]
see also #33480 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34081">issues.joomla.org/tracker/joomla-cms/34081</a>.</sub>

**Comment by eopws** [comment]
Is it ok to wrap the fields to another line when not having enough container width?

Or something else?

**Comment by chmst** [comment]
@eopws I think that this is ok. 

My impression is, that the problem happens with an odd number of elements.

**Comment by eopws** [comment]
@chmst

> My impression is, that the problem happens with an odd number of elements.

Actually no. It happens when the elements are too big. Count of elements doesn't matter

![odd](https://user-images.githubusercontent.com/42320170/119233958-087c7600-bb34-11eb-8ef1-bfcda3d03541.png)
![even](https://user-images.githubusercontent.com/42320170/119233960-09ada300-bb34-11eb-878b-ef7c25e51a63.png)

Or I didn't understand you right

**Comment by eopws** [comment]
What about addin' a horizontal scrollbar?

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34145 . Thanks in advance.
