### ISSUE TITLE
[4.0] Install Additional Language

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34082]
### Steps to reproduce the issue
Install Joomla and an additional language

When you get the Congratulations message there is another button to Install additional languages
Select that

### Expected result
Table displayed as before without error

### Actual result
Notice: Undefined offset: 1 in C:\htdocs\joomla-cms\installation\tmpl\remove\default.php on line 240

**Comment by chmst** [comment]
I cannot replicate that in my localhost win10, xampp, php7.4. 
I tested with German as first, then after the  congratulation message with Macedonian, Albanian (both not available), French and Persian. 
What is your environment?

**Comment by Fedik** [comment]
That may happen when preg_match fail to find something
https://github.com/joomla/joomla-cms/blob/7b98bbb97802da10ce35b97353021494e7e79047/installation/tmpl/remove/default.php#L238-L241

Did you got it on any specific language, or always?

**Comment by brianteeman** [comment]
weird - i dont get it now
