### ISSUE TITLE
[4.0] Lack of documentation in showon.js

### ISSUE THREAD

**Issue by eopws** [joomla/joomla-cms#34084]
# The problem
A method in showon.js file has empty documentation comment.
I think that the comment should have a description of what the method does

https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/showon.es6.js#L114-L117

**Comment by dgrammatiko** [comment]
At line 101 there is a comment `// Initialise`  https://github.com/joomla/joomla-cms/blob/24830a9157c829b79bfb0554d4583786fc532321/build/media_source/system/js/showon.es6.js#L101

So what `linkedOptions(key)` is doing is `initialize the showon behaviour for the given HTMLElement `

**Comment by eopws** [comment]
> So what linkedOptions(key) is doing is initialize the showon behaviour for the given HTMLElement

Yes, but I think that the comment https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/showon.es6.js#L114-L117 should have that info too.

> At line 101 there is a comment // Initialise

Don't you think that the comment is too small and creates ambiguity (initialise what?).

**Comment by brianteeman** [comment]
see #34680

**Comment by alikon** [comment]
please test #34680
