### ISSUE TITLE
[4] Admin header issues still on mobile.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34105]
### Steps to reproduce the issue

Paging @dgrammatiko (sorry) seems the latest round of JS/CSS fixes broke mobile things. 

I hope this is not a release candidate blocker... 

Several bugs on mobile - Safari on iPhone 12 Real life phone not a simulator.

1) On some pages the header doesnt collapse the logo until scrolled
2) On a list page (Articles) the toolbar is visible on first page load, and when pressing the top right corner (COGS) flashes to open state again, until a second press of the cogs closes the toolbar
3) on an edit page (Edit Article) the toolbar shows on page load, and hides on scroll 
3) on an edit page (Edit Article) the brand logo is large until scroll

https://user-images.githubusercontent.com/400092/119233236-f55fab00-bb1f-11eb-8072-c20834d8ded0.mov

**Comment by dgrammatiko** [comment]
I'm aware and had a PR already opened https://github.com/joomla/joomla-cms/pull/33877 but there are still cases that aren't solved. I will spend some time later on to see if a more solid approach is fissible

**Comment by dgrammatiko** [comment]
@PhilETaylor can you give #33877 a spin. I think I got it right this time

**Comment by PhilETaylor** [comment]
Closing as https://github.com/joomla/joomla-cms/pull/33877 fixes all my reported issues.
