### ISSUE TITLE
[4] Media manager doesnt show previews for JPEG extensions, but does for JPG

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34107]
### Steps to reproduce the issue

upload two images, one with a jpg extension and one with a jpeg extension

### Expected result

expect to see preview of both. 

### Actual result

<img width="1301" alt="Screenshot 2021-05-22 at 17 18 41" src="https://user-images.githubusercontent.com/400092/119233597-c6e2cf80-bb21-11eb-8d73-199c80910182.png">

### System information (as much as possible)

safari on mac
safari on iPhone 12

**Comment by brianteeman** [comment]
Confirmed. ~PR coming~

**Comment by brianteeman** [comment]
Correction - not what I thought. No idea why its not being recognised as image file for displaying a thumbnail. It is being recognised as an image for displaying a preview (that works)

**Comment by PhilETaylor** [comment]
Linked to this - its impossible to EDIT the JPEG extension image too - the icon is missing.


https://user-images.githubusercontent.com/400092/119237321-1f22cd00-bb34-11eb-951b-cfd9a7b66bcc.mp4

**Comment by brianteeman** [comment]
Could it be the code that is getting the etxension is only get three characters

**Comment by dgrammatiko** [comment]
> Could it be the code that is getting the etxension is only get three characters

Nope, go to the com_media options and add `jpeg` in the legal image extensions
<img width="1007" alt="Screenshot 2021-05-22 at 22 13 01" src="https://user-images.githubusercontent.com/3889375/119239693-040f8780-bb4b-11eb-88d0-8460067b3a0a.png">


Probably also webp and avif

**Comment by brianteeman** [comment]
webp has a pr sitting there for ages. 
avif has support issues

pr for jpeg #34113

**Comment by richard67** [comment]
Closing as having a pull request.
