### ISSUE TITLE
[4] search box on mobile larger than search icon

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34106]
### Steps to reproduce the issue

safari on iPhone 12

<img width="894" alt="Screenshot 2021-05-22 at 17 08 31" src="https://user-images.githubusercontent.com/400092/119233323-58e9d880-bb20-11eb-85bd-968fe866233e.png">

**Comment by PhilETaylor** [comment]
same on login page

<img width="835" alt="Screenshot 2021-05-22 at 17 10 20" src="https://user-images.githubusercontent.com/400092/119233375-9f3f3780-bb20-11eb-9f2f-f046cf7cb59a.png">

**Comment by PhilETaylor** [comment]
same on edit user - looks like any field with the split input and icon...

<img width="857" alt="Screenshot 2021-05-22 at 17 13 48" src="https://user-images.githubusercontent.com/400092/119233467-1ecd0680-bb21-11eb-8668-ad13d6a35324.png">

**Comment by brianteeman** [comment]
Are you sure you're upto date - I already fixed that https://github.com/joomla/joomla-cms/pull/33928

**Comment by PhilETaylor** [comment]
Yup up to date 4.0-dev

![image](https://user-images.githubusercontent.com/400092/119235492-b6832280-bb2a-11eb-93b8-70e1b0925cd8.png)

**Comment by himanshu007-creator** [comment]
Confirmed the issue on Chrome Beta (android 11) By fork is up-to-date .

**Comment by brianteeman** [comment]
Chrome emulator for mobile shows this correctly. No idea then. Cache?

**Comment by PhilETaylor** [comment]
Totally brand new iPhone bought yesterday - no cache

**Comment by PhilETaylor** [comment]
Just downloaded chrome for first time on this phone![image](https://user-images.githubusercontent.com/400092/119235939-bc7a0300-bb2c-11eb-87a2-e645f1714d6d.png)

**Comment by brianteeman** [comment]
as I can only use the emulator I have no idea. it's working perfectly there

**Comment by infograf768** [comment]
Searchbox and password confirmed issue on Firefox.

Problem with 
```
.btn {
    margin-bottom: 0.25rem;
}
```
![searchbox_mobile](https://user-images.githubusercontent.com/869724/119236042-8db45a80-bb35-11eb-9020-159180b87e78.gif)

**Comment by infograf768** [comment]
i.e. in  _buttons.scss
```
.btn {
  transition: none;

  @include media-breakpoint-down(sm) {
    margin-bottom: .25rem;
  }
}

```

**Comment by brianteeman** [comment]
SORRY I AM AN IDIOT

the PR I referred to is for cassiopeia and I was testing just now with the site login.

Same fix needs to be applied to atum

**Comment by brianteeman** [comment]
please test #34112

**Comment by richard67** [comment]
Closing as having a pull request. Please test.
