### ISSUE TITLE
[4] Mobile Login Page Flow

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34104]
### Steps to reproduce the issue

/administrator/ on mobile

### Expected result

"I want to login, I dont want support in my face first. I want a login box"

### Actual result

![Joomla4 - Administration](https://user-images.githubusercontent.com/400092/119233014-f3e1b300-bb1e-11eb-99c2-ea0cb07fb97a.png)

### System information (as much as possible)

safari on iPhone 12

**Comment by brianteeman** [comment]
WTF - this was fixed

**Comment by PhilETaylor** [comment]
If I had to guess I would say that in trying to fix the error states this was broken. There was a flow issue on one of the error states that put the menu on the right hand side of the screen.. 

@ciar4n  ?

**Comment by PhilETaylor** [comment]
this? https://github.com/joomla/joomla-cms/pull/33803/files

**Comment by brianteeman** [comment]
Should be closed as there is a PR
