### ISSUE TITLE
[4] enabling accessibility help leads to toolbar items being mismatched sizes 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34109]
### Steps to reproduce the issue

https://user-images.githubusercontent.com/400092/119236313-a40ae800-bb2e-11eb-912b-7c3324458508.mp4

### Expected result

equal height items

### Actual result

User Menu item not larger like the others

<img width="711" alt="Screenshot 2021-05-22 at 18 51 23" src="https://user-images.githubusercontent.com/400092/119236335-c13fb680-bb2e-11eb-9ab9-da9c0250f5d8.png">

### System information (as much as possible)

safari on mac

**Comment by ghost** [comment]
Confirm the issue (firefox, mac).

Issue caused by this setting:

![image](https://user-images.githubusercontent.com/78906980/119251108-fc7ccc80-bba4-11eb-9c2d-79e2c5fd8e80.png)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34146 . Thanks in advance.

**Comment by PhilETaylor** [comment]
The PR misinterpreted the issue.

**Comment by richard67** [comment]
Re-opening due to previous comment.

@PhilETaylor Could you comment that in that PR if not done yet?

**Comment by PhilETaylor** [comment]
Already done - I'll copy here...

**Comment by PhilETaylor** [comment]
To be clear: 

The issue is 

1)  the User Menu oval background is not the same height and depth as the other two (Postinstallation messages and joomla4 in your screenshot) 

2) User Menu is not underlined. 

<img width="1585" alt="Screenshot 2021-05-23 at 23 18 58" src="https://user-images.githubusercontent.com/400092/119278459-591bce00-bc1d-11eb-92fb-c6938c5178fd.png">

3) User Menu has no border/highlight

**Comment by richard67** [comment]
Is PR #34146 ok now after recent corrections so it solves this issue here and we can close it?
