### ISSUE TITLE
[4.0] An image in media manager image preview is not centered

### ISSUE THREAD

**Issue by eopws** [joomla/joomla-cms#34111]
### Steps to reproduce the issue

Go to media manager > images > sample data > parks > landscape and open the "120px_rainforest_bluemountainsnsw.jpg" image.

### Expected result

![expected](https://user-images.githubusercontent.com/42320170/119237298-c9a2ec00-bb44-11eb-994e-f108b6932d62.png)

### Actual result

![img](https://user-images.githubusercontent.com/42320170/119237301-cc054600-bb44-11eb-8d5f-beff27e945c6.png)

### System information (as much as possible)

Google chrome version 90.0.4430.212 (Official Build) (64-bit) on Windows 10.
Joomla version ‎4.0.0-beta8-dev.

### Additional comments

I don't have idea on how to solve it.

**Comment by eopws** [comment]
I believe that it wasn't a deliberate design solution as it looks weird on my opinion..

**Comment by brianteeman** [comment]
The title text is left-aligned which is the correct and intended behaviour as can be seen when previewing other images.

The problem here is that the text is bigger than the image

**Comment by dgrammatiko** [comment]
Please close
