### ISSUE TITLE
[4.0] Multilangual: Show Articles available for different languages (not countries)

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34116]
### Is your feature request related to a problem?

Articles show available country-sites like en-GB, fr-FR, … Its not possible to show available Articles for different languages like EN, FR, ….

User have to hover the country-tag to see that the site is for a language (title_native of content-language is renamed from "English (United Kingdom)" to "English"):

> ![image](https://user-images.githubusercontent.com/78906980/119253094-cd1f8d00-bbaf-11eb-82a0-46830b8af7de.png)

### Describe the solution you'd like

- Article-Option to show the  `Title in Native Language`.
or
- Show as image the Language like EN, FR, …, not a country flag: 
> ![image](https://user-images.githubusercontent.com/78906980/119253348-250ac380-bbb1-11eb-9a74-20479a9b9814.png)

### Additional context

#32992 changed the showing of language-tags:

> Using full lang tag in button to let choose when we have the same language for different countries: de-DE, de-AT"

This is helpfull having country-sites, but not helpfull having language-sites.

**Comment by brianteeman** [comment]
> Show as image the Language like EN, FR, …, not a country flag:

What image would you use?

**Comment by brianteeman** [comment]
I think I understand the issue
en-GB and en-US are different languages
de-DE and de-AT are different languages
The second part of the tag is not about the country. It is more about a variation of the languages

The incorrect use of nation flags encourages this confusion

**Comment by ghost** [comment]
> What image would you use?

"FA", "DE", "FR" like it was shown before #32992 (please ignore the red circle):

> ![image](https://user-images.githubusercontent.com/78906980/120271317-6551fc00-c2ab-11eb-828f-30fac10ca40a.png)

I guess this buttons in the article are by css and its not usable as image.

**Comment by infograf768** [comment]
> The second part of the tag is not about the country

Wrong.

This change was done as some sites may have multiple content languages which can only be differentiated by their country code.

a site can have de-DE, de-AT, de-CH
Each of these content languages may have different contents in their associated counterpart.
This is the only way to differentiate them.

Possible solution is to create a new parameter or create a layout override.
