### ISSUE TITLE
[4.0] Global Configuration - Sidebar collapse toggle incorrectly initialized for smaller screens

### ISSUE THREAD

**Issue by YatharthVyas** [joomla/joomla-cms#34117]
### Steps to reproduce the issue

1. Visit the Global Configuration page in the Backend.
2. Switch to the mobile view using Devtools.
3. **Refresh the page while being in the mobile view** or navigate outside and back to this page to imitate how a mobile user would enter this page.
4. Notice that the sidebar dropdown is initially expanded (Contrary to `aria-expanded="false"`) and when you press the toggle button, it goes through an animation to stay in the expanded state (class changes from `sidebar-nav` to `sidebar-nav collapsing` and then to `sidebar-nav collapse show`)

### Expected result
When you resize the screen after it has loaded, then the sidebar is initially hidden and the toggle button behaves as intended.

![config_menu2](https://user-images.githubusercontent.com/53610833/119253328-5e9df780-bbce-11eb-86f5-37ca45e25023.gif)

### Actual result
On refreshing the page in mobile view (without resizing), the menu is expanded by default and the first toggle button press doesn't collapse it.

![config_menugif](https://user-images.githubusercontent.com/53610833/119252855-12ea4e80-bbcc-11eb-9026-5ec85741ac55.gif)

### System information (as much as possible)
Google Chrome on Windows 10

**Comment by PhilETaylor** [comment]
Confirmed on real mobile iPhone 12

https://user-images.githubusercontent.com/400092/119260036-e41ea900-bbc8-11eb-9a56-b44b16ccec90.mov

**Comment by eopws** [comment]
> 4\. class changes from `sidebar-nav` to `sidebar-nav collapsing` and then to `sidebar-nav collapse show`

I have tried to add `sidebar-nav collapse show` to the list initially and it works and doesn't ruin anything, but I don't know whether it is a good solution or not?

**Comment by eopws** [comment]
IMHO, the "toggle menu" button has to have margin-left.

**Comment by infograf768** [comment]
> IMHO, the "toggle menu" button has to have margin-left.

If it does in LTR, then it should have a margin-right in RTL

**Comment by YatharthVyas** [comment]
> > 4. class changes from `sidebar-nav` to `sidebar-nav collapsing` and then to `sidebar-nav collapse show`
> 
> I have tried to add `sidebar-nav collapse show` to the list initially and it works and doesn't ruin anything, but I don't know whether it is a good solution or not?

This could be a possible fix but I think the person who wrote this code intended to keep the menu toggled off by default. I think maybe an alternate fix (not sure if better) could be executing the 'resize' JS event handler during page load.

![image](https://user-images.githubusercontent.com/53610833/119304439-dcbcd580-bc84-11eb-8786-522b5086a117.png)

**Comment by eopws** [comment]
Please test #34158

**Comment by YatharthVyas** [comment]
Closing in favour of #33877 (https://github.com/joomla/joomla-cms/pull/34158#issuecomment-846946233)
