### ISSUE TITLE
[4.0] Blog sample data - success message invisible

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#34126]
### Steps to reproduce the issue
Load blog sample data on a new Installation.

### Expected result
If sample data are loaded, the success message remains visible and has a dismiss button. 

### Actual result
The last message when loading sample data is closed and the screen refreshed before it can be seen.
The other messages have dismiss buttons.

![sampledata](https://user-images.githubusercontent.com/1035262/119260831-e5ee6980-bbd4-11eb-9965-c921ff4c47ae.gif)

**Comment by PhilETaylor** [comment]
look up :) 

<img width="1044" alt="Screenshot 2021-05-23 at 15 39 24" src="https://user-images.githubusercontent.com/400092/119264998-14704280-bbdd-11eb-849d-91bb1ad2e894.png">

**Comment by chmst** [comment]
:) small laptop and known issue. 

But it looks wrong, imho. May be it's only me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34126">issues.joomla.org/tracker/joomla-cms/34126</a>.</sub>
