### ISSUE TITLE
[4] Popover in extension update

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#34129]
### Steps to reproduce the issue
Install an extension where the update key is missing. 

Go to update extensions

### Expected result
Additional information should be added as a tooltip or schould be displayed completely as a warning text, without tooltip/popver

### Actual result
![grafik](https://user-images.githubusercontent.com/1035262/119262968-6ca74480-bbdd-11eb-9150-f742029fcc44.png)

### Additional comments
Related  #33698

**Comment by brianteeman** [comment]
Does that tooltip offer anything useful?

**Comment by brianteeman** [comment]
Added the fix for this to the existing PR #34419
