### ISSUE TITLE
[4] Debug bar duplicate query count. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34121]
### Steps to reproduce the issue

Maybe a won't fix.

Not sure if this will be a Joomla or upstream issue at the moment

Edit an article in Joomla 4 admin with debug mode on

The debug toolbar states

`45 statements were executed, 6 of which were duplicates, 39 unique`

When actually, logically, there are 3 which are duplicates of another 3. So there are only 3 duplicates, the first 3 are not duplicates, they are the originals. 

Having read several online dictionaries, Im still not certain and Im a native english speaker... haha

### Expected result

`45 statements were executed, 3 of which were duplicates, 39 unique`

### Actual result

`45 statements were executed, 6 of which were duplicates, 39 unique`

**Comment by PhilETaylor** [comment]
Another weird one, edit a user and you get `Edit user has 11 of which were duplicate queries to load` 

11 is an odd number haha.

**Comment by brianteeman** [comment]
Because a query could be triplicated
