### ISSUE TITLE
[4] [DOM] Found 2 elements with non-unique id #jform_browserNav #jform_template_style_id

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34128]
### Steps to reproduce the issue

Edit menu item - inspect the HTML 

### Expected result

All HTML Elements have unique IDs

### Actual result

Hidden in plain sight.
[DOM] Found 2 elements with non-unique id #jform_browserNav:
[DOM] Found 2 elements with non-unique id #jform_template_style_id

![Image 2021-05-23 at 2 24 14 pm](https://user-images.githubusercontent.com/400092/119262303-a58dec00-bbd2-11eb-86cb-17373bf49002.jpg)

**Comment by brianteeman** [comment]
not just duplicate ids - they are the same field being dupplicated

Please test #34136

**Comment by PhilETaylor** [comment]
yeah but Google Chrome console only reported on the ids :)

**Comment by PhilETaylor** [comment]
ta
