### ISSUE TITLE
[4.0] Additional informations from table header not hidden.

### ISSUE THREAD

**Issue by barsan-md** [joomla/joomla-cms#34125]
### Steps to reproduce the issue
1) Go to /administrator/index.php?option=com_banners&view=clients
2) Shrink the window below md breakpoint

### Expected result
Additional informations in the table are hidden.

### Actual result
In the table, additional informations about rows are hidden but the header is still shown

### System information (as much as possible)
![Cattura](https://user-images.githubusercontent.com/14260975/119261116-239fc200-bbd6-11eb-91de-a7297245383d.PNG)

### Additional comments
"d-none" class is ineffective in the header because display property is overridden by "d-md-table-cell".

**Comment by barsan-md** [comment]
Sorry, forget to fix the title. Can't edit it anymore.

**Comment by rjharishabh** [comment]
Please test #34143

**Comment by rjharishabh** [comment]
Please close as the issue has been resolved
