### ISSUE TITLE
[4] configuration.php offline_message  <br />

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34135]
### Steps to reproduce the issue

Install joomla 4
View configuration.php
Login to admin
save global configuration with no changes

see https://gist.github.com/PhilETaylor/95609cc3d716e985aa348da5b839cced/revisions

### Expected result

After saving Joomla global config `<br>` is retained.

### Actual result

`<br>` changed to `<br />`

**Comment by PhilETaylor** [comment]
upstream https://github.com/joomla-framework/filter/pull/49

**Comment by PhilETaylor** [comment]
well if my personal troll is going to down thumb the change upstream in the filter, and if Joomla 4 demands that we continue using `<br>` instead of `<br />` then Joomla (The CMS™) needs to make a decision to either fork the filter library to be able to make their change, or to stop enforcing the use of `<br>` over `<br /> in Joomla 4.

Over to you George @wilsonge

**Comment by brianteeman** [comment]
as the upstream pull request this valid bug should be reopened
