### ISSUE TITLE
[4] After using Download ID Quick Icon link, and saving download id, filter produces incorrect results. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34132]
### Steps to reproduce the issue

1. install a Joomla 4 compatible extension that supports download ids 
2. Return to Home Dashboard - see that A Download Key is missing quick icon is shown - click it to get to http://127.0.0.1:4444/administrator/index.php?option=com_installer&view=updatesites&filter[supported]=-1
3. Click the name of the extension to get to the edit page eg url http://127.0.0.1:4444/administrator/index.php?option=com_installer&view=updatesite&layout=edit&update_site_id=6
4. Enter a download id (anything) and click save and closse
5. Note that CORRECTLY it now says "No Matching Results" because we are filtered by "Download Key Invalid"
6. Change the filter to deselect "Download Key Invalid" to "-Select Download Key-"
7. We now have no filters so CORRECTLY the filters options are no longer shown
8. HOWEVER we also INCORRECTLY now have "No Matching Results" shown. 
9. Try to open Filter Options and make selections from the dropdowns - all will result in  "No Matching Results" shown. 
9. Press Clear to clear all selections from the dropdowns - result still  "No Matching Results" shown. 
9. Press Rebuild - result still  "No Matching Results" shown. 
9. Search for the name of your extension  - result still  "No Matching Results" shown. 

Im guessing there is some filter (filter[supported] ?) in the session that comes from the GET request from the quickicon click that cannot be toggled using the interface. 

### Expected result

filters apply correctly 

### Actual result

8. HOWEVER we also INCORRECTLY now have "No Matching Results" shown. 
9. Try to open Filter Options and make selections from the dropdowns - all will result in  "No Matching Results" shown. 
9. Press Clear to clear all selections from the dropdowns - result still  "No Matching Results" shown. 
9. Press Rebuild - result still  "No Matching Results" shown. 
9. Search for the name of your extension  - result still  "No Matching Results" shown. 

### System information (as much as possible)

safari on mac, google chrome on mac

**Comment by joomdonation** [comment]
@PhilETaylor There was a PR merged earlier today https://github.com/joomla/joomla-cms/pull/34357

Could you check to see if it solves this issue?

**Comment by PhilETaylor** [comment]
Fixed with #34357 duplicate of #34353
