### ISSUE TITLE
[4] Abusing Joomla Upload & Update for other purposes

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34138]
### Steps to reproduce the issue

Login to Joomla 4 admin
Click on Joomla is up to date quick icon
Click upload & update tab
Click choose file - select a ZIP file you created with some files (or hacker shells) in it (just as an example zip file with contents) 
Click upload & install 
enter username and password 
click install 

### Expected result

Joomla checks if its a valid Joomla package file. Aborts gracefully if not. Cleans up its changes only. 

### Actual result

Firstly you get Invalid Login. 

BUT THEN IT DOES EXTRACT ANYWAY!!!

<img width="589" alt="Screenshot 2021-05-23 at 16 24 31" src="https://user-images.githubusercontent.com/400092/119266613-64ea9e80-bbe3-11eb-892c-c2192f746178.png">

Joomla extracts the contents of the zip file to the root of the Joomla installation 

Joomla then deletes the /installation/ folder if it was there (eg, in development environment)

**Comment by chmst** [comment]
> Joomla then deletes the /installation/ folder if it was there (eg, in development environment)

Confirmed. 
Just had the issue when testing a patch. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34138">issues.joomla.org/tracker/joomla-cms/34138</a>.</sub>

**Comment by HLeithner** [comment]
parts of this reports are a duplicate of https://github.com/joomla/joomla-cms/issues/29763 so we should fix the invalid login error message.

**Comment by PhilETaylor** [comment]
> so we should fix the invalid login error message.

No, "we" should fix the fact that it is possible to upload literally anything - and not just a joomla update file - and have Joomla upload it and extract it to the root of the site with zero validation, checking or anything...  

Closing as #29763 is already open, for almost a year...
