### ISSUE TITLE
[4] configuration.php int/boolean

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34134]
### Steps to reproduce the issue

Install joomla 4
View configuration.php
Login to admin
save global configuration with no changes

see the https://gist.github.com/PhilETaylor/95609cc3d716e985aa348da5b839cced/revisions

as you can see debug_lang_const and cache_platformprefix on clean installation are booleans 

After saving Joomla global configuration, they are converted and stored as integers.

**Comment by wilsonge** [comment]
So obviously we should convert the cases to boolean/integer. However worth noting all J3 sites won't be converted - so we'll be handling both cases for at least the forseeable future (there probably are ways to try and force the conversion by running a save through the global config controller - but don't see any reason to force it - at least for now)

**Comment by PhilETaylor** [comment]
But Joomla 4 clean install and Joomla 4 saving configuration should pick a side and stick to it, there is no reason one should use a bool and one should use an int... regardless if the code reading those later on can use either.

**Comment by PhilETaylor** [comment]
PR [4] filter to bool the cache_platformprefix and debug_lang_const on save #34148
