### ISSUE TITLE
Error after PHP upgrade

### ISSUE THREAD

**Issue by Sichys** [joomla/joomla-cms#34141]
Please help me with ths;

My Linux shared hosting PHP version was upgraded to Php 7.2 and by the time I realized My Joomla website had stopped working. I  tried to update the joomla core files but still getting the below error; 

Fatal error: Uncaught TypeError: Argument 1 passed to JErrorPage::render() must be an instance of Exception, instance of Error given in /home/twigof1e/public_html/libraries/cms/error/page.php:28 Stack trace: #0 [internal function]: JErrorPage::render(Object(Error)) #1 {main} thrown in /home/twigof1e/public_html/libraries/cms/error/page.php on line 28

Any help in resolving this will be appreciated.

**Comment by PhilETaylor** [comment]
what version of Joomla are you running?

**Comment by brianteeman** [comment]
Please use the forum for support https://forum.joomla.org

**Comment by Sichys** [comment]
I think it is probably  Joomla 2.5 or something like that I can't really remember. I installed in 2015

**Comment by Bond97** [comment]
@Sichys if you have backup of your site, try to upload it to free hosting like cloudaccess or so on, turn on php version, that was been earlier and your Joomla site working. Or turn on that php vesrion in your shared hosting.
Check, it is working or not.
If it working, try to update your Joomla site to version 3.9.26 via manual installation https://github.com/joomla/joomla-cms/releases/download/3.9.26/Joomla_3.9.26-Stable-Update_Package.zip

If update will be success, you must do backup and upload it to main hosting.

**Comment by richard67** [comment]
Closing as not a Joomla CMS issue. Please use forum for support https://forum.joomla.org . You will find similar posts there where people had the problem that their PHP version was upgraded and their old and outdated Joomla 2.5 doesn't support such a new version.

Another common mistake are php.ini directives like e.g. `extension_dir` still pointing to the old version in a local php.ini file.

Same for `AddType` or `AddHandler` directives in an .htaccess file still using the old PHP version.
