### ISSUE TITLE
[4] Use Joomla\Input\Cli instead, despite that class not existing

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34162]
On Code review the class `\Joomla\CMS\Filter\InputFilter\Cli` has been deprecated, and every property and method has been marked as 

`* @deprecated  5.0  Use Joomla\Input\Cli instead`

The problem is that there is no such class as `Joomla\Input\Cli` which is very confusing for developers... 

https://github.com/joomla/joomla-cms/blob/f64e0186e41df3d68fa6b14d185cb4e60593cab9/libraries/src/Input/Cli.php#L19

**Comment by brianteeman** [comment]
This has been resolved with #34306 and can be closed
