### ISSUE TITLE
[4] PASSWORD_ARGON2ID requires PHP 7.3

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34170]
Code review. 

Support for Argon2id passwords using PASSWORD_ARGON2ID was added in PHP 7.3.0 and Joomla 4 needs to ensure full compatibility as low as /checks notes/ PHP 7.2.5

Documentation: https://www.php.net/manual/en/function.password-hash.php

using the constant `PASSWORD_ARGON2ID` therefore cannot be done. 

https://github.com/joomla/joomla-cms/blob/f64e0186e41df3d68fa6b14d185cb4e60593cab9/libraries/src/Authentication/Password/Argon2iHandler.php#L33

**Comment by ReLater** [comment]
I'm a bit irritated. You reference to joomla-cms/libraries/src/Authentication/Password/Argon2iHandler.php
`PASSWORD_ARGON2ID` is not used there. It uses `PASSWORD_ARGON2I` which is supported since 7.2.0

**Comment by PhilETaylor** [comment]
> I'm a bit irritated. 

Oh. Im sorry. I'm really really sorry that I made a typo and my irritated eyes did not notice the difference between `PASSWORD_ARGON2I` and `PASSWORD_ARGON2ID`

Let me go and search for the term for you... 

Here is the correct file link reference:

https://github.com/joomla/joomla-cms/blob/f64e0186e41df3d68fa6b14d185cb4e60593cab9/libraries/src/Authentication/Password/Argon2idHandler.php#L33

and here is what phpStorm states about it:

<img width="1169" alt="Screenshot 2021-05-24 at 13 14 03" src="https://user-images.githubusercontent.com/400092/119346422-17793a80-bc92-11eb-8b00-cb9f2565891c.png">

**Comment by PhilETaylor** [comment]
This class is referenced by the `password.handler.argon2id` service in the container provided by:

https://github.com/joomla/joomla-cms/blob/f64e0186e41df3d68fa6b14d185cb4e60593cab9/libraries/src/Service/Provider/Authentication.php#L54

**Comment by PhilETaylor** [comment]
Im guessing its a won't fix - as this code probably never runs, as the `Argon2idHandler::isSupported` checks the version number and returns false anyway...
