### ISSUE TITLE
[4.0] alert-warning colours

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34174]
In atum the color for a warning is yellow and the color for danger is red which is pretty standard. However when we get to the alerts the danger is still red but the warning is an ugly brown mud color. I'm assuming that wherever the calculation is done to set the color there is a mistake but this is beyond my css.

### alert warning
![image](https://user-images.githubusercontent.com/1296369/119345097-5c9c6d00-bc90-11eb-9d4c-8c231d8a894e.png)

### alert danger
![image](https://user-images.githubusercontent.com/1296369/119345167-6f16a680-bc90-11eb-892f-66dfaf082608.png)

### alert info
![image](https://user-images.githubusercontent.com/1296369/119345215-7f2e8600-bc90-11eb-8415-cb9e0210163d.png)

### alert success
![image](https://user-images.githubusercontent.com/1296369/119345275-92415600-bc90-11eb-9297-65860ab55f5e.png)

**Comment by himanshu007-creator** [comment]
https://github.com/joomla/joomla-cms/blob/565bb92433a85826297fead18cbc7f12c98be007/administrator/templates/atum/scss/_variables.scss#L194-L196

<code>darken($warning, 24%);</code> is responsible for this Muddish yellow color. 
If we set <code>$state-warning-text: $warning; </code>  and <code>$state-warning-border: $warning; </code>, <code> $warning:</code> is yellow then it would look like this. If this is desired, I'll send the PR right away.
![ss](https://user-images.githubusercontent.com/65963997/119628253-8ee1d200-be2a-11eb-86b6-db6546155ad3.gif)

**Comment by brianteeman** [comment]
Changing the values as you suggest didnt change the text color as you show and i still get a text color of mud

Having said that I doubt the yellow on yellow has enough contrast and the mud color seems to work ok and have sufficient contrast. 

Please try to create a PR and check the colors with the contrast checker https://webaim.org/resources/contrastchecker/

**Comment by himanshu007-creator** [comment]
Yes, yellow on yellow don't have enough contrast                 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<a href="https://webaim.org/resources/contrastchecker/?fcolor=FFB514&bcolor=FFFCF4">reference</a>

Present Mud color have a good contrast though
![2021-05-27](https://user-images.githubusercontent.com/65963997/119792333-3d514a00-bef3-11eb-8d01-af82a6cdfd92.png)


The contrast ratio is not good, so I didn't sent  a PR. <a href="">These</a> are some valid combinations, but having such background will not establish an identical behavior with other alert styles.

**Comment by brianteeman** [comment]
If you can work it out so that the text is mud and the rest is yellow that would be great
