### ISSUE TITLE
[4.0] [Media] Ludicrous frame in crop / resize / rotate operations

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34184]
### Steps to reproduce the issue
Go to Media Manager, select any image to edit. Pay attention to the frame during in crop / resize / rotate operations. In some places, overlap of 2 and even 3 lines (see the first screenshot). I think it would be better to remove it. 

**With and without frame**

![Screenshot_4](https://user-images.githubusercontent.com/8440661/119398252-fb9c8580-bcdf-11eb-8ff4-5458e9008a14.png)

![Screenshot_5](https://user-images.githubusercontent.com/8440661/119398254-fccdb280-bcdf-11eb-9be9-da3d8f4f384b.png)

**Comment by brianteeman** [comment]
its the border around the fieldset.

**Comment by brianteeman** [comment]
please test #34189
