### ISSUE TITLE
[4.0] [Cassiopeia] Classic style checkboxes

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34183]
### Steps to reproduce the issue
Go to System - Site Styles, in the Cassiopeia style parameters on the Menu Assignment tab, you can see the classic style checkboxes.

Perhaps the root of the issue is somewhere near https://github.com/joomla/joomla-cms/issues/33794, I'm not sure - haven't researched the issue, just let you know.

![Screenshot_3](https://user-images.githubusercontent.com/8440661/119397770-48339100-bcdf-11eb-8e7e-3be88c2d62b5.png)

**Comment by rjharishabh** [comment]
Please test #34213
