### ISSUE TITLE
[4] build.php PHP Warning:  Undefined variable $tagVersion

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34188]
### Steps to reproduce the issue

`php build.php --remote=4.0-dev`

wait.....

### Expected result

No PHP Errors, Notices or warnings... 

### Actual result

<img width="1259" alt="Screenshot 2021-05-24 at 21 26 37" src="https://user-images.githubusercontent.com/400092/119403753-be7fc580-bcd6-11eb-9990-1c94b5b8728e.png">

```bash
Generating github_release.txt file
PHP Warning:  Undefined variable $tagVersion in /Users/phil/Sites/JOOMLA/joomla4/build/build.php on line 632

Warning: Undefined variable $tagVersion in /Users/phil/Sites/JOOMLA/joomla4/build/build.php on line 632
Build of version 4.0.0-beta8-dev complete!
```

### System information (as much as possible)

MacOS file system

### Additional comments

The cause is because we specified a `--remote=4.0-dev` in the command and the code only sets `$tagVersion` if no remote is provided. 

```php
// If not given a remote, assume we are looking for the latest local tag
if (!$remote)
{
	chdir($repo);
	$tagVersion = system($systemGit . ' describe --tags `' . $systemGit . ' rev-list --tags --max-count=1`', $tagVersion);
	$remote = 'tags/' . $tagVersion;
	chdir($here);
}
```

**Comment by zero-24** [comment]
Will be fixed here and than moved up to 4 after its merged: https://github.com/joomla/joomla-cms/pull/34341
