### ISSUE TITLE
[4.0] [Cassiopeia] Font information block on the right

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34181]
### Steps to reproduce the issue
Go to System - Site Styles, click on the cassiopeia style options. Below is a block of information about fonts. Previously, it was located OVER, now on the right. Not sure if this move was intended.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/119396874-1ff76280-bcde-11eb-8ffa-1072c1add639.png)

**Comment by brianteeman** [comment]
Definitely not intentional - looking to see which pr broke it

**Comment by brianteeman** [comment]
@chmst please can you look at this as it comes from your PR https://github.com/joomla/joomla-cms/pull/33751

**Comment by Kostelano** [comment]
Probably where the BRAND was added.

**Comment by chmst** [comment]
I reverted the usage of parentclass  - the message now is as before BELOW the font face field. Please test #34200.
