### ISSUE TITLE
[4.0] User Notes: Select field does not change its color depending on the status

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34193]
### Steps to reproduce the issue
Go to any user, add a note to it. Please note that the select field does not change its color depending on the value (status). As far as I could notice, in other places regarding the status of Published / Not published, the color change Green / Red is implemented. 

Perhaps this is normal behavior, then just close Issue. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/119408780-f2ff7b80-bcee-11eb-958a-49496c28cc78.png)

**Comment by brianteeman** [comment]
please test #34194
