### ISSUE TITLE
Change attribute route to com_contact

### ISSUE THREAD

**Issue by deibit** [joomla/joomla-cms#34198]
Hello all.

Just by chance I took a look into some components and notice route should be:

`/administrator/components/com_contact/models/fields`

instead of 

`/administrator/components/com_contacts/models/fields`

Regards

https://github.com/joomla/joomla-cms/blob/443f5933a3c9336f37f992d855b61b09a5f4e21e/components/com_contact/models/forms/filter_contacts.xml#L3

**Comment by joomdonation** [comment]
Thanks for reporting @deibit . That filter form does not use Modal_Contact field type (the only field type defined in administrator/components/com_contact/models/fields folder), so I would say that we can event remove the whole code`addfieldpath="/administrator/components/com_contacts/models/fields"` from that line. Could you please make a PR for the change?

**Comment by joomdonation** [comment]
Closing as there is PR https://github.com/joomla/joomla-cms/pull/34203 . Thanks @deibit
