### ISSUE TITLE
[4.0] Creating a menu in the panel: there are items where the component was not exist

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34192]
### Steps to reproduce the issue
Go to the menu manager, create a menu for the CONTROL PANEL and select, for example, Help Preset as a preset. Save. Please note that 24 items were automatically imported (in my case), among which there are items in which "the component was not found".

I have not tested other presets, but I think the problem is there as well. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/119407115-723f8000-bcec-11eb-9c9e-d3a7401f7339.png)

**Comment by Kostelano** [comment]
At the same time, supposedly, all the points were published. Although the screenshot above says otherwise.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/119407422-deba7f00-bcec-11eb-8e29-2e32a8d792d1.png)

**Comment by Kostelano** [comment]
So, I caught a similar error only with the help preset. But in other presets there are also surprises (the values of the language constants are not pulled up).

**Comment by brianteeman** [comment]
please test #34704
