### ISSUE TITLE
Edit article trough menu item Single article empty

### ISSUE THREAD

**Issue by joris85** [joomla/joomla-cms#34206]
### Steps to reproduce the issue
Create menu items with single article 
Choose an article or create one
After saving menu item click on edit article (left next to create article)
I see a popup with creating a new article instead of edit

### Expected result
See article item that is selected in the menu item that i can edit

### Actual result

I see a popup with creating a new article instead of edit

### System information (as much as possible)
Php 7.4
Joomla 4 beta 7

**Comment by joomdonation** [comment]
@joris85 Could not confirm the issue. Instead of testing it with beta 7, could you please use Joomla 4 nightly build instead? You can download it from this page https://developer.joomla.org/nightly-builds.html or with this direct link https://developer.joomla.org/nightlies/Joomla_4.0.0-beta8-dev-Development-Full_Package.zip

**Comment by PhilETaylor** [comment]
> After saving menu item click on edit article (left next to create article)

There is no "Create" button next to the edit button, its a clear button.

<img width="1133" alt="Screenshot 2021-05-25 at 19 48 41" src="https://user-images.githubusercontent.com/400092/119552064-3828b980-bd92-11eb-8ef7-659048faf782.png">

I cannot replicate the issue, when I press edit I see the article I created.

**Comment by joris85** [comment]
Ok Tuan, i will update today! 

Phil your right, before it is create, after it is ckear. 
So i ment next to clear 😅

**Comment by joris85** [comment]
It works after the update to beta8-dev :-D

**Comment by joomdonation** [comment]
Closing
