### ISSUE TITLE
[4] Edit article in modal has tags width issue

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34214]
### Steps to reproduce the issue

Create a menu item to point to a single article

Use edit button in the menu edit page to load article in the modal

See the tags select box width is wrong

### Expected result

Here is the article edit page - tags width is fine there:

<img width="1596" alt="Screenshot 2021-05-25 at 19 49 30" src="https://user-images.githubusercontent.com/400092/119552525-8a69da80-bd92-11eb-8a25-11ba3d8bdd55.png">

### Actual result

Although you see my 1Password icon in this video, i do not believe is that. 

https://user-images.githubusercontent.com/400092/119552628-a3728b80-bd92-11eb-894c-8215747e262b.mp4

Note if I make my browser "far too wide, even wider than normal (more than half the 27" iMac screen) then the tags is the same width as the other fields. 

https://user-images.githubusercontent.com/400092/119552877-eb91ae00-bd92-11eb-9405-72063876aa1e.mp4

### System information (as much as possible)

safari on mac

**Comment by ghost** [comment]
Similar #27907.

**Comment by PhilETaylor** [comment]
Thanks - seems there is already discussion about this upstream so I'll close this one.
