### ISSUE TITLE
[4.0] cpanel border radius

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34210]
The modules on the dashboard are displayed with top corners as rounded and bottom corners as square. Looking at the css I don't believe this is intentional - especially as the "add module" block has rounded corners top and bottom.

Closer investigation shows that it is caused by

```
.com_cpanel .card-body {
    padding:0;
}

```

As soon as you put the padding back to 1rem the corners are back, this css was added by @ciar4n [4.0] Admin UI repaint (#33100) and I assume its a mistake but would prefer @ciar4n to have the opportunity to comment before making a PR.

PS also everything "looks better" **to me** with the lines not reaching the edges.

### screenshot without padding
![image](https://user-images.githubusercontent.com/1296369/119537606-1d4e4900-bd82-11eb-960f-1df67547f86e.png)

### screenshot with padding
![image](https://user-images.githubusercontent.com/1296369/119537701-39ea8100-bd82-11eb-8a83-a34ce2c8c4fb.png)

**Comment by ciar4n** [comment]
Indeed an issue and not as intended. Rather than reverting the padding I would suggest adding `overflow: hidden` to the card element.

**Comment by brianteeman** [comment]
Thanks @ciar4n pull request at #34218
