### ISSUE TITLE
[4.0] Fieldset (Blog/Featured Layouts)

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#34219]
### Steps to reproduce the issue
Content > Articles > Options
> Categories: Layout OK (and others).

![screen shot 2021-05-25 at 21 27 26](https://issues.joomla.org/uploads/1/996495b93060f4a704a83dc7d3cf8b24.jpg)
> Blog Features Layouts not OK.

![screen shot 2021-05-25 at 21 27 51](https://issues.joomla.org/uploads/1/6e20f332cdd30f8a2a77ae8d04b546b1.jpg)

Both have the same screensize.
### Expected result
belongs to: `<div class="tab-description alert alert-info">`?
### Actual result
see screenshots

### System information (as much as possible)
4.0.0-beta8-dev

**Comment by rjharishabh** [comment]
Please test #34222

**Comment by richard67** [comment]
Closing as having a pull request.
