### ISSUE TITLE
[ALL] PHP Version Check

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34225]
Before **_attempting_** a PR can people confirm my finding and that I have not made a silly mistake.

The plugin quickicon check is supposed to give a warning once the php version reaches the security only date and an error message when it reaches the end of support date.

As far as I can tell the security only warning message can **never** be displayed because the code is wrong. 

This applies to all versions 3.9x, 3.10, 4.x

The easiest way to confirm this is to change the dates for your version of php in the plugin code.

@wilsonge @zero-24 @HLeithner

**Comment by HLeithner** [comment]
The security date is not used but the warning is shown 3 month before end of support. I'm not sure if it's useful to show a "in security only mode" message a year in advanced before the php versions is eol. The 3 month should be enough.

**Comment by brianteeman** [comment]
That is what the code is doing because it is **broken**.

It was certainly written to display the end of support information originally and I didnt see a PR that states an intentional change to that behaviour

> This plugin checks three conditions: whether the PHP version is still fully supported, whether it has entered security support only, or whether it is unsupported by the PHP project. 
https://github.com/joomla/joomla-cms/pull/11498#issue-80350584

Why else do we have the string 
https://github.com/joomla/joomla-cms/blob/6a25a6a38fedbbaaae0ab9476607eb9ecf25a5e9/administrator/language/en-GB/en-GB.plg_quickicon_phpversioncheck.ini#L8

**Comment by brianteeman** [comment]
oh wait - i misunderstood you - checking

**Comment by brianteeman** [comment]
I get it now - sorry for the confusion. It displays the security notice 3 months before the end of life. I get it now. Sorry for disturbing
