### ISSUE TITLE
Language install error: Unable to detect manifest file

### ISSUE THREAD

**Issue by joris85** [joomla/joomla-cms#34231]
### Steps to reproduce the issue
Installing Dutch in the Joomla 4 installer.
I get this error: Unable to detect manifest file.

### Expected result
Installing language :-)

### Actual result
Error: Unable to detect manifest file.

### System information (as much as possible)
Joomla 4 Beta8-dev

### Additional comments
Maybe it is not yet active but i tried to install it trough the installer and i get an error.
Should this already work or are there not languages yet and is it just waiting for the right files?

**Comment by richard67** [comment]
@joris85 In J4 currently only the language packs for German (DE), French and Persian work.

**Comment by richard67** [comment]
Closing as duplicate report, see issue #34231 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34231">issues.joomla.org/tracker/joomla-cms/34231</a>.</sub>
