### ISSUE TITLE
[4.0] Privacy: Information Requests - different styles of icons for export

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34235]
### Steps to reproduce the issue
Go to **Privacy: Information Requests**, create a request to export data (you can enter your email address).
Confirm your request by email.

Return to the **Privacy: Information Requests** page, notice the difference in the export icons. When you click on an icon, there is also a border, which is not observed when you click on other icons in Joomla.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/119712522-56adb400-be69-11eb-9f92-5155265c3049.png)

As for the delete data icon, it is fine.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/119712616-72b15580-be69-11eb-8d68-94ac4dce0f66.png)

**Comment by PhilETaylor** [comment]
The icons are correct. You can Download, Email or invalidate a request depending on the status of the request.

**Comment by brianteeman** [comment]
There is an outline when you click on either export or email - you just might not have seen it due to the time it takes to perform the action.

Regarding the email icon I am assuming that your comment is that it is grey in colour and looks as if it is disabled? If so then thats an easy fix

**Comment by brianteeman** [comment]
Actually it looks like a css bug and it should look like this

![image](https://user-images.githubusercontent.com/1296369/119732331-f2dab980-be6f-11eb-9543-999fb24fc992.png)

**Comment by PhilETaylor** [comment]
Doesn't it (wrongly, showing state by colour only being bad and all that) change colour after you have clicked it to email the personal data to the requester? Or am I making that up....

**Comment by brianteeman** [comment]
If I guessed correctly and it was the grey colour was the issue then please test #34237

**Comment by alikon** [comment]
please test #34237

**Comment by Kostelano** [comment]
@brianteeman Thank you, that's what I meant.

@PhilETaylor The gray icon did not change color after performing the action.
