### ISSUE TITLE
[4.0] Users: Edit Profile: notification about Joomla API Token of a different type

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34247]
### Steps to reproduce the issue
Include User plugin - Joomla API Token and, for example, two factor authentication plugins. Go to editing your profile, pay attention to the type of notification on the Joomla API Token tab - P-tag + has no icon. On the next tab (two-factor authentication), the notification has an icon and is placed in the DIV + SPAN tags.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/119875258-3a744a80-bf2f-11eb-9985-c4c25822f44b.png)

Option from an adjacent tab.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/119875313-49f39380-bf2f-11eb-97a9-732aaed6b8bd.png)

For some reason, the notification of the User plugin - Joomla API Token is "hardcoded" into the XML-file.

```
<field
	name="saveme"
	type="note"
	label="PLG_USER_TOKEN_SAVEME_DESC"
	heading="p"
	class="alert alert-warning"
/>
```

In fact, I decided to designate this "problem" because I have already met similar places in Joomla 4 several times. In my opinion, there is no unity in notifications of this type.

**Comment by PhilETaylor** [comment]
Please test [4] Change notefield form field to display better #34323
