### ISSUE TITLE
[4.0] Users: too many columns in the panel

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34249]
### Steps to reproduce the issue
I missed the PR, which implemented a "reduction" in the number of columns in the CONTENT / ARTICLES pane. I love it.

I have a fairly small laptop. There are probably the same users. I think that a similar solution is needed for several more Joomla panels, in particular - USERS. Below I have provided the current screenshots of how it looks.

In my opinion, it would be correct to "hide" columns that the administrator does not use with some additional option. After all, at the first glance at the mass of sites where, say, there are only 4-5 users and there is no registration, information about the date of their registration / activation is not at all necessary. As an example.

In addition, the font size of the column contents can also be reduced, following the example of the CONTENT / ARTICLES panel.

In general, these are general thoughts, but perhaps we will come to improvement.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/119877038-3812f000-bf31-11eb-9c29-acec1821abde.png)

![Screenshot_2](https://user-images.githubusercontent.com/8440661/119877041-38ab8680-bf31-11eb-8fb7-aef930aa0229.png)

**Comment by Quy** [comment]
Duplicate #32820. Thanks for the report.
