### ISSUE TITLE
Smart Search: Can't find items with short description

### ISSUE THREAD

**Issue by slepoy1** [joomla/joomla-cms#34242]
### Steps to reproduce the issue
Problem appear after updating from J3.9.26 to J3.9.27.

1) add video to EasySocial component with short description
2) result 1: item is indexed (can see it in backend > com_finder / smart search).
3) but can't find it with smart search on frontend
4) edit video item and add long description
5) Result 2: I can now find it with smart search on frontend.

### Additional comments

After long hours debugging this issue on site, (clearing the indexes and re-index the videos), what we find out is, if a EasySocial video has a very short description, this video most likely will not be able to search in Smart Search. However, if you give long description to the video, then this video will be searchable in Smart search.

You can try to edit this video and give a very short video description and try to search again using the same search term, you will notice your search will not have the test video.

Based on the these finding, I believed this is an issue from Joomla smart search itself.

look like this is an issue with latest Joomla 3.9.27. I believed Joomla changed something on the smart search which causing the search return inconsistent results.

**Comment by slepoy1** [comment]
I temporary fix it this way:
1) downloaded **Joomla! 3.9.26 to 3.9.27 Patch Package (.tar.bz2)**
2) checked what files about com_finder was changed.
3) downloaded Joomla! 3.9.26 Full Package (.tar.bz2)
4) unzipped files about com_finder and uploaded it to site (replaced com_finder files 3.9.27 by 3.9.26)
5) re Index content in com_finder backend
Result: Now I can find everything.

How is possible to fix it in next Joomla release?

Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34242">issues.joomla.org/tracker/joomla-cms/34242</a>.</sub>

**Comment by slepoy1** [comment]
Updated: I noticed the same problem with com_content.
If there is short text in Intro text, article will not be found.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34242">issues.joomla.org/tracker/joomla-cms/34242</a>.</sub>

**Comment by Quy** [comment]
Maybe because of this PR #33720. Please replace `administrator/components/com_finder/helpers/indexer/indexer.php` with the v3.9.26 version to see if it is the culprit.

**Comment by slepoy1** [comment]
> Maybe because of this PR #33720. Please replace `administrator/components/com_finder/helpers/indexer/indexer.php` with the v3.9.26 version to see if it is the culprit.

Hi. Yes, I replaced all com_finder related files by files from v3.9.26 and it helped.

Later I’ll try to replace only indexer.php. Thanks.

**Comment by charlynancy54** [comment]
I confirm these errors. This also happens with the following finder plugins: categories, weblinks, flexicontent.
I confirm these errors. This also happens with the following finder plugins: categories, weblinks, flexicontent.
Fix it by overwriting old files of the finder component is OK

**Comment by mbaggy** [comment]
same problem in com_content with a short article (316 characters). I did a test: just added some lorem ipsum in an article. After that the article showed up as result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34242">issues.joomla.org/tracker/joomla-cms/34242</a>.</sub>

**Comment by nonickch** [comment]
Confirming this with com_content. Article title is not being indexed when there's two (or more?) words in the title.
Rolling back to 3.9.26 and saving the article makes it searchable. Updating to 3.9.27 no longer makes it searchable.

Said article has no content in the html editor, we compose it on the fly from customfields.
I did try inserting 5 lines of 100chars, did not fix it. So I'm not sure that the length of the article is at fault.
I did trace this down to the indexer. The title does not end up as a term in the terms table. It's "duh" thing, but I did check :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34242">issues.joomla.org/tracker/joomla-cms/34242</a>.</sub>

**Comment by Quy** [comment]
Please post which files were replaced/reverted to fix the issue.

**Comment by prinswebdevelopment** [comment]
Same problem with all titles? I can't find articles on part of title that doesn't exist in article self.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34242">issues.joomla.org/tracker/joomla-cms/34242</a>.</sub>

**Comment by nonickch** [comment]
@Quy : Rolling back 3.9.27 to 3.9.26 is what fixed the issue for me, after re-indexing the test article via opening/saving it (I can only assume that there's no difference between mass-index and single-article indexing).

So the file-list is everything in 3.9.26. (EDIT: this should be "everything in 3.9.27" )

@prinswebdevelopment : I had a similar theory, but I didn't get to verify it so I'm not 100% certain.
I'll prod at this issue within the week and I'll probably get closer to this, if not home in.

**Comment by HLeithner** [comment]
@Hackwar found a regression in on of the pr merged into 3.9.27. We hopefully see a fix soon.

**Comment by Quy** [comment]
Please test PR ##34497
