### ISSUE TITLE
[3.9] Link to JDocs in the Update Warning Message

### ISSUE THREAD

**Issue by alejandrovega** [joomla/joomla-cms#34254]
### We don't have a direct link to provide the step by step process.
![Screenshot_2021-05-27 Joomla Update - DemoSite - Administration](https://user-images.githubusercontent.com/9896498/119924146-a6a77c00-bf38-11eb-9187-ab7336bf88c5.png)

### Why this should be fixed
What if users don't know how this process can be achieve?

### How would you fix it
Providing a link within the Warning.

### Side Effects expected
Users can find a direct link to Docs **with the correct process** and **official recommendations** for this process.

**Comment by PhilETaylor** [comment]
> Users can find a direct link to Docs with the correct process and official recommendations for this process.

I could not find such a resource.

**Comment by AMurray2016** [comment]
Are you meaning "how to backup your site" and/or Update Extensions (as that is what is mentioned in the warning message):
Would these not be the right resources of documentation: https://docs.joomla.org/Backup_Basics_for_a_Joomla!_Web_Site, and https://docs.joomla.org/Help39:Extensions_Extension_Manager_Manage.  Or do you mean a link to the Joomla update process - https://docs.joomla.org/J3.x:Updating_from_an_existing_version?

If I have missed the point of @alejandrovega post please clarify what the discussion is about......

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
