### ISSUE TITLE
Please provide more context on failed delete

### ISSUE THREAD

**Issue by echterhoff** [joomla/joomla-cms#34259]
Hi there,

every here and then some things go wrong. A message about some undeletable file is great but actually worth nothing, if you don't know where to look for that specific problem.
It would be great if that delete method could provide also the path to look for the specific file.

Since this file gets rewritten during a core file refresh, changing it by myself is no option.

https://github.com/joomla/joomla-cms/blob/443f5933a3c9336f37f992d855b61b09a5f4e21e/libraries/vendor/joomla/filesystem/src/File.php#L126

Thanks
Lars

**Comment by brianteeman** [comment]
So instead of changing it yourself and having it rewritten why dont you submit your changes as pull request here

**Comment by echterhoff** [comment]
Hi Brian,

simply because I have no clue how to do this in a fast, economic way other than forking, changing and request you guys to pull my changes. (I know that's the reason for Github to exist.)
My thought on this small thing was more like: Well, maybe someone with it's hands already on the code might add it and...

I will add it and send you a pull request later that day. My fault.

Have a nice day
Lars

**Comment by brianteeman** [comment]
I wouldnt know what the code is that you want to change to. But if its just in a single file then you can find the file here on github, click on the pencil icon in the top right and make your changes following the onscreen instructions.
