### ISSUE TITLE
[4.0] Web services don't always comply with JSON:API

### ISSUE THREAD

**Issue by pjdevries** [joomla/joomla-cms#34269]
### Steps to reproduce the issue

Access a `PATCH` or `DELETE` endpoint. 

### Expected result

A valid [JSON:API](https://jsonapi.org/) document response.

### Actual result
`PATCH`: `[]`
`DELETE`: `1`

**Comment by wilsonge** [comment]
Agree patch needs fixing.

To me delete should be returning the empty response as https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/MVC/Controller/ApiController.php#L322 doesn’t output anything. Should be an easy fix somewhere

**Comment by wilsonge** [comment]
OK just tested this - for me I'm not getting any response back from delete (as expected).

Obviously as you say patch is incorrect

**Comment by alikon** [comment]
so for the PATCH
this will be enough  in your opinion ? @wilsonge @pjdevries 
after this line 
https://github.com/joomla/joomla-cms/blob/884d197bc5bd9face0130508577ce622b9bc626d/libraries/src/MVC/Controller/ApiController.php#L396

adding  `$this->displayItem($recordId);   `

**Comment by pjdevries** [comment]
@alikon Makes sense, since `POST` is handled in a similar fashion. But I'm not the expert, so I leave it up to @wilsonge.

**Comment by alikon** [comment]
better discuss with code :smile: 
see #34313

**Comment by pjdevries** [comment]
> OK just tested this - for me I'm not getting any response back from delete (as expected).

Don't want to nit pick, bu no response is not entirely as expected. That is to say, if we want to comply with the JSON:API completely. Take a look at [JSON:API](https://jsonapi.org/format/#crud-deleting-responses) says about `DELETE` responses. A 200 response should return 'only top-level meta data'.

**Comment by wilsonge** [comment]
> Don't want to nit pick, bu no response is not entirely as expected. That is to say, if we want to comply with the JSON:API completely. Take a look at JSON:API says about DELETE responses. A 200 response should return 'only top-level meta data'.

I agree but I'm getting back a 204 not a 200 (which is expected as we're setting that here https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/MVC/Controller/ApiController.php#L322) and that's totally allowed by JSON API in that section.

Would be useful to see what request you're getting a 200 from on a delete. Because I can't seem to reproduce that.

**Comment by pjdevries** [comment]
> Would be useful to see what request you're getting a 200 from on a delete. Because I can't seem to reproduce that.

I'm getting a 200 from my recently added media web service :) Deleting an article gives me a 204 but also returns an unexpected literal `1` in the response.

**Comment by pjdevries** [comment]
@wilsonge The `200` response from my media web service was not correct, so I remedied that. It now returns a `204` but still also return a literal `1`. Can't find where that happens though.
