### ISSUE TITLE
A txt file that is supposed to be deleted to verify ownership of a website during installation is not created.

### ISSUE THREAD

**Issue by PlanetProphet** [joomla/joomla-cms#34283]
### Steps to reproduce the issue
Unpack Joomla_4.0.0-beta7-Beta-Full_Package.zip and upload using Filezilla over ftp to installation folder. Enter website to open installation screen. Enter all information required up to database details. When pressing "Install Joomla" button the following warning message is displayed:

You are trying to use a database host which is not on your local server. For security reasons, you need to verify the ownership of your web hosting account. Please read the documentation for more information.

and the following information message:

To confirm that you are the owner of this website please delete the file named "_JoomlalzcKUQ4iOQRZipgwzQJTI.txt" that has been created in the "installation" folder of your Joomla site. Then select "Install Joomla" to continue.

### Expected result

A file should be created in the installation folder, to be deleted for ownership confirmation. No such file is created in the installation folder and the instructions in the documentation referred to above (link below) do not help to solve it. No instructions to upload a file are given either (as mentioned for FTP mode by the link). https://docs.joomla.org/J3.x:Secured_procedure_for_installing_Joomla_with_a_remote_database

### Actual result

Installation cannot proceed, as site ownership cannot be verified.

### System information (as much as possible)
Linux Web Hosting with PHP 7.4.15

**Comment by zero-24** [comment]
> No such file is created in the installation folder 

hmm do you have the wwwrun problem that your user (that runs php) is not allowed to write to the disk?

If so please double check that you can not fix that permision issue with your hoster, as that will lead to even more issues along the line. In order to fix this issue here please upload an empty file with the name mentiond in the message to the "installation" folder and proceed with the installation.

**Comment by PhilETaylor** [comment]
I cannot replicate this on linux docker containers that I rebuild each day, it has always correctly generated the file for me (I need it as mysql is in a different container with a different hostname).

**Comment by PlanetProphet** [comment]
Thanks for the helpful comments.

I will have a look into the wwwrun problem. I can write files to the website directory over ftp no problem and the permissions are set to 755 for the main directory as required. I don't have access to all the server settings though, so will have to call the service provider to check if there are any other permissions that could be causing this.

**Comment by Quy** [comment]
Please test using the nightly builds to see if the issue persists.

https://developer.joomla.org/nightly-builds.html

**Comment by PlanetProphet** [comment]
Thank you, it has worked now. I got the admin to reset my account on the server and installed the latest build.
