### ISSUE TITLE
[4] File header in framework forked libraries need updating

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34294]
Files in `/libraries/src` need their headers updated 

They are currently:

```
<?php
/**
 * Joomla! Content Management System
 *
 * @copyright  (C) 2009 Open Source Matters, Inc. <https://www.joomla.org>
 * @license    GNU General Public License version 2 or later; see LICENSE.txt
 */
```

There is no need for `Joomla! Content Management System` and Im sure there is some other standard header the project wants

**Comment by brianteeman** [comment]
Looking at other libraries from other vendors I see similar headers

This file is part of the Symfony package.
This file is part of the TYPO3 project.
This file is part of sebastian/diff.
This file is part of the php-code-coverage package.
This file is part of the DebugBar package.
