### ISSUE TITLE
large xml file template and debug enabled causes http error 500

### ISSUE THREAD

**Issue by cloudfaction** [joomla/joomla-cms#34309]
### Steps to reproduce the issue

use a template, with a large xml manifest file (140kb or larger) enable debug system

### Expected result

always have access to template settings

### Actual result

with large xml file and debug system on, the template settings page causes http 500 error

### System information (as much as possible)

4.0.9Beta8 DEV

### Additional comments

making my template ready for J4 caused me this problem. Dunno if the error is from the size, but it seems. when making the xml manifest smaller, to a certain size, the template settings work with debugging enabled.

**Comment by cloudfaction** [comment]
sorry system is 4.0.0-beta8-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34309">issues.joomla.org/tracker/joomla-cms/34309</a>.</sub>

**Comment by brianteeman** [comment]
please check the php setting max_input_vars 
if its at 1000 change it in php to 2000

**Comment by cloudfaction** [comment]
set to 2k problem still occurs.

**Comment by cloudfaction** [comment]
php 7.4

max_execution_time:30
max_input_time: -1
max_input_vars: 2000
memory_limit: 128m

**Comment by brianteeman** [comment]
was just an idea. sorry it didnt help

**Comment by PhilETaylor** [comment]
Please provide the exact XML file you are using.

**Comment by cloudfaction** [comment]
http://joonextpro.com/joonextpro.zip is the template file i use to install

**Comment by brianteeman** [comment]
you have invalid xml - thats why you have the problem

**Comment by cloudfaction** [comment]
ok. but works fine without debugging

**Comment by PhilETaylor** [comment]
Firstly on install you are doing something crazy that breaks Joomla 4 admin template...

<img width="1599" alt="Screenshot 2021-05-31 at 19 34 58" src="https://user-images.githubusercontent.com/400092/120230494-55a0cc00-c247-11eb-92ff-fe88ffcdcbf8.png">

**Comment by PhilETaylor** [comment]
And I am able to edit the template ok:

<img width="1601" alt="Screenshot 2021-05-31 at 19 36 26" src="https://user-images.githubusercontent.com/400092/120230585-87199780-c247-11eb-8251-7ce52a2f7b0a.png">

**Comment by PhilETaylor** [comment]
But editing template styles I get a Memory issue writing log files:

```
webserver_1  | 2021/05/31 18:37:23 [error] 29#29: *42 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes) in /application/libraries/src/Log/LogEntry.php on line 121PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 32768 bytes) in /application/libraries/vendor/symfony/error-handler/Error/OutOfMemoryError.php on line 1PHP message: PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 307200 bytes) in Unknown on line 0" while reading response header from upstream, client: 172.19.0.1, server
```

**Comment by brianteeman** [comment]
Fix **all** the extra </field> that you have on line 290

39,721 characters on one line is pretty crazy - no wonder you didnt see the errors

**Comment by PhilETaylor** [comment]
I can load the edit page now, and all I did was refresh the page a few times... 

The problem is a simple running out of PHP Memory 

Im guessing that the overhead of storing the debug information and logging is adding some memory use before the page gets to render your insanely large form fieldsets :) 

<img width="1599" alt="Screenshot 2021-05-31 at 19 42 56" src="https://user-images.githubusercontent.com/400092/120231103-93522480-c248-11eb-8b6a-d102714b20c1.png">

**Comment by PhilETaylor** [comment]
You might also want to fix this, when enabling your template and visiting the frontend:

<img width="719" alt="Screenshot 2021-05-31 at 19 47 08" src="https://user-images.githubusercontent.com/400092/120231320-09568b80-c249-11eb-857a-989ae62ffab0.png">

**Comment by PhilETaylor** [comment]
The root problem is logging in Joomla 4... the following is called, which kills Joomla on 128Mb memory_limit

```
// Get the current call stack and back trace (without args to save memory).
$this->callStack = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
```

**Comment by cloudfaction** [comment]
guys thank you so much. i will close this for now, i can move further with your valued tips! It's mainly the google fonts i load in the option boxes, i will fix that issue. thank you again!

**Comment by brianteeman** [comment]
there are other ways to do it if you really want to list all google fonts. Your current method is not sustainable as it will always be out of date as google add and remove fonts.
