### ISSUE TITLE
[4.0] Atum: Changing hue value, module-position-colour stay same

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34307]
### What needs to be fixed
Go to `System`> `Administrator Template Styles` and change the hue value for the dark template colour (i used 89).

In modules the position-colour stay same:

> ![image](https://user-images.githubusercontent.com/78906980/120194884-786aba80-c21e-11eb-9354-25313839a3ea.png)

### Why this should be fixed

At `Menu` (multilingual site) the colour change.

Changed template style |  Default template style
--- | ---
![image](https://user-images.githubusercontent.com/78906980/120194617-1c079b00-c21e-11eb-9b23-3e885a767f65.png) | ![image](https://user-images.githubusercontent.com/78906980/120196517-3b9fc300-c220-11eb-81e5-b9cf310ae925.png)

### How would you fix it
Don't know.

### Side Effects expected
Don't know.

**Comment by himanshu007-creator** [comment]
Confirmed the issue👍🏽

**Comment by brianteeman** [comment]
the module position badges use standard bootstrap classes eg bg-info which use specific colors 
the badge in the menu uses a variable for the colour so it is impacted by the hue settings

**Comment by ghost** [comment]
Thanks @brianteeman for the info. Can't the module position badge 

1. also use a variable for colour like in the menu or 
2. both use the standard bootstrap class as both shows infos (one about position, the other show in which menu is the default page for the language)?

**Comment by brianteeman** [comment]
I am explaining the reason why so that you (or others) can make a change

**Comment by ghost** [comment]
Thanks @brianteeman now i understand. I'm sorry, i cannot do changes, hopefully another will do.

**Comment by pinak3748** [comment]
I have made the changes but want to make sure that it's right and should we change the color of text and buttons [new, option] also or what?

![aaa](https://user-images.githubusercontent.com/59458280/127119971-95901e23-5327-416b-a033-85f80488b0e3.jpg)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34923 . Thanks in advance.
