### ISSUE TITLE
[4.0] Welcome to Joomla message

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34304]
The post installation "welcome to Joomla" message has a link to the forum
![image](https://user-images.githubusercontent.com/1296369/120163888-e2b93600-c1f1-11eb-9e66-35a10969d20b.png)

Currently it links to a joomla 3 board
![image](https://user-images.githubusercontent.com/1296369/120163964-f6fd3300-c1f1-11eb-9202-3beeaa5a1fe0.png)

Proposal - ask the global forum moderators to add a new forum for J4 that can be linked to - or just make it a generic forum link in the message

@pe7er @wilsonge

**Comment by pe7er** [comment]
Thanks @brianteeman 
We'll create a J4.x forum board when the stable version is released.

**Comment by brianteeman** [comment]
@pe7er thats a chicken and egg situation. We can't update the link in core until the link is created in the forumand if you dont create the forum link until joomla 4 is released ....

**Comment by zero-24** [comment]
> Thanks @brianteeman 
> We'll create a J4.x forum board when the stable version is released.

Could that forum be created but set to hidden when the policy is to not publish it before? This would allow us to link but not to collide with the existing rule.

Within our german forum thats what we did. We also created an "Joomla 4 pre releases forum" thats live now while the others are created but hidden.

**Comment by pe7er** [comment]
I'll find a solution with the Mod team.

**Comment by ooffick** [comment]
The page is created in the forum and we will see that we create a pull request so that the new forum link will be added.

**Comment by brianteeman** [comment]
any problems creating the pr please post back

**Comment by brianteeman** [comment]
Thansk

**Comment by pe7er** [comment]
Thanks @ooffick + @brianteeman
