### ISSUE TITLE
[4.0] Can "Global Options"  look like "Install from Web"?

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34305]
### What needs to be fixed
Its hard to see in `Options` which options a user is in comparing to the layout of `Install from Web`:

Hard | Easy
--- | ---
![Screenshot_2021-05-31 Template Options - View the Homepage - Administration](https://user-images.githubusercontent.com/78906980/120176146-3b46fe00-c207-11eb-80de-b8f8af07ad26.png) | ![Screenshot_2021-05-31 Extensions Install - View the Homepage - Administration](https://user-images.githubusercontent.com/78906980/120176170-426e0c00-c207-11eb-9df5-a6b4cf1e74b0.png)

### Why this should be fixed
Easier to see what option a user is in and similar layout.

### How would you fix it
Don't know.

### Side Effects expected
Don't know.

**Comment by brianteeman** [comment]
Yes they can (or something similar) it's only css and they should because as it is right now its an accessibility failure as you discovered yourself

**Comment by brianteeman** [comment]
please test #34310

**Comment by alikon** [comment]
closing please test  #34310
