### ISSUE TITLE
[4] Dropdown truncated on home dashboard

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34317]
Safari on mac tested. 

https://user-images.githubusercontent.com/400092/120239141-91db2900-c255-11eb-8637-745b5a76d65c.mp4

**Comment by dgrammatiko** [comment]
- Tweaking the `z-index` of the dropdowns should fix this but needs caution as it could break other instances.
- Another approach `min-height` for the cards to ensure dropdowns open inside the card
- Something else

**Comment by PhilETaylor** [comment]
Im too scared to attempt those... :)

**Comment by dgrammatiko** [comment]
But CSS is not a real programming language therefore you can't break it 🤣 (sarcasm)

**Comment by PhilETaylor** [comment]
Thats ok cause Im not a real programmer either... Im just an idiot bumbling his way around...

**Comment by dgrammatiko** [comment]
So am I, therefore, I'm calling @ciar4n who knows the solution here

**Comment by ciar4n** [comment]
This should do it... https://github.com/joomla/joomla-cms/pull/34332
