### ISSUE TITLE
[4] alert warning yellow gulp

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34322]
Something changed recently to the colours of the yellow in the alert warning which makes it very very hard on the eyes.

Furthermore it was only implemented to one type of warning and not the other. See the difference between a div with `alert alert-warning` and a `joomla-alert` custom element 

If we are keeping this glaring in-your-face-and-painful-for-my-eyes yellow alert then it should be implemented consistently. 

<img width="1135" alt="Screenshot 2021-05-31 at 23 05 16" src="https://user-images.githubusercontent.com/400092/120245357-d15d4180-c264-11eb-8609-d2fed9a845dd.png">
<img width="1189" alt="Screenshot 2021-05-31 at 23 04 49" src="https://user-images.githubusercontent.com/400092/120245358-d3270500-c264-11eb-8199-caf5979ba022.png">

**Comment by PhilETaylor** [comment]
The accessibility contrast is 1.72 which fails.

**Comment by PhilETaylor** [comment]
Needs to be `#976c0c` to be AA with a ratio of 4.5 or for AAA 7.0 it needs to be a text color of `#715109`

**Comment by ghost** [comment]
> Something changed recently to the colours of the yellow in the alert warning

By #34246

**Comment by PhilETaylor** [comment]
PR https://github.com/joomla/joomla-cms/pull/34328
