### ISSUE TITLE
[4.0] "Help"-Sidebar should have same layout as similar sidebars

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34327]
### What needs to be fixed

Open in Backend sidebar on help:

> ![image](https://user-images.githubusercontent.com/78906980/120285852-f4680f80-c2bd-11eb-9488-383e6b1f8677.png)

### Why this should be fixed
Similar sidebars like in `Global Options` and `Install from Web` are easier for user to see, at which menu they are.

### How would you fix it
Same CSS-changes like in #34310 or maybe all three sidebars can use the same CSS?

### Side Effects expected
I hope not.

**Comment by brianteeman** [comment]
it just needs the class "item" adding to the links
