### ISSUE TITLE
[4.0] Redirect-Plugin: After enable in Modale reload the page

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34333]
#### 1. After click on `Redirect System Plugin` 

![image](https://user-images.githubusercontent.com/78906980/120321650-d7463780-c2e3-11eb-9571-fcd4ff201ab6.png)

#### 2. a modal open to enable the plugin:

![image](https://user-images.githubusercontent.com/78906980/120321822-0a88c680-c2e4-11eb-8471-6f2886d673db.png)

### Describe the solution you'd like
A message similar to other components that the plugin is enabled. This happen now if user reload the page:
![image](https://user-images.githubusercontent.com/78906980/120322417-aca8ae80-c2e4-11eb-8881-6679a025267f.png)

**Comment by PhilETaylor** [comment]
This because you are doing all the work in the model but the parent page doesn't know to reload automatically after you save and close the modal...

**Comment by dgrammatiko** [comment]
> but the parent page doesn't know to reload automatically after you save and close the modal...

There's an event `modal.bs.close` (or something like that) that is fired when the modal closes so you can listen for that event on the specific modal and just do a `location.reload();`. Has a drawback that it will reload even if cancel was pressed but getting the state from the iframe is not something that the project has a known way to deal with it...

**Comment by brianteeman** [comment]
We already do something like this on the admin dashboard when you add a new module

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/blob/0d616016e4eccfd293e4b314dec00d241b544e1a/build/media_source/com_cpanel/js/admin-add_module.es6.js#L61-L73
