### ISSUE TITLE
Update Sites filtering breaks when changing the "Select Download Key" dropdown.

### ISSUE THREAD

**Issue by nikosdion** [joomla/joomla-cms#34353]
### Steps to reproduce the issue

* Go to System, Update Sites
* Click the “- Select Download Key -” dropdown and select “Download Key Support”.
* After the page reloads click the same dropdown and select “- Select Download Key -”.

### Expected result

All Update Sites listed.

### Actual result

No Update Sites listed.

### System information (as much as possible)

Confirmed on PHP 7.4 and 8.0. The environment seems to be irrelevant, though.

### Additional comments

This is a bug in code I had contributed in 2019, namely https://github.com/joomla/joomla-cms/blob/2b70fb087cd7d743b992db20a71412639d1450ef/administrator/components/com_installer/src/Model/UpdatesitesModel.php#L666

The switch statement above should be setting $supportedIDs to null and the noted line should have a check for a non-null result.

I will submit a PR shortly.

**Comment by sozzled** [comment]
Confirmed.  Thanks.

**Comment by nikosdion** [comment]
Here's the Pull Request https://github.com/joomla/joomla-cms/pull/34357

**Comment by zero-24** [comment]
We can close here while we have the PR right?

**Comment by nikosdion** [comment]
BTW, you don't have to close my issues when I submit a PR. I always include the text "closes blah-blah" as the first thing in my PR description so that the issue is auto-closed by GitHub when you merge the PR. IMHO it makes it easier for people to see if an issue is known — most people will search the issues but almost nobody looks into open PRs.

**Comment by PhilETaylor** [comment]
> BTW, you don't have to close my issues when I submit a PR. I always include the text "closes blah-blah" as the first thing in my PR description so that the issue is auto-closed by GitHub when you merge the PR.

The Jersey Way™️ - To be fair Symfony do that too.. 

This was also a duplicate of https://github.com/joomla/joomla-cms/issues/34132#issuecomment-853175031 which you missed before opening this :)

**Comment by nikosdion** [comment]
Yeah, I'd missed your issue. It didn't come up when I searched. I believe you called it Download ID, Joomla calls it Download Key and I searched for the latter. Nothing immediately popped up so I filed an issue :)

**Comment by PhilETaylor** [comment]
ah :) haha

**Comment by nikosdion** [comment]
If Microsoft is hearing, we'd like some AI in the issues search so it can figure out subtle differences in terminology to avoid awkward situations like this... 😛
