### ISSUE TITLE
[4.0] Update-Problem with Dutch-Language

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34356]
### Steps to reproduce the issue
Can someone please guide me to the right place, i couldn't find where to report: The Dutch language pack reports an update, in `Extensions: Update` i got:

![image](https://user-images.githubusercontent.com/78906980/120444550-02826280-c388-11eb-9238-2ef777579deb.png)

Update is reported as successfully, on Home dashboard update is reported again.

**Comment by zero-24** [comment]
@MartijnMaandag is the contact listed on the downloads page: https://downloads.joomla.org/language-packs/translations-joomla4

@MartijnMaandag could it be that you use crowdin where the update path is not set correctly to the 4 list xml?

**Comment by ghost** [comment]
Thanks @zero-24, now i know where to look. Can i close the issue or let it open for @MartijnMaandag?

**Comment by MartijnMaandag** [comment]
This is the first language available, I will ask someone to have a look at this.

**Comment by wilsonge** [comment]
@MartijnMaandag the reason the update shows is because the pack needs to be tagged 4.0.0-rc1.1 in the XML - i'm unsure why there's the extension.xml issue - ill try and look later this evening if I have time.

**Comment by infograf768** [comment]
Another issue is that crowdin J4 does NOT add the correct update server in the package xml.

```
<updateservers>
		<server type="collection" priority="1" name="Geaccrediteerde Joomla! vertalingen"/>
	</updateservers>
```

See https://github.com/joomlagerman/joomla/pull/1832

**Comment by ghost** [comment]
reopen cause of discussion i don't expected.

**Comment by infograf768** [comment]
We need the subversion number in the xml (the .1, then .2, etc.) for the cron job to propose an updated corrected pack concerning the same J version and display the pack version correctly in J UI

<img width="929" alt="Screen Shot 2021-06-02 at 12 11 39" src="https://user-images.githubusercontent.com/869724/120463007-c0631c00-c39b-11eb-8710-cbb4588b3804.png">

btw, we can't install anymore the Persian pack from joomla UI which means testers who want to test RTL have to download its j3 version and install via extensions installer.
http://joomlacode.org/gf/download/frsrelease/21015/166076/fa-IR_joomla_lang_full_3.9.27v1.zip

**Comment by ghost** [comment]
@infograf768 i got today two languages (dutch, german).

**Comment by infograf768** [comment]
Yes, because these were the only J4 ones added in the new repo. French above is installed via extensions install.

**Comment by MartijnMaandag** [comment]
@wilsonge I tried to update the languagepack but when i upload a version nr2 I do get an error on upload:
"Save failed with the following error: Release ZIP has already been created in the release system."

**Comment by infograf768** [comment]
@MartijnMaandag 
you can post issues here
https://github.com/joomla-extensions/pkg_languagepack/issues

**Comment by zero-24** [comment]
> @wilsonge I tried to update the languagepack but when i upload a version nr2 I do get an error on upload:
> "Save failed with the following error: Release ZIP has already been created in the release system."

What exact version did you choose? Did you increase the 'language pack version'?

**Comment by MartijnMaandag** [comment]
I did change the releasenr in 2 on "Specify the language pack version for this Joomla Version"

**Comment by zero-24** [comment]
Hmm i have just checked that only the version 4.0.0-rc1.1 is uploaded seems to be an issue here: https://github.com/joomla-extensions/pkg_languagepack/blob/8dd6b025f6df44fbd4e80bf865d0a8e189f424ed/com_languagepack/site/models/newpack.php#L259-L298

On a quick look it looks correct but it seems it the check for the "language pack version" is not working correctly. So that is the thing @wilsonge can take a look later.

**Comment by MartijnMaandag** [comment]
@wilsonge What I see now is that the <updateservers> information is not exported from Crowdin into the export. (You can see it in the current download of the Dutch language. (These are grayed items)

**Comment by infograf768** [comment]
@MartijnMaandag 
your package version is

```
<version>4.0.0.rc1.1</version>
```

instead of 
```
<version>4.0.0-rc1.1</version>
```

**Comment by MartijnMaandag** [comment]
Yes i know, but i can't upload a new release.

**Comment by wilsonge** [comment]
@MartijnMaandag are you able to send me the pack on glip please. i have a test fix here https://github.com/joomla-extensions/pkg_languagepack/pull/50 - but want to debug it in case there are any issues with the upload

**Comment by MartijnMaandag** [comment]
I did share v2: https://www.joomlacommunity.nl/downloads/joomla-4

**Comment by wilsonge** [comment]
Thankyou. I've pushed the fix to the site now and uploaded your pack. should work if/when you need to push a v3 pack!

**Comment by ghost** [comment]
Close the issue as it is resolved. Thanks all.
