### ISSUE TITLE
[4.0] Non default path's causes problems using the media manager

### ISSUE THREAD

**Issue by pjdevries** [joomla/joomla-cms#34358]
### Steps to reproduce the issue

Change both path's of the Media Manager configration, i.e. 'Path to Files Folder' and  'Path to Images Folder'.

Open Media Manager.

### Expected result

A list of files in folder 'Path to Files Folder', if there are any, or an empty folder otherwise.

### Actual result

The result depends on proper configuration of the `FileSystem - Local` plugin. If no directory is chosen, which is the default, the plugin returns `[{"directory": "images"}]` and the Media Manager shows nothing.

### System information (as much as possible)

A fresh Joomla! 4.0 installation, or at least with unaltered  `FileSystem - Local` plugin configuration.

### Additional comments

My suggestion is to return Media Manager's 'Path to Files Folder' setting from `FileSystem - Local` as a default and _not_ `[{"directory": "images"}]`.

**Comment by richard67** [comment]
@pjdevries Will that be solved, too, with your PR #34314 ? If so, this issue can be closed.

**Comment by pjdevries** [comment]
@richard67 Unfortunately this will not be solved with PR  #34314. It's a minor fix though, which I don't mind doing if that's o.k.

**Comment by richard67** [comment]
> ...  which I don't mind doing if that's o.k.

@pjdevries You mean you wanna fix it with another PR? That would be very o.k.

**Comment by pjdevries** [comment]
@richard67 Yeah, that's what I meant. I'll do it right away.

**Comment by alikon** [comment]
please test #34364
