### ISSUE TITLE
[4.0] Issue with drag & drop ordering

### ISSUE THREAD

**Issue by nozaro33** [joomla/joomla-cms#34369]
Hi, I had noticed this bug in beta 8, but given it was nightly build I wasn't sure if there was something wrong with my build so didn't report it. I have tested this issue on a site that was updated from beta, and also a clean install of RC1. 
You can drag and drop to change ordering on categories (appears to be fine when categories are all root) 

But when you have more category trees, (various levels) Sometimes it doesn't work and js console will show an error.  "Cannot read property 'value' of undefined".   Once this error appears, it can kill some other functions on the page. (I can't use batch unless I refresh page, See video below. )

I've seen this happen also on menu and plugin pages, but  I'm not sure how to reproduce so I won't put it here for now.

### Steps to reproduce the issue

Create multiple categories with various levels.
Try to change ordering of categories
(See video below)

### Expected result

Should work as expected

### Actual result

Will appear "Cannot read property 'value' of undefined" in console error resulting in unable to change order, when category have multiple levels 

### System information (as much as possible)
Joomla 4 RC1
Mysql 5.7.26
PHP 7.4.2

https://user-images.githubusercontent.com/25219289/120580250-6aee4400-c45b-11eb-937d-3e733bbd6864.mp4

**Comment by ghost** [comment]
If this is the wrong place please tell me, will open a new issue*).

Similar issue in administrator-modules: Reordering `User Status` before `Frontend Link` seems to work, after page-reload the ordering is lost.

![1](https://user-images.githubusercontent.com/78906980/120587257-51d29c80-c435-11eb-93e9-9f70525b4657.gif)

*) no error in browser-console so i thinks its another, but similar issue.

**Comment by joomdonation** [comment]
I think the issue is the same. I think I/we will have to review the re-ordering logic implemented on the PR https://github.com/joomla/joomla-cms/pull/33937. Look like we are having issues with re-order grouped items.

**Comment by joomdonation** [comment]
@dgrammatiko @Fedik Does Dragula allow drag nested elements? From what I see right now, when we drag and parent category to new position, only that parent category is moved, not it's child categories ?

**Comment by joomdonation** [comment]
@nozaro33 @sandramay0905 Could you please help testing the PR https://github.com/joomla/joomla-cms/pull/34375 ? Thanks !

**Comment by nozaro33** [comment]
@joomdonation  Hey Tuan, going to bed soon will test tomorrow morning! Thanks!

**Comment by joomdonation** [comment]
Great. Thanks @nozaro33

**Comment by Fedik** [comment]
> Does Dragula allow drag nested elements? 

sorry for delay,
I think it only would work if the children located in the same container with parent, in the same div element,
but we have each item (parent and child) as own element

**Comment by dgrammatiko** [comment]
> but we have each item (parent and child) as own element

Yes and also we have a data attribute that indicates the parent of each element. Anyways @joomdonation figured it out

**Comment by joomdonation** [comment]
@dgrammatiko @Fedik Actually, I can only fix the ordering issue. The issue with drag and drop nested element is still there. You can see the issue here https://github.com/joomla/joomla-cms/pull/34375#issuecomment-854366900 (In J3, we handles it better)

**Comment by dgrammatiko** [comment]
> In J3, we handles it better

What's the behaviour in J3? Reload?

**Comment by joomdonation** [comment]
> What's the behaviour in J3? Reload?

Somehow, in J3, when we drag and drop the parent categories, it's the children categories (actually the whole category tree are moved to new position). And no, it is not reload.
