### ISSUE TITLE
[4.0] Help pages blocked

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34367]
When you click on the help button top right of most pages then the docs site opens in a popup new browser window. BUT when you click on the help menu item bottom left then the help pages are opened in an iframe.

This issue is about the iframe use not the popup.

If you check the links on the page you will see they are all being _proxied_ through help.joomla.org however the links in the footer are not 

![image](https://user-images.githubusercontent.com/1296369/120560914-8b86b180-c3fb-11eb-8e52-e69ff8d1791d.png)

The first two (highlighted above) are direct to the docs site - but you cannot open the docs site links
![image](https://user-images.githubusercontent.com/1296369/120561019-ba048c80-c3fb-11eb-97f0-c39af834cc17.png)

You also cannot open the link to the osm site
![image](https://user-images.githubusercontent.com/1296369/120561093-d86a8800-c3fb-11eb-8869-19077b1ba8a9.png)

I believe this is due to the iframe blocking code on those two sites but it may also be something to do with how that block is generated. 

I don't know if this is a CMS issue or an Operations issue so I am crossposting it - please close it if this is the wrong place,

**Comment by zero-24** [comment]
The joomla-websites issue is noted and will be worked on. Closing here.
