### ISSUE TITLE
[4.0] Subforms Repeatable -> new fields always show at bottom as opposed to below existing field

### ISSUE THREAD

**Issue by nozaro33** [joomla/joomla-cms#34374]
So I'm not sure if this is by design, but it's not ideal UX. Plus the behavior is different from Joomla 3 so I'll assume it's a bug, if not then please close this issue.

When you use subforms -> repeatable.
Whenever you add use the + button from an existing field, you expect the new field to pop below the existing field you just clicked.  Right now, regardless of where you press the + button, the new field(s) all appear on the bottom, which can result in confusion that the button isn't working if the number of fields exceed your browser height.  In Joomla 3 the repeatable fields work as expected, where a new one "drops" below the existing field that you clicked "+" on.
I hope I make sense!

### Steps to reproduce the issue

Create a subform in custom fields,
and use it in Article editor.

### Expected result

New empty field in subform should show below the existing field if you use the +  of said existing field

### Actual result

Every new field is added at the bottom.

### System information (as much as possible)

Joomla 4 RC1
Mysql 5.7.26
PHP 7.4.2

### Additional comments

<img width="1229" alt="Screen Shot 2021-06-03 at 17 49 43" src="https://user-images.githubusercontent.com/25219289/120625472-4ebac900-c494-11eb-8935-3c2f0733d1a1.png">

**Comment by brianteeman** [comment]
confirmed

**Comment by Fedik** [comment]
broken somewhere there #28753 or #28695
need a closer look

**Comment by Fedik** [comment]
please test #34402
