### ISSUE TITLE
[4.0] mod_popular and mod_latest emptystate

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34379]
The query for articles in these two modules intentionally does not include archived articles.

However when calculated the emptystate the query must include archived.

To test. Change the state of all articles to archived and check these two modules. They are displaying  "No Articles have been created yet." which is not correct

**Comment by PhilETaylor** [comment]
LMAO And this is why my first PR was right... but [you opposed it.](https://github.com/brianteeman) to the point I changed it.

**Comment by brianteeman** [comment]
Where? There is nothing in that link remotely related

**Comment by PhilETaylor** [comment]
> Where? There is nothing in that link remotely related

Im sorry you feel that way... but once again you are wrong. 

if you had not opposed it the text would have remained 

```
"You do not have any popular articles yet"
"You do not have any recent articles yet" 
```

The "Empty State" of these modules is not "There are no articles, you have not ever created any"... That is the empty state of the component... These modules are not aware of the FULL table of content, they are only aware if there is something to show or not... its not a real "empty state" like the "empty state" is defined for the extensions, it more a "text string when there is no items to show"... and therefore the original language like those below is "more correct" and that is what https://github.com/joomla/joomla-cms/pull/33472 proposed.

"You do not have any popular articles yet"
"You do not have any recent articles yet"

**Comment by PhilETaylor** [comment]
And that was the whole purpose originally of the `textSuffix`

```
'textSuffix' => '_RECENT',

'textSuffix' => '_POPULAR',
``

Which again, you just removed earlier today /facepalm

**Comment by brianteeman** [comment]
Sorry but the text of the string is nothing to do with the issue. An article can be popular and still be archived. An article can be recently created and still be archived.

**Comment by PhilETaylor** [comment]
Even before empty state, these modules have NEVER shown archived items...

**Comment by PhilETaylor** [comment]
>  An article can be popular and still be archived. An article can be recently created and still be archived.

Yes, but Even before empty state, these modules have NEVER shown archived items...

Even before empty state, these modules would have shown nothing...

**Comment by PhilETaylor** [comment]
> To test. Change the state of all articles to archived and check these two modules. They are displaying "No Articles have been created yet." which is not correct

So what exactly is your EXPECTED behaviour? 

Maybe 

```
"You do not have any non-archived popular articles yet"
"You do not have any non-archived recent articles yet" 
```

**Comment by ReLater** [comment]
Maybe a good chance to think about a take-back of these strange emptystate codes from at least modules; with additional DB queries and JLayouts for nothing than a message.

**Comment by PhilETaylor** [comment]
> with additional DB queries

Empty State for modules DOESN'T run any additional DB Queries at all. 

Empty State for Extensions ONLY runs a single additional DB query when NO ITEMS are about to be shown. 

On a normal site, with data in the db, Empty State Design DOESN'T have any overhead whatsoever ever.

Until @brianteeman answers the question, "what exactly is your EXPECTED behaviour" there is nothing that can be achieved on this issue.
