### ISSUE TITLE
[4.0 ] Admin: "Recently Added Articles" show Language-Constant

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34370]
### Steps to reproduce the issue

Fresh installation of todays nightly build using launch.joomla.org:

![image](https://user-images.githubusercontent.com/78906980/120584054-90655880-c42f-11eb-9493-b4fb9efdde1a.png)

### Expected result

Value of Language-Constant is shown.

### Actual result

Language-Constant is shown.

### System information

![image](https://user-images.githubusercontent.com/78906980/120584330-16819f00-c430-11eb-82aa-7273e82590bb.png)

**Comment by brianteeman** [comment]
Please test #34373

**Comment by ghost** [comment]
Close cause of pull request, thanks @brianteeman
