### ISSUE TITLE
[4.0] Drag'n'Drop a parent-category show children-categories only after page-refresh

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34389]
### Steps to reproduce the issue

Please see video:

![120749908-aba29780-c505-11eb-97c6-3d05927a03b3](https://user-images.githubusercontent.com/78906980/120753204-1c987e00-c50b-11eb-824a-7253da5e66a4.gif)

### Expected result

After drop of parent- the children-categories are shown like the parent.

### Actual result

After drop of parent- the children-categories are not shown below the parent.

### System information (as much as possible)

![image](https://user-images.githubusercontent.com/78906980/120753502-8ca70400-c50b-11eb-8454-8c6c6133a245.png)

### Additional comments
The issue come up at #34375

**Comment by joomdonation** [comment]
@dgrammatiko @Fedik This is the question/issue I asked you two yesterday. Would be nice if we can come up with a solution (although I'm unsure if it is possible with the library we are using)

**Comment by Fedik** [comment]
I wonder for what  this option
https://github.com/joomla/joomla-cms/blob/ad06aa48f235dd09a8ca7181cf48f51ad0f6a291/build/media_source/system/js/draggable.es6.js#L36-L37

seems does not make any difference

**Comment by joomdonation** [comment]
Guess that's used to prevent dragging an element from one group to a different group only. We do not have a way to move the whole group (parent and it's children) to new position.

**Comment by dgrammatiko** [comment]
@Fedik @joomdonation please read the commend at the beginning of the conditional, this is the fallback for B/C.

**Comment by joomdonation** [comment]
@dgrammatiko I think we understand that. @Fedik wanted to know if that could be used to solve the issue you are having here.

Do you think we can have a solution for dragula to handle drag and drop the whole group as we are having in J3?

**Comment by dgrammatiko** [comment]
FWIW at the drop event if the dragged element was a category parent I guess we could move all the children after it.
pseudocode:
```js
// el the dragged element
Array.from(document.querySelectorAll(el.dataset.nested).reverse().filter(l => l !== el).map(
// move them under el...
)

```

**Comment by joomdonation** [comment]
I was thinking the same but that's beyond my JS skill :(.

**Comment by Fedik** [comment]
please test #34584
