### ISSUE TITLE
[4.0][a11y] alert-warning has bad colour contrast in template styles

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#34381]
### Steps to reproduce the issue

Open Template Styles for Cassipeia

### Expected result
The note has colour contrast as alert-message

### Actual result
Bad colour contrast in alert-warning
![grafik](https://user-images.githubusercontent.com/1035262/120666543-f9c78480-c48c-11eb-830e-f1a7e8d5179e.png)

**Comment by richard67** [comment]
@chmst Can you check with current 4.0-dev? There has been merged PR #34328 some half an hour ago, which should fix that.

**Comment by richard67** [comment]
I've just checked with current 4.0-dev and can confirm the issue has been solved with PR #34328 some half an hour ago. Feel free to re-open if this is wrong.
