### ISSUE TITLE
global-menu-options branch

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#34382]
Hey @chmst 

Did you, on purpose, 2 days ago push the branch `global-menu-items` to the official project git repo? 

I assume this was a mistake that can be deleted?

https://github.com/joomla/joomla-cms/branches

Kindest regards 
Phil

**Comment by richard67** [comment]
@PhilETaylor I've clarified with @chmst . It was a mistake. I've just deleted the branch. Thanks for reporting.

**Comment by PhilETaylor** [comment]
Ta
