### ISSUE TITLE
[4.0] Unexpected white space

### ISSUE THREAD

**Issue by max123kl** [joomla/joomla-cms#34384]
### Actual result
I am not sure if this unexpected white space at the end of the language string is a problem and needs to be corrected.

Found in:
`administrator/language/en-GB/joomla.ini`  Line 361

`JGLOBAL_BLOG_CLASS_NOTE_DESC ="You can add...`

### System information (as much as possible)
current 4.0-dev branch

**Comment by brianteeman** [comment]
best to fix it

**Comment by max123kl** [comment]
do you want me to do a PR?

**Comment by chmst** [comment]
Closing as there is a pr
