### ISSUE TITLE
[4.0] Administration - calendar

### ISSUE THREAD

**Issue by rjharishabh** [joomla/joomla-cms#34393]
### Steps to reproduce the issue
Check any calendar
for e.g. Contents > Articles > Try to edit any article  > Go to Publishing Tab > check the calendar here

#### Issue 1 
Hover on dates - date disappears (reason: color is set to white)
#### Issue 2
Time icon missing

### Expected result
Date should not disappear on hover
Time icon should be visible

### Actual result
Date disappears on hover
Time icon missing

![calendar](https://user-images.githubusercontent.com/61203226/120779274-884b0d00-c544-11eb-9658-47908cbeeb11.gif)

### System information (as much as possible)
PHP 8.0.6
MySQLi 10.4.19-MariaDB
Chrome on Windows 10

pinging @ciar4n

**Comment by ghost** [comment]
Confirm issue; firefox / mac.

**Comment by brianteeman** [comment]
please test #34395

**Comment by rjharishabh** [comment]
Close with PR #34395
