### ISSUE TITLE
[4.0] Unificaton of language string JGLOBAL_BLOG_CLASS

### ISSUE THREAD

**Issue by max123kl** [joomla/joomla-cms#34397]
### Actual result
With PR #32943, the following strings were changed (among others):
`administrator/language/en-GB/joomla.ini`
JGLOBAL_BLOG_CLASS="Article Class"
JGLOBAL_BLOG_CLASS_LEADING="Leading Article Class" 

However, the same strings kept their former values in the following file.
`api/language/en-GB/joomla.ini`
JGLOBAL_BLOG_CLASS="Blog Class"
JGLOBAL_BLOG_CLASS_LEADING="Blog Class (Leading Articles)"

### System information (as much as possible)
current 4.0-dev branch

### Additional comments
Shouldn't the second file be modified as well?

**Comment by brianteeman** [comment]
yes please
