### ISSUE TITLE
[4.0] Unifying the same language string in three joomla.ini files

### ISSUE THREAD

**Issue by max123kl** [joomla/joomla-cms#34390]
### Expected result
The same language string should be the same in three joomla.ini files, isn't it?
However, there is a small difference in one file (the differences are shown here in bold, only for demonstration).

### Actual result
`/administrator/language/en-GB/joomla.ini`
JGLOBAL_FIELD_SHOW_BASE_DESCRIPTION_DESC="Show description of the top level category or alternatively replace with the text from the description field found in the menu item. If using Root as **the Top Level** category, the description field has to be filled."

`/api/language/en-GB/joomla.ini`
JGLOBAL_FIELD_SHOW_BASE_DESCRIPTION_DESC="Show description of the top level category or alternatively replace with the text from the description field found in the menu item. If using Root as **a top level** category, the description field has to be filled."

`/language/en-GB/joomla.ini`
JGLOBAL_FIELD_SHOW_BASE_DESCRIPTION_DESC="Show description of the top level category or alternatively replace with the text from the description field found in the menu item. If using Root as **a top level** category, the description field has to be filled."

### System information (as much as possible)
current 4.0-dev branch

### Additional comments
The most recent version is the one in the `/administrator/language/en-GB/joomla.ini` file. That string was last modified 3 months ago, the ones in the other files are much older.

Which is the preferred version?
If the latest version is used, then should "Top Level" be written in lower case or, if it is to be emphasised, in quotes?

**Comment by richard67** [comment]
To me the lowercase in the frontend and the API language files looks more correct than the uppercase in the backend language file, even if that is newer. @brianteeman What do you think?

**Comment by chmst** [comment]
for me it is ... using root as the top level .... everythin lowercase - but it is surely a decison of native speakers.

**Comment by max123kl** [comment]
what about "a" and "the"?

**Comment by richard67** [comment]
I‘d say like @chmst , lowercase with „the“, or maybe without any „a“ or „the“, so it’s just „as top level category“. But we are both not native speakers.

**Comment by max123kl** [comment]
me too

**Comment by brianteeman** [comment]
If only one item can be the top level then it should be the not a
no need to capitalise

**Comment by max123kl** [comment]
OK, I will open a PR

**Comment by richard67** [comment]
Closing as having a pull request.
