### ISSUE TITLE
[4.0] Translation doesn't work for layouts [tpl_cassiopeia.sys]

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34405]
### Steps to reproduce the issue
In 4.0 Beta 7, alternate layouts + corresponding language constants were added (https://github.com/joomla/joomla-cms/pull/33978).

In file `SITE/language/en-GB/mod_menu.sys.ini`: 

```
MOD_MENU_LAYOUT_COLLAPSE-DEFAULT="Collapsible Default Menu"
```

In file `SITE/language/en-GB/tpl_cassiopeia.sys.ini`:

```
TPL_CASSIOPEIA_MOD_MENU_LAYOUT_COLLAPSE-METISMENU="Collapsible Dropdown"
TPL_CASSIOPEIA_MOD_MENU_LAYOUT_DROPDOWN-METISMENU="Dropdown"
```

The fact is that the translation of 2 lines from file `tpl_cassiopeia.sys.ini` is not pulled up. Something is wrong. I didn't understand why, I just report it. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/120854309-a2590f80-c585-11eb-988c-34fb10c47a18.png)

**Comment by brianteeman** [comment]
To be 100% certain can you please confirm that yourlanguage/tpl_cassiopeia.sys.ini contains those two lines and translated to your language

**Comment by Kostelano** [comment]
Of course. These constants are.

**Comment by chmst** [comment]
@Kostelano I just has a similiar issue - the problem was that somewhere in the language file (not in the non-translated strings) an error occurred. In my case it was a "." after another language string, which blocked the loading of the following translations. 

Could you please check your language files if there are somewhere two "" or unexpected spaces or corrupt lines?
Or post the lanuage file here

**Comment by Kostelano** [comment]
There is no problem in the localization file.

I just copied the en-GB file into the ru-RU directory, renaming the strings like this:

```
TPL_CASSIOPEIA_MOD_MENU_LAYOUT_COLLAPSE-METISMENU="Collapsible Dropdown444"
TPL_CASSIOPEIA_MOD_MENU_LAYOUT_DROPDOWN-METISMENU="Dropdown4444"
```

Everything is the same, line feed is NOT pulling up.

**Comment by Kostelano** [comment]
Collected the package. Please test it yourself. Thank you. 

ru-RU_joomla_lang_full_4rc1.1-a.zip
https://drive.google.com/file/d/1MSf7Mi9GIOJH0gd_x6f7UIZ90F5zMtpx

**Comment by brianteeman** [comment]
please test #34409 
![image](https://user-images.githubusercontent.com/1296369/120863492-90c23880-c582-11eb-8a11-ff6131698bf0.png)

**Comment by brianteeman** [comment]
@chmst thanks for the tip
