### ISSUE TITLE
[4.0] System notification is hidden but should be visible

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34404]
### Steps to reproduce the issue
File `administrator/language/en-GB/plg_system_updatenotification.ini` has lines:

```
PLG_SYSTEM_UPDATENOTIFICATION_POSTINSTALL_UPDATECACHETIME="The Joomla! Update Notification will not run in this configuration"
PLG_SYSTEM_UPDATENOTIFICATION_POSTINSTALL_UPDATECACHETIME_ACTION="Set it back to the default setting (6 Hours)"
PLG_SYSTEM_UPDATENOTIFICATION_POSTINSTALL_UPDATECACHETIME_BODY="<p>In your Installer Configuration you have set the Option Update Cache (in Hours) to 0 this means that Joomla is not caching the Update. This means an email should be sent on every page visit but this is not possible. Please increase the value (6 is default) or confirm that the Joomla! Update Notification will never send you mails.</p>"
```

Hide all system notifications on the Post-installation Messages page. Go to the extensions settings and set the "Updates Caching (in hours)" parameter to 0. Go to the main page - there is no icon about an important system message in the toolbar.

Given that these system messages are generally important, the message counter should have changed by at least 1. This is what I consider to be wrong behavior and created Issue.

Now go to Post-installation Messages and hit the reset button. Hurray, now we finally have a message that says the wrong combination of parameters.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/120853385-375b0900-c584-11eb-98d8-acfbc8c6a627.png)

By the way, in the `PLG_SYSTEM_UPDATENOTIFICATION_POSTINSTALL_UPDATECACHETIME_BODY` constant, I would prefer to slightly change the ending of the phrase. Something like `... or disable the System - Joomla! Update Notification plugin, thereby confirming that there is no need to send Joomla update notifications. `

**Comment by brianteeman** [comment]
>  the way, in the PLG_SYSTEM_UPDATENOTIFICATION_POSTINSTALL_UPDATECACHETIME_BODY constant, I would prefer to slightly change the ending of the phrase. Something like ... or disable the System - Joomla! Update Notification plugin, thereby confirming that there is no need to send Joomla update notifications.

It is a deliberate decision not to explain how to do that

**Comment by Kostelano** [comment]
Interesting ... In the same file, but in a different notification:

```
To disable these emails, please unpublish the 'System - Joomla! Update Notification 'plugin in the Plugin Manager on your site.
```

**Comment by chmst** [comment]
@Kostelano is this still a valid issue?

**Comment by Kostelano** [comment]
Yes, sure. So far no one has solved it.

**Comment by Kostelano** [comment]
The problem is no longer relevant, since the plugin has been removed (transferred to tasks), and the mentioned functionality has been permanently removed. I'm closing.
