### ISSUE TITLE
[4.0] Menu Dashboard: Missing Space of "Home"-Icon

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34427]
### What needs to be fixed

In the menu-sideboard the space between text and home-symbol is different to the menu-dashboard:

![image](https://user-images.githubusercontent.com/78906980/120912903-7330c400-c693-11eb-9994-5e3135ac5679.png)

### Why this should be fixed

Space should be similar.

### How would you fix it
Don't know.

### Side Effects expected
I hope not.

**Comment by brianteeman** [comment]
Please test #34429

**Comment by ghost** [comment]
Closed because of pull request #34429
