### ISSUE TITLE
[4.0] Tags use "badge", Categories "btn"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34428]
### What needs to be fixed
Go to `index.php?option=com_tags&view=tags`, the list use `badge` for tagged items:

![image](https://user-images.githubusercontent.com/78906980/120915973-16d79f80-c6a7-11eb-84c7-8f69c0b5254f.png)

### Why this should be fixed
Categories use `btn` to show similar:

![image](https://user-images.githubusercontent.com/78906980/120916017-4686a780-c6a7-11eb-9528-0945f4dd063b.png)

### How would you fix it

Maybe there is a different meaning between badge ans button but for layout it should be look same. Like com_menus do also:

![image](https://user-images.githubusercontent.com/78906980/120916089-c90f6700-c6a7-11eb-9f79-0458f6f9f834.png)

**Comment by chmst** [comment]
The difference is: In com_tags, there is just a badge = css to make a number better visible. 

In categories, the numbers are links. Click on a number in the category overview and you will come to a articles overview (where you can see the number of his as small badges.

**Comment by ghost** [comment]
Thanks @chmst for your information. Do you know why tagged items are not links like in categories? The first times i clicked on it to see the tagged items and was surprised that it doesn't do this.

**Comment by brianteeman** [comment]
Because the tag could be applied to items in different components if I remember correctly

**Comment by ghost** [comment]
> Because the tag could be applied to items in different components

Ah, now i understand, thanks @brianteeman.
