### ISSUE TITLE
[4.0] Checkbox field displays empty text / value pair as checkbox

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#34437]
### Steps to reproduce the issue
Create a field of type checkboxes.
Add one or two  text / value pairs with content in text and value
Add another and let text and value empty.

![grafik](https://user-images.githubusercontent.com/1035262/120935309-67301b00-c702-11eb-9800-62171d4e3b19.png)

### Expected result
Empty text / value is ignored 

![grafik](https://user-images.githubusercontent.com/1035262/120935277-423ba800-c702-11eb-933f-0c0313bfabba.png)

### Actual result
For the empty text/value pair, a checkbox without label is displayed

![grafik](https://user-images.githubusercontent.com/1035262/120935142-a0b45680-c701-11eb-8418-930b2584f279.png)

**Comment by brianteeman** [comment]
should they be made required? or ignored and not saved

**Comment by chmst** [comment]
I would say required. Not sure if this makes difficulties with subforms, but this shpud be independent and  ignored and not saved would also be ok.

**Comment by brianteeman** [comment]
I dont know either just wanted to clarify ;)

**Comment by richard67** [comment]
I think the text and value fields should be required so it’s not possible to save with an empty text or value.

**Comment by AndySDH** [comment]
> I think the text and value fields should be required so it’s not possible to save with an empty text or value.

An empty value could actually still be useful as you may want an option (eg. in a List field) to not save a value in the database.
For example having a text "None" and a an empty value as the first option in the List dropdown could make sense.

However, the text part should indeed probably be required. An empty text doesn't make sense.

**Comment by brianteeman** [comment]
Please test #37138

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37138 . Thanks in advance.
