### ISSUE TITLE
com_menus.ini overrides JDEFAULT

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#34438]
### Steps to reproduce the issue

I cannot find an example in the core, it happens when developing a third-party extension.

Whenever a field's value is JDEFAULT in the context of a menu item (while setting up a view), the translation is 'Home' (in English) rather than 'Default'.

### Expected result

Translation of JDEFAULT should be 'Default' (in English)

### Actual result

Translation of JDEFAULT is 'Home' (in English)

### System information (as much as possible)

Any system supporting Joomla 4

### Additional comments

joomla.ini and com_menus.ini have a conflicting language key JDEFAULT.
Shouldn't JDEFAULT be translated the same way throughout Joomla core?

**Comment by brianteeman** [comment]
> Shouldn't JDEFAULT be translated the same way throughout Joomla core?

No. There are many examples of this - usually relating to permissions.

> I cannot find an example in the core, it happens when developing a third-party extension.

![image](https://user-images.githubusercontent.com/1296369/120938044-dc065380-c708-11eb-8360-1ad55890fd9e.png)

**Comment by obuisard** [comment]
Thanks Brian.

What I tried to convey is that I could not find an example of a menu item containing a field with value 'default' and translated with JDEFAULT where I could demonstrate the issue.

![image](https://user-images.githubusercontent.com/5964177/120939272-4c02e280-c6e5-11eb-9342-f3bad1369d5e.png)

JDEFAULT has been added to com_menus.ini in Joomla 4.
It is such a global and general key, that any time JDEFAULT needs to be translated on a page where com_menus.ini is loaded, the translation will be 'Home' and not 'Default'.

**Comment by brianteeman** [comment]
> It is such a global and general key, that any time JDEFAULT needs to be translated on a page where com_menus.ini is loaded, the translation will be 'Home' and not 'Default'.

The only time that com_menus.ini should be loaded is when in the menu component where it is the intended behaviour.

**Comment by brianteeman** [comment]
Please test #3882

**Comment by alikon** [comment]
Please test https://github.com/joomla/joomla-cms/pull/38825
