### ISSUE TITLE
Curl Post error when create article, user etc

### ISSUE THREAD

**Issue by marconte21870** [joomla/joomla-cms#34430]
"{"errors":[{"title":"Field required: Title\nField required: Category"}]}"
when i send curl for new article, user :
curl -X POST [myhttspsite]/joomla/api/index.php/v1/content/articles
-H "Content-Type: application/json"
-H "X-Joomla-Token: mytoken"
-d "{'alias': 'my-article','articletext': 'My text','catid':'2,'language': '*','metadesc': '','metakey': '','title': 'Here's an article'}"

**Comment by alikon** [comment]
cannot confirm see https://github.com/joomla/joomla-cms/pull/34274#issuecomment-855368862

**Comment by marconte21870** [comment]
I solved with your advice, it works but on postman it does not work, it is not important postman but it is important that it works on php and my n8n platform,
a sincere thank you
