### ISSUE TITLE
[4.0] Improving the display of an arrow in language string in "plg_system_updatenotification.*"

### ISSUE THREAD

**Issue by max123kl** [joomla/joomla-cms#34442]
Takes place after the modification in PR #33759

### Steps to reproduce the issue
Select Home Dashboard → Site panel → Plugins from the Administrator menu.
Open Plugin "System - Joomla! Update Notification"
Read description

### Expected result

...You can customise the email at System &rarr; Mail Templates.

### Actual result

...You can customise the email at System > Mail Templates.

### System information (as much as possible)
current 4.0-dev branch

### Additional comments
This arrow symbol (`&rarr;`) is used within the JDOC and JHelp pages as well.
PR is prepared.

**Comment by alikon** [comment]
you don't need to open an issue if you already provide a pr

**Comment by infograf768** [comment]
Careful with RTL
