### ISSUE TITLE
[4.0] Display J! platform/framework version information in backend

### ISSUE THREAD

**Issue by sozzled** [joomla/joomla-cms#34445]
In J! 3._x_, the platform version can be accessed by going to **System** » **System Information**.  The platform is displayed (in J! 3.9) as "Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT".

### Steps to reproduce the issue

Go to **System** » **System Information** » **System Information**

### Expected result

Platform (or framework) information used with the current release of the CMS

### Actual result

No information (comparable to J! 3.x) displayed

### System information (as much as possible)

J! 4.0 RC1

### Additional comments

I understand that there may not be a corollary to a "platform" in J! 4.0.  Therefore, my question may not be relevant to J! 4.  I'm unsure if and where the framework information is stored in the Joomla! CMS.

**Comment by brianteeman** [comment]
Not relevant for j4 which is why it was removed

**Comment by sozzled** [comment]
Thanks.

Follow-up question, please:  is the framework information stored somewhere in the CMS?  If so, where?

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/composer.json

Not that its remotely useful

**Comment by sozzled** [comment]
Thanks.  You're right.  The framework information is not "stored" in the CMS.  :)
