### ISSUE TITLE
[4.0] Frontend: Tag in Article miss top-shadow

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34446]
### What needs to be fixed
Use sample data and open for example `sample-layouts/category-list/welcome-to-your-blog.html`:

![image](https://user-images.githubusercontent.com/78906980/120991149-a18ccd00-c781-11eb-81dd-1ed496b39918.png)

### Why this should be fixed

Look better.

### How would you fix it
Don't know.

**Comment by brianteeman** [comment]
The cause is this line of css but I have no idea what removing it will do elsewhere

```
.com-content-article ol,.com-content-article ul {
     overflow:hidden; 
}
```

**Comment by drmenzelit** [comment]
This line of code was introduced with PR #33624

**Comment by shahwezahmad** [comment]
i want to work on this issue assign me  this

**Comment by shahwezahmad** [comment]
I am interested in this issue assign me t

**Comment by ghost** [comment]
@shahwezahmad Thanks for your interest on this issue. You don't need to be assign to create a pull request.

**Comment by shahwezahmad** [comment]
I am new in open source field  can you suggest me any project to contribute
or anything  which is helpful  to grow me   in this field

**Comment by ghost** [comment]
Similar on "Read more"-Button but not sure if it's worth to open a new issue:

![image](https://user-images.githubusercontent.com/78906980/121773927-7dfdc400-cb7f-11eb-873c-34afcb67e9b6.png)

**Comment by jatinS-dev** [comment]
hello, I want to work on this issue. Can anyone help me how to start?

**Comment by brianteeman** [comment]
Please test #34636

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34636 . Thanks in advance.
