### ISSUE TITLE
Blog Layout administration tab needs to scroll horizontally

### ISSUE THREAD

**Issue by mariantanase** [joomla/joomla-cms#34450]
### Steps to reproduce the issue
Step 1. Fresh Joomla 4 RC1 installation
Step 2. Install "Blog sample data"
Step 3. Go to Menus > Main Menu Blog > Blog (item)
Step 4. Click on "Blog Layout" tab.

### Expected result
No horizontal scroll

### Actual result
The "Multi Column Direction" drop-down and "Date for Ordering" are out of the screen and need to scroll orizontally.
Link: http://localhost/joomla4rc1/administrator/index.php?option=com_menus&view=item&client_id=0&layout=edit&id=102
![scrollhblog](https://user-images.githubusercontent.com/3976174/121026300-48836000-c7a6-11eb-8803-709b9883119b.png)

### System information (as much as possible)
Windows 10 x64 environment
Screen resolution: 1280 x 1024
Firefox 89
PHP 7.4.13
Apache 2.4.41
MySQL 8.0.16

**Comment by drmenzelit** [comment]
That has been already reported #34081 and there is a PR #34145 you can test
