### ISSUE TITLE
Add 2 new positions

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#34464]
Dear colleagues. How many web designers create websites using the Cassiopeia template, redefining its blocks, creating a completely new design?
I do the same thing. The Cassiopeia template has accessibility, normalization, styles, and a framework. This template is ideal for starting even if you need to create a website with a completely different design.
But Cassiopeia is not adapted for use on a large scale with such capabilities.
Cassiopeia is used only with the design that is already laid down. This is bad. It can not be used as NORMALIZE.CSS is used.
We need to add this to the template:
//134 line
**`<jdoc:include type="modules" name="top" style="none" class="grid-child" />`**
//180 line
**`<jdoc:include type="modules" name="bottom" style="none" class="grid-child" />`**
**The important thing is that you need to add these positions without the** **`<DIV>`** **container**.
Using classes in a position
`  class="grid-child"`
we specify that the position will have the default grid width that all blocks on the site have.
Class processing should be added to
//25 line  \templates\cassiopeia\html\layouts\chromes\noCard.php
//25 line  \templates\cassiopeia\html\layouts\chromes\card.php
```
$moduleAttribs['class'] = $module->position . ' no-card ' . ($params->get('moduleclass_sfx') ?
			(htmlspecialchars($params->get('moduleclass_sfx'), ENT_QUOTES, 'UTF-8')) : $attribs['class']);
```
Add the GRID-ARIA grid position to the styles.
.
Dear colleagues, thanks to the change. You can create modules on the site that are the width of the entire site, this can be a map of the route map. It can be a carousel of products. Agree that the driving directions and carousel are convenient when they are the entire width of the site.
Let's make more features for Cassiopeia!
By default, this position has only the width of the content.
This is also convenient when placing just ordinary modules.
If desired, we can place the gallery in the entire width of the site between the blocks.
90% of sites have a gallery in the site header with a width of 100% without affecting the main menu.
For example, the Xiaomi website.
https://www.mi.com/global/
https://www.solus.com/

**Comment by drmenzelit** [comment]
Interesting idea for bringing more flexibility into Cassiopeia. We have to look into it, but probably for the next version of J4.

**Comment by korenevskiy** [comment]
> Interesting idea for bringing more flexibility into Cassiopeia. We have to look into it, but probably for the next version of J4.

There's nothing to learn here. Here it is necessary to test.
Add to the nightly build, and test and test. During the test, there will be errors or not be errors.

**Comment by chmst** [comment]
Would you like to make a PR for that? Looking forward to test it.

**Comment by korenevskiy** [comment]
> Would you like to make a PR for that? Looking forward to test it.

I can't do PR since the Cassiopeia repository is closed. https://github.com/joomla/cassiopeia/


I've been doing this for less than a year, redoing Cassiopeia for J3, adding these positions. I'll tell you this is very convenient.
Of course, in my version of Cassiopeia for J3, I had to replace jQuery with 3.5. But in general, everything works well. Thanks to this flexibility.
I could create a new HEADER for mobile devices. And also create your own hamburger menu also for mobile devices by placing other modules in the hamburger.
According to accessibility, if one HEADER has DISPLAY:NONE, then it is ignored completely and you can add another HEADER.
The use of such positions is very wide.

**Comment by drmenzelit** [comment]
The cassiopeia repository was only an interim solution while working on improvements. Now Cassiopeia is integrated in core, so you can create a PR directly there.

**Comment by korenevskiy** [comment]
> The cassiopeia repository was only an interim solution while working on improvements. Now Cassiopeia is integrated in core, so you can create a PR directly there.

What CSS files should I make changes to? .min.css, .css, css?

**Comment by korenevskiy** [comment]
Let's delete the old repository
It's not relevant, is it?
https://github.com/joomla/cassiopeia/

**Comment by drmenzelit** [comment]
You need to change the scss files and build the css again. You need a development environment with composer and npm. Do you have experience using npm?
https://github.com/joomla/joomla-cms/tree/4.0-dev#how-to-get-a-working-installation-from-the-source

**Comment by korenevskiy** [comment]
no experience with NPM

**Comment by korenevskiy** [comment]
In the near future. I'll try adding PR

**Comment by Quy** [comment]
Can you post the proposed changes here and maybe someone else can submit a pull request?

**Comment by korenevskiy** [comment]
> Can you post the proposed changes here and maybe someone else can submit a pull request?



\templates\cassiopeia\index.php - Insert line 166 
`<jdoc:include type="modules" name="top" style="none" class="grid-child" />`

\templates\cassiopeia\index.php - Insert line 212
`<jdoc:include type="modules" name="bottom" style="none" class="grid-child" />`

\templates\cassiopeia\html\layouts\chromes\noCard.php - Replace line 25 
```
$moduleAttribs['class'] = $module->position . ' no-card ' . ($params->get('moduleclass_sfx') ?
			(htmlspecialchars($params->get('moduleclass_sfx'), ENT_QUOTES, 'UTF-8')) : $attribs['class']);
```

\templates\cassiopeia\html\layouts\chromes\card.php - Replace line 25 
```
$moduleAttribs['class'] = $module->position . ' card ' . ($params->get('moduleclass_sfx') ?
			(htmlspecialchars($params->get('moduleclass_sfx'), ENT_QUOTES, 'UTF-8')) : $attribs['class']);
```

/templates/cassiopeia/templateDetails.xml - Insert 31, 39 lines
```
		<position>top</position>
		<position>bottom</position>
```



/templates/cassiopeia/scss/blocks/_css-grid.scss - Insert in 8 and 41 lines
`". top top top top ."` later `". banner banner banner banner ."`
/templates/cassiopeia/scss/blocks/_css-grid.scss - Insert in 15 and 46 lines
`". bot bot bot bot ."` later `". bot-b bot-b bot-b bot-b ."`

/templates/cassiopeia/scss/blocks/_css-grid.scss - Insert in 72 line
`.container-top {  grid-area: top;}` after `.container-banner {  grid-area: banner;}`

/templates/cassiopeia/scss/blocks/_css-grid.scss - Insert in 112 line
`.container-bottom {  grid-area: bot;}` after `.container-bottom-b {  grid-area: bot-b;}`

**Comment by korenevskiy** [comment]
to make a wide module, you need to add a class suffix **`full-width`**  in the module settings of the admin panel.

**Comment by korenevskiy** [comment]
https://github.com/joomla/joomla-cms/pull/34473 Votes please

**Comment by korenevskiy** [comment]
Votes please

**Comment by richard67** [comment]
I'm confused: Your PR is for 4.1-dev .. so you want it to go into 4.1 and not 4.0?

**Comment by korenevskiy** [comment]
I'm confused myself.
I hardly understand how GitHub works.
I've been trying to make changes to 4.0 for about 5 hours.
NetBeans throws an error. And through the web interface also did not work.

**Comment by korenevskiy** [comment]
I'll try to make it for 4.0

**Comment by korenevskiy** [comment]
![image](https://user-images.githubusercontent.com/6898474/121376869-8e792900-c94a-11eb-84b6-6b786400dbe1.png)

![image](https://user-images.githubusercontent.com/6898474/121377062-bbc5d700-c94a-11eb-90dd-574fe9bfaddd.png)

![image](https://user-images.githubusercontent.com/6898474/121377227-d730e200-c94a-11eb-8086-bf6a3551b752.png)

Tell me what I'm doing wrong?

**Comment by brianteeman** [comment]
![after](https://user-images.githubusercontent.com/1296369/121379345-d6448400-c93b-11eb-9e15-5fedae228e3f.gif)

**Comment by korenevskiy** [comment]
https://github.com/joomla/joomla-cms/pull/34477

**Comment by korenevskiy** [comment]
@brianpeat 
There are no questions here.
I had a problem with that when I make changes. I have changes for only one file every time in one patch. I can't change 5 files to create 5 PR.
I had a problem to create 1 PR but to have 5 modified files in it.

**Comment by korenevskiy** [comment]
I have many identical patches. If I delete everything.
Will the PR created by me remain?

![image](https://user-images.githubusercontent.com/6898474/121382171-05182580-c94f-11eb-910b-74aaaff9a366.png)

**Comment by korenevskiy** [comment]
@drmenzelit @chmst @Quy @richard67 
**`<jdoc:include type="modules" name="top" style="none" class="grid-child" />`**
What do you think?
does the CLASS attribute have the correct name?
After all it is more correct in meaning that the attribute has the name DEFAULT_CLASS

**Comment by korenevskiy** [comment]
#34477

**Comment by richard67** [comment]
Can this be closed now as there is a PR for it?

**Comment by korenevskiy** [comment]
Yes.
