### ISSUE TITLE
Error creating menu in newly installed Joomla 4RC2 Call to a member function getGroup() on null

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#34479]
### Steps to reproduce the issue
Save and close does work, but the save and new option causes the following error.

Call to a member function getGroup() on null

joomla-toolbar-button.min.js?2b501bedfd8651d06d2c09104ed18cd2:1 Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at HTMLElement.connectedCallback (joomla-toolbar-button.min.js?2b501bedfd8651d06d2c09104ed18cd2:1)
    at joomla-toolbar-button.min.js?2b501bedfd8651d06d2c09104ed18cd2:1
3core.min.js?2b501bedfd8651d06d2c09104ed18cd2:1 Uncaught TypeError: Cannot set property 'value' of undefined
    at Object.e.submitform (core.min.js?2b501bedfd8651d06d2c09104ed18cd2:1)
    at Object.e.submitbutton (core.min.js?2b501bedfd8651d06d2c09104ed18cd2:1)
    at HTMLElement.executeTask (joomla-toolbar-button.min.js?2b501bedfd8651d06d2c09104ed18cd2:1)
template.min.js:1 Uncaught TypeError: Cannot read property 'split' of undefined
    at getCookie (template.min.js:1)
    at setDesktop (template.min.js:1)
    at template.min.js:1

**Comment by ghost** [comment]
Cannot confirm. 

Test: Create a menu-item (archived articles) by `Save & New` work as expected. 
Nightly build, firefox, macos.

**Comment by joomdonation** [comment]
Could not confirm the issue, both by when create new Menu or Menu Item using nightly build. @Stuartemk Could you please test it using nightly build or let us know exactly step by step what we need to do to see this error?

**Comment by Quy** [comment]
Closing due to no response with additional information to reproduce issue.
