### ISSUE TITLE
[4.0] Sorted by: table caption

### ISSUE THREAD

**Issue by rjharishabh** [joomla/joomla-cms#34476]
### Steps to reproduce the issue
Visit the articles page in the backend
Sort the table, for example - by Status ascending 
Just look at the table caption in the developer tools or just remove `class="visually-hidden"`  from the code
https://github.com/joomla/joomla-cms/blob/44934f7863bc68ec09aa510a6cb890b16f98a51b/administrator/components/com_content/tmpl/articles/default.php#L110

### Expected result
Correct Sorted by

### Actual result
Incorrect Sorted by

![sorted](https://user-images.githubusercontent.com/61203226/121379300-82e52c80-c961-11eb-91d1-e77a6cce287b.JPG)

### System information (as much as possible)
Chrome on Window 10
PHP 8.0.6
MySQLi 10.4.19-MariaDB

**Comment by ghost** [comment]
Confirm the issue:

![image](https://user-images.githubusercontent.com/78906980/121467960-57daf700-c9ba-11eb-8c3f-261ff55dc760.png)

**Comment by chmst** [comment]
Good find. It comes from searchtools, javascript.

**Comment by rjharishabh** [comment]
Please test #34487

**Comment by ghost** [comment]
@rjharishabh Can you close the issue or is the pull request a partial fix?
