### ISSUE TITLE
[4.0] Options: Different colour active/hover like Sidebar

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34494]
### What needs to be fixed

In Options the active menu (1) has the same colour like a menu, which a user is on (2):

> ![image](https://user-images.githubusercontent.com/78906980/121773007-7a673e80-cb79-11eb-9890-761501c8f92c.png)

In the Sidebar both have different colours (1: active, 2: hover)

![image](https://user-images.githubusercontent.com/78906980/121773087-e34eb680-cb79-11eb-9bcd-cf7be9b6b213.png)

### Why this should be fixed
Easier for user, consistency in Backend.

### How would you fix it
Colours in Options similar to Sidebar.

**Comment by ChristineWk** [comment]
similar? #34484<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34494">issues.joomla.org/tracker/joomla-cms/34494</a>.</sub>

**Comment by ghost** [comment]
@ChristineWk i don't understand what @brianteeman  describe but if it's the same i close this issue. Can you please give your comment if i should close?

**Comment by ChristineWk** [comment]
@sandramay0905 I'm sure @brianteeman  knows this better - that's why I made a ?

**Comment by Sinha-09** [comment]
I'll do it but in which directory or folder its code exist??
I tried to find but I didn't get it
