### ISSUE TITLE
[4.0 RC1] Organization of the menu order

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#34498]
Dale smenus manager, I can't move and reorganize the links. I select and I move, but I can not position the links by a click. It sticks to the mouse ...
<img width="1970" alt="Capture d’écran 2021-06-13 à 16 29 51" src="https://user-images.githubusercontent.com/26197929/121811554-10c45e80-cc65-11eb-8eae-7cf168443c49.png">

**Comment by Quy** [comment]
Please test with the nightly builds: https://developer.joomla.org/nightly-builds.html

**Comment by Magnytu2** [comment]
@Quy Yes it works thank you very much

**Comment by Magnytu2** [comment]
@Quy You can move menu links, but it is a disaster to organize, because the links do not stay in order and even get mixed up.

**Comment by joomdonation** [comment]
Hmm. I just tried nightly build and re-order menu items works OK here for me. Could anyone else confirm this issue?

**Comment by ghost** [comment]
I tried moving menus up and down, this works. @Magnytu2 can you please be more specific what not works, maybe a gif-animation by LICEcap?

**Comment by ghost** [comment]
@joomdonation found something what @Magnytu2 maybe mean.

The animation show that drag'n'drop a menu up work, down don't work:

![1](https://user-images.githubusercontent.com/78906980/121843910-68a1aa80-cce3-11eb-9fbe-79dfe001f8fc.gif)

**Comment by joomdonation** [comment]
Thanks @sandramay0905. Will wait for more information from @Magnytu2 before looking at it. If it is the issue, I guess it is something related to the code on this method https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/draggable.es6.js#L107-L118 .

**Comment by ghost** [comment]
Drag'n'drop down works on menu, but not on last:

![1](https://user-images.githubusercontent.com/78906980/121846343-2ed2a300-cce7-11eb-837e-8568752e7f02.gif)

Same on modules:

![1](https://user-images.githubusercontent.com/78906980/121846887-026b5680-cce8-11eb-98e0-c66cb7ef7343.gif)

**Comment by Magnytu2** [comment]
I move menu items well. But it has no frontend or out of order effect. And if I update the backend the menus are indeed out of order. I do not know if this has an impact, but I am on sub-menus.

**Comment by joomdonation** [comment]
@Magnytu2 Not sure If I mis-understand the issue but I tried using nightly build and it is working well for me. Change ordering of menu items from admin affect frontend immediately.

Could anyone checks to see if you can confirm this issue?

**Comment by brianteeman** [comment]
Please make a recording of your problem - you can use licecap for the recording

**Comment by Magnytu2** [comment]
I change the order of the submenus, I update my front and I display it no change. I'm updating my backend and it's still changing.
![ OrganisationMenu](https://user-images.githubusercontent.com/26197929/121927577-8270db00-cd3f-11eb-9e85-94db8a26b87d.gif)

**Comment by brianteeman** [comment]
and do you have cache enabled?

**Comment by brianteeman** [comment]
That could be both a cache setting in Joomla and even in your hosting

**Comment by Magnytu2** [comment]
the cache is disabled, emptied. I changed my browser as well.
<img width="1276" alt="Capture d’écran 2021-06-14 à 19 03 50" src="https://user-images.githubusercontent.com/26197929/121931052-666f3880-cd43-11eb-92c1-fba9c4829352.png">

**Comment by brianteeman** [comment]
Is this localhost or is it hosted somewhere I can look at?

**Comment by Magnytu2** [comment]
it is hosted remote. It is a simple site to present Joomla 4. An article, a title, an image, a sentence. https://joomla-4.fr/

**Comment by brianteeman** [comment]
If you can send me super admin access details I can take a closer look.

**Comment by Magnytu2** [comment]
I sent your credentials by email.

**Comment by brianteeman** [comment]
I will look after dinner

**Comment by brianteeman** [comment]
I can confirm that there is something odd happening.

I can move items in the menu and sometimes it works but sometimes it is wrong. When it is wrong if I click on "rebuild" in the admin then the menu in the admin now matches the frontend.

Sorry I cant see a reason why

**Comment by chmst** [comment]
Can you see js errors on the console?

**Comment by brianteeman** [comment]
no - and now it seems to be working correctly

**Comment by Magnytu2** [comment]
For me it does not work. If I move one, okay. If I move two, it doesn't work.

**Comment by chmst** [comment]
![image](https://user-images.githubusercontent.com/1035262/121939652-873c8b80-cd4d-11eb-9739-1de145358e85.png)

I got this when I tried to drag the xx2 above xx1

I make a new composer / npm now

**Comment by brianteeman** [comment]
> For me it does not work. If I move one, okay. If I move two, it doesn't work.

bingo. confirmed on my own site

**Comment by joomdonation** [comment]
[draggable.zip](https://github.com/joomla/joomla-cms/files/6653719/draggable.zip)

Could someone get this modified file, unzip it, upload to media/system/js folder, then test it to see if it solves the issue?

Before, we only submitted data between drag and drop element to server for updating ordering. Now, I modified it so that data from all rows (within same group if there are group) will be submitted in ajax request (basically, same with J3). Hope it solves the issue.

**Comment by chmst** [comment]
I have tested your js. The js error from https://github.com/joomla/joomla-cms/issues/34498#issuecomment-860901081  has gone and drag and drop is working fine now, also on the lecond level. But the effect described here persits  https://github.com/joomla/joomla-cms/issues/34498#issuecomment-860398606

**Comment by brianteeman** [comment]
This should be closed as there is a pr
