### ISSUE TITLE
[4.0] uitab validation errors

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#34492]
### Steps to reproduce the issue

Use https://validator.w3.org/nu/#textarea to validate a page containing uitabs (article edit form).
It flags errors:
Error: Attribute name not allowed on element section at this point.
`<section id="dateSelect" name="Dates">`
One for every tab.

If I change libraries/src/HTML/Helpers/UiTab.php so that line 92 has data-name rather than name AND
I change media/vendor/joomla-custom-elements/js/joomla-tab.js so that line 246 has data-name rather than name 
then the tabs still work and do not cause validation errors.

Is this something to worry about? Should it be fixed?

**Comment by brianteeman** [comment]
name is not a valid element for a section

data-* is ignored by all checkers so will pass any test and its usually used if you need to pass something to javascript

**Comment by dgrammatiko** [comment]
> `<section id="dateSelect" name="Dates">`


This **shouldn't be** a section element but a custom element and then the `name` attribute is totally valid. That said there are other more serious problems with the joomla-tabs custom elements...

**Comment by ceford** [comment]
I decided to roll my own tabs so I am not pursuing this. However, I am leaving it open because I don't think Joomla should release 4.0 knowing some pages will fail validation.

**Comment by brianteeman** [comment]
How disappointing

**Comment by dgrammatiko** [comment]
> How disappointing

What's actually disappointing is that you personally cancelled all my attempts to fix the custom elements. Count this comment also as another one

**Comment by brianteeman** [comment]
me?

**Comment by dgrammatiko** [comment]
> me?

https://github.com/joomla/joomla-cms/issues/25890#issuecomment-522098992

**Comment by Quy** [comment]
Please test PR #34813
