### ISSUE TITLE
[4.0] Hits field in meta-tags block / News feed

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34500]
### Steps to reproduce the issue
Go to the News Feeds component and create a new feed. In the publish tab, you can see that the HITS field is in the met-tags block, which is strange to me.

Perhaps we can see a similar problem in other components, we need to check.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/121818562-a0333700-cc90-11eb-9649-94d5ef4ac459.png)

**Comment by brianteeman** [comment]
please test #34506
