### ISSUE TITLE
[4.0] Style "Block FLoC"

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34504]
### What needs to be fixed
In `Global Configuration` > `Site` the switch need style:

>![image](https://user-images.githubusercontent.com/78906980/121840883-83712080-ccdd-11eb-91e7-82ec074b1463.png)

### Why this should be fixed

Style should be the same like:

>![image](https://user-images.githubusercontent.com/78906980/121855387-90990a00-ccf3-11eb-9146-0b76508b9f12.png)

### How would you fix it

Don't know.

**Comment by brianteeman** [comment]
Please test #34507

**Comment by ghost** [comment]
Closed because having pull request #34507
