### ISSUE TITLE
Adding attachment in mail template doesn't work

### ISSUE THREAD

**Issue by RickR2H** [joomla/joomla-cms#34512]
### Steps to reproduce the issue
1. Go to System -> Mail Templates -> open the "Global Configuration: Test Mail" mail template.
2. Try to add an attachment by clicking the "Plus button".
3. There should be a field to upload and add the attachment, but only a blank space is added.

![screen shot 2021-06-14 at 10 12 24](https://issues.joomla.org/uploads/1/9a3ef96fc8c9286d9fc1d0bb10291dcf.jpg)

**Comment by richard67** [comment]
@RickR2H I can't reproduce this on a clean, new installation of current 4.0-dev. In this case, the "Attachments Folder" option in the Media Manager component's options is empty, so there is no "+" button shown in any of the mail templates to add an attachment.

So my questions are:
1. Have you used a new installation of current 4.0-dev or latest nightly? Or have you used an installation which was updated in past? If so, please let us know the update history.
2. What is the value of the "Attachments Folder" option in the Media Manager component's options of your installation?

**Comment by joomdonation** [comment]
@richard67 I can confirm the issue. Currently, look like subform is not working at all. For example, we can add a new custom field checkbox and could not add options for the custom field anymore

**Comment by ghost** [comment]
I got the issue reported by @RickR2H if i set in options of mail templates the `Attachment Folder` to `images`.

**Comment by richard67** [comment]
> I got the issue reported by @RickR2H if i set in options of mail templates the `Attachment Folder` to `images`.

Confirmed.

**Comment by richard67** [comment]
> @richard67 I can confirm the issue. Currently, look like subform is not working at all. For example, we can add a new custom field checkbox and could not add options for the custom field anymore

@joomdonation Last change for subforms in J4 was #31567 . Could it be related to that PR? Or has the upmerge from 3.10-dev broken something from that PR?

**Comment by richard67** [comment]
@joomdonation Could you open an issue for the general subforms issue and we make it a release blocker? Or should we use this issue here to continue and make it a release blocker?

**Comment by joomdonation** [comment]
@richard67 We could use this issue here to continue. I don't know subform code enough to confirm where this issue comes from. Maybe @Fedik could help ?

**Comment by Fedik** [comment]
I will try to look what's going on

**Comment by joomdonation** [comment]
Sorry @dgrammatiko . Look like it causes by `Joomla.sanitizeHtml` too. If we change this line of code to https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js#L186 to :

```javascript
tmpEl.innerHTML = this.template;
```
The issue is gone. Could you please look at this?

**Comment by dgrammatiko** [comment]
@Fedik probably it's coming from the sanitiser: https://github.com/dgrammatiko/joomla-cms/blob/bdf673b3c7c82b819b8e97608ceef41325c06d3c/build/media_source/system/js/fields/joomla-field-subform.w-c.es6.js#L186

**Comment by joomdonation** [comment]
Ah, we added comment at the same time :).

**Comment by dgrammatiko** [comment]
@joomdonation here's a PR: #34514

**Comment by joomdonation** [comment]
Fixed on PR https://github.com/joomla/joomla-cms/pull/34514 , so closing this issue.
