### ISSUE TITLE
Joomla login Uncaught TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by RickR2H** [joomla/joomla-cms#34511]
### Steps to reproduce the issue
The login screen of Joomla 4 generates Javascript errors:

Go yo the login screen and open the console.
Click on the password field.

![screen shot 2021-06-14 at 10 03 03](https://issues.joomla.org/uploads/1/4dcb6452a272f726213b121a3ef291ca.jpg)

**Comment by ghost** [comment]
Confirm the issue (Firefox, Mac):

![image](https://user-images.githubusercontent.com/78906980/121876831-41120880-cd0a-11eb-924b-b3016ef00bb3.png)

**Comment by RickR2H** [comment]
Maybe partially related to #34472 ?

**Comment by joomdonation** [comment]
@RickR2H is right. It's related to that PR

@dgrammatiko It's related to this code block https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/js/fields/validate.es6.js#L119-L125

message is null, and it causes the error. Could you please fix it? My dirty fix would be changing that block of code to:

```javascript
if (empty && empty === 'checkbox') {
elMsg.innerHTML = (message !== null && Joomla.sanitizeHtml(message)) || Joomla.sanitizeHtml(Joomla.Text._('JLIB_FORM_FIELD_REQUIRED_CHECK'));
} else if (empty && empty === 'value') {
elMsg.innerHTML = (message !== null && Joomla.sanitizeHtml(message)) || Joomla.sanitizeHtml(Joomla.Text._('JLIB_FORM_FIELD_REQUIRED_VALUE'));
} else {
elMsg.innerHTML = (message !== null && Joomla.sanitizeHtml(message)) || Joomla.sanitizeHtml(Joomla.Text._('JLIB_FORM_FIELD_INVALID_VALUE'));
}
```
But you understand it better and could provide better fix.

**Comment by dgrammatiko** [comment]
@joomdonation your code is fine, my bad

**Comment by joomdonation** [comment]
Thanks @dgrammatiko . I opened PR https://github.com/joomla/joomla-cms/pull/34513 to solve this issue.
