### ISSUE TITLE
[4.0] Pre-update check "More Detail" and "Less Detail" toggles of the PHP checks are broken.

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#34510]
### Steps to reproduce the issue

On a current 4.0-dev branch which includes the latest commits from stuff having been merged up from 3.10-dev today, make a new installation if you haven't done one yet.

Then go to the Joomla Update Component's options and set the update channel to the custom URL of the nightlies so that the pre-update checker is shown after saving.

Now toggle a few times one of the "More Detail" and "Less Detail" links in the legends of the 2 PHP checks "Required PHP & Database Settings" and "Recommended PHP Settings" at the top.

_Important:_ Click on the arrow symbol for toggling, not on the "More Detail" or "Less Detail" texts.

### Expected result

The toggle just changes the text and the arrow icon.

### Actual result

The link text is added again and again with each toggle:

![2021-06-14_pre-update-check-js-problem](https://user-images.githubusercontent.com/7413183/121872272-5cc6e000-cd05-11eb-99d3-d11e2489abda.png)

### System information (as much as possible)

Current 4.0-dev branch from today, June 14 2021.

### Additional comments

Might be something to be fixed in the JS of the Joomla Update Component.

**Comment by brianteeman** [comment]
it is a change in the markup that is impacting on the js. probably after the recent merge from @wilsonge

**Comment by richard67** [comment]
> probably after the recent merge from @wilsonge

@brianteeman Remove the "probably" ;-)

**Comment by richard67** [comment]
Strange: Now after having been logged out for a while, it works, and I can't reproduce this issue here.

**Comment by richard67** [comment]
I've just tried again with a fresh and clean 4.0-dev and still can't reproduce it, so I guess it was some kind of caching issue.

**Comment by joomdonation** [comment]
I use nightly build and don't see the issue, too. So we are fine.

**Comment by Quy** [comment]
To reproduce it, click on the arrow and not the text.

**Comment by richard67** [comment]
>To reproduce it, click on the arrow and not the text.

@Quy Confirmed.

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/34516 should fix this issue. Please test.
