### ISSUE TITLE
[4.0] Modal window for privacy consent too small

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#34529]
### Steps to reproduce the issue

- Activate the plugin `System - Privacy Consent`
- Configure an article or a menu containing the privacy policy
- Allow user registration
- Create a menu item for registration form
- Go to the registration form and click on the link to the Privacy Policy, a modal window will open

(The same problem with the plugin `User - Terms and Conditions`)

### Expected result
You can read the Privacy Policy

### Actual result
The modal window is too small, the height doesn't adapt to the content, you have to scroll a lot to read the text
![image](https://user-images.githubusercontent.com/9153168/122199671-941ac580-ce9a-11eb-9f5d-5bf497755bce.png)

**Comment by ghost** [comment]
Confirm the issue:

![1](https://user-images.githubusercontent.com/78906980/122348231-3befcc00-cf4b-11eb-8763-913d28e6e654.gif)

**Comment by drmenzelit** [comment]
Found the problem, working now on a solution

**Comment by alikon** [comment]
test #34537

**Comment by drmenzelit** [comment]
Thank you @alikon , I forgot to close it earlier today
