### ISSUE TITLE
[4.0] htaccess kills admin

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34525]
A message was added #33097 
```

## If your site starts to look strange after enabling this, and you see
##     ERR_CONTENT_DECODING_FAILED in your browser console network tab,
##     then your server is already gzipping css and js files and you don't need this
##     block enabled in your .htaccess

```

> Hopefully people will read :-) and understand.

I managed to track down my issue to the htaccess file but as I had no ERR_CONTENT_DECODING_FAILED or any other error in my console I ignored the message - even though it did appear to solve the issue

There must be a better way than breaking the site and then being skilled enough to locate where the error is coming from and then guessing the fix. Especially as the fix is "outside" the joomla ui.

**Comment by PhilETaylor** [comment]
The message was added to help... imagine how hard it was before the helpful message... :)

**Comment by brianteeman** [comment]
in my case I only saw the message AFTER I had found the problem

**Comment by PhilETaylor** [comment]
yes - because Historically Joomla has never checked if a server is already going to gzip the sites output once PHP hands the response back to apache, before apache once again gzipping (and therefore corrupting) the output. 

I guess the change you are after is finding a way to tell if a server is going to gzip the output after Joomla with a crystal ball ahead of time, and therefore not firstly (unperformantly) first gzipping using PHP code. 

There are several things that enable GZIP 

1) Joomla. This gzips the HTML response if gzip is enabled in Joomla Global Config. 
2) .htaccess - this gzips the HTML response and all other assets
3) .htaccess - configured by copy and paste from most online FAQ questions -  this gzips the JS/CSS responses only
4) Web Server - can be configured a myriad of ways, to gzip some, all, or most assets depending on mime type

I vote for removing GZIpping in Joomla Global Config, all the other options are far more performant than compressing in PHP. 

But that still leaves your problem... a myriad of ways a server can be configured, and config overruled by .htaccess rules...

**Comment by brianteeman** [comment]
and remember i have no console errors

**Comment by PhilETaylor** [comment]
> and remember i have no console errors

You dont actually report what the problem you had was...

**Comment by PhilETaylor** [comment]
Im going to guess you had the same issue as https://github.com/joomla/joomla-cms/issues/32892 

In SOME browsers you would see:

<img width="940" alt="114297879-69e50a00-9add-11eb-956d-23722a2d3a54" src="https://user-images.githubusercontent.com/400092/122222083-d26bb100-cea9-11eb-9d4e-02ebe18b443f.png">

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/122221935-af410180-cea9-11eb-8ffd-32d2f83401d0.png)

**Comment by PhilETaylor** [comment]
and if you tried to go direct to one of those JS files - does your browser refuse to show the JS file? with a ERR_CONTENT_DECODING_FAILED across the middle of the page?

**Comment by brianteeman** [comment]
as i said no problems
![image](https://user-images.githubusercontent.com/1296369/122222417-26769580-ceaa-11eb-8489-cab28ca3c674.png)

**Comment by PhilETaylor** [comment]
Are you even sure your issue is a gzip issue? As the content type in that screenshot is just plain js

**Comment by brianteeman** [comment]
as soon as I comment out these lines it works correctly

```
	RewriteCond "%{HTTP:Accept-encoding}" "gzip"
	RewriteCond "%{REQUEST_FILENAME}\.gz" -s
	RewriteRule "^(.*)\.css" "$1\.css\.gz" [QSA]
```

**Comment by PhilETaylor** [comment]
But do you have *.css.gz files next to your *.css files or are they missing?

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/122227031-6dff2080-ceae-11eb-9e6b-d01e27fa6560.png)

**Comment by PhilETaylor** [comment]
Strange as your screenshot has the JS tab selected and not the css tab !?

What's the css tab look like?

**Comment by brianteeman** [comment]
ok problem solved (i think)

I just deleted the entire css folder and rebuilt with npm

there are now no gz files at all

So I am going to guess two thing (before checking)

1. the build script overwrites the existing css - it does not delete the folder and rebuild from scratch
2. the build script no longer builds the gz files on my system

As a result the gz css files that were being loaded were just old and out of date

**Comment by brianteeman** [comment]
dont have any more time today to look into it

**Comment by dgrammatiko** [comment]
> So I am going to guess two thing (before checking)

> - the build script overwrites the existing css - it does not delete the folder and rebuild from scratch
> - the build script no longer builds the gz files on my system

You're right for both, the build tools just rebuild the css/js without recreating the `.gz` neither refreshing the hash for the invalidation. For those 2 you need to run the commands separately (`npm run gzip` and `npm run versioning`)

The reasons that these commands are not executed directly on `npm install` are:
- the process will be longer
- it's harder to debug/develop with both the .gz and a fixed version (you need to constantly invalidate the static assets)
- both these commands are supposed to be part of the build process for the release

That said, I find it kinda weird that you had `.gz` files in a cloned repo, but as a final solution for everything npm related: delete both the media folder and the node_modules and re run `npm install` (templates also need extra step here till everything static is finally served from the media folder [talking about the child templates])
