### ISSUE TITLE
[4.0] Mail Templates: Line between flags

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#34522]
### What needs to be fixed
In Mail Templates is a line between the flags on a multilanguage site:

![image](https://user-images.githubusercontent.com/78906980/122041917-cdd7c780-cdd9-11eb-8b0c-c09d06503438.png)

### Why this should be fixed
I think there should be only padding between the flags.

**Comment by drmenzelit** [comment]
Probably underlines from link?

**Comment by chmst** [comment]
Closing. Please test #34530
