### ISSUE TITLE
[j4 RC 2] Media manager in ultrawidth screen

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#34528]
### Steps to reproduce the issue
testing mediamanager in ultra width screen have some ratio problem
3400px
![image](https://user-images.githubusercontent.com/2539440/122170805-4775c100-ce7f-11eb-91dd-24ffe09cf6e2.png)

1950px
![image](https://user-images.githubusercontent.com/2539440/122170934-712ee800-ce7f-11eb-9087-b68cb51b41f7.png)

i think 16.66% is too big
9% is better for this resolution
![image](https://user-images.githubusercontent.com/2539440/122171227-c79c2680-ce7f-11eb-9b3f-eafe28cbbf0d.png)

**Comment by laoneo** [comment]
You can change the zoom level in the toolbar for large screens as well. Guess then this issue is solved.
![image](https://user-images.githubusercontent.com/251072/122786619-c9694e00-d2b4-11eb-9bc8-cb75743b9e63.png)

**Comment by brianteeman** [comment]
Should be closed
