### ISSUE TITLE
SEF Not Working For Tags In Category Blog

### ISSUE THREAD

**Issue by David2376** [joomla/joomla-cms#34527]
### Steps to reproduce the issue
Create a tag in Components -> Tags
Assign tag to an article
Create a menu item of category blog and set to display the tag created above
Navigate to the menu item

### Expected result
URL should be SEF

### Actual result
URL is not SEF.
A query is attached to the URL 
?filter_tag[0]=1

### System information (as much as possible)
Joomla 4.0.0-rc1
PHP 7.4.16

### Additional comments
I have found this issue dating back to early versions of Joomla. It appears that it was fixed but is broken again in all Joomla 4 releases.

**Comment by ditsuke** [comment]
Hello, I've been attempting to fix this issue! 
I've gone through site router and then the routers for `com-content` and `com-tags` but haven't been able to find the SEF route build rules/code responsible for handling tags or filters yet. Can someone help me find the responsible code?

**Comment by Quy** [comment]
Please test PR #34652. Thanks.

**Comment by wilsonge** [comment]
Reopening this as the proposed patch isn't acceptable. But this bug still needs fixing

**Comment by brianteeman** [comment]
Closed as resolved with #40225
