### ISSUE TITLE
[4.0 RC2] Weblinks component partial error

### ISSUE THREAD

**Issue by MaghSamana** [joomla/joomla-cms#34536]
Under Components > Weblinks labels displays as com_weblinks. Its two submenus also lack labels and display as com_weblinks_links and com_weblinks_categories.

The Weblinks Categories open normally when clicked. The Weblinks Links throw a general error.

![Screenshot #003 - Error_ 500 - dev](https://user-images.githubusercontent.com/46110970/122306734-b00d7e00-cf11-11eb-9543-152ed2a0a9e2.png)

### System information (as much as possible)
Test site: Joomla! 4.0.0-rc2, PHP 7.4.20, Apache.

**Comment by Quy** [comment]
The weblinks component has been decoupled from Joomla CMS.
Please post your issues here: https://github.com/joomla-extensions/weblinks

**Comment by brianteeman** [comment]
even decoupled this should not happen

**Comment by joomdonation** [comment]
Just want to update that the current weblinks extension is not compatible with Joomla 4:

- Backend is half converted to J4 component structure
- Frontend is still uses same structure on J3, so it is not working.

The JBS team will work on it and try to get it converted to J4 ASAP.
