### ISSUE TITLE
[4.0 RC2] The image area disappears from the article

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#34532]
### Steps to reproduce the problem
I am having strange behavior with the addition of a warning box in the text of an article. In blog view, the poster is correct. In view of the article, the image disappears to make way for a very large alert zone.

https://joomla-4.fr/informations/avertissements

### Expected result
Identical text zone in blog and article view

### Current result
The image area disappears to make room for a whole alert message area.

### System information (as much as possible)
Joomla! 4 RC2

![Capture 054 - Avertissements - joomla-4 fr](https://user-images.githubusercontent.com/26197929/122234759-6c892480-cebd-11eb-9d75-58cab192b735.jpg)
![Capture 055 - Comment supprimer l'avertissement PHP de Joomla _ - joomla-4 fr](https://user-images.githubusercontent.com/26197929/122234771-6f841500-cebd-11eb-9768-4544ed35bc31.jpg)

**Comment by drmenzelit** [comment]
That is because your image has `float:left` but it is too big to be floated (4000px width!!).

**Comment by Magnytu2** [comment]
I changed the image to 1920px, and it's the same problem.
<img width="1275" alt="Capture d’écran 2021-06-16 à 17 10 13" src="https://user-images.githubusercontent.com/26197929/122245266-defe0280-cec5-11eb-917c-1669de41da01.png">

**Comment by drmenzelit** [comment]
1920px is still to big to be floated, you have only 986px space in the content area

**Comment by Magnytu2** [comment]
All my images are in 1920px and it works. There is only this article with the orange warning box.
If I start the article with:
<div class = "alert alert-warning" role = "alert"> the image disappears.
If I remove this class the image appears.

https://joomla-4.fr/informations/avertissements/comment-supprimer-lavertissement-php-de-joomla

**Comment by brianteeman** [comment]
everything looks fine to me and I have zero idea what @drmenzelit is talking about. The image is scaled so the native size is irrelevant to the float

**Comment by Magnytu2** [comment]
I have doubled the article so you can see the difference.
https://joomla-4.fr/informations/avertissements/comment-supprimer-lavertissement-php-de-joomla-2

**Comment by brianteeman** [comment]
Ok I can see it now and what is happening is perfectly correct for the code and css on the site (even if it is not what you wanted or expected to happen)

This isnt the place to go into great depth on the issue as its not really a core problem. But you can fix this in two different ways.

1. Dont put a float on the image
2. Remove position: relative on the alert

Note that you are misusing the alert anyway and breaking accessibility.

**Comment by Magnytu2** [comment]
I added some introductory text before the warning box. Thanks a lot you two.

**Comment by drmenzelit** [comment]
Yes, sorry, I was not clear enough telling you that removing `float:left` from the image would solve the problem. Float is ok when the image is small enough to share the place with the text.
I think you can now this issue.

**Comment by chmst** [comment]
@Magnytu2 it seems that this is not a bug or issue of joomla. Can we close this?

**Comment by Quy** [comment]
Closing as not a core issue. Thanks.
