### ISSUE TITLE
[4] $table var dump exhausts 1 GB memory

### ISSUE THREAD

**Issue by pioada** [joomla/joomla-cms#34531]
### Steps to reproduce the issue
var_dump or print_r $table in Joomla\CMS\MVC\Model\AdminModel save method or 
Joomla\Component\Banners\Administrator\Model prepareTable method
Add new baner and save
### Expected result
Dump $table var

### Actual result
Error: 1GB memory exhausted

### System information (as much as possible)
Joomla 4 beta 7
Linux, Apache, PHP 7.2.28

**Comment by Quy** [comment]
Please test with the nightly builds to see if the issue persists. https://developer.joomla.org/nightly-builds.html

**Comment by pioada** [comment]
Tested with J4 RC3 dev.
Still can't dump $table var. print_r causes Error OutOfMemoryError Error: Allowed memory size of 134217728 bytes exhausted. var_dump causes "white screen".
I think method usage looks like: Joomla\CMS\MVC\Model\AdminModel::save -> Joomla\CMS\MVC\Model\BaseDatabaseModel::getTable -> Joomla\CMS\MVC\Model\BaseDatabaseModel::_createTable -> Joomla\CMS\MVC\Model\DatabaseAwareTrait::getDbo - return $this->_db is the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34531">issues.joomla.org/tracker/joomla-cms/34531</a>.</sub>

**Comment by Fedik** [comment]
It is very much depend of what exactly data you dumping,
It is not a Joomla issue.

Hint: try var_dump only for needed properties, instead of whole Object
