### ISSUE TITLE
beez3 and protostar templates appear in the /templates folder after every Joomla update even when uninstalled

### ISSUE THREAD

**Issue by stanislawru** [joomla/joomla-cms#34539]
### Steps to reproduce the issue
1. Uninstall the **beez3** and **protostar** templates from your Joomla.
2. Check the /templates folder via FTP to see their (sub)folders are gone.
3. Update your Joomla with the automated update inside the administrative interface.
4. Check the /templates folder via FTP to see the **beez3** and **protostar** (sub)folders are back.

### Expected result
If uninstalled, the **beez3** and **protostar** templates should not appear in the /templates folder after a Joomla update.

### Actual result
The **beez3** and **protostar** templates appear in the /templates folder after every Joomla update even when uninstalled.

### System information (as much as possible)
Any Joomla version (my current is 3.9.27).

### Additional comments
This is not a problem when you manually update Joomla from a ZIP file where the **beez3** and **protostar** folders present – if they present, and you copy them via FTP, they, of course, must be copied to the server.

**Comment by zero-24** [comment]
> Uninstall the beez3 and protostar templates from your Joomla.

That is not intended nor supported.

> Update your Joomla with the automated update inside the administrative interface.

Yes an core update will always restore any core extensions including templates. You can disable the plugin but uninstall is not supported nor intended.

> This is not a problem when you manually update Joomla from a ZIP file where the beez3 and protostar folders present – if they present, and you copy them via FTP, they, of course, must be copied to the server.

Please do not update via FTP anymore. If you need to manually upload the package please use the com_joomlaupdate too. Only this way we can make sure that all migration scripts such as SQL updates and script.php steps are done at all and in the correct order.

**Comment by stanislawru** [comment]
@zero-24, “is not intended nor supported” sounds like a universal negative answer to **any** reported issue. :-(

> That [uninstalling the beez3 and protostar templates] is not intended nor supported.

As I **can** uninstall the **beez3** and **protostar** templates from my Joomla, this **is** already supported. And if I do so, I am definitely **intended** to.

> …Core update will always restore any core extensions including templates. You can disable the plugin but uninstall is not supported nor intended.

If a plugin/template/etc. is removed from Joomla it should definitly **not** be updated and appear back, regardless it is a core one or a third party's.

Updating unstalled extensions produces “phantoms” and is definitely **not** the behaviour a user/administrator expects from the CMS. Moreover, it can produce a suspicion that the website is hacked (as the folders of the previously removed can be seen again).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34539">issues.joomla.org/tracker/joomla-cms/34539</a>.</sub>

**Comment by zero-24** [comment]
> @zero-24, “is not intended nor supported” sounds like a universal negative answer to **any** reported issue. :-(
> 
> > That [uninstalling the beez3 and protostar templates] is not intended nor supported.

Yes. I'm sorry when that sound to negativ. But yes thats the status right now.

> As I **can** uninstall the **beez3** and **protostar** templates from my Joomla, this **is** already supported. And if I do so, I am definitely **intended** to.
> 
> > …Core update will always restore any core extensions including templates. You can disable the plugin but uninstall is not supported nor intended.
> 
> If a plugin/template/etc. is removed from Joomla it should definitly **not** be updated and appear back, regardless it is a core one or a third party's.

My comment is only about core. Third party extensions can not be updated once uninstalled. ;-)

> 
> Updating unstalled extensions produces “phantoms” and is definitely **not** the behaviour a user/administrator expects from the CMS. Moreover, it can produce a suspicion that the website is hacked (as the folders of the previously removed can be seen again).

IIRC in the past we had protected core extensions from beeing uninstalled for the reason mentiond above. I'm suprised that this is not the case anymore. But the issue is that the update process does not support the uninstalled core extensions but will restore the files on update.

Feel free to disable the core extensions like templates you do not use but please do not uninstall core extensions.

**Comment by ChristineWk** [comment]
Think it's all explained by @zero-24. One more point: it happens that, for example, a template used in e.g. views and/or has some error messages.
Then it is useful to temporarily check with a standard template (prefer Protostar) whether errors result from (own) template. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34539">issues.joomla.org/tracker/joomla-cms/34539</a>.</sub>

**Comment by chmst** [comment]
This is an issue since years and enerves me since years. I wonder why we have never had an issue for that. @zero-24 can we resolve it in 3.10? If these template folders don't exist, then don't re-install? This only for Beez3 and Hathor, not for protostar and isis.

**Comment by brianteeman** [comment]
This is why we have protected extensions in j4

**Comment by zero-24** [comment]
> This is an issue since years and enerves me since years. I wonder why we have never had an issue for that. @zero-24 can we resolve it in 3.10? If these template folders don't exist, then don't re-install? This only for Beez3 and Hathor, not for protostar and isis.
> 

The solution would be to remove that stuff from the core distribution it has been tried with weblinks but than hold back for varius reasons.

Specificly for templates there is also the point @ChristineWk mention to have a fallback distributed by the core.

**Comment by zero-24** [comment]
> This is why we have protected extensions in j4

Ah than its that what i had in mind :-)

**Comment by richard67** [comment]
@stanislawru What's your problem? Does your server have so little disk space that these 2 templates bother? If so, then you have more severe problems. I think.

**Comment by stanislawru** [comment]
@zero-24,
> I'm suprised that this is not the case anymore.

So if I **can** uninstall core extensions in my Joomla 3.9.27, why do you consider **normal** restoring uninstalled extensions? :-O It is **definitely a bug now**.

> Feel free to disable the core extensions like templates you do not use but please do not uninstall core extensions.

I do not want to disable them – as I do not need them, completely, I want to uninstall them, and I do so, and I expect the uninstalled extension not to be back on update!

@ChristineWk,
> …It happens that… a template used in e. g. views and/or has some error messages. Then it is useful to temporarily check with a standard template… whether errors result from (own) template.

I have never used core templates to debug my custom ones. That why I do not need them and uninstall them. That is why I have opened this issue.

@chmst, thanks for being the only one who understands me here! :-)

@brianteeman,
> This is why we have protected extensions in J4.

I do not know when J4 is released, and this issue bothering me is **here** and **now**.

@richard67,
> What's your problem?

I have descibed it above in detail.

> Does your server have so little disk space that these 2 templates bother?

No. Please re-read my explanations and answers above to understand why the issue is a bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34539">issues.joomla.org/tracker/joomla-cms/34539</a>.</sub>

**Comment by brianteeman** [comment]
This issue should be closed. It is working as designed and at this time no new features are being added to joomla 3

**Comment by alikon** [comment]
thanks for the reminder
