### ISSUE TITLE
[4.0] [Front] Bold font in the list of items

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34544]
### Steps to reproduce the issue
Install demo data. In the frontend, select the item to create an article, then select the CMS CONTENT -> Article (or, for example, MENU) item in the editor. Please note that all items in the list are in bold. Was that intended ~~or did we miss something at the time of repainting the template~~? Looks bad to me. If the majority thinks otherwise, please close Issue.

UPD
Sorry, I forgot that this template was not recolored :)

![Screenshot_1](https://user-images.githubusercontent.com/8440661/122439545-67eb6b80-cfa4-11eb-9dc0-3fbf55357b39.png)

**Comment by brianteeman** [comment]
In the admin template there is 
```
.table tbody th {
    font-weight: 500
}
```

This is not present in the front end template 

@drmenzelit is this intentional

**Comment by drmenzelit** [comment]
I don't think that is intentional, more probably missed at some point in the long history of Cassiopeia

**Comment by brianteeman** [comment]
For me it would be much better if cassiopeia used the full range of font weights as seen in atum #22317

**Comment by Kostelano** [comment]
PR https://github.com/joomla/joomla-cms/pull/34552
