### ISSUE TITLE
[4.0] [Front] Inadequate arrow in directory navigator (paths)

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34545]
### Steps to reproduce the issue
Install demo data. In the frontend, select the item to create an article, then select the CMS CONTENT -> Image. Go to some directory deeper. Note the dimensions of the arrow in the directory navigator (paths). The problem is reproduced in Mozilla (unfortunately, there is no other browser to check).

![Screenshot_1](https://user-images.githubusercontent.com/8440661/122440313-1becf680-cfa5-11eb-8229-7252e04d6f86.png)

**Comment by brianteeman** [comment]
from the look of that the css for the media manager is missing

**Comment by laoneo** [comment]
#34624 should fix this issue but https://github.com/joomla/joomla-cms/pull/34621 needs to be tested and merged first.

**Comment by laoneo** [comment]
Can you guys give https://github.com/joomla/joomla-cms/pull/34624 a test?
