### ISSUE TITLE
[4.0] [Front] Missing JGLOBAL_LEARN_MORE

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34543]
### Steps to reproduce the issue
Make sure there are no contacts on the site. Install demo data (or create a menu item to create an article). In the front, select the item for creating an article, in the editor, select **CMS CONTENT -> Contact**. Constant JGLOBAL_LEARN_MORE will be skipped in the modal window.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/122438797-c2d09300-cfa3-11eb-8c00-be823601566d.png)

**Comment by brianteeman** [comment]
please test #34550

**Comment by alikon** [comment]
closing as we have a pr
