### ISSUE TITLE
[4.0] [Front] Endless lines of errors in Media Manager

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34548]
### Steps to reproduce the issue
A problem that still occurs today in several places on RC2. For example, https://github.com/joomla/joomla-cms/issues/33450.

For example, when we click on the Delete button, we get an infinite number of error lines. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/122443428-41c7ca80-cfa8-11eb-8ccb-22da54e69038.png)

**Comment by brianteeman** [comment]
_I believe this was reported already by @PhilETaylor_

**Comment by PhilETaylor** [comment]
Duplicate of https://github.com/joomla/joomla-cms/issues/33306

**Comment by alikon** [comment]
thanks for closing it
,,, appreciated
