### ISSUE TITLE
[4.0] [Front] Need left indent for button bar

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34547]
### Steps to reproduce the issue
When creating an article in the front in the editor, select CMS CONTENT - Image, click on the UPLOAD button. Note that its focus is limited to the left side. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/122442026-cf0a1f80-cfa6-11eb-9d49-cc65c2a1af48.png)

**Comment by Kostelano** [comment]
This applies to all button bars that are in modals on the left.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/122442244-0aa4e980-cfa7-11eb-81fb-ea7c9cc7f3cf.png)

**Comment by brianteeman** [comment]
Same problem as #34545

**Comment by pinak3748** [comment]
![Articles_ Edit - pinak - Administration - Brave 24-06-2021 11_35_04](https://user-images.githubusercontent.com/59458280/123211259-d23e6780-d4e0-11eb-9394-04373e5f0c44.png)

The above issue #34547 has been solved.

**Comment by brianteeman** [comment]
@pinak3748 That is a screenshot from joomla 3

**Comment by rhythmjain32** [comment]
![image](https://user-images.githubusercontent.com/60003625/123299741-78b55780-d537-11eb-9fa1-1329431cde2f.png)
I cannot find the issue in #34547 . It seems to be working fine in joomla 4.0

**Comment by rhythmjain32** [comment]
![image](https://user-images.githubusercontent.com/60003625/123300496-448e6680-d538-11eb-9e7a-49e662550995.png)
I could not find the issue in #34547. It seems to be correct in joomla 4.0

**Comment by brianteeman** [comment]
@rhythmjain32 please read the original bug report more carefully

> When creating an article in the **front** in the editor

**Comment by pinak3748** [comment]
![Screenshot 2021-06-24 224918](https://user-images.githubusercontent.com/59458280/123306093-799db780-d53e-11eb-9384-9afc48d37bab.png)
I have navigated through the file according to the provided bug report by @Kostelano but still not seen the bug.

**Comment by Kostelano** [comment]
You will be looking for her for a long time in the control panel

**Comment by brianteeman** [comment]
I believe this has now been resolved - please confirm

**Comment by rhythmjain32** [comment]
I have checked this issue on chrome, and it is working perfectly.

**Comment by Kostelano** [comment]
Fixed, closed.
