### ISSUE TITLE
[4.0] [Front] Legends in the fields. Are they needed or not?

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34549]
### Steps to reproduce the issue
Install demo data. In the frontend, select the item to create an article. Notice the AUTHOR (a custom field that is created with demo data), Publish, Metadata tabs. One tab has a legend, others don't. Out of sync.

![Screenshot_3](https://user-images.githubusercontent.com/8440661/122444825-9ae42e00-cfa9-11eb-8047-39611f082393.png)

![Screenshot_1](https://user-images.githubusercontent.com/8440661/122444796-9586e380-cfa9-11eb-990b-625fe5c15ff8.png)

![Screenshot_2](https://user-images.githubusercontent.com/8440661/122444812-9881d400-cfa9-11eb-92fb-59f7ef0cc0a5.png)

Now, for example, create a CREATE CONTACT menu item in the control panel. Go to the front again and try to make contact. Now check out the tabbed legends here.

![Screenshot_4](https://user-images.githubusercontent.com/8440661/122445061-d7b02500-cfa9-11eb-9b3f-de8ea458374c.png)

![Screenshot_5](https://user-images.githubusercontent.com/8440661/122445073-db43ac00-cfa9-11eb-8392-0cb9953941c5.png)

One thing is clear - there is no single solution. I think similar places can be found 50/50 in other extensions. I am ready to review all such pages and report them if a clear decision is made whether the legends on the tabs are needed or not.

My opinion is that duplication of the tab title is absolutely useless. Correct me if I do not understand why this is.

**Comment by brianteeman** [comment]
A fieldset must have a legend.

In some tabs there are multiple fieldsets but in others there is only one hence the apparent useless duplication. However it is a requirement to have a legend

**Comment by chmst** [comment]
We are doing all for disabled users and sometimes this results in bad UX for sighted users. Less noise would be appreciated.

**Comment by brianteeman** [comment]
@chmst I think something was lost in translation with your comment

**Comment by chmst** [comment]
Sorry, it is so hot today. 
Accessibility requires that fields are grouped into fieldsets and fieldsets need a legend. But I also feel, as sighted user, that there is information noise when the same information appears several times. I feel it "too much" if the tab and the legend show the same information.

**Comment by brianteeman** [comment]
> . I feel it "too much" if the tab and the legend show the same information.

I understand what you are saying (and while I personally dont see a problem) I know that if some tabs have visible fieldset legends and others do not then people will report that as a bug.

**Comment by chmst** [comment]
I have a PR for the missing character count, very attentive :) please test  #34563

Your remarks concerning the fieldset and legend are answered by @brianteeman, so maybe this issue can be closed?

**Comment by chmst** [comment]
Closing this for now as the bug is resolved and the question is answered.
