### ISSUE TITLE
Missing Option To Change Global Article Date For Ordering

### ISSUE THREAD

**Issue by David2376** [joomla/joomla-cms#34553]
### Steps to reproduce the issue
Go to Global Options - Article - Shared

### Expected result
There should be an option to change the default Date For Ordering (Created, Modified, Published, Unpublished).

### Actual result
The option to change the default Date For Ordering is missing. It is pre-set to Published with no way to change it globally. The only way to change it currently is to go to each menu item and manually change it under Blog Options.  

### System information (as much as possible)
Joomla 4.0.0-rc1![screen shot 2021-06-17 at 22 50 46](https://issues.joomla.org/uploads/1/d0744790a19bd5789abfd7d2f8968d66.png)
PHP 7.4.16

 

### Additional comments

![screen shot 2021-06-17 at 22 50 48](https://issues.joomla.org/uploads/1/9b57c42ed92954cc95567a1adb62557f.png)

**Comment by brianteeman** [comment]
Is this what you mean?

![image](https://user-images.githubusercontent.com/1296369/122483121-caa32e00-cfc9-11eb-8e72-c2a9f3eab5aa.png)

**Comment by richard67** [comment]
@chmst "New Feature" label? Why? In current 4.0-dev or RC 2 and maybe earlier versions it is implemented, see @brianteeman 's screen shot.

**Comment by richard67** [comment]
@David2376 Is your 4.0 RC 1 the result of a new installation, or has it an update history from previous versions? If you update to 4.0 RC 2, does the option shown in @brianteeman 's screen shot appear after that? If not: Can you try with a new installation of RC 2 (without any update history) and report back if that is whant you had in mind? The possibility to use "Unpublished" which you have mentioned is not implemented, but that would not make any sense because if it's not published you won't see it in e.g. a blog.

**Comment by brianteeman** [comment]
Shouldn't matter which version you are using as this has been available for a very long time

**Comment by richard67** [comment]
> Shouldn't matter which version you are using as this has been available for a very long time

@brianteeman Yes, but why does his screenshot not show it?

**Comment by brianteeman** [comment]
He is looking at a different tab

**Comment by chmst** [comment]
> 
> 
> @chmst "New Feature" label? Why? In current 4.0-dev or RC 2 and maybe earlier versions it is implemented, see @brianteeman 's screen shot.

Forgotten  param , sorry

**Comment by richard67** [comment]
> He is looking at a different tab

@brianteeman No, the first screenshot is the com_content options, tab "shared", like in your screenshot. Or am I missing something?

**Comment by brianteeman** [comment]
Article order has to be set to a date related option before the setting is shown

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/blob/e2a44b7686cdacacfa2873abbad85a3a05a76fab/administrator/components/com_content/config.xml#L956-L967

**Comment by richard67** [comment]
> Article order has to be set to a date related option before the setting is shown

Ahh ... I see ... makes sense.

@David2376 The reason why you can't see the field for selecting which date to be used (see screenshot above) is because you have chosen "Title alphabetical" for the article order. If you chose "Oldest first" or "Most recent first" for the article order, the field to select the date (created, modified or published) will be shown. If that's what you were looking for, please close this issue. Thanks in advance.

**Comment by brianteeman** [comment]
Actually thinking about it a bit more with a coffee we should remove the showon. That way you can set a global default for the date  to be used when you select a date ordering in a menu etc

**Comment by richard67** [comment]
> Actually thinking about it a bit more with a coffee we should remove the showon. That way you can set a global default for the date to be used when you select a date ordering in a menu etc

Hmm, makes sense ... now with the showon you can't do that.

**Comment by brianteeman** [comment]
I will take a look at fixing that after coffee. Need to make sure it bubbles though correctly etc and probably have to check other components

**Comment by brianteeman** [comment]
Please check and test #34553

**Comment by richard67** [comment]
> Please check and test #34553

@brianteeman That's the number of this issue here 😄 I guess you mean #34554 .

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34554 . Thanks in advance.

**Comment by richard67** [comment]
@brianteeman Your coffee seems to be good 😄

**Comment by David2376** [comment]
Yeah I figured it out....I wasn't selecting "Oldest First" or "Most Recent First". Sorry sometimes the lack of sleep gets the best of me! Issue marked as closed. Thanks guys.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34553">issues.joomla.org/tracker/joomla-cms/34553</a>.</sub>
