### ISSUE TITLE
[4.0] Media Manager scss needs to be rebuilt

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34559]
There are numerous bug reports regarding media manager in the front end and I have been able to track them down.

They are caused because of the use of atum variables which of course are not actually ever going to be available.

media manager scss should be template independent.

If it is necessary to add template specific scss for the media manager then that should be in its own scss that lives in the templates own folder and not in com_media

**Comment by brianteeman** [comment]
just to be clear without fixing this media manager is between useless and ugly on every frontend template

**Comment by dgrammatiko** [comment]
> media manager scss should be template independent.

If Joomla had a design system with known default css vars, then the media manager css would work fine with **any** template (that complies to the design system and that should have been the minimum compatibility requirement). The proposal was rejected a few years ago as the backend people decided that Bootstrap was the perfect design system for Joomla. Now the only viable solutions are, as you stated:
- make the com_media independent of the template (different colours, etc)
- require **every** front end template to roll their own com_media css

WIN.

**Comment by brianteeman** [comment]
for reference its not just colours it is all use of variables

**Comment by gorgonz** [comment]
Situation:
- use frontend
- Menu is located in the right sidebar,
- Editor is tinymce,
- Edit an article
- Drag the bottom/right corner ofcontent-area to the right, so overlapping the menu area

Result:
the background of the area will show the menu overlapping with the content

Question: Is this an effect, that has to do with this issue - or is it a separate issue?

**Comment by brianteeman** [comment]
@gorgonz that is nothing to do with the media manager

**Comment by brianteeman** [comment]
@wilsonge This really should be a release blocker.

**Comment by laoneo** [comment]
I made a proposal in #34621 to have the template variables generic. Any thoughts?

**Comment by brianteeman** [comment]
Closing this here. Left my _thoughts_ as a comment on the PR
