### ISSUE TITLE
[4.0] French language pack

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34557]
```
	<updateservers>
		<server type="collection" priority="1" name="Accredited Joomla! Translations"/>https://update.joomla.org/language/translationlist_4.xml
	</updateservers>
```

This is not correct as there should be a closing </server>

```
	<updateservers>
		<server type="collection" priority="1" name="Accredited Joomla! Translations">
			https://update.joomla.org/language/translationlist_4.xml
		</server>
	</updateservers>
```

**Comment by zero-24** [comment]
Yes this has been reported to the TT already and will be fixed with the next release of the pack.

**Comment by brianteeman** [comment]
ok - thanks . there was nowhere else that I could to see to report this

**Comment by zero-24** [comment]
> ok - thanks . there was nowhere else that I could to see to report this

I send my mail to the contact listed on the downloads portal. ;-)
