### ISSUE TITLE
[3.10] [4.0] Pre-Update Check - Doesn't repect Minimum Extension Stability

### ISSUE THREAD

**Issue by piotr-cz** [joomla/joomla-cms#34555]
### Steps to reproduce the issue

1. Install extension with stability lower than *Stable* (ie. Beta, Release Candidate) and updates in manifest with stability lower than *Stable*

1. Set up Minimum Extension Stability to: Development  
   *Administrator > Global Configuration > Installer*

1. Start Joomla update from 4.0.0-rc.1 to 4.0.0-rc.2

### Expected result

Extension Pre-Update Check should not show extension in *Update Information Unavailable* section

### Actual result

Extension Pre-Update Check shows extension in *Update Information Unavailable* section.

### System information (as much as possible)

Joomla 4.0.0-rc.1

### Additional comments

Extension Pre-Update Check doesn't use options set up in the Installer component to determine compatibility with Joomla 4:

The `checkCompatibility` method

https://github.com/joomla/joomla-cms/blob/eef2c1362ffebfffd800ed36084e013206674719/administrator/components/com_joomlaupdate/src/Model/UpdateModel.php#L1578

should use same logic as `getUpdateInformation` method

https://github.com/joomla/joomla-cms/blob/eef2c1362ffebfffd800ed36084e013206674719/administrator/components/com_joomlaupdate/src/Model/UpdateModel.php#L244

when accessing `Joomla\CMS\Updater\Update::loadFromXml`:

https://github.com/joomla/joomla-cms/blob/eef2c1362ffebfffd800ed36084e013206674719/libraries/src/Updater/Update.php#L477

**Comment by zero-24** [comment]
Can you confirm that issue with 3.10 too? So it would be an issue to be patched in 3.10 than.

**Comment by piotr-cz** [comment]
I can only confirm by looking at the Joomla 3.10 codebase - yes the issue should be present as well

https://github.com/joomla/joomla-cms/blob/376e44131f518f3df11a9390344659ef4d9139c0/administrator/components/com_joomlaupdate/models/default.php#L1733

**Comment by zero-24** [comment]
Ok thanks, then this should be fixed in 3.10 and than merged up to 4.0

**Comment by zero-24** [comment]
A PR for Joomla 3.10 has been done here: https://github.com/joomla/joomla-cms/pull/34772 Please test it @piotr-cz
