### ISSUE TITLE
[4.0] Tooltip for "pinned" in banners 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#34566]
### Steps to reproduce the issue
Add a few banners to the banner component, some pinned and some unpinned.
Compare tooltips for publish button and pinned button.

### Expected result
If the user can change the pinned state, the tooltip shows that (as for published button)

### Actual result
![grafik](https://user-images.githubusercontent.com/1035262/122637306-249d1400-d0ee-11eb-87ec-a1e272c3569e.png)

**Comment by brianteeman** [comment]
its the same problem you identified with com_content where the tips are mixing a "state" message and an "action" message

**Comment by brianteeman** [comment]
and the code for this tooltip is different to others :(

**Comment by PrathameshPawar119** [comment]
According to problem description I have modified tooltip messages on UI
Can you please tell  me is it right or any further modifications ?

1. While Banner in unpinned stage --> Pin this Banner
![image](https://user-images.githubusercontent.com/104665278/221433725-85613d1c-1104-4e45-b2f9-e7cb43f4a91d.png)

2. While Banner in pinned stage --> Unpin this Banner
![image](https://user-images.githubusercontent.com/104665278/221433802-87e7a707-0d17-4410-808a-68fbbfa7fee7.png)

tooltip just telling what action to perform on click.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39952 . Thanks in advance.
