### ISSUE TITLE
[3.10] Support of new Joomla 4 features

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#34561]
I have created an extension for 3.9. Last version here: https://github.com/astridx/pkg_agosms/releases/tag/v3.0.2

For 4.0 I have rebuilt it. Version here: https://github.com/astridx/pkg_agosms/releases/tag/v4.0.0

For the Pre Update Checker I now need a version that runs on 3.10 and 4.0. Draft here: https://github.com/astridx/pkg_agosms/releases/tag/untagged-cd01d507bd3028dbbf84

My Draft (mainly the 4.0 version, only the minimum Joomla Version in the install script is different) shows this error message while install on 3.10.

![4](https://user-images.githubusercontent.com/9974686/122610304-ae61c880-d07f-11eb-936e-e7e1605ef9e7.png)

Am I doing something wrong or is there no support for the dashboard  under 3.10? What is the best way for me to update under 3.10 before upgrading to Joomla 4.0 in this case?

**Comment by zero-24** [comment]
There are no dashboards in 3.10 when you are talking about the new 4.x dashboards? So it would make sense to me that the method does not exist, i'm missing something?

**Comment by astridx** [comment]
Sorry. I did not express myself well. I mean this function:
https://github.com/joomla/joomla-cms/pull/28027
If I see it correctly, my J4 version is not installable in 3.10 because of this.  And my 3.9 version is not compatible with j4. 

Is there a workaround for this case for the Pre update checker?

**Comment by zero-24** [comment]
> If I see it correctly, my J4 version is not installable in 3.10 because of this. And my 3.9 version is not compatible with j4.

Well if thats the only thing you can try an version conditional right?

> Is there a workaround for this case for the Pre update checker?

I'm not sure whether i can follow you here?

**Comment by astridx** [comment]
@zero-24  Thanks for your answer and patience. I'll try asking it again in a different way. 

> Well if thats the only thing you can try an version conditional right?

This is my `update.xml`:

```
...
    <update>
        <downloads>
            my3.0.0.zip
        </downloads>
        <targetplatform name="joomla" version="3.[789]|10"/>
    </update>
    <update>
        <downloads>
            my4.0.0.zip
        </downloads>
        <targetplatform name="joomla" version="4.0.0"/>
    </update>
...
```

(https://github.com/astridx/pkg_agosms/blob/243b7a9e2c9b8f12e54a2f968a98c774a1996bff/agosms-update.xml#L579)

`my3.0.0.zip` only works on Joomla 3x and `my4.0.0.zip` only works on Joomla 4.x. 

Users of my extension see this picture, if they update to Joomla 3.10.

![5](https://user-images.githubusercontent.com/9974686/122636965-5e6d1b00-d0ec-11eb-961f-544484739d65.png)


Now I am asked what to do from users of my extension. 

The message in the Pre Update says that you should update. But the next version is offered only when Joomla 4.0 is installed. Some tried to update and get the error message I inserted above. That is why I do not allow to install on Joomla 4.x via installer script.

So far I answer the questions like this: I write, that my extension should be deactivated, the update to Joomla 4.0 should be done and then the new version of my extension can be installed via Joomla Updater. But even if everything is disabled, the message, that the extension should be updated still appears.

That does not looks right to me. 

Therefore I ask if I am missing something? Should I set something differently? Do I have the possibility to give a different information via the Pre Updater?

**Comment by zero-24** [comment]
> But even if everything is disabled, the message, that the extension should be updated still appears.

Hmm will have a look and check that, IIRC the intention was that once the extension is disabled it is not checked anymore given that it does not run any code too.

> So far I answer the questions like this: I write, that my extension should be deactivated, the update to Joomla 4.0 should be done and then the new version of my extension can be installed via Joomla Updater. 

Thats totally valid and intended by the words "check the developer docs" or something similiar in the pre upgrade checker.

> Therefore I ask if I am missing something? Should I set something differently? Do I have the possibility to give a different information via the Pre Updater?

IIRC the intention was to show "hey once you are on 4.x you have to update this extension" But will have a closer look into this and come back here.

Maybe @GeraintEdwards would like to take a look here too?

**Comment by astridx** [comment]
I am closing this issue. I decided against the offer for an update. 
Although the extensions are disabled and the entry for Joomla 4 is removed from the Update Server XML, the entry is displayed in my Pre Update Checker.
Maybe it's also my environment or my different expectations when no one else is bothered.
