### ISSUE TITLE
Error while testing upgrade from 3.9.27 to 4.0.0

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#34562]
### Steps to reproduce the issue

1. Install Joomla 3.9.27
2. Switch  the Update Channel to “Custom URL” and and the Minimum Stability option to “Alpha” set the Custom URL to “https://update.joomla.org/core/nightlies/next_minor_list.xml”
Now you get, update to the  3.10.0 Alpha Version.
3. Switch  the Update Channel to “Custom URL” and and the Minimum Stability option to “Release Candidate” set the Custom URL to “https://update.joomla.org/core/nightlies/next_major_list.xml”
Now you get, update to the latest 4.0 Development Version.

### Expected result

Update works

### Actual result

After the update to 3.10 
![1](https://user-images.githubusercontent.com/9974686/122613511-40200480-d085-11eb-9fa9-054c708c83c8.png)

I see this message:
![0](https://user-images.githubusercontent.com/9974686/122612976-59748100-d084-11eb-8ed0-eebc2f5d7410.png)

After the update to 4.0.0 
![8](https://user-images.githubusercontent.com/9974686/122613391-0fd86600-d085-11eb-8a5d-1c0e531bfcac.png)

I see this message:
![7](https://user-images.githubusercontent.com/9974686/122611720-131e2280-d082-11eb-9bef-138e80b297fa.png)

The Pre Update Checker has no entry, because it was a fresh installation
![00](https://user-images.githubusercontent.com/9974686/122613576-5e860000-d085-11eb-80ef-1a0bd24de524.png)

### System information (as much as possible)

php: Linux php80_mysql 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64
dbserver: mysql
dbversion: 5.7.34
dbcollation: latin1_swedish_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 8.0.7
server: Apache/2.4.41 (Ubuntu)
sapi_name: apache2handler
version: Joomla! 3.9.27 Stable [ Amani ] 25-May-2021 15:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:89.0) Gecko/20100101 Firefox/89.0

safe_mode: false
display_errors: true
short_open_tag: false
file_uploads: true
magic_quotes_gpc: false
register_globals: false
output_buffering: true
open_basedir: 
session.save_path: xxxxxx
session.auto_start: 0
disable_functions: pcntl_alarm,pcntl_fork,pcntl_waitpid,pcntl_wait,pcntl_wifexited,pcntl_wifstopped,pcntl_wifsignaled,pcntl_wifcontinued,pcntl_wexitstatus,pcntl_wtermsig,pcntl_wstopsig,pcntl_signal,pcntl_signal_get_handler,pcntl_signal_dispatch,pcntl_get_last_error,pcntl_strerror,pcntl_sigprocmask,pcntl_sigwaitinfo,pcntl_sigtimedwait,pcntl_exec,pcntl_getpriority,pcntl_setpriority,pcntl_async_signals,pcntl_unshare,
xml: true

### Additional comments

I tryed the update like explained here: https://www.joomla.org/announcements/release-news/5838

"Go to the Joomla Update Component Options and switch the Update Channel to “Testing” and the Minimum Stability option to “Alpha”." did not offer me an update.

Also "Switch the Update Channel to “Custom URL” and the Minimum Stability option to “Development” and set the Custom URL to “https://update.joomla.org/core/test/310to4_list.xml”" did not offer me an update.

What is my mistake?

**Comment by zero-24** [comment]
Hmm is the database up-to-date when you start updating? The SQL error does not make sense on a quick look as the plugins are part of the package for a long time now.

Will check the update server xmls whethere there are issues and why it does not work for you.

**Comment by astridx** [comment]
I have freshly installed this for this issue to rule out other things. Could it be because of PHP 8?

**Comment by richard67** [comment]
@astridx Have you done all that in an empty folder? Or have you used a git clone and only checked out branch and pulled? In this case or if the folder was not empty at the beginning there might be old SQL files which have been removed later. E.g. between 4.0 Beta 7 and RC 1 files have been removed.

**Comment by richard67** [comment]
It cannot have anything to do with PHP 8.

**Comment by richard67** [comment]
I think the folder in which the 3.9.27 was installed was not empty and contained some remainders from experiments with J4 Beta 7 or earlier, and so there were some of the files present which have been removed with PR #34139 in J4.

**Comment by astridx** [comment]
Thanks for your answers. No. It can't be the files. I installed it fresh in real. If no one else is having the problem, it's probably my environment.
