### ISSUE TITLE
[4.0] Broken LIST of news feeds

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34573]
### Steps to reproduce the issue
Create menu items with a list of articles and a list of news feeds (pre-install demo data AND create a news feed). Compare what we get in the front:

List of articles in category

![Screenshot_2](https://user-images.githubusercontent.com/8440661/122673463-3d362880-d1d9-11eb-8bbc-2ca1f502fec0.png)

List of news feeds in category

![Screenshot_1](https://user-images.githubusercontent.com/8440661/122673462-3c9d9200-d1d9-11eb-90fc-ac1699b5c250.png)

**Comment by brianteeman** [comment]
Confirmed. The list of newsfeeds in a category is displayed as a list and not a table. Which means that various options such as show table headers dont work

**Comment by brianteeman** [comment]
However I also note that this is the same in joomla 3

**Comment by chmst** [comment]
Indeed, seems that this is not used very often.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34573">issues.joomla.org/tracker/joomla-cms/34573</a>.</sub>

**Comment by brianteeman** [comment]
I suggest that the layout is kept as a list and the non-working option to display table headers is simply removed.

**Comment by chmst** [comment]
agree. It needs only b5 classes list-group and list-unstyled in the ul, list-group-item in the <li

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34573">issues.joomla.org/tracker/joomla-cms/34573</a>.</sub>

**Comment by Kostelano** [comment]
> 
> 
> Indeed, seems that this is not used very often.

I just wanted to write that this is probably about as much in demand as it was with FTP :)

**Comment by brianteeman** [comment]
Please test #34583
