### ISSUE TITLE
[4.0] [Workflows] Incorrect filter operation / Transitions

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34574]
### Steps to reproduce the issue
Include in the content options Workflows. Install demo data. Go to the **Workflows -> Transitions** page, click on the Current Stage column, pay attention to the events in the filter. By the way, there is no Current Stage. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/122684920-15fb4d80-d211-11eb-8413-f2eeee414ad6.png)

**Comment by brianteeman** [comment]
Confirmed. The columns for Current Stage (aka from_stage) and Target Stage (aka to_stage) are both sortable by clicking on the column headers but they do not have a value in the filter_transitions.xml

**Comment by brianteeman** [comment]
Please test #34575
