### ISSUE TITLE
[4.0] Empty state of private messages for incoming only

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34587]
### Steps to reproduce the issue
An empty state is displayed if neither you nor you have ever sent a private message.

Create another user, give him administrator rights. Send him a private message. Now the empty state of the page is not displayed, since it is logical that something was happening in your mailbox (sending or receiving a message).

If you enter the database and physically delete the outgoing message record, the empty state will be displayed again.

Based on this, there are several questions.

1. Why do we NOT display sent private messages? It seems to me that this information could be useful sometime LATER, when you want to remember how your conversation with another administrator went.

2. If point 1 will not be implemented by anyone (although it is logical that it is needed), then the empty state should be corrected as "only for incoming". Those. as soon as we have no incoming messages (we did not receive them or deleted them completely), show the empty status page again.

@PhilETaylor, I will mark you as you've been dealing with blank state pages and I wonder what you think about that.

In general, this is certainly not a bug, but simply monitoring the functionality of a particular component.

**Comment by PhilETaylor** [comment]
> Why do we NOT display sent private messages? 

This is historic, Private Messages has not really been used by Joomla historically and therefore no considerable investment has been made into it... Feel free to PR this new feature against the `4.1-dev` branch for consideration by the maintainers

> Then the empty state should be corrected 

Empty state is a "first out-of-the-box view", not a replacement "there are no messages" view.  It is meant to be a pretty page that provides guidance and help on understanding what the feature is and how to use it. It is not a replacement for "there are no messages" view which has its own place and its own right to be there.

**Comment by Kostelano** [comment]
Thanks for the answer. I agree. I'll close for now as there is no error. I'm a little confused that I was not taking the empty state page as intended :)
