### ISSUE TITLE
404 error when no association in articles/menus

### ISSUE THREAD

**Issue by fontanil** [joomla/joomla-cms#34582]
### Steps to reproduce the issue
Create a site with two or more languages then add multilingual data samples.
Navigate from a language to the other works fine.
Add a menu link on a new article in one language (no association because it's no article nor menu link on the other language).
Open this menu link to display the article. Then change to the other language.

### Expected result
Home page expected

### Actual result
404 error: article not found

### System information (as much as possible)
Local and remote sites
Joomla! 4 RC2 

### Additional comments
No error on a Joomla! 3 multilingual website migrated to 4 RC2

**Comment by richard67** [comment]
@fontanil I can't reproduce this with a new installation of current 4.0-dev.

Can you provide more details?
- Does the article without association belong to a category in the same language than the article? Or does it belong to "Uncategorized", which is for all languages?
- Does the menu item of type "Single Article" which points to that article have the same language than the article?
- Which languages did you use?
- SEO settings in Global Configuration - Site

**Comment by fontanil** [comment]
@richard67 
The article belongs to a category "french"
The menu links uses the same language
I'm using french fr-FR, english en-GB and sometimes german de-DE
I tried without and with SEO

**Comment by richard67** [comment]
Hmm, that seems to be the same what I did. But there must be some difference.
Could you try with latest nightly build?

**Comment by fontanil** [comment]
I'm sorry, the language change was not saved, it was left on "all". :-(
I created a new site with three languages, installed the multilingual samples, then added three menu itmf "Single article", created the articles and set them to their language, set the menu items to their language and it works fine now.
Sorry for this discussion which is probably due to an error on my part on the previous test sites.

**Comment by richard67** [comment]
@fontanil No problem. Thanks for reporting back.
