### ISSUE TITLE
[4.0] Tooltip not working on "New" button

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#34594]
### Steps to reproduce the issue
Create a "Articles - Category List" menuitem and visit that while logged in with a user that can create articles.

### Expected result
The new button should have a tooltip. At least the code suggests it:
![image](https://user-images.githubusercontent.com/1018684/122898839-83ab9480-d34b-11eb-9f7a-7fe03e4a8601.png)

### Actual result
![image](https://user-images.githubusercontent.com/1018684/122898646-56f77d00-d34b-11eb-940f-258f44068148.png)

No tooltip is shown, only the regular "title" display is shown by the browser.

### Additional comments
I think this one (and probably others) were missed when the tooltips were changed to the CSS based ones.

**Comment by Bakual** [comment]
Just to be clear - I don't mind if there is a tooltip or not. We could as well remove the class and title attributes here. It's just not my decision. Just the current status is wrong.
Maybe @brianteeman has an opinion on this.

**Comment by brianteeman** [comment]
I would do this
`<a href="/link"><span class="element-invisible">Submit article</span>New</a>`

but ask the accessibility team

**Comment by chmst** [comment]
Will make a PR in the evening.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34601 . Thanks in advance.
