### ISSUE TITLE
[4.0] Buttons with underline in version history

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34592]
### Steps to reproduce the issue
Sorry for the "Russian" screenshot, but it's clear where to look.

Enable the ability to store versions in the content settings on the edit form contribution. Save any article multiple times. then use the VERSION button.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/122799708-b95c6900-d2ca-11eb-9f3c-56b55088a064.png)

**Comment by chmst** [comment]
Confirmed. What scares me more that the underline is the lock icon without a tooltip, contrary to other views

**Comment by brianteeman** [comment]
please test #34614

**Comment by brianteeman** [comment]
@chmst the lock icon here is just a visual indicator that the item is marked to keep forever. The column is "keep forever" and the text is "yes" so there is no need for a tooltip. Its not the same as the other uses of the lock icon which is for checked out.
