### ISSUE TITLE
[4.0] No option to put off title in readmore button in newsflash modul

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#34609]
### Steps to reproduce the issue
Joomla 4 with sample data
Go to Content -> Options, under "Articles" you will find two switcher for the read more button:

![grafik](https://user-images.githubusercontent.com/9153168/123102548-78cd2e80-d435-11eb-99a9-56c02c3e45eb.png)

The two options are on.
Set "Read More" Link to "hide". The second option disappears (but it is still set to "show")

Go to site modules and look at the options in the newsflash module (Latest Posts in position top-a). You can show or hide the read more button, but you can't turn off the title in the button. You have to go to Content -> Options, turn on read more again, then turn off the title and turn off read more again... 

### Expected result
You can turn off titles in read more buttons directly in the newsflash module

### Actual result
If you want to have titles in the read more buttons in a blog layout, you will have automatically titles in the read more buttons in newsflash. It is not possible to configure articles and module differently.
In comparison the module Articles - Category has an option to turn on/off titles in the buttons.

Another problem is that you will not see the option for putting off titles in Content -> Options if you have already set read more to hide.
In J3 the two options are always visible.

**Comment by brianteeman** [comment]
ah - now I understand ;)

You are correct that the option to use titles or not should be in the newsflash module - even if that was not an option in j3

> Another problem is that you will not see the option for putting off titles in Content -> Options if you have already set read more to hide.

Assuming the module is fixed then that isnt a problem is it?

**Comment by chmst** [comment]
And I see that labels for Read more are different in languagea files. In category a description is added to the read-more optio, but not in global configuration
(but not in scope of this PR)

**Comment by brianteeman** [comment]
> In comparison the module Articles - Category has an option to turn on/off titles in the buttons.

I can't see that option. For me both Articles - Category and Articles - Newsflash only have an option to show/hide the read more link

**Comment by B1TSH3LL** [comment]
I want to work on this issue as an Gsoc Contributer. Can you please assign this to me. And provide me exact resources for the issues required to get the work done ?

**Comment by rdeutz** [comment]
closing because we have a PR #43457
