### ISSUE TITLE
[4.0] Modal window multilingual status not a11y

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#34606]
### Steps to reproduce the issue
Build a multilingual site. 
Activate the multilingual status button in the top bar and a model shows um with tow tables

### Expected result
The content is accessible 

### Actual result
The first table is not a table but a list - maybe a definition list.
The second table has not table caption. 

![grafik](https://user-images.githubusercontent.com/1035262/123099261-5259c400-d432-11eb-8213-a937d4c1a2ee.png)

**Comment by brianteeman** [comment]
Why is it not a table?
It has a table header with columns and then table rows with cells that match the information in the columns

**Comment by richard67** [comment]
> Why is it not a table?
> It has a table header with columns and then table rows with cells that match the information in the columns

Correct. It has columns „Details“ and „Status“. @chmst What‘s wrong with that?

**Comment by chmst** [comment]
Personally I would see the details part more as definition list, not as a table and it is hard to read on big screens. For me it looks much more like a layout table than a data table. 
But not worth to start a dicussion. 

The issue is that the tables don't have a table caption.

**Comment by brianteeman** [comment]
Please test #37559

**Comment by richard67** [comment]
Closing as having a pull request. Please test https://github.com/joomla/joomla-cms/pull/37559 . Thanks in advance.
