### ISSUE TITLE
[4.0] Replace title by tooltip categories

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#34602]
### Steps to reproduce the issue
Got to categories overview. Hover one of the badges in the list.

![grafik](https://user-images.githubusercontent.com/1035262/122999556-b63aa900-d3ae-11eb-97b7-c4d6dca29dda.png)

### Expected result
A tooltip which says: Show published / unpublished.. items. 
similiar to the publish buttons

![grafik](https://user-images.githubusercontent.com/1035262/123000288-ae2f3900-d3af-11eb-8878-f425f386d317.png)

### Actual result
see above - browser title without information.

**Comment by brianteeman** [comment]
Please test #34615
