### ISSUE TITLE
[4.0] [Privacy] Invalidate button on empty page

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34600]
### Steps to reproduce the issue
Go to **Users -> Privacy: Consents** page. If your site has valid consents, delete them through the database. Note that the empty status page has a **Invalidate all Consents** button. First, it is clearly superfluous, since there is not a single user consent. Secondly, clicking on the button raises a warning `No item(s) selected`.

Not a crime, but there is no expediency in such a button.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/122978029-b763da00-d39e-11eb-9b48-07915947cd4d.png)

In fact, in other places there are a lot of similar examples, but there, as a rule, buttons for creating something.

**Comment by Kostelano** [comment]
A great example to implement is the message page after installing or updating Joomla. The HIDE ALL button is displayed only if there are messages in front of our eyes, but there is no button on a empty page.

**Comment by brianteeman** [comment]
I am unable to replicate this
![image](https://user-images.githubusercontent.com/1296369/123059752-fe36eb80-d401-11eb-8195-10f1a0520e77.png)

**Comment by Kostelano** [comment]
Hmm .. Thanks. Perhaps due to the fact that I discovered my problem after manually deleting user consent records in phpmyadmin. Returning to the admin area, I saw a button.

I close it.
