### ISSUE TITLE
[4.0] Field has "optional" in the label although the field is required

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#34611]
### Steps to reproduce the issue
Create a contact with contact form
Activate the plugin "Content - Confirm Consent" and configure an article to be linked with.
Go to the contact in frontend
The field "Privacy Note" is a required field, you can't send the form without check in the box. But besides the label you will see the text "(optional)"

### Expected result
No optional if field is required

### Actual result
Wrong "optional" text
![grafik](https://user-images.githubusercontent.com/9153168/123118947-5f32e380-d443-11eb-9820-819817b4c8ab.png)

**Comment by brianteeman** [comment]
I'm sure we have had this before

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/22194

**Comment by drmenzelit** [comment]
Same behaviour with a radio custom field 
![grafik](https://user-images.githubusercontent.com/9153168/123125668-0108ff00-d449-11eb-9539-acd49247b186.png)

**Comment by drmenzelit** [comment]
> #22194

I think the Confirm Consent plugin needs a rewrite... but for the beginning it seems that removing components/com_contact/layouts/joomla/form/renderfield.php solves the problem...

**Comment by drmenzelit** [comment]
Closing with PR #34617
