### ISSUE TITLE
[3.9] Pagination is not using the layouts

### ISSUE THREAD

**Issue by angieradtke** [joomla/joomla-cms#34628]
### Steps to reproduce the issue
We used the pagination.php file, which we could copy to the template and overwrite it  there. 
This technique is now deprecated and has been replaced by the layouts.  
Unfortunately, this only works halfway.
 I noticed that  while overwriting the output by customizing the  layouts  JQuery is still pulled, although I couldn't find anything in my code.
 
 I haven't checked yet if this is still the case in 4.0.
File: libraries/src/Pagination/Pagination.php
Example:
`
   if (function_exists('pagination_list_render'))
			{
				\JLog::add('pagination_list_render is deprecated. Use the layout joomla.pagination.list instead.', \JLog::WARNING, 'deprecated');
				$listOverride = true;
			}
`

@Hackwar

**Comment by brianteeman** [comment]
Not enough information to go on.

**Comment by brianteeman** [comment]
No idea what this issue is about or what is expected. Maybe the bug squad should review it and make a decision to close?

**Comment by richard67** [comment]
@angieradtke What's the problem? That jQuery is pulled and you don't know why? I'm not sure if I get this issue right. Have you meanwhile found time to check if it is also an issue with J4?

**Comment by Hackwar** [comment]
The problem is, that the pagination class throws a deprecation notice that the usage of the pagination file function thing-a-ma-bob is deprecated, but actually doesn't seem to use the layouts its suggesting in that same deprecation notice.

**Comment by richard67** [comment]
> The problem is, that the pagination class throws a deprecation notice that the usage of the pagination file function thing-a-ma-bob is deprecated, but actually doesn't seem to use the layouts its suggesting in that same deprecation notice.

@Hackwar I see. Do you know how it's in J4? And what would you suggest to do?

**Comment by Hackwar** [comment]
I didn't look into this in J4 and basically only looked at this half a year ago. I would have to start from scratch as well.

**Comment by Fedik** [comment]
Should use `$pagination->getPaginationLinks($layout)`, 
if `$layout` is empty then will be used default `joomla.pagination.links`.

https://github.com/joomla/joomla-cms/blob/88b03dd506233117f7225140387ad0ad365d6a5f/libraries/src/Pagination/Pagination.php#L436

To customize the pagination, can create an override for layout `joomla.pagination.links`.

**Comment by Fedik** [comment]
I see that default Admin tables still use `$pagination->getListFooter()` wich uses of `template-name/html/pagination.php`,
Deprecation just means that we should  switched to `$pagination->getPaginationLinks($layout);` that will use `joomla.pagination.links`.

~~Tricky issue, it still need to update all our list view to use new method.~~

**Comment by Fedik** [comment]
Hm, but `$pagination->getListFooter()` is proxy to `$pagination->getPaginationLinks()` :)
So yeah, use override for `joomla.pagination.links` and delete `emplate-name/html/pagination.php` if your template use it. 

Sorry for confusing :)

**Comment by richard67** [comment]
@Fedik So it can be closed again?

**Comment by Fedik** [comment]
Yeap ;)
