### ISSUE TITLE
[4.0] Comment :  @see    \JControllerLegacy

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#34626]
### Steps to reproduce the issue

Inspect the code - there are lots of these comments, but a Class JControllerLegacy (or CotrollerLegacy) does no longer exist

**Comment by chmst** [comment]
There are alos lots of Comments 	 * @return  static  A \JControllerLegacy  ....   which should be changed

**Comment by chmst** [comment]
@wilsonge what do you think here? Is removing comments and updating @return to
 * @return static A BasicController 
 a good idea?

**Comment by wilsonge** [comment]
I've removed the @see references just now. I think 

`	 * @return  static  To allow chaining.`

Might be good enough? I don't see any need to reference the class name to be honest - the static reference will deal with that - we just need to mention why we do it.

**Comment by brianteeman** [comment]
@chmst is this resolved for you now after @wilsonge changes?
