### ISSUE TITLE
Joomla 4.0 Beta8 Article & Menu Access Does Not Show User Created User Group

### ISSUE THREAD

**Issue by jcss** [joomla/joomla-cms#34631]
#### Steps to reproduce the issue
Create a new user group named Registered-1
Open an existing Content Article
In Access box click down arrow to display user groups

#### Expected result
Registered-1 should be in list

#### Actual result
Only Joomla installed user groups are listed; Registered-1 is not listed

**Comment by brianteeman** [comment]
The access dropdown displays levels not groups

**Comment by chmst** [comment]
Closing - not an issue
