### ISSUE TITLE
[4.0] Not possible to use an icon as menu item

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#34639]
### Steps to reproduce the issue
A user wants to build a menu with icons instead of texts. 

He enters "icon-eye" as link class (or another class see issue #30793)
and sets displlay menuTitle off

![grafik](https://user-images.githubusercontent.com/1035262/123604516-302dc080-d7fb-11eb-9de3-968e78db2116.png)

### Expected result
Same behaviour as with images:  
If display menuTitle is off, show only the icon with visually hidden Menu Title as Text

### Actual result
The icon is displayed (no aria-hidden = true), the menu Item title also is displayed (but with wrong font) also if "display menu title" is off

![grafik](https://user-images.githubusercontent.com/1035262/123610057-86513280-d800-11eb-8c40-b986e88ea887.png)

**Comment by brianteeman** [comment]
Has this ever been possible? I know in Joomla 3 I used an image to achieve this

**Comment by brianteeman** [comment]
The issue of the wrong font when the icon class is used has been raised before. I believe it is caused because fontawesome is classed as a serif font

**Comment by chmst** [comment]
Same in J3 - probably never tried this before without override.

**Comment by chmst** [comment]
If it were possible to use an icon in the same way as an image it can be made a11y and displayed independent of the menu item title.

**Comment by brianteeman** [comment]
At this time that would need quite a bit of markup change in the menu module. Because of the way the icon changes the font it needs be a separate class and not a class on the link itself. Which also means it would have to be a separate field so that you could still add a link class

**Comment by drmenzelit** [comment]
https://github.com/joomla/joomla-cms/issues/32471

**Comment by brianteeman** [comment]
The _problem_ is that the link class adds a class to the entire link when all you want is to add a new span just for the icon. This could be achieved with an override. To change it for core it would require a lot more as you would need to keep the link class and then add another field for an icon class and its associated markup.

Another option without changing markup is you could change the css as below. Replacing Roboto with your own site font

```
.fa, .fas, [class*=" icon-"], [class^=icon-] {
    font-family: Font Awesome\ 5 Free, Roboto;
    font-weight: 900;
}
```

**Comment by chmst** [comment]
Please test #34658
