### ISSUE TITLE
[4.x] Inconsisent template preview buttons

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#34635]
### Is your feature request related to a problem? Please describe.
Inconsistent appearance and inplemateation of the template prview feature. Template and template styles have abutton for the template preview, but different.

![grafik](https://user-images.githubusercontent.com/1035262/123536902-32294e00-d72d-11eb-8577-7cfa4ee1a647.png)

![grafik](https://user-images.githubusercontent.com/1035262/123536830-d5c62e80-d72c-11eb-8986-39ee2c21b6ab.png)

### Describe the solution you'd like

Both views have plenty of place and could have a equal columns / buttons  / texts for the preview

**Comment by brianteeman** [comment]
I spotted this some time ago but was expecting a new template manager from @dgrammatiko so didnt do anything. I guess that new template manager will have to wait until a later release

**Comment by brianteeman** [comment]
@chmst not sure how you want this to be fixed.
In styles there is a column preview so the icon and the tip make sense to me
In templates there is no column so it makes sense to me to also have the word preview.

PS its not a button on my install

**Comment by dgrammatiko** [comment]
>  I guess that new template manager will have to wait until a later release

Still on my list, maybe instead of trying to fix everything in that PR I should roll only the essential parts and leave the rest for 4.1 (there's no B/C there so it can still make it in the 4.0 if I get some time to work on it)

**Comment by chmst** [comment]
closing for now, thank you!
