### ISSUE TITLE
[4.0] Multilingual home 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34641]
@chmst I assume that this should be a tip and not a title ?

![menu](https://user-images.githubusercontent.com/1296369/123622574-47bd7700-d804-11eb-80ff-83933682574b.gif)

**Comment by chmst** [comment]
Indeed - but is the message correct? Unset a language? It ist the home for this language - So maybe it should be "unset Home for this language"

**Comment by brianteeman** [comment]
Unset as German Home page ?

**Comment by chmst** [comment]
Yes :)

**Comment by brianteeman** [comment]
Needs a bit of work to adjust the messages etc will try to do it tonight
