### ISSUE TITLE
[com_finder] Regression: article title no longer searchable

### ISSUE THREAD

**Issue by janschoenherr** [joomla/joomla-cms#34647]
### Steps to reproduce the issue

Use Smart Search (com_finder) to search for any article by article title.

### Expected result

Article is found.

### Actual result

Article is not found.

### System information (as much as possible)

Joomla 3.9.27 (works correctly with 3.9.26)

### Additional comments

This commit seems to be the cause of the issue.

https://github.com/joomla/joomla-cms/commit/37e1ac34416e7a7c8f61ebfdaf9adf2d6b991452

**Comment by brianteeman** [comment]
I believe this is the issue fixed for 3.9.28 here https://github.com/joomla/joomla-cms/pull/33942

**Comment by janschoenherr** [comment]
> I believe this is the issue fixed for 3.9.28 here #33942

The issue seems to be with the changes to the indexer.php though, not the suggestions.

**Comment by Quy** [comment]
Please test #34497 to see if it fixes your issue. Thanks.

**Comment by janschoenherr** [comment]
Thanks, #34497 fixed the issue.
