### ISSUE TITLE
TinyMCE Broken features

### ISSUE THREAD

**Issue by RickR2H** [joomla/joomla-cms#34649]
Issues in Joomla 4.0 rc3-dev!

### Steps to reproduce the issue
Just did a clone from Git an noticed that some functionality from TinyMCE are broken.

1. The icon configurator is empty:
![screen shot 2021-06-29 at 16 55 49](https://issues.joomla.org/uploads/1/73c1eb912245fa4d2ff30fb09a90ff51.jpg)
When TinyMCE is saved in this state I get an error when I use the article editor: Notice: Trying to get property '2' of non-object in W:\wamp64\www\testeditor\plugins\editors\tinymce\tinymce.php on line 200

![screen shot 2021-06-29 at 17 25 02](https://issues.joomla.org/uploads/1/b75266ce41651e0657a228a0ecb8d49e.jpg)

2. Content Template Directory/functionality is not working
There is new a functionality added to the TinyMCE called Content Templates. With this functionality you can select predefined content templates from Cassiopeia html/tinymce folder. As the folder selector is there in the TinyMCE, it only shows - Default -. Also the functionality is not working as TinyMCE only shows the predefined templates from the old location.

![screen shot 2021-06-29 at 17 29 16](https://issues.joomla.org/uploads/1/4ca7ed94661bb115084c0c5b9349274a.jpg)
 

3. Custom CSS Classes not working
Selecting a custom CSS file is not working in TinyMCE. It will only load the editor.css

![custom-classes](https://user-images.githubusercontent.com/5610413/123843250-fe5b4d80-d911-11eb-8d4f-822163b8b051.jpg)

**Comment by chmst** [comment]
Did you composer install and npm ci?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34649">issues.joomla.org/tracker/joomla-cms/34649</a>.</sub>

**Comment by RickR2H** [comment]
> Did you composer install and npm ci?
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/34649](https://issues.joomla.org/tracker/joomla-cms/34649).

Yes I did! A clean install of the 4.0-dev branche.

**Comment by richard67** [comment]
> Issues in Joomla 4.0 RC3!

@RickR2H This version has not been released yet. I guess you mean rc3-dev.

**Comment by RickR2H** [comment]
> > Issues in Joomla 4.0 RC3!
> 
> @RickR2H This version has not been released yet. I guess you mean rc3-dev.

Correct. Updated my description! How can I update the milestone?

**Comment by richard67** [comment]
> > Did you composer install and npm ci?
> > This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/34649](https://issues.joomla.org/tracker/joomla-cms/34649).
> 
> Yes I did! A clean install of the 4.0-dev branche.

@RickR2H @chmst hasn’t asked if you made a clean installation, she has asked if you have run composer and npm.

**Comment by richard67** [comment]
@RickR2H Milestones are set for pull requests, not for issues.

**Comment by RickR2H** [comment]
> > > Did you composer install and npm ci?
> > > This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/34649](https://issues.joomla.org/tracker/joomla-cms/34649).
> > 
> > 
> > Yes I did! A clean install of the 4.0-dev branche.
> 
> @RickR2H @chmst hasn’t asked if you made a clean installation, she has asked if you have run composer and npm.

True, but you have to run composer and npm ci to get the installation to work.

**Comment by richard67** [comment]
> > > > Did you composer install and npm ci?
> > > > This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/34649](https://issues.joomla.org/tracker/joomla-cms/34649).
> > > 
> > > 
> > > Yes I did! A clean install of the 4.0-dev branche.
> > 
> > 
> > @RickR2H @chmst hasn’t asked if you made a clean installation, she has asked if you have run composer and npm.
> 
> True, but you have to run composer and npm ci to get the installation to work.

@RickR2H Not necessarily if the branch hasn’t been cleaned up from previous, older results of these commands after having checked out or pulled.

**Comment by RickR2H** [comment]
@richard67 It was a git pull from the J! repo. After switching the branche to 4.0-dev I dit composer install and npm ci. That's what I ment with clean. Did an other run of composer and npm just to be sure. Same result.

**Comment by brianteeman** [comment]
Confirmed

**Comment by brianteeman** [comment]
```
Uncaught TypeError: Cannot read property 'tooltip' of null
    at g (tinymce-builder.min.js?9822b7ae5b380d2f620c8f583b70a843:1)
    at Object.h.TinyMCEBuilder (tinymce-builder.min.js?9822b7ae5b380d2f620c8f583b70a843:1)
    at HTMLDocument.<anonymous> (tinymce-builder.min.js?9822b7ae5b380d2f620c8f583b70a843:1)
```

**Comment by chmst** [comment]
I have repeated clean installation on win10, xampp PHP 7.4 and php8.0 without problem.   

Until clearing browser cache ... then i could reproduce 


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34649">issues.joomla.org/tracker/joomla-cms/34649</a>.</sub>

**Comment by RickR2H** [comment]
I'll try a nightly when I back on my PC.

**Comment by richard67** [comment]
@RickR2H Better try the brand new RC 3. It has just been released.

**Comment by richard67** [comment]
@RickR2H @brianteeman What’s your npm and node versions?

**Comment by brianteeman** [comment]
C:\htdocs\joomla-cms>npm -v
7.16.0

C:\htdocs\joomla-cms>node -v
v14.15.2

**Comment by richard67** [comment]
Hmm versions should be new enough.

**Comment by richard67** [comment]
If you can't test with the brand new RC 3 in an empty folder for some reason, issue following commands in a command window on your local git clone after having checked out and pulled the 4.0-dev branch:

```
git clean -d -x -f
git checkout .
git pull origin 4.0-dev
```
(assuming the remote is named "origin").

The first command removes all files and folder not being tracked by git and not being mentioned in the .gitignore file.
The second command reverts all modifications to files tracked by git.
The third commands pulls changes from remote.

After that, do again

```
composer install
npm ci
```

And then make again a new installation.

If that or the new 4.0 TC 3 package works, then there was some compiled/compressed/gzipped js leftover from past which causes the issues.

If all that does not work then we can be more sure that we have an issue.

**Comment by richard67** [comment]
P.S.: And clear browser cache to be sure having gotten rid of old cached js.

**Comment by brianteeman** [comment]
Before I had the same screenshot as @RickR2H 

Now after git clean etc I have

![image](https://user-images.githubusercontent.com/1296369/123855115-695b5300-d917-11eb-8af8-3f01bfc3dddf.png)

**Comment by richard67** [comment]
Hmm ... less weird but still weird ... next step would be to format hard disk ...

**Comment by brianteeman** [comment]
remind me how to do that again ;)

**Comment by richard67** [comment]
I can reproduce what @brianteeman reported back on a clean, current 4.0-dev branch after composer install and npm ci, cleared browser cache and closed browser session:

![2021-03-29_1](https://user-images.githubusercontent.com/7413183/123858085-62d2d880-d923-11eb-89ce-7cc6f19b6f13.png)

![2021-03-29_2](https://user-images.githubusercontent.com/7413183/123858089-65353280-d923-11eb-814c-ad38c561ca17.png)

**Comment by richard67** [comment]
Tested with latest version of Firefox and Google Chrome, both on Windows 10.

**Comment by richard67** [comment]
The 2nd point I can't reproduce:

![2021-03-29_3](https://user-images.githubusercontent.com/7413183/123859149-97935f80-d924-11eb-8aaa-878c7be67488.png)

**Comment by RickR2H** [comment]
> I can reproduce what @brianteeman reported back on a clean, current 4.0-dev branch after composer install and npm ci, cleared browser cache and closed browser session:
> 
> ![2021-03-29_1](https://user-images.githubusercontent.com/7413183/123858085-62d2d880-d923-11eb-89ce-7cc6f19b6f13.png)
> 
> ![2021-03-29_2](https://user-images.githubusercontent.com/7413183/123858089-65353280-d923-11eb-814c-ad38c561ca17.png)

Confirmed! Same result... On Windows 10 + Chrome

**Comment by RickR2H** [comment]
> The 2nd point I can't reproduce:
> 
> ![2021-03-29_3](https://user-images.githubusercontent.com/7413183/123859149-97935f80-d924-11eb-8aaa-878c7be67488.png)

Same issue with the current 4.0-dev. Still only - Use Default - as an option

**Comment by richard67** [comment]
@RickR2H You mean you have only the "Default" in the list select and not the "cassiopeia/html/tinymce"?

**Comment by richard67** [comment]
Ah I was too fast, you wrote it already.

**Comment by RickR2H** [comment]
> @RickR2H You mean you have only the "Default" in the list select and not the "cassiopeia/html/tinymce"?

Yes, only - Use Default - as option. Not the path like in your screenshot.

**Comment by RickR2H** [comment]
@brianteeman does the path in the "Content Template Directory" work in your installation?

**Comment by Fedik** [comment]
the icons missed due to  #34472
`Joomla.sanitize()` applied to icons:

https://github.com/joomla/joomla-cms/blob/ca4670a737a5954804363aee0657593cbff6e665/build/media_source/plg_editors_tinymce/js/tinymce-builder.es6.js#L283-L285

**Comment by RickR2H** [comment]
@dgrammatiko could you take a look?

**Comment by richard67** [comment]
Ping @dgrammatiko 😄

**Comment by RickR2H** [comment]
Could this also be related to the "Content Template Directory" path?

**Comment by brianteeman** [comment]
> @brianteeman does the path in the "Content Template Directory" work in your installation?

Yes it works

Check to make sure that the folder exists

**Comment by brianteeman** [comment]
as the js issue was to fix a release blocker and it clearly created this issue then this should be a release blocker

**Comment by dgrammatiko** [comment]
> the icons missed due to #34472
> `Joomla.sanitize()` applied to icons:
> 
> https://github.com/joomla/joomla-cms/blob/ca4670a737a5954804363aee0657593cbff6e665/build/media_source/plg_editors_tinymce/js/tinymce-builder.es6.js#L283-L285

The sanitizer can have a second argument (array of objects) to extend the supported elements and the safe attributes. I’ll do a pr

EDIT: PR: #34654

**Comment by alikon** [comment]
please test #34654

**Comment by RickR2H** [comment]
@richard67 @brianteeman Update regarding the "Content Template Directory" path. I did some extensive testing and I noticed that in a live site environment I can select the path "cassiopeia/html/tinymce" on my local WAMP server I just get "- Use Default -". So the issue is related to my local env, The problem is that is is just a clean WAMP installation with no fancy tweaks. So probably more people should have the same problem. Maybe it is an issue with how the Content Tenplate path is required from the server that only works om some configurations?

Do you guys have some tips on where to look and how to investigate the issue?

**Comment by richard67** [comment]
I normally use Linux servers for testing but will later see if I can reproduce it on one of my Windows environments.

On the other hand, as far as I know @brianteeman uses Windows, so it should not be Windows specific problem.

**Comment by brianteeman** [comment]
correct - i am on windows

**Comment by RickR2H** [comment]
> I normally use Linux servers for testing but will later see if I can reproduce it on one of my Windows environments.
> 
> On the other hand, as far as I know @brianteeman uses Windows, so it should not be Windows specific problem.

Thanks Richard! I'll also do some more investigation. Let me know it it works on your env. @brianteeman which WAMP install do you use?

**Comment by brianteeman** [comment]
I use native apache and php etc

**Comment by RickR2H** [comment]
@brianteeman @richard67 Did some extensive testing and can confirm that is was pure my local installation. Thanks for your patience and feedback.

**Comment by RickR2H** [comment]
@brianteeman looks like the "Content Template Directory" path work now but setting it is has no effect in the editor, Only the default templates show up in the template selector. Also setting a custom editor CSS in TinyMCE doesn't seems to work. Could you confirm my findings? If so, I'll open a new issue. Thanks!

**Comment by brianteeman** [comment]
are you sure you didnt fall into the trap of forgetting that those settings apply only to the selected set. So if you are a super admin you would need to move to the third tab (set 0) and make the settings there

**Comment by brianteeman** [comment]
![tiny](https://user-images.githubusercontent.com/1296369/124189613-e540d100-dab8-11eb-9825-b8b77658af90.gif)

**Comment by RickR2H** [comment]
@brianteeman never noticed that all te settings apply to every set differently! Thanks for pointing me in the right direction!
