### ISSUE TITLE
[4.0] Check for override updates does not work correctly

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34643]
### Steps to reproduce the issue
Issue reproduce BEFORE installing a new nightly build.

Create any override for Atum or Cassiopeia template. Remember which override you created (for example, com_content - article).

![Screenshot_1](https://user-images.githubusercontent.com/8440661/123638009-55382880-d827-11eb-8b1a-4e96a046bacc.png)

Download the new nightly build, make any changes to the layout of what you just created the override for (for example, add the tags div, br, p, etc, or temporarily remove some line).

Install nightly build. After installation, you will immediately receive a message that "n files" have been changed. Go to System - Templates (Site) - Cassiopeia, note that the last column contains the same information - "n changes".

![Screenshot_2](https://user-images.githubusercontent.com/8440661/123638037-5f5a2700-d827-11eb-8586-776672348b42.png)

![Screenshot_3](https://user-images.githubusercontent.com/8440661/123637973-4baec080-d827-11eb-9556-1944ed3a734c.png)

Once I click on the Cassiopeia options (in this case), under the Updated Files tab, everything is fine. I can't get the list of files with changes in any way.

![Screenshot_4](https://user-images.githubusercontent.com/8440661/123637954-46517600-d827-11eb-9b8f-34fe73f197a3.png)

Everything was tested on RC2 + updates from nightly builds (a lot - updated every day).

**Comment by joeforjoomla** [comment]
Confirmed, also with 3PD templates.

**Comment by Quy** [comment]
Duplicate #33173? See PR #33256.

**Comment by Kostelano** [comment]
No, not a duplicate, another problem is being solved there.

**Comment by Kostelano** [comment]
Given the post https://github.com/joomla/joomla-cms/discussions/34944, I want to point out once again that this new feature is not working.

**Comment by brianteeman** [comment]
If confirmed then this is a release blocker as its a complete loss of functionality of a feature @richard67

**Comment by richard67** [comment]
> If confirmed then this is a release blocker as its a complete loss of functionality of a feature @richard67

Forwarding the ping to @wilsonge regarding the blocker status.

**Comment by wilsonge** [comment]
`i'll drop a release blocker tag as a safety first approach. Won't be able to look into it for another hour or two

**Comment by joomdonation** [comment]
Hopefully PR https://github.com/joomla/joomla-cms/pull/34960 address this issue properly.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34960 . Thanks in advance.
