### ISSUE TITLE
Translation strings in Crowdin

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#34642]
### Steps to reproduce the issue
For translations of Joomla 4.x we moved from crowdin.com/project/joomla-cms to joomla.crowdin.com.
There are some translation in Joomla.ini which were not visible for translaters in the old system. I don't know if it is because they were hidden or because they were not exported to Crowdin (in the old system J4 is deleted).
At this moment I do find new strings in Joomla.ini for which it shouldn't be possible to translate:
Mail_Templates:_Options, Mail_Templates, Mail_Template:_Edit, Admin_Modules:_Privacy_Status_Check, Admin_Modules:_Sample_Data and Site_Modules:_Who%27s_Online
If somebody translates this the system will not function well.

### Expected result
Not visible for translaters

### Actual result
Visible for translaters

**Comment by Kostelano** [comment]
These lines do not need to be translated

**Comment by MartijnMaandag** [comment]
I know, so don't show them to translaters who maybe don't know and who can kill the system.

**Comment by infograf768** [comment]
> These lines do not need to be translated

Simple curiosity : where are these weird mixed cases « phrases » used?

**Comment by infograf768** [comment]
Ah, all those are in fact JHELP_COMPONENTS_etc

**Comment by Bakual** [comment]
I have manually hidden those (along with others) in the old Crowdin instance.
Please take such issues to the ones responsible for the new Crowdin instance. It's not something which can be fixed here.

**Comment by Bakual** [comment]
For reference: https://github.com/joomla/joomla-cms/issues/30803

**Comment by MartijnMaandag** [comment]
They are hidden now.
Maybe inform the people who do the new Crowdin? Is there a document they can use with what to do and what not?

**Comment by Bakual** [comment]
That's something which should be handled within the Joomla Translation Program Team (https://volunteers.joomla.org/teams/joomla-translation-program-team) where you are part of.
I believe Wilco is the lead person for Crowdin related things.
