### ISSUE TITLE
[4.0] RC3 Param:  image_intro_alt_empty  has no defaut value

### ISSUE THREAD

**Issue by angieradtke** [joomla/joomla-cms#34657]
com_content article.xml
 I just noticed that the parameter 'image_intro_alt_empty"  has no default value, which leads to a the Notice: Undefined property

Angie

**Comment by brianteeman** [comment]
The documentation says it does not require a default value
https://docs.joomla.org/Checkbox_form_field_type

**Comment by angieradtke** [comment]
Is also not really bad, I just noticed. Thought only that it is  an unnecessary Notice.

**Comment by brianteeman** [comment]
Where did you see the notice?

**Comment by angieradtke** [comment]
Set: Error Reporting to Maximum

1. Make a new Artikel , 
2. Select a Intro-Image 
3. **Don't touch the other params**
4. add some contents 
5. save

**Comment by brianteeman** [comment]
I cannot replicate this - maybe someone else can

Please provide your full system info

**Comment by angieradtke** [comment]
Probably it is also just a matter of taste

.../ intro_image.php  
Here is it caught  with: empty($images->image_intro_alt_empty)

**Comment by brianteeman** [comment]
@chmst please can you try to replicate this

**Comment by brianteeman** [comment]
@chmst any idea - if not then this should be closed

**Comment by brianteeman** [comment]
This should be closed
