### ISSUE TITLE
Text Filter set to No Filtering but code is removed on save

### ISSUE THREAD

**Issue by theigloo** [joomla/joomla-cms#34650]
I set the Text Filters for all user types to No Filtering then I ad a youtube iframe in an article and click save, then the iframe is gone.

### Expected result 
iframe should be in the article

### Actual result 
iframe code dissapears

### System information 
Joomla RC3 on MAMP Mac

**Comment by richard67** [comment]
@theigloo You have to go to the options of the TinyMCE editor plugin, go to the set which you are using and search for the option "Prohibited Elements". There you find a list of elements among which is "iframe". Remove it from the list, save the options, try again and then report back if it works for you. Thanks in advance.

**Comment by theigloo** [comment]
Thanks, @richard67 
I followed your instructions and its working now :)
Not a bug

**Comment by richard67** [comment]
@theigloo No problem. Thanks for reporting back.

**Comment by brianteeman** [comment]
> @theigloo You have to go to the options of the TinyMCE editor plugin, go to the set which you are using and search for the option "Prohibited Elements". There you find a list of elements among which is "iframe". Remove it from the list, save the options, try again and then report back if it works for you. Thanks in advance.

OR even simpler in tinymce set it to use the Joola Text filter
![image](https://user-images.githubusercontent.com/1296369/123855874-4d0be600-d918-11eb-9cc8-17de2d9df608.png)

**Comment by theigloo** [comment]
@brianteeman ah yes, thanks for the tip :)
