### ISSUE TITLE
[4.0] Finder Indexer does not work when debug is enabled

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#34665]
### Steps to reproduce the issue
1. Go to the Joomla Configuration > System and enable the "System Debug".
2. Go to components Smart Search and click the "Clear Index" button.
3.  Go to components Smart Search and click the "Index" button.

### Expected result
Indexer to work

### Actual result
Does not work

### System information (as much as possible)
Checked both in J4 RC4 and a github clone

### Additional comments
Seems to related with the js file: [media/com_finder/js/indexer.js](https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/com_finder/js/indexer.es6.js#L80)

**Comment by brianteeman** [comment]
Confirmed

**Comment by wilsonge** [comment]
Closing as we have a PR https://github.com/joomla/joomla-cms/pull/34795

**Comment by richard67** [comment]
Please test #34795 . Thanks in advance.
