### ISSUE TITLE
[3.x] - Toggle requireReset forces change but doesn't update lastResetTime or resetCount

### ISSUE THREAD

**Issue by tonypartridge** [joomla/joomla-cms#34666]
### Steps to reproduce the issue
Toggle a user to require password reset

### Expected result

once logged in and updated password the following should happen

requireReset = 0
resetCount increases +1
lastResetTime  = date/time of reset

### Actual result

requireReset = 0
resetCount = unchanged
lastResetTime = unchanged

#####

I am unsure if these columns are marked for removal since I don't really see them used. But if not I am happy to make the required changes to support them again.

**Comment by brianteeman** [comment]
If my memory is correct those fields are used for user initiated resets. They are used by the Maximum reset count etc option in com_users<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34666">issues.joomla.org/tracker/joomla-cms/34666</a>.</sub>

**Comment by tonypartridge** [comment]
Thanks Brian!
