### ISSUE TITLE
[40] Wrong error message in language DE while copying template

### ISSUE THREAD

**Issue by gorgonz** [joomla/joomla-cms#34673]
### Steps to reproduce the issue
goto backend (using language DE)
click system => site templates => cassiopeia
click button "copy template" and select a name including character "-"
The description text is "Den Namen des neuen Templates eingeben. Es dürfen nur Buchstaben, Zahlen und Unterstriche benutzt werden."

### Expected result
an error message like "Fehlerhafter Template-Name! Es dürfen nur Buchstaben, Zahlen und Unterstriche benutzt werden. "

### Actual result
error message is "Fehlerhafter Template-Name! Es sind nur Buchstaben, Zahlen, Binde- und Unterstriche erlaubt."

### System information (as much as possible)
Didn't know howto tell, that we talk about J4 RC3

### Additional comments
Maybe also use same syntax as in description text, which is correct

**Comment by brianteeman** [comment]
@tecpromotion

**Comment by bembelimen** [comment]
You can report it here: https://github.com/joomlagerman/joomla/tree/4.0-dev
