### ISSUE TITLE
[4.0] fake html mail templates

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34676]
The new mail templates feature has the option to send mails in html format. When enabled you have a full tinymce editor so it is expected that the features of the editor will work in the produced email.

However they dont as
1. any images included are sent with relative paths. They should be absolute paths
2.  css styles are not embedded in the mail

Probable solution would be to load a differently configured version of tinymce in the mail templates editor

**Comment by dgrammatiko** [comment]
> Probable solution would be to load a differently configured version of tinymce in the mail templates editor

Or just fix these issues on the `beforeSave` event (either with a plugin or directly in the model). Goes without saying that there should be also an onBeforeFormData (or whatever is the event for loading the form data) that will reverse the saved data in the db so tinyMCE (or any editor) will display what the user typed/inserted.

**Comment by brianteeman** [comment]
if i remember correctly tinymce can be configured to work correctly for emails just not with the same settings as you would use for a content item

**Comment by dgrammatiko** [comment]
> if i remember correctly tinymce can be configured to work correctly for emails just not with the same settings as you would use for a content item

But you still have to embed the css instead of linking it, will it cover also this?

https://codepen.io/tinymce/pen/vYLqwKO

https://www.tiny.cloud/blog/email-marketing-software/

PS. this reminds me that tinyMCE still doesn't have a way to customize the 
```js
  // styles property makes that easy.
  // https://www.tiny.cloud/docs/configure/content-formatting/#formats
  formats: {
    h1: { block: "h1", styles: { fontSize: "32px" } },
    h2: { block: "h2", styles: { fontSize: "18px" } },
    cta: {
      selector: "a",
      styles: {
        backgroundColor: "#706FD3",
        padding: "12px 16px",
        color: "#ffffff",
        borderRadius: "4px",
        textDecoration: "none",
        display: "inline-block"
      }
    }
  },

  // The style_formats option controls the styleformat toolbar button menu
  // https://www.tiny.cloud/docs/configure/editor-appearance/#style_formats
  style_formats: [
    { title: "Paragraph", format: "p" },
    { title: "Heading 1", format: "h1" },
    { title: "Heading 2", format: "h2" },
    { title: "Button styles" },
    { title: "Call-to-action", format: "cta" }
  ]
```
I should reopen that PR https://github.com/joomla/joomla-cms/pull/14456

**Comment by Quy** [comment]
> any images included are sent with relative paths. They should be absolute paths

PR #36088
