### ISSUE TITLE
[4.0] Label has fixed width also when used as sticked

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#34679]
### Steps to reproduce the issue
Build a blog layout with a language with longer words than English (here it is German) 
The screen uses the sticky layout for fields 

### Expected result
Labels are displayed in the same width as the input field below

### Actual result
Label has fixed width 240px.

![grafik](https://user-images.githubusercontent.com/1035262/124113150-65404a00-da6b-11eb-8a66-9afb2a48b52e.png)

### Additional comments

**Comment by simbus82** [comment]
I see that all elements in this "tab" are not styled like elements in others tabs in the menu voice edit page. 

WRONG (Blog Layout Tab)
![image](https://user-images.githubusercontent.com/1375730/137283876-81f45e50-890d-4a09-afdb-909775b7e9c3.png)

RIGHT (es. Category Tab)
![image](https://user-images.githubusercontent.com/1375730/137284044-22ad564d-38ad-4782-a419-8c09c88cf855.png)

Probably something in this "view" was not changed when the admin template was rewritten.
So i confirm the problem.

**Comment by RickR2H** [comment]
Closing as having a pull request, Please test #35823<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34679">issues.joomla.org/tracker/joomla-cms/34679</a>.</sub>
