### ISSUE TITLE
[4.0] Translations home

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34686]
Where will joomla 4 translations live on j.org ?

We have a link on the help page that goes to https://community.joomla.org/translations.html

Is that still valid?

**Comment by Bakual** [comment]
My guess would be to change this to https://downloads.joomla.org/language-packs. I don't think the old page will be expanded for J4 and the download page seems to have the same information on it.

**Comment by brianteeman** [comment]
Thanks - PR created
