### ISSUE TITLE
[4.0] No toolbar controls under lg breakpoint

### ISSUE THREAD

**Issue by barsdeveloper** [joomla/joomla-cms#34695]
### Steps to reproduce the issue
Go to Content > Articles > [+] to create a new article.
Shrink the window to go under lg breakpoint.
You are under lg when the controls on the right disappear (the ones in the image).
(BTW maybe lg is too narrow (there is XL and XXL) or just 3 columns are not enough, as you can see they overflow on the right)
![Cattura](https://user-images.githubusercontent.com/84736467/124355932-f2260780-dc13-11eb-8a48-b8d56f1b6f0b.PNG)
Now everithing looks fine.
Refresh the page.
The toolbar controls (Save, Save&Close, Cancel, Help) are gone.
![Cattura2](https://user-images.githubusercontent.com/84736467/124356035-5943bc00-dc14-11eb-8e54-0abb172c9588.PNG)
I think that is caused by some JS because you can see them for a couple of moments, then they disappear.
If you resize the window they appear again, but I immagine on devices such as tablets, they are never shown and there is no way to save an article.

### Additional comments
Anyway why is JS needed to manage the appearence or disappearance of the controls? Css with meadia queries should be sufficient and you would avoid the blinking effect of elements appearing/disappearing.

**Comment by brianteeman** [comment]
![media](https://user-images.githubusercontent.com/1296369/124362840-6fab4100-dc2f-11eb-8461-36002ecd17da.gif)

**Comment by barsdeveloper** [comment]
@brianteeman You missed the "Refresh the page" point.
And stop before the gears appear.

**Comment by brianteeman** [comment]
Got it now and confirmed

**Comment by barsdeveloper** [comment]
Thanks for taking time to check

**Comment by angieradtke** [comment]
I think the issue is  in the autum template.js file  where the media-queries  and the collapse function are located.

media/templates/administrator/atum/js/template.js 
This will help

document.addEventListener("DOMContentLoaded", function() {

  if (mobile.matches) {
    setMobile();
  } else {
    setDesktop();
  }
});

**Comment by barsdeveloper** [comment]
May I suggest to add release blocker to this issue? Joomla 4 stable is out and it is **not usable** in the MD breakpoint (which is many tables or side by side window on desktop) because toolbar is missing some fundamental parts. It is kinda big deal, isn't it?

**Comment by Chaosxmk** [comment]
Instead of doing
```
if (mobile.matches) {
  changeLogo('closed');

  if (subhead) {
    subhead.classList.remove('show');
    subhead.classList.add('collapse');
  }
}
```
Wouldn't it be better to just immediately run setMobile()?
```
if (mobile.matches) {
  setMobile();
}
```

**Comment by brianteeman** [comment]
I can not replicate this anymore

**Comment by Hackwar** [comment]
@barsdeveloper can you check if this is still an issue for you and otherwise close it?

**Comment by fgsw** [comment]
Can't confirm the issue on J5.2.2.

**Comment by barsdeveloper** [comment]
Sorry, I'm not doing web development anymore these days. I think we can close it assuming it was fixed at some point 😁
