### ISSUE TITLE
[4.0] [Language Overrides] Main panel logic

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34698]
### Steps to reproduce the issue
Go to System - Language Overrides. Please note that the NEW and CLEAR CACHE buttons are available in the toolbar. Click on NEW.

We receive a message that we need to select a location for which a new override will be created.

In addition, values ​​are available on the right to sort the values. However, again, this is only available AFTER selecting a site area. Why are they open then?

![Screenshot_1](https://user-images.githubusercontent.com/8440661/124356605-82b61500-dc1f-11eb-9027-9302167099d8.png)

I think it would be better if we could select an area of ​​the site AFTER clicking the NEW button. Right there in the main panel, we could display all the overrides, but add a column something like "Site area" (site / control panel). Like that.

This is not a bug, but a request for a future change.

**Comment by Quy** [comment]
Related #28855
