### ISSUE TITLE
[4.0] Export function of preset menu does not work

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34700]
### Steps to reproduce the issue
Go to MENU - MANAGER, select ADMINISTRATOR in the filter, create a menu. Create any menu item inside, any.

Then again go to MENU - MANAGER, select the ADMINISTRATOR in the filter, select the created menu and click on the Download as Preset button. We will receive an error:

> Warning
> To use export, please first select a valid Menu in the manager.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/124359390-5f926200-dc2d-11eb-869f-f5b873aa94fc.png)

What's wrong?

**Comment by brianteeman** [comment]
Confirmed - might help someone find the problem but if the menu has no menu items it can be exported and shows the problem ?

```
<code>403</code>
<message>You don't have permission to access this. Please contact a website administrator if this is incorrect.</message>
<trace>#0 C:\htdocs\joomla-cms\libraries\src\MVC\Controller\BaseController.php(730): Joomla\Component\Login\Administrator\Controller\DisplayController->display() #1 C:\htdocs\joomla-cms\libraries\src\Dispatcher\ComponentDispatcher.php(146): Joomla\CMS\MVC\Controller\BaseController->execute('') #2 C:\htdocs\joomla-cms\administrator\components\com_login\src\Dispatcher\Dispatcher.php(43): Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() #3 C:\htdocs\joomla-cms\libraries\src\Component\ComponentHelper.php(389): Joomla\Component\Login\Administrator\Dispatcher\Dispatcher->dispatch() #4 C:\htdocs\joomla-cms\libraries\src\Application\AdministratorApplication.php(143): Joomla\CMS\Component\ComponentHelper::renderComponent('com_login') #5 C:\htdocs\joomla-cms\libraries\src\Application\AdministratorApplication.php(186): Joomla\CMS\Application\AdministratorApplication->dispatch() #6 C:\htdocs\joomla-cms\libraries\src\Application\CMSApplication.php(278): Joomla\CMS\Application\AdministratorApplication->doExecute() #7 C:\htdocs\joomla-cms\administrator\includes\app.php(63): Joomla\CMS\Application\CMSApplication->execute() #8 C:\htdocs\joomla-cms\administrator\index.php(32): require_once('C:\\htdocs\\jooml...') #9 {main}</trace>
</error>
```

**Comment by chmst** [comment]
Same in J3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34700">issues.joomla.org/tracker/joomla-cms/34700</a>.</sub>

**Comment by Fedik** [comment]
please test #34746 for Joomla 4

for Joomla 3 I can backport, later
