### ISSUE TITLE
[4.0] Pages without item hints

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34707]
### Steps to reproduce the issue
Not so long ago, tooltips for items were added in places (in the archive, in the trash, published, not published).

![Screenshot_1](https://user-images.githubusercontent.com/8440661/124383470-4cd36800-dcd5-11eb-9c93-d616815d3cac.png)

There are several pages left where these tips are not present when the mouse cursor is hovered over.

**Banners: Clients**
![Screenshot_2](https://user-images.githubusercontent.com/8440661/124383498-6f658100-dcd5-11eb-8699-49d2f9461154.png)

**Smart Search: Content Maps**
![Screenshot_3](https://user-images.githubusercontent.com/8440661/124383482-5eb50b00-dcd5-11eb-841e-6c0072c68edf.png)

**Comment by brianteeman** [comment]
Please check - I m pretty sure there are either pull requests or open issues

**Comment by Quy** [comment]
Fixed for Banner Clients per #36262

**Comment by brianteeman** [comment]
Final part #36801
