### ISSUE TITLE
Remove php warning  from \administrator\components\com_joomlaupdate\models\default.php 

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#34710]
### Steps to reproduce the issue
call to jooma 3.10 alpha 8 pre-checker may throw warning:
Warning: Creating default object from empty value in C:\myjoomla3\administrator\components\com_joomlaupdate\models\default.php on line 1470

to fix this e.g. add check for object property at line 1470:
```
if (isset($decode->description))
	   $decode->description = '';
```

**Comment by ReLater** [comment]
For me the message looks like that the object `$decode` isn't created correctly, not only this and all other properties. Or do I miss something?

Can you check in your database table if all extensions with package_id=0 have something in field manifest_cache?

Can you add a debug code in line 
https://github.com/joomla/joomla-cms/blob/3.10-dev/administrator/components/com_joomlaupdate/models/default.php#L1468

```
if (!is_object($decode))
{
 echo $extension->name . '|' . $extension->extension_id;
exit;
}
```

**Comment by jschmi102** [comment]
hi,
had to remove  $extension->id from debug code but  got "de-DEJEvents|"  for  $extension->name
```
Notice: Undefined property: stdClass::$id in C:\myjoomla3\administrator\components\com_joomlaupdate\models\default.php on line 1472
de-DEJEvents|
```
Founds 1 entry in database showing (surprise!) "de-DEJEvents|" (element "pkg_de-DEJEvents")

**Comment by jschmi102** [comment]
hi,
deleted this (orphan) entry from database - this fixed the php-warning (same as my fix-code did)

**Comment by ReLater** [comment]
I would say: Not a core issue when an 3rd extension has no <strike>ID and</strike> manifest_cache in db table.
EDIT: Nonsense. My debug code was wrong. Not $extension->id but $extension->extension_id is correct.

Maybe one could think about a Joomla warning if orphaned extensions are found in pre-checker but how friendly must Joomla be there.

To close or not to close?

**Comment by ReLater** [comment]
I corrected my code in https://github.com/joomla/joomla-cms/issues/34710#issuecomment-874148275

**Comment by jschmi102** [comment]
hi,
the question is  should bad input (here caused by orphan extension)  be handled by code (e.g. throw error message) or may one live with a php-warning (which can be understod and solved) - both OK for me - so I close this issue.

**Comment by ReLater** [comment]
That has to decide somebody else. TBH I don't know what happens after this line
https://github.com/joomla/joomla-cms/blob/3.10-dev/administrator/components/com_joomlaupdate/models/default.php#L1477
where a NULL is passed over as $extension->manifest_cache.

Maybe @zero-24 knows that?

**Comment by zero-24** [comment]
Hi @ReLater @jschmi102 this issue should have been patched now by https://github.com/joomla/joomla-cms/pull/34774 please check and than close here Thanks.

**Comment by wilsonge** [comment]
Haven't heard anything in regards to this. Closing this - if it's still in the next RC due on Tuesday (27 August) then we can reopen
