### ISSUE TITLE
[4.0] pre-checker inconsistency

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#34716]
Have installed and tested an extension (package) on joomla4. Extension contains  two plugins which both run successfully with Joomla3 and joomla4.  Pre-checker on 3.10.0 alpha8 informs (correctly) that installed version is compatible with both joomla versions ("green state"). But whith Joomla 4 RC3 pre-checker tells that though installed package is compatible and does not need update there would be a "Package Potentially Serious Problem".  It seems that though developer has stated a compatible version via his update-server's plugin xml , pre-checker for joomla4 warns to run with this type of plugin (system).

**Comment by ChristineWk** [comment]
@zero-24 #34599<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34716">issues.joomla.org/tracker/joomla-cms/34716</a>.</sub>

**Comment by zero-24** [comment]
@jschmi102 please provide your update xml

And please provide the following:
- Joomla Version in which you run the pre upgrade checker
- Joomla Update Server Configuration

Thanks

**Comment by jschmi102** [comment]
Hi,

Isssue https://github.com/joomla/joomla-cms/issues/34599 describes and discusses most of the problems of this issue. 

Joomla V3.10 and Joomla V4 have implemented a checking mechanism to provide a consistent compatibility information for joomla extensions e.g. to be used for a migration to Joomla V4. This information is based on the setting of an update server (stored in xml format). This setting will have to be done by the developer of extensions. This also means that the developer must provide a valid compatibility information, so that a user can rely on this info and process his/her migration effort successfully. E,g. Developer should not “lie” or mistakenly define a compatibility where is none (I saw a couple of extensions where the developer defined a genereic version for updates `version=".*" ` - which results in a compatibility for **any** joomla version, which is certainly  wrong).
On the other hand, Joomla should provide a consistent compatibility information – this means Info from joomla 3.10 should be similar to Joomla 4.x Unfortunately this is not the case with Joomla 4.0 RC3 and Joomla 3.10. alapha 8. Whereas Joomla 3.10 reports “No Update Required” (which is correct) does Joomla 4.0RC3 also tell “No Update Required”  but warns the user additionally better not to install the extension, though the developer has defined a complete compatibility for Joomla4.    
I'm using an update server for my extension to support updates on Joomla V3.9, V3.10 and V4.0.
(click http://www.jschmidt-systemberatung.de/downloads/jmootips12_updates.xml  to see contents):
	
```
<updateservers>
 <server type="extension" priority="1" name="jmootips1.2 Updates">http://www.jschmidt-systemberatung.de/downloads/jmootips12_updates.xml
 </server>
</updateservers>  
```

It seems that only for system type plugins warn ing message “Package Potentially Serious Problem.” will be issued on Joomla 4 RC3.

**Comment by brianteeman** [comment]
> It seems that only for system type plugins warn ing message “Package Potentially Serious Problem.” will be issued on Joomla 4 RC3.

Yes thats correct as they could result in the site being down

**Comment by jschmi102** [comment]
> Yes thats correct as they could result in the site being down

Any other type of plugins could cause a system crash (e.g. a content plugin) - so for me this argument is not understandable

**Comment by brianteeman** [comment]
No thats not correct

**Comment by jschmi102** [comment]
E.g. a content plugin will be trigered by onContentPrepare event - this means practically on each page. If there is a serious bug it will crash the system.

**Comment by brianteeman** [comment]
it will crash the site but you can still access it in order to disable the plugin. with an errant system plugin it will kill the site and you will need to have database access to repair it

**Comment by farimas** [comment]
it will crash the site but you can still access it in order to disable the plugin. with an errant system plugin it will kill the site and you will need to have database access to repair it<a href="https://bestlivenewsonline.blogspot.com/">https://github.com/joomla/joomla-cms/blob/3.9.28/administrator/components/com_search/helpers/search.php#L285</a><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34716">issues.joomla.org/tracker/joomla-cms/34716</a>.</sub>

**Comment by zero-24** [comment]
The issue has been explained here and the string has been updated here: https://github.com/joomla/joomla-cms/pull/34771
