### ISSUE TITLE
[4.0 rc2 -> rc4] Warning if allow_url_fopen = 0

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#34729]
### Steps to reproduce the issue
Update a J4 - in this case from RC2 to RC4 on a webspace where allow_url_fopen = 0 

If allow_url_fopen = 0  the update starts with a warning:

### Expected result
If this is an error, then the pre_check should show it, otherwise no warning

### Actual result

Warning: get_headers(): https:// wrapper is disabled in the server configuration by allow_url_fopen=0 in 
administrator/components/com_joomlaupdate/Model/UpdateModel.php on line 300

### System information (as much as possible)
After setting allo_url_fopen to 1: 

![grafik](https://user-images.githubusercontent.com/1035262/124789564-b1e3c380-df4a-11eb-8f03-57ac073db007.png)

**Comment by brianteeman** [comment]
You should have received a nice warning
JLIB_UPDATER_ERROR_COLLECTION_FOPEN="The PHP allow_url_fopen setting is disabled. This setting must be enabled for the updater to work."

**Comment by wilsonge** [comment]
You should. However that string is unused by core :D

**Comment by chmst** [comment]
With the newest code from github I cannot reproduce the issue. So closing this now.
