### ISSUE TITLE
Anonymize client IP addresses in Joomla log files optionally

### ISSUE THREAD

**Issue by gersteba** [joomla/joomla-cms#34735]
### Steps to reproduce the issue
Joomla creates log entries i. e. in error.php, joomla_update.php.

### Expected result
An option "mask ip addresses" for each Joomla log file.
i. e. instead of
104.96.128.125
... this entry
104.96.128.1**

### Actual result
No options available, yet.
The full IP addresses are being stored.

### System information (as much as possible)
---

### Additional comments
See also discussion ['Anonymize client IP addresses in Joomla log files - how?'](https://forum.joomla.org/viewtopic.php?f=708&t=987177).

**Comment by brianteeman** [comment]
I agree with everything @pe7er said in the forum discussion

**Comment by wilsonge** [comment]
Yes agree with @pe7er 's comments too. Closing this as a won't fix.
