### ISSUE TITLE
"Hide all messages" not getting translated to back-end Administrator language in the screen "Post-installation Messages for Joomla CMS"

### ISSUE THREAD

**Issue by imanickam** [joomla/joomla-cms#34730]
### Steps to reproduce the issue

1. Log into site's back-end with a login that has Super User privileges
2. Go to the screen "System Dashboard"
3. Install French language
4. Go back to the screen "System Dashboard"
5. Go to the screen "Languages: Installed (Administrator)" (Manage => Languages -> Administrator)
6. Make French as the Default Administrator language (by clicking on the Grey "Set Default" icon)
7. Go back to the screen "System Dashboard" ("Système : Tableau de bord" in French)
8. Click on the link "Messages d'installation" (Information => Messages d'installation) - (ie "Installation Messages" in English)
9. in the resultant screen "Messages de post-installation pour Joomla CMS" ("Post-installation Messages for Joomla CMS" in English) look for the button with the text "Cacher tous les messages" ("Hide all messages" in English).

Your will not find the button with the text "Cacher tous les messages".  Where as you would notice the button with the text "Hide all messages".

### Expected result

The button text must be in French.

![Hide_all_messages_language_string_display_expected_for_other_languages](https://user-images.githubusercontent.com/4947580/124879189-98925400-dfea-11eb-9008-3979d70c43f7.jpg)

### Actual result

The button text is in English instead of in French.

![Hide_all_messages_language_string_display_error_for_other_languages](https://user-images.githubusercontent.com/4947580/124879072-76003b00-dfea-11eb-8baa-3f03076146c2.jpg)

### System information (as much as possible)

Joomla Versions tested: 4 RC3 as well as v4 RC4 (nightly build on July 7, 2021)
Operating System: WIndows 10
PHP version: 7.4.20
MySQL version: 5.7.34
Web Server: Apache 2.4.46

### Additional comments

- This happens for all languages - tested with French and Tamil languages
- If a language override is created for the language string, for the Administrator-language combination, that has the constant COM_POSTINSTALL_HIDE_ALL_MESSAGES, the appropriate language value is shown.  That is how I created the Expected Result image attached.

**Comment by brianteeman** [comment]
That is the expected behaviour if there is no translation available or have I missed something

**Comment by imanickam** [comment]
Opps. Sorry.  It looks like the images are in the reverse order.  Expected in Actual and Actual in Expected.  I will correct the images order.

**Comment by imanickam** [comment]
Please be informed that the translations are correct and the translated language strings do appear in the respective language files.

Following are the language strings from the language files:

C:\wamp64\www\Joomla_4rc3\administrator\language\en-GB\com_postinstall.ini (1 hit)
	Line 12: COM_POSTINSTALL_HIDE_ALL_MESSAGES="Hide all messages"
C:\wamp64\www\Joomla_4rc3\administrator\language\fr-FR\com_postinstall.ini (1 hit)
	Line 12: COM_POSTINSTALL_HIDE_ALL_MESSAGES="Cacher tous les messages"
C:\wamp64\www\Joomla_4rc3\administrator\language\ta-IN\com_postinstall.ini (1 hit)
	Line 12: COM_POSTINSTALL_HIDE_ALL_MESSAGES="அனைத்து செய்திகளையும் மறைக்க"

**Comment by brianteeman** [comment]
I have a fix - coming shortly

**Comment by Quy** [comment]
Please test #34737. Thanks.
