### ISSUE TITLE
Bug 3.9.28

### ISSUE THREAD

**Issue by ghost-pc-83** [joomla/joomla-cms#34731]
Bonjour,

sorry for my English :)

For information, following the update to 3.9.28, by connecting to the admin if you use wrong credentials you will be returned: Call to undefined function mb_strimwidth () then return to the control panel ...
Situation verified on around 10 sites and not present on 3.9.27
Have a good day.
Ghost

**Comment by ghost-pc-83** [comment]
Problem solved .... another cache issue in Firefox which since its last update is playing with my nerves
Thank you for your attention.
Cdt.

GHost<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34731">issues.joomla.org/tracker/joomla-cms/34731</a>.</sub>

**Comment by chmst** [comment]
Thank you for reporting! I will close this issue.
