### ISSUE TITLE
[4.0] Nested Categories do not work properly

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#34744]
### Steps to reproduce the issue
1. Create several content categories and children categories
2. Create a menu item to link to **List All Categories in an Article Category Tree** menu item type of com_content
3. Make sure **Empty Categories** parameter in the menu item set to Show
4. Access to that menu item from frontend

### Expected result
1. Click on + icon should show children categories
2. Click on - icon should hide children categories

![Content-Categories](https://user-images.githubusercontent.com/977664/125106066-67f50c00-e109-11eb-9b59-fdc6cb3bc644.png)

### Actual result
Children categories are not being shown/hide when click on these icons

### System information (as much as possible)
Joomla 4 nightly build

### Additional comments
This happens on all components (content, contact....). Do we need to load the below command in the layout?

```php
HTMLHelper::_('bootstrap.collapse');

**Comment by richard67** [comment]
@joomdonation Could you check if #33052 solves this issue? Thanks in advance.

**Comment by joomdonation** [comment]
Closing this issue because it is solved by PR https://github.com/joomla/joomla-cms/pull/33052
