### ISSUE TITLE
[4.0] [Contacts] The copy sending line is separate from the checkbox

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34757]
### Steps to reproduce the issue
Create a contact page with a feedback form. Please note that the line for sending a copy is placed separately from the checkbox, unlike, for example, the confidentiality clause below.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/125192621-7e0de400-e251-11eb-8559-de9a4c685573.png)

**Comment by ChristineWk** [comment]
I never use this function because it can be used to spam.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34757">issues.joomla.org/tracker/joomla-cms/34757</a>.</sub>

**Comment by drmenzelit** [comment]
I'm looking at this

**Comment by Kostelano** [comment]
PR https://github.com/joomla/joomla-cms/pull/39252
