### ISSUE TITLE
[4.0] [Mail Templates] Tag is inserted only at the end of the message

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34758]
### Steps to reproduce the issue
Go to **SYSTEM - Mail Templates**, open any template. Place your mouse cursor somewhere in the middle of the message text and try to insert a tag - it is inserted only at the end of the message.

This only happens with the message body WITHOUT HTML. In the field of HTML - everything is good.

**Comment by JamesNGarrett** [comment]
https://github.com/joomla/joomla-cms/blob/4.0.0-rc3/build/media_source/com_mails/js/admin-email-template-edit.es6.js

Line 58 suggests that if the editor isn't loaded then insertTag just appends the tag to the value.

```
 if (Joomla.editors.instances[input.id]) {
        Joomla.editors.instances[input.id].replaceSelection(tag);
      } else {
        input.value += ` ${tag}`;
      }
```

**Comment by brianteeman** [comment]
Confirmed

**Comment by Hackwar** [comment]
In the meantime the field is not using textarea anymore, but editor with the type forced to none, which makes this work fine. Closing this issue as solved.
