### ISSUE TITLE
[4.0] Removing non Joomla links from language files

### ISSUE THREAD

**Issue by horus68** [joomla/joomla-cms#34755]
### Is your feature request related to a problem? Please describe.
Language files includes links to non joomla sites as in "more informations on specific subject". 
If/When those links changes there is a need to fix the master language and all translations.

### Describe the solution you'd like
1- Any informative non joomla link will be removed from language files. 
This will not cover the mandatory GPL license https://www.gnu.org/licenses/gpl-2.0.html
2- Language files would only show a link to a Joomla docs page presenting that specific subject. 
3- There the external link for more information will be placed as contents (it could be just with a single external link or getting more text if required later)
4- Any future change will be done in a single place (the Joomla docs) and the language files will have no need to be changed.

### Additional context
A list of external links for "More information" i found inside language files:

```

https://github.com/WICG/floc
https://www.eff.org/deeplinks/2021/03/googles-floc-terrible-idea

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referrer-Policy
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/script-src
https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP

https://en.wikipedia.org/wiki/Cross-site_scripting
https://en.wikipedia.org/wiki/Clickjacking
https://en.wikipedia.org/wiki/Google_Authenticator
https://en.wikipedia.org/wiki/Google_Authenticator#Implementation

https://support.google.com/accounts/answer/1066447

```

This ones could be just links to services, need to be checked
```
https://freeotp.github.io
https://hstspreload.org
http://skin.tiny.cloud
https://www.google.com/recaptcha
```

**Comment by brianteeman** [comment]
For many of those links the reason they are in the language file is so that the TT can update the links to the correct link for their language.

For example `https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP` would be translated to `https://developer.mozilla.org/fr/docs/Web/HTTP/CSP`

**Comment by zero-24** [comment]
Hmm I'm not sure whether it would make sense to maintain our own CSP / HTTP Headers docs or copies of other well trused and up-to-date docs and copy them to docs.joomla.org specificly that they are about very general non-joomla specific topics, i personally would say that the docs.joomla.org should focus on joomla specific docs.
Given that the links are within the language string the TT in question is free to point the link to better informations or translations like brian mentiond too.
And I dont have the fear that with that very limited set of links as presented here we will have major issues with changing URLs.

**Comment by brianteeman** [comment]
All this will really do is to move the task from the translation team to the documentation team for no benefit

**Comment by horus68** [comment]
I'm not suggesting to have a copy of those content pages inside Joomla docs. 
Joomla docs will be linked from the language file but only need to have the external link, so the language files will never require to be updated just for an external link change.

**Comment by brianteeman** [comment]
Seems pointless to me but someone should make a decision and either apply this change request or close it

cc @bembelimen @roland-d

**Comment by bembelimen** [comment]
I see the point in theory that it could give a very small benefit for translators, but TBH it would lead to a very big overhead and work for other teams and maintainers. So for me it's a clear "NO" to change it.
