### ISSUE TITLE
Bootstrap Carousel Control is broken

### ISSUE THREAD

**Issue by Manuel-Franz** [joomla/joomla-cms#34766]
### Steps to reproduce the issue
Copy the Carousel from the cheatsheet on this site:"https://getbootstrap.com/docs/5.0/examples/cheatsheet/"

### Expected result
The Controls on the left and right side should appear

### Actual result
They don't appear and the line <span class="carousel-control-prev-icon" aria-hidden="true"></span> and <span class="carousel-control-next-icon" aria-hidden="true"></span> get removed.

### System information (as much as possible)
Joomla 4.0.0.rc3
Default editor of joomla 4

### Additional comments
I assume that this might be caused by the svg graphics of the Controls.

**Comment by brianteeman** [comment]
Please see https://docs.joomla.org/J4.x:Using_Bootstrap_Components_in_Joomla_4

**Comment by Manuel-Franz** [comment]
Hello. Thank you for that interesting link. I did not knew that this article exists.
I also failed to send the part of the code which gets deleted since it got removed from my post. The problem is the icon to the left and right.

This is the code for the icons which make the problem:
`<span class="carousel-control-prev-icon" aria-hidden="true"></span>` and `<span class="carousel-control-next-icon" aria-hidden="true"></span>`

These classes link to the following svg file for the left icon:
`background-image: url(data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23fff'%3e%3cpath d='M11.354 1.646a.5.5 0 0 1 0 .708L5.707 8l5.647 5.646a.5.5 0 0 1-.708.708l-6-6a.5.5 0 0 1 0-.708l6-6a.5.5 0 0 1 .708 0z'/%3e%3c/svg%3e);`

And for the right icon:
`background-image: url(data:image/svg+xml,%3csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 16 16' fill='%23fff'%3e%3cpath d='M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z'/%3e%3c/svg%3e);`

This icons also doesn't exist in the documentation article, you linked above. Maybe this is planned, or it is caused by the same problem I figured out. The code snippet on the documentation article also has the clickspots for navigating through the Carousel. But it don't has the icons to the left or right, which doesn't makes much sense in my opinion.

Indeed I think that these icons are necessary for controlling the Carousel. I hope its not planned that users are not being able to include them.
I also hope that you can clearly understand me. I'm not that good at writing in English, so its kinda hard to express the problem for me.

**Comment by pavankumar-tidke** [comment]
Where we can see the carousels on the Joomla website. Can you please specify the path for the crousel?

**Comment by Quy** [comment]
Please ask help at [Joomla Forum ](https://forum.joomla.org/).
