### ISSUE TITLE
Logout during article editing

### ISSUE THREAD

**Issue by ch2856** [joomla/joomla-cms#34761]
### Steps to reproduce the issue
Been logout while editing an article

### Expected result
Allow to save 

### Actual result
Logout

### System information (as much as possible)
joomla 3.9.28 
Session Handler DB
lifetime 1200

### Additional comments
I believe the issue started from j3.9.25 or 3.9.26
I never logout actively, and while editing a new article I suddenly see I am logout when trying to add an image ir save the article with a notification I am not allowed to save.

**Comment by richard67** [comment]
And you are sure your session has not expired, i.e. there was no coffee break between starting to edit the article and trying to save it?

**Comment by ch2856** [comment]
I upload about 5-6 articles a day, so sometimes yes, there can be 2-3 min of break doing but most of the time no. It never happen to me on earlier versions.

**Comment by brianteeman** [comment]
Is this in the frontend or the admin?
What editor are you using?
In theory when the editor is open there is a script running to keep the session alive

**Comment by ch2856** [comment]
Admin only. 
The biggest problem is that it's random, I can't recreate the issue to know exactly why or when it happen.

**Comment by Fedik** [comment]
> lifetime 1200

Well, can you please try some reasonable number, around 15-30min. Instead of 20 hours.

**Comment by chmst** [comment]
Can this issue be related to the images? Are they very large or is your webspace exhausted?

**Comment by Quy** [comment]
Closing due to no response with additional details.
