### ISSUE TITLE
[4.0] [Feature request] Change favicon Icon when browser theme changes

### ISSUE THREAD

**Issue by rs4231199** [joomla/joomla-cms#34767]
### Is your feature request related to a problem? Please describe.
There is a light and dark Joomla favicon available, but it doesn't change unless the page is reloaded. 

![e5133b84-6d0c-40ff-92a6-1916bdc8a62b](https://user-images.githubusercontent.com/43215292/125459721-0ce4110b-0135-4afb-9c37-4c07e74f80a0.gif)

### Describe the solution you'd like
It would be nice if the website detects browser theme and update the favicon accordingly.

**Comment by sunil-hash706** [comment]
@rs4231199  Is this issue fixed ? if not I wants to fix this issue.

**Comment by rs4231199** [comment]
> @rs4231199 Is this issue fixed ? if not I wants to fix this issue.

The issue is still open. You can clone the repository and test it.

**Comment by sunil-hash706** [comment]
> > @rs4231199 Is this issue fixed ? if not I wants to fix this issue.
> 
> The issue is still open. You can clone the repository and test it.

Yah sure

**Comment by Ashish-100-tiwari** [comment]
this issue is still open ? if yes , can I work on it .

**Comment by rs4231199** [comment]
The issue is still open.
This problem is specific to chromium browser. Everything works as expected in Firefox. There is an open issue regarding this on chromium's website. I think we should wait for them to fix it.

**Comment by Ashish-100-tiwari** [comment]
OK , Rahul saini .
thank you for replying so quickly

**Comment by coolcat-creations** [comment]
This issue seems to be resolved meanwhile @rs4231199 can you check and if yes close the issue?

**Comment by alikon** [comment]
see #37713
