### ISSUE TITLE
[4.0] Extensions update cache not deletable

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#34775]
### Steps to reproduce the issue
- I have installed a plugin with version 2021.07.**12** with no compatibilty entry for Joomla 4 in update xml file.
- For testing purposes I added a new version 2021.07.**13** in the update xml file and added Joomla 4 compatibilty `<targetplatform name="joomla" version=".*" />`.
- Go into Pre-Update-Checker > "Check For Updates". It tells me that an update to 2021.07.13 is required for this plugin. Correct.
- Go into Extensions > Update. Click "Check For Updates". It tells me that an update to 2021.07.**13** is available for this plugin. Correct.
- I changed the update xml file and removed version 2021.07.**13**. I changed it to already installed 2021.07.**12**.
- I checked that the changed file is delivered correctly from the update server.
- I checked that Joomla uses this file via "Update Sites".
- Go into Pre-Update-Checker. Click "Check for updates". It still shows me version 2021.07.**13**. WRONG.
- Go into Extensions > Update. Click "Check For Updates". It tells me that an update to 2021.07.**13** is available for this plugin. WRONG.
- I clicked several times "Check For Updates". No change.
- Deleted browser caches, Joomla cache tells me that there is "no cached content", logged out from Joomla, logged in again.
- Go into Extensions > Update. Click "Check For Updates". It tells me that an update to 2021.07.**13** is available for this plugin. WRONG.

### Expected result
- In Joomla 3 we have an additional button in Extensions > Update "Clear Cache". It does what it says.
- In Joomla 4 I found no way to clear the extension cache immediately and I had to wait 10 to 15 minutes before the wrong version was removed. Many clicks, reopening and things.

### Question
- Where is the update data cached in Joomla 4 and where/how can I delete it immediately like in Joomla 3 without delay?

**Comment by richard67** [comment]
The cache should be deleted when using the search for updates button:

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_installer/src/Controller/UpdateController.php#L104

No idea yet why it doesn't work here.

But if it works, it doesn't need that extra button anymore which we have in J3, right?

**Comment by ReLater** [comment]
I will check the db tables '#__updates' / '#__update_sites' next time when I test again.

Just BTW: Shouldn't I see this message after clicking? https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_installer/src/Model/UpdateModel.php#L331

**Comment by richard67** [comment]
> Just BTW: Shouldn't I see this message after clicking? https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_installer/src/Model/UpdateModel.php#L331

Not sure, maybe it's later overwritten here? https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_installer/src/Controller/UpdateController.php#L118
