### ISSUE TITLE
[3.10] com_joomlaupdate warning

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34773]
Checking the update component I get the following warning
`Warning: Creating default object from empty value in administrator\components\com_joomlaupdate\models\default.php on line 1470`

![image](https://user-images.githubusercontent.com/1296369/125522857-cffcb45f-b956-40dd-b7d5-1e56128dd8f6.png)

no extensions 
default update channel
php 7.4.7

**Comment by zero-24** [comment]
PR here: https://github.com/joomla/joomla-cms/pull/34774 It can happen when the manifest cache field is emtpy.
