### ISSUE TITLE
[4.0] RC4 Component: Multilingual Associations is Missing

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#34788]
### Steps to reproduce the issue
Please check the Components Menu.
The Multilingual Associations Component is missing.
Intentional?
Accidential?

### System information (as much as possible)
RC4 automatic update from previous.

**Comment by brianteeman** [comment]
Only displayed on a  multilingual site now

**Comment by 200MPHMEDIA** [comment]
Thanks Brian.  Will apply the MLS and check results.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34788">issues.joomla.org/tracker/joomla-cms/34788</a>.</sub>

**Comment by 200MPHMEDIA** [comment]
Right.  When the plugins are enabled, the Multilingual Component link displays in the Component Menu.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34788">issues.joomla.org/tracker/joomla-cms/34788</a>.</sub>
