### ISSUE TITLE
[4.0] Joomla update. "emptystate" blocks Update-Checker

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#34789]
### Steps to reproduce the issue
- Yesterday I updated to nightly 4.0.0-rc5-dev. The new Update-Checker was shown before.
- Today I wanted to update to the current nightly 4.0.0-rc5-dev. And clicked "Check for Updates".
- The Update-Checker is suppressed and I see this:

![14-07-_2021_17-29-42](https://user-images.githubusercontent.com/20780646/125649312-5ab34894-7608-4e46-95bc-2794414e8506.jpg)

- All I can do is to click "Update your site by manually uploading the update package." or "Reinstall" which starts an immediate upload and installation.
- BTW: This "emptystate" behavior is not overrideable like in many other places in Joomla.

### Expected result
- I see the Update-Checker even if I want to reinstall the current Joomla version.

### Actual result
- I see an all in all senseless page with possibility to reinstall Joomla without checks.
- I have to go back to an outdated Joomla version to see the checker.

**Comment by zero-24** [comment]
The pre upgrade checker does not show up when you update to the same version.  You have to downgrade to a lower version or use a updateserver with an higher joomla version.

That should be the case with 3.10 to.

**Comment by ChristineWk** [comment]
@ReLater 
Confirmed. Here is the changed update layout: #34754 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34789">issues.joomla.org/tracker/joomla-cms/34789</a>.</sub>

**Comment by ReLater** [comment]
In order to correct Joomla in a second update step, because one did not pay attention before or was too brave despite warnings, the pre-update checker is absolutely necessary and helpful. to be able to correct one's previously made mistakes.

Do we want to tell people that they have to install a backup of the old site first because of an obvious bug (from my point of view) instead of going through simple solutions first and check again which extensions could be the reason? This makes the idea of the pre-update checker absurd.

I will stop testing Joomla 4 and 3.10 (again). The current solution in favor of a nonsense feature like "emptystate" on this page is not acceptable. I won't make dozens of installations to test this feature.
