### ISSUE TITLE
[4.0] Language Filter automatic language change redirect issue

### ISSUE THREAD

**Issue by Flowman** [joomla/joomla-cms#34799]
### Steps to reproduce the issue

Just want to report that this issue exists in Joomla 4.0 RC4 too. 

https://github.com/joomla/joomla-cms/issues/32816

When using a link to a restricted page on a multilingual site with automatic language changed enabled. After using the login form the user gets thrown to a logout page instead getting redirected to the correct URL.

### System information (as much as possible)

Joomla 4.0 RC4
Cloud Access nightly build

### Additional comments

If someone fixes it pleas backport to 3.9

**Comment by Quy** [comment]
Closing to keep discussion under one issue. #32816 has the labels or J3/J4. Thank for confirming issue with J4.
