### ISSUE TITLE
(4.0) Autum Form Grid issue

### ISSUE THREAD

**Issue by angieradtke** [joomla/joomla-cms#34790]
![grid](https://user-images.githubusercontent.com/1172403/125650244-f1e35d07-2ffd-48ce-b8a5-4a3d5cda36cc.png)

Make  a new menu item of the type:  category- blog.
In the  tab "options"  we can see that the view does not scale in smaller screens , because of the spanning "class-input-field.
The issue is located in the from-grid.
I would use the grid in a different way, maybe @ciar4n can take a look.

**Comment by Quy** [comment]
Please test PR #34145

**Comment by Quy** [comment]
Fixed in #35823.
