### ISSUE TITLE
[4.0] RC 4 -

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#34793]
### Steps to reproduce the issue
Administrator Article Workspace Screen.
When editing a long Article, it is very cumbersome to scroll to the top of the screen to execute a "Save" action, then back down to the content area to continuing editing, then back up to the top to "Save" and so on, over and over.

### Expected result
Can the screen banner and the "Save Buttons" be locked to the top of the Screen so that there is no need to scroll up to perform incremental "saves" when editing long Articles.  This might be appropriate to use globally also.  Simply lock the top two rows and scroll the rest of the screen UNDER the rows.

**Comment by brianteeman** [comment]
Can you post a screenshot or recording to explain this as I dont see what ypu are talking about or I misunderstand
![new1](https://user-images.githubusercontent.com/1296369/125661486-955ec652-d958-4111-9cdb-fd8f0539b3f2.gif)

**Comment by 200MPHMEDIA** [comment]
The blue header row and the "Save" button row should stay locked at the top so that when you move down a long article, they stay locked above the rest of the page that moves.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34793">issues.joomla.org/tracker/joomla-cms/34793</a>.</sub>

**Comment by 200MPHMEDIA** [comment]
When the entire main page scrolls up, those top two rows should not move or disappear.  The page should scroll but the top two rows should stay fixed at top=0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34793">issues.joomla.org/tracker/joomla-cms/34793</a>.</sub>

**Comment by brianteeman** [comment]
sorry - I see it now that I made my browser smaller. Its an easy fix and if no one beats me too it I will make it in the morning

**Comment by 200MPHMEDIA** [comment]
Excellent!  Thank you very much.  It will make progressive saving much easier.  HERB<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34793">issues.joomla.org/tracker/joomla-cms/34793</a>.</sub>

**Comment by brianteeman** [comment]
Sorry - someone else will have to take a look because from what I can there is already a class of subhead on the toolbar which should be making it sticky and its not.

**Comment by 200MPHMEDIA** [comment]
Thanks for checking Brian.  Maybe someone else can pick up the issue and solve it to make them sticky.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34793">issues.joomla.org/tracker/joomla-cms/34793</a>.</sub>

**Comment by Quy** [comment]
Please test PR #34805.
