### ISSUE TITLE
[3.9.28] Changing user in backend always destroys user session.

### ISSUE THREAD

**Issue by Flowman** [joomla/joomla-cms#34798]
### Steps to reproduce the issue

Noticed in latest 3.9.28 there is a new function to destroy user session if password or block has been changed.

https://github.com/joomla/joomla-cms/blob/ced954fef11311a7d4f0653767502dda5b8215d9/administrator/components/com_users/models/user.php#L308

Problem is that the 'password' always contains a string, so it will always destroy the session. It should be using the 'password2' variable that is only set on password changes.

### Expected result

Change a user in backend, and frontend session should not get destroyed when not changing password or blocking user.

### Actual result

Session always get destroyed.

### System information (as much as possible)

Joomla 3.9.28
Php 7.4.20

**Comment by richard67** [comment]
Ping @SniperSister .

**Comment by SniperSister** [comment]
confirmed!

**Comment by Quy** [comment]
Please test PR #34868.
