### ISSUE TITLE
[4.0] Edit module is missing some JS dependencies

### ISSUE THREAD

**Issue by barsdeveloper** [joomla/joomla-cms#34791]
I'm trying to create a new template from scratch. I suspect there are some asset dependencies missing from editing view (dependencies which are added by cassipeia) because when I access the menu module edit page (com_config&view=modules&id=1&Itemid=101), the date selection widgets do not work. They can't be closed and a date can't be selected.
![Cattura](https://user-images.githubusercontent.com/84736467/125652711-0f060f22-31f0-42e3-8bed-3abe8fbe2ec9.PNG)

**Comment by Fedik** [comment]
You have to enable "debug mode",
Then open browser console on "broken page", and check for errors there

**Comment by barsdeveloper** [comment]
I don't see any JS error. I think some script that manage those calendars (make them disappear and appear only when clicking on the icon) is missing.

**Comment by Fedik** [comment]
the calendar script does not have extra dependency, if I right remember

**Comment by barsdeveloper** [comment]
There is at least one CSS issue: when clicking on the Close button on the calendar, it adds the class "hidden" but it is not something bootstrap understands. https://getbootstrap.com/docs/5.0/helpers/visually-hidden/ or maybe "d-none" for better accessibility.
I guess it is defined somewhere in Cassiopeia but not calendar specific css.
![Cattura](https://user-images.githubusercontent.com/84736467/126077126-b645f3f9-c733-45fc-a2cb-2d76ab5adba5.PNG)

Another issue is the button Remove item not properly styled
![Cattura](https://user-images.githubusercontent.com/84736467/126077179-5d3c10b0-642c-443e-92be-6b27a4543243.PNG)

Another CSS fix:
calendar.css defines
.calendar-container {}
with background white but does not define the color. Containers that define the background color, should also define the text color because my body text is white (just defining bootstrap colors sass variables to be a dark theme) so it appears with white text on white background.

**Comment by dgrammatiko** [comment]
> because my body text is white

You can and you should provide your own CSS override in your template for the calendar (and many other core parts). The default CSS was written with the assumption that Protostar would be the template used.

**Comment by Fedik** [comment]
Please test #34871
