### ISSUE TITLE
[4.0] RC 4 Cannot import an image

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#34794]
Since the update of Joomla! 4 RC3 to Joomla! 4 RC4, I cannot import an image to the media manager. I did this manipulation on two different sites and I have the same problem. I also emptied the cache. Do you have an idea ?

![Capture 132 - Médias - Joomla 4 Demo - Administration - joomanji fr](https://user-images.githubusercontent.com/26197929/125666913-bf324406-382b-4205-8ab1-de82251c7ca2.jpg)

**Comment by alikon** [comment]
please check  #34778

**Comment by Magnytu2** [comment]
Ah great, thank you I'll try and confirm the resolution of the problem.

**Comment by Magnytu2** [comment]
@alikon Hello, I confirm that this PR is working correctly to solve the problem of importing images into the media manager. Thank you very much for your help and to the developers.
