### ISSUE TITLE
How to use Font Awesome (or some other icons) on menu items ?

### ISSUE THREAD

**Issue by mariantanase** [joomla/joomla-cms#34801]
### Steps to reproduce the issue
On menu item > Link Type > Link Class, I add a icon class
![shot-icon2-config](https://user-images.githubusercontent.com/3976174/125754378-80116993-74b1-4342-affd-3e5b00c5e95d.png)

### Actual result
![shot-icon1-actual-result](https://user-images.githubusercontent.com/3976174/125754398-5cf52d42-376d-4094-9033-b267b89618ea.png)

### System information (as much as possible)
Joomla 4 RC4
PHP 7.4.13

### Additional comments
Am I wrong with the code ?
Or it's not possible to use icons on menu items ?
Thanks

**Comment by chmst** [comment]
Please test this: https://github.com/joomla/joomla-cms/pull/34658J

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34658 . Thanks in advance.
