### ISSUE TITLE
[4.0.1] Replace "unactivated" to "deactivated"

### ISSUE THREAD

**Issue by max123kl** [joomla/joomla-cms#34800]
### Problem identified
In the entire CMS repo (4.0-dev Branch), the word "unactivated" is used in a string in a total of 3 files, but once also in its value. So that it can be seen publicly.
I am not a native English speaker, but the verb "to unactivate" cannot be found in any English dictionary I know (including the Collins and various other technical dictionaries).

### Proposed solution
In the following files, the string in question should be changed.
`/administrator/components/com_users/src/Helper/UsersHelper.php` and
`/libraries/src/Form/Field/UseractiveField.php`
The new string then looks this way: `COM_USERS_DEACTIVATED`

and in the language file
`/administrator/language/en-GB/com_users.ini`
the string should look like this:
`COM_USERS_DEACTIVATED="Deactivated"`

### Open questions
If there might be any issues with the PHP files, only the value in the language string should be changed.

**Comment by brianteeman** [comment]
Thanks for reporting this. If changed then we would only change the value and not the constant. That way it doesn't impact on translations.

The intention of this text (seen only in the filters) is to show the users who are not marked as having activated their account.

While activated is a positive action and unambiguous I am unsure if there is a suitable single word to indicate "not activated yet". It is definitely not "deactivated" as this is also a positive action ie the account was activated and it has now been deactivated.

I have asked my colleagues at Cambridge University Press for their recommendation. If they don't propose a single word I will suggest that we change to "Not Activated".

_(However we are in language freeze for Joomla 4.0 so any change might not be merged until 4.0.1)_

**Comment by max123kl** [comment]
@brianteeman 
I will revert the commit c83739f and will create a new one with the suggested change.
The branch within my forked repo will remain until it is needed.

**Comment by brianteeman** [comment]
As mentioned I have checked with my colleague who is Senior ELT Research Manager at Cambridge University Press. I include my question and her reply in full below

***

> In Joomla if I have a list of users that may or may not be active. There are two states

> 1. Activated (they have confirmed their account)
> 2. Unactivated (the account was created but has not been confirmed yet)

> I am being told that "unactivated" is not a word?  Is that correct? If it is then what would be a better word to use?

***

>>Seems fine to me. Prefix de- meaning “removal” of something, and prefix un- meaning “not” or “opposite” of something.

>>When people say it’s “not a word”, do they mean it doesn’t appear in dictionaries yet? (It is in [Wictionary,](https://en.wiktionary.org/wiki/unactivated)) There’s always a lag and it takes time for dictionaries to catch up with new words/usages. If enough people start using it, it will end up in the dictionaries eventually. The world isn’t static, and neither is language - if we only ever used words which appeared in the dictionary, we’d struggle to communicate – especially in your sector. Tech/IT is a key driver of language change, and here it is in action. There are always people who get angry about this sort of thing, along with splitting infinitives and ending sentences with prepositions…

>>The only concern I might have is whether people would understand the distinction between deactivated and unactivated if seen out of context of the other states in the list, without the definitions you provide. There might be instances of these used interchangeably, though I’ve not checked. But to me, the distinction is intuitive - especially when you see them in opposition to each other.

>>Difficult to think of an alternative which sits neatly in the set – options could be:
>>Unconfirmed
>>Not yet activated

**Comment by max123kl** [comment]
If I understand the answer correctly, there is no compelling reason to replace the word "Unactivated".
If that is also your intention, I agree.
In that case, the issue can be closed.

**Comment by brianteeman** [comment]
Please close
