### ISSUE TITLE
bootstrap 5 accordion in article or category

### ISSUE THREAD

**Issue by lauraneb** [joomla/joomla-cms#34816]
### Steps to reproduce the issue
to replace the "read more" in the categories which does not exist, I copied the bootstrap 5 accordion code that I adapted (customize id) in category. I tested so in article. 
(the easiest for users would be to have it "read more" in the categories too)

testwebsite joomla 4 : https://mac4.macabann.com/index.php/les-projets

### Expected result
that the tab on which I click opens and the previous one closes

### Actual result
no tab opens or closes since rc2

### System information (as much as possible)
joomla 4.0.0-rc4
Linux webm107.cluster006.gra.hosting.ovh.net 4.14.232-ovh-vps-grsec-zfs-classid #1 SMP Mon May 10 09:26:52 CEST 2021 x86_64
mysql 5.6.50
PHP Version 7.3.27
template cassiopeia
Web Server Apache
web browser : firefox and chromium

### Additional comments
was functional before rc2

**Comment by lauraneb** [comment]
for verification, the bootstrap 5 code brut is in 
https://mac4.macabann.com/index.php/les-projets/11-des-experiences-de-design
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34816">issues.joomla.org/tracker/joomla-cms/34816</a>.</sub>

**Comment by brianteeman** [comment]
https://docs.joomla.org/J4.x:Using_Bootstrap_Components_in_Joomla_4

**Comment by richard67** [comment]
@lauraneb Please check the document linked in the previous comment by @brianteeman and report back if that works for you or not. If it works for you, please close this issue. Thanks in advance.

**Comment by richard67** [comment]
Setting "Information Required" status.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34816">issues.joomla.org/tracker/joomla-cms/34816</a>.</sub>

**Comment by pritam825** [comment]
Now, I have checked it's working fine

**Comment by brianteeman** [comment]
This should be closed now, please.

**Comment by richard67** [comment]
> This should be closed now, please.

Correct. Normally I give the authors a bit time to do that, but as this has passed without reaction, I close this issue now.
