### ISSUE TITLE
[4.0] RC4 Media manager "restrict uploads" option not working as expected

### ISSUE THREAD

**Issue by Mrs-Jaydot** [joomla/joomla-cms#34814]
### Steps to reproduce the issue
Log in as SU, leave "restrict uploads" ON, upload a .jpg in the media manager

### Expected result
The jpg uploads. Because it is an image, and SU is "higher" than manager.

### Actual result
Error message "Cannot upload the file".

### Additional comments
When "restrict uploads" is switched OFF, the SU can upload files without problems.

**Comment by Quy** [comment]
Thanks for the report. Fixed in #34778. 

Please test using the nightly builds. https://developer.joomla.org/nightly-builds.html

**Comment by Mrs-Jaydot** [comment]
Thank you!

**Comment by Webdongle** [comment]
I initially tested with J4.0.0 rc4 on Wamp on a laptop.  Did not experience the problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34814">issues.joomla.org/tracker/joomla-cms/34814</a>.</sub>
