### ISSUE TITLE
[4.0] unused scss ?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34828]
https://github.com/joomla/joomla-cms/blob/3071cd68a5d17e9616144e5ee003f143122c2aa6/templates/cassiopeia/scss/blocks/_modals.scss#L21-L39

Can someone tell me where this is used please. I just can't find any use

**Comment by dgrammatiko** [comment]
It's redundant BS5 has `<button type="button" class="btn-close novalidate" data-bs-dismiss="modal" aria-label="Close"></button>` a class `btn-close` where it used to be `close`.

Kill it

**Comment by brianteeman** [comment]
I thought so - just wanted a sanity check - thanks
