### ISSUE TITLE
[4.0] Long hints of search fields are hidden under the header-inside

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34842]
### Steps to reproduce the issue
The control panel has a lot of hints for search fields. There are short ones. But there are also long ones (for example, on the CONTENT / Articles page). Such hints are hidden under the header-inside.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/126218063-fd96af26-4f01-48fe-81de-48e18a234f7e.png)

I'm not sure if this is on all monitors, but I tried to change the scale of the site and the situation with the prompt was always reproduced.

**Comment by Quy** [comment]
Fixed in #34805. Thanks for the report.
