### ISSUE TITLE
[4.0] admin menu rtl

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34843]
### Steps to reproduce the issue
When the admin menu sidebar is collapsed then the flyout submenus are not displayed in RTL when you hover over the icon

### LTR
![ltr](https://user-images.githubusercontent.com/1296369/126226908-4dbb3c94-b71c-4c2c-8c95-6e906f8be2ac.gif)

### RTL
![rtl](https://user-images.githubusercontent.com/1296369/126226885-07243558-9f5a-47d9-bab0-1b18590a8f25.gif)

**Comment by wilsonge** [comment]
PR https://github.com/joomla/joomla-cms/pull/34869
