### ISSUE TITLE
[4.0] Non-localized strings in taxonomy results

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34841]
### Steps to reproduce the issue
1. Install some other language (it is desirable that it is clearly different from English). For example, [Russian](https://github.com/JPathRu/localisation/releases/tag/4.0.0-RC4).
2. Enable the option for taxonomy of results in the smart search component.
3. Install demo data.
4. Go to the frontend and try to enter some obvious word / phrase in another language (not en-GB).

You will get results. And in the taxonometry column there will be terms that are not localized.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/126215986-1c0dab55-7bea-42ed-9a70-dd0fad86dadf.png)

A piece of code that outputs the lines:

```
<ul class="result__taxonomy">
	<?php foreach ($taxonomies as $type => $taxonomy) : ?>
		<?php $branch = Taxonomy::getBranch($type); ?>
		<?php if ($branch->state == 1 && in_array($branch->access, $user->getAuthorisedViewLevels())) : ?>
			<?php $taxonomy_text = []; ?>
			<?php foreach ($taxonomy as $node) : ?>
				<?php if ($node->state == 1 && in_array($node->access, $user->getAuthorisedViewLevels())) : ?>
					<?php $taxonomy_text[] = $node->title; ?>
				<?php endif; ?>
			<?php endforeach; ?>
			<?php if (count($taxonomy_text)) : ?>
				<li class="result__taxonomy-item result__taxonomy--<?php echo $type; ?>">
					<span><?php echo $type; ?>:</span> <?php echo implode(',', $taxonomy_text); ?>
				</li>
			<?php endif; ?>
		<?php endif; ?>
	<?php endforeach; ?>
</ul>
```

Anticipating the question, are all strings translated ...? Yes, everything is translated. It's not about the constants.

**Comment by Kostelano** [comment]
The same story in the control panel - smart search - content index. Choosing a content map.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/126216821-4295c197-71ba-4918-8d3d-bd830673ee1c.png)

By the way, in Joomla 3 too.

**Comment by wilsonge** [comment]
// cc @Hackwar

**Comment by brianteeman** [comment]
Found the problem - looking for a solution

**Comment by brianteeman** [comment]
Only checked the admin but its almost certainly the same problem. The untranslated words are the taxonomy branches. Taxonomy branches are created in the finder plugins for example

https://github.com/joomla/joomla-cms/blob/7682b166f09c8029efa813e8f0c4813aebb56386/plugins/finder/contacts/contacts.php#L375-L379

As can be seen this will create a taxonomy branch called **Country**

You can confirm this by first changing Country to Fruit. Clearing the finder index and then reindexing the content.

The dopdown filter will now have a section called Fruit

**Comment by brianteeman** [comment]
I might have confused the term contentmap and taxonomybranch

**Comment by brianteeman** [comment]
PR coming

**Comment by brianteeman** [comment]
Changing the code above to 
`$item->addTaxonomy('PLG_FINDER_QUERY_FILTER_BRANCH_P_COUNTRY', $item->country); 
`

and then updating

https://github.com/joomla/joomla-cms/blob/7682b166f09c8029efa813e8f0c4813aebb56386/administrator/components/com_finder/src/Field/ContentmapField.php#L93-L96

to 
`$name = TEXT::_($branch->text);`

Seems to be a good starting point but it becomes a bit of a rabbit hole after that so maybe this isnt the correct approach.

Anyone?

**Comment by Fedik** [comment]
> Changing the code above to $item->addTaxonomy('PLG_FINDER_QUERY_FILTER_BRANCH_P_COUNTRY', $item->country);

I do not think that it is a good idea doing it when indexing, 
It should be translated while rendering. Somewhere in layout (and field).

> $name = $branch->text;

hm, in j3 there it without JText, does it also issue on Joomla 3?

**Comment by brianteeman** [comment]
> I do not think that it is a good idea doing it when indexing,

Its not translating it during indexing. Its just using a translatable key instead of hard-coded english

**Comment by brianteeman** [comment]
> hm, in j3 there it without JText, does it also issue on Joomla 3?

Honestly no idea. I never work with joomla in any other language.

**Comment by Kostelano** [comment]
Yes, in Joomla 3 the situation is the same. Only in the control panel.

**Comment by Hackwar** [comment]
#36863 fixes this.

**Comment by Quy** [comment]
Closing as having a pull request.

**Comment by Destroy666x** [comment]
So, how exactly do you translate those now? I have latest translations + I see the merged code is in the search results template, but the labels are still in English. I guess I need some overrides, but not too sure how they should be called.

**Comment by Hackwar** [comment]
You have to add translation strings in the format `PLG_FINDER_QUERY_FILTER_BRANCH_S_[taxonomy-title]`. No need to create layout overrides or something.

**Comment by Destroy666x** [comment]
Not layout overrides, language overrides.

Where to get the taxonomy title? I tried e.g. `AUTHOR` (`PLG_FINDER_QUERY_FILTER_BRANCH_S_AUTHOR`) for Author or `TYPE` (`PLG_FINDER_QUERY_FILTER_BRANCH_S_TYPE`) for Type but nope. I also looked in other popular language packages and no sign of `PLG_FINDER_QUERY_FILTER_BRANCH_S_` in them. This could certainl be better documented IMO.
