### ISSUE TITLE
[4.0] Pagination Frontend

### ISSUE THREAD

**Issue by angieradtke** [joomla/joomla-cms#34850]
Hi , 
one question. 
Why do we have an onclick event on the  pagination links now ? 
Why is  the href not  used anymore?
```
<a <?php echo $cssClasses ? 'class="' . implode(' ', $cssClasses) . '"' : ''; ?> <?php echo $title; ?> href="#" onclick="<?php echo $onClick; ?>">
			<?php echo $display; ?>
		</a>
```
Sorry, I think I just had versionschaos

Has settled - I had version chaos

**Comment by richard67** [comment]
> Sorry, I think I just had versionschaos
>
> Has settled - I had version chaos

@angieradtke So this issue can be closed? Or is there still an issue?

**Comment by angieradtke** [comment]
yes, sorry

**Comment by richard67** [comment]
> yes, sorry

@angieradtke Yes what? Yes, can be closed? Or yes, is still an issue?

**Comment by angieradtke** [comment]
@richard67 can be closed, sorry

**Comment by richard67** [comment]
Thanks ... all fine.
