### ISSUE TITLE
[4.0] Changelog popup. language badge not readable.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#34852]
#### 1) Install test extension
- Can be tested with installation of test plugin https://github.com/GHSVS-de/plg_system_changelogtest/archive/refs/tags/0.0.1.zip

#### 2) OR code youself

- Install outdated version of an extension that supports changelog view feature https://docs.joomla.org/Adding_changelog_to_your_manifest_file
- Prepare changelog.xml and update.xml for a newer version with tag in changelog.xml
```
<language>
	<item><![CDATA[
		Some corrections and translations..
	]]></item>
</language>
```

#### Then for both variants 1) and 2)
- Go to administrator/index.php?option=com_installer&view=update and "Check for updates".
- Click "Changelog"
![20-07-_2021_18-26-35](https://user-images.githubusercontent.com/20780646/126361845-ee5e2d9a-0976-4d98-80a9-446ec4a34d33.jpg)

### Expected result
- Language badge readable.

### Actual result
![20-07-_2021_18-24-21](https://user-images.githubusercontent.com/20780646/126361861-36d8093e-ac0b-4e66-b55b-68fde15c7966.jpg)

**Comment by Quy** [comment]
Thanks for the report/extension. Please test PR #34858.
