### ISSUE TITLE
[4.0] .hidden class missing in media/system/css/fields/calendar.css

### ISSUE THREAD

**Issue by angieradtke** [joomla/joomla-cms#34863]
Use of custom field calendar in com_contact mailform

If the frontend template does not have class .hidden, 
the calendar is always expanded.

Solution
media/system/css/fields/calendar.css 

adding

`.js-calendar.hidden
{display:none}`

**Comment by brianteeman** [comment]
class=hidden is used in lots of places in the frontend. So the proposed solution is just a band aid for one possible issue and not a solution for the non-core template not having the required class

**Comment by angieradtke** [comment]
The calendar should be encapsulated and work everywhere.
If a template does not have the hidden class it will not work.
This is a simple fix to ensure functionality everywhere.

**Comment by brianteeman** [comment]
> This is a simple fix to ensure functionality everywhere.

so submit a pull request - dont expect others to do it for you

**Comment by richard67** [comment]
@angieradtke It needs to change it in the "build/media_source" here https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/system/css/fields/calendar.css , not in the "media" folder.

**Comment by angieradtke** [comment]
@richard67 You certainly know better than me where to change . 
I'm tinkering a page here from the scratch with all possible functionalities and note possible errors.

**Comment by richard67** [comment]
> @richard67 You certainly know better than me where to change .

@angieradtke Well now you know it too :smile: Do you want to make a PR or shall someone else do it?

**Comment by angieradtke** [comment]
> so submit a pull request - dont expect others to do it for you

I think I can help more by pointing out the things I find while experimenting.
@richard67
  I would do it, but for you  it is easy. It is not my daily buisness, so I forgot every time how it works.
  For me it takes hours. Checking out the stuff to may local computer,  etc...
With svn it was easy creating a patch done, but ....

**Comment by dgrammatiko** [comment]
The code has a class hidden because at that time IE8 and IE9 were still supported. These days an attribute `hidden` will do the work **without any lines of CSS**.

My 2c

**Comment by richard67** [comment]
I'd prefer someone else than me to make a PR.

**Comment by angieradtke** [comment]
@dgrammatiko @richard67 
Yes, as long as we don't have an attribute hidden and we use the class we also need appropriate CSS.

**Comment by dgrammatiko** [comment]
@Fedik is already patching the calendar right now for the strings, ask him to change the toggling of the class to a toggle of a `hidden` attribute...


Eg change https://github.com/joomla/joomla-cms/blob/3395ffcaae04998bacb80e0cbb4e3713dff2b497/build/media_source/system/js/fields/calendar.es5.js#L259
to this `this.dropdownElement.removeAttribute('hidden');`
and https://github.com/joomla/joomla-cms/blob/3395ffcaae04998bacb80e0cbb4e3713dff2b497/build/media_source/system/js/fields/calendar.es5.js#L282 to `this.dropdownElement.setAttribute('hidden', '');`

2 lines of code can be done in the Github by editing the file...

**Comment by Fedik** [comment]
this may be related #34791, just for reference

**Comment by Fedik** [comment]
Please test #34871
