### ISSUE TITLE
[4.0] Language selection on batch modal 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#34874]
### Steps to reproduce the issue
Install at least two languages, but don't make the site multilingual.

Go to Artilces overview.
The language column is not shown.
Activate one or more items and call the action "Batch". 

### Expected result
On the batch modal, language change is not enabled

### Actual result
language change is enabled 

![grafik](https://user-images.githubusercontent.com/1035262/126704293-141aba14-1011-4423-ad67-9204bd1574ba.png)

This is a bit confusing, because you don't know which language now is set for the articles. 

How to resolve this? Change the language select field or check every batch modal?

**Comment by brianteeman** [comment]
> How to resolve this? Change the language select field or check every batch modal?

I would say that the preferred option is to add the `if (Multilanguage::isEnabled())` check to every batch modal but an alternative would be to do that once in the layout but this might result in invalid html

**Comment by chmst** [comment]
Agree, simple but no risk.  I will do it right now for weblinks where I am working at the moment.

**Comment by brianteeman** [comment]
should I do it here ?

**Comment by chmst** [comment]
If you have the time, yes, please!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34874">issues.joomla.org/tracker/joomla-cms/34874</a>.</sub>

**Comment by brianteeman** [comment]
Filming this morning. Will do it tonight

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34887 . Thanks in advance.
