### ISSUE TITLE
J4 RC 4 Warning COM_INSTALLER_MSG_WARNINGS_PHPUPLOADNOTSET message

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#34889]
### Steps to reproduce the issue

Clean Joomla 4 RC 4 installation.
Go to .../administrator/index.php?option=com_joomlaupdate&view=upload

### Expected result

See message:
The PHP temporary folder is not set.

### Actual result

See message labels:
Warning COM_INSTALLER_MSG_WARNINGS_PHPUPLOADNOTSET
COM_INSTALLER_MSG_WARNINGS_PHPUPLOADNOTSETDESC

### System information (as much as possible)

PHP 7.4
Windows 10

**Comment by Quy** [comment]
Thanks for the report. Fixed per #34804. Please test with the nightly builds. https://developer.joomla.org/nightly-builds.html
