### ISSUE TITLE
[4.0] Better error message for failed media upload

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#34897]
### Steps to reproduce the issue
- Create a new article
- Click on Select button to select an image.
- On the popup, click on Upload button
- Select a PDF file to upload

### Expected result
A friendly message telling users that they can only upload image here or the the file type is not allowed.

### Actual result
A red unfriendly message Error Occur displayed.

### System information (as much as possible)
Joomla 4 nightly build.

**Comment by Quy** [comment]
Related #33702

**Comment by joomdonation** [comment]
Closing because it is duplicate.
