### ISSUE TITLE
[4.0] Error "The template for this display is not available" after update from 3.10

### ISSUE THREAD

**Issue by Bond97** [joomla/joomla-cms#34908]
Maybe that error it's ok, but I want to create issue. Or it's not ok?

### Steps to reproduce the issue
1. Install clean 3.9.28
2. Update to 3.10 alpha 9
3. Set update url https://update.joomla.org/core/test/310to4_list.xml
4. Update to Joomla 4 rc-4
5. See error at the screenshot on "Actual result"

### Expected result
Update process without any errors

### Actual result
![изображение](https://user-images.githubusercontent.com/78050514/126943186-53b967c0-ff4e-47dc-a462-c78214319717.png)

### System information (as much as possible)

PHP 8.0.8, Mysql 5.7.34

**Comment by Kostelano** [comment]
I was getting the same error when I upgraded from 3.9 to 3.10 to 4.0.

**Comment by richard67** [comment]
It is well known that this is shown one time after the update and then disappears and doesn't come again when you start to navigate around in backend.

**Comment by Kostelano** [comment]
Everything is correct. However, I'm starting to curl my fingers how many more of these Issue will be created upon the release of the stable version 4.0.

**Comment by richard67** [comment]
Yes, that would be a pain. I'm just clarifying if we have some docs about it or if we need some or need more.

**Comment by Bond97** [comment]
@richard67 maybe it will be better to show full description about this? When Joomla 4 goes to stable version, users will be ask questions about it.

For example, "The template Isis is not supported with Joomla 4 and now, after upgrade from Joomla 3.10, it was deleted"

**Comment by richard67** [comment]
> For example, "The template Isis is not supported with Joomla 4 and now, after upgrade from Joomla 3.10, it was deleted"

It's an error message shown in general when the template is not available. We don't have one for that special case of just having updated from 3.10 to 4.0. So if we just change the message text as suggested, the message will be wrong in other cases of missing templates.

**Comment by brianteeman** [comment]
So maybe we should look at changing that so it is a specific error with a specific message OR work to prevent that message appearing in the first place.

**Comment by brianteeman** [comment]
Looking at the code and considering what situation would trigger this message I would suggest not outputting a message at all by removing the following line or replacing it with a log message (ie not displayed on screen)

https://github.com/joomla/joomla-cms/blob/eeb71ee627f4328474edac300bce05bfb6d28623/libraries/src/Application/AdministratorApplication.php#L275

The reality is that 99.99% of the time it will only be shown on updates and that is the one time that the message is incorrect and of no use.

**Comment by richard67** [comment]
> Looking at the code and considering what situation would trigger this message I would suggest not outputting a message at all by removing the following line or replacing it with a log message (ie not displayed on screen)

I'd be ok with that. Opinions from others are welcome.

**Comment by wilsonge** [comment]
I'd be happy with a log message too. I think it's fairly consistent with things as it's not something that an end user can fix anyhow if they saw it in the frontend too.

**Comment by brianteeman** [comment]
this would only be in the admin but I will prepare a PR

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34912 (and if necessary continue discussion there). Thanks in advance.

**Comment by richard67** [comment]
Re-opening since the pull request has been closed.

**Comment by Fedik** [comment]
I have made another one #34914 , please review first, maybe it also not good

**Comment by Fedik** [comment]
Because we cannot use `jerror` for log there, and seems we do not have another appretiere category, so instead of introducing new category (that will be only here and no one will know about it) I suggest to remove that line.

A couple lines down there an exception if something crazy happen:
https://github.com/joomla/joomla-cms/blob/b892e8ada3c77560c520610ab5556d5322833c2d/libraries/src/Application/AdministratorApplication.php#L275-L283

**Comment by brianteeman** [comment]
agree

**Comment by Fedik** [comment]
another one #34930 please check :)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34930 . Thanks in advance.
