### ISSUE TITLE
[4.0] search_ignore

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#34909]
I was looking at the german language files and saw a big list of words in an array to be used by `getIgnoredSearchWords` and several other search related settings.

- getIgnoredSearchWords
- getLowerLimitSearchWord
- getUpperLimitSearchWord
- getSearchDisplayedCharactersNumber

The problem is that as far as I can tell they were only used by com_search and are not used by com_finder

For com_finder I believe the equivalent is 
- `getIgnoredSearchWords` is the list of words in `com_finder.commonwords.txt`
and this is not enabled by default in the component options _Filter Common Words_

I dont see any equivalents for the other three

cc @HLeithner 

_UPDATE_
I am guessing that these 4 settings will still be used by the code in the decoupled com_search which, for me, is a problem in that we have to maintain settings in core that are never used in core. If decoupled com_search needs these settings then they should be part of the component

**Comment by HLeithner** [comment]
> I was looking at the german language files and saw a big list of words in an array to be used by `getIgnoredSearchWords` and several other search related settings.
> 
> * getIgnoredSearchWords
> * getLowerLimitSearchWord
> * getUpperLimitSearchWord
> * getSearchDisplayedCharactersNumber
> 
> The problem is that as far as I can tell they were only used by com_search and are not used by com_finder
> 
> For com_finder I believe the equivalent is
> 
> * `getIgnoredSearchWords` is the list of words in `com_finder.commonwords.txt`
>   and this is not enabled by default in the component options _Filter Common Words_
> 
> I dont see any equivalents for the other three

I noticed this too and asked @Hackwar and he confirm this is not used in com_finder. The commonwords list can be edited in crowdin with a variable count of words.

> 
> _UPDATE_
> I am guessing that these 4 settings will still be used by the code in the decoupled com_search which, for me, is a problem in that we have to maintain settings in core that are never used in core. If decoupled com_search needs these settings then they should be part of the component

I would say it's a bit late to change this and would keep then till the EOL of Joomla 4 and remove it in Joomla 5.0 if not used by any other component.

or did I missed anything @Hackwar ?

**Comment by brianteeman** [comment]
maybe added a deprecated note and/or a comment where it is used ?

**Comment by HLeithner** [comment]
the Problem is that it's defined in the language packs... but sure in the cms when we call the function we should create a note to it's deprecated.
