### ISSUE TITLE
Updating one library removes files for another

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#34910]
### Steps to reproduce the issue

Create 2 libraries with the manifest libraryname field as follows:

&lt;libraryname&gt;mycompany/mylibrary1&lt;/libraryname&gt;

&lt;libraryname&gt;mycompany/mylibrary2&lt;/libraryname&gt;

Both successfully installed and accessible / usable by my component.

Make a change to _mylibrary1_ and install the new version (do not uninstall ... just run the installer).

### Expected result

_mylibrary1_ updated.
_mylibrary2_ not changed.

### Actual result

_mylibrary1_ updated.
_mylibrary2_ files in JPATH_SITE/libraries/mycompany/mylibrary2 removed.

Have to uninstall both libraries and install both again.

### System information (as much as possible)

Windows 10
PHP 7.4

### Additional comments

Problem at lines 310-314 of Installer/Adapter/LibraryAdapter.php 

These should read:
if (2 === \count($elementParts))
{
  Folder::delete(JPATH_MANIFESTS . '/libraries/' . $elementParts[0] . '/' . $elementParts[1]);
  Folder::delete(JPATH_PLATFORM . '/' . $elementParts[0] . '/' . $elementParts[1]);
}

**Comment by brianteeman** [comment]
As you have a proposed fix please submit a pull request

**Comment by BrainforgeUK** [comment]
Correction to **Additional Comments** - suggested code change should read...

if (2 === \count($elementParts))
{
  $folders = Folder::folders(JPATH_PLATFORM . '/' . $elementParts[0], '.', false, true, array(), array());
  if (empty($folders))
  {
    Folder::delete(JPATH_MANIFESTS . '/libraries/' . $elementParts[0]);
    Folder::delete(JPATH_PLATFORM . '/' . $elementParts[0]);
  }
}
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34910">issues.joomla.org/tracker/joomla-cms/34910</a>.</sub>

**Comment by richard67** [comment]
Closing as having a pull request.

@BrainforgeUK It would save us time if you would close your issue yourself when having made yourself a pull request to solve it.
