### ISSUE TITLE
[4.0] Category List / Blog SEF menu item

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#34915]
Hi guys, 
PHP 7.4.21 + Joomla RC4
- Joomla Global Configuration > Site > Search Engine Friendly URLs: Yes
- Joomla Global Configuration > Site > Use URL Rewriting:: Yes
- Joomla Content > Options > Integrations > Remove IDs from URLs: Yes

I create a Category List (or Blog) menu item:
- without to set Tags the Menu Item URL in frontend is SEF .../category-list
- with Tags added  the Menu Item URL in frontend is not SEF, tags filters are shown .../category-list?filter_tag[0]=2

Shouldn't the SEF URL![screen shot 2021-07-26 at 15 54 44](https://issues.joomla.org/uploads/1/e2c90d8fe4615e2c0cd1b5ae39dea936.jpg) be kept?![screen shot 2021-07-26 at 15 54 44](https://issues.joomla.org/uploads/1/8107bf778c71a17ff1dedc48b7d1bbb1.jpg)

**Comment by richard67** [comment]
There is already an issue for that, #34527 , which has been closed because there is a pull request which claims to solve it, ~~34915~~ #34652 .

That pull request seems to try to solve the issue in the wrong way, so it has to be modified.

But so or so this here is a duplicate report => Closing.

**Comment by joomleb** [comment]
@richard67,
be careful, the pull request is #34652  Am I right ?

Thanks for the info, I'm going to test it and sorry for the duplicate, I didn't found them...

**Comment by richard67** [comment]
> be careful, the pull request is #34652 Am I right ?

Yes, that's the right one.
