### ISSUE TITLE
[4.0] Media field preview shows no image when url has no extension

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#34921]
When adding a url into the image field of an article which has no extension, then the preview image is not rendered. This is the case for example with google drive which creates urls like https://drive.google.com/uc?id=dr123&export=download.

![image](https://user-images.githubusercontent.com/251072/127122409-925be238-393a-4def-abad-938dc7c55d40.png)

Issue appears since #34634.

@dgrammatiko any idea?

**Comment by dgrammatiko** [comment]
Might be https://github.com/joomla/joomla-cms/blob/caf4cb707443c9d762aee0c66ada1d8d6917381f/build/media_source/system/js/fields/joomla-field-media.w-c.es6.js#L212

Check what the value is there (maybe you have to remove the hash part of the url)

**Comment by laoneo** [comment]
Problem is that the extension can't be determined here https://github.com/joomla/joomla-cms/blob/caf4cb707443c9d762aee0c66ada1d8d6917381f/build/media_source/system/js/fields/joomla-field-media.w-c.es6.js#L200 so it will not even arrive on 212.

**Comment by dgrammatiko** [comment]
@laoneo pass me some some valid URL in DM (tweeter or whatever)

**Comment by dgrammatiko** [comment]
@laoneo this should do it:

```js

const getExtension = (path) => {
  const parts = path.split(/[#]/);
  if (parts.length) {
    const clean = parts[1].split(/[\?]/);
     return clean[0].split('.').pop().trim()
  }
  return path.split(/[#?]/)[0].split('.').pop().trim();
}

```

**Comment by laoneo** [comment]
It does, do you make a pr?

**Comment by dgrammatiko** [comment]
sure

**Comment by dgrammatiko** [comment]
@laoneo done: https://github.com/joomla/joomla-cms/pull/34922

**Comment by richard67** [comment]
Closing as having a pull request. Please test #34922 . Thanks in advance.
