### ISSUE TITLE
[4.0] Changing default Admin Menu Preset results in 500 error

### ISSUE THREAD

**Issue by jameswadsworth** [joomla/joomla-cms#34928]
This Joomla 4 RC4

Go into admin -> System -> admin modules -> Admin Menu and click on save and close

I would expect the module to save and close correctly

Instead it throws a 500 error Call to a member function authorise() on null  in /shared/httpd/jooomla4xxx/public_html/administrator/modules/mod_menu/src/Menu/CssMenu.php (line 416) 

```php
                {
                    $parent->removeChild($item);
                    continue;
                }
                elseif (($item->link === 'index.php?option=com_installer&view=install' || $item->link === 'index.php?option=com_installer&view=languages')
                    && !$this->user->authorise('core.admin'))
                {
                    continue;
                }
                elseif ($item->element === 'com_admin')
                {
```

$this->user is not a populated object and needs converting to $user for it to work correctly.

**Comment by joomdonation** [comment]
Thanks @jameswadsworth . Your provide solution is correct, in the future, do you mind making PR directly?

For this one, I made the PR https://github.com/joomla/joomla-cms/pull/34929 so that it could be merged and included in next RC release (which is planned later today).
