### ISSUE TITLE
[4.0] Redirects: Empty new URL

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34935]
### Steps to reproduce the issue
Similar to the old issue https://github.com/joomla/joomla-cms/issues/28621.

Go to System - Redirect, create a redirect link. Then in the list of links select the link + at the bottom select batch processing - do not fill anything, but update the link. Batch processing will complete successfully, but now the selected link has empty in the new URL field.

I do not know what behavior in this case will be when clicking on the old link (in theory, nothing to worry about), but at least when creating a link, the form will not be sent until you fill in both fields (old / new URL URL).

I think that if the system in one case asks to fill in a field, then when batch processing links, you need to repeat the requirement.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/127216712-8ecd775f-d997-4c1b-8526-39a636c48319.png)

**Comment by pinak3748** [comment]
Confirmed, it updates the old link with a new blank one.

**Comment by brianteeman** [comment]
If I remember correctly there was a problem here that the update links form is not actually a separate form to the batch modal and this prevented making the fields here to be required.

There should be an open issue about this. Perhaps by @wilsonge

**Comment by Quy** [comment]
Duplicate #25489
