### ISSUE TITLE
[4.0] No validation of Joomla service pack before updating it

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34939]
### Steps to reproduce the issue
I'm not sure if this is the expected behavior. If I'm wrong, close this.

Pack any file into a ZIP archive, whatever. For example, a program with an exe file. Go to System - Joomla Update, select the manual installation item (below), select the archive and install. Joomla will be "updated" with a message that it has been successfully updated to "such and such version". All contents of the archive go to the root of the site.

**Comment by wilsonge** [comment]
This is expected behaviour and is why Joomla Update is hard restricted to super admins.
