### ISSUE TITLE
[4.0] Line at the end of the page in front of the buttons

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34937]
### Steps to reproduce the issue
Install demo data, log in to the frontend. There will be a menu on the right, go through the items. At the very bottom of the page there is an incomprehensible line (which, by the way, was removed earlier on the profile page ... forgotten).

On the menu items:

**Site parameters**,
**Template parameters**. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/127218065-99932ebe-9094-4462-9d81-36a9cf52b7be.png)

**Comment by pavankumar-tidke** [comment]
can you please specify the path of this page?

**Comment by Kostelano** [comment]
Sorry, but Joomla is not at hand. And everything is written in the topic - the menu on the right AFTER authorization in the frontend, then the specified menu items.

**Comment by brianteeman** [comment]
please test #34958
