### ISSUE TITLE
[4.0] Remove old icons in new releases? 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#34931]
Joomla used some icons in media / system / images.

Now all icons are icons from icon fonts. I could not find any usage of the old icons in J4.

In J4 we could get rid of the old images and not deliver them anymore. Probably it is not necessary to delete them during upgrade, maybe there are older extension using them?

I suggest that new Joomla releases do not deliver these icons, but leave them in upgraded version (do not delete during upgrade)

mooRainbow
arrow.png
arrow_rtl.png
blank.png
calendar.png
checked_out.png
edit.png
edit_unpublished.png
emailButton.png
icon_error.gif
icon-16-logout.png
indent.png
indent1.png
indent2.png
indent3.png
indent4.png
indent5.png
jquery.minicolors.png
livemarks.png
livemarks-rtl.png
mootree.gif
mootree_loader.gif
new.png
no_indent.png
pdf_button.png
printButton.png
rating_star.png
rating_star_blank.png
sort_asc.png
sort_desc.png
sort_none.png
sort0.png
sort1.png
tooltip.png
weblink.png
mooRainbow/blank.gif
mooRainbow/moor_arrows.gif
mooRainbow/moor_slider.gif
mooRainbow/moor_cursor.gif
mooRainbow/moor_woverlay.png

<img width="784" alt="system-images" src="https://user-images.githubusercontent.com/1035262/127184049-fc9b0294-264b-49c7-95b2-5434095e4186.PNG">
<img width="548" alt="images-moor" src="https://user-images.githubusercontent.com/1035262/127184061-65139645-264f-466a-a8ad-b75d44bcb1ea.PNG">

**Comment by brianteeman** [comment]
see #33768

**Comment by dgrammatiko** [comment]
kill them with fire

**Comment by chmst** [comment]
killed with a pr #34962. please test.
