### ISSUE TITLE
[4.0] Underlined link to all notes

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#34936]
### Steps to reproduce the issue
Users, create a new note. Go back to the users page, notice that there is a style inconsistency for links in the dropdown. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/127217578-8ec681e2-bc45-48b0-8aba-1cc0290ee254.png)

**Comment by brianteeman** [comment]
Please test #36947
