### ISSUE TITLE
[4.0] Custom Fields Multiple List Layout AJAX Select Missing

### ISSUE THREAD

**Issue by David2376** [joomla/joomla-cms#34941]
### Steps to reproduce the issue
Create a custom field with type list and multiple set to yes.
Create or edit a new article.

### Expected result
Expecting the list to be an AJAX select list like in Joomla 3. (see attached images)

### Actual result
The list is a scrolling list. (see attached images)

### System information (as much as possible)
Joomla 4.0.0-rc4

**Comment by David2376** [comment]
![screen shot 2021-07-27 at 20 20 16](https://issues.joomla.org/uploads/1/9eb7837d63c8d61ed72f34478ea15b54.png)

![screen shot 2021-07-27 at 20 20 21](https://issues.joomla.org/uploads/1/b681c626a0390d3e5750a02679c5b094.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34941">issues.joomla.org/tracker/joomla-cms/34941</a>.</sub>

**Comment by brianteeman** [comment]
Please test #36551
