### ISSUE TITLE
J4RC5 Inconsistency in property name and label

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#34953]
### What needs to be fixed
&lt;field
	name="siteDescription"
	type="text"
	label="TPL_CASSIOPEIA_TAGLINE"
/&gt;

The field name and label are inconsistent.
Not minor difference, as elsewhere, but totally different.

### Why this should be fixed

Easier reuse in child templates.

### How would you fix it

Change the field name to **siteTagline**
Also change the related CSS class **site-description** to **site-tagline**

Some may argue for changing the label instead - not my first choice.
I prefer the word 'Tagline' as displayed on the style configuration page.
If site developer / admin want to change the text they will use language override anyway.

### Side Effects expected

Any existing child templates - but as this is at RC stage the author should be anticipating such changes.

**Comment by brianteeman** [comment]
Do you mean for example that
```
			name="loggable_verbs"
			label="COM_ACTIONLOGS_LOGGABLE_VERBS"
```

ie label should be "COMPONENT_FIELDNAME"

If so then then there has never been a standard for this and you will find a large number of labels that do not follow this _rule_

OR do you mean something else??

**Comment by BrainforgeUK** [comment]
A standard / recommendation for this as you suggest could be a good direction to go in.
Makes it easier looking for every use of LOGGABLE_VERBS (ignoring case) in an IDE.

In this particular case I was thinking of changing the field definition to:

&lt;field
name="siteTagline"
type="text"
label="TPL_CASSIOPEIA_TAGLINE"
/&gt;

In line with your comment this would be even better!
But then where do you stop changing labels everywhere ...
Maybe just make a change when it crosses one's path, like this one.

&lt;field
name="siteTagline"
type="text"
label="TPL_CASSIOPEIA_SITETAGLINE"
/&gt;

**Comment by brianteeman** [comment]
> Maybe just make a change when it crosses one's path, like this one.

That just makes the situation worse.

Changing any of this at this time (rc5) is never going to happen. Realistically the next time this could be changed would be joomla 5 (imho)

**Comment by richard67** [comment]
I see not really an issue in sense of a bug in it. Shall we move it do discussions?

**Comment by BrainforgeUK** [comment]
Worth keeping in mind and include in discussions about future changes to standards / recommendations.

In meantime created pull request #34955 

I've not changed the CSS classes or _header.css
Be better if site-description changed to site-tagline for consistency.
Will see if I can add that to pull request.

**Comment by richard67** [comment]
@BrainforgeUK Then the same applies what I already posted in your other issue: If you've made a PR to solve your own issue, it would help us if you close that issue. Otherwise, if the PR solves only a part of it, then leave the issue open but mention in the PR that it solves only a part.

**Comment by BrainforgeUK** [comment]
Closed the earlier pull request and created a new one #34957

**Comment by alikon** [comment]
please test  #34957
