### ISSUE TITLE
PHP 8.1 deprecations

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#34952]
PHP deprecations for 8.1 has been implemented and this features are planed to be removed in 9.0

https://wiki.php.net/rfc/deprecations_php_8_1

Special attention should go to the removal of  `strftime`

If this is relevant for 3.x is open for discussion, since 3.10 will be EOL before php 8.0 is EOL and at this point of time all Joomla Installation should be upgraded to 4.x (I know that this is more a wish then a fact).

For 4.x series I would say starting with 4.1 it's relevant.

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/34851

**Comment by PhilETaylor** [comment]
Joomal 3.10.1
PHP 8.1-RC2

```

Deprecated: Joomla\Input\Input implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /Users/phil/Sites/Joomla_3.10.1-Stable-Full_Package/libraries/vendor/joomla/input/src/Input.php on line 41

Deprecated: Return type of Joomla\Input\Input::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/phil/Sites/Joomla_3.10.1-Stable-Full_Package/libraries/vendor/joomla/input/src/Input.php on line 170

Deprecated: Joomla\CMS\Input\Input implements the Serializable interface, which is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in /Users/phil/Sites/Joomla_3.10.1-Stable-Full_Package/libraries/src/Input/Input.php on line 31

Deprecated: Return type of Joomla\Registry\Registry::jsonSerialize() should either be compatible with JsonSerializable::jsonSerialize(): mixed, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/phil/Sites/Joomla_3.10.1-Stable-Full_Package/libraries/vendor/joomla/registry/src/Registry.php on line 126

Deprecated: Return type of Joomla\Registry\Registry::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/phil/Sites/Joomla_3.10.1-Stable-Full_Package/libraries/vendor/joomla/registry/src/Registry.php on line 439

Deprecated: Return type of Joomla\Registry\Registry::offsetGet($offset) should either be compatible with ArrayAccess::offsetGet(mixed $offset): mixed, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/phil/Sites/Joomla_3.10.1-Stable-Full_Package/libraries/vendor/joomla/registry/src/Registry.php on line 453

Deprecated: Return type of Joomla\Registry\Registry::offsetSet($offset, $value) should either be compatible with ArrayAccess::offsetSet(mixed $offset, mixed $value): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/phil/Sites/Joomla_3.10.1-Stable-Full_Package/libraries/vendor/joomla/registry/src/Registry.php on line 468

Deprecated: Return type of Joomla\Registry\Registry::offsetUnset($offset) should either be compatible with ArrayAccess::offsetUnset(mixed $offset): void, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/phil/Sites/Joomla_3.10.1-Stable-Full_Package/libraries/vendor/joomla/registry/src/Registry.php on line 482

Deprecated: Return type of Joomla\Registry\Registry::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/phil/Sites/Joomla_3.10.1-Stable-Full_Package/libraries/vendor/joomla/registry/src/Registry.php on line 288

Deprecated: Return type of Joomla\Registry\Registry::count() should either be compatible with Countable::count(): int, or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /Users/phil/Sites/Joomla_3.10.1-Stable-Full_Package/libraries/vendor/joomla/registry/src/Registry.php on line 112

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /Users/phil/Sites/Joomla_3.10.1-Stable-Full_Package/libraries/src/Application/WebApplication.php on line 1256

Deprecated: Automatic conversion of false to array is deprecated in /Users/phil/Sites/Joomla_3.10.1-Stable-Full_Package/libraries/vendor/joomla/uri/src/UriHelper.php on line 50
```

**Comment by Bakual** [comment]
To get rid of `strftime` requires a rewrite of the calendar formfield. The we can drop it. Just needs someone skilled with JS 😄

**Comment by dgrammatiko** [comment]
> Just needs someone skilled with JS

Temporal is also coming to all the browsers in the coming months. This is important because it means that all the browsers, natively, will support almost all calendars. Of course, the project doesn't have to wait till the feature has landed as there's already a polyfill, so, in theory, someone could create a calendar even today. Also FWIW I'm already working on such an implementation for my own projects https://github.com/dgrammatiko/temporal-calendar

**Comment by PhilETaylor** [comment]
34 BC breaking changes in php 8.1 now documented... 

https://github.com/php/php-src/blob/PHP-8.1/UPGRADING#L18-L179

**Comment by PhilETaylor** [comment]
`is_resource` is also going to be an issue for Joomla. https://externals.io/message/116127

**Comment by xillibit** [comment]
`strftime` is set as deprecated in Php 8.1 and will be removed in Php 9.0

On 8.1.0-RC6-DEV with J!4.0.0 i have too an exception : 

`Call to a member function getTag() on null in \joomla-cms-40-dev\libraries\src\WebAsset\AssetItem\LangActiveAssetItem.php (line 46) `

The stack trace : 

`Call to a member function getTag() on null

  at \joomla-cms-40-dev\libraries\src\WebAsset\AssetItem\LangActiveAssetItem.php:46
  at Joomla\CMS\WebAsset\AssetItem\LangActiveAssetItem->__construct('template.active.language', '', array('description' => 'An asset to allow language specific css, eg \'language/[lang-CODE]/[lang-CODE].css\', to use it as a dependency to the active template', 'type' => 'style', 'class' => 'LangActiveAssetItem', 'dependencies' => array('template.active'), 'assetSource' => array('registryFile' => 'templates\\cassiopeia\\joomla.asset.json')), array(), array())
     (\joomla-cms-40-dev\libraries\src\WebAsset\WebAssetRegistry.php:241)
  at Joomla\CMS\WebAsset\WebAssetRegistry->createAsset('template.active.language', '', array('description' => 'An asset to allow language specific css, eg \'language/[lang-CODE]/[lang-CODE].css\', to use it as a dependency to the active template', 'type' => 'style', 'class' => 'LangActiveAssetItem', 'dependencies' => array('template.active'), 'assetSource' => array('registryFile' => 'templates\\cassiopeia\\joomla.asset.json')))
     (\joomla-cms-40-dev\libraries\src\WebAsset\WebAssetRegistry.php:424)
  at Joomla\CMS\WebAsset\WebAssetRegistry->parseRegistryFile('templates\\cassiopeia\\joomla.asset.json')
     (\joomla-cms-40-dev\libraries\src\WebAsset\WebAssetRegistry.php:347)
  at Joomla\CMS\WebAsset\WebAssetRegistry->parseRegistryFiles()
     (\joomla-cms-40-dev\libraries\src\WebAsset\WebAssetRegistry.php:128)
  at Joomla\CMS\WebAsset\WebAssetRegistry->get('style', 'theme.colors_standard')
     (\joomla-cms-40-dev\libraries\src\WebAsset\WebAssetManager.php:257)
  at Joomla\CMS\WebAsset\WebAssetManager->useAsset('style', 'theme.colors_standard')
     (\joomla-cms-40-dev\libraries\src\WebAsset\WebAssetManager.php:225)
  at Joomla\CMS\WebAsset\WebAssetManager->__call('registerandusestyle', array('theme.colors_standard', 'templates/cassiopeia/css/global/colors_standard.css'))
     (\joomla-cms-40-dev\templates\cassiopeia\error.php:38)
  at require('\\joomla-cms-40-dev\\templates\\cassiopeia\\error.php')
     (\joomla-cms-40-dev\libraries\src\Document\HtmlDocument.php:771)
  at Joomla\CMS\Document\HtmlDocument->_loadTemplate('\\joomla-cms-40-dev\\templates/cassiopeia', 'error.php')
     (\joomla-cms-40-dev\libraries\src\Document\HtmlDocument.php:830)
  at Joomla\CMS\Document\HtmlDocument->_fetchTemplate(array('template' => 'cassiopeia', 'directory' => '\\joomla-cms-40-dev\\templates', 'debug' => true, 'csp_nonce' => null, 'templateInherits' => '', 'params' => object(Registry), 'file' => 'error.php'))
     (\joomla-cms-40-dev\libraries\src\Document\HtmlDocument.php:633)
  at Joomla\CMS\Document\HtmlDocument->parse(array('template' => 'cassiopeia', 'directory' => '\\joomla-cms-40-dev\\templates', 'debug' => true, 'csp_nonce' => null, 'templateInherits' => '', 'params' => object(Registry), 'file' => 'error.php'))
     (\joomla-cms-40-dev\libraries\src\Document\HtmlDocument.php:652)
  at Joomla\CMS\Document\HtmlDocument->render(false, array('template' => 'cassiopeia', 'directory' => '\\joomla-cms-40-dev\\templates', 'debug' => true, 'csp_nonce' => null, 'templateInherits' => '', 'params' => object(Registry), 'file' => 'error.php'))
     (\joomla-cms-40-dev\libraries\src\Document\ErrorDocument.php:140)
  at Joomla\CMS\Document\ErrorDocument->render(false, array('template' => 'cassiopeia', 'directory' => '\\joomla-cms-40-dev\\templates', 'debug' => true, 'csp_nonce' => null, 'templateInherits' => '', 'params' => object(Registry), 'file' => 'error.php'))
     (\joomla-cms-40-dev\libraries\src\Error\Renderer\HtmlRenderer.php:77)
  at Joomla\CMS\Error\Renderer\HtmlRenderer->render(object(RuntimeException))
     (\joomla-cms-40-dev\libraries\src\Exception\ExceptionHandler.php:128)
  at Joomla\CMS\Exception\ExceptionHandler::render(object(RuntimeException))
     (\joomla-cms-40-dev\libraries\src\Exception\ExceptionHandler.php:71)
  at Joomla\CMS\Exception\ExceptionHandler::handleException(object(RuntimeException))
     (\joomla-cms-40-dev\libraries\src\Application\CMSApplication.php:311)
  at Joomla\CMS\Application\CMSApplication->execute()
     (\joomla-cms-40-dev\includes\app.php:63)
  at require_once('\\joomla-cms-40-dev\\includes\\app.php')
     (\joomla-cms-40-dev\index.php:32)    `

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/36395

**Comment by PhilETaylor** [comment]
@Bakual @dgrammatiko Please see https://github.com/joomla/joomla-cms/pull/36469 with replacement for `strftime` for calendar (with unit tests)

**Comment by sunnydrake** [comment]
BAD SLOW FIX
Deprecated: Automatic conversion of false to array is deprecated in /libraries/vendor/joomla/uri/src/UriHelper.php on line 50
add line 
                              if ($result===false) $result=array();

Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in libraries/src/Uri/Uri.php on line 143
add line 
			if(is_null($live_site)) $live_site='';<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34952">issues.joomla.org/tracker/joomla-cms/34952</a>.</sub>

**Comment by sunnydrake** [comment]
JOOMLA 3.10
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in  libraries/src/Uri/Uri.php on line 141
replace 
			$live_site = ($uri->isSsl()) ? str_replace('http://', 'https://', (string) $config->get('live_site')) : $config->get('live_site');

database/driver/mysqli.php :254 possible passing param as null
at line  240 add
                if (is_null($text)) return '';
Deprecated: ucfirst(): Passing null to parameter #1 ($string) of type string is deprecated in /libraries/src/MVC/Controller/BaseController.php on line 286
		$class = ucfirst((string)$prefix) . 'Controller' . ucfirst((string)$type);
Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in libraries/src/MVC/Controller/BaseController.php on line 684
		$task = strtolower((string)$task);
Deprecated: preg_split(): Passing null to parameter #3 ($limit) of type int is deprecated in libraries/src/Document/HtmlDocument.php on line 595
		$words = preg_split('# ' . $operators . ' #', $condition, 0, PREG_SPLIT_DELIM_CAPTURE);
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in administrator/modules/mod_menu/menu.php on line 383
			if (!in_array($item->type, array('separator', 'heading', 'container')) && trim((string)$item->link) === '')
BAD FIX need more research 
Deprecated: Constant FILTER_SANITIZE_STRING is deprecated in /administrator/components/com_virtuemart/helpers/vrequest.php on line 144
replace FILTER_SANITIZE_STRING   with FILTER_SANITIZE_FULL_SPECIAL_CHARS in all doc
Deprecated: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in administrator/includes/helper.php on line 31
		$option = strtolower((string)$app->input->get('option'));
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34952">issues.joomla.org/tracker/joomla-cms/34952</a>.</sub>

**Comment by zero-24** [comment]
@sunnydrake please create a dedicated issue with the coresponding versions and stacktraces so the issue can be debugged and fixed thanks.

**Comment by brianteeman** [comment]
Does this need to be kept open?

**Comment by sunnydrake** [comment]
I fixed a lot of bugs for my version with plugins but... have no time for
upload. Sorry
Im from Kyiv Ukraine so im a bit busy with war at the moment, maybe another
time.

**Comment by brianteeman** [comment]
stay safe!!

**Comment by laoneo** [comment]
Please test #37329 as it is a followup of https://github.com/joomla/joomla-cms/pull/36469.

**Comment by laoneo** [comment]
For most of the cases, there are already pull requests open, so I guess we can close this one here then. If you want to keep track of open 8.1 pr's, use the [8.x label](https://github.com/joomla/joomla-cms/pulls?q=is%3Apr+is%3Aopen+label%3A%22PHP+8.x%22).

**Comment by laoneo** [comment]
Please test #37502  which solves the input error.

**Comment by FIDELTORRES** [comment]
sunnydrake espero que estes bien y tambien tu familia.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34952">issues.joomla.org/tracker/joomla-cms/34952</a>.</sub>

**Comment by FIDELTORRES** [comment]
hola buen día, alguien me puede ayudar con este error.
Fatal error: Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in 
trabajo con PHP y SCRIPTCASE desde que migre a PHP 8.1  tengo estos problemas.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34952">issues.joomla.org/tracker/joomla-cms/34952</a>.</sub>
