### ISSUE TITLE
[4] Some Problems in administrator module mod_feed

### ISSUE THREAD

**Issue by MrMusic** [joomla/joomla-cms#34967]
Hi,

I have noticed a few problems with the administrator module mod_feed:

1. The options shown are confusing for 0 and 1 in the xml. One time 0=active, one time 1=active, see screenshot
![mod_feed-options](https://user-images.githubusercontent.com/9802593/127452303-4a8e5ecc-8a36-4e29-9b83-2e2899a93449.jpg)

2. The feed description shown is just 'plain text' with no formatting.

3. If the feed description contains a [form] there is an infinite loop.

Tested with
Joomla 4.0.0 rc5
PHP 7.4

There are no problems in Joomla 3.9.28

Thanks!

**Comment by brianteeman** [comment]
can you share the feed for testing please?

**Comment by MrMusic** [comment]
Test feed url: https://mrmusic63.de/jgtest/?format=feed&type=rss

Small correction: '2. Plain text' was already the same in Joomla 3.9.28

**Comment by Quy** [comment]
#1 appears to be fixed. Please advise if the other issues are still pending. Thanks.

![34967-feed](https://user-images.githubusercontent.com/368084/219721803-9f1db6f0-8008-4c37-a5b0-e67f687d420a.jpg)
