### ISSUE TITLE
[4.0] Menu preset export. Several Warnings in XML afterwards.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#34977]
### Steps to reproduce the issue
- Issue should be fixed before test: https://github.com/joomla/joomla-cms/issues/34964
- Current nightly.
- Activate error reporting in Joomla configuration: `Maximum`
- Go to `Menus > Manage`.
- Set filter on `Administrator` to create a backend menu.
- Click button `New`.
- Enter `Title` and `Unique name`.
- Field `Import a preset`: Select `Preset Alternative Main Menu`.
- `Save & Close`
- Put a tick in front of the new menu to activate button `Download as Preset` and click on button.
- Save XML file.
- Open the exported XML file in an text editor

### Expected result
- No PHP warnings.

### Actual result
First lines of exported file:

```
Warning</b>:  Undefined property: Joomla\CMS\Menu\AdministratorMenuItem::$class in /administrator/components/com_menus/src/View/Menu/XmlView.php on line 137

Warning:  Undefined property: Joomla\CMS\Menu\AdministratorMenuItem::$submenu in /administrator/components/com_menus/src/View/Menu/XmlView.php on line 175

Warning:  foreach() argument must be of type array|object, null given in /administrator/components/com_menus/src/View/Menu/XmlView.php on line 175
```

- PHP 8.0.6 (Linux dd51328 5.4.0-80-generic #   90-Ubuntu SMP Fri Jul 9 22:49:44 UTC 2021 x86_64 )

**Comment by alikon** [comment]
please test #34990
