### ISSUE TITLE
Akeeba Backup - An unhandled Exception has been detected

### ISSUE THREAD

**Issue by 7at1blow** [joomla/joomla-cms#34972]
### Steps to reproduce the issue

I've done three Updates:
1.) Akeeba Backup Core package 8.0.6 > 8.0.8
2.) German 4.0.0-rc4.1 > 4.0.0-rc5.1
3.) J!-Core 4.0.0-rc4 > 4.0.0-rc5

4.) Backend: Click on Components > Akeeba Backup > Manage Backups

### Expected result

Possibility to see and manage the backups.

### Actual result

Can't see the backups, got an error message instead:

"Akeeba Backup - An unhandled Exception has been detected
500 implode(): Argument #1 ($pieces) must be of type array, string given
File &lt;root&gt;/layouts/joomla/form/field/calendar.php Line 107

 The content below this point is for developers and power users.

Joomla 4.0.0-rc5 – PHP 8.0.8 on Linux

Debug information
Exception type: TypeError

..."

### System information (as much as possible)

- Joomla! 4.0.0-rc5 Release Candidate [ Mañana ] 27-July-2021 22:41 GMT
- PHP-Version	8.0.8
- Webserver Apache
- Datenbanktyp mysql

### Additional comments

I've got the same problem in another installation of 4.0.0-rc5.

**Comment by Fedik** [comment]
It has been fixed in #34949 
thanks for report

**Comment by 7at1blow** [comment]
Wow, thanks Fedik for your comment on the other post. I would not have understood that it was the same problem there.
And I'm glad to see that the problem is already fixed.
