### ISSUE TITLE
Reinstall language fails

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#34975]
### Steps to reproduce the issue
Install Danish language. After that try to reinstall language

### Expected result
Reinstallation of the language package
![reinstall](https://user-images.githubusercontent.com/1399437/127519086-63c98e27-675b-43e6-9e67-ff974d566c57.jpg)

### Actual result
<html><body>
<blockquote class="blockquote">The pakke install adapter does not exist.						</blockquote>
													<div>
								

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/Installer/Installer.php:2431
2 | Joomla\CMS\Installer\Installer->loadAdapter() | JROOT/libraries/src/Installer/Installer.php:883
3 | Joomla\CMS\Installer\Installer->setupInstall() | JROOT/libraries/src/Installer/Installer.php:489
4 | Joomla\CMS\Installer\Installer->install() | JROOT/administrator/components/com_installer/src/Model/InstallModel.php:206
5 | Joomla\Component\Installer\Administrator\Model\InstallModel->install() | JROOT/administrator/components/com_installer/src/Controller/InstallController.php:50
6 | Joomla\Component\Installer\Administrator\Controller\InstallController->install() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
8 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
9 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
10 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
11 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
12 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63
13 | require_once() | JROOT/administrator/index.php:32

</div>
</body>
</html>

### System information (as much as possible)
J!4 RC5 - PHP 7.4

### Additional comments
I first installed the danish language pack on an RC4 install. Then updated to RC5. Then I released an updated language pack here: https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-danish/4-0-0-rc5-2 - (Which by the way does not show as an update??) - I tried to reinstall under Extension:language to update the languiage package but got the error.

**Comment by richard67** [comment]
@rbuelund Can you try following:

Change in the XML file of the language pack following code

```
		<server type="collection" priority="1" name="Akkrediterede Joomla oversættelser">
			https://update.joomla.org/language/translationlist_4.xml
		</server>
```
into following:
 
```
		<server type="collection" priority="1" name="Akkrediterede Joomla oversættelser">https://update.joomla.org/language/translationlist_4.xml</server>

```
i.e. remove the line breaks inside the server element.

**Comment by ot2sen** [comment]
Could it be the manifest in the package having 3 mentions of 'sprog' for type, where I probably shouldn´t be translated?
Files section 
folder type="sprog" client="frontend"

**Comment by richard67** [comment]
yes, that also could be a problem

**Comment by rbuelund** [comment]
Ahh hmm.. that is comming from Crowdin - will take a look..

**Comment by rbuelund** [comment]
I cannot remove the line breaks nor can i change the translation of sprog ?? - it is locked in Crowdin !

**Comment by rbuelund** [comment]
That is pretty bad - I do not know where that translation of the word language is comming from in Crowdin !?

**Comment by rbuelund** [comment]
I see now that also the word package has been translated to pakke - i Have not done that!? Is that some kind of machine translation on Crowdin ?

**Comment by rbuelund** [comment]
I have posted this problem on the Joomla translation forum

**Comment by ot2sen** [comment]
Could well be an issue that those hidden and not for translation strings initially were auto-translated before being approved by the osm-admin. So they will either have to change hidden state so we can edit them of manually change these hidden ones to English system strings
