### ISSUE TITLE
[4.0] Unable to add module class suffix

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#34982]
### Steps to reproduce the issue

Try to add the module class suffix to the modules (backend and frontend).

### Expected result

Can add the module class suffix.

### Actual result

Unable to add the module class suffix.

### System information (as much as possible)

Joomla 4

### Additional comments

Missing of:
`$moduleclass_sfx = htmlspecialchars($params->get('moduleclass_sfx'), ENT_COMPAT, 'UTF-8');`

`class="mod-custom custom<?php echo $moduleclass_sfx; ?>`

**Comment by Fedik** [comment]
It exists in module chrome `/layouts/chromes`

https://github.com/joomla/joomla-cms/blob/d55e7fa9ee60a22be8c875f9a79ce8c562cd60ee/layouts/chromes/html5.php#L26

**Comment by richard67** [comment]
Beside that, as far as I remember in J4 the module class suffix is not a suffix anymore which is appended to the class, it is a module class which is added to the class, separated with a space.

**Comment by chmst** [comment]
correct ... the name of the variable needs to be changed.

**Comment by sandewt** [comment]
A closer look, shows that the issue occurs in the position **menu** and not in the position **sitebar-right** for example.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34982">issues.joomla.org/tracker/joomla-cms/34982</a>.</sub>

**Comment by sandewt** [comment]
I have used the module mod_custom.

![34982](https://user-images.githubusercontent.com/9271775/127644383-e63ae6d9-c2d2-40da-9dfa-1577c12bc791.png)

**Comment by brianteeman** [comment]
As already stated by @fedik the suffix is applied by the chrome.

If you look at the template you will see that the menu position has no chrome

`					<jdoc:include type="modules" name="menu" style="none" />
`

So thats the explanation and the solution for you would be to change the style="none" to style="html5" in the templates index.php 

OR

In the module settings change the style from inherited to html5 (or any other chrome that uses the suffux)

![image](https://user-images.githubusercontent.com/1296369/127645160-b1ed6cb2-7d2c-43e1-85fd-bc4f4969cf72.png)

**Comment by richard67** [comment]
@sandewt Is the explanation above sufficient for you? If so, please close this issue. From my point of view it is expected behaviour.

**Comment by sandewt** [comment]
>@sandewt Is the explanation above sufficient for you? If so, please close this issue. From my point of view it is expected behaviour.

Yes

**Comment by sandewt** [comment]
Thanks all

**Comment by brianteeman** [comment]
Just want to repeat that this _expected behaviour_ is for me not a good behaviour and I have brought this up before. From my perspective every default setting in a module should function in every module chrome.

**Comment by sandewt** [comment]
>Just want to repeat that this expected behaviour is for me not a good behaviour...

Indeed, inconsistent behavior creates confusion. In joomla 3 the top position was included.

**Comment by Fedik** [comment]
In joomla 3 it is duplicated if module chrome is used, 
that makes another issue
