### ISSUE TITLE
Serialization of 'SimpleXMLElement' is not allowed

### ISSUE THREAD

**Issue by techfry** [joomla/joomla-cms#34984]
### Steps to reproduce the issue

1. Navigate to System -> Update Sites. (/index.php?option=com_installer&view=updatesites)

2. Click on Rebuild button on the toolbar.

### Expected result

The system should rebuild the update sites, but it is giving error.

### Actual result

An error has occurred.
0 Serialization of 'SimpleXMLElement' is not allowed

**Comment by richard67** [comment]
@techfry Could you provide the system information, like e.g. which Joomla version you've used?

**Comment by techfry** [comment]
Joomla version: ‎4.0.0-rc5

Call stack (First 3 rows)
#	Function	Location
1	()	JROOT/libraries/vendor/joomla/database/src/Monitor/DebugMonitor.php:76
2	serialize()	JROOT/libraries/vendor/joomla/database/src/Monitor/DebugMonitor.php:76
3	Joomla\Database\Monitor\DebugMonitor->startQuery()	JROOT/libraries/vendor/joomla/database/src/DatabaseDriver.php:661<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34984">issues.joomla.org/tracker/joomla-cms/34984</a>.</sub>

**Comment by richard67** [comment]
@techfry Which language packs and 3rd party extensions do you have installed, if any? I've noticed that error before with the Danish language pack, which clearly has a broken manifest, and so rebuilding the update site URL was broken.

**Comment by techfry** [comment]
Language file is default - English (United Kingdom) (eb-GB)

I installed many extensions for checking, then uninstalled all these 3rd party extensions. May be this is causing? Should I re-install Joomla and check again fresh installation?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34984">issues.joomla.org/tracker/joomla-cms/34984</a>.</sub>

**Comment by richard67** [comment]
> I installed many extensions for checking, then uninstalled all these 3rd party extensions. May be this is causing? Should I re-install Joomla and check again fresh installation?

@techfry Well, that could help to find out if some of these extensions has not been removed properly when uninstalling and if that has caused the problem.

**Comment by joomdonation** [comment]
@richard67 @techfry I can re-procedure the issue by enable Debug System in Global configuration, so you do not need to re-install Joomla. We will try to figure out why the issue happens and get it sorted

**Comment by richard67** [comment]
> @richard67 @techfry I can re-procedure the issue by enable Debug System in Global configuration, so you do not need to re-install Joomla. We will try to figure out why the issue happens and get it sorted

@joomdonation Ouch .. I remember now I had observed that, too, and had forgotten about it.

**Comment by brianteeman** [comment]
Confirming the issue

**Comment by joomdonation** [comment]
Should be fixed by https://github.com/joomla/joomla-cms/pull/34985.  Please test. Thanks !
