### ISSUE TITLE
Cassiopeia content vertical alignment is center

### ISSUE THREAD

**Issue by RickR2H** [joomla/joomla-cms#35003]
### Steps to reproduce the issue
Make a clean install and disable all modules. The content will be aliened vertically in the middle of the screen.
![screen shot 2021-07-31 at 14 07 11](https://issues.joomla.org/uploads/1/a824e36399a36687ac968c2bb3807be2.jpg)

### Expected result
The content should be aligned at the top. Also the header has more padding then necessary.
 
### Actual result
See screenshot.

### Additional comments
Due to the PR https://github.com/joomla/joomla-cms/pull/34849 the body now has a height of 100%. That way the grid rows get stretched. If the actual content height is nog filling the 100% height, the content gets centered vertically and other positions get some extra padding.

@drmenzelit please review your PR.

**Comment by sandewt** [comment]
I confirm this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35003">issues.joomla.org/tracker/joomla-cms/35003</a>.</sub>

**Comment by drmenzelit** [comment]
I can confirm... I solved the problem of the footer not staying at the bottom and created a new problem... that is really great...

I could need some help on this, the grid is driving me crazy... @dgrammatiko @hans2103 ... someone else with css super power?

**Comment by RickR2H** [comment]
@drmenzelit
**Option 1** would be to remove the 100vh on the body, add a div with class spacer above the footer. Set the grid-template-rows of the body to auto for all the rows, except for the spacer this one should be 1fr. This pushes the footer down. This is not the cleanest option but works.

**Option 2** is a bit (maybe a lot) more work. place a div around the content and module positions. That way you get 3 divs (header / middle / footer). Then you can use flexbox or grid to push the footer down. The content in the middle div then can be aligned to top.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35003">issues.joomla.org/tracker/joomla-cms/35003</a>.</sub>

**Comment by drmenzelit** [comment]
@RickR2H it seems we had similar thoughts at the same time. Please check PR #35004 
Your option 2 is probably the better way, that is the holy grail layout (https://www.digitalocean.com/community/tutorials/css-css-grid-holy-grail-layout), but Cassiopeia's grid-areas are very complex with other positions like banner, top-a, botton-a, etc.

**Comment by drmenzelit** [comment]
Closing as we have a PR.
Please feel free to re-open if not solved or to create a different PR.
