### ISSUE TITLE
Joomla 4 RC 5 - Back Buttons missing in Installer

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#35007]
### What needs to be fixed
If you realize during installation that you made a mistake in the informations given before (for example your decision for the admin email, there is no way back.

### Why this should be fixed
It improves the User Experience

### How would you fix it
Back Button and Step indicators.

### Side Effects expected
no

**Comment by Quy** [comment]
Related #24556

**Comment by seomarketercomau** [comment]
I'm also having the same issue encountered that I want to incorporate [here](https://seomarketer.com.au/ "SEO Marketer"). <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35007">issues.joomla.org/tracker/joomla-cms/35007</a>.</sub>

**Comment by brianteeman** [comment]
Please delete the spam

**Comment by harshraj1311** [comment]
Can I work on this issue?

**Comment by coolcat-creations** [comment]
@harshraj1311 I would very welcome it :)

**Comment by Quy** [comment]
Closing as duplicate of #24556.
