### ISSUE TITLE
[4.0] Should our backend template support style for chosen like frontend template?

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#35006]
### Is your feature request related to a problem? Please describe.
For extensions which support both Joomla 3 and Joomla 4, it might still use chosen `HTMLHelper::_('formbehavior.chosen', 'select');` for select dropdown.

However, the style for chosen dropdown looks much different with the standard select dropdown in our backend template. See the screenshots below:

- With chosen loaded
![with-chosen-loaded](https://user-images.githubusercontent.com/977664/127746975-d463f6d6-329f-4570-b361-3c288d2666dd.png)

- Without chosen
![without-chosen-loaded](https://user-images.githubusercontent.com/977664/127746984-88338fca-a7ee-40f0-afc2-a4ad81f658e4.png)

### Describe the solution you'd like
The backend template has style support for chosen like in our frontend template so that the style of select tag looks the same for standard select and select with chosen loaded. That would make the layout looks consistent, especially for third party extensions still support both Joomla 3 and Joomla 4.

We have css code for frontend template already, so it should be easy to port it for our backend template.

**Comment by brianteeman** [comment]
We've had to support a dead script for five years. Please no more.

**Comment by joomdonation** [comment]
Hmm, OK. I thought it could be useful for us when we still have to support both Joomla 3 and Joomla 4 for our extensions, especially when I saw it is supported in the frontend template https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/vendor/_chosen.scss
