### ISSUE TITLE
Joomla 4 RC 5 - Progress indicator missing in extension installer

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#35008]
### What needs to be fixed
When installing an extension in Joomla there is no visual feedback from the website that something is happening at all

### Why this should be fixed
to improve user experience

### How would you fix it
Adding at least the Joomla logo animation like in J3

### Side Effects expected
no

**Comment by brianteeman** [comment]
that looks like a recent bug then as the animation definitely used to be there

**Comment by brianteeman** [comment]
Did you see an empty white box when you were installing the extension?

![image](https://user-images.githubusercontent.com/1296369/127768884-34e1fa1e-714d-48ed-8f40-549518c1d3d1.png)

**Comment by coolcat-creations** [comment]
I did not see it, I  now repeated the installation and I see the empty box from your screenshot

**Comment by brianteeman** [comment]
If I was to guess then I would say there is an issue after the joomla-tabs js was changed recently. But debugging js is almost impossible for me

**Comment by brianteeman** [comment]
This has beeen resolved with #37538
