### ISSUE TITLE
[4.0] Installed library appears in Extensions:Discover listing

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#35015]
### Steps to reproduce the issue

Install library:
[lib_bftest1.zip](https://github.com/joomla/joomla-cms/files/6913355/lib_bftest1.zip)

### Expected result

Library installed, does not appear in Extensions:Discover listing

### Actual result

Appears in Extensions:Discover listing and can be installed again from there.
End up with 2 records for the same library in the extensions table!

### System information (as much as possible)

Windows 10
PHP 7.4

### Additional comments

Found problem while using solution to issue #34910
May only be an issue in MS Windows environments, not Linux.

In com_installer/src/Model/DiscoverModel.php function discover() one key has a forward slash (/), the other a backward slash (\) hence the array_key_exists() function returns false instead of true.

Have solution for which I will submit a pull request shortly.

**Comment by brianteeman** [comment]
Are you sure its nothing to with the library name?

**Comment by BrainforgeUK** [comment]
The library name is:
&lt;libraryname&gt;brainforgeuk/test1&lt;/libraryname&gt;

i.e. mycompany/mylibrary as in issue #34910 referred to.

Using \ instead of / does not make sense and would cause more confusion - and could such packages be installed on Linux hosts?

**Comment by richard67** [comment]
The library name should neither contain a slash nor a backslash, I think. You should not try to use the library name to make up a subfolder structure.

**Comment by richard67** [comment]
And if you have a PR to solve your issue (regardless if it’s right or wrong) then please close your issue.

**Comment by richard67** [comment]
Closing as having a pull request.
