### ISSUE TITLE
[4.0] form field note with close="true" doesn't close

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#35016]
### Steps to reproduce the issue
- Edit `templates\cassiopeia\templateDetails.xml`
- Line 104 add a `close="true"` in `note` field
```
<field
	name="noteFontScheme"
	type="note"
	close="true"
	description="TPL_CASSIOPEIA_FONT_NOTE_TEXT"
	class="alert alert-warning"
/>
```
- Go to `administrator/index.php?option=com_templates&view=styles`
- Open `Cassiopeia`
- Check alert below field `Fonts Scheme`
- It has a close button but that doesn't close the alert.
- And (I don't care): The close `X` should be right aligned. And it has 2 `x` (1 is a svg background).
- I see the same behaviour in many custom extension settings in the backend where it works without issues in Joomla 3.

```
<div class="alert alert-warning">
<button type="button" class="btn-close" data-dismiss="alert">×</button>
Some text.
</div>
```

![01-08-_2021_22-17-19](https://user-images.githubusercontent.com/20780646/127784506-777841aa-b308-4f64-85c5-ef92101c8246.jpg)

### Additional comments
- No JS errors.
- I tried a lot, using `data-bs-dismiss` instead of `data-dismiss`, added `alert-dismissible show` classes, forced BS loading. No success.

**Comment by Fedik** [comment]
`close="true"` does it ever worked? :)

As I see it does not have any js connected

**Comment by Fedik** [comment]
okay, it probably missing `HTMLHelper::_('bootstrap.alert')`

**Comment by ChristineWk** [comment]
Confirmed. Made the steps above. It's after line 106 [4.0.0-rc6-dev]
![screen shot 2021-08-01 at 21 37 04](https://issues.joomla.org/uploads/1/d52a65b98c6e4daa84d4a41551667bc7.jpg)
There is a small x and a big X

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35016">issues.joomla.org/tracker/joomla-cms/35016</a>.</sub>

**Comment by ReLater** [comment]
Will write a pr.

**Comment by ReLater** [comment]
Test https://github.com/joomla/joomla-cms/pull/35017 please
