### ISSUE TITLE
[4.0] Custom field media - images with space are not displayed

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#35036]
### Steps to reproduce the issue
Make a custom field of type media for articles
Have image with a name like "water 1.jpg"  with a space
Make a new article and select this image into the field.

### Expected result
The image is displayed in the frontend

### Actual result
The image is not displayed.

### Note
Now rename the image to water1.jpg and repeat, the image is displayed. 

The raw value is:
 [rawvalue] => {"imagefile":"images\/bilder\/water%201.jpg#joomlaImage:\/\/local-images\/bilder\/water 1.jpg?width=425&height=319","alt_text":"ggz"}

See the space in the image name.

### Additional comments
working on win10, xampp. php 7.4

**Comment by brianteeman** [comment]
confirmed at a guess its from #33724 and the space needs to be converted to an entity in both places not just the first

**Comment by brianteeman** [comment]
Please test #35038 My guess was wrong

**Comment by richard67** [comment]
Closing as having a pull request. Please test #35038 . Thanks in advance.
