### ISSUE TITLE
[4.0] com_contact.contact. Empty params (null) in onContentPrepare of a plugin.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#35044]
- In a system plugin I have method `public function onContentPrepare($context, &$article, $params, $page = 0)`.
- In a `com_contact.contact` page view (frontend) the received `$params` are empty (null) which throws a fatal error when I use `$params->get()`.
- Plugin runs on J3 without issues.
- I think `$this->params` in this line is wrong: https://github.com/joomla/joomla-cms/blob/4.0-dev/components/com_contact/src/View/Contact/HtmlView.php#L349
- and should be `$item->params`: like this:
- `$app->triggerEvent('onContentPrepare', array ('com_contact.contact', &$item, &$item->params, $offset));`

- `$item->params` is filled step by step before the line, not `$this->params`
- Compare also with Joomla 3:
https://github.com/joomla/joomla-cms/blob/staging/components/com_contact/views/contact/view.html.php#L306

**Comment by wilsonge** [comment]
Yup. I agree. As you say $item->params is created on https://github.com/joomla/joomla-cms/blob/4.0-dev/components/com_contact/src/View/Contact/HtmlView.php#L383 after we call this. You happy to do a PR?

**Comment by ReLater** [comment]
Not happy but will do ;-)

**Comment by ReLater** [comment]
Please test https://github.com/joomla/joomla-cms/pull/35045
