### ISSUE TITLE
J4 not working switch RECORD HITS

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#35043]
![image](https://user-images.githubusercontent.com/6898474/128238875-fd884b74-a53b-46c5-b020-ace4ce5abfe4.png)
![image](https://user-images.githubusercontent.com/6898474/128239158-cb814349-0f5c-4a70-9f92-4341000ac344.png)

In the Article settings. The RECORD HITS field is disabled.
But this value is displayed on the site.
The fact is that the disabled RECORD HITS field hides another HITS field.
I believe that it should be like this:
- Either the RECORD HITS field will not hide the HITS field.
- Either disabling the RECORD HITS field will automatically deactivate the HITS field.
![image](https://user-images.githubusercontent.com/6898474/128240189-14b98eb6-6467-415b-af7b-5524bbf04d38.png)

**Comment by ChristineWk** [comment]
> In the Article settings. The RECORD HITS field is disabled.
> But this value is displayed on the site.

It's not displayed in Frontend.

You can set RECORD HITS to Yes and HITS to No. also.

#34211

**Comment by korenevskiy** [comment]
> 
> > In the Article settings. The RECORD HITS field is disabled.
> > But this value is displayed on the site.
> 
> It's not displayed in Frontend.
> 
> You can set RECORD HITS to Yes and HITS to No. also.
> 
> #34211

there are no questions about what you wrote in the article.
The error is when RECORD HITS disabled and HITS enabled is selected.
At the same time, the HITS checkbox is hidden , which means it should also not work.
If RECORDS HITS operates on the principle of disable HITS at all on the site. Then why show hits?

**Comment by brianteeman** [comment]
In this case the showon in the xml is the problem and should be removed so that you can have any combination of show and record hits

**Comment by korenevskiy** [comment]
> In this case the showon in the xml is the problem and should be removed so that you can have any combination of show and record hits

I'm deactivating RECORDS HITS. Then I look at the client's website. And at a loss that the Hits are shown.
After that, I go to the settings, look and see that the hits are turned off. I can't find the setting where hits are enabled at all. Since all visible settings are disabled. But the hits are still being shown.
User experience shows that when you turn off Hits, hits will be shown on the client, this means that the second switch should not disappear, since its function continues to work, and it is no longer visible, hidden.

**Comment by brianteeman** [comment]
Sorry I guess my reply was lost in translation. I agree with you and the way to do it is to change the xml file and delete the line with showon. Will you do a PR

**Comment by korenevskiy** [comment]
> Sorry I guess my reply was lost in translation. I agree with you and the way to do it is to change the xml file and delete the line with showon. Will you do a PR

https://github.com/joomla/joomla-cms/pull/35154

**Comment by richard67** [comment]
Closing as having a pull request.

@korenevskiy Please when you have created an issue and later make a PR to solve the issue, then close the issue. We have enough open issues which might be already solved or are duplicates because of such things. Thanks in advance.
