### ISSUE TITLE
J4 RC5 Editor Layout broken after disabling and enabling 

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#35042]
### Steps to reproduce the issue
Click into Articles  and create a new Article, write some text and switch the editor off and then on again.
![grafik](https://user-images.githubusercontent.com/828371/128170154-73fc5471-ed55-40c1-bbfa-531168e160f6.png)

Result:
![grafik](https://user-images.githubusercontent.com/828371/128170132-d49da627-ccef-470d-b62b-0844520af3a6.png)

### Expected result

![grafik](https://user-images.githubusercontent.com/828371/128170186-2d9f2eb3-4ae3-4619-b83b-fec87f1462fb.png)

### System information (as much as possible)

Joomla 4 RC5

**Comment by brianteeman** [comment]
unable to replicate

**Comment by ChristineWk** [comment]
Hi Elisa,

I also can see this wondrous appearance from time to time. But it's not always. It belongs to browser sidebar, when scrolling. Clear the browser cache :-) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35042">issues.joomla.org/tracker/joomla-cms/35042</a>.</sub>

![pr35042](https://user-images.githubusercontent.com/15275917/128182746-e2757fc5-5956-4f43-873d-a7a8e045ba7e.jpg)

@brianteeman Try to Click several times the Toggle Editor button and scroll with the sidebar. Just replicate it again.

**Comment by dgrammatiko** [comment]
> Click into Articles and create a new Article, write some text and switch the editor off and then on again.

What browser?
Can you give the exact steps for replication?

**Comment by coolcat-creations** [comment]
I made here a screen capture:
https://vimeo.com/582962406/d7c162bf2c

I am using Firefox Developer Edition Version  91.0b9

**Comment by dgrammatiko** [comment]
I just figure out that this was a Firefox bug as Chrome and Safari are totally fine. For whatever reason Firefox is not rendering correctly the sticky menu and toolbar of tinyMCE. Probably create issues in tinyMCE's and Firefox repos


FWIW I can't replicate it with their nightly https://www.mozilla.org/en-US/firefox/channel/desktop/

**Comment by coolcat-creations** [comment]
I confirm it works in chrome

**Comment by wilsonge** [comment]
We're on the latest version of tinymce. So I really doubt unless something comes from upstream that we'll see a fix on this to be honest.

**Comment by dgrammatiko** [comment]
@wilsonge according to https://wiki.mozilla.org/Release_Management/Calendar the next version of FF is on 10th Aug `2021-08-10` and I already confirmed that their nightly has solved the issue. So nothing to be done here, the issue will be resolved before the GA

**Comment by coolcat-creations** [comment]
Then I close the issue ;-)
