### ISSUE TITLE
J4 RC5 - Hide in Subform Fields Setting cannot be reversed

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#35041]
### Steps to reproduce the issue
Create a new Field, Set first  "Only Use In Subform"  to yes.

<img width="418" alt="grafik" src="https://user-images.githubusercontent.com/828371/128154614-268e1749-02a6-4ef6-83e4-5de44f5bb971.png">

Then Select the Fieldtype Subform and save

<img width="1062" alt="grafik" src="https://user-images.githubusercontent.com/828371/128155238-514c9959-e2c4-4e6e-a92d-8385fb785e67.png">

### Expected result
The setting subform only must be ignored in subform to prevent user errors. Specially for beginners it might be a setting they confuse. 

### Actual result
Subform is set to be only used in subforms and cannot be reversed/fixed.

### System information (as much as possible)
Joomla 4 RC%

**Comment by brianteeman** [comment]
I think the problem you are describing is that you are setting an option before you set the field type? Is that correct

**Comment by coolcat-creations** [comment]
Yes exactly, that happened to a kid from the Joomla class and I think this behaviour could be improved.

**Comment by brianteeman** [comment]
that behaviour happens on many fields and also happens on most menu types

**Comment by coolcat-creations** [comment]
The issue is, that on the other fields it can be set to visible again, in subform not. The setting is gone.

**Comment by AndySDH** [comment]
Yeah, so I think the fix would be forcing that setting to "0" (false) upon saving or editing a Subform field.

**Comment by Quy** [comment]
@coolcat-creations Followed your instructions and got the following. Please confirm if this is still an issue.

> You need to create standard fields before creating a Subform field.

**Comment by coolcat-creations** [comment]
Yes that issue is solved, thank you :)
