### ISSUE TITLE
[4.0 RC5] Images will not insert into Articles.

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#35054]
### Steps to reproduce the issue
A.png image was loaded into the Media Manager.
Attempted to add image to an Article via all default methods.  The only insertion action that will take one to the Media Manager to select the image is via the CMS options.  Adding an image, or using the image icon, takes the admin to an insertion window, but no way to get to the content in the Media Manager.  There is also no way to upload an image via any method other than being "in" the Media Manager.  No other way is functional.
Finally, when in the Media Manager and an images is selected for insertion, it will not insert at any ad hoc location, nor as the "Article" images choices.

### Expected result
All actions to insert images should have a pathway to the Media Manager to select images.

### Actual result
Nearly a fully disfunction feature.

### System information (as much as possible)
Using latest version of the Chrome browser on Windows 10.

### Additional comments
This inability to add images is shocking and makes one wonder if it is actually a global issue that was/is overlooked.

**Comment by 200MPHMEDIA** [comment]
Have verified that the same lack of image insertion ability occurs in FireFox on the same computer.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35054">issues.joomla.org/tracker/joomla-cms/35054</a>.</sub>

**Comment by brianteeman** [comment]
Unable to replicate

**Comment by brianteeman** [comment]
Please post some screenshots or even better do a screen recording

**Comment by 200MPHMEDIA** [comment]
Any screen shots or recordings would show nothing.  In other words, clicking all the buttons results in NO RESULTS.
We have tested this with the JCE Editor and images are installable, etc. etc.
Will put this on the back burner until RC6 or Stable is released to determine if it is OUR problem or EVERYONE'S problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35054">issues.joomla.org/tracker/joomla-cms/35054</a>.</sub>

**Comment by brianteeman** [comment]
Think about it. Such a major feature of Joomla not working surely would have been noticed and reported by a LOT of people.

@richard67 as the op wont provide more information as requested I suggest this is closed

**Comment by 200MPHMEDIA** [comment]
Understand that it would look that way from your lofty point of observation, but WT heck is causing a local issue with the media manager not connecting to the articles?  But, if no one else is complaining, I should just go back to my tasks and wait for any updates to see if the patient is dead or cured.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35054">issues.joomla.org/tracker/joomla-cms/35054</a>.</sub>

**Comment by brianteeman** [comment]
as you wont provide ore information no one can help you

**Comment by dgrammatiko** [comment]
@200MPHMEDIA is your testing Joomla installation a clean install of the latest nightly?

If not delete your installation download the latest nightly and then report if the problem exists or just close the issue

**Comment by ChristineWk** [comment]
> 
> We have tested this with the JCE Editor and images are installable, etc. etc.

That’s not enough information. Do you have the latest version?
https://www.joomlacontenteditor.net/support/forum/108409-cannot-add-images-since-jce-pro-2-9-10-update

Same effect with TinyMCE? 

> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/35054](https://issues.joomla.org/tracker/joomla-cms/35054).

**Comment by brianteeman** [comment]
Please close<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35054">issues.joomla.org/tracker/joomla-cms/35054</a>.</sub>

**Comment by richard67** [comment]
I tend to do that but we should wait and give the author more time to react.

**Comment by brianteeman** [comment]
They have already said they wont be
