### ISSUE TITLE
[4.0] Misleading button state when updating Joomla

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#35055]
### Steps to reproduce the issue

When attempting to update from RC4 to RC5, the "Start Update" button appears to be clickable, despite the checkbox above not being checked.

I have no 3rd party extensions installed and this is a local instance and don't require a backup, therefore didn't check the checkbox.

If this checkbox is required to be checked before the "Start update" button actually does anything, can I suggest disabling the button or changing the checkbox text.

### Screenshot

![Screenshot 2021-08-06 at 06-51-23 Upload Update - BCS Gaming - Administration](https://user-images.githubusercontent.com/2019801/128462734-07879c19-bf10-4512-b019-7b88a0806ed1.png)

**Comment by richard67** [comment]
Ping @bembelimen ... Could you have a look on that?

**Comment by brianteeman** [comment]
I never get that screen ?

![image](https://user-images.githubusercontent.com/1296369/128997993-4c3e1ab7-3634-4a15-b1df-456435a3c536.png)

**Comment by richard67** [comment]
I think you only get it if not all checks are green, e.g. if some extensions have unknown compatibility status. But I hope @bembelimen can confirm or correct me.

**Comment by C-Lodder** [comment]
I think you're right @richard67.
One of the 3rd party extensions I'm using was flagged.

@brianteeman you can probably replicate by disabling one of the recommended PHP/server settings

**Comment by brianteeman** [comment]
I tried that and it didnt change the button

**Comment by zero-24** [comment]
@brianteeman the site you did the screenshot on was a rc5 or rc6?

**Comment by brianteeman** [comment]
‎4.0.0-rc6-dev

**Comment by zero-24** [comment]
Ah sorry I got confused with a different message.

**Comment by C-Lodder** [comment]
Must have been fixed in RC5 as I no longer see this.
Closing

**Comment by brianteeman** [comment]
You can re-open this. I got the screen AFTER clicking on update on the screen I posted before

**Comment by brianteeman** [comment]
Should be resolved with #36860

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36860 . Thanks in advance.
