### ISSUE TITLE
No 'Pre-Update Check' tab

### ISSUE THREAD

**Issue by Maddexi** [joomla/joomla-cms#35059]
There is no tab with the 'Pre-Update Check' in Joomla Update after selecting 'Joomla Next' from the drop-down for Update Channel.

### Steps to reproduce the issue
Install a fresh Joomla 3.9.28-site, upgrade to Joomla 3.10.0 Alpha 5 (joomla_3.10.0-alpha5-alpha-full_package.zip) and select 'Joomla Next' from the drop-down for Update Channel in Joomla Update Options.

### Expected result
A 'Pre-Update Check' tab where Joomla will show you the requirements for Joomla 4.

### Actual result
No 'Pre-Update Check' tab.

### System information (as much as possible)
PHP Built On: Linux
Database Type: mysql
Database Version	5.5.5-10.3.30-MariaDB-cll-lve
Database Collation	utf8mb4_unicode_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version: 7.4.22
Web Server: LiteSpeed
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 3.10.0-alpha5 Alpha [ Amani ] 2-February-2021 19:01 GMT
Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: Mac
Chrome/92.0.4515.107 Safari/537.36

**Comment by zero-24** [comment]
Yes this is expected for now as Joomla 4 has not been published yet. Please use this update server as custom update server for testing until 4.0.0 stable is out: `https://update.joomla.org/core/test/310to4_list.xml`

**Comment by Maddexi** [comment]
Ok, thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35059">issues.joomla.org/tracker/joomla-cms/35059</a>.</sub>

**Comment by brianteeman** [comment]
Please close<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35059">issues.joomla.org/tracker/joomla-cms/35059</a>.</sub>
