### ISSUE TITLE
J4 Feature request Search Index Option to find Word parts

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#35051]
### Is your feature request related to a problem? Please describe.
In German there are many words that are build by two words. 
For example "Zahnarzt" is the Word for Tooth Doctor - literally translated.
In Search Index you would not find Zahnarzt if you seach for tooth (Zahn) and you would not find it when you search for doctor (Arzt)

But putting in the whole Word "Zahnarzt" would be very uncommon when I look for any doctor. I would just type in "Arzt"

Same now with the Kids Joomla Class. One of the Kids created a Website and has a Page about "Holzdübel" -> Wooden dowels

If you search for Holz, there is no result. If you search für Dübel, there is no result either. The visitor must guess how the word is exactly written and that makes the search really useless.

com_search in Joomla 3 had the ability to find part of word.

### Describe the solution you'd like
I understand that this has performance impacts but I deeply wish a switcher to turn on finding parts of words too.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/32236

**Comment by coolcat-creations** [comment]
Its only partly related to "Stemmer" @brianteeman as my issue really also about part of wordy and not only about official dictonary word.
Lets say someone has a software named SuperJoo - I want to find it also by typing "Joo"

**Comment by brianteeman** [comment]
its all a mystery to me, crazy decision to switch to finder only as its useless at this sort of real world search.

**Comment by coolcat-creations** [comment]
Actually for specially two customers I would not be able to upgrade to J4 because of this - or I would need a custom made search component which has the ability to search for word parts. The search is an important part of their site, and currently they use com_search because com_finder has not the ability for statistics in J3, now in J4 it has the ability for statistics but does not find anything...

**Comment by Elfangor93** [comment]
> In Search Index you would not find Zahnarzt if you seach for tooth (Zahn) and you would not find it when you search for doctor (Arzt)
But putting in the whole Word "Zahnarzt" would be very uncommon when I look for any doctor. I would just type in "Arzt"

I can confirm this behaviour and have already reported it in [#32186](https://github.com/joomla/joomla-cms/issues/32186). Is there any hope that this will be fixed in the future? As mentioned by @coolcat-creations a working search is very crucial for large websites...

**Comment by alikon** [comment]
let's continue on ##32236
