### ISSUE TITLE
[4.0 RC5] Cannot Uninstall Component Add-In Module in Admin

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#35053]
### Steps to reproduce the issue
Have created a new Module in Admin to show all Components.
If you recall, a "Components" Module was previously part of the back end as an alternative way of accessing them when the left sidebar menu was minimized.
Once added, this Component Module "looks" and operates terribly and cannot be uninstalled or deleted.

### Expected result
Some method to modify the layout and/or remove or delete it from the Admin area.

### Actual result
No such controls or removal process available.

### System information (as much as possible)
Joomla! 4, RC5

### Additional comments
Why isn't there a default block in Admin that lists the Components and allows access via that Module vs. exclusively by the left menu?

**Comment by 200MPHMEDIA** [comment]
There is a convoluted "Trash" method to remove, but this entire feature needs a full look-see and updating so that a simple block of COMPONENTS be shown in the same style as the rest of the Admin Panels.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35053">issues.joomla.org/tracker/joomla-cms/35053</a>.</sub>

**Comment by brianteeman** [comment]
From the information provided it is impossible to tell. I have no memory of any module that displayed a list of all components.

**Comment by chmst** [comment]
You have written a module yourself.  So it will be you responsibility to adapt it to J4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35053">issues.joomla.org/tracker/joomla-cms/35053</a>.</sub>

**Comment by 200MPHMEDIA** [comment]
In early versions, they used to be a block on the Home Dashboard that listed the Components that were installed and when a new one was added, it appeared in the block and was accessible there w/o using the left menu.  What happened to it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35053">issues.joomla.org/tracker/joomla-cms/35053</a>.</sub>

**Comment by brianteeman** [comment]
There has never been such a "block"

**Comment by 200MPHMEDIA** [comment]
Well, then let's call "it" what "it" is ... 3rd Party Block.  After we installed JCE, a "3rd Party Block" has magically appeared, and seeing the JCE Editor IS a component, I guess I am totally wrong in assuming it that does exist.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35053">issues.joomla.org/tracker/joomla-cms/35053</a>.</sub>

**Comment by brianteeman** [comment]
So thats not displaying all components which is what you said. This is a quickicon created by JCE. If any component provides a quickicon then it will be displayed in the "3rd party block". If a component doesnt provide a quickicon it will not be displayed in this block. This display of an extension provided quickicon is not new to j3 but it is now more prominently displayed.

To completely remove that block click on the cog icon and unpublish it
![image](https://user-images.githubusercontent.com/1296369/128394679-157366b5-8f0e-4adb-bd75-6a57263c19ee.png)

If you have multiple components displayed in that block and you only want to remove the jce one then go to plugins and siable the JCE quickicon plugin

![image](https://user-images.githubusercontent.com/1296369/128394844-f167a73e-f389-4ecb-b52d-d24fc6d30e9a.png)

**Comment by 200MPHMEDIA** [comment]
OK, now at least we have a rational answer to the issue and how the "3rd Party" Component block works.  Sure would like to see that explained on one of the "Help" screens for Joomla! 4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35053">issues.joomla.org/tracker/joomla-cms/35053</a>.</sub>

**Comment by brianteeman** [comment]
It always helps when you describe the problem correctly in the first place. That is why posting screenshots helps.

As I said component supplied quickicons are not new - you have them in your joomla 3 site as well.

**Comment by 200MPHMEDIA** [comment]
RE: Sentence two = I know, which is why I questioned them missing in J!4. 
Given that, what are the "Administrative Dashboard Menu" with the "Presets-Components Dashboard" going to display, and "how" will it display, because when we activate it, the appearance is wonky.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35053">issues.joomla.org/tracker/joomla-cms/35053</a>.</sub>

**Comment by brianteeman** [comment]
Wonky is not a technical term and its impossible to guess EXACTLY what you mean. Please post a screenshot

**Comment by brianteeman** [comment]
This should be closed

**Comment by brianteeman** [comment]
Still should be closed
