### ISSUE TITLE
J4 Cassiopeia - To Top button overlaps information

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#35057]
### What needs to be fixed
When the to-top button in cassiopeia is activated it could happen that it overlaps a footer module / link or whatever:
<img width="173" alt="grafik" src="https://user-images.githubusercontent.com/828371/128492667-8fbb3cb4-50b1-4290-b5a1-38292d2cdb74.png">

### Why this should be fixed
There is not really a good workaround, than maybe changing the fixed position to another value so I would suggest that the to top button can also "exist" without being fixed. Means, when I disable the absolute positioning the button should flow into the footer.

### How would you fix it
maybe with a backend parameter switch fixed position or footer position

**Comment by dgrammatiko** [comment]
The `back to the top` is really a stupid thing from the past: Users **CAN** and **WILL** scroll. Scrolling is the default behaviour of the webpages. There's no need for such button...

My 2c

**Comment by brianteeman** [comment]
That's why its an option and not enabled by default

**Comment by richard67** [comment]
Closing as having a pull request. Please test #35996 . Thanks in advance.
