### ISSUE TITLE
Some pdf files don't upload

### ISSUE THREAD

**Issue by robbiejackson** [joomla/joomla-cms#35060]
### Steps to reproduce the issue

Go into Media and click to upload a file, eg: [doh-2021-covid-regs-amdt13.pdf](https://issues.joomla.org/uploads/1/2d99a5171059ce4e86007b1e57237f1e.pdf)

When you try to upload the attached file (from https://www.health-ni.gov.uk/publications/health-protection-coronavirus-restrictions-regulations-northern-ireland-2021) then joomla gives a 403 response.

Some pdf files upload ok, others don't. I can't see what the difference is between those that upload ok and those that fail.

### Expected result

pdf file is uploaded

### Actual result

upload is rejected with a 403 status

### System information (as much as possible)

Joomla 3.9.28 on a hosted service provided by Krystal Hosting.

### Additional comments

The upload of the above file works ok on my joomla 3.9.14 instance on my windows pc.

**Comment by brianteeman** [comment]
Please see #16238 

(note it works fine on my sites with scalahosting)

**Comment by robbiejackson** [comment]
@brianteeman thanks for that - I think you're right. I updated my local instance to 3.9.28 and it works there ok.

I'll look into the issue a bit more on the hosting side to try and find the root of the problem. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35060">issues.joomla.org/tracker/joomla-cms/35060</a>.</sub>

**Comment by robbiejackson** [comment]
@brianteeman - it wasn't a joomla problem after all, but some security rules on the hosting service that had got a bit overzealous, and which the hosting company has now fixed.

Actually I should have realised it wasn't joomla because it was showing the 403 error on a page which referenced the LiteSpeed web server, so the requests weren't actually making it through to joomla, but were being rejected at the web server.

Hence I'm closing this ticket - apologies for the false alarm. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35060">issues.joomla.org/tracker/joomla-cms/35060</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for reporting back.
