### ISSUE TITLE
[3.9] Parent link selection is reset after selecting a menu type

### ISSUE THREAD

**Issue by SemaphoreOxalis** [joomla/joomla-cms#35078]
### Steps to reproduce the issue
- Create a new menu link
- Select a new parent for the link
- Select any type of menu link
- The menu link parent is rest

### Expected result
The previously link parent selected stay selected

### Actual result
 The menu link parent is reset

### System information (as much as possible)
J3.9.28
Fresh install
Ext : Akeeba/RSForms/Regular labs sliders/JCE

### Additional comments
I know it works like that from ages but can we moveon that (don't have tested on J!4)

**Comment by chmst** [comment]
Duplicate: https://github.com/joomla/joomla-cms/issues/22150 same in J4
