### ISSUE TITLE
[4.0] Image edit page throws a Javascript error with new edit plugins

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#35075]
### Steps to reproduce the issue
I have a custom edit plugin and then the image edit page throws the following error:

Uncaught (in promise) TypeError: this.plugins[plugin] is undefined
    initPluginFn http://localhost/j4/media/com_media/js/edit-images.js?59ef01f967593c6adca2aa614d150ed2:87
    Edit http://localhost/j4/media/com_media/js/edit-images.js?59ef01f967593c6adca2aa614d150ed2:90
    Edit http://localhost/j4/media/com_media/js/edit-images.js?59ef01f967593c6adca2aa614d150ed2:90
    promise callback*Edit http://localhost/j4/media/com_media/js/edit-images.js?59ef01f967593c6adca2aa614d150ed2:42
    <anonymous> http://localhost/j4/media/com_media/js/edit-images.js?59ef01f967593c6adca2aa614d150ed2:288

**Comment by dgrammatiko** [comment]
What's your initialization code?
Did you update your plugins to use the initialize event: https://github.com/joomla/joomla-cms/pull/34885

**Comment by laoneo** [comment]
Yes I did.

**Comment by laoneo** [comment]
Error on my end.
