### ISSUE TITLE
[4.0] Mail template API fails creating mail templates

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#35071]
### Steps to reproduce the issue

Use the new Mail Template API to create a mail template (using MailTemplate::createTemplate())

### Expected result

New entry in the mail_templates table.

### Actual result

Error: Field 'attachments' doesn't have a default value

### System information (as much as possible)

Joomla 4 RC5 MySQL 5.7.14

### Additional comments

It looks like the API does not take into account the attachments database column.
Since there is no way to add an attachment or a default value in createTemplate(), inserting a template in the database fails.
The database table should have a default value for the 'attachments' column in this case, since attachments are omitted.

**Comment by richard67** [comment]
> The database table should have a default value for the 'attachments' column in this case

@obuisard No, this is wrong. As a column with data type TEXT, it should not have a default value, see PR #27937 and PR #17860 and also https://stackoverflow.com/questions/3466872/why-cant-a-text-column-have-a-default-value-in-mysql for the reasons. Insteasd of this, the API should properly initialize that column value and use it in the insert statement.

**Comment by richard67** [comment]
@obuisard Please report back which version of Joomla 4 you have used, e.g. "RC 5" or a previous RC, or a nightly build.

**Comment by obuisard** [comment]
I have updated the bug report to show RC 5 as the version tested.
Thanks @richard67 for the info about the default values in the database :-)

**Comment by richard67** [comment]
I think it could be fixed here in this function by adding the attachments property to that standard class and set it’s value to an empty string (or json?): https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Mail/MailTemplate.php#L411 .

I’ll have a look tomorrow if that’s the right fix if nobody is faster.

**Comment by richard67** [comment]
Will work on it today.

**Comment by obuisard** [comment]
Thank you @richard67, I was not able to propose a PR myself (traveling). I appreciate your help.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #35074 and then mark the test result in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/35074 by using the "Test this" button at the top left corner, selecting the right test result (I hope "success") and submit. Thanks in advance.
