### ISSUE TITLE
[4.0 RC5/6] Akeeba Backup "update available" question

### ISSUE THREAD

**Issue by sozzled** [joomla/joomla-cms#35085]
### Steps to reproduce the issue

Installed J! 4 RC5 with _Akeeba Backup_ v8.0.8.  Prior to updating to J! 4 RC6 I observed there was an update available for the _Akeeba Backup_ extension.  Attempted to use extension update facility prior to updating J! but the extension update failed (unable to write files).  Updated to J! 4.RC6 and was again advised there was an update available for _Akeeba Backup_.  Attempted to re-install _Akeeba Backup_ from the "Update from Web" facility but was not shown any version of _Akeeba Backup_ as "compatible" with the current version.  Changed the filter to look for "All versions of Joomla" and then re-installed the extension.  Still showing there is an extension update available even though the test site has v8.0.8 installed (see screenshot below)

### Expected result

The extension table should reflect the currently installed version of _Akeeba Update_.

### Actual result

The extension table shows the wrong version of _Akeeba Update_ (v6.1.0) and advises to update to v7.0.0.

![j4_ABupdate-available](https://user-images.githubusercontent.com/877778/128987580-78e993d1-0cc6-4aeb-8865-86116f18ad0e.png)

### System information (as much as possible)

PHP 7.4.6

### Additional comments

Cleared all caches, ran discover tool, database check.  No issues there.

**Comment by zero-24** [comment]
Can you share the update site URL? Is that the pro or free version?

**Comment by zero-24** [comment]
And what version is showed within the extensions table view in the backend, please share a screenshot here. Is the database version of the CMS up-to-date?

**Comment by sozzled** [comment]
I cannot "share" the website URL; it is a PC-hosted website.  I can, however, show a screenshot of the phpMyAdmin dump of the _extensions table.  AFAIK, the "CMS" is up-to-date.  Thanks for your reply.  I'll get the information for you shortly.

**Comment by Bond97** [comment]
@sozzled maybe @zero-24 means screenshot in administrator/index.php?option=com_installer&view=updatesites

**Comment by zero-24** [comment]
> I cannot "share" the website URL; it is a PC-hosted website. I can, however, show a screenshot of the phpMyAdmin dump of the _extensions table. AFAIK, the "CMS" is up-to-date. Thanks for your reply. I'll get the information for you shortly.

I dont need the website URL.

But I asked for the update server URL that you can find where @Bond97 reported it.
And I have asked for the Extensions page where the installed package version is listed.

**Comment by zero-24** [comment]
> AFAIK, the "CMS" is up-to-date. 

That was about the database version that you can find in the installer under the "Database" tab. There it reports whether the version is up-to-date in the database too. It should be but sometimes it isnt so lets check that,

**Comment by sozzled** [comment]
Scratch this.  The warning relates to _Akeeba Admin Tools_ (see the screenshot above).  Again, there is no compatible version appearing under the "Joomla Current Version" filter when trying to install (or, in my case, re-install) this extension and, when setting the filter to "All Joomla Versions" the latest version available is v6.1.0.  The problem is therefore not with J! but with the _AAT_ update site.

I'm closing this item for the time being and will live with the anomaly.
