### ISSUE TITLE
[4.1] Still can't select other fomat than images in media field and particulary in repeat field

### ISSUE THREAD

**Issue by SemaphoreOxalis** [joomla/joomla-cms#35088]
### Steps to reproduce the issue

Upload a PDF using media manager (every thing is set to allow it and you can see it in the media)
Create a repeat field using a media
Create an article using these repeat filed
Try to select the PDF

### Expected result

You can select the PDF

### Actual result
You can't select PDF

### System information (as much as possible)
J3.10
PHP7.4

### Additional comments
I know there is a loooot of others issue like this one #19954 #30548 #10871, each have been closed with no real answer. How can we build website a repeat forms with PDF uploading capacity (or other document field). We can hack the administrator/components/com_media/models/list.php and add PDF but it's not a solution and it' don't work with JCE media field override.

**Comment by richard67** [comment]
It has been solved in Joomla 4, not in 3.10.

**Comment by andrust** [comment]
I do experience this issue with 4.0.3 (https://github.com/joomla/joomla-cms/commit/27ffee6f90c409f96a385e4153cc43137c542124). Previously this _was_ working with 4.0.0-beta7 (https://github.com/joomla/joomla-cms/commit/1360a9b71aeeeab1dc6f12e8b452a226d1ec4fc6)
I was using https://docs.joomla.org/Media_form_field_type in my own module, and also i used this as a custom field. Unfortunately I don't have the PHP knowledge to pinpoint some code. As above stated, there are lots of closed issues like this, without useful answers, and the suggested 'hacks' do not apply in J4, and even if it did, I think hacking the core code is not ideal.

**Comment by keyoftime** [comment]
I found Joomla 4 Media Field had a new attribute "types" to selected pdf. Sorry to my poor english.

```
<field
    name="imageurl"
    type="media"
    types="images,documents,audios,videos"
    label="COM_BANNERS_FIELD_IMAGE_LABEL"
    directory="images"
    hide_none="1"
/>
```

**Comment by Quy** [comment]
Closing as duplicate of  #36252 which has additional info.
