### ISSUE TITLE
Render issue for editor field Codemirror when added to core component via plugin

### ISSUE THREAD

**Issue by RickR2H** [joomla/joomla-cms#35096]
### Steps to reproduce the issue
Download the plugin: [https://www.rickspaan.nl/testplugin.zip](https://www.rickspaan.nl/testplugin.zip "download testplugin")
Install an activate the plugin
Got to System -> Site template styles -> Cassiopeia
There should be an extra tab with an editor field with Codemirror layout
On initial load the gutter is to small and the line numbers are missing. Also when you start typing the first few characters are hidden behind the gutter.
When the page is reloaded the gutter is shows. After clearing the cache the same problem occurs.

![screen shot 2021-08-12 at 09 28 00](https://issues.joomla.org/uploads/1/b357a010ec4ee984658263b0611ad05e.jpg)

### Expected result
Gutter should always show

### Additional comments
It looks like some javascript is loaded to quickly / slowly.

**Comment by Fedik** [comment]
This is old codemiror issue, happen when it initialized with a hidden element.

Need to call `element.CodeMirror.refresh()` when the element become visible.

**Comment by RickR2H** [comment]
I hope someone can find some time to fix this as it is rather annoying to press refresh every time this happens.

**Comment by RickR2H** [comment]
@dgrammatiko Could you please take a look at this? It's bugging me for so long. Don't know how to fix this... Hope you can help!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35096">issues.joomla.org/tracker/joomla-cms/35096</a>.</sub>

**Comment by dgrammatiko** [comment]
Will have a look this weekend (hopefully, I have a big todo list…)

**Comment by RickR2H** [comment]
> This is old codemiror issue, happen when it initialized with a hidden element.
> 
> Need to call `element.CodeMirror.refresh()` when the element become visible.

@Fedik can you tell me in which file I have to call the refresh? Any guidance to solve the issue would be great. I asked @dgrammatiko but het is also really a busy guy ;)

I was playing with https://issues.joomla.org/tracker/joomla-cms/23577 en encountered the same issue.

**Comment by Fedik** [comment]
Wait, I will make PR

**Comment by Fedik** [comment]
please test #36140
