### ISSUE TITLE
[4.0] Menu items shown in the front-end but not in the backend

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#35090]
### Steps to reproduce the issue
1. Create an article.
2. Create a menu item for that article (type: Articles > Single Article) and set it in a menu that is visible in the front-end.
3. Trash the article.
4. Check your Menus > All Menu items. It is not there.
5. Check your front-end menu. It's there and there is no way to be removed.

### Expected result
See the same menu items in the backend and frontend

### Actual result
Seen in frontend but not in the backend

### System information (as much as possible)
Joomla 4.0.0 RC6

**Comment by brianteeman** [comment]
Unable to replicate with the instructions provided

**Comment by sakiss** [comment]
@brianteeman i tested that in a new installation with the multilingual sample data, in case it helps.

**Comment by sakiss** [comment]
Issue resolved after logging out and logging back in. Probably some kind of filter was saved in the session.
