### ISSUE TITLE
Getting 500 on the articles endpoint

### ISSUE THREAD

**Issue by xRealNeon** [joomla/joomla-cms#35100]
### Steps to reproduce the issue
Sending a GET request to the articles endpoint like described in the docs: https://docs.joomla.org/J4.x:Joomla_Core_APIs#Get_List_of_Articles

### Expected result
```json
{
    "alias": "my-article",
    "articletext": "My text",
    "catid": 64,
    "language": "*",
    "metadesc": "",
    "metakey": "",
    "title": "Here's an article"
}
```

### Actual result
```json
{
    "errors": [
        {
            "code": 500,
            "title": "Internal server error"
        }
    ]
}
```

### System information (as much as possible)
Joomla: 4.0.0-beta1
Server: Apache
PHP: 7.4
Postman

**Comment by xRealNeon** [comment]
I have Updated to rc6 now I can get a list of articles, but it's on `/api/index.php/v1/content/articles` not on `/api/index.php/v1/content/article` like in the docs

**Comment by alikon** [comment]
the docs should be updated  the correct one is `/api/index.php/v1/content/articles`

**Comment by xRealNeon** [comment]
I think that sums it up
