### ISSUE TITLE
[RC6] Akeeba Backup 9.0.2 - An unhandled Exception has been detected

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#35110]
### Steps to reproduce the issue
![screen shot 2021-08-13 at 17 00 44](https://issues.joomla.org/uploads/1/660dd6320ad479c3a80b1c8fbb067361.png)

### Actual result
see screenshot please

### System information (as much as possible)
4.0.0-RC6
PHP 7.4
PHP 8.0.6

### Additional comments
![screen shot 2021-08-13 at 17 05 33](https://issues.joomla.org/uploads/1/9bc0d81b38805ffb355b4bc90d32ad7b.png)

Some Users experience:

- There is a need to twist any write permissions - to check any "Encryptions" etc?. 
Access password protection deactivated because the AB 8 has problems with and asks for a password after every page change.

- After error messages "indefinable type" and length (debug mode on) Somehow got into the control panel.
Crash with a hint that one should export and import them manually.

Or, on another space with PHP 7.4
- Apply settings from 8, and everything was ok, configuration wizard done, backup performed, but no file in the backup folder. Back to Version 8 with backup.

**Comment by brianteeman** [comment]
I can confirm the problem. Checking if its an akeeba or joomla bug

**Comment by brianteeman** [comment]
I know what the problem is but sadly can't offer you a solution and you will have to report it as a bug at akeebabackup.com

For reference the bug is ONLY on windows filesystems

**Comment by brianteeman** [comment]
PS as it is a religious holy day this weekend don't expect a reply until monday https://en.wikipedia.org/wiki/Dormition_of_the_Mother_of_God

**Comment by ChristineWk** [comment]
@brianteeman 
Thanks for your info. I don't know what I'll do yet. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35110">issues.joomla.org/tracker/joomla-cms/35110</a>.</sub>

**Comment by ChristineWk** [comment]
I reported this to akeeba using the contact form. When it is processed there, I will close this issue here (later).

**Comment by ChristineWk** [comment]
Nicholas informed me (based on bug report via contact form) that this is a known issue which should be fixed in the next release scheduled for tomorrow. As the date of release so close to major religious holiday, he has to work even during  holiday.

**Comment by ChristineWk** [comment]
Thanks to Nicholas, who gave me the following information: 

The problem only happens on Windows. 

We have a custom method to load any template from any view of the component. To do that we need to “trick” Joomla into thinking that it’s loading view templates from a different component view than the current one. The only way this can happen is by changing the template path of the View object.
 

Up until some point Joomla was always using forward slashes as path separators. At some point it changed to backslashes on Windows only. Since we are trying to break down the original path by the path separator this broke the logic of our implementation and resulted in the errors.
 

Last time I had tried Akeeba Backup 9 on Windows was either beta 7 or RC2. I am not perfectly sure since I have overwritten that test site as Akeeba Backup 9.0.1 really can’t run on older betas and RC versions of Joomla – many things changed in the meantime. With RC6 I can indeed reproduce the issue which means I can solve it.

 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35110">issues.joomla.org/tracker/joomla-cms/35110</a>.</sub>

**Comment by brianteeman** [comment]
as i said before ;)

Anyway this can be closed

**Comment by ChristineWk** [comment]
@brianteeman OK. closed. But: we have explanation and more infos about :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35110">issues.joomla.org/tracker/joomla-cms/35110</a>.</sub>
