### ISSUE TITLE
[4.0] After initial install homepage whitespace issue

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35119]
### Steps to reproduce the issue

USE A LARGE MONITOR! 

Install 4.0-dev 
View homepage

### Expected result

No huge white space after header

### Actual result

The content on the white background is actually vertically centred... 

<img width="1491" alt="Screenshot 2021-08-15 at 00 58 36" src="https://user-images.githubusercontent.com/400092/129462949-397559f6-a59d-4a9b-ba94-6e7866fdc96b.png">

On a small viewport it "looks" right  because the vertically centred is pushed higher

WATCH VIDEO: https://screenshot.phil-taylor.com/rRubLbb4

### System information (as much as possible)

safari on mac
google chrome on mac

**Comment by sozzled** [comment]
Good call.  You don't need a large monitor to replicate the issue:  just shrink the zoom level and you'll discover that the component is vertically centred.

Reproducible with _FireFox 91.0_, _Opera 78.0.4093.147_, _Google Chrome 92.0.4515.159_, and _MS Edge 92.0.902.73_ on Windows 8.1 & 10.  Obviously there's no point trying to use _Internet Explorer_, of course, and _Safari on Windows_ is unsupported.  I've merely simulated the conditions for viewing a J! 4 website on a mobile device and it looks OK there.  It's just the desktop version of **Cassiopeia**.

**Comment by wilsonge** [comment]
Caused by https://github.com/joomla/joomla-cms/pull/34849

Potential fix in https://github.com/joomla/joomla-cms/pull/35012

**Comment by PhilETaylor** [comment]
Can't believe Joomla 4 is so close to release and yet the home page of Joomla 4 has this serious of an issue.

**Comment by sozzled** [comment]
Can one expect this to be remediated with the release and celebratory event of J! 4.0.0 within the next 12 hours or thereabouts?

**Comment by PhilETaylor** [comment]
Ive tested #35012 and it works - but it breaks on the error pages... so there is still work to be done, but even if #35012 is merged as is - it would be a million times better than launching a home page thats "broken"

**Comment by sozzled** [comment]
*sigh*

**Comment by PhilETaylor** [comment]
fixed in PR https://github.com/joomla/joomla-cms/pull/35012#issuecomment-899837880 so closing here
