### ISSUE TITLE
[4.0] Home Dashboard is always highlighted

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35118]
### Steps to reproduce the issue

install joomla-cms/4.0-dev today
Login to admin 
Select a sub menu item on the left

### Expected result

Home Dashboard is no longer highlighted 

### Actual result

Home Dashboard is still highlighted
Sub item selected is correctly higlighted
No console.log errors

<img width="355" alt="Screenshot 2021-08-15 at 00 37 39" src="https://user-images.githubusercontent.com/400092/129462721-db15109f-0afa-4d67-aa3a-4ba299e63434.png">

### System information (as much as possible)

Google Chrome on mac

**Comment by infograf768** [comment]
Confirmed also Firefox

**Comment by brianteeman** [comment]
Duplicate of #34484
