### ISSUE TITLE
[4.0] sprintf wrong number of params

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35122]
https://github.com/joomla/joomla-cms/blob/72e78f448f12e0b30a1a503440c888c969163134/libraries/src/Mail/Mail.php#L221

https://github.com/joomla/joomla-cms/blob/72e78f448f12e0b30a1a503440c888c969163134/libraries/src/Factory.php#L420

https://github.com/joomla/joomla-cms/blob/72e78f448f12e0b30a1a503440c888c969163134/libraries/src/Http/Transport/SocketTransport.php#L271

**Comment by wilsonge** [comment]
I've fixed the middle one directly as that is new in J4. The first and last are also in J3 so need to be made as a PR to 3.10 and propagated through.

**Comment by richard67** [comment]
For the first and the last finding see PR #35148 for 3.10-dev. Not sure if it's the best way to fix it, but it should work.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #35148 . Thanks in advance.
