### ISSUE TITLE
[4.0] Tabs click highlight border truncated on right 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35120]
### Steps to reproduce the issue

Install 4.0-dev - go to any page with tabs, click with mouse 

### Expected result

complete square blue outline

### Actual result

the right border of the outline is truncated

![Screen Recording 2021-08-15 at 01 05 56 am](https://user-images.githubusercontent.com/400092/129463056-8af9497f-cab4-40de-81e9-2aa4bcfb900f.gif)

### System information (as much as possible)

safari on mac

**Comment by brianteeman** [comment]
grrh I fixed this before

**Comment by brianteeman** [comment]
Weird that its showing the box at all because that should **only** be displayed when you navigate between tabs with the keyboard.

Appears to be an issue only with the safari browser?

**Comment by PhilETaylor** [comment]
> Appears to be an issue only with the safari browser?

Google Chrome and Firefox do not show this behaviour. Only Safari on mac can replicate this.

**Comment by dgrammatiko** [comment]
> Appears to be an issue only with the safari browser?

This is a long-standing issue of Safari, it treats click and tap totally different compared to any other browser. The solution here is focus-visible but not before the next release of Safari (assuming that they will provide focus-visible on their next stable, October)
<img width="1503" alt="Screenshot 2021-08-15 at 16 01 46" src="https://user-images.githubusercontent.com/3889375/129481132-9f6b3f5c-a3e9-4702-8507-3b92d4aa31ab.png">

**Comment by PhilETaylor** [comment]
Closing this then as a known issue thats not going to change.
