### ISSUE TITLE
[4.0] Add Admin Module

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#35153]
### Steps to reproduce the issue
Use the add module button on the dashboard
Select a module, give it a title etc and then Save and close

### Expected result
Module is published on the dashboard

### Actual result
No module Visible

### Additional comments
Unless my site is corrupted the problem is that when you click add a module the position is set to none when it should be preselected as cpanel.

![module](https://user-images.githubusercontent.com/1296369/129622684-401f6b4a-3535-40c8-9d42-ad701aee4928.gif)

**Comment by AliElhosh250** [comment]
i have tested it and it works  just fine

**Comment by brianteeman** [comment]
The code is designed so that when you click on the add module you are to create a module with the cpanel position already selected. This is the part that is not working. As shown in the original post there is no position preselected therefore it is in position ::none::

https://github.com/joomla/joomla-cms/blob/a72b834b303d07bb51575394f0235dbba7f0679d/administrator/components/com_cpanel/tmpl/cpanel/default.php#L41

**Comment by brianteeman** [comment]
resolved with #38611
