### ISSUE TITLE
https://topblogs.joomla.com/

### ISSUE THREAD

**Issue by ashishs45** [joomla/joomla-cms#35174]
### Steps to reproduce the issue
Hi, 

I HAVE THIS ERROR, WHEN WE ADD SMOMETHING IN.

"No configuration file found and no installation code available. Exiting..."
HOW CAN I SOLVED IT, PLEASE HELP ME.

**Comment by PhilETaylor** [comment]
Please post in the forum for support at https://forum.joomla.org

GitHub is for the development of Joomla, not for support :)
