### ISSUE TITLE
[4] installation folder delete failure gives no messages

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35170]
### Steps to reproduce the issue

@wilsonge @HLeithner
last min changes in #35168 got merged - oh well.
If Joomla is unable to delete the installation folder (permissions issues, or opcache_invalidate disabled by server admin

### Expected result

Helpful messages

### Actual result

`chmod 000 installation`

<img width="892" alt="Screenshot 2021-08-17 at 09 31 07" src="https://user-images.githubusercontent.com/400092/129692657-fc135ef4-8e25-4543-b6f1-bd8cb8b1be77.png">

or 

add die() in /installation/index.php

<img width="775" alt="Screenshot 2021-08-17 at 09 41 39" src="https://user-images.githubusercontent.com/400092/129693679-4dea9d2f-32fd-4ebc-a6a7-6fbb1420fe39.png">

**Comment by Fedik** [comment]
please try this one #35173

**Comment by HLeithner** [comment]
Thanks for the report fixed in #35173 and #35171
