### ISSUE TITLE
__DEPLOY_VERSION__ tags in libraries

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35185]
<img width="477" alt="Screenshot 2021-08-17 at 17 05 50" src="https://user-images.githubusercontent.com/400092/129761321-e6a46fc9-cbab-4cb8-93b8-644a07420ace.png">

**Comment by brianteeman** [comment]
1. Shouldnt these be reported upstream in the framework repo
2. at least two of them are correct if you read rather than grep

**Comment by PhilETaylor** [comment]
well you believe what you want to believe

**Comment by brianteeman** [comment]
i was checking from the bottom up and they were both in the vendor/ folder
