### ISSUE TITLE
[4.0.0-rc6] Akeeba Backup Migration 8.0.9 > 9.0.3: Error Joomla\CMS\Filesystem\Folder::create: Infinite loop detected

### ISSUE THREAD

**Issue by 7at1blow** [joomla/joomla-cms#35197]
### Steps to reproduce the issue

- J!4.0.0-rc6 with installed Akeeba Backup 8.0.9 (already with some implemented backups during the last months)
- downloading zip and then installation of Akeeba Backup 9.0.3 (before updating J!4.0.0-rc6 to 4.0.0 stable)
- after installation  of "Akeeba Backup for Joomla" 9.0.3 clicking the button "Migration" to migrate the configurations of 8.0.9 and the already implemented backups to 9.0.3 - like it is explained in the Backend > Components > Akeeba Backup (see added screenshot)

### Expected result

Migration without any error messages.

### Actual result

Got two error messages (Backend > Components > "Akeeba Backup for Joomla":

a) The settings migration failed to complete. You may have to manually import your backup profiles and / or transfer and import backup archives.

b) Joomla\CMS\Filesystem\Folder::create: Infinite loop detected.

### System information (as much as possible)

- 4.0.0-rc6

### Additional comments

- Couldn't find any information about this problem in the www.
- At the moment I don't dare to deinstall the prevoius version of Akeeba Backup (8.0.9) like it is explained (see screenshot).
- I don't really know what exactly and correctly to do with the hint "You may have to manually import your backup profiles and / or transfer and import backup archives".
- And at the moment I don't dare to continue with updating from J4.0.0-rc6 to 4.0.0 stable.

![2021-08-17 Akeeba Backup Migration in J4 0 0-rc6 _01](https://user-images.githubusercontent.com/42974861/129770543-7f94ff47-7193-42a6-9667-11b7d41b0ffd.jpg)

**Comment by PhilETaylor** [comment]
This sounds like an Akeeba issue - @nikosdion has been alerted but support should be sought from the Akeeba Forums and not here, until its proved its a Joomla 4 issue.

**Comment by PhilETaylor** [comment]
According to Nic this is already fixed in the dev release of Akeeba.

**Comment by PhilETaylor** [comment]
Already documented here: https://www.akeeba.com/news/1748-joomla-3-10-and-4-0-common-issues.html

**Comment by zero-24** [comment]
Closing for now thanks.

**Comment by nikosdion** [comment]
FWIW I fixed it by NOT using Joomla’s CMS Filesystem API. The bug is in Joomla. When it trie to write to a file it checks all root folders for writability but without checking for open basedir restrictions. I suspect that’s what causing it to bomb out. Suspect as in I wasn’t given access to an affected server so I can only infer from the common information of the affected users and reading Joomla’s code.

**Comment by 7at1blow** [comment]
@nikosdion After it will be fixed: Will there be offered a second possibilty for the Migration from Akeeba Backup 8.0.9 to Akeeba Backup for Joomla 9.0.x?
Or will I have to deinstall Akeeba Backup for Joomla 9.0.3 first and then to install the newer 9.0.x to get again the Migration button and possibility?
Can I/should I do something now? Or just wait? Thank you!

**Comment by nikosdion** [comment]
Frankly, whether yo are offered the migration depends on how much of it completed before Joomla bugged out on the files handling. 

If you do not see the migration button check if your backups are transferred, i.e do you see them in the Manage Backups page and can you download them? If you do and you can DO NOT uninstall Akeeba Backup 9, you'll lose your backups. Instead export the backup profiles from Akeeba Backup 8 and import then in Akeeba Backup 9.

**Comment by 7at1blow** [comment]
@nikosdion Thank you, Nicholas, for your further and helpful information.

**Comment by 7at1blow** [comment]
@nikosdion Thank you for the new version 9.0.4, and so fast!

In one 4.0.0-rc6-installation (still only with 8.0.9) I've now installed the new version of your Akeeba Backup 9.0.4 and the migration worked without any error messages.

Then I tried to deinstall the prevoius version 8.0.9 as I understood (System > Manage > Extensions: deinstall the Akeeba Backup Site Package 8.0.9). It ended with this error message:

_You have 3 extension(s) depending on this version of FOF. The package cannot be uninstalled unless these extensions are uninstalled first.

Es ist ein Fehler aufgetreten. [ ~ An error occured.]
0 Failed opening required '/var/www/vhosts/.../administrator/components/com_akeeba/BackupEngine/Factory.php' (include_path='.:/usr/local/php80/share/php80')_

The Akeeba Backup Site Package 8.0.9 remained installed (is still listed and enabled in the extensions list). It seems for now that only the menu item of 8.0.9 has disappeared from the backend menu (Components).

What should I do now?

**Comment by nikosdion** [comment]
This is either a leftover extension from a long time ago OR Joomla didn't fully install 9.0.4. Let's try both.

Try installing [Magic Eraser](https://github.com/akeeba/magiceraser/releases/tag/1.0.0). It doesn't actually install anything, it simply removes leftover obsolete extensions.

If this didn't work, try installing 9.0.4 twice in a row, **without** uninstalling it before or in between. Then go to Components, Akeeba Backup for Joomla (the menu item for Akeeba Backup 9). _Then_ try to uninstall Akeeba Backup 8.

You will still get the message about FOF, that's normal. If you can't uninstall it manually afterwards don't worry. An uninstaller for it will be provided in due time, just like Magic Eraser currently uninstalls FOF 3. I just want to make sure that most people will have had the chance to upgrade to Joomla 4 and our native Joomla 4 versions before letting them force uninstall FOF 4 (it's still used by Akeeba Ticket System and Akeeba Engage as I didn't have the time to convert them just yet).
