### ISSUE TITLE
Upgrade wamania/php-stemmer (if needed)

### ISSUE THREAD

**Issue by wamania** [joomla/joomla-cms#35200]
Hi guys

New release from wamania/php-stemmer
https://github.com/wamania/php-stemmer/releases/tag/v3.0.0

I just set phpunit to version 9 (from 4.8...) and set php to ^7.3
Backward compatible, but the tests won't work with php less than 7.3

(tested with php8.0)

**Comment by wilsonge** [comment]
This sounds amazing. But unfortunately our minimum requirements are going to be 7.2 for at least the foreseeable future.

**Comment by brianteeman** [comment]
@wilsonge the 7.3 requirement is just for the test.  Not something that would actually be included in the cms release. Or have I read that wrong.

**Comment by wilsonge** [comment]
The composer release requires it which would block the require. Even though I think the code is fine.

**Comment by brianteeman** [comment]
https://php.watch/articles/composer-ignore-platform-req
A new feature in Composer v2 allows you to selectively ignore platform requirements.

Does that help

**Comment by Hackwar** [comment]
Thank you @wamania for your work. As the others already said, we are stuck on PHP 7.2 for the Joomla 4.x lifecycle, but I created a PR to update to 3.0.0 for Joomla 5.0. The PR is #39953. With that, we would be closing this issue.
