### ISSUE TITLE
Pre-Update Check for Joomla 4.0.0 not 3.10.0 on Default Update Channel

### ISSUE THREAD

**Issue by mariantanase** [joomla/joomla-cms#35212]
### Steps to reproduce the issue
1. Start from an existing Joomla 3.9.28 website.
2. Update to Joomla 3.10
3. I see the screen with "Pre-Update Check for Joomla 4.0.0"
4. Click to Options > Change the channel from "Default" to "Joomla Next" and Save & Close.
5. Click to Options again > Change back from "Joomla Next" to "Default" channel, Save & Close.
6. Now I see the correct screen "Pre-Update Check for Joomla 3.10.0"

**Comment by zero-24** [comment]
Where are you comming from version whise? I have got a backup on another person to test and debug and will take a look into this afternoon. But would be great to know what version this site was build from in the beginning.

**Comment by mariantanase** [comment]
The site was build from 3.9.x joomla longo time ago...

**Comment by zero-24** [comment]
Please send me a Database backup of the 3.9.28 installation to tobias.zulauf@community.joomla.org I need the #__extensions table and there the com_joomlaupdate line.

**Comment by mariantanase** [comment]
> 
> 
> Please send me a Database backup of the 3.9.28 installation to [tobias.zulauf@community.joomla.org](mailto:tobias.zulauf@community.joomla.org) I need the #__extensions table and there the com_joomlaupdate line.

Done

**Comment by zero-24** [comment]
Ah I see the problem. Please test this PR: https://github.com/joomla/joomla-cms/pull/35214
