### ISSUE TITLE
[4.0-dev] Installation folder is deleted after installation without deleting it manually.

### ISSUE THREAD

**Issue by socke300** [joomla/joomla-cms#35218]
### Steps to reproduce the issue
1. Setup Joomla with 4.0-dev branch.
2. Follow the installation instructions
3. When the installation is finished, do not press the "Delete installation folder" button.
4. Click on the "open backend" button

### Expected result
The installation folder should remain.

### Actual result
The folder is deleted without pressing the "delete" button.

### System information (as much as possible)
I only noticed the error on Branch 4.0-dev, other versions were not tested.

**Comment by PhilETaylor** [comment]
Confirmed. 

@wilsonge is a naughty boy.

**Comment by infograf768** [comment]
The dev case is not anymore taken care of in `Joomla.deleteJoomlaInstallationDirectory = function (redirectUrl) {` in `remove.js`

**Comment by PhilETaylor** [comment]
It should - here: 

https://github.com/joomla/joomla-cms/blob/c59286034b3794ddd63f302e569ef09714447dde/installation/template/js/remove.js#L55

**Comment by infograf768** [comment]
You are correct. There were many changes in that js file since I looked at it.

**Comment by PhilETaylor** [comment]
fixed in https://github.com/joomla/joomla-cms/pull/35220

**Comment by richard67** [comment]
Closing as having a pull request, Please test #35220 (as soon as testing instructions are ready there). Thanks in advance.
