### ISSUE TITLE
[4]Content cannot be scheduled to be featured.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35213]
### Steps to reproduce the issue

Create an article in Joomla 4 with a Start Featured and Finish Featured date/times

Save 

Dates are lost

### Expected result

<img width="727" alt="Screenshot 2021-08-18 at 09 12 31" src="https://user-images.githubusercontent.com/400092/129862685-b4188f0c-05a0-4fb3-be8c-3e23d421dfe8.png">

### Actual result

<img width="737" alt="Screenshot 2021-08-18 at 09 13 16" src="https://user-images.githubusercontent.com/400092/129862759-b0f466b3-20dd-4884-a994-c7767663aac2.png">

**Comment by richard67** [comment]
Isn't it like that in J3, too, that start and end featured dates are only used if the "Featured" status is set for that article?

**Comment by PhilETaylor** [comment]
And that makes sense to you?  Featured status is a toggle... you should be able to set the dates without setting featured = true

You might have an article that you have published as featured and want to be able to toggle on and off at will the featured status.

**Comment by brianteeman** [comment]
Duplicate #29942

**Comment by brianteeman** [comment]
> Isn't it like that in J3, too, that start and end featured dates are only used if the "Featured" status is set for that article?

Its a new feature in 4

**Comment by PhilETaylor** [comment]
When you toggle the featured status in the article list view - the dates are also deleted.

**Comment by richard67** [comment]
> Its a new feature in 4

Ouch, my mistake. Yes, I remember now we added it in J4.

**Comment by PhilETaylor** [comment]
> Duplicate #29942

So this was known of for over a year?... wow... Joomla 4, the only CMS that you cannot easily maintain content in... #fail.
