### ISSUE TITLE
[4.0] Nightly builds can't updated properly

### ISSUE THREAD

**Issue by Bond97** [joomla/joomla-cms#35210]
### Steps to reproduce the issue
1. Install 4.0.1-dev
2. Set update server https://update.joomla.org/core/nightlies/next_major_list.xml
3. Try to update Joomla 4.0.1-dev to latest nightly version

### Expected result
Button "Reinstall Joomla files".

### Actual result
Nothing happens and in https://update.joomla.org/core/nightlies/next_major_list.xml you will see 4.0.0-rc7-dev, not 4.0.1-dev

**Comment by zero-24** [comment]
The next major update would point to 5.0 which is not in any pipeline yet. So please switch to the next patch (3.10+4.0) or next minor (4.1) in the mean time.

**Comment by Bond97** [comment]
@zero-24 ok, I will switch to "next patch", but maybe it will be better to update link on page https://developer.joomla.org/nightly-builds.html ?

I mean 4.1 and write properly link in 4.0.

**Comment by zero-24** [comment]
Ups yes we planed to change the plugin but It seems it got missed in the process and with much less sleep than recommended ;)

https://github.com/joomla/developer.joomla.org/pull/44

Will also later check the update server itself as the file is not gone yet while it should be removed from there.

**Comment by zero-24** [comment]
Ok so the next_major update servers should be gone by the next sync of the CDN.

**Comment by PhilETaylor** [comment]
https://docs.joomla.org/J3.x:Joomla_3.10_points_to_4.0_while_it_claims_to_be_on_the_Default_update_server

**Comment by Bond97** [comment]
Ok, so it's time to merge joomla/developer.joomla.org#44 and update https://developer.joomla.org/nightly-builds.html - write new xml to 4.1-dev like next_minor_list.xml

When it happens, I will close issue :)

**Comment by zero-24** [comment]
Yes its still on my radar but i have not yet had the time to fix it yet.

**Comment by zero-24** [comment]
We are awaiting @HLeithner to merge the PR and deploy it to the site. I have removed the old update servers from the CDN already.

**Comment by HLeithner** [comment]
should be fine now.

**Comment by brianteeman** [comment]
Thanks @HLeithner
