### ISSUE TITLE
[J4] Media field outputs broken image if  only description is set

### ISSUE THREAD

**Issue by regularlabs** [joomla/joomla-cms#35227]
### Steps to reproduce the issue
Create a Media field.
Only fill in the description, but leave the image field itself (path) empty.
![image](https://user-images.githubusercontent.com/13553242/130084596-ab5895ff-755c-4280-b9e6-aa788c6b47a5.png)

### Expected result
No image is shown.

### Actual result
A broken image is shown (img tag with no src value).
![image](https://user-images.githubusercontent.com/13553242/130084667-be0d47e6-7633-4912-a0e7-58abc37b5097.png)

**Comment by laoneo** [comment]
Please test #35556.

**Comment by alikon** [comment]
closing as we have a pr #35556
