### ISSUE TITLE
[4.1] Unable to focus in media files

### ISSUE THREAD

**Issue by Krshivam25** [joomla/joomla-cms#35229]
### Steps to reproduce the issue
1. Open Media
![media](https://user-images.githubusercontent.com/49578630/130100468-6f943e62-1258-47ef-9e75-08ecc715819b.png)
2. Use tab to navigate through the elements
![media local](https://user-images.githubusercontent.com/49578630/130100754-757b4bc0-a091-49c3-8fea-d8072d4b6f87.png)
3. This element is not accessible with the keyboard

**Comment by PhilETaylor** [comment]
Confirmed.

**Comment by pritam825** [comment]
I have started working on this

**Comment by khu5h1** [comment]
@Krshivam25 I have solved the issue and would be creating a PR for the same.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #35911 . Thanks in advance.
