### ISSUE TITLE
Pre-Update check not working

### ISSUE THREAD

**Issue by johanpeters** [joomla/joomla-cms#35224]
### Steps to reproduce the issue
components>Joomla Update>options> set to joomla update channel to next
run Joomla update

### Expected result
pre-update check will activly check if installed modules,components, plugins are compliant with the next version based on the joomla update version. i expact the result to be the same as when update channel is set to default

### Actual result
it list the plugins but not actualy running checks to see if its compliant or not.
no extentions are checked and get status of good, issues, not compliant.

when i set joomla update channel to default then you see it's running the pre-update check and also getting results.
but the default is currently joomla 3.10

### System information (as much as possible)
php 7.4
joomla update channel default (joomla 3.10)
joomla update channel next (joomla 4.00)

**Comment by johanpeters** [comment]
i have tried it on several domains, several servers and serveral hosting componies.
al with the same results.
i can not update to Joomla 4.00 
live update, ignore and update is also not working (button is not working).

**Comment by zero-24** [comment]
What database type and version do you use? You can check that under the system information.

**Comment by johanpeters** [comment]
Site 1
Php 7.4.16
MariaDB 10.3.29

Site 2
Php 7.4.16
MariaDB 10.2.39

**Comment by zero-24** [comment]
Hmm what happend when you go and clear the update cache under: Extensions -> manage -> Update -> clear cache

**Comment by zero-24** [comment]
Can you please show a sceenshot and whether there are any JS error messages in the browser console?

**Comment by johanpeters** [comment]
screenshot of joomla pre-update check (joomla update channel default)
![FireShot Capture 001 - Joomla Update - Ton Halfman Photography - Administration - thphoto itics net](https://user-images.githubusercontent.com/1411354/130033931-f46319c0-b184-42d0-ad13-9347a3f31f36.png)

screenshot of joomla pre-update check (joomla update channel next)
![FireShot Capture 002 - Joomla Update - Ton Halfman Photography - Administration - thphoto itics net](https://user-images.githubusercontent.com/1411354/130033954-737fe35f-765d-4dde-9875-7a5d86e1b863.png)

**Comment by zero-24** [comment]
OK do you get any JS error messages in the browser console?

**Comment by johanpeters** [comment]
if needed / handy i can arrange access.. it's not a live site (still in development).
then you can see what happends..

**Comment by johanpeters** [comment]
> OK do you get any JS error messages in the browser console?

no JS errors

**Comment by zero-24** [comment]
> if needed / handy i can arrange access.. it's not a live site (still in development).
> then you can see what happends..

Please do send the access data to tobias.zulauf@community.joomla.org

**Comment by johanpeters** [comment]
> > if needed / handy i can arrange access.. it's not a live site (still in development).
> > then you can see what happends..
> 
> Please do send the access data to [tobias.zulauf@community.joomla.org](mailto:tobias.zulauf@community.joomla.org)

sent you the details

**Comment by zero-24** [comment]
Thanks will take a closer look once I'm back from work this afternoon

**Comment by johanpeters** [comment]
Thanks @zero-24 .. keep me posted

**Comment by johanpeters** [comment]
Hello @zero-24 ..by change did you find time to jave a look at this issue?..

**Comment by zero-24** [comment]
I have just replied to your mail :)

**Comment by zero-24** [comment]
Please test this patch here: https://github.com/joomla/joomla-cms/pull/35272
