### ISSUE TITLE
joomla 4 extensions download fails when URL redirects

### ISSUE THREAD

**Issue by casaschi** [joomla/joomla-cms#35231]
I'm managing the embedchessboard extension, it works great on joomla 4 apart from an installation issue.

The extension is registered on the joomla extension directory to support the web install option.
The download URL was fully working on joomla 3.x
http://downloads.sourceforge.net/project/pgn4web/embedchessboard-joomla-plugin-3.05.00.zip

This is the URL on sourceforge that will redirect to one of their mirrors.

The web install on joomla 4 gives an error, about missing the manifest file, that means it did not download the file correctly. Same passing the URL above to the "install from URL form".

If instead I use the actual mirror address in the "install from URL form", it all works:
https://kumisystems.dl.sourceforge.net/project/pgn4web/embedchessboard-joomla-plugin-3.05.00.zip

Something changed from joomla 3.x to joomla 4 that does not like URL redirects when downloading an extension. Is this intentional or it's a bug? How do I report this issue for a fix?

Thanks.

PS: temporarily I changed the web install URL to restore the functionality, but it would really be great to get it back to work as in joomla 3.x

**Comment by PhilETaylor** [comment]
(note not https://) 

http://downloads.sourceforge.net/project/pgn4web/embedchessboard-joomla-plugin-3.05.00.zip generates a 302 Found Header when its first attempted here: 

https://github.com/joomla/joomla-cms/blob/c59286034b3794ddd63f302e569ef09714447dde/libraries/src/Installer/InstallerHelper.php#L83

that redirects to https:// for me 

```
HTTP/1.1 302 Found
Connection: keep-alive
Content-Disposition: attachment; filename="embedchessboard-joomla-plugin-3.05.00.zip"
Content-Length: 375
Content-Type: text/html; charset=UTF-8
Date: Thu, 19 Aug 2021 16:26:45 GMT
Location: https://kumisystems.dl.sourceforge.net/project/pgn4web/embedchessboard-joomla-plugin-3.05.00.zip
Server: nginx
Set-Cookie: sf_mirror_attempt=pgn4web:kumisystems:embedchessboard-joomla-plugin-3.05.00.zip; Max-Age=120; Path=/; expires=Thu, 19-Aug-2021 16:28:45 GMT
```

and then if I try that url it loads with a 2-- OK - it never redirects me to a mirror.

The 302 should be handled by Joomla though 

https://github.com/joomla/joomla-cms/blob/c59286034b3794ddd63f302e569ef09714447dde/libraries/src/Installer/InstallerHelper.php#L95

**Comment by casaschi** [comment]
If you try in the extension "Install from URL" form, both
http://downloads.sourceforge.net/project/pgn4web/embedchessboard-joomla-plugin-3.05.00.zip
and
https://downloads.sourceforge.net/project/pgn4web/embedchessboard-joomla-plugin-3.05.00.zip
fail.

Only the last URL works, the one that does not redirects anymore:
https://kumisystems.dl.sourceforge.net/project/pgn4web/embedchessboard-joomla-plugin-3.05.00.zip

It might be that sourceforge is doing something funny... but it used to work without a glitch in joomla 3.x<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35231">issues.joomla.org/tracker/joomla-cms/35231</a>.</sub>

**Comment by PhilETaylor** [comment]
When Joomla calls 

```
GET /project/pgn4web/embedchessboard-joomla-plugin-3.05.00.zip HTTP/1.1
Host: downloads.sourceforge.net
User-Agent: Mozilla/5.0 Joomla!/4.0.1-dev Joomla
Accept: */*
Connection: keep-alive
```

The response is:

```
HTTP/1.1 307 Temporary Redirect
Server: nginx
Date: Thu, 19 Aug 2021 16:33:51 GMT
Content-Type: text/html; charset=UTF-8
Content-Length: 454
Location: https://sourceforge.net/projects/pgn4web/files/embedchessboard-joomla-plugin-3.05.00.zip/download?use_mirror=kumisystems
Proxy-Connection: keep-alive

<html>
 <head>
  <title>307 Temporary Redirect</title>
 </head>
 <body>
  <h1>307 Temporary Redirect</h1>
  The resource has been moved to <a href="https://sourceforge.net/projects/pgn4web/files/embedchessboard-joomla-plugin-3.05.00.zip/download?use_mirror=kumisystems">https://sourceforge.net/projects/pgn4web/files/embedchessboard-joomla-plugin-3.05.00.zip/download?use_mirror=kumisystems</a>;
you should be redirected automatically.


 </body>
</html>
```

Joomla doesnt handle a 307. Joomla will only handle a 302 Found redirect.

**Comment by casaschi** [comment]
"Joomla doesnt handle a 307. Joomla will only handle a 302 Found redirect."

it used to work in joomla 3.x... any chance of restoring the functionality?

In a way, it makes sense to use the temporary redirect because sourceforge uses a pool of mirrors, so requesting the same URL at different times might result in a different mirror being selected and a different final URL.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35231">issues.joomla.org/tracker/joomla-cms/35231</a>.</sub>

**Comment by PhilETaylor** [comment]
Its been this way for 3 years from https://github.com/joomla/joomla-cms/pull/23065 https://github.com/joomla/joomla-cms/commit/046f014ad6ee7c6376baab1b07e7de2082f66ddc

**Comment by PhilETaylor** [comment]
In fact when testing Im getting a 200 OK header now... with no body.. 

Investigating.

**Comment by casaschi** [comment]
It seems I haven't checked for a while... I just spotted the issue now doing some checks on joomla 4.

Still, would there be any issue in handling a 307 response in the same way as a 302 response?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35231">issues.joomla.org/tracker/joomla-cms/35231</a>.</sub>

**Comment by casaschi** [comment]
Weird, but I have very little chance of changing sourceforge behaviour.

Such a pity that the joomla extension directory does not offer the possibility to pull the extension from their server...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35231">issues.joomla.org/tracker/joomla-cms/35231</a>.</sub>

**Comment by PhilETaylor** [comment]
sourceforge is just trying to protect against leeching... its now giving me different responses each time.

**Comment by PhilETaylor** [comment]
Ok I have it stable now.

The first call is a 307 redirect which it seems Joomla (somehow) is following. 

This redirects me to https://sourceforge.net/projects/pgn4web/files/embedchessboard-joomla-plugin-3.05.00.zip/download?use_mirror=kumisystems

That is a 200 OK response with a full HTML page. 

Sourceforge is not giving us any Zip file url to download - it gives us a 200 OK with a HTML page. 

This is Sourceforge protecting against leeching and automated downloads. 

This therefore cannot be fixed in Joomla.. 

<img width="1593" alt="Screenshot 2021-08-19 at 17 54 01" src="https://user-images.githubusercontent.com/400092/130110864-545a74fa-d129-415c-a80b-f4265b9f3053.png">

**Comment by PhilETaylor** [comment]
It should also be noted that if you do all this at the command line with Curl you will first get a 302  and then a 200 with the zip file contents.

**Comment by casaschi** [comment]
The conclusion seems that I need to find another host for the download package of my joomla extension :-(

Thanks for looking into this!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35231">issues.joomla.org/tracker/joomla-cms/35231</a>.</sub>

**Comment by PhilETaylor** [comment]
Sourceforge is so 1990s anyway :) 

GitHub is the way to host code now :)

**Comment by richard67** [comment]
Closing as not a core issue.
