### ISSUE TITLE
[J4] Directly Create New Article In Specific Category Doesn't Always Work As Expected

### ISSUE THREAD

**Issue by JoeJoomla** [joomla/joomla-cms#35230]
### Steps to reproduce the issue

In a fresh Joomla 4  install create a new category called 'Blog'.  You should now have two categories; category id=2 for 'uncategorized' and id=8 for 'blog' category.

Go to the main dashboard and use the following URL structure in the browser window (or create a link in a custom admin module to click) to open an 'Add Article' in the blog category (assuming id=8 is blog category):

`/administrator/index.php?option=com_content&filter[category_id]=8&view=article&layout=edit`

This may work as expected the first time but if you then try to directly open a new article editor window in the uncategorized id=2 category you likely will get the blog category instead.

So on a subsequent try, with id=2 for 'uncategorized' and id=8 for 'blog'' category, put the URL in the browser  (or click the link you made with the URL in it) for:

`/administrator/index.php?option=com_content&filter[category_id]=8&view=article&layout=edit` 

### Expected result

A new article editor window should open with the blog category already selected.

### Actual result

A new window is opened with the category 'uncategorized' selected instead of the 'blog' category

![open-new-article-in-specific-category](https://user-images.githubusercontent.com/1197717/130103559-cb68af51-0c85-4004-b89c-588ad2b96f9e.jpg)

### System information (as much as possible)

Joomla! 4.0.0 Stable
PHP 7.3.29
Database 5.7.33-cll-lve

**Comment by PhilETaylor** [comment]
IIRC the `filter[category_id]` syntax can only be used on list views, not edit views?

**Comment by PhilETaylor** [comment]
http://example.com/administrator/index.php?option=com_content&view=article&layout=edit&catid=2
http://example.com/administrator/index.php?option=com_content&view=article&layout=edit&catid=8

These work for me. 

Because of this code: 

```// Pre-select some filters (Status, Category, Language, Access) in edit form if those have been selected in Article Manager: Articles```
https://github.com/joomla/joomla-cms/blob/c59286034b3794ddd63f302e569ef09714447dde/administrator/components/com_content/src/Model/ArticleModel.php#L626

**Comment by JoeJoomla** [comment]
Thank you Phil, that does indeed work. I'll close up this issue now.
