### ISSUE TITLE
[4.0.0] Missing label tag in advanced search

### ISSUE THREAD

**Issue by kapetanov** [joomla/joomla-cms#35249]
### Steps to reproduce the issue

1. open the website frontend with standard installation (cassiopeia template)
2. use the search function in the website header
3. open the advanced search on the results page
4. the input fields of the calendar selection have no label tags

The label tags for the input fields with the id "filter_date1" and "filter_date2" are missing. Label tags are necessary for accessibility.

**Comment by brianteeman** [comment]
Sorry but this report is not correct.

![image](https://user-images.githubusercontent.com/1296369/130314524-c1581e12-ddf1-406c-8de4-a3255a6eaeba.png)

And this is announced correctly by both NVDA and Narrator. 

Tip: Automated testing tools are only an indicator, they are not perfect.

**Comment by kapetanov** [comment]
Sorry, I ran the test tool and overlooked the tag in the source code. the label tag is available. My mistake.

However, there is one other flaw. The validation of the date fields does not work properly. If an incorrect date is entered manually, the date is simply set to today's day.

An error message would be correct.

Errors often occur when entering forms: users make mistakes or skip required entries.

If user input is checked, the error messages issued should be helpful. They should identify the field (or fields) with incorrect or missing entries and make it easier for users to correct entries.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35249">issues.joomla.org/tracker/joomla-cms/35249</a>.</sub>

**Comment by brianteeman** [comment]
that is a different issue. please close this one and create a new issue for the validation

**Comment by kapetanov** [comment]
i will create more issue reports on monday. I noticed another bug in the backend.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35249">issues.joomla.org/tracker/joomla-cms/35249</a>.</sub>
