### ISSUE TITLE
[4.0] JGLOBAL_INTEGRATION_LABEL language item for en_US

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#35248]
### Steps to reproduce the issue
I don't know why **JGLOBAL_INTEGRATION_LABEL** language item for en_US (administrator/language/en-US/lib_joomla.ini) has value **Menu Item Associations** while it has nothing to do with menu item associations. Sound like a translation mistake?

![Articles-Options-Joomla-4-Administration](https://user-images.githubusercontent.com/977664/130209975-09ee20f3-362a-452e-b799-95ce830209d2.png)

### Expected result
Should be **Integration**

### Actual result
**Menu Item Associations**

### Additional comments
Found that while installing the language to test PR https://github.com/joomla/joomla-cms/pull/35222 .

**Comment by infograf768** [comment]
Many errors in this pack. Version and others.
For example
`JNO="Notice"`

**Comment by PhilETaylor** [comment]
yes see https://github.com/joomla/joomla-cms/issues/35205

**Comment by joomdonation** [comment]
Ah, OK. I'm closing this issue, then.
