### ISSUE TITLE
[4.0] English Language Pack Not Updating

### ISSUE THREAD

**Issue by jweaver0312** [joomla/joomla-cms#35245]
### Steps to reproduce the issue

Says 4.0.0.6 package is available
Hit update

### Expected result

Update to 4.0.0.6 successfully

### Actual result

Backend says it was successful but still reflects 4.0.0.1 as the currently installed pack

### Additional comments

Even tried completely removing it and reinstall and it still only results in 4.0.0.1 being present.

**Comment by infograf768** [comment]
If you speak about en-US or en-AU, theavailable packs are totally wrong for the version in the pkg as well as the langmetadata.xml
```
<?xml version="1.0" encoding="utf-8"?>
<metafile client="administrator">
	<name>English (United States)</name>
	<version/>
	<creationDate>August 2021</creationDate>
```

**Comment by particthistle** [comment]
That's now been resolved in the past 30 minutes with a new update that is the process of waiting to appear in the language installer list.

4.0.1.1 pack is just slightly more cutting edge than it needed to be. If you install it, it resolves the version issue.

A 4.0.0.10 version has been corrected and uploaded but from what @infograf768 is telling me at the moment it won't replace the 4.0.1.1 version at this time. 4.0.1.1 won't be a problem after Tuesday with a 4.0.1 release coming out.

**Comment by infograf768** [comment]
> 4.0.1.1 won't be a problem after Tuesday with a 4.0.1 release coming out.

It still would display no version in the admin ui (site/admin) as well as the pkg manifest. It is the pkg version which defines Updates afaik. So updates would be broken for subsequent packs 4.0.1.x, 4.0.2.x, etc.

**Comment by particthistle** [comment]
After further diagnosis, 4.0.1.1 pack had to be removed which has been now completed.

@jweaver0312 if you install/update/reinstall 4.0.0.11 now you'll find it gives you correct versioning.

You should also find 4.0.0.12 appearing in the next few hours to also resolve remaining additions https://github.com/joomla/core-translations/issues/35

**Comment by brianteeman** [comment]
This can probably be closed now as @particthistle reports it was fixed

**Comment by particthistle** [comment]
Correct @brianteeman - packs have been further updated several times since August. @jweaver0312 please close the issue.
