### ISSUE TITLE
[4] Cannot preview content in admin that is unpublished

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35256]
### Steps to reproduce the issue

4.1-dev

# **MAKE SURE YOU ARE NOT LOGGED INTO THE FRONTEND**

Create an article in /administrator/ - ensure that published is set to `Unpublished`
Save the article.
Click Preview

### Expected result

As a Super Admin origin content, I want to be able to preview the unpublished article.

### Actual result

404 Page not found.

**Comment by brianteeman** [comment]
Same issue as #35255 should be merged as a single issue

**Comment by PhilETaylor** [comment]
two totally different features. One is time based, one is a state flag in the db, therefore 2 different fixes required.

**Comment by brianteeman** [comment]
whatever,

**Comment by brianteeman** [comment]
For reference the article **will** be displayed if you are logged in to the frontend.

Terrible UX but thats how the code was created

**Comment by PhilETaylor** [comment]
I know that. Proves you don't read. Let me make it more bold and larger for you. 

```
MAKE SURE YOU ARE NOT LOGGED INTO THE FRONTEND
```

**Comment by Quy** [comment]
Duplicate #24132

**Comment by PhilETaylor** [comment]
There simply is no code to power this feature... its not a bug. Its just never been a feature. Apparently.

**Comment by alikon** [comment]
please test #35488
