### ISSUE TITLE
[4] Breadcrumbs (and other modules) have redundant "show title" toggle.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35259]
### Steps to reproduce the issue

If you edit the breadcrumbs module there is a show/hide toggle for the title.

This does nothing. (Unlike, say, mod_menu which shows a title when togged to show one).

Other modules also have this same issue. 

### Expected result

Only show options that actually do things! 

### Actual result

<img width="523" alt="Screenshot 2021-08-20 at 17 05 16" src="https://user-images.githubusercontent.com/400092/130261890-71514407-d6df-41dd-b4da-9ab00c443483.png">

**Comment by brianteeman** [comment]
Just as with Joomla 3 it depends on what position and chrome the module is published in.

![image](https://user-images.githubusercontent.com/1296369/130263074-a7a643ee-78c3-4ffd-a8b0-a0980fef88ed.png)

**Comment by PhilETaylor** [comment]
hmmm ok then,,
