### ISSUE TITLE
[4] Cannot preview expired content in admin

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35255]
### Steps to reproduce the issue

MAKE SURE YOU ARE NOT LOGGED INTO THE FRONTEND
Create an article in /administrator/ with a "Finish Publishing" date greater than "now"
Save the article.
Click Preview

### Expected result

As a Super Admin origin content, I want to be able to preview the article.

### Actual result

404 Page not found.

**Comment by alikon** [comment]
related to #24132 
solvable expanding #35488 a bit

**Comment by PhilETaylor** [comment]
I have rejected  #35488  on the basis it doesnt work and introduces a huge security hole into Joomla.
