### ISSUE TITLE
[4] Left admin template site doesn't touch bottom

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35262]
### Steps to reproduce the issue

Left admin template site doesn't touch bottom bar.

### Expected result

full coverage

### Actual result

A pixel or two space... 

<img width="352" alt="Screenshot 2021-08-20 at 17 49 02" src="https://user-images.githubusercontent.com/400092/130267151-2c615645-bc02-454b-845c-b307648eb5ca.png">

### System information (as much as possible)

Google Chrome and Safari on mac tested.

**Comment by PhilETaylor** [comment]
Im going to say this is a browser thing...

**Comment by PhilETaylor** [comment]
Narrator: its not a browser thing...

**Comment by brianteeman** [comment]
Can not replicate on chrome windows

![image](https://user-images.githubusercontent.com/1296369/131232319-0fc528fa-fe8a-40cd-9a40-8cbed0c13de5.png)

**Comment by PhilETaylor** [comment]
Firefox, Google Chrome and Safari on mac tested - all have the same issue - only with Joomla 4 admin, not with other templates - eg (random quick google) https://www.spruko.com/demo/dashlot/Dashlot/sidemenu-Toggle-Light/index.html

<img width="467" alt="Screenshot 2021-08-28 at 23 19 09" src="https://user-images.githubusercontent.com/400092/131232381-471d4695-b50f-49b1-9040-39397b868ba2.png">

**Comment by PhilETaylor** [comment]
![Screen Recording 2021-08-28 at 11 21 47 pm](https://user-images.githubusercontent.com/400092/131232433-6c0605f1-9c26-42bf-a278-ec1d52201465.gif)

**Comment by brianteeman** [comment]
Until you showed this last image it was not obvious that you were referring to the log in page which as you know is a different file to the main template.

I can confirm it on the login page and only on the login page

**Comment by PhilETaylor** [comment]
but are you on a small laptop screen with no vertical space?

<img width="780" alt="Screenshot 2021-08-28 at 23 31 03" src="https://user-images.githubusercontent.com/400092/131232532-0efb2b20-b74b-464c-8aba-1654f89c1f89.png">
<img width="677" alt="Screenshot 2021-08-28 at 23 30 56" src="https://user-images.githubusercontent.com/400092/131232533-400c496b-ac44-4e9c-9da3-a439f7e64da4.png">
<img width="1029" alt="Screenshot 2021-08-28 at 23 30 37" src="https://user-images.githubusercontent.com/400092/131232535-f977b112-8983-4364-bdc3-b38697cd12ac.png">

**Comment by brianteeman** [comment]
Please test changing the value here to 66px which is the height of the header and not 69
https://github.com/joomla/joomla-cms/blob/ddb844b450ec989f08f6a54c051ca52d57fa0789/administrator/templates/atum/scss/blocks/_sidebar.scss#L5

**Comment by PhilETaylor** [comment]
yup that fixes it - thanks - PR https://github.com/joomla/joomla-cms/pull/35412
