### ISSUE TITLE
[4.0.0] Little bug for Logo and Sidebar collapse animation

### ISSUE THREAD

**Issue by simbus82** [joomla/joomla-cms#35264]
### Steps to reproduce the issue
Use the "Toggle Menu" in Admin

### Expected result

- No overflow of the Logo over the header-title
- Same transition easing for Logo and Sidebar
![issue-solved-joomla-3](https://user-images.githubusercontent.com/1375730/130265967-ec6f0d32-c1b4-4214-b63c-333a74bde7b4.gif)

### Actual result
- The Logo have an overflow over the header-title
- Logo have an "ease-in-out" transition and Sidebar only "ease" transition.
![issue-solved-joomla-2](https://user-images.githubusercontent.com/1375730/130265772-1a145bf8-29be-490a-aeea-8b07396f8f20.gif)

### Additional comments
Solution in Pull Requests
https://github.com/joomla/joomla-cms/pull/35265
https://github.com/joomla/joomla-cms/pull/35266

**Comment by Quy** [comment]
Thank you for the PRs. It is not necessary to create an issue if you have the PR. Just include the info in the PR to save time and less steps.

**Comment by brianteeman** [comment]
There is no need to open an issue if you are also opening a pull request

**Comment by simbus82** [comment]
Oook! I thought I had to always do the "issue" and then propose the solution. Better this way, simpler. Thanks!
