### ISSUE TITLE
UI Bug - Display extension logo incorrectly

### ISSUE THREAD

**Issue by mozaffar** [joomla/joomla-cms#35274]
### Steps to reproduce the issue
1. Install an extension (in my case RSForm Pro)

### Expected result
Display the extension logo in its place in resized mode

### Actual result
Disaplys the logo in right place but it is not resized and it covers some parts of the installation message

### System information (as much as possible)
Linux Fedora 34, Apache![screen shot 2021-08-21 at 04 43 16](https://issues.joomla.org/uploads/1/7f77d08ace514fa754ad0a8b5332bfcc.png)

**Comment by joomdonation** [comment]
This message, actually, generated by the extension itself, not Joomla. So I guess you should report this issue to RSForm Pro developer instead.

**Comment by PhilETaylor** [comment]
This is not a Joomla Core issue. This should be closed.

**Comment by joomdonation** [comment]
Closing. Please contact RSForm Pro developer for support if needed.
