### ISSUE TITLE
[3.x] Pre-Update check title

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#35287]
_Issue reported to me by a user._

The title of the Pre-update check is confusing. It says its for 3.10.0 but I am already on 3.10.0

![image](https://user-images.githubusercontent.com/1296369/130347793-fed25d3f-a0f6-40e5-9ab2-c30c311e0fa2.png)

![image](https://user-images.githubusercontent.com/1296369/130347795-6b2d22a5-627d-496e-bf04-8aed5fb878d7.png)

**Comment by zero-24** [comment]
Yes this is an known issue to be fixed here: https://github.com/joomla/joomla-cms/pull/35269

**Comment by brianteeman** [comment]
ok - cool
