### ISSUE TITLE
No progress bar in admin when installing extensions

### ISSUE THREAD

**Issue by cantgetmyusername** [joomla/joomla-cms#35283]
### Steps to reproduce

navigate to the "mamage/install" 
select "Upload Package File" tab
then "browse for file"
doubleclick the extension (confirmed compatible"

### Expected result

I expected to see some feedback that something was happening - percent counter or progress bar

### Actual result

Nothing. The administrator panel is there, but no feedback of any kind

### System information (as much as possible)

PHP 7.4.2 
Linux VPS / Apache
Joomla 4.0.0
Mozilla 5.0 (Firefox)

### Additional comments

I like it a lot so far!

**Comment by PhilETaylor** [comment]
Upload progress in PHP is fraught with issues on mass hosting servers and so unreliable as to not be implemented in pretty much any mass market software like Joomla - the requirements and prerequisites are mostly out of Joomla's hands. https://www.php.net/manual/en/session.upload-progress.php - Upload speeds vary (I have 1Gbps upload) and so you might not even see this progress bar even if implemented (plus the reasons in the linked article) 

Once the zip file is uploaded, extracting and redirecting is normally very quick also - depending on your webhost, and constantly "asking Joomla to report the installation status" would actually slow down the installation as the webhost would have to run checks and respond back to that check request. Again this would depend on lots of factors outside of the control of Joomla and would rely on a well configured webhost. 

Uploading and installing should take no longer than a few seconds at max.

**Comment by richard67** [comment]
Closing as duplicate report. See https://github.com/joomla/joomla-cms/issues/35008 . A simple search for keywords "progress" and "extension" has shown that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35283">issues.joomla.org/tracker/joomla-cms/35283</a>.</sub>
