### ISSUE TITLE
[4] Prohibited input U+00000024

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35298]
### Steps to reproduce the issue

Attempt to create a new contact in Joomla admin when providing the website address as "£$" (not just one or the other, but this exact string)

### Expected result

URL Fails validation with normal red banner error message

### Actual result

Unhelpful non-user friendly error message. 

Punnycode Helper exception thrown is not handled

<img width="1601" alt="Screenshot 2021-08-22 at 17 25 59" src="https://user-images.githubusercontent.com/400092/130362624-825d0585-d0b3-4640-8b10-df85de35e96e.png">

### Additional comments

Note that when using the same `£$` in other URL fields in Joomla Admin - such as in the banners component, this error is not shown.

**Comment by dgrammatiko** [comment]
> Punnycode Helper exception thrown is not handled

Client-side or server-side Punnycode Helper? I mean were the form expected to punycode encode the input's string or this is a php side problem? Or both?

**Comment by PhilETaylor** [comment]
This uncaught error is PHP side. Although to get to PHP side it already passed any (is there any!?) JS validation for urls.

**Comment by dgrammatiko** [comment]
> is there any!?) JS validation for urls

There's some unusable validation script but it only uses Punycode for emails: https://github.com/joomla/joomla-cms/blob/173ac7db15a3d2dc3483cd299095cf9d26851b88/build/media_source/system/js/fields/validate.es6.js#L33-L37

Also most of the time it doesn't do anything more than informing the user of required inputs without value...

**Comment by PhilETaylor** [comment]
```
<input type="url" inputmode="url" name="jform[webpage]" class="form-control valid form-control-success" id="jform_webpage" value="" size="30" aria-invalid="false">
``

Strange that HTML type `url` allows the entry of and form submission of a value of `£$`

**Comment by ch2856** [comment]
Why the issue is closed if the issue is still here? can't create new user " Prohibited input U+0000202C"

**Comment by chmst** [comment]
"Prohibited input" is not a Joomla message, do you have an extension?

**Comment by brianteeman** [comment]
The issue is closed only because the original submitter closed it.

It is a valid issue and can be replicated as reported.

@chmst the error message is coming directly from the library as shown in the original screenshot
