### ISSUE TITLE
[4] Impossible to edit contacts/articles on the frontend unless there is a menu item

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35296]
### Steps to reproduce the issue

4.0-dev
Create a contact in the backend
Login to the frontend as a super admin and go directly to 

http://example.com/index.php/component/contact/category/uncategorised?Itemid=101

see: 
<img width="826" alt="Screenshot 2021-08-22 at 16 49 09" src="https://user-images.githubusercontent.com/400092/130361496-5bc2a9ca-233f-420e-9712-5b376f3dbf59.png">

Click Edit

### Expected result

Edit form populated with the item detail.

### Actual result

Edit form not populated, because `getInt` is converting `philtaylor` to 0 and not pre-converting the slug to the id. 

NOTE THAT IF YOU: Add a menu item, "List Contacts in a category" to a menu, _then the edit button will then work_.  **However the edit button SHOULD be able to be used without a menu item being published in the menu.  There is no point displaying an edit button that cannot be used.** 

Same thing happens with articles, if there are no menu items that point to com_content, then the edit button just loads a blank form and not the edit form for the article whose edit button you clicked.

The expectation is that you should not need menu items published, just to use edit buttons that are displayed to you.

**Comment by brianteeman** [comment]
Confirmed
