### ISSUE TITLE
Workflows - stages with „unpublished“ article status can’t be selected 

### ISSUE THREAD

**Issue by alve89** [joomla/joomla-cms#35300]
### Steps to reproduce the issue
I’m having a workflow with three stages
![873B32AF-FB39-4D0F-B252-3CD76252CAEB](https://user-images.githubusercontent.com/11487054/130363075-def0aa2a-dce6-4b1f-a7e1-ccdc21c7a526.jpeg)

and two transitions
![FE1C6BE6-C86D-4704-8231-5356036F1777](https://user-images.githubusercontent.com/11487054/130363217-963c9d55-3028-46fd-86ba-954ff3610679.jpeg)

But in the configuration of the second transition I can’t choose the stage _Geprüft - Überarbeitung nötig_, probably because the articles status within this stage is Unpublished.
![0C94E895-9DE4-4588-B121-5F3923B34A1E](https://user-images.githubusercontent.com/11487054/130365609-597373a7-843b-4c52-a8f7-28487bd4b34a.jpeg)

### Expected result

After creating a new article and using the stage _Neu - zur Prüfung einreichen_, which means the article is new and shall be checked, an authorized user (group Publisher) should have two options:
Either the article is approved and can be published, so it is _Geprüft - Freigabe_, or it has to be corrected, so it is not approved and can’t be published (_Geprüft - Überarbeitung nötig_).

### Actual result
But now you can’t “decline” an article and for example return it in the Writing / Editing department - currently  the next step has to be Published (at least a stage with the configured article status Published), which is quite restrictive and doesn’t allow covering possible scenarios. 

### System information (as much as possible)
Joomla ‎4.0.0-rc1

**Comment by wilsonge** [comment]
Isn't it because the stage itself is unpublished? Rather then the status of the article

**Comment by bembelimen** [comment]
> 
> 
> Isn't it because the stage itself is unpublished? Rather then the status of the article

That's the reason, probably we should still offer disabled stages?

**Comment by brianteeman** [comment]
then there would be no point in having enable/disable funtionality

**Comment by bembelimen** [comment]
The transition(s) targeting this stage wouldn't be available then

**Comment by alve89** [comment]
> Isn't it because the stage itself is unpublished? Rather then the status of the article

You’re right, my bad! As I saw in the video of Joomla Day 19 I thought this would be the link between the articles status and the stages. As that’s obviously wrong - aren’t there the conditions anymore?

**Comment by bembelimen** [comment]
> > Isn't it because the stage itself is unpublished? Rather then the status of the article
> 
> You’re right, my bad! As I saw in the video of Joomla Day 19 I thought this would be the link between the articles status and the stages. As that’s obviously wrong - aren’t there the conditions anymore?

No, this was in the old workflow which was more like a publishing workflow, which means you couldn't manage much more than the publishing states. There were then over the last year a lot of improvements and changes which made the workflow to a real one with much more flexibility and functions.

The conditions are removed and the transitions are now the most important part to set up the changes.

**Comment by alve89** [comment]
Alright, then I just misunderstood that. I'll close this issue now because my initial problem is solved. Thank you guys!

**Comment by alve89** [comment]
Actually I don't find any solution for the following:

User A (author) creates a new article and sets the default stage _Zur Prüfung einreichen_ (he can't choose anything else)
![image](https://user-images.githubusercontent.com/11487054/130405444-8a2693ba-7c72-4730-b136-96113e2dfffd.png)

Then the article has the default stage. Since no transition was triggered, no notification was sent to any users. How would publishers know that there are new articles without any notification?

**Comment by chmst** [comment]
This is a valid point. Could you open this as a new issue, please? Then it is easier fur us to maintain.

**Comment by brianteeman** [comment]
The cause of this is the same as the one reported here.
https://github.com/joomla/joomla-cms/issues/29942

**Comment by alve89** [comment]
@brianteeman I can't see any relation here - did you perhaps mixed up my other issue (#35308) to link it with your #29942?
@chmst I'll do if I'm right with my previous written assumption - just to avoid duplicates. Thanks for your quick reply!

**Comment by brianteeman** [comment]
sorry - removed that comment and put it in the correct place.

**Comment by bembelimen** [comment]
> 
> 
> Actually I don't find any solution for the following:
> 
> User A (author) creates a new article and sets the default stage _Zur Prüfung einreichen_ (he can't choose anything else)
> ![image](https://user-images.githubusercontent.com/11487054/130405444-8a2693ba-7c72-4730-b136-96113e2dfffd.png)
> 
> Then the article has the default stage. Since no transition was triggered, no notification was sent to any users. How would publishers know that there are new articles without any notification?

Creating an article is not using the workflow. If the article is created in the frontend, then you can setup the Joomla! plugin to inform admins. If the article is created in the backend, there is no messaging will a transition is executed. (But that didn't change from 3.x...)
