### ISSUE TITLE
Clicking on Menu item sometime not going to “Edit” mode & no “Edit” action when selected.

### ISSUE THREAD

**Issue by Chacapamac** [joomla/joomla-cms#35301]
### Steps to reproduce the issue
Happen in Firefox 92.0b6 (64-bit) and also Chrome Version 92.0.4515.159 
Seem to happen sometimes on a refresh of page, not predictable.

### Expected result
Opening the menu item “Edit” Mode

### Actual result
Nothing Happen even if you have the visual click/over happening

### System information (as much as possible)
Apple Sierra
PHP Built On	Darwin iMac.local 16.7.0 Darwin Kernel Version 16.7.0: Sun Jun 2 20:26:31 PDT 2019; root:xnu-3789.73.50~1/RELEASE_X86_64 x86_64
Database Type	mysql
Database Version	5.7.32
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	Yes
PHP Version	7.4.12
Web Server	Apache/2.4.46 (Unix) OpenSSL/1.0.2u mod_fastcgi/mod_fastcgi-SNAP-0910052141 mod_wsgi/3.5 Python/2.7.13 mod_perl/2.0.11 Perl/v5.30.1
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 4.0.0 Stable [ Furaha ] 17-August-2021 12:30 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36

### Additional comments

I think that when a menu item is selected, an “Edit” link should appear under the “Actions” roll down choice. It make no sense to not include as it is one of the main “Actions” users will want to do?![screen shot 2021-08-22 at 17 35 26](https://issues.joomla.org/uploads/1/09668028813a4caa733340f615b282d7.gif)

**Comment by PhilETaylor** [comment]
the green flash in your animation is you starting a drag operation. Be sure to keep the mouse still when clicking.

**Comment by PhilETaylor** [comment]
Are you using a standard mac mouse? Any adaptive input controls?

**Comment by PhilETaylor** [comment]
A workaround for you if you are having issues keeping the mouse still, would be to order your list table by another column, for example click ID once to sort by the ID column, this disabled drag/drop features for reordering.

**Comment by Chacapamac** [comment]
Using a standard mouse.
I just try to not move at all and yes, It seem to work.
My tracking speed is to the max

I think we find the problem thank you. Solved for me.

**Did you see my additionnal comments, I think its important**
“I think that when a menu item is selected, an “Edit” link should appear under the “Actions” roll down choice. It make no sense to not include as it is one of the main “Actions” users will want to do?”
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35301">issues.joomla.org/tracker/joomla-cms/35301</a>.</sub>

**Comment by PhilETaylor** [comment]
I remember commenting about that a long time ago, and there was a reason that edit is not listed in the actions - I cannot remember why now, but it's a purposeful decision that was made :-(

**Comment by PhilETaylor** [comment]
For the record I also have my mac mouse at full fast tracking speed and I've not experienced the drag, unless my CPU is maxed out at 100% cpu doing something else (normally docker builds building in the background) and mac is already a bit laggy

**Comment by Chacapamac** [comment]
> I think that when a menu item is selected, an “Edit” link should appear under the “Actions” roll down choice. It make no sense to not include as it is one of the main “Actions” users will want to do?

I personally see that as an interface error. “Edit” is an “Action” that you want to do with selected menu items, even if you can just click on the menu item link to do so.

My logic is:
You have an “Actions” menu and for no reasons Actions should be taken out of it. It defeat the purpose to have the Select > Actions menu > Choice sequence...

You can close this, if you want....

**Comment by richard67** [comment]
@Chacapamac Has your issue been resolved? If so, please close it. If you want to have more opinions on your suggestion about an extra edit link, please Open a new item in „Discussions“. Thanks in advance.

**Comment by Chacapamac** [comment]
No problem, Closed

**Comment by Chacapamac** [comment]
Good Day to All.
