### ISSUE TITLE
[4.0] Compile LESS button missing!

### ISSUE THREAD

**Issue by wamk9** [joomla/joomla-cms#35303]
Hi everyone!

I update my Joomla to 4.0 Stable, but when i go to template edit on this version i don't have "Compile Less" Button on my application.

![image](https://user-images.githubusercontent.com/5170693/130369575-07f3baea-7a85-4853-9904-c5e085c72ccf.png)

Anybody can help-me and tell when is this button or what i do now?

**Comment by HLeithner** [comment]
We removes the less compiler in j4 for 2 reasons.

Joomla switched to scss and the less compiler was out of date.

So you have to compile your less on your local machine and upload the CSS file.

**Comment by RickR2H** [comment]
There is some good documentation on Joomla 4 and the use of SCSS. https://docs.joomla.org/J4.x:SCSS_and_Sass/en<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35303">issues.joomla.org/tracker/joomla-cms/35303</a>.</sub>

**Comment by dgrammatiko** [comment]
> There is some good documentation on Joomla 4 and the use of SCSS. docs.joomla.org/J4.x:SCSS_and_Sass/en

All the commands in that doc are **wrong**

eg 
> You can compile all Joomlaǃ core css files with the command `node build --compile css`

should be 

> You can compile all Joomlaǃ core css files with the command `npm run build:css` or if someone needs to build a specific folder: `npm run build:css -- templates/cassiopeia/scss` or if they want to watch a folder: `npm run watch -- templates/cassiopeia/scss`

**Comment by RickR2H** [comment]
@dgrammatiko Do you know who is responsible for this documentation? If it's wrong it needs to fixed asap as many people are going to use the Cassiopeia as stating point. Is the REDME.md in the build folder up to date? Maybe we should add a reference to this file?

**Comment by dgrammatiko** [comment]
>  Is the REDME.md in the build folder up to date

Yes

> Maybe we should add a reference to this file?

and yes

> Do you know who is responsible for this documentation?

No

**Comment by PhilETaylor** [comment]
> Do you know who is responsible for this documentation?

Its a wiki. You/We/They are all responsible for its content ;-) 

Here is a list of previous contributors https://docs.joomla.org/index.php?title=J4.x:SCSS_and_Sass&action=history

You can edit the page by selecting Edit from the Actions menu https://docs.joomla.org/index.php?title=J4.x:SCSS_and_Sass&action=edit

**Comment by RickR2H** [comment]
@PhilETaylor Thanks! I'll try to update the parts that are wrong... Someone has got to do it 😉

**Comment by brianteeman** [comment]
This should be closed

**Comment by HLeithner** [comment]
Expected behavior because we removed less support in j4.
