### ISSUE TITLE
Joomla 3.10.0 causing a problem for  auto image rotation in Articles (Blog options)

### ISSUE THREAD

**Issue by junstx** [joomla/joomla-cms#35304]
### Steps to reproduce the issue
Update Joomla from 3.9 to 3.10. Reboot the site and go to any article pages with gallery function (images in featured section of a page or . 
In Joomla 3.9, Gallery images rotates automatically or by clicking right and left arrow.  
In Joomla 3.10, Gallery images adds texts(previous and next).Gallery images does not rotate (forward or rewind images halts). Upon clicking previous or next button over the image, nothing but a page shifts slightly upward a

I am running WAMP locally but this happened on the production server (Linux box5205.bluehost.com 4.19.150-76.ELK.el6.x86_64 with PHP7.3.29![screen shot 2021-08-22 at 23 20 32](https://issues.joomla.org/uploads/1/cf7f91d2be931c968770bb8efc4b6138.jpg))as well.

### Expected result
Images rotates at set interval and there should not by any stoppage. You can forward or rewind images by clicking right or left arrow at will.

### Actual result
Images stops rotating and do not do anything even if clicking right or left arrow.

### System information (as much as possible)
Setting	Value
///local setup 
PHP Built On	Windows NT WINDOWS-10JS 10.0 build 19042 (Windows 10) AMD64
Database Type	mysql
Database Version	5.7.31
Database Collation	utf8mb4_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.4.9
Web Server	Apache/2.4.46 (Win64) PHP/7.4.9
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.10.0 Stable [ Daraja ] 14-August-2021 11:55 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36
End of Local setup///

**Comment by junstx** [comment]
P.S. I roll back to 3.9 from 3.10.0 on production server and everything is working normal.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35304">issues.joomla.org/tracker/joomla-cms/35304</a>.</sub>

**Comment by joomdonation** [comment]
Hello

For this, you should contact the developer of the gallery extension and ask him to check it. This is not something in Joomla core, so we could not help
