### ISSUE TITLE
[4] "Install from Web" is missing UI parts for a correct UX

### ISSUE THREAD

**Issue by simbus82** [joomla/joomla-cms#35319]
### Steps to reproduce the issue
Go to "Install from Web", try to understand where to click

### Expected result
1. Clear visual information about which link is and External Links
2. A clear CTA to open the modal
3. A rapid link to "install" action

### Actual result
![image](https://user-images.githubusercontent.com/1375730/130461874-d84d7130-a95d-485e-95cf-5ea5825df713.png)

1. Link are not underlined and the bold of text "hide" the presence of the "external link" icon. The external link is in the top of the "extension" block, so for a user it is the first thing to click. 
2. The block doesn't have a hover; a button with a clear Call-To-Action (Detail, Info, More, atc) is not here to invite the user to click.
3. A rapid action to Install in one-click the known extension is missing.

### Additional comments
I think this page must be restyled to let "new adopters" feel comfortable.

**Comment by PhilETaylor** [comment]
This even trips up people like me. Probably best to post on the install from web project (which is separate to the main joomla/joomla-cms project) 

https://github.com/joomla/install-from-web-server/issues

**Comment by simbus82** [comment]
Thanks @PhilETaylor, you are right. I re-post it in the right project.
