### ISSUE TITLE
[4.0] [Cassiopeia] Template too large logo

### ISSUE THREAD

**Issue by mariantanase** [joomla/joomla-cms#35314]
### Steps to reproduce the issue
Step 1. On Dashboard > System > Site Template Styles > Cassiopeia - Default > Advance tab
Step 2. Select a 75x75 px immage for logo
Step 3. Save&Close

### Actual result
On frontend it shows a 18rem logo !
It seems that what causes this issue is a template class "container-header .navbar-brand img", who broken the immage.

![Screenshot 2021-08-23 at 14-21-05 Home](https://user-images.githubusercontent.com/3976174/130447381-e754d020-f9c0-43d7-9b49-f23d8ab9c233.png)

### System information (as much as possible)
Joomla 4.0.0 stable
PHP 7.4.13

### Additional comments
Questions:
1. Can be fix this ?
2. Why isn't possible to have both (logo and title) ?

**Comment by drmenzelit** [comment]
The standard Cassiopeia logo is a svg, that is why the width for the img element was given. We need to check if it is possible to change it.
Temporary you can create a user.css file and change the values here:

`.container-header .navbar-brand img {
    width: 18rem;
    min-width: 18rem;
}`

You can use the tagline to add a line of text below the logo.

**Comment by RickR2H** [comment]
@drmenzelit Maybe it is an option to add the image sizes to the SVG itself and remove the fixed width and height from the template? If an image is then added to the header, the width and height of the image is respected. Whats your opinion on this? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35314">issues.joomla.org/tracker/joomla-cms/35314</a>.</sub>

**Comment by drmenzelit** [comment]
That could be an option, we have to test it :-)

**Comment by RickR2H** [comment]
I'll try to make a PR.

**Comment by RickR2H** [comment]
@mariantanase If you want text next to the logo, add text to the tag line and add the following code to the user.css:

```
.navbar-brand {
  display: flex;
}
```

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35314">issues.joomla.org/tracker/joomla-cms/35314</a>.</sub>

**Comment by richard67** [comment]
Closing as having a pull request. Please test #35337 . Thanks in advance.

**Comment by RickR2H** [comment]
@mariantanase Please test the PR #35337 
we need 2 successful tests before it can be added.
