### ISSUE TITLE
Versioning in custom modules...

### ISSUE THREAD

**Issue by ThiloSO** [joomla/joomla-cms#35313]
Feature Request:

The nice function "versions" which is accessible through each article would also be great for custom modules...

Any thoughts about that?

Greets

**Comment by PhilETaylor** [comment]
Currently Modules do not implement the Versionable trait and therefore this is currently not possible. 

This should be moved to [Discussions](https://github.com/joomla/joomla-cms/discussions) as is a feature request and not a bug.
