### ISSUE TITLE
9 ideas to turn a dull and boring informative speech into a highly engaging one - 2021 Guide

### ISSUE THREAD

**Issue by astridhorton90** [joomla/joomla-cms#35328]
9 ideas to turn a dull and boring informative speech into a highly engaging one - 2021 Guide[9 ideas to turn a dull and boring informative speech into a highly engaging one.pdf](https://issues.joomla.org/uploads/1/df795cf3fe94caa096edf35798fe9d5c.pdf)

**Comment by PhilETaylor** [comment]
Spam can be closed
