### ISSUE TITLE
[4.0.0] None Transparent Icons

### ISSUE THREAD

**Issue by je1977** [joomla/joomla-cms#35334]
### Steps to reproduce the issue
go to com_joomlaupate in the backendand start the updateprocess

### Expected result
transparent icons

### Actual result
none transparent icons![screen shot 2021-08-24 at 08 54 51]

![None Transparent Icon](https://issues.joomla.org/uploads/1/f037df91fe1c3da2082485cdf1b5948a.gif "None Transparent Icon")

### System information (as much as possible)
Joomla 4.0.0 Local Installation with no external Plugins

**Comment by brianteeman** [comment]
I thought I had a fix for this but I just realised that if you remove the white background then the icon is impossible to see on the dark blue (especially the spinner)

**Comment by PhilETaylor** [comment]
Fixed in [4] Fix spinner bg #35339

**Comment by brianteeman** [comment]
Can be closed as there is a PR for testing

**Comment by alikon** [comment]
please test #35339
