### ISSUE TITLE
[4.0] loader image has white rotating background in pre-install check

### ISSUE THREAD

**Issue by regularlabs** [joomla/joomla-cms#35335]
![image](https://user-images.githubusercontent.com/13553242/130589177-0b01b80c-2203-48c4-aae0-d6f2c93e90f3.png)

Yes, also happens in Joomla 4.0.1

**Comment by brianteeman** [comment]
Not saying its correct but all the icons there have a white background

![image](https://user-images.githubusercontent.com/1296369/130590459-5724ad0c-2d5e-423f-8c70-150ec9b873b3.png)

![image](https://user-images.githubusercontent.com/1296369/130590462-664a44be-111d-4e71-a0e5-447f23409502.png)

**Comment by regularlabs** [comment]
Which doesn't look bad if it isn't rotating...
![c00qv](https://user-images.githubusercontent.com/13553242/130593258-84b0fb4b-681f-4e0e-b909-3359715cb105.gif)

**Comment by PhilETaylor** [comment]
Duplicate https://github.com/joomla/joomla-cms/issues/35334

**Comment by PhilETaylor** [comment]
Fixed in [4] Fix spinner bg #35339
