### ISSUE TITLE
[4] Label and description not clear in configuration

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#35349]
### Steps to reproduce the issue
Global configuration

![grafik](https://user-images.githubusercontent.com/1035262/130655693-adaf5624-8e56-45b9-89b3-60518753f9c9.png)

The description is not clear - what is logged with "no" and what with "yes"?

**Comment by simbus82** [comment]
Usually in the softwares the logging is "fully" activated and then the user is given the choice to disable the logging of something that could be too verbose or not very informative.

Here it is not just a matter of the label and description, but it is an issue of the intended behaviour for those switches.

The most "user understandable" solution, is to have a "master Log Switch" ex. "Logging Enabled", while the second switch should say "Disable logging of deprecated API".

**Comment by brianteeman** [comment]
please test #35733

**Comment by alikon** [comment]
test #35733
