### ISSUE TITLE
Important but easy improvements to the code of the articles

### ISSUE THREAD

**Issue by impressionestudio** [joomla/joomla-cms#35342]
I write below a list of simple but useful improvements to the HTML code of an article in order to expand its usability to the needs of today (CSS grid).

I created a demo article having a title, image, main text, article information and two custom fields before and after the main text.

![Demo article](https://demo.impression-estudio.gr/_issue-tracker/demo-article.jpg "Demo article")

### 1. BETTER PLACEMENT OF THE  CUSTOM FIELDS

The custom fields: 
- must be placed outside the ul/li elements, 
- must be placed on the same level as the main content, the title and the image 
- and must be placed inside divs. 

(The custom fields may contain large texts, images, links, video players, photo galleries etc. So it is not good to be placed in ul/li elements.)

So the code for a custom field should change from: 
```
<ul class="fields-container">
	<li class="field-entry city">
		<span class="field-label ">City: </span>
		<span class="field-value city">Athens</span>
	</li>
</ul>
```

to: 

```
<div class="field-entry city">
	<span class="field-label ">City: </span>
	<span class="field-value city">Athens</span>
</div>
```

The code for the article part with the above changes is:

![Custom fields code after the improvements](https://demo.impression-estudio.gr/_issue-tracker/custom-fields-after.jpg "Custom fields code after the improvement")

### 2. BETTER NAMES TO CLASSES

There is some inconsistency in the names of the CSS classes as it concerns the code of an article. 
The class names:
- should be smaller
- should have a common logic

Specifically: 
1. The class “page-header” should be renamed to “title” since it represents the title field of an article.
2. The class “item-image” should be only “image”. No need to use “item” since we don’t use it anywhere else in the rest class names.
3. The class “com-content-article__body” is big. Maybe only “body” or “content” since it refers to the “Content” field of an article is better.
4. The class “field-entry” should be renamed to “field” or “custom-field”.
5. The class “article-info” should be renamed to “info”. The “article-“ part is redundant/obvious.
6. The class “article-info-term” could change to “info-title”.
7. The class “category-name” witch is part of the article information should be simply “category” since for example the class “published” is not “published-date”.

### 3. ARTICLE INFO

The article info code should be organized better:
1. The labels of the article information like “Written by:” or “Category:” or “Published:” should be place in their own span elements 
2. They should have a specific class name “info-label” similar to “field-label” in the custom fields.
3. The article info values should have a specific class name “info-value” similar to “field-value” in the custom fields.

So the code should change from:

![Article info code before the changes](https://demo.impression-estudio.gr/_issue-tracker/article-info-before.jpg "Article info code before the changes")

to: 

![Article info code after the changes](https://demo.impression-estudio.gr/_issue-tracker/article-info-after.jpg "Article info code after the changes")

I wish the Joomla developers will agree with the above ideas.

Thank you!

**Comment by ReLater** [comment]
Regarding "2. BETTER NAMES TO CLASSES". Joomla 4 uses at many places BEM nomenclature. http://getbem.com/naming/ . That was a deliberate decision.

**Comment by simbus82** [comment]
Agree with the proposal, escluding point 2 where the naming could be improved but not int that way.

**Comment by RickR2H** [comment]
Why not make a pull request? Just fork the Joomla repo and add your proposed changes so people can test and add comments.

**Comment by jwaisner** [comment]
Adjusting priority to reflect proposal.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35342">issues.joomla.org/tracker/joomla-cms/35342</a>.</sub>

**Comment by EJBJane** [comment]
Thank you, this is super important to me as a designer. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35342">issues.joomla.org/tracker/joomla-cms/35342</a>.</sub>

**Comment by chmst** [comment]
@EJBJane I understand perfectly that every designer wants his or her own css classes and his or her own layout. Why not make a template override?

**Comment by impressionestudio** [comment]
> @EJBJane I understand perfectly that every designer wants his or her own css classes and his or her own layout. Why not make a template override?

Because the changes I suggest are useful for the most cases. It is better to have a code that needs override in 1 out of 10 times, not 9 times out of 10.

On the other side, as it is now and mostly the custom fields which are "locked" inside a ul/li element are completely hard to make good use of them and every time someone uses a couple of custom fields he/she needs to create an override. 

Custom fields have the same importance as the description text (content in J4) so they shouldn't be separated like the article info details.

After all, the proposed code will slightly affect the appearance of the article with custom fields and article info details from the way it is now. Custom fields will continue to be placed before and after the description text and will continue to be one below the other. The only difference is that will not be in a ul/li element but only each custom field in a div.

**Comment by EJBJane** [comment]
> @EJBJane I understand perfectly that every designer wants his or her own css classes and his or her own layout. Why not make a template override?

Because I am thinking the average user doesnt know how to make overrides? I wouldn't ask an average WP user to create overrides.

**Comment by EJBJane** [comment]
Because the changes I suggest are useful for the most cases. It is better to have a code that needs override in 1 out of 10 times, not 9 times out of 10.
Agree

**Comment by chmst** [comment]
@impressionestudio could you make a PR? Integrating custom fields surely can be improved.

> @EJBJane I wouldn't ask an average WP user to create overrides. 

This is Joomla.

**Comment by impressionestudio** [comment]
> @impressionestudio could you make a PR? Integrating custom fields surely can be improved.

I intend to do a PR but needs more time. I am not used to PRs.

**Comment by chmst** [comment]
Thank you! If you need support, don't hesitate to ask.

**Comment by impressionestudio** [comment]
Ok. Thanks.

**Comment by EJBJane** [comment]
> @impressionestudio could you make a PR? Integrating custom fields surely can be improved.
> 
> > @EJBJane I wouldn't ask an average WP user to create overrides.
> 
> This is Joomla.

Yes, I do realize that.  ;-)  What's a PR?

**Comment by alikon** [comment]
stand for Pull Request

**Comment by EJBJane** [comment]
> stand for Pull Request
Ok thanks..never done one.

**Comment by ghost** [comment]
>  Ok thanks..never done one.

@EJBJane if you wanna create a PR: [My first pull request to Joomla! on Github](https://docs.joomla.org/My_first_pull_request_to_Joomla!_on_Github)

**Comment by impressionestudio** [comment]
I read the instructions for creating a PR. I remember it is the second time I read the instructions and the conclusion is the same: 
I am not going to install all these tools just for suggesting a few changes in some code. I know that everybody uses GitHub, but I don't like it, I don't use it, I don't like Java (Eclipse) and all these steps described are too much for me. So if you are going to accept the simple way of suggesting code changes, then I can continue. If not, then no problem, we can all forget this "issue".

**Comment by zero-24** [comment]
@impressionestudio simpler changes can be done without external tools and only the GitHub UI: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by impressionestudio** [comment]
Please do not curse me. It is the first time I use Github.

The above changes have to do with better names on classes, following the BEM approach and removing some redundant classes.
A few changes remain in order this issue to be completely satisfied, but I will remain for a response from the experts before I continue.

**Comment by impressionestudio** [comment]
How may I know if somebody will take a look at the suggested improvements and if they will be accepted?

**Comment by RickR2H** [comment]
@impressionestudio There has to be a pull request with the suggested code changes that can be tested. The easiest way to go if you want to change one file is via Github itself. please read: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests/en

The other option is to clone the repo in your own account, make the changes and the do a PR. Please read: https://opensource.com/article/19/7/create-pull-request-github

After two successful tests, the project team will decide if it will be added to the code base.

Hope that helps a bit.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35342">issues.joomla.org/tracker/joomla-cms/35342</a>.</sub>

**Comment by alikon** [comment]
@EJBJane & all
please test:
#35796, #35797, #35798, #35799, #35800, #35801, #35802, #35803, #35804, #35805, #35806, #35807

**Comment by Fedik** [comment]
@impressionestudio  please merge [all that changes in 1 pull request](https://opensource.com/article/19/7/create-pull-request-github), and then we can review it.

**Comment by Fedik** [comment]
@impressionestudio addittionaly, if you want to have an extra class, better add new to existing, this way it will not make hard time for templates.

And please check what @laoneo comment https://github.com/joomla/joomla-cms/pull/35807#issuecomment-940208571

**Comment by impressionestudio** [comment]
@RickR2H Thank you for the guidance.

@Fedik Ok, I will add the new classes along with the existing ones in order not to brake templates. (I believe that in later versions of Joomla 4 the old classes will be removed.)

I will try to merge all the pull requests to one and add also the code changes in order the issue to be completely covered by this one pull request.

**Comment by Fedik** [comment]
@impressionestudio thanks, and please not forget to look this RFC #15279, @ciar4n have made a big work to make classes more consistent.

**Comment by brianteeman** [comment]
This should be closed for the reasons stated by @bembelimen https://github.com/joomla/joomla-cms/pull/36557#issuecomment-1019125779
