### ISSUE TITLE
[4] Multiple 4.0.0 to 4.0.1 downloads are not available 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35340]
Posting here for quicker response. 

The following files are not available for the public to download on download.joomla.org - all others seem to work. 

My geographic region is either Paris France or London, depending on the wind. 

Others reported in Joomla forum and Twitter. 

 Note that the file sizes also look suspect

<img width="688" alt="Screenshot 2021-08-24 at 11 17 01" src="https://user-images.githubusercontent.com/400092/130600024-8850a604-2576-4bf8-b5d2-c14bb37c539b.png">

They all result in a AWS message

```xml
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>
joomladownloads/joomla4/Joomla_4-0-x_to_4-0-1-Stable-Patch_Package.tar.bz2
</Key>
<RequestId>B7J5X425NWEG2JHF</RequestId>
<HostId>
m27WU2gsqRWILsSoEb8gyqIx2UYCSglhTCqflyXqQENnBZfapV25hPx5oQtvJi/ZniB2F2nwGh8=
</HostId>
</Error>
```

**Comment by PhilETaylor** [comment]
@wilsonge

**Comment by brianteeman** [comment]
isnt that because you asked for the release to be removed?

**Comment by PhilETaylor** [comment]
No.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/35331#issuecomment-904412870

**Comment by PhilETaylor** [comment]
<img width="324" alt="Screenshot 2021-08-24 at 11 31 00" src="https://user-images.githubusercontent.com/400092/130601672-2aa8ac06-a74a-4587-858c-67aa8c22a6b2.png">

**Comment by PhilETaylor** [comment]
And to be clear - this only effects SOME of the links - not all of them.

**Comment by zero-24** [comment]
@PhilETaylor should be fixed now please confirm on your side.

**Comment by PhilETaylor** [comment]
I'm mobile at the moment - the links seem to work but the file sizes are still reported wrong. I'm unable to compare the hashes on mobile maybe those are based on the wrong size file too, best to check them too when fixing file size issue

![image](https://user-images.githubusercontent.com/400092/130608623-7c352b8c-8934-4dfa-9918-85769ff12229.png)

**Comment by Bond97** [comment]
@zero-24 on my side - I can't update my testing Joomla site from 4.0.1-dev to 4.0.2-dev, it will show this error

![изображение](https://user-images.githubusercontent.com/78050514/130608839-404b1e24-1a1c-41c0-b3fe-feb1002c5835.png)

Maybe zip files isn't available or not updated xml file https://update.joomla.org/core/nightlies/next_patch_list.xml

**Comment by PhilETaylor** [comment]
That is unrelated. That's related to the bug in 4.0.1 restore.php that is fixed by 4.0.2

**Comment by zero-24** [comment]
Yes as noted by @PhilETaylor once 4.0.2 is out there will be a dedicated update package provided for 4.0.1 installs to patch the updater so you later can go to 4.0.2 using the patched updater: https://docs.joomla.org/J4.x:Update_from_4.0.1_to_4.0.2 

But that package nor 4.0.2 is ready yet.

**Comment by PhilETaylor** [comment]
> But that package nor 4.0.2 is ready yet.

But that package FOR 4.0.2 is NOT ready yet.

**Comment by zero-24** [comment]
> I'm mobile at the moment - the links seem to work but the file sizes are still reported wrong. I'm unable to compare the hashes on mobile maybe those are based on the wrong size file too, best to check them too when fixing file size issue

Ok I have run the hashes script again that should have fixed the size issue and hashes too.

**Comment by wilsonge** [comment]
If anyone gets time to figure out what went wrong in my script here that would be awesome https://github.com/joomla/downloads.joomla.org/blob/master/cli/ars-create-cms-release.php cause i'll need to use it again this evening for 4.0.2. @zero-24 mentioned it was hyphens vs fullstops in the file name or similar

**Comment by zero-24** [comment]
That should do the trick: https://github.com/joomla/downloads.joomla.org/pull/275

**Comment by PhilETaylor** [comment]
Is there an attributable reason why that changed? has this not been used for all the releases other than this time?

**Comment by zero-24** [comment]
> Is there an attributable reason why that changed? has this not been used for all the releases other than this time?

The script has only been used for the 4.0.0 and 4.0.1 releaes

**Comment by PhilETaylor** [comment]
Nevermind - I see its new https://github.com/joomla/downloads.joomla.org/commit/d5486a0a04b209974657d39b575e92d5b319e74a

**Comment by wilsonge** [comment]
Yup we’ve done direct DB inserts until now 🤷‍♂️
