### ISSUE TITLE
Never ending "Extensions Pre-Update Check" when try to update from 4.0.0 to 4.0.1

### ISSUE THREAD

**Issue by simbus82** [joomla/joomla-cms#35351]
### Steps to reproduce the issue
Install Joomla 4.0.0.
Go to Joomla Update component, wait the pre-update checks

### Expected result
"Extensions Pre-Update Check" ends the tests and let me able to update Joomla 4.0.0 to 4.0.1

### Actual result
![image](https://user-images.githubusercontent.com/1375730/130660600-de1aaa94-592a-47e2-be6d-dc8bb4162860.png)

_Message: Warning, Pre-Update checks have not been completed yet - please wait._

I receive a Console Error too and the "Extensions Pre-Update Check" never ends to "spin" (waited 10 minutes).

### System information (as much as possible)
![image](https://user-images.githubusercontent.com/1375730/130660794-86941391-950f-4227-a02d-ae29487ad3ce.png)

### Additional comments
It's a "vanilla" installation with Blog Demo data installed.
Forcing the update, everything works fine.

**Comment by PhilETaylor** [comment]
Go to:

https://example.com/administrator/index.php?option=com_joomlaupdate&task=update.fetchextensioncompatibility&joomla-target-version=4.0.1&joomla-current-version=4.0.0-dev&extension-version=4.0.0&extension-id=216

What is shown?

**Comment by zero-24** [comment]
@simbus82 This is an issue with 4.0.0 and has been patched by 4.0.1 but please wait for 4.0.2 and go directly from 4.0.0 to 4.0.2. That warning should not block you from updating.

**Comment by alikon** [comment]
as 4.0.2 is out we i'll close this one
