### ISSUE TITLE
[4] Live Update is not available

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35353]
Something is NOT available. 

Too scary language when really we dont want a negative here, we want a positive, enticing people to carry on reading to update the component because live update is available, they just first need to update the component. 

Also "Live Update" is old Akeeba language, Joomla doesn't refer to updating Joomla using com_joomlaupdate anywhere else as a "live update" (apart from in the very recently added pre update check) 

<img width="735" alt="Screenshot 2021-08-24 at 22 37 21" src="https://user-images.githubusercontent.com/400092/130693429-0658cdd9-3b7b-48fd-abcb-e6a6c6bb1891.png">

**Comment by PhilETaylor** [comment]
as an example, after upgrading the component its called "One-click update"

<img width="803" alt="Screenshot 2021-08-24 at 22 42 13" src="https://user-images.githubusercontent.com/400092/130693905-ec5d70ef-37b2-4329-bd9b-8a390e7f3179.png">

**Comment by zero-24** [comment]
> Too scary language when really we dont want a negative here, we want a positive, enticing people to carry on reading to update the component because live update is available, they just first need to update the component.

@PhilETaylor can you please send a PR with a better language string against 3.10-dev.

> Also "Live Update" is old Akeeba language, Joomla doesn't refer to updating Joomla using com_joomlaupdate anywhere else as a "live update" (apart from in the very recently added pre update check)

The tab you hit "install update" is called "live update" since years?

**Comment by PhilETaylor** [comment]
> @PhilETaylor can you please send a PR with a better language string against 3.10-dev.

No, nope. Not prepared to have to defend my english :) Im already told Im a bully and too negative.

What we dont want people doing is seeing that something is not available and clicking away... without reading. Users do this kind of thing.  

> The tab you hit "install update" is called "live update" since years?

There is no tab in Joomla 4. So even less references to "live update"

**Comment by PhilETaylor** [comment]
Not a single reference to "Live" 

https://docs.joomla.org/J3.x:Updating_from_an_existing_version

https://docs.joomla.org/J4.x:Updating_from_an_existing_version

**Comment by zero-24** [comment]
Its there (in 3.x) since we added the "Upload & Install" tab into 3.x: 
![image](https://user-images.githubusercontent.com/2596554/130697084-2c55d484-f6e6-4ded-bbb7-fd502a135a3d.png)

But I'm fine to change it to something else when there is a better proposal out there.

**Comment by richard67** [comment]
But we should not call it "One click update" as long as we have these check boxes for confirming that all extensions are compatible and having made a backup and so on and so on.

**Comment by richard67** [comment]
Maybe "Three click update"? ;-)

**Comment by PhilETaylor** [comment]
Further proving my point that this is overdue a rethink. The naming of the feature however was only a secondary point to this issue. The overly negative language was the main point I was trying to get across.

**Comment by zero-24** [comment]
I agree I'm happy to take better meaning more positive english wording in.

**Comment by brianteeman** [comment]
Am I correct that you are looking for an alternative label for LiveUpdate that indicated it is different from Upload & Update because you dont need to download anything to your pc?

If so then I would suggest "Direct Update" or even just "Update"

**Comment by PhilETaylor** [comment]
> Am I correct that you are looking for an alternative label for LiveUpdate t

As the issue opening text states, this issue was more about the overly negative language in the title that could put off people upgrading. Saying "LiveUpdate/Direct Update/Update is not available" is just as bad. People will read that and give up. What that should be is inviting them to upgrade the com_joomlaupdate plugin before returning and trying again

**Comment by richard67** [comment]
Maybe something like "One step needed before you can update Joomla!"?
