### ISSUE TITLE
Fatal error, There was a problem we could not recover from.

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#35350]
### Steps to reproduce the issue
Installing the Joomla Update, I received this message and the website is gone: Sorry, there was a problem we could not recover from.
The server returned a "500 - Whoops, looks like something went wrong."
I downloaded the Joomla update
I chose it from a file in my downloads and chose update and install. 
The website began the update and then turned into an orange screen with the above error code. You can see it at www.climbcityrock.com

### Additional comments
I am not a developer. I simply maintain the website. I am in WAY over my head and really need help to get our website back online. Please help asap. Thank you!

**Comment by PhilETaylor** [comment]
edit /configuration.php 

Change 

`$debug = false;`

to 

`$debug = true;`

save the file and then reload the error page. 

Screenshot its contents and post here.

**Comment by PhilETaylor** [comment]
What version did you upgrade from - which is a Joomla 4 error message, did you know you were upgrading to Joomla 4? Did you take all the precautions, advice, migration planning, backups and tested backups before upgrading your site to Joomla 4?

**Comment by ghost** [comment]
I was upgrading from Joomla 3.9 to 4.0.1. 
 
I backed everything up through Akeeba backup per instructions. I am really a beginner beginner and have no idea what to do. 
 


-----Original Message-----

**Comment by PhilETaylor** [comment]
3.9 is a whole series, not a version. There are 28 versions in 3.9.x and then there is 3.10.0 and 3.10.1... 

 If you did not upgrade to Joomla 3.10.1 and resolve all your compatibility issues then you just destroyed your site but not reading the very clear instructions on joomla.org 

You will need to restore from your last know good backup. 

You should close this issue here, this GitHub Issues tracker is for reporting bugs, not for seeking support. Sorry.

**Comment by richard67** [comment]
> I was upgrading from Joomla 3.9 to 4.0.1.

Did you do that in one step, not with 3.10 in between? If so, then you should know that is not supported. Updates to 4.x have to be done from 3.10.x. This is written in EVERY release announcement for 3.10.x and 4.0.x releases, and it is also described here: https://docs.joomla.org/Joomla_3.x_to_4.x_Step_by_Step_Migration - mind the big red box at the top!

**Comment by ghost** [comment]
You know, I'm panicked right now after losing this website. I did read. I can't remember the version off the top of my panicked head, but after checking, reading, reading more, I thought I was doing the correct thing. This forum is fantastic for people chastising you and not so great for help. 
 
Thanks.


-----Original Message-----

**Comment by PhilETaylor** [comment]
I’m sorry you feel “chastised” but this is NOT A SUPPORT FORUM.

**Comment by rdeutz** [comment]
@angecityrock https://forum.joomla.org/ is a better place to asked question like this, this here is for bugs within the software.

**Comment by PhilETaylor** [comment]
You stated you have an Akeeba Backup - well read this:

https://www.akeeba.com/news/1748-joomla-3-10-and-4-0-common-issues.html

Especially the sections entitled: 

 - I upgraded to Joomla 4.0 by accident and my site is broken
 - I cannot restore a Joomla 3 backup on top of Joomla 4; the site is broken.

Then before upgrading to Joomla 4.0.x again read these: 

 - https://docs.joomla.org/Planning_for_Mini-Migration_-_Joomla_3.10.x_to_4.x
 - https://www.joomla.org/announcements/release-news/5845-joomla-4-0-and-joomla-3-10-are-here.html

> # How can I upgrade my site to Joomla 4?
> Don’t stress, you’re not alone, we are guiding you for the mini-migration.
> 
> The first step will be to update your site to Joomla 3.10. We invite you to read Joomla 3.10 The Pre-update Checker [ https://magazine.joomla.org/all-issues/may-2020/joomla-3-10-and-the-update-checker]. The 3.10 update checker will tell you which extensions are compatible with Joomla 4.0 (great, isn’t it?). 
> 
> And then, you just have to follow our step by step tutorials. You can find them on our official documentation at https://docs.joomla.org/Why_Migrate. Planning is the most important part of the mini-migration process. See https://docs.joomla.org/Planning_for_Mini-Migration_-_Joomla_3.10.x_to_4.x to start with. At the bottom of that doc, you can then proceed to the step by step for mini-migration from 3.10 to 4.x. and specifically start with planning at (you’ll find plenty of information and tutorial about Joomla 4 on JDocs).
> 
> Note: we advise you to first test the migration on a copy of your production site.
> 
> You may also wonder if you have to migrate ASAP? You can take your time, we’ll support 3.10 for 2 more years. So your site is not at risk if you don’t upgrade now. And don’t forget that some of your extensions may not be yet ready for Joomla 4 (even though most developers have done a great job offering a Joomla 4 test version for a while - you can read articles about these extensions on the Joomla Community Magazine)
> ```

**Comment by PhilETaylor** [comment]
I see you site is online again now... see no need to panic after all. This is why backups are important. 

<img width="1592" alt="Screenshot 2021-08-24 at 19 07 48" src="https://user-images.githubusercontent.com/400092/130667644-26fdbbeb-f4b2-470a-a687-04931b5c609c.png">
