### ISSUE TITLE
[4] Use Symfony ErrorHandler for fatal errors in /administrator/ when debug = true

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35355]
### Steps to reproduce the issue

Probably a note to self. 

Cause a fatal PHP error in admin when debug = true

### Expected result

Red type Symfony stack trace, with the multiple exceptions or errors shown

<img width="1129" alt="Screenshot 2021-08-24 at 21 18 44" src="https://user-images.githubusercontent.com/400092/130700677-775f8297-7f38-4980-92bc-fdcb7781beac.png">

### Actual result

Joomla error page showing only the latest stack trace 

<img width="1599" alt="Screenshot 2021-08-24 at 23 56 36" src="https://user-images.githubusercontent.com/400092/130700670-dea96556-117b-45db-a942-1f280425012b.png">

**Comment by Fedik** [comment]
That is expected. All exceptions from Application handled by Joomla Exception handler.
Symfony ErrorHandler used for boot process, and when Joomla Exception handler failed (then you will get 2 exceptions in a list, as on your screen).

**Comment by PhilETaylor** [comment]
With debug mode enabled, It would be much better to show the Symfony error handler which has more features including click to launch code in IDE support (PR Coming soon).

With debug mode disabled, we can leave the Joomla Exception Handler to display the error (as it does now, without a stack trace)

**Comment by Fedik** [comment]
That need to discuss, what other want/like. I am fine with both approach.

Btw, symfony error handler "full report" also work when `error_reaporting => maximum`, not required `debug => true` (that may be overhead in some cases)

**Comment by PhilETaylor** [comment]
`error_reporting` is more about hiding and showing PHP errors and should (and does) only map to the PHP ini setting `error_reporting` 

`error_reporting` was a quick way to hide PHP warnings in older versions of Mambo/Joomla 

It makes no sense to have `error_reporting`  on and debug mode off. 

Debug mode however should show stack traces and helpful debug information - and IMHO - should also enable by default, when debug is enabled,  error_reporting(E_ALL) and display_errors = On.

**Comment by wilsonge** [comment]
> With debug mode enabled, It would be much better to show the Symfony error handler

Joomla's exception handler is aware of request format - it can handle appropriately for JSON, JSON API, XML etc - symfony's only deals with cli/html.

Joomla's HTML renderer could definitely be enhanced or pass it through to Symfony - but I don't think we want to completely shortcut it out. It's also still at the stage where because we set the response body into the application we can have plugin events trigger on render of the error page (Symfony's one was put higher level when we didn't have that level of information available).

**Comment by PhilETaylor** [comment]
ok cool

**Comment by wilsonge** [comment]
Just to be clear we can improve things to be sure. Just completely removing the Joomla Exception handler isn't the right approach but there's definitely scope to improve things.

**Comment by PhilETaylor** [comment]
No worries... first I have to completely rewrite the LDAP plugin... for the 5 people in the world using it :)
