### ISSUE TITLE
[4] Highlighting of active admin menu item (again)

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35357]
### Steps to reproduce the issue

# This is NOT AN AKEEBA BACKUP BUG - This is a Joomla Admin Menu Javascript bug. 

This is still not perfect. [The last change fixed the highlighting of the Home Dashboard](https://github.com/joomla/joomla-cms/pull/35294) when sub menus were used 

Now when you are three levels deep you have a highlight issue as well. 

Install Akeeba Backup 

In Left menu go to Components -> Akeeba Backup For Joomla -> Control Panel NOTE ONLY Control Panel is highlights = Correct. (url /administrator/index.php?option=com_akeebabackup) 

In Left menu go to Components -> Akeeba Backup For Joomla -> Profile Configuration NOTE INCORRECT Control Panel is highlighted as well as Profile Configuration. (url is /administrator/index.php?option=com_akeebabackup&view=configuration) 

### Expected result

When selecting "Profile Configuration " only the "Profile Configuration " is highlighted as active. 

Mockup Screenshot - not real:
<img width="316" alt="Screenshot 2021-08-25 at 01 30 43" src="https://user-images.githubusercontent.com/400092/130707147-60dbf979-2a02-4d94-b3b1-5c519f1db4e0.png">

### Actual result

When selecting "Profile Configuration " the "Control Panel " and "Profile Configuration " is highlighted as active. 

<img width="315" alt="Screenshot 2021-08-25 at 01 30 25" src="https://user-images.githubusercontent.com/400092/130707131-811b1ff9-4843-4be0-a1ac-6eb0cd317d5e.png">

### Additional comments
@nikosdion This is NOT AN AKEEBA BACKUP BUG This is a Joomla Admin Menu Javascript bug. 
@dgrammatiko Maybe you would be so kind to fix this once and for all by refactoring the code correctly, [my last change](https://github.com/joomla/joomla-cms/pull/35294) was really only for the Home Dashboard menu item and did not have sub menus in its scope. Maybe some reincarnation of https://github.com/joomla/joomla-cms/issues/34484#issuecomment-858708218 that takes into account the Home Dashboard as well ?

**Comment by brianteeman** [comment]
The cause is the exact same issue I identified a few months ago

**Comment by PhilETaylor** [comment]
I'm going to bed
I have a fix
I will fix it myself tomorrow
