### ISSUE TITLE
If we use note type in xml, then second note is not completely full width in joomla 4

### ISSUE THREAD

**Issue by ashik685** [joomla/joomla-cms#35359]
### Steps to reproduce the issue

If we use note type in xml, then second note is not completely full width in joomla 4

type="note"
class="alert alert-success"

### Expected result

But two needs to be full width

### Actual result

One shows full width and second shows half width

### System information (as much as possible)

Joomla 4

**Comment by ReLater** [comment]
Are you sure that the lines in your second note field are not just shorter? As far as I see the note fields are just as wide as the content in it. Compare images please.

### Shorter lines:

![grafik](https://user-images.githubusercontent.com/20780646/130786873-5bf5802a-d6e4-4892-9e8c-e214c97ff690.png)

### Longer line:

![grafik](https://user-images.githubusercontent.com/20780646/130786999-944eaf0a-71d5-4ede-87bf-02048760db01.png)

**Comment by ReLater** [comment]
If you want them always with width 100% use this class combination in your XML:

`class="alert alert-success w-100"`

**Comment by richard67** [comment]
@ashik685 Please check the above replies and close this issue if you are ok with it. Thanks in advance.

**Comment by Quy** [comment]
Closing due to no response.
