### ISSUE TITLE
[3.10] Is it really necessary to get four Joomla update notifications a day?

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#35368]
### Problem identified
Joomla 3.10 installed. 
Update notifications received:
Tues 24th 16:03
Tues 24th 22:03
Weds 25th 04:03
Weds 25th 10:04
Weds 25th 16:03
anticipating Weds 25th 22:03

This is across several websites so getting very annoying. 

### Proposed solution
Reduce to twice per day.

### Open questions
Or is there already a setting for this other than disabling notifications altogether?

**Comment by PhilETaylor** [comment]
LMAO! See https://github.com/joomla/joomla-cms/pull/35345 

//cc @brianteeman

**Comment by PhilETaylor** [comment]
Documentation: https://docs.joomla.org/J3.x:Plugin_Joomla_Update_Notification

"Quick Tips: To turn off Joomla! update email notifications simply disable the plugin."

**Comment by Scrabble96** [comment]
Ah yes. I'll close this, but perhaps the best option would be to give the user a choice, e.g. every 24, 12, 6 hours or none.

**Comment by PhilETaylor** [comment]
Already is configurable! You can set the cache time out already.￼

**Comment by Scrabble96** [comment]
How? It's not an option on the plugin. I'm looking at 3.10, BTW and not 4.0 at the moment.

**Comment by wojsmol** [comment]
In `/administrator/index.php?option=com_config&view=component&component=com_installer` by setting `Updates Caching (in hours)'.

**Comment by Scrabble96** [comment]
Thanks. Presumably it will need re-doing after every update as it will get overwritten with every update.

**Comment by PhilETaylor** [comment]
It's saved in the database so no, it should persist

**Comment by Scrabble96** [comment]
Thank you, both, @wojsmol and @PhilETaylor, I'll give it a go.

**Comment by Scrabble96** [comment]
Hi. Adding the URL above to the domain returns a not found, so I went to cPanel in File Manager and navigated to domain > administrator > components > com_installer > config.xml and changing line 30 from
`default="6"` 
to
`default="24"`
for one test domain and
`default="1"`
for another.

I've tried 24 and 1 as I'm not sure whether 24 means 24 x hourly cache or 1 x 24-hr cache.

Either way, it has made no difference. I'm still getting the emails for both sites every six hours.

**Comment by wojsmol** [comment]
@Scrabble96 URL posted in my previous comment correspond to Extensions > Manage > Updates > open Options > change `Updates Caching (in hours)` to fore example `12`. This is update cache expiration time so 12 hours means that mail will be send 2 time a day.

**Comment by Scrabble96** [comment]
Thank you. Found it. :-)
