### ISSUE TITLE
[4.0] Smart search highlight is highlighting meta-data headers

### ISSUE THREAD

**Issue by scout507** [joomla/joomla-cms#35361]
### Steps to reproduce the issue

1. Enable smart search 
2. Create an article containing these words or substrings of these (for example 'at', 'detail')

![grafik](https://user-images.githubusercontent.com/70096457/130753071-8b1b28d2-4930-4da1-958a-c0d0813e946f.png)

3. Use the smart search to search for the article

### Expected result

Only the content of the article and it's meta-data should be highlighted.

### Actual result

The meta-data headers also get highlighted if they contain the search term(s).

![grafik](https://user-images.githubusercontent.com/70096457/130754707-fda6cd00-a992-452c-ae68-4ad83dd81257.png)

### System information (as much as possible)

Tested on 4.0-dev & 4.0.1

**Comment by Hackwar** [comment]
Unfortunately there is no reliable way for us to know which part is the search result and which is the metadata since everybody can create overrides and specific layouts for search results, which can change everything. Thus unfortunately this is something we can't/wont fix.
