### ISSUE TITLE
[4.0] Update Server declared as 3.x ?

### ISSUE THREAD

**Issue by 7at1blow** [joomla/joomla-cms#35369]
### Steps to reproduce the issue

J4.0.2
Backend > System > Updates > Joomla

### Expected result

Update Server is declared as 4.x

### Actual result

Update Server is declared as 3.x instead of 4.x
see screenshot 

![2021-08-25 Joomla 4 Update Server 3 x](https://user-images.githubusercontent.com/42974861/130820284-9475f54e-08d1-4907-b5dc-c4bbaba6dc97.jpg)

**Comment by richard67** [comment]
@7at1blow Your 4.0.2 is the result of a new installation? Or has it been updated? If so, from which version(s), i.e. which update history does it have?

**Comment by richard67** [comment]
@7at1blow I just see it seems to be a mistake in the German language string:

```
COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_DEFAULT="Dieser Server ist mit dem „%s“-Update-Server verbunden - Von dieser Update-Quelle werden alle Updates für die aktuelle Hauptversion (3.x) angeboten."
```

That means you are very likely on the right update channel, just the text with the version number above the buttons is wrong.

Please report this issue here: https://github.com/joomlagerman/joomla

**Comment by richard67** [comment]
@7at1blow I just see there is already a pull request in the German translations repository, so no need to report an issue there: https://github.com/joomlagerman/joomla/pull/2045 . So it will be fixed with a futire update of the language pack, I think.

**Comment by richard67** [comment]
Closing as not a CMS core issue, see previous comments.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35369">issues.joomla.org/tracker/joomla-cms/35369</a>.</sub>

**Comment by zero-24** [comment]
In the end it is a CMS issue. We should pass the versions via sprintf and not rely on the TTs to update the strings. While we are going to fix it now we should do it right in the CMS in the first place.

**Comment by richard67** [comment]
> 
> 
> In the end it is a CMS issue. We should pass the versions via sprintf and not rely on the TTs to update the strings. While we are going to fix it now we should do it right in the CMS in the first place.

@zero-24 Feel free to make a PR.

**Comment by zero-24** [comment]
> > 
> > 
> > In the end it is a CMS issue. We should pass the versions via sprintf and not rely on the TTs to update the strings. While we are going to fix it now we should do it right in the CMS in the first place.
> 
> @zero-24 Feel free to make a PR.

I know just want this to be logged here too.

**Comment by brianteeman** [comment]
note that it will require a completely new key

**Comment by richard67** [comment]
For such major version related texts I think they could remain hardcoded and translators should properly translate from the English texts for J4 and not just reuse their J3 strings.

**Comment by brianteeman** [comment]
As we have no suitable quality  control and we have seen from experience the problems a bad translation can cause (remember the installation folder) we have to do what we can to avoid issues. When experienced joomla users producing the french, german and american packs can produce language packs that have not been tested what chance do the language users have when the translators dont even use joomla
