### ISSUE TITLE
[4.0] Smart search weight allows negative values

### ISSUE THREAD

**Issue by Waleet** [joomla/joomla-cms#35365]
### Steps to reproduce the issue

Go to System -> Global Configuration -> Smart Search -> Index 

![image](https://user-images.githubusercontent.com/82458509/130799259-b6b563c3-cabe-4dbd-829f-49485bf95b6c.png)

Here you can input negative weight multipliers.

### Expected result

After inputting negative weight multipliers and trying to save said changes, get a popup/message notifying you that negative values are prohibited.

### Actual result

You can save negative values for weight multipliers.
This will result in an error when trying to index your data with the new multipliers.

![image](https://user-images.githubusercontent.com/82458509/130793376-4f79346f-f317-4f1f-99fa-932dca5bc797.png)

### System information (as much as possible)

This has been tested on Joomla 4.0 dev and Firefox 91.0.2 64bit with ~1300 articles and Sample blog data installed.

### Additional comments

This option makes sense for values from 0-n but values below 0 should be prohibited.

**Comment by brianteeman** [comment]
It would just need this xml updating https://github.com/joomla/joomla-cms/blob/2f9ce76ceb0f1bd3b1e4af868a6a2a20e82e8e55/administrator/components/com_finder/config.xml#L276 so that each of the fields  has `min="0"`

**Comment by alikon** [comment]
please test #35367

**Comment by Waleet** [comment]
@alikon oh my bad, I searched for weight multiplier and did´nt find anything but I can test your PR

**Comment by richard67** [comment]
@Waleet Please test #35367 and after test mark the test result in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/35367 by using the "Test this" button at the top left corner, then selecting the appropriate test result and then submit. Thanks in advance, and thanks for reporting the issue. Good catch.

**Comment by Waleet** [comment]
@richard67 Ty Richard happy to help :)
