### ISSUE TITLE
[4] tool tip hover gives text pointer cursor and not hand pointer cursor

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35375]
### Steps to reproduce the issue

When hovering over certain text that has tool tip you get a text pointer.

Internet says:
"The text pointer is used when you need to edit text."
"When you see the text pointer come up, it can mean your mouse pointer is in an area that can be edited"

This is because the tool tip is on a span/div it seems. Here is an [example fiddle](https://jsfiddle.net/shail/MxmbK/2/) where if you hover on the four on the top which are `a` links you get a hand pointer and on the "hover on me" you get a text pointer. This shows the same issue... 

All of the Bootstrap example tooltips (just as a comparison) are using button or `a` tags for tooltips and all show hand pointer cursors for that reason https://getbootstrap.com/docs/5.0/components/tooltips/

A text pointer is the wrong cursor to be showing in this situation when there are more suited cursors. 

### Expected result
Maybe a hand shape pointer, or maybe a help pointer? 

### Actual result

![Screen Recording 2021-08-25 at 10 01 26 pm](https://user-images.githubusercontent.com/400092/130864201-bf94a22a-4f00-478d-88d3-25277ded404a.gif)

### System information (as much as possible)

safari on mac

**Comment by harshraj1311** [comment]
hey, Can I work on this issue?

**Comment by drmenzelit** [comment]
@harshraj1311 you don't need to ask for permission, if you have a solution for this issue, you can create a pull request.

**Comment by Shubhamverma2796** [comment]
Hey, please let me know how can I reproduce this issue becaue I want to work on it.

**Comment by drmenzelit** [comment]
@Shubhamverma2796 I think the explanation from Phil is clear enough. The screencast shows System -> Update Sites. But probably the problem appears in other views too.

**Comment by Shubhamverma2796** [comment]
Can you please tell me this issue is associated with which file or folder? Also, can it be resolved by using the CSS hover effect?

**Comment by brianteeman** [comment]
If someone did that then they might as well fix the problem themselves
