### ISSUE TITLE
Duplicate entries of variables in the configuration file

### ISSUE THREAD

**Issue by infoJson7** [joomla/joomla-cms#35371]
### Steps to reproduce the issue
Install Joomla 4 on Sub-Domain from Softaculous

### Expected result
To install scripts and execute

### Actual result
500 ERROR

### System information (as much as possible)
From my Hosting Administrators
Thank you for your patience.

Our operations team checked the issue in detail and they have found that the problem was caused by duplicate entries of variables in the configuration file. It looks like the problem is due to a bug in Joomla and hope they will fix it in the future updates.

The Joomla installation at https://wiki.domainname.com/ is now working fine after commenting out the following duplicate entries.

============

JConfig::$caching on line 45 and 65.

JConfig::$cachetime on line 47 and 66.

JConfig::$gzip on line 30 and 67.

==========

**Comment by PhilETaylor** [comment]
I have heard many reports of Softaculous breaking Joomla 4 installs - not Joomla issue :-)

**Comment by alikon** [comment]
it's seems to work the demo i mean
![Screenshot from 2021-08-25 18-39-12](https://user-images.githubusercontent.com/181681/130830778-69495cb9-bf37-4cf0-9b57-eb30afaa682f.png)

**Comment by alikon** [comment]
hum i've talked too early :smile: 
![Screenshot from 2021-08-25 18-42-46](https://user-images.githubusercontent.com/181681/130831282-9ed06d5f-c589-4861-a2db-76542476266f.png)

**Comment by alikon** [comment]
anyway we should try to collaborate with them isn't it ?

**Comment by infoJson7** [comment]
Thanks for the heads up that it's a Softaculous issue. Here in-lies the problem. The folks who loaded Joomla through Softaculous are going to want to UPGRADE (Which is how my issues all started) and they are going to get that 500 Error, it's a flood coming your way just so ya know 😉👍

**Comment by brianteeman** [comment]
I have the ceo contact details if a maintainer wants them

**Comment by alikon** [comment]
would be nice to get in touch with them ... to sort this out...never used it personaly, but i've already heard that some people doing so..

**Comment by alikon** [comment]
...ops i'm not a mantainer ....
some github synch glitch again

**Comment by infoJson7** [comment]
There is a Forum Board for Bugs at Softaculous.com I submitted it there and hope they fix it. Looks like they frequent their Forum

**Comment by jwaisner** [comment]
Thank you @infoJson7 for reporting this. This has been identified as not an issue with Joomla but with Softaculous. Sounds like you have already reached out to their support. I will be closing this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35371">issues.joomla.org/tracker/joomla-cms/35371</a>.</sub>

**Comment by softaculous** [comment]
Hi,

Thank you for reporting the issue. 

While we are unable to replicate the issue on our servers, if we can get access to a test account on one of the servers from the reporters I would like to personally look into it and get it resolved. 

You can send the login details with a support ticket with a link to this thread :
https://softaculous.deskuss.com/

Mention @ Brijesh in the ticket and I shall check it asap.

Regards,
Brijesh Kothari
President - Softaculous<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35371">issues.joomla.org/tracker/joomla-cms/35371</a>.</sub>

**Comment by brianteeman** [comment]
> CEO's are not going to be interested in the slightest.

thankfully you're wrong and we got the president instead ;)

**Comment by softaculous** [comment]
In order to narrow down if the issue is with just one hosting provider or more, may I ask which hosting provider are you guys using ?

**Comment by infoJson7** [comment]
We are using A2Hosting. I have also submitted a ticket at https://www.softaculous.com/board/index.php?tid=17911 and Punit is working on it. I submitted a ticket to https://softaculous.deskuss.com/ with @ Brijesh and @ Punit in it with Logins for Cpanel

**Comment by softaculous** [comment]
@infoJson7 Thank you for sharing the login details over support ticket. 

We were able to identity the exact cause of the issue. 

The issue is due to customization done by A2 Hosting after the installation process is completed by Softaculous using the hooks available. 

Joomla changed their syntax of storing integer and boolean values in configuration.php

Example :
Joomla 3 : public $caching = '0';
Joomla 4 : public $caching = 0;

Joomla 3 : public $gzip = '0';
Joomla 4 : public $gzip = false;

So previously Joomla didn't use boolean and saved just 0 and 1 and the integers were saved with a single quote wrapped around it. 
@brianteeman can you confirm this ?

Due to this the A2 Hosting system failed to detect that the variable already exists and added the variables at the end of the file causing the issue reported in this thread. 

We have notified the A2 Hosting team and we are confident they will be fixing this asap. 

Regards,
Brijesh Kothari<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35371">issues.joomla.org/tracker/joomla-cms/35371</a>.</sub>

**Comment by brianteeman** [comment]
> So previously Joomla didn't use boolean and saved just 0 and 1 and the integers were saved with a single quote wrapped around it.
@brianteeman can you confirm this ?

Basically yes. The relevant file is  https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/src/Model/ConfigurationModel.php and the relevant pull request where the changes were made is https://github.com/joomla/joomla-cms/pull/17082

**Comment by softaculous** [comment]
> 
> 
> > So previously Joomla didn't use boolean and saved just 0 and 1 and the integers were saved with a single quote wrapped around it.
> > @brianteeman can you confirm this ?
> 
> Basically yes. The relevant file is https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/src/Model/ConfigurationModel.php and the relevant pull request where the changes were made is #17082

Thanks!

**Comment by infoJson7** [comment]
Thanks for all the HELP...you guys are all TOP NOTCH people. You probably hear mostly BS and complaints all day, so I want to let you know, you guys went ABOVE AND BEYOND and for FREE and it turned out it was a bunch of people who do the hosting that I PAY FOR...and go no results and the guys who do it for FREE came out on TOP. Again top notch each and everyone of you 👊😉👊

PS Phil E Taylor didn't realize who you were, but I knew that name sounded familiar you looked familiar....I used to buy your extensions back in the day with Blue Flame Digital Solutions....didn't realize you code with the project....Good Man ALWAYS on top of things paid and free 👍<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35371">issues.joomla.org/tracker/joomla-cms/35371</a>.</sub>

**Comment by softaculous** [comment]
> 
> 
> Thanks for all the HELP...you guys are all TOP NOTCH people. You probably hear mostly BS and complaints all day, so I want to let you know, you guys went ABOVE AND BEYOND and for FREE and it turned out it was a bunch of people who do the hosting that I PAY FOR...and go no results and the guys who do it for FREE came out on TOP. Again top notch each and everyone of you 👊😉👊
> 
> PS Phil E Taylor didn't realize who you were, but I knew that name sounded familiar you looked familiar....I used to buy your extensions back in the day with Blue Flame Digital Solutions....didn't realize you code with the project....Good Man ALWAYS on top of things paid and free 👍
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/35371](https://issues.joomla.org/tracker/joomla-cms/35371).

Thank you for the kind words :)
