### ISSUE TITLE
[4.0] Subform fields do not show field descriptions

### ISSUE THREAD

**Issue by regularlabs** [joomla/joomla-cms#35389]
When using the subform field, sub-fields are shown without the description attached to those fields in the xml files.

**Comment by Fedik** [comment]
should be with, there nothing special for subform
https://github.com/joomla/joomla-cms/blob/46c2b50b7e1709dd841b5c68b1371a953c4dcc26/layouts/joomla/form/field/subform/repeatable/section.php#L37-L39

and
https://github.com/joomla/joomla-cms/blob/46c2b50b7e1709dd841b5c68b1371a953c4dcc26/layouts/joomla/form/field/subform/repeatable-table.php#L64-L67

**Comment by regularlabs** [comment]
Sorry, was caused by something else...
