### ISSUE TITLE
[4] Uploading SVG file in Media Manager gives generic error messages

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35387]
### Steps to reproduce the issue

try to upload a SVG file in Media Manager in Joomla 4 admin 

### Expected result

Depending on configuration, either the file uploads, or gives a helpful message saying this file type is not allowed. 

### Actual result

<img width="721" alt="Screenshot 2021-08-26 at 19 21 27" src="https://user-images.githubusercontent.com/400092/131015773-553cbb87-2d2b-41b3-869f-2e62306c0d7a.png">

**Comment by Quy** [comment]
Related #33702

**Comment by brianteeman** [comment]
thought it sounded familiar
