### ISSUE TITLE
J 4.0.2 cant find GD library when using the template editor.

### ISSUE THREAD

**Issue by gwstyles** [joomla/joomla-cms#35386]
### Try editing images in J 4 template editor.
While testing the template editor in j4.0.2 I can not see the svg images.The screen shot shows that J4 thinks I do not have the GD library available ,but it is? Is this a bug or does it work for you?
Also the documentation button goes to J3 info not J4. 

### System information (as much as possible)
 Site Information

    Setting 	Value
PHP Built On 	Linux manganese.cloudhosting.co.uk 4.18.0-305.10.2.2.lve.el7h.x86_64 #1 SMP Wed Jul 28 13:09:44 UTC 2021 x86_64
Database Type 	mysql
Database Version 	10.3.30-MariaDB-log-cll-lve
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	No
PHP Version 	8.0.9
Web Server 	LiteSpeed
WebServer to PHP Interface 	litespeed
Joomla! Version 	Joomla! 4.0.2 Stable [ Furaha ] 24-August-2021 19:54 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0 
Articles 

### Additional comments

![screen shot 2021-08-26 at 16 43 40](https://issues.joomla.org/uploads/1/2f0bb2769461677fe01dcd6e1744498d.jpg)

**Comment by brianteeman** [comment]
Could you upload larger images please.

**Comment by wojsmol** [comment]
@brianteeman On screan shot posted by @gwstyles there's visible COM_TEMPLATES_GD_EXTENSION_NOT_AVAILABLE message.

**Comment by gwstyles** [comment]
Do you need larger images or is it ok?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35386">issues.joomla.org/tracker/joomla-cms/35386</a>.</sub>

**Comment by gwstyles** [comment]
I cant paste it here?
see attached.[error message.txt](https://issues.joomla.org/uploads/1/41f9abe57ccea6ae586cc9a74effd0b9.txt)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35386">issues.joomla.org/tracker/joomla-cms/35386</a>.</sub>

**Comment by gwstyles** [comment]
Cant upload a svg, change jpg to .svg<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35386">issues.joomla.org/tracker/joomla-cms/35386</a>.</sub>

**Comment by gwstyles** [comment]
JPG extension tells me invalid mime type, so I have changed it to txt.
First time on git and a bit odd for an old git...![screen shot 2021-08-26 at 18 14 42](https://issues.joomla.org/uploads/1/4d4012d360dea0a7e1f76c03db20e43b.txt)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35386">issues.joomla.org/tracker/joomla-cms/35386</a>.</sub>

**Comment by gwstyles** [comment]
OK that dont work,how do you upload an svg image to git?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35386">issues.joomla.org/tracker/joomla-cms/35386</a>.</sub>

**Comment by gwstyles** [comment]
OK its not a bug then just not designed to do this.Good stuff lads.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35386">issues.joomla.org/tracker/joomla-cms/35386</a>.</sub>

**Comment by dgrammatiko** [comment]
> You cannot edit SVG Files with Joomla's template manager The only formats supported are

@PhilETaylor in the template editor you should be able to edit the svg (using the codemirror editor, basically editing the text)

**Comment by dgrammatiko** [comment]
> Yes but when Im talking about editing images with GD, they have to be one of those formats

Even Media manager can't handle all of the possible image formats (gif, ...) for some good reasons:
https://github.com/joomla/joomla-cms/blob/932dea2c0d59fabff1865d9d4b667baa28b9d09a/administrator/components/com_media/resources/scripts/components/browser/items/image.vue#L205

**Comment by dgrammatiko** [comment]
> I dont have time to look into all the Media Manager issues

Quick recap: the media manager repo when abandoned had around 100 open issues
I have a personal list of issues that are ranking from annoying bugs to serious sh**t

That doesn't mean that the media manager is bad, actually, it's the best implementation in the Joomla world (I've tested the others and they are 10 years behind). BUT needs hands to fix and implement whatever the MM team left half-baked...

**Comment by brianteeman** [comment]
> OK its not a bug then just not designed to do this.Good stuff lads.
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/35386](https://issues.joomla.org/tracker/joomla-cms/35386).


This should be closed now
