### ISSUE TITLE
[4.0] Paging Problem Tags

### ISSUE THREAD

**Issue by DonPedro34** [joomla/joomla-cms#35382]
### Steps to reproduce the issue
If you have 100's of Articles Tagged with the same Tag, like "Year 2021" and you want to see them, with 10 Articles per Page.

The First Page displays Correctly.

The Second Page returns 404 not found.

The First Page is linked like this:
/index.php/en/component/tags/tag/year-2021

The second page like this:
/index.php/en/component/tags/year-2021?Itemid=237&start=5

With "/tag" missing. => result 404.

### Expected result

"/tag" is included.

### Actual result

"/tag" is missing.

### System information (as much as possible)

J 4.0.2 upgrade from 3.10.1

### Additional comments

This works correctly on J 3.10.1

**Comment by joomdonation** [comment]
Confirmed. Quick solution would be creating a menu item to link to **List All Tags** menu item type. I tested it on a mono language website and it worked, should work for your multilingual website, too

There is PR https://github.com/joomla/joomla-cms/pull/33208 tries to solve this issue but it is not working yet.

**Comment by arturkb** [comment]
Yeep, same issue for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35382">issues.joomla.org/tracker/joomla-cms/35382</a>.</sub>

**Comment by ch2856** [comment]
Any progress with this issue?

**Comment by DrZen33** [comment]
I am a bit confused. I have just discovered the Pagination bug for Lists of Tags, after upgrading from Joomla 3 to **Joomla 4.1.5**.
There seems to be many duplicate reports that have been closed for the same bug.
It is now the 25th of August 2022 - one year later since beginning of this thread...
Is there any progress on fixing this bug?
Is there is a manual fix listed somewhere on Github for this?
Regards, Derek.

**Comment by Hackwar** [comment]
#39114 should fix this. Please help testing that.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39114 . Thanks in advance.

**Comment by chmst** [comment]
Preparing a test for https://github.com/joomla/joomla-cms/pull/39114 I could not replicate this old issue.
