### ISSUE TITLE
[4.0] Override update info improvement

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#35381]
### Is your feature request related to a problem? Please describe.
When making an update where overriden files were changes, you get a message.
![grafik](https://user-images.githubusercontent.com/1229869/130933978-560bee74-48d0-4ee6-ae94-e9ef90fee1ff.png)

### Describe the solution you'd like
It would be helpful to have a link to click, where the overrides could be checked.

@astridx ?

**Comment by RussW** [comment]
is it not sufficient that on the "Home Dashboard" there is a link to the overrides, the template style with the change then has a badge stating it has a change, the file list for the template style with the change also has a tab "Updated Files" that then can be selected/checked and acknowledged that you have seen it and taken any appropriate action, which in turn removes the notification.

**Comment by brianteeman** [comment]
A link in the message would be helpful even if it just goes to /administrator/index.php?option=com_templates&view=templates

Wherever possible we should aim to have a "solution" in the message. In this case the "solution" is the link

**Comment by Scrabble96** [comment]
I have just upgraded a site to 4.0.5 and had a message that 4 overrides had changed, but absolutely no indication as to which of the many overrides I have created had changed. What use is a message like that?

And, presumably, it is not the overrides that have changed but the original core files that the overrides were based on?

**Comment by astridx** [comment]
@Scrabble96 
> I have just upgraded a site to 4.0.5 and had a message that 4 overrides had changed, but absolutely no indication as to which of the many overrides I have created had changed. What use is a message like that?
And, presumably, it is not the overrides that have changed but the original core files that the overrides were based on?

For me, the procedure is fine.

After the update, I see a note:
![1](https://user-images.githubusercontent.com/9974686/146353465-188f6616-7be4-41b8-9c16-0f0e106cbd47.PNG)

The red symbol "Updates to check" leads me per click to the Template Manager:
![2](https://user-images.githubusercontent.com/9974686/146353470-d103ab1b-cedb-4ae8-8199-d676bd2ff428.PNG)

In the Template Manager I can see which templates are affected and I can open the template for editing per click on the name:
![2a](https://user-images.githubusercontent.com/9974686/146353473-0b93c52c-b94e-4021-8f85-a984434afb09.png)

When I edit the template, I see in the tab `updatet files`, a link through which I can open each individual file to change.
![2b](https://user-images.githubusercontent.com/9974686/146353476-e1e380a5-3109-44c5-9df0-44640369db74.PNG)

Each file provides a diff view:
![2c](https://user-images.githubusercontent.com/9974686/146353479-e342cc20-baf5-4afc-acb5-e0c1eaf6e176.png)

--- 
One could consider linking the information "x files are changed" in the Template Manager directly into the tab that displays the files. But everything has its advantages and disadvantages. Advantage: Someone who wants to edit the files has to click less once. Disadvantage: I think that more options cause more confusion. Especially newcomers would find themselves in a subtab after clicking and have to orientate themselves first. That's why I would leave it as it is.
What do you think @Anu1601CS

**Comment by Scrabble96** [comment]
@astridx what you are seeing is the same as I am seeing.

Your changed file has this code ```key = "JHELP_MENUS_MENU_ITEM_CONTACT_SINGLE_CONTACT" which is highlighted in green. Anything highlighted in green I would expect to mean 'this is ok, this is correct', but in fact it is the text highlighted in pink which has changed.

Perhaps highlighting in pink doesn't mean 'wrong' but it indicates 'danger, you must look at this' instead and I was interpreting it the wrong way. I guess I won't be the only one.

I still think the text for the on/off buttons are the wrong way around, though.

**Comment by astridx** [comment]
@Scrabble96 The colours are a misunderstanding. Red indicates that a text has been deleted. The green text was inserted. 

The point is to look at the code that has been added to the Joomla Core files. You may want to integrate this into your overrides, i.e. your own code. This is the case if it contains new functions that you want to use. It is even more important if security risks have been corrected.

**Comment by astridx** [comment]
> I still think the text for the on/off buttons are the wrong way around, though.

You are a native speaker and you are certainly right. what do you suggest?

**Comment by Scrabble96** [comment]
> > I still think the text for the on/off buttons are the wrong way around, though.
> 
> You are a native speaker and you are certainly right. what do you suggest?

I'm looking at it again today, and I'm not so sure, now. Sorry!

BTW, do you know why has the copyright date changed from 2005 - 2020 to 2010? Joomla started in 2005, didn't it? Or does it mean that J4 has been in development since 2010? Protostar files have 2012.

**Comment by RussW** [comment]
a few observations if you don't mind...
It seems to be an issue with "expectation" to me.

Screenshot One (The dashboard notice):
the user is informed that there have been 4 override changes and the wording matches the "expectation" - The last update changed 4 override files, the user needs to check them in case they have manual updates to make themselves.

Screenshot Two (The Template Manager):
the user expectation at this point would be more information about the changes, but instead we just see a label telling that a specific template has had (the already known) 4 override changes.

1. at this point it's not immediately obvious what the users next action should be
2. there is nothing that guides the inexperience/new user to click on the template name
3. even then, clicking on the template name itself is not the obvious choice, we were just talking about overrides, not templates

User Expectation: 
to either immediately see the changed override information (which is not the most desirable option) or to have a button/link appropriately named/worded to describe their next action. EG "View Override Changes" or "View Updated Files"
I would suggest a new button under the effected template title & description and linking directly to the "Updated Files" tab on the next screen, leave the label as a label as this is a status.

Screenshot Three (Templates: Customise):
Better describe the "Delete List Entry" button, the word "Delete" is a warning sign for many and user may be too scared to "Delete" something they are unsure of what they are deleting. Maybe something like "Mark As Checked"

Screenshot Four (Diffs):
again, expectation or experience may cause some confusion here, whilst many developers and more technical users may have used "diff" before and know that "red" = deleted and "green" = added, in todays world of traffic light colour highlighting, this is (as mentioned) the reverse expectation.  For consistency of method (diff standard practice), keep the colours, but may be add the (+) and (-) symbols in front of the lines, this is also then consistent with many "diff" utilities.

**Comment by astridx** [comment]
> BTW, do you know why has the copyright date changed from 2005 - 2020 to 2010? Joomla started in 2005, didn't it? Or does it mean that J4 has been in development since 2010? Protostar files have 2012.

Has that been changed here: https://github.com/joomla/joomla-cms/pull/31504 ?

**Comment by brianteeman** [comment]
Please test #38401

**Comment by brianteeman** [comment]
Quite correct that the message about overrides on the update page needs improvement. In the context of the page you are on when you get that message it is not helpful. I will see what I can come up with.

**Comment by richard67** [comment]
@brianteeman Is this issue solved with your PR #38449 (and possibly your other PRs), so we can close it? Or is it solved only partly so we should leave it open?

**Comment by brianteeman** [comment]
as far as i am concerned it is, but maybe its not fr me to decide

**Comment by richard67** [comment]
Closing as having a pull request. @bembelimen Feel free to reopen this issue if I’m missing something.
