### ISSUE TITLE
[4.0] Namespaces of disabled extensions are still registered

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#35390]
### Steps to reproduce the issue

Disable any component/module/plugin in extension manager

### Expected result

The extension namespaces are removed from `/administrator/cache/autoload_psr4.php`

### Actual result

Namespaces are kept

### System information (as much as possible)

Joomla 4.0.2

### Additional comments

Same if delete autoload file: it's re-created but includes the namespaces of disabled extensions.

**Comment by Denitz** [comment]
Actually it's a problem because `/administrator/cache/autoload_psr4.php` is auto-created before the app initialization , is it logical to use the `Factory::getDbo()` in `JNamespacePsr4Map` class?

We can query the database and load the list of enabled extensions.

**Comment by PhilETaylor** [comment]
You are only Disabling the extension, not uninstalling it right? 

Just because something is "disabled" in extension manager, doesnt mean it will not contain code that can and will run... 

I would say this is normal and expected behaviour.

**Comment by Denitz** [comment]
Sounds good for me now.
