### ISSUE TITLE
Checkboxes, Radio buttons and list fields can't be saved

### ISSUE THREAD

**Issue by jamieyouellBuro26** [joomla/joomla-cms#35391]
### Steps to reproduce the issue
When adding a new field (checkbox, radio button, list) an error occurred.

### Expected result
Saving field

### Actual result
An error has occurred.
0 Call to a member function test() on bool
![image](https://user-images.githubusercontent.com/89634159/131098897-bccdcdae-533d-480a-894c-f0f688e44e1f.png)

### System information (as much as possible)
Joomla 4.0.0

**Comment by chmst** [comment]
In which context are you using the fields? In an owhn extension? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35391">issues.joomla.org/tracker/joomla-cms/35391</a>.</sub>

**Comment by jamieyouellBuro26** [comment]
Im trying to add a new field (checkbox, radio button, list) via content -> fields from the backend of Joomla 4.

![image](https://user-images.githubusercontent.com/89634159/131118496-ffdcd000-83bd-4cff-9982-10d3d55cd87a.png)

After filling all the necessary data  and hitting 'Save' the error shows up. So just core Joomla.

**Comment by joomdonation** [comment]
Could not re-procedure this error. @jamieyouellBuro26 Could you please go to System -> Global Configuration, access to System tab, set **Debug System** to Yes, then try again and send us the screenshot of that error page. That would help see what code causes the error (could be something on your site, not from Joomla core).

**Comment by Quy** [comment]
Closing due to no response.
