### ISSUE TITLE
Consider reskin of update process. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35393]
Consider reusing the empty state kind of look and feel as a captive page like [mockup - not real]:

Currently looks like this:

<img width="831" alt="Screenshot 2021-08-27 at 12 41 07" src="https://user-images.githubusercontent.com/400092/131123573-c6325ee3-c718-4923-af5d-26e78b87c637.png">

But could look like this:

<img width="1054" alt="Screenshot 2021-08-27 at 12 46 35" src="https://user-images.githubusercontent.com/400092/131122647-e0d442f4-f3b7-4aad-a614-c223284cedb0.png">

<img width="894" alt="Screenshot 2021-08-27 at 12 51 13" src="https://user-images.githubusercontent.com/400092/131123131-b786afbd-6564-4cb9-b628-c863ba205c9a.png">

_Originally posted by @PhilETaylor in https://github.com/joomla/joomla-cms/pull/35388#issuecomment-907142748_

**Comment by nikosdion** [comment]
This should be part of #35388 otherwise we are duplicating effort and we are very likely to create an inconsistent user experience.
