### ISSUE TITLE
Test issue for issue tracker

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#35399]
Testing if syncing works after composer upgrades to the issue tracker

**Comment by wilsonge** [comment]
It does

**Comment by wilsonge** [comment]
Test comment on tracker end<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35399">issues.joomla.org/tracker/joomla-cms/35399</a>.</sub>

**Comment by PhilETaylor** [comment]
@wilsonge  - you broke it... 

```
0 UnexpectedValueException
State not set in JTracker\Model\AbstractTrackerDatabaseModel
```

https://issues.joomla.org/activity/user/joomla-cms/query
