### ISSUE TITLE
[4.0] Click on Batch Button: Illegal invocation

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#35394]
### Steps to reproduce the issue
Click on batch button:
![img](https://i.imgur.com/hl5v77t.png)

### Expected result
No Javascript error

### Actual result
Javascript error
![img](https://i.imgur.com/hl5v77t.png)

### System information (as much as possible)
Joomla 4 Stable, Windows, Linux

**Comment by chmst** [comment]
Which Batch button? I cannot replicate this error in com_content, com_contact, com_odules. Can you give more information please?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35394">issues.joomla.org/tracker/joomla-cms/35394</a>.</sub>

**Comment by PhocaCz** [comment]
Hi Christiane,

I get these problems in my extensions where it worked in RC/Beta versions but not more in Stable. Maybe, it seems like some problem when moving from BS4 to BS5. It occurs by batch buttons, where standard code:

`HTMLHelper::_('bootstrap.renderModal', 'collapseModal');
...
$bar->appendButton('Custom', $dhtml, 'batch');`

does not work anymore (throws this error). It looks like I need to find another solution.

Anyway, will be great to get some info about all the changes which happened between Beta and Stable, because a lot of code which was overwritten for Beta does not more work in Stable. :-(

Thank you, Jan

**Comment by joomdonation** [comment]
@PhocaCz In my extensions, I use the same code as in J3 and it still works https://github.com/joomla/joomla-cms/blob/3.10-dev/administrator/components/com_content/views/articles/view.html.php#L182-L188

If it is really needed, maybe you can attach a copy of your extension here and tell us where the code is used and have problem. Maybe someone could look at it and give you correct code to use (hope so :) )

**Comment by PhocaCz** [comment]
@joomdonation Did you test it in stable? I use exactly the same code as you are using and it worked OK in beta/rc but in stable it throws now error. :idea:

![img](https://i.imgur.com/REQIvzw.png)

![img](https://i.imgur.com/lw0Iomq.png)

Jan

**Comment by joomdonation** [comment]
@PhocaCz Yes. I tested it, the modal opens OK, so I did not check the console for that js error. Don't have time to check to see what's causing that error now but quick modification to use the following code solves the issue for me. Maybe you can try
```php
$bar = JToolbar::getInstance('toolbar');
$bar->popupButton('batch')
	->text('JTOOLBAR_BATCH')
	->selector('collapseModal')
	->listCheck(true);
```

**Comment by PhocaCz** [comment]
@joomdonation Yes, this did the trick, now the batch function works without any error and the produced output is OK (including BS5 attributes):

```
<joomla-toolbar-button id="toolbar-batch" list-selection="">
<button value="http://localhost/xxx/administrator/" class="button-batch btn btn-primary" type="button" data-bs-toggle="modal" data-bs-target="#collapseModal">
	<span class="icon-square" aria-hidden="true"></span>
	Batch</button>
</joomla-toolbar-button>
```
Thank you, Jan

**Comment by Fedik** [comment]
please test #35417
