### ISSUE TITLE
Update 3.10.1 has write permission error's, but changes the permission itself

### ISSUE THREAD

**Issue by MoniqueNijboer** [joomla/joomla-cms#35405]
### Steps to reproduce the issue
directory and/or file permission are not writable

/home/{user}/public_html/administrator/components/com_actionlogs/models/fields/plugininfo.php

after changing it manual with chmod to 775 (file and directory) running the update Joomla sets file permission back to 644 and directory permission to 755. and throws an error with write permission during the update

### Expected result
run the update without error's

afterwards set file permission back (automatic or manual)

### Actual result
throws an error "could not open /home/..../plugininfo.php for writing"

### System information (as much as possible)
running apache 2.4.46,php 8.0.5, webmin 1.980, virtualmin 6.16

standard directory/file permission user = owner www-data = group dir 755 file 644

ubuntu 16.04.6 (i know!)

**Comment by PhilETaylor** [comment]
Not a joomla issue - but a hosting issue. 

If your server requires 775 for a file to be writable then it is non standard. 

http://www.filepermissions.com/file-permission/755
http://www.filepermissions.com/file-permission/775

The standard of 755 for folders and 644 for files is pretty standard and will work on a standard ubuntu/apache build as long as the ownership of the files is correct.

**Comment by MoniqueNijboer** [comment]
"Not a joomla issue - but a hosting issue."

sure, but the update sequence changes it back to standard, and then try to update Joomla.

if it first updates, and then changes it back to stock everything is fine.

It should not do that, as is i can't update it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35405">issues.joomla.org/tracker/joomla-cms/35405</a>.</sub>

**Comment by MoniqueNijboer** [comment]
changed owner of public_html and subfolders/files to www-data
now i get an error "invalid login" when trying to do the update

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35405">issues.joomla.org/tracker/joomla-cms/35405</a>.</sub>

**Comment by PhilETaylor** [comment]
>  "invalid login"

Which means that Joomla doesn't have access to create a file at to /administrator/components/com_joomlaupdate/restoration.php

**Comment by MoniqueNijboer** [comment]
checked with "ps aux | egrep '(apache|httpd)'"
and apache is running as www-data

if file permission is set to 644 and directory permission set to 755,
as you stated is standard than it should work.

but even if i change it to 775 (file and directory) i still get the error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35405">issues.joomla.org/tracker/joomla-cms/35405</a>.</sub>

**Comment by MoniqueNijboer** [comment]
changed everything to 777 and then it would update at last!
afterwards it didn't set it back to standard this time.
so i set it back to 755 and 644.
but then the website wasn't working as the user was wrong had to change user from www-data back to {user}

so either something in my system is not functioning, or Joomla update is not handeling the permissions correct.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35405">issues.joomla.org/tracker/joomla-cms/35405</a>.</sub>

**Comment by brianteeman** [comment]
You have an ownership problem

**Comment by MoniqueNijboer** [comment]
> You have an ownership problem

thanks, but how was this not showing before 3.10.1

and as i stated apache is running as www-data so when setting file/directory permission to www-data:www-data it should be working right.

how could this work with webmin/virtualmin, as they give permission to public_html as user:www-data.
apache running as www-data and write permission as user.

WP has similar issues
|https://archive.virtualmin.com/node/57063



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35405">issues.joomla.org/tracker/joomla-cms/35405</a>.</sub>

**Comment by PhilETaylor** [comment]
> WP has similar issues

Thus proving this is a hosting issue and not a Joomla issue.

**Comment by jwaisner** [comment]
Closing as this has been identified as a hosting issue, not related to Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35405">issues.joomla.org/tracker/joomla-cms/35405</a>.</sub>
