### ISSUE TITLE
Image upload fails from media manager

### ISSUE THREAD

**Issue by paydelott** [joomla/joomla-cms#35400]
### Steps to reproduce the issue
From Joomla 4.02 dashboard, upload media content.
Select appropriate image folder.
Browse to source image on local PC. Select one or more images.
Watch progress indicator on upload. 
See error message: "You don't have permission to access this. Please contact a website administrator if this is incorrect."
 

### Expected result
Small image files should upload without issues.

### Actual result
Images cannot be uploaded.

### System information (as much as possible)
Note: Upload also fails with JCE image manager.
Files can be upload to /images directory via file manager in cpanel.
File & folder permissions all set to 655.

**Comment by dgrammatiko** [comment]
> Note: Upload also fails with JCE image manager.

Uninstall JCE and report back if the problem persists

**Comment by paydelott** [comment]
I disabled JCE with no change in behavior. The system also constantly
requires me to login after every action. I manually upgraded to 4.02 with
no change in behavior.

Thanks for the suggestion.
Paul

**Comment by PhilETaylor** [comment]
well it uploads fail in JCE and uploads fail in Joomla - then its probably a hosting issue and not a Joomla issue. 

Fix permissions and ownership on files and folders and try again, also remove all .htaccess files and try again.

**Comment by PhilETaylor** [comment]
Please send a screenshot of this error page:

> See error message: "You don't have permission to access this. Please contact a website administrator if this is incorrect."

**Comment by paydelott** [comment]
I believe I uploaded a screenshot initially.

**Comment by brianteeman** [comment]
If you had done then you wouldn't have been asked to do it.

**Comment by paydelott** [comment]
The htaccess file is what ships with Joomla. The php version is 7.4.22. New site. Only Akeeba admin tools installed to verify file permissions. 
![screen](https://user-images.githubusercontent.com/5893264/131230745-8ad98251-5a87-4a78-940b-ef3dee189c70.png)

**Comment by dgrammatiko** [comment]
Can you upload on the folder `banners` or `headers`?

**Comment by PhilETaylor** [comment]
ok this is not a hosting issue. 

You are failing one of these checks:

```php
// Access check
		if (!$user->authorise('core.manage', 'com_media')
			&& (!$asset || (!$user->authorise('core.edit', $asset)
			&& !$user->authorise('core.create', $asset)
			&& count($user->getAuthorisedCategories($asset, 'core.create')) == 0)
			&& !($user->id == $author && $user->authorise('core.edit.own', $asset))))
		{
			throw new NotAllowed($this->app->getLanguage()->_('JERROR_ALERTNOAUTHOR'), 403);
		}
```

so ... the question is which, and why... 

Whats the history of this site? is it an upgrade? an upgrade from what? 

Please try applying the patch here https://github.com/joomla/joomla-cms/pull/35397 or testing the nightly build here https://developer.joomla.org/nightly-builds.html

**Comment by PhilETaylor** [comment]
Are you logged in as a super admin or other type of user?

**Comment by paydelott** [comment]
super admin. I even set up duplicate super accounts. No difference.

I first set up the account as an upgrade from a new 3.10. That initially
showed the problem. Then I did a manual reinstall copying all files from a
complete 4.02 version I had uploaded. No change.

**Comment by paydelott** [comment]
Added the edit action as advised. No change.

**Comment by PhilETaylor** [comment]
after adding it - go to the OPTIONS button in media manager and click save and close. And try again.

**Comment by brianteeman** [comment]
> Fix permissions and ownership on files and folders and try again, also remove all .htaccess files and try again.

> Then I did a manual reinstall copying all files from a complete 4.02 version I had uploaded. 

did you check the onwership?

**Comment by PhilETaylor** [comment]
This is not a file ownership issue. Its a Joomla ACL levels issue and [its failing in this access check](https://github.com/joomla/joomla-cms/issues/35400#issuecomment-907689369)

**Comment by paydelott** [comment]
Edited outside Joomla in cpanel and restarted Joomla.

**Comment by paydelott** [comment]
Attempted to login to home page to edit article and add image. 

First attempt: login successful with edit button appearing on home page article. JCE edit shows, image upload button works to select image, but attached error page shows. Apparently logged out from front-end.
Second and subsequent login attempt immediately show the attached error page.
![loginError](https://user-images.githubusercontent.com/5893264/131356464-d056b949-1400-4f02-a387-2762e517b733.png)
 Note: this is consistent with the same error in #35244. No caching either in Joomla or by Cloudflare. Website is shared hosting by Siteground.

**Comment by PhilETaylor** [comment]
> Siteground

Ok before we go any further go and DISABLE all the SiteGround CACHING features!!!

**Comment by paydelott** [comment]
All caches were turned off. Yeah, can't test with cache on.

**Comment by paydelott** [comment]
It appears that what is happening is that my session is being killed before the upload takes place. Therefore I must constantly login. This is the error showing in my host's error log:
2021-09-01 14:24:05 UTC [apache][:notice] [pid 81191] [client 67.143.160.151:54578] mod_hive matched URI http://dust-n-shavings.com/administrator/index.php (/home/u1577-wcezfu0gtrdi/www/dust-n-shavings.com/public_html/administrator/index.php) with match 10, referer: http://dust-n-shavings.com/administrator/

**Comment by PhilETaylor** [comment]
`mod_hive` Siteground by any chance?

**Comment by paydelott** [comment]
Yes. Perhaps this is a Siteground problem with their version of Apache?

**Comment by PhilETaylor** [comment]
`mod_hive` later known as 1h.com (ironically their own website is no longer working) is a Siteground security product. 

Move web hosts or turn off Siteground specific security tools - then test.

**Comment by paydelott** [comment]
Thanks. I'll take up the issue with Siteground.

**Comment by paydelott** [comment]
Advise to the wise. Forget Siteground as a host that specializes in Joomla. That appears to have changed. No help from their support desk.

**Comment by PhilETaylor** [comment]
> Forget Siteground as a host 

This happened several years ago when they first started increasing their prices by a huge percentage. They used to be the flagship forerunner but went down hill very very quickly :-( 

Their tech is still second to none - but it causes more issues than it solves on dynamic sites.
