### ISSUE TITLE
[3.10.1] Uncaught ReferenceError: COM_JOOMLAUPDATE_VIEW_DEFAULT_EXTENSIONS_SHOW_MORE_COMPATIBILITY_INFORMATION is not defined

### ISSUE THREAD

**Issue by krogias** [joomla/joomla-cms#35406]
### Steps to reproduce the issue
Pressing [More Detail >] on "Required PHP & Database Settings : Passed" or "Recommended PHP Settings : Passed" ect.

### Expected result
See more details

### Actual result
Nothing happens. Getting error "Uncaught ReferenceError: COM_JOOMLAUPDATE_VIEW_DEFAULT_EXTENSIONS_SHOW_MORE_COMPATIBILITY_INFORMATION is not defined" in .../media/com_joomlaupdate/js/default.js

### System information (as much as possible)
Webserver: Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.7

**Comment by brianteeman** [comment]
Which language are you running Joomla in?

**Comment by krogias** [comment]
English and Greek. Backend English.

**Comment by krogias** [comment]
Anyone else with the same issue? I can't even see the Update button.

**Comment by joomdonation** [comment]
@krogias Unfortunately, I could not re-procedure the issue. Could you please look at browser console (before you press on More Detail....) to see if there are any (js) errors?

And just want to be clear, you are on 3.10.1 already and want to update (to Joomla 4 ?) ?

**Comment by krogias** [comment]
@joomdonation  Yes, 3.10.1 and want to update to 4.0. I hope those screen shots will help:
Before pressing More Detail:
![issue](https://user-images.githubusercontent.com/8203277/131881519-80fb4acb-f5cd-46c2-b618-e04b16916136.png)
After pressing More Detail:
![issue2](https://user-images.githubusercontent.com/8203277/131882131-06985215-beaa-4c67-843b-ede57366147c.png)

**Comment by joomdonation** [comment]
Yes. I can see that there is some js error causes by the translation of the language item COM_JOOMLAUPDATE_VIEW_DEFAULT_EXTENSIONS_SHOW_MORE_COMPATIBILITY_INFORMATION to your language. That should be fixed.

However, a quick workaround you can use now is login to administrator area of your site using English language and you should not get the error and can progress with the upgrade.

**Comment by joomdonation** [comment]
@krogias Or if you don't want to switch language to English, get this file, unzip it, upload to administrator/components/com_joomlaupdate/views/default/tmpl folder to replace original file should address the issue, too
[default_preupdatecheck.zip](https://github.com/joomla/joomla-cms/files/7100541/default_preupdatecheck.zip)

**Comment by krogias** [comment]
@joomdonation I am always using English language in backend. My browser is in Greek. 
I 've also uploaded your default_preupdatecheck.php, with no change unfortunately.

**Comment by joomdonation** [comment]
@krogias From what I see from your screenshot, the Greek language string is used there, and it causes javascript error. In theory, the file I sent you should fix it but I don't know why it does not work for you

If you want, you can send super admin account of your site to tuanpn@joomdonation.com. I will take a quick look for you and get it sorted for you. Should be easy.

**Comment by krogias** [comment]
@joomdonation I am sorry but it's forbidden to give super admin accounts. Are you sure it is a javascript error because of the greek string language? I am pretty sure that I am using only English in my backend. 
![engl](https://user-images.githubusercontent.com/8203277/131991485-b0ab1686-1eca-41ef-8ff1-2cf710ca5fd3.jpg)

**Comment by joomdonation** [comment]
@krogias I can only guess :). Maybe you can view source of the page, copy the source into a text file and upload it here so that I can take a look to see if I can see what's wrong without having access to your site?

**Comment by krogias** [comment]
@joomdonation I hope this will help: 
[source.txt](https://github.com/joomla/joomla-cms/files/7105623/source.txt)

**Comment by joomdonation** [comment]
@krogias  Look like it is not full source code of the page? If it is just the attached code, I don't see anything wrong.

**Comment by krogias** [comment]
@joomdonation check your inbox

**Comment by joomdonation** [comment]
@krogias Replied you via email with instructions.

**Comment by krogias** [comment]
@joomdonation oh, yes! That was it! Disabling the extension "System - Perfect Publisher for Google's structured data / Social Profile Links" solved the problem!
Thank you!

**Comment by krogias** [comment]
@joomdonation oh, yes! That was it! Disabling the extension "System - Perfect Publisher for Google's structured data / Social Profile Links" solved the problem!
Thank you!

**Comment by anibalsanchez** [comment]
### Steps to reproduce the issue

1. We have a plugin name that has the string "Google's structured data".
2. com_joomlaupdate generates this JavaScript var declaration:

```javascript
var nonCoreCriticalPlugins = '...."3":{"name":"System - Perfect Publisher for Google's structured data \/ Social Profile Links"....';
```

3. The JSON structure is correctly defined including the ' character, but the JavaScript is invalid when the variable is assigned.
4. Uncaught SyntaxError: Unexpected identifier

### Expected result

Support of plugin names that include a ' character.

### Actual result

Browser console error: Uncaught SyntaxError: Unexpected identifier

### System information (as much as possible)

Joomla 3.10.1 and a plugin with a name that includes a ' character.

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/35481 should address this issue. @krogias @anibalsanchez Could you please help testing?

**Comment by krogias** [comment]
Tested successfully

**Comment by anibalsanchez** [comment]
Tested successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35406">issues.joomla.org/tracker/joomla-cms/35406</a>.</sub>
