### ISSUE TITLE
[3] npm ci leaves git tracked modifications

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35413]
### Steps to reproduce the issue

Paging @dgrammatiko ?

r.m..-.R.f..* 
git checkout 4.0-dev
git reset --hard
npm ci

### Expected result

No tracked git files modified , nothing reported modified

### Actual result

2 files modified

<img width="528" alt="Screenshot 2021-08-29 at 00 28 15" src="https://user-images.githubusercontent.com/400092/131233440-cbb12455-7979-48f0-aba1-bb9907bd970e.png">

The change is the whole `window.errorLocale` object.

<img width="2440" alt="Screenshot 2021-08-29 at 00 29 50" src="https://user-images.githubusercontent.com/400092/131233457-7d8b7d36-f3dc-478e-923b-1b73af4519fb.png">

Does this just mean we now have more languages and someone needs to commit this change? 

### System information (as much as possible)

mac

**Comment by dgrammatiko** [comment]
Well, https://github.com/joomla/joomla-cms/pull/35098#issuecomment-900697028

**Comment by PhilETaylor** [comment]
So close this and let @HLeithner fix it?
