### ISSUE TITLE
[3.10.x] All help links in backend do not work because there is no 3.10 help in the docs

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#35414]
### Steps to reproduce the issue

See https://github.com/joomla/help.joomla.org/issues/32

### Additional comments

No idea what's the right place to fix that. Normally I would think it is https://github.com/joomla/help.joomla.org/issues , but that repository seems to be not very active in recent times.

We could change the backend links in 3.10 back to using "keyref=Help39" instead of "keyref=Help310". That would work, but that would not be very nice, I think.

**Comment by brianteeman** [comment]
its a setting on the docs site iirc

**Comment by richard67** [comment]
I hope so. So not a CMS issue, but maybe should I leave this here open as reminder or reference?

**Comment by wilsonge** [comment]
These should be fixed now

**Comment by richard67** [comment]
Confirmed.

**Comment by brianteeman** [comment]
@wilsonge please add this to the release procedure documentation https://docs.joomla.org/Joomla:Release_procedure_and_checklist

**Comment by ghost** [comment]
@wilsonge last update of https://docs.joomla.org/Joomla:Release_procedure_and_checklist was 2018. I would update the document if you give me a text but i do not have permission to edit pages in the Joomla namespace.
