### ISSUE TITLE
[J4] Backend sidebar/wrapper not full height of page

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#35425]
### What needs to be fixed
The sidebar/wrapper element in the backend doesn't take the full navigator height, there's always ~3px between the bottom of the sidebar and the bottom of the page if the main content of the page doesn't itself take the full page.
![image](https://user-images.githubusercontent.com/32301627/131361438-ab7d6324-b775-4274-b74e-261e2f38208e.png)

### Why this should be fixed
It's oddly distracting.

### How would you fix it
Fiddling around with what styles are loaded, there are 2 solutions I've noted.
A) Add the class flex-grow-1 to the div with the id "wrapper"
B) Edit the styles of .sidebar-wrapper, modifying `min-height: calc(100vh - 69px)` to `min-height: calc(100vh - 66px)` (The header is 66px tall, not 69px)

### Side Effects expected
Option A really shouldn't have any long term affects on the template, but Option B might require re-tuning if the header ever changes sizes

**Comment by PhilETaylor** [comment]
Already fixed - see prs

**Comment by Chaosxmk** [comment]
Perfect, I searched for issues/prs using a different key term. Closing.

**Comment by Quy** [comment]
@Chaosxmk Please test PR #35412. Thanks.
