### ISSUE TITLE
issues.joomla.org reveals a dump

### ISSUE THREAD

**Issue by stAn47** [joomla/joomla-cms#35428]
Submitting a bug into issues.joomla.org reveals a dump of all variables available to PHP - i experienced it during submission of this bug: https://github.com/joomla/joomla-cms/issues/35427

best regards, stan

**Comment by stAn47** [comment]
i.e.: 
```
array(7) { [0]=> array(7) { ["file"]=> string(50) "/home/i...../src/App/Tracker/Model/IssueModel.php" ["line"]=> int(445) ["function"]=> string(8) "getState" ["class"]=> string(43) "JTracker\Model\AbstractTrackerDatabaseModel" ["object"]=> object(App\Tracker\Model\IssueModel)#313 (7) { ["context":protected]=> string(17) "com_tracker.issue" ["name":protected]=> string(5) "Issue" ["option":protected]=> string(7) "Tracker" ["table":protected]=> NULL ["project":"JTracker\Model\AbstractTrackerDatabaseModel":private]=> object(App\Projects\TrackerProject)#350 (13) { ["project_id":protected]=> int(1) ["title":protected]=> string(11) "Joomla! CMS" ["alias":protected]=> string(10) "joomla-..." ["gh_user":protected]=> string(6) "j....." ["gh_project":protected]=> string(10) "j.." ["gh_editbot_user":protected]=> string(14) "joomla..." ["gh_editbot_pass":protected]=> string(40) "b
```

**Comment by alikon** [comment]
ok but you should open this issue on the correct repo https://github.com/joomla/jissues/issues

**Comment by alikon** [comment]
please open a on that repo https://github.com/joomla/jissues/issues

**Comment by stAn47** [comment]
ok, i now did, just for the reference - https://github.com/joomla/jissues/issues/1133

**Comment by PhilETaylor** [comment]
You should never have posted this on the tracker - just like the issue template told you, it should have been emailed direct to Joomla! Security Strike Team <security@joomla.org>

**Comment by stAn47** [comment]
my apologies for not evaluating this correctly, i didn't really expect this to be that serious. 
kind regards, stan

**Comment by PhilETaylor** [comment]
Exposing the Github Credentials for any app that has read and write access... yeah I would say that was serious.
