### ISSUE TITLE
[4.0.2] Install fails with File not found - though files are accessible

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#35423]
install plugin which creates sql-table

### Expected result
Install should works succesfully as it installs successfully with joomla 3.10.1

### Actual result
get istaller error
```
Warning
JInstaller: :Install: SQL File not found C:\myjoomla4\plugins/system/jphp/sql/jphp.install.sql
Extension installation aborted
```

### System information (as much as possible)
defined sql-install:
```
        <install>
		<sql>
			<file driver="mysqli" charset="utf8">sql/jphp.install.sql</file>
		</sql>
	</install> 
```
### Additional comments
Install process finishes succsessfull if "driver" is ommitted - but then sql-tabel is not installed.

**Comment by jschmi102** [comment]
hi,
found the problem joomla4 neesds a "`<folder>sql</folder>`" otherwise it fails to find the sql install files

**Comment by chmst** [comment]
Thanks for reporting the solution. So I close the issue for now.
