### ISSUE TITLE
Inconsistency in backend com_templates.ini in j4.0.2 langpack

### ISSUE THREAD

**Issue by jofrank** [joomla/joomla-cms#35422]
The last language constant of the file is JLIB_RULES_SETTING_NOTES. To be consistent with the other components this should be JLIB_RULES_SETTING_NOTES_COM_TEMPLATES.

**Comment by Kostelano** [comment]
It is not only there that needs to be changed. For example, also in the [com_categories.ini](https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/language/en-GB/com_categories.ini#L79).

**Comment by wojsmol** [comment]
@Kostelano @jofrank Please test https://github.com/joomla/joomla-cms/pull/35424

**Comment by alikon** [comment]
closing as we have a pr #35424
