### ISSUE TITLE
\\\' "' what?

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#35432]
Not sure how \\\' explode \\\" this\\? \'

**Comment by PhilETaylor** [comment]
<img width="631" alt="Screenshot 2021-08-30 at 22 53 42" src="https://user-images.githubusercontent.com/400092/131410778-88207849-3602-4c22-b7e5-b2d137c98400.png">

**Comment by HLeithner** [comment]
thanks ;-) I know

**Comment by PhilETaylor** [comment]
Yeah I know too...
