### ISSUE TITLE
J4.0 Debug plugin: Debug bar doesn't display logs and deprecated tabs by default, while setting's default is ON

### ISSUE THREAD

**Issue by beat** [joomla/joomla-cms#35454]
The Debug system plugin's setting Logging tab / Logging fieldset / "Log Entries" (PLG_DEBUG_FIELD_LOGS_LABEL, param `logs`) has a different default value of 1/true/ON in the settings, but false/0/OFF in the code.

Result is that as long as the DEBUG plugin settings have not been saved, the logs/deprecation tab of the debug bad are not displayed.

XML file default setting: https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/system/debug/debug.xml#L227
PHP file default setting: https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/system/debug/debug.php#L179

### Steps to reproduce the issue

- Fresh Joomla install
- Turn debugging and logging on in global configuration
- Open the debug bar by clicking the joomla logo at top bottom

### Expected result

See "Log", "Deprecated" and "Deprecation notices" tabs on the right of "J! Info Request Session Profile Queries" tabs.

### Actual result

Seeing only "J! Info Request Session Profile Queries" tabs.

Then when just saving the Joomla plugin Debug settings WITHOUT changing them, those See "Log", "Deprecated" and "Deprecation notices" tabs suddenly display on the right of "J! Info Request Session Profile Queries" as expected.

### System information (as much as possible)

Vanilla Joomla 4.0.2, on any platform.

**Comment by beat** [comment]
Proposing PR #35455 to fix this bug.

**Comment by alikon** [comment]
closing as we have a pr #35455
