### ISSUE TITLE
[4] feeds.joomla.org in testing data needs replacing

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35461]
### Steps to reproduce the issue

TODO: feeds.joomla.org is dead and should no longer be used. 
https://github.com/joomla/joomla-cms/blob/1a6f5aeb49bee4ee78b3a245cd30b42bd2786c07/plugins/sampledata/testing/testing.php#L1429
### Expected result

Replace all instances of feeds.joomla.org with other example feeds. 

### Actual result

feeds.joomla.org is dead.

**Comment by Quy** [comment]
Please test PR #37136. Thanks.
