### ISSUE TITLE
Category list uses popovers in table header

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#35467]
### Steps to reproduce the issue
Have a look on the category list in cassiopeia with blog sample data

### Expected result
Table header with Tooltips, not popvers.

### Actual result
![grafik](https://user-images.githubusercontent.com/1035262/131897635-fbc014c6-d871-4458-913e-3b7dfee86a75.png)

**Comment by Shubhamverma2796** [comment]
Can you please elaborate the issue? I want to work on it.

**Comment by chmst** [comment]
In J4 we do not longer want popovers. 
You can compare overviews in the backend. How is the table header coded there? Maybe you can adapt the frontend view in this way?

**Comment by chmst** [comment]
Closed as we have a PR. #36202

**Comment by brianteeman** [comment]
Plkease re-open
