### ISSUE TITLE
Broken update server for 4.1 Nightly Builds

### ISSUE THREAD

**Issue by dmitriy-cloudaccess** [joomla/joomla-cms#35462]
On nightly builds page https://developer.joomla.org/nightly-builds.html
in 4.1 section the update server is pointed  as https://update.joomla.org/core/nightlies/next_minor_list.xml
It points to details url https://update.joomla.org/core/nightlies/next_minor_extension.xml
which contains the update version `4.1.0-dev` and download url https://developer.joomla.org/nightlies/Joomla_4.1.0-dev-Development-Update_Package.zip
This url is broken (returns 404).
Correct url found on https://developer.joomla.org/nightly-builds.html is https://developer.joomla.org/nightlies/Joomla_4.1.3-dev-Development-Update_Package.zip
and version is 4.1.3-dev.
So it seems information in https://update.joomla.org/core/nightlies/next_minor_list.xml and https://update.joomla.org/core/nightlies/next_minor_extension.xml is not being updated.

**Comment by zero-24** [comment]
@bembelimen can you please check the version in the 4.1-dev branch? Seems the [last upmerge](https://github.com/joomla/joomla-cms/commit/894d743f0a9fd50bbf26ea16bf80d569548c5b00#diff-33b71db81de67ed59567ae47bb51efda9a1fa125fb426e0f8564c4dfbd9910a3R53) got the version wrong.

@dmitriy-cloudaccess the version in the xml is correct but the version in the 4.1-dev branch is wrong. ;)

**Comment by bembelimen** [comment]
Thx, fixed here https://github.com/joomla/joomla-cms/commit/5bffadde691d2c2c9dc05316cfe5022748cbb9b4

**Comment by zero-24** [comment]
Thanks closing here 👍
