### ISSUE TITLE
[4.0] Template style is the one of the Home page instead of default

### ISSUE THREAD

**Issue by barsdeveloper** [joomla/joomla-cms#35465]
### Steps to reproduce the issue
Create a new template style
Make it default
Try to open a page that isn't assigned to a menu (like module edit or user profile)

### Expected result
It should use the default template style

### Actual result
It uses the style of the home page

**Comment by PhilETaylor** [comment]
I cannot replicate this in Joomla 4.0.3-dev/PHP8.0.10

I: 
- Duplicated "Cassiopeia - Default" and called it MINE and before saving made changes like turning off brand, changing the colour theme, and enabling the three options 

<img width="935" alt="Screenshot 2021-09-07 at 19 27 42" src="https://user-images.githubusercontent.com/400092/132393376-06ac29f2-9699-4756-85a2-c694434a431c.png">

I also set it to default and saved:

<img width="1027" alt="Screenshot 2021-09-07 at 19 28 09" src="https://user-images.githubusercontent.com/400092/132393430-0076c327-6c7c-4ba1-8366-1071cf634578.png">

Then I logged into the frontend as a super admin and tried to edit a module and I was CORRECTLY given my new style

<img width="1576" alt="Screenshot 2021-09-07 at 19 28 56" src="https://user-images.githubusercontent.com/400092/132393559-4ca3207b-d98d-45fd-9304-9ff805f17b6e.png">

I then tried the profile edit page `index.php?option=com_users&view=profile&layout=edit` and again got the right customised template style.

**Comment by brianteeman** [comment]
Module edit would use the style of the page that you are editing the modules on. 

In my test (just like @PhilETaylor ) if i edit the modules on the home page the template style used is as expected the template style of the home page and if I edit the modules of another page that is using the default template style then its is as expected using the default template style.

Pages that have no menu item at all (unless created) will always use the settings of the default homepage. That would include the template styles and modules.

**Comment by barsdeveloper** [comment]
> 
> 
> Module edit would use the style of the page that you are editing the modules on.
> 
> In my test (just like @PhilETaylor ) if i edit the modules on the home page the template style used is as expected the template style of the home page and if I edit the modules of another page that is using the default template style then its is as expected using the default template style.
> 
> Pages that have no menu item at all (unless created) will always use the settings of the default homepage. That would include the template styles and modules.

Ahh so it is expected behavior. But this creates (depending on the type of settings the template has) profoundly different user experience determined by the page the module is edited on. Is there a way to prevent this behavior? I mean even a snippet of code to put in some template override.

**Comment by brianteeman** [comment]
You could take a look at this free plugin https://extensions.joomla.org/extension/clean-edit/

**Comment by jwaisner** [comment]
Closing as this is expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35465">issues.joomla.org/tracker/joomla-cms/35465</a>.</sub>
