### ISSUE TITLE
[4.x][BUG] Color form field onchange property not handled properly

### ISSUE THREAD

**Issue by thednp** [joomla/joomla-cms#35464]
### Steps to reproduce the issue
* Open a templateDetails.xml for any template (Cassiopeia) 
* Paste inside `<fieldset name="basic">` the following sample field
```markup
<field 
      name="color_fill"
      type="Color"
      label="Color onchange test"
      format="rgb"
      default="rgb(0, 102, 153)"
      onchange="console.log(this.value)" />
```

### Expected result
The browser console throws logs of `rgba()` values.

### Actual result
Nothing happens as the markup of the field is wrong, see below (some attributes removed)

```markup
<input
  type="text" name="color_fill" id="color_fill" 
  value="rgb(0, 102, 153)"
  placeholder="rgb(0, 0, 0)"
  class="form-control minicolors rgb minicolors-input"
  data-position="default"
  data-control="advanced"
  console.log(this.value)=""
  data-format="rgb" data-opacity="1.00">
```

### System information (as much as possible)
Joomla 4.0.2, I think this issue is also present in Joomla 3.x as well.

### Additional comments
I might commit some possible fix, anyone interested in testing and pushing this into the stable release?

**Comment by Quy** [comment]
Please test PR #30743 for v3.10.

**Comment by thednp** [comment]
More details on the progress at #30743 closing the issue.
