### ISSUE TITLE
Joomla\CMS\HTML\Helpers\Bootstrap::loadCss Not load RTL css file

### ISSUE THREAD

**Issue by sinahaghparast** [joomla/joomla-cms#35472]
### What needs to be fixed
Joomla\CMS\HTML\Helpers\Bootstrap::loadCss

### Why this should be fixed
Not support RTL css

### How would you fix it
1- upload RTL version css file from https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.rtl.min.css in media folder.
2- change loadCss function code, and use $direction to select which file load.

### Side Effects expected
This way can create and manage RTL template fine.
[rtl.txt](https://github.com/joomla/joomla-cms/files/7105234/rtl.txt)

**Comment by richard67** [comment]
> upload RTL version css file from https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.rtl.min.css in media folder.

@sinahaghparast Joomla 4 uses Bootstrap 5.0, not 5.1.

**Comment by brianteeman** [comment]
This should be closed as there is nothing useful to respond with based on the information provided

**Comment by richard67** [comment]
Closing as stated above. No reaction since January 16.
