### ISSUE TITLE
JSON var nonCoreCriticalPlugins not correctly escaped

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#35475]
### Steps to reproduce the issue

1. We have a plugin name that has the string "Google's structured data".
2. com_joomlaupdate generates this JavaScript var declaration:

```javascript
var nonCoreCriticalPlugins = '...."3":{"name":"System - Perfect Publisher for Google's structured data \/ Social Profile Links"....';
```

3. The JSON structure is correctly defined including the ' character, but the JavaScript is invalid when the variable is assigned.
4. Uncaught SyntaxError: Unexpected identifier

### Expected result

Support of plugin names that include a ' character.

### Actual result

Browser console error: Uncaught SyntaxError: Unexpected identifier

### System information (as much as possible)

Joomla 3.10.1 and a plugin with a name that includes a ' character.

**Comment by alikon** [comment]
better to merge with #35406 ?

**Comment by anibalsanchez** [comment]
Yes, it is the same issue.
