### ISSUE TITLE
include_once for Cache/Lite.php errors under php 8

### ISSUE THREAD

**Issue by skurvish** [joomla/joomla-cms#35487]
### Steps to reproduce the issue
Upgrade to php8
Set Joomla error reporting to anything but none
Attempt to access site

### Expected result
Access successful

### Actual result
500 error include_once(Cache/Lite.php): Failed to open stream: No such file or directory

### Additional comments
PHP8 seems to be throwing this error whenever the included file is missing if the error reporting is anything other than none. J4 does not have this issue as the cache Lite has been removed.

I originally thought this was j3.10 specific but on further though expect the same issue any any J3 rlease.

**Comment by PhilETaylor** [comment]
This is not a Joomla issue. 

I cannot replicate this with the steps to reproduce. I believe the ket thing you are not telling us is that your site is already configured to use Cache_Lite in Joomla Global Config before you upgraded PHP. 

There is only one place in Joomla 3 code that attempts to `include_once` the `Cache/Lite.php` file and that is in 

https://github.com/joomla/joomla-cms/blob/742de2e8b2a6ace38eb235d90130245eca3bff60/libraries/src/Cache/Storage/CacheliteStorage.php#L347

However, even if I set error_reporting to development and display_errors on, I still dont get a 500 Internal Server error like you describe, all I can get is this when accessing Global Config (the only place that calls the above code) 

<img width="1347" alt="Screenshot 2021-09-06 at 16 05 46" src="https://user-images.githubusercontent.com/400092/132236614-d5e2fbcb-872c-4b04-bdba-d6e0c98c7019.png">

Therefore there must be something else going on withy our site. 

Also note, that probably all the main contributors to Joomla core work all day every day with error reporting set to development and mostly now with PHP 8, if your steps to reproduce were accurate we would probably have seen this issue before. 

-- 

Cache_Lite is not shipped with Joomla and is not shipped with PHP - it is a pear installable extension and thus NEEDS TO BE INSTALLED for each series of PHP you run.

What I believe you have done, is upgrade to PHP 8- but you have not correctly configured your PHP 8 the same way you have your previous versions of PHP - i.e you have not yet installed Cache_Lite using the pear distribution. 

You need to install Cache_Lite using pear for your new PHP version - then Joomla can include it 

However, please note https://pear.php.net/package/Cache_Lite/ package is not maintained, and is unlikely to continue working for long. The last version 1.8.3 was released in 2019, and thus predates PHP 8 and therefore might not even be compatible (Ive not tested)

What is for certain though, is this is not a Joomla root caused issue.

**Comment by skurvish** [comment]
Thanks Phil. Installing the Cache_Lite pear package did in fact solve the problem. The question I have now though is why? I have caching disabled which I would have thought would not then attempt to perform this include. I do not remember ever having enabled anything in Joomla for this support.

Do you know where the configuration for this would be?

**Comment by skurvish** [comment]
In order to do that I need to uninstall the pear package. I have done so but the problem is no longer occurring. Very strange.

**Comment by skurvish** [comment]
OK, forget that previous comment, I hadn't enabled error reporting. Below is the stack trace:

KExceptionError | Warning [500]
include_once(Cache/Lite.php): Failed to open stream: No such file or directory
.../libraries/src/Cache/Storage/CacheliteStorage.php:347
342 	 *
343 	 * @since   3.0.0
344 	 */
345 	public static function isSupported()
346 	{
347 		@include_once 'Cache/Lite.php';
348 
349 		return class_exists('\Cache_Lite');
350 	}
351 }
include_once() Joomla\CMS\Cache\Storage\CacheliteStorage::isSupported() Joomla\CMS\Cache\Cache::getStores() JFormFieldCacheHandler->getOptions() JFormFieldList->getInput() Joomla\CMS\Form\FormField->__get() JFormFieldList->__get() include() Joomla\CMS\Layout\FileLayout->render() Joomla\CMS\Layout\LayoutHelper::render() include() ConfigViewCmsHtml->loadTemplate() include() JViewHtml->render() ConfigViewApplicationHtml->render() ConfigControllerDisplay->execute() require_once() Joomla\CMS\Component\ComponentHelper::executeComponent() Joomla\CMS\Component\ComponentHelper::renderComponent() Joomla\CMS\Application\AdministratorApplication->dispatch() Joomla\CMS\Application\AdministratorApplication->doExecute() Joomla\CMS\Application\CMSApplication->execute()
include_once()
.../libraries/src/Cache/Storage/CacheliteStorage.php:347
342 	 *
343 	 * @since   3.0.0
344 	 */
345 	public static function isSupported()
346 	{
347 		@include_once 'Cache/Lite.php';
348 
349 		return class_exists('\Cache_Lite');
350 	}
351 }
Joomla\CMS\Cache\Storage\CacheliteStorage::isSupported()
.../libraries/src/Cache/Cache.php:128
123 			{
124 				continue;
125 			}
126 
127 			// Sweet!  Our class exists, so now we just need to know if it passes its test method.
128 			if ($class::isSupported())
129 			{
130 				// Connector names should not have file extensions.
131 				$handler = str_ireplace('Storage.php', '', $fileName);
132 				$handler = str_ireplace('.php', '', $handler);
133 				$handlers[] = strtolower($handler);
Joomla\CMS\Cache\Cache::getStores()
.../libraries/joomla/form/fields/cachehandler.php:43
38 	protected function getOptions()
39 	{
40 		$options = array();
41 
42 		// Convert to name => name array.
43 		foreach (JCache::getStores() as $store)
44 		{
45 			$options[] = JHtml::_('select.option', $store, JText::_('JLIB_FORM_VALUE_CACHE_' . $store), 'value', 'text');
46 		}
47 
48 		$options = array_merge(parent::getOptions(), $options);
JFormFieldCacheHandler->getOptions()
.../libraries/joomla/form/fields/list.php:58
53 
54 		// Initialize JavaScript field attributes.
55 		$attr .= $this->onchange ? ' onchange="' . $this->onchange . '"' : '';
56 
57 		// Get the field options.
58 		$options = (array) $this->getOptions();
59 
60 		// Create a read-only list (no name) with hidden input(s) to store the value(s).
61 		if ((string) $this->readonly == '1' || (string) $this->readonly == 'true')
62 		{
63 			$html[] = JHtml::_('select.genericlist', $options, '', trim($attr), 'value', 'text', $this->value, $this->id);
JFormFieldList->getInput()
.../administrator/components/com_fabrik/classes/310/FormField.php:425
420 
421 			case 'input':
422 				// If the input hasn't yet been generated, generate it.
423 				if (empty($this->input))
424 				{
425 					$this->input = $this->getInput();
426 				}
427 
428 				return $this->input;
429 
430 			case 'label':
Joomla\CMS\Form\FormField->__get()
.../libraries/joomla/form/fields/list.php:277
272 		if ($name == 'options')
273 		{
274 			return $this->getOptions();
275 		}
276 
277 		return parent::__get($name);
278 	}
279 }
JFormFieldList->__get()
.../layouts/joomla/content/options_default.php:33
28 			<?php endif; ?>
29 			<div class="control-group<?php echo $groupClass; ?>"<?php echo $datashowon; ?>>
30 				<?php if (!isset($displayData->showlabel) || $displayData->showlabel) : ?>
31 					<div class="control-label"><?php echo $field->label; ?></div>
32 				<?php endif; ?>
33 				<div class="controls"><?php echo $field->input; ?></div>
34 			</div>
35 		<?php endforeach; ?>
36 	<?php endforeach; ?>
37 </fieldset>
include()
.../libraries/src/Layout/FileLayout.php:125
120 		{
121 			return $layoutOutput;
122 		}
123 
124 		ob_start();
125 		include $path;
126 		$layoutOutput .= ob_get_contents();
127 		ob_end_clean();
128 
129 		return $layoutOutput;
130 	}
Arguments
0	
string(56) "/var/www/html/layouts/joomla/content/options_default.php"
Joomla\CMS\Layout\FileLayout->render()
.../libraries/src/Layout/LayoutHelper.php:73
68 
69 		// Make sure we send null to FileLayout if no path set
70 		$basePath = empty($basePath) ? null : $basePath;
71 		$layout = new FileLayout($layoutFile, $basePath, $options);
72 
73 		return $layout->render($displayData);
74 	}
75 }
Joomla\CMS\Layout\LayoutHelper::render()
.../administrator/components/com_config/view/application/tmpl/default_cache.php:14
 9 
10 defined('_JEXEC') or die;
11 
12 $this->name = JText::_('COM_CONFIG_CACHE_SETTINGS');
13 $this->fieldsname = 'cache';
14 echo JLayoutHelper::render('joomla.content.options_default', $this);
include()
.../components/com_config/view/cms/html.php:142
137 			// Start capturing output into a buffer
138 			ob_start();
139 
140 			// Include the requested template filename in the local scope
141 			// (this will execute the view logic).
142 			include $this->_template;
143 
144 			// Done with the requested template; get the buffer and
145 			// clear it.
146 			$this->_output = ob_get_contents();
147 			ob_end_clean();
Arguments
0	
string(89) "/var/www/html/administrator/components/com_config/view/application/tmpl/default_cache.php"
ConfigViewCmsHtml->loadTemplate()
.../administrator/components/com_config/view/application/tmpl/default.php:87
82 				<div id="page-system" class="tab-pane">
83 					<div class="row-fluid">
84 						<div class="span12">
85 							<?php echo $this->loadTemplate('system'); ?>
86 							<?php echo $this->loadTemplate('debug'); ?>
87 							<?php echo $this->loadTemplate('cache'); ?>
88 							<?php echo $this->loadTemplate('session'); ?>
89 						</div>
90 					</div>
91 				</div>
92 				<div id="page-server" class="tab-pane">
include()
.../libraries/joomla/view/html.php:151
146 
147 		// Start an output buffer.
148 		ob_start();
149 
150 		// Load the layout.
151 		include $path;
152 
153 		// Get the layout contents.
154 		$output = ob_get_clean();
155 
156 		return $output;
Arguments
0	
string(83) "/var/www/html/administrator/components/com_config/view/application/tmpl/default.php"
JViewHtml->render()
.../administrator/components/com_config/view/application/html.php:79
74 
75 		$this->userIsSuperAdmin = $user->authorise('core.admin');
76 
77 		$this->addToolbar();
78 
79 		return parent::render();
80 	}
81 
82 	/**
83 	 * Add the page title and toolbar.
84 	 *
ConfigViewApplicationHtml->render()
.../components/com_config/controller/display.php:114
109 				$this->app->allowCache(false);
110 				return $view->render();
111 			}
112 
113 			// Render view.
114 			echo $view->render();
115 		}
116 
117 		return true;
118 	}
119 }
ConfigControllerDisplay->execute()
.../administrator/components/com_config/config.php:31
26 $controller = $controllerHelper->parseController($app);
27 
28 $controller->prefix = 'Config';
29 
30 // Perform the Request task
31 $controller->execute();
require_once()
.../libraries/src/Component/ComponentHelper.php:402
397 	 * @since   1.7
398 	 */
399 	protected static function executeComponent($path)
400 	{
401 		ob_start();
402 		require_once $path;
403 
404 		return ob_get_clean();
405 	}
406 
407 	/**
Arguments
0	
string(60) "/var/www/html/administrator/components/com_config/config.php"
Joomla\CMS\Component\ComponentHelper::executeComponent()
.../libraries/src/Component/ComponentHelper.php:377
372 
373 		// Handle template preview outlining.
374 		$contents = null;
375 
376 		// Execute the component.
377 		$contents = static::executeComponent($path);
378 
379 		// Revert the scope
380 		$app->scope = $scope;
381 
382 		if (JDEBUG)
Joomla\CMS\Component\ComponentHelper::renderComponent()
.../libraries/src/Application/AdministratorApplication.php:101
 96 
 97 		$document->setTitle($this->get('sitename') . ' - ' . \JText::_('JADMINISTRATION'));
 98 		$document->setDescription($this->get('MetaDesc'));
 99 		$document->setGenerator('Joomla! - Open Source Content Management');
100 
101 		$contents = ComponentHelper::renderComponent($component);
102 		$document->setBuffer($contents, 'component');
103 
104 		// Trigger the onAfterDispatch event.
105 		\JPluginHelper::importPlugin('system');
106 		$this->triggerEvent('onAfterDispatch');
Joomla\CMS\Application\AdministratorApplication->dispatch()
.../libraries/src/Application/AdministratorApplication.php:159
154 		 * ex: due of the sef urls
155 		 */
156 		$this->checkUserRequireReset('com_admin', 'profile', 'edit', 'com_admin/profile.save,com_admin/profile.apply,com_login/logout');
157 
158 		// Dispatch the application
159 		$this->dispatch();
160 
161 		// Mark afterDispatch in the profiler.
162 		JDEBUG ? $this->profiler->mark('afterDispatch') : null;
163 	}
164 
Joomla\CMS\Application\AdministratorApplication->doExecute()
.../libraries/src/Application/CMSApplication.php:225
220 		{
221 			throw new \RuntimeException('Invalid input, aborting application.');
222 		}
223 
224 		// Perform application routines.
225 		$this->doExecute();
226 
227 		// If we have an application document object, render it.
228 		if ($this->document instanceof \JDocument)
229 		{
230 			// Render the application output.
Joomla\CMS\Application\CMSApplication->execute()
.../administrator/index.php:51
46 
47 // Instantiate the application.
48 $app = JFactory::getApplication('administrator');
49 
50 // Execute the application.
51 $app->execute();

**Comment by PhilETaylor** [comment]
And there we have the clue I needed

‘KExceptionError’

this is not a Joomla issue - this is an issue in the JoomlaTools (DocMan, LogMan suite of tools) library framework overwriting the default and Joomla error handlers.

**Comment by skurvish** [comment]
OK, great! I will revert back to them. Thanks for finding that. I am closing this issue.

**Comment by skurvish** [comment]
OK, so now I seem to be in the middle. Here is what Joomlatools has to say about it:

Happy to assist you. From the report info you link too the error you are experiencing is Joomla error.

Our framework has a build in more advanced error handling and error reporting system that is activated when you put your site into debug mode. We promote PHP execution errors too Exceptions inline with the changes made in PHP7: "PHP 7 changes how most errors are reported by PHP. Instead of reporting errors through the traditional error reporting mechanism used by PHP 5, most errors are now reported by throwing Error exceptions." "https://www.php.net/manual/en/language.errors.php7.php"

An error report is generated from the exception including a backtrace if possible, a reference to KExceptionError is included since that is the class that wraps the error and handles it. There are different classes for different types of exceptipns. In this case it's an Error throw an Exception. This doesn't mean however that the error is a problem with any of our extensions. We just caught it. The actual error is the one you reported initially: 500 error include_once(Cache/Lite.php): Failed to open stream: No such file or directory

This does indeed sound like a bug in Joomla 3.10 and the information you provided in the bug report is correct. The "Cache/Lite.php" file doesn't exist or is not readable. A quick check in the Joomla bug trackers reveils follwoing related issues:

- https://github.com/joomla/joomla-cms/issues/10862
- https://github.com/joomla/joomla-cms/issues/12580
- https://github.com/joomla/joomla-cms/issues/9136

Looking at the code shows that the error is generated: https://github.com/joomla/joomla-cms/blob/3.10-dev/libraries/src/Cache/Storage/CacheliteStorage.php#L347
public static function isSupported()
{
@include_once 'Cache/Lite.php';
return class_exists('\Cache_Lite');
}


Joomla is using the error supressor to supress the include error. This no longer works for certain fatal errors. More info here: https://php.watch/versions/8.0/fatal-error-suppression.

Error supression shouldn't be used in libraries, it's considered a code smell. The right solution here would be to either throw an exception and catch it, or to just check if the "Cache/Lite.php" file exists instead of trying to require it.

Hope helps,

**Comment by PhilETaylor** [comment]
> Joomla is using the error supressor to supress the include error. This no longer works for certain fatal errors. More info here: https://php.watch/versions/8.0/fatal-error-suppression.

Correct. And probably something that can be improved. 

> Error supression shouldn't be used in libraries, it's considered a code smell. 

Again correct, but there are historical reasons why it is there, and therefore justified reasons through libraries why error suppression is - sparingly - used. Its use is sparingly and even Joomla contributors limit their use of it. 

> The right solution here would be to either throw an exception and catch it, or to just check if the "Cache/Lite.php" file exists instead of trying to require it.

Joomla could do that. Yes.

**Comment by PhilETaylor** [comment]
But also for the record, the article https://php.watch/versions/8.0/fatal-error-suppression clearly states that using the error suppression on include IS A VALID CASE ... as is file operations. 

Also failing to include is NOT a fatal error, but is just a WARNING - THAT CAN, in ALL PHP VERSIONS be suppressed correctly, including in PHP 8 - see test case here:

https://3v4l.org/844Nh

and then see it create warnings:

https://3v4l.org/MjorB

So... no we cannot catch the exception, because it doesnt, under normal circumstances, generate an exception, all it generates is.... 


I have tested this up to PHP 8.1 RC 2 and the above facts are correct. 

So... .that leads you back to JoomlaTools who manipulate error handling...

**Comment by PhilETaylor** [comment]
`include_once` raises warnings whereas `require_once` would be a fatal error if it could not load the file.

**Comment by PhilETaylor** [comment]
On further reflection and testing, this is not a Joomla issue. 

As evidenced by my testing previously and again today, the failure of an `include_once` to find the file to include raises a warning in PHP 7 and in PHP 8 and is correctly suppressed by the error suppressor on both occasions in both PHP versions 

It is never raised to a 500 Internal Server Error and is never raising an exception. This is correct and by design. 

The only difference between this by design, and your error message, is that JoomlaTools framework has raised this PHP Warning into a PHP Exception. This is wrong, and not a Joomla fault. 

I installed com_docman 3.5.4 to Joomla 3.10.1 to see if I could replicate this issue but I was unable to ever replicate your reported issue at all.

**Comment by skurvish** [comment]
I could provide you with the latest version but it is licensed so should not. Disabling the Joomlatools framework plugin gets around the issue for now, but I think between the two entities something needs to be done to allow the two to coexist. Not my pervue.

**Comment by PhilETaylor** [comment]
> Disabling the Joomlatools framework plugin gets around the issue for now

Is this confirming that once you disable the JoomlaTools framework, you no longer have this issue?

**Comment by skurvish** [comment]
That is correct.

**Comment by PhilETaylor** [comment]
Then I refer you to my[ initial comment](https://github.com/joomla/joomla-cms/issues/35487#issuecomment-913719790). This is not a Joomla issue. Joomla, and PHP are doing what Joomla and PHP are designed to do. JoomlaTools framework is escalating a PHP Warning (which is correctly suppressed in all supported PHP versions) to an Exception and killing the page load.

 >  think between the two entities something needs to be done to allow the two to coexist.

Joomla and PHP are doing the standard thing. Escalating a suppressed PHP Warning and converting it into an Exception is plain wrong and I would have expected better of Johans team. 

This issue can be closed.

**Comment by skurvish** [comment]
Thanks Phil, I appreciate your assistance. I guess I am stuck, Joomlatools continues to say it is a Joomla issue, you say it is not. I don't know where to go from here.

**Comment by johanjanssens** [comment]
@PhilETaylor Thanks for the assistance. You are 100% right, I was a bit too fast in my initial assessment yesterday. Done some in-depth testing today and can confirm that warnings generated by `include` are properly suppressed.

The problem stems from the local setup used by @skurvish. He Is running with `xdebug` enabled. Only when xdebug is enabled Joomlatools Framework error handler is not suppressing warnings in PHP8. This is by design, we develop locally with xdebug enabled and turn error reporting to max to make sure we don't miss any errors, warnings or notices.

For the code in Joomla 3.10 you could consider changing the check error suppressors remain a code smell and are best refactored out. You can use `stream_resolve_include_path` for this.

From

```
public static function isSupported()
{
     @include_once 'Cache/Lite.php';
    return class_exists('\Cache_Lite');
}

```

to 

```
public static function isSupported()
{
      if(stream_resolve_include_path('Cache/Lite.php')) {
        include_once ‘Cache/Lite.php’;
     }
   
     return class_exists('\Cache_Lite');
}
````

Change might not be worth it with Cache_Lite no longer part of Joomla 4.

**Comment by skurvish** [comment]
As you see above.

I am now closing this issue.

**Comment by zero-24** [comment]
Would you mind proposing an PR against 3.10-dev @johanjanssens so it can be patched in 3.10 and we dont get issues on PHP8?

**Comment by PhilETaylor** [comment]
Your post is proof that you did not read the whole thread. 

There will never be an issue on PHP8.

Tl:dr; this situation only occurs because JoomlaTools reconfigures error reporting when xdebug is installed and promotes a PHP warning into an exception. 

Even in PHP8 it will still be a correctly suppressed warning just like it is today. One of the only real uses for error surppression as evidenced by the blog post they provided.

there is no point removing one error suppression and not all the others throughout Joomla. 

Yes it could be done but for no real gain apart from with compatibility with the JoomlaTools framework.

**Comment by zero-24** [comment]
I have read the things about xdebug and the JoomlaTools Framework but wouldt it be "the better way" to add such check over supressing error messages? Maybe also for similiar other places?

**Comment by PhilETaylor** [comment]
Now you changed your tune haha 
Before it was about PHP8 issues
Now you say you want it because it’s the better way
PRs welcome etc etc lmao

**Comment by zero-24** [comment]
From my understanding this is an php8 issue only as only there the JoomlaTools thing kicks in but the error supressing is a general thing that should be avoided when there are better solutions.

>>or to just check if the "Cache/Lite.php" file exists instead of trying to require it.
>
>Joomla could do that. Yes.

That are your own words :D so what is the problem in asking for a PR to add the check thats proposed?

**Comment by PhilETaylor** [comment]
Please test #35507

**Comment by PhilETaylor** [comment]
> so what is the problem in asking for a PR to add the check thats proposed?

What is the point in fixing a single error suppression in a single feature that is hardly used by anyone (cache lite) and that is already deprecated and removed from Joomla 4, and that requires at least 4 specific things (PHP8, JoomlaTools, XDebug AND removal of cache_lite from previously working server) in order to trigger... 

This is not really fixing anything except **a very very very edge case**. There are bigger issues to resolve (like why people cannot use CloudFlare and Joomla 4!)

Oh the irony here is that out of the 783 instances of error suppression in my code base right now, (if you ignore restore.php which has over 209 because its dealing with file operations) a large percentage, are from JoomlaTools framework and docman...

**Comment by PhilETaylor** [comment]
There you go - its now part of the official Joomla Coding Standards:
 
https://github.com/joomla/coding-standards/pull/274/files

**Comment by skurvish** [comment]
I confirm that the above commit fixes this issue. Thank you all and sorry about the hours invested in this very very very edge case.

**Comment by zero-24** [comment]
Thanks. @PhilETaylor 

@skurvish can you submit your test result on the PR that has been created? https://github.com/joomla/joomla-cms/pull/35507 Thanks!
