### ISSUE TITLE
[4] template previews need size restrictions

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35498]
Template developers cannot be trusted to provide correctly sized images - Joomla could enforce a strict hard coded ratio

real life example seen today: 

<img width="1601" alt="Screenshot 2021-09-07 at 21 42 02" src="https://user-images.githubusercontent.com/400092/132408257-a9b1c601-5a88-4fc6-9c6f-f13baf6d60c1.png">

**Comment by dgrammatiko** [comment]
It Will be fixed with https://github.com/joomla/joomla-cms/pull/32896 if I ever manage to complete the work there.

**Comment by brianteeman** [comment]
Please test #36946
