### ISSUE TITLE
Edit image cause logout

### ISSUE THREAD

**Issue by galamarco** [joomla/joomla-cms#35496]
### Steps to reproduce the issue
I click on "media", click on the "pencil" of a photo and log out.
if I try to login from this page the login fails.

Example URL: administrator/index.php?option=com_media&view=file&mediatypes=0,1,2,3&path=local-images:/articoli/2021-09/download%206.png

I'm using a clean installation of Joomla 4.0.2 without other extension.

### System information (as much as possible)
Versione PHP 7.4.22
Joomla 4.0.2
Database version MySql 10.3.31-MariaDB-cll-lve

Best regards
Marco Galassi

**Comment by dgrammatiko** [comment]
Try renaming the file from `download 6.png` to `download_6.png` to bypass the problem but I guess someone should check why a filename with a space fails

Edit: Just saw your other issue, follow the instructions from @PhilETaylor

**Comment by galamarco** [comment]
space or not is the same. For exemple this url is the same:
administrator/index.php?option=com_media&view=file&mediatypes=0,1,2,3&path=local-images:/articoli/2021-09/img_20210906_105007.jpg<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35496">issues.joomla.org/tracker/joomla-cms/35496</a>.</sub>

**Comment by PhilETaylor** [comment]
> I click on "media", click on the "pencil" of a photo and log out.

How do you logout? There is no log out link/button on that page?

If I logout in a different tab, and then come back and refresh this page Im then at the login page and then I can login with no issues. 

<img width="947" alt="Screenshot 2021-09-07 at 20 56 59" src="https://user-images.githubusercontent.com/400092/132403408-d3925d66-8d9e-4667-a309-c4462a13623c.png">

**Comment by galamarco** [comment]
>How do you logout? There is no log out link/button on that page?
after clicking on the pencil I automatically see the login page and the session has expired.
Please note that I have never seen this screen in my life.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35496">issues.joomla.org/tracker/joomla-cms/35496</a>.</sub>

**Comment by PhilETaylor** [comment]
Ok thanks.

mate you using CloudFlare or Siteground services?

**Comment by jwaisner** [comment]
@galamarco , please see above request for information on your issue.

**Comment by galamarco** [comment]
> Are you using CloudFlare or Siteground services?

Yes I'm using CloudFlare

**Comment by maxclee-tt** [comment]
I'm facing the same problem

**Comment by brianteeman** [comment]
Have you followed the advice from cloudflare to the exclude the admin

https://support.cloudflare.com/hc/en-us/articles/201997250-Cloudflare-and-Joomla-Recommended-First-Steps

**Comment by swilski** [comment]
I am facing very same issue, have no idea what is going on as on the same server I have joomla 3, with joomla 4 whenever I try to rename file I am logged out and the path looks like this
https://.../administrator/index.php?option=com_media&view=file&mediatypes=0,1,2,3&path=local-images:/powered_by.png

**Comment by chmst** [comment]
@swilski  are you using  using CloudFlare? Is this still an issue?

> Have you followed the advice from cloudflare to the exclude the admin
> 
> https://support.cloudflare.com/hc/en-us/articles/201997250-Cloudflare-and-Joomla-Recommended-First-Steps

**Comment by brianteeman** [comment]
I am closing this as there is nothing further to do except for the users to follow the advice from cloudflare
