### ISSUE TITLE
[4.0] Editor field in Subform: CMS content buttons trigger error

### ISSUE THREAD

**Issue by janschoenherr** [joomla/joomla-cms#35490]
### Steps to reproduce the issue

Create an Editor field. Use it in a Subform field. Set "Buttons" options to "yes". In the article edit view, create an editor and try to open the Media modal.

### Expected result

Media modal should open

### Actual result

`Uncaught TypeError: document.getElementById(...).open is not a function`

### System information (as much as possible)

Joomla 4.0

**Comment by Hackwar** [comment]
Thank you for reporting this and sorry that a response has taken so long. In the meantime this bug has been fixed, so I'm going to close this issue.
