### ISSUE TITLE
[4.0] Sorted by: Incorrect table caption

### ISSUE THREAD

**Issue by rjharishabh** [joomla/joomla-cms#35494]
### Steps to reproduce the issue
Visit the articles page in the backend
Sort the table, for example - by Status ascending 
Just look at the table caption in the developer tools or just remove `class="visually-hidden"`  from the code
https://github.com/joomla/joomla-cms/blob/44934f7863bc68ec09aa510a6cb890b16f98a51b/administrator/components/com_content/tmpl/articles/default.php#L110

### Expected result
Correct Sorted by

### Actual result
Incorrect Sorted by

![sorted](https://user-images.githubusercontent.com/61203226/121379300-82e52c80-c961-11eb-91d1-e77a6cce287b.JPG)

### System information (as much as possible)
Joomla 4.0.3-dev
Chrome on Window 10
PHP 8.0.6
MySQLi 10.4.19-MariaDB

**Comment by carlitorweb** [comment]
https://github.com/joomla/joomla-cms/blob/a72b834b303d07bb51575394f0235dbba7f0679d/libraries/src/HTML/Helpers/SearchTools.php#L110-L117 If this condition is deleted, all work as should be. Personally I can't find a use case for this condition, after delete it, all still working okay. 

But if not, is just change the `sort.php` layout and add the correct directions there. I was doing a PR for this, but then the question arose which is the correct way, if delete or not the condition.

**Comment by rjharishabh** [comment]
Hi @carlitorweb If we delete the condition as you suggested, I think it will break the sorting using table header.

**Comment by carlitorweb** [comment]
@rjharishabh I checked and the sorting still working

**Comment by rjharishabh** [comment]
> @rjharishabh I checked and the sorting still working

Great, then  I think you should create a PR

**Comment by ReLater** [comment]
Issue confirmed with Joomla 4.2.3 and 4.2.4. See: https://github.com/joomla/joomla-cms/issues/39082

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39106 . Thanks in advance.
