### ISSUE TITLE
Logout (session problem)

### ISSUE THREAD

**Issue by galamarco** [joomla/joomla-cms#35495]
Hello,
I detect continuous logout (about every 60 seconds) using the backend. I have a new installation wihout extension. I think there is a problem...

Yet I increased the session life time to 60 minutes, it shouldn't happen.

I try to change session from database to system file but I don't solve the problem.
https://prnt.sc/1ri61uo
I think there is a problem on Joomla 4'session. It is clear that it is thus unusable.

### System information (as much as possible)
Versione PHP	7.4.22
Joomla 4.0.2
Database version MySql 10.3.31-MariaDB-cll-lve

Best regards
Marco Galassi

**Comment by PhilETaylor** [comment]
Are you using SiteGround?

Are you using CloudFlare?

**Comment by galamarco** [comment]
No I'm not using SiteGround, I'm using SupportHost and CloudlFlare.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35495">issues.joomla.org/tracker/joomla-cms/35495</a>.</sub>

**Comment by galamarco** [comment]
In cloudflare I try to set "Development Mode" and this don't solve the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35495">issues.joomla.org/tracker/joomla-cms/35495</a>.</sub>

**Comment by PhilETaylor** [comment]
As you are using cloud flare, please close this in favour of the existing #35244 issue. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35495">issues.joomla.org/tracker/joomla-cms/35495</a>.</sub>

**Comment by jwaisner** [comment]
Closing, please reference #35244 for followup.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35495">issues.joomla.org/tracker/joomla-cms/35495</a>.</sub>
