### ISSUE TITLE
[4.0] finder routing

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#35497]
Search module has two itemid

## Steps to reproduce the issue PART 1
Create a smart search module. Do not create a search menu item or set an ItemID in the module
![image](https://user-images.githubusercontent.com/1296369/132399905-366e5ccb-3920-406e-a982-e4816a680292.png)

Then visit the front end and perform a search with the module

### Expected result
The url is `example.com/component/finder/search?q=&Itemid=101`

_where 101 is the id of the default home page_

or even better `example.com/component/finder/search?q=`

### Actual result
The url is `example.com/component/finder/search?q=&Itemid=101&Itemid=101`
Only the first of the two itemid is used

## Steps to reproduce the issue PART 2
Repeat the test but this time add a search menu item or set an ItemID in the module

Then visit the front end and perform a search with the module

### Expected result

The url is `example.com/component/finder/search?q=&Itemid=xxx`
where xxx is the id of the search menu item or the id of the menu item selected in the module

### Actual result
The url is `example.com/component/finder/search?q=&Itemid=101&Itemid=xxx`
where xxx is the id of the search menu item or the id of the menu item selected in the module
where 101 is the id of the default home page

Only the first of the two itemid is used

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36426 . Thanks in advance.
