### ISSUE TITLE
[3.10] It is not possible to empty Trash in the Redirect Component

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#35508]
### Steps to reproduce the issue
Go to Components > Redirects
If no Expired (Source) URLs are listed, create one.
Trash an Expired URL you no longer need.
Use the bulk import facility to create an identical URL with a new redirect URL. This will show up as the new entry, currently disabled.
Use search tools to look for the URL using Status 'All'
Both entries for the Expired (Source) URL will appear.
Attempt to enable the new entry or modify the redirect URL.

### Expected result
As above, but expect to see the option to 'Emtpy Trash', as is found for articles, modules, menu items, etc.

Alternatively, a report saying that "x, y, z URL were not imported as they are duplicates".

### Actual result
1. No 'Empty Trash' option
2. When attempting to amend and save the redirect URL on either of the two entries this message appears:
   ERROR
   Save failed with the following error: The source URL must be unique.

(BTW, the message says 'source URL' but the column heading and field name is 'Expired URL'.

### Additional comments
The only hack I have found - without being able to totally remove one of them - is to change the expired URL https: to http (or any other change to make it different; it still doesn't remove the entry).
I don't think it is a cache issue.

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/132533257-98bf2c6b-eacc-4c7b-84bb-bf3fc937dd47.png)

Do you not see this?

**Comment by Scrabble96** [comment]
Thanks @brianteeman 
Gaah. I was expecting to see it there if I had 'All' selected. Hey ho.

**Comment by brianteeman** [comment]
no different to any other component afaik
