### ISSUE TITLE
J4 preview item seams broken

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#35501]
0 create an item

~~1 preview button doesn't have icon~~ plugin conflict
2 preview modal error

![image](https://user-images.githubusercontent.com/2539440/132470286-b48c8c44-1e2a-438f-ae7a-f2f50ea7d241.png)
![image](https://user-images.githubusercontent.com/2539440/132470317-f96ebc50-e951-4475-a683-adb1ca134316.png)

**Comment by PhilETaylor** [comment]
After playing with preview for the last week I can say this is not a Joomla issue :-) 

I cannot replicate this at all, in any environment

**Comment by PhilETaylor** [comment]
The error actually says that your browser could not connect to the server... maybe your server was having a down moment?

**Comment by dgrammatiko** [comment]
@micker check that your apache has the right mimes.types enabled, eg https://github.com/joomla/joomla-cms/files/6725305/mime.types.txt

**Comment by chmst** [comment]
@micker could you resolve it following the link of @dgrammatiko? If yes, then please close this issue.

**Comment by micker** [comment]
sorry i didn't receive notificati
[systeminfo-2021-09-17T13_46_57+02_00.txt](https://github.com/joomla/joomla-cms/files/7185320/systeminfo-2021-09-17T13_46_57%2B02_00.txt)
on

**Comment by dgrammatiko** [comment]
@micker can you share the file that is not getting a preview?
Did you read my other comment? Does your mime.types file allow all the extensions needed for Media Manager to function properly?

**Comment by micker** [comment]
sorry @dgrammatiko i thinked all information are in system export file
can you explain wjere i can find this information ?

**Comment by micker** [comment]
i found an error in console log
Refused to display 'https://www.....com/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.

**Comment by PhilETaylor** [comment]
make sure you are visiting your website with www in the domain name then... 

Also make sure you have NOT set `$live_site` value in `/configuration.php`

**Comment by dgrammatiko** [comment]
@micker sorry I misread the issue, your problem is the missing icon in the preview button in the toolbar (assuming in the article edit view). I can't recreate the issue. Would help to share the inspected element like:
![Screenshot 2021-09-17 at 13 56 10](https://user-images.githubusercontent.com/3889375/133778794-d816b46c-6253-4c32-a6b2-1dd4af04bdac.png)
![Screenshot 2021-09-17 at 13 55 55](https://user-images.githubusercontent.com/3889375/133778800-51535f30-675a-482b-9a89-1c406f72e676.png)

**Comment by micker** [comment]
hello
about icon that flase bug => a plugin conflict
about preview, nothing in livesite but yes @dgrammatiko with www all works ... bug ? or config serveur problem ?

**Comment by micker** [comment]
i found thanks @dgrammatiko to help to find it, a plugin conflict with www redirection plugin
