### ISSUE TITLE
J4 paths settings in com_media not working

### ISSUE THREAD

**Issue by RickR2H** [joomla/joomla-cms#35505]
### Steps to reproduce the issue
Go to the media manager options and change the path of the images and documents folder to something different (make sure the paths exists). Save the settings and open the media manager. Still the media manager will open in the default images folder and not respect the new path settings.

![screen shot 2021-09-08 at 12 30 32](https://issues.joomla.org/uploads/1/443949456507aaf6b6ed17604a731f71.jpg)

### Expected result
The new paths should be respected

### Actual result
Media manager opens the default images/ folder

**Comment by PhilETaylor** [comment]
Paths are now set in the file system plugin - look in that plugin

**Comment by RickR2H** [comment]
@PhilETaylor So these paths should be removed from the component then?

**Comment by PhilETaylor** [comment]
I’m mobile at the moment sorry, this has already been discussed repeatedly here, a quick search might find the answers you seek

**Comment by brianteeman** [comment]
First reported Feb 2019 #23972
Later reported Dec 2020 #31568

Both reports have been ignored

**Comment by RickR2H** [comment]
Closed because it is reported. Reason why it is still in J4 is expanded in #23972
