### ISSUE TITLE
J4 Installation db error

### ISSUE THREAD

**Issue by kamzar1** [joomla/joomla-cms#35502]
J 4.0.2 Installation 
php 7.4 / php7.4-fpm MariaDB 10.6.4
 
When starting the installation on https://joomla.my.domain/installation/index.php
At step DB, it shows "A Database error occurred"  with no further elaboration:

![dberror](https://user-images.githubusercontent.com/71010840/132479292-cb0edc2e-c057-4515-b6f4-39bddea5e50d.png)

This says browser console (Brave, chromium based):

![dberror_console](https://user-images.githubusercontent.com/71010840/132479234-3d3ee3f4-4cb8-4675-93d9-6d080fd44665.png)

Starting the installation over in http://domain solves the problem.

**Comment by PhilETaylor** [comment]
I cannot replicate this, starting an install on https:// urls results with all ajax calls being made over https://

<img width="1398" alt="Screenshot 2021-09-08 at 10 06 18" src="https://user-images.githubusercontent.com/400092/132480660-957befbc-c468-4d6e-b279-7db4805cca4f.png">

Can you give more information about your setup please?

**Comment by kamzar1** [comment]
Sure, you are right. It might be causing the issue in this case.
Traffic to Instance routed by HAProxy SSL offload.
That can be the issue! Instance get http requests, where HAProxy as middleware already had offloaded the ssl.

**Comment by PhilETaylor** [comment]
Joomla has never supported installation behind a terminated ssl connection. I have worked considerably on these issues in Joomla core. 

However, once installed, you can then correctly configure Joomla to work behind a terminated ssl connection easily, with setting the force SSL setting and the new Behind Proxy settings.

**Comment by kamzar1** [comment]
Thanks.
How to achieve this?

> "However, once installed, you can then correctly configure Joomla to work behind a terminated ssl connection easily, with setting the force SSL setting and the new Behind Proxy settings

."

**Comment by PhilETaylor** [comment]
Just like you said: 

> Starting the installation over in http://domain solves the problem.

**Comment by PhilETaylor** [comment]
Please leave this issue open, because it should be simple for Joomla (me probably) to improve this so that it is possible in the future to install Joomla behind a ssl terminated load balancer

**Comment by kamzar1** [comment]
That I got, but afterwards in normal operation modus, how to configure it for behind terminated ssl?
To get all links and HTTPRequests in https, despite having the http request.

**Comment by PhilETaylor** [comment]
Like I said: 

> However, once installed, you can then correctly configure Joomla to work behind a terminated ssl connection easily, with setting the force SSL setting and the new Behind Proxy settings.

Both these settings are in the Joomla Global Config.

**Comment by richard67** [comment]
@kamzar1 Let us known if the above information helped you and if so, close this issue. Thanks in advance.

**Comment by kamzar1** [comment]
Information was helpful and issue solved.

**Comment by richard67** [comment]
@kamzar1 Thanks for reporting back.

**Comment by richard67** [comment]
@kamzar1 Why reopened this?

**Comment by kamzar1** [comment]
Problem was:
Behind an haproxy ssl off load
Installing Joomla in https://domain/installation has thrown a Database error.
Switching to http://domain during installation has solved the problem and after installation page has worked normal in https://domain. 
I had similar issue with another application and these two steps helped:
1. HA Proxy config:
 http-request set-header X-Forwarded-Proto https if { ssl_fc }

2. Application:
if ($_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https') $_SERVER['HTTPS'] = 'on';

Perhaps a similar approach will help here as well?

**Comment by PhilETaylor** [comment]
Please close this and start a new issue for the new problem

**Comment by kamzar1** [comment]
Not a new problem, just a suggestion.
Closing anyway.
