### ISSUE TITLE
[4] No location in module when shared sessions enabled.

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#35500]
### Steps to reproduce the issue

Install Joomla 4
Enable shared sessions in Joomla Global Config 
Logout
Login
Visit Home Dashboard

### Expected result

The logged in users table to have a value in the location. 
Ok, so we probably dont know they are "currently in administrator" but we could display "Shared Session" instead of a blank space. 

### Actual result

<img width="637" alt="Screenshot 2021-09-07 at 22 33 49" src="https://user-images.githubusercontent.com/400092/132413849-59b05ef1-ccfc-4ac0-82d1-472cbd54173c.png">

**Comment by brianteeman** [comment]
Please test #35732

**Comment by alikon** [comment]
test #35732
