### ISSUE TITLE
privacy requests red notification without requests pending

### ISSUE THREAD

**Issue by galamarco** [joomla/joomla-cms#35513]
### Steps to reproduce the issue
I have a clean installation of Joomla 4.0.2 and one day after the installation the privacy request box is red with "unknown requests" written even when there are no pending requests.
![notification box is red](https://bramantehouse.it/images/articoli/2021-09/screenshot_30.png)

If I check the request pending there are not request pending.
![notification box is red](https://bramantehouse.it/images/articoli/2021-09/screenshot_31.png)

### Expected result
If there are requests, the box must be red otherwise green

### Actual result
it is always red and the system is probably unable to check for pending requests

### System information (as much as possible)
Joomla 4.0.2
PHP: 7.4.23
MySql: 10.3.31-MariaDB-cll-lve

Marco Galassi

**Comment by brianteeman** [comment]
Unable to replicate
