### ISSUE TITLE
Update to bugfixed Bootstrap 5.1.1

### ISSUE THREAD

**Issue by 1337180** [joomla/joomla-cms#35515]
### Steps to reproduce the issue

https://blog.getbootstrap.com/2021/09/07/bootstrap-5-1-1/

### Expected result
Bootstrap 5.1.1 in Joomla! 4.0.3

### Actual result

Bootstrap 5.0.2 in Joomla! 4.0.2

### System information (as much as possible)

none

### Additional comments
Please stay up-to-date. THanks!

**Comment by brianteeman** [comment]
> Please stay up-to-date. THanks!

It is not that simple<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35515">issues.joomla.org/tracker/joomla-cms/35515</a>.</sub>

**Comment by Quy** [comment]
Duplicate #35182

**Comment by dgrammatiko** [comment]
Please test #35518
