### ISSUE TITLE
J4 Sample Data 

### ISSUE THREAD

**Issue by Knock-Out** [joomla/joomla-cms#35516]
### Steps to reproduce the issue

Joomla! 3.10.1

- I have installed Joomla! 3.10.1 Full Package (Sample Data English (GB) Blog)
- I upgraded to Joomla! 4.0.2

Joomla! 4.0.2

- I added and activated the Sample Data module
- Sample Data for Cassiopeia (Blog) cannot be installed

### Expected result

No error

### Actual result

Step 1 Failed: Another category with the same parent category has the same alias (remember it may be a trashed item).

![Home Dashboard - joomla_3 9 x_4 0 x - Administration](https://user-images.githubusercontent.com/24791536/132670508-12b45c06-256d-4a56-a470-99509c87c170.png)

Step 1 Failed: Another Tag has the same alias (remember it may be a trashed item).

![Home Dashboard - joomla_3 9 x_4 0 x - Administration (2)](https://user-images.githubusercontent.com/24791536/132671993-fb530a0b-30ef-4320-96dd-8801f66c650b.png)

### System information (as much as possible)

- XAMPP V3.2.4
- PHP 7.4.13
- MySQLi 10.4.17-MariaDB

### Additional comments

No items are trashed

**Comment by brianteeman** [comment]
Sample data can only be installed on a site that is empty

**Comment by chmst** [comment]
Not quite there could be some own content already, but Sample data cannot be installed twice. 
Closing this issue because it is intended behaviour.

**Comment by Knock-Out** [comment]
In the Joomla! 3.10.1 Full Package, I tested:

- Sample data English (GB) Brochure
- Sample data English (GB)
- Sample Data English (GB) Learn

In the Joomla! 4.0.2 the "Blog Sample Data" has been installed replacing them.
