### ISSUE TITLE
[4.0] Copy template not possible

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#35529]
### Steps to reproduce the issue

1.  Go to template manager and try to copy the template Cassiopeia, 
![issue](https://user-images.githubusercontent.com/9974686/132906909-837a359e-f2af-4ea2-b4ee-b981b74a1f66.png)

2. Although you give a new name you get an error that you use an existing name.
![issue2](https://user-images.githubusercontent.com/9974686/132906902-a67018b2-7d3d-4ef3-be88-c5fa8bde7ce4.png)

### Expected result

The template is copied

### Actual result

You see error

Can someone confirm this?

**Comment by brianteeman** [comment]
Can not replicate

![astrid](https://user-images.githubusercontent.com/1296369/132911406-e50a65f6-5aa9-4fc4-8518-2f8727b325c4.gif)

**Comment by astridx** [comment]
Many thanks Brian. Then it's most likely due to my setup, which I haven't used practically for a while. Tomorrow I'll take my time and set up my development environment from scratch..

Sorry that I have probably opened an issue unnecessarily,

**Comment by dgrammatiko** [comment]
> tomorrow I'll take my time and set up my development environment from scratch..

Try deleting everything inside your `/tmp` folder
