### ISSUE TITLE
LDAP authentication not working

### ISSUE THREAD

**Issue by ac89live** [joomla/joomla-cms#35532]
### Steps to reproduce the issue
LDAP login worked before the upgrade. we were on version 3.9.x
Joomla is configured with ldap authentication plugin
either regular "LDAP - Authentication" plugin or miniOrange plugin
Tried to reproduce the issue also with two php versions 7.2 and 7.3

### Expected result
LDAP authentication should successfully work

### Actual result
error message:
Unknown column 'sso_test' in 'field list'

### System information (as much as possible)

PHP Built On | Windows NT CLOUDABD 6.3 build 9600 (Windows Server 2012 R2 Standard Edition) AMD64
Database Type | mysql
Database Version | 5.5.45
Database Collation | utf8_general_ci
Database Connection Collation | utf8mb4_general_ci
PHP Version | 7.3.25
Web Server | Microsoft-IIS/8.5
WebServer to PHP Interface | cgi-fcgi
Joomla! Version | Joomla! 3.10.1 Stable [ Daraja ] 22-August-2021 16:41 GMT
Joomla! Platform Version | Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent | Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0

**Comment by PhilETaylor** [comment]
Column 'sso_test' is not a Joomla column name, therefore this is probably a miniOrange support request and not a Joomla 3.10.1 issue at all.

**Comment by PhilETaylor** [comment]
LDAP in Joomla 3 has not changed, or been modified or changed since Joomla 3.9.15 back in 2020.

https://github.com/joomla/joomla-cms/commits/3.10-dev/plugins/authentication/ldap

LDAP in Joomla 4 is mostly broken an unusable.

**Comment by ac89live** [comment]
I encountered the issue with the LDAP authentication default plugin:
https://docs.joomla.org/Help39:Extensions_Plugin_Manager_Edit/de#Authentication_-_LDAP
And then I tried the miniOrange.
I'll do an extended troubleshooting 
Thanks :)

**Comment by ac89live** [comment]
Hi
Issue resolved by installing different plugin
I used jmapmyldap instead, and its working fine now
Thanks

**Comment by PhilETaylor** [comment]
ok - then please close this issue here on GitHub.
