### ISSUE TITLE
[4.0] TinyMCE Plugin ignores filter settings

### ISSUE THREAD

**Issue by michaelhthomas** [joomla/joomla-cms#35535]
### Steps to reproduce the issue

- Enter TinyMCE plugin settings and disable iframe / script tag filtering, or enable use Joomla text filter option.
- Add content to a page which contains an iframe or script tag
- Switch between editor and HTML modes or attempt to save the page.

### Expected result

Page is saved correctly and iframe / script tags are preserved.

### Actual result

Iframe/script tags are stripped by the editor and cannot be saved. Adding iframes or script tags is only possible when the TinyMCE plugin is disabled entirely.

### System information (as much as possible)

Joomla 4.0.2 using Docker-compose on Ubuntu.

### Additional comments

Even with Joomla system wide content filtering disabled, as well as the "Use Joomla text filter" option enabled, TinyMCE strips protected tags from the HTML and ignores this configuration.

**Comment by richard67** [comment]
You have to remove iFrame from the prohibited elements in the options of the tinymce editor plugin.

**Comment by brianteeman** [comment]
@richard67 The user has already stated that they have done that. ;) However.

You have almost certainly come across an example of a poor user interface for the settings of tinymce.

TinyMCE lets you have different settings for different usergroups. The default group for admins is group 0 but you have probably not noticed the tab settings and have only changed the setting for the first group displayed which is group 2.

![image](https://user-images.githubusercontent.com/1296369/132980179-242dde7a-5990-41e4-81c6-410abfa7945e.png)

![image](https://user-images.githubusercontent.com/1296369/132980184-a8105274-3b2a-4b3f-93db-395465a1ed53.png)

**Comment by brianteeman** [comment]
This can probably be closed now.

**Comment by HLeithner** [comment]
Thanks brian, I think it explained how to solve this.
