### ISSUE TITLE
Smart Search option "Filter Numeric Terms" trigger fatal error message

### ISSUE THREAD

**Issue by aniki-971** [joomla/joomla-cms#35539]
### Steps to reproduce the issue

1) Create one or two dummy article and launch smart search indexer.

2) Go in Component > Smart Search > Index, click "Options" and in Index tab, enable "Filter Numeric Terms".
Leave all other options to their default values.

3) Try to create a new article and save.

### Expected result

No error message
Article saved.

### Actual result

The following error message is displayed whenever you try to save something.
"Save failed with the following error: Syntax error near '' at line 1."
(See attached image for reference)![screen shot 2021-09-12 at 13 51 17](https://issues.joomla.org/uploads/1/8e71f550c9a01e695982e017f70dee95.png)

Every time you try to save your article a new record is created in the content table 
while the article is not displayed at all in the com_content component. Leading to multiple invisible duplicate.

### System information (as much as possible)

Joomla version : 4.0.2 (Freshly installed, with the Full Package). 
No plugin installed. Only Joomla + 1 custom template (copy of the Cassiopeia template delivered with Joomla)
2 Joomla Languages actives : French (default), English
Apache Version : 2.4.46
Server Software : Apache/2.4.46 (Win64) PHP/7.4.9, Apache port : 80
PHP Version : 7.4.9

### Additional comments

The error is not related specifically to article saving because launching the Smart Search indexing while the "Filter Numeric Terms" option is enabled will trigger the error message too.
![screen shot 2021-09-12 at 13 51 20](https://issues.joomla.org/uploads/1/ae0fcd85c0c9f75e76a46cbdd4a46a66.png)

**Comment by brianteeman** [comment]
Issue confirmed

![image](https://user-images.githubusercontent.com/1296369/132992260-752dd9d1-c1d3-4649-b1c3-df875280248d.png)

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/35540 should solve this issue. Please help testing. Thanks !
