### ISSUE TITLE
Can't turn module title on / off for Banner Position on Cassiopeia Template

### ISSUE THREAD

**Issue by nineoo** [joomla/joomla-cms#35546]
### Steps to reproduce the issue
Scenario one: Place a custom module with an image in the **Banner Position** on the Cassiopeia Template. Forget to hide module Title and save. Go back in and set to hidden.

Scenario two: Place a custom module with an image in the Banner Position on the Cassiopeia Template. Set to hide module Title. Go back in and set to show title.

### Expected result
Scenario one: Title will show and then on second save be hidden.

Scenario two: Title will be hidden but when opened again to set to show it will be displayed.

### Actual result
Scenario one: Title is displayed and can't turn it off

Scenario two: Title is hidden but can't turn it back on

### System information (as much as possible)
2 different sites using version 4.0.2.

Site one: Apache/2.4.47 (Win64) OpenSSL/1.1.1k PHP/8.0.9, mysql 5.7.33

Site two: LiteSpeed Server, php 7.4.23, 10.3.25-MariaDB

### Additional comments
It seems that whatever it as set as on the first save of the module is the one it cannot be changed from.

My testing was with a banner image in a custom module set to the position Banner. I also tried the Popular Tags module in the Banner position and the same issue occurs with the show/hide title. Resorted to hiding the banner title with CSS for now.

**Comment by brianteeman** [comment]
Not sure how you ever had the title displaying in the banner position because the "module chrome" for that position is "none"  and this "module chrome" will only display the content no matter what the title options are.

(note I do not agree that a module chrome will ignore the settings in a module)

**Comment by nineoo** [comment]
I've since upgraded to 4.0.3 and can't replicate the issue now. In hindsight I ought to have sent some screen shots!
