### ISSUE TITLE
Create menu item: an obsolete underlined whitespace in link in modal window

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#35548]
In addition to this issue #31474 where is similar issue was detected.

How to reproduce the issue:
Create a new menu item > articles and get a popup window with a list of articles and there is such a space in the link.

<img width="1400" alt="1" src="https://user-images.githubusercontent.com/3432048/133076578-4c008bb2-b75f-41dc-88d3-6c5f876d9156.png">

<img width="1735" alt="2" src="https://user-images.githubusercontent.com/3432048/133076584-65f54ae4-6f64-4c1e-85fa-367a114df6f5.png">

<img width="458" alt="3" src="https://user-images.githubusercontent.com/3432048/133076592-f4d1e90c-55d7-48cc-ad4a-9d1ccbf951ce.png">

You will see empty space in links.

Joomla 4.0.2

**Comment by chmst** [comment]
Confirmed. https://github.com/joomla/joomla-cms/pull/35514
We need a generic soution for that.

**Comment by brianteeman** [comment]
something like` $html= trim(preg_replace('/>\s+</', '><', $html));`

otherwise its a never ending list of manual fixes.

**Comment by chmst** [comment]
I would prefer a consequent usage of HtmlHelper for generating links.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #35564 . Thanks in advance.
