### ISSUE TITLE
[4.0] display incomplete Users Permissions Table - with German translation

### ISSUE THREAD

**Issue by je1977** [joomla/joomla-cms#35558]
#### It´s not perfect, but better as in German

![table_misdesign_eng](https://user-images.githubusercontent.com/39240528/133248775-be56864f-ecb5-45ac-a526-2a0b7e6fb25b.gif)

### Actual result
![Screenshot](https://user-images.githubusercontent.com/39240528/133247170-4a1e7d9f-3517-4ef6-8fe8-eab6dc85e887.gif)

### System information (as much as possible)
Joomla Version: !J 4.0.3
Server: Wamp (localhost)
PHP Version: 7.4.9

**Comment by Quy** [comment]
Duplicate #23628. Thank you for the report.
