### ISSUE TITLE
#34890 breaks offline.php in Joomla 4.0.3

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#35552]
Reported by Rachel Walraven as part of the CMS Release Team testing. #34890 breaks the offline.php @dgrammatiko 

### Steps to reproduce the issue
Use latest version (4.0.3-rc or final package) and check the offline page.

![screencapture-localhost-j403-index-php-en-2021-09-13-15_45_39](https://user-images.githubusercontent.com/1497730/133098328-ddfd90e1-038d-4a6a-a44e-295ce13f579b.png)

**Comment by dgrammatiko** [comment]
https://github.com/joomla/joomla-cms/pull/35553

**Comment by HLeithner** [comment]
Thanks
