### ISSUE TITLE
HTTP Headers Plugin - Help Screen error

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#35557]
While checking the right settings for HTTP Headers Plugin, I noticed that the Help Screen was not on par with the changes that had been made on this plugin.
A "Content-Security-Policy (CSP)" tab is missing. Check this:

![screen shot 2021-09-14 at 09 51 20](https://issues.joomla.org/uploads/1/8963e8ee81283853c4bded89461e1aca.png)

Additionally, 
* this doc:
https://docs.joomla.org/Help4.x:Content_Security_Policy:_Options/en
refers to it as a component. I guess it should be removed from the docs.

NB : this is the right doc:
J4.x:Http Header Management - Joomla! Documentation
https://docs.joomla.org/J4.x:Http_Header_Management/en

* I have been looking for a way to trigger "CSP Reports". It seems that this functionality no longer exists.

**Comment by zero-24** [comment]
Hmm i thought i have updated the docs the other day. Yes com_csp is gone and the settings are moved to the plugin.

**Comment by zero-24** [comment]
> A "Content-Security-Policy (CSP)" tab is missing. Check this:

Thanks I have just updated the docs to point to the HTTP Header docs as well as uploaded a new version of the image (might take some time to clear the cache)

> I have been looking for a way to trigger "CSP Reports". It seems that this functionality no longer exists.

As com_csp is gone from the core you have to run your own script like this one: https://github.com/zero-24/csp-reporter-php or deploy an CSP reporter service.

> refers to it as a component. I guess it should be removed from the docs.

Yes I have just again requested that pages to be finally removed from the docs.

**Comment by ghazal** [comment]
Thanks for the "csp-reporter" tip/script.

**Comment by jwaisner** [comment]
Thank you for opening this report. As it has been identified that there were changes and documentation has been updated/provided for you. I will close this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35557">issues.joomla.org/tracker/joomla-cms/35557</a>.</sub>
