### ISSUE TITLE
Joomla 4 - redirect after login

### ISSUE THREAD

**Issue by Sandvelder** [joomla/joomla-cms#35562]
### Steps to reproduce the issue
Hi
Joomla 4, after a session has expired, does not redirect to the previous page after a re-login, but goes to the user's profile page.

**Comment by brianteeman** [comment]
Are you referring to the site or the admin?

**Comment by Sandvelder** [comment]
Hi Brian
I am referring to the site. I have 22 sites, of which 3 are on Joomla 4. The new Joomla 4 sites give this issue.
For instance, I would be on my management site (management.jfbdesigns.co.za) on the academics page (https://management.jfbdesigns.co.za/academics) and after a while, the session ends. On refreshing, the login screen pops up and I log in. You should then go back to the academics page, but the user profile screen pops up. Joomla 4 should, like Joomla 3, keep you on the page you were on when the session expired.
Regards,
Francois

**Comment by brianteeman** [comment]
There are two places you should check
1. The login module
2. The login menu item (if you have one)

Both of these have an option describing what will happen on login

**Comment by Sandvelder** [comment]
Thank you, Brian
Yes, I have checked those prior to posting here, but they seemed not to have changed anything. I have now logged into the module again and removed any references to redirects. It seemed to have resolved it. But I did that before too and it would not change anything. It seems fine now - fingers crossed!
Regards
Francois

**Comment by Sandvelder** [comment]
Hi Brian
I thought the problem was solved, but it was not.
In Joomla 4, if a session has expired and you click on a menu item, it takes you to the login screen, which is correct, and once you logged in you are supposed to be directed to the menu item you clicked on, but you land up at the user profile page.
I have gone through all the login module settings and nowhere is there a redirection set to the user profile page.
I think it is one of those new issues with a new version which someone should just address rather sooner than later. The rest of Joomla 4 is working nicely and I am impressed with it.
Regards,
Francois

**Comment by brianteeman** [comment]
I could not replicate this when I checked this morning. Please post a screenshot of your login module options and of any login menu (if you have one)

**Comment by Sandvelder** [comment]
Hi Brian
When I am logged out of my management site, only two items are available: 1) Home and 2) Blog. When I log in, the others appear too. See this [screenshot](https://management.jfbdesigns.co.za/j4issues/gbit4.JPG).

Once the session times out and I click on any of those menu items, say [Finance], the website takes me to a login screen. See this [screenshot](https://management.jfbdesigns.co.za/j4issues/gbit1.JPG).
I then click on [Login], expecting to go to [Finance] but land up [here](https://management.jfbdesigns.co.za/j4issues/gbit2.JPG).

I am supposed to be on this [screen](https://management.jfbdesigns.co.za/j4issues/gbit3.JPG)

**Comment by Sandvelder** [comment]
The links I left do not work. 

I do not know what to do anymore

**Comment by brianteeman** [comment]
post your images here

**Comment by jwaisner** [comment]
@Sandvelder , Please post images of your issue.

**Comment by joomdonation** [comment]
Tried and could not confirm the issue. Looking at the code https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Application/SiteApplication.php#L101 , I believe we have handle this use-case already

So for now, I'm closing this issue. If you have a reliable way to allow us to see the error, feel free to re-open. Thanks !

**Comment by JanMeest** [comment]
Yes I have the same problem. Joomla 4.1.3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35562">issues.joomla.org/tracker/joomla-cms/35562</a>.</sub>

**Comment by Sandvelder** [comment]
That problem still persists - I do not know if anyone is even looking into it.

**Comment by HLeithner** [comment]
@Sandvelder if you session expire and you get redirected to the login screen please check the sourcecode of the page. There should be an input field with the Name "return". The value is a base64 Encoder string, please post this string Here.

**Comment by Hackwar** [comment]
Unfortunately there was no response even after 2 years, so I'm closing this issue. If you still encounter this issue, please open a new ticket with the necessary information.
