### ISSUE TITLE
[4.0] Subform resets to default when all entries are deleted

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#35561]
### Steps to reproduce the issue

1. Open `modules/mod_login/mod_login.xml` and add the following code:
```
<field
	name="colours"
	type="subform"
	formsource="modules/mod_login/colours.xml"
	layout="joomla.form.field.subform.repeatable-table"
	label="Colours"
	multiple="true"
	default='[{"colour":"#FF0000"},{"colour":"#008000"}]'
/>
```

2. Create a new file (`modules/mod_login/colours.xml`) and add the following code:

```
<?xml version="1.0" encoding="UTF-8"?>
<form>
	<fieldset name="colours" label="Colours">
		<field name="colour" type="color" label="Colour" />
	</fieldset>
</form>
```

3. In your Joomla administrator panel, open the Login module and you should see two default colours:
![image](https://user-images.githubusercontent.com/2019801/133281450-904701cb-c628-463b-9807-c4f35c2f7ba0.png)

4. Delete both subform rows and click `Save`

### Expected result

There should be NO colour fields shown.

### Actual result

The field is reset back to the default values.

**Comment by brianteeman** [comment]
Isn't that the same with any field that has a default value? The same is true with the template style color fields

**Comment by C-Lodder** [comment]
When I say remove the colour entries, I dont mean from the input fields. I mean delete the actual subform row.

**Comment by Fedik** [comment]
It expected behavior.  As @brianteeman wrote, the same happen to other fields if you remove the value. On next load it will use default. You can test it with `<field type="text" name="text" default="blabla" />`

> I mean delete the actual subform row.

Each row is a value in subform (multiple), removing all rows means the subform is empty, and it will pick up default.

**Comment by C-Lodder** [comment]
Cool, thanks.
Just tested with other fields and you're both right.
