### ISSUE TITLE
[3.10] category can not be saved because alias already existes -> all fields are empty

### ISSUE THREAD

**Issue by nadjak77** [joomla/joomla-cms#35565]
### Steps to reproduce the issue

New category
fill in all fields (title, content, category, custom fields...) 
save
error message: coult not be saved, alias already exists
all fields (title, content, category, custom fields,...) are empty

### Expected result
the fields are still filled in (like in the last jommla versions)

### Actual result
all fields are empty

### System information (as much as possible)
xampp for windows on local system
PHP 7.4.22
Joomla 3.10.2

**Comment by chmst** [comment]
Confirmed. It is in J3.9 but not in J4.

**Comment by joomdonation** [comment]
Guess we can fix it by backport this PR https://github.com/joomla/joomla-cms/pull/32959 to 3.10

**Comment by joomdonation** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/35576 . Thanks !

**Comment by nadjak77** [comment]
Thank you @joomdonation ! I successfully tested the patch and reported it to the issuetracker

**Comment by joomdonation** [comment]
Thanks for testing @nadjak77 .
