### ISSUE TITLE
0 Unknown named parameter $params after Website Offline Function used

### ISSUE THREAD

**Issue by marcelkb** [joomla/joomla-cms#35578]
### Steps to reproduce the issue
Activate the Website Offline (=Wartungsmodus) Option
Login with the Login-Mask

### Expected result
You can view the normal website

### Actual result
Bei Problemen ist der Administrator dieser Website zuständig.

0 Unknown named parameter $params
Call stack
#	Function	Location
1	()	JROOT\libraries\src\Editor\Editor.php:200
2	Joomla\CMS\Editor\Editor->display()	JROOT\plugins\system\inlinecontent\inlinecontent.php:298
3	PlgSystemInlineContent->onAfterDispatch()	JROOT\libraries\src\Plugin\CMSPlugin.php:285
4	Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}()	JROOT\libraries\vendor\joomla\event\src\Dispatcher.php:486
5	Joomla\Event\Dispatcher->dispatch()	JROOT\libraries\src\Application\EventAware.php:111
6	Joomla\CMS\Application\WebApplication->triggerEvent()	JROOT\libraries\src\Application\SiteApplication.php:211
7	Joomla\CMS\Application\SiteApplication->dispatch()	JROOT\libraries\src\Application\SiteApplication.php:245
8	Joomla\CMS\Application\SiteApplication->doExecute()	JROOT\libraries\src\Application\CMSApplication.php:278
9	Joomla\CMS\Application\CMSApplication->execute()	JROOT\includes\app.php:63
10	require_once()	JROOT\index.php:32

Still after logout and F5 it is broken.
Visiting with another browser or in incognito mode works

### System information (as much as possible)
Win10, XAMPP Version: 8.0.9

**Comment by PhilETaylor** [comment]
This is not a Joomla problem. This is a problem with the custom plugin plugins\system\inlinecontent

**Comment by marcelkb** [comment]
ah ok, though it was a Joomla internal plugin, but seems to be sth. from Ark ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35578">issues.joomla.org/tracker/joomla-cms/35578</a>.</sub>

**Comment by joomdonation** [comment]
Closing because of none core issue.

**Comment by PhilETaylor** [comment]
Arguably it is a core issue that should be resolved https://github.com/joomla/joomla-cms/issues/33529#issuecomment-831800679

**Comment by joomdonation** [comment]
Without looking at the actual plugin code, I'm unsure. The issue you linked too, causes by JCE editor does not use same method signature with core if I remember correctly and the developer fixed it (with happiness from long time ago).

**Comment by PhilETaylor** [comment]
Its actually a PHP 8 Named Arguments Backward compatibility break as detailed in the issue I raised and the comment I made on how Joomla can better handle it. 3pd should not be expected to have to change their code because Joomla fails to make PHP 8 compatibility a priority.
