### ISSUE TITLE
[4.0] itemid is overruled when system - sef is enabled

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#35570]
### Steps to reproduce the issue

1) Setup joomla
2) Install Kunena 6.0 nightly build (https://www.kunena.org/download)
3) Enable kunena forum
4) Create a topic
5) Check the item id on the message action reply button.

### Expected result

`http://localhost/j4/index.php?option=com_kunena&view=topic&catid=2&id=37&mesid=42&Itemid=151`

### Actual result

`http://localhost/j4/index.php?option=com_kunena&view=topic&catid=2&id=37&mesid=42&Itemid=101`

provided url on components/com_kunena/template/aurelia/layouts/widget/button/default.php =
 `index.php?option=com_kunena&view=topic&layout=reply&catid=2&id=37&Itemid=151`

### System information (as much as possible)

Nightly joomla 4.0
Nightly Kunena 6.0

Extra info:

Default joomla menu, where the home is set as itemid 101
Kunena menu itemid = 151

**Comment by brianteeman** [comment]
What do you mean by provided url

**Comment by 810** [comment]
the input value.  $this->url

**Comment by brianteeman** [comment]
So not hardcoded as you wrote but using the api and being passed through jroute

**Comment by 810** [comment]
when i use hardcoded is the same:

`<a href="index.php?option=com_kunena&view=topic&layout=reply&catid=2&id=37&Itemid=151">
	test
</a>`

Result: 
`<a href="/j4/index.php?option=com_kunena&amp;view=topic&amp;layout=reply&amp;catid=2&amp;id=37&amp;Itemid=101">
	test
</a>`

**Comment by Ruud68** [comment]
I have been fighting this (I think) in trying to get one of my components ready for both J3 and J4 based on the new modern router.
J3 and J4 router behaves differently: the code returns a different SEF URL on J3 and on J4. IMO this means that the new / modern router as implemented in J4 is not B/C.

I have drilled it down to the different handling of the Itemid.

My workaround is to do a check on J version and based on that set / unset the Itemid in the preprocess function of the MenuRules.

**Comment by richard67** [comment]
Closing as having a pull request, see #35634 . @810 Please when you make a PR to solving an issue created by you in future, then close that issue when the PR is ready for testing. Thanks in advance.

**Comment by Hackwar** [comment]
The PR #35634 was closed since there was no response there. However we have a new PR #42989 which should help with the issue as well.
