### ISSUE TITLE
[4] misleading descriptions of LDAP plugin configuration form fileds

### ISSUE THREAD

**Issue by pioada** [joomla/joomla-cms#35571]
### Steps to reproduce the issue
Go to Admin > plugins > Authentication - LDAP > configuration form

### Actual result
Description of field "Search String" says "...Only used when searching." while this param is used in search and direct bind.
Description of field "User's DN" says "...Only used for direct binds." while this is used only in search method.

### Expected result
Correct fields descriptions.

### System information (as much as possible)
-

### Additional comments
-

**Comment by PhilETaylor** [comment]
The LDAP in Joomla 4 is so bad as to be totally unusable. It needs a complete rewrite by someone who understands LDAP. 

https://github.com/joomla/joomla-cms/issues/25434
https://github.com/joomla/joomla-cms/issues/35316
https://github.com/joomla/joomla-cms/issues/35216

https://github.com/joomla/joomla-cms/pull/35323
https://github.com/joomla/joomla-cms/pull/32400

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37959 . Thanks in advance.
