### ISSUE TITLE
[4.0] Hungarian language file of TinyMCE is not up-to-date

### ISSUE THREAD

**Issue by csbalazs** [joomla/joomla-cms#35579]
Under Joomla 4.0.3 the Hungarian language file of TinyMCE is not up-to-date. Can anyone update? I updated the language file on Transifex: https://www.transifex.com/tiny/tinymce/language/hu_HU/
Untranslated texts in yellow: 
![image](https://user-images.githubusercontent.com/1657924/133765824-1e45d3da-4394-4c36-b4de-647c0154ce33.png)

**Comment by infograf768** [comment]
Here is the file as zip to be decompressed and placed in build/media_source/vendor/tinymce/langs/ folder to replace the one present.
[hu.es5.js.zip](https://github.com/joomla/joomla-cms/files/7186836/hu.es5.js.zip)



<img width="345" alt="Screen Shot 2021-09-17 at 17 36 29" src="https://user-images.githubusercontent.com/869724/133816235-2aa3b223-98ec-4858-970a-534dc572ac5d.png">
@Bakual @richard67

**Comment by infograf768** [comment]
@joomla/cms-maintainers 
Most of these lang files are incomplete as they come from 3.x and nobody took care asking TTs to provide new files for their language.
For the version of Tinymce used by J4, the number of lines is 462 while in 3.x it was 230.

Examle above for Hungarian.
Same below for French:
<img width="332" alt="Screen Shot 2021-09-17 at 17 53 36" src="https://user-images.githubusercontent.com/869724/133818406-0542cf20-df16-47b0-9d87-3ff4a50be27d.png">

**Comment by csbalazs** [comment]
> Here is the file as zip to be decompressed and placed in build/media_source/vendor/tinymce/langs/ folder to replace the one present.
> [hu.es5.js.zip](https://github.com/joomla/joomla-cms/files/7186836/hu.es5.js.zip)
> 
> <img alt="Screen Shot 2021-09-17 at 17 36 29" width="345" src="https://user-images.githubusercontent.com/869724/133816235-2aa3b223-98ec-4858-970a-534dc572ac5d.png">
> 
> @Bakual @richard67

That already looks good!

**Comment by infograf768** [comment]
Here is a zip of the file to use for French
[fr.es5.js.zip](https://github.com/joomla/joomla-cms/files/7187013/fr.es5.js.zip)

The files which are ready are here
https://www.tiny.cloud/get-tiny/language-packages/

To whoever will merge these lang packs, WARNING with file names and top of the file line.

In both cases Hungarian and French, I had to modify inside the file to `tinymce.addI18n('hu',{` and `tinymce.addI18n('fr',{` instead of fr-FR and hu-HU

Therefore these 2 above are corrected.

**Comment by infograf768** [comment]
@joomla/cms-maintainers

I asked TTs in the Private Forum to update and post there the new files.
https://forum.joomla.org/viewtopic.php?f=54&t=988685

Hungarian and French already available there.

**Comment by Bakual** [comment]
See https://github.com/joomla/joomla-cms/pull/35599 for the updated language files.
This here can be closed
