### ISSUE TITLE
J 4.0.x Mark Field as Required (UX)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#35583]
### What needs to be fixed
When you want to update or upload a Joomla Package you have a checkbox where you confirm that you made a backup before. This field should be marked as obligatory

### Why this should be fixed
Since no one knows that this field is obligatory it seems that the update Button is not working

### How would you fix it
Solution 1) Put a validation message when not ticked
Solution 2) (less effective) add an asterisk to the checkbox and label it as obligatory

### Side Effects expected
no

**Comment by PhilETaylor** [comment]
I would vote for removing the said checkbox all together. It’s just a useless barrier to functional use and 99% of people will just check it and still not have a backup. It’s a useless roadblock.

**Comment by coolcat-creations** [comment]
yes, would be happy with that too.

**Comment by Quy** [comment]
@bembelimen

**Comment by Quy** [comment]
Duplicate #35055
