### ISSUE TITLE
[J4] Missing language constants in com_modules for moduleclass and caching

### ISSUE THREAD

**Issue by hennysmafter** [joomla/joomla-cms#35586]
### Steps to reproduce the issue
Install latest Joomla 4.
Install any extension that uses these constants:

COM_MODULES_FIELD_MODULECLASS_SFX_DESC
COM_MODULES_FIELD_CACHING_DESC

### Expected result
In Joomla 3 these constants where like this:

COM_MODULES_FIELD_MODULECLASS_SFX_DESC="A suffix to be applied to the CSS class of the module. This allows for individual module styling."
COM_MODULES_FIELD_CACHING_DESC="Use the global cache setting to cache the content of this module or disable caching for this module."

### Actual result
Extensions that are using these constants do now show to the end user:

COM_MODULES_FIELD_MODULECLASS_SFX_DESC
COM_MODULES_FIELD_CACHING_DESC

Which is expected

### System information (as much as possible)
J 4.0.3
PHP 7.4

### Additional comments
Are these options now depreciated? We did look if we could find some info about this but to no avail.

**Comment by infograf768** [comment]
See discussion here:
https://github.com/joomla/joomla-cms/issues/35580

**Comment by Bakual** [comment]
Within core, we don't use those descriptions anymore as we thought there is no meaningful information in it. So it got removed with a lot of other descriptions.
Of course you still can add a description yourself in your extension, but you need to provide your own language string for it then.

**Comment by Bakual** [comment]
Ah and also keep in mind that the `moduleclass_sfx` param no longer is a suffix. We just kept the name for B/C reasons, but it's a simple module class now, no suffix anymore. So the old description doesn't fit anymore anyway.

**Comment by brianteeman** [comment]
This should be closed as the question has been answered.
