### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by xhorizont** [joomla/joomla-cms#35596]
Articles in Category Blog Menu Item Type displays Division by zero error.

Example url:    ...index.php?option=com_content&view=category&layout=blog&id=8

Debug:

Call stack
#	Function	Location
1	()	JROOT/plugins/system/helixultimate/overrides/com_content/category/blog.php:107
2	require()	JROOT/templates/shaper_helixultimate/html/com_content/category/blog.php:11
3	include()	JROOT/libraries/src/MVC/View/HtmlView.php:429
4	Joomla\CMS\MVC\View\HtmlView->loadTemplate()	JROOT/libraries/src/MVC/View/HtmlView.php:218
5	Joomla\CMS\MVC\View\HtmlView->display()	JROOT/libraries/src/MVC/View/CategoryView.php:268
6	Joomla\CMS\MVC\View\CategoryView->display()	JROOT/components/com_content/src/View/Category/HtmlView.php:207
7	Joomla\Component\Content\Site\View\Category\HtmlView->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:692
8	Joomla\CMS\MVC\Controller\BaseController->display()	JROOT/components/com_content/src/Controller/DisplayController.php:125
9	Joomla\Component\Content\Site\Controller\DisplayController->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:730
10	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
11	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()	JROOT/components/com_content/src/Dispatcher/Dispatcher.php:55
12	Joomla\Component\Content\Site\Dispatcher\Dispatcher->dispatch()	JROOT/libraries/src/Component/ComponentHelper.php:389
13	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/SiteApplication.php:206
14	Joomla\CMS\Application\SiteApplication->dispatch()	JROOT/libraries/src/Application/SiteApplication.php:245
15	Joomla\CMS\Application\SiteApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:278
16	Joomla\CMS\Application\CMSApplication->execute()	JROOT/includes/app.php:63
17	require_once()	JROOT/index.php:32

**Comment by alikon** [comment]
did the same happens without _helixultimate_  ?

**Comment by PhilETaylor** [comment]
This is not a Joomla issue, and should be closed. The problem is in non-core Joomla code.
