### ISSUE TITLE
Joomla 4.0.3 - Toggle Menu - Dashboards do not load

### ISSUE THREAD

**Issue by Rickard19** [joomla/joomla-cms#35598]
### Steps to reproduce the issue
Hello.

When I toggle the menu and it only displays the icons. The Home Dashboard and Help Dashboard are the only buttons that display the dashboards. The other icons when clicked re-expand the toggle menu and their respective drop menu drops down.

Thank you

**Comment by PhilETaylor** [comment]
I believe this is the expected behaviour, although several of us have commented before how this is not the real-world user expectation for a collapsed menu.

**Comment by Quy** [comment]
Duplicate #32934. Thanks for the report.

**Comment by brianteeman** [comment]
> The other icons when clicked re-expand the toggle menu and their respective drop menu drops down.

How else would you do it? A button should only do one thing

**Comment by Hackwar** [comment]
Thank you for reporting this issue, however this is expected behavior. Because of that, I'm closing this one.
