### ISSUE TITLE
[4.0.3] Conditional fields of the contact component do not respect the assigned category

### ISSUE THREAD

**Issue by GennaroMarra** [joomla/joomla-cms#35609]
Hello, conditional fields do not respect the category assignment of a given form.

Although they are assigned to a certain category of forms, they also appear in the other forms of a different category.
If I click on the Test 01 menu item for the first time, the conditional field "Test 01" appears correctly, the same thing happens for "Test 02", but if I decide to click again on the "Test 01" menu item, the in the form incorrectly appears "Test 01" the conditional field "Test 02".

Link to a clean installation of the latest version of Joomla 4: https://advsinopia.eu/test-01

These are the backend settings:
![test01](https://user-images.githubusercontent.com/37039554/134317813-33d2703e-13ce-4c27-8132-f2f6e278ea89.jpg)
![test02](https://user-images.githubusercontent.com/37039554/134317818-99d9f15a-f6e2-4d06-ba01-bb4d3f1221e3.jpg)

Thanks

**Comment by GennaroMarra** [comment]
PHP attivo su Linux srv.hdedi-xlogic2600.org 3.10.0-962.3.2.lve1.5.56.el7.x86_64 #1 SMP Thu May 27 10:10:44 UTC 2021 x86_64
Tipo database 	mysql
Versione database 	10.3.31-MariaDB-cll-lve
Collation database 	latin1_swedish_ci
Collation connessione database 	utf8mb4_general_ci
Crittografia connessione database 	Nessuno
Il server del database supporta la crittografia della connessione 	No
Versione PHP 	7.4.23
Web Server 	LiteSpeed
WebServer interfaccia PHP 	litespeed
Versione di Joomla! 	Joomla! 4.0.3 Stable [ Furaha ] 12-September-2021 10:39 GMT
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:92.0) Gecko/20100101 Firefox/92.0

**Comment by GennaroMarra** [comment]
Hello, since I haven't received feedback for seven days now, so is it just my problem?

I would like to use Joomla 4 but I'm stuck with this problem, thanks to those who want to give me a kind reply

**Comment by joomdonation** [comment]
@GennaroMarra Look like there is a bug here. While waiting for a proper solution, you can solve it by removing these lines of code https://github.com/joomla/joomla-cms/blob/4.0-dev/components/com_contact/src/View/Contact/HtmlView.php#L135-L140 from your Joomla installation (it prevents Joomla! to use wrong catid data for contact stored in session)

**Comment by GennaroMarra** [comment]
> 
> 
> @GennaroMarra Look like there is a bug here. While waiting for a proper solution, you can solve it by removing these lines of code https://github.com/joomla/joomla-cms/blob/4.0-dev/components/com_contact/src/View/Contact/HtmlView.php#L135-L140 from your Joomla installation (it prevents Joomla! to use wrong catid data for contact stored in session)

Good morning and thank you ;-)

**Comment by joomdonation** [comment]
@GennaroMarra Does that change solve your issue?

**Comment by GennaroMarra** [comment]
> 
> 
> @GennaroMarra Does that change solve your issue?

After I try and update you

**Comment by joomdonation** [comment]
@GennaroMarra OK. Please try the suggested change and update us back with the result. Thanks !

**Comment by GennaroMarra** [comment]
> 
> 
> @GennaroMarra OK. Please try the suggested change and update us back with the result. Thanks !

It works :-)

**Comment by joomdonation** [comment]
@GennaroMarra Please test PR https://github.com/joomla/joomla-cms/pull/35763 so that this issue will be fixed in next release.
