### ISSUE TITLE
[4.x] npm updates

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#35604]
There needs to be a procedure to make sure that all npm packages are up to date before a new joomla release is made.

For example there have been three tinymce releases since the release of Joomla 4.0.0

**Comment by dgrammatiko** [comment]
https://www.whitesourcesoftware.com/free-developer-tools/renovate/ does an excellent job, it's free and will work nicely in the project's context

**Comment by brianteeman** [comment]
Thanks for the suggestion. I dont care what is used as long as something is and we dont end up making a release that contains outdated software

**Comment by dgrammatiko** [comment]
This can only be tackled by people with the right permissions in this repo. I'm not one of them so I can only propose something that I have used in countless projects so far and I know that it works...
Still waiting for the same thing to be enabled in the custom elements repo (although that repo has dependencies only for the tools)

**Comment by brianteeman** [comment]
Closed as no one who can do anything about this shows the remotes sign of any interest
