### ISSUE TITLE
J 4.0 Media Manager improve Error Message

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#35618]
### What needs to be fixed
I tried to upload an svg in media manager, I made all settings I could think of to make this possible. Still getting an error but the error does not help me at all:
![grafik](https://user-images.githubusercontent.com/828371/134055310-712f49be-11d3-44da-818a-26108b1f55a0.png)

### Why this should be fixed
If an image could not be uploaded I would be curious to know the reasons (too big, filetype does not match, something else?)

### How would you fix it
get through the error messages and improve them

### Side Effects expected
no

**Comment by Quy** [comment]
Duplicate #33702
