### ISSUE TITLE
Italian language pack for Joomla 3.x unavailable

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#35619]
Information about the Italian Language Pack has disapeared from https://update.joomla.org/language/translationlist_3.xml

No language update is offered, can you please fix this?

Thanks!

**Comment by infograf768** [comment]
Someone has modified the main package name by adding the version 3.10.2 as suffix and doubling the `IItalian`
I corrected it back to what it should be. That name should NEVER be modified

<img width="418" alt="Screen Shot 2021-09-21 at 08 24 39" src="https://user-images.githubusercontent.com/869724/134121807-87c44adc-69ad-486a-880c-fac8cc9a657b.png">


Let's wait a bit until a new cron does its job.

**Comment by alikon** [comment]
should be ok now `<extension name="Italian" element="pkg_it-IT" type="package" version="3.10.2.1" detailsurl="https://update.joomla.org/language/details3/it-IT_details.xml"/>`

**Comment by infograf768** [comment]
It IS now available. My correction is all what was needed.
<img width="1143" alt="Screen Shot 2021-09-21 at 09 10 00" src="https://user-images.githubusercontent.com/869724/134127145-7a0d84db-bb5c-4592-8f97-a3418016a295.png">

**Comment by smz** [comment]
Confirmed, all is good now.

Thanks to everybody!
