### ISSUE TITLE
[4.x] bootstrap.renderModal - backdrop => static has no influence on the modal behaviour

### ISSUE THREAD

**Issue by Kubik-Rubik** [joomla/joomla-cms#35624]
### Steps to reproduce the issue

Easy to reproduce:

Click on the link "Add module to the dashboard" on the main dashboard in the backend to open a modal window. This modal window uses the backdrop option with the value "static". When the backdrop option is set to static, the modal should not close when clicking outside it.

### Expected result

Modal is not closed when clicking outside it. This option works fine in Joomla! 3.x.

### Actual result

Modal is closed.

### System information (as much as possible)

Tested with Joomla! 4.0.3 in Chrome and Firefox.

**Comment by dgrammatiko** [comment]
Rename the `data-backdrop="static"` to `data-bs-backdrop="static"` and it will work as expected

**Comment by Kubik-Rubik** [comment]
Hey Dimitris,

I know, but this is not possible with `HTMLHelper::_('bootstrap.renderModal', ....)` and it must be fixed there for the new syntax in Bootstrap 5.

Cheers

**Comment by dgrammatiko** [comment]
> I know, but this is not possible with HTMLHelper::_('bootstrap.renderModal', ....)

I don't understand what was impossible, it was literally a string replace: https://github.com/joomla/joomla-cms/pull/35626

**Comment by Kubik-Rubik** [comment]
We have a solution with https://github.com/joomla/joomla-cms/pull/35626.

Thanks!
