### ISSUE TITLE
[4.0.3] 404 page + SEF

### ISSUE THREAD

**Issue by mrownicki** [joomla/joomla-cms#35620]
### Steps to reproduce the issue
Activate SEF to ON
change htacess.txt to .htaccess

*Basic htaccess file with no custom modifications.
*2 installations Cassiopeia and Helix this same results.

### Expected result

Should show 404 PAGE

### Actual result

Joomla dont show 404 error! All bad urls redirect to homepage

### System information (as much as possible)

404 page show only if SEF is OFF

### Additional comments
This should be fix soon as possible.

Impact SEO and UX

**Comment by simbus82** [comment]
Do you have mod_rewrite enabled in your server?

**Comment by mrownicki** [comment]
Yes


Okey i find what is cause problem.

I home page is a component like SP page builder on homepage by default. 

404 page not working. I can write /34343/3434343 and always redirect to home.

But if  i go to article /article-1/34353543  show 404.

**OK this is problem JoomlaShaper not Joomla.**

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35620">issues.joomla.org/tracker/joomla-cms/35620</a>.</sub>
