### ISSUE TITLE
Issue on tablets - Unable to select item in the dropdown

### ISSUE THREAD

**Issue by TawareAditya** [joomla/joomla-cms#35623]
### Steps to reproduce the issue
1. Launch Joomla site in the Samsung or any tablet.
2. Open the dropdown filter and try to choose value
3. When user click item from the dropdown nothing happen.

### Expected result
1. User should able to select value from the dropdown in the Tablet screen

### Actual result
Unable to select value in the dropdown

### System information (as much as possible)
Samsung Tablet. Latest Chrome browser.

**Comment by dgrammatiko** [comment]
Test: https://github.com/joomla/joomla-cms/pull/35518

**Comment by chmst** [comment]
closing as there is a pr
