### ISSUE TITLE
[4.0] TinyMCE uses a not available  'glob' flag

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#35633]
### Steps to reproduce the issue
Install Joomla 4 and open a view having a TinyMCE editor

### Expected result
No errors, all works fine

### Actual result
error 0: Undefined constant "GLOB_BRACE"

### Additional comments
The line 477 of the file tinymce.php uses the 'GLOB_BRACE' flag:
foreach (glob(JPATH_ROOT . $template_path . '/*.{html,txt}', GLOB_BRACE) as $filepath)

but: The GLOB_BRACE flag is not available on some non GNU systems, like Solaris or Alpine Linux.
see: https://www.php.net/manual/en/function.glob.php

That one should be removed

**Comment by richard67** [comment]
The use of that flag had been introduced with PR #33130 . Am working on a fix.

**Comment by richard67** [comment]
Closing as having a pull request (PR). Please test #35636 and let me know if you would prefer the other possible solution described in that PR's description, the one with the try and catch. Thanks in advance.
