### ISSUE TITLE
[3.10.2] Wrong links in Weblinks

### ISSUE THREAD

**Issue by crommie** [joomla/joomla-cms#35635]
### Problem identified

In the weblinks, I see dutchjoomla.org and forum.dutchjoomla.org. They don't exist anymore (and have been extinct for years). I don't know where to report this.

### Proposed solution

Replace it with https://www.joomlacommunity.nl/ and https://www.joomlacommunity.nl/forum

**Comment by joomdonation** [comment]
Sorry, where do you see this? Could you please attach a screenshot?

**Comment by crommie** [comment]
Backend -> Components -> Weblinks

![afbeelding](https://user-images.githubusercontent.com/11227077/134303665-3b7bc0fa-d100-4fd9-b871-ae5d5284185f.png)

**Comment by crommie** [comment]
Oh. I just realised this site was already there in the Joomla 1.5 times. Maybe they have been in there since 1.5?

**Comment by joomdonation** [comment]
If so, it is managed in the website. You need to contact the administrator of the website and ask her/him to update the links. This is not related to the weblinks extension.

**Comment by crommie** [comment]
I am the administrator of the website :). 

I just checked with a site that started out as a 3.9.x site and the same links are in there. I did not put a single one of them in, so where do they come from if it's not from weblinks itself?

**Comment by joomdonation** [comment]
Someone must entered it or it was there from long time ago. You can try to install a fresh installation of Joomla 3, Joomla 4, and install weblinks, these links won't be inserted automatically :).

**Comment by crommie** [comment]
Eh no. I'm 100% sure no one entered any of this. Maybe they were there in older versions of Joomla and still present in the database, and they re-surface with the Weblinks update.

**Comment by joomdonation** [comment]
To be honest, I have no clue about this. From the current code in weblinks, I could not see how it could happen because there is no code to insert these weblinks. Also, there are no code to make the old weblinks re-surface. For now, I guess you just need to delete it and it won't appear again on next update :)

**Comment by crommie** [comment]
So I found a mystery :)

**Comment by brianteeman** [comment]
All those links (except the dutch) were in very very old sample data that was always installed. I assume the additional dutch links came from a localisation script

**Comment by crommie** [comment]
Thanks @brianteeman and @joomdonation I'm going to delete them and never think about this again.

**Comment by joomdonation** [comment]
> All those links (except the dutch) were in very very old sample data that was always installed

Thanks for the info @brianteeman.

**Comment by brianteeman** [comment]
sometimes it helps to be old

**Comment by crommie** [comment]
And have cast-iron memory.

(Yes. I just discovered that the site I thought was a fresh install was in fact a copy of the existing site that had the old weblinks since J 1.5 - my memory isn't as good as I thought it was)
