### ISSUE TITLE
[4.0] Change database layout to support smaller screens

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#35631]
### What needs to be fixed
Layout is only horizontal so scrolling is required to see the entire table.
This is visually annoying.
![image](https://user-images.githubusercontent.com/1850089/134227811-d692c621-b2ac-4bbf-9ed4-6d94483954ff.png)

### How would you fix it
Change form for smaller screens to vertical informational blocks.

### Side Effects expected
None.

**Comment by brianteeman** [comment]
Like all pages they can only be adjusted so much and they can't fit at every screen size. What screen size is that?

Switching to vertical layouts is fine but it doesn't work very well when you have multiple rows.

For me its fine if it works at regular/popular screen sizes including mobile which it does

**Comment by N6REJ** [comment]
about 1/2 1920x1080.
I'm thinking "card" layouts would work.  I'll check mobile tomorrow but shrinking to minimum didn't help.

**Comment by N6REJ** [comment]
@brianteeman here's i10 display.  Notice its still chopped.  
![image](https://user-images.githubusercontent.com/1850089/134414150-358af16c-940e-414f-a614-20352a2f5226.png)
![image](https://user-images.githubusercontent.com/1850089/134414198-af03091d-1237-4693-bc14-1407c751bbb0.png)
Card style layout would be perfect here.

**Comment by Octopus2** [comment]
I have the same display error on my Android 11 smartphone (Samsung browser). Same with the user settings. Joomla 4.0.3 with German language package
![Screenshot_20210921-215629_Samsung Internet](https://user-images.githubusercontent.com/4060419/134483748-1c90542e-8490-423d-8c38-d7d97e04d600.jpg)
.

**Comment by brianteeman** [comment]
@Octopus2 the toolbar is accessed from the cog icon in the top right and the user menu from the button on the bottom
![image](https://user-images.githubusercontent.com/1296369/134484893-150b3310-986b-4c5d-8d0f-7b777117925f.png)

![image](https://user-images.githubusercontent.com/1296369/134484902-44416c68-df5f-4d46-8171-e9960b92f803.png)

**Comment by Octopus2** [comment]
@brianteeman Thanks, but I understood how to use it. With the screenshot I wanted to show that in this view the white box with the list of tables on the right-hand side is not closed and the entire screen is shifted to the left (which can be seen from the cog icon in the upper right corner). Maybe because of the longer words "administrator" and "component".

**Comment by Quy** [comment]
Related #32912

**Comment by brianteeman** [comment]
I am closing this as the reported issue for the database layout on small screens was resolved with #35731
