### ISSUE TITLE
News Tags added after Update to Joomla 4 disappear on editor reload after save.

### ISSUE THREAD

**Issue by DonPedro34** [joomla/joomla-cms#35649]
### Steps to reproduce the issue

Enter the following a new tag.
Enter any Additional Tags after the new.

Use Tags from before Update to Joomla 4.

Press Save in the Editor. On reload the new Tags are gone.

### Expected result

All the Tags are loaded.

### Actual result

All Tags are actually stored and displayed on the Frontend. But at reload in Backend they new ones disappear.

### System information (as much as possible)

Joomla 4.0.3.

### Additional comments

This worked in version 3.10.

**Comment by dgrammatiko** [comment]
Remove the parenthesis

**Comment by alikon** [comment]
unable to reproduce

**Comment by abs66on** [comment]
Hello all, I have the same problem. My TAGs consist of several words. because of this, the alias have a hyphen.  Also for me, when editing posts, some TAGs are no longer displayed. If I take the hyphens out of the alias everything works normally.

**Comment by DonPedro34** [comment]
This is pretty annoying.

Old tags created before the Update to J4 can be used without Problem, new Tags disappear on reload.

Makes it rather unuseable!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35649">issues.joomla.org/tracker/joomla-cms/35649</a>.</sub>

**Comment by alexhokamp** [comment]
I could replicate the Issue. Upgraded a Website to Joomla 4.0.3. Seems to be a problem with Ajax. When you go into the Tags: Options and change in Data Entry the Tag Entry Mode to Nested, it worked in my installation. This obviously does not correct the error in the Data Entry Mode when it is set to AJAX, but it solves the problem until the AJAX Data Entry Mode is checked. ![screen shot 2021-11-12 at 10 44 28](https://issues.joomla.org/uploads/1/0f702aa4e204336ab04c7da54de5fb69.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35649">issues.joomla.org/tracker/joomla-cms/35649</a>.</sub>

**Comment by unet2581** [comment]
Thank you [alexhokamp](https://github.com/alexhokamp)

**Comment by jv5** [comment]
I also have this issue. Migrated to J4 and lost ability to save tags to articles. Existing tags from articles migrated to J4 work as expected. Flipping the Tags Data Entry Option to "Nested" did not work for me. 

FWIW, nothing gets written to the contentitem_tag_map table.

**Comment by morphinestyle** [comment]
I also have this issue. Not working properly adding new tags from articles, saving, and when save again it disappears.
(website updated from 3.x to 4)

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/39254 should address this issue. Please help testing. Thanks !

**Comment by jv5** [comment]
Did not work for me.  Tags do not get saved to article. Also, nothing gets written to the contentitem_tag_map table.

**Comment by joomdonation** [comment]
@jv5 Could cause by something else. If you give me access to your site and tell me step by step what I need to do to see the issue, I will be happy to take a look at it and try to find a solution

**Comment by jv5** [comment]
@joomdonation - Thank you! I would appreciate that. How do I send the access info to you?

**Comment by joomdonation** [comment]
@jv5 See https://github.com/joomla/joomla-cms/pull/39254#issuecomment-1323232859 for the requested information.

**Comment by jv5** [comment]
@joomdonation Email with info sent on 11/27/22. Let me know if you did not receive.

**Comment by joomdonation** [comment]
@jv5 Sorry, missed the email. Just checked and saw your email. Replied your email because the user account you sent me is blocked, so I could not login to check

**Comment by jv5** [comment]
@joomdonation Should be good now.

**Comment by joomdonation** [comment]
Just want to update that I checked the site sent by @jv5 and found that the issue somehow related to field `core_xreference` field in **#__ucm_content** table does not have default value. I don't see that field in the table from Joomla 4 installation, so guess it was used in Joomla 3. The solution could be :

- Set default value for that field
- Or maybe drop that field from the table 

It is not related to the PR which I made, just post the reason and solution here in case someone has similar problem

**Comment by morphinestyle** [comment]
Hello @joomdonation, i have same TAG issue: i try to find same field?

**Comment by joomdonation** [comment]
@morphinestyle You can try to apply the change from PR https://github.com/joomla/joomla-cms/pull/39254/ to see if it solves the issue first. You can apply that change by getting the attached file, unzip it, upload the received file to **libraries/src/Form/Field** folder on your site to see if it solves the issue.

[TagField.zip](https://github.com/joomla/joomla-cms/files/10124223/TagField.zip)

**Comment by morphinestyle** [comment]
@joomdonation where i can found "attached file"?
Sorry, but i don't see attached files.

**Comment by joomdonation** [comment]
@morphinestyle Sorry, it is the TagField.zip in the message. See the attached screenshot
![tagfield](https://user-images.githubusercontent.com/977664/204836442-6db6ad2d-8f8a-473f-9e6a-f1947f8fe823.png)

**Comment by jv5** [comment]
As suggested by @joomdonation, I edited the ucm_content table and dropped the core_xreference column. This appears to have resolved the issue. 

When migrating my site from Joomla 3.x to 4.x, I used a migration plugin to transfer the ucm_content table (among others). During this transfer, the plugin did not remove the core_xreference column.

Thank you @joomdonation for your help!

**Comment by morphinestyle** [comment]
Sorry, you're right, i was looking on PR 39254.
I will try and let you know as soon.

**Comment by brianteeman** [comment]
@jv5 what was this migration plugin so we can let them know it is broken

**Comment by jv5** [comment]
@brianteeman SP Transfer

Not sure the app is "broken" - although I did have many issues using it - but regarding this particular issue, the transfer of the ucm_content table was not automated by the plugin. It was not part of the "Core Files" transfer that was somewhat automated. It was when I discovered issues with the Tags that I discovered I needed to also transfer the ucm_content table (and a few others that were part of the core database files that were not transferred). When I transferred the ucm_content table over, my old tags then appeared, but I was unable to add new tags, which was the issue that led me to this thread.

[Here is a link](https://www.kainotomo.com/products/sp-transfer/documentation/migrate-old-site-to-joomla-version-3-x) to the SP Transfer instructions I used.

**Comment by morphinestyle** [comment]
@joomdonation sorry for the late reply.
It Works! Issue solved, Thank you!

**Comment by getimo** [comment]
Hello, I just migrated from Joomla 3 to 4. I have the same issue but was not able to fix it with the file attched by @joomdonation Anybody an idea what I could do else?

**Comment by jv5** [comment]
@getimo, did you check to see if the ucm_content table has a "core_xreference" column? Per my post above, I deleted this column and it fixed it for me.

**Comment by chris-m87** [comment]
Hello, I have the same issue. I migrated from J3 to J4 and I am not able to save tags in articles. I have already applied the two changes by replacing the revised TagField.php and I have also deleted the core_xreference column. Unfortunately the issue remains the same and I still cannot save the tags. When I push the save button Joomla states in green color that I have saved, but the tags which I have selected out of the list are gone again. Is there further help?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35649">issues.joomla.org/tracker/joomla-cms/35649</a>.</sub>

**Comment by chris-m87** [comment]
Hallo, I have already found an answer to this issue. In my case, I had to replace the table #_content_types in my DB with another table from a J4 version, where the saving of tags was working. After replacing it, I was able to save the tags in my articles.

**Comment by chmst** [comment]
@joomdonation should we re open this issue?

**Comment by joomdonation** [comment]
@getimo Maybe you can try the solution which I posted on this post https://www.facebook.com/groups/joomlanospam/posts/10158751157500997/ on Joomla! User Group on Facebook  (see my last comment on that post )

Check this link https://gist.github.com/joomdonation/ceac27f88445f9ff4d3d4505ee324ecb for the SQL commands need to be executed (replace jos_ with database table prefix uses for your site)

Hope that fix the issue for you. If not, I'm afraid of you will need to have a developer to check it directly on your site.

**Comment by getimo** [comment]
@joomdonation Thank you very much for not giving up helping me! I will try that fix too. In case it does not work: Are you available for custom jobs like this to fix that?
