### ISSUE TITLE
tinymce language js

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#35646]
Because of the way that tinymce works it can only use a language file that is named exactly the same as the language. As a result none of the minified files `eg de.min.js ` will ever be used. 

They are also listed as a language in the plugin configuration.

Either the build scripts are set to exclude these js files OR they are minified but not renamed.

I took a look at the build scripts but its beyond my skillset to implement

**Comment by wojsmol** [comment]
@brianteeman If I read code correctly the adding something like https://github.com/joomla/joomla-cms/blob/95f5ac8f345b38de1f0e2086d07b15ace3def54c/build/build-modules-js/compilejs.es6.js#L62-L64 should fix the issue.

**Comment by brianteeman** [comment]
@wojsmol sadly not

**Comment by brianteeman** [comment]
Closed as we have a PR #35878
