### ISSUE TITLE
Errors in Joomla API endpoint documentation for articles

### ISSUE THREAD

**Issue by MayaSima** [joomla/joomla-cms#35658]
### Steps to reproduce the issue
GET list of articles is using "articles" in plural: `/api/index.php/v1/content/articles`
the rest of the endpoints for single article (GET, POST, DELETE, PATCH) are using "article" in singular, but the endpoints do not work, returning 404 errors:
`{
    "errors": [
        {
            "title": "Resource not found",
            "code": 404
        }
    ]
}`

Changing `article` to `articles` in each corresponding endpoint fixes the issue:

`/api/index.php/v1/content/article/{article_id}` -> `/api/index.php/v1/content/articles/{article_id}`
`/api/index.php/v1/content/article` -> `/api/index.php/v1/content/articles`

DELETE article still doesn't work
`DELETE {{base_path}}/api/index.php/v1/content/articles/4`

### Expected result
Article gets deleted

### Actual result
`{
    "errors": [
        {
            "title": "Forbidden"
        }
    ]
}`

### System information (as much as possible)
See attachment

### Additional comments
[systeminfo-2021-09-24T05_10_52-04_00.zip](https://github.com/joomla/joomla-cms/files/7224558/systeminfo-2021-09-24T05_10_52-04_00.zip)
![image](https://user-images.githubusercontent.com/13040479/134651278-1bf135cb-8e6d-492e-94e5-dde7de234753.png)

**Comment by zero-24** [comment]
I can confirm that issue but didnt had time to look into the details but it looks like they got changed intentionally: https://github.com/joomla/joomla-cms/pull/34093

So the docs and the postman file needs to be updated with the new routes.

**Comment by alikon** [comment]
you can delete an article only if it is in trashed status (-2)

for reference see:

- #31581
- #31130

and yes the docs is outdated

**Comment by alikon** [comment]
docs updated https://docs.joomla.org/J4.x:Joomla_Core_APIs#Articles
