### ISSUE TITLE
Language switcher returns 404 in German / English site

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#35650]
![screen shot 2021-09-23 at 08 48 48](https://issues.joomla.org/uploads/1/54fc2242edd264068f968e164441ff5d.jpg)### Steps to reproduce the issue
1. Both Languages installed and published. Both Content languages created and published (German is default language)
2. Main menus for ALL, en & de have their own default homepages. Menu module for ALL is unpublished. Both language menus/modules are published
3. Multilingual Status is published, shows no issues.
4. Language filter is active - "remove url language code' is set to 'yes'
5. Language switcher is active and published
6. Template YP - after switching to Cassiopeia the problem remains

### Expected result
Site switches to English with ..../en and to german without de

### Actual result
Switching from German to English works
Switching back to German gets an 404 error page not found

### System information (as much as possible)

 PHP 7.4.23, Joomla 4.0.3
The problem appears on a site hosted by IONOS. The same problem is with a site hosted by Rochen
A copy of this page transferred to Host Europe works.

### Additional comments

![screen shot 2021-09-23 at 08 48 59](https://issues.joomla.org/uploads/1/c5e3529ce21ee1569b6107b9508bb932.jpg)

**Comment by richard67** [comment]
Duplicate report to #35541 ?

**Comment by paternax** [comment]
Sorry Richard, I didn't see this report. Perhaps helps the information, that an identical copy of the system on another host have no problem with the language switcher.

**Comment by richard67** [comment]
@paternax Yes, that has also been discovered in #35541 .

**Comment by richard67** [comment]
Closing as duplicate report. See #35541 . Thanks for reporting though.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35650">issues.joomla.org/tracker/joomla-cms/35650</a>.</sub>
