### ISSUE TITLE
[4.0] Admin menu wrong class

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#35665]
### Steps to reproduce the issue

I have two components with similar names, like this: com_thingy, com_thingy_plus

### Expected result

All seems fine, except...

### Actual result

If I select com_thingy_plus in the admin menu then both are highlighted. And if there are submenus both are open.

### Additional comments

I have traced the problem to line 62 of media/mod_menu/js/admin-menu.js
```    if (!link.href.match(/index\.php$/) && currentUrl.indexOf(link.href) === 0 || link.href.match(/index\.php$/) && currentUrl.match(/index\.php$/)) {```

I first noticed this with a custom media component named com_media_thingy - a bit of a nuisance to rename come_thingy_media!

**Comment by PhilETaylor** [comment]
ffs here we go again. This would be so much easier to handle in PHP instead of JS.

**Comment by dgrammatiko** [comment]
>  This would be so much easier to handle in PHP instead of JS.

This would be so much easier if in the PHP we assigned an attribute like `data-name=unique` so JS doesn't have to do a lot of guessing (which no matter how good the regex is it will fail for some edge case that wasn't considered as valid cases).

**Comment by brianteeman** [comment]
duplicate of #34067

**Comment by ceford** [comment]
Searched before positing but clearly no well enough. Closing as #34067 has much better problem description.
