### ISSUE TITLE
[4.0.3] Add new User: Email sent without Sitename, Username and Password if default admin language is not english (%s instead)

### ISSUE THREAD

**Issue by fab966** [joomla/joomla-cms#35660]
### Steps to reproduce the issue
A new fresh Joomla 4 installation with PHP 7.4.
Set the administrator's default language other than English (for example Italian).
Create a new Administrator User and set "Receive System Emails" on YES. 

### Expected result
The user should be receive this Email, with Sitename, Username and Password:

Hello Marc,

You have been added as a User to _Sitename_ by an Administrator.

This email has your username and password to log in to https://www.sitename

Username: _Marc_
Password: _123456789_

### Actual result
For example, with Italian default Administrator Language, Login Data are shown with **%s**:

Salve %s,

sei stato aggiunto come Utente sul sito %s da un Amministratore.

Questa email contiene i tuoi nome utente e password per accedere a %s

Nome utente: %s
Password: %s

Non rispondere a questo messaggio in quanto generato automaticamente e solo a scopo informativo.

### System information (as much as possible)
PHP Built On 	Linux dalin.dnshigh.com
Database Type 	mysql
Database Version 	5.7.35-log
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	Yes
PHP Version 	7.4.23
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 4.0.3 Stable

### Additional comments

It looks like a Language Association Issue...

**Comment by PhilETaylor** [comment]
This is a translation issue, not a Joomla issue. 

Joomla 4 is NOT using sprintf php style `%s` replacements in `PLG_USER_JOOMLA_NEW_USER_EMAIL_BODY` but hard coded placeholders like `{SITENAME}`

```
PLG_USER_JOOMLA_NEW_USER_EMAIL_BODY="Hello {NAME},\n\n\nYou have been added as a User to {SITENAME} by an Administrator.\n\nThis email has your username and password to log in to {URL}\n\nUsername: {USERNAME}\nPassword: {PASSWORD}\n\n\nPlease do not respond to this message as it is automatically generated and is for information purposes only."
```

**Comment by Bakual** [comment]
This should be moved to https://github.com/joomla/core-translations or even better directly fixes in https://joomla.crowdin.com/cms

**Comment by PhilETaylor** [comment]
related https://github.com/joomla/joomla-cms/issues/35517

**Comment by fab966** [comment]
Thank a lot to all for the informations,
How can I move this issue to the right place?
Best regards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35660">issues.joomla.org/tracker/joomla-cms/35660</a>.</sub>

**Comment by fab966** [comment]
Changing from %s to _placeholders_ in language file solves the problem.

**Comment by infograf768** [comment]
TT informed of the issue.

This can be closed.
