### ISSUE TITLE
[4.0] Tag created data has additional offset

### ISSUE THREAD

**Issue by Harmageddon** [joomla/joomla-cms#35670]
Reported by user abs66 at https://forum.joomla.de/thread/14246-fehler-bei-der-tag-bearbeitung/.

### Steps to reproduce the issue

1. Set your server time (System - Global Configuration - Server) to something different from UTC. Testing this is more intuitive, if your server is actually located in this time zone (e.g. CEST = UTC+2). Otherwise, you'd have to do the appropriate calculations in order to check if the time fits.
2. Check the time zone setting of your own user (top right: User Menu - Edit Account - Basic Settings) to match your actual time zone (or to compensate for the "wrong" server time zone from step 1 if your server is on UTC).
3. At Components - Tags, create a new tag and save it.
4. Edit the tag and look at the created and modified date.
5. Save the tag multiple times.

### Expected result

- The creation date should be correct.
- The creation date should not be modified by saving the tag.

### Actual result

- The creation time is two hours ahead (in case of server time UTC+2) of the current time.
- The creation time is increased by two hours on every save.

### System information (as much as possible)

- Joomla! 4.0.3 stable
- PHP Version 7.3.10
- MySQL 5.6.19-67.0-log
- Server: Apache on Linux
- Server time: UTC+2

### Additional comments

After the first save, the created time in the database is correctly in UTC. So it appears to be a display issue in the form when you edit the tag. And the value shown there should IMO not be stored in the database when you save the tag again.

**Comment by alikon** [comment]
please test #35724
