### ISSUE TITLE
[4.0] Subforms - How to get right data-base-name

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#35677]
Hi,

in Joomla 3 it was possible to get the name or current subform in data-base-name.

Example:
If there was a subform called "attributes" and its subsubform called "options", it was possible to get these names in event by attribute "data-base-name"

`document.addEventListener('subform-row-add', ({ detail: { row } }) => {`

`<field name="attributes" type="subform"`

`<field name="options" type="subform"`

![img](https://i.imgur.com/nUjuDli.png)

Now all the items are anonymous:

![img](https://i.imgur.com/zS3W1eh.png)

Is there a way to get field names in the event to differentiate between each subforms?

Thank you, Jan

**Comment by Fedik** [comment]
This name should be equal to field name:
https://github.com/joomla/joomla-cms/blob/9bd9e5223520f71f1ab6b235e932dbbafd21ff7a/libraries/src/Form/Field/SubformField.php#L249

One difference I noticed between J3 and J4, it is `setup()`, tries to "read" the fieldname attribute, that looks strange to me:
https://github.com/joomla/joomla-cms/blob/9bd9e5223520f71f1ab6b235e932dbbafd21ff7a/libraries/src/Form/Field/SubformField.php#L199-L202
If attribute fieldname does not exists, it reset the `fieldname` property of the field, and use `__field` instead.

Please try remove `fieldname` form foreach, and check if it work. ~~or try add `fieldname` attribute to your field XML~~.

By default  `fieldname` is equal to "raw" name of field (without group and without form control):
https://github.com/joomla/joomla-cms/blob/81db97d940d854fe0bdaf72df3cfe8ed5475c395/libraries/src/Form/FormField.php#L540-L543

**Comment by Fedik** [comment]
It was added here #24711, but I do not see a reason why.

**Comment by PhocaCz** [comment]
Hi, thank you for the info:

> Please try remove fieldname form foreach, and check if it work.

Yes, this did the trick. Now the question is, it is a bug or some specific feature?

![img](https://i.imgur.com/FoANTW6.png)

The problematic part is, when there is no such information, you cannot get easily the subform which called the event. So if there are:
a) more levels of one form (form - subform - subform)
b) or more subform types in form

it is very problematic to detect which subform called the event. Finding this out from the html content of the form is very impractical and performance intensive.

**Comment by PhocaCz** [comment]
BTW:

> or try add fieldname attribute to your field XML.

This even does the trick.

**Comment by Fedik** [comment]
> Now the question is, it is a bug or some specific feature?

To me it is a bug. 
I will make PR a bit later, if you do not make it faster :)

**Comment by PhocaCz** [comment]
No problem for later PR, please link the PR here so I can test it.

Thank you very much.

Jan

**Comment by Fedik** [comment]
Please test #35685

**Comment by PhocaCz** [comment]
Thank you, tested now: https://github.com/joomla/joomla-cms/pull/35685#issuecomment-928168043
