### ISSUE TITLE
Causing issue in PHP8.0.11 due to BC break in PHP8.0 regarding call_user_func_array and named parameters

### ISSUE THREAD

**Issue by alexandreelise** [joomla/joomla-cms#35674]
Causing issue in PHP8.0.11 due to BC break in PHP8.0 regarding call_user_func_array and named parameters

A quick fix would be to do array_values($params) rather than just params which is causing a 
Fatal error in PHP8.0.11 Joomla 4.0.3 

https://github.com/joomla/joomla-cms/blob/e198c085b140fd0efef4496ad0dac57e5424a3fc/libraries/src/Captcha/Captcha.php#L227

**Comment by zero-24** [comment]
Closing here as there is a PR https://github.com/joomla/joomla-cms/pull/35675 thanks @alexandreelise

**Comment by alexandreelise** [comment]
No problem @zero-24 Doing my best to help the community and make Joomla! even better.

**Comment by PhilETaylor** [comment]
related to related to https://github.com/joomla/joomla-cms/issues/33529 which is the same issue.
