### ISSUE TITLE
[4.0] Accordions always collapsed by default

### ISSUE THREAD

**Issue by jreviews** [joomla/joomla-cms#35671]
### Steps to reproduce the issue

Create an accordion:

```php
<?php echo HTMLHelper::_('bootstrap.startAccordion', 'group', [
	'parent' => 'group',
	'active' => 'slide-1',
]); ?>

<?php echo HTMLHelper::_('bootstrap.addSlide', 'group', 'Title A', 'slide-1'); ?>
Content A
<?php echo HTMLHelper::_('bootstrap.endSlide'); ?>

<?php echo HTMLHelper::_('bootstrap.addSlide', 'group', 'Title B', 'slide-2'); ?>
Content B
<?php echo HTMLHelper::_('bootstrap.endSlide'); ?>

<?php echo HTMLHelper::_('bootstrap.endAccordion'); ?>
```

### Expected result

The first slide should be active and expanded on page load

### Actual result

All slides are collapsed

### System information (as much as possible)

Issue comes from `media/vendor/bootstrap/js/collapse.js` where all accordions are forced to collapse.

![image](https://user-images.githubusercontent.com/31069418/134782666-78d3897c-d1ba-4b0f-922b-73ccd07eb2d2.png)

### Additional comments

In addition to this, the aria-expanded attribute in accordions is always empty.

https://github.com/joomla/joomla-cms/blob/95f5ac8f345b38de1f0e2086d07b15ace3def54c/libraries/src/HTML/Helpers/Bootstrap.php#L720

Should be:

```php
$ariaExpanded = trim($in) === 'show' ? 'true' : 'false';
```

**Comment by brianteeman** [comment]
You don't need `'parent' => 'group',` in the array

I can not confirm your issue with aria-expanded

![collapse](https://user-images.githubusercontent.com/1296369/135324398-d238e22d-7e0f-4799-88a8-dbf11273d2cf.gif)

**Comment by jreviews** [comment]
You are right, without using the parent option, the active slide works, but also the accordion doesn't automatically collapse a slide when another one is opened, so you end up with all slides open as you click them. My understanding is that this is why you would use the `parent` option to begin with.

Check the code in the file I referenced.

```php
		$in        = static::$loaded[__CLASS__ . '::startAccordion'][$selector]['active'] === $id ? ' show' : '';
```

`$in` is set to ' show', with an extra leading space. Then after that you have a strict check that will never be true:

```
$ariaExpanded = $in === 'show' ? true : false; 
```

And finally, since the values are set to boolean instead of strings, they output on the page will either be one or zero within the attribute. 

For this last bit you may need to check the source of the page using `view-source:` in the address bar, rather than looking at the page after it's been loaded and javascript initialized.

**Comment by brianteeman** [comment]
I cannot confirm your comments regarding the $ariaexpanded. That is working perfectly as intended.
