### ISSUE TITLE
Fields not in search results

### ISSUE THREAD

**Issue by kokgreat** [joomla/joomla-cms#35688]
Hello. I test Joomla 4 locally, fill in the Fields (Content, Contacts) with data. The search does not see this data, it is not in the search results.
I also do it in Joomla 3 - I get a good result.

My System Information:
PHP Built On Windows NT TLT773 6.1 build 7601 (Windows 7 Professional Edition Service Pack 1) AMD64
Database Type mysql
Database Version 5.6.47
PHP Version 7.4.5
Web Server Apache
Joomla! Version Joomla! 4.0.3 Stable [ Furaha ] 12-September-2021 10:39 GMT

**Comment by chmst** [comment]
@kokgreat do you have a extension which searches over the field values in J3?

**Comment by kokgreat** [comment]
@chmst I don't know. I didn't install anything specifically for this. 
My Joomla 3 has installed: Zoo 3, Admin Tools 6.1.2...and other little things.

**Comment by Hackwar** [comment]
I assume this is a duplicate to #12829.

**Comment by Quy** [comment]
Closing as duplicate.
