### ISSUE TITLE
[4.0] Workflow Notification message

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#35694]
I am not 100% familiar with workflows and the intended behaviour but the notification messages appear to be wrong to me.

Title: {article title}, changed by {author}, new state: {stage}

These messages are generated by the transitions. The problem with that can be seen with the default basic workflow which only has one stage. So when you do any of the transitions you get the same message which isn't very helpful.

#### Published Transition
Title: {article title}, changed by {author}, new state: Basic Stage

#### Un-Published Transition
Title: {article title}, changed by {author}, new state: Basic Stage

#### Trashed Transition
Title: {article title}, changed by {author}, new state: Basic Stage

@bembelimen @chmst can you take a look at this please.

**Comment by chmst** [comment]
Please test #35775
