### ISSUE TITLE
[3.10] - Subform Fields not sortable

### ISSUE THREAD

**Issue by travisrisner** [joomla/joomla-cms#35696]
### Steps to reproduce the issue

- Create new subform field with layout of either repeatable or repeateable-table
- Create new entry, add 2 items to the subform and save
- Use the icon to change the order of the fields, save again

### Expected result

The item would be saved with the ordering set by the reordering process.

### Actual result

The subform values seem to retain an order relative to their ID and the ID is not changed in the reordering process?

**Comment by Fedik** [comment]
Please tell more detail.

Where do you use the field, and how do you store it?

Such thing may happen if you store the field value in mysql `json` column type.

**Comment by travisrisner** [comment]
Ah yes, that's it! Completely related to the columns being of type json in mysql. Is there a recommended column type for this data?

**Comment by Fedik** [comment]
you can use json, there nothing bad with it.
just reindex the field value before save, then all be good, kind of:
```php
$subformValues = array_values($data['subformField']);
```
