### ISSUE TITLE
Custom user field of Media type not displayed

### ISSUE THREAD

**Issue by oorzaak** [joomla/joomla-cms#35690]
### Steps to reproduce the issue
In Users > Fields, create a custom field of the Media type. 

Login to the front end and add an image to your user profile, using this custom field.

Note that the image is displayed perfectly while you are in edit mode.

Save this change and view your profile page.

### Expected result
I expect to see the image in my profile. This used to work in Joomla 3, e.g. for adding an Avatar.

### Actual result
When viewing the profile, only the field label for the image field is displayed; there is no html for the image in the page source.

### System information (as much as possible)
Joomla 4.0.3, php 7.4.23

### Additional comments
I double- and triple checked all settings to exclude, for example, ACL settings hiding the field.
Also, in the same site I checked the output with a custom user field of the Text type; this worked as expected.

**Comment by drmenzelit** [comment]
Confirmed

**Comment by drmenzelit** [comment]
Checked today with Joomla 4.0.5 and the problem is gone. @oorzaak can you please check?

**Comment by drmenzelit** [comment]
It seems that PR #35685 solved the problem here.
