### ISSUE TITLE
'show_search_form' param does not exist in com_finder

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#35692]
### Steps to reproduce the issue
Check the file: _components/com_finder/tmpl/search/default.php_

There is that code:
```
<?php if ($this->params->get('show_search_form', 1)) : ?>
      <div id="search-form" class="com-finder__form">
	      <?php echo $this->loadTemplate('form'); ?>
      </div>
<?php endif; ?>
```
Though a param with the name `show_search_form` does not exist in _com_finder_.
If you are familiar with grep search, you can search the entire Joomla installation, to confirm that.

### Expected result
To exist a param with that name in the component's config xml or in the menu item xml

### Actual result
Not found

### System information (as much as possible)
Joomla 4.0.3

**Comment by brianteeman** [comment]
even joomla 3 has this code and doesnt have a parameter

**Comment by sakiss** [comment]
Shouldn't get fixed, though?

**Comment by brianteeman** [comment]
of course it should

**Comment by brianteeman** [comment]
please test #35967

**Comment by richard67** [comment]
Closing as having a pull request. Please test #35967 . Thanks in advance.
