### ISSUE TITLE
[4.0] Side menu doesn't function

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#35708]
### Steps to reproduce the issue
pull latest 4.0-dev
go to admin attempt to click on any menu item in the side panel besides "dashboard"

### Expected result
menu expands

### Actual result
nothing happens.

### Additional comments
Seems the same thing is happening in system->database.  Those links don't work properly either.

**Comment by jwaisner** [comment]
I am not able to replicate as of a72b834b commit.

![image](https://user-images.githubusercontent.com/12568201/135568798-20878802-5e0c-463a-9895-f4b565004e81.png)

![image](https://user-images.githubusercontent.com/12568201/135568935-33e5a9fa-59e0-443c-a6b7-bde1ffc4e29d.png)


This is on a clean install on a localhost.

**Comment by brianteeman** [comment]
As you have shown elsewhere that your local branch is not building correctly then its obvious that you need to fix that before reporting any errors

**Comment by N6REJ** [comment]
since @jwaisner can't replicate it, I'll close this till the other issue is resolved.
