### ISSUE TITLE
[4.0] Template user.css not loaded as last

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#35706]
### Steps to reproduce the issue

- Create user.css in template - in templates/cassiopeia/css/user.css
- Load some CSS in some extension, example:

`HTMLHelper::_('stylesheet', 'media/com_phocacart/css/main.css', array('version' => 'auto'));`

### Expected result

User.css will be loaded after component CSS (main.css)

### Actual result

User.css is loaded before component CSS (main.css)

![img](https://i.imgur.com/3g3rLoD.png)

### System information (as much as possible)

Joomla 4.0.2

**Comment by Fedik** [comment]
Please try WebAsset instead https://docs.joomla.org/J4.x:Web_Assets
All call of `HTMLHelper::_('stylesheet or script', ...` still works, but they attached last.

**Comment by PhocaCz** [comment]
Hi, thank you for the info.

```
$wa = Factory::getApplication()->getDocument()->getWebAssetManager();
$wa->registerAndUseStyle('com_phocacart', 'media/com_phocacart/css/main.css');
```

This did the trick. But the question is how many developers will use this latest method if the standard methods still work.

**Comment by Fedik** [comment]
Many of them, that a question of the time.
We cannot easily drop the old way. For j4.
