### ISSUE TITLE
[4.0] Atum lacks definition for buttons Warning, Light, Dark (and Link)

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#35702]
Hi,

it looks like Atum lacks definition for buttons Warning, Light, Dark (and Link) in

administrator/templates/atum/scss/blocks/_toolbar.scss

![img](https://i.imgur.com/RZTbfKs.png)

PS: Yes, for my personal use it's not a problem to add it to my own CSS, but it would be good to keep a consistent style for the whole CMS.

Thank you, Jan

**Comment by brianteeman** [comment]
that file is just for changes to the bootstrap defaults.

**Comment by arishmaurya** [comment]
hey , I want to work on this . is this issue is still open ?

**Comment by Quy** [comment]
Closing for reason stated.
