### ISSUE TITLE
[4.0] multiple select with fancy layout breaks showon

### ISSUE THREAD

**Issue by stell** [joomla/joomla-cms#35718]
### Steps to reproduce the issue

        <field name="myfield1" default="1" type="list" label="Testfield 1" layout="joomla.form.field.list-fancy-select">
            <option value="1">Value1</option>
            <option value="2">Value2</option>
            <option value="3">Value3</option>
        </field>
        <field name="myfield2" type="number" default="0" label="Testfield 2" filter="unset" min="0" showon="myfield1:2" />

### Expected result

myfield2 should display when Value2 is selected.

### Actual result

showon is not working.

### System information (as much as possible)
Joomla 4.0.2 (works in J3)

### Additional comments
Works when field is a non fancy non multiselect list.

**Comment by Fedik** [comment]
same as here #35486
it not because the layout, but because `multiple`

**Comment by Fedik** [comment]
Closed because it already have an issue opened
