### ISSUE TITLE
[J4] Not working filter files in typefield filelist

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#35717]
```
<field
	type="filelist"
	filter="^(theme_)[A-Za-z0-9]*(.css)"
name="stylefiles"
hide_default="true"
hide_none="true"
multiple="false"
default="default.css"
directory="modules/mod_select/css/"
exclude=""
stripext=""
label="Style">
</field>
```
Not working filter files
`filter="^(theme_)[A-Za-z0-9]*(.css)"`
`filter="css"`
`filter="^(?!(theme_*)|(default.css)|(test.css)).*.css"`
`filter="^(?!(forAdmin.css)|(test.css)).*.css"`
`filter="^(?!forAdmin.css).*.css"`

Display all files in directory

**Comment by Fedik** [comment]
Please check for correct attribute name https://docs.joomla.org/Filelist_form_field_type

**Comment by richard67** [comment]
The attribute is named fileFilter in Joomla 4, as stated in the docs. Closing as expected behavior.

**Comment by korenevskiy** [comment]
@richard67  
That's... wow. 

We could, for old compatibility, enable support for both attributes.
