### ISSUE TITLE
[4.0] Cassiopeia - Collapsible Dropdown menu overflows out of the browser

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#35713]
### Steps to reproduce the issue

- Create menu items with submenu items
- Set Layout "Collapsible Dropdown" or "Dropdown" in Main Menu module
- Click to expand the submenu item

### Expected result

Submenu will fit the browser window

### Actual result

Submenu menu overflows out of the browser
![img](https://i.imgur.com/hWU9lAW.png)

### System information (as much as possible)

Joomla 4.0.2

**Comment by ChristineWk** [comment]
Hi Jan,

Where can we see these overflows? 
https://cassiopeia.joomla.com/help/menu-module

Edit: Now I saw your screenshot under Github (not on Issue tracker).

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35713">issues.joomla.org/tracker/joomla-cms/35713</a>.</sub>

**Comment by ChristineWk** [comment]
I think the reason is how many menus you have on top.

**Comment by brianteeman** [comment]
it still should not happen

**Comment by PhocaCz** [comment]
Some dropdown methods can detect the edge of the page and move the dropdown to the left.

The Metismenu method, which is used in the Cassiopeia template, uses absolute positioning for displaying the submenu, so you just need to assign the "right" property to the submenu (e.g. right: 0;) and the result can look like this:

![img](https://i.imgur.com/5vk2tD2.gif)

Unfortunately, this is statically set in CSS, I don't know the Metismenu library, so it's hard to say if this could be set (recalculated) dynamically according to the menu position.

**Comment by brianteeman** [comment]
metismenu can definitely do this see the documentation and exaamples https://onokumus.com/metismenujs/mm-horizontal.html

**Comment by dgrammatiko** [comment]
This is already fixed with https://github.com/joomla/joomla-cms/pull/35518

**Comment by alikon** [comment]
closing as #35518 has been merged
