### ISSUE TITLE
[4.0] Cassiopeia - Description = Tagline - add a description to the Tagline parameter

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#35719]
### Is your feature request related to a problem? Please describe.

I couldn't find the page description for a long time because I would never have thought that in Joomla 4 it's now called Tagline.

### Describe the solution you'd like

It would be great to have a description for the Tagline parameter, just like there was a description for the Description parameter in Joomla 3

![img](https://i.imgur.com/0aXaFEG.png)

Having "Optional text to show as a subheading" clearly says what the parameter does

### Additional context

Thank you, Jan

**Comment by brianteeman** [comment]
please submit a  pull request

**Comment by PhocaCz** [comment]
https://github.com/joomla/joomla-cms/pull/35720

**Comment by alikon** [comment]
closing as we have a pr #35720
