### ISSUE TITLE
remove input size?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#35711]
> size
Valid for email, password, tel, url and text input types only. Specifies how much of the input is shown. Basically creates same result as setting CSS width property with a few specialities. The actual unit of the value depends on the input type. For password and text, it is a number of characters (or em units) with a default value of 20, and for others, it is pixels. **CSS width takes precedence over size attribute.**

As css takes precedence over any size attribute it has been suggested that we remove all size="xx" from the xml form definitions.

Personally I would keep it for all frontend inputs as there may not be any css in the site template for this but I would remove all the admin input sizes as they are redundant.

@chmst @bembelimen

**Comment by chmst** [comment]
I also think that removing all size="xx" in backend only is a good solution. ``

**Comment by brianteeman** [comment]
PR created #35742
