### ISSUE TITLE
Smart Search Module Minfication

### ISSUE THREAD

**Issue by DaveOzric** [joomla/joomla-cms#35716]
Using a template with Minification turned on the smart search module auto-suggest does not work. Posted in Gridbox forum.

https://support.balbooa.com/forum/gridbox/13881-smart-search-module#65459

The developer says it's caused by one-line comments.

### Steps to reproduce the issue
Enable minifcation in Gridbox template, type in smart search module input field.

### Expected result
Auto-suggest should populate suggestions

### Actual result
No auto-suggest box opens on a page with HTML modification. This works on the actual search results page where the page is not minified.

### System information (as much as possible)
Joomla! 3.10.2 
PHP Version 7.4.24
Gridbox template

### Additional comments
This module will not work with enabled minimization since their using 1-line comments in the code.
![screen shot 2021-10-01 at 14 14 07](https://issues.joomla.org/uploads/1/f71d07d9b4b49c048b2986daa31619bb.jpg)

**Comment by brianteeman** [comment]
Sounds very odd but you can remove the comments yourself by creating a template override for the module

**Comment by dgrammatiko** [comment]
The comments are totally valid. The software that you are using just doesn’t handle those correctly. Personally I wouldn’t change anything in the core and I would created a ticket on the other software

**Comment by DaveOzric** [comment]
I'll let them know. Is there a way to test this with the core Joomla template? Does Joomla 4 have minifcation?

**Comment by dgrammatiko** [comment]
Joomla 4 doesn’t use inline scripts almost nowhere…

**Comment by DaveOzric** [comment]
So this won't be an issue in Joomla 4 when using Gridbox? If that is the case it's a moot point.

**Comment by dgrammatiko** [comment]
Well, their code is broken, so you might not have a problem with core Joomla but most probably you will with some 3rd party extensions.

Also, concatenating scripts is NOT a best practice for many years, so the whole point here is kinda seriously outdated and baggy

**Comment by DaveOzric** [comment]
Thanks for your help.
