### ISSUE TITLE
[4.1-dev] 0 Access to undeclared static property: Joomla\Module\Quickicon\Administrator\Helper\QuickIconHelper::$buttons

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#35727]
### Steps to reproduce the issue

Since update to: 4.1: After Login and/or Klick on: Home Dashboard (part of view):

![screen shot 2021-10-02 at 13 57 36](https://issues.joomla.org/uploads/1/eaed4ecfcc9c1e8e87fb10426d4722ff.jpg)

An error has occurred.
0 Access to undeclared static property: Joomla\Module\Quickicon\Administrator\Helper\QuickIconHelper::$buttons 

Click on:  Global Configuration: View is OK.

### Actual result
see above.

### System information (as much as possible)
System: installed: 4.1.0-dev
Server: https://update.joomla.org/core/nightlies/next_minor_list.xml

Joomla CMS 
Joomla! 4 Content Management System. 
Site 
File 
No Problems 
Database: 4.0.3-2021-09-05 
‎Manifest: 4.1.0-dev 

### Additional comments
Can anyone confirm that, or is it just me?

**Comment by PhilETaylor** [comment]
please enable debug mode and error_reporting to development and then report the stack trace shown when the error occurs.

**Comment by ChristineWk** [comment]
@PhilETaylor 
Tks. I hope, it helps. If not successful or other unknown reason, then I will go back to Version 4.0.3

![screen shot 2021-10-03 at 15 46 26](https://issues.joomla.org/uploads/1/da58a12dfde1b26d261443f68d72c430.jpg)

![screen shot 2021-10-03 at 15 46 40](https://issues.joomla.org/uploads/1/e70556152f37f4e4164c0acadaae5140.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35727">issues.joomla.org/tracker/joomla-cms/35727</a>.</sub>

**Comment by PhilETaylor** [comment]
And shall I assume you are on some very high PHP 8 version? Which version exactly?

**Comment by ChristineWk** [comment]
PHP 8 not yet :-)
> 

Database Type | mysql
-- | --
5.7.33-log
latin1_swedish_ci
utf8mb4_general_ci
None
Yes
7.4.21
Apache
cgi-fcgi
Joomla! 4.1.0-dev Development [ Kuamini ] 28-September-2021 			18:25 GMT

**Comment by ghazal** [comment]
Confirming this error.
PHP 8.0.10
MariaDB 10.4.21
Joomla 4.1.0-dev (today's NightlyBuild ie 10/4)
Only in the Home Dashboard.

**Comment by ghazal** [comment]
I guess I found where the error lies:
/administrator/modules/mod_quickicon/src/Helper/QuickIconHelper.php
Around show_tags (new?) feature.

I guess it should not be:
				`//self::$buttons[$key][] = $tmp;`
but:
				`$this->buttons[$key][] = $tmp;`

**Comment by PhilETaylor** [comment]
Looking at the file https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/modules/mod_quickicon/src/Helper/QuickIconHelper.php I do not see any `self::$buttons[$key][] = $tmp;`

**Comment by ghazal** [comment]
Its a 4.1 dev pb

**Comment by PhilETaylor** [comment]
ah that would do it yes

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/32223 related

**Comment by PhilETaylor** [comment]
Please test https://github.com/joomla/joomla-cms/pull/35754
