### ISSUE TITLE
Subform duplicated when Saved if subform had (child) subform too

### ISSUE THREAD

**Issue by DelPoint** [joomla/joomla-cms#35721]
**_Note_**: the problem can be reproduced only if a template has subforms in its **templateDetails.xml**, and you try to modify/save template parameters. So, I've provided a very minimalistic template (no front-end fancyness) to demonstrate the issue. Use that for testing.

### Steps to reproduce the issue
1. Install vanilla J! 4.03 (stable) w/o demo data.
2. Install template **test** attached: [test.zip](https://github.com/joomla/joomla-cms/files/7270766/test.zip)
3. Go to **System** -> **Site Template Styles** -> **test - Default** style to change template's parameters.
4. Switch to **Advanced** tab/panel.
5. Add a (parent) subform by clicking the green '**+**' (plus) button next to the parameter **I have Problems**.
6. Add a (child) subform by clicking the green '**+**' button next to the parameter **Child Subform**
7. You should see ONE (parent) subform with ONE (child) subform on your screen - see expected result.
8. Now click on the **Save** button to save the template parameters.
9. After saved, and page refreshed, you will see that the parent subform is duplicated w/o a (child) subform, and also the subform w/ subform (created by the user) is on the screen - see actual result below.

### Expected result
![Expected Result](https://user-images.githubusercontent.com/1571585/135700808-ef20a188-d740-4b35-b9cb-783518497e56.png)

### Actual result
![Actual Result](https://user-images.githubusercontent.com/1571585/135701039-10b01900-459b-405f-8ab1-b03049604a4b.png)

### System information (as much as possible)
Apche 2.4.46
PHP 8.03
MySQL 5.6.17
Joomla! 4.03

### Additional comments
1. Duplicated (parent) subform also saved into the MySQL database.
2. If we change the user actions a bit: 
  - add the 1st (parent) subform AND click **Save** BEFORE adding the 2nd (child) subform
  - THEN now add the child subform
  - AND now click **Save** again -> **no duplicated subforms will be created**
That suggests maybe this is an error caused by **Save**: duplicated entries got pushed into the DB, and after page refreshed, DB sent back 2 subforms. Didn't have time for more debugging though.
3. I also noticed that J! built-in field editor doesn't produce this kind of error. So, I've seen the problem only around the editing of template parameters.
4. And a final observation: duplicated subform is always inserted BEFORE the subform created by the user, and never after it.

**Comment by nozaro33** [comment]
I've also replicated this problem with Joomla 4.0.3, used inside a config.xml

**Comment by Fedik** [comment]
I can confirm,
it worked in past somehow :)

**Comment by Fedik** [comment]
please test #35726

**Comment by DelPoint** [comment]
Hi Fedik,

I can confirm that #35726 solves the duplication of subforms when saved, but it breaks **showon** functionality now.

Add a second field to the (child) subform with **showon** condition, which refers to the 1st field of this (child) subform. Condition: **showon="first_field!:"** (ie. if 1st field empty, 2nd field shouldn't appear).
Using your commit/modifications, as soon as I've added the 2nd (child) subform, ALL fields appeared in this form, ignoring the **showon** condition of the 2nd field.
Attached a modified **test_2** template, where I've added a 2nd field into the (child) subform with **showon** condition.
Test your commit with this XML now, you'll see what I've described above.
[test_2.zip](https://github.com/joomla/joomla-cms/files/7272306/test_2.zip)

Also noticed: if a field with **showon** condition displayed while it shouldn't, and this field is a radio button group (the fancy one), then these buttons are not clickable. I guess, this is a side effect of JS implementation of "showon".
