### ISSUE TITLE
[4.0] Reorder by drag and drop the featured articles, do not save the correct order in the administrator area

### ISSUE THREAD

**Issue by carlitorweb** [joomla/joomla-cms#35728]
### Steps to reproduce the issue

2. Create 2 categories
3. Create 1 article inside each category.
4. Put as **Featured** both articles
5. **In the administrator side**, go to the **Featured Articles** view, and reorder the articles using the drag and drop characteristic.
6. Refresh **the administrator Featured Articles view**

### Expected result
Both articles keep the order you establish

### Actual result
The articles did not respect the order you established, and back to the same initial order they had.

### System information (as much as possible)
A fresh J4.0.3 site in: https://launch.joomla.org/

### Additional comments
If you do the same, but having both articles in the same category, all work as expected.

**Comment by brianteeman** [comment]
In the menu item you need to set Category to no-order and Articles to featured-order

![image](https://user-images.githubusercontent.com/1296369/135745391-30b0ef32-96ce-4d49-ad12-ee8529342901.png)

**Comment by carlitorweb** [comment]
> In the menu item you need to set Category to no-order and Articles to featured-order
> 
> ![image](https://user-images.githubusercontent.com/1296369/135745391-30b0ef32-96ce-4d49-ad12-ee8529342901.png)

But this is also needed for the administrator area?  What I reporting here is only inside the administrator area, not in the frontend where that menu item should have effect.

Anyway, I tested and after create a menu item in a fresh 4.0.3, who have this options you mention, do not cause any change.

**Comment by brianteeman** [comment]
Sorry I misunderstood your original post

**Comment by carlitorweb** [comment]
@brianteeman is okay, maybe I did not explain myself as good as I though. I trying find the problem, but so far the method `saveOrderAjax(`) and `saveorder($pks = array(), $order = null)` look good. Seen is some kind of js problem...somehow do not let the `table->store()`, save the correct values in the `frontpage table` when the articles come from a different category. 
But then, all work okay when come from the same category and that make the js assumption invalid. 

In all my sites, the users use this view, so is kind of a critical problem for me.

**Comment by dgrammatiko** [comment]
@carlitorweb can you test removing the `data-draggable-group="<?php echo $item->catid; ?>"` from https://github.com/joomla/joomla-cms/blob/4288fddb43d7b3afde8fa6c45ffb6e0783ef758a/administrator/components/com_content/tmpl/featured/default.php#L197

**Comment by carlitorweb** [comment]
> @carlitorweb can you test removing the `data-draggable-group="<?php echo $item->catid; ?>"` from
> 
> https://github.com/joomla/joomla-cms/blob/4288fddb43d7b3afde8fa6c45ffb6e0783ef758a/administrator/components/com_content/tmpl/featured/default.php#L197

**It worked like a charm!** You save my day, thank you. Do you think this change could cause any break in other place?  I do not think can cause any problem, but just for be sure

**Comment by dgrammatiko** [comment]
No, that piece of code shouldn’t be there in that view. How do I know? I wrote the first version of drag and drop 😄

**Comment by dgrammatiko** [comment]
@carlitorweb if you can mark your successful test in the issues.joomla.org the fix would be available in one of the next versions. The PR is https://github.com/joomla/joomla-cms/pull/35741

**Comment by richard67** [comment]
Closing as having a pull request. Please test #35741 . Thanks in advance.
