### ISSUE TITLE
Class Joomla\Input\Input is not respecting the source data

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#35746]
### Steps to reproduce the issue

Checking the `Joomla\Input\Input` class, the constructor is defined in this way:

```php
	public function __construct($source = null, array $options = [])
	{
		$this->data    = empty($source) ? $_REQUEST : $source;
		$this->filter  = $options['filter'] ?? new Filter\InputFilter;
		$this->options = $options;
	}
```

As a consequence, a call to `new Input([])` generates an `Input` initialized with the `$_REQUEST`, instead of generating an `Input` initialized with `[]`.

According to the doc:

```php
@param   array  $source   Optional source data. If omitted, a copy of the server variable '_REQUEST' is used.
```

Since the parameter `$source` is not committed, and it has the value `[]`, the object should be initialized with `[]`.

### Expected result

`new Input([])` initialized with `[]`

### Actual result

`new Input([])` generates an object initialized with a different source.

### System information (as much as possible)

Joomla 4.

### Additional comments

As a workaround, to create an empty `Input`, the developer could call a `new Input(['no-input' => 'fake-input'])`...

**Comment by richard67** [comment]
Would it be a solution to replace the `empty($source)`by `!isset($source)`?

**Comment by richard67** [comment]
Or better with positive logic and simplified using null coalescing: `$this->data = $source ?? $_REQUEST;`

**Comment by anibalsanchez** [comment]
Yes, it would be better with the Null Coalescing Operator.

**Comment by anibalsanchez** [comment]
@richard67 Do you submit the PR? Or, do I submit the change?

**Comment by richard67** [comment]
@anibalsanchez If you want, do it. It could take some time until I can do it, so I'd be happy if you can be faster. Do you have any idea about testing instructions, how we can test that nothing is broken?

**Comment by joomdonation** [comment]
Look like the issue was sorted already. The current code is:

$this->data    = $source ?? $_REQUEST;

It is already addressed the issue reported here, so I'm closing this issue.
