### ISSUE TITLE
misuse of aria-label in the pagnation

### ISSUE THREAD

**Issue by kapetanov** [joomla/joomla-cms#35758]
hi, 

the pagnation in the frontend template (cassiopaia) has an misuse of  the aria-label. If you use aria-label, aria-labelledby, or aria-describedby with any other elements (like div, span, p, blockquote, or strong etc.), they generally won’t work across all browser/assistive technology combinations.

https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/pagination/link.php (line 94)

**Comment by chmst** [comment]
@kapetanov it is not cassiopeia but the lyout in the core as you correctly found out. Thanks for the hint.

**Comment by kapetanov** [comment]
yes, its the core. the same issue is in the backend pagnation. i made an override, until the fix is coming.

**Comment by brianteeman** [comment]
why not contribute your fix

**Comment by kapetanov** [comment]
ok, here is my workaround.

replace line 94 in

https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/pagination/link.php

`<span aria-current="true" aria-label="<?php echo $aria; ?>" class="page-link"><?php echo $display; ?></span>`

with

`<span aria-current="true" class="hidden"><?php echo $aria; ?></span><span aria-hidden="true" class="page-link"><?php echo $display; ?></span>`

i made two span tags. the first is hidden for display users and readable for assistive technology. the second span ist hidden for assistive technology and readable for display users.
