### ISSUE TITLE
Joomla 4.0.3 installation fails after Data Base configuration

### ISSUE THREAD

**Issue by jernesten** [joomla/joomla-cms#35751]
### Steps to reproduce the issue
Install Joomla 4.0.3 in a LEMP self hosted server

### Expected result
Install joomla

### Actual result
Joomla installation returns to the beginning after the database configuration step

### System information (as much as possible)
LEMP self hosted server in an Ubuntu 20.04.3 LTS

### Additional comments
No information is given after the error
Data base is written after the database configuration step

**Comment by richard67** [comment]
You don’t see any error message when scrolling to the top after that has happened?

**Comment by carlitorweb** [comment]
I running Ubuntu LTS in a LEMP environment, and already installed several J4, even unzip backups for upgrade sites etc. So far I did not found any problem in the installation part.

Will be good if you can provide a error information, maybe is relate with your custom environment.

**Comment by Eggeriley** [comment]
I am having the same.

Here is the error: 

> GET https://recipes.accessipd.com/installation/index.php?view=remove&layout=default 403 (Forbidden)
> Joomla.goToPage @ /installation/templa…af49c070f4d2347e:41
> onError @ /installation/templa…f49c070f4d2347e:208
> o.onreadystatechange @ /media/system/js/cor…c3f47a6e9b4100832:1
> XMLHttpRequest.send (async)
> e.request @ /media/system/js/cor…c3f47a6e9b4100832:1
> Joomla.install @ /installation/templa…f49c070f4d2347e:169
> onSuccess @ /installation/templa…f49c070f4d2347e:204
> o.onreadystatechange @ /media/system/js/cor…c3f47a6e9b4100832:1
> DevTools failed to load source map: Could not load content for chrome-extension://liecbddmkiiihnedobmlmillhodjkdmb/js/intercom-link-expand-loader.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME
> DevTools failed to load source map: Could not load content for chrome-extension://liecbddmkiiihnedobmlmillhodjkdmb/js/content.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

**Comment by wmienis** [comment]
I Have the same issue.
After entering all fields for the website, the database and al the right credentials the installation comes up with the Joomla Logo and looks as if it is installing.
After a while (1 min) the startpage form the installation is loaded again. No error message anywhere.
The database is created.
If I rename the install folder to check if anything is happend it gives the message no config files are available when url us loaded.
Cannot find right logfiles to check install. Were should I find those?
Thanks in advance.

**Comment by Hackwar** [comment]
We didn't get any feedback back from the original poster and the other two people reporting here seem to have differing issues. @wmienis I would expect it to timeout when writing the configuration.php. @Eggeriley are you sure the install package was properly uploaded?

Since the original reporter didn't get back, I'm closing this one.
