### ISSUE TITLE
menu link image not showing

### ISSUE THREAD

**Issue by greenlizzard24** [joomla/joomla-cms#35779]
### Steps to reproduce the issue
created a menu item, in the tab for link type, I selected a png image, the image displays in the box but does not display in the menu item. 

### Expected result
menu link with an image next to it

### Actual result
Nothing, blank

### System information (as much as possible)
Joomla 4.0.3
PHP 7.4.24
Database Type	mysql
Database Version	10.3.31-MariaDB-log-cll-lve

### Additional comments
I can select the image but the link is showing a rather strange format, where it should be images/myimage.png instead it is showing images/myimage.png#joomlaimage://local-images/myimage.png?width=41&height=17

**Comment by dgrammatiko** [comment]
If anyone wants to fix this one probably they might be interested to also fix all the other places in the core that images are broken. Here's a good list: https://github.com/ttc-freebies/plugin-responsive-images/tree/4.0.0/src/plugins/system/responsiveplgoverrides/html

**Comment by dgrammatiko** [comment]
@greenlizzard24 please test https://github.com/joomla/joomla-cms/pull/35780

**Comment by chmst** [comment]
Closing as there is a PR. 

But - I see all images .png or .jpg as expected. So do cannot confirm the issue. @dgrammatiko what am I missing?

**Comment by dgrammatiko** [comment]
@chmst check my PR

**Comment by chmst** [comment]
I see and I am a big fan of HtmlHelper for images, so looks really good for me. 
But I got the images also before your patch. So do not understand what was the issue.

**Comment by dgrammatiko** [comment]
> But I got the images also before your patch. So do not understand what was the issue.

Maybe the particular issue here is due to some override or something else custom (module, template, etc). But it was a good reminder that images needed some attention...
