### ISSUE TITLE
[3.x] Upgrade override information

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#35770]
Upgrading a site today to j4 and everything went perfectly - woohoo

The one bit I struggled with was the site template - no surprise there EXCEPT the site template actually worked perfectly it was the overrides of core modules and components where it fell down. Something I had completely forgotten I had created.

Perhaps other people will have the same problem and we can save some time for them. Either by checking if there are any in the upgrade check and informing you OR something that @laoneo did with dpcalendar and renamed the html override folder so that the files were still present but not loaded.

**Comment by zero-24** [comment]
Hmm I'm not sure whether renaming the html folder is a wise choice for the core as we even decided to intentionally break sites and not disable for example critical extensions on upgrade.

What kind of information do you have in mind about the pre Upgrade checker?

I have not checked the details of the new Override manager but couldn't that be triggered somehow to show a message within J4? Maybe something like "we found overrides that have not been checked yet for J4 compatibility"? Given that this is the place starting from 4.0 for overrides anyway right?

**Comment by brianteeman** [comment]
using the override manager would be the perfect solution. even a very simple article override from j3 will break a site in j4
