### ISSUE TITLE
[4.0] installing a module produces error Undefined constant "JPATH_" 

### ISSUE THREAD

**Issue by gorgonz** [joomla/joomla-cms#35778]
### Steps to reproduce the issue
use a  joomla v4.03, that is installed on a sever (not local!), i used php 8
goto the backend and install the attached minimum demo module

### Expected result
it gets installed

### Actual result
getting the error: Undefined constant "JPATH_" 

### System information (as much as possible)
i used a fresh j4.0.3

### Additional comments
i didn't see it with a local installation. For better analysis i will also add an attachment of the debug info
[mod_demo-min.zip](https://github.com/joomla/joomla-cms/files/7302545/mod_demo-min.zip)
![error-undefined-constant-jpath](https://user-images.githubusercontent.com/11473875/136375221-b79309ca-2252-4fb1-bb67-e1bd8bda5ac7.png)
Maybe, there is a wrong coding in my module, it is my first attempt to do so in Joomla 4 ;-)

**Comment by gorgonz** [comment]
forgot the debug log:

![error-undefined-constant-jpath-debug](https://user-images.githubusercontent.com/11473875/136377182-adece268-91a2-4856-9dc7-2af95ec4fbe4.png)

**Comment by joomdonation** [comment]
If I remember correctly, You need to add client attribute , like this https://github.com/joomla/joomla-cms/blob/4.0-dev/modules/mod_articles_categories/mod_articles_categories.xml#L2

**Comment by chmst** [comment]
And a namepace Path like this 
https://github.com/joomla/joomla-cms/blob/4.0-dev/modules/mod_articles_categories/mod_articles_categories.xml#L12

**Comment by chmst** [comment]
This issue is not a Joomla issue, so I close it here.  Better address for your question: https://joomla.stackexchange.com/questions is a better address for you.
