### ISSUE TITLE
[4.0] Bug - Subform of subform does not store values

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#35787]
### Steps to reproduce the issue
Use some part of the system which uses subform in subform.

A typical example
Item
___--> Attributes (subform)
______--> Options (subsubform)

![image](https://i.imgur.com/jpvbvZV.png)

But under specific conditions:

A) If you create attributes first and save the whole item and then create options and save whole item, then everything is OK

B) But if you create attributes and options together at once and store whole item, then values for options will be not stored*

* There is different behaviour in 4.0.2 and 4.0.3

4.0.2 - Subform values will be stored, Subsubform values are empty - not stored
4.0.3 - Subform values will be stored, another empty instance of Subform values will be additionaly created (without data) but such second instance includes right subsubform values.

In case:
a) there are not required fields - form will be stored but without data for options
b) there are required fields - form will be not stored because of missing required field

4.0.2:
![image](https://i.imgur.com/fgTBw0R.png)

4.0.3:
![image](https://i.imgur.com/0egcJjK.png)

### Expected result

Expected result should be the same like in **Joomla 3** where it was possible to create subform -> fill in the data, create subsubform -> fill in the data and store whole item = **all values are stored**.

### Actual result

Subsubform values are not stored in case, the values are added at the same time like subform values in 4.0.2. In 4.0.3 additional empty instance of subform will be created.

### System information (as much as possible)

Joomla 4.0.2
Joomla 4.0.3

This patch: https://github.com/joomla/joomla-cms/pull/35685 does not influence this problem.

### Additional comments

The problem in 4.0.3 is creating of another X instance

![img](https://i.imgur.com/QkYOOEx.png)

**Comment by Fedik** [comment]
It sounds similar to #35721, It is fixed in the 4.0-dev branch.
Please check if that works for you.

**Comment by PhocaCz** [comment]
Hi @Fedik 

testing now all possible combinations, and it looks like it works in 4.0.4 (#35726)

Thank you, Jan

**Comment by richard67** [comment]
Does it mean this issue can be closed because solved with #35726 ?

**Comment by PhocaCz** [comment]
Yes, solved, closed. Thank you.
