### ISSUE TITLE
[4.0] Articles and modules sub-head container disappears on narrow screens

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#35792]
### Steps to reproduce the issue
On a desktop, open an article (or a module) to edit it.
Narrow the width of the browser so the screen width is about 900px
See the sub-head menu:

![sub-head-container-visible](https://user-images.githubusercontent.com/36987494/136666702-7f46a077-e51a-429e-9e2d-fb729615c94a.jpg)

Click the 'Save' button (It's not necessary to change the article).

### Expected result
The article is saved but the sub-head menu should still be visible.

### Actual result
The sub-head container has disappeared:

![sub-head-container-not-visible](https://user-images.githubusercontent.com/36987494/136666753-95699268-e45a-4c76-bbde-4a0b7999c821.jpg)

In fact, if you narrow the screen to its minimum, the menu disappears without the 'save' option being applied first.

The only way to retrieve the menu is to pull the browser wider.

The same issue happens with a new article or module except that the sub-head container does not appear at all on narrower screens.

### System information (as much as possible)
J4.0.3 fresh install onn 08/10/2021

**Comment by chmst** [comment]
I cannot replicate this issue. I see that you have added a search module on your backend and removed all other backend status modules. Where did you get this search module for backend? 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35792">issues.joomla.org/tracker/joomla-cms/35792</a>.</sub>

**Comment by brianteeman** [comment]
I can replicate this and there are multiple open issues

**Comment by brianteeman** [comment]
example #35630

**Comment by richard67** [comment]
So it’s a duplicate report?

**Comment by Scrabble96** [comment]
I guess it is a kind of duplicate, but I posted this after searching for 'sub-head container' not 'fix button missing' and couldn't find anything similar. Has anyone opened a PR to fix it?

**Comment by brianteeman** [comment]
> Has anyone opened a PR to fix it?

No

**Comment by RickR2H** [comment]
Closing as having a pull request. Please test #35860<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35792">issues.joomla.org/tracker/joomla-cms/35792</a>.</sub>
