### ISSUE TITLE
Admin Template wont copy

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#35790]
### Steps to reproduce the issue
System >>> Templates ... Administrator Templates(link) ... Atum Details and Files(link) Click the copy button
Give it a name and copy

### Expected result
Copy of the Template should be created with new name should be created

### Actual result
An error has occurred.
    -1 Source folder not found 

### System information (as much as possible)
Wamp localhost

**Comment by brianteeman** [comment]
Already fixed see #35791

**Comment by Webdongle** [comment]
No wasn't already fixed.  The fix was created after this thread.

**Comment by alikon** [comment]
please test #35791
