### ISSUE TITLE
Atum backend template xml manifest: folder "Service" missing

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#35793]
While checking Atum template files and folders, I noticed that the folder administrator/templates/atum/Service listed in XML manifest file is missing.
AFAIK, no effect on the template display.
Same in J4 v.4.1 Alpha (as of 10/10's nightly build).
PHP 8.0.10

**Comment by brianteeman** [comment]
see #35791

**Comment by ghazal** [comment]
OK.
Tks.
