### ISSUE TITLE
Option "Image float" is missing in article tab "Images and links"

### ISSUE THREAD

**Issue by WoodyF4u** [joomla/joomla-cms#35809]
### Steps to reproduce the issue
Open an article in Joomla 4. Go to the tab "Images and links".
Look for the option "Float image" for the intro image and for the full article image.
This option was available in Joomla 3, but no longer in Joomla 4.
There is now only the option "Image Class", but that requires css knowledge from the user.

### Expected result
I expected the "Float image" option in Joomla 4 too.
Is there any reason why the option "Image float" is not included in Joomla 4?

### Actual result
There is no "Image float" available in Joomla 4.

### System information (as much as possible)
Joomla 4

### Additional comments
I don't think it is necessary to describe additional information.

**Comment by brianteeman** [comment]
please see https://github.com/joomla/joomla-cms/pull/31017 and referenced issues

**Comment by WoodyF4u** [comment]
Hi Brian,
Thank you for pointing me to that issue.
I just read issue #31017.
I just don't understand why Float image was abandoned at the time and that field was replaced by the Image class.
If the user doesn't have a bit of css knowledge, then setting up the layout of 'Images and links' doesn't get any easier in Joomla 4.

Can you explain why that choice was made in 2020?

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/30924#issuecomment-703607156

**Comment by WoodyF4u** [comment]
Ah thanks Brian,
I read further and saw that this has already started in 2017 in #17399.
It became clear that floating images no longer work well in modern templates.
A brief explanation of how to apply class and css in the help pages and in the documentation on joomla.org would be helpful for less experienced users.

**Comment by brianteeman** [comment]
its a wiki so feel free to update them

**Comment by richard67** [comment]
So can we close this issue as expected behaviour?

**Comment by WoodyF4u** [comment]
Yes, this one can be closed.
