### ISSUE TITLE
[4.0] Design issues in Menu items - Edit - Blog Layout

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#35816]
### Steps to reproduce the issue
Create a menu link, e.g. Menus - Main menu - New, select Article - Category Blog e.g. Navigate to Blog Layout, see screenshot:

![img](https://i.imgur.com/bebb5tX.png)

or this Twitter discussion:
https://twitter.com/sulpher/status/1448001157411090439

### Expected result
No design issues

### Actual result
Design issues (scattered elements floating off screen)

### System information (as much as possible)
Joomla 4.0.3

**Comment by chmst** [comment]
I don't use twitter. If someone wants to open issues or start discussions, the this repo is the right place.

**Comment by PhocaCz** [comment]
Hi Christiane, as written in the first post, you can see the problem here on the screenshot or see more screenshots on Twitter. But it's not important to see screenshots on Twitter, I think this one shown here clearly shows where the problem is.

**Comment by brianteeman** [comment]
the issue mentioned on twitter is not this

**Comment by PhocaCz** [comment]
> the issue mentioned on twitter is not this

Sorry I don't understand. The Twitter post was about destroyed design in Russian language, as seen on the other screenshots, this should be the same in German or default English language. Or did I get it wrong?

**Comment by brianteeman** [comment]
This is what it refers to

![image](https://user-images.githubusercontent.com/1296369/137218921-d51533fa-d436-4039-84af-3dad270dbfe3.png)

**Comment by PhocaCz** [comment]
Now I understand, so should be both design issues divided?

**Comment by brianteeman** [comment]
The issue you opened is a valid issue that needs to be resolved.

As far as I can tell the issue from twitter can not be easily resolved and has existed in every version of joomla or any cms for that matter. It really is never possible for every string to work exactly the same at every character count. There are things that can be done in the design such as wrapping the text at a set maximum width - which is what you see here - or the translators can actually look at their work in the CMS and adjust what they write to prevent this.

For me the issue complained about on twitter can only be resolved by the language translator. Anything else would be impossible. (but maybe someone can solve the impossible - I can only try to solve the improbable)

**Comment by PhocaCz** [comment]
Screenshots:

Design - Russian language
![img](https://pbs.twimg.com/media/FBhUG7HXoAMUr0j?format=jpg&name=small)

Design - German language
![img](https://pbs.twimg.com/media/FBm25bFXoAEL4Z5?format=png&name=small)

Design - English language
![img](https://pbs.twimg.com/media/FBm3yUCXoAM4yKZ?format=png&name=small)

Joomla 3:
![img](https://i.imgur.com/IrLnsdM.png)

**Comment by chmst** [comment]
There #34679 one issue is already written here. 

For the other inequal height of labels I have no solution at the moment. 


Quite another issue is the overlapping select listfields.

**Comment by chmst** [comment]
@PhocaCz so your issue is the valid issue :)

**Comment by ChristineWk** [comment]
Hi Jan,

Can't confirm that unfortunately. Joomla 4.0.3-dev, Joomla 4.1.0-dev Nightly.
Found this: #34145(relevant?) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35816">issues.joomla.org/tracker/joomla-cms/35816</a>.</sub>

**Comment by dmitriitux** [comment]
> The issue you opened is a valid issue that needs to be resolved.
> 
> As far as I can tell the issue from twitter can not be easily resolved and has existed in every version of joomla or any cms for that matter. It really is never possible for every string to work exactly the same at every character count. There are things that can be done in the design such as wrapping the text at a set maximum width - which is what you see here - or the translators can actually look at their work in the CMS and adjust what they write to prevent this.
> 
> For me the issue complained about on twitter can only be resolved by the language translator. Anything else would be impossible. (but maybe someone can solve the impossible - I can only try to solve the improbable)

In the administrative part, such grids have been created that really do not solve anything with them, they are simply built incorrectly, then it is wrong to adjust the language to the interface, it is necessary to make the interface taking into account different languages (which can be either short or long names). And to begin to reduce, then it will generally not become clear what it is. Here is what is shown in the screenshots, there is no way to shorten it at all (I'm talking about Russian).

**Comment by dmitriitux** [comment]
we make similar forms. But we break it in the same way as in joomla 3, but the columns are simple. For example, two vertical shapes, but two horizontal columns. It's just that this mesh is generally not usable and not made correctly.

**Comment by RickR2H** [comment]
Closing as having a pull request, Please test #35823<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35816">issues.joomla.org/tracker/joomla-cms/35816</a>.</sub>

**Comment by dmitriitux** [comment]
@RickR2H As far as I understand, you only corrected it in the blog, but as I understand it, there are such forms in other places. It's just that the concept of the grid is incorrect, it will still crumble. In my opinion, it is necessary to make vertical forms as before, but in columns. It will stop falling horizontally. There is also a lot of empty space just not used in this grid. But this is a global work, it is necessary to go through all the xml forms, make a grouping there in another fieldset, most likely, and rewrite the templates.

**Comment by RickR2H** [comment]
@dmitriitux Thank you for the feedback. Could you tell me on which places so I can take a look en create a far as the current grid will allow.

**Comment by dmitriitux** [comment]
@RickR2H ok, on the weekend I will try to view the entire standard interface of forms in joomla 4 in Russian and throw it here, where the grid is still going.

**Comment by chmst** [comment]
@ChristineWk you found one of these issues where the problem was already noticed :) 

I think you cannot replicate the issue because you have a bigger screen? If you make your window smaller, maybe you will see it.

**Comment by ChristineWk** [comment]
@chmst 
You are right. Tried again with (smaller) resized screen. Tks.
![screen shot 2021-10-14 at 20 58 57](https://issues.joomla.org/uploads/1/f4598b5b57a41d6f8fe0f76434388c38.jpg)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35816">issues.joomla.org/tracker/joomla-cms/35816</a>.</sub>
