### ISSUE TITLE
[4.0]  AdminModel.php getItem - huge backwards compatibility change between J4 Beta7 and J4 RC1

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#35811]
Hi, is there some documentation for the following backwards compatibility change:

**libraries/src/MVC/Model/AdminModel.php**

method: **public function getItem($pk = null)**

Joomla 4 Beta 7
```
// Check for a table object error.
if ($return === false && $table->getError())
{
    $this->setError($table->getError());

    return false;
}
```

Joomla 4 RC 1
```
// Check for a table object error.
if ($return === false)
{
    // If there was no underlying error, then the false means there simply was not a row in the db for this $pk.
    if (!$table->getError())
    {
        $this->setError(Text::_('JLIB_APPLICATION_ERROR_NOT_EXIST'));
    }
    else
    {
        $this->setError($table->getError());
    }

    return false;
}
```

This completely changes the behaviour of this method.

**Joomla 4 Beta 7 (Joomla 3)**
- when no item was found, empty object was returned

**Joomla 4 RC 1 (Joomla 4 Stable)**
- when no item is found, FALSE is returned (even there is no error)

The first question is: How can such huge backward compatibility change can be done between RC and Beta?
The second question is: How to distinguish between empty result and error now?

Or is this bug? Because I don't think you can deliberately change the method to return FALSE instead of TRUE.

Thank you, Jan

**Comment by richard67** [comment]
That change has been made with PR #33414 . @PhilETaylor Any thoughts?

**Comment by PhilETaylor** [comment]
All my thoughts are in the original PR #33414 and the reasons behind it, which were open to peer review, tested by two humans, and merged by a release leader. 

If an item doesnt exist, then returning an empty object is simply wrong anyway IMHO. 
You cannot checkout a non-existing item.
You cannot load a non existing item into a form for edit. Its simply wrong.

**Comment by richard67** [comment]
> All my thoughts are in the original PR #33414 and the reasons behind it, which were open to peer review, tested by two humans, and merged by a release leader - now the president of Open Source Matters...
> 
> If an item doesnt exist, then returning an empty object is simply wrong anyway IMHO. You cannot checkout a non-existing item. You cannot load a non existing item into a form for edit. Its simply wrong.

Makes all sense to me.

**Comment by PhilETaylor** [comment]
Also shows how crap the unit tests are if it never picked up such a "huge backwards compatibility change" LMAO.

**Comment by PhocaCz** [comment]
The **first problem** here is the backwards compatibility change.

This:
`if ($item = parent::getItem($pk)) {`

returns TRUE in J3, J4 Beta

but FALSE in J4 RC, J4 Stable

when there is no item, which is the complete opposite

Something like change

FROM:
if ($i > 0)
TO:
if ($i < 0)

The **second problem** here is to differentiate between error and empty result, **which are completely different outcomes**.

**Comment by PhocaCz** [comment]
This post is not trying to say what is right or wrong, but that between Beta and RC we can't change the answer of the method to the complete opposite.

The reason for the distinction between an error and an empty result in earlier versions was probably because the empty result defined an object with table columns to work on.

**Comment by PhocaCz** [comment]
>The false has been there for TWELVE YEARS!

In previous version, the FALSE was returned only when there was an error, not when there were no items:

```
// Check for a table object error.
if ($return === false && $table->getError())
{
    $this->setError($table->getError());

    return false;
}
```
These are completely two different FALSE statements

**J4 BETA**
```
// Check for a table object error.
if ($return === false && $table->getError())
{
    $this->setError($table->getError());

    return false;
}
```
* FALSE is returned only when there is error.

vs:

**J4 RC**
```
// Check for a table object error.
if ($return === false)
{
    // If there was no underlying error, then the false means there simply was not a row in the db for this $pk.
    if (!$table->getError())
    {
        $this->setError(Text::_('JLIB_APPLICATION_ERROR_NOT_EXIST'));
    }
    else
    {
        $this->setError($table->getError());
    }

    return false;
}
```
FALSE is returned always - when there is error or when there are no items.

**Comment by PhilETaylor** [comment]
> In previous version, the FALSE was returned only when there was an error, not when there were no items:

IMHO If you are calling a function called `getItem` and that function cannot get the item you are asking for from the database then **THAT IS AN ERROR**, because you were expecting that item to be in the database and its not!

**Comment by PhocaCz** [comment]
Again, I am not saying here what is right or not.

**Comment by richard67** [comment]
Regardless of what’s right and not: If we change it back we again have a b/c break, but this time in stable phase.

**Comment by PhocaCz** [comment]
> That is exactly what I would expect. I asked for an item, and the item does not exist so its an error.

This is completely wrong. Empty result is not an error. If you ask for items but system tells you, there are no items, it means, it says, there are 0 items but this is not an error.

Example: How many items are there?
- 10 ... Success (No error)
- 0 ... Success (No error)
- Error (some error happened during asking the database e.g.) ... Error

**Comment by PhilETaylor** [comment]
> This is completely wrong. Empty result is not an error. If you ask for items but system tells you, there are no items, it means, it says, there are 0 items but this is not an error.

Then we disagree. 

>  it means, it says, there are 0 items but this is not an error.

If you have asked for an item with a `$pk` of an integer, and the db doesnt contain that row with that primary key - that should never return an empty object in my opinion. 

> How many items are there?

This is not about `items` plural - the method changed in my PR is `getItem` (singular) and `checkout`. Other methods should be unchanged by my PR. Therefore I have no clue what on earth you are on about with asking items (plural) as this method is for loading a SINGLE ITEM from the db checking out A SINGLE ITEM. 

If you have issues with " ask for items but system tells you, there are no items," then that is unrelated to the PR quoted.

**Comment by PhocaCz** [comment]
>Please explain how on earth you expect the methods changed in my PR to tell you if there are 10 or 0 items?!??! Im so confused but you seem adamant that this broke, when the methods changed have nothing to do with plural items.

This was an example to explain that returning information about not items is not an error. General example to explain what is difference between error and returning empty results.

**Comment by PhocaCz** [comment]
If this has nothing to do with your PR, the question is who changed

FROM:
```
// Check for a table object error.
if ($return === false && $table->getError())
{
    $this->setError($table->getError());

    return false;
}
```

TO:

```
// Check for a table object error.
if ($return === false)
{
    // If there was no underlying error, then the false means there simply was not a row in the db for this $pk.
    if (!$table->getError())
    {
        $this->setError(Text::_('JLIB_APPLICATION_ERROR_NOT_EXIST'));
    }
    else
    {
        $this->setError($table->getError());
    }

    return false;
}
```

which is huge backwards compatibility change, because it changes the behavior of the function completely. 

For those who are not familiar with PHP:

- in first code, the FALSE is only returned when there is an error (empty results returns TRUE)
- in second code, the FALSE is returned even there is no error (empty results returns FALSE)

**Comment by PhilETaylor** [comment]
Revert "[4] When item doesn't exist, show specific message" #35813

**Comment by PhocaCz** [comment]
Phil, I'm not here to tell you what's right or wrong. My example with items has nothing to do with your PR, you are right, I just wanted to show that an error and no result are two different things.

Also, I'm not a core developer where this feature has worked for many years, so it's hard to explain why it split between an error and a empty result.

I'm just saying that it's very bad that in Beta this function returned TRUE with empty result and in RC it started to return FALSE under the same conditions.

**Comment by PhocaCz** [comment]
BTW I don't know why it worked that way, maybe because if no result was found, then there was an empty object that got filled with data, etc.

>In the absence of any official Joomla backward compatibility statement, relying on SEMVER alone, there is nothing wrong with a change of this (accidental) "magnitude" between a beta and a RC - its not ideal. but its not against the b/c rules.

It is not only change between Beta and RC but between many many years used in J3 till J4 Beta and J4 RC.

**Comment by PhocaCz** [comment]
```
/**
* Method to get a single record.
*
* @param   integer  $pk  The id of the primary key.
*
* @return  CMSObject|boolean  Object on success, false on failure.
*
* @since   1.6
*/
```

**@return  CMSObject|boolean  Object on success, false on failure.**

Then we are left with the philosophical question, what is success and what is error? 

In my opinion, success is also the fact that the function returns an empty result - an empty object. It's still not an error.

**Comment by richard67** [comment]
I agree with @PhilETaylor here. And reverting that change would be a b/c break now in stable phase. So I think this issue and PR #35813 should be closed. But I am only a small maintainer and I might be wrong so I don’t think I am the right one to decide anything.

**Comment by Fedik** [comment]
I agree this is b.c. break compared to Joomla 3, and should be documented https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4

Also I agree that changes were done is valid. Returning an object for empty result is confusing. No need to revert in my opinion.
Our fault that it was not documented.

However I see another issue: now it not easy to distinct "Model had error", and "Item not found".
Because "Item not found" now is an error 
https://github.com/joomla/joomla-cms/blob/3239d0d0a7ebaac628532c0ce09459870542c8e6/libraries/src/MVC/Model/AdminModel.php#L1083-L1087
I would just return `false` without setting an error. (Ideally throw NotFoundException, but it will be another b.c. break :) )

**Comment by PhocaCz** [comment]
> However I see another issue: now it not easy to distinct "Model had error", and "Item not found".

This is in fact, what I asked in first post:
> The second question is: How to distinguish between empty result and error now?
https://github.com/joomla/joomla-cms/issues/35811#issue-1023967814

That's basically what I've been saying all along. If we take it as an error that there is no record, how do we differentiate that from a real error.

We have in fact three statuses:

1) item will be loaded ... no error
2) item does not exist, will be not loaded ... still no error - we get an error-free response ... no error
3) item will be not loaded because of db error, etc. ... this is the true error.

If we join 2) and 3) then we cannot differentiate the 2) from real error. 

So in Joomla 4 Beta or Joomla 3, the purpose of this function was:
- separate only the real error and maybe
- build empty object if there is no data (this is very important for linked tables - for them, we need empty object when creating new item)

**Comment by PhocaCz** [comment]
> ￼You distinguish by reading the error message that is set! Simple!

I'm not sure it's any kind of fun? If not, how do I achieve it?

```
if ($item = parent::getItem($pk)) {
 ...
} else {
    // False returned
    // How to get human readable and translated error messages from message queue and transform them to condition?
    // Something like parsing $app->getMessageQueue(); and what next?
}

**Comment by Fedik** [comment]
> You distinguish by reading the error message that is set! Simple!

nope, 
Do you mean doing something like this?:
```php
$model->getError() === Text::_('JLIB_APPLICATION_ERROR_NOT_EXIST')
```
Sorry but it a :hankey: 

If we remove this part https://github.com/joomla/joomla-cms/blob/3239d0d0a7ebaac628532c0ce09459870542c8e6/libraries/src/MVC/Model/AdminModel.php#L1083-L1087

Then it can be like this:
```php
$item = $model->getItem($pk);

if ($model->getError())
{ 
  //... there an error
}
else if (!$item)
{
  // .. item not found
}
```

**Comment by Fedik** [comment]
hm, how is that?
I do not suggest to revert it, but change how "Not found Error" is set.

In my opinion "Not found" message should be set within a View instead of forced in Model.
Because Developer may want to show something specific like "Foobar not found", instead of generic one.

Kind of this:
```php
if ($return === false)
{
	if ($table->getError())
	{
		$this->setError($table->getError());
	}

	return false;
}
```
instead of https://github.com/joomla/joomla-cms/blob/3239d0d0a7ebaac628532c0ce09459870542c8e6/libraries/src/MVC/Model/AdminModel.php#L1081-L1094

But only problem, then also need check every core View to add "Not found" message :smile:

**Comment by Fedik** [comment]
Well, I have no idea.

**Comment by PhocaCz** [comment]
I don't know why we're talking about overengineering here. What exactly was wrong with the original version:

- when an item exists, an object with the item is returned
- if the item does not exist, an empty object is returned
- if an error occurs, false is returned (possibly initializing an error message)

Making a condition and splitting false or empty object can't be a problem or?

In the same or similar way as it is used in the core, example:
administrator/components/com_categories/src/Model/CategoryModel.php
```
if ($result = parent::getItem($pk))
		{
```
...

```
if (empty($result->id))
			{
```	
or
```
if ($result->id != null)
			{
```		
etc.

**Comment by PhocaCz** [comment]
I don't know why Joomla developers invented and used it for several years. It probably fulfilled some other function that I wrote about. There is no item, so create an empty object that will be used to initialize the new item (usually needed to join with other tables). The crucial thing is that with this design we can easily solve problems. We know how to easily separate the actual error and the empty result. And once again, the empty result is the success that is used to initialize a new entry for example.

We need to remember that this is a universal function that can serve in multiple places. For example, a place where we create a new item and ask if the item already exists. When an empty object is returned, we know that the item does not exist and we use that object to initialize the new item (in the form)

**Comment by PhocaCz** [comment]
Once again, I'm representing my opinion here and trying to point out that the original solution made some sense. I'm not saying I'm 100% right or that I don't understand why you modified the feature to work the way it does now. I'm just pointing out that it originally worked completely the opposite way and that maybe there was a reason for that. This isn't a fight about removing a PR, I just want to spark a discussion about whether we should modify it. The philosophical question of whether or not the empty result is a error or not should be answered by the core developers.

**Comment by Fedik** [comment]
Hey, stop fighting each other :smile: 
The issue is clear, we just need a solution (ideally without reverting)

**Comment by PhocaCz** [comment]
If only parts of my statements are read, then it is difficult to advise further. If all of my argument is summed up in the phrase "it used to do this", then I don't know how more to explain it.

>If you want an empty object you CAN STILL get one by passing a null or empty pk - just like Joomla does in many places!

If I want something, I do it easily with writing my own getItem method in my model, it is not about what I want.

**Comment by Fedik** [comment]
I just noticed that Empty object used everywhere,
`ArticleModel`
https://github.com/joomla/joomla-cms/blob/a175fc65cf74c1adff73380857a14925b9c7a538/administrator/components/com_content/src/Model/ArticleModel.php#L400-L426
`CategoryModel`
https://github.com/joomla/joomla-cms/blob/a175fc65cf74c1adff73380857a14925b9c7a538/administrator/components/com_categories/src/Model/CategoryModel.php#L199-L217

It more deep as I expected :smile: 
Sound like a reverting is a good idea. Or we need a bigger changes in all core Models which use Empty objects.

**Comment by PhocaCz** [comment]
As I wrote, it looks like returning an empty object is the intention. The whole CMS counts on it. I don't know what exactly was intended, anyway, for the example I gave, it's appropriate: we ask for the existence of the item, if it doesn't exist yet, create an empty object so we can create a new instance right away.

I don't see any downside to that. We have clearly separated the states "error" and "empty object" and in case we need to create a new instance, we have a ready object with all the columns of the database table (ideal for loading into the Form object), etc.

**Comment by PhocaCz** [comment]
@PhilETaylor I don't understand why you're blaming me for something I didn't create. Something that the core Joomla developers created and used for a few years until the J4 RC version?

>If you WANT a blank object then call getItem with no $pk integer - simple, but if you provide an ID and that row doesn't exist in the database then returning a blank object is conceptually, architecturally plain stupid

As written many times, it is about join tables with the current ID, not auto increment ID, if you will read my previous posts properly, I have written it there.

Anyway, if we forget everything this, I still didn't get answer how to differentiate between "error" and "empty data" when false is returned?

>Its clear you dont understand that. and for this reason Im unsubscribing, because whatever step you force the Joomla contributors to make, is going to be the wrong one.

I don't force anyone into anything, my tone is friendly, non-confrontational, and I try to avoid escalating the discussion. So I don't understand your comments.

**Comment by Fedik** [comment]
~~@PhilETaylor can you please revert only AdminModel part and adjust User HtmlView, the rest seems okay, or maybe I missed something?~~

**Comment by Fedik** [comment]
hm, @PhocaCz found another fun thing, in old code if you do `$model->getItem(1111);` (with non existing id), it return empty table with this id assigned (I mean `$object->id` will be `1111`), and it still impossible to distinguish between empty result and error.

As example when you try open `/administrator/index.php?option=com_users&task=user.edit&id=11111` to edit, you will get a form to edit a user with ID `11111`, instead of "Not found" error.

@wilsonge can you please have a look, maybe you have some idea? It looks like a big mess :smile:

**Comment by PhocaCz** [comment]
@Fedik

For the user table it seems to be a different story, the ID is supplied somewhere else.

libraries/src/Table/User.php line 65 (Joomla 3)

```
// Get the id to load.
if ($userId !== null)
{
	$this->id = $userId;
}
else
{
	$userId = $this->id;
}
```
The object basically gets each ID and keeps it ($this->id)

You also get a warning, but from a completely different place

![img](https://i.imgur.com/02a9HxG.png)



libraries/src/User/User.php line 885(Joomla 3)

```
\JLog::add(\JText::sprintf('JLIB_USER_ERROR_UNABLE_TO_LOAD_USER', $id), \JLog::WARNING, 'jerror');
```

So it looks like the user table is a slightly different matter. But overall we need to look at the getItem method in the model globally, not just the method that affects the content (article) model, but the model of all parts of the system. And there you need to count on a solution that is as universal as possible (because each part can override its own solution), so that it fits all kinds of needs.

As I've written many times in this thread, I'm not here to argue that I'm right, but rather to point out the problem and somehow contribute to a consensus regarding the handling of errors and empty results.

>it still impossible to distinguish between empty result and error

So it seems, in case of user table, you are right, which doesn't make the situation any easier, but rather adds another problem to the decision 😄

**Comment by Fedik** [comment]
hm, I see, so there is another bug :)

**Comment by richard67** [comment]
will we get a discount when having found 10 bugs, "buy 10 and pay 8 only"?

**Comment by PhocaCz** [comment]
BTW - maybe new issue should be done for the user table. It is very interesting.

- You can access the edit
- You can save it

![img](https://i.imgur.com/iW6KZP9.png)

- It tells you, that the user is successfully stored but all data will be emptied and there is no record in database

The **bad news** is that it's behaving very strangely.
The **good news** is that it hopefully won't allow you to save a record and thus might be meaningless, since the possibility of this happening to a normal user in normal use is slim.

**Comment by brianteeman** [comment]
Is there anything to be done here?

**Comment by joomdonation** [comment]
I agree with @brianteeman . Joomla 4 was released more than one year ago, so it's too late for us to discuss about backward incompatible changes now. Therefore, I'm closing this issue. Let's move forward !
