### ISSUE TITLE
COM_CONTACT: COM_CONTACT_WEBPAGE language key & value missing

### ISSUE THREAD

**Issue by DelPoint** [joomla/joomla-cms#35817]
**COM_CONTACT_WEBPAGE** key is displayed on front-end if **Global Configuration -> Contacts -> Icons** panel's **Settings** drop-down list is set to **Text**.

The  key **COM_CONTACT_WEBPAGE** and its value is missing from all INI files.

Affected: Joomla! v3.9x & v4.03.

Is this a right place to report missing lang strings? If not, please advise...

**Comment by conconnl** [comment]
Is it correct that you mean the following settings and this also happens in the default en-GB language?
<img width="958" alt="image" src="https://user-images.githubusercontent.com/11913918/137219990-f323ba74-4cfb-4537-a1a0-5772d008180a.png">

**Comment by DelPoint** [comment]
Yes, it is correct.
However, your screenshot is from J!3, and you'll not notice the missing string on the front-end, as it is simply not output/used at all. But the string is still missing from the lang files of J!3 too.
 If you use J!4 though, then you'll see it on the front-end too, as before the webpage of a contact the language KEY will be displayed of course.

**Comment by HLeithner** [comment]
Moved @conconnl

**Comment by DelPoint** [comment]
@conconnl May I ask for a little explanation?
> As it’s in the base language (en-GB) as well, it’s not a translation or language pack issue, but a Core issue.
You mean:
- not displaying the missing key/value in J! 3 _ _is_ _ the core issue?
- or trying to display the missing key/value in J!4 _ _is_ _ the core issue?

**Comment by infograf768** [comment]
The string is missing in J4
<img width="468" alt="Screen Shot 2021-10-15 at 09 15 11" src="https://user-images.githubusercontent.com/869724/137447350-24748f5e-8f66-4081-b1a4-54fa0d779b7f.png">

The string AND the code `$item->params->set('marker_webpage')` are missing in J3.

**Comment by alikon** [comment]
please test
#35835  for j3
#35836  for j4
