### ISSUE TITLE
[4.0] Invisible recaptcha label

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#35814]
### Steps to reproduce the issue
Configure and enable the invisible recaptcha plugin

### Expected result
Contact form is displayed with the invisible recaptcha and the label is **not** displayed

### Actual result
Label is displayed
![image](https://user-images.githubusercontent.com/1296369/137026942-4c1febfd-1502-4bc2-9c8b-535682980a1c.png)

### System information (as much as possible)
cassiopeia 
current main branch

**Comment by C-Lodder** [comment]
> libraries/src/Form/Field/CaptchaField.php

Adding `protected $hiddenLabel = true;` to the field doesn't work, for some odd reason.
Only way I managed to hide it, was by adding an empty `protected function getLabel() {}`, but not sure this is the correct approach.

**Comment by joomdonation** [comment]
Change https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/captcha/recaptcha_invisible/recaptcha_invisible.php#L172 to

```php
$element['hiddenLabel'] = 'true';
```

should solve the issue.

**Comment by C-Lodder** [comment]
PR: https://github.com/joomla/joomla-cms/pull/35828

Ended up removing that method and adding a class variable instead, cause I don't agree with a mix of strings and booleans

**Comment by joomdonation** [comment]
I made PR https://github.com/joomla/joomla-cms/pull/35834 to fix this issue. Please check and give feedback. Closing this issue for now and will re-open later if needed.
