### ISSUE TITLE
[4] Not possible to delete cache if cache not activated in configuration

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#35810]
# 1.)
### Steps to reproduce the issue
- My cache folders are full of content of 3rd extensions.
- Joomla cache is deactivated in Global Configuration.
- I can't delete several cache groups like it was possible in Joomla 3.
- The Clear Cache page shows a message:

> You have no cached content. If you enable caching in Joomla Global Configuration, then any cached items will be displayed here.

### Expected result
- I can delete cache without activating Joomla caches.

### Additional comments
- The dependency above is nonsense.

# 2.)
- When I activate Joomla Caching:
- A click on "Delete All" doesn't delete all folders and files from both cache folders.
- Especially (why I report here) autoload_psr4.php is extremely annoying for developers.
- And no, these aren't newly created folders and files.
- And no, "Clear expired" doesn't help.
- Why this new behavior in Joomla 4 that forces people to clear their cache folders via FTP?

**Comment by brianteeman** [comment]
_*Ignoring for now the autoload_ps3 file_

When I enabled system cache on my test site with the `file` cache_handler  the only folder that was used for storing the cached files was the cache folder `/administrator/cache`

When I used the clear cache from the system menu this folder was emptied *

Browsing again to refill the cache and then disabling the cache in the global configuration I see that all the contents of the cache folder* were emptied as soon as the configuration change was made.

**Comment by ReLater** [comment]
We had confirmations of this issue in german forum. Using Cache Cleaner of Regular Labs for Joomla 4 solves the issue. It deletes everything in /cache/ folders. Not only Joomla cache folders/files.
