### ISSUE TITLE
An error has occurred. 0 Using $this when not in object context

### ISSUE THREAD

**Issue by Akash1029** [joomla/joomla-cms#35824]
I have recently Updated to Joomla 4.0.3. now everything is working fine. but whenever I'm trying to access the Site module 
I'm getting this error

An error has occurred. 0 Using $this when not in object context.

<html>
<body>

1 | () | JROOT\libraries\vendor\joomla\application\src\AbstractWebApplication.php:739
-- | -- | --
2 | Joomla\Application\AbstractWebApplication::getBody() | JROOT\plugins\system\roksprocket\roksprocket.php:295
3 | plgSystemRokSprocket->onAfterRender() | JROOT\libraries\src\Plugin\CMSPlugin.php:285
4 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT\libraries\vendor\joomla\event\src\Dispatcher.php:486
5 | Joomla\Event\Dispatcher->dispatch() | JROOT\libraries\src\Application\EventAware.php:111
6 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT\libraries\src\Application\CMSApplication.php:1042
7 | Joomla\CMS\Application\CMSApplication->render() | JROOT\libraries\src\Application\AdministratorApplication.php:514
8 | Joomla\CMS\Application\AdministratorApplication->render() | JROOT\libraries\src\Application\CMSApplication.php:284
9 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:63
10 | require_once() | JROOT\administrator\index.php:32

</body>
</html>

**Comment by joomdonation** [comment]
You should report this bug to the developer of **roksprocket** plugin and ask him to fix it. This is not related to Joomla core.

**Comment by joomdonation** [comment]
Closing because this is none core issue.
