### ISSUE TITLE
Missing strings - Dashboard

### ISSUE THREAD

**Issue by mrownicki** [joomla/joomla-cms#35820]
### Steps to reproduce the issue

Missing strings - Dashboard for other languages
(screenshot)
### Expected result

Added string for it was possible to translate

### Actual result
![screen shot 2021-10-14 at 10 40 22](https://issues.joomla.org/uploads/1/62f04b3bd910b5cfd536f1e9ecac1022.png)
No translation possible

### System information (as much as possible)
Joomla 4.0.3

### Additional comments

I looked through the submissions, but I haven't seen anything like it.

**Comment by brianteeman** [comment]
These are the titles of the administrator modules and not translatable strings

**Comment by mrownicki** [comment]
@brianteeman 
You want to tell me that every time I build a website I will have to change it every time.... 
This is not a good solution.
During the installation, when I choose the language, I would like the CMS to be 100% translated. And not an additional translation. 
This creates a serious barrier for non-English speaking people ...

This should be translated at the language selection level. Even if it requires an additional SQL update.

**Comment by Quy** [comment]
Related #35587

**Comment by Quy** [comment]
Duplicate #35587
