### ISSUE TITLE
[3.10] The User Action Logs let's not see the username 

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#35821]
### Steps to reproduce the issue

1) Go to 'Forgot your username?' and request your username.

2) Go to 'User Action Logs' and there you will see the 'name' of the user and NOT the 'username'.
This is inconsistent.

### Expected result

'User Action Logs' let's see the 'username'

### Actual result

'User Action Logs' let's see the 'name'

### System information (as much as possible)

Non relevant

### Additional comments

Same issue for [4.0]

file:\joomla\plugins\actionlog\joomla\joomla.php, line 929...

Code
```
$message = array(
	'action'      => 'remind',
	'type'        => 'PLG_ACTIONLOG_JOOMLA_TYPE_USER',
	'id'          => $user->id,
	'title'       => $user->name,
	'itemlink'    => 'index.php?option=com_users&task=user.edit&id=' . $user->id,
	'userid'      => $user->id,
	'username'    => $user->name,
	'accountlink' => 'index.php?option=com_users&task=user.edit&id=' . $user->id,
	);
```
Should be:

```
$message = array(
	'action'      => 'remind',
	'type'        => 'PLG_ACTIONLOG_JOOMLA_TYPE_USER',
	'id'          => $user->id,
	'title'       => $user->username,
	'itemlink'    => 'index.php?option=com_users&task=user.edit&id=' . $user->id,
	'userid'      => $user->id,
	'username'    => $user->username,
	'accountlink' => 'index.php?option=com_users&task=user.edit&id=' . $user->id,
	);
```

**Comment by chmst** [comment]
Which remembers me that wanted to suggest a change in the language. 
The words "username" and "user" are confusing - maybe only for me? But this is such a typical case where maybe it was not clear that user is not a user but an account name. 
What do you think about changing the "user" to "account"? 

@brianteeman 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35821">issues.joomla.org/tracker/joomla-cms/35821</a>.</sub>

**Comment by brianteeman** [comment]
That would be a big change that would need to be applied in a lot of places

**Comment by chmst** [comment]
Yes, I know. It was a conceptual mistake. Something like client = 1 means admin and 0 means site (or vice versa?).  :)

**Comment by brianteeman** [comment]
and a concept that has existed for 17 years

**Comment by brianteeman** [comment]
Joomla 4 already uses the proposed code and as j3 wont be getting any more changes this should be closed

**Comment by sandewt** [comment]
Thks
