### ISSUE TITLE
[4] View of the component don't render correctly

### ISSUE THREAD

**Issue by davidribeiro05** [joomla/joomla-cms#35832]
Hello everyone, first of all, sorry for my bad english, i'm using a translator to explain my problem.

If i try access my component through the url ex: mydomain.com/index.php?option=com_mycomponent&view=myview, Joomla doesn't show the component preview, instead it keeps rendering the index layout.

### Steps to reproduce the issue
Access the component with an url like ex: mydomain.com/index.php?option=com_mycomponent&view=myview

### Expected result
The correct display of the component.

### Actual result
Index page layout display

### System information (as much as possible)
<html>
<body>

Joomla! Version | 4.0.3
-- | --
PHP Version | 7.4.3
Identity | guest
Response | 200
Template | custom

</body>
</html>

**Comment by brianteeman** [comment]
Same problem as #35463 
If there is no layout in the url then the default routing is not used as intended

**Comment by richard67** [comment]
@brianteeman So it can be closed as duplicate report to #35463 ?

**Comment by joomdonation** [comment]
The report is not clear, so I am unsure if it is similar to #35463. @davidribeiro05 Could you please give more information? What's **Index page layout** in your report? Is it one of the layout from myview view of your component? Or it is the layout of a component which is setup in your site Home menu item?

**Comment by davidribeiro05** [comment]
@joomdonation  The error was happening on the main page apparently it was a developer programming error. It has been fixed and is working fine. Thanks!
