### ISSUE TITLE
Hide menu link title

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#35831]
Hello,

### Steps to reproduce the issue

In the menu items, in the "Link Type" tab, the "Display Menu Item Title" button does not work. When I deactivate it, the title is still displayed, whereas in Joomla 3, the title was hidden.

### Expected result

The menu title must be hidden.

### Actual result

The title is still displayed.

### System information (as much as possible)

Joomla 4.0.3

**Comment by brianteeman** [comment]
I can not replicate this

![image](https://user-images.githubusercontent.com/1296369/137471954-9033f499-af2a-4fcc-b323-72fc301232b5.png)

![image](https://user-images.githubusercontent.com/1296369/137471874-8ee838e2-927f-4171-a5ce-6bba1a99d2e6.png)

**Comment by RickR2H** [comment]
Title will only be hidden if the menu item has an image. In that case only the image will be shown. To hide the menu item you set the option "Display in Menu: to "No"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35831">issues.joomla.org/tracker/joomla-cms/35831</a>.</sub>

**Comment by RickR2H** [comment]
@dvince38 Please check is the issues is resolved with the comments above so we can close the issue. Otherwise please add some more details om how to reproduce the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35831">issues.joomla.org/tracker/joomla-cms/35831</a>.</sub>

**Comment by ghost** [comment]
I do the same as brianteeman and this is what I get:

![screen shot 2021-10-15 at 11 59 01](https://issues.joomla.org/uploads/1/8d847eb4eb06833e9bd6031bfd921aa1.jpg)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35831">issues.joomla.org/tracker/joomla-cms/35831</a>.</sub>

**Comment by brianteeman** [comment]
Please test with the cassiopeia template. It sounds like there is a menu module override in your template that is missing the relevant code.

**Comment by ghost** [comment]
It's the same thing with the cassiopeia template :
![screen shot 2021-10-15 at 13 47 46](https://issues.joomla.org/uploads/1/043d0cb4f4c079be02835fe477ee19f6.png)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35831">issues.joomla.org/tracker/joomla-cms/35831</a>.</sub>

**Comment by RickR2H** [comment]
@dvince38 I did some testing and could not reproduce the issue. Could you please test with the latest nightly build? https://developer.joomla.org/nightly-builds.html

If it is a production site you could try to reinstall the core files.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35831">issues.joomla.org/tracker/joomla-cms/35831</a>.</sub>

**Comment by ghost** [comment]
@brianteeman Indeed, I use a module that is missing the relevant code.
So the problem is solved.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35831">issues.joomla.org/tracker/joomla-cms/35831</a>.</sub>

**Comment by alikon** [comment]
closing as issue is solved
