### ISSUE TITLE
Order featured articles does not work

### ISSUE THREAD

**Issue by peterhulst** [joomla/joomla-cms#35837]
### Steps to reproduce the issue
Change the order by using the article drag and drop

### Expected result
The featured order is changed

### Actual result
The order remains the same (test it by toggling: ordering ascending / order descending)

### System information (as much as possible)
Version 4.0.3; php 8

### Additional comments
In the main menu: Category order: No order
In the main menu: Article order: Featured article order
Standard template.

**Comment by joomdonation** [comment]
@peterhulst There is a PR https://github.com/joomla/joomla-cms/pull/35741 which fixes this issue. Could you please test? Thanks !

**Comment by peterhulst** [comment]
That fix works! Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35837">issues.joomla.org/tracker/joomla-cms/35837</a>.</sub>
