### ISSUE TITLE
J 3.10.x + Wrong Error Message after User has been already activated

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#35849]
### Steps to reproduce the issue
When a user is already activated and / or if the user already clicked the activation link an error appears that the verification code cannot be found.

### Expected result
If the user is already confirmed there should be a simple system message that there is nothing to activate and that the user might try and login with the username and password. If the verification code is wrong, there should be a message to double check the link and maybe copy the whole link and paste it into the browser adress bar.

### Actual result
"Fatal error" #403 Verification code not found and opens the error.php page instead of simple system warning.

### System information (as much as possible)
currently with Joomla 3.10.x - i did not test with Joomla 4 but i think its the same there.

### Additional comments
For aecurity reasons, gdpr oder whatever the error message cannot disclose if the account exists or not so the errormessage must be something generic like:

**We could not activate your account because:
1. Maybe your account is already activated, try to login here.
2. Maybe you mistyped the verification code or link, please double check
3. Maybe your registration failed.
If you have further issues please contact the administrator of the website.**

**Comment by bembelimen** [comment]
https://github.com/joomla/joomla-cms/pull/35574

**Comment by richard67** [comment]
@bembelimen The PR which you have linked solves it for J4. But the issue here is for J3 and J4 as far as I understand, so I think we'd have to leave it open as long as we don't have a PR for J3. Is that right?

**Comment by bembelimen** [comment]
Yes, till someone backports the solution.

**Comment by richard67** [comment]
Then I only hope nobody will forget to close the issue when time has come.

**Comment by Quy** [comment]
PR #36051 for J3
