### ISSUE TITLE
bootstrap utilities

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#35850]
In the rush to implement bootstrap 5 it was not implemented 100% correctly - specifically regarding RTL

For example we are maintaining https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/templates/atum/scss/vendor/bootstrap/_bootstrap-rtl.scss

If we were correctly using the utilities api then there would be no need for this file and the bonus is that the classes would actually be correct in RTL.

For example the class `.me-2` created in that file is completely wrong 
`margin-left: auto !important;`
should be 
`margin-left: 0 !important;`

That incorrect css produces 
![image](https://user-images.githubusercontent.com/1296369/137704089-c25b9ea7-c823-4113-a884-0578f55048a4.png)

It should be
![image](https://user-images.githubusercontent.com/1296369/137704214-dbce4757-93cf-4d76-8d26-f9a55b5b33a7.png)

Yes we could easily patch the `_bootstrap-rtl.scss` file but that is not the correct solution. The correct solution is to use the API.

**Comment by pritam825** [comment]
after removing the me-2 class from sample_data_title, it giving the correct as desired.
![Screenshot (1916)](https://user-images.githubusercontent.com/54195688/150635682-5fd0eeb9-222c-4d41-97d6-375740f303f2.png)

Is this the correct way, then I will open the pr for this, thanks :)

**Comment by brianteeman** [comment]
is it still correct in ltr when you do that?

**Comment by pritam825** [comment]
sorry, I didn't understand ltr?

**Comment by pritam825** [comment]
@brianteeman  Yes I have checked now, It's still correct

**Comment by brianteeman** [comment]
great

**Comment by pritam825** [comment]
Thanks

**Comment by richard67** [comment]
@brianteeman Is this issue solved with that PR? Or is there something remaining?

**Comment by brianteeman** [comment]
That PR addresses the visual issue with the example I gave. It doesnt address the fact that we are not using the bootstrap rlt utilties

**Comment by richard67** [comment]
Thanks for confirming my understanding. So I think we should leave the issue open, and maybe later when that PR has been merged just change the description so it doesn't handle the visual thing anymore.

**Comment by brianteeman** [comment]
That PR is also not correct

**Comment by brianteeman** [comment]
#38412
