### ISSUE TITLE
Upload in Media Manager Impossible with PHP Setting memory_limit=-1

### ISSUE THREAD

**Issue by mipri25** [joomla/joomla-cms#35853]
### Steps to reproduce the issue
With Joomla! 4.0.3 and a PHP configuration including
`memory_limit=-1`
try to upload an image using the Media Manager (Content -> Media in the Backend).

### Expected result
Since according to the [PHP dokumentation](https://www.php.net/manual/en/ini.core.php#ini.memory-limit) "memory_limit=-1" means "there is no limit", the upload should work.

### Actual result
Upload is rejected with error "This file is too large to upload."

### System information (as much as possible)
Joomla! 4.0.3 Stable [ Furaha ] 12-September-2021 10:39 GMT
PHP-Version 7.4.24
Apache Webserver

**Comment by brianteeman** [comment]
But what are the important settings
post_max_size
upload_max_filesize

**Comment by mipri25** [comment]
They are both set to 64M, and the error occurs even when uploading tiny files of about 10k.

I also could workaround the problem by adding
`ini_set('memory_limit','256M');`
to administrator/index.php

**Comment by brianteeman** [comment]
There is a bug when memory limit is set to -1. Working on a fix

**Comment by brianteeman** [comment]
Please test #35854

**Comment by alikon** [comment]
closing as we have a pr #35854

**Comment by richard67** [comment]
Re-opening as the PR has been closed.

**Comment by richard67** [comment]
Closing as having a new pull request. Please test #36023 . Thanks in advance.
