### ISSUE TITLE
languages missing metadata

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#35851]
It should not be possible to have a language file with missing metadata

![image](https://user-images.githubusercontent.com/1296369/137705667-e32a0cf2-59ca-4493-910c-3c79ad57f48a.png)

**Comment by brianteeman** [comment]
Because the version is missing for the arabic language joomla will permanently tell you that there is a new version available to install

**Comment by brianteeman** [comment]
Arabic language is still broken and permanently offers an update. Can this please be fixed (and preferably some quality control to prevent it happening) @Bakual @willebil

**Comment by Bakual** [comment]
I can't help with J4 languages. They're handled on the new Crowdin Instance where I'm not a manager.
The reason is as Brian already wrote. The XML manifests (6 of them, the api install.xml has "4.0.0") doesn't contain the version string:
````
<extension type="package" method="upgrade">
	<name>Arabic ar-AA(العربية الموحدة)</name>
	<packagename>ar-AA</packagename>
	<version/>
	<creationDate>August 2021</creationDate>
````

**Comment by pritam825** [comment]
@brianteeman sir, sorry for disturbing you, I have installed all the languages for checking that for which language version is missing, I found "Norwegian bokmål (Norway)" and "Arabic (اللغة العربية)" version is missing and date is updated for all the languages, so for the version updation, will I have to change like this as I have pasted the scrrensho
![Screenshot (1913)](https://user-images.githubusercontent.com/54195688/150630285-929cbebe-9ba6-405e-ab9f-ca41fa94931d.png)

or I am thinking in the wrong direction ,   Thanks in Advance :)

**Comment by brianteeman** [comment]
@tecpromotion any chance you can force a fix on the arabic

**Comment by tecpromotion** [comment]
The easiest way is to contact the author. I can do this of course.
