### ISSUE TITLE
Wrong url in Compact List of Tagged Items

### ISSUE THREAD

**Issue by deroderuiter** [joomla/joomla-cms#35852]
I haven a J3 website with categories with tags. To display all the categories with the same tags I use a menu with "Compact List of Tagged Items". 
When you click on one of the items in the list the category is displayed.

### Expected result
After I upgraded the website to J4, I expected that this would still work.

### Actual result
But in J4 the URL's of the tagged items are wrong. They all point to the root of the website.

### System information (as much as possible)
I build a small new website in J4 and there the List of tagged items is working as expected. I think the problem is caused by the upgrade to J4.

### Additional comments
I have a live J3 website and a J4 testwebsite were you can see the differences.
I added two files were you can see that the url in J3 is different than in J4.

![screen shot 2021-10-18 at 13 56 23](https://issues.joomla.org/uploads/1/670afcf9175148858b494214653dd130.jpg)

![screen shot 2021-10-18 at 13 56 26](https://issues.joomla.org/uploads/1/882c15d85240fe7fbbf3df978168c728.jpg)

**Comment by deroderuiter** [comment]
I build a small part of the website directly in Joomla 4. The same problem occurs in the Compact List of Tagged Items<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35852">issues.joomla.org/tracker/joomla-cms/35852</a>.</sub>

**Comment by brianteeman** [comment]
Please retest using the core cassiopeia template to avoid any possible issues with your template

**Comment by deroderuiter** [comment]
I now have a very small website with just a few items: 3 tags, 2 articles, 5 categories, 4 sitemodules (menu, article newsflash and logon), 2 menu's and no third party extensions. The only site template is Cassiopeia. 
The result is still the same. The URL in the Compact List of Tagged Items is still wrong.

**Comment by deroderuiter** [comment]
Sorry, I accidentally closed it. How do I reopen it?

**Comment by deroderuiter** [comment]
Sorry, I accidentally closed it

**Comment by Pinkeltje** [comment]
Unable to reproduce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35852">issues.joomla.org/tracker/joomla-cms/35852</a>.</sub>

**Comment by deroderuiter** [comment]
I have been able to reproduce the problem. You need to have a Menu item called "Home". Then you can display one of the Items of the list. When you delete the menu item "Home", you cannot display an item.

I solved my problem by creating a menu item called "Home" of the type "Category List" and I did choose a category that is parent to all the categories that have tags.

My website is rather complex and I needed to make some more changes because to each category with a tag, modules are attached. All these modules (about 800!!!) need to be assigned to "Home" menu item.

In Joomla I didn't need to make all these changes so its a pity that it doesn't work the same in J4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35852">issues.joomla.org/tracker/joomla-cms/35852</a>.</sub>

**Comment by joomdonation** [comment]
I tried before and could not re-procedure the issue, too. Just for information, you should have a menu item like that to allow Joomla! routing to build right URL. It does not need to be called **Home** and could also be set to hidden if needed.

As you solved the issue with a recommended setup and we could not re-procedure the issue, I'm closing this.
