### ISSUE TITLE
[4.0] Template mail + TinyMCE + HTML

### ISSUE THREAD

**Issue by mrownicki** [joomla/joomla-cms#35868]
### Steps to reproduce the issue
Please add Categories on Github com_mails.

Create new template USERS: NEW USER - plg_user_joomla.mail

Options format - HTML

I add some simple text + image. 
TinyMCE missing CMS CONTENT button.![screen shot 2021-10-20 at 11 21 18](https://issues.joomla.org/uploads/1/e919a3c084940468085e2ca279f6de19.png)

2. TinyMCE 

Not allow add https://domain.com/images/image.jpg Because is stripped https://domain.com 

In mail must be full URL to image.

Drag and drop also it doesn't give you the entire url

I know TinyMCE have setup relative url. 
But no one will remember to rearrange it every time. It does not make sense.

### Expected result

Add CMS CONTENT Button

Image and the other media (video, mp3 etc.) in template mail have always absolute url.

### Actual result

Missing content button

Image url is relative

### System information (as much as possible)
4.0.3

### Additional comments

The whole concept of beautiful emails just doesn't work as it should at this point.

**Comment by sakiss** [comment]
This is how most editors work, since they are developed for a different purpose (creating content).
A solution could be to set your editor to "none" in your user/admin settings and change the urls to absolute manually.

**Comment by mrownicki** [comment]
@sakiss I know that.
This is normal for perspective developer not user ;) 
It makes no sense then to give HTML options and start the editor. It just wasn't thought out well.

The user cannot run around constantly around the settings! It has to focus on acting and creating.
That's why WP is popular and J! keeps falling in statistics.

I only report a problem if no one changes. It's just that users will use it marginally.
Regards.

**Comment by brianteeman** [comment]
@sakiss that is not the solution. The solution is to initialise the tinymce editor with the correct required options for this use. Sadly the developer of this poorly thought out extension had obviously never actually used it. Instead they bullied its inclusion when it was not ready

**Comment by HLeithner** [comment]
@Hackwar the rendering engine for the html email should replace the relative sources right?

**Comment by Fedik** [comment]
I am not @Hackwar :smile: but @HLeithner is right, it should be done while rendering, replace relative path to correct one.
Because User may use any editor, also the content will be broken when user change site domain/path.

**Comment by joomdonation** [comment]
Hopefully PR https://github.com/joomla/joomla-cms/pull/36088 fixes this issue. Please help testing. Thanks !

**Comment by sakiss** [comment]
@mrownicki could you please test?

**Comment by mrownicki** [comment]
> @mrownicki could you please test?

How i can test this? I don't use repo github. Will it be in the night dev?

**Comment by sakiss** [comment]
@mrownicki Install the PatchTester component and then apply that Pull Request.
Instructions here: https://docs.joomla.org/Component_Patchtester_for_Testers

Then mark your test result in the issue tracker.
https://issues.joomla.org/

More details on the process can be found here: https://docs.joomla.org/Testing_Joomla!_patches
It may look unfamiliar atm but it is quite simple.

**Comment by mrownicki** [comment]
Test work.
