### ISSUE TITLE
Smart Search only searches from the start of word

### ISSUE THREAD

**Issue by RickR2H** [joomla/joomla-cms#35861]
### Steps to reproduce the issue
Create an article with the word: Transform
Activate Smart Search in Joomla 4 start the indexer.
Search for: "form" Finder will not find any match.

### Expected result
The result should say: Transform

### Actual result
No results

### Additional comments

**Comment by brianteeman** [comment]
As far as I am aware that's what makes it a smart search. It only searches for words with the same stem

**Comment by RickR2H** [comment]
Closing as having a Pull Request #35864<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35861">issues.joomla.org/tracker/joomla-cms/35861</a>.</sub>
