### ISSUE TITLE
Google recaptcha  not working on login page

### ISSUE THREAD

**Issue by amer1404** [joomla/joomla-cms#35866]
I am using Joomla 3.10.2 and I enabled Google ReCaptcha plugin (visible and invisible)  with set keys in the correctly way

The issue is the ReCaptcha is not shown with login page but it is working fine with the rest password and email pages.
I tried both ReCaptcha methods ( visible and invisible) , both of them were not shown with login page.

Am trying also with different template, it's same result.

**Comment by joomdonation** [comment]
Actually, it is not a bug or issue. We just do not support captcha on login form.

**Comment by joomdonation** [comment]
Closing because this is not an issue and I don't think we will implement captcha with login page very soon.
