### ISSUE TITLE
[3.10.2] Updater problem after changed server to ssl

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#35876]
changed my joomla site ftom http to https. Since then I get messages (though sites are accessible):
`Update: Could not open update site #104 "jmootips1.2 Updates", URL: http://www.jschmidt-systemberatung.de/downloads/jmootips12_updates.xml
` 
and more...
Checked with editing "../libraries/src/Updater/upDateAadapter.php" on line 261 (changed from
`$response = null`; 
 to 
`$response->code = http_response_code();`
With this problem is gone as $response->code showed  "200". Sofar I could not find out why 
`$response = $http->get($url, array(), 20); ` 
ran into runtimeException, though http response was "200".

**Comment by brianteeman** [comment]
if you go to the url listed in your component it is http and that is then redirected to https - maybe it doesnt like the redirect?

**Comment by jschmi102** [comment]
hi,
added code
```
$app = Factory::getApplication();
$app->enqueueMessage($e->getMessage(), 'error'); 
```
this showed the problem: runtimeExeption says: 

`SSL certificate problem: certificate has expired
`

**But this is not true** as certificate is valid upto "**Wednesday, 19. January 2022**"  
Pls can you clarify what goes wrong?

**Comment by zero-24** [comment]
@jschmi102 please check the 3.10.3-rc1: https://github.com/joomla/joomla-cms/releases/tag/3.10.3-rc1 that contains an updated cacert.pem.

**Comment by jschmi102** [comment]
hi,
Version 3.10.3-rc1 fixed the problem. Thank you!

**Comment by zero-24** [comment]
Great the GA is expected to be on the 26th October
