### ISSUE TITLE
No Articles Message - is shown regardless of category configuration.

### ISSUE THREAD

**Issue by arturkb** [joomla/joomla-cms#35885]
### Steps to reproduce the issue
Create a category without articles and then try to hide and show "No Articles Message".

### Expected result
"No Articles Message" should not be shown when the configuration is with "hide"

### Actual result
There is no difference when we do change from show to hide on "No Articles Message".

### System information (as much as possible)
The currently installed Joomla! version is "‎4.0.3"‎

**Comment by brianteeman** [comment]
The no articles message refers to the display in the front end

**Comment by arturkb** [comment]
![screen shot 2021-10-24 at 09 03 51](https://issues.joomla.org/uploads/1/d486b409d6b1fc05e6b73059147cbbdb.jpg)![screen shot 2021-10-24 at 09 03 52](https://issues.joomla.org/uploads/1/71c5500f65ce057b6f1bd53e7e403a7b.jpg)![screen shot 2021-10-24 at 09 03 54](https://issues.joomla.org/uploads/1/cbb294127a7bafc710ef926ba39c9f5b.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35885">issues.joomla.org/tracker/joomla-cms/35885</a>.</sub>

**Comment by brianteeman** [comment]
sorry I misunderstood and thought you were referring to the new empty state message in the admin.

What are the settings in the menu item?

**Comment by arturkb** [comment]
![screen shot 2021-10-24 at 12 12 31](https://issues.joomla.org/uploads/1/becbbbbaf47448bbd60c1b206cdf4e18.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35885">issues.joomla.org/tracker/joomla-cms/35885</a>.</sub>

**Comment by brianteeman** [comment]
i meant the settings of the menu item that is generating this page in the frontend

**Comment by arturkb** [comment]
![screen shot 2021-10-24 at 12 32 10](https://issues.joomla.org/uploads/1/71d475b047099d1880b0825b872d6cf0.jpg)![screen shot 2021-10-24 at 12 32 12](https://issues.joomla.org/uploads/1/f6cf93db6f656a713e6c31c678feb4be.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35885">issues.joomla.org/tracker/joomla-cms/35885</a>.</sub>

**Comment by brianteeman** [comment]
seems to work for me

![mess](https://user-images.githubusercontent.com/1296369/138612548-055d4d23-6294-441d-9197-2a1d7aa85768.gif)

**Comment by arturkb** [comment]
Ok, then it seems to be a more specific problem either with categories with subcategories or menu time list. I will different combination and see how this looks like. BTW, where configuration is saved in the file or DB?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35885">issues.joomla.org/tracker/joomla-cms/35885</a>.</sub>

**Comment by brianteeman** [comment]
If you are not using the core template then I would also check to see if the problem is caused by your template. It could be that the template is missing the logic to check if this message should be displayed. Yiu can quickly confirm this by switching to the core template.

**Comment by arturkb** [comment]
I am using standard/core template. I recreated the same issue on this demo site. You can check this her: http://arturkb.joomla.com/index.php/blog/test-menu Send me email address then I will create admin user for you to play with. BTW i see another problem with paging on tags. But lets take one problem at time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35885">issues.joomla.org/tracker/joomla-cms/35885</a>.</sub>

**Comment by brianteeman** [comment]
I still can't replicate it. Please email brian at teeman dot net

**Comment by arturkb** [comment]
ok, done please check email<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35885">issues.joomla.org/tracker/joomla-cms/35885</a>.</sub>

**Comment by brianteeman** [comment]
ok - found the problem. You were looking at a category list menu item. I was looking at a category blog menu item. You have identified a bug. I am looking at a solution

**Comment by brianteeman** [comment]
We got there in the end. Please help to test #35894

**Comment by arturkb** [comment]
Sure I will do it. I need to see how to install this pathed version :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35885">issues.joomla.org/tracker/joomla-cms/35885</a>.</sub>

**Comment by alikon** [comment]
closing as we have a pr #35894
