### ISSUE TITLE
[4.0] JHtml::_('grid.published') does not pick up tick.png icon

### ISSUE THREAD

**Issue by mastervanleeuwen** [joomla/joomla-cms#35892]
### Steps to reproduce the issue
Use JHtml::_('grid.published', $obj, $i)

### Expected result

code for an icon with javascript to publish/unpublish an item

e.g. in Joomla 3: 
`<a href="#" onclick="return listItemTask('cb0','unpublish')" title="Unpublish Item"><img src="/administrator/templates/isis/images/admin/tick.png" alt="Published" /></a>
`

### Actual result 
`<a href="#" onclick="return Joomla.listItemTask('cb0','unpublish')" title="Unpublish Item"><img src="" alt="Published" ></a>
`
The img src field is empty. There is no admin directory in templates/cassiopeia/imagies/. Does cassiopeia use a symbol font for the published icon?

### Additional comments
I am migrating code from Joomla 3 to Joomla 4; this call seems to be intended to work, but something is missing. Maybe the names of the icon files changed?

**Comment by joomdonation** [comment]
@mastervanleeuwen Better migrate your code to use `jgrid.published` instead. Your old code could be changed to :

```php
JHtml::_('jgrid.published', $row->published, $i);
```

Or better, using namespace code:

```php
HTMLHelper::_('jgrid.published', $row->published, $i);
```

That's how I did while migrating my extensions to Joomla 4.

**Comment by mastervanleeuwen** [comment]
Thanks for the tip; this works. I wonder what 
`JHtml::_('grid.published')`
is meant for, but this solved my problem!

**Comment by chmst** [comment]
@mastervanleeuwen thanks for feedback! Could you close the issue, please?

**Comment by mastervanleeuwen** [comment]
Sorry for insisting, but this still leaves the question open why the [grid.published function](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/HTML/Helpers/Grid.php#L190)
has 'tick.png' and 'publish_x.png' as default arguments; it looks like the code cannot find these files; is that intentional?

**Comment by chmst** [comment]
Yes, J4 uses icons 

![image](https://user-images.githubusercontent.com/1035262/139063406-3b32b021-dc7c-41f8-a733-8cb22a3048ac.png)
