### ISSUE TITLE
[4.0] Sessions terminated forcibly due to difference between $_SERVER['REMOTE_ADDR'] and ip

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#35901]
### Steps to reproduce the issue
Unfortunately i am not sure how to reproduce that on your end.

Though i will describe my findings.
1. My user sessions terminate on their own after a very short period (less than a minute).
2. After debugging, i found that the culprit is the function: `Joomla\Session\Validator\AddressValidator::validate()`
Seems like the: `$this->session->get('session.client.address')` is different to the server's REMOTE_ADDR `$this->input->server->getString('REMOTE_ADDR', '')`

Hence it throws an exception and terminates my sessions again and again.
Not sure why this happens but i suppose it's related to some reverse proxy between the client and the server.

Any input is welcome!

### Expected result
Sessions to follow the session set duration

### Actual result
forcible termination 

### System information (as much as possible)
J4.0.3
Hosted on apache sitting behind nginx.
Cloudflaire's CDN is used as well

**Comment by brianteeman** [comment]
Did you already read and test the other issues regarding the use of the cloudflare cdn

**Comment by sakiss** [comment]
Hi Brian
Thanks for pointing out. I was not aware that it's because of Cloudflaire.
I am closing that as a duplicate to #35244 and https://github.com/joomla-framework/session/issues/54
