### ISSUE TITLE
[4.0] Standard Bootstrap 5 Collapse Feature does not work

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#35906]
### Steps to reproduce the issue
Paste some example from this site: https://getbootstrap.com/docs/5.0/components/collapse/ to Cassiopeia index.php and try to run the collapse feature. It does not work.

### Expected result
Collapse feature works.

### Actual result
Collapse feature does not work.

### System information (as much as possible)
Joomla 4.0.3

The question is, should some additional Javascript library be loaded to run standard Bootstrap collapse feature?

Thank you, Jan

**Comment by HLeithner** [comment]
Afaik Cassiopeia doesn't use bootstrap, maybe that's the reason some JS files are missing?

**Comment by PhocaCz** [comment]
@HLeithner Thank you for this info, now I understand it.

This
```
HTMLHelper::_('bootstrap.collapse', '');
```
did the trick.

Thank you, Jan

**Comment by brianteeman** [comment]
https://docs.joomla.org/J4.x:Using_Bootstrap_Components_in_Joomla_4

**Comment by brianteeman** [comment]
> Afaik Cassiopeia doesn't use bootstrap, maybe that's the reason some JS files are missing?

NO!!!!

**Comment by HLeithner** [comment]
> > Afaik Cassiopeia doesn't use bootstrap, maybe that's the reason some JS files are missing?
> 
> NO!!!!

Right, my fault.
