### ISSUE TITLE
Pre-update checker is still showing in 4.0.3 - 4.0.4 updates

### ISSUE THREAD

**Issue by softforge** [joomla/joomla-cms#35904]
### Steps to reproduce the issue
Update a site from J4.0.3 to J4.0.4

### Expected result
Usual warnings about backups but not the whole pre-update checker

### Actual result
The pre-update checker shows and gives lots of warnings

### System information (as much as possible)
J4.0.x website that needs updating

### Additional comments
I'm assuming any fix will go into J4.0.5 and then we wont see the change until between J4.0.5 to J4.0.6
![screen shot 2021-10-26 at 12 08 29](https://issues.joomla.org/uploads/1/16bebd6bfce2c55683d2e9bcb95b07d5.png) 
![screen shot 2021-10-26 at 12 08 41](https://issues.joomla.org/uploads/1/976d078db50d8abfc3e5377437a78978.png)
![screen shot 2021-10-26 at 12 08 53](https://issues.joomla.org/uploads/1/dfe4de0528a5ea553a0c7fb776a4ca3c.png)

**Comment by brianteeman** [comment]
Are you still having this problem? I don't see it myself and it might have been a cdn cache delay?

**Comment by zero-24** [comment]
As mentiond in other places on a quick look it looks like the call to: [shouldDisplayPreUpdateCheck](https://github.com/joomla/joomla-cms/search?q=shouldDisplayPreUpdateCheck)

Has to be added in here: https://github.com/joomla/joomla-cms/blob/ebad54c7bba0a72ae4b48bcca6f9d820f871da85/administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php#L171

> Are you still having this problem? I don't see it myself and it might have been a cdn cache delay?

I'm not sure what kind of CDN cache delay could have an impact on whether the pre upgrade check is shown? It could be that the pre upgrade checker shows here because there is the error AcyMailing? Maybe @bembelimen can give some more insight here as he rewrote this stuff for 4.0

**Comment by softforge** [comment]
@zero-24 and others suggested that the code to stop it had been removed in 4 at some point. So The call to shouldDisplayPreUpdateCheck is not called from com_joomlaupdate https://github.com/joomla/joomla-cms/search?q=shouldDisplayPreUpdateCheck<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35904">issues.joomla.org/tracker/joomla-cms/35904</a>.</sub>

**Comment by brianteeman** [comment]
i still cannot replicate this

**Comment by AndNovAtor** [comment]
I can. STILL.
Updated Joomla 3.10.2 to Jooma 4.0.3. Now 4.0.4 is availible. And pre-update checker still shows. And as it "STUPID" (shows warning any time as ANY extension has not last version), it's hilarrious for Joomla 4
@brianteeman , do you have test Joomla 4.0.3 updated from Joomla 3.10.2, for example (with installed any NOT last version [third-party] extension)? (even, for example, pkg_search with not last version - 4.0.0-dev, as 4.0.1-dev is last version)

**Comment by AndNovAtor** [comment]
>cache

btw, Joomla 3 have "clear" buton in extension install tab, that clear INSTALLER cache (also affects Joomla check update cache), but sadly there is no such button in Joomla 4

**Comment by richard67** [comment]
In J4 that cache clean should be made every time when using the button to search for updates so it doesn't need the extra button anymore.

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/35978 should fix this issue. Please test, thanks !
