### ISSUE TITLE
[4.0.4] Atom feed links are missing closing tag slashes

### ISSUE THREAD

**Issue by david19161** [joomla/joomla-cms#35907]
Links in Atom feeds are missing slash in self-closing tags and wont verify at W3C and (some/most) feed readers wont read them

### Steps to reproduce the issue

eg: taken from the atom link on the home page of a default joomla4 4.0.4 installation

   link rel="alternate" type="text/html" href="http://joomla4-local-default">

   link rel="self" type="application/atom+xml" href="http://joomla4-local-default/index.php?format=feed&amp;type=atom">

missing />

**Comment by zero-24** [comment]
@david19161 please test: https://github.com/joomla/joomla-cms/pull/35908

**Comment by richard67** [comment]
Closing as having a pull request.
