### ISSUE TITLE
J4.0.4 Installation Messages - shows 5 but none visible

### ISSUE THREAD

**Issue by austin7-21** [joomla/joomla-cms#35918]
Updated to 4.0.4 & the Information section shows Installation Message - 5
Click either link and the Installation Messages section opens but there are no messages to view.

**Comment by chmst** [comment]
@austin7-21 I cannot replicate your issue. From which version did you start the update?

**Comment by austin7-21** [comment]
From 4.0.3. It was a fresh build on 4.0.3, Joomla advised the update was available, so having backed up the installation I used to auto-update function within J4.0.3 - everything is working fine - for clarity, the visual face of the site is working as expected & the admin side allows all functions to perform as required with exception of the Installation Message element, which is behaving as described.

The website is hosted on Linux running Apache and uses the latest of everything, including PHP.

**Comment by Quy** [comment]
@austin7-21 I cannot replicate with a fresh install of 4.0.3 to 4.0.6.
Do you see a `Hide all Messages` button and no messages or `Reset Messages` button in the middle of the page?

**Comment by chmst** [comment]
@austin7-21 I did my test on php 7.4 and php 8.0.1.
As you write "The latest of everything" does this mean php 8.1?

**Comment by Quy** [comment]
Closing as not reproducible and no response with additional details.
