### ISSUE TITLE
Retrive sitename in multilingual websites

### ISSUE THREAD

**Issue by mikajaxxx** [joomla/joomla-cms#35916]
### Steps to reproduce the issue
go extension-> langauges- > content langauges & set site name in ' Custom Site Name '
try retrieve site name for language by:
$app = JFactory::getApplication();
$site_name = $app->get('sitename');
or
$config = JFactory::getConfig();
$site_name = $config->get( 'sitename' );

### Expected result
both way render current language site name

### Actual result
render default langauge site name

### System information (as much as possible)
joomla 4.0.4

**Comment by brianteeman** [comment]
You must enable the language filter plugin

**Comment by richard67** [comment]
@mikajaxxx Please check the previous comment and report back if your issue still persists after you have enabled the language filter plugin. Thanks in advance.

**Comment by joomdonation** [comment]
As pointed out by @brianteeman , you need to enable **System - Language Filter** plugin to have it works. The code which handles this could be found here https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/system/languagefilter/languagefilter.php#L189

Closing this issue as this is not a core issue.

**Comment by mikajaxxx** [comment]
@joomdonation  & @brianteeman  of course i enabled system - language Filter and System - Language Code before reporting this issue!

**Comment by brianteeman** [comment]
In which case neither of us can replicate the reported problem

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/139604065-3200c2c7-fe3f-466b-bedd-a5f81c63fba1.png)

![image](https://user-images.githubusercontent.com/1296369/139604068-da0da1d0-04e3-4aee-a1fe-3c770baaf0b3.png)

![image](https://user-images.githubusercontent.com/1296369/139604071-2dca6ffb-e3f7-4975-a313-5e8f52901520.png)

![image](https://user-images.githubusercontent.com/1296369/139604075-d0be1f5e-0fa2-45f2-86b2-631c8af98bdc.png)

![image](https://user-images.githubusercontent.com/1296369/139604076-0ca7c5a4-dfff-4d97-9367-e83e8248d874.png)

**Comment by mikajaxxx** [comment]
It doesnt work on my website, i done it the same way as you!
![jeco](https://user-images.githubusercontent.com/5157272/139604890-fa211d00-309e-4573-879d-c9c599e9e5c2.jpg)

**Comment by joomdonation** [comment]
@mikajaxxx Where do you put your code?

**Comment by mikajaxxx** [comment]
@joomdonation at a system plugin

**Comment by joomdonation** [comment]
@mikajaxxx And that's the reason of the issue. If you look at https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/system/languagefilter/languagefilter.php#L189, you will see that the language filter plugin process that data on onAfterRoute event, so if your system plugin code is triggered before that, the data won't be available
