### ISSUE TITLE
PHP Memory limit  -1 / Unable to upload file

### ISSUE THREAD

**Issue by tristan-bellosta** [joomla/joomla-cms#35925]
### Steps to reproduce the issue
Only applies if php.ini setting "memory limit" is set to -1 (no limit).
On a fresh Joomla 4, try to upload a 1Mo picture on media manager.

### Expected result
Sucess (if others parameters such as upload max size are > 1 Mo, which is default)

### Actual result
Fail : file is too large.

### System information (as much as possible)
memory_limit = -1 on php.ini

### Additional comments
On file administrator\components\com_media\src\Controller\ApiController.php line 370
test if file length > memory limit, which is always true if memory_limit is -1
We should ignore this test if memory limit is -1

**Comment by Quy** [comment]
Closing as having a pull request. Please test #35854. Thanks in advance.
