### ISSUE TITLE
"The Author" Tab Title Not Driven by Language String in "Articles: New/Edit" Screen

### ISSUE THREAD

**Issue by imanickam** [joomla/joomla-cms#35945]
### Steps to reproduce the issue

(a) Log into the Back-end
(b) Make "English (en-GB)" as the default Administrator language
(c) Go to the screen "Articles" (Content > Articles)
(d) Click on the button "New" or edit an existing article
(e) In the resultant screen notice the title of the fourth tab is "The Author"
(f) Cancel/Close the screen
(g) Install the French language (System => Install -> Language)
(h) Make "French (fr-FR)" as the default Administrator language
(i) Go to the screen "Articles" (Content > Articles)
(j) Click on the button "New" or edit an existing article
(k) In the resultant screen notice the title of the fourth tab is "The Author", same as when English was the default Administrator language
(l) Cancel/Close the screen

Note: French language was taken for illustration only.  The same issue prevails with all the languages except for English.

### Actual result

(a) Screenshot with English as the back-end Administrator language
![screen shot 2021-10-30 at 07 10 19](https://issues.joomla.org/uploads/1/fc7b823e930280add7000f70ee6f042d.jpg)

(b) Screenshot with French as the back-end Administrator language
![screen shot 2021-10-30 at 07 10 50](https://issues.joomla.org/uploads/1/fce6afdf1849e5345e09a72702cbcdb0.jpg)

(c) Screenshot with LANGUAGE CONSTANTS
![screen shot 2021-10-30 at 07 11 22](https://issues.joomla.org/uploads/1/0e6b22f48375984a3f5c30794e0daeb0.jpg)

### System information (as much as possible)

Joomla! 4.0.4

**Comment by brianteeman** [comment]
This is part of the sample content

**Comment by brianteeman** [comment]
PLG_SAMPLEDATA_BLOG_SAMPLEDATA_CONTENT_FIELDS_GROUP_TITLE="The Author"

**Comment by imanickam** [comment]
Thanks for the clarification.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35945">issues.joomla.org/tracker/joomla-cms/35945</a>.</sub>

**Comment by chmst** [comment]
@imanickam if this is clear now, could you please close your issue?

**Comment by brianteeman** [comment]
I can see the problem. It is not a translateable language string in the normal sense. If you install the sample data with a language installed then the language file (of the currently active admin language) is used to create the field group with the correctly translated name. Otherwise it will always be in english

![image](https://user-images.githubusercontent.com/1296369/139558024-f74214e6-c222-4f33-8c2b-a48b0e677632.png)

**Comment by imanickam** [comment]
> @imanickam if this is clear now, could you please close your issue?

Yes, I would do.  I do not know how to close this issue. Could you please guide me as to how to close an issue? Thanks,<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35945">issues.joomla.org/tracker/joomla-cms/35945</a>.</sub>

**Comment by brianteeman** [comment]
This should be closed
