### ISSUE TITLE
PHP Warning messages for using uninitialized variables

### ISSUE THREAD

**Issue by boddunan** [joomla/joomla-cms#35941]
### Steps to reproduce the issue
Create a custom component with categories support and do not add /components/$component/forms/$name.xml file

### Expected result
No PHP warning messages shown

### Actual result
PHP warning messages shown as below
Warning: Undefined variable $ref_key in /root../administrator/components/com_categories/src/View/Categories/HtmlView.php on line 302

Warning: Undefined variable $url in /root../administrator/components/com_categories/src/View/Categories/HtmlView.php on line 318

Warning: Undefined variable $url in /root../administrator/components/com_categories/src/View/Categories/HtmlView.php on line 328

### System information (as much as possible)
Joomla 4.0.4 and above

### Additional comments
The bug was introduced in Joomla 4.0.4

**Comment by joomdonation** [comment]
@boddunan You do not need to create an issue to open a PR to fix it. In the future, please open directly. Thanks.
