### ISSUE TITLE
com_contact: Contact image does not display

### ISSUE THREAD

**Issue by jen4web** [joomla/joomla-cms#35940]
### Steps to reproduce the issue
1. Create a new contact: Components - Contacts - New
2. Choose or upload an image in the "image" field in "Edit Contact"
3. Enter other contact information as desired. 
4. Save contact. 
5. Link to menu. 
6. Look at the contact screen on the front end.

### Expected result
See the image displayed, along with the rest of the contact information entered and set to display.

### Actual result
Contact information displays on the public facing website but the image is broken. (Image displays as a thumbnail in the data entry screen.)

Rendered HTML shows an incorrect path to the image:
<div class="com-contact__thumbnail thumbnail">
   <img src="/joomla/" alt="Leaf and Mortar" itemprop="image">				
</div>

### System information (as much as possible)
PHP 7.4.11
Database version 5.7.32

### Additional comments

![screen shot 2021-10-29 at 21 47 34](https://issues.joomla.org/uploads/1/4896dfc0b0cff433c903a1f0903fec77.png)
![screen shot 2021-10-29 at 21 47 34](https://issues.joomla.org/uploads/1/03ec53d60439ad4b682659eeaa7082b2.png)

**Comment by jen4web** [comment]
HTML for the contact image:

<pre>
    <div class="com-contact__thumbnail thumbnail">
	<img src="/joomla/" alt="Leaf and Mortar" itemprop="image">				
    </div>
</pre><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35940">issues.joomla.org/tracker/joomla-cms/35940</a>.</sub>

**Comment by brianteeman** [comment]
Can not replicate

![image](https://user-images.githubusercontent.com/1296369/139505735-3ca0eaf7-e56f-463b-aa5d-c73224b2e190.png)

![image](https://user-images.githubusercontent.com/1296369/139505778-c32db813-2e9d-4c9a-ad14-3fab497b4e76.png)

**Comment by chmst** [comment]
Hi, @jen4web which formalt is your image? jpg, JPEG, png, PNG ... I cannot see that in your screen. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35940">issues.joomla.org/tracker/joomla-cms/35940</a>.</sub>

**Comment by jen4web** [comment]
Hi chmst - I tested .jpg, .png

The path to the image in the code was img src="/joomla/" alt="Leaf and Mortar"

However - it seems the issue is related to the file name. If there are spaces in the file name, i.e. "leaf image.png", this produces a broken image. If there are no spaces in the file name, then the image is fine.

Spaces in the file name does not seem to be an issue elsewhere, as I've used these images in the media manager in articles and modules elsewhere on the site. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35940">issues.joomla.org/tracker/joomla-cms/35940</a>.</sub>

**Comment by joomdonation** [comment]
Confirm the issue with space in filename. The reason is because:

- We replace space character with %20 in the local adapter https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/filesystem/local/src/Adapter/LocalAdapter.php#L754
- Because space character is replaced with %20, `is_file` check https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/HTML/HTMLHelper.php#L1316 return false, and no image is returned

A possible solution is replace %20 back to space on is_file check. So the code would be something like:

```php
private static function checkFileOrder($first, $second)
{
	$decodedSecond = str_replace('%20', ' ', $second);

	if (is_file($decodedSecond))
	{
		return static::convertToRelativePath($second);
	}

	$decodedFirst = str_replace('%20', ' ', $first);

	if (is_file($decodedSecond))
	{
		return static::convertToRelativePath($first);
	}

	return '';
}
```

That works. But is it a good solution?

**Comment by joomdonation** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/35948 . Thanks !
