### ISSUE TITLE
Joomla-4.1 Installation error

### ISSUE THREAD

**Issue by pritam825** [joomla/joomla-cms#35953]
### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/54195688/139591867-ce76f130-162a-47ac-8d25-c913b5bf2cca.png)

**Comment by richard67** [comment]
Either you have not created a database and a database user, or the database name or the user name is wrong or the password is wrong.

**Comment by richard67** [comment]
P.S.: It seems you have used user name "pritam" for the super user and also for the database user. That would be ok, but for the database user it needs to create that user in the database e.g. with use of phpMyAdmin, and this user needs full privileges for the database which you want to use, and the user needs the privilege to connect to that database.

**Comment by Shubhamverma2796** [comment]
If you are still facing this issue, then refer to [this](https://www.youtube.com/watch?v=w312ogCUd00) video to see how to set up or change password from phpmyadmin.

**Comment by pritam825** [comment]
Thanks to all, actually I had filled all the things correct, but it wasn't taking my password, and password wasn't mandatory for the database so when I entered without password it's installed, Now issue is resolved thanks

**Comment by richard67** [comment]
Closing as not an issue with the CMS core.
