### ISSUE TITLE
Error uninstalling convertform - Erreur lors de la desinstallation de convertform

### ISSUE THREAD

**Issue by philigrane** [joomla/joomla-cms#35959]
### Steps to reproduce the issue
1 Install the component convertform for test
2 Uninstall the component convertform correectly from the backend![screen shot 2021-11-02 at 18 09 22](https://issues.joomla.org/uploads/1/d16258b6cff163a388b6cf3cfcc8b957.jpg)

### Actual result
error on all the backend and frontend (Une erreur est survenue - 0 Call to a member function isClient() on null)
Attached is a screenshot of the inspector. I'm not sure this is related.
### System information
Use the latest stable version of Joomla 4

**Comment by brianteeman** [comment]
Despite being advertised as Joomla 4 compatible the extension is not and you should contact the creator of the extension

**Comment by brianteeman** [comment]
or delete this folder plugins\system\convertforms and then you will be able to get back into the site and complete the uninstall

**Comment by philigrane** [comment]
Thank you that works. I had deleted all the others except this one.
I warn the developer. Good evening<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35959">issues.joomla.org/tracker/joomla-cms/35959</a>.</sub>

**Comment by richard67** [comment]
Closing as not an issue with the CMS core.
