### ISSUE TITLE
[4.0] [Workflow] Item type is not localized in the subject of the state change notification

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#35958]
### Steps to reproduce the issue
1. Use the latest stable version of Joomla.
2. Create a new user, add it to the administrators group (for example).
3. Enable workflows in the content settings.
4. Enable all plugins in the workflow group.
5. Go to the process transitions and, for example, for the "Publish" item in the notification settings, enable the "administrator" user group or a specific user created earlier.
![Screenshot_1](https://user-images.githubusercontent.com/8440661/139716823-627e2426-957c-4bd9-abbd-437a5d06b3ca.png)

6. Install any other language that is clearly different from en-GB.
7. Create an article, define it in the "Publish" transition.
8. The second created user will receive a private message informing that the state has changed. However, in the subject of the message - the type (in this case Article) will be in English, since these elements are not localized.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/139716892-347e1542-e224-442c-97d3-b3218ea68e60.png)

**Comment by brianteeman** [comment]
I can confirm the Subject is not correct. Can you also confirm please that the message is correct

**Comment by Kostelano** [comment]
Everything is in order in the message. Issue only deals with the topic of the notification.

**Comment by brianteeman** [comment]
I just wanted to double check

**Comment by Kostelano** [comment]
By the way, another Russian-speaking user received a notification with "Form" in the subject.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/139723279-3e6d7f2d-b041-406a-805c-f38e24151419.png)

**Comment by brianteeman** [comment]
same bug. I just don't know the fix

**Comment by chmst** [comment]
It is the model name. Can we translate the model name?

**Comment by brianteeman** [comment]
This is the relevant line https://github.com/joomla/joomla-cms/blob/ebd801ade267cfc367979972c7876480c6343248/plugins/workflow/notification/notification.php#L228

We translate the transitionName here
https://github.com/joomla/joomla-cms/blob/ebd801ade267cfc367979972c7876480c6343248/plugins/workflow/notification/notification.php#L213-L217

I tried the same `$lang->` but no luck

**Comment by chmst** [comment]
A simple solution would be:
Changeing the message and insert the title instead of the model name (is this a b/c break?).
"The status of "halloween 2021" has been changed" instead of "The status of an article has been changed"

Also possible but not my favourite: 
mapping all modelnames to Language strings
case $modelName == "article" 
      lang_key = "PLG_WORKFLOW_NOTIFICATION_ARTICLE"

**Comment by brianteeman** [comment]
I would go with option 1. Its not breaking anything (afaict) its just fixing a bug and improving the message

**Comment by chmst** [comment]
Please test #35960
