### ISSUE TITLE
Contacts/Categories 'There are no Contacts to display"

### ISSUE THREAD

**Issue by laybergerF** [joomla/joomla-cms#35965]
![screen shot 2021-11-04 at 15 34 28](https://issues.joomla.org/uploads/1/6aec73027115aefdd2859b50890729df.png)### Steps to reproduce the issue: Even with the 'There are no Contacts to display' option set to 'Hide' via the 'Contacts > Options > No Contacts Message' menu, the message is still being displayed for the first category.

**Comment by richard67** [comment]
@brianteeman Can it be that this is the same issue here for com_contacts as you had solved for com_content with PR #35894 ?

**Comment by brianteeman** [comment]
probably

**Comment by brianteeman** [comment]
I cannot replicate this. Please test and confirm the issue with cassiopeia

**Comment by laybergerF** [comment]
Okay, I'll try to get that done tonight.Sent from my T-Mobile 5G Device
-------- Original message --------From: Brian Teeman ***@***.***> Date: 11/4/21  1:25 PM  (GMT-07:00) To: joomla/joomla-cms ***@***.***> Cc: laybergerF ***@***.***>, Author ***@***.***> Subject: Re: [joomla/joomla-cms] Contacts/Categories 'There are no Contacts to display" (Issue #35965) 
I cannot replicate this. Please test and confirm the issue with cassiopeia

**Comment by laybergerF** [comment]
Sorry, it's take a little longer to respond than I expected. The message is not displayed using the Cassiopeia template with the 'Contacts > Contact > 'No Contacts Message'' option set to 'Hide'. Using the 't4_bs5_blank - Default' template the message is displayed for the first category even with the option set to 'hide'. Since this appears to be related to the t4 template, I'm going to contact its developer. Thank you for you help.

**Comment by richard67** [comment]
Thanks for reporting back. Closing as not a core issue.
