### ISSUE TITLE
Backend template and CSS file only loads when this is set: public $debug = true;

### ISSUE THREAD

**Issue by ptrouw** [joomla/joomla-cms#35964]
### Steps to reproduce the issue
Installed a new joomla installation, v4.0.4. /administrator didn't load any Template/CSS. With debug on it works as it should.
### Expected result
Loading off CSS file
### Actual result
Just text in administrator

### System information (as much as possible)
PHP gebouwd op	Linux 4.18.0-147.3.1.el7h.lve.1.x86_64 #1 SMP Wed Feb 12 07:03:11 EST 2020 x86_64
Databasetype	mysql
Database versie	10.4.21-MariaDB
Database collatie	latin1_swedish_ci
Collatie van de databaseverbinding	utf8mb4_general_ci
Database verbinding versleuteling	Geen
Databaseserver ondersteunt verbindingsversleuteling	Nee
PHP versie	7.4.25
Webserver	LiteSpeed
Webserver naar PHP interface	litespeed
Joomla! versie	Joomla! 4.0.4 Stable [ Furaha ] 24-October-2021 19:25 GMT
Gebruikersagent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.3

### Additional comments
Apache log file last line:
80.xxx.xx.xx - - [04/Nov/2021:13:24:57 +0100] "GET /media/mod_menu/js/admin-menu.min.js?387324d09eeb2005b99ae05abb4a84fc HTTP/1.1" 200 0 "https://www.xxx.xx/administrator/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/ Safari/537.36"

Error log: no entries

**Comment by dgrammatiko** [comment]
You're using Litespeed so you need to comment these lines in your htaccess: https://github.com/joomla/joomla-cms/blob/2e44061275b1ae4d7e1513ff879553a8f0037169/htaccess.txt#L134-L166

**Comment by ptrouw** [comment]
Thx a million. Works.
