### ISSUE TITLE
[4.0] com_contact icons settings error

### ISSUE THREAD

**Issue by reilldesign** [joomla/joomla-cms#35961]
### Steps to reproduce the issue

go to components » Contacts » Contacts and click Options. Select »Settings None« in the Icons tab.

### Expected result

show nothing

### Actual result

icons are shown

### System information (as much as possible)

Joomla 4.0.4
PHP Version 7.4.3
Web Server Apache

**Comment by brianteeman** [comment]
What are the settings for the menu item that you are accessing the contact in the front end

**Comment by reilldesign** [comment]
i'm using the Menu Item Type  Single Contact. there are no settings for icons in the Contact Display Options tab or the others.

**Comment by richard67** [comment]
@reilldesign ~~What do you mean with "icons"? A profile image? Or an icon for the menu item?~~

~~For the contact image it is sufficient to define an image for the contact and in the menu item options set "Contact Information" to be shown.~~

Seems I've misunderstood the issue first.

**Comment by richard67** [comment]
~~Or do you mean the icons beside address, phone, email and so on?~~

~~As far as I could see - but maybe I've missed something - they cannot be set individually for the single contact or the contact menu item, they can be only set in the options of the contact component.~~

Got it and can reproduce the issue.

**Comment by richard67** [comment]
@reilldesign If my last comment answers your questions let us know so we can close this issue, or close it yourself. Thanks in advance.

**Comment by brianteeman** [comment]
@richard67 That is **exactly** what is being described in the first post and the report is that it is NOT working and the icons are still being displayed

**Comment by brianteeman** [comment]
I can confirm the bug and am looking at the reason

**Comment by richard67** [comment]
@brianteeman Just wanted to type I can confirm.

**Comment by brianteeman** [comment]
This block of code (that works in j3) is not working in j4

https://github.com/joomla/joomla-cms/blob/2e44061275b1ae4d7e1513ff879553a8f0037169/components/com_contact/src/View/Contact/HtmlView.php#L253-L264

**Comment by brianteeman** [comment]
The problem was created by the changes made by @chmst in https://github.com/joomla/joomla-cms/pull/30985

**Comment by chmst** [comment]
Please test #35963
