### ISSUE TITLE
the showon feature for module fields does not work properly

### ISSUE THREAD

**Issue by cloudfaction** [joomla/joomla-cms#35968]
### Steps to reproduce the issue

try to add a showon property with more than 1 option:

showon="jn_val_type:18[OR]jn_val_type:11"

### Expected result

show only on the 2 options

### Actual result

it shows on all options

### System information (as much as possible)

J4 latest (4.04)/ own module.

### Additional comments

showon works with just one option, but as soon as i use OR or AND it does not work.

**Comment by dgrammatiko** [comment]
What's the input element/form field that holds `showon="jn_val_type:18[OR]jn_val_type:11"`?

**Comment by cloudfaction** [comment]
text field

<field name="jn_db_join_pk" type="text" label="DB Join pk" description="Set db join pk"  showon="jn_val_type:18[OR]jn_val_type:11"/><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35968">issues.joomla.org/tracker/joomla-cms/35968</a>.</sub>

**Comment by cloudfaction** [comment]
### <field name="jn_db_join_pk" type="text" label="DB Join pk" description="Set db join pk"  showon="jn_val_type:18[OR]jn_val_type:11"/><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35968">issues.joomla.org/tracker/joomla-cms/35968</a>.</sub>

**Comment by dgrammatiko** [comment]
And what type is the `jn_val_type`?

**Comment by cloudfaction** [comment]
that's a list. works like a charm in j3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35968">issues.joomla.org/tracker/joomla-cms/35968</a>.</sub>

**Comment by brianteeman** [comment]
This is used in multiple places in core

**Comment by dgrammatiko** [comment]
I can not replicate it, it works fine here. My test was on the footer module XML:
<details>
<summary>Code</summary>
```xml

<?xml version="1.0" encoding="utf-8"?>
<extension type="module" client="site" method="upgrade">
	<name>mod_footer</name>
	<author>Joomla! Project</author>
	<creationDate>July 2006</creationDate>
	<copyright>(C) 2006 Open Source Matters, Inc.</copyright>
	<license>GNU General Public License version 2 or later; see LICENSE.txt</license>
	<authorEmail>admin@joomla.org</authorEmail>
	<authorUrl>www.joomla.org</authorUrl>
	<version>3.0.0</version>
	<description>MOD_FOOTER_XML_DESCRIPTION</description>
	<namespace path="src">Joomla\Module\Footer</namespace>
	<files>
		<filename module="mod_footer">mod_footer.php</filename>
		<folder>tmpl</folder>
	</files>
	<languages>
		<language tag="en-GB">language/en-GB/mod_footer.ini</language>
		<language tag="en-GB">language/en-GB/mod_footer.sys.ini</language>
	</languages>
	<help key="Site_Modules:_Footer" />
	<config>
		<fields name="params">
			<fieldset name="advanced">
				<field
					name="layout"
					type="modulelayout"
					label="JFIELD_ALT_LAYOUT_LABEL"
					class="form-select"
					validate="moduleLayout"
				/>

				<field
					name="moduleclass_sfx"
					type="text"
					label="COM_MODULES_FIELD_MODULECLASS_SFX_LABEL"
					rows="3"
					validate="CssIdentifier"
					showon="jn_val_type:18[OR]jn_val_type:11"
				/>

				<field
					name="jn_val_type"
					type="list"
					label="test"
					>
					<option value="0">0</option>
					<option value="1">1</option>
					<option value="11">11</option>
					<option value="18">18</option>
				</field>

				<field
					name="cache"
					type="list"
					label="COM_MODULES_FIELD_CACHING_LABEL"
					default="1"
					filter="integer"
					validate="options"
					>
					<option value="1">JGLOBAL_USE_GLOBAL</option>
					<option value="0">COM_MODULES_FIELD_VALUE_NOCACHING</option>
				</field>

				<field
					name="cache_time"
					type="number"
					label="COM_MODULES_FIELD_CACHE_TIME_LABEL"
					default="900"
					filter="integer"
				/>

				<field
					name="cachemode"
					type="hidden"
					default="static"
					>
					<option value="static"></option>
				</field>
			</fieldset>
		</fields>
	</config>
</extension>
```
</details>

**Comment by cloudfaction** [comment]
for me this is inside a subform. see attached part of module xml file

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35968">issues.joomla.org/tracker/joomla-cms/35968</a>.</sub>

**Comment by cloudfaction** [comment]
[example.txt](https://issues.joomla.org/uploads/1/0eaec512432b4cea51139d350874f7d7.txt)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35968">issues.joomla.org/tracker/joomla-cms/35968</a>.</sub>

**Comment by dgrammatiko** [comment]
If you have mentioned that this was on a subform would be easier, so please be more specific when you describe a bug

**Comment by dgrammatiko** [comment]
@cloudfaction please test https://github.com/joomla/joomla-cms/pull/35972

**Comment by cloudfaction** [comment]
i downloaded the latest build (https://ci.joomla.org/artifacts/joomla/joomla-cms/4.0-dev/35972/downloads/48267/)  but showon.es6.js  was not in there... i have no local git environment to test. sorry i cannot test this for you.

**Comment by richard67** [comment]
@cloudfaction The file modified by this PR is the source file "build/media_source/system/js/showon.es6.js". in the package which you have downloaded, the compiled and minified files can be found in folder "media/system/js". These files are
- showon.js
- showon.min.js
- showon.min.js.gz
- showon-es5.js
- showon-es5.min.js
- showon-es5.min.js.gz

So if you unzip the full package which you have downloaded into some temporary folder and copy the files mentioned above from folder "media/system/js" in the unpacked package folder to the same folder "media/system/js" in your Joomla installation, of course having made a backup of these files before so you can later change back, then you can test the PR.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #35972 . Thanks in advance.
