### ISSUE TITLE
Menu item associations to other languages 

### ISSUE THREAD

**Issue by crimle** [joomla/joomla-cms#35979]
### Steps to reproduce the issue
Let's assume we have a Multi Language Webseite with at least two languages. 
We have a Main Menu in English and a Main Menu in German.
Each menu contains a number of menu items.
Now we want to associate each of the menu items to the corresponding menu item of the other language.
Open any menu item from the Main Menu in English. 
Go to the tab «Associations».
Click the «Select» button next to the corresponding language.
Use the search field in order to find the corresponding menu item of the other language.
Click the menu item of the search result.

### Expected result
The menu item should be transferred into the «Associations» dialogue.

### Actual result
The menu item is NOT transferred into the «Associations» dialogue. The text «- No association -» indicates that no association has been selected.
[screen shot 2021-11-06 at 10 48 44](https://issues.joomla.org/uploads/1/486583786e576d3c453fb8e24f978421.png)

### System information (as much as possible)
Joomla 4.0.4
PHP 7.4

### Additional comments
It works all right if you do NOT use the search field but select the corresponding menu item by scrolling manually.

**Comment by infograf768** [comment]
Can't reproduce here. All is fine
![assoc](https://user-images.githubusercontent.com/869724/140636212-791c17be-1a53-4e32-afaa-669e7360a56f.gif)
.

**Comment by crimle** [comment]
Thank you. So my issue must be related to the template I am using:

Template = tp_sport 1.3.4
Vendor = joomlaplates.com
Astroid Framework 2.5.4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35979">issues.joomla.org/tracker/joomla-cms/35979</a>.</sub>

**Comment by richard67** [comment]
@crimle Does it work for you if you switch to the standard template?

**Comment by crimle** [comment]
Yes it does. I am sorry, I should have tested with «Cassiopeia» before reporting this behaviour as a bug. This issue is obviously related to the Joomlaplates Template I am using resp. to the Astroid Framework 2.5.4. I just reported this bug to the Joomlaplates support team a couple of minutes ago.

**Comment by richard67** [comment]
> Yes it does. I am sorry, I should have tested with «Cassiopeia» before reporting this behaviour as a bug.

No problem. Thanks for reporting back.

**Comment by infograf768** [comment]
The demo above is independent from front-end template. Therefore it may be related to the framework indeed.
