### ISSUE TITLE
Character Countdown in Metadata

### ISSUE THREAD

**Issue by Cpointcc** [joomla/joomla-cms#35975]
### Is your feature request related to a problem? Please describe.
Yes, managing SEO from the core Joomla article is not user-friendly as you cannot see how many characters you are typing.

### Describe the solution you'd like
To have a character count feature in article metadata fields.  There are clear standards on character count for titles and descriptions.

**Comment by chmst** [comment]
There is a character count in meta data. 
![image](https://user-images.githubusercontent.com/1035262/140581672-d8e7572a-2a51-4933-9b4a-8c3964ae63ed.png)

Which Joomla Version have you?

**Comment by richard67** [comment]
With this PR character counting has been implemented in Joomla 4.0.0 for meta descriptions: #27804 . There is an open PR to add it for text fields, too, for Joomla 4.1.

**Comment by brianteeman** [comment]
This should be closed

**Comment by richard67** [comment]
@Cpointcc As stated above the feature is available in Joomla 4. So I‘m closing this issue. Beside this it is not really helpful if people create issues but are not responding to feedback or questions.

**Comment by Cpointcc** [comment]
Thank you for your replies.  Sorry I was out ill and not able to respond in a timely fashion.
