### ISSUE TITLE
[4.0] Hiding navigation removes fields which are to be displayed after content

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#35982]
### Steps to reproduce the issue
You need a field for articles, which is displayed after the content. Easy with Blog Sample Data, there you can use the article "About your website". 
![image](https://user-images.githubusercontent.com/1035262/140625436-f9c230c8-f253-45da-878e-06f0130bc589.png)

The field is placed below the pagination (it is not what I expected but seems to be accepted as it is unchanged since many years). 

Now go to the menu item which points to this article and set the parameter "show pagination" to "hide".

### Expected result
The navigation disappears, the field remains unchanged.

### Actual result
The field disappears with the navigation

![image](https://user-images.githubusercontent.com/1035262/140625546-6cf2c43f-df71-4398-8b64-bef90a45da01.png)

**Comment by brianteeman** [comment]
Do you mean Show Navigation not pagination

If so then I can't replicate this
![image](https://user-images.githubusercontent.com/1296369/140817236-a9bb6df5-ce05-4faa-bc6f-13a1e6f4426a.png)

![image](https://user-images.githubusercontent.com/1296369/140817268-210a8281-c2aa-4521-adc0-968bdad8921c.png)

**Comment by chmst** [comment]
Yes, sorry, it should be navigation.

If it works for you I will re-test with another data set and a fresh installation.

**Comment by brianteeman** [comment]
and I agree with you that the field should be above the navigation

**Comment by chmst** [comment]
re-tested in a new installation and it is ok. Closing this.
