### ISSUE TITLE
Joomla 3+4- Actionlog search does not work

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#36009]
### Steps to reproduce the issue
Have Actionlog activated
Change an article or category or whatever
Use the Search Box in the user Action log to find who changed article or category xyz

### Expected result
Search should show a list of actions that have been done to the object you search

### Actual result
Search does not find anything altough its there

### System information (as much as possible)
Happens in Joomla 4 and in 3

**Comment by brianteeman** [comment]
What exactly is your search term?

> Search in username. Prefix with ID: to search for an actionlog ID. Prefix with ITEM_ID: to search for an actionlog item ID.

I just did a quick test of the above in J3 and it seemed to work ok

**Comment by coolcat-creations** [comment]
Example:
![grafik](https://user-images.githubusercontent.com/828371/141307474-bd35b18f-9d9f-4ab4-aa25-0590131e3c7b.png)


![grafik](https://user-images.githubusercontent.com/828371/141307413-310511ce-63ef-40ea-b971-a1af8c63d676.png)

**Comment by coolcat-creations** [comment]
Second example

![grafik](https://user-images.githubusercontent.com/828371/141307611-69e13089-9f9d-4892-aeb2-9f43e34dfe4e.png)
![grafik](https://user-images.githubusercontent.com/828371/141307702-c0d6e295-d531-43fc-b28e-c4b0a337c712.png)

**Comment by brianteeman** [comment]
Rightly or wrongly that would be the expected behaviour according to the information.

> Search in username. Prefix with ID: to search for an actionlog ID. Prefix with ITEM_ID: to search for an actionlog item ID.

**Comment by ChristineWk** [comment]
confirm last images.
hv tried another action. maybe compromise

![screen shot 2021-11-11 at 14 42 20](https://issues.joomla.org/uploads/1/96e911679982b441d9393e44c7124902.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36009">issues.joomla.org/tracker/joomla-cms/36009</a>.</sub>

**Comment by richard67** [comment]
> Rightly or wrongly that would be the expected behaviour according to the information.
> 
> > Search in username. Prefix with ID: to search for an actionlog ID. Prefix with ITEM_ID: to search for an actionlog item ID.

Then I would say this issue should be closed as expected behavior or be changed to a feature request.
