### ISSUE TITLE
Menu Item alias in URL config options

### ISSUE THREAD

**Issue by RedDustSnow** [joomla/joomla-cms#36001]
### Steps to reproduce the issue
On a fresh 4.0.4, created a new menu item, but no options for SEF & alias configuration (See Pic 1)

![screen shot 2021-11-10 at 01 28 09](https://issues.joomla.org/uploads/1/15dfd698b74907b2f36576b717ba269d.jpg)

### Expected result
When creating a new menu item, there are options (to the right of the alias field) that allow urls derived from the menu item alias to be relative or direct, inherited or not inherited.

On another 4.0.4 website, that was a J3.10 > J4.0, they are present

See the second picture.

![screen shot 2021-11-10 at 01 28 43](https://issues.joomla.org/uploads/1/628d4b59fa1127ba866a58629d38de53.jpg)

### Actual result

No options for url (alias) configuration and sef URL's created not fully sef 

**### System information** (as much as possible)
PHP Built On	Linux 681963.cloudwaysapps.com 5.14.2-x86_64-linode147 #1 SMP Wed Sep 8 15:00:46 EDT 2021 x86_64
Database Type	mysql
Database Version	10.4.20-MariaDB-1:10.4.20+maria~stretch-log
Database Collation	utf8mb4_general_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	Yes
PHP Version	7.4.25
Web Server	Apache/2.4.25 (Debian)
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 4.0.4 Stable [ Furaha ] 24-October-2021 19:25 GMT

* Note, the same config as the migrated 4.0.4 that works as expected.

### Additional comments
Confused about this one.

Simon!

**Comment by brianteeman** [comment]
Those options are from an extension and not from core

**Comment by RedDustSnow** [comment]
Thanks, Brian.... that is bizarre as I am not running anything I could attribute to that.

Sorry for the bother.... <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36001">issues.joomla.org/tracker/joomla-cms/36001</a>.</sub>

**Comment by chmst** [comment]
As this is not related to Joomla core, I close the issue
