### ISSUE TITLE
[4.0][Cassiopeia] max-width is overwritten

### ISSUE THREAD

**Issue by reilldesign** [joomla/joomla-cms#36002]
### What needs to be fixed

in the template.min.css file the max-width value of the class .grid-child is overwritten by the class .site-grid > [class*=" container-"] (screenshot) and leads to a wrong width (screenshot). removing the property max-width: none; fixes the problem. unfortunately i can't estimate if it leads to other problems. in my case everything fits.

### Why this should be fixed

leads to a wrong width (screenshot).

### How would you fix it

removing the property max-width: none; fixes the problem.

### Side Effects expected

i can't estimate if it leads to other problems.

Screenshots:

<img width="424" alt="template-min-css" src="https://user-images.githubusercontent.com/43771555/141105029-572df28b-6a27-449b-a6b7-c1697a23dca3.png">
<img width="480" alt="max-width-none" src="https://user-images.githubusercontent.com/43771555/141105033-6e706049-be2d-4791-a845-7607117fb88e.png">

**Comment by brianteeman** [comment]
What makes you think it is wrong?  Please provide some screenshots (not of the code)

**Comment by reilldesign** [comment]
<img width="480" alt="141105033-6e706049-be2d-4791-a845-7607117fb88e" src="https://user-images.githubusercontent.com/43771555/141129796-c55f22a9-a9db-4d36-abec-f1f50af501dc.png">

the grid container has  a larger width (1329.6px) than, for example, the footer (1320px)

**Comment by brianteeman** [comment]
What makes you think it is wrong? Please provide some screenshots (not of the code)

**Comment by reilldesign** [comment]
screenshot which shows the different widths

<img width="1440" alt="different-widths" src="https://user-images.githubusercontent.com/43771555/141134885-feba14d7-5f43-4766-9f4f-7ff8013c2a42.png">

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/141151913-2b9de2ba-888b-4082-9983-376ff6c37d25.png)

![image](https://user-images.githubusercontent.com/1296369/141151980-fa398f0d-d63b-4ebf-9efd-14047d83474b.png)

**Comment by chmst** [comment]
This is a wrong assumption. 
The definitions in casssiopeia css  are made for cassiopeia. 
If  you need other definitions in your template, you can override css definitions in your user.css. 

This is no issue of Joomla, so I close this one.
