### ISSUE TITLE
Unable to see field groups/custom fields as a Super User

### ISSUE THREAD

**Issue by MrMalkio** [joomla/joomla-cms#36008]
### Steps to reproduce the issue
I don't know how to recreate the issue

### Expected result
filed group tabs be visibile when editing the custom fields via back end in article editor.

### Actual result
When creating the article initially the field groups are available, but after saving the field group tabs are not visible, it's as if they don't exist. 

[Here is a video](https://www.awesomescreenshot.com/video/5966192?key=8c8c1626b5c7e9f3aaa60962d8a2095a&fbclid=IwAR0CZxlG_zRebfqRESihRx5shA5s9ZJOuV9EfDz_RxeFFe4Ifa_9fi6wzak) 

### System information (as much as possible)

PHP Built On	Linux a2plcpnl0457.prod.iad2.secureserver.net 2.6.32-954.3.5.lve1.4.86.el6.x86_64 #1 SMP Tue Aug 31 17:08:39 UTC 2021 x86_64
Database Type	mysql
Database Version	5.6.51-cll-lve
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	No
PHP Version	7.4.23
Web Server	Apache
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 4.0.4 Stable [ Furaha ] 24-October-2021 19:25 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.69 Safari/537.36

### Additional comments
Please see video

**Comment by chmst** [comment]
Have you set the parameter  "Editable in" to both or administrator?
![image](https://user-images.githubusercontent.com/1035262/141268098-6aa2f9b1-b237-4f6d-a72d-f1546d24fb0b.png)

**Comment by brianteeman** [comment]
There really isnt enough information in the video. If you can provide access to the site then it will be quicker to diagnose

**Comment by brianteeman** [comment]
As you stated on facebook that you have now wiped the install you can not provide further information so this should be closed

**Comment by chmst** [comment]
Thanks for the information. I still think that the param for "Editable in" was not set. Close this for now.
