### ISSUE TITLE
Open administrator/index.php?option=com_installer&view=discover writes extensions automatically !

### ISSUE THREAD

**Issue by JProof** [joomla/joomla-cms#36007]
I have download a package with component ..plugins and so on.
This is not my component. But playing around with joomla to find Joomla-Bugs and strange behaviours. 

### Steps to reproduce the issue

* Remove from all entries from  extensions table they are named as in screenshot
* ![img-2021-11-10-22-07-02](https://user-images.githubusercontent.com/12245927/141193572-33b122e3-1503-4730-996f-25b049427536.png)
* removed from table: 
![img-2021-11-10-22-08-07](https://user-images.githubusercontent.com/12245927/141193699-9745bd4d-91ac-4667-acc4-14c8ef3beff8.png)
* open with GET /administrator/index.php?option=com_installer&view=discover
* Displays in backend: 
![img-2021-11-10-22-09-53](https://user-images.githubusercontent.com/12245927/141193920-36ad2071-bec6-4604-aeca-f6ba263f9ba1.png)
* also in database again without "Clicking" 
![img-2021-11-10-22-11-21](https://user-images.githubusercontent.com/12245927/141194061-6c9e7ae1-b4a2-4351-8717-0eaf4ca3de0d.png)

### Expected result

No writing to database without clicking "install" 

### Actual result

Writes to Database!

### System information (as much as possible)

Joomla! 4.0.4
every system

### Additional comments

that is really strange!

**Comment by brianteeman** [comment]
This is expected and intentional behaviour

It is showing that the extensions have been discovered and are available for you to install. If you look at the database table you will see that they have enabled = 0

**Comment by alikon** [comment]
closed as expected behaviour
