### ISSUE TITLE
Remove hard-limit of 20 to the Module Tags-Popular list size

### ISSUE THREAD

**Issue by pwireless** [joomla/joomla-cms#36016]
### Steps to reproduce the issue

Create new Module Tags-Popular. It's not allowed to show more than 20 tags.

### Expected result

Show more than 20 tags. Have a high limit e.g. 500.

**Comment by alikon** [comment]
you can change the default max here https://github.com/joomla/joomla-cms/blob/4.0-dev/modules/mod_tags_popular/mod_tags_popular.xml#L43

**Comment by brianteeman** [comment]
It wouldnt be "popular" tags if there were 500

**Comment by chmst** [comment]
In other modules (polular articles, most read articles) we use type=number and leave it to the user how many itemshe wants to see.

**Comment by brianteeman** [comment]
It has had a maximum of 20 since  Elin introduced the code 9 years ago - just saying

**Comment by HLeithner** [comment]
I see no technical reason for the limit. if you write a pull request to remove this restriction I would support it.

**Comment by chmst** [comment]
Please test #36019

**Comment by richard67** [comment]
@chmst Why reopened? Isn't there a pull request which claims to fix it?

**Comment by Quy** [comment]
@richard67 it was reopened before #36261.

**Comment by richard67** [comment]
Ah … ok.

Closing as having a pull request. Please test #36261 . Thanks in advance.
