### ISSUE TITLE
[J4] Call to undefined function YOOtheme\app()

### ISSUE THREAD

**Issue by Krshivam25** [joomla/joomla-cms#36012]
### Steps to reproduce the issue
I am migrating the Joomla 3.10 website to Joomla 4.0.
On the home page, this issue occurs.
![issue](https://user-images.githubusercontent.com/49578630/141320549-b9f14cee-9131-444c-b7c1-fd63e948064c.jpg)

### Expected result
The dashboard should run properly

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/35380

**Comment by Fedik** [comment]
It YOOtheme issue, I suspect that installed version not compatible with 4.x.
Not Joomla issue.
