### ISSUE TITLE
URL's in embedded google maps (in marker) does not work in J4

### ISSUE THREAD

**Issue by Hans-63** [joomla/joomla-cms#36022]
URLs in embedded google maps does not work in J4

The insertion of a google map in the website works the same as in Joomla3, however urls that are included in a marker will open the desired page in J3 neatly, but in J4 this results in an error message from google.
Example in J3: https://www.htm63.com/joomla3/in-english/our-properties-on-the-map
Example in J4: https://www.htm63.com/index.php/in-english/our-properties-on-the-map

The actual code is with copy/paste copied from J3 to J4... Used code : 

```html
<p><iframe src="https://www.google.com/maps/d/u/0/embed?mid=1QTZ6vr8usIwVnv5tbQgW1veaokxw_80c" width="937" height="937"></iframe></p>
```

What to do to get this working as simple as possible!

Thanks in advance.

Hans

**Comment by Knight1354** [comment]
Hey there,
I studied the issue but I found nothing unusual in the anchor tag. To solve the problem we should use the onclick function on 
anchor tag.

**Comment by HLeithner** [comment]
@Hans-63 can you please try to disable the "System - HTTP Header" plugin. I don't think that's this is the reason but I see not much difference that can effect the google script in the iframe.

Google attaches 3 on click event handlers and one of them causes this error.

**Comment by Hans-63** [comment]
@HLeithner : Great!! thanks a lot for this tip.... After disabeling the plugin it works as wanted.
