### ISSUE TITLE
Backend Module to Play Audio Files in a Folder

### ISSUE THREAD

**Issue by pwireless** [joomla/joomla-cms#36028]
### Is your feature request related to a problem? Please describe.

Currently in the backend there is the "Random Image" module, that displays a random image from a chosen folder.

Similar feature is requested but instead of showing image, play audio files from a chosen folder.

### Describe the solution you'd like

Create a new backend module, that plays audio files from a chosen folder.

The module could play the files in order, or randomly.

A play/pause button should be needed.

(If the module has next/previous track buttons, and current playing title, would be great)

**Comment by HLeithner** [comment]
I'm pretty sure there is a module in the JED.

**Comment by chmst** [comment]
This is a rather specific request and the job for extension developers.

**Comment by chmst** [comment]
Closing as it is not an issue for Joomla core.
