### ISSUE TITLE
PostCSS should be updated

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#36038]
While using the npm-scss feature, I noticed that template.min.css was not updated (template.css was though).
Reading the error message, I figured out it was related to an outdated PostCss Version (ie 7.xx).
Updating PostCss to 8.x in package.jon:
```
"devDependencies": {
...
"postcss": "^8.3.11",
```
resolved the issue.

**Comment by HLeithner** [comment]
please create a pull request.

**Comment by rdeutz** [comment]
closed because we have a PR
