### ISSUE TITLE
Path error in Joomla Docs Article: SCSS and Sass

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#36037]
In article: 
SCSS and Sass
https://docs.joomla.org/J4.x:SCSS_and_Sass

Chapter:
#How to re-generate the CSS style sheets
We are invited to run:
``` 
node build --compile-css
``` 
However, in package.json, we have:
``` 
node build/build.js --compile-css
```
which is the correct command (the one that works).

This one works too:
``` 
npm run build:css
```

**Comment by dgrammatiko** [comment]
@ghazal the docs in this repo should be correct: https://github.com/joomla/joomla-cms/tree/4.0-dev/build You can update the Wikimedia docs using the info in this PR

**Comment by AJAY007L** [comment]
`npm run build:css`
This one is correct as it is also written in https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment while setting up the project locally.

**Comment by AJAY007L** [comment]
> @ghazal the docs in this repo should be correct: https://github.com/joomla/joomla-cms/tree/4.0-dev/build You can update the Wikimedia docs using the info in this PR

Hello sir , where is the exact location of wikimedia docs ?
Also sir, I am beginner. 
Can you tell me about some beginner friendly issues so that i can start contributing?

**Comment by Shubhamverma2796** [comment]
I have changed the documentation from node build --compile-css to npm run build:css 
please verify.

**Comment by ghazal** [comment]
Tks

**Comment by Quy** [comment]
@ghazal Please close if this has been resolved. Thanks.

**Comment by ghazal** [comment]
Sorry. Closing.
