### ISSUE TITLE
[4.1] npm packages installation error

### ISSUE THREAD

**Issue by Krshivam25** [joomla/joomla-cms#36052]
I have install npm package using npm run command and added the dependency in settings.json file but this error is coming
![npm ci](https://user-images.githubusercontent.com/49578630/141778659-cb6efd47-a642-44e5-a326-4f6cd478b42e.jpg)

**Comment by brianteeman** [comment]
and did you do what the error message says?

**Comment by Krshivam25** [comment]
I run npm install <npm package> the package.lock.json get loaded with 10000+ lines

**Comment by brianteeman** [comment]
and do you then get that error message?

**Comment by brianteeman** [comment]
Adding  "mousetrap": "^1.6.5", to package.json and then `npm install` completed successfully for me. 

Whatever the problem is thaty you are facing it is nothing to do with joomla and all to do with your own npm installation

**Comment by Krshivam25** [comment]
@brianteeman can you please share where you added the npm packages inside the settings.json file

**Comment by brianteeman** [comment]
oh boy you have a lot of mistakes there. always try to learn from the example of other similar sections of the code. that is what I do.

![image](https://user-images.githubusercontent.com/1296369/141963648-a029375d-e4d7-4996-b99f-5fb28a311a3c.png)

**Comment by Krshivam25** [comment]
This is resolved thank you so much for this.
