### ISSUE TITLE
[J4] Subheader toolbar not visible on certain screensizes

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#36069]
### Steps to reproduce the issue
Open the back-end to any page that uses the toolbar on a screen with a view-port width between 992px and 576px inclusively.

### Expected result
The toolbar is visible and accessible to Save, Close, etc.

### Actual result
The toolbar is not visible until either the page is resized (either but resizing the window on desktop or swapped between landscape/portrait on mobile) or the page is dragged down on mobile.

**Comment by Quy** [comment]
Duplicate #34695?

**Comment by Chaosxmk** [comment]
Yeah, it's a duplicate issue. Couldn't find that one. Closing.
