### ISSUE TITLE
[4.0][B/C Change] Plugin event names - documentation

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#36062]
Hi,

I didn't find any information about this issue:

https://github.com/joomla/joomla-cms/issues/20966#issuecomment-403520907

in

https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4

If it is not, it would be good to add it, this can be very useful information for developers.

In Short:

Plugin events with name, which does not start with "on" work in Joomla 3 but do not work in Joomla 4 (no error or warning message, plugin event is just ignored).

Each Joomla plugin event function where the name does not start with "on" needs to be changed to name starting with "on".

This does not affect only function in plugins but even the call in extensions.

Plugin:
FROM:
`public function SpecificPluginGroupBefore...`
TO:
`public function onSpecificPluginGroupBefore...`

Extension
FROM:
`Factory::getApplication()->triggerEvent('SpecificPluginGroupBefore...' `
TO:
`Factory::getApplication()->triggerEvent('onSpecificPluginGroupBefore ...'`

I still didn't find the reason why this convention was not strict in J3 but in J4, but at least it will be great to document it for other developers starting to overwrite their extension.

**Comment by HLeithner** [comment]
Thanks for finding this, it would be great if you could update the documentation too.

**Comment by PhocaCz** [comment]
Done

**Comment by alikon** [comment]
thank you

p.s 
close the issue then :smiley:

**Comment by akfaisel** [comment]
I was wasting half of the day "on" this issue.
