### ISSUE TITLE
Error Invalid Field When Saving Users Options

### ISSUE THREAD

**Issue by aboarken** [joomla/joomla-cms#36067]
### Steps to reproduce the issue
I am getting an error message whenever I make or I don't make any change/s to users options. I click on save then an error message shows in red.

### Expected result
Its not supposed to throw that error.

### Actual result
Invalid Field: Minimum Characters is shown every time I click on save "Users: Options" as shown in the picture below:

![Invalid Field Issue While Saving](https://user-images.githubusercontent.com/18500882/142061871-ac072af8-d27c-4170-abcf-bb423660a207.png)

### System information (as much as possible)
Joomla Version 4.0.4

**Comment by Quy** [comment]
Under `Password Options` tab, what is the value for `Minimum Characters`?

**Comment by alikon** [comment]
that message is issued only when _Minimum Characters_  is less than 8 and it is expected behaviuor

**Comment by brianteeman** [comment]
#36072 should reduce the confusion

**Comment by alikon** [comment]
please test #36072

**Comment by aboarken** [comment]
Thanks everyone.
