### ISSUE TITLE
Files uploaded via ftp client with UTF8 diacritics

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#36061]
### Steps to reproduce the issue
1. Upload image with special charaters with czech letter(or special letters), via Total Commander, Filezilla etc.
2. In admin, make new article and then open in tinymce editor CMS Content / Media and select that image with czech letters
3. Save that article

### Expected result
Saving that article.

### Actual result

500: whooops

/www/libraries/vendor/joomla/string/src/phputf8/mbstring/core.php (line 96)
or www/libraries/vendor/joomla/filter/src/InputFilter.php (line 277)

Error: Maximum execution time of 60 seconds exceeded

### System information (as much as possible)
PHP 7.4.4
Joomla 4.0.4

### Additional comments
When you upload image via Media in admin, everything goes well. It will rename special letters.

I dont see this as an error/bug, but maybe there is a way to let user know, where exactly is the problem. In the name od that uploaded(via FTP) image/file with special letters.

Try this in article content and you will see

<p>testovaci tšext </p>
<p><img src="images/fotogalerie/fototemata/2021/06/Keř2.jpg" width="1024" height="768" loading="lazy" data-path="local-images:/fotogalerie/fototemata/2021/06/Keř2.jpg" /></p>

**Comment by PhilETaylor** [comment]
Also related https://github.com/joomla/joomla-cms/issues/36053

**Comment by Hackwar** [comment]
Thank you for reporting this issue and sorry that it took so long to give you some feedback. I tried your instructions and could not replicate this anymore. The code at the lines you gave has since changed and hopefully has been fixed. Because of that, I'm closing this issue now. If you still encounter this problem, please open a new issue. Thank you!
