### ISSUE TITLE
Since 4.0.4 - HtmlView.php return undefined variables

### ISSUE THREAD

**Issue by rflieb13** [joomla/joomla-cms#36075]
### Steps to reproduce the issue
Updated Joomla version from 4.0.3 to 4.0.4
Installed DJ-Image Slider v4.2

Entered DJ Image slider > Categories
and got 3 Notices about undefined variables

### Expected result
No Warnings, Notices, Erros

### Actual result
Notice: Undefined variable: ref_key in /Users/#USR#/Sites/#sitename#/_joomla4_final/administrator/components/com_categories/src/View/Categories/HtmlView.php on line 302

Notice: Undefined variable: url in /Users/#USR#/Sites/#sitename#/_joomla4_final/administrator/components/com_categories/src/View/Categories/HtmlView.php on line 318

Notice: Undefined variable: url in /Users/#USR#/Sites/#sitename#/_joomla4_final/administrator/components/com_categories/src/View/Categories/HtmlView.php on line 328

### System information (as much as possible)
PHP 7.4.21

### Additional comments

on using the HtmlView.php from previous version everything was fine again - but I doubt that with the next update it will be overwritten again...

**Comment by joomdonation** [comment]
Please try to use latest code from https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_categories/src/View/Categories/HtmlView.php , it should fix your issue. It will be part of next release, so you won't have to worry about it on next update.

**Comment by rflieb13** [comment]
That was a quick one 

Thank you very much!

Best
Ralf

**Comment by Quy** [comment]
Fixed in #35662.
