### ISSUE TITLE
Custom Error Page redirect problem

### ISSUE THREAD

**Issue by DD-Webentwicklung** [joomla/joomla-cms#36070]
### Steps to reproduce the issue
hidden menu -> error-404.html, link to sp pagebuilder page.

Custom Error php in template folder. 
case for two languages de / en and default - if error 404 - redirect to /error-404.html

### Expected result
redirect if wrong url  to: /error-404.html
in J3 worked

### Actual result
blog-detail page: wrong url -> redirect to /error-404.html
all other pages: redirect with code 200 to mainpage - no error.

### System information (as much as possible)
all SEO-options enable.
Newest J4 release, Sp Pagebuilder. 

error php:
<?php
header("HTTP/1.0 404 Not Found");
defined( '_JEXEC' ) or die;
	// variables
use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Uri\Uri;

	if (($this->error->getCode()) == '404') {	
		switch ($lang->get('tag')){
			case 'de-DE':
				header('Location: /error-404.html');
				exit;
			break;
			case 'en-GB':
				echo 'en';
				die();
			break;	
			default:
				header("Location: /error-404.html");
				die();
			break;
		}
	}
?>

**Comment by michelwaechter** [comment]
I had the same situation, hope you can fix it. @joomla-cms-bot

**Comment by ReLater** [comment]
I can't confirm this issue while using Joomla 4 core installation:

- Created file `JoomlaRoot/error-404.html`
```
Blaubbbbbbbb Balb Blabbbb
```

- Changed error.php of cassiopeia to

```
<?php
defined('_JEXEC') or die;

use Joomla\CMS\Factory;

$app = Factory::getApplication();
$lang = Factory::getLanguage();

header("HTTP/1.0 404 Not Found");

if ($this->error->getCode() == '404')
{
    switch ($lang->get('tag')){
        case 'de-DE':
            header('Location: /error-404.html');
            die();
        break;
case 'en-GB':
            header("Location: /error-404.html");
            die();
        break;
        default:
            header("Location: /error-404.html");
            die();
        break;
    }
}
```
- Entered a not existing URL in browser.
- and see `Blaubbbbbbbb Balb Blabbbb` in browser => redirection to `error-404.html` works.

**Comment by DD-Webentwicklung** [comment]
hidden menu -> custom error page with sp-pagebuilder. in J3 there was no need to put a error.html in root, just redirect to a link from joomla menu. this routing dont work in j4.

**Comment by ReLater** [comment]
Changed my test case:
- Created a Joomla menu item with alias `error` (first level menu item). Hidden in menus.

![grafik](https://user-images.githubusercontent.com/20780646/142404597-49f34a53-59df-45eb-82ac-38f82d1fed01.png)

- Changed SEO settings in configuration
![grafik](https://user-images.githubusercontent.com/20780646/142404829-59ecdedb-184e-4579-830e-7a1082cf7ce2.png)

- Adapted my code in `error.php` **Because you told us in german forum that your Joomla is inside a subfolder** without custom domain now with `Uri`.

```
<?php
defined('_JEXEC') or die;

use Joomla\CMS\Factory;
use Joomla\CMS\Uri\Uri;

$app = Factory::getApplication();
$lang = Factory::getLanguage();

header("HTTP/1.0 404 Not Found");

if ($this->error->getCode() == '404')
{
	switch ($lang->get('tag')){
		case 'de-DE':
			header('Location: ' . Uri::root(true) . '/error.html');
			die();
		break;
			header('Location: ' . Uri::root(true) . '/error.html');
			echo 'en';
			die();
		break;
		default:
			header('Location: ' . Uri::root(true) . '/error.html');
			die();
		break;
	}
}
```

- redirection works as expected when I call an invalid url

![grafik](https://user-images.githubusercontent.com/20780646/142405286-266f737b-30d1-48f9-a1a0-769058d914e0.png)

- So this seems not to be a Joomla 4 core issue.

**Comment by DD-Webentwicklung** [comment]
i changed the subfolder to root. so the page is direct accessible. unicode aliase -> on please. 
error.html or error-404.html.. simply dont matter. also tried the real link: index.php?option...
pls check mail.

**Comment by chmst** [comment]
Which mail?

**Comment by Fedik** [comment]
To get correct routing to menu item use `Route::_('index.php?Itemid=111')` where 111 is ID of your menu item.

Please ask more for support on a forum.
I closing this, it not looks like Joomla issue, but some problem with your code.

**Comment by DD-Webentwicklung** [comment]
i asked on a forum thx. seems nobody can explain routing in j4. code is posted so everybody can modify and test my code :) thx for closing. its a joomla issue cause: blog detail works, blog page not. needs just time till someone find the bad routing.. i'll wait.
