### ISSUE TITLE
Ldap auntification not work

### ISSUE THREAD

**Issue by DoctorDeatch** [joomla/joomla-cms#36074]
### Steps to reproduce the issue
activated and configured the plugin as in version 3 

### Expected result
passing authorization 

### Actual result
The username or password was entered incorrectly, or such an account does not exist. 

### System information (as much as possible)
{"host":"10.2.1.3","port":389,"use_ldapV3":1,"negotiate_tls":0,"ignore_reqcert_tls":0,"no_referrals":0,"auth_method":"search","base_dn":"dc=itgroup,dc=local","search_string":"sAMAccountName=[search]","users_dn":"","username":"ldap@i.local","password":"AhqM5","ldap_fullname":"displayName","ldap_email":"mail","ldap_uid":"uid","ldap_debug":0}

### Additional comments
plugin settings are made in the same way as for version 3. Websites work on one server

**Comment by HLeithner** [comment]
I hope this is not your real password, if it is you should change it.

Sadly I have no ldap implementation to test, but since we use the symfony package in j4 I would expect that it should work better then in j3...

**Comment by brianteeman** [comment]
@hleithner there are a LOT of open issues that the ldap plugin does not work in j4

**Comment by PhilETaylor** [comment]
> I would expect that it should work better then in j3...

I would expect the total opposite. LDAP support in Joomla 4 is broken, unusable and requires a complete rewrite with input from real world users that use LDAP along with its myriad of configurations, with and without SSL/TLS.

 - https://github.com/joomla/joomla-cms/issues/35571
 - https://github.com/joomla/joomla-cms/issues/35573
 - https://github.com/joomla/joomla-cms/issues/25434
 - https://github.com/joomla/joomla-cms/issues/35316
 - https://github.com/joomla/joomla-cms/issues/35216

 - https://github.com/joomla/joomla-cms/pull/35323
 - https://github.com/joomla/joomla-cms/pull/32400
 - etc...

**Comment by HLeithner** [comment]
so, then it's good that we switched... still can't fix it because I don't have a setup for this, the last time I fixed a security issue in our ldap package took me a long time to build a working setup... if someone can help out It would be very appreciated .

**Comment by PhilETaylor** [comment]
I'm in bed but if you search github you will find my very documented set up of ldap in a docker container 

but the problem with that is that in the real world there are a million different configurations - this is why it's best tackled by someone with in-depth access and experience with live ldap servers 

I tried my best before but a lot has changed and right now it's all pretty much broken

**Comment by PhilETaylor** [comment]
See https://github.com/joomla/joomla-cms/issues/35216#issuecomment-901286023

**Comment by HLeithner** [comment]
that's exactly the problem, running a documented container form the internet doesn't solve anything you have to understand ldap... I tried and hated it and gave up... (after the fix^^)

**Comment by HLeithner** [comment]
the alternative could be to switch pack to the joomla-framework v1 version... (I know not the best solution)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37959 . Thanks in advance.
