### ISSUE TITLE
Filtering Articles by Tags in Menu Category Blog

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#36073]
### Steps to reproduce the issue
1. Create Tags items for example 1 and 2
2. Create root Category and several subcategories
3. Create several Articles in each Category and assign them one Tags item (1 or 2)
4. Create a Menu item with Menu Item Type = Category Blog (or Category List), Choose a Category = root Category and Tags = 1
5. Open this Menu in front

### Expected result

- only subcategories are displayed in which the Articles with Tag 1
- empty subcategories are not displayed that do not contain Articles with Tag 1
- correct count of Articles is displayed in the category (only with Tag 1)

### Actual result

- all subcategories are displayed, even if there are no Articles with Tag 1 (empty subcategories in this case)
- incorrect count of Articles is displayed in the category (all Artcles, even if there are Articles without Tag 1)

**Comment by chmst** [comment]
Sorry for this later reply! Was your issue for Joomla 3 or Joomla4? Meanwhile there were so many fixes that your issue could be already resolved. So please let us know which version.

**Comment by 1inkin** [comment]
Joomla 4.1.3
the problem is still relevant<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36073">issues.joomla.org/tracker/joomla-cms/36073</a>.</sub>

**Comment by 1inkin** [comment]
screenshots for clarity
![screen shot 2022-05-19 at 05 40 50](https://issues.joomla.org/uploads/1/c96c8cc676c5e55bca25d67f081ee467.jpg)![screen shot 2022-05-19 at 05 40 52](https://issues.joomla.org/uploads/1/08420601f11cac5371ddba36354ff22b.jpg)![screen shot 2022-05-19 at 05 40 52](https://issues.joomla.org/uploads/1/642d1386e336dec92e10f0a141a544e4.jpg)![screen shot 2022-05-19 at 05 40 52](https://issues.joomla.org/uploads/1/f8cb5e6a200026bf45647b22c305c711.jpg)![screen shot 2022-05-19 at 05 40 52](https://issues.joomla.org/uploads/1/28a5a1cc39bf6086063593d419c3dba0.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36073">issues.joomla.org/tracker/joomla-cms/36073</a>.</sub>

**Comment by 1inkin** [comment]
Joomla 4.1.4
the problem is still relevant<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36073">issues.joomla.org/tracker/joomla-cms/36073</a>.</sub>

**Comment by brianteeman** [comment]
I've looked into this and the problem is that the count takes place on a query before the query with the filter. It will require quite a major rewrite to change that. Chosing not to display the article count will help to reduce the problem (at least until there are 0 articles with the matching tag).

**Comment by 1inkin** [comment]
i hope this will be fixed soon. on my site, this causes a serious inconvenience, as many empty categories are displayed in different sections of the site<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36073">issues.joomla.org/tracker/joomla-cms/36073</a>.</sub>

**Comment by 1inkin** [comment]
Joomla 4.2 RC1
the problem is still relevant<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36073">issues.joomla.org/tracker/joomla-cms/36073</a>.</sub>
