### ISSUE TITLE
Template Module Positions Not Displaying All Positions

### ISSUE THREAD

**Issue by philowantage** [joomla/joomla-cms#36071]
### Steps to reproduce the issue
Under the Template: Options there is a selection for Preview Module Positions. When this is Enabled and the URL of the site is appended with ?tp=1, all positions should be displayed even if there are no modules loaded into them.

### Expected result
All positions should be displayed.

### Actual result
Casiopeia has 16 positions, but only 5 are displayed when no modules are loaded on the page. i.e. topbar, below-top, breadcrumbs, main-top, main-bottom and debug.

### System information (as much as possible)
Under normal operation templates use the countModules() function to decide if a module position should be displayed.

### Additional comments
There is no point in the Position Preview if you can't see everything. i.e. All 16 positions in Casiopeia.

**Comment by brianteeman** [comment]
For reference the pull request that should make this work was https://github.com/joomla/joomla-cms/pull/29521

**Comment by brianteeman** [comment]
The PR that broke the behaviour was https://github.com/joomla/joomla-cms/pull/35225 and specifically in this code. 
https://github.com/joomla/joomla-cms/blob/79ac1e1c7a286224fcca0be3c3d64debbf616fe9/libraries/src/Helper/ModuleHelper.php#L169-L174

Sorry I dont understand it enough to fix it.

**Comment by chmst** [comment]
See also https://github.com/joomla/joomla-cms/pull/34743 tests are welcome!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36071">issues.joomla.org/tracker/joomla-cms/36071</a>.</sub>

**Comment by brianteeman** [comment]
#34743 is completely unrelated and I just confirmed that when testing #34743 the issue reported here is still present

**Comment by Fedik** [comment]
Pleas test #36268
