### ISSUE TITLE
The field min="0" does not validates the input when type="number"

### ISSUE THREAD

**Issue by Shubhamverma2796** [joomla/joomla-cms#36080]
### Steps to reproduce the issue

From the modules, select the Articles - Archived.
Type any negative value in # of months row.

![Screenshot (284)](https://user-images.githubusercontent.com/54266411/142731770-344faa97-22c0-459d-b27b-2b49c6a9eb40.png)

### Actual result

You can easily set -ve values. Obviously, there is no point in setting the number of months as a negative value. 
This is because the field min="0" is not validating the input when type="number".

### Expected result

A warning should be displayed whenever the user tries to enter any value which is not between the already set min and max value.

**Comment by pritam825** [comment]
can you please mention, it's in 4.0 or 4.1

**Comment by brianteeman** [comment]
Please test #36081

**Comment by pritam825** [comment]
@brianteeman tested successfully #36081 after applying patch
