### ISSUE TITLE
[4.0] Joomla! Updater has to delete the autoload_psr4.php to prevent Exceptions for new system plugins

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#36089]
### Steps to reproduce the issue
- Install Joomla! 4.0.x
- Update Joomla! 4.1 with this PR: https://github.com/joomla/joomla-cms/pull/35143 (Using the download option there)

### Expected result
No exception

### Actual result
Exception, that new namespaced classed could not be found.

### Additional comments
This needs an update of the updater in my opinion.

@wilsonge

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36094 . Thanks in advance.
