### ISSUE TITLE
The administration modules are  not getting validated.

### ISSUE THREAD

**Issue by pritam825** [joomla/joomla-cms#36096]
Summary of Changes
Validated type=number so that the user can not set negative values to follow proper form validation.

Testing Instructions
go to System Dashboard ->  Add module to dashboard
Articles-Latest. Try to save the module with Articles to display = any -ve value.
![image](https://user-images.githubusercontent.com/54195688/143093520-598046da-a277-4874-92a5-1084ca0e7718.png)
![image](https://user-images.githubusercontent.com/54195688/143093603-a153222d-30ee-4842-872a-85cb0dcf88fb.png)

Actual result BEFORE applying this Pull Request
All the fields with the -ve values will be saved successfully before this pr and doesn't show any error.
![image](https://user-images.githubusercontent.com/54195688/143093699-c251feaa-0535-451f-899c-c78e428f0f86.png)

Expected result AFTER applying this Pull Request
Invalid field message is displayed.

**Comment by richard67** [comment]
@pritam825 I am confused now. This here is an issue and not a pull request, but you describe it like a pull request. Can it be that you want to make a pull request for the admin modules like the recently merged #36091 did for the site modules, but accidentally have made an issue instead of a pull request?

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36100 . Thanks in advance.

**Comment by pritam825** [comment]
@richard67  Sorry for describing like an PR but it's an issue
