### ISSUE TITLE
Menus - List Layouts - # Articles to List - Use Global

### ISSUE THREAD

**Issue by pwireless** [joomla/joomla-cms#36109]
### Is your feature request related to a problem? Please describe.

Currently in Menus - List Layouts - # Articles to List, there is the option to select how many articles to list: 5, 10, ....100, All.

### Describe the solution you'd like

With the current approach, you have to go to each menu/list and set the #articles to list. 

Suggesting to add a global option for that #articles to list parameter: "Use Global".

With the "Use Global" you can have all your list layouts having the same # easily, you can adjust it easier, and you don't have to go to each single list layout to adjust.

**Comment by chmst** [comment]
I am not sure which parameter you mean. Is it this page-limit? Maybe you can add a screenshot. 

![image](https://user-images.githubusercontent.com/1035262/143305393-eefd2654-edc1-4a55-a3de-9033363d602b.png)

The global setting for all these fields is in global configuration, Tab "Site", global list limit.

**Comment by pwireless** [comment]
Thank you, here is what I mean:

main admin page -> Menus -> select a Menu you have created on the Site -> click on a menu item displaying "Articles >> Category List" -> go to tab "List Layouts" -> "# Articles to List" -> have option "Use Global" (a global param would need to get added)

See red rectangle in the attached figure.

![joomla-numarticlestolist](https://user-images.githubusercontent.com/16202968/143312296-0398c40e-95aa-4cac-8393-d88a4dbd0d89.png)

**Comment by chmst** [comment]
Thank you! Now it is clear.

**Comment by deepak-yadav123** [comment]
Hello, myself Deepak Yadav
I am a second year undergrad and want to contribute to your projects or work on your issues,
I am familiar with HTML, JavaScript, CSS and have descent knowledge of MySQL and Js.node
Since I am very much intrested in open source, I'm also looking forward to contribute in Google Summer of Code
Please take me on board for any of your upcoming or current projects that require frontend development skill.

**Comment by Shubhamverma2796** [comment]
please test #36790

**Comment by richard67** [comment]
Closing as having a pull request.
