### ISSUE TITLE
Switch show password icon

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#36104]
### Steps to reproduce the issue
While the password is not visible, the show password icon is the `icon-eye` (eye) while when the password is shown is the `icon-eye-slash` (eye with a cross line).
In most applications out there from our phones to google and facebook is the opposite. So atm it is confusing as it's the opposite to how most users expect it to be.

### Expected result

![j-pwd](https://user-images.githubusercontent.com/1838041/143230247-360cd53e-646b-4cdb-ac27-1f11ddc20747.png)

### Actual result

![j-pwd2](https://user-images.githubusercontent.com/1838041/143230270-f4e16f5e-326d-4e05-95a4-7e9df1d18a2a.png)

### System information (as much as possible)
J4

### Additional comments
This happens in all the login forms.

**Comment by brianteeman** [comment]
https://ux.stackexchange.com/questions/123812/is-google-using-the-password-show-hide-toggle-icon-on-their-login-form-correctly

https://ux.stackexchange.com/questions/1318/should-a-toggle-button-show-its-current-state-or-the-state-to-which-it-will-chan

**Comment by brianteeman** [comment]
Those two links _suggest_ to me that it is a subjective view. The important thing is what does the user think. In this specific case I think its obvious that clicking the icon will change a hidden password to a visible password

**Comment by sakiss** [comment]
I decided to open that issue after i got confused more than once with the show button's current state.
Although it is subjective, users got used to a specific implementation that is applied almost everywhere and and they use it intuitively.

**Comment by brianteeman** [comment]
How could you be confused about the current state when the field will either look like

![image](https://user-images.githubusercontent.com/1296369/143239545-bddaa801-9770-40a7-b1fa-27a3653dba30.png)

or

![image](https://user-images.githubusercontent.com/1296369/143239592-e23ed8f6-c0c2-4fc4-8060-f4e01e38af03.png)


However you are correct that the use of an open and closed icon is not used consistently in Joomla.

**Comment by sakiss** [comment]
> How could you be confused about the current state when the field will either look like

The anticipated state does not match the current one and this is confusing.

**Comment by brianteeman** [comment]
> The anticipated state does not match the current one and this is confusing.

thats a common issue throughout joomla

**Comment by chmst** [comment]
@sakiss 

It seems correct for me on login: Buttons are "call-for-action", not information about the state (icon).

A button says for example "read more" or "hide the content" or "klick me" - and something happens.
Here the button says "hide the password" if the password is plain text.
Or "show plaintext" if the password is hidden.

> However you are correct that the use of an open and closed icon is not used consistently in Joomla. 

And in other applications also 


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36104">issues.joomla.org/tracker/joomla-cms/36104</a>.</sub>

**Comment by sakiss** [comment]
@chmst When something is used so widely, that users interact with it intuitively, thinking in terms of wrong and right, can be misleading.
It is like changing the sketch in a road sign, just because we think it will be more correct.

We may have to take the general consensus more seriously. 
Otherwise we can end up creating idiosyncratic UIs which are great in theory but offer little utility.
Just my opinion :)

**Comment by chmst** [comment]
Closing as there is a Pull Request. Please test #36195.

**Comment by brianteeman** [comment]
For me this is a pointless change. From a straw poll of two sites they both use opposite options. If its changed here now then people will be quite right to submit a pr to reverse it again with the same reasoning. its one of those where 50% of the people will always think its wrong

### Twitter
![image](https://user-images.githubusercontent.com/1296369/144724116-eb0a64cf-fa49-4236-a9d3-6eef96d2d633.png)

### Facebook
![image](https://user-images.githubusercontent.com/1296369/144724119-8c603cd3-7b4e-4201-a69c-b17a17068bc7.png)
