### ISSUE TITLE
layouts/joomla/form/field/color/advanced.php - $required field attribute causing rendering error

### ISSUE THREAD

**Issue by CerberusMkII** [joomla/joomla-cms#36113]
### What needs to be fixed
File location: 
layouts/joomla/form/field/color/advanced.php

**Line 83 on Joomla 3.10.3** and **line 88 on Joomla 4.04** is missing the following field attribute handling:
`$required     = $required ? ' required aria-required="true"' : '';`

### Why this should be fixed
Without the fix this is happening:
`<input type="text" name="jform[color]" id="jform_color" value="#000000" placeholder="#rrggbb" class="minicolors required hex" data-position="default" data-control="hue"1 data-format="hex"/>`

`data-control="hue"1`, it's applying an integer instead of correct formatting.

### How would you fix it
Add the following above `$autocomplete` as done in other field layout files:
`$required     = $required ? ' required aria-required="true"' : '';`

Result should be:
`<input type="text" name="jform[color]" id="jform_color" value="#000000" placeholder="#rrggbb" class="minicolors required hex" data-position="default" data-control="hue" required aria-required="true" data-format="hex"/>`

### Side Effects expected
As far as I can tell everything should work fine.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36122 . Thanks in advance.
