### ISSUE TITLE
[4.0] Fix Cassiopeia choices.css shows /*=====  End of Choices  ======*/ in the wrong place

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#36115]
### What needs to be fixed
This is a very minor tidying up issue, but on an installed Cassiopeia template, the file /css/vendor/choicesjs/choices.css has, on line 336:
```
/*=====  End of Choices  ======*/
```

### Why this should be fixed
There are a further 150 or so lines of CSS, still referencing 'choices', so it either needs removing or moving to the end.
I do realise that on the front end the choices.min.css file is used not the choices.css.

### How would you fix it
Not sure, because I can't find it in the code on Github under the Cassiopeia SCSS and I can't find the CSS files

### Side Effects expected
None

**Comment by dgrammatiko** [comment]
https://github.com/Choices-js/Choices/blob/ebbea8c3b0f20473e05112f61bc8ce3bd6bf12da/src/styles/choices.scss#L360

**Comment by Scrabble96** [comment]
Ok. So something in the Joomla 4 compilation is adding extra lines in the Cassiopeia version of the file and presumably can't remove that comment line as it's an external file.

**Comment by dgrammatiko** [comment]
https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/vendor/choicesjs/choices.scss

**Comment by Scrabble96** [comment]
Ah, yes. I'll close this then.
