### ISSUE TITLE
Created by Alias : Component to keep aliases (similar to Tags component)

### ISSUE THREAD

**Issue by pwireless** [joomla/joomla-cms#36111]
### Is your feature request related to a problem? Please describe.

Currently in articles -> publishing -> we have to enter each time, manually the "created by alias" alias name.

### Describe the solution you'd like

Having a component keeping the used so far aliases, and also user being able to populate the component by aliases per will, is a helpful feature (Component similar to Tags).

This will minimize having multiple misspelled aliases of the same person throughout the articles, and also will put an order to the "created by alias" aliases.

The aliases would pop up in the "created by alias" field when entering first characters (or allow to enter a new alias), similar to Tags entry in the article.

### Additional context

![joomla-createdbyalias](https://user-images.githubusercontent.com/16202968/143326753-f981893f-e6a6-49a3-b24d-75aca7183175.png)

**Comment by Aamir-Ansari-almost** [comment]
Greetings!
I would love to solve this issue, I will explore the code and get back here with solution.
Thanks!

**Comment by joomdonation** [comment]
Honestly, I don't think this feature would every be implemented. Maybe we can rely on browser auto-complete for remembering this data for the time being. 

With that said, I'm closing this issue. If anyone disagree, please re-open.
