### ISSUE TITLE
[4.0] Setting "view article options" to No also hides all custom fields tabs. (Regression)

### ISSUE THREAD

**Issue by crystalenka** [joomla/joomla-cms#36121]
### Steps to reproduce the issue
1. Make sure you have an article with custom fields available to edit.
2. Go to edit the com_content configuration.
2. Select the "Editing Layout" tab.
3. Set "Article Options" to "Hide".
4. Save and close.
5. Open an article to edit.

### Expected result
The "Options" tab is hidden, but all other tabs including custom field tabs are still available.

### Actual result
The "Options" tab is hidden, along with all custom fields tabs. Moreover, if you accidentally save the article while all the custom fields are hidden, any previously stored custom fields values in this article are cleared from the database.

### System information (as much as possible)
Joomla 4.0.4
PHP 7.4.25

### Additional comments
This is a regression of issue #15473 and was previously fixed, but is now happening again.

**Comment by brianteeman** [comment]
Confirmed the issue.

**Comment by crystalenka** [comment]
Thank you Brian!


Sent from my Apple Watch

**Comment by brianteeman** [comment]
just like last time I'm afraid I dont know how to fix it

**Comment by joomdonation** [comment]
@crystalenka @brianteeman Could you please check to see if PR https://github.com/joomla/joomla-cms/pull/36168 solves the issue? Hopefully I don't make anything broken :).
