### ISSUE TITLE
[4.0] Moving menu item from one menu to child of item type not Public in a different menu not working correctly

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#36139]
### Steps to reproduce the issue
Create two menus. I have 'mainmenu' and 'editor menu' with an item called "MoveMe".
Add a new menu item of type 'Menu heading', e.g. title "Restricted" in mainmenu and give it Access level 'Registered'
Open item "MoveMe" in the other menu and change its menu assignment to 'mainmenu' and then try to make the Parent item "Restricted".

### Expected result
To be able to assign the item "MoveMe" to parent item "Restricted"

### Actual result
The menu item heading "Restricted" is not yet visible.
What you have to do is assign the menu item "MoveMe" either as a top level item or as a child of one of the visible 'Public' items, save the item and then, if you select 'Parent Item' you will see that "Restricted" is now visible and it is possible to reassign "MoveMe" as a child of "Restricted".

### System information (as much as possible)
J4.0.4

**Comment by brianteeman** [comment]
> What you have to do is

Almost but not quite.

### Option 1
You need to change the menu and save. Then you will see the available parents for that menu.

### Option 2
Use the actions->batch button and you can do it all in one step

**Comment by brianteeman** [comment]
@Scrabble96 did this help you?

**Comment by Scrabble96** [comment]
@brianteeman 
Thanks for the batch tip. I'll remember that for the future.

For some reason, the registered menu items are now showing up alongside the public items when I try to move items, so I have no idea why it wasn't doing so before.

I'll close this now.
