### ISSUE TITLE
[4.0] Quadruple optin for update

### ISSUE THREAD

**Issue by StefanSTS** [joomla/joomla-cms#36151]
### Steps to reproduce the issue

In the update view of Joomla 4 in backend you see an update button.

You cannot press the button until you "opt in" with a tick in the input that the extensions are compatible.
After you tick a popup comes up if you really want to do that. 2nd "opt in".
Now I can press the update button. (But it's not the button for update, it's another opt in.)

Now I come to the next screen that shows an update button. (huh?)
I cannot click the update button, I have to tick another input, 4th "opt in".
There is no popup this time. (Wonderful, but why not, it was there in the screen before, shouldn't it be consistent?)
Now after clicking the 4th "opt in" I can finally click on Update and the button is doing what it says it would.

### Expected result
If I see an update button, I like to see the action performed, otherwise I might want to read something like "Next step to Update". But I would prefer it even shorter.

What I actually expect is that the user is not held for a Dummy and gets one "opt in" and can then press the Update button without being hassled with unnecessary steps.

A hint towards the compatibility of extensions and the backup on one page would suffice.
With the tick of the input the "opt in" process should be good and done.
A popup to ask the user again, what he just now said he wants to do, is Kindergarten. 

### System information (as much as possible)
Came to me on updating two Joomla 4.0.3 to 4.0.4. I have to lie about the backup because for the test page I did not do that. So now I am a liar, or I have to do a backup for a test site where I do not even think about doing a backup. Being a liar is an ugly thing for me, btw, I don't like white or grey lies.

If you think this was a pretty long thing to read for a small issue like that, you exactly feel what I feel.

**Comment by richard67** [comment]
We have had so many issues with people updating when their extensions, especially system plugins, were not compatible, that we saw no other way to make people aware.

Maybe we should offer a kind of subscription where people can opt out and update in one step but will be registered in support forums and here so any issues about updating submitted by those people will directly go into the trash can.

Or we find some 5 or 10 new full time contributors who handle this kind of issues.

**Comment by StefanSTS** [comment]
I am not sure what you are saying.
Means because users had problems updating from Joomla 3 to Joomla 4, we have to go the long road for all tiny updates in the Joomla 4 line?
The other comments are not helpful to take this into a serious conversation.

**Comment by richard67** [comment]
I am saying that it was a deliberate decision to have the check boxes and warnings to make sure people have noticed that they shall make a backup before updating and that they shall check their extensions before updating on a productive site.

**Comment by joomdonation** [comment]
@StefanSTS Just for information, that pre-update checker supposes to show when you update to a new major release of Joomla only (From Joomla 3 to Joomla 4, and later form Joomla 4 to Joomla 5...)

Due to a bug in the code (which was fixed recently), that step is still being shown when you update from earlier version to until 4.0.5. After updating 4.0.5, you won't see that pre-update checker step anymore (until you update to Joomla 5 in the future).

**Comment by richard67** [comment]
Well there still will be that one check box to confirm that you have checked your extensions and have made a backup.

**Comment by StefanSTS** [comment]
@joomdonation 
Thanks for that information. That might indeed change the user experience.
So I guess I pause this until I have seen how it works in J 4.0.5.

If there is still one checkbox left, I would prefer a box that says "I have read the above and want to go ahead" instead of acknowledging something I might not have checked or done for various reasons.

**Comment by RussW** [comment]
but surely, whether it is the 3.9>4.x upgrade or later 4.x updates, forcing any user to check boxes is not only condescending but pointless if they don't understand anyway? Not to mention, with the 3.9>4.x upgrade, surely it would have been more user friendly and logical process to provide two upgrade buttons, one that is proceed at your own risk and the other to proceed with Joomla! auto-disabling any extensions that are not known to be compatible. Both ways warn the user, if everything goes to hell and a handbasket if they proceed regardless, thats their call, if Joomla! disables unknown extensions then at the upgrade should proceed and those extensions can be updated afterwards to be compatible. This also reduces the assumed need to beat the user around the head with messages, check-boxes and confirmations that will only actually lead to even more down-level (potentially vulnerable) Joomla! sites in the long run as users will be too scared to upgrade/update.

**Comment by StefanSTS** [comment]
A change like this would help the user to feel to be a truthful person:

COM_JOOMLAUPDATE_UPDATE_CONFIRM_BACKUP="I'm prepared for the update and have made a backup."
to
COM_JOOMLAUPDATE_UPDATE_CONFIRM_BACKUP="I am aware that a backup prior to the update is strongly recommended."

What this does:
1. Remove prepared for update:
The phrase that someone is prepared is kind of prerequisite, otherwise the person would not see this screen.

2. Keep the topic of the input simply to "backup", but leave a way for experienced developers (that have a good reason, not to backup) to truely tick the input box.
(For example me with my 10 Joomla 3 test sites and three Joomla 4 test sites that I keep uptodate all the time, but only sometimes backup.)

**Comment by StefanSTS** [comment]
On Joomla 4.0.5 to 4.0.6 update the "quadruple" problem is fixed. 
Only one screen appeared in the update process.
Only one checkbox to tick.
So the major issue is solved.

Missing would be a change of the label like suggested above.
Does anyone have a better suggestion for COM_JOOMLAUPDATE_UPDATE_CONFIRM_BACKUP? 

My version is quite long, so there might be some native English speaking person who gets the meaning of it into fewer words.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36151">issues.joomla.org/tracker/joomla-cms/36151</a>.</sub>

**Comment by richard67** [comment]
I do not see the need to change that text. In my opinion the 2nd part of the sentence "and have made a backup." shows what being prepared means.

But maybe we should ask a native speaker.

@brianteeman Do you think the text could or should be improved as suggested in [this comment above](https://github.com/joomla/joomla-cms/issues/36151#issuecomment-981569419)?

**Comment by brianteeman** [comment]
Is this even still relevant. I thought there was a PR that changed this

**Comment by richard67** [comment]
> Is this even still relevant. I thought there was a PR that changed this

Hmm, I've just checked if the string is different in the 4.1-dev branch, but it's the same as in 4.0-dev, and that hasn't changed compared to the above comment.

**Comment by richard67** [comment]
@brianteeman Would the text suggested by @StefanSTS be ok?

> I am aware that a backup prior to the update is strongly recommended.

**Comment by brianteeman** [comment]
#36531 changed this didnt it?

**Comment by richard67** [comment]
> Is this even still relevant. I thought there was a PR that changed this

@brianteeman The quadruple times problem is not relevant anymore. The remaining point is only if the "COM_JOOMLAUPDATE_UPDATE_CONFIRM_BACKUP" text can or should be improved.

**Comment by richard67** [comment]
> #36531 changed this didnt it?

As far as I can see, that PR does not change the "COM_JOOMLAUPDATE_UPDATE_CONFIRM_BACKUP" text.

**Comment by StefanSTS** [comment]
In Joomla 4.0.6 it is
COM_JOOMLAUPDATE_UPDATE_CONFIRM_BACKUP="I'm prepared for the update and have made a backup of the files and database."

In 4.1 dev at this time it is the same:
https://github.com/joomla/joomla-cms/blob/4.1-dev/administrator/language/en-GB/com_joomlaupdate.ini

As I expressed earlier, there is not always a good reason to make a backup. Test sites e.g., if it breaks it will be repaired or discarded. Multiple updates of similar sites, sites without content changes for a long time.

Ticking this would be a lie for many users. That is unacceptable for a person that likes to say the truth. Yes, I know how that sounds. But does anyone actually want to make a Joomla user feel uneasy about ticking that box? 
Joomla should be as user friendly as possible. Means also to tick boxes in good conscience.

This, anyone can tick with ease:
COM_JOOMLAUPDATE_UPDATE_CONFIRM_BACKUP="I am aware that a backup prior to the update is strongly recommended."

**Comment by brianteeman** [comment]
please see #38071 which I believe is thelasr part of this issue.

**Comment by richard67** [comment]
The other PR #36531 has been replaced meanwhile by #37911 .

Besides other things, it adds a new option to make the confirmation checkboxes optional.

So I think with the 2 PRs #37911 and #38071 , this issue should be solved.

**Comment by richard67** [comment]
Closing as having 2 pull requests which together solve this issue. Please test #37911 and #38071 . Thanks in advance.
