### ISSUE TITLE
[4.0] Incorrect code comments

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36152]
A recent merge introduced the following lines which have a code comment that is copy pasted from elsewhere and is clearly not correct

https://github.com/joomla/joomla-cms/blob/6801293f0e6e7645af79e0cab860a85555d00b82/administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php#L92-L94

https://github.com/joomla/joomla-cms/blob/6801293f0e6e7645af79e0cab860a85555d00b82/administrator/components/com_joomlaupdate/src/View/Joomlaupdate/HtmlView.php#L110-L115

**Comment by chmst** [comment]
Please have a look on #36188
