### ISSUE TITLE
Drone failure - requires git

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36160]
#36159 is failing at the npm stage because git is not included in the alpine docker image. See [explanation](https://github.com/nodejs/docker-node/pull/367)

The fix is very [simple ](https://github.com/nodejs/docker-node/issues/586) for someone who has access to the docker image

ping @bembelimen @HLeithner

**Comment by HLeithner** [comment]
created a pr on your branch https://github.com/brianteeman/joomla-cms/pull/133

**Comment by brianteeman** [comment]
Thanks very much

**Comment by brianteeman** [comment]
@HLeithner 
```
npm ERR! Error while executing:
npm ERR! /usr/bin/git ls-remote -h -t ssh://git@github.com/joomla-projects/joomla-a11y-checker.git
npm ERR! 
npm ERR! Host key verification failed.
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR! 
npm ERR! exited with error code: 128
```

**Comment by HLeithner** [comment]
the package.json needs to be https://github.com/joomla-projects/joomla-a11y-checker.git not ssh://git@

**Comment by brianteeman** [comment]
ok - updated and trying again. 

PS blame @bembelimen he wrote that part

**Comment by brianteeman** [comment]
same error.

**Comment by HLeithner** [comment]
couldn't be the same?! do you have a link?

**Comment by brianteeman** [comment]
https://ci.joomla.org/joomla/joomla-cms

**Comment by HLeithner** [comment]
have seen it, it's strange because it uses the wrong urls...

**Comment by brianteeman** [comment]
Just revisiting this. I see that the last error was not the same

> Host key verification failed.
