### ISSUE TITLE
method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given (creating article)

### ISSUE THREAD

**Issue by aftertaf** [joomla/joomla-cms#36165]
### Steps to reproduce the issue
-Start to create new article (do not save it yet)
-Choose a category for new article
-URL while doing this action :
https://mysite/administrator/index.php?option=com_content&view=article&layout=edit

### Expected result
New article becomes assigned to the chosen category

### Actual result
Joomla multicolor splash screen lightbox animation pops up for 2-3 seconds
backend reports error : "method_exists(): Argument #1 ($object_or_class) must be of type object|string, array given"

### System information (as much as possible)
PHP 8
Joomla 4.0.4

### Additional comments
NB, i've set PageBuilderCK to be my main article editor, but the issue happens when this is not set this way too...

Stack Trace:
Call stack
#	Function	Location
1	()	JROOT/plugins/system/pagebuilderck/pagebuilderck.php:77
2	method_exists()	JROOT/plugins/system/pagebuilderck/pagebuilderck.php:77
3	plgSystemPagebuilderck->onContentPrepareForm()	JROOT/libraries/src/Plugin/CMSPlugin.php:285
4	Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}()	JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:486
5	Joomla\Event\Dispatcher->dispatch()	JROOT/libraries/src/Application/EventAware.php:111
6	Joomla\CMS\Application\WebApplication->triggerEvent()	JROOT/libraries/src/MVC/Model/FormBehaviorTrait.php:179
7	Joomla\CMS\MVC\Model\FormModel->preprocessForm()	JROOT/administrator/components/com_content/src/Model/ArticleModel.php:1105
8	Joomla\Component\Content\Administrator\Model\ArticleModel->preprocessForm()	JROOT/libraries/src/MVC/Model/FormBehaviorTrait.php:117
9	Joomla\CMS\MVC\Model\FormModel->loadForm()	JROOT/administrator/components/com_content/src/Model/ArticleModel.php:490
10	Joomla\Component\Content\Administrator\Model\ArticleModel->getForm()	JROOT/libraries/src/MVC/View/AbstractView.php:146
11	Joomla\CMS\MVC\View\AbstractView->get()	JROOT/administrator/components/com_content/src/View/Article/HtmlView.php:87
12	Joomla\Component\Content\Administrator\View\Article\HtmlView->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:692
13	Joomla\CMS\MVC\Controller\BaseController->display()	JROOT/administrator/components/com_content/src/Controller/DisplayController.php:63
14	Joomla\Component\Content\Administrator\Controller\DisplayController->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:730
15	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
16	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()	JROOT/libraries/src/Component/ComponentHelper.php:389
17	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/AdministratorApplication.php:143
18	Joomla\CMS\Application\AdministratorApplication->dispatch()	JROOT/libraries/src/Application/AdministratorApplication.php:186
19	Joomla\CMS\Application\AdministratorApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:278
20	Joomla\CMS\Application\CMSApplication->execute()	JROOT/administrator/includes/app.php:63
21	require_once()	JROOT/administrator/index.php:32

**Comment by aftertaf** [comment]
Once the article has been saved once, it is possible to choose a category for it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36165">issues.joomla.org/tracker/joomla-cms/36165</a>.</sub>

**Comment by joomdonation** [comment]
If you look at the call stack, you will see that the error comes from pagebuilderck system plugin. Please contact the developer of that extension and ask him to check and correct it

Closing this issue because it's a none-core issue.

**Comment by aftertaf** [comment]
OK, having checked with this not replacing the default editor, the stack trace still mentions this plugin. thanks..<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36165">issues.joomla.org/tracker/joomla-cms/36165</a>.</sub>
