### ISSUE TITLE
HTML mail templates not sending images correctly [j4.0.4]

### ISSUE THREAD

**Issue by aftertaf** [joomla/joomla-cms#36163]
### Steps to reproduce the issue
Using HTML format mail templates, I add an logo image to the top of the mail

### Expected result
Mail received shows the image

### Actual result
Mail can't load the image, and the path to the image remains relative to the server '/images/site_logos/my_logo.png' instead of 'https://mysite.org/images/site_logos/my_logo.png'

### System information (as much as possible)
PHP Mailer
PHP 
Joomla 4.0.4

### Additional comments
I've tried to put the full URL to the image inside the mail <img src=""> but it gets automatically stripped out

**Comment by joomdonation** [comment]
@aftertaf PR https://github.com/joomla/joomla-cms/pull/36088 fixes this issue. It needs one more test. So if you can help testing, that would be great.

**Comment by aftertaf** [comment]
Hi,
i have just modified the 3 files mentioned in your fix, and confirm the image is sent in the mail as expected. Works for me :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36163">issues.joomla.org/tracker/joomla-cms/36163</a>.</sub>

**Comment by joomdonation** [comment]
@aftertaf Could you please go to https://issues.joomla.org/tracker/joomla-cms/36088 and submit your test result? As mentioned, we need two successful tests for the PR to be merged.
