### ISSUE TITLE
Articles: New Alias character issue

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#36164]
### Steps to reproduce the issue

There is a problem with the letters **Üü, Öö**.

**Create New Article**

Title: Joomla Ürünler
Title: Joomla Önek

### Expected result

The link should be like this,

Alias that should be: joomla-urunler
Alias that should be: joomla-onek

### Actual result

Alias: joomla-ueruens (this is not true)
Alias: joomla-oenek (this is not true)

### System information (as much as possible)

- I just installed
- Joomla! 4.0.4
- [System Information](https://joomlatr.org/systeminfo-2021-11-30T13_42_00+03_00.txt)

Best Regards

**Comment by chmst** [comment]
Which constellation of languages do you have on your PC?
In J3, were there the alias names as you expected - was there a difference between turkish and german ü/ö?

**Comment by infograf768** [comment]
PHP INTL extension transliterates ö and ü to oe and ue after this was merged
https://github.com/joomla/joomla-cms/pull/35029

To override this, a transliterate method has to be added to your language localise.php.

**Comment by ghost** [comment]
> Which constellation of languages do you have on your PC? In J3, were there the alias names as you expected - was there a difference between turkish and german ü/ö?

In fact, it was in the J3 version as well.

@infograf768 I will implement it and let you know, thank you.

**Comment by ghost** [comment]
> PHP INTL extension transliterates ö and ü to oe and ue after this was merged #35029
> 
> To override this, a transliterate method has to be added to your language localise.php.

Problem not solved. Could you please download and test the Turkish language pack?

**Comment by ghost** [comment]
I edited the libraries/src/Language/transliterate.php file, everything is fine now.

I replaced it with the defaults.

I was looking for ways to make these changes permanent but this is not the solution!

`'à' => 'a',
'ô' => 'o',
'ď' => 'd',
'ḟ' => 'f',
'ë' => 'e',
'š' => 's',
'ơ' => 'o',
'ß' => 'ss',
'ă' => 'a',
'ř' => 'r',
'ț' => 't',
'ň' => 'n',
'ā' => 'a',
'ķ' => 'k',
'ŝ' => 's',
'ỳ' => 'y',
'ņ' => 'n',
'ĺ' => 'l',
'ħ' => 'h',
'ṗ' => 'p',
'ó' => 'o',
'ú' => 'u',
'ě' => 'e',
'é' => 'e',
'ç' => 'c',
'ẁ' => 'w',
'ċ' => 'c',
'õ' => 'o',
'ṡ' => 's',
'ø' => 'o',
'ģ' => 'g',
'ŧ' => 't',
'ș' => 's',
'ė' => 'e',
'ĉ' => 'c',
'ś' => 's',
'î' => 'i',
'ű' => 'u',
'ć' => 'c',
'ę' => 'e',
'ŵ' => 'w',
'ṫ' => 't',
'ū' => 'u',
'č' => 'c',
'ö' => 'o',
'è' => 'e',
'ŷ' => 'y',
'ą' => 'a',
'ł' => 'l',
'ų' => 'u',
'ů' => 'u',
'ş' => 's',
'ğ' => 'g',
'ļ' => 'l',
'ƒ' => 'f',
'ž' => 'z',
'ẃ' => 'w',
'ḃ' => 'b',
'å' => 'a',
'ì' => 'i',
'ï' => 'i',
'ḋ' => 'd',
'ť' => 't',
'ŗ' => 'r',
'ä' => 'ae',
'í' => 'i',
'ŕ' => 'r',
'ê' => 'e',
'ü' => 'u',
'ò' => 'o',
'ē' => 'e',
'ñ' => 'n',
'ń' => 'n',
'ĥ' => 'h',
'ĝ' => 'g',
'đ' => 'd',
'ĵ' => 'j',
'ÿ' => 'y',
'ũ' => 'u',
'ŭ' => 'u',
'ư' => 'u',
'ţ' => 't',
'ý' => 'y',
'ő' => 'o',
'â' => 'a',
'ľ' => 'l',
'ẅ' => 'w',
'ż' => 'z',
'ī' => 'i',
'ã' => 'a',
'ġ' => 'g',
'ṁ' => 'm',
'ō' => 'o',
'ĩ' => 'i',
'ù' => 'u',
'į' => 'i',
'ź' => 'z',
'á' => 'a',
'û' => 'u',
'þ' => 'th',
'ð' => 'dh',
'æ' => 'ae',
'µ' => 'u',
'ĕ' => 'e',
'œ' => 'oe',`

And

`'İ' => 'I',
'Ô' => 'O',
'Ď' => 'D',
'Ḟ' => 'F',
'Ë' => 'E',
'Š' => 'S',
'Ơ' => 'O',
'Ă' => 'A',
'Ř' => 'R',
'Ț' => 'T',
'Ň' => 'N',
'Ā' => 'A',
'Ķ' => 'K',
'Ŝ' => 'S',
'Ỳ' => 'Y',
'Ņ' => 'N',
'Ĺ' => 'L',
'Ħ' => 'H',
'Ṗ' => 'P',
'Ó' => 'O',
'Ú' => 'U',
'Ě' => 'E',
'É' => 'E',
'Ç' => 'C',
'Ẁ' => 'W',
'Ċ' => 'C',
'Õ' => 'O',
'Ṡ' => 'S',
'Ø' => 'O',
'Ģ' => 'G',
'Ŧ' => 'T',
'Ș' => 'S',
'Ė' => 'E',
'Ĉ' => 'C',
'Ś' => 'S',
'Î' => 'I',
'Ű' => 'U',
'Ć' => 'C',
'Ę' => 'E',
'Ŵ' => 'W',
'Ṫ' => 'T',
'Ū' => 'U',
'Č' => 'C',
'Ö' => 'O',
'È' => 'E',
'Ŷ' => 'Y',
'Ą' => 'A',
'Ł' => 'L',
'Ų' => 'U',
'Ů' => 'U',
'Ş' => 'S',
'Ğ' => 'G',
'Ļ' => 'L',
'Ƒ' => 'F',
'Ž' => 'Z',
'Ẃ' => 'W',
'Ḃ' => 'B',
'Å' => 'A',
'Ì' => 'I',
'Ï' => 'I',
'Ḋ' => 'D',
'Ť' => 'T',
'Ŗ' => 'R',
'Ä' => 'Ae',
'Í' => 'I',
'Ŕ' => 'R',
'Ê' => 'E',
'Ü' => 'U',
'Ò' => 'O',
'Ē' => 'E',
'Ñ' => 'N',
'Ń' => 'N',
'Ĥ' => 'H',
'Ĝ' => 'G',
'Đ' => 'D',
'Ĵ' => 'J',
'Ÿ' => 'Y',
'Ũ' => 'U',
'Ŭ' => 'U',
'Ư' => 'U',
'Ţ' => 'T',
'Ý' => 'Y',
'Ő' => 'O',
'Â' => 'A',
'Ľ' => 'L',
'Ẅ' => 'W',
'Ż' => 'Z',
'Ī' => 'I',
'Ã' => 'A',
'Ġ' => 'G',
'Ṁ' => 'M',
'Ō' => 'O',
'Ĩ' => 'I',
'Ù' => 'U',
'Į' => 'I',
'Ź' => 'Z',
'Á' => 'A',
'Û' => 'U',
'Þ' => 'Th',
'Ð' => 'Dh',
'Æ' => 'Ae',
'Ĕ' => 'E',
'Œ' => 'Oe',`

@HLeithner

**Comment by infograf768** [comment]
Don’t do that…

**Comment by ghost** [comment]
> Don’t do that…

I just tested. And I can't solve the problem.

**Comment by infograf768** [comment]
You have to add a transliterate method in the Turkish language `localise.php` to override the INTL default transliteration.

Here is the file which should replace the existing localise.php in your admin and site `language/tr-TR/` folders.

[localise.php.zip](https://github.com/joomla/joomla-cms/files/7647324/localise.php.zip)

**Comment by ghost** [comment]
> `localise.php`INTL varsayılan harf çevirisini geçersiz kılmak için Türkçe dilinde bir harf çevirisi yöntemi eklemeniz gerekir .
> 
> Yönetici ve site `language/tr-TR/`klasörlerinizdeki mevcut localise.php dosyasının yerini alması gereken dosya burada .
> 
> [yerelleştir.php.zip](https://github.com/joomla/joomla-cms/files/7647324/localise.php.zip)

@infograf768  Thanks for everything. I was working on admin/language/en-TR. I didn't think of the fronted.

Best Regards

**Comment by ghost** [comment]
Now I noticed and several users contacted me. After doing this, I keep getting an update warning. I can't figure out where we went wrong.

View:
https://imgur.com/a/QzHXAOC

> localise.php.zip

@infograf768

**Comment by infograf768** [comment]
The Turkish TT coordinator has been informed about this topic and this update contains the transliterate method. You can update safely ;)
