### ISSUE TITLE
[4.0] modal.js behaves differently than modal.min.js

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#36176]
### Steps to reproduce the issue
**media/vendor/bootstrap/js/modal.js** behaves differently than **media/vendor/bootstrap/js/modal.min.js** 

See example: https://github.com/joomla/joomla-cms/issues/36169

### System information (as much as possible)
Joomla 4.0.4 stable package.
Joomla_4.0.5-rc2-dev-Development-Full_Package.zip - Nightly Build Wednesday, 01 December 2021 03:00:04 UTC

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36178 . Thanks in advance.
