### ISSUE TITLE
Change in Default Language from en-GB to en-CA generated a 500 error code

### ISSUE THREAD

**Issue by fballem** [joomla/joomla-cms#36170]
### Steps to reproduce the issue
1. Installed two language packages - en-CA and fr on a new installation of Joomla 4
2. Received notification that both language packages were installed correctly (07-Joomla Language Setup 02)
3. Selected System Languages (09-Joomla Language Setup 04)
4. Changed the default language to en-CA (10-Joomla Language Setup 05)
5. Received the 500 Error Code. I'm unable to access my site.
6. Debug shows the cause of the error (00-Fatal Error) - two images attached.

### Expected result
1. The default language should be set to en-CA. I'm not sure why it was attempting to set an instance of en-GB, since we don't speak British English in Canada.![screen shot 2021-11-30 at 22 16 29](https://issues.joomla.org/uploads/1/a6c1db3af78b3ffcf385ad0f354bc4dd.png)

### Actual result
1. A 500 Error was generated and I can no longer access my site.

### System information (as much as possible)
Version : 4.0.4, 3.10.3 New Installation, logged in as the site administrator

### Additional comments
In order to continue building my website, I'll re-install. I'll setup Content Languages and set en-CA to the default. I don't want en-GB to be an option on my content, so I hope that change will work.

![screen shot 2021-11-30 at 22 16 29](https://issues.joomla.org/uploads/1/2191a658de7f6b9b06a9b9545758fa81.png)![screen shot 2021-11-30 at 22 16 29](https://issues.joomla.org/uploads/1/19cf476896dbe1632ebd864827882df9.png)![screen shot 2021-11-30 at 22 16 29](https://issues.joomla.org/uploads/1/5247b8ce386db162193fd836a7205818.png)![screen shot 2021-11-30 at 22 16 29](https://issues.joomla.org/uploads/1/1798de920596d2ca3e198665893d6769.png)

**Comment by brianteeman** [comment]
Grrrh another bad language

**Comment by brianteeman** [comment]
That change wont really work as en-gb is the default so you will still get the error.

What you can do after installing the language but before enabling it is to use ftp or your hosting control panel to edit that file.

Just change en_gblocalise to
`abstract class en_CALocalise`

**Comment by fballem** [comment]
Thanks Brian, I’ll give that a try. Good thing that this is a new installation. I assume that the language package is the culprit and that it will get fixed? Best wishes,Flavelle Sent from Mail for Windows From: Brian TeemanSent: November 30, 2021 5:28 PMTo: joomla/joomla-cmsCc: fballem; AuthorSubject: Re: [joomla/joomla-cms] Change in Default Language from en-GB to en-CA generated a 500 error code (Issue #36170) That change wont really work as en-gb is the default so you will still get the error.What you can do after installing the language but before enabling it is to use ftp or your hosting control panel to edit that file.Just change en_gblocalise toabstract class en_CALocalise—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fballem** [comment]
Brian: That seems to have worked. Now if only I could get rid of British English from the options to select a language for everything 😃 I very much appreciate the quick fix! Best wishes,Flavelle Sent from Mail for Windows From: Flavelle BallemSent: November 30, 2021 5:49 PMTo: joomla/joomla-cmsSubject: RE: [joomla/joomla-cms] Change in Default Language from en-GB to en-CA generated a 500 error code (Issue #36170) Thanks Brian, I’ll give that a try. Good thing that this is a new installation. I assume that the language package is the culprit and that it will get fixed? Best wishes,Flavelle Sent from Mail for Windows From: Brian TeemanSent: November 30, 2021 5:28 PMTo: joomla/joomla-cmsCc: fballem; AuthorSubject: Re: [joomla/joomla-cms] Change in Default Language from en-GB to en-CA generated a 500 error code (Issue #36170) That change wont really work as en-gb is the default so you will still get the error.What you can do after installing the language but before enabling it is to use ftp or your hosting control panel to edit that file.Just change en_gblocalise toabstract class en_CALocalise—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by infograf768** [comment]
Informed P. Jackson of this error

**Comment by particthistle** [comment]
4.0.4.4 available tomorrow.

**Comment by particthistle** [comment]
4.0.4.4 will be officially available once Joomla Downloads system process the changes I've just made (most likely it will be available by the time you're reading this in the morning @fballem).

If it's not yet become available you can install this updated version of 4.0.4.4 manually: [en-CA.zip](https://github.com/joomla/joomla-cms/files/7631492/en-CA.zip)

And congratulations - you're the first person to have actually downloaded, installed, tested AND reported back on en-CA issues! Apologies for the inconvenience the 500 error caused.

**Comment by richard67** [comment]
So can this issue be closed?

**Comment by fballem** [comment]
Nope – the update failed Sorry about that! Flavelle Sent from Mail for Windows From: Richard FathSent: December 1, 2021 2:00 AMTo: joomla/joomla-cmsCc: fballem; MentionSubject: Re: [joomla/joomla-cms] Change in Default Language from en-GB to en-CA generated a 500 error code (Issue #36170) So can this issue be closed?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fballem** [comment]
Peter: I noticed that 4.0.4.4 was identified as an update on the Joomla site, so I attempted to update and got a checksum error. (screenshot attached). You were kind enough to send me a zip file. I assume that if I open Extensions and try to install the zip file, then that should work. Apparently not (second screenshot attached). As for congratulations, thank you. I am a proud, bilingual Canadian who is trying to setup a bilingual website. It’s unbelievably hard – given that there appears to be no way to fully disable the English (United Kingdom) and no way to get the French module to report as fr-CA. I do want to thank all of you for your hard work! Sent from Mail for Windows From: Patrick JacksonSent: December 1, 2021 1:36 AMTo: joomla/joomla-cmsCc: fballem; MentionSubject: Re: [joomla/joomla-cms] Change in Default Language from en-GB to en-CA generated a 500 error code (Issue #36170) 4.0.4.4 will be officially available once Crowdin and the Downloads system process the changes I've just made (this evening local time in ***@***.*** You can install this updated version of 4.0.4.3 with the file fixed to confirm it's working: (en-CA).zipAnd congratulations - you're the first person to have actually downloaded, installed, tested AND reported back on en-CA!—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by infograf768** [comment]
I have no problem here installing en-CA version 4.0.44 which is already available in `administrator/index.php?option=com_installer&view=languages`

Concerning multilingual: it is easy to use fr-FR and, using the languagecode plugin make it look as fr-CA in the html produced.
<img width="1440" alt="Screenshot 2021-12-01 at 11 15 33" src="https://user-images.githubusercontent.com/869724/144216132-e3019f51-e2a2-4e96-bc9f-59996474d911.png">

**Comment by fballem** [comment]
Thanks for the help. I will try both things later today! Flavelle Sent from Mail for Windows From: infograf768Sent: December 1, 2021 5:18 AMTo: joomla/joomla-cmsCc: fballem; MentionSubject: Re: [joomla/joomla-cms] Change in Default Language from en-GB to en-CA generated a 500 error code (Issue #36170) I have no problem here installing en-CA version 4.0.44 which is already available in administrator/index.php?option=com_installer&view=languagesConcerning multilingual: it is easy to use fr-FR and, using the languagecode plugin make it look as fr-CA in the html produced.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fballem** [comment]
Since it was early in my process, I re-installed Joomla and I was able to load the new English-Canada Language with no further issues. Please close this ticket. Also, thanks for the instruction on the Language Code for French. That has helped. Thanks everyone for your help, Flavelle Sent from Mail for Windows From: infograf768Sent: December 1, 2021 5:18 AMTo: joomla/joomla-cmsCc: fballem; MentionSubject: Re: [joomla/joomla-cms] Change in Default Language from en-GB to en-CA generated a 500 error code (Issue #36170) I have no problem here installing en-CA version 4.0.44 which is already available in administrator/index.php?option=com_installer&view=languagesConcerning multilingual: it is easy to use fr-FR and, using the languagecode plugin make it look as fr-CA in the html produced.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by richard67** [comment]
Closing as stated in previous comment. Thanks for reporting back.
