### ISSUE TITLE
[4.0.5] Trying to get property '0' of non-object in tinymce.php

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#36179]
### Steps to reproduce the issue
Go to System > Plugins
Edit `Editor - TinyMCE` plugin.
Click `Save & Close` button.

Create or edit an article.
See error.

### Actual result
 > Notice: Trying to get property '0' of non-object in \plugins\editors\tinymce\tinymce.php on line 200

**Comment by brianteeman** [comment]
Is this a completely clean installation?

**Comment by brianteeman** [comment]
I could not replicate this on a completely clean install

**Comment by chmst** [comment]
I cannot replicate the error on the site where I am working on (4.0.5 dev, not empty)

**Comment by brianteeman** [comment]
The reason that I said not empty was that I could replicate it on an install that had moved up to 4.1 and then back to 4.0

**Comment by Quy** [comment]
4.0.4 Clean install OK
4.0.5 Clean install of the nightly build. NOT OK

![36179](https://user-images.githubusercontent.com/368084/144309061-e29342e6-00c1-477a-b168-48bed46160b8.jpg)

**Comment by dgrammatiko** [comment]
`$toolbarParams = $toolbarParamsAll->{$set};` should do

**Comment by Quy** [comment]
Same error. Initially, it is an object. After saving TinyMCE settings, it is an array.

Before:
```
object(stdClass)[1058]
  public '2' => 
    object(stdClass)[1057]
      public 'toolbar1' => 
        array (size=11)
          0 => string 'bold' (length=4)
          1 => string 'underline' (length=9)
          2 => string 'strikethrough' (length=13)
          3 => string '|' (length=1)
          4 => string 'undo' (length=4)
          5 => string 'redo' (length=4)
          6 => string '|' (length=1)
          7 => string 'bullist' (length=7)
          8 => string 'numlist' (length=7)
          9 => string '|' (length=1)
          10 => string 'pastetext' (length=9)
```
After:
```
array (size=3)
  0 => 
    object(stdClass)[1066]
      public 'menu' => 
        array (size=6)
          0 => string 'edit' (length=4)
          1 => string 'insert' (length=6)
          2 => string 'view' (length=4)
          3 => string 'format' (length=6)
          4 => string 'table' (length=5)
          5 => string 'tools' (length=5)
```

**Comment by dgrammatiko** [comment]
Try 
```php
$extraOptionsAll  = (object) $this->params->get('configuration.setoptions', array());
$toolbarParamsAll = (object) $this->params->get('configuration.toolbars', array());
```

**Comment by Quy** [comment]
It fixed it, however, menu is missing (Edit, Insert,  View...).

Before saving settings:
![tinymce-before](https://user-images.githubusercontent.com/368084/144328685-16da0db1-f2a9-488d-b4de-faf5be7c8291.jpg)

After saving settings:
![tinymce-after](https://user-images.githubusercontent.com/368084/144328692-38283ca6-e9ea-431a-85f6-7a8dc3f73a45.jpg)

**Comment by dgrammatiko** [comment]
Can you reverse the array and then cast it to an object?

**Comment by Quy** [comment]
Sorry I don't understand. Another issue is that it is displaying set 2 and not set 0 after saving TinyMCE settings. Something else is going on since v4.0.4.

**Comment by brianteeman** [comment]
@quy but two of us can not replicate your issue

**Comment by Quy** [comment]
Yes, I understand. Hopefully, it is an isolated case. If no one else can reproduce it, I will close it by tomorrow.

**Comment by Fedik** [comment]
@Quy  did you edited TinyMCE plugin options after installation, or not? so they is default now

> Something else is going on since v4.0.4.

there was PR #36066 

One thing I can guess, before the PR we had keys as 2 1 0 and JRegistry store it as `object`,
after changing order to 0 1 2 JRegistry store it as `array`.
This need to check.

**Comment by joomdonation** [comment]
Just tried and can confirm the issue with today nightly build!

**Comment by infograf768** [comment]
Confirmed here (last 4.0.5-dev)
<img width="1082" alt="Screenshot 2021-12-02 at 10 01 48" src="https://user-images.githubusercontent.com/869724/144390583-41762e0a-67b4-424f-be32-f4d829e31edc.png">

**Comment by dgrammatiko** [comment]
Reversing this https://github.com/joomla/joomla-cms/blob/8bcefc93a21b3122d0b74f576481b9be28493dbd/plugins/editors/tinymce/src/Field/TinymcebuilderField.php#L97-L100

to 

```php
		// Get array of sets names
		for ($i = $setsAmount; $i >= 0; $i--)
		{
			$data['setsNames'][$i] = Text::sprintf('PLG_TINY_SET_TITLE', $i);
		}
```

Seems to do the trick. (keep the typecasting and the other `->{$set}` from my previous comments)

@Fedik since the whole tinyMCE builder is mostly your code can you confirm that this is correct? If so, then someone needs to do a PR with the changes

**Comment by Fedik** [comment]
This will revert changes from #36066 ;) 
There should be another solution,  I will look later

**Comment by dgrammatiko** [comment]
> This will revert changes from #36066 ;)

No, the tabs are still in the right order (0, 1, 2) and the data is also correctly correlated to the right number. Anyways you might have a better solution 😉

Edit, you're right this reverses the order of tabs

**Comment by brianteeman** [comment]
Probably the code that @fedik changed in my pr that is causing this ;)

**Comment by Fedik** [comment]
Please test #36186
