### ISSUE TITLE
php 8.1 lack of automated testing

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#36187]
### Is your feature request related to a problem? Please describe.
yes we currently doesn't have in the drone pipeline any  test coverage for php 8.1

### Describe the solution you'd like
the test suite must cover php 8.1

from a random pr 
![Screenshot from 2021-12-02 21-16-44](https://user-images.githubusercontent.com/181681/144496420-54d0160e-7be6-46a0-b335-99d4d746e73b.png)

**Comment by laoneo** [comment]
Did a pr which adds the unit and integration tests for PHP 8.1. System tests are still open as you can read in the instructions in #36234.

**Comment by HLeithner** [comment]
Add system tests for 8.1 in #36260
