### ISSUE TITLE
[4.0] MariaDB issue when same code works fine on MySQL

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#36183]
### Steps to reproduce the issue

New component works fine on dev machine with MySQL.

Install same component on another machine with MariaDB.

### Expected result

Work the same on both MySQL and MariaDB.

### Actual result

On MariaDB get a 'Prepared statement needs to be re-prepared' error from one of the view models.

### System information (as much as possible)

Looks like there is a history of this with MariaDB - see Google search results.

### Additional comments

Looks like the problem caused by a SQL VIEW being accessing by the Joomla view model.

Restructured the Joomla view model to avoid using the SQL VIEW and works fine on MariaDB.

This is information maybe helpful if others encounter this.

**Comment by UkaniVedant** [comment]
[https://mariadb.com/kb/en/library/server-system-variables/#table_definition_cache]
SET GLOBAL table_definition_cache = 1024
I think running this in the MariaDB solved the problem.

**Comment by richard67** [comment]
> New component works fine on dev machine with MySQL.
>
> Install same component on another machine with MariaDB.

So it's not a problem with the CMS core but with a 3rd party component?

**Comment by alikon** [comment]
i'm really curious to know what SQL standard statements fails on MariaDB  and succed on MySQL

**Comment by richard67** [comment]
> i'm really curious to know what SQL standard statements fails on MariaDB and succed on MySQL

@alikon Does that mean we would collect non core issues here?

**Comment by alikon** [comment]
No... my curiosity was about what SQL standard query is not managed by core
only that

**Comment by alikon** [comment]
anyway we need start to think about MariaDB in a more "_professional_" way

**Comment by ghazal** [comment]
If I use MariaDB, I always modify these settings:
Global Configuration/System/Session Handler -> Session = Filesystem instead of Database<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36183">issues.joomla.org/tracker/joomla-cms/36183</a>.</sub>

**Comment by BrainforgeUK** [comment]
The problem in my case encountered with component model using the getListQuery() method and building the query with the standard Joomla database query building methods.

The problem appeared to be with a join to SQL view which included a group by. The tables contained no data so at that point do not expect to have to MariaDB configuration / tuning.

Good point though that the **table_definition_cache** might be different between the systems - not checked!

**Comment by Hackwar** [comment]
As was stated before, I don't see how this is a core issue or what we could do here. Can we close this?

**Comment by richard67** [comment]
Closing as not an issue with the CMS core. See previous comments.

**Comment by BrainforgeUK** [comment]
Ok to close.
