### ISSUE TITLE
Error: Missing field in database: Joomla\CMS\Table\Extension &#160; extension_id after update to php 8.1

### ISSUE THREAD

**Issue by carlitorweb** [joomla/joomla-cms#36185]
### Steps to reproduce the issue
Today my host updated the versión of PHP from 7.4.26 to 8.1.0, and this error: `Missing field in database: Joomla\CMS\Table\Extension &#160; extension_id.` started to show, for example, when you go to com_joomlaupdate

### Expected result
com_joomlaupdate show the last version to upgrade

### Actual result
Throw a error

### System information (as much as possible)
PHP 8.1.0
5.5.60-MariaDB
Joomla! 4.0.3 Stable 

### Additional comments
I aware of the proccess of the .htaccess, as I did not edit never the .htaccess in this site, I should do not have problem with this.

**Comment by zero-24** [comment]
@carlitorweb please try 4.0.4-rc that includes fixes for php 8.1 with 4.0.3 we are aware of PHP 8.1 issues.

**Comment by carlitorweb** [comment]
> @carlitorweb please try 4.0.4-rc that includes fixes for php 8.1 with 4.0.3 we are aware of PHP 8.1 issues.

Got it. But right now cant use the admin panel to update the version because this error. Is okay download the package 4.0.4-rc and upload trough FTP? I guess not, but asking just in case

**Comment by carlitorweb** [comment]
And I guess you mean, 4.0.5-rc1 right?

**Comment by carlitorweb** [comment]
I just find, when trying to save a new article, a similar error show:

`Missing field in database: Joomla\Component\Categories\Administrator\Table\CategoryTable &#160; extension.`

**Comment by zero-24** [comment]
Yes please downgrade the php version and update your site to the latest rc version of J4

Please do never use FTP to update Joomla.

**Comment by carlitorweb** [comment]
> Yes please downgrade the php version and update your site to the latest rc version of J4
> 
> Please do never use FTP to update Joomla.

Understood. In case there is not way to downgrade the PHP version, is there any other way to accomplish this?

**Comment by zero-24** [comment]
I'm not aware of an official supported way. The easiest thing is to take the backup you did before the change restore it on a local instance upload it to the latest version upload that version to the site.

Sure you can try to monkey patch the php8.1 changes and hope nothing else breaks but downgrade to PHP 7 and take that is the solution to go.

**Comment by carlitorweb** [comment]
Thank you, I will see what do. 
As note, for j3.10 also is happening this errors.

**Comment by zero-24** [comment]
Yes and also for 3.10 there is a RC version (public now) and a stable to be released next week with similiar patches.

**Comment by carlitorweb** [comment]
**A note for those with the same problem**

In you find yourself in the same situation, and cant downgrade the PHP version, the recomend way is a backup you had, update it in local, and then restore it in your site. 

But, in case you have not a up to date backup done, like in my case, what I did was make manually the change are listed in this PR, in those 4 files:

https://github.com/joomla/joomla-cms/pull/36041/files

Please note, this is not the recomend way, but I check first if this change alone break something in the site, before apply it. So far all was good, and the com_joomlaupdate is working again and I can do now the update.

**Comment by wojsmol** [comment]
You can also make a manual backup of website files and database and then restore it on environment with lower php version.

**Comment by zero-24** [comment]
So this issue can be closed now @carlitorweb ?

**Comment by carlitorweb** [comment]
> So this issue can be closed now @carlitorweb ?

Yes, thank you for your answers.

**Comment by martiniturbide** [comment]
Hi.

I started to experience the same problem on Joomla 3.10 while trying to reach  3.10.5 . 
I'm stuck in 3.10 with the same error.
- I can not downgrade PHP
- I can not upgrade to Joomla 4 yet. (My community uses an old browser and Joomla 4 does not display right in it)

Is there any other solution? 

Regards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36185">issues.joomla.org/tracker/joomla-cms/36185</a>.</sub>

**Comment by martiniturbide** [comment]
Hi

If I try to upgrade manually to 3.10.5 (Changing the files directly), do you think this error will be gone?

Regards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36185">issues.joomla.org/tracker/joomla-cms/36185</a>.</sub>

**Comment by martiniturbide** [comment]
Hi

I did something stupid, maybe not recommended, but I think it worked for me.

I was on Joomla 3.10 experiencing the "Missing field in database: Joomla\CMS\Table\Extension &#160; extension_id." Error.

First I took some backups.

I got "Joomla_3.10.5-Stable-Full_Package", unzip it and started to replace the 3.10 files to the 3.10.5 ones by hand. 
- Administrator, bin, cli and compoments
When I ended "components" the problem was gone, so I just grabbed "Joomla_3.10.x_to_3.10.5-Stable-Patch_Package" and install it with the normal Joomla procedure so I can be sure all the files are updated. 

It seems that now I have Joomla 3.10.5 working. I can add articles back. I'm still checking for any errors. 

Regards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36185">issues.joomla.org/tracker/joomla-cms/36185</a>.</sub>

**Comment by OldMan-Jakob** [comment]
Hi
I've just installed XAMPP Version 8.1.6 and installed a new version of Joomla 4.04
and am getting the "Missing field in database: Joomla\CMS\Table\Extension   extension_id." error
I can't install anything else.
I thought this issue had been resolved but apparently it's not.
What's my next step?
Regards
David<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36185">issues.joomla.org/tracker/joomla-cms/36185</a>.</sub>

**Comment by brianteeman** [comment]
Why are you installing an old version of Joomla? The current version is 4.1.5

**Comment by OldMan-Jakob** [comment]
Excellent question, Brian. I just searched for a link to joomla downloads and didn't check the version.
Problem solved!
Thank you.
