### ISSUE TITLE
Component menu on J! 4.0 not created like on J! 3.10

### ISSUE THREAD

**Issue by xillibit** [joomla/joomla-cms#36196]
### Steps to reproduce the issue

Install last beta 5 version of Kunena, generate components menus by using the tools part from Kunena dashboard.

### Expected result

On J! 3.10 the menu has a selection list nammed "Default Menu Item" : 

![image](https://user-images.githubusercontent.com/876395/144719443-35be0f00-e3b7-473c-a8e8-6179dd6bea9e.png)

### Actual result

On J!4.0 the  selection list "Default Menu Item" is missing : 

![image](https://user-images.githubusercontent.com/876395/144719577-ece0d713-86be-41fc-8b49-8568002d56f0.png)

### System information (as much as possible)

Joomla 4.0.5-dev

### Additional comments

Related to : https://github.com/Kunena/Kunena-Forum/issues/8164

**Comment by brianteeman** [comment]
It's not missing as it was not part of joomla 3. I can only assume it was a modification by kunena.

**Comment by brianteeman** [comment]
This is nothing to do with Joomla and is specific to kunena who have changed the menu item in k6 and should be closed here as there is nothing that can be done here.

**Comment by chmst** [comment]
as @brianteeman says .. closing this issue.

**Comment by xillibit** [comment]
I don't know why but in J!4.0, Joomla! doesn't load this file which make the display of the list "Default Menu Item" : https://github.com/Kunena/Kunena-Forum/blob/K6.0/src/site/tmpl/Home/tmpl/default.xml, there are no errors neither
I have found where is loaded in J!3.10 but in J!4.0 i don't find the place where this file should be loaded

**Comment by brianteeman** [comment]
I have no idea either. If I add the field to a core component it works perfectly.
