### ISSUE TITLE
[4.1] Tasks learn more button

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36204]
The "learn more" button on the scheduled tasks empty state currently points to the gsoc github repositary. It should point to a docs site link

**Comment by pritam825** [comment]
can you please mention the docs site link so that I can attach accordingly

**Comment by pritam825** [comment]
(https://docs.joomla.org/Main_Page) are you talking about this link?

**Comment by ditsuke** [comment]
> can you please mention the docs site link so that I can attach accordingly

@pritam825 

Apologies I've been away for a while, here's the link: https://docs.joomla.org/J4.x:Task_Scheduler

**Comment by pritam825** [comment]
Thanks @ditsuke

**Comment by Quy** [comment]
Please test PR #36666
