### ISSUE TITLE
[4.1] Tasks Scheduler, 35 x `@Todo` ?

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#36201]
Im concerned about the large amount of `@todo` tags that were still in the com_scheduler when it was merged, and now that it is merged, there doesn't seem to be any plan to address these. 

This is adding considerable technical debt in a feature that is not even released yet. 

@ditsuke 

An even scary @joomla/security `@todo`comment in plugins/task/requests/requests.php

```
// @todo this handling must be rethought and made safe. stands as a good demo right now.
		$responseFilename = Path::clean(JPATH_ROOT . "/tmp/task_{$id}_response.html");
```

There are 34 `@todo` tags in /administrator/components/com_scheduler alone. 

<img width="794" alt="Screenshot 2021-12-04 at 19 12 16" src="https://user-images.githubusercontent.com/400092/144721764-a1a2383d-e803-4a08-a9de-ab8debf0b2b6.png">

**Comment by ditsuke** [comment]
Thanks for tagging. I have my exams at Uni at the moment, but I plan on addressing the todos and some other things later in December when I'm free.

**Comment by richard67** [comment]
@ditsuke All the best wishes for your exams.
