### ISSUE TITLE
[4.1] Scheduled tasks Help

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36213]
The help button gives a 404 :(

**Comment by tecpromotion** [comment]
This help screen, right?
https://help.joomla.org/proxy?keyref=Help4.1:JHELP_COMPONENTS_SCHEDULED_TASKS_MANAGER

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36213">issues.joomla.org/tracker/joomla-cms/36213</a>.</sub>

![2022-01-16_19-16-37](https://user-images.githubusercontent.com/1752513/149672611-02df0935-c12f-4bab-9a9e-bbc9ed101e02.jpg)

**Comment by tecpromotion** [comment]
The page was created. The content comes afterwards.
The problem was solved by @coolwebcreations

**Comment by brianteeman** [comment]
Thanks for creating the page. Now to fix it in the cms
