### ISSUE TITLE
[4.1] Task Parameters duplicated

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36214]
The task parameters (if present) for a task are duplicated and are present on both the "Edit Task" tab and at the bottom of the "Advanced" tab. I assume they should only be on the "Edit Task" tab

## Edit Task
![image](https://user-images.githubusercontent.com/1296369/144751954-0ed1a359-660e-44a5-9025-4d1a40943ab9.png)

## Advanced
![image](https://user-images.githubusercontent.com/1296369/144751981-14018f65-5836-4321-9d58-77762a67b83f.png)

**Comment by AJAY007L** [comment]
@brianteeman, how to navigate to this edit task tab?

**Comment by ditsuke** [comment]
@AJAY007L 
> @ brianteeman, how to navigate to this edit task tab?

It's the default tab for an existing task.

**Comment by AJAY007L** [comment]
@ditsuke 
 Actually, I can't see anything to create a task in the system tab.
![Opera Snapshot_2021-12-24_112551_localhost](https://user-images.githubusercontent.com/60544908/147343851-d770a774-6100-4a3e-aae7-7108dd4126af.png)

**Comment by ditsuke** [comment]
> @ditsuke 
>  Actually, I can't see anything to create a task in the system tab.
> ![Opera Snapshot_2021-12-24_112551_localhost](https://user-images.githubusercontent.com/60544908/147343851-d770a774-6100-4a3e-aae7-7108dd4126af.png)
> 

You need to be on a 4.1-dev build for the Scheduler (it was added only recently with #35143)

**Comment by AJAY007L** [comment]
I also checked with 4.1-dev. The result is the same and also Joomla pic is not visible in the top-left corner. 

![Inked4 1_LI](https://user-images.githubusercontent.com/60544908/147354675-e7186e6d-babb-4f77-9c53-8ec8913865fb.jpg)

**Comment by ditsuke** [comment]
@AJAY007L 

> I also checked with 4.1-dev. The result is the same and also Joomla pic is not visible in the top-left corner. 
> 
> ![Inked4 1_LI](https://user-images.githubusercontent.com/60544908/147354675-e7186e6d-babb-4f77-9c53-8ec8913865fb.jpg)
> 
> 


If you updated via git to 4.1 you will still have to update the database (see "Database" under Maintenance in your screenshot) and build assets with npm (`npm ci`).

**Comment by brianteeman** [comment]
resolved elsewhere
