### ISSUE TITLE
[4.1] Delete Child Template

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36217]
If you create a child template and then decide it sucks there is no ability to delete the child template

**Comment by dgrammatiko** [comment]
> If you create a child template and then decide it sucks there is no ability to delete the child template

As a child template is an actual template the same workflow for a normal template will work here as well.
Eg:
- Goto: http://host.local/joomla-cms/administrator/index.php?option=com_installer&view=manage&filter_type=template
- Select the child and uninstall

**Comment by brianteeman** [comment]
Closing this - my fault. I tried to do what @dgrammatiko suggested before posting but i was checking on the wrong site

**Comment by PMWilliams123** [comment]
I know this is closed but it was very helpful as I was trying to delete a child template and was puzzled by the error which was something like Can't delete last style. Compounded by my lack of a full understanding between templates and styles, but that is another matter. My thought was could the error message be improved to point out that stuff about last style that to delete it must be uninstalled? Or is that too trivial?  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36217">issues.joomla.org/tracker/joomla-cms/36217</a>.</sub>

**Comment by dgrammatiko** [comment]
> My thought was could the error message be improved to point out that stuff about last style that to delete it must be uninstalled?

You could improve the message

**Comment by PMWilliams123** [comment]
@dgrammatiko
. I am sorry I don't understand your comment unless it is an attempt to take the piss out of an old man with limitations.

**Comment by dgrammatiko** [comment]
@PMWilliams123 what I meant was that the error message could be altered by you, probably we're talking about this: https://github.com/joomla/joomla-cms/blob/e9b9263a34ad919c7a8e6b817074f53eb1997565/administrator/language/en-GB/com_templates.ini#L49

**Comment by PMWilliams123** [comment]
Thank you for that clarification but it seems to miss the point. Which is that not only a daft old person like I was confused about the error message but Brian Teeman, the co-founder of of joomla, also found if less than helpful, if only briefly. What earthly good does it do for anyone else in the Joomla community (or in the whole wide world)  for me to add a language override (which I guess is what you are suggesting ) to just one of my sites. It will help me if I every forget again, which is always possible. What I was aiming at by my hastily typed comment was to help others who might encounter the same confusion. I thought that was the point of all this. As for proposing a different error message, I am not qualified to do that.

**Comment by brianteeman** [comment]
I'm afraid that you misunderstood what @dgrammatiko was saying - let me translate.

Please suggest a better text string that can be used. Then we can update Joomla to use your suggestion.

**Comment by PMWilliams123** [comment]
Sadly all too often I misunderstand and its getting more frequent as more brain cells check out.. I apologise for that.

As I said I "lack of a full understanding between templates and styles" hence I don't understated the message. "Can't delete the last style of a template." I though I was trying to delete the template and in fact hat is the solution  - uninstall the child template). Clearly I need to learn more about templates and styles, I need to add it to the lengthening list of other things I need better to understand. And that is why I also said "As for proposing a different error message, I am not qualified to do that."

**Comment by PMWilliams123** [comment]
An error message along the lines of "Can't delete the last style of a template, to remove the template you need to uninstall it." But as I don't understand "Can't delete the last style of a template" when I am trying to delete a template I am not  sure that it makes sense.

**Comment by brianteeman** [comment]
A style can be thought of as the configuration file for a template. Every template must have one (otherwise it doesnt know what template options to apply) and the cool thing is that you can have multiple configurations (styles) saved for each template.

"Can't delete the last style of a template. Did you intend to remove the template? Click here to uninstall the template"

??

**Comment by PMWilliams123** [comment]
Than you that is very helpful as usual and your error message is spot on.
Happy Christmas and a prosperous new year.
Philip

**Comment by brianteeman** [comment]
please test https://github.com/joomla/joomla-cms/pull/39491

**Comment by PMWilliams123** [comment]
Tried to test: Downloaded https://github.com/joomla/joomla-cms/releases/tag/4.3.0-alpha1 and installed it, Created a child template, Tried to delete it and got "Can't delete the last style of a template." Added a language override for  COM_TEMPLATES_ERROR_CANNOT_DELETE_LAST_STYLE in System> Language: Overrides English (United Kingdom_ - Administrator to "Can't delete the last style of a template. Did you intend to remove the template? Click here to uninstall the template." except i don't know how to add the appropriate relative link to "click here".  Tried to delete again and the appropriate message appeared without a working "click here" obviously.

**Comment by brianteeman** [comment]
thats because you tested the wrong download - it has not been accepted yet so it is not in a release.

You can download a testing release with the changes by going to #39491 and clicking on the download link
![image](https://user-images.githubusercontent.com/1296369/209557134-599666c6-2d62-441a-9697-b19069afea36.png)

**Comment by PMWilliams123** [comment]
Thanks, please excuse my stupidity. doing that now.

**Comment by PMWilliams123** [comment]
Thank you it worked as expected. Sorry not to have responded sooner to you earlier messages to test the change but Christmas day rule in our household is no computers to be switched on.
