### ISSUE TITLE
[4.1]Task Manager Sort

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36210]
The task manager has various sort options but some dont make sense

![image](https://user-images.githubusercontent.com/1296369/144744746-9084369c-c6b7-4387-89d9-71f7942900a7.png)

### Ordering
I can't see any reason to have any ordering. If that is correct then the ordering sort should be removed AND the ordering column should be removed

### Task Priority
There is no column displayed for the priority so the ordering doesnt make sense. Either the sort should be removed or the column should be added

**Comment by chmst** [comment]
There is no "Test this" button. No clue why this happens from time to time. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36210">issues.joomla.org/tracker/joomla-cms/36210</a>.</sub>

**Comment by brianteeman** [comment]
@chmst thats not related to this is it?

**Comment by chmst** [comment]
I cannot give a "tested with success" in the issue tracker

**Comment by chmst** [comment]
Closing  as there is a PR #36209

**Comment by chmst** [comment]
Sorry - there are too many similiar issues and pr titles

**Comment by ditsuke** [comment]
@brianteeman 
 
> ### Ordering
> I can't see any reason to have any ordering. If that is correct then the ordering sort should be removed AND the ordering column should be removed

Ordering was added to make it easier to group together related tasks and aid management. Tagging @particthistle as he was in support of this.

> ### Task Priority
> There is no column displayed for the priority so the ordering doesnt make sense. Either the sort should be removed or the column should be added

I'll add a column for priorities!

**Comment by brianteeman** [comment]
Ordering
I can see the use case but we would normally use categories for that. Misusing "ordering" for that breaks expected behaviour of the ordering field

**Comment by brianteeman** [comment]
closed see #37224
