### ISSUE TITLE
[4.1] Duplicate template

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36216]
With the introduction of child templates by @dgrammatiko it is no longer possible to duplicate a template :(
The create duplicate button has been replaced by a child template button

## Before
![image](https://user-images.githubusercontent.com/1296369/144752963-2bb1261f-438a-4daf-b879-2168bb140fe3.png)

## After
![image](https://user-images.githubusercontent.com/1296369/144752974-747965e6-eee5-41e0-a1ea-5af3e72023b4.png)

**Comment by dgrammatiko** [comment]
> The create duplicate button has been replaced by a child template button

It's still there for templates that don't support children. For the templates implementing the new mode this is not needed, I mean forking any extension shouldn't be a click of a button (but that's just me)

**Comment by bembelimen** [comment]
I agree on the parent template, but probably copying a child template would be a nice addition.
+ The buttons in the forking modal has to be renamed (like "Create" instead of "Child Template")

**Comment by dgrammatiko** [comment]
> I agree on the parent template, but probably copying a child template would be a nice addition.

What I'm missing is a way to apply a specific style from the parent (or a child [debatable?]) when a new child is created (now it starts with the vanilla style of the parent). That would speed up things for the users that need to replicate spawn children with some minor changes. Also should be quite easy to implement without any major hacks (get the list of the style rows, render it into a select tag, and after successful installation apply the style params to the new template. 5mins work [just kidding it's not 5mins...] )

**Comment by bembelimen** [comment]
> 
>  [...] 5mins work [just kidding it's not 5mins...] )

Sounds interesteing....I'm also ok with 6 minutes...

**Comment by brianteeman** [comment]
I can think of several scenarios whereby you would want to duplicate a template  and not create a dependent child

**Comment by dgrammatiko** [comment]
> I can think of several scenarios

I might be awfully wrong here but I think that with child templates (Joomla needs a better name for this, the term is not even correct English). Could you briefly describe these scenarios?

**Comment by brianteeman** [comment]
### Sample Scenario
As an agency I have a generic template that I use as a base template for all clients that contains lots and lots of layouts etc. I install that template and then copy the template and customise it for the specific site. I keep the base template installed during development so that I can easily revert changes etc. Once the site is live I can then delete the generic base template and just leave the client specific version. If I update the base template to support child (dependent) templates this would not be possible.

**Comment by brianteeman** [comment]
### Question?
Can you install a template with child templates in one step?

**Comment by dgrammatiko** [comment]
> Can you install a template with child templates in one step?

Yes but you have to create a package (basically an XML file and all the zips)

**Comment by dgrammatiko** [comment]
> If I update the base template to support child (dependent) templates this would not be possible.

Yes that workflow is not possible anymore but I might have a better proposal for this or similar cases.

**Comment by wilsonge** [comment]
Worth noting whilst not directly related to this issue it comes from a similar'ish background. The Duplicate template functionality has been the blocker to us being able to add core support for namespacing templates with 4.0 (e.g. https://github.com/joomla/joomla-cms/pull/30816 here we also hide the modal if the template is namespaced - because we'd end up with duplicate namespaces being autoloaded).
