### ISSUE TITLE
[4.1] Child templates language files

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36218]
Shouldnt the child template either copy the parent language files or use the language files of the parent? Currently neither happens.

![image](https://user-images.githubusercontent.com/1296369/144753398-f27c04e7-31c9-499b-ad09-39f7309be264.png)
![image](https://user-images.githubusercontent.com/1296369/144753486-2944b490-0a7a-4e73-9f0b-a0f64d4e4f43.png)

It does however appear to fall back to the parent language file for the template styles

![image](https://user-images.githubusercontent.com/1296369/144753482-c43814b8-b577-47ca-ab42-fc6424adfe05.png)

**Comment by dgrammatiko** [comment]
@brianteeman the code is loading the parent language file (unless you override them locally in the child), what I mean is that they should follow the general inheritance model of all the other files. The code that deals with it is (per model):
https://github.com/joomla/joomla-cms/blob/40eff93677773b400fddcc4123af06a7216eec52/administrator/components/com_templates/src/Model/StyleModel.php#L420-L425

What's the URL for this screenshot?

**Comment by brianteeman** [comment]
First screenshot is from the template code view. The second is from the template style view

**Comment by dgrammatiko** [comment]
Ok, so, https://github.com/joomla/joomla-cms/blob/40eff93677773b400fddcc4123af06a7216eec52/administrator/components/com_templates/src/Model/TemplateModel.php#L401-L403

should be 
```php
$lang->load('tpl_' . $template->element, $client->path)
||	(!empty($template->xmldata->parent) && $lang->load('tpl_' . $template->xmldata->parent, $client->path))
||	$lang->load('tpl_' . $template->element, $client->path . '/templates/' . $template->element)
||	(!empty($template->xmldata->parent) && $lang->load('tpl_' . $template->xmldata->parent, $client->path . '/templates/' . $template->xmldata->parent));

```

**Comment by dgrammatiko** [comment]
There's a PR: https://github.com/joomla/joomla-cms/pull/36219
