### ISSUE TITLE
[4.0] Custom Field display in 3rd Pty component

### ISSUE THREAD

**Issue by garkell** [joomla/joomla-cms#36224]
### Steps to reproduce the issue
In the admin side edit of a record, using the Tabs to display various fieldsets for your component, fails to add a tab containing the custom fields within a group set within 3rd party component.
Need a 3rd party component designed for J4 with Custom Fields set up.  Add a new custom field within a custom field group.

### Expected result
A new tab displaying the custom fields within the group if any exist just like com_users.

### Actual result
Custom field displays at the bottom of each existing tab with notices:
Notice: Undefined index: Joomla\CMS\HTML\Helpers\Bootstrap::startTabSet in mydomain\libraries\src\HTML\Helpers\Bootstrap.php on line 860
Notice: Trying to access array offset on value of type null in mydomain\libraries\src\HTML\Helpers\Bootstrap.php on line 860
Notice: Trying to access array offset on value of type null in mydomain\libraries\src\HTML\Helpers\Bootstrap.php on line 860

### System information (as much as possible)
J4.0.4
PHP 7.4.9
MySql 8.0.21
Apache 2.4.46
Windows 10 using WAMP 3.2.3

### Additional comments
This may be related to #33409 which has been closed due to no "interest".  Sorry just trying to learn how to incorporate Custom Fields into one of my components.

Code used in the admin side edit of a single record (edit.php):

echo HTMLHelper::_('uitab.startTabSet', 'myTab', array('active' => 'general'));

echo HTMLHelper::_('uitab.addTab', 'myTab', 'general', Text::_('COM_MYCOMP_TITLE', true));

echo $this->form->renderFieldset('general');

echo HTMLHelper::_('uitab.endTab');

$this->ignore_fieldsets = array('general');
echo LayoutHelper::render('joomla.edit.params', $this);

echo HTMLHelper::_('uitab.endTabSet');

**Comment by garkell** [comment]
HTMLHelper::_('uitab.startTabSet', 'myTab', array('active' => 'general'));

HTMLHelper::_('uitab.addTab', 'myTab', 'general', Text::_('COM_MYCOMP_TITLE', true));

$this->form->renderFieldset('general');

HTMLHelper::_('uitab.endTab');

$this->ignore_fieldsets = array('general');
LayoutHelper::render('joomla.edit.params', $this);

HTMLHelper::_('uitab.endTabSet');

**Comment by chmst** [comment]
If I understand correctly, this is not an issue of Joomla but a question how to use custom fields in your component?

**Comment by garkell** [comment]
Hi, well I'm not sure.
I am trying to utilise com_fields (Custom Fields) in my component and followed what has been done in com_content I think from memory (which fails often).  I gave up on it due to other pressures but would like to work into my component the ability of using custom fields.
If you feel this is not an issue or appropriate here, please feel free to close it and when I get back to having the time to work on it, I can raise the issue/question then.

**Comment by brianteeman** [comment]
> If you feel this is not an issue or appropriate here, please feel free to close it and when I get back to having the time to work on it, I can raise the issue/question then.

For me this should be closed and @garkell can always ree-open it if needed at a future date
