### ISSUE TITLE
[4.1] Child template empty folders

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36230]
When you create a child template it creates several folders for css, images and js which are empty

![image](https://user-images.githubusercontent.com/1296369/144827379-79e0e08f-9b28-405e-bfc3-d851578e8e8d.png)

The problem is that if you click on any of those folders nothing happens and it would be reasonable to assume that its broken.

Possible solutions would be to have a "this folder is empty" message when you click. Or add a blank(ish) index.html file to the folder

**Comment by dgrammatiko** [comment]
> Or add a blank(ish) index.html file to the folder

Sure, but `.html` files are filtered for some reason. The only reason I added them was to remove the step that users will have to create these folders. The exclusion of HTML files from the list is kinda problematic (pretty sure there was a reason, security I guess, they did it but still...)

**Comment by brianteeman** [comment]
Forgot about the *.html restriction. 
I guess it needs to be a "no files found" type solution then

**Comment by brianteeman** [comment]
Just realised its not strictly a child template issue but its more likely to be observed with child templates
