### ISSUE TITLE
[4.1] Schedule tasks error reporting

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36238]
### Steps to reproduce the issue
Create a new image size action
Do NOT select a path
Save and run a test

### Expected result
Error message that the image path does not exist

![image](https://user-images.githubusercontent.com/1296369/144852162-0635c2d4-357d-4cf3-ba55-e1346fd93aee.png)

### Actual result
No error message on screen. 
Not much point in doing a test if you dont get to see any errors

### Additional comments
The error is present in the logs

![image](https://user-images.githubusercontent.com/1296369/144852064-d495acf2-921c-420a-a8c7-856cfc47b070.png)

**Comment by pritam825** [comment]
I understood the error, and found the error and changes the code but can you please guide me how can I check this, I'm little confuse with this, that where is the logger section, can you please help me with this and provide the screenshot so that I will be able to reach the logger section and verify my code

**Comment by ditsuke** [comment]
> I understood the error, and found the error and changes the code but can you please guide me how can I check this, I'm little confuse with this, that where is the logger section, can you please help me with this and provide the screenshot so that I will be able to reach the logger section and verify my code

@pritam825 The scheduler log is currently stored in the `administrator/logs/joomla_scheduler.php` file. Each time the scheduler triggers a task, the task logs its progress to this file, and additionally the task log file if it is enabled in the configuration for that specific task. As I understand this issue, we need an additional logger than echoes the logs to stdout during a manual ("test") run. Can you share your solution?

**Comment by brianteeman** [comment]
Closed as the directory is now a required field
