### ISSUE TITLE
[4.1] Child templates and editor.css

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36233]
Tinymce only loads the editor.css from the parent template (or the system template if not present)

This is another dependency on the parent template that a user will not understand. (I tested and creating an editor.css in the child is ignored). It would not be unreasonable for a user to not realise that they have to make the change in a template called **cassiopeia** when they are using a template called **andromeda**

**Comment by dgrammatiko** [comment]
@brianteeman did you place an `editor.css` in the child's CSS folder eg `media/templates/site/andromeda/css/editor.css`?
Does renaming to `editor.min.css` work (assuming not in debug mode, if in debug the editor.css should be loaded, IIRC the new logic tries to load the compressed/uncompressed one)?

If none of the above this is a bug...

**Comment by brianteeman** [comment]
renaming to editor.min.css worked but both should work

![image](https://user-images.githubusercontent.com/1296369/144835749-426ccebe-1ad9-49d8-86ee-c38037f6d0a9.png)

**Comment by brianteeman** [comment]
Has been resolved elsewhere

**Comment by brianteeman** [comment]
re-opening because the bug is still present
