### ISSUE TITLE
[4.1] Schedule task logs

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36239]
### Steps to reproduce the issue
Create a new action log with the default settings and run it a few times. Then check the administrator/logs folder 

### Expected result
A log file 

### Actual result
No log file

### Additional comments
Either its a bug or the field name needs clarification

When I saw this option I assumed (perhaps wrongly) that **all** scheduled tasks would be logged into a **single** log file

![image](https://user-images.githubusercontent.com/1296369/144852481-3d94b81a-08d0-450c-81b8-897a0ee20402.png)

And I only needed to set individual log files if I wanted to keep the logs for each action separate

![image](https://user-images.githubusercontent.com/1296369/144852810-3fe19b48-43db-4640-8ff5-35f41018ee1b.png)

**Comment by brianteeman** [comment]
Closed as its either been resolved elsewhere or I've forgotten exactly what this was

**Comment by heelc29** [comment]
> Closed as its either been resolved elsewhere or I've forgotten exactly what this was

Do you think that's no log file is created when you do a "Test Run" or "Run Task" manually?
