### ISSUE TITLE
[4.x] Template preview broken

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36257]
### Steps to reproduce the issue
With no modules and template preview enabled all module positions should be indicated. They're not and this makes the preview completely pointless

### Expected result
![image](https://user-images.githubusercontent.com/1296369/145107543-973cde8d-356d-4eaf-abc9-77d0d8f0cf3a.png)

### Actual result
![image](https://user-images.githubusercontent.com/1296369/145107558-a34dc29b-7f53-4402-bb32-0c28112a1ff4.png)

### Additional comments
The problem appears to originate with #35225 by @fedik 

Possibly here https://github.com/joomla/joomla-cms/pull/35225/files#r693565865

**Comment by chmst** [comment]
Duplicate to #36071?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36257">issues.joomla.org/tracker/joomla-cms/36257</a>.</sub>

**Comment by Fedik** [comment]
#35225 that just fixing a cache, 

The issue a bit different, since #19416 some positions rendered only if they contain any real content,
So in result you see preview only for these positions.

Possible fix, is to update if() statement a bit, example https://github.com/joomla/joomla-cms/blob/913f8e7fe1cf14d60fbe1c116bb2b8530a4437ca/templates/cassiopeia/index.php#L187-L191

Change to something like:
```php
if ($templatePreview || $this->countModules('banner', true))
```

> Duplicate to #36071?

Yes, it the same.

**Comment by brianteeman** [comment]
> #35225 that just fixing a cache,

Well the problem didnt exist before and it does after 

> Possible fix, is to update if() statement a bit, example

That "fix" is specific to cassiopeia so it doesnt solve the problem. 

> The issue a bit different, since #19416 some positions rendered only if they contain any real content,

Ok thanks for the hint I will take a look there as this issue really bugs me

**Comment by Fedik** [comment]
> That "fix" is specific to cassiopeia so it doesnt solve the problem.

That fix is specific for templates that use this new feature.

I wonder if old behavior still show all positions if the position does not have any module assigned in backend?
`if ($this->countModules('banner'))`

**Comment by Fedik** [comment]
> I wonder if old behavior still show all positions if the position does not have any module assigned in backend?

Yea, it is, it have this horror hack :smile: 
https://github.com/joomla/joomla-cms/blob/7978f281c49276756cd6fe6faa61a8c30ec77a53/libraries/src/Helper/ModuleHelper.php#L101-L111
So it force empty module, if position is empty but `&tp=1` exists
hmhm

**Comment by Fedik** [comment]
Well, we can extend that hack,
Can someone try to add next code and check if it works:
```php
$result[0]->contentRendered = true;
$result[0]->content = 'Dummy module';
```

hm no

**Comment by Fedik** [comment]
Please test #36268
