### ISSUE TITLE
[4.1] Improve aria label for search input in filter forms

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#36254]
### Steps to reproduce the issue
Aria labelled by in filter forms as reported #36215  in was fixed with #36225.

![image](https://user-images.githubusercontent.com/1035262/145057631-5986d4dd-8c56-429c-9e9c-852e1ef567e2.png)

A better solution is possible as suggested by @laoneo here 
https://github.com/joomla/joomla-cms/pull/36225#discussion_r763698670

**Comment by alikon** [comment]
please test #36259
