### ISSUE TITLE
[Question/Feature Request] joomla.form.field.subform.repeatable Expand/Collapse Feature

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#36266]
Hi,

is there a way how to make repeatable Joomla subform field expandable/collapsible?

The problem with long repeatable subform fields is the ordering. If the form field item's height is the same like browser height or higher, then it is very difficult to move/order the items.

![img](https://i.imgur.com/BwuBbQG.png)

The solution for this issue could be button (next to add, close and move button) which will make the item collapsed so it can be moved/ordered.

Thank you, Jan

**Comment by Fedik** [comment]
Nope, it not exists.
But in theory you can apply a script over subform section to toggle/collapse.
```javascript
document.addEventListener('joomla:updated', (event) => {
  if (event.target.dataset.baseName === 'blablaField') {
    // ... apply toggle script to subfrom row (event.target)
  }
});
```

**Comment by PhocaCz** [comment]
Hi, thank you for the info. Unfortunately I don't know much about Joomla core Javascript functions and the system, so I have created system plugin for my user's needs. 

If someone will be interested and wants to implement it into core, please feel free to contact me for more info. The feature I asked here, looks like this (see YouTube video):

[![Phoca Collapse System plugin](http://i3.ytimg.com/vi/aq_uks3gM1o/hqdefault.jpg)](https://youtu.be/aq_uks3gM1o)

**Comment by Fedik** [comment]
What you made is also good ;)
