### ISSUE TITLE
[4.0] "Upload&Install" button in manual Joomla Update is enabled and clickable without the backup opt-in

### ISSUE THREAD

**Issue by simbus82** [joomla/joomla-cms#36274]
### Steps to reproduce the issue

Go to Joomla Update in admin, go to "Update your site by manually uploading the update package."
Select a package, don't check the "I'm prepared for the update and have made a backup.", try to click the "Upload & Install".

### Expected result

"Upload & Install" is disabled and become enabled only after putting a check in "I'm prepared for the update and have made a backup."

### Actual result

"Upload & Install" is enabled without putting a check in "I'm prepared for the update and have made a backup". 
I can click the button but i have no visual feedback.
![image](https://user-images.githubusercontent.com/1375730/145380224-f3ef0168-416c-45f6-8548-8059d909e4c8.png)

### System information (as much as possible)
Joomla 4.0.4

**Comment by Quy** [comment]
Please test PR #36531. Thanks.

**Comment by Quy** [comment]
Related #35055

**Comment by Shubhamverma2796** [comment]
please test #36860. Thanks in advance.

**Comment by richard67** [comment]
Closing as having a pull request.
