### ISSUE TITLE
[4.1] btn-group for radio fields is broken

### ISSUE THREAD

**Issue by OctavianC** [joomla/joomla-cms#36277]
### Steps to reproduce the issue
- Go to Content - Media - Click on the three dots on an image and choose Edit item
- Go to the Rotate tab
- Look at the Angle Buttons field

### Expected result
4.0.4
![image](https://user-images.githubusercontent.com/1422378/145406306-bfcbde26-cf18-46af-b03f-c130fdceb6d8.png)
HTML is generated correctly:
```
<div class="btn-group radio">
```

### Actual result
4.1 beta
![image](https://user-images.githubusercontent.com/1422378/145406339-6559db6f-1ad5-4a2c-a29a-093434186699.png)
HTML is missing the class attribute:
```
<div btn-group radio>
```

### Additional comments
Seems related to PR #35947

**Comment by brianteeman** [comment]
Confirmed

**Comment by joomdonation** [comment]
Sorry, my bad. PR https://github.com/joomla/joomla-cms/pull/36288 should fix it. Please test. Thanks!
