### ISSUE TITLE
[4.1] Template override missing functionality

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36287]
### Steps to reproduce the issue
Create an override in cassiopeia for com_content articles

## Expected result as seen in J4.0

![image](https://user-images.githubusercontent.com/1296369/145596033-5a040488-33a5-446f-b290-bc62a26478c9.png)

### Actual result as seen in J4.1

![image](https://user-images.githubusercontent.com/1296369/145595926-aabe197d-c75b-4de6-b1e8-3e70af8a6e67.png)

**Comment by simbus82** [comment]
Same here, i have the yesterday nightly build of 4.1. The override viewer/comparison is missing, with or without child templates.

**Comment by brianteeman** [comment]
Can someone please add the release blocker label

**Comment by joeforjoomla** [comment]
Confirmed. Probably due to child template feature.

**Comment by dgrammatiko** [comment]
Please test https://github.com/joomla/joomla-cms/pull/36290

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36290 . Thanks in advance.
