### ISSUE TITLE
Web links component global target parameter doesn't work in module

### ISSUE THREAD

**Issue by dolmenhir** [joomla/joomla-cms#36291]
Global target status of "web links" set in the component's parameters do not work on module:
- if the global target parameter is set on "new window" links are opened in "parent window" from the "web links" module.
note: that works if target is set inside the link parameters.

### System information (as much as possible)
Joomla 3.10.3
Component/module version : web links 3.9.0
Php 7.4.x and 8.x

**Comment by joomdonation** [comment]
@dolmenhir Could you please submit this issue to weblinks repo https://github.com/joomla-extensions/weblinks ? I believe I fixed this issue for Joomla 4, just need to backport this change to the version for Joomla 3.

**Comment by dolmenhir** [comment]
ok, no problem.
Done !

**Comment by joomdonation** [comment]
Thanks @dolmenhir
