### ISSUE TITLE
[4.0.5] update not working

### ISSUE THREAD

**Issue by conseilgouz** [joomla/joomla-cms#36305]
### Steps to reproduce the issue

Update from J4.0.4 to J4.0.5

### Expected result

Update OK

### Actual result

Update not working : error message in console
Uncaught TypeError: window.pingExtract is not a function
    at HTMLDocument.<anonymous> (admin-update-default.min.js?3d6c129acbaece9e88379bfb3adbb7c7e0c160c3:1)

### System information (as much as possible)
J4.0.4, PHP 8.0.3

**Comment by zero-24** [comment]
Hi, please check whether the htacess has thew new extract.php (the old value was the "restore.php") been allowed. More details here: https://www.joomla.org/announcements/release-news/5850-changes-to-update-process-that-you-need-to-be-aware-of.html

**Comment by conseilgouz** [comment]
Hi, 
I use default .htaccess.

**Comment by Fedik** [comment]
Did you made patch update in past?
Please reupload whole `/media` folder from 4.0.4 release. And then try update to 4.0.5

It sounds like issue #35920

UPD: Or probably more easy, upload only `/media/com_joomlaupdate` folder from 4.0.4 release, and then try update to 4.0.5

**Comment by conseilgouz** [comment]
I tried to copy media/com_joomlaupdatedirectory. It did not work.
Copied J4.0.4 full media directory : everything OK
Closing issue

**Comment by conseilgouz** [comment]
For info, i updated from 3.10.2 to 4.0.3 (Oct, 14th), then 4.0.4 (Oct. 26th) using "small update files".
