### ISSUE TITLE
php script dont work anymore

### ISSUE THREAD

**Issue by rcarmoPT** [joomla/joomla-cms#36309]

**Comment by rcarmoPT** [comment]
this page stop working
https://www.kronoracing.com/online

**Comment by rcarmoPT** [comment]
Code on page: 

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>KronoRacing - Actualização Tempos Online</title>
<script language="javascript" src="js/jquery.timers-1.0.0.js"></script>

<script type="text/javascript">
jQuery(document).ready(function()
{
    jQuery(".atualiza").everyTime(5000,function(i){
        jQuery.ajax({
         url: <?php echo('"php/refresh.php"')?>,
         cache: false,
         success: function(html){
            jQuery(".atualiza").html(html);
         }
        })
    })
});
</script>
</head>
<body>
<?php
echo ("<div class='atualiza'><h6>Aguarde por favor<br>A redirecionar para o Servidor de Dados...</h6></div>");
?>
</body>
</html>

**Comment by Quy** [comment]
Please ask support questions at [Joomla forum](https://forum.joomla.org/).
