### ISSUE TITLE
Are php extensions escapeshellcmd() and escapeshellarg() necessary for joomla 4?

### ISSUE THREAD

**Issue by gwstyles** [joomla/joomla-cms#36307]
### Steps to reproduce the issue
Install some extensions compatible with j4.

### Expected result
They work

### Actual result
0 Call to undefined function PHPMailer\PHPMailer\escapeshellcmd()

### System information (as much as possible)
J 4.0.4
PHP 8.0.13

### Additional comments
A little bit of history. I have been testing J4 since beta,I have discovered a few extensions that cause this error. The first was easycontact from les arbres who worked through the weekend to fix it,the second was RS forms pro who fixed it after a couple of days.I now have a booking extension that is doing the same (I wont name them)and they say I have to have these php extensions enabled on the server for it all to work because this is the way joomla does (I don't think so). I have a few J4 sites that do not need these ext to be enabled on the server and all work fine.This is what their devs say ; Hello,

it's true, we use the setSender() native Joomla function, but the PHP function that was missing (before you enabled it) was called by Joomla itself. Those are PHP functions which are enabled within any web server (both Joomla and WordPress use the same exact PHP functions to send emails), so there's nothing much that either you, or us, can do to avoid using them, otherwise you should disable the mailing functionalities within any Joomla or Wordpress plugin.
I don't think this is correct but do not have sufficient knowledge to argue the point.I have been told by friends that enabling these php exts are a possible security risk??
Would somebody who knows tell me what is correct and what is not.Thanks gws.

**Comment by brianteeman** [comment]
Look at the PHP web site to see what these functions are and why they exist.

Hint: never trust a friend

**Comment by gwstyles** [comment]
@Brian, thanks for your reply, I did look at the php site to understand what they do,it appears to me they are used to sanitise imputed code/url etc.Further searching suggested they were ineffective and possibly open to abuse. All this is above my head.The question is does J4 require this or not? Thanks gws.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36307">issues.joomla.org/tracker/joomla-cms/36307</a>.</sub>

**Comment by brianteeman** [comment]
if you are using anythign that uses phpmail then they are needed. If you use smtp then they are not

**Comment by gwstyles** [comment]
Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36307">issues.joomla.org/tracker/joomla-cms/36307</a>.</sub>

**Comment by richard67** [comment]
@gwstyles Is your question answered and you (or we) can close this issue?

**Comment by gwstyles** [comment]
Good day Richard, I don't know how to close it,new to this board.Please close for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36307">issues.joomla.org/tracker/joomla-cms/36307</a>.</sub>

**Comment by richard67** [comment]
Closing as agreed above.
