### ISSUE TITLE
[4.0] Javascript error - Uncaught TypeError: this.searchField is null

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#36304]
### Steps to reproduce the issue

For a component view create a filter form without a field with name _search_.

### Expected result

Works OK with the other filter fields.

### Actual result

Get Javascript error **Uncaught TypeError: this.searchField is null** on line 105 of searchttols.js

### Additional comments

One way round this is to create a hidden filter field named _search_.

&lt;field name="search1" type="hidden" disabled="disabled" /&gt;

Better way would be to change the line in searchtools.js to allow for this situation.

      if (this.searchField) {
        this.searchString = this.searchField.value; // Do some binding
      }

**Comment by Fedik** [comment]
One more thing, if a filter form does not contain "search" field, then whole search is not rendered, or I am wrong?
I just tried to test on `administrator/components/com_content/forms/filter_articles.xml`, and when I rename/remove `search` field then whole filter disappeares.
 
js error can be fixed easily, but the filter will not be shown anyway.

I not sure if it a bug or feature :)

**Comment by BrainforgeUK** [comment]
Using a custom layout ...

```
&lt;?php
echo LayoutHelper::render('searchtools.custom', array('view' => $this));
?&gt;
```

Did not want to touch the Javascript.

**Comment by Fedik** [comment]
Okay, understood. I will make js fix a bit later.

Or you can do PR, as you already have a fix :wink: 

```javascript
this.searchString = this.searchField ? this.searchField.value : '';
```

**Comment by pritam825** [comment]
I have changed this, can I do PR

**Comment by BrainforgeUK** [comment]
Yes you can do the PR thanks, not setup for it at the moment - just tested the line from Fedik on a demo site.

**Comment by Fedik** [comment]
please test #36335
