### ISSUE TITLE
[4.0]"This is already a Punycode string" when email domain name contains accented characters

### ISSUE THREAD

**Issue by conseilgouz** [joomla/joomla-cms#36301]
### Steps to reproduce the issue
In configuration, if email domain name contains accented characters, test mail doesn't send any mail, nore display any message (no success message, no error message). 

Other use of phpmailer will throw "This is already a Punycode string" error.

### Expected result

Test message sent and success message displayed.

### Actual result

No error message, no email sent

### System information (as much as possible)

Joomla 4.0.4, 

### Additional comments

When trying to send mail via phpmailer, libraries/vendor/algo26-matthias/idna-convert/src/Punycode/ToPunycode.php throw AlreadyPunycodeException, so email sending process stops.
As email is stored in database in 'punycode format', phpmailer will never send mail.

Replacing line 37 "throw new AlreadyPunycodeException('This is already a Punycode string', 100);" by "return false" should solve this issue.

**Comment by conseilgouz** [comment]
another way to fix it is to check string before calling IdnaConvert in libraries/src/String/PunycodeHelper.php 
`	public static function toPunycode($utfString)
	{
	    if (!preg_match("/[[a-zA-Z0-9-]+$/", $utfString)) {
    	    return (new ToIdn)->convert($utfString);
	    }
	    return $utfString;
	}
`

**Comment by alikon** [comment]
please test #36303

**Comment by FrankReisenhofer** [comment]
@conseilgouz :This issue is still in version 4.1.4.

Looks like the PR was not merged.

Should I open a new Issue or can someone please reopen it.

**Comment by alikon** [comment]
reopened

**Comment by conseilgouz** [comment]
This issue has been reopened, but not its PR #36303

**Comment by FrankReisenhofer** [comment]
@alikon : Could you please help here and reopen the PR #36303

**Comment by alikon** [comment]
done
