### ISSUE TITLE
[4.0.4] Search function in Plugin names is case sensitive for Russian language (English is OK)

### ISSUE THREAD

**Issue by DSist** [joomla/joomla-cms#36300]
### Steps to reproduce the issue

System - Manage - Language - Administrator - Set Russian language as default
System - Manage - Plugins - Search in plugin name

Test strings:

1. joomla
2. Joomla
3. пользователь
4. Пользователь

### Expected result

1. All plugins with the word "Joomla" are shown
2. All plugins with the word "Joomla" are shown
3. All plugins with the word "Пользователь" are shown
4. All plugins with the word "Пользователь" are shown

### Actual result

1. All plugins with the word "Joomla" are shown
2. All plugins with the word "Joomla" are shown
3. No plugins are found
4. All plugins with the word "Пользователь" are shown

### System information (as much as possible)

Joomla 4.0.4

### Additional comments

The problem may not only be with the plugin names provided the engine uses the same comparing string algorithm throughout the system.

![search1](https://user-images.githubusercontent.com/95962014/145728629-84b1e90c-35d8-492b-831d-535268a46a8e.png)
![search2](https://user-images.githubusercontent.com/95962014/145728635-6c7d8395-af24-4295-8b66-b2ba9ea3ddc3.png)

**Comment by infograf768** [comment]
Apparently, this problem does not exist with modules.
![Screenshot 2021-12-13 at 10 09 03](https://user-images.githubusercontent.com/869724/145783474-4b62c92e-1075-4278-ae43-1c95f2dccd75.png)

**Comment by Kostelano** [comment]
Joomla 3 has exactly the same problem.

**Comment by Hackwar** [comment]
I've created a PR #44525 to fix this. Please test. Since we have a PR, I'm closing this issue. Thank you for reporting.
