### ISSUE TITLE
[4.0]Missing title attribute of image names in Media Manager

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#36302]
### Steps to reproduce the issue
Hi,

not sure, if I miss some parameter or option, but I don't see full image names in Media Manager. The question is, why the image names don't include "title" attributes to display full title when hovering.

### Expected result
When I hover over the image title, the title attribute will display full image name

![img](https://i.imgur.com/bwN3XFA.png)

### Actual result
When I hover over the image title, no full image name is displayed
![img](https://i.imgur.com/ZN7zAxB.png)

### System information (as much as possible)
Joomla 4.0.4

Jan

**Comment by brianteeman** [comment]
I can't think of any good reason for the title not to be displayed

**Comment by brianteeman** [comment]
> I can't think of any good reason for the title not to be displayed

except for the fact the image is a background and you are actually hovering over a layer on top of the image. So even if you put the title it will never be displayed

**Comment by PhocaCz** [comment]
> except for the fact the image is a background and you are actually hovering over a layer on top of the image. So even if you put the title it will never be displayed

The "title" attribute is missing on file name text below the image not on image itself. This way, it works even in Joomla 3:

So adding a title attribute to "media-browser-item-info" div should do the trick:
![img](https://i.imgur.com/ay5MbtA.png)

![img](https://i.imgur.com/xSvtoj3.png)

Joomla 3 - full title when hovering file name:
![img](https://i.imgur.com/AEPJoP6.png)

**Comment by brianteeman** [comment]
I didnt think of trying to put the title on the div. Doing that will display the title BUT its not very intuitive as you are much more likely to hover over the image. 

How about this way and then the title is on the image area

![image](https://user-images.githubusercontent.com/1296369/149513381-9c38571c-bf23-4be8-9c9f-1165befa5935.png)

![image](https://user-images.githubusercontent.com/1296369/149513764-4d08ab68-9361-486d-8bc6-d1847fe32e3d.gif)

**Comment by PhocaCz** [comment]
It is important to be able to see the full file name. Is it on the image, or the name, or both? Personally, I'd put it above both the image and the name.

Now it's more a question for the developers of the hover effect over the image. If it doesn't have any negative effect on this effect. If not, then the full name is fine with the hover effect over the image.

**Comment by Shubhamverma2796** [comment]
please test #36754.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36754 . Thanks in advance.
