### ISSUE TITLE
3.10.4 breaks menu when progressive caching is selected

### ISSUE THREAD

**Issue by efrancis** [joomla/joomla-cms#36317]
### Steps to reproduce the issue
Upgrade to 3.10.4
Go to System → Global Configuration → System
Set System Cache to "ON - Progressive caching"
In the front end click on a menu item other than the one currently active

### Expected result
The menu item that was clicked on should now get the "active" class and as such allow CSS to highlight it

### Actual result
The previously selected menu item will remain active, even though the content of the newly selected item is displayed

### System information (as much as possible)
Tested and confirmed on 4 different sites as soon as 3.10.3 was upgraded to 3.10.4. My server uses PHP 7.4.

### Additional comments
Clearing cache and making the directory cache/com_modules unwritable solves the problem.
Setting cache to "conservative caching" also solves the problem
Disabling the cache in the menu module DOES NOT solve th problem strangely (but that might be a different bug)

**Comment by sozzled** [comment]
Confirmed by my own testing.  Enabling progressive caching messes with the CSS for the active menu item.

**Comment by HLeithner** [comment]
possible reason is this commit https://github.com/joomla/joomla-cms/commit/7b777766af809906fa33b7ff4b57d5ae13bc047a with the nice name "fix" which leads to https://github.com/joomla/joomla-cms/pull/35528 

it changes the caching from the complete object to the object class only at 
https://github.com/joomla/joomla-cms/commit/7b777766af809906fa33b7ff4b57d5ae13bc047a#diff-1f3d4b0ff411d275d94c1538ef487ef75d4450d772ad2cf712b5796467917f6dR475

which would mean no module variables are honored any more, at least that could be the reason for this.

can you please change the line back to the original code 
`$hash = md5(serialize(array($name, $attribs, null, $renderer)));`
file: libraries/src/Document/HtmlDocument.php in line 475

**Comment by micker** [comment]
i confirm bug on 4.0.3

**Comment by HLeithner** [comment]
@micker can you test what I wrote?, it's the same in 4.0.3 maybe different line

**Comment by efrancis** [comment]
@HLeithner I just tried replacing line 475 in libraries/src/Document/HtmlDocument.php to what you suggested and I confirm that fixes the problem.

**Comment by Fedik** [comment]
Joomla 4.0 issue was already reported  #36102 and fix is there #36193, please test.
It can be back-ported to 3.10

> Disabling the cache in the menu module DOES NOT solve th problem strangely (but that might be a different bug)

It not a bug, this option works only for "conservative caching".
"Progressive caching" caches a whole position (with all modules in it) instead of each module (as it done with "conservative caching").

**Comment by Fedik** [comment]
Please test #36324

**Comment by efrancis** [comment]
@Fedik I tested the fix #36324 and confirm that it works as expected

**Comment by Fedik** [comment]
Please set your test result here https://issues.joomla.org/tracker/joomla-cms/36324
With this button ;) 
![image](https://user-images.githubusercontent.com/1568198/146240963-57ded06d-afc7-4345-bc6e-e322081b9150.png)
