### ISSUE TITLE
[4.0] Users: Field Groups cannot assign group to Users: Field - Access level issue

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#36314]
### Steps to reproduce the issue

Create a User Access level **Test**.

Assign it to user group **Registered**.

Create a User Field Group **My Field Group** and assign it **Test** access.

Create a User Field **My Field** and try to put it into **My Field Group**

### Expected result

Able to assign the new field to **My Field Group**.

### Actual result

**My Field Group** is not available in the list.

### System information (as much as possible)

PHP 7.4

### Additional comments

If I change **My Field Group** and assign it **Registered** access then I can assign the group to the new field. But I then lose the assignment when I move it back to **Test**. Changing the field access level does not affect this behaviour.

**Comment by drmenzelit** [comment]
I'm not sure if I really understand the problem, but if you are logged in as Super User and you try to create a field in a group that is only available for Registered users, you will not succeed.. You need to add Super Users to the access level Test too, I think

**Comment by fancyFranci** [comment]
@BrainforgeUK were your able to solve your issue with drmenzels answer?

**Comment by BrainforgeUK** [comment]
Long ago. We got round issue somehow. Will close this.
