### ISSUE TITLE
Joomla 4.04 - Extension Updater - get Error "Call to undefined method InstallerHelper::getExtensionGroupes()""

### ISSUE THREAD

**Issue by rflieb13** [joomla/joomla-cms#36310]
### Steps to reproduce the issue
On J4 4.04 I got announced to update 3 extensions.
On visiting the page I get an error "Call to undefined method InstallerHelper::getExtensionGroupes()"

### Expected result
No Error to show

### Actual result
Error gets shown "Call to undefined method InstallerHelper::getExtensionGroupes()"
CSS at the top menu is a bit broken

### System information (as much as possible)
PHP 7.4
J4.04

![screen shot 2021-12-14 at 15 41 58](https://issues.joomla.org/uploads/1/601aa38edf788873405d75e508164d97.png)

**Comment by brianteeman** [comment]
So one of those extensions looks like it must have a typo in its code because it should be "groups" not "group**e**s"

**Comment by rflieb13** [comment]
Hey brianteeman,
I just solved this on my own - there was a discrepancy in the db schema of Joomla.
Did the "repair" function in the BE and everything worked now fine...
Best
Ralf
