### ISSUE TITLE
Unable to rename 'Public' usergroup

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#36322]
### Steps to reproduce the issue
- Edit the public usergroep
- Change the name
- Save

### Expected result
- New name is saved

### Actual result
- Error: "Invalid field: Group Parent"

### System information (as much as possible)
Joomla 4.0.5
PHP 8.0.13
10.2.41-MariaDB

**Comment by toivo** [comment]
The Joomla! Help page [Users: New or Edit Group](https://help.joomla.org/proxy?keyref=Help40:Users:_New_or_Edit_Group&lang=en "Users: New or Edit Group") advises against editing User Groups:

"Joomla! is installed with set of User Groups suitable for management of standard sites. **The default groups should not be edited!** New groups can be created for special purposes."<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36322">issues.joomla.org/tracker/joomla-cms/36322</a>.</sub>

**Comment by alikon** [comment]
expected behaviour

**Comment by brianteeman** [comment]
Please re-open. The help might say that but the documentation and the code doesnt. There is no mention of this restriction in Joomla 3 help pages.

If you cannot rename these groups "for some unknown reason" then they should not be editable and they should have a correct and meaningful error message. Not the current error message which is not helpful

**Comment by brianteeman** [comment]
In addition the information that "The default  groups should not be edited" is totally wrong. There is no reason that any of them can not be edited. The only one with a problem is the root (public)

**Comment by jjnxpct** [comment]
I just want to translate the group names to the language that is used in the backend, for our clients this is mostly dutch. So we want then to see dutch usergroup names. I see no reason why this should not be done? Maybe adding translation string to the usergroup could also help with this.  But I am not sure that is technically possible.

We already changed the group names below the root public item. The root is the only one we could not change because of the error.

**Comment by deltapapa01** [comment]
Hi,
I have exactly the same problem: After migrating a J3 site to J4, I noticed that the root group is named "Öffentlich". I now wanted to rename this to Public, simply to name the groups of clarity in all my Joomlas in the same way. That works good, except for the lowest level. Renaming from "Öffentlich" to "Public" is not possible. Presumably the parent level field is there and empty but hidden, hence the error message. The only way was to change the entry directly in the table via PhpMyAdmin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36322">issues.joomla.org/tracker/joomla-cms/36322</a>.</sub>

**Comment by chmst** [comment]
If the name  may not be change, the message is wrong. If the name can be changed then the parent name of "public" cannot be requested.

**Comment by brianteeman** [comment]
Technically the message is correct as it explains the technical reason why. However I would much prefer it if we could work out how to allow the group to be renamed instead of adjusting the message

**Comment by brianteeman** [comment]
Please update the label to j4 issue - 

a valid reason for renaming all the groups is so that they can be presented in the users language and not in english.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38592 . Thanks in advance.
