### ISSUE TITLE
Update 4.0.4 to 4.05

### ISSUE THREAD

**Issue by seniooriz** [joomla/joomla-cms#36326]
### Steps to reproduce the issue
Update from J4.0.4 to J4.0.5

### Actual result
Update not working : error message in console
Uncaught TypeError: window.pingExtract is not a function
at HTMLDocument. (admin-update-default.min.js?3d6c129acbaece9e88379bfb3adbb7c7e0c160c3:1)

### System information (as much as possible)
J4.0.4
PHP 8.0.11

### Additional comments

i did add this in .httaccess

`RewriteRule ^administrator/components/com_joomlaupdate/restore\.php$ - [L]`
`RewriteRule ^administrator\/components\/com_joomlaupdate\/restore\.php$ - [L]`
`RewriteRule ^administrator\/components\/com_joomlaupdate\/extract\.php$ - [L]`

also reupload `/media` folder from J4.0.4 stable package to server.

**Comment by conseilgouz** [comment]
Please check https://github.com/joomla/joomla-cms/issues/36305
and https://github.com/joomla/joomla-cms/issues/35920

**Comment by Fedik** [comment]
> also reupload /media folder from J4.0.4 stable package to server.

Do not forget to clear the Browser cache.
The issue the same as @pmleconte already commented.

**Comment by seniooriz** [comment]
> Please check #36305 and #35920

i did. not working

**Comment by Fedik** [comment]
@seniooriz you have a cache somewhere
