### ISSUE TITLE
[4] strange radio layout switcher problem in suborm

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#36321]
### Steps to reproduce the issue
create a subform in xml
adding yes no field with switcher layout
set switcher on yes => that display no

### Expected result
![image](https://user-images.githubusercontent.com/2539440/146191753-3de2a82c-1938-4eb7-9ce8-bae3fb60f6ae.png)

### Actual result
![image](https://user-images.githubusercontent.com/2539440/146191709-885afd7e-b4a2-4613-90d3-d1127a16f46f.png)

that me or you can reproduce it ?

**Comment by brianteeman** [comment]
Shouldnt the xml be
option value=0
option value=1

**Comment by richard67** [comment]
> Shouldnt the xml be
> option value=0
> option value=1

I think so, too.

**Comment by micker** [comment]
hi, if i remove "" arrounf number => 
![image](https://user-images.githubusercontent.com/2539440/146201850-1c5047b2-dce5-4db9-bdee-f33128e224a5.png)
outside subform switcher is display correct with the code

**Comment by Fedik** [comment]
@micker  options order, not `"`
you have `Yes` first because value=1 is first

**Comment by Fedik** [comment]
ah well, no, there is also `default="1"` 
something strange

**Comment by micker** [comment]
ahhh soo simple if i change order its works but not very local not ?

**Comment by Fedik** [comment]
you have to test, I cannot say ;)

**Comment by micker** [comment]
<option value="0">JNO</option>
    <option value="1">JYES</option>
working in suborm, outside order havn't any effect its always good, in subform need to be carefull

**Comment by Quy** [comment]
> working in suborm, outside order havn't any effect its always good, in subform need to be carefull

The behavior/order is the same in subform as outside of subform. Please close as this is not an issue.

https://github.com/joomla/joomla-cms/blob/b5a0d5858d953f11cae58e3020f92de8d3e705b5/administrator/components/com_actionlogs/config.xml#L5-L15
