### ISSUE TITLE
Joomla 3.10.4 Issues

### ISSUE THREAD

**Issue by in805** [joomla/joomla-cms#36323]
### Steps to reproduce the issue

Hello,

I recently upgraded my sites from Joomla 3.10.3 (which is working perfect) to 3.10.4.  After installing 3.10.4, immediately noticed several issues with site navigation not working, not linking to the correct pages or redirecting to the homepage, content modules randomly appearing on pages that the content is not targeted to, broken links, etc.  A mess...

I then had to restore all my sites back to 3.10.3. They again work fine.

I do have 3.10.4 on a dev instance if you want to review.

The instance has the following specs:

Joomla 3.10.4
PHP 7.4.26
Gantry 4
Updated and current Gantry and templates
MySQL

Appreciate any help you can provide?

Have there been other reported issues with Joomla 3.10.4?

Thanks,

John

**Comment by Fedik** [comment]
Do you use progressive cashing on your site?

**Comment by in805** [comment]
Joomla system cache progressive = on, so yes.

**Comment by Fedik** [comment]
Okay, thanks for comment.
It already known issue, please follow #36317
And please test the fix #36324

**Comment by in805** [comment]
Thanks.  I'll review.  Much appreciated.

**Comment by in805** [comment]
Hello,

I am following up on the issue I posted last week (listed below).

Is the issue resolved for Joomla 3.10.4 or is it something that will be fixed soon?  I have been holding off on updating my website until the issue's resolved.

Thanks,

John


********

Hello,

I recently upgraded my sites from Joomla 3.10.3 (which is working perfect) to 3.10.4. After installing 3.10.4, immediately noticed several issues with site navigation not working, not linking to the correct pages or redirecting to the homepage, content modules randomly appearing on pages that the content is not targeted to, broken links, etc. A mess...

I then had to restore all my sites back to 3.10.3. They again work fine.

I do have 3.10.4 on a dev instance if you want to review.

The instance has the following specs:

Joomla 3.10.4
PHP 7.4.26
Gantry 4
Updated and current Gantry and templates
MySQL

Appreciate any help you can provide?

Have there been other reported issues with Joomla 3.10.4?

Thanks,

John<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36323">issues.joomla.org/tracker/joomla-cms/36323</a>.</sub>
