### ISSUE TITLE
[4.0] query re colours used for highlighting differences in original and overridden files

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#36330]
### Problem identified
I have just updated a J4 site from 4.0.4 to 4.0.5 and have been notified of four overridden files.
One of these is a category blog override and I'm currently looking at blog_children.php.

Having double-checked with the source code here on Github, I can see that:

The copyright appears to have changed from
"* @copyright   Copyright (C) 2005 - 2020 Open Source Matters, Inc. All rights reserved."
to
" * @copyright   (C) 2010 Open Source Matters, Inc. <https://www.joomla.org>"

![file-override-differences](https://user-images.githubusercontent.com/36987494/146415321-38af155e-8efd-4ca1-ba2d-f7d59160b2a9.jpg)

and line 32 from
```<span class="badge badge-info tip">```
to
```<span class="badge bg-info tip">```

(Plus a few other changes).

I would have expected the new, 'correct' text or code to be highlighted green and the old, or 'wrong' text or code that needs changing, to be highlighted in pink.

Similarly, above the editor, in order to see the original file file, you have to click the grey button that says "Hide Original" and to see the differences, click the grey button "Hide Differences"

### Proposed solution
1. Swap the highlighting colours
2. Switch the text so that it initially displays "Show Original" and "Show Differences"

**Comment by brianteeman** [comment]
1. Traditionaly in a diff red is the original and green is the changed version. Hopefully if #38401 is merged it will remove any _confusion_
2.  As with all uses of a toggle button throughout joomla the text is showing the current state so your suggestion would be incorrect. However it would probably be better to change the label to "Show Differences" and the state to yes/no

**Comment by joomdonation** [comment]
@brianteeman @Scrabble96  As I understand, after two PRs https://github.com/joomla/joomla-cms/pull/38823 and https://github.com/joomla/joomla-cms/pull/38463 merged, this issue is now solved. Could you please confirm so that we can close this issue?

**Comment by joomdonation** [comment]
Brian confirmed that the two PRs solved the issue, therefore, I'm closing this issue.
