### ISSUE TITLE
php 8.x incompatibility

### ISSUE THREAD

**Issue by raidnet-ms** [joomla/joomla-cms#36334]
### Steps to reproduce the issue

While in the backend, go to joomla update or to sysinfo.

### Expected result

showing the content without errors

### Actual result

error.
0 Unknown format specifier "S"

### System information (as much as possible)

php 8.0 and php 8.1, while with 7.4 (64bit) I get no errors

Installation comes from a 3.10 update

**Comment by brianteeman** [comment]
What language are you using

**Comment by raidnet-ms** [comment]
Hi, Italian language

**Comment by brianteeman** [comment]
I thought so - there was a faulty version of the italian language pack which I believe has now been resolved. Please update the language pack and let us know

**Comment by alikon** [comment]
i think should have been fixed already in crowdin 

anyway as a quick fix #36227

**Comment by raidnet-ms** [comment]
Here's the system info page with error:

https://ibb.co/vYhpNr4

while joomla update page states this:
https://ibb.co/r348NWN

**Comment by raidnet-ms** [comment]
> I thought so - there was a faulty version of the italian language pack which I believe has now been resolved. Please update the language pack and let us know

I already have the latest version: https://downloads.joomla.org/it/language-packs/translations-joomla4/downloads/joomla4-italian
Version installed: 4.0.4.1

**Comment by raidnet-ms** [comment]
> i think should have been fixed already in crowdin
> 
> anyway as a quick fix #36227

Hi alikon, is this bugfix still in dev version?

**Comment by alikon** [comment]
i think it should be in 4.0.5  as per #36226

**Comment by raidnet-ms** [comment]
I updated to j4.05 before moving to php 8.1 because I already noticed this problem with php 8.0 and j4.x

If I get back to php 7.4 I get no errors.

**Comment by alikon** [comment]
please check installation/language/it-IT/joomla.ini  line 180
should be  like this 
`INSTL_EXTENSION_AVAILABLE="Disponibile %s"`

**Comment by raidnet-ms** [comment]
> please check installation/language/it-IT/joomla.ini line 180 should be like this `INSTL_EXTENSION_AVAILABLE="Disponibile %s"`

I got JFIELD_COLOR_SELECT="Seleziona un colore" on line 180 and INSTL_EXTENSION_AVAILABLE="Disponibile %s" does not list into this joomla.ini file :-(

**Comment by alikon** [comment]
you must look at installation folder

**Comment by raidnet-ms** [comment]
> you must look at installation folder

isn't installation folder deleted after installation?

I have a joomla.ini in administration/language/it-IT
with  this on line 180 `JERROR_ALERTNOTEMPLATE="Il template per questa schermata non Ã¨ disponibile."`

and a joomla.ini in language/it-IT
with this `JFIELD_COLOR_SELECT="Seleziona un colore" on line 180.`

but no installation folder in joomla. 

I searched for that line `INSTL_EXTENSION_AVAILABLE="Disponibile %s"` in both files without success.

**Comment by Quy** [comment]
Fixed in #36226
