### ISSUE TITLE
[4.0] `$filetype` is undefined in checkFileExtension

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#36347]
### Steps to reproduce the issue

 -  #34999

By @SniperSister introduced code in libraries/src/Helper/MediaHelper.php:191:106 which resulted in committing `$filetype` variable which is undefined. 

### Expected result

All PHP vars are defined

### Actual result

libraries/src/Helper/MediaHelper.php:191:106  `$filetype` variable is undefined.

**Comment by Quy** [comment]
Please test PR #36705. Thanks.
