### ISSUE TITLE
Joomla 4.04: upgrade to 4.05 fails, upgrade process freezes with now messages

### ISSUE THREAD

**Issue by boris-grinac** [joomla/joomla-cms#36349]
### Steps to reproduce the issue
Upgrade from 4.04 to 4.05 will not complete.
Trying on-line upgrade, the default: message on screen "" Not a a valid header
Trying manual upload: no messages on screen, no response, but after new login administrator environment works, still showing version 4.04, so no upgrade done.

### Expected result
Version should be reported as 4.05

### Actual result
Version is reported as 4.04

### System information (as much as possible)
After I have activated "log almost everything", there is uncaught exception in log:
2021-12-18T18:17:39+00:00       CRITICAL 192.168.0.10   error   Uncaught Throwable of type Laminas\Diactoros\Exception\InvalidArgumentException thrown with message """ is not valid header name". Stack trace: #0 /srv/www/htdocs/libraries/vendor/laminas/laminas-diactoros/src/MessageTrait.php(414): Laminas\Diactoros\HeaderSecurity::assertValidName('')
#1 /srv/www/htdocs/libraries/vendor/laminas/laminas-diactoros/src/MessageTrait.php(341): Laminas\Diactoros\Response->assertHeader('')
#2 /srv/www/htdocs/libraries/vendor/laminas/laminas-diactoros/src/Response.php(135): Laminas\Diactoros\Response->setHeaders(Array)
#3 /srv/www/htdocs/libraries/src/Http/Transport/StreamTransport.php(234): Laminas\Diactoros\Response->__construct(Object(Laminas\Diactoros\Stream), 303, Array)
#4 /srv/www/htdocs/libraries/src/Http/Transport/StreamTransport.php(202): Joomla\CMS\Http\Transport\StreamTransport->getResponse(Array, 'PK\x03\x04\x14\x00\x00\x00\x08\x00\xF0\xA6\x8BS\xA1...')
#5 /srv/www/htdocs/libraries/vendor/joomla/http/src/Http.php(314): Joomla\CMS\Http\Transport\StreamTransport->request('GET', Object(Joomla\Uri\Uri), NULL, Array, NULL, 'Mozilla/5.0 Joo...')
#6 /srv/www/htdocs/libraries/vendor/joomla/http/src/Http.php(152): Joomla\Http\Http->makeTransportRequest('GET', Object(Joomla\Uri\Uri), NULL, Array, NULL)
#7 /srv/www/htdocs/administrator/components/com_joomlaupdate/src/Model/UpdateModel.php(500): Joomla\Http\Http->get('https://downloa...')
#8 /srv/www/htdocs/administrator/components/com_joomlaupdate/src/Model/UpdateModel.php(400): Joomla\Component\Joomlaupdate\Administrator\Model\UpdateModel->downloadPackage('https://downloa...', '/srv/www/htdocs...')
#9 /srv/www/htdocs/administrator/components/com_joomlaupdate/src/Controller/UpdateController.php(56): Joomla\Component\Joomlaupdate\Administrator\Model\UpdateModel->download()
#10 /srv/www/htdocs/libraries/src/MVC/Controller/BaseController.php(730): Joomla\Component\Joomlaupdate\Administrator\Controller\UpdateController->download()
#11 /srv/www/htdocs/libraries/src/Dispatcher/ComponentDispatcher.php(146): Joomla\CMS\MVC\Controller\BaseController->execute('download')
#12 /srv/www/htdocs/libraries/src/Component/ComponentHelper.php(389): Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()
#13 /srv/www/htdocs/libraries/src/Application/AdministratorApplication.php(143): Joomla\CMS\Component\ComponentHelper::renderComponent('com_joomlaupdat...')
#14 /srv/www/htdocs/libraries/src/Application/AdministratorApplication.php(186): Joomla\CMS\Application\AdministratorApplication->dispatch()
#15 /srv/www/htdocs/libraries/src/Application/CMSApplication.php(278): Joomla\CMS\Application\AdministratorApplication->doExecute()
#16 /srv/www/htdocs/administrator/includes/app.php(63): Joomla\CMS\Application\CMSApplication->execute()
#17 /srv/www/htdocs/administrator/index.php(32): require_once('/srv/www/htdocs...')
#18 {main}

**Comment by brianteeman** [comment]
To avoid confusion please explain in detail what you mean about the three different upgrade methods.
Also were they one after the other or did you restore from a backup between the attempts

**Comment by richard67** [comment]
And which PHP version?

**Comment by Fedik** [comment]
Did you made patch update before? example 4.0.3_to_4.0.4_patch

**Comment by beatty12** [comment]
I'm having same issue.
I setup a new LAMP env. on Azure (VM) with Debian 11. Apache 2.4, 10.5.12-MariaDB-0+deb11u1, php8 on Dec 18th. Installed Joomla 4.0.4 this morning (Dec 20th) and was prompted to update to V 4.0.5 upon my first login into the administrator env. When I tried to run the update, I got the same ("" Not a a valid header) error message. 
There was a post somewhere about cURL being an issue and another post a while back that suggested running a database fix would resolve the issue, but it was regarding a J3 issue and I can't find the same "fix" button anywhere in Joomla 4 (under manage extensions) like there was in J3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36349">issues.joomla.org/tracker/joomla-cms/36349</a>.</sub>

**Comment by Fedik** [comment]
You can find "fix" button there `/administrator/index.php?option=com_installer&view=database`,
but it called `Update Structure` in Joomla 4

**Comment by beatty12** [comment]
Thanks!
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36349">issues.joomla.org/tracker/joomla-cms/36349</a>.</sub>

**Comment by boris-grinac** [comment]
More details:
Three upgrade methods:
1. Standard online upgrade
2. Manual upload of update package (.zip)
3. Manual upload of full installation package (.zip)
Each time I have restored the server from backup.
I have applied updates to this server each time there was an update. So this server is now version 4.04
System info: OpenSuse Leap 15.3, PHP Version 7.4.6
Now I have reverted this server back to backup. My backup is full images backup. This server is a virtual machine and I restored whole system.
The server looks good, but update to 4.05 does not work.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36349">issues.joomla.org/tracker/joomla-cms/36349</a>.</sub>

**Comment by boris-grinac** [comment]
I have tried to update database structure. The database version is 4.03, but manifest version is 4.04 
I am not sure it this is correct, but this "update database" trick does not fix the update problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36349">issues.joomla.org/tracker/joomla-cms/36349</a>.</sub>

**Comment by chmst** [comment]
@boris-grinac could you update to 4.1? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36349">issues.joomla.org/tracker/joomla-cms/36349</a>.</sub>

**Comment by brianteeman** [comment]
This should probably bee closed now

**Comment by boris-grinac** [comment]
Dear Christiane,
I have tried to update to 4.1, but still no success. When updating via
normal update, I have a freeze, no messages even no errors in debug window.
When installing the update package in zip format, it looks better and I
have error messages, basically the same as before when updating to 4.0. The
difference is that now, with 4.1, the whole Joomla installation is not
trashed, after failed update I still can open new admin session and it
looks like Joomla is still alive - only not updated. So I do not have to
revert the whole server back from snapshot. I have full control over the
server, it is hosted on xen and the operating system is OpenSuse Leap 15.3

Boris

**Comment by drmenzelit** [comment]
Maybe this one helps: https://docs.joomla.org/J4.x:Fix_%22Database_Table_Structure_NOT_Up_to_Date%22_before_Update
