### ISSUE TITLE
Module menu assignment broken in upgrade from 3.10.3 to 3.10.4

### ISSUE THREAD

**Issue by 54csar** [joomla/joomla-cms#36352]
### Steps to reproduce the issue
Module menu assignment does not recognize "Only on pages selected" option.  Custom modules assigned to same position on different pages conflict, with the last created module taking precedence.  

### Expected result
Custom modules should appear only on selected pages per menu assignment.

**Comment by richard67** [comment]
System Information (as much as possible): Nothing given. Very helpful.

Questions: Which PHP version? And do you have progressive caching on in global configuration? If yes: does it help to change to conservative caching?

**Comment by Fedik** [comment]
Do you use "Progressive caching"? If so, then it the same as #36102,
The fix is there #36324 please test

**Comment by richard67** [comment]
Setting to "Information Required" in the issue tracker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36352">issues.joomla.org/tracker/joomla-cms/36352</a>.</sub>

**Comment by sho81** [comment]
I'm suffering from this bug, too. After reading through the issues I've changed the setting under "Global Configuration, System tab, Cache Setting" and this seems to fix the problem by switching from "Progressive caching" to "Conservative caching". It's a Germn UI so it's displayed to me as from "AN - Erweitertes Caching" to "AN - Normales Caching". It also broke the second level stage of my menu: mostly only first level menu items were visible.
It's really hard impact / problem to my page (depending of how excessive modules assignment to single page(s) is used).
Keeping fingers crossed you find/fix/release it for 3.10.5. Thanks for your work.
My current version: Joomla! 3.10.4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36352">issues.joomla.org/tracker/joomla-cms/36352</a>.</sub>

**Comment by sho81** [comment]
Systeminformationen
Einstellung 	Wert
 
PHP erstellt für 	Linux localhost 3.10.0-1160.36.2.el7.x86_64 #1 SMP
Database Type 	mysql
Datenbankversion 	5.7.36-log
Datenbankzeichensatz 	utf8_general_ci
Datenbankverbindungszeichensatz 	utf8mb4_general_ci
PHP-Version 	8.0.13
Webserver 	Apache/2.4.51 (Unix)
PHP-Interface für den Webserver 	cgi-fcgi
Joomla!-Version 	Joomla! 3.10.4 Stable [ Daraja ] 11-December-2021 15:02 GMT
Joomla!-Plattform-Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:95.0) Gecko/20100101 Firefox/95.0 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36352">issues.joomla.org/tracker/joomla-cms/36352</a>.</sub>

**Comment by richard67** [comment]
@54csar As you did not report back after my question if you have used progressive cache but gave a thumb up to @Fedik 's comment about it, I assume it was the case, so it is solved with PR #36324 and will be available with the upcoming 3.10.5 release.

@sho81 In your case it's the same.

Closing as solved with PR #36324 .
