### ISSUE TITLE
J4 doesnt clear update cache on upgrade

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36357]
### Steps to reproduce the issue
Install joomla 3.10.1 (any 3.10 version that is not the current)
Make sure that it is displaying the update available information
Switch the update channel to Next and upgrade to j4

### Expected result
Dashboard icon shows no updates available

### Actual result
Dashboard icon shows update to joomla 3.10.4 available

**Comment by zero-24** [comment]
It is the intended behavior to always go via the latest 3.10 release to 4.x so any additional checks we might want to implement into the pre upgrade checker will be exectued and this way we can also mitigate issues like that "lts/sts" setting.

**Comment by brianteeman** [comment]
Then it should not be possible to upgrade from 3.10.3 etc

**Comment by zero-24** [comment]
We have defined it here: https://github.com/joomla/update.joomla.org/blob/master/www/core/sts/list_sts.xml#L16-L18
Based on this 3.10.3 also would have to go via 3.10.4 to get 4.0.5.

Or what do you mean here? Maybe we missed something when we build it?

**Comment by richard67** [comment]
So or so I would not expect an update to 3.10.x to be available AFTER having upgraded to 4, as far as I understand the issue.

**Comment by zero-24** [comment]
Ah ok sorry got it wrong. Yes you are right the update cache should be cleared after the update.

**Comment by brianteeman** [comment]
Quite a few people on facebook have reported this today. 

It is easy to replicate by doing an update to the latest j3 and then immediately updating to j4

**Comment by brianteeman** [comment]
Closing due to lack of interest
