### ISSUE TITLE
Alert messages cannot be deleted

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#36351]
### Steps to reproduce the issue
Go to Multimedia and create 3 or 4 folders, letting the alert messages be displayed.

### Expected result
Click on X and delete the alert messages

### Actual result
Clicking on X but DOES NOT delete the alert messages

### System information (as much as possible)
Joomla 4.0.5

**Comment by akshitrattan** [comment]
I checked the issue on my local system, but I didn't face this problem.

**Comment by Quy** [comment]
@Open2logic Unable to reproduce. Does the alert auto dismiss? Is there an error in the browser's console?

**Comment by Quy** [comment]
Closing due to no response.
