### ISSUE TITLE
No configuration screen for packages

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#36359]
### Steps to reproduce the issue
It is not possible for an extension developer to define configuration options for packages. A simple use case would be to have a package with plugins and modules and want to offer the user a way to set a download id for the package. There is no way to do it.

**Comment by Fedik** [comment]
That a "feature request".
Not sure how it should be implemented. And which exactly requirement for it.

**Comment by roland-d** [comment]
@laoneo We can enter the download ID now in the update sites section of Joomla 4. The download sites show the package if you installed a package. Not sure about what other options a package could/should have that an end-user should configure.

**Comment by laoneo** [comment]
How can you enter it in the update site, I don't see such a field?

**Comment by roland-d** [comment]
@laoneo Please see the documentation at https://docs.joomla.org/Manifest_files#Supporting_Download_Keys You need to have a `dlid` tag in your manifest file.

**Comment by laoneo** [comment]
Nice, this actually works.
