### ISSUE TITLE
[4.0] Could the "Diff between original and overridden file" have line numbers?

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#36365]
### Is your feature request related to a problem? Please describe.
Checking changes to original files to be compared with overrides, the windows showing the overridden and original files have line numbers, the differences do not.

### Describe the solution you'd like
Show line numbers on 'differences' view

### Additional context
Here, on GitHub, the line numbers are shown, for example in a PR request showing changes in files.

**Comment by brianteeman** [comment]
The library used to create the diff does not offer this

**Comment by brianteeman** [comment]
Changed the library - please test #58129

**Comment by Fedik** [comment]
@brianteeman you probably meant #38823 or?

**Comment by brianteeman** [comment]
oops yes - I posted the drone reference

**Comment by Fedik** [comment]
Okay, then I close it, because we have a PR #38823, please test
