### ISSUE TITLE
[4.0] Layout Chromes appear to be missing from module advanced tab

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#36361]
### Steps to reproduce the issue
Start a new module
Go to the Advanced tab
Click/tap the down arrow for 'Layout'

### Expected result
To see 'Card' and 'noCard'

### Actual result
Only: 
'From Module' > 'Default'

### System information (as much as possible)
Joomla 4.0.5

### Additional comments
What is the 'Default' layout?
Should there not be a choice of 'Card' and 'noCard'?
Custom layouts only work if they are in the new 'mod_custom' folder. They used to work if located in the layouts > chromes folder.

**Comment by brianteeman** [comment]
You are confusing module layout and module style. Still works the same as J3

![image](https://user-images.githubusercontent.com/1296369/146811724-9fb9021e-196b-4fd8-a662-60b4524f936b.png)

**Comment by Scrabble96** [comment]
Oh dear. Thanks, @brianteeman.
