### ISSUE TITLE
Banner component started logging tracking impressions almost every minute

### ISSUE THREAD

**Issue by isidrobaq** [joomla/joomla-cms#36375]
After upgrading to Joomla! 3.10.3, banner component started logging every individual impression and click, instead of logging hourly impressions/clicks.

### Steps to reproduce the issue

Publish a banner on the frontend
Enable "Track impressions" in Banner component settings
Navigate through the frontend for a while, so the banner is loaded a few times
Check Banner Tracks in Banner Component

### Expected result

A single log per hour for each banner should be displayed in Banner tracks view.

### Actual result

Several logs per hour are shown for each banner (check attached image). This causes _banner_tracks table to grow insanely fast (nearly 3 million records in barely 3 weeks), and make banner component hard to manage.

### System information (as much as possible)

mysql - 5.6.40 - utf8_general_ci - utf8mb4_general_ci 
PHP 7.4.27 
Apache 
fpm-fcgi 
Joomla! 3.10.4 Stable [ Daraja ] 11-December-2021 15:02 GMT 
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 

The site was upgraded from an old 3.9.18 version to 3.10.3

### Additional comments

Searching for any possible solution this PR came along

https://github.com/joomla/joomla-cms/pull/24651

Apparently this was included again in 3.10, and this comment is related to my specific issue

https://github.com/joomla/joomla-cms/pull/24651#issuecomment-485439618

Actually, this comment is what made this PR appear in my search.

**Comment by isidrobaq** [comment]
Added screenshot.

![screen shot 2021-12-27 at 09 07 09](https://issues.joomla.org/uploads/1/93bbf987afaed36b4b9de8aac910ba20.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36375">issues.joomla.org/tracker/joomla-cms/36375</a>.</sub>

**Comment by Quy** [comment]
Can you please test PR #24651 to confirm the fix? Thanks.

**Comment by isidrobaq** [comment]
@Quy Thanks for your reply. That PR indicates DB should be posgreSQL, which is not my case. I only mentioned it because it was related, but apparently not the same issue. Am I missing anything?

**Comment by Quy** [comment]
It might fix your issue so please give it a test to confirm or rule it out.

**Comment by Quy** [comment]
Fixed in #24651. Tested with MySQL.
