### ISSUE TITLE
[4.x] extend email template to other component

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#36389]
Hello
We have workflow manager
We have template email
That realy greeeat
But its a little incomplet feature
Why we can't use it together ?
And for now if i understand we can't use email template in 3dth extension
Imagine
Customise all email sended for each steep of workflow
If component use workflow integrator Can manage all emails ...
Cool feature not ?

**Comment by alexandreelise** [comment]
@micker Yup would be pretty cool
