### ISSUE TITLE
Web Assets and language strings

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36387]
Finally getting my head around the web asset stuff.

Love that I can add one line to a component to add multiple scripts using the presets.

What I am missing _(maybe it exists and I'm not skilled enough to see it)_ is the ability to use joomla language strings in the same way.

For example I have a preset that contains multiple scripts and stylesheets and it needs to use **one** language string. This currently means that I have to add that string to the component php as well ;(

### Example
```
// Attach all items from foobar preset to the document
$wa->usePreset('foobar');
// Grab any language strings that are needed in the preset
Text::script('JGLOBAL_COLUMNS');
```
Not too bad with one string but a real pia with multiple. It would be great to list them in the preset _or similar_

**Comment by Fedik** [comment]
That would be a good feature, especially for complex clientside apps (like media manager).
Not sure how it should be implemented, maybe something like: `Text::scriptLanguageFile('blabla.script.ini')` which load whole file to `Text::script()`.

At current state Developer can implement own `WebAsset` item class for the script, and load constants from there.
The class should implement `WebAssetAttachBehaviorInterface` https://docs.joomla.org/J4.x:Web_Assets#Advanced:_Custom_WebAssetItem_class
With `onAttachCallback` method, that will call `Text::script` for all constants, not much nice but should work.
 
Something like this:

```php
class MyFancyFoobarAssetItem extends WebAssetItem implements WebAssetAttachBehaviorInterface
{
  public function onAttachCallback(Document $doc): void
  {
    Text::script('BLABLA_CONSTANT');
    Text::script('BLABLA_CONSTANT2');
    Text::script('BLABLA_CONSTANT3');
    ...
  }
}
```

**Comment by wilsonge** [comment]
Actual example here for the form validation https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/WebAsset/AssetItem/FormValidateAssetItem.php with it's web asset definition https://github.com/joomla/joomla-cms/blob/92529d11bd6d9554aee58f4ee63378c01e9bbdf6/build/media_source/system/joomla.asset.json#L130-L141

But as @Fedik says this is the intended & documented solution for now. Happy if something more concrete as a proposal comes up to considering it - but closing this for now as it's definitely possible with the current code.

**Comment by brianteeman** [comment]
thanks
