### ISSUE TITLE
Search by multiple tags

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#36392]
In addition to searching by headings of articles, add the ability to select additional tags for sorting the list.

**Comment by ReLater** [comment]
Please tell us:
- Joomla 3 or 4?
- Backend (administrator) or frontend?
- Which view? List of articles or one of the two search components? Or?

**Comment by 1inkin** [comment]
- Joomla 4;
- Frontend;
- When we click on a tag in a article or popular tags module, a page opens with a list of articles related to this tag. In this list, only a text search by the title of the articles is available. It would be convenient to be able to additionally filter the list by additional tags. To show articles with a few common tags in the list.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36392">issues.joomla.org/tracker/joomla-cms/36392</a>.</sub>

**Comment by joomdonation** [comment]
I don't think we would have something like this in the core, so I'm closing this issue/feature request so that we can focus on other issues/prs. Feel free to re-open it if you don't agree and I will ask for feedback from our maintainers.
