### ISSUE TITLE
Testing 4.1 beta2

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36423]
### Steps to reproduce the issue
Set the update channel to Testing and Beta
![image](https://user-images.githubusercontent.com/1296369/147406409-1aa2b1da-5775-4271-abc0-443b4e6eab6e.png)

### Expected result
Offered the 4.1 beta 2 release

### Actual result
No updates available

### Additional comments
This means it is impossible to test the update which is kind of daft as the entire point of the beta is to be able to test updates on real sites and make sure it doesnt break anything

**Comment by joeforjoomla** [comment]
Confirmed. Update is only possible through manual package upload. I don't know who should test 4.1 planned for February 15, 2022 in this situation.

**Comment by brianteeman** [comment]
So we now have confirmation that only two people have even tried an update because of this IGNORED issue. What is the point of beta releases if no one even checks you can do an update. Does the CMS release team still exist?

**Comment by joeforjoomla** [comment]
@brianteeman i was asking the same to myself.

**Comment by brianteeman** [comment]
Wow - still no response

**Comment by zero-24** [comment]
Btw the testing Channel is expected to not provide the updates yet but the plan i have been told is to use it with the RC. But i can only ask for information what is planed and not decide stuff myself for releases where i'm not the release lead ;-)

The cms release team still exists when that is a real question.

**Comment by brianteeman** [comment]
Thank you for taking the time to respond. Still surprising that the update cant be tested yet as we've already discovered several blockers in the process

**Comment by zero-24** [comment]
When uploading the update via com_joomlaupdate only the download is different so testing the update process (execpt the download) is already possible but i understand the reason for that question and i'm sorry that I'm no longer have the capaticity to follow all issues here on GitHub but focus mostly of my limited time on issues about my release.

Btw testing the full update process is and was at every time possible using the nighly build update servers.

**Comment by brianteeman** [comment]
closing as the rc is now available on the testing channel
