### ISSUE TITLE
[4.1-dev] Scheduler attempts to run orphaned tasks

### ISSUE THREAD

**Issue by ditsuke** [joomla/joomla-cms#36435]
### Steps to reproduce the issue
- Create task with a short interval based rule
- Orphan the task by disabling the parent plugin.
- Wait for the task to be triggered

### Expected result
The task is not triggered since its orphaned.

### Actual result
The task is triggered, a "running" icon indicating a lock on the task is visible on visiting the Task Manager.

### System information (as much as possible)
N/A

### Additional comments
\-

**Comment by Quy** [comment]
Thank you for PR #36436. It is not necessary to create an issue if there is a PR for it to save time.

**Comment by ditsuke** [comment]
thanks
