### ISSUE TITLE
[4.1-dev] Task Manager pagination is broken

### ISSUE THREAD

**Issue by ditsuke** [joomla/joomla-cms#36437]
### Steps to reproduce the issue
- Create > 5 tasks.
- Orphan some of the tasks so that non-orphaned tasks = 5.
- Set Task Manager pagination size to 5.
- Exclude orphaned tasks in the task manager (the default is not really applied)

### Expected result
We see 5 tasks in the task manager.

### Actual result
We see < 5 tasks in the task manager.

### System information (as much as possible)
n/a

### Additional comments
\-

**Comment by Quy** [comment]
#36438

**Comment by brianteeman** [comment]
If you are creating a pull request at the same time there is no need to create an issue
