### ISSUE TITLE
[4.1 ScheduledTasks] - Cannot save task Image Size Check

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#36449]
### Steps to reproduce the issue

4.1-dev
Login to admin -> System -> Scheduled Tasks
click Add your first Task
select image size check
Enter a title... 
Select Directory - banners (or any of them) 
set Interval in Minutes = 1
Click save

### Expected result

Saved.

### Actual result

NOTE there is a Directory dropdown on the ADVANCED TAB as well.. this is the one that is the cause of the issue - seems the Task Parameters fields is duplicated... 

<img width="1595" alt="Screenshot 2021-12-27 at 22 35 38" src="https://user-images.githubusercontent.com/400092/147511506-5c40e87c-561d-454a-bb0c-092877859aac.png">

**Comment by PhilETaylor** [comment]
@ditsuke

**Comment by chmst** [comment]
@ditsuke the params for directory are on the first tab and on the advanced tab. This causes the error, as already mentioned above
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36449">issues.joomla.org/tracker/joomla-cms/36449</a>.</sub>

**Comment by chmst** [comment]
As improvement - it would be nice to know if the Limit is kb or mb or px or something else.

**Comment by ditsuke** [comment]
> @ditsuke the params for directory are on the first tab and on the advanced tab. This causes the error, as already mentioned above
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/36449](https://issues.joomla.org/tracker/joomla-cms/36449).



> As improvement - it would be nice to know if the Limit is kb or mb or px or something else.

@chmst 
Noted and on it!

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36515 . Thanks in advance.
