### ISSUE TITLE
Language switcher does not work properly in J4.0.5

### ISSUE THREAD

**Issue by w13ear** [joomla/joomla-cms#36446]
Language switcher: associations between articles and menu-items aren't working as expected.
Switching from default language to secondary language and back is not working properly.
Steps to reproduce the issue

Joomla 3.10.x or Joomla 4.0.x installed
Language plugins enabled
At least 2 languages installed in the front-end
Language switcher available in the front-end
Visit front-end of the website
Switch to second (not default) language
Switch back to default language
Expected result

    Article (page) shown in second language
    Articel (page) shown in default language

Actual result

    Default page shown in second language
    Error 404 showing page not found

System information (as much as possible)

Joomla 4.0.5
Website cm.gw24.nl
Additional comments

cm.gw24.nl (J4.0.5) is a akeeba backup copy from creatief.management (J3.10.4)
After deleting non-Joomla4 components and unpublishing plugins migrated to J4.
Since the associations did not work anymore.
Tried to work-around it by deleting all associations on both article and menu-item levels
Followed by adding new associations.
Same result: no returning back to original language.

**Comment by infograf768** [comment]
Can't reproduce.
Looks like your gdpr plugin interferes with normal cookie behavior.

**Comment by Quy** [comment]
Closing due to no response.

**Comment by Sandra97** [comment]
I'm having this issue too on 2 multilingual websites.
It seems it's linked to the Language filter plugin. 
If I enable 'Remove URL Language Code', then pages of the default language are 404 when using the language switcher. It keeps the language code in the URL 
If I disable this option, associations work as expected and no more 404.
(I'm sure there's another issue on GH about this, but couldn't find it)

**Comment by Sandra97** [comment]
Found how to fix it adding a condition in the htaccess like mentioned here #35541
