### ISSUE TITLE
[4.1 ScheduledTasks] Failed task doesn't release lock ever

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#36458]
### Steps to reproduce the issue

When a scheduled task fails, it retains the lock and further scheduled runs will fail because it cannot acquire a lock. 

### Expected result

When a scheduled task fails, it should be logged, it should have the Times Failed increased, and the lock should be released so that on the next scheduled run, it can run again

### Actual result

The task is permanently locked and a "running" icon is displayed in the admin console. 

```json
{
  "success": true,
  "message": null,
  "messages": null,
  "data": {
    "message": "could not acquire lock on task. retry or allow concurrency."
  }
}
```

<img width="1291" alt="Screenshot 2021-12-27 at 23 29 57" src="https://user-images.githubusercontent.com/400092/147513516-868484ee-dbd0-41cd-a87e-3df7eb838ad6.png">

**Comment by ditsuke** [comment]
Thanks for opening this issue. Originally, we were doing auto-recovery of "locked" tasks running beyond a set timeout (Scheduler config > Task Timeout). With the conversation from https://github.com/joomla-projects/soc21_website-cronjob/issues/39, it was decided it's not such a good idea.

Normally, these perma-blocking locked tasks requiring manual checks are only possible if a task crashes the parent process or similar. However, I can see we still have edge cases we are not accounting for and recovering the locks.

I'm guessing you got this lock as a result of an orphaned task (https://github.com/joomla/joomla-cms/pull/36436)? Can you share some more information?

**Comment by PhilETaylor** [comment]
If a task fails - like this

**Comment by PhilETaylor** [comment]
Like this https://github.com/joomla/joomla-cms/issues/36455

**Comment by ditsuke** [comment]
> Like this #36455

Thanks that's awesome. I'm on it.

**Comment by PhilETaylor** [comment]
the way I read that thread, Nics point is about unlocking running tasks, not failed tasks. 

If a task fails, it is no longer running, you should release the lock and report the failure, allowing the task to run again (and maybe succeed) at a later schedule. All cron job systems do this.

**Comment by ditsuke** [comment]
> the way I read that thread, Nics point is about unlocking running tasks, not failed tasks.
> 
> If a task fails, it is no longer running, you should release the lock and report the failure, allowing the task to run again (and maybe succeed) at a later schedule. All cron job systems do this.

Absolutely, and failed tasks _are_ unlocked. We just have a few scenarios not covered so we aren't catching exceptions where we should be catching them. I'll work on fixing this soon so you can test. 🙂

**Comment by PhilETaylor** [comment]
ok cool - so the failure case I provided a useful one then

**Comment by sabersaberi2** [comment]
hi
i have similar problem. i get this error:

```
{
    "success": true,
    "message": null,
    "messages": null,
    "data": {
        "message": "could not acquire lock on task. retry or allow concurrency."
    }
}
```
i change the 
Scheduler config > Task Timeout
to 10 sec, but not any effect. i use shared hosting and can not check linux cron report.

how to resolve the problem?
i use joomla version 5.0.0
