### ISSUE TITLE
[4.1 ScheduledTasks] No way to reset the statistics

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#36457]
### Steps to reproduce the issue

So lets say my task has been constantly failing and I have 3123 Times Failed. I have fixed the problem and want to reset the stats to that I can keep an eye on it, there is no way to do that without deleting the task and creating a new one. 

<img width="635" alt="Screenshot 2021-12-27 at 23 26 04" src="https://user-images.githubusercontent.com/400092/147513369-47d1d964-5acc-4727-af81-be1244dcec21.png">

@ditsuke

**Comment by pritam825** [comment]
![Screenshot (1962)](https://user-images.githubusercontent.com/54195688/151229923-d3cc8984-82ef-4fa8-8909-87c8040d644d.png)
is this the correct position for the reset button?

**Comment by ditsuke** [comment]
> ![Screenshot (1962)](https://user-images.githubusercontent.com/54195688/151229923-d3cc8984-82ef-4fa8-8909-87c8040d644d.png) is this the correct position for the reset button?

@pritam825 it should go under "Execution History". Also I think the button should be inlined into a field (for example the calendar and user buttons besides "Created" an "Created By".

**Comment by pritam825** [comment]
@ditsuke  is this fine?
![Screenshot (1976)](https://user-images.githubusercontent.com/54195688/151701234-9b5848c2-6298-47fd-a5c0-ed4829757a0c.png)

**Comment by pritam825** [comment]
or you are taking about this, here in the input field there will two values, one is yes and another one is no, and default value will be no, when we will click on yes, then it will so a warning message and after clicking "ok" on the warning button, it resets the history 
![Screenshot (1979)](https://user-images.githubusercontent.com/54195688/151702625-554dc1cf-0f1b-45f5-8836-f0881ba23f72.png)

**Comment by ditsuke** [comment]
@pritam825 take a look at this reset button for user API tokens. I believe we should have a similar radio here. You can have a look at the underlying form XML at `plugins/user/token/forms/token.xml`

![image](https://user-images.githubusercontent.com/72784348/151706093-d901a16e-6791-4657-844f-1a6b479c1d59.png)

**Comment by Quy** [comment]
Or add a reset button next to Time Executed  and Times Failed. See Banners component where this is done.

**Comment by brianteeman** [comment]
Definitely this way is the way to go

![image](https://user-images.githubusercontent.com/1296369/151706927-0712bf15-fe63-4152-a610-9a69b29b5665.png)

**Comment by ditsuke** [comment]
> Definitely this way is the way to go
> 
> ![image](https://user-images.githubusercontent.com/1296369/151706927-0712bf15-fe63-4152-a610-9a69b29b5665.png)

Better yet! Inline these buttons for supported stats. Although not sure if Times Failed and Times Executed should be decoupled.

**Comment by brianteeman** [comment]
please test #37201

**Comment by pritam825** [comment]
@brianteeman I was also working on this improvement and did the same thing as you do, but you opened before me🥺😊

**Comment by pritam825** [comment]
@brianteeman , I had also done the same thing, by getting and understanding the code of banners, but You created the PR first

**Comment by pritam825** [comment]
Can I create mine🥺

**Comment by brianteeman** [comment]
if its different sure.

**Comment by pritam825** [comment]
It's almost same,the only change in the file name, I have saved the file name with Times_executed_field and Times_failled_field 🥺, and the code is same because the same logic as of ClickField.php in com_banners

**Comment by pritam825** [comment]
so, can I create mine? 🥺

**Comment by richard67** [comment]
It seems Brian was faster. That can happen sometimes.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37201 . Thanks in advance.

**Comment by pritam825** [comment]
@richard67 yes, Thanks

**Comment by richard67** [comment]
Re-opening since the pull request has been closed by it’s author.

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/38486#issuecomment-1217704680
