### ISSUE TITLE
[4.1 ScheduledTasks] - %s seconds duration

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#36450]
### Steps to reproduce the issue

Manually trigger a GET request ScheduledTask to http://httpbin.org/get

### Expected result

`Duration: 0 seconds`
`Duration: 1 second`
`Duration: 2 seconds`

### Actual result

`%d seconds`

<img width="374" alt="Screenshot 2021-12-27 at 22 42 47" src="https://user-images.githubusercontent.com/400092/147511813-fd698e7c-3aa4-4b8c-9e3b-7a6b4aed051c.png">

**Comment by PhilETaylor** [comment]
same if you use the `sleep` task for 15 seconds:
<img width="284" alt="Screenshot 2021-12-27 at 22 47 32" src="https://user-images.githubusercontent.com/400092/147511999-113ab939-0416-417f-a395-fb352603cffa.png">

**Comment by PhilETaylor** [comment]
@ditsuke

**Comment by brianteeman** [comment]
I thought that already was fixed

**Comment by PhilETaylor** [comment]
my git repo is at 9a5a7784e347d9be663bdd2038050b7b76d5452e which is the very latest https://github.com/joomla/joomla-cms/commits/4.1-dev

**Comment by brianteeman** [comment]
#36297

**Comment by Quy** [comment]
#36297 Merged
