### ISSUE TITLE
[4.1] Filter options clear buttons height mismatch 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#36451]
<img width="267" alt="Screenshot 2021-12-27 at 22 52 56" src="https://user-images.githubusercontent.com/400092/147512182-451569b5-1fc8-4962-9f9e-5472470fcf29.png">
<img width="262" alt="Screenshot 2021-12-27 at 22 53 26" src="https://user-images.githubusercontent.com/400092/147512190-70468459-9438-49fb-abf7-a1223cc822df.png">

Safari on mac

**Comment by brianteeman** [comment]
Pretty sure I submitted a pr to fix that

**Comment by Quy** [comment]
#36246 not yet unmerged to v4.1
