### ISSUE TITLE
[4.1 ScheduledTasks] 0 is not a valid CRON expression

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#36452]
### Steps to reproduce the issue
@ditsuke 

Create a new scheduled task 

select execution rule = Cron Expression 

### Expected result

Select: 0 0 1 January Monday 

<img width="780" alt="Screenshot 2021-12-27 at 22 58 12" src="https://user-images.githubusercontent.com/400092/147512363-9fa76b70-3428-45ab-9b8a-a5780ec27a0c.png">

click save 

### Actual result

<img width="580" alt="Screenshot 2021-12-27 at 22 59 01" src="https://user-images.githubusercontent.com/400092/147512373-9e302d78-d28c-4515-a11b-1d819098e67f.png">

Im unable to get ANY cron expression to save. 

### Also

Well firstly if select "Cron Expression (Advanced)" I expect to enter my cron syntax in myself, manually, like the expert I am. 

I want a text box I can past in my cron expression like...
`*/15 * * * *`

------

Secondly - I note that the select boxes have the wrong integers? Monday in cron is `1` whereas in the select box its `0` is this being taken into account?

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36927 . Thanks in advance.
