### ISSUE TITLE
[4.1 ScheduledTasks] No way to see which tasks have failed

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#36459]
### Steps to reproduce the issue

A schedule task just failed..

### Expected result

Something red... something in my face that tells me without having to go into each and every task, and then execution history tab, to see whether it has succeeded on its last run or not... 

### Actual result
On the Scheduled Tasks overview page you can see the Last Run Date, and you can see a Running Man icon for "running" tasks, but there is no visual way of seeing which of the 100 scheduled tasks failed on their last run. 

<img width="1291" alt="Screenshot 2021-12-27 at 23 29 57" src="https://user-images.githubusercontent.com/400092/147513565-462d9255-d291-44ed-b4b9-0f16c5292872.png">

@ditsuke

**Comment by pritam825** [comment]
can I do like if it fails then run test color becomes red, and if passed then it will become green, can I work in this direction?

**Comment by pritam825** [comment]
should we change the run test button name also, shouldn't it be Run Task?

**Comment by ditsuke** [comment]
@pritam825 I'm afraid I'd done some work on this issue already. I've tried a group of indicators and think I finally settled on one so PR comes soon.

**Comment by brianteeman** [comment]
> can I do like if it fails then run test color becomes red, and if passed then it will become green, can I work in this direction?

No - you must never rely on color alone as an indicator for anything.

**Comment by Quy** [comment]
Closing as having a pull request. Please test #36765. Thanks in advance.
