### ISSUE TITLE
[3.10] [4.0] Classes for Articles custom fields and Articles custom field labels are not rendered

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#36467]
### Steps to reproduce the issue
In either J3.10 or J4.0.5 create a custom fields. I used a basic 'text' field.
In the Options tab, add a class for 'Field Class' and one for 'Label Class (Form)'.
Create or edit an article and add some text to the field.
View the article on the front end and use the browser's inspector.

### Expected result
The field should be wrapped in a span with the associated class, e.g.

```<span class="field-label my-field-class">Field label</span>```
```<span class="field-value my-label-class">Text of field</span>```

### Actual result
```<span class="field-label ">Field label</span>```
```<span class="field-value ">Text of field</span>```

**Comment by brianteeman** [comment]
Can not replicate

![image](https://user-images.githubusercontent.com/1296369/147596949-31e45d5a-bfc2-4148-9dfc-8e098d0a3d39.png)

**Comment by brianteeman** [comment]
> In the Options tab, add a class for 'Field Class' and one for 'Label Class (Form)'.

Thats the problem. They are for the FORM ie for editing. Scroll down

![image](https://user-images.githubusercontent.com/1296369/147597103-5782b502-a8e2-4080-b3d8-8d3097d7c9dc.png)

**Comment by brianteeman** [comment]
Note there is a PR from me to rename the Render Options to Display Options

**Comment by Scrabble96** [comment]
Thank you. That was indeed the issue. Sorry.
