### ISSUE TITLE
[4.0] Inconsistent language file handling in com_mails

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#36462]
### Steps to reproduce the issue

Install attached component - com_bftest.zip

https://brainforge.co.uk/media/extra_downloads/com_bftest.zip

### Expected result

Component emails appear listed in
``` https://mytestsite/administrator/index.php?option=com_mails&view=templates ```

### Actual result

Emails appear in mail template listing view - correct.

Click on a component mail in order to edit it - OK.
Able to edit the component mail - OK.

ERROR - the mail title and description are not translated.

### System information (as much as possible)

PHP 7.4

### Additional comments

The problem appears to be that the edit page of the mails component is not reading language files from
``` administrator/component/com_bftest/language ```
It is only looking in
``` administrator/language ```
This is inconsistent with elsewhere in Joomla.

![screen shot 2021-12-28 at 09 42 58](https://issues.joomla.org/uploads/1/57c6da38b888ff10c19261cd3bd7028b.png)![screen shot 2021-12-28 at 09 43 53](https://issues.joomla.org/uploads/1/2f23e04314a37995ef199a9c38d50882.png)

**Comment by brianteeman** [comment]
please test #36463

**Comment by alikon** [comment]
closing as we have a pr to test #36463
