### ISSUE TITLE
Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#36477]
Hey @dgrammatiko one for you? means nothing to me :) haha

I get this when running `jinstall`

<img width="1288" alt="Screenshot 2021-12-29 at 14 55 42" src="https://user-images.githubusercontent.com/400092/147674972-336ffdb8-2c9d-4943-a7fa-2208af8ef20e.png">

**Comment by dgrammatiko** [comment]
There's already a PR for this: https://github.com/joomla/joomla-cms/pull/35648

I think @wilsonge waits for Font Awesome to fix their part upstream

**Comment by PhilETaylor** [comment]
Awesome thanks.
