### ISSUE TITLE
[4.x] Wrong Update Channel

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36497]
On a clean install of J4 you are on the **default** update channel.

BUT if  you have updated from j3 you are on the **next** update channel

I suppose that as part of the update process from j3 the update channel should be changed back to **default**

**Comment by zero-24** [comment]
> I suppose that as part of the update process from j3 the update channel should be changed back to default

No in the past we have not changed the update server after the update and I'm not sure whether we should do that as we have not directly changed settings done by our users "in the background".

So for now this is the expected behavior the question would be whether we want to change this behavior in the future.

**Comment by brianteeman** [comment]
Not changing it is a problem when we reach j5. Not making the change now means the **default** and **next** channels have to be identical and so that means you will need another channel for j5

**Comment by zero-24** [comment]
The next channel is nearly identical to the default channel already.

Default (keeps you in the current major)
Next (provides updates to the next major and keeps that version up-to-date)

Right now we also make sure that when you go via the next channel and you are still on 3.x that you get the latest updates for 3.10 too before going to 4. I would say a similiar thing has to be done for j4->j5 too.

In the updater we display a message "you are on the next update channel and will get the next major as soon its aviable"

So on every update the admin knows what update server he is running.

But i can also understand your point, but i'm reluctant as we specificly choose in the past (even for security relevant stuff) to not change user defined settings on updates.

We might could provide a postinstallation warning reminding the users about this setting and provide more context about what this means?

Using that we can make sure the users can do an informend decision and we can help them with an "reset to default" button as postinstall action.

**Comment by brianteeman** [comment]
Better yet would be to automatically make the change (if they are on the Next channel only) and then add a message
"We have reset your update channel ..."

**Comment by zero-24** [comment]
Has this been closed accidentally or intentionally?

**Comment by brianteeman** [comment]
wow and look what happened 3 years later
