### ISSUE TITLE
[4.0] System > Install > Discover does not show when a new template is available

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#36495]
### Steps to reproduce the issue
Install J4.0x
Upload and extract another J4 template to the templates folder in cPanel (or other) File Manager

### Expected result
In the Joomla System > Install > Discover you should expect to see a '1' like you do for extension updates.

### Actual result
It shows a green tick, implying that there is nothing to discover

### System information (as much as possible)
J4.0.5
PHP 8.0

**Comment by brianteeman** [comment]
It's a bug I reported a long time ago. If you open the discover you will see its there and when you go back to the system dashboard it will show 1.

**Comment by Scrabble96** [comment]
Ok. I'll close this.
