### ISSUE TITLE
[4.1] Error: 0 in the frontend after installing nightly build + demo data 

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#36517]
### Steps to reproduce the issue
Used the latest nightly build which is available on 01.01. All I did was install the build, tested the PR https://github.com/joomla/joomla-cms/pull/36515 (i.e. created 1 task) and then installed the demo data (NOT multilingual). Everything, the frontend fell off. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/147847543-be355826-5efa-482c-a49f-85ac74b48d55.png)

### System information (as much as possible)
Joomla 4.1 Nightly Builds on 01.01
PHP 7.2.34

**Comment by chmst** [comment]
Please test #36505

**Comment by PhilETaylor** [comment]
Already fixed https://github.com/joomla/joomla-cms/pull/36505

**Comment by chmst** [comment]
Closing as there is a PR
