### ISSUE TITLE
DRONE BUILD BROKEN - RELEASE BLOCKER

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#36520]
@HLeithner  Something has been merged that has broken the build. 

All PR builds are now failing. 

see:  phpmin-api-mysql

<img width="1067" alt="Screenshot 2022-01-01 at 11 30 43" src="https://user-images.githubusercontent.com/400092/147849571-a4564a32-ca5f-4e04-987f-b49ed160b1e9.png">

**Comment by PhilETaylor** [comment]
maybe this will fix it? https://github.com/joomla/joomla-cms/pull/36521

**Comment by HLeithner** [comment]
I restarted https://ci.joomla.org/joomla/joomla-cms/49935/1/1 (last I have seen working for 4.0) checking if it's the image or something merged

**Comment by PhilETaylor** [comment]
Looks like this broke it? https://github.com/joomla/joomla-cms/commit/6dc01f5c4951686271171d2f28faf002010ceb40

**Comment by HLeithner** [comment]
that's an upmerge from 4.0 to 4.1, 4.1 worked before this upmerge, so it looks more like somthing got merged into 4.0 which is broken

**Comment by PhilETaylor** [comment]
Cool - I'll leave it with you :)

**Comment by PhilETaylor** [comment]
The law of averages probably says I screwed up then... 
<img width="582" alt="Screenshot 2022-01-01 at 11 41 25" src="https://user-images.githubusercontent.com/400092/147849717-a53ae6c3-2bed-4fe6-8d85-553a1075a301.png">

**Comment by HLeithner** [comment]
https://ci.joomla.org/joomla/joomla-cms/49935/1/1 still works so must be a pr

**Comment by HLeithner** [comment]
I like it when PRs are merged blindly...

**Comment by PhilETaylor** [comment]
here https://github.com/joomla/joomla-cms/commit/6dc01f5c4951686271171d2f28faf002010ceb40#diff-607a1be0b730bbf7e30979fd2535b8f8f6b2a2574cd2cfa5f4b5eda5c80014c0 in the merge up that I referred to earlier

**Comment by HLeithner** [comment]
good that I thought 4.0 is broken...

**Comment by PhilETaylor** [comment]
<img width="583" alt="Screenshot 2022-01-01 at 11 50 17" src="https://user-images.githubusercontent.com/400092/147849843-50eb3526-fcd4-4d90-8301-3231a5dc8790.png">

**Comment by PhilETaylor** [comment]
Helper\Api there was changed

**Comment by PhilETaylor** [comment]
looks like that came from @laoneo https://github.com/joomla/joomla-cms/pull/35989

**Comment by PhilETaylor** [comment]
Confused.

**Comment by PhilETaylor** [comment]
maybe this? https://github.com/joomla/joomla-cms/pull/36521

**Comment by PhilETaylor** [comment]
yeah that fixes the issue - but now the unit tests fail 

```
 [PHPUnit\Framework\Exception] Undefined index: cmsPath at tests/Codeception/_support/Helper/Api.php:76  
```

**Comment by HLeithner** [comment]
https://github.com/joomla/joomla-cms/pull/36510 benjamin fixed it to on another position but get the same error

**Comment by dgrammatiko** [comment]
Didn't someone updated codeception to the next major version? Maybe there's a B/C break there...

**Comment by bembelimen** [comment]
Thanks for the report, we're working on it (thanks @HLeithner for the help). I messed something up at the upmerge.

**Comment by PhilETaylor** [comment]
Thanks!
