### ISSUE TITLE
[4.1 Scheduled Tasks] The date in the task completion notification is not translated

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#36522]
### Steps to reproduce the issue
When you receive a notification about the progress of a task, the date is not translated into the default language for the site / control panel.

@ditsuke 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/147850673-bd81f2a8-aebc-45b8-9ee6-b90766845b9e.png)

**Comment by shagungarg0** [comment]
Can i work on this issue?

**Comment by brianteeman** [comment]
You dont need to ask!!

**Comment by brianteeman** [comment]
Please test #37556
