### ISSUE TITLE
attributes not attribute in developer.joomla.org/schemas/json-schema/web_assets.json!!!

### ISSUE THREAD

**Issue by JProof** [joomla/joomla-cms#36530]
### Steps to reproduce the issue

Using completion during work with joomla.asset.json
the ressource definition contains "attribute"
https://developer.joomla.org/schemas/json-schema/web_assets.json

But this is wrong 
Joomla\CMS\WebAsset\WebAssetItemInterface
/**
	 * Get all attributes
	 *
	 * @return array
	 *
	 * @since   4.0.0
	 */
	public function getAttributes(): array;

Please correct the https://developer.joomla.org/schemas/json-schema/web_assets.json definition

**Comment by brianteeman** [comment]
This has now been resolved and can be closed

**Comment by richard67** [comment]
Closing as solved with https://github.com/joomla/schemas/pull/9 .

@JProof Thanks for reporting the issue.

@brianteeman Thanks for solving the issue.

**Comment by wilsonge** [comment]
Just as a quick update. Jenkins deploy failed for this when I merged it last night. Just fixed the jenkins job now and it's just deployed in the last 10 minutes
