### ISSUE TITLE
[4.0] Should the front editor reCaptcha appear on all tabs - not just content?

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#36535]
### Problem identified
In order to save changes to an article, it is necessary to check/tick the reCaptcha box first, but this only appears on the Content tab.
If you're working your way through an article, changing its content, adding a publishing date and then adding a meta description, then I would prefer to be able to save the article from that tab, rather than having to go back to the content tab first.

### Proposed solution
Show reCaptcha on all tabs, i.e. Images and Links, Fields, Publishing, Metadata

**Comment by PhilETaylor** [comment]
> Show reCaptcha on all tabs, i.e. Images and Links, Fields, Publishing, Metadata

There can only be one reCaptcha. It should be outside the tabbed interface.

**Comment by Scrabble96** [comment]
Good answer!

**Comment by Scrabble96** [comment]
Does anyone have the know-how to change this? I don't.

**Comment by brianteeman** [comment]
As with so many things its just a template override. This time its the components/com_content/tmpl/form/edit.php

Just move this code to where you want it
```
				<?php if ($this->captchaEnabled) : ?>
					<?php echo $this->form->renderField('captcha'); ?>
				<?php endif; ?>
```

For example if you move it after the `uitab.endTabSet` it will show directly below the form no matter which tab you are on

![image](https://user-images.githubusercontent.com/1296369/156748638-b8a53f1b-50c4-47a8-8980-d0838929d9db.png)

Or if you move it inside a tab then it will show just on that tab

![image](https://user-images.githubusercontent.com/1296369/156748876-16675196-f613-4a40-b84c-8871abe2d898.png)

**Comment by brianteeman** [comment]
can be closed

**Comment by Scrabble96** [comment]
> As with so many things its just a template override. This time its the components/com_content/tmpl/form/edit.php
> 
> Just move this code to where you want it
> 
Thanks, Brian. I've only just seen this. It may be that "it's 'just' a template override" but anyone new to Joomla wouldn't know that. It took me months from first learning about Joomla (from a YouTube video) to discovering overrides, especially as I had no knowledge of PHP at the time.
