### ISSUE TITLE
[J4] Improving back end display of custom fields "list" and "SQL"

### ISSUE THREAD

**Issue by crystalenka** [joomla/joomla-cms#36548]
### Is your feature request related to a problem? Please describe.
For the custom field types 'list' and 'SQL', if multiple = true, we are shown a list in a box where to select multiple items you have to hold down CMD or CTRL.

<img width="900" alt="" src="https://user-images.githubusercontent.com/9141288/147939288-087c4cf5-1b88-4cf4-9af9-111eaf77cf5c.png">

This is hard for some people to understand and use, and seems terribly old-fashioned (web-wise).

### Describe the solution you'd like
At a minimum, it would be nice if these fields rendered with the core fancy select list when multiple items are possible.

<img width="300" alt="" src="https://user-images.githubusercontent.com/9141288/147940058-63738f3d-adb7-4847-890f-e25efe5c750c.png">

### Additional context
For consistency, it could also be a better user experience to use the fancy select even when selecting one item; the default drop-down is cumbersome when there are many items and it would be nice to be able to type to find a specific item. This is consistent with the category selection in articles and in other places.

<img width="300" alt="" src="https://user-images.githubusercontent.com/9141288/147940120-429aad70-05e3-48d7-a69d-1aa5c3c4d2a8.png">

**Comment by nikosdion** [comment]
@laoneo Wanna take a look at this? This sounds like a reasonable way to implement it, possibly with an option in the field plugin.

**Comment by brianteeman** [comment]
I think there is already an open issue for this.

**Comment by laoneo** [comment]
This would be a new option where the layout can be defined. The choices.js ones need the layout `joomla.form.field.list-fancy-select`.

**Comment by nikosdion** [comment]
If there was an option to define the layout I'd **love** it. I have several use cases on my site and the upcoming version of my Ticket System software where it'd made a hell of a lot more sense than the default layout. Would you have the time to do a PR? I can promise a test from both me and Crystal — each one of us has a different use case where we'd need it.

**Comment by crystalenka** [comment]
> This would be a new option where the layout can be defined. The choices.js ones need the layout `joomla.form.field.list-fancy-select`.

Allowing the layout to be defined would be absolutely utterly MAGICAL and open so many doors for custom fields for advanced integrators. 😮

> I think there is already an open issue for this.

I didn't see any, I did check!

**Comment by laoneo** [comment]
If we call it layout, we get into a collision with #36265. So we need another wording as this is for the layout of the field for form rendering.

**Comment by crystalenka** [comment]
Maybe "Form Layout"?

**Comment by brianteeman** [comment]
There is an issue from @wilsonge that all fields needed to be converted to use layouts perhaps that is the one I was thinking of. 

I know because I tried to do that and add support for fancy-field exactly as you request #34941. There was also another issue about creating layout overrides for fields https://github.com/joomla/joomla-cms/issues/36046. It was something I needed as well but failed to create to fell back to adding the field in the xml instead of a custom field. There are still quite a lot of gaps between fields (and options) you can create in xml and the same in the custom  fields component

**Comment by crystalenka** [comment]
I think that if someone is able to add the layout (form layout? Form render layout? Form field layout?) to custom fields it would go a long way in closing those gaps. I can just imagine the possibilities with custom subform layouts...

**Comment by brianteeman** [comment]
i agree 10000% but I tried myself and failed

**Comment by crystalenka** [comment]
I tried to take a look before opening the issue but couldn't make heads nor tails of where the layouts come from so it's sadly above my level too. :(

**Comment by laoneo** [comment]
Feedback welcome on #36551.

@nikosdion You can do that already without any core changes on your custom fields. The logic of the pr #36551 can be applied to any custom field. Setting the layout must then be done in your plugin in the `onCustomFieldsPrepareDom` method override.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36551 . Thanks in advance.
