### ISSUE TITLE
[J4] Media Manager icons do not respect permissions settings

### ISSUE THREAD

**Issue by crystalenka** [joomla/joomla-cms#36549]
### Steps to reproduce the issue
1. Create a user group "Test User Group".
2. Create a user "Test User" and assign to "Test User Group".
3. As a super user, navigate to the global configuration, and click permissions.
4. Click "test user group" and ensure it can log in to administrator. Save.
5.  In the configuration, click on media, and click permissions.
6. Select "Test User Group" and set "Access Administration Interface" and "Create" to "Allowed", and ensure all other permissions are set to "Not Allowed", like so:
<img width="475" alt="Screen Shot 2022-01-03 at 18 26 26" src="https://user-images.githubusercontent.com/9141288/147954799-fa34ca9f-d75c-4e11-8bd9-e671e26e81ca.png">
7. Login as "Test User", and go to media manager.

### Expected result
Test user can see and navigate media, but cannot rename, delete, or edit images or folders.

### Actual result
Test user has full permissions via the quick icons.
<img width="168" alt="Screen Shot 2022-01-03 at 18 28 04" src="https://user-images.githubusercontent.com/9141288/147954995-66f174e3-bb4e-42c1-97d9-25b90deea6b1.png">

### System information (as much as possible)
Joomla 4.0.5
PHP 8

### Additional comments
The "create" permission works as expected. It just seems that those icons that appear on hover do not respect permissions at all. This is also true from the image select field.

**Comment by brianteeman** [comment]
Can you try changing the plugin access levels
![image](https://user-images.githubusercontent.com/1296369/147958061-49499971-416d-4823-91c5-7909bff34652.png)

**Comment by crystalenka** [comment]
I tried that, the icons still show up. It's just that pencil icon takes you to a blank view, which is in itself a bug.

<img width="401" alt="Screen Shot 2022-01-03 at 23 57 23" src="https://user-images.githubusercontent.com/9141288/147984869-3c4b4524-52b0-476d-9211-2086bbc2fc60.png">
<img width="1039" alt="Screen Shot 2022-01-03 at 23 57 34" src="https://user-images.githubusercontent.com/9141288/147984876-96d843d4-04cc-4ff1-81bc-1bf6dd74cc27.png">

There's also no plugin for renaming or deleting, both which I would imagine should respect the permissions in com_media?

**Comment by brianteeman** [comment]
> I tried that, the icons still show up. It's just that pencil icon takes you to a blank view, which is in itself a bug.

Ah - thats why I remembered that ;)

**Comment by dgrammatiko** [comment]
There's a PR: #36556

**Comment by crystalenka** [comment]
Thanks! I'll test this and the other media manager PR in a little bit.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36556 . Thanks in advance.
