### ISSUE TITLE
[4] improve media view

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#36545]
hello i think we can improve media view with a small modification
For now media view isn't optimise for long list of image or media
we need may scroll up down for many action :
- change folder
- search
- change view

i propose to fix search and sidebar
a concept here
<a href="https://www.loom.com/share/d29286f12414425f889ec2d913b79733">
    <p></p>
    <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/d29286f12414425f889ec2d913b79733-with-play.gif">
  </a>

https://www.loom.com/embed/d29286f12414425f889ec2d913b79733

**Comment by brianteeman** [comment]
On the list view I would probably make the table column headers sticky as well.

Looking forward to testing the pr

**Comment by micker** [comment]
i am not sure about good rules for a pr
i put here first draft of code (an maybe if some one can help me for a clean pr)
in media-manager.css
change
`.media-toolbar {
  position:sticky;
  top:67px;
  z-index:1;`
and change 
`.media-drive {
    position: fixed;
    z-index: 1;
}`
and add
`thead.media-browser-table-head {
  position: sticky;
  top: 124px;
  z-index: 1;
}`
TODO
check thead render
check folder sidebar => maybe the solution is to add js
https://www.loom.com/share/9460851222c446e9ba72a1161395d07c

**Comment by akshitrattan** [comment]
one more solution to this issue can be adding the 'position: fixed;' property in the 'media-disk' class in 'media-manager.css'

**Comment by akshitrattan** [comment]
@brianteeman 
Also, I would like to make a PR for this issue, may I??

**Comment by micker** [comment]
Very cool thanks

**Comment by Shubhamverma2796** [comment]
@micker please test #36658

**Comment by alikon** [comment]
closing as we have a pr #36658

**Comment by Quy** [comment]
Please test PR #37397. Thanks.
