### ISSUE TITLE
Issues with URL built for 'Category Blog' Menu Item having Tags selected.

### ISSUE THREAD

**Issue by narainrajat** [joomla/joomla-cms#36546]
### Steps to reproduce the issue
(1) Create a Category, say 'Blog'
(2) Create several tags, say 'A', 'B', 'C'
(3) Create multiple articles with category Blog and associate with 1 or more of the tags. 
(4) Create a 'Category Blog' menu item for the category 'Blog', and set 'Tags' field to one or more Tags, say 'A'.
(5) Lets say, this menu item is set up as a root menu item and given an alias of 'category-blog'.

### Expected result
Since the menu item has been setup, I would expect the link in the menu to read... '<host name>/category_blog'

### Actual result
The URL built in the menu instead reads, '<host name>/category_blog?filter_tag[0]=1', where 1 is the tag id for the tag A which was set in the menu item params. 

The tag information, that is set in the menu item appears as a query var, which can be manipulated by the site visitor to display content of any other tag by changing the value of the tag id. This should never be the case as the tag was specifically set in the menu item and is intended to display only the content associated with the selected tag.

### System information (as much as possible)
Joomla 4.0.5 (and previous Joomla 4 versions).

### Additional comments
NOTE THAT IT BEHAVED (AND STILL BEHAVES) CORRECTLY IN JOOMLA 3.X series.

**Comment by richard67** [comment]
I am almost sure this has been reported several times before, but I‘m too tired to search for the other issues now.

**Comment by Quy** [comment]
See PR #34652 however it appears to be not the right fix.

**Comment by brianteeman** [comment]
Closed as resolved with #40225
