### ISSUE TITLE
Joomla4 Frontend Editing of Articles - Existing Article Content Not Populated

### ISSUE THREAD

**Issue by laybergerF** [joomla/joomla-cms#36541]
### Discussed in https://github.com/joomla/joomla-cms/discussions/36540

<div type='discussions-op-text'>

<sup>Originally posted by **laybergerF** January  2, 2022</sup>
Hi, We are building a new site founded on Joomla 4, and would like to only use core extension like the Article features built into Joomla 4, but we've run into a wall trying to implement editing an article from the Frontend of the site. We've found an effective way to get an article that we want to edit to display within the Article Editor on the Frontend except it fails to come up with the content included in the original (it comes up blank). What do we need to do to get the content of the selected, existing article to be included for editing on the Frontend of the site? I've included screen captures showing how we get the Event Editor to display on the Frontend and the resulting, blank, unpopulated editor.

![ArticleEditig-NoPopulatingOfContent-2022-01-02-10_17_27](https://user-images.githubusercontent.com/5634531/147887726-29900642-ce7c-4e67-be5c-a73e0882a2d7.jpg)
.</div>

**Comment by richard67** [comment]
You should have answered the question in the linked discussion instead of just posting the same text again in an issue. How can you expect to get help if you just ignore questions for more Information?

**Comment by laybergerF** [comment]
I'm sorry, I have not seen a request for additional information, which I would be happy to provide.

**Comment by brianteeman** [comment]
Please close this as a duplicate

**Comment by richard67** [comment]
@laybergerF The request for additional info was in the discussion item, #36540 .
