### ISSUE TITLE
[J4] "Articles - Latest" admin module does not respect "edit own" permissions

### ISSUE THREAD

**Issue by crystalenka** [joomla/joomla-cms#36558]
### Steps to reproduce the issue
1. Create a user group "Test User Group".
2. Create a user "Test User" and assign to "Test User Group".
3. As a super user, navigate to the global configuration, and click permissions.
4. Click "test user group" and ensure it can log in to administrator. Save.
5. In the configuration, click on Articles, and click permissions.
6. Select "Test User Group" and set "Access Administration Interface" and "Edit Own" to "Allowed", and ensure all other permissions are set to "Not Allowed", like so:

<img width="512" alt="Screen Shot 2022-01-04 at 12 32 21" src="https://user-images.githubusercontent.com/9141288/148046052-e32b1a5e-180b-42bf-88b8-875cde502aea.png">

7. Save.
8. Go to content > administrator modules, and create a new module with type "Articles - Latest". Assign it to cpanel, set category to "any category", and set authors to "added or modified by me", like so:

<img width="941" alt="Screen Shot 2022-01-04 at 12 34 22" src="https://user-images.githubusercontent.com/9141288/148046357-daa812a9-9918-4130-b9ff-a1e35b522065.png">

9. Save and close.
10. Log in as Test User.
11. Create a new article in any category and save it.
12. Navigate to the home dashboard.

### Expected result
The article is shown with a linked title so that the user can edit their own article:
<img width="608" alt="Screen Shot 2022-01-04 at 12 36 40" src="https://user-images.githubusercontent.com/9141288/148046631-a4f04b7f-aa62-4f21-8d29-0c770b950bc6.png">

### Actual result
The title is not linked even though the user has permission to edit their own article:
<img width="608" alt="Screen Shot 2022-01-04 at 12 37 38" src="https://user-images.githubusercontent.com/9141288/148046725-f49a63d3-ad7b-4267-8df0-fefcbeed5c67.png">

### System information (as much as possible)
Joomla 4.0.5
PHP 8

### Additional comments
The title is only linked if the user group is given edit access to all articles:
<img width="495" alt="Screen Shot 2022-01-04 at 12 38 40" src="https://user-images.githubusercontent.com/9141288/148046843-c46fab97-cd12-4ce8-bba7-549c49e11376.png">

The module helper seems to be trying to check the user permissions against the article ID, so something here must not be working right:

```
if ($user->authorise('core.edit', 'com_content.article.' . $item->id))
			{
				$item->link = Route::_('index.php?option=com_content&task=article.edit&id=' . $item->id);
			}
```
_(administrator/modules/mod_latest/src/Helper/LatestHelper.php lines 99-102)_

**Comment by Quy** [comment]
#36559
