### ISSUE TITLE
joomla-field-media.js error  Frontend Article Editor

### ISSUE THREAD

**Issue by laybergerF** [joomla/joomla-cms#36563]
### Steps to reproduce the issue
Log into site with permissions to edit articles from Frontend. Access an existing article. Select the 'Edit' option which launches the Article Editor. 

### Expected result
When the editor opens, it should be populated with the content from the article selected to edit.

### Actual result
The editor opens without any content from the article selected to edit: it's blank. No errors are displayed even with debug on and reporting set to maximum. The browser console displays the following error: 

joomla-field-media.js?b9214e72c06daafd562e5c4116292b5763a437fe:172 Uncaught TypeError: window.bootstrap.Modal.getInstance is not a function
    at HTMLElement.connectedCallback (joomla-field-media.js?b9214e72c06daafd562e5c4116292b5763a437fe:172)
    at joomla-field-media.js?b9214e72c06daafd562e5c4116292b5763a437fe:325

### System information (as much as possible)
Joomla 4.0.5, PHP 7.4.27, mySQL 5.6.41-84.1, T4 2.0.9, T4_bs5_blank Template 1.1.2. TinyMCE 5.10.2.

### Additional comments
The same results occur with the JCE and CodeMirror editors, and using the Cassiopeia template with the T4 framework/template disabled.

**Comment by dgrammatiko** [comment]
Does it work with the build in tinyMCE? If so the problem is JCE

**Comment by laybergerF** [comment]
No, it doesn't work with tinyMCE.

**Comment by dgrammatiko** [comment]
Can you uninstall all the 3rd PD extensions and add them back one at a time till you figure out which one is breaking Joomla?

**Comment by laybergerF** [comment]
To do that, I'll have to set up a test system and it will be time consuming so I'm hoping that I don't, and that someone will be able to pinpoint the cause or at least provide some more specific insight on where to look for it's cause.

**Comment by dgrammatiko** [comment]
Well, you need to uninstall extensions that potential could cause this problem. I said JCE as I know that it completely replaces the media field. The other area is to remove your template and any framework that came with it. My point is that the default template works fine...

**Comment by laybergerF** [comment]
Oh, I understand and I've started the process of building a test configuration on my localhost system

**Comment by laybergerF** [comment]
Okay, I've now been able to narrow the problem down. With all of the T4 items disabled, and with the Cassiopeia template set as the site default template, the problem still shows up. It can be reproduced by creating a menu item with a menu type of 'List All Categories in an Article Category Tree'. When logged into the Frontend  as an authorized user, selecting a category from the page displayed by the menu will bring up all of the articles being included in the selected category. Selecting the 'Edit' button next to an article will bring up the article editor which should be populated with the content of the article, but in this case it comes up blank. No errors are displayed even with debug and max errors enabled. There are no javascript errors displayed in the browser console.

**Comment by laybergerF** [comment]
A little more information: For testing, I set a menu item for a single article and set it as the default page. With T4 still uninstalled and the Cassiopeia template set as the default for all pages, selecting 'Edit' still brings up the Frontend article editor void of content.

**Comment by AMurray2016** [comment]
Just chiming in - the Joomla forum discussion on this issue is here: https://forum.joomla.org/viewtopic.php?f=812&t=990923.  

I've been trying to help @laybergerF on the forum but I've run out of ideas and it was my final suggestion to post it on the Issue Tracker.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36563">issues.joomla.org/tracker/joomla-cms/36563</a>.</sub>

**Comment by laybergerF** [comment]
@AMurray2016, thank you for your assistance!

**Comment by drmenzelit** [comment]
Can you try on a clean J4 installation? Maybe there are some leftovers from your 3rd-party installations.
I can't reproduce the issue on my test J4 site.

**Comment by laybergerF** [comment]
Thank you. This issue has been resolved by copying all of the Joomla 4 files from a fresh install over top of the existing site files.
