### ISSUE TITLE
[4.1] Multiple issues since moving template media

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36581]
### Steps to reproduce the issue
Install nightly or make sure your using the latest branch and have run npm i

## Status select
css is looking for select-bg.svg in the templates folder **not** the media/templates folder
![image](https://user-images.githubusercontent.com/1296369/148354408-4afe4dca-8aaf-4909-adca-d8a3ad4a1ec1.png)

![image](https://user-images.githubusercontent.com/1296369/148354442-b7ad5f9a-b38f-4f06-8604-ad5824c1944c.png)

## Template Preview
incorrect path to the template_preview

![image](https://user-images.githubusercontent.com/1296369/148355368-87d361f1-238a-4ed5-b621-27135a2aad5d.png)

![image](https://user-images.githubusercontent.com/1296369/148355477-09bddb04-9d81-4013-a8bc-fe45a964ed02.png)

**Comment by dgrammatiko** [comment]
You are in mixed mode, make sure the column `inheritable` is `1` in the table `#__template_styles` like so:
![Screenshot 2022-01-06 at 10 26 20](https://user-images.githubusercontent.com/3889375/148360656-c0e82b58-4594-4b6c-93f5-a632516f237e.png)


So, by this I can conclude that something is very wrong on the db side. Was that a new installation or did you just switch branches? If the second you have the update problem...

**Comment by brianteeman** [comment]
changing the db fixed the first problem

the template preview is not fixed though and looks like an error in `administrator\components\com_templates\src\Service\HTML\Templates.php`

If you look at the path it has an extra "administrator"

**Comment by dgrammatiko** [comment]
> If you look at the path it has an extra "administrator"

I will have a look in a bit.

FWIW the update SQL is a Release Blocker

**Comment by brianteeman** [comment]
closing for now
