### ISSUE TITLE
builds are all breaking again... 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#36621]
@HLeithner ? 
<img width="645" alt="Screenshot 2022-01-09 at 15 37 26" src="https://user-images.githubusercontent.com/400092/148689319-03599e4e-94a7-4b33-a4fd-640b190d53e6.png">

**Comment by HLeithner** [comment]
Have seen it but don't understand why it's marked as fail... because all failing tasks are set to failure:ignore....

I will investigate further

**Comment by HLeithner** [comment]
Hopefully fixed it.
