### ISSUE TITLE
[4.0] deprecation warning inside mod_banners in php 8.1

### ISSUE THREAD

**Issue by elpescador-nl** [joomla/joomla-cms#36623]
### Steps to reproduce the issue
Add a banner module without header/footer text

### Expected result
No deprecation warning

### Actual result
A deprecation warning:
```
Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /path/to/joomla4/modules/mod_banners/mod_banners.php on line 16
```
### System information (as much as possible)
Joomla! 4.0.5
php 8.1.1

**Comment by elpescador-nl** [comment]
This:
https://github.com/joomla/joomla-cms/blob/ca0c42d0ae2b939fb46d6f5651e22a4932d2bb38/modules/mod_banners/mod_banners.php#L16-L17

Replaced by this, might be the simplest solution:
```
 $headerText = trim($params->get('header_text', '')); 
 $footerText = trim($params->get('footer_text', ''));
```

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/36625

**Comment by alikon** [comment]
please test #36625
