### ISSUE TITLE
Meta Keywords Missing in J4

### ISSUE THREAD

**Issue by arunsasi** [joomla/joomla-cms#36639]
[###] Steps to reproduce the issue

Meta Keywords missing in J4 compared to J3 in Menu settings

[https://ibb.co/bW84Yrz](url)

**Comment by brianteeman** [comment]
This is intentional as meta keywords are no longer used

**Comment by arunsasi** [comment]
Google may rule out. There are other search engine out there, Bing is not going to rule out similarly Yandex and baidu.

**Comment by brianteeman** [comment]
They dont use it either

**Comment by infograf768** [comment]
https://www.metatags.org/all-meta-tags-overview/the-metatags-influence/metatags-bing/

**Comment by arunsasi** [comment]
As i know, SEO agency in china recommended meta keyword for my site.
 If intentionally removed then why keywords listing in article [https://ibb.co/bKH8j1f](url)

**Comment by brianteeman** [comment]
They are not metatags. They are keywords used for things like the related articles module

**Comment by richard67** [comment]
> As i know, SEO agency in china recommended meta keyword for my site.

Maybe this SEO agency has a bit outdated knowledge.

**Comment by PhilETaylor** [comment]
This should be closed as it was an architectural decision for Joomla 4.
