### ISSUE TITLE
Content of Custom Fields not found with SmartSearch

### ISSUE THREAD

**Issue by BPBlueprint** [joomla/joomla-cms#36632]
### Steps to reproduce the issue
1. Create Custom Field of type "text" or "editor" or "textarea"
2. Create a new article called "My test article" and enter some keywords for searching into the custom field (e.g. "My favourite fish is a pike")
3. Go to component > index and index all your content
4. Go to frontend and use Joomla!-search: enter "pike" or "fish"

### Expected result
The article "My test article" should be found by Joomla!-search

### Actual result
"No Results Found"

### System information (as much as possible)
Joomla! 4.0.5
PHP 8.0.14

**Comment by Quy** [comment]
Same issue reported in J3 #12829

**Comment by Quy** [comment]
Closing as there is a pull request. Please test #36747 . Thanks in advance.
