### ISSUE TITLE
Article category module

### ISSUE THREAD

**Issue by ajaydubey26** [joomla/joomla-cms#36649]
### Steps to reproduce the issue
Hi I have website in joomla 3 now i have updated from joomla 3.10 to joomla4. When i click on article category module link than it is generating not seo url. It was working in joomla 3 perfectly but not in joomla 4.

Now url showing like that:

http://localhost/joomla/?view=article&id=523370:abc-group-concludes-project-development-for-steel-forging-line-2&catid=52

can any body help me in this issue

**Comment by Quy** [comment]
Duplicate #36648

**Comment by chmst** [comment]
I tried to replicate the error with an own webiste but here it is as expected. You are sure that you have set the Switch for user friendly url in your local installation? 
Or is there a  template override from J3 for for  the article category module?

**Comment by rafal-nagorski** [comment]
I have the almost exact same issue after migrating from 3.10 to 4.06 in one site.

Another similar site has no issue.
I checked the main configuration and plugins on both sides. There is no difference.

Menu links to Articles -> Category Blog or Category List etc..
Link from the main menu is fine.
Link from the sitemap or module on the home page listing the same category is different from this in the main menu.

Example:
/blog-test/190-temporibus-sapiente-delectus.html - from main menu
?view=article&amp;id=190:temporibus-sapiente-delectus&amp;catid=42 - from site map or module on the home page

I don't know where to look for a possible error after migration.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36649">issues.joomla.org/tracker/joomla-cms/36649</a>.</sub>

**Comment by Hackwar** [comment]
In both cases the URL is missing the option part. I'm also assuming that both issues are because of a missing root menu item for the articles. I'm guessing that there is just a featured view as the main menu item. This is not a bug in Joomla.
