### ISSUE TITLE
[3.10] Pre-Update Check FAILS

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36644]
### Steps to reproduce the issue
Install joomla 3.10 on php 7.0
On completion set the joonla update channel to Joomla Next
Update Joomla

### Expected result
The pre-update check fails because the version of php is below the minimum

### Actual result
The pre-update check is checking for the php requirements of joomla 3 not joomla 4

![image](https://user-images.githubusercontent.com/1296369/148997442-f670c03a-6521-4097-91e9-c780a125564c.png)

**Comment by zero-24** [comment]
Yes this is a known issue and a dublicate of: https://github.com/joomla/joomla-cms/issues/36610#issue-1097003709 So Imo this here can be closed right?

**Comment by alikon** [comment]
humm
i've understood the issue reading this one, 
anyway 
i'll let the pr maker choose which it prefer to close first
:rofl:

**Comment by brianteeman** [comment]
I dont believe its a duplicate because I believe the description on yours is misleading/wrong

The reason that you see "PHP Version >= 5.3.10" is because 5.3.10 is the fallback string when the real update information is not found. Having said that I cannot find anywhere or any means for the correct php minimum requirements ever to be found.

```
	/**
	 * Returns the PHP minimum version for the update.
	 * Returns JOOMLA_MINIMUM_PHP, if there is no information given.
	 *
	 * @return string
	 *
	 * @since 3.10.0
	 */
	private function getTargetMinimumPHPVersion()
	{
		$updateInformation = $this->getUpdateInformation();

		return isset($updateInformation['object']->php_minimum) ?
			$updateInformation['object']->php_minimum->_data :
			JOOMLA_MINIMUM_PHP;
	}
```


THIS IS A RELEASE BLOCKER

**Comment by zero-24** [comment]
> I dont believe its a duplicate because I believe the description on yours is misleading/wrong

I tried to explain the technical reason that the information is not aviable, maybe it was not good enough. In the end its the same root cause and similiar to what george wrote on the other issue too.

**Comment by alikon** [comment]
btw let's focus on this a bit more

**Comment by brianteeman** [comment]
Your description is wrong. 
You are saying that the code to do the check is not taking place.
I am saying that it can never take place because the information does not exist

**Comment by zero-24** [comment]
> You are saying that the code to do the check is not taking place.

Again maybe my description is not good. But the check takes place and works as designed for now. As it pre dates the pre upgrade checker the filtering is already happening in JUpdate and when the version (php or mysql or stability) is not meet jupdate reports "we have found an update but no update object to download it" And as that update object is not aviable it does not have the correct versions and falls back to the minimum version set in the CMS.

**Comment by brianteeman** [comment]
> But the check takes place and works as designed for now. 

Where do we define that the minimum for php in j4 is xxxxx

**Comment by brianteeman** [comment]
not wasting more time

**Comment by zero-24** [comment]
> Where do we define that the minimum for php in j4 is xxxxx

https://github.com/joomla/update.joomla.org/blob/master/www/core/sts/extension_sts.xml#L59-L63
