### ISSUE TITLE
[4.0] - SEO link generation fails on single article view

### ISSUE THREAD

**Issue by janschoenherr** [joomla/joomla-cms#36648]
### Steps to reproduce the issue

Enable 'Search Engine Friendly URLs' in the system settings.

Create two articles (test,test2). In one of the articles create a link to the other article.

e.g. `<p><a href="index.php?option=com_content&amp;view=article&amp;id=1&amp;catid=2">test</a></p>`

Create a menu item of the type 'Single Article' referencing the article with the link.

### Expected result

In Joomla 3 this would result in a SEF friendly URL:

`<p><a href="/test/index.php/test2/1-test">test</a></p>`

### Actual result

In Joomla 4 this results in a non SEF friendly URL:

`<p><a href="/test/index.php/test2?view=article&amp;id=1&amp;catid=2">test</a></p>`

**Comment by ajaydubey26** [comment]
Hi I am facing same issue with joomla 4. can any one tell me the solution<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36648">issues.joomla.org/tracker/joomla-cms/36648</a>.</sub>

**Comment by devarsh-mavani-19** [comment]
I tried to reproduce the issue but I am getting the expected result.

**Comment by Hackwar** [comment]
How is the second article linked in your site? You will need a categories, category or article menu entry for an article to get a "nice" URL. If you are expecting the old behavior (Frontpage article menu item as homepage of the site and everything falls back to that one), that has been removed.

**Comment by euphoriatek** [comment]
I think I need to create a category list menu and then need to assign a module in that particular category menu. It can solve my issue.

**Comment by brianteeman** [comment]
After 8 months surely this should be closed
