### ISSUE TITLE
Word suggestion wrong font size in search box [Joomla 4]

### ISSUE THREAD

**Issue by DSist** [joomla/joomla-cms#36643]
### Steps to reproduce the issue

Open native Joomla Search page. Click on the search field for word suggestion list to be shown. Click on any suggestion word to put it into the search field. Click on the search field for word suggestion list to be shown again. Hover the pointer over any suggestion word and the word is temporarily put into the search field with its own default font size not from the template css. It causes the text to jerk changing its font size while you move the pointer between the search field and suggestion list.

### Expected result

All the word suggestion font parameters should be derived from the search field font (from the template css).

### System information (as much as possible)

Joomla 4.0.5

![joomla_search_box1](https://user-images.githubusercontent.com/95962014/148958845-142ed273-04dc-413b-972e-8cfe0cd1352f.png)
![joomla_search_box2](https://user-images.githubusercontent.com/95962014/148958884-9aeddae8-01e7-49cd-84f6-3c967ebae693.png)

**Comment by drmenzelit** [comment]
Sorry, but I can't follow your explanation... I don't see any difference in the font size from the search field and the suggestions list. The list is using the general font size from body. The input field (.form-control) has an extra definition for font-size: 1rem (the same as body). Only if you change the definition for the input field the font size will be different.

**Comment by DSist** [comment]
It is not about the suggestion list font, it is about temporary substitution font while you hovering over the suggestion list. I have no idea where this temporary substitution takes font parameters from as DevTools is of no help here, and it is not only about font size, it is about the font family too. I have described above how to reproduce the issue.

**Comment by Hackwar** [comment]
I can't replicate the behavior you are describing.

**Comment by DSist** [comment]
> I can't replicate the behavior you are describing.

I have just checked it again with Cassiopea default template. Try to enlarge font for the search field to see the difference clearly via DevTools (font-size: 20px) or via css:

.com-finder .input-group .form-control { font-size: 20px; }

The issue arises when you have something already typed in the search field, open suggestion list after and hover over the suggestion strings. Every time you hover over a suggestion word it is temporarily put into the search field with its own font parameters, replacing search field font parameters of the site template.

**Comment by brianteeman** [comment]
>  Every time you hover over a suggestion word it is temporarily put into the search field 

I cant replicate this - even after setting wildly different styles for the input and the suggestion

**Comment by Quy** [comment]
Closing as non reproducible.
