### ISSUE TITLE
[4.1] Scheduler activation

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36659]
The scheduler is a new component and its not obvious that out of the box the interval is only an approximate value. If no one visits your site the task wont be triggered.

I'm also a bit confused as to what my options are for triggering a task.

Is the native cron referred to here the web cron?  

![image](https://user-images.githubusercontent.com/1296369/149194681-0f621e73-8f03-456c-ad63-332dbb9e0393.png)

![image](https://user-images.githubusercontent.com/1296369/149194747-b352618e-726c-40f3-b473-72980134dfb9.png)

**Comment by richard67** [comment]
> Is the native cron referred to here the web cron?

I think it's a real (Unix) cron job running locally on an unixoid host.

**Comment by brianteeman** [comment]
I think it might be as well but no idea what the syntax would be for that.  Especially as there is still no help page

**Comment by richard67** [comment]
I think a real cron would use the CLI: `php cli/joomla.php scheduler:run` (without any arguments).

**Comment by brianteeman** [comment]
there must be arguments otherwise the cli would not know which task to run.

But do you see my point. There is no way for a user to know this stuff. Especially the way that lazy scheduling works with regards to intervals

**Comment by richard67** [comment]
I agree there should be some documentation.

**Comment by richard67** [comment]
> there must be arguments otherwise the cli would not know which task to run.

It could run all which are outstanding.

**Comment by PhilETaylor** [comment]
> there must be arguments otherwise the cli would not know which task to run.

No, that's the whole point of the component! It runs all jobs - based on the cron syntax of the task, the current time, and the last run time of that task. 

The `php cli/joomla.php scheduler:run` should be run every min of every day `* * * * *`

Then the component decides which jobs need running
