### ISSUE TITLE
[4.x] Atum Select style

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36661]
Atum has no styling for native select. I am assuming that the chromium useragent stylesheet has changed as it now results in this.

![chromium](https://user-images.githubusercontent.com/1296369/149198148-e87da81f-ecdd-4b1b-a095-a80489e42497.gif)

**Comment by dgrammatiko** [comment]
It needs to be fixed upstream (bs)

**Comment by C-Lodder** [comment]
Standard select dropdowns have very limited with styling options.
I believe you can only change the background and text colours.

Anything more, and you'll need to use that JS lib to replace the element completely.

**Comment by dgrammatiko** [comment]
TBH I don't have any issues on macOS for native select elements
![Screenshot 2022-01-13 at 15 34 27](https://user-images.githubusercontent.com/3889375/149349738-706bd129-5b7e-47fe-b65f-57428f40184c.png)

![Screenshot 2022-01-13 at 15 37 28](https://user-images.githubusercontent.com/3889375/149350259-44017870-6be0-4b9e-8b29-8e7efccf2f0a.png)


The Choices.js ones have the same rendering 
![Screenshot 2022-01-13 at 15 34 35](https://user-images.githubusercontent.com/3889375/149350388-979011cb-08fe-407b-827d-70fd22ac1e2b.png)

**Comment by C-Lodder** [comment]
Browsers use different styling for HTML select dropdowns.
If the objective of this issue is to have the same styling between native selects and Choice.js dropdown, then this simply isn't possible with CSS tweaks. Choices.js is going to have to be used throughout.

**Comment by dgrammatiko** [comment]
> Choices.js is going to have to be used throughout.

That would be awkward and will considerably slow down things. Obviously, I'm against replacing native elements with some random JS created alternatives. Yes, I'm that JS guy saying don't use JS if the native element fulfils the requirements...

**Comment by Quy** [comment]
Duplicate #31889?

**Comment by brianteeman** [comment]
Closed as a duplicate
