### ISSUE TITLE
[4.0] custom fields of type media disappear when switching article to different category

### ISSUE THREAD

**Issue by superknutsel** [joomla/joomla-cms#36668]
### Steps to reproduce the issue

- Create a custom field of the type media, assign to all categories
- Create an article and fill in the custom field with an image and save the article
- Change the categorie to a different one and check the tab with the custom field. It should be gone until you hit save. Then the field will be back but empty.

### Expected result
I would expect the fields not to disappear and keep their content.

### Actual result
Now after moving an article to a different categorie your custom fields are empty, probably because they had some sort of "reset".

### System information (as much as possible)
Joomla 4.0.5
PHP 8.0.14
MySQL 8.0.27

**Comment by drmenzelit** [comment]
I can confirm the issue

**Comment by alikon** [comment]
fixed by #36736
