### ISSUE TITLE
[4.0]Inconsistency in MediaHelper::canUpload

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#36674]
### Steps to reproduce the issue
Code review of libraries/src/Helper/MediaHelper.php lines 243 - 252

```
		// Media file names should never have executable extensions buried in them.
		$executables = array_merge(self::EXECUTABLES, InputFilter::FORBIDDEN_FILE_EXTENSIONS);

		// Remove allowed executables from array
		if (count($allowedExecutables))
		{
			$executable = array_diff($executables, $allowedExecutables);
		}

		$check = array_intersect($filetypes, $executables);
```
Line 249 should be:
```
			$executables = array_diff($executables, $allowedExecutables);
```
### Additional comments
Compare the above to MediaHelper::checkFileExtension in lines 177 to 183:
```
		// Remove allowed executables from array
		if (count($allowedExecutables))
		{
			$executables = array_diff($executables, $allowedExecutables);
		}

		if (in_array($extension, $executables, true))
```

**Comment by richard67** [comment]
> Line 249 should be:
> `$executables = array_diff($executables, $allowedExecutables);`

From reading code I'd say you are right.

**Comment by akshitrattan** [comment]
after going through the entire file I too think that line 249 should be changed
However, when I upload a restricted file type( E.g.- I tried uploading an SVG image, which is a restricted file type), considering this code snippet, I should not get an error, but I still get an error that I can't upload the file type
Can anyone explain to me why this happens?

**Comment by brianteeman** [comment]
@akshitrattan restricted file type and executable files are completely different things

**Comment by akshitrattan** [comment]
> @akshitrattan restricted file type and executable files are completely different things

oh, so as in a file like .exe??

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/blob/65aaacc28cddfed55804306eb02b407d28884159/libraries/src/Helper/MediaHelper.php#L28-L40

**Comment by akshitrattan** [comment]
> https://github.com/joomla/joomla-cms/blob/65aaacc28cddfed55804306eb02b407d28884159/libraries/src/Helper/MediaHelper.php#L28-L40

thanks a lot, now I'm familiar with the exact meaning of the term

**Comment by richard67** [comment]
Who wants to make a pull request to fix that? I think the main challenge is to find good testing instructions for a real human test. As far as I can see there are no unit tests for the media helper yet, so I think it needs some kind of human test to make sure nothing is broken.

**Comment by akshitrattan** [comment]
> Who wants to make a pull request to fix that? I think the main challenge is to find good testing instructions for a real human test. As far as I can see there are no unit tests for the media helper yet, so I think it needs some kind of human test to make sure nothing is broken.

i'll make a PR

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36695 . Thanks in advance.
