### ISSUE TITLE
[4.1] com_scheduler checked out and locked

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36676]
In the actions dropdown for tasks you will find an unlock option but not a checkin. They are not the same thing.

Checkin is the usual check to see if the record is open elsewhere (checked out)
Unlock appears to be when the item is running

The codebase does checkout a record when it is open. But there is no code to display that it is checkedout and no option to check it back in.

This will create issues like this where there is no indication the record is checked out but you get the error message when trying to open the task (as an admin) and there is no obvious way for a superadmin to resolve this.

## Admin User
![image](https://user-images.githubusercontent.com/1296369/149488419-d9ee8034-7091-40bf-a4f2-a5bd3745d337.png)

## Super Admin User
![image](https://user-images.githubusercontent.com/1296369/149488530-5a8a9981-1cac-4b67-8309-87ed95750a92.png)

PS Is it correct that any user can unlock a task?

**Comment by heelc29** [comment]
In addition, when the task is closed (or saved&closed), the values for `checked_out` and `checked_out_time` are also not correctly reset to `NULL`. This is indicated in _Maintenance: Global Check-in_.

![image](https://user-images.githubusercontent.com/66922325/151415507-5a1fdc24-a281-4fee-9c31-f19f79fbae47.png)
![image](https://user-images.githubusercontent.com/66922325/151415794-04041212-9bc5-41ef-8ddb-2cc8c132c4fd.png)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36875 . Thanks in advance.
