### ISSUE TITLE
[4.1] Module "Show full description ..." Link doesn't work

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#36670]
### Steps to reproduce the issue
* Create/Edit eg the site module "Articles - Related"
* Click the link "Show full description ..."
![image](https://user-images.githubusercontent.com/1018684/149364130-f803acd3-ceea-48f3-b47e-4c19f2260319.png)

### Expected result
The "Description" tab should activate

### Actual result
Nothing happens.
Dev Console shows an error:
![image](https://user-images.githubusercontent.com/1018684/149364213-c5dcfa25-3a9b-4c15-8037-c69f45f8a445.png)

### System information (as much as possible)
Tested on 4.1-dev nightly from today (2022-01-13)

### Additional comments
The JavaScript looks for the tab with the ID `tab-description` (`document.querySelector('#tab-description').click();`), but the tab has no ID at all.
So either the JavaScript needs to be fixed to activate the tab correctly or the tab needs an ID.

**Comment by dgrammatiko** [comment]
```js
document.getElementById('myTab').activateTab(1); // 1 is the second tab, array based

// OR

document.getElementById('myTab').activateTab(document.getElementById('description'))

// The activateTab accepts an event, HTMLElement (the tab's content element) or an integer as the index of the array of the tabs. Pick your poison...
````

**Comment by Bakual** [comment]
I'm not sure if we can be certain that the "Description" is always the second tab. So the first variant sounds a bit to fragil to me. And the second variant needs an ID on the tab, which doesn't exist 😄

**Comment by dgrammatiko** [comment]
Both are working, I've tested them because I don't know all the methods off the top of my head...
The tab content for the `description` has an ID `description`

**Comment by Bakual** [comment]
Ah, then please can you do the PR? Thanks.

**Comment by dgrammatiko** [comment]
@Bakual #36683

**Comment by alikon** [comment]
closing as we have a pr #36683
