### ISSUE TITLE
[4.1] com_scheduler run/test task permissions

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36677]
### Steps to reproduce the issue
Create a task eg image size and check that it will run successfully when clicking on the run/test task button

Log back in as an admin level user and try to  clicking on the run/test task button

### Expected result
At first I expected the task to run successfully but then I saw in the permissions that by default an admin user does not have permission to do that.

So I would expect a disabled button and/or a meaningful error message

### Actual result
the button is not disabled and the message is not helpful

![image](https://user-images.githubusercontent.com/1296369/149489338-aefffb66-301b-400e-8fa1-e9825651ad02.png)

### Comment
~When the button was labelled "Test Task" then the permission restricting it to admin users made sense
Now the button etc is being relabelled as "Run Task" the restriction is more debatable~

**Update**
Just realised that even if it was labelled "Test Task" then a user should at a minimum be able to test the task that they created.

**Comment by PhilETaylor** [comment]
@ditsuke

**Comment by ditsuke** [comment]
On it!

**Comment by brianteeman** [comment]
closed as there is a draft pr
