### ISSUE TITLE
Drag and drop an image with TinyMCE uses thumb path

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#36686]
### Steps to reproduce the issue
Drag and drop an image with TinyMCE in an article description.

### Expected result
The real url of the image is used.

### Actual result
The thumb url of the image is used.

### System information (as much as possible)
Joomla 4

### Additional comments
The code is here https://github.com/joomla/joomla-cms/blob/4.0-dev/build/media_source/plg_editors_tinymce/js/plugins/dragdrop/plugin.es5.js#L52-L60.

ping @dgrammatiko any feedback before I will do a pr why it is like that?

**Comment by dgrammatiko** [comment]
Line 59 should be

```js
urlPath = response.data.url;
```

or something along this line. BTW the same (wrong, blame me here) code exists in the select-media.es6.js

**Comment by laoneo** [comment]
Problem is that the ajax response doesn't contain the url. But if you agree that it should be .url, then I will do a pr.

**Comment by laoneo** [comment]
> BTW the same (wrong, blame me here) code exists in the select-media.es6.js

Don't think so as there is a file request done with the url parameter.

**Comment by dgrammatiko** [comment]
> Problem is that the ajax response doesn't contain the url. But if you agree that it should be .url, then I will do a pr.

I think the problem is in the local adapter, somehow the URL is not set there and as a result, I had to use thumb_path. I observed the inconsistent behaviour on the thumbnails PR but didn't patch it yet. Probably I should (although I don't think that PR would make it to 4.1)

**Comment by laoneo** [comment]
Please test #36687.

**Comment by dgrammatiko** [comment]
Yes and no. I see the hardcoded part of the `local-` as a complete architecture failure. The `response.data.url` coming from the PHP should always be either the relative path (if local) or the external path. But maybe unrelated to the thumb part?

What I'm saying is that the conditional should be more like: does it start with `http || \\`? instead of the hardcoded part...

**Comment by laoneo** [comment]
This is handled in #36667.
