### ISSUE TITLE
[3.10.4] Module caching setting to "no caching" is ignored - always cached

### ISSUE THREAD

**Issue by sm0rgm** [joomla/joomla-cms#36680]
### Steps to reproduce the issue
Go to Global Settings -> Server -> Cache handler = File, System Cache = ON - progressive cache
Create a breadcrumb module, set Advanced -> Cache -> No caching
Visit different pages on the site. Notice that the breadcrumb is the same for all pages.
Go to System -> Clear cache
Now another breadcrumb is displayed but the same breadcrumb is displayed for all pages on the site.
Downgrade to 3.10.3 resolves the issue.

### Expected result
The correct breadcrumb should be displayed for each page when Cache = No caching is set for the Breadcrumb module.

### Actual result
A cached version of the breadcrumbs, i.e. same breadcrumb, is displayed for all pages on the site.

### System information (as much as possible)
Joomla 3.10.4, PHP 7.4.25.

### Additional comments
Downgrading to 3.10.3 immediately resolves the issue.

**Comment by zero-24** [comment]
Hi, yes this is a known issue to be fixed by 3.10.5 next week can you please check the 3.10.5-rc1 ?

https://github.com/joomla/joomla-cms/releases/tag/3.10.5-rc1

**Comment by sm0rgm** [comment]
I've upgraded to 3.10.5-rc1 and the problem is resolved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36680">issues.joomla.org/tracker/joomla-cms/36680</a>.</sub>

**Comment by alikon** [comment]
please close the issue

**Comment by bellu** [comment]
Hi, i'm using the 3.10.14-elts version, and i've the same exact problem with mod_breadcrumbs. The no cache settings is ignored. Any suggestions? Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36680">issues.joomla.org/tracker/joomla-cms/36680</a>.</sub>

**Comment by sm0rgm** [comment]
Try setting **No caching** _and_ **Cache Time** to 0 on the module's Advanced tab.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36680">issues.joomla.org/tracker/joomla-cms/36680</a>.</sub>
