### ISSUE TITLE
cassiopeia 2 problems

### ISSUE THREAD

**Issue by lorenzo2022cazzo** [joomla/joomla-cms#36694]
2 problems translated from Italian with google
1 menu item "featured articles of all categories" set to 3 columns with navigation .... page 1 ok I see 3 columns but if  I click on page 2 .... 2 columns
2 I publish an article with an image .... I enter the article to read it .... the text is attached to the image .... need  to go to the css ... but put some space between the image and the text so as to help clumsy users ....

is it possible to hope for an update that solves it ??
or suggest me how to alter css (which file what to write ?)

**Comment by brianteeman** [comment]
I do not see the problem with the columns

## Menu Settings
![image](https://user-images.githubusercontent.com/1296369/149631145-12ac7110-de7d-46ec-8e98-79eed981ef0f.png)

## Page 1
![image](https://user-images.githubusercontent.com/1296369/149631155-92ef3206-6e32-4f73-b74b-6e5cf1b8e33d.png)

## Page 2
![image](https://user-images.githubusercontent.com/1296369/149631176-db94aefe-67e2-4544-a4fb-853704064ac5.png)

**Comment by brianteeman** [comment]
I am going to guess at why you are not seeing three columns on page 2. I hope google translate works for this.

The default is to set the direction of the columns down 

1| 4| 7|
-|---|---
2| 5| 8|
3|6|9

If the next page has less than 7 items you will only see two columns

10|13|
--|--
11|14
12| 15

The solution to that is to set the direction to across as you can see in my first screen shot
1|2|3
-|-|-
4|5|6
7|8|9

10|11|12
-|-|-
13|14|15

**Comment by lorenzo2022cazzo** [comment]
now it's okay .... many thanks _____    but look below ..

![immagine](https://user-images.githubusercontent.com/97790117/149657339-5653b4dc-2e5e-44e9-85e0-b08b2d3333e7.png)

but someone help me with this default crap - I put an "! important" if necessary but on which css file and what do I write? see image below text attached to image

![Immagine](https://user-images.githubusercontent.com/97790117/149657578-bbc4c4f3-55cc-4538-9d7a-5352bf09be19.png)

**Comment by ChristineWk** [comment]
You can make CSS changes etc. in a (previously created) user.css
Here some useful informations:https://cassiopeia.joomla.com/help<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36694">issues.joomla.org/tracker/joomla-cms/36694</a>.</sub>

**Comment by drmenzelit** [comment]
@lorenzo2022cazzo you need to add the class float-start for the image (directly on the article or in the global options for all articles)
Please close the issue if the explanations helped you.

**Comment by lorenzo2022cazzo** [comment]
funziona ..... evviva  grazie
