### ISSUE TITLE
[4.0] Custom URL field displays as "View website"

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#36697]
### Problem identified
In J3x a custom URL field displayed the actual URL on the front end. In J4x it displays 'view website'.

### Proposed solution
Revert to showing actual URL
Or make it a choice of one or the other
Or have the option of adding user-specified display text

### Open questions
Why was the display format changed?

**Comment by brianteeman** [comment]
Seek and ye shall find

![image](https://user-images.githubusercontent.com/1296369/149634079-d99e7461-0ec4-47b5-9301-00fc23a09afc.png)

**Comment by Scrabble96** [comment]
Ah yes. But it is already 'green' in my settings like you've shown. But it doesn't show on the front end.
This is, however, a website upgraded from J3.10x with pre-existing custom URL fields. Could that be the issue?

**Comment by brianteeman** [comment]
Try to resave the field.

**Comment by Scrabble96** [comment]
Yes, that worked. Thanks again.
