### ISSUE TITLE
[4.1] Post Installation Message

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36701]
Should we start to use the Post Installation Message to announce the major new features?

I fear that without it a user might not even notice that there are some cool new features in 4.1 and not just bug fixes

**Comment by dgrammatiko** [comment]
+1

**Comment by richard67** [comment]
Shouldn't this be a discussion and not an issue?

**Comment by PhilETaylor** [comment]
No we should not. 

Post Installation Messages are for important messages - not generic news. 

They are "important post-installation messages that require your attention" as the announcement in Joomla 3 says... this is not the place to announce new features. 

Overusing it for news/new features will lesson its impact when its used for important messages that require a users attention such as security changes they need to be aware of (XSS in SVG for .htaccess), or a change in a default setting that is b\c break (default text filter settings)
