### ISSUE TITLE
[4.1] Help pages

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36713]
In Order to generate the helpTOC.json correctly for 4.1 we need to run build/helpTOC.php

Currently the script fails because it cannot find the MINOR version as called here

https://github.com/joomla/joomla-cms/blob/79d8b8e209a540eaa394c3188fefc076b1dbea05/build/helpTOC.php#L92-L96

IIRC there is something that has to be done on help.joomla.org to facilitate this but I neither have access nor remember exactly

@bakual @bembelimen 

PS this always gets forgotten when we release a new minor version and should be documented and even better be automated

**Comment by brianteeman** [comment]
Without this administrator/index.php?option=com_admin&view=help will only ever show the 4.0 help files

**Comment by brianteeman** [comment]
PPS this was not done correctly for 4.0 which is why there is no entry for workflows

**Comment by brianteeman** [comment]
I really dont understand why this has been moved to 4.1.1

The idea of launching 4.1 with new components and not having them in the help pages makes no sense to me

**Comment by wilsonge** [comment]
As far as I can see the only thing required is to go through each page, review and if good then add the category to the page (you can use the quick add at the bottom - add to the Help screen 4.1/Help screen 4.2 categories

**Comment by brianteeman** [comment]
great 100 pages to check - working on it.

**Comment by brianteeman** [comment]
see #38194
