### ISSUE TITLE
Debug plugin outputs errors in DataFormatter

### ISSUE THREAD

**Issue by beat** [joomla/joomla-cms#36716]
### Steps to reproduce the issue

Reported by Kunena team: When Kunena and CB are installed and debug is enabled, and as reported by Kunena "to reproduce the issue you need to enable the CB integration plugin into Kunena. You need to have too the debug and debug enabled into Joomla! configuration."

### Expected result

Normal page.

### Actual result

`PHP Warning: Undefined array key 0 in C:\Users\flo\git\joomla-cms-40-dev\plugins\system\debug\src\DataFormatter.php on line 79`

### System information (as much as possible)

Joomla 4.0.6-dev

### Additional comments

The bug is obvious and could be merged on source-code review.

**Comment by brianteeman** [comment]
@beat you do not need to create an issue if you are creating a pull request at the same time. Please close this

**Comment by richard67** [comment]
Closing as there is a pull request to fix it.

**Comment by beat** [comment]
There was another PHP Warning reported by Kunena team in this bug:

PHP Warning: Undefined array key 0 in plugins\system\debug\src\DataFormatter.php on line 

@brianteeman Oki, not reporting issue then. However, how do we list fixed bugs in PRs if there is no issue ?

**Comment by brianteeman** [comment]
you dont - that info is only needed when you are fixing an existing issue - perhaps created by someone else
