### ISSUE TITLE
No ability to logout user from the backend.

### ISSUE THREAD

**Issue by sjb1963** [joomla/joomla-cms#36720]
### Steps to reproduce the issue
Install Joomla 4.
Create a basic user.
Login to the website from the font end.
Review backend. User shows up

### Expected result
Just like in Joomla 3.x, I should be able to log out a user from the backend.

### Actual result
This doesn't even exists at all.

### System information (as much as possible)
Joomla 4.0.5

**Comment by brianteeman** [comment]
can  not replicate this

![image](https://user-images.githubusercontent.com/1296369/149806851-f3004a74-6349-4cfb-96fa-ef1a57fc8951.png)

**Comment by sjb1963** [comment]
This is not what I have. Sorry. I have everything except anything at all under the "location" column.

**Comment by sjb1963** [comment]
![image](https://user-images.githubusercontent.com/48100518/149808890-25afb797-f6a0-453e-b505-371ecdcda34b.png)

**Comment by brianteeman** [comment]
ah - do you have this option enabled

![image](https://user-images.githubusercontent.com/1296369/149808834-a51d0b7e-b93b-46d3-9a2b-29342c0c1946.png)

**Comment by sjb1963** [comment]
I have both of those options enabled.

**Comment by brianteeman** [comment]
and if you set it to shared sessions - no?

**Comment by Quy** [comment]
See PR #35732

**Comment by brianteeman** [comment]
@quy what does that have to do with it?

**Comment by Quy** [comment]
It fixes #35500 which is a duplicate of this issue.

**Comment by brianteeman** [comment]
Sorry I understand now. Its not a duplicate but I can see why you might think it was

**Comment by brianteeman** [comment]
@sjb1963 I can't remember the exact reasoning but if you have shared sessions enabled then the logout button is not available

**Comment by Quy** [comment]
It is a duplicate. Please see screenshots in both issues. They don't have values under the Location column because client_id is null, Here is the code:

```
					<?php if ($user->client_id === null) : ?>
						<?php // Don't display a client ?>
					<?php elseif ($user->client_id) : ?>
						<?php echo Text::_('JADMINISTRATION'); ?>
					<?php else : ?>
						<form action="<?php echo $user->logoutLink; ?>" method="post" name="adminForm">
							<?php echo Text::_('JSITE'); ?>
							<button type="submit" class="me-2 btn btn-danger btn-sm">
								<?php echo Text::_('JLOGOUT'); ?>
							</button>
						</form>
					<?php endif; ?>
```

**Comment by brianteeman** [comment]
not arguing - the issues are different. This issue is about not having a logout button. That issue is about the location being empty. That PR will resolve the column being empty but will have no impact on the logout button

**Comment by Quy** [comment]
Please read the code. If client_id is null, display nothing and don't display the logout button.

**Comment by brianteeman** [comment]
Your not listening - I give up!!

**Comment by sjb1963** [comment]
Kind of completely invalidates the usefulness of "shared sessions" if you ask me.
Why screw with something that was working fine? To make it look and act even MORE like Wordpress?

**Comment by brianteeman** [comment]
Shared sessions is just a way to have you logged in on the frontend when you are logged in to the admin. Thats all. It is NOT enabled by default. It's something that some people will find useful but not all.

**Comment by Quy** [comment]
Sorry, I understand your point now. I am trying to explain why the Login button won't display under Shared Session.

shared = nothing
1 = Administration
0 = Site + login button

**Comment by brianteeman** [comment]
I understood why ;)

**Comment by brianteeman** [comment]
@quy I understand the code why the logout button doesnt appear I am just wondering why it has been setup this way as this limitation was not present in j3. My apologies to @sjb1963 for not checking that - I thought shared sessions was new to j4

**Comment by sjb1963** [comment]
So, if it's true then that "Shared Sessions" serves no other useful purpose than to allow a person with the proper rights to login to the back end and "share" that login with the front end - if that is true, then...

Wouldn't it be safe to say there is an issue with the display of the "logout" button that has nothing to do with shared sessions?

**Comment by richard67** [comment]
> Kind of completely invalidates the usefulness of "shared sessions" if you ask me.

@sjb1963 What is the use of shared sessions for you, and why do you want to be able to force logout a user in a shared session who might currently be logged in in backend?

To me it seems that you just insist in this issue to be an issue because you don't want to change your opinion, regardless of any explanations or reasons.

> To make it look and act even MORE like Wordpress?

What does that issue here have to do with look and act of Wordpress? This sentence is just an unrelated rant ... kind of troll behaviour in my opinion.

**Comment by sjb1963** [comment]
As I have repeatedly stated, I want the ability to log a user off of the front end, from the back end - just like in Joomla 3.x, and not be told it's a "feature".

This was a very simple question to which you @richard67 have not contributed one useful insight or solution.

Call me a troll if you like - I.do.not.care.

**Comment by richard67** [comment]
> As I have repeatedly stated, I want the ability to log a user off of the front end, from the back end - just like in Joomla 3.x, and not be told it's a "feature".

@sjb1963 Switch off the shared sessions option and you can do that as you like.

So what’s your problem?

**Comment by sjb1963** [comment]
Look up Richard. Read what was written before you. I'm not going to justify a single thing to you about why I want to use a single feature of Joomla, or how I use it.

This is a bug. I have reported it that way. Its clear from what has been said that this is not the way it should work.
Unless you are actively trying to solve this issue, please refrain from actually BEING a troll on my post. Thank you.

**Comment by HLeithner** [comment]
Hello @sjb1963,

first of all thanks for reporting this issue and tbh honest using a rude language doesn't help much. Any way the behavior change is actually a security measure to be consistent with the behavior that you can't log out users from the backend.
The reason for this that nobody should be able to logout a super user (not even another super user).

Never the less this behavior can be improved. We found 2 possible solutions.
1. Cheap way, we could check if the user has only frontend permissions and add the logout button
2. More solid way, check if the active user has com_users.manage permissions and the user that should be logout is not a super user. (this could be drive more further to check if the active user has a higher permission level then the "bad" user, but I think that's not needed)

Any way now we need one who is interested to implement this feature.

**Comment by brianteeman** [comment]
@HLeithner wont this lead to confusion where only some users are listed with a logout button?

**Comment by HLeithner** [comment]
per default only super users wouldn't have a logout but and only super users can see the logout button... but yeah an info on docs  (or somewhere else) would make sense why you can't logout a super user. Maybe there is already a docs entry?

**Comment by sjb1963** [comment]
This was a very simple issue about ADMINISTRATION.

AN ADMINISTRATOR SHOULD BE ABLE TO LOG A USER OUT FROM THE BACKEND.
**Basic Administrative functionality.**

That's all. **Nothing else.** This post was not about ANYTHING else.

STILL NO SOLUTION.

I have REASON to be pissed off.

I've had people who didn't even know this feature was IN Joomla 3 - let alone in Joomla 4 - commenting, people who don't even bother to verify the question and post their arrogant and presumptuous answers here, apparently because they need to post on everything to maintain their sense of relevance, or scan for opportunities to try to assert their "virtual" moral superiority; others who didn't bother to try to understand the question, and then those who intentionally derail the question:  linking it to things that aren't even relevant (like shared sessions).

This functionality existed on Joomla 3 for years flawlessly - it doesn't work/not there on Joomla 4. This is not an improvement.

**Comment by richard67** [comment]
> ... and post their arrogant and presumptuous answers here, apparently because they need to post on everything to maintain their sense of relevance, ...

@sjb1963 Just for the records in case if you later delete your post as a proof that is was you who started to offend people here and so violate the code of conduct.

**Comment by sjb1963** [comment]
And Still the issue goes unresolved.

**Comment by richard67** [comment]
If users offend contributors who spend their free time without payment for Joomla so they stop to contribute so there are too few contributors at the end because it is not fun being offended, you should not expect issues to be solved quickly.

**Comment by sjb1963** [comment]
That's right, this is MY fault.

Thank you for making my point.

**Comment by Fedik** [comment]
I closing it as expected behavior for Joomla 4 when Shared session is enabled.
If you want to be able to force Site User to logout, please disable shared session.

**Comment by sjb1963** [comment]
That's precisely why it's a bug. NOT a feature.

As explained earlier, "Shared Sessions" has nothing to do with it.

This is NOT the functionality it formerly had in Joomla 3.

STILL A BUG.

**Comment by rdeutz** [comment]
@sjb1963 I give you a week to think about your behaviour.
