### ISSUE TITLE
Internal Server Error 500

### ISSUE THREAD

**Issue by ipresencesa** [joomla/joomla-cms#36730]
### Steps to reproduce the issue
After updating to Joomla 4.0.6 I ran the site audit using an SEO tool.

### Expected result
All redirected URLs should be redirected to new URLs.
Example: https://www.allmaids.co.za/gardeners --> https://www.allmaids.co.za/domestic-placements/gardeners

### Actual result
Internal Server Error 500 on all on previously working redirects.

### System information (as much as possible)
Joomla 4.0.6 update.

**Comment by brianteeman** [comment]
that redirect is working for me

**Comment by richard67** [comment]
For me, too ... I clicked the first URL in the example and got redirected to the 2nd.

Maybe that SEO tool uses a user agent which is blocked by an .htaccess rule for blocking bad user agents, like it is created by certain tools, i.e. not the default from the htaccess.txt coming with Joomla?

But on the other hand, that should not return a 500.

Update: And it should not change with an update to 4.0.6.

@ipresencesa Does the redirect work for you when testing in the browser, not with the SEO tool? What kind of SEO tool is that?

**Comment by ipresencesa** [comment]
The SEO tool is working fine after I downgraded to 4.0.5

 

I found that it happens only with first level redirects. 

 

Example:

https://www.allmaids.co.za/gardening-services 

 

but not 

 

https://www.allmaids.co.za/domestic-services/gardening-services

 

I don’t understand which it works immediately after downgrading without changing anything.

 

I will try upgrading again and give an update.

**Comment by ipresencesa** [comment]
Nope, the tool and the browser give same errors.

 

Updating again gives same error 500.

**Comment by brianteeman** [comment]
and have you done what it tells you to do?

**Comment by richard67** [comment]
Besides documentation block changes I see no other changes in the code of com_redirect between 4.0.5 and 4.0.6 so I have no idea why that should change behaviour after an update.

**Comment by brianteeman** [comment]
> Besides documentation block changes I see no other changes in the code of com_redirect between 4.0.5 and 4.0.6 so I have no idea why that should change behaviour after an update.

But if you follow the instructions we will have a better idea

**Comment by richard67** [comment]
> > Besides documentation block changes I see no other changes in the code of com_redirect between 4.0.5 and 4.0.6 so I have no idea why that should change behaviour after an update.
> 
> But if you follow the instructions we will have a better idea

@brianteeman You mean me? If so, which instructions?

**Comment by brianteeman** [comment]
no I mean  @ipresencesa and the instructions on the 500 error page

**Comment by richard67** [comment]
I see ... https://docs.joomla.org/J4.x:FatalError

**Comment by ipresencesa** [comment]
The following is the output after Debug = true

 

Error

in  <https://www.allmaids.co.za/how-it-works> /home1/allmalvb/public_html/plugins/system/redirect/redirect.php (line 243)

238.                 // Always count redirect hits

239.                 $redirect->hits++;

240.  

241.                 try

242.                 {

243.                     $db->updateObject('#__redirect_links', $redirect, 'id');

244.                 }

245.                 catch (Exception $e)

246.                 {

247.                     // We don't log issues for now

248.                 }

in  <https://www.allmaids.co.za/how-it-works> /home1/allmalvb/public_html/libraries/vendor/joomla/event/src/Dispatcher.php -> handleError (line 486)

Dispatcher->dispatch('onError', object(ErrorEvent))in  <https://www.allmaids.co.za/how-it-works> /home1/allmalvb/public_html/libraries/src/Application/EventAware.php (line 111)

WebApplication->triggerEvent('onError', object(ErrorEvent))in  <https://www.allmaids.co.za/how-it-works> /home1/allmalvb/public_html/libraries/src/Application/CMSApplication.php (line 309)

CMSApplication->execute()in  <https://www.allmaids.co.za/how-it-works> /home1/allmalvb/public_html/includes/app.php (line 63)

require_once('/home1/allmalvb/public_html/includes/app.php')in  <https://www.allmaids.co.za/how-it-works> /home1/allmalvb/public_html/index.php (line 32)

**Comment by ipresencesa** [comment]
The extended output:

 

Error

in  <https://www.allmaids.co.za/how-it-works> /home1/allmalvb/public_html/plugins/system/redirect/redirect.php (line 243)

238.                 // Always count redirect hits

239.                 $redirect->hits++;

240.  

241.                 try

242.                 {

243.                     $db->updateObject('#__redirect_links', $redirect, 'id');

244.                 }

245.                 catch (Exception $e)

246.                 {

247.                     // We don't log issues for now

248.                 }

in  <https://www.allmaids.co.za/how-it-works> /home1/allmalvb/public_html/libraries/vendor/joomla/event/src/Dispatcher.php -> handleError (line 486)

481.                 if ($event->isStopped())

482.                 {

483.                     return $event;

484.                 }

485.  

486.                 $listener($event);

487.             }

488.         }

489.  

490.         return $event;

491.     }

Dispatcher->dispatch('onError', object(ErrorEvent))in  <https://www.allmaids.co.za/how-it-works> /home1/allmalvb/public_html/libraries/src/Application/EventAware.php (line 111)

106.         else

107.         {

108.             throw new \InvalidArgumentException('The arguments must either be an event or an array');

109.         }

110.  

111.         $result = $dispatcher->dispatch($eventName, $event);

112.  

113.         // TODO - There are still test cases where the result isn't defined, temporarily leave the isset check in place

114.         return !isset($result['result']) || \is_null($result['result']) ? [] : $result['result'];

115.     }

116. }

WebApplication->triggerEvent('onError', object(ErrorEvent))in  <https://www.allmaids.co.za/how-it-works> /home1/allmalvb/public_html/libraries/src/Application/CMSApplication.php (line 309)

304.                     'application' => $this,

305.                 ]

306.             );

307.  

308.             // Trigger the onError event.

309.             $this->triggerEvent('onError', $event);

310.  

311.             ExceptionHandler::handleException($event->getError());

312.         }

313.  

314.         // Send the application response.

CMSApplication->execute()in  <https://www.allmaids.co.za/how-it-works> /home1/allmalvb/public_html/includes/app.php (line 63)

58.    

59.   // Set the application as global app

60.   \Joomla\CMS\Factory::$application = $app;

61.    

62.   // Execute the application.

63.   $app->execute();

64.    

require_once('/home1/allmalvb/public_html/includes/app.php')in  <https://www.allmaids.co.za/how-it-works> /home1/allmalvb/public_html/index.php (line 32)

27.    * define() is used rather than "const" to not error for PHP 5.2 and lower

28.    */

29.   define('_JEXEC', 1);

30.    

31.   // Run the application - All executable code should be triggered through this file

32.   require_once dirname(__FILE__) . '/includes/app.php';

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36733 . Thanks in advance.

@ipresencesa Just apply the change of that PR on your 4.0.6 and check if it helps. If it does, please mark the test result in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/36733 by using the "Test this" button, selecting the appropriate test result and submitting. Thanks in advance.
