### ISSUE TITLE
[4.0] Com Redirect not working

### ISSUE THREAD

**Issue by mrownicki** [joomla/joomla-cms#36744]
Hi. Core extension redirect not working in J4.x

### Steps to reproduce the issue
Make redirect /custom to /exist-alias-url
simple redirect 301

### Expected result
redirect to /exist-alias-url

### Actual result
Error 500

Error:
Call to a member function updateObject() on null

  at nowa/plugins/system/redirect/redirect.php:243
  at PlgSystemRedirect->handleError(object(ErrorEvent))
     (nowa/libraries/vendor/joomla/event/src/Dispatcher.php:486)
  at Joomla\Event\Dispatcher->dispatch('onError', object(ErrorEvent))
     (nowa/libraries/src/Application/EventAware.php:111)
  at Joomla\CMS\Application\WebApplication->triggerEvent('onError', object(ErrorEvent))
     (nowa/libraries/src/Application/CMSApplication.php:309)
  at Joomla\CMS\Application\CMSApplication->execute()
     (nowa/includes/app.php:63)
  at require_once('/public_html/nowa/includes/app.php')
     (nowa/index.php:32)     

![screen shot 2022-01-19 at 14 39 34](https://issues.joomla.org/uploads/1/d8f746ff5d6cc4fcd0739d8f2a4f7461.png)
### System information (as much as possible)

Joomla migrated from 3.10.4 to Joomla 4.0.5 and update 4.0.6
PHP 7.4 
.Htaccess original
Test on Cassiopeia
DB is correct, no errors.
### Additional comments

I think that is an urgent problem.

**Comment by conseilgouz** [comment]
Please check https://github.com/joomla/joomla-cms/pull/36733

**Comment by richard67** [comment]
Closing as duplicate repost, see precious issue #36730 and pull request #36733 for the solution.

@mrownicki To solve the problem, apply the changes from that pull request. A FAQ document for 4.0.6 will be written soon.

**Comment by mrownicki** [comment]
@richard67 
Thank you! Great info! 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36744">issues.joomla.org/tracker/joomla-cms/36744</a>.</sub>
