### ISSUE TITLE
Update to Joomla 4.0.6 not possible

### ISSUE THREAD

**Issue by derMaxi** [joomla/joomla-cms#36755]
### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/45736810/150305437-3185faed-e01b-4061-beac-e5e10f63ae53.png)
Click on update.

### Expected result

Joomla should show the update and let me update.

### Actual result

![image](https://user-images.githubusercontent.com/45736810/150305663-46babdd8-6ca6-44f3-84f8-0c7752742595.png)

### System information (as much as possible)

Joomla! 4.0.5 Stable [ Furaha ] 11-December-2021 20:52 GMT
PHP 8.1.1
MySQL 5.5.68-MariaDB

**Comment by zero-24** [comment]
Please upgrade your mysql version mysql 5.5.68 is not supported for J4. The minimum is 5.6 ;-)

https://downloads.joomla.org/de/technical-requirements-de

**Comment by richard67** [comment]
And when that worked for you close this issue please. Thanks in advance.

**Comment by derMaxi** [comment]
Thanks! It works now.

**Comment by richard67** [comment]
Thanks for reporting back.
