### ISSUE TITLE
[4.0] Hits and ID columns disappear in Articles list view in Admin (Atum template)

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#36758]
### What needs to be fixed
Both the 'Hits' and 'ID' columns (th and td) have class ```d-lg-table-cell```. All the others have ```d-md-table-cell```
(In modules view, the 'ID' column has ```d-md-table-cell```)

### Why this should be fixed
When the screen is less than 992px wide these two columns disappear

### How would you fix it
Change ```d-lg-table-cell``` to ```d-md-table-cell```
Where, I have no idea, but I'm sure one of you will

### Side Effects expected
None that I can see

**Comment by richard67** [comment]
@brianteeman Do you remember if that was a deliberate decision? Or is that a mistake?

**Comment by brianteeman** [comment]
No idea but when the columns pr is merged it will be redundant

**Comment by pritam825** [comment]
https://github.com/joomla/joomla-cms/pull/36767
can you please test this?

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36767 . Thanks in advance.
