### ISSUE TITLE
Button fur submit batch process in administrator menus not existent

### ISSUE THREAD

**Issue by dieseitenwerkstatt** [joomla/joomla-cms#36760]
### Steps to reproduce the issue
**Create additional admin menu**
- switch to administrator/index.php?option=com_menus&view=menus
- switch to "Administrator" in top left
- Click New and create Menu

**create menu entries in the new menu**
- switch to menu entry editing: administrator/index.php?option=com_menus&view=items&menutype=NEWMENU
- add some entries in the newly created menu

**try to move entries with batch functionality**
- now select some of the new menu items and click on "Actions -> Batch"
- in the popup folder select an entry and choose to move or copy

### Expected result
Button Submit should be clickable to batch process the entries
See scrennshot also. In all other views there is a button at the marked place. Modal is useless without this button.

### Actual result
**submit button is missing, only cancel button is shown**

### System information (as much as possible)
every joomla4 version since release

**Comment by brianteeman** [comment]
~The submit button **is** present only when you have more than one admin menu. This is obviously wrong.~

Looking into this as it was my pr from 4 years ago

**Comment by Quy** [comment]
Closing as having a pull request. Please test #36762 . Thanks in advance.
