### ISSUE TITLE
[4.1] Scheduled Taks Help button instruction isn't useful

### ISSUE THREAD

**Issue by pritam825** [joomla/joomla-cms#36763]
### Steps to reproduce the issue

go to Scheduled Tasks click on help button

### Expected result
the content in the page after clicking the help button, should be useful and helpful

### Actual result
there isn't any helpful content in the page after clicking the help button

### Additional comments
if it won't be the part of issue then I will close this. 

![Screenshot (1904)](https://user-images.githubusercontent.com/54195688/150482384-5a4e9c38-b47d-480f-9a69-f743bb117b57.png)

**Comment by richard67** [comment]
@brianteeman Do I assume right that this issue here is a duplicate to your issue #36713 ?

**Comment by brianteeman** [comment]
No

**Comment by richard67** [comment]
It's a CMS issue or an issue with the help docs?

**Comment by brianteeman** [comment]
#36713 is a cms issue http://localhost/joomla-cms/administrator/index.php?option=com_admin&view=help

**Comment by richard67** [comment]
@brianteeman I mean this one here.

**Comment by brianteeman** [comment]
this one is a docs issue i believe

**Comment by richard67** [comment]
@brianteeman Just found your PR #36714 ... does that solve this issue here? To me it reads as if so.

**Comment by richard67** [comment]
.. Hmm, on a deeper look maybe not.

**Comment by pritam825** [comment]
Yes, this one is the docs issue

**Comment by tecpromotion** [comment]
> Yes, this one is the docs issue

May ping @coolwebcreations (Mike Brandner) and his team for help

**Comment by pritam825** [comment]
@tecpromotion thanks

**Comment by coolwebcreations** [comment]
The HELP pages are created. Please check, if issue is solved.

**Comment by Quy** [comment]
Confirmed help page has info. Thank you!

**Comment by pritam825** [comment]
@coolwebcreations thanks, sorry for the late response, actually I was ill, so I wasn't active in these days.
