### ISSUE TITLE
[4.0] Nested subforms

### ISSUE THREAD

**Issue by n3t** [joomla/joomla-cms#36779]
### Steps to reproduce the issue
- Install attached test plugin [plg_test.zip](https://github.com/joomla/joomla-cms/files/7917193/plg_test.zip) 
- go to Test plugin configuration, there is subform field called Test
- add 2 elements to this field
- it contains another subform field, ad some elements to it also
- drag the outer form element
- drag the inner form element

### Expected result
Outer elements could not be dropped inside inner form, inner elements could not be dropped outside its scope.

### Actual result
All elements (inner and outer) could be dropped anywhere
![subform1](https://user-images.githubusercontent.com/979699/150614718-fac84e51-3e19-4f7f-8f56-b472834f681a.gif)
![subform2](https://user-images.githubusercontent.com/979699/150614734-511d820d-e8af-40b4-a69b-d928b94e98ea.gif)

### System information (as much as possible)
Joomla 4.0.6

### Additional comments
Fields definition contains nested subform:

```
        <field name="test_outer" class="test1" type="subform" layout="joomla.form.field.subform.repeatable" multiple="true" label="Test outter" hiddenLabel="true">
          <form>
            <field name="test_inner" class="test2" type="subform" layout="joomla.form.field.subform.repeatable" hiddenLabel="true" multiple="true" label="Test Inner">
              <form>
                <field name="test_value" type="text" label="Test value" />
              </form>
            </field>
          </form>
        </field>
```

In `joomla-field-subform.js` file seems to be prepared some solution for this. It requires set `rows-container` attribute, which is not used in `joomla.form.field.subform.repeatable`. I tried to add there  `rows-container="joomla-field-subform"` and seems it solved dragging outer elements inside the inner form. But not dragging inner elements to outer form.

**Comment by Fedik** [comment]
I can confirm

**Comment by Fedik** [comment]
please test #36780
