### ISSUE TITLE
No Database in redirect system plugin

### ISSUE THREAD

**Issue by hsm-berlin** [joomla/joomla-cms#36781]
### Steps to reproduce the issue
I get the following error-message php-fpm-error:
[22-Jan-2022 09:59:48 Europe/Berlin] PHP Notice:  Undefined variable: db in .../www/plugins/system/redirect/redirect.php on line 243

redirect.php uses at line 243 the $db variable that was never initialized.

###Solution
use the class variable $this->db at line 243 fixes the error:
$this->db->updateObject('#__redirect_links', $redirect, 'id');

**Comment by richard67** [comment]
This has been fixed 4 days ago with PR #36733 . Closing.

**Comment by richard67** [comment]
See also https://docs.joomla.org/J3.x:Redirects_from_Redirect_system_plugin_(if_enabled)_cause_internal_server_errors_500 .
