### ISSUE TITLE
 Open_basedir warning on creating menu-item #35895 

### ISSUE THREAD

**Issue by hsm-berlin** [joomla/joomla-cms#36788]
### Steps to reproduce the issue
There is an open_basedir exception on line 1221 see:
[22-Jan-2022 15:44:57 Europe/Berlin] PHP Warning:  is_file(): open_basedir restriction in effect. File(/metadata.xml) is not within the allowed path(s): (...www:/tmp/) in ....www/administrator/components/com_menus/src/Model/ItemModel.php on line 1221

as reportet in the closed issue #35895 if you create an new MenuItem. 

### Expected result
/metadata.xml may not located at the root directory of the filesystem.

### System information (as much as possible)
Joomla 4.0.6 with Apache | PHP on CentOS 8

**Comment by ChristineWk** [comment]
Confirm the issue (see also closed one)
Hoster had a suggested solution, but I can't understand resp. comprehend it.
I don't know the right solution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36788">issues.joomla.org/tracker/joomla-cms/36788</a>.</sub>

**Comment by Fedik** [comment]
please test #36789 for Joomla 3

**Comment by Fedik** [comment]
and for Joomla 4 #36791

**Comment by richard67** [comment]
@hsm-berlin Could you test if the changes from pull request (PR) #36791 fix this issue for you and if so, report back in that PR? Thanks in advance.

**Comment by durian808** [comment]
I just discovered this on the site I'm working on, when attempting to add a new menu item.  I rebuilt menus, but error remains.

Joomla 3.10.5
PHP 7.4.27

**Error message:**
Warning: is_file(): open_basedir restriction in effect. File(/metadata.xml) is not within the allowed path(s): (/var/www/vhosts/mywebsite.org/:/tmp/) in /var/www/vhosts/mywebsite.org/httpdocs/new/administrator/components/com_menus/models/item.php on line 1153

I am now attempting to debug this. 

So far I've found that $base is empty in this code...

                    // Now check for a component manifest file
                    $path = JPath::clean($base . '/metadata.xml');
//jjj: debug
echo "base: [" . $base . "]<br />";
                    if (is_file($path))
                    {
                        $formFile = $path;
                    }
                }

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36788">issues.joomla.org/tracker/joomla-cms/36788</a>.</sub>
