### ISSUE TITLE
Getting "assets - No asset found for com_modules.module.90, falling back to com_modules" log entries at backend logout

### ISSUE THREAD

**Issue by phunsoft** [joomla/joomla-cms#36806]
### Steps to reproduce the issue
Log into Joomla! 4.0.4 or 4.0.6 backend.
Enable System Debug.
Log out.
Lock at the log entries.

### Expected result
No log entries at all.

### Actual result
The are two entries as follows:
`assets - No asset found for com_modules.module.90, falling back to com_modules (warning)`

### System information (as much as possible)
Joomla! 4.0.4 as well as 4.0.6
The runtime environment is XAMPP for Windows 8.0.10 with PHP 7.4, and Firefox (96.0.2) on Windows 10

### Additional comments
I'm not sure it the messages indicate a problem, but would not expect any warning level messages in release code.

**Comment by richard67** [comment]
For new installations this has been fixed already with 4.0.6 here: #36481 .

In updates we can't fix that, but you can go into the module manager in backend, change from site to admin and the search for a module named "Login Support" in an English Backend. If found, edit the options of that module and just save without making changes. This should created the missing record in the assets table.

@phunsoft Please check and report back if that helps, and if so, the issue can be closed.

**Comment by phunsoft** [comment]
@richard67 Thanks for the quick reply. I testet your fix instructions and can confirm that the log messages are gone.

**Comment by richard67** [comment]
Thanks for reporting back.
