### ISSUE TITLE
Tags pagination not working after upgrading from Joomla 3.10 to 4.0

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#36837]
### Steps to reproduce the issue
- upgrade site from Joomla 3.10 to 4.0. 
- in front-end click on a tag to open the list of articles for that tag.  
- go to another page number of the list of articles for the selected tag.

### Expected result
continuation of the list of articles for the selected tag

### Actual result
Error 404. View not found [name, type, prefix]: tagname, html, site

**Comment by joomdonation** [comment]
It is a known bug. See https://github.com/joomla/joomla-cms/issues/35382#issuecomment-906477897 for a workaround until we can fix this bug.

**Comment by richard67** [comment]
@joomdonation Is this a duplicate report to #35382 ?

**Comment by pritam825** [comment]
For me, it' looks like totally same as #35382

**Comment by joomdonation** [comment]
@richard67 Yes, it is the same issue. Closing as this is a duplicate issue.
