### ISSUE TITLE
[4.1] remove fof from code comments

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36838]
One for you @PhilETaylor 

starts here
https://github.com/joomla/joomla-cms/blob/360409f51cd81de6ca302ee3a51e718f26d3fa7b/administrator/components/com_postinstall/src/Model/MessagesModel.php#L443-L447

**Comment by pritam825** [comment]
can I remove FOFModel code comments, if you allow me.

**Comment by shagungarg0** [comment]
is this issue only related to remove fof lines from comments?

**Comment by brianteeman** [comment]
It means that the code comments need to be updated so that they are correct

**Comment by joomdonation** [comment]
@brianteeman Are you interested to make the PR to correct the comment? We can replace the mentioned code with the new code below:

```php
Factory::getApplication()->bootComponent('com_postinstall')
->getMVCFactory()->createModel('Messages', 'Administrator', ['ignore_request' => true])
->addPostInstallationMessage($options);
```

Thanks !

**Comment by Hackwar** [comment]
I created a PR in #39214. Closing this issue.

**Comment by brianteeman** [comment]
thanks
