### ISSUE TITLE
COM_CONFIG_FIELD_TEMP_PATH_DESC 

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#36847]
### Steps to reproduce the issue
COM_CONFIG_FIELD_TEMP_PATH_DESC
Content is: Joomla needs to temporarily store some files to perform actions such as installing / updating extensions or uploading files. Enter the absolute path of a directory that is writeable be PHP. <em>Do not</em> use the system–wide temporary folder (e.g. <code>/tmp</code>) for security reasons.
**writeable be PHP** must be **writeable by PHP**

**Comment by brianteeman** [comment]
confirmed. will you please make a pull request to fix it.

**Comment by richard67** [comment]
Closing as having a pull request. Thanks for reporting the issue.
