### ISSUE TITLE
[J4] BLOG_SAMPLEDATA_CONTENT_ARTICLE_4_INTROTEXT plg_sampledata_blog.ini

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#36851]
### Steps to reproduce the issue
Install J4 with blog sample data.
compare the description of the article 4 with the Joomla administrator side

### Expected result
the name of the module match the description

### Actual result
Actual text:
`<p>Your site has some commonly used modules already preconfigured. These include:</p><ul><li>Image Module which holds the image beneath the menu. This is a Custom module that you can edit to change the image.</li><li>Most Read Posts which lists articles based on the number of times they have been read.</li><li>Older Articles which lists out articles by month.</li><li>Syndicate which allows your readers to read your posts in a news reader.</li><li>Popular Tags, which will appear if you use tagging on your articles. Enter a tag in the Tags field when editing.</li></ul><p>Each of these modules has many options which you can experiment with in the Module Manager in your site Administrator. When you are logged in you can also select the edit icon in the top right corner which will take you to an edit screen for that module. Always be sure to save and close any module you edit.</p><p>Joomla! also includes many other modules you can incorporate in your site. As you develop your site you may want to add more modules that you can find at the <a href='https://extensions.joomla.org/'>Joomla Extensions Directory.</a></p>`

So the module is:
- Image
- Most Read Posts
- Older Articles
- Syndicate
- Popular Tags

But we have:
![image](https://user-images.githubusercontent.com/906604/151067788-2a49e3f5-ba32-4be7-acac-015047f951f7.png)

we need to make the article consistent with J4

### System information (as much as possible)
file: [plg_sampledata_blog.ini](https://github.com/joomla/joomla-cms/blob/4.1-dev/administrator/language/en-GB/plg_sampledata_blog.ini) text constant: PLG_SAMPLEDATA_BLOG_SAMPLEDATA_CONTENT_ARTICLE_4_INTROTEXT

**Comment by richard67** [comment]
The text says „These include …“ at the very beginning and so makes perfectly clear that it is not a complete list of all possible modules but a list with often used examples.

Making the text describe all possible modules would make it so long that nobody will read it. We have the help pages for that purpose, telling which kinds of modules are available.

So this issue here should be closed in my opinion.

**Comment by richard67** [comment]
Well maybe I misunderstood at first reading. If the module names in that text shall be made consistent with the module names in the module manager it might be ok. I only think the text should not be extended to describe all modules.

**Comment by Razzo1987** [comment]
No, the idea is only to have the correct name of the module.
And where is **Most Read Posts**? If we have removed we need to also remove from the article text.

**Comment by chmst** [comment]
It is not removed, it only is not activated in your list. Look here: Articles - most read is what you are missing. 

![grafik](https://user-images.githubusercontent.com/1035262/151075135-f8e10bad-16d1-4810-b9b2-2c9a7350086c.png)

**Comment by Razzo1987** [comment]
@chmst yes, I know (I use it in one of my J4 installation ;-) ). but the article say which modules have been configured in the SITE side: `Your site has some commonly used modules already preconfigured. [...]`.

In my opinion, it might be a good idea to have both names in the article (that of the configured module (**Title**) and that of the module **Type**).

I'll try to write the text by this evening to get an idea of what it would look like

**Comment by Razzo1987** [comment]
Old Article:
![image](https://user-images.githubusercontent.com/906604/151125113-121d6291-e3a7-4d9a-a7a1-7812c14f3285.png)

NEW Article:
![image](https://user-images.githubusercontent.com/906604/151171306-f554d6e8-7954-454e-b254-8d3eb7904fa5.png)
(edit: there is a double bot in the image, I have fixed it in the text below)

If you agree with the proposal I can create the PR.

The new text of the language value is:
`<p>Your site has some commonly used modules already preconfigured. These include:</p><ul><li>Image (type: Custom), which holds the image beneath the menu. This is a Custom module that you can edit to change the image.</li><li>Popular Tags (type: Tags - Popular), which will appear if you use tagging on your articles. Enter a tag in the Tags field when editing.</li><li>Older Posts (type: Articles - Category), which lists out articles by categories.</li><li>Syndication (type: Syndication Feeds), which allows your readers to read your posts in a news reader.</li><li>Login Form (type: Login), which allows your users to access the website.</li></ul><p>Each of these modules has many options which you can experiment with in the Module Manager in your site Administrator. When you are logged in you can also select the edit icon in the top right corner which will take you to an edit screen for that module. Always be sure to save and close any module you edit.</p><p>Joomla! also includes many other modules you can incorporate in your site. As you develop your site you may want to add more modules that you can find at the <a href="https://extensions.joomla.org/">Joomla Extensions Directory.</a></p>`

**Comment by brianteeman** [comment]
makes sense to me

**Comment by richard67** [comment]
Agree.

**Comment by richard67** [comment]
Closing as having a pull request.
