### ISSUE TITLE
Alias already existed so a number was added at the end but instead adding of number it's increasing the year

### ISSUE THREAD

**Issue by pritam825** [joomla/joomla-cms#36850]
### Steps to reproduce the issue

go to article-> create more than one articles with the same name

### Expected result

if the article already exist with the same name then it will add the number instead of increasing year

### Actual result

![Screenshot (1960)](https://user-images.githubusercontent.com/54195688/151054498-cccb06a5-f1b6-406a-8e9c-1a08231d2e55.png)

### Additional comments
@richard67 if you allow then I can add time , just below the date, otherwise not.
and if this is not an issue mentioned above then I will close this, sorry for disturbing you and Thanks in advance .

**Comment by richard67** [comment]
I do not understand. What should the year be increased in the title? How shall Joomla know what you put into your title, a year or a time or any arbitrary number, and which rule you want it to use to increase? It really depends on what you do with your title. One may have a year in it and wants to increase it, and another wants it not to be increased.

**Comment by pritam825** [comment]
sorry for my issues, which was not an issues, Now I understood completely from your above message how it's working, sorry for taking your time, Thanks a lot for helping me.
and the last thing I had to ask, sorry for this, is underlined necessary for the title, for example when I will create the article with article name "Thank_You" then "_" will get collapse with underlined, Thanks a lot in advance

**Comment by richard67** [comment]
@pritam825 Lonks are underlined for accessibility. It shall be visible not only by the colour that a link is a link.

**Comment by richard67** [comment]
Closing as expected behavior.

**Comment by pritam825** [comment]
> 

Ok sir thanks and sorry for taking your precious time
