### ISSUE TITLE
Redirects '500' error Joomla 4.

### ISSUE THREAD

**Issue by Hans-63** [joomla/joomla-cms#36856]
### Steps to reproduce the issue
To redirect non-existing urls on my Joomla sites to a logical, existing url on my site I use (like many) the redirects plugin.
It worked fine until a while ago.
Today I got a notification from google that some pages are not available.
When you go to the url you get a (joomla) orange screen with an error message: Sorry, there was a problem we could not fix.
The server returned a "500 - Whoops, looks like something went wrong."

### Expected result

Redirect to correct page / url on site...
When I look up the url in the redirects list it is in there and the referring url is correct.....
Removing the url from the list results in a 404-error page as you would expect.

### Actual result

After adding the url again with a url of an existing page on the site the orange error page appears again.

Expired url: https://htm63.com/av-t-en-francais/contactez-av-transaction
new url : https://www.htm63.com/en-francais/contactez-moi

I have looked at and tried everything, but I can't get it to work.... Who knows how to get it to work again?

### System information (as much as possible)
System:
Setting	Value
PHP Built On	Linux dh29280.eatserver.nl 3.10.0-962.3.2.lve1.5.61.el7.x86_64 #1 SMP Wed Aug 18 07:50:15 UTC 2021 x86_64
Database Type	mysql
Database Version	10.5.13-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	No
PHP Version	7.4.27
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 4.0.6 Stable [ Furaha ] 15-January-2022 17:06 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36

PHP:
Setting	Value
Upload Max Filesize	32M
Post Max Size	32M
Memory Limit	128M
Open basedir	/var/www/vhosts/htm63.com/:/tmp/
Display Errors	Off
Short Open Tags	On
File Uploads	On
Output Buffering	On
Session Save Path	/var/lib/php/session
Session Auto Start	0
XML Enabled	Yes
Zlib Enabled	Yes
Native ZIP Enabled	Yes
Disabled Functions	opcache_get_status
Multibyte String (mbstring) Enabled	Yes
GD Available	Yes
iconv Available	Yes
intl Available	Yes
Maximum Input Variables	1000

Config file:
Setting	Value
offline	false
offline_message	Deze site is niet beschikbaar wegens onderhoud.<br />Probeer het later nog eens.
display_offline_message	1
offline_image	
sitename	iad France - Région d'Ambert - Livradois-Forez
editor	jce
captcha	recaptcha_invisible
list_limit	20
access	1
debug	false
debug_lang	false
debug_lang_const	true
dbtype	mysqli
host	xxxxxx
user	xxxxxx
password	xxxxxx
db	htmu
dbprefix	htm4_
dbencryption	0
dbsslverifyservercert	false
dbsslkey	
dbsslcert	
dbsslca	
dbsslcipher	
force_ssl	2
live_site	
secret	xxxxxx
gzip	false
error_reporting	default
helpurl	https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}
offset	UTC
mailonline	true
mailer	mail
mailfrom	hans@htm63.com
fromname	IAD Region Ambert Livradois-Forez France (HTM)
sendmail	/usr/sbin/sendmail
smtpauth	false
smtpuser	xxxxxx
smtppass	xxxxxx
smtphost	localhost
smtpsecure	none
smtpport	25
caching	0
cache_handler	file
cachetime	15
cache_platformprefix	false
MetaDesc	Site de Hans KETTING pour iad France (Auvergne, france), Conseiller en immobilier avec des maisons dans la région d'Ambert (63600) dans le Livrados-Forez
MetaAuthor	true
MetaVersion	true
robots	
sef	true
sef_rewrite	true
sef_suffix	true
unicodeslugs	true
feed_limit	10
feed_email	none
log_path	/var/www/vhosts/htm63.com/httpdocs/administrator/logs
tmp_path	/var/www/vhosts/htm63.com/httpdocs/tmp
lifetime	15
session_handler	database
shared_session	false
session_metadata	true
memcached_persist	true
memcached_compress	false
memcached_server_host	localhost
memcached_server_port	11211
redis_persist	true
redis_server_host	localhost
redis_server_port	6379
redis_server_db	0
cors	false
cors_allow_origin	*
cors_allow_headers	Content-Type,X-Joomla-Token
cors_allow_methods	
behind_loadbalancer	false
proxy_enable	false
proxy_host	
proxy_port	
proxy_user	xxxxxx
massmailoff	false
replyto	
replytoname	
MetaRights	(C) - 2021 - Hans KETTING
sitename_pagetitles	2
session_filesystem_path	
session_memcached_server_host	localhost
session_memcached_server_port	11211
session_redis_persist	1
session_redis_server_host	localhost
session_redis_server_port	6379
session_redis_server_db	0
frontediting	1
block_floc	1
log_everything	0
log_deprecated	0
log_priorities	all
log_categories	
log_category_mode	0
cookie_domain	
cookie_path	
asset_id	1
redis_server_auth	xxxxxx
session_redis_server_auth	xxxxxx
ftp_user	xxxxxx
ftp_pass	xxxxxx
proxy_pass	xxxxxx

**Comment by joomdonation** [comment]
@Hans-63 It is a known issue. See https://docs.joomla.org/J4.x:Redirects_from_Redirect_system_plugin_(if_enabled)_cause_internal_server_errors_500 for solution.

**Comment by Hans-63** [comment]
Thanks a lot for the answer; my search earlier didn't give this answer.....
