### ISSUE TITLE
[4.1] Scheduler: "task failed" counts twice

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#36859]
### Steps to reproduce the issue

- Go to _Scheduled Tasks_ and add a _GET Request_
- Enter an invalid url to _Request URL_ (e.g. http://jooomla.org)
- _Execution Rule_: manual
- Save the task
- Run the task **once**

### Expected result

![image](https://user-images.githubusercontent.com/66922325/151224512-a0729bd7-57ac-4bf1-8a73-1ff53faab40d.png)

### Actual result

![image](https://user-images.githubusercontent.com/66922325/151224355-56e84688-30d2-4ce4-85f8-0bf100bb3051.png)

### System information (as much as possible)

Joomla: 4.1.0-rc1
PHP: 7.4.9
DB: 10.3.29-MariaDB

**Comment by heelc29** [comment]
Here the two lines:

https://github.com/joomla/joomla-cms/blob/6d0ad10ab39f4b6874f24579e90fbb50837aeb0c/administrator/components/com_scheduler/src/Task/Task.php#L274

https://github.com/joomla/joomla-cms/blob/6d0ad10ab39f4b6874f24579e90fbb50837aeb0c/administrator/components/com_scheduler/src/Task/Task.php#L415

**Comment by Shubhamverma2796** [comment]
Removing +1 from line 415 fixes the issue. After removing +1, if the task fails the count is incremented by +1 only and does not get doubled. Please let me know if this is a valid fix then I will open a pr.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36868 . Thanks in advance.
