### ISSUE TITLE
[3.10.5] Two Factor Authentication is not working anymore

### ISSUE THREAD

**Issue by toonetcreation** [joomla/joomla-cms#36854]
### Steps to reproduce the issue

- update joomla to 3.10.5 version
- go to a user profile
- enable Two Factor Authentication
- save user profile
- edit again user profile
- you will see that Two Factor Authentication is disabled, even if you enable it before

### Expected result

Two Factor Authentication working, able to connect on front/back end

### Actual result

Even If I enable Two Factor Authentication, then when I save user profile, option is always disabled :

![screen shot 2022-01-26 at 09 46 04](https://issues.joomla.org/uploads/1/b8f51b23384bd819434f2a7ea33f93b2.png)

### System information (as much as possible)

Joomla 3.10.5
PHP 8.0.14
Database 5.5.5-10.3.32-MariaDB

### Additional comments

This problem appears since latest update from joomla 3.10.4 to 3.10.5
Problem is also for websites running on joomla 3.10.4 where Two Factor Authentication was already enabled.
So for those websites, after upgrading joomla to 3.10.5, it is just impossible to login on front-end/back-end as Two Factor Authentication is not working anymore.

**Comment by toonetcreation** [comment]
any news or infos?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36854">issues.joomla.org/tracker/joomla-cms/36854</a>.</sub>

**Comment by zero-24** [comment]
I just did a quick check with a site where I use 2FA and I can not confirm that issue. Can you check your php error log and maybe check error messages when you set error reporting to maximum? Please also check that the 2FA Plugin have been enabled.

As a quick fix you can go and disable the plugins via the database or by renaming the /plugins/twofactorauth/ folder to plugins/back_twofactorauth/ that should you allow to login without 2FA.

But would be very interesting to understand why it fails on your end maybe the error messages give some clue.

**Comment by toonetcreation** [comment]
I have tried again and otday works fine.
weird because yesterday I tried many times and problem was the same.
so problem closed for me.
thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36854">issues.joomla.org/tracker/joomla-cms/36854</a>.</sub>

**Comment by zero-24** [comment]
Are you using Google 2FA or YubiKey 2FA? Maybe the YubiKey server was not reachable at that very moment where you tested?

But as its solved I will close here for now feel free to reopen when it happens again or you have more infos for us.

**Comment by toonetcreation** [comment]
I'm using Google 2FA.
yes probably out yesterday...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36854">issues.joomla.org/tracker/joomla-cms/36854</a>.</sub>

**Comment by brianteeman** [comment]
You should also note that 2fa is extremely time sensitive. If the time of your device (or server) is not correct then 2fa will fail

**Comment by toonetcreation** [comment]
ok undertsood, many thanks ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36854">issues.joomla.org/tracker/joomla-cms/36854</a>.</sub>
