### ISSUE TITLE
Quickicon for global checkin does not count numbers

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#36866]
### Steps to reproduce the issue### Steps to reproduce the issue
This is probably related to php version 8 as it is not in online  applications with php7.3
Maybe also related to com_language, I got an error 500 on the ajax request with and answer related to com_language when I was in a german backend. 

In quickicons, set the icon for global check-in to "items with count".

### Expected result
A number as in other icons

### Actual result
The spinner never stops. 

![grafik](https://user-images.githubusercontent.com/1035262/151254677-bba6e528-76f7-4089-a96d-1dc57f9d4669.png)

### System information (as much as possible)
win11, xampp, php 8.0.14 joomla 4.0.6

**Comment by brianteeman** [comment]
on a monolingual site with php 8.0.10 I could not replicate this

**Comment by chmst** [comment]
Was the number of folder > 0? 

Mine is a multilingual site too and it happens also when I choose English as language.
I found this in the ajax request answer, seems to be the plural language string. 

-- libraries\\src\\Language\\Text.php(251): sprintf('Globales Freige...', 2)
-- administrator\\components\\com_checkin\\src\\Controller\\DisplayController.php(120): Joomla\\CMS\\Language\\Text::plural('COM_CHECKIN_N_Q...', 2)\n
-- \\libraries\\src\\MVC\\Controller\\BaseController.php(730): Joomla\\Component\\Checkin\\Administrator\\Controller\\DisplayController->getQuickiconContent()

**Comment by brianteeman** [comment]
it was 1

**Comment by chmst** [comment]
Then it is another language key which does not replace the %D

COM_CHECKIN_N_QUICKICON_SRONLY="Globales Freigeben: %D Tabellen haben gesperrte Einträge."

**Comment by brianteeman** [comment]
I did locate another problem though - note the count. only the first image has the correct count

![image](https://user-images.githubusercontent.com/1296369/151321018-b9685e5d-60da-42f1-a0c2-1fc55ac81796.png)

![image](https://user-images.githubusercontent.com/1296369/151321027-ac3faf62-8da4-4206-8a1c-e6e69ff00bf2.png)

![image](https://user-images.githubusercontent.com/1296369/151321035-ac77fea7-989f-4414-b6c3-6f52c3ec74f4.png)

**Comment by chmst** [comment]
The first one counts the number of records, the quickicon counts the number of folders. I agree that this is not self explaining.

**Comment by brianteeman** [comment]
folders is wrong. you are checking in items

**Comment by chmst** [comment]
Can you open another issue then? Then it will not be forgotten if this one will be closed.

**Comment by brianteeman** [comment]
will do

**Comment by chmst** [comment]
The german language strings use %D instead of %d as placeholder for variables in this language file (com_checkin.ini).  With php 7 this does not matter but in php 8 
@tecpromotion @zero-24. 

Solution in the  german language file or in the sprintf function of text.php (in case of other languages who also use %D)?
Regex is not what I want to touch ...

**Comment by tecpromotion** [comment]
fixed in https://github.com/joomlagerman/joomla/pull/2253
thanks @chmst

**Comment by chmst** [comment]
So I close this for now as the bug is fixed in the german language file. Thanks @tecpromotion
