### ISSUE TITLE
[4.1] Core templates SCSS does not compile in release

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#36872]
Try to compile the SCSS of the frontend template for example in media/templates/site/cassiopeia/scss/template.scss That is what we are shipping to our users with 4.1 and it does not compile, since it is a copy from the /build folder to the /media folder. However in the /build folder it is another level deeper than in the /media folder and thus for example the above file tries to include files by traveling one level to high in the filesystem.

**Comment by brianteeman** [comment]
How are you trying to compile it?

**Comment by Hackwar** [comment]
I've tried it with the code from #35403.

**Comment by richard67** [comment]
@dgrammatiko Could you have a look on this issue? Thanks in advance.

**Comment by dgrammatiko** [comment]
The `scss` folder in the `media/...` is a **deliverable** and not the **source** thus they should **NOT** used (in conjunction with Joomla's own tools) for compiling the css files, for those you need to use the folder `build/...`. But anyways the PHP compiler should be abandoned as it's not a real replacement of the actual tools for compiling SCSS to CSS...

**Comment by Hackwar** [comment]
However we aren't talking about the PHP compiler, but about the SCSS we are going to ship with 4.1 and that SCSS right now is broken. You can not create an SCSS file which includes that template.scss and run npm to compile it. So please stay on topic.

**Comment by Hackwar** [comment]
If those files aren't meant to be compiled, then delete them now and don't deliver them with our release package.

**Comment by dgrammatiko** [comment]
You can, the source files are in the build folder...

**Comment by dgrammatiko** [comment]
> If those files aren't meant to be compiled, then delete them now and don't deliver them with our release package.


Yes probably should be removed

**Comment by brianteeman** [comment]
> You can, the source files are in the build folder...

That folder is not distributed


> > If those files aren't meant to be compiled, then delete them now and don't deliver them with our release package.
> 
> Yes probably should be removed

Irrespective of the phpcss thing having the scss for the templates is useful - assuming that the paths are fixed and they can be used.

@Hackwar raises a valid issue here

**Comment by dgrammatiko** [comment]
> Irrespective of the phpcss thing having the scss for the templates is useful 

Let me disagree here. Bootstrap 5.2 will have most of their components (I think their missing only the forms, but have;t checked lately) using CSS Variables. Meaning you will never-ever need to recompile Bootstrap... The whole SCSS precompiling is not needed anymore...
Here's what Bootstrap is doing regarding CSS Variables:
- https://github.com/twbs/bootstrap/pull/35428
- https://github.com/twbs/bootstrap/pull/35413
- https://github.com/twbs/bootstrap/pull/35409
- https://github.com/twbs/bootstrap/pull/35403
- https://github.com/twbs/bootstrap/pull/35402
- https://github.com/twbs/bootstrap/pull/35399
- https://github.com/twbs/bootstrap/pull/34622
- https://github.com/twbs/bootstrap/pull/34600
- https://github.com/twbs/bootstrap/pull/34443
- https://github.com/twbs/bootstrap/pull/33125
- https://github.com/twbs/bootstrap/pull/35401
- https://github.com/twbs/bootstrap/pull/35123

**Comment by dgrammatiko** [comment]
What I'm trying to say is **JUST KILL SCSS** It was a **mistake**

**Comment by brianteeman** [comment]
> What I'm trying to say is **JUST KILL SCSS** It was a **mistake**

Maybe so but for at least the next 6 months we will be shipping it - so it should be usable

**Comment by dgrammatiko** [comment]
> so it should be usable

Ok will try to do a pr this weekend

**Comment by dgrammatiko** [comment]
This can be closed

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36879 . Thanks in advance.
