### ISSUE TITLE
Redirection, Joomla 4.0.6

### ISSUE THREAD

**Issue by yurypinchuk** [joomla/joomla-cms#36874]
The built-in redirection does not work. Previously, there was no such problem.

https://mirx100.com/muzei
https://mirx100.com/registration

**Comment by Quy** [comment]
It is a known issue. See https://docs.joomla.org/J4.x:Redirects_from_Redirect_system_plugin_(if_enabled)_cause_internal_server_errors_500 for solution.

**Comment by yurypinchuk** [comment]
Thank you very much!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36874">issues.joomla.org/tracker/joomla-cms/36874</a>.</sub>
