### ISSUE TITLE
Install Languages is not possible

### ISSUE THREAD

**Issue by Quarx64** [joomla/joomla-cms#36887]
Debian 10
PHP 8.0.14
Apache 2.4

[Sat Jan 29 12:50:08.310049 2022] [php:warn] [pid 25493] [client 192.168.100.101:6403] PHP Warning:  simplexml_load_string(): Entity: 
line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 154, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed
[Sat Jan 29 12:50:08.310122 2022] [php:warn] [pid 25493] [client 192.168.100.101:6403] PHP Warning:  simplexml_load_string(): 19ee in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 154, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed
[Sat Jan 29 12:50:08.310140 2022] [php:warn] [pid 25493] [client 192.168.100.101:6403] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 154, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed
[Sat Jan 29 12:50:08.310200 2022] [php:warn] [pid 25493] [client 192.168.100.101:6403] PHP Warning:  Attempt to read property "extension" on bool in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 158, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed
[Sat Jan 29 12:50:08.310226 2022] [php:warn] [pid 25493] [client 192.168.100.101:6403] PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 158, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed
[Sat Jan 29 12:51:51.938477 2022] [php:warn] [pid 25437] [client 192.168.100.101:6424] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 154, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed
[Sat Jan 29 12:51:51.938552 2022] [php:warn] [pid 25437] [client 192.168.100.101:6424] PHP Warning:  simplexml_load_string(): 19ee in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 154, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed
[Sat Jan 29 12:51:51.938571 2022] [php:warn] [pid 25437] [client 192.168.100.101:6424] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 154, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed
[Sat Jan 29 12:51:51.938601 2022] [php:warn] [pid 25437] [client 192.168.100.101:6424] PHP Warning:  Attempt to read property "extension" on bool in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 158, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed
[Sat Jan 29 12:51:51.938636 2022] [php:warn] [pid 25437] [client 192.168.100.101:6424] PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 158, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed
[Sat Jan 29 12:59:58.543832 2022] [php:warn] [pid 25489] [client 192.168.100.101:6467] PHP Warning:  simplexml_load_string(): Entity: line 1: parser error : Start tag expected, '&lt;' not found in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 154, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed
[Sat Jan 29 12:59:58.543899 2022] [php:warn] [pid 25489] [client 192.168.100.101:6467] PHP Warning:  simplexml_load_string(): 19ee in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 154, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed
[Sat Jan 29 12:59:58.543916 2022] [php:warn] [pid 25489] [client 192.168.100.101:6467] PHP Warning:  simplexml_load_string(): ^ in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 154, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed
[Sat Jan 29 12:59:58.543946 2022] [php:warn] [pid 25489] [client 192.168.100.101:6467] PHP Warning:  Attempt to read property "extension" on bool in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 158, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed
[Sat Jan 29 12:59:58.543961 2022] [php:warn] [pid 25489] [client 192.168.100.101:6467] PHP Warning:  foreach() argument must be of type array|object, null given in /var/www/html/joomla4/administrator/components/com_installer/src/Model/LanguagesModel.php on line 158, referer: http://192.168.100.104/joomla4/administrator/index.php?option=com_languages&view=installed

**Comment by chmst** [comment]
Please add more information. Which joomla version? Downloaded from where? Which language are you installing? During installation of Joomla or into an existing installation?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36887">issues.joomla.org/tracker/joomla-cms/36887</a>.</sub>

**Comment by richard67** [comment]
Most important is which language as it seems that either the XML file of that language download site or the manifest XML of the package is broken.

**Comment by zero-24** [comment]
FYI @Llewellynvdm and me are looking into this and try to avoid it in the future. I would say we keep this open till we have a PR to check and validate that it worked.

**Comment by brianteeman** [comment]
If only someone had said we had an issue with bad languages before

**Comment by zero-24** [comment]
The things we are investigating have nothing to do with bad languages for example we also got other reports where all languages where down. The latest issue that have beem fixed where an issue of the language that was wrongly setup by the admin on the downloads portal.

**Comment by Quarx64** [comment]
Fresh Joomla 4, downloaded from joomla.org
Installation: OK
In Admin panel klick on "Install Languages" -> no effekt and Errors as described in apache.log

**Comment by zero-24** [comment]
The server side patch from @Llewellynvdm has been deployed now.

**Comment by brianteeman** [comment]
I guess this can be closed now?

**Comment by richard67** [comment]
@Quarx64 Please test and report back if it works now for you. Thanks in advance.

**Comment by Quarx64** [comment]
no changes
ive inserted a line "echo $response->body;"
after $updateSiteXML = simplexml_load_string($response->body);
in joomla file /administrator/components/com_installer/src/Model/LanguagesModel.php on line 154
after klick on "Install Languages" it takes 1 Minute an then i get the Result: 19ee 0 on screen

**Comment by zero-24** [comment]
@Quarx64 can you run a var_dump on the `$response` variable at line 146? `var_dump($response);` Would be interesting to know what you get back.

**Comment by Quarx64** [comment]
New server, new installation:
Die Update-Quelle #2 "Accredited Joomla! Translations", URL: https://update.joomla.org/language/translationlist_4.xml, konnte nicht geöffnet werden.

**Comment by zero-24** [comment]
Hmm interesting can you check whether curl is installed and enabled on said server?

**Comment by brianteeman** [comment]
Is this still a problem?

**Comment by Quarx64** [comment]
No, all problems resolved.
Update Server is reachable and Joomla Versions 3.xx and 4.xx runs perfectly.

**Comment by richard67** [comment]
Closing as stated above.
