### ISSUE TITLE
[4.1] Components pass database table prefix to user activity log

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#36889]
### Steps to reproduce the issue
Components pass the database table prefix to the user activity log. Probably not worth doing.

See https://github.com/joomla/joomla-cms/issues/36889#issuecomment-1038065923

~~To reproduce the problem, just play with the task scheduler component in the plan to create / execute / unlock the task, then look in the action log, having previously checked the scheduler component in the action log settings (by the way, if I don’t confuse anything from memory, this is the only DISABLED component in the action log after installing Joomla).~~

Localhost, PHP 7.2, MariaDB 10.3, One of the latest nightly builds of Joomla 4.1.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/151665265-94399df1-08ea-4c8b-9e74-2f5f106407e0.png)

![Screenshot_2](https://user-images.githubusercontent.com/8440661/151665266-5d5b2067-13e4-4f71-a28b-ac94ebec0fe5.png)

**Comment by Kostelano** [comment]
I wrote carefully :)

> Probably, this should not be done, given that this has never been noticed in the work of other components.

At first glance, it's hard for me to imagine a situation with a security breach, even if NOT a super administrator (but just an administrator) knows the prefix of the database tables.

I think that more experienced developers will be able to appreciate this behavior. If I'm wrong, just close.

**Comment by brianteeman** [comment]
You are correct it should not show the prefix

**Comment by Quy** [comment]
I am unable to replicate. Please provide steps to reproduce.

**Comment by brianteeman** [comment]
From your screenshot it looks odd because there are 4 logs of a checkin and only one of those does not have the prefix removed.

**Comment by Kostelano** [comment]
Hmmm, now I have the prefix displayed in any component, not just the scheduler. I have not yet determined what sequence in the Joomla control panel should be done to get this behavior.

I'll close this for now.

**Comment by heelc29** [comment]
@Kostelano Can you reopen please. I can replicate it.

Check-in via buttons (close) or lock icon works fine
![image](https://user-images.githubusercontent.com/66922325/153752338-af0ab4c1-cd77-4ff2-91e6-49e0ae001c70.png)
Check-in via _Global Check-in_ not
![image](https://user-images.githubusercontent.com/66922325/153752376-2a8a53d6-242c-4b2e-b9fb-e0f6e4a73264.png)
Actionslogs:
![image](https://user-images.githubusercontent.com/66922325/153752433-f0e8bfd8-d7be-42d2-a109-daf870aac4c3.png)
Also, it's not specific to task scheduler. I've tested it with the contact component.

**Comment by Kostelano** [comment]
@heelc29 opened. Yes, I agree, this does not apply to the scheduler, it just happened initially that I caught the problem with it.

I will rename the problem.

**Comment by brianteeman** [comment]
Please test #37198
