### ISSUE TITLE
[4.1] Media Manager [a11y]

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36881]
### Steps to reproduce the issue
Use this keyboard only and try to create a new folder in the media manager

The _modal_ never gets keyboard focus - you can see navigation taking place on the main window below the modal

![media](https://user-images.githubusercontent.com/1296369/151525612-73aa5b36-a402-401b-91a1-248dd53a251a.gif)

**Comment by pritam825** [comment]
I am working on this

**Comment by pritam825** [comment]
I have replace this code
      MediaManager.Event.listen('onClickCreateFolder', function () {
        return _this2.$store.commit(SHOW_CREATE_FOLDER_MODAL);
      });
with this
      MediaManager.Event.listen('onClickCreateFolder', function () {
       document.querySelector('[tabindex="-1"]').focus();
        return _this2.$store.commit(SHOW_CREATE_FOLDER_MODAL);
      });
But it's not working , can you please give me some hint, I have tried by made a function for setting globally tabindex=-1 and calling it when clicking on the create folder button , it's also not working, so can you please give some hint;

**Comment by brianteeman** [comment]
If I could have fixed it then I would have done it myself. Sorry I dont have a clue

**Comment by pritam825** [comment]
ok sir Thanks, I will try until I get the solution.

**Comment by dgrammatiko** [comment]
@pritam825 you will need to jail the tab functionality only to the modal focusable elements, eg:
- get the modal focusable elements: https://github.com/joomla-projects/custom-elements/blob/1b3b9e7a0a19eca44c5f91eb89f6d6009e8b3f90/src/js/modal/modal.js#L13
- jail logic: https://github.com/joomla-projects/custom-elements/blob/1b3b9e7a0a19eca44c5f91eb89f6d6009e8b3f90/src/js/modal/modal.js#L165-L189

The functionality needs to happen on the opening of the modal and needs to be disconnected when the modal closes

**Comment by pritam825** [comment]
@dgrammatiko Thanks, I am working according to your instruction

**Comment by akshitrattan** [comment]
Where do we have to make the changes for the modal, as in which file???

**Comment by akshitrattan** [comment]
`const focusasbleElements = ['a[href]', 'area[href]', 'input:not([disabled])', 'select:not([disabled])', 'textarea:not([disabled])', 'button:not([disabled])', 'iframe', 'object', 'embed', '[contenteditable]', '[tabindex]:not([tabindex^="-"])'];
    const firstFocusableElement = modal.querySelectorAll(focusableElements)[0];
    const focusableContent = modal.querySelectorAll(focusasbleElements);
    const lastFocusableElement = focusableContent[focusableContent.length - 1];

    document.addEventListener('keydown', function(e) {
      let isTabPressed = e.key === 'Tab' || e.keyCode === 9;
    
      if (!isTabPressed) {
        return;
      }
    
      if (e.shiftKey) { // if shift key pressed for shift + tab combination
        if (document.activeElement === firstFocusableElement) {
          lastFocusableElement.focus(); // add focus for the last focusable element
          e.preventDefault();
        }
      } else { // if tab key is pressed
        if (document.activeElement === lastFocusableElement) { // if focused has reached to last focusable element then focus first focusable element after pressing tab
          firstFocusableElement.focus(); t
          e.preventDefault();
        }
      }
    });
    
    firstFocusableElement.focus();`

I made these changes in the modal-es6.js in the modal.addEventListener('shown.bs.modal') and it doesn't seem to work

**Comment by akshitrattan** [comment]
I have 2 solutions to this, problem, and I tried applying it on my local system but due to some reason the changes don't seem to work, I would need a little help regarding the solutions from anyone who is familiar with vue.js
I am pretty sure the solutions should work
@dgrammatiko

**Comment by akshitrattan** [comment]
> ### Steps to reproduce the issue
> Use this keyboard only and try to create a new folder in the media manager
> 
> The _modal_ never gets keyboard focus - you can see navigation taking place on the main window below the modal
> 
> ![media](https://user-images.githubusercontent.com/1296369/151525612-73aa5b36-a402-401b-91a1-248dd53a251a.gif)

this problem is with the delete modal also

**Comment by richard67** [comment]
> I have 2 solutions to this, problem, and I tried applying it on my local system but due to some reason the changes don't seem to work, I would need a little help regarding the solutions from anyone who is familiar with vue.js I am pretty sure the solutions should work @dgrammatiko

@akshitrattan You know that you have to compile the js, e.g. with `npm ci` or `npm run build:js`? See here for a description: https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment

**Comment by richard67** [comment]
Closing as having a pull request.
