### ISSUE TITLE
Overrides need checking on an uninstalled template

### ISSUE THREAD

**Issue by PMWilliams123** [joomla/joomla-cms#36885]
### Steps to reproduce the issue

Updated Joomla Core form 4.0.5 to 4.0.6
Updated Template Creator CK form 5.0.9 to 5.0.11
Checked templates noticed I had two copies of the same template.
Changed site template to Cassiopeia and uninstalled the template made in Template Creator CK template.
Both instance of that template gone.
Recreated installed the template form template creator CK.
Noticed that hope dashboard is reporting (and still is) "Override(s) to check 5"
Clicking on that button takes me to Templates Templates 9Site) which reports that boteh Cassiopeia and the template created in Template Creator CK are "Up To Date". They are the only two templates on the site. 

### Expected result

that there are no overrides to check

### System information (as much as possible)

Override(s) to check 5"

### Additional comments

Please forgive me if i get this wrong as this is the first time I have attempted to use this. I can describe how I produced the issue. I am not in a position to see if it is reproducible at the moment..

**Comment by brianteeman** [comment]
Thanks very much for the report

**Comment by brianteeman** [comment]
I finally found out why this happened. As I have written in detail on another issue #38700 I am going to suggest that this issue is closed and it is continued in that one.

**Comment by richard67** [comment]
Closing as suggested above. See #38700 for further discussion.
