### ISSUE TITLE
[4.1] Scheduled Tasks Dashboard Typo?

### ISSUE THREAD

**Issue by alann60** [joomla/joomla-cms#36890]
On the Scheduled Tasks Dashboard, after the add your first task screen the tasks Set Site Online and Set Site Offline have the same description see attached screenshot.

![screen shot 2022-01-29 at 16 23 49](https://issues.joomla.org/uploads/1/cca4f093f8738120df7b29675dd4c2b4.png)

Same typo in task view:

![task_scheduler_online_offline2](https://user-images.githubusercontent.com/30389463/151669298-6dff59f7-1e23-4bff-88ab-3c5e41815a0c.png)

**Comment by Quy** [comment]
Fixed in #36589. Please test using the nightly builds. https://developer.joomla.org/nightly-builds.html
