### ISSUE TITLE
2 bugs found for Joomla 4.0.6 

### ISSUE THREAD

**Issue by wedevlops** [joomla/joomla-cms#36899]
### Steps to reproduce the issue
Hi,

I have seen two bugs so far:

1. the private massage does not work in Joomla 4 ver. 4.0.6
Go to:
User - massaging - Private massage

2. Article options has also a bug; basically if you change the Author to hide in global configuration is working; but when you sent this to an individual page like hiding author, hits, publish date, category, and other fields won't work. 
Go to:
Any article (In my case I used the sample data) - Click on options - hide Author example or show hits. 

### Expected result

1. Nothing happens (filter won't work for any options like users/id/)

2. Per page should be able to over write if you set the page. Example: In one article you show the Author or hide the hits (It was not working properly)

### Actual result

1. You cannot find any users.

2. You cannot set the article options (working only in Global settings)

### System information (as much as possible)

Joomla 4 version 4.0.6 
PHP Version	7.4.27

### Additional comments

I have installed the sample data for joomla 4.0.6

**Comment by brianteeman** [comment]
Neither of these are bugs

1. Private messages will only offer to send a message to users with access to the administrator. If you dont have any users with administrator access then there will be no users offered.

2. You also need to consider the options settings in the menu

**Comment by wedevlops** [comment]
Thanks for point number 1. Now; I know that only part of the administrator can send messages. 

but for number 2 items. see attached file. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36899">issues.joomla.org/tracker/joomla-cms/36899</a>.</sub>

**Comment by richard67** [comment]
> but for number 2 items. see attached file.

@wedevlops Which attached file? There is none.

**Comment by wedevlops** [comment]
![screen shot 2022-01-31 at 09 45 29](https://issues.joomla.org/uploads/1/44748c60e7199b71e189b38d256ae4ad.jpg)

sorry; i miss out the attachment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36899">issues.joomla.org/tracker/joomla-cms/36899</a>.</sub>

**Comment by wedevlops** [comment]
if you also try hide the hits and publish date.. it will not work as well. I just create a one example on my marking author hide. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36899">issues.joomla.org/tracker/joomla-cms/36899</a>.</sub>

**Comment by richard67** [comment]
@wedevlops What does your screenshot show? The article settings? Or the menu item settings? The menu item settings take precedence over the article settings, and these take precedence over the global settings.

**Comment by wedevlops** [comment]
![article option _ settings](https://user-images.githubusercontent.com/69560329/152120168-d173efc6-9808-49a9-a587-e2dd5eb50890.jpg)

**Comment by brianteeman** [comment]
> @wedevlops What does your screenshot show? The article settings? Or the menu item settings? The menu item settings take precedence over the article settings, and these take precedence over the global settings.

**Comment by wedevlops** [comment]
I tried that as well. Global settings Hide author and article settings show author. the result is it will always follow a global setting. you cannot show the author to a particular Article.

**Comment by richard67** [comment]
@wedevlops You still do not tell us anything about the **_menu item_** settings for what we have asked several times.

**Comment by brianteeman** [comment]
If the menu item is a "single article"
Global - hide
Article - show
Menu - show

If the menu item is a blog category 
Global - hide
Article - show
Menu - Use article settings

**Comment by wedevlops** [comment]
yeah.. I miss that out the Menu settings.. Thanks.. CASED SOLVED!

**Comment by richard67** [comment]
That was hard but finally you found it. Closing as not as bug.

@wedevlops Please in future try to use better titles. As you have seen, not everything of which you think it is a bug is a bug at the end, and the title also doesn't tell anything about what is not working. Thanks in advance.
