### ISSUE TITLE
[4.2] clicking on the Help Button, it's  giving 404 - RuntimeException

### ISSUE THREAD

**Issue by pritam825** [joomla/joomla-cms#36891]
### Steps to reproduce the issue

goto components->index-> then click on the  help button

### Expected result

help button should not be given the error on clicking help button on every page, one of the screenshot is as below

### Actual result

![Screenshot (1971)](https://user-images.githubusercontent.com/54195688/151669732-aa2aa868-d48b-44ba-939c-a18bad4756e3.png)

**Comment by pritam825** [comment]
can I replace the link with this -> "https://docs.joomla.org/Help25:Components_Finder_Manage_Indexed_Content"

**Comment by brianteeman** [comment]
that is the exoected behaviour until the help server is configured for joomla 4.2

**Comment by pritam825** [comment]
oh ok ,I thought there is some mistakes, Thanks sir
