### ISSUE TITLE
[4.1] Child Templates & Task Schedule

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36896]
Maybe my search skills are failing but I can't find any documentation for either of these new features. Not even a three sentence summary.

**Comment by dgrammatiko** [comment]
Depends on your expectations:
- If you're looking for documentation on the use of those features, I guess there are no docs.
- If you're looking for the explainers of the features, then for the child templates is [here](https://gist.github.com/dgrammatiko/7aa31a2e7f82b9878eb35f8bc7e1203b)

**Comment by brianteeman** [comment]
I guess I was looking for both and expecting to find them on docs.joomla.org

**Comment by brianteeman** [comment]
Actually I was also looking for a high level overview of why we have both these new features. I've made an attempt at that which if correct someone can add to the docs site in the correct place as a start.

## Child Templates
How do you override an override and not lose it on update? How do you create multiple different overrides of the same view?

Welcome to the world of Child Templates.

A child template works exactly the same as any other template except that it uses all the code, php, css and javascript, of its parent template. At its most basic level it only contains a single file, templateDetails.xml, as everything else is inherited from the parent. 

Now with a child template you can customise an override or css and keep the parent template as clean as the day your template provider supplied it. There is no limit on the number of child templates that you can create so each one could have different layouts and styles.

## Schedule Tasks
Many Joomla extensions provide options for automating certain tasks eg optimising images, performing a backup or sending a newsletter.

Until now they have all needed to create their own code to schedule the task and/or rely on the site owner understanding how to set up a cron job.. 

With Joomla 4.1 there is now a core provided component that developers can use with their extensions. It's as simple as writing a new plugin and then the Schedule Tasks component provides all the automation and controls for the site owner to manage the task.
