### ISSUE TITLE
Joomla 4 - Error 404

### ISSUE THREAD

**Issue by alehei3333333** [joomla/joomla-cms#36908]

**Comment by alehei3333333** [comment]
Wrote a trial component

schooltech.xml
`<?xml version="1.0" encoding="utf-8"?>
<extension type="component" method="upgrade">

 
    <name>SchoolTech</name>
    
    <creationDate></creationDate>
    
    <author>MuCompani</author>
    <authorUrl></authorUrl>
    <copyright></copyright>
    <license></license>
    
    <version>0.1</version>
    
    <description>
        Контент для сайта
    </description>
 
    
    <namespace path="src/">MuCompani\Component\SchoolTech</namespace>
           
    <administration>
        
        <menu link="index.php?option=com_schooltech">SchoolTech</menu>
        
        <files folder="admin/">
            <folder>services</folder>
            <folder>src</folder>
            <folder>tmpl</folder>
        </files>
    </administration>
 
</extension>`

admin/services/provider.php
`
<?php

defined('_JEXEC') or die;

use Joomla\CMS\Dispatcher\ComponentDispatcherFactoryInterface;
use Joomla\CMS\Extension\ComponentInterface;
use Joomla\CMS\Extension\MVCComponent;
use Joomla\CMS\Extension\Service\Provider\ComponentDispatcherFactory;
use Joomla\CMS\Extension\Service\Provider\MVCFactory;
use Joomla\CMS\MVC\Factory\MVCFactoryInterface;
use Joomla\DI\Container;
use Joomla\DI\ServiceProviderInterface;

return new class implements ServiceProviderInterface {

    public function register(Container $container): void {
        $container->registerServiceProvider(new MVCFactory('\\MuCompani\\Component\\SchoolTech'));
        $container->registerServiceProvider(new ComponentDispatcherFactory('\\MuCompani\\Component\\SchoolTech'));
        $container->set(
            ComponentInterface::class,
            function (Container $container) {
                $component = new MVCComponent($container->get(ComponentDispatcherFactoryInterface::class));
                $component->setMVCFactory($container->get(MVCFactoryInterface::class));

                return $component;
            }
        );
    }
};
`

admin/src/Controller/DisplayController.php
`<?php

namespace MuCompani\Component\SchoolTech\Administrator\Controller;

defined('_JEXEC') or die;

use Joomla\CMS\MVC\Controller\BaseController;

/**
 * @package     Joomla.Administrator
 * @subpackage  com_schooltech
 *
 * [member=126442]copyright[/member]   Copyright (C) 2021 John Smith. All rights reserved.
 * @license     GNU General Public License version 3; see LICENSE
 */

/**
 * Контроллер по умолчанию компонента SchoolTech
 *
 * @package     Joomla.Administrator
 * @subpackage  com_schooltech
 */
class DisplayController extends BaseController {
    /**
     * Представление по умолчанию для метода отображения.
     *
     * @var string
     */
    protected $default_view = 'schooltemplate';

    public function display($cachable = false, $urlparams = array()) {
        return parent::display($cachable, $urlparams);
    }

}`

admin/src/View/SchoolContent/HtmlView.php
`
<?php

namespace MuCompani\Component\SchoolTech\Administrator\View\SchoolContent;

defined('_JEXEC') or die;

use Joomla\CMS\MVC\View\HtmlView as BaseHtmlView;

/**
 * @package     Joomla.Administrator
 * @subpackage  com_helloworld
 *
 * [member=126442]copyright[/member]   Copyright (C) 2021 John Smith. All rights reserved.
 * @license     GNU General Public License version 3; see LICENSE
 */

/**
 * Основной вид в админке "SchoolTech"
 */
class HtmlView extends BaseHtmlView {

    /**
     * Отображение основного вида "SchoolTech"
     *
     * @param   string  $tpl  Имя файла шаблона для анализа; автоматический поиск путей к шаблону.
     * @return  void
     */
    function display($tpl = null) {
        parent::display($tpl);
    }


}
`

admin/tmpl/schooltemplate/default.php
`<?php

/**
 * @package     Joomla.Administrator
 * @subpackage  com_helloworld
 *
 * [member=126442]copyright[/member]   Copyright (C) 2021 John Smith. All rights reserved.
 * @license     GNU General Public License version 3; see LICENSE
 */

// Нет прямого доступа к этому файлу
defined('_JEXEC') or die('Всем кыш! =D');
?>
<h2>TEST</h2>`

I collect com_schooltech.zip in the archive, install it. When I try to enter the component in the admin panel, I get

"404 Could not find view [name, type, prefix]: schooltemplate, HTML, Administrator."

At the same time, with a stupid rewrite from the example at the link below, everything works fine. But it is worth trying to replace the values ​​​​with those that I have and we get the above error. Am I misunderstanding something? Is there something not the name of files / folders, but something systemic?

[https://mb4.ru/cms/joomla4/724-developing-a-basic-component-for-joomla-4.html](url)

**Comment by b2z** [comment]
This should be closed as not related to CMS at all

**Comment by chmst** [comment]
@alehei3333333 please ask such questions in forum.joomla.org, this is for issues with the joomla core. So closing.
