### ISSUE TITLE
Joomla 4 search bar in menu link / categories missing

### ISSUE THREAD

**Issue by thefbi79** [joomla/joomla-cms#36916]
### Steps to reproduce the issue
Go to admin panel. Create a new menu link. Search for the parent menu link. Here in Joomla 3.x was a search field to quickly find your menu when have many menu. Idem for the categories search.

### Expected result
Have a search field to find the item.!

### Actual result
No search field available

### System information (as much as possible)
Joomla 4.0.6

### Additional comments

[screen shot 2022-02-02 at 08 30 28](https://issues.joomla.org/uploads/1/f537b69471bfdd52c0fc7d5ece65154a.jpg)
[screen shot 2022-02-02 at 08 30 18](https://issues.joomla.org/uploads/1/58ef5ec34e4f5def1960beac47a050a9.jpg)

**Comment by brianteeman** [comment]
Confirmed

**Comment by thefbi79** [comment]
EDIT : This problem is on all search field, even if you want to find an article by the filters for example.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36916">issues.joomla.org/tracker/joomla-cms/36916</a>.</sub>

**Comment by thefbi79** [comment]
EDIT 2 : Sorry, in the search field for article it is OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36916">issues.joomla.org/tracker/joomla-cms/36916</a>.</sub>

**Comment by ReLater** [comment]
Please test https://github.com/joomla/joomla-cms/pull/36925
