### ISSUE TITLE
Spam removed

### ISSUE THREAD

**Issue by KaleGlassman** [joomla/joomla-cms#36917]
Removed

**Comment by brianteeman** [comment]
@zero-24 please remember to remove the pdf from the issues server

**Comment by zero-24** [comment]
I do not have access to that server but will ask who has to get it removed. Thanks

**Comment by brianteeman** [comment]
@HLeithner has access

**Comment by HLeithner** [comment]
Removed

**Comment by brianteeman** [comment]
thanks
