### ISSUE TITLE
CAPTCHA - reCAPTCHA

### ISSUE THREAD

**Issue by wedevlops** [joomla/joomla-cms#36915]
### Steps to reproduce the issue
1. Enable CAPTCHA - reCAPTCHA (input site key and secret key) - everything is working normally 
2. BUT when you decide to disable the CAPTCHA - reCAPTCHA even if the plugin is disabled - you cannot save it unless you put any character on the site key and secret key

### Expected result

You should be able to save it if the plugin is disabled (But in this case you need to put any character before you can save it) 

### Actual result

But in this case, you need to put any character before you can save it

### System information (as much as possible)

Joomla 4.0.6

**Comment by wedevlops** [comment]
![adding recapcha](https://user-images.githubusercontent.com/69560329/152115128-4b9a5cf5-cdeb-4ab0-83f8-1d57ac1a14fa.JPG)

Attaching files

**Comment by brianteeman** [comment]
This is the expected behaviour. Why would you want to save a form with invalid data? Also please remember that any plugin can be enabled directly from the plugin manager.

**Comment by wedevlops** [comment]
when I move the demo site to the actual domain and decided not to use google Recaptcha then I encounter this.  to close that window (screenshot) your need to input any character just to close it; even the plugin is disabled.

**Comment by brianteeman** [comment]
ah I think I see your use case. please confirm if my understanding is correct.

You have a site with captcha keys setup and then you want to disable captcha AND remove reference to those keys?

**Comment by wedevlops** [comment]
yes; right.. i tested in J3 it works fine.

**Comment by brianteeman** [comment]
I can  not confirm that. The behaviour in j3 is identical

It can't really be fixed whilst it is a required field

**Comment by wedevlops** [comment]
okay... I am just sharing my experience for J4. thanks..

**Comment by brianteeman** [comment]
Thank you it is appreciated

**Comment by richard67** [comment]
So the issue shall be closed as expected behavior?

**Comment by brianteeman** [comment]
Yes I would say so. The only other option would be to have a default value for the two fields set to something like 00000000000 but then that defeats the purpose of it being a required field

**Comment by richard67** [comment]
Closing as expected behavior. Details see previous comments. Feel free to re-open if you don't agree.
