### ISSUE TITLE
[4.0] Menu Item edit - order of Start/Finish Publishing

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#36918]
### What needs to be fixed
In Joomla 4 you can set the **Start Publishing** and **Finish Publishing** date of a menu item.
IMHO the order in the **Menus: Edit Item** of those new fields is not logical.

![menu_item](https://user-images.githubusercontent.com/1217850/152152415-b34e29d2-b477-4607-97ec-cb3cb59737b6.png)

### Why this should be fixed
The **Access** and **Language** fields are used more often than Start/Finish Publishing. 
This means that you have to scroll to use those options that are used more often.

Besides, with those fields in the form, the structure of the fields differs from other commonly used edit forms, like the **Articles: Edit** form:
![screencapture-localhost-joomla-joomla-cms-administrator-index-php-2022-02-02-13_11_47](https://user-images.githubusercontent.com/1217850/152152454-73af426c-5dd3-482f-bed6-ecf051679480.png)

### How would you fix it
Other forms have **Start Publishing** and **Finish Publishing** dates on a separate tab called **Publishing**.
**Menus: Edit Item** does not have that tab. However IMHO it makes more sense to move those Publishing fields to **Page Display**
I'll submit a PR for that.

### Side Effects expected
None, except that the documentation will have to be updated: https://help.joomla.org/proxy?keyref=Help4.x:Menu_Item:_New_Item/en

**Comment by brianteeman** [comment]
> The Access and Language fields are used more often than Start/Finish Publishing.

What do you base that on? Only your own experience.

Personally I've never used the language field and only rarely the access field - probably about as often as the start/end publishing

**Comment by karan-vaishnav** [comment]
Hello Sir!
may I work on this issue??

**Comment by pe7er** [comment]
> > The Access and Language fields are used more often than Start/Finish Publishing.
> 
> What do you base that on? Only your own experience.
> 
> Personally I've never used the language field and only rarely the access field - probably about as often as the start/end publishing

@brianteeman Yes, you are right. I base it on my personal experience with portal and multilingual websites.
And on the opinions of other Joomla (non-native English) users with whom I discussed about it.
For portal websites with multiple User Groups and Viewing Access Levels the Access field is used a lot.
And for multilingual website the Language field is essential.

Actually, although the start/end publishing for menu items might be a nice feature for some, I don't think that I will ever use it myself. Unpublishing menu items leads to 404 errors. I'd like to unpublish menu items manually so I can use the Redirect Manager to redirect the old link to a new page.

**Comment by pe7er** [comment]
I tried moving the Start Publishing and Finish Publishing date from the Details tab to the "Page Display" tab. And I found out that when you put those 2 fields on the "Page Display", they are saved as parameters in the ``params`` field. Instead they should be saved to the ``publish_up`` and ``publish_down`` fields.

I'll create a new PR just to move the Start Publishing and Finish Publishing date to the bottom of the Details page.

**Comment by pe7er** [comment]
> Hello Sir! may I work on this issue??

@karan-vaishnav Yeah, if you like. 
I created another PR to move the fields to the bottom, so they won't be in the way anymore.
If you know a better solution, then you are welcome to write another PR.

**Comment by richard67** [comment]
Closing as having a pull request.

@pe7er You could have closed the issue yourself as you know we close issues when having a PR, and you made both the issue and the PR.

**Comment by pe7er** [comment]
Ok, thanks!
