### ISSUE TITLE
iframe-height js

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36922]
What does this script do (or what is it supposed to do)?

https://github.com/joomla/joomla-cms/blob/88b03dd506233117f7225140387ad0ad365d6a5f/components/com_wrapper/tmpl/wrapper/default.php#L15

**Comment by dgrammatiko** [comment]
Nothing, kill it

**Comment by brianteeman** [comment]
So I wasnt going mad

**Comment by brianteeman** [comment]
(but if its not doing anything why did you spend your time converting it to es6?)

**Comment by dgrammatiko** [comment]
Actually I'm wrong here, the script will try to set the height of the iframe according to the contents inside it. Probably it shouldn't be useful as you can do that with css. So it's there for those that didn't actually styled correctly the iframe. In an perfect world that people used correctly HTML5 this should be redundant...

**Comment by brianteeman** [comment]
> Actually I'm wrong here, the script will try to set the height of the iframe according to the contents inside it.

Doesnt seem to do that in my tests

> Probably it shouldn't be useful as you can do that with css.

Really? I dont think you can but would like to learn

**Comment by dgrammatiko** [comment]
> Doesnt seem to do that in my tests

Is the iframe in the same origin? Cross origin I think won't work anymore (although it's the iframe that shouldn't have right on the parent doc)

**Comment by brianteeman** [comment]
same origin

**Comment by dgrammatiko** [comment]
Do you have attribute `load` appended on the iframe?
Comes from here:
https://github.com/joomla/joomla-cms/blob/88b03dd506233117f7225140387ad0ad365d6a5f/components/com_wrapper/src/View/Wrapper/HtmlView.php#L82

**Comment by brianteeman** [comment]
MY FAULT

I didnt set autoheight on

![image](https://user-images.githubusercontent.com/1296369/152193873-fc5fa969-548e-4087-ac91-3e9e5d956a5d.png)
