### ISSUE TITLE
Plugin: System - Additional Accessibility Features Google Fonts remove

### ISSUE THREAD

**Issue by pnkr** [joomla/joomla-cms#36928]
### Steps to reproduce the issue
Enabling this plugin tries to use Google Fonts
https://fonts.googleapis.com/icon?family=Material+Icons
through this css file /media/vendor/accessibility/js/accessibility.min.js?3.0.14

As of recent events Google Fonts breaches European law GDPR and should be optional.

### Expected result
Plugin should be google font independent. So it should use a embeded font or another solution for icons.

### System information (as much as possible)
Joomla 4.0.6

**Comment by zero-24** [comment]
Hmm looks like its a default option to use the remote font: https://github.com/ranbuch/accessibility/blob/09e9e21dadd5d0861c676cba008d8341533c2ef7/src/common.js#L75-L94
https://github.com/ranbuch/accessibility/blob/09e9e21dadd5d0861c676cba008d8341533c2ef7/src/main.js#L5-L6

But It looks like its possible to override it on the lib using end. But I'm not a JS expert to know how that could be done.

**Comment by brianteeman** [comment]
https://ranbuch.github.io/accessibility/#icon-image

**Comment by zero-24** [comment]
Looks like we can pass the relevant options here: https://github.com/joomla/joomla-cms/blob/4.1-dev/plugins/system/accessibility/accessibility.php#L73 and that icons can be stored and served locally

**Comment by brianteeman** [comment]
Just read the docs!!!

**Comment by zero-24** [comment]
Yes the docs says we can set a option in the array. Now I pointed to the place where the options can be changed :)

**Comment by zero-24** [comment]
PR created: https://github.com/joomla/joomla-cms/pull/36948
