### ISSUE TITLE
CustomField Type Media (media) > Changing Preview doesn´t work

### ISSUE THREAD

**Issue by BPBlueprint** [joomla/joomla-cms#36938]
### Steps to reproduce the issue
Create a customField of type Media (media).
Set preview 1. Tooltip, 2. Inline and 3. No
Test the view in backend for 1, 2 and 3

### Expected result
View of CustomField in Backend is
1. Tooltip
2. inline
3. No

### Actual result
View of CustomField in Backend is
1. and 2. are the same view
3. is No (means 3. works correct)

### System information (as much as possible)
Joomla! 4.0.4 AND Joomla! 4.1.0 RC1
PHP 8

**Comment by laoneo** [comment]
@dgrammatiko any feedback here? Is this done on purpose?

**Comment by dgrammatiko** [comment]
Yes, there is no tooltip anymore. That was by design

**Comment by laoneo** [comment]
Then we need to remove that options from the custom field?

**Comment by HusiBT** [comment]
Option "NO" should still be there. This works and is really helpful.
TOOLTIP can be removed, when it´s no more wanted. Cause it´s a bit confusing like that.

**Comment by dgrammatiko** [comment]
> Then we need to remove that options from the custom field?

FWIW early in the J4 development we were keeping things even if the functionality was removed (eg `behavior.framework`), later most got dropped, this one slipped...

Also iirc this field has some nasty logic for some of the expected attributes/options, these should be normalised to boolean, etc

**Comment by Quy** [comment]
Please test PR #37115.
