### ISSUE TITLE
[4.2] Hard limit need to be removed in Meta Description field

### ISSUE THREAD

**Issue by simbus82** [joomla/joomla-cms#36939]
### Steps to reproduce the issue
Try to add more than 160 ch in a Meta Description field, for example a Menu Voice.

### Expected result
The counter become red or go to negative after 160ch, i can continue to write what i want, and maybe will be the search engine to truncate my content.
On mobile and in some devices (combination of resolution/dpi), Google use a pixels limit for Meta Description, so can be over 160ch.

### Actual result
I can't try to use more that 160ch, the field have ad hard limit, so i can't, for example, cut&paste a long content and then edit to a 160 ch.
It's very annoying and time consuming.

![image](https://user-images.githubusercontent.com/1375730/152506061-8772ee30-ff9d-43d0-9e0e-13d7bd08c09f.png)

**Comment by brianteeman** [comment]
I'm sure we have discussed this before

**Comment by simbus82** [comment]
> I'm sure we have discussed this before

I checked if there was some talk about the "hard" limit, but I didn't find any other "issues" on this subject.
There were some discussions about the length (which is correct anyway).
We work with these fields on a daily basis, and with Joomla 4 we have found a slowdown in the process with our copywriters and SEOs.

**Comment by ReLater** [comment]
That was a political decision of Google disciples to force this limit. Nobody knows which limits will be recommended in the future and who is using meta fields for what purposes.

You can test this plugin that can also be configured to just not limit the length of some Meta fields.
https://github.com/GHSVS-de/plg_system_characterscounterghsvs#possible-settings-for-each-field-individually
**But first read:**
https://github.com/GHSVS-de/plg_system_characterscounterghsvs#restrictions

**Comment by simbus82** [comment]
> That was a political decision of Google disciples to force this limit. Nobody knows which limits will be recommended in the future and who is using meta fields for what purposes.

I'm sorry about that, and a little worried.
I'm a SEO and I would never have made such a decision.

Probably those who led you down this path (blocking the entry in the field) lack some SEO and UX skills.

Google has constantly changed, and continues to change, the length of meta. Two years ago on mobile they exceeded 200 ch, to date there are continuous tests (doing a lot of SEO we often fall into rollout of Google beta functions).
All of who do SEO with Joomla 4, need to be free to work with these contents.

> You can test this plugin that can also be configured to just not limit the length of some Meta fields. https://github.com/GHSVS-de/plg_system_characterscounterghsvs#possible-settings-for-each-field-individually **But first read:** https://github.com/GHSVS-de/plg_system_characterscounterghsvs#restrictions

Thanks a lot, But I hope this problem will be fixed because it remains a bug. The counter is ok, but we can't force a limit if not DB related.

I see that the limit is imposed in the XML, But is there a way to set the counter and not make it become the "max limit" of the field?

Maybe we can add a "case" here **/libraries/src/Form/Field)/TextareaField.php** called "**charlimit**" that if it is enabled do a true limit or not.
Is it possible @brianteeman?  (i see that you worked on the "charcounter" code)

**Comment by simbus82** [comment]
> I'm sure we have discussed this before

Found it, you are right! But no one considered the comment https://github.com/joomla/joomla-cms/pull/27804#issuecomment-595310546

![image](https://user-images.githubusercontent.com/1375730/152543853-933ddf73-f26d-42bf-9430-e9902cb4bc3e.png)

**Comment by brianteeman** [comment]
The script being used takes its count from the maxlength value in the field. To achieve what you want would require using a different attribute eg data-maxlength and changing the script to allow characters greater than the length and to count how many characters above that length.

Currently that script can not do this. Maybe if you submitted an issue report they will be able to make the change https://github.com/rikschennink/short-and-sweet/

**Comment by simbus82** [comment]
I made an issue (https://github.com/rikschennink/short-and-sweet/issues/7) but, obviously, the developer, despite having clear how to do it, asks to do a PR.
Unfortunately I don't develop in JS, so I can't fix the external script.

I'll try to find someone who can fix it ...

**Comment by pcombet-adosis** [comment]
Hello @brianteeman ,
I'm having the same issue. One of my client wants to be able to add extra character than the Default 160 char count, for the Metadata tab, in the backend. Modifying Charlimit in /libraries/src/Form/Field/TextareaField.php doesn't do anything.

Any clue to : 

1. have it changed hard coding the max char number
2. changing it using a dynamic value than can be set somewhere in the backoffice (maybe on Global config > site > SEO) - see screenshot

Thanks Brian, from all the french AFUJ members (just coming back from Bruxelles 2022 Joomla Days).
Best
Philippe
![seo-char-count](https://user-images.githubusercontent.com/30263049/169855646-577ea8ed-6de1-49e2-9a36-b5986f9d971e.png)

**Comment by pcombet-adosis** [comment]
@brianteeman Hello Brian, any idea how to have this issue being analysed by the Dev team ? Who can be interested by this point in the Joomla dev team ? 160 char is very short from a SEO point of view...
Thanks for your answer.
Philippe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36939">issues.joomla.org/tracker/joomla-cms/36939</a>.</sub>

**Comment by Mich-es** [comment]
Hi, 

Ultimately, the 160 characters don't matter, it's just annoying.

SUGGESTION - the 160 characters stay gray as long as you are under 160 characters. Anything beyond that changes the 160 characters to red font, but you can still save it and it will be accepted that way. It is then up to the user what he does and what not.

Google recently had a 120 character limit and also Google takes the appropriate test from the meta that matches the search query and limits that to 160 characters. There can and may be more in there.

> There's no limit on how long a meta description can be, but the snippet is truncated in Google Search results as needed, typically to fit the device width. https://developers.google.com/search/docs/appearance/snippet

**Comment by Sieger66** [comment]
More people which wants a possibility of configuration the limit of Meta Description see also at:

> #35018:

> [ReLater](https://github.com/ReLater):
> A core-side limitation of the length without the possibility of configuration is a no-go. No one knows whether the default length of 160 characters is also recommended for the future.
> There is only the possibility to manipulate the JLayout textarea.php, but not in a flexible way.

> [coolcat-creations](https://github.com/coolcat-creations):
> Thats not good, there are different recommendations for the desc and the administrator should be able to set an own limit or disable the limit. Last year there were even recommendations for 270 chars

**Comment by bembelimen** [comment]
Some thoughts:
- I guess best would be to remove the character limit temporary from the field till "short and sweet" is enhanced => someone's up for a PR?
- Joomla itself supports data attributes, so when "short and sweet" is enhanced, it's a one liner to add the new function
- The enhancement of "short and sweet" looks rather easy, just a second check the data attribute, shouldn't be that hard to pay someone to improve it.

**Comment by progreccor** [comment]
yes, we need to remove this hard limit - not only Google use this field - we have others Search engines

**Comment by Mich-es** [comment]
Any news on this? Because this hard limit is since a few days ago simply disastrous - with Google and other search engines. There is NO limit so why in Joomla? Please remove or remodel sensibly - thank you very much!

**Comment by theigloo** [comment]
Hi I just found this thread when searching for a solution to this.

So I agree the limit should be removed, plus all my old metas from my j3 site are now cut off at 160 in the <head> there are thousands of them, so I'm not even gonna try to re write them.

I think it should be up to the user how long the descriptions are



thanks

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36939">issues.joomla.org/tracker/joomla-cms/36939</a>.</sub>

**Comment by theigloo** [comment]
Sorry this is incorrect "**plus all my old metas from my j3 site are now cut off**"

old metas are ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36939">issues.joomla.org/tracker/joomla-cms/36939</a>.</sub>

**Comment by simbus82** [comment]
Dear [Joomla! Optimisation Team (JOT)](https://volunteers.joomla.org/teams/seo-team) (@weeblr and @agerix), could you push a little about this problem?

**Comment by weeblr** [comment]
@simbus82 That team has been dismantled a while ago. It was actually not meant to work on Joomla itself but on improving the Joomla websites SEO.

**Comment by weeblr** [comment]
My take on this would just be to remove the counter, it serves no purpose really.

**Comment by Mich-es** [comment]
@weeblr Thanks for the feedback, but not only the counter but the whole restriction should be removed. That would be a real improvement. I just hope that the old data will then all still work correctly

**Comment by weeblr** [comment]
@Mich-es I likely read too quickly as I was under the impression the javascript character counter was the one restricting description length. Description is not limited in the database storage, so it has to be a "soft" limitation.

**Comment by weeblr** [comment]
Ah no, there's also a max-length on the field definition. So indeed removing that restriction is a very quick and simple change, only a few lines to change in a few XML files

**Comment by pakimov** [comment]
I agree the limit should be removed.

**Comment by weeblr** [comment]
Hi

I made [a PR](https://github.com/joomla/joomla-cms/pull/39598) for this.

**Comment by pcombet-adosis** [comment]
> Hi
> 
> I made [a PR](https://github.com/joomla/joomla-cms/pull/39598) for this.

@weeblr Thank for your input and your help to have this issue resolved in the next J! versions.
Philippe

**Comment by alex-90-rus** [comment]
I support, the restriction should be removed.

**Comment by djandressolano** [comment]
I have 15 years working in website and mostly in SEO, we did many many multiple tests, and had great results with bigger meta descriptions also in the tests we saw big meta descriptions did not created any problem with Google, is the same with the Title of the pages, we have a top # 1 site in google for over 8 years and page have a very big title and meta description and we saw that any site can't rank better just because of this. 

So Joomla need to remove the meta description limit now!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36939">issues.joomla.org/tracker/joomla-cms/36939</a>.</sub>

**Comment by djandressolano** [comment]
What we did is change the meta description in the configuration.php then you can check in the page source code.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36939">issues.joomla.org/tracker/joomla-cms/36939</a>.</sub>

**Comment by V1nc3nt79** [comment]
Dear @Joomla! Optimisation Team (JOT) (@weeblr and @agerix) -> july 2023, still nothing ????? Do you know what SEO is ? 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36939">issues.joomla.org/tracker/joomla-cms/36939</a>.</sub>

**Comment by Mich-es** [comment]
SUGGESTION - the 160 characters stay gray as long as you are under 160 characters. Anything beyond that changes the 160 characters to red font, but you can still save it and it will be accepted that way. It is then up to the user what he does and what not.

Google recently had a 120 character limit and also Google takes the appropriate test from the meta that matches the search query and limits that to 160 characters. There can and may be more in there.

    There's no limit on how long a meta description can be, but the snippet is truncated in Google Search results as needed, typically to fit the device width. https://developers.google.com/search/docs/appearance/snippet


It is therefore absurd for a CMS to impose a hard limit! Please think about it again. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36939">issues.joomla.org/tracker/joomla-cms/36939</a>.</sub>

**Comment by pcombet-adosis** [comment]
@obuisard Olivier bonjour, je profite de tes nouvelles fonctions au sein de Joomla Dev Team pour remettre sur le tapis ce probleme sur Joomla qui handicap les fonctionnalités SEO de Joomla. Peux-tu regarder pour faire quelque chose avec ton equipe ?! Merci, Philippe (present aux Joomla Days FR 2023 pour lesquels tu es intervenu en direct LIVE from New York ;-)

**Comment by obuisard** [comment]
Bonjour Philippe @pcombet-adosis, I have gone through the conversations found in here and the PR that had been created by Yannick @weeblr. I totally understand the problem that was brought up. 

The PR from Yannick was addressing the max length issue but by doing so was removing the letter count from the meta fields.
We need a solution that keeps the letter count with the allowance to go over the count (so that we don't remove the useful char counter). 

Right now, the script that handles the char counter cannot go over the maxlength attribute. maxlength is a standard attribute for the 'input' element. 

For the use case described in here to work, we would need to remove the maxLength attribute from the XML forms with the meta field but keep charcounter set to 'true'. That would also require the addition of a non-standard attribute (softMaxLength for instance, showing as data-softmaxlength in the input field) that the charcounter script could pick up and use for the char count. The charcounter script would use that value rather than the standard maxlength, which will be missing here. So basically, at this point, we have an input field that is not bound to a max length, but still have a counter that is bound. We could have the char count message become red as soon as the count reaches negative values.

This involves:
- a modification of the script used for the char counter (no one stepped up for a modification as stated in https://github.com/rikschennink/short-and-sweet/issues/7).
- a modification of the textarea field (and text field, to keep features in sync) to accept the new attribute.

As I see it, the modifications need to be implemented into a 'feature' release (not the 4.3 branch).
We need someone to step up and implement the changes :-)
Any taker welcome.

**Comment by pcombet-adosis** [comment]
Thank you @obuisard for all these clarifications. I understand the explanations and the implications it entails. I am not a developer, so I won't be able to be part of the potential correctors for the solution to be implemented. I just support simbus82's request because, on a daily basis, we encounter this demand from our clients to go beyond 160 characters for SEO optimization. For your information, I would like to mention that a solution has been found to exceed 160 characters. It involves modifying the file \administrator\components\com_content\forms\article.xml, line 211. To learn more, please read the last remark on the page https://github.com/joomla/joomla-cms/pull/39598. Best regards to everyone! Philippe.
 @simbus82

**Comment by HLeithner** [comment]
As compromise I raised the limit to 300 as suggested by a bigger search engine. please give a try at #41795
