### ISSUE TITLE
HTMLHelper::calendar needs style updates

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#36933]
### What needs to be fixed
There are several bits about the resulting popup from HTMLHelper::calendar that feel very out of date and in need of some fixes.
![image](https://user-images.githubusercontent.com/32301627/152377119-6133e265-b462-425d-9921-68190af37ea3.png)

### Why this should be fixed
It unfortunately looks like it's been unchanged since Joomla! 2.5 despite having the brand new Bootstrap buttons in the footer

### How would you fix it
1. Make it so that the table `.calendar-container table` uses a `margin: auto` to center itself. I initially tried using a `width: 100%`, but that appears to conflict with someone else and ruins the entire layout.
![image](https://user-images.githubusercontent.com/32301627/152377715-a0847ec3-2c1c-408c-b47e-8f3b3b96c856.png)
2. Remove the class `.nav` from the td tag inside thead. There is a conflict of style where they are being forced to `display: flex`, affecting the alignment of their internal objects. If the class `.nav` is absolutely needed for something like a11y, a style override should be added to `calendar.css` that resets back to `display: table-cell`.
![image](https://user-images.githubusercontent.com/32301627/152378925-48fe6a88-8ede-4e9f-9b8b-8152dfb43236.png)
3. Stylize the time dropdown menu. It is completely unstyled currently, and sticks out compared to everything else. I added the classes `form-select` and `form-select-sm` to stylize and edited the html of that line to remove the empty td and redistribute that wasted space.
![image](https://user-images.githubusercontent.com/32301627/152380663-c4b64203-6317-427f-9bad-1d88f4e5c568.png)

### Side Effects expected
I don't forsee any negative side effects, but I'm sure someone more familiar than me would be able to correct me.

Why not do a PR myself? I literally can't figure out how to, and I don't seem to be smart enough to figure it out by myself.

**Comment by Quy** [comment]
Related #33447

**Comment by akshitrattan** [comment]
we can stylize the time dropdown menu by using the Bootstrap timepicker from the Bootstrap 4 datetimepicker library

**Comment by akshitrattan** [comment]
<img width="752" alt="Screenshot 2022-02-10 at 6 36 06 PM" src="https://user-images.githubusercontent.com/78909027/153414219-13a6b440-902e-4273-99c2-de31de90a009.png">
@dgrammatiko I made the changes for styling the time dropdown menu but the width ratios are getting messed up, if i make the dropdown very small I am not able to see its contents, I tried making changes in the `.calendar-container` class in calendar.css file to adjust the width of the entire calendar window but the changes don't work

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36995 . Thanks in advance.

**Comment by dgrammatiko** [comment]
@richard67 you close the wrong PR, this is valid

**Comment by cyrezdev** [comment]
@Chaosxmk @richard67 @akshitrattan i've opened a new PR, as this style problem is there since a long time, and not yet things done to get an accepted and merged fix for this display issue.

If you could have a look here: https://github.com/joomla/joomla-cms/pull/40761

Thanks! 👍
