### ISSUE TITLE
Joomla 4 API REST - Create User when there is a required field and Editable in 'Site' is selected

### ISSUE THREAD

**Issue by nbradshaw45** [joomla/joomla-cms#36936]
### Steps to reproduce the issue
Set a User->Field (Phone as an example) to 'Required'="yes", AND 'Editable In'="Site"

Create a user with REST API:
POST: {{base_url}}/{{base_path}}/users

BODY:
{"block":"0","email":"bob.smith@test.com","groups":["2"],"lastResetTime":"","lastvisitDate":"","name":"Bob Smith","params":{"admin_language":"","admin_style":"","editor":"","helpsite":"","language":"","timezone":""},"password":"qwerty1235%%##","password2":"qwerty1235%%##","registerDate":"","requireReset":"0","resetCount":"0","sendEmail":"0","username":"bobsmith"}

### Expected result
API should process User Create 
Since the Admin can create a user in the Admin interface without being required to enter a value in a required field WHEN 'Editable In'="Site" - I would expect that the Super User can create the user via REST API with the same conditions.

### Actual result
Create User via REST API Fails:

JSON Response:
{
    "errors": [
        {
            "title": "Invalid field: phone"
        }
    ]
}

### System information (as much as possible)
Joomla 4.0.6

**Comment by alikon** [comment]
please test #37030

**Comment by nbradshaw45** [comment]
This has tested good.

**Comment by alikon** [comment]
Could you please mark your test result in the issue tracker by going to this page https://issues.joomla.org/tracker/joomla-cms/37030 , using the blue "Test this" button at the top left corner, selecting the test result ("Tested successfully" in this case) and then submit? Thanks in advance.

p.s
it will need  2 test to be marked RTC (Ready To Commit) and then evaluated for merge from Release Lead
