### ISSUE TITLE
Variables $title and $content are initialised twice in module layouts\joomla\content\emptystate.php

### ISSUE THREAD

**Issue by phunsoft** [joomla/joomla-cms#36935]
### What needs to be fixed

At the beginning of file layouts\joomla\content\emptystate.php, some variables are initialized. Variables $title and $content are initialised twice. See below. Although this doesn't have any impact, it should be fixed.

$formURL    = $displayData['formURL'] ?? '';
$createURL  = $displayData['createURL'] ?? '';
$helpURL    = $displayData['helpURL'] ?? '';
$title      = $displayData['title'] ?? Text::_($textPrefix . '_EMPTYSTATE_TITLE');                   <<<==========
$content    = $displayData['content'] ?? Text::_($textPrefix . '_EMPTYSTATE_CONTENT'); <<<==========
$icon       = $displayData['icon'] ?? 'icon-copy article';
$append     = $displayData['formAppend'] ?? '';
$title      = $displayData['title'] ?? Text::_($textPrefix . '_EMPTYSTATE_TITLE');                   <<<==========
$content    = $displayData['content'] ?? Text::_($textPrefix . '_EMPTYSTATE_CONTENT'); <<<==========
$btnadd     = $displayDat

### Why this should be fixed

Initialise any variable only once.

### How would you fix it

Delete the second initialisations

### Side Effects expected

None.

**Comment by Quy** [comment]
Please test #36937. Thanks.
