### ISSUE TITLE
Joomla 4.0.1-4.0.6 - Post API for article creation throws a 404 error

### ISSUE THREAD

**Issue by JulianR-HR** [joomla/joomla-cms#36931]
Hi,

as written in the subject, creating an article via the API with a POST on on the /content/article endpoint does not work.

### Steps to reproduce the issue

- Enable the API Authentication for a user which is allowed to create articles (superuser in my case)
- try to create an article:
** myurl.com/api/index.php/v1/content/article** with the following body:
{
    "alias": "my-article",
    "articletext": "My text",
    "catid": 64,
    "language": "*",
    "metadesc": "",
    "metakey": "",
    "title": "Here's an article",
    "condition": 1
}

### Expected result
Status 200

### Actual result
404 File not found

### System information (as much as possible)
PHP 7.4
Joomla 4.0.6

### Additional comments
GET-Requests against the API are working perfect.

**Comment by zero-24** [comment]
Please try to post against: /v1/content/articles (adding an "s" to article)

https://github.com/alexandreelise/j4x-api-collection/blob/master/j4x-api-complete-collection.postman_collection.json#L1509-L1535

**Comment by JulianR-HR** [comment]
I did, but then I receive the next error:

<code>
{
    "errors": [
        {
            "title": "Field required: Title\nField required: Category"
        }
    ]
}
</code>

I think this does still not work as it should...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36931">issues.joomla.org/tracker/joomla-cms/36931</a>.</sub>

**Comment by zero-24** [comment]
Well its the correct post URL for now. I have not implemented the API myself yet but you can have a look at the tests how it should work: https://github.com/joomla/joomla-cms/blob/4.1-dev/tests/Codeception/api/com_content/ContentCest.php

**Comment by Quy** [comment]
Please read the doc for required properties.  You are missing `catid`.
https://docs.joomla.org/J4.x:Joomla_Core_APIs#Create_Article

**Comment by JulianR-HR** [comment]
Hi Quy,

no, I don't forgot the <code>cadid</code>

Please check the screenshot.

![screen shot 2022-02-03 at 15 58 00](https://issues.joomla.org/uploads/1/c36ced29524e0f328a40911e3d035076.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36931">issues.joomla.org/tracker/joomla-cms/36931</a>.</sub>

**Comment by brianteeman** [comment]
@quy the catid is there - thats literaly a copy/paste from the link you shared,

What I dont know is if the user has a category with an id of 64 and if not would the request fail because of that

**Comment by JulianR-HR** [comment]
Hi @brianteeman - I used another canid as you might see in the screenshot. canid 11 is valid on my page.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36931">issues.joomla.org/tracker/joomla-cms/36931</a>.</sub>

**Comment by Quy** [comment]
Please enclose the value with double quotes: "Titel"

**Comment by Quy** [comment]
Closing as this is an entry error.
