### ISSUE TITLE
[4.1] Scheduled Tasks - Argument 1 passed must be of the type array  

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#36934]
> 0 Argument 1 passed to Joomla\Component\Scheduler\Administrator\Model\TaskModel::wildcardIfMatch() must be of the type array, null given, called in \administrator\components\com_scheduler\src\Model\TaskModel.php on line 672 

### Steps to reproduce the issue
Apply PR #36927.
Create a new task.
For the Execution Rule, select `Cron Expression (Advanced)`.
Leave selections empty under Cron Match.
Click Save button.

@ditsuke

**Comment by ditsuke** [comment]
For anyone taking a look at this issue, this is a starter issue I recommend. https://github.com/joomla/joomla-cms/pull/36927 has been merged now so we only need to work with `4.1-dev` for a fix; no need to apply the PR!

**Comment by ditsuke** [comment]
@Quy was this resolved?

**Comment by Quy** [comment]
See PR #https://github.com/joomla/joomla-cms/pull/37536
