### ISSUE TITLE
CustomField Type Media (media) > Hide Image Description and No Description Fields at Admin-Forms

### ISSUE THREAD

**Issue by BPBlueprint** [joomla/joomla-cms#36940]
When I use the Custom Field Type Media (media) there are three fields/formfields
1. image
2. Image Description (Alt Text)
3. No Description [Checkbox]

For sure Field 1 (image) is the one we always need.
But fields 2 (Image Description) and field 3 (No Description) are sometimes really disturbing, cause they take alot of space at the screen.

Especially when you use a Media CustomField at a subform.
In my yes this is quite user-unfriendly.

Maybe it is possible to have kinda dropdown-box at the custom field, where you can configure "Show Image Description YES/NO" and "Show No Description YES/NO"

@laoneo

**Comment by brianteeman** [comment]
No - they are extremely important fields and you always need them all

**Comment by HusiBT** [comment]
Well, I donot agree ... or I ask like this: WHY are those alyways needed?
If you see in my screenshots J3 vs J4 -> it is hard to explain to people, why they now have such really user-unfriendly forms to fill, when it was much easier bevor
![j3_having_alt-text_with_customfield-text](https://user-images.githubusercontent.com/34511344/152518111-bdea91d7-205c-4d9e-a142-0b0d08343870.JPG)
![j4_takes_soooooo_much_space_and_is_really_userunfriendly](https://user-images.githubusercontent.com/34511344/152518120-647cfe1f-bf8c-4214-bd3b-ae0417488e9d.JPG)
.

**Comment by ReLater** [comment]
That is one aspect of accessibility (a11y). An ALT text equals not always the visible description of images, e.g. in a `<figcaption>`. It can, but it doesn't have to.

I agree that the checkbox is useless overhead for most users. If the ALT attribute (= the ALT field) is empty than it has the same meaning as "just a decorative image". Why do we have to confirm that?

**Comment by brianteeman** [comment]
> I agree that the checkbox is useless overhead for most users. If the ALT attribute (= the ALT field) is empty than it has the same meaning as "just a decorative image". Why do we have to confirm that?

1. Because it should be a conscious decision to mark an image as only a decorative image. 
2. An image marked as decorative will have an alt of "". This means that you wont be "bothered" by an accessibility error.

**Comment by HusiBT** [comment]
But I think you agree, that using the way it is, is much more user-unfriendly than it could be (screenshots)?!
So maybe we need a solution for making it user-friendly to fill out the forms. Especially when you use a media-field withing a subform.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36940">issues.joomla.org/tracker/joomla-cms/36940</a>.</sub>

**Comment by HusiBT** [comment]
![screen shot 2022-02-07 at 12 18 17](https://issues.joomla.org/uploads/1/330285c8720c83948fc193cab8b209b5.png)![screen shot 2022-02-07 at 12 18 19](https://issues.joomla.org/uploads/1/942208621aabd8f04f5bbcc238684375.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36940">issues.joomla.org/tracker/joomla-cms/36940</a>.</sub>

**Comment by brianteeman** [comment]
For me this is the eexpected behaviour and should be closed.

**Comment by BPBlueprint** [comment]
3rd-Party Extension DPMedia now has an option to remove Accessebility Options :-) 
https://extensions.joomla.org/extension/dpmedia/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36940">issues.joomla.org/tracker/joomla-cms/36940</a>.</sub>

**Comment by BPBlueprint** [comment]
CAN BE CLOSED<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36940">issues.joomla.org/tracker/joomla-cms/36940</a>.</sub>

**Comment by brianteeman** [comment]
My 2c is that if any extension deliberately removes core accessibility functionality it should be removed from the JED
