### ISSUE TITLE
[4.0] [3.9] com_contact - custom fields-  category

### ISSUE THREAD

**Issue by angieradtke** [joomla/joomla-cms#36956]
### Steps to reproduce the issue

 I have two com_contact categories and assign different custom fields to these categories in the email form. 
This leads to  a mess in the frontend. The custom fields do not know to which category
they belong and when switching between the different contact forms,
the fields are alternately assigned to one or the other category.

The issue is located in:
components/com_contact/src/View/Contact/HtmlView.php
The form  is  displayed before the category is  assigned

```
 Line: 136 $this->form = $this->get('Form');
		.......
		// Add catid for selecting custom fields
		$data['catid'] = $item->catid;
```

Turn around  and it works like expected.

**Comment by brianteeman** [comment]
If you have the solution then please submit a pull request

**Comment by angieradtke** [comment]
@brianteeman  If it was that easy for me, I would do that. But it isn't.

**Comment by brianteeman** [comment]
I'm sure you are more than capable of doing it. Its really not hard for someone with your skills

**Comment by joomdonation** [comment]
I made PR https://github.com/joomla/joomla-cms/pull/35763 sometime ago to fix the issue with Joomla 4. It had some unsuccessful test but I could not see it myself. I will try to look at it again one more time.

**Comment by angieradtke** [comment]
I think you overestimate me

**Comment by brianteeman** [comment]
It is very easy and you should learn

![angie](https://user-images.githubusercontent.com/1296369/152785227-153e05df-3278-4343-8f2f-d7a4e0a506ba.gif)

**Comment by prakhar3062** [comment]
Can i work on this issue

**Comment by joomdonation** [comment]
@angieradtke Could you please test PR https://github.com/joomla/joomla-cms/pull/35763 ? It should address this issue. If it is success, we can backport the change to Joomla 3.10 if required.

**Comment by angieradtke** [comment]
@brianteeman  thanks for your advice. I always have probs to  sync my local branch  with my  branch om git and and this one with joomla current.   The issue is that I not often work on Joomla  and  my local branch is a lot behind the current Joomla one. So first I have to fetch upstream - and here the chaos starts. I talk to Niels , Hannes etc and they try to help me, but ...
 I try with git desktop and my php storm.  I remember svn " create patch"  and things happen.

**Comment by angieradtke** [comment]
@joomdonation 

Hi Tuan,
 your solution  is different from mine.
 I only change the order of the code  in the view.
 You are the php coder so I think your solution is the better one. But can you explain me  why.
 I will test now.

**Comment by brianteeman** [comment]
I'm sure they will have told you to always start on a new branch. That way you will never have the issue you refer to. Or for simple pr like this one just do it online as I showed.

**Comment by joomdonation** [comment]
@angieradtke In short, the code in view is not needed, so I removed. Normally, view should receive data from model to render/display. For some reasons, here in Contact view, we have strange code to manipulate the data and then pass it back to session for model to use to. It's not right (at least as I understand)

Your solution also solves the problem. But having these lines of code in view is unnecessary (and not right to me, too).

**Comment by angieradtke** [comment]
@joomdonation thank you
