### ISSUE TITLE
JLIB_INSTALLER_ERROR_PACK_UNINSTALL_NOT_PROPER

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#36959]
### Steps to reproduce the issue
JLIB_INSTALLER_ERROR_PACK_UNINSTALL_NOT_PROPER text is:
Package Uninstall: This extension may have already been uninstalled or might not have been **uninstall** properly: %s

Must it be:
Package Uninstall: This extension may have already been uninstalled or might not have been **installed** properly: %s
I do not know for sure if the last 'uninstall' must be 'uninstalled' or 'installed'

**Comment by chmst** [comment]
Maybe we could write something like "The unstinstall process found that there are missing files which could be a result of a uncomplete install or uninstall process" - something like that. So users know why the uninstaller fond an error? 

@quy @brianteeman  mative speakers needed ;)

**Comment by brianteeman** [comment]
Looking at the code this is in a function called `removeExtensionFiles` so I would simply correct the error in the message as follows

```
JLIB_INSTALLER_ERROR_PACK_UNINSTALL_NOT_PROPER=
"Package Uninstall: This extension may have already been uninstalled or might not have been uninstalled properly: %s"
```

**Comment by Quy** [comment]
Closing per #36969.
