### ISSUE TITLE
COM_CONTACT_EMAIL in default_address.php

### ISSUE THREAD

**Issue by dzandut** [joomla/joomla-cms#36957]
### Steps to reproduce the issue
Enable email display

### Expected result
The value of the language variable

### Actual result
language variable

### Additional comments
No required variable in language files
extra characters **">** at the end of the variable 
```
76 <span class="visually-hidden"><?php echo Text::_('COM_CONTACT_EMAIL'); ?>"></span>
```

**Comment by chmst** [comment]
I cannot replicate this with English language. Which language is it?

**Comment by brianteeman** [comment]
@chmst the code is clearly wrong as there is an extra " and there is no language string com_contact_email

**Comment by chmst** [comment]
my bad, was looking at the wrong place.

**Comment by dzandut** [comment]
I think that this is for any language, since this variable is not in English.

If I try to find the COM_CONTACT_EMAIL variable
it is not in more than one language file

Specifically, I checked, I did a variable search throughout the project. I have default English and German installed
```
76 <span class="visually-hidden"><?php echo Text::_('COM_CONTACT_EMAIL'); ?>"></span>
```
Located on the following path
components/com_contact/tmpl/contact/default_address.php

I think the variable should be in the file
language/en-GB/com_contact.ini
But she's not there as in other language files
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36957">issues.joomla.org/tracker/joomla-cms/36957</a>.</sub>

**Comment by prakhar3062** [comment]
Can i work on this issue, i will try to resolve to resolve the bug

**Comment by chmst** [comment]
Go for it :)

**Comment by prakhar3062** [comment]
I have made the pr

**Comment by alikon** [comment]
please test #36976
