### ISSUE TITLE
Unable to save article successfully, happens randomly in J4

### ISSUE THREAD

**Issue by joomla-admin** [joomla/joomla-cms#36955]
### Steps to reproduce the issue
Create an article. Type something in the content. Select save. Type "Edit" to return to enter edit mode for the same article. 
Type some words to update the article. Then select save. 
The system shall spin during saving process. 
Please note the duration of the spinning time. Instantly or 3~5 seconds.
Make sure your article is saved with new update.
If not, user will have to select "<--" (Back button) on the browser to return to the article in editor mode, and select save again.
The system shall save properly as the system shall spin longer during saving process.

### Expected result
System shall spin for a few seconds during saving process

### Actual result
Occasionally, system spin for one second and jump out of editor mode

### System information (as much as possible)
- Joomla 4 is hosted on Ubuntu 21.04
- This issue happens since the beginning of 4.0.x version. 
- The issue is NOT related to Editor (TinyMCE or JCE) or Browser (Google Chrome of MS Edge). 
- The bug may not happen in the first attempt. Try it for 10 times, you will definitely get one.
- To work around this bug, the user will need to use the browser back button (<--) to return to the page in which the article is in the edit mode and with the update. Select "Save" to save the article again. The article shall be saved for the second time.

### Additional comments
You may contact me at bkwchong@gmail.com, Bryan Chong.

**Comment by richard67** [comment]
Please give this issue a meaningful title.

**Comment by brianteeman** [comment]
> The bug may not happen in the first attempt. Try it for 10 times, you will definitely get one.

If that were true this would **not** be the first report

> Type some words to update the article. Then select save.

So clearly something is happening **onsave** that is causing the problem.

You didnt provide any system information as requested so its impossible to debug. You should look at all plugins that operate onsave/aftersave for example the smartsearch content plugin.

**Comment by joomla-admin** [comment]
System information
- using Ubuntu 20.04
- this issue also happens in Joomla 4.1
- please let me know what other system info you are looking for?

**Comment by bkwchong** [comment]
This issue retain in Joomla 4.1

**Comment by bkwchong** [comment]
> Please give this issue a meaningful title.

Done

**Comment by bkwchong** [comment]
> > The bug may not happen in the first attempt. Try it for 10 times, you will definitely get one.
> 
> If that were true this would **not** be the first report
> 
> > Type some words to update the article. Then select save.
> 
> So clearly something is happening **onsave** that is causing the problem.
> 
> You didnt provide any system information as requested so its impossible to debug. You should look at all plugins that operate onsave/aftersave for example the smartsearch content plugin.

I have updated system info. Let me know what other info do u need.

**Comment by brianteeman** [comment]
Please close as another issue was created #37106
