### ISSUE TITLE
[4.1 RC] Tinymce errors

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#36966]
### Steps to reproduce the issue
open an article for editing (or anything that uses tinymce)

### Expected result
No console errors

### Actual result
two errors

Failed to load resource: the server responded with a status of 404 ()  en.min.js

tinymce.min.js?340e0e78b1d2f447621cc11039d0f260:9 Failed to load language: en.min from url 

### Additional comments
It is correct that there is no en.min.js file in tinymce

The problem comes from either #35883 or #36112 - sorry out of time to debug today.

@bembelimen this really needs to be fixed before release

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/blob/bfa162411623a7093204b7aa80f6a18fb3f776a7/plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php#L171-L184

**Comment by dgrammatiko** [comment]
Change https://github.com/joomla/joomla-cms/blob/bfa162411623a7093204b7aa80f6a18fb3f776a7/plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php#L439

to 

```php
'language' => $langPrefix,
```

**Comment by brianteeman** [comment]
Closed as we have a PR
