### ISSUE TITLE
[4.0] The title of a loaded module is not visible.

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#36965]
### Steps to reproduce the issue

- Create a cutom module.
- Activate the title of this module.
- Load this module into an article with {loadposition ....): Article edit > CMS content > Module.

### Expected result

The title of the loaded module is visible. 

### Actual result

The title of the loaded module is NOT visible. 

### System information (as much as possible)

Joomla 4.0.6

### Additional comments

It does work in J3.10.5

**Comment by brianteeman** [comment]
its because the chrome "none" doesnt output the title _which i think is wrong_

**Comment by sandewt** [comment]
@brianteeman 

I see that the title can be made visible under the 'Module Style'.
By default the title should be visible, as you indicate.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36965">issues.joomla.org/tracker/joomla-cms/36965</a>.</sub>

**Comment by brianteeman** [comment]
its the same problem with the class 
For me all default module settings should exist even if the chrome is none

**Comment by brianteeman** [comment]
The official answer is that you should set the chrome in the module as when you insert a module into content there is no chrome to _inherit_.

![image](https://user-images.githubusercontent.com/1296369/152966260-626176a4-5201-480b-8279-da3dec0c0032.png)

You can also set the chrome when you insert the module into the content 
> Within content this plugin loads a Module by ID, Syntax: {loadmoduleid 1} or a Module by position, Syntax: {loadposition user1} or a Module by name, Syntax: {loadmodule mod_login}. Optionally can specify module style and for loadmodule a specific module by title, Syntax: {loadmodule mod_login,module title,style}.

**Comment by Fedik** [comment]
We have an option for that:
![Screenshot 2022-02-08_12-16](https://user-images.githubusercontent.com/1568198/152966957-76b50220-7c3b-4660-905f-44955cb49b6e.png)
But as I see it is sets for `xhtml` that not exist in J4, or I missed something (that probably a bug).


Or use `{loadposition position-name,html5}` then all be good. 

> its because the chrome "none" doesnt output the title which i think is wrong

To include "title" in to the module "content" output we need to change whole rendering API for Module, that we cannot do for J4.

**Comment by Fedik** [comment]
> It does work in J3.10.5

yeah, J3 has `xhtml` Chrome style,
so looks like a bug in the plugin configuration, the style field contains non existing chrome styles

**Comment by brianteeman** [comment]
YEah from what I can see the plugin is fubar

**Comment by altrasoluzione** [comment]
Hi, are there any news about this bug? Or are there any workarounds?
Thank you!

**Comment by Fedik** [comment]
Specify the style in the placeholder tag, eg `{loadposition position-name,html5}`

**Comment by altrasoluzione** [comment]
> Specify the style in the placeholder tag, eg `{loadposition position-name,html5}`

I hoped there was an alternative to replacing all instances of loadposition.
It's ok, I'll do it directly in the database.
Thank you Fedik!

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/36965#issuecomment-1032437931

**Comment by altrasoluzione** [comment]
> [#36965 (comment)](https://github.com/joomla/joomla-cms/issues/36965#issuecomment-1032437931)

Unfortunately it is not a global solution but an operation to do on every single module. I guess it is much easier to replace all {loadposition ...} in the sql export file. Isn't it?

Thank you!

**Comment by brianteeman** [comment]
yes you have to do it on the module but if you use the module multiple times then you would only do it once

**Comment by sandewt** [comment]
An additional problem is that an undesirable situation can easily arise, namely:
`<p>{loadposition test}</p`
This results eg in the following source code:
`<p><div>Some text....</div></p>`
A p-tag followed by a div-tag is undesirable.

Please your opinion.

**Comment by Fedik** [comment]
Please test #39839

**Comment by Fedik** [comment]
> An additional problem is that an undesirable situation can easily arise, namely:
> `<p>{loadposition test}</p>`

Ideally User should not place the placeholder inside P tag,
But that is default behavior of TinyMCE, I have no idea what can be done here from our side.
