### ISSUE TITLE
[4.x] - Titles for field groups, individual styling per field group in frontend view

### ISSUE THREAD

**Issue by pickeboe** [joomla/joomla-cms#36967]
### Problem

Custom fields and field groups are a great option to show standardized data in the articles. But the visual designability (with css) is not really good. The main problem is the lack of separate blocks per field group. I can create several field groups in the backend. That's great. But I can NOT use them in the frontend for styling reasons because they doesn't exist. That's bad. Instead of separat blocks there is a long ul list, that contains ALL fields - no matter which field group they come from.

### Solution

I would suggest the following:
a) field groups should be created - in the frontend html code - as individual lists: one list per field group.
b) each field group should contain it's own - individual - css class (e.g. this class could be created in the backend by the user)
c) the name of the field group should be - optionally - shown in the frontend. But, as far as I know, this is not possible at the moment.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36974 . Thanks in advance.
