### ISSUE TITLE
Add support for field groups when rendering custom fields in the frontend

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#36973]
### What needs to be fixed

When custom fields are rendered in the frontend (in an article page for instance), the fields are not grouped by the field groups they are member of. 
Grouping works perfectly in the admin console where, when a field is part of a group, it is shown in its own group tab.

### Why this should be fixed

To properly group fields in the frontend, as intended by the designer of the website.

### How would you fix it

Change the code for components/com_fields/layouts/fields/render.php to support the field groups 

### Side Effects expected

There will be no change for fields that are not grouped.
However, field groups will be skinnable and custom fields that are part of those groups will be properly organized.

The output now:

```
<ul class="fields-container">
    <li class="field-entry"> … </li>
    <li class="field-entry"> … </li>
</ul>
```

The new output:

```
<ul class="fields-container">
    <li class="field-entry"> … </li>
    <li class="field-entry"> … </li>
    <li class="field-group group_[group id]">
        <span id="group_[group id]">[group name]</span>
        <ul role="list" aria-labelledby="group_[group id]">
            <li class="field-entry"> … </li>
            <li class="field-entry"> … </li>
            <li class="field-entry"> … </li>
        </ul>
    </li>
</ul>
```

Following this proposal, I will propose a PR.

**Comment by richard67** [comment]
We close issues when we have a PR for it. As you are the author of the PR and the issue you could have closed this issue yourself.

**Comment by obuisard** [comment]
Thanks Richard, I did not know that.

**Comment by richard67** [comment]
Was this a duplicate to #36967 ?
