### ISSUE TITLE
[3.10.*] Add a plugin event to change the SQL query to get a list of records

### ISSUE THREAD

**Issue by motokraft** [joomla/joomla-cms#36978]
### Is your feature request related to a problem? Please describe.
In the [**ListModel**](https://github.com/joomla/joomla-cms/blob/eb70adcbe43425c557d8b7b05d847819f22b50b4/libraries/src/MVC/Model/ListModel.php) model class, there is a [**getListQuery**](https://github.com/joomla/joomla-cms/blob/eb70adcbe43425c557d8b7b05d847819f22b50b4/libraries/src/MVC/Model/ListModel.php#L213) function, I want to add a plugin event so that I can change the SQL query before execution.

### Describe the solution you'd like
Add a plugin event to the [**getItems**](https://github.com/joomla/joomla-cms/blob/eb70adcbe43425c557d8b7b05d847819f22b50b4/libraries/src/MVC/Model/ListModel.php#L180) function so that you can change the SQL query before execution

### Additional context
None

**Comment by prakhar3062** [comment]
Are you woking on it now

**Comment by motokraft** [comment]
> Are you woking on it now

Yes. I want to make a **pull request**

**Comment by Quy** [comment]
PR #36979
