### ISSUE TITLE
[4.0.6] Bugs in Smart Search -> Content Map section

### ISSUE THREAD

**Issue by Octopus2** [joomla/joomla-cms#36980]
### Steps to reproduce the issue

1. Create and publish a category with the title "invisible" in the backend.
2. Create and publish an article titled "Test" with any text in the category "invisible".
3. Go to Smart Search -> Content Map and disable publishing for the “invisible” category.

Bug 1:
Search for "Test" in the frontend.
The post will appear as a search result.

Bug 2:
In the backend, open the "Test" article again, edit it and save it.
Go to Smart Search -> Content Map: The unpublished category "invisible" has now been published again.

### Expected result

Bug 1:
Search for "test" in the frontend.
The article will NOT appear as a search result.

Bug 2:
In the backend, open the "Test" entry again, edit it and save it.
Go to Smart Search -> Content Map: The unpublished category "invisible" is still unpublished.

### System information (as much as possible)

Joomla 4.0.6 under php 7.4 / SP Pagebuilder 3.8.3 and Magnin-Temlate 1.0 from Joomshaper

### Additional comments

What it's all about and maybe I don't understand how it's implemented in Joomla: I want to publish articles in a category that will never be displayed in the search results. These are, for example, articles to confirm registration for a newsletter, etc.

**Comment by Hackwar** [comment]
Unpublishing Content Maps should not suppress search results. It just removes the option to filter your search results by this taxonomy. Simply said, Bug 1 works as expected. Regarding Bug 2 I will have to have a look.

**Comment by alexaf2000** [comment]
I'm also currently facing this issue. Both of them exactly as @Octopus2 said.

Also when deleting content from indexing, after update the article it does appear again in the search results.

**Comment by Hackwar** [comment]
Please take a look at #39961, which should fix all these issues. Closing as we have a PR.
