### ISSUE TITLE
Joomla 3.10.x - Administrator Mail is sent also to non-admins

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#36988]
### Steps to reproduce the issue
With this setting all Users who are registered, and have the "Receive System Mails" Flag on "Yes" (1) will receive an email notification that a new User registered on the Website

The Email which is sent out contains even the Greeting "Hello Administrator" 

<img width="530" alt="grafik" src="https://user-images.githubusercontent.com/828371/153384644-0152871c-adae-4a1c-be13-94c123aff08c.png">

### Expected result
When I set "Send Mail to Administrators" to yes, I expect that only users with Administration (ACL) rights will receive a mail.

### Actual result
All users who are flagged to receive system emails receive an email, greeting them as Administrator and informed about sensitive data (User Email Address and Name)

### System information (as much as possible)
Joomla 3.10.5

### Additional comments
1) Either the field **Send Mail to Administrators** has to be renamed to Send System Messages to all enabled users (or similar) or 
2) There needs to be an additional check to only send out this information only to the Administrator level.

**Comment by blueforce** [comment]
This is also the case in version 4.x
![Bildschirmfoto 2022-02-10 um 11 32 45](https://user-images.githubusercontent.com/1141234/153389159-f2ef5de6-a57e-4e20-bd30-a90ac4e06159.png)

**Comment by brianteeman** [comment]
>1. Either the field Send Mail to Administrators has to be renamed to Send System Messages to all enabled users (or similar) or
>2. There needs to be an additional check to only send out this information only to the Administrator level.

For me option 1 is just covering up the problem. 

As these emails always/often include links that require access to the admin interface then they should not be sent to a user who does not have the required acl access irrespective of the setting for this checkbox.

**Comment by Quy** [comment]
Closing per PR #36997.
