### ISSUE TITLE
[4.0] [3.10] E-Mail Cloak: part of the TLD will be truncated

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#36981]
### Steps to reproduce the issue
Reported by Joomla Forum: https://forum.joomla.de/thread/15298-email-adresse-mit-doppeltem-link-dargestellt/

### Actual result
Once the plugin is actived, part of the TLD will be truncated. Example:
<a href="mailto:office@some.international" base="">office@some.international</a>
becomes:
<a href="mailto:office@some.internatio" base="">office@some.internatio</a> 

### System information (as much as possible)
Joomla 4.0.6

### Additional comments
could be relevant:
```// Example: any@example.org```
        $searchEmail = '([\w\.\'\-\+]+\@(?:[a-z0-9\.\-]+\.)+(?:[a-zA-Z0-9\-]{2,10}))';

**Comment by brianteeman** [comment]
its the 2,10 part of the regex causing the truncation so it is simple to fix by increasing the number

**Comment by ChrisHoefliger** [comment]
I can confirm this issue, TLD 'international' seems to be a valid TLD. Increasing 2,10 to 2,13 does no longer truncate this TLD.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36981">issues.joomla.org/tracker/joomla-cms/36981</a>.</sub>

**Comment by ChristineWk** [comment]
@ChrisHoefliger Thanks for your investigation!
@brianteeman any PR possible? Thanks

**Comment by ChristineWk** [comment]
The bug fix should then also be in Joomla 3.10. This completely outdated RegEx is also used there.

There hasn't been a length limitation for a long time now except >= 1.

**Comment by brianteeman** [comment]
Anyone can submit a pull request

**Comment by richard67** [comment]
Closing as having a pull request. It is for 3.10 but can be merged up later. Please test #36986 . Thanks in advance.
