### ISSUE TITLE
scss depreciated warnings

### ISSUE THREAD

**Issue by HarshJaiswani** [joomla/joomla-cms#36991]
![Capture](https://user-images.githubusercontent.com/95242923/153405399-48e56924-39cd-45f8-ad31-ba8bc062d9a1.PNG)
### Steps to reproduce the issue

Hit "npm run build:css" you will observe some warnings appearing.

### Expected result

no warning should appear

### Actual result

warnings about depriciated scss occurs

**Comment by dgrammatiko** [comment]
https://github.com/joomla/joomla-cms/pull/36906

**Comment by HarshJaiswani** [comment]
@dgrammatiko is it still open and can i help fix it ?

**Comment by dgrammatiko** [comment]
I closed it but feel free to reopen it.
BTW the fix requires upgrading to FontAwesome v6 which is still beta atm, that's why I closed the PR in the first place

**Comment by HarshJaiswani** [comment]
@dgrammatiko yes there were some of that warnigns but some were also from build\media_source i have fixed them can i make a pull request of them ?

**Comment by brianteeman** [comment]
> I closed it but feel free to reopen it. BTW the fix requires upgrading to FontAwesome v6 which is still beta atm, that's why I closed the PR in the first place

not any more

**Comment by dgrammatiko** [comment]
@HarshJaiswani I restored my PR. I will update it later to remove the changes for choices.js as they already patched it there

**Comment by richard67** [comment]
Closing as having a pull request. Please test #36906 as soon as it has been updated by the change mentioned in the previous comment. Thanks in advance.

**Comment by richard67** [comment]
@HarshJaiswani @dgrammatiko Shall PR #36992 be closed in favour of #36906 ?
