### ISSUE TITLE
[4.0] Custom media field images and images in Images and Links tab do not display height, width, loading

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#37006]
### Steps to reproduce the issue
1. Add an image to an article via the Images and Links tab
2. Create a custom field of type Media then add an image via that field to an article
3. Inspect the result on the front end

### Expected result
There should be 'height' and 'width' attributes as well as ```loading="lazy"```

### Actual result
There are no 'height' and 'width' attributes or ```loading="lazy"```

### System information (as much as possible)
J4.0.6

### Additional comments
In the /plugins/fields/media/tmpl/media.php file lines 33 to 50 are:

```
if ($img->attributes['width'] > 0 && $img->attributes['height'] > 0)
	{
		$buffer = sprintf('<img loading="lazy" width="%s" height="%s" src="%s"%s%s>',
			$img->attributes['width'],
			$img->attributes['height'],
			$imgUrl,
			$class,
			$alt
		);
	}
	else
	{
		$buffer = sprintf('<img src="%s"%s%s>',
			$imgUrl,
			$class,
			$alt
		);
	}
```

with line 35 looking for width and height. But it's obviously not picking those attributes up. Why? If an image is added to an article in the editor, all three attributes are added, so the data is obviously available.

**Comment by dgrammatiko** [comment]
Please test #37008
