### ISSUE TITLE
[J4] All Menu Items  Check In

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#37004]
### Steps to reproduce the issue

In Joomla 4 Administrator got to Menus / All Menu Items (I have 5 items)
Select All
In Actions select Chck-in

### Expected result

Something sensible

### Actual result

An error has occurred.
![screen shot 2022-02-11 at 14 17 49](https://issues.joomla.org/uploads/1/5355134ff8c180ac04a8766e7f8f499c.png)

### System information (as much as possible)

Reported in the Forum and confirmed by me on localhost
Mac OSX / Apache / PHP 8.0

**Comment by alikon** [comment]
please test #37005
