### ISSUE TITLE
Date format in calendar field

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#37000]
hello i have strange problem with calendar custom field ...

1 i create one date field no specific configuration

2 but date isn't good in backend and i didn't find where in can change format ...

3 if user set a date via selector that display 10-02-2022 for  10 feb 2022 (french format) that display in front 2 october 2022
I didn't think its an output problem because if is set 24-02-2022  (24 feb 2022)
in front it crashed because systeme think month number 24 that doesn't exist .... 

Some body can confirm ? 
Bug config problem ? 

![2022-02-10_11h20_08](https://user-images.githubusercontent.com/2539440/153555916-7cc14b48-ebe4-4923-a33a-539ff5930f5f.png)
![2022-02-10_11h20_41](https://user-images.githubusercontent.com/2539440/153555919-5807411f-9f78-450e-a099-71257494be49.png)
![2022-02-10_11h21_48](https://user-images.githubusercontent.com/2539440/153555922-bd4c92ba-18e5-4ded-be7e-ae1fe5d51f75.png)

**Comment by richard67** [comment]
@Fedik Any idea?

**Comment by Bakual** [comment]
Which version of the language pack are you using?
The format is converted using four language strings provided by the language pack. You may want to check those:
````
DATE_FORMAT_CALENDAR_DATE="%d-%m-%Y"
DATE_FORMAT_CALENDAR_DATETIME="%d-%m-%Y %H:%M:%S"
DATE_FORMAT_FILTER_DATE="d-m-Y"
DATE_FORMAT_FILTER_DATETIME="d-m-Y H:i:s"
````
These are taken from the official pack from https://downloads.joomla.org/de/language-packs/translations-joomla4/downloads/joomla4-french/4-0-6-1 and look correct.

Can you also check what is stored in the database? Should be in the english format (2022-02-10)

**Comment by Fedik** [comment]
It as @Bakual  said.

Use default system format for your language.
There not only "calendar format", but also "format for filter", that must be in sync.

If you changing "calendar format" you also must change "format for filter".

**Comment by micker** [comment]
hello
1 i update language to last package
2 i update any item to 31/02/2022
![image](https://user-images.githubusercontent.com/2539440/153596291-2bd2e0a4-34f4-46a4-8fb1-e1c062e8a26f.png)
when i load item
![image](https://user-images.githubusercontent.com/2539440/153596381-908bc0e3-a9dc-40bf-b8ee-5e18a79dee7a.png)
to load my code i use this
`echo HtmlHelper::date($this->item->arbitrary_property_name['date-de-parution']->value, Text::_('DATE_FORMAT_LC3'));`
3 format of date in database 2020-01-31 14:03:03

if is set this
![image](https://user-images.githubusercontent.com/2539440/153597192-c250ee37-9a6e-443f-b6ef-3b8de8f964ff.png)
display works but wrong date
![image](https://user-images.githubusercontent.com/2539440/153597287-e3c7b6dd-b89b-46e2-b1dd-7e7dea2c3e03.png)

**Comment by Fedik** [comment]
Please post what value for this language constants on your admin/site:
```
DATE_FORMAT_CALENDAR_DATE
DATE_FORMAT_CALENDAR_DATETIME
DATE_FORMAT_FILTER_DATE
DATE_FORMAT_FILTER_DATETIME
```

You can try search them in language override

**Comment by micker** [comment]
DATE_FORMAT_CALENDAR_DATE = "%d-%m-%Y"
DATE_FORMAT_CALENDAR_DATETIME = "%d-%m-%Y %H:%M:%S"
DATE_FORMAT_FILTER_DATE ="d-m-Y"
DATE_FORMAT_FILTER_DATETIME = "d-m-Y H:i:s"
seems correct

**Comment by Fedik** [comment]
hm yes, strange then why it fail

**Comment by micker** [comment]
lol i take many time to find why item is failed ... lol 
tahnks for your help

**Comment by Fedik** [comment]
What value for `DATE_FORMAT_LC3`?
and what happen if you just do `echo HTMLHelper::_('date', $blablaDateValue)` (without use of format)?

**Comment by richard67** [comment]
What's the value of DATE_FORMAT_LC3? If you use that for creating your date, it has to be the ISO format?

**Comment by richard67** [comment]
It seems @Fedik and me just had the same idea. 😄

**Comment by Bakual** [comment]
Since the calendar field apparently stores the date correctly into the database in format YYYY-MM-DD, and the calendar field also correctly shows the date again, something must be wrong with your code to display the date in frontend.
I doubt the issue is the DATE_FORMAT_LC3 either, as that one should not create such issues when being wrong.

I rather suspect your `$this->item->arbitrary_property_name['date-de-parution']->value` doesn't hold the date as it is in the database but is already transformed to another format, which is why the date function then breaks.
This value has to be in the format YYYY-MM-DD.

**Comment by micker** [comment]
hello i think @Bakual you are right
this `<?php echo $this->item->arbitrary_property_name['date-de-parution']->value;?>` display 10/01/2020 that the good date ...
how i can format it on html output ? can i use joomla format ?

**Comment by Bakual** [comment]
Joomla always expects YYYY-MM-DD. The same as is stored in the database. So you need to check your code why the value is already localised. You probably already applied the date format on that property and now try to apply it a second time, which fails.

**Comment by micker** [comment]
ok thanks i close this thank for all
