### ISSUE TITLE
[3.10.5] Plugin System Redirect works with PHP 8.0, but no longer with PHP 8.1

### ISSUE THREAD

**Issue by 7at1blow** [joomla/joomla-cms#37015]
### Steps to reproduce the issue

Joomla 3.10.5
System-Redirect activated
Switch from PHP 8.0 to PHP 8.1

### Expected result

system redirect works

### Actual result

system redirect does not work
Browser shows: HTTP Error 500

### Additional comments

When I switch back to PHP 8.0 the plugin system redirect works fine again.

**Comment by zero-24** [comment]
Hi, can you please enable debug mode and set the error reporting (global configuration) to maximim and post the resulting stack trace for us? So we can see whats wrong there.

Thanks

**Comment by 7at1blow** [comment]
Mmmh, I don't dare this because it's a productive site. All that report would be published. Or is there a trick to get the report without it being published?

**Comment by ReLater** [comment]
Maybe related? https://github.com/joomla/joomla-cms/issues/37035

**Comment by Quy** [comment]
@7at1blow Please upgrade to the latest version and confirm if it is still an issue. Thanks.

**Comment by Quy** [comment]
Closing due to no response. Possibly fixed in #37074. Please upgrade and report if still an issue. Thanks.
