### ISSUE TITLE
Created SCSS folder in Cassiopeia can not be compiled with external compiler

### ISSUE THREAD

**Issue by RickR2H** [joomla/joomla-cms#37011]
### Steps to reproduce the issue
1. Install Joomla 4.1 using the nightly build version
2. Go to the created folder media\templates\site\cassiopeia\scss and try to build the CSS with NPM or VScode.
3. The build will fail because of wrong source paths in some of the SCSS files

Looks like the same problems with the Atum template in PR: https://github.com/joomla/joomla-cms/pull/36879

Solution is to change the paths to the vendor and system folders in the scss/template.scss, scss/tools/_tools.scss and scss/offline.scss

The build script needs to be changed to handle the updates paths.

@dgt41 could you take a look?

**Comment by dgrammatiko** [comment]
there's a pr: https://github.com/joomla/joomla-cms/pull/36879

**Comment by dgrammatiko** [comment]
> Looks like the same problems with the Atum template in PR: https://github.com/joomla/joomla-cms/pull/36879

Did you try it? Did you run `npm install` after applying that PR?

**Comment by RickR2H** [comment]
The PR works! But that is only for compiling SCSS in a development environment when the build folder is present. I'm talking about a live site with the build media folder. So, download and install a regular Joomla 4.1 installation. Then try to compile the SCSS files in media/templates/site/cassiopeia with a tool of your choice. then you get:

{
  "status": 1,
  "file": "E:/wamp64/www/j41development/media/templates/site/cassiopeia/scss/tools/_tools.scss",
  "line": 2,
  "column": 1,
  "message": "File to import not found or unreadable: ../../../../vendor/bootstrap/scss/functions.",
  "formatted": "Error: File to import not found or unreadable: ../../../../vendor/bootstrap/scss/functions.\n        on line 2 of scss/tools/_tools.scss\n        from line 5 of scss/template.scss\n>> @import \"../../../../vendor/bootstrap/scss/functions\";\r\n   ^\n"
}

The paths need to be one level up. From: ../../../../../media/vendor/bootstrap/scss/functions to ../../../../media/vendor/bootstrap/scss/functions. Then compiling works.

**Comment by dgrammatiko** [comment]
> The PR works! But that is only for compiling SCSS in a development environment when the build folder is present.


The pr is not merged for 4.1 so 4.1 will be broken.

**Comment by RickR2H** [comment]
Thanks @dgrammatiko 😉

**Comment by RickR2H** [comment]
Duplicate of #36872 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37011">issues.joomla.org/tracker/joomla-cms/37011</a>.</sub>
