### ISSUE TITLE
[4.2] Install Languages

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37018]
When working on the 4.2 branch its not possible to install any additional language as the manifests all say 
`<targetplatform name="joomla" version="4.[01]"/>`

@roland-d

**Comment by zero-24** [comment]
PR has been created here: https://github.com/joomla-extensions/pkg_languagepack/pull/97

I would say we can close here or do you want to wait for it to be deployed?

**Comment by brianteeman** [comment]
Thanks - I will close it when its deployed and the issue is solved
