### ISSUE TITLE
Escaped single quotes in language file

### ISSUE THREAD

**Issue by dyfrig** [joomla/joomla-cms#37024]
### Steps to reproduce the issue

The file plg_system_jooa11y.ini has escaped single quotes \' in 3 lines :
Line 63: PLG_SYSTEM_JOOA11Y_PANEL_STATUS_12="The item you are trying to view is not visible; it may be hidden or inside of an accordion or tab component. Here\'s a preview="
Line 83: PLG_SYSTEM_JOOA11Y_LINK_URL="Longer, less intelligible URLs used as link text might be difficult to listen to with assistive technology. In most cases, it is better to use human-readable text instead of the URL. Short URLs (such as a site\'s homepage) are okay."
Line 91: PLG_SYSTEM_JOOA11Y_NEW_TAB_WARNING="Link opens in a new tab or window without warning. Doing so can be disorienting, especially for people who have difficulty perceiving visual content. Secondly, it is not always a good practice to control someone\'s experience or make decisions for them. Indicate that the link opens in a new window within the link text."

Testing
Line 91 used as example
Set the accessibility test setting Links (Advanced) to on.
Insert a link into an article and set it to open in a new window e.g. <a href="https://www.joomla.com" target="_blank" rel="noopener">Test Link</a>
Save article and click on Accessibility Check
An accessibility warning appears next to the link.  Click on it

### Expected result

Text shown with correct apostrophe and escape character (backslash) not shown

### Actual result

Text shown with escape character![screen shot 2022-02-13 at 20 56 08](https://issues.joomla.org/uploads/1/8c1cb3cd86e4068c95070352df4ac49f.png)

**Comment by Webdongle** [comment]
Confirmed https://forum.joomla.org/viewtopic.php?p=3652428#p3652351https://forum.joomla.org/viewtopic.php?p=3652428#p3652351<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37024">issues.joomla.org/tracker/joomla-cms/37024</a>.</sub>

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37025 . Thanks in advance.
