### ISSUE TITLE
Blocked user indicator reversed

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#37026]
### Steps to reproduce the issue
Open user manager check blocked user setting at bottom
click to where its gray will show "blocked"

### Expected result
User is blocked on green

### Actual result
User is NOT blocked on green
![image](https://user-images.githubusercontent.com/1850089/153781434-26748204-9337-4205-a158-3532489ac771.png)
![image](https://user-images.githubusercontent.com/1850089/153781453-8a1be88c-de42-46e4-a292-a53823cbe139.png)

### System information (as much as possible)

4.0.6 release

**Comment by chmst** [comment]
https://github.com/joomla/joomla-cms/pull/21026  i gave up

**Comment by Quy** [comment]
In a new install, the label is `User Status` and not `Block this User`.

![37026](https://user-images.githubusercontent.com/368084/153916630-a45453c0-2017-474a-9d01-a2b996028a63.png)

**Comment by brianteeman** [comment]
@quy - I suspect that @N6REJ is using an en-US language pack and that language pack is once again faulty and out of date.  https://github.com/joomla/joomla-cms/discussions/37028

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/153919273-2f801f80-fc09-49f8-8176-554378590999.png)


Note that in just that one file there are strings in multiple languages!!

**Comment by brianteeman** [comment]
Can be closed as a bug in the US language pack

**Comment by particthistle** [comment]
Resolving now in Crowdin. Next en-US language pack (and some other packs also affected by what's been identified) will have this corrected.

Details on other items affected: https://github.com/joomla/core-translations/issues/185

**Comment by tecpromotion** [comment]
> Resolving now in Crowdin. Next en-US language pack (and some other packs also affected by what's been identified) will have this corrected.
> 
> Details on other items affected: [joomla/core-translations#185](https://github.com/joomla/core-translations/issues/185)

thanks @particthistle
