### ISSUE TITLE
[4.x] Banner Alias check only works sometimes

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37031]
The check to prevent more than one banner in the same category having the same alias fails on new banner but works on update banner

### Steps to reproduce the issue - Part 1
Create a banner with the name "test1"
Create a second banner with the name "test1"

### Expected result
First Banner saved. Second banner gives an error message about duplicate alias

### Actual result
Both banners saved with the same alias

### Steps to reproduce the issue - Part 2
Create a banner with the name "test2"
Create a second banner with the name "test2"
Create a banner category with the name "cat2"
Open each banner and save them in the "cat" category

### Expected result
First Banner saved. Second banner gives an error message about duplicate alias

### Actual result
First Banner saved. Second banner gives an error message about duplicate alias

**Comment by alikon** [comment]
please test #37056
