### ISSUE TITLE
please fix wrong label "page class" in menu - irritating

### ISSUE THREAD

**Issue by dozentis** [joomla/joomla-cms#37047]
### Steps to reproduce the issue
- open a menu item, type like _list of categories_
- move to tab _Page Display_
- type in your _Page Class_ and save 

### Actual result in HTML source code of page
`<div class="categories-listyourcssclassname list-group">`

### Additional comments
Page Class is a **Suffix** to the class _categories-list_ (like in module/advanced)

## My recommendation
Please change label of **Page Class** in _Menus: Edit Item_ to **Page Class Suffix**

**Comment by chmst** [comment]
Which Joomla version?

**Comment by brianteeman** [comment]
It's a bug!

It was changed to be a page class and not a suffix iirc and in the body tag its a page class 
eg `<body class="site com_content wrapper-static view-category no-layout no-task itemid-119 banana has-sidebar-right">`

But on the category list it is also being used (**_not sure if it is supposed to be as its not in category blog_**)
eg
```
<div class="com-content-category category-list">
<div class="content-categorybanana">
<h1>Category List</h1>
```

**Comment by brianteeman** [comment]
The "bug" is in C:\htdocs\joomla-cms\layouts\joomla\content\category_default.php

**Comment by dozentis** [comment]
Thanks for reply. 
So I see it has already been revised with Joomla 4 (3.x?), so we no longer have a suffix specification like formely in Modules/Advances?

I've checked some menu types.

Category blog  -> **issue**
`<div class="blogmycssclass">`

single article -> no issue
`<div class="article-details mycssclass" itemscope itemtype="https://schema.org/Article">`

Category list -> **issue**
`<div class="category-listmycssclass">`

List all tags  -> **issue**
`<div class="tag-categorymycssclass">`

I'll check some more on my demo site




<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37047">issues.joomla.org/tracker/joomla-cms/37047</a>.</sub>

**Comment by chmst** [comment]
Thanks for reporting! Yes it should not longer be a suffix but a class. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37047">issues.joomla.org/tracker/joomla-cms/37047</a>.</sub>

**Comment by dozentis** [comment]
List all Tags -> **issue**
`<div class="tag-categorymycssclass">`

In all users menu items like login e.g. **issue**
`<div class="loginmycssclass">`

also all contact menu items **issue**
`<div class="contact-categorymycssclass">`

I think nearly all layout files must be updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37047">issues.joomla.org/tracker/joomla-cms/37047</a>.</sub>

**Comment by brianteeman** [comment]
@dozentis can you confirm which version of joomla you are using as I only found a few and not some of the ones you listed in joomla 4

**Comment by dozentis** [comment]
> @dozentis can you confirm which version of joomla you are using as I only found a few and not some of the ones you listed in joomla 4

I was using 4.0.6 and updated to V4.1 and can confirm this, because I've checked every menu tpye today. Unfortunately the demo website is on localhost (Im lecture for joomla and wordpress) but tomorrow i can upload it if you need further investigations

**Comment by brianteeman** [comment]
I did a pull request for all the instances I could find. #37055 but I can not find anything for category blog

**Comment by dozentis** [comment]
> I did a pull request for all the instances I could find. #37055 but I can not find anything for category blog

![jom1-inspektor-front](https://user-images.githubusercontent.com/98828023/154229654-0d4b17c2-a9b3-42db-ab25-66f1804868a4.jpg)

![jom2-menuitemtype](https://user-images.githubusercontent.com/98828023/154229666-2e95ac13-47ec-4186-8af3-ac2da8b4e248.jpg)

![jom3-pagedisplay](https://user-images.githubusercontent.com/98828023/154229680-a7a9d123-01c2-4c11-a0ec-b17186810128.jpg)

**Comment by RickR2H** [comment]
@dozentis are you using the Cassiopeia template? Looks like the view is generated by SP page builder.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37047">issues.joomla.org/tracker/joomla-cms/37047</a>.</sub>

**Comment by dozentis** [comment]
> @dozentis are you using the Cassiopeia template? Looks like the view is generated by SP page builder.
> 
The page-builder wasn't used for this page (but now it's deactivated), only Helix Ultimate Template and I've switched back to Cassiopeia:

search mycssclass on category-blog page
### Cassiopeia - one result: looks good
`<body class="site com_content wrapper-static view-category layout-blog no-task itemid-111 mycssclass">`

### Helix Ultimate template - **two results** 🤔
`<body class="site helix-ultimate hu com-content view-category layout-blog task-none itemid-111 de-de ltr sticky-header layout-boxed offcanvas-init offcanvs-position-right mycssclass">`

and (surprise ❗) 
````
<main id="sp-component" class="col-lg-8 ">
.....
  | <div class="blogmycssclass">
  | <div class="page-header">
  | <h1>Immobilien 🏡 Anzeigen - privat und gewerblich✔</h1>

````

Now I see that I was in wrong line in screenshot/inspector. Didn't see before, that _mycssclass_ was used twice in `#body` and `#main` _(sorry for confusing you guys, but that was surprising, didn't expect the class on both elements)_ 
But anyway, I didn't expect too that the helix template changes code although I wasn't using their own page-title (they add a tab called page-title, see menu screenshot, but it's empty there)

**Comment by RickR2H** [comment]
@dozentis as long as the problem is not core Joomla or Cassiopeia template layout we can close the issue here. Agreed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37047">issues.joomla.org/tracker/joomla-cms/37047</a>.</sub>

**Comment by RickR2H** [comment]
Closing this issue as this is not a Joomla core problem.
