### ISSUE TITLE
[4.1] Tinymce strips span tags without class or id

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#37046]
### Steps to reproduce the issue
Create an article or custom module with some text containing two spans, one without a class and another with, e.g:
```
<div>This is some text. <span>This part has a span tag</span> and this doesn't.</div>
<div>This is some additional text. <span class="span">This part also has a span tag</span> and this doesn't.</div>
```
Save
Tinymce will revert back to the main editor
Toggle back to the code view
### Expected result
```
<div>This is some text. <span>This part has a span tag</span> and this doesn't.</div>
<div>This is some additional text. <span class="span">This part also has a span tag</span> and this doesn't.</div>
```
### Actual result
```
<div>This is some text. This part has a span tag and this doesn't.</div>
<div>This is some additional text. <span class="span">This part also has a span tag</span> and this doesn't.</div>
```

### System information (as much as possible)
J4.1.0 but I first noticed it yesterday with J.4.0.6

### Additional comments
This does not happen with JCE Editor

**Comment by brianteeman** [comment]
Tinymce is stripping the empty span as it does not consider them to be valid markup.

You have two options
1. In the tinymce plugin change the "use joomla text filter" to on
![image](https://user-images.githubusercontent.com/1296369/154048605-200f4ccf-8e66-4ab3-a639-eb90e6ccde56.png)


2. in the tinymce plugin add span to the list of extended valid elements
![image](https://user-images.githubusercontent.com/1296369/154048808-ff2948eb-df6a-4e71-9d44-78219452b538.png)

**Comment by Scrabble96** [comment]
> Tinymce is stripping the empty span as it does not consider them to be valid markup.
> 
> You have two options
> 
Thank you. You're right, of course. Although I can't see why 'span' isn't allowed by default.

**Comment by brianteeman** [comment]
Thats something to take up with tinyMCE ;)

If this is now resolved please close the issue.

**Comment by Fedik** [comment]
Closing because it is TinyMCE behavior.
