### ISSUE TITLE
Login menu item as default:  403 error on redirect logout to this menu item

### ISSUE THREAD

**Issue by sozzled** [joomla/joomla-cms#37042]
### Steps to reproduce the issue

See full discussion at https://forum.joomla.org/viewtopic.php?f=808&t=991877.  All the information is there.

### Expected result

Based on J! 3.10.5

![screen shot 2022-02-15 at 00 34 59](https://issues.joomla.org/uploads/1/597356f057a4849cd0b1545e313a3717.gif)

### Actual result

![screen shot 2022-02-15 at 00 35 19](https://issues.joomla.org/uploads/1/2673cfbfda0fc5ab54fcd8cddf730670.gif)

### System information (as much as possible)

J! 4.0.6, PHP 8.0.5, Cassiopeia frontend, Atum backend

### Additional comments

The user is not logged-out and the [guest only] menu item causes a 403 error.  Please read observations and comments from several forum users:  three people have confirmed this can be reproduced.

**Comment by prakhar3062** [comment]
I will check it and will try to improve

**Comment by sozzled** [comment]
This is pretty basic J!.  When someone clicks the logout menu item they should be (1) logged-out, then (2) redirected—if a redirection target is set—to wherever the site manager has defined the target.  This does not seem to be happening with J! 4._x_ which appears to reverse the sequence, i.e. (1) redirect to the target and then (2).  Under J! 4.x, if the user has no access to the redirected target—i.e. before the logout occurs—a 403 error is generated.

This did not happen with J! 2.5 or J! 3._x_.

I think this is a bug.

**Comment by brianteeman** [comment]
patience is a virtue ;)

As you know I have already confirmed that this is occurs when the home page is set to be com_users.

I have never done this before so I have no idea if it was ever possible.

**Comment by sozzled** [comment]
> I have never done this before so I have no idea if it was ever possible.

Demonstrated (with J! 3.0.6) in the animation above.

**Comment by sozzled** [comment]
I gave up, deleted the test site, and consider this matter closed.  It's been a waste of time trying to make this work.
