### ISSUE TITLE
[4.1] Can't find a download url

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37045]
As the title says. My dashboard says 4.1 is now available but the update component says no download url.

Tried multiple update channels

![image](https://user-images.githubusercontent.com/1296369/154039215-9b6b404c-985b-4b16-81ed-18467181f61e.png)

![image](https://user-images.githubusercontent.com/1296369/154039093-99e5d70b-3d81-46f2-8515-e0b3f78f4911.png)

**Comment by brianteeman** [comment]
corrected the screenshot

**Comment by zero-24** [comment]
What update server has been set? Update cache cleared?

**Comment by PhilETaylor** [comment]
Works for me.
<img width="1596" alt="Screenshot 2022-02-15 at 10 06 41" src="https://user-images.githubusercontent.com/400092/154039667-c5db5d0e-ed12-4e8d-ac89-9ab5f119ecc9.png">

**Comment by zero-24** [comment]
I have also just deployed an update that 4.1.0-whatever to 4.1.0 works too: https://github.com/joomla/update.joomla.org/commit/c5ce8168c514712990811bb1c5bd9830a128988d

It can takes a few minutes to de deployed worldwide

**Comment by brianteeman** [comment]
OK it does show it now. 

But it shouldnt show that an update is available if it cant find the url. Thats odd

**Comment by PhilETaylor** [comment]
Lets hope you have more luck with your upgrade than I did...
<img width="1598" alt="Screenshot 2022-02-15 at 10 14 36" src="https://user-images.githubusercontent.com/400092/154041006-bd56d398-068d-43c8-a3f7-cf475dd57a39.png">

**Comment by zero-24** [comment]
> OK it does show it now.

Great so we close here?

> But it shouldnt show that an update is available if it cant find the url. Thats odd

Yes I agree, The technical reason is that we use two files to provide the update and at this time it was not consistent now it is.

**Comment by zero-24** [comment]
> Lets hope you have more luck with your upgrade than I did...

What update did you try? @PhilETaylor ?

**Comment by brianteeman** [comment]
@PhilETaylor yes - no problem at all https://domorewithcore.com/

> Yes I agree, The technical reason is that we use two files to provide the update and at this time it was not consistent now it is.

If its now consistent and won't happen again then it can be closed.

**Comment by PhilETaylor** [comment]
4.0.0 to 4.1.0 - locally... but its dockerized - so lets blame docker for now until I debug why the /media/administrator/ folder is missing folders.

**Comment by PhilETaylor** [comment]
Just to confirm - running the same test, after a restart of docker for Mac, and the upgrade worked this time without losing files... docker for Mac can sometimes be, well, annoying, if not rebooted every few hours.

**Comment by zero-24** [comment]
Thanks for checking
