### ISSUE TITLE
Accessibility Checker Panel Status language constants do not cater for multiple plural forms

### ISSUE THREAD

**Issue by dyfrig** [joomla/joomla-cms#37053]
The system plugin Joomla Accessibility Checker needs to be changed so that the following language constants cater for languages with multiple plurals

PLG_SYSTEM_JOOA11Y_PANEL_STATUS_2="1 accessibility error and %(warningCount) warnings found."
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_3="%(errorCount) accessibility errors and 1 warning found."
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_4="%(errorCount) accessibility errors and %(warningCount) warnings found."
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_6="%(errorCount) accessibility errors found."
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_8="Please review %(warningCount) warnings."
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_10="%(warningCount) <span class=\"jooa11y-visually-hidden\">warnings found.</span>"
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_11="%(totalCount) <span class=\"jooa11y-visually-hidden\">total issues found.</span>"

**Comment by brianteeman** [comment]
I'm not sure if that is solvable. Could you create an issue on the jooa11y main tracker please https://github.com/joomla-projects/joomla-a11y-checker/issues

**Comment by Kostelano** [comment]
@dyfrig Make it easier. For example, how we did it for the Russian language, since we also have enough forms of pluralization.

https://github.com/JPathRu/localisation/blob/joomla-4/administrator/language/ru-RU/plg_system_jooa11y.ini#L51

**Comment by infograf768** [comment]
never use a `_figure="` when it is NOT a plural form!!!

Rather use for example
`PLG_SYSTEM_JOOA11Y_PANEL_2_STATUS="1 accessibility error and %(warningCount) warnings found."`

**Comment by dyfrig** [comment]
I would suggest combining Kostelano's and Infograf768's suggestions into to avoid both problems.  Not sure if it would work for all languages but it would for Welsh and, according to Kostelano for Russian.  This would result in something like

;Panel status
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_1_MESSAGE="Accessibility errors: 1, Warnings: 1"
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_10_MESSAGE="<span class=\"jooa11y-visually-hidden\">Warnings found:</span> %(warningCount)"
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_11_MESSAGE="<span class=\"jooa11y-visually-hidden\">total issues found:</span> %(totalCount)"
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_2_MESSAGE="Accessibility errors: 1, Warnings: %(warningCount)"
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_3_MESSAGE="Accessibility errors: %(errorCount), Warnings: 1"
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_4_MESSAGE="Accessibility errors: %(errorCount), Warnings: %(warningCount)"
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_5_MESSAGE="Accessibility errors: 1"
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_6_MESSAGE="Accessibility errors: %(errorCount)"
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_7_MESSAGE="Please review warning."
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_8_MESSAGE="Please review warnings [%(warningCount)]."
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_9_MESSAGE="No accessibility errors found."
PLG_SYSTEM_JOOA11Y_PANEL_STATUS_12_MESSAGE="The item you are trying to view is not visible; it may be hidden or inside of an accordion or tab component. Here's a preview="

**Comment by dyfrig** [comment]
> I'm not sure if that is solvable. Could you create an issue on the jooa11y main tracker please https://github.com/joomla-projects/joomla-a11y-checker/issues

Done https://github.com/joomla-projects/joomla-a11y-checker/issues/66

**Comment by brianteeman** [comment]
As this will require changes upstream first and as @dyfrig has created an issue there can this be closed here.

**Comment by dyfrig** [comment]
Closing the issue as the upstream includes both original issue and Infograf768's comments.
