### ISSUE TITLE
[4.1] TinyMCE unusable things: text moving, inserting images, drag&drop errors

### ISSUE THREAD

**Issue by simbus82** [joomla/joomla-cms#37054]
### Steps to reproduce the issue

Select some words or characters from a content and try to move in another place in the same content

### Expected result

Text is moved like in any other WSIWYG editor

### Actual result

TinyMCE activates the "drag&drop" mode, impossible to move block of text like in every WSIWYG editors

https://user-images.githubusercontent.com/1375730/154099070-f2d19fd8-6446-4e23-abbb-e4b323d1bf4c.mp4

**-------------------------------------**

### Steps to reproduce the issue

Try to add an image in an article from PC or from Joomla Media

### Expected result

Click on the Image button in TinyMCE, browse the pc or browse Joomla Media, add the image in the content.
Or drag&drop an image from PC folders.

### Actual result

Click on the Image button in TinyMCE, only an input field is present, can't select or uploads any media.
![image](https://user-images.githubusercontent.com/1375730/154098041-cbb1842c-625a-4ef8-aac0-4d930a046465.png)

Try a drag&drop, an error is shown without any information.
![image](https://user-images.githubusercontent.com/1375730/154097272-e63018e7-c8bc-4f4d-9aff-158304f88399.png)

**Comment by brianteeman** [comment]
Nothing new here.

**Comment by simbus82** [comment]
> Nothing new here.

I do not understand. Are there already other issues?
If there are already (for 4.0?), why does 4.1 still have these problems? They are release-blocking bugs for a cms.
To date TinyMCE is completely useless in this way, the insertion of images, after being able to write, is the second most important thing of an editor.

**Comment by brianteeman** [comment]
These _limitations_ exist for many years

**Comment by brianteeman** [comment]
1. Moving text
To be honest thats something I was surprised you can even do. I guess as a keyboard user I have always used cut and paste. The _problem_ is caused by the drag and drop image plugin conflicting

2. Inserting images
That is why we have the Media button in cms content.

3. Drag and Drop images
You can drag and drop them directly from your pc to the article. Not sure if I understand your problem here

**Comment by richard67** [comment]
> TinyMCE activates the "drag&drop" mode, impossible to move block of text like in every WSIWYG editors

Can you do that in Microsoft Word (if the text is not in a text box)? MS Word is a WYSIWYG editor, too.

**Comment by brianteeman** [comment]
@richard67 Yes you can and you can do it in default tinymce (I checked) but the image drag/drop conflicts with that **obviously**

**Comment by brianteeman** [comment]
You can also do it in tinymce if you disable drag/drop images

​​
![image](https://user-images.githubusercontent.com/1296369/154112599-905b40df-c8e3-485d-aeac-2dc9d4628cbb.png)


Its a users choice. Have something useful or comment about something thats not

**Comment by simbus82** [comment]
> To be honest thats something I was surprised you can even do. I guess as a keyboard user I have always used cut and paste.

When Copywriters make the layout or the content review often move chapters or paragraphs, you are in a phase where the mouse + keyboard is used a lot (ex. Select and ctrl + b to do a bold text)
But the same problem occurs when trying to move an image from one place to another in the content.
However, now this feature does not work and gives an error, this shoul be solved.

> > TinyMCE activates the "drag&drop" mode, impossible to move block of text like in every WSIWYG editors
> 
> Can you do that in Microsoft Word (if the text is not in a text box)? MS Word is a WYSIWYG editor, too.

Yes, in Word, in Notepad, in PHPStorm, in web text field, in every editor.
There is a conflict with Drag&Drop that start the "drag" even if we start from the editor itself, that is wrong.
Text drag&dropping doesn't require any plugin, is something that work in many browsers.

**Comment by simbus82** [comment]
> @richard67 Yes you can and you can do it in default tinymce (I checked) but the image drag/drop conflicts with that **obviously**

In JCE Editor i don't have this problem... i can move text with a drag, and the drag&drop works very well for many media.

https://user-images.githubusercontent.com/1375730/154123832-57b53afb-e69d-4068-b47d-02c535af1f71.mp4

> 2. Inserting images
>    That is why we have the Media button in cms content.

Wow, found it. It's a really bad idea to have two buttons that, for any users, do virtually the same things, and hide the only "usable" option inside a dropdown. :-(
![image](https://user-images.githubusercontent.com/1375730/154122361-949567a0-8671-4e98-8366-5f684c272eba.png)

> 3. Drag and Drop images
>    You can drag and drop them directly from your pc to the article. Not sure if I understand your problem here

I remember that was working. Now, i think we have a bug. I have this error after the "drop" of a simple jpg:
![image](https://user-images.githubusercontent.com/1375730/154123173-1fbb3530-331c-4974-bc91-2f19e0c1384a.png)

**Comment by richard67** [comment]
Shame on me I did not remember that Word feature 😊

**Comment by HLeithner** [comment]
I stumbled about this today and don't understand why this hasn't been escalated earlier... This has to be a bug in Joomla since https://www.tiny.cloud works with drag and drop and moving text and images around.
@dgrammatiko or @Fedik do you have a chance to look at this?

**Comment by brianteeman** [comment]
As stated already the reason is due to a conflict between the drag and drop image option and tinymce.

Its definitely a bug but its hardly a release blocker. Especiallyas it has been present since 4.0

**Comment by Fedik** [comment]
Please test #38900
