### ISSUE TITLE
Joomla 4.1 Media mime_type

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#37052]
### Steps to reproduce the issue
I encountered it for the first time. All settings are default I haven't played any (new installation).
Joomla 4.1. new installation. I click on the Media link from the menu and I see this warning.
`Property 'mime_type' of argument 'item' of event onFetchMediaItems has a wrong item. Valid: string`

Image: https://imgur.com/o4fDTtV

### System information (as much as possible)
PHP version: 8.0

**Comment by ghost** [comment]
I enabled fileinfo, no problem.

**Comment by ghost** [comment]
How do I activate?
1- Login to cPanel
2- Find or search PHP version
3- Find the fileinfo and tick the box and that's it.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37052">issues.joomla.org/tracker/joomla-cms/37052</a>.</sub>

**Comment by cebyrd** [comment]
How do we enable fileinfo without cPanel? I uploaded Joomla onto a school server. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37052">issues.joomla.org/tracker/joomla-cms/37052</a>.</sub>

**Comment by wojsmol** [comment]
@cebyrd Enabling fileinfo php extension requires changes to php configuration - contact school server administrator.

**Comment by micheleramazza** [comment]
On some server the module fileinfo is not available. Please add a support if the library is not found. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37052">issues.joomla.org/tracker/joomla-cms/37052</a>.</sub>

**Comment by gwillson2** [comment]
Despite not being at the technical level of the above users I had to find me own fix as none of the above worked for me. I had two J4 sites where I had ticked fileinfo in cPanel PHP Selector but in System Information Fileinfo showed up as no. So my settings were being ignored or overridden. I had success only after I went to my WHM and made server wide changes to my EasyApache4 settings. Then it worked. I have my own webserver not shared.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37052">issues.joomla.org/tracker/joomla-cms/37052</a>.</sub>

**Comment by Chris-Stevenson-NSWRA** [comment]
That worked for me, but strangely it took about 30 mins before it worked, not sure why. I immediately logged out and then back in and no good. Tried again 30mins later and it worked. Caching?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37052">issues.joomla.org/tracker/joomla-cms/37052</a>.</sub>

**Comment by williegagnon** [comment]
Enabling fileinfo worked here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37052">issues.joomla.org/tracker/joomla-cms/37052</a>.</sub>
