### ISSUE TITLE
[PHP 7.4.3] Class not found Error 0 - Joomla 4.1.0/4.0.6

### ISSUE THREAD

**Issue by EccoB** [joomla/joomla-cms#37058]
### Steps to reproduce the issue
I can only reproduce this on the Server of my hoster (alfahosting) which uses PHP 7.4.3 (more info about the PHP Version at https://pastebin.com/yLLBY6ZA ). Both, Ver. 4.1.0 and 4.0.6 showed the same behaviour. On my local setup (PHP 8) everything works fine.
* Upload the joomla files to the hoster
* Go through the installer (works flawlessly, entries in the DB are written)
* After installation go to backend or frontend

### Expected result
Seeing the backend/frontend

### Actual result
Red error page.
After turning on debug you get the stacktrace:
~~~
Class 'Joomla\Plugin\System\Debug\Storage\FileStorage' not found
Call stack
--
# | Function | Location
1 | () | JROOT/plugins/system/debug/debug.php:175
2 | PlgSystemDebug->__construct() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:242
3 | Joomla\CMS\Application\CMSApplication->loadPluginFromFilesystem() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:160
4 | Joomla\CMS\Application\CMSApplication->loadExtension() | JROOT/libraries/src/Extension/ExtensionManagerTrait.php:94
5 | Joomla\CMS\Application\CMSApplication->bootPlugin() | JROOT/libraries/src/Plugin/PluginHelper.php:236
6 | Joomla\CMS\Plugin\PluginHelper::import() | JROOT/libraries/src/Plugin/PluginHelper.php:194
7 | Joomla\CMS\Plugin\PluginHelper::importPlugin() | JROOT/libraries/src/Application/CMSApplication.php:742
8 | Joomla\CMS\Application\CMSApplication->initialiseApp() | JROOT/libraries/src/Application/SiteApplication.php:707
9 | Joomla\CMS\Application\SiteApplication->initialiseApp() | JROOT/libraries/src/Application/SiteApplication.php:222
10 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
11 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:63
12 | require_once() | JROOT/index.php:32
~~~

### System information (as much as possible)
PHP 7.4.3, MySQL Database
additional information: https://pastebin.com/yLLBY6ZA
I had the exact same issues with Joomla 4.1.0 and 4.0.6

### Additional comments
* I checked that file permissions are correct
* I checked that the corresponding files are not corrupted
* In ExtensionManagerTrait.php - loadPluginFromFilesystem(), I added printouts from the $path variable to verify the pathes to the files are ok - they are
* I checked in debug.php by adding a get_included_files() that the expected files are included
* I used class_exists("FileStorage") in debug.php to check if it finds the class, but it does not
* I tried to change in line 175 in debug.php: FileStorage($storagePath) to Joomla\Plugin\System\Debug\Storage\FileStorage($storagePath) -> no change

Any hint is welcome to trace that down.

**Comment by ReLater** [comment]
> Upload the joomla files to the hoster

Did you also check that all files where transferred? The number of allowed simultaneous connections differ from hoster to hoster when you use FTP.

**Comment by brianteeman** [comment]
Go to administrator/cache and delete the file autoload_psr4.php
Reload the web page and the file will be recreated
That should resolve the problem.

If it does not please open the file autoload_psr4.php and verify that it has the following line
`	'Joomla\\Plugin\\System\\Debug\\' => [JPATH_PLUGINS . '/system/debug/src'],
`

**Comment by EccoB** [comment]
> Go to administrator/cache and delete the file autoload_psr4.php Reload the web page and the file will be recreated That should resolve the problem.
> 
> If it does not please open the file autoload_psr4.php and verify that it has the following line ` 'Joomla\\Plugin\\System\\Debug\\' => [JPATH_PLUGINS . '/system/debug/src'], `

Oh - deleting that in the cache did solve the issue indeed. I wonder if I or Joomla could have prevented that. Is it worth to document that? Thanks for your help!

**Comment by laoneo** [comment]
This should happen automatically on update.

**Comment by brianteeman** [comment]
This should be closed. Looks like it was just an error in the update

**Comment by EccoB** [comment]
Yes - Problem was solved by that. Thx
