### ISSUE TITLE
LDAP Login bug with Php8

### ISSUE THREAD

**Issue by gopalji** [joomla/joomla-cms#37060]
### Steps to reproduce the issue

LDAP Login to ActiveDirectory domain

error in ldapclient.php - isConnected() function: \is_resource($this->resource) returns error

### Expected result
true

### Actual result
error

### System information (as much as possible)

Latest Joomla 3.10.6
Php 8.1.2
Apache/2.4.37 (rocky) OpenSSL/1.1.1k

**Comment by gopalji** [comment]
No additional error available, the call to \is_resource($this->resource) simply returns false
Interestingly the first call to ldapbind() (ldap.php line 75ff) works, so the first call to isConnected() returns true, the next fails<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37060">issues.joomla.org/tracker/joomla-cms/37060</a>.</sub>

**Comment by zero-24** [comment]
Can you run a var_dump on `$this->resource` in that method?

**Comment by gopalji** [comment]
Seems somewhat strange,
if I run var_dump($this->resource) in this method, the result is null. So I ran var_dump($this->resource) once after the method returned true (which gave "object(LDAP\Connection)#512 (0) { } object(LDAP\Connection)#510 (0) { }")
and then after the method returned false (which gave "object(LDAP\Connection)#511 (0) { }")

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38750 . Thanks in advance.
