### ISSUE TITLE
[4.1] TinyMCE does not use non-en-GB languages

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#37061]
Tinymce does not use admin or site language

Uncaught ReferenceError: tinymce is not defined
    <anonymous> http://localhost:8888/joomla41/media/vendor/tinymce/langs/fr.min.js?e68e3c297f9f548ffc9fec71ecc6078b:1
[fr.min.js:1:1](http://localhost:8888/joomla41/media/vendor/tinymce/langs/fr.min.js?e68e3c297f9f548ffc9fec71ecc6078b)
    <anonymous> http://localhost:8888/joomla41/media/vendor/tinymce/langs/fr.min.js?e68e3c297f9f548ffc9fec71ecc6078b:1
    
   
<img width="588" alt="Screenshot 2022-02-16 at 11 32 07" src="https://user-images.githubusercontent.com/869724/154246591-22225b60-fb69-45a0-a8e5-21f3857b66b3.png">

**Comment by dgrammatiko** [comment]
Out of curiosity if you save the tinyMCE settings (in the plugin) it solves the problem?

**Comment by infograf768** [comment]
Nope. No change.

**Comment by dgrammatiko** [comment]
If you remove the language then save and then re select the French lang? Does that make any difference?

**Comment by brianteeman** [comment]
looks like the problem is with the autodetect language part as it works when set manually

![image](https://user-images.githubusercontent.com/1296369/154250906-fbe17dca-c183-4b2f-aa5b-259f10ae297e.png)

![image](https://user-images.githubusercontent.com/1296369/154250739-80bfb8f7-5864-493e-9596-b1863eb197df.png)

**Comment by dgrammatiko** [comment]
I think I can see why that is happening, for this mode we have to load the non min files

**Comment by infograf768** [comment]
tested setting it off, saving and then setting it on again.
No change. Using manual setting same result.

HINT: same issue in 4.0-dev of 3 weeks ago.

**Comment by infograf768** [comment]
interesting:

manual setting does work indeed when editing an article for example, but NOT in the tiny plugin editor.

**Comment by infograf768** [comment]
<img width="922" alt="Screenshot 2022-02-16 at 12 13 43" src="https://user-images.githubusercontent.com/869724/154253421-4bd2fba5-2e81-4611-8b04-e67dc44a3126.png">

Uncaught ReferenceError: tinymce is not defined
    <anonymous> http://localhost:8888/joomla41/media/vendor/tinymce/langs/fr.js?2ec79d5d7690c330f0817f1569b547a1:1

**Comment by dgrammatiko** [comment]
@infograf768 could you please change https://github.com/joomla/joomla-cms/blob/de15a4085b54821abdb9599870fb7a6147e08dbf/plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php#L171
to

```php
		if ((int) $levelParams->get('lang_mode', 1))
```

If that doesn't make any difference could you `var_dump($language->getTag());die;` after that if conditional? 

FWIW I cannot replicate this, so maybe describing what's the site setup might help, is it multilingual, what's the backend language, etc...

**Comment by brianteeman** [comment]
@dgrammatiko
I installed french in my test site. Set it to be the admin language
Then went to the tiny mce plugin and made the change to force usng french and saved
Then I open an article for editing and tinmyce is in french
Now I went back to the plugin settings (still in french) and the drag/drop area of the plugin configuration is in english.

I checked in Joomla 3 and it was in french then.

I got distracted so I didnt make a note of the console error message at the time. I will test again.

**Comment by brianteeman** [comment]
1. The autodetection of language is as you suspected related to the *.mn.js language file. That works perfectly in debug mode when using the non-minified language
2. The issue in the plugin itself is and the error is as JM reported.  Screenshot shows this.

![image](https://user-images.githubusercontent.com/1296369/154368095-54e7ca29-b7bd-40a4-b235-f43c802deef0.png)

3. Changing the trait to `if ((int) $levelParams->get('lang_mode', 1))` has no impact.

4. To fix the loading of the minified langauge file when using the editor  remove ` . (JDEBUG ? '' : '.min'` from line 175 and 179

5. A similar change to TinyMCEbuilderField.php will probably work for the plugin view.

**Comment by dgrammatiko** [comment]
Check https://github.com/joomla/joomla-cms/pull/37075 should fix the field part. The actual editor is working fine for me in article editing no matter if in debug or using different backend language

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/pull/37075 works for both issues for me.
Closing. Can be reopened if someone has still some issue.

**Comment by mmsarki** [comment]
tested, works very well thanks
