### ISSUE TITLE
[4.1] View languages installed uses a radio button where all other views have checkbox

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#37067]
### Steps to reproduce the issue
Go to system - languages installed 

![grafik](https://user-images.githubusercontent.com/1035262/154261226-baf95021-9c87-4057-9a4f-a570828fa0fb.png)

### Expected result

Checkbox as in all other views
![grafik](https://user-images.githubusercontent.com/1035262/154261355-e3741711-58d8-4658-a26f-ae3e7c5d241f.png)

### Actual result
see screen - a radio button

**Comment by brianteeman** [comment]
A radio button is correct.

On this screen you can only do one thing - make a language default and you can only make one language default to its a radio

**Comment by chmst** [comment]
Whether I can choose between different actions or have only one possible action for selected items makes no difference. 
This can happen also in other views, depending on access rights.

In menus, where we can set only one menuItem as "home", we also have checkboxes. As there are only two states possible "checked" or "not checked" and no alternatives are present, I think it is better when all screens are equal.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37067">issues.joomla.org/tracker/joomla-cms/37067</a>.</sub>

**Comment by brianteeman** [comment]
if it is possible to select multiple items then it must be a check box
If it is only possible to select one item then it must be a radio

Remember that when you select a radio then it unselects any previous selection.

**Comment by brianteeman** [comment]
> Ever since the first edition of Inside Macintosh in 1984, the rule has been the same for when to use checkboxes versus radio buttons. All subsequent GUI standards and the official W3C Web standards have included the same definition of these two controls:

> 1. Radio buttons are used when there is a list of two or more options that are mutually exclusive and the user must select exactly one choice. In other words, clicking a non-selected radio button will deselect whatever other button was previously selected in the list.

> 2. Checkboxes are used when there are lists of options and the user may select any number of choices, including zero, one, or several. In other words, each checkbox is independent of all other checkboxes in the list, so checking one box doesn't uncheck the others.

> 3. A stand-alone checkbox is used for a single option that the user can turn on or off.

Source NN Group

Radio and checkboxes also have inherent semantic meanings

**Comment by Quy** [comment]
Radio button is the  correct usage as only one should be selected to be the default. Otherwise, you will run into this issue:
https://github.com/joomla/joomla-cms/pull/24591

**Comment by Quy** [comment]
> In menus, where we can set only one menuItem as "home", we also have checkboxes. As there are only two states possible "checked" or "not checked" and no alternatives are present, I think it is better when all screens are equal.

Because there are other actions that will perform on multiple items. In this case, there is only one action `Default` on one item.
