### ISSUE TITLE
[4.1] breadscrumps does not display correctly

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#37076]
### Steps to reproduce the issue

Set the button Last to Hide.

### Expected result

The path of the breadcrumps is correct.

### Actual result

The path of the breadcrumps does NOT display correctly, when the button Last is set to Hide.

### System information (as much as possible)

J4.1

### Additional comments

![screen shot 2022-02-17 at 07 01 17](https://issues.joomla.org/uploads/1/39de00bce42901a86b552924c4013501.png)!
Button Last is set to Hide:
![Schermafbeelding 2022-02-17 075404](https://user-images.githubusercontent.com/9271775/154424031-cd2a9b14-afd1-4f82-8171-cbb73d48d2a7.png)
Button Last is set to Show (correct display):
![Schermafbeelding 2022-02-17 075218](https://user-images.githubusercontent.com/9271775/154424043-b9a548d3-571c-4c56-99d2-66ce43e8e738.png)

**Comment by drmenzelit** [comment]
I can confirm and on the homepage it is worse

![grafik](https://user-images.githubusercontent.com/9153168/154655432-633ef4ad-0a81-4a22-ac4d-4edc0d98c445.png)

**Comment by pippo8765** [comment]
line 67 prints breadcrumbs in \modules\mod_breadcrumbs\tmpl\default.php. It should not be there (comment it or delete), but in 2 upper places
Whole foreach loop just above that line should look like this:
```
// Generate the trail
foreach ($list as $key => $item) :
   if ($key !== $last_item_key) :
      if (!empty($item->link)) :
         $breadcrumbItem = HTMLHelper::_('link', Route::_($item->link), '<span>' . $item->name . '</span>', ['class' => 'pathway']);
      else :
         $breadcrumbItem = '<span>' . $item->name . '</span>';
      endif;
      echo '<li class="mod-breadcrumbs__item breadcrumb-item' . $class . '">' . $breadcrumbItem . '</li>';
      elseif ($show_last) :
      // Render last item if required.
         $breadcrumbItem = '<span>' . $item->name . '</span>';
         $class = ' active';
         echo '<li class="mod-breadcrumbs__item breadcrumb-item' . $class . '">' . $breadcrumbItem . '</li>';
      endif;
endforeach;
```
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37076">issues.joomla.org/tracker/joomla-cms/37076</a>.</sub>

**Comment by Quy** [comment]
@pippo8765 please submit a pull request.

**Comment by chmst** [comment]
Closing as there is a pull request. Please test  #3707

**Comment by chmst** [comment]
Sorry  @pippo8765  could you please make your PR against the dev 4.1-dev branch of the joomla-cms?

**Comment by sandewt** [comment]
@pippo8765

Maybe this will help you ? 

[https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests/en](https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests/en)

**Comment by pippo8765** [comment]
Yes, thank you, I tried posting request against J 4.1 branch, but seemed like I have no permissions to do that. Button is grayed. Also, didn't do much with git, so I'll go through your doc.
  
Thanks!
  

  

  
  
 -- S poštovanjem,/Kind regards, Filip Jovic M.Sc. E. E. JUNIS, University of Niš +381 18 257 085, lok: 152 st: Univezitetski trg 2 ------------------------------------------- +381 64 61 54 557 ***@***.***  

  
  
  
  
  
>

**Comment by sandewt** [comment]
>Also, didn't do much with git, so I'll go through your doc.

You don't need git. 

Look up the file in the desired J4.1 branch
All you need to do is cut and paste.

**Comment by wojsmol** [comment]
@pippo8765 You can simply go to https://github.com/joomla/joomla-cms/compare/4.1-dev...pippo8765:pippo8765-patch-1 fill out the PR template and submit it 😄

**Comment by pippo8765** [comment]
> @pippo8765
> 
> Maybe this will help you ?
> 
> https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests/en

Hi again, this above is exactly the process I used (seemed logical) and as stated in doc I ended up with new branch created, https://github.com/pippo8765/joomla-cms... Also I went through Pull Request form and filled it. So all went exactly as described in docs link. Now if someone is willing to instruct me what I did wrong :) I expected it to appear under https://github.com/joomla/joomla-cms/pulls but it did not happen :)
Thank you!

**Comment by sandewt** [comment]
@pippo8765 Maybe you can do something with this?

Creating a pull request:

- Switch to the branch that you want to create a pull request for. ...
- Click Create Pull Request. ...
- On GitHub, confirm that the branch in the base: drop-down menu is the branch where you want to merge your changes. ...
- Type a title and description for your pull request.

[https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/working-with-your-remote-repository-on-github-or-github-enterprise/creating-an-issue-or-pull-request)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37076">issues.joomla.org/tracker/joomla-cms/37076</a>.</sub>

**Comment by richard67** [comment]
Closing as having a pull request.

**Comment by sandewt** [comment]
Thanks @pippo8765 

PR #37282
