### ISSUE TITLE
Fix the multiselect of the template field. Please!

### ISSUE THREAD

**Issue by salitygen** [joomla/joomla-cms#37073]
Multivelection has become extremely inconvenient in the 4th version
--
That's how it was in the early versions
![old_version](https://user-images.githubusercontent.com/44565194/154355629-64974c97-ad5c-40c2-b234-3addf61b155c.jpg)

That's how it became
![new_version](https://user-images.githubusercontent.com/44565194/154356455-455b2e70-3bf4-4945-a423-d486fc04bfa5.jpg)

The set values of the fields have to be searched for a long time...

**Comment by chmst** [comment]
In which context have you found this? In a module? Backend? Frontend?

**Comment by salitygen** [comment]
Administrative interface, editing of material, custom fields, multiselect.

**Comment by chmst** [comment]
I tried a few multiselects but looks all good. 
![grafik](https://user-images.githubusercontent.com/1035262/154363536-19c82658-b672-44c1-9fa2-e8e0e1f12a84.png)
![grafik](https://user-images.githubusercontent.com/1035262/154363752-567ba4ee-c444-4727-9c59-dff3fc04a48f.png)

From which version to which version was your update?

**Comment by salitygen** [comment]
No, in Custom fields!

**Comment by salitygen** [comment]
![fields](https://user-images.githubusercontent.com/44565194/154364617-faaceeae-f80e-400f-9bac-b61474c55184.jpg)

**Comment by chmst** [comment]
ok thank you, now i know where it is. It is late today, but tomorrow ..

**Comment by brianteeman** [comment]
There is already a bug report for this @quy is the expert in finding them

**Comment by chmst** [comment]
I remembered this one https://github.com/joomla/joomla-cms/issues/30105 and https://github.com/joomla/joomla-cms/issues/28389

**Comment by Fedik** [comment]
Set the layout for the field to "Enhanced select":
![Screenshot 2022-02-19_13-12](https://user-images.githubusercontent.com/1568198/154798562-3ec1a875-b468-4711-a803-5faca6495704.png)
