### ISSUE TITLE
Select Category image cause logout

### ISSUE THREAD

**Issue by maxclee-tt** [joomla/joomla-cms#37071]
### Steps to reproduce the issue

create category 
in options select image 
upload 
you are logout 

### Expected result

add image to category 

### Actual result

logout 

### System information (as much as possible)

PHP Built On | Linux vl20530.dinaserver.com 4.9.0-0.bpo.17-amd64 #1 SMP Debian 4.9.290-1~deb8u1 (2021-12-23) x86_64
-- | --
mysql
5.7.37-log
latin1_swedish_ci
utf8mb4_general_ci
None
Yes
8.0.15
Apache
fpm-fcgi
Joomla! 4.1.0 Stable [ Kuamini ] 15-February-2022 09:30 GMT
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36

### Additional comments

I gues version php 7.4 doesn't cause this problem

**Comment by drmenzelit** [comment]
Can't reproduce on a local (xampp) installation
![grafik](https://user-images.githubusercontent.com/9153168/154657101-0bba28b6-5316-457f-ab0f-0e5211aab54b.png)

**Comment by chmst** [comment]
@maxclee-tt is this still an issue? I also cannot replicate your problem in the same environment. Could you add a screenshot or video? Are there special signs in the name of the image of folder?

**Comment by maxclee-tt** [comment]
Hi, thank you for interes 
yes I change version of php but problem continue 
actually ver. php8 
please check video >  
https://youtu.be/Gv5WbsQb_60

**Comment by chmst** [comment]
Thanks for your video. I cannot replicate it here, so we must investigate.

**Comment by brianteeman** [comment]
Is this happening whenever and wherever you upload an image or just for categories?

**Comment by maxclee-tt** [comment]
first;  thanks for helping me

@brianteeman 
1. photos have been uploaded via ftp 
2. concerns articles and categories

**Comment by brianteeman** [comment]
I strongly suspect that you are triggering a mod_security rule setup by your hosts. You should definitely speak to them and ask them to check the mod_security logs

**Comment by Quy** [comment]
Closing as a hosting issue.
