### ISSUE TITLE
error - Unknown column 

### ISSUE THREAD

**Issue by WillyMartin** [joomla/joomla-cms#37085]
### Steps to reproduce the issue
Press menu - 
/administrator/index.php?option=com_installer&view=discover

### Expected result
An error has occurred.

    1054 Unknown column 'system_data' in 'field list'
    JROOT\\libraries\joomla\database\driver\mysqli.php:668 

Call stack
# 	Function 	Location
1 	() 	JROOT\libraries\joomla\database\driver\mysqli.php:668
2 	JDatabaseDriverMysqli->execute() 	JROOT\libraries\joomla\database\driver.php:1421
3 	JDatabaseDriver->insertObject() 	JROOT\libraries\src\Table\Table.php:821
4 	Joomla\CMS\Table\Table->store() 	JROOT\administrator\components\com_installer\models\discover.php:170
5 	InstallerModelDiscover->discover() 	JROOT\administrator\components\com_installer\views\discover\view.html.php:35
6 	InstallerViewDiscover->display() 	JROOT\administrator\components\com_installer\controller.php:59
7 	InstallerController->display() 	JROOT\libraries\src\MVC\Controller\BaseController.php:702
8 	Joomla\CMS\MVC\Controller\BaseController->execute() 	JROOT\administrator\components\com_installer\installer.php:19
9 	require_once() 	JROOT\libraries\src\Component\ComponentHelper.php:402
10 	Joomla\CMS\Component\ComponentHelper::executeComponent() 	JROOT\libraries\src\Component\ComponentHelper.php:377
11 	Joomla\CMS\Component\ComponentHelper::renderComponent() 	JROOT\libraries\src\Application\AdministratorApplication.php:101
12 	Joomla\CMS\Application\AdministratorApplication->dispatch() 	JROOT\libraries\src\Application\AdministratorApplication.php:159
13 	Joomla\CMS\Application\AdministratorApplication->doExecute() 	JROOT\libraries\src\Application\CMSApplication.php:225
14 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT\administrator\index.php:51

**Comment by WillyMartin** [comment]
found a solution to the problem

ALTER TABLE tbl_extensions
add system_data MEDIUMTEXT COLLATE utf8mb4_unicode_ci NOT NULL;<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37085">issues.joomla.org/tracker/joomla-cms/37085</a>.</sub>

**Comment by Quy** [comment]
Please see #14750 for details of its removal.
