### ISSUE TITLE
Incomplete code display when editing a file using Firefox

### ISSUE THREAD

**Issue by mariantanase** [joomla/joomla-cms#37088]
### Steps to reproduce the issue
If you need to open a file in edit mode (e.g. index.php), on **Firefox** browser, the few left columns of code are hidden.
On other browsers, like Chrome, everything is ok.

### Actual result

![edit-mode-cassiopeia](https://user-images.githubusercontent.com/3976174/154670666-581fd44b-189d-47c6-882a-ba639f5cc8f7.png)

### System information (as much as possible)
Joomla 4.1.0
Firefox 97.0.1

**Comment by chmst** [comment]
I cannot replicate this effect, using the same firefox version as you.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37088">issues.joomla.org/tracker/joomla-cms/37088</a>.</sub>

**Comment by brianteeman** [comment]
You might have changed one of the settings in the codemirror plugin. ?

**Comment by mariantanase** [comment]
> You might have changed one of the settings in the codemirror plugin. ?

I didn't changed anything to **Editor - Code Mirror** plugin. Are the default settings.
Why is the behavior different from one browser to another?

**Comment by mariantanase** [comment]
Later edit: 
On a different PC, with the same Firefox version I do not experience any problems.
I need to investigate why it doesn't work on that PC
