### ISSUE TITLE
Joomla 4 Pre-Update warning improvement

### ISSUE THREAD

**Issue by kitepascal** [joomla/joomla-cms#37086]
### Problem identified
The forums and support channels are full of people crashing their live sites, upgrading from Joomla 3 to 4.
I think the message on top of the update process should be improved.

Current message:
**Warning**
Before you update Joomla, ensure that the installed extensions are available for the new Joomla version.
You are strongly advised to make a backup of your site's files and database before you start updating.

### Proposed solution
**Warning**
The Joomla 4.x update is not a simple one, depending on the complexity of the website.
It is highly recommended that you **do not perform this step on the live site** but in a test environment.
A copy of the live site can be set up very easily using *the most famous backup extension*:
$link_to_a_helpful_step_by_step_article

Before you update Joomla, ensure that the installed extensions are available for the new Joomla version.
You are strongly advised to make a backup of your site's files and database before you start updating.

### Open questions
What do you think about that?

#lessfrustration #nostress #bestpractices #helpfullinks

**Comment by zero-24** [comment]
Sounds like a good idea to me. I would not change the existing string but add a new message to 3.10 on "upgrades to the next major" updates only.
As 3.10-> 3.10 and 4.1->4.1 updates are not affected by this.

**Comment by chmst** [comment]
It is a issue of J3 and I suggest replacing 

> The Joomla 4.x update

Upgrading J3 to J4 can be a big step, ....

**Comment by kitepascal** [comment]
Thx!

**Updated solution:**

**Warning**
Upgrading J3 to J4 can be a big step, depending on the complexity of the website.
It is highly recommended that you **do not perform this step on the live site** but in a test environment.
A copy of the live site can be set up very easily using a **backup/restore extension** (linked to /administrator/index.php?option=com_installer&view=install#web).


..only in case of a major upgrade.

**Comment by kitepascal** [comment]
@brianteeman  May you please comment your thumb down?

My bank balance increases from broken live sites but the users involved in those accidents are not happy - so I think it is important to make things clearer for non-experts.

**Comment by brianteeman** [comment]
Better to spend the time improving the update process and mediate many of the known issues than to scare people away from ever updating

**Comment by kitepascal** [comment]
OK, good points. 

I see that as an improvement of the update process.
Nobody with extended knowledge does that major update on the live site, because there is always some manual work to do. 

The reason for my suggestion: Many people contact me in my (half-commercial) J! troubleshooting chat over the last few weeks because they crashed their live sites and don't even know how to successfully restore a backup.

That scares more imho and greenhorn's frustration regarding J4 live crashes could be minimized in that way.

**Comment by daniel-lenz** [comment]
Hello community,

there also should be a "pre-update-check" that checks for the richt filesystem permissions and a "post-update-check" that checks if all files have been installed correctly.

best regards,
Daniel

**Comment by kitepascal** [comment]
If the update fails, the post-update-check will not work ;-)
@ #37110 

The Pre-Update Warning should really be improved.

It's all documented already in a very attractive way in multiple languages, including Development Location and Akeeba Backup recommendation:
https://docs.joomla.org/Joomla_3.x_to_4.x_Step_by_Step_Migration

But users do not read/google the f****** manual beforehand to be prepared, so it should be part of the warnings straight away in backend, to protect unexperienced users from doing something wrong - make it almost impossible that they act around the already existing 5-🌟  documentation from official site.

Kind regards
Pascal

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
