### ISSUE TITLE
[4.1] com_scheduler Help links

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#37094]
### Steps to reproduce the issue

Go to System -> Manage -> Scheduled tasks and click the Help button

### Expected result

The title should be Scheduled Tasks

### Actual result

The title is JHELP COMPONENTS SCHEDULED TASKS MANAGER
Although I have asked for the link to redirect to a document with the correct title

### Additional comments

There are three instance of JHELP_COMPONENTS_SCHEDULED_TASKS_MANAGER in com_scheduler that need to be changed to Scheduled_Tasks

**Comment by niharikamahajan02** [comment]
I don't find the title named as JHELP COMPONENTS SCHEDULED TASKS MANAGER
![image](https://user-images.githubusercontent.com/72392580/154806910-fbfe9b5d-2bd3-491b-8cb5-fa89537a8803.png)

Will you attach a screenshot for that issue.

**Comment by ceford** [comment]
You don't see it in your screenshot because we have now created a redirection in JDocs. The string needs to be changed in com_scheduler/src/View/Select/HtmlView.php - the Help button right at the bottom. And likewise in Task/HtmlView.php and Tasks/HtmlView.php. With those changes in place we can remove the redirection. All other Help buttons now use the JDocs page name and not a translatable string.

**Comment by brianteeman** [comment]
and then you need to add a com_admin_help string so that the help toc can be created

**Comment by ceford** [comment]
@brianteeman - I am not clear about that. Can you clarify where that change is located? I have only just noticed that Task Scheduler is missing from the Joomla! Help list (to be honest, I have only just remembered that list exists). Is that a separate issue?

**Comment by brianteeman** [comment]
#36213 #36713

**Comment by niharikamahajan02** [comment]
Do you mean JHELP_COMPONENTS_SCHEDULED_TASKS_MANAGER has to be replaced to Scheduled_Tasks only and then we need to add  a com_admin_help string

**Comment by ceford** [comment]
@niharikamahajan02 - Yes, replace those three instances. I think the point raised by @brianteeman is a separate issue.

**Comment by Quy** [comment]
Closing per PR #36714.
