### ISSUE TITLE
J4.1 Nginx 502 bad gateway error on admin cpanel when debug enabled.

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#37090]
### Steps to reproduce the issue

Upgrade from 4.0.7 to 4.1

### Expected result

Working site front-end and back-end.

### Actual result

Front end works OK.
Cannot login into admin back-end get 502 error from Nginx
Manually edit configuration.php and disable debug.
Login OK and access admin pages, including com_cpanel.

Enable debug and save configuration OK.
Go back to com_cpanel get 502 error again.
Go back to configuration OK - with debug enabled.
Access other extension admin pages OK - with debug enabled.

Looking at system/debug.php commented out line 701
$this->app->setHeader('Server-Timing', $metrics);

Reinsert the line and break the previous loop which generates $metrics when $index > 65.
Can access com_cpanel.
Change it to break when $index > 70 and get 502 errors again.

Looks like there is a limit to Server-Timing which Joomla 7.4.1 exceeds.

### System information (as much as possible)

Plesk 18
Ubuntu 20
PHP 7.4.27 FPM served by Apache

### Additional comments

Looking at server logs spotted this:
upstream sent too big header while reading response header from upstream

Which led me to this
https://stackoverflow.com/questions/23844761/upstream-sent-too-big-header-while-reading-response-header-from-upstream

Adding these Nginx directives (from above article) fixed the problem.
fastcgi_buffers         16  16k;
fastcgi_buffer_size         32k;
proxy_buffer_size          128k;
proxy_buffers            4 256k;
proxy_busy_buffers_size    256k;

OK, sorted, but is all this Server-Timing information necessary?
Should it be possible to enable / disable it separately?

**Comment by Quy** [comment]
Duplicate #37080. Please test PR #37087. Thanks.
