### ISSUE TITLE
How do I completely disable en-GB

### ISSUE THREAD

**Issue by fballem** [joomla/joomla-cms#37105]
I want to completely disable en-GB from my multi-lingual website. I use en-CA and fr-FR languages. I do not want any options that use en-GB.

**Comment by chmst** [comment]
You should not disable en-GB as it is the fallback language. This means if by any circumstance one of your preferred languages has not a translation, then English is used. Or did you mean the langauge switcher module? Then your question is better in forum.joomla.org

**Comment by Fedik** [comment]
If I right remember, you have to unpublish content language at /administrator/index.php?option=com_languages&view=languages

**Comment by chmst** [comment]
Closing as it is not a Joomla issue.
