### ISSUE TITLE
[4.1]Advanced Search > parameters > Sort order > price

### ISSUE THREAD

**Issue by pcombet-adosis** [joomla/joomla-cms#37112]
In Backend > Advanced search parameters, there is an option to sort results based on different options. 
![screen shot 2022-02-21 at 12 51 48](https://issues.joomla.org/uploads/1/dd1d3675e76aa0971abeac25f2281d26.png)

One of them is "Sort by Price", which is based on a field in table #finder_links called "list_price". 
![screen shot 2022-02-21 at 12 51 47](https://issues.joomla.org/uploads/1/0d12a88a74ffe8d36e000a9cbb3f9c6b.png)
Is this parameter useful ? I've checked every script in Joomla, and there is no need of this option, as it is not used anywhere in Joomla. It seems to be a left over of an old Joomla version (2.5 ?)

This is my first PullRequest, asked by Marc Dechevre to do it. Please be kind, hoping I'm not missing any important milestone/haveto. 

Best
Philippe

**Comment by brianteeman** [comment]
Please read 
1. https://developer.joomla.org/joomlacode-archive/issue-29551.html
2. https://github.com/joomla/joomla-cms/pull/507

**Comment by richard67** [comment]
> This is my first PullRequest, asked by Marc Dechevre to do it.

@pcombet-adosis This here is an issue report, not a pull request. That's why it's listed here https://github.com/joomla/joomla-cms/issues and not here https://github.com/joomla/joomla-cms/pulls . A pull request includes code changes. Was your intention to make a pull request?

**Comment by pcombet-adosis** [comment]
@richard67 those variables list_price and sale_list are NOT used anymore in Joomla. Brian Teeman confirmed and pointed me to some features that were abandoned back in 2013 (9 years). My idea via a PullRequest was to clean the database, the backend option (not used), the SQL files that create the columns in J!, so that we lighten the code. That was an idea, Behind this action, I'm trying to get used to the debugging/PR process, as this is my first attempt to improve J! I do not really know if the idea is good but it's worth trying it ;-)
Philippe

**Comment by richard67** [comment]
@pcombet-adosis I still don't understand why you write as if you had created a pull request already but you have only created an issue report.

**Comment by brianteeman** [comment]
I did NOT confirm they are not being used.

**Comment by pcombet-adosis** [comment]
> @pcombet-adosis I still don't understand why you write as if you had created a pull request already but you have only created an issue report.

@richard67 Sorry I'm not used to the exact vocabulary of testing/coding/improving software.  My intention was to mention that those options in the backend are NOT used/useful in J!. I have checked all the J! files, and it not used anywhere. Thus creating an issue woukld bring the topic on the table, so that maybe others coders/volunteers could analyse it to lighten J! code. The PullRequest was a suggestion from MarcDechevre, but sorry if I'm mistaken, I'm not used to this new vocab. I'm a Marketing man, not much a coder. Best, Philippe

**Comment by Quy** [comment]
Please see https://github.com/joomla/joomla-cms/pull/35993#issuecomment-1047061627 for context of possible usage.

**Comment by Hackwar** [comment]
Yes, the price field currently is not used, but we have it and it would allow shops to use smart search as well. I don't think we want to remove that.

**Comment by richard67** [comment]
@pcombet-adosis Are you ok with the above explanations now? Can we (or you can yourself) close this issue as expected behaviour?

**Comment by pcombet-adosis** [comment]
@Hackwar Ok with your explanation. Issue closed. Thx.
