### ISSUE TITLE
J!4 - Create User via REST API - Generate welcome email?

### ISSUE THREAD

**Issue by nbradshaw45** [joomla/joomla-cms#37128]
### Steps to reproduce the issue
After creating a user using the api - an email is NOT being kicked off to the new user.

Create User API documentation: https://documenter.getpostman.com/view/ ... 8340d77e4f

Joomla Settings:
New User Account Activation = 'SELF'
Send Password = 'Yes'

I was hoping that an email will be sent to the user with their password using the Mail Template: 'Users: New account with self-activation (with PW)'

Is this a bug? Or is this just not ready yet? Or is this how it was designed to work? Can there be another option in the JSON to kick off the email if it is set to: 1 ?

### Expected result
An email should be sent for self-registration

### Actual result
No email is sent

### System information (as much as possible)
4.1

**Comment by alikon** [comment]
please test #37149

**Comment by nbradshaw45** [comment]
Thank you! This tested good!

However, I have a suggestion:

"sendEmail": (0 or 1) relates to receiving admin messages (the name is a little confusing).

I think it would make sense to add a new flag for send email to users on create - so that it is optional - there could be reasons why an admin may not want to send these emails.

So creating a new json element called "sendUserWelcomeEmail": values (0 or 1)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37128">issues.joomla.org/tracker/joomla-cms/37128</a>.</sub>

**Comment by alikon** [comment]
dunno what should be the "correct" behaviour from a web service,
imho  prefer to not set self-register mode from webservices, but, 
if we would like to "mimic" the cms....

**Comment by redpanda-gr** [comment]
Thank you for your response!

The true is that I don't know what a web-service should do and what not, in order to not mimic a CMS.
My comment was based on, since we have a hook (email send) for the endpoint 
`POST /users, `
we could have one more, lets say 
`PATCH user/verify/{id}`
Imho the SELF activation is an important step for the registration process, but of course I understand that the API should be "to the point".

Thank you again @alikon !
