### ISSUE TITLE
Joomla 4 renders article titles as h1 (instead of h2)

### ISSUE THREAD

**Issue by Oliohly** [joomla/joomla-cms#37137]
Hello Joomla Team,

i am updating to Joomla 4 and found out that every article title is rendered as h1 - not as h2 anymore. And now every article has a heading looking very different to what it was before the update. Now i am wondering how to return to the 'old' look, where a title was rendered as h2. 

### Expected result
Example title "incognito fesselt sein Publikum" at the top: This is [how it should be](https://www.fosbos-neusaess.de/index.php/einblicke/15-schultheater-fesselt-wieder-einmal-sein-publikum "This is how the title should be") (production site with joomla 3.10)

### Actual result
Example title "incognito fesselt sein Publikum" at the top: This is [how the updated J4.1 site looks](https://fosbos.telefos.de/index.php/einblicke/15-schultheater-fesselt-wieder-einmal-sein-publikum "Title formatted as h1 instead of h2") (sandbox with joomla 4.1)

### System information
Production site: J3.10.6
Sandbox site: J4.10
Template: RocketThemes Koleti

### Additional comments
The seller of the template (rockettheme.com) checked that this is an joomla issue. For the meantime the supports recommends this override: "First, you should report this to Joomla. In the meantime, to get around this, you will need to create a Joomla override. So, go to templates > templates (site) > koleti files and folder > click on the "create override" tab and select com_content > article Then if you look on line 28 of the created override for default.php you will see where the tag to be used is defined. However, I think that the two tags are the wrong way around - if the page heading has been set to show then the title tag should be h2 not h1."

I hope it helps. Thank You for your tremendous work on Joomla!
Oliver

**Comment by brianteeman** [comment]
>  if the page heading has been set to show then the title tag should be h2 not h1."

That is exactly what this code does
`$htag    = $this->params->get('show_page_heading') ? 'h2' : 'h1';
`

**Comment by brianteeman** [comment]
And please dont confuse the visual appearance of something with its meaning.

h1, h2 etc are NOT just shorthands to use to visually style your content

They have a specific meaning that is essential for any technology looking to read your site and to understand what is important. This includes screen readers and search engines.

**Comment by simbus82** [comment]
@Oliohly an article title in the article page should be an H1 for the SEO, so in Joomla 4 it's correct.
PS: your site 3.x has many technical SEO "issues": index.php in the url, same keywords in the pages (adding meta keys is a loss of time), missing H1 in pages, no metatitles, same desc in every pages, wrong tree of headings (example an h4 after an h2 without a h3). Don't replicate these in your new 4.x website ;-)

**Comment by chmst** [comment]
Thanks for clarifying, @brianteeman and @simbus82. Closing this as it  is not an issue of Joomla.
