### ISSUE TITLE
Rendering mod_custom duplicate render (double title)  

### ISSUE THREAD

**Issue by micheleramazza** [joomla/joomla-cms#37147]
### Steps to reproduce the issue
Global cache OFF
insert  mod_custom with ShowTitle->on  Cache->off in footer 
insert the same module with a {loadmoduleid xxx} into the page article. 

### Expected result

I expect one title for every module. 

### Actual result
The second module is render with 2 titles. Third time the module is render, 3 title.  The html content of the module is replaced with the render of the first time the module has been rendered  

### System information (as much as possible)

not dependent

### Additional comments
I have replaced from line 234 of /libraries/src/Helper/ModuleHelper.php
and it works (maybe the cache doesn't work): 

234-		foreach (explode(' ', $attribs['style']) as $style)
		{
			if ($moduleContent = LayoutHelper::render('chromes.' . $style, $displayData, $basePath))
			{
				$modulecontent = $moduleContent; //this is originally $module->content=...
			}
		}

		// Revert the scope
		$app->scope = $scope;

		$app->triggerEvent('onAfterRenderModule', array(&$module, &$attribs));

		if (JDEBUG)
		{
			Profiler::getInstance('Application')->mark('afterRenderModule ' . $module->module . ' (' . $module->title . ')');
		}

		return $modulecontent;

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

I have however created a pull request for joomla 4 to fix this. #38571
