### ISSUE TITLE
no help     administrator/help/en-GB/Articles:_Edit.html

### ISSUE THREAD

**Issue by mvlogten** [joomla/joomla-cms#37142]
### administrator/help/en-GB/Articles:_Edit.html
there is help,' ? Help button ' produces in alle cases the 404 code

where are the help files located and how are they called ?

**Comment by brianteeman** [comment]
Unable to replicate

![image](https://user-images.githubusercontent.com/1296369/155856525-56cf4399-3339-4863-b7e9-0a090508aca4.png)

**Comment by brianteeman** [comment]
I guess this can be closed now?

**Comment by mvlogten** [comment]
No i don’t see the relevance of the first comment
I want to know hoe the help button (right upper corner) in de backend screens work
Amy suggestions/information?
