### ISSUE TITLE
build --watch

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37155]
Can someone please check that this is working as intended. It might be me doing something wrong but I am expecting that when running then any changes I make to an scss file inside `build\media_source\templates\` will be converted to css, copied to `\media` and minified.

Is it  broken or is my expectation wrong?

**Comment by dgrammatiko** [comment]
@brianteeman the watch is only aware of the entry SCSS file at the moment, so if you edit an import that won't kick a new rebuild. It should be easily fixable if someone could add this file in the mix: https://github.com/sass/node-sass/blob/master/lib/watcher.js

**Comment by akshitrattan** [comment]
will simply adding the watcher.js file in the build folder and making changes in the package.json file work??

**Comment by akshitrattan** [comment]
> @brianteeman the watch is only aware of the entry SCSS file at the moment, so if you edit an import that won't kick a new rebuild. It should be easily fixable if someone could add this file in the mix: https://github.com/sass/node-sass/blob/master/lib/watcher.js


I feel I've I'm close to solving this problem but while trying to implement the solution the 'this.reset() is giving an error and I cannot figure out why

**Comment by dgrammatiko** [comment]
> the 'this.reset() is giving an error and I cannot figure out why

What is the error you're getting?

**Comment by akshitrattan** [comment]
im using the 'changed' function in the watcher.js file to watch for changes in SASS files, the function consists of a line "this.reset()" which itself is another function, but while running the watch command in the terminal it gives an error that 'this.reset()" is not a function
<img width="1439" alt="Screenshot 2022-03-18 at 7 41 05 PM" src="https://user-images.githubusercontent.com/78909027/159018584-0aba7ca1-b91b-4643-9f46-1501ca1afbf6.png">

**Comment by dgrammatiko** [comment]
@akshitrattan do you have a link to the brach you're currently working?

**Comment by akshitrattan** [comment]
> @akshitrattan do you have a link to the brach you're currently working?

https://github.com/akshitrattan/joomla-cms/tree/Fix%2337155
