### ISSUE TITLE
Media manager URLs / file names Issue

### ISSUE THREAD

**Issue by lushdomain** [joomla/joomla-cms#37159]
Hi,
This is to the person in charge of Joomla's media manager (I think).
Please can you make the URLs/filenames for selected images in media manager, and any extension that uses media manager, display fully when you hover over them.
I don't know about others but I make several size versions of the same image, and when I select them from media manager it's hit and miss that I select the correctly sized image the first time. It would be much easier if the image file name was completely visible one way or another, so I can see the filename, thus select the correct image first time.

Thank You.

**Comment by brianteeman** [comment]
Already done

![image](https://user-images.githubusercontent.com/1296369/155901891-aa53b903-b337-4026-927d-d65987b58077.png)

**Comment by brianteeman** [comment]
of course you could also name your files with the dimension first or display the files in list view

![image](https://user-images.githubusercontent.com/1296369/155902023-7b844d41-ca3c-44ee-8a4d-78a9fa7b417e.png)

**Comment by lushdomain** [comment]
Hi Brian,

I think I did not explain properly.

The issue is not just in media manager. It's in the images and links tab (or similar) when you are making an article.

![screen shot 2022-02-27 at 22 19 44](https://issues.joomla.org/uploads/1/8246b3c05bdccdde96853f5c981a6c2b.png)

In media manager, yes I can use the list, rather than gallery. But I still don't get the hover file name as your pic indicates in the gallery view.

What version of J4 are you using to get the hover file name as in your pic?

Regards, Brendan
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37159">issues.joomla.org/tracker/joomla-cms/37159</a>.</sub>

**Comment by brianteeman** [comment]
it was merged here https://github.com/joomla/joomla-cms/pull/36754 with 4.1.0

**Comment by lushdomain** [comment]
Thanks Brian :)

I'll update to 4.1 as soon as the extensions i'm using are compatible to see the changes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37159">issues.joomla.org/tracker/joomla-cms/37159</a>.</sub>

**Comment by Quy** [comment]
Closing as fixed in v4.1.
