### ISSUE TITLE
[4.1] tags assets invalid data

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37153]
Create a clean install

Check the #__assets table and you see (apart from root.1) that all the names are in the form com_something

Create a new article and give it a tag

Check the #__ucm_content table and you will see a record has been created for the article you just created

For that record check the value of asset_id (it will be a number)

Now go to the #__assets table and you will see some new records. Find the record with the id matching the asset_id from above.

The name and title are both in the form #__ucm_content.xx

Fairly sure thats not intended and may have consequences

**Comment by chmst** [comment]
Confirmed. I assume that it has no consequences except flooding the assets table with useless data. 
There is no reason for having an assetid field in com_ucm_content as much as I see.

**Comment by brianteeman** [comment]
I have no idea if there are consequences. I presumed there was a reason for the record to be created but it was created wrongly

**Comment by brianteeman** [comment]
@chmst I assume that you added the wrong tag?

**Comment by chmst** [comment]
It was also in j3. Let's see if we resolve it in J3

**Comment by brianteeman** [comment]
> There is no reason for having an assetid field in com_ucm_content as much as I see.

Is it perhaps needed for the version history which is available with tags?

**Comment by chmst** [comment]
If every version can have different permissions - maybe. I must build tests with many different roles / permissions for testing that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37153">issues.joomla.org/tracker/joomla-cms/37153</a>.</sub>

**Comment by brianteeman** [comment]
Please correctly tag this issue as for J4

**Comment by Hackwar** [comment]
I can confirm this issue. These entries have no use and we should remove them. Especially since they are all empty, even when their original content item does have entries in there. This is just wasting lots of time and slowing down sites.

**Comment by brianteeman** [comment]
anks for confirming. I can work on this tomorrow now.

**Comment by Hackwar** [comment]
I got it fixed. Writing a PR right now.

**Comment by brianteeman** [comment]
great - one less thing for me to look at

**Comment by Hackwar** [comment]
PR #39165 is created, this issue is closed. Nothing to do here for me. :-)

**Comment by brianteeman** [comment]
Well I never would have found that solution. So thanks again
