### ISSUE TITLE
Backend login page -> space bottom of the page

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#37171]
### What needs to be fixed
Backend Login page -> There's a little space below the left blue bar. I believe this only shows when there are NO buttons in the top header.  We have disabled all those buttons for not logged in users.

### Why this should be fixed
Just for better looks ;-)

### How would you fix it
body.com_login :
div#wrapper -> Add:  flex-grow: 1;

### Side Effects expected
None

Not sure if this is the right place to create this issue? maybe there is a rep for just the backend template?

![2022-03-02_09-35-31](https://user-images.githubusercontent.com/4346247/156353618-ce094f9a-a74a-4db0-ac44-532c86b8b7de.png)

**Comment by richard67** [comment]
> Not sure if this is the right place to create this issue? maybe there is a rep for just the backend template?

It is the right place here. There is a backend template repo, but that was used in past and is not active anymore.

**Comment by brianteeman** [comment]
confirmed when the site preview button is removed

**Comment by brianteeman** [comment]
@jjnxpct are you able to submit a pull request to fix this?

**Comment by jjnxpct** [comment]
@brianteeman I have never done that before ;-) Not sure how to do it. But I am willing to learn. 

I work with VSCode and we also work with GitHub within VScode. But mainly for our own projects. We don't use pull requests. 

To do this I would need to first clone this repo and then change some code. But then? In stead of committing I would need to 'upload' it as a pull request?

**Comment by richard67** [comment]
@jjnxpct Fork the repo, clone your fork so you have it locally, create a new branch based on the 4.1-dev branch, make your changes in that new branch, push them to your remote and there use the UI on GitHub to create a pull request from that branch.

That's how I would do it. Maybe there are more comfortable ways in VScode, I don't know.

**Comment by anmode** [comment]
Heyy I know how to solve it but I cannot replicate the error in my backend login page there is nothing this type of issue. You check it out I had made a vimeo. https://vimeo.com/685087190/461385f2f9

**Comment by anmode** [comment]
Heyy I know how to solve it but I cannot replicate the error in my backend login page there is nothing this type of issue. You check it out I had made a Vimeo https://vimeo.com/685087891/35176c2781

**Comment by jjnxpct** [comment]
@anmode You need to disable the button in the top bar (that takes you to the website) so there are no buttons there. Only then will you see the space below.

**Comment by anmode** [comment]
.

> @anmode You need to disable the button in the top basr (that tales you to the website) so there are no buttons there. Only then will you see the space below.

ohh okay I got it :) thanks

**Comment by anmode** [comment]
@richard67 @brianteeman  I think i had solved this issue via inspecting it you may check out vimeo I have made it https://vimeo.com/685375065/247291ab08 but a small help I am unable to locate where this `sidebar-wrapper` CSS  please would u help a little.

**Comment by jjnxpct** [comment]
Hi! As stated in my first post here I think this might be a fix in the CSS:
body.com_login -> div#wrapper -> Add: flex-grow: 1;
/media/templates/administrator/atum/scss/blocks/_global.scss

But this changing the #wrapper here might have impact on other pages as well?
I found the specific login CSS here:
/media/templates/administrator/atum/scss/blocks/_login.scss

Hope this helps.

**Comment by anmode** [comment]
Disabling buttons via `visibility: hidden` need no change in the CSS files.

**Comment by Quy** [comment]
Please test PR #37236
