### ISSUE TITLE
Joomla 4.1.0 issue

### ISSUE THREAD

**Issue by bobdxb** [joomla/joomla-cms#37182]
### Steps to reproduce the issue
Have created multilanguage website with hikashop and keep receiving error

### System information (as much as possible)

[error-bgsite.txt](https://github.com/joomla/joomla-cms/files/8172732/error-bgsite.txt)

### Additional comments
tks for help resolving

**Comment by brianteeman** [comment]
The error message indicates that the problem is with hikashop and you should contact them for support.

>` [02-Mar-2022 19:38:31 UTC] PHP Notice:  Trying to access array offset on value of type null in /home/customer/www/-------.com/public_html/administrator/components/com_hikashop/helpers/helper.php on line 1797`
