### ISSUE TITLE
Article Global Options ... 'Hits' setting missing.

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#37216]
### Steps to reproduce the issue
Navigate to Articles Global Options

### Expected result
In the Articles tab there should be an option to set show/hide Hits and an option to Record the Hits.

### Actual result
No Hits Options available

### Additional comments
The Menu Item edit screens and Articles both set default as 'Use Global'.  But there are no Global options for Hits.

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/156938144-6e4fb498-abe8-4ee2-addd-5f3da0a7833b.png)

**Comment by Webdongle** [comment]
Strange two of my test sites don't have it but the others do.  OK thanks.  Closing
