### ISSUE TITLE
[3.10] Admin content search tools button disappears on narrow screens

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#37215]
### Steps to reproduce the issue
Open J3 administrator
Go to Articles or Categories or Featured Articles or Fields or Field Groups
Narrow the screen to (I think) <767px

### Expected result
To still have this dropdown button available which would normally reveal three more buttons on click.

### Actual result
The button disappears so filtering is not possible.

### System information (as much as possible)
J3.10.6

**Comment by brianteeman** [comment]
I would say that this is the expected behaviour in j3. It is not intended that you can do everything in a mobile view.

**Comment by pritam825** [comment]
I am also agree with @brianteeman , but if needed then I will work on this

**Comment by Scrabble96** [comment]
Ok. I can see on my iPad (which isn't a large one) that the button is not available in portrait mode but it is available in landscape mode, so I guess that's probably good enough.
