### ISSUE TITLE
Language Tag being used for Content

### ISSUE THREAD

**Issue by fballem** [joomla/joomla-cms#37228]
### Steps to reproduce the issue
1. Modify the settings for a content language, such as changing the description or the URL Language Code.
2. Create content, such as articles, categories, menus, or menu items.
3. Note that the Language Tag is used to identify the content language. Screenshot attached shows the menus on the left side showing en-GB and fr-FR.![screen shot 2022-03-08 at 09 28 55](https://issues.joomla.org/uploads/1/57467b840b257234a5fc6488a9627dba.png)

### Expected result
Could we not use the URL Language Code in identifying Content Languages? The field is required and must be unique. We cannot change the Language Code, but we can change the URL Language Code.

### Additional comments
I understand that this would be a very large change, but it would be a good one from a user standpoint.

**Comment by brianteeman** [comment]
>  but it would be a good one from a user standpoint.

Could you explain why?

**Comment by fballem** [comment]
If I go to the trouble of modifying the parameters around the content language, such as the name, the native title, and possibly the URL Language code, then that's what I should be seeing on the Administrative interface when I'm building my content. I'm not writing in en-GB or fr-FR, I'm writing for English (Canada) or French (Canada). I realise that those are too long to display on such things as the menu, but the URL Language Code is short (en or fr). More reflective of what I am writing.

**Comment by brianteeman** [comment]
I dont know about french but I do know there is a language pack for English (Canada)

**Comment by fballem** [comment]
I would agree - if there was a way to eliminate en-GB as a content language and if en-CA was maintained by the project team. The challenges are that there is no way to eliminate en-GB and I have encountered issues with trying to use the en-CA language pack. I made the decision to use en-GB as the starting point of English. There is no fr-CA language pack, so I have to use fr-FR language pack.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37228">issues.joomla.org/tracker/joomla-cms/37228</a>.</sub>

**Comment by brianteeman** [comment]
>  if there was a way to eliminate en-GB as a content language

There is you just remove it from the content language list.

**Comment by fballem** [comment]
Actually, that does not work. I have installed English (Canada), added it to the Content Languages, changed all of my English content to use English (Canada), and set the default content language to English (Canada). I also removed English (United Kingdom) from the content language list. As you can see from the attached screenshots, English (United Kingdom) is still showing as a selectable language for my content in many places, such as associations.

On an earlier post, I was told that English (United Kingdom) could not be removed, since it is the default installation language. That's why I chose to make minor changes - can't fight city hall.

There is no language pack for French (Canada), so again, I had to make changes to fr-FR in order to make it "look" like it is Canadian.

The fact that Language tags are used instead of the URL Language Code looks quite ugly when building content.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37228">issues.joomla.org/tracker/joomla-cms/37228</a>.</sub>

**Comment by brianteeman** [comment]
You cannot remove the en-gb language but you should be able to remove the en-gb content setting and if not then its a bug

I think you forgot the screenshots

**Comment by fballem** [comment]
Had a malfunction between chair and keyboard. Screenshots are attached. I do remove the content setting. I suspect that I cannot disable en-GB as a Site Language and that's probably where the issue is arising.

![screen shot 2022-03-09 at 11 08 43](https://issues.joomla.org/uploads/1/ec1ea468d3fdd2ddec098821e4702b9d.png)![screen shot 2022-03-09 at 11 08 43](https://issues.joomla.org/uploads/1/b1d7be9aeb830b91f41ee60908f9dda6.png)![screen shot 2022-03-09 at 11 08 43](https://issues.joomla.org/uploads/1/1c47255f06c07c82514f49ffef3cb5cd.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37228">issues.joomla.org/tracker/joomla-cms/37228</a>.</sub>

**Comment by fballem** [comment]
I'd like to offer a suggestion. For those language packs, such as en-CA or en-US, that are 'officially supported' by the Joomla project team, why not allow the user a choice of using those as an installation option. So, instead of just offering English during the installation, offer English (United Kingdom), English (United States), English (Australia), English (Canada), etc. American users must go nuts with British spellings. Canadian users not so much, since we use a happy mix of both American and British English.

Do the same thing for your German users. I'm not sure what you would do for your Portuguese users, since I'm not sure how well supported the two versions of Portuguese are.

Just thinking outside of the box.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37228">issues.joomla.org/tracker/joomla-cms/37228</a>.</sub>

**Comment by brianteeman** [comment]
its already there as part of the install process

**Comment by infograf768** [comment]
The en-GB content language has to be deleted to take it off from all multilingual editing. It works fine.
Also, it is possible to install any supported language at install time. Look at the last screen of installation
<img width="776" alt="Screenshot 2022-03-10 at 12 18 35" src="https://user-images.githubusercontent.com/869724/157651453-6a0db8eb-d753-4c59-9414-cf8d943633af.png">
.

**Comment by fballem** [comment]
I don't recall seeing that option during the main installation of Joomla. Since I'm not too far along, I can re-install Joomla from scratch and see if I have that option. Please note that I am installing Joomla using Softaculous that is provided by my webhosting provider. I don't know if that makes a difference.

If it's not on the installation for Joomla itself, then please explain how I get the screen that you showed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37228">issues.joomla.org/tracker/joomla-cms/37228</a>.</sub>

**Comment by fballem** [comment]
I do want to say "Thank you/merci" for the time that you are spending helping me with this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37228">issues.joomla.org/tracker/joomla-cms/37228</a>.</sub>

**Comment by fballem** [comment]
I did go into the Extensions to see if I could uninstall en-GB. As the screenshot shows, it's locked and a protected extension. I have made en-CA the default for the site and for administration.![screen shot 2022-03-10 at 22 50 29](https://issues.joomla.org/uploads/1/c2fd0070770a8891f57858f529b917cf.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37228">issues.joomla.org/tracker/joomla-cms/37228</a>.</sub>

**Comment by brianteeman** [comment]
You can not uninstall the en-GB language as it is needed for when language packs are not 100% up to date.

What @infograf768 was referring to was deleting the CONTENT language which is not the same.

Also I see that you installed using softaculous installer which is their own code and does not offer the ability to set languages at installation

**Comment by fballem** [comment]
I took your suggestion and re-installed my website using the Joomla package directly. That seems to have solved the majority of the problems that I was having with the multilingual bits in my website. There is nothing that I can do about the French, which shows as fr-FR using the Language tag, instead of fr, using the URL Language Code. There is no French (Canada) language pack.

I can live with it, but it sure would be nice if the change could be made to use the URL Language Code.

If that's not a change that you want to put in the hopper, then feel free to close this ticket.

Again, many thanks for the time you have taken to help me solve the significant problems that I was experiencing!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37228">issues.joomla.org/tracker/joomla-cms/37228</a>.</sub>

**Comment by brianteeman** [comment]
Glad to hear you have made good progress. 

Not my call about the language tag change but I suspect it will be a no as its quite a disruptive change

**Comment by infograf768** [comment]
You can use the Language Code system plugin to display fr-ca in html produced instead of fr-FR

<img width="797" alt="Screenshot 2022-03-13 at 09 18 11" src="https://user-images.githubusercontent.com/869724/158051218-a61a1e30-e22e-43a9-b35d-d4325f028602.png">

<img width="1133" alt="Screenshot 2022-03-13 at 09 15 56" src="https://user-images.githubusercontent.com/869724/158051263-8a233509-dd23-4a80-a8ce-e5c2b21b1f48.png">

**Comment by brianteeman** [comment]
Is there another "trick" to solve these two places

![image](https://user-images.githubusercontent.com/1296369/158052334-980a461c-9810-4468-beb9-bfca1f42393e.png)

![image](https://user-images.githubusercontent.com/1296369/158052351-a99474e5-c343-4897-bde4-5e84326d1687.png)

**Comment by fballem** [comment]
Thank you for the hint about the Language Code. Since I am using only en-CA and fr-FR in my website, I have changed them to en and fr respectively.

I am hoping that someone can solve for the last two places.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37228">issues.joomla.org/tracker/joomla-cms/37228</a>.</sub>

**Comment by infograf768** [comment]
@fballem 
The language code as set in that system plugin is NOT the URL language code. This is why I posted the htlm result where you can see both. We created that plugin to help search engines.

AFAIK, there are no tricks yet to use the language code as defined in the plugin for the associations badges.

**Comment by infograf768** [comment]
Concerning associations badges, see patch here
https://github.com/joomla/joomla-cms/pull/37289

**Comment by fballem** [comment]
That will certainly solve the last lingering issue. I assume that when the patch is put into production, there will be an update identified on Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37228">issues.joomla.org/tracker/joomla-cms/37228</a>.</sub>

**Comment by richard67** [comment]
So as we have a pull request, #37289 , can we close this issue like we usually do when we have a pull request? Or is there something remaining which is not solved by that pull request and previous advice?

The bad new could be that the pull request might be delayed until 4.2 because the change is considered to be a new feature.

**Comment by fballem** [comment]
I'm not sure what a 'pull request' means. If this means that the change will be included in a Joomla update then I would be content to close this issue. I have been able to get my site up and running pretty close to perfect and the pull request would fix the final lingering issue. I'm also okay if the update doesn't occur prior to 4.2, since we are running 4.1 now.

Thanks everyone for all of your help!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37228">issues.joomla.org/tracker/joomla-cms/37228</a>.</sub>

**Comment by richard67** [comment]
A pull request is a proposed code change here on GitHub, like #37289 is.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37289 . Thanks in advance.
