### ISSUE TITLE
Smart Search > Result Taxonomy > language strings not being translated in the front-end

### ISSUE THREAD

**Issue by woluweb** [joomla/joomla-cms#37229]
### Steps to reproduce the issue

Enable Smart Search in the front-end (and make sure that the Option "Result Taxonomy" is set on Yes, which is the case by default btw).

Make a search in the front-end where the latter is in any language otehr than English

### Expected result

The Result Taxonomy should have its keywords translated, namely
- Type
- Author
- Category
- Language

### Actual result

It will display something like

`Type: Article  Author: Marc Dechèvre  Category: Brabant wallon  Language:`

where the words
- Type
- Author
- Category
- Language
are *not* translated

### System information (as much as possible)

J4.1.0 stable
PHP8.0

**Comment by Quy** [comment]
Fixed in #36863

**Comment by woluweb** [comment]
txs
