### ISSUE TITLE
Webinstall packages version 4.1 wrong version check

### ISSUE THREAD

**Issue by ZjeeBie** [joomla/joomla-cms#37226]
###
Install clean Joomla 4.1.
install additional language Dutch (nl-NL).
Go to administer extensions.
Add new one through web service, i.e. Akeeba.

### Expected result
4.1 should be backwards compatible with 4.0. So package (Akeeba) should install correctly.

### Actual result
A message is shown that the minimum version should be 4.0.99

### System information (as much as possible)
MacOS monterey 12.2.1, MacBook Pro (16-inch, 2021), Apple silicon M1 MAX, 64GB
MAMP pro 6.6.1 (build 22865 - universal
Safari 15.3 / Firefox developer 98.0b.10 (64-bit)

### Additional comments
When installing through an optional way all works well.
Other alternative ways to install packages seems to work fine

**Comment by richard67** [comment]
> 4.1 should be backwards compatible with 4.0. So package (Akeeba) should install correctly.

@ZjeeBie Joomla 4.1 **_is_** backwards compatible with 4.0.

Which version of Akeeba have you tried to install?

**Comment by brianteeman** [comment]
This is nothing to do with Joomla. The problem is that the akeeba backup extension listing on the extension directory and provided by the install link you used is  v.8.1.2. This version is not compatible with joomla 4.1 and it is akeeba backup that is telling you that not joomla. The correct version for joomla 4.1 is akeeba backup 9.2 which you can download and install from https://www.akeeba.com/download.html#akeebabackup-joomla

I assume that the problem is that the joomla extension directory only has a single download/install link when it should have 2 or more where there are different releases for different versions of joomla

**Comment by richard67** [comment]
> I assume that the problem is that the joomla extension directory only has a single download/install link when it should have 2 or more where there are different releases for different versions of joomla

Hmm, I thought they had fixed that. But maybe that was wrong.

**Comment by brianteeman** [comment]
I just tested it and its definitely not fixed

**Comment by richard67** [comment]
Am just trying to get someone on Glip who has to do with the JED.

**Comment by brianteeman** [comment]
Wil leave it to you @richard67 but this is not a joomla issue per se and can be closed

**Comment by ZjeeBie** [comment]
Richard,
Maybe I can shine a little more light on the issue.
When on the page of JED, downloads are represented by cards. Akeeba’s title directs to their website and version 9. But the card-text redirects to 
http://cdn.akeeba.com/updates/pkgakeebacore.xml
And in this file a relation to their version 8 is made. I have further no knowledge of the process or structures behind all this but it just attracted my attention. Hope it helps
Kind regards
@Zjeebie Jan Baelemans

**Comment by richard67** [comment]
> But the card-text redirects to http://cdn.akeeba.com/updates/pkgakeebacore.xml And in this file a relation to their version 8 is made.

@ZjeeBie I see. Well, that file is in the responsibility of the extensions developer, i.e. in this case Akeeba. Could you report the issue there? https://www.akeeba.com/support.html

Thanks in advance.

**Comment by richard67** [comment]
Closing as not a core issue.
