### ISSUE TITLE
[4.1] Maintenance: Database - wrong sql types, error in your SQL syntax?

### ISSUE THREAD

**Issue by Globulopolis** [joomla/joomla-cms#37234]
### Steps to reproduce the issue
Install component with table updates.
Sample file https://github.com/Globulopolis/Jcomments-4/blob/master/component/administrator/install/sql/updates/mysql/4.0.16.sql

### Expected result
`No Problems`

### Actual result
`You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ' AND `null` = 'NO'' at line 1`

`...the wrong type or attributes`

### System information (as much as possible)
Joomla 4.1
MariaDB 10.4.22
PHP 7.4.13

### Additional comments
The `Update structure` button will not help here.

![image](https://user-images.githubusercontent.com/740757/157340375-db12c847-b1da-407c-be6b-e992bc23a0ff.png)

**Comment by richard67** [comment]
@Globulopolis hat's a known limitation of the database checker which results in a false alarm. See #36363 . The solution can be found here: https://github.com/joomla/joomla-cms/issues/36363#issuecomment-998600390 , i.e. ask them to change their SQL to:

```
ALTER TABLE `#__jcomments_subscriptions` CHANGE `hash` `hash` CHAR(32) NOT NULL DEFAULT '';
ALTER TABLE `#__jcomments_subscriptions` CHANGE `source` `source` VARCHAR(100) NOT NULL DEFAULT '';
```

Let me know if this works for you and if they accept that change. If so, I suggest to close this issue.

**Comment by richard67** [comment]
P.S.: For the long term I'm working on a fix, but in the mean time please ask them to change their update SQL as suggested above,

**Comment by Globulopolis** [comment]
Thanks for help @richard67 
Suggested solution at https://github.com/joomla/joomla-cms/issues/36363#issuecomment-998600390 fixed the problem.

**Comment by richard67** [comment]
@Globulopolis You should also check the comments after the one you have linked, e.g. https://github.com/joomla/joomla-cms/issues/36363#issuecomment-998981251 .

I.e. in your case it should be [like I suggested above](url), without the "COLUMN" key word:

```
ALTER TABLE `#__jcomments_subscriptions` CHANGE `hash` `hash` CHAR(32) NOT NULL DEFAULT '';
ALTER TABLE `#__jcomments_subscriptions` CHANGE `source` `source` VARCHAR(100) NOT NULL DEFAULT '';
```

**Comment by Globulopolis** [comment]
@richard67 yes, I split the code and test it. All fine. No errors now.
