### ISSUE TITLE
Cassiopeia Style Copy: no CSS issue

### ISSUE THREAD

**Issue by dozentis** [joomla/joomla-cms#37246]
### Steps to reproduce the issue
Go to Template Style Site
Open Cassiopeia  - Default
Save as copy 
Assign Style via Menu or just make it default style

### Actual result
No CSS loaded, just HTML on website

### System information (as much as possible)
Joomla 4.1.0 - PHP 8.0.10 Xampp

### Additional comments
But the alternative way works!!!

Go to Template Style Site
Check Cassiopeia  - Default and click "Duplicate"
Assign Style via Menu or just make it default style
CSS loaded, all good!

-> "Save as copy" Cassiopiea Style doesnt load css, but when just duplicated the style the css will be loaded

**Comment by brianteeman** [comment]
Issue confirmed

**Comment by brianteeman** [comment]
Found the bug. Should have a fix shortly.

**Comment by brianteeman** [comment]
Sorry I cant see the fix. The problem is that the inheritable field is not being set.

**Comment by dgrammatiko** [comment]
There's a PR: #37248 please test

**Comment by alikon** [comment]
closing as there is a pr
