### ISSUE TITLE
MediaManager: Error on folders named "0" (number zero)

### ISSUE THREAD

**Issue by mikeazores** [joomla/joomla-cms#37242]
### Steps to reproduce the issue
Using Media Manager, can't navigate to a folder named "0" (number zero).

### Expected result
List all the media in that folder

### Actual result
Got this error: Error
Property 'name' of argument 'item' of event onFetchMediaItems has a wrong item. Valid: non empty string

### System information (as much as possible)
=============
System Information
=============
php: Linux fc92ce794b99 5.4.39-linuxkit #1 SMP Fri May 8 23:03:06 UTC 2020 x86_64
dbserver: mysql
dbversion: 10.5.6-MariaDB
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: false
phpversion: 8.0.14
server: nginx/1.14.2
sapi_name: fpm-fcgi
version: Joomla! 4.1.0 Stable [ Kuamini ] 15-February-2022 09:30 GMT
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36 Edg/99.0.1150.36

=============
PHP Settings
=============
memory_limit: 384M
upload_max_filesize: 100M
post_max_size: 100M
display_errors: true
short_open_tag: true
file_uploads: true
output_buffering: false
open_basedir: 
session.save_path: 
session.auto_start: 0
disable_functions: 
xml: true
zlib: true
zip: true
mbstring: true
gd: true
iconv: true
intl: true
max_input_vars: 1000

=============
Configuration File
=============
offline: false
display_offline_message: 1
offline_image: 
sitename: xxxxxx
editor: tinymce
captcha: 0
list_limit: 20
access: 1
debug: true
debug_lang: false
debug_lang_const: true
dbtype: mysqli
host: xxxxxx
user: xxxxxx
password: xxxxxx
db: xxxxxx
dbprefix: xxxxxx
dbencryption: 0
dbsslverifyservercert: false
dbsslkey: 
dbsslcert: 
dbsslca: 
dbsslcipher: 
force_ssl: 0
live_site: 
secret: xxxxxx
gzip: false
error_reporting: maximum
helpurl: https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}
offset: Europe/Madrid
mailonline: true
mailer: mail
mailfrom: xxxxxx
fromname: xxxxxx
sendmail: xxxxxx
smtpauth: false
smtpuser: xxxxxx
smtppass: xxxxxx
smtphost: xxxxxx
smtpsecure: none
smtpport: 25
caching: 0
cache_handler: file
cachetime: 15
cache_platformprefix: false
MetaDesc: 
MetaAuthor: false
MetaVersion: false
robots: 
sef: false
sef_rewrite: false
sef_suffix: false
unicodeslugs: false
feed_limit: 10
feed_email: none
log_path: xxxxxx
tmp_path: xxxxxx
lifetime: 120
session_handler: database
shared_session: false
session_metadata: true
memcached_persist: true
memcached_compress: false
memcached_server_host: xxxxxx
memcached_server_port: 11211
redis_persist: true
redis_server_host: xxxxxx
redis_server_port: 6379
redis_server_db: 0
cors: false
cors_allow_origin: *
cors_allow_headers: Content-Type,X-Joomla-Token
cors_allow_methods: 
behind_loadbalancer: false
proxy_enable: false
proxy_host: 
proxy_port: 
proxy_user: xxxxxx
massmailoff: false
replyto: 
replytoname: 
MetaRights: 
sitename_pagetitles: 0
session_filesystem_path: 
session_memcached_server_host: xxxxxx
session_memcached_server_port: 11211
session_redis_persist: 1
session_redis_server_host: xxxxxx
session_redis_server_port: 6379
session_redis_server_db: 0
frontediting: 1
block_floc: 0
log_everything: 0
log_deprecated: 0

	
=============
PHP Information
=============

**Comment by chmst** [comment]
It happens if the folder iis created outside of the media manger, via ftp, for example. Creating a folder in media manager gives this result: 

![grafik](https://user-images.githubusercontent.com/1035262/157854197-da97e480-dc93-4b6a-b079-4414aeafd3c6.png)

Creating a folder when the name starts with 0 creates a folder bt als with error message as above

**Comment by vorayash** [comment]
When trying to create folder with name 0 more than one time it gives stack of errors. I was wondering that, is this also a issue? what if we remove last error before giving new error?

![image](https://user-images.githubusercontent.com/72155000/157874141-7124b6e4-a74a-43d5-8bbb-94412ede9fc0.png)

**Comment by brianteeman** [comment]
@chmst I think that error message is a false clue. If you comment out that test then you get a different error

> Property 'name' of argument 'item' of event onFetchMediaItem has a wrong item

**Comment by chmst** [comment]
I posted this as one symptom more that foldername starting with 0 or foldername == 0 needs our attention. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37242">issues.joomla.org/tracker/joomla-cms/37242</a>.</sub>

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/39476 should address this issue. Please help testing. Thanks !
