### ISSUE TITLE
Batch process the selected tags  - Copy or Move 

### ISSUE THREAD

**Issue by dozentis** [joomla/joomla-cms#37247]
### Scenario
There are many tags on the website. If you need a keyword hierarchy afterwards, e.g. for different keyword clouds, you must have to open and edit each tag to subordinate them.

### Still missing feature - and a must-have!
Open components/tags
check your tags
action/batch
**Copy or Move to tag**  <- I miss this
_(should be available like in articles, categories or menuitem batch process)_

### System information (as much as possible)
for 3.x and 4.x

**Comment by Quy** [comment]
Duplicate #23304?

**Comment by richard67** [comment]
Looks indeed like a duplicate to #23304 .

**Comment by dozentis** [comment]
Yes exactly, thank you. Didn't find it though I searched for tags and batch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37247">issues.joomla.org/tracker/joomla-cms/37247</a>.</sub>

**Comment by richard67** [comment]
Closing as duplicate report. Thanks anyway for reporting.
