### ISSUE TITLE
New Menu Item Error: 0 array_key_exists(): Argument #2 ($array) must be of type array, stdClass given

### ISSUE THREAD

**Issue by xplaym** [joomla/joomla-cms#37269]
### Steps to reproduce the issue
With PHP8 (8.0.8, 8.1.0) I get the above error when i try to add a new menu item
With PHP7 (7.4.28) all works fine

### System information (as much as possible)
Setting 	Value
 
PHP Built On 	Linux
Database Type 	mysql
Database Version 	8.0.26
Database Collation 	utf8mb4_0900_ai_ci
Database Connection Collation 	utf8mb4_0900_ai_ci
PHP Version 	8.0.8
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.10.6 Stable [ Daraja ] 12-February-2022 17:04 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0

**Comment by richard67** [comment]
Could you (temporarily) switch on debug in global configuration so you can see the stack trace to the error, and post that stack trace here? It would help us to see where the error happens. Thanks in advance.

**Comment by xplaym** [comment]
I just solved the problem and was due the component "Adsmanager"

activating the debug I can read this additional info:
0 array_key_exists(): Argument #2 ($array) must be of type array, stdClass given
/plugins/content/adsmenu/adsmenu.php:14 

Solution: upgrade the component Adsmanager to the version 3.2.15

**Comment by xplaym** [comment]
Solution: upgrade the component Adsmanager to the version 3.2.15

**Comment by richard67** [comment]
Thanks for reporting back. Happy it was solved.
