### ISSUE TITLE
[4.1] cassiopeia mod_finder

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37263]
### Steps to reproduce the issue
Install joomla with sample data
check that the module Smart Search is published in the search position
Experiment with the advanced search options

### Option 1 - Hide
![image](https://user-images.githubusercontent.com/1296369/158073682-0dc03353-b281-4503-9c18-5f93d35243f0.png)

### Option 2 - Show
![image](https://user-images.githubusercontent.com/1296369/158073702-721f5322-a7a9-48ca-b991-3416f51e1ec2.png)

### Option 3 - Link to component
![image](https://user-images.githubusercontent.com/1296369/158073714-bb85f5a0-9c48-44a5-a6d0-f738cf79e824.png)

### Additional comments
I have NOT attempted to fix this as I don't know the approved way to add css when a module is in a specific position but the module really should work nicely when its in its default position

**Comment by richard67** [comment]
This could be something for @drmenzelit .

**Comment by RickR2H** [comment]
See PR #37275<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37263">issues.joomla.org/tracker/joomla-cms/37263</a>.</sub>
