### ISSUE TITLE
[4.0?][4.1] No more 404 error with inexistent urls

### ISSUE THREAD

**Issue by morphinestyle** [joomla/joomla-cms#37262]
### Steps to reproduce the issue
Launch:
**www.mywebsite.com/%$£-wrong-or-inexistent-url**

### Expected result
A 404 error page

### Actual result
It loads up to the "first slash" of THE VALID URL, in this case it loads homepage, without any 404 error
**www.mywebsite.com/%$£-wrong-or-inexistent-url** => J4.1 loads: www.mywebsite.com 

### System information (as much as possible)
Joomla 4.1 on Apache+Nginx using Mysql
Joomla 4.1 on OpenLitespeed using MariaDB

### Additional comments
**For wrong url with a second / "slash" it returns correctly a 404 error page**
i.e.: **www.mywebsite.com/category/%$£-wrong-or-inexistent-url** => J4.1 returns correctly a 404 error

**Comment by Orgoth** [comment]
I have the same problem since 4.1.0.
Unfortunately, it leads to the fact that all set up redirects are ignored and in the Search Console of Google the first entries for duplicate content come up.

**Comment by brianteeman** [comment]
I am unable to replicate this. Are you using the htaccess file supplied by Joomla

**Comment by morphinestyle** [comment]
Hi Brian,
yes, i put the basic J4 .htaccess in both Apache+Nginx and OpenLitespeed webservers again right now: but it doesn't works as expected. (Now i put again my standard htaccess directives: some redirects, and the removal of the last "ZIP" block on OpenLitespeed webserver)

I already tested deactivating quite every extension on my websites, and switched also to Cassiopeia template from Gantry: but the issue persist on every J4.1 website (at first i thought about a Gantry issue).

**Comment by morphinestyle** [comment]
Right in this moment i see this: https://github.com/gantry/gantry5/issues/2938
Now deactivating completely Gantry and using Cassiopeia i can replicate the issue.

**Comment by mahagr** [comment]
I think this may also related to https://github.com/joomla/joomla-cms/issues/35463

**Comment by morphinestyle** [comment]
Update, 29 March 2022:

- updated J4 to 4.1.1
- updated Gantry&Helium to 5.5.12
- updated SP Pagebuiler to 3.8.6 with the fix: "**Router is preventing 404 page**"...
- other plugin updates.

Now the problem seems solved in my live websites.
Most likely that extension was causing the issue, which was inactivated while error testing.

I will make more trials, and i will close this issue just in case.

**Comment by morphinestyle** [comment]
Tested: plugin related issue.
I'm closing the issue.
