### ISSUE TITLE
cassiopeia-grid-gutter

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37265]
I'm looking at the scss for cassiopeia and I see that one of the most used variables is $cassiopeia-grid-gutter

However as the value of $cassiopeia-grid-gutter is $grid-gutter-width I can't see that we actually need this additional variable

https://github.com/joomla/joomla-cms/blob/06ae97f00a47591f85260ebfd503567824e7482c/build/media_source/templates/site/cassiopeia/scss/tools/variables/_variables.scss#L145-L147

Assuming that I am correct and we don't need this variable I propose to remove it and use grid-gutter-width instead. This will make the css less "cassiopeia-specific" and might even result in the need for less.

Happy to do the work but would like a sanity check from @hans2103 and/or @drmenzelit first that it is indeed a useless variable.

**edit** : I already did a search and replace and compared the generated css and the results are the same

**Comment by hans2103** [comment]
History of these two variables:

PR [4.0] New Frontend (Aurora) Template #14864
add
```
// Gutter
$grid-gutter-width-base:             15px !default;
```

PR [4.0] Move Aurora to CSS Grid #16810
add
```
$aurora-grid-gutter:                 15px;
```

PR [4.0] Update Bootstrap to beta-1 #17496
change
```
$grid-gutter-width:                  15px !default;
$aurora-grid-gutter:                 $grid-gutter-width;
```

PR [4.0] Rename aurora #18418
rename Aurora to Cassiopeia
```
$grid-gutter-width:                  15px !default;
$cassiopeia-grid-gutter:          $grid-gutter-width;
```

[Commit 💄 override Bootstrap 4 px sizes by em sizes
](https://github.com/joomla/joomla-cms/commit/23340f206965398b3aea17f6df6a78eda97673ac)change pc => em
```
$grid-gutter-width:                  1em !default;
$cassiopeia-grid-gutter:             $grid-gutter-width;
```


No changes afterwards.

The variable `$grid-gutter-width` is a Bootstrap 5 variable and set to 1.5rem in bootstrap itself.
https://github.com/twbs/bootstrap/blob/a9a89debc7535a1c5857ced28c1002a2f682889f/scss/_variables.scss#L466

In Cassiopeia an override is created to change this variable to 1em.

I agree with the suggestion made by @brianteeman and replace `$cassiopeia-grid-gutter` by `$gtid-gutter-width`

**Comment by brianteeman** [comment]
OK thanks for confirming I will submit the PR

**Comment by brianteeman** [comment]
please test #37266
