### ISSUE TITLE
Create new backend module -> Should not be possible when there are no create rights

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#37267]
### Steps to reproduce the issue
Create a new
On Joomal 4.1 - Create a new usergroup. Give this group **acces** (only) to the modules. No 'create' rights. Then log in with a user in this usergroup on the backend.

### Expected result
There should not be an 'Add module to the dashboard' button on the backend control panel.

### Actual result
There is an 'Add module to the dashboard' button on the control panel. It is not possible to add a module, but I think the button to add a module should not be there when creating  a module is not possible (because of ACL).

### System information (as much as possible)
Joomla! 4.1.0
PHP 8.0.16

**Comment by brianteeman** [comment]
please test #37268

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37268 . Thanks in advance.

**Comment by chmst** [comment]
If https://github.com/joomla/joomla-cms/pull/42467 is accepted, this issue is open again

**Comment by Sieger66** [comment]
This issue is not open again because now in 42467 is the code of 37268 integrated.
