### ISSUE TITLE
Media modal preview images too wide (fix included)

### ISSUE THREAD

**Issue by toroworx** [joomla/joomla-cms#37277]
### What needs to be fixed
When using the modal preview for images with large images, images gets cut off. 

### Why this should be fixed
Images only partly visible.

### How would you fix it
https://github.com/joomla/joomla-cms/pull/37276

### Side Effects expected
None as far as I know. I don't know why it was 200% though.

**Comment by RickR2H** [comment]
Has a PR #37276 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37277">issues.joomla.org/tracker/joomla-cms/37277</a>.</sub>
