### ISSUE TITLE
PHP 8.1 Deprecation

### ISSUE THREAD

**Issue by exstreme** [joomla/joomla-cms#37274]
### Steps to reproduce the issue
Turn on error displaying

### System information (as much as possible)

Joomla 4.1 PHP 8.1

Deprecated
: substr(): Passing null to parameter #1 ($string) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: substr(): Passing null to parameter #1 ($string) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: substr(): Passing null to parameter #1 ($string) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: substr(): Passing null to parameter #1 ($string) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: substr(): Passing null to parameter #1 ($string) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: substr(): Passing null to parameter #1 ($string) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: substr(): Passing null to parameter #1 ($string) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: substr(): Passing null to parameter #1 ($string) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
792

Deprecated
: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\JavascriptRenderer.php
on line
808

Deprecated
: Implicit conversion from float -INF to int loses precision in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\DataFormatter\DataFormatter.php
on line
81

**And some deprecations in fields with date:**
Deprecated: Function strftime() is deprecated in C:\OpenServer\domains\joomla.test\libraries\src\Form\Field\CalendarField.php on line 277

**Comment by brianteeman** [comment]
Please re-test with the nightly version - pretty sure most if not all of these have been resolved

**Comment by richard67** [comment]
They are all about the debug bar, i.e. it needs to switch on debug in global configuration in addition to setting display errors to reproduce the issue.

I haven’t tested today, but as far as I remember from recent tests, all these deprecations for the debug bar haven’t been fixed yet.

**Comment by richard67** [comment]
The last one is not about the debug bar but about the calendar. That might be fixed meanwhile, not sure.

**Comment by Quy** [comment]
Related #36772

**Comment by exstreme** [comment]
4.1.1-dev - still reproduce problems with debug and calendar

**Comment by alikon** [comment]
there are some merged PR's upstream  https://github.com/maximebf/php-debugbar/pulls?q=is%3Apr+is%3Aclosed but still not a new version of php-debugbar

**Comment by richard67** [comment]
@alikon Hmm, they have a new release v1.18.0 from February 10 which includes [your upstream PR for PHP 8.1 deprecations](https://github.com/maximebf/php-debugbar/pull/494), but 2 other PRs were merged on February 11. So maybe the v1.18.0 doesn't fix everything, but it should fix a lot and so be a huge progress. Do you want to make the PR to update the CMS to v1.18.0? As far as I saw you also did the last update for the debugbar in last December.

**Comment by alikon** [comment]
please test  #37278

**Comment by alikon** [comment]
the https://github.com/joomla/joomla-cms/pull/37278 cover only the https://github.com/maximebf/php-debugbar part

**Comment by richard67** [comment]
New PR for the debug bar is #37279 . It replaces #37278 .

**Comment by exstreme** [comment]
Deprecated
: Implicit conversion from float -INF to int loses precision in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\DataFormatter\DataFormatter.php
on line
81

tested on https://github.com/joomla/joomla-cms/pull/37279

**Comment by richard67** [comment]
> Deprecated : Implicit conversion from float -INF to int loses precision in C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\DataFormatter\DataFormatter.php on line 81
> 
> tested on #37279

@exstreme You mean that was the only one which was left after you have applied the changes from that PR? In this case your test was successful because the PR only claims to solve the debug bar notices, not the one for the calendar. If that is the case, please go to the issue tracker here https://issues.joomla.org/tracker/joomla-cms/37279 , use the "Test this" button at the top left and then select the right test result and submit. Thanks in advance.

We will leave your issue open until the remaining notice about the calendar field will be solved with another PR.

**Comment by exstreme** [comment]
@richard67 Yes, test was success with debugbar, but one deprecation was still left for the debugbar

**Comment by exstreme** [comment]
![image](https://user-images.githubusercontent.com/18548890/158461396-5957d479-67b9-44a1-97cf-0f922b6b6b6b.png)

**Comment by richard67** [comment]
I just see they will be solved with the next version of the debug bar, which is not available yet. See here the merged PR in their repository: https://github.com/maximebf/php-debugbar/pull/498 . Their latest version 1.18 is from February 10, and that PR was merged on February 11. So for now we have to wait for that version, and my PR can only fix all the other ones except of these 2.

We will leave your issue open until their new version is available.

**Comment by richard67** [comment]
I've subscribed to get notified when they make a new release of the debug bar, so as soon as that happens I can make another PR to fix the remaining deprecation notices.

**Comment by exstreme** [comment]
Deprecated
: Return type of Joomla\Input\Input::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in
C:\OpenServer\domains\joomla.test\libraries\vendor\joomla\input\src\Input.php
on line
149

Should I create new issue or can update this?

**Comment by laoneo** [comment]
@exstreme on which branch do you get that issue as it should be fixed already.

**Comment by exstreme** [comment]
> @exstreme on which branch do you get that issue as it should be fixed already.

4.1.2 stable

**Comment by richard67** [comment]
@laoneo Possibly fixed in the framework but not in the CMS yet, see #37441 .

**Comment by exstreme** [comment]
Still active issues too:

> Deprecated
: Implicit conversion from float -INF to int loses precision in
C:\OpenServer\domains\joomla.test\libraries\vendor\maximebf\debugbar\src\DebugBar\DataFormatter\DataFormatter.php
on line
81

We are waiting for new version of DebugBar

>And some deprecations in fields with date:
Deprecated: Function strftime() is deprecated in C:\OpenServer\domains\joomla.test\libraries\src\Form\Field\CalendarField.php on line 277

**Comment by richard67** [comment]
@exstreme I stated already here https://github.com/joomla/joomla-cms/issues/37274#issuecomment-1068423627 and here https://github.com/joomla/joomla-cms/issues/37274#issuecomment-1068475071 that I am watching their repository and will make a PR here as soon as they made a new release. But that hasn't happened yet. No need to repeat that again and again.

**Comment by exstreme** [comment]
That's why I wrote:
>We are waiting for new version of DebugBar

I was just trying to generalize and update

**Comment by laoneo** [comment]
Please test #37502  which solves the input error.

**Comment by laoneo** [comment]
Please test https://github.com/joomla/joomla-cms/pull/37488 which solves the debug bar issue.

**Comment by Quy** [comment]
> Deprecated: Function strftime() is deprecated in C:\OpenServer\domains\joomla.test\libraries\src\Form\Field\CalendarField.php on line 277

Please test #37373.

**Comment by brianteeman** [comment]
Surely this can be closed now?
