### ISSUE TITLE
[4.1] Installation FAIL

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37285]
### Steps to reproduce the issue
On a completely clean checkout of the 4.1dev branch do the usual composer install and npm ci
Then try to install joomla

### Expected result
![image](https://user-images.githubusercontent.com/1296369/158556892-2f9543e6-187b-4b89-b259-e7cb799b3dcc.png)

### Actual result
![image](https://user-images.githubusercontent.com/1296369/158556997-00f95b7b-ac6f-4f95-acf1-398b96d6f262.png)

### Additional comments
If I change 
https://github.com/joomla/joomla-cms/blob/5eed656b685188b03a1ff537e7f04baed6eeaa3a/installation/template/index.php#L19

to 
` ->registerAndUseStyle('template.installation', 'installation/template/css/template' . ($this->direction === 'rtl' ? '-rtl' : '') . '.css') 
`

Then I get the expected result. 

Has something changed or am I going mad?

**Comment by chmst** [comment]
> On a completely clean checkout of the 4.1dev branch do the usual composer install and npm ci
Then try to install joomla

No problem here. Working on win11, xampp, php 8.0.

**Comment by brianteeman** [comment]
weird

**Comment by chmst** [comment]
I have no idea. The latest commit in my branch ist this https://github.com/joomla/joomla-cms/pull/37279, maybe it solved the problem for me?

**Comment by richard67** [comment]
> I have no idea. The latest commit in my branch ist this #37279, maybe it solved the problem for me?

That should not be the case. That commit was only for the debug bar.

**Comment by dgrammatiko** [comment]
@brianteeman what's your local server's setup? eg localhost but the current installation is a folder (or folders) deeper?

**Comment by brianteeman** [comment]
localhost/joomla-cms

**Comment by brianteeman** [comment]
it's weird because the nightly build installs fine. so it must be something in the npm build scripts. gave up trying to work it out for now.

**Comment by dgrammatiko** [comment]
@brianteeman this is a bug your proposal is correct. My bad

Check https://github.com/joomla/joomla-cms/pull/37292

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37292 . Thanks in advance.

**Comment by chmst** [comment]
How then is it working for me on a fresh branch? Strange.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37285">issues.joomla.org/tracker/joomla-cms/37285</a>.</sub>

**Comment by richard67** [comment]
Yes, I am wondering about the same https://github.com/joomla/joomla-cms/pull/37292#issuecomment-1069089291

**Comment by brianteeman** [comment]
are you in a subdirectory?

**Comment by dgrammatiko** [comment]
@chmst @brianteeman @richard67 my guess is that somehow the `$relative` argument is passed wrongly here: https://github.com/joomla/joomla-cms/blob/8f862d6ee33b00df6781bb9442366599bb428c3a/libraries/src/HTML/HTMLHelper.php#L412
from here: https://github.com/joomla/joomla-cms/blob/8f862d6ee33b00df6781bb9442366599bb428c3a/libraries/src/WebAsset/WebAssetItem.php#L349

OR the installation template options (either inheritable or parent) are wrongly set

**Comment by richard67** [comment]
No, I'm not in a subdirectory. I have an Apache Vhosts environment where Joomla is in the root of the particular VHost.

**Comment by richard67** [comment]
@dgrammatiko Hmm, the method is named "isPathAbsolute", but it returns true if the given path exists below the Joomla root, i.e. is relative, and the doc block says "Check if the Path is relative to /media folder or absolute", which sounds as if it should do that, but then the name of that method would be wrong.

I would know whom to ask now, but I fear that one is currently not available due to reasons (sad).

**Comment by dgrammatiko** [comment]
@brianteeman could you please add 

```php
		var_dump([is_file(JPATH_ROOT . '/' . $path) => $path]);
```
before https://github.com/joomla/joomla-cms/blob/8f862d6ee33b00df6781bb9442366599bb428c3a/libraries/src/WebAsset/WebAssetItem.php#L352 and share the results for the installation page?

@richard67 sadly yes

**Comment by chmst** [comment]
I am in xampp/htdocs/joomla-4 - a new empty directory, pulled the latests 4.1-dev, so everything as usual.

**Comment by brianteeman** [comment]
The results on a working install in the subdirectory are 
```

array(1) {
  [1]=>
  string(38) "installation/template/css/template.css"
}
array(1) {
  [0]=>
  string(50) "vendor/joomla-custom-elements/joomla-alert.min.css"
}
array(1) {
  [0]=>
  string(18) "system/core.min.js"
}
array(1) {
  [0]=>
  string(46) "vendor/webcomponentsjs/webcomponents-bundle.js"
}
array(1) {
  [0]=>
  string(27) "system/keepalive-es5.min.js"
}
array(1) {
  [0]=>
  string(29) "system/fields/validate.min.js"
}
array(1) {
  [0]=>
  string(26) "system/messages-es5.min.js"
}
array(1) {
  [0]=>
  string(36) "system/joomla-core-loader-es5.min.js"
}
array(1) {
  [0]=>
  string(23) "system/keepalive.min.js"
}
array(1) {
  [1]=>
  string(36) "installation/template/js/template.js"
}
array(1) {
  [0]=>
  string(22) "system/messages.min.js"
}
array(1) {
  [0]=>
  string(32) "system/joomla-core-loader.min.js"
}

```

**Comment by brianteeman** [comment]
and the results with the current (non-working) code is
```

array(1) {
  [1]=>
  string(12) "template.css"
}
array(1) {
  [0]=>
  string(50) "vendor/joomla-custom-elements/joomla-alert.min.css"
}
array(1) {
  [0]=>
  string(18) "system/core.min.js"
}
array(1) {
  [0]=>
  string(46) "vendor/webcomponentsjs/webcomponents-bundle.js"
}
array(1) {
  [0]=>
  string(27) "system/keepalive-es5.min.js"
}
array(1) {
  [0]=>
  string(29) "system/fields/validate.min.js"
}
array(1) {
  [0]=>
  string(26) "system/messages-es5.min.js"
}
array(1) {
  [0]=>
  string(36) "system/joomla-core-loader-es5.min.js"
}
array(1) {
  [0]=>
  string(23) "system/keepalive.min.js"
}
array(1) {
  [1]=>
  string(36) "installation/template/js/template.js"
}
array(1) {
  [0]=>
  string(22) "system/messages.min.js"
}
array(1) {
  [0]=>
  string(32) "system/joomla-core-loader.min.js"
}

```

**Comment by richard67** [comment]
Hmm, the function seems to return true if the path exists as relative path directly below the Joomla root, and false if that is a relative path not directly below the joomla root but somewhere deeper. so the name of the method might be misleading indeed, but it seems to do what it shall do for its usage.

Update: That was for the first test by Brian. In the 2nd test the first output seems to be wrong.

**Comment by dgrammatiko** [comment]
Ok, this doesn't make any sense, 
```
array(1) {
  [1]=>
  string(12) "template.css"
}
```

the result should be

```
array(1) {
  [0]=>
  string(12) "template.css"
}

```

>  but it seems to do what it shall do for its usage.

Not really in the second case it's wrong

**Comment by richard67** [comment]
Yes, I had only commented the first case.

**Comment by dgrammatiko** [comment]
@brianteeman do you have a file `template.css` under the root folder?

**Comment by brianteeman** [comment]
Let me check. Iv been doing some template work, maybe a file got left in the wrong place

**Comment by brianteeman** [comment]
That was it. my bad

I still think the pr is good though

**Comment by richard67** [comment]
> I still think the pr is good though

I agree.

**Comment by dgrammatiko** [comment]
> That was it. my bad

Not really your fault. The heuristics used for deciding how to treat a path is undocumented and this is one of the edge cases that the logic will fail. Might worth couple of lines in the docs

**Comment by brianteeman** [comment]
as soon as you mentioned the subdirectory I just assumed it was another one of your mistakes ;)

**Comment by dgrammatiko** [comment]
Hehe, thankfully that wasn't the case this time but I'm leaving this for the next one

![giphy](https://user-images.githubusercontent.com/3889375/158616933-d951e16b-013f-4de9-b1dc-5776ed6b30e3.gif)
