### ISSUE TITLE
[4.1.1-Dev] Incorrect constant in plugins/system/jooa11y/jooa11y.php

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#37280]
### Steps to reproduce the issue
Install a Joomla nightly build, enable jooa11y plugin to be displayed on all pages, underline the word in any available material and see how the problem looks in the frontend.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/158469453-c846d387-1a48-49c0-93e8-040fb462eb42.png)

The `PLG_SYSTEM_JOOA11Y_TEXT_UNDERLINE_WARNING_INFO` constant should be replaced with `PLG_SYSTEM_JOOA11Y_TEXT_UNDERLINE_WARNING_TIP`.

**Comment by brianteeman** [comment]
grrh - thanks for the heads up will fix it in the morning

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37283 . Thanks in advance.
