### ISSUE TITLE
Action Log email report

### ISSUE THREAD

**Issue by PMWilliams123** [joomla/joomla-cms#37290]
### Steps to reproduce the issue

User action Log / options --events to log - Users
Send an email 

### Expected result

Email should be 

Action | Date | Extension | Name
User xxxxxx changed settings of the component Search | 2022-03-16 10:13:10 UTC | Configuration | Pxxx Wxxx - admin

### Actual result

Latest User Actions
------

Email is:

"_This is the latest action performed by a user on your website.

Action | Date | Extension | Name
 User **<a href='http://j4.glcoord.org/administrator/index.php?option=com_users&task=user.edit&id=461'>xxxx</a>** changed settings of the component Search | 2022-03-16 10:13:10 UTC | Configuration | Pxxxxp Wxxx - admin_"
![screen shot 2022-03-16 at 10 46 40](https://issues.joomla.org/uploads/1/5f698b3fc9542bf5baadea1991a0ab31.png)

### System information (as much as possible)

PHP Built On	Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Database Type	mysql
Database Version	5.7.36-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	Yes
PHP Version	8.0.16
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 4.1.0 Stable [ Kuamini ] 15-February-2022 09:30 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

**Comment by PMWilliams123** [comment]
Your device handled it better than my email 

This is the latest action performed by a user on your website.

What I get is the html see the attached image

Action | Date | Extension | Name
 User "<a href='http://j4.glcoord.org/administrator/index.php?option=com_users&task=user.edit&id=461'>SU-Philip</a>" changed settings of the component Search | 2022-03-16 10:13:10 UTC | Configuration | Philip Williams - admin

Is it the email agent -- blessed outlook!![screen shot 2022-03-16 at 10 45 10](https://issues.joomla.org/uploads/1/4a9a4423d411aa4f325aa33751456aac.png)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37290">issues.joomla.org/tracker/joomla-cms/37290</a>.</sub>

**Comment by brianteeman** [comment]
Is this the same as #35028

**Comment by Quy** [comment]
Closing as duplicate.
