### ISSUE TITLE
Create optional class to disable a[target=_blank]:before

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#37293]
### Is your feature request related to a problem? Please describe.
Every time I add a link with `target="_blank"` in the backend, it forcefully adds the icon indicating the external url. Usually it isn't a problem but occasionally I want to use an icon that better fits the situation or no icon at all. For my custom component, this isn't an issue but whenever I have to do something similar outside of my component I'm forced to either include a custom css file just for this or to live with the icon

### Describe the solution you'd like
A class to disable the icon would be very helpful, something like
```
a[target=_blank].no-target-blank::before {
	display: none !important;
}
```
Or even a modification to the existing style
```
a[target=_blank]:not(.no-target-blank)::before {
	[...]
}
```

**Comment by chmst** [comment]
Removing the icon in your component means that you have other methods for indicating external links? 
Joomla 4 aims to be accessible (AA) and indication external links is mandatory. 
"no-target-blank" is not an option. If you have better icons - which would you suggest?

**Comment by richard67** [comment]
What is the problem with using a custom CSS (user.css)?

**Comment by Chaosxmk** [comment]
I don't really have a concrete answer with what would be a better icon, and while I understand that the icon is being added for a11y functionality I do think it could be helpful in fringe instances. That said, I'm doing a pretty poor job at explaining my reasoning or defending it and maybe it would be best to just handle those fringe instances myself.

**Comment by chmst** [comment]
@Chaosxmk thank you for understanding the reason for the exernal link icon. 
I will close this issue for now. We can re-open it if you have a generic solution for that.
