### ISSUE TITLE
Accessibility cant be changed by users

### ISSUE THREAD

**Issue by PMWilliams123** [joomla/joomla-cms#37291]
### Steps to reproduce the issue

Registered users log into front end and attempt to edit profile 

menu item -- Edit User Profile / link -- index.php?option=com_users&view=profile&layout=edit

### Expected result

The ability for the user to choose their accessibility needs (as can be done in the backend - "Users: Edit / Accessibility Settings") 

### Actual result

NO option to change accessibility settings (Monochrome, High Contrast, Highlight Links, Increase Font Size), have to be done by a backend admin on the users behalf -- (does he take sugar?) that is just wrong.

### System information (as much as possible)

PHP Built On	Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Database Type	mysql
Database Version	5.7.36-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	Yes
PHP Version	8.0.16
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 4.1.0 Stable [ Kuamini ] 15-February-2022 09:30 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36

**Comment by brianteeman** [comment]
Those options ONLY work with the admin template

**Comment by brianteeman** [comment]
If you want similar functionality in the front end then you should use the dedicated plugin that is provided for that. 

System - Additional Accessibility Features

**Comment by richard67** [comment]
So this issue can be closed as expected behaviour?

**Comment by brianteeman** [comment]
absolutely. plus the admin options only work for someone who is logged in.

**Comment by richard67** [comment]
Closing as expected behaviour according to explanation given in previous comments.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37291">issues.joomla.org/tracker/joomla-cms/37291</a>.</sub>

**Comment by PMWilliams123** [comment]
I am sorry but apart from the fact even with System - Additional Accessibility Features enabled alt+a  has no effect it doesn't answer the issue. 

The issue is that users whether disabled or not out to be able to control their own accessibility settings not rely on someone else -- and admin- to do it for them. I am not an accessibility expert but I do feel strongly that less able people should have the option of taking control themselves not have their needs assessed and set by someone else. perhaps you are all to young to remember the program "Does he take sugar"

**Comment by brianteeman** [comment]
> I am sorry but apart from the fact even with System - Additional Accessibility Features enabled alt+a has no effect it doesn't answer the issue.

It is ctrl alt a

> The issue is that users whether disabled or not out to be able to control their own accessibility settings not rely on someone else

Of course they should not rely on someone else. But once again I repeat. The settings you referred to that are in the user profile in the admin side of joomla are ONLY for the admin area of joomla. They do nothing in the front end of the site.

>  perhaps you are all to young to remember the program "Does he take sugar"

Absolutelt remember it but as I have said it is not releavant here.

**Comment by nibra** [comment]
> They do nothing in the front end of the site.

That seems to be the core of the issue. This issue should be seen as a reasonable feature request.

**Comment by brianteeman** [comment]
@nibra Think about it, look at the code in the user profile and try the plugin.

1. That code requires someone to be logged in. Surely it is better to have this functionality (and more) that is available to everyone
2. That code requires the template to be aware of the options. Surely it is better to have functionality (and more) that is available with any template
3. The plugin wasn't added just to bloat joomla it is there for the purpose and it does its job. Sure it could be improved but thats not the issue here.
4. Even if an admin saves the options on behalf of a user it wont do anything as the site template is not aware of them.

**Comment by PMWilliams123** [comment]
I do apologise. I have misunderstood. I had not realised those accessibility options only apply to users accessing the backend and have nothing to do with the frontend so clearly only configurable by backend users. That was not clear to me, and maybe others.I will try the ctl alt a when I am stationery and in front of my pc.PhilipSent from my Galaxy
-------- Original message --------From: Brian Teeman ***@***.***> Date: 17/03/2022  07:37  (GMT+00:00) To: joomla/joomla-cms ***@***.***> Cc: Philip ***@***.***>, Author ***@***.***> Subject: Re: [joomla/joomla-cms] Accessibility cant be changed by users (Issue
  #37291) 

I am sorry but apart from the fact even with System - Additional Accessibility Features enabled alt+a has no effect it doesn't answer the issue.

It is ctrl alt a

The issue is that users whether disabled or not out to be able to control their own accessibility settings not rely on someone else

Of course they should not rely on someone else. But once again I repeat. The settings you referred to that are in the user profile in the admin side of joomla are ONLY for the admin area of joomla. They do nothing in the front end of the site.

perhaps you are all to young to remember the program "Does he take sugar"

Absolutelt remember it but as I have said it is not releavant here.

**Comment by PMWilliams123** [comment]
Again forgive my inexperience.. I now have some better understanding  although I have a ways to go to get my head round all the template stuff...PhilipSent from my Galaxy
-------- Original message --------From: Brian Teeman ***@***.***> Date: 17/03/2022  10:49  (GMT+00:00) To: joomla/joomla-cms ***@***.***> Cc: Philip ***@***.***>, Author ***@***.***> Subject: Re: [joomla/joomla-cms] Accessibility cant be changed by users (Issue
  #37291) 
@nibra Think about it and look at the code.

That code requires someone to be logged in. Surely it is better to have this functionality (and more) that is available to everyone
That code requires the template to be aware of the options. Surely it is better to have functionality (and more) that is available with any template
The plugin wasn't added just to bloat joomla it is there for the purpose and it does its job. Sure it could be improved but thats not the issue here.
Even if and admin saves the options on behalf of a user it wont do anything as the site template is not aware of them.

**Comment by brianteeman** [comment]
No problem at all. 

We can definitely look at adding a description that they are the settings for the admin only. It is not obvious.

**Comment by PMWilliams123** [comment]
Joomla knows which user has backend accessl doesn't? In which case could the options only be available for users with backend access. Or perhaps that is the case.Regds PhilipSent from my Galaxy
-------- Original message --------From: Brian Teeman ***@***.***> Date: 17/03/2022  11:15  (GMT+00:00) To: joomla/joomla-cms ***@***.***> Cc: Philip ***@***.***>, Author ***@***.***> Subject: Re: [joomla/joomla-cms] Accessibility cant be changed by users (Issue
  #37291) 
No problem at all.
We can definitely look at adding a description that they are the settings for the admin only. It is not obvious.
