### ISSUE TITLE
Showon not working when used within list option

### ISSUE THREAD

**Issue by toroworx** [joomla/joomla-cms#37299]
### Issue
As [explained in the manual,](https://docs.joomla.org/List_form_field_type#Showon_attribute_for_list_options) you can use `shown` attributes within `<option>` tags since this PR: https://github.com/joomla/joomla-cms/pull/18998
This works for `com_config` if you try, but it does not (always) work for other components.

### Steps to reproduce the issue
- This does not work, when used with a 'new' component (or e.g. with com_banners for this example), when you follow the directions of the mentioned manual. This is because `/media/system/js/showon.min.js` is not automatically loaded. I think there's either a bug, or the manual is missing this info.
- Check Chrome DevTools > Sources > `your/site/media/system/js`, which should show `showon.min.js`. 
It's visible at `https://website/administrator/index.php?option=com_config`. But if you go to `https://website/administrator/index.php?option=com_banners&view=banner&layout=edit` you'll see `showon.min.js` is missing. 

### Steps to fix the issue
Either update the manual or the Joomla code. I don't know what's preferred.
If you'll manually add the following to your existing component's `joomla.asset.json`:
```	
{
	"name": "showon",
	"type": "script",
	"dependencies": [
		"core",
		"showon.es5"
	],
	"uri": "system/showon.min.js",
	"attributes": {
		"type": "module"
	},
	"version": "bfc733e48a923aaffb3d959cd04f176bad7d7d52"
}
```

And load this script with the web asset manager:
```
$wa = $this->document->getWebAssetManager();
$wa->useScript('showon');
```

Then it should work as expected.

### Attention
It's key for this bug report to try the `shown` feature within an `<option>` tag, because it does always work within a `<field>` tag.

### System information
Joomla! 4.1.0 Stable

**Comment by dgrammatiko** [comment]
~~Expected behaviour. If you need the `showon` you have to load the script. Also you don't have to copy the system JSON to your component, just load it directly `$this->document->getWebAssetManager()->useScript('showon')`~~

Joomla is not following the old patterns, eg loading JS/CSS global, if the developer needs a specific JS/CSS they have to load it, per instance but this is a bug

**Comment by dgrammatiko** [comment]
Please test https://github.com/joomla/joomla-cms/pull/37300

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37300 . Thanks in advance.

**Comment by richard67** [comment]
Re-opening as the pull request was closed.

**Comment by richard67** [comment]
New PR is #37451 .
