### ISSUE TITLE
[4.1] Error in Joomla JsonApiView constructor

### ISSUE THREAD

**Issue by prtuson** [joomla/joomla-cms#37305]
### Steps to reproduce the issue
When creating a JsonApi view using the MVCFactory an error is produced if the optional options are not completed with a contentType.

### Expected result
No error should be raised.

### Actual result
An error is raised and the processing stops.

### System information (as much as possible)
The constructor code in JsonApiView (within the MVC Library) is:
	if (\array_key_exists('contentType', $config)) {
		$this->type = $config['contentType'];
	}
   	if ($this->serializer === null)	{
    		$this->serializer = new JoomlaSerializer($this->type);
    	}

### Additional comments
It should be:
	if (\array_key_exists('contentType', $config)) {
	    $this->type = $config['contentType'];
   	    if ($this->serializer === null)	{
    		$this->serializer = new JoomlaSerializer($this->type);
    	    }
	}

So that the serializer is only called if the contentType option has been supplied.

**Comment by Hackwar** [comment]
I created a PR: #43179 Closing this issue.
