### ISSUE TITLE
[4.x] (newest version 17.03.22) Redirect comes back after Deletion

### ISSUE THREAD

**Issue by L00tz1ffer** [joomla/joomla-cms#37301]
### Steps to reproduce the issue
I set up a redirect from ```site.com/index.php?blablabla``` to ```site.com/request```
for this i used the ```reweite url``` feature from the menu ```system>config>site```
so i enabled this feature and went to the  ```system>manage>redirects``` menu and set up this redirect as described above.
> more in Actual Result

### Expected result
the expected result was to rewrite the url, in a sense, that i could type ```site.com/request``` in the browser and get shown ```site.com/index.php?blablabla```

### Actual result
the actual result is, this operation changed every link in my site to ```site.com/request```  but since the target url does not exist, it redirects me to a 404 page.

Further more, i did NOT disable this "redirect" which is more a rewrite for deat urls as i found out, i DIRECTLY DELETED this entry without disabling it first.

after this was showing no effect i deleted the Database Entry, hoping this would bring the end

guess what it did not...

so now this wasted my installation totally - everytime i reenable the url rewrite feature again the db entries spawn again and i have to delete them by hand.

>there was no effect by deleting cache

>No effect by deleting db entries

>only effect - since this is the method i use is disabling url rewrite til today...

i dont know that to do to get rid of this absurd error, i dont know the file hierarchy that good, that i would have an idea where the textfile is where this problem lies....
but since i need the url rewrite feature for other stuff this is very disgusting...

### System information (as much as possible)
Strato Basic Hosting instance (with 20gb storage, 3x domain, 1x ssl cert)

#### BAN IN THE FORUM
Furhter more i tried to register myself in the forum ```forum.joomla.org``` to discuss this bug there and warn other people tapping into this.... 
what did i get? Guess what -> A Ban because my email (same as my github email) seems to your system like SPAM ?!?!?!

#### Sorry for my Bad english

>If needed i may provide a twitch stream or some kind of discord or zoom meeting to help fixing this issue

**Comment by L00tz1ffer** [comment]
ok, so as of now i hope i fixed this issue. 

i guess but i cannot tell exactly, that the solution was to manually reupload the ```.htaccess``` file

**Comment by chmst** [comment]
Thanks for clarifying that. I am closing the issue for now, we can re-open it, if needed.
