### ISSUE TITLE
Feature request – “Save & Do Not Close” button (Apply) for frontend article editing

### ISSUE THREAD

**Issue by oorzaak** [joomla/joomla-cms#37312]
### Steps to reproduce the issue

– Create or edit an article using frontend article editing, in a Joomla 4 core installation.

– Try to save the article without closing the edit view.

### Expected result

When editing an article in the backend, you can choose between a “Save” button and a “Save & Close” button. This adds to a good user experience. It would make sense to have both options in the frontend as well.

### Actual result

In the frontend, you only have one button, which has the label “Save” but in fact acts as “Save & Close”. There is no way to save and stay in the edit view.

### System information (as much as possible)

Joomla 4.1.0

### Additional comments

I had several customers asking for a “Save & do NOT Close” button in the frontend. 

I suppose that this corresponds with the task: article.apply

This also applies to J.3 but of course it would be most effective if this is added to J.4.

**Comment by BhavyaT-135** [comment]
Hey, @oorzaak Can I work on this issue?? 😃

**Comment by richard67** [comment]
> Hey, @oorzaak Can I work on this issue?? 😃

No need to ask. Just do it.

**Comment by BhavyaT-135** [comment]
> > Hey, @oorzaak Can I work on this issue?? 😃
> 
> No need to ask. Just do it.

I followed the steps mentioned above and created a sample article. Although, I didn't have any problem using either the "Save" or the "Save & Close" button. They seem to work fine :)

**Comment by richard67** [comment]
I guess you have tested in backend but the issue here is for frontend editing.

**Comment by roland-d** [comment]
@BhavyaT-135 Could you check the front-end and propose a pull request? I would love to have this in version 4.2.

**Comment by oorzaak** [comment]
> I guess you have tested in backend but the issue here is for frontend editing.

I mean frontend editing, indeed. I'm sure that many people would be happy to have this feature :smile:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37312">issues.joomla.org/tracker/joomla-cms/37312</a>.</sub>

**Comment by BhavyaT-135** [comment]
> @BhavyaT-135 Could you check the front-end and propose a pull request? I would love to have this in version 4.2.

Sure sir,  I'll give it a shot.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37362 . Thanks in advance.
