### ISSUE TITLE
Joomla 4.1 upgrade from 3.8.5 -- missing component after full upgrade

### ISSUE THREAD

**Issue by wherbjr35** [joomla/joomla-cms#37315]
Good evening,
Pardon me if this question is not in the right forum for Joomla support.  

I'm working in a hosted environment where i had Joomla 3.8.5 running kinda unattended. When logging into my hosting CP, i noticed php versions were marked as 'obsolete', so i picked the version closest to what i had (not the latest/max available -- which is 8.1.4.  When i chose this, my site crashed of course.  I first toggled the various php versions available, but nothing resolved the issue.  I then found and uploaded the 4.1.0 Update package, and seems to make some progress. I landed on a page where i was told php 7.2.5 min was required.  As i landed on the suitable version of php in my CP, i had other php errors in the browser that led me to upload the FULL 4.1.0 stable package.  This is where i am now.  ![screen shot 2022-03-19 at 05 53 19](https://issues.joomla.org/uploads/1/128c49db27500f1ff9f0afc02134057b.png)
I did check permissions on the file ComponentHelper.php and found them set as 755, i tried as 777, but no difference, so i am doubting this file is root cause. Any ideas on troubleshooting this?

Thank you,

WH

**Comment by zero-24** [comment]
an Upgrade to 4.x has to go via the latest 3.10.6. The Upgrade is not directly possible from 3.8.5 please restore a backup, update to the latest 3.10 release starting from there you can review and check whether the Upgrade to j4 is possible.

https://docs.joomla.org/Joomla_3.x_to_4.x_Step_by_Step_Migration

**Comment by richard67** [comment]
And what means uploaded the update? Using the „Upload and Update“ functionality of the Joomla Update Component (right), or just uploading and unpacking the zip (wrong)?

**Comment by richard67** [comment]
And of course @zero-24 is right. Update from something before 3.10 to 4 is not supported and will for sure cause missing core extensions which would have been added with an update to 3.10.

**Comment by richard67** [comment]
Closing as not a core issue. For further help please use the support forum. Thanks for your understanding.
