### ISSUE TITLE
Schedules Tasks

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#37313]
### Steps to reproduce the issue

1. Create Demo Task - Sleep 
2. Select `Cron Expression Advanced` as `Execution Rule`
3. Do not select all values in area `Crone match`.

### Expected result

You see a message about what you have to select.

### Actual result

You see 

![m](https://user-images.githubusercontent.com/9974686/159076411-820aa3ec-f089-43b8-b11e-65da0d8a9d02.png)

**Comment by richard67** [comment]
Could be a good first task for a potential GSoC student.

**Comment by keshavgbpecdelhi** [comment]
Can I go ahead with this?

**Comment by richard67** [comment]
> Can I go ahead with this?

 No need for asking. Just do it.

**Comment by keshavgbpecdelhi** [comment]
I was trying to set up this , but the command not found popped up on composer. Need Assistance.

![image](https://user-images.githubusercontent.com/56075233/159124049-36b39429-ab0c-44ad-b373-b805c69a1943.png)

**Comment by richard67** [comment]
@keshavgbpecdelhi Well, you have to install the Composer software first before you can use it. Same later for node.js before you can use npm. It does not come with a standard Webserver software.

**Comment by keshavgbpecdelhi** [comment]
I have done the installation part, can you please tell how to go to the above mentioned page (the path).
I can see this :
![image](https://user-images.githubusercontent.com/56075233/159126717-adc2c825-c875-4985-9b7c-0921bd0e14de.png)

**Comment by richard67** [comment]
@keshavgbpecdelhi The folder shown in your screenshot should be the root of a local webserver or a subfoder of that root. You then just browser the URL for that local web site, e.g. "http://localhost" if in the webserver root, or "http://localhost/somesubfolder" if in a sub folder.

But honestly: This here is an issue tracker for Joomla issues and not a support forum for teaching how to install Joomla.

If you are a potential GSoC 2022 student, please join our channels on Glip (RingCentral) and put your questions there, so we do not pollute this issue with installation questions and other students can benefit from the answers, too.

Thanks in advance.

**Comment by teekhandekar** [comment]
@astridx Can I work on this ?

**Comment by Quy** [comment]
Please test PR #37350.

**Comment by bembelimen** [comment]
Reopened as the PR is on hold.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37536 . Thanks in advance.
