### ISSUE TITLE
[3.10] tinymce does not display icons for editor-xtd plugin

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#37318]
### Steps to reproduce the issue
add  svg icon to button settings - e.g.:    
```
$button->icon    = 'tip';
$button->iconSVG = '<svg ... </svg>' 
```

### Expected result
editor toolbar should display button with icon 

### Actual result
on joomla v3.10. icon ist missing

![buttons-v3](https://user-images.githubusercontent.com/69053785/159123719-ffa2871d-e6b9-4940-bac2-c984379f6d30.jpg)

on Joomla4 with exacly same plugin-code display is OK:
![buttons-v4](https://user-images.githubusercontent.com/69053785/159123746-29c07366-b1f3-4ed0-9534-48c83d24d3ed.jpg)

### System information (as much as possible)
tinymce version on joomla 3 displayed is "4.5.12'
if I use svg e.g. from pagebeak editor-xtd plugin display of icon is also missing.
Can anybody explain what goes wrrong?

**Comment by jschmi102** [comment]
hi,
now I found how this works with joomla V3.
you will have define a property: ` $button->name = 'icon-name';`  
eg. `$button->name  = 'lamp'; `
This setting will result in: `<i class="mce-ico mce-i-none icon-lamp"></i>`
class "_icon-lamp_' is defined in isis-template as: 
 `.icon-lamp::before { content: "\74"; }` and using font family "icoMoon" which contains all sorts of icon-like chars. (content "\74" displays a lamp). 

You will see then a correct display: 
![buttons-v3](https://user-images.githubusercontent.com/69053785/159127799-a0918767-c8cc-4e8f-886c-306c594c3c47.jpg)

**Comment by richard67** [comment]
@jschmi102 So the issue can be closed?

**Comment by jschmi102** [comment]
OK
