### ISSUE TITLE
Unify the modal fields and make them simpler

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#37327]
Unify the modal fields and abstract most of the functions in a base class. This is a placeholder issue for pr #20788 so somebody can take it over or make a new one. Maybe @dgrammatiko :-)

**Comment by richard67** [comment]
Related discussion see https://github.com/joomla/joomla-cms/discussions/32473

**Comment by laoneo** [comment]
Should we keep then the issue open?

**Comment by richard67** [comment]
It's on you. I'd prefer to close it because one issue less, but if you feel in the discussions it is not visible enough you might want to leave it open.

**Comment by laoneo** [comment]
Made a comment in the discussion and will close this one here then.
