### ISSUE TITLE
[4.1.1 RC1] File Checksum Failed

### ISSUE THREAD

**Issue by conseilgouz** [joomla/joomla-cms#37339]
### Steps to reproduce the issue

Set your config so that "update source" is : 
- Update Channel = testing
- Minimum stability : Release candidate
- Update from J 4.1.0 to J4.1.1 RC

### Expected result

Joomla updated

### Actual result

After Pre-update check, when  clicking on "Start update" button, "File Checksum Failed" error

![Joomla_update_to_rc_error](https://user-images.githubusercontent.com/19435246/159281478-5a49544e-6265-4db1-9a7c-943450e8b87d.jpg)

**Comment by zero-24** [comment]
Thanks for the report. We have just patched it on the update server here. It might take some time to go out via all the CDNs: https://github.com/joomla/update.joomla.org/pull/239

Please keep this issue open as the real message should have been that the download failed not that the checksums did not match and that should be patched
