### ISSUE TITLE
Joomla 3.10.6 error when trying to send an email or reset a password.

### ISSUE THREAD

**Issue by Sparkkkkie** [joomla/joomla-cms#37332]
### Steps to reproduce the issue
Get joomla 3.10.6 
Try to send an email or click the reset password button on the site itself.
Get the error: Fatal error: Type of JException::$file must be string (as in class Exception) in C:\xampp\htdocs\libraries\legacy\exception\exception.php on line 18 

### Expected result
That it sends an email.

### Actual result
Getting the error: Fatal error: Type of JException::$file must be string (as in class Exception) in C:\xampp\htdocs\libraries\legacy\exception\exception.php on line 18

### System information (as much as possible)
Xampp.
SSD

**Comment by zero-24** [comment]
Hi, looks like you are running php 8.1 please apply the changes here and try again: https://github.com/joomla/joomla-cms/pull/37074

But that will just show the real issue so please share some more infos from the issue.

**Comment by Sparkkkkie** [comment]
> Hi, looks like you are running php 8.1 please apply the changes here and try again: #37074
> 
> But that will just show the real issue so please share some more infos from the issue.

Huh? What do you mean? What should i do to fix this, sorry im pretty new to php.

**Comment by zero-24** [comment]
Please go here https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/37074.diff and manually apply that changes to your instance. It will be shipped with the upcomming 3.10.7 release. But that only allows to show the error message for the real issue you have so please apply that change and show the error message you get :)

**Comment by Sparkkkkie** [comment]
> Please go here https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/37074.diff and manually apply that changes to your instance. It will be shipped with the upcomming 3.10.7 release. But that only allows to show the error message for the real issue you have so please apply that change and show the error message you get :)

Alr but how can i apply those changes? Sorry im new.

**Comment by Sparkkkkie** [comment]
> Please go here https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/37074.diff and manually apply that changes to your instance. It will be shipped with the upcomming 3.10.7 release. But that only allows to show the error message for the real issue you have so please apply that change and show the error message you get :)

Are you still here? I really need to fix this.

**Comment by zero-24** [comment]
> > Please go here https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/37074.diff and manually apply that changes to your instance. It will be shipped with the upcomming 3.10.7 release. But that only allows to show the error message for the real issue you have so please apply that change and show the error message you get :)
> 
> Alr but how can i apply those changes? Sorry im new.

Remove the things that are marked as "red" and add the lines that are green here: https://github.com/joomla/joomla-cms/pull/37074/files

**Comment by Sparkkkkie** [comment]
> > > Please go here https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/37074.diff and manually apply that changes to your instance. It will be shipped with the upcomming 3.10.7 release. But that only allows to show the error message for the real issue you have so please apply that change and show the error message you get :)
> > 
> > 
> > Alr but how can i apply those changes? Sorry im new.
> 
> Remove the things that are marked as "red" and add the lines that are green here: https://github.com/joomla/joomla-cms/pull/37074/files

Where do i have to add them? In what file?

**Comment by Sparkkkkie** [comment]
> > > Please go here https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/37074.diff and manually apply that changes to your instance. It will be shipped with the upcomming 3.10.7 release. But that only allows to show the error message for the real issue you have so please apply that change and show the error message you get :)
> > 
> > 
> > Alr but how can i apply those changes? Sorry im new.
> 
> Remove the things that are marked as "red" and add the lines that are green here: https://github.com/joomla/joomla-cms/pull/37074/files

?

**Comment by ChristineWk** [comment]
I think @zero-24 means:

To remove "red" lines 29-46 and lines 57-74 in: /libraries/legacy/exception/exception.php

**Comment by Sparkkkkie** [comment]
> > > Please go here https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/37074.diff and manually apply that changes to your instance. It will be shipped with the upcomming 3.10.7 release. But that only allows to show the error message for the real issue you have so please apply that change and show the error message you get :)
> > 
> > 
> > Alr but how can i apply those changes? Sorry im new.
> 
> Remove the things that are marked as "red" and add the lines that are green here: https://github.com/joomla/joomla-cms/pull/37074/files

Thanks! That worked! Im now closing this issue as it has now been fixed.
