### ISSUE TITLE
[4.1] Wrong language constats for media plugins

### ISSUE THREAD

**Issue by wojsmol** [joomla/joomla-cms#37343]
### What needs to be fixed
We  need to fix the language constants in the `plg_media_action` language files and in the php/js files respectively. After `PLG_MEDIA` part, dash is used everywhere instead of hyphen (`PLG_MEDIA-`)

### How would you fix it
Replace `PLG_MEDIA-` with `PLG_MEDIA_` in all places
### Side Effects expected
N/A

**Comment by brianteeman** [comment]
Is this just for consistency or is there a bug?

**Comment by wojsmol** [comment]
This not causing any error. It's just a matter of maintaining convention.

**Comment by Srijan-Chak012** [comment]
Hey, I'd like to start with this, can you guide me on how to get started?

**Comment by laoneo** [comment]
This was done on purpose as the media action plugins have as group name `media-action` same as with buttons https://github.com/joomla/joomla-cms/blob/4.1-dev/administrator/language/en-GB/plg_editors-xtd_article.ini#L8

**Comment by richard67** [comment]
@laoneo So the issue should be closed as expected behaviour?

**Comment by laoneo** [comment]
For me yes, not sure how others feel about. All I wanted to say is that it was done on purpose at the time we made the new media manager.

**Comment by Hackwar** [comment]
As @laoneo says, this is correct the way it is with the plugin groups name. Thus this should be closed.

**Comment by richard67** [comment]
Closing as expected behavior. See previous comments for explanation.

**Comment by wojsmol** [comment]
As a additional note [specification of language files](https://docs.joomla.org/Specification_of_language_files) should be created.
