### ISSUE TITLE
Media List View

### ISSUE THREAD

**Issue by QuotesUK** [joomla/joomla-cms#37359]
### Is your feature request related to a problem? Please describe.
Media. List View. Unable to sort columns.
Name | Size | Dimensions | Date Created | Date Modified

### Describe the solution you'd like
1/ Click on the column heading to sort.
2/ Global Configuration settings to choose default of list view or icon view, and sort preference

### Additional context
Maybe add a counter for number of files in a folder

**Comment by brianteeman** [comment]
#31347 possible duplicate?
