### ISSUE TITLE
[4.x] Image Class

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37357]
### Steps to reproduce the issue
Create an article and add a full article image. Do not add a class.
![image](https://user-images.githubusercontent.com/1296369/159705927-a017bc28-17b1-424e-bdab-a247f18c1896.png)

Visit the site in the front end and view the source of the article

### Expected result

```
<figure class="item-image">
	<img src="...">	</figure>
```

### Actual result
```
<figure class="left item-image">
	<img src=."..">	</figure>

```

Note the additional class 

### Additional comments
Unless you add an actual class to the image then this class of "left" will always be added - even though you have not set it.

Why?

After a lot of digging I discovered that this class is defined in the article options. Buried at the bottom of a page of the artcile editing tab

![image](https://user-images.githubusercontent.com/1296369/159706842-83ca3b2a-1fe7-4b24-a99f-4a8eed6dd7f8.png)

Why?

### How would I solve this?
1. a clean install should not have a value for this class
2. if/when a default class is set in the options then this should be clearly indicated on the full article image field eg

![image](https://user-images.githubusercontent.com/1296369/159707300-ca531601-d633-4f18-9569-a00e80c87712.png)

I spent a long time tracking down where this "left" came from and I consider myself an experienced user.

This is not a good experience

**Comment by drmenzelit** [comment]
> After a lot of digging I discovered that this class is defined in the article options. Buried at the bottom of a page of the artcile editing tab

These options are been there for a long time (intro image float and full text image float in J3) to set the position of the images globally

![grafik](https://user-images.githubusercontent.com/9153168/160085658-8f6eaef8-431e-488d-8fa7-13c98e2b138d.png)

What would you suggest to do? Let the gobal settings empty on new installations?

**Comment by brianteeman** [comment]
In J3 this setting resulted in 
![image](https://user-images.githubusercontent.com/1296369/160088002-48278123-c379-41a7-b0d5-ffbe1167029b.png)

That is what is missing in J4. Some sort of indicator that there is a class being used

**Comment by drmenzelit** [comment]
Oh I see...

**Comment by brianteeman** [comment]
Not only dont you know that there is a global setting being used you dont even know what it is

**Comment by drmenzelit** [comment]
The solution is to add `useglobal="true"` on the fields in \administrator\components\com_content\forms\article.xml
I will prepare a PR

**Comment by brianteeman** [comment]
If only it was that easy

**Comment by drmenzelit** [comment]
![grafik](https://user-images.githubusercontent.com/9153168/160093149-c6593e63-afb7-4589-ac61-5b96cc435574.png)

Do you have another idea? Maybe a note where to find the global settings?

**Comment by brianteeman** [comment]
weird - I am sure I tried that and it didnt work

**Comment by drmenzelit** [comment]
Closing as we have a PR #37368
