### ISSUE TITLE
[4.1] Activity notifications in Scheduled Tasks are disabled by default

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#37361]
### Steps to reproduce the issue
Install the latest build of Joomla 4.1, go to **User Actions Log: Options** - here the only disabled component for sending action notifications is Scheduled Tasks.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/159967674-ac1b3cc7-fff8-4ba0-bb58-c037b54ca500.png)

**Comment by Ddharmani3** [comment]
do we have to make it enabled by default instead of diabled?

**Comment by Ddharmani3** [comment]
do we have to make it enabled by default instead of disabled?

**Comment by Kostelano** [comment]
I think yes. By default, all other components are enabled.

**Comment by brianteeman** [comment]
see #37365
