### ISSUE TITLE
I'm getting an error doing a Restore Joomla! core files

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#37364]
### Problem identified
Could not open /var/www/website/html/libraries/vendor/tobscure/json-api/.git/logs/HEAD for writing.

<img width="1005" alt="Joomla Update -  Administration 2022-03-24 12-48-47" src="https://user-images.githubusercontent.com/1373815/159998393-50ae75f2-0bad-4a68-88e1-382d5bc145c1.png">

Prior to this error is I've been importing article contents manually via CSV. I wouldn't thought it would break Joomla! update by doing CSV import. 

Any thought how to fix this issue? I also check the file that is mentioned in the error and it does exists. The file permission is also right (644).  I also tried to upload a fresh copy of libraries folder from the Joomla! 4.1.0 update zip file but the error still appears. I did restore Joomla! core files several times before when I was working on my com_content custom override without an issue until I was importing articles to db manually.

Any help or hint how to fix it would be greatly appreciated and besides this might help other people who have this issue later on.

Thanks!

**Comment by brianteeman** [comment]
>  I also check the file that is mentioned in the error and it does exists.

It should not exist. It is not part of the distributed release of Joomla.

**Comment by frogydiak** [comment]
> > I also check the file that is mentioned in the error and it does exists.
> 
> It should not exist. It is not part of the distributed release of Joomla.

Oh wow! Yes, it must be auto created by my PhpStorm IDE. I just deleted .git folder and the update worked again.

Thanks Brian!
