### ISSUE TITLE
[4.1] Media Downloads

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37369]
### Steps to reproduce the issue
In an article use the xtd-editor media button to open the media manager.
Upload a pdf file that has spaces in the name eg "20 May 2021 Minutes.pdf"
Insert the file with the download option
Repeat the above with another pdf that this time has no spaces in it eg "20May2021Minutes.pdf"

![image](https://user-images.githubusercontent.com/1296369/160102313-e300f799-c2ad-4d77-b178-6f02ea1e1b03.png)

### Expected result
Clickable links to download the pdf with the filename in the text

### Actual result
The file with spaces in it loses everything between the first and second space

![image](https://user-images.githubusercontent.com/1296369/160102672-3da029f9-56ef-41ec-ada9-adf4248d6eff.png)

### Additional comments
I believe the relevant code is

https://github.com/joomla/joomla-cms/blob/f9cb42d60e60d10b675ed735dcfe1aa10cdd360b/build/media_source/system/js/fields/joomla-media-select.w-c.es6.js#L245-L250

**Comment by dgrammatiko** [comment]
```js
 } else { 
   const name =  Joomla.selectedMediaFile.url.substr(0, Joomla.selectedMediaFile.url.lastIndexOf('.'));
   outputText = `<a download href="${Joomla.selectedMediaFile.url}">${Joomla.Text._('JFIELD_MEDIA_DOWNLOAD_FILE').replace('{file}', name)}</a>`; 
 } 
```

**Comment by brianteeman** [comment]
@dgrammatiko almost. It is now displayed with the %20 characters

**Comment by dgrammatiko** [comment]
```js
const name =  Joomla.selectedMediaFile.url.substr(0, Joomla.selectedMediaFile.url.lastIndexOf('.')).replace(/\%20/, ' ');
```

**Comment by brianteeman** [comment]
Still not right. I will leave it to someone else to fix

**Comment by Vanshitasingh** [comment]
@brianteeman this might work:
`const name =  Joomla.selectedMediaFile.url.substr(0, Joomla.selectedMediaFile.url.lastIndexOf('.')).replace(/%20/g, " "); `

**Comment by anmode** [comment]
could I solve this?
