### ISSUE TITLE
No feedback given when attempting to create a tag that exists

### ISSUE THREAD

**Issue by ConfidantCommunications** [joomla/joomla-cms#37377]
### Steps to reproduce the issue
1. Create a tag, save and close. 
2. Create a new tag with same name. Click Save & Close.

### Expected result
Joomla should report "That tag already exists. Please choose a different name".

### Actual result
The page reloads, and the title field is populated. No message is shown.

### System information (as much as possible)
Joomla 4.1.0

**Comment by brianteeman** [comment]
Can not replicate

![image](https://user-images.githubusercontent.com/1296369/160170512-8e13ecc3-98e7-4262-b8f2-ad831a789695.png)

**Comment by drmenzelit** [comment]
Can't replicate either
![grafik](https://user-images.githubusercontent.com/9153168/160171059-0032f6f1-76be-4e62-b490-1384ca7ac405.png)

**Comment by ConfidantCommunications** [comment]
I just tried again. Now I am noticing that the error message flashes very quickly and disappears.

**Comment by ConfidantCommunications** [comment]
Inspecting the code, the #system-message-container is set to display:none. If I set that to display:block I can see the message and click the X button. Doing that removes the &lt;joomla-alert&gt; element.

**Comment by ConfidantCommunications** [comment]
I'm on Firefox Mac 98.02

**Comment by brianteeman** [comment]
Tested again using Firefox Mac 98.02 and I still cannot replicate your findings and everything works as expected.

**Comment by ConfidantCommunications** [comment]
Thanks

**Comment by drmenzelit** [comment]
Closing as the issue can't be replicated. Please feel free to reopen, if you have more information.
