### ISSUE TITLE
Admin lists with double row records (items displayed over two rows) cannot use grid checkboxes 

### ISSUE THREAD

**Issue by aschkenasy** [joomla/joomla-cms#37370]
### Steps to reproduce the issue
- in any list tmpl, in the tables <tbody> add a secondary <tr> without grid checkbox
- navigate to admin list
- select the second checkbox

### Expected result
only second checkbox should be checked

### Actual result
second and fourth checkboxes are checked

### System information (as much as possible)
vanilla 4.1.0 stable installation
php 8.0.16
Apache 2.4.52
(lando lamp container)

### Additional comments
This happens for any component.
seemingly connected to `class="row<?php echo $i % 2; ?>"` as without it, it works as expected.

simplest way to reproduce:

in `administrator\components\com_content\tmpl\articles\default.php` in the `<tbody>` add 
```
<tr class="row<?php echo $i % 2; ?>">
    <td class="d-none d-lg-table-cell">
        <?php echo (int) $item->id; ?>
    </td>
</tr>
```
before the `<?php endforeach; ?>`

clicking on the second row produces the bug.

remove the `class="row<?php echo $i % 2; ?>"` class and it works fine.

**Comment by drmenzelit** [comment]
I can't follow... what are you trying to achieve? What is the purpose of this new table row?

**Comment by aschkenasy** [comment]
any item is currently displayed as single row in the list table. however, in template overrides (or in custom components) item info might need to be displayed over two rows. (imagine if you want to show the introtext of an article). in table design (as atum template is) this can be achieved by adding the additional row  with a colspan td where this info can be displayed.
however, that tr cant have the row class which of course would be a problem for styling etc.

**Comment by aschkenasy** [comment]
I think the real issue is that the js relies on some odd calculations involving class names...

**Comment by aschkenasy** [comment]
by definition, the checkbox has an id, so the Joomla.isChecked(this.checked); shouldn't be bothered at all with class names

**Comment by brianteeman** [comment]
I dont get what you are trying to do either. There are lots of uses in core where a cell is on multiple lines without needing to be in a second row.

**Comment by aschkenasy** [comment]
![github](https://user-images.githubusercontent.com/2855207/160199122-140120b7-3ede-4501-98f2-3a9ab892bb13.png)
This is just one example of what can be done with double rows.. This is for articles (to ensure the bug exists in core).

**Comment by brianteeman** [comment]
I'm not disputing that you have identified an issue I am just not convinced at all that it is something we should "fix". From your example its not just the checkbox select that breaks. The complete loss of table headers results in a broken table which fails accessibility.

Semantically a table row should contain a complete record. I am assuming that the motivation for your work is due to the limitation in the number of columns that can be easily displayed on a screen without scrolling laterally. This is considerably improved in 4.2 with the user selectable option to chose which columns to display.

**Comment by aschkenasy** [comment]
@brianteeman sounds good. thx.
