### ISSUE TITLE
[4.x] Installation params and default params do not match

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37386]
### Steps to reproduce the issue
Clean install
Export #__extensions where name like com_%

Open each component and save the options
Export #__extensions where name like com_%

Compare the results

### Expected result
The values in the params fiels are identical 

### Actual result
There are many differences.

#### Empty value in the sql but default value in the xml
Option that says "Use Global" will not be able to display what the global value is

#### Different value in the sql to the default value in the xml
User changes an unrelated setting in the component and gets unexpected changes. They may even be on a different tab to make it even harder to notice.

#### Missing option
Documented behaviour will not be correct until you have saved the options once. Making it even harder to track down a bug etc

### Additional comments

[clean.csv](https://github.com/joomla/joomla-cms/files/8357210/clean.csv)
[save.csv](https://github.com/joomla/joomla-cms/files/8357211/save.csv)

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/30027
