### ISSUE TITLE
[4.2] [UX] Reset hidden postinstallation messages

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#37399]
### Steps to reproduce the issue
Open postinstallation messages in backend. 
![grafik](https://user-images.githubusercontent.com/1035262/160603373-102fc9f8-587a-4860-b0f8-647a6dc1e935.png)

It is possible to hide single messages.
But it is impossible to reset messages again, as long as not all messages are hidden. 

### Expected result
If there are hidden messages, an additional button "reset messages" exists (can show the number of hidden messages) which activates hidden messages. 

### Actual result
If you want to reset messages, you have to hide all messages, then you can restore them all. This is not self-explaining

**Comment by brianteeman** [comment]
The reason to "hide" the messages was to remove the notification of unread messages.

Two suggestions
1. Change the hide button to more of a collapse so you only see the title and have a restore message
2. Change the hide button to a "mark as read" button. This would keep the messages displayed but remove the notification

**Comment by chmst** [comment]
The reason for this use-change:
I read a message, maybe change my htaccess as requested in the message, klick on "hide". 
Then get an error and want to repeat and control the changes I made - but the message disappeared.

A button which brings up all messages again, as we have now in the empty state view resolves the problem that hidden messages are no longer available. 

Of course there are many possibilities for further enhancement.
Iwould like  a combination of 1) and 2) in the comment above:  "Mark as read" collapses the message and removes the notification, but the message can be expanded. 
This would make the empty state screen superfluous.

**Comment by brianteeman** [comment]
> A button which brings up all messages again, as we have now in the empty state view resolves the problem that hidden messages are no longer available.

But the problem is that you now have to unhide all the messages (there may be a lot) just to read one

**Comment by chmst** [comment]
Indeed. And nobody knows thet this is the only way to get a message back.

**Comment by brianteeman** [comment]
How about this?

![message](https://user-images.githubusercontent.com/1296369/160904363-515ed8dc-88f4-4f84-9cf8-8705c5a41eb1.gif)

**Comment by brianteeman** [comment]
anyone?

**Comment by Quy** [comment]
> How about this?

Looks good! 👍

**Comment by chmst** [comment]
Yes, looks good!

**Comment by brianteeman** [comment]
Now I just have to remember how I did that 10 weeks later

**Comment by brianteeman** [comment]
please see #38064

**Comment by chmst** [comment]
Closing as we hava a PR
