### ISSUE TITLE
Cannot select user under Users > Private Messages

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#37427]
### Steps to reproduce the issue
1. Login to the admin as a super user.
2. Go to: Users > Messaging > Private Messages and create a new message
3. Under the recipient field, click the user button to the right to load the users modal.
4. Check the modal, is always empty.

### Expected result
The users modal

### Actual result
No users
![users_modal](https://user-images.githubusercontent.com/1838041/160849877-ac55af05-0507-421d-b5d6-f6403b5a583d.png)

### System information (as much as possible)
Joomla 4.1.0

### Additional comments
Tested in 2 different installations

**Comment by brianteeman** [comment]
The only users that you can send private messages to are those with admin access

**Comment by sakiss** [comment]
> The only users that you can send private messages to are those with admin access

So is this by design?

**Comment by brianteeman** [comment]
Yes. But I'm sure I did a pr recently that would remove the ability to send a pm if there is no one you can send it to
