### ISSUE TITLE
loadmodule or loadposition not working

### ISSUE THREAD

**Issue by devjoomla** [joomla/joomla-cms#37422]
### Steps to reproduce the issue

1. Add an article to article manager
2. Add code to load module from modules manager like we normally use in joomla 3.x series i.e. {loadposition positionname} or {loadmoduleid moduleid}

### Expected result
This should produce output as it is in module manager and show in article at frontend.

### Actual result

But it shows just tags we added in content in article

### System information (as much as possible)

Joomla 4.1
Php 8

### Additional comments

Created module in module manager, here is screenshot of it https://prnt.sc/9jJJMBiywlYZ
Added same module by using both tags in article, here is screenshot of it https://prnt.sc/_pXJqWL3fcuK
Load module in content plugin is published, here is screenshot of it https://prnt.sc/I9DGyvl-VcYr
Yet, the output is just showing tags instead content, here is screenshot of it https://prnt.sc/tGE8_vsjf1a5

**Comment by brianteeman** [comment]
The only way that I can replicate this behaviour is 
1. when I disable the plugin
2. when I set the plugin permissions to higher than the user viewing the article. ie the plugin is set to superuser so a guest user just sees the {loadmodul... 
3. when the template does not process the plugin event. Check by using cassiopeia.

**Comment by devjoomla** [comment]
Hi,

I also tried with cassiopeia template, and plugin access is already set to public, its the same result at all the times, here is screenshot of it https://prnt.sc/_GwrSY13M02h

Thank you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37422">issues.joomla.org/tracker/joomla-cms/37422</a>.</sub>

**Comment by brianteeman** [comment]
Sorry I have no idea then as I cannot replicate it in any other scenario

**Comment by brianteeman** [comment]
The only other thing I can think of was that there is a conflict with another content plugin.

**Comment by devjoomla** [comment]
Hi,

Found the issue :) it was due to TZ Portfolio System Plugin, just disabled it, and it found to be working, 

Thank you though.. :)

**Comment by brianteeman** [comment]
I trust you have reported the bug to them

**Comment by devjoomla** [comment]
Yes, I reported it to them, 

Actually, one other thing is found, that is, added phocamap and other map components, and tried to use their plugin codes to insert map into article, but it just showed plugin code only, not sure if it is an issue from joomla or from extensions, other plugins like jw_ts i.e. slides and tabs plugin generates output properly as needed, but map plugins do not generating any output and only shows plugin insertion code as its in article. I am about to contact concern developer and report them to.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37422">issues.joomla.org/tracker/joomla-cms/37422</a>.</sub>
