### ISSUE TITLE
[3.10] With php 8.1 Error when saving Configuration

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#37428]
### Steps to reproduce the issue
With php 8.1: 
In a 3.10.8 open configuration. Set error-reporting to maximum and debug-mouds on.
Save and close.

### Expected result
Configuration is saved

### Actual result
![image](https://user-images.githubusercontent.com/1035262/160887973-e1758760-0410-4e82-a9ae-174e49468c6a.png)

**Comment by brianteeman** [comment]
Is that the same issue fixed here https://github.com/joomla-framework/session/pull/56

**Comment by alikon** [comment]
that one is for j4 [joomla-framework:2.0-dev](https://github.com/joomla-framework/session)
on j3 [joomla-framework:1.x-dev](https://github.com/joomla-framework/session) 
need https://github.com/joomla-framework/session/pull/56 to be backported

**Comment by chmst** [comment]
Additional Information: In J4.1 debug mode is possible, fixed here: https://github.com/joomla-framework/session/releases/tag/2.0.1 but error-reporting maximum with php 8.1 is not.

**Comment by chmst** [comment]
Saving is now possible without warnings / errors, Closing.
