### ISSUE TITLE
update.joomla.org not up-to-date with 3.10.7 !

### ISSUE THREAD

**Issue by DiSToAGe** [joomla/joomla-cms#37426]
### Steps to reproduce the issue
You can download 3.10.7 update manually (from yesterday (?), but the update is not reported on automatic xml lists
https://update.joomla.org/core/list.xml
https://update.joomla.org/core/sts/list_sts.xml

**Comment by zero-24** [comment]
Yes its intended for now as the decision has been taken to take 3.10.7 & 4.1.1 off to be replaced with a new release to fix an issue with a patch included.

**Comment by brianteeman** [comment]
🤦 so people can still download the zip and use the manual update process. whoops

**Comment by DiSToAGe** [comment]
Yes, manually as me ... :smile:
So waiting to 3.10.8 ...? :wink:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37426">issues.joomla.org/tracker/joomla-cms/37426</a>.</sub>

**Comment by zero-24** [comment]
Update to 3.10.8 has been published on the update server. Will close here.
