### ISSUE TITLE
J4 Plugin Fields List Options and Plugin Params Options Not Merging

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#37429]
### Steps to reproduce the issue
Open the plugin Fields - List and add some options:
![Fields - List](https://user-images.githubusercontent.com/1373815/160946745-bb7f23de-c67c-40eb-99a2-ede4e95c43f0.png)

Then create a field of list type in an article for example:
![Articles Fields - List](https://user-images.githubusercontent.com/1373815/160946902-6b729bfb-fd79-429d-93a3-b52cf46fc91e.png)

Now go and create a new article, look at the Field Tab to see the field.
![Articles: New - Fields](https://user-images.githubusercontent.com/1373815/160947157-733b60ed-582e-4902-b3f8-97b67d052834.png)

According to the code in FieldsListPlugin.php at line#73:

`public function getOptionsFromField($field)
{
$data = array();

// Fetch the options from the plugin
$params = clone $this->params;
$params->merge($field->fieldparams);  

foreach ($params->get('options', array()) as $option)
{
	$op = (object) $option;
	$data[$op->value] = $op->name;
}

return $data;
}`

It should merge the parameters from the plugin settings and in the field, right? Unless, I am reading the code wrong, am I? 

### Expected result
The list options/params I set in the plugin settings: One and Two should be merged into the options I added in the Field edit.

### Actual result
The list field only pull options from the field edit.

**Comment by varaprasad16** [comment]
hello this is vara prasad can you tell me where the code relating to this issue is located.

**Comment by varaprasad16** [comment]
Hello, this is Vara Prasad I've gone through the error and related code, and I saw that the error is occurring due to the merge method that you've used in line 73(according to the new code).

**Comment by richard67** [comment]
To me it seems that this is desired behaviour. See the description of PR #13578 :

> After this PR you will only see the ones from the field. The plugin ones are only shown if none are defined in the field.

@Bakual Can you confirm this?

**Comment by Bakual** [comment]
This is expected. The field overwrites the plugin defaults.

**Comment by richard67** [comment]
Closing as expected behaviour due to reasons mentioned in previous comments.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37429">issues.joomla.org/tracker/joomla-cms/37429</a>.</sub>

**Comment by frogydiak** [comment]
I see, understand now but there should be a text/description in the plugin parameters that the default values defined will be overwritten if values are defined in the field parameters.

**Comment by Bakual** [comment]
I don't think it needs a text. The behavior is the same as in every other place. Default parameters get overwritten, not merged.
You just happend to have wrong expections in this case because you had your use case. If your use case would have been different, you wouldn't have expected this behavior at all.
