### ISSUE TITLE
[4.x] Remove WinCache?

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#37420]
I'm currently reviewing the setup for Appveyor and I stumbled over WinCache. WinCache seems to be the only caching solution for Windows IIS, but: This project seems to be completely and utterly dead. I had issues finding an official website and there are 3:
- https://www.iis.net/downloads/microsoft/wincache-extension
  This website says, that WinCache only supports PHP up to version 7.1
- https://windows.php.net/downloads/pecl/releases/wincache/2.0.0.8/
  This provides a package for up to version 7.2
- https://sourceforge.net/projects/wincache/
  Here we have packages for 7.3 and 7.4
- http://pecl.php.net/package/WinCache/2.0.0.8
  Last release seems to be from 2016...

All these sites haven't had any changes in the last 2-6 years and the support seems to be nearly 0 everywhere. We wont be able to test WinCache with our current setup with PHP greater than 7.2, since that is the latest package available in the second link. But even that package claims to only be supported on PHP 5.2 and not newer. For PHP8 there seems to not be an ice cubes chance in hell to see a release.

We don't have any tests for WinCache in Joomla 4, although admittedly we have tests in the cache package of the framework. At the same time, the performance gain by using WinCache in an old PHP version is most likely negligable compared to using PHP 7.4 or later with built in Opcache. Looking at our tracker, the WinCache code does seem to be the most perfect code ever to be added to Joomla, since we seem to have only exactly one PR to fix one notice in everything. (The rest mentions WinCache in other contexts.) Redis by comparison has ~80 issues and ~60 PRs. Long story short: I doubt that anyone has used it in Joomla 4 and most likely no one is using it in Joomla 3 either.

That is why I'd like to propose to drop WinCache with the next minor release. Yes, I know that that is against SemVer, but considering the absolute minimal chance that anyone is even using this, I think it would be reasonable to do this. We aren't testing the code, we don't know if it works, we can't really add proper tests anymore for it... If you really want to keep this dead code, I'd at least like to remove the dead code from the appveyor setup.

**Comment by HLeithner** [comment]
Already said in some other Issues/PR if SemVer doesn't fit the needs of Joomla! then please help finding a specification at https://github.com/joomla/rfc/pull/29

For wincache it self we can remove it with 5.0, Please deprecate it in the framework with 3.0 and for Joomla 5.0 (introducing the deprecation with the next minor). I see no hurry to remove it since it doesn't break code other code and we don't know if someone is using it or not.

**Comment by Hackwar** [comment]
Ok, will deprecate it and leave the code otherwise where it is. However, I'm going to remove the few bits we have in the testing infrastructure, which is setup on each build to run tests we simply don't have. I don't see anyone creating tests for this, so I don't think the additional several minutes of runtime to setup this each time is worth it.
