### ISSUE TITLE
Warning: Undefined array key "fr-FR" in plugins/system/languagefilter/languagefilter.php on line 455

### ISSUE THREAD

**Issue by roscofil** [joomla/joomla-cms#37434]
### Steps to reproduce the issue
Had a system running php 7.4. Upgraded to php 8.0

Error messages displayed are:

Strict Standards: date_default_timezone_get(): We selected 'Europe/Berlin' for 'CEST/2.0/DST' instead in xxx/libraries/src/Date/Date.php on line 117

Warning: Undefined array key "fr-FR" in xxx/plugins/system/languagefilter/languagefilter.php on line 455

Warning: Attempt to read property "sef" on null in xxx/plugins/system/languagefilter/languagefilter.php on line 455

### Expected result

Website to display :-)

### Actual result

Endless loop on error messages

### System information (as much as possible)

- Ionos hosted website
- SmartAddons template
- Worked perfect with php 7.4

### Additional comments

Feel free to ask for other details

**Comment by richard67** [comment]
> Feel free to ask for other details

@roscofil How about the most important information, the Joomla version?

**Comment by roscofil** [comment]
Reverted back to 4.1.1: same issues if I upgrade php to 8.0, except that the error messages just don't indefinitely loop.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37434">issues.joomla.org/tracker/joomla-cms/37434</a>.</sub>

**Comment by roscofil** [comment]
@richard67 : Version tested was 4.1.2 and just checked now with 4.1.1 with same effects.
Thx
Philippe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37434">issues.joomla.org/tracker/joomla-cms/37434</a>.</sub>

**Comment by infograf768** [comment]
Which precise php version?
My test here with php 8.0.8 are fine.

**Comment by richard67** [comment]
8.0.0 is indeed known as buggy.

**Comment by roscofil** [comment]
Can't check php version since Ionos access seems currently down...Selection was just displaying 8.0 or 8.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37434">issues.joomla.org/tracker/joomla-cms/37434</a>.</sub>

**Comment by richard67** [comment]
Ah, ok, IONOS PHP version selection. I have my private homepage there. Then they should use an newer 8.0.x version.

**Comment by roscofil** [comment]
Additional interesting informations:

1. Went back to php 7.4 and Joomla 4.1.1: website works fine
2. Stayed with php 7.4 and upgraded to Joomla 4.1.2: website loading fails with ERR_TOO_MANY_REDIRECTS<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37434">issues.joomla.org/tracker/joomla-cms/37434</a>.</sub>

**Comment by richard67** [comment]
@roscofil Do you have a local php.ini or .user.ini file in your Joomla root folder? If so, check if they contain entries like e.g. `extension_dir = "/usr/lib/php8.0/extensions";` or `browscap = /usr/lib/php8.0/browscap.ini;`, these need to be adjusted to the particular PHP version. For a test it would also be good to just rename that file (if present) so it's not used anymore.

Or do you have a special .htaccess file which contains any entries specific for the particular PHP version?

**Comment by roscofil** [comment]
@richard67 Yes I do have a php.ini file and no there's no extension_dir directive.
My .htaccess is basically the defaut std joomla htaccess.
Also removed php.ini: no change
W>ent back to 4.1.0 and php 7.4...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37434">issues.joomla.org/tracker/joomla-cms/37434</a>.</sub>

**Comment by roscofil** [comment]
A bit more investigations on this:

1. If I disable the Joomla system language plugin filter, the website comes up when using php 8 and 4.1.0 except that I get the default_timezone message as follows:
Strict Standards : date_default_timezone_get(): We selected 'Europe/Berlin' for 'CEST/2.0/DST' instead in xxxxxx/libraries/src/Date/Date.php
on line 117 which I can fix with php.ini by adding this:
[Date]
date.timezone = Europe/Paris

2. If I then upgrade to J! 4.1.2, the website gets back to life

Anybody? 
Sounds like there's something going on around the language plugin filter and php 8.x...

Cheers

Philippe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37434">issues.joomla.org/tracker/joomla-cms/37434</a>.</sub>

**Comment by roscofil** [comment]
Nope...I was wrong: if cache is cleared some parts of the website such as a top slider does not display...Back to the block!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37434">issues.joomla.org/tracker/joomla-cms/37434</a>.</sub>

**Comment by roscofil** [comment]
Le 27 févr. 2023 à 12:44, Hannes Papenberg ***@***.***> a écrit :﻿
I went through the code and the notice today would come from line 419 in our current codebase. I have a hunch that this is related to #6746. @roscofil do you still have this issue? Can you have a look at your #__language table and see if all rows have a none-0 value in the access column? From all code reading I could do, this would be the only situation where this could happen.

**Comment by roscofil** [comment]
Hello there,Honestly I don’t recall when I logged this one and, since I did’t see it showing up again, it’s probably gone in some spare records areas of my old brain. But I’ll check the #__language table and let you know if pb there. ThksPhilippeLe 27 févr. 2023 à 13:09, Philippe Lévi ***@***.***> a écrit :﻿Le 27 févr. 2023 à 12:44, Hannes Papenberg ***@***.***> a écrit :﻿
I went through the code and the notice today would come from line 419 in our current codebase. I have a hunch that this is related to #6746. @roscofil do you still have this issue? Can you have a look at your #__language table and see if all rows have a none-0 value in the access column? From all code reading I could do, this would be the only situation where this could happen.

**Comment by Quy** [comment]
Closing for now. If you can reproduce it, this can be reopened. Thanks.
