### ISSUE TITLE
Error on logout on Joomla 3.10.7 with PostgreSQL 13.3

### ISSUE THREAD

**Issue by motokraft** [joomla/joomla-cms#37432]
Выводит ошибку при выходе из аккаунта в Joomla 3.10.7 и PostgreSQL 13.3

(translated with Google Translator: Displays an error when logging out of an account in Joomla 3.10.7 and PostgreSQL 13.3)

`bin2hex(): Argument #1 ($string) must be of type string, resource given
JPATH_ROOT\libraries\joomla\database\driver\pgsql.php:1021`

**Comment by motokraft** [comment]
<html>
<body>


Call stack
--
# | Function | Location
1 | () | JROOT\libraries\joomla\database\driver\pgsql.php:1021
2 | bin2hex() | JROOT\libraries\joomla\database\driver\pgsql.php:1021
3 | JDatabaseDriverPgsql->quoteBinary() | JROOT\libraries\src\User\UserHelper.php:919
4 | Joomla\CMS\User\UserHelper::destroyUserSessions() | JROOT\plugins\user\joomla\joomla.php:359
5 | PlgUserJoomla->onUserLogout() | JROOT\libraries\joomla\event\event.php:70
6 | JEvent->update() | JROOT\libraries\joomla\event\dispatcher.php:160
7 | JEventDispatcher->trigger() | JROOT\libraries\src\Application\BaseApplication.php:108
8 | Joomla\CMS\Application\BaseApplication->triggerEvent() | JROOT\libraries\src\Application\CMSApplication.php:985
9 | Joomla\CMS\Application\CMSApplication->logout() | JROOT\administrator\components\com_login\controller.php:112
10 | LoginController->logout() | JROOT\libraries\src\MVC\Controller\BaseController.php:702
11 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\administrator\components\com_login\login.php:22
12 | require_once() | JROOT\libraries\src\Component\ComponentHelper.php:402
13 | Joomla\CMS\Component\ComponentHelper::executeComponent() | JROOT\libraries\src\Component\ComponentHelper.php:377
14 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:101
15 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:159
16 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:225
17 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\index.php:51


</body>
</html>

**Comment by richard67** [comment]
@motokraft Can you update to 3.10.8 which has been released yesterday? If so, does the error still happen after the update?

**Comment by richard67** [comment]
P.S. I allowed myself to translate the title into English and add also a translation to the description.

**Comment by motokraft** [comment]
Да, проблема осталась!

**Comment by richard67** [comment]
@motokraft Please use English here.

**Comment by alikon** [comment]
issue confirmed on 3.10.8 php 8.0.8 postgresql 11.7
please test  #37440

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37440 . Thanks in advance.

Пожалуйста, проверьте #37440.  Заранее спасибо.
