### ISSUE TITLE
Update jommla delete changes in template Cassiopeia

### ISSUE THREAD

**Issue by Emasmas** [joomla/joomla-cms#37431]
### Steps to reproduce the issue
The Cassiopeia template in Joomla 4 can be customized, change the css, add positions by editing the index.php, among many things. But when updating joomla, all the changes that are made are rewritten, leaving the template as the original. All changes are deleted.

**Comment by adithyareddych** [comment]
@Emasmas How should the template be looking like after adding CSS ? Can you please provide more specific details ?

**Comment by drmenzelit** [comment]
That is not the way to work with the template. Only the user.css file should be modified, it will not be overwritten by an update. If you need to make big modifications on Cassiopeia you should use the new feature and create a child template.

**Comment by richard67** [comment]
Closing as expected behavior.
