### ISSUE TITLE
Blank log-in admin page

### ISSUE THREAD

**Issue by ma-byrdmedia** [joomla/joomla-cms#37430]
Logging into back end of website produces a blank white screen. How can we fix this? 

Second question, are you able to provide FTP username and password for our website if we provide the details? (What details would you need?)

**Comment by drmenzelit** [comment]
Hi @ma-byrdmedia, github is not a support platform for Joomla. It would be better to post your problem, with detailed information, on the forum: forum.joomla.org
For the second question: You should ask your hosting provider for FTP access for your domain
