### ISSUE TITLE
We can't find a download URL

### ISSUE THREAD

**Issue by peterwouda** [joomla/joomla-cms#37433]
![update-url-2](https://user-images.githubusercontent.com/18345618/160998571-e341cbde-df08-41da-802e-0dc3da0b25c5.png)
![update-url-1](https://user-images.githubusercontent.com/18345618/160998584-98822062-a409-4c34-be8e-f5cfc09081bc.png)

Even since the beginning of my Joomla 4 website (no migration but Joomla 4 from the start) I have to manually update Joomla because no download URL was found. 
Clearing the cache, changing update source, nothing helps. 

Same issue as Brian Teeman #37045  but did not find the solution in this post.

**Comment by drmenzelit** [comment]
What do you mean with "manually update"? Have you clicked on the link at the bottom "Update your site by manually uploading the update package" and uploaded there the update package?

**Comment by peterwouda** [comment]
Yes, that is way I update Joomla: uploading the update package :

![afbeelding](https://user-images.githubusercontent.com/18345618/161014454-f616b504-0ba1-4671-9f44-79ac1a1a67ea.png)

**Comment by drmenzelit** [comment]
How did you installed Joomla? By yourself or using some installer from hoster? Which is your hoster? What do you see when you go to System -> Database?

**Comment by peterwouda** [comment]
I installed and developed the site first on localhost, then published it on a dedicated live server with 80 websites on it. Other websites update Joomla without problems. 
All database structures are up to date (Still Joomla version 4.1.0. Did not update to version 4.1.2 yet): 
![afbeelding](https://user-images.githubusercontent.com/18345618/161023296-6c5c1376-f1ac-4fbd-8344-24b8278063b8.png)

**Comment by ghost** [comment]
I would like to add that I too am experiencing this issue on all of my J4 sites. I too am forced to use the "Update your site by manually uploading the update package" method to update Joomla on my sites. Some of these sites started out life as J3 sites but some are brand new J4 installations and they both exhibit the same issue. The Joomla update shows as being available but when I go to update I can't the same message shown as the OP.

All update sites look good to me in joomla updater and I am on the "Joomla Next" update channel.

If someone could give more clues as to what else to look at I'd be extremely grateful.

Regards, Mark.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37433">issues.joomla.org/tracker/joomla-cms/37433</a>.</sub>

**Comment by zero-24** [comment]
Please post your database type and version. Mostlikly thats the reason when they do not match the minimum version published on the update server.

**Comment by brianteeman** [comment]
If that is the case shouldnt we be displaying a helpful message?

**Comment by zero-24** [comment]
It does within J3 not sure why its gone with J4

**Comment by ghost** [comment]
My database version (as shown in Joomla 4 > system information) is reported as 10.0.38-MariaDB.

To be honest I do now remember reading something about this as I had to download the update packge to J4 (from 3.10.x) too because of the same issue.

I hope that helps.

Regards, Mark.

**Comment by peterwouda** [comment]
My database version for this particular website is even (much) lower, 5.5.68-MariaDB. I will update it and see if the update URL is found.
A message with a hint to this solution would have been helpfull. 

Regards,
Peter

**Comment by ghost** [comment]
tbh I think it's the "-MariaDB" on the end of our version number that is the issue here - I hope Joomla can fix this as it is a perfectly  valid version number.

**Comment by zero-24** [comment]
> My database version (as shown in Joomla 4 > system information) is reported as 10.0.38-MariaDB.

> My database version for this particular website is even (much) lower, 5.5.68-MariaDB. I will update it and see if the update URL is found.

The minimum version is `<supported_databases mysql="5.6" mariadb="10.1" postgresql="11.0" />`

**Comment by zero-24** [comment]
> tbh I think it's the "-MariaDB" on the end of our version number that is the issue here - I hope Joomla can fix this as it is a perfectly valid version number.

Joomla knows how to handle mariadb version numbers the versions are just to low to be supported on J4 so at the point where the updater checks the requirements as definedn in the xml it fails to found a "download url" for this envoirments.

**Comment by ghost** [comment]
10.0.38-MariaDB is equivalent to Mysql 5.6 so  not sure why that's not acceptable?

Either way the message being given on the updater or "can't find download URL" sucks and needs improvement to state what the actual error is. 

I should also point out that everything else in J4 is working fine on 10.0.38-MariaDB 

Also, if it's not acceptable then how come Joomla 4 install worked (albeit manual update package had to be downloaded and installed in joomla updater)?

Regards, Mark.

**Comment by brianteeman** [comment]
> I should also point out that everything else in J4 is working fine on 10.0.38-MariaDB

that you are aware of

**Comment by zero-24** [comment]
> Either way the message being given on the updater or "can't find download URL" sucks and needs improvement to state what the actual error is.

I agree, looks like the details we had there in the past have been removed so some more details could be added there back in. Its also not limited to database versions but any limitation features that can be applied via the updater.xml files can have such a result.

> Also, if it's not acceptable then how come Joomla 4 install worked (albeit manual update package had to be downloaded and installed in joomla updater)?

As you noticed it is actually not possible to install it via the core updater where you get said error message right? Sure you can upload the package and sure we can make it even harder or just stop the execution of Joomla on none supported envoirments. Not sure whether that would be a better solution here.

> 10.0.38-MariaDB is equivalent to Mysql 5.6 so not sure why that's not acceptable?

I'm not deep into the differences between the version, there might be features within 10.1 that are not in 10.0.(?). But it has been decided that we only support it starting from 10.1 and therefor said check has been implemented that way.

**Comment by tbreeze29** [comment]
I'm experiencing the same problem. Same onscreen message about not finding download url<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37433">issues.joomla.org/tracker/joomla-cms/37433</a>.</sub>

**Comment by fancyFranci** [comment]
There is a Pull Request https://github.com/joomla/joomla-cms/pull/38799 which should solve this issue or at least give a better description of the real problem.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38799 . Thanks in advance.
