### ISSUE TITLE
[4.2] [Feature request] New components in the default admin menu

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#37449]
### Is your feature request related to a problem? Please describe.
In 4.1, the scheduler component was added, a little earlier - email templates. I would like to see these components not so much in the SYSTEM item, but in the main menu of the control panel, since their "importance" is not inferior to the importance of other components like BANNERS (not to mention the news feed). There is enough space in the COMPONENTS menu item.

Yes, I know that it is possible to change all this on your own. My request is about adding these components to a base installation like 4.2.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/161291977-bef43a62-c322-41b4-94ef-668038f880e8.png)

**Comment by brianteeman** [comment]
neither of those are user-facing components. they are system tools which will not be used on a regular basis

**Comment by alikon** [comment]
i've made a pr #37513 to add scheduler to System Quick Icons

**Comment by justbytecode** [comment]
Hlw Sir I am Mani. 
Can I contribute in this issue.

**Comment by brianteeman** [comment]
> neither of those are user-facing components. they are system tools which will not be used on a regular basis

This really should be closed for the reason above.

**Comment by brianteeman** [comment]
Closed for the reasons stated above
