### ISSUE TITLE
[4.1] search with images broken

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37448]
### Steps to reproduce the issue
Set up finder to include images when you do a search (follow the instructions in the original PR for this #35612 by @sakiss )

### Expected result
If present then images will be displayed in the results

### Actual result
The images can never be displayed because it is checking for a variable, $images, which is never set. 

This was broken by #37022 by @dgrammatiko

**Comment by sakiss** [comment]
You need to clear your indexes and re-index your content.
The images are being indexed like the other variables.

If this does not work, probably it's broken by another PR

**Comment by brianteeman** [comment]
> If this does not work, probably it's broken by another PR

That is exactly what I wrote!!

**Comment by sakiss** [comment]
Confirmed
I tried in the same site before and after the J update.

**Comment by dgrammatiko** [comment]
Test #37450
