### ISSUE TITLE
J4.1.2 raises error 404 when clicking on tag starting with a numeric character in the output of menutype "List All Tags"

### ISSUE THREAD

**Issue by loovanloon** [joomla/joomla-cms#37444]
### Steps to reproduce the issue
Create a tag named "TestParentTag", no parent
Create a tag named "alpha2020", parent: "TestParentTag"
Create a tag named "2020", parent: "TestParentTag"

Create a menu item of type "List All Tags", parent tag: "TestParentTag"
Go to frontend, to the new menu item created, in the tag list, click on "alpha2020" Output: as expected
Go to frontend, to the new menu item created, in the tag list, click on "2020" Output: 404 error page

### Expected result
List of articles with the tag 

### Actual result
Error 404 page

### System information (as much as possible)
See attached file

### Additional comments
Issue arose after updating from J4.1.0 to J4.1.2
[systeminfo-2022-04-01T11_09_48+02_00.txt](https://issues.joomla.org/uploads/1/d29b62b098985bd678ee4b5f8ebab47d.txt)

**Comment by chmst** [comment]
Confirmed.

**Comment by MayWorkman** [comment]
Also a problem starting with J3.10.8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37444">issues.joomla.org/tracker/joomla-cms/37444</a>.</sub>

**Comment by chmst** [comment]
Just got this again. When a tag starts with a number and userfriendly urls are on, the router calculates the $pk for getItem() by concatenation of tagId and the tag itsellf. 

In my case tagID = 9, Tag = "12 of 12", $pk = 912 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37444">issues.joomla.org/tracker/joomla-cms/37444</a>.</sub>

**Comment by loovanloon** [comment]
I wouild love to help, but I don’t understand where and how I can get and install this dev-version of Joomla.
Can you give me a hint?

 

Van: Hannes Papenberg ***@***.***> 
Verzonden: maandag 31 oktober 2022 22:36
Aan: joomla/joomla-cms ***@***.***>
CC: loovanloon ***@***.***>; Author ***@***.***>
Onderwerp: Re: [joomla/joomla-cms] J4.1.2 raises error 404 when clicking on tag starting with a numeric character in the output of menutype "List All Tags" (Issue #37444)

 

#39114 <https://github.com/joomla/joomla-cms/pull/39114>  should fix this. Please help testing that.

**Comment by alikon** [comment]
you can test  installing the prebuild package https://ci.joomla.org/artifacts/joomla/joomla-cms/4.3-dev/39114/downloads/59234/

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39114 . Thanks in advance.
