### ISSUE TITLE
Joomla 4 updates -  check list entry files

### ISSUE THREAD

**Issue by TonConsultant** [joomla/joomla-cms#37447]
### Steps to reproduce the issue

After each joomla 4 update, there are often many template overrides to check and validate.
https://ibb.co/SX1nptd

I would like to know if a simple button could enable us to check them all at once

**Comment by brianteeman** [comment]
Then you wouldnt have tested them would you?

**Comment by chmst** [comment]
If you do not want to see this notification button, you can deactivate the plugin "Quick Icon - Joomla! Overrides Update Notification". 
Then it is up to you to make sure that your overrides are working also when the original changes.

**Comment by TonConsultant** [comment]
I do not understand your replies. Of course I would have made tests before. I was asking for a simple button to validate the huge list of overrides. NB : I was advised to mention it. Forget it. if you do not want to take it into account !!!!!!!!!!!!

Si chaque fois que je remonte ce que je considère comme mauvais sur le plan UX,  (car j'ai 167 clics à faire) et qu'on me fait remarquer que mon commentaire n'est pas pertinent , je m'abstiendrai bien-sur de commenter la prochaine fois. En, tout cas pas top les gars Joomla. Je vais aller voir ailleurs.

**Comment by chmst** [comment]
Please write English. 167 clicks is very much. I can add a feature request label to your issue, but it would be better if you explain your process so we understand better what you need.

Or, as you write "En, tout cas pas top les gars Joomla. Je vais aller voir ailleurs" I can close it.

**Comment by joomdonation** [comment]
The request in this issue is not clear and after 7 months without further information provided, I'm closing this issue. If you still want to discuss about this issue, feel free to open it. But description exactly what is the problem you are having or how you want to change it so that we can understand your request and reply you further. Thanks !

**Comment by brianteeman** [comment]
The request is quite simple. On the list of template overrides to check the user is requesting the ability to "select all" and then mark "them all" as checked

**Comment by joomdonation** [comment]
Sorry, I don't have enough experience with template override and did not understand the request. I re-opened the issue. Thanks for the feedback.

**Comment by brianteeman** [comment]
I dont know if this was added after this issue was raised but its no longer a problem as you can use the check all checkbox and this can be closed.

![image](https://github.com/user-attachments/assets/8957fd3c-c8f6-4b38-8f2e-d329031141b9)

**Comment by Hackwar** [comment]
As was said, we have the check all now and thus have this solved. Closing.
