### ISSUE TITLE
Convert core modules to service provider

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#37455]
This is issue acts as central place for people helping to convert core modules to service providers. If you are helping to convert one, please leave a comment so others can see which modules are already in the process.

This initiative has it's root in the pr #37398 and a first example can be found in #37445.

**Comment by brianteeman** [comment]
Could you please explain what the benefits of this change are. And has it been approved by production? Obviously its a big change that will require a lot of work by a lot of people and wouldnt want to see that work go to waste

**Comment by Ruud68** [comment]
For me to start it is important that #37445 has been merged. That way I know that I can build starting with that PR as an example.

**Comment by Ruud68** [comment]
Any news on this?
