### ISSUE TITLE
[4.1 Сassiopeia] Icon tooltip placed far away

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#37467]
### Steps to reproduce the issue
For simplicity, install the demo data, then log in to the frontend as an administrator, try editing the main menu module (the icon next to the Typography), go down below and go to the module's main parameters tab - call the modal window to select the basic menu item and hover over the publication icon. Pay attention to how far the tooltip to the icon is placed. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/161428240-5f650af4-ec18-46df-970f-228e93ffccef.png)

**Comment by drmenzelit** [comment]
Confirmed

**Comment by chmst** [comment]
https://github.com/joomla/joomla-cms/issues/33047 related

**Comment by justbytecode** [comment]
Hlw Sir/Mam 
I am Mani and I am interested to solve this issue,
Can I solve this issue?

**Comment by drmenzelit** [comment]
@manipal254 you don't need to ask for permission. If you know how to solve the problem go for it!

**Comment by shazmasiddiqui** [comment]
I am facing difficulty in reproducing the issue. Can anybody help me with this?

**Comment by drmenzelit** [comment]
@shazmasiddiqui did you follow the steps described by @Kostelano ?

**Comment by shazmasiddiqui** [comment]
@drmenzelit yes I tried following those steps but I could not find any issue. Here is the screenshot for reference:
![tooltip_issue](https://user-images.githubusercontent.com/43249198/162782283-aeea6fbb-8b79-443e-a542-58070a49d921.png)
Please let me know where I am going wrong.

**Comment by drmenzelit** [comment]
I guess the screenshot shows the backend, the issue is in the frontend

**Comment by shazmasiddiqui** [comment]
I got it. Thank you for your help.

**Comment by chmst** [comment]
Closing as there is a Pull Request. Please test https://github.com/joomla/joomla-cms/pull/37695
