### ISSUE TITLE
[4.1 Сassiopeia] One-time emergency passwords in one line

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#37468]
### Steps to reproduce the issue
Enable two-factor authentication for the super admin and login to the site in the frontend. On the right menu, select Edit Profile.

Please note that one-time emergency passwords are placed in one line, unlike, for example, the same situation in the Atum template. 

![Screenshot_1](https://user-images.githubusercontent.com/8440661/161429421-2f350007-1a8a-4936-99b9-6c472f19a3ac.png)

![Screenshot_2](https://user-images.githubusercontent.com/8440661/161429422-e82863cc-84cd-4712-9640-653319347813.png)

**Comment by drmenzelit** [comment]
I don't see a problem here...

**Comment by chmst** [comment]
Maybe one layout used in both, backend and frontend edit.php could be considered.

**Comment by brianteeman** [comment]
The atum way is much better. Much easier to read and also to mark which ones have been used on the printout

**Comment by brianteeman** [comment]
please test #37476

**Comment by drmenzelit** [comment]
Closing as we have a PR #37476
