### ISSUE TITLE
[4.1] Missing tags in two layouts for the email template component

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#37469]
### Steps to reproduce the issue
I noticed that two of the email layouts were missing some tags in the "Insert Tags" column.

**User Actions Log: Notification Mail**
- {USERNAME}

**Contacts: Contact Form Mail Copy**
- {CONTACTNAME}

![Screenshot_1](https://user-images.githubusercontent.com/8440661/161437619-f06b74b2-2c35-412e-8f38-44bf1f348f78.png)

In other layouts - everything is ok.

**Comment by brianteeman** [comment]
Preparing a PR for this - thanks for finding it

**Comment by brianteeman** [comment]
Please test #37504

**Comment by chmst** [comment]
Closing as there is a PR https://github.com/joomla/joomla-cms/pull/37504
