### ISSUE TITLE
[4.1][Mail Templates?] Email headers missing Reply To and Reply To Name

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#37473]
### Steps to reproduce the issue
Go to Global Configuration - Server - Mail.
Enter an email address into 'Reply To' and a name into 'Reply To Name'.
Click 'Send Test Mail'.

### Expected result
The received email should have the reply-to header with the name and the email address in the format 
Reply-To: Firstname Surname <mailbox@example.com>.

### Actual result
The Reply-To header is missing from the received email, as shown in the first screenshot.

### System information (as much as possible)
Joomla 4.1.3-dev on Wampserver 3.2.7 using PHP 7.4.26.
Using smtp.gmail.com as SMTP server.

### Additional comments
In Joomla 3.10.8 in the same system the received message includes the Reply-To header, as shown in the second screenshot.
This issue was reported at the Joomla support forum (https://forum.joomla.org/viewtopic.php?f=811&t=992972 "Joomla 4 'Reply To' / 'Reply To Name' Issue")

**Comment by toivo** [comment]
Screenshots from received email in Joomla 4.1.3-dev and Joomla 3.10.8:

![screen shot 2022-04-04 at 05 07 09](https://issues.joomla.org/uploads/1/2a4eec31f2df01383329a958c091b50c.jpg)![screen shot 2022-04-04 at 05 07 09](https://issues.joomla.org/uploads/1/1785d7bb05a121c2d4f2868a4c0279d9.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37473">issues.joomla.org/tracker/joomla-cms/37473</a>.</sub>

**Comment by toivo** [comment]
The original report in the Joomla forum mentions "when "Reply to Email" / "Reply to Name" are set, they are not coded by Joomla 4 in the test message or any of Joomla 4 email templates."

I verified this by testing the Account Details message for a new user in Joomla 4.1.3-dev and Joomla 3.10.8. 

Just a guess but maybe the issue originates from the processing of the email templates, introduced in Joomla 4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37473">issues.joomla.org/tracker/joomla-cms/37473</a>.</sub>

**Comment by Fedik** [comment]
Yeah, there a diference, J3 use `$mail->sendMail()`, wich care about ReplyTo:
https://github.com/joomla/joomla-cms/blob/8be66ebad93992c9a10219059322683ba74b731a/libraries/src/Mail/Mail.php#L737-L763

However in J4 we use MailTemplate that use own `send()` method, where global ReplyTo is ignored:
https://github.com/joomla/joomla-cms/blob/ac61e60df9e36e800249ae1be311042a58062255/libraries/src/Mail/MailTemplate.php#L292-L295

**Comment by toivo** [comment]
@Fedik thank you for the explanation.  Shouldn't Mail Templates behave the same way as mail in Joomla 3 and use the global settings Reply To and Reply To Name? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37473">issues.joomla.org/tracker/joomla-cms/37473</a>.</sub>

**Comment by Fedik** [comment]
I also think it should use global setings when "local" not exists for ReplyTo.

**Comment by cathelin45** [comment]
Hi,
Is there a way to know when that bug will be corrected? It is still the same problem with Joomla version 4.2.8
Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37473">issues.joomla.org/tracker/joomla-cms/37473</a>.</sub>

**Comment by toivo** [comment]
@cathelin45 no indication until one of the developers creates a Pull Request (PR). Two successful tests are required before the fix is included in the next version.

A related issue was reported today with the current version of VirtueMart, 4.0.12.10777.  VirtueMart sets the Reply-To header by calling the function addReplyTo() in libraries/src/Mail/Mail.php, which then passes the details to the addReplyTo() function in the PHPMailer library, but PHPMailer rejects the email address:
***0 - Invalid address: (Reply-To)***  

I will try to test this last use case with VirtueMart, narrow it down and get more details.   The forum topic is [
Issue with Reply-To address in PHPMailer with VirtueMart](https://forum.joomla.org/viewtopic.php?f=814&t=999875)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37473">issues.joomla.org/tracker/joomla-cms/37473</a>.</sub>

**Comment by toivo** [comment]
It turns out that the Reply-To email address forwarded by VirtueMart's Recommend to Friend form via Joomla addReplyTo() to addReplyTo() in PHPMailer must have been blank, which explains the error message. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37473">issues.joomla.org/tracker/joomla-cms/37473</a>.</sub>

**Comment by toivo** [comment]
@Fedik @cathelin45,
Just tested a patch in Joomla 4.2.8-dev (shouldn be called 4.2.9-dev?) of 19 February. It worked with the Sent Test Mail and the Forgot Your Password email.

libraries/src/Mail/MailTemplate.php lines 279-281:

```
        if ($this->replyto) {
            $this->mailer->addReplyTo($this->replyto->mail, $this->replyto->name);
        }
```
change to:
```		
	if ($this->replyto) {
            $this->mailer->addReplyTo($this->replyto->mail, $this->replyto->name);
        } elseif ($app->get('replyto')) {
            $this->mailer->addReplyTo($app->get('replyto'), $app->get('replytoname'));		
	}
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37473">issues.joomla.org/tracker/joomla-cms/37473</a>.</sub>

**Comment by Fedik** [comment]
@toivo that should work I think

**Comment by toivo** [comment]
@Fedik would you like to create a PR from that? I do not have the tools or skills to do that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37473">issues.joomla.org/tracker/joomla-cms/37473</a>.</sub>

**Comment by Fedik** [comment]
I will try over the week, if no one will be faster

**Comment by toivo** [comment]
@Fedik thank you!

**Comment by cathelin45** [comment]
Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37473">issues.joomla.org/tracker/joomla-cms/37473</a>.</sub>

**Comment by cathelin45** [comment]
Hi Toivo,
Many thanks for that. "Reply to" is now correctly coded with you patch; it now works alright.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37473">issues.joomla.org/tracker/joomla-cms/37473</a>.</sub>

**Comment by Fedik** [comment]
Please test #39893
