### ISSUE TITLE
[4.1] Restore post-installation messages

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#37480]
### Steps to reproduce the issue

1. hide all messages
2. click button `Reset Messages`

![image](https://user-images.githubusercontent.com/66922325/161544321-ce1e5b25-9895-4963-8123-76d62809e702.png)

### Expected result

Possible to restore post-installation messages

### Actual result

Not possible to restore post-installation messages

### System information (as much as possible)

Joomla: 4.1.2

**Comment by richard67** [comment]
Closing as having a pull request.

@heelc29 Could you next time when you make a pull request for an issue created also by you close the issue. Thanks in advance. In addition, when you already know you will make a pull request, it does not need to create an issue, the pull request is sufficient then.

**Comment by heelc29** [comment]
@richard67 Thanks for the hint. I'll keep that in mind for next time.
