### ISSUE TITLE
[3.10.8] Modules: Articles - Categories - Layout invalid

### ISSUE THREAD

**Issue by beejay41** [joomla/joomla-cms#37491]
### Steps to reproduce the issue
Add a module layout override to your template. Create or change an article categories module and select your layout override from the layout dropdown on the advanced tab. Click save.

### Expected result
The module should be saved.

### Actual result
The error "Warning: invalid layout" is displayed and the module is not saved.

### System information (as much as possible)
![screen shot 2022-04-05 at 09 13 43](https://issues.joomla.org/uploads/1/7c25a7bec1d13f7ed7433c0aa9ce097b.png)

### Additional comments
If the layout is changed in the database, it operates as expected in the frontend.
This behaviour has been introduced since 3.9+, I believe. It certainly worked as expected in the past.

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
