### ISSUE TITLE
[4.1] Smart Search: Options: Default Language

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#37494]
### Steps to reproduce the issue
Go to Smart Search: Options, Index tab, just below the Default Language option.

I can't figure out the meaning of NONE. If this is a mistake, please fix it. If not, could you explain how to understand this. Especially in the context of the description:

`Set the language to be used for non-multilingual sites or content marked as "All".`

![Screenshot_1](https://user-images.githubusercontent.com/8440661/161790373-d551b6f1-c99f-49c9-991e-b08f4691ac2f.png)

**Comment by norhan-mahmoud** [comment]
I think that,
"None" means that the characters for the search are not filtered
That is, it is possible to search within the database in more than one language at the same time
"default site language" means that it will filter for the characters of the database search and will allow characters for the language already selected for the site
"language name" means that it will filter for the characters of the search in the database and will allow the characters of the language mentioned
