### ISSUE TITLE
Joomla Cassiopeia: link color issue on click to close Submenu

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#37490]
### Steps to reproduce the issue

Creating new submenus. When the submenu is closed, you will see that there is a link color problem.

### Actual result

**Please click the picture for the video.**
[![Watch the video](https://www.grafiksite.com/1.jpg)](https://www.grafiksite.com/j4.1.2.mp4)

### System information (as much as possible)

New installation
Joomla 4.1.2
PHP: 8.0.17

**Comment by brianteeman** [comment]
sorry I dont see what the problem is that you are trying to show in the video

**Comment by ghost** [comment]
> üzgünüm videoda göstermeye çalıştığın sorunun ne olduğunu anlamadım

Hi @brianteeman ,

Please look at the link colors when closing the submenu. It turns blue.

**Comment by brianteeman** [comment]
i see the circle on your mouse pointer change but not the link.

![zoom](https://user-images.githubusercontent.com/1296369/161750482-13baade9-f8b4-4c5a-9565-5f6743372a99.gif)

**Comment by ghost** [comment]
Add different color to CSS file, not default link colors.  I added slow motion so you can see better now.

https://www.grafiksite.com/j4.mp4

**Comment by ghost** [comment]
For example, I want to use a color as follows. The result is like the video I added in my previous message.

`.metismenu.mod-menu .mm-collapse>li>a {
    color: var(--template-bg-dark-80);
}`
`.metismenu.mod-menu .mm-collapse>li>a:hover {
    color: var(--danger-border) !important;
}`

**Comment by chmst** [comment]
I understand that you want to change the appearance of your links in metismenu. 
You can make a child template of cassiopeia and write your changes into a user.css. 

This is not an issue of the joomla core or of cassiopiea. You better ask in forum.jooma.com

**Comment by ghost** [comment]
I know how to do it (I'm using user.css). But there is an error in the template dropdown here, check anyway. I didn't say anything about the Joomla core. And I've never seen this kind of problem with any template. It's not nice to have minor bugs in the core template.
Thank you.

**Comment by chmst** [comment]
@drmenzelit could you please have a look here? It it is a bug in cassiopeia we can re-open the issue.

**Comment by drmenzelit** [comment]
Hi @joomlaphp , I see what you mean, it has something to do with the javascript controlling the dropdown. Sadly I'm not good at javascript, so I don't know how to solve it...

**Comment by brianteeman** [comment]
I could try and help but I just dont see the bug. maybe i am looking in the wrong place?

**Comment by drmenzelit** [comment]
When the menu items have another colour than the standard Cassiopeia blue (Ugur has some grey) and you close the dropdown for a tiny moment you see the links dissapering and they are blue... in the slow motion video is better to see... We had already reports about the background of the submenu dissapering faster than the links itself, but I can't find them now...

**Comment by brianteeman** [comment]
ok I see it now

**Comment by ghost** [comment]
Yes, it seems to be related to javascript. I'm looking through the files, I hope we can find and fix it. 
@brianteeman @drmenzelit @chmst Thank you again for your interest.

**Comment by brianteeman** [comment]
The _problem_ is reproducable on the metismenujs demo site https://onokumus.com/metismenujs/

The _problem_ is that for a small period of time there is no metismenu mm-collapse class on the link

So its not something that can be fixed here and would need to be addressed upstream at https://github.com/onokumus/metismenujs

You could try adding 
`.metismenu.mod-menu a { color: var(--template-bg-dark-80); }
`

Or if you want to dig into the javascript then it will be the hide or the hidden events
| | |
|--|--|
| hide.metisMenu | This event is fired immediately when the hide method has been called. |
| hidden.metisMenu | This event is fired when a collapse ul element has been hidden from the user (will wait for CSS transitions to complete). |

**Comment by ghost** [comment]
> `.metismenu.mod-menu a { color: var(--template-bg-dark-80); } `

Of course this solves the problem. I'm sure this little problem will be fixed in time. Thanks again to all of you.

**Comment by abinash185** [comment]
I am working on it.

**Comment by chmst** [comment]
Thank you @abinash185 I assigned this to you.

**Comment by ghost** [comment]
@abinash185 Any progress?

Thanks

**Comment by ghost** [comment]
@abinash185 ?

**Comment by chmst** [comment]
unassigned @abinash185. Annoying ^^

**Comment by joomlaphp** [comment]
@onokumus , could you take a look at this thread, thanks.

**Comment by ghost** [comment]
I asked the question to the producer of Metismenu and the answer was:

> Hello,
> 
> First of all, I should point out that MetisMenu only comes with the CSS code it needs. The rest of the customizations belong to the user.
> 
> For example, padding, margin, text color, background color, underline etc. features are left to the user. In other words, MetisMenu only offers basic features, does not interfere with the rest.
> 
> As I understand from the video, your requests are not related to these basic features, but for customization. I also don't know how much Joomla customizes MetisMenu and offers it to its users.
> 
> For the reasons I listed above, the recommendations I can give you are:
> 
> Examine how the CSS features offered by Joomla affect MetisMenu,
> 
> If necessary, find out how to customize it according to this review.

**Comment by brianteeman** [comment]
As stated above I replicated the issue you reported on the metismenu example site
