### ISSUE TITLE
[4.1] Mismatch in column and sort table

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#37499]
### Steps to reproduce the issue
Go to System - Languages (Manage). There is an error in the language tag column and sort table.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/162048622-19fe9638-afaf-4670-a794-41fb09079aa6.png)

![Screenshot_2](https://user-images.githubusercontent.com/8440661/162048647-fc3dd9a9-a397-463f-8f91-b339c8e2a3ff.png)

**Comment by chmst** [comment]
Ordering by language Tag, not by language. Thanks for checking ;)

**Comment by Kostelano** [comment]
The problem is related to the fact that the sorting elements are tied to multilingualism, although in my example multilingualism is not enabled.

https://github.com/joomla/joomla-cms/blob/126ed6a1d4d4661d839096ca10bb2102486ae0dd/administrator/components/com_languages/forms/filter_installed.xml#L39-L40

**Comment by brianteeman** [comment]
There are two different errors here

1. requires="multilanguage" should not be there - that fixes the language tag issue
2. The first column is headed Title but the filter for that column is called Language (this same issue is present in the  Languages: Content page)

==
1. Easy fix
2. Should the column be changed to Language to match the filter name OR should the filter be change to Title to match the column name

**Comment by brianteeman** [comment]
Did a PR for the first part

**Comment by RitikaGarg-tech** [comment]
Can I work on this issue?

**Comment by Manaswini123456** [comment]
Can I work on this issue. If yes can somebody guide me on the above?

**Comment by drmenzelit** [comment]
@RitikaGarg-tech @Manaswini123456 every one can work on issues, you don't need to ask for permission.
Please check the information we give the GSoC students in the glip channel.

**Comment by Kostelano** [comment]
PR https://github.com/joomla/joomla-cms/pull/37527 for the header column.
