### ISSUE TITLE
How to remove ?tag_list_language_filter= 

### ISSUE THREAD

**Issue by DeniGj** [joomla/joomla-cms#37492]
After Joomla 4 upgrade all the menu items which are tagged items, in frontend got a **?tag_list_language_filter=** parameter added to the url. How can I get red of that parameter in the url?

for example:
**/blog/news** is now **/blog/news/?tag_list_language_filter=en-GB** and I want it back to **/blog/news**

**Comment by brianteeman** [comment]
Does this also happen on newly created menu items?

**Comment by DeniGj** [comment]
I just tried and no, the parameter is not there on the newly created menu item<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37492">issues.joomla.org/tracker/joomla-cms/37492</a>.</sub>

**Comment by brianteeman** [comment]
and if you open and save one of the existing menu items does it go away?

**Comment by DeniGj** [comment]
no it doesn't go away <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37492">issues.joomla.org/tracker/joomla-cms/37492</a>.</sub>

**Comment by DeniGj** [comment]
found a way, changing the menu type and returning it back works, thank you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37492">issues.joomla.org/tracker/joomla-cms/37492</a>.</sub>

**Comment by DeniGj** [comment]
or actually it doesn't :(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37492">issues.joomla.org/tracker/joomla-cms/37492</a>.</sub>

**Comment by DeniGj** [comment]
now when I set the language filter in options for Tags->Item Selection to be the current language, and then I dont have to change anything in the menu item for language filter, it works, as soon as I change the language filter in the menu item it addes the parameter automatically.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37492">issues.joomla.org/tracker/joomla-cms/37492</a>.</sub>

**Comment by Hackwar** [comment]
#39114 should fix this. Please help testing that.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39114 . Thanks in advance.
