### ISSUE TITLE
[4.1]Structured data from modul breadcrumbs

### ISSUE THREAD

**Issue by nadjak77** [joomla/joomla-cms#37508]
### Steps to reproduce the issue
modul breadcrumbs
works fine if the article has a menu point
but if the article is in a blog, the id for the last item is missing.

### Expected result
id in last element is for all articles set, not only if there is a menu point for this article.

### Actual result
structure data is not valid for articles without a menu point (f.e. blogs, or featured articles)

### System information (as much as possible)
Joomla 4.1

**Comment by chmst** [comment]
Related for J3 
https://github.com/joomla/joomla-cms/issues/27151

**Comment by drmenzelit** [comment]
Confirmed
That is how the json structured data look like when you are on an article in a blog layout
`<script type="application/ld+json" nonce="Yzk4MzI3ZmVmOWFmMzFhODc2ZTc1NTYzMzExNzFiOGRkOWRmODdiNmE2YWJkNGYxMTY2ZjhjMmZjMDI5ZTU3NTkzNjFlODUyODkwZWM5OWQ5ZmFiMTc0ZTY3Y2ZjMzM5ZjkwZGY0ZGFiMzYxZDZmYTlkMTIyMTYwNjk2N2I4NDY=">{"@context":"https:\/\/schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"@id":"http:\/\/localhost\/test4\/en\/","name":"Home"}},{"@type":"ListItem","position":2,"item":{"@id":"http:\/\/localhost\/test4\/en\/denkmalobjekte","name":"Denkmalobjekte"}},{"@type":"ListItem","position":3,"item":{"@id":{},"name":"Klosterkirche mit Resten der Klostermauer"}}]}</script>`

The last element has an empty `@id` (the link is missing)

The test for structured data report an error

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37679 . Thanks in advance.
