### ISSUE TITLE
How can I fix the problem

### ISSUE THREAD

**Issue by kodes1** [joomla/joomla-cms#37514]
### What needs to be fixed

Warning: Use of undefined constant PHP_SELF - assumed 'PHP_SELF' (this will throw an Error in a future version of PHP) in /index.php on line 9

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /libraries/joomla/session/session.php on line 96

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /libraries/joomla/session/session.php on line 99

Warning: session_set_save_handler(): Cannot change save handler when headers already sent in /libraries/joomla/session/storage.php on line 95

Warning: session_name(): Cannot change session name when headers already sent in /libraries/joomla/session/session.php on line 719

Warning: ini_set(): Headers already sent. You cannot change the session module's ini settings at this time in /libraries/joomla/session/session.php on line 742

Warning: session_set_cookie_params(): Cannot change session cookie parameters when headers already sent in /libraries/joomla/session/session.php on line 642

Warning: session_cache_limiter(): Cannot change cache limiter when headers already sent in /libraries/joomla/session/session.php on line 461

Warning: session_start(): Cannot start session when headers already sent in /libraries/joomla/session/session.php on line 462

Warning: Parameter 1 to JError::customErrorPage() expected to be a reference, value given in /libraries/joomla/error/error.php on line 698
Infinite loop detected in JError

---------
Please help 
`&#x2764;`

**Comment by toivo** [comment]
Please go to the Joomla! forum at https://forum.joomla.org, register an account and create a topic in the right sub forum, depending on the version of Joomla, and give more information about your website by posting the results from the Forum Post Assistant (FPA) by following the instructions at https://forumpostassistant.github.io/docs/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37514">issues.joomla.org/tracker/joomla-cms/37514</a>.</sub>

**Comment by drmenzelit** [comment]
Feel free to open this again, if it is really a Joomla issue and you not get answers in the forum.
I guess you are a GSoC student, in this case please post your questions in the students channel in glip.

**Comment by kodes1** [comment]
Thank You
