### ISSUE TITLE
[4.x] Extension installer loader animation

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37516]
### Steps to reproduce the issue
go to the extension installer.
inspect source and remove the `class="hidden"` from the div with `id="loading"`

### Expected result
The joomla logo animated gif is displayed in the middle of the screen

### Actual result
The gif is not displayed because of an error in the js which puts the loading div below the installer-install div instead of on top of it.

For the style top to be created this should be appended with + 'px'

https://github.com/joomla/joomla-cms/blob/939488f506a5a6954dc0fe9f533fb1c2c61fc12c/build/media_source/com_installer/js/installer.es6.js#L14

But that offset makes no sense and as far as I can tell it should simply be top: 0

What is needed is an offsetleft which takes into account the width of the sidebar and then the loader will be displayed in the middle of the main div whether the sidebar is expanded or not.

Sadly my js knowledge is not good enough for that

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37538 . Thanks in advance.
