### ISSUE TITLE
[4.1] Remove the misleading word 'manually' from Joomla Update page

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#37512]
### Steps to reproduce the issue
Go to System - Update and click Joomla.
The Joomla Update page is opened at administrator/index.php?option=com_joomlaupdate

### Expected result
The link at the bottom of the page mentions the option to upload and update without causing confusion with other methods like FTP transfers.

### Actual result
The link at the bottom of the page includes the word 'manually':
**The Update your site by manually uploading the update package.**

The word 'manually' confuses both new and old Joomla users because the words 'manual' and 'manually' are associated with FTP and transferring the update package or update folders and files directly to the website, overwriting existing files, which operation has very often broken Joomla websites.

### Additional comments
The following Joomla forum topic **Joomla 4 misleading wording "manual update" causes problems** at https://forum.joomla.org/viewtopic.php?f=812&t=992921 is good example of the confusion that causes problems and more work for the volunteers assisting the members of the Joomla forum.

**Comment by toivo** [comment]
![screen shot 2022-04-08 at 05 29 29](https://issues.joomla.org/uploads/1/ec1edc6201ed7a362bc0db93c402f6da.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37512">issues.joomla.org/tracker/joomla-cms/37512</a>.</sub>

**Comment by brianteeman** [comment]
I am aware of the alledged confusion on the forum. The users have not been confused and have been following the link it has been the people answering the questions that assumed the user was using ftp etc. Although the text could be better I dont believe that is the real problem.

1. people didn't realise it was a link and assumed it was an instruction. this has been partially improved by the forced addition of the underline. It could still be improved futher.
2. servers that do not meet the minimum server requirements do not show the availability of an update AND dont give any indication that this is the case.

**Comment by toivo** [comment]
@brianteeman, it is not just an alleged confusion but it also causes real communication issues when our volunteers give assistance to forum members who have had problems with the Joomla! Update.  

In addition to removing the misleading word 'manually', it would certainly be good to add a brief instruction, emphasizing  the importance of using only the Joomla! Update.  The best place for a couple of lines would be under the link 'Update your site by uploading the update package' and move that link upwards a couple of lines.  That page has plenty of space.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37512">issues.joomla.org/tracker/joomla-cms/37512</a>.</sub>

**Comment by brianteeman** [comment]
I agree there is confusion. I just don't believe removing the word manually will solve it. There needs to be a better way.

Perhaps
![image](https://user-images.githubusercontent.com/1296369/162397247-4bb040ad-1881-4eda-894d-001d59595e88.png)

**Comment by toivo** [comment]
@brianteeman, thank you for such this streamlined solution, which is certain to remove ambiguity and possible misunderstandings from the update process!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37512">issues.joomla.org/tracker/joomla-cms/37512</a>.</sub>

**Comment by brianteeman** [comment]
I will wait for more feedback before creating the pull request

**Comment by Webdongle** [comment]
When a user says they have 'manually updated' Joomla they need to be asked for their definition.  If they are not asked for their definition then it is unknown if:
A. They have used ftp to upload the update files
or
B. Used the Upload and Update method.

**Comment by gwstyles** [comment]
I agree that changing the wording should make it easier for newbies and will stop allot of the forum posts regarding this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37512">issues.joomla.org/tracker/joomla-cms/37512</a>.</sub>

**Comment by brianteeman** [comment]
With almost all of the forum posts that I have seen the confusion is not from the user. They have done the manual upload correctly. The confusion has come from those people answering who assumed that they have done something completely different. Anyway I will do the pull request shortly as a button is much more appropriate than a link with a very long text in it.

**Comment by gwstyles** [comment]
Thanks Brian.

**Comment by brianteeman** [comment]
please test #37519 

without tests it wont get merged

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37519 . Thanks in advance.
