### ISSUE TITLE
Problems Logging in to my account. I can get into the control panned but only because I have the page bookmarked.

### ISSUE THREAD

**Issue by JPratt314** [joomla/joomla-cms#37511]

**Comment by toivo** [comment]
Presumably you have problems in accessing your Joomla website. If that is the case, please create a topic at the Joomla forum 
 https://forum.joomla.org but provide more information, for example the version of Joomla and PHP, the URL and the FPA results.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37511">issues.joomla.org/tracker/joomla-cms/37511</a>.</sub>

**Comment by drmenzelit** [comment]
Please do what @toivo suggested and if you are a GSoC student, please post your questions in the student channel in glip.
