### ISSUE TITLE
[4.1] menu item link calss doesn't accept @

### ISSUE THREAD

**Issue by aschkenasy** [joomla/joomla-cms#37529]
### Steps to reproduce the issue
try to add `uk-visible@m` as link class to any menu item

### Expected result
`uk-visible@m` should be stored

### Actual result
class name value throws error Invalid field: Link Class

### System information (as much as possible)
j4.1.2

### Additional comments

**Comment by brianteeman** [comment]
> class name value throws error Invalid field: Link Class

That is because it is an invalid class

https://www.w3.org/TR/CSS21/syndata.html#characters

**Comment by chmst** [comment]
This is intended behaviour. Closing.
