### ISSUE TITLE
[4.x] Error page displayed on logging out without saving changes to edited article

### ISSUE THREAD

**Issue by alisha-kamat** [joomla/joomla-cms#37539]
### Steps to reproduce the issue
1. Login on the frontend
2. Open any article from the list
3. Click on edit article and make a few changes to it. 
4. Now try to logout without saving changes to these edits.

### Expected result
A popup / message reminding the user to either save changes or else continue to logout after discarding these changes.

### Actual result
An error page is displayed 

![image](https://user-images.githubusercontent.com/84401192/162900447-a5ec772b-4ebe-4bcf-9c63-8dc20d7a3bc4.png)

### System information (as much as possible)
Joomla 4.0.7
PHP 7.4.22

**Comment by xboxreviewer** [comment]
I have the same problem, <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37539">issues.joomla.org/tracker/joomla-cms/37539</a>.</sub>

**Comment by joomdonation** [comment]
I'm afraid of this is a won't fix issue. The logout (button or menu item) is not aware of the page you are viewing (or what you are doing), so I don't think we can display the warning message as you suggested.

From what I see, we could not do anything to improve this, so I'm closing. Feel free to re-open if you do not agree and I will ask for feedback from our maintainers.
