### ISSUE TITLE
Italian translation issue on Joomla 4.1.2 installation process

### ISSUE THREAD

**Issue by PixedBo** [joomla/joomla-cms#37532]
### Steps to reproduce the issue

Install Joomla 4.1.2 and select "italian".
Go forward to the database section.

### Expected result

The username field should ask for username

### Actual result

It seems that a tip is showing, see screenshot

![dbuser](https://user-images.githubusercontent.com/12549961/162742121-e0f75fe1-b2de-4ba0-b066-279c1a5f7c8d.png)

It says something like: 

> Could be a user name you have created or a user name provided by your hosting provider. *

### System information (as much as possible)

PHP 8.0.17 on Apache
Database MySQL 5.7.36-log 

### Additional comments

Another issue (but maybe it's not an issue) i've found is that i'm not using localhost so the hostname is some thing like xxx.myhost.com and when i clicked on "install" nothing happened, i clicked few times and nothing still happens. Only in the end i scrolled to the top and saw the tip about deleting the random file inside the "install" folder (i use localhost 99% of the time so forgot about this). After deleting the file everything was fine, but i think that putting that message at the bottom and not at the top could be useful for other users.
Thanks.

**Comment by zero-24** [comment]
cc @tecpromotion Can you forward that to the italian TT IIRC they use Crowdin too so this should be solved there of if not within the core-translations repo I guess.

**Comment by richard67** [comment]
> Another issue (but maybe it's not an issue) i've found is that i'm not using localhost so the hostname is some thing like xxx.myhost.com and when i clicked on "install" nothing happened, i clicked few times and nothing still happens.

@PixedBo If you scroll up you should see an alert with an information message about an additional verification step when not using localhost as database server. It asks you to remove a special file from the installation folder to verify that you have access to the webserver. This step exists already sine Joomla 3.4 or so, it’s nothing new.

**Comment by richard67** [comment]
P.S. For moving that alert down there is already an issue here. I can’t find it right now but I‘m sure there is one.

**Comment by PixedBo** [comment]
> > Another issue (but maybe it's not an issue) i've found 
> @PixedBo If you scroll up you should see an alert with an information message about an additional verification step when not using localhost as database server. It asks you to remove a special file from the installation folder to verify that you have access to the webserver. This step exists already sine Joomla 3.4 or so, it’s nothing new.

Hi @richard67 and thanks for your reply. 
My mistake: the issue was not the message or the mechanics themself, but the fact the the message was not visibile and "nothing" happened on click. I knew the file to delete thing was present in j3 too, but the fact that it was not a one-page installation produced a more visibile warning.
