### ISSUE TITLE
Error with creating cronjon in Joomla 4.2

### ISSUE THREAD

**Issue by Lumiga** [joomla/joomla-cms#37533]
### Steps to reproduce the issue
Go to system > Scheduled Tasks > Add task > Akeeba Backup - Take a Backup
Execution Rule: Cron Expression (advanced)
0 minuten, 1 hours, Days of Week Monday 

### Expected result
Creating a task without errors

### Actual result
Error: /administrator/components/com_scheduler/src/Model/TaskModel.php on line 689

<html>
<body>

# | Function | Location
-- | -- | --
1 | () | JROOT/administrator/components/com_scheduler/src/Model/TaskModel.php:823
2 | Joomla\Component\Scheduler\Administrator\Model\TaskModel->wildcardIfMatch() | JROOT/administrator/components/com_scheduler/src/Model/TaskModel.php:690
3 | Joomla\Component\Scheduler\Administrator\Model\TaskModel->buildExecutionRules() | JROOT/administrator/components/com_scheduler/src/Model/TaskModel.php:597
4 | Joomla\Component\Scheduler\Administrator\Model\TaskModel->save() | JROOT/libraries/src/MVC/Controller/FormController.php:708
5 | Joomla\CMS\MVC\Controller\FormController->save() | JROOT/libraries/src/MVC/Controller/BaseController.php:735
6 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
7 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
8 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
9 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
10 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
11 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63
12 | require_once() | JROOT/administrator/index.php:32

</body>
</html>

### System information (as much as possible)
<html>
<body>

PHP Built On | Linux com-linweb274 5.10.103-combell #202203071342 SMP Mon Mar 7 13:42:40 UTC 2022 x86_64
-- | --
mysql
5.7.35-38-log
latin1_swedish_ci
utf8mb4_general_ci
None
Yes
8.0.17
Apache
fpm-fcgi
Joomla! 4.1.2 Stable [ Kuamini ] 30-March-2022 16:00 GMT
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36

</body>
</html>
<html>
<body>

Setting | Value
-- | --
256M
256M
256M
None
On
Off
On
Off
/data/sites/web/luciansnl/tmp
0
Yes
Yes
Yes
None
Yes
Yes
Yes
Yes
Yes
20000

</body>
</html>

### Additional comments
@bembelimen @nikosdion

**Comment by ditsuke** [comment]
@Lumiga thank you for creating this issue! I believe this is a duplicate of #37313. We'll work on getting a fix in soon. However you should be able to create the cron-rule based task still if you fill in all the fields. So for example, for your 0m, 1h and Monday example you should select Minute 0, Hour 1, Day Monday, and then select all the options for the month field and day-of-month field. I'll love to know if you're able to do so!

![image](https://user-images.githubusercontent.com/72784348/162769702-07a39544-e77c-4e5b-8819-6ce788968010.png)


Some reflection on my end, this is not at all a good UI as pointed out by others in the past and through this bug. We'll work on delivering a more friendly and intuitive UI for the cron rule selection in a future minor release. Would love it if you have any more feedback to share with us on the Scheduler either here or in a [GitHub Discussion](https://github.com/joomla/joomla-cms/discussions).

/cc @bembelimen

**Comment by bembelimen** [comment]
Thx for reporting, @Lumiga please check the other issue, if it's not the same, we can reopen here.

**Comment by Lumiga** [comment]
> @Lumiga thank you for creating this issue! I believe this is a duplicate of #37313. We'll work on getting a fix in soon. However you should be able to create the cron-rule based task still if you fill in all the fields. So for example, for your 0m, 1h and Monday example you should select Minute 0, Hour 1, Day Monday, and then select all the options for the month field and day-of-month field. I'll love to know if you're able to do so!
> 
> ![image](https://user-images.githubusercontent.com/72784348/162769702-07a39544-e77c-4e5b-8819-6ce788968010.png)
> 
> Some reflection on my end, this is not at all a good UI as pointed out by others in the past and through this bug. We'll work on delivering a more friendly and intuitive UI for the cron rule selection in a future minor release. Would love it if you have any more feedback to share with us on the Scheduler either here or in a [GitHub Discussion](https://github.com/joomla/joomla-cms/discussions).
> 
> /cc @bembelimen

@Ditsuke, I think it's the same issue indeed.

Creating a cronjob with your example works for me! 
Selecting all the days en months works fine and give no errors!
Thanks for the workaround.

Kind regards,
Lumiga

**Comment by nikosdion** [comment]
I can confirm that I could reproduce the issue and the fix. I also just realised I had bumped into this issue when documenting setting up a backup using Scheduled Tasks several weeks ago but I forgot to report it at the time 🤦🏽‍♂️
