### ISSUE TITLE
Router URLs problems J3 and J4 

### ISSUE THREAD

**Issue by mrownicki** [joomla/joomla-cms#37541]
### Steps to reproduce the issue
Clean installs J3.10.6 and J3.9.22 and Joomla 4.1.2

create 2 categories  [test, test2]
create 1 article  "test" in category test

turn on SEF and rewrite change .htaccess

Menu view category blog

### Expected result
test/1-nowy
test2/1-nowy  - return 404

/1-test/1-nowy show article
/2-test/1-nowy - return 404

### Actual result
test/1-nowy  show article
test2/1-nowy show article

In J3 additional setup legacy router.

/1-test/1-nowy show article
/2-test/1-nowy show article

Duplicate content! This same article, two URL.

Well now all articles generate urls in all available category. Should be available one url per category.

### System information (as much as possible)
This is happened when in J3 selected is modern router and legacy. Options Remove IDs from URLs is off.

Joomla 4 - Remove IDs from URLs is OFF

### Additional comments
Breadcrumbs show incorrect path too. screen,

Error caught thanks to google that reports duplicate content ...
Every site after migration will be this problem if remove id is off.
Which is normal if the old addressing is kept for SEO reason.

This will be fix ASAP :(

**Comment by brianteeman** [comment]
What are the menu items?

**Comment by brianteeman** [comment]
... and duplicate content does not count negatively in terms of seo. https://www.searchenginejournal.com/google-duplicate-content-is-not-a-negative-ranking-factor/394321/#close

**Comment by mrownicki** [comment]
Articles » Category Blog
J3 and J4.1.2

In J3 additional setup legacy router. 

/1-test/1-nowy  show article
/2-test/1-nowy  show article 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37541">issues.joomla.org/tracker/joomla-cms/37541</a>.</sub>

**Comment by mrownicki** [comment]
@brianteeman 

The url is supposed to be one, each duplication should point to 404.
Nobody wants permutation this same urls, this is not good practice.


There are many reasons why this type of situation should not occur.
The duplicate content itself is not considered, but google does not know which address is correct if it has 10 the same with different url. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37541">issues.joomla.org/tracker/joomla-cms/37541</a>.</sub>

**Comment by simbus82** [comment]
@mrownicki Unfortunately I can't test the behavior on Joomla 3, and at this point in its life I don't think it's even worth investing time.
But I didn't understand how to replicate it on Joomla 4: do I have to create categories and articles, theirs menus, and only then deactivate the IDs? Or i don't have to create menu voices?

PS: @brianteeman, the dear Muller's usual "ambiguous" statements that make "SEOs" laugh :-P He talks about the absence of penalties, he didn't say it's a good thing or a best practices right to achieve a good positioning with the best effort.
If I close an eye when I drive in my car, maybe no one will give me a ticket, but it's very likely that I'll have to go much slower to get to my destination.
If the Joomla "canonicals" worked, I would also agree that if the CMS duplicates the content we don't have any big SEO problems.
But then another problem comes for those who make "big" websites (thousands pages): "Crawl Budget". Duplicated contents and no canonicals can kill it.
Anyway a CMS that generate, without it being explicitly desired, a "duplicated && indexable" content, it's a CMS not really SEOptimized.

**Comment by mrownicki** [comment]
@simbus82 
do I have to create categories and articles, theirs menus, and only then deactivate the IDs? Or i don't have to create menu voices?

A create categories and 1 article. Categories in a menu blog layout. 
Remove id is off / Article url have ID in url.

![screen shot 2022-04-12 at 13 59 02](https://issues.joomla.org/uploads/1/042fbc1edec6f019a8c4ed20f91ed2ff.png)![screen shot 2022-04-12 at 13 59 03](https://issues.joomla.org/uploads/1/17ee12ca0fe9d09fe28ee422bad1f627.png)![screen shot 2022-04-12 at 13 59 05](https://issues.joomla.org/uploads/1/bdfb0595946f8d292d2f0c06a0bdb736.png)![screen shot 2022-04-12 at 13 59 06](https://issues.joomla.org/uploads/1/fd46971253f5c2d5a75eb67fec48c61e.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37541">issues.joomla.org/tracker/joomla-cms/37541</a>.</sub>

**Comment by ReLater** [comment]
The well-known behavior becomes an SEO problem when the user is stupid enough to make search engines aware of stupid URLs. Self-appointed SEO "experts" should be able to make website owners aware of the causes, such as poorly structured menus etc. and provide solutions like redirects. In most cases these "DC" URLs are pure theory.

**Comment by maxer77** [comment]
Author,Marcin created this issue for me.
 I discovered in Google Search Console, double working articles (after change category). I checked my website on my server and local server. 
Finally, I installed fresh Joomla 3 on local server. I was shocked that it's possible.
On picture you can can see:
(red color) - a random URL's. When we entered broken,changed URL should be redirect to alias set in backend. Nowadays working all URL
I repeated this bug on your Joomla website. 
(green color)  article in a random category. When we change category, article is double. Google says that its duplicate. normally should be 404 
![joomlaissue](https://user-images.githubusercontent.com/103517402/162992522-6285d29e-ed64-49c5-8af2-f640c6a9d0fe.png) 
I tried redirect old address to new,but (another shocking),redirect not working.

**Comment by mrownicki** [comment]
@ReLater 
This is not relative in structure menu ... ;/ 
If you read all post you see, a can call up all the address in all your categories... if don't see if this is not a problem. 
Then I don't understand your approach at all.
This is overall problem, not dedicate only a DC.

I changed the subject, maybe it was confusing.

**Comment by mrownicki** [comment]
All articles that are not assigned to their only one category and can be recalled should give 404. 
Otherwise, we have a URLs mess.

**Comment by brianteeman** [comment]
Jeez. For years people have known about this. That is why all the work was done to support urls without ID. Now you are complaining that the old way with ID is broken. We know thats why the feature was created.

**Comment by brianteeman** [comment]
(the redirect component is NOT a url rewriter. It will redirect a non-existent page (404) to an existing page.)

**Comment by mrownicki** [comment]
@brianteeman 
I don't use ID, I write this ticket for maxer77
But there are pages that were not created today but years ago and they still use ID.

So no one thought about creating an address migration for the redirect extension so that there would be no problems and that from joomla 4 the problem would not occur.

As you imagine on a page of 20k articles to suddenly disable ID from addresses .... And you have 404 20k urls.

And then you are surprised that joomla has the opinion not seo friendly cms.

Over the years I have learned about the surprises in joomla. But many users don't, and they should be taken care of. The old arm can handle the new one.

**Comment by brianteeman** [comment]
Please read carefully the posts before replying again. If you stop using id then you can use the redirect component.  If you still use the id then you will get these known issues. The solution is not to use the id.

**Comment by simbus82** [comment]
> As you imagine on a page of 20k articles to suddenly disable ID from addresses .... And you have 404 20k urls.

A website with 20K articles is not an "amateur" website.
So a SEO person, i hope, is involved. You can solve the problem with a row in htaccess with a RewriteRule and a regex.
Example (to be deeply tested):
```
RewriteRule ^(.*)\/[\d]*\-(.*)$ $1/$2 [L,R=301]
```

> And then you are surprised that joomla has the opinion not seo friendly cms.

Ok i can understand, lot's of CMS automatically create an internal redirect in these cases (Prestashop, Magento 1 & 2, ecc.), sometime you have a choice for a 301 or 302 redirect too.

I have tested the problem, but for me, the url ID can ben totally removed from CMS :-)
I hate it since 2005.
I never used it before the modern routing too (i have used some plugins to remove it years ago, since Joomla 1.0).

I'm having hard time to understanding if it is really necessary to solve this problem "today".  :-(

As @ReLater said, this "problem" has been known for a long time and can be solved in different ways, in addition to the fact that you can always set, with external tools, a canonical that also eliminates (totally) the problem of duplication.

**Comment by mrownicki** [comment]
For me, the topic is probably exhausted that @maxer77 ax has something to add  ;-)

@simbus82 
`RewriteRule ^(.*)\/[\d]*\-(.*)$ $1/$2 [L,R=301]`
I know;) Always need to test using. Example this rule with YTP it blows up the internal cache YTP. 
I don't use ID either. 
20k only show example ;)

Regards.

**Comment by drmenzelit** [comment]
Closing that as it is expected behavior.

**Comment by simbus82** [comment]
"Example this rule with YTP it blows up the internal cache YTP"
I don't understand. YTP is an acronym for? '^_^

Which internal cache this rule blows?

**Comment by drmenzelit** [comment]
I guess YTP = Yootheme Pro
