### ISSUE TITLE
Iframe Menu Item -> Scroll Bar Parameters tab missing Scroll Bars No/Yes/Auto Field

### ISSUE THREAD

**Issue by bayareajenn** [joomla/joomla-cms#37544]
### Steps to reproduce the issue
1. Login to the backend of Joomla 4.1.2
2. Add a new menu item "Wrapper -> Iframe"
3. Click on Scroll Bar Parameters tab
There are two fields displayed; Width and Height. There should be a third field "Scroll Bars" with the options of No/Yes/Auto. The help screen shows this field.![screen shot 2022-04-12 at 17 16 54](https://issues.joomla.org/uploads/1/53e51d691e3290797d8588c11858016d.png)

### Expected result
To see and be able to use the Scroll Bars field.

### Actual result
There is no Scroll Bars field. 

### System information (as much as possible)
Joomla 4.1.2
PHP 8.1

**Comment by richard67** [comment]
I think the parameter has been removed with this PR: #32913 . @bayareajenn Please check and if that attribute is really deprecated then close this issue here as expected behavior.

The help pages often are not up to date with the latest code changes so they cannot server as a reference.

**Comment by bayareajenn** [comment]
Thanks @richard67 
Sadly, we use this in our custom extension in an integration. So I guess I'll have to come up with some work around which is unfortunate. In working on getting our extension ready for J4, I found this bug which is not a bug but rather someone thinking no one uses it. Bummer.

**Comment by richard67** [comment]
@bayareajenn As said, the scrolling attribute is deprecated. See e.g. here: https://stackoverflow.com/questions/5048793/the-scrolling-attribute-on-the-iframe-element-is-obsolete-use-css-instead . Maybe you can achieve the same by adding a css class?

**Comment by bayareajenn** [comment]
@richard67 I'm sure I'll figure something out. I can give a go to a CSS class. Thank you for helping me figure this out and for your time and service.
