### ISSUE TITLE
Iframe Menu Item -> Advanced tab Auto Add set to "No" is ignored

### ISSUE THREAD

**Issue by bayareajenn** [joomla/joomla-cms#37545]
### Steps to reproduce the issue
1. Login to the backend of Joomla
2. Add a new Menu Item with the Menu Item Type Wrapper -> Iframe
3. Give it any Title - doesn't matter
3. Click the Advanced tab
4. Change the Auto Add field from Yes to No
5. Click the Details tab
6. Enter a URL without http or https into the URL field (doesn't matter what it is, let's say google.com)
7. Click Save
8. The URL now has http:// added even though the parameter has been set to "No" for Auto Add

### Expected result
That no http or https is added to the URL field when the Auto Add field is set to no.

### Actual result
http is added when it shouldn't be

### System information (as much as possible)
J 4.1.2
PHP 8.1

**Comment by Quy** [comment]
Duplicate #33235?

**Comment by chmst** [comment]
The parameter is for the frontend, it is not used in backend. 
The filter="url" in the url field writes a http:// as prefix.

**Comment by chmst** [comment]
@Quy not a duplicate but similiar. I made a PR - but need more opinions if this has side effects.

**Comment by chmst** [comment]
Closing as there is a PR. Please test https://github.com/joomla/joomla-cms/pull/37547
