### ISSUE TITLE
[4.x] Batch Copy fields

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37555]
### Steps to reproduce the issue
Create a content field
Use the batch function to COPY the field
Publish the new field
Open an article for editing

### Expected result
Field tab has TWO fields with the same label

### Actual result
Field tab has ONE field only

### Additional comments
When you create a field it checks that the generated name is unique and if not prevents saving.

When you batch copy a field there is no check and you end up with invalid data as you have multiple fields with the same name (but diffeerent id)

**Comment by hytsch** [comment]
exactly.

**Comment by brianteeman** [comment]
So this should be closed as a duplicate

**Comment by brianteeman** [comment]
closed as we have a pr #38682
