### ISSUE TITLE
[4.1] Latest User Actions: Links not recognized

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#37557]
### Steps to reproduce the issue
Set up mail settings, enable sending actions for all components in the user settings ("User Actions Log Options" tab), then perform a few actions in the control panel.

An email will be sent to you with the latest activity. Note that links are not recognized + probably it makes sense to change the date in the letter to the format proposed in PR https://github.com/joomla/joomla-cms/pull/37556.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/163557826-2af34408-dd9e-45ca-a1ff-72a0fecdae3c.png)

As for link recognition, as soon as we change the "Mail Format" parameter to HTML or BOTH in the settings of the "Mail Templates" component, the format of the letters will change to readable.

![Screenshot_2](https://user-images.githubusercontent.com/8440661/163558089-7f541437-86cf-4869-8c0f-a836dea6e47a.png)

**Comment by Quy** [comment]
Duplicate #35028?
