### ISSUE TITLE
Module start level / end level not working right

### ISSUE THREAD

**Issue by oxido21** [joomla/joomla-cms#37553]
### Steps to reproduce the issue
Create a menu with at least 3 levels of sub-menus, like so:
Menu (level 1)
-Sub-menu (level 2)
--Sub-sub-menu (level 3)
Create a module to display this menu and set the "start level" to 2

### Expected result

In the module I expect to see this menu items:
Sub-menu
-Sub-sub-menu

### Actual result
I see nothing, no menu item is rendered.

### System information (as much as possible)
No errors (debug was enabled)

### Additional comments
After 2h of testing.
I've made alot of test's, and it worket 1 time only but with this condition.
I've set the "start level: 2" and "End level 3", it din't work if the "end level was: All".

**Comment by chmst** [comment]
@oxido21 thanks for reporting. Is it Joomla 3.x?

In J4 your use case works for me. Startlevel 2 and end level "all" shows levels 2 and 3. .

**Comment by oxido21** [comment]
Yes, joomla 3.10.8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37553">issues.joomla.org/tracker/joomla-cms/37553</a>.</sub>

**Comment by brianteeman** [comment]
And what is the basee item in your tests

**Comment by oxido21** [comment]
URL, I have added an image.![screen shot 2022-04-14 at 06 23 39](https://issues.joomla.org/uploads/1/a9ee658d41450ac35093d8d0186024cb.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37553">issues.joomla.org/tracker/joomla-cms/37553</a>.</sub>

**Comment by brianteeman** [comment]
Menu Type URL is the problem.

**Comment by oxido21** [comment]
Same problem with "Heading" type<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37553">issues.joomla.org/tracker/joomla-cms/37553</a>.</sub>

**Comment by brianteeman** [comment]
Yes - that is expected. They are not real menu items so the module does not know it neeeds to be displayed

**Comment by oxido21** [comment]
For me it doesn't work with other types of menus either![screen shot 2022-04-14 at 06 48 51](https://issues.joomla.org/uploads/1/aa599574beb0290ec84205a68216ae03.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37553">issues.joomla.org/tracker/joomla-cms/37553</a>.</sub>

**Comment by oxido21** [comment]
More info, maybe it helps.
If I change the level to start from 1 to 3 and I access any of the sub-menus, after, we can change back the level to start from 2 to 3 and the menu it is visible.
But if I exit from the sub-menus, the menu is no longer visible in front-end<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37553">issues.joomla.org/tracker/joomla-cms/37553</a>.</sub>

**Comment by brianteeman** [comment]
cache?

**Comment by oxido21** [comment]
No, it's just the way it works.
I will try a better explanation.
Item_A  (level 1)
--Item-sub_A (level 2)
---Item-sub_A-A (level 3)
--Item-sub_B (level 2)
I set the module to show the menu using starting level 1 to all ( I can see the menu in front-end).
a) I access any of the sub items
b) I change the module to show the menu using starting level 2 to all (I refresh the page and the menu it is visible, without the root item and I can switch between any of this sub-items of the menu)
--Item-sub_A (level 2)
---Item-sub_A-A (level 3)
--Item-sub_B (level 2)
C) I click on the logo of the website and I access the home page (the menu is not visible anymore)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37553">issues.joomla.org/tracker/joomla-cms/37553</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
