### ISSUE TITLE
[4.x] Unpublished/Trashed Category bug

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37577]
### Steps to reproduce the issue
Create a catgory called test and create 4 articles in that category. Add a tag to each article
Create a module to display popular tags and counts
Unpublish or Trash the category

### Expected result - Admin
The article manager indicates in some way that the article cannot bee displayed as the category is unpublished

### Actual result - Admin
the articles are listed exactly the same as all other articles

### Expected result - Site
in the tags module the count of articles per tag only includes articles which can be displayed

### Actual result - Site
the count of articles per tag includes all articles. So the count might display 4 but if they are all in an unpublished article cateory then the link from the module shows zero articles.

### Additional comments
Not sure if this is good enough but perhaps something like this

![image](https://user-images.githubusercontent.com/1296369/163974288-92cf27bd-1e1a-4728-8473-206ea122f04e.png)

**Comment by chmst** [comment]
Agree with administration, indicating the state of the category would be useful.

> in the tags module the count of articles per tag only includes articles which can be displayed. 

I think that articles can be diplayed if their tag is published, independent of the category.

**Comment by brianteeman** [comment]
> I think that articles can be diplayed if their tag is published, independent of the category.

No they can't which is how I discovered this bug

[edit] it also effects trashed categories

**Comment by chmst** [comment]
Sorry - poor english. Yes they have to be displayed and counted if the tag is published (and the article itself) independent from the stat of the category.

**Comment by brianteeman** [comment]
not sure I agree. If the tag and article is published but the category is not published then it should not bee counted because the article cannot be displayed

**Comment by brianteeman** [comment]
another option for the article list is instead of adding the text to the category name we change the icon and message on the status column. Maybe to a red triangle. With a message - this article will not be displayed as the category is unpublished.

**Comment by chmst** [comment]
I am not sure about that. Tags enable a kind of multi category solution. If I unpublish the main category - maybe I want to keep it in another category (tag)?

**Comment by brianteeman** [comment]
Then there is no point in adding a message in the article manager at all because it would have to say

this article will not be displayed as the category is unpublished/trashed unless it also has a tag which is published

**Comment by chmst** [comment]
I agree that this would be confusing.

**Comment by rdeutz** [comment]
Closing as we have a PR #37578

**Comment by brianteeman** [comment]
Please re-open this as @rdeutz pr only addresses half of the issue

**Comment by brianteeman** [comment]
Closing as both issues are now resolved.
