### ISSUE TITLE
check box is overlapping to the content

### ISSUE THREAD

**Issue by Raunaksingh100** [joomla/joomla-cms#37573]
### Steps to reproduce the issue
The check box is overlapping to the content you can check the bug from this link - https://www.joomla.org/sponsorship-application.html
and see in the screenshot which is given below for the better understanding.

### screenshot
![bug](https://user-images.githubusercontent.com/65535360/163786055-649e239e-e6d6-4ca2-946f-484765283706.PNG)

### System information (as much as possible)
windows 10

**Comment by brianteeman** [comment]
This should bee reported at  https://github.com/joomla/joomla-websites/issues/new?title=[joomla.org]%20&body=Please%20describe%20the%20problem%20or%20your%20issue

**Comment by richard67** [comment]
@Raunaksingh100 Please report at the place suggested in the previous comment. Thanks in advance. Closing here as not an issue with the CMS core.
