### ISSUE TITLE
[4.1.x] Privacy Consent - I do not agree - Language String

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#37579]
Hi guys,
this is valid also for 3.10.x
Into the Registration page the "I do not agree" Privacy Consent is shown as "No" - [Here an image](https://photos.app.goo.gl/YkrpEJ3NQh9ei7Zh9)

PLG_SYSTEM_PRIVACYCONSENT_OPTION_AGREE
I agree
PLG_SYSTEM_PRIVACYCONSENT_OPTION_DO_NOT_AGREE
No - …I cannot find this language string...
PLG_USER_TERMS_OPTION_AGREE
I agree
PLG_USER_TERMS_OPTION_DO_NOT_AGREE
I do not agree

**1** - It should be "I do not agree" as for Terms Consent

**2** - I'm not able to find the relative PLG_SYSTEM_PRIVACYCONSENT_OPTION_DO_NOT_AGREE language string. Please, Where is ?

**Comment by drmenzelit** [comment]
> PLG_SYSTEM_PRIVACYCONSENT_OPTION_DO_NOT_AGREE
> No - …I cannot find this language string...

There is no specific language string for that, it is `JNO` (plugins\system\privacyconsent\forms\privacyconsent.xml)

**Comment by Quy** [comment]
PR #37346 for 3.10 is waiting to be merged which will be upmerged to 4.1.

**Comment by zero-24** [comment]
The 3.10 PR has been merged now and will be shipped with 3.10.9
