### ISSUE TITLE
Article Newsflash Module does not show introtext if introtext is custom field

### ISSUE THREAD

**Issue by bubi-luka** [joomla/joomla-cms#37576]
### Steps to reproduce the issue

1. Create custom field Introduction text.
2. Create new article.
3. Fill text into Introduction text custom field.
4. On Article Text field insert this custom field as intro text.
5. Create module Article Newsflash module.
6. Insert module into another article (i.e. frontpage article).

### Expected result
:heavy_check_mark: The intro text should be visible on all articles.

### Actual result
:heavy_check_mark: The intro text is visible on articles, where intro text is entered as text on main content field.
:x: The intro text on the articles, where it was entered as custom field, is not visible.

### System information (as much as possible)

Setting | Value
-- | --
PHP Built On  | Linux Pinus 5.16.19-200.fc35.x86_64 #1 SMP PREEMPT Fri Apr 8 15:34:44 UTC 2022 x86_64
Database Type  | mysql
Database Version  | 10.5.13-MariaDB
Database Collation  | utf8mb4_general_ci
Database Connection Collation | utf8mb4_general_ci
Database Connection Encryption  | None
Database Server Supports Connection Encryption  | No
PHP Version | 8.0.17
Web Server | nginx/1.20.2
WebServer to PHP Interface | fpm-fcgi
Joomla! Version | Joomla! 4.1.2 Stable [ Kuamini ] 30-March-2022 16:00 GMT
User Agent | Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:99.0) Gecko/20100101 Firefox/99.0

**Comment by drmenzelit** [comment]
That is expected behavior: modules don't display custom fields. If you want to show a custom field on a module you can create an override.

**Comment by bubi-luka** [comment]
@drmenzelit : Can I please ask for help regarding setting this override?

**Comment by drmenzelit** [comment]
https://magazine.joomla.org/all-issues/july-2021/custom-fields-list-of-resources
https://www.web-eau.net/developpement/joomla-overrides

**Comment by bubi-luka** [comment]
Thank you!
