### ISSUE TITLE
Does not specify the error

### ISSUE THREAD

**Issue by pearlpriyanka** [joomla/joomla-cms#37575]
### Steps to reproduce the issue
Try to upload an extension in the "upload package file" link will cause an error when you upload a folder in this link, But the error caused is not specified it just shows a red colored error bar without any content.

### Expected result
The error should be specified in the red colored error bar saying "Package FIles not found" when the user tries to upload any other file.
![Screenshot (26)](https://user-images.githubusercontent.com/62989282/163921717-426ed016-bb70-4023-8d03-b6fa6a8ddc04.png)

### Actual result
But the actual result is it does not specify any error, it just shows a red bar with an error symbol.
![Screenshot (25)](https://user-images.githubusercontent.com/62989282/163921751-622e26a1-2ddb-4a72-a6bb-d7417fd4eda1.png)

### Additional comments
The user should upload the extension under the "install from folder" link to avoid this issue but the error should be specified for new users to be able to work efficiently.

**Comment by brianteeman** [comment]
Confirmed - empty error message

**Comment by brianteeman** [comment]
I believe it is duee to a javascript error

POST http://localhost/joomla-cms/administrator/index.php?option=com_installer&task=install.ajax_upload net::ERR_ACCESS_DENIED
Joomla.request @ core.js?e718547c598935f1b696b04a8a218a74:730
(anonymous) @ packageinstaller.js?e718547c598935f1b696b04a8a218a74:151

**Comment by brianteeman** [comment]
please test #38227

**Comment by alikon** [comment]
closing as we have a pr to test #38277

**Comment by richard67** [comment]
> closing as we have a pr to test #38277

No, it's #38227 . Please test.
