### ISSUE TITLE
Pragamatically install joomla

### ISSUE THREAD

**Issue by godinc0** [joomla/joomla-cms#37582]
I'm developing an application that will let you install joomla without the original configuration page.

I have some difficulties populate the table and calling joomla scripts from my application to start the installation. I'm currently trying to post locally on the domaine/installation/index.php but i see that there is multiple script and endpoints that is called.

Does any dev have some recommendations to install joomla ragamatically (via a script) or can i get in touch with any joomla developper for help ?

Anyone already did this ?

Thank you !

**Comment by brianteeman** [comment]
I can see that you have already asked the same question on the forum and as that is the most appropriate place for this question please close this here.

**Comment by godinc0** [comment]
Ok. Is it possible to talk with you ? I'm currently working on app that can bring a lot of user to Joomla  ?
I just need a little help for the integration.
