### ISSUE TITLE
[4.x] Scheduler CLI

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37586]
### Steps to reproduce the issue
Use the joomla cli to change the state of a scheduled task

`php cli/joomla.php scheduler:state`

and follow the prompts

### Expected result
The state is changed 

### Actual result
The state is always set to be enabled

### Additional comments
![cli](https://user-images.githubusercontent.com/1296369/164189678-548b9482-615a-4415-9387-88c37d06be46.gif)

**Comment by vorayash** [comment]
Path: joomla-cms\libraries\src\Console\TasksStateCommand.php
![image](https://user-images.githubusercontent.com/72155000/164239233-b00d2f54-251a-4f52-ab13-bd923d2bc96d.png)
if we state is valid then value of the state should be itself, right?
![image](https://user-images.githubusercontent.com/72155000/164239682-0255d4cc-3292-43e4-b2ca-7da92554b922.png)

**Comment by alikon** [comment]
i've experienced this times ago 
forgot to sumbit my dirty fix #37591
