### ISSUE TITLE
[4.2] TinyMCE 6.x

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37596]
TinyMCE 6 is now available. Although it claims to be backwards compatible in how it is used there will be changes required in the plugin for configuration etc. It might also require a notice (as before) that the plugin needs to be saved again to update existing installs.

@roland-d

**Comment by roland-d** [comment]
@brianteeman Looking at the release info, they do say there are breaking changes on this page:
https://www.tiny.cloud/blog/tinymce-6-0-whats-new/

Checking the [migration guide](https://www.tiny.cloud/docs/tinymce/6/migration-from-5x/) also lists a lot of changes that are big  and breaking changes with how it used to work.

I don't see this going into 4.2 at least as it is going to require a lot of work to make sure nothing breaks.

**Comment by brianteeman** [comment]
Without digging into the code its hard to be certain BUT everything that had been deprecated before I had already removed from our implementation

**Comment by brianteeman** [comment]
> I don't see this going into 4.2 at least as it is going to require a lot of work to make sure nothing breaks.

That would be a real shame. TBH there is nothing in 4.2 yet that eveen justifies a release

**Comment by roland-d** [comment]
> Without digging into the code its hard to be certain BUT everything that had been deprecated before I had already removed from our implementation

So we are going to need a PR to check everything. Without that it is just a discussion based on a blog entry. I have no idea how stock or customized our TinyMCE is.

> That would be a real shame. TBH there is nothing in 4.2 yet that eveen justifies a release

A release is not based on features but based on time. Features that are tested and ready, let's put them in. If they are not ready, don't force them in just because you must have a feature.

**Comment by brianteeman** [comment]
Just because you reach a date is a poor reason to force an update

**Comment by laoneo** [comment]
You may want to have a look at #37633, it is still in draft mode.

**Comment by N6REJ** [comment]
closed as there is a pr
