### ISSUE TITLE
[4.2] Composer install psr-4

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37606]
### Steps to reproduce the issue
Joomla 4.2 run composer install

### Actual result
`Class Joomla\Tests\Unit\Libraries\Cms\Uri\JUriTest located in C:/htdocs/joomla-cms/tests\Unit\Libraries\Cms\Uri\UriTest.php does not comply with psr-4 autoloading standard. Skipping. `

**Comment by BilalAhmerCS** [comment]
Actual result
Class Joomla\Tests\Unit\Libraries\Cms\Uri\JUriTest located in C:/htdocs/joomla-cms/tests\Unit\Libraries\Cms\Uri\UriTest.php does not comply with psr-4 autoloading standard. Skipping.

**Comment by laoneo** [comment]
Please test #37632.
