### ISSUE TITLE
[4.2] Regression related to multiselect.js

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#37600]
### Steps to reproduce the issue
Install a 4.2 package.

Go to a list view that includes more than 2 records and uses multiselect.js, for example the update extensions installer:
http://root/administrator/index.php?option=com_installer&view=update

Select one of the checkbox.

### Expected result
Only that checkbox is checked

### Actual result
The same checkbox and the next one is checked. 2 checkbox are checked at once.

### System information (as much as possible)
The error is due to this change in the file multiselect.js, line 16.

Joomla 4.1 OK:
this.boxes = [].slice.call(this.tableEl.querySelectorAll('input[type=checkbox]'));

Joomla 4.2 ERROR:
this.boxes = [].slice.call(this.tableEl.querySelectorAll('td input[type=checkbox]'));

![image](https://user-images.githubusercontent.com/17835460/164558318-ed04d579-69d1-469f-ad49-e9e638d58423.png)

**Comment by brianteeman** [comment]
I'm sure this was fixed some time ago

**Comment by joeforjoomla** [comment]
@brianteeman at the moment the issue is still present in the 4.2 Alpha 3 dev. Not sure where is has been fixed and still not merged.

**Comment by Fedik** [comment]
It only for com_installer "update" view , please test #37725

**Comment by joeforjoomla** [comment]
@Fedik #37725 this does not work! The multi select feature is lost!
