### ISSUE TITLE
[4.2] fubar - language installation not possible 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37616]
### Steps to reproduce the issue
in a completeely clean folder checkout thee 4.2 branch
composer install
npm ci
log in to the admin of the new site
install an additional language

### Expected result
everything works

### Actual result
Unable to detect manifest file.

![image](https://user-images.githubusercontent.com/1296369/164770893-ede7c103-7e64-4336-a9e9-4bf346cba4b9.png)

### System information (as much as possible)

Database Type	mysql
Database Version	8.0.19
Database Collation	utf8mb4_unicode_ci
Database Connection Collation	utf8mb4_0900_ai_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	Yes
PHP Version	8.0.10
Web Server	Apache/2.4.41 (Win64) mod_fcgid/2.3.10-dev

### Additional comments
earlier checkouts of 4.2 work fine

**Comment by chmst** [comment]
Confirmed. $package['type'] is empty.

**Comment by brianteeman** [comment]
i **deliberately** did not put language installation not possible in the title as that was just one exampl of 4.2 beeing fubar and was easy to reproduce. The language installer must be a symptom of thee real issue whatever that is

**Comment by brianteeman** [comment]
closing. Sorry I forgot that you cannot install languages in 4.,2 as this PR has not beeen merged https://github.com/joomla-extensions/pkg_languagepack/pull/97

**Comment by chmst** [comment]
I also think that this is a side effect and a maybe a result of changing paths but could not identify yet.  But we always ask users to choose titles.. At the first glance I thought that this is spam.

**Comment by brianteeman** [comment]
I will seee if I can find a better example and create a new issue for that
