### ISSUE TITLE
4.1 & 4.2 Weblinks Submit an Article via Front-End Fails to Open Editor

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#37626]
### Steps to reproduce the issue
Weblinks Extension install OK and all functions properly via Super User Back-End, create everything, including Weblinks.
Created a Menu Link Item = Submit a Weblink, which appears on the front-end.  Have tested for both public and registered users; only when the Super User is logged in does it work properly.
When anyone other than Super User attempts to Submit a Weblink it fails with a "Requested Page Not Found" display.  Have tried every editor configuration; same front-end result for everyone but the Super User.

### Expected result

When a user clicks the front-end Submit a Weblink, the editor panel should display into which weblink information can be added.

### Actual result

Submit a Weblink via the front-end fails for all but the Super User.

### System information (as much as possible)

Fully operating website on GoDaddy linux server, V.4.1.2 and V.4.2 of Joomla! test with same failure.

### Additional comments
Please fix this Joomla-owned Extension so as to allow, at the minimum, a registered user to Submit a Weblink.

Alternate question:  Does the non-Super User submission require a Captcha feature enabled?

**Comment by joomdonation** [comment]
Hello

Please access to Weblinks extension, then click Options button in the toolbar, look at Permissions tab, select **Registered** user group and set **Create** permission to Allowed, then try again, it should work well (see attached screenshot)

For more questions/issues, please create a new issue on Weblinks repo https://github.com/joomla-extensions/weblinks and we will reply you further from there.

Closing this issue for now.
![weblinks_permissions_settings](https://user-images.githubusercontent.com/977664/164910429-33e2dbfa-862d-495e-97b7-552ff5b0d99e.png)
