### ISSUE TITLE
On clean installation there are some com_search components (including the module) that should not be there and in fact searching, gives error jevent dispatcher not found.

### ISSUE THREAD

**Issue by aspergerway** [joomla/joomla-cms#37627]
### System information (as much as possible)

Clean installation of joomla 4.1.2

![Search package and plugins](https://user-images.githubusercontent.com/43296926/164912932-f8325509-3ade-4e93-a131-8a0705a875fd.png)
![Search Module](https://user-images.githubusercontent.com/43296926/164912930-60c2e056-470a-44a8-b323-51cc38db805a.png)

**Comment by brianteeman** [comment]
Where did you get the zip fil to install from?

As I can see you also have code from joomshapr builder and that has never been part of the core.

So either you did not install in a clean directory or the zip file was not from joomla

**Comment by aspergerway** [comment]
I installed Joomla inanoera clean and then installed helix ultimate only
template and then SP Page builder.
I downloaded the zipper files from joomla.org.

Il Sab 23 Apr 2022, 18:45 Brian Teeman ***@***.***> ha
scritto:

**Comment by brianteeman** [comment]
so it was not a clean install.

**Comment by aspergerway** [comment]
I didn't upgrade from Joomla 3.10.8

You mean com_search was installed either from helix or sp page builder!

I'm not talking about the search on so page builder plugin, I'm talking
about the fact that installing either the template or the page builder,
also brings com_search.

Is it therefore possible? Are you telling me this?
If so and I understood correctly, I didn't know it.

By clean installation I meant installation from zipper file not upgrading
from 3.10.8.

Il Sab 23 Apr 2022, 20:36 Brian Teeman ***@***.***> ha
scritto:

**Comment by brianteeman** [comment]
> You mean com_search was installed either from helix or sp page builder!

well its not coming from the joomla.org supplies zip

**Comment by brianteeman** [comment]
I can confirm that both the helix ultimate template and the helix quickstarter package both contain lots of the garbage you are seeing

**Comment by chmst** [comment]
That's bad. 
But it is nothing where joomla devlopers can help. @aspergerway please deactivate the old crap .. November 2005?
Maybe supporters in foum.joomla.org have already workarounds for you. 
I close this for now.

**Comment by aspergerway** [comment]
non ho usato quickstart. deve essere stato helix ultimate. Grazie!

Il giorno sab 23 apr 2022 alle ore 22:28 Christiane Maier-Stadtherr <
***@***.***> ha scritto:

**Comment by aspergerway** [comment]
I didn't use quickstart. it must have been helix ultimate. Thank you!

Il giorno dom 24 apr 2022 alle ore 21:44 Asperger Way - Ilaria e Simone <
***@***.***> ha scritto:
