### ISSUE TITLE
[4.x] cli cache clean

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37646]
### Steps to reproduce the issue
in global config enable cache
navigate the site to put some files in the cache
confirm there are files in the cache
![image](https://user-images.githubusercontent.com/1296369/164999344-d49d0cea-0524-4d20-af4d-9ebfc1e72465.png)

run `php cli/joomla.php cache:clean`

### Expected result
![image](https://user-images.githubusercontent.com/1296369/164999362-9fbd8c45-484a-4c5e-a4c6-fdfb3ad21693.png)

and confirmed when checking  Maintenance: Clear Cache in the admin ui

### Actual result
![image](https://user-images.githubusercontent.com/1296369/164999392-5298dddb-d12a-4c5a-a201-91b348cc2ded.png)

BUT no files have been removed as can be confirmed in the admin ui or by checking the disk

### System information (as much as possible)

Database Type	mysql
Database Version	8.0.19
Database Collation	utf8mb4_unicode_ci
Database Connection Collation	utf8mb4_0900_ai_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	Yes
PHP Version	8.0.10
Web Server	Apache/2.4.41 (Win64) mod_fcgid/2.3.10-dev

**Comment by alikon** [comment]
please test #38091
