### ISSUE TITLE
[4.1.x] Cassiopea Password Reset process pages classes

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#37642]
Hi guys, 
about the Cassiopea Password Reset process pages classes:

[Reset](https://photos.app.goo.gl/stYPPDk3qPL8m24T8 "Reset")
com-users-reset reset 
> Okay

[Reset Confirm](https://photos.app.goo.gl/fNEvoyNQ3yXy81js7 "Reset Confirm")
com-users-reset-confirm reset-confirm 
> Shouldn't that be com-users-reset reset-confirm ? 

[Reset Complete](https://photos.app.goo.gl/yeR9nUiKAzgERqha8 "Reset Complete")
com-users-reset-complete reset-complete 
> Shouldn't that be com-users-reset reset-complete ?

**Comment by brianteeman** [comment]
Possibly but it cant really be changed now

**Comment by brianteeman** [comment]
maintainers please make a decision

**Comment by joomleb** [comment]
@brianteeman 
thanks, from my point of view, I continue to believe that is a simple fix to a "bug" (the classes as they are written now don't make much sense, so I still assume that was not the real developer's aim)

**Comment by brianteeman** [comment]
It's not a simple fix as you would need to address all existing website

**Comment by chmst** [comment]
The same structure of classnames is used in all components. extension-view__detail. 
It is not related to Cassiopeia but is in the core,  will not be changed for password reset.

**Comment by brianteeman** [comment]
@chmst I dont understand why you marked this as a new feature and did not close

**Comment by Hackwar** [comment]
I agree with @chmst evaluation. Since this is expected behavior, I'm closing this issue.
