### ISSUE TITLE
[3][4] Language string for agree / don't agree

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#37649]
### Is your feature request related to a problem? Please describe.
In different plugins the consent radio button has different labels for I agree / I don't agree
Possible solution: Generic language key JAGREEand  JNOTAGREE instead of individual language keys for plugins 

### Describe the solution you'd like
Same language string for the labels of all consent radio buttons

### Additional context
seen in  #37645 
related #37181

**Comment by zero-24** [comment]
While I see the argument i would say we are good to go with individual strings here. As that allows to adjust them on a per place basis. Yes/No are very simple thing but I agree / I dont agree can be different or depending on the usecase be changed only on one place.

**Comment by brianteeman** [comment]
as @zero-24 says it might be that on a terms and conditions page you would want to say "I accept" instead of "I agree"

**Comment by chmst** [comment]
But then the disagree label  should be "I don't agree" or "I don't accept" instead of "no" like here #37181

**Comment by zero-24** [comment]
Yes thats what has been changed there from "No" (JNO) to "I dont agree" with an dedicated string.

**Comment by chmst** [comment]
please test #37656

**Comment by brianteeman** [comment]
i think you meant #37656
