### ISSUE TITLE
[4.1.x] Cassiopea Registration page Privacy/Terms alignment

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#37645]
Hi guys, 
about the [Cassiopea Registration page Privacy/Terms alignment](https://photos.app.goo.gl/6VZuH7Ja7RQ8yfKt5 "Registration Privacy/Terms"),
Should not be better to add by default:

.required.radio {
  display: inline-flex;
  gap: 1rem;
}

to align them horizontally and don't waste precious space ?

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37709 . Thanks in advance.
