### ISSUE TITLE
[urgent] appscdn.joomla.org certificate expired

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#37655]
Cross posting here to gain maximum attention from people who might actually be able to fix this. 

> Happened again on 23.4.2022 ;-)

_Originally posted by @masbaehr in https://github.com/joomla/joomla-cms/issues/7614#issuecomment-1108888205_

<img width="734" alt="Screen Shot 2022-04-25 at 19 19 19" src="https://user-images.githubusercontent.com/400092/165149903-7477249c-c760-484c-98e6-b165d7a58720.png">

**Comment by HLeithner** [comment]
Is hopefully fixed now. We moved from the old CDN to cloudflare.
