### ISSUE TITLE
[4.1] Fronted edit Tinymce + add image cover window

### ISSUE THREAD

**Issue by mrownicki** [joomla/joomla-cms#37651]
### Steps to reproduce the issue

Login front add article.
TinyMCE click ... dots to show all element now add media 

### Expected result
Modal widow to on top

### Actual result
TinyMCE show on top
![screen shot 2022-04-25 at 11 09 50](https://issues.joomla.org/uploads/1/3391b0bf49bc3325fabe7f0c3fb6b012.png)

### System information (as much as possible)
4.1.2 Cassiopeia edit on front.

### Additional comments
Check on Opera and Chrome work this same.

**Comment by vorayash** [comment]
Can you please upload screen recording on how to reproduce issue?

**Comment by mrownicki** [comment]
https://user-images.githubusercontent.com/28987360/165355979-1b4a969d-bb1d-4d92-bca2-c5db606f1a8b.mp4

I now find this is only happened if TinyMCE have setup toolbard mode - floating. 
I try help to find and fixed using z-index but this maybe work on js.

**Comment by brianteeman** [comment]
Well it makes sense that floating mode does that.

**Comment by drmenzelit** [comment]
Closing that as expected behavior when using floating toolbar mode in TinyMCE
