### ISSUE TITLE
[4.x] Testing Sample Data plugin should be removed

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37663]
I know it is not shipped with any release but people do use it for testing.

The problem is that as well as being outdated it is also broken in many ways which means that it cant really be used for testing. I suspect assets tables but can't be certain without spending a lot of time etc

Examples.
Menu items cannot be copied to another menu. The batch copy appears to be successful but the menu items are not displayed
The deep items menu can never be expanded.

I propose that it is removed until someone has the time to build a completely new set. Testing with broken data is worse than not testing

**Comment by brianteeman** [comment]
I dont mind writing a new testing set but it will take a while and in the meantime if the plugin is not removed people will waste time on bugs that dont exist (as I have done for the last 4 hours)

**Comment by chmst** [comment]
Agree with removing the plugin and all the old images we keep for it in the image folder. 

Writing a new set of data is a huge work - I tried but gave up. If it is rewritten we should separate plugin and data (also for blog sample). Maybe this way: 
https://github.com/dgrammatiko/sloth-pkg/tree/main/plg_sampledata could be <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37663">issues.joomla.org/tracker/joomla-cms/37663</a>.</sub>
