### ISSUE TITLE
[4.1] cli database import fails

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37662]
### Steps to reproduce the issue
export the database using the following command

`php cli/joomla.php database:export --folder=tmp/`

the import the database with the following command

`php cli/joomla.php database:import --folder=tmp/`

### Expected result
Import completed

### Actual result
`[ERROR] Error merging the structure for xvchc_contentitem_tag_map: You have an error in your SQL syntax; check the     
         manual that corresponds to your MySQL server version for the right syntax to use near 'DEFAULT_GENERATED,      
         `type_id` mediumint NOT NULL, UNIQUE KEY `uc_ItemnameTagid` (' at line 1  `

**Comment by vorayash** [comment]
I was unable to reproduce this issue in my system. I got **[OK] Import completed in 153 seconds**.

**Comment by vorayash** [comment]
I was unable to reproduce issue. I got **[OK] Import completed in 141 seconds**.

**System information**
Windows 10
Joomla 4.1

**Comment by brianteeman** [comment]
It works on my mariadb server (10.5.13) but fails on my mysql server (8.0.19)

**Comment by richard67** [comment]
See https://github.com/joomla-framework/database/pull/253 .

**Comment by alikon** [comment]
please test https://github.com/joomla-framework/database/pull/253 .

**Comment by brianteeman** [comment]
Until there is a pull request to this repo I don't consider this even remotely resolved

**Comment by alikon** [comment]
up to you
I consider this issue closed as there is a PR, even if is it  in a upstream repo
i'll re-invite you to test it
