### ISSUE TITLE
Jommla 4.x + Php8.1 + Curly brackets for array indices

### ISSUE THREAD

**Issue by gopalji** [joomla/joomla-cms#37667]
I found 2 files that prevent joomla to start with Php 8.1 due to curley brackets as array index:

\libraries\vendor\typo3\phar-stream-wrapper\src\PharStreamWrapper.php, line 479
\libraries\src\Filesystem\Path.php line 145 ff

Please check

Joomla 4.1.2, Php 8.1

**Comment by toivo** [comment]
Please close this PR. There are no curly braces in arrays in these two files in Joomla 4.1.3-dev.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37667">issues.joomla.org/tracker/joomla-cms/37667</a>.</sub>
