### ISSUE TITLE
? in url for blog filter with tags

### ISSUE THREAD

**Issue by ch2856** [joomla/joomla-cms#37685]
### Steps to reproduce the issue

create a menu type article blog and use a tag as filter

### Expected result

Clean SEF URL with not "?"

### Actual result
xxx.com/aaa?filter_tag[0]=2

### System information (as much as possible)
j4.1.2
Apache php 8 MAMP server
.htaccess

**Comment by Quy** [comment]
Duplicate #36546. Thanks for reporting.
