### ISSUE TITLE
Pre Update Check gives no information

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#37687]
### Steps to reproduce the issue
Set Joomla Update to 'Joomla next' channel.
Save and close the options

### Expected result
Pre update check should appear

### Actual result
The Live Update tab shows

> Update unavailable

> An update to Joomla 4.1.2 was found, but it wasn't possible to download that update. There are three possibilities why this happens:
> - Your host doesn't support the minimum requirements for Joomla 4.1.2 and there is no alternative download for your configuration available.
> - The update to Joomla 4.1.2 is not available for your stability level.
> - There is a problem with the Joomla Update Server.

> Please try to download the update package from the official Joomla download page and use the Upload and Update tab. 

### System information (as much as possible)
Fails on Hosting server
php 8.0.18 
php 8.0.17 

Works as expected on localhost php 8.0.9

**Comment by brianteeman** [comment]
what version of joomla?

**Comment by Webdongle** [comment]
3.10.8
I did put that in on the side when I created the tracker on issues.joomla.org
But that field doesn't appear in the github tracker

**Comment by richard67** [comment]
Database type and version?

**Comment by Webdongle** [comment]
Fails database
10.1.48-MariaDB
5.5.60-0+deb7u1-log 
5.7.36-log

Works localhost database
5.7.31

**Comment by richard67** [comment]
MariaDB 10.1 and MySQL 5.7 should be ok. MySQL 5.5 is too old. See https://github.com/joomla/joomla-cms/blob/4.1-dev/installation/src/Helper/DatabaseHelper.php#L36

**Comment by Webdongle** [comment]
I suspect it is server related.  Two separate servers where I found the failure.  And one user in the Joomla forum.  So that is a total of 3 separate servers.  The user in the forum is database 10.0.38-MariaDB-cll-lve (Client:mysqlnd 8.0.17).  So we have 3 databases that should be ok.

The only thing in common (that I can see) is it fails on remote server.

**Comment by richard67** [comment]
> The user in the forum is database 10.0.38-MariaDB-cll-lve (Client:mysqlnd 8.0.17). So we have 3 databases that should be ok.

@Webdongle This is wrong. As my linked code clearly shows, MariaDB 10.0 is too old. Requirement is 10.1.

So in 2 of the cases, your MySQL 5.5 and that MariaDB 10.0, we know that the message is right because the databases are too old.

**Comment by extonjaez** [comment]
administrator/index.php?option=com_installer&view=updatesites

Put "Joomla! Core" to enabled

:D

**Comment by Webdongle** [comment]
@richard67 
Solved this.  Closing
