### ISSUE TITLE
[4.2] Help screens

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#37682]
### Steps to reproduce the issue

Using 4.2.0 Alpha select Help / Joomla Help to test new layout

### Expected result

A help screen

### Actual result

404 - RuntimeException

### Additional comments

This is sort of expected because the Help links all have keyref=Help42: 
All of the Help screens actually have namespace Help4.x and I wonder if it would be better to use that.
Otherwise the proxy needs a fix.

**Comment by brianteeman** [comment]
bump

**Comment by wilsonge** [comment]
I've added an alias for Help42 into the docs site

**Comment by brianteeman** [comment]
This is resolved now
