### ISSUE TITLE
[4.2] Plugin in Debug mode

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#37691]
### Steps to reproduce the issue

Set Debug System to Yes and Error Reporting to Maximum
Go to Home Dashboard / Plugins

### Expected result

A list of plugins

### Actual result

The list starts with a stack trace starting;

( ! ) Notice: Only variable references should be returned by reference in /Users/ceford/Sites/j420a3/libraries/src/MVC/Model/BaseDatabaseModel.php on line 418

### System information (as much as possible)

Newly downloaded 4.2.0 Alpha 3
Mac OSx / Apache / MySQL 5.6.34 / PHP 8.0.11

**Comment by brianteeman** [comment]
Confirmed

**Comment by chmst** [comment]
thiswas fixed in 4.1  https://github.com/joomla/joomla-cms/pull/37488

**Comment by richard67** [comment]
> Newly downloaded 4.2.0 Alpha 3

@ceford This cannot be since the latest release was 4.2.0 Alpha 2. Maybe you mean a current 4.2 nightly build, which has version 4.2.0-alpha3-dev? (Mind the "-dev", it always shows the next version as version number with that "-dev" when using a nightly build or being on the current git branch.)

**Comment by ceford** [comment]
I came across this problem when doing something else so thought I should get the latest version to check. My system info says this the version for which I reported the bug:
Joomla! 4.2.0-alpha3-dev Development [ Uaminifu ] 26-April-2022 16:49 GMT
I admit I have so many local installs I get confused!

**Comment by richard67** [comment]
So it's like I said, it's a nightly build with version "4.2.0-alpha3-dev".

**Comment by richard67** [comment]
@ceford Could you check if PR #37661 solves this issue? I think it should. It has been merged 1 hour ago so tomorrow it will be in the nightly build. If it fixes your issue here, please close it. Thanks in advance.

**Comment by richard67** [comment]
> thiswas fixed in 4.1 #37488

@chmst I don't think so. But I think it has been fixed with #37661 .

**Comment by ceford** [comment]
Just updated to last night's build and I no longer see the error message.
