### ISSUE TITLE
[4.x] com_media crashes if directory exists with image ending

### ISSUE THREAD

**Issue by dawe78** [joomla/joomla-cms#37692]
### Steps to reproduce the issue
Backend: go to content -> media, create new directory >test.png< (which makes no sense, but a customer of me did and caused the error)

### Expected result
- show message "can't create directory"
- directory was not created
- com_media keeps working

### Actual result
- message is shown
- directory was created
- com_media shows no content any more; on some systems message "image not found" appears, but not for all systems (dont know why the behaviour is different for same release number systems)

### System information (as much as possible)
Joomla 4.1.2 (current stable)
PHP 7.4

### Additional comments
maybe a solution could be to check if current string is a directory or file; currently com_media treats directorys as file if name syntax matches to file name syntax and tries to get fileinfo for directory, thats why com_media crashes. before getting fileinfo, com_media should check if current string is file or not.

**Comment by chmst** [comment]
Confirmed online PHP 8.0 
![grafik](https://user-images.githubusercontent.com/1035262/166136711-a83b6773-7914-4886-b758-eecfde6bd76c.png)

On my localhost win11, php 8.1 I see that directories are gernerated for example xx.png, test.jpg.

**Comment by ReLater** [comment]
> Expected result
> show message "can't create directory"
> directory was not created

I think it should be created. Why not?

Of course, as long as
> com_media keeps working

**Comment by chmst** [comment]
Directories  are created for example xx.png, test.jpg. 
These directories are only visible in my local installation (I am on win11), not online (via ftp).

As long as these directories exist, no directory tree is displayed  - see screenshot

**Comment by dawe78** [comment]
ReLater I agree; what I meant was the directory has been created although the message said it was not - what possibly is a bug. But youre right, there is no reason NOT to create a directory like this, so this message has to be removed.

**Comment by Quy** [comment]
Closing per #42874.
