### ISSUE TITLE
Wrong position of the ReCaptcha in the registration form

### ISSUE THREAD

**Issue by benyrfg** [joomla/joomla-cms#37698]
### Steps to reproduce the issue

If ReCaptcha is enabled in the registration form and custom fields are used at the same time, ReCaptcha is placed before custom fields. It doesn't make sense, the ReCaptcha should be placed before the submit button.

The same if "User - profie" fields are enabled.

### Expected result

The ReCaptcha should be placed before the submit button.

### Actual result

The ReCaptcha is placed before custom field, in the midddle of the form.

### System information (as much as possible)

J4.1.2

### Additional comments

https://prnt.sc/GEEz_YbI8c9O

![screen shot 2022-04-29 at 21 59 26](https://issues.joomla.org/uploads/1/6ac4f3a3bfb6d0a54955d1e11d4e9462.png)

**Comment by Vanshitasingh** [comment]
Can you explain in detail how to reproduce this issue?

**Comment by chmst** [comment]
@Vanshitasingh you could read the docs to understand. 

An administrator can allow user registration, then users can register. 
https://docs.joomla.org/Allowing_user_registration

He(she) can activate Google ReCaptcha - this is injected by a plugin after the registration form
https://docs.joomla.org/J3.x:Google_ReCaptcha

In this form, the user adds some custom fields. 

So you would need to enable user registration, get a google re-captcha and add a  custom field in the  the registration form.

**Comment by alikon** [comment]
please test #37705
