### ISSUE TITLE
Focusborder cut in modal window for media upload

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#37706]
### Steps to reproduce the issue
Go to media, set the focus on upload.

### Expected result
The focus boderer is visible

### Actual result
![grafik](https://user-images.githubusercontent.com/1035262/166136609-027144a9-d7ea-4724-9f5b-b0f37fcaa984.png)

**Comment by brianteeman** [comment]
It needs a margin on the body element inside the iframe

**Comment by coolcat-creations** [comment]
I just installed the 4.1.3 dev and can't reproduce: 
<img width="521" alt="grafik" src="https://user-images.githubusercontent.com/828371/166140036-77737534-6161-4624-a4f9-573d16b25f61.png">

**Comment by coolcat-creations** [comment]
I just installed 4.1.3 dev and can't reproduce: 
<img width="578" alt="grafik" src="https://user-images.githubusercontent.com/828371/166140074-42f40afc-4bb2-412c-adf9-0e14b393e0e1.png">
Which Browser are you using?
@chmst your font looks different is there any extension interfering with the template?

**Comment by brianteeman** [comment]
chrome windows
![image](https://user-images.githubusercontent.com/1296369/166140462-d7635548-a206-4ccf-9a44-480f5affae96.png)

firefox windows
![image](https://user-images.githubusercontent.com/1296369/166140544-1a7345c4-3164-4ded-9d86-30a4e1dae833.png)

**Comment by brianteeman** [comment]
this is in the front end

**Comment by chmst** [comment]
sorry, yes, I forgot to mention the frontend.

**Comment by coolcat-creations** [comment]
Please test https://github.com/joomla/joomla-cms/pull/37707
