### ISSUE TITLE
Weblinks "Description" field inaccessible via Front-End.

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#37718]
### Steps to reproduce the issue
When performing a "Submit Weblink" via the Front-End by a Registered User, the "Description" field cannot be accessed by the mouse cursor to enter any text.

### Expected result
The field should accept the cursor to allow the entry of text.

**Comment by Quy** [comment]
Please post Weblink issues to https://github.com/joomla-extensions/weblinks. Stop posting here. Thank you for your cooperation/understanding.
