### ISSUE TITLE
Language Use Inconsistency in "Weblinks"

### ISSUE THREAD

**Issue by 200MPHMEDIA** [joomla/joomla-cms#37717]
### Steps to reproduce the issue
Within the "Weblinks" Component Extension, there is much inconsistency with the actual term of "weblinks."
The term "weblinks" and "Web Links" are used frequently and illogically.
Please review and change all the use of the word to "weblinks" as one word vs. two words.

### Expected result
Would prefer seeing the term consistently user as "weblinks" [one word only].

**Comment by Quy** [comment]
Please post to https://github.com/joomla-extensions/weblinks.
