### ISSUE TITLE
Pagination links for tags are wrong

### ISSUE THREAD

**Issue by ch2856** [joomla/joomla-cms#37727]
### Steps to reproduce the issue
display a single tag items (com_tags)  with pagination. 
SEF + Use URL rewriting 

### Expected result
next page link should be
/component/tags/tag/tag-name?start=15

### Actual result
/component/tags/tag-name?Itemid=104&start=15 

leads to 404 page. 

### System information (as much as possible)
J4.1.2

**Comment by Quy** [comment]
Duplicate #35382?

**Comment by richard67** [comment]
@ch2856 If this issue here is a duplicate to #35382 then please close it. Besides this, it's not really sufficient to answer a question just with a thumbs up of which nobody is notified. A comment answering the question would be better.

**Comment by chmst** [comment]
Thanks for opening an issue @ch2856, it is a bug and hopefully someone will make a PR. 
As it is a duplicate I close here.
