### ISSUE TITLE
[4.1] Editor custom field height setting doesn't work correctly with TinyMCE

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#37723]
### Steps to reproduce the issue
Create an article custom field of type editor
Change the height to 150px (the default is 250px)

### Expected result
Both the editor pane and code pane to be 150px

### Actual result
The editor pane doesn't change but the code pane does

### System information (as much as possible)
J4.1.2

### Additional comments
It works correctly using JCE Editor

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37603 . Thanks in advance.
