### ISSUE TITLE
J4.x components installing fine, but fail to work properly

### ISSUE THREAD

**Issue by stephan-ansems** [joomla/joomla-cms#37728]
According to the documentation (read it [here](https://docs.joomla.org/Manifest_files)) the manifest file of a component must be named  `manifest.xml `or `<extension_name>.xml`.

However if you use the name `manifest.xml` the component will install properly, but fail to work. Probably you'll get errors lile 'Class ... not found' or 'Layout default not found'. It took me ages to figure out if i made some typo somewhere, but it turns out that the manual and documentation is wrong:

The following line in the code expects the manifext to be called `<extension_name>.xml` and that you component declares it namespace tag in the manifest, otherwise it will not generate an entry in the namespace map and you'll end up wasting time.

https://github.com/joomla/joomla-cms/blob/a94decccac55949997c6fd0227b26abfc5457fec/libraries/namespacemap.php#L215

Either update the doc, or add a line for `manifest.xml` to the code.

**Comment by chmst** [comment]
Sorry but this is not the right place  for your problem. Please ask here https://joomla.stackexchange.com/ or in forum.joomla.org.

**Comment by stephan-ansems** [comment]
It is not a support request, it is a bug in the code or the documentation.
