### ISSUE TITLE
[4.1.2] Post-installation Message COM_ADMIN_POSTINSTALL_MSG_FLOC_BLOCKER_TITLE

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#37736]
### Steps to reproduce the issue
Open administrator/index.php?option=com_postinstall
The Page shows a Message showing Language Constant:

<img width="1185" alt="pim" src="https://user-images.githubusercontent.com/89642616/166623972-35ba576f-4e12-47b6-9822-b0a6c16912ef.png">

### Expected result
Message shows the Language Values or the Message isn't shown.

### Actual result
Message shows the Language Constants.

### System information (as much as possible)
![image](https://user-images.githubusercontent.com/89642616/166624129-d2467874-4760-4aa9-a65a-a8cbbb17e384.png)

**Comment by brianteeman** [comment]
Was this a clean installation or was this an upgrade

**Comment by ghost** [comment]
All Updates are manually by uploading the update packages 4.0 > 4.1 > 4.1.2.

**Comment by brianteeman** [comment]
from this page?

![image](https://user-images.githubusercontent.com/1296369/166639579-6d3b109f-d0df-4f6e-958e-1af502fbce69.png)

**Comment by ghost** [comment]
Yes, from this page.

**Comment by brianteeman** [comment]
ok good. that was just to check as some users have just extracted the zip and that is not an update.

**Comment by ghost** [comment]
I was unable to update automatically at cloudaccess (saying theres a bad database, but there is nothing to fix) so i do the manually way.

**Comment by brianteeman** [comment]
This is a known error at cloudaccess and its probably why the update did not complete correctly.

Tagging @cloudaccess-net

**Comment by ghost** [comment]
Thanks @brianteeman for your time. Closing as no core issue.
