### ISSUE TITLE
can not change group name Public

### ISSUE THREAD

**Issue by zmax99** [joomla/joomla-cms#37737]
### Steps to reproduce the issue
1,joomla version 4.1.2

I want to change "Public" to a new name,but can not save success.
Invalid field: Group Parent
![screen shot 2022-05-04 at 09 03 43](https://issues.joomla.org/uploads/1/c1c02dd741a47d1596f2d55e14244149.png)

### Actual result
Invalid field: Group Parent

### System information (as much as possible)
Invalid field: Group Parent

**Comment by brianteeman** [comment]
Duplicate report of #36322

**Comment by chmst** [comment]
Closing, Duplicate
