### ISSUE TITLE
[4.1.3-rc1] Quickicons category count error

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#37735]
### Steps to reproduce the issue
Edit module quickicons. 
Set button categories to "show with count" 

### Expected result
The number of categories is visible on dashboard

### Actual result
![grafik](https://user-images.githubusercontent.com/1035262/166521940-18a6c643-fdd7-41fc-b02f-e917817d181b.png)

### Additional comments
Could be afrom older versions of J4

**Comment by paternax** [comment]
I can't reproduce this (J. 4.1.2 / PHP 8.0.6) - the categories count is correct

**Comment by brianteeman** [comment]
i cant reproduce on 4.12 or 4.1dev

**Comment by chmst** [comment]
Additional info: 
![grafik](https://user-images.githubusercontent.com/1035262/166562147-012b42a8-374c-4646-aa25-5ab22f386978.png)

Maybe a php 8.1 problem?
<b>Deprecated</b>:  explode(): Passing null to parameter #2 ($string) of type string is deprecated in <b>D:\xampp\htdocs\joomla-rc\administrator\components\com_categories\src\Dispatcher\Dispatcher.php</b> on line <b>33</b><br />
{"success":true,"message":null,"messages":null,"data":{"amount":5,"sronly":"Categories: 5 article categories are published.","name":"Article Categories"}}

**Comment by brianteeman** [comment]
maybe. i am not on 8.1

**Comment by chmst** [comment]
In another Application on 8.0 the count is correct. I set the label for php 8.1.

**Comment by brianteeman** [comment]
I just retested by changing my php version to 8.1 and I still cannot replicate the error

**Comment by chmst** [comment]
Closing with Pull request https://github.com/joomla/joomla-cms/pull/37738.
