### ISSUE TITLE
J4.x components installing fine, but fail to work properly

### ISSUE THREAD

**Issue by stephan-ansems** [joomla/joomla-cms#37750]
### Steps to reproduce the issue
1. Create (or reuse) a component that has an admin page.
2. Make sure the manifest file is named `manifest.xml` instead of `<extension_name>.xml`. According to the documentation (read it [here](https://docs.joomla.org/Manifest_files)) the manifest file of a component can be named  `manifest.xml `or `<extension_name>.xml`.
3. Create the zipfile for the component so it can be uploaded.
4. Install it in a fresh Joomla server version 4.1.2. 
5. Try and access an admin page of your component.

### Expected result
- The admin page of the component

### Actual result
- You'll see an error page. Even though the component installed properl, the admin page will fail to work. You'll probably see an error like 'Class ... not found' or 'Layout default not found'.

### System information (as much as possible)
- Clean install of the Joomla 4.1.2 

### Additional comments
The following line in the code expects the manifext to be called `<extension_name>.xml` and that you component declares it namespace tag in the manifest, otherwise it will not generate an entry in the namespace map and you'll end up wasting time.
https://github.com/joomla/joomla-cms/blob/a94decccac55949997c6fd0227b26abfc5457fec/libraries/namespacemap.php#L215
Either update the doc, or add a line for `manifest.xml` to the code.

@chmst Please don't treat this as a support request like last time. I think its a bug.

**Comment by roland-d** [comment]
@stephan-ansems Thank you for your findings.

> Either update the doc, or add a line for manifest.xml to the code.

I agree the docs should follow the code. As anybody can update the docs because it is a wiki, feel free to update the docs. We are all volunteers and try to help where we can.

**Comment by ReLater** [comment]
Mentioned change in docs: See https://docs.joomla.org/Manifest_files and https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#Namespace_mapping_and_manifest_file_name

**Comment by roland-d** [comment]
As the change has been documented now, I will close this issue.
