### ISSUE TITLE
Drop ES5 javascript files

### ISSUE THREAD

**Issue by dgrammatiko** [joomla/joomla-cms#37755]
[<img width="1603" alt="Screenshot 2022-05-06 at 14 23 21" src="https://user-images.githubusercontent.com/3889375/167132485-3bd0a281-9646-49db-ad5f-22fa7a64ac62.png">](https://www.microsoft.com/en-us/download/internet-explorer.aspx)

### Problem identified
Joomla 4 emits/creates ES5 javascript next to the current ES2018 ones. That was done because Internet Explorer was still _alive_ but in few weeks it will be officially dead. Most of the tools also will adjust to this change, specifically `autoprefixer` and `preset-env` will move that browser to the dead ones. Thus the project has 2 options:
- adjust the scripts to keep creating the ES5 files (which are already broken, missing essential polyfills, etc, basically they are useless)
- or adjust the build tools to stop creating the ES5 files

### Proposed solution
The proposal is to (obviously) drop the dead, unusable, ES5 files. The process needs some adjustments for the build tools and also adjusting the `joomla.assets.json` files.

### Open questions

PS: If there's a decision to drop them I'll put the work to make it happen but time is critical here and this should be in the 4.2 early enough to have as much testing as possible

Context: 
- https://github.com/joomla/joomla-cms/pull/35739
- https://github.com/joomla/joomla-cms/discussions/35737
- https://github.com/joomla/joomla-cms/discussions/32148

**Comment by pl71** [comment]
and... es5 files are still here.
<script src="/media/com_finder/js/finder-es5.min.js<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37755">issues.joomla.org/tracker/joomla-cms/37755</a>.</sub>
