### ISSUE TITLE
Cassiopeia logo svg image usage

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#37756]
In order to always have a clean logo on all screens I try to use an SVG image. But unfortunately the Cassiopeia template does not work with this format with Joomla 4.
Or I'm wrong ?
Can we modify this?
Do you have a tip, maybe a detail escapes me?
Or simply should I use another format and if so which one in which size to have an optimal display for smartphone, HD screen and 4k?
Thanks for your help.

**Comment by brianteeman** [comment]
> But unfortunately the Cassiopeia template does not work with this format with Joomla 4.

That is a very unclear statement. What doesn't work? It doesnt get uploaded? It doesnt display? What?

**Comment by Magnytu2** [comment]
Both my captain. Even following your video. Import does not work. But I got around the problem by using Filezilla. https://youtu.be/U7hHYpuNqsg
For displaying the image, it works in the backend of the cassiopeia template, but not in the frontend.
http://magnytudeweb.com/aplf-flexi/

<img width="1526" alt="Capture d’écran 2022-05-07 à 10 26 12" src="https://user-images.githubusercontent.com/26197929/167246781-49d03d9a-0b81-4957-a9ac-d5a71a505fc8.png">

**Comment by brianteeman** [comment]
No problem here

![image](https://user-images.githubusercontent.com/1296369/167247195-09c8cdad-9c93-44a7-881c-f9e6dc340a2b.png)

![image](https://user-images.githubusercontent.com/1296369/167247206-91294e71-358c-4108-8557-1b27a80251f4.png)

**Comment by Magnytu2** [comment]
Oh well then... Is it with the Cassiopeia template from Joomla 4?

**Comment by Magnytu2** [comment]
Alright, I don't understand it anymore. I just did a test using an image from the site: https://2.flexiple.com/scale/home
And there it works but the image is huge.
So I imagine that my image in svg is badly encoded. Do you have any rules to follow? Where can I find information to respect the format, the dimension?
<img width="886" alt="Capture d’écran 2022-05-07 à 11 59 54" src="https://user-images.githubusercontent.com/26197929/167249580-373eabd4-a474-4cda-b943-0759e4c821e2.png">

**Comment by brianteeman** [comment]
Yes my screenshot was cassiopeia just with some css that made it look different.

**Comment by chmst** [comment]
I hope you can display now your svg, @Magnytu2. I close this as it is not an issue of the joomla core.

**Comment by Magnytu2** [comment]
No, I can't build a correct SVG image from illustrator. But yes you can close my post. There is still a problem with the svg image transfer in the media manager. Thanks a lot you two.

**Comment by chmst** [comment]
Thank you and good luck :) Yes, the upload issue is known and devs are working on it.

**Comment by thanviuyw** [comment]
The primary justification for its adoption is this. Telugu [hiidude](https://www.digitaltechupdates.com/hiidude/ "hiidude") films The user is presented with copyrighted material on the net archive plagiarism website. However, a lot of fresh people frequently visit the website. Hiidude borrows admirably from other websites; it is simple, straightforward, and mobile-friendly. The newest Hindi, Telugu, English, and suitably unique Punjabi films are free on the Filmi Meet website<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37756">issues.joomla.org/tracker/joomla-cms/37756</a>.</sub>

**Comment by asma5377** [comment]
American Express, MasterCard, and Visa have prepaid card options that allow consumers to cash in funds from an online casino portfolio; however, fees will vary between vendors. International online casinos that accept Visa credit cards and debit cards also accept Visa gift cards. Thus, online players should be OK with using their prepaid cards as deposit methods on international gaming sites. Since many prepaid cards are
[Good Casino Deposit Methods](https://casinobloggers.com/are-prepaid-cards-a-good-casino-deposit-methods/ "Good Casino Deposit Methods")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37756">issues.joomla.org/tracker/joomla-cms/37756</a>.</sub>
