### ISSUE TITLE
[4.1] Broken joomla-translations-bot

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#37759]
@HLeithner @bembelimen as mentiond here: https://github.com/joomla/joomla-cms/pull/37344#issuecomment-1075038461

We have to manually fix the joomla-translation-bot after merging any changes to workflow files as it currently fails with this error message:

![image](https://user-images.githubusercontent.com/2596554/167264976-89577a72-224a-4b5c-8c51-e44c70143a51.png)

**Comment by zero-24** [comment]
Looks like the bot has been fixed thanks @HLeithner : https://github.com/joomla/joomla-cms/pull/37770

**Comment by HLeithner** [comment]
Yes I fixed it by manually updated the branch.
