### ISSUE TITLE
[4.2] - Mails sent with Mail Templates are not replacing variables in the mail body

### ISSUE THREAD

**Issue by aftertaf** [joomla/joomla-cms#37769]
### Steps to reproduce the issue
Install 4.2.0 alpha3-dev
Create a new user (or complete any action that will generate a system e-mail being sent)

### Expected result
Email sent with variables replaced with actual data (username created, siteurl, etc)

### Actual result
%s in place of each variable in the mail body
(see attachment)
![screen shot 2022-05-09 at 20 29 57](https://issues.joomla.org/uploads/1/e5082d1cf5d660e403e2e6d9369b23a4.png)

### System information (as much as possible)
php 8.1.5

### Additional comments
Site set to French as default. but French language is at version 4.1, whereas English is at 4.2. Dont know if relevant...
j4.2-alpha3-dev (was running j4.0, then j4.1, each updated when publicly released as stable, now on 4.2 to test).

**Comment by chmst** [comment]
Seems to be an issue with language, not joomla core

**Comment by brianteeman** [comment]
This can be closed as I can see that the french language pack no longer uses the incorrect %s
