### ISSUE TITLE
[4.x] User Logout direct fails

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37763]
### Steps to reproduce the issue
1. Create a menu item with GUEST permissions
2. Create a menu item with REGISTERED permissions
3. Create a menu item with Public permissions
4. Publish the login module on all pages AND set redirect on login to the registered page and redirect on logout to the guest page
5. Create a menu item Users->Login Form  AND set redirect on login to the registered page and redirect on logout to the guest page
6. Create a menu item Users->Logout AND set redirect on logout to the public page
7. Create a menu item Users->Logout AND set redirect on logout to the guest page

### Test 1
login and logout using the module 

### Test 2
login and logout using the menu login form

### Test 3
Login (any method) and Logout using the Logout menu item that redirects to a public page

### Test 4
Login (any method) and Logout using the Logout menu item that redirects to a guest page

### Expected Results
login and logout and redirects all work as expected

### Actual Result
Test 1,2 & 3 work as expected
Test 4 produces a 403 You don't have permission to access this

**Comment by sozzled** [comment]
Thanks, @brianteeman.  I reported this at #37042 but it failed to gain any traction or attention.  I consider this a bug with J! 4 that probably goes back to before the release of J! 4.0 but was overlooked or not considered important.   Whether or not the matter is fixed I would like an acknowledgement from the development team(s) as to why this happens:

The logout **_menu item_** does not close the session (and reset the viewing permissions) before the session is redirected to a menu item that the session is not permitted to access.  That, in a nutshell, is the problem.

Further, the viewer remains logged-in as a result of the error.

**Comment by brianteeman** [comment]
> I reported this at https://github.com/joomla/joomla-cms/issues/37042 but it failed to gain any traction or attention.

Probably because you didnt have good test instructions and asked people to wade through the forum.

>  I consider this a bug with J! 4 that probably goes back to before the release of J! 4.0 but was overlooked or not considered important

Doesnt really matter what you consider or when the bug first occurred. The only thing that matters is when someone discovers and reports it.,

>  I would like an acknowledgement from the development team(s) as to why this happens:

I would like a ferrari

**Comment by brianteeman** [comment]
Closing as no longer reproducable
