### ISSUE TITLE
BreadcrumbList: Google found structured data with syntax errors 

### ISSUE THREAD

**Issue by Gratia-Mira** [joomla/joomla-cms#37766]
### Steps to reproduce the issue

Go to an article page in Joomla 4.1.2 and test the printed data of the module. Test the data with https://search.google.com/test/rich-results

### Expected result

The expectation would be that it has no faults.

### Actual result

At the moment - at least for me - the link of the current page is not output as a structured page.

### System information (as much as possible)

Joomla 4.1.2
Linux Server

### Additional comments

Perhaps it is a consequential error. The fact is simply that the function "Uri::getInstance()" outputs an empty string. That's why I replaced the following line as a workaround.

old: '@id'  => $item->link ? Route::_($item->link, true, Route::TLS_IGNORE, true) : Route::_(Uri::getInstance())
new: '@id'  => $item->link ? Route::_($item->link, true, Route::TLS_IGNORE, true) : Route::_($_SERVER['REQUEST_URI']),

Now it works correctly again. I wanted to share this hint simply because I am not sure if this might be a bug. Thank you for your work!

**Comment by alikon** [comment]
can you check if this #37679 solve the issue please?

**Comment by drmenzelit** [comment]
Probably duplicated from #37510 and #37508

**Comment by Gratia-Mira** [comment]
Yes, it is the same issue.
Yes, this solution also works! But in that case, I guess I'll stick with my solution for my template because it's both simple and provides a link for the last object.
Thanks for the answers!
