### ISSUE TITLE
[4.x] Incomplete extension changelog

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#37774]
### Steps to reproduce the issue
When an extension has e.g. three versions A, B, C, install version A
In the extension updater it will show installed extension A and updated version available C
When clicking on the [Changelog] button, only the changelog for C is shown

### Expected result
Changelogs should show all changes between installed version and to be installed version.
The changelog should show changelog for version B AND C

### Actual result
Only changelog for version C is shown leading to possible issues as important information that you base your upgrade strategy on is not available.

### System information (as much as possible)
Joomla 4.1.3

### Additional comments
-

**Comment by brianteeman** [comment]
None of the extensions that I have use the changelog functionality. Could you point to an extension that does please.

**Comment by Ruud68** [comment]
All extension that are offered via ochSubscriptions have changelog functionality support.
I can provide two versions of a plugin to test with if needed

**Comment by Ruud68** [comment]
Here you see the versions installed and updates available:
![image](https://user-images.githubusercontent.com/2733197/168006997-0cfa5c73-9631-4c4b-a954-58f9d56aadb8.png)

as an example ochFitvids installed is 2.2.0 (A) there is a 2.3.0 version available but not installed (B) and the update prompts for version 3.0.0 (C).
The changelog is only shown for 3.0.0 and not also for 2.3.0 (in which important notices / changes / etc. could be present)
![image](https://user-images.githubusercontent.com/2733197/168007369-15d18e8e-719a-4d39-943a-85ae7be65860.png)

and the contents of the provided xml that does have all the information (so also for version 2.3.0)
![image](https://user-images.githubusercontent.com/2733197/168007441-3eb6a7cd-edcb-4d00-a514-60f2b0b6a079.png)

**Comment by ReLater** [comment]
I am against an amendment like the one proposed here.

You show a short changelog but imagine please the displayed changelogs for extensions that "have more to say" than just 2 phrases. I simply add a link to my current changelog list "See all changelogs" that opens an external page with all changelogs.

**Comment by Ruud68** [comment]
@ReLater IMO that is still possible, you can still add a link that users can click and that will redirect to your site.
Changelogs are part of a decision making process: what does it add? what does that mean for me in terms of: can I install that, should I test? If I should test: what has changed so that I know how to focus my tests?

Without a complete changelog, this functionality is window dressing and in that case it would be better to completely remove this changelog functionality and replace it with a button to the changelog page of the developer.

Incomplete information will lead to incorrect decision making.

**Comment by brianteeman** [comment]
By definition a changelog is a record of the changes in this verssion. The code is working correctly and as intended

**Comment by Ruud68** [comment]
> correct and working as 'intended'...

that is what I tell my customers but still they say crucial info for their decision making process is missing. So better to not provide changelogs via Joomla but as @ReLater does only fill them with a link to the full changelog on my site.

**Comment by brianteeman** [comment]
That would be a business decision for you

**Comment by Ruud68** [comment]
> That would be a business decision for you

true, maybe also the reason why you haven't seen any usage on extensions for this Joomla feature yet. It could have add more value for users and developers. now it only adds (potential) confusion to users that do not install every update available but e.g. are following a period based update schedule.

**Comment by brianteeman** [comment]
Then that user needs to be educated better as they are potentially leabing themselves open to vulnerabilities.

> The code is working correctly and as intended

**Comment by n3t** [comment]
Agree completely with @Ruud68. Changelog should show list of changes since installed version, or it is IMO useless function in Joomla, bringing just confusion to administrators. I just decided to add changelog to my extensions, which seemed to me great idea, after finding this functionality I will not add it. @brianteeman - maybe this is the reason, why none extensions you use have changelog implemented.

Just imageine if you have for example installed version 3.9, then there is 4.0.0 with lot of changes (major version change), and short after there is 4.0.1 with one minor change which was discovered after releasing 4.0.0. Administrators will see just one minor change, so can easily overlook Major version change, and think they can install without any issues easily.

And IMO changelog is by definition list of changes, the addition "in this version" is not general valid. Seems to me very logical to have listed changes since my installed version, so I can see (as user or admin) what everything will change, if I install new version.

@ReLater - if changelog is shown for multiple versions at once, still you can have for every version just 2 sentences with link to all changes, I don't think proposed change will break this... Of course it's not in purpose to show all changes history, just changes between currently installed version and proposed update.

**Comment by n3t** [comment]
Ok, what about to leave the decision on changelog author? There could be attribute on the changelogs element, something like showcomplete="true" and based on this value complete changelog will be displayed. 

This is backwards compatible, as missing attribute would mean false, so only last change will be displayed. 

Is something like this acceptable?

**Comment by Ruud68** [comment]
@n3t what I think (and for what it is worth) is A. nobody of the 'community' is having this issue (so there will be no attention for this issue other then Brian responding), B. thinking from the assumption that all sites and extensions are always up to date C. making the conclusion that if B. is not true then it is the website maintainer his problem.

So either accept this is not going to happen and solve the issue on your side, or continue the 'monologue' here :) or do a PR for the change (with a high risk of that being ignored: been there, done that).

I think this is a relative small change as we on the server side have all versions changelogs in the xml, know what the installed version is and what the new version is. so instead of reading and displaying one changelog it is a foreach with a heading. It could even be the same (layout) it is now but then with an added [show more] button for the additional changes implemented by the update.

**Comment by peteruoi** [comment]
Sorry for interfering.
I believe a new tag is needed here. (e.g. **nicetohave**)
We have an issue here that it sounds logical. It complements or corrects an established behaviour. THere are comments here that do not oppose the logic of the proposed "correction" but explain how themselves work around it (or with it). That doesn 't mean that the proposed "complete" extension changelog is wrong for joomla. So, as long as, it's fully backwards compatible and not another switch is introduced in the interface i cannot see the reason why a release lead would not accept it. 
On the other hand, i understand someone that is gonna spend time on it would like to know if the release lead would accept it or not if all the requirements are met. 
It's something that doesn't concern the archtecture, or it doesn 't change the route of the project so i believe the RLDQ  tag is too much for this. But anyone from the production team could add this tag. If you 'd like some thumbs up to the first post from anyone could be required to grant this tag. 
I know that there is lot of work elsewhere and more important features and issues but if someone wants to work on this why lose him?
pinging @richard67 as a very friendly fellow if he wants to comment on this.

**Comment by brianteeman** [comment]
> I know that there is lot of work elsewhere and more important features and issues but if someone wants to work on this why lose him?

nothing is stopping anyone from working on this if it scratches their itch

**Comment by n3t** [comment]
> On the other hand, i understand someone that is gonna spend time on it would like to know if the release lead would accept it or not if all the requirements are met.

Exactly

> nothing is stopping anyone from working on this if it scratches their itch

Nothing but statements like 'The code is working correctly and as intended' or 'That would be a business decision for you' from core team member...

> So either accept this is not going to happen and solve the issue on your side, or continue the 'monologue' here :) or do a PR for the change (with a high risk of that being ignored: been there, done that).

...which often results in something like this, killing the will to try to contribute at all :(

**Comment by Fedik** [comment]
The Changelog designed to show changes for specific version.
Currently there no code to display a whole log. Anyone are welcome to code it.

It not a bug, but feature request.
