### ISSUE TITLE
User groups acess issue

### ISSUE THREAD

**Issue by Borgas** [joomla/joomla-cms#37776]
### Steps to reproduce the issue

Create user group (parent of public)
Create user level 
Assign user group to new user level and Special (added both)

tutorial followed for this steps was [this tutorial](https://magazine.joomla.org/all-issues/january-2022/joomla-4-for-clients-managing-users-access)

### Expected result
I have no idea. Just exploring this user group thing

### Actual result
User assigned to this user group can not edit is own "user groups" but is allowed to edit the groups of other users.

He cannot become a super user, but he can go to another user and assign him as super user.

### System information (as much as possible)
Joomla version - Lastest version, fresh install 4.1.3 with no extra installs, just the core version
PHP 7.4.29
MySQLi 5.7.38
Colocar em cache Disabled
Gzip Disabled

**Comment by chmst** [comment]
Parent of public is not possible. You mean public is the parent of your user group? 
I think that you have allowed too much in configuration permissions. Could you please post a screenshot of the permissions?

**Comment by Borgas** [comment]
> Parent of public is not possible. You mean public is the parent of your user group? I think that you have allowed too much in configuration permissions. Could you please post a screenshot of the permissions?

![1](https://user-images.githubusercontent.com/54105234/167834959-3225c7f2-ff61-48b4-8c51-d3b3fe35805b.PNG)
![2](https://user-images.githubusercontent.com/54105234/167834961-49903637-e547-42da-b222-32191c4505f7.PNG)

This user, if goes to back-end, he cannot change his users permissions, but can access to another user, and modify that user permission
![3](https://user-images.githubusercontent.com/54105234/167835080-7383e829-34a6-4a19-a3a3-15848cc3a7e5.PNG)

**Comment by chmst** [comment]
Which permissions do you see here 

![grafik](https://user-images.githubusercontent.com/1035262/167836785-30786b43-b17a-42aa-b103-de23795f364a.png)

and in user permissions?  

![grafik](https://user-images.githubusercontent.com/1035262/167836973-bd11af89-a790-4feb-ba97-067ee4311606.png)

**Comment by Borgas** [comment]
![4](https://user-images.githubusercontent.com/54105234/167842153-6e385d11-e4cd-48e8-8e5f-5abb498e6698.PNG)
![5](https://user-images.githubusercontent.com/54105234/167842156-58ef0ddb-aa8c-40b7-865b-b69808967ca5.PNG)

**Comment by chmst** [comment]
Your user seems to have permission for editing everything. He is also in a group Socios, this makes a big difference if this group has more permissions.

**Comment by Borgas** [comment]
> Your user seems to have permission for editing everything. He is also in a group Socios, this makes a big difference if this group has more permissions.

Thank you for, reply, but removed from all other groups, and levels (i have removed from special and configure everything to have access [toolbar, menus etc]

News prints of configuration, and seems strange this options
![1](https://user-images.githubusercontent.com/54105234/168063926-6baba620-5d85-4bfa-b3ee-b385d9ba6315.PNG)
![2](https://user-images.githubusercontent.com/54105234/168063931-78b33de4-fca5-462d-ba5e-957477a16255.PNG)
![3](https://user-images.githubusercontent.com/54105234/168063935-f537c29d-0484-4429-bb87-c39486563df6.PNG)
![4](https://user-images.githubusercontent.com/54105234/168063937-25c3b911-9b68-4cc5-90b4-91a8ed9096fe.PNG)

In his profile, he cannot manage his level
![5](https://user-images.githubusercontent.com/54105234/168063939-fae053fc-ef26-42d3-8f93-5ccfde615cdd.PNG)

In another user, he can give any level
![6](https://user-images.githubusercontent.com/54105234/168063943-e4d246da-d643-4c80-9a30-2bbe12efe0cb.PNG)

**Comment by drmenzelit** [comment]
The user "Marco Ascensao" belongs to different groups, that can make trouble if the permissions are different in each group

**Comment by Borgas** [comment]
> The user "Marco Ascensao" belongs to different groups, that can make trouble if the permissions are different in each group

Hi, thank you for reply.

Even in a user "registered" the user as acess to all levels

Teste - User with privileges  and is going to visit ->Teste1

![1](https://user-images.githubusercontent.com/54105234/168180410-08a7a5e0-51cd-4e1d-85a8-2c5af33ca014.JPG)

Result page
![2](https://user-images.githubusercontent.com/54105234/168180251-95192dbe-3973-420a-b679-f0bb3506ef4a.JPG)

I dont know if this was suppose to happen, i don´t play Joomla since 1.7 version
I´m just digging to find a way for a user with privileges be able to upgrade a registered user to another level, but not admin.
Like a registered user and a paywall

![3](https://user-images.githubusercontent.com/54105234/168180782-6b8d73b9-91ba-44f2-951d-d1271a99db4b.JPG)

**Comment by drmenzelit** [comment]
Normally a user in Registered group has no access to the backend. Something is wrong with your settings.

**Comment by chmst** [comment]
@Borgas I suggest to ask in forum.joomla.org. The supporters there are very good with ACL problems. Give them a link to this issue. 
I close this for now as it is not a joomla core problem. It can be re-opened if necessary.

**Comment by Borgas** [comment]
> Normally a user in Registered group has no access to the backend. Something is wrong with your settings.

Hello, it´s not the registered who as access.

User 1 - Registered
Manager 1 - Manager

Manager 1 can go to back-end and CAN NOT edit is group in is profile
Manager 1 can go back-end and VISIT User 1 profile, and tell is a Higher Manager than is own

For me, this shouldn´t be possible. Manager should only be able to assign until is level...not higher.

**Comment by drmenzelit** [comment]
Try the same on a fresh installed Joomla site, before doing changes on your own. If that still happens, then it is probably a bug.

**Comment by Borgas** [comment]
> Try the same on a fresh installed Joomla site, before doing changes on your own. If that still happens, then it is probably a bug.

Hello, thank you for reply

It´s a fresh install, no "extra things" installed, just core Joomla. And updated to latest version
That´s why i open this ticket here, not in forum.

I think no one tried to replicate the issue. Maybe my english is not so good to explain the steps

**Comment by drmenzelit** [comment]
No, it is not a clean install, you have already changed the user groups. And as I told you, if an user is in several groups with different permissions, the higher permission will won.
