### ISSUE TITLE
Language Overrides Search results not per language

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#37779]
Hi guys,
happening on 4.1.3 and also on J 3.10.9

Language Override > I select the Language (Administrator / Site) > New item or Edit > When I perform a Language String Search ( Value or Constant ):

**A** - Should the result give me only the results of the selected language ?
So, one result for the same language strings...

**B** - ...OR, Should the result give me all the language files strings in the folders for the same Constant string language / Value ?
So, more results (all languages) for the same language strings (depending on the installed languages)...

As far as I know, [here the Joomla Forum discussion](https://forum.joomla.org/viewtopic.php?f=708&t=988729 "J Forum topic"), "**A**" should be the right, while some 3rd parties extensions (like DPCalendar, Solidres) are running in the "**B**" mode that complicates a lot the Language String Search for Overrides...
I add an image for you:

![DPCalendar-languages-strings](https://user-images.githubusercontent.com/14607633/167890857-b7a291b3-3e56-4be3-8150-23286cf898a4.png)

Now, I asked to Allon (DPCalendar team leader) and he gently replied to me:
"...I had a deeper look on the code and it is an issue with the override feature which is not using the current language. This needs a bigger refactoring in the CMS. So I suggest you open an issue on the CMS repo. ...it is not DPCalendar related, but affects every extension..."

**Comment by infograf768** [comment]
It should be A and I confirm the issue.
Looks like the problem comes from the fact that the code is not optimized to fetch the results from the extension's local language folder when the strings are not in the core language folder.

**Comment by Bakual** [comment]
I think this should work: https://github.com/joomla/joomla-cms/pull/37809

**Comment by richard67** [comment]
Will it be fixed in 3.10-dev, too?

**Comment by richard67** [comment]
And why in 4.2-dev and not 4.1-dev? Is it considered a new feature?

**Comment by richard67** [comment]
After having discussed this with other maintainers, I think it is ok to fix this in 4.2.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37809 . Thanks in advance.

**Comment by joomleb** [comment]
> Will it be fixed in 3.10-dev, too?

@richard67 
Thanks and, Please, What about this question ?

**Comment by richard67** [comment]
It seems the answer is: No.
