### ISSUE TITLE
[4.x] replace placeholder eg. for username reminder fail (german translation issue)

### ISSUE THREAD

**Issue by dawe78** [joomla/joomla-cms#37773]
### Steps to reproduce the issue
Frontend: go to "send username" and send form. 

### Expected result
Mail contains proper text with replaced placeholders

### Actual result
Mailtext still contains placeholder {site} and {siteurl}

### System information (as much as possible)
Joomla 4.13
PHP 7.4

### Additional comments
The language file "de-DE/com_users.ini" contains old placeholders. Joomla has changed placeholder {site} (old) to {sitename} (new) but not all language strings were updated yet, eg. COM_USERS_EMAIL_USERNAME_REMINDER_BODY. Language file has to be updated for proper reminder mails.

Another issue is that array key "siteurl" is not set eg in RemindModel.php (line 180+), but placeholder is used in language string and should be replaced.

**Comment by brianteeman** [comment]
@tecpromotion

**Comment by heelc29** [comment]
Please see https://github.com/joomlagerman/joomla/pull/2443

**Comment by tecpromotion** [comment]
@dawe78 please use https://github.com/joomlagerman/joomla/issues for german only issues. Thanks.
Please close the issue.

**Comment by alikon** [comment]
closed as requested

**Comment by dawe78** [comment]
@tecpromotion Okay, I will open a new issue for joomla german, but one thing I reported is not only related to joomla german. In all language files the placeholder siteurl is used, eg. for username reminder, but this array key is not set in RemindModel.php of com_users. So this has to be fixed too. Should I open another issue or open this one again?

**Comment by tecpromotion** [comment]
> @tecpromotion Okay, I will open a new issue for joomla german, but one thing I reported is not only related to joomla german. In all language files the placeholder siteurl is used, eg. for username reminder, but this array key is not set in RemindModel.php of com_users. So this has to be fixed too. Should I open another issue or open this one again?

Please see https://github.com/joomlagerman/joomla/pull/2443
A new issue in the joomlagerman repo is not necessary.

And yes, please open a new issue for the other issue if this is still a bug.
> Another issue is that array key "siteurl" is not set eg in RemindModel.php (line 180+), but placeholder is used in language string and should be replaced.
