### ISSUE TITLE
JDatabaseExceptionConnecting returns a HTTP 200 status

### ISSUE THREAD

**Issue by shane-clickingmad** [joomla/joomla-cms#37787]
### Steps to reproduce the issue
Enter invalid mysqli credentials within configuration.php

### Expected result
a http 500 status to be returned

### Actual result
a 200 status is returned, along with the word "Error".

### System information (as much as possible)
has been tried on multiple systems include a plesk setup, and cpanel.

### Additional comments
RuntimeExceptions created by JDatabaseExceptionConnecting dont appear to be handled by the catch statement in the parent driver class.

**Comment by roland-d** [comment]
Hello @shane-clickingmad  Could you provider some more details on your setup and how you trigger this specific error because I cannot reproduce it at all. I tried incorret, hostname, username, password, database name, prefix, and port. They all returned a 500 error status.
