### ISSUE TITLE
WEBP for mediamanager

### ISSUE THREAD

**Issue by gopitzohlsen** [joomla/joomla-cms#37785]
### Is your feature request related to a problem? Please describe.

The media manager doesn't display WebP images. 

### Describe the solution you'd like

In order to use WebP images, it would be helpful to support this format in the media manager of Joomla and all effected plugins and modules.

**Comment by brianteeman** [comment]
webp is already supported

![image](https://user-images.githubusercontent.com/1296369/168052220-372b4d84-902e-4d20-8494-8996c63d0260.png)

**Comment by drmenzelit** [comment]
Closing this as it is not an issue. The support for webp files ~~can be added~~ is already in the media manager.

**Comment by brianteeman** [comment]
> The support for webp files can be added in the media manager.

Not true. You do not need to add anything

**Comment by drmenzelit** [comment]
> Not true. You do not need to add anything

True, I missed the fact that the file type is there by default
