### ISSUE TITLE
[4.1.3] menu ordering not saved

### ISSUE THREAD

**Issue by nzimas** [joomla/joomla-cms#37786]
### Steps to reproduce the issue

1. Create at least 2 menu items
2. Change their ordering in the backend using the drag and drop tool 

### Expected result

The position of menu items on the frontend should reflect the ordering of menu items in the backend.

### Actual result

Menu ordering is not saved in the backend, therefore the position of menu items on the frontend remains unchanged.

### System information (as much as possible)

Server:
Joomla 4.1.3
PHP 7.4.28
Mysql 10.1.48-MariaDB-0+deb9u2
Apache/2.4.25

Client:
Chrome 101.0.4951.64 for MacOS

**Comment by joomdonation** [comment]
Hello

This bug was fixed recently but will only be available on next Joomla 4.1.4 release. For the time being, you can use the solution I posted here https://github.com/joomla/joomla-cms/issues/37778#issuecomment-1124537696 .

**Comment by retromore** [comment]
Something is not quite perfect there with that JS patch. In modules list If I drag 2 modules (at the end of the list) – after _n_  number of drags it skips remembering the order again for some reason. Not 100% sure it's the correct pattern but I think it skips at some odd number of drags 3/7/15

__Update:__ this pattern seems to be consistent with all module items. Drag the same item 3 times and and it will skip saving the third one:

https://user-images.githubusercontent.com/9862634/168932216-b821b88d-5008-42d6-8732-353477106048.mp4

Same issue is reproducible in menu ordering
