### ISSUE TITLE
Joomla 4.1.3 installation fails

### ISSUE THREAD

**Issue by boris-grinac** [joomla/joomla-cms#37782]
### Steps to reproduce the issue
Tried to update Joomla site with Virtuemart. Update fails with "Invalid controller class: update"
Joomla front end also reports error after update ""Invalid controller class: display"
Tried both ways: standard update and manual upload update. The result is the same.
This is a brand new site, installed from scratch on Ubuntu 22.04 LTS.
Call stack
# 	Function 	Location
1 	() 	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:178
2 	Joomla\CMS\Dispatcher\ComponentDispatcher->getController() 	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:145
3 	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() 	JROOT/libraries/src/Component/ComponentHelper.php:389
4 	Joomla\CMS\Component\ComponentHelper::renderComponent() 	JROOT/libraries/src/Application/SiteApplication.php:204
5 	Joomla\CMS\Application\SiteApplication->dispatch() 	JROOT/libraries/src/Application/SiteApplication.php:243
6 	Joomla\CMS\Application\SiteApplication->doExecute() 	JROOT/libraries/src/Application/CMSApplication.php:278
7 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT/includes/app.php:63
8 	require_once() 	JROOT/index.php:32 

### Expected result
Update runs with no error and Joomla version is displayed as 4.1.3

**Comment by drmenzelit** [comment]
What happens if you disable Virtuemart? Did you tried the update on a website without Virtuemart?

**Comment by chmst** [comment]
Which Virtumart Version? The latest 4 for Joomla4? Which php version?

**Comment by boris-grinac** [comment]
Tried to disable all Virtuemart* and all VM* extensions. Upgrade from
Joomla 4.1.2 to 4.1.3 still fails with the same messages.

System information:
Setting Value
PHP Built On Linux shop-upsserv-cz 5.15.0-27-generic #28-Ubuntu SMP Thu Apr
14 04:55:28 UTC 2022 x86_64
Database Type mysql
Database Version 10.6.7-MariaDB-2ubuntu1
Database Collation utf8mb4_general_ci
Database Connection Collation utf8mb4_general_ci
Database Connection Encryption None
Database Server Supports Connection Encryption No
PHP Version 8.1.2
Web Server nginx/1.18.0
WebServer to PHP Interface fpm-fcgi
Joomla! Version Joomla! 4.1.2 Stable [ Kuamini ] 30-March-2022 16:00 GMT
User Agent Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0)
Gecko/20100101 Firefox/100.0

**Comment by drmenzelit** [comment]
>PHP Version 8.1.2

Maybe that is the problem. Are you sure Virtuemart is compatible with PHP 8.1? You should try with PHP 7.4 or 8.0

**Comment by brianteeman** [comment]
This is really a support issue that should be dealt with on the forum

**Comment by drmenzelit** [comment]
As Brian said that is a support issue that should be posted in the forum (forum.joomla.org)

**Comment by boris-grinac** [comment]
Dear Viviana, thanks for the idea to downgrade PHP to 8.0
This downgrade created a bunch of other issues, needed to configure php and nginx from scratch. But using error logs I have managed to make my shop work, Joomla upgrades now work.
Thanks.
