### ISSUE TITLE
[4] Http Headers plugin. Nonces on Category List block inline Javascript

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#37799]
### Steps to reproduce the issue
- Joomla 4.1.3. Core template. Firefox 100.0.
- Configure plugin "Http Headers" > "Content-Security-Policy (CSP)"
- Client: Site
- Nonce: Yes
- Add a "Policy Directive" for "Client: Site"

`script-src: {nonce} 'self' 'unsafe-inline'`
- Create a frontend menu item of type "Category List" for a article category with some articles.
- Activate some table headers to have possibility to order table columns.
- Open menu item in frontend with Firefox.
- See browser inspector. Error message that Inline scripts are blocked.

`Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf inline blockiert ("script-src"). 4 category-list`

- Try to order table columns by clicking on table headers. Fails.

### Reason

Inline Javascript (onclick)

```
<th scope="col" id="categorylist_header_title">
 <a href="#" 

onclick="Joomla.tableOrdering('a.title','asc','', document.getElementById('adminForm'));return false;"

class="hasPopover" title="" data-bs-content="Select to sort by this column" data-bs-placement="top" data-bs-original-title="Title">Title</a></th>
```

If Nonces are activated modern browsers ignore the rule 'unsafe-inline'.

### Result
We can't use the HTTP Header plugin with Nonces activated.

The inline scripts should be replaced by a document->addScriptDeclaration or similar. Then it will get a nonce.

**Comment by ReLater** [comment]
Addition. Where the inline script comes from:
https://github.com/joomla/joomla-cms/blob/4.1.3/libraries/src/HTML/Helpers/Grid.php#L64

**Comment by zero-24** [comment]
Yes unsafe-inline will be ignored when nonces are set and supported by the Browser.

And the solution proposal is correct too the Inline js call has to be converted into something thats pushed via the API so it can be allowed via hashes and nonces.

**Comment by ReLater** [comment]
As far as I see this issue should be fixed with https://github.com/joomla/joomla-cms/pull/39730
