### ISSUE TITLE
[4.1.3] PHP8.1.5: Warnings on Updater.php

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#37801]
### Steps to reproduce the issue

1. Use PHP8.1.5
2. Login screen at .../administrator/index.php
3. this 2 informations are shown (Error Reporting is 'Maximum')

```
Warning
: Trying to access array offset on value of type null in
.../libraries/src/Updater/Updater.php
on line
347


Deprecated
: version_compare(): Passing null to parameter #2 ($version2) of type string is deprecated in
.../libraries/src/Updater/Updater.php
on line
347
```

### Expected result
No Warnings are shown.

### Actual result
See above.

### System information (as much as possible)
![image](https://user-images.githubusercontent.com/89642616/168476544-01fa1a71-4b56-4741-9090-6aa181dc2036.png)

### Additional comments
On PHP 7.4.29 this warnings  aren't shown.

**Comment by eeshaanSA** [comment]
where are these informations shown? in the php log, error log or the warings section?

**Comment by ghost** [comment]
> Login screen at .../administrator/index.php
<img width="692" alt="Untitled" src="https://user-images.githubusercontent.com/89642616/170853890-65196741-1d69-47d0-9f18-b5fe26bbfbff.png">

**Comment by brianteeman** [comment]
Unable to replicate in 4.2

**Comment by ghost** [comment]
Closed as issue resolved. Thanks for looking at this @brianteeman
