### ISSUE TITLE
[4] scheduler  web cron not working

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#37806]
### Steps to reproduce the issue

go to system -> scheduled task -> web cron   enable it and save

### Expected result

![image](https://user-images.githubusercontent.com/181681/168556725-b7945ede-790d-46f2-8675-0b9a687c504c.png)

### Actual result
![image](https://user-images.githubusercontent.com/181681/168553348-90a75cde-c04d-4954-9376-959b43f219df.png)

**Comment by brianteeman** [comment]
Confirmed

**Comment by rgblogs** [comment]
How to solve this?

**Comment by joomdonation** [comment]
If I understand the issue correctly, PR https://github.com/joomla/joomla-cms/pull/37868 should fix it. Please help testing. Thanks !
