### ISSUE TITLE
Menu order not changable

### ISSUE THREAD

**Issue by schildmi** [joomla/joomla-cms#37808]
### Steps to reproduce the issue

- Login as administrator
- Go to menus
- Change order of an menu
- reload page

### Expected result

new order is shown

### Actual result

old order is shown

### System information (as much as possible)

Joomla 4.1.3

**Comment by ghost** [comment]
https://github.com/joomla/joomla-cms/issues/37778

**Comment by chmst** [comment]
Closing as duplicate
