### ISSUE TITLE
[4.1.3] Frontend: 'Publishing Options: Hide' show 'Publishing' tab

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#37816]
#### Set 'Publishing Options' to hide:

<img width="498" alt="backend-settings" src="https://user-images.githubusercontent.com/89642616/168765801-74a4c8a5-901b-4cb9-8828-37319fcd255b.png">

#### Open an article in Frontend, 'Publishing' tab is shown:

<img width="571" alt="publish-hide" src="https://user-images.githubusercontent.com/89642616/168766075-93df4864-e702-45ba-a836-92556373ea24.png">

#### Set 'Publishing Options' to show 'Metadata' tab is shown too:

<img width="572" alt="publish-show" src="https://user-images.githubusercontent.com/89642616/168766790-fdcd596e-f61e-4fd8-a7a4-0cc30321b46b.png">

### Expected result

In Frontend 'Publishing' tab is not shown.

### Actual result

In Frontend 'Publishing' tab is shown.

### System information (as much as possible)

<img width="688" alt="systeminfo" src="https://user-images.githubusercontent.com/89642616/168767303-c9b1dd4d-bc36-4f2b-9a30-a0db40f7c1f5.png">

### Additional comments

In Backend 'Publishing' tab has 'Publishing' and 'Metadata' parts, but in Frontend only the 'Metadata' part is hidden:

<img width="1403" alt="meta" src="https://user-images.githubusercontent.com/89642616/168768482-f3291725-0301-42cd-a32d-72d3e893d66d.png">

**Comment by alikon** [comment]
please test #37833

**Comment by alikon** [comment]
repoened as pr has been closed

**Comment by brianteeman** [comment]
> In Backend 'Publishing' tab has 'Publishing' and 'Metadata' parts, but in Frontend only the 'Metadata' part is hidden:

That's not correct. The tab named "publishing" is still displayed but the fields that would have been displayed on the admin form publishing tab are not displayed.

![image](https://user-images.githubusercontent.com/1296369/172311773-77f6073e-5775-4056-8224-4366ca330fbf.png)

![image](https://user-images.githubusercontent.com/1296369/172311881-4373c26c-b815-4bdd-89ee-2feb60e27b00.png)

**Comment by ghost** [comment]
I'm confused, i try again what i mean:

1. Set 'Publishing Options' to hide
2. Open an article in Frontend, 'Publishing' tab is shown. This is the core Issue i mean.

Maybe the Option mean "Hide some options but not the tab" and i misunderstand.

**Comment by brianteeman** [comment]
> Maybe the Option mean "Hide some options but not the tab" and i misunderstand.

yes

**Comment by ghost** [comment]
Thanks @brianteeman for your time :-) 

Closing issue as its not an issue.
