### ISSUE TITLE
[3.10.9] Links from numeric tags cause error 404

### ISSUE THREAD

**Issue by conseilgouz** [joomla/joomla-cms#37814]
### Steps to reproduce the issue
Create a numeric tag in an article, display this article, click on his numeric tag

### Expected result
display articles list 

### Actual result
error 404 : tag not found

### System information (as much as possible)
Joomla 3.10.9
php 8.1

### Additional comments
Due to 3.10.7  com_tags/models/tag.php update.

**Comment by richard67** [comment]
Closing as having a pull request. See #37815 .

@conseilgouz When you already know that you will make a pull request, it does not need to create an issue. The pull request is enough.

**Comment by conseilgouz** [comment]
thank you
