### ISSUE TITLE
Dark Mode (Boostrap 5.2)

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#37810]
### Is your feature request related to a problem? Please describe.
Bootstrap 5.2 will be available with the dark mode:

[https://github.com/twbs/bootstrap/pull/35857](https://github.com/twbs/bootstrap/pull/35857)
[https://blog.getbootstrap.com/2022/05/13/bootstrap-5-2-0-beta/](https://blog.getbootstrap.com/2022/05/13/bootstrap-5-2-0-beta/)

### Describe the solution you'd like
I suggest to add dark mode for `Control Panel` and also for `frontend` (if possible).

### Additional context
[https://github.com/joomla/joomla-cms/issues/26772](https://github.com/joomla/joomla-cms/issues/26772)

**Comment by ReLater** [comment]
> Bootstrap 5.2 will be available with the dark mode

Earliest in BS 5.3. At the moment they try to implement it in the BS 5.2 documentation.

https://github.com/twbs/bootstrap/projects/39#card-77835542
https://github.com/twbs/bootstrap/pull/35857

**Comment by Quy** [comment]
PR https://github.com/joomla/joomla-cms/pull/39400

**Comment by Quy** [comment]
PR  #41409
