### ISSUE TITLE
[4.2] Parameters in category blog menu item ignored

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#37822]
### Steps to reproduce the issue
Install blog sample data in a Joomla 4.2 instance
Check a category blog menu item
Play with the parameters for articles ordering, try to change the classes for items, etc.

### Expected result
The menu item "Blog" is configured to display 4 leading articles with classes "boxed" and "columns-2"
![grafik](https://user-images.githubusercontent.com/9153168/168836930-f65b2504-14a3-4a75-855b-bbae149bf42b.png)

In the frontend you should have a two columns layout with boxes

If you change the articles ordering in the menu item, you should see changes in the ordering of the articles in frontend

### Actual result

No columns, no boxes, no changes in ordering. The parameters from menu item are being ignored, only the global options are used.

### System information (as much as possible)
PHP Built On 	Windows NT DESKTOP-H2FDIEA 10.0 build 19044 (Windows 10) AMD64
Database Type 	mysql
Database Version 	10.4.22-MariaDB
Database Collation 	utf8mb4_unicode_ci
Database Connection Collation 	utf8mb4_general_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	No
PHP Version 	8.0.14
Web Server 	Apache/2.4.52 (Win64) OpenSSL/1.1.1m PHP/8.0.14
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 4.2.0-alpha3-dev Development [ Uaminifu ] 26-April-2022 16:49 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0

**Comment by chmst** [comment]
Confirmed. 

https://github.com/joomla/joomla-cms/blob/4.1-dev/components/com_content/src/Model/CategoryModel.php#L145
The $app->getMenu()->getActive() gives the active menu item in 4.1.
In 4.2 the result is empty.

**Comment by joomdonation** [comment]
It causes by PR https://github.com/joomla/joomla-cms/pull/37630. For 4.2-dev, calls `$app->getMenu()` always return a new menu object https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Application/CMSApplication.php#L533 , so active menu item set for menu (for example, during routing process) could not be get by calling `$app->getMenu()->getActive()` (always return null)

So somehow, we will have to cache menu instance per app like how we did in the past. @laoneo Could you please look at this ?

**Comment by ChristineWk** [comment]
Issue confirmed. Have the same settings as on the screenshot.
But I can only see 1 column.

System infos:
```PHP Built On 
Linux www45.world4you.com 4.18.0-305.10.2.2.lve.el8.x86_64 #1 SMP Wed Jul 28 12:08:46 EDT 2021 x86_64 
Database Type 
mysql 
Database Version 
5.7.36-log 
Database Collation 
latin1_swedish_ci 
Database Connection Collation 
utf8mb4_general_ci 
Database Connection Encryption 
None 
Database Server Supports Connection Encryption 
Yes 
PHP Version 
7.4.28 
Web Server 
Apache 
WebServer to PHP Interface 
cgi-fcgi 
Joomla! Version 
Joomla! 4.2.0-alpha3-dev Development [ Uaminifu ] 26-April-2022 16:49 GMT 
User Agent 
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:100.0) Gecko/20100101 Firefox/100.0 ```

 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37822">issues.joomla.org/tracker/joomla-cms/37822</a>.</sub>

**Comment by laoneo** [comment]
@joomdonation is right. But why we do need to cache the menu to make it work? Not saying we should not cache, but do we do set some params on runtime and not on create? Just wondering where the caching should be done as for me it looks like something along the line is wrong and revealed with the pr #37630.

**Comment by laoneo** [comment]
Please test #37824.

**Comment by alikon** [comment]
closing as we have a pr #37824
