### ISSUE TITLE
[4.1] Custom fields show list of field before content

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#37829]
### Steps to reproduce the issue

Create a custom field
place it into an article
you will see a list of fields before the content and then the field in content where it should be.
see http://bearscave.us/blog

### Expected result
Only custom field content displays

### Actual result
![image](https://user-images.githubusercontent.com/1850089/169359912-720d2e11-927a-4604-be7a-d98e8a9a57bd.png)

**Comment by RickR2H** [comment]
The visibility of the custom field is set in the field parameters. Closed for now as it is not an issue but by design.
