### ISSUE TITLE
Use of PHP reserved word in function name

### ISSUE THREAD

**Issue by ProfDavidMora** [joomla/joomla-cms#37823]
### Problem identified
This was initially discussed in the Inteliphense project in [this issue](https://github.com/bmewburn/vscode-intelephense/issues/2227).
The tool is detecting an instance of a function using the name `match` in the CMS core code. This is a PHP keyword since version 8.0 according to [the manual](https://www.php.net/manual/en/reserved.keywords.php) 

### Proposed solution
Change the name of this functions both at definition:
https://github.com/joomla/joomla-cms/blob/a8adadf982677c141686dc2b5560aabd2f944e76/libraries/src/Environment/Browser.php#L514

And the calling location (there seems to be only one place):
https://github.com/joomla/joomla-cms/blob/a8adadf982677c141686dc2b5560aabd2f944e76/libraries/src/Environment/Browser.php#L477

Some candidates for the new name:
- _match
- match_useragent
- match_features

### Open questions
I am not fully aware of all applicable coding rules (naming conventions), so I prefer to have someone with more expertise address the final code and include in the project if relevant. Does this need to be changed and what is the preferred final code for it?

**Comment by wilsonge** [comment]
As far as I can tell from the PHP RFC https://wiki.php.net/rfc/match_expression_v2  

```
match was added as a keyword (reserved_non_modifiers). This means it can’t be used in the following contexts anymore:

- namespaces
- class names
- function names
- global constants

Note that it will continue to work in method names and class constants.
```

We're using it in a method name here which means everything works fine. Given that this is a public method available for extension developers to use I'm not sure that we really want to change the function name - certainly we would have to keep the original in J4 as an alias even if we did set a new name

**Comment by eeshaanSA** [comment]
Hi, i would like to work on this issue, if allowed, as @wilsonge pointed out. I assume this is a good issue for beginners. Please point me out if i am wrong.

**Comment by ProfDavidMora** [comment]
@wilsonge, thanks for the reference to the RFC. It indeed works on the web server, most definitely, otherwise the webapp would have been broken during testing. I will contact the guys at Intelephense again so that they tweak the code sensing and allow this particular one in the stated contexts.

Given that fact, I understand there is no **need** for code changes, but maybe it should follow the path of deprecation so that extension developers have time to move away from it and eventually it can be taken out altogether and align with the evolution of PHP. Possibly not a top priority, understandably, but also something that can be done specially having a volunteer already jumping in. Thoughts?

**Comment by laoneo** [comment]
I'm closing this as it is an issue on the parser side.
