### ISSUE TITLE
[4.1.3]parameter description disapeared

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#37825]
I've found that all parameter descriptions for extensions disapeared. 
Is this a bug or a new setting for all extensions? 

with Joomla4. descriptions, which were displayed in Joomla3 with tooltips had been shown permanently - but now these descriptions disapeared as well.
Are parameter despriptions now not anymore neccessary?

**Comment by ChristineWk** [comment]
See here please: #37772 and PR #37819<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37825">issues.joomla.org/tracker/joomla-cms/37825</a>.</sub>

**Comment by richard67** [comment]
Would be nice if people would do at least a brief check if there is already an issue before creating the Nth duplicate report.

Closing as duplicate report.
