### ISSUE TITLE
[4.x] Manual update from package using "Stable-Full_Package" suddenly run instalation finalizing script on update ending (extract installation folder)

### ISSUE THREAD

**Issue by AndNovAtor** [joomla/joomla-cms#37834]
I had test Joomla 4.1.2 installation. 4.1.3 is [was] availible. I had 4.1.3 full install package file. I ran update, and when update ended, default instalation finalizing script was executed.
![image](https://user-images.githubusercontent.com/3628514/169466404-7f86a3cb-22c4-4189-bd43-7ccce4cf004e.png)

Also (not only because) installation folder was created (so installation finalizing script is executed).

Btw, if I rename/delete installation dir without ending finalizing script and open direct update ending link (for example, `http://sitedomain/administrator/index.php?option=com_joomlaupdate&task=update.install&57b0a0d70396539b89d9b72deb389c42=1`), then I got 303 riderects and then "Too many redirects" http error.

When I ended installation finalizing script and open admin panel (installation folder was removed), it's simply opens, as usual. When I opened old direct update ending link, it was redirected to admin update page, as usual.

As I remember, maybe I wrong, with Joomla 3, when using full package file for updating, it simply ignore installation directory inside package, so full package is used as default full updagte packed.

Soooo. Is described behavior above intended for Joomla 4? Or is it a bug/missing future from Joomla 3?

**Comment by richard67** [comment]
In my opinion, using a full installation package for updating is and always was wrong. If J3 allows this, it is a bug in J3, I think.

But I might be wrong.

**Comment by AndNovAtor** [comment]
@richard67 , I understand your opinion. I simply want (again) to note, if it would be a "bug" in J3, then something strange would be on package extracting. As no installation folder created (or removed immidiatly), it looks like J3 "check" a little package files (but replace all system files that package contains [all - for default update package, some - for "patch" update packages] - for security reasons, for example).

As J4 made many changes, it COULD be as intended for J4, but behavior to extract all files (including installation folder) looks more like extacting without "checks", and could be missing feuature (or, yes, _removed_ feature).

I created this issue for more discussions and "invistigating"

**Comment by richard67** [comment]
Well I agree that the updater simply should not allow to use a full installation package.

**Comment by AndNovAtor** [comment]
> Well I agree that the updater simply should not allow to use a full installation package.

Maybe, but it would be unintended for somebody (strange for me, but it doesn't count).

Forgot to note, why even I made _this_ update.

I had multiple test Joomla installations in localhost, few Joomla 4 installations. Some of it have old versions. Few days ago, I created new test installation, so I downloaded full package.
For my internet providers. I can't download update package from Joomla update urls, same for few "servers" on hosting providers, that blocks ANY outcoming connections (for example, using PHP/CURL/etc.). So, I only can use manual updates every time (download package manualy, sometimes only from GitHub).

So, when I have some old J4 installation, and I have lastest J4 install package (every time version changed and somehow I already have full package), I have two ways (for J3 in the past): simply immidiatly use full packeg to use it as default Update package (as I expected from Joomla), or download new file, sometimes with slow internet speed ~300kb/s, and need to wait while new file donloaded. Yes, I'm partially exaggerating, but still

Anyway, I think, first of all, need to discuss about old feature - using full package as full update packed, because J3 do it (even if it not so intended). And _then_ think about any changes to J4, if it's _realy_ needed

**Comment by richard67** [comment]
@AndNovAtor What keeps you from unzipping the full installation package, removing the installation folder and zipping it again to cover your scenario?

**Comment by AndNovAtor** [comment]
@richard67 , btw, good note. But, again, J3 do it "automatically". So, again, why I created this issue. To discuss.

**Comment by richard67** [comment]
> @richard67 , btw, good note. But, again, J3 do it "automatically". So, again, why I created this issue. To discuss.

@AndNovAtor Maybe it should be moved to discussions then? Issues are for bugs or missing functionality or UX issues.

**Comment by AndNovAtor** [comment]
@richard67 , it could be missing feuture or feuture request. ¯\\_(ツ)_/¯ I want more people to discuss.
Also, sadly, some people don't "use" discussion tab on GitHub...

**Comment by AndNovAtor** [comment]
Sorry, @brianteeman , for example, what do you think about it? This thing, that "is" in J3.

**Comment by richard67** [comment]
@AndNovAtor Other question: when you did that on J3 sites, have you at least removed the installation after that? You know there is a reason why it is to be removed after a new installation, and that reason does not go away just because it was an update which brought that folder back.

**Comment by AndNovAtor** [comment]
> have you at least removed the installation after that?

I wrote it above - it removed automaticaly or EVEN not CREATED.
So, it (full installation package) works as full udpdate package.
(But I don't know HOW it works actually)

**Comment by richard67** [comment]
> > have you at least removed the installation after that?
> 
> I wrote it above - it removed automaticaly or EVEN not CREATED.

@AndNovAtor Can you confirm that it still works like this with 3.10? Or is that some memory from old 3.4 times when it was possible to use the extensions installer for updating the core? I can’t check that myself now because am away from desk and on mobile.

**Comment by AndNovAtor** [comment]
>Can you confirm that it still works like this with 3.10?

Tested just now with updating 3.10.8 to 3.10.9 with full installation package (with two sites, one - on php 5.4, another - on php 7.4).

1) update started
2) in the middle of update `installation` folder was created
3) before the end (or on 2/3) `installation` folder was removed
4) update ended and showed "update succesfull"

**Comment by HLeithner** [comment]
@AndNovAtor even if it was possible to use the installation package to update Joomla! it's definitive not supported by us. So for example if someone looks at the installation folder why it doesn't get deleted on update it wouldn't mean that we have another problem tomorrow like maybe we don't have the sql update files anymore with the installation package because they are useless.

Also the upgrade packages are specially created with a smaller size to make updates faster. What we are missing since 4.0 are our minor version updates files. The reason for this is that our build script is unable to create them correctly atm.

So to come to an end this is a wouldn't fix because we don't have to resources to test this way to upgrade. I hope you understand us and can use the upgrade package.

What I'm more interested in is your problems with isps blocking (only our?) update servers
> For my internet providers. I can't download update package from Joomla update urls, same for few "servers" on hosting providers, that blocks ANY outcoming connections (for example, using PHP/CURL/etc.). So, I only can use manual updates every time (download package manualy, sometimes only from GitHub).

Which providers are blocking downloads with curl at all and which of them are blocking downloads.joomla.org (which is AWS S3 us-west-2), which blocks update.joomla.org which uses the cdn provided by our hostings sponsors rochen, and last github (which afaik) still uses amazon to host content.

For the moment I'm closing this issue, but you can always reopen it.

**Comment by AndNovAtor** [comment]
@richard67, @HLeithner, So let this issue remain closed.

> it's definitive not supported by us

Looks like it not supported in J4. =)

Anyway, as I sayed, I needed more information, and I got it. Also, this issue will remain "for the history".

Thx to all.

> What we are missing since 4.0 are our minor version updates files. The reason for this is that our build script is unable to create them correctly atm.

Btw, great thx for this info. Good to note it.
