### ISSUE TITLE
Subcategories cannot be sorted

### ISSUE THREAD

**Issue by Gratia-Mira** [joomla/joomla-cms#37845]
### Steps to reproduce the issue
Create new categories or subcategories in the Joomla backend. Try to change the category orders.
Refresh the page.

### Expected result
The order changes

### Actual result
The new order is not saved.

### System information (as much as possible)
The latest in Joomla (4.1.3 Stable)
Linux Server

**Comment by richard67** [comment]
Should have been solved with #37781 . See the comment there for a workaround:  https://github.com/joomla/joomla-cms/pull/37781#issuecomment-1124536569 . Please check and if it is solved close this issue. Thanks.

**Comment by Gratia-Mira** [comment]
Thanks, I figured that already exists a ticket and searched for it but unfortunately not found! The workaround has worked! Thanks again!
