### ISSUE TITLE
[4.1/4.2] Save User Actions Log Options

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#37840]
#### 1st part
J4.1 Remove all checkboxes and press save (no existing entry in #_action_logs_users for user)
![image](https://user-images.githubusercontent.com/66922325/169628383-a9b9a94c-1c74-413b-953a-57cb58ade877.png)

#### 2nd part
Different behavior in 4.2 after PR #37446 (no existing entry in #_action_logs_users for user)
In 4.2 by default no element in "Events to Email"
![image](https://user-images.githubusercontent.com/66922325/169628611-b2b1c93f-f021-4f4f-a110-c37926de9122.png)
In 4.1 by default all elements in "Events to Email"
![image](https://user-images.githubusercontent.com/66922325/169628614-95c08720-e00e-40df-aeb0-cf33abf200ac.png)

So it is not possible in J4.2 to save the user (without adjust something in user actions options) for eg to generate the api token (→ same error like in J4.1 when no extension is selected)
![image](https://user-images.githubusercontent.com/66922325/169628774-74e8c9ca-8069-42da-af9e-628e9279fc5b.png)

### Expected result

1st part: No error
2nd part: All extension are selected by default

### Actual result

1st part: Not possible to save if no checkbox is checked
2nd part: No extension is selected by default

### System information (as much as possible)

J4.1: ‎4.1.4-rc2-dev
J4.2: 4.2.0-alpha3-dev

**Comment by brianteeman** [comment]
Closing as this was resolved with #38439
