### ISSUE TITLE
[4.1] mod_feed. Inline CSS style not working when using Content-Security-Policy with Nonces

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#37859]
### Steps to reproduce the issue
J!4.1.3. Current Firefox.

At the end of the day it's somehow a security issue because users can't activate security settings without losing functionality here or there.

Related https://github.com/joomla/joomla-cms/issues/37799 (Same reason. Inline scripts in Joomla core make usage of CSP with nonces pointless).

Step 1:
- Create a FE module `mod_feed`.
  - Example feed: `https://www.rki.de/SiteGlobals/Functions/RSSFeed/RSSGenerator_nCoV.xml`
  - **Set `RTL Feed`: `Yes`.**
  - Position `Banner` of `Cassiopeia`.
- See module in frontend: It's right aligned. OK. (Image 1).

Step 2:
- In plugin `System - HTTP Headers`
  - Activate `Content-Security-Policy (CSP)`.
  - Don't activate any switch.
  - Add Policy Directive: `style-src: 'self' 'unsafe-inline'`
  - Activate plugin
- See module in frontend: It's right aligned. OK. (Image 1).

Step 3:
- In plugin `System - HTTP Headers`
  - Activate `Nonce`
  - Change Policy Directive: `{nonce} 'self' 'unsafe-inline'`
- See module in frontend: It's left aligned. NOT OK. (Image 2).

Reason: 
- Inline style https://github.com/joomla/joomla-cms/blob/4.1.3/modules/mod_feed/tmpl/default.php#L69
- `direction: rtl` ignored.

### Image 1

![grafik](https://user-images.githubusercontent.com/20780646/169713102-96e6e5a5-8f90-4761-af4f-9d249e3abd1f.png)

### Image 2

![grafik](https://user-images.githubusercontent.com/20780646/169713230-ef9605ae-79c4-4f76-a1f0-fbab76a379db.png)

### Additional comments
Inline scripts and styles shouldn't be used in Joomla core.

**Comment by ChristineWk** [comment]
@ReLater 
Confirmed. Thank you for your instructions/explanations.
<code>unsafe-inline'" is ignored inside script-src or style-src</code>
<code>Content Security Policy: The site's settings have blocked loading of a resource on inline ("style-src").</code>

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37859">issues.joomla.org/tracker/joomla-cms/37859</a>.</sub>

**Comment by ReLater** [comment]
A B\C solution can be something like this: https://github.com/ReLater/joomla-cms/pull/1/files

Other solution could be to add new helper classes to core CSS files like `direction-rtl` and `direction-ltr`, but not B\C if people use other templates.

**Comment by ChristineWk** [comment]
> A B\C solution can be something like this: https://github.com/ReLater/joomla-cms/pull/1/files
> 
changed https://github.com/ReLater/joomla-cms/pull/1/files accordingly and got right aligned in frontend:

`<div class="text-right feed modFeedDir-169">
						<h2 class=" redirect-ltr">`

**Comment by richard67** [comment]
Closing as having a pull request. See #37873 (and also #37872 ).
