### ISSUE TITLE
[4.1] It isn't possible to move submenu item on the last position with drag and drop

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#37869]
### Steps to reproduce the issue
- Build a menu item with at least three child menu items
- Try to move a sub menu item to the last position with drag & drop

### Actual result

It isn't possible 

### System information (as much as possible)

Tested with Joomla 4.1.3, PHP 8.0.16

**Comment by ghost** [comment]
https://github.com/joomla/joomla-cms/issues/37778

**Comment by richard67** [comment]
@paternax This has been solved meanwhile with PR #37781 , and the fix will be available in the upcoming release 4.1.4 scheduled for tomorrow. If you can't wait for that and need the fix before, use the workaround described here: https://github.com/joomla/joomla-cms/pull/37781#issuecomment-1124536569 .

Closing as duplicate report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37869">issues.joomla.org/tracker/joomla-cms/37869</a>.</sub>
