### ISSUE TITLE
[4.1] The outside of the tags is not fully visible at focus.

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#37864]
### Steps to reproduce the issue

- Install Joomla testing data and visit a page that contains tags.
- Hover over a tag.

### Expected result

The outside of the tags is fully visible at focus.

### Actual result

The outside of the tags is NOT fully visible at focus.
![screen shot 2022-05-23 at 09 38 56](https://issues.joomla.org/uploads/1/0fa70d3c01ccb4a6b6d93da41068ac0e.png)

### System information (as much as possible)

J4.1

### Additional comments

None

**Comment by brianteeman** [comment]
I am sure we have had this problem before. Weird

**Comment by brianteeman** [comment]
please test #37877

**Comment by alikon** [comment]
closing as we have a PR
