### ISSUE TITLE
[4.1] Changes to article template are not changed when selected

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#37862]
### Steps to reproduce the issue

create an article template
go to article and apply template
change the article template
go to article and attempt to load that changed template
clear cache & try pulling in the changed template again.

### Expected result
changes made in template are present.

### Actual result
Old template code still pulled.

### System information (as much as possible)
[systeminfo-2022-05-23T00_18_39+00_00.txt](https://github.com/joomla/joomla-cms/files/8750523/systeminfo-2022-05-23T00_18_39%2B00_00.txt)

### Additional comments

Eventually that change is pulled but idk what the trigger is to make that happen.

**Comment by N6REJ** [comment]
This might be related to a category blog issue... I have the article empty yet the category blog menu item still shows the camero
![image](https://user-images.githubusercontent.com/1850089/169723720-4ee97f35-189d-41d5-9d9c-1e85b3293847.png)
clicking on it however shows an empty article.

**Comment by brianteeman** [comment]
This is obviously a cache issue on your install - pleas use the forum for support

**Comment by N6REJ** [comment]
not at all convinced its a cache issue, even though thats logical, as it does it on multiple browsers/pc's and clearing cache does nothing. but for the moment I'll let it drop.

**Comment by brianteeman** [comment]
>  as it does it on multiple browsers/pc's and clearing cache does nothing. but for the moment I'll let it drop.

Don't confuse browser cache with all other types of cahce

**Comment by N6REJ** [comment]
FInally tracked it down.. not sure why yet, but its J51 templates.  Tried 2 of them and both did the same, but another template ( not casseopia ) doesn't have the issue.

**Comment by N6REJ** [comment]
@brianteeman after speaking to TASSOS it turns out the exact problem is the cache within novrain framework ( j51 convert form ) doesn't play nice with cache cleaner ( nonumber ).  He's working on the issue.
