### ISSUE TITLE
Webcon Protection Key not generating

### ISSUE THREAD

**Issue by rgblogs** [joomla/joomla-cms#37867]
### Steps to reproduce the issue

Navigate to System -> Scheduled Tasks -> Options -> Web Cron

Save the configuration.

The webcron needs a protection key before it is functional. Saving this configuration will autogenerate the key.

### Expected result

After saving, key should be generated.

### Actual result

Key not generated.

**Comment by richard67** [comment]
Closing as duplicate report. See #37806 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37867">issues.joomla.org/tracker/joomla-cms/37867</a>.</sub>
