### ISSUE TITLE
[4.1.4] Updating to 4.1.4 with Debug displays a warning at the front end

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#37884]
### Steps to reproduce the issue
Update Joomla 4.1.3-rc2-dev while the Debug option is selected and error reporting in Global Configuration is set to 'Maximum'.
Browse to the front end.

### Expected result
No errors or warnings.

### Actual result
Warning: file_get_contents(C:\www\joomla4test\administrator\cache/plg_system_debug_site\X6649be3832b1df130203803d39442fa1.php): Failed to open stream: No such file or directory in C:\www\joomla4test\plugins\system\debug\src\Storage\FileStorage.php on line 55
Call Stack
#	Time	Memory	Function	Location
1	0.0011	363128	{main}( )	...\index.php:0
2	0.0033	364456	require_once( 'C:\www\joomla4test\includes\app.php )	...\index.php:32
3	0.0597	1295112	Joomla\CMS\Application\CMSApplication->execute( )	...\app.php:63
4	0.6624	7586584	Joomla\Event\Dispatcher->dispatch( $name = 'onAfterRespond', $event = ??? )	...\CMSApplication.php:321
5	0.6624	7587328	PlgSystemDebug->onAfterRespond( class Joomla\Event\Event { protected $name = 'onAfterRespond'; protected $arguments = []; protected $stopped = FALSE } )	...\Dispatcher.php:486
6	0.6646	7728664	Joomla\Plugin\System\Debug\JavascriptRenderer->render( $initialize = ???, $renderStackedData = ??? )	...\debug.php:367
7	0.6649	7730312	DebugBar\DebugBar->getStackedData( $delete = ??? )	...\JavascriptRenderer.php:116
8	0.6649	7730264	Joomla\Plugin\System\Debug\Storage\FileStorage->get( $id = 'X6649be3832b1df130203803d39442fa1' )	...\DebugBar.php:383
9	0.6649	7730392	file_get_contents( $filename = 'C:\\www\\joomla4test\\administrator\\cache/plg_system_debug_site\\X6649be3832b1df130203803d39442fa1.php' )	...\FileStorage.php:55

### System information (as much as possible)
Wampserver 3.2.8 on Windows 10 with PHP 8.0.15 and MySQL 8.0.27

### Additional comments
Turning the Debug option off gets rid of the warning at the front end.
A second 4.1.4-rc site where the Debug option was turned off displayed the front end all right, with no warning, after the update to 4.1.4 was completed.

**Comment by Fedik** [comment]
I cannot reporduce it on 4.1.4, with php 8.1 (error maximum), on Linux

**Comment by brianteeman** [comment]
After several months with no other reports this should probably be closed
