### ISSUE TITLE
Joomla 4.1.4 Update - We can't find a download URL

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#37880]
### Steps to reproduce the issue
Joomla 4.1.3 to 4.1.4
Click on the admin panel update notification.
![guncelleme](https://user-images.githubusercontent.com/423588/170098380-a218d0ab-7cdb-4ff7-a060-baea99116ecb.png)

### Expected result
We can't find a download URL
![update](https://user-images.githubusercontent.com/423588/170098560-819565d4-2a0c-4adc-b433-b79804ab05fc.png)

### System information (as much as possible)

[systeminfo-2022-05-24T20_42_26+03_00.txt](https://github.com/joomla/joomla-cms/files/8765037/systeminfo-2022-05-24T20_42_26%2B03_00.txt)

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/37879

**Comment by ghost** [comment]
> #37879

Thank you.

**Comment by PhilETaylor** [comment]
> Thank you.

Two words the Joomla project never even said to me for reporting it... oh well...

**Comment by ghost** [comment]
@PhilETaylor Thanks again.
