### ISSUE TITLE
Class "Joomla\Plugin\System\Cache\Extension\Cache" not found after upgrading to 4.2.0-alpha3

### ISSUE THREAD

**Issue by swiffer** [joomla/joomla-cms#37881]
### Steps to reproduce the issue

After upgrading from 4.2.0-alpha2 to 4.2.0-alpha3 Joomla Admin and Site are not working anymore via ZIP package from the GitHub release.

### Expected result

Should work fine

### Actual result

Class "Joomla\Plugin\System\Cache\Extension\Cache" not found

### System information (as much as possible)

PHP 8.1.6 / Ubuntu

**Comment by richard67** [comment]
@swiffer Have you used the Joomla Update Component to upload and update? Or have you uploaded and unpacked the zip manually?

**Comment by swiffer** [comment]
I've used the update component

**Comment by richard67** [comment]
@nikosdion Is this right here? https://github.com/joomla/joomla-cms/pull/36042/files#diff-14bdb875e42e40282bacd45f20f1b1895c2d2cd786c526d9e8c1d4d91a986b2cR20

Update: Hmm, seems to be all right.

**Comment by swiffer** [comment]
i removed the plugin entry from the #__extensions table and added it again from the current install sql script. now it's working fine again for me.

```sql
INSERT INTO `#__extensions` (`package_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `locked`, `manifest_cache`, `params`, `custom_data`, `ordering`, `state`) VALUES
(0, 'plg_system_cache', 'plugin', 'cache', 'system', 0, 0, 1, 0, 1, '', '{"browsercache":"0","cachetime":"15"}', '', 3, 0)
```

maybe because of the manifest_cache? can this in general be refreshed ?

**Comment by richard67** [comment]
The manifest cache of each extension is refreshed with the entries from the XML file at the end of an update.

**Comment by swiffer** [comment]
Looks like the Update didnt completely Run through. Also had a warning regards Out of Date core Database Schema.

**Comment by nikosdion** [comment]
@richard67 Yup, it is right, this is the class of the extension plugin object returned.

**Comment by richard67** [comment]
> Looks like the Update didnt completely Run through. Also had a warning regards Out of Date core Database Schema.

@swiffer Have you used the “Fix database structure” button (with the row of the CMS core selected)? If so: Did it help?

**Comment by swiffer** [comment]
Yes, i did that and it helped (for the alert of outdated DB Schema).

**Comment by richard67** [comment]
And the class not found error was shown after that?

**Comment by richard67** [comment]
Am asking because when using the fix button, it also refresh the manifest caches of extensions at the end.

And what is shown in the update log "administrator/logs/joomla_update.php"?

**Comment by swiffer** [comment]
No, it was shown directly after the Update and solved by removing the Mainfest Cache Data From #__extensions Table. Afterwards i was able to visit the Admin again and noticed that also DB Schema was outdated. Both together let me assume the Update wasn't completely successfully executed (4.2.0-alpha2 -> 4.2.0-alpha3). Now everything ist fine.

**Comment by richard67** [comment]
Well if everything is fine and we could be sure that the problem was not caused by a bug in our code, we could say let’s close this issue. But as long as we don’t know what the problem was, we can’t really be sure. What does the update log show?

**Comment by swiffer** [comment]
2022-05-24T18:23:42+00:00       INFO Ip.Ip.Ip.Ip      update  Neue Version wird jetzt installiert.

Thats all.

Close and reopen If someone Else ist experiencing this as Well?

**Comment by richard67** [comment]
> 2022-05-24T18:23:42+00:00 INFO Ip.Ip.Ip.Ip update Neue Version wird jetzt installiert.
> 
> Thats all.

That looks indeed incomplete.

> Close and reopen If someone Else ist experiencing this as Well?

Not sure yet. I‘d at least like to try to reproduce it, but I‘m off desk at the moment.

**Comment by PhilETaylor** [comment]
oh my... Im going to say that this is probably the same cause as the Joomla 4.2 fiasco ... that the update is not deleting autoload_psr4.php and allowing it to be regenerated. 

delete the /administrator/cache/autoload_psr4.php when you get the error message `Class "Joomla\Plugin\System\Cache\Extension\Cache" not found` and I bet it then magically works

**Comment by PhilETaylor** [comment]
for a 4.2.x to the 4.2.x this https://github.com/joomla/joomla-cms/pull/37990 merged in June would have fixed this persons issue reported in May.

However this was the WARNING you needed to prevent the Joomla 4.2 upgrade fiasco we see today

This issue should be closed.
