### ISSUE TITLE
Tags menu - Root

### ISSUE THREAD

**Issue by JohnDeJuhl** [joomla/joomla-cms#37887]
### Steps to reproduce the issue

When setting a Tags menu to start with "ROOT" it produces a 500 error

### Additional comments
![Screenshot 2022-05-24 at 22 21 28](https://user-images.githubusercontent.com/106227119/170194604-3e26f284-131e-43a5-b779-7c58d91372fc.png)

**Comment by chmst** [comment]
I cannot replicat that Error. Are you sure that your database is available? The first line in your screen tells about a general issue in your system. Please give some more information about your environment.

**Comment by JohnDeJuhl** [comment]
Sure :)

Joomla 4
Template: Helix Ultimate (Joomshaper)

Pls see enclosed screenshot:

If I set Parent Tag to: *ROOT*, I get the error (I don't know if ROOT is a
Joomla default - I don't recall having made it myself)

If I set it as: *None*, all tags are shown as expected.

[image: Screenshot 2022-05-25 at 10.28.13.png]

Thanks for your fast response :)

John.


On Wed, May 25, 2022 at 10:12 AM Christiane Maier-Stadtherr <
***@***.***> wrote:

> I cannot replicat that Error. Are you sure that your database is
> available? The first line in your screen tells about a general issue in
> your system. Please give some more information about your environment.
>
> —
> Reply to this email directly, view it on GitHub
> <https://mailtrack.io/trace/link/3277a1475dbc724e56cd145b531c2803603b91b2?url=https%3A%2F%2Fgithub.com%2Fjoomla%2Fjoomla-cms%2Fissues%2F37887%23issuecomment-1136930714&userId=8209242&signature=c3d1934e2bccc85b>,
> or unsubscribe
> <https://mailtrack.io/trace/link/dfdc5c39abc723d6daa23342687c589bb44d40c6?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAZKOLL5BEI6DSXJAZFQHCXTVLXOHBANCNFSM5W36NNHQ&userId=8209242&signature=affabcedb6777071>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>


-- 
Kind regards, med vänliga hälsningar, med venlig hilsen,

John Juhl

www.WaterproofingPilot.com
<https://mailtrack.io/trace/link/437d7d8082873d174db949c5eea56337674477c1?url=http%3A%2F%2Fwww.WaterproofingPilot.com&userId=8209242&signature=b8a6021723e6341d>
***@***.***
+45 24 46 41 42

Scan my info to your phone

**Comment by chmst** [comment]
New question - could you check if there are errors in sytem / maintenance /database?

**Comment by brianteeman** [comment]
Also please check to ensure that the error is not related to the template by testing with the cassiopeia template

**Comment by JohnDeJuhl** [comment]
Would love to - but I'm not a programmer or anything near that - are there
any tools in Joomla to check that? or do I have to enter the database via
Cpanel ?

(my son is studying programming - so perhaps I need his help :)

**Comment by chmst** [comment]
No need for programming sons - 
![grafik](https://user-images.githubusercontent.com/1035262/170254674-8e17b0c0-9676-4077-8c17-95b4c3580ca7.png)

If you have access to the backend, open the system panel and see if the Database is ok or if there is a yellow badge with errors.

**Comment by JohnDeJuhl** [comment]
Great, caus' I wanna learn myself :)

[image: Screenshot 2022-05-25 at 14.04.47.png]

**Comment by JohnDeJuhl** [comment]
Pretty strange - just updated J4 and now I don't get the error anymore....
strange, but good of course.

Anyway, Thanks for your effort :)

John.

**Comment by chmst** [comment]
Thanks for feedback, so I close this issue.
