### ISSUE TITLE
[J4] Media Manager Ordering

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#37893]
### Is your feature request related to a problem? Please describe.

The request arises from the difficulty of managing the images when they become many in the same folder and you want to use the last one uploaded in an article

### Describe the solution you'd like

Add option to order columns in list view
![image](https://user-images.githubusercontent.com/906604/170247633-654cc727-3601-4e7d-b8b6-80350bec77ed.png)

### Additional context
By default the images are shown as thumbs, but you can view them as a list.
The problem is that the list is not sortable for any of the columns

**Comment by Quy** [comment]
Duplicate #31347
