### ISSUE TITLE
[4.1] CMS Content button does not appear in custom Editor field when TinyMCE is the default editor

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#37897]
### Steps to reproduce the issue

- Have TinyMCE as default editor
- Create a custom field of type editor (assign to specific category/categories if preferred)
- Start a new document
- In the 'Content' tab you will see 'CMS Content' in the toolbar with a dropdown to select Article, Contact, Field, Media, Menu, etc.
- Switch to the 'Fields' tab and look at the custom editor field toolbar

### Expected result
To see the 'CMS Content' button

### Actual result
The 'CMS Content' button is not shown

### Additional comments
Is this something that needs to be 'allowed' in the TinyMCE setup? If so, what? And if so, it's definitely not intuitive.

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/170321920-4cbe7cbf-b7d7-4193-9166-35b0bb375ff0.png)

**Comment by Scrabble96** [comment]
Thanks.

**Comment by easypony** [comment]
# Steps to reproduce the issue
Have TinyMCE as default editor
Create a custom field of type "editor" assigned to a subfield (along with other text fields).
Start a new article
Switch to the 'Fields' tab for the subform and repeat the subform a few times.
In the second (or third, makes no difference) TinyMCE editor field use "CMS Content" button to add image where the cursor is placed
### Expected result
To see the image in the part of the TinyMCE editor where the cursor was
### Actual result
The image is loaded into the first TinyMCE editor instance before any content that was there.

**System information (as much as possible)**
Joomla 4.3.4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37897">issues.joomla.org/tracker/joomla-cms/37897</a>.</sub>
