### ISSUE TITLE
List of articles by tags (J4)

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#37890]
Hello, I notice that my sites that use tags, in J4.1.3 or J4.1.4, no longer work as I imagined.
When I click on a tag I should have a common article list. Off I go back to the home page. 
Do you also have this behavior?

Has there been a change and the cause would be that there is no "content" area in the home page?

**Comment by chmst** [comment]
I don't understand your issue. But maybe it is related to this: https://github.com/joomla/joomla-cms/pull/37721?

**Comment by Quy** [comment]
Closing due to no response.
