### ISSUE TITLE
Cassiopeia template Logo and menu alignment

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#37902]
### What needs to be fixed
The logo must be aligned with the menu.

**Default:**

![logo2](https://user-images.githubusercontent.com/423588/170486261-06ac902f-6bb8-476d-aada-29ffaf43383e.png)

### How would you fix it

![logo1](https://user-images.githubusercontent.com/423588/170486727-f01b6beb-da7c-4167-9fd7-5175c91d2528.png)

`.brand-logo img {
    padding: 0 20px;
}`

**Comment by richard67** [comment]
The proposed fix looks even more ugly.

If you select the leftmost menu item you will see that the menu is in fact aligned, just it’s border isn’t visible normally.

Either make the border of the menu visible with some CSS, or more the menu to the left. Both would look good.

But the solution you propose with your screenshot looks really bad.

**Comment by richard67** [comment]
Furthermore I think it as a deliberate design decision to have it that way. It can be easily adjusted to your taste by using a user.css (formerly called custom css).

So if you ask me I would say close this issue.

**Comment by chmst** [comment]
Agree with @richard67. Every template has its own logo, slogan, focus ring, menu style. No matter what we change - it will not fit for every site.

**Comment by brianteeman** [comment]
It is more about the menu alignment

It is something I have changed on every site so that it is left alignd with the logo

**Comment by richard67** [comment]
> It is something I have changed on every site so that it is left alignd with the logo

That would of course look better than the proposed solution to align the menu with the logo by moving it to the right.

Feel free to make a PR.

**Comment by brianteeman** [comment]
please see #37905 for a proposal

**Comment by richard67** [comment]
Closing as having a pull request. Please test #37905 . Thanks in advance.

**Comment by ghost** [comment]
Thank you

**Comment by chmst** [comment]
Aligning the menu exactly with the logo has some side effects. For example: if the focus ring more visible with padding and a thicker line it will be cut as we have seen in some places. I would leave the alignment of elements to the user.

**Comment by coolcat-creations** [comment]
The maintenance team decided not to allow fixing this, so this issue should be closed.
@rdeutz
