### ISSUE TITLE
Cassiopeia Template + Bootstrap 5.1.3 + Mobile Menu issue

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#37916]
### What needs to be fixed
If we add bootstrap (js, css) with Cassiopeia, the mobile menu does not work.

**Install** new Joomla 4.1.4.

- getbootstrap.com
- Copy-paste the stylesheet <link> into your <head> before all other stylesheets to load our CSS.
`<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">`

- Place one of the following <script>s near the end of your pages, right before the closing </body> tag, to enable them.
`<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>`

After completing this process, we can now use some features of Bootstrap on our website. It's all right!

https://user-images.githubusercontent.com/423588/170824011-3c7fa78c-507a-4c27-b00b-88f9989f3e35.mp4

### Why this should be fixed

The mobile menu, unfortunately, does not work.

### How would you fix it
Seems to be an issue with the Cassiopeia menu JS.

### Side Effects expected

Best Regards

**Comment by dgrammatiko** [comment]
> After completing this process, we can now use some features of Bootstrap on our website. It's all right!

That's not how it supposed to work. Check how the javascript should be added PER USE CASE: https://gist.github.com/dgrammatiko/efb3de4aa7cab4813a244f93f73cc0fd

**Comment by brianteeman** [comment]
Why are you loading bootstrap twice?

**Comment by joomlaphp** [comment]
> > Bu işlemi tamamladıktan sonra artık Bootstrap'in bazı özelliklerini web sitemizde kullanabiliriz. Her şey yolunda!
> 
> Bu böyle olmamalıydı. KULLANIM DURUMUNDA javascript'in nasıl eklenmesi gerektiğini kontrol edin: [https://Gist.github.com/dgrammatiko/efb3de4aa7cab4813a244f93f73cc0fd](https://gist.github.com/dgrammatiko/efb3de4aa7cab4813a244f93f73cc0fd)

**Comment by ghost** [comment]
> > Bu işlemi tamamladıktan sonra artık Bootstrap'in bazı özelliklerini web sitemizde kullanabiliriz. Her şey yolunda!
> 
> Bu böyle olmamalıydı. KULLANIM DURUMUNDA javascript'in nasıl eklenmesi gerektiğini kontrol edin: [https://Gist.github.com/dgrammatiko/efb3de4aa7cab4813a244f93f73cc0fd](https://gist.github.com/dgrammatiko/efb3de4aa7cab4813a244f93f73cc0fd)
Ok, I understand now, thank you.

> Why are you loading bootstrap twice?

You're right, thank you both.
