### ISSUE TITLE
Issue with navigation menu and breakpoints between medium and large screens.

### ISSUE THREAD

**Issue by mariantanase** [joomla/joomla-cms#37926]
### Steps to reproduce the issue
Clean installation of joomla 4.1.4 without any changes. 
I noticed that on screens with resolutions between 768px (medium) and 992px (large), the navigation menu does not collapse to hamburger menu.

### Actual result

![joomla-breakpoint](https://user-images.githubusercontent.com/3976174/170977688-4cba69d7-02d9-45d8-8ac6-ad58305bf230.png)

### System information (as much as possible)
Joomla 4.1.4
PHP 8.0.13
MySQL 8.0.27

**Comment by ChristineWk** [comment]
That could be a possible solution. Written by a user in the German Joomla forum:

`@media (min-width: 768px) and (max-width: 991px) {
.navbar-expand-md .navbar-collapse:not(.show) {
    display: none !important;
  }
}

@media (max-width: 991px) {
  .navbar-expand-md .navbar-toggler {
    display: block !important;
  }
}
`

**Comment by mariantanase** [comment]
Thanks @ChristineWk 
This fix resolved the issue. However, it would be better if it can be implemented in the future directly in the joomla core.

**Comment by ChristineWk** [comment]
@mariantanase

 Unfortunately, I can't tell you how to proceed here. let's wait for more information

**Comment by mariantanase** [comment]
I notice that the issue is still present on the most recent nightly build, Joomla_4.2.0-beta1-dev-Development-Full_Package.

**Comment by TAGarrison** [comment]
I don't know if it helps or not, but the same issue includes sidebars - they are not hidden in the 1024px mobile size, which is the iPad Pro 12.9 inch. It works in all other sizes properly.
I can also confirm that the menu issue is still a problem. I found the CSS here and that fixed things for me, but not the sidebar. You can hide the bar itself, but you cannot hide the container, so there's a huge white-bar in the iPad Pro 12.9.

**Comment by ChristineWk** [comment]
add. Issue: #39645<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37926">issues.joomla.org/tracker/joomla-cms/37926</a>.</sub>

**Comment by Mohammadkhan18** [comment]
Is this issue is still open? ,because adding some bootstrap classes will automatically resolve the issue i think<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37926">issues.joomla.org/tracker/joomla-cms/37926</a>.</sub>

**Comment by alikon** [comment]
yes, feel free to submit a pull request

**Comment by hans2103** [comment]
PR #40574 created

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40574 . Thanks in advance.
