### ISSUE TITLE
Email Cloaking Plugin Does Not Sustain Link Classes

### ISSUE THREAD

**Issue by waveswebdesign** [joomla/joomla-cms#37922]
### Steps to reproduce the issue
1) in Joomla 4X with Plugin Email Cloaking enabled apply a css style to a link. For example <a href="email@email.com" class="button button-xlarge">Join the Meet Up</a></p>

### Expected result
The link class is applied

### Actual result
The link class is not applied

### System information (as much as possible)

Joomla 4X

Gantry 5 Template Studius by Rocket Themes

### Additional comments

Template developer has confirmed that this is a Joomla Bug and suggested I report the issue

**Comment by brianteeman** [comment]
Unable to confirm

![image](https://user-images.githubusercontent.com/1296369/170879964-31c0508d-e2cb-4076-bdfd-b4c9e9fa9bb3.png)

![image](https://user-images.githubusercontent.com/1296369/170879992-9a632914-7307-431f-a188-358322180963.png)

**Comment by chmst** [comment]
> Gantry 5 Template Studius by Rocket Themes 

Try with Cassiopeia - does it work in Cassiopeia?

**Comment by richard67** [comment]
Is is related to issue #36166 ? If so, would PR #36269 help? It seems the PR needs some changes, but maybe it would help here, too?

**Comment by waveswebdesign** [comment]
It is only for mailto: links
I posted a sample but it didn't show the code I guess...
![Capture-2](https://user-images.githubusercontent.com/106483097/170894790-82fcef7c-56ec-4e3a-bc38-9a68a113eb06.JPG)
I am posting template developer response for clarification

**Comment by Quy** [comment]
Please test PR #36269.
