### ISSUE TITLE
Problems with tags

### ISSUE THREAD

**Issue by Kadmon06** [joomla/joomla-cms#37927]
### Steps to reproduce the issue

Add more than 5 tags to an article. Edit: It seems to depend on the specific tags I add to the article, some tags remain, others get removed. It looks that if I type the name of the tag, and add it that way, it causes this problem. If I just choose them from the listed tags, I can add any number of tags.
Save the article - the tags will appear in the contentitem_tag_map.
When the article refreshes after saving, it will only show 5 tags.
If I save the article again, it will only save those 5 tags, deleting the rest from the contentitem_tag_map.

Sometimes it's 3 or 7 tags that gets opened from the database. It's odd.

![screen shot 2022-05-30 at 12 53 53](https://issues.joomla.org/uploads/1/4b04c8fffdbe31e8774cdc492f3b13a9.png)

PS: Also, the tag previews don't show up properly after adding the 5th tag. It becomes case sensitive, and sometimes I have to type the whole address line to be able to add a tag.

### Expected result

The article editor should open all of the tags. After saving, the tags should remain in the database.

### Actual result

If I open the article in the editor, and save it, only 3-5 tags remain.
Edit: When I open the article, it only reads the first 3-5 tags from the database, and treat the article as if only those tags were included. It treats tags that are already in the database, but not read, as new tags to be added.

![screen shot 2022-05-30 at 12 53 50](https://issues.joomla.org/uploads/1/a6c0f8dac915d1719214cda3a387399b.png)

Until I save it, the tags appear in the actual articles.

![screen shot 2022-06-01 at 06 50 06](https://issues.joomla.org/uploads/1/cf622d9880483064adf6fd372a75f805.png)

The tags are also there in the database:

![screen shot 2022-06-01 at 06 48 10](https://issues.joomla.org/uploads/1/d2d5aa3c0ab2f0c4e7f089846ad8ee1d.png)

Update: Sometimes it works normally, and I can add tags, that remain. I didn't change anything in the settings, or haven't updated anything when it started to work, and also didn't change anything when it turned problematic again.

### System information (as much as possible)

Lenovo Ideapad 320-15ISK Laptop - Type 80XH
Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz   1.99 GHz
12,0 GB RAM

Joomla 4.1.4
Multi-language site

Windows 10 Home 19044.1706 64bit
Firefox 100.0.2 & Google Chrome 101.0.4951.67

### Additional comments

The problem appeared after refreshing to Joomla 4.1.4.
It doesn't even notify the user, the tags just disappear.
If I open an article, change some grammar errors, and save the article, I lose almost all of the previously set tags.

### Solution

You need to switch the tags from AJAX to Nested.

Go to Global Configuration/Tags/Data Entry, and Tag Entry Mode should be Nested.

I still prefer the look of AJAX entry mode, with the full path, but it's a sacrifice I'm ready to make.

**Comment by chmst** [comment]
Thanks you for reporting. Could you please give more information? 
Which Joomla Version is it? Is it a multilingual site? 
Colud you add a screenshot with your tags?

**Comment by sfosseen** [comment]
I am seeing the same problem on my system.  Currently Joomla 4.1.4, but it has been consistent in every 4.x release I have used so far.

For me if I add the tags:  [Cloud Printing][Google Drive Storage][Hardened Repository][Printer Logic][Veeam][Vendor Presentation] in any order, after I save the article the only tags that show up are [Vendor Presentations][Veeam].  

I did an experiment and did discover that if I used just single work "Tags" All my tags are saved.  

I think it looks like if tags have a space, then things are not processed properly.

**Comment by chmst** [comment]
I cannot replicate that. 
@sfosseen is your site multilingual?

**Comment by Kadmon06** [comment]
"I think it looks like if tags have a space, then things are not processed properly."
For me, spaces don't make a difference in saving, however, you are right that when searching for the tags, it is able to find one-word tags, or tags that are separated by a - sign, but it doesn't work for phrases with a space between them.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37927">issues.joomla.org/tracker/joomla-cms/37927</a>.</sub>

**Comment by sfosseen** [comment]
My site is not Multilingual.

Tags were originally setup in a 3.x version of Joomla.  The site is pretty much a basic install of Joomla with only a comment component installed.  

Also on the articles, the "Tag" formatting seems to be off.  Some of the tags have different background.  

https://k12tech.plaea.org is the website.

**Comment by sfosseen** [comment]
OK, One other Suprise.  When I view the article, all the tags I have entered show up.  When I edit the document from the back end, only 2 of the tags are in the TAG dialog box.

Also, the two tags that show up in the dialog box, don't have the correct formatting on the front page, but the other tags on the front-end article are formatted correctly.

**Comment by Kadmon06** [comment]
What I also noticed is that the new tags I enter get the wrong path in the tags table.

Here's the parent id: 1611, that's "films".
However, in the path, after /films/ for some unfathomable reason, it adds Doctor Strange for every movie article I've written after publishing Doctor Strange. For example: english/nexus-eng/films/film-doctor-strange-in-the-multiverse-of-madness-2022/film-the-boys-season-3-2022
Even though, as parent, it correctly shows 1611, "films"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37927">issues.joomla.org/tracker/joomla-cms/37927</a>.</sub>

**Comment by Kadmon06** [comment]
"Also on the articles, the "Tag" formatting seems to be off. Some of the tags have different background."

That's because there are tags with 
class="btn btn-sm label label-info"
, and also tags with
class="btn btn-sm btn-info"

I have no clue how does the system choose which one to use for a tag, but more seem to have the first class than the second.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37927">issues.joomla.org/tracker/joomla-cms/37927</a>.</sub>

**Comment by Kadmon06** [comment]
Here is how it looks:
![screen shot 2022-06-17 at 12 11 35](https://issues.joomla.org/uploads/1/bd21e2ded8d73f8957c235a014cc52ce.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37927">issues.joomla.org/tracker/joomla-cms/37927</a>.</sub>

**Comment by brianteeman** [comment]
What is the value of max_input_vars?

# [Max - Input Vars](https://app.tango.us/app/workflow/91916cec-6f6e-45d9-bc0a-94796bdfa6fa?utm_source=markdown&utm_medium=markdown&utm_campaign=workflow%20export%20links)



__Date:__ June 17, 2022

__Author:__ Brian Teeman

__Source:__ [Tango](https://app.tango.us/app/workflow/91916cec-6f6e-45d9-bc0a-94796bdfa6fa?utm_source=markdown&utm_medium=markdown&utm_campaign=workflow%20export%20links)

***

### 1. [Go to Home Dashboard - Administration](https://j4.test/administrator/index.php)


### 2. Click on System
![Step 2 screenshot](https://images.tango.us/public/screenshot_df894d6c-34b9-4382-81a8-341d8a6b21bd.png?crop=focalpoint&fit=crop&fp-x=0.0370&fp-y=0.3660&fp-z=3.0671&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 3. Click on System Information
![Step 3 screenshot](https://images.tango.us/public/screenshot_36133137-ce1b-4ebf-a8c9-cccc69b9b542.png?crop=focalpoint&fit=crop&fp-x=0.8417&fp-y=0.2993&fp-z=3.0590&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 4. Click on PHP Settings
![Step 4 screenshot](https://images.tango.us/public/screenshot_b2d9a07b-91ea-447d-a375-e178f6d82c90.png?crop=focalpoint&fit=crop&fp-x=0.2913&fp-y=0.1933&fp-z=2.7350&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 5. Scroll to the bottom of the page
![Step 5 screenshot](https://images.tango.us/public/edited_image_da06c6f1-5a72-40db-b5a8-f7c3c096a5d1.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.5000&fp-z=1.0000&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1016%3A348)


***
_[This workflow was created with Tango](https://app.tango.us/app/workflow/91916cec-6f6e-45d9-bc0a-94796bdfa6fa?utm_source=markdown&utm_medium=markdown&utm_campaign=workflow%20export%20links)_

**Comment by sfosseen** [comment]
Maximum Input Variables on my system is "1000"

**Comment by brianteeman** [comment]
I suspect that you may be hitting that limit. Try changing that setting to 2000 and see if it resolves the problrem.

There are many ways that you can do this. Some of them are described [here](https://www.fastcomet.com/kb/change-php-max_input_vars-limit) or you might simply ask your web host to do it.

**Comment by Kadmon06** [comment]
Thank you for your idea!
However, I've changed mine up to 4000, but it didn't change a thing...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37927">issues.joomla.org/tracker/joomla-cms/37927</a>.</sub>

**Comment by Kadmon06** [comment]
"Tags were originally setup in a 3.x version of Joomla." 
Just like mine.

"The site is pretty much a basic install of Joomla with only a comment component installed."
I also use the same, Ccomment. I switched off Ccomment to check if that is the cause, but that didn't change anything about the problems.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37927">issues.joomla.org/tracker/joomla-cms/37927</a>.</sub>

**Comment by Kadmon06** [comment]
I've searched the net for similar cases, and found these threads:
https://forum.joomla.org/viewtopic.php?t=993798
https://github.com/joomla/joomla-cms/issues/35649

Also, I've found a possible solution to the problem. This solved mine problem, but others reported they still have the problem even after switching to Nested.

### Solution 1

You need to switch the tags from AJAX to Nested.

Go to Global Configuration/Tags/Data Entry, and Tag Entry Mode should be Nested.

I still prefer the look of AJAX entry mode, with the full path, but it's a sacrifice I'm ready to make.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37927">issues.joomla.org/tracker/joomla-cms/37927</a>.</sub>

**Comment by sfosseen** [comment]
> Maximum Input Variables on my system is "1000"

I have increased my "Input_Var" to "4000", Confirmed that on the System page it reflects the change to 4000.  I then edited an article, removed all the tags, saved the article, then edited the article by adding the tags back.  No difference in results after the increase of "Input Variables"

**Comment by sfosseen** [comment]
> I've searched the net for similar cases, and found these threads: https://forum.joomla.org/viewtopic.php?t=993798 #35649
> 
> Also, I've found a possible solution to the problem. This solved mine problem, but others reported they still have the problem even after switching to Nested.
> 
> ### Solution 1
> You need to switch the tags from AJAX to Nested.
> 
> Go to Global Configuration/Tags/Data Entry, and Tag Entry Mode should be Nested.
> 
> I still prefer the look of AJAX entry mode, with the full path, but it's a sacrifice I'm ready to make.
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/37927](https://issues.joomla.org/tracker/joomla-cms/37927).

This change did fix the issue on the back end of showing all the tags assigned to an article.  All the tags do show in the Article, but the formatting is still different between the tags.  
![image](https://user-images.githubusercontent.com/897317/174934238-b3f7b78d-7ee9-42e9-9718-d858c632a3ae.png)

**Comment by chmst** [comment]
Thanks for this hint, @Kadmon06 

@sfosseen have you different css classes or layouts in your tags options?

**Comment by sfosseen** [comment]
> Thanks for this hint, @Kadmon06
> 
> @sfosseen have you different css classes or layouts in your tags options?

Yes it does look like for some reason the css classes are different.

class=**"btn btn-sm label label-info"**  Is the class of the buttons that have always showed up on the back end, and on the front end appear not to have the proper formatting

class=**"btn btn-sm btn-info"** is the code for the buttons that were hidden on the back end after a save, and show the proper formatting on the front end.

![image](https://user-images.githubusercontent.com/897317/175090098-90f94f5f-df82-4abd-b48c-bed6a4f11536.png)

I have made no CSS changes myself.

**Comment by chmst** [comment]
This is stored in the database.  #__tags, column params. 
You have two possibilities: either delete the classes in older tags or define the old classes in the css file of your template.

I don't see a Joomla issue here

**Comment by Kadmon06** [comment]
The Joomla issue I see here is that I didn't change anything about the classes, but they were changed in the database.
Now that I know that they were changed (and where is it stored in the database), it's easy to remedy them, though.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37927">issues.joomla.org/tracker/joomla-cms/37927</a>.</sub>

**Comment by sfosseen** [comment]
> This is stored in the database. #__tags, column params. You have two possibilities: either delete the classes in older tags or define the old classes in the css file of your template.
> 
> I don't see a Joomla issue here

It does look like there was a change in how the TAGS component works between Joomla 3.x and 4.x, unless there is something in the template that would add "label label-info" to the option page of the TAG field in the back end.  I am able to confirm that if I remove the "Label label-info" from the CSS Class for tag link field, then the tags show up as I expect with the correct formatting.  

I do assume that if in the Tag settings I switch back to AJAX though that all the tags will not show up on the article edit screen after a save/close.  I will have to test.  


![image](https://user-images.githubusercontent.com/897317/175166673-9d790004-0aa7-4b4c-8ab8-02e98233af78.png)

**Comment by morphinestyle** [comment]
Same problem, temporarily fixed switching Ajax/nested

**Comment by sarahhayes103** [comment]
1st November 2022 - I'm also getting the problem with tags disappearing, which is fixed by switching from Ajax to nestled, so it seems like the problem persists or has returned, with the Ajax entry mode. I'm working on a new site with a clean/new install of Joomla 4.2.4.

I add tags (both already created in the tags component and creating on the fly in articles), tags are added to the tags component. Although on save the tags, some tags disappear from the article edit view, they have been saved. The problem is, that once they disappear from article view, if you save again, you then save the article without the tags and they disapear. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37927">issues.joomla.org/tracker/joomla-cms/37927</a>.</sub>

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/39254 should address this issue. Please help testing. Thanks !
