### ISSUE TITLE
[4.*] JOOMLA API by roles

### ISSUE THREAD

**Issue by JeremyLegendre** [joomla/joomla-cms#37925]
### Is your feature request related to a problem? Please describe.

Currently, only sysadmin users can access to API, with all rights on it. In most cases, we would like to create a role with API access, restricted to few routes ( for example only access to get requests and note delete)

### Describe the solution you'd like

Possibility to create custom roles with API, and a mapping between rights given by the role and accessible API routes OR the possibility to configure access foreach available routes

**Comment by HLeithner** [comment]
The reason for this limitation is that we want to evaluate the API first. It is planed that "normal" users get access to the API too.

**Comment by richard67** [comment]
> The reason for this limitation is that we want to evaluate the API first. It is planed that "normal" users get access to the API too.

@HLeithner So shall this issue stay open until that has been done? Or shall it be closed? Or shall it be moved to discussions?

**Comment by HLeithner** [comment]
I would like to get @wilsonge involved here

**Comment by richard67** [comment]
> I would like to get @wilsonge involved here

@HLeithner He can also be involved into a discussion, it doesn't need to be an issue.

**Comment by alikon** [comment]
could we use a single point for this like discussion https://github.com/joomla/joomla-cms/discussions/37908  ?

**Comment by HLeithner** [comment]
Closing this in favor for #37908 as suggested by Nicola
