### ISSUE TITLE
[4.1] Rate button vote plugin is not exactly aligned with selector

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#37920]
### Steps to reproduce the issue

- Enable the vote plugin
- Show voting (in an article or a menu item)

If you look closely, you can see that the rate button is not exactly aligned with the selector.
There's a little jump in it.

![screen shot 2022-05-29 at 09 17 28](https://issues.joomla.org/uploads/1/20d7428b69a5dbee63344aa22e230f82.png)

### Expected result

The rate button is exactly inline with the selector.

### Actual result

The rate button is NOT inline with the selector.

### System information (as much as possible)

J4.1

### Additional comments

None

**Comment by brianteeman** [comment]
Confirmed but no idea why

**Comment by ashish960** [comment]
Hy , i m new to open source ,i wants to solve this problem,can you assign me this issue

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39465 . Thanks in advance.
