### ISSUE TITLE
Menu aliases not working correctly

### ISSUE THREAD

**Issue by gochitashvili** [joomla/joomla-cms#37951]
### Steps to reproduce the issue
Create category: News
Create Tags: example1, example2, example3
Add articles and set different tags
Create  Menu items (Category blog) 

menu 1 (Category:News, Tag:example1)
menu 2 (Category:News, Tag:example2)
menu 3 (Category:News, Tag:example3)

### Expected result
Click on menu 1 should go to articles with ALIAS menu1
Click on menu 2  should go to articles with ALIAS menu2
Click on menu 3  should go to articles with ALIAS menu3

### Actual result
Click on menu 1 is going to articles with ALIAS menu1
Click on menu 2 is going to articles with ALIAS menu1
Click on menu 3 is going to articles with ALIAS menu1

### System information (as much as possible)

Using Xampp, Windows
PHP Version	8.0.18
Web Server	Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.0.18
Joomla! Version	Joomla! 4.1.4 Stable [ Kuamini ] 24-May-2022 16:00 GMT

### Additional comments
This happens only when I have same category and different tags on all articles, but if I specify each article to different category that is ok and works good.

**Comment by richard67** [comment]
Can it be that actual an expected result are mixed up in the description? “Actual” should be what the software really does, and “Expected” should be what you think the software should do.

And what has it do do with “alias”? As far as I can see in the description, all menu items are of type “category blog”, none is of type “menu item alias”.

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/171413121-eb859348-1160-4cc8-9c30-0ddf197ea495.png)

What you are seeing is actually the expected behaviour even if it is not what you expect or desire.

If you have multiple menu items all pointing to the same category then the first one is the one that is used. It does not consider the tags at this point in the process.

**Comment by gochitashvili** [comment]
I have multiple menus with same category but used different tags, so I was  going to set different modules on different menus, now this is not possible because all articles going to same alias.

Here is a loom video https://www.loom.com/share/376acc54081b4507966261a64cb961cd

**Comment by gochitashvili** [comment]
> Expected result

Sorry for my english, you are correct.

**Comment by richard67** [comment]
> > Expected result
> 
> Sorry for my english, you are correct.

@gochitashvili Then correct the description of this issue please.

**Comment by gochitashvili** [comment]
> > > Expected result
> > 
> > 
> > Sorry for my english, you are correct.
> 
> @gochitashvili Then correct the description of this issue please.

updated

**Comment by richard67** [comment]
> updated

Thanks.

But as Brian correctly mentioned, this issue might be closed as expected behaviour.

**Comment by gochitashvili** [comment]
Yes but I have already described and showing video of issue, why you think it is not? please describe..
Thanks.

**Comment by richard67** [comment]
What I mean is that the it is intended that the menu item alias is determined by the category and not by the tag. That's how it works, and as far as I know it is also how it is intended to work.

**Comment by gochitashvili** [comment]
okay, Agree.  it is not issue and can be closed
