### ISSUE TITLE
Big Problem JOOMLA 4

### ISSUE THREAD

**Issue by fredsotier** [joomla/joomla-cms#37965]
Bonjour,
Je vous informe qu'il existe un gros bug dans joomla 4,
un article dépublié s'affiche en ligne... Le public voit mes articles dépubliés, j'ai été choqué. Merci de me faire un retour pour savoir ce qui se passe. Merci

Hello,
I inform you that there is a big bug in joomla 4,
an unpublished article appears online... The public sees my unpublished articles, I was shocked. Please get back to me to find out what's going on. Thanks

**Comment by Fedik** [comment]
> an unpublished article appears online

How do you found it?
And do you sure that you not logged in to the site as admin?

**Comment by fredsotier** [comment]
No I checked

**Comment by chmst** [comment]
Which template (style) is active? Cassiopeia?
Is there a template override for blog?

**Comment by brianteeman** [comment]
this is obviously a problem best suited for the forum

**Comment by Quy** [comment]
Please post to Joomla Forum for assistance. https://forum.joomla.org/

**Comment by fredsotier** [comment]
!!! RESOLVED !!!

The problem is solved, it was from my code.
I beg your pardon.
