### ISSUE TITLE
Search/Finder and CustomFields

### ISSUE THREAD

**Issue by BPBlueprint** [joomla/joomla-cms#37968]
### Steps to reproduce the issue
1. Have an article with CustomField Type text, editor or textarea
2. make sure the CustomField is set to SEARCHABLE at CustomField-options
3. enter your search-string (e.g. "Hulk") into the CustomField in your article and save the article
4. start search-index
5. in frontend search for "Hulk" at Joomla!-Search

### Expected result
the article which has "Hulk" in the CustomField is found by Joomla!´s search

### Actual result
the article is NOT found

### System information (as much as possible)
Joomla! 4.2.0-alpha3-dev

### Additional comments
after indexing the word "Hulk" is liste at the search-index in backend, but no results after searching in frontend

Maybe it belongs to this PR?
https://github.com/joomla/joomla-cms/pull/36747

**Comment by joomdonation** [comment]
Could you please update to latest 4.2.0 (beta 1 or nightly build), then try again ? I just tried and it worked well for me.

**Comment by BPBlueprint** [comment]
I would, but cannot find beta 1. 
Even via Joomla!-backend I cannot find this version.

**Comment by HusiBT** [comment]
I tested 4.2.0 beta 1 -> it works!

**Comment by joomdonation** [comment]
Great. As it is working as expected, I'm closing this issue.
