### ISSUE TITLE
Mitigate information disclosure on profile edit form

### ISSUE THREAD

**Issue by alexandreelise** [joomla/joomla-cms#37969]
### Is your feature request related to a problem? Please describe.

When you are on edit profile page want to prevent leaking information when showing oteps backup codes.

### Describe the solution you'd like

Add a details/summary to show/hide on demand

### Additional context

I did a pull request addressing this feature

**Comment by richard67** [comment]
@alexandreelise I think I have explained you already in past that it does not need to create an issue when creating a pull request.

**Comment by richard67** [comment]
Closing as having a pull request. See #37970 .

**Comment by alexandreelise** [comment]
Hi @richard67 I thought I needed to create an issue as in the pull request template it still requires an issue number. Maybe someone should remove this requirement in the template as it is misleading. I tried to strictly follow the rules and the procedure. Next time i'll not do an issue. Thanks for reminding Richard.
