### ISSUE TITLE
Subform form field can only can be dragged when pointing directly to icon [firefox]

### ISSUE THREAD

**Issue by retromore** [joomla/joomla-cms#37974]
### Steps to reproduce the issue

This is probably narrow use case but still: 
Create some subform field type items in module/component
Drag the item up and down grabbing by the drag button

### Expected result

Item should be draggable when pointing to the whole button

### Actual result

Item drags only when pointing directly to arrows icon.
Works as expected in Chrome but not in Firefox

https://user-images.githubusercontent.com/9862634/171925766-a88a8f5b-81be-4f11-bb17-8ffdeebcded7.mp4

### System information (as much as possible)

php 7.4.3
Joomla 4.1.4
browser: Firefox 102.0b3
(works as expected in chrome)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39576 . Thanks in advance.
