### ISSUE TITLE
aggiornamento alla versione 414

### ISSUE THREAD

**Issue by Maurocanonico** [joomla/joomla-cms#37985]
### Steps to reproduce the issue
durante l'aggiornamento alla versione 414 il sistema ha dato un anomalia su 3 tabelle con strutture non aggiornate . dopo aggiornamento il template non vedeva piu il css e quindi ne il menu amministrativo ne quello del sito non funzionavano piu ma vi erano solo linee con il contenuto  html  . tramite queste linee ho aggiornato il sistema all'ultima versione  e ora funziona tutto .

**Comment by brianteeman** [comment]
google translation

> during the update to version 414 the system gave an anomaly on 3 tables with outdated structures. after updating the template no longer saw the css and therefore neither the administrative menu nor that of the site no longer worked but there were only lines with the html content. through these lines I have updated the system to the latest version and now everything works.

**Comment by richard67** [comment]
@Maurocanonico From which version did you update to 4.1.4? And please note that here English is communication language.

**Comment by Quy** [comment]
Please ask help in Joomla forum. https://forum.joomla.org/
