### ISSUE TITLE
[4.1] Custom Fields don't honor order in article

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#37986]
### Steps to reproduce the issue

create a few custom fields.
open new article creations
check field order
change order of fields
check article order is not in the order to which it was changed.

### Expected result
Order of fields in article are the same as in field list.  If the order is changed in field list, its also changed in article list

### Actual result

![fields order](https://user-images.githubusercontent.com/1850089/172029871-310b47f4-2f7b-490d-800a-4fd9ee66b668.JPG)
order was set to 
Maintence
Exterior
Interior
Safety
Entertainment
in field list.

**Comment by N6REJ** [comment]
fixed in latest patch it seems

**Comment by TLWebdesign** [comment]
after looking in the code i see it only happen to subform fields. It only gets the initial order and cid. when you move a different field it gets initial and new order sent to the saveOrder task.
