### ISSUE TITLE
[4.1.4] Chinese Traditional translation: update is always available

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#37988]
### Steps to reproduce the issue

install Chinese Traditional language

### Expected result

no update is available

### Actual result

update is always available:

<img width="158" alt="zh" src="https://user-images.githubusercontent.com/89642616/172036901-d3d927ba-1685-4b21-84ef-a39202733590.png">

### System information (as much as possible)
<img width="693" alt="sysinfo" src="https://user-images.githubusercontent.com/89642616/172036982-bd9d76ff-9b6a-4758-8a43-1794e4a2fe70.png">

### Additional comments

**Comment by brianteeman** [comment]
@tecpromotion same problem as reported yesterday with Greek. The version number in the manifest is not correct

**Comment by tecpromotion** [comment]
I sent an email to Alex Chen with instructions and a request to fix this in crowdin and then upload a new package.

@Franzwohlkoenig 
Feel free to close the issue as it cannot be solved here. Thank you very much.

**Comment by ghost** [comment]
Thanks @brianteeman and @tecpromotion for your comments, closing the issue.

**Comment by ghost** [comment]
Confirm Issue is solved. Thanks to Alex Chen.
