### ISSUE TITLE
[4.1] Repeatable custom field Subform doesn't hide empty form.

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#37984]
### Steps to reproduce the issue
Create a custom fields - text field to be used as the repeatable field.
Create a  custom fields - subform field and select your repeatable field as the field to use.  Set "Render value" to 'yes'
create an accordion article ( see attached file )  leaving one or more of the repeatable fields empty.
repeat putting something in the repeatable field.

### Expected result
When something from the repeatable fields exists the subform will show the subform. 
![image](https://user-images.githubusercontent.com/1850089/172028556-a8e55841-4466-41f3-b39b-81f901089ffe.png)

 When there are no repeatable fields it will hide that subform entry.

### Actual result
Entry still displays but with no content.
![image](https://user-images.githubusercontent.com/1850089/172028572-7e93b153-13ab-461a-9872-8e8a906eb762.png)

### System information (as much as possible)
[systeminfo-2022-06-04T23_22_15+00_00.txt](https://github.com/joomla/joomla-cms/files/8839084/systeminfo-2022-06-04T23_22_15%2B00_00.txt)

### Additional comments

The accordion is straight css/html.  No JS or other behavior altering code.
[Salesview.txt](https://github.com/joomla/joomla-cms/files/8839085/Salesview.txt)
https://pilkey.abiviahost.ca/classics/1947-chevrolet-3100-pickup#accordion4 ( this is the safety row )
Template: j51_nina - https://joomla51.com/joomla-4-templates/j51-nina-j4

**Comment by brianteeman** [comment]
Look at your static html. Of course it does what you say. There is zero code to conditionaly check if an accordion should be shown or not. 

```
				<div>
					<span class="target-fix" id="accordion4"></span>
					<a href="#accordion4" id="open-accordion4" title="open">Safety</a>
					<a href="#accordion" id="close-accordion4" title="close">Safety</a>
					<div class="accordion-content">
						{field 29}
					</div>
				</div>
```

Your code is doing exactly what you have told it to do. Please use the forum for support.

**Comment by N6REJ** [comment]
I see your point.

**Comment by brianteeman** [comment]
Best you can do simply would be to remove the margin bottom and then at least it wont show th small white area. Best would be to write conditional code

**Comment by N6REJ** [comment]
thanks, I'll look into how to do that, js is not my strong point.

**Comment by brianteeman** [comment]
it would be php not js

put an if not null statement before the slide

**Comment by N6REJ** [comment]
you can't put php ( afaik ) into the template file as tiny wipes it out when you load the template

**Comment by brianteeman** [comment]
ah - did not know it was a content template
