### ISSUE TITLE
Greek translation version error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37981]
### Steps to reproduce the issue
install greek language

### Expected result
no update is available

### Actual result
update is always available

### Additional comments
This is because the version nu,ber in the language pacakge has not been updated

**Comment by tecpromotion** [comment]
Hi @brianteeman 
I have sent Yiorgos a message asking him to fix this on crowdin and then create a new language package 4.1.4.2, as his package 4.1.4.1 also contains other bugs. You are welcome to close the issue then.

**Comment by brianteeman** [comment]
Thanks I wille let the use who reported this know.

**Comment by gfakas** [comment]
Hi @brianteeman @tecpromotion  
Sorry about that I have uploaded the correct version 4.1.4.2

**Comment by brianteeman** [comment]
That's great news. Thanks
