### ISSUE TITLE
[4.x] Italian language

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#37992]
### Steps to reproduce the issue
install italian language and set it as default for the admin. The visit the redirects component

### Expected result
no errors

### Actual result
error

### Additional comments
the problem is cause by a missing letter s in a language string. The correct string is

`COM_REDIRECT_BATCH_TIP="Inserisci l'URL scaduto (obbligatorio) con un nuovo URL (facoltativo) separato da %1$s(es. vecchio-url %1$snuovo-url). Ciascuna linea una voce!"`

cc @tecpromotion

**Comment by brianteeman** [comment]
reference https://forum.joomla.org/viewtopic.php?f=808&t=994218&p=3661757#p3661757

**Comment by tecpromotion** [comment]
> reference https://forum.joomla.org/viewtopic.php?f=808&t=994218&p=3661757#p3661757

Thanks @brianteeman 

I added in the forum that the bug can best be fixed directly in Crowdin.

Then the proofreader gets the information directly and can make it available directly with a new package if necessary.

But I will also write an email to Giovanni right away.

**Comment by jeckodevelopment** [comment]
There are a lot of mistakes in the Italian translation. I fixed some of them in Crowdin, but can't see them merged in the Italian package.
