### ISSUE TITLE
Safe as copie published, which means that we inevitably have two posts online with identical content, which a content manager has to correct each time.

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#37996]
### Steps to reproduce the issue

"Save as copy" an article

### Expected result

Joomla creates a copy of the post and sets it to status **unpublished.**

### Actual result

Joomla creates a copy of the post and sets it to status **unpublished**.

### System information (as much as possible)

J 4.1.4

**Comment by richard67** [comment]
@hytsch The actual and the expected result are exactly the same in your description. Either one is wrong.

**Comment by chmst** [comment]
Joomla sets the copy to pubished which is wrong imho. https://github.com/joomla/joomla-cms/issues/37351

**Comment by richard67** [comment]
> Joomla sets the copy to pubished which is wrong imho. #37351

The issue points to a PR which claims to solve it.

Closing as having a pull request.

Please test #37354 . Thanks in advance.
