### ISSUE TITLE
Sample data error

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#38015]
### Steps to reproduce the issue
Install Joomla 4.1.4
Install sample data

### Expected result
Sample data is installed

### Actual result
Error shows 
"There is an error in a sample data plugin. Response is invalid."

and only part of the sample data is installed

### System information (as much as possible)
Database Type 	mysql
Database Version 	8.0.29
Database Collation 	utf8mb4_unicode_ci
Database Connection Collation 	utf8mb4_0900_ai_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	Yes
PHP Version 	8.1.7
Web Server 	Apache/2.4.46 (Win64) PHP/8.1.7 mod_fcgid/2.3.10-dev

**Comment by chmst** [comment]
see also: (https://github.com/joomla/joomla-cms/issues/37663)

**Comment by Webdongle** [comment]
Closed in favour of #37663

**Comment by richard67** [comment]
Hmm, testing sample data should not be available on a stable version, so I assumed this issue here is about blog sample data and so not related to the other issue.

@Webdongle What kind of sample data have you tried to install? Blog? Or testing?

**Comment by brianteeman** [comment]
@richard67 of course its related. Maybe its time for another coffee

**Comment by Webdongle** [comment]
Blog data.  There is no testing sample data.  There is no 'Learn Joomla' sample data either

**Comment by richard67** [comment]
So I don't think this issue here should have been closed in favour of the other one.

**Comment by chmst** [comment]
I assumed  the testing sample data as you are experienced with Joomla installations. 
I am installing blog sample data frequently and never have problems. 

Did you install on a new installation or had you already some content? Which part of sample data was added to your system?

**Comment by brianteeman** [comment]
So why did you close this @Webdongle as its nothing to do with the other issue

**Comment by Webdongle** [comment]
Because I thought the error message "There is an error in a sample data plugin. Response is invalid." was related to the same plugin.

It was a virgin install of Joomla and there was no other data when I tried to install Blog sample data

**Comment by chmst** [comment]
@Webdongle as I cannot replicate this error on my environments: Could you repeat it and watch the console? Your php Version 8.1.7 is newer than mine.

**Comment by Webdongle** [comment]
Watch the console for what?

**Comment by chmst** [comment]
![grafik](https://user-images.githubusercontent.com/1035262/174408708-d18fde7e-2b64-413e-8b5a-f3231e3d170b.png)

For the error message, like in this screen where i have simulated an error.

**Comment by Webdongle** [comment]
![console01](https://user-images.githubusercontent.com/1115202/174428503-8ef24b47-e6c8-485f-979f-ca3aaf78d55c.JPG)
A second attempt
![console02](https://user-images.githubusercontent.com/1115202/174428583-5d9097c7-4d18-4de5-a34b-7a622df16269.JPG)

**Comment by richard67** [comment]
@Webdongle And you are not able to check the error console of your browser’s developer tools as requested by @chmst ? I can’t really believe that.

**Comment by Webdongle** [comment]
I did and the output was empty.  See the screenshot.

**Comment by brianteeman** [comment]
No errors for me

![image](https://user-images.githubusercontent.com/1296369/174451003-ed202388-cd08-49e9-b8a5-b66a7417a6b4.png)

**Comment by chmst** [comment]
@Webdongle it is not possible to repeat the installation of blog sample data, this would make dupicates. 

Could you make a fresh empty database and the repeat? And see what is in the Tab XHR where we get server responses? 
![grafik](https://user-images.githubusercontent.com/1035262/174451064-66c616b5-8fc1-4bb5-b0f7-3a1600692f3f.png)

I keep installing blog sample data  in my countless test installations, but never have a problem. There must be something special in your environment.

**Comment by Webdongle** [comment]
The first image was from a clean install
![console01](https://user-images.githubusercontent.com/1115202/174459481-201cce53-69e6-4a96-bee7-f3a18456fd35.JPG)

The second image was after clicking the install a second time
![console02](https://user-images.githubusercontent.com/1115202/174459527-5c693c00-0baa-4322-bd33-c04d5e197dff.JPG)

When the second attempt was made the the 1/4 red line should not appear.  In any case the first image was a clean install and first attempt to install sample data.

In both cases no output in the console.  


I have installed Joomla many times and know to use fresh install to fresh database.

This only happens on wamp
Database Type mysql
Database Version 8.0.29
Database Collation utf8mb4_unicode_ci
Database Connection Collation utf8mb4_0900_ai_ci
Database Connection Encryption None
Database Server Supports Connection Encryption Yes
PHP Version 8.1.7
Web Server Apache/2.4.46 (Win64) PHP/8.1.7 mod_fcgid/2.3.10-dev

It doesn't happen with wamp 
PHP Built On 	Windows NT LAPTOP-U0DC46MD 10.0 build 19044 (Windows 10) AMD64
Database Type 	mysql
Database Version 	5.7.31
Database Collation 	utf8mb4_unicode_ci
Database Connection Collation 	utf8mb4_general_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	No
PHP Version 	8.0.9
Web Server 	Apache/2.4.46 (Win64) PHP/8.0.9 mod_fcgid/2.3.10-dev
WebServer to PHP Interface 	apache2handler 

Also with PHP Version 	8.0.9 there is output in the console.  Must be a glitch in PHP Version 8.1.7 or at least the wamp PHP Version 8.1.7 that I have?

**Comment by richard67** [comment]
@Webdongle Could you check if this change fixes it for you? https://github.com/joomla/joomla-cms/commit/7ede54a2398b17a88acd153beaf0ec549a47a4df

**Comment by Webdongle** [comment]
What is the pull ID so I can use Joomla patch tester?

In the mean time I tried with Chrome which does display console output
This is the error shown prior to attempting to install sample data and after the fail

![console03](https://user-images.githubusercontent.com/1115202/174495694-a565f001-0e51-4402-922f-4036eb61eea0.JPG)
![console04](https://user-images.githubusercontent.com/1115202/174495797-11d8dab8-5b2d-4679-b6bf-a51fb91f9207.JPG)

The DevTools fail to load error shows with both of the settings shown previously

**Comment by richard67** [comment]
> What is the pull ID so I can use Joomla patch tester?

@Webdongle There was no pull request, the change was committed directly. It’s a small change which can be applied with an editor, but it seems there are more issues with sample data and PHP 8.1.

**Comment by richard67** [comment]
Possibly an issue with PHP 8.1 only, see also https://github.com/joomla/joomla-cms/commit/7ede54a2398b17a88acd153beaf0ec549a47a4df#commitcomment-76467354 .

**Comment by brianteeman** [comment]
fyi my test above was with php 8.1.6

**Comment by Webdongle** [comment]
So it works with php 8.1.6 but not with php 8.1.7 which is the current stable version https://www.php.net/downloads.php

**Comment by brianteeman** [comment]
tested again with no problem on php 8.1.7

![image](https://user-images.githubusercontent.com/1296369/174507614-04c4fee0-95d1-4e75-9c93-d19b9bdc61bc.png)

**Comment by brianteeman** [comment]
> In the mean time I tried with Chrome which does display console output

This is not the view we are asking for. As shown in the screenshot in my last post it is the network tab not the console tab and then filtered by selecting the Fetch/XHR.

This must be opened before you click on the sample data plugin

**Comment by Webdongle** [comment]
Must be a problem with my wamp's php?  I updated wamp from https://wampserver.aviatechno.net/

**Comment by brianteeman** [comment]
I doubt that very much. If you could please provide the output of the network tab it would really help.

**Comment by Webdongle** [comment]
Just doing it as you were posting.  btw what mysql did you test with?
![console05](https://user-images.githubusercontent.com/1115202/174558397-e3c1c0db-94f3-4d4a-91a5-fd5eb073ab9e.JPG)

And with Chrome
![console06](https://user-images.githubusercontent.com/1115202/174560329-876794bc-8c90-40cd-a9d9-5d3cc285fdd8.JPG)

**Comment by Webdongle** [comment]
@brianteeman 
Are those the screen shots that are being requested?  and Are they helpful?

**Comment by chmst** [comment]
Not for me, sorry. 
If I am working with sample data, I use to look at the XHR tab of the console which shows all requests and their responses as you can see here  (https://github.com/joomla/joomla-cms/issues/38015#issuecomment-1159279504)

Could you please check if something was stored in your database? The first step stores a few tags. 

Then IF com_fields are enabled, it stores custom fields. 

Could you check if tags are stored in your database? And maybe check if you have disabled components?

**Comment by Webdongle** [comment]
Sorry don't understand what tables you want me to look for and what records in them

**Comment by chmst** [comment]
I could not replicate this error in many new installations. And we have no other issue like yours. @Webdongle is this still an issue or can we close it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38015">issues.joomla.org/tracker/joomla-cms/38015</a>.</sub>

**Comment by Webdongle** [comment]
If nobody can replicate the error then it needs to be closed

**Comment by domcotec** [comment]
@Webdongle Do you have YOOtheme Pro installed?
I get the same error and I think it's a yootheme problem here.

**Comment by Webdongle** [comment]
> @Webdongle Do you have YOOtheme Pro installed? I get the same error and I think it's a yootheme problem here.

No standard Joomla install with Cassiopeia.
