### ISSUE TITLE
Client-side form validation.

### ISSUE THREAD

**Issue by Disaron** [joomla/joomla-cms#3801]
1. If exists two or more forms with fields having similar names, client-side validation repeat twice (or more if exists more then two fields) field name in error message.
2. If field adding dinamicaly (with jQuery, for example) field label does not hinting when field validation is invalid.

Since Joomla! 3.3.0

**Comment by spignataro** [comment]
Every field on a page should have their own unique ID therefore the issue would not exist. All of the Joomla! fields that I have checked are all unique and even if I put similar forms on the page I am still able to submit (they still have their own unique ID). 

I suggest that this issue be closed unless further information is provided.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3801">issues.joomla.org/joomla-cms/3801</a>.</sub>

**Comment by roland-d** [comment]
Hello @Disaron 

Thank you for your contribution.

The last comment here was on 19th July. So the question is, Is this issue/pull request still valid?
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3801">issues.joomla.org/joomla-cms/3801</a>.</sub>

**Comment by roland-d** [comment]
@Disaron Since no reply has been received for more than 4 weeks, I am closing this issue. If you want to follow up later, feel free to open the PR. Thank you for your contribution.
