### ISSUE TITLE
Backend - User: Cannot choose ONE User when logged in as NOT SuperAdministator

### ISSUE THREAD

**Issue by BPBlueprint** [joomla/joomla-cms#38021]
### Steps to reproduce the issue
1) Create at least THREE users via Backend. 
1st user is SuperUser named "admin"
2nd user is Manager namend "manager"
3rd and more users are Manager or just Registered User "manager2" "user1" "user2" ...

2) Login at backend with User 2 (= Administrator)

3) Go to Manage Users

4) Try to check ONE user with checkbox (first user SuperUser cannot be selected, cause of less rights)

### Expected result
this ONE user is selected

### Actual result
always TWO users are selected

### System information (as much as possible)
Joomla! 4.1.4

### Additional comments
Seems that the problem is caused by the not editable SuperUser, when it is on top of user-list. When it´s at the bottom of the list, no problem.

**Comment by HusiBT** [comment]
![screen shot 2022-06-09 at 08 58 41](https://issues.joomla.org/uploads/1/10fe43c12e54a28e79107795babd96ef.jpg)
![screen shot 2022-06-09 at 08 58 58](https://issues.joomla.org/uploads/1/f1cc9bf9b19e6e2a968639a748b1e090.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38021">issues.joomla.org/tracker/joomla-cms/38021</a>.</sub>

**Comment by chmst** [comment]
Confirmed.

![screen shot 2022-06-09 at 12 00 26](https://issues.joomla.org/uploads/1/b9b4a93ec24bcec11acc12586764aeb2.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38021">issues.joomla.org/tracker/joomla-cms/38021</a>.</sub>

**Comment by richard67** [comment]
Do we have the same issue on latest 3.10.x versions, too? Or can we be really sure that it’s a J4 only issue? Am off desk so can’t check that myself now. But someone should check that.

**Comment by chmst** [comment]
Only J4

**Comment by brianteeman** [comment]
The script is completely different in j4

**Comment by wilsonge** [comment]
Well this one was a nightmare to fix. But here's an attempt at a patch https://github.com/joomla/joomla-cms/pull/38146
