### ISSUE TITLE
Deprecated warnings in com_menus and Language

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#38032]
### Steps to reproduce the issue

I want to add an own Administrator Menu and use a preset.

Go to Menu - manage
New menu: enter a name and choose "Alternative Menu Preset"
Save and Close 
A new menu is on the menus view

Open the list of menu items

click the first item (home dashboard) 

### Actual result

![grafik](https://user-images.githubusercontent.com/1035262/173196050-0acacbc4-2bc1-4b15-a585-c3be00af78ae.png)

### System information (as much as possible)
win11, xampp, php 8.1.5

**Comment by brianteeman** [comment]
Confirmed on php 8.1

**Comment by brianteeman** [comment]
There are two different issues here

The first is that there is a bug in the preset and it is not using the correct value for the menu item type #38042)

The second is that in php 8.1 the bug above results in the deprecation errors.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38042 . Thanks in advance.

**Comment by brianteeman** [comment]
Please re-open. My pr only resolves part of the issue

**Comment by richard67** [comment]
> Please re-open. My pr only resolves part of the issue

@brianteeman Then please note that somehow in your PR, e.g. by changing the `Pull Request for Issue #38032 .` to `Pull Request for Issue #38032 (part).` or something like that.

**Comment by brianteeman** [comment]
I did write that above here but have now added the word partial there

**Comment by chmst** [comment]
Please test https://github.com/joomla/joomla-cms/pull/38081.  Closing as now both warnings are resolved.
