### ISSUE TITLE
[4.1] Issue on the check boxes of the extensions update list

### ISSUE THREAD

**Issue by impressionestudio** [joomla/joomla-cms#38035]
### Steps to reproduce the issue
Go to the Extensions Update having one item with the mark "**The Download Key is missing**" and at least one item after it. When selecting the item with the mark "The Download Key is missing" or the items after this, then the checkboxes being clicked, are affecting the sibling checkboxes.

### Actual result
Please see the following video to understand easier: 
https://demo.impression-estudio.gr/_issue-tracker/issue-on-extension-update-checkbox-list.mp4

### System information (as much as possible)
Joomla version: 4.1.4

**Comment by brianteeman** [comment]
Issue confirmed

There is a js error

> Uncaught TypeError: Cannot read properties of undefined (reading 'checked')
    at t.onRowClick (multiselect.min.js?a78c7c2184ee83021253d01ce4a5da167199f3c0:1:1139)
onRowClick @ multiselect.min.js?a78c7c2184ee83021253d01ce4a5da167199f3c0:1

I am assuming that the problem is that when the checkbox is removed (because of the missing key) then the onrowclick should also be disabled

**Comment by Quy** [comment]
Fixed #38146
