### ISSUE TITLE
[4.2] [Cassiopeia] Different sizes of login buttons and WebAuthn

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#38031]
### Steps to reproduce the issue
Enable the **System - WebAuthn Passwordless Login** plugin. Refer to the frontend to the site separately using the HTTP and HTTPS protocols.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/173192361-553d62ff-9012-4807-bdc6-4520de1ccc48.png)

### Additional comments
I don’t know how to better mark the buttons, but at the moment there is a certain dissonance.

Among other things, we need to remove the wild `mt-4` padding on the `<button>`.

**Comment by brianteeman** [comment]
Is this what you want?

![image](https://user-images.githubusercontent.com/1296369/173449907-89707a64-01d5-414f-b15a-f06c0dae8a52.png)

**Comment by Kostelano** [comment]
Yes, it looks much better in my opinion. If we are talking about a couple of buttons.
