### ISSUE TITLE
Scheduled Article Update

### ISSUE THREAD

**Issue by pefraba** [joomla/joomla-cms#38046]
### Feature request:
I would very much like to be able to schedule the update of an article content.

### Expected result
In Joomla! it is possible to schedule publishing/unpublishing (publish_up/publish_down) of the whole article, and -- per feature request #13596 (and pull request #25979) -- it is (or soon will be) possible to schedule featured/unfeatured (featured_up/featured_down). A scheduled update of an article content (or a category description) however, is not possible.

I imagine this can be done using the article versions: I edit the most recent article version and switch its publication (using a newly introduced switch button) from 'immediately' to 'scheduled'. When 'scheduled' is selected then an additional time field is displayed where I can enter date and time of the update publication.

Using article versions, the range of scheduled updating does not have to be limited to article content, but to me scheduled content update is the most important aspect of it.

### Additional comments
This is my first feature request. I hope I do comply with established standards.
I wasn't sure what to write in the 'Build' field. So I copied 'master' from feature request #13596.

**Comment by WoodyF4u** [comment]
Could be interesting.
But scheduling an article was already possible in Joomla.
Just not scheduling different versions of the same article.
But is that useful?
Wouldn't it be better to create a new article with Save & Copy and then schedule that article?
I think you'll get the same result.

**Comment by pefraba** [comment]
Thanks for your thoughts :-) . Your proposed method only works under very specific conditions. If you switch articles in a blog then a) external search engine links may no longer work, and b) the "updated" article may no longer appear at the same position, depending on the sorting order of that blog. On the other hand, if you switch articles that are uniquely linked to a menu item (a menu item that leads to a single article) then you also have to update the selected article in that menu item, but this cannot be done by scheduled automation.

Additionally, let me explain why I need to update articles on schedule in the first place: On my employer's website [grosserrat.bs.ch](https://grosserrat.bs.ch/ "grosserrat.bs.ch") (the parliament of the city and canton Basel, Switzerland) there are some article-pages that need to be updated at a specific time, namely after elections when the presidency changes or when the whole legislative body changes. These changes have to happen at specific dates and times, irrespective of weekends or nightly hours, e.g. midnight between saturday and sunday, my favourite ;-) .

So this is why I would welcome very much to be able to schedule an article update.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38046">issues.joomla.org/tracker/joomla-cms/38046</a>.</sub>

**Comment by brianteeman** [comment]
>  If you switch articles in a blog then a) external search engine links may no longer work 

Unless you change the title and alias then there should be no problem and you wouldnt be changing that anyway

> the "updated" article may no longer appear at the same position, depending on the sorting order of that blog. 

The dates can all be edited so for example you can make the "created date" the same.  And sorting by title is not an issue

> On the other hand, if you switch articles that are uniquely linked to a menu item (a menu item that leads to a single article) then you also have to update the selected article in that menu item, but this cannot be done by scheduled automation.

In Joomla 4 you can now set menu items to start and finish publishing

> Additionally, let me explain why I need to update articles on schedule in the first place: On my employer's website [grosserrat.bs.ch](https://grosserrat.bs.ch/) (the parliament of the city and canton Basel, Switzerland) there are some article-pages that need to be updated at a specific time, namely after elections when the presidency changes or when the whole legislative body changes. These changes have to happen at specific dates and times, irrespective of weekends or nightly hours, e.g. midnight between saturday and sunday, my favourite ;-) .
> 
> So this is why I would welcome very much to be able to schedule an article update.
> 

And should all be achievable right now in joomla 4.

**Comment by pefraba** [comment]
WOW!! Thank's a lot, you make some very good points, but...

> Unless you change the title and alias ...

If the blog article address includes the article ID, as is the case in our blogs, then switching articles will break the link when coming from a search engine.
Then why include the ID, you may ask. Because using the ID prevents broken links after changing (correcting) the title and alias.

> The dates can all be edited so for example you can make the "created date" the same. And sorting by title is not an issue

True, except for 'Most Hits' and 'Least Hits', but I don't use these, and I could copy the 'hits' value in the database.
I first thought, erroneously, that there's a sorting by ID but there isn't.

> In Joomla 4 you can now set menu items to start and finish publishing

That's great news. Unfortunately, we do not and cannot use J!4 just yet because some third party extension upgrades are not yet available.
And I wonder: How can there be two menu items with the same title and alias and parent coexisting, different only in selected article and publishing date?
Please, _brianteeman_, can you confirm that in J!4 this is possible? Because in J!3 it isn't.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38046">issues.joomla.org/tracker/joomla-cms/38046</a>.</sub>

**Comment by pefraba** [comment]
@brianteeman, sorry to bother you but if you would be so kind, please review my reply regarding two menu items with identical titles and aliases and parent. Is that really possible in J!4? Or how do you suggest I switch the article connected to a specific menu item? Thanks a lot for sharing your knowledge and experience :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38046">issues.joomla.org/tracker/joomla-cms/38046</a>.</sub>

**Comment by brianteeman** [comment]
I just checked one of my joomla 3 sites where I have a menu link /election and the contents of this link change over time.

The _trick_ was to use the category blog menu item type and then to point that at a category called election.
In that category there are three articles (without readmore) which are published/unpublished in sequence so that there is only one article published at any time
- Election Announcement
- Election Candidates
- Election Results

An alternative to this if you need to have the /election displaying different articles from different categories was to use featured articles or tagged articles.

**Comment by pefraba** [comment]
Ah! That's a clever one, indeed. So you don't use single article menu items at all. Yes, in a blog without readmore this is possible. And since there's only one article visible at any given time this can look as if there were only one article at all when in fact there are two or more, one replacing the other perfectly. Thank you very much for pointing this out.

So the only (minor) shortfall remaining would be the number of hits per article. But this I can update manually in the database by copying respective values from unpublished to published article versions.

So then, my request seems to be unnecessary after all. How do I withdraw or cancel my request?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38046">issues.joomla.org/tracker/joomla-cms/38046</a>.</sub>

**Comment by alikon** [comment]
simply close the issue

**Comment by pefraba** [comment]
Easier said than done, I'm struggling.

Do I have to go over to GitHub to do that?
https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue

Should be possible here, too, but how?

Sorry, I'm a Newbie :-/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38046">issues.joomla.org/tracker/joomla-cms/38046</a>.</sub>

**Comment by alikon** [comment]
i'll do it for you 

for the  next time look at the close button
![image](https://user-images.githubusercontent.com/181681/174781158-6aaac1d3-85a8-4699-a839-10016f91831d.png)

**Comment by pefraba** [comment]
Thanks alikon, kind of you :-)
You used the GitHub-Page, right?

I was writing on this Joomla!-page
https://issues.joomla.org/tracker/joomla-cms/38046
and here I cannot find such a nice button ;-)
![screen shot 2022-06-21 at 10 51 04](https://issues.joomla.org/uploads/1/f5e5bd531771be4c52b6cfa1fae956c1.png)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38046">issues.joomla.org/tracker/joomla-cms/38046</a>.</sub>
