### ISSUE TITLE
Media Manager - Additional Data - Popup

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#38059]
### Steps to reproduce the issue

![screen shot 2022-06-14 at 15 43 03](https://issues.joomla.org/uploads/1/f8564111ecf955329881f679c62c8dc5.png)

### Expected result
Set the media manager so that it doesn't open automatically when you select an image to insert.
To make it editable on a mobile.

### Actual result
Anyone know how to turn that off?
Why aren't the labels just placed discreetly above the fields, but fill up half the width?

### System information (as much as possible)
J 4.1.4 (or J 4.1.5-rc2-dev)

### Additional comments
TinyMCE 5.1.0.3

**Comment by brianteeman** [comment]
This is nothing to do with tinymce

**Comment by ChristineWk** [comment]
ah, I think it's the same in JCE (?) (After temporarily switching editors for testing purposes) 

But when I go to Insert Image:

in TinyMCE, I get:
![screen shot 2022-06-14 at 16 27 44](https://issues.joomla.org/uploads/1/a1056d7183221137a868e453fdefba33.png)

similar to #37054

in the JCE, it's OK:
![screen shot 2022-06-14 at 16 28 23](https://issues.joomla.org/uploads/1/58028db007251716c0a91ac41f166d05.png)

Coming back to the issue title, what is the cause?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38059">issues.joomla.org/tracker/joomla-cms/38059</a>.</sub>

**Comment by drmenzelit** [comment]
The popup is generated by the plugin editors-xtd / image<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38059">issues.joomla.org/tracker/joomla-cms/38059</a>.</sub>

**Comment by ChristineWk** [comment]
Ah, found it now under: Plugins > Button - Media:

> Displays a button to insert media into an editor area. Displays a popup allowing you to configure the media's properties and upload new media files.

Hv changed (removed TinyMCE) from Issue title.

**Comment by brianteeman** [comment]
I'm confused as to what it is you are asking for

**Comment by chmst** [comment]
I see it as a request to make the labels smaller and less prominent. Especially for Image description it is weird that the label takes so much place and make the input fields so small. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38059">issues.joomla.org/tracker/joomla-cms/38059</a>.</sub>

**Comment by ChristineWk** [comment]
@brianteeman 
See Actual and Espected Result. Thank you.

**Comment by brianteeman** [comment]
> Set the media manager so that it doesn't open automatically when you select an image to insert.

you mean you dont want the additional data to open? If so then thats not going to happen as it would prevent you from setting alt descriptions etc
