### ISSUE TITLE
[4.3] Media Manager SVG File

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#38068]
### Steps to reproduce the issue
Upload svg file as logo in cassiopeia.
A message appears: An error has occurred.

### Expected result

Solution: Under Media you have to allow svg in several places
file types; image/svg+xml
Valid image file extensions: svg
Allowed extensions: svg

### Actual result
If you do not enter all types (see above). A message appears: An error has occurred.

### Additional comments

Feature Rquest: Wouldn't it make sense to offer such information directly where the problem can occur?
Eg by displaying a small question mark icon and behind it the information that you first have to set e.g. svg "on" at this point or that.
Thank you.

**Comment by chmst** [comment]
There is indeed some need for information and documentation. Maybe we can add information for cassiopeia?
@drmenzelit

**Comment by brianteeman** [comment]
The problem is that there is a bug and the correct error message is not being displayed.

**Comment by ChristineWk** [comment]
> The problem is that there is a bug and the correct error message is not being displayed.

would a PR be possible?

**Comment by N6REJ** [comment]
I don't know if this is related or not, but I just tried to  upload this image and it was refused even though I have everything set correctly
![collabnet-versionone-logo](https://user-images.githubusercontent.com/1850089/179146084-8f1b21f1-802e-4903-a9e5-e5b8f5e1eee0.svg)
using tiny I was able to user <img src=> to include it in the article however.
![image](https://user-images.githubusercontent.com/1850089/179146385-830c0769-04f9-441a-8edf-6a601dabe8e5.png)

**Comment by obuisard** [comment]
Indeed, there is a problem with SVGs here. Even when the allowed types and mime types are set correctly in the media manager's global configuration (like stated in the previous comment by @N6REJ), it is impossible to add SVGs to the Media manager (via uploads or drag-and-drop). Once the files are added to the images folder via FTP, for instance, the files are visible (without a preview, which is expected for now) and selectable in the article manager or Cassiopeia. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38068">issues.joomla.org/tracker/joomla-cms/38068</a>.</sub>

**Comment by N6REJ** [comment]
@Quy can you tackle this?

**Comment by ChristineWk** [comment]
@obuisard: Thanks for your intervention

**Comment by brianteeman** [comment]
@obuisard that is not my experience as shown in this video https://www.youtube.com/watch?v=U7hHYpuNqsg&ab_channel=LearnJoomla4

**Comment by obuisard** [comment]
Thank you, Brian @brianteeman. It confirms that it used to work under Joomla 4.0.4. But my tests under Joomla 4.1.5 and 4.2.0 are failing.

**Comment by obuisard** [comment]
I am doing more testing on this.
My findings so far:

In Joomla 4.0.4, SVG files can be uploaded EXCEPT if the files start with an XML comment. Once the comment has been removed or moved inside <svg>, it can be uploaded. This kind of comment is usually added by generators of SVG files.

In Joomla 4.1.5, no file can be uploaded unless they are 'simple' XML files (containing <svg> and the optional xml declaration). The ones containing additional namespaces or DOCTYPE cannot be uploaded.

In Joomla 4.2.0, no SVG file could be uploaded on my test sites.

So, I see regression.

**Comment by brianteeman** [comment]
Sounds like a issue with the security SVG filter

**Comment by obuisard** [comment]
We need to document what is a clean SVG and why some SVG files may be denied upload. SVG files need to be sanitized to avoid all kinds of security issues (cross-site scripting, HTML injections, denial of service - basically any possible attack related to XML documents).

**Comment by brianteeman** [comment]
Its more than that. The svg files used to test the filters when they were added do not work either

**Comment by brianteeman** [comment]
you need to roll back to when it worked and then see what has changed. I have my suspicions but its too late and I had too many beer to try

**Comment by obuisard** [comment]
Yes @brianteeman, thank you!

**Comment by obuisard** [comment]
The major difference I see is that in 4.0 the content of the files was scanned for specific html/xml tags. In more recent versions, a sanitizer is used instead (from vendor 'enshrined'). It's the same one used in Nicholas K. Dionysopoulos's plugin for Joomla 3 (https://github.com/nikosdion/joomlasvg). 

The new sanitizer checks the SVG files and returns a clean one, if necessary. The results of that operation is true or false. True means the file has been modified will all issues removed with success or it has not been edited. False means there are unresolved issues. 

It is possible to see what issues have been addressed during sanitization. However it is useless for the Joomla user and it should not be tested upon in order to determine that the file is valid or not. As long as the sanitization returns true, we should consider the file valid and move on (based on my review of the MediaHelper code in 4.2). That is what holds most of the SVG file uploads I believe.

**Comment by N6REJ** [comment]
Incase it helps here's 2 inkscape svg files.  One is in "save as inkscape svg" and the other is "save as svg"
![Bearsampp-logo-128x128](https://user-images.githubusercontent.com/1850089/185294001-2e3393bb-02d9-4ba1-81a4-54a193b08ffa.svg)
![Bearsampp-logo-inkscape](https://user-images.githubusercontent.com/1850089/185294006-2377322f-2573-4169-98b2-56bf86dade6a.svg)

**Comment by obuisard** [comment]
I am going to write a PR that fixes the messaging that appears when the upload fails.
Another PR should be created to give the option to the administrator to sanitize SVG files rather than just scanning them for issues.

**Comment by Fedik** [comment]
I have added better messenging, Please test #38536

**Comment by level420** [comment]
For joomla 4.2.4 I was not able to upload any svg image even with all settings for the media manager 

Allowed extensions: svg
Legal Image Extensions: svg
Legal MIME Types: image/svg+xml

Any progress on this issue?

**Comment by Orgoth** [comment]
For joomla 4.3.2 it is the same.

Allowed extensions: svg
Legal Image Extensions: svg
Legal MIME Types: image/svg+xml

Had to upload the files via sftp, the media manager blocks any attempt.
Message by the Manager: File can not be uploaded. "Datei kann nicht hochgeladen werden."<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38068">issues.joomla.org/tracker/joomla-cms/38068</a>.</sub>

**Comment by obuisard** [comment]
> For joomla 4.3.2 it is the same.
> 
> Allowed extensions: svg Legal Image Extensions: svg Legal MIME Types: image/svg+xml
> 
> Had to upload the files via sftp, the media manager blocks any attempt. Message by the Manager: File can not be uploaded. "Datei kann nicht hochgeladen werden."
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/38068](https://issues.joomla.org/tracker/joomla-cms/38068).

This can still happen. SVG files are checked upon upload and if there is anything in the file that is considered harmful, the file will be rejected. You need to make sure the SVG file has been sanitized before use.

**Comment by Orgoth** [comment]
> > For joomla 4.3.2 it is the same.
> > Allowed extensions: svg Legal Image Extensions: svg Legal MIME Types: image/svg+xml
> > Had to upload the files via sftp, the media manager blocks any attempt. Message by the Manager: File can not be uploaded. "Datei kann nicht hochgeladen werden."
> > This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/38068](https://issues.joomla.org/tracker/joomla-cms/38068).
> 
> This can still happen. SVG files are checked upon upload and if there is anything in the file that is considered harmful, the file will be rejected. You need to make sure the SVG file has been sanitized before use.

I have create the svg with inkscape, I have assumed, it would already be sanitized.

**Comment by Orgoth** [comment]
I tested a [SVGOMG ](https://svgomg.net/) optimized file and it worked.
Thank you very much for this hint.
It would be good if this could be described better.
Since just the message alone is not helpful at all.

Instead of this message: "File cannot be uploaded."
Would be better to add the addition that the user should check if the file is sanitized.

Some hint would be really helpful, otherwise there will be a lot more users like me who stumble across this problem and then open completely unnecessary new tickets.
It's even worse with pagebuilders like Yootheme or SPPB, where there's no feedback at all, just an empty popup.
Which suggests that there is a problem with the notification not being communicated correctly to the outside world.

Regardless, thanks again and a thumbs up from me as well for the responses.

**Comment by Quy** [comment]
> Instead of this message: "File cannot be uploaded." Would be better to add the addition that the user should check if the file is sanitized.

Please test PR #38536.

**Comment by alikon** [comment]
closing as we have pr #38536
