### ISSUE TITLE
moduleclass_sfx validation too strict

### ISSUE THREAD

**Issue by stell** [joomla/joomla-cms#38067]
### What needs to be fixed
`moduleclass_sfx ` validation too strict.

### Why this should be fixed
Saving UIkit classes like `uk-width-1-2@s` not possible.

### How would you fix it
Relax the validation.

### Side Effects expected
none

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/37542

**Comment by richard67** [comment]
Closing as duplicate report. See #37542 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38067">issues.joomla.org/tracker/joomla-cms/38067</a>.</sub>
