### ISSUE TITLE
[4.2 beta1] Error after update 4.1 -> 4.2 beta

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#38063]
### Steps to reproduce the issue
Update an installation from 4.1.0 to 4.2 beta1.

### Expected result
Update as usual

### Actual result
![grafik](https://user-images.githubusercontent.com/1035262/173686128-155b7404-22ec-4e3c-97f3-53ec58e8e6ee.png)

### System information (as much as possible)
localhost with php 8.1.5 and online with php 8.0.

**Comment by brianteeman** [comment]
can you enable debug and post the stack trace please

**Comment by richard67** [comment]
@chmst Does #38034 solve this? Please check, even if the description reads s bit different.

**Comment by chmst** [comment]
I think that #38034 is not related here. Will re-install the old environment tomorrow

**Comment by richard67** [comment]
> I think that #38034 is not related here. Will re-install the old environment tomorrow

To think is good, to know is better. Try it.

**Comment by chmst** [comment]
I thought wrong @richard67. Indeed https://github.com/joomla/joomla-cms/pull/38034 solves that . Thanky you, I close this.

**Comment by richard67** [comment]
Sometimes I am not as silly as I look like 😛
