### ISSUE TITLE
sqlsrv driver needs encrypt state in config array

### ISSUE THREAD

**Issue by DaniDuesentrieb** [joomla/joomla-cms#38076]
### Steps to reproduce the issue
Tested with php sql_srv extension 5.10.0

If you want to Connect to an unencrpyted MsSQL Server with the following connection array, a connection could not be established, because the encryption could not be set.

       $option['driver'] = 'sqlsrv'; 
        $option['host'] = 'server\\instancename, 1433';
        $option['port'] = 1433;
        $option['user'] = 'user';
        $option['password'] = 'pass';
        $option['database'] = 'DBName';
        $option['prefix'] = '';

        return JDatabaseDriver::getInstance($option);

### Expected result
In the config array there is an option "encrypt" to set the state.

       $option['driver'] = 'sqlsrv'; 
        $option['host'] = 'server\\instancename, 1433';
        $option['port'] = 1433;
        $option['user'] = 'user';
        $option['password'] = 'pass';
        $option['database'] = 'DBName';
        $option['prefix'] = '';
        $option['encrypt'] = false;

        return JDatabaseDriver::getInstance($option);

### System information (as much as possible)
Jommla 4.1.4
PHP 7.4.28
Linux Ubuntu Webserver
sql_srv extension 5.10.0

### Additional comments

In the file libraries\vendor\joomla\database\src\Sqlsrv\SqlsrvDriver.php at line 117 to 124 the config array needs the option encrypt, so the array must be change from this:

		$config = [
			'Database'             => $this->options['database'],
			'uid'                  => $this->options['user'],
			'pwd'                  => $this->options['password'],
			'CharacterSet'         => 'UTF-8',
			'ReturnDatesAsStrings' => true
		];
to this:

		$config = [
			'Database'             => $this->options['database'],
			'uid'                  => $this->options['user'],
			'pwd'                  => $this->options['password'],
			'CharacterSet'         => 'UTF-8',
			'ReturnDatesAsStrings' => true,
			'encrypt'	       => $this->options['encrypt']
		];

**Comment by richard67** [comment]
@DaniDuesentrieb Could you report this issue here https://github.com/joomla-framework/database/issues ? Thanks in advance.

**Comment by DaniDuesentrieb** [comment]
@richard67 Issue reported at https://github.com/joomla-framework/database/issues/265<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38076">issues.joomla.org/tracker/joomla-cms/38076</a>.</sub>

**Comment by richard67** [comment]
@DaniDuesentrieb Thanks.

**Comment by alikon** [comment]
closing here as has been opened at https://github.com/joomla-framework/database/issues/265
