### ISSUE TITLE
[4.2] Missing constants on installation

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#38077]
### Steps to reproduce the issue
Most likely the problem will not be reproduced, but just when installing the latest 4.2, I received errors with missing lines at the step of installing the localization pack.

They must be duplicated in the localization file when installing Joomla.

```
JLIB_INSTALLER_ERROR_DOWNLOAD_SERVER_CONNECT
COM_INSTALLER_MSG_INSTALL_INVALID_URL
```

![Screenshot_1](https://user-images.githubusercontent.com/8440661/174070297-966a31fd-99d1-412b-9425-3e36ea5b5cbb.png)

**Comment by richard67** [comment]
Should be a similar PR as #37286 before.

@Kostelano Do you think you can make a PR?

**Comment by brianteeman** [comment]
I couldnt replicate it as you expected
# [Installation in russian](https://app.tango.us/app/workflow/d36fda32-7e8d-4d11-b6ea-8ffdff62b939?utm_source=markdown&utm_medium=markdown&utm_campaign=workflow%20export%20links)



__Date:__ June 16, 2022

__Author:__ Brian Teeman

__Source:__ [Tango](https://app.tango.us/app/workflow/d36fda32-7e8d-4d11-b6ea-8ffdff62b939?utm_source=markdown&utm_medium=markdown&utm_campaign=workflow%20export%20links)

***

### 1. [Go to Joomla Installer](https://nightlky.test/installation/index.php)


### 2. Click on  Параметры сайта…
![Step 2 screenshot](https://images.tango.us/public/screenshot_3ffab03b-5e4d-486d-b475-2c39c78d1ff1.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.6015&fp-z=1.4118&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 3. Type "Site Name"
![Step 3 screenshot](https://images.tango.us/public/screenshot_d98d452d-a4ae-450b-bf8f-7ba01bc33f24.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.5667&fp-z=1.4458&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 4. Click on Параметры учетной записи 
![Step 4 screenshot](https://images.tango.us/public/screenshot_0219a7c7-f137-40e7-897c-6bc2ace20b47.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.6598&fp-z=1.4458&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 5. Type "My Full Name"
![Step 5 screenshot](https://images.tango.us/public/screenshot_935d7196-32a4-4863-804d-bdf6ed2d24c7.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.2752&fp-z=1.4458&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 6. Type "admin"
![Step 6 screenshot](https://images.tango.us/public/screenshot_bd53162f-97ab-45b4-b1dd-668d6452f613.png?crop=focalpoint&fit=crop&fp-x=0.5000&fp-y=0.4019&fp-z=1.4458&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 7. Type password
![Step 7 screenshot](https://images.tango.us/public/screenshot_7b77e0ff-1336-4f39-9e37-b8b8563b90d9.png?crop=focalpoint&fit=crop&fp-x=0.4776&fp-y=0.5275&fp-z=1.5214&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 8. Type "admin@example.com"
![Step 8 screenshot](https://images.tango.us/public/screenshot_ce6926bc-c15f-4896-ac34-17fe551e234f.png?crop=focalpoint&fit=crop&fp-x=0.4948&fp-y=0.7550&fp-z=1.4458&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 9. Click on Параметры базы данных 
![Step 9 screenshot](https://images.tango.us/public/screenshot_0b49daf1-fbb9-46f0-85a5-4b639cb7f635.png?crop=focalpoint&fit=crop&fp-x=0.4948&fp-y=0.8470&fp-z=1.4458&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 10. Type "joomla_ru"
![Step 10 screenshot](https://images.tango.us/public/screenshot_d59cff59-14df-4c4c-bed4-bda922f15dbe.png?crop=focalpoint&fit=crop&fp-x=0.4948&fp-y=0.7797&fp-z=1.4458&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 11. Type "root"
![Step 11 screenshot](https://images.tango.us/public/screenshot_5b086854-7cdf-4cde-855e-b7fb537c10cf.png?crop=focalpoint&fit=crop&fp-x=0.4948&fp-y=0.2382&fp-z=1.4458&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 12. Click on Установить Joomla 
![Step 12 screenshot](https://images.tango.us/public/screenshot_905c7de5-95d7-41ea-ac75-835b641c6b62.png?crop=focalpoint&fit=crop&fp-x=0.4948&fp-y=0.8346&fp-z=1.4458&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 13. Click on  Завершение установки…
![Step 13 screenshot](https://images.tango.us/public/screenshot_77e9099d-61c5-4151-88bf-087b1f8eb6a2.png?crop=focalpoint&fit=crop&fp-x=0.4945&fp-y=0.5448&fp-z=1.0213&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 14. Click on Установить языковые пакеты 
![Step 14 screenshot](https://images.tango.us/public/screenshot_f3cf8d82-3180-4438-b811-e78e434f5a98.png?crop=focalpoint&fit=crop&fp-x=0.4948&fp-y=0.3044&fp-z=1.4458&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 15. Check Russian
![Step 15 screenshot](https://images.tango.us/public/screenshot_6423c475-f7c2-4701-8eec-55fdbea56bf9.png?crop=focalpoint&fit=crop&fp-x=0.3073&fp-y=0.4496&fp-z=3.1015&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 16. Click on Далее…
![Step 16 screenshot](https://images.tango.us/public/screenshot_07e4601a-0427-444c-a0fd-5efbc21e0a25.png?crop=focalpoint&fit=crop&fp-x=0.4948&fp-y=0.7876&fp-z=1.4458&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 17. Click on 	Russian (ru-RU)	ru-RU
![Step 17 screenshot](https://images.tango.us/public/screenshot_3b5f4b1e-5bc7-491c-b45b-f849edc2172f.png?crop=focalpoint&fit=crop&fp-x=0.3523&fp-y=0.6822&fp-z=2.4647&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 18. Select "ru-RU"
![Step 18 screenshot](https://images.tango.us/public/screenshot_998311a1-5bee-44c2-89a2-35f721007699.png?crop=focalpoint&fit=crop&fp-x=0.3078&fp-y=0.6771&fp-z=3.1015&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 19. Select "ru-RU"
![Step 19 screenshot](https://images.tango.us/public/screenshot_969b35be-cb2d-4fe8-9a0e-b51844eda686.png?crop=focalpoint&fit=crop&fp-x=0.3078&fp-y=0.1222&fp-z=3.1015&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 20. Click on Языковые пакеты установлены. Пожалуйста, выберите язык по умолчанию для панели управления и нажмите "Установить по умолчанию".…
![Step 20 screenshot](https://images.tango.us/public/screenshot_32597245-a3ff-49f7-9dd2-dc58a62cf24b.png?crop=focalpoint&fit=crop&fp-x=0.4948&fp-y=0.2438&fp-z=1.4480&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


### 21. Click on  Открыть панель управления
![Step 21 screenshot](https://images.tango.us/public/screenshot_0434f225-97f0-48fc-b882-a0fe219b2ced.png?crop=focalpoint&fit=crop&fp-x=0.4948&fp-y=0.8582&fp-z=1.4458&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A892)


***
_[This workflow was created with Tango](https://app.tango.us/app/workflow/d36fda32-7e8d-4d11-b6ea-8ffdff62b939?utm_source=markdown&utm_medium=markdown&utm_campaign=workflow%20export%20links)_

**Comment by richard67** [comment]
@brianteeman But maybe it could make sense to add the untranslated error messages shown in @Kostelano 's screen shot to the `installation/language/en-GB/joomla.ini` file regardless of that?

**Comment by brianteeman** [comment]
For the COM_ More likely the solution is to add a string INSTL_to the installation and update the php accordingly

**Comment by richard67** [comment]
> For the COM_ More likely the solution is to add a string INSTL_to the installation and update the php accordingly

That's right.

When checking in which PHP files outside of the "administrator/components/com_installer" folder are using language stings like "COM_INSTALLER_", I find:

```
libraries/src/Console/ExtensionRemoveCommand.php
plugins/installer/packageinstaller/tmpl/default.php
plugins/installer/webinstaller/tmpl/default.php
installation/src/Model/LanguagesModel.php
layouts/joomla/installer/changelog.php
```

But we have language string with keys like "COM_INSTALLER_" only in the "com_installer" language files of the backend, and that's how it should be.

The "installation/src/Model/LanguagesModel.php" really should not use "COM_INSTALLER_" language strings.

As far as I can see it uses only that one here: https://github.com/joomla/joomla-cms/blob/4.2-dev/installation/src/Model/LanguagesModel.php#L292

So this should be changed to an "INSTL_" sting which should then be added to the "installation/language/en-GB/joomla.ini" file.

The "JLIB_INSTALLER_ERROR_DOWNLOAD_SERVER_CONNECT" should be added to the same file at the right place. 

**_And now the important question:_** Who wants to make the PR? 😄

**Comment by richard67** [comment]
If nobody else wants to make a PR, I can make one, but I want to avoid us doing duplicate work in parallel, so if someone is already working on it let me know. I'll wait a while.

**Comment by Kostelano** [comment]
> If nobody else wants to make a PR, I can make one, but I want to avoid us doing duplicate work in parallel, so if someone is already working on it let me know. I'll wait a while.

Sorry, I'm not at home at the PC, so I can't right now.

**Comment by brianteeman** [comment]
And I am at the pub

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38080 , either by code review, or if you can reproduce the error which causes the mentioned strings to be shown, do a real test. Thanks in advance.
