### ISSUE TITLE
Notice for count

### ISSUE THREAD

**Issue by uzielweb** [joomla/joomla-cms#38104]
### Steps to reproduce the issue

Install locally Joomla 4.1.2 in PHP 8.1

### Expected result

Normal installation page

### Actual result
A message is displayed in the top of the page like this bellow

_Deprecated
: Return type of Joomla\Input\Input::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in
D:\laragon\www\joomla4\libraries\vendor\joomla\input\src\Input.php
on line
149_

### System information (as much as possible)

Laragon with PHP 8.1.4, Maria DB 10.6.4 and Apache 2.4.51

**Comment by brianteeman** [comment]
Please retest with the latest released version of Joomla which is [4.1.4](https://downloads.joomla.org/)

**Comment by Quy** [comment]
Fixed in v4.1.3. See  #37502. Thanks for the report.
