### ISSUE TITLE
<supported_databases> in updates XML always results in an error (which also has wrong wording).

### ISSUE THREAD

**Issue by nikosdion** [joomla/joomla-cms#38117]
Ever since @richard67 introduced me to the 2-in-1 bug specials I only find this kind of bugs. This morning we will see that an update with `<supported_databases>` always results in an error and the error message is misleading.

### Steps to reproduce the issue

* Install an older version of an extension with `<supported_databases>` in its XML update file, e.g. https://github.com/lucid-fox/social-magick/releases/download/1.0.1/socialmagick-1.0.1.zip
* Go to System, Update, Extensions
* Click on Check for Updates

### Expected result

Update found, no warning.

### Actual result

A bunch of **misleading** warnings:

* For the extension Social Magick version 1.0.2 is available, but your current database MySQL (PDO) is not supported anymore.
* For the extension Social Magick version 1.0.1 is available, but your current database MySQL (PDO) is not supported anymore.
* For the extension Social Magick version 1.0.0 is available, but your current database MySQL (PDO) is not supported anymore.

### System information (as much as possible)

Joomla 4.1.5 on PHP 8.1 but this might be irrelevant as the issue seems to exist since #12355

### Additional comments

They say a picture is worth one thousand words. I agree:
<img width="802" alt="Screenshot 2022-06-22 at 09 29 03" src="https://user-images.githubusercontent.com/256041/174962139-57b1dd10-d09f-4c31-9bb9-279434976893.png">

In libraries/src/Updater/Adapter/ExtensionAdapter.php:159 we are trying to see if the site's database connector object's `$dbType` (all **lowercase**) matches one of the keys of the `$supportedDbs` array. However, the keys in the `$supportedDbs` array are **upppercase**. Therefore we will _never_ match a database type...

This is bug number one.

We then display the JLIB_INSTALLER_AVAILABLE_UPDATE_DB_MINIMUM message _but_ instead of reporting the database _server type_ (e.g. MySQL) we report the database _connector name_ (e.g. MySQLi or PDO MySQL). This causes the asinine and misleading messages sampled above.

This is bug number two.

#### How to fix this

For the first bug change line 159 from
```php
if (\array_key_exists($dbType, $supportedDbs))
```
to
```php
if (in_array(strtolower($dbType), array_map('strtolower', array_keys($supportedDbs))))
```

For the second bug, change lines 167 to 174 from
```php
								$dbMsg = Text::sprintf(
									'JLIB_INSTALLER_AVAILABLE_UPDATE_DB_MINIMUM',
									$this->currentUpdate->name,
									$this->currentUpdate->version,
									Text::_($db->name),
									$dbVersion,
									$minimumVersion
								);
```

to

```php
								$dbMsg = Text::sprintf(
									'JLIB_INSTALLER_AVAILABLE_UPDATE_DB_MINIMUM',
									$this->currentUpdate->name,
									$this->currentUpdate->version,
									Text::_('JLIB_DB_SERVER_TYPE_' . $dbType),
									$dbVersion,
									$minimumVersion
								);

```

and create the lang strings JLIB_DB_SERVER_TYPE_MARIADB, JLIB_DB_SERVER_TYPE_MYSQL, JLIB_DB_SERVER_TYPE_POSTGRESQL, JLIB_DB_SERVER_TYPE_ORACLE, JLIB_DB_SERVER_TYPE_SQLITE, JLIB_DB_SERVER_TYPE_MSSQL which are far cleaner than the existing, unprefixed ones.

### Credits

Hat tip to the ever keen-eyed @woluweb who noticed these warnings and reported them to a repository I help with.

**Comment by richard67** [comment]
> Ever since @richard67 introduced me to the 2-in-1 bug specials

@nikosdion When was that or what does it refer to?

**Comment by nikosdion** [comment]
@richard67 A few weeks ago, when I stumbled into a bug while fixing another. It was an off-hand comment but now everything I do, I stumble into these 2-bugs-for-1 specials 🤣

**Comment by brianteeman** [comment]
Buy one get one free

**Comment by richard67** [comment]
@nikosdion Ahh, now I remember. Will you do the PR for this issue?

**Comment by nikosdion** [comment]
@richard67 Yup! Let me upgrade a few sites I was too dead tired to upgrade last night and then I'm on it.

@brianteeman An idea for a new t-shirt is slowly forming in my head...

**Comment by brianteeman** [comment]
"There are no bugs without u"

**Comment by nikosdion** [comment]
OMG, Brian, now I have to convince Crystal to make it into a cheesy to-shirt design!

**Comment by nikosdion** [comment]
I did the PR https://github.com/joomla/joomla-cms/pull/38121 against Joomla 4.2 since I am adding language strings. Even though they don't need to be translated (they are product names) I believe the right way to do it is to put them in the upcoming version that's looming closer every day.

**Comment by richard67** [comment]
Closing as having a pull request. See #38121 . Thanks @nikosdion .
