### ISSUE TITLE
[4.2] Cannot Install Languages

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38110]
### Steps to reproduce the issue
Try to install a language

### Expected result
list of available languages is displayed

### Actual result
Notice: Trying to get property 'extension' of non-object in C:\laragon\www\j4\administrator\components\com_installer\src\Model\LanguagesModel.php on line 158

Warning: Invalid argument supplied for foreach() in C:\laragon\www\j4\administrator\components\com_installer\src\Model\LanguagesModel.php on line 158

### System information (as much as possible)
php 8.1.7 and php 7.4
joomla 4.2 branch upto date at time of posting

**Comment by brianteeman** [comment]
Release blocker?

**Comment by alikon** [comment]
is https://update.joomla.org/language/translationlist_4.xml that doesn't return the xml

**Comment by brianteeman** [comment]
so that means there are TWO bugs

1. The missing xml
2. The absence of a sensible error message when that happens

**Comment by alikon** [comment]
the 1) is solved now  can you confirm ?

**Comment by brianteeman** [comment]
> the 1) is solved now can you confirm ?

yes

**Comment by alikon** [comment]
please test #38113
