### ISSUE TITLE
$this->app->getDocument() is NULL

### ISSUE THREAD

**Issue by thynk-media** [joomla/joomla-cms#38114]
Hello,

I just updated my Joomla 4 instance to 4.1.4, since then reCaptcha, invisble reCaptcha and also hCaptcha stopped working with following error:

Call to a member function getWebAssetManager() on null

### Steps to reproduce the issue

Use $this->app->getDocument() in a plugin

### Expected result

\Joomla\CMS\Document\HtmlDocument

### Actual result

NULL

**Comment by Fedik** [comment]
On which extension do you use reCaptcha?

**Comment by thynk-media** [comment]
I this case it was Balboa Forms, but with the release of 4.1.5 the problem was solved ;)

Thank you anyways, have a nice day :)
