### ISSUE TITLE
Article Readmore Button Focus

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#38122]
### What needs to be fixed
Read more button issue persists. It was opened before but I couldn't find it.

![readmore](https://user-images.githubusercontent.com/423588/175041842-4b32fae3-ed48-48c4-ba4b-d6e52ec4a8b4.jpg)
-----------------------------------
**Article Class: image-left**, This way there is no problem.

![readmore-class](https://user-images.githubusercontent.com/423588/175053479-aade6c61-94ec-4dff-ba39-1e02f913254d.jpg)

- Joomla 4.1.5 new installation

Regards

**Comment by Quy** [comment]
Closing as this is not a core issue. Please report here. Thank you.

https://github.com/joomla/joomla-websites/issues/new?title=[joomla.org]%20&body=Please%20describe%20the%20problem%20or%20your%20issue

**Comment by ghost** [comment]
> Closing as this is not a core issue. Please report here. Thank you.
> 
> [https://github.com/joomla/joomla-websites/issues/new?title=[joomla.org]%20&body=Please%20describe%20the%20problem%20or%20your%20issue](https://github.com/joomla/joomla-websites/issues/new?title=%5Bjoomla.org%5D%20&body=Please%20describe%20the%20problem%20or%20your%20issue)

Cassiopeia Template issue

**Comment by chmst** [comment]
simliar https://github.com/joomla/joomla-cms/pull/37877 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38122">issues.joomla.org/tracker/joomla-cms/38122</a>.</sub>

**Comment by chmst** [comment]
@joomlaphp could you please test https://github.com/joomla/joomla-cms/pull/37877 and see if your issue can be closed?

**Comment by brianteeman** [comment]
no it is not fixed by that pr which as you can see in the code was only for  .list-inline-item

**Comment by brianteeman** [comment]
The problem is because there is a padding:0 on the parent container. Any focus will therefore be cut off,

One way to fix this would be to always ensure that there is positive padding on every container
