### ISSUE TITLE
Module Options Description is not displayed

### ISSUE THREAD

**Issue by Gratia-Mira** [joomla/joomla-cms#38136]
### Steps to reproduce the issue
Go to the backend and to a module of which you know that settings are described in the xml file by using "description".  For example like this:
`            <field 
                name="team-mitarbeiter"
                label="CSS team-mitarbeiter-Klasse"
                size="10"
                type="text"
                default=""
                filter="raw"
                description="Fügen Sie  weitere CSS-Definitionen hinzu. Die team-mitarbeiter-Klasse umfasst alle Mitarbeiter der Abteilung."
            />
`

### Expected result
The purpose of this description is that it is displayed to the user. On the picture in the grey text
![image](https://user-images.githubusercontent.com/93832365/175555013-fac73d4f-3686-4341-b76f-228db65ea417.png)

### Actual result
The description is not displayed, as it seems in all modules.

### System information (as much as possible)
Joomla 4.1.5 (Linux and Windows Server)

### Additional comments
Is there a solution to this?

**Comment by Fedik** [comment]
By default it hidden with `d-none` (no idea why)
https://github.com/joomla/joomla-cms/blob/54ed9907d08908f4163cc7b9caddbb2ab6904dd0/layouts/joomla/form/renderfield.php#L40

in theory you can add attribute `inlineHelp="true"` to enable it back (from #37819)
But in quick test it does not work for me.

Probably some bugs.

UPD: found, it hidden because this #35610

**Comment by Fedik** [comment]
Maybe @brianteeman have a better hint for you.

**Comment by Gratia-Mira** [comment]
@Fedik All right, I have now seen how to show the help. Thanks for the link!

But this does not yet work for "repeatable" xml fields. These are always displayed. That's why I thought something was wrong here.

@brianteeman Should I close the ticket or do you still want to keep pursuing this?

**Comment by Fedik** [comment]
if it works for you, you can close :wink:

**Comment by chmst** [comment]
Simplest solution is the hint Attribute, add information like a  placeholder.

**Comment by Gratia-Mira** [comment]
Good, thank you all!
