### ISSUE TITLE
Deprecation messages are somewhat unhelpful without a code reference.

### ISSUE THREAD

**Issue by MarkRS-UK** [joomla/joomla-cms#38137]
### Steps to reproduce the issue
Set "Log Deprecated API" on in the "Logging" Global Configurations panel.
Run almost anything, either in the front or back end.
If running something in the back end, look in the file <root>/administrator/logs/deprecated.php (I haven't checked the corresponding front end file)

### Expected result
Deprecation messages should show the line number and file name causing the deprecation message.

### Actual result
They don't.

### System information (as much as possible)
Present in 4.1.5 and all previous versions (presumably).

### Additional comments
In file <root>/libraries/src/Exception/ExceptionHandler.php method handleUserDeprecatedErrors line 44, add in the file and line reference, which are supplied to that method, eg

`Log::add("$errorMessage - $errorFile - Line $errorLine", Log::WARNING, 'deprecated');`

I can imagine that this was excluded purposefully since the core still contains hundreds, if not thousands, of deprecation instances, but in a way that makes it even more unhelpful that this information is not printed.

**Comment by laoneo** [comment]
Can you make a pull request with the suggestion. Sounds like a good addition.

**Comment by richard67** [comment]
Closing as having a pull request. See #38158 .
