### ISSUE TITLE
Branch 4.1-dev broken because it set as 4.2.0-dev now

### ISSUE THREAD

**Issue by xillibit** [joomla/joomla-cms#38139]
### Steps to reproduce the issue

Update with last changes from github the 4.1-dev branch, in the backend it displays now 4.2.0-dev

Under "Maintenance: Database" there is another issue : 

![image](https://user-images.githubusercontent.com/876395/175766191-8566dd30-0e06-4d88-8719-afc421dda487.png)

### Expected result

In the backend it should stays as 4.1.0-dev

### Actual result

In the backend it displays 4.2.0-dev

### System information (as much as possible)

Joomla 4.1-dev branch
Php 8.0.20

**Comment by richard67** [comment]
@bembelimen Any comment?

**Comment by brianteeman** [comment]
> In the backend it should stays as 4.1.0-dev

why is that expected. 4.1 is not the default branch any more as there will be no further 4.1 releases

**Comment by bembelimen** [comment]
Don't use the 4.1 branch anymore. The stable was the last version, the final releases should be used or 4.2 for development.
4.1-dev is only here till we have moved all PRs to 4.2.

**Comment by richard67** [comment]
@bembelimen So the issue should be closed as expected behavior?

**Comment by xillibit** [comment]
ok thanks for the info
