### ISSUE TITLE
Update from Joomla! 3.10.9 to 3.10.10 messes up the .htaccess

### ISSUE THREAD

**Issue by lepathie** [joomla/joomla-cms#38130]
### Steps to reproduce the issue
Update from Joomla! 3.10.9 to 3.10.10

### Expected result
System should be working correctly and the .htaccess should not be altered in a bad way

### Actual result
The website stops working. The .htaccess gets altered with new lines ending at "## End - Joomla! core SEF Section." the last line is now missing a line-break that forces the following line to be commented out. In our case the "RewriteCond %{HTTP_HOST} !^www\." which lead to an unlimited amount of rewrites like www.www.www. .
See screenshot of .htaccess .![screen shot 2022-06-23 at 16 14 33](https://issues.joomla.org/uploads/1/2e32b4407ad543cb2b1efb34d1d5340d.png)

### System information (as much as possible)
Joomla 3.10.10

### Additional comments
Parallel to Joomla! we updated 2 broadly used Plugins:
- Akeeba Backup
- JCH Optimize

**Comment by brianteeman** [comment]
At no point in the update process does any existing .htaccess file get changed.

Whenever a change to the htaccess is recommended then this is done in the htaccess.txt file and a post installation message is published in the admin with details and instructions on how to MANUALLY make any change.

The last change to the htaccess.txt was over 4 months ago.

I can see from your screenshot that you are already modifying the .htaccess from the one supplied by Joomla. So whatever change is _breaking_ your site it is not coming from Joomla itself.

**Comment by richard67** [comment]
@brianteeman is absolutely right. Closing as not a core issue. If you need advice regarding your custom .htaccess file, please use the support forum.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38130">issues.joomla.org/tracker/joomla-cms/38130</a>.</sub>

**Comment by ReLater** [comment]
Just BTW: JCH Optimize changes the .htaccess after **any** JCH installation and any JCH update. Even if you have disabled all JCH extensions.

**Comment by richard67** [comment]
> Just BTW: JCH Optimize changes the .htaccess after **any** JCH installation and any JCH update. Even if you have disabled all JCH extensions.

Interesting ... and good to know. Thanks @ReLater .

**Comment by lepathie** [comment]
Thanks @brianteeman for clarification.

And thanks @ReLater for the information. Then probably there is what caused the problem.
