### ISSUE TITLE
feature request : add collapsible dropdown menu for all screen sizes .

### ISSUE THREAD

**Issue by sofianhit** [joomla/joomla-cms#38147]
hi
joomla 4 , menu module .

it is a good idea to have a menu like off-canvas menu on the site .
in joomla 4 the collapsible menu is for small screens only .
why not to be for all screens sizes too ? .
![screen shot 2022-06-26 at 21 12 50](https://issues.joomla.org/uploads/1/2d094beb8d26e736cdbe8e6279c15b78.png)

**Comment by brianteeman** [comment]
There is no need for a new feature.

Simply create a template overide for this layout and remove the standard bootstrap class navbar-expand-md

See https://getbootstrap.com/docs/5.0/examples/navbars/#

**Comment by sofianhit** [comment]
> There is no need for a new feature.
> 
> Simply create a template overide for this layout and remove the standard bootstrap class navbar-expand-md

go make it and test it before you comment here .

if i do it like you say , the off-canvas button will display , but the text menu will display too . then i made the text not display , then i click on the button nothing display .

please go to sleep and dont do any feature request , dont work on it . i dont need your help . i dont want this feature .

**Comment by brianteeman** [comment]
maintainers - please close this and all other feature requests from this user.

**Comment by chmst** [comment]
@sofianhit thanks, closing this as requested
