### ISSUE TITLE
Administrator Menu Filter Options missing

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#38150]
### Steps to reproduce the issue
I create an administrator menu with several menu items. 

To make the view clearer while working I choose the filter options.

### Expected result

I expect the same functions as in a menu for the frontend: filters for status, access level, language, max. levels....

### Actual result

These functionalities are completely missing.

### System information (as much as possible)

J4.1

### Additional comments

This behavior contradicts the usability principle of expectation conformity, since as an administrator managing a menu for the frontend, I would expect the same behavior for an administrator menu.

**Comment by brianteeman** [comment]
> I expect the same functions as in a menu for the frontend: filters for status, access level, language, max. levels....

### Admin Menu filters
![image](https://user-images.githubusercontent.com/1296369/175892130-b0a3d17b-ad32-4c68-9828-b33c14e4a395.png)

As the admin menu items do not have access level or language a filter would be pointless

**Comment by hytsch** [comment]
ok, accepted, but still the filters are not congruent with the functions: The filter "parent menuitem" is missing.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38540 . Thanks in advance.
