### ISSUE TITLE
Article copies are incorrectly published directly

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#38151]
### Steps to reproduce the issue

I am copying an article. 

### Expected result

Every COPY of an article, a category, menuitem, module, CustomField etc. should always be NOT published first.

### Actual result

The copy of the post is created as "published".

### System information (as much as possible)

J4ff

**Comment by richard67** [comment]
Closing as duplicate report, see e.g. #37351 or #37996 , There is a pull request which claims to fix it. Please test #37354 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38151">issues.joomla.org/tracker/joomla-cms/38151</a>.</sub>
