### ISSUE TITLE
[4.2] The ruleset.xml file gets into the nightly assembly

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#38164]
### Steps to reproduce the issue
The ruleset.xml file gets into the nightly assembly.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/176143195-d70c8727-eef0-48b2-b58d-50bae29ed923.png)

**Comment by richard67** [comment]
It probably needs to add code to build.php to remove that file and possibly other stuff,

**Comment by brianteeman** [comment]
see #38166

**Comment by richard67** [comment]
Closing as having a pull request.
