### ISSUE TITLE
[4.2] web installer cant install extensions

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38179]
This is a different issue to #38173

Akeeba backup will install quite happily on j4.2 when installed from a zip file (it doesnt use the db stuff causing issues in the other pr)

Trying to install AB using the install web functionality fails with the message **Unable to detect manifest file.**

I can see from the network traffic that there is a 302 taking place and i understand that the error message is a generic one that says "I cant do anything - so i've gone back to the beginning"

Install from web using 4.1.5 works without problem

I can't see how based on the above it can be an issue with AB and must be changes here

cc @nikosdion

**Comment by nikosdion** [comment]
There is nothing for me to fix.

My JED entry has the correct URL to the XML update file:

<img width="561" alt="Screenshot 2022-06-29 at 17 33 05" src="https://user-images.githubusercontent.com/256041/176462987-6039e0a4-f0aa-4ebf-b621-b5d9f4ab1ef3.png">

My XML update file (http://cdn.akeebabackup.com/updates/akeebabackupjed.xml) is correct:

<img width="727" alt="Screenshot 2022-06-29 at 17 33 38" src="https://user-images.githubusercontent.com/256041/176463112-896af557-2b8b-4fd4-ab84-dfa721eb286d.png">

**HOWEVER!** 

Do note that I have NOT published any version tagged as compatible with Joomla 4.2 **just yet** (at the time of this writing we are still in the Joomla 4.2 beta phase; I only make releases tagged as compatible during the latent Release Candidate stage of each Joomla release cycle as I can't trust that the project won't introduce a breaking change I could not have anticipated before that point in time). Joomla should be able to pick this up and display an error that this extension is not compatible with this version of Joomla.

I hope that clarifies the problem and what you should be looking for to fix.

**Comment by brianteeman** [comment]
dam - thats what i thought of last night and then got convinced it was something else. should have stuck to my guns

**Comment by nikosdion** [comment]
In your defence it even took _me_ two beats too long to realise the problem while I was staring at the code of the XML file, waiting for the image to upload to GitHub.
