### ISSUE TITLE
Filtered search with Advanced search module

### ISSUE THREAD

**Issue by NicolasJOS** [joomla/joomla-cms#38176]
### Steps to reproduce the issue
I needed to create a filtered search : Components > Advanced Search > Search Filter
I wanted to apply this filter to my search field, two possible methods:

- I tried to create an "Advanced search" menu link to which I applied my filter, the results are indeed filtered.
- I then tried to create an "advanced search module" to which I applied my filter, but in this case the results are not filtered!

### Actual result
The filter is applicable to a "Advanced Search Module" but has no effect.

### System information (as much as possible)

Joomla 4.1.5
php 8.0

**Comment by chmst** [comment]
I cannot replicate this. If I set a filter i.e. for "tags" and apply it in the smart search module, the filter works. 
Are you not speaking about joomla core but about an advanced search extension? 

Could you show your filter settings?

**Comment by NicolasJOS** [comment]
Hi, here it is :

I have two category Fruits & Vegetables

Two articles "Banana" in "Fruits" and "Carrot" in "Vegetables"

I'v created a filter first to search only in category "Vegetables"

![Capture d’écran 2022-07-05 à 11 09 22](https://user-images.githubusercontent.com/102307388/177293356-b35bf3e8-5115-412f-9fe6-f0966e01c764.png)

And added a Menu item using my filter
![Capture d’écran 2022-07-05 à 11 03 05](https://user-images.githubusercontent.com/102307388/177293490-89cd12cf-0bf5-4773-8353-bdc3e46ea0c4.png)

And added a Joomla native Advanced search module using the same filter 
![Capture d’écran 2022-06-30 à 09 51 19](https://user-images.githubusercontent.com/102307388/177293652-afd64ed7-5906-44cd-a54a-71fb70031dd4.png)

I installed my menu in Main menu and my Module in footer.

You can see the result here https://www.njnet.fr
Searching Banana using the menu, no result, it's ok.
Searching Banana using the module, you have a result ...

Thanks

**Comment by chmst** [comment]
Thanks for your information, I tried the same environment (categories, articles, filter) on a test installation, but still cannot replicate that. Could you switch to the default template cassiopeia? 
Search module and search form on the same page is somehow confusing but works as expected in cassiopeia.

![grafik](https://user-images.githubusercontent.com/1035262/177763299-724e49f7-34fe-4450-9327-b86e6b31f98f.png)

**Comment by NicolasJOS** [comment]
Hi, you're right,
I did the same in Cassiopeia and in this case, all is ok.
So my actual template (Yootheme) override the search result within a module ...
I'll discuss this with Yootheme team !
Thanks a lot
Nicolas

**Comment by chmst** [comment]
Thank you for the feedback! I close this now.
