### ISSUE TITLE
J4 v4.1.5 Fields Description in Plugin is not showing up

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#38174]
### Steps to reproduce the issue
I created a custom system plugin and in the plugin xml file I have several fields and I added a normal description attribute. The description text is supposed to appear under the field form control but it does not. I just upgraded to v4.1.5 the other day and just noticed this behaviour. Although description under the view xml fields are working fine. It could be just with the plugins.

**Comment by chmst** [comment]
https://github.com/joomla/joomla-cms/issues/38136 see here

**Comment by Fedik** [comment]
Click this litle button on toolbar :wink: 
![image](https://user-images.githubusercontent.com/1568198/176458348-7be09599-8d60-4f03-9b6e-e6a26295ce43.png)

**Comment by frogydiak** [comment]
Got it! I thought that button was just for help (documentation) which is basically gets ignored. Maybe it should say "Toggle Fields Inline Help" and it's weird to see it in the toolbar.

Anyhow, thank you!
