### ISSUE TITLE
[4.2] No longer possible to install extensions - Release blocker

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#38173]
### Steps to reproduce the issue
Install whatever extension on Joomla 4.2, for example Acymailing, JEvents, etc

In more details, it seems that the class Joomla\CMS\Installer\Installer is now DatabaseAwareTrait and if an extension instantiate it in the install script as usual, it will be missing the setDatabase causing the B/C issue.
It's common that an install script also install other extensions such as plugins, modules, etc

### Expected result
No errors

### Actual result
Installation fails:
![image](https://user-images.githubusercontent.com/17835460/176318907-ffa7a64b-27ad-4473-a0d2-c953c9e8d2b7.png)

### System information (as much as possible)
Joomla 4.2 Beta 2

**Comment by brianteeman** [comment]
~Almost certainly those extensions have only been set as compatible with 4.0 and 4.1~

**Comment by joeforjoomla** [comment]
@brianteeman an extension has to be set compatible with Joomla 3 and Joomla 4 on the JED and it's supposed to be compatible with a whole major release without this kind of breaking changes between minor releases.

**Comment by brianteeman** [comment]
~1. 4.2 is not releasd yet~
~2. This is nothing new. An extension has always been responsible with setting which version it is compatible with.~
3. I might hav been confused with th targetversion in the update xml

**Comment by laoneo** [comment]
Is it a public extension you try to install? If yes, can you share here the link so I can try it out?

**Comment by laoneo** [comment]
I just tried to install JEvents on the latest 4.2 code and it worked. Can you test if they work with the latest changes from the 4.2-dev branch?

**Comment by laoneo** [comment]
Acymailing failed with the first installation but a second one succeeded.

**Comment by joeforjoomla** [comment]
@laoneo the problem happens when an extension instantiate the class Joomla\CMS\Installer\Installer in the install script file without being aware that now it requires ->setDatabase() to inject the db object

**Comment by joeforjoomla** [comment]
You can try the free package of acymailing: https://www.acyba.com/index.php?option=com_updateme&ctrl=download&component=acymailing&level=starter&ext=tar.gz

This one can't be installed at all, nor the first nor the second time

**Comment by OctavianC** [comment]
Can confirm - `new JInstaller` now needs `$installer->setDatabase($db);` to work. ~~Also, a world of pain comes up when calling the JInstaller to uninstall another extension from the uninstall script:~~
```php
class com_testInstallerScript
{
	public function uninstall($parent)
	{
		$extension_id = 'some-other-extension';
		$installer = new JInstaller;
		$installer->setDatabase($db)
		$installer->uninstall('plugin', $extension_id);
	}
}
```

EDIT: got confused editing the wrong file, above works, so just `setDatabase()` is needed whenever a `new JInstaller` is created.

**Comment by laoneo** [comment]
> @laoneo the problem happens when an extension instantiate the class Joomla\CMS\Installer\Installer in the install script file without being aware that now it requires ->setDatabase() to inject the db object

When not available, then this should be set from the global db instance. As I said, can you try with the latest code changes from the 4.2-dev branch?

**Comment by laoneo** [comment]
There should be a fallbck to the gloabl db instance when it is not set. But I need some kind of a stack trace as I can't reproduce the issue with the latest code from the 4.2-dev branch.

**Comment by joeforjoomla** [comment]
@laoneo can i try the latest nightly build? https://developer.joomla.org/nightlies/Joomla_4.2.0-dev-Development-Full_Package.zip

**Comment by OctavianC** [comment]
same results with latest nightly.

**Comment by joeforjoomla** [comment]
Confirmed, same results with latest nightly https://developer.joomla.org/nightlies/Joomla_4.2.0-dev-Development-Full_Package.zip and the latest package of Acymailing attached used as an example

[starter_v7.8.3_2022-06-29_09-48-10.tar.gz](https://github.com/joomla/joomla-cms/files/9008481/starter_v7.8.3_2022-06-29_09-48-10.tar.gz)
![image](https://user-images.githubusercontent.com/17835460/176384346-9f3b2f05-eef5-482e-bc2e-b9700635667b.png)

**Comment by laoneo** [comment]
I will have a look as it looks like there is something different between the branch and the build. I will report back as this should def. work without explicitly setting the database.

**Comment by joeforjoomla** [comment]
@laoneo thank you. Let me know if you need further informations or tests on my side

**Comment by OctavianC** [comment]
This is the line that's causing issues in [starter_v7.8.3_2022-06-29_09-48-10.tar.gz](https://github.com/joomla/joomla-cms/files/9008481/starter_v7.8.3_2022-06-29_09-48-10.tar.gz)
```php
$installer = new JInstaller();
$installer->refreshManifestCache($extension->extension_id);
```

**Comment by joeforjoomla** [comment]
@OctavianC that's not only the reason, it's enough to use the installer for example to install a plugin:

```
$pluginInstaller = new Installer ();
$pluginInstaller->install($path);
```

**Comment by OctavianC** [comment]
Yes, I've already figured that out. Can be fixed by using `$installer->setDatabase($db)` but a $db should be assumed by the code if not explicitly set.

I see that https://github.com/joomla/joomla-cms/commit/a36f76c9c1912098fc5b0ddb01e0976b0c49ac2f has injected `$db` to every `Installer` object but that shouldn't have been needed as it's breaking compatibility

**Comment by joeforjoomla** [comment]
@OctavianC yes indeed this is exactly the point of this issue, as @laoneo said it should work in all cases. Let's @laoneo having a look...

**Comment by richard67** [comment]
For testing I've just installed OSMap Free via the Install From Web on a clean, new install of current 4.2-dev. I get an error alert shown, but despite or debug and error reporting no stack trace and nothing in the error log. The error alert says:

```
2416: /home/richard/lamp/public_html/joomla-cms-4.2-dev/libraries/src/Installer/Installer.php
Installer::getDatabase() - Database not set in Joomla\CMS\Installer\Installer
```

I think that's nothing new now, but I thought I leave that info about another way to reproduce the issue.

**Comment by Fedik** [comment]
The bug happened because DB injected in `Installer::getInstance()`
https://github.com/joomla/joomla-cms/blob/dd91072a956a19a43798515239892edd2b49ac7b/libraries/src/Installer/Installer.php#L186-L191

And not in constructor, 
then `Installer::getInstance()` will work and `new Installer` will fail.

Not sure what correct fix.

**Comment by Fedik** [comment]
Addittionaly, developers can extend our Installer class, and override getInstance or __construct.
That makes things a bit more complicated.

**Comment by laoneo** [comment]
Please test #38187.

**Comment by richard67** [comment]
Closing as having a pull request.
