### ISSUE TITLE
custom INT field with vaules beyond 999999 makes editing item fail

### ISSUE THREAD

**Issue by mc-cm** [joomla/joomla-cms#38181]
### Steps to reproduce the issue

- create an integer custom field for articles or contacts .
- set the values to 1 (min) and 99999999, steps 1
- try to create an article or contact.

### Expected result

- editing form should open.

### Actual result

- server error: Allowed memory size of 8589934592 bytes exhausted (tried to allocate 1073741832 bytes)
- (importet vaules don't show in the backend, instead "1" is displayed in the forms)

### System information (as much as possible)

- local install
- 10.8.3-MariaDB 
- utf8mb4_unicode_ci 
- php 7.4.29 
- Apache/2.4.53 (Unix) PHP/7.4.29 
- Joomla! 4.1.4 Stable [ Kuamini ] 24-May-2022 16:00 GMT

### Additional comments

Hi there!
Here's the big picture: I needed a 8-digit field to store contact IDs, so I created a custom int field for contacts. First I did this without touching the settings of the field. All the contact data got imported directly to the database, no manual input.
I can see the correct values in the database, I also can see all the contacts in the list. Basically: import works.

But as soon as I try to open and manually edit a contact, the system crashes.

Same behavior for articles.

Some more details: if the int field is only 6digits (max value 999999), editing works. With every digit more it get's slower until editing crashes. If no min / max / step values are present everything works, but I only can enter a max value of "100". Imported values don't show up anyway. They sit in the database but don't show up in the backend of the contact.

Somehow I get the feeling I try to misuse the int field?

**Comment by brianteeman** [comment]
What you are doing is setting up a drop down list with values from 1 - 999999 so thats obviously not correct.

The correct method is to create a text field with a filter of integer and a maximum length of 6 characters

![image](https://user-images.githubusercontent.com/1296369/176486177-6607dc15-8a13-40e3-8ba6-ed28cbcb468e.png)

**Comment by mc-cm** [comment]
OK, I thought the problem was on the human side.
Thanks for the clarification.
