### ISSUE TITLE
Site modules are always visible in the component tag view, independend from the menu assignment of the modules

### ISSUE THREAD

**Issue by die-webdesigner** [joomla/joomla-cms#38182]
### Steps to reproduce the issue
Install Joomla 4.1.5 with Blog Sample Data
Go in the backend to Content -> Site modules. Per default, the menu assignment of the "image" module on "banner" position is selected to "Only on the page selected". The only selected page is "Home".

Goto "Home" on the front page and the image (or module image) is displayed.
Select "blog" in the menu. The immage (or module image) is not displayed. Correct.   
Select any of the tags in the blog view. For example "Millions" in the article "Welcome to your blog".
The tag view (e.g. mytestsite.com/index.php/component/tags/tag/millions) is open.

### Expected result
In the component tag view the immage (or module image) should not be visible.

### Actual result
In the component tag view the immage (or module image) is visible.
This is different to Joomla 3.10.10. Modules are not visible in the tag view, unless menu assignment "On all pages" is selected. 

### System information (as much as possible)
PHP Built On: XAMPP 7.4.8 Windows AMD64
Database Type: mysql
Database Version: 10.4.13-MariaDB
Database Collation: utf8mb4_unicode_ci
Database Connection Collation: utf8mb4_general_ci
Database Connection Encryption: None
Database Server Supports Connection Encryption:	No
PHP Version: 7.4.8
Web Server: Apache/2.4.43 (Win64) OpenSSL/1.1.1g PHP/7.4.8
WebServer to PHP Interface: apache2handler
Joomla! Version: Joomla! 4.1.5 Stable [ Kuamini ] 21-June-2022 14:00 GMT

### Additional comments
This bevavior ist also valid for the "Latest Posts" module on position "top-a".
Is it an issue or works as designed? For me it makes more sense how it works in Joomla 3.

**Comment by brianteeman** [comment]
Every page in joomla has an itemID - which is easier to understand if you think of it as a menuitemID

If there is no matching menu item then Joomla will use the itemid of the home page

You may find it easier to understand what I am explaining if you disable SEF urls in the global configuration. Then you will see the full url including the itemid

**Comment by die-webdesigner** [comment]
I apologize for the delay and thank you for the explanation.

Questions:
1. Why does it work in Joomla 3.10.10 as I expect?
2. How can I show or not show or place a module in a tag component view as I want. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38182">issues.joomla.org/tracker/joomla-cms/38182</a>.</sub>

**Comment by brianteeman** [comment]
1. happy accident 
2. create a menu link for the tag component (doesnt have to be visible)

**Comment by chmst** [comment]
@die-webdesigner I am closing this, as it is not a joomla issue  @brianteeman explained.

**Comment by die-webdesigner** [comment]
yes, that is fine. I found a solution that works for me.

@brianteeman: Thanks for syour support!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38182">issues.joomla.org/tracker/joomla-cms/38182</a>.</sub>

**Comment by andrescmhz** [comment]
@brianteeman can you by more specefic? I don't know how to assign-create a menu link for the tag component<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38182">issues.joomla.org/tracker/joomla-cms/38182</a>.</sub>
