### ISSUE TITLE
feature request: joomla 4 own video player

### ISSUE THREAD

**Issue by sofianhit** [joomla/joomla-cms#38195]
hi
all we need youtube , vemo , .... etc videos on our sites .
and all we need the video stay on youtube , vemo , .... etc site . 
**we dont want to host the video on our sites** , we are right, we want to save space on our server .
in the same time we want to keep our visitors staying in our site and prevent them to jump to youtube or any external sites .
BUT : 
the existing way to add videos in articles dont prevent jumping to youtube or any .

my idea is , to play videos using joomla own player that plays video from external url and not has any options to leave the site (not show any links to youtube or any , not show related videos that jumps outside our site).

for example : 
this nice free player-
https://www.mediaelementjs.com/

is it possible to step forward with this great feature for joomla ? 

thanks

**Comment by brianteeman** [comment]
This should be an extension and not part of the core. There are quite a few already available.

Note that if you are playing a video from youtube you can never remove the links to youtube or the related videos as you can see in their demo https://plyr.io/#youtube

**Comment by sofianhit** [comment]
look at this one , the title and related videos not jumb to youtube .
https://www.mediaelementjs.com/ 
(choose youtube from dropdown meny on the top right corner of the player)

all of extensions that already available is not care to prevent jumping outside the site .

keep in mind that the editor tinymce is an external code but joomla using it in the core . 
so i think joomla can using its own player .


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38195">issues.joomla.org/tracker/joomla-cms/38195</a>.</sub>

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/176869458-2e8a6a59-5ace-4b2e-a28c-421cebc6200a.png)

The links are still there - the player just disables them so the user thinks its broken - no thanks

**Comment by sofianhit** [comment]
brianteeman : 
i am not fighting for hide them because i dont want see them !never, what i want is not use them .
so please play youtube video there and click on any title (like in your image) .
they will not jump to youtube .
my idea to sty watching on my site .
and the great featurs this player has that i can use keyboard shortcuts like space= play/pause arrows left/right = move forward/backward 
F= fullscreen .  
my users will forgot youtube .

what you say now !
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38195">issues.joomla.org/tracker/joomla-cms/38195</a>.</sub>

**Comment by brianteeman** [comment]
I stick with my original comment

**Comment by dgrammatiko** [comment]
Mediaelementjs is already in the distribution: https://github.com/joomla/joomla-cms/blob/e8be0cb6fdd500944262a731bf732b55e7df100d/package.json#L55

**Comment by sofianhit** [comment]
dgrammatiko : 
what is those in the distribution ?
is this meaning that joomla will use them in the fuure or it is already in joomla ? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38195">issues.joomla.org/tracker/joomla-cms/38195</a>.</sub>

**Comment by dgrammatiko** [comment]
It means that if you create a custom field of type url then in the layout override you can apply this player to the inserted url. Means that everything needed are already in place…

**Comment by sofianhit** [comment]
i tried to add it by custom field of type url , but did not see this player and dont know where is the layout override ? 
can you bring a screenshot !
but from the other side my idea is to add video in article directly not by custom field .
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38195">issues.joomla.org/tracker/joomla-cms/38195</a>.</sub>

**Comment by ReLater** [comment]
In times when there are data protection concerns against embedding external content, I am against a corresponding feature in the Joomla core that invites you to embed something like this. There are already extensions that can do this. Every user can install them on his or her own responsibility and Joomla will not get into the predicament of having to integrate any data protection tools again or of having to investigate and discuss endlessly whats allowed and how and... It's not worth it.

**Comment by sofianhit** [comment]
yes , i understand . 
thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38195">issues.joomla.org/tracker/joomla-cms/38195</a>.</sub>

**Comment by rdeutz** [comment]
This is not going to happen for reasons stated.
