### ISSUE TITLE
why the topbar not has "grid-child" class ? 

### ISSUE THREAD

**Issue by sofianhit** [joomla/joomla-cms#38206]
hi 
in the header there are 4 divs 
all of them have the "grid-child" class but the topbar dont has it .
so the module on topbar flaot to left because the "grid-child" class has a margin-left .
is this intentionally not has this class ? 
can i know why it not has it ! 

![screen shot 2022-07-02 at 19 41 03](https://issues.joomla.org/uploads/1/36ce0e47acf4c2fddc7038633dbc9b02.png)

**Comment by chmst** [comment]
Because another contributor wanted to have it like this and made a Pull Request. 

@sofianhit You are workig on a site with an own design. So have lots of people and everyone has other needs and wishes. Do you know the concept of child templates? In a child templateof cassiopeia you can override everything, even the index.php. 
https://github.com/joomla/joomla-cms/issues/38204#issuecomment-1172919045

**Comment by richard67** [comment]
The topbar position has been added with PR #31731 . Maybe when you read that PR and the comments on it you will find the explanation why it has been done like it has been done.

**Comment by sofianhit** [comment]
my question was not why added topbar position .
my question is why it is not has "grid-child" class .
I don't object the topbar itself , never , i like it, but module on it float to left . 
i just speak about style it .

but i want to tell you : 
the header need some works and improvement .
for example : 
the topbar need another div inside it .
like this : 
<?php if ($this->countModules('topbar')) : ?>
			<div class="container-topbar ">
				**<div class=" grid-child">**
			<jdoc:include type="modules" name="topbar" style="none" />
			**</div>**
				</div>
		<?php endif; ?>

the topbar will be 100% width and the inside div will get the grid-child class to be Collimated with the logo and below top modules .

i promise i will not ask any questions .
i will not request any features .
i will use what i get from joomla .

my problem is that i dont know php .

thanks  
 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38206">issues.joomla.org/tracker/joomla-cms/38206</a>.</sub>

**Comment by sofianhit** [comment]
<?php if ($this->countModules('topbar')) : ?>
			<div class="container-topbar ">
				**<div class=" grid-child">**
			<jdoc:include type="modules" name="topbar" style="none" />
			**</div>**
				</div>
		<?php endif; ?>
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38206">issues.joomla.org/tracker/joomla-cms/38206</a>.</sub>

**Comment by chmst** [comment]
Now as you have found the solution :) make a child template from casssiopeia and  override  the index.php. As you see, no php skills are required, it is only Html.
But I have labelled your request.

**Comment by brianteeman** [comment]
I dont see how this can be changed in core as it would change the behaviur on all existing sites uwing this position.

Should be closed.

**Comment by sofianhit** [comment]
close close , close all my posts . dont wait

**Comment by sofianhit** [comment]
> I dont see how this can be changed in core as it would change the behaviur on all existing sites uwing this position.
> 
> Should be closed.

you comment without reading , you dont understand what wrote above .

**Comment by chmst** [comment]
Closing as requested
