### ISSUE TITLE
feature request : surrounding the logo and the menu inside container + new class for logo

### ISSUE THREAD

**Issue by sofianhit** [joomla/joomla-cms#38204]
hi 
this feature request can be instead of this feature request : 
https://issues.joomla.org/tracker/joomla-cms/38192
or fulfillment both .

the idea here is to put the logo and the menu inside one div + adding a new class for logo .
We will get : 
1- keep 100% width for topbar and below top .
2- keep topbar and below top sticky inside sticky header .
3- **no need much works and changes from the developers** .
4- PUT the logo and menu in one row without affect the topbar and below top (by own css).
5- by adding a new class for logo we can play with the width of the logo and menu inside their new container . 
6- must add new class to logo because it has only "grid-child" class that is for topbar and below top too .

![screen shot 2022-07-02 at 09 28 14](https://issues.joomla.org/uploads/1/3e655e043c72df18b340ab6c1ba6ddce.png)

![screen shot 2022-07-02 at 09 28 18](https://issues.joomla.org/uploads/1/dc31b57c0ec667201f1ca51183f88100.jpg)

**Comment by richard67** [comment]
So can #38192 be closed?

**Comment by sofianhit** [comment]
maybe yes , maybe wait to hear another opinions .
like you want .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38204">issues.joomla.org/tracker/joomla-cms/38204</a>.</sub>

**Comment by ReLater** [comment]
In a "Mobile first!" world I would like to see more mockups for different screen widths. And would like to hear some ideas how you want to realise them in a backwards compatible Cassiopeia.

Finally you're planning a new template somehow. Don't you think that would be the better way to realise your ideas? And less work? Or maybe it would be better to implement them in core as an additional child template?

**Comment by sofianhit** [comment]
close this topic<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38204">issues.joomla.org/tracker/joomla-cms/38204</a>.</sub>

**Comment by richard67** [comment]
Closing as stated by the author in the previous comment.
