### ISSUE TITLE
CLI database export

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38217]
### Steps to reproduce the issue
`php .\cli\joomla.php database:export`

### Expected result
no errors or notices

### Actual result
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in C:\laragon\www\j4\libraries\vendor\joomla\database\src\DatabaseExporter.php on line 305

### System information (as much as possible)
php 8.1

**Comment by richard67** [comment]
@brianteeman There is a PR with a fix for that in the framework, but it has a thumbs down from an old well known fellow (but not the one who usually gives the thumbs down): https://github.com/joomla-framework/database/pull/264

**Comment by Hackwar** [comment]
https://github.com/joomla-framework/database/pull/286 fixes this issue. Since we have a PR, I'm closing this one.
