### ISSUE TITLE
CLI finder:index

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38214]
### Steps to reproduce the issue
`php .\cli\joomla.php finder:index `

### Expected result
no errors

### Actual result
```
In PluginHelper.php line 46:
                                                                                     
  Call to undefined method Joomla\CMS\Application\ConsoleApplication::getTemplate()
```

### System information (as much as possible)
php 8.1

**Comment by alikon** [comment]
please test #38222
