### ISSUE TITLE
[4.2b3] New install, Operation timed out after 5013 milliseconds

### ISSUE THREAD

**Issue by OctavianC** [joomla/joomla-cms#38233]
### Steps to reproduce the issue
- Install latest 4.2.0 beta 3
- Open front or admin

### Expected result
Working pages :)

### Actual result
![image](https://user-images.githubusercontent.com/1422378/177480498-fe0c5298-b870-40c9-999d-08d36f093b5d.png)

     0 Operation timed out after 5007 milliseconds with 16384 out of 1204198 bytes received 

### Additional comments
So I've traced this to `plugins/system/webauthn/src/MetadataRepository.php`:

```php
$response = $http->get('https://mds.fidoalliance.org/', [], 5);
```

It times out after 5 seconds due to the 3rd param - my download speed is abysmal, not sure if related to my own internet or the hosting server...

![image](https://user-images.githubusercontent.com/1422378/177480448-b2060e61-a9a0-4baa-8802-5dbf0cf355ef.png)

Either way this shouldn't render the website unusable. Maybe catching the exception would be a temporary fix but this would still overload the URL, triggerring connections on every visit.
Can be fixed manually by downloading blob.jwt and renaming it to `cache/fido.jwt` and `administrator/cache/fido.jwt`

**Comment by richard67** [comment]
@nikosdion Could you have a look on it? Thanks in advance.

**Comment by nikosdion** [comment]
@richard67 https://github.com/joomla/joomla-cms/pull/38234

**Comment by nikosdion** [comment]
I'd say a single test by the affected user is enough for this trivial change. It already took me 50x longer than fixing it to open a PR. I am not wasting any more time on it.

**Comment by alikon** [comment]
please test #38234

**Comment by richard67** [comment]
@nikosdion Thanks a lot.

**Comment by nikosdion** [comment]
You're welcome! Sorry for not having a lot of time, it's gonna be a bit hectic the next few weeks as I'm finishing up pending work to maybe manage go on vacation for a week or two this August — I need it after working non-stop since 2019...
