### ISSUE TITLE
Tinymce Prohibited Elements field change not saving

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#38235]
### Steps to reproduce the issue
Open Tinymce plugin for editing
Remove 'script,applet,iframe' from the Prohibited Elements field
Save

### Expected result
Prohibited Elements field is empty

### Actual result
Prohibited Elements field still has 'script,applet,iframe'

**Comment by Quy** [comment]
See #29645 for context.

**Comment by Fedik** [comment]
> Remove 'script,applet,iframe' from the Prohibited Elements field
> Prohibited Elements field still has 'script,applet,iframe'

Because the field have default value. And cannot be "emptied".

For your case, replace 'script,applet,iframe' with 'potato', that will be a workaround :wink:

**Comment by joomdonation** [comment]
See the reason explained by @Fedik above and use his suggested workaround to solve this issue. As we could not do anything more here, I'm closing this issue.
