### ISSUE TITLE
[5.0] codemirror version 6

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38230]
A brand new release of codemirror is now available. 

> The only breaking change is that @codemirror/basic-setup has been renamed to just codemirror, and no longer exports EditorState (you can now create views by inlining the options to EditorState.create in the object given to the EditorView constructor, so you no longer need that to set up a minimal editor). All other packages should be entirely compatible with 0.20.0.

> This should be the last time you need to do invasive version shuffling—in the foreseeable future, releases will be boring and backwards-compatible, and covered by ^6.0.0 version ranges.

So from the sound of it there should be no issues with using it now. 

The only problem is that our js build scripts wont work with this version as the file and folder structure has changed

@fedik @dgrammatiko

**Comment by Fedik** [comment]
Yeah, that need some work, not for 4.2 for sure even if it does not have b/c issue ;)

**Comment by brianteeman** [comment]
@obuisard 4.3 ?

**Comment by obuisard** [comment]
I would prefer to be cautious and avoid issues with the build scripts BUT if we wait for Joomla 5.0, that means we won't have the update for another year... So, I do agree with updating to Codemirror v6, as long as with have the manpower for it.

**Comment by brianteeman** [comment]
https://codemirror.net/docs/migration/

**Comment by Fedik** [comment]
@dgrammatiko did you had any luck with it? 
I tried a bit, and it seems we have to compile whole own bundle, including lang. syntaxes. Also probably drop existing themes.

Sounds like here we will have a zero backward compatibility. Not good, not bad, just what it is.

**Comment by Fedik** [comment]
This is done in https://github.com/joomla/joomla-cms/pull/41070
