### ISSUE TITLE
Webservices API language allways set to en-GB

### ISSUE THREAD

**Issue by mgscreativa** [joomla/joomla-cms#38237]
Hi! Joomla! webservices api language somehow defaults to en-GB despite I have set both, front and back languages in J! admin to default to es-ES. Checking the api/languages folder I can see that both languages are there but they are quite little in lang files, I guess that's because most of the lang constant get loaded from the component itself, like in my case, that a table check produces some lang output that gets loaded from my administrator/com_component/language/en-GB, but it should look for administrator/com_component/language/es-ES as as long as I understand, as this is the default admin language set.

### Steps to reproduce the issue
* Create a simple copmponent with the basic admin files for inserting data from a model/table
* Create a new webservice plugin and a new api controller and view
* Set Joomla! default language to something different to en-GB

### Expected result
Text output from webservice API calls should get translated to default admin lang (es-ES in my case)

### Actual result
All text output from webservice API calls got translated to en-GB

### System information (as much as possible)
Apache
MariaDB 10.3.34
PHP 7.4.30
J! 4.1.5

### Additional comments

*Step debugger showing that all lang files loaded in a webservice API request got to en-GB*
![screen shot 2022-07-06 at 13 20 14](https://issues.joomla.org/uploads/1/f909895808760ffc45e179eaa52ca7fc.png)

*It seems that the webservices API somehow expects to be multi language*
![screen shot 2022-07-06 at 13 28 20](https://issues.joomla.org/uploads/1/0b36240177ebcf8ad4874333113b7b8c.png)

**Comment by richard67** [comment]
If I understand this right, having other languages than en-GB isn't supported yet: https://docs.joomla.org/Joomla_Api_Specification#Language_Negotiation

**Comment by mgscreativa** [comment]
Thanks  a lot @richard67!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38237">issues.joomla.org/tracker/joomla-cms/38237</a>.</sub>
