### ISSUE TITLE
[BUG][J4][4.1.5] Array to string conversion in modules/mod_finder/src/Helper/FinderHelper.php on line 48

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#38252]
### Steps to reproduce the issue

When using advanced search and filter, searching something with filter enabled (for example set language to all - see screenshot)

![bug](https://i.imgur.com/GQKLtTr.png)

will produce this warning:

**Warning: Array to string conversion in modules/mod_finder/src/Helper/FinderHelper.php on line 48**

Following foreach gets array instead of string in $v variable.
```
foreach ($uri->getQuery(true) as $n => $v)
		{
			$fields[] = '<input type="hidden" name="' . $n . '" value="' . $v . '">';
		}
```

### Expected result
- no warning, managing the value in array, not the string

### Actual result
- Warning: Array to string conversion in modules/mod_finder/src/Helper/FinderHelper.php on line 48

### System information (as much as possible)
Joomla 4.1.5
PHP 8.1.6

**Comment by Fedik** [comment]
how did you get language filter there? I do not have :) 
However I tried with other fields: Type, Author, and did not get such error

**Comment by PhocaCz** [comment]
> how did you get language filter there? I do not have :)

When some of finder plugin has this rule:

```// Add the language taxonomy data.
$item->addTaxonomy('Language', $item->language);
```

**Comment by andrescmhz** [comment]
I have the same problem

**Comment by Hackwar** [comment]
Is this still an issue? The line referenced here is now an empty line and I did fix some issuers there some time ago.

**Comment by Hackwar** [comment]
Closing since there has been no response in the last 10 days. I'm rather certain that the bug has been fixed in the past already.
