### ISSUE TITLE
Custom plugin name can't started with plg_ 

### ISSUE THREAD

**Issue by ZhukDmitry** [joomla/joomla-cms#38254]
### Steps to reproduce the issue
When you try to create custom plugin with name like "plg_MyPlugin" - it doesn't work in Joomla 4

But if you create plugin plgMyPlugin - it works

### Expected result
Plugin name can have name started with plg_

### System information (as much as possible)
Joomla! Version | 4.1.5
PHP Version | 8.0.18

**Comment by chmst** [comment]
Did that work in J3? 
It surely works if you add the plugin group as in all other plugins: plg_content_nameoftheplugin.

**Comment by GHSVS-de** [comment]
Can't confirm this issue. I created a test plugin here: https://github.com/GHSVS-de/plg_mybaseplugin

As long as the mandatory attributes `type` and `group` are configured correctly in the mandatory manifest XML the `name` of the plugin can be whatever you want.

See https://github.com/GHSVS-de/plg_mybaseplugin/blob/main/mybaseplugin.xml#L2-L3

You can also use a custom group (= folder in /plugins/) if you want.

The demo plugin can be installed, activated, opened, saved and uninstalled without any issues:
https://github.com/GHSVS-de/plg_mybaseplugin/raw/main/plg_mybaseplugin.zip

**Comment by chmst** [comment]
Same here, also checked with capital letters. So please @ZhukDmitry specify what exactly does not work - error message? How did you install your plugin? you also can append your manifestfile here.

**Comment by ChristineWk** [comment]
Difference between : plg_myBasePlugin and plg_**M**yPlugin
After the underscore = starts with a capital letter = don't know if relevant?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38254">issues.joomla.org/tracker/joomla-cms/38254</a>.</sub>

**Comment by ZhukDmitry** [comment]
It works in J3, I just trying convert to support J4

Here my test plugin
-- manifest
<?xml version="1.0" encoding="utf-8"?>

<extension type="plugin" version="4.0.0" method="upgrade" group="content">
    <name>PLG_ZHOSMMAP</name>
    
    <creationDate>Sep 2018</creationDate>
    <author>Zhuk Dmitry</author>
    <authorEmail>ZhukDL@gmail.com</authorEmail>
    <authorUrl>http://zhuk.cc</authorUrl>
    <copyright>Copyright</copyright>
    <license>http://www.gnu.org/licenseses/gpl-2.0.html GNU/GPLv2 or later</license>
    
    <version>3.22.1.11</version>
    
    <description>PLG_ZHOSMMAP_DESCRIPTION</description>
    <files>
        <filename plugin="plg_zhosmmap">plg_zhosmmap.php</filename>
        <filename>index.html</filename>
        <folder>language</folder>
        <folder>helpers</folder>
    </files>
         
    <languages>
                <language tag="en-GB">language/en-GB/en-GB.plg_content_plg_zhosmmap.ini</language>
    </languages>
        
        <updateservers>
                
                <server type="extension" priority="1" name="Zh OSM Map Plugin Update Site">http://zhuk.cc/update/plg_zhosmmap/extension.xml</server>
        </updateservers>
</extension>


--- plugin code

defined('_JEXEC') or die('Restricted access');

use Joomla\CMS\Component\ComponentHelper;
use Joomla\CMS\Factory;
use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;
use Joomla\CMS\Router\Route;
use Joomla\CMS\Plugin\CMSPlugin;

class plgContentplg_zhosmmap extends CMSPlugin
{    

    protected $app;

    public function onContentPrepare($context, &$article, &$params, $page = 0)
    {

		$article->text = "Hello";
    }

}

**Comment by ZhukDmitry** [comment]
My plugin name
filename plugin="plg_zhosmmap"

and plugin class
class plgContentplg_zhosmmap extends CMSPlugin

it is not processed

if I change name and files to any other (for example plgzhosmmap), - it works

**Comment by ZhukDmitry** [comment]
Probably I must to name my plugin without plg_, but I did it like the other extensions like rules for j3 (component = com_, module = mod_, and so on)

**Comment by brianteeman** [comment]
Just look at how all the core plugins are named and structured.

**Comment by GHSVS-de** [comment]
I think (don't know for sure) it's this line that is the reason that plugin base file/classes don't work any longer if they start with `plg_` or (which is a bit harsh) contain `plg_`
https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Extension/ExtensionManagerTrait.php#L87

Later in the chain loadPluginFromFilesystem() can't find the plugin base file, better: can't find the class:
https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Extension/ExtensionManagerTrait.php#L192

That's new but expected from my point of view. Maybe the plugin lagacy mode works different??
