### ISSUE TITLE
Configuration - Component name for Content is Articles? 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#38250]
### Steps to reproduce the issue
Just wanted to change permissions for com_content. 
Used to find the component "content" near "contact" it took me some time to find "articles = content". 

Opened Configuration 
![grafik](https://user-images.githubusercontent.com/1035262/178159167-6d5db120-3db1-4237-87dc-af836d0a7212.png)

Maybe it is only the point of view of a developer and not of other users? 

Would be nice to get some opinions here from "outside development"

**Comment by Kostelano** [comment]
All articles are content, but not all content is articles. In my opinion everything is right now.

**Comment by ReLater** [comment]
But the component is "Content" (com_content) that can be configured there. And the headline in left sidebar is "Components". Therefore I understand the input of chmst.

Not that I care ;-) 
I never use that configuration view.

**Comment by brianteeman** [comment]
The heading in the sidebar is Content but this contains several things (com_content, com_fileds, com_modules, com_workflows).
The heading of the com_content component is Articles so it is correct as it is right now. I can however see the confusion from a developer point of view but it would be inaccurate to rename this

**Comment by ReLater** [comment]
> The heading in the sidebar is Content

I talked about the white sidebar of the configuration view, not the sidebar menu. There the title is "Component".

**Comment by brianteeman** [comment]
Even then the names os all the items in the white sidebar are the user friendly names of the components not the developer friendly version eg Mail templates not mails, Smart search not finder, etc

**Comment by chmst** [comment]
Thanks for your answers! I close this, it is not really an issue but an example how we sometimes mix terms.
