### ISSUE TITLE
[4.2] webauthn missing string?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38260]
# [Joomla 4.2 Registration](https://app.tango.us/app/workflow/4422d7e5-1845-4141-a3e8-75cdfe48f514?utm_source=markdown&utm_medium=markdown&utm_campaign=workflow%20export%20links)

__Date:__ July 12, 2022

__Author:__ Brian Teeman

__Source:__ [Tango](https://app.tango.us/app/workflow/4422d7e5-1845-4141-a3e8-75cdfe48f514?utm_source=markdown&utm_medium=markdown&utm_campaign=workflow%20export%20links)

***

## 2. Click on Users
![Step 2 screenshot](https://images.tango.us/public/screenshot_fa5bc2b4-ddbc-4e2b-a23e-dbaa36d77036.png?crop=focalpoint&fit=crop&fp-x=0.0341&fp-y=0.3286&fp-z=3.0639&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A872)

## 3. Click on Manage
![Step 3 screenshot](https://images.tango.us/public/screenshot_34cad5bd-7f15-4b0c-b04f-887064203e8d.png?crop=focalpoint&fit=crop&fp-x=0.0393&fp-y=0.3744&fp-z=3.0428&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A872)

## 4. Click on  Options
![Step 4 screenshot](https://images.tango.us/public/screenshot_6b8cd14f-2959-42d1-8f3e-4bfa7c9343af.png?crop=focalpoint&fit=crop&fp-x=0.8940&fp-y=0.1141&fp-z=2.8817&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A872)

## 5. Set Allow User Registration to Yes
![Step 5 screenshot](https://images.tango.us/public/screenshot_6567d336-eb69-44f5-abe4-e1b2b23ae875.png?crop=focalpoint&fit=crop&fp-x=0.5552&fp-y=0.3911&fp-z=3.0094&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A872)

## 6. Click on  Save & Close
![Step 6 screenshot](https://images.tango.us/public/screenshot_7af137b5-febc-455a-9f01-4e1754b2155a.png?crop=focalpoint&fit=crop&fp-x=0.2661&fp-y=0.1141&fp-z=2.6158&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A872)

## 7. Open the front end of the site
![Step 7 screenshot](https://images.tango.us/public/screenshot_94048791-3672-493a-9d44-8e102929f3b9.png?crop=focalpoint&fit=crop&fp-x=0.8898&fp-y=0.0378&fp-z=2.9301&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A872)

## 8. Click on Create an account 
![Step 8 screenshot](https://images.tango.us/public/screenshot_50077ac7-4fe9-4b91-92be-2b0ea6076027.png?crop=focalpoint&fit=crop&fp-x=0.7255&fp-y=0.7311&fp-z=3.1947&w=1200&mark-w=0.2&mark-pad=0&mark64=aHR0cHM6Ly9pbWFnZXMudGFuZ28udXMvc3RhdGljL21hZGUtd2l0aC10YW5nby13YXRlcm1hcmsucG5n&ar=1920%3A872)

# Is this just a missing string or is it something more?

![image](https://user-images.githubusercontent.com/1296369/178463983-be829fa3-50cc-40db-9fb9-8bebfff7e719.png)

cc @nikosdion @roland-d

**Comment by nikosdion** [comment]
This must've been present since 4.0. The problem is that the WebAuthn plugin loads even in the new user page since Joomla uses the same context in the new user page, the profile overview page and the edit profile page. If you ask me, that's a shortcoming of Joomla.

I am currently busy with other work. I can take a look at it sometime later this week and tell you if we can do anything about it.

**Comment by brianteeman** [comment]
Repeating the exact same steps with joomla 4.1.5 shows that this is new to joomla 4.2

![image](https://user-images.githubusercontent.com/1296369/179697239-26e18fd6-ba62-431b-ad1b-54f0ba40ffc9.png)

**Comment by brianteeman** [comment]
It is crazy that 4.2 will be launching with a major new feature and the first impression for a user will be less than optimal.

This really should be a release blocker

@roland-d @richard67

**Comment by roland-d** [comment]
@brianteeman Thanks for the heads-up, this got out of sight, but I agree, this must be fixed before release. I am working on it. Also confirmed this language string is missing.

**Comment by roland-d** [comment]
We have a pull request #38341
