### ISSUE TITLE
[4.1] Tags in menu require extra click

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#38272]
### Steps to reproduce the issue

Create a menu item and then in tag field try to enter multiple tags.

### Expected result
hitting enter makes cursor ready to create next tag, the same way as it does in articles.

### Actual result
cursor loses focus and requires clicking in field to create another.

### System information (as much as possible)

[systeminfo-2022-07-14T08_20_34+00_00.txt](https://github.com/joomla/joomla-cms/files/9109953/systeminfo-2022-07-14T08_20_34%2B00_00.txt)

**Comment by chmst** [comment]
Confirmed - the input field loses focus when a new tag  was entered. 

But the tags field is always the same, in all views. What is the difference to articles?

**Comment by N6REJ** [comment]
> Confirmed - the input field loses focus when a new tag was entered.
> 
> But the tags field is always the same, in all views. What is the difference to articles?

idk, I know it did it ONCE properly but its not now.. maybe I was seeing things

EDIT: ok, I figured out when it keeps focus... if you select a previous tag from the drop down then focus is maintained

**Comment by brianteeman** [comment]
This is exactly the same in all views.

**Comment by Hackwar** [comment]
You should not be able to type in custom tags in menu items. See #39154. That PR should make this issue obsolete as well. Closing this one.
