### ISSUE TITLE
Add SVG-extension to media

### ISSUE THREAD

**Issue by svermassen** [joomla/joomla-cms#38270]
### Steps to reproduce the issue
I have several sites that use SVG-image-files.
Eg: YOOtheme.
These are not showing in the Media-manager.
Now I add the extension manual to the settings for the visualisation and the possibility to upload.

### Expected result
With no manual intervention should be these files be visible and can be uploaded.

### Actual result
These are not showing in the Media-manager.
Now I add the extension manual to the settings for the visualisation and the possibility to upload.

**Comment by ssnobben** [comment]
+ 1 **Add SVG-extension to media**

**Comment by svermassen** [comment]
I mean, I should be standard in the Joomla Core be added.
I already added it manualy

**Comment by alikon** [comment]
i think this is expected behavior, should be responsibility of the admin to decide what to allow
closing as expected

**Comment by Quy** [comment]
Duplicate request #38068
