### ISSUE TITLE
No item menu for delete article to cart in any category with enable Workflows

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#38274]
The description of the problem and the reason are indicated in the ISSUE header .

![image](https://user-images.githubusercontent.com/6898474/178986009-be04c710-ce14-4674-a492-e050dc28396f.png)

In "Batch process the selected articles" item menu there is also no this item.
 
 
![image](https://user-images.githubusercontent.com/6898474/178991221-263ce746-b02a-49fe-a7b6-8cfbfc2dfa06.png)

![image](https://user-images.githubusercontent.com/6898474/178990271-9291b474-28fb-4030-a97d-3f4042003881.png)
![image](https://user-images.githubusercontent.com/6898474/178990324-cc851326-228d-4450-99d9-caab7526d7cc.png)
![image](https://user-images.githubusercontent.com/6898474/178990350-c998ee74-e92f-4aac-b917-fae36691581c.png)

The problem is Stage Wrorkwlows.
As soon as I turn off all Stages except one base Stage. So immediately there is a menu item for removing materials in the basket.
But if there are several Stages, the menu item Delete in the basket disappears and it does not exist.

But now everything has worked.
.
I opened the "Transitions: Basic Workflow", after which I opened "Trash". Re-saved "Trash".
Then everything worked. There are menu items in the articles.

This is strange. Everything should work without re-serving "Transitions".
Users will face a problem and will not know what to do.

**Comment by chmst** [comment]
I am sorry, but I don't understand your issue.
This is what I understand: You want to build a shop. An item in this shop can be in basic stage - a customer can order, then will pay.
Now you need a transition "delete form cart" ? I think this is a question for the forum forum.joomla.org

**Comment by korenevskiy** [comment]
@chmst 
 What I do build a SHOP is irrelevant . This is just an example that after adding new transitions and statuses, it is not possible to delete an article in the list of materials.
I created transitions and statuses for article products.
But after I created the above.
 It turns out that I stopped being able to delete the article.
 Removal transitions to the basket are available. Also, if you go to the article editor, you can see the deletion switch to the basket. But after that, you need to keep the article.
But to delete an article in the list of articles in the basket is gone.
 There is an opportunity in the article, but there is no possibility in the list of articles.

But now everything has worked.
 I did not create transitions, and new statuses.
 I once turned off the status and turned it on again. After which the transitions in the list of articles appeared.
 I think this is a CMS Joomla error.
But I was not able to find the cause of the error.

**Comment by brianteeman** [comment]
I am going to close this. It is very difficult to establish exactly the issue due to the poor automatic translation. As the user reports that now everything works I am closing. It can always be re-opened
