### ISSUE TITLE
[4.1.5] Template Editing in Firefox cuts off editing area

### ISSUE THREAD

**Issue by bayareajenn** [joomla/joomla-cms#38282]
### Steps to reproduce the issue
1. Using Firefox
2. Login to the backend of Joomla
3. Go to Extensions -> Templates -> Templates (or however you get there with the new dashboard/menu)
4. Click on Cassiopeia and choose any override file

### Expected result
To see all the code regardless of browser

### Actual result
In Firefox, code is cut off forcing the user to click inside the box and press F10 to see all the code. Chrome works fine.

### System information (as much as possible)
Windows 10
Firefox version 102.0.1

### Additional comments
I disabled all browser extensions and the issue persisted. Worth a try.![screen shot 2022-07-15 at 13 52 53](https://issues.joomla.org/uploads/1/767e56b96282e805ecf976794eb5eada.jpg)
![screen shot 2022-07-15 at 13 52 54](https://issues.joomla.org/uploads/1/1ae4001367d622d6cd126594b2986ddd.jpg)

**Comment by brianteeman** [comment]
If you change the default editor to codemirror and then edit an article do you have the same problem there?

**Comment by bayareajenn** [comment]
Good question. The default editor is set to None. Problem persists no matter which editor is selected (including None). Tried them all. The User editor is set to "use default" as well.

**Comment by ChristineWk** [comment]
had that too (month ago) and also, if using new installation.
Saw this:
![screen shot 2022-07-15 at 15 39 27](https://issues.joomla.org/uploads/1/ee5fecaa73b059f08b8b4c65ab2860dd.png)

solved it with this:

`.CodeMirror-gutters {
left: 0px !important;  
}`
administrator/atum > user.css
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38282">issues.joomla.org/tracker/joomla-cms/38282</a>.</sub>

**Comment by brianteeman** [comment]
> Good question. The default editor is set to None. Problem persists no matter which editor is selected (including None). Tried them all. The User editor is set to "use default" as well.

Thats not what I asked.

> If you change the default editor to codemirror and then edit an article do you have the same problem there?

**Comment by bayareajenn** [comment]
![article-editing-codemirror-firefox](https://user-images.githubusercontent.com/5952595/179272609-10b9d724-ab83-4a7f-960f-3e83fb786a73.jpg)
Happens with codemirror in article editing as well.

**Comment by brianteeman** [comment]
ok - that rules some possibilities out and confirms that its the gutter-width calculation causing the problem. This is something that codemirror has had problems with for many years

**Comment by bayareajenn** [comment]
That's unfortunate, but good to know. If there's something else you'd like me to test, let me know. I'll read more slowly next time. Thanks for taking a look.

**Comment by chmst** [comment]
I am on win11 and cannot repliace this effect, Maybe it is the OS?

**Comment by mariantanase** [comment]
I reported the same behavior (not solved yet), with issue #37088

**Comment by bayareajenn** [comment]
@chmst Could be the OS. I don't have any idea how to troubleshoot what that setting could possibly be. But I'll see if I can do some searching and see what I can dig up.
@mariantanase thanks for linking your closed issue. That confirms what @chmst said with it being a Windows 10 specific issue.
I'll let y'all know what I can figure out .. or if I cannot figure anything out.

**Comment by chmst** [comment]
Thank you @mariantanase and @bayareajenn  - this is one of these highly frustrating issues. Every little information can help here. @ChristineWk do you remember which OS you had at this time and what happened  then? If I read your post it seems that it is resolved now for you?

**Comment by mariantanase** [comment]
>  That confirms what @chmst said with it being a Windows 10 specific issue. 

I'm not very sure for that. In my case I used the same os (Windows 10) and the same Firefox versions, but on different computers.

**Comment by ChristineWk** [comment]
WIN 10, FF. 
After an update from J 4.0.6 to 4.0.7-dev I had this phenomenon for the first time. Unfortunately I didn't know about #37088, otherwise I would have answered there at the time. I don't know why this inline segment existed (see screenshot).
If I use above code, it's OK.

**Comment by mariantanase** [comment]
> 
> solved it with this:
> 
> `.CodeMirror-gutters { left: 0px !important; }` administrator/atum > user.css

This fix is working for me !

**Comment by rgtr** [comment]
Hi 

I have windows 7 pro and windows 8 and have the same problem.

It happens when you save the file e.g. user.css
Pressing F10 to go full screen is fine. 
When you press ESC you get back to a proper display [gutter free]

Richard<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38282">issues.joomla.org/tracker/joomla-cms/38282</a>.</sub>

**Comment by rgtr** [comment]
Hi
I use JCE and have that set as default editor. Tried changing to CodeMirror but makes no difference
Used the code mirror fixed given above in Atum ...
However it is clear that CodeMirror is used in Atum when editing css files.
Problem sort of goes away, but line numbers then display on top of my css code ...
My guess there is a bug somewhere.
Richard
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38282">issues.joomla.org/tracker/joomla-cms/38282</a>.</sub>

**Comment by rgtr** [comment]
Hi
Yup - that works fine now. After making the change to the css you need to quit and close Firefox.
Richard

**Comment by rgtr** [comment]
Firefox 110.0.1 on Win 11 Pro
It is something to do with caching I guess.
R

**Comment by Quy** [comment]
Can you check the `left` property before changing the css?

![38282-codemirror](https://user-images.githubusercontent.com/368084/223508314-74244e7a-58e3-44e0-bf80-d142288d5cd6.png)

**Comment by Quy** [comment]
Closing as no longer reproducible.
