### ISSUE TITLE
[4.2] com_media. config. upload_mime_illegal used?

### ISSUE THREAD

**Issue by GHSVS-de** [joomla/joomla-cms#38280]
### Problem identified
The `config.xml` of `com_media` has a field named `upload_mime_illegal`. I cannot find any use of this parameter in the 4.2-dev core.

### Open questions
Remove it?

**Comment by brianteeman** [comment]
I can confirm that this is not used in j3 or j4

**Comment by GHSVS-de** [comment]
Thank you. We come nearer to a "Remove it".

---
I don't know if relevant anyhow or for Joomla 4 in particular:

@ChristineWk made some investigations and found via some old Joomla issues a 3rd component https://github.com/jmcameron/attachments of @jmcameron that uses this parameter.

I hereby ping him.

**Comment by zero-24** [comment]
Not sure whether its a good idea to remove it? Maybe better implement it here: [checkMimeType](https://github.com/joomla/joomla-cms/blob/09d14c65f25f9bc76f2698e69c4d7b35f43bc848/libraries/src/Helper/MediaHelper.php#L126)

**Comment by brianteeman** [comment]
Core has not used this field in j3  or j4

**Comment by GHSVS-de** [comment]
In J3 until 3.7.0 but removed in 3.7.1:
https://github.com/joomla/joomla-cms/commit/0fc3778861fa20c055ea00870c641a06bc692ecb#diff-393a2d3b46d95b063033351529f96afe6b5044c36f09f2e07cdbc3a36077be3bL156

**Comment by Quy** [comment]
PR #39196

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39196 . Thanks in advance.

**Comment by ReLater** [comment]
PR https://github.com/joomla/joomla-cms/pull/39196 is closed. Reopen here? If you think it's worth it.

**Comment by richard67** [comment]
Reopening as pull request #39196 has been closed.

**Comment by ReLater** [comment]
Please test pr https://github.com/joomla/joomla-cms/pull/39452

**Comment by ReLater** [comment]
Sorry! I made a mistake. New pr will follow.

**Comment by ReLater** [comment]
Please test pr https://github.com/joomla/joomla-cms/pull/39453

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39453 . Thanks in advance.
