### ISSUE TITLE
Feature request concerning PSR12 code style since Joomla 4.2

### ISSUE THREAD

**Issue by GHSVS-de** [joomla/joomla-cms#38288]
### Is your feature request related to a problem? Please describe.
I have to use higher zooms on some days in my code editors. Otherwise the code lines are jumping around in my brain. Short: I can't read them as separate lines.

Therefore I use settings "Display tabs as 2 spaces" (sometimes 1). This way I don't have to scroll horizontally too often in my editor to be able to read most of the lines without enabling line wraps.

Now we have new rules "No tabs anymore and each tab is replaced by 4 spaces". There are no settings in editors that replace 4 spaces with 2 or 1 space while reading but are still 4 spaces in reality.

I can't read my own code anymore after I've ran a PSR-12 fixer.

It is time consuming to switch the code back and forth (tabs to spaces and back etc.) or to revert PSR12 fixed commits in my branches.

### Describe the solution you'd like
An automatic PSR12 fixer in this repository that makes it possible to continue using tabs when creating a pr.

**Comment by brianteeman** [comment]
> An automatic PSR12 fixer in this repository that makes it possible to continue using tabs when creating a pr.

That's not going to help you as when you pull the latest branch everything will be psr12

**Comment by Fedik** [comment]
A bigger monitor, or second monitor  (if you use laptop) will help much more than that :wink: 
24"+

**Comment by ReLater** [comment]
I pull it, tell my editor to change indentions to tabs. Work on with tabs and provide the pr with tabs. If changes are necessary I can work on without any additional actions.

> A bigger monitor, or second monitor (if you use laptop) will help much more than that

Bullshit comment. I only use large monitors. Where do accessibility criteria start here?

All PSR12 changes where made automatically in 4.2-dev. Why shouldn't that be possible after merges.

**Comment by brianteeman** [comment]
> All PSR12 changes where made automatically in 4.2-dev. Why shouldn't that be possible after merges.

of course it is and hopefully that will happen. Wont really help though as all the existing code is now spaces etc

**Comment by Fedik** [comment]
> Bullshit comment. I only use large monitors. Where do accessibility criteria start here?

Please keep your emotion with you. That was a friendly recomendation.
Try to work on 14-15" laptop, or smaller screen, then read my comment again.
