### ISSUE TITLE
[4.2] Deprecated on login

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38296]
### Steps to reproduce the issue
Create a login menu item
Enable maximum error reporting
Visit login link in the front end

### Expected result
no notices etc

### Actual result
```
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in components\com_users\tmpl\login\default_login.php on line 36

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in components\com_users\tmpl\login\default_login.php on line 48
```

### System information (as much as possible)
php 8.1

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/38300 should fix it. Please test, thanks !
