### ISSUE TITLE
[4.2] Redirect on login url error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38297]
### Steps to reproduce the issue
Create a login menu item
Set the login menu item to redirect to any menu item on login
Visit site and login

### Expected result
Redirected to example.com/menuitem

### Actual result
redirected to example.com/menuitem?lang=

### System information (as much as possible)
php 8.1

### Additional comments
This is a clean install with no additional languages

**Comment by brianteeman** [comment]
no problems with 4.1.5

**Comment by joomdonation** [comment]
Look like it causes by this PR https://github.com/joomla/joomla-cms/pull/37614

**Comment by brianteeman** [comment]
what a suprise :(

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/38299 should fix this issue. Please help testing, thanks !
