### ISSUE TITLE
Smart Search, indexing error: The category must have a title

### ISSUE THREAD

**Issue by danpdanp** [joomla/joomla-cms#38295]
### Steps to reproduce the issue
After updating to Joomla 4.1.5 (of a Joomla 3.10.10 site that already used smart search and in which indexing was successful), during the indexing of the search, it stops at about 1/4 returning the error message "An error has occurred. The category must have a title".

### Expected result
Complete indexing at 100%, or I would like to know specifically what is the problem (the category) that prevents indexing from completing

### Actual result
Smart Search Content Indexing stops with message: An error has occurred. Category must have a title.

### System information (as much as possible)
database mysql 10.3.24-MariaDB
php 7.4.22
web server Apache
Joomla! 4.1.5 Stable

### Additional comments
I checked in all categories (even in the database) and there is none without a name. I checked the author / article pairings and there is no "orphaned" author article, as assumed here: https://github.com/joomla/joomla-cms/pull/36759. I ask for help

**Comment by ReLater** [comment]
That's a known issue. Please see https://github.com/joomla/joomla-cms/pull/36759
Try the fix https://github.com/joomla/joomla-cms/pull/36759/files

**Comment by danpdanp** [comment]
Resolved!
Thank you!

**Comment by richard67** [comment]
@danpdanp Thanks for testing. Could you report your successful test by going to the pull request in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/36759 , then using the blue "Test this" button at the top left corner, then selecting the appropriate test result (success) and submit? Thanks in advance.

**Comment by richard67** [comment]
Closing as having a pull request. See #36759 .
