### ISSUE TITLE
[4.1] Overflow in "Extensions: Manage" when screen is narrow

### ISSUE THREAD

**Issue by impressionestudio** [joomla/joomla-cms#38293]
### Steps to reproduce the issue
In the administration area, go to "Extensions > Manage > Extensions".
Then change the window state of the browser from maximum to normal.
You will notice that a horizontal slider will appear and the page parts (header, filters, list) do not align right.

### Expected result
I guess there should not be a horizontal scrollbar and/or the page parts should align right.

### Actual result
The page should behave like "System > Manage > Plugins".

### System information (as much as possible)
Joomla 4.1.5.

### Additional comments
Please see the following video to understand easier.
https://demo.impression-estudio.gr/_issue-tracker/manage-extensions-overflow.mp4

Relative issue: https://issues.joomla.org/tracker/joomla-cms/32674

**Comment by brianteeman** [comment]
Joomla 4.2 has a new feature that lets you decide which columns to display

**Comment by Quy** [comment]
Duplicate issue #32820.

**Comment by impressionestudio** [comment]
The new feature to select the columns to display is very useful.
I searched for a relative issue before I add this one but I couldn't find it.
