### ISSUE TITLE
Home Dashboard Notifications Panel Text Inconsistency

### ISSUE THREAD

**Issue by nineoo** [joomla/joomla-cms#38298]
### Steps to reproduce the issue
View Notifications Panel where published on Home Dashboard.![screen shot 2022-07-19 at 08 39 23](https://issues.joomla.org/uploads/1/1ffec1e0d9ee3b6faf180b3af8f05177.jpg)

### Expected result
Text formatting consistent.

### Actual result
3 items have a full stop at end.

### System information (as much as possible)
Joomla! 4.1.5 Stable [ Kuamini ] 21-June-2022 14:00 GMT

### Additional comments
A tiny issue in the grand scheme of things but ought to match other items as it's part of first impression of Joomla 4.

**Comment by brianteeman** [comment]
Nothing core can do about the text string from akeeba backup

**Comment by nineoo** [comment]
Hi Brian, thank you. It's certainly no big deal but thought it was worth getting it checked.

I ought to have included the whole Dashboard in the screenshot as it was compared to them - sorry about that! You could take the view the other panels (Site and System) have titles whereas the notifications ones are statements, hence the use of a full stop. I note the Download Keys entered correctly is also missing the full stop too, so I'm guessing from what you said, that one is not output by Joomla core either given that unless extension keys are used it won't appear.

This was not my observation, it was picked up in an intro to Joomla 4 session by a sharp eyed administrator - so that was their first impression of the new Dashboard - and it being on a giant screen didn't help!
