### ISSUE TITLE
mod_quickicon.php listed in XML manifest file is missing - Is it regular?

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#38307]
Just updated to 4.2 RC1 via Testing process on a 4.2 beta version and I noticed that mod_quickicon.php listed in XML manifest file is missing.
Is this regular?
Home Dashboard is still displaying normally though.

**Comment by richard67** [comment]
No, it is not regular, it's a mistake which does not have an impact on functionality.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38309 . Thanks in advance.
