### ISSUE TITLE
[4.2 RC1] Feed display module not working

### ISSUE THREAD

**Issue by conseilgouz** [joomla/joomla-cms#38310]
### Steps to reproduce the issue
Create a Feed display module.
Enter https://www.joomla.org/announcements.feed?type=rss in Feed URL parameter
Enter Sidebar-right as position (using cassiopeia template)

### Expected result
Display Feed infos.

### Actual result
Feed display module shows "Feed not found" error in all cases.

### System information (as much as possible)
Joomla 4.2 RC1
PHP 8.1

### Additional comments
Seems to be related to fix #38095 
Librairies/src/Feed/Parser/RssParser.php : line 355 makes RSS reader point to far in RSS file.

**Comment by conseilgouz** [comment]
maybe same issue in AtomParser.php

**Comment by conseilgouz** [comment]
> 

Nope : Atom is OK

**Comment by richard67** [comment]
> Seems to be related to fix https://github.com/joomla/joomla-cms/pull/38095
> Librairies/src/Feed/Parser/RssParser.php : line 355 makes RSS reader point to far in RSS file.

@wilsonge Could you have a look?

**Comment by conseilgouz** [comment]
Atom Parser seemed to be ok, but it is not :   $this->stream->getAttribute('version') is always empty.

In RssParser.php and AtomParser.php, when calling initialise function, XML reader is already on rss or feed record due to feedfactory.php lines 68 to 77 (skip ahead to the root node). 
In both cases, $this->moveToNextElement() is pointing to next element, so  $this->stream->getAttribute('version') is always empty.
In RssParser.php, calling $this->moveToNextElement('channel') moves XML reader to end of the file, causing empty file message.
In AtomParser.php, moveToNextElement being done earlier (line 194), everything seemed to be ok (except $this->version).

**Comment by richard67** [comment]
Closing as having a pull request. See #38312
