### ISSUE TITLE
[4.2] Update Bootstrap to latest 5.2

### ISSUE THREAD

**Issue by dgrammatiko** [joomla/joomla-cms#38323]
### Steps to reproduce the issue
[Bootstrap 5.2](https://blog.getbootstrap.com/2022/07/19/bootstrap-5-2-0/) was released on July 19, 2022 thus 4.2 should NOT be released with 5.1 (meaning 4.x will stack for 6 months on an older version of BS)

### Additional comments

I would expect this to be a RELEASE BLOCKER

**Comment by wilsonge** [comment]
As our release candidate also came out on the 19th I think it's _unlikely_ we shove this into 4.2 at this stage. But down to @roland-d and @fancyFranci who have bought it up in maintainers for discussion.

**Comment by roland-d** [comment]
I do not think this is a release blocker and it is too late to add this to 4.2 as the RC is already out. This can wait for version 4.3.

**Comment by dgrammatiko** [comment]
> I do not think this is a release blocker and it is too late to add this to 4.2 as the RC is already out. This can wait for version 4.3.

For people that DO NOT do any front end work of course this is not important. For front enders this is massive as BS5.2 transitioned everything (almost) to CSS Variables. Also the RC is out is just a convention, post a blog explaining why there will be another RC, do the update in the package.json and merge it then release the proper RC. Holding back the whole front end for 6 months is not a wise choice.

Anyways, I had to give it a shot but I'm closing this as it seems font end (what people actually sell/buy) is not really important for the maintainers.
