### ISSUE TITLE
[J4] Joomla! Help License page is blank

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#38326]
### Steps to reproduce the issue

Go to Administrator / Help / License

### Expected result

A licence document

### Actual result

Nothing

### System information (as much as possible)

Firefox on Mac, remote shared host.

### Additional comments

Console says: The loading of “https://www.gnu.org/licenses/old-licenses/gpl-2.0.html” in a frame is denied by “X-Frame-Options“ directive set to “sameorigin“. I think that means the remote site is blocking loading in a frame.

**Comment by sandewt** [comment]
I confirm this issue

@zero-24 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38326">issues.joomla.org/tracker/joomla-cms/38326</a>.</sub>

**Comment by zero-24** [comment]
I'm not sure how i can actually help here? gnu.org decided that its website can not be framed so i guess the help page needs to be changed and maybe just link to that page vs iframing that site?

**Comment by ceford** [comment]
I have copied the licence to a Help page. You can see it here: https://docs.joomla.org/Help4.x:License - so now it can be loaded from our Help Server like any other Help page. Someone needs to check the legal position!

**Comment by brianteeman** [comment]
legal is fine

**Comment by HLeithner** [comment]
@brianteeman when we are at this topic, other software like mobile apps list all used 3rd party packages including the license on a license page.

And since we are not only shipping GPL software it could make sense to list them too?

**Comment by brianteeman** [comment]
It could but I am not sure if it is required. Joomla itself is GPL and thats what this refers to.

**Comment by brianteeman** [comment]
please test #38366

**Comment by alikon** [comment]
closing as we have a pr #38366
