### ISSUE TITLE
Top menu in the Cassiopeia template being able to wrap menu items.

### ISSUE THREAD

**Issue by rambro** [joomla/joomla-cms#38336]
### Steps to reproduce the issue

Hi all, working on a the cassiopeia template in joomla 4.0. I have a number of menu items I would like to put in the top menu at certain times of the year, it seems to me that the cassiopeia top menu in the "menu position" will not wrap the menu items and cuts off some of the menu items at some point. Is there some way to make this top menu more flexible.  I will try to show with an attachment.

### Additional comments
I probably could reduce the font size of the menu items, in the top menu, but I would like the ability to have a more flexible top menu in cassiopeia.
![At some point the menu item gets cut off in my case it the about us menu item](https://user-images.githubusercontent.com/4724475/181627938-f491a1c8-c916-48ca-bf4f-dd7588b46fe3.jpg)
![see how the menu items in the top menu wrap around nicely in joomla 3x prostar template](https://user-images.githubusercontent.com/4724475/181627954-5ea4a753-edb2-4af7-bd21-d4ad1cb73a67.jpg)

**Comment by brianteeman** [comment]
You will need to add a little extra css which you can do by creating a file called user.css in your template with this code

```
.container-header .mod-menu {
   flex-wrap: wrap;
}
```

**Comment by rambro** [comment]
Brian,

Thanks, it worked!!! I also had the clear the cache in Mozilla Firefox.

**Comment by richard67** [comment]
So this issue can be closed?

**Comment by chmst** [comment]
@rambro I close this now. This area is for bugs in Joomla core. The supporters in forum.joomla.org will help you with building your website.
