### ISSUE TITLE
Helix Ultimate 2.0.10 (PHP 8 issues)

### ISSUE THREAD

**Issue by sparkktv** [joomla/joomla-cms#38348]
Testing PHP 8 in my localhost using MAMP. And running the latest version of Helix Ultimate and Helix Ultimate Template on Joomla 4.1.5. When I use PHP 8, it get the error 0
mb_strpos(): Argument #3 ($offset) must be contained in argument #1 ($haystack)
on every page of my site, but if I downgrade back to PHP 7.4 then the site works without issues. It is indeed a Helix issue as I switched over the the Joomla 4 default template Cassiopeia template and the site worked fine in PHP8. 
I'm just wondering when this will be fixed because the release notes say the latest version has PHP8 support but this doesn't seem to be the case.

**Comment by brianteeman** [comment]
You are asking the wrong people - you need to ask the makers of the Helix template.

**Comment by HLeithner** [comment]
Closing See brians answer.
