### ISSUE TITLE
PHP Notice:  Trying to get property 'id' of non-object

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#38357]
Just decided to examine server-side error.log and found numerous notices:

`[Sun Jul 31 08:13:42.671625 2022] [proxy_fcgi:error] [pid 3306697:tid 140328884639488] [client 67.46.151.63:54390] AH01071: Got error 'PHP message: PHP Notice:  Trying to get property 'id' of non-object in /var/www/site.com/libraries/src/Updater/Adapter/ExtensionAdapter.php on line 333`

Joomla 4.1.5
PHP 7.4.27

Unfortunately, I cannot remember what have been done since I worked on the site during a day.  There are various 3rd party extensions installed on the site, but this warning looks like something related to the core feature.

**Comment by brianteeman** [comment]
It is essential to know which extensions are installed as this error message is directly related to one of them
