### ISSUE TITLE
Multi-factor Authentication - RTL

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38364]
### Steps to reproduce the issue
the offset-sm-3 etc is causing issues on RTL as shown in the screenshots

## LTR

![image](https://user-images.githubusercontent.com/1296369/182108335-06d40d5b-e496-4cd5-b2eb-4b82b419937a.png)

## RTL

![image](https://user-images.githubusercontent.com/1296369/182108477-c438ee03-d1e4-4f32-8761-79c7632297b5.png)

**Comment by nikosdion** [comment]
Given that this is the example code [Bootstrap gives for checkboxes in horizontal forms](https://getbootstrap.com/docs/5.2/forms/layout/#horizontal-form) wouldn't it be a Bootstrap problem instead of a Joomla problem?

At the time of this writing the code Bootstrap suggests is the following:
```html
  <div class="row mb-3">
    <div class="col-sm-10 offset-sm-2">
      <div class="form-check">
        <input class="form-check-input" type="checkbox" id="gridCheck1">
        <label class="form-check-label" for="gridCheck1">
          Example checkbox
        </label>
      </div>
    </div>
  </div>
```

**Comment by brianteeman** [comment]
That would assume that joomla is using bs and its rtl correctly - hint we're not

If we were correctly using bootstrap rtl then the class offset-* would be margin-right when in rtl instead of margin-left

Sadly we're still not using it correctly so we have a mess of some overrides that J_M wrote and the rest is missing

**Comment by nikosdion** [comment]
Then the problem is how Joomla uses Bootstrap and not the HTML code in the MFA feature. Fix Joomla's use of Bootstrap and the problem corrects itself.

**Comment by brianteeman** [comment]
exactly

**Comment by brianteeman** [comment]
ok - spent the entire today but #38412
