### ISSUE TITLE
Joomla 4.1.5 Status Error 409 - Not possible to load the backend Template

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#38376]
### Steps to reproduce the issue
Occurs on a customers site and I also read about others on Facebook and in Forums having this issue on their hosting

### Expected result
Backend Template should load

### Actual result
Backend assets are marked with status 409 and not loaded

<img width="771" alt="grafik" src="https://user-images.githubusercontent.com/828371/182476819-aa93fcc9-da93-4264-83c7-df7c10c9eb7b.png">

I tried to solve it in various ways:
- Downloading Template Files and uploading again
- resetting htacces and removing all mod header stuff there
- clear cache, disable cache
- Creating a Child Template of Atum

The only way to fix it partially was to add 	$this->addStyleSheet(Uri::root() . 'media/templates/administrator/atum/css/template.css');
 into the index.php of atum template. 
(would need to add the other styles and scripts that way as well, but that does not look like a proper solution.

It seems as soon the versioning Number is added the file could not be loaded anymore.

**Comment by richard67** [comment]
@coolcat-creations In the title of this issue you wrote „403“. Shouldn’t it be „409“?

**Comment by brianteeman** [comment]
What browser?
Have you tested without any browser extensions?
What cache?
Are you using a cdn?

as a 409 is usually related to a local problem and not a server problem all of these are important to know/test

**Comment by coolcat-creations** [comment]
I tested with:
Safari on Mac
Opera On Mac
Chrome on Mac
Firefox on Mac 
With/ Without Privacy Mode
Without extensions 
Not using any CDN
Cache Disabled locally 
Cache Disabled on the Site
Htaccess empty / core / core with mod.headers commented out / normal
Checked Permissions / Repaired Database 


i read that the Status Code 409 might be Related to that a Request is delivering unexpected Data as something that is older than the version on the Server or something like that. So I had the Idea to implement the css without the Versioning Number in the Atum index.php as said above and that is fixing somehow the Error. So I think something is wrong with the Versioning Number.

**Comment by coolcat-creations** [comment]
> @coolcat-creations In the title of this issue you wrote „403“. Shouldn’t it be „409“?

Yes 409 sorry just tried to change it on my phone but it's not possible to scroll in the Edit window for me 😅

**Comment by richard67** [comment]
Would be interesting to know if this happens also with a 4.2-dev nightly build on the same environment.

**Comment by richard67** [comment]
… or if it happens also with older 4.1 or 4.0 versions.

**Comment by brianteeman** [comment]
Do you have any other sites o the same host?

**Comment by coolcat-creations** [comment]
Site was an Upgrade from Joomla 3.10.10. to 4.1.5 
There are other sites on the same host, Joomla 3 works well, Joomla 4.1.5 clean install same error.

**Comment by brianteeman** [comment]
ok well thats good news as it clearly identifies that the issue is somewhere in the hosting config/setup even if we dont know yet what is causing it. Would it be possible to get the domain name of the clean install so we can check the response headers etc. Perhaps the host as a cahing layer of their own that is in play?

**Comment by coolcat-creations** [comment]
I am having the Joomla Kids Lectures this week, I will contact the customer if its ok and share it as soon I can

**Comment by coolcat-creations** [comment]
Can you test if you see the template Style on http://joomladevtest.torontocameraclub.com/administrator/ - its the 4.2 nightly. For me this one works for the customer not. While the staging site backend does not work for me but for my customer. It's a really weird issue. As mentioned above I have cache disabled completely and I test on different browsers.

**Comment by chmst** [comment]
I get the message "Warning! Internet Explorer should not be used for proper operation of the Administrator Backend. " on this site, FF on win11.

**Comment by brianteeman** [comment]
@chmst that message is because my pull request is sat untested and unmerged #37900

**Comment by brianteeman** [comment]
@coolcat-creations Please check and review this https://stackoverflow.com/questions/55915264/scriptdocument-cookie-humans-21909-1-document-location-reloadtrue-scri

In  other words it sounds like it could be a bad mod_security rule on the server

**Comment by brianteeman** [comment]
and you will see that all reports of this issue are from the same hosting company :(

**Comment by brianteeman** [comment]
I should have added that the server response to all thefiles with a 409 is 
`<script>document.cookie = "humans_21909=1"; document.location.reload(true)</script>`

interesting analysis showing its a server issue https://www.hetogrow.com/account-registration-error-code-cookie-humans_21909

**Comment by coolcat-creations** [comment]
Thank you for the evaluation @brianteeman I did not see the cookie at all. So the hoster is adding a cookie? strange...
I saw that issues also from bluehost customers and others.
Should I close the issue or leave it open now?

**Comment by brianteeman** [comment]
This is where you can find it

![image](https://user-images.githubusercontent.com/1296369/182869205-561e434b-86b4-4d96-93db-ae8862c05eab.png)

I don't believe there is anything we can do about this and it should be closed and passed to the hosting company

**Comment by coolcat-creations** [comment]
@brianteeman Thank you. I am suprised a hosted can attach cookies to files. Every day something new :) Thanks for your help!

**Comment by coolcat-creations** [comment]
Just one more question: Joomla 3 works without issues, so there must be something in Joomla 4 confusing mod_security of such hosters. What could it be? Searching through the net I saw that the word register is causing problems. As implementing the css works, if it's implemented manually maybe "registering" the webasset Manager is the problem?

**Comment by richard67** [comment]
> Searching through the net I saw that the word register is causing problems.

@coolcat-creations Do you have some links so interested readers don't have to search again?

**Comment by coolcat-creations** [comment]
@richard67 yes sorry:
this is mentioning the problem with the word register: https://stackoverflow.com/questions/55915264/scriptdocument-cookie-humans-21909-1-document-location-reloadtrue-scri

**Comment by richard67** [comment]
Well I don't think we can change our web asset manager to use something else than "register" without b/c breaks.

Reading the linked stackoverflow thread, one provider was able to change their mod_security settings, while another just recommended to disable mod_security completely.

Maybe it is possible to set some mod_security rules in the .htaccess file? I haven't investigated yet.

If that is not possible, I do not really see a way to solve it on our side without b/c breaks.

It would need to add some documentation on that issue at a good place, maybe the known J4 b/c issues or the J4 FAQ.

**Comment by brianteeman** [comment]
You can't modify mod security with htaccess
