### ISSUE TITLE
[4.2] [Smart Search] Error with option "Gather Search Statistics" enabled

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#38370]
### Steps to reproduce the issue
1. Install nightly build 4.2.
2. Install demo data.
3. Index demo data in Smart Search.
4. Go to the frontend, use the search module - for example, the query "Joomla". Everything is working.

5. Return to the admin panel, enable option **Gather Search Statistics** in the settings of the Smart Search component, then repeat the search in the frontend.

In my case, I always get an error.
If the error repeats for you (and not just in my some exceptional case), then it is quite serious and needs to be fixed before stable 4.2.

```
The requested page can't be found.
...
Serialization of 'Closure' is not allowed.
```

![Screenshot_1](https://user-images.githubusercontent.com/8440661/182325242-89d26a90-10ca-46df-bd22-3e51566d7ab9.png)

**Comment by alikon** [comment]
i've got a different one
![image](https://user-images.githubusercontent.com/181681/182349119-967062fa-df8f-4d7e-9f30-be5e7c0e3131.png)

anyway  I've made a  draft  #38373 can you check if it works for you too ?

**Comment by Avenezer** [comment]
I confirm the topikstarter message.
![screenshot_704](https://user-images.githubusercontent.com/52596123/185108426-48c78c6b-0fea-405e-8d3e-8b2fc6e409a9.jpg)

**Comment by SharkyKZ** [comment]
Will this B/C break be mitigated?
