### ISSUE TITLE
Versioning does not work completely

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#38377]
### Steps to reproduce the issue
I use the versioning function and set a post from date Y to an earlier version back to a date X. 

### Expected result
The content of the post should then correspond to the version as of date X.

### Actual result
However, I get a mixture: contents in core and standard fields are actually reset to the status as of date X. Contents in custom fields, on the other hand, are not reset but simply taken over from the version as of date Y. => This results in sheer chaos in the output... 

### System information (as much as possible)
J4.1.5

### Additional comments
Joomla is a brilliant system, but such weaknesses are very unsettling for customers and content managers: There is no reason to call this behaviour desired and correct. Unfortunately, the custom fields function is simply not fully developed.

**Comment by ReLater** [comment]
> There is no reason to call this behaviour desired and correct.

Just to say it: From my point of view it's a 50:50 decision if it's correct to reset the custom fields also. Sometimes welcome, sometimes not.

**Comment by FaiSoo** [comment]
Yup, i have a same problem also
Here my website [Ruai99](https://ruai99.com/ "Ruai99 Slot")

But how to do, nothing much can do

my customer put these info inside, but it become Y eventually
Ruai99 มีโปรโมชั่นแจกไม่อั้นยิ่งกว่าใคร!! สมัครตอนนี้รับทันทีฟรีโบนัส และโปรโมชั่นฝากครั้งแรกที่ให้มากถึง 100% ร่วมเล่นเกมกับเรา ไม่มีผิดหวัง
Ruai99 สล็อต ออนไลน์ เว็บตรงจากค่ายดัง ไม่ผ่านเอเย่นต์ ไม่มีขั้นต่ำ แอพเกมสล็อตที่ดีที่สุดในไทย
ทดลองเล่นสล็อตฟรี PG / JOKER / PP/ สล็อต XO ฟรีจริง! ไม่ต้องฝากก่อน
Ruai99 สล็อต ฝาก ถอน True Wallet ไม่มีขั้นต่ำ
Ruai99 แอปพลิเคชั่นสล็อตออนไลน์ที่ดีที่สุดในไทย
อัพเดทเกมใหม่ทุกวัน ไม่ว่าจะเป็นเกมสล็อต เกมยิงปลา เกมไพ่ โดยเกมทั้งหมดเราได้คัดสรร เกมเด่น เกมดัง เกมยอดนิยม ที่เล่นง่ายได้เงินจริงมาให้กับทุกท่านที่ Ruai99
Ruai99 มีเกมสล็อตให้บริการมากกว่า 2,000 เกม ให้ทุกท่านได้สนุกและลุ้นรับแจ๊คพอต สุดเหวี่ยงกับความบันเทิงระดับโลก
Ruai99 แอปสล็อตอันดับ 1 ในไทย สมัครง่าย ระบบฝากถอนอัตโนมัติ ด้วยประสบการณ์ยาวนาน เราจึงมั่นใจว่าทุกท่านที่เข้าเล่นจะได้รับความมั่นคงทางการเงินและความบันเทิงอย่างเต็มรูปแบบ<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38377">issues.joomla.org/tracker/joomla-cms/38377</a>.</sub>

**Comment by coolcat-creations** [comment]
Versioning should absolutely work for custom fields as well. Its a huge flaw that it does not work.

**Comment by crystalenka** [comment]
Collecting a few issues into a bigger discussion on versioning and preview in custom fields, so I'm closing this as duplicate. Join the discussion here if you would like: https://github.com/joomla/joomla-cms/issues/39217
