### ISSUE TITLE
Custom field values for categories are not deleted when a category is deleted

### ISSUE THREAD

**Issue by domcotec** [joomla/joomla-cms#38379]
### Steps to reproduce the issue
1. Create a new custom field for categories (Navigate to Content > Fields, select 'Category' in the filter dropdown at the top of the page and click '+New' to create a new custom field and save it.)
2. Create a new category (Content > Categories > New)
3. In the category switch to the 'Fields' tab and add some data to the custom field you just created. Save.
(Now in the database in table **#__fields_values** a new row is created with the catID, fieldID and custom field value.)
4. Now change the publication 'Status' to 'Trash' and then go to the trash and delete the category completely.
(Here is the potential bug: In the database table **#__fields_values** the row for this catID and fieldID should have been deleted, but it remains in the database.)

### Expected result
Deleting a category should also delete the mapped custom field values. (This actually works for articles, but not for categories) 

### Actual result
The row for the deleted category ID and field ID with the field values remains in the database (unused forever).

### System information (as much as possible)
Joomla! 4.1.5
PHP 7.4.30

**Comment by chmst** [comment]
I cannot confirm that. Did you trash the fields or did you  delete them permanently (empty trash)?

**Comment by domcotec** [comment]
I deleted the category permanently, not the field.
But the cf value remains in the #__fields_values table.

It's important that you test this with a category, not with an article, because for articles it works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38379">issues.joomla.org/tracker/joomla-cms/38379</a>.</sub>

**Comment by domcotec** [comment]
Thank you all! 🙏🏼🙂
