### ISSUE TITLE
Copying custom fields incorrectly (name)

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#38383]
### Steps to reproduce the issue
Copy a custom field using the batch function. 
### Expected result
The copy contains a number in brackets (2) in the label and the addition "-2" in the name.

### Actual result
Joomla creates a copy of the field with the identical name.

### System information (as much as possible)
j4.1.5

### Additional comments
This is particularly tricky because identical names should not occur.

**Comment by brianteeman** [comment]
same as #37555 ?

**Comment by chmst** [comment]
Closing as duplicate
