### ISSUE TITLE
Add new item to custom client admin menu using PHP 8

### ISSUE THREAD

**Issue by anteud3000** [joomla/joomla-cms#38381]
### Steps to reproduce the issue

I've recently built a J4 (4.1.5) website from scratch on a MAMP localhost running PHP 7.4.21 and everything has been working fine.

I updated the PHP version to 8.0.8 and attempted to created a streamlined client admin area having a Custom client admin (see https://magazine.joomla.org/all-issues/ ... experience) and everything worked fine UNTIL I tried to add a menu item to the client admin menu.

### Expected result

When I select "Menu Item Type" a list of items should appear

### Actual result

When I select "Menu Item Type" I receive the notification - 

"An error has occurred.

0 strlen(): Argument #1 ($string) must be of type string, array given 

![screen shot 2022-08-03 at 10 52 25](https://issues.joomla.org/uploads/1/2552653ab4d77ecf47c4c4c58b11d639.png)

### System information (as much as possible)

![screen shot 2022-08-03 at 10 54 40](https://issues.joomla.org/uploads/1/f6109273c3b7812bdedc6f39a1d474fc.jpg)

### Additional comments

If I rollback to PHP version 7.4.21 everything works as expected so I'm wondering if this might be a J4 / PHP 8 bug?

**Comment by anteud3000** [comment]
It would appear this problem was linked to the component OSMap Free? I disabled the component and everything started to work as expected <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38381">issues.joomla.org/tracker/joomla-cms/38381</a>.</sub>

**Comment by alikon** [comment]
so not a core issue let's close it then
