### ISSUE TITLE
J4 cant install on remote postresgsql server

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38391]
### Steps to reproduce the issue
During the installation you are asked what type of database yuo are installing to : mysql, postgres etc BUT the list is filtered so that only the db options that are available on your server are presented in the select box.

This means that you can never install joomla on a remote postgres server unless you already have postgres running on the same server as php.

or am I missing something?

**Comment by HLeithner** [comment]
The filter is if the running PHP Version is supporting PostgreSQL. That has nothing todo if the Server is local or is remote.

**Comment by brianteeman** [comment]
Knew I was missing something ;)
