### ISSUE TITLE
Issues with tags that have spaces

### ISSUE THREAD

**Issue by GabyE4U** [joomla/joomla-cms#38400]
### Steps to reproduce the issue
1. Create a tag with a space in the name.
2. Create subtags of this tag, with or without spaces. This doesn't matter.
3. It should look something like this:

![Tag tree](https://i.imgur.com/I1wdYLb.png "Tag tree")

4. Create an article in the administrator (in com_content).
5. Type the full name of the parent tag in the Tags field to search for the sub-tags it has.

### Expected result
It should show the parent tag AND the child tags.

### Actual result
1. When you first start typing, it shows all the tags like it's supposed to.
![First result](https://i.imgur.com/eWYkhJV.png "First result")

2. Once you type out the full parent tag name and the tag list refreshes, only the parent tag shows up and the child tags disappear.
![Second result](https://i.imgur.com/83Pa8wG.png "Second result")

### System information (as much as possible)
This happens on any system, but here's my browser specs:

Chrome version 104.0.5112.80

### Additional comments
This issue has been reported by one of our customers. She has experienced this since at least May 2022 (so for several Joomla 3 versions), but it could've existed earlier. I was able to reproduce her issue on several different PCs and browsers.

**Comment by Fedik** [comment]
> Once you type out the full parent tag name and the tag list refreshes, only the parent tag shows up and the child tags disappear.

I think it is expected, because search work for a tag title, not for any parent, but for the tag name itself.
We display the parents in drop down just for "visual siplicity", so you know wich exatly tag tree you selected.

**Comment by chmst** [comment]
@GabyEdit4U Which behaviour would you expect here? I agree with @Fedik that this is "normal" behaviour.

**Comment by GabyEdit4U** [comment]
@Fedik @chmst Sorry for my late reply, I was unavailable due to vacation last week.

In point 1 of the first result you can see that when you start with typing the parent tag (in this case "Test"), it will actually show all the results that have "Test Tag" as the parent tag. Only when you type in the space and the list refreshes (or type out the full Test Tag name for that matter as described in point 2 for simplicity), is when the results disappear.

 The behaviour is currently irregular as you are able to see the child tags for parent tag "Test Tag" as long as you only type the first portion of the tag.

**Comment by brianteeman** [comment]
Thank you for raising this issue.

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed.

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc [@zero-24](https://github.com/zero-24)

**Comment by morphinestyle** [comment]
@brianteeman this bug is still present in J4.2.2: in article editing i can't assign tags with spaces from several J4 versions. F.I: RED APPLE can't be added to article.

**Comment by chmst** [comment]
I cannot replicate in J4 - see example, all tags are added in editing an article.
![grafik](https://user-images.githubusercontent.com/1035262/193972395-5e0f0d08-52dc-42d0-b282-70022ad89961.png)
 As @brianteeman says .. open a new issue for J4.

**Comment by morphinestyle** [comment]
I can't replicate on a new website... i need to make an accurate test excluding some 3rd part extensions.
I tried with/without multi language, with without spaces, nested and not nested... I can't replicate it.

How can i get more infos when i SAVE the ARTICLE and lost the tags? Debug? Set to show all errors?

**Comment by morphinestyle** [comment]
However i'm experiencing the issue is slightly different, not related to space between tags:
**I see 5 tags on frontend, but on my article editing i see only 3 tags!**

**Comment by Fedik** [comment]
I am clossing it, see comment https://github.com/joomla/joomla-cms/issues/38400#issuecomment-1229014326
Also because it is not an issue for j4
