### ISSUE TITLE
[4.1.5] Multilingual Associations:  Default List Limit is set to '25'

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#38411]
### Steps to reproduce the issue

1. Global Configuration: Set 'Default List Limit' to **5**
2. Components: Multilingual Associations: 'Default List Limit' is **5**
3. Select 'Item Type': 'Default List Limit' chance to **25**. This happen using any item type. 

### Expected result

'Default List Limit' stay at '5' after selecting an item type.

### Actual result

please see 'Steps to reproduce the issue'.

### System information (as much as possible)
<img width="1054" alt="si" src="https://user-images.githubusercontent.com/89642616/183282298-f8de81c8-5787-46ad-8763-3513f49074a2.png">

### Additional comments

Edit: Same issue in J3.

**Comment by brianteeman** [comment]
Unable to replicate - or did I miss something?

![image](https://user-images.githubusercontent.com/1296369/183312095-0e1e26cd-b383-4913-acb7-c766a44388ad.png)

![ass](https://user-images.githubusercontent.com/1296369/183312140-1c6bff4e-9c93-4de3-9184-6c409a206742.gif)

**Comment by ghost** [comment]
Thanks @brianteeman for taking your time to look at the issue.

Please do a change of the item type, for example from 'Articles' to 'Menu Item' back to 'Select Item Type'. The List Limit is after each change '25':

https://user-images.githubusercontent.com/89642616/183343096-bbcabdf9-834b-4c8d-b306-8a4856011a08.mov

**Comment by brianteeman** [comment]
ok - that I can confirm

**Comment by chmst** [comment]
I can confirm that this is since I am with Joomla (1.6).

**Comment by brianteeman** [comment]
did we have associations then ?

**Comment by chmst** [comment]
Setting list limit is valid only for one view, no matter which component.

**Comment by brianteeman** [comment]
Sorry I dont follow you. I have no problems with other components

**Comment by brianteeman** [comment]
same problem as #17136

**Comment by Franzwohlkoenig** [comment]
closed as double report.
