### ISSUE TITLE
Unable to save menu item

### ISSUE THREAD

**Issue by prh47bridge** [joomla/joomla-cms#38429]
### Steps to reproduce the issue

Create a menu item (the type I used was for a single article)
Give it the title "The Rhône from Sea to Source"
Do not set a parent item
Save it
Modify it by setting a parent item
Save it again

### Expected result
Both saves should work

### Actual result
The second save fails claiming that the alias, "the-rhone-from-sea-to-source", is already being used.

### System information (as much as possible)
Joomla 4.1.5
PHP 7.4.30
MySql 5.7.39

### Additional comments
Joomla is failing to notice that the menu item being saved is the one with the alias. If I give the menu item the title "The Rhone from Sea to Source" it works correctly.

**Comment by prh47bridge** [comment]
Note that changing the title of the item from "The Rhone from Sea to Source" (i.e. losing the accent on the o" doesn't make a difference. However, if I use that title to create the item I can save it as often as I want.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38429">issues.joomla.org/tracker/joomla-cms/38429</a>.</sub>

**Comment by ReLater** [comment]
I can not confirm this issue. I followed the steps and could save the menu item several times without any warnings.

**Comment by richard67** [comment]
@prh47bridge What’s your backend language? And is the PHP extensions “intl” for internationalization (e.g. transliteration) enabled?

**Comment by prh47bridge** [comment]
On further investigation, it only happens if the "modify it" step involves changing the parent item. Other changes to the menu item don't cause the problem.

My backend language is English (United Kingdom).

php-intl was not installed. I have now installed and enabled it but it has made no difference.

**Comment by prh47bridge** [comment]
Just to add the specifics in case it is relevant, I created the menu item and forgot to assign a parent item. I then went in again to edit it and assign the correct parent. It refused to save. I deleted the menu item (trash and empty trash) and then tried again, assigning it to the correct parent when I created it. That worked. I can reliably reproduce the issue on my system.

**Comment by brianteeman** [comment]
I can't replicate it either - sorry

**Comment by prh47bridge** [comment]
It is more specific than I thought! It seems to depend on which parent item I choose. I can move the menu item to some parents without a problem, others produce this error. I will add some debugging to see if I can figure out what's going on.

**Comment by brianteeman** [comment]
are you 10000% certain that you dont have any trashed menu items?

**Comment by prh47bridge** [comment]
Oops! For some reason I didn't find the trashed item when I searched for it. It does exist. My bad. Sorry.
