### ISSUE TITLE
[4.2-rc] OpenSearch php deprecated

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38427]
### Steps to reproduce the issue
Install Joomla 4.,2rc and the sample data
php version is 8.1.7
navigate front end of the site

### Expected result
empty php error log

### Actual result
`[09-Aug-2022 09:18:30 UTC] PHP Deprecated:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in libraries\src\Document\OpensearchDocument.php on line 139`

**Comment by richard67** [comment]
> the sample data

@brianteeman Which one? Blog? Or multilingual? Or testing?

**Comment by brianteeman** [comment]
It was blog - but I doubt it makes a difference

**Comment by Fedik** [comment]
It is here https://github.com/joomla/joomla-cms/blob/19a2b79ea6d1b72c9584087d2576898fb7e13a7b/libraries/src/Document/OpensearchDocument.php#L138-L140

However default value is empty string (not null) https://github.com/joomla/joomla-cms/blob/19a2b79ea6d1b72c9584087d2576898fb7e13a7b/libraries/src/Document/Document.php#L33-L40

It seems that some code overrides the default value value to `null`

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/blob/4.2-dev/components/com_finder/src/View/Search/OpensearchView.php#L42

**Comment by Fedik** [comment]
Please test #38431
