### ISSUE TITLE
[4.1.5] Media: Options: No 'Help' button shown

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#38430]
### What needs to be fixed
As title say:

<img width="1015" alt="Untitled" src="https://user-images.githubusercontent.com/89642616/183818987-1a48b3cc-8d11-41e1-b27a-0f9c3af146a8.png">

### Why this should be fixed
There is a [help screen](https://docs.joomla.org/Help4.x:Media) where the 'Help' button can link.

### How would you fix it
?

### Comment
'Scheduled Tasks Configuration' have also no 'Help' button, but have no help screen. As these options are written in [Scheduled Tasks](https://docs.joomla.org/Help4.x:Scheduled_Tasks#Scheduled_Tasks_Options) i guess its no issue.

**Comment by brianteeman** [comment]
please test #38435
