### ISSUE TITLE
Enable upload of font file formats to the template manager

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#38437]
### Is your feature request related to a problem? Please describe.
I tried to show my Joomla Kids how to customize Cassiopeia. In Germany you are not allowed to embed Google Fonts so you have to upload them into the template.
It's not possible to upload it because of security restriction.

### Describe the solution you'd like
Allow Upload of:
eot, woff, otf, ttf, woff2 and svg into a font folder of the template through the template manager

**Comment by mariantanase** [comment]
> In Germany you are not allowed to embed Google Fonts so you have to upload them into the template.
Also in Italy

**Comment by dgrammatiko** [comment]
Only `woff` and `woff2` fonts should be supported, all the others are really, really old...

**Comment by coolcat-creations** [comment]
The others are standard in the webfont kits that myfonts and other services are providing. To not make it too complicated I would suggest just to whitelist all the font formats as it does not hurt and prevents frustration when trying to upload and it does not work.

**Comment by Fedik** [comment]
I have removed version from the title, because it feature request, and having a version in the title may confuse :wink:

**Comment by coolcat-creations** [comment]
Thank you @Fedik 
@dgrammatiko I use for example myfonts and the https://google-webfonts-helper.herokuapp.com/fonts both deliver the full package. It does not harm to allow the files so why discussing it? It's worse for a beginner not to be able to upload and being confused by it.

**Comment by dgrammatiko** [comment]
@coolcat-creations I just stated that the CMS should not promote deprecated/unsupported things. Anyways, I have my own solution that doesn't require any of all that copy/paste/upload/etc (I even tried to contribute that in the core: https://github.com/joomla/joomla-cms/pull/30914)

https://user-images.githubusercontent.com/3889375/184446207-20a88495-6897-49ae-8807-9f6967521396.mp4

**Comment by coolcat-creations** [comment]
What's wrong with allowing file types that are common for templates in the template manager?

**Comment by coolcat-creations** [comment]
I added also the wish for allowing .min. in filenames. renaming template.min.css for example to style.min.css does not work.

**Comment by brianteeman** [comment]
Thats a slightly different issue so could you please make a new issue for that (if there isnt one already) - the reason that you cannot currently upload a *.*.* file was to address a security issue (which may not be relevant anymore)

**Comment by HLeithner** [comment]
The reason not to support legacy or better deprecated file types is to make it easier for people to do the right thing. If you only allow state of the art (in this case only needed) file types you automatically teach people to do the right thing and they don't need to make there own research what they have to do. 

I personally would only allow woff2, the usage difference is about 1,5% an that's mainly IE users (0,97) and some really dated android versions (0,44%). 100% isn't possible because Opera mini doesn't support webfonts at all.

**Comment by N6REJ** [comment]
> @coolcat-creations I just stated that the CMS should not promote deprecated/unsupported things. Anyways, I have my own solution that doesn't require any of all that copy/paste/upload/etc (I even tried to contribute that in the core: #30914)
> 
>  Screen.Recording.2022-08-12.at.23.05.57.mp4

@coolcat-creations does his video solve the issue or is that too complex for the kids?
We definitely need to support our kids.  The winning popularity or raspberry pi's proves that point.

**Comment by brianteeman** [comment]
Instead of wasting time debating which font formats to support why not spend the time more productively on an actual method to upload the files.

PS joomla already has support for those other font formats in the preview

**Comment by brianteeman** [comment]
> It's not possible to upload it because of security restriction.

It is currently perfectly possible to upload ttf, woff and otf fonts in the template manager - don't know why you could not?

The only one that cannot be uploaded currently is woff2 and all thata has to be done is to add it to the list of font formats in the template options.

![image](https://user-images.githubusercontent.com/1296369/184533077-eaad8230-faba-4848-867e-9528de0c844f.png)

![image](https://user-images.githubusercontent.com/1296369/184533091-48683030-0ec4-4cb9-824d-3c41d7252d96.png)


woff2 can be added to the default for new installs if desired - upgraded sites will need to update the options themself

**Comment by brianteeman** [comment]
please remove the new feature tag as its already possible

**Comment by coolcat-creations** [comment]
I tested again and It's not possible to upload eot and woff files. These are all files contained in the herokuapp package. If it's not adviseable to use these font formats the error should say: "You don't need this font format, we advise you to only upload woff" - A beginner does not know why you dissallow the upload of a font what for example myfonts.com or herokuapp is giving you. and if .eot is the first font in the list to upload why should I bother to try upload the others? Well, thats what happened. It would be great to either fix the error message or to let the user decide himself what he needs in the template.

**Comment by brianteeman** [comment]
eot is not in the list of allowed file types as defined in the component options. Add it and you will be able to upload.
I have no problem uploading woff files at all as shown in the screenshot.

I have discovered a mismatch between the default options in the component (includes woff2) and the default options created in the database (does not include woff2). I will do a pr for that but it will only impact on new installs. For existing installs just go to the template options and add woff2

**Comment by dgrammatiko** [comment]
@coolcat-creations couple of things:
- the heroku app is abandonware, proof: https://github.com/majodev/google-webfonts-helper/pull/123
- that PR also denotes that using the app to get your fonts will actually HARM the performance of your site
- at the end of that PR there's a link to another site that zips the css/woff2 and should be probably used (as I said before I have my own take on this so take this with a grain of salt) https://nextgenthemes.com/google-webfont-downloader/

**Comment by coolcat-creations** [comment]
Ok, got you @brianteeman and @dgrammatiko -  can we also add something to the error messages to understand why something is blocked? A beginner just does not understand and thinks Joomla does not work properly. Also the Filemanager is weird you have to click a folder before uploading and you can't move files when you forgot. But thats another issue.

> I have discovered a mismatch between the default options in the component (includes woff2) and the default options created in the database (does not include woff2). I will do a pr for that but it will only impact on new installs. For existing installs just go to the template options and add woff2

Thank you, appreciate that!

**Comment by brianteeman** [comment]
What more do you want than is there currently

![image](https://user-images.githubusercontent.com/1296369/184605131-dff23cbe-b154-4b93-8841-f228f73d7f98.png)

**Comment by coolcat-creations** [comment]
> @coolcat-creations I just stated that the CMS should not promote deprecated/unsupported things. Anyways, I have my own solution that doesn't require any of all that copy/paste/upload/etc (I even tried to contribute that in the core: #30914)
> Screen.Recording.2022-08-12.at.23.05.57.mp4

Sorry somehow I overlooked this, this is a very nice solution!

**Comment by coolcat-creations** [comment]
> What more do you want than is there currently
> 
> ![image](https://user-images.githubusercontent.com/1296369/184605131-dff23cbe-b154-4b93-8841-f228f73d7f98.png)

Maybe something like "You tried to upload a svg font. Svg fonts are a outdated format and should not be used anymore. Try to upload a woff file"

**Comment by brianteeman** [comment]
Then you would need to have a message for every single type of file

**Comment by coolcat-creations** [comment]
Or maybe we add a message like: This file format is not supported. To read more about why click here on manuals.joomla.org/supported-file-formats.... And there we could explain for severall file formats why they are outdated. ?

**Comment by brianteeman** [comment]
But it might not be that they are outdated. It might be that they are really not supported on the web or that they are too new a format etc.

**Comment by coolcat-creations** [comment]
> But it might not be that they are outdated. It might be that they are really not supported on the web or that they are too new a format etc.

Yes we could explain that all on the manuals page - Hopefully the manuals Page will have a module like "was this explanation helpful for you?" at the end so we can get feedback from the users where to improve. @bembelimen

**Comment by brianteeman** [comment]
i thought the manuals site was for developer docs not user docs?

**Comment by coolcat-creations** [comment]
Oh I thought it would be a full new documentation for every level... @bembelimen ? Is it only for developers?

**Comment by HLeithner** [comment]
yes https://manual.joomla.org is primary used for "developer" documentation

**Comment by brianteeman** [comment]
I think I forgot to reference #38465

**Comment by brianteeman** [comment]
There really is nothing to do here and this should be closed. It is already possible to upload fonts. A small bug that woff2 wasn't appearing on the list has already been fixed. The only remaining thing is to add documentation links to error messages. There is already an open issue for that from the op.

Please close
