### ISSUE TITLE
Remove useless uninstall warnings.

### ISSUE THREAD

**Issue by joomlahenk** [joomla/joomla-cms#38438]
### What needs to be fixed
Uninstall warnings:
"Joomla\CMS\Filesystem\Folder::delete: Path is not a folder." and "JInstaller: :Install: SQL File not found"

### Why this should be fixed
I know these warnings are on purpose, See: #34996: [4.0] Fix fatal error while uninstall deleted plugin and: #6559: Wrong error message. But they are totally useless and just filling up the screen.
Also real warnings get unnoticed if there are many useless ones.

### How would you fix it
If possible please remove these useless warnings.

### Side Effects expected
None

**Comment by brianteeman** [comment]
what makes you think they are useless

**Comment by joomlahenk** [comment]
Maybe you can explain the use.

**Comment by richard67** [comment]
> Maybe you can explain the use.

When you open an issue you should be willing to provide the necessary information.

**Comment by joomlahenk** [comment]
OK, J! team is not interested
