### ISSUE TITLE
Allow Upload and renaming of .xxx. files to template manager

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#38455]
### Is your feature request related to a problem? Please describe.
In School class I showed how to customize a template. If you want to upload or rename a min.js or a min.css file to the template manager it's not allowed.

### Describe the solution you'd like
Allow .min. files in the template manager

**Comment by brianteeman** [comment]
For reference the original reason to prevent the upload of *.*.* filenames was to address a security issue. I have no idea if that is still relevant but it explains why it is currently prevented

**Comment by Quy** [comment]
Duplicate #30908?

**Comment by brianteeman** [comment]
So I remembered what the security issue was and found the code that deals with it.

The good news is that code does not prevent *.min.* and I have verified that I can upload both a min.js and a min.css file


https://user-images.githubusercontent.com/1296369/184516276-31c957ed-15d2-44a9-8a07-e4fd472c5fa0.mp4

**Comment by brianteeman** [comment]
Currently it is not possible to rename a file example.csss to example.min.css but is that necessary?
It is a very quick fix if it is necessary and it would be acceptable for it to be 

![image](https://user-images.githubusercontent.com/1296369/184516547-4fbe54e5-3e4c-4d20-9d8f-820adeb0c59b.png)

**Comment by coolcat-creations** [comment]
I can't rename a template.min.css to style.min.css. I mean that's a simple wish to something and could be frustrating if it's not possible. It would be really nice if it's possible.

**Comment by brianteeman** [comment]
if the option shown in the screenshot is acceptable it is a 2 second pr

**Comment by coolcat-creations** [comment]
Means I can upload a min.js but still not create? It would be at least a part of the solution. Creation would be appreciated too when they do not use an IDE in the first moment :-)

**Comment by brianteeman** [comment]
>  Creation would be appreciated too
same fix

**Comment by brianteeman** [comment]
creating is a bit harder as the regex is more comples but i will take a look

**Comment by brianteeman** [comment]
please test #38458

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38987 . Thanks in advance.
