### ISSUE TITLE
[4.2] deprecation notice in userlevels

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38464]
### Steps to reproduce the issue
Try to create a new viewing access level

### Expected result
form opens with no php messages

### Actual result

Deprecated: json_decode(): Passing null to parameter #1 ($json) of type string is deprecated in administrator\components\com_users\src\Model\LevelModel.php on line 154

![image](https://user-images.githubusercontent.com/1296369/184602073-96db8469-411a-4257-b29d-80de3ea5efd6.png)

### System information (as much as possible)

php 8,1,7

**Comment by alikon** [comment]
please test #38467
