### ISSUE TITLE
Content article: assigned tags partially deleted when reloading and saving again

### ISSUE THREAD

**Issue by WeibelMarc** [joomla/joomla-cms#38468]
### Steps to reproduce the issue
Assign 9 predefined tags to a selected content article in the administrator form.
Save and close the content article.
Check the contentitem_tag_map for the selected content article (should be faithful).
Open again the same article and check the previously assigned tags.
Save the selected article again.
Check the contentitem_tag_map for the selected content article (missing records should be noticed).
Open it again and and check the previously assigned tags.
Missing records should be noticed also in the content article administrator form.

### Expected result
All tags assigned to a content article must be preserved during successive recording (click on the Save button) of the content article.

### Actual result
You should also see that some assigned tags are missing after reloading the content article. 
In my tests, only 5 tags were loaded, and preserved when saving for the second time.
The other assigned tags above 5 get lost also in the contentitem_tag_map table (not only on the browser form).

### System information (as much as possible)
Joomla 4.15
Server side infos in the attached file.
Reproduced with Firefox and Chrome, both with cache cleaned.

### Additional comments
[SQL check Tags contentitem_tag_map.txt](https://issues.joomla.org/uploads/1/4658d9ae8ed20542ed58f81899b057f9.txt)[systeminfo-2022-08-15T18 22 47+00 00.txt](https://issues.joomla.org/uploads/1/1e75ccba7aef3b3f048664e430d65704.txt)

**Comment by chmst** [comment]
Could be the same as here https://issues.joomla.org/tracker/joomla-cms/37927.

**Comment by WeibelMarc** [comment]
Yes absolutely. Many thanks. Sorry for missing this issue report. The hint from Kadmon06 solves the issue (Solution 1
You need to switch the tags from AJAX to Nested. Go to Global Configuration/Tags/Data Entry, and Tag Entry Mode should be Nested.) Kind regards.
