### ISSUE TITLE
3.10.11 Release news

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38477]
### Steps to reproduce the issue
check the email sent by your 3.10.10 site informing you of an update

### Expected result
Links contain all the relevant information

### Actual result
Link to release news has no information about the release

![image](https://user-images.githubusercontent.com/1296369/184972678-b8c36992-c0e1-4756-bd58-a4e95c459eda.png)

@zero-24 did an article not get published?

**Comment by zero-24** [comment]
IIRC there was never a dedicated link to the concrete article included in the mail? Also there was never a dedicated URL for 3.10 as that was always included within the 4.x release at that time.

**Comment by brianteeman** [comment]
so the text of the plugin needs to be changed if it is telling people to go to a page for more information and that page doesnt have any more information

**Comment by brianteeman** [comment]
spot the difference

![image](https://user-images.githubusercontent.com/1296369/184973870-4836ad47-c644-4aa5-94d9-381ca51f9e65.png)

![image](https://user-images.githubusercontent.com/1296369/184973909-6eea92d2-a723-434d-812c-46522fa8111b.png)

![image](https://user-images.githubusercontent.com/1296369/184973838-a9e8e570-c7ad-48a2-923b-d96cd9da0671.png)

**Comment by zero-24** [comment]
> so the text of the plugin needs to be changed if it is telling people to go to a page for more information and that page doesnt have any more information

It is hardceded to this page within the plugin: https://github.com/joomla/joomla-cms/blob/3.10-dev/plugins/system/updatenotification/updatenotification.php#L235

**Comment by zero-24** [comment]
> spot the difference
> 
> ![image](https://user-images.githubusercontent.com/1296369/184973870-4836ad47-c644-4aa5-94d9-381ca51f9e65.png)
> 
> ![image](https://user-images.githubusercontent.com/1296369/184973909-6eea92d2-a723-434d-812c-46522fa8111b.png)
> 
> ![image](https://user-images.githubusercontent.com/1296369/184973838-a9e8e570-c7ad-48a2-923b-d96cd9da0671.png)

I do agree will ask whether it can be added back to the title.

**Comment by brianteeman** [comment]
thanks.

 _to be clear i wasnt expecting the email to link to a specific article_

**Comment by zero-24** [comment]
3.10 has been put in the title again. Thanks for reporting :)
