### ISSUE TITLE
com_finder: fatal error with 4.2 when click on the button search

### ISSUE THREAD

**Issue by WeibelMarc** [joomla/joomla-cms#38475]
### Steps to reproduce the issue
With Joomla 4.2, Extended search (com_finder) activated and content indexed, enter a search term in the public search form, click on the button [Search].

### Expected result
Extended search working fine as with Joomla 4.15 previously.

### Actual result
After click on the Search button, there is an error message: 
'0 Serialization of 'Closure' is not allowed'

### System information (as much as possible)
Reproduced with Chrome and Firefox, cache cleaned.
Joomla 4.2 just updated, all requirements fulfilled.
Search newly indexed.

**Comment by rdeutz** [comment]
What php version do you have?

**Comment by WeibelMarc** [comment]
Currently PHP 7.4, due to old modules. I will switch to PHP 8.1 at the end of the on-going site migration.
I just realized that it is the same issue as #38373.
It was not obvious when reading this error report.
But when I turned off "collect statistics", the extended search worked again.
The statistics collection was working fine today with Joomla 4.15.
Kind regards.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38475">issues.joomla.org/tracker/joomla-cms/38475</a>.</sub>

**Comment by richard67** [comment]
Closing as duplicate report and because there is a pull request, see #38373 . Thanks for reporting.
