### ISSUE TITLE
[4.2] Keyboard Shortcuts Capitalisation Advertised Wrong

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#38478]
### Steps to reproduce the issue

Reporting on behalf of a user of Joomla.

Joomla 4.2.0 advertises the keyboard shortcuts with CAPITAL LETTERS indicating (to those of us that use global pallet design daily in other apps) that these need to be typed as capital letters. 
<img width="562" alt="Screenshot 2022-08-16 at 21 13 39" src="https://user-images.githubusercontent.com/400092/184976808-fc923251-6813-4be5-a983-e64c5009e812.png">
<img width="250" alt="Screenshot 2022-08-16 at 21 13 32" src="https://user-images.githubusercontent.com/400092/184976816-4cd009e8-8ad7-4ca6-812b-040516c7d178.png">

### Expected result

The shortcuts should show lowercase letters to indicate that they dont need the shift key pressed

### Actual result

Nothing works because idiots like me use SHIFT to get the advertised CAPITAL J and CAPITAL other letter.

**Comment by PhilETaylor** [comment]
> They work with both upper and lower case letters

Factually incorrect in the real world

**Comment by PhilETaylor** [comment]
The truth is that it doesn't work with either caps lock on, or holding down shift, on a Mac, in Safari or Firefox to Google Chrome. The user reported that to me, and I confirmed it myself.

**Comment by PhilETaylor** [comment]
> They work with both upper and lower case letters

Take the demo code from https://wangchujiang.com/hotkeys/ and placed it in Codepen 

```
<script src="https://unpkg.com/hotkeys-js/dist/hotkeys.min.js"></script>
<script type="text/javascript">
hotkeys('ctrl+a,ctrl+b,r,f', function (event, handler){
  switch (handler.key) {
    case 'ctrl+a': alert('you pressed ctrl+a!');
      break;
    case 'ctrl+b': alert('you pressed ctrl+b!');
      break;
    case 'r': alert('you pressed r!');
      break;
    case 'f': alert('you pressed f!');
      break;
    default: alert(event);
  }
});
</script>
```

https://codepen.io/philetaylor/pen/GRxwBbG

Click in the white area

type lower case r - see a pop up

type upper case r - see no popup

Conclusion, despite you thinking it does, it doesn't work as you think.

The Joomla "J" capital hotkey is hard coded as a capital letter https://github.com/joomla/joomla-cms/blob/937df36b85a4b80aa104ed81c678e28764b1acb7/build/media_source/plg_system_shortcut/js/shortcut.es6.js#L58

**Comment by brianteeman** [comment]
> Conclusion, despite you thinking it does, it doesn't work as you think.

Maybe its a mac thing. Works perfectly on windows

**Comment by brianteeman** [comment]
Even on your code pen
type r or R
both give the same alert

note that R is not the same as shift-R

**Comment by PhilETaylor** [comment]
Are you telling me that Joomla has just shipped a flagship new feature and no one tested it on Mac's, the number one PC brand in the world, 15% marketshare in the USA, shipping 22.3 million Mac units a quarter? 

/FACEPALM/

> note that R is not the same as shift-R

HOW THE HELL do you type a capital R without shift or caps lock then?!!?!

**Comment by PhilETaylor** [comment]
ok if I enable caps lock and click into the white of the code pen and press R it doesn't work, of I then click out (blur) and then click back into the whitespace and press R (caps lock still on) then it works. 

It seems like there is a bug here for sure...
