### ISSUE TITLE
4.0 Error Update (4.1.5 to 4.2)

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#38473]
### Steps to reproduce the issue
Update 4.1.5 to 4.2

### Expected result
Update

### Actual result
An error has occurred.
0 Redis::setex(): Argument #2 ($expire) must be of type int, float given

**Comment by richard67** [comment]
@Stuartemk Could you enable debugging in backend (or if you can't go to the backend anymore, edit configuration.php) so you can seer the stack trace and make a screenshot of it and post it here? Thanks in advance.

**Comment by richard67** [comment]
Here the update from 4.1.5 to 4.2.0 went fine. Maybe it happens only with PHP 8.1? I was on 8.0. @Stuartemk Could you provide some information on your PHP version and database type and version? Thanks in advance.

**Comment by alikon** [comment]
this appens when you have the cache enabled and  Redis as handler

**Comment by richard67** [comment]
@alikon Is it a known issue already? Or new?

**Comment by alikon** [comment]
new 
checked on 4.1.3 and it works fine

**Comment by N6REJ** [comment]
@alikon its not based on cache or redis.. 
I have a bare bones site with the same issue.  
It states the schema is out of date but it infact is correct.
After pulling it into my *ampp I see the following....
```

Warning: Undefined array key 0 in E:\Bearsampp\www\bearsampp\administrator\components\com_joomlaupdate\src\Model\UpdateModel.php on line 1411

Warning: Trying to access array offset on value of type null in E:\Bearsampp\www\bearsampp\administrator\components\com_joomlaupdate\src\Model\UpdateModel.php on line 1414
```

**Comment by richard67** [comment]
> @alikon its not based on cache or redis.. I have a bare bones 4.1.5 site with the same issue. It states the schema is out of date but it infact is correct. After pulling it into my *ampp I see the following....
> 
> ```
> 
> Warning: Undefined array key 0 in E:\Bearsampp\www\bearsampp\administrator\components\com_joomlaupdate\src\Model\UpdateModel.php on line 1411
> 
> Warning: Trying to access array offset on value of type null in E:\Bearsampp\www\bearsampp\administrator\components\com_joomlaupdate\src\Model\UpdateModel.php on line 1414
> ```

@N6REJ Did you get the error mentioned in the description of this issue, which is clearly from redis? If not, your problem is maybe a different issue?

**Comment by N6REJ** [comment]
no, not that exact error

**Comment by alikon** [comment]
please test #38490

**Comment by roland-d** [comment]
@N6REJ The warning you get is different from the Redis issue reported here. THe warning you see is because some extension ID is not found. Sounds like a corrupt extensions table or something.
