### ISSUE TITLE
[4.2] statistics plugin on the captive page

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#38476]
Issue for PR #38436

### Steps to reproduce the issue

Click on one button of the statistics alert
![image](https://user-images.githubusercontent.com/66922325/184962483-da1b0cb3-8753-4af8-9d96-25b54dc1bc13.png)
![image](https://user-images.githubusercontent.com/66922325/184962516-2c55780f-780f-4fb1-b27e-35a6d2b5ffd5.png)

### Expected result

It's allowed to enable or disable statistics or alert is not shown

### Actual result

403 error

### System information (as much as possible)

Joomla 4.2.0

ping @roland-d

**Comment by Fedik** [comment]
please test #38492

**Comment by nikosdion** [comment]
I have submitted a PR which implements the recommended approach of the plugin being responsible to detect it is running under an MFA captive page and refrain from showing its UI. See https://github.com/joomla/joomla-cms/pull/38533

**Comment by alikon** [comment]
please test #38533
