### ISSUE TITLE
4.2 - MultiFactor GMP/bcmath requirement locks users out of site

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#38485]
### Steps to reproduce the issue

Install Joomla 4.2.0 on a server without GMP and bcmath PHP Extensions
Login to Joomla Admin and Enable Multi Auth using an `Web Authentication` (Touch ID on Mac)
Joomla allows this, and secures your account. 

Logout 

Attempt to login again

### Expected result

Expect to be prevented from locking myself and users, out of their accounts

Expect not to be able to SET UP and LOCK an account if the server then cannot authenticate that multi-auth authenticator due to server requirements not being met.

### Actual result

**Im now forever locked out of my account** because I was allowed to enable multi-auth but my server doesn't have GMP or bcmath extensions and so I cannot login on the captive login page

<img width="861" alt="Screen Shot 2022-08-16 at 22 53 50" src="https://user-images.githubusercontent.com/400092/184991974-f66f7898-bae4-41b3-972d-3212ef6d235b.png">

**Comment by PhilETaylor** [comment]
Compare the new Multi-auth Web Authentication set up screen with the old W3C Web Authentication (WebAuthn) Login screen (which is also still available) which clearly, up front, stops you from using it if the requirements are not met. 

<img width="1596" alt="Screen Shot 2022-08-16 at 23 00 49" src="https://user-images.githubusercontent.com/400092/184992899-6c3bfbbd-84f6-4797-b705-7f8dd5ab128d.png">

**Comment by nikosdion** [comment]
Thank you for NOT reporting this three months ago when I had abandoned my business for a whole month to contribute this feature and for just whining instead of proposing a code solution. Yes of course I will cancel the first vacation I had tried to take in three years to write code for the issues you are filing three months too late, playing all high and mighty, when the reality is that you COULD have contributed three months ago but couldn't be arsed. Thank you for nothing, Phil.

**Comment by PhilETaylor** [comment]
Thank you for proving the Joomla project is still a toxic place. Pathetic. 

>  when I had abandoned my business for a whole month to contribute this feature

I do not dictate what you do with your time - you have no right to dictate what I do with my time 

> just whining

Reporting issues with open source software is not whining. Its contributing.

> Yes of course I will cancel the first vacation I had tried to take in three years

No one expects that, and I certainly did not demand that.

>  playing all high and mighty

Im sorry that you believe reporting genuine issues is " playing all high and mighty" - get real. 

> when the reality is that you COULD have contributed three months ago but couldn't be arsed.

I choose to contribute to non-toxic projects where my contributions are welcome, unlike receiving the tirade of abuse from you shows that Im not welcome here. 

> Thank you for nothing, Phil.

Im sorry you feel that my contributions are worth nothing. In a non-toxic project you would have been banned already.

**Comment by rdeutz** [comment]
@PhilETaylor thanks for reporting, @nikosdion enjoy your vacation. Maintenance will look at it.

**Comment by nikosdion** [comment]
@PhilETaylor Oh come on, Phil! I am replying to your issue on the same tone this issue and all your other issues the last 10 hours are written. Funny you don't like others treating you the same way you treat them, huh?

Count how many times you use the word "fiasco" in your issues the last 9 hours. Count how many personal attacks you have made. Even here you are spreading FUD by making **what you know is a FALSE CLAIM** you are "forever locked out" of your Joomla account. The only thing you achieve with this kind of false and unfair comments is undoing ten years of trying to educate users on account security and give them the tools to protect their sites.

Please talk to people the same way you want them to talk to you.

In any case, I am going to write code to fix this. @rdeutz thanks for the offer but I am not one to throw code over the wall and call it a day.

**Comment by nikosdion** [comment]
@rdeutz Please assign this issue to me

**Comment by rdeutz** [comment]
@nikosdion ok, done.

**Comment by PhilETaylor** [comment]
I have not made a single personal attack. I have identified and reported genuine issues with the Joomla 4.2 release that could and should have been found during testing by the teams dedicated to testing the release. 

It is a fiasco that, yet again, a major release has had to be pulled by the Joomla project due to issues that should and would have been caught by better quality testing. 

I shall not entertain your drama.

**Comment by nikosdion** [comment]
Pull request https://github.com/joomla/joomla-cms/pull/38488. Please test.

**Comment by nikosdion** [comment]
@PhilETaylor Okay, let's take a deep breath. As one neurodivergent person to another: the way we perceive others' words and the way we perceive how _our_ words might affect others are not always in line with how most people do. Let's stop bickering and start working together. In the end of the day and regardless of the words we exchanged we **both** want to help Joomla succeed. I am sorry for misunderstanding the tone of your voice and do understand that you also read more to my reply than I said. While I am disappointed that you didn't test in May — yet you are right that I cannot and I **will not** dictate how you use your own time — I was also being factual, not snarky, saying that I _am_ cutting my vacation short (at least for today) to help fix what is broken in the code _I contributed_. I feel responsibility for my code. So let's stop bickering and work together. Thank you.
