### ISSUE TITLE
[4.2] MFA Captive page issues on mobile screen size. 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#38480]
Reporting on behalf of Mark, a user of Joomla. 

Use Joomla 4.2 on an iPhone 

Login when Multi Factor enabled. Get the captive page.

Issues

1) Clicking the Joomla logo opens and quickly closes that area
2) clicking the cog top right correctly shows the toolbar buttons, but there are duplicate (badly styled) buttons injected in mobile view in the page (blue/red/link) 
<img width="574" alt="Screenshot 2022-08-16 at 21 30 28" src="https://user-images.githubusercontent.com/400092/184979247-61db2262-eb13-4f36-b62a-defe3bc67679.png">

3) Clicking bottom left ... does nothing

4) clicking hamburger menu bottom right turns it into a X and back into a hamburger

5) one screen resolution higher - the toggle menu does nothing, the input box label is compressed

<img width="1026" alt="Screenshot 2022-08-16 at 21 32 27" src="https://user-images.githubusercontent.com/400092/184979622-8bf78750-9959-4c96-b246-0a3de0569ed0.png">

**Comment by nikosdion** [comment]
Thank you for NOT testing this back in May and now playing all high and mighty. Propose a solution. I don't have the time to do that in my vacation and when I'm back I have my actual business to run.

**Comment by PhilETaylor** [comment]
I choose to spend my time on non-toxic projects and without abuse. You do not get a right to demand how I spend my time. Thankfully. 

I am reporting genuine issues in an open source project - there is no "high and mighty" - but just a genuine issue to fix. 

>  Propose a solution

No. I will not. And it is not required to propose a solution in an open source project when reporting genuine issues.

>  I don't have the time to do that in my vacation and when I'm back I have my actual business to run.

No one asked you to. Ever.

**Comment by nikosdion** [comment]
@rdeutz Please assign this issue to me

**Comment by nikosdion** [comment]
Pull request https://github.com/joomla/joomla-cms/pull/38488  Please test.

**Comment by nikosdion** [comment]
I cannot reproduce this on an iPhone SE (2020), the smallest screen device I have in my possession, using Safari and a Verification Code as indicated in the issue report.

Test 1: When logging into the backend I do see the field to enter my verification code. I do that and tap on the blue Validate button. It works as intended.

Test 2: When logging into the backend I do see the field to enter my verification code. I do that and tap on the cog button at the top right. The toolbar pane opens just fine. I tap on the “Validate” button there. It works as intended.

Test 3: When logging into the frontend I do see the field to enter my verification code. I do that and tap on the blue Validate button. It works as intended.

The whole report sounds like there is a JavaScript issue on that site. However, it's not a JavaScript issue coming from core code as far as I can see.

If you could provide access to an affected test site maybe I could tell you more.

**Comment by PhilETaylor** [comment]
Your comments I assume are about issue 2 I reported:

> clicking the cog top right correctly shows the toolbar buttons, but there are duplicate (badly styled) buttons injected in mobile view in the page (blue/red/link)

You are not understanding the issue

You assume the issue is that the buttons dont work. That is not what was said or reported. 

The issue is that Joomla uses the toolbar for the actions. The toolbar correctly has the actions. the toolbar works - therefore there is no need for duplicated buttons to magically appear in Red Blue and a Link when only on small screens. Small screen users should be using the Joomla toolbar, like everywhere else in Joomla, like when using this page on larger screens - its a standard interface design that is expected by Joomla users. 

Nothing in my report said the validate buttons did not work. 

The test site is a stock Joomla Site, there is nothing else installed in it, all Javascript is Joomla Core. The issues number 1, 3, 4 are all present in Joomla Core javascript and should be removed on the captive page as they serve no purpose in a captive environment chrome. 

Issue 5 is just one of html layout and is easily fixed.

**Comment by nikosdion** [comment]
> You assume the issue is that the buttons dont work. That is not what was said or reported.

That's what it read like.

> The issue is that Joomla uses the toolbar for the actions. The toolbar correctly has the actions. the toolbar works - therefore there is no need for duplicated buttons to magically appear in Red Blue and a Link when only on small screens. Small screen users should be using the Joomla toolbar, like everywhere else in Joomla, like when using this page on larger screens - its a standard interface design that is expected by Joomla users.

Yes, there **is** a need. The reason is called User Experience and consistency. If you had participated in the discussion in May or read it before making an assumption you'd have known. 

Conceptually (in the mind of the user) this is NOT a standard Joomla form page where actions are always in the toolbar. This looks like, feels like and works like a login page. Login pages have action buttons below the fields the user uses to interact with it.

A minority of users, like you, might thing to use the cog to open the toolbar. The majority would be starting at a screen with no obvious way to proceed.

> If you want the buttons in the page on small screens, then there is no need for duplication of these buttons in the toolbar and they could be removed from the toolbar. Duplication is a anti pattern for interface design.

I agree and that was exactly my argument in May. However, the only way to get this PR merged was to compromise and have a solution which would appeal both the the actual users using this feature AND to people who insisted that the One True Joomla Way is to have a toolbar. Hence the duplication.

This is already something discussed ad nauseam, I am not going to have the same discussion I have already wasted three days of my life on.

> Nothing in my report said the validate buttons did not work.

let me quote you verbatim: “Clicking bottom left ... does nothing”. Bottom left is the Validate button.

@rdeutz Please label this issue invalid and close it. The only actionable issue is a design decision already made in May.

**Comment by PhilETaylor** [comment]
> Yes, there is a need. The reason is called User Experience and consistency.

But yet you HIDE the in-page buttons on larger displays... thus changing the User Experience and destroying consistency... /facepalm/

> Conceptually (in the mind of the user) this is NOT a standard Joomla form page where actions are always in the toolbar.

But yet on a larger screen they are... 

> Bottom left is the Validate button.

No it is not. Bottom left  ( DOT DOT DOT) the ellipsis icon...

**Comment by PhilETaylor** [comment]
> @rdeutz Please label this issue invalid and close it. The only actionable issue is a design decision already made in May.

Proof that you have not even read what I wrote. 

There are at least THREE other issues to resolve on a small screen, the JS icons in the TOP LEFT BOTTOM LEFT and BOTTOM RIGHT which are all invalid or broken in captive mode

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/38486#issuecomment-1217704680

**Comment by nikosdion** [comment]
@PhilETaylor Again, **READ THE DISCUSSION FROM MAY**. All of that has already been discussed.

> Proof that you have not even read what I wrote.

Unlike you, I actually do read what you write.

> There are at least THREE other issues to resolve on a small screen, the JS icons in the TOP LEFT BOTTOM LEFT and BOTTOM RIGHT which are all invalid or broken in captive mode

None of that has anything to do with the MFA feature. This is how Joomla works. It shows these buttons EVEN THOUGH nothing is published in these module positions. This is a template issue, not an MFA issue. My remit was very specific and I could not possibly touch the backend template.
