### ISSUE TITLE
[4.x] Naming of overridden file (editable) is not chosen correctly.

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#38497]
### Steps to reproduce the issue

Goto:
- Templates: Customise (Cassiopeia) > Editor > /templates/cassiopeia > html

### Expected result
Naming:
**Override** file (editable)

### Actual result
Naming:
**Overridden** file (editable)

### System information (as much as possible)
J4

### Additional comments
Because this file is NOT overriden, that is the Original file.
![screen shot 2022-08-17 at 09 53 08](https://issues.joomla.org/uploads/1/c6218d48a85e44a9b8cadd2f92a6228c.png)

**Comment by richard67** [comment]
The override file is the one which overrides the original file, so the original file is the one being overridden. I do not see any mistake in that terminology.

**Comment by brianteeman** [comment]
Linguistically this is a bit weird and I think it is currently wrong but would like to hear more views.

Overridden is the past participle

The original file is being overriden by the new file

therefore we have an **original** and an **override**

**Comment by Abernyte-Git** [comment]
I would agree, neither usage is horribly wrong, just confusing.  A past participle describes a completed action so the use of **overridden** should refer to the original file being amended not to its new state.
For clarity is it not better to have an Original file and an Override file, which is the present and future simple tense?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38497">issues.joomla.org/tracker/joomla-cms/38497</a>.</sub>

**Comment by brianteeman** [comment]
> For clarity is it not better to have an Original file and an Override file, which is the present and future simple tense?

Thats my current thinking as well. Lets leave this open for some other comments and then we can create a pr

**Comment by richard67** [comment]
@brianteeman Does your PR #38541 close this issue?

**Comment by brianteeman** [comment]
Yes this can be closed

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38541 . Thanks in advance.
