### ISSUE TITLE
Child of Atum template does not show correct text at login page

### ISSUE THREAD

**Issue by pierre-pvln** [joomla/joomla-cms#38499]
### Steps to reproduce the issue
Create a child template for Atum template
Added a user.css in css folder of atum template (/media/templates/administrator/atum_child/css/user.css)
Set this child as the default template

### Expected result
in login page sidebar left:
**Joomla Administrator Login**

### Actual result
**TPL_ATUM_BACKEND_LOGIN**

### System information (as much as possible)
Joomla 4.2.0
PHP 8.0

### Additional comments
When I switch back to atum default (the parent) the correct text is shown.
I have no user.css in atum default.

**Comment by brianteeman** [comment]
Confirmed

**Comment by chmst** [comment]
The system tries to load the language file tpl_atum_[childname] from the language folder, which does not exist. Probably the same in frontend.

**Comment by brianteeman** [comment]
Its not just the login page it is all the pages that have this problem. It's not noticable visually on the template dashboard for example but it certainly is for a screenreader where it breaks a lot of strings

**Comment by alikon** [comment]
please follow the discussion of this issue here #38568
