### ISSUE TITLE
[4.2] User defined Hide Table Columns: unattractive list display

### ISSUE THREAD

**Issue by sba** [joomla/joomla-cms#38503]
### Steps to reproduce the issue
- Install german language pack
- Goto Content => Categories

### Expected result
![grafik](https://user-images.githubusercontent.com/186256/185113258-940f7c80-0cae-4e7f-9380-20dd05939c34.png)

### Actual result
![grafik](https://user-images.githubusercontent.com/186256/185113199-737fef7b-2a8e-48ae-9243-ab8d7150c4c0.png)

### System information (as much as possible)
- Joomla 4.2.0
- Latest Firefox or Chrome

### Additional comments
Can be fixed with additional style:
`
.dropdown-menu li label {
  white-space: nowrap;
}
`

**Comment by richard67** [comment]
> Can be fixed with additional style:
.dropdown-menu li label { white-space: nowrap; }

Should be a more specific selector, otherwise it would also affect other pulldowns, e.g. the pulldown menu from the menu module.

**Comment by chmst** [comment]
It is not quite consistent The columns have icons and it is not obvious which icon belongs to which entry. Would it be possible to use icons (with invisible text) instead of long names? @brianteeman

**Comment by brianteeman** [comment]
Anything is possible but I don't understand your request

**Comment by richard67** [comment]
As far as I understand @chmst , she wants to use icons instead of the column titles. Have fun in a list view with 15 or 20 columns to find icons which are sufficiently distinguable from each other so you quickly can see to which of the 15 or 20 columns they belong. In my opinion a silly idea, and I haven’t seen any software which does it that way, chose the columns to be displayed in a table by an icon and not the (full or shortened) title. In my opinion a silly idea which is not practicable and result in bad ux and due to small icons maybe also bad accessibility.

**Comment by brianteeman** [comment]
Thats what I thought it meant but for the reasons you stated I think it must be something else

**Comment by brianteeman** [comment]
please test #38507

**Comment by richard67** [comment]
Meanwhile I had a closer look on the issue, and I must admit that **I've made a mistake**.

**I was not aware of the fact that we already use in diverse list views for some columns an icon and for some other columns a text as column title**, and so I thought the icons were a new idea for the column selection dropdown of the show or hide columns feature.

I understand now that @chmst only wanted to make the column titles in that dropdown equal to the column titles in the table. Currently they aren't equal, e.g. we have an icon for the status column's title in the table and a text in the dropdown, and so it's not always clear to which column belongs what (except of course by the order, that should be equal).

But **I still think a mix of icons and text will not look good** and will not be easy to get by the user, and I also think we should never have established that mix of icons and text for the table column titles in the list view. It might have made sense when we had problems with space (width), but now as we can decide which columns to show or hide, that space problem is less critical.

So I would still recommend to make that consistent on the long run, i.e. use text only or use icons only at both places, or maybe let the user adjust some setting to select if icons or text.

Possibly inspired by the imagination I had on the (in my opinion) ugly look of the dropdown with a mix of icons and text, I had written **"silly idea"** in my comment.** That was not really nice, and I honestly apologize for that and will try to avoid that in future.** @chmst I hope you can accept my apologize.

**Comment by brianteeman** [comment]
Is this what you are referring to
![image](https://user-images.githubusercontent.com/1296369/185454821-a132a268-90b0-4586-b8a2-16d0348ec05f.png)

If so then those columns really should look the same as 
![image](https://user-images.githubusercontent.com/1296369/185455060-bbeed888-4370-4d0d-a98e-9cd8104d5eec.png)

I thinlk categories is the only place where you will see the icon on its own

**Comment by richard67** [comment]
@brianteeman The "Ordering" column also doesn't have a text, only an icon. But yes, that's what I meant.

**Comment by richard67** [comment]
Anyway, the main thing is that I made a mistake and that I have chosen wrong words and that I realized my mistakes and want to apologize.

**Comment by brianteeman** [comment]
So I would say that the columns with just an icon should be updated to include text but I would not add the icon to the dropdown.

As for the ordering column - I have no strong opinion
