### ISSUE TITLE
Updating JCE component results in 500 error code (administration)

### ISSUE THREAD

**Issue by mcassisa** [joomla/joomla-cms#38509]
### Steps to reproduce the issue

Update the JCE component and Extension Package in Joomla!

### Expected result

The expected result is an updated JCE component 

### Actual result

After a message telling the administrator that all went fine, the administration part of the joomla! website is not accessible anymore (error 500)

The apache2 log:
AH01071: Got error 'PHP message: PHP Fatal error:  Cannot declare class En_GBLocalise, because the name is already in use in /var/www/apache2/html/language/it-IT/localise.php on line 21

### System information (as much as possible)
Ubuntu 20.04.4
Apache 2.4.41
Joomla! 4.1.5
JCE Editor: 2.9.29
System Locale: LANG=en_US.UTF-8

### Additional comments
The admin user's backend language is set to "default" - english
In order to have the system working again, the class En_GBLocalise had to be renamed (e.g. to En_GBLocaliseX @ line 21 /var/www/apache2/html/language/it-IT/localise.php 
After updating the italian language it-IT through the joomla admin web page the error disappeared and the file /var/www/apache2/html/language/it-IT/localise.php was updated (this meaning that the class name has been restored to En_GBLocalise, overwriting the modification)

**Comment by zero-24** [comment]
> AH01071: Got error 'PHP message: PHP Fatal error: Cannot declare class En_GBLocalise, because the name is already in use in /var/www/apache2/html/language/it-IT/localise.php on line 21

This is an know issue thats in discussion with the italian TT but is not something that is a core issue. Please try this language pack: https://downloads.joomla.org/de/language-packs/translations-joomla4/downloads/joomla4-italian/4-2-0-3 When that still dont work please go and install the 4.1.5 languag pack over the existing 4.2.0 pack as a workaround: https://downloads.joomla.org/de/language-packs/translations-joomla4/downloads/joomla4-italian/4-1-5-1

Thanks

**Comment by 01Kuzma** [comment]
The same thing happens with Lithuania translation.
Installing the 4.1.5.1 language pack has fixed this bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38509">issues.joomla.org/tracker/joomla-cms/38509</a>.</sub>

**Comment by Laurent-run-974** [comment]
![screen shot 2022-11-17 at 13 47 39](https://issues.joomla.org/uploads/1/3cc71d49240570decda8c23aa835e4cc.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38509">issues.joomla.org/tracker/joomla-cms/38509</a>.</sub>
