### ISSUE TITLE
[4.2] The Joomla! 4.2.0 Upgrade Package is missing some images

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#38501]
### Steps to reproduce the issue

Download the concerning packages:
- Joomla! 4.2.0 Upgrade Package (.zip)
- Joomla! 4.2.0 Full Package (.zip)

Compare the images folders with each other.

Link: [Joomla! Downloads](https://downloads.joomla.org/cms/joomla4/4-2-0 "https://downloads.joomla.org/cms/joomla4/4-2-0")

### Expected result

- Joomla! 4.2.0 Upgrade Package (.zip)

This package is NOT missing images, if you compare this with the full package.

### Actual result

- Joomla! 4.2.0 Upgrade Package (.zip)

This package is missing the following images:
![screen shot 2022-08-17 at 10 58 48](https://issues.joomla.org/uploads/1/c0d4bb06afd064209bd9b5e38202bcc7.png)

### System information (as much as possible)

J4.2

### Additional comments

**This problem probably started before J4.2 !**

**Comment by zero-24** [comment]
That is intended to avoid getting that images back when deleting them after the initial install via any update again.

**Comment by sandewt** [comment]
> That is intended to avoid getting that images back when deleting them after the initial install via any update again.

I missed these images despite the fact that I never deleted them.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38501">issues.joomla.org/tracker/joomla-cms/38501</a>.</sub>

**Comment by brianteeman** [comment]
@sandewt I'm sorry but I don't understand what you are saying here.

**Comment by sandewt** [comment]
@brianteeman I try to explain:

First: I update a site J4.1.5 with the Joomla! 4.2.0 Upgrade Package (.zip). No images are added.
Then: I installed the same site with the Joomla! 4.2.0 Full Package (.zip). Images are added.

**Comment by brianteeman** [comment]
As @zero-24 said that is the intended behaviour

**Comment by sandewt** [comment]
Intended behaviour
