### ISSUE TITLE
Error with Cli Apps after upgrading to 4.2

### ISSUE THREAD

**Issue by jhrenshaw** [joomla/joomla-cms#38500]
### Steps to reproduce the issue

php /path-to-root-directory/cli/joomla.php update:extensions:check

### Expected result

Fetching Extension Updates
==========================

 ! [NOTE] There are available updates to apply

### Actual result

RuntimeException {#1797
  #message: "Could not parse the requested URI http://path-to-root-directory/cli/joomla.php"
  #code: 0
  #file: "/path-to-root-directory/libraries/vendor/joomla/uri/src/AbstractUri.php"
  #line: 373
  trace: {
    /path-to-root-directory/libraries/vendor/joomla/uri/src/AbstractUri.php:373 { …}
    /path-to-root-directory/libraries/src/Uri/Uri.php:286 {
      Joomla\CMS\Uri\Uri->parse($uri)^
      › {
      ›     return parent::parse($uri);
      › }
      arguments: {
        $uri: "http://path-to-root-directory/cli/joomla.php"
      }
    }

### System information (as much as possible)

Redhat Linux 8
PHP 7.4.30
Mysql 8.0.26

### Additional comments

If you try

cd /path-to-root-directory/cli/
php joomla.php update:extensions:check

then all is ok.

Works fine with the full path using Joomla 4.1

**Comment by alikon** [comment]
thanks for reporting 
please follow here #38518
