### ISSUE TITLE
[4.2] Position next button page navigation

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#38512]
### Steps to reproduce the issue

Open a page with the page navigation buttons.

### Expected result
Position (first) next button at the right.

![screen shot 2022-08-18 at 08 52 03](https://issues.joomla.org/uploads/1/2b036b990810706dee62c346fcefdac8.png)

### Actual result

Position (first) next button at the left.

![screen shot 2022-08-18 at 08 52 23](https://issues.joomla.org/uploads/1/890a74469b9a0835393bdeb143296af6.png)
### System information (as much as possible)

J4.2

### Additional comments

- It is more consistent that the next button is always on the right side.
- The next and prev buttons look a bit small, so they could be bigger.

See #38236

[EDIT] Oops I  gave myself a thumb :-)

**Comment by sandewt** [comment]
@brianteeman 

My suggestion is to roll back the previous PR #38236, and just replace the following class:

`<a class="btn btn-sm btn-secondary"`
with
`<a class="p-2 btn btn-sm btn-secondary m-1"`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38512">issues.joomla.org/tracker/joomla-cms/38512</a>.</sub>

**Comment by brianteeman** [comment]
Please test #38612
