### ISSUE TITLE
[4] Nightly builds. "Reinstall Joomla! core files" doesn't show what ZIP it will install.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#38514]
### Steps to reproduce the issue
- Go to "Joomla update" in a Joomla with current version. Or dev versions (doesn't work at the moment with Joomla 4.2-dev).
- Click "Check for update".

#### Joomla 3
- tells you which file will be installed.
- Installation starts with click on "Reinstall"

![grafik](https://user-images.githubusercontent.com/20780646/185393307-3d9cc5ae-c897-447d-9c88-82def97b3165.png)

#### Joomla 4
- tells you nothing. Sends you to URLs that tell you nothing helpful.
- When you are on dev update channels: Link "Additional informations" leads to https://developer.joomla.org/nightly-builds.html
  - Complete nonsense during an update procedure. Tells you nothing specific.
- Installation starts immediately with click on "Reinstall" without any helpful additional informations.

![grafik](https://user-images.githubusercontent.com/20780646/185393763-5c494106-70fd-4f87-b39e-28381d5f96ce.png)

### Additional comments
- This behavior is extremely annoying. At least when you are on dev channels.
- And also on stable releases. User should always know what ZIP will be used. Normally one uses this feature when you have issues with Joomla. In these situations it can be eytremely helpful if an update failed somehow, which version will be reinstalled.

**Comment by zero-24** [comment]
I agree. The info URL goes to the nighly page as that is the only place where infos are available. But I agree that it would make sense to show some more details on reinstall maybe the version number is a first step when the decision has been taken to take the URL off.

**Comment by richard67** [comment]
> when the decision has been taken to take the URL off.

@zero-24 Has such a decision been made or is it planned? What speaks against showing the download URL?

**Comment by zero-24** [comment]
Well looks like a decision has been made as it was showed within 3.x but I dont know whether it was a that definitiv decision maybe just a style opinion while that page was redesigned.

**Comment by richard67** [comment]
I also don’t remember if it was a style thing or for another reason. So we are 2 in the club ;-)

**Comment by ReLater** [comment]
3! ;-)

I only remember criticising that at the time when the huge icons came up ;-) (Background then: I always have to scroll down before I see the process bar, infos, buttons, whatever.)

**Comment by ReLater** [comment]
After short investigations:
All informations are available in file/view `administrator\components\com_joomlaupdate\tmpl\joomlaupdate\reinstall.php`

in array `$this->updateInfo`

```
$this->updateInfo['object']->get('downloadurl')->_data

=> https://developer.joomla.org/nightlies/Joomla_4.3.0-dev-Development-Update_Package.zip
```
```
$this->updateInfo['object']->get('name')->_data

=> Joomla! 4.3 Nightly Build
```

`$this->updateInfo['object']->get('version')->_data`

and others.

**Comment by richard67** [comment]
I know. Question is just if we want to show it and if yes, do it in a nice way.

**Comment by ReLater** [comment]
Thanks for spending time with it. I am not an aesthetician. I will use 2 overrides, installable via a file extension in atumn folder; with an additional $displayData['additionalInfos']. Thus I get also rid of all the noise and scroll actions that these emptystate pages produce.
