### ISSUE TITLE
Nightly builds. "Reinstall Joomla! core files" button dead. "updateCheck is null"

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#38513]
### Steps to reproduce the issue
- Joomla 4.1.5. Backend.
- Go to /administrator/index.php?option=com_config&view=component&component=com_joomlaupdate
- Edit Update Source options:
- "Custom URL": https://update.joomla.org/core/nightlies/next_patch_list.xml (image is wrong here)

![grafik](https://user-images.githubusercontent.com/20780646/185387240-57db9258-3e15-42cb-bd1e-e0e20454bebf.png)

- Save&Close
- Click button "Check for updates" when Update Checker doesn't start automatically.
- Go through update to version 4.2.1-dev.

Issue starts:
- Click button "Check for updates".
- Click on button "Reinstall Joomla! core files".

### Expected result
- Current nightly 4.2.1-dev package will be picked and installed. Like on Joomla 3, Joomla 4.1.5.

### Actual result
- Nothing happens. Button link not populated correctly by JavaScript.
- Activate Debug Mode. Try again.

See browser Javascript console:

`Uncaught TypeError: updateCheck is null`

![grafik](https://user-images.githubusercontent.com/20780646/185388558-8a4589c2-0d85-4a25-b9e3-abc411f46c87.png)

### System information (as much as possible)
- PHP8.1
- Firefox (current version)

### Additional comments
- Also tested with 4.3.0-dev, 4.2.0-dev, whatever.

**Comment by ReLater** [comment]
I'll test again with a new 4.1.5 install.

I see that button behavior on any 4.2 site (dev or stable). Doesn't matter what the base version was. And see it for a longer time now.

But: Even if the update server url is wrong or XML damaged, whatever, there should not be a JS error.

**Comment by zero-24** [comment]
I agree this is why i "hope" it has something todo with the local site you are doing your testing with else we might have another major issue with the updater component.

**Comment by ReLater** [comment]
> I agree this is why i "hope" it has something todo with the local site you are doing your testing with else we might have another major issue with the updater component.

I always test online. No local sites.

#### To clarify

I'm already on 4.2.1-dev. And then I get the updateCheck JS error.

The link behind the "Reinstall" is .../administrator/index.php?option=com_joomlaupdate# then.

#### New test with fresh 4.1.5

Same behavior like described in opener post.

4.1.5: All works like expected.

4.1.2-dev: See opener post. Firefox and Vivaldi. Console on Vivaldi differs a bit but same file, same line:

![grafik](https://user-images.githubusercontent.com/20780646/185416339-a6cba861-e4f7-4faf-a691-559ff26a092d.png)

Deleted cache folder via FTP between each tests.

**Comment by zero-24** [comment]
I'm sorry I'm not at my desk right now but can you please verify whether and update via the "regular" update path works and just the reinstall is broken?
So 4.2.0 -> 4.2.1-dev via the next_patch update server works or not.

**Comment by zero-24** [comment]
PR here @ReLater please test works good for me: https://github.com/joomla/joomla-cms/pull/38519#issue-1343375385
