### ISSUE TITLE
[4.x] Deprecated: trim(): Passing null when call Path::clean - PHP 8.1

### ISSUE THREAD

**Issue by sonvnn** [joomla/joomla-cms#38510]
### Steps to reproduce the issue
When call function Path::clean(''); with empty $path on PHP 8.1 
System will raise warning
`Deprecated: trim(): Passing null to parameter #1 ($string) of type string is deprecated in /{root}/libraries/src/Filesystem/Path.php on line 198`

### System information (as much as possible)

- Joomla 4.x
- PHP 8.1

**Comment by richard67** [comment]
Closing as having a pull request. See #38511  .
