### ISSUE TITLE
[4] Upload files via FTP client (FileZilla/Windows) has at least "1 failed transmission"

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#38515]
### Steps to reproduce the issue
- Windows, FileZilla.
- Download a Joomla_4.1.5-Stable-Full_Package (I saw the issue already with other versions).
- Unpack ZIP file locally.
- Upload extracted files with FTP client to Linux online webspace.
- Any trial has at least "1 failed transmission" which is unsolvable.
- I know that this is not a real problem (/vendor/../bin/ folder that often have problems on WIN) but could irritate some users.

![grafik](https://user-images.githubusercontent.com/20780646/185420004-f33e464b-78f3-4437-9e4c-a21442fc5e65.png)

**Comment by brianteeman** [comment]
Pull Request incoming
