### ISSUE TITLE
[4.1.5] Unable to update site to 4.2

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#38522]
### Steps to reproduce the issue
1. Open backend and navigate to the Joomla Update component.
2. Click "Check for updates"

### Expected result
The 4.2 update should be found, and be offered for updating

### Actual result
The page shows "Currently no update available"

### System information (as much as possible)
PHP Version: 7.4.30
Joomla! Version: Joomla! 4.1.5 Stable [ Kuamini ] 21-June-2022 14:00 GMT
Browser Version: Microsoft Edge Version 104.0.1293.54 (Official build) (64-bit)

### Additional comments
I've verified that com_installer has Joomla! Core as an available option, and that it is published. I've opened https://update.joomla.org/core/list.xml to confirm that 4.2.0 is an available option for updating. I've also taken steps to clear the cache.

**Comment by zero-24** [comment]
4.2.0 has been pulled of form the update server yesterday and we are working on 4.2.1 you can still manually update with the package provided on downloads.joomla.org.

Will close as expected behavior for now.
