### ISSUE TITLE
[4.1.5] Fields: Sort column by 'Field Group' give '403'

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#38538]
### Steps to reproduce the issue
1. go to `index.php?option=com_fields&view=fields&context=com_content.article`
2. click on column title 'Field Group'
3. a `403, Forbidden` is shown:

https://user-images.githubusercontent.com/89642616/185730255-75796d70-9c4c-477f-ba4c-c48b0c2f56e1.mov

Browser console:

<img width="717" alt="field group" src="https://user-images.githubusercontent.com/89642616/185730294-f782b019-e1a7-4d4b-bf8e-0414f6b50be9.png">

### Expected result

Fields sort by 'Field Group'.

### Actual result

403

### System information (as much as possible)

<img width="615" alt="si" src="https://user-images.githubusercontent.com/89642616/185730347-d2de3ff2-106b-4354-b796-320a01a1b96a.png">

### Additional comments

- Get 403 on articles, contacts and users.
- using sort by dropdown: same result
- append a field to a field group: same result
- Error reporting on 'Maximum' show no Error.

**Comment by brianteeman** [comment]
I couldn't replicate this and the error message makes no sense for a clean install

**Comment by Franzwohlkoenig** [comment]
Thanks for your comment @brianteeman. As the site has updates starting at 4.0.0 and i had to manually update each version its something in the site, so closing.
