### ISSUE TITLE
adduser CLI command fails on upgrade to 4.2

### ISSUE THREAD

**Issue by jhrenshaw** [joomla/joomla-cms#38543]
### Steps to reproduce the issue
go to CLI directory
php joomla.php user:adduser --username=me --name="My Name" --email=valid_email_address --password="my password" --usergroup=Registered

### Expected result
user is added to the user table

### Actual result
user is not added to the user table

the return value of $userObj->getError() is something like

'the field otpKey does not have a default value'

There is a similar issue if the field 'otep' is not given a default value

### Additional comments

I think you just need to add

$user['otpKey'] = '';
$user['otep'] = '';

after line 148 in the addUserCommand.php file

**Comment by laoneo** [comment]
@nikosdion, is this related to the MFA changes of 4.2?

**Comment by nikosdion** [comment]
@laoneo Yes. Please assign this to me, I'll come up with a PR shortly.

**Comment by nikosdion** [comment]
To be fair, the table does give both columns a default value (this is MySQL, the same happens with PostgreSQL):
```
  `otpKey` varchar(1000) NOT NULL DEFAULT '' COMMENT 'Two factor authentication encrypted keys',
  `otep` varchar(1000) NOT NULL DEFAULT '' COMMENT 'Backup Codes',
```

It appears that the database table definition is broken on the database server. Still, it's fairly trivial to fix.

**Comment by nikosdion** [comment]
This is the PR https://github.com/joomla/joomla-cms/pull/38549

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38549 . Thanks in advance.
