### ISSUE TITLE
TAGS : error on display tags with a lot of tags 

### ISSUE THREAD

**Issue by elecoest** [joomla/joomla-cms#38547]
### Steps to reproduce the issue

In Joomla 4 latest version, PHP 8.0 in **backend** : 

- Create more than 30 tags
- Add all tags on your content
- Save
- Display your content

### Expected result

All tags related are displayed 

### Actual result

Only the 30th tags are displayed

### System information (as much as possible)

This file : 
/libraries/src/Form/Field/TagField.php
seems load only the 30th first tags :-(

**Comment by laoneo** [comment]
What is your default list length in the global Joomla configuration?

**Comment by elecoest** [comment]
100

The value 30 is hard designed

Le lun. 22 août 2022 à 12:57, Allon Moritz ***@***.***> a
écrit :

**Comment by brianteeman** [comment]
I  think you may have misread the code regarding the hardcoded value of 30 and where it is used.

**Comment by elecoest** [comment]
@brianteeman I have a bug, i'm not an expert :)

**Comment by chmst** [comment]
@elecoest pleaes set the parameter for tags to nested. 
![grafik](https://user-images.githubusercontent.com/1035262/185924908-a7e25609-bfef-48f7-8fdc-f3477174232a.png)

**Comment by chmst** [comment]
@laoneo @brianteeman we had already different issues here. So would say that we need a UX improvement here. I have no clue for what this param is used.

**Comment by laoneo** [comment]
The 30 limit is introduced by #31481.

**Comment by elecoest** [comment]
@chmst  it's OK with your parameter. Thanks. Not really easy to understand.
