### ISSUE TITLE
[J4.2] Module Newsflash:  Show Article Images show/hide button does not work

### ISSUE THREAD

**Issue by peterhulst** [joomla/joomla-cms#38542]
### Steps to reproduce the issue
Use the standard installation with installation template and blog articles.
The module Articel Newsflash show the intro images.
When switching Show Article Images from Show to Hide, the intro (or full images if selected) remains displayed.

### Expected result
When: Show Article Images: Hide, then all images should be hidden.
This should be the same behaviour when Show Intro/Full Image is selected: No

### Actual result
When switching Show Article Images from Show to Hide, the intro (or full images if selected) remains displayed.

### System information (as much as possible)
Joomla 4.2.1 rc 1, PHP8.1

### Additional comments
---

**Comment by brianteeman** [comment]
They are two seperate options
One controls the display of images contained in the article content and the other controls the display of the intro/full images

![image](https://user-images.githubusercontent.com/1296369/185862137-d2ba5b40-6cfe-4644-86e2-6d5a931640d9.png)

**Comment by peterhulst** [comment]
Thank you Brian. 
However the first option (Show Article Images) does not work. 
Select: Show or Hide: images are always displayed.
Regards, Peter<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38542">issues.joomla.org/tracker/joomla-cms/38542</a>.</sub>

**Comment by brianteeman** [comment]
I cannot replicate that _bug_

**Comment by peterhulst** [comment]
> I cannot replicate that _bug_

Strange!
In Joomla! 4.2.0 Stable [ Uaminifu ] 16-August-2022 13:05 GMT the _bug_ exist.
Show Intro/Full image: _No_  works as expected
Show Article Images: _Hide_ **does not work** and is still the same as _Show_

**Comment by brianteeman** [comment]
https://user-images.githubusercontent.com/1296369/185909415-e9c8a81e-4258-426a-bb58-18a04a149b4e.mp4

**Comment by peterhulst** [comment]
Thank you Brian.  
You convinced me with the very clear video.

My idea was that "Intro Image" was the image before 'Read More'. 
In the database in 'introtext'. 
But it is in the database as 'images', "image_intro".
Sorry for misunderstanding.

Regards,
Peter

**Comment by brianteeman** [comment]
Please can you close this

**Comment by peterhulst** [comment]
I have closed it now
