### ISSUE TITLE
[J4.1.5] Joomla could not detect new version 4.2

### ISSUE THREAD

**Issue by trananhmanh89** [joomla/joomla-cms#38551]
### Steps to reproduce the issue
- Install fresh joomla 4.1.5
- Go to `administrator/index.php?option=com_joomlaupdate`
- Check for update

### Expected result
- Joomla should show 4.2 available

### Actual result
- Joomla shows no update

### Additional comments
As i check on `https://update.joomla.org/core/list.xml`, the `4.2` package has `targetplatformversion="4.2"`. So joomla couldn't find new version.

**Comment by mariantanase** [comment]
https://github.com/joomla/joomla-cms/issues/38522#issuecomment-1219786939

**Comment by zero-24** [comment]
> As i check on https://update.joomla.org/core/list.xml, the 4.2 package has targetplatformversion="4.2". So joomla couldn't find new version.

Thats used only for updates within the 4.2 series. The upgrade from 4.1.5 will be possible once 4.2.1 has been released which is expected to be soon as there have been RC out since last week too. Will close here for that reason that right now this is expected behavior.
