### ISSUE TITLE
Improve information text for "Tag Entry Mode"

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#38553]
### Steps to reproduce the issue
The tags component has a parameter tag_field_ajax_mode

![grafik](https://user-images.githubusercontent.com/1035262/185932047-3b8aa698-c93d-42fb-bef8-1076f86cd902.png)
 
### Expected result
The information explains which consequences the alternatives AJAX and nested have on the system. 

### Actual result
The information says nothing what users can understand. i.e. https://github.com/joomla/joomla-cms/issues/38547

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38620 . Thanks in advance.
