### ISSUE TITLE
Child template language handling

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#38568]
### Steps to reproduce the issue

Create a child template from Cassiopeia
_cassiopeia_mychildtemplate_

### Expected result

(a) If the language files tpl_cassiopeia_mychildtemplate.ini and tpl_cassiopeia_mychildtemplate.sys.ini are created and left blank I expected the text from tpl_cassiopeia.ini and tpl_cassiopeia.sys.ini to be used. I.E. the cassioperia text will be used by default, the child being able to overwrite / add more as needed.

(b) I expected to be able to place language files in templates/cassiopeia_mychildtemplate/language/en-GB folder. This being consistent with elsewhere where you can use either modules/mod_mymodule/language/en-GB/mod_mymodule.ini or language/en-GB/mod_mymodule.ini

(c) I expected to be able to translate the template name (cassiopeia_mychildtemplate) in the templateDetails.xml file with text in cassiopeia_mychildtemplate.sys.ini.

### Actual result

(a) Have to duplicate all the cassiopeia text in the child language files. This will cause problems later when extra parameters / more text added to cassioperia - I would expect the child to inherit everything by default.

(b) Language files in templates/cassiopeia_mychildtemplate/language/en-GB folder are ignored.

(c) There appears to be no translation for the template name.

### System information (as much as possible)

Joomla 4.2.0

**Comment by BrainforgeUK** [comment]
Item (a) - Not leave tpl_cassiopeia_mychildtemplate.ini blank but put a single line in it ...

TPL_CASSIOPEIA_XML_DESCRIPTION="Cassiopeia child template for my site."

Can of course change TPL_CASSIOPEIA to TPL_CASSIOPEIA_MYCHILDTEMPLATE in both the .ini and .xml files, but that is not significant to this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38568">issues.joomla.org/tracker/joomla-cms/38568</a>.</sub>

**Comment by BrainforgeUK** [comment]
Overlaps. This gives more detail of what needs to be investigated.

**Comment by brianteeman** [comment]
Agreed. Maintainers please close the other issue and link it here
Please.

**Comment by alikon** [comment]
please test #38578
