### ISSUE TITLE
[PL] Translations in Crowdin

### ISSUE THREAD

**Issue by Valdnet** [joomla/joomla-cms#38564]
There are many text strings incorrectly translated in Crowdin for Polish that are approved. Unable to correct them due to limited permissions. I am asking for reviewer's rights.

**Comment by zero-24** [comment]
From my understanding the polish translation managed here from my understanding and only synced to crowdin: https://github.com/JoomlaPolska/jezyk-J4

cc @wojsmol

**Comment by wojsmol** [comment]
Hi @zero-24 @Valdnet 
As mentioned by @zero-24 Polish Translation is managed in in https://github.com/JoomlaPolska/jezyk-J4 and only translation for J$ 4.x is synchronized to crowdin. @Valdnet Please check that repo and create an issue there if necessary.

**Comment by Valdnet** [comment]
@zero24 @wojsmol Thank you for the information 😉.

In my opinion, you should use ready-made translation portals and automatic synchronization of translations to the repository. This makes it easier for translators and developers.
