### ISSUE TITLE
Upgraded to 4.2 - RSS Feed Module - Feed not found.

### ISSUE THREAD

**Issue by dgrimey** [joomla/joomla-cms#38572]
After upgrading to 4.2 my RSS Feed Modules show "Feed not found." I moved the site to other locations and same error. Reinstalled my previous back up before the 4.2 upgrade and everything worked. Tried simply coping some files from the old "Modules" directory to the new, but didn't resolved the issue.

**Comment by Franzwohlkoenig** [comment]
same as #38531?

**Comment by brianteeman** [comment]
This has been resolved for 4.2.1 which will be released soon(ish)

**Comment by dgrimey** [comment]
Besides 4.2.1 upgrade is there anything we can do to fix this? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38572">issues.joomla.org/tracker/joomla-cms/38572</a>.</sub>

**Comment by zero-24** [comment]
Apply the changes done here: https://github.com/joomla/joomla-cms/pull/38312#issue-1311370448 or upgrade to a 4.2.1 RC version.

**Comment by richard67** [comment]
Closing as solved with PR #38312 .
