### ISSUE TITLE
[4.1.5] Field Groups: Edit: Tab 'Publishing' is before 'Options'

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#38584]
### Steps to reproduce the issue
In 'Field Groups: Edit' the tab 'Publishing' is shown before the tab 'Options':

<img width="600" alt="1200px-Help-4x-Field-Groups-Edit-publishing-subscreen-en" src="https://user-images.githubusercontent.com/89642616/186414101-51988f43-9427-47c1-a755-5b87e6c8959a.png">

Usually its the other side around, as example "Fields: Edit':

<img width="600" alt="1200px-Help-4x-Fields-Edit-publishing-subscreen-en" src="https://user-images.githubusercontent.com/89642616/186414248-15864fdc-a514-4e94-b44c-cb6d3dacf07a.png">

### Expected result

Same ordering of tab.

### Actual result

see above.

### System information (as much as possible)

<img width="615" alt="185730347-d2de3ff2-106b-4354-b796-320a01a1b96a" src="https://user-images.githubusercontent.com/89642616/186414794-971c399e-b4c4-49e2-864e-3271225d9854.png">

### Additional comments

Compared also 'Articles: Edit' and 'Categories: Edit', they have 'Options' before 'Publishing'.

**Comment by brianteeman** [comment]
please test #38591
