### ISSUE TITLE
finder aka smart search index contains macros of loadmodule in search results

### ISSUE THREAD

**Issue by level420** [joomla/joomla-cms#38599]
### Steps to reproduce the issue
Enable smart search aka finder and publish a finder search module somewhere or connect a menu item to the smart search item type.
Enable the load modules plugin.
Enable the smart search content plugin.
Create a site module of type custom with some content and place it at custom positon `herewego`.
Create an article and place a loadposition macro in that article like this:
`{loadposition herewego}`
Now the finder automatically indexes the new article.
Go to the search box and search for `loadposition` or `herewego`.

### Expected result
I would not expect to see search results containing the article with the loadposition macro. 
I would not expect the search suggestions list containing the search items `loadposition` and `herewego`.
Instead I would expect that the macro is deleted in this case before indexing.

### Actual result
The search result does contain the article where the loadposition macro is placed and the suggestion list contains both `loadposition` and `herewego`.

### System information (as much as possible)
joomla 4.2.0
mariadb 10.6
php 8.1 running as fpm

### Additional comments
The code related is here:
https://github.com/joomla/joomla-cms/blob/4.2-dev/plugins/content/loadmodule/loadmodule.php#L43-L46
In case of `$context` being `com_finder.indexer` the macros `loadposition`, `loadmodule` and `loadmoduleid` should be removed.
I don't know the implication why in the case of finder triggering the `onContentPrepare` for loadmodule it is simply skipped, maybe for performace reasons.
I think this should be configurable in the loadmodule plugin or by adding an additional parameter to loadmodule like `renderinindex` or similar, which would allow to control the behaviour per macro.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38998 . Thanks in advance.

**Comment by NiSHoW** [comment]
This pull request has not yet been introduced. I found this issue in the latest version of Joomla 4.3.2. 
Are there any updates on this? 
I patched the code manually and it works by regenerating the smart search indexes.

**Comment by richard67** [comment]
@NiSHoW Each pull request needs 2 successful human tests before it can be accepted. You can help with that by testing the pull request.
