### ISSUE TITLE
[4.1.5] Media Options: 'Restrict Uploads: No' hide fields in different positions

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#38637]
### Steps to reproduce the issue

1. open 'Media: Options'
2. by default 'Restrict Uploads' is 'Yes' (please look at the red marked fields):
<img width="852" alt="yes" src="https://user-images.githubusercontent.com/89642616/187383833-0c6f3900-5bc8-44c8-92c7-11a11653e01c.png">
4. change 'Restrict Uploads' to 'No' the red marked fields are hidden:
<img width="843" alt="no" src="https://user-images.githubusercontent.com/89642616/187384298-41779621-54d4-4ac0-9fad-70efa52fec86.png">

### Expected result
The red marked fields are below each other.

### Actual result
The fields are in different positions.

### System information (as much as possible)

<img width="815" alt="si" src="https://user-images.githubusercontent.com/89642616/187385050-9c321789-2d35-48ff-8fe5-3f676558b988.png">

**Comment by Franzwohlkoenig** [comment]
Maybe this is expected behaviour – which i don't understand :-). 

If so i would close, no need to have unnecessary open issues.
