### ISSUE TITLE
Phoca Gallery: Menu disappear in cassiopeia

### ISSUE THREAD

**Issue by Rolli1962** [joomla/joomla-cms#38634]
### Steps to reproduce the issue
Upgrade installation from 3.10.11 to current version 4.1.5, than to 4.2.1-rc2

### Expected result
menu entries should be present

### Actual result
menu entries are disappearing

### System information (as much as possible)
Joomla 4.2.1-rc2. Currently in test environment ubuntu / xampp

### Additional comments
Phoca Gallery elements are working in menu, but picts are not shown correctly.
Change installation to test, updated to 4.2.1-rc2
Phoca Gallery picts are shown correctly, but now the menu entries disappearing completely
Of course this seems to be the lonly minor issue, think I will update my life-site as soon 4.2.1 is set to free.
Than  issue can be seen on wupperveilchen.de

**Comment by ChristineWk** [comment]
So I see the menus as normal. But: did you migrate from Joomla 3 to Joomla 4 following this procedure?
https://www.phoca.cz/documents/50-joomla/phoca/1178-how-to-migrate-extensions-from-joomla-3-to-joomla-4

For example, Missing a "theme", e.g. theme_simple.
Also, the photo page is on Template Protostar instead Cassiopeia.
That was just a quick overview for now.

**Comment by chmst** [comment]
Thank you, @ChristineWk . I close this for now as it is not a joomla core issue.

**Comment by Rolli1962** [comment]
Thans for comment. Maybe if someone else is reading - no, I have not followed the migrate procedure (seems that are the step to move the configuration of an old phoca site to a fresh set up of joomla 4). I have done a upgrade of a joomla 3.10 site.
But I found out that in the administration of phoca -> Styles was activated a default.css. Even the file is empty - if I deactivate it, it is working. Maybe here an additional hint - Bootstrap (bootstrap.min.css) was deactivated and seems has still to be deactivated.
But thanks for comment - Roland

**Comment by ChristineWk** [comment]
> Thans for comment. Maybe if someone else is reading - no, I have not followed the migrate procedure (seems that are the step to move the configuration of an old phoca site to a fresh set up of joomla 4).

The migration of Joomla 3 (of an current actual (!) PG version) to Joomla 4, has to be done as described in above link.
Between Joomla 3 and Joomla 4 there are changes (PG) in the database structure.



> Maybe here an additional hint - Bootstrap (bootstrap.min.css) was deactivated and seems has still to be deactivated. But thanks for comment - Roland

In Protostar (!) yes, the bootstrap.min.css has to be deactived. You can't use Protostar (or in your case it's a copy) in Joomla 4.

**Comment by ChristineWk** [comment]
Checked again your given URL and see, that it's on Cassiopeia now. It seems it is solved.
