### ISSUE TITLE
Contact Error while upgrade to php version 8

### ISSUE THREAD

**Issue by 11709394** [joomla/joomla-cms#38636]
### Steps to reproduce the issue

List contacts in a category will error if I change my php version from 7.4 to 8.0.

**Comment by chmst** [comment]
Which Joomla Version? Could you please post the error message?

**Comment by chmst** [comment]
I see 3.10.11. But post the message, please, and check if there is a template override.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38636">issues.joomla.org/tracker/joomla-cms/38636</a>.</sub>

**Comment by Hackwar** [comment]
After over 2 months no response from the original poster. Since J3 is EOL in regards to bugfixes, I'm closing this one.
