### ISSUE TITLE
Module select description

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38635]
### Steps to reproduce the issue
Go to create a new module
Look at the descriptions of each module - specifically Login

### Expected result
Text displayed (or truncated) with no html entities

### Actual result
html entities dislayed

![image](https://user-images.githubusercontent.com/1296369/187305944-4092fb3e-70ec-4d68-a07f-22a37e20c424.png)

### Additional comments
It is caused by 
https://github.com/joomla/joomla-cms/blob/9df5e6c7a7a1c6ec0aed99d6d4a22be048b9b299/administrator/components/com_modules/tmpl/select/default.php#L65

Wondering why we are stripping everything there?

**Comment by Quy** [comment]
#37740
