### ISSUE TITLE
No access : Call to undefined method Joomla\Component\.....\HtmlView::getCurrentUser()

### ISSUE THREAD

**Issue by Multistud** [joomla/joomla-cms#38648]
Hello, Since the joomla 4.2.0 update, I can no longer access certain menus in the administration and no page on the site except the home page.
PHP 8.1.0 - MySQLi 5.6.51-log - Mise en cache Désactivé - Gzip Désactivé
3rd Party :YOOthemePro 2.7.24, Virtuemart 4.0.6, VMuikitX 10.21
On FrontEnd 
ERROR 0
Call to undefined method Joomla\Component\Content\Site\View\Article\HtmlView::getCurrentUser()

# Function Location
1 () JROOT/components/com_content/src/View/Article/HtmlView.php:104
On BackEnd
ERROR 0
Cache
Call to undefined method Joomla\Component\Cache\Administrator\View\Cache\HtmlView::getCurrentUser()
Global Configuration
Call to undefined method Joomla\Component\Config\Administrator\View\Application\HtmlView::getCurrentUser()
Users
Call to undefined method Joomla\Component\Users\Administrator\View\Users\HtmlView::getCurrentUser()
Articles
Call to undefined method Joomla\Component\Content\Administrator\View\Articles\HtmlView::getCurrentUser()
Media
Call to undefined method Joomla\Component\Media\Administrator\View\Media\HtmlView::getCurrentUser()
Update Joomla
Call to undefined method Joomla\Component\Joomlaupdate\Administrator\View\Joomlaupdate\HtmlView::getCurrentUser()
Substitutions
Call to undefined method Joomla\Component\Templates\Administrator\View\Template\HtmlView::getCurrentUser()

### Actual result
I followed  advice form joomla team, and restored with joomla 4.1.5, after waiting for the new version 4.2.1, I installed it but I have exactly the same problem !!!!

### System information (as much as possible)

PHP 8.1.0 - MySQLi 5.6.51-log - Mise en cache Désactivé - Gzip Désactivé
3rd Party :YOOthemePro 2.7.24, Virtuemart 4.0.6, VMuikitX 10.21

**Comment by richard67** [comment]
> I followed advice form joomla team, and restored with joomla 4.1.5, after waiting for the new version 4.2.1, I installed it but I have exactly the same problem !!!!

@Multistud What means „installed it“? Have you used the Joomla Update component to update to that version? Or have you just uploaded andbunpacked the zip package without using the update component?

And what means „restored with joomla 4.1.5“? Does that mean there was a previous, failed attempt to update to 4.2.0, and you restored a backup? If so: have you used an empty database to restore the backup? How have you restored? Manually or with a tool?

**Comment by richard67** [comment]
Am not asking to blame. Just want to know what happen so we can find out what to investigate as next.

**Comment by alikon** [comment]
it was already reported on the forum https://forum.joomla.org/viewtopic.php?f=808&t=995951

**Comment by alikon** [comment]
i mean the post open date `Wed Aug 24`

**Comment by Multistud** [comment]
Hello and thank you for your answer.

Here I solved the problem, in fact I had restored the old version 4.1.5 FTP via a backup at the host but I had not restored the database...

So this time I restored the old version 4.1.5 FTP + database in order to find a functional site

Then I made the update for the new version 4.2.1 as well as the updates of the templates, YoothemePro 2.7.25 and VmuikitX 10.22.

Now everything seems to work normally with Joomla 4.2.1

**Comment by richard67** [comment]
@Multistud Glad you could solve it.

Closing as not a core issue.
