### ISSUE TITLE
No Migration from twofactorauth to multifactorauth in Joomla 4.2.1

### ISSUE THREAD

**Issue by hsm-berlin** [joomla/joomla-cms#38647]
Joomla 4.2.x Updates delete the twofactorauth plugin directory and creates an new multifactorauth directory. But the extension database will not be updated. It is not possible to delete the old extension-entries for plg_twofactorauth_totp and plg_twofactorquath_yubikey within the backend (only direct in database). The new multifactor plugins must be installed via the Backend com_installer | View=discover.

Would it be possible to update the database with the update?

**Comment by brianteeman** [comment]
Sounds like you did not update joomla using the joomla update component?

**Comment by hsm-berlin** [comment]
I upgraded first to 4.2.0 with the Joomla_4.2.0-Stable-Full_Package.zip because the automatic update was not available. I was not using the Update-Package. Perhaps that was the mistake?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38647">issues.joomla.org/tracker/joomla-cms/38647</a>.</sub>

**Comment by brianteeman** [comment]
My question is Exactly how did you upgrade?

**Comment by hsm-berlin** [comment]
I used /administrator/index.php?option=com_joomlaupdate&view=upload with the Joomla_4.2.0-Stable-Full_Package.zip

No idea why the databases have not been updated. With Joomla 4.2.1 the automatic update is available and the databases will be updated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38647">issues.joomla.org/tracker/joomla-cms/38647</a>.</sub>

**Comment by spamzini** [comment]
For me it's the same.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38647">issues.joomla.org/tracker/joomla-cms/38647</a>.</sub>

**Comment by HLeithner** [comment]
I understand the last comment by @hsm-berlin that the issues is solved and maybe triggered by using the wrong (none) update package. 

I'm closing this.

@spamzini please provide additional information if you still have the problem.
