### ISSUE TITLE
Api error in Content Field plugin with multiple values

### ISSUE THREAD

**Issue by antonbag** [joomla/joomla-cms#38642]
### Steps to reproduce the issue
1) Create a Content Field of type List with Multiple Values (Multiple option as Yes) called "myfields" (for example).
2) Enter two or more values in "List Values"
3) Create an Article and in the Fields Tab, select multiple fields and save
4) Call with the API to the created ID article {{base_url}}/{{base_path}}/content/articles/**your article id**

### Expected result
A json list with data

### Actual result
"errors": {
        "code": 500,
        "title": "Internal server error",
        "detail": "TypeError: Illegal offset type in

### System information (as much as possible)
Php 8.0
Joomla J4.2

### Additional comments
The problem is in onCustomFieldsBeforePrepareField from list.php.
in the line $field->apivalue = [$field->value => $options[$field->value]];
if $field->value is multiple (an array), it returns error.

**Comment by richard67** [comment]
@antonbag Could you add some information to the title after the workd "with" so we know by the title what the issue is about? Thanks in advance.

**Comment by antonbag** [comment]
Done. Sorry... I forgot it :/
Thank you! :)

**Comment by alikon** [comment]
please test #38655

**Comment by Lakshay-Pruthi** [comment]
@antonbag Can you help me with step 3 and 4?
I have completed till step 2
![image](https://user-images.githubusercontent.com/91469717/190975534-a524d95b-6f92-4eb6-a7f8-1de96092aeb9.png)
Can you brief step 3 and 4?

**Comment by antonbag** [comment]
![image](https://user-images.githubusercontent.com/25433747/190977924-d0bd5038-8236-4527-b269-4faeac59a782.png)

In the Article, select multiple:
![image](https://user-images.githubusercontent.com/25433747/190978130-a9b9e5b9-77af-4148-bdea-50d4cc4189eb.png)

When I get the data from API in Postman, I get nothing (because is an array):
![image](https://user-images.githubusercontent.com/25433747/190979330-ff58cea0-3c39-4a64-8035-d93b13ebcf6c.png)

This is fixed in https://github.com/joomla/joomla-cms/pull/38655

**Comment by Lakshay-Pruthi** [comment]
Completed step 3.
I am little confused about the URL
![image](https://user-images.githubusercontent.com/91469717/191186649-0c57c35a-bf86-4bdf-b10b-11d04b16b090.png)
This is what my article page looks like.
If I'm not wrong Base URL will be "http://localhost/joomla"
Artlice ID is 1
what is the base path?
