### ISSUE TITLE
[4.2.0]Contact administrator component corrupted after migration from 3.10.11

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#38645]
### Steps to reproduce the issue
I've upgraded my joomla 3.10..11 to version 4.2.0. Upgrade completed with no error indication. But when I checked the administrator,  contact component catagories- and contacts-option disapeared - only "Fields-option" and "Field Group" Option are displayed:      
![grafik](https://user-images.githubusercontent.com/69053785/187450636-ca58fcff-2ccf-4cc5-963f-2a6ce24c0a12.png)
really bad as I cannot manage anymore my contacts. 

Any clue what went wrong with this? How can i check or repair?  

### System information (as much as possible)
joomla 4.2.0, mySQL,, 5.7.36, php V 8.1.6  

### Additional comments
checked table  "#__contact_details" - but could not find any problms. Frontend  "contact component" runs fine (no errors) and all pages display correctly. Just updated to 4.2.1 but problem is still there.

**Comment by jschmi102** [comment]
hi,

I've fixed this issue/problem. There was a inconsistancy in table "#__menu". I've checked  3 entries related to com_contact on my  joomla4 system w/o this problem:  (they had the ids. "7", "8", "9" and their parent ids (correctly): "1", "7","7"). 

The system with this problem had ids "107", "108" ,"109" and parent ids "1", "7" ,"7".  This indicated  a **wrong setting** of parent ids! It should be **"1", 107", "107"**. I corrected this and the problem disapeared! 

Sofar I could not find out the causer of  this problem:  the migration process of Joomla or updater of com_contact - maybe someone could clarify?

**Comment by chmst** [comment]
Thank you for this information. I did not see any similiar issue until now. 
To find out what exactly happened would require the installation of the 3.10 backup and inspect the database if there were hidden inconsistencies before the update. Then update again. 
In any case, please save the backup for some time in case we get more issues like yours. 

 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38645">issues.joomla.org/tracker/joomla-cms/38645</a>.</sub>

**Comment by osijekdgo** [comment]
Two of my upgraded sites(3.10.11->4.2.2) doesn't have admin menu Contacts/Contact and Contacts/Categories, one site was repaired with solution in "#__menu" table like it was suggested, but in one site, row 109 in "#__menu" (Contacts/Categories) disappeared. Contacts can be reached if open Global Configuration/Contacts and exit with close, page will be redirected to Contacts list where is again available Add/Delete contacts. So confused... why it happened?

**Comment by Dirk-K** [comment]
well I can't see it is resolved. same issue here. After upgrade from 3.10.11 to 4.2.2 I can't edit the contacts component in backend anymore.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38645">issues.joomla.org/tracker/joomla-cms/38645</a>.</sub>
