### ISSUE TITLE
array_key_exists(): Argument #2 ($array) must be of type array, null given

### ISSUE THREAD

**Issue by hmed95** [joomla/joomla-cms#38641]
### Steps to reproduce the issue
When i edit a menu item and try to save it.

### System information (as much as possible)

php 8 & 8.1
with php 7.4 its ok.

**Comment by ReLater** [comment]
Do you get more informations in the message? Like file and line number?

**Comment by ReLater** [comment]
Which Joomla version ?

**Comment by hmed95** [comment]
Hi, i am on j 4.1.5.
i dont see any file information, just this message.
its only showing with php 8 & 8.1 for me

**Comment by ReLater** [comment]
Could you please check this issue: https://github.com/joomla/joomla-cms/issues/37269

Especially: https://github.com/joomla/joomla-cms/issues/37269#issuecomment-1067274984

**Comment by hmed95** [comment]
Cool got it !

`<html>
<body>
<h1 style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0.5rem; font-weight: 400; line-height: 1.2; color: var(--template-bg-dark); font-size: 1.65rem; font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(237, 242, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">An error has occurred.</h1><blockquote class="blockquote" style="box-sizing: border-box; margin: 0px 0px 1rem; font-size: 1.25rem; color: rgb(73, 80, 87); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(237, 242, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><span class="badge bg-secondary" style="box-sizing: border-box; display: inline-block; padding: 0.3rem 0.2rem; font-size: 0.75rem; font-weight: 700; line-height: 1; color: rgb(255, 255, 255); text-align: center; white-space: nowrap; vertical-align: baseline; border-radius: 0.2rem; --bg-opacity: 1; background-color: rgba(var(--secondary-rgb), var(--bg-opacity))  !important; margin-bottom: 0px;">0</span><span> </span>array_key_exists(): Argument #2 ($array) must be of type array, null given</blockquote><div style="box-sizing: border-box; color: rgb(73, 80, 87); font-family: Roboto, -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, &quot;Helvetica Neue&quot;, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;, &quot;Segoe UI Symbol&quot;, &quot;Noto Color Emoji&quot;; font-size: 16px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(237, 242, 247); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

Call stack
--
# | Function | Location
1 | () | JROOT/plugins/content/pingomatic/pingomatic.php:412
2 | plgContentPingomatic->onContentAfterSave() | JROOT/libraries/src/Plugin/CMSPlugin.php:285
3 | Joomla\CMS\Plugin\CMSPlugin->Joomla\CMS\Plugin\{closure}() | JROOT/libraries/vendor/joomla/event/src/Dispatcher.php:486
4 | Joomla\Event\Dispatcher->dispatch() | JROOT/libraries/src/Application/EventAware.php:111
5 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/administrator/components/com_menus/src/Model/ItemModel.php:1571
6 | Joomla\Component\Menus\Administrator\Model\ItemModel->save() | JROOT/administrator/components/com_menus/src/Controller/ItemController.php:434
7 | Joomla\Component\Menus\Administrator\Controller\ItemController->save() | JROOT/libraries/src/MVC/Controller/BaseController.php:735
8 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:146
9 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:389
10 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:143
11 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:186
12 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:278
13 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:63

</div>
</body>
</html>`

**Comment by chmst** [comment]
Thanks for the information. Please contact the developer of your plugin pingomatic or check if there is a newer version of it, compatible to php 8.1. Closing this as it is not joomla core.
