### ISSUE TITLE
Joomla Administrator Login Issue

### ISSUE THREAD

**Issue by mfaries-pcard** [joomla/joomla-cms#38656]
Dear Joomla Team,

we are facing issue in login Joomla application.
in the login screen we getting message as below:
Deprecated: Function get_magic_quotes_gpc() is deprecated in /home/customer/www/pcard.com.sa/public_html/libraries/cms/application/administrator.php on line 119

Also, attached the error appeared during login![screen shot 2022-08-31 at 14 24 15](https://issues.joomla.org/uploads/1/225e4929fec387b38bb532e7d0cac7ab.jpg)

![screen shot 2022-08-31 at 14 24 15](https://issues.joomla.org/uploads/1/1f9e73d02747e106aa6558670628654e.jpg)

Kindly need your support to resolve the issue.

Regards,
MOHAMED FARIES K A S
+966592461235

**Comment by chmst** [comment]
@mfaries-pcard this is the wrong place for your question. It is about the PHP Version of your application. Please contact your provider or post your question here: https://forum.joomla.org
