### ISSUE TITLE
4.2 Keyboard Shortcuts not clear

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#38659]
### What needs to be fixed
The Keyboard Shortcuts are announced everywhere with J + X - but that means in Shortcut language to press the buttons simultaneos. It should be written J, X or J » Y to make it more obvious that they don't have to be pressed together.

### Why this should be fixed
Already so much questions on Facebook and from Clients that say it does not work because they do whats written and not what is correct.

### How would you fix it
write one of these:
J, X 
J » Y
(tap 1) J  (tap2) X

### Side Effects expected
better understanding of what to do

**Comment by brianteeman** [comment]
github and gmail both use the same type of sequential shortcut key

github just shows the two letter eg J X
gmail uses a then eg J then X

![image](https://user-images.githubusercontent.com/1296369/187861900-96578d72-6891-4cf0-85d3-01a6a38ec38e.png)

![image](https://user-images.githubusercontent.com/1296369/187861948-8a958497-a260-4035-a131-c75b7949fbaa.png)

**Comment by coolcat-creations** [comment]
I like the approach with "then" 
"+" is misleading and not writing anything is not clear enough i think

**Comment by coolcat-creations** [comment]
Should I create a PR with then instead of + or does something speak against it?

**Comment by toivo** [comment]
BTW, in Joomla 4.2.1 shortcuts only upper case letters work, as I found out by trial and error.   That is probably a good thing, as long as it is clearly documented, at least in the Help section of the Keyboard Shortcuts plugin,

**Comment by bembelimen** [comment]
> Should I create a PR with then instead of + or does something speak against it?

Yes, please do so

**Comment by brianteeman** [comment]
> BTW, in Joomla 4.2.1 shortcuts only upper case letters work, as I found out by trial and error. That is probably a good thing, as long as it is clearly documented, at least in the Help section of the Keyboard Shortcuts plugin,

no they work in both upper and lower case

**Comment by toivo** [comment]
True, further test confirms they work.  My first test results from PEBCAK.

**Comment by coolcat-creations** [comment]
I just prepare the PR but the language Change in the administrator/language/en-GB/plg_system_shortcut.ini and administrator/language/en-GB/plg_system_shortcut.sys.ini have no effect on the information in the modal window. Searching through the whole Project I only found a es6 File where the Keyboards are mentioned. Are they hardcoded there? @fancyFranci ?

**Comment by brianteeman** [comment]
@richard67 thats the correct place. So you can either go the github option and remove the + in the js
or create a language string
in the php pass it to the script
and then use it in the script

**Comment by richard67** [comment]
> @richard67 thats the correct place. So you can either go the github option and remove the + in the js or create a language string in the php pass it to the script and then use it in the script

@brianteeman Hmm, as far as I can see, the `'+'` at the place which I've found is used to separate the particular keys. But where does the `+` in the modal display come from?

**Comment by brianteeman** [comment]
Sorry I am getting really confused here (for a change)

> The Keyboard Shortcuts are announced everywhere with J + X 

where? Thats not what I am seeing

![image](https://user-images.githubusercontent.com/1296369/187932111-cda8eb0f-ede5-49e5-b46e-d6556fc8b365.png)

![image](https://user-images.githubusercontent.com/1296369/187932181-2720b408-065e-4f00-8b12-80970707bd57.png)

**Comment by richard67** [comment]
I trusted the desription in the issue. I haven't checked the modal myself because I'm in the office at my regular job. But I'm confused now, too.

**Comment by Fedik** [comment]
On dashboard, scroll down
![image](https://user-images.githubusercontent.com/1568198/187933510-70ff4dbe-e9cb-48b0-96ed-000be1d29c58.png)

**Comment by richard67** [comment]
Ah there it is.

**Comment by Fedik** [comment]
I like the idea about replacing `+` to `then`, also would do it in modal popup

**Comment by brianteeman** [comment]
@fedik that string is a 30 second change
https://github.com/joomla/joomla-cms/blob/c9331a81d44ebfca876eb4393fdffde31bdc5fa6/administrator/language/en-GB/plg_system_shortcut.ini#L8

**Comment by coolcat-creations** [comment]
> @coolcat-creations On a quick search I found a hard-coded usage of `'+' ` as separator for keys: https://github.com/joomla/joomla-cms/blob/4.2-dev/build/media_source/plg_system_shortcut/js/shortcut.es6.js#L106
> 
> I know, that was not what you are looking for. But I thought I should mention it because you might have to change that, too.

thats what I meant in my previous post

**Comment by coolcat-creations** [comment]
> @Fedik that string is a 30 second change
> 
> https://github.com/joomla/joomla-cms/blob/c9331a81d44ebfca876eb4393fdffde31bdc5fa6/administrator/language/en-GB/plg_system_shortcut.ini#L8

But the PLG_SYSTEM_SHORTCUT_XML_DESCRIPTION does not have any effect on the modal

**Comment by brianteeman** [comment]
the modal doesnt have the + you were complaining about in your first post

**Comment by coolcat-creations** [comment]
Yes, it does not have the then as well, I wanted to change it there too.

**Comment by Fedik** [comment]
Closing, because we have a PR #38667
Please test
