### ISSUE TITLE
SMTP Mail on PHP8 has a type error

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#38652]
### Steps to reproduce the issue
Set up Office 365 SMTP.
Use PHP8
Use Joomla 4

### Expected result
Sends SMTP email

### Actual result
Type errors

SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    onSuccess https://wwwSyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data
    onSuccess https://www.********.co.uk/media/system/js/fields/joomla-field-send-test-mail.js?e91fbd76a9dcdcda2f24c2c7cb637038444a5d23:59
    onreadystatechange https://www.**************.co.uk/media/system/js/core.js?17121a112ecec3d656efe5c5f493429c9acf2179:712
joomla-field-send-test-mail.js:62:21
    onSuccess https://www.*********.co.uk/media/system/js/fields/joomla-field-send-test-mail.js?e91fbd76a9dcdcda2f24c2c7cb637038444a5d23:62
    onreadystatechange https://www.************.co.uk/media/system/js/core.js?17121a112ecec3d656efe5c5f493429c9acf2179:712

Uncaught TypeError: response is undefined
    onSuccess https://www.*************.co.uk/media/system/js/fields/joomla-field-send-test-mail.js?e91fbd76a9dcdcda2f24c2c7cb637038444a5d23:65
    onreadystatechange https://www.*************.co.uk/media/system/js/core.js?17121a112ecec3d656efe5c5f493429c9acf2179:712
    request https://www.************.co.uk/media/system/js/core.js?17121a112ecec3d656efe5c5f493429c9acf2179:703
    sendTestMail https://www.**************.co.uk/media/system/js/fields/joomla-field-send-test-mail.js?e91fbd76a9dcdcda2f24c2c7cb637038444a5d23:47
    connectedCallback https://www.************.co.uk/media/system/js/fields/joomla-field-send-test-mail.js?e91fbd76a9dcdcda2f24c2c7cb637038444a5d23:22
jooml
co.uk/media/system/js/fields/joomla-field-send-test-mail.js?e91fbd76a9dcdcda2f24c2c7cb637038444a5d23:59
    onreadystatechange https://www.************.co.uk/media/system/js/core.js?17121a112ecec3d656efe5c5f493429c9acf2179:712
joomla-field-send-test-mail.js:62:21
    onSuccess https://www.*************.co.uk/media/system/js/fields/joomla-field-send-test-mail.js?e91fbd76a9dcdcda2f24c2c7cb637038444a5d23:62
    onreadystatechange https://www.*************.co.uk/media/system/js/core.js?17121a112ecec3d656efe5c5f493429c9acf2179:712

Uncaught TypeError: response is undefined
    onSuccess https://www.**************.co.uk/media/system/js/fields/joomla-field-send-test-mail.js?e91fbd76a9dcdcda2f24c2c7cb637038444a5d23:65
    onreadystatechange https://www.***********.co.uk/media/system/js/core.js?17121a112ecec3d656efe5c5f493429c9acf2179:712
    request https://www.*************.co.uk/media/system/js/core.js?17121a112ecec3d656efe5c5f493429c9acf2179:703
    sendTestMail https://www.************.co.uk/media/system/js/fields/joomla-field-send-test-mail.js?e91fbd76a9dcdcda2f24c2c7cb637038444a5d23:47
    connectedCallback https://www.************.co.uk/media/system/js/fields/joomla-field-send-test-mail.js?e91fbd76a9dcdcda2f24c2c7cb637038444a5d23:22
jooml

### System information (as much as possible)
[systeminfo-2022-08-31T11_17_46+01_00.txt](https://issues.joomla.org/uploads/1/a02d6236a71863c961fadfc102ed133a.txt)

### Additional comments
This information was provided to me by my host.  My apologies if this has already been reported or is a false report, I couldn't find it.

Host changed me to PHP7.1 and things are fine.

**Comment by Fedik** [comment]
> Sends SMTP email

You meant, "send test mail" button in backend?

By looking your error info: the error probably come from PHP deprecation notice, that breaks JSON response.

> Host changed me to PHP7.1 and things are fine.

You still can use php 8, just change error_reporting to minimum, or set it off, or exclude deprecation (in server config)
Looking your config, you have error_reporting = maximum.

**Comment by Fedik** [comment]
@uglyeoin Can you please test it on latest joomla 4.2.1?
I checked, and do not have this error on 4.2.1

**Comment by uglyeoin** [comment]
[systeminfo-2022-08-31T15_06_23+01_00.txt](https://github.com/joomla/joomla-cms/files/9462155/systeminfo-2022-08-31T15_06_23%2B01_00.txt)
Not sure if this helps

**Comment by uglyeoin** [comment]
The error is the same as previous but the host gave me further information.  I just want to know how to get that information myself.

**Comment by uglyeoin** [comment]
> Is this still an open issue for you @uglyeoin

I'll have to check and come back to you.  It won't be today @brianteeman

**Comment by Quy** [comment]
Closing for now. If you can reproduce it, this can be reopened. Thanks.
