### ISSUE TITLE
[J4.2] System - WebAuthn Passwordless Login significantly slows page loading

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#38660]
### Steps to reproduce the issue
Hi, not sure if this happens only on my test servers (PHP 8.1), but when System - WebAuthn Passwordless Login plugin is enabled, it significantly slows page loading in administration (e.g. in plugin list)

FROM:
225ms (execution time)
![img](https://i.imgur.com/vIqK8XU.png)
TO:
5 264ms (execution time)
![img](https://i.imgur.com/XFWkYTR.png)

That's 23 times longer and work in the administration then becomes very unpleasant

### Expected result
Not so much of a slowdown

### Actual result
Significant slowdown

### System information (as much as possible)
Joomla 4.2.1
PHP 8.1
10.4.24-MariaDB

Is anyone getting similar problems?

Thank you, Jan

**Comment by weeblr** [comment]
@brianteeman @PhocaCz Please see the issue I just opened with more details: https://github.com/joomla/joomla-cms/issues/38662

**Comment by PhocaCz** [comment]
Hi, thank you for the info, closing it here due to other topics.
https://github.com/joomla/joomla-cms/issues/38662
https://github.com/joomla/joomla-cms/issues/38654
