### ISSUE TITLE
Slow sites after update to 4.2.1!

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#38668]
### Steps to reproduce the issue
Update 4.2.0 site to 4.2.1

### Expected result
Same or better page load speed as before

### Actual result
Very slow page load (4 seconds)

### System information (as much as possible)
Joomla 4.2.1
PHP Version 	8.0.20
Web Server 	LiteSpeed 
Database Version: 5.7.39-42 

### Additional comments
I have 3.10.11 and 4.2.0 sites on same server that now run faster as all my 4.2.1 sites on the same server - this is very bad !

**Comment by conseilgouz** [comment]
same issue than #38665

pr in progress

**Comment by conseilgouz** [comment]
issue #38662 gives you a way to make everything straight : disable webauthen plugin

**Comment by rbuelund** [comment]
Also helped here to disable WebAuth plugin

**Comment by alikon** [comment]
thanks for reporting
a fix has been already worked out 
please follow here #38664
