### ISSUE TITLE
Breadcrumbs behaving very oddly

### ISSUE THREAD

**Issue by pschmehl** [joomla/joomla-cms#38674]
### Steps to reproduce the issue
Go to a menu item that is an article. Select an article listed on that article page. Then look at the breadcrumbs and select a backlink.

### Expected result
Selecting a backlink should take you to that link.

### Actual result
Clicking on a backlink takes you to a display of random code and several pages all displayed together.

### System information (as much as possible)
This is a test instance of an upgrade from 3.10.11 to 4.1.5, then upgraded to 4.2.1. If you want SuperUser access to investigate, I will grant it.

[quote="Forum Post Assistant (v1.6.5) : 2-Sep-2022"][quote="Basic Environment ::"][size=85][b]Joomla! Instance :: [/b][color=Blue]Joomla! [b]4.2.1[/b]-Stable (Uaminifu) 30-August-2022[/color]
[b]Joomla! Configured :: [/b][color=Green]Yes[/color] | Read-Only ([color=Green]444[/color]) | 
[b]Configuration Options :: Offline:[/b] false | [b]SEF:[/b] true | [b]SEF Suffix:[/b] false | [b]SEF ReWrite:[/b] false | [b].htaccess/web.config:[/b] [color=orange]No[/color] | [b]GZip:[/b] true | [b]Cache:[/b] true | [b]CacheTime:[/b] 15 | [b]CacheHandler:[/b] file | [b]CachePlatformPrefix:[/b] false | [b]FTP Layer:[/b] false | [b]Proxy:[/b] false | [b]LiveSite:[/b]  | [b]Session lifetime:[/b] 240 | [b]Session handler:[/b] database | [b]Shared sessions:[/b] false | [b]SSL:[/b] 2 | [b]Error Reporting:[/b] default | [b]Site Debug:[/b] false | [b]Language Debug:[/b] false | [b]Default Access:[/b] Public | [b]Unicode Slugs:[/b] false | [b]dbConnection Type:[/b] mysqli | [b]PHP Supports J! 4.2.1: [/b][color=Green]Yes[/color] | [b]Database Supports J! 4.2.1: [/b][color=Green]Yes[/color] | [b]Database Credentials Present:[/b] [color=Green]Yes[/color] | 

[b]Host Configuration :: OS:[/b] Linux |  [b]OS Version:[/b] 3.10.0-962.3.2.lve1.5.65.el7.x86_64 | [b]Technology:[/b] x86_64 | [b]Web Server:[/b] LiteSpeed | [b]Encoding:[/b] gzip, deflate, br |  [b]System TMP Writable:[/b] [color=Green]Yes[/color] | [b]  Free Disk Space :[/b] 889.99 GiB |

[b]PHP Configuration :: Version:[/b] [b]8.0.22[/b] | [b]PHP API:[/b] [b]litespeed[/b] | [b]Session Path Writable:[/b] [color=Green]Yes[/color] | [b]Display Errors:[/b] 0 | [b]Error Reporting:[/b] 22527 | [b]Log Errors To:[/b] error_log | [b]Last Known Error:[/b] 28th August 2022 20:07:30. | [b]Register Globals:[/b]  | [b]Magic Quotes:[/b]  | [b]Safe Mode:[/b]  | [b]Allow url fopen:[/b] 1 | [b]Open Base:[/b]  | [b]Uploads:[/b] 1 | [b]Max. Upload Size:[/b] 128M | [b]Max. POST Size:[/b] 128M | [b]Max. Input Time:[/b] 600 | [b]Max. Execution Time:[/b] 300 | [b]Memory Limit:[/b] 512M

[b]Database Configuration :: [/b] [b]Version:[/b] [b]10.3.35-MariaDB-cll-lve[/b] (Client:10.3.35) | [b]Database Size:[/b] 22.05 MiB | [b]#of Tables with config prefix: [/b] 124 | [b]#of other Tables: [/b] 0 | [b]User Privileges : [/b]GRANT ALL[/size][/quote][quote="Detailed Environment ::"][size=85][b]PHP Extensions :: [/b]Core (8.0.22) | date (8.0.22) | [color=Green][b]libxml[/b][/color] (8.0.22) | [color=Green][b]openssl[/b][/color] (8.0.22) | pcre (8.0.22) | sqlite3 (8.0.22) | [color=Green][b]zlib[/b][/color] (8.0.22) | bz2 (8.0.22) | calendar (8.0.22) | ctype (8.0.22) | [color=Green][b]curl[/b][/color] (8.0.22) | hash (8.0.22) | filter (8.0.22) | ftp (8.0.22) | gettext (8.0.22) | gmp (8.0.22) | SPL (8.0.22) | [color=Green][b]iconv[/b][/color] (8.0.22) | json (8.0.22) | pcntl (8.0.22) | readline (8.0.22) | Reflection (8.0.22) | session (8.0.22) | standard (8.0.22) | shmop (8.0.22) | SimpleXML (8.0.22) | [color=Green][b]mbstring[/b][/color] (8.0.22) | tokenizer (8.0.22) | [color=Green][b]xml[/b][/color] (8.0.22) | litespeed () | i360 (6.4.3) | bcmath (8.0.22) | dom (20031129) | enchant (8.0.22) | fileinfo (8.0.22) | gd (8.0.22) | imap (8.0.22) | intl (8.0.22) | ldap (8.0.22) | exif (8.0.22) | [color=Green][b]mysqli[/b][/color] (8.0.22) | mysqlnd (mysqlnd 8.0.22) | PDO (8.0.22) | [color=Green][b]pdo_mysql[/b][/color] (8.0.22) | pdo_pgsql (8.0.22) | pdo_sqlite (8.0.22) | pgsql (8.0.22) | Phar (8.0.22) | posix (8.0.22) | pspell (8.0.22) | snmp (8.0.22) | soap (8.0.22) | sockets (8.0.22) | tidy (8.0.22) | xmlreader (8.0.22) | xmlwriter (8.0.22) | xsl (8.0.22) | [color=Green][b]zip[/b][/color] (1.19.5) | Zend Engine (4.0.22) | 
[b]Potential Missing Extensions :: [/b]

[b]Switch User Environment :: PHP CGI:[/b] No | [b]Server SU:[/b] No |  [b]PHP SU:[/b] No |  [b]Potential Ownership Issues:[/b] [color=Green]No[/color] [/size][/quote][quote="Folder Permissions ::"][size=85][b]Core Folders :: [/b]images/ (755) | components/ (755) | modules/ (755) | plugins/ (755) | language/ (755) | templates/ (755) | cache/ (755) | logs/ (---) | tmp/ (755) | administrator/components/ (755) | administrator/modules/ (755) | administrator/language/ (755) | administrator/templates/ (755) | administrator/logs/ (755) | 

[b]Elevated Permissions[/b] [i](First 10)[/i][b] :: [/b]images/dms/documents/ ([color=Red]777[/color]) | [/size][/quote][quote="Database Information ::"][size=85][b]Database statistics :: [/b][b]Uptime:[/b] 1229222 | [b]Threads:[/b] 134 | [b]Questions:[/b] 1419277926 | [b]Slow queries:[/b] 191 | [b]Opens:[/b] 44394604 | [b]Flush tables:[/b] 43 | [b]Open tables:[/b] 2000 | [b]Queries per second avg:[/b] 1154.614 | [/size][/quote][quote="Extensions Discovered ::"][size=85][b]Components :: Site :: [/b]
[b] Core :: [/b][color=Blue][/color]
[b]3rd Party:: [/b][color=Brown]WF_AGGREGATOR_AUDIO_TITLE (2.9.29)  ? | WF_AGGREGATOR_VIMEO_TITLE (2.9.29)  ? | WF_AGGREGATOR_VIDEO_TITLE (2.9.29)  ? | WF_AGGREGATOR_DAILYMOTION_TITLE (2.9.29)  ? | WF_AGGREGATOR_YOUTUBE_TITLE (2.9.29)  ? | WF_POPUPS_JCEMEDIABOX_TITLE (2.9.29)  ? | WF_LINKS_JOOMLALINKS_TITLE (2.9.29)  ? | WF_FILESYSTEM_JOOMLA_TITLE (2.9.29)  ? | WF_LINK_SEARCH_TITLE (2.9.29)  ? | WF_TEXTCASE_TITLE (2.9.29)  ? | WF_KITCHENSINK_TITLE (2.9.29)  ? | WF_SEARCHREPLACE_TITLE (2.9.29)  ? | WF_CONTEXTMENU_TITLE (2.9.29)  ? | WF_NONBREAKING_TITLE (2.9.29)  ? | WF_EMOTIONS_TITLE (2.9.29)  ? | WF_FONTCOLOR_TITLE (2.9.29)  ? | WF_ANCHOR_TITLE (2.9.29)  ? | WF_STYLE_TITLE (2.9.29)  ? | JCE - Noneditable (1.0.0)  ? | WF_HR_TITLE (2.9.29)  ? | WF_MEDIA_TITLE (2.9.29)  ? | WF_XHTMLXTRAS_TITLE (2.9.29)  ? | WF_LINK_TITLE (2.9.29)  ? | WF_CLEANUP_TITLE (2.9.29)  ? | WF_STYLESELECT_TITLE (2.9.29)  ? | WF_FORMATSELECT_TITLE (2.9.29)  ? | WF_IMGMANAGER_TITLE (2.9.29)  ? | WF_CHARMAP_TITLE (2.9.29)  ? | WF_DIRECTIONALITY_TITLE (2.9.29)  ? | WF_BROWSER_TITLE (2.9.29)  ? | WF_PREVIEW_TITLE (2.9.29)  ? | WF_FULLSCREEN_TITLE (2.9.29)  ? | WF_ARTICLE_TITLE (2.9.29)  ? | WF_CLIPBOARD_TITLE (2.9.29)  ? | WF_TABLE_TITLE (2.9.29)  ? | WF_VISUALBLOCKS_TITLE (2.9.29)  ? | WF_WORDCOUNT_TITLE (2.9.29)  ? | WF_SPELLCHECKER_TITLE (2.9.29)  ? | WF_AUTOSAVE_TITLE (2.9.29)  ? | WF_LISTS_TITLE (2.9.29)  ? | WF_FONTSIZESELECT_TITLE (2.9.29)  ? | WF_FONTSELECT_TITLE (2.9.29)  ? | WF_VISUALCHARS_TITLE (2.9.29)  ? | WF_SOURCE_TITLE (2.9.29)  ? | WF_HELP_TITLE (2.9.29)  ? | WF_PRINT_TITLE (2.9.29)  ? | os_paypal (4.0.3)  ? | os_eway (4.0.3)  ? | os_authnet (4.0.3)  ? | os_offline (4.0.3)  ? | [/color]

[b]Components :: Admin :: [/b]
[b] Core :: [/b][color=Blue]com_plugins (4.0.0)  1 | com_banners (4.0.0)  1 | com_contenthistory (4.0.0)  1 | com_admin (4.0.0)  1 | com_redirect (4.0.0)  1 | com_workflow (4.0.0)  1 | com_wrapper (4.0.0)  1 | com_media (3.0.0)  1 | com_actionlogs (3.9.0)  1 | com_config (4.0.0)  1 | com_finder (4.0.0)  1 | com_mails (4.0.0)  1 | com_cpanel (4.0.0)  1 | com_fields (4.0.0)  1 | com_tags (4.0.0)  1 | com_menus (4.0.0)  1 | com_privacy (3.9.0)  1 | com_postinstall (4.0.0)  1 | com_languages (4.0.0)  1 | com_modules (4.0.0)  1 | com_joomlaupdate (4.0.3)  1 | com_cache (4.0.0)  1 | com_content (4.0.0)  1 | com_installer (4.0.0)  1 | com_checkin (4.0.0)  1 | com_scheduler (4.1.0)  1 | com_categories (4.0.0)  1 | com_login (4.0.0)  1 | com_newsfeeds (4.0.0)  1 | com_associations (4.0.0)  1 | com_users (4.0.0)  1 | com_messages (4.0.0)  1 | com_templates (4.0.0)  1 | com_ajax (4.0.0)  1 | [/color]
[b]3rd Party:: [/b][color=Brown]COM_JCE (2.9.29)  1 | com_admintools (7.1.10)  1 | com_easyfolderlistingpro (4.1.1)  1 | Slideshow CK (2.3.13)  1 | com_slideshowck (2.3.13)  1 | GSD (1.0)  1 | com_akeebabackup (9.3.0)  1 | DMS (5.4.3)  1 | [/color]

[b]Modules :: Site :: [/b]
[b] Core :: [/b][color=Blue]mod_articles_popular (3.0.0)  1 | mod_banners (3.0.0)  1 | mod_breadcrumbs (3.0.0)  1 | mod_finder (3.0.0)  1 | mod_stats (3.0.0)  1 | mod_footer (3.0.0)  1 | mod_feed (3.0.0)  1 | mod_login (3.0.0)  1 | mod_articles_news (3.0.0)  1 | mod_custom (3.0.0)  1 | mod_tags_popular (3.1.0)  1 | mod_languages (3.5.0)  1 | mod_articles_latest (3.0.0)  1 | mod_tags_similar (3.1.0)  1 | mod_menu (3.0.0)  1 | mod_random_image (3.0.0)  1 | mod_articles_categories (3.0.0)  1 | mod_users_latest (3.0.0)  1 | mod_whosonline (3.0.0)  1 | mod_related_items (3.0.0)  1 | mod_articles_category (3.0.0)  1 | mod_syndicate (3.0.0)  1 | mod_articles_archive (3.0.0)  1 | mod_wrapper (3.0.0)  1 | [/color]
[b]3rd Party:: [/b][color=Brown]MOD_EASYFILEUPLOADER (2.9.2)  1 | Slideshow CK (2.3.13)  1 | Tags modules for Documents Seller (5.4.3)  1 | MOD_EASYFOLDERLISTINGPRO (2.1)  1 | DMS Cart (5.4.3)  1 | JJ Social Slider (4.1.0PRO)  1 | DMS Categories (5.4.3)  1 | DMS documents (5.4.3)  1 | [/color]

[b]Modules :: Admin :: [/b]
[b] Core :: [/b][color=Blue]mod_multilangstatus (3.0.0)  1 | mod_latestactions (3.9.0)  1 | mod_latest (3.0.0)  1 | mod_messages (4.0.0)  1 | mod_feed (3.0.0)  1 | mod_quickicon (3.0.0)  1 | mod_login (3.0.0)  1 | mod_custom (3.0.0)  1 | mod_privacy_dashboard (3.9.0)  1 | mod_privacy_status (4.0.0)  1 | mod_menu (3.0.0)  1 | mod_post_installation_messages (4.0.0)  1 | mod_user (4.0.0)  1 | mod_logged (3.0.0)  1 | mod_stats_admin (3.0.0)  1 | mod_submenu (3.0.0)  1 | mod_toolbar (3.0.0)  1 | mod_title (3.0.0)  1 | mod_frontend (4.0.0)  1 | mod_popular (3.0.0)  1 | mod_sampledata (3.8.0)  1 | mod_version (3.0.0)  1 | mod_loginsupport (4.0.0)  1 | [/color]
[b]3rd Party:: [/b][color=Brown][/color]

[b]Libraries :: [/b]
[b] Core :: [/b][color=Blue][/color]
[b]3rd Party:: [/b][color=Brown]Helvetica (-)  ? | Free Mono (-)  ? | file_fof40 (4.1.1)  ? | [/color]

[b]Plugins :: [/b]
[b] Core :: [/b][color=Blue]plg_multifactorauth_fixed (4.2.0)  0 | plg_multifactorauth_webauthn (4.2.0)  1 | plg_multifactorauth_email (4.2.0)  1 | plg_multifactorauth_yubikey (3.2.0)  1 | plg_multifactorauth_totp (3.2.0)  1 | plg_captcha_recaptcha_invisible (3.8)  0 | plg_captcha_recaptcha (3.4.0)  1 | plg_media-action_rotate (4.0.0)  1 | plg_media-action_resize (4.0.0)  1 | plg_media-action_crop (4.0.0)  1 | plg_privacy_content (3.9.0)  1 | plg_privacy_message (3.9.0)  1 | plg_privacy_consents (3.9.0)  1 | plg_privacy_actionlogs (3.9.0)  1 | plg_privacy_user (3.9.0)  1 | plg_content_vote (3.0.0)  1 | plg_content_confirmconsent (3.9.0)  0 | plg_content_pagebreak (3.0.0)  1 | plg_content_pagenavigation (3.0.0)  1 | plg_content_joomla (3.0.0)  1 | plg_content_loadmodule (3.0.0)  1 | plg_content_emailcloak (3.0.0)  0 | plg_content_fields (3.7.0)  1 | plg_content_finder (3.0.0)  1 | plg_authentication_cookie (3.0.0)  1 | plg_authentication_joomla (3.0.0)  1 | plg_authentication_ldap (3.0.0)  0 | plg_installer_webinstaller (4.0.0)  1 | plg_installer_packageinstaller (3.6.0)  1 | plg_installer_override (4.0.0)  1 | plg_installer_urlinstaller (3.6.0)  1 | plg_installer_folderinstaller (3.6.0)  1 | plg_workflow_featuring (4.0.0)  1 | plg_workflow_publishing (4.0.0)  1 | plg_workflow_notification (4.0.0)  1 | plg_task_check_files (4.1)  1 | plg_task_demo_tasks (4.1)  1 | plg_task_requests (4.1)  1 | plg_task_site_status (4.1)  1 | plg_quickicon_joomlaupdate (3.0.0)  1 | plg_quickicon_downloadkey (4.0.0)  1 | plg_quickicon_privacycheck (3.9.0)  1 | plg_quickicon_phpversioncheck (3.7.0)  1 | plg_quickicon_overridecheck (4.0.0)  1 | plg_quickicon_extensionupdate (3.0.0)  1 | plg_behaviour_taggable (4.0.0)  1 | plg_behaviour_versionable (4.0.0)  1 | plg_actionlog_joomla (3.9.0)  1 | plg_editors-xtd_pagebreak (3.0.0)  1 | plg_editors-xtd_image (3.0.0)  1 | plg_editors-xtd_module (3.5.0)  1 | plg_editors-xtd_article (3.0.0)  1 | plg_editors-xtd_fields (3.7.0)  1 | plg_editors-xtd_readmore (3.0.0)  1 | plg_editors-xtd_menu (3.7.0)  1 | plg_sampledata_multilang (4.0.0)  1 | plg_webservices_plugins (4.0.0)  1 | plg_webservices_privacy (4.0.0)  1 | plg_webservices_languages (4.0.0)  1 | plg_webservices_content (4.0.0)  1 | plg_webservices_redirect (4.0.0)  1 | plg_webservices_menus (4.0.0)  1 | plg_webservices_installer (4.0.0)  1 | plg_webservices_messages (4.0.0)  1 | plg_webservices_media (4.1.0)  1 | plg_webservices_users (4.0.0)  1 | plg_webservices_tags (4.0.0)  1 | plg_webservices_modules (4.0.0)  1 | plg_webservices_config (4.0.0)  1 | plg_webservices_banners (4.0.0)  1 | plg_webservices_templates (4.0.0)  1 | plg_webservices_newsfeeds (4.0.0)  1 | plg_filesystem_local (4.0.0)  1 | plg_fields_integer (3.7.0)  1 | plg_fields_list (3.7.0)  1 | plg_fields_text (3.7.0)  1 | plg_fields_subform (4.0.0)  1 | plg_fields_usergrouplist (3.7.0)  1 | plg_fields_calendar (3.7.0)  1 | plg_fields_color (3.7.0)  1 | plg_fields_media (3.7.0)  1 | plg_fields_checkboxes (3.7.0)  1 | plg_fields_sql (3.7.0)  1 | plg_fields_url (3.7.0)  1 | plg_fields_textarea (3.7.0)  1 | plg_fields_radio (3.7.0)  1 | plg_fields_user (3.7.0)  1 | plg_fields_imagelist (3.7.0)  1 | plg_fields_editor (3.7.0)  1 | plg_finder_content (3.0.0)  1 | plg_finder_contacts (3.0.0)  1 | plg_finder_tags (3.0.0)  1 | plg_finder_newsfeeds (3.0.0)  1 | plg_finder_categories (3.0.0)  1 | plg_api-authentication_basic (4.0.0)  1 | plg_api-authentication_token (4.0.0)  1 | plg_system_cache (3.0.0)  1 | plg_system_updatenotification (3.5.0)  1 | plg_system_redirect (3.0.0)  1 | plg_system_shortcut (4.2.0)  1 | plg_system_webauthn (4.0.0)  1 | plg_system_sef (3.0.0)  1 | plg_system_sessiongc (3.8.6)  1 | plg_system_httpheaders (4.0.0)  1 | plg_system_actionlogs (3.9.0)  0 | plg_system_accessibility (4.0.0)  0 | plg_system_jooa11y (4.2.0)  1 | plg_system_privacyconsent (3.9.0)  0 | plg_system_debug (3.0.0)  1 | plg_system_schedulerunner (4.1)  1 | plg_system_highlight (3.0.0)  1 | plg_system_fields (3.7.0)  1 | plg_system_logout (3.0.0)  1 | plg_system_skipto (4.0.0)  1 | plg_system_languagefilter (3.0.0)  0 | plg_system_languagecode (3.0.0)  0 | plg_system_stats (3.5.0)  1 | plg_system_logrotation (3.9.0)  1 | plg_system_task_notification (4.1)  1 | plg_system_remember (3.0.0)  1 | plg_system_log (3.0.0)  1 | plg_extension_namespacemap (4.0.0)  1 | plg_extension_joomla (3.0.0)  1 | plg_extension_finder (4.0.0)  1 | plg_user_contactcreator (3.0.0)  0 | plg_user_joomla (3.0.0)  1 | plg_user_profile (3.0.0)  1 | plg_user_terms (3.9.0)  0 | plg_user_token (3.9.0)  1 | [/color]
[b]3rd Party:: [/b][color=Brown]Documents Seller - System (DO NOT U (5.4.3)  ? | Documents Seller - MPDF (2.22.3)  0 | plg_content_jce (2.9.29)  1 | PLG_CONTENT_EASYFOLDERLISTINGPRO (2.0)  1 | Content - DMS Category (5.4.3)  1 | Installer - Documents Seller (5.4.3)  1 | plg_installer_jce (2.9.29)  1 | PLG_GSD_CONTENT (1.0)  1 | plg_quickicon_jce (2.9.29)  1 | PLG_QUICKICON_AKEEBABACKUP (9.3.0)  1 | PLG_ACTIONLOG_ADMINTOOLS (7.1.10)  0 | PLG_EDITORS-XTD_EASYFOLDERLISTINGPR (2.0)  ? | plg_editors_codemirror (5.65.6)  1 | plg_editors_jce (2.9.29)  1 | plg_editors_tinymce (5.10.5)  1 | PLG_SOCIALLOGIN_GOOGLE (4.0.3)  0 | PLG_SOCIALLOGIN_LINKEDIN (4.0.3)  0 | PLG_SOCIALLOGIN_APPLE (4.0.3)  0 | PLG_SOCIALLOGIN_MICROSOFT (4.0.3)  0 | PLG_SOCIALLOGIN_TWITTER (4.0.3)  0 | PLG_SOCIALLOGIN_GITHUB (4.0.3)  0 | PLG_SOCIALLOGIN_FACEBOOK (4.0.3)  1 | plg_fields_mediajce (2.9.29)  1 | Search - Documents Seller (5.4.3)  1 | Hikashop - VirtueMart Fallback Redi (4.6.1)  ? | VM Framework Loader during Plugin U (1.0)  ? | plg_system_jce (2.9.29)  1 | mySites.guru Secure Plugin (n/a)  ? | Hikashop - Mijoshop Fallback Redire (4.6.1)  ? | plg_system_gsd (5.1.3)  1 | PLG_SYSTEM_SOCIALLOGIN (4.0.3)  1 | PLG_SYSTEM_ADMINTOOLS (7.1.10)  1 | plg_system_nrframework (4.9.52)  1 | Hikashop - Redshop Fallback Redirec (4.6.1)  ? | plg_extension_jce (2.9.29)  1 | [/color][/size][/quote][quote="Templates Discovered ::"][size=85][b]Templates :: Site :: [/b][color=Blue][b][u]cassiopeia (1.0)[/u][/b][/color]  1 | 
[b]Templates :: Admin :: [/b][color=Blue][b][u]atum (1.0)[/u][/b][/color]  1 | [/size][/quote][/quote]

### Additional comments

See this post in Joomla Forum for a full explanation with screenshots.
https://forum.joomla.org/viewtopic.php?f=808&t=996209

When I backed off php to version 7.4.30 the problem changed. When I click on Myths and Lles, the breadcrumb says I'm on Home. All the rest of the menu appears to work as expected. The only top-level menu items that are actual articles are Home and Myths and Lies. All the other menu times are placeholders for dropdown menus. So, the problem appears to be related to a manu item that is an article that links to other articles.

**Comment by pschmehl** [comment]
Following up. I granted SuperUser access to an extension developer so he could investigate an issue. He was apparently on the site working because his extension was producing errors during the same time that these menu issues appeared. Now the behavior has changed. When I click on the Myths and Lie link, the breadcrumb shows that I'm there. But, when I click on an article linked INSIDE the breadcrumb article, the breadcrumb shows that I am at Home. So, it appears that breadcrumbs only understand menu links and not articles linked with a menu item that is an article.

Still, it seems that appropriate behavior should be that the breadcrumb points to the article linked inside the menu article. Failing that, it should at least point to the menu article and not home.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38674">issues.joomla.org/tracker/joomla-cms/38674</a>.</sub>

**Comment by pschmehl** [comment]
I rescind my previous comment. The behavior returns as soon as I change php to version 8.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38674">issues.joomla.org/tracker/joomla-cms/38674</a>.</sub>

**Comment by ReLater** [comment]
> This is a test instance of an upgrade from 3.10.11 to 4.1.5

Are you using a mod_breadcrumb override coming from Joomla 3 in your Joomla 4? If yes, remove it.

I saw your issue several times after migrations. It was always an override.

**Comment by pschmehl** [comment]
Forgive me. I'm not a developer. How would I find the mod_breadcrumb override? When I look in modules, i have one breadcrumb module. I don't see anything about overrides.

**Comment by ReLater** [comment]
Which template do you use in frontend?

**Comment by pschmehl** [comment]
Cassiopeia

**Comment by ReLater** [comment]
Then forget my comments, please. Pure cassiopeia has no overrides for mod_breadcrumbs.

**Comment by pschmehl** [comment]
So, is this a real bug then? The only place that it shows up is in the Myths and Lies dropdowns. The rest of the menus behave as expected, but the Myths and Lies menu item is a Single Article. That article contains links to 38 other articles. If you click on one of those articles, the breadcrumb goes crazy.

**Comment by Webdongle** [comment]
> ### Steps to reproduce the issue
> 
> Go to a menu item that is an article. Select an article listed on that article page. Then look at the breadcrumbs and select a backlink.

Article menu items do open an Article that has a list unless the Article has a module or a manually created list inserted into it.
Breadcrumbs does not have a 'back link'.

Please specify exactly how to reproduce it on fresh Joomla install (or a migration from a fresh J3 install).

**Comment by pschmehl** [comment]
Create an Article with several links to other articles on the site. Make that article a Singe Article Menu Item. Click on that menu link. Click on an article linked within that article. Then look at breadcrumbs. You will see unrelated menu items in the breadcrumb path. Click on those unrelated items in the breadcrumb. Or on the breadcrumb link to the article that is a menu item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38674">issues.joomla.org/tracker/joomla-cms/38674</a>.</sub>

**Comment by Webdongle** [comment]
I had a quick look at the OP's site.  He has top level Menu items of type 'URL' and defining the url as '#'. This is creating an error in the paths Breadcrumbs is trying to create.

Methinks this can be closed now.

**Comment by Hackwar** [comment]
I agree with @Webdongle. Closing.
