### ISSUE TITLE
Toggle Inline Help doesn´t work in subform field

### ISSUE THREAD

**Issue by antonbag** [joomla/joomla-cms#38677]
### Steps to reproduce the issue

Insert a subform in an xml plugin or module:

			<field
				name="subformfield-name"
				type="subform"
				label="Subform Field"
				description="Subform Field Description does toggle"
				multiple="true"
				min="1"
				max="10"
				>
				<form>
					<field
						name="example_text"
						type="text"
						label="Example Text"
						description="Desc  does not toggle"
						/>
					<field
						name="example_textarea"
						type="textarea"
						label="Example Textarea"
						cols="40"
						rows="8"
						description="Desc does not toggle"
						/>
				</form>
			</field>

### Expected result
The Toggle Inline Help button hides and displays the description in subform fields.

### Actual result
The Toggle Inline Help button doesn't work in the subform fields

### System information (as much as possible)
Joomla 4.2.1
Php 8.1

**Comment by conseilgouz** [comment]
Hi,

To make inline help button work in subforms, after your form line, add  

`	<config>         
		<inlinehelp button="show"/>     
	</config>
`
In your case, it will become : 
`<field
			name="subformfield-name"
			type="subform"
			label="Subform Field"
			description="Subform Field Description does toggle"
			multiple="true"
			min="1"
			max="10"
			>
			<form>
	                      <config>         
		                     <inlinehelp button="show"/>     
 	                      </config>
				<field
					name="example_text"
					type="text"
					label="Example Text"
					description="Desc  does not toggle"
					/>
				<field
					name="example_textarea"
					type="textarea"
					label="Example Textarea"
					cols="40"
					rows="8"
					description="Desc does not toggle"
					/>
			</form>
		</field>
`

**Comment by antonbag** [comment]
That worked perfectly! Thanks!!!
