### ISSUE TITLE
LDAP Login bug with Php8 in Authorisation Method Bind and Searc

### ISSUE THREAD

**Issue by jsfernando** [joomla/joomla-cms#38672]
### Steps to reproduce the issue
When logging in/password of website that was working in php7.4 version

### Expected result
true

### Actual result
false
Incorrect username and password or you don't have an account yet.

### System information (as much as possible)
Linux webserver.domain.com.br 4.18.0-372.9.1.el8.x86_64 #1 SMP Tue May 10 14:48:47 UTC 2022 x86_64
mysql
10.6.8-MariaDB
Collation BD	utf8mb4_unicode_ci
Collation connection bd	utf8mb4_general_ci
PHP	8.1.9
Serverr Web	Apache/2.4.54 (Rocky Linux) OpenSSL/1.1.1k
Interface PHP with server Web	fpm-fcgi
Version Joomla	Joomla! 3.10.10 Stable [ Daraja ] 18-June-2022 16:32 GMT
Version platform Joomla	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
On the same php8 server there are other hotsites with joomla4 version and with the same settings as ldap(Authorisation Method: Bind and Search) and it is working. only on Joomla 3.10.10 it stopped working
Below the always used settings and also an attachment:

Plugin configuration
Authorisation Method: Bind and Search
Base DN: DC=fac,DC=domain,DC=br
Search String: sAMAccountName=[search]
User´s DN: CN=userldap,OU=Users,DC=fac,DC=domain,DC=br
Connect username: userldap
Connect Password: ******
Map: Full Name: description
Map: Email: userPrincipalName
Map: User ID: sAMAccountName
![ldap-authorisationMethod-Bind-and-Search](https://user-images.githubusercontent.com/3800865/188176374-563f733e-7802-4ac5-87f8-e432416d579e.png)

Map

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38750 . Thanks in advance.

**Comment by jsfernando** [comment]
Thank you very much!
Adjusted.
All very well
