### ISSUE TITLE
Multiple emails notifying Joomla upgrade

### ISSUE THREAD

**Issue by counterpoint** [joomla/joomla-cms#38675]
### Steps to reproduce the issue

Wait for a Joomla upgrade.

### Expected result

Occasional emails notifying upgrade

### Actual result

Over 200 emails in less than 10 minutes

### System information (as much as possible)

Joomla 4.2.1 on Debian 11 and PHP 8.1

### Additional comments

Getting worse.

**Comment by ReLater** [comment]
Please check your settings in "Global Configuration" > Left Sidebar: "Installer" > "Updates Caching (in hours)"

Safe it newly.

Go to "Joomla Update". Click "Check for Updates" to clear the Update Cache.

**Comment by rdeutz** [comment]
Hope the comment had helped, closing it for now.
