### ISSUE TITLE
Search Extension Package - DEV version available, is normal ?

### ISSUE THREAD

**Issue by mariantanase** [joomla/joomla-cms#38681]
### Steps to reproduce the issue
Update a Joomla 4.2.1 to 4.2.2 fine.

I want to specify that I am on **Stable** channel for _Minimum Extension Stability_.

### Expected result
I expect that the stable version should be reported
Search Engine Package 4.0.1

### Actual result
I receive a notification for updates available:
Search Engine Package 4.0.1-dev

### Additional comments
![Screenshot 2022-09-04 at 12-20-07 Extensions Update - TANASE IT - Administration](https://user-images.githubusercontent.com/3976174/188308843-1d26affb-86ee-4388-9929-7a710dad0e05.png)

**Comment by brianteeman** [comment]
This issue should be created at https://github.com/joomla-extensions/search

**Comment by zero-24** [comment]
Yes there has not been a stable version for this extension. When you dont need it feel free to uninstall it.
