### ISSUE TITLE
W3C Org validator error

### ISSUE THREAD

**Issue by pschmehl** [joomla/joomla-cms#38685]
### Steps to reproduce the issue
Look at a page using back to top on the w3c validator. You can view my test site: [Test Site VVFH](https://testvvfh.vvfh.org "") 
[W3C Validation](https://validator.w3.org/nu/?doc=https%3A%2F%2Ftestvvfh.vvfh.org%2F "")

I'm using the Cassiopeia template. The back to the top button is selected in the Advanced tab of the Template Style.

### Expected result

Passes w3c validation

### Actual result
Error: Element style not allowed as child of element body in this context. (Suppressing further errors from this subtree.)
From line 171, column 5; to line 171, column 11
↩    ↩    <style>↩	.jj-
Contexts in which element style may be used:
Where metadata content is expected.
In a noscript element that is a child of a head element.
Content model for element body:
Flow content.

### System information (as much as possible)
LAMP system running Joomla 4.2.2 (upgraded from 3.10.11) with php 8.0.22, LiteSpeed V8.0.1 Cloudlinux 1.3, and mariadb 10.3.35

### Additional comments
I tested surrounding the social slider code with a div, but that did not clear the error.

**Comment by dgrammatiko** [comment]
The validator is wrong, ignore it. From MDN: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript 

<img width="794" alt="Screenshot 2022-09-05 at 11 00 26" src="https://user-images.githubusercontent.com/3889375/188411118-b76f07db-3b3a-4355-a8e3-21b181182c31.png">

Also from the W3C specs: https://html.spec.whatwg.org/multipage/scripting.html#the-noscript-element


<img width="1341" alt="Screenshot 2022-09-05 at 11 01 59" src="https://user-images.githubusercontent.com/3889375/188411468-1d116ce4-3457-409c-87cf-eb4289ae67cb.png">


Close this as false issue
