### ISSUE TITLE
Can't upload images larger than 512Kb in Media Manager in Joomla 4

### ISSUE THREAD

**Issue by velisnolis** [joomla/joomla-cms#38680]
### Steps to reproduce the issue

- keep standard setup values for uploads

- upload an image larger than 512kb via Menu -> Content -> Media

### Expected result

- image uploaded

### Actual result
- The blue line gets to the end and nothing happens
- There's no error in the console

### System information (as much as possible)
=============
System Information
=============
php: Linux server.miras.pro 4.18.0-372.16.1.lve.el7h.x86_64 #1 SMP Thu Jul 14 08:11:38 UTC 2022 x86_64
dbserver: mysql
dbversion: 10.5.16-MariaDB-cll-lve
dbcollation: latin1_swedish_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: false
phpversion: 8.0.22
server: Apache
sapi_name: litespeed
version: Joomla! 4.2.2 Stable [ Uaminifu ] 2-September-2022 20:41 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:91.0) Gecko/20100101 Firefox/91.0

=============
PHP Settings
=============
memory_limit: 1024M
upload_max_filesize: 16M
post_max_size: 32M
display_errors: false
short_open_tag: false
file_uploads: true
output_buffering: false
open_basedir: 
session.save_path: xxxxxx
session.auto_start: 0
disable_functions: 
xml: true
zlib: true
zip: true
mbstring: true
fileinfo: true
gd: true
iconv: true
intl: true
max_input_vars: 5000

### Additional comments

- In the same cPanel Account  and server it works on Joomla 3.10 and Wordpress
- I have tried Chrome, Safari and Firefox with the same result

**Comment by chmst** [comment]
Which value is your maximum upload in media options?

**Comment by brianteeman** [comment]
crazy suggestion but you havent run out of disk space have you?

**Comment by velisnolis** [comment]
10MB

**Comment by velisnolis** [comment]
No.I'm not out of Space. I haver a VPS and I'm the admin.

**Comment by velisnolis** [comment]
Aldo I hace the same issue un all t'he Joomla 4.2.2 in t'he server with
different accounts and 7.4 and 8.0 PHP versions. But all t'he 3.10 versions
works fine

**Comment by brianteeman** [comment]
is it always the same image you are trying to upload? if it perhaps you could attach it here so others can try to replicate your problem

**Comment by velisnolis** [comment]
@brianteeman I can give you access to a couple of joomla if you think it can help to track the issue :) 
I've tried 3 different images over 512Kb and the iissue is always present
![_MOM1181](https://user-images.githubusercontent.com/35151/188314107-e8518e45-fb84-4b66-9464-5468451df8b1.jpg)

**Comment by Franzwohlkoenig** [comment]
Successful upload:

<img width="999" alt="Untitled" src="https://user-images.githubusercontent.com/89642616/188314313-153f1377-8282-437d-a27c-a7ec7736caff.png">

**Comment by velisnolis** [comment]
Then it's something on my setup?
I have a very coomon setup. cPanel with Cloudlinux 7.9 Apache and MariaDB + alt-php + imunify360. And it's working on Joomla 3.10 and WP in the same enviroment :/

**Comment by velisnolis** [comment]
I thinks that the limit is 800kb and that it's ModSecurity related. If ModSecurity is enabled I can't upload any image greater than 800kb and works well if disabled.

This make any sense to you? 
Should I open a ticket on imunify360 website?

**Comment by velisnolis** [comment]
I think that's the rule:

77316736: IM360 WAF: Request body parsing error\|\|T:APACHE\|\|
--

**Comment by velisnolis** [comment]
For people with the same issue. The solution:
https://cloudlinux.zendesk.com/hc/en-us/articles/360012079000-Error-ModSecurity-Request-body-no-files-data-length-is-larger-than-the-configured-limit

**Comment by chmst** [comment]
Thanks for information. I close this, as it is not a joomla core issue.
