### ISSUE TITLE
[4.x] Backend article view   delete / unpublish  multiple posts at once not working

### ISSUE THREAD

**Issue by angieradtke** [joomla/joomla-cms#38688]
### Steps to reproduce the issue

> administrator/index.php?option=com_content&view=articles

Select more than two article  in the list (table) and try to delete them. 
The correct message is shown, " articles deleted", but this  is not happen.

### Actual result
The icons in the article list do not change  state and the articles are still published,

### System information (as much as possible)

Tested width Firefox

**Comment by angieradtke** [comment]
Hello Brian, 
 at the moment I can't reproduce it either, but the last days I had the phenomenon here local.  Can 4.2.1 have triggered the problem? Could it cause by  loading jam?

**Comment by brianteeman** [comment]
> Hello Brian, at the moment I can't reproduce it either, but the last days I had the phenomenon here local. Can 4.2.1 have triggered the problem? Could it cause by loading jam?

no

**Comment by brianteeman** [comment]
Please make sure that you can replicate the problem when you are posting. That way people dont waste their time
