### ISSUE TITLE
[4.2] Updates are there but not found

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#38694]
### Steps to reproduce the issue

Joomla 4.2.1, needs to be updated to 4.2.2

### Expected result
Updates are found and installed

### Actual result
Updates are found in com_cpanel but not in com_joomlaupdate

![image](https://user-images.githubusercontent.com/17835460/188491451-af88af3e-dad5-4409-8dbf-765457290491.png)

![image](https://user-images.githubusercontent.com/17835460/188491501-b10e51e7-64e3-44e6-ac5f-cd1958246409.png)

![image](https://user-images.githubusercontent.com/17835460/188491525-9ed2e34d-1fcb-4a5e-8b0e-31f13a9fc6e9.png)

**Comment by Abernyte-Git** [comment]
"Please check back to update"  Has the site not just temporarily failed to reach the update server?  
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38694">issues.joomla.org/tracker/joomla-cms/38694</a>.</sub>

**Comment by zero-24** [comment]
please tell us your php, mysql and Database versions strings.

**Comment by joeforjoomla** [comment]
Yes sure:
![image](https://user-images.githubusercontent.com/17835460/188820916-806179ce-873f-4ae6-8f9b-922e64af70a2.png)

**Comment by zero-24** [comment]
You are running on a not supported mysql version. The minimum version for 4.x is 5.6 and therefore you dont get a update.

**Comment by brianteeman** [comment]
We need to have better messaging to avoid this

**Comment by joeforjoomla** [comment]
@zero-24 thanks for the information. Anyway given that the database version is not supported, then updates should not be shown also in the com_cpanel. In this way it makes no sense.

**Comment by zero-24** [comment]
Yes i'm thinking about a message on the updater screen showing "you are running joomla on a not supported Environment" maybe also on the Dashboard?

**Comment by zero-24** [comment]
> @zero-24 thanks for the information. Anyway given that the database version is not supported, then updates should not be shown also in the com_cpanel. In this way it makes no sense.

yes kind of. you could argue that showing the update bumps you to the issue even more. Not showing the update can cause that noone notices that the update exists. Improving the messaging should be the focus in my opinion. Hiding it from the plugin is as easy as checking whether an download URL has been found or not but i can also understand the point that there is a update which should be installed.

**Comment by joeforjoomla** [comment]
> Yes i'm thinking about a message on the updater screen showing "you are running joomla in a not supported Environment" maybe also on the Dashboard?

Yes that could be ideal. I will ask to my client to update the database version on the server, but i even didn't notice he was running MySQL 5.5. It's tricky without a system message that warns about the unsupported environment.

**Comment by zero-24** [comment]
An PR with improved messaging has been created here: https://github.com/joomla/joomla-cms/pull/38799 would be great to get your feedback there @joeforjoomla @brianteeman will close here for now. Thanks
