### ISSUE TITLE
[4.2] Error in localise.php

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#38693]
### Steps to reproduce the issue

Joomla 4.2.1 with 2 languages

### Expected result
No errors with both languages

### Actual result
Error with the native en-GB language, no errors with the secondary installed language

![image](https://user-images.githubusercontent.com/17835460/188491008-5e584d5e-d290-40ad-b09d-8899b0e3754d.png)

**Comment by brianteeman** [comment]
This is clearly a problem JUST in the italian language file.

In fact if you update to the latest italian language package you will see that the problem is already fixed

**Comment by joeforjoomla** [comment]
@brianteeman correct, it was a mistake in the Italian language pack
