### ISSUE TITLE
Call to undefined method Joomla\CMS\Form\Field\MenuField::getDatabase()

### ISSUE THREAD

**Issue by joomlahenk** [joomla/joomla-cms#38692]
### Steps to reproduce the issue
Menus -> All menu items 

### Expected result
List of all menu items

### Actual result
 Call to undefined method Joomla\CMS\Form\Field\MenuField::getDatabase()

Call stack:
# | Function | Location
1 | () | JROOT/libraries/src/Form/Field/MenuField.php:49
2 | Joomla\CMS\Form\Field\MenuField->getGroups() | JROOT/libraries/src/Form/Field/GroupedlistField.php:160
3 | Joomla\CMS\Form\Field\GroupedlistField->getInput() | JROOT/administrator/components/com_fabrik/classes/FormField.php:468

### System information (as much as possible)
Joomla 4.2.2, PHP8.1, MySQL5.7

### Additional comments
The extension uses a class override for FormField.php.
In Joomla 4.1.5 this was working.
In Joomla 4.2.x in libraries/src/Form/Field/MenuField.php:49, $db = Factory::getDbo(); is changed to $db = $this->getDatabase();
now causing this error.
If I change $db = $this->getDatabase(); back to $db = Factory::getDbo(); the issue is solved.

**Comment by ReLater** [comment]
Even if I fully understand the frustration about this B\C breaking change in v4.2.2 (a so called "improvement") I think you should ask the developers of com_fabrik to adapt their extension.

The chances are slim that this will be fixed in Joomla core. That's just my opinion...

**Comment by joomlahenk** [comment]
OK, not a Joomla 4.2.2 bug. Solved in com_fabrik
