### ISSUE TITLE
spam

### ISSUE THREAD

**Issue by isabellapritchardr** [joomla/joomla-cms#38699]

**Comment by PhillaSc** [comment]
https://sultangames.com/ru/casino/slots/game/andromeda-aztecgold<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38699">issues.joomla.org/tracker/joomla-cms/38699</a>.</sub>
