### ISSUE TITLE
Allowed Frontend/backen module positions stay empty

### ISSUE THREAD

**Issue by basd82** [joomla/joomla-cms#38705]
![screen shot 2022-09-06 at 14 56 44](https://issues.joomla.org/uploads/1/ca6ce434c6e151e2edb7386dac5e7073.png)
Hi
I have the problem the allowed frontend/backend module positiions stay empty here.

Version infp

Database Version 8.0.30-0ubuntu0.20.04.2
Database collatie	utf8mb4_unicode_ci
Collatie van de databaseverbinding	utf8mb4_0900_ai_ci
Database verbinding versleuteling	TLSv1.3 (TLS_AES_256_GCM_SHA384)
Databaseserver ondersteunt verbindingsversleuteling	Ja
PHP Version 8.0.22
Webserver	Apache
Webserver naar PHP interface	fpm-fcgi
Joomla! versie	Joomla! 4.2.2 Stable [ Uaminifu ] 2-September-2022 20:41 GMT

**Comment by brianteeman** [comment]
What front end template are you using?

If its not cassiopeia please could you also test with that template

**Comment by basd82** [comment]
Just tested on my personal play ground vanila joomla same issue

**Comment by brianteeman** [comment]
strange as it works for me - I wonder what the difference is

**Comment by coolcat-creations** [comment]
Also empty for me: 
<img width="809" alt="grafik" src="https://user-images.githubusercontent.com/828371/188736821-d4d1c02d-e7bf-4adb-a46c-369ccaf9a1ea.png">

**Comment by basd82** [comment]
Any resolution's or workaround for this ?
Can someone tel we has it working how the db settings look like so i have workaround ?

**Comment by basd82** [comment]
I have add my postions manual this works

I did this in params field in extention table for com_users.

  "allowed_positions_frontend": ["navbar","footer"]

But they don't show up in the config. 

So there is something wrong in field of module selection

**Comment by brianteeman** [comment]
Found the reason. It only lists module positions that are in use. It is the same as the position filter in the module manager

![image](https://user-images.githubusercontent.com/1296369/221528982-fd82c05b-e2db-4c69-b60d-34c537a0be37.png)

![image](https://user-images.githubusercontent.com/1296369/221529066-8835bb7e-873d-47dc-98f7-ec8e1c479a3f.png)

**Comment by coolcat-creations** [comment]
I got an external email from Nico, who fixed the issue by writing ModulesPosition instead modulesposition in the file /administrator/components/com_users/config.xml I tested the fix and it works for me. I will prepare a PR thanks to him.

**Comment by basd82** [comment]
Great

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by coolcat-creations** [comment]
@basd82 did you test it?

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40040 . Thanks in advance.
