### ISSUE TITLE
Joomla 4.2.2 Integer fields not working correctly

### ISSUE THREAD

**Issue by jzeevi** [joomla/joomla-cms#38709]
### Steps to reproduce the issue
Create an integer field with a start value of 100000 and an end value to 900000 and increment of 1.
select a user to edit this field

### Expected result
Can edit/enter a number in the field

### Actual result
Selecting the user turns the webpage to white.

### System information (as much as possible)
Joomla 4.2.2
Integer fields with max less than 1000 seem to work acceptably.
Other large numbers for start/stop seems to either turn the returned page to red (error indication) or white (no response at all)

**Comment by jzeevi** [comment]
I'm happy to try things to help debug this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38709">issues.joomla.org/tracker/joomla-cms/38709</a>.</sub>

**Comment by brianteeman** [comment]
Expected behaviour. Integer field provides a drop down list of integers between a minimum and maximum. So not surprising the page ran out of memory.

You want a number field 
https://docs.joomla.org/Number_form_field_type

**Comment by jzeevi** [comment]
Ah! How do I create a number field from the Users->Fields->New form? There doesn't seem to be a number type there.

**Comment by jzeevi** [comment]
BTW - thanks for the explanation - yes, I can see why it didn't work. Not sure how to create a number field, though.

**Comment by jzeevi** [comment]
And, A lot of searching turned up that you need to select a text field and assign is to get filtered as an integer. Thanks for the hint.

**Comment by brianteeman** [comment]
sorry beat me to it - glad you found the answer
