### ISSUE TITLE
The problem after switching to jumla 4

### ISSUE THREAD

**Issue by FxBullMarket** [joomla/joomla-cms#38706]
Hello, I need help, after switching from 3.10.x to joomla 4 (version 4.2.1) for some reason, registered users can log in to the site, but new ones cannot register. I removed the old plugins and modules because there was no version 4. I have temporarily enabled the standard joomla component, but it gives a short error message "Registration failed" (Registration failed:). And after the transition there are many problems, but now it is more important.
The topic is open on the official Joomla forum, but no one can find a solution. We checked the site folders and the database on the hosting, everything is fine there

**Comment by brianteeman** [comment]
The forum is the correct place for support issues

**Comment by brianteeman** [comment]
Please close. This is a forum issue

**Comment by FxBullMarket** [comment]
Even the developers of jumla themselves do not know how to solve some problems on jumla 4!!!!! It was necessary to stay on jumla 3.x for another 5-7 years!!!!!!

**Comment by brianteeman** [comment]
Not at all. Any problem can be solved. But this is not the place to offer support
