### ISSUE TITLE
logout getMenuLanguage

### ISSUE THREAD

**Issue by thalueng** [joomla/joomla-cms#38720]
### Steps to reproduce the issue
PHP throws a TypeError on logout from the site. This is because getMenuLanguage is called with the wrong argument in com_users/src/Controller/UserController.php within method logout on line 146 (Joomla 4.2.2), which was introduced with Joomla 4.2.0.

### Expected result
getMenuLanguage needs to be called with $return == menu id (xxx) as int, not with $return == 'index.php?Itemid=xxx'

### System information (as much as possible)
Joomla 4.2.2, Apache 2.4, PHP 7.4

**Comment by brianteeman** [comment]
This is the pull request where the change was made https://github.com/joomla/joomla-cms/pull/38299

**Comment by chmst** [comment]
Closing as there is a pull request

**Comment by brianteeman** [comment]
@chmst I think you may have misunderstood. The PR I referenced is the one causing the reported broken behaviour

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/39251 should fix this issue. Please help testing. Thanks !
