### ISSUE TITLE
[4.2] Missing ParameterType::DOUBLE in case of prepared statements

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#38730]
### Steps to reproduce the issue

Use the ParameterType::DOUBLE

### Expected result

No error message

### Actual result

Error message:
Undefined class constant 'DOUBLE' 

### System information (as much as possible)

J4.x

### Additional comments

Honestly I don't know if this is really a bug, but a conscious choice of Joomla design in the past.

**Comment by wilsonge** [comment]
It's a kinda conscious choice. The parameter types are a way for us to backport PDO's parameter types into the other languages. Double isn't one of these types (the 5 we have are a mapping to the non-php 7.2 param types here https://www.php.net/manual/en/pdo.constants.php) so we've not done anything special for it

**Comment by sandewt** [comment]
@wilsonge 

_1) Joomla has defined the following parameters:_

JOOMLA\libraries\vendor\joomla\database\src\Sqlsrv\SqlsrvStatement.php

protected $parameterTypeMapping = [
		ParameterType::BOOLEAN      => ParameterType::BOOLEAN,
		ParameterType::INTEGER      => ParameterType::INTEGER,
		ParameterType::LARGE_OBJECT => ParameterType::LARGE_OBJECT,
		ParameterType::NULL         => ParameterType::NULL,
		ParameterType::STRING       => ParameterType::STRING,
	];

_2) I compare the Joomla parameters with the following:_

[https://www.php.net/manual/en/mysqli-stmt.bind-param.php](https://www.php.net/manual/en/mysqli-stmt.bind-param.php)

i 	corresponding variable has type integer
d 	corresponding variable has type double
s 	corresponding variable has type string
b 	corresponding variable is a blob and will be sent in packets

_3) That's why I started this issue. But I may be seeing this wrong._

**Comment by brianteeman** [comment]
you do realise that the first file you reference is for sql server?

**Comment by sandewt** [comment]
This is an example of what I mean.
The `ParameterType::DOUBLE` is not available.

```
$test = (float) $value; // e.g. $value = 2.2311

$query = $db->getQuery(true)
	->select($db->quoteName('id'))
	->from($db->quoteName('#__example'))
	->where($db->quoteName('test') . ' = :test')
	->bind(':test', $test, ParameterType::DOUBLE);
$db->setQuery($query);
$db->execute();

```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38730">issues.joomla.org/tracker/joomla-cms/38730</a>.</sub>

**Comment by sandewt** [comment]
Closed
