### ISSUE TITLE
Custom field description is not displayed in the article or category editor form

### ISSUE THREAD

**Issue by adiheutschi** [joomla/joomla-cms#38743]
### Steps to reproduce the issue

The description text of the custom field should be displayed in the article editing window.

![printscreen09-12-22 at 09 40 AM](https://user-images.githubusercontent.com/16303176/189603983-2c3a9893-0248-41a8-95f7-d66c8ff4acd4.JPG)

before without description in Article/Category Editor:
![printscreen09-12-22 at 09 45 AM 001](https://user-images.githubusercontent.com/16303176/189603514-de055624-6d63-413f-be71-f094165b0d94.JPG)

### Expected result

The description text of the custom field should be displayed in the article editing window.

![printscreen09-12-22 at 09 40 AM](https://user-images.githubusercontent.com/16303176/189603983-2c3a9893-0248-41a8-95f7-d66c8ff4acd4.JPG)

![printscreen09-12-22 at 09 49 AM](https://user-images.githubusercontent.com/16303176/189603530-c056b040-872f-4c2b-9823-541b7d363340.JPG)

### Actual result

The field description of the custom field is not displayed in the Article or Category form.

![printscreen09-12-22 at 09 45 AM 001](https://user-images.githubusercontent.com/16303176/189603084-e17c3e5e-20ac-4158-a370-c8f6f542bed5.JPG)

**Comment by crystalenka** [comment]
Confirmed, suspect this is something to do with the new 'toggle inline help' feature

**Comment by brianteeman** [comment]
Yes it is - descriptions that were always displayed are now only displayed when toggled. See title alias field as an example

**Comment by crystalenka** [comment]
It doesn't always work for custom fields, I have seen this too.

**Comment by chmst** [comment]
I see this as a bug here in custom fields.

**Comment by crystalenka** [comment]
Actually I can't reproduce in articles anymore. It shows up with the toggle.

In categories, the toggle help button is not yet implemented and the custom field description shows.

Do you maybe have a plugin that is changing how things are rendered? I see a little icon in the title field that makes me think that might be the case. I also don't see the toggle button on your article edit form. @adiheutschi

**Comment by brianteeman** [comment]
Can not replicate

![image](https://user-images.githubusercontent.com/1296369/190361736-0f99701c-2b4e-4884-9f3c-b0dcb6037d8f.png)

![image](https://user-images.githubusercontent.com/1296369/190361797-4aa140d3-c9fd-4fe9-89e3-1d71b7fccbeb.png)

![image](https://user-images.githubusercontent.com/1296369/190361934-550e8a3c-25bf-4e79-af74-2c46bf6c4ea5.png)

![image](https://user-images.githubusercontent.com/1296369/190362138-60d3744a-5316-4c60-a57f-a49ac05acd18.png)

**Comment by adiheutschi** [comment]
> Eigentlich kann ich in Artikeln nicht mehr reproduzieren. Es zeigt sich mit dem Kipper.
> 
> In Kategorien ist die Schaltfläche zum Umschalten der Hilfe noch nicht implementiert und die Beschreibung des benutzerdefinierten Felds wird angezeigt.
> 
> Haben Sie vielleicht ein Plugin, das die Art und Weise ändert, wie Dinge gerendert werden? Ich sehe ein kleines Symbol im Titelfeld, das mich denken lässt, dass dies der Fall sein könnte. Ich sehe auch nicht die Umschaltfläche auf Ihrem Artikelbearbeitungsformular. @adiheutschi

The icon is from the roboform password manager. This has no influence.

**Comment by brianteeman** [comment]
Can anyone else replicate this bug?

**Comment by crystalenka** [comment]
@adiheutschi Do you see the "toggle inline help" button anywhere?

**Comment by adiheutschi** [comment]
With "toogle inline help" enabled, it shows the descriptions for the customFields. Thats great!

However, I don't have this "toogle inline help" button on some pages either. It is missing. See printscreens. 
Probably on migrated pages. With a new installation it is present.
Also after there Joomla 4.2.2 Update Package again have installed as well as the Full Package 4.2.2.

Additional question.
Is it possible to activate the "toogle inline help" button by default?

![Screen Shot 09-25-22 at 01 38 PM](https://user-images.githubusercontent.com/16303176/192141484-3f6725a5-f99a-45c5-9c04-eb567713c30a.JPG)

**Comment by adiheutschi** [comment]
I think I have an unclean test installation.
I don't have the problem with the missing toggle on any other pages.

It would only be nice if the Toogle - Inline Help - could be activated by default.

I don't think normal users would get the idea to select this. 

Thank you very much for your efforts!!!
