### ISSUE TITLE
[4.3] Error installing cypress

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38740]
On a clean checkout of 4.3 on a windows pc and then running `npm i`
It gets to a certain point and then _hangs_

Checking the npm log and the directory tree its failing when trying to install cypress.

```

207 timing reify:rollback:retireShallow Completed in 15ms
208 timing command:i Completed in 284544ms
209 verbose stack Error: command failed
209 verbose stack     at ChildProcess.<anonymous> (C:\laragon\bin\nodejs\node-v18\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
209 verbose stack     at ChildProcess.emit (node:events:527:28)
209 verbose stack     at maybeClose (node:internal/child_process:1090:16)
209 verbose stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
210 verbose pkgid cypress@10.6.0
211 verbose cwd C:\laragon\www\j4
212 verbose Windows_NT 10.0.22000
213 verbose node v18.3.0
214 verbose npm  v8.12.1
215 error code 127
216 error path C:\laragon\www\j4\node_modules\cypress
217 error command failed
218 error command C:\WINDOWS\system32\cmd.exe /d /s /c node index.js --exec install
219 error Installing Cypress (version: 10.6.0)
219 error
```

**Comment by Hackwar** [comment]
I checked out a clean copy of the current 4.3-dev branch and ran `composer i` and `npm i` and it installed fine. Maybe a firewall preventing something to run?

**Comment by brianteeman** [comment]
Hard to believe it will be a firewall as everything else works. Are you using windows?

**Comment by Hackwar** [comment]
Windows 10 Pro Version	10.0.19044 Build 19044

**Comment by N6REJ** [comment]
Can't confirm
![image](https://user-images.githubusercontent.com/1850089/189840903-b4297cc6-beb1-4547-ba88-cf650c946b1a.png)

**Comment by C-Lodder** [comment]
Can't confirm on Window 10 x64. Tried with both Node.js 16.x and 18.x
Try updating your Node.js from 18.3.0 to **18.9.0**

**Comment by brianteeman** [comment]
Thanks @C-Lodder will give that a try later

My google-fu seems to suggest that this is a regular problem with cypress

**Comment by Hackwar** [comment]
Is there any more in the log output? Can you get more information maybe with more verbose output?

**Comment by brianteeman** [comment]
updating node seems to have resolved the problem
