### ISSUE TITLE
psr12 script

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38754]
Following a comment elsehwere I checked and there appear to be approx 70 files still using tabs for indentation instead of spaces.

For example
administrator\components\com_actionlogs\src\View\Actionlogs\HtmlView.php

I ran the psr12 scripts but it didnt pick up anything and I checked the ruleset.xml to make sure that these files were not being excluded.

@HLeithner am I missing something?

**Comment by HLeithner** [comment]
I think the psr12 can be removed at some point (will do this later, because it also removes the jexec die).
I will look why this file is not touched... I don't see a reason based on the path...

**Comment by brianteeman** [comment]
its not the only file.

i did a grep for tabs in *.php and that gave me 76 files

**Comment by HLeithner** [comment]
yes I understood that, more interesting is why drone doesn't complain.

**Comment by brianteeman** [comment]
drone doesnt complain about a lot of things. I keep saying that

**Comment by HLeithner** [comment]
yes but it should complain about tabs

**Comment by brianteeman** [comment]
thinking out loud here but its almost as if - there were no other errors in the file - so it was skipped. and that the conversion from tab to space only takes place on saving an edited file

**Comment by HLeithner** [comment]
shouldn't be the case because phpcs did the analyse which should know the difference between space and tabs ;-)
I would think that the files where excluded maybe because of html in the name but that's only a guess

**Comment by brianteeman** [comment]
unlikely as this is one of the other files 
administrator\components\com_actionlogs\tmpl\actionlogs\default.php

**Comment by brianteeman** [comment]
see #39145
