### ISSUE TITLE
PHP 8.1 deprecation warning "htmlspecialchars(): Passing null to parameter #1" when using Brand image without description

### ISSUE THREAD

**Issue by beni71** [joomla/joomla-cms#38759]
### Steps to reproduce the issue
In the backend:
1. Navigate to Menu Home dashboard
2. Click Global configuration, in TAB "Server", set Error Reporting to "Maximum".
3. Navigate to Menu System
4. Click Administrator Template Styles, open your active style. In my case it is "Atum - Default".
5. In TAB "Image Settings", Select a "Brand Large" image, leave Image description empty and check the "No Description" box.
6. Select a "Brand Small" image, leave Image description empty and check the "No Description" box.
7. Click SAVE.

![grafik](https://user-images.githubusercontent.com/8353850/190154507-35c8be41-3cd6-434e-b774-0ee9321838e2.png)

### Expected result
There is no PHP deprecation warning.

### Actual result
There are two PHP deprecation warnings:

```
Deprecated
: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in
E:\joomla\4.2.2\administrator\templates\atum\index.php
on line
56

Deprecated
: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in
E:\joomla\4.2.2\administrator\templates\atum\index.php
on line
59
```

### System information (as much as possible)
Installed Joomla 4.2.0 and updated it to 4.2.2
mysql   10.4.24-MariaDB
Apache/2.4.53 (Win64) OpenSSL/1.1.1n PHP/8.1.6
Joomla! 4.2.2 Stable [ Uaminifu ] 16-August-2022 13:05 GMT

**Comment by brianteeman** [comment]
The current version is 4.2.2

**Comment by beni71** [comment]
Your are right, sorry for that. I updated Joomla to the latest version 4.2.2, but the problem is still there.

**Comment by alikon** [comment]
please test #38762
