### ISSUE TITLE
Providing an option to disable core (template) CSS Styles for modules

### ISSUE THREAD

**Issue by stefanwillig** [joomla/joomla-cms#38769]
### Is your feature request related to a problem? Please describe.
On updating a Joomla 3.x website to Joomla 4.x, I've found some new CSS Classes in Core Module Template CSS, with new attributes.
As all our templates are custom developed for our customers, new CSS classes and attributes in some core CSS files lead to displaying problems in our templates.

### Describe the solution you'd like
It would be nice to have an option to disable loading core template CSS from any module.
Maybe there could be an option switch in the module backend to choose if you want to load core CSS for this module or not.
Maybe there could also be an option switch in configuration -> modules for disabling/enabling core module CSS system wide.

**Comment by brianteeman** [comment]
there is no such thing as core css. your template contains all the css.

or did you mean css classes such as `div class="d-none"`

If you did then that is what template overrides are for

**Comment by stefanwillig** [comment]
In my case, it was "mod_languages".
There comes a template.min.css (/media/mod_languages/css/template.min.css) with the module core.

In my case there is a new CSS class "div.mod-languages ul li.lang-active" which now has defined a background-color.

**Comment by brianteeman** [comment]
ah - there are two exceptions to my statement and you found one.

far quicker for you to just override that class in your templates css than to find an option and remember to set it.

or to delete the line calling that css file in a module override.

you cant have an option for everything - thats why yyou have the option to customise things with css and template overrides. And as you build custom templates for everyone then you already know how to do it.

**Comment by chmst** [comment]
@stefanwillig thank you for your contribution. @brianteeman show you a way to resolve your issue. I will close it now, We can re-open if you think it is necessary.

**Comment by coolcat-creations** [comment]
@chmst I think Core should not force CSS by default - don't you think so? I can create a PR with a setting to disable the css? cc @crystalenka @angieradtke @pe7er
