### ISSUE TITLE
Dashboards and Joomla\CMS\Installer\InstallerScript

### ISSUE THREAD

**Issue by nikosdion** [joomla/joomla-cms#38760]
OFF TOPIC

**Comment by crystalenka** [comment]
I can't comment to the technical implementation, but from a usability perspective, a little more consistency between component dashboards (like from third parties) would be hugely helpful. From what I understand, these changes would encourage 3PDs to use core dashboards more and it would be more consistent across the board? Is that accurate?

**Comment by nikosdion** [comment]
@crystalenka Correct. The other missing part for Dashboards adoption is documentation which I am already working on.

**Comment by brianteeman** [comment]
Probably should @hackwar as he wrote the original Pr

**Comment by nikosdion** [comment]
@brianteeman As you can read in my issue, I am not even touching the Dashboard feature at all — that's what Hannes wrote. This part works fine.

I am only touching the installer script which was contributed by @wilsonge based on the code of the F0FUtilsInstallScript class included in FOF 2.x.

**Comment by brianteeman** [comment]
it was a long issue to read ;)

**Comment by rdeutz** [comment]
Valid issue

**Comment by nikosdion** [comment]
You are actively harassing me by reopening the issues I have closed because your organisation has bullied me away. What kind of dystopian hell is this project?
