### ISSUE TITLE
Media Manager Thumbnails

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38773]
### Steps to reproduce the issue
At high resolutions the layout is broken for images whose natural width is less than thumbnails - See below

![image](https://user-images.githubusercontent.com/1296369/190441742-d8e32b5b-3b30-4b3a-be56-9f7c4c0b3da0.png)

This is cause because there is no min-width min-height values set on the thumbnail container and the container has css setting an aspect ratio of 1:1 - the images probably should be centered as well

My css isnt good enough to fix this

**Comment by crystalenka** [comment]
This may be fixed by accident in my PR https://github.com/joomla/joomla-cms/pull/38771, can you check?
