### ISSUE TITLE
[4.2.3 RC] Tabs instead of spaces left in some files

### ISSUE THREAD

**Issue by StefanSTS** [joomla/joomla-cms#38786]
In some files there are still tabs instead of spaces.

- libraries/src/Cache and subfolders
- plugins/system/actionlogs/actionlogs.php
- administrator/components/com_admin/src/Service/HTML/Configuration.php
- ....com_cache/tmpl/cache/emptystate.php

I am not sure if I caught all occurrences.
If you compare the installation folders of J 4.1.5 and 4.2.3 RC with Meld or KDiff3 you can quickly identify the files that stayed the same.

Regards
Stefan

**Comment by brianteeman** [comment]
#38754

**Comment by brianteeman** [comment]
please check #39145

**Comment by StefanSTS** [comment]
Thanks, Brian.
