### ISSUE TITLE
[4.2x] Feature request: assign category to field if pre-filtered to a category

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#38794]
### Is your feature request related to a problem? Please describe.
In Article view, filtering by a category and then selecting 'new' ensures that the category is pre-selected.
For new fields, this does not. Even if the fields are filtered by a category, when '+ New' is selected, the default category is 'All'. 

### Describe the solution you'd like
Allow the Fields' filtered category to become the default category.

### Additional context
I appreciate that fields can be allocated to several categories, but the pre-filtered category is a good start. Having 'All' is somewhat dangerous, especially if the field is mandatory and one forgets to change the category on saving the new field.

**Comment by simbus82** [comment]
This can speed up the work of copywriters/editor users a lot, and this is a real UX improvement. Little things that make big difference.
I hope the team consider it, nice solution!

**Comment by brianteeman** [comment]
fyi it works correctly for the field group so shouldnt be a hard fix

**Comment by joomdonation** [comment]
I made PR https://github.com/joomla/joomla-cms/pull/39253 to implement this request. Please help testing. Thanks !
