### ISSUE TITLE
[4.2x] Menu item 403 error pop-up 'Close' button doesn't work

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#38801]
### Steps to reproduce the issue
I have a problem with - probably - mod_security blocking me from editing an article from within the menu item setup. My hosts are looking at that. However, in the meantime, when I try to edit the article a modal pops up with a 403 error message, but the three buttons that appear at the bottom of the pop-up - most importantly the 'Close' button - don't work.

### Expected result
Click 'Close' and the modal disappears

### Actual result
Nothing happens. The only way to close the pop-up is to hit the Esc key.

### System information (as much as possible)
Joomla 4.2.2
The error message in the console is:
Uncaught TypeError: i.contentWindow.Joomla is undefined
    processModalEdit https://cassiopeia.[my-domain].co.uk/media/system/js/fields/modal-fields.min.js?2cf5ce06b5b33eeae7bfc9c13af12daa32ce7475:1
    onclick https://cassiopeia.[my-domain].co.uk/administrator/index.php?option=com_menus&view=item&client_id=0&layout=edit&id=101:1

And

"The character encoding of a framed document was not declared. The document may appear different if viewed without the document framing it."

[https://cassiopeia.[my-domain].co.uk/administrator/index.php?option=com_content&view=article&layout=modal&tmpl=component&f7aba2e4ccd0808dc7459d8cb95eecfe=1&task=article.edit&id=%27%2013%20%27]

### Additional comments
I realise there is an ongoing discussion about the original problem of mod_security conflicts, but perhaps the button issue could be sorted in the meantime? Thanks.

**Comment by brianteeman** [comment]
It's all related so can't be resolved on it's own

**Comment by Quy** [comment]
Duplicate #38404?

**Comment by brianteeman** [comment]
@quy yes its a duplicate
