### ISSUE TITLE
Impossible to differentiate disabled values in select

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#38817]
### Steps to reproduce the issue

Open a select box that has values that are disabled. If you cannot find one, use the inspector of your browser and set one of the options to have the attribute 'disabled'.

### Expected result

I can visually see what values are disabled

### Actual result

I have no visual clue that some values are disabled. I can only find it out when the mouse or the finger just cannot select the disabled item. 

For instance, the 'left' value is disabled. Can you tell?

![screen shot 2022-09-22 at 18 51 32](https://issues.joomla.org/uploads/1/c51919925087ae7b349c71001e249724.png)

### System information (as much as possible)

Any Joomla 4.

**Comment by Quy** [comment]
Duplicate #34496?

**Comment by obuisard** [comment]
Indeed, an identical issue. Brian offered a solution, which was not accepted then (adding a background to the disabled item). The focus got moved to the workflow functionality and having a disabled item inside the workflow select box (from which the example was from), but it totally missed the point: disabled items are not differentiated visually from the other enabled ones.

**Comment by brianteeman** [comment]
It appears to me that this has been resolved elsewhere. Please confirm and close

**Comment by obuisard** [comment]
Yes, it can be closed as there was a resolution as proved by the screenshot below (where one see distinctively which item is disabled):

![Image](https://github.com/user-attachments/assets/00616f00-60b9-4d41-95ff-613d5d187c06)
