### ISSUE TITLE
Admin com_menus component wrongly overrides JDEFAULT

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#38815]
### Steps to reproduce the issue

I have not noticed this with core extensions but with third-party extensions.
If an extension uses JDEFAULT as value for a field, the field value is translated into 'home' rather than 'Default' (in English anyway).

### Expected result

The translation shows 'Default' in English.

### Actual result

The translation shows 'Home' in English.

### System information (as much as possible)

Any Joomla 4 version.

### Additional comments

Such a key should not have a totaly different meaning, and I don't think JDEFAULT should be translated into anything else than 'Default'.

**Comment by Quy** [comment]
Duplicate #34438

**Comment by brianteeman** [comment]
its a simple fix

**Comment by brianteeman** [comment]
Please test #38825
