### ISSUE TITLE
Difficulty to dissociate hint from actual value in input field

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#38816]
### Steps to reproduce the issue

Find an input text field that has a hint.
For instance:
![screen shot 2022-09-22 at 18 41 44](https://issues.joomla.org/uploads/1/4df5606695287a0e5f5d7fd79cf01d37.png)

### Expected result

I can tell this is a hint and not the actual value

### Actual result

I can't tell if I see the value or the hint

### System information (as much as possible)

Any Joomla 4 version

### Additional comments

Using colors to differentiate hint from actual value may not be the answer.
One solution could be to add the hint to the description. But now the system can hide descriptions...

**Comment by brianteeman** [comment]
kill the hint

**Comment by obuisard** [comment]
I would kill the hint too, but that is a standard HTML attribute, and we can't ignore it.

**Comment by brianteeman** [comment]
`input::placeholder {font-size: .8rem;}`

![image](https://user-images.githubusercontent.com/1296369/192036984-959db21a-7f1e-4c89-bdf0-22ec9dccef2f.png)

![image](https://user-images.githubusercontent.com/1296369/192036996-c4aa9100-9f74-4b2f-889f-0063dfa9bbbb.png)

or
`input::placeholder {font-size: .8rem;font-style:italic;}`

![image](https://user-images.githubusercontent.com/1296369/192037148-0e7607fa-3556-4388-bed7-db56a18ac627.png)

**Comment by obuisard** [comment]
+1 for me. Being italic, smaller and slightly whiter makes it easier to spot as a hint. 
No accessibility issue either as we use standard markup.

**Comment by brianteeman** [comment]
please test #38827
