### ISSUE TITLE
Buttons in the modal window without function

### ISSUE THREAD

**Issue by deltapapa01** [joomla/joomla-cms#38814]
Hello,

I'm not entirely sure if this is a bug, but maybe one of you can confirm it. Tried it on two different J!4.2.2 with the same result:

click path:

- I create a menu item (single article) and select an existing article.
- Then I delete the article (also from the recycle bin)
- In the menu management I would now like to select a new article, but at the end it says "Edit" instead of "Select":

![screen shot 2022-09-22 at 16 07 27](https://issues.joomla.org/uploads/1/5b3971cd8230c26a50ed6d1702a5e547.jpg)

- If I click on Edit (not on Empty first) I get the following window as a modal:

![screen shot 2022-09-22 at 16 09 01](https://issues.joomla.org/uploads/1/2e6fd0f4d044a77ba700ca905a522a56.jpg)

- I can't get out of this window, except with the browser back button.
- I can also move in the modal (LeftMenu), just not close it.

When I click the Close button in the modal window, the following error appears in the console:

![screen shot 2022-09-22 at 16 11 16](https://issues.joomla.org/uploads/1/7ddcfce7f675b489d90799dbfd947dfb.jpg)

I posted this yesterday in the German Joomla Forum, someone could confirm the error there: https://forum.joomla.de/thread/16725-buttons-schlie%C3%9Fen-etc-im-modal-ohne-funktion/# post115494

Joomla 4.2.2, PHP 8.1.10, mysql 8.0.25-15, Apache Server

WBR,
deltapapa

**Comment by ReLater** [comment]
I confirm this issue with Joomla 4.2.3. I was not tough enough to click Save buttons in modal because tested on a productive site ;-)

**Comment by alikon** [comment]
please test #38984
