### ISSUE TITLE
Users/Groups/permission page not responsive

### ISSUE THREAD

**Issue by Lakshay-Pruthi** [joomla/joomla-cms#38828]
### What needs to be fixed
The User/Groups/permission page is not responsive. Headers are not aligned with each other.
![image](https://user-images.githubusercontent.com/91469717/192087279-c5fef819-21bc-4319-9639-4c7bf13c7b5a.png)
 

### Why this should be fixed
To make the page responsive for all types of resolutions

### How would you fix it
By making it responsive

### Side Effects expected
No

**Comment by Lakshay-Pruthi** [comment]
I would like to work on this issue. Can anyone share the path to the file where the code for this is written?

**Comment by chmst** [comment]
Thank for yourinterest in contributing. But your screen is not from Version 4.2.2. 
It looks like this: 

![grafik](https://user-images.githubusercontent.com/1035262/192092004-0a247d11-71d0-42e8-a99d-7555ce23be27.png)

Please have a look here https://github.com/joomla/joomla-cms/pull/37807

But if you can make this table responisve, it would be great!

**Comment by Lakshay-Pruthi** [comment]
I am referring to this table -->



![image](https://user-images.githubusercontent.com/91469717/192335431-c7fdb83e-1318-48da-8ea5-ec5c7999227f.png)



I made some changes via "inspect element" in the browser and it works.



![image](https://user-images.githubusercontent.com/91469717/192335049-6a64a40b-bb4e-4d7b-82ae-4c6322e1dcb9.png)

![image](https://user-images.githubusercontent.com/91469717/192335166-26a99313-711d-4e00-9801-855416b1889d.png)





I am not able to find the stylesheet file for this page. Can you help me in finding the path?

**Comment by brianteeman** [comment]
I think @chmst was confused with the users/permissions page when this is the usergroups/permissions page

The files you need to look in are administrator/com_users/tmpl/debuggroup

**Comment by Lakshay-Pruthi** [comment]
@brianteeman  When we install Joomla we get this folder -->
![image](https://user-images.githubusercontent.com/91469717/192553361-8edcc299-008a-4af9-a3cc-6d732603819b.png)
but I can't find it in the repo. Basically I'm looking for media\templates\administrator\atum\css\template.min.css .

**Comment by Lakshay-Pruthi** [comment]
@brianteeman any update??

**Comment by AnonymousX777** [comment]
@chmst Can I work on this issue?

**Comment by AnonymousX777** [comment]
@chmst I'm also confused with the template.min.css file as I am not able to find it in the repository.

**Comment by chmst** [comment]
Everyone can work on this issue. 
You cannot change the template.min.css but work on files in the scss folder. npm then generates the min.css.

**Comment by richard67** [comment]
Closing as having a pull request, see #39326 .

**Comment by chmst** [comment]
Re-opening as the PR did not resolve the problem

**Comment by brianteeman** [comment]
@chmst maybe this should simply be closed as not achievable and that you should use the table-column selector if needed.

**Comment by chmst** [comment]
What could be improved: Extract the first columns of the table as in user permissions. But responiveness is not achievable, this is true and a reason to close here.

**Comment by Lakshay-Pruthi** [comment]
@chmst @brianteeman You said this can't be made responsive. I did it!! check #39335

**Comment by brianteeman** [comment]
no you did not as already explained.
