### ISSUE TITLE
Missing Manage Plugins button on Extensions: Install page

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#38824]
### Steps to reproduce the issue

Go to extensions install page..

### Expected result

After installing a plugin frequently want to configure the plugin.

### Actual result

The Manage Extensions button is of no use in this scenario.

### Additional comments

Workaround - usually have a browser tab open at Manage Plugins page, annoying that one has to refresh it to see the new plugin. A manage plugin button would make the process simpler - drag & drop install and click manage plugin button to configure.

**Comment by brianteeman** [comment]
> The Manage Extensions button is of no use in this scenario.

Depends on the type of extension

> Workaround 

No need for a workaround. You can add functionality in your plugin to do this

My 2c is that this has to be done by the extension developer as its not always appropriate

some extension developers open the plugin manager with a filter to just display their plugins on install
some extension developers open the specific plugin on install

**Comment by joomdonation** [comment]
Agree that this should be implemented by extension developer. So I'm closing this issue.
