### ISSUE TITLE
SocketTransport Location is array

### ISSUE THREAD

**Issue by billyroberts11** [joomla/joomla-cms#38821]
try {
// Set the query and get the result list[.](https://essaymap.org/ "")
$db->setQuery($this->query);
$items = $db->loadObjectList();
} catch (ExecutionFailureException $e) {
Factory::getApplication()->enqueueMessage(Text::('JERROR_AN_ERROR_HAS_OCCURRED'), 'error');
} catch (mysqli_sql_exception $e) {
Factory::getApplication()->enqueueMessage($e->getMessage(), 'error');
}
_

**Comment by Hackwar** [comment]
I have no idea what this report is supposed to mean. Since there is a slightly older issue with the same title, I'm guessing that this actually isn't a valid issue report. Closing this one.
