### ISSUE TITLE
[4.2] Choose from multiple accessibility symbol icons

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#38832]
On my website I use the Joomla accessibility symbol.
See the image below.

I have received criticism from several people that the symbol used by Joomla is confrontational.

My suggestion is to use a more friendly symbol or at least a choice, that is internationally recognized.

### Expected result

An example from another icon (source font awesome):
![screen shot 2022-09-25 at 09 29 13](https://issues.joomla.org/uploads/1/c976d368cd797a9954de5f68b053235b.png)

### Actual result

![screen shot 2022-09-25 at 09 29 08](https://issues.joomla.org/uploads/1/33da723c90232e3ee7fadbe91f060ba0.png)

**Comment by chmst** [comment]
Thank you, this is a known issue and will be implemented soon.

**Comment by brianteeman** [comment]
Or you can fix it today by setting the plugin to use the material fonts in the plugin options as I doubt it will be fixed any time in the next 6 months

**Comment by sandewt** [comment]
> Thank you, this is a known issue and will be implemented soon.

Can you use help?

**Comment by sandewt** [comment]
> Or you can fix it today by setting the plugin to use the material fonts in the plugin options 

Thanks for the suggestion. Done.

**Comment by sandewt** [comment]
Closing, see pr  #39615.
