### ISSUE TITLE
debug user permissions

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38830]
This problem arises from #37807 by @chmst

### Steps to reproduce the issue
select a user debug permissions
in the filter options select start level 5 and send level 6

### Expected result
no idea really as I have no idea what level 4,5,6 are supposed to do but at a minimum there should be no errors

### Actual result
```

Warning
: Undefined array key 0 in
administrator\components\com_users\tmpl\debuguser\default.php
on line
40


Warning
: Attempt to read property "checks" on null in
administrator\components\com_users\tmpl\debuguser\default.php
on line
40


Warning
: Trying to access array offset on value of type null in
administrator\components\com_users\tmpl\debuguser\default.php
on line
40

```

The error can be solved by changing line 40 to
`$check = isset($this->items[0]->checks[$name]);
`

But I suspect it is more than that else this code will never be reached with that change
https://github.com/joomla/joomla-cms/blob/b0088ce88aa0a680ebb7abc939abb6bcd552c324/administrator/components/com_users/tmpl/debuguser/default.php#L53-L57

**Comment by chmst** [comment]
please test https://github.com/joomla/joomla-cms/pull/38960
