### ISSUE TITLE
Installation error : "A Database error occurred."

### ISSUE THREAD

**Issue by abhiquiet** [joomla/joomla-cms#38839]
### Steps to reproduce the issue
OS - Ubuntu 20.04
PHP 7.4.3 (cli) (built: Aug 17 2022 13:29:56) ( NTS )
Mysql Server - Already installed and running various other databases on separate server - Version 5.7
Mysql Client installed is  version 8.0
Joomla Version 4.2.2
Apache2 - Server version: Apache/2.4.41 (Ubuntu)

The Webserver is fresh installation with latest update and upgrade. 

After installing the pre-requisites, I started the installation and filled in the basic details and database connections. 

I am able to connect the database from the server from commandline. 

But, when I proceed with Joomla installation, I am getting the A Database error occurred. 

Note :- separate database created for joomla installation. 

I am not able to view the logs for the errors further. 

Kindly help me with the installation in case I am missing somehting. . 

Regards

Abhinav Aggarwal

**Comment by abhiquiet** [comment]
@joomla-cms-bot 

This is basic installation error. 

No logs available, hence no code attached.

**Comment by N6REJ** [comment]
are you sure you used the right name for the database connection?  It's probably NOT localhost

**Comment by abhiquiet** [comment]
It was my bad. 
I realised that the error shown is different from the actual error. 
I digged in the errors reported in the browser developer tools. 
The main error was relating to the CORS. 
When I changed the name of my site based on the url, it proceeded smoothly and I completed my installation. 
Thanks for the support.
