### ISSUE TITLE
[4.2] Banner, User Notes: Category:Edit show button 'Associations' but the extensions does not support multilingual associations

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#38837]
### Steps to reproduce the issue

1. open a category in banner or user notes
2. click on button 'Associations'
3. a 404 is shown (example com_banners):
<img width="500" alt="Banner 404 button Associations" src="https://user-images.githubusercontent.com/89642616/192248874-f2341e34-0cf0-47f3-98b2-3837acca26ce.png">

### Expected result
Extensions not supporting multilingual associations don't show button 'Associations'.

### Actual result
Extensions not supporting multilingual associations show button 'Associations'.

### System information (as much as possible)
![grafik](https://user-images.githubusercontent.com/89642616/192248330-25a7a7e3-e6be-41bc-a8a3-ea2ca659e611.png)

**Comment by brianteeman** [comment]
Confirmed

**Comment by alikon** [comment]
please test #38889
