### ISSUE TITLE
4.2.2 Settings Content structure Search index is overwritten when the index is rebuilt

### ISSUE THREAD

**Issue by WM-Loose** [joomla/joomla-cms#38838]
### Steps to reproduce the issue
If I adjust the content structure and e.g. deactivate language or categories, these options are hidden in the frontend in the advanced view in the search. But if I run the indexing, the deactivated contents of the content structure are simply activated again and displayed in the frontend.

### Expected result
It also has nothing to do with manually rebuilding the index. An automatic re-indexing could be the cause, but where should one be able to set that in Joomla? Maybe a plugin does this (suspicion OSMap but I can't find anything about automated index creation in the sitemap settings).

### Actual result
I still cannot understand why after a certain time the hidden parameters such as author, language, etc. are simply displayed again in the frontend in the advanced search.

### System information (as much as possible)
J4.2.2 /PHP8.0 /MariaDB

### Additional comments
![1](https://user-images.githubusercontent.com/99647423/192250648-2f34a24b-f2cc-41f1-91fb-9503ad712b98.png)
![2](https://user-images.githubusercontent.com/99647423/192250650-ec4632ca-d8be-4ee2-a3ed-7fabcf15fd62.png)

**Comment by WM-Loose** [comment]
Even with the new version Joomla 4.2.4 this problem is still not solved. 
Please let me know when you can expect a solution. 
Thanks

**Comment by Hackwar** [comment]
This has been fixed for 5.0 with #39961 and  #39944
