### ISSUE TITLE
unable to upload image with .jpeg extension

### ISSUE THREAD

**Issue by webfeuerflo** [joomla/joomla-cms#38833]
### Steps to reproduce the issue
Upload image with .jpeg file-extension in the media manager

### Expected result
file is uploaded

### Actual result
error message "an error occured"

### System information (as much as possible)
joomla 4.2.2, PHP 7.4.30

### Additional comments
You can fix this by adding "jpeg" in the media manager options under "Legal Image Extensions (File Types)". It should be there by default, I think

**Comment by Abernyte-Git** [comment]
It is listed as default in Media options in J4.2.3 rec2-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38833">issues.joomla.org/tracker/joomla-cms/38833</a>.</sub>

**Comment by brianteeman** [comment]
it has been the default fpr a very long time

**Comment by webfeuerflo** [comment]
> 

on a new joomla installation it is not. it just has "bmp,gif,jpg,png,svg" as legal image extension. jpeg is allowed in file types but not as image type

**Comment by Abernyte-Git** [comment]
New installation of J4.2.3 rc2
![screen shot 2022-09-26 at 10 11 09](https://issues.joomla.org/uploads/1/458eabd594dd0cfddcf3f4412d7e9a81.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38833">issues.joomla.org/tracker/joomla-cms/38833</a>.</sub>

**Comment by webfeuerflo** [comment]
great, thank you

**Comment by brianteeman** [comment]
I dont know where you are getting your download from but jpeg is part of the legal image extensions on a clean install of all versions released of Joomla 4

**Comment by webfeuerflo** [comment]
that's interesting, than it might have something to do with updates from previous versions, where it doesn't get added

**Comment by brianteeman** [comment]
found it. joomla 3 did not have jpoeg in the list and we dont modify that file on upgrade

**Comment by webfeuerflo** [comment]
great, so this will be added?

**Comment by brianteeman** [comment]
No. we can't change a users settings

**Comment by webfeuerflo** [comment]
ok, but thanks and good to know
