### ISSUE TITLE
[4.1] Debug mode deprecation warning in PHP 8.1

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#38847]
### Steps to reproduce the issue

Using PHP 8.1 set Debug System to Yes and in the System - Debug plugin set Refresh Assets to No.

### Expected result

Nothing unusual!

### Actual result

In Site and Administrator screens, above the Joomla banner there is a Warning that reads:

Deprecated
: strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in
/Users/username/Sites/j4xdemos/libraries/src/Document/Document.php
on line
762

### System information (as much as possible)

MacOS Catalina / Firefox / Apache 2.4 / MySQL / PHP 8.1.9

### Additional comments

Quite an annoyance!

**Comment by Fedik** [comment]
Please test #38848
