### ISSUE TITLE
Module uninstallation error :  Undefined constant "JPATH_" 

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#38840]
### Steps to reproduce the issue

Install module and then uninstall it.

### Expected result

Succesfull installation.

### Actual result

Get error  Undefined constant "JPATH_" 

1 ()                       JROOT\libraries\src\Installer\Adapter\ModuleAdapter.php:370
2 constant()       JROOT\libraries\src\Installer\Adapter\ModuleAdapter.php:370
3 Joomla\CMS\Installer\Adapter\ModuleAdapter->loadLanguage()    JROOT\libraries\src\Installer\Adapter\ModuleAdapter.php:525
4 Joomla\CMS\Installer\Adapter\ModuleAdapter->setupUninstall()    JROOT\libraries\src\Installer\InstallerAdapter.php:1150
5 Joomla\CMS\Installer\InstallerAdapter->uninstall()    JROOT\libraries\src\Installer\Installer.php:875
6 Joomla\CMS\Installer\Installer->uninstall()    JROOT\administrator\components\com_installer\src\Model\ManageModel.php:262 

### System information (as much as possible)

PHP 8.1

### Additional comments

Happens with a number of modules from the same developer, guess its likely to be a problem with their manifest but not investigated further.

Still com_installer should detect and handle such errors more gracefully.

**Comment by AByakugans** [comment]
I have the same problem with uninstallation of several modules like AcyMailing or VirtueMart 4+ I am on Joomla 4.2.3 what happened in the latest updates in the core?

**Comment by BrainforgeUK** [comment]
Tracked it down to needing _client="site"_ in the manifest file.
Some older modules from 3rd parties don't include that

`<extension type="module" client="site" method="upgrade" version="2.5">
`

Still com_installer should handle such issues more gracefully.
No time at the moment to make such changes.

**Comment by AByakugans** [comment]
So how can we fix that in already installed modules for instance? Can you give us step-by-step workaround? Thx

**Comment by BrainforgeUK** [comment]
I have made a change and submitted a pull request..

https://github.com/joomla/joomla-cms/pull/38891

**Comment by richard67** [comment]
> I have made a change and submitted a pull request..
> 
> #38891

@BrainforgeUK You could have closed your issue because we close zutuest as soon as there is a PR to solve it. Please remember next time. Closing now.
