### ISSUE TITLE
[4.2] Dashboards for third party extensions break when Unicode Aliases is toggled in Global Configuration

### ISSUE THREAD

**Issue by nikosdion** [joomla/joomla-cms#38849]
### Steps to reproduce the issue

* Install a new site.
* Install an extension with a custom Dashboard, e.g. https://www.akeeba.com/download/arsdev/7-1-0-dev202209271443-revc1215dcb.html

**TEST 1**

* Go to System, Global Configuration, Site.
* Set Unicode Aliases to No (that's the default).
* Click on Save & Close.
* Go to extension's dashboard (e.g. Components, and click the dashboard icon next to Akeeba Release System)

**TEST 2**

* Go to System, Global Configuration, Site.
* Set Unicode Aliases to Yes.
* Click on Save & Close.
* Go to extension's dashboard (e.g. Components, and click the dashboard icon next to Akeeba Release System)

### Expected result

**Test 1**: The dashboard is shown
**Test 2**: The dashboard is shown

### Actual result

**Test 1**: The dashboard is NOT(!!!) shown
**Test 2**: The dashboard is shown

### System information (as much as possible)

Irrelevant.

### Additional comments

This is yet another blatant bug in Joomla 4 which is trivial to spot and fix — if someone actually uses the Joomla 4 features 😢 

The problem lies in https://github.com/joomla/joomla-cms/blob/f520c98c64efb538e70e918acffb60d07e4d6b1e/administrator/components/com_cpanel/src/View/Cpanel/HtmlView.php#L64 The com_cpanel component's HtmlView converts the component specific dashboard (which must be provided as `com_example.something`) to a module position by putting that dashboard string through `\Joomla\CMS\Application\ApplicationHelper::stringURLSafe`.

However, what `stringURLSafe` does depends on the “Unicode Slugs” setting in Global Configuration 🤦🏽 

When that setting is No the underscore is converted to a dash, therefore the module position for this dashboard is `cpanel-com-example-something`.

When that setting Yes the underscore remains as is, therefore the module position for this dashboard is `cpanel-com_example-something`.

Since a module cannot be published in two positions at the same time the Dashboard breaks depending on the Global Configuration “Unicode Slugs” setting. 

You do not see that with core dashboards _because Joomla cheats when it comes to itself!_. Instead of using component-specific dashboards it uses hardcoded dashboard names which do not include the `com_` prefix or a dot, they just contain lowercase characters a-z without diacritics. When this happens, going through `stringURLSafe` returns the string verbatim, therefore Joomla's cheating dashboards always work.

### Proposal

Right now, there is not one valid module position to use with component-specific dashboards. The only reasonable solution is to replace
```php
$position = ApplicationHelper::stringURLSafe($dashboard);
```
with
```php
$position = \Joomla\CMS\Filter\OutputFilter::stringUrlUnicodeSlug($dashboard);
```
This way we will have predictable dashboards which always use the module position format `cpanel-com-example-something`.

Tagging @laoneo because his bug report in my repo led me to discover the root cause of this issue (as you may have guessed, being Greek I use Unicode Slugs on my multilingual dev site…) and because he's in the leadership so he can make a decision about how to best fix this.

**Comment by laoneo** [comment]
I didn't dig too deep into the code, but from what you describe it sounds like a legit change. As it affects only the admin dashboard view it looks like that nothing will break as it doesn't work correctly anyway.

**Comment by Fedik** [comment]
I think it should be compatible with the Modules position field https://github.com/joomla/joomla-cms/blob/99e177df5635ff376df0c314a396aa7c751f8c62/administrator/components/com_modules/forms/module.xml#L86-L93

Wich have a filter `string` in default. https://github.com/joomla/joomla-cms/blob/f520c98c64efb538e70e918acffb60d07e4d6b1e/libraries/src/Form/FormField.php#L1115

https://github.com/joomla/joomla-cms/blob/f520c98c64efb538e70e918acffb60d07e4d6b1e/libraries/src/Filter/InputFilter.php#L128

**Comment by nikosdion** [comment]
@Fedik Check my PR https://github.com/joomla/joomla-cms/pull/38853  It does that now.

The dashboard URL parameter first goes through Input's getCmd, then goes through OutputFilter::stringURLSafe. This means we end up with alphanumeric and dash because of https://github.com/joomla/joomla-cms/blob/f520c98c64efb538e70e918acffb60d07e4d6b1e/libraries/src/Filter/OutputFilter.php#L96

**Comment by Fedik** [comment]
Okay, then I will close here, because we have a PR
