### ISSUE TITLE
[4.2] type values are not translated in com_finder search result

### ISSUE THREAD

**Issue by tecpromotion** [joomla/joomla-cms#38846]
### Steps to reproduce the issue

Install some languages and activate them alternately for the frontend.
Search for content, tags, contacts etc. in the search (com_finder).
The word type is translated but the value of the type always remains the same.

The language strings do not need to be revised as they are already maintained.

### Expected result

All strings are translated.

### Actual result

e.g. for Article

Frontend English (en-gb):
![2022-09-27_14-38-49](https://user-images.githubusercontent.com/1752513/192528621-b394081a-ce44-448a-a676-f4aecbc3fb06.png)

Frontend German (de-de):
![2022-09-27_14-40-33](https://user-images.githubusercontent.com/1752513/192528913-c08c08a3-5647-48a8-b416-aaf6bcb17ef2.png)

Frontend French (fr-fr):
![2022-09-27_14-41-33](https://user-images.githubusercontent.com/1752513/192529162-f4a2c6dd-f66e-4c84-87ef-da4aae630d1d.png)

Frontend Danish (de-de):
![2022-09-27_14-42-38](https://user-images.githubusercontent.com/1752513/192529369-ec085510-a921-44ee-bcc7-7e978cf574d7.png)

All Strings are in english, no matter which language was chosen for the frontend.

### System information (as much as possible)

4.2.2

### Additional comments

@Hackwar see
https://github.com/joomla/joomla-cms/blob/f520c98c64efb538e70e918acffb60d07e4d6b1e/administrator/components/com_finder/src/Helper/LanguageHelper.php#L57-L67

**Comment by cyrezdev** [comment]
Hi there,
Same for me, and as i was looking to open a PR to fix it, if none already opened, i will linked this one to this issue report.

**Comment by cyrezdev** [comment]
A PR is opened and ready for testers: https://github.com/joomla/joomla-cms/pull/39353

;-)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39353 . Thanks in advance.
