### ISSUE TITLE
Joomla 4 - save button disappear after migrating ftom J3  

### ISSUE THREAD

**Issue by maxclee-tt** [joomla/joomla-cms#38845]
### Steps to reproduce the issue

Mirgation from last joomla 3 to 4 
System is stable, no errors, nothing, but simply save button disappear 

### Expected result

Can't save changes 

### Actual result

Can save changes

### System information (as much as possible) 

Only warring message is  : 
 
 WarningThe PHP temporary folder is not set.
This folder is the folder that PHP uses to store an uploaded file before Joomla can access this file. Whilst the folder not being set isn't always a problem, if you are having issues with manifest files not being detected or uploaded files not being detected, setting this in your php.ini file might fix the issue.

its nonsense as far I see 

### Additional comments

Please Help  !

**Comment by brianteeman** [comment]
please use the forum for support https://forum.joomla.org

**Comment by HLeithner** [comment]
Not sure which save button you mean and I think it's not a core issue (since we daily save things^^) as brain sad please ask the forum.

I'm closing this for now, if you think that's an error you can always reopen the issue.
