### ISSUE TITLE
J4 Cassiopeia allows the use of fonts.googleapis.com / GDPR issue

### ISSUE THREAD

**Issue by schultz-it-solutions** [joomla/joomla-cms#38855]
### Steps to reproduce the issue
Joomla4: open "edit templates styles" (in Administration). 
Select "Cassiopeia"
switch to "Advanced" tab
click on "Fonts scheme"

### Expected result
Selectable options should be GDPR compliant

### Actual result
without warning, it is possible to select "Fonts from web" (which results in loading the fonts from Google Fonts API).
This creates a GDPR violation (currently only in Germany, but Austria and other countries might follow soon), and the website owner is not even informed about this.

### System information (as much as possible)
Joomla 4.2

### Additional comments
Either remove the "Fonts from web" option, or replace it with a GDPR compliant solution (e.g. host the fonts on a Joomla server located within the EU).
It could also be a solution to warn the user about a possible GDPR violation, and leave the decision to him.

**Comment by brianteeman** [comment]
> Selectable options should be GDPR compliant

The entire world is not governed by a crazy law in Germany.

> and the website owner is not even informed about this.

Yes they are. At least in english - I can't speak about the german language translation/.

#
![image](https://user-images.githubusercontent.com/1296369/192725352-c4698d42-3196-4c0a-829a-2f8a5d2658d4.png)

**Comment by schultz-it-solutions** [comment]
"The entire world is not governed by a crazy law in Germany." 
I fully agree with you here. However the issue is not "a crazy law in Germany", but rather a very strict interpretation (by a german court) of an EU wide regulation (the regulation being already mirrored in many parts of the world).

I actually did not recognize the message below the field, sorry!
