### ISSUE TITLE
danger Invalid field: Minimum Password Length

### ISSUE THREAD

**Issue by galamarco** [joomla/joomla-cms#38859]
### Steps to reproduce the issue
go to administrator/index.php?option=com_config&view=component&component=com_users
save without changing anything

### Expected result
Save the setting without error

### Actual result
the error "danger Invalid field: Minimum Password Length" will be displayed

### System information (as much as possible)
Joomla ![screen shot 2022-09-28 at 17 17 52](https://issues.joomla.org/uploads/1/1b493da0fe17309ae3f6ce76d4b595c2.png)4.2.3

**Comment by HLeithner** [comment]
Joomla needs at minimum 8 characters for the password length. That's expected behaviour. If I understood your issue wrong please reopen the issue.

**Comment by galamarco** [comment]
I agree on the choice of 8 characters but then, when migrating from joomla 3 to joomla 4 this parameter must be automatically changed to respect the criteria that the CMS itself wants and verifies.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38859">issues.joomla.org/tracker/joomla-cms/38859</a>.</sub>

**Comment by alikon** [comment]
i don't think so...
the site  admin should do a deliberate choiche not the end user
i still run a migrated site from 3 to 4 
with the same psw 
please don't kill me , i'm lazy ;)

**Comment by webmasterab** [comment]
I had the same today.

I migrated a Joomla 3 website to Joomla 4.
The password length was set to 6 in Joomla 3.

When I wanted to add an email domain to the users, I kept getting the message of password length is not correct.

I did not understand that and after a consultation on mattermost we came to the conclusion that the length should not be 6 but should be at least 8.

Please note that this is not stated in the message.
You only see that something is not right, but you do not see what is not right.
The message must then be that the length must be at least 8.

Translated from Dutch with Google<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38859">issues.joomla.org/tracker/joomla-cms/38859</a>.</sub>
