### ISSUE TITLE
FileSystem Local breaks Media view when custom directory removed

### ISSUE THREAD

**Issue by QuotesUK** [joomla/joomla-cms#38866]
### Steps to reproduce the issue
Add custom directory to Media with FileSystem Local
Delete directory

### Expected result
Graceful removal from Media view

### Actual result
An error has occurred message instead of Media view

### System information (as much as possible)
Joomla 4.2.3

### Additional comments
Reversible by recreating custom directory
Avoidable by removing custom directory with FileSystem Local first
<img width="534" alt="Screenshot" src="https://user-images.githubusercontent.com/3391399/193078804-ef86979f-6b68-4231-874a-e4da16c97e06.png">

**Comment by brianteeman** [comment]
please test #38867
