### ISSUE TITLE
The cache in administration prevent debug

### ISSUE THREAD

**Issue by philigrane** [joomla/joomla-cms#38864]
### Steps to reproduce the issue
Joomla fresh install : 4.2.2
Phocagallery : 4.5.1

For exemple when i debug Phocagallery : 
go to images, edit one image and in  "Publishing options" insert a Tag in the field "Tag".
There is an error caused by the file managing the tags.
When i correct this in the file, the error, apparently, is not corrected.
I have to manually delete the "Autoload_PSR4.PHP" file in the administration cache so that everything works correctly.

**Comment by brianteeman** [comment]
sounds like an issue with the gallery. Have you asked the developer?

**Comment by philigrane** [comment]
Yes, it is a Gallery bug. I proposed my correction to the developer. 
My corrections were not taken into account.
I realized that this was not the case and that I had to delete the file "Autoload_psr4.php » each time the filesin the cache of the administration of Joomla

**Comment by brianteeman** [comment]
There is something seriously wrong if you need to delete that file.

**Comment by brianteeman** [comment]
This should be closed as its confirmed as a non core issue
