### ISSUE TITLE
User can't login in frontend if privacy consent is expired

### ISSUE THREAD

**Issue by galamarco** [joomla/joomla-cms#38861]
### Steps to reproduce the issue
in a website with "system - privacy consent" plugin activated
a user with privacy consent expired login in frontend
on edit-user-details.html page select "I agree" in autorization privacy policy and save

### Expected result
The consent is saved and the user is unlocked who can navigate, logged in, in the reserved area

### Actual result
The same page is reloaded, the consent is not saved and the user cannot browse a restricted area.

### System information (as much as possible)
Joomla 4.2.3

### Additional comments

![screen shot 2022-09-28 at 18 11 33](https://issues.joomla.org/uploads/1/fdbbe43993c933b3c41beb2941553274.png)

**Comment by drmenzelit** [comment]
Please check if the problem persists, when you switch to Cassiopeia. And check if your template is using an override for login / consent.

**Comment by galamarco** [comment]
Thanks for the analysis, I can confirm that changing the template in Cassiopea solves the problem. I report the problem to Yootheme support.

![screen shot 2022-09-28 at 18 11 33](https://www.mantrayogacentre.com/images/articoli/2022-10/Screenshot_72.png?1665127562418)

**Comment by alikon** [comment]
then close the issue please
