### ISSUE TITLE
LDAP auth does not work properly

### ISSUE THREAD

**Issue by albertmoreno** [joomla/joomla-cms#38865]
### Steps to reproduce the issue
I configured a working ldap just exactly how is working in some J3 sites i have, and it does not work as it worked in Joomla 3.5 and previous versions.

### Expected result
It does not authenticate the users

### System information (as much as possible)
The currently installed Joomla! version is "‎4.2.3"‎4.2.3
php 8.0.23
a2hosting

### Additional comments
Is it true that following and advice od a user, changing the line 134 of public_html/plugins/authentication/ldap/ldap.php
//$ldap->bind($ldap->escape($credentials['username'], '', LDAP_ESCAPE_DN), $credentials['password']);
by
$dn = str_replace('[username]', $credentials['username'], $this->params->get('users_dn', ''));
$ldap->bind($dn, $credentials['password']);

it works slow but it worls, but is not logical that i have to change core code, because it will be overwritten at every actualization.
ldap is simply and it a must

**Comment by alikon** [comment]
there are some pr about LDAP that need testing https://github.com/joomla/joomla-cms/pulls?q=is%3Apr+is%3Aopen+ldap

**Comment by tatankat** [comment]
@albertmoreno Please test #37959. This should fix your issue.
If it does, please go to the pull request in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/37959 and mark your test result by using the blue "Test this" button at the top left corner, selecting your test result and then submit. Thanks in advance. (quoting @richard67)

Once 2 persons have done this, the fix should be included in a coming version. For now, it apparently lacks human testing to be accepted...

**Comment by richard67** [comment]
Closing as there is a pull request.

**Comment by oleksand** [comment]
still no fix as of  Joomla 4.2.7

**Comment by richard67** [comment]
@oleksand It will be fixed in 4.3 with this merged pull request: https://github.com/joomla/joomla-cms/pull/37959 .
