### ISSUE TITLE
[4] set_time_limit() disallowed by hosting servce in PHP 8.1

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#38876]
### Steps to reproduce the issue

This is a report from a user that his hosting service has disallowed the PHP set_time_limit() function in PHP 8.1.

https://forum.joomla.org/viewtopic.php?f=808&t=996843

I have looked through the Joomla code and see that most calls are preceded by @ but one instance checks for the existence of the function. What we need to know is whether to treat this as a bug or to advise the user to move to a different hosting service.

**Comment by brianteeman** [comment]
The host simply does not understand the purpose of that function. Disabling it actually makes the issue they are trying to resolve worse.

**Comment by brianteeman** [comment]
Note that wordpress will also fail if that function is disabled

**Comment by Webdongle** [comment]
> I have looked through the Joomla code and see that most calls are preceded by @ but one instance checks for the existence of the function

Is that inconsistent?

**Comment by SharkyKZ** [comment]
>Is that inconsistent?

No. If it's accepted that `set_time_limit()` is the kind of function that could be disabled (which is very sensible for shared hosting), all instances should be wrapped in in `function_exists()` checks while still maintaining error suppression. This is because in PHP 8 calling a disabled function throws an `Error` which can not be suppressed, only caught. Previously only a warning was emitted.

**Comment by Webdongle** [comment]
so is `set_time_limit()` wrapped in `function_exists()` ?  If not is that what is causing the issue?

**Comment by SharkyKZ** [comment]
Yes, that's what's causing the issue.

**Comment by Webdongle** [comment]
So why has nobody edited the code in Joomla so that`set_time_limit()` is wrapped in `function_exists()` ?

**Comment by zero-24** [comment]
Could be it was not reported before that there are issues like this my hoster for example also dont block that. Feel free to create a PR or look where that calles are missing so someone else can take a look and do the PR :)

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/38876#issuecomment-1263241732
https://github.com/joomla/joomla-cms/issues/38876#issuecomment-1263443915

**Comment by ReLater** [comment]
2cents:

- Core code is trying to suppress the error by a nowadays unreliable/useless/error throwing `@` to avoid using `class_exists()`. Means: Programmers were aware that not all hosts support it and that it is just a nice-to-have at this code place.
- It's a Joomla bug that it doesn't work anymore like before.
- If we leave it as it is, `set_time_limit()` should be documented as a technical requirement of J!4. 
  - Joomla should not expect that hosts will change their server configuration.
  - As long we are talking about easily to fix things we shouldn't tell users that they have to change their hosting service.
- For the sake of consistency and code clarity `@` should be replaced in core code at several places.

BTW: Using `set_time_limit()` at this code place is a bit questionable from my point of view.

**Comment by Webdongle** [comment]
> ... Feel free to create a PR or look where that calles are missing so someone else can take a look and do the PR :)

If I could I would but that is beyond me.

**Comment by brianteeman** [comment]
see #41523
