### ISSUE TITLE
Usability: Category Filter subcategories

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#38881]
### Steps to reproduce the issue
In the menu item list, I can use the filters to select a parent menu item and thus jump to a sublevel in the menu item hierarchy, thus making the view clearer.
Go to Category List View, turn on the filters. 

### Expected result
When I search for the same function in the post category list view, I don't find it. This is a violation of the usability principle that like should work like.

### Actual result
no filter dropdown for category with subcategories

**Comment by reilldesign** [comment]
there was already a pull request #27486. this function is superfluous for pages with a lot of categories.

**Comment by brianteeman** [comment]
see #39950

**Comment by richard67** [comment]
Closing as having a pull request.Please test #39950 . Thanks in advance.
