### ISSUE TITLE
Custom list / sql fields allowing multiple selections - not user friendly

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#38886]
### Steps to reproduce the issue

Create a list / sql field allowing multiple selections

### Expected result

The list to be user friendly using chosen.

### Actual result

Standard HTML multiple select list displayed.

### Additional comments

Should there be another parameter 'chosen' in the field parameters next to 'multiple'?![screen shot 2022-10-01 at 13 15 20](https://issues.joomla.org/uploads/1/7e29fea5ae670a7f4c662c56ebaf25ee.png)![screen shot 2022-10-01 at 13 15 29](https://issues.joomla.org/uploads/1/d8a48f433a5d17930a21c1c75f9a6bd1.png)

**Comment by Fedik** [comment]
If you think that the standart `<select multiple>` input not user friendly https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select then better complain about it to WHATWG :wink: 

A tip: if you want to have a fancy select, use layout `layout="joomla.form.field.list-fancy-select"` for your List field.

I am closing it, as not an issue.

**Comment by BrainforgeUK** [comment]
Thanks,
On the options tab there are 2 layout options - one for form, the other for display.
The form one has an 'enhanced select' option - does what I want, I had not spotted it there.
