### ISSUE TITLE
J4 unable to do RewriteRule in .htaccess Report this postQuoteAccept this answer

### ISSUE THREAD

**Issue by vicn1222** [joomla/joomla-cms#38899]
### Steps to reproduce the issue

I copy htaccess.txt supplied by Joomla into .htaccess, then add line between
"## Begin - Custom redirects" and "## End - Custom redirects", as below

<PRE>
RewriteRule ^history/([^-]*)-?(.*).htm$ index.php?option=com_content&view=article&id=52&q=$1&page=$2 [NC,L]
</PRE>

My url is like
http://localhost/history/32456.htm, this return 404 "Page not found".

My investigation found it is in file libraries/src/Router/Router.php. If I comment out 
  throw new RouteNotFoundException(Text::_('JERROR_PAGE_NOT_FOUND'));

The ReWriteRule works. But then I never get "Page Not Found", even if a page really doesn't exists.

<PRE>
public function parse(&$uri, $setVars = false)
    {
        // Do the preprocess stage of the URL parse process
        $this->processParseRules($uri, self::PROCESS_BEFORE);

        // Do the main stage of the URL parse process
        $this->processParseRules($uri);

        // Do the postprocess stage of the URL parse process
        $this->processParseRules($uri, self::PROCESS_AFTER);
/*
        var_dump( $uri );
        var_dump( $uri->getPath() );
        die();
 */
        // Check if all parts of the URL have been parsed.
        // Otherwise we have an invalid URL
        if (\strlen($uri->getPath()) > 0) {
            //throw new RouteNotFoundException(Text::_('JERROR_PAGE_NOT_FOUND'));
        }

        if ($setVars) {
            $this->setVars($uri->getQuery(true));

            return $this->getVars();
        }

        return $uri->getQuery(true);
}
</PRE>

**Comment by richard67** [comment]
Your rewrite rule expects the part of the URL after the "history/" to have 2 parts, separated by a dash ("-"). The first part before the dash is $1 and the second part is $2 in the URL after rewrite. The dash is mandatory in the old URL in your rewrite rule, so if the URl has no dash at that place, the rewrite will not take place.

But the URL `http://localhost/history/32456.htm` does not have any dash in "32456.htm".

Are you really sure that your rewrite rule is right an working (without Joomla)?

**Comment by vicn1222** [comment]
Hmmm, don't know why my previous followup got lost. I will repost my fixes again.

Bellow is my fixes. Someone please review the codes and change as necessary? Thanks!

<pre>
    public function parse(&$uri, $setVars = false)
    {
        // Do the preprocess stage of the URL parse process
        $this->processParseRules($uri, self::PROCESS_BEFORE);

        // Do the main stage of the URL parse process
        $this->processParseRules($uri);

        // Do the postprocess stage of the URL parse process
        $this->processParseRules($uri, self::PROCESS_AFTER);

        // Check if all parts of the URL have been parsed.
        // Otherwise we have an invalid URL
        if ( \strlen( $uri->getPath() ) > 0 ) {
          $vars = $uri->getQuery(true);
          if ( array_key_exists( "Itemid", $vars ) ) {
            $table = \JTable::getInstance( "Menu" );
            $table->load( [ "id" => $vars[ "Itemid" ] ] );

            // trying to redirect to home page when getPath() is not empty, page doesn't exists!
            if ( $table->home == 1 ) {
              throw new RouteNotFoundException(Text::_('JERROR_PAGE_NOT_FOUND'));
            }
          }

        }

        if ($setVars) {
            $this->setVars($uri->getQuery(true));

            return $this->getVars();
        }

        return $uri->getQuery(true);
    }
</pre><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38899">issues.joomla.org/tracker/joomla-cms/38899</a>.</sub>

**Comment by Quy** [comment]
Closing in favor of #39916 which has additional info. Thanks.
