### ISSUE TITLE
Disable Fontawesome

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#38898]
### Steps to reproduce the issue
I am trying to dsiable fontawesome in a child template of cassiopeia as I'm using a different set of fonts.

From what I read adding the following should work
`$wa->disableStyle('fontawesome');`

### Expected result
joomla-fontawesome.min.css is not loaded

### Actual result
still loaded - because its a dependency of template.cassiopeia.ltr in joomla.asset.json

### Additional comments

1. Why is it a dependency?
2. If it needs to be a dependency is there a method in the web asset manager to disable it

**Comment by Fedik** [comment]
You have 2 option:
Override 'fontawesome' to emptiness `$wa->registerStyle('fontawesome', '')`
Edit `joomla.asset.json` and remove 'fontawesome' dependnecy for `template.cassiopeia` **style** asset, and add 'fontawesome' dependnecy to `template.cassiopeia` **preset** (And make PR, if you want).

> If it needs to be a dependency is there a method in the web asset manager to disable it

To keep track of correct dependency tree you have to override existing asset to asset with new dependencies. 
https://github.com/joomla/joomla-cms/blob/f520c98c64efb538e70e918acffb60d07e4d6b1e/libraries/src/WebAsset/WebAssetItem.php#L23

**Comment by brianteeman** [comment]
Thank you - the override works and seems to be the best option

**Comment by Chacapamac** [comment]
You should be able to unload fontawesome from Joomla by an available settings in Joomla interface.
