### ISSUE TITLE
Joomla menu aliases are wrong

### ISSUE THREAD

**Issue by gochitashvili** [joomla/joomla-cms#38901]
### Steps to reproduce the issue

Available Category:  **news**
Available Tags:  **politics**, **business**, **other**

**Available Menu items:** 
- News (menu type: category blog, category name: news, menu alias: news)
- Politics (menu type: category blog, category name: news, tag: politics, alias: politics)
- Business(menu type: category blog, category name: news, tag: business, alias: business)

### Expected result

Click any article inside News menu should go to LINK: example.com/news/some-news
Click any article inside Business menu should go to LINK: example.com/business/some-news
Click any article inside Politics menu should go to LINK: example.com/politics/some-news

Menu items ordering: News, Business, Politics

### Actual result

Click any article inside News menu is going to LINK: example.com/politics/some-news
Click any article inside Business menu is going to LINK: example.com/politics/some-news
Click any article inside Politics menu is going to  LINK: example.com/politics/some-news

if I change Menu items ordering: Business, Politics, News

Now all is going to /news links..

### System information (as much as possible)

PHP Version | 8.0.22
Joomla! 4.2.1 Stable
Apache Web server

**Comment by richard67** [comment]
That's how the router works in Joomlaas far as I know. Tags will not be a folder in the URL like categories are. So if I'm right, this issue should be closed as expected behavior. Maybe @Hackwar can explain it better and more detailed.

**Comment by Hackwar** [comment]
Indeed, this is expected behavior and rather a "false" setup from your side. If you want this to be distinguished, use subcategories. But tags aren't part of the URLs of a content item.

**Comment by richard67** [comment]
@Hackwar Thanks for clarifying.
