### ISSUE TITLE
Smart search highliter issue when searching for several words

### ISSUE THREAD

**Issue by pl71** [joomla/joomla-cms#38903]
### Steps to reproduce the issue
Site with module Smart search published. Indexed.
Publish Article "Foo" with text "Foo bar foobarfoo".
Smart Search for the same text: "Foo bar foobarfoo"
![foo](https://user-images.githubusercontent.com/4776779/193915028-f543bdf1-c7c4-45b4-82c8-63d041eee6da.PNG)

### Expected result

"Foo bar foobarfoo" to be highlighted, as in other popular search engines - with changed text colors only .

### Actual result

"Foo bar foobarfoo" is highlighted, but with added spaces between words as in the following screenshot:

![foo bar](https://user-images.githubusercontent.com/4776779/193916522-541113cf-8bbd-4dc3-9894-c18d2d9ffa34.PNG)

Devtools for the second ~~word~~ bar (EDIT: 'bar' inside 'foobarfoo'):
```
<mark data-markjs="true">
    <mark data-markjs="true">
        <mark data-markjs="true">
            <mark data-markjs="true">
                <mark data-markjs="true">
                    <mark data-markjs="true">
                        bar
                    </mark>
                </mark>
            </mark>
        </mark>
    </mark>
</mark>

```

### System information (as much as possible)

Joomla 4.2.3
PHP 8.1

### Additional comments

For larger articles text becomes almost unreadable.

**Comment by pl71** [comment]
Understood it is a mostly styling issue since the Cassiopeia template has padding which multiplies.

```
.mark, mark {
	background-color: #fbeea8;
	padding: .2em;
}
```
I can remove padding-left and padding-right,
But, nested marks remain...

**Comment by Fedik** [comment]
Looks like it is a highlighter bug, it should highlight a whole word, and only once, hm

**Comment by sandewt** [comment]
I confirm this bug. Highlighted words are broken.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38903">issues.joomla.org/tracker/joomla-cms/38903</a>.</sub>

**Comment by Fedik** [comment]
Please test #38908
