### ISSUE TITLE
[4.2.3] Order of items not always saved

### ISSUE THREAD

**Issue by wwwiiimmm** [joomla/joomla-cms#38910]
When rearranging the order of items the new possition is not always saved.

Tests so far:
- Joomla 4.2.3
- in the menu-items list, (filtered) articles list and featured articles list.
- in Safari and Firefox
- multiple people, different computers
- on localhost and servers of 2 different hosts
- clean Joomla + sample data

### Steps to reproduce the issue
1. In the backend go to any/a listpage (menu-items, featured articles with multiple items
2. Drag&drop up/down an item to rearrange it
3. Check frontend if item has moved
4. Repeat

Note: this issue may not happen all the time or on the first move.
You may need to repeat it.

### Expected result
Items are in the correct order.

### Actual result
When it happens it looks good in the BE, but when checking the FE nothing happened.
Refreshing the BE you'll notice the order is set back to what it was before you changed it.

### System information (as much as possible)
Joomla 4.2.3
PHP 8.0
Localhost/servers(Linux)/different webhosts

**Comment by HLeithner** [comment]
@Fedik any chance you have a look at this?

**Comment by Fedik** [comment]
Yeah, I can confirm the bug, after some time JS sends wrong order position.

Better way to reproduce:
Open sample data menus list for Top menu.
Drag "Fruit Shop" to:
3-d position, check frontend - position should change,
then drag to 5-th position, check froned - position stays 3-rd
Important: do not refresh the menu list page.

**Comment by Fedik** [comment]
Current work around: always reload the list page, after sorting changed.

**Comment by Fedik** [comment]
Please test #38935
