### ISSUE TITLE
[4.2.3] After upgrade - View Articles - categories are in the trashed, but not in the trashed.

### ISSUE THREAD

**Issue by mrownicki** [joomla/joomla-cms#38913]
### Steps to reproduce the issue
Upgrade 3.10.11 to 4.2.3
After migrating to Joomla 4, the categories are in the trashed, but not in the trashed.
Each category name in the articles view is as if it were in the trash. However, in categories it is visible normally. 

![screen shot 2022-10-06 at 14 19 50](https://issues.joomla.org/uploads/1/14559bd71f8ceed867c1c6406f998615.png)

If i in view articles and go to category show published.
View categories show published all.

Check ROOT is OK.
No override in admin view.
No plugin that might interfere.

Rebuild categories not working.
Move to trash and move to publish not working.

This is all symptoms bug :) 

### Expected result
View Articles - categories publish

### Actual result

View Articles - categories publish and this same in trash.

### System information (as much as possible)
Joomla 4.2.3 PHP 8.0

### Additional comments
I check in version 4.1.5 if show normal.
administrator/components/com_content/tmpl/articles/default.php

Problem starts on version 4.2.0

Im in not dev but maybe this is problem. Line 301 (Joomla 4.2.3)
```
if ($item->category_published < '1') :
echo $item->category_published == '0' ? ' (' . Text::_('JUNPUBLISHED') . ')' : ' (' . Text::_('JTRASHED') . ')';
endif;

```
Justin White say.
"seems like '1' and '0' should be numbers not strings"
https://www.facebook.com/groups/joomlanospam/permalink/10158537073975997/

**Comment by richard67** [comment]
> if ($item->category_published < '1') :
echo $item->category_published == '0' ? ' (' . Text::_('JUNPUBLISHED') . ')' : ' (' . Text::_('JTRASHED') . ')';
endif;

What happens if you change that line of code as follows?

```
if ((int) $item->category_published < 1) :
echo ((int) $item->category_published === 0) ? ' (' . Text::_('JUNPUBLISHED') . ')' : ' (' . Text::_('JTRASHED') . ')';
endif;
```

**Comment by brianteeman** [comment]
i would be very suprised if that was the cause of the problem as it has not changed

**Comment by chmst** [comment]
https://issues.joomla.org/tracker/joomla-cms/38673

**Comment by mrownicki** [comment]
@richard67 now show UNPUBLISHED
![image](https://user-images.githubusercontent.com/28987360/194482578-398dde53-ec12-402e-be4e-3b7e8795fe1d.png)

**Comment by alikon** [comment]
please continue on #38673
