### ISSUE TITLE
Captcha - Cloudflare Turnstile

### ISSUE THREAD

**Issue by joombler** [joomla/joomla-cms#38915]
Using currenctly Google Recaptcha v3, but would like to switch to Cloudflare Turnstile.
@ https://www.cloudflare.com/products/turnstile/

Is there a work around for that in J! 4.2.3 or do I have to make an official request for this?

**Comment by nikosdion** [comment]
As a contributor to the project, I will tell you what I have been told several times in the past: the Joomla project does not accept and will not implement features which rely on third party services.

Most recently, when I submitted the Multi-factor Authentication feature, I could not include my (already written and used in production) plugins for sending a six-digit code by PushBullet or the SMSAPI.com service as they relied on these external, third party services.

This policy was created before Joomla 3.2 and exempts any features which were already present. reCAPTCHA integration predated the policy so it's still maintained and distributed with Joomla.

I would recommend checking with a third party developer who has already created CAPTCHA plugins for Joomla and ask them if they are interested in creating a plugin for CloudFlare Turnstile.

**Comment by brianteeman** [comment]
a plugin for cloudfare turnstile already exists https://github.com/SharkyKZ/joomla-turnstile-plugin

i have not tested it etc i just saw it in my feed

**Comment by joombler** [comment]
Thanks, the author already has responded tool. I am not a programmer and for sake of security I'd rather await the come out of its functionallity before implementing it. Of course no offense meant to the creator of the pluging.
I do remember the start of the J! project, a long time ago. In those days J! was by its users and for its users. These days seem to have passed unfortunately...

**Comment by joomdonation** [comment]
As answered above, this feature would not be implemented in core. Please use the recommended third party plugin instead. I'm closing this issue.
