### ISSUE TITLE
[4.2] Unused code in User.profile plugin

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#38912]
### Steps to reproduce the issue

View the code.
The $key variable is not used.

### Expected result

Possible code modification.

### Actual result
These code is not used:
https://github.com/joomla/joomla-cms/blob/881fc6ce36f9699688d0015290b4509d3e73c16a/plugins/user/profile/profile.php#L369-L371

### System information (as much as possible)

J4.2

### Additional comments

None.

**Comment by Fedik** [comment]
It in use, look carefully :wink:

**Comment by sandewt** [comment]
> It in use, look carefully

Indeed, it took some searching :smiley:
