### ISSUE TITLE
Problem saving configuration in some components

### ISSUE THREAD

**Issue by djandressolano** [joomla/joomla-cms#38924]
### Steps to reproduce the issue

With Joomla 4, when you are in a particular component and change any configuration then save it, but when you come back to the configurations in the component, the change has not been made. 

this only happens with components that have their own save button also with all the configurations of the component  

components that use the joomla save button don't have that problem

![screen shot 2022-10-09 at 05 09 00](https://issues.joomla.org/uploads/1/1eb7e73e77f5d8513b205af26815c172.jpg)

**Comment by HLeithner** [comment]
I would expect this is not a core issue if a component does it own thing? please contact the extension developer.

I'm closing this for now, if you think it's a core issue please elaborate where you see the issue in core.

Thanks
