### ISSUE TITLE
No preview of WebP files in Templates: Edit Style

### ISSUE THREAD

**Issue by pl71** [joomla/joomla-cms#38923]
### Steps to reproduce the issue

Administrator - System - Site Template Styles 
Select 'Cassiopeia - Default'
Tab Advanced
Brand - Yes
Logo - Select any file of type webp.

### Expected result

Image to have a preview next to Logo, same as jpg files.

### Actual result

No preview.
![WebP preview](https://user-images.githubusercontent.com/4776779/194727175-95356c51-ab2e-41b5-a880-7ebe6f5f2bfe.PNG)

The subject file can be used as a logo, the only inconvenience is that there is no preview.

### System information (as much as possible)

Joomla 4.2.3
webp is included in Legal Image Extensions (File Types) in System Configuration - Media

**Comment by brianteeman** [comment]
That is not the core media field. You have an extension installed that is replacing the core media field. the core media field will happily display webp images

![image](https://user-images.githubusercontent.com/1296369/194727953-361159e1-2130-4258-9048-8b9b1e8b01f8.png)

**Comment by pl71** [comment]
Yes, you are right. The pure Joomla installation has no such defect.

**Comment by pl71** [comment]
Webp image appeared in **Edit menu item/Link Type/Link Image** only after adding
`webp` to **Global Configuration/Media/Legal Image Extensions (File Types)** and updating **Legal MIME Types** there.
I haven't played with these settings since the initial install with Joomla 3.
So I suppose WebP functionality was added somewhere in Joomla 4 and these settings remained unchanged.
Do Joomla update packages include checking here?

**Comment by brianteeman** [comment]
> Do Joomla update packages include checking here?

No. As you may have edited the settings here we dont touch them on an update
