### ISSUE TITLE
[SOLVED] Property 'mime_type' has a wrong item

### ISSUE THREAD

**Issue by joombler** [joomla/joomla-cms#38925]
Dear team,
Just saw in Content -> Media this message:
Error
Property 'mime_type' of argument 'item' of event onFetchMediaItems has a wrong item. Valid: string

Running Apache24 on Joomla 4.2.3 on FreeBSD 13.1
Found a lot of suggestions, but unfortunately no solution to this. Can you advise how to solve?
Thanks, jos

**Comment by joombler** [comment]
I solved the issue by installing the latest version of php80-fileinfo-8.0.24
Thanks anyway for letting me put the issue in this informative community. Keep up the good work.

**Comment by chmst** [comment]
Thanks for information, I close this issue.
