### ISSUE TITLE
Cassiopeia template is violating local font configuration

### ISSUE THREAD

**Issue by RichardZimmerEschborn** [joomla/joomla-cms#38932]
### Steps to reproduce the issue
Install Joomla 4.2.3
Select Cassiopeia template
System -> Site Templete Styles -> Cassiopeia -> Advanced -> Font Sheme
Select Roboto (local)
There is a Warning that it might be illigal to load fonts from external sources.
Also activate the back to the top link.
Save configuration changes.
Now use FireFox Klar the secure version of FireFox to browse the Joomla website.

### Expected result
Expected to see Hamburger Symbol in minimized main menue (like on smart phone) and arrow pointing up at the end of the web page.

### Actual result
The Hamburger Symbol for the minimized main menue is not shown. Like it the symbol at the bottom of the webpage to scroll to the top is also not shown.

Now configure FireFox to NOT block external fonts and refresh the webpage. The Hamburger symbol and the scroll to top symbol are displayed. 

### Additional comments

So Cassiopeia still loads external fonts, even if local font is selected. This is also disturbing data protection rules, since the provider of the font might track who is loading the symbols.

I did not check if Cassiopeia is also accessing other external recources (like bootstrap or JavaScript), which would cause the same violation as the external font.

**Comment by brianteeman** [comment]
1. The icons you are referring to (back to top and hamburger) are loaded from fontawesome - they are **nothing** to do with the font settings in the cassiopeia template
2. the fontawesome font is loaded from the media folder of your site. 

Check the code and you will be able to confirm the above

From what you have written I think you have not understood the settings in your browser. The browser blocking web fonts setting means that no fonts are used in your browser except for those present on your own computer. By making this setting you are disabling any font from the web. That will also include the roboto font indicated as local in cassiopeia. Local does NOT mean local to your own computer. It means a font local to the web site. ie it is hosted in the same web space as the rest of the website as opposed to a font hosted on another server eg google, adobe etc

**Comment by RichardZimmerEschborn** [comment]
Thanks for clarifying this.

I scanned though the page as it is displayed in the browser and found only one reference to the outside. I am not shure if it actually does an internet access though.

<div class="com-content-article item-page" itemscope="" itemtype="https://schema.org/Article">

From the documentation at:
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/itemtype

It looks to me that itemtype is used by searchengines only to recognize what kind of information is contained in this block.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38932">issues.joomla.org/tracker/joomla-cms/38932</a>.</sub>

**Comment by brianteeman** [comment]
This can be closed as not a core issue.

**Comment by richard67** [comment]
Closing as not a core issue.
