### ISSUE TITLE
Menu Headings & Menu Seperator acting as links

### ISSUE THREAD

**Issue by southpaw3229** [joomla/joomla-cms#38938]
### Steps to reproduce the issue
visit https://golf-course-websites.com/DEV/trinidad/ and the main side nav is treating menu headings and menu seperators as links.  They confuse the visitor as they think they are links, but they should be menu sub headings.  Non clickable, non rollover, etc...  if you view GOLF > The Course > Golf Rates, you will see THE COURSE is treated as a menu item and it's a menu heading.

### Expected result
Non Clickable Menu Headings or Menu Seperators. 

### Actual result
Should not be clickable.

### System information (as much as possible)
Joomla 4.2.3
Astroid Framework Version: 2.6.1
Jollyany Version: 3.5.11
Medil Template Version 1.0.2 (purchased from https://www.templaza.com/

### Additional comments
Template Plaza support said this was a joomla 4 bug.  Just seeing what you all say.

Thanks in advanced.

**Comment by chmst** [comment]
This is the behaviour of your template, the astroid sidebar menu must have own css rules.

**Comment by richard67** [comment]
> Template Plaza support said this was a joomla 4 bug.

Have they provided any information about how they come to this conclusion?

**Comment by southpaw3229** [comment]
They have not and i suspect it was on there end.  Thanks for confirming.

**Comment by richard67** [comment]
Closing as not a core issue. Feel free to reopen it if it turns out that closing was wrong.

**Comment by southpaw3229** [comment]
Thanks Richard.


Bay

Bay Paul
CEO and Founder
CourseLogix
m: (248) 613-2816
w: Course-Logix.com
