### ISSUE TITLE
Joomla 3 crashes

### ISSUE THREAD

**Issue by vicn1222** [joomla/joomla-cms#38933]
When installing Joomla 3 in php 8 environment, Joomla crashes. I have found the bugs are in two files:

includes/framework.php
administrator/includes/framework.php

Where $config->error_reporting = "None", the switch below goes to default case

<PRE>
switch ($config->error_reporting)
{
        ......

	default:
		error_reporting($config->error_reporting);
		ini_set('display_errors', 1);

		break;

}
</PRE>

Where error_reporting( "None" ) throw exception as below
<pre>
PHP Fatal error:  Uncaught TypeError: error_reporting(): Argument #1 ($error_level) must be of type ?int, string given in ....
</p>

In php 7, it does not throw exception and program moves on...

**Comment by vicn1222** [comment]
No, I don't even know what is that value in configuration.php.

**Comment by vicn1222** [comment]
Interestingly, I re-save the configure.php using the admin control panel, it becomes "none". I don't know why that happened.

But still, it probably is better to use strtolower if lower case is expected. Especially the default case should be explicitly casted to int, knowing in php 8, exception will be thrown if the $config->error_reporting is a string

<PRE>
switch ( strtolower( $config->error_reporting ) ) {
...

    default:
        error_reporting( (int)$config->error_reporting );
        ini_set('display_errors', 1);

        break;

}
</pre><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38933">issues.joomla.org/tracker/joomla-cms/38933</a>.</sub>

**Comment by Fedik** [comment]
I think, we can leave it as it is. 
When there a wrong value then it should crash and burn, so owner will know he/she (or 3rd extension) doing something wrong with configuration.

**Comment by HLeithner** [comment]
So not a core problem and we can close this issue. Thanks for the report.
