### ISSUE TITLE
[4] Templates: Customise Documentation link

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#38943]
### Steps to reproduce the issue

Go to System / Site Templates / Cassiopeia Details and Files
Select the Documentation button - it links to https://docs.joomla.org/J3.x:How_to_use_the_Template_Manager

I have rewritten the Documentation so the link should now be https://docs.joomla.org/J4.x:Template_Overrides

### Expected result

J4 Documentation

### Actual result

J3 Documentation

### Additional comments

I have been revising the documentation for Joomla 4 to make it more useful in the context of an Index. This is just one of a group of articles on Templates - links at the bottom and more to do.

**Comment by brianteeman** [comment]
pull request done.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38944 . Thanks in advance.
