### ISSUE TITLE
TAGS Batch for organisation tag structure

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#38942]
### Steps to reproduce the problem
We want to organise tags using the batch function. We select several tags and open the "Batch" dialogue window.

### Expected result
Since tags are organised hierarchically just like posts, we expect to be able to edit this structuring using the batch function.

### Actual result
The Move Tags function is not available. (The only thing available for batch processing is the access level).

### System information (as far as possible)
J4.2.3, PHP 8.1

### Additional comments
This behaviour contradicts the usability principle that like works like. Therefore, this is not a feature request but a bug.

**Comment by chmst** [comment]
Please test this: https://github.com/joomla/joomla-cms/pull/38583

**Comment by richard67** [comment]
Closing as there is a pull request which claims to solve this issue. Please test #38583 . Thanks in advance.
