### ISSUE TITLE
TAGS Dropdown display: Missing Data

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#38940]
### Steps to reproduce the problem
We create tags (approx. 100). We open a post and want to assign tags to it.

### Expected result
In the dropdown 'Tags' all tags should be displayed.

### Actual result
Only a few (approx. 10 of >100) tags are listed in the 'Tags' dropdown.

### System information (as far as possible)
J4.2.3, PHP 8.1

### Additional comments
The error did not exist in version 4.1.5. It must be related to the changes in 4.2.

**Comment by chmst** [comment]
Are the tags in the sourcecode and not displayed or are they not found? Maybe you can add a screenshot?

**Comment by richard67** [comment]
Isn't that dropdown a fancy select (not at my desk now to check that) shows only a limited number of values but fetches more when you start to type a tag name?

**Comment by brianteeman** [comment]
Depends on the option in the component to show nested or ajax tags

**Comment by richard67** [comment]
Are the following issues related or is this here even a duplicate of one of these two? #38763 #37927

**Comment by brianteeman** [comment]
probably

**Comment by hytsch** [comment]
we open a new issue with screenshots. #39219

**Comment by richard67** [comment]
@hytsch And what to do with this issue here? Close it?

**Comment by chmst** [comment]
yes ... closing in favour of an new one https://github.com/joomla/joomla-cms/issues/39219
