### ISSUE TITLE
TAG assigned not saved

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#38941]
### Steps to reproduce the problem
We create tags. We open an article, select a tag and save the article.

### Expected result
The tag is assigned to the article.

### Actual result
The tag is NOT assigned to the article, the assignment is not saved.

### System information (as far as possible)
J4.2.3, PHP 8.1

### Additional comments
This misbehaviour is particularly annoying because a content manager assumes when saving+closing that his work has actually been saved, but in fact he is working "in the blue" without realising it.

**Comment by Hackwar** [comment]
I can't reproduce this. Assigning tags to an article works fine for me, both in PHP 7.4 and 8.1. Are you typing in the tag and don't press enter to confirm the tag or did you select the tag with the mouse? The tag will be shown as a small badge in the tag field when it is going to be saved.

**Comment by hytsch** [comment]
ok, we observe the following behaviour:
### Steps to reproduce the issue
The post already has tags, e.g. a tag "elections" is added. 
### Expected result and actual result
The tag is applied and still displayed after saving. After saving, the newly added tag "Elections" is displayed, but the previously existing tag "Agriculture" has disappeared. 

### System information (as much as possible)
joomla 4.2.5 (fresh installed), PHP 8.1

### Additional comments
Some of the tags that disappeared from the backend are displayed in the frontend. Similar error in several different posts, various tags affected. It affects both tags that are frequently used and tags that are rarely used. The hierarchy level (levels 1 and 2 have been used up to now) also seems to have no significance. The error is not always reproducible; there are posts for which a certain tag was not "taken" several times, but can then be added sometime later. It seems to be a problem with the display.

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/39254 should address this issue. Please help testing. Thanks !
