### ISSUE TITLE
Article Info Title is shown in Articles - Archive regardless of setting

### ISSUE THREAD

**Issue by pl71** [joomla/joomla-cms#38952]
### Steps to reproduce the issue
Set 'Article Info Title' to 'Hide' in Global Configuration inside 'Articles'
Set some articles in archive state.
Add module 'Articles - Archived' and open archived articles thru this module.

### Expected result

Article Info Title not shown

### Actual result
![screen shot 2022-10-13 at 10 10 29](https://issues.joomla.org/uploads/1/e2f0c33afcd26130cfe3101f93f049c9.png)
Article Info Title is shown

### System information (as much as possible)

Joomla 4.2.3
PHP 8.1.x

**Comment by brianteeman** [comment]
Please test #38953

**Comment by richard67** [comment]
Closing as having a pull request. Please test #38953 . Thanks in advance.

**Comment by brianteeman** [comment]
please test #44601
