### ISSUE TITLE
[4.2] com_modules / com_scheduler unfinished code

### ISSUE THREAD

**Issue by Flowman** [joomla/joomla-cms#38958]
### Steps to reproduce the issue

Just noticed that someone missed  "<?php somthing" in the data-function= part.

https://github.com/joomla/joomla-cms/blob/00813e7533f0015690ef177506f9ce077d61c3ac/administrator/components/com_modules/tmpl/select/default.php#L66

And as com_scheduler select is a copy of com_modules it has the same issue in the the select template. But its not used in the same way, as someone have removed the top $function code. Guess data-function= can be removed from here.

https://github.com/joomla/joomla-cms/blob/00813e7533f0015690ef177506f9ce077d61c3ac/administrator/components/com_scheduler/tmpl/select/default.php#L75

The modal view in com_scheduler select is useless to, as it is never used in core and just copied from com_modules.

### Expected result

Output correct HTML code.

### Actual result

Not the correct HTML code.

### Additional comments

Just some clean-up of core :)

**Comment by chmst** [comment]
Partial solution here https://github.com/joomla/joomla-cms/pull/38959

Still open: the file modal.php. Removing a file needs more actions. Please @richard67 could you take this part?

**Comment by chmst** [comment]
Completed the PR https://github.com/joomla/joomla-cms/pull/38959, please test.
