### ISSUE TITLE
Start and Finished featured article settings cleared when saving article at frontend

### ISSUE THREAD

**Issue by WoodyF4u** [joomla/joomla-cms#38961]
In Joomla 4 you can set at "Publishing" the settings for Start Featured and Finish Featured in the backend.
After saving it works well on the website.
But in article management on the frontend, these settings are not available.
When someone edits and saves an article on the frontend, the Start Featured and Finish Featured settings in the backend disappear.
Those fields are then empty again.
And therefore the scheduled featured articles no longer work.

### Expected result
The fields for scheduled featured articles in article management on the backend must also be added to article management on the frontend.
So that the same settings are kept in both places.

### Actual result
At this point, the settings made on the backend will be cleared when the article is edited on the frontend.

### System information (as much as possible)
Core Joomla 4

**Comment by drmenzelit** [comment]
Do your user have edit state permissions?

**Comment by WoodyF4u** [comment]
That is a good question. The user did not have the edit state permissions.
After I changed that, the fields in article management on the frontemnd were available.
Thanks for your suggestion.

But now I see that the values ​​set in the fields ion the backend are not shown on the frontend.
If someone now edits the article on the frontend and does so with those empty fields, then it is empty again on the backend.
Can you test that? I wonder if that's a bug in Joomla or if I'm forgetting something.

**Comment by alikon** [comment]
please test #38975
