### ISSUE TITLE
Joomla 4 closes shared javascript popup window without actually closing it.

### ISSUE THREAD

**Issue by vicn1222** [joomla/joomla-cms#38966]
In the attached test.html, as soon as I click Joomla, the previously created popup window got closed without actually closing the popup, causing new button click to create another popup window. All other clicks will share the same popup window.

**Comment by vicn1222** [comment]
Didn't notice test.html can't be attached. Rename to test.txt and try again.

Try to attach again..[test.txt](https://issues.joomla.org/uploads/1/e4673c7504a555e354224ca213bd310e.txt)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38966">issues.joomla.org/tracker/joomla-cms/38966</a>.</sub>

**Comment by brianteeman** [comment]
please use the forum for support

**Comment by vicn1222** [comment]
I think this is a bug, not a support issue.

I add 2 more buttons to open my own Joomla 3 & Joomla 4 websites. When opening my own Joomla 4 website, the behavior is identical to opening joomla.org website, that is, the previously created popup got closed without actually closing it, causing next button click to create a new popup. Opening Joomla 3 website doesn't have this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38966">issues.joomla.org/tracker/joomla-cms/38966</a>.</sub>

**Comment by vicn1222** [comment]
This has been fixed due to non policy conpliance of newly added "System - HTTP Headers" with following changes
<pre>
    $app = JFactory::getApplication();
    $app->setHeader( "cross-origin-opener-policy", "same-origin-allow-popups" );
</pre>

The issue is thus closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38966">issues.joomla.org/tracker/joomla-cms/38966</a>.</sub>
