### ISSUE TITLE
Custom Fields in Subforms: Calendar Field Display Errors

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#38969]
### What needs to be fixed
We have a custom field calendar in subforms, repeatable. Unfortunately, the display in the admin is poor: the data picker creates a scroll bar, and yet it is not visible.  

![image](https://user-images.githubusercontent.com/4489029/196008430-716a41aa-7a7f-4f28-a7ff-927a6d20dd5f.png)

### Why this should be fixed
A calendar filter cannot be used in its current state.

### How would you fix it
Admin Template CSS

### Side Effects expected

**Comment by Fedik** [comment]
Use non-table layout for subform
`joomla.form.field.subform.repeatable` instead of `joomla.form.field.subform.repeatable-table`

**Comment by Fedik** [comment]
hmhm you are right, there no such option for Custom field, unfortunately.
But in general it supported by subform field.

Need to add it, similar to `list` Custom field https://github.com/joomla/joomla-cms/blob/283f2b5656d0fc6dacaeac67239265af278ceef1/plugins/fields/list/params/list.xml#L44-L54

**Comment by crystalenka** [comment]
Yes, we need to add that too, but it covers up the symptom, not the problem.

I guess we may need to use our own solution for responsive tables in order to fix this but is that possible without a B/C break?

**Comment by brianteeman** [comment]
Will this help?

https://lea.verou.me/2012/04/background-attachment-local/

**Comment by richard67** [comment]
> I have come across this issue too. Duplicate of #38443

So either we have to close this issue here with reference to #38443 , or vice versa, close that other one and leave this here open.

So we have to decide which one we close and in which other one we continue the discussion.

@crystalenka What's your preference? Continue here? Or continue with your issue?

**Comment by crystalenka** [comment]
> So either we have to close this issue here with reference to #38443 , or vice versa, close that other one and leave this here open.
> 
> So we have to decide which one we close and in which other one we continue the discussion.
> 
> @crystalenka What's your preference? Continue here? Or continue with your issue?

Let's close this one and continue in mine, just because mine has a little more context with the source of the problem.

**Comment by richard67** [comment]
Closing as duplicate report. Let‘s continue in issue #38443 .
