### ISSUE TITLE
Extension sort-by-date causes Undefined property: stdClass::$creationDate

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#38970]
### Steps to reproduce the issue
system->extension manager-> click on date arrow

### Expected result
sorts date

### Actual result
While the date is sorted this error below occurs numerous times
```
Warning: Undefined property: stdClass::$creationDate in /home/bearsampp/public_html/libraries/vendor/joomla/utilities/src/ArrayHelper.php on line 602
```

### System information (as much as possible)

[systeminfo-2022-10-16T06_00_24+00_00.txt](https://github.com/joomla/joomla-cms/files/9793694/systeminfo-2022-10-16T06_00_24%2B00_00.txt)

**Comment by chmst** [comment]
Cannot replicate this in my installations. Probably one of your extension has a wrong value in creationDate. 
You could check the content $a here
public static function sortObjects(array $a, $k, $direction = 1, $caseSensitive = true, $locale = false)

**Comment by brianteeman** [comment]
Unable to replicate  - as @chmst says its probably an extension with an incorrect valaue.

**Comment by N6REJ** [comment]
not sure what an extension would have to do with date sorting.  No extension exists in that install that effects admin other then admintools

**Comment by N6REJ** [comment]
Could this be related?
![image](https://user-images.githubusercontent.com/1850089/196335206-6c41f5e2-0666-422d-b9bf-148d1057eae6.png)

**Comment by brianteeman** [comment]
yes

**Comment by richard67** [comment]
> not sure what an extension would have to do with date sorting. No extension exists in that install that effects admin other then admintools

As the extensions manager shows ALL extensions, it doesn’t matter if the extension is for admin or site. Any extension with a malformed date in its XML can cause that the list breaks, due to the poor error handling of the installer regarding XML files.

**Comment by Lumiga** [comment]
Hi N6REJ,

How did you fixed this issue?
We have no SimplifyYourWeb Extension
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38970">issues.joomla.org/tracker/joomla-cms/38970</a>.</sub>

**Comment by N6REJ** [comment]
The issue was left over from, improper extensions in the database.  I went thru the db, removed extensions that didn't belong there and then made sure there were no extensions with "level" less then zero.

**Comment by Lumiga** [comment]
Oké thanks, in my case Hikashop was the problem. See here: https://www.hikashop.com/forum/install-update/905225-extension-sort-by-date-causes-undefined-property.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38970">issues.joomla.org/tracker/joomla-cms/38970</a>.</sub>
