### ISSUE TITLE
[4] Edit user.css codemirror warning

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#38979]
### Steps to reproduce the issue

Go to System / Site Templates / Cassiopeia Details and Files
Create a New File / user.css in the css folder

### Expected result

Creation works OK but...

### Actual result

This message appears above the Edit box:

 Warning: Undefined property: stdClass::$readOnly in /Users/ceford/Sites/j4cms/plugins/editors/codemirror/layouts/editors/codemirror/element.php on line 41

### System information (as much as possible)

Cloned joomla-cms from repo, built with npm ci, installed 
PHP 8.1.9 

### Additional comments

Debug set to Yes and Error Reporting set to Maximum

**Comment by drmenzelit** [comment]
That is solved with https://github.com/joomla/joomla-cms/pull/38989
