### ISSUE TITLE
Searchbox with "script" as search term returns error 400 - Bad Request

### ISSUE THREAD

**Issue by betsco123** [joomla/joomla-cms#38988]
Front-end: 
Searchbox at top of my site (Search module placed in top-bar2) returns this:
400 - Bad Request
Your browser sent a request this server could not understand

...if the search term contains the word "script," like "description" or "prescription" or just "script."

It doesn't do it on the search page, just on the searchbox that is at the very top of all pages.

https://nnpstv.com/

Chrome, IE, and Firefox
Joomla 3.10.0

Any ideas why and how to fix it?

Thanks!

**Comment by brianteeman** [comment]
The error page is coming from your hosting and not from your web site.

Their is probably a misconfigured security script that is blocking the word script - you should speak to your web host

**Comment by betsco123** [comment]
brianteeman you are correct and they are fixing by whitelisting that word.  Thanks for the help!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38988">issues.joomla.org/tracker/joomla-cms/38988</a>.</sub>
