### ISSUE TITLE
'A read more &hellip; link' - fix localization

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#38991]
When attempting to insert ReadMore tag twice in article edit mode:
<img width="429" alt="Снимок экрана 2022-10-18 в 22 10 57" src="https://user-images.githubusercontent.com/3432048/196615984-d88a16eb-bc24-4091-8c91-2c507685a9da.png">

Maybe it is better to replace &hellip; ASCII code to triple ... symbols to avoid such little issue. 

Joomla 4.2.3

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39573 . Thanks in advance.
