### ISSUE TITLE
Adding a user with the username as an email address

### ISSUE THREAD

**Issue by sozzled** [joomla/joomla-cms#38997]
### Steps to reproduce the issue

This is more of a question rather than reporting an error.  Add a new user to the backend with the **username** as something like xxxxx@gmail.com.  Add the other fields as required and assign the user to the Registered group.  Save the user.

Attempt to login with this username and password

### Expected result

New account should not be created or, if it is, it should be possible to login with this username.

### Actual result

New account is created.  Attempt to login fails with "Username and password do not match or you do not have an account yet."

### System information (as much as possible)

J! 4.2.3

### Additional comments

If we should not be using email accounts as usernames (which I agree with)—see #29403—then the new account should not be created with some explanation about why email addresses cannot be used as usernames (unless someone has installed a third-party plugin that allows email addresses to be used as usernames in which case I don't know what you would do about that).

Low priority

**Comment by brianteeman** [comment]
I have no problem registering and logging in with an email address as a username. In any version of Joomla
![image](https://user-images.githubusercontent.com/1296369/196804236-cd8762d2-446e-44d1-9275-8d60ed8a9a26.png)

**Comment by sozzled** [comment]
Thanks, @brianteeman.  It was completely my error.  We can dismiss this as an issue.  

I do appreciate your help on this.  :relaxed:
