### ISSUE TITLE
rawurldecode(): Passing null to parameter in com_redirrect

### ISSUE THREAD

**Issue by sthibaut** [joomla/joomla-cms#38992]
### Steps to reproduce the issue

when com redirrect is in capture mode on a site under php 8.1 an error deprecated appears in each line of the url column the error is 
Deprecated: rawurldecode(): Passing null to parameter #1 ($string) of type string is deprecated in /home/public_html/administrator/components/com_redirect/tmpl/links/default.php on line 123

### Additional comments
it is fixed changing line 123 to
<?php echo $this->escape(rawurldecode($item->new_url ?? '')); ?>

**Comment by alikon** [comment]
please test #39005
