### ISSUE TITLE
?layout=list prefix in the URL for compact list of tagged items

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#38996]
Here is the structure:

1. menu item. domain.com/tags/
Tags. Compact list of tagged items
<img width="711" alt="Снимок экрана 2022-10-19 в 17 05 51" src="https://user-images.githubusercontent.com/3432048/196716346-4e1da557-3fa1-49aa-b6c0-738e3f7d42f2.png">

2. Settings. The menu item settings include various tags
 
<img width="1166" alt="Снимок экрана 2022-10-19 в 17 26 49" src="https://user-images.githubusercontent.com/3432048/196719483-bbedda76-73ff-46a3-b604-a1eb01c93ea0.png">

I use tags to navigate though tagged articles. There is no sense to make menu item for each tag since tagged items solves the task.
However, I noticed a little problem with router in breadcrumbs:

Home = domain.com/
Tags = domain.com/tags?layout=list
Tagged item = domain.com/tags/plugin

I suggest considering of removing **?layout=list** from the URL if a menu item exist. A change in Joomla router.
Joomla 4.2.3

Thank you.

**Comment by Hackwar** [comment]
#39114 should fix this. Please help testing that.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39114 . Thanks in advance.
