### ISSUE TITLE
custom fields on com_contact mail form

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39010]
### Steps to reproduce the issue
Create a contact and a menu link to display the contact
Create a custom field for contacts with the context mail 
![image](https://user-images.githubusercontent.com/1296369/197186391-b4d1859c-fd80-422f-9c63-b0ca429b9635.png)

The custom fields are rendered as a fieldset after the core fields eg
Name
Email
Subject
Message
CUSTOM FIELD

In all other places you can manually render the fields using

echo $field->renderField('name');

and then following the documentation at https://docs.joomla.org/J3.x:Adding_custom_fields/Overrides you can get each custom field.

So now I would be able to render the fields
Name
CUSTOM FIELD
Email
Subject
Message

### the problem

The documented method does not work in this context and I can't find out how to get the field to render.

Either there is a bug or there is missing documentation or Brian is missing a brain ?

cc @laoneo

**Comment by drmenzelit** [comment]
In the form you need to load the form elements not render the field:
`<?php echo $this->form->getLabel('contact_name'); ?>`
`<?php echo $this->form->getInput('contact_name'); ?>`

I wrote a blog (German) here: https://wicked-software.de/dynamisches-kontaktformular-mit-auswahlfelder

**Comment by brianteeman** [comment]
Thanks for the post

I can see now that you can render the field you just need to set the correct values - which I now have from your post
```
    <?php echo $this->form->renderField('contact_name'); ?>
    <?php echo $this->form->renderField('country', 'com_fields'); ?>
    <?php echo $this->form->renderField('contact_email'); ?>
```
