### ISSUE TITLE
[4.2.3] Modify options in select choices

### ISSUE THREAD

**Issue by JoomBall** [joomla/joomla-cms#39061]
### Problem identified

I already commented an error in #38792 that has not been resolved in the latest joomla update.

I still don't understand how to modify options of a select that is instantiated with choices. In  (media/system/js/fields/joomla-field-fancy-select.js)
Same problem in #36756.

### Open questions

I haven't found any documentation.
I also do not understand that this error has not been updated and that they may not take it into account.
I hope someone can help with an example, thank you very much.

**Comment by HLeithner** [comment]
Since this is a duplicate I'm closing it. About your question you may notice that we have more then 770 open issues and more then 200 pull requests unmerged. It means we need some time and women/men power to fix things.
