### ISSUE TITLE
[4.2] Problem in User Actions Log: invalid password reset commit

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#39062]
### Steps to reproduce the issue
1. Set up sending mail from the site,
2. Create a test user with a valid email address,
3. Use the item "Forgot your passwor" in the authorization form in the frontend for a test user,
4. Enter your login / confirmation code or follow the link in the letter received by mail,
5. Change the user's password to a new one.

Everything is successful, except that in the user activity log we have 2 entries about the registration of a new user, which is undoubtedly false and misleading.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/197507207-6159b63d-54fa-4f32-9472-98519e1afc30.png)

In addition, we have not received a record of a REQUEST to reset a user's password and then actually reset the user. Although we have such language strings.

```
PLG_ACTIONLOG_JOOMLA_USER_RESET_COMPLETE="User <a href='{accountlink}'>{username}</a> completed the password reset for their account"
PLG_ACTIONLOG_JOOMLA_USER_RESET_REQUEST="User <a href='{accountlink}'>{username}</a> requested a password reset for their account"
```
If I'm not mistaken, older versions of Joomla 4 didn't have this problem. Probably a regression.

P. S. The request to remind the login (username) in the action log is reflected correctly.

**Comment by Kostelano** [comment]
Rechecked on a new installation of version 4.1.5 - the same problem.

**Comment by alikon** [comment]
can please test #39435
