### ISSUE TITLE
[4.3] Language string is not used

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#39076]
`JLIB_RULES_SETTING_NOTES_ITEM_COM_CATEGORIES` is not used after apply PR #35424

### Steps to reproduce the issue

Open category edit form and switch to tab _Permissions_.

#### J4.2
![image](https://user-images.githubusercontent.com/66922325/197855155-76c20964-aabd-4df9-a00c-9f4f9cf033ed.png)
![image](https://user-images.githubusercontent.com/66922325/197855406-32919bc9-a7f0-409a-a390-e4c48953fc0f.png)

#### J4.3
![image](https://user-images.githubusercontent.com/66922325/197855219-0eb47b7e-ab0f-4f80-a5a8-6ab0eb9d112b.png)

![image](https://user-images.githubusercontent.com/66922325/197855645-21ace121-36cb-44e0-a389-76b60932fe09.png)

### Expected result

Same text as before the PR -> language string from `com_categories.ini` is used

### Actual result

Standard text for components -> language string from `lib_joomla.ini` is used

### System information (as much as possible)

J4.2.4 and J4.3-dev

@wojsmol @HLeithner

**Comment by Kostelano** [comment]
Missing "section"? In addition to the component, it is also needed.

**Comment by richard67** [comment]
> Missing "section"? In addition to the component, it is also needed.

Maybe. But the bigger problem is that here we are not in com_categories, we are in com_content. URL is `option=com_categories&view=category&layout=edit&id=2&extension=com_content`, and it seems the `extension` parameter is the relevant one.

When I change the language string constant from `JLIB_RULES_SETTING_NOTES_ITEM_COM_CATEGORIES` to `LIB_RULES_SETTING_NOTES_ITEM_COM_CONTENT_CATEGORY`, the right test is shown.

Of course we can't just rename that string. We have to deprecate the old one, and I have to check if the same applies to the other string from PR #35424 , too.

**Comment by richard67** [comment]
I will make a PR soon.

**Comment by richard67** [comment]
The other string `JLIB_RULES_SETTING_NOTES_COM_TEMPLATES` from PR #35424 is ok.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39212 . Thanks in advance.
