### ISSUE TITLE
Joomla 4.2.4 / php 8.0.8 / Override creations fails

### ISSUE THREAD

**Issue by rflieb13** [joomla/joomla-cms#39074]
### Steps to reproduce the issue
Installed a fresh installation of Joomla 4.2.4 on PHP 8.0.8 with MySQL 5.7.34 on my local machine via MAMP.
Installed german as a default language for FE & BE.
Wanted to create an override in Cassiopeia and got an error message return without generating the override

### Expected result
Override gets created as expected with success message

### Actual result
Error gets shown (screenshot) and no override gets created

### System information (as much as possible)
Joomla 4.2.4
PHP 8.0.8
MySQL 5.7.34 
on my local machine via MAMP PRO
MAC OS

**Comment by rflieb13** [comment]
![screen shot 2022-10-25 at 16 33 27](https://issues.joomla.org/uploads/1/ccdb88a5fa23dfb346a675b5aea5de2f.png)

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39074">issues.joomla.org/tracker/joomla-cms/39074</a>.</sub>

**Comment by HLeithner** [comment]
I can't confirm this, I tried with an updated site to 4.2.4 and was able to create the override without issues. Are you sure our file access rights are correct?

**Comment by rflieb13** [comment]
@HLeithner  thanks for checking this on your side - that is really strange as it is not my first joomla installation.
And a 2 week older installation works like a charm.
Currently I do not really know HOW I can tackle this issue on my side - I am kinda stuck here.
Tried also to install older version - no positive result.

Any suggestions what I should check in terms of "file access rights"?

**Comment by HLeithner** [comment]
I'm sorry I don't have macos I can only google this but I'm pretty sure you should be able to do this your self. As alternative ask in the forum.joomla.org for help.

I'm closing this for now, if it is really a joomla error you can reopen the issue at any time.
