### ISSUE TITLE
Should DATEBASE getNullDate return '0000-00-00 00:00:00'?

### ISSUE THREAD

**Issue by skurvish** [joomla/joomla-cms#39086]
### Open questions

According to the J4 Potential Backward Compatibility document [here](https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#PHP_MySQL_Extension) a date value of this type is no longer supported and we should be using NULL instead. 

So shouldn't getNullDate() return NULL?

**Comment by richard67** [comment]
No. It is made for returning the old deprecated zero date in case if it is used somewhere. It makes no sense to return null at this point.

**Comment by richard67** [comment]
Closing as expected behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39086">issues.joomla.org/tracker/joomla-cms/39086</a>.</sub>
