### ISSUE TITLE
[4.2.4] Article list. Table caption "Sorted by". Ordering shows wrong direction.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#39082]
### Steps to reproduce the issue
- Make a hack in file `administrator\components\com_content\tmpl\articles\default.php`.
  - Change line 86 `<caption class="visually-hidden">` to `<caption class="visually-hiddenssss">`.
  - Or use the browser inspector if you prefer that.
- In backend go to Articles List view and set filter to `Ordering ascending`.
- Compare with text in table `<caption>`.
- See images please: Wrong direction displayed.

![grafik](https://user-images.githubusercontent.com/20780646/198132943-122b2200-81e8-4c7c-923c-4c44bf8a3029.png)

![grafik](https://user-images.githubusercontent.com/20780646/198133061-838701aa-589e-444c-a8c7-7148e8b7e902.png)

### Additional comments
Already seen in 4.2.3 and thought it's my failure in my custom component where the caption is not visually-hidden.

**Comment by ReLater** [comment]
Checked some more filters in another site. Other filters are also affected. For example:

![grafik](https://user-images.githubusercontent.com/20780646/198135834-53fa1440-275c-4503-b52c-b2215429f593.png)

![grafik](https://user-images.githubusercontent.com/20780646/198135885-a805bd0d-c73e-49af-9144-81082c328f19.png)

**Comment by ChristineWk** [comment]
Assuming I checked correctly, I can confirm:

![screen shot 2022-10-27 at 11 56 31](https://issues.joomla.org/uploads/1/4815818e1c255aa1082279f52e178978.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39082">issues.joomla.org/tracker/joomla-cms/39082</a>.</sub>

**Comment by brianteeman** [comment]
99% certain this has been reported before

**Comment by ReLater** [comment]
> 99% certain this has been reported before

https://github.com/joomla/joomla-cms/issues/35494
