### ISSUE TITLE
After Update Joomla 4 i get an error

### ISSUE THREAD

**Issue by diddipoeler** [joomla/joomla-cms#39084]
Es ist ein Fehler aufgetreten.
0 Call to undefined method Joomla\Plugin\Behaviour\Versionable\Extension\Versionable::setApplication()

**Comment by richard67** [comment]
@diddipoeler Could you provide more information? From which to which version have you updated? What PHP version and what database type and version? Or do you really think an issue without this information is helpful in any way?

**Comment by diddipoeler** [comment]
UPDATE-INFORMATIONEN
================================================================================
Die Website hat festgestellt, dass eine aktualisierte Version für Joomla! zur Verfügung steht.
Aktuell installierte Joomla!-Version: 4.2.4-dev
Zur Installation verfügbare Joomla-Version: 4.2.5-dev

Vorher war die Version 4.2.5

PHP Version 8.0

Mysql

**Comment by richard67** [comment]
> Vorher war die Version 4.2.5

We have to communicate in English here.

Version 4.2.5 can not be because this never has been released.

Are you on the "Testing" update channel (German: Update-Quelle)? Otherwise you should not be offered a version " 4.2.5-dev", which would be a nightly build of the current development status.

**Comment by richard67** [comment]
Why closed? Has your issue been resolved or have you found the reason why it failed?
