### ISSUE TITLE
Option to hide 'New Article' button in Content Category List menu items

### ISSUE THREAD

**Issue by bascherz** [joomla/joomla-cms#39095]
### Steps to reproduce the issue
For Super Users and ACLs given permission to create articles, in the front end there is no option to hide the "New Article" button. There are definitely cases where this is desired, but there is no way to **make it invisible on a *selective basis***.

### Expected result
The most obvious way to do this is to add an option to hide that button in the Category List menu item, either under List Layouts or Options (probably the latter). This should be a fairly simple enhancement that I would think might be more popular than you think.

### Actual result
There is no way to selectively hide the com_content.category "New Article" button on a per-category.

### System information (as much as possible)
Joomla 4+

### Additional comments
I use and write extensions and snippets that are part of extensions that create articles that I do not want anyone but the Super User to be able to edit and do not want ANY USER to be able to create new articles in the designated categories. **It is not critical if this does not apply to the Super User ACL, but it should apply to all other levels (or the level should be selectable in the category options).**

Thank you for your consideration. :thumbsup:

**Comment by brianteeman** [comment]
Just go to the category, and then permissions.
Deny the ability to create articles for that usergroup
Job done.

Am i missing something?

**Comment by bascherz** [comment]
Yes, I would like for it to be selective by category, not fully inclusive by permission.

Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39095">issues.joomla.org/tracker/joomla-cms/39095</a>.</sub>

**Comment by brianteeman** [comment]
How is that different from what I described.

**Comment by bascherz** [comment]
Not sure what idiot mode I was in the other day when I did exactly what you recommend and it did not seem to work. Probably went to the wrong category. But it does work, so this request can be rejected and closed.

Sometimes coffee is just not enough of a stimulant. Thanks, Brian!

Bruce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39095">issues.joomla.org/tracker/joomla-cms/39095</a>.</sub>
