### ISSUE TITLE
[4.2.4] Modules: Articles - Categories - Layout invalid

### ISSUE THREAD

**Issue by beejay41** [joomla/joomla-cms#39094]
### Steps to reproduce the issue
Add a module layout override to your template. Create or change an article categories module and select your layout override from the layout dropdown on the advanced tab. Click save.

### Expected result
The module should be saved.

### Actual result
The error "Invalid field: layout" is displayed and the module is not saved.

### System information (as much as possible)
![screen shot 2022-10-28 at 13 38 48](https://issues.joomla.org/uploads/1/d0b34e0cd4c0b153f65776c4d2bddb25.png)

### Additional comments
If the layout is changed in the database, it operates as expected in the frontend.
This behaviour has been introduced since 3.9+, I believe. It certainly worked as expected in the past.

The same issue occurs with mod_login. 

Previously reported on 3.x:
[https://issues.joomla.org/tracker/joomla-cms/37491](http:// "[#37491] - [3.10.8] Modules: Articles - Categories - Layout invalid")

**Comment by ReLater** [comment]
I can't confirm your find.

![grafik](https://user-images.githubusercontent.com/20780646/198687043-7accb816-c128-40f5-aa9b-11b3615b7e29.png)

I could save all 3 modules after selecting my `customlayout`.

PHP 8.1.7
MySQLi 10.5.16-MariaDB-1:10.5.16+maria~focal-log
Joomla 4.2.4

**Comment by beejay41** [comment]
Curious. Yes, if I select the override in Cassiopia, then it will save, but when I select the override from my own template, it fails to save.
I must be missing something in my template xml or perhaps just that my template has a period in it (folkclubs.2020)! The latter could easily explain why several on my templates exhibit this issue. I'll try changing that and report back.

**Comment by beejay41** [comment]
The period in the template name was the problem. I can't find any specific rules on template naming, but I'll avoid this in future.
It seemed like a good idea to include the year created in the name, but that was in the 1.5 era.

**Comment by sh-si** [comment]
I can confirm this issue.
The naming of my custom template is "nameX_nameY-v3.0.0".
If i change the template name to "nameX_nameY-v3_0_0" everything works as expected. 

Is there a documentation / specification of template naming rules somewhere?
