### ISSUE TITLE
Non-static method Joomla\Http\HttpFactory::getHttp() cannot be called statically

### ISSUE THREAD

**Issue by techfry** [joomla/joomla-cms#39093]
### Steps to reproduce the issue

Open File: /libraries/vendor/joomla/oauth2/src/Client.php

The Code On Line 77 : $http ?: HttpFactory::getHttp($this->options);

This method getHttp() is non static. So, error is coming.

Check Here: /libraries/vendor/joomla/http/src/HttpFactory.php

### Expected result

The method getHttp() should be static.

### Additional comments

All external requests using OAuth 2.0 has stopped due to this error.

**Comment by ReLater** [comment]
Because these are vendor libraries I think your issue should go here
https://github.com/joomla-framework/http/tree/2.0-dev/src
and/or here
https://github.com/joomla-framework/oauth2/tree/2.0-dev/src

**Comment by sergeytolkachyov** [comment]
I had the same problem. Need in this fix too

**Comment by sergeytolkachyov** [comment]
In which version of Joomla will this bug fix appear?

**Comment by korenevskiy** [comment]
https://github.com/joomla-framework/oauth2/issues/16

**Comment by Hackwar** [comment]
PR #41455 should fix these issues, thus closing this issue. Thank you for your work and time.
