### ISSUE TITLE
GDPR, Cookie banner, EU law - Need to be a core of every Content Management System

### ISSUE THREAD

**Issue by PCT1991** [joomla/joomla-cms#39103]
Hello Joomla-Community,

Data protection law has been in force in Europe since 2018.

A handful of GDPR plugins were programmed for Joomla. But only one on the market, which you also have to buy, has observed all legal points.

As an IT expert, I simply do not understand why a cookie banner has not been implemented in Joomla or in other CMS for a long time.

It is important that a website visitor has to agree before loading scripts or fonts from other websites. Likewise, not a single cookie may be set before consent has been given.

The law also says that cookies must be described to the website visitor. Name, purpose, duration, ...

In addition, a website visitor must be able to withdraw their consent at any time.

For this reason I am requesting this feature. It's been almost 5 years and neither in Joomla nor in other CMS was something integrated. It's the law. So it should be anchored at the core of every CMS.

BTW this is the only plugin which provide all the right functions for Joomla:
https://extensions.joomla.org/extension/gdpr/

The other plugins are just wrong for the EU. This can get very, very expensive if a law agent contact you, because some Google Fonts get downloaded or a Cookie get setted without a permission of the user.

Thank you in advance!

Best regards
Pascal

**Comment by brianteeman** [comment]
This is not an issue for github
