### ISSUE TITLE
[4] Please reopen Issue #34248 (global menu options)

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#39109]
A decision should be made. Maybe remove the mentioned global settings in Joomla 5 or earlier.

It's an issue that is open since many many years and Joomla versions and is just leading to user irritation again and again. All attempts to solve the problem were unsuccessful.

**Comment by richard67** [comment]
I've re-opened #34248 because the PR which closed it was closed without merging, so the issue should have been re-opened anyway.

@ReLater Thanks for notifying. So shall we close this one here and go on with #34248 ?

**Comment by ReLater** [comment]
Thanks! Yes i close now.
