### ISSUE TITLE
[4.2] Hotkey-hint not localized in "System - Additional Accessibility Features"

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#39102]
### Steps to reproduce the issue
I noticed that in plugin **System - Additional Accessibility Features** the prompt line about hot keys is not localized. Not essential, but could be fixed in future versions.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/198839690-6cf7fa04-9d90-4f77-9add-b8df74aed6f7.png)

**Comment by drmenzelit** [comment]
We will have a look at that.

**Comment by wojtekxtx** [comment]
@Kostelano Try to load anoither language and see there.
@drmenzelit 7 days and no response?

**Comment by drmenzelit** [comment]
You can also have a look at the script and try to find out where and how to localize the Hotkey strings: https://github.com/ranbuch/accessibility

**Comment by alikon** [comment]
> ...7 days and no response?

@wojtekxtx did you know, that, we are, "all volunteers"  here ?

**Comment by wojtekxtx** [comment]
@alikon All of you? I thought that some of you ( management of Joomla ) is paid for this. Seriously.
And even if all contributors are volunteers, not replying for 7 days is damaging to the project. Not to mention its rude. You all have notifications when there is a reply......

**Comment by alikon** [comment]
I can swear that nobody here are paid, and we are a fully community driven project

**Comment by chmst** [comment]
@Kostelano can speak for himself if he needs a quick answer, but he knows how we work. 

@wojtekxtx 
> All of you? I thought that some of you ( management of Joomla ) is paid for this. Seriously.

As @alikon wrote nobody is paid in the Joomla project. Volunteers spend their spare time unpaid for people like you. You are warmly invited to join us, add new features, answer discussions, test and make releases, fix bugs, write documentation, provide PRs.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39102">issues.joomla.org/tracker/joomla-cms/39102</a>.</sub>

**Comment by wojtekxtx** [comment]
>  nobody is paid

@chmst even employees of OSM? Really? Than whats [this](https://volunteers.joomla.org/board-of-directors?start=75?start=54?start=18?start=63?start=10?start=36?start=6?start=6?start=6?start=65?start=33?start=80?start=66?start=12?start=55?start=21?start=39?start=45?start=90?start=85?start=30?start=10?start=5?start=20?start=40?start=25?start=15?start=3?start=3?limitstart=0?start=57?start=35?start=39?start=75?start=54?start=36?start=80?start=66?start=3?start=6?start=40?start=78?start=18?start=63?start=10?start=6?start=65?start=33?start=3?start=12?start=55?start=21?start=3?start=3?start=85?start=54?start=35?start=10?start=15?start=20?start=25?start=30?start=35?start=40?start=45?start=5?start=90?start=80?start=66?start=54)

The fact that its placed under `volunteers` subdomain speaks **nothing**.

**Comment by brianteeman** [comment]
ffs why can't you accept what you are told.

NO ONE IS PAID.

we're all wasting too much time with this troll

**Comment by wojtekxtx** [comment]
> we're all wasting too much time with this troll

@brianteeman having discussion is trolling? haha good riddance. Now go tell GitHub they should shutdown Discussions as people who discuss there are trolls. C'mon man, Im waiting...............

**Comment by alikon** [comment]
> even employees of OSM? Really? 

yet again no one is paid even in OSM

**Comment by Quy** [comment]
This will be fixed in #43143. Thanks for the report.

**Comment by brianteeman** [comment]
pull request submitted upstream so that it can be merged with #43143
