### ISSUE TITLE
Reopen issue #39100

### ISSUE THREAD

**Issue by RichardZimmerEschborn** [joomla/joomla-cms#39107]
Sorry, I did not find a way to reopen the issue and did not get a reply to my last comment. So I file a new issue.

Sorry, that I am not expressing myself perfect and am not able to make you understand the problem right away.

Sorry again, but it seems to me, that you are not trying to understand the problem I am reporting, but just trying to find a hind which allows you to close the issue.

So please leave the issue open, until the problem is fully understood and solved.

I changed the settings for system/language filter plugin. Now the settings are:

x-default Language: German (DE)
Remove URL Language Code: No

### Steps to reproduce the issue

1. Set browser settings to prefer English content.
2. Clear all browser cache (content and cookies)
3. Follow this link https://bogenparadies.de/hilfe
4. Follow this link https://bogenparadies.de/de/hilfe

### Expected result

See the help page of the site. Preferable in English (because of the browser setting), or as fallback see the German help page of the site.

### Actual result

See a 404 Error page.

### System information (as much as possible)

Same as already given in #39100

### Additional comments

It seems to me, that the system/language filter (like its name might suggest) simply blocks all content which does have a different language setting than the state of the plugin.

This would be a bug, because the browser setting is to PREFER English content and not to show English content ONLY.

The expected behavior would be, if an assosiated English version of the URL exists: redirect to the English version (this is what the browser setting wants). If no English version is assosiated with the URL, show the German article.

And we did not jet talk about multiple prefered languages in a specific order in the end users browser settings.

Also. when the URL is given without language code, the corresponding article should be displayed. That means when the URL path part matches the alias of the Menu-Item the article may be found and displayed (maybe through a redirect).

**Comment by richard67** [comment]
> Also. when the URL is given without language code, the corresponding article should be displayed. That means when the URL path part matches the alias of the Menu-Item the article may be found and displayed (maybe through a redirect).

You are completely ignoring that 2 pages with different languages can have the same alias. That is and should be possible.

**Comment by richard67** [comment]
For reference here the link to the previous issue #39100 and here the link to the support forum post mentioned in that previous issue https://forum.joomla.org/viewtopic.php?f=809&t=997383 .

**Comment by HLeithner** [comment]
I'm closing this and reopen #39100 because of duplication. I will comment in the old issue.

**Comment by richard67** [comment]
Thanks.
