### ISSUE TITLE
Media Manager folder tree

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39126]
When you have a large number of folders it is not possible to scroll to the folders that are not in the viewport independent to the main scroll.

You will probably only notice this when the media manager is loaded in a modal.

https://user-images.githubusercontent.com/1296369/199445266-a1098938-1a63-4dee-a0b1-173be97ce22e.mp4

**Comment by wojtekxtx** [comment]
Again, very easy fix. Disk/Folder browser is implemented in a borderless `box` on borderless `canvas` element with `LayoutManager`. Its enough to implement `scroll` action. Thats it. Some 5 mins of work.

**Comment by crystalenka** [comment]
It's because of the sticky property. Something similar happens when you have multiple media sources defined—they stack.

This should be only CSS updates (I hope...) so I will give it a try.

**Comment by brianteeman** [comment]
Closing as there is a pr
