### ISSUE TITLE
TinyMCE loses English language after editing plugin options

### ISSUE THREAD

**Issue by mavrosxristoforos** [joomla/joomla-cms#39121]
### Steps to reproduce the issue
Open TinyMCE plugin options in Joomla 4.
Save.

### Expected result
Editor language should remain English.

### Actual result
Editor language switches to Afrikaans. (first value of `Language code` dropdown)

### Additional comments
The `Language Code` field in `plugins/editors/tinymce/forms/setoptions.xml [line 106]` is a `filelist` of the directory `media/vendor/tinymce/langs/`. The default value is `en`. However, there is no `en.js` file in that directory, so the default value is lost and replaced with `af` as soon as you tweak any TinyMCE plugin options.

Joomla 3 seems to have a similar issue, where you can't deselect a selected language code, but at least the default is empty, because of the different behavior of the dropdown. (the default value in setoptions.xml is still `en`)

**Comment by Fedik** [comment]
Note: this only happens when "Automatic Language Selection" set to "Off"

**Comment by mavrosxristoforos** [comment]
@Fedik I confirm.

**Comment by Fedik** [comment]
Please test #39131
