### ISSUE TITLE
Error page when no items found in "Compact List of Tagged Items"

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#39127]
### Steps to reproduce the issue

Make a menu entry  type "Compact List of Tagged Items". 
With a tag where no articles or other items are tagged with. 

In frontend, click the link.

### Expected result
User friendly Information: no items found

### Actual result
404 - tag not found. 

From the technical point of view the message is correct. For the user it is not.

 JROOT\components\com_tags\src\Model\TagModel.php:313 

### Additional comments
https://github.com/joomla/joomla-cms/pull/39113

**Comment by Hackwar** [comment]
I tried this and I can't replicate it on a current 4.3-dev. Can you check this again? The code you mentioned is actually not there to load the content items, but the (list of) tag(s) to use in this menu item. When I tested this, it worked fine. Maybe you had the tag unpublished?

**Comment by chmst** [comment]
I don't remember but after a new test - yes. The 404 comes when the tag is not published.

**Comment by Hackwar** [comment]
That would then indeed be the right behavior. We do the same when an article is unpublished in a menu item. Therefor I would close this issue for now.

**Comment by chmst** [comment]
I will open a new issue. From a users point of view and this message is technically correct but not user friendly and forums are full with questions.
