### ISSUE TITLE
MenuItem - Adding non existing tag in tags field causes 404

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#39128]
### Steps to reproduce the issue
Menu Item of type Compact List of tagged Items has an input field of type tags.
Enter a non existing tag. Save.

### Expected result
The new tag is stored as a tag.

### Actual result
The tag is not stored, but added to the link. 
![grafik](https://user-images.githubusercontent.com/1035262/199461227-a9b2d627-3eb3-4c85-a0b5-01acb94829f8.png)

### Additional comments
Related: https://github.com/joomla/joomla-cms/pull/39113

**Comment by Hackwar** [comment]
It should not be possible to create new tags from the menu manager.

**Comment by Hackwar** [comment]
We got a PR. #39154

**Comment by brianteeman** [comment]
I think there is another open issue about 

> It should not be possible to create new tags from the menu manager.
