### ISSUE TITLE
Unable to select Url type menu item as Base item in mod_menu

### ISSUE THREAD

**Issue by artur-stepien** [joomla/joomla-cms#39130]
This issue https://github.com/joomla/joomla-cms/issues/20556 did return in Joomla! 4 

### Steps to reproduce the issue
- Create menu consisting of `URL type` items and its subitems (that is important)
- Go to `Modules -> New -> Menu`
- Try to select in `Base item` any of the submenu `URL type` items you added in first step

### Expected result
Able to select `URL`, `Heading`, `Alias`  type menu item as `Base item`

### Actual result
Menu item is inactive

### System information (as much as possible)
Joomla! 4.2.4

### Additional comments
Because of this you can't build a menu that will consist of parts of other menus cause you can't chose URL or Alias type of menu items.

**Comment by brianteeman** [comment]
I thought I fixed this

**Comment by artur-stepien** [comment]
@brianteeman  In Joomla! 3 yes, in Joomla! 4 it exists. It might be the last time it was reported the Joomla! 4 was already using a different fork or something.

![obraz](https://user-images.githubusercontent.com/2000754/199465040-b2d0a0aa-e892-4952-be57-d1cbf492dfd8.png)

**Comment by brianteeman** [comment]
If you can find the pr where I made the fix in j3 it would be helpful

**Comment by artur-stepien** [comment]
> If you can find the pr where I made the fix in j3 it would be helpful

https://github.com/joomla/joomla-cms/pull/38563/files

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/199471158-920a2281-04dc-4e2f-ad4b-aad95ab3003f.png)

That shows it is fixed in the upcoming 4.3 release

**Comment by artur-stepien** [comment]
Oh, It's an August update. I see it exists in 4.3 dev so I close it
