### ISSUE TITLE
Joomla 4.2.4 Not Listed In Releases

### ISSUE THREAD

**Issue by redevodm** [joomla/joomla-cms#39132]
If you go to the Joomla Release site here https://github.com/joomla/joomla-cms/releases, Joomla 4.2.4 is not listed.

**Comment by zero-24** [comment]
It is to me?
![image](https://user-images.githubusercontent.com/2596554/199528453-cebc7fbb-21b1-4f1d-8c3e-a90d8369f011.png)

**Comment by alikon** [comment]
i can confirm it is not listed
![image](https://user-images.githubusercontent.com/181681/199529253-4ccbf34d-13c6-422a-9d99-d49589aa2212.png)

**Comment by brianteeman** [comment]
Good spot Phil

**Comment by zero-24** [comment]
Hmm interesting will mention it to @roland-d who created the release. Its also only showed to me when logged in to github but not when I'm not logged in.

**Comment by alikon** [comment]
my screenshot  is from when i'mi logged in

**Comment by roland-d** [comment]
I also did not see the 4.2.4 release when not logged-in. Did not see anything obvious. Resaved the release and now it shows up for me. Can you guys verify?

**Comment by zero-24** [comment]
>my screenshot is from when i'm logged in

Yes but we both have different permission levels on GitHUb. But even that does not make sense to me as we had reactions from people who do not have special permissions too

![image](https://user-images.githubusercontent.com/2596554/199535738-a0ffb5b9-eaf3-497f-9040-0c270f429242.png)

**Comment by redevodm** [comment]
> I also did not see the 4.2.4 release when not logged-in. Did not see anything obvious. Resaved the release and now it shows up for me. Can you guys verify?

I can confirm it now shows up for me too

**Comment by alikon** [comment]
i can confirm that now is listed
![image](https://user-images.githubusercontent.com/181681/199537738-aadf1e70-a836-4f3b-b53b-cffe4e55f3dc.png)

**Comment by alikon** [comment]
i'll consider this closed
