### ISSUE TITLE
Categories - Batch process copy makes duplicate alias 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#39137]
### Steps to reproduce the issue

Have a category tree with equal aliasses in differnet categories.  (John - books and Rachel - books
Perform batch action move as in the following screen. Move books from Rachel to John

![grafik](https://user-images.githubusercontent.com/1035262/199549111-11f8bd1d-497a-479c-950b-bbf6650ddcf0.png)

This results in duplicate title and aliases for two different categories

### Expected result

A check for duplicate alias is performed and a warning is displayed and/or the moved alias gets a number.

### Actual result

Duplicate title and alias for moved categories
![grafik](https://user-images.githubusercontent.com/1035262/199547895-f016ad70-9890-4478-a520-96563a646c9e.png)

**Comment by alikon** [comment]
please test #39158
