### ISSUE TITLE
Batch process categories -reverse ordering error 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#39133]
### Steps to reproduce the issue
Select more than one category and choose Reverse ordering 

![grafik](https://user-images.githubusercontent.com/1035262/199524519-eb253916-172c-49b0-86fe-1f2268ab581c.png)

### Expected result
Reverse ordering is performed for all selected categories

### Actual result
Error

Cannot set the query type to "select" as the query type is already set to "update". You should either call the `clear()` method to reset the type or create a new query object.
	
JROOT\libraries\vendor\joomla\database\src\DatabaseQuery.php:1675

**Comment by heelc29** [comment]
Please test #39174

**Comment by alikon** [comment]
closing as we have a pr to test #39174 

P.S.
thank you @heelc29
