### ISSUE TITLE
Selection of cache group not working correct

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#39144]
### Steps to reproduce the issue
1. goto Maintenance: clear cache
2. select (e.g.) _media_version_ by clicking in the _media_version_ text

![screen shot 2022-11-03 at 13 22 39](https://issues.joomla.org/uploads/1/7f9acea79749486f400a91023e2dae86.jpg)
### Expected result
the cache group _media_version should be selected

### Actual result
The cache group get focus but is NOT selected.

### System information (as much as possible)
J4.2.4

### Additional comments
clicking on the radio button or anywhere else on the cache group row does work correct, it only doesn't work when clicking the text.

**Comment by joomlaphp** [comment]
[#38314](https://github.com/joomla/joomla-cms/issues/38314)

**Comment by brianteeman** [comment]
please test #39147

**Comment by alikon** [comment]
closing as we have a pr #39147
