### ISSUE TITLE
media folder

### ISSUE THREAD

**Issue by Stepanov-Sergey** [joomla/joomla-cms#39166]
### Steps to reproduce the issue
1. created a directory "data/images"
2. system/general configuration/media
Path to Files Folder changed the path to  :"data"
and
Path to Images Folder  changed the path to Path to  "img"
Path to Images Folder  changed the path to Path to  "data/img"

### Expected result

created a new article, went to the images tab, clicked select image
expected directory  "data/img" 

### Actual result
created a new article, went to the images tab, clicked select image
the default directory "images" has opened

### System information (as much as possible)

joomla 4.2.4

### Additional comments
previously, this worked and continues to work even on upgraded to 4.2.4

**Comment by 19kushal** [comment]
can you specify in which file specifically do I have to edit the path to data/img

**Comment by Quy** [comment]
Duplicate #35689?

**Comment by Quy** [comment]
Closing as duplicate.
