### ISSUE TITLE
Atum Administrator Template isn't loading

### ISSUE THREAD

**Issue by mahrens61** [joomla/joomla-cms#39167]
After my Update to 4.2.4 the Atum template isn't working.

**Comment by brianteeman** [comment]
Please use the forum for support https://forum.joomla.org.

And when you do post on the forum PLEASE give them a bit more information.

**Comment by mahrens61** [comment]
Hi Brian,

I will make a post in the support forum. Btw. i send three screendumps, it seems they are lost.

Michael
