### ISSUE TITLE
I am trying to Use the "link" button on an article in Joomla but I am getting an error message:  

### ISSUE THREAD

**Issue by Pircman** [joomla/joomla-cms#39163]
### Steps to reproduce the issue

Click on the "chain" link button 

### Expected result

Option to input webpage to link to

### Actual result
error message 
Error
An error has occurred.

    0 func_get_arg(): Argument #1 ($position) must be less than the number of the arguments passed to the currently executed function 

Return to Control Panel

**Comment by chmst** [comment]
Which Joomla Version? Where do you click on the chain button? TinyMCE or an extension? Which extension?

**Comment by Pircman** [comment]
Joomla! 3.10.11
The Small chain ling that appears above the box you type in,

 Just in a "Joomla article"

**Comment by ChristineWk** [comment]
Are you using jce and if so, the latest version?

@chmst could be relevant? https://forum.joomla.de/thread/13127-fehlermeldung-jce-pro-mit-php-8/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39163">issues.joomla.org/tracker/joomla-cms/39163</a>.</sub>

**Comment by chmst** [comment]
@ChristineWk seems the same error, thank you.

**Comment by Pircman** [comment]
I updated JCE to the latest before just before the error appeared yes.
I can't understand the german. Will look at the JCE link though.

**Comment by ChristineWk** [comment]
@Pircman 
Switch on "Debug Mode" on your website (in Global Configuration) so you can see where the error comes from (Call Stack)

**Comment by brianteeman** [comment]
This really should be on the forum and not here. Especially as it is for joomla 3 and an extension.

**Comment by chmst** [comment]
agree, and closing here. https://forum.joomla.org
