### ISSUE TITLE
Joomla deletes password for new user

### ISSUE THREAD

**Issue by lmcintoshgw** [joomla/joomla-cms#39179]
### Steps to reproduce the issue
1. Create new User
2. Create Password 
3. Save

### Expected result
Password is saved and user can log in using those credentials

### Actual result
Password is deleted and user cannot log in at all

### Additional comments
I have created several new users but this issue is the repeated.  Current users do not have this password issue.
All other fields remain saved 
![Joomla 1](https://user-images.githubusercontent.com/117777244/200675298-c90c5616-c8ea-4d8b-86c3-8e599c0c8c4d.png)
![Joomla 2](https://user-images.githubusercontent.com/117777244/200675301-5426e183-9d47-40c1-b6ee-2c561f844519.png)

**Comment by chmst** [comment]
Joomla does not delete a password, but it does not show it on a screen. Please post this question in the forum.joomla.org.
