### ISSUE TITLE
Use "Header set" instead of "Header append" in .htaccess to avoid double encoding

### ISSUE THREAD

**Issue by vicn1222** [joomla/joomla-cms#39176]
Hello,

I have exactly the same issue described at https://www.drupal.org/project/drupal/issues/1116416

My joomla is installed in a sub-directory that has already doing a gzip compression, which causes double gzip encoding.

I change htaccess.txt as below: 

Header set Content-Encoding gzip
Header set Vary Accept-Encoding

then the Joomla page works properly.

Thanks.

**Comment by richard67** [comment]
> I change htaccess.txt as below:

I doubt that a change on `htaccess.txt` had any impact on your webserver 😄 .

I assume you've changed `.htaccess`.

> Header set Content-Encoding gzip
> Header set Vary Accept-Encoding

You mean here? https://github.com/joomla/joomla-cms/blob/4.2-dev/htaccess.txt#L164-L171

**Comment by richard67** [comment]
P.S.: I was reading the complete discussion in the drupal issue thread and at the end they concluded to change only the `Header set Content-Encoding gzip`.

The `Header append Vary Accept-Encoding` they left as it was because the `Accept-Encoding` can have multiple encodings in its value, so that was not a problem.

**Comment by vicn1222** [comment]
Of course I change .htaccess after copying from htaccess.txt :-)

Joomla doesn't come with .htaccess, but htaccess.txt, so I said htaccess.txt (*_^)

Maybe "Header append Vary Accept-Encoding" doesn't need to be changed, but "Header append Content-Encoding gzip" shoud.

Cheers<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39176">issues.joomla.org/tracker/joomla-cms/39176</a>.</sub>

**Comment by richard67** [comment]
> Maybe "Header append Vary Accept-Encoding" doesn't need to be changed, but "Header append Content-Encoding gzip" shoud.

@vicn1222 Agreed.

Do you want to make a pull request so you get the honour and fame for having fixed that? If so, you should provide some testing instructions. If you don't want or can't make a PR, let me know here, than I can make one. Would be great if you could test it then.

**Comment by vicn1222** [comment]
@richard67 Please make the request.

I have tested both standalone and inside a sub-direction. Both work well without issue. Without that change, the joomla inside a sub-directory causes the issue, and my google search lead me to the solution by drupal user.

Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39176">issues.joomla.org/tracker/joomla-cms/39176</a>.</sub>

**Comment by vicn1222** [comment]
@richard67 

Hi Richard, could you please also make request for this bug? https://issues.joomla.org/tracker/joomla-cms/38899

The new update didn't take my fix. Please feel free to make changes as necessary.

Many thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39176">issues.joomla.org/tracker/joomla-cms/39176</a>.</sub>

**Comment by richard67** [comment]
Closing as having a pull request.

@vicn1222 Please test #39205 and when having tested, go to the PR in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/39205 , use the blue "Test this" button at the top left corner, select your test result and then submit. Thanks in advance.

For the other issue which you have mentioned I am not sure if I will make a pull request. I have to check later.
