### ISSUE TITLE
misleading CLI installation docs

### ISSUE THREAD

**Issue by kiranparajuli589** [joomla/joomla-cms#39194]
### Steps to reproduce the issue
1. Browse to https://docs.joomla.org/J4.x:Joomla_CLI_Installation
2. Navigate to section: `Script-driven automatic installation`. The first line in the section says there is a `joomla.php` file inside `installation` dir

### Expected result
A `joomla.php` file should be present inside `installation` dir

### Actual result
There is no such dir.

### Additional comments
I want to perform CLI installation of Joomla4.xx. The docs says running `joomla.php` from installation dir, but the code does not posses one. How can we process CLI installation???

**Comment by brianteeman** [comment]
You ignore the very first words on that page

"Starting with Joomla! 4.3,"

**Comment by richard67** [comment]
Closing for reason mentioned in the previous comment.

**Comment by kiranparajuli589** [comment]
> You ignore the very first words on that page
> 
> "Starting with Joomla! 4.3,"

sorry for that ;). thx for the clearance.
