### ISSUE TITLE
[4.2] Under the author of the article everywhere "Alias: Joomla"

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#39198]
### Steps to reproduce the issue
Install 4.2,
Install demo data,
Go to Content --- Articles,
Please note that under the author of the articles, the **Joomla** alias is mentioned everywhere.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/201466217-628a8d8b-42a6-4a67-963f-8cd303ef425a.png)

**Comment by brianteeman** [comment]
Yes, it is a demo of the author alias feature

**Comment by Kostelano** [comment]
Okay, I'm closing. I hadn't noticed it before, but it seemed strange.
