### ISSUE TITLE
Text Filter mangles HTML when attribute value contains a special character

### ISSUE THREAD

**Issue by ryandemmer** [joomla/joomla-cms#39193]
### Steps to reproduce the issue
1. In System -> Global Configuration -> Site, set **Default Editor** to _Editor - None_.
2. In System -> Global Configuration -> Text Filters, set **Filter Type** for the Super Users group to _Default Forbidden List_.
3. Click Content -> Articles -> New to create a new article.
4. Paste in the content below. Note the (valid) special character in the href attribute value.
```html
<a href="https://www.ikea.com/gb/en/p/birkelånga-tray-patterned-multicolour-grey-green-40537947" target="_blank">BIRKELÅNGA</a>
```
5. Click Save

### Expected result
The article content should remain intact as the HTML is valid.

### Actual result
The content becomes 
```html
a href="https://www.ikea.com/gb/en/p/birkelånga-tray-patterned-multicolour-grey-green-40537947&quot;&quot;"BIRKELÅNGA</a>
```
once filtered and saved. The first < and > from the ```<a>``` tag are removed and the last " of the attribute value is encoded.

### System information (as much as possible)
Joomla 4.2.4
Browser (Any)
PHP 8.0.14

### Additional comments
When the Text Filter **Filter Type** is set to _No Filtering_, this issue does not occur, and the content is saved correctly.

**Comment by ryandemmer** [comment]
This appears to only occur when the special characters are in the href attribute value. For example, the following link, where the special caharacters are in the title attribute value, the Text Filter does not affect the HTML:
``` html
<a href="https://www.ikea.com/gb/en/p/birkelanga-tray-patterned-multicolour-grey-green-40537947" title="BIRKELÅNGA">BIRKELÅNGA</a>
```

Further investigation shows that when a special character is in the **src** attribute value of an ```<img>``` tag for example, a **FatalError Error: Maximum execution time of 30 seconds exceeded** is generated with reference to **libraries/vendor/joomla/string/src/phputf8/mbstring/core.php on line 94**

**Comment by MacJoom** [comment]
I can confirm this, only with my system the <img> tag is mangled as well, no Fatal Error, and strange enough <img gets ig

**Comment by SharkyKZ** [comment]
https://github.com/joomla-framework/filter/pull/50.

**Comment by ryandemmer** [comment]
This appears to be fixed in this PR - https://github.com/joomla-framework/filter/pull/50

**Comment by MacJoom** [comment]
Yes i have successfully tested joomla-framework/filter/pull/50 - closing this issue then

**Comment by deltapapa01** [comment]
Hi,
Bug is still there: https://github.com/joomla/joomla-cms/issues/39515
