### ISSUE TITLE
com_tags and com_content  - another problem with router

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#39206]
I have been discovered an issue with router associated with com_tags/com_content.
There are two menu items:

1. Category Blog. Alias: blog.
2. Tags > compact list of tagged items. Alias: tags.

I noticed some items with  incorrect URL:
Quantum Manager 1.5.0 released (https://mydomain.com/blog)
Quantum Manager 1.3.1 released (https://mydomain.com/blog)

Other items have correct URLs which leads to the page, e.g.:
https://mydomain.com/blog/quantum-manager-1-4-0-released

I switched to Cassiopeia to check out and the issue is the same:
<img width="1358" alt="Снимок экрана 2022-11-12 в 19 26 05" src="https://user-images.githubusercontent.com/3432048/201485368-df39771a-96c0-4c09-8241-3390c9ee23c1.png">

Menu item options: 
<img width="1418" alt="Снимок экрана 2022-11-12 в 19 34 26" src="https://user-images.githubusercontent.com/3432048/201485288-7ae4c6f4-700d-4aff-a250-b9724f8c9317.png">

So, in some cases the path to the article is wrong...

If this issue is known - ok. I just shared the info which recently was discovered.

### System information (as much as possible)

Joomla 4.2.5
PHP 7.4 / 8.1

**Comment by Hackwar** [comment]
#39114 should fix this.
