### ISSUE TITLE
Don't reset category selector when a new article is being created

### ISSUE THREAD

**Issue by fillera** [joomla/joomla-cms#39201]
### Steps to reproduce the issue
1. Create a new article or contact
2. Try to reset on category selector clicking on close button (see screenshot attached)
![screen shot 2022-11-12 at 10 31 35](https://issues.joomla.org/uploads/1/fbf3108c59ecd46f7c06fa0c726ee21a.png)

### Expected result
No category selected

### Actual result
Reload the page (showing Joomla Logo) and show the same category previously selected.

### System information (as much as possible)
Joomla 4.2.4
PHP 8.1.12

### Additional comments
This issue happens only when create a new item. If you try to edit an existing item the close button acts as would be expected.

**Comment by brianteeman** [comment]
> This issue happens only when create a new item. If you try to edit an existing item the close button acts as would be expected.

I don't understand. When I edit an existing article and click on the x then the category is reset to the default "uncategorised" category - exactly the same as when I do the same on a new article.

What were you expecting to happen that isnt

**Comment by Hackwar** [comment]
No response for 2 months, so closing the issue.

Since a content item always has to have a category, you can't unset that field.
