### ISSUE TITLE
Tag is not applied when saving

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#39219]
### Steps to reproduce the issue

Tag a post - example tag "Wein" - see screenshots 1: Save post
![image](https://user-images.githubusercontent.com/4489029/202009454-ff1dddc6-302f-4f3e-b696-7c413c026bab.png)

### Expected result
Tag is applied and still displayed after saving
![image](https://user-images.githubusercontent.com/4489029/202010735-68e4c1fe-0f0b-4f97-93b3-490a23a8ce92.png)

### Actual result
Tag is not displayed after saving (neither in the backend nor in the frontend) - see screenshot 2:
![image](https://user-images.githubusercontent.com/4489029/202009709-22fdd600-3bf5-431f-94e3-973479e64c8b.png)

### System information (as much as possible)
joomla 4.2.5, PHP 8.1

### Additional comments
Occurs regardless of whether the tag is displayed in the preselection during allocation and selected via it or freely entered (screenshots 3 and 4)
![image](https://user-images.githubusercontent.com/4489029/202009966-9320b9cc-79cb-4e68-8af5-b915c10082b8.png)
![image](https://user-images.githubusercontent.com/4489029/202010050-440319c6-8d78-4f28-8121-0c762a800ccb.png)

**Comment by chmst** [comment]
Did you press enter to finish the input?

**Comment by crystalenka** [comment]
@angieradtke is this similar to what you were experiencing?

**Comment by angieradtke** [comment]
Right, that seems to be the issue I have

**Comment by angieradtke** [comment]
The last  element of the array is missing

**Comment by chmst** [comment]
Then I must repeat my question. Did you press enter after typing the tag name? If not, there is no input.

**Comment by angieradtke** [comment]
in my  case I have 25 tags selected, but in the field I can only see 24. 
In the frontend I  can see all 25.  So the last one is missing in the backend. 
If I reorder the tags, i can see that always the last one is missing.
This is why I think it is a wrong counting array. But if I have less than 24 everything is fine.

**Comment by chmst** [comment]
Then I think it is another issue. If I understand this here correctly then the user wants to add a new tag but this new tag is not stored.

**Comment by hytsch** [comment]
Hi all, I can't describe it any better, just repeat that the error exists, and that it only appears after a certain number of tags. It seems important to me to point out that we have deactivated Ajax in the tag option configuration. Now the work with the tags works perfectly. => **AJAX is the problem!**

**Comment by chmst** [comment]
Thank you @hytsch and @angieradtke. Your issues are related and the number of tags is relevant.

**Comment by joomdonation** [comment]
Hopefully PR https://github.com/joomla/joomla-cms/pull/39254 will address this issue. Please help testing. Thanks !
