### ISSUE TITLE
Update extension and part of extension is not correct

### ISSUE THREAD

**Issue by ZhukDmitry** [joomla/joomla-cms#39223]
### Steps to reproduce the issue
If you have component with autoupdate feature, and package (where component is also too) with autoupdate feature and you add update SQL file and create new versions of conponent and package, it tries to execute it twice - when component install, and when package install and fails with error about duplicate columns.

The version of component is the same in a single archive, as in package

### Expected result
Execute SQL file only once

**Comment by ZhukDmitry** [comment]
Close it, I need more tests for this case, probably it is my error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39223">issues.joomla.org/tracker/joomla-cms/39223</a>.</sub>

**Comment by ZhukDmitry** [comment]
I reproduce it. Look only for component
If I add SQL into v1, install it, and after that just create v2 - it tries to execute SQL again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39223">issues.joomla.org/tracker/joomla-cms/39223</a>.</sub>

**Comment by ZhukDmitry** [comment]
Ok. I think I have to rewrite my SQL for new installation and updates. Close my ticket.
I'm sorry for disturb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39223">issues.joomla.org/tracker/joomla-cms/39223</a>.</sub>

**Comment by richard67** [comment]
Closing as stated above.
