### ISSUE TITLE
Link Error in /media/system/html/noxml.html File

### ISSUE THREAD

**Issue by cmbr** [joomla/joomla-cms#39234]
The Help page link in line 17 of the _/media/system/html/noxml.html_ file (_https://docs.joomla.org/Special:MyLanguage/J4.x:Missing_XML_Library_) points to a non-existent page or one without text.

See also [4.0 Redo the fatal error pages #31743](https://github.com/joomla/joomla-cms/pull/31743)

**Comment by brianteeman** [comment]
Can be closed now as I have created a page on the docs server (even if it is not very helpful)
