### ISSUE TITLE
Make Menus in Admin Menu sortable

### ISSUE THREAD

**Issue by ke-communication** [joomla/joomla-cms#39236]
### Steps to reproduce the issue
In Admin Menu > Menus > Site 

The items appear to be sorted by ID descending. Please make them sortable!!!

### Expected result
[menu.png](https://postimg.cc/MfxT5mZ3)

**Comment by crystalenka** [comment]
Thanks for opening the issue! I have this frustration sometimes too :) 

This has come up before here: https://github.com/joomla/joomla-cms/issues/38143

And there is a PR, but it is still in draft: https://github.com/joomla/joomla-cms/pull/38149

Since the PR is in draft I'm leaving the issue open and request other maintainers do the same so we can keep track.

**Comment by codezuma** [comment]
@ke-communication  Is anyone working on this issue. If not can i work on this project.

**Comment by alikon** [comment]
@codezuma feel free to do it 👍

**Comment by chmst** [comment]
@codezuma there ist already someone working on it: And there is a PR, but it is still in draft: https://github.com/joomla/joomla-cms/pull/38149

**Comment by crystalenka** [comment]
> anyone working on this issue. If not can i work on this project.

Hi! Check the PR I linked above, you can contribute and work together on it, or use it as a basis for your own solution. You do not need permission to propose a fix or work on an issue. :)

**Comment by codezuma** [comment]
@crystalenka oh is it i was just checking because i didn't want to do it again in case it was already done.

**Comment by crystalenka** [comment]
> @crystalenka oh is it i was just checking because i didn't want to do it again in case it was already done.

It's not already done, there is in progress work which you can build upon or add to.

**Comment by moonLight-7k** [comment]
I want to contribute in solving this issue

**Comment by chmst** [comment]
Closing this as we have a PR. Please test #38149
