### ISSUE TITLE
RHEL 8.7 and Rocky Linux 8.6 Fails to open Update sites on joomla.org

### ISSUE THREAD

**Issue by jperrygodfrey** [joomla/joomla-cms#39231]
### Steps to reproduce the issue
$ sudo dnf install httpd httpd-tools
$ sudo systemctl start httpd
$ sudo systemctl enable httpd
$ sudo dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
$ sudo dnf install -y https://rpms.remirepo.net/enterprise/remi-release-8.rpm
$ sudo dnf module list php
$ sudo dnf module reset php
$ sudo dnf module enable php:remi-8.1
$ sudo dnf install php php-opcache php-gd php-curl php-mysqlnd php-mbstring php-xml php-pear php-fpm php-mysql php-pdo php-json php-zip php-common php-cli php-xmlrpc php-xml php-tidy php-soap php-bcmath php-devel 
$ sudo systemctl start php-fpm
$ sudo systemctl enable php-fpm
$ sudo setsebool -P httpd_execmem 1
$ sudo dnf install mysql-server
$ sudo systemctl start mysqld
$ sudo systemctl enable mysqld
$ mysql -u root -h localhost -p
mysql>  CREATE USER 'usrjoomla'@'localhost' IDENTIFIED BY 'pAss1@7k(90432';
mysql>  CREATE DATABASE joomla_db;
mysql>  GRANT ALL PRIVILEGES ON joomla_db.* TO 'usrjoomla'@'localhost';
mysql>  exit
$ wget https://downloads.joomla.org/us/cms/joomla4/4-2-5/Joomla_4-2-5-Stable-Full_Package.tar.gz
$ sudo mkdir -p /var/www/html/joomla
$ sudo tar -xvf Joomla_4-2-5-Stable-Full_Package.tar.gz -C /var/www/html/joomla
$ sudo chown -R apache:apache /var/www/html/joomla/
$ sudo chmod -R 755 /var/www/html/joomla/ 
$ sudo nano /etc/httpd/conf.d/joomla.conf
<VirtualHost *:80>
    ServerAdmin admin@vmlocal.local
    DocumentRoot /var/www/html/joomla/
    ServerName vmlocal.local
    ServerAlias vmlocal.local
    ErrorLog ${APACHE_LOG_DIR}/error.log
    CustomLog ${APACHE_LOG_DIR}/access.log combined

    <Directory /var/www/html/joomla/>
            Options FollowSymLinks
            AllowOverride All
            Require all granted
    </Directory>
</VirtualHost>
$ sudo apachectl -t 
$ sudo semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/html/joomla(/.*)?" 
$ sudo semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/joomla/installation/configuration.php-dist'
$ sudo semanage fcontext -a -t httpd_sys_rw_content_t '/var/www/html/joomla/installation'  
$ sudo restorecon -Rv /var/www/html/joomla
$ sudo restorecon -v /var/www/html/joomla/installation/configuration.php-dist
$ sudo restorecon -Rv /var/www/html/joomla/installation
$ sudo chown -R apache:apache /var/www/html/joomla
$ sudo systemctl restart httpd
Open http://vmlocal.local
Setup Joomla
su1234
pAss1@7k(90432
Open Administrator

### Expected result
XML updates show needed updates or no updates needed.

### Actual result
Shows these errors:
Warning
Update: Could not open update site #1 "Joomla! Core", URL: https://update.joomla.org/core/list.xml
Update: Could not open update site #2 "Accredited Joomla! Translations", URL: https://update.joomla.org/language/translationlist_4.xml
Update: Could not open update site #3 "Joomla! Update Component", URL: https://update.joomla.org/core/extensions/com_joomlaupdate.xml

### System information (as much as possible)
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterprise
Description:    Red Hat Enterprise Linux release 8.7 (Ootpa)
Release:        8.7
Codename:       Ootpa
PHP: 8.1
MYSQL Ver 8.0.30 for Linux on x86_64
Server version: Apache/2.4.37 (Red Hat Enterprise Linux)

### Additional comments
I have tested this implementation on Debian 11.5 with PHP 8.1 and mysql 8.0.31 and it does not have this error looking for the XML file.

**Comment by brianteeman** [comment]
This is a server configuration issue. Not a joomla issue

**Comment by jperrygodfrey** [comment]
brianteeman you might think that, but if you review this post and comparisons, there is a pretty good case the Joomla is not performing the get/post the same way on these new Red Hats and Rocky spins.  https://forum.joomla.org/viewtopic.php?f=811&t=997748 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39231">issues.joomla.org/tracker/joomla-cms/39231</a>.</sub>

**Comment by zero-24** [comment]
What happens when you do a plain curl call to the update server XMLs?

**Comment by jperrygodfrey** [comment]
# curl https://update.joomla.org/core/extensions/com_joomlaupdate.xml
<?xml version="1.0" ?>
<updates>
	<update>
		<name>Joomla! Update Component Update</name>
		<description>Joomla Update Component</description>
		<element>com_joomlaupdate</element>
		<type>component</type>
		<client>administrator</client>
		<version>3.6.1</version>
		<infourl title="Joomla!">https://www.joomla.org/</infourl>
		<downloads>
			<downloadurl type="full" format="zip">https://github.com/joomla/joomla-cms/releases/download/3.6.1/com_joomlaupdate-3.6.1.zip</downloadurl>
		</downloads>
		<tags>
			<tag>stable</tag>
		</tags>
		<maintainer>Joomla! Production Department</maintainer>
		<maintainerurl>https://www.joomla.org</maintainerurl>
		<targetplatform name="joomla" version="3.6"/>
	</update>
	<update>
		<name>Joomla! Update Component Update</name>
		<description>Joomla Update Component</description>
		<element>com_joomlaupdate</element>
		<type>component</type>
		<client>administrator</client>
		<version>4.0.2</version>
		<infourl title="Joomla!">https://www.joomla.org/announcements/release-news/5847-joomla-4-0-2-bug-fix.html</infourl>
		<downloads>
			<downloadurl type="full" format="zip">https://downloads.joomla.org/cms/joomla4/4-0-2/com_joomlaupdate-4.0.2.zip</downloadurl>
			<downloadsource type="full" format="zip">https://github.com/joomla/joomla-cms/releases/download/4.0.2/com_joomlaupdate-4.0.2.zip</downloadsource>
			<downloadsource type="full" format="zip">https://update.joomla.org/releases/4.0.2/com_joomlaupdate-4.0.2.zip</downloadsource>
		</downloads>
		<tags>
			<tag>stable</tag>
		</tags>
		<supported_databases mysql="5.6" mariadb="10.1" postgresql="11.0" />
		<php_minimum>7.2.5</php_minimum>
		<sha256>5a16b2e000a0d8723e26fa340ee267bc78070fa85ff916f483f278f0684e3cdf</sha256>
		<sha384>e6c0dad8bfe27817ca3fffdbb2975db11d266bce0decbc7294fba9018235d556a5f536a00ff8f7a43f2d3ad69f9fa285</sha384>
		<sha512>4e51154ed8580dbdeb6d7892ed68af652925415b25ab6b1b1e6a9affffd3abb09caa2f901db7f22570fbf114ca6463986504cbb687734f2a680c2edda68f9bfa</sha512>
		<maintainer>Joomla! Production Department</maintainer>
		<maintainerurl>https://www.joomla.org</maintainerurl>
		<targetplatform name="joomla" version="4.0.1"/>
	</update>
</updates><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39231">issues.joomla.org/tracker/joomla-cms/39231</a>.</sub>

**Comment by jperrygodfrey** [comment]
SELinux on both Red Hat and Rocky are blocking updates.   I set to Permissive via # setenforce 0 and now the updates are working.  I am not sure where to allow this yet while keeping SELinux enforced, but I am working on it.  The help page https://www.linuxshelltips.com/install-joomla-rhel/ did not have the SELinux settings for these updates. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39231">issues.joomla.org/tracker/joomla-cms/39231</a>.</sub>

**Comment by jperrygodfrey** [comment]
So false alarm no bug just a setting in SELinux:

~]# setsebool -P 'httpd_can_network_connect' on<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39231">issues.joomla.org/tracker/joomla-cms/39231</a>.</sub>

**Comment by zero-24** [comment]
closing thanks

**Comment by brianteeman** [comment]
Exactly what I said.
