### ISSUE TITLE
Joomla 3 - Tag Component in tag single item has not given the tag metadescription

### ISSUE THREAD

**Issue by uzielweb** [joomla/joomla-cms#39293]
### Steps to reproduce the issue

Create a TAG and create the metadescrition for it. After this go to the site frontend and browse the tag.
When showing the created tag in frontend, check the description meta in source code from browser.

### Expected result

In the source code needs to appear the created metadescription for the current tag

### Actual result

Nothing is showed or is showed the default site description.

### System information (as much as possible)

PHP 7.4.3
Joomla 3.10.11

**Comment by ReLater** [comment]
Can't confirm. Tested like this.
- Article with TagA. Tag has metadesc "sdsd wwrwq retterte".
- Open article in frontend.
- Click on "TagA".
- I see in source code the description.

![grafik](https://user-images.githubusercontent.com/20780646/203659082-0274036b-716c-4fa7-84dd-f2203771e12b.png)

**Comment by brianteeman** [comment]
Joomla! 3 is in security only mode and there will be no further bug fix releases

**Comment by joomdonation** [comment]
As stated above, Joomla! 3 is in security mode and there will be no further bug fix releases (although as tested by @ReLater, this issue seems to be invalid). I also tested it in Joomla 4 and could not confirm this issue, so I'm closing this issue.
