### ISSUE TITLE
Featured menu item always shows introtext wheter set in options or not

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-cms#39291]
### Steps to reproduce the issue
Create a Menu Item Type >> Featured Articles.
In options Intro text >> set to hide

### Expected result
Intro text does not show on page

### Actual result
Intro text does show

### System information (as much as possible)
J ‎4.2.5

### Additional comments
components/com_content/tmpl/featured/default_item.php
line 86 
<?php echo $this->item->introtext; ?>

should become something like 
<?php if ($params->get('show_intro')) : ?>
	<?php echo $this->item->introtext; ?>
<?php endif; ?>

Thanks
S :)

**Comment by brianteeman** [comment]
The code is working as intended.  When it says "show intro text" it refers to the full article.

For example you have a movie review website. the intro text is a precis of the review that you only want to display on the featured or blog pages but not on the individual article page that you access after clicking on read more

**Comment by saraheagle** [comment]
Oh of course it is! Thanks for your reply.
