### ISSUE TITLE
[4] Media broken with folder named 0 (zero)

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#39307]
### Steps to reproduce the issue

From the file system, create a folder with the name 0. This might be an item inherited from J3.
Select Media from the Administrator menu.

### Expected result

Normal media display.

### Actual result

Error message and no media display.
Property 'name' of argument 'item' of event onFetchMediaItems has a wrong item. Valid: non empty string

### System information (as much as possible)

Linux / Apache 2.4 / PHP 8.1

### Additional comments

Line 66 of administrator/components/com_media/src/Event/AbstractMediaItemValidationEvent.php:
        if (empty($item->path) || !is_string($item->path)) {

**Comment by dgrammatiko** [comment]
please test https://github.com/joomla/joomla-cms/pull/38934

**Comment by brianteeman** [comment]
This is a duplicate report see #37242

**Comment by richard67** [comment]
Closing as duplicate report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39307">issues.joomla.org/tracker/joomla-cms/39307</a>.</sub>
