### ISSUE TITLE
Saving RicheyWeb-AdminExile plugin returns an error

### ISSUE THREAD

**Issue by les3trapelles** [joomla/joomla-cms#39338]
### Steps to reproduce the issue
Save configuration of RicheyWeb-Adminexile plugin.

### Expected result
When you enter to review configuration, it should work correctly

### Actual result
It gives the following:
_An error has occurred.
htmlspecialchars(): Argument #1 ($string) must be of type string, array given_

### System information (as much as possible)
PHP: 8.1.11
Database: mysql
Database version: 8.0.31
Web Server: Apache 2.4.6
Joomla Version: 4.2.5
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36

### Additional comments
The problem occurs on input field about the groups where the plugin should apply. It expects a integer, not an array.

**Comment by brianteeman** [comment]
This should be reported to the maker of that extension,

**Comment by joomdonation** [comment]
As Brian mentioned, you should report this issue to the developer of that plugin so that he can fix it. Closing because this is not a core issue.

**Comment by les3trapelles** [comment]
This plugin has been installed by Joomla, not by me. It has come with version 4.2.5  of Joomla. 
In my opinion, if Joomla adds this plugin in the install zip file, Joomla should work fine or check why it is not working as expected.

**Comment by joomdonation** [comment]
This plugin is not installed by Joomla. It must be installed by an administrator of your site, or you installed a quick start package has that plugin. Try to install a fresh installation of Joomla 4.2.5 if you want, you will see that plugin is not installed/available.
