### ISSUE TITLE
/libraries/src/Language/Text.php Joombla 4.2.5 broken

### ISSUE THREAD

**Issue by Ltamann** [joomla/joomla-cms#39352]
### Steps to reproduce the issue

the comment on top of the file /** Examples: has ?> tags and these are producing that the complete file is converted in comment.

* Examples:
     * `<script>alert(Joomla.Text._('<?php echo Text::_("JDEFAULT", array("script"=>true)); ?>'));</script>`
     * will generate an alert message containing 'Default'
     * `<?php echo Text::_("JDEFAULT"); ?>` will generate a 'Default' string

### Additional comments

easy to repair

**Comment by joomdonation** [comment]
Could you please explain exactly what's broken here? It is not clear to me base on your issue description. I have the feeling that it is broken in your Joomla installation only. So maybe you should check to see if the issue you found is still valid with the latest code from here https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Language/Language.php ?

**Comment by Ltamann** [comment]
I was talking about the Joomla_4.2.5-Stable-Full_Package\libraries\src\Language\Text.php file.
https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Language/Text.php
Maybe its only a problem of my script program displaying the code like wrong, in github it looks fine:
![image](https://user-images.githubusercontent.com/2974923/205481887-c0f10c9c-f40d-49ce-a23a-d0e2af6713df.png)

**Comment by joomdonation** [comment]
Look good on my editor (phpstorm), so if there is anything wrong here, I guess it is a problem with your file or your editor
 
<img width="960" alt="Text" src="https://user-images.githubusercontent.com/977664/205482119-b246dd5f-fc49-4e9f-a1f5-b7e817487521.png">

**Comment by richard67** [comment]
Notepad++ also shows it well here regarding syntax colouring:

![2022-12-04_j4-issue-39352](https://user-images.githubusercontent.com/7413183/205489943-add234a2-7dbb-4385-a6aa-6b16ffa7773a.png)

So it's definitely an issue with your editor.

Closing as not an issue with the CMS code. Feel free to re-open if you think this is wrong.
