### ISSUE TITLE
JEvents - Path cannot be empty

### ISSUE THREAD

**Issue by spravce474** [joomla/joomla-cms#39356]
### Steps to reproduce the issue
I cannot manage events with JEvents v3.6.43, Joomla v3.10.11 and PHP v8.1.7.
I had to go back to Joomla v7.4.13 to manage events.
Everything was working fine before updating to JEvents v3.6.43.
I tried using PHP v8.1.13 but unfortunately no luck.

### Expected result
Working manage events.

### System information (as much as possible)
JEvents v3.6.43, Joomla v3.10.11 and PHP v7.4.13.
![JEvents_error](https://user-images.githubusercontent.com/119840252/205581327-d5462655-85ff-4027-b028-529e8ccb0c48.jpg)

**Comment by joomdonation** [comment]
For this, you should contact the developer of JEvents developer and ask them to fix it. Base on your report, look like the extension is not compatible with PHP 8.1 yet. 

Closing because this is not a Joomla core issue.
