### ISSUE TITLE
Problem with breadcrumbs for List of all tags menu item type / tagged items list

### ISSUE THREAD

**Issue by cyanama** [joomla/joomla-cms#39367]
![baseline3](https://user-images.githubusercontent.com/119266525/205949147-300a3679-7354-4a18-ad35-468e377af12e.png)

Above I have three menus of _List all tags_ type, where **Authors**, **Series** and **Genres** are the parent tag.

![screen shot 2022-12-06 at 17 22 55](https://issues.joomla.org/uploads/1/d45c1eaeb0c0a19db762227a7090420c.png)

Hitting the menu lines works as expected and shows correct breadcrumbs and their list of child-tags

![screen shot 2022-12-06 at 17 30 16](https://issues.joomla.org/uploads/1/6146f060c6906926545e9e7eb6d4ebde.png)

Hitting a child tag from the list, breadcrumbs always show the parent tag for **the second menu line**, in this case 'Series' instead of 'Authors'; same happens for the menus 'Genres' below. Somewhere in the code must be a variable constantly set to the value for the second menu.

### Steps to reproduce the issue
Create a menu with 3 or more menu lines type _List all tags_ and different parent tags
Select menu line 1, 3, 4...
Click onto an item of the result list

### Expected result
breadcrumbs should show the title of the parent tag

### Actual result
breadcrumbs always show title of parent tag in menu line 2

### System information (as much as possible)
J4.25
Firefox 102.5.0
win and os platform

### Additional comments
none

**Comment by joomdonation** [comment]
Confirm that the issue happens with Joomla 4.2. However, look like it was fixed on Joomla 4.3 (there were several PRs improved com_tags for 4.3 merged). Could you please try to test it using Joomla 4.3 nightly build https://developer.joomla.org/nightlies/Joomla_4.3.0-alpha2-dev-Development-Full_Package.zip to see if you can still re-procedure the issue?

**Comment by cyanama** [comment]
Done. The issue is solved with 4.3
Thanks, great job<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39367">issues.joomla.org/tracker/joomla-cms/39367</a>.</sub>

**Comment by alikon** [comment]
please then close this issue

**Comment by cyanama** [comment]
How?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39367">issues.joomla.org/tracker/joomla-cms/39367</a>.</sub>

**Comment by joomdonation** [comment]
Closing because this issue is fixed in 4.3.
