### ISSUE TITLE
Joomla\CMS\Event\AbstractImmutableEvent not immutable

### ISSUE THREAD

**Issue by SharkyKZ** [joomla/joomla-cms#39372]
### What needs to be fixed

`Joomla\CMS\Event\AbstractImmutableEvent` contains working `addArgument`, `setArgument`, `removeArgument`, `clearArguments` methods inherited from `Joomla\Event\Event` making it totally mutable.

### Why this should be fixed
Class name seems inaccurate.

### How would you fix it
Don't extend `Joomla\Event\Event`.

### Side Effects expected
Yes.

**Comment by wilsonge** [comment]
PR https://github.com/joomla/joomla-cms/pull/39469
