### ISSUE TITLE
Backend do not follow the System > Manage Languages > Administrator setting 

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#39386]
Hi guys,  
PHP 8.1.13 + Joomla 3.10.11
System > Manage Languages > Site: Spanish
System > Manage Languages > Administrator: English

I upgraded to Joomla 4.2.5 with success.
But now in the **Backend** some Extensions like "SP Page Builder 4", "Solidres" and also _some Menus_ (and their submenus) into the toggle Menu like "Contents" and "Users" are following the "System > Manage Languages > **Site**: Spanish" setting (in fact, switching it the mentioned languages change).

I enabled the debug mode with Error Reporting to Maximum
I over re-installed Joomla 4 and the Extensions
I switched more times between languages
I cleared Joomla and Browser cache
I tested switching back to PHP 7.4.33

But nothing change. Please, Do you have any ideas ? How can I investigate it ?

**Comment by richard67** [comment]
Have you updated the Spanish language package too after having updated to Joomla 4?

**Comment by brianteeman** [comment]
Based on comments here and elsewhere this appears to be another problem caused by sp page builder. As this is a commercial extension I am unable to verify that but in the absence of any similar reports when NOT using sp page builder I recommend that this is closed.
