### ISSUE TITLE
Error 1615 Prepared statement needs to be re-prepared

### ISSUE THREAD

**Issue by cloudfaction** [joomla/joomla-cms#39392]
### Steps to reproduce the issue

Uncertain. it happens on occasion, i cannot pinpoint when exactly. When i occurs, the entire site is down, and after about 30 seconds it all works again

### Expected result

No error, working site

### Actual result

Site down, and 1615 error

### System information (as much as possible)

J 4.2.5 / PHP 8.0.14 / 10.3.24 MariaDB cll-lve
Linux 192-168-246-187.atm.cloudlinux.com 4.18.0-305.25.1.el8_4.x86_64 #1 SMP Wed Nov 3 10:29:07 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Additional comments

Problem seems isolated to 1 server. could be a hosting issue, but i cannot pinpoint it[systeminfo-2022-12-10T19_19_00+01_00.txt](https://issues.joomla.org/uploads/1/e45650d92431826e91debfa6918a153b.txt)

**Comment by cloudfaction** [comment]
I have this on several websites. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39392">issues.joomla.org/tracker/joomla-cms/39392</a>.</sub>

**Comment by brianteeman** [comment]
See if this helps

https://bobcares.com/blog/1615-mysql-error/

**Comment by richard67** [comment]
… and please report back if it helped.

**Comment by JorisLange** [comment]
With these increased values still problems (but less):
table_open_cache = 4096
table_definition_cache = 4096
We keep you posted.

**Comment by cloudfaction** [comment]
I am asking ISP for details, but problem still appears after Brians suggested fix.

**Comment by chmst** [comment]
Thanks for feedback. I'll close this now.
