### ISSUE TITLE
Smart Search Results Taxonomies

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39390]
### Steps to reproduce the issue
On a monolingual site where all the content is flagged as ALL check the search results

### Expected result
No mention of the Language - Usually there is a check for ismultliang before any language related stuff is displatyed

### Actual result
All results are displated with the useless and confusing "Language: *"

![image](https://user-images.githubusercontent.com/1296369/206765379-393106ac-16b3-4d3d-8143-333b3c3a5519.png)

### Additional comments
It is possible to unpublish the language map and then the "Language: *" disappears BUT as soon as the site is reindexed that content map is republished.

**Comment by Quy** [comment]
Would you consider PR #36867 to be a possible solution?

**Comment by Hackwar** [comment]
No, that PR is not going to solve this issue.

**Comment by Hackwar** [comment]
We have a PR: #39919 Closing issue. Thank you for reporting this problem!
