### ISSUE TITLE
[4.x] Editor-XTD buttons in subform insert content to first row only

### ISSUE THREAD

**Issue by crystalenka** [joomla/joomla-cms#39416]
### Steps to reproduce the issue
1. Create a custom field of type editor. Make sure the "Buttons" option is set to yes. Set the editor to subform only.
2. Create a custom field of type subform. Add the editor field to it. Make sure multiple is set to yes.
3. Edit an article where the field is available.
4. Add 2-3 rows of the subform.
5. On the last subform row, use an editor button ("CMS content" in TinyMCE) to insert something like a menu item.

### Expected result

Content is inserted in the editor field where the button was pressed.

### Actual result

Content is inserted in the editor field in the first row only.

### System information (as much as possible)
J 4.2.6
PHP 8.1

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39449 . Thanks in advance.

**Comment by crystalenka** [comment]
> That kind of "known issue" since subform exist, there no easy fix for it currently.
> 
> 
> 
> Work around:
> 
> - add rows that you need,
> 
> - save the article
> 
> - now buttons should work

There's a PR open :) also that's not accurate, it also happens after saving.

**Comment by Fedik** [comment]
hmhm, It worked in j3?
