### ISSUE TITLE
[J4.2.5] Language string wrong (&hellip;)

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#39410]
There is an error in a language string at the quick items 

### What needs to be fixed
<img width="286" alt="grafik" src="https://user-images.githubusercontent.com/828371/207358161-81b15500-2520-4fc9-a5ea-1bcfe2826a48.png">

I think the &hellip; is not on purpose there?

**Comment by Kostelano** [comment]
Up to a couple https://github.com/joomla/joomla-cms/issues/38991

**Comment by chmst** [comment]
Closing as duplicate, but thanks for this description and screen @coolcat-creations. This makes things clearer.
