### ISSUE TITLE
[BUG][J4] SmartSearch unpublished categories  in search results

### ISSUE THREAD

**Issue by angieradtke** [joomla/joomla-cms#39415]
Is it possible that unpublished categories are still available  in the search results?
In my case I have lots of content in lots of categories. 
If I unpublish a category, this category is still in  the index.

**Comment by simbus82** [comment]
Does this also happen after re-indexing?

**Comment by Quy** [comment]
@angieradtke Please advise if this is still an issue. Thanks.

**Comment by Quy** [comment]
Closing as not a bug. Thanks for the prompt confirmation!
