### ISSUE TITLE
Joomla Update Error Message - Get Help Link gives a 404 Error

### ISSUE THREAD

**Issue by nineoo** [joomla/joomla-cms#39425]
### Steps to reproduce the issue
Update from Joomla 4.2.5 to 4.2.6 halted with an error message.

Three options in error message - Resume Update, Restart Update or Get help with this error

### Expected result

On clicking the Get help button expected a dialogue box or help page.

### Actual result

Returned a 404 error on the page at [Your text to link here...](https://help.joomla.org/proxy?keyref=Help42:JHELP_COMPONENTS_JOOMLA_UPDATE&lang=en "Get help link")
![screen shot 2022-12-15 at 14 59 32](https://issues.joomla.org/uploads/1/c9848a449d847848769969dee810c87b.png)
![screen shot 2022-12-15 at 14 59 32](https://issues.joomla.org/uploads/1/4cf2a9a64a35ce69151b04f8ec3e0c77.png)

### System information (as much as possible)
PHP Built On	Linux uk604.directrouter.com 2.6.32-954.3.5.lve1.4.89.el6.x86_64 #1 SMP Sat May 7 10:18:11 UTC 2022 x86_64
Database Type	mysql
Database Version	10.3.25-MariaDB
Database Collation	utf8mb4_general_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	No
PHP Version	8.0.26
Web Server	LiteSpeed
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 4.2.6 Stable [ Uaminifu ] 13-December-2022 15:00 GMT (after update from 4.2.5)
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

### Additional comments
Don't know if this is the wrong link in the error message or a problem with the document/page it links to.

Update successful on clicking the Resume Update button.

2 screenshots attached.

**Comment by richard67** [comment]
The issue has already been reported here: #35668 . The screenshot looks a bit different because made before the implementation of enhancements for the updater, but the reason is the same.

Closing as duplicate report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39425">issues.joomla.org/tracker/joomla-cms/39425</a>.</sub>

**Comment by nineoo** [comment]
Thank you Richard.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39425">issues.joomla.org/tracker/joomla-cms/39425</a>.</sub>
