### ISSUE TITLE
Unable to install Joomal CMS via CLI installation

### ISSUE THREAD

**Issue by ddevopsrepos** [joomla/joomla-cms#39420]
### Steps to reproduce the issue

I am following this link to install joomla CLI installation 

https://docs.joomla.org/J4.x:Joomla_CLI_Installation#Requested_Information_on_Install_Joomla

### Expected result
php installation/joomla.php install

### Actual result
Install Joomla to run cli commands

Kindly guide me on how i can install Joomla via CLI the above link is not valid, if not kindly guide me on what step I am missing 

Steps I am following up 

Download the joomla.zip 
extract it on webroot 
executing the cli command
php cli/joomla.php install --site-name=

Regards
Syed Ejaz

**Comment by brianteeman** [comment]
You missed the first line on that page
> Starting with Joomla! 4.3, the Joomla CLI installation is available.

**Comment by richard67** [comment]
Closing as expected behavior. See comment above.
