### ISSUE TITLE
[4.2.6] Email cloaking fails.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#39422]
#### Joomla 4.2.5 and 4.2.6
- Check that plugin "Content - Email Cloaking" is enabled and setting "Mode" is "As linkable mailto address" (= standard setting).
- Open an article.
- Switch editor to HTML-Code view.
- Paste `<p>info@example.com</p>`.

![grafik](https://user-images.githubusercontent.com/20780646/207825558-2397716c-88e1-4117-8a34-9237c67f5b3f.png)

- Save article without switching back to normal view.
- Open article in front-end.

### Expected result
- With JS enabled in browser

![grafik](https://user-images.githubusercontent.com/20780646/207824123-9a0c7450-60d2-4184-a8be-272a7e283693.png)

- With JS disabled in browser

![grafik](https://user-images.githubusercontent.com/20780646/207824348-c47f244b-ab03-4e5f-9925-bb4fb86e8b0c.png)

#### Joomla 4.2.6
- With JS enabled or disabled

![grafik](https://user-images.githubusercontent.com/20780646/207824660-aed88848-c92f-453d-a8fd-f8d99e443892.png)

### Additional comments
There are other scenarios where cloaking doesn't work anymore like in 4.2.5.

Only if there's already a `mailto` link set in editor it looks like cloaking works.

From German forum: A user reports that `<a href="#">info@example.com</a>` isn't cloaked in their case. In a mod_custom module with "Prepare Content" activated.

**Comment by brianteeman** [comment]
What mode is the Email Cloaking plugin set to?

**Comment by ReLater** [comment]
Standard: "Add mailto".

I've tested it now on 3 sites (several will follow). Replacing `plugins/content/emailcloak` folder with 4.2.5 variant brings back cloaked emails on all concerned pages, like it was before update to 4.2.6 (that removed cloaking and click functionality).

Exchanging JavaScripts was not needed in my case (because I never use specific CSS classes or so), but blank email addresses. See: https://github.com/joomla/joomla-cms/pull/36269

**Comment by brianteeman** [comment]
>> What mode is the Email Cloaking plugin set to?

> Standard: "Add mailto".

Thanks for confirming

**Comment by ReLater** [comment]
@LukasHH Could you please look at this issue?

**Comment by ReLater** [comment]
Both email examples in opener post [fail with $pattern](https://github.com/joomla/joomla-cms/blob/4.2.6/plugins/content/emailcloak/emailcloak.php#L444)

`~<[^<]*(?<!\/)>(*SKIP)(*F)|(<\w.*\"' . $searchEmail . '\".*\/\>)~i`

4.2.5 was

`~<[^<]*>(*SKIP)(*F)|' . $searchEmail . '~i`

**Comment by LukasHH** [comment]
I need to take another look at why I had changed the pattern.
I think that it was not recognized correctly when an email it is entered as a placeholder or title attribute.

Example:
`<img src="/images/joomla_black.png" alt="" class="img-thumbnail" style="border: 1px solid #00f;" title="[email@example.org](mailto:email@example.org)" />`

and

`<input type="text" placeholder="[email@example.org](mailto:email@example.org)" />`

**Comment by LukasHH** [comment]
I think what might work would be the following pattern:
`~<[^<]*(?<!\/)>(*SKIP)(*F)|(<\w.*\"' . $searchEmail . '\".*\/\>)|' . $searchEmail . '~i`

But you have to test it more exactly.
https://regex101.com/r/PJpBIQ/1

**Comment by brianteeman** [comment]
it is not just the cloaking that fails. The ability for a simple typed email address in content being automatically converted to a mailto link also does not happen. This is a major loss of functionality.

**Comment by LukasHH** [comment]
The pattern in line 444 was about obfuscating email addresses specified as placeholders or in the title attribute. These are also not returned as a mailto link. That would not fit in these places.

For the case specified in the issiu, an additional pattern would have to be added as it was before.

But I am still there to build a pattern for the case of this specification:
`<li title="email@example.org">email@example.org</li>`
or
`<a title="email@example.org" href="#">email@example.org</a>`
These do not currently work with any of the previous patterns.

**Comment by ReLater** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/39508
