### ISSUE TITLE
Use fancy select for filters

### ISSUE THREAD

**Issue by JackKellyUK** [joomla/joomla-cms#39426]
### Is your feature request related to a problem? Please describe.

This has mainly been an issue for me when a site has a large number of menu items. When attempting to filter for modules by menu item it can quite hard to find what you are after.
![image](https://user-images.githubusercontent.com/55460781/207958183-62de7f65-2664-4efe-9696-44d4211eb649.png)

### Describe the solution you'd like

Use the fancy select layout for the module filters or possibly all filters across Joomla.
![image](https://user-images.githubusercontent.com/55460781/207958705-c250b35b-3690-4937-adca-28f71969a9a5.png)

### Additional context
Would be happy to work on this

**Comment by chmst** [comment]
> Would be happy to work on this

Thank you - Just do it!

**Comment by micker** [comment]
Great idea

**Comment by crystalenka** [comment]
Agree with @chmst — if you want to work on this, go for it! Let us know if you need any pointers or have questions. :)

**Comment by richard67** [comment]
Closing as having a pull request. See #39456 .
