### ISSUE TITLE
[4.x] Replace or remove an old non-existent bootstrap class

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#39423]
### Steps to reproduce the issue

Nowadays joomla uses bootstrap 5. The used class="label" is a call from a previous bootstrap version and no longer exists.
See module: **Language Switcher**

### Expected result
For example:
`<span class="badge bg-light text-dark" title="<?php echo $language->title_native; ?>"><?php echo strtoupper($language->sef); ?></span>`
or
`<span class="badge bg-secondary" title="<?php echo $language->title_native; ?>"><?php echo strtoupper($language->sef); ?></span>`

### Actual result

`<span class="label" title="<?php echo $language->title_native; ?>"><?php echo strtoupper($language->sef); ?></span>`

### System information (as much as possible)

J4: [See file](https://github.com/joomla/joomla-cms/blob/cf218445e1b16ec9172a1c98dbcb0147f6c0d49a/modules/mod_languages/tmpl/default.php#L90 "https://github.com/joomla/joomla-cms/blob/cf218445e1b16ec9172a1c98dbcb0147f6c0d49a/modules/mod_languages/tmpl/default.php#L90")

### Additional comments

This is probably an old class from bootstrap 3.

**Comment by ayushanand16** [comment]
@sandewt I would like to work on this issue.

**Comment by brianteeman** [comment]
and how you do know that someone is not using that class in their template?

**Comment by sandewt** [comment]
> and how you do know that someone is not using that class in their template?

- I used this class in the past, but switched to the bootstrap 5.0 badge class.
- I encountered the class="label" in the libraries of @regularlabs.

The question is whether we should allow this obsolete class="label" to continue. I would suggest remove and replace this class.
In addition, the badge class is used extensively in J4.

Bootstrap 3 (obsolete): https://getbootstrap.com/docs/3.3/components/#labels

Bootstrap 5 (current): [https://getbootstrap.com/docs/5.0/components/badge/](url)

**Comment by sandewt** [comment]
> @sandewt I would like to work on this issue.

@ayushanand16 Of course, that's up to you :smiley:

**Comment by brianteeman** [comment]
> I encountered the class="label" in the libraries of @regularlabs.

and that is the perfect example of why it should not be removed.

I do remember someone went thourgh and changed label to badge BEFORE j4 was released but the must have missed this one.

**Comment by regularlabs** [comment]
I don't mind the use of `class="label"` being removed from Joomla.
There was indeed one occurrence in my code that was mimicking the HTML of the language label in Joomla.
I have already changed it in my code (which will be pushed into next versions).

Currently the Joomla admin template gives no CSS styling to the `label` class.
So this could only be a minor 'issue' for custom/3rd-party admin templates that do include specific styling for that.
Buy changing `class="label"` to `class="badge bg-secondary"` would in my view not cause any issues. As other admin templates would also have CSS for that (as it is used a lot in other places in Joomla).

**Comment by sandewt** [comment]
Another argument, to change the class name:

Line 90 is completely identical to line 105, with the only difference being the classes. Perhaps something went wrong here in the past?

https://github.com/joomla/joomla-cms/blob/cf218445e1b16ec9172a1c98dbcb0147f6c0d49a/modules/mod_languages/tmpl/default.php#L90

https://github.com/joomla/joomla-cms/blob/cf218445e1b16ec9172a1c98dbcb0147f6c0d49a/modules/mod_languages/tmpl/default.php#L105

**Comment by chmst** [comment]
I am fine with this change.

**Comment by legendary0911** [comment]
i would like to work on this issue

**Comment by sandewt** [comment]
> @sandewt I would like to work on this issue.

> i would like to work on this issue

All initiatives are appreciated

**Comment by sandewt** [comment]
> and that is the perfect example of why it should not be removed.

A new insight is that this is (possibly) a b/ c break .
See #39568

**Comment by sandewt** [comment]
b/ c break
