### ISSUE TITLE
Function strftime() is deprecated

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#39430]
### Steps to reproduce the issue
use PHP version 8.1.x on your site
create (or change) a form calendar field by either removing the optional translateformat parameter (in that case it default to false, or setting it to false > translateformat="false"

### Expected result
No deprecated message

### Actual result
Deprecated: Function strftime() is deprecated in [root]/libraries/src/Form/Field/CalendarField.php on line 273

### System information (as much as possible)
J4.2.6
PHP 8.1.13

**Comment by brianteeman** [comment]
#38276

**Comment by chmst** [comment]
Closing as duplicate.

**Comment by joomdonation** [comment]
@Ruud68 Just saw this from the linked issue. In your case, if you use you a Calendar form field `translateformat="false"`, you can prevent warning by adding `filterformat` attribute to the field. The `filterformat` must provide equivalent format with the format defined in `format` attribute of the field. For example

```xml
<field
	name="test"
	type="calendar"
	label="Test Calendar"
        format="%Y-%m-%d %H:%M:%S"
        filterformat="Y-m-d H:i:s"
	showtime="true"
	filter="user_utc"
/>
```
Hope this helps.

**Comment by Ruud68** [comment]
Thanks Tuan for following up
