### ISSUE TITLE
Impossible to update «Italian» Language Pack 

### ISSUE THREAD

**Issue by crimle** [joomla/joomla-cms#39455]
### Steps to reproduce the issue
Make sure you have the Italian Language Pack installed.
Go to System > Update > Extensions 
Click [Check for updates] unless the availability of «Italian 4.2.6.1» is already displayed
Install the update
Click [Check for updates] again

### Expected result
The Italian Language Pack should have been installed all right. 

### Actual result
The availability of «Italian 4.2.6.1» keeps being displayed. It seems to be impossible to install the update properly.

### System information (as much as possible)
Joomla 4.2.6
PHP 8.1.13
MySQLi 10.4.26-MariaDB-log

**Comment by richard67** [comment]
@crimle That's an error in the lanuage pack. The responsibles for the language pack haven't updated the version number in their XML file so after the update Joomla still sees the old version and so finds again the update.

**Comment by crimle** [comment]
Ok, thank you. Is it possible to assign this bug report to the team concerned? Or what else should I do?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39455">issues.joomla.org/tracker/joomla-cms/39455</a>.</sub>

**Comment by richard67** [comment]
I've sent a message to the coordinator of the Italian translation team listed on our languages download page https://downloads.joomla.org/language-packs/translations-joomla4 .

Closing as not an issue with the CMS core.

**Comment by Razzo1987** [comment]
We are working on it. Thanks
