### ISSUE TITLE
plg_system_privacyconsent setting error to not existing object

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#39460]
### Steps to reproduce the issue
When deleting a user, plg_system_privacyconsent will act on the onUserAfterDelete triggered event.
it will delete any user consents for the user that is being deleted.

If there is an error in this deletion, it will set an error to $this->_subject
```
            } catch (Exception $e) {
                $this->_subject->setError($e->getMessage());
            }
```
but this will throw an error as $this->_subject doesn't exist

![screen shot 2022-12-21 at 13 13 34](https://issues.joomla.org/uploads/1/22a93bdd569a67a22c0e98d97a46ba38.jpg)

### Expected result
no error / error bubled up as message?

### Actual result
error
![screen shot 2022-12-21 at 13 18 10](https://issues.joomla.org/uploads/1/a70ce1997f6527d3ee6a3f43c959c75d.jpg)

### System information (as much as possible)

Joomla 4.2.6

**Comment by joomdonation** [comment]
Maybe we should log the error like how it is implemented here https://github.com/joomla/joomla-cms/blob/4.2-dev/administrator/components/com_admin/src/Model/SysinfoModel.php#L448-L455 ?

**Comment by Hackwar** [comment]
The code has since been refactored and the problematic stuff has been removed. Closing this issue.

**Comment by Hackwar** [comment]
And of course: Thank you @Ruud68 for reporting this!
