### ISSUE TITLE
Privacy Consent Deprecated messages

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#39468]
Hi guys, 
PHP 8.1.13 + Joomla 4.2.6
Global Configuration > System > Debug System: enabled & Server > Error Reporting: Maximum

- In Backend I created a new Joomla User
- Logging in the Frontend I had back an Error 404 - I add an image here for you. 

![Error-404](https://user-images.githubusercontent.com/14607633/209046834-0c085a40-5016-46a9-9079-37f154b08905.png)

- So, I created a oomla User Profile menu item
- Then, Logging in the Frontend I have back these Deprecated Messages:

Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in/home/…/plugins/system/privacyconsent/privacyconsent.php on line 304

Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in/home/…/plugins/system/privacyconsent/privacyconsent.php on line 305

Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in/home/…/plugins/system/privacyconsent/privacyconsent.php on line 306

Deprecated: substr(): Passing null to parameter #1 ($string) of type string is deprecated in/home/…/plugins/system/privacyconsent/privacyconsent.php on line 307 

I suppose it is something "connected"  "similar" to #38791 and #39460

**Comment by richard67** [comment]
The call stack shows a third party plugin (opengraph) being involved. Does that issue also happen without that plugin?

**Comment by joomdonation** [comment]
@joomleb The 404 error causes by third party plugin opengraph as mentioned by @richard67 
For the warnings in Privacy Consent plugin, it should be fixed by PR https://github.com/joomla/joomla-cms/pull/39475 . Please help testing. Thanks !
