### ISSUE TITLE
[4.2x] Menu item of type Featured Articles does not have a layout option

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#39462]
### Is your feature request related to a problem? Please describe.
When creating a category blog there is an option - under the Options tab - to select a layout for the items (i.e. articles)
A Featured Articles menu item type is a variation of a blog, but there is no "Default layout to use for items." 

### Describe the solution you'd like
Add the option to select a layout for items

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39467 . Thanks in advance.
