### ISSUE TITLE
Language String Problem with Menu Heading Menu Type

### ISSUE THREAD

**Issue by JoomlaTema** [joomla/joomla-cms#39470]
### Steps to reproduce the issue
Joomla 4.2.6 create a new menu item select System Links >> Menu Heading type the language string of Options Tab does not display properly it displays constant as "COM_MENUS_PAGE-OPTIONS_FIELDSET_LABEL"  see attached image. I have searched for language string whole package with text-search tool and found nothing.
image
https://prnt.sc/snrVNXAs7bCG

### Expected result
It should be Options

**Comment by ReLater** [comment]
I can't confirm this issue.

Your image shows more than only the 3 common tabulator labels:
- Details
- Link Type
- Options

Therefore, I suspect that the error comes from a non-core plugin or similar.

**Comment by Kostelano** [comment]
This is created by a third party extension.

**Comment by brianteeman** [comment]
This must be coming from that etxension
The core Headings menu type does not even have an options tab ;)

**Comment by chmst** [comment]
And the string is not consistent with "-".  
The string could be generated automatically, so you could search for "OPTIONS_FIELDSET_LABEL" only in the whole package.

**Comment by joomdonation** [comment]
Closing because it is not an issue with Joomla core issue as states above.
