### ISSUE TITLE
#__template_styles.param field type

### ISSUE THREAD

**Issue by yasen-petrov** [joomla/joomla-cms#39471]
### Steps to reproduce the issue
Attempt to save custom CSS into Purity III template. CSS in question is 250+ KB

### Expected result
Custom CSS is saved

### Actual result
Save failed with message: "Save failed with with the following error: Data too long for column 'params' at row 1"

### System information (as much as possible)
Joomla 2.5

### Additional comments
field type for #__template_styles.params being LONGTEXT will fix the problem (client of ours does have style sheet too big for TEXT format)

**Comment by wilsonge** [comment]
This is a won’t fix for us I’m afraid. The bug here is the template saving css into the database rather than loading it into a native file. Storing it and retrieving something that large from the database is significantly worse than storing to file.

**Comment by brianteeman** [comment]
and joomla 2.5 is dead amd buried
