### ISSUE TITLE
table name needs to be quoted

### ISSUE THREAD

**Issue by Kurantje** [joomla/joomla-cms#39487]
### Steps to reproduce the issue
Create a component (com_xxx) using a table with a special character, e.g. da-events
Go to ...?option=com_xxx&view=event&layout=edit&id=1 to get the first element from the table

### Expected result
Get in edit.php the data from the da-events table for id=1

### Actual result
Exception informing about sql syntax error (without insight in the actual query causing the error)

### System information (as much as possible)
Joomla! Version	4.2.6
PHP Version	8.0.13
Database	Server		mysql
		Version		10.3.28-MariaDB-cll-lve
		Collation	latin1_swedish_ci
		Conn Collation	utf8mb4_general_ci

### Additional comments
The problem is in libraries/src/Table/Table.php
On line 734 it states:  ->from($this->_tbl);
This should be:         ->from($this->_db->quoteName($this->_tbl));

**Comment by richard67** [comment]
@Kurantje Good catch. Do you want to create a pull request with your proposed fix so you get the flowers at the end? Especially for a small change in one file it's easy to do it directly here on GitHub, see https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests for a description.

**Comment by Kurantje** [comment]
@richard67 thanks. I've created the pull request in the 4.2-dev branch. Does it then also get carried over to the 4.3-dev branch? OR should I also do a pull request for that one?

**Comment by richard67** [comment]
@Kurantje It will be merged up into the 4.3-dev branch sooner or later after it has been merged into 4.2-dev. I close this issue here as we normally do that when having a PR for an issue. Thanks.
