### ISSUE TITLE
[4.2.6] PHP8.2. Fatal error by deprecated message from portable-utf8 with XDebug

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#39512]
### Steps to reproduce the issue
- I'm using Bearsampp, Win10 Pro, PHP8.2, Joomla 4.2.6. I wasn't aware that XDebug is activated in Bearsampp (and I don't know how to turn it off at the moment) ;-) So I needed a while to understand what is happening.

- XDebug is throwing a deprected message

> Deprecated: Using ${var} in strings is deprecated, use {$var} instead in libraries\vendor\voku\portable-utf8\src\voku\helper\UTF8.php on line 4653

- which crashes front-end and back-end afterwards with error message

> Failed to start the session because headers have already been sent by "libraries\vendor\voku\portable-utf8\src\voku\helper\UTF8.php" at line 4653.

Replacing all `${chars}` with `{$chars}` in UTF8.php solved the issue. But it's a vendor library where Joomla or whatever is loading v5.4.51 where this PHP82 fix is not included: https://github.com/voku/portable-utf8/pull/181 (v6.0.?).

**Comment by wilsonge** [comment]
https://github.com/wamania/php-stemmer/pull/26 Looks like it's going to be tricky because this compat release is going to require a higher library version. @zero-24 we might need to put something in joomla-backports

**Comment by zero-24** [comment]
Looks like @SharkyKZ already raised that with the maintainers, lets see how they react. Not happy to branch it out just for such a non reason but please let me know as soon as you notice that a decision is taken on that topic by them and I can create a repo on joomla-backports when we do need it.

**Comment by SharkyKZ** [comment]
FWIW, it already requires PHP 7.3 since 3.0. Although that's only because of a bump in phpunit dev dependency. There have been no code changes so it's still very much PHP 7.0 compatible.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/35200

**Comment by Hackwar** [comment]
I asked @wamania if he could do a new release: https://github.com/wamania/php-stemmer/issues/30

**Comment by Hackwar** [comment]
And there actually already is a PR for this: https://github.com/wamania/php-stemmer/pull/26

**Comment by Hackwar** [comment]
And the fix for us is here: #39955
Please test this PR and I'm closing this issue.
