### ISSUE TITLE
[4.2.6] - Unable to save/edit articles with umlauts in filenames during frontend editing

### ISSUE THREAD

**Issue by tgurr** [joomla/joomla-cms#39515]
### Steps to reproduce the issue
Using frontend editing. Try to edit an existing article or create a new one and add for example a picture with umlauts in its file name. This only appears to affect frontend editing, the same works fine when editing the article in the backend as administrator.

1. Add a picture
![01_add_picture](https://user-images.githubusercontent.com/414984/209810333-4dbf7d13-56d7-42f1-857b-8512ad86db64.png)
2. Pick a picture with umlauts
![01_pick_file_with_umlauts](https://user-images.githubusercontent.com/414984/209810354-71ffbb0a-04bb-4c90-b533-f06b86ddef2e.png)
3. Try to save the article
4. Experience the following error:

![Screenshot_20221228_123303](https://user-images.githubusercontent.com/414984/209810493-1d31601d-d395-417d-8dbe-d49860c3c04b.png)

![Screenshot_20221228_123230](https://user-images.githubusercontent.com/414984/209810513-dccae9c9-8da6-4263-9791-21b9a08101bc.png)

It's reproducible when creating a new article just consisting of the following code:

`<p><img src="dateien/103/images/jubiläum_november_2015.jpg" alt="jubilaeum november 2015" style="margin: 5px 20px;"></p>`

When first renaming the file replacing umlauts the same works fine.

### Expected result
No error - work like before in Joomla 3.x

### Actual result
Experience a timout/fatal error

### System information (as much as possible)
From Joomla system information:
* Database: 10.5.18-MariaDB
* Database charset: utf8_general_ci
* Database connection charset: utf8mb4_general_ci
* PHP: 8.0.26 (but also reproducible on 7.4.33)
* Default Cassiopeia template
* JCE Editor

### Additional comments
This wasn't an issue and worked fine before in Joomla 3.x before upgrading to Joomla 4.x. Raising the PHP execution timeout also doesn't help as the PHP-FPM process is taking 100% CPU no matter how long it runs until running into the timeout/error.

**Comment by tgurr** [comment]
Apparently this issue has already reported before https://github.com/joomla/joomla-cms/issues/39193 and would be fixed by https://github.com/joomla-framework/filter/pull/50 if it would be merged instead of the bugreport just being closed as completed where it is **NOT**. Found this after searching for another problem and stumbling upon https://www.joomlacontenteditor.net/support/forum/109751-photo-filename-with-umlauts-cannot-save-article which mentioned the bugreport and the PR.

**Comment by deltapapa01** [comment]
Hello,
I can confirm the error.
I have tested it with a different editor, template and language.
However, the articles can be saved as Super User, everything below (so as Admin) does not work. So after pressing save nothing happens, no error output at all.
I use Joomla 4.3 and PHP 8.2.0

Hope https://github.com/joomla/joomla-cms/issues/39193 will be reopen!

WBR,
deltapapa

**Comment by richard67** [comment]
Closing as having a pull request. Please test #41451 . Thanks in advance.
