### ISSUE TITLE
Deprecated: strpos(): Passing null to parameter # 1 ($haystack) of type string is deprecated in [root]/plugins/content/loadmodule/loadmodule.php on line 58

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#39514]
### Steps to reproduce the issue

Issue started after update to Joomla 4.2.6 and is due to change #38977 

call HTMLHelper::_('content.prepare', null, '', 'test');

above test is only to show the error, a component is able to push null to the function, e.g. when the value comes from parameters and the parameter is not set it will return null.

Deprecated: strpos(): Passing null to parameter # 1 ($haystack) of type string is deprecated in [root]/plugins/content/loadmodule/loadmodule.php on line 58

when doing a dump of $article in the plugin it shows $article->text = null

### Expected result
no warning

### Actual result
Deprecated: strpos(): Passing null to parameter # 1 ($haystack) of type string is deprecated in [root]/plugins/content/loadmodule/loadmodule.php on line 58

### System information (as much as possible)

Joomla 4.2.6
PHP 8.1

### Additional comments

this can be fixed by also checking on !is_null($article->text).
```
if (!is_object($article) || !property_exists($article, 'text') || is_null($article->text)) {
```

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39522 . Thanks in advance.
