### ISSUE TITLE
Fatal error when using recurrent HTMLHelper::_()

### ISSUE THREAD

**Issue by carlitorweb** [joomla/joomla-cms#39529]
### Steps to reproduce the issue
**The example is using the module Articles Category, but I think can be any extension or process who do something similar.**

Using the module Articles Category, put the _Count_ option inside the Filtering Options tab, with 3 or more (you can put 0 in this way will show all articles). Also, inside the Display Options tab, _show_ the introtext.

### Expected result
The module show the articles in the fronted

### Actual result
```log
Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 8192 bytes) in....
```

### Additional comments
Checking the code I think is related with the load method `HTMLHelper::_(...)`. 
I copy and paste the content of the method `Joomla\CMS\HTML\Helpers\Content::prepare()` directly inside the Helper class of the module (without the need of use `HTMLHelper::_('content.prepare'......)`) and all worked as expected....But really could not catch where the error is happening.

**Comment by richard67** [comment]
@carlitorweb Do you see the call stack when switching on debug in global configuration?

**Comment by carlitorweb** [comment]
> @carlitorweb Do you see the call stack when switching on debug in global configuration?

No, unfortunately the page do not show the call stack. Just a white page with the error.

**Comment by Fedik** [comment]
> No, unfortunately the page do not show the call stack. Just a white page with the error.

So it Joomla 3 right? Can you please test the same on joomla 4

The error may be dute to a huge amount of content in your articles or one of them, (especialy when you set to "show all articles").
Can happen when one of articles contain huge base64 encoded image, or some kind of copy-paste from MS Office.

**Comment by carlitorweb** [comment]
@Fedik no, is J4 and sample test data from a test site. I tried with xdebug to track the problem, but really not lead me to any place (I will upload some screenshot if you want of this)

**Comment by Fedik** [comment]
Okay, strange then. No need screenshot.

**Comment by Fedik** [comment]
I just checked, you can get a recursion when you show all child categories, and because one of Article is a demo for "Article category" module it tries to render all over again, you get a loop.

Do you have this issue on real world site?

**Comment by carlitorweb** [comment]
I raise well enough the PHP memory but did not fixed the problem.

Then when debug the error, the first stop is here. But from there not lead me to any place really...maybe is me who not see well the problem

![Captura](https://user-images.githubusercontent.com/3956472/211151476-8b0fd05a-5f0a-41ed-b3b5-b20f3c6bceb9.PNG)

**Comment by Fedik** [comment]
What happens when you set option "Child Category Articles" to "exclude"?

**Comment by carlitorweb** [comment]
> Do you have this issue on real world site?

No, with bugtesting site I have. A cloned one.

> I just checked, you can get a recursion when you show all child categories, and because one of Article is a demo for "Article category" module it tries to render all over again, you get a loop.

Interesting, let me check this

**Comment by carlitorweb** [comment]
> What happens when you set option "Child Category Articles" to "exclude"?

I had already on exclude. But I understand what do you mean, and then this only happen in a test site.

**Comment by carlitorweb** [comment]
Yep, is that. I removed from the module the categories who render in their article content, another module, and all is working. 
Good catch @Fedik with the loop.

**Comment by carlitorweb** [comment]
I will close the isse, but not sure if this classify as a bug? A module who render itself in a loop...

**Comment by Fedik** [comment]
I think we cannot prevent such recursion.
