### ISSUE TITLE
[4.2] Subform filter UX

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39531]
### Steps to reproduce the issue
There is a filed filter for subforms but it doesnt match the other filters AND when selected you cant tell what the filter is for

![image](https://user-images.githubusercontent.com/1296369/210168533-0e7206cb-7544-43b8-a8f5-9572764f5966.png)

![image](https://user-images.githubusercontent.com/1296369/210168538-8a2f2361-7491-431b-903a-010937871eaa.png)

![image](https://user-images.githubusercontent.com/1296369/210168539-6ced5131-03d2-43df-922c-611cb6732045.png)

I would change it myself but I dont understand what the opposite for "yes" is in this filter or is there not really a yes and it should simply  be

```
- Use in Subform - 
Subform Only
```

**Comment by joomdonation** [comment]
When you setup a custom field, there is a setting called **Only Use In Subform**:

- If set to No, it is a standard custom field.
- If set to Yes, it will be a special field which can only be used as a **child** field of a **Subform** custom field only. This field won't be displayed on add item screen (for example new article form) like the other standard custom fields, it is just a child of Subform custom field.

For the filter, it has three options :

- Only Use In Subform: Both field types will be displayed
- Yes: Only fields which can only be used on Subform custom fields will be displayed
- No: Only standard fields will be displayed.

Not sure if it answers your question?

**Comment by richard67** [comment]
So the value „Only Use In Subform“ means nothing is selected for filtering and is maybe just the repeated name of the option. Maybe if should be replaced by „Both“ or „Any“ or „Nothing selected“ or something like that. And maybe the „Yes“ and „No“ values should also be changed?

**Comment by brianteeman** [comment]
> For the filter, it has three options :
Only Use In Subform: Both field types will be displayed
Yes: Only fields which can only be used on Subform custom fields will be displayed
No: Only standard fields will be displayed.


no - the first of those is not an option - its just a description of the filter and has no value - just like all the other filters

@richard67 yes you understand the problem correctly and it really should display something more meaningful than yes/no as we don't display the filtername. Just saying yes - as shown in the screenshot - has no meaning
```

- Use in Subform -
   Use Only in Subform
   USe in Any form
```

??

**Comment by chmst** [comment]
Or this?

- Use in Subform -
   Only in Subform
   In Any form
