### ISSUE TITLE
JApplicationDaemon can't find its own class, DemonApplication sets incorrect class as signal handler.

### ISSUE THREAD

**Issue by dmb0058** [joomla/joomla-cms#39533]
### Steps to reproduce the issue

Code attached in file below, JApplicationCli invocation works, JApplicationDaemon throws exception.

### Expected result

```
$ php test.php
pages: 1
```

### Actual result

```
$ php test.php -d

PHP Warning:  pcntl_signal(): Specified handler "DaemonApplication::signal" is not callable (class 'DaemonApplication' not found) in /var/www/game.conlucra.com/public_html/libraries/src/Application/DaemonApplication.php on line 886
```

### System information (as much as possible)
```
PHP Built On	Linux ip-172-30-2-137 5.15.0-1026-aws #30-Ubuntu SMP Wed Nov 23 14:15:21 UTC 2022 x86_64
Database Type	mysql
Database Version	8.0.31-0ubuntu0.22.04.1
Database Collation	utf8mb4_0900_ai_ci
Database Connection Collation	utf8mb4_0900_ai_ci
PHP Version	7.4.32
Web Server	Apache/2.4.52 (Ubuntu)
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.10.11 Stable [ Daraja ] 14-August-2022 14:18 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Linux; Android 10; SM-G960U1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Mobile Safari/537.36
```

### Additional comments

[testCli.txt](https://issues.joomla.org/uploads/1/d2d7041ce3601e19a5ced971644db605.txt)

**Comment by dmb0058** [comment]
Incomplete code, apologies.

This is the correct code to reproduce:

<?php

const _JEXEC = 1;

if (file_exists(dirname(__DIR__) . '../../defines.php'))
    require_once dirname(__DIR__) . '../../defines.php';

if (!defined('_JDEFINES'))
{
    define('JPATH_BASE', dirname(__DIR__) . "/../..");
    require_once JPATH_BASE . '/includes/defines.php';
}

require_once JPATH_LIBRARIES . '/import.legacy.php';
require_once JPATH_LIBRARIES . '/cms.php';

class LaunchCLI extends JApplicationCli
{
    public function doExecute()
    {   
        $db = JFactory::getDbo();
        $query = $db->getQuery(true);
        $query->select('COUNT(*) AS count')->from($db->quoteName('#__content'));
        $db->setQuery($query);
        $result = $db->loadObject();
        $this->out("pages: " . $result->count);
    }
}

class LaunchDaemon extends JApplicationDaemon
{
    public $name='test';

    public function doExecute()
    {   
        $db = JFactory::getDbo();
        $query = $db->getQuery(true);
        $query->select('COUNT(*) AS count')->from($db->quoteName('#__content'));
        $db->setQuery($query);
        $result = $db->loadObject();
        $this->out("pages: " . $result->count);
    }
}

$options = getopt("d");

try {
    if (array_key_exists('d', $options))
        JApplicationDaemon::getInstance('LaunchDaemon')->execute();
    else
        JApplicationCli::getInstance('LaunchCLI')->execute();
}
catch (Exception $e){
    echo $e->getMessage() . "\n";
}

?><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39533">issues.joomla.org/tracker/joomla-cms/39533</a>.</sub>

**Comment by dmb0058** [comment]
Test script[testCli.txt](https://issues.joomla.org/uploads/1/b517d8455bd0758d9b317621b6184a0f.txt)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39533">issues.joomla.org/tracker/joomla-cms/39533</a>.</sub>

**Comment by brianteeman** [comment]
Joomla 3 is now only getting security fixes

**Comment by dmb0058** [comment]
NP, I assume it doesn't work on J4 either, I'll test and submit a new bug report ...

**Comment by brianteeman** [comment]
were you able to replicate this in joomla 4?

**Comment by dmb0058** [comment]
No, I haven't had time, had to fall back on building a cli app/cron job to
get a reliable solution in place. The daemon is on the backlog, maybe after
we port the whole package to J4.

**Comment by Fedik** [comment]
I just looked the code, the issue valid for both J3 and j4.
DemonApplication sets incorrect class as signal handler.
Joomla 3 https://github.com/joomla/joomla-cms/blob/2ca2d4ebf0184d9183621af9721eaf80427f105a/libraries/src/Application/DaemonApplication.php#L703-L709

Joomla 4 https://github.com/joomla/joomla-cms/blob/f520c98c64efb538e70e918acffb60d07e4d6b1e/libraries/src/Application/DaemonApplication.php#L653-L658

It should be full class name, with namespace.

**Comment by Hackwar** [comment]
I created #44518 to fix this. Since we have a PR, I'm closing this one. Thank you for reporting this!
