### ISSUE TITLE
[4.3] module - article categories ordering

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39532]
### Is your feature request related to a problem? Please describe.
The module displays a list of categories but there is no option to set the ordering. 

![image](https://user-images.githubusercontent.com/1296369/210169799-21a72751-e596-445a-a4e0-6edb36b0c924.png)

### Describe the solution you'd like
Just like everywhere else I would like to be able to set ordering 

![image](https://user-images.githubusercontent.com/1296369/210169813-78e09ea7-ae40-4fe3-ada7-925156f85000.png)

**Comment by carlitorweb** [comment]
In fact this order is not working at all. The module do not have the order option, and the **Menu type: List All Categories in an Article Category Tree**  do not work

**Comment by brianteeman** [comment]
I said there was no ordering at all in this module so not sute how you can say it is not working when it doesnt exist

**Comment by carlitorweb** [comment]
Fixed. Just want point out that even if the option exist like in the **Menu type: List All Categories in an Article Category Tree**, is not working.

**Comment by wojtekxtx** [comment]
@brianteeman good catch 👍 
@carlitorweb so its more like `feature request` than `bug`.

**Comment by brianteeman** [comment]
@wojtekxtx it is a feature request
![image](https://user-images.githubusercontent.com/1296369/211046422-66a3ec5c-2d53-42bc-b40c-fe2c7ddc862a.png)

**Comment by wojtekxtx** [comment]
@brianteeman Good. So now let's wait for PR from @carlitorweb. 😃

**Comment by carlitorweb** [comment]
@wojtekxtx if you test it, I will do the PR for sure 😃

**Comment by Naveen0910** [comment]
is this issue still open? if yes assign it to me i may able to contribute !!

**Comment by arpan-mondal** [comment]
You can modify the code to include an additional parameter for ordering, and then adjust the query used to retrieve the articles accordingly. This can be a example for adding a new parameter for ordering in the XML file that defines the module.
<field
    name="ordering"
    type="list"
    label="Select Ordering"
    default="ordering"
>
    <option value="ordering">Default Ordering</option>
    <option value="title">Title</option>
    <option value="created">Date Created</option>
    <option value="modified">Date Modified</option>
    <option value="hits">Hits</option>
</field>

**Comment by nyni123** [comment]
Hi @brianteeman 

I have setup the project but the Extension "com_content" (Article) is missing on my setup so I am installing it again from "https://extensions.joomla.org/" 

<img width="1376" alt="image" src="https://user-images.githubusercontent.com/41539225/229739066-c249280c-2932-4786-9991-b84a0215ef15.png">

Please check that the marked extension in the attached screenshot is correct.

**Comment by nyni123** [comment]
Hi 
I found the Article Component but its protected and I am unable to Enable this

<img width="1372" alt="image" src="https://user-images.githubusercontent.com/41539225/229752380-01494892-61bf-4479-8a78-52d675b591d8.png">

**Comment by nawarajshah** [comment]
i have solved this so can you please check this out?

**Comment by alikon** [comment]
please test #40631

**Comment by brianteeman** [comment]
#40631 has absolutely nothing to do with this!! Please re-open

**Comment by alikon** [comment]
oops, misread

**Comment by nawarajshah** [comment]
> #40631 has absolutely nothing to do with this!! Please re-open

is my solution wrong?

**Comment by nawarajshah** [comment]
I got it

**Comment by nawarajshah** [comment]
Can you make it clear exactly where in that page you want that feature?

**Comment by richard67** [comment]
Closing as having a pull request. Please test #41336 . Thanks in advance.

**Comment by charvimehradu** [comment]
This may be opened again as the problem has not yet been resolved and I would need help and time.
