### ISSUE TITLE
[4x] Feature Request: allow scheduling of menu item publish up and down dates

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#39541]
### Is your feature request related to a problem? Please describe.
When preparing a website that has, for example, a programme of events displayed via a category blog menu item type, in order to keep the programme hidden until the official programme launch date means keeping the menu item unpublished, then manually publishing the menu item at the appropriate date and time. Similarly, for a programme of events that has been and gone it needs to be unpublished manually.

### Describe the solution you'd like
Enable publishing up/down of menu items as per individual articles.

**Comment by richard67** [comment]
There are published up and down times for menu items already in Joomla 4. You have to set the status to published, then you can enter the start and stop times, and the menu item should only be shown between these times. Does that not do what you require?

**Comment by Scrabble96** [comment]
Oops. Sorry. Somehow I missed it. Can you delete this request?

**Comment by richard67** [comment]
No problem. Closing is sufficient.
