### ISSUE TITLE
Problem with the column in the site Joomla

### ISSUE THREAD

**Issue by SalvoLaDelfa** [joomla/joomla-cms#39551]
### Steps to reproduce the issue
Hi. If I put two column in the home of my site (www.ilfilodies.it) the homepage shrinkes (the articles go to one column. 
Could you help me? Thank you

### Expected result

sss

### Actual result
sss

### System information (as much as possible)

sss

### Additional comments

sss

**Comment by carlitorweb** [comment]
Hello. Please use the forum for support [](https://forum.joomla.org/). And when you do post on the forum, please give them a bit more information.
