### ISSUE TITLE
No feedback returned when Registered User attempts to authenticate while site 'offline'

### ISSUE THREAD

**Issue by tyfairclough** [joomla/joomla-cms#39559]
### Steps to reproduce the issue

Configure joomla instance so that is is set to 'offline'

### Expected result

A registered user would be shown an error message describing that their access level does not permit access while the site is offline.

### Actual result

Login view refreshes
GET https://smartonboard.lunchlabs.co.uk/ 503

### System information (as much as possible)

System Information
Setting	Value
PHP Built On	Linux  4.18.0-348.lve.el8.x86_64 #1 SMP Sun Nov 21 10:56:33 EST 2021 x86_64
Database Type	mysql
Database Version	10.5.15-MariaDB-cll-lve
Database Collation	utf8mb4_unicode_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	Yes
PHP Version	8.0.24
Web Server	LiteSpeed
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 4.2.6 Stable [ Uaminifu ] 13-December-2022 15:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

request headers

:method: GET
:path: /
:scheme: https
accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
accept-encoding: gzip, deflate, br
accept-language: en-US,en;q=0.9
cache-control: max-age=0
cookie: 105cf6faae506f52d3342a381db5d409=u122i428o5t5d1s2cuvjg91nte; joomla_user_state=logged_in
referer: https://smartonboard.lunchlabs.co.uk/
sec-ch-ua: "Not?A_Brand";v="8", "Chromium";v="108", "Google Chrome";v="108"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
sec-fetch-dest: document
sec-fetch-mode: navigate
sec-fetch-site: same-origin
sec-fetch-user: ?1
upgrade-insecure-requests: 1
user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36

### Additional comments
Using Yootheme Pro
Go easy on me, first bug reported (not an engineer). Reported here first rather than yootheme because I got a 503 not a 403 (which suggests it's not the theme forgetting to include ACL use case, but an issue in the response).

**Comment by Hackwar** [comment]
Thank you for your report. I can confirm that behavior and that we should add an additional message when permissions are not high enough.

**Comment by Quy** [comment]
Please test  #39561.
