### ISSUE TITLE
Joomla 4 Router URL is case sensitive.

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#39560]
### Steps to reproduce the issue

This URL works
https://www.brainforge.co.uk/our-services

This URL fails
https://www.brainforge.co.uk/Our-services

### Expected result

Both should produce the same result.

### Actual result

Upper case character in URL fails.

### Additional comments

This was encountered with a 3rd party component with code which looked something like this...

$url = 'myname';
$url = JURI::base() . JText::_($url);
// JText Returns Myname (or a language equivalent)

Link / redirection to that url fails.

I've tried entering uppercase on another Joomla site which has no extension(s) of mine, so I'm sure its not something I have done!

**Comment by brianteeman** [comment]
see #38145 and https://github.com/joomla/joomla-cms/issues/38257

**Comment by Fedik** [comment]
Closing as duplicate.
