### ISSUE TITLE
[4.2.6] Feature start and end date don't affect blog view

### ISSUE THREAD

**Issue by Harmageddon** [joomla/joomla-cms#39562]
### Steps to reproduce the issue

Create three menu items:

1. "Featured"
  - Type: Featured
2. "Not Featured Blog"
  - Type: Category Blog
  - Category: Category A
  - Blog Layout - Featured Articles: Hide
3. "Featured Blog"
  - Type: Category Blog
  - Category: Category A
  - Blog Layout - Featured Articles: Only

Create an article
- Featured: Yes
- Category: Category A
- Start Featured: In 2 minutes
- End Featured: In 4 minutes

Navigate to the three menu items you created before, and notice their content...
- Before the "Start Featured" time
- Between "Start Featured" and "End Featured"
- After the "End Featured" time

### Expected result

During the feature time, the article should be displayed on "Featured" and "Featured Blog", but not in "Not Featured Blog". Before and after the feature time, the article should be displayed on "Not Featured Blog", but not on "Featured" and "Featured Blog".

### Actual result

The article is never shown at "Not Featured Blog".

The "Featured" and interestingly also the "Featured Blog" page behave as expected.

### System information (as much as possible)

Joomla! 4.2.6 Release

### Additional comments

Originally reported by user Octo at the German forum: https://forum.joomla.de/thread/17507-beitrag-automatisch-verschieben-mit-hauptbeitrag-bis/

**Comment by wojtekxtx** [comment]
> System information (as much as possible)
Joomla! 4.2.6 Release

OK, but what OS are you using? Windows, Linux, macOS?

**Comment by brianteeman** [comment]
The operating system is irrelevant

**Comment by brianteeman** [comment]
@Harmageddon Not had the opportunity to test yet but could you confirm if there is any cache enabled on the site and if so which option

**Comment by wojtekxtx** [comment]
@brianteeman just the opposite in fact. If you were right than why there is `System information` field in the issue template?

**Comment by Harmageddon** [comment]
@brianteeman Caching is disabled in global configuration.

@wojtekxtx Did you try to reproduce it? I highly doubt it is an OS issue. But to make you happy: Client is Firefox 108.0.2 on Windows 10 64 bit. Server is a linux system, PHP 8.0.26 on Apache with 10.4.27-MariaDB database.

**Comment by wojtekxtx** [comment]
@Harmageddon yes I tried.

> I highly doubt it is an OS issue.

Same here, but, as the saying goes: "never say never", for proper troubleshooting you have to have full list of possible solutions and just cross out not valid as you go.

**Comment by brianteeman** [comment]
Issue confirmed

The problem is in the query that "hides" the featured articles (Menu 2)

The query is only checking "where featured = 0"
The query should also be checking "WHERE featured = 1 and (featured_up < NOW and featured_down < NOW)

or som,ething like that - sql not my area but you should understand what I mean

**Comment by wojtekxtx** [comment]
@brianteeman why this is done with SQL in the first place?

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/39572 should fix this issue. Please testing, especially @Harmageddon . Thanks !
