### ISSUE TITLE
Wrong meta-description priority

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#39587]
Joomla 4.2.6

See meta-description of an article:
<img width="1424" alt="Снимок экрана 2023-01-10 в 14 04 34" src="https://user-images.githubusercontent.com/3432048/211535743-2c4d55bc-8c83-4d00-93d4-a4703dc32dc6.png">

And see a menu item to this article:
<img width="851" alt="Снимок экрана 2023-01-10 в 14 04 51" src="https://user-images.githubusercontent.com/3432048/211535816-a8674ba8-ba52-40b3-a4fd-41d1cd1f6eb6.png">

And here is the source code:
<img width="910" alt="Снимок экрана 2023-01-10 в 14 05 42" src="https://user-images.githubusercontent.com/3432048/211536148-6c050900-763f-4b06-b3ae-357b925a53f8.png">

As it is supposed, the menu item settings should has upper priority upon article settings as it is already released in Joomla 3.
In J4 it is not.

**Comment by Septdir** [comment]
4.2.5 same problem

**Comment by joomdonation** [comment]
@Sulpher @Septdir Please test PR https://github.com/joomla/joomla-cms/pull/39588 . It should address this issue. Thanks !

**Comment by Sulpher** [comment]
@joomdonation thanks for the quick fix!

I have to add a comment to avoid misunderstanding. the issue the has been described above is actual for Joomla 3 too (I thought it is ok with J3).


<img width="1325" alt="Снимок экрана 2023-01-10 в 14 37 35" src="https://user-images.githubusercontent.com/3432048/211542595-3a0537da-14c7-437c-a025-65479f013373.png">
<img width="609" alt="Снимок экрана 2023-01-10 в 14 38 07" src="https://user-images.githubusercontent.com/3432048/211542601-529d2a33-8855-49a0-8d20-3e251dcb2459.png">
<img width="903" alt="Снимок экрана 2023-01-10 в 14 38 24" src="https://user-images.githubusercontent.com/3432048/211542602-2e7edddd-a84c-4e52-aec4-9e76fe98d259.png">

**Comment by joomdonation** [comment]
@Sulpher We do not fix that kind of issue for Joomla 3 now, only for Joomla 4. And I believe the PR solves the issue.

**Comment by MaghSamana** [comment]
Please take a look here, there is another meta priority problem - maybe they are related?

https://github.com/joomla/joomla-cms/issues/39664
