### ISSUE TITLE
Newsflash module, not independant : advanced Layout / (vert. / horiz.), Gil

### ISSUE THREAD

**Issue by gilou103** [joomla/joomla-cms#39584]
### Steps to reproduce the issue
Create a Newsflash "A" module in Top-a position, 4 articles, Advanced / Layout = Horizontal 
Display is of 4 articles is horizontal OK

Add another Newsflash "B" module in Bottom-a (or b) position, 2 articles, Advanced / Layout =Vertical 

Display is of Newsflash "A" 4 articles is changed to vertical + mix of Newsflash "B" 
Disable Newsflash "B" = Display back Newsflash "A" = OK (horizontal)

### Expected result
I expect that both Newsflash "A" and Newsflash "B" config are independant (vertical / horizontal) layout

I've another Newsflash "Logo" in "Below-Top" position, no impact = Display remains OK in its position, so no impact from Newsflash "A & B" 
This allows me to change logos by articles "logo's"

### Actual result
Newsflash "A" advanced layout is corrupted by Newsflash "B" Layout 

### System information (as much as possible)
I use a child Cassiopea Template
Joomla 4.26
Cassiopeia, child

### Additional comments
This is my first reported "bug".. Sorry if not so clear
Have a good time
Thanks, Gil
---------------------------------------------------------

![Newsflash_bug_4_positions_A+B+C](https://user-images.githubusercontent.com/49638535/211337892-fc8ae4f0-f5c0-493a-8a20-4b32a7a315e5.JPG)
![Newsflash_bug_3_B_Config_vertical](https://user-images.githubusercontent.com/49638535/211337894-dbb90509-d35b-4328-a4a5-adfa083e119d.JPG)
![Newsflash_bug_1_A_OK_enable](https://user-images.githubusercontent.com/49638535/211337896-9b57e7cf-9b9e-44b7-9f29-c44628cc0d1f.JPG)
![Newsflash_bug_2_A+B_enable_BUG](https://user-images.githubusercontent.com/49638535/211337899-0218a908-2800-428b-ad07-ac101df43fa1.JPG)
![Newsflash_bug_3_A_Config_horizontal](https://user-images.githubusercontent.com/49638535/211337884-8abaca02-3e98-4605-8dbe-9e58eb896e29.JPG)

**Comment by brianteeman** [comment]
I cannot replicate this

![image](https://user-images.githubusercontent.com/1296369/211413846-57e1fd50-8edb-4a75-9424-4cf4b48d73e5.png)

**Comment by gilou103** [comment]
Hi Brian,

Thanks for you answer.

You may visit our site for  demo of problem.

If you like, we can have a Teamviewer remote session.

 

Amicalement,

Gilles

 

De : Brian Teeman ***@***.***> 
Envoyé : lundi 9 janvier 2023 22:41
À : joomla/joomla-cms ***@***.***>
Cc : gilou103 ***@***.***>; Author ***@***.***>
Objet : Re: [joomla/joomla-cms] Newsflash module, not independant : advanced Layout / (vert. / horiz.), Gil (Issue #39584)

 

I cannot replicate this

 <https://user-images.githubusercontent.com/1296369/211413846-57e1fd50-8edb-4a75-9424-4cf4b48d73e5.png>

**Comment by brianteeman** [comment]
Sorry this is not the place for support - you should use forum.joomla.org

**Comment by gilou103** [comment]
Please try to set Top A position for 4 articles categorie and Bottom-A for 2 articles categories

**Comment by gilou103** [comment]
This is not support request as we have found a workaround, but it look like a bug behavior

**Comment by brianteeman** [comment]
My apologies - there is indeed something weird going on when using those two specific positions.

**Comment by brianteeman** [comment]
@drmenzelit Any ideas? Beyond me. I suspect something to do with the css grid perhaps

**Comment by gilou103** [comment]
No problem, support...
Plan was to use "Newsflash" position and add some articles to get articles flexibility (as version, editing, ...). 
We understand, just want to report this "behavior" / Bug.

If I enable "Newsflash" "Below Top" position (logos), site is OK. No impact on Top A.
Logo is generated by an article from logo Categorie. I may add two, change it ...

**Comment by drmenzelit** [comment]
I found the reason. Each layout should load an own css file: horizontal = media\mod_articles_news\template.css, vertical = media\mod_articles_news\template-vert.css and that works. But the style has the same name: $wa->registerAndUseStyle('mod_modules'.... so the last one loaded wins... We need a PR changing the name of the style for the WebAssets Manager

**Comment by brianteeman** [comment]
good find

**Comment by drmenzelit** [comment]
Closing as we have a PR. Please test #39585
