### ISSUE TITLE
New punycode.js release:: version 2.2.0

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#39590]
See
https://github.com/mathiasbynens/punycode.js

**Comment by laoneo** [comment]
Thanks for the information. As we update all dependencies when we arrive in 4.3 beta phase, this one can be closed. Or do you think this should be updated earlier?

**Comment by brianteeman** [comment]
Can be closed as updated with #39875

**Comment by joomdonation** [comment]
Thanks @brianteeman . Closing this issue. Please check PR https://github.com/joomla/joomla-cms/pull/39875 .
