### ISSUE TITLE
smart search - filters Content type & Content maps improvements

### ISSUE THREAD

**Issue by sofianhit** [joomla/joomla-cms#39627]
hi

if i have 5 Content type (videos, articles , faqs , conacts and other) ,
i will see all of their content maps in same place .
this mean if i create a new filter for videos and chose videos in Content type ,
then i will see in content maps the videos categories , the articles categories , the contacts and the faqs and other maps .

think that i create a ctegory for videos with name News and ctegory for articles also name News , i will see 2 News maps .

my idea is :
when chose content type (for example videos) , display just the videos categorias in content maps .

or , split the content maps to be like this :

**content maps** 
search by videos categories
list for videos categories

search by articles categories
list for articles categories

search by faqs categories
list for faqs categories

search by conacts  categories
list for conacts categories

here i can know evry ctegory what is its parent type .

what you say about this ?

thanks

**Comment by Hackwar** [comment]
I'm sorry, but your request would go pretty much directly against the architecture of smart search. The idea is, that identical categories across different components will only show up once in the taxonomies. If you want to filter that down further, you have to filter by type for example. We will not differentiate the categories by component again.
