### ISSUE TITLE
[4.2]  webclient user agents

### ISSUE THREAD

**Issue by david19161** [joomla/joomla-cms#39637]
### Steps to reproduce the issue

Somehow! set your user agent to "Chrome Privacy Preserving Prefetch Proxy"

### Expected result
no warnings

### Actual result
Undefined array key 1 in libraries/vendor/joomla/application/src/Web/WebClient.php on line 439

### System information (as much as possible)
joomla 4.2.6
php 8.0.23

### Additional comments
seeing a lot of these in the php error log.
its obvious why, there is no "/" in the user agent string

**Comment by ReLater** [comment]
Something seems to be wrong with your testing instructions. Line 439 is surrounded by

```
elseif (stripos($userAgent, 'Chrome') !== false)
{

}
```

but there is no `Chrome` in your UserAgent string.

**Comment by ReLater** [comment]
For reference: https://developers.google.com/search/docs/crawling-indexing/overview-google-crawlers

As far as I see Google never adds the string `Chrome/W.X.Y.Z` to Feedfetcher user agents or just `Chrome`.

It looks like somebody is visiting your site with a badly faked user agent. Block them!

Or do I miss something?

**Comment by david19161** [comment]
corrected instructions
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39637">issues.joomla.org/tracker/joomla-cms/39637</a>.</sub>

**Comment by david19161** [comment]
user agent is "Chrome Privacy Preserving Prefetch Proxy"
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39637">issues.joomla.org/tracker/joomla-cms/39637</a>.</sub>

**Comment by ReLater** [comment]
Maybe a solution could be:

`elseif (stripos($userAgent, 'Chrome/') !== false)`

The correct repository for this issue is https://github.com/joomla-framework/application

I'm out.

**Comment by Simran180** [comment]
can I work on this issue?

**Comment by alikon** [comment]
there is no need to ask, please submit your pull request

**Comment by ReLater** [comment]
@Simran180 

Like said in https://github.com/joomla/joomla-cms/issues/39637#issuecomment-1383241989 it's not the joomla-cms repository here but joomla-framework. See https://github.com/joomla-framework/application/issues/112 there.

**Comment by brianteeman** [comment]
Closing this here as a relevant issue has been created in the upstream library
