### ISSUE TITLE
[4.2] Duplicate buttons on second Editor instance

### ISSUE THREAD

**Issue by OctavianC** [joomla/joomla-cms#39646]
### Steps to reproduce the issue
Have 2 different editors on the page. Using this code I'm showing 'Editor - None' and 'Editor - CodeMirror' on the same page:
```php
foreach (array('none', 'codemirror') as $plugin)
{
	$editor = \Joomla\CMS\Editor\Editor::getInstance($plugin);

	echo $editor->display($plugin, $plugin, 500, 320, 70, 10, true);
}
```

### Expected result
Two editors with the same amount of buttons

### Actual result
Buttons are duplicated on the second editor
![image](https://user-images.githubusercontent.com/1422378/212686457-ad13cdd9-f65c-4e0b-a2cd-3860d8e07e91.png)

### Additional comments
Seems to be caused by these lines:
https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Editor/Editor.php#L93-L104

Every time an editor is initialized the event listener is added. Might be an oversight because you won't notice this out of the box (I haven't found any page where the Joomla! CMS would present different editors).

**Comment by Fedik** [comment]
The probalem that getButtons is not an event, it is a callback https://github.com/joomla/joomla-cms/blob/4d5e843cbcc71b40ec368179e31176f1e87d53e9/plugins/editors/codemirror/codemirror.php#L351 (`$this->_subject` is instance of Joomla\CMS\Editor class)

I cannot find PR, but found it was changed in a commit https://github.com/joomla/joomla-cms/commit/e9c1efcc5ba986508007baae2752d90733a8ef93

**Comment by dgrammatiko** [comment]
@OctavianC @Fedik please test https://github.com/joomla/joomla-cms/pull/39648
