### ISSUE TITLE
[4.2] PHP8.2 - Joomla installation could not be finished. Error on Check DB

### ISSUE THREAD

**Issue by degobbis** [joomla/joomla-cms#39655]
### Steps to reproduce the issue
- Clone Joomla 4.2-dev branch (start composer install and npm ci).
- Start the installation and fill out all datas.
- Finish the installation.

### Expected result
Joomla ist installed and You can call the frontend and the backend

### Actual result
Installation could not be finished. 

### System information (as much as possible)
There is an error message in the browser console:

![Screenshot_2023-01-14_20_54_32](https://user-images.githubusercontent.com/10517822/212854021-61558729-207a-427b-a571-ba29694c5402.jpg)

### Additional comments
Addressed at @laoneo in Mattermost https://joomlacommunity.cloud.mattermost.com/main/pl/1jtaekzscfr1jdfmpuog5sqnsa

**Comment by brianteeman** [comment]
what is your php version

**Comment by degobbis** [comment]
PHP 8.2

**Comment by alikon** [comment]
can you please give a test 
adding this 
```php
    private $token;
    private $lang;
    private $error;
    private $data;
```

here https://github.com/joomla/joomla-cms/blob/4.2-dev/installation/src/Response/JsonResponse.php#L28 
and report back

**Comment by degobbis** [comment]
@alikon I can't test this until the evening, I will report then.

**Comment by alikon** [comment]
no problem

**Comment by degobbis** [comment]
@alikon with Your changes the error in the console is gone, but the installation does not continue. 
There is also no error message shown. 
I can say, at this point https://github.com/joomla/joomla-cms/blob/4.2-dev/installation/src/Controller/InstallationController.php#L61 the validation fails.

**Comment by laoneo** [comment]
Please test #39660.
