### ISSUE TITLE
Rest API - get all menu items related to a specific menu

### ISSUE THREAD

**Issue by bellu** [joomla/joomla-cms#39667]
### Is your feature request related to a problem? Please describe.
I'm trying to build a website using Joomla only for the REST API.

### Describe the solution you'd like
After building a menu, how can i retrieve all of the menu items related to that menu?
I found this endpoint curl -X GET /api/index.php/v1/menus/{app}/items .
But in this way i'm going to retrieve all the menu items for the entire frontend.

**Comment by ReLater** [comment]
I'm not an expert. Doesn't it work by adding `?filter[menutype]=mainmenu` to the url? `mainmenu` as example for the `menutype` column from table `#__menu`

**Comment by alikon** [comment]
we should introduce such new endpoint i think

**Comment by bellu** [comment]
@alikon so basically now, i can't filter anything with the REST API, right?

**Comment by alikon** [comment]
please test #39675

**Comment by bellu** [comment]
@alikon thanks for your implementation.
I Think that the filter should be implemented even for the modules.
Starting from a menu alias, there should be a way to retrieve all the modules associated; because at the moment it's a little bit tricky retrieve all the content associated to a menu item.

Should i open another issue? I don't want to go off topic.

**Comment by alikon** [comment]
yes please open a new issue and describe the feature
