### ISSUE TITLE
Joomla 3 and PHP 8

### ISSUE THREAD

**Issue by jochenkeutel** [joomla/joomla-cms#39665]
### Steps to reproduce the issue
I switched today our Joomla 3.10.11 from PHP 7.4 to PHP 8.0.
Error message: count(): Argument #1 ($value) must be of type Countable|array, bool given

### Expected result
working page

### Actual result
Error message: count(): Argument #1 ($value) must be of type Countable|array, bool given

### System information (as much as possible)
Joomla 3.10.11, PHP 8.0

### Additional comments

Fixes - after applying them all works fine:

- plugins\system\stools\core\class.helper.php:
  - line 301: $modCnt = count($mods); ---> $modCnt = count((array)$mods);
  - line 399: $max = count((array)$activeMod); ---> $max = count((array)$activeMod);
- modules\mod_ju_msilders\mod_ju_msilders.php:
  - line 12: $path=$_SERVER['HTTP_HOST'].$_SERVER[REQUEST_URI]; ---> $path=$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];

**Comment by ReLater** [comment]
Thanks for providing your fixes.

Both fixes aren't related to Joomla core. Both extensions aren't Joomla core. This repository here is only for Joomla core issues. Please contact the developers of the extensions and close your issue here.
Thank you!
