### ISSUE TITLE
Red notifications and empty media folder

### ISSUE THREAD

**Issue by jobrusche** [joomla/joomla-cms#39674]
### Steps to reproduce the issue
Display admin control panel after login
Display content Media

### Expected result

![GREEN-notifications](https://user-images.githubusercontent.com/117929258/213663557-4785ea0f-ca99-4961-8997-0bd8df7f23ac.PNG)

![Media-folder](https://user-images.githubusercontent.com/117929258/213663746-f6fae66d-734b-4429-b352-ffaeb293d3dc.PNG)

### Actual result

![RED-notifications](https://user-images.githubusercontent.com/117929258/213663436-7ac26918-8208-414f-bb92-25bb6af1d88e.PNG)

![Empty-media](https://user-images.githubusercontent.com/117929258/213663525-c625b50c-55dd-481f-bdf2-1d978cd10e2c.PNG)

### System information (as much as possible)

[systeminfo-2023-01-20.txt](https://github.com/joomla/joomla-cms/files/10465092/systeminfo-2023-01-20.txt)

### Additional comments
Situation returns to normal after using Usersmenu ->Accessibility->Close ->Login in    ###backend.
This site is a clone of my testsite nicole.brusche.be where this problem is NOT exhibited

References:  
PR #38172
[https://issues.joomla.org/tracker/joomla-cms/38001](url)

**Comment by carlitorweb** [comment]
Please, click F12 in your browser, and in the `console` tab you will see there, check if you see any error attach to there.

**Comment by dgrammatiko** [comment]
@carlitorweb fwiw `http://mysite.com` is not the same as `http://www.mysite.com`. The www is a subdomain of `mysite.com` so restrictions apply...

**Comment by carlitorweb** [comment]
@dgrammatiko did not see that. But why then open in others browser? Is what confuse me....

**Comment by jobrusche** [comment]
With F12 in chrome ,console displays 
Access to XMLHttpRequest at 
'https://www.nicolesaenen.be/administrator/index.php?option=com_joomlaupdate&task=update.ajax&bd05f19467342b5bf3401f0a70952a42=1' 
from origin 'https://nicolesaenen.be' has been blocked by CORS policy: 
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
www.nicolesaenen.be/administrator/index.php?option=com_joomlaupdate&task=update.ajax&bd05f19467342b5bf3401f0a70952a42=1:1          
Failed to load resource: net::ERR_FAILED

**Comment by dgrammatiko** [comment]
Check https://observatory.mozilla.org/analyze/nicolesaenen.be

![Screenshot 2023-01-21 at 16 00 23](https://user-images.githubusercontent.com/3889375/213872774-f65c6f27-9ad2-49fd-8d3a-8cdcd54cf33c.png)

Fix this (it's the server setup) and you'll fix your cors problems

**Comment by richard67** [comment]
@jobrusche Please check @dgrammatiko 's [comment above](https://github.com/joomla/joomla-cms/issues/39674#issuecomment-1399267090) and report back if it helped you to fix your CORS problem. Thanks in advance.

**Comment by richard67** [comment]
Closing as not an issue with the CMS core. Thanks @jobrusche for reporting back.
