### ISSUE TITLE
Save button in modules does not work, because the number of menu items more than max_input_vars

### ISSUE THREAD

**Issue by anilalci** [joomla/joomla-cms#39672]
### What needs to be fixed
Save button in modules does not work, because the number of menu items more than max_input_vars
I have 3K menu items but default max_input_vars is 1K

### How would you fix it
jform[assigned] can compress before submit.

### Workaround
increase the value of max_input_vars in .user.ini or php.ini files
for example;
max_input_vars = 9000

**Comment by brianteeman** [comment]
I would be suprised that your suggestion will make a difference but if it will then great - please submit a pull request for the code and it can be tested.

What you describe as a workaround is what I would describe as the expected action to take. But if your code works then even better

**Comment by richard67** [comment]
Closing as having a pull request. See #39673 .
