### ISSUE TITLE
[4.2][3.10] Joomla 4 does not show parsing errors in language strings

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#39687]
Hi, 

I don't know if I'm missing a setting somewhere, but Joomla 4 doesn't show me parsing errors in language strings

### Steps to reproduce the issue

1) Enable language debug in Joomla Global Configuration

2) Edit following file

_administrator/language/en-GB/com_content.ini_

( _administrator/language/en-GB/en-GB.com_content.ini_ in Joomla 3.9, 3.10)

and intentionally create an error there - remove the quotation mark, e.g. on line 6

![image](https://i.imgur.com/jor7oDI.png)

### Expected result

Joomla language debug will display parsing error message

### Actual result

Joomla language debug does not display parsing error message

This is problematic in Joomla 4.2.6, Joomla 3.10 **but not in Joomla 3.9.27**

Joomla 3.9.27

![image](https://i.imgur.com/TFKd07L.png)

Joomla 3.10

![image](https://i.imgur.com/GTvUTpO.png)

Joomla 4.2.6

![image](https://i.imgur.com/fddBGlv.png)

![image](https://i.imgur.com/obZMOW0.png)

### System information (as much as possible)

Joomla 4.2.6 (Joomla 3.10, Joomla 3.9.27)

Jan

**Comment by chmst** [comment]
Confirmed.

**Comment by brianteeman** [comment]
unable to replicate with 4.2.9

![image](https://user-images.githubusercontent.com/1296369/230671656-7c47e651-da3f-4c53-ab6b-74eb2086d037.png)

unable to replicate with 4.3rc1

![image](https://user-images.githubusercontent.com/1296369/230671904-1ba8fc81-a67e-47e7-b011-0aa59313a319.png)

**Comment by brianteeman** [comment]
@chmst can you still replicate this? If not then this should be closed

**Comment by PhocaCz** [comment]
I am testing it now in 4.3.1 and there it seems to be OK.
