### ISSUE TITLE
LDAP bug

### ISSUE THREAD

**Issue by edrobal** [joomla/joomla-cms#39696]
My site uses LDAP authentication. With php 7, no problem. I upgraded to php 8.1 as requested and since then, authentication no longer works. As usual, changing php versions is a hassle.

**Comment by tatankat** [comment]
Hi @edrobal.
I guess you are still using Joomla 3. See the fix + important remarks at #38750.

**Comment by Hackwar** [comment]
@edrobal Can you confirm @tatankat that you are using Joomla 3?

**Comment by richard67** [comment]
@edrobal Have you checked the [link](https://github.com/joomla/joomla-cms/pull/38750) in the [comment above](https://github.com/joomla/joomla-cms/issues/39696#issuecomment-1400810122)? Could you check and report back if you are using Joomla 3 and if that link helps?
