### ISSUE TITLE
Problem with com_tag rewrite

### ISSUE THREAD

**Issue by sonosergio** [joomla/joomla-cms#39708]
### Steps to reproduce the issue
Create a menu item to show list article from com_tags

### Expected result
only alias is shown in the menu

### Actual result
rewrite does not transform all fields
&view=tag&id[0]=4&types[0]=1&tag_list_language_filter=it-IT they are shown in the url generated in the menu

![Screenshot_20230125_094212](https://user-images.githubusercontent.com/5682550/214521186-83107672-cd10-4243-8fc3-b02878cae64a.png)

**Comment by Shinchan3102** [comment]
i wanted to  contribute in it but i didn't get much idea about the issue

**Comment by Hackwar** [comment]
Are you getting this issue in 4.3 or in 4.2? This should be the same behavior since Joomla 3, so unless you are experiencing this differently in 4.3 compared to 4.2, this is not an issue of the rewrite. However I do agree, that we should fix this in the long term.

**Comment by sonosergio** [comment]
Sorry for the few details
Joomla Version > ‎4.2.6
the menu item also works without the additional parameters which, however, are entered automatically

See this [Video](https://datafiles.sfweb.it/errore_tag_joomla.mp4)
Thanks so much

**Comment by DirkLerner** [comment]
I have the same experience with J4.3.0. The URL is not rewritten when using tags to filter the content within a menu item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39708">issues.joomla.org/tracker/joomla-cms/39708</a>.</sub>

**Comment by DirkLerner** [comment]
And a screenshot to show the issue on my page.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39708">issues.joomla.org/tracker/joomla-cms/39708</a>.</sub>

**Comment by Hackwar** [comment]
As I wrote, this is nothing new and has been working like this since tags have been introduced in Joomla 3.1 or 3.2. Yes, it is ugly and sucks big time, but it is not a new behavior. To keep backwards compatibility, I can also already guarantee you, that we wont be changing this in 4.x.

**Comment by Quy** [comment]
Closing as duplicate #42208
