### ISSUE TITLE
Serious ACL Problems

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39706]
or I just don't get it

### Steps to reproduce the issue
Create a user with Manager permissions
Login with that user and confirm that for com_content there is no Options button
Log back in as a super user and go to the com_content options and change the permissions to give the Manager permission for the options.

![image](https://user-images.githubusercontent.com/1296369/214390524-4d28d6f2-4a82-4d3a-a770-7b595454fe6a.png)

Log back in as a manager confirm that for com_content there now is an Options button

### Expected result
Clicking on the Options button will display the options for the component

### Actual result
403 Access denied
![image](https://user-images.githubusercontent.com/1296369/214390922-1686511f-1c40-4f01-9ffd-a5f14ff7edfd.png)

### Additional comments
The button is displayed because the code checks that you gave permission to the component for that user. 

https://github.com/joomla/joomla-cms/blob/cc4bdae6b7224d16c7aec31898fe9079e1407fd2/administrator/components/com_content/src/View/Articles/HtmlView.php#L242-L244

However you dont get access because you do not have permission to access the admin interface of com_config which can only be set in global configuration and would give access to all the components

**Either I am missing something or this is a serious bug in the ACL system.**

**Comment by joomdonation** [comment]
You are not missing anything. There is a bug in com_config ACL check, also reported before here https://github.com/joomla/joomla-cms/issues/36273 . I'm going to make a PR to fix this issue in the next few days if no one is faster.

**Comment by wojtekxtx** [comment]
@brianteeman Also noticed it
@joomdonation go for it :)

**Comment by coolcat-creations** [comment]
I do not know if this is connected but I was also confused that I gave an user Access to create Users but the buttons for this were not shown because the buttons are assigned to user group special. I thought that the buttons should be also shown depending on the general access and not by module acl. ?

**Comment by Quy** [comment]
Please test PR ##39710

**Comment by wojtekxtx** [comment]
> I thought that the buttons should be also shown depending on the general access and not by module acl. ?

@coolcat-creations your assumption is correct 👍

**Comment by richard67** [comment]
Which one shall we close as duplicate report? The older #36273 ? Or this one here?

**Comment by wojtekxtx** [comment]
@richard67 If it was up to me, Id close #36273 (especially after reading https://github.com/joomla/joomla-cms/issues/36273#issuecomment-1313228254)

**Comment by joomdonation** [comment]
Closing this issue because there is PR https://github.com/joomla/joomla-cms/pull/39710 to address it. The PR is not complete yet, but we will try to work together to get the issue fixed.
