### ISSUE TITLE
Deprecated: md5(): Passing null to parameter #1 ($string) of type string is deprecated - Joomla 4.2.6 and 3.10.11 with PHP8.1

### ISSUE THREAD

**Issue by DebasisDa** [joomla/joomla-cms#39701]
### Steps to reproduce the issue
Install joomla application (4.2.6/ 3.10.11) with php 8.1

### Expected result
No error message

### Actual result
Error : Deprecated: md5(): Passing null to parameter #1 ($string) of type string is deprecated in /home/bVOWdNvW/iibcdegf-1674533169466.stackwaysapps.com/public_html/libraries/src/Cache/CacheStorage.php on line 100

**Comment by harsitagarwalla187** [comment]
I am to here. Could you please elaborate what type of changes should i make. I have setup it locally.

![Screenshot 2023-01-25 211621](https://user-images.githubusercontent.com/84774840/214608964-1998bbea-1cb3-44db-b64f-b248a23d8752.png)

**Comment by alikon** [comment]
reading the issue, the  problem should arise  on this line  and not where you are looking
https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Cache/CacheStorage.php#L100

**Comment by harsitagarwalla187** [comment]
@alikon Is it the right way ?
md5($app->get('secret') ?? ' ' )

**Comment by alikon** [comment]
did you have been able to replicate the issue ?

btw
`$app->get('secret',' ')`    sounds better imho

**Comment by harsitagarwalla187** [comment]
> did you have been able to replicate the issue ?
No but by doing some research i found that the newer version of PHP doesn't allow null as parameters implicitly.
> btw `$app->get('secret',' ')` sounds better imho
Should i make the PR.

**Comment by alikon** [comment]
yes please
better you should do 2 pr
1 x 4
1 x 3
😄

**Comment by alikon** [comment]
as per issue 

> (4.2.6/ 3.10.11) with php 8.1

you need a pr for  j4 branch as you already did #39720
and one pr for  for j3 branch

**Comment by laoneo** [comment]
We don't need a pr for the 3 branch as we didn't fix the 8.x deprecation's there.

**Comment by HLeithner** [comment]
Closed since we have a pr https://github.com/joomla/joomla-cms/pull/39720 Joomla 3 will not be patched for php 8.1
