### ISSUE TITLE
[4.2] Smart Search Filter does not work with nested multilingual categories

### ISSUE THREAD

**Issue by crystalenka** [joomla/joomla-cms#39718]
### Steps to reproduce the issue
This has a lot of steps folks, sorry about that. I promise they're all necessary to reproduce this issue.

1. On a Joomla site with multiple content languages set up, create a category named "Parent" with language set to "All".
2. Create one category for each language. Make sure the language is set appropriately, and set the parent category to "Parent".  **CAUTION:** Do not try to bulk move categories from different languages into the parent category. Things break. No good. I will be filing another issue about it, but it's unrelated. (I think.)
3. Create one article for each language, added to the respective category and with language set appropriately. Make sure there's searchable content in there, even lorem ipsum.
4. Make sure smart search has properly indexed and mapped all the categories and articles.
5. Add a menu item for search, and do a test search in the front end to make sure it is working as expected.
6. In the back end, Create a search filter, and in "Search by Category" select "Parent" from step 1. Save and close
8. In the front end, go to the search page, refresh, and do the same test search.

### Expected result
Search provides results, but filtered by the selected category

### Actual result
"No Results Found
No search results in English (en-GB) could be found for query:"

### System information (as much as possible)
Joomla 4.2.6, 4.2.7-RC2-dev
PHP 8.1

### Additional comments
Possibly related issues: https://github.com/joomla/joomla-cms/issues/38957, https://github.com/joomla/joomla-cms/issues/38201

Also an interesting observation that I have seen both times I have reproduced this (once with real data, once on a test site). The "Parent" category, which has language set to all, shows up with a language attached in the content map:

<img width="1175" alt="Screenshot 2023-01-26 at 13 27 50" src="https://user-images.githubusercontent.com/9141288/214824800-b86dbd34-1a03-4cff-917f-db0e7a921598.png">

vs the real setting in the category list:

<img width="1175" alt="Screenshot 2023-01-26 at 13 28 19" src="https://user-images.githubusercontent.com/9141288/214824848-49ca43ba-b0cd-41f1-842d-1388eb00e544.png">

I tested whether selecting all content maps, or selecting only maps that are a "type", etc etc did anything—it does not change the behavior. The moment there is a filter applied, the search does not work. If you remove the filter, the search works fine.

I also tried clearing the index and reindexing, and that has no effect—the behavior is consistent.

Tagging @Hackwar since he is the search master and this is a funky bug!

**Comment by Hackwar** [comment]
Please have a look at PR #39751

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39751 . Thanks in advance.

**Comment by Hackwar** [comment]
The pull request does not solve the issue. Reopening.

**Comment by Hackwar** [comment]
Please have a look at both #39751 and #39961. These two combined should fix this issue. Closing again as we have a PR.
