### ISSUE TITLE
4.3-alpha-4 notice in administrator\components\com_fields\src\Helper\FieldsHelper.php

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#39719]
### Steps to reproduce the issue
open a component's settings at admin backend 

### Actual result
got notice;
**Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated 
in ..\administrator\components\com_fields\src\Helper\FieldsHelper.php on line 59**

I changed code at line 59 to:
```
if (empty($contextString)) 
  $parts = array();		
else
  $parts = explode('.', $contextString, 2);
```
this fixed  it.

### System information (as much as possible)
4.3-apha4-dev
php 8.1.6

**Comment by joomdonation** [comment]
@jschmi102 Could you please let us know what component you are having this error :

- If it is a core component, please let us know how we can see the issue ourself so that we can check it
- If it is a third party component, I would suggest to report to the developer of the extension and ask him to fix it. It's very likely he passed wrong data to the method call in his own code.

**Comment by jschmi102** [comment]
hi,
I am not able to find out which component is causing this. But I think that any coding esp. in libraries should take care, if parameters or any other input is not set as expected- E.g. if your variable "$contextString" is expected to be an array you should check this and add code to handle wrong assignments.

**Comment by joomdonation** [comment]
Yes, we can take care of that, but it will make our codebase a bit ugly. Since you proposed code, could you please make a PR to address this issue ? I think we can just return early if null is passed for that parameter, something like:

```php
if ($contextString === null) {
	return null;
}
```

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/39864 should address this issue. Please help testing. Thanks !
