### ISSUE TITLE
Category field does not show active item

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#39725]
### Steps to reproduce the issue
Create a xml field type "category" which is a flat list of items
<field name="categories_catid" type="category"  ... />
edit it the setting and see the field rendering :
- unexpected display with a blue border around the list
- the active/selected item is not shown

### Expected result
to have a clear list that shows the selected item

### Actual result
the item is selected but the user can not see it

### System information (as much as possible)
joomla 4

### Additional comments
this is a problem with the CSS, more with the css class "form-select" added on the field
the selected item has a white background on a white list, then you can not see it![screen shot 2023-01-27 at 10 17 03](https://issues.joomla.org/uploads/1/42893120ded3cccbfd721196e6e51f6e.png)

**Comment by brianteeman** [comment]
You need to use
`					layout="joomla.form.field.list-fancy-select"
`

For an example see any core usage of the field of the same type

https://github.com/joomla/joomla-cms/blob/c3b11efd14cde5002d4f3bf1228d94a52e4eb8a2/modules/mod_articles_latest/mod_articles_latest.xml#L26-L34

**Comment by ced1870** [comment]
thank you !
this shall be by default, not as an alternative layout :)

**Comment by brianteeman** [comment]
This is not a bug. It is working as designed. To achieve the desired result then the correct layout should be used.
