### ISSUE TITLE
[4.3.0-alpha4-dev] Firefox. TinyMCE issue.

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#39743]
### Steps to reproduce the issue
- Sorry I don't have time to set up a fresh test page right now. 
- Seen on 2 pages where I've updated 4.3 with nightly packages via Upload&Update several times in the past.
- In addition, I have a very "weirdly" configured Firefox browser ("extreme privacy", "blocking browser caches where possible").
- PHP8.0/PHP8.1. Current nightly Joomla 4.3.0. 109.0 Firefox Release, January 17, 2023. WIN10 Pro. EDIT: Also confirmed for WIN11 now.
- Online installations of Joomla.
- Open a new module of type "Custom".
- See TinyMCE editor.
  - Blinking footer (where the word counter is).
  - Try to enter some text. Disappears immediately.
  - Toggle the editor. Immediately jumps back.
  - Try to resize the editor. Jumps back to the old size.
- No console errors.
- Vivaldi browser: No issues.

Maybe someone here has the time to test this with current Firefox.

Thank you!

**Comment by chmst** [comment]
confirmed. See console

![grafik](https://user-images.githubusercontent.com/1035262/215325174-d729954a-108f-49e1-a3c7-2fb8fa28a0cd.png)

**Comment by ChristineWk** [comment]
Hv installed now complete new test page: Joomla 4.3.0-alpha4-dev.
But: PHP 8.0, as I can't  use 8.1 (still Joomla 3 on my test-space).

This took time of course, therefore late info :-)
Wanted to insert text, e.g. the words: "Some text". But after the letter "s", no more words possible.
@ReLater will give you per Mail the URL, then you can check maybe more/better.

![screen shot 2023-01-29 at 13 35 57](https://issues.joomla.org/uploads/1/4761aff09da34a4861c7c9f6e7129032.png)

The orange arrow: It was "jumping". 


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39743">issues.joomla.org/tracker/joomla-cms/39743</a>.</sub>

**Comment by ReLater** [comment]
@ChristineWk 

I've tested on your test site. Exactly the same like described in my opener comment. Maybe the reason for the slightly different test results is:

> In addition, I have a very "weirdly" configured Firefox browser

I have added PHP8.0 and WIN11 in my testing instructions.

**Comment by brianteeman** [comment]
Do you have the same problerm here https://codepen.io/pen

**Comment by chmst** [comment]
@brianteeman No problem on your test page. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39743">issues.joomla.org/tracker/joomla-cms/39743</a>.</sub>

**Comment by Quy** [comment]
This will be fixed per #39686 with the upmerge of 4.2.7 .
