### ISSUE TITLE
[4.2.7] - Error Message at creating Admin Menu Item

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#39758]
### Steps to reproduce the issue
Create an admin menu
Create a menu item and click on menu item type

### Expected result
A list of menu item types

### Actual result
  0 strlen(): Argument #1 ($string) must be of type string, array given 

### System information (as much as possible)

<div class="table-responsive" style="box-sizing: border-box; min-height: 0.01%; overflow-x: auto; direction: ltr; color: rgb(63, 67, 80); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgba(63, 67, 80, 0.04); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

PHP Version 8.0.27 ==================
--

</div>

> 0 strlen(): Argument #1 ($string) must be of type string, array given

| **Call stack** |  |  |
| --- | --- | --- |
| **#** | **Function** | **Location** |
| 1 | () | JROOT/administrator/components/com\_menus/src/Model/MenutypesModel.php:412 |
| 2 | strlen() |   |
| 3 | array\_filter() | JROOT/administrator/components/com\_menus/src/Model/MenutypesModel.php:412 |
| 4 | Joomla\\Component\\Menus\\Administrator\\Model\\MenutypesModel->getTypeOptionsFromManifest() | JROOT/administrator/components/com\_menus/src/Model/MenutypesModel.php:173 |
| 5 | Joomla\\Component\\Menus\\Administrator\\Model\\MenutypesModel->getTypeOptionsByComponent() | JROOT/administrator/components/com\_menus/src/Model/MenutypesModel.php:108 |

### Additional comments
If I comment out Line 412 to 420 in Menu Model it works,
/*     $o->request = array_filter($request, 'strlen');
				 $options[]  = new CMSObject($o);

				 // Do not repeat the default view link (index.php?option=com_abc).
				 if (count($o->request) == 1) {
					 $ro = null;
				 }*/
</div>

print_r for $request is: print_r for request is:

Array ( [option] => com_banners ) Array ( [option] => com_categories [extension] => com_banners ) Array ( [option] => com_banners [view] => clients ) Array ( [option] => com_banners [view] => tracks ) Array ( [option] => com_contact ) Array ( [option] => com_categories [extension] => com_contact ) Array ( [option] => com_easybookreloaded ) Array ( [option] => com_easybookreloaded [view] => gb ) Array ( [option] => com_easybookreloaded [view] => badwords ) Array ( [option] => com_newsfeeds ) Array ( [option] => com_categories [extension] => com_newsfeeds ) Array ( [option] => com_osmap [act] => [task] => [controller] => [view] => sitemaps [layout] => [sub] => ) Array ( [option] => com_plugins [filter] => Array ( [folder] => osmap ) ) Array ( [option] => com_weblinks ) Array ( [option] => com_categories [extension] => com_weblinks ) Array ( [option] => com_fields [view] => fields [context] => com_weblinks.weblink ) Array ( [option] => com_fields [view] => groups [context] => com_weblinks.weblink ) 

-- could not be reproduced by others.

Hoster is Ionos

**Comment by chmst** [comment]
I cannot replicate that. What did you before? Disable the admin menu module?

**Comment by brianteeman** [comment]
Can you replicate this WITHOUT com_easybookreloaded

**Comment by joomdonation** [comment]
Base on data from print_r command, it could come from osmap. I guess in the extension, there is link with this format

`option=com_plugins&filter[folder]=osmap`

That link could be used to diplay plugins from osmap plugin group. Joomla could not handle that kind of link for some reasons and it causes the error. Sound like a valid bug.

**Comment by brianteeman** [comment]
@joomdonation  confirmed

**Comment by carlitorweb** [comment]
Both imo

**Comment by richard67** [comment]
Joomlashack have provided an update for their allediaframework library yesterday, which is also used by and provided with OSMap. Maybe that's related?

**Comment by billtomczak** [comment]
@coolcat-creations has been in touch with us. This is a problem we've been aware of for some time but affected only one other user over the years, so we pretty much ignored it.

OSMap contains a link in the sidebar to a list of plugins filtered by OSMap plugins. This is in the component manifest:

`<menu link="option=com_plugins&amp;filter[folder]=osmap">COM_OSMAP_SUBMENU_EXTENSIONS</menu>`

This breaks code in Joomla for creating admin menus in both Joomla 3 and Joomla 4. The only thing we can do on our end is remove this convenience link. So future versions of OSMap will remove this convenience link.

**Comment by Hackwar** [comment]
This has been reported again in #43715  and there I proposed a fix. I'm unable to create a PR myself right now, but please look at that other issue as well to be kept up to date.

**Comment by alikon** [comment]
please test #43884
