### ISSUE TITLE
Column 'checked_out' cannot be null

### ISSUE THREAD

**Issue by msauer75** [joomla/joomla-cms#39760]
Hi,
I did an upgrade from Joomla 3.10 to the latest 4.2.6. Now I will get this error Column 'checked_out' cannot be null.
What can I do?
BR
martin

**Comment by chmst** [comment]
First go to system - information and check if your database is up to date. Maybe you need to repair it

**Comment by msauer75** [comment]
I checked:
![image](https://user-images.githubusercontent.com/69081100/215806070-8b42391a-0516-42fc-95e0-9f0c7c05a419.png)

**Comment by chmst** [comment]
As you seem to be German, please look here. https://forum.joomla.de/thread/15460-1048-column-checked-out-cannot-be-null/?postID=103577#post103577

**Comment by richard67** [comment]
@msauer75 The change of the checked_out columns to allow NULL values is made here: https://github.com/joomla/joomla-cms/blob/4.2-dev/administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-05-29.sql#L31-L49

In the update log "administrator/logs/joomla_update.php" the execution of these SQL statements and the file name "4.0.0-2020-05-29.sql" should have been logged during the update like in the following example:

> Ran query from file 4.0.0-2020-05-29.sql. Query text: ALTER TABLE `#__extensions` MODIFY `checked_out` INT UNSIGNED;

Could you check and report back if this is the case?

And check the fix suggested here: https://forum.joomla.de/thread/15460-1048-column-checked-out-cannot-be-null/?postID=103577#post103577 .

Thanks in advance.

**Comment by richard67** [comment]
@msauer75 Have you checked [my previous comment](https://github.com/joomla/joomla-cms/issues/39760#issuecomment-1410953525)? Could you check as advised there and report back?

**Comment by msauer75** [comment]
Hi,
I changed the column to the following
![image](https://user-images.githubusercontent.com/69081100/231203326-9403d36b-06eb-42bd-9e2b-333bc7070cae.png)

**Comment by richard67** [comment]
@msauer75 This doesn’t really answer my questions.

**Comment by brianteeman** [comment]
In the absence of any follow up can only assume that the problem has been resolved. In every case that this error has been reported it has been related to an upgrade failure.

Dont see what else can be done here and it should probably be closed.
