### ISSUE TITLE
[4.2] Bad Joomla Update error string 

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#39769]
### Steps to reproduce the issue

Using this sort of url to test: administrator/index.php?option=com_joomlaupdate&view=update
The **Get help with this error button** leads to a MediWiki error page.

### Expected result

A proper Help page

### Actual result

404 - RuntimeException

### System information (as much as possible)

Reported as a document error but is a coding error.

### Additional comments

administrator/components/com_joomla_update/tmpl/update/default.php contains JHELP_COMPONENTS_JOOMLA_UPDATE and I think that should be Help4.x:Joomla_Update.

As it is an external link it does not really need the proxy.

**Comment by max123kl** [comment]
Issue reported in https://github.com/joomla/joomla-websites/issues/1810 and https://github.com/joomla/joomla-websites/issues/1816

**Comment by beni71** [comment]
Hi . Can you agree that the correct help page for example for Joomla 4.3 version should be:
https://help.joomla.org/proxy?keyref=Help43:Components_Joomla_Update&lang=en

If so, I think it would be easy to fix. The text string (bold) in the following code line:

$helpUrl = Help::createUrl('**JHELP_COMPONENTS_JOOMLA_UPDATE**', false);

could be replaced with:

$helpUrl = Help::createUrl('**Components_Joomla_Update**', false);

But the resulting linked page does not show the correct information. It shows the same information as the help page from the main view:  administrator/index.php?option=com_joomlaupdate
which is: https://help.joomla.org/proxy?keyref=Help43:Joomla_Update&lang=en

So after that code change the wiki page
https://help.joomla.org/proxy?keyref=Help43:Components_Joomla_Update&lang=en
needs to be updated. Shouldn't it show the information like here (troubleshooting):
https://docs.joomla.org/Help4.x:Components_Joomla_Update
Or should it just be rewriten to meet the new styling?

Its not needed to discuss here about the wiki page content. My question is only whether the proposed change of the code line goes in the right direction.

**Comment by ceford** [comment]
We should change the name and prefix of Help4.x:Components_Joomla_Update so the link to it would be https://docs.joomla.org/Special:MyLanguage/J4.x:Joomla_Update_Problems

I could update the existing content. I happened to be looking at extract.php today and have participated in answering any number of questions on this topic in the Forum recently.

If you agree I can move (rename) Help4.x:Components_Joomla_Update. You may wish to suggest another name: Troubleshooting instead of Problems? Or ... perhaps just approve my suggestion.

**Comment by alikon** [comment]
please test #40670
