### ISSUE TITLE
Wrong Url i n Cli joomla /cli/joomla.php core:update

### ISSUE THREAD

**Issue by thuebschmann** [joomla/joomla-cms#39762]
### Steps to reproduce the issue
run /cli/joomla.php core:update

### Expected result
Upodate Joomla site

### Actual result
cli Load the update from an wronmg url  https://downloads.joomla.org/cms/joomla4/4-2-**6**/Joomla_4.2.**7**-Stable-Update_Package.zip

its wrong in https://update.joomla.org/core/sts/extension_sts.xml

**Comment by wilsonge** [comment]
Thankyou! This should be fixed with https://github.com/joomla/update.joomla.org/commit/13ee156832df6a0a649b812452e6464e8db0393f (due to the cache on the CDN this will take 5-10 minutes to actually roll out onto the servers)

**Comment by thuebschmann** [comment]
its wrong in  https://update.joomla.org/core/sts/extension_sts.xml<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39762">issues.joomla.org/tracker/joomla-cms/39762</a>.</sub>
