### ISSUE TITLE
Error when trying to upgrade Joomla 4.2.6 to 4.2.7

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#39763]
### Expected result
Make the update work perfectly

### Actual result

Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 28060392 bytes) in /home/my_site/public_html/libraries/vendor/laminas/laminas-diactoros/src/Stream.php on line 246
OutOfMemoryError
--
Symfony\Component\ErrorHandler\Error\OutOfMemoryError: Error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 28060392 bytes)    at /home/my_site/public_html/libraries/vendor/laminas/laminas-diactoros/src/Stream.php:246

### System information (as much as possible)

10.6.11-MariaDB-0ubuntu0.22.04.1-log
utf8mb4_general_ci
utf8mb4_general_ci
None
No
8.1.14
Apache
fpm-fcgi
Joomla! 4.2.6 Stable [ Uaminifu ] 13-December-2022 15:00 GMT
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36

Memory Limit | 64M

Build Date | Jan 13 2023 10:43:50
-- | --
Build System | Linux
Server API | FPM/FastCGI
Virtual Directory Support | disabled
Configuration File (php.ini) Path | /etc/php/8.1/fpm
Loaded Configuration File | /etc/php/8.1/fpm/php.ini
Scan this dir for additional .ini files | /etc/php/8.1/fpm/conf.d
Additional .ini files parsed | /etc/php/8.1/fpm/conf.d/10-mysqlnd.ini, /etc/php/8.1/fpm/conf.d/10-opcache.ini, /etc/php/8.1/fpm/conf.d/10-pdo.ini, /etc/php/8.1/fpm/conf.d/15-xml.ini, /etc/php/8.1/fpm/conf.d/20-calendar.ini, /etc/php/8.1/fpm/conf.d/20-ctype.ini, /etc/php/8.1/fpm/conf.d/20-curl.ini, /etc/php/8.1/fpm/conf.d/20-dom.ini, /etc/php/8.1/fpm/conf.d/20-exif.ini, /etc/php/8.1/fpm/conf.d/20-ffi.ini, /etc/php/8.1/fpm/conf.d/20-fileinfo.ini, /etc/php/8.1/fpm/conf.d/20-ftp.ini, /etc/php/8.1/fpm/conf.d/20-gd.ini, /etc/php/8.1/fpm/conf.d/20-gettext.ini, /etc/php/8.1/fpm/conf.d/20-iconv.ini, /etc/php/8.1/fpm/conf.d/20-igbinary.ini, /etc/php/8.1/fpm/conf.d/20-imagick.ini, /etc/php/8.1/fpm/conf.d/20-imap.ini, /etc/php/8.1/fpm/conf.d/20-intl.ini, /etc/php/8.1/fpm/conf.d/20-mbstring.ini, /etc/php/8.1/fpm/conf.d/20-mysqli.ini, /etc/php/8.1/fpm/conf.d/20-pdo_mysql.ini, /etc/php/8.1/fpm/conf.d/20-phar.ini, /etc/php/8.1/fpm/conf.d/20-posix.ini, /etc/php/8.1/fpm/conf.d/20-pspell.ini, /etc/php/8.1/fpm/conf.d/20-readline.ini, /etc/php/8.1/fpm/conf.d/20-redis.ini, /etc/php/8.1/fpm/conf.d/20-shmop.ini, /etc/php/8.1/fpm/conf.d/20-simplexml.ini, /etc/php/8.1/fpm/conf.d/20-soap.ini, /etc/php/8.1/fpm/conf.d/20-sockets.ini, /etc/php/8.1/fpm/conf.d/20-sysvmsg.ini, /etc/php/8.1/fpm/conf.d/20-sysvsem.ini, /etc/php/8.1/fpm/conf.d/20-sysvshm.ini, /etc/php/8.1/fpm/conf.d/20-tokenizer.ini, /etc/php/8.1/fpm/conf.d/20-xmlreader.ini, /etc/php/8.1/fpm/conf.d/20-xmlrpc.ini, /etc/php/8.1/fpm/conf.d/20-xmlwriter.ini, /etc/php/8.1/fpm/conf.d/20-xsl.ini, /etc/php/8.1/fpm/conf.d/20-zip.ini
PHP API | 20210902
PHP Extension | 20210902
Zend Extension | 420210902
Zend Extension Build | API420210902, NTS
PHP Extension Build | API20210902, NTS
Debug Build | no
Thread Safety | disabled
Zend Signal Handling | enabled
Zend Memory Manager | enabled
Zend Multibyte Support | provided by mbstring
IPv6 Support | enabled
DTrace Support | available, disabled
Registered PHP Streams | https, ftps, compress.zlib, php, file, glob, data, http, ftp, zip, phar
Registered Stream Socket Transports | tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2, tlsv1.3
Registered Stream Filters | zlib.*, string.rot13, string.toupper, string.tolower, convert.*, consumed, dechunk, convert.iconv.*

**Comment by bembelimen** [comment]
Hello @Stuartemk ,
could you please check what is you memory_limit and if you can increase it?

**Comment by Stuartemk** [comment]
> Hello @Stuartemk , could you please check what is you memory_limit and if you can increase it?

The error occurs with 64MB
Fixed by changing the memory limit to 128MB

I think it should be stated in the system requirements that to use Joomla a minimum of 128MB of memory is required.

https://docs.joomla.org/J4.x:Optional_Technical_Requirements

**Comment by carlitorweb** [comment]
Documentation added ✔️

**Comment by alikon** [comment]
can you post the link of the document,
so we can close the issue redirecting on doc

**Comment by alikon** [comment]
closing the issue as pre document : https://docs.joomla.org/J4.x:Optional_Technical_Requirements
