### ISSUE TITLE
Upgrade from 4.2.7-rc1 to 4.2.7 stable version

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#39761]
### Steps to reproduce the issue
I updated the 4.2.6 system to version 4.2.7 RC1. When I start to update to the stable version 4.2.7 released today, I get the following error.

### Expected result
The result after clicking the start update button:

![1](https://user-images.githubusercontent.com/423588/215806891-323f46a5-fbeb-4031-9b01-a995d6ae79dc.jpg)

### System information (as much as possible)
Database Version	5.7.40-cll-lve
PHP Version	8.1.13

**Comment by chmst** [comment]
We are now on 4.2.7 stable, please update to the stable version.

**Comment by chmst** [comment]
Please repeat.

**Comment by webgras** [comment]
I had the same problem with a local RC, but it works now for me.

**Comment by joomlaphp** [comment]
Ok it works, thanks
