### ISSUE TITLE
SEARCH and CUSTOM FIELDS Custom field content is not indexed by SmartSearch

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#39779]
### Steps to reproduce the problem
Create a Custom Field e.g. of type "Text", create an "Article X" with "Title", "Article Text A" (in the Article Text field) and "Article Text B" (in the CustomField). Search with SmartSearch for the text "Articletext A. => The Article X appears in the hit list. Now search with SmartSearch for the text "Article Text  B..

### Expected result
The Article X appears in the hit list.

### Actual result
Article X does NOT appear in the hit list.

### System information (as far as possible)
J4.2.6, PHP 8.1.14

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/38650
