### ISSUE TITLE
[4.2.7] Atum Login Logo stretched

### ISSUE THREAD

**Issue by forrestkirby** [joomla/joomla-cms#39776]
### Steps to reproduce the issue

- edit the *Atum - Default* template style
- choose a Login Logo, for example use https://unsplash.com/de/fotos/zUNs99PGDg0
- save

### Expected result

The logo is displayed in its intrinsic aspect ratio. This was the case in versions prior to 4.2.7, e. g. in 4.2.6.

### Actual result

The logo is displayed strechted, the rendered aspect ratio does not match the intrinsic aspect ratio.

### System information (as much as possible)

Joomla 4.2.7 Stable
PHP 8.1.13
Apache

### Additional comments

If you manually change the content in the image field from
`images/nathan-dumlao-zUNs99PGDg0-unsplash.jpg#joomlaImage://local-images/nathan-dumlao-zUNs99PGDg0-unsplash.jpg?width=4480&height=6720` to `images/nathan-dumlao-zUNs99PGDg0-unsplash.jpg`, the image is displayed properly.

![](https://cdn.screencast.com/uploads/g0003029ruijZTvMKCecIfP5hma4I/SNGOUT2091.jpg?sv=2021-08-06&st=2023-02-02T10%3A34%3A21Z&se=2023-02-03T10%3A34%3A21Z&sr=b&sp=r&sig=gPx9%2F8MIXpICNz%2FTGRtsR8QOkerMnUMuoxYBiuUePx0%3D)

**Comment by ChristineWk** [comment]
See here please: #39766<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39776">issues.joomla.org/tracker/joomla-cms/39776</a>.</sub>

**Comment by forrestkirby** [comment]
Thank you, I didn’t find that issue when searching similar issues first because I searched for “logo”.
