### ISSUE TITLE
Blog item showing $this->item->introtext; when $this->params->get('show_intro')  === 0

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-cms#39780]
### Steps to reproduce the issue
1 - Create a menu item to a category blog page
2 - Set 'Intro Text' to 'hide'

### Expected result
Intro text is not loaded

### Actual result
Intro text is loaded

### System information (as much as possible)
J The currently installed Joomla! version is "‎4.2.6"

### Additional comments
components/com_content/tmpl/category/blog_item.php
`	<?php echo $this->item->introtext; ?>`

Change to 
		
		`<?php if ($this->params->get('show_intro', '1') == '1') : ?>
			<?php echo $this->item->introtext; ?>
		<?php endif; ?>`

Also I think 
	`<?php if (!$params->get('show_intro')) : ?>
			<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
			<?php echo $this->item->event->afterDisplayTitle; ?>
		<?php endif; ?>`
Should be 
`<?php if ($this->params->get('show_intro', '1') == '1') : ?>
<?php // Content is generated by content plugin event "onContentAfterTitle" ?>
			<?php echo $this->item->event->afterDisplayTitle; ?>
		<?php endif; ?>`
????
Thanks :)

**Comment by Fedik** [comment]
If I right remamber, that option is for hide the Intro in Article detail view only. So you have "Intro" on Blog view, and rest of article in a detail view.

**Comment by brianteeman** [comment]
The option to show/hide the intorotext refers to if it should be shown on the full article view after clicking on readmorFor example if you have a movie review website you may show a precis of the movie on the blog view and then hide that precis when you click through to the full page view

**Comment by saraheagle** [comment]
It is confusing, maybe the wording "Intro Text" should be "Intro Text on Full Article"?

**Comment by brianteeman** [comment]
The description for the blog menu item type is "displays article introductions"
![image](https://user-images.githubusercontent.com/1296369/216604292-3f751586-cf9f-4ae9-b87d-ffafac54f1e4.png)

What is it you are actually trying to do? Sounds like you are perhaps trying to display the article title, image and readmore link only. If so then you dont need to create any introtext at all in your article and just add the readmore at the top of the article. OR do a template override to remove the line 
```	<?php echo $this->item->introtext; ?>```

**Comment by saraheagle** [comment]
Yes, that is true. It's just there isn't a way from a menu item to have a link to articles in a category and just have their images, without the introtext, without using a module. I think this is quite a basic requirement?? Quite often I would just visually hide the text, as it doesn't take much time to load, but on this particular site, there were about 50 pages that all had large image galleries in the intro text. In the end I moved the 'introtext' to the 'fulltext' in the database itself as luckily the 'fulltext' column was empty for that category.
It might be helpful to have two checkboxes, one to show the the blog introtext and one for the full page introtext?
Thanks very much for your help.

**Comment by saraheagle** [comment]
I try not to use tempate overrides unless its absolutley necessary as they require checking regularly, I would rather use core layouts & css only. The cards are great :D Thanks very much.

**Comment by joomdonation** [comment]
Closing because this is not a core issue but the user misunderstand the parameter.
