### ISSUE TITLE
Wrong type of message on saving module in frontend editing

### ISSUE THREAD

**Issue by Kaushik1216** [joomla/joomla-cms#39790]
### Steps to reproduce the issue

Just do editing of any module in frontend editing and save it.

### Expected result
A success msg with green color will shown after save 

### Actual result
![Screenshot from 2023-02-04 22-14-48](https://user-images.githubusercontent.com/100058812/216779528-45808c14-b117-4144-8806-027f79e28acc.png)

A info type msg with boostrap info color will shown after save
### System info
Joomla 4.2.6
Browser Chrome,Ubuntu
php 8.1

### Additional comments
On inpecting browser I found that type of msg is info instead of success

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39794 . Thanks in advance.
