### ISSUE TITLE
[4.3] Large gap to the right of infobar in Media Manager

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#39792]
### Steps to reproduce the issue
Go to Content > Media.
Click `i` icon to display info bar.

### Actual result
![media-manager](https://user-images.githubusercontent.com/368084/216787522-9f0a8a0f-0949-4ad5-a54b-348d9154825d.jpg)

### System information (as much as possible)
4.3.0 beta1

**Comment by dgrammatiko** [comment]
@Quy remove this line https://github.com/joomla/joomla-cms/blob/d9297853c98a7604f3a41c56b86470543c6cf6ea/administrator/components/com_media/resources/scripts/components/browser/browser.vue#L124

The up merge went wrong I guess

**Comment by avijain09** [comment]
Can you please assign me this issue.

**Comment by chmst** [comment]
@avijain09 Just work on it and make a PR, no need for assignment.

**Comment by chmst** [comment]
This looks so strange because the definition list is no longer horizontal (in bootstrap 5?).  We have the same issue for shortcut keys, looks simply weird.

**Comment by brianteeman** [comment]
No gap here either

**Comment by dgrammatiko** [comment]
> But I don't have this gap in my installation (win 11, firefox)

That screenshot is **NOT** from 4.3-beta.1. The order button is missing...

**Comment by brianteeman** [comment]
issue confirmed

**Comment by dgrammatiko** [comment]
Test https://github.com/joomla/joomla-cms/pull/39796

**Comment by chmst** [comment]
it was the browser cache, not the branch _._

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39796 . Thanks in advance.
