### ISSUE TITLE
Font Awesome icons do not show up or show up wrong

### ISSUE THREAD

**Issue by cyanama** [joomla/joomla-cms#39802]
### Steps to reproduce the issue
create a menu and assign **icon-tree** as link class

### Expected result
the menu line should show a leading tree (fa /f1bb)

### Actual result
the menu line shows code-merge (fa /f387) instead

### Steps to reproduce the issue
create a menu and assign **icon-bomb** as link class

### Expected result
the menu line should show a leading bomb (fa /f1e2)

### Actual result
the menu line shows no leading icon

### System information (as much as possible)
Joomla 4.3 prerelease
Font Awesome 5.15.4

**Comment by Kaushik1216** [comment]
It's work for me perfect.What you write in LINK CLASS ? .You can try by writing fa fa-tree in Link class than it work

**Comment by brianteeman** [comment]
The issue is because fontawesome is not a single font of icons. Joomla includes brands, regular and solid and you need to use the additional class for those as well as the icon class

eg
fab fa-youtube
fas fa-folder-open
far fa-folder-open
fa fa-folder-open same as far above

All icons are not present in each font so it is important to use the correct additional class

**Comment by cyanama** [comment]
Thanks for the clarifications
Yes, I used **icon-xyz** as font class as mentioned in my initial statement. fa-tree works fine. Thanks!

I'm aware that this is not the right place, but maybe can some expert here please point me to a description how to upgrade to fa6? I got a detailed description from ChatGBT, however it requires to alter css files, that are out of scope of overrides, so I'm not sure if this is the way to go.

thanks a lot
Cyana<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39802">issues.joomla.org/tracker/joomla-cms/39802</a>.</sub>

**Comment by Quy** [comment]
Please ask in [Joomla Forum](https://forum.joomla.org/) or in [Discussions](https://github.com/joomla/joomla-cms/discussions?discussions_q=fontawesome).
