### ISSUE TITLE
Email cloak plugin fails for emails with IDN

### ISSUE THREAD

**Issue by Globulopolis** [joomla/joomla-cms#39811]
### Steps to reproduce the issue
Insert example link in article: test@домен.ком and save.

### Expected result
Cloaked email

### Actual result
test@домен.ком

### Additional comments
If email insert as link in editor it's working as expected.

**Comment by LukasHH** [comment]
I have an idea:
change the row https://github.com/joomla/joomla-cms/blob/c3b11efd14cde5002d4f3bf1228d94a52e4eb8a2/plugins/content/emailcloak/emailcloak.php#L106

to:
        $searchEmail = '([\w\.\'\-\+]+\@(?:[a-z0-9\.\-\p{L}]+\.)+(?:[a-zA-Z0-9\-\p{L}]{2,24}))';

**\p{L}** => matches any kind of letter from any language

and the row
https://github.com/joomla/joomla-cms/blob/c3b11efd14cde5002d4f3bf1228d94a52e4eb8a2/plugins/content/emailcloak/emailcloak.php#L474

to
        $pattern = '~<[^<]*(?<!\/)>(*SKIP)(*F)|' . $searchEmail . '~iu';

**\u** => unicode

**Comment by alikon** [comment]
please test #39888

**Comment by richard67** [comment]
@LukasHH Could you check that PR #39888 ? I think it has several mistakes.
