### ISSUE TITLE
[4.3 beta 1] help links

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39818]
### Steps to reproduce the issue
all the help links fail and load the home page of docs.joomla.org

![image](https://user-images.githubusercontent.com/1296369/218248411-95a6038c-744f-4083-9799-311a0ce8fc45.png)

**Comment by harsitagarwalla187** [comment]
I have gone through the link mentioned in https://github.com/joomla/docs.joomla.org documentation. 
All the links on the website(https://docs-next.joomla.org) are working fine.  
Am I understanding wrong?

**Comment by brianteeman** [comment]
yes you are mistaken.
![image](https://user-images.githubusercontent.com/1296369/218248411-95a6038c-744f-4083-9799-311a0ce8fc45.png)

**Comment by iitian360** [comment]
@brianteeman, I have also gone through [https://github.com/joomla/docs.joomla.org documentation] documentation, and there are no such links as you mentioned above☝️

**Comment by brianteeman** [comment]
This repository is for issues with the Joomla CMS. If I was reporting that the links were broken on another repository then I would have reported it there. As I didn't then clearly I am referring to a bug in Joomla CMS. Thats why you can't find the liniks when you are looking in the wrong place. Although why you would even look at that github repository I have no idea as no where did I mention it.

/me has no patience to deal with this

**Comment by brianteeman** [comment]
Reminder again that this needs to be resolved.
Please raise this to a release blocker

**Comment by brianteeman** [comment]
I hope this is fixed before any rc2

**Comment by ceford** [comment]
In 4.2 the button code looks like this:
```
<button class="button-help btn btn-info" type="button" onclick="Joomla.popupWindow('https:\/\/help.joomla.org\/proxy?keyref=Help42:Users&amp;lang=en', 'Help', 700, 500, 1)" title="Opens in a new window">
    <span class="icon-question" aria-hidden="true"></span>
    Help</button>
```

In 4.3 it looks like this:

```
<button class="button-help btn btn-info js-toolbar-help-btn" data-url="https:\/\/help.joomla.org\/proxy?keyref=Help42:Users&amp;lang=en" data-title="Help" data-width="700" data-height="500" data-scroll="1" type="button" title="Opens in a new window">
    <span class="icon-question" aria-hidden="true"></span>
    Help</button>
```
For the latter, the back slashes in the url need to be removed. Test it by hard-coding the minor version of $helpurl in configuration.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39818">issues.joomla.org/tracker/joomla-cms/39818</a>.</sub>

**Comment by brianteeman** [comment]
@ceford no the issue I am reporting is  nothing to do with that. It is simply a 1 line change that needs to be made on the help site so that the proxy supports 4.3

**Comment by ceford** [comment]
OK. I created a separate issue.

**Comment by brianteeman** [comment]
:( grrh

**Comment by brianteeman** [comment]
Thanks @wilsonge
