### ISSUE TITLE
[4.3 beta1] template diff 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39825]
Create a template override and make some changes to the file
in the templates component options change the file diff view to "inl9ine
check the override and you will see an unwanted column selector
![image](https://user-images.githubusercontent.com/1296369/217610611-3b18b323-4f94-4645-822e-b3d4dfd95d20.png)

This is caused by my pull request #39380 which added the column selector to the override list tab.

I don't know how to prevent it also loading in the diff view

**Comment by avijain09** [comment]
Can you please brief what exactly is the issue and what is expected to be done.

**Comment by dgrammatiko** [comment]
@brianteeman check #39828

Would be nice if you could pass an attribute to the table, so the ignore conditional would be more generic...

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39828 . Thanks in advance.
