### ISSUE TITLE
Wrong logo size on login page (Administrator Panel) in ver.4.2.7

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#39821]
The logo has 800x264px size. It is assigned to the login page in Atum template:
<img width="1415" alt="Снимок экрана 2023-02-08 в 01 17 11" src="https://user-images.githubusercontent.com/3432048/217454401-a9deb6a4-2bfe-4c65-9d29-2a462d49833b.png">

And here is the result:
<img width="1182" alt="Снимок экрана 2023-02-08 в 01 18 18" src="https://user-images.githubusercontent.com/3432048/217454528-aca3d2a4-213d-45ec-9323-26b01af22501.png">

The script attempts to display 800x264, but the image is too big and deformed.

I played in browser console and set the width to 300px and it looks nice:
<img width="1407" alt="Снимок экрана 2023-02-08 в 01 18 091" src="https://user-images.githubusercontent.com/3432048/217455128-5f5099e0-78a0-48b8-bbb1-259a61f18c43.png">

This issue appeared after upgrading from Joomla 4.2.6 to 4.2.7.

**Comment by chmst** [comment]
https://github.com/joomla/joomla-cms/pull/39766 closing as already fixed
