### ISSUE TITLE
[4.3 beta1] Extension Install - Unable to detect manifest file.

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39823]
Almost every extension that I tried to install via _install from web_ failed with the very unhelpful message "Unable to detect manifest file".

That error message is not helpful. The actual problem is that the extension xml file that is used by the _ifw_ plugin typically has a targetplatform attribute and most extension have a regex here that is not compatible with 4.3.

eg
`<targetplatform name="joomla" version="((4\.(0|1|2))"/>`

so there are two issues here

1. Extension developers need to be reminded that they need to update the regex to one that include 4.3
2. The error message should be changed to something more helpful. Something like _This extension is not declared as being compatible with your version of Joomla. You should contact the extension developer._

@obuisard @crystalenka

**Comment by obuisard** [comment]
Good point Brian @brianteeman. I agree totally with the message. 
I will also make sure I remind developers (like in the third party JUG) they need to update their manifest files.
However, I know some developers who wait until RCs or even final releases before they change the manifests, especially if they are not done with testing their extensions under the new version.

**Comment by brianteeman** [comment]
iirc its not going to be a simple change for the error message as thats a generic cacth all error, But I will check tomorrow.

Regarding let extension developers know I would suggest that it is included in the release announcements AND also that all ext developers listed on the JED are emailed.

**Comment by obuisard** [comment]
> Regarding let extension developers know I would suggest that it is included in the release announcements AND also that all ext developers listed on the JED are emailed.

I will check with Philip.

**Comment by brianteeman** [comment]
Reminder

**Comment by obuisard** [comment]
I wrote a post in the third-party developer JUG last February and talked to Phil about it then.
I will write a reminder in Mattermost in the proper channel(s).

**Comment by brianteeman** [comment]
thanks
