### ISSUE TITLE
Indexer is messing up with CLI

### ISSUE THREAD

**Issue by alex-storytellingmedia** [joomla/joomla-cms#39830]
### Steps to reproduce the issue
Launching Indexer via Terminal with code:
php -d memory_limit=512M joomla.php finder:index

### Expected result
To launch the indexer

### Actual result

Finder Indexer
==========================

 Starting Indexer
 Setting up Smart Search plugins
 Setup 9224 items in 0.02 seconds.

In router.php line 635:
                                                                                           
  Call to undefined method Joomla\CMS\Application\ConsoleApplication::getLanguageFilter()  
                                                                                           

finder:index [--minproctime MINPROCTIME] [--pause PAUSE] [--divisor DIVISOR] [--live-site [LIVE-SITE]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command> [<purge>]

### System information (as much as possible)
I'm using Joomla 4.2.7

**Comment by alikon** [comment]
unable to replicate
anyone else ?

**Comment by Irata** [comment]
I attempted the same command on both J4.2.5 and J4.2.7 and both worked without error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39830">issues.joomla.org/tracker/joomla-cms/39830</a>.</sub>

**Comment by joomdonation** [comment]
Could not re-procedure the issue, too. My guess is that on your site, there are third party finder plugins which uses `Route::_()` method to generate URL of item and it causes the error. You would have to find that plugin (could try to disable one by one) and ask the the developer of that plugin to correct it

As 3 of us could not re-procedure the issues, I would say that this is none core issue and close it.
