### ISSUE TITLE
Email Cloaking triggers on image files with @ in the name

### ISSUE THREAD

**Issue by crystalenka** [joomla/joomla-cms#39832]
### Steps to reproduce the issue
Rename an image to include `@2x` in the filename. For example, `forest@2x.png`. 
Select it as an image somewhere in Joomla so it displays on the front end, for example as an intro or full text image of an article.
Ensure email cloaking is enabled.
Navigate to the front end.

### Expected result
Image displays normally, like so:
``` HTML
<img src="path-to-image/forest@2x.png" alt="alt text" />
```

### Actual result
The img output is totally broken.

``` HTML
<img src="path-to-image/&lt;joomla-hidden-mail  is-link=" 1"="" is-email="1" first="Z3Jvd3Ro" last="MngucG5n" text="Z3Jvd3RoQDJ4LnBuZw==" base="">
This email address is being protected from spambots. You need JavaScript enabled to view it." alt="" width="200px" height="200px" /&gt;
```

Screenshot:
<img width="298" alt="Screenshot 2023-02-10 at 12 02 52" src="https://user-images.githubusercontent.com/9141288/218062892-9a48c1da-5bfb-42f0-afec-e5d41a23057c.png">

### System information (as much as possible)
Joomla 4.2.7

### Additional comments
Many image and vector editing programs will export images with the scale as part of the file name, for example `imagename@2x.png`, so this is not an uncommon situation. The `@` triggers the email cloaking plugin and breaks the image.

**Comment by crystalenka** [comment]
I believe this bug was introduced with https://github.com/joomla/joomla-cms/pull/39508/files

**Comment by brianteeman** [comment]
duplicate report #39786 ?

**Comment by crystalenka** [comment]
Yup looks like the same thing, though this issue has a bit more context

**Comment by richard67** [comment]
Anyway it's a duplicate report and so one of the 2 issues should be closed. Normally we close the newer one as the older one already has some discussion.

**Comment by richard67** [comment]
Closing as duplicate report. See issue #39786 . Let's continue discussion there. I've added a comment there about the common use of "@" by some image editors. Thanks for reporting.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39832">issues.joomla.org/tracker/joomla-cms/39832</a>.</sub>
