### ISSUE TITLE
[4] Subform field uses wrong variables for tooltip with groupByFieldset layout

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#39848]
### Steps to reproduce the issue
The layout uses `$field` to get the `id` and the `description` which is not possible because `$field` is not defined.

https://github.com/joomla/joomla-cms/blob/669e2fc16fe41bc206f7030aa5f2f5b76f02a98a/layouts/joomla/form/field/subform/repeatable-table.php#L55

### Additional comments
I don't use this layout and don't know how to use it just saw this while debugging another thing and just wanted to mention it if someone once to fix it.

**Comment by Fedik** [comment]
yeap that is wrong, 
was added by @brianteeman in #26614

There is no field, but fieldset is used.

**Comment by brianteeman** [comment]
It is used in the core mail domain options

![image](https://user-images.githubusercontent.com/1296369/218309349-c2a94353-1e6d-4790-bd06-3cff66cbc6a6.png)

**Comment by Fedik** [comment]
Brian it does not use `groupByFieldset` option there :wink: 
The bug affects only cases when `groupByFieldset="true"` is used in subform field xml.

**Comment by brianteeman** [comment]
I mentioned it for reference only

**Comment by Fedik** [comment]
Please test #39894
