### ISSUE TITLE
Adding functionality to change dimensions of images.

### ISSUE THREAD

**Issue by harsh5902** [joomla/joomla-cms#39843]
### Is your feature request related to a problem? Please describe.
Right now, when we add image to the joomla website, there is not any option available to change dimension of the images on the joomla website itself (height and width of image).

### Describe the solution you'd like
I would like to add the functionality to change the image dimensions according to user's will.

**Comment by brianteeman** [comment]
This is already possible in the Media component

**Comment by harsh5902** [comment]
yes, but it would be easier if we add this functionality while uploading the photo itself. Rather than later going to media tab for changing it.

**Comment by brianteeman** [comment]
That was not clear from your descrirption

**Comment by harsh5902** [comment]
sorry, for little unclear description
So can I work on it??

**Comment by brianteeman** [comment]
In Joomla no one needs permission to create something. Create it, submit a pull request and it will be reviewed

**Comment by harsh5902** [comment]
sure thanks
