### ISSUE TITLE
[4.2] User Action Information emails do contain HTML links in plain text emails

### ISSUE THREAD

**Issue by ManuelHu** [joomla/joomla-cms#39851]
Also described by @ReLater in https://github.com/joomla/joomla-cms/issues/39774#issuecomment-1425910872. This is an additional issue, that is significantly older (i suppose since the introduction of mail templates)

### Steps to reproduce the issue
* Install joomla 4.2.6 _or_ 4.2.7 with #39850 applied
* Make sure action logs for user events are enabled and configure working system email sending
* In the user settings for a user with a valid email address (you can receive mail on), enable user action information emails for the user component.
* Log out and log back in
* Look at the emails you should have received

### Expected result
Plain text mails do not contain HTML links

### Actual result
Plain text mails do contain HTML links, which renders weird in some mail clients

### System information (as much as possible)
* joomla 4.2.7 on PHP 8.1
* Mail clients: e.g. Thunderbird, but also others

### Additional comments
This appears to be a regression from the introduction of MailTemplates in Joomla 4.x and is working in 3.10.x
* All (default) mail templates are plain text in 4.2
* In 3.10.x, user information mails are rendered via the "normal" layout way - always producing HTML mails: [administrator/components/com_actionlogs/models/actionlog.php#L167](https://github.com/joomla/joomla-cms/blob/3.10-dev/administrator/components/com_actionlogs/models/actionlog.php#L167)
* The data passed to the template did not change significantly between 3.10.x and 4.x, and still contains HTML markup in the bound values

This is a problematic situation, as the new mail templates also support HTML mails (that are disabled by default?), but there is no way to differentiate the values passed to the template. All simple fixes will lead to either the HTML emails losing the links, or to the plain text mails having HTML markup in them.

**Comment by ManuelHu** [comment]
I have thought about different ways to implement this nicely.

1. apply `strip_tags` on all replaced values. This is rather bad, as php's `strip_tags` does not know what a tag is and removes anything between `<` and `>`, possibly removing valid and intended data. -> NOT A SOLUTION
2. add some sort of suffixes to template tags - so that `{USERNAME#strip_html}` will apply the function onto the value (for now only for a strip_tags wrapper, but this could be extended in the future)
3. Add a separate parameter array that will be used for the plain text template mode. This should be merged with the default/HTML array before applying it, to gracefully fall back if the caller does not specify extra text-mode data

Both options 2 and 3 should be viable in a technical sense, and could be used to solve this issue.

**Comment by ManuelHu** [comment]
I have implemented strategy "3" in #40033. Please only close this issue after the strategy is approved and not scrapped :-)

**Comment by Quy** [comment]
Closing as PR is merged. Thank you.
