### ISSUE TITLE
An Error Occured

### ISSUE THREAD

**Issue by sdhinternet** [joomla/joomla-cms#39877]
Am using Joomla 4.2.8 - Brand new install, all of a sudden it stated saying "An Error Occurred" when I upload any image/s
Can any one help

**Comment by Kaushik1216** [comment]
Please login again and try to upload image again also check image extension than you allow in adminstrator  and your uploading image extension

**Comment by ssnobben** [comment]
Better ask this question of a problem first to forum here: https://forum.joomla.org/viewforum.php?f=810&sid=67adbaa7bdbd2db63cb41818de766e61<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39877">issues.joomla.org/tracker/joomla-cms/39877</a>.</sub>

**Comment by sdhinternet** [comment]
Have tried, the weird thing is if I upload using the BLOG when creating a new article it uploads - but I cannot see where image extension??
Also it was working earlier, I uploaded and image went to upload another and got the error
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39877">issues.joomla.org/tracker/joomla-cms/39877</a>.</sub>

**Comment by sdhinternet** [comment]
Sorted thank you, the files where jpeg and they where not on the legal listSent from my GalaxyRegards Shaun
-------- Original message --------From: KaushikVishwakarma ***@***.***> Date: 17/02/2023  11:29  (GMT+00:00) To: joomla/joomla-cms ***@***.***> Cc: sdhinternet ***@***.***>, Author ***@***.***> Subject: Re: [joomla/joomla-cms] An Error Occured (Issue #39877) 
Please login again and try to upload image again also check image extension than you allow in adminstrator  and your uploading image extension
