### ISSUE TITLE
Source code modal does not work as accepeted on small screen

### ISSUE THREAD

**Issue by Kaushik1216** [joomla/joomla-cms#39871]
### Steps to reproduce the issue
open source modal near 500px width after adding code try to click on **OK** button to save it .As left side text on OK button you are not unable to click on it

### Expected result
we can click on ok button

### Actual result
You can not click on ok button thus unable to save changes in source code modal
![Screenshot from 2023-02-15 17-41-58](https://user-images.githubusercontent.com/100058812/219373911-959a4021-4b0e-450f-8516-d6a873c450a6.png)

### System information (as much as possible)
joomla 4.2.7

**Comment by richard67** [comment]
Confirmed.

**Comment by N6REJ** [comment]
@Kaushik1216 this is a issue with tinymce's "oxide" skin.  Please inform them of this issue.  Feel free to post a link to your issue #

**Comment by N6REJ** [comment]
@dgrammatiko do we close this as a tinymce issue?

**Comment by dgrammatiko** [comment]
@N6REJ this is **NOT** a tinyMCE problem. The issue is the absolute position of the help text [here](https://github.com/joomla/joomla-cms/blob/ac2658e7981378f9e88dca5a1673c5ed28a0d5b7/build/media_source/plg_editors_tinymce/js/plugins/highlighter/source.es6.js#L188)

**Comment by brianteeman** [comment]
The modal is nothing to do with tinymce

**Comment by dgrammatiko** [comment]
@N6REJ this is **NOT** a tinyMCE problem. The issue is the absolute position of the help text [here](https://github.com/joomla/joomla-cms/blob/ac2658e7981378f9e88dca5a1673c5ed28a0d5b7/build/media_source/plg_editors_tinymce/js/plugins/highlighter/source.es6.js#L188)

**Comment by N6REJ** [comment]
@dgrammatiko when I looked @ the css I saw it was coming from .../skins/oxide/skins.min.css ergo my tinymce statement.  Your the expert at tinymce so I'll shush

**Comment by dgrammatiko** [comment]
I'm not sure which element you were poking, but here's the one causing the problem
![Screenshot 2023-02-16 at 22 23 18](https://user-images.githubusercontent.com/3889375/219490030-06f67086-9e5d-4c8a-ad98-5b24f95b72ce.png)

**Comment by dgrammatiko** [comment]
Please test #39873
