### ISSUE TITLE
E-mail field in contact form showing COM_CONTACT_EMAIL">

### ISSUE THREAD

**Issue by 7u5a** [joomla/joomla-cms#39874]
### Steps to reproduce the issue
When you want to show the email label in the joomla contact form

### Expected result
E-mail or Email

### Actual result
COM_CONTACT_EMAIL">

### System information (as much as possible)
Joomla 4.2.8

### Additional comments
It's not a new bug, has been a problem some time now

**Comment by joomdonation** [comment]
Could you please explain step by step what we need to do to see the issue? If it is a possible, a screenshot shows the issue will help us understand the problem. It could be a problem with core code, or it also comes from your own layout override, so please provide as much information as possible

**Comment by 7u5a** [comment]
When showing the address in the joomla contact form, and want show the email label

![billede](https://user-images.githubusercontent.com/89579091/219541025-fcf1e151-88e0-4861-a074-8d3d30cdb9a4.png)

**Comment by joomdonation** [comment]
Sorry, is your site Joomla 3 or Joomal 4 website? If it is Joomla 4 website, could you please tell me how to configure the system to show email label like that as I could not find it myself. I even search at source code but could not found **COM_CONTACT_EMAIL** , so I don't know where it comes from. Maybe it comes from your layout override?

**Comment by Quy** [comment]
Duplicate #37442?

**Comment by joomdonation** [comment]
@Quy Look like a different issue. But it is very likely it comes from earlier version of Joomla or from a template override for contact form

**Comment by 7u5a** [comment]
I go to System -> Global configuration -> Component -> Contacts
Under the Contact pane I have E-mail selected to show
![billede](https://user-images.githubusercontent.com/89579091/219561294-d56a296d-eb2c-4a93-adee-223fbc86a615.png)

And on the Icon pane I have none slected
![billede](https://user-images.githubusercontent.com/89579091/219561851-eec4c3ac-a87f-4e37-a4b1-e9c22e052020.png)

**Comment by joomdonation** [comment]
@7u5a In this case, I would suggest you to contact the developer of the template and ask him to check and correct it for you. Or if you know code, you can look at PATH_TO_TEMPLATE/html/com_contact/contact/default_address.php to check and correct the code in the override. PATH_TO_TEMPLATE is path to the template which you are using on your site

As this is none core issue, I'm closing.
