### ISSUE TITLE
Remove hardcoded sass embed dependency

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#39882]
For now the sass embed dependency is hardcoded on 4.3 through #39875, because of an issue in upstream https://github.com/sass/embedded-host-node/issues/205. More information can found in discussion here https://github.com/joomla/joomla-cms/pull/39875#discussion_r1110037445.

Once the issue is fixed upstream, we can revert this change in pr #39875.

**Comment by dgrammatiko** [comment]
@laoneo there's a new version `1.58.3` so you can remove the hardcoded one

**Comment by laoneo** [comment]
Thanks for the update. Closing as it works now.
