### ISSUE TITLE
Medianamager: Display problem with the file directories

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#39898]
### Steps to reproduce the issue
Add an adapter to the media manager (e.g. DPMedia). Add a post image to a post.

### Expected result
Vertical scrolling to select a media file is possible.

### Actual result
Vertical scrolling leads to an overlay of the two directories (see video).

### Additional comments

https://user-images.githubusercontent.com/4489029/220136809-dd5eab52-151b-4cc9-b0d9-cc5c1322b93d.mp4

**Comment by brianteeman** [comment]
This is a known issue that I thought had been resolved/ Maybe it was for 4.3?

**Comment by Quy** [comment]
Please test #39266.
