### ISSUE TITLE
Cassiopeia Article full width background

### ISSUE THREAD

**Issue by sergiurat** [joomla/joomla-cms#39899]
I am trying to set a max-width to the content of the website, so it doesn't get too wide for large screens and in the same time to have a different background for each section or blogs. Any solution I found for Articles, didn't work for blogs or newsflash, for example.
If I set a background for the article, the background will not span into the area full-width, but only on a portion of the screen (see capture).
I have being trying to find a solution for a long time, but nothing seem to work. I think that an area or something is missing between the container-component and item-content. This is very annoying because in WordPress it is easy to do (capture1).
The result is that all websites look boxy and old style.
![screen shot 2023-02-20 at 17 38 44](https://issues.joomla.org/uploads/1/4b3982026c24e5843e9d1a1d2e0c9f16.jpg)
![screen shot 2023-02-20 at 17 38 45](https://issues.joomla.org/uploads/1/cc19952317b3ed743cf2c328f703a053.jpg)

**Comment by Prabhav25** [comment]
Can you please let me know, where to implement this @sergiurat

**Comment by brianteeman** [comment]
Without knowing what you have tried it is impossible to give you any advice. From your description I would have thought that you shoould be setting the background on the body. 

The forums are a better place to get support

**Comment by Prabhav25** [comment]
I know how to implement this functionality which has been stated above but where to write that specific piece of code, that is what I'm looking forward to know. SO any help in thatregards would be of great help. Thanks!

**Comment by chmst** [comment]
I think this is not an issue for Joomla core, a full cover background image is a requirement for a template. There are countless templates available and as @brianteeman says - look for Joomla templates or ask in a forum. 

@Prabhav25 if you want to make a PR for an improvement - you are welcome! You find the scss files for templates in the build media source folder. But please be aware that every change there can have side effects or break the bakward compatibility.

**Comment by brianteeman** [comment]
@chmst surely this is a support question and not a feature request and should just be closed?

**Comment by chmst** [comment]
Agree for this request, but we are always open for improvment. 
So, @Prabhav2 if you want to contribute for cassiopeia, feel free to make PRs.

**Comment by sergiurat** [comment]
I think it should be in the core, within the article.
The main reason is that we need to keep the amazing speed advantage of J4.
So, in the article, there should be a layer of content and below it, there should be a second layer where to put the text and pictures. The first layer should be used for background and the second one for text, modules, pictures, etc. If you have a background set in the article, module, blogpost, you should inherit it full-width on a separate layer.
We should be able to customize background separately from text and other content. For example, background is full width, with a picture or pattern behind and the text and everything in the article content with max-width 1600px, centered.
All should be done within the article, either by a special css for section, div, etc, or for the whole article within a "Background" selector.
