### ISSUE TITLE
Requires Password Reset does not work with users who have MFA enabled

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#39895]
### Steps to reproduce the issue
The Requires Password Reset feature needs to deny login to the site and ask the user to go through the password reset (instead of trying to redirect them to the password reset page) when MFA is enabled for this user. For the reasoning see https://github.com/joomla/joomla-cms/issues/38788#issuecomment-1253440628

**Comment by Hackwar** [comment]
I created a PR #44521 to fix this. Please test it. Since we have a PR, I'm closing this one. Thanks for reporting.
