### ISSUE TITLE
Link Icon Class with FontAwesome not working

### ISSUE THREAD

**Issue by icc365** [joomla/joomla-cms#39892]
### Steps to reproduce the issue
1. Ensure FontAwesome is loading
2. Create a Menu (for social icons that will use FontAwesome v5.15)
3. Add at least one menu item using the URL type and create a Twitter item.
4. In the "Link Icon Class" field, enter: fab fa-twitter
5. In the "Display Menu Item Title" setting, toggle to off to ensure only the icon shows.
6. Save

### Expected result
My understanding is that this allows for just the icon to show with the menu item title disabled.

### Actual result
No icon is showing and the source code shows no association with the icon or the FontAwesome class being applied; only the menu item title is showing.

### System information (as much as possible)
Localhost via XAMPP on a Windows 10 Pro system. Joomla 4.28 installed. Dependency is enabled for FontAwesome through a template I am building based on Cassiopeia.

### Additional comments
As a side test, instead of entering the fab fa-twitter into the Link Icon Class field, enter it into the Link Class field. The icon then shows up on the front end which is applied to the link <a>. It also doesn't matter if the Display Menu Item Title is on or off, the title still shows. This only seems to work if I use an image instead.

On a side note about the link title, I would recommend wrapping the anchor text with at least a span for added customization. But the big issue here is trying to show just a FontAwesome icon with the title hidden/disabled. At the moment, just to get a linked icon only, I had to heavily customize the CSS for this social menu using absolute positioning, sizing, z-index, visibility hidden, etc.

![screen shot 2023-02-19 at 18 43 09](https://issues.joomla.org/uploads/1/cd2cfb9c1cfe447a41ce1b0021b9f0f0.jpg)
![screen shot 2023-02-19 at 18 43 12](https://issues.joomla.org/uploads/1/6b0da902e94e34a6a6e85e97a564a889.jpg)![screen shot 2023-02-19 at 18 43 16](https://issues.joomla.org/uploads/1/3c1233c25574a61c74e56cc275e577ac.jpg)![screen shot 2023-02-19 at 18 43 19](https://issues.joomla.org/uploads/1/c09b4f245220a582cb6c7c0c7c147fe2.jpg)![screen shot 2023-02-19 at 18 43 22](https://issues.joomla.org/uploads/1/6bf29c2be3733fe860ec24a5923d0b4f.jpg)![screen shot 2023-02-19 at 18 45 52](https://issues.joomla.org/uploads/1/22463a4b8fecf5f856419947d4e6e530.jpg)

**Comment by brianteeman** [comment]
I am unabe to replicate this using cassiopeia

![image](https://user-images.githubusercontent.com/1296369/219968954-43db98ed-2903-45ef-9861-b406e5c17dc3.png)

![image](https://user-images.githubusercontent.com/1296369/219968967-5452666d-eb23-45ae-aa66-37a3f485b523.png)

**Comment by icc365** [comment]
I didn't think to try this with Cassiopeia--I will do that right now. If it's related to my custom template, I will be a bit curious as to what is causing the issue on my end. I will delete the mod_menu override in my template to test also.

**Comment by icc365** [comment]
Looks like the override mod_menu is the culprit. No bug then except what I did. I'll close this out. Thanks!
