### ISSUE TITLE
Non-SEF urls still remains in Article's Link A parameter

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#39908]
Go to edit article mode > Images and Links 
Add non-SEF url in Link A parameter:
<img width="1637" alt="Снимок экрана 2023-02-21 в 22 41 46" src="https://user-images.githubusercontent.com/3432048/220442849-5e19573d-585d-41ab-afea-22be02458221.png">

`/index.php?option=com_content&amp;view=article&amp;id=1&amp;catid=2`

And this non-SEF url still remains on the front-end. 
I expect to get SEF URL since SEF mode is enabled. 
And I use non-SEF URL to avoid 404 error if article's alias will be changed.
 
Joomla 4.2.8

**Comment by joomdonation** [comment]
@Sulpher Our System - SEF plugin can only convert the URL to SEF URL if the link starts with **index.php**. In this case, the link starts with **/index.php** (note the slash at the beginning) and it is not being converted (I don't know why we decided to add the / to the link like that)

**Comment by Sulpher** [comment]
> @Sulpher Our System - SEF plugin can only convert the URL to SEF URL if the link starts with **index.php**. In this case, the link starts with **/index.php** (note the slash at the beginning) and it is not being converted (I don't know why we decided to add the / to the link like that)

Yes, but the slash is being added by Joomla after saving since I always paste the non-SEF URL as is which starts from index.php.
So, then a patch is needed which prevents of adding slash before the URL.

**Comment by joomdonation** [comment]
@Sulpher Afraid it is designed to work like that. We use [url filter](https://github.com/joomla/joomla-cms/blob/4.2-dev/administrator/components/com_content/forms/article.xml#L800)  to make sure the entered value is really accessible URL. 

You can test it by :

1. Remove `filter="url"` from the code in the above link
2. Enter the URL in the format you mentioned
3. Disable System - SEF plugin

Then try to access to article and click on the link. You will get a broken link. For example, in my test, the link becomes **http://localhost/joomla42/index.php/content-categories/sport/index.php?option=com_article&view=article&id=23**  .

**Comment by joomdonation** [comment]
Closing this issue because it is working as expected as explained above.
