### ISSUE TITLE
JInstaller: :Install: Can't find XML setup file.

### ISSUE THREAD

**Issue by 1825921819** [joomla/joomla-cms#39901]
JInstaller: :Install: Can't find XML setup file.

An error has occurred.
0 Call to a member function attributes() on null

![屏幕截图 2023-02-21 105624](https://user-images.githubusercontent.com/77914295/220237537-aca267ac-0273-4bfd-931f-f03bc6992308.png)
![屏幕截图 2023-02-21 105719](https://user-images.githubusercontent.com/77914295/220237548-b2aa9dbe-9771-485a-a7d7-2ae0d2906c3e.png)

What causes this problem? The system program has opened all permissions; I hope you can help solve it, thank you!

**Comment by joomdonation** [comment]
What did you do (step by step) and got this error? Usually, the issue happens because something wrong with the extension you are installing/uninstalling.

**Comment by 1825921819** [comment]
Installing the Caven Template requires the support of the T3 plug-in. However, when installing the T3, the specific reason for this problem is unknown.

**Comment by 1825921819** [comment]
![屏幕截图 2023-02-21 112020](https://user-images.githubusercontent.com/77914295/220239438-023317ac-6c73-4a6a-af19-b34650306446.png)
Caven Template

**Comment by joomdonation** [comment]
I just tried to install T3 System plugin and it is installed without any problem. So please make sure you download and installed the right plugin. Attached is a copy of the plugin which I just tried to download and install

[t3-system-plugin_3.1.2.zip](https://github.com/joomla/joomla-cms/files/10789281/t3-system-plugin_3.1.2.zip)

From your screenshot, look like you are using install from folder option. If so, please try to read instructions here https://docs.joomlabamboo.com/getting-started/how-to-install-items-using-the-tmp-folder-in-joomla-3.html to install it (I just googled it quickly and found the link) and you should be able to install it. Or better, use Upload Package File installation option to install, that's the easiest way

Anyway, for this issue, you better ask for support on joomlart.com forum or [Joomla forum](https://forum.joomla.org/) .

[t3-system-plugin_3.1.2.zip](https://github.com/joomla/joomla-cms/files/10789285/t3-system-plugin_3.1.2.zip)

I'm closing this issue.

**Comment by 1825921819** [comment]
Ok, thank you very much for your hard work !

**Comment by joomdonation** [comment]
You're welcome !
