### ISSUE TITLE
Contact Form Spam

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39900]
My blog is under a deluge of span from russia :(

In an attempt to block it I have tried to use the banned email function of the contact form.

![image](https://user-images.githubusercontent.com/1296369/220170851-6cb1306f-f0cb-4b8b-a23d-223aafae322e.png)

I have tried various formats for the emails to be blocked but none of them appear to do anything and any contact form submission that I  make using a banned domain or even specific address is still processed.

Is this a case of me configuring it wrongly or does this simply not work in Joomla 4

_I am not asking for advice about stopping spam. Just about this one specific feature of Joomla_

**Comment by Fedik** [comment]
Should be: `mail.ru;list.ru;` or just `.ru` :smile: 
https://github.com/joomla/joomla-cms/blob/f520c98c64efb538e70e918acffb60d07e4d6b1e/components/com_contact/src/Rule/ContactEmailRule.php#L50-L58

**Comment by Fedik** [comment]
btw, the ReCaptcha does not protect from spam anymore, same for invisibleReCaptcha, from my expiriance.
ReCaptcha v3 works better, but it is not in the core, and probably never be.

**Comment by brianteeman** [comment]
yes the recaptcha is doing nothing and will be removed.

I see now that when it says "Separate multiple email addresses with a semicolon." it is very strict.

I had this mail.ru; list.ru
this failed for list.ru because it was checking for spacelist.ru

**Comment by brianteeman** [comment]
perhaps we should add a trim to the explode??

**Comment by Fedik** [comment]
Yes, because you have a space, it failed.

> perhaps we should add a trim to the explode

yea, that sounds as a good idea

**Comment by richard67** [comment]
The description text is also not correct. It is not a list of email addresses but of email addresses or parts of it (e.g. domains). So maybe it should be "Separate multiple email addresses or parts of emails addresses with a semicolon" or something like that.

**Comment by Fedik** [comment]
I mark it as bug, need to fix:
- add trim
- improve description, with infor that it allow to use "substring", and maybe with some examples
