### ISSUE TITLE
List All Categories in an Article Category Tree - unused layout

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39913]
As far as I can tell the layout  \layouts\joomla\content\categories_default_items.php is never used. Maybe thats the root cause of some of the other bugs with the "List All Categories in an Article Category Tree" menu item type

**Comment by joomdonation** [comment]
From what I see by reading code (and testing, too), the layout is not used as all. I think it even not used in Joomla 3.

**Comment by brianteeman** [comment]
closed see #39933
