### ISSUE TITLE
# List All Categories in an Article Category Tree - Blog layout

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39911]
### Steps to reproduce the issue
On a clean site 

1. create the following category structure
- Category1
 -- Subcategory 1-1
- Category 2
-- Subcategory 2-1
- Category 3
-- subcategory-empty
2. Add at least one article to each category except for _subcategory-empty_
3. create a menu item of type _ List All Categories in an Article Category Tree_ 

### Expected result
1. An option to select either the blog or list layouts when you have clicked on a category
2. All the same options you have for a category blog and category list menu item

### Actual result
1. No option exists - it will always be the blog layout
2. there are no options for # Columns or Multi Column Direction

**Comment by joomdonation** [comment]
If I'm not wrong, you can control this from the component settings/options already. For example, if you want the category uses **List** layout when it is clicked, go to Articles , click on Options button in the toolbar. Then on **Category** tab, set **Choose a Layout** parameter to **List**

The blog layout options as you requested #2, could be controlled in **Blog/Featured Layouts** tab on component options

I think it's flexible enough.

**Comment by brianteeman** [comment]
1. You are correct - that is where the decision to display a blog or list comes from. I never would have guessed

This means that 
1. you can not use multiple tree menu item with their own choice
2. there is no way to know that the menu is using this component option
3. if the component is set to list then you should not be presented the blog options and vice versa

Same answer applies to the missing blog options. PLUS if we are to say "just use the component options" for the # columns why are we not also saying "just use the component options" for the # links. There is no logic that these two options are not present

**Comment by brianteeman** [comment]
Now that I know where the settings come from I can try and improve the menu item

**Comment by joomdonation** [comment]
Have to look at it again, but Yes, you can add the missing options to the menu item parameters to improve it.

**Comment by brianteeman** [comment]
closed as we have a pr #39929
