### ISSUE TITLE
List All Categories in an Article Category Tree - Category

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39912]
### Steps to reproduce the issue
On a clean site 

1. create the following category structure
- Category1
 -- Subcategory 1-1
- Category 2
-- Subcategory 2-1
- Category 3
-- subcategory-empty
2. Add at least one article to each category except for _subcategory-empty_
3. create a menu item of type _ List All Categories in an Article Category Tree_ 
4. There is a tab for Category - “These options are also used when you select one of the category links” set show #articles to none

### Expected result
the subcategories are listed without an article count

### Actual result
the option is ignored (as are the other options in this tab

**Comment by joomdonation** [comment]
> the subcategories are listed without an article count

Are you talking about the article count on the first page or the page when you click on one of the category from first page (Category1 for example)? As I understand, If it is first page, then it is controlled by settings on Categories tab. The setting on Category  tab is used for the page which is displayed when you click on a category from first page.

**Comment by brianteeman** [comment]
found it - thanks
