### ISSUE TITLE
Media manager breadcrumb error

### ISSUE THREAD

**Issue by toonetcreation** [joomla/joomla-cms#39921]
Hi,

On joomla 4.2.8, from media manager I have a folder called images.
But when I click on this folder name from breadcrumb I get this : https://www.screenpresso.com/fr/cloud/mAdld/

Thanks
L.

**Comment by brianteeman** [comment]
Confirmed

**Comment by toonetcreation** [comment]
ok thx

**Comment by dgrammatiko** [comment]
@toonetcreation please test #39922

**Comment by toonetcreation** [comment]
as issue is closed, do you need my test or not?

**Comment by dgrammatiko** [comment]
The issue is closed because there is some code that maybe solves the problem. You should test it as it was you that reported the issue

**Comment by toonetcreation** [comment]
ok understood, I come back to you

**Comment by toonetcreation** [comment]
ok tested from my side and works fine.
thank you
