### ISSUE TITLE
Allow longer clickurl in com_banners

### ISSUE THREAD

**Issue by keep** [joomla/joomla-cms#39925]
### Steps to reproduce the issue
If you use com_banners with external advertisers, sometimes you have the work with very long urls.
When you have a long base url + utm_source + utm_medium + utm_campaig + utm_content etc it easily hits the varchar(200) limit in #__banners.clickurl

### Expected result
Allow longer clickurl

### Actual result
On save you'll get an error: Data too long for column 'clickurl' at row 1

### System information (as much as possible)
Joomla 4.2.8
PHP 8.1

### Additional comments

In my current case I have an url with 250 characters, I'm not sure what would be the best length for the varchar, but more than this.
Using external url shortener services are not acceptable, because the advertiser's policy doesn't allow using it. Maybe because the referer parameters or the stats, I'm not sure.

**Comment by brianteeman** [comment]
yes it should be bigger - the max allowed for a url is about 2000 in the specifications iirc

**Comment by keep** [comment]
Also the form input should have maxlength attribute according to the length of the field<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39925">issues.joomla.org/tracker/joomla-cms/39925</a>.</sub>

**Comment by alikon** [comment]
please test #39937
