### ISSUE TITLE
[4.2] Make the manifest file type encoding consistent

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#39927]
In the manifest .xml files I see the following:

With a capital: UTF

`<?xml version="1.0" encoding="UTF-8"?>`

or with a lowercase: utf

`<?xml version="1.0" encoding="utf-8"?>`

Proposal: choose a consistent notation.

Note: I don't know what the standard is.

**Comment by joomdonation** [comment]
Base on several sources I found in the internet, both are allowed but **UTF-8** is preferred. You can see examples on this [XML Specification](https://www.w3.org/TR/xml/#charencoding) page uses **UTF-8**, too.

@sandewt If it is possible, please make a PR to change it.

**Comment by sandewt** [comment]
@joomdonation 

It concerns more than 500 files. Changing all these files manually is quite a job with a chance of errors. I assume it can also be done with git or something similar. Sorry, but I'm not familiar enough with that right now.

**Comment by charvimehradu** [comment]
@sandewt @joomdonation I can make a PR for this. Do I need any particular permissions?

**Comment by joomdonation** [comment]
@charvimehradu No permissions is needed. You can make PR, then maintainers will decide if it will be merged. But if you don't want to waste time, maybe wait until there is decision made.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39949 . Thanks in advance.
