### ISSUE TITLE
[4.3] Error creating child templates (Release Blocker)

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39934]
### Steps to reproduce the issue
Create a child template of cassiopeia
Open the new child in the template manager

### Expected result
![image](https://user-images.githubusercontent.com/1296369/221295048-2fbd0b90-82af-4018-9198-7b19f6a32ad0.png)

### Actual result
![image](https://user-images.githubusercontent.com/1296369/221295431-a37dc083-4c7c-4071-99fb-f57dcf34ad00.png)

### Additional comments
The physical folder in /media/templates/site/cassiopeia_check are created

~The difference is that in 4.3 empty folders are not being displayed in the template manager~

**Comment by MacJoom** [comment]
I could not reproduce the isse - the child template was created including the media directories - PHP 8.1 
![chrome-capture-2023-1-25](https://user-images.githubusercontent.com/6154099/221353390-5cbe53a4-ecb5-4999-8c90-e025a04826ed.png)

**Comment by wojtekxtx** [comment]
@brianteeman any logs?

**Comment by chmst** [comment]
I can confirm. Latest pull and npm ci performed.

**Comment by dgrammatiko** [comment]
Maybe related to https://github.com/joomla/joomla-cms/pull/39329

**Comment by joomdonation** [comment]
> Maybe related to #39329

I can confirm that. @ReLater Could you please check ?  Thanks !

**Comment by MacJoom** [comment]
Sorry - confirmed on 4.3-beta3

**Comment by brianteeman** [comment]
confirmed that reverting #39329 resolves the problem

**Comment by ReLater** [comment]
Then revert https://github.com/joomla/joomla-cms/pull/39329 !

**Comment by brianteeman** [comment]
closed

**Comment by ReLater** [comment]
@joomdonation @brianteeman @dgrammatiko 

> I can confirm that. @ReLater Could you please check ? Thanks !

I can NOT confirm this issue here with fresh Joomla 4.2.9-dev nightly of today and Cassiopeia using Bearsampp on Win 10 Pro.

Therefore I think the reason is not my pr but any other change in J!4.3 that ignored that.

**Comment by ReLater** [comment]
Deleted my last comment. After reopening the child template same result like in J!4.3.
