### ISSUE TITLE
ImageList images cannot be WEBP or AVIF

### ISSUE THREAD

**Issue by NicolasDerumigny** [joomla/joomla-cms#39936]
### What needs to be fixed
 Add webp and avif (or the media configured by the user in the global parameters) to [here](https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Form/Field/ImagelistField.php#L42).

### Why this should be fixed
Images cannot be chosen in WEBP or AVIF format with this field.

### How would you fix it
Add `$|\.webp$|\.avif` to the string in `libraries/src/Form/Field/ImagelistField.php`

### Side Effects expected
None

**Comment by chmst** [comment]
Thanks for your suggestion! As you already know how to resolve your request, would you like to make yourself a a PR for that?

**Comment by alikon** [comment]
closing as we have a pr #39942
