### ISSUE TITLE
Undefined variable warning

### ISSUE THREAD

**Issue by chrisdavenport** [joomla/joomla-cms#39941]
### Steps to reproduce the issue

Fresh install Joomla 4.2.8.  Set error reporting to maximum.  Content -> Articles -> Add your first article.  Just below Article Text label, the following warning is shown:

Notice: Undefined property: Joomla\CMS\Object\CMSObject::$name in /var/www/joomla428/plugins/editors/tinymce/src/PluginTraits/XTDButtons.php on line 61

### Expected result

No PHP warning

### Actual result

PHP warning shown.

### System information (as much as possible)

Joomla! 4.2.8 Stable [ Uaminifu ] 16-February-2023 15:00 GMT
PHP 7.4.33

**Comment by heelc29** [comment]
Sorry, I can't replicate it (Joomla! 4.2.9-dev Development [ Uaminifu ] e3f21ebcd6fa4b4ba0c4f95409cc58d9a878ca3b | PHP 8.1.16)
![image](https://user-images.githubusercontent.com/66922325/221359971-73f33fd7-d908-4a1d-b990-e530add97a19.png)

**Comment by joomdonation** [comment]
Could not confirm, too. Maybe the warning happens because your site use a none core **editors-xtd** plugin ?

**Comment by joomdonation** [comment]
Closing this issue because both of us could not re-procedure it. @chrisdavenport Feel free to re-open the issue if you still see the issue with a fresh Joomla 4.2.8/4.2.9-dev installation. Thanks !

**Comment by Duke3D** [comment]
Hey Chris - long time!
Found this thread searching the same error message triggered when launching a New Category page in both com-content and in a TPE that both use TinyMCE for the description block. 
I isolated the issue to the plugin associated with that TPE that added a button to the editor by disabling the editor-xtd buttons one at a time.  Hope this helps someone with the same issue.
