### ISSUE TITLE
Afrikaans Language pack error

### ISSUE THREAD

**Issue by NielBuys** [joomla/joomla-cms#39945]
### Steps to reproduce the issue
1. Load the Afrikaans Language pack. 
2. In user Options set the following. "New User Account Activation -> Self" and "Send Password -> No"
3. Register a user on save there is a error "7 arguments is expected 6 is given"

### Expected result
No error

### Actual result
Error is generated 7 arguments is expected 6 is given

### System information (as much as possible)
Joomla 3
PHP 8
Linux Debian

**Comment by NielBuys** [comment]
I found the problem but I have no idea where to send the fix for the Afrikaans language pack.

The below line is the problem in file "af-ZA.com_users.ini"

Wrong line:
COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_BODY_NOPW="Hallo %s,\n\nBaie dankie vir jou registrasie op %s. Jou rekening is geskep en moet eers geaktiveer word voordat jy dit kan gebruik. Om dit te aktiveer, kliek op die volgende skakel of kopieer-plak dit in jou webblaaier:\n%s\n\nWanneer die rekening geaktiveer is, kan jy by %s inteken met die volgende gegewens:\n\nGebruikersnaam - %s\nWagwoord - %s"

Line should be changed to:
COM_USERS_EMAIL_REGISTERED_WITH_ACTIVATION_BODY_NOPW="Hallo %s,\n\nBaie dankie vir jou registrasie op %s. Jou rekening is geskep en moet eers geaktiveer word voordat jy dit kan gebruik. Om dit te aktiveer, kliek op die volgende skakel of kopieer-plak dit in jou webblaaier:\n%s\n\nWanneer die rekening geaktiveer is, kan jy by %s inteken met die volgende gegewens:\n\nGebruikersnaam - %s"

**Comment by brianteeman** [comment]
@tecpromotion

**Comment by tecpromotion** [comment]
Hi @NielBuys 
Unfortunately, no current language pack has been created for Joomla 3.10.x. The last one was created and uploaded for version 3.9.16.
https://downloads.joomla.org/language-packs/translations-joomla3/downloads/joomla3-afrikaans

Maybe you can get in touch with Gerrit and ask him?
https://downloads.joomla.org/language-packs/translations-joomla3

Alternatively, you can also compile an update and make it available.
If Gerrit is no longer able to offer this, I would be very happy to have you accepted as coordinator for the Joomla 3 language package. @Bakual and @zero-24 are the right contacts here with rights in the old Crowdin at https://crowdin.com/project/joomla-cms.

The packages for 4 are currently available at https://joomla.crowdin.com/u/projects/18/l/af and can also be looked up there if necessary.
I have included the coordinator @Llewellynvdm for the J4 language package here.
Maybe he can help too.

Greetings Stefan

**Comment by Llewellynvdm** [comment]
@NielBuys ons kan die Afrikaans vir Joomla 3.10 reg maak, praat gerus met my.

We can fix this, and we can update the language pack, you can connect with the Afrikaans translation team on Telegram at https://t.me/JAfrikaans

**Comment by brianteeman** [comment]
Can this be closed here now?

**Comment by NielBuys** [comment]
I just asked @Llewellynvdm if he and the Afrikaans Team on telegram is going to take the job. And if they is going to upload an updated Afrikaans translation for Joomla 3. I have explained to him what needs to be done.

If he answers then we can probably close this ticket. I didn't join the telegram team for now.

**Comment by Llewellynvdm** [comment]
Shall we continue this conversation in a more suitable location? We can connect on the official Joomla chat at [joom.la/chat](https://joom.la/chat), where my handle is [@llewellyn-van-der-merwe](https://joomlacommunity.cloud.mattermost.com/main/messages/@llewellyn-van-der-merwe).

Alternatively, we could use email or connect on Telegram. Please let me know your preferred method.

**Comment by NielBuys** [comment]
I got in contact with @Llewellynvdm this issue can close
