### ISSUE TITLE
Select folder in setting plgEditor Tinymce, will not be select images sub directory  for if create directory 'images' in directory 'administrator'

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#39946]
By creating the IMAGES directories in the ADMINISTRATOR directory. 
Create the TEST subdirectory in the IMAGES directory. 
Go to the settings of the Editor Tinymce plugin and select a subfolder to save images. 
We see that the list for selecting subfolders is limited to only one TEST folder. 
Thus, the list of the directory from the administrator folder is displayed in the plugin settings. But when saving image files in the materials manager, the files are still saved to the standard image folder. The presence of the IMAGES folder in the Admin folder breaks the configuration setting of the Tinymce editor plugin.

**Comment by brianteeman** [comment]
For others looking at this. It is an obscure but valid bug.

The images directory option in TinyMCE should look something like this
![image](https://user-images.githubusercontent.com/1296369/221668182-fe376f5a-5e83-43bb-a200-a34215f0623d.png)

In other words it should be displaying the /images directory and all subdirectories.

The bug occurs if you also have a folder /administrator/images

That should have no effect on the field in tiinymce but as shown below it does

![image](https://user-images.githubusercontent.com/1296369/221668638-ddc17961-ee6c-4141-b2c4-5ddc0ca0b767.png)

**Comment by joomdonation** [comment]
Thanks @korenevskiy for reporting the bug and @brianteeman for explains the issue clearer. If someone has time, change this line of code https://github.com/joomla/joomla-cms/blob/4.2-dev/plugins/editors/tinymce/src/Field/UploaddirsField.php#L51 to the below code should fix the bug:

```php
$this->directory   = JPATH_ROOT . '/' . ComponentHelper::getParams('com_media')->get('image_path');
```

**Comment by joomdonation** [comment]
I'm closing this issue because @korenevskiy made PR https://github.com/joomla/joomla-cms/pull/39962 to solve it. Please help testing. Thanks.
