### ISSUE TITLE
[4.2] or [4.3] Feature request: schedule 301 redirects

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#39956]
### Is your feature request related to a problem? Please describe.
When a menu item is scheduled to be unpublished it could then produce 404 errors.

### Describe the solution you'd like
Allow scheduling of 301 redirects so that when a menu item is unpublished the page(s) on that item are redirected elsewhere instead of to the error page.

**Comment by joomdonation** [comment]
Technical, Joomla is a menu base routing system. It replies on **published** menu items to find the matching component, execute it and returns the response. Supporting this will require loading unpublished menu items into memory for each and change how Joomla core routing system works, so it will:

- Slow down / de-performance the system
- Could cause many potential breaks

From what I see, if this is needed, this should be the job of a third party plugin or the error page of your template. It could catch the 404 error, find the matching unpublished menu item and perform the redirection. It is not something I see that could/should be implemented in Joomla! core.

**Comment by brianteeman** [comment]
In addition you can use the redirect manager (admittedly without the scheduling) to issue a 301
This should be closed for the reasons stated by @joomdonation

**Comment by joomdonation** [comment]
Closing for the reasons explained above.
