### ISSUE TITLE
Subform-repeatable javascript

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39964]
### Steps to reproduce the issue
Create a repeatable subform that contains a field that uses js

You can add this code to mod_article_categories.xml as a test

```
<field
	name="field-name"
	type="subform"
	label="Subform Field"
	multiple="true"
	min="1"
	max="10"
	>
	<form>
		<fieldset name="basic" addfieldprefix="Joomla\Component\Categories\Administrator\Field">
			<field
				name="parent"
				type="modal_category"
				label="MOD_ARTICLES_CATEGORIES_FIELD_PARENT_LABEL"
				extension="com_content"
				filter="integer"
				published=""
				select="true"
				new="true"
				edit="true"
				clear="true"
			/>
		</fieldset>
	</form>
</field>
```

### Expected result
A working repeatable field to select the category

### Actual result
Only the first occurence works. All subsequent fields do not as the modal is empty

### Additional comments
I understand that this is because the modal_category field uses javascript to populate the iframe in the body of the modal but as it does this on page load it does not work for the repeated field because it is not present on page load.

I assume that there could be some javascript that could be instantiated when a subform row is added that would populate the field as required. But I don't have a clue with js to know where to start

cc @fedik @dgrammatiko

**Comment by dgrammatiko** [comment]
Some time ago I spend some time resurrecting the pr for the modal fields https://github.com/joomla/joomla-cms/pull/39351 and asked if this was b/c or not. Didn’t get any answer so I closed it

**Comment by brianteeman** [comment]
not suprised that you got no feedback on #39351 as it contained no information about what changed and why. 

Looking at it now I still don't know if its just a refactoring or if it indeed resolves the issue I have.

Surely (to my non js dev mind) its just a case of having some js to watch if a new row is added and then do what is necessary to configure the field

**Comment by dgrammatiko** [comment]
@brianteeman you're wrong: https://github.com/joomla/joomla-cms/issues/38404#issuecomment-1339910867

**Comment by brianteeman** [comment]
and how is anyone supposed to know that? You ddidn't link to 38404 anywhere in 39351

**Comment by brianteeman** [comment]
and anyway 38404 is completely unrelated to the issue I am reporting

**Comment by dgrammatiko** [comment]
> Surely (to my non js dev mind) its just a case of having some js to watch if a new row is added and then do what is necessary to configure the field

Not really, the fields with a modal need to be client side rendered and not prerendered from the php side. Me an Fedik investigated on the possible solutions: 
- Discussion: https://github.com/joomla/joomla-cms/discussions/32473
- RFC: https://github.com/joomla/joomla-cms/pull/39344

> and how is anyone supposed to know that? You ddidn't link to 38404 anywhere in 39351

I wasn't expecting `anyone` to participate on that PR, only the people I mentioned in the issue

> and anyway 38404 is completely unrelated to the issue I am reporting

It's the same issue and it's occurring almost in every field that has a modal...

**Comment by brianteeman** [comment]
> > and anyway 38404 is completely unrelated to the issue I am reporting

> It's the same issue and it's occurring almost in every field that has a modal...

it is not the same issue. Please re-read what I wrote and not what you think I wrote.

and the site I am testing on does NOT have mod_security enabled!

**Comment by Fedik** [comment]
As Dimitris wrote, almost any modal field will not work in subform. 

And other fields that have extra javascript logic, should be coded to work in subform as web component or with this event: https://docs.joomla.org/J4.x:ClientSideEvents#joomla:updated

**Comment by brianteeman** [comment]
and thats what I am asking for

**Comment by Fedik** [comment]
Sadly the docs page for ClientSideEvents almost inpossible to find in Google.

**Comment by brianteeman** [comment]
I still don't know what to do with that information 

> I assume that there could be some javascript that could be instantiated when a subform row is added that would populate the field as required. But I don't have a clue with js to know where to start

**Comment by Fedik** [comment]
There also some examples in https://docs.joomla.org/Subform_form_field_type
They are old for jquery and need to be updated, but the idea the same.
You basicaly need to run javascript for iniitialise when page loaded (on DOMContentLoaded) and when new row added (on joomla:updated event.)

Like here example https://github.com/joomla/joomla-cms/blob/6798f076caf679b77b527cefe15761391cd7c3fb/build/media_source/system/js/fields/select-colour.es6.js#L41-L46

**Comment by dgrammatiko** [comment]
> I still don't know what to do with that information

Check the comments from me and @Fedik on another field: https://github.com/joomla/joomla-cms/pull/35678#pullrequestreview-764170325

**Comment by brianteeman** [comment]
Thanks @fedik I will see if I can understand that.

What I don't understand why you both keep saying things like this instead of it actually being fixed. So please do not close this. Maybe someone else will have their itch scratched

**Comment by dgrammatiko** [comment]
> What I don't understand why you both keep saying things like this instead of it actually being fixed

It's not that easy and involves some sort of B/C break. For example the selecting of a category has a dynamic function (created on PHP at run time) passed in the URL: https://github.com/joomla/joomla-cms/blob/6798f076caf679b77b527cefe15761391cd7c3fb/administrator/components/com_categories/src/Field/Modal/CategoryField.php#L115

This is wrong on every conceivable way but fixing it involves some level of B/C break. These were the kind of solutions we were looking at, both on the discussion and the RFC. Also, whenever a b/c break is required, people get extremely impolite on their responses, so that's also not very motivating to work on such issues.

**Comment by Fedik** [comment]
To fix all that in proper way, need to rewrite a looooooot of our js with some b/c break, and I not really in mood of doing it :smile:

**Comment by brianteeman** [comment]
FWIW I just tested #39344 and while (as you state) it is not production ready it does successfully resolve the issue I am reporting here

**Comment by Fedik** [comment]
This is fixed with:
- https://github.com/joomla/joomla-cms/pull/42293

Also see other linked PR in https://github.com/joomla/joomla-cms/issues/32663#issuecomment-1803933390

If some specific field is broken, then better open a new issue for that field.
