### ISSUE TITLE
[4.2] WebClient.php deprecated elements on PHP8.1

### ISSUE THREAD

**Issue by somerandomuserim** [joomla/joomla-cms#39960]
### Steps to reproduce the issue
webclient.php:
---(stripos($userAgent,
+++(stripos((string) $userAgent,

### System information (as much as possible)
PHP 8.1

### Additional comments
Deprecated lines 303, 308, 313, 318, 323, 328, 333, 338, 343

**Comment by joomdonation** [comment]
Thanks @imperpl for reporting the issue. I reported it to Joomla framework application package repo https://github.com/joomla-framework/application/issues/114. We will try to have it fixed ASAP and hopefully, have the fix includes in Joomla 4.3.

**Comment by brianteeman** [comment]
Closing this here as the relevant issue as been created upstream

**Comment by richard67** [comment]
Please test #42937 . Thanks in advance.

**Comment by richard67** [comment]
For 5.x this issue has been fixed with PR #42945 , which will be part of the 5.1.0-beta1 coming up tomorrow.

For 4.4 it still needs to be fixed.
