### ISSUE TITLE
[4.3] Error installing extensions - Release blocker?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#39969]
### Steps to reproduce the issue
Try to upload an install any extension
Try to drag and drop to install an extension

### Expected result

No errors and both methods are successful at installing an extension

### Actual result

Upload works
drag and drop does not
![image](https://user-images.githubusercontent.com/1296369/221915883-b7f9a1d2-7039-4cdc-9ccf-eb4fb9e863a1.png)

Unexpected token 'T', "The most r"... is not valid JSON

https://user-images.githubusercontent.com/1296369/221919073-182f276f-247e-495f-b5c6-264973849578.mp4

**Comment by MacJoom** [comment]
Confirmed. Other Json Error 
JSON.parse: unexpected character at line 1 column 1 of the JSON data

**Comment by wilsonge** [comment]
csrf token doesn't match. Assuming https://github.com/joomla/joomla-cms/pull/39580 isn't handling the relative url stuff

**Comment by wilsonge** [comment]
Patch https://github.com/joomla/joomla-cms/pull/39970 but I suspect reverting the original pr might be a better fix??

**Comment by brianteeman** [comment]
#39970 didnt fix anything :(
