### ISSUE TITLE
Permissions: If no items inside, then do not display System menu item

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#39972]
I created a new user group and set up limited permissions. 
There are no any available core extensions which a user has access to:
 
<img width="954" alt="Снимок экрана 2023-03-01 в 16 14 27" src="https://user-images.githubusercontent.com/3432048/222149944-9e7c394e-372f-4bd5-9cba-024470ba7875.png">

My idea is to hide System menu item if there are no items which the user has access to.

Joomla 4.2.8

P.S. If there is a rule somewhere which limits the access, please write it here and close this issue

**Comment by brianteeman** [comment]
In global configuration set the permission for that group to denied for "access administration interface" 

![image](https://user-images.githubusercontent.com/1296369/222222819-26f56d38-e289-4c5c-87ab-5c09854935ac.png)

**Comment by Sulpher** [comment]
> In global configuration set the permission for that group to denied for "access administration interface" and then set it to be allowed per component. That is what the default manager group does
> 
> ![image](https://user-images.githubusercontent.com/1296369/222222819-26f56d38-e289-4c5c-87ab-5c09854935ac.png)

This rule denies access to the administrator panel as it is described, and a user will get empty dashboard while we need the user to have limited access to some sections like components. 
And this is already configured - the user gets access to specific sections of the site.
All what is needed is to hide System link for such user group because of this section is empty (for this user group).

**Comment by brianteeman** [comment]
>  and then set it to be allowed per component. That is what the default manager group does

**Comment by wojtekxtx** [comment]
@Sulpher what @brianteeman is trying to tell you is that you should set `Access Administration Interface` to `Denied` and than set your created group permissions for that soecific component.

**Comment by Quy** [comment]
Closing due to no response that you have your answer.

**Comment by Sulpher** [comment]
I am sorry this subject was kept non-answered for a long period of time. 
Well, I returned back to this task and still cannot resolve it.

Let me explain what I need.

I need to allow access to specific components only and do not display System menu item.

<img width="283" alt="Снимок экрана 2023-10-22 в 11 21 28" src="https://github.com/joomla/joomla-cms/assets/3432048/69e8a482-e0a7-4c44-8ee0-8c932e27ac58">

What I do:
1. Go to System > Global Settings > Options. Choose the the right user group and set **Access Administration Interface**  to **Not Allowed**:
<img width="1516" alt="Снимок экрана 2023-10-22 в 11 23 55" src="https://github.com/joomla/joomla-cms/assets/3432048/7e05848c-d606-4b22-9fa3-e69003c12684">

Then I go to any component, let it be Banners and set **Access Administration Interface**  to **Allowed:. but the parameter from Global Options has higher priority and overrides the value in component settings:
<img width="1523" alt="Снимок экрана 2023-10-22 в 11 33 50" src="https://github.com/joomla/joomla-cms/assets/3432048/0925fb01-ccc9-4607-b6f0-630bcac54db1">

As the result, the user do not have access to components at all:
<img width="286" alt="Снимок экрана 2023-10-22 в 11 18 30" src="https://github.com/joomla/joomla-cms/assets/3432048/bdeff369-565e-449b-b180-51f4a1188bb9">

Well, it is logically.  But I have no idea how to disable access to System  in such a way. 

I will be thankful for any advice. Thanks.

**Comment by brianteeman** [comment]
![image](https://github.com/joomla/joomla-cms/assets/1296369/3bb9a917-1278-4f8f-93b0-00d38fcb7e9d)

![image](https://github.com/joomla/joomla-cms/assets/1296369/407b5db2-f57f-4312-abff-37bb7d7917a3)
