### ISSUE TITLE
Tooltip style broke the other extension behavior

### ISSUE THREAD

**Issue by ZhukDmitry** [joomla/joomla-cms#39971]
### Steps to reproduce the issue
Hi
I use Leaflet library to display Open Street Maps.
And this library has "Tooltipp object", that has attribute role="tooltip"
And in this case in default template CSS file template.min.css applied style

<code>
[role=tooltip]:not(.show){
background:#fff;
border:1px solid #6d757e;
border-radius:.25rem;
-webkit-box-shadow:0 0 .5rem rgba(0,0,0,.8);
box-shadow:0 0 .5rem rgba(0,0,0,.8);
color:#000;
display:none;
margin:.5em;max-width:100%;
padding:.5em;
right:5em;
text-align:start;
z-index:1070
}
</code>
It broke expected map behavior - not displays tooltips as map object 

### Expected result

Display tooltip as map object

### Actual result

It has display=none and other incorrect values to show correct result

### System information (as much as possible)
Joomla 4.2.8

### Additional comments

I can add link to development site to current map with incorrect behavior

**Comment by N6REJ** [comment]
The css you've shown are for when the .show class is not being used.

**Comment by ZhukDmitry** [comment]
You didn't understand
I can't change leaflet library. It creates divs

![image](https://user-images.githubusercontent.com/18059939/222144692-ebde6d18-5b80-4515-ada4-9fb4304e687e.png)

As you can see template overrides it

![image](https://user-images.githubusercontent.com/18059939/222144892-d32c38fc-1892-4222-997a-ec627f2664db.png)

**Comment by N6REJ** [comment]
please provide link where this can be checked.

**Comment by N6REJ** [comment]
Things like this belong in the forum.  It's not a core Joomla issue.

**Comment by ZhukDmitry** [comment]
Here link

https://test.zhuk.cc/j4/index.php/test-map?view=map&id=3&externalmarkerlink=0

Now I configure to show tooltip by default. And it is not shown, but you can find it as I wrote image above.

It is test page for fixing problem for hover event (show|hide tooltip on hovering), but now I configure to have tooltip shown on load.

**Comment by N6REJ** [comment]
glad you got it resolved
