### ISSUE TITLE
Joomla Frontend User Registration & Contact Form emails not working | Could not instantiate mail function 

### ISSUE THREAD

**Issue by avinashpatwari** [joomla/joomla-cms#39981]
### Steps to reproduce the issue
- Download and install Joomla_4.2.8-Stable-Full_Package.zip
- Allow User registration from admin side > user configuration
- Create Contact and assign contact to menu item

### Expected result
- When user register on site it should send an activation email (New User Account Activation = self) 
- When site user input and submit contact form it should send an email to assigned contact.

### Actual result
- Displays Could not instantiate mail function warning in both instance

### System information (as much as possible)
Host: Siteground
PHP: 7.4.33/8.0.28/8.1.16
Web Server:	Apache
Joomla: 4.2.8

### Additional comments
- When admin creates user it sends email subjected with "New User Details" to user
- When Sent Test Mail clicked it sends email

So somewhat issues on frontend codebase.

**Comment by coolcat-creations** [comment]
Does your "Test Mail" work when you test your Mail settings?

**Comment by alikon** [comment]
unable to replicate

**Comment by avinashpatwari** [comment]
> Does your "Test Mail" work when you test your Mail settings?

Yes

**Comment by avinashpatwari** [comment]
> Does your "Test Mail" work when you test your Mail settings?
The email was sent to xxxxxxx@xxxxx.com using PHP Mail. You should check that you've received the test email.
I got email as well

**Comment by avinashpatwari** [comment]
Thank you for looking in to it.
I have figured out by using SMTP as Mailer and its working fine now, sure some issues on my server to use PHP Mail as Mailer.

Considering it as solved and no codebase error.

**Comment by toivo** [comment]
It is likely that the host has restricted the email domains into which the web server can send emails when the mailer PHP Mail has been selected. Therefore the message "Could not instantiate mail function."  Both use cases described in Expected Results work all right in Joomla 4.2.8 and 4.2.9-dev. 

You could search for similar topics from the [Joomla! Forum](https://forum.joomla.org/) or create a new topic and get the answers from there.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39981">issues.joomla.org/tracker/joomla-cms/39981</a>.</sub>
