### ISSUE TITLE
An extra space when inserting an Article via the editor button

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#39988]
<img width="1192" alt="Снимок экрана 2023-03-02 в 23 05 43" src="https://user-images.githubusercontent.com/3432048/222540909-50ce64bc-6f1c-4d6f-acff-87a02e48118b.png">

Click on Article button in article edit mode and choose any article.  And see the code of inserted article:
`<a  href="index.php?option=com_content&view=article&id=314&catid=15">Creating a Multilingual site on Joomla</a>`

There is extra space <a href ... 

Joomla 4.2.8 + CodeMirror editor

**Comment by brianteeman** [comment]
confirmed with any editor

**Comment by viocassel** [comment]
Confirm

**Comment by dgrammatiko** [comment]
please test: #39989
