### ISSUE TITLE
Customization of the Metis Menu

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#39992]
Hello, we are working on the customization of the Cassiopeia template. But I can't find a way to change the little triangle that leads to the sub-menu. 
Could you please guide me in this search?

<img width="789" alt="Capture d’écran 2023-03-03 à 17 34 28" src="https://user-images.githubusercontent.com/26197929/222776078-4990a9e4-a60b-493a-ab0f-a44c01f382ee.png">

**Comment by brianteeman** [comment]
```
.dropdown-toggle::after {
  display: inline-block;
  margin-left: 0.255em;
  vertical-align: 0.255em;
  content: "";
  border-top: 0.3em solid;
  border-right: 0.3em solid transparent;
  border-bottom: 0;
  border-left: 0.3em solid transparent;
}
```

**Comment by Magnytu2** [comment]
I would like to replace it with an awesome icon font? Is this possible and how please?

https://fontawesome.com/icons/angle-down?s=solid&f=classic

**Comment by brianteeman** [comment]
please use the forum for support

**Comment by alikon** [comment]
matter for forum https://forum.joomla.org/
