### ISSUE TITLE
J4.2.x PHP 8.1 Deprecated: mb_strtolower() error

### ISSUE THREAD

**Issue by 01Kuzma** [joomla/joomla-cms#39995]
Hi,
I'm developing the website locally with some third-party components and YooTheme Builder.

The currently installed Joomla! version is "‎4.2.8" 

PHP 7.4, PHP 8.0.x work without problem. But switching to PHP 8.1 produces this error:

`Deprecated: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in C:\laragon\www\project\libraries\vendor\joomla\string\src\phputf8\mbstring\core.php on line 114`

I observed, that previously Joomla had a similar error with PHP 8 and then it was fixed

**Comment by chmst** [comment]
It is probably one of your extensions which causes this error. Could you check the call stack?

**Comment by 01Kuzma** [comment]
@chmst , thank you for your answer.
I've turned on the `debug` and set error reports to `maximum`. And only what I see is a debug bar without call stack. Am I missing something?
![image](https://user-images.githubusercontent.com/569504/222884027-a57bd7df-a47c-4a4f-abee-8a876357ad0c.png)

**Comment by chmst** [comment]
What happens if you disable DJcatalog?

**Comment by 01Kuzma** [comment]
@chmst , well, yes, if I temporary disable components on a page the error disappears.
Thank you
