### ISSUE TITLE
Incorrect News Feed Status Target

### ISSUE THREAD

**Issue by khu5h1** [joomla/joomla-cms#40001]
### What needs to be fixed
The target for News Feed  Guided Tour for the `Status` step is incorrect, so the pop-up is not targeting the correct item.

![main](https://user-images.githubusercontent.com/60094678/222903375-29b8f61f-e511-4d43-857c-0f64adffefcf.PNG)

### How would you fix it
![2](https://user-images.githubusercontent.com/60094678/222903379-484e51a5-5fd1-4f7c-9b90-fb99c06518b2.PNG)

Replace the target with the correct id/classname.

**Comment by richard67** [comment]
@khu5h1 It does not need to create an issue if you already know you will create a pull request. The pull request is enough in this case.

Closing as having a pull request. See #40000 .

**Comment by khu5h1** [comment]
@richard67 Sure will take care of this. Thanks a lot for your feedback.
