### ISSUE TITLE
[4.2] Not prefixed cookies

### ISSUE THREAD

**Issue by somerandomuserim** [joomla/joomla-cms#40005]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie

Prefixed cookies are security related.

Could be changed by hand (Host or secure).

**Session.php (line 204)**
--- $this->store->setName($name);
+++ $this->store->setName('__Host-'.$name);

### System information (as much as possible)
PHP 8.1

### Additional comments
I'm sorry if it's not the right place (if so please at least point, where it should be suggested)

**Comment by brianteeman** [comment]
As this requires the secure flag then its basically the same issue as https://github.com/joomla/joomla-cms/issues/40651 so closing this as a duplicate
