### ISSUE TITLE
Guided Tours - Component option

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40023]
### Steps to reproduce the issue
Similar to #40022 
If you try to limit the tours to specific components you get a problem as they are not context aware

For example I create the following tours for content
- create article
- create category
- create fields

If I assign them just to articles component then I see all three when I am in the article manager
![image](https://user-images.githubusercontent.com/1296369/222954693-2edb7974-97eb-4d99-bb29-6b3772465b9d.png)

But if I then chose the category tour and on completion check the available tours there are none.
![image](https://user-images.githubusercontent.com/1296369/222954773-a706fafd-0e88-427d-b285-5752faa823b7.png)

And if I try to be clever and assign the categories tour to also appear in the category component then we see the other category tours for the other components

![image](https://user-images.githubusercontent.com/1296369/222954856-ec8c09dd-024c-4936-a045-2164c6068267.png)

![image](https://user-images.githubusercontent.com/1296369/222954864-8f8f09bf-310b-4cb9-b633-f9b3276cfab6.png)

**Comment by obuisard** [comment]
It seems to me this is how it is intended to work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40023">issues.joomla.org/tracker/joomla-cms/40023</a>.</sub>

**Comment by brianteeman** [comment]
> It seems to me this is how it is intended to work.
> 

More likely it is a real world scenario that was not considered during development

**Comment by GeraintEdwards** [comment]
I would say this is related to issue #40025 - there should be an option to add a view/layout value to a tour in addition to a component.  If we did this then the strictly context specific tour could be offered.

The good news is that if the tour URL matches the current URL then the page isn't reloaded when the tour start so you would not loose your current work.  

It could be that we'd need to check POST variables in addition the GET values in the URL when deciding if to reload the page.  OR we simply pass and argument to the tour initiation script to tell if not to reload the page.

**Comment by brianteeman** [comment]
closed should be resolved with #41303
