### ISSUE TITLE
Guided Tours - Save failed error message

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40026]
### Steps to reproduce the issue
Create a NEW tour. Enter a title and url. Set the components option to blank.

### Expected behaviour
Tour is saved as both required fields have been entered

### Actual Behavior
Save fails with an error message that **extensions** cannot be blank
![image](https://user-images.githubusercontent.com/1296369/222955797-ee748237-0293-4d68-9296-7b681ec5977a.png)

This doesnt help me because
1. There is no field called extensions
2. Even if I guess that it means the component field it's confusing as now the field has a value of **all**

### Recommended behaviour
Component field is required
Error message refers to Component field not extensions

**Comment by wojtekxtx** [comment]
1. There is no such field. Create it;
2. Reword error.

**Comment by chmst** [comment]
There is such a field and the message comes from the database.

**Comment by chmst** [comment]
Please test https://github.com/joomla/joomla-cms/pull/40034
