### ISSUE TITLE
Guided Tours - duplicate or save as copy

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40024]
### Steps to reproduce the issue
See video recording
Creating seperate issue for each bug report so that they dont get lost inside a bigger report (again)

The title field of the tours is NOT a unique field yet it uses the code from elsewhere that checks for an existing tour of the same name and adds (2) etc to the title.

Not only is this not needed but it breaks the automatic translation functionality

https://user-images.githubusercontent.com/1296369/222955216-d0dec028-af66-4c2c-928b-8891fa97e58a.mp4

**Comment by obuisard** [comment]
I think we should translate the title on 'save as copy' or 'duplicate' before adding the number.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40024">issues.joomla.org/tracker/joomla-cms/40024</a>.</sub>
