### ISSUE TITLE
The Installer behaves differently if I drag a file or browse for the file.

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#40039]
### Steps to reproduce the issue

Drag a file to be uploaded
Browse for a file to be uploaded.

I can't provide the file I'm using because it is a paid for file.  But it is Engage Box 5.2.2.  I don't know if the issue occurs with other extensions.

### Expected result
The browse and drag are the same thng.

### Actual result
For some reason browse is a 403 and dragged files are a blank error message.

### System information (as much as possible)
[systeminfo-2023-03-07T12_20_10+00_00.txt](https://issues.joomla.org/uploads/1/94276d77e313857785b37e27d1b06a52.txt)

### Additional comments

https://youtu.be/4z6Eg604faY

**Comment by brianteeman** [comment]
This is a known issue see #39970

**Comment by uglyeoin** [comment]
> This might be the known issue see #39970

Seems like it could be but it seems like my install might be botched somehow too.

**Comment by joomdonation** [comment]
> Seems like it could be but it seems like my install might be botched somehow too

The said issue is for Joomla 4.3-dev. So if you are using Joomla 4.2.8, it must be a different issue.

**Comment by uglyeoin** [comment]
> I just tested with Engagebox 5.2.2 and the only difference I see is that for drag I see a progressbar when uploading and when selecting I see the animated Joomla logo. But both install successfully. I uninstalled between the two tries.
> 
> You have a slightly adjusted template, do you? Are you logged in as a super user?

Yes, super user.  I don't think we have adjusted the template.  I assume you mean admin?

**Comment by joomdonation** [comment]
@uglyeoin Look at the video, I think the 403 response causes by server blocks the request for some reasons, not something returned by Joomla. So for this, I think you should contact hosting provider support, ask them to see why the request is being blocked and get back to us with their response. If it is something causes by our code, we can fix it. If not, maybe they will add a whitelist rule to get this issue sorted for you.

**Comment by joomdonation** [comment]
Closing because this is a server issue. From @uglyeoin on Joomla user group on Facebook.

> Turns out this was caused by a false positive on the firewall at my hosts end. Problem solved

**Comment by uglyeoin** [comment]
> Closing because this is a server issue. From @uglyeoin on Joomla user group on Facebook.
> 
> > Turns out this was caused by a false positive on the firewall at my hosts end. Problem solved

But this doesn't explain why there are two different results from what I considered to be the same action @joomdonation .  Both should be a 403 or both should show a blank error message.  And a blank error message is not usually very helpful so that is also unexplained from me (the unknowledgeable end user) perspective.

**Comment by brianteeman** [comment]
No, as the file is transferred differently
