### ISSUE TITLE
Pagination results not showing on Joomla

### ISSUE THREAD

**Issue by Mercy-K2** [joomla/joomla-cms#40036]
### Steps to reproduce the issue
I have set the pagination results to "Show," but for some reason, on my site, when I click on subsequent pages (2,3,3....), I am redirected to the home page. How can I fix this?

### Expected result
Ideally, the subsequent pages should open and show the articles on that page. That doesn't happen. This is on Joomla 3.7.4

**Comment by chmst** [comment]
I am sure that this is not an error in Joomla (we have version 3.10.1). It could be an override in your template or a bug in a component.  Please post your question in the forum.joomla.org they can help you to find out what happens.

**Comment by Mercy-K2** [comment]
I cannot even post a question on the forum. There is no "New topic" button, as explained in the FAQs.

**Comment by chmst** [comment]
![grafik](https://user-images.githubusercontent.com/1035262/223225920-cc7457fc-7879-4b2b-b30e-48fcd0778827.png)
