### ISSUE TITLE
Guided Tours - Step language

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40030]
### Steps to reproduce the issue
On a multilingual site you have the ability to assign a tour to a language. However on a step you can not  change a step language to be something different to the tour langage - which makes sense. But instead of displaying a disabled field (with broken styling)  it would be better to show no language information on a step

![image](https://user-images.githubusercontent.com/1296369/222974517-1ff77254-93b2-4276-b631-ad3d9fc7aba9.png)

Creating seperate issue for each bug report so that they dont get lost inside a bigger report (again)

**Comment by MaheshGayakwad** [comment]
hey, i am not able to reproduce the issue can you please guilde me..

**Comment by MaheshGayakwad** [comment]
hey, i am not able to reproduce the issue can you please guilde me..

**Comment by wojtekxtx** [comment]
@brianteeman styling is imo correct.

Displaying it this way fits perfectly here. What you suggest will introduce *visual mess*.

**Comment by obuisard** [comment]
I think the problem is that the template removes the border of a disabled select box. Not sure if it's Bootstrap or our own making.

**Comment by brianteeman** [comment]
Why do we even display the language here

**Comment by obuisard** [comment]
When creating a tour for multiple languages and not using language keys, it is a good reminder of what the tour language is and therefore what the step language should be.

**Comment by wojtekxtx** [comment]
@brianteeman what should be dispolayed here if not language?

**Comment by brianteeman** [comment]
> I think the problem is that the template removes the border of a disabled select box. Not sure if it's Bootstrap or our own making.

Removing the border is fine - we do that on several other fields in the same circumstance. The problem is that the drop down arrow should also be removed.

**Comment by heelc29** [comment]
Will fixed by #40350
![image](https://user-images.githubusercontent.com/66922325/230775734-8cd12640-e670-4856-bdf9-131c959605c5.png)

**Comment by brianteeman** [comment]
great
