### ISSUE TITLE
[4.2] Codemirror keymaps

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40049]
### Steps to reproduce the issue
1. install Joomla in a subdirectory
2. set codemirror as the default editor
3. in the codemirror plugin set the kepmap to vim
4. create a new article

### Expected result
textarea using codemirror

### Actual result
codemirror fails to load as it cant find the path to the keymap

### Additional comments
The problem appears to lie in the js as this code

```
    if (this.options.keyMapUrl) {
      await import(`${this.host}/${this.options.keyMapUrl}`);
    }
```

results in 
`"keyMapUrl":"media\/vendor\/codemirror\/keymap\/vim.min.js"}`

instead of 
`"keyMapUrl":"MYFOLDER\/media\/vendor\/codemirror\/keymap\/vim.min.js"}`

@dgrammatiko looks like it might be the same error we have had before but the js makes no sense to me so sorry I cant fix it

**Comment by dgrammatiko** [comment]
https://github.com/joomla/joomla-cms/pull/40050
