### ISSUE TITLE
Using ${var} in strings is deprecated, use {$var} instead in libraries\vendor\voku\portable-utf8\src\voku\helper\UTF8.php

### ISSUE THREAD

**Issue by uzielweb** [joomla/joomla-cms#40047]
### Steps to reproduce the issue

First step on installation

### Expected result

Start normal

### Actual result

Warning message:
Using ${var} in strings is deprecated, use {$var} instead in libraries\vendor\voku\portable-utf8\src\voku\helper\UTF8.php

### System information (as much as possible)
PHP 8.2.3
Apache 2.4.47
MariaDB 10.8.3
Laragon for Windows
Joomla! 4.3.0 Beta 4

**Comment by infograf768** [comment]
Confirmed.
This breaks installing and running multiple aspects of J using php 8.0

**Comment by infograf768** [comment]
RELEASE BLOCKER<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40047">issues.joomla.org/tracker/joomla-cms/40047</a>.</sub>

**Comment by joomdonation** [comment]
As I understand, this merged PR https://github.com/joomla/joomla-cms/pull/39955 should fix that issue.

**Comment by infograf768** [comment]
Unhappily that merge is for 4.3...
The problem here is for 4.2.9
