### ISSUE TITLE
[4.3] Missing field in database: Joomla\CMS\Table\ContentType   alias.

### ISSUE THREAD

**Issue by hikashop-nicolas** [joomla/joomla-cms#40052]
### Steps to reproduce the issue
Install HikaShop's latest version (4.7.1) on Joomla 4.3 Beta 4

### Expected result
Sucessful installation

### Actual result
Error is displayed:
Missing field in database: Joomla\CMS\Table\ContentType   alias.
https://i.imgur.com/yRGq5wK.png

### System information (as much as possible)
Joomla 4.3 Beta 4 (any beta of 4.3 should have the issue)

### Additional comments
This issue is related to this PR: https://github.com/joomla/joomla-cms/pull/38576

**Comment by joomdonation** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/40060 . Thanks !
