### ISSUE TITLE
Changelogurl not set in #__extensions when package updated

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#40056]
### Steps to reproduce the issue
1. When you have a package installed that didn't have a changelogurl set in the manifest file and you upgrade that package with a version that does have a changelogurl set in the manifest, this changelogurl is not stored in that database.
2. when you change the changelogurl in your package and install this updated package, the changelogurl is still the old one > so not updated

currently changelogurl is only set (and thus used) on newly installed packages. The changelog button is showed, but when clicked there is not url set to get the contents from (and displays an empty popup)

### Expected result
changelogurl field in table #__extensions for packages should be updated to (new) changelogurl

### Actual result
changelogurl field in table #__extensions for packages is not updated

### Additional comments
workaround is to set it manually via a install script on updating the package.

**Comment by Ruud68** [comment]
Hi @joomdonation thanks for following up. I reported this issue here because I have customers complaining about it and now I can refer them to where the bug actually is.
For my own packages I have a workaround in place.
Reporting the issue here is the most I can do currently.

**Comment by joomdonation** [comment]
I was hoping you could make the PR, but that's OK. We will try to fix it ASAP.

**Comment by richard67** [comment]
Closing as having a pull request Please test #44564 . Thanks in advance.
