### ISSUE TITLE
Media manager: image upload fails due to wrong format.

### ISSUE THREAD

**Issue by jduerscheid** [joomla/joomla-cms#40055]
### Steps to reproduce the issue
go to standard Joomla and try to upload an *.jpeg file. The upload will fail due to the wrong file type.

### Expected result
An error message which will gave you information why the image upload fails. 

### Actual result
There is only an standard error message which doesn't help an user to fix the error
![grafik](https://user-images.githubusercontent.com/12672918/223953998-5afbe081-52aa-4dfc-88f1-8b654daa24fa.png)

### System information (as much as possible)
Joomla 4.2.8

**Comment by Quy** [comment]
Please test PR #40155.
