### ISSUE TITLE
Template diff view has wrong colors

### ISSUE THREAD

**Issue by RickR2H** [joomla/joomla-cms#40065]
### Steps to reproduce the issue
1. Create a template override
2. Go to a file of the override
3. Edit the file and save
4. The whole area is now colored and not only the changed lines. Even when no change is made, the area is colored.

Edit:
The issue is that windows uses CRLF line endings. When a file is saved in the template editor the files gets converted to LF. Because of the difference between the line endings, all lines are marked as changed.

![diff-colors](https://user-images.githubusercontent.com/5610413/224284256-378b7368-f3e2-4b95-a0bf-89571b8e83bf.gif)

### System information (as much as possible)
Windows WAMP server

### Additional comments
This is an issue create due to a discussion on #38823

**Comment by RickR2H** [comment]
@brianteeman issue is created.

**Comment by RickR2H** [comment]
@jfcherng Did some testing on Linux and the problem is not there. Is seems to be installation specific...

**Comment by jfcherng** [comment]
I doubt that the original PHP is \n line ending, which makes sense. And after saving on Windows via PHP, it's converted into \r\n or maybe the browser is too smart so it convert it into \r\n. But I am not sure why Brian can't reproduce that.

**Comment by RickR2H** [comment]
My windows machine saves the files as CRLF and when I convert the file back to LF the diff works.

**Comment by RickR2H** [comment]
I guess there is no simple solution. The only options is to compare the line endings on save and make sure they are the same for the original and the override. Forcing LF could be an option. @jfcherng do you have so an ideas how solve the issue?

**Comment by jfcherng** [comment]
I can add a new option to my diff lib so that it removes line ending chars before doing diff.

**Comment by RickR2H** [comment]
@jfcherng if you have a fix, please mention @brianteeman so he can update the library. After the update I'll make sure it gets the tests needed to get the changes in the core.

**Comment by jfcherng** [comment]
@brianteeman php-diff has released both v6.14.0 and v6.10.9, which add a new differ option `ignoreLineEnding`. Turn on that differ option should avoid this issue.

**Comment by RickR2H** [comment]
Closed as having a PR #40070 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40065">issues.joomla.org/tracker/joomla-cms/40065</a>.</sub>
