### ISSUE TITLE
Control structures with no braces are not PSR-12 compatible

### ISSUE THREAD

**Issue by aDaneInSpain** [joomla/joomla-cms#40064]
Example (code added 13 years ago):

```$saveOrder = $listOrder == 'a.ordering';```

https://github.com/joomla/joomla-cms/blob/e462044fc9a6f795c67c02c98daff5fa7d71dcba/administrator/components/com_content/tmpl/articles/default.php#L38

This is in many files, and I stumbled upon it as I find is very cryptic to read personally.

According to PSR-12 then 

```
The body of each structure MUST be enclosed by braces. This standardizes how the structures look and reduces the likelihood of introducing errors as new lines get added to the body.
```

I am just curious if this is considered acceptable in the Joomla code base?

If it should be PRS-12 compatible, then I believe that code should be written more ugly but easier to understand:

```
$saveOrder = false;
if ($listOrder == 'a.ordering' ) {
    $saveOrder = true;
}
```

**Comment by Fedik** [comment]
Hi,
If I not mistaken, it a Ternary operator.

`$saveOrder = $listOrder == 'a.ordering';` is shorter version of:
```php
$saveOrder = $listOrder == 'a.ordering' ? true : false;
```

And the quote you posted about Control structures is about to avoid stuff like:
```php
if ($foo)
  $bar = 1;
```

**Comment by aDaneInSpain** [comment]
Yeah, Seems like you are right. I had not read this part:

![image](https://user-images.githubusercontent.com/4998032/224289636-8f0da679-39bf-4639-8b5e-d918a31fa2bb.png)
