### ISSUE TITLE
[4.3] guided tours need a filter for internal urls

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#40086]
### Steps to reproduce the issue
If a user opens a new tour and enters a non internal url, for examlpe "example.com", it results in a 404. 
There should ba a validation on the url field so that non-internal urls are not accepted.

### Actual result

If this is not entered as shown here:

![screen shot 2023-03-11 at 21 44 38](https://issues.joomla.org/uploads/1/6e8cbae0bde60612b29dbe2d8a379d05.jpg)
the backend ... /administrator is broken.

### System information (as much as possible)
4.3.0-beta5-dev

**Comment by Quy** [comment]
Duplicate #40020

**Comment by richard67** [comment]
> Duplicate #40020?

Seems so.

**Comment by ChristineWk** [comment]
Found also this one now: #40021 But is then also duplicate?
Hv to close now?

**Comment by richard67** [comment]
> Found also this one now: #40021 But is then also duplicate?
> Hv to close now?

@ChristineWk Of the other 2 issues, one is for the tour and the other one for the step, so they are not duplicating each other.

Your issue here is indeed a duplicate and so should be closed.

**Comment by richard67** [comment]
Closing as duplicate report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40086">issues.joomla.org/tracker/joomla-cms/40086</a>.</sub>
