### ISSUE TITLE
In manager articles field 'tags' overflow

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#40096]
### Expected result
In the articles manager, the tags field goes beyond the dimensions of the widget column.
![image](https://user-images.githubusercontent.com/6898474/224667626-ceb6bb2e-d360-4ff3-8d08-23162c2cab56.png)

### Actual result

The size of the field must match the size of the panel.

**Comment by chmst** [comment]
Not only in articles, everywhere where the tabs field is used.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40096">issues.joomla.org/tracker/joomla-cms/40096</a>.</sub>

**Comment by brianteeman** [comment]
it is the overrides in the atum template for choicesjs which are setting the padding for the .choices__inner class

**Comment by rajputanuj31** [comment]
If I put `width: 100% !important;` in the `.choices_input class`, it works well in the browser. Do I need to make more changes or is this enough?

**Comment by korenevskiy** [comment]
> If I put `width: 100% !important;` in the `.choices_input class`, it works well in the browser. Do I need to make more changes or is this enough?

Let's stop at the fact that this is enough.

**Comment by Quy** [comment]
See https://github.com/joomla/joomla-cms/issues/27907 and https://github.com/Choices-js/Choices/issues/823

**Comment by brianteeman** [comment]
Closed as we have a pr for testing #41478
