### ISSUE TITLE
[4.4] or [5.0] Between "Delete file" and "Close file" a major visual difference would be an advantage

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#40112]
A wish/suggestion was expressed in the Joomla.de forum:

### Expected result
Between "Delete file" and "Close file" a major visual difference would be an advantage.
Or: A different symbol should be used for close or delete.

### Actual result
![screen shot 2023-03-14 at 11 00 36](https://issues.joomla.org/uploads/1/6fcf7d1c769df270b1f0de3ceedb23bf.jpg)

### System information (as much as possible)
Joomla 4.2.8 / Joomla 4.2.9-dev

### Additional comments

But shouldn't ay11 also be taken into account? (not sure about that)
Maybe someone has an idea about this?

**Comment by brianteeman** [comment]
Pretty sure this has come up before.
It is a very valid issue but unfortunately it has wider implications than just in this view.

It is obvious here because we have both buttons at the same time which I don't believe happens elsewhere. So whatever change is made (I would suggest the delete icon is the one that is changed) it needs to be checked against all other occurences

**Comment by HLeithner** [comment]
You may suggest an alternative from https://fontawesome.com/search?q=delete&o=r&m=free at the same time you may replace the floppy symbol with a more state of the are icon. maybe something for @joomla/joomla-experience-team-jxt too

**Comment by chmst** [comment]
https://github.com/joomla/joomla-cms/pull/33515 similar, but it is not the same.

**Comment by Fedik** [comment]
In theory changing this https://github.com/joomla/joomla-cms/blob/5025b5747cacbd263f7e9226f5b940055f3c4a00/administrator/components/com_templates/src/View/Template/HtmlView.php#L294
to `icon-trash` should improve the thing. And will not affect other views.

**Comment by brianteeman** [comment]
> #33515 similar, but it is not the same.

ah that was the one I was thinking of

**Comment by brianteeman** [comment]
Whatever icon is used it should be used consistently so it is not just here that it should be changed but also in other places such as 
![image](https://user-images.githubusercontent.com/1296369/225035676-5e80427b-4e44-4ee1-b703-af65a81a7749.png)

**Comment by chmst** [comment]
Thank you @drmenzelit. Please test https://github.com/joomla/joomla-cms/pull/40167
