### ISSUE TITLE
document addScript method

### ISSUE THREAD

**Issue by HubITgr** [joomla/joomla-cms#40115]
### Steps to reproduce the issue
Add any external url without .js extention (like google maps api)

### Expected result
Add external script to header as it is

### Actual result
Removes http(s) and makes the url relative to joomla

### System information (as much as possible)
Any system

**Comment by joomdonation** [comment]
Cannot confirm. I tried:

```php
$document->addScript('https://maps.google.com/maps/api/js?key=AAAA');
```

And it is rendered properly

```html
<script src="https://maps.google.com/maps/api/js?key=AAAA"></script>
```

From my experience, it could cause by a plugin on your site or your site template (tries to process/optimize JS). You will need to check and figure out it yourself.

**Comment by HubITgr** [comment]
It never crossed my mind.. It happened after the latest joomla update but it seems that it is theme related. Thank you!
