### ISSUE TITLE
Can't add media on CMS Content with Haproxy and JCE not working

### ISSUE THREAD

**Issue by Haaaaakan-Andersson** [joomla/joomla-cms#40128]
### Steps to reproduce the issue
Clean install with debian 11 or centos 7 and all libs with J4
When connecting server direct to IPadress CMS content media is working
but when traffic goes trought HAProxy (Pfsense 2.6) its not working.
Same setup is working with wordpress/drupal/phpbb but not joomla.
Also tested with bitnami/vmware joomla with same result.
JCE is not coming up at all with HAProxy.

Older j1-3 is working with same setup.

### Expected result
Should work as other CMS

**Comment by brianteeman** [comment]
I am sorry but I am not familiar with HAProxy. However I found this post which although old sounds as if it could be relevant to your issue https://www.mattbeckman.com/2008/02/26/tips-on-load-balancing-a-joomla-cluster-with-haproxy/#comments

**Comment by Hackwar** [comment]
I'm marking this as a bug, but I fear that this is outside of our power and rather and issue with pfsense or Haproxy.

**Comment by Haaaaakan-Andersson** [comment]
Thanks for answers !!
I dont think it is about pfsense or haproxy, because i have found that it strangely works 
with google chrome but not firefox latest, so it must have something to do with J4.

I think i maybe something wrong with internal relative links.

Kind regards
Håkan

**Comment by brianteeman** [comment]
The fact that it works in one browser and not another reinforces for me the comment from @Hackwar . I am closing this as there is nothing we can do to resolve this. IT can always be reopened if that is found not to be correct
