### ISSUE TITLE
RSS and ATOM - Change Title Description

### ISSUE THREAD

**Issue by Mich-es** [joomla/joomla-cms#40123]
### Steps to reproduce the issue
Activate the newsfeed for your page, look into the source code of the page and pay attention to the title of the newsfeed

### Expected result
The possibility to add a meaningful title to the feed

### Actual result
```
<link href="seite.feed?type=rss" rel="alternate" type="application/rss+xml" title="RSS 2.0">
<link href="seite.feed?type=atom" rel="alternate" type="application/atom+xml" title="Atom 1.0">
```

### System information (as much as possible)
J4.2.8
PHP 8.0.28

### Additional comments
This is of decisive importance for Google Discover and generally makes sense to implement a meaningful title. Maybe you use the category description?
https://developers.google.com/search/docs/appearance/google-discover?hl=de
Use a short, descriptive title for your RSS feed, just as you would for a website.
Recommended: Google Search Central Blog
Not recommended: RSS Feed or Central Blog

**Comment by brianteeman** [comment]
Please test #40168
