### ISSUE TITLE
Upload failed exceeds the maximum allowed size of 1024 Kb

### ISSUE THREAD

**Issue by lipatovroman** [joomla/joomla-cms#40136]
We have set in Joomla Media Manager 
Maximum Size (in MB) = 10
We have set in php.ini on server
upload_max_filesize = 10
Any 3rd-party Joomla extensions uploads files without problems.
But native Joomla Media manager always says 
Upload failed exceeds the maximum allowed size of 1024 Kb

**Comment by travisrisner** [comment]
Can you verify what your upload_max_filesize is set to in your php.ini?

**Comment by lipatovroman** [comment]
I wrote above - php.ini on server
upload_max_filesize = 10

**Comment by lipatovroman** [comment]
![2023-03-16_16-55-02](https://user-images.githubusercontent.com/6747127/225656732-25268c60-61eb-46ac-9b28-2f6736ea61eb.jpg)

**Comment by Quy** [comment]
@lipatovroman  Please advise status.

**Comment by lipatovroman** [comment]
It was JCE Editor setting.
I don't know how, but this setting works for native Joomla Media manager too.
