### ISSUE TITLE
Unable to run webinstaller

### ISSUE THREAD

**Issue by wojtekxtx** [joomla/joomla-cms#40149]
![Zrzut ekranu 2023-03-18 o 11 44 42](https://user-images.githubusercontent.com/109670049/226100748-ca4412d0-2c6f-48a8-b522-02516bf2f6b5.png)

**Comment by brianteeman** [comment]
There was a reason you were asked a series of questions. Joomla does not provide mind reading capability

**Comment by wojtekxtx** [comment]
@brianteeman yet 👍 But seriously: I dont get you. Since you are cocreator, its you who should know ins&outs of J!, not simple user/admin. Dont you think?

**Comment by brianteeman** [comment]
there are a million reasons and a million scenarios

**Comment by wojtekxtx** [comment]
@brianteeman I know, but still..........

**Comment by brianteeman** [comment]
I guess you dont want help and the maintainers should simply close this.

**Comment by dgrammatiko** [comment]
@wojtekxtx if you **can't** describe the steps you took to get this screen **nobody** would ever be able to give you any meaningful solution

**Comment by bembelimen** [comment]
Please enable the debug mode and check the error.

Then you can ask in the forum for support.
