### ISSUE TITLE
Custom extension category menu item do not show categories with custom access level

### ISSUE THREAD

**Issue by boddunan** [joomla/joomla-cms#40151]
### Steps to reproduce the issue
1. Create a custom component with Joomla categories support
2. Create site view for category with default.xml includes the category field name
ex: <field name="id" type="category" description="JGLOBAL_CHOOSE_CATEGORY_DESC" extension="com_mycomponent" label="JGLOBAL_CHOOSE_CATEGORY_LABEL" required="true" />
3. Create a nested user group such as Registerd -> Parent Group -> Child Group
4. Create a access level, say Child Access, to allow only Child group
5. Go to your custom component categories page on backend and click on new button to create a category
6. Create a category, say "Restricted Category" with the access level Child Access
7. Go to Menus -> Menu -> Add Menu
8. Select MyComponent -> Category menu item type
9. The category dropdown do not show the Restricted Category. 
10. It does not show the category even if the access level of menu item is same

### Expected result
The category Restricted Category is shown in the dropdown list of category form field.

### Actual result
"Restricted Category" does not show

### System information (as much as possible)
Joomla 3 & 4

**Comment by joomdonation** [comment]
@boddunan Can you try to re-procedure the issue with a Joomla core components which also uses Categories like com_content or com_contact ? We do not have access to your component, so it is hard for us to see the issue ourself to see what's wrong.

Also, in step 8 and step 9 which you described, normally, for core component, you will select a category from modal popup, not from a dropdown. Maybe that's the difference from how your component with core components.

**Comment by boddunan** [comment]
@joomdonation the issue is only with the category form field. Since the article category blog uses modal dialog, I do not see this issue.

**Comment by joomdonation** [comment]
Could you please attach the default.xml of your category so that we know exactly how you use that field ? Or better, use modal to allow selecting category like how we are doing it in the code.

**Comment by boddunan** [comment]
Please find it below.

`<?xml version="1.0" encoding="utf-8"?>
<metadata>
	<layout title="COM_COMMUNITYQUIZ_CATEGORY_VIEW_DEFAULT_TITLE" option="COM_COMMUNITYQUIZ_CATEGORY_VIEW_DEFAULT_OPTION">
		<help key="JHELP_MENUS_MENU_ITEM_QUIZ_CATEGORY_LIST" />
		<message>
			<![CDATA[COM_COMMUNITYQUIZ_CATEGORY_VIEW_DEFAULT_DESC]]>
		</message>
	</layout>

	
	<fields name="request">
		<fieldset name="request">
			<field name="id" type="category" description="JGLOBAL_CHOOSE_CATEGORY_DESC" extension="com_communityquiz" label="JGLOBAL_CHOOSE_CATEGORY_LABEL" required="true" />
		</fieldset>
	</fields>
</metadata>`

**Comment by joomdonation** [comment]
By reading code quickly, that form field will only show categories which match the current user access levels. I guess we should modify code to exclude access level filter for users with core.admin permission

For the time being, please make sure the account you are to create menu item has the **Child Access** access level and the he will see the category.

**Comment by joomdonation** [comment]
@boddunan PR https://github.com/joomla/joomla-cms/pull/40193 should address your issue. Could you please help testing? Thanks !
