### ISSUE TITLE
[4.3] debug bar loads twice

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#40185]
### Steps to reproduce the issue

enable debug mode

### Expected result

Only one debug bar should be present

### Actual result

Two debug bars are present
![image](https://user-images.githubusercontent.com/66922325/227579048-2308c5c3-eb30-49b4-a874-d35b285270b2.png)

### System information (as much as possible)

J4.3.0-rc1 (Atum Template)

### Additional comments

I've already found out that it has something to do with the guided tours model
https://github.com/joomla/joomla-cms/blob/280c0b8f327f3709d09228b7e7aef929fc099cd6/administrator/modules/mod_guidedtours/tmpl/default.php#L78

add the mobile status menu
https://github.com/joomla/joomla-cms/blob/280c0b8f327f3709d09228b7e7aef929fc099cd6/administrator/templates/atum/html/layouts/status.php#L30-L38

Output:
```html
<div class="header-dd-item dropdown-item" data-item="1">
    <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
    <?xml encoding="utf-8" ?>
    <html>
        <body>
            <div class="header-item-content dropdown header-tours d-none d-sm-block">
                <button class="dropdown-toggle d-flex align-items-center ps-0 py-0" data-bs-toggle="dropdown" type="button" title="Take a Tour">
                    <div class="header-item-icon">
                        <span class="icon-map-signs" aria-hidden="true"></span>
                    </div>
                    <div class="header-item-text">
                        Take a Tour        
                    </div>
                    <span class="icon-angle-down" aria-hidden="true"></span>
                </button>
                <div class="dropdown-menu dropdown-menu-end">
                    <button type="button" class="button-start-guidedtour dropdown-item" data-id="3">
                        <span class="icon-map-signs" aria-hidden="true"></span>How to create articles?
                    </button>
                    [...]
                    <button type="button" class="dropdown-item text-center" data-bs-toggle="modal" data-bs-target="#modGuidedTours-modal">
                        Show all tours
                    </button>
                </div>
            </div>
        </body>
    </html>
</div>
```

As you can see, the `div` elements contain a second `body` node which probably causes this behavior.
https://github.com/joomla/joomla-cms/blob/280c0b8f327f3709d09228b7e7aef929fc099cd6/plugins/system/debug/debug.php#L370

**Comment by obuisard** [comment]
In trying to replicate the issue, all seems alright under PHP 7.4 or 8.0.
All gets loose on PHP 8.1 and higher.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40185">issues.joomla.org/tracker/joomla-cms/40185</a>.</sub>

**Comment by heelc29** [comment]
> In trying to replicate the issue, all seems alright under PHP 7.4 or 8.0. All gets loose on PHP 8.1 and higher.

@obuisard I can also reproduce in PHP 7.2 and 8.0
![image](https://user-images.githubusercontent.com/66922325/227709445-72667a83-1eaf-442d-92ce-2451ad274e01.png)
![image](https://user-images.githubusercontent.com/66922325/227709385-6214476c-5fea-4eec-872a-289f60107a74.png)

**Comment by Fedik** [comment]
I cannot reproduce it on php 8.1
What "DOM/XML API Version" and "libxml Version" your php have? Maybe it something from that.
```
DOM/XML API Version: 20031129
libxml Version: 2.9.14
```

**Comment by Fedik** [comment]
I found, that it related to DOMDocument behavior https://www.php.net/manual/en/domdocument.savehtml.php#85165
We probably should avoid it here, somehow.

**Comment by heelc29** [comment]
> What "DOM/XML API Version" and "libxml Version" your php have? Maybe it something from that.

| dom | version |
| --- | --- |
| DOM/XML API Version | 20031129 |
| libxml Version | 2.9.12 |

![image](https://user-images.githubusercontent.com/66922325/227711630-beb69c99-0c53-406d-8cb9-1a5aa8a1ea5f.png)

**Comment by Fedik** [comment]
@heelc29 Can you please try change the code to 

```php
if ($els[0]) {
  $moduleCollapsedHtml[] = $dom->saveHTML($els[0]); //$els[0]->nodeValue;
}
```

I think I found, that when element not found it export whole Document

**Comment by joomdonation** [comment]
@Fedik Yes, that seems to fix the issue. But anyone really understands what we are trying to do with this block of code https://github.com/joomla/joomla-cms/blob/4.3-dev/administrator/templates/atum/html/layouts/status.php#L30-L38 ? In case the a tag is not found, should we add module output to $moduleCollapsedHtml array, something like ?

```php
if ($els->length > 0) {
	$moduleCollapsedHtml[] = $dom->saveHTML($els[0]); //$els[0]->nodeValue;
} else {
	$moduleCollapsedHtml[] = $out;
}
```

**Comment by Fedik** [comment]
No, that will not work,
That code is extracting bootstrap toggler in this strange way, and skipping it if there none.

**Comment by joomdonation** [comment]
Yes, strange/buggy code. Seems it wants to find a tag which has `data-bs-toggle="modal"`. If found, only add a tag to $moduleCollapsedHtml, if not, add the whole module output to $moduleCollapsedHtml array, but who knows :)

Anyway, your code fixed the reported issue. So please make PR.

**Comment by brianteeman** [comment]
iirc that is for the mobile views

**Comment by heelc29** [comment]
> But anyone really understands what we are trying to do with this block of code

I think it's used for the multilangstatus module ... to not add the [$modalHTML](https://github.com/joomla/joomla-cms/blob/280c0b8f327f3709d09228b7e7aef929fc099cd6/administrator/modules/mod_multilangstatus/tmpl/default.php#L48) twice (normal and collapsed)
https://github.com/joomla/joomla-cms/blob/280c0b8f327f3709d09228b7e7aef929fc099cd6/administrator/modules/mod_multilangstatus/tmpl/default.php#L40-L48

**Comment by Fedik** [comment]
Please test #40194
