### ISSUE TITLE
[4.3 RC1] : NoMenuRules.php : undefined $this->app

### ISSUE THREAD

**Issue by conseilgouz** [joomla/joomla-cms#40182]
### Expected result
No Error

### Actual result
ERROR 0 - Call to a member function getInput() on null in ...\libraries\src\Component\Router\Rules\NomenuRules.php:82
$this->app is not initialized

### System information (as much as possible)
Joomla 4.3 RC1
PHP 8.1

### Additional comments
I found this issue with PhocaDownload extension, but, I don't think it's related to this extension.
In version 4.2.9, $this->router->app is being used instead of $this->app.

**Comment by joomdonation** [comment]
Confirm the issue and the propose code is right, too. @conseilgouz Do you want to make PR to solve this issue?

**Comment by joomdonation** [comment]
Closing as we have PR https://github.com/joomla/joomla-cms/pull/40184 .

**Comment by conseilgouz** [comment]
PR created. I just have a problem on testing instruction.

As stated, I found it using Phocadownload extension.

@joomdonation :  is code review enough ?

**Comment by joomdonation** [comment]
> @joomdonation : is code review enough ?

We need to have a way to test it using Joomla core if it is possible. No worry about testing instructions, I will provide it. Thanks for making the PR.
