### ISSUE TITLE
[4.3] Lost table ordering B/C for third-party extensions

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#40191]
### Steps to reproduce the issue
Try to order table columns using:

HTMLHelper::_('grid.sort',  'Text', 's.title', $this->orders['order_Dir'], $this->orders['order'], 'contents.display');

### Expected result

Ordering still works

### Actual result

Ordering does not work

### System information (as much as possible)

Caused by removing the onclick handler in the sort function:

$html = '<a href="#" onclick="Joomla.tableOrdering(\'' . $order . '\',\'' . $direction . '\',\'' . $task . '\'' . $form . ');return false;"'
            . ' class="hasTooltip" title="' . htmlspecialchars(Text::_('JGLOBAL_CLICK_TO_SORT_THIS_COLUMN')) . '" data-bs-placement="top">';

and replaced with:

  $html = '<a href="#" class="hasTooltip" title="' . htmlspecialchars(Text::_('JGLOBAL_CLICK_TO_SORT_THIS_COLUMN')) . '"'
            . ' data-ordering-order="' . $order . '"'
            . ' data-ordering-direction="' . $direction . '"'
            . ' data-ordering-task="' . $task . '"'
            . ' data-ordering-form="' . (isset($form) ? $form : '') . '"'
            . ' data-bs-placement="top">';

**Comment by dgrammatiko** [comment]
Is the table on the front end or the backend?

**Comment by joeforjoomla** [comment]
I mean in the backend... looks like there is no longer a JS handler to call the Joomla.tableOrdering function

**Comment by dgrammatiko** [comment]
> looks like there is no longer a JS handler to call the Joomla.tableOrdering function

That shouldn't be a problem for the backend as there is already JS code to handle that. Does your page uses searchtools?

**Comment by obuisard** [comment]
@joeforjoomla can you check if PR#40192 fixes the issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40191">issues.joomla.org/tracker/joomla-cms/40191</a>.</sub>

**Comment by joeforjoomla** [comment]
> @joeforjoomla can you check if PR#40192 fixes the issue?
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/40191](https://issues.joomla.org/tracker/joomla-cms/40191).

@obuisard yes #40192 fixes the issue. Indeed the problem was the inline handler that was removed.
@dgrammatiko also in the backend there was no JS code to handle that, once removed the inline handler.

**Comment by alikon** [comment]
closing as we have a pr #40192
