### ISSUE TITLE
[4.3] guided tours - assets table

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40199]
### Steps to reproduce the issue
1. open and save any installed tour
2. create a new tour

check the assets table

### Expected result
com_guidedtours has a parent_id of 1 (root)
com_guidedtours.tour.1 has the parent_id of the component
etc

### Actual result
all of them have the same root, breaking inheritance in the permissions of a tour 

![image](https://user-images.githubusercontent.com/1296369/227745599-51009c52-8ae3-45c2-bfb1-e6da9b8e7b33.png)

**Comment by obuisard** [comment]
Found the issue. I am writing a PR for it. The table class is missing the _getAssetParentId() to get the parent id of the component.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40208 . Thanks in advance.
