### ISSUE TITLE
[4.3] guided tours - installation sql

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40201]
When I look at the installation sql I see that for any table that has an asset_id field any records have a value for asset_id

But for guided tours the asset_id for all the tours have the same value of 0

**Comment by richard67** [comment]
> for any table that has an asset_id field any records have a value for asset_id

@brianteeman That's not really right. We have two places where we insert one or more records into a table which has a column "asset_id" and we use a zero value (or not use the column in the insert so the default of zero will be used).

- Table `#__languages`: Here we insert the one record for the default language without specifying the asset_id, so the default of zero will be used. https://github.com/joomla/joomla-cms/blob/4.3-dev/installation/sql/mysql/base.sql#L446-L447
- Table `#__menu_types`: Here we use zero as asset_id for the one record for the main site menu. https://github.com/joomla/joomla-cms/blob/4.3-dev/installation/sql/mysql/base.sql#L562-L563

That does not mean that I think it is right here for the guided tours. In fact I don't know. I just wanted to point to the places where we already do that.

**Comment by brianteeman** [comment]
@richard67 both of those are examples where there is only one record.

- Table `#__categories` https://github.com/joomla/joomla-cms/blob/b7f4ddfbc505c9862dd58c947292f6e7cdad862d/installation/sql/mysql/supports.sql#L66-L72

- Table `#__modules` https://github.com/joomla/joomla-cms/blob/b7f4ddfbc505c9862dd58c947292f6e7cdad862d/installation/sql/mysql/base.sql#L600-L636

- Table `#__workflows` https://github.com/joomla/joomla-cms/blob/b7f4ddfbc505c9862dd58c947292f6e7cdad862d/installation/sql/mysql/base.sql#L1125-L1126

- Table `#__workflow_stages` https://github.com/joomla/joomla-cms/blob/b7f4ddfbc505c9862dd58c947292f6e7cdad862d/installation/sql/mysql/base.sql#L1174-L1175

- Table `#__workflow_tramsitions` https://github.com/joomla/joomla-cms/blob/b7f4ddfbc505c9862dd58c947292f6e7cdad862d/installation/sql/mysql/base.sql#L1209-L1216

**Comment by brianteeman** [comment]
> That does not mean that I think it is right here for the guided tours. In fact I don't know. I just wanted to point to the places where we already do that.

I don't know either - just pointing it out for someone with more knowledge to decide to either fix or close

**Comment by richard67** [comment]
@brianteeman I know the other examples. Before we can decide for the right asset IDs here for the guided tours I think it needs to solve the other issue #40199 . The reason is that when we update we do not add new assets anyway, so we have to rely on the PHP doing it right and adding them to the right parent. I have too little knowledge on where that happens.

**Comment by brianteeman** [comment]
agreed that 40199 needs to be fixed first

**Comment by richard67** [comment]
@brianteeman I've pinged the maintainers in their Mattermost channel. I hope it can be clarified and fixed. With the latter I would help of course when I know how the assets shall be structured and named.

**Comment by brianteeman** [comment]
@richard67 thanks - fixing assets after a release will be very hard

**Comment by obuisard** [comment]
As far as I understand, tours are not saved into the asset table until permissions are modified. The asset id is properly set in the guidedtours table once the tour has been saved once. So, I believe this is ok, but this needs to be confirmed.

**Comment by brianteeman** [comment]
addressed elsewhere
