### ISSUE TITLE
[4.3] guided tours - delete

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40209]
### Steps to reproduce the issue
open and save a tour so that a record is created in the assets table
delete the tour

### Expected result
the record is removed from the assets table

### Actual result
the record exists and is now an orphan

**Comment by obuisard** [comment]
I could not reproduce this.
I have trashed some tours, filtered trashed tours and deleted them.
The asset table does not have those records anymore on my test sites.

**Comment by brianteeman** [comment]
My bad - I only trashed them - I did not delete them
