### ISSUE TITLE
Guided Tour: Category / Parent Category field not working

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#40211]
### Steps to reproduce the issue
All fields of type Category / Parent category (tag), etc. do not work, you can not select anything in them. Unlike, for example, fields for selecting tags. Test on several tours.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/227802924-7999d01c-f3a8-4516-baed-dcee5c5ece1b.png)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40238 . Thanks in advance.
