### ISSUE TITLE
Guided Tour: Create banner - missing fields

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#40210]
### Steps to reproduce the issue
When we go through the tutorial on how to create a banner, there are skipping fields, some of which are required.

![Screenshot_1](https://user-images.githubusercontent.com/8440661/227801607-66a86717-c0af-4aa6-8332-f917a2120c15.png)

**Comment by Kostelano** [comment]
You can try to implement it the way it was done when creating a contact. Group:

![Screenshot_1](https://user-images.githubusercontent.com/8440661/227801745-31013739-0a10-463b-86d1-32296939e0df.png)

**Comment by khu5h1** [comment]
@Kostelano Thanks a lot for testing Guided Tours and reporting the issue. I will work on this and create a PR for the same. Thanks!

**Comment by Quy** [comment]
Please test PR #40258.
