### ISSUE TITLE
Backend has an irritant ‘dialog box’ popping up at every action.

### ISSUE THREAD

**Issue by FMellink** [joomla/joomla-cms#40217]
### When I e.g. press Control Panel or any other item I get an annoying big white dialog, which after closing pops up after every action. See screenshot. However when I click away the dialog the dialog (only possible via clicking the exit cross at the top right corner; the exit cross in the red bar on the left doesn’t work), then all is green, appendix 2. I run the default Atum template for the backend and the Cassopeia template for the website. Strange is that I cannot remove the old j3 templates, although they are not selected. 

How can I fix this annoying problem![screen shot 2023-03-27 at 10 14 51](https://issues.joomla.org/uploads/1/5cf5e8dc0e63068ce3e7a6cbf8317dc3.jpg)

### Additional comments

![screen shot 2023-03-27 at 10 14 53](https://issues.joomla.org/uploads/1/efe9edc9aec47d9f8acac977d91a4d9e.png)

**Comment by chmst** [comment]
Probably this effect is caused by a javascript from your old J3 templates. Please aks this question in forum.joomla.org.
