### ISSUE TITLE
[4.2.x] Installing new language does not update #__finder_terms_common

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#40215]
### Steps to reproduce the issue
Download Joomla_4.2.10-dev-Development-Full_Package.zip from Nightly Builds.
Install Joomla 4.2.10-dev.  Select language English (United Kingdom).
The installation is completed normally.
Check the database table _finder_terms_common that it has 174 rows.
Go to System - Languages and click Install Languages.
Install Dutch (nl-NL), ignore the info "_Language pack does not match this Joomla version.  Some strings may be missing and will be displayed in English_"
The message "_success - 
Installation of the language pack was successful_" is displayed.  
Check the database table _finder_terms_common.   **(1)**
Download the German language pack from https://downloads.joomla.org/language-packs/translations-joomla4/downloads/joomla4-german/4-2-9-1
Go to System - Install - Extensions - Upload Package File.
Select the German language pack that was downloaded.
The message "_Installation of the package was successful_" is displayed.
Check the database table _finder_terms_common.  **(2)** 
### Expected result
**(1)** more than 275 rows
**(2)** more than 1266 rows
The file com_finder.commonwords.txt in the Dutch language pack has 108 words, some of them duplicated.
The file com_finder.commonwords.txt in the German language pack has 992 words.

### Actual result
**(1)** 174
**(2)** 174

### System information (as much as possible)
Joomla 4.2.10-dev of 27 March out-of-the-box
PHP 8.1.16
Wampserver 3.3.1 64-bit on Windows 11

### Additional comments
Joomla! Forum topic [common words in dutch are not blocked](https://forum.joomla.org/viewtopic.php?f=809&t=1000318 "Common words in Dutch are not blocked")

**Comment by heelc29** [comment]
@toivo Can you check this PR https://github.com/joomla/joomla-cms/pull/39188?

**Comment by toivo** [comment]
@heelc29 thank you for the tip. 
PR #39188 is already merged into Joomla 4.3.0-rc2-dev and therefore I was able to test the installation of a language from System - Language and also from Install - Extensions.
The results are a mixed bag.  Installation of Dutch does not add words into _finder_terms_common either way. 
Installing German from Install - Extensions adds the 900 odd words all right.
The option to install from System - Language is offered, therefore it should also work consistently.
The issue with the Dutch language pack should be investigated further.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40215">issues.joomla.org/tracker/joomla-cms/40215</a>.</sub>

**Comment by heelc29** [comment]
> some of them duplicated

There are no entries because of these duplicated words. There is a fix with #41468. @toivo Can you please test it.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #41468 . Thanks in advance.
