### ISSUE TITLE
[RC1] admin blocked

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40226]
### Steps to reproduce the issue
100% clean install in a brand new location using the offifial RC zip from github

### Actual result
![image](https://user-images.githubusercontent.com/1296369/228364577-51e1ee06-a245-4f71-b59c-a0fc09e5b8ce.png)

### System information (as much as possible)
win11 apache php8.,1

**Comment by brianteeman** [comment]
![image](https://user-images.githubusercontent.com/1296369/228364853-d058ccce-4de4-4983-8f78-e8e3a9a65fe0.png)

**Comment by brianteeman** [comment]
weird - cant replicate it again.

**Comment by obuisard** [comment]
I can't replicate it either Tried the same environment without issue. That's a strange one

**Comment by brianteeman** [comment]
As the file it _crashed_ on was the first of the plugins I suspect that the build of the cache file didnt complete for some reason.

**Comment by joomdonation** [comment]
Could not replicate the issue, too. I'm using win 10, apache, php 8.2.

**Comment by OctavianC** [comment]
Happened to me too - when using Windows (wamp) and then uploading the files back to a Unix server. The directory separator is different in **autoload_psr4.php**:

Windows:
```php
'Joomla\\Plugin\\Actionlog\\Joomla\\' => [JPATH_PLUGINS . '\actionlog/joomla/src'],
```

Unix:
```php
'Joomla\\Plugin\\Actionlog\\Joomla\\' => [JPATH_PLUGINS . '/actionlog/joomla/src'],
```

Notice the different slashes. When uploading to a Unix server, **\\** is not treated as a directory separator but as part of the directory's name so it's probably looking for a directory named **plugins\actionlog** hence the error.

**Comment by Hackwar** [comment]
Yes, the slashes are different, but that doesn't matter for PHP. It handles both fine.

**Comment by chmst** [comment]
Win 1, xampp, php 8.1
Cannot replicate the issue

**Comment by N6REJ** [comment]
win10 x64pro can't replicate it.

**Comment by alikon** [comment]
@brianteeman  can you close this one ? as it seems not reproducible

**Comment by brianteeman** [comment]
as two of us have reported this issue AND the file responsible for creating the autoload_psr was changed since the previous release I still see it as a problem. It obviously happens its just about working out under what cirscumstances it happens

**Comment by richard67** [comment]
> Yes, the slashes are different, but that doesn't matter for PHP. It handles both fine.

@Hackwar That's not 100% right. PHP allows to use *nix paths with a slash as directory separator anywhere, i.e. it allows to use standardized paths with slashes, like other programming languages do, e.g. Java. That means you can use paths with slashes also on Windows. But the opposite is not right, you cannot safely use Windows paths with backslashes on Linux. The paths should always use slashes.

**Comment by Fedik** [comment]
As I understood it happen when uploading files from Windows to Unix?
Well, **the cache should not be migrated**. 
No cache => No issue :wink:

**Comment by richard67** [comment]
> As I understood it happen when uploading files between Windows and Unix? Well, **the cache should not be migrated**. This also applies for /tmp files. No cache => No issue 😉

Makes sense to me. Should be documented somewhere if possible.

**Comment by Fedik** [comment]
> Should be documented somewhere if possible.

To me it is an obvious rule, everyone should follow. It not only about Joomla, but about any system

**Comment by brianteeman** [comment]
So I just came across the same thing on another site on *nix and googling and checking this tracker is showing that others are having the same problem not just with 4.3. Deleting the autoload_psr4.php cache does not help as the problem is still present in the renewed file. 

I havent worked out why but when you look in the autoload_psr4.php you will see that the first x entries for plugins are all missing.
```

	'Joomla\\Module\\Version\\Administrator\\' => [JPATH_ADMINISTRATOR . '/modules/mod_version/src'],
	'Joomla\\Module\\Whosonline\\Site\\' => [JPATH_SITE . '/modules/mod_whosonline/src'],
	'Joomla\\Module\\Wrapper\\Site\\' => [JPATH_SITE . '/modules/mod_wrapper/src'],
	'Joomla\\Plugin\\Content\\ConfirmConsent\\' => [JPATH_PLUGINS . '/content/confirmconsent/src'],
	'Joomla\\Plugin\\Editors\\CodeMirror\\' => [JPATH_PLUGINS . '/editors/codemirror/src'],
	'Joomla\\Plugin\\Editors\\TinyMCE\\' => [JPATH_PLUGINS . '/editors/tinymce/src'],


```
