### ISSUE TITLE
Asigning menu item to single article not working

### ISSUE THREAD

**Issue by maz001** [joomla/joomla-cms#40234]
### Steps to reproduce the issue

Just did fresh install Joomla 4.3 Release Candidate 1 for testing.( Used no additons and default template). Created a new article. Cretaed a new menu link to this single article. Returns 404 The requested page can't be found.

### Expected result

SIngle artilce to display

### Actual result

 Returns 404 The requested page can't be found.

### System information (as much as possible)
PHP 8

### Additional comments

All other links work. For example if I make the articles 'featured' and create a menu-item link to featured articles or to category blog or login form for example, they all work. It's only the menu item link to 'single articles' which returns error.

**Comment by drmenzelit** [comment]
Can't confirm.
Do you have URL rewriting on with .htaccess?

**Comment by maz001** [comment]
Hi
Thank you for your reply. Yes URL rewriting is on with the appropriate htaccess. I’ve also tried re uploading a fresh install as well and same result.

Sent from my iPhone

On 29 Mar 2023, at 18:31, Viviana Menzel ***@***.***> wrote:

﻿

Can't confirm.
Do you have URL rewriting on with .htaccess?

**Comment by maz001** [comment]
OK I now installed the nightly build version 4.4.0 and this is working
