### ISSUE TITLE
 Issue with new users email notifications

### ISSUE THREAD

**Issue by Dpetridou** [joomla/joomla-cms#40247]
### Steps to reproduce the issue
Email notifications to new registration users coming like below. 

Hello {NAME},

Thank you for registering at {SITENAME}. Your account is created and must be activated before you can use it.
To activate the account select the following link or copy-paste it in your browser:
{ACTIVATE} 

After activation you may login to {SITEURL} using the following username and password:

Username: {USERNAME}
Password: {PASSWORD_CLEAR}

**Comment by Quy** [comment]
Duplicate #39914
