### ISSUE TITLE
F10 is mentioned as fullscreen toggle; should be F11.

### ISSUE THREAD

**Issue by FDIN-NL** [joomla/joomla-cms#40255]
### Steps to reproduce the issue

Making an override in i.e. the template presents the codemirror as editor. Here the F10 is mentioned to switch to full screen.

### Expected result
Advise the F11 as this works in a.o. Chrome and Firefox

### Actual result
F10 is advised and does not work.

### System information (as much as possible)
Joomla 4 current version

### Additional comments
I changed my local version:

Solution:
plugins/editors/codemirror/layouts/editors/codemirror/element.php
line 32 $fskeys[]        = $params->get('fullScreen', 'F10');
changed to
line 32 $fskeys[]        = $params->get('fullScreen', 'F11');

**Comment by brianteeman** [comment]
Sorry you are mistaken about what this does.

The f11 you are referring to is a browser hotkey which makes the browser go full screen

Here the reference to f10 is a codemirror hotkey which makes codemirror take up the entire screen.

![f10](https://user-images.githubusercontent.com/1296369/228947346-c87102d0-893b-4789-8416-4ea280afca4d.gif)

**Comment by Quy** [comment]
Closing as not an issue for reason stated.

**Comment by FDIN-NL** [comment]
Thank you Brian for explaining. I tried to find any document about CODEMIRROR and FULL SCREEN annd this came up:
https://codemirror.net/5/demo/fullscreen.html
Apparently they agree with me that F11 is the way to go.
I have retried the toggle F11 and as you explained with the focus on the codemirror sub-window it will work, and with the focus on the rest of the browser-page it also works! 
With my suggested change they both work as expected.
Please reconsider.

@Quy I would appreciate to be able to close MY issue after I am satisfied with the response.

**Comment by brianteeman** [comment]
You could of course use the EXISTING settings in the Joomla settings for codemirror that let you set the function key to whatever you want - including adding a modifier

![image](https://user-images.githubusercontent.com/1296369/229073552-4c55b109-5a83-450c-99d9-178305f0a7fb.png)

**Comment by FDIN-NL** [comment]
Thank you again. There is still so much to discover in Joomla!

This is the perfect solution. I would not mind if this became the default... <html>
<body>


:smiley:
--


<br class="Apple-interchange-newline">
</body>
</html>
