### ISSUE TITLE
Copying a banner doesn't reset clicks and views

### ISSUE THREAD

**Issue by stimpsonjcat** [joomla/joomla-cms#40262]
### Steps to reproduce the issue

When you create a copy of a banner, the views and clicks of the original are copied as well. To reset the counters you have to remove the stats manually.

### Expected result

Creating a copy of a banner should create a new banner with statistics set to 0.

### Actual result

Clicks and views of the original banner are copied to the new banner, thus resulting in cumulative views and clicks, not in statistics for the copy of the banner only.

### System information (as much as possible)

Joomla 4.2.9
PHP 8.0.28

**Comment by chmst** [comment]
Please test #40307
