### ISSUE TITLE
Can't copy a banner

### ISSUE THREAD

**Issue by stimpsonjcat** [joomla/joomla-cms#40261]
### Steps to reproduce the issue

When I open de the banners component I can select an existing banner and then choose Actions > Batch. A modal window pops up with 2 drop down menus: **set client** and **Copy/Move**.
If I resort the list (i.e. by id to have the latest banner at the top) then the modal only shows the Set Client option. There's no option to copy or mode the banner. And you are required to make a choice for an other client.

### Expected result

Having a copy/move option an being abled to create a copy of the selected banner.

### Actual result

No copy/move dropdown visible.

### System information (as much as possible)

Joomla 4.2.9
PHP 8.0.28

### Additional comments
A workaround is to open the existing banner and choose **Save and copy**.

![Banners 1](https://user-images.githubusercontent.com/3033162/229083082-e38aeb7d-98ec-49e3-8e96-842585be763a.png)
![Banners 2](https://user-images.githubusercontent.com/3033162/229083073-bc0e9147-0264-4bbe-825a-4cc6defbfe44.png)

**Comment by brianteeman** [comment]
If you look in the browser console do you see any errors?

**Comment by stimpsonjcat** [comment]
No errors reported in the console.

**Comment by brianteeman** [comment]
Bug confirmed

Fix - incoming

**Comment by brianteeman** [comment]
Please test #40263

**Comment by alikon** [comment]
closing as we have a pr #40263
