### ISSUE TITLE
[4.3] Help button link urls

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#40268]
### Steps to reproduce the issue

In 4.3.0-...dev configuration.php set the minor version of $helpurl in configuration.php to 2 (hard code it). Select Content / Articles and click the Help button.

Note that this is a different problem from #39818 

### Expected result

A Help page.

### Actual result

The Joomla Docs site Home page.

### System information (as much as possible)

4.3.0-beta5-dev

### Additional comments

I can change the Help button url using the browser Developer Tools. This is what I found:

In 4.2 the button code looks like this:

```
<button class="button-help btn btn-info" type="button" onclick="Joomla.popupWindow('https:\/\/help.joomla.org\/proxy?keyref=Help42:Users&amp;lang=en', 'Help', 700, 500, 1)" title="Opens in a new window">
    <span class="icon-question" aria-hidden="true"></span>
    Help</button>
```

In 4.3 it looks like this:

```
<button class="button-help btn btn-info js-toolbar-help-btn" data-url="https:\/\/help.joomla.org\/proxy?keyref=Help42:Users&amp;lang=en" data-title="Help" data-width="700" data-height="500" data-scroll="1" type="button" title="Opens in a new window">
    <span class="icon-question" aria-hidden="true"></span>
    Help</button>
```

For the latter, the back slashes in the url need to be removed. With them removed with the browser Developer Tools the Help link works correctly.

**Comment by dgrammatiko** [comment]
Check #40270
