### ISSUE TITLE
Class prefix needs a space

### ISSUE THREAD

**Issue by sanus70** [joomla/joomla-cms#40267]
### Steps to reproduce the issue
- Create a Menu Module
- Add at "advanced" a menuclass (prefix) 

### Expected result
class name prefix appended
class="nav menu menu-module list-inline d-block myclass"

### Actual result
class name prefix appended WITHOUT space, so it will create a new name with the class name in front
class="nav menu menu-module list-inline d-blockmyclass"

### System information (as much as possible)
joomla 4.2.8

### Additional comments
Fixing takes just a minute...

**Comment by Quy** [comment]
Related #38238

**Comment by alikon** [comment]
unable to reproduce
![image](https://user-images.githubusercontent.com/181681/229158860-35b231d7-1ce6-46b5-825c-ea73c618691a.png)

![image](https://user-images.githubusercontent.com/181681/229159464-e6e7bcd4-9999-44b6-abb0-b933a2478c28.png)

**Comment by sanus70** [comment]
See: templates\tp_ice\html\mod_menu\default.php
Line 20: <ul class="nav menu menu-module list-inline d-block<?php echo $class_sfx; ?>"<?php echo $id; ?>>
                                                            ^ space missing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40267">issues.joomla.org/tracker/joomla-cms/40267</a>.</sub>

**Comment by sanus70** [comment]
Ah sorry - its a template isssue!
My fault

Please close<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40267">issues.joomla.org/tracker/joomla-cms/40267</a>.</sub>
