### ISSUE TITLE
[4.2.9] Cursor Placement on MFA Login to the Frontend

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#40273]
### Steps to reproduce the issue

- Create a user account with MFA (TOTP) active.
- Login to the frontend with this account with username and password.
- A form is displayed to enter the TOTP code.

### Expected result
The cursor should sit in the input field.

### Actual result
The cursor does not sit in the input field and must be placed there manually.
![SKYLAR_J4_MFA](https://user-images.githubusercontent.com/7933215/229216317-565ad732-f3dc-4d1f-ac7b-9a14ac803e99.jpg)

### System information (as much as possible)
Joomla 4.2.9 / PHP 8.1 / MySQL 8.0
Tested with Cassiopeia and SKYLAR_J4 (from Joomla51): Identical behavior

### Additional comments
When logging in to the backend, the cursor correctly sits in the input field
![Atum_MFA](https://user-images.githubusercontent.com/7933215/229216637-2afb6b7a-4874-4ed6-893a-a02ed59e5085.jpg)

**Comment by chmst** [comment]
Do you have the same effect when you switch your template to cassiopeia defalt view?

**Comment by dautrich** [comment]
Yes, as mentioned above under "System Information":
"Tested with Cassiopeia and SKYLAR_J4 (from Joomla51): Identical behavior"

**Comment by richard67** [comment]
I can reproduce the issue on the current 4.3-dev branch with Cassiopeia as site template.

**Comment by richard67** [comment]
It seems that this script which is loaded on the captive login page of the multi factor authentication on both badkend and frontent login does not work in the frontend: https://github.com/joomla/joomla-cms/blob/4.3-dev/build/media_source/com_users/js/two-factor-focus.es6.js .

The ID of the field for the verification code is right in both views.

But in frontend, there is a javascript error "Uncaught TypeError: document.getElementById(...) is null" in the browser console on the frontend page but not on the backend page.

The error happens here: https://github.com/joomla/joomla-cms/blob/4.3-dev/build/media_source/com_users/js/two-factor-focus.es6.js#L12

**Comment by richard67** [comment]
I have found the mistake and will provide a fix soon.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40330 . Thanks in advance.
