### ISSUE TITLE
[4.3] com_admin&view=help

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40271]
This is another release blocker - and should have been done during the beta!!

### Steps to reproduce the issue
This is about the page in the joomla admin that displays all the help pages and NOT the individual help buttons

The index on that page should be regenerated for every release otherwise changes such as the new guided tours component will not be in the index.

The index is generated using the cli script `build\helpTOC.php`

It does various things (read the code) and then generates a json file `administrator\help\en-GB\toc.json` which needs to be committed.

in 4.2 there are 89 links generated
running the script today for J4.3 only generates 38 :(

cc @obuisard @wilsonge @ceford @carlitorweb

**Comment by heelc29** [comment]
> running the script today for J4.3 only generates 38 :(

I have already added the category to some help pages. When I started there were under 10 help pages.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40377 . Thanks in advance.
