### ISSUE TITLE
[5.0] On a clean 5.0-dev branch, codemirror.xml and tinymce.xml are not up to date

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#40285]
### Steps to reproduce the issue

Check out the current 5.0-dev branch and make sure it is clean (e.g. with `git clean -d -x -f` and `git checkout .`.

Run `git status`.

Result: No changes are shown.

Check the version tags in files "plugins/editors/codemirror/codemirror.xml" and "plugins/editors/tinymce/tinymce.xml".

Result: Codemirror has 5.65.9, tinymce has 6.2.0.

Run `composer install` and `npm ci`.

Run `git status` and check the version tags in files "plugins/editors/codemirror/codemirror.xml" and "plugins/editors/tinymce/tinymce.xml".

### Expected result

Still no changes are shown.

The version tags in the XML files should be the same before and after running "npm ci".

### Actual result

Result of `git status`:
changed:       plugins/editors/codemirror/codemirror.xml
changed:       plugins/editors/tinymce/tinymce.xml

Result of version check in XML files:
Codemirror has 5.65.12, tinymce has 6.4.0.

### System information (as much as possible)

Current 5.0-dev branch.

### Additional comments

It seems the dependencies tinymce and codemirror have been updated in package.json, but the updated xml files have not been committed.

**Comment by richard67** [comment]
@brianteeman Asking you because I think you are familiar with updating the editors: Is is enough to commit the updated XML files for fixing this issue? I assume it is, but I'm not sure, maybe I'm missing something.

**Comment by brianteeman** [comment]
yes that will fix the issue

the problem is because people keep updating npm and composer without looking at the files that are changed when they commit. Not the first time :(

**Comment by richard67** [comment]
> yes that will fix the issue
> 
> the problem is because people keep updating npm and composer without looking at the files that are changed when they commit. Not the first time :(

@brianteeman Thanks for the feedback.

**Comment by richard67** [comment]
Closing as having a pull request. See #40287 .
