### ISSUE TITLE
No checksum found on the server

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#40303]
### Steps to reproduce the issue

Update a third party extension.
If the extension's update server is missing checksum data (sha256, sha384 and/or sha512), after install, a warning pops up:
**No checksum found on the server**.

This message 'scares' a lot of users and most don't understand what it means.
This should probably be 'rewritten' in a language everyone can understand, not only the developers.

### Expected result

Users understand what is going on

### Actual result

Users get confused about the message, if they are not developers

**Comment by brianteeman** [comment]
How about

This extension does not provide a checksum for validation of the integrity of the downloaded file.

**Comment by obuisard** [comment]
That's already much better.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40303">issues.joomla.org/tracker/joomla-cms/40303</a>.</sub>

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40304 . Thanks in advance.
