### ISSUE TITLE
Php error when overriding FormFactory in component

### ISSUE THREAD

**Issue by Elfangor93** [joomla/joomla-cms#40324]
## FormFactory can not be overwritten.

A php error with message `Key Joomla\CMS\Form\FormFactoryInterface is protected and can't be overwritten.` stating that FormFactoryInterface has the 'isProtected' flag in the container and can not be overwritten. 

### Steps to reproduce the issue
1. Install Joomla
2. Create a new article
3. Copy the `Joomla\CMS\Service\Provider\Form` to `Joomla\Component\Content\Administrator\Service\Provider\Form` and change the namespace of the file accordingly
4. Edit the file `/administrator/components/com_content/services/provider.php`
   - Add `use Joomla\Component\Content\Administrator\Service\Provider\Form as FormFactoryProvider;`
   - Add `$container->registerServiceProvider(new FormFactoryProvider('\\Joomla\\Component\\Content'));` after line 53
5. Open any backend form view of com_content

### Expected result

Loading the view using the custom FormFactoryProvider.

### Actual result

php error: `Key Joomla\CMS\Form\FormFactoryInterface is protected and can't be overwritten.`

### System information (as much as possible)

- Wampserver 3.2.9 on Windows 10
- Apache 2.4.46
- PHP 7.4.27
- mysql 5.7.37
- Joomla 4.2.9

**Comment by Elfangor93** [comment]
Looks like most of the ContainerRexource are protected. This leads me to the conclusion that most things can not be overridden by custom components...

![grafik](https://user-images.githubusercontent.com/39154009/229618997-a1eb3897-2461-4960-bc5c-bf38af498fd1.png)

**Comment by HermanPeeren** [comment]
Joomla's DI-container has the *odd* feature that you can register a resource as protected. That key can not be overriden anymore then (at least not without some tricks). 

I say odd, because:
* one of the main reasons to use a DI container is that one implementation of a dependency can easily be exchanged by another (for testing purposes or whatever). This is prevented by that protected flag.
* I'm not aware of such a feature being used on a large scale by other DI containers in other frameworks (but counter examples would be interesting).

Maybe we should just stop using that protected flag. It is now mainly used in the core service providers in  /libraries/src/Service/Provider. What harm do you think it could possibly do to be able to override *any* resource in the local clone of the DI container  in your own component?

**Comment by rdeutz** [comment]
@Elfangor93 Could ou explain what you are trying to achive?

**Comment by Fedik** [comment]
> I would like to have my own Form class

I had similar issue in one of my projects, I made own MVCFactory and set my FormFactory there. 
Not perfect but works.

But solving this in core, would be nice.

**Comment by Elfangor93** [comment]
Oke, I tried to analyse the current state here.

The first time `Joomla\CMS\Factory::getContainer()` is called during app runtime the method `Joomla\CMS\Factory::createContainer()` is called. This method registers all containers available under `Joomla\CMS\Service\Provider`.
All of them are set using the method `Joomla\DI\Container::share()` and all of them with the third argument to be `true` making them a protected container thenceforth. Since `Joomla\CMS\Factory::getContainer()` is normally called the first time before a component is booted they are all protected and can not be overridden by components.

![grafik](https://user-images.githubusercontent.com/39154009/230583115-d224ad50-2fbc-4a63-83d8-136787949b7f.png)

**To conclude:**
All containers registered by the providers located in `Joomla\CMS\Service\Provider` can not be overridden by components.

**My proposition:**
All important containers which may be overridden by components should not be registered with the protected flag.
In my opinion these should be
- Dispatcher
- Document
- Form
- Language
- Menu
- Router
- Toolbar

What are your opinions? Which of these containers may be overidden by components?
If you are developing components, which containers have you tried to overwrite in the past?

**Comment by laoneo** [comment]
Honestly I would allow to override all of them.

**Comment by richard67** [comment]
Closing as having a pull request. See #40388 .
