### ISSUE TITLE
Deprecated warnings in php 8.1.x for libraries/src/Access/Access.php

### ISSUE THREAD

**Issue by Attila-SWE** [joomla/joomla-cms#40329]
### Steps to reproduce the issue
PHP 8.1.17
Go to access settings for article in backend or edit article with user that does not have access to change access settings.

### Expected result
No error

### Actual result
Deprecated: strrpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /libraries/src/Access/Access.php on line 776

Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /libraries/src/Access/Access.php on line 744

**Comment by IUSAB** [comment]
Solved it. Issue was that article was "copied" from one site XXX_content to another without also copying XXX_assets information. So it was basically missing a row with rules and therefore the parameters were null. So issue was not with code.

**Comment by Attila-SWE** [comment]
Solved it. Issue was that article was "copied" from one site XXX_content to another without also copying XXX_assets information. So it was basically missing a row with rules and therefore the parameters were null. So issue was not with code.

**Comment by richard67** [comment]
@Attila-SWE Thanks for reporting back.
