### ISSUE TITLE
Joomla Custom Fields Contact 

### ISSUE THREAD

**Issue by Geoffresh** [joomla/joomla-cms#40338]
Hello Joomla Devs,

Upon updating to Joomla 4.2.9, we noticed that emails that are coming from the Joomla contact form have HTML included in the body (See screenshot).

### Steps to reproduce the issue
Create a custom field in Joomla's contact form
Complete this form and notice that the email that is generated has HTML code surrounding the custom fields.

### Expected result
Joomla Custom Fields content to be displayed without HTML code surrounding it.

### Actual result
HTML code looks to be included in body of the email. (see screenshot)

### System information (as much as possible)
Joomla 4.2.9
Using Joomla contact form with custom fields

### Additional comments
<img width="610" alt="Screenshot 2023-04-04 at 2 10 35 PM" src="https://user-images.githubusercontent.com/129969858/230117641-18964270-bce7-4b73-9d1b-bf5c63addcf7.png">

**Comment by richard67** [comment]
@Geoffresh You write about screenshots but I do not see any. Could you go to https://github.com/joomla/joomla-cms/issues/40338 and edit the description (initial post), and then upload the screenshots? Thanks in advance.

**Comment by Geoffresh** [comment]
> @Geoffresh You write about screenshots but I do not see any. Could you go to #40338 and edit the description (initial post), and then upload the screenshots? Thanks in advance.

Sorry about that! I uploaded it previously, but it looks like it didn't make it in there. I've edited the original post with the screenshot and verified that it made it in there this time.

Thank you for flagging!

**Comment by drmenzelit** [comment]
Confirmed

**Comment by brianteeman** [comment]
Related PR #40033

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40557 . Thanks in advance.

**Comment by laoneo** [comment]
Please test Just for the record, #40033 is not related.
