### ISSUE TITLE
TinyMCE removing the summary element if heading elements are used inside of it

### ISSUE THREAD

**Issue by olivdee** [joomla/joomla-cms#40342]
### Steps to reproduce the issue

Add inside an article while in scource code view the following:
`<details class="accordion-item">`
`<summary class="accordion-button collapsed"><h3>My Heading</h3></summary>`
`<p class="accordion-body">Lorem impsum...</p>`
`</details>`

### Expected result

...would be to keep all code unchanged, especially when one can use heading elements inside `<summary>` as explained her: 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/summary#summaries_as_headings

### Actual result

`<details class="accordion-item">`
`<h3>My Heading</h3>`
`<p class="accordion-body">Lorem impsum...</p>`
`</details>`

### System information (as much as possible)

J! 4.2.9
PHP 8.1.17

### Additional comments

none

**Comment by brianteeman** [comment]
Sorry but there is nothing we can do about this as it is tinymce and not joomla removing the heading. Possibly for the same reasons as the big red warning on the mdn page you linked to

**Comment by richard67** [comment]
Closing as not a Joomla issue. Feel free to report your issue here: https://github.com/tinymce/tinymce
