### ISSUE TITLE
Css not loading on joomla page

### ISSUE THREAD

**Issue by DebasisDa** [joomla/joomla-cms#40340]
### Steps to reproduce the issue
Install joomla application (4.2.6/ 3.10.11) with php 8.1

### Expected result
Joomla webpage with css.

### Actual result
Joomla webpage without css.

![Screenshot (1037)](https://user-images.githubusercontent.com/44518704/230305865-b8f89cd2-063c-4d88-a266-87a59feba8cc.png)

**Comment by brianteeman** [comment]
Please use the forums for support. This is a configuration issue

**Comment by richard67** [comment]
Closing as not a core issue but a configuartion issue.
