### ISSUE TITLE
[4.4] 'Testing Sample Data' Install is not visible on Home Dashboard

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#40347]
### Steps to reproduce the issue

Install Joomla 4.4 with git

### Expected result

Data plugin 'Sample Data - Testing'  Install is visible on Home Dashboard: Sample Data

### Actual result

Data plugin 'Sample Data - Testing' Install is NOT visible on Home Dashboard: Sample Data

![screen shot 2023-04-09 at 07 16 50](https://issues.joomla.org/uploads/1/f40a37bd9e86bb9b98819ac341654dbf.png)

### System information (as much as possible)

J4.4

### Additional comments

Installation is only possible via discover

![screen shot 2023-04-09 at 07 16 50](https://issues.joomla.org/uploads/1/1c7c42abe48312c32e4ffb29faee33ae.png)

Possible related to #40173 (testing.xml)

**Comment by richard67** [comment]
I can confirm the issue. On a clean 4.3-dev branch I get the testing sample data shown on the dashboard when having run "composer install" and "npm ci" and having made a new installation, and on a clean 4.4-dev branch I don't get it shown under the same conditions.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40348 . Thanks in advance.
