### ISSUE TITLE
[4.x] Missing category field in batch modal 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#40346]
### Steps to reproduce the issue

Found this in the banners component - this can be there since "always".

Trash one or more banners.
Then check a banner and select the batch action. 
Now the category selection is not displayed. 
 
![grafik](https://user-images.githubusercontent.com/1035262/230738968-178a546b-44d1-423e-948a-9b4e82da9bf8.png)

Changing the browser helps, the category field comes back 

### Expected result

Category field is visible. 
![grafik](https://user-images.githubusercontent.com/1035262/230743112-cc1d45fa-3ae3-4b6e-a761-53f7d5bf4793.png)

**Comment by brianteeman** [comment]
See #40263

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40263 . Thanks in advance.

**Comment by richard67** [comment]
Update: I just see the PR is already RTC so no need to test.
