### ISSUE TITLE
[4.3.0] Field not editable

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#40352]
### Steps to reproduce the issue
Create a field:
![image](https://user-images.githubusercontent.com/906604/230868852-1ec560f8-b6b8-4164-83ee-bb4a09512a6c.png)
![image](https://user-images.githubusercontent.com/906604/230869153-406839b3-ec80-4c33-8029-b86528312c58.png)

Create new article and try to edit the value:
![image](https://user-images.githubusercontent.com/906604/230869262-8c406f31-92da-448b-9b4f-4b1402181dba.png)

### Expected result
You can set the value of the field

### Actual result
No edit option. The dropdown doesn't work

### System information (as much as possible)
4.3.0-rc3-dev

### Additional comments
I think is a problem on all type of field, not only list (text field doesn't have the text editor and is readonly)

**Comment by obuisard** [comment]
Can you check what are the permissions for the field?
In particular, make sure 'Edit Custom Field Value' is allowed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40352">issues.joomla.org/tracker/joomla-cms/40352</a>.</sub>

**Comment by Razzo1987** [comment]
@obuisard My mistake! I forgot I was login a user with Administrator permissions and not Super User.
On the other hand, if I try to create a field logged with the Administrator user and give it permissions directly, it gives me an error:
![image](https://user-images.githubusercontent.com/906604/231082762-69c5d410-4e2f-40e5-8f01-d2270d88a56c.png)

It's correct?
