### ISSUE TITLE
[4.3] clear button in list view is not disabled when no "filter" is active

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#40378]
### Steps to reproduce the issue

open any list view (eg. plugins)

### Expected result

J4.2.10-dev: clear button is disabled
![image](https://user-images.githubusercontent.com/66922325/231680091-ddc9375d-f8b1-49be-ad7a-900b3670b346.png)

### Actual result

J4.3.0-rc4-dev: clear button is not disabled
![image](https://user-images.githubusercontent.com/66922325/231680184-d2e1838a-e94b-424c-bc74-ba0cadc4f960.png)

### Additional comments

This behavior is broken with #39772 @dgrammatiko by adding the if condition `mainContainer`
https://github.com/joomla/joomla-cms/blob/99fadde9a30f9356e2dcda3a61e5179f36f48b89/build/media_source/system/js/searchtools.es6.js#L373-L382

and so now evaluation for filter fields also include the ordering (which are maybe always are active)
https://github.com/joomla/joomla-cms/blob/99fadde9a30f9356e2dcda3a61e5179f36f48b89/build/media_source/system/js/searchtools.es6.js#L305-L313

**Comment by chmst** [comment]
I do not think that this is a bug. In J3 the clear button was always active and I used it also to cleat the search input field.

**Comment by brianteeman** [comment]
Sorry to disagree but it is a bug. In Joomla 4.2 the button is always disabled UNLESS a filter is selected OR a search term is used.

![dis](https://user-images.githubusercontent.com/1296369/232308854-1ab0475e-d8b8-4842-9a6f-bae9018f63d2.gif)

**Comment by chmst** [comment]
I was missing this feature from J3. But indeed the button was disabled in former J4 versions.

**Comment by brianteeman** [comment]
> I was missing this feature from J3.

it is still there (after a search)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40398 . Thanks in advance.
