### ISSUE TITLE
[4.3] 3 times Save & Close in module Save & Close dropdown

### ISSUE THREAD

**Issue by RickR2H** [joomla/joomla-cms#40379]
### Steps to reproduce the issue
In the latest 4.3 nightly build I noticed that on saving a module there is now 3 times Save & Close present in the dropdown. Just open the dropdown in a module and you can see the result.

![screen shot 2023-04-13 at 08 12 50](https://issues.joomla.org/uploads/1/4ba88aa46541f819781b40b889b2b5ab.jpg)

### Expected result
The two options in the dropdown should be Save & New and Save as Copy.

**Comment by brianteeman** [comment]
confirmed. I think I know which PR broke this. will check and submit a pr very shortly

**Comment by RickR2H** [comment]
Thanks @brianteeman I'll test when you have a patch!

**Comment by brianteeman** [comment]
It's caused by the changes in the pr from George

**Comment by joomdonation** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/40381. Thanks !
