### ISSUE TITLE
[cypress] tests\System\integration\administrator\components\com_categories\Category.cy.js

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40387]
Every time I run this test it ends with an uncaught exception
`(uncaught exception)TypeError: Cannot read properties of undefined (reading 'element')`

![image](https://user-images.githubusercontent.com/1296369/232068309-ae7cf386-77ad-45e8-975e-0c8b52be0a18.png)

**Comment by carlitorweb** [comment]
![Captura](https://user-images.githubusercontent.com/3956472/232791336-d981458f-1a83-499f-ad8b-e692aae7a8a0.PNG)

**Comment by brianteeman** [comment]
@carlitorweb happy to see its not just me

**Comment by carlitorweb** [comment]
The one I got is from tests #40404

**Comment by carlitorweb** [comment]
Let me check `Category.cy`

**Comment by laoneo** [comment]
run npm ci first, just to be sure no old assets are loaded

**Comment by carlitorweb** [comment]
@laoneo same before and after `npm ci`
![joomla-cms---Google-Chrome-1](https://user-images.githubusercontent.com/3956472/232798514-261bdbcc-2c83-47dd-b6bd-78fa577b64d5.png)

**Comment by carlitorweb** [comment]
![Captura](https://user-images.githubusercontent.com/3956472/232798853-5cf2237e-c29e-4f76-94c9-14fac675b461.PNG)

**Comment by brianteeman** [comment]
Might as well close this one
