### ISSUE TITLE
[4] Web Asset Manager loads CSS from Joomla ROOT

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#40395]
[From german forum](https://forum.joomla.de/thread/18425-joomla-4-backend-nach-upgrade-funktioniert-nur-teilweise) and I could reproduce it.

### Steps to reproduce the issue
- Upload an empty `template.min.css` to JOOMLA's ROOT.

### Expected result
- This `template.min.css` is ignored. Not loaded.

### Actual result
Frontend AND Backend formatted wrongly.

- Source code (example backend):

`<link href="/template.min.css?..." rel="stylesheet" />`

instead of

`<link href="/media/templates/administrator/atum/css/template.min.css?..." rel="stylesheet" />`

### System information (as much as possible)
- PHP 8.1 (not tested with other versions)
- J!4.2.9 (not tested with other versions)
- online LAMP server (not tested locally)

**Comment by richard67** [comment]
Confirmed. I can reproduce this issue with a new installation on clean, current 4.3-dev branch. I used the command `touch template.min.css` in a command shell in the root folder on my Linux web server to create the empty file.

**Comment by richard67** [comment]
Issue confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40395">issues.joomla.org/tracker/joomla-cms/40395</a>.</sub>

**Comment by richard67** [comment]
Additional info: It really happens only when you have the minified file `template.min.css` in the Joomla root. If you don't have that file but the unminified `template.css` in the Joomla root and enable "Debug System" in global configuration, the issue doesn't happen and the unminified file is ignored. But as soon as there is the minified file, the issue happens, also when debug is switched on.
