### ISSUE TITLE
[4.3 RC] Override changes - copy-and-paste not working correctly

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#40391]
### Steps to reproduce the issue
Firstly, it's great to see that there are now line numbers for both original and override files, but copy-and-paste doesn't work as expected.

### Expected result
Copy text from more than one line in the original to copy back into the override will copy just the code from the original file.

### Actual result
Highlight several lines and it copies the lines in both the original AND the override file and pastes both. See example from /html/com_users/registration/default.php override. The top part has been pasted and I have re-highlighted the copied text:

![image](https://user-images.githubusercontent.com/36987494/232106407-f6023f02-f762-4119-b12c-82afc8ca1d11.png)

The only way to avoid this is to copy and paste one line at a time, which is a pain if there is a block of, say, eight lines.

**Comment by brianteeman** [comment]
I can replicate this when there are multiple changed lines.

@jfcherng is this a known issue or did I miss a config setting?

**Comment by jfcherng** [comment]
If this is believe to be an issue of php-diff, can we simplify this to 

```php
$old = ???
$new = ???
```

## Screenshot of actual result

...

## Expected result

...

**Comment by jfcherng** [comment]
Oh wait. This is not related to "diff" itself. But more like an CSS or layout issue?

**Comment by brianteeman** [comment]
Just checked the upstream demo and its the same as here. Basically with the current code the side by side view will always work this way as the markup is horizontal and not vertical (see screenshot for a better explanation)

![image](https://user-images.githubusercontent.com/1296369/232341374-1e02f2c1-6778-4afc-bd42-b14b56e1c413.png)

@Scrabble96 if you go to to the template manager options you can change from side by side to inline for the display of the php-diff. Thats all I can suggest for now

**Comment by Scrabble96** [comment]
> @Scrabble96 if you go to to the template manager options you can change from side by side to inline for the display of the php-diff. Thats all I can suggest for now

Thanks. That works perfectly and makes much more sense - to me, at least. Perhaps that should be the default layout?

**Comment by brianteeman** [comment]
For everyone that prefers an inline diff there will be others that prefer side by side

**Comment by brianteeman** [comment]
Nothing to do here
