### ISSUE TITLE
[cypress] instructions

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40390]
I am getting multiple errors and I am assuming that it is partially down to my joomla installation and/or missing instructions

1. Should I be running the tests on a CLEAN joomla install or can it be on ANY joomla install
2. and then how can you run the installation test because joomla is already installed
3. all of the API tests are failing with a 401 unauthorized on a CLEAN joomla install - is there a missing setup instructiion about this?

**Comment by richard67** [comment]
Regarding 3. I think you have to provide an API token in the settings of the super user. That could be already part of the regular backend documentation or elsewhere.

**Comment by sandewt** [comment]
> all of the API tests are failing with a 401 unauthorized

The api token is hardcoded in the api.js
File: \joomla\tests\System\support\commands\api.js

Generate your own token and paste it in. And it works. But that cannot be the intention. So I guess the api code is not finished yet.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40390">issues.joomla.org/tracker/joomla-cms/40390</a>.</sub>

**Comment by sandewt** [comment]
Test instructions: https://github.com/joomla/joomla-cms/blob/4.4-dev/tests/System/README.md<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40390">issues.joomla.org/tracker/joomla-cms/40390</a>.</sub>

**Comment by brianteeman** [comment]
how does you posting the instructions help when I already said the instructions are missing information

**Comment by sandewt** [comment]
I'm trying to contribute here. Perhaps I should have indicated 'issue confirmed' better. :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40390">issues.joomla.org/tracker/joomla-cms/40390</a>.</sub>

**Comment by brianteeman** [comment]
yes - thankyou

**Comment by brianteeman** [comment]
@laoneo really appreciate your help here.

**Comment by laoneo** [comment]
1. Yes tests should always be executed on a clean Joomla.
2. It is reccomended to run the installation test first, that's what we do with drone. But actually you can also run it in between.
3. You have to set as secret `tEstValue` in the configuration.php, because the tokens for authentication are built with the secret. The installation test does that already for us.

**Comment by brianteeman** [comment]
So the instructions were indeed missing vital information - I will do an update

**Comment by brianteeman** [comment]
closed see #40407

**Comment by laoneo** [comment]
On some point we have to migrate them to the [manual](https://github.com/joomla/Manual/tree/main/docs/testing/automated/system), just didn't had time yet. I made [that document](https://github.com/joomla/joomla-cms/blob/4.4-dev/tests/System/README.md) basically for the GsoC students.
