### ISSUE TITLE
[5.0] tinymce language files

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40408]
Not commenting about the history behind this but in https://github.com/joomla/joomla-cms/tree/5.0-dev/build/media_source/vendor/tinymce/langs we have our own translations for tinymce. These are now mostly out of date in joomla 5.0 with tinymce6. 

They should be removed and we should now use the official language files directly from tinymce at https://www.tiny.cloud/get-tiny/language-packages/

**Comment by dgrammatiko** [comment]
I can update the tools to do that

**Comment by tecpromotion** [comment]
Yes please.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40418 . Thanks in advance.

**Comment by dgrammatiko** [comment]
@brianteeman could you reopen this?

https://github.com/joomla/joomla-cms/pull/40418 is wrong in the sense that the files should be cached and that should happen in the https://github.com/joomla/core-translations but that repo doesn't have anything for v5...

**Comment by brianteeman** [comment]
I  don't have access to reopen it. Perhaps @richard67 can do it

**Comment by alikon** [comment]
reopened as requested
