### ISSUE TITLE
[4.3 RC] 'joomla' has been introduced as a script class

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#40405]
### Is your feature request related to a problem? Please describe.
I would prefer not to have the word 'Joomla' appear in source code in order to try to avoid Joomla-specific hacks. I have already added ```<?php $this->setGenerator(null); ?>``` in the html just above the ```head``` tag.

Checking the head of a website with 4.3 RC installed (a updated dev site) in browser developer tools shows the following:

```
<script type="application/json" class="joomla-script-options new">{"joomla.jtext":{"MOD_FINDER_SEARCH_VALUE":"Search &hellip;"},"system.paths":{"root":"","rootFull":"https:\/\/mywebsite\/","base":"","baseFull":"https:\/\/mywebsite\/"},"csrf.token":"d5bd1b2fd4ce9969850b2db354bd1a65"}</script>
```
When I disabled the Search modules I'd added the code changed to this:

```
<script type="application/json" class="joomla-script-options new">{"joomla.jtext":{"ERROR":"Error","MESSAGE":"Message","NOTICE":"Notice","WARNING":"Warning","JCLOSE":"Close","JOK":"OK","JOPEN":"Open"},"system.paths":{"root":"","rootFull":"https:\/\/ssoj4.websiteprep.co.uk\/","base":"","baseFull":"https:\/\/ssoj4.websiteprep.co.uk\/"},"csrf.token":"d5bd1b2fd4ce9969850b2db354bd1a65"}</script>
```
### Describe the solution you'd like
Change the class names to something not mentioning Joomla and, hopefully, ```joomla.jtext``` to something else.

**Comment by brianteeman** [comment]
That is 
1. nothing new in 4.3
2. security by obscurity and is absolutely of no benefit at all

**Comment by Fedik** [comment]
Hello,
The feature since Joomla 3.6 :wink: 

Even if we rename the class, the CMS still will be very much recognisable.
I am closing the issue. The requested feature does not give us any benefits.
