### ISSUE TITLE
Presentation view or Gallery view

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#40413]
Since the beginning of Joomla I have been using all kinds of components to create a gallery: Ozio, Phoca, Joom, etc...

The functionalities of a gallery are very obvious: thumbnail, description, view categories, additional info fields, etc... and ooops, i saw a great similarity, Joomla doesn't need a gallery component, all those features are already there: category view, a main image, short and extended description (read more), custom fields.

There are only two things the article component needs to be perfect gallery: 
1 ) article full screen view 
2) and next and back buttons that transition from one article to another.
This would be enough to create galleries, presentations, slides, product catalogs, photo albums, newspapers, digital magazines.
All the code of the Category Blog view could be duplicated and only two new ones are added.

By assigning a menu button to the component we would have this wonderful option:

![Captura de pantalla 2023-04-19 084414](https://user-images.githubusercontent.com/9007607/232988881-d8e4c8c7-1e5a-42ae-baf3-501ea8837283.jpg)

The view would be like the blog format (we could choose columns, categories, etc...) the introduction of the articles would be shown, but the title or linkable image of each article would execute the article in full screen view.

**Comment by brianteeman** [comment]
This is just a template override. I did the same thing (but with a module) https://magazine.joomla.org/all-issues/november-2022/follow-up-the-joomla-out-of-the-box-challenge#submission-1-brian-teeman the exact same technique could be done with a blog override instead of a module override

**Comment by Global-Works-Agency** [comment]
This Open2logic proposal seems like a very good idea for easy development and it seems that the topic is abandoned.
Joomla brings out a lot of internal improvements in its updates, but not many attractive new features.
This proposal should be recovered.

I have seen the website you made and the behavior of the modules and it seems incredible to me.

If you already did it, why is that functionality not included in the Joomla 5 modules?
Where can you get those modules you made?
