### ISSUE TITLE
0 - Class "Joomla\Plugin\System\GuidedTours\Extension\GuidedTours" not found

### ISSUE THREAD

**Issue by thuebschmann** [joomla/joomla-cms#40411]
### Steps to reproduce the issue

Install Joomla 4.3 via cli/joomla.php core:update

### Expected result
Error
0 - Class "Joomla\Plugin\System\GuidedTours\Extension\GuidedTours" not found
# 	Function 	Location
1 	() 	JROOT/plugins/system/guidedtours/services/provider.php:42
2 	Joomla\DI\ServiceProviderInterface@anonymous/kunden/408500_09117/kunden/immotreff-chemnitz/plugins/system/guidedtours/services/provider.php:23$0->{closure}() 	JROOT/libraries/vendor/joomla/di/src/ContainerResource.php:182
3 	Joomla\DI\ContainerResource->getInstance() 	JROOT/libraries/vendor/joomla/di/src/Container.php:96
4 	Joomla\DI\Container->get() 	JROOT/libraries/src/Extension/ExtensionManagerTrait.php:177
5 	Joomla\CMS\Application\CMSApplication->loadExtension() 	JROOT/libraries/src/Extension/ExtensionManagerTrait.php:99
6 	Joomla\CMS\Application\CMSApplication->bootPlugin() 	JROOT/libraries/src/Plugin/PluginHelper.php:221
7 	Joomla\CMS\Plugin\PluginHelper::import() 	JROOT/libraries/src/Plugin/PluginHelper.php:181
8 	Joomla\CMS\Plugin\PluginHelper::importPlugin() 	JROOT/libraries/src/Application/CMSApplication.php:744
9 	Joomla\CMS\Application\CMSApplication->initialiseApp() 	JROOT/libraries/src/Application/SiteApplication.php:635
10 	Joomla\CMS\Application\SiteApplication->initialiseApp() 	JROOT/libraries/src/Application/SiteApplication.php:226
11 	Joomla\CMS\Application\SiteApplication->doExecute() 	JROOT/libraries/src/Application/CMSApplication.php:293
12 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT/includes/app.php:61
13 	require_once() 	JROOT/index.php:32 

### Actual result
Repaired joomla

### Additional comments
I need help to fix itz

**Comment by obuisard** [comment]
It's been suggested you delete administrator/cache/autoload_psr4.php manually. The file will be re-created automatically.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40411">issues.joomla.org/tracker/joomla-cms/40411</a>.</sub>

**Comment by obuisard** [comment]
Make sure the folder is writable though!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40411">issues.joomla.org/tracker/joomla-cms/40411</a>.</sub>

**Comment by thuebschmann** [comment]
thank you vari much<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40411">issues.joomla.org/tracker/joomla-cms/40411</a>.</sub>

**Comment by mikch06** [comment]
I have the same issue. Did nothing deleted myself.

But mv the file administrator/cache/autoload_psr4.php to administrator/cache/autoload_psr4.something solved the issue for me.

Page is back.

**Comment by webfeuerflo** [comment]
Have the same problem. just updated from 4.2.9 to 4.3 and get this error when switching to php8.0. deleting the file does not help. switching back to php7.4 and the site is running again

**Comment by tecpromotion** [comment]
See also https://docs.joomla.org/J4.x:Class_%22Joomla%5CPlugin%5CSystem%5CGuidedTours%5CExtension%5CGuidedTours%22_not_found

**Comment by tecpromotion** [comment]
@thuebschmann did deleting the administrator/cache/autoload_psr4.php file help?

**Comment by thuebschmann** [comment]
> @thuebschmann did deleting the administrator/cache/autoload_psr4.php file help?

yes it helps i posted  thank you 14 hours ago

**Comment by richard67** [comment]
I can reproduce the issue on new, clean installation on a clean 4.2-dev branch. When I use cli to update, the autoload_psr4.php has not changed after the update.

I don't know yet why this happens. The file should be deleted by the extract.php script here https://github.com/joomla/joomla-cms/blob/4.3-dev/administrator/components/com_joomlaupdate/extract.php#L1930-L1941 and also in the finalisation.php script here https://github.com/joomla/joomla-cms/blob/4.3-dev/administrator/components/com_joomlaupdate/finalisation.php#L74-L82 .

**Comment by brianteeman** [comment]
i can confirm this as well

**Comment by joomdonation** [comment]
@richard67 The code you are talking about is only executed when Joomla is updated using web updater. For CLI updater, that code is not executed, and that's the reason causing the error. Somehow, we will need to put that logic into [UpdateCoreCommand](https://github.com/joomla/joomla-cms/blob/4.3-dev/libraries/src/Console/UpdateCoreCommand.php)

**Comment by joomdonation** [comment]
@richard67 I will see but could not promise because I haven't had any experience with console code. If someone is faster, please go head. I would say beside delete autoload_prs4.php, we should also include this block of code, too https://github.com/joomla/joomla-cms/blob/4.3-dev/administrator/components/com_joomlaupdate/extract.php#L1948-L1959

**Comment by richard67** [comment]
> @richard67 I will see but could not promise because I haven't had any experience with console code. If someone is faster, please go head. I would say beside delete autoload_prs4.php, we should also include this block of code, too https://github.com/joomla/joomla-cms/blob/4.3-dev/administrator/components/com_joomlaupdate/extract.php#L1948-L1959

@joomdonation Also agreed. Unfortunately my time is very limited in the next two or three days, so I would be happy if you could work on it, and of course I would help if necessary.

**Comment by brianteeman** [comment]
the update log also needs to run on the cli update

checking other parts now

**Comment by Fedik** [comment]
Please test the fix #40437
