### ISSUE TITLE
4.3.0 - Out of memory in Admin panel

### ISSUE THREAD

**Issue by MarkRS-UK** [joomla/joomla-cms#40419]
After using the system menu in administrator section, with debug system on, any and all subsequent action causes an out of memory error.  Requires logging out to fix it.

### Steps to reproduce the issue

Switch on "Debug System" (Global configuration, system tab)
Save and select System from admin menu
Pick any option

### Expected result

Selection works as normal

### Actual result

Out of memory error (see attached screen shot)
Any selection after this causes this same error.

### System information (as much as possible)

Locally served site. Fedora Linux, 

### Additional comments

Turning off debug system restores correct action.

![OutOfMemory](https://user-images.githubusercontent.com/2373721/233026207-92ea4985-922c-4e60-8d16-98bfe0f789b6.png)

**Comment by carlitorweb** [comment]
I tried to reproduce it in a fresh local installation, and I could not. What `memory_limit` you have in your php ?

**Comment by toivo** [comment]
A few topics at the Joomla forum have reported that 128M is not enough to run with the option Debug System turned on.  Increase the memory to 256M as a workaround.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40419">issues.joomla.org/tracker/joomla-cms/40419</a>.</sub>

**Comment by Fedik** [comment]
When debug enabled the fix is there #39526

**Comment by MarkRS-UK** [comment]
I have 1024Mb set for my memory limit ("memory_limit" in php.ini), so I it looks to me like this **is** a bug and Fedik has it fixed but the fix hasn't made it into production yet.

Is that right?

**Comment by Fedik** [comment]
Correct

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39526 . Thanks in advance.
