### ISSUE TITLE
Tags on articles are missing the correct link 

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#40423]
### Steps to reproduce the issue
On Joomla 4.3 - Create some tags and add them to an article. Set the article / menu item to show the tags.
### Expected result
Tags should be shown on the article page with a link to the view of a listing of all items tag have the clicked tag.
### Actual result
The links on the tags all have this href: /root. Clicking on it shows a 404 page error.
### System information (as much as possible)
Joomla 4.3
PHP 8.1.17
### Additional comments
I think Joomla 4.3 had some changes to the tags routing?
I believe we did not have this issue on the previous version.

**Comment by jjnxpct** [comment]
In the layout file layouts/joomla/content/tages the URL is created with this code:

`echo Route::_(RouteHelper::getComponentTagRoute($tag->tag_id . ':' . $tag->alias, $tag->language));`

I check the variables $tag->tag_id, $tag->alias and $tag->language. I believe they were all there,

So maybe something wrong with the routehelper?

**Comment by brianteeman** [comment]
possibly a result of https://github.com/joomla/joomla-cms/pull/39114
