### ISSUE TITLE
4.3.0 - error in frontend

### ISSUE THREAD

**Issue by rbuelund** [joomla/joomla-cms#40424]
### Steps to reproduce the issue
Update 4.2.9 site to 4.3.0 - default cassiopeia template and lang switcher plugin enabled. Two languages installed

### Expected result
No problem

### Actual result
Error: setcookie(): Expects exactly 3 arguments when argument #3 ($expires_or_options) is an array

### System information (as much as possible)
PHP 8.1.17
MySQL 5.7.41

### Additional comments
When lang filter plugin is disabled the error goes away ???

**Comment by brianteeman** [comment]
Please see https://docs.joomla.org/J4.x:Error_setCookie()

You dont need to disable tha5t plugin - just change the cookie to be "sesssion" instead of "year"

**Comment by tecpromotion** [comment]
Please see also https://github.com/joomla/joomla-cms/pull/40414

**Comment by Fedik** [comment]
Please test the fix https://github.com/joomla/joomla-cms/pull/40414
