### ISSUE TITLE
Language Filter broken in 4.3

### ISSUE THREAD

**Issue by brbrbr** [joomla/joomla-cms#40427]
### Steps to reproduce the issue
Clean install of Joomla 4.3
Enable the 'Language Filter'
Cookie Lifetime to year

### result

setcookie(): Expects exactly 3 arguments when argument #3 ($expires_or_options) is an array

### Additional comments

setLanguageCookie in plugins/system/languagefilter/languagefilter.php calls the set method with an array for expire.

libraries/src/Input/Cookie.php passes the array to setcookie as 'expire_or_options' WITH the other function arguments. Should be WITHOUT.

**Comment by brbrbr** [comment]
Sorry for bothering you with this report. 

I did search on 'language filter' and 'setcookie' with no hits. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40427">issues.joomla.org/tracker/joomla-cms/40427</a>.</sub>

**Comment by richard67** [comment]
Closing as duplicate report and because there is a pull request which fixes the issue. Please test #40414 . Thanks in advance.
