### ISSUE TITLE
Smart search filters query incorrect no results (J4)

### ISSUE THREAD

**Issue by prinswebdevelopment** [joomla/joomla-cms#40434]
### Steps to reproduce the issue
- enable smart search content plugin
- add category with subcategories
- add articles with content to subcategories
- create filter en select only subcategories (not the parent category)
- add smart search module with that filter
- search on frontend and result is as aspected

- change filter and add parent category (do not unset the subcategories)
- try to search, you havo no results

### Expected result
I expect to find the articles

### Actual result
No results

### System information (as much as possible)
PHP 8.1.2
Joomla! 4.3.0

### Additional comments
The problem is in components/com_finder/src/Model/SearchModel.php:getListQuery()  row 201
// Iterate through each taxonomy group.
for ($i = 0, $c = count($groups); $i < $c; $i++) {
    $query->having('SUM(CASE WHEN t.node_id IN (' . implode(',', $groups[$i]) . ') THEN 1 ELSE 0 END) > 0');
}

This result in een AND like this:

HAVING 
SUM(CASE WHEN t.node_id IN (15) THEN 1 ELSE 0 END) > 0 
AND SUM(CASE WHEN t.node_id IN (16,17) THEN 1 ELSE 0 END) > 0
AND SUM(CASE WHEN m.term_id IN (9) THEN 1 ELSE 0 END) > 0

But I think the AND must be an OR like this:

HAVING 
(SUM(CASE WHEN t.node_id IN (15) THEN 1 ELSE 0 END) > 0 
OR SUM(CASE WHEN t.node_id IN (16,17) THEN 1 ELSE 0 END) > 0) 
AND SUM(CASE WHEN m.term_id IN (9) THEN 1 ELSE 0 END) > 0

The last AND with m.term is add in row 311 of the same file.

**Comment by pixelhexe** [comment]
Seems to be the same bug as described already here:

[https://github.com/joomla/joomla-cms/issues/38201](https://github.com/joomla/joomla-cms/issues/38201)

In my opinion the issue was set to "closed" by mistake.

**Comment by alikon** [comment]
it's not closed by mistake, but because there is a pull request https://github.com/joomla/joomla-cms/pull/39751

so if it is the same issue please close this one and test #39751

**Comment by prinswebdevelopment** [comment]
pull request #39751 solves the problem. Thanks! This one can close.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40434">issues.joomla.org/tracker/joomla-cms/40434</a>.</sub>
