### ISSUE TITLE
Joomla 4.3 without [Content – ImageLazyLoading] plugin

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#40436]
### Steps to reproduce the issue
Today I migrated my website from Joomla 3.10.11 to Joomla 4.3

### Expected result

`Content – ImageLazyLoading` plugin must be installed along with the migration to Joomla 4.3

### Actual result
`Content – ImageLazyLoading` plugin was not installed during the migration to Joomla 4.3

### System information (as much as possible)
PHP -  8.0.28 
MySQL - 8.0.31 
Joomla 3.10.11 - Joomla 4.3

### Additional comments
before upgrading to Joomla 4.3, I had [this plugin](https://extensions.joomla.org/extension/imagelazyloading/) @zero-24  installed for Joomla 3.10, but I removed it before migrating to Joomla 4.3

**Comment by brianteeman** [comment]
Sorry I dont understand why you are expecting a plugin to be installed.

**Comment by alikon** [comment]
for better understanding, what do you mean for
"I removed it before migrating 
**deleted/unpublished/unistalled**"

@universewrld

**Comment by zero-24** [comment]
Within J4 the aproache has been changed and no content plugin is required anymore: https://magazine.joomla.org/all-issues/january-2021/using-native-lazyloading-on-your-website

When you need to adjust the existing content you can install the plugin or run the component by dimitris mentiond in the blog.

**Comment by zero-24** [comment]
Correct the core does not ship with that plugin anymore.

**Comment by zero-24** [comment]
No it does not i would recommend to reduce the usage of iframes and where still used use a one time migration to with or without lazyloading as it is recommended for the image tag too.

**Comment by richard67** [comment]
Closing as expected behavior. Feel free to re-open if you think this is wrong. But as far as I can see, all questions have been clarified.
