### ISSUE TITLE
PHP 8.2.0 Joomla 4.3.0 stable : Impossible installing sample data (multilang)

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#40431]
2 languages (en-GB + fr-FR) 
All works fine when using PHP 7.4.33

Error when getting to step3

<img width="614" alt="Screenshot 2023-04-20 at 09 34 27" src="https://user-images.githubusercontent.com/869724/233293985-223e33ae-ed82-4d73-b11e-832935abccd5.png">

Hint: same error for blog (step2) when the language filter is published (multilang ON)

<img width="609" alt="Screenshot 2023-04-20 at 09 34 02" src="https://user-images.githubusercontent.com/869724/233293790-66bdc088-e637-441c-860d-ad692c313982.png">

**Comment by infograf768** [comment]
Closing as solved by https://github.com/joomla/joomla-cms/pull/40332

**Comment by wilsonge** [comment]
Good to see your still keeping interest JM! Hope is is well with you and the wife!
