### ISSUE TITLE
[4.3] Tags router changes adds itemid

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40442]
B/C Break!!

### Steps to reproduce the issue
Joomla 4.3 with sample data installed and SEF urs enabled

On the home pge click on any of the tags 

### Expected result
urls in the format domain/component/tags/tag/tagname

### Actual result
urls in the format domain/component/tags/tag/tagname?itemid=xxx

### In Joomla 4.2
urls in the format domain/component/tags/tag/tagname

### Additional comments
This is probably the result of the changes in #39114 
This is possibly related to #40423 

I have confirmed this on both clean installs and live sites. and there have been multiple reports elsewhere

**Comment by Fedik** [comment]
Please try to coment out this code, and check if it helps? https://github.com/joomla/joomla-cms/blob/853d3248f8d39c4932622b5c10288ecdd44be661/components/com_tags/src/Service/Router.php#L130-L137

**Comment by brianteeman** [comment]
@fedik that does revert the urls to the ones that I expected and had previously

HOWEVER I am not a heavy user of tags so I might be missing something

**Comment by Fedik** [comment]
Okay, I made PR, but not sure if it correct,
Please test #40448

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40448 . Thanks in advance.
