### ISSUE TITLE
Little issue in backend: mark template override as checked by clicking on icons not possible

### ISSUE THREAD

**Issue by pixelhexe** [joomla/joomla-cms#40440]
### Steps to reproduce the issue

1. Go to > system > site templates and choose your template 
2. In the tab "override files" (english translated by me, maybe not exactly the original words) try to mark an override as checked (or not checked) by clicking on the x-icon. On hovering a tooltip "mark as checked" will appear, screenshot of a german backend:

![grafik](https://user-images.githubusercontent.com/12550133/233445284-b31778c1-01c2-406e-8a63-41f1706c4adf.png)

### Expected result
The gray x-icon should change into a green hook and a success message should be shown.

### Actual result
The gray x-icon stays as it is and an error message appears ("no file selected").

![grafik](https://user-images.githubusercontent.com/12550133/233445501-b641f5ea-01ab-4015-8353-c147eb1726b8.png)

### System information (as much as possible)
J 4.2 and 4.3 tested, probably the bug is older.
PHP 8.x
Tested on local and remote systems

### Additional comments
Of course it exists this workaround: select the radio button before the template file name in the list and click on the button at the top ("check overrides") to mark as "checked" or "unchecked". But it irritates a little because clicking on the icons would be more comfortable and is the usual way in Joomla. Hopefully not a big deal for someone who knows where to adjust the code...

**Comment by brianteeman** [comment]
see https://github.com/joomla/joomla-cms/pull/40397

**Comment by pixelhexe** [comment]
Thank you, @brianteeman! So I'll close this.
