### ISSUE TITLE
joomla 4.3 makes php 8.1.18 SIGSEV at least on OpenBSD 7.3

### ISSUE THREAD

**Issue by renaudallard** [joomla/joomla-cms#40443]
### Steps to reproduce the issue

Install nginx (under OpenBSD) and make it forward to a php-fpm 8.1.18 unix socket.
Browse the joomla 4.3 website.

### Expected result

joomla site works as good as on php 8.1.17

### Actual result

[20-Apr-2023 11:45:24] WARNING: [pool hvcb] child 51588 exited on signal 11 (SIGSEGV) after 3.476756 seconds from start

### System information (as much as possible)

OpenBSD 7.3 amd64
nginx-1.22.0p0
php-8.1.18 started with fpm

**Comment by Hackwar** [comment]
Do you still have that issue? Is there any news regarding this? Without a stack trace or any additional information, we wont be able to do anyhting here.

**Comment by Hackwar** [comment]
We've been waiting a week and didn't get any further feedback. Since we also didn't get similar reports and I also can't replicate this, I'm closing this issue.
