### ISSUE TITLE
Dragging and dropping an image to a folder from Media behaves unstable

### ISSUE THREAD

**Issue by Open2logic** [joomla/joomla-cms#40441]
### Steps to reproduce the issue
In Media view, inside some folder, when you try to drag and drop an image, the function is displayed intermittently and when you drop the image it will most likely open it in the browser, instead of adding it to the folder half.

### Expected result
Being able to drag and drop an image into a folder.

### Actual result
The image is opened by the browser without being added to the folder.

### System information (as much as possible)
Chrome : Versión 112.0.5615.122 (Build oficial) (64 bits)
Joomla 4.3

### Additional comments

https://user-images.githubusercontent.com/9007607/233516279-f72a5240-fcf5-45d3-ae98-e9640acc23cd.mp4

**Comment by dgrammatiko** [comment]
I can't reproduce this with `Version 112.0.5615.137 (Official Build) (arm64)`.
Make sure that you have **disabled** all the Chrome Extensions and try again. Then you could start enabling (if there are any) extensions to figure out which one is the one that breaks the DnD...

**Comment by Open2logic** [comment]
In incognito mode and no extension installed
The image is not added, it opens in another browser tab.
Chrome
https://user-images.githubusercontent.com/9007607/233943719-66f2c8c7-5a0d-415c-aebb-e2b15d02344b.mp4

**Comment by Open2logic** [comment]
The image is not added, it opens in another browser tab.
Opera
https://user-images.githubusercontent.com/9007607/233946931-e77959d0-cad5-47c6-ae3c-cdff4af1f05d.mp4

**Comment by Open2logic** [comment]
In incognito mode and no extension installed
The image is not added, it opens in another browser tab.
Brave
https://user-images.githubusercontent.com/9007607/233947464-b631b085-a447-41bd-868b-ccda8df339a7.mp4

**Comment by brianteeman** [comment]
i cannot replicate this

**Comment by dgrammatiko** [comment]
@Open2logic please provide more info here, eg:
- OS, version?
- is your site on localhost or deployed on some domain?
- is your site served using https or not?

**Comment by brianteeman** [comment]
is it possible to get access to the site to test

**Comment by dgrammatiko** [comment]
Could you delete jce and try again?

**Comment by Open2logic** [comment]
Well, I don't know anymore, I have uninstalled all the components that I always put, Jce editor, advanced module and Akeeba Backup, the error continues when trying to drag and drop an image.

**Comment by brianteeman** [comment]
I can't see any reason to keep this open
