### ISSUE TITLE
I can't uninstall Irish

### ISSUE THREAD

**Issue by WhiteTiger-IT** [joomla/joomla-cms#40451]
### Steps to reproduce the issue
if you uninstall the Irish language not everything is uninstalled and some references remain in the filters and associations.

### System information (as much as possible)
PHP Built On	Linux ul-i-vls1 5.15.0-69-generic #76-Ubuntu SMP Fri Mar 17 17:19:29 UTC 2023 x86_64
Database Type	mysql
Database Version	10.6.12-MariaDB-0ubuntu0.22.04.1
Database Collation	utf8mb3_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	8.1.18
Web Server	nginx/1.20.2
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 4.3.0 Stable [ Bora ] 18-April-2023 16:00 GMT

### Additional comments
"Hand" solution:
After uninstalling the Irish Language Package
- Go to the screen "Languages: Content" (System => Manage -> Content Languages)
- Select the Irish language and change the status to Trashed (press the button "... Actions -> Trash to trash an item)
- Select the status Trashed (by clicking on the button Filter Options and for the option "- Show Status -" choose the value Trashed)
- Select the Irish language and press the button "Empty Trash"

**Comment by richard67** [comment]
@WhiteTiger-IT How have you uninstalled the language? Have you uninstalled the admin language and the site language separately? Or have you uninstalled a complete language package? When uninstalling a package, the content language should be deleted, but when installing just a language (site or admin) I think the content language remains.

Do you have the same problem also with other languages than Irish?

**Comment by brianteeman** [comment]
Unable to confirm

**Comment by brianteeman** [comment]
Can be closed as not reproducable and no further information provided to assist furthert
