### ISSUE TITLE
New Category error Joomla 4.3.0

### ISSUE THREAD

**Issue by AlexandervanderKemp** [joomla/joomla-cms#40456]
I’m experiencing an awkward problem that I can't find the answer to.
When creating a new Category an error message appears,
Joomla\CMS\Toolbar\Toolbar::versions(): Argument #2 ($itemId) must be of type int, null given, called in /home/vanderkemp/public_html/administrator/components/com_categories/src/View/Category/HtmlView.php on line 239

Who has a solution for this error, to eventually create a new Category?

System information 
Joomla 4.3.0 
ea-php80
SEO = no

allow_url_fopen = On
display_errors = Off
enable_dl = Off
file_uploads = On
max_execution_time = 2400
max_input_time = 60
max_input_vars = 1000
memory_limit = 2000M
post_max_size = 256M
session.gc_maxlifetime = 1440
session.save_path = "/var/cpanel/php/sessions/ea-php80"
upload_max_filesize = 252M
zlib.output_compression = Off
upload_tmp_dir = "/home/vanderkemp/public_html/tmp"

DEBUG information

Call stack
# 	Function 	Location
1 	() 	JROOT/libraries/src/Toolbar/CoreButtonsTrait.php:511

2 	Joomla\CMS\Toolbar\Toolbar->versions() 	JROOT/administrator/components/com_categories/src/View/Category/HtmlView.php:239

3 	Joomla\Component\Categories\Administrator\View\Category\HtmlView->addToolbar() 	JROOT/administrator/components/com_categories/src/View/Category/HtmlView.php:121

4 	Joomla\Component\Categories\Administrator\View\Category\HtmlView->display() 	JROOT/administrator/components/com_categories/src/Controller/DisplayController.php:111

5 	Joomla\Component\Categories\Administrator\Controller\DisplayController->display() 	JROOT/libraries/src/MVC/Controller/BaseController.php:678

6 	Joomla\CMS\MVC\Controller\BaseController->execute() 	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143

7 	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() 	JROOT/libraries/src/Component/ComponentHelper.php:361

8 	Joomla\CMS\Component\ComponentHelper::renderComponent() 	JROOT/libraries/src/Application/AdministratorApplication.php:143

9 	Joomla\CMS\Application\AdministratorApplication->dispatch() 	JROOT/libraries/src/Application/AdministratorApplication.php:186

10 	Joomla\CMS\Application\AdministratorApplication->doExecute() 	JROOT/libraries/src/Application/CMSApplication.php:293

11 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT/administrator/includes/app.php:61

12 	require_once() 	JROOT/administrator/index.php:32 

![screen shot 2023-04-22 at 18 24 12](https://issues.joomla.org/uploads/1/412a446326e2391cb24a010b6f1eb0a8.jpg)

**Comment by Fedik** [comment]
Hello,
What exactly you trying, just "push new button" or eny extra steps?

For test, please try change: https://github.com/joomla/joomla-cms/blob/c93bdfdbec16cac5e4ff1f774db29f8caab3dcd7/administrator/components/com_categories/src/View/Category/HtmlView.php#L140
to:
```php
$isNew = !empty($this->item->id);
```

**Comment by Puntje1000** [comment]
There is a big bug in the form login in Joomla 4.3. many errors. 

I have an The server returned a "500 - Whoops, looks like something went wrong." error. In php 7.4. I see the website in php 8 and more I get the error The server returned a "500 - Whoops, looks like something went wrong."

I hope the developers of joomla make a new update, so that the website just shows again, even though people can log in

With another website, I had to clear the public_html and mysql database and restore the backup, which did nothing. Not even in backend. I did not update website after  that. Also a login in php. But that bug was very big<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40456">issues.joomla.org/tracker/joomla-cms/40456</a>.</sub>

**Comment by richard67** [comment]
@Puntje1000 Your comment is not really related to this issue here.

**Comment by chmst** [comment]
@AlexandervanderKemp  In Articles, Contact and other Joomla core categories I cannot replicate this error. Are you working with an extension?

**Comment by AlexandervanderKemp** [comment]
@Fedik 
Thank you for your response, I followed up on your test.
Unfortunately, there was no improvement or a different error by our lovely Debug.
Tested this:
  $isNew      = ($this->item->id == 0); 
Change to:
  $isNew      = !empty($this->item->id);
Unfortunately, there was no improvement or a different error by our lovely Debug.
If you have any suggestions or want to see it in a live situation, no problem.

What I’m trying to do? Create a category, nevertheless, I can proceed with the single-article format.
Why I posted this, within my belief that Joomla is outstanding and versatile. Joomla is disliked by the quick and dirty limited internet sites that pop up and leave. 
I’m not excellent at this. Ask me to negotiate a business deal and I’ll be better off. 
Let me know if you have any suggestions.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40456">issues.joomla.org/tracker/joomla-cms/40456</a>.</sub>

**Comment by AlexandervanderKemp** [comment]
@chmst 
Thank you for your response, I’m directly in Categories. Not using a different extension.
Clicking + New, and the error with debug as in the picture appears.

In extensions I’ve seen that the Categorie is Locked, all normal. And choose to Refresh Cache.
This ended in a frozen page when Clicking + New in Categories.
I did a Graceful Server Reboot (WHM) of the dedicated server and back to the error message as before.

In my root where I made a test before, different database, the same Template and is in Joomla 4.2.8, I didn't update to 4.3.0, and here Clicking + New in Categories functions all fine. 

I’m open to updates and new suggestions, nevertheless, I can proceed with the single-article format.

Let me know if you have any suggestions.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40456">issues.joomla.org/tracker/joomla-cms/40456</a>.</sub>

**Comment by AlexandervanderKemp** [comment]
@richard67 
Hello Richard,

Can you please read the two comments I wrote on the matter in + New in Categories?
Perhaps you have an Idea, or solution, or can redirect the matter.

Many thanks in advance.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40456">issues.joomla.org/tracker/joomla-cms/40456</a>.</sub>

**Comment by AlexandervanderKemp** [comment]
Dear @Puntje1000 

Issues are there to be resolved, in a team as a challenge. We understand that everyone wishes to be heard. The journey is where we are living, the solution is within our journey.
It is interesting to read that one has similar issues to be solved. 

In excellence, and teamwork we reach out for solutions.

I sincerely believe that you found your best solution Puntje1000, I wish you a great day.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40456">issues.joomla.org/tracker/joomla-cms/40456</a>.</sub>

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40484 . Thanks in advance.

**Comment by stewart9643** [comment]
I have the same issue. Was there a solution that I missed?
Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40456">issues.joomla.org/tracker/joomla-cms/40456</a>.</sub>

**Comment by richard67** [comment]
@stewart9643 The pull request #40484 with the fix has been merged so it will be in the upcoming 4.3.2.
