### ISSUE TITLE
Links for tagged items changed

### ISSUE THREAD

**Issue by MacJoom** [joomla/joomla-cms#40454]
### Steps to reproduce the issue

Use a fresh install of 4.2 - install second language - install multilanguage data, install sample data
- Check the tag links a the bottom under 'Popular Tags' -> all with 'component'
- Create a menu item in a installed language (not all) type Tagged items select  two or more tags (important!)
- Check the newly created links in popular tags - 'component' is gone for the items in the newly created menu 
- Do an update to 4.3
- Check the links in popular tag. 'component' is back for all the links

### Expected result

Links remain the same

### Actual result

Links are created like if there was no menu item for the tagged items - with 'component'

### System information (as much as possible)

PHP 8.1.16 
Joomla 4.3.0 (upgraded from 4.2.9) 

### Additional comments

User tramber91 commented on PR #40448 on this problem, the PR removes the itemid but has no effect on this problem

**Comment by MacJoom** [comment]
I could not reproduce the broken links, still the links change - still not sure what happened to tamper91 in PR #40448<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40454">issues.joomla.org/tracker/joomla-cms/40454</a>.</sub>

**Comment by Fedik** [comment]
Please test this #40460

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40460 . Thanks in advance.
