### ISSUE TITLE
Updated to 4.3.0 but notifications continue

### ISSUE THREAD

**Issue by bascherz** [joomla/joomla-cms#40464]
### Problem identified
Just updated from 4.2.9 to 4.3.0. Everything looks and works fine, but I continue to receive email notifications about the update being available. Tried reinstalling the 4.3.0 core, but that had no effect.

### Open questions
Looking for ideas on how to resolve this. Don't want to proclaim bug, but something is clearly wrong. I am not a core developer.

**Comment by bascherz** [comment]
I will check with the admin. Definitely a possibility!

Thanks.
______________________________________________________
Bruce Scherzinger * ***@***.***

**Comment by richard67** [comment]
It can also come from a completely different site or domain which uses the same email address and site name so the update notifications emails look the same.

**Comment by bascherz** [comment]
That was it. Admin (a Joomla newbie) had stood-up a test site with the same name. Applied the update there and advised him to be sure to maintain it as well.
