### ISSUE TITLE
Extension Names

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40465]
```
	<name>plg_workflow_publishing</name>
	<author>Joomla! Project</author>
	<creationDate>2020-03</creationDate>
	<copyright>(C) 2020 Open Source Matters, Inc.</copyright>
	<license>GNU General Public License version 2 or later; see LICENSE.txt</license>
	<authorEmail>admin@joomla.org</authorEmail>
	<authorUrl>www.joomla.org</authorUrl>
	<version>4.0.0</version>
	<description>PLG_WORKFLOW_PUBLISHING_XML_DESCRIPTION</description>
```

Is there a reason that the value for `name` is lowercase?
It is a language string and all other language strings are uppercase.

If there is no reason for it to be lowercase would it not be better to change them all to uppercase for consistency?

**Comment by brianteeman** [comment]
> It's the same, the `Text::_()` will always make the passed string uppercase:
> 

For me it should be in uppercase for codestyle

**Comment by brianteeman** [comment]
@laoneo @HLeithner thoughts? 4.4 or 5?

**Comment by HLeithner** [comment]
I expect all extensions are lowercase and I think it's not only the title it's also used for the folder name? But not sure about this. For me it's ok lowercase but don't care too much.

**Comment by brianteeman** [comment]
the folder name isnt a translatable string

**Comment by HLeithner** [comment]
I mean that the name-tag is the folder name but not sure only came to my head
