### ISSUE TITLE
4.3.0 Clearing filter in backend also clears selection limit leading to out of memory issue

### ISSUE THREAD

**Issue by Attila-SWE** [joomla/joomla-cms#40475]
### Steps to reproduce the issue
1. Any backend admin component with several thousand entries (com_users has same issue)
2. Press clear in filter row next to search
3. List limit is also cleared
4. Joomla tries to show all entries
5. Memory exhaustion if too many entries

### Expected result
Keeping selection limit and removing other filters

### Actual result
Out of memory

**Comment by conseilgouz** [comment]
@Attila-SWE : is debug enabled ?

**Comment by Attila-SWE** [comment]
> @Attila-SWE : is debug enabled ?

Yes. But even when disabling all debug functions the limit dropdown is cleared when pressing "clear"-button:

![image](https://user-images.githubusercontent.com/129858930/234217090-9590bb0f-16a0-4c3d-8225-a89208fdfb71.png)

which results in all entries being fetched and displayed. We have thousands of members so pressing clear leads to same results even when debug is disabled (just tested it).

**Comment by Fedik** [comment]
I can confirm, it affects all filters in backend.
Probably result of #39772
https://github.com/joomla/joomla-cms/blob/f7049713c230380a425cce7a8661d2609758e342/build/media_source/system/js/searchtools.es6.js#L265

**Comment by chmst** [comment]
@Attila-SWE is this a new bug or was it also in Joomla 4.2?

**Comment by Fedik** [comment]
It is new, for 4.3

**Comment by Attila-SWE** [comment]
> @Attila-SWE is this a new bug or was it also in Joomla 4.2?

Did not notice in 4.2.x

**Comment by Attila-SWE** [comment]
> Hi,
> 
> I didn't get an error (small count of data on my test sites) but the "clear" button is always enabled (disabled if no filter on 4.2.9) and clicking sets the number of items to 25 instead of the default list limit or a previous change in that list.

Yes. Clear-button is enabled constantly.

If you watch closely to what happens the clear button changes list limit to empty, resends the form, loads all data no matter what number is shown as limit after page reload and then the list limit field is set to some default value (but not respected as all entries already have been loaded).

**Comment by dgrammatiko** [comment]
Check https://github.com/joomla/joomla-cms/pull/40398

**Comment by richard67** [comment]
> Hi,
> 
> I didn't get an error (small count of data on my test sites) but the "clear" button is always enabled (disabled if no filter on 4.2.9) and clicking sets the number of items to 25 instead of the default list limit or a previous change in that list.

This has been clearly fixed with #40398 , which will hopefully be included in the upcoming 4.3.1 bugfix release.

**Comment by Attila-SWE** [comment]
> From what I can see, PR #40398 also fixes the unwanted reset of the ordering and the list limit fields and so could indeed fix also this issue here . But I don't have the huge amount of data to check the out of memory aspect.
> 
> What I can see is that for a short moment, the 2 fields are still cleared when that PR is applied, but after that they have their previous value, i.e. are not reset.

You do not need huge data. Go to com_articles or com_menu and test to clear search. After page reload you can scroll and see if you have more than the number of entries showing that the list limit would suggest.

**Comment by richard67** [comment]
@Attila-SWE Then test the pull request https://github.com/joomla/joomla-cms/pull/40398 . You should do that on a testing environment, a copy of your real site in a subfolder or a subdomain or on a local environment. You can update that testing site to the pull request by using either the custom update URL or the update zip package "Joomla_4.3.0-rc4-dev+pr.40398-Development-Update_Package.zip" linked on this page: https://ci.joomla.org/artifacts/joomla/joomla-cms/4.3-dev/40398/downloads/64739/ .

The custom update URL can be used in the options of the Joomla Update Component when using "Custom URL" as update source, and then you can do a live update with that. Or you download the "Joomla_4.3.0-rc4-dev+pr.40398-Development-Update_Package.zip" and used that for the Upload & Update method of the Joomla Update Component.

If that PR solves your problem, please report back here. Thanks in advance.

**Comment by richard67** [comment]
@Attila-SWE P.S.: For me that pull request solves your issue. After page reload, the list still shows as many items as set by the list limit, and the list limit has not changed.

**Comment by richard67** [comment]
@dgrammatiko Hmm, your PR #40398 solves this issue for me for the patchtester component's list view, but not for the content/categories list.

**Comment by brianteeman** [comment]
#40398 is not a complete fix

**Comment by richard67** [comment]
> #40398 is not a complete fix

Not for this issue here, but for the other issue which it claims to fix, it is complete.

**Comment by richard67** [comment]
@Attila-SWE The pull request is ready now. You can find the new donloads and update IRL here: https://ci.joomla.org/artifacts/joomla/joomla-cms/4.3-dev/40398/downloads/64986/ . Thanks in advance for testing.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40398 . Thanks in advance.
