### ISSUE TITLE
Iframe Wrapper Auto Height not working

### ISSUE THREAD

**Issue by Pallieguy** [joomla/joomla-cms#40489]
### Steps to reproduce the issue
Create a menu item of type "Iframe Wrapper"
Turn on "Auto Height" under "Advanced" tab
Load page

### Expected result
Iframe height will be changed to match that required by the iframe src

### Actual result
Iframe height equals "Height" value set on "Scroll Bar Parameters" tab

### System information (as much as possible)
VPN hosted by Dreamhost
Joomla 4.3.0
PHP 8.1 FastCGI
Ubuntu 20.04.1
Apache 2.4.29
MySQL 14.14 Distrib 5.7.41

### Additional comments
I had not tested earlier versions of Joomla 4 so can't say if this is a new bug.  I don't know what categories this goes under, sorry.

**Comment by brianteeman** [comment]
Auto height. Automatically set height to height of external page. Note - this will only work if the external page is on the same domain. For example, http://www.example.com the external html must be in the example.com root file structure. Sub domains will not work, as a sub domain is considered a separate domain.

**Comment by richard67** [comment]
@Pallieguy is the URL of your iframe on the same or a different domain? Please check the previous comment for why I'm asking.

**Comment by brianteeman** [comment]
This should be closed
