### ISSUE TITLE
Calendar minyear / maxyear are no longer relative inline with documentation and J3 behaviour

### ISSUE THREAD

**Issue by shane-clickingmad** [joomla/joomla-cms#40481]
The behaviour of minyear / maxyear attributes on the calendar field seems to no longer reflect the documentation, or that of how Joomla 3.10.x functioned.

### Steps to reproduce the issue
Create a calendar field with minyear and maxyear attributes set to -10 and 1 respectively.

### Expected result
Calendar year is clamped between 2013 and 2023

### Actual result
Calendar year is clamped between the years -0010 and 0001

### System information (as much as possible)
Joomla 4.3.0

### Additional comments
https://docs.joomla.org/Calendar_form_field_type states "minyear (optional): set a signed integer for a number of years (-10, -2, 0, 7, 12, ...) to define the **relative** lower limit for the year selection. The user cannot select a year before this limit (starting with 3.7.0). If zero, which is the default, there is no limit."

It looks like this may have been of result of this commit (though I don't quite understand the motive behind said change)

https://github.com/joomla/joomla-cms/pull/34870/commits/d6b013dc736da1c7d18f94bd09124ce0c1b24625

**Comment by richard67** [comment]
> It looks like this may have been of result of this commit (though I don't quite understand the motive behind said change)
> 
> [d6b013d](https://github.com/joomla/joomla-cms/commit/d6b013dc736da1c7d18f94bd09124ce0c1b24625)

For other readers: The mentioned commit belongs to PR #34870 .

@Fedik Do you remember why you have removed the `getBoundary` calls?

**Comment by Fedik** [comment]
No idea, maybe to save a couple bites :smile: 

Can probably revert that changes, need to look.

**Comment by shane-clickingmad** [comment]
Any update on this?

**Comment by Fedik** [comment]
No, for now

**Comment by Fedik** [comment]
Please test #40580
