### ISSUE TITLE
Smart Search 

### ISSUE THREAD

**Issue by ericsps** [joomla/joomla-cms#40485]
### Steps to reproduce the issue
1.) Restore site with Akeeba Backup and Kickstart Pro
2.) Delete Smart Search Index
3.) Attempt to Index

### Expected result
Smart Search Index is rebuilt successfully
Smart Search filters return results on front end

### Actual result
1.) The Smart Search Index fails with the following error (screenshot included)
An Error Has Occurred
The following message was returned by the server:
A parse error has occurred while processing the following JSON data:
Unexpected non-whitespace character after JSON at position 52

2.) No results are returned on the front-end search pages using the existing search filters

### System information (as much as possible)
Joomla 4.2.9 and Joomla 4.3.0

### Additional comments
We have had a developer patch the following files (attached![screen shot 2023-04-26 at 14 40 38](https://issues.joomla.org/uploads/1/ac11f8272367b61bb564889ac67a2c52.png):
admininstrator/components/com_finder/src/indexer/Indexer.php line 761
admininstrator/components/com_finder/tmpl/index/default.php line 166
admininstrator/components/com_finder/src/response/Response.php 282
[com_finder-src-indexer-index-php.txt](https://issues.joomla.org/uploads/1/3ec36089ad83b5b4398c2970a7d40ed1.txt)[com_finder-src-Response-Response-php.txt](https://issues.joomla.org/uploads/1/def810b59888551a76f9feba84a0177c.txt)[com_finder-tmpl-index-default-php.txt](https://issues.joomla.org/uploads/1/379c8dd6a69c108c1d0295e1431ad008.txt)

**Comment by Fedik** [comment]
Change error reaporting to `none`, or `minimum`

**Comment by Fedik** [comment]
> We have had a developer patch the following files (attached

Please make a Pull Request.

**Comment by ericsps** [comment]
Fedik,

Apologies...not a developer.

Do you mean php error reporting or Joomla Global Configuration?

Thanks for the response!
EJ<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40485">issues.joomla.org/tracker/joomla-cms/40485</a>.</sub>

**Comment by richard67** [comment]
> Do you mean php error reporting or Joomla Global Configuration?

@ericsps He means Joomla Global Configuration. This then sets the PHP error reporting to the right value. With changing to "none" or "minimum" you can (hopefully) make the site work again.

**Comment by Fedik** [comment]
> Do you mean php error reporting or Joomla Global Configuration?

Yeap, as already Richard said.

The error you see is due to PHP Notice (I suspect a deprecation notice), which break JSON for AJAX request.
When you change error reaporting to none or minimum then this notices will not be shown and all should work as usual.
This notices not an error, it just for developers, you should not worry about them.

**Comment by Hackwar** [comment]
The files you provided don't contain any relevant code changes. This looks like a third party finder plugin acting up. This is not a core bug.
