### ISSUE TITLE
J4.3.0 Clear filter loads all rows at backend

### ISSUE THREAD

**Issue by zdenyv** [joomla/joomla-cms#40491]
### Steps to reproduce the issue
Open System / Manage / Extensions table `administrator/index.php?option=com_installer&view=manage`
Keep initial paging e.g. 20 (from Global Settings)
Click on Clear button next to Search field (you can also try first to search for some text, but result is the same)

### Expected result
Only 25 rows should be loaded (default setting in `administrator/components/com_installer/forms/filter_manage.xml`)
Or better same 20 like on beginning according Global Settings.

### Actual result
**All rows from database are loaded** and after this page size combo is set to 25

### System information (as much as possible)
Windows 10, XAMPP

### Additional comments
Same wrong behavior is also for other tables in other components e.g. `administrator/index.php?option=com_actionlogs&view=actionlogs` can contain huge amount of rows...
And e.g. Manage Users - here is then after pressing Clear displayed error:

> Commands out of sync; you can't run this command now
>  `JROOT\administrator\components\com_users\src\View\Users\HtmlView.php:115`

**Comment by richard67** [comment]
Closing as duplicate report. See Issues #40378 and #40475 . The fix has already been merged and will be included in the upcoming release 4.3.1, see #40398 .
