### ISSUE TITLE
Smart Search Levels not working

### ISSUE THREAD

**Issue by JohnDeJuhl** [joomla/joomla-cms#40495]
I have a problem with Smart Search:

As soon as I filter more that 1 level of Categories, the Search Result shows no Results at all.

Pls. see this short video:

https://vimeo.com/821189454/89331d2305

Thanks,

John.

**Comment by brianteeman** [comment]
Thank you for the very detailed video. Could you please post the version of php being used

**Comment by pixelhexe** [comment]
Possibly same issue as in [#40343](https://github.com/joomla/joomla-cms/issues/40434)?

Fix as in [PR #39751](https://github.com/joomla/joomla-cms/pull/39751) might help?

**Comment by JohnDeJuhl** [comment]
Sorry for the delay: it's PHP 8.0.28

**Comment by richard67** [comment]
@JohnDeJuhl Could you check if #39751 fixes this issue?

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39751 . Thanks in advance.
