### ISSUE TITLE
The doctrine of instructions for online casino games

### ISSUE THREAD

**Issue by JennyCasino** [joomla/joomla-cms#40497]
SPAM

**Comment by DaniMarl** [comment]
An attractive list of online casinos [https://jennycasino.com/casinos/](https://jennycasino.com/casinos/ "https://jennycasino.com/casinos/") , it suits me. I have selected a few of them to play where the games are more fascinating. And I also liked the interesting special bonuses called "Refer a Friend" or "Invite a Friend", it's just kind of novelty in gambling, I haven't seen it before.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40497">issues.joomla.org/tracker/joomla-cms/40497</a>.</sub>

**Comment by fgsw** [comment]
Please delete the spam above.

**Comment by DaniMarl** [comment]
Attractive list of online casinos at JennyCasino ++, it suits me. I chose a few of them to play, where the games are more exciting. And I also liked the interesting special bonuses called "Refer a Friend" or "Invite a Friend", this is just some kind of novelty in gambling, I have not seen this before.
