### ISSUE TITLE
Wrapper Menu

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40490]
### Steps to reproduce the issue
PR #32342 broke the functionality of the wrapper menu item by changing it to a type url and adding url validation

There is a parameter in the optiion for this menu type called autoadd
> By default, http:// will be added unless it detects http:// or https:// in the URL you provide. This allows you to switch off this functionality.

This cannot work when the field is a type url with validate and filter url

As a result it is not possible to have a wrapper to an internal url as http is always added 

If it is not desired to be able to have an internal url then the following code is useless and should be cleaned up

https://github.com/joomla/joomla-cms/blob/a950b5354264258cf7ba4285f6a38b38cc6f956e/components/com_wrapper/tmpl/wrapper/default.xml#L57-L67

https://github.com/joomla/joomla-cms/blob/a950b5354264258cf7ba4285f6a38b38cc6f956e/components/com_wrapper/src/View/Wrapper/HtmlView.php#L87-L106

https://github.com/joomla/joomla-cms/blob/a950b5354264258cf7ba4285f6a38b38cc6f956e/administrator/language/en-GB/com_wrapper.ini#L7-L8

If it is desired to allown internal urls then this PR #32342 needs to be reverted

**Comment by richard67** [comment]
Is PR #37547 related to this issue?

**Comment by brianteeman** [comment]
I guess so - although that PR doesn't completely fix the issue created by the original PR. It does make the idea of having a RLDQ a bit of a joke as it is now over 1 year since it was added.

**Comment by brianteeman** [comment]
closing as a duplicate
