### ISSUE TITLE
Warning message if no menu object and edit profile page

### ISSUE THREAD

**Issue by Attila-SWE** [joomla/joomla-cms#40499]
### Steps to reproduce the issue
1. Activate error reporting
2. Go to registration/edit_details/ without having a menu object (for example through a custom module or direct url)

### Expected result
No warning

### Actual result
Warning: Attempt to read property "query" on null in /components/com_users/src/View/Profile/HtmlView.php on line 142

### System information (as much as possible)
Joomla 4.3 and php 8.1

### Additional comments
Probable solution is to only execute line 142 if query is not null.

**Comment by Nitz2611** [comment]
Hey if it has not been done , can you assign me for this?

**Comment by chmst** [comment]
@Nitz2611 thank you - no assignment needed. We will be happy to receive your PR!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40499">issues.joomla.org/tracker/joomla-cms/40499</a>.</sub>

**Comment by brianteeman** [comment]
@Hackwar guessing this is another menu item routing issue

**Comment by Hackwar** [comment]
Not exactly a menu item routing issue, but I created a PR: #43140 Since we have a PR, I'm closing this one.
