### ISSUE TITLE
[4.3] missing plugin attribute in .xml file

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#40520]
### Steps to reproduce the issue

Missing plugin attribute in .xml files, see:
- joomla\plugins\quickicon\joomlaupdate\joomlaupdate.xml
- joomla\plugins\system\guidedtours\guidedtours.xml

### Expected result

`<folder plugin="[plugin name]">`

### Actual result

`<folder>`

### System information (as much as possible)

Joomla 4.3 and 4.4

### Additional comments

https://github.com/joomla/joomla-cms/blob/dcc81595a6bb08fa2ea120d653251f03d08306ea/plugins/quickicon/joomlaupdate/joomlaupdate.xml#L14

https://github.com/joomla/joomla-cms/blob/dcc81595a6bb08fa2ea120d653251f03d08306ea/plugins/system/guidedtours/guidedtours.xml#L14

Related to #40204
Ping @laoneo

**Comment by laoneo** [comment]
Can you make a pr to fix it?

**Comment by sandewt** [comment]
> Can you make a pr to fix it?

Yes, for Joomla 4.3 (so this time not for Joomla 4.4).

**Comment by sandewt** [comment]
Closed, see pr #40521
