### ISSUE TITLE
Joomla 4.3.0 Media Gallery for Manager does not work with a reverse proxy with SSL.

### ISSUE THREAD

**Issue by T-Nosaka** [joomla/joomla-cms#40523]
### Steps to reproduce the issue

This joomla 4.3.0 is in docker.
Joomla in docker is nginx with php-fpm, running on port 80, translating to port 8080 and listening.
In addition, nginx on the host uses a reverse proxy to connect from SSL to docker's 8080 port.
Joomla Media Gallery does not work properly in this environment.

### Expected result

Joomla Media Gallery should function normally even in joomla in docker with reverse proxy using SSL.

### Actual result

Only 'images' string are displayed, and the actual images, etc. are not displayed at all. I can't even create a folder.

### System information (as much as possible)

amd64 environment
Ubuntu 22.0.4.2
Docker 23.0.5
nginx 1.18.0
php-fpm8.1
mariadb 15.1

### Additional comments

I did it in the arm environment, but it was the same behavior.

**Comment by T-Nosaka** [comment]
Stopping SSL on nginx on the host and changing to port 80 works fine.

**Comment by richard67** [comment]
@T-Nosaka Could you post a screenshot of the "Proxy" section in your Site settings in Global Configuration? See here for an example: https://docs.joomla.org/Help4.x:Site_Global_Configuration_Server

I think you have to switch on the "Behind Load Balancer" option for the reverse proxy, and you have to fill in the right details for the outbound proxy (i.e. the forward direction).

**Comment by richard67** [comment]
@T-Nosaka P.S.: See also https://docs.joomla.org/Help310:Site_Global_Configuration#Proxy_Settings .

**Comment by T-Nosaka** [comment]
Thank you for answering.

The global setting "Behind Load Balancer" remains Yes.
[Shot1](https://homebase.server-on.net/images/stories/contents/joomla_issue/j1.jpg)

A reverse proxy connection from the internal network is as follows.
[Shot2](https://homebase.server-on.net/images/stories/contents/joomla_issue/j2.jpg)
http://joomla.oci.woonet/

A reverse proxy connection from an external network is as follows.
[Shot3](https://homebase.server-on.net/images/stories/contents/joomla_issue/j3.jpg)
https://homebase.server-on.net/

It's freely connect to the outside from Joomla.
Joomla 3.x had not the problem, so I'm guessing after 4.x is the problem.

**Comment by dgrammatiko** [comment]
Is there any error logged in the browser dev tools?

**Comment by richard67** [comment]
@T-Nosaka Your first screenshot shows that you have not switched on the "Enable Outbout Proxy" setting. Please do that and then fill in the necessary details in the fields ("Outbound proxy host" and "Outbound proxy port") which become visible below that option when you switch it on.
