### ISSUE TITLE
[4.3] Cassiopeia Bootstrap 5.2

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40540]
the main cassiopeia template.scss file in 4.3+ has some new lines for borders and backgrounds

an explanation of those new lines from @dgrammatiko can be found here https://github.com/joomla/joomla-cms/pull/39379#issuecomment-1356121914

I dont really understand what is being said there but unfortunately they are not correct :(

For example 
`.bg-black {
  background-color: var(--black) !important;
}
`
this does not work as there is no --black

**Comment by dgrammatiko** [comment]
Hmm, https://github.com/twbs/bootstrap/blob/cb021439c683d9805e2864c58095b92d405e9b11/dist/css/bootstrap.css#L19

https://github.com/twbs/bootstrap/blob/cb021439c683d9805e2864c58095b92d405e9b11/dist/css/bootstrap.css#L8126-L8129

This needs some investigation why cassiopeia is not having all the colors that BS defines in the root
