### ISSUE TITLE
Feature Request - user.css - inherit

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40542]
### Is your feature request related to a problem? Please describe.
If you create a user.css (and presumably a user.js) in your main template eg cassiopeia then it is used 
If you create a child template eg child_cassiopeia then the parent user.css is used 
If you create a user.css in your child template then only that child user.css is used 

This means that you have to copy everything in the parent user.css to the child user.css 

### Describe the solution you'd like
a child template should load the parent user.css AND then any child user.css
REMEMBER you may have multiple child templates being used on a site

### Additional context - Use Case
add a user.css to cassiopeia to change the size of the h1 tp 50px
add a child green_cassiopeia to change all the color of the h1 to green
add a child red_cassiopeoa to change all the color of the h1 to red

### My expected/desired  behaviour 
Menu item with default cassiopeia tempalte **h1=50px**
Menu item with green_cassiopeia **H1=50px and GREEN**
Menu item with red_cassiopeia **H1=50px and RED**

Currently the only way to achieve that is to **copy** everything in the main user.css to both the children user.css

This really limits the power of child templates - _unless I have missed an undocumented feature_

**Comment by brianteeman** [comment]
Another reason to have this is that child templates use the overrides in a parent template (if not being overridden again in the child. But if you used any user.css then it will be lost in the child

**Comment by dgrammatiko** [comment]
For the time you can add it manually at the top of the child user.css, ie

```css
@import("../../cassiopeia/css/user.css");

/* rest of the child user.css... */
```

**Comment by brianteeman** [comment]
thanks for the tip

**Comment by brianteeman** [comment]
closed due to lack of interest. I solved it for myself as described above
