### ISSUE TITLE
The search term is not highlighted in the search results if there is no space right after the term in the text

### ISSUE THREAD

**Issue by DSist** [joomla/joomla-cms#40545]
### Steps to reproduce the issue

Highlight Search Terms parameter = Yes. The issue can be reproduced with a specific search provided there is no space right after the term in the text. It does not matter what comes after the term: a punctuation mark or a latter (if the search term is a part of a bigger word), the term is not highlighted.

### Expected result

Green color - search terms highlighted correctly with mark data-markjs="true", there is a space right after all the terms.

### Actual result

Red color - missing highlights because there is a dot right after the terms, not space.

![search_bug2_1](https://user-images.githubusercontent.com/95962014/236458989-1ab38fef-9957-45b3-a46b-2e3fb3094e36.png)

### System information (as much as possible)

Joomla 4.3.1 native search
PHP 8.0.3

### Additional comments

The issue has been there from the very beginning of Joomla 4.

**Comment by brianteeman** [comment]
Confirmed

**Comment by hans2103** [comment]
Confirmed
Highlight.js was added via https://github.com/joomla/joomla-cms/pull/33089
Highlight.js was built upon mark.js
Looking at an example of mark.js I see that finding `amet` even highlights the search word followed by comma or dot. 
https://jsfiddle.net/julmot/vpav6tL1/

so ... something in our Joomla code breaks the feature mark.js already provides.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40545">issues.joomla.org/tracker/joomla-cms/40545</a>.</sub>

**Comment by hans2103** [comment]
Issue started by merging the solution for https://github.com/joomla/joomla-cms/pull/38908

I'll create a PR te revert that commit and solve the issue using CSS.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40545">issues.joomla.org/tracker/joomla-cms/40545</a>.</sub>

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40576
