### ISSUE TITLE
Sometimes there is no space between two words in the search results while there is actually a space in the text

### ISSUE THREAD

**Issue by DSist** [joomla/joomla-cms#40543]
### Steps to reproduce the issue

Result Description parameter = Show. It doesn't happen often, but can be reproduced with a specific search.

### Expected result

![search_bug1_2](https://user-images.githubusercontent.com/95962014/236449412-baee8aa6-02c5-4c7f-acc2-2a47001e6141.png)

### Actual result

![search_bug1_1](https://user-images.githubusercontent.com/95962014/236451906-c4dc1f65-7107-462f-8f11-55aa52ae46ca.png)

### System information (as much as possible)

Joomla 4.3.1 native search
PHP 8.0.3

### Additional comments

The issue has been there from the very beginning of Joomla 4.

The articles are in Russian, but I don't think it is a language-specific issue. The site is under development with no dns record. If needed I can provide all the data in a private message.

**Comment by chmst** [comment]
Could you please check if the space is something like %nbsp; or %shy; in the original text?

**Comment by DSist** [comment]
> Could you please check if the space is something like %nbsp; or %shy; in the original text?

Nope, a regular space. Moreover if I delete this space in the original text Joomla removes the previous one as well, etc.

I have extracted the text fragment to reproduce the issue. Create a new article and paste this code:

//--- Code

<p>Планетарное Братство Учителей Мудрости, направляющее эволюцию на нашей планете. Распределительный центр энергии Любви Бога. Духовный источник всех человеческих рас, цивилизаций, религий, культур. Великое Белое Братство. Иерархия Учителей. Иерархия Света.</p>
<p>Духовная Иерархия — это реальность, как и сама душа. А для нас, людей, это сверхреальность, так как Иерархия представляет собой более высокое царство природы — царство душ, которое является причинным по отношению к нашему человеческому царству. Это значит, что все эволюционные изменения, которые происходят в человечестве, являются следствиями изменений, что сначала происходят в Иерархии, то есть в умах Учителей Мудрости, и лишь затем они осаждаются на планы человеческого бытия, где и обретают те или иные формы: религиозные, политические, общественные, экономические и другие.</p>
<p>Планетарная Иерархия направляет эволюцию на нашей планете, имея одной из задач непрерывное расширение человеческого сознания, так как именно человеческое царство является связующим звеном между тремя дочеловеческими и тремя сверхчеловеческими царствами в теле Планетарного Логоса, нашего Бога. Иерархия воздействует на человечество двумя основными способами:</p>

//---

Search the term: 

//--- Term

нашего

//---

There is no space in the search results between the words inside the red circle

![search_bug1_3](https://github.com/joomla/joomla-cms/assets/95962014/ade76084-24ad-499d-848d-29061c65b9fb)

**Comment by chmst** [comment]
I can confirm the issue, Firefox and Chrome. But no clue what happens here.

**Comment by brianteeman** [comment]
Wonder why it was different for me

**Comment by chmst** [comment]
After removing the spaces from the copied text with "my" spaces the search result is ok, There must be something in the text.

**Comment by DSist** [comment]
I have replaced all the spaces in the text with "new" spaces via JCE Editor, the result is the same.

**Comment by DSist** [comment]
I have found how to reproduce both results. I use JCE Editor as default editor.

If you copy the source text I have cited above, paste it via Code section of the Editor and save, the text is inserted as a single paragraph. The search result is OK.

If you divide it into two or three paragraphs using Enter via Editor section with br/ inserted or with p tag via Code section the result is wrong.

**Comment by DSist** [comment]
Yes, it is replicated with tinymce: a single p tag - OK, several p tags - no space.

**Comment by Hackwar** [comment]
The problem is the tokenize() code in the Smart Search component in the Helper class. It removes all tags and seems to not insert the right spaces here.

**Comment by Hackwar** [comment]
Got a PR to fix this with #41502. Closing the issue.
