### ISSUE TITLE
Modules displaying in my custom component views despite menu assignment off

### ISSUE THREAD

**Issue by christomagnifico** [joomla/joomla-cms#40550]
4.2.9 Cassiopeia template. I have assigned modules to my home page, only home page. These modules appear in my custom component view. I checked menu assignment in main menu also.

I assume there exists some sort of home page inheritence.

Other than using javascript to hide the modules, is there a better method?

**Comment by brianteeman** [comment]
From what you have said I am guessing that your component does NOT have a menu item. If it doesn't then it will use the itemid of the page that the link was on. The itemid should really be called the menuid and its the glue between a component and a module.

**Comment by christomagnifico** [comment]
Brian thank you for speedy response. I have created my default.xml and edit.xml files within site/tmpl/someview, and created a menu item for each component view in my "main menu". _Am I missing a further step?_ Module assignment are display NO in menu item options, and only pages selected:home in my module settings.

**Comment by brianteeman** [comment]
disable sef urls in global configuration and check the itemid in the url

**Comment by christomagnifico** [comment]
With SEF off, if my url includes the Itemid, the page is working as expected. Perhaps I need to include &Itemid=123 in all of my links... then switch on SEF url's ?

**Comment by brianteeman** [comment]
no. that means (as far as I remember) that your router file is not correct.

**Comment by christomagnifico** [comment]
Is a router file required in J4 component?

**Comment by brianteeman** [comment]
only if you want it to work

**Comment by chmst** [comment]
Closing this as it is not a Core issue. 

@christomagnifico  please ask questions in forum.joomla.org or stack exchange, or join us on  mattermost - there is a extension developer channel. https://joomlacommunity.cloud.mattermost.com
