### ISSUE TITLE
Favicon image no longer works on v4.3.1

### ISSUE THREAD

**Issue by jkfuerte** [joomla/joomla-cms#40554]
Hi,I was using v4.3.0 but now favicon image no longer appears on v4.3.1
Could you please help me about this?

**Comment by richard67** [comment]
@jkfuerte How do you think someone can help you if you do not provide any information besides the Joomla version?

**Comment by chmst** [comment]
Besides that - forum.joomla.org is the better place for support. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40554">issues.joomla.org/tracker/joomla-cms/40554</a>.</sub>

**Comment by brianteeman** [comment]
Should be closed

**Comment by richard67** [comment]
@jkfuerte As you haven't provided any information about your favicon, e.g. where it was located, it is impossible to help you. In case if you just have replaced the favicon shipped with the CMS core in the "media\system\images" folder, then of course that's overwritten on update. Please use the support forum https://forum.joomla.org/ for support questions like how to use your own favicon. I am almost sure you can already find answers there.

Closing as not a core issue.
