### ISSUE TITLE
[4.3] TinyMCE Language of Parts

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#40568]
### Steps to reproduce the issue

Go to the TinyMCE plugin and add a Language of Parts item but leave the fields blank.
Save and go to edit an article.

### Expected result

Article Edit Form

### Actual result

Error page:
 array_merge(): Argument #1 must be of type array, null given 
 JROOT/plugins/editors/tinymce/src/PluginTraits/DisplayTrait.php:393 

### Additional comments

Discovered by a user who accidentally added an empty field.

**Comment by brianteeman** [comment]
confirmed. If no one beats me to it I will have fix over the weekend

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40581 . Thanks in advance.
