### ISSUE TITLE
Joomla 4.3.1 HTML module header is not displayed and a class is assigned

### ISSUE THREAD

**Issue by kosh2323** [joomla/joomla-cms#40570]
Hello everyone. When creating an HTML module, the module header is not shown and a class is not assigned to the module. Joomla 4.3.1. Why is this happening?
![1](https://github.com/joomla/joomla-cms/assets/82117170/e6171793-c7d3-46c0-b8de-2e39e0d5c927)

![2](https://github.com/joomla/joomla-cms/assets/82117170/3d26f9fb-dd87-4e5e-b6a3-b4cce3d1ac50)

![3](https://github.com/joomla/joomla-cms/assets/82117170/00747112-e646-476b-8a55-5b5663576f94)

**Comment by sandewt** [comment]
Choose another module style, in this case **html5**. Then the title and class must be visible. Correct?

![Schermafbeelding 2023-05-11 203554](https://github.com/joomla/joomla-cms/assets/9271775/ab14aa34-8dc8-4b53-bc22-31b9b92f0782)

**Comment by kosh2323** [comment]
> Choose another module style, in this case **html5**. Then the title and class must be visible. Correct?
> 
> ![Schermafbeelding 2023-05-11 203554](https://user-images.githubusercontent.com/9271775/237784770-ab14aa34-8dc8-4b53-bc22-31b9b92f0782.png)

Yes, thanks for the hint, it works correctly.

**Comment by kosh2323** [comment]
I think the topic can be closed.
