### ISSUE TITLE
[4.4] Plugin: Allow Compression Option: Task/checkfiles/src/extension/checkfile.php [Feature Request]

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#40575]
### Steps to reproduce the issue
Unfortunately, when the plugin was created, it was not thought of and without compression it actually gets big. 

### Expected result
The (missing) third parameter would allow a compression option:
https://github.com/joomla/joomla-cms/blob/4.3-dev/plugins/task/checkfiles/src/Extension/Checkfiles.php#L153

### Actual result

For example:
    image before adjustment: 1280x1794 Pixel - 0,367MB
    image after adjustment: 1080x1514 Pixel - 1,686MB

### System information (as much as possible)
Reported with Joomla 4.3.1
@bembelimen: pls assist. Thank you.

**Comment by richard67** [comment]
@ChristineWk When pining Benjamin @bembelimen you should use the right nick name.

**Comment by ChristineWk** [comment]
Sorry about ...

**Comment by alikon** [comment]
please test #40658
