### ISSUE TITLE
Com_users backend toolbar buttons (save, save & close) not working as expected for non super admin

### ISSUE THREAD

**Issue by Attila-SWE** [joomla/joomla-cms#40573]
### Steps to reproduce the issue
1. Login as admin without rights to change ACL for com_users
2. Edit a user and press save or save & close

### Expected result
Save -> Save and stay on same edit page
Save & close -> Save and go back to users view with list of users

### Actual result
Save -> Saves and sends admin to control panel start page
Save & close -> Saves and sends admin to control panel start page

### System information (as much as possible)
Joomla 4.3.1
Php 8.1

### Additional comments
Giving admin right to change ACL for com_users resolves issue. No issue when testing com_menus or com_content even without ACL rights for those components.

**Comment by brianteeman** [comment]
Issue confirmed

**Comment by alikon** [comment]
should be a regression from #39038

**Comment by joomdonation** [comment]
Please test PR https://github.com/joomla/joomla-cms/pull/42872, it should solve the issue.
