### ISSUE TITLE
If username is e-mail adress then no activate account email is sent

### ISSUE THREAD

**Issue by Attila-SWE** [joomla/joomla-cms#40571]
### Steps to reproduce the issue

1. Enable that user need to activate their account themselves
2. Frontend guest creates user account where username is same as e-mail

### Expected result
Activation e-mail is sent

### Actual result
Private message is sent to admin that activation e-mail couldn't be sent

### System information (as much as possible)
Joomla 4.3.1
PHP 8.1.17

**Comment by brianteeman** [comment]
Unable to replicate
![image](https://github.com/joomla/joomla-cms/assets/1296369/48f42d61-2004-485d-b8ce-81ae98d1f575)

![image](https://github.com/joomla/joomla-cms/assets/1296369/249ad014-8532-4d3e-8c85-ce1db0abe4b5)

**Comment by Attila-SWE** [comment]
> Unable to replicate

Could you please test with username === email address used for account? 

So abc@abc.com for both username and email address. 

In your image I understand that username != email

Thanks

**Comment by brianteeman** [comment]
Still no problem.

Admin received an email
![image](https://github.com/joomla/joomla-cms/assets/1296369/b40bed71-ecd0-4e4f-810c-45e563e88613)

User received an email
![image](https://github.com/joomla/joomla-cms/assets/1296369/ec86f563-6262-4b63-91f0-bfb9b95dc969)

**Comment by Attila-SWE** [comment]
> Still no problem.

Thank you for testing. Any suggestions to how I could go on with testing why I have issue? It has affected 100% of users (4) who tried to register with username === e-mail adress since upgrading to joomla 4 last week.

**Comment by Attila-SWE** [comment]
So. I have found issue.

Further testing gave error:

Prohibited input U+00000020

When user tries to register as above. Removing {USERNAME} from email template for user registration solves the issue.

So steps for reproducing error:

Add {USERNAME} to email subject for template  com_users.registration.user.self_activation and retest.

**Comment by brianteeman** [comment]
Please test #41138

**Comment by brianteeman** [comment]
Can be closed as there is an PR

**Comment by PetrChudoba73** [comment]
I did a test with 4.3.3 and I am not able use username === email.

**Comment by Quy** [comment]
@PetrChudoba73 Please test PR [#41138 ](https://github.com/joomla/joomla-cms/pull/41138/files) with PatchTester or manually changing the file which is a simple change is this case.
