### ISSUE TITLE
Calendar gets stuck above field instead of aligning based on available space

### ISSUE THREAD

**Issue by MojoMojosoup** [joomla/joomla-cms#40577]
### Steps to reproduce the issue
1. Open the calendar on any date field where it'll appear above the field.
2. Scroll down and open the calendar again.

### Expected result
![image](https://github.com/joomla/joomla-cms/assets/44834581/57571445-5c39-43f2-9a83-cf940f531af7)

### Actual result
![image](https://github.com/joomla/joomla-cms/assets/44834581/a01244b7-3af9-4ade-b2ab-3937bcbde7be)

### System information (as much as possible)
Found this issue on firefox.

### Additional comments
The calendar will align correctly to the bottom if it hasn't appeared at the top before.

**Comment by chmst** [comment]
Related  #38443, #38346

**Comment by richard67** [comment]
Closing as having a pull request. Please test #41477 . Thanks in advance.
