### ISSUE TITLE
Category List Menu shows empty list (and strange behavior)

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#40582]
### Steps to reproduce the issue
Just upgraded from J3.10.1 to J4.3.1 with a multilingual site.
A menu item is a "Category List" one, pointing to a category where there are many articles (more than 200) and with Title filter box.

### Expected result
The page shows the list of articles contained in that category.

### Actual result
The page shows an empty list with the message "There are no articles in this category. If subcategories display on this page, they may have articles."
By clicking on the "Clear" button of the Title filter box, the page is reloaded and first 5 articles appear (they do exist!), but clicking on one of the following pages in the navigation bar leads to an empty page again.

### System information (as much as possible)
Joomla 4.3.1, Rocky Linux 9.1, PHP 8.1.19.

### Additional info
If changing the menu type to blog, articles are normally displayed.

**Comment by chmst** [comment]
Sorry, I don't understand the issue. 
A category list shows a list of categories, or a category tree i.e. also the child categories. 
A category blog shows a list of articles in a category. This is intended behaviour.

**Comment by Giuse69** [comment]
Hi, the "Category List" is described as "Displays a list of _articles_ in a category" and infact in J3 it displays the list of articles in the selected category. In J4 it shows no article, but clicking on "clear" on the filter, the articles do appear, but navigation does not work.

**Comment by richard67** [comment]
@chmst Well, the help page indeed tells that it shows articles: https://docs.joomla.org/Help4.x:Menu_Item:_Category_List

@Giuse69 Maybe something wrong with permissions for the categories or the particular articles? Or with the "List Layouts" setting of the menu item? Could you check on the J4 help page which I've linked if everything is right?

**Comment by richard67** [comment]
@chmst Maybe you had this one in mind? https://docs.joomla.org/Help4.x:Menu_Item:_List_All_Categories

**Comment by Giuse69** [comment]
@richard67: I checked and I see no strange settings. I created a new menu item from scratch pointing to that category and again no article is shown. As described in the first post, if I click on the "clear" button of the title search, results do appear...

**Comment by Giuse69** [comment]
Hi, any update on this? If you can re-read the initial post, the behavior is very suspicious of a bug/conflict: no article is returned with the Category List on the first page load, then clicking on the "Clear" button of the title filter makes the page reload with articles listed. Also every interaction with the filter (like typing a char and press enter) makes the articles appear.
So it's not an issue of permission or menu configuration since using the filter, the articles in that category do show.
thanks for you feedback

**Comment by Giuse69** [comment]
I finally found that the problem is due to a bug in Seblod opened 2 days ago: https://github.com/Octopoos/SEBLOD/issues/750
So I am closing this for Joomla
thanks

**Comment by coolcat-creations** [comment]
Thanks to @bembelimen for finding the source of the bug, you already helped at least 2 persons. :-)
