### ISSUE TITLE
Not all Codemirror shortcuts are working.

### ISSUE THREAD

**Issue by bmankowski** [joomla/joomla-cms#40595]
### Steps to reproduce the issue
Switch editor to Codemirror in global configuration.
During editing in Codemirror press "Ctrl+/" to comment a line or block.

### Expected result
Line/block should be commented.

### Actual result
Nothing happens.

### System information (as much as possible)
Tried on freshly installed joomla 4 instalation, and asked on Joomla forum to check the scenario:
https://forum.joomla.org/viewtopic.php?f=814&t=1001653
and the other person had the same result.

**Comment by brianteeman** [comment]
Why do you expect that behaviour?
Can you replicate it on a codemirror demo from the codemirror.net site?

**Comment by bmankowski** [comment]
@brianteeman  I expect this behavior because in https://codemirror.net/docs/ref/#commands "ctrl+/" is stated as "Ctrl-/ (Cmd-/ on macOS): toggleComment." Tried it in Joomla4 and as it doesn't work I filed this tikcet. Could you check if it works for you?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40595">issues.joomla.org/tracker/joomla-cms/40595</a>.</sub>

**Comment by bmankowski** [comment]
On https://codemirror.net/ it works normally.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40595">issues.joomla.org/tracker/joomla-cms/40595</a>.</sub>

**Comment by brianteeman** [comment]
The links you shared are for codemirror v6. Joomla is currently using v5. 
I checked the demos for v5 and unless I am missing something it is not a feature of v5
https://codemirror.net/5/demo/fullscreen.html

**Comment by bmankowski** [comment]
In https://codemirror.net/5/doc/manual.html#commands it mention it's possible to use comment/comment.js
And in fact it's already in /media/vendor/codemirror/addon/comment
I just don't have a knowledge to bind it to a key. 
Do you think it's worth to make this change, or do you think it's better to just wait for next version of codemirror to be introduced to Joomla v4?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40595">issues.joomla.org/tracker/joomla-cms/40595</a>.</sub>

**Comment by Fedik** [comment]
It is work in Joomla 5 with Codemirror 6 https://github.com/joomla/joomla-cms/pull/41070
