### ISSUE TITLE
[5.0] Testing Sample Data - module banners client

### ISSUE THREAD

**Issue by hans2103** [joomla/joomla-cms#40616]
### Steps to reproduce the issue

- Install Joomla 5.0
- Joomla 5 > Administrator > Dashboard > Sample Data
- Install _Testing Sample Data_
- Visit frontend /index.php/banner

### Expected result

![Scherm­afbeelding 2023-05-17 om 12 31 32](https://github.com/joomla/joomla-cms/assets/639822/f7c1000d-3f47-48be-8a28-d33e31b6f456)

### Actual result

![Scherm­afbeelding 2023-05-17 om 12 31 49](https://github.com/joomla/joomla-cms/assets/639822/af4a94d3-6d74-4755-b7f1-757669e91f7e)

**Comment by hans2103** [comment]
Joomla! 5 > Administratror > Content > Site Modules
/administrator/index.php?option=com_modules&view=module&layout=edit&id=137&client_id=0

Configuration of field _Client_ should be changed from `Joomla` to non-set. Because none of the items in com_banners is assigned to a client.

**Comment by brianteeman** [comment]
Going to close this as the testing sample data is being reworked see #41489
