### ISSUE TITLE
Extend Custom Field - Editor

### ISSUE THREAD

**Issue by macstalker** [joomla/joomla-cms#40619]
For some custom fields I would like to have an option to choose code editor explicitly no matter what editor selected in user preferences, as well as type of content to wrap a code in appropriate tags.

I propose to add following options:

Editor type: 

	Default (accordingly to user preferences, current behavior)
	WYSIWYG (loads WYSIWYG edior)
	Code (loads CodeMirror or None, depending on user preferences)

If Code is chosen then activate another dropdown with syntax options:
None, Style, Javascript, PHP, etc - these should wrap field output in appropriate tag: <style>, <javascript>, <?php>, etc.

![screen shot 2023-05-17 at 11 14 53](https://issues.joomla.org/uploads/1/8d8da6fa44b9261efc42e22d3b651cba.png)

![screen shot 2023-05-17 at 11 15 02](https://issues.joomla.org/uploads/1/bf6d0a4410bc8f2e9441f269641a8cf3.png)

**Comment by rdeutz** [comment]
Nothing we want to implement for core
