### ISSUE TITLE
[4.3] GuidedTours system plugin is not loading component language file

### ISSUE THREAD

**Issue by machadoug** [joomla/joomla-cms#40624]
### Steps to reproduce the issue
Create Guided Tours for custom components and add the language strings to com_component.sys.ini file.

### Expected result
The language file should be loaded by the System > Guided Tours plugin, but it's not.

### Actual result
Untranslated constants

### System information (as much as possible)
Joomla 4.3
PHP 8

### Additional comments
Created PR #40606

**Comment by richard67** [comment]
@machadoug There is no need to create an issue when you have also created a PR. We close an issue when we have a PR for it.
