### ISSUE TITLE
[4.3] pagination counter is hiding behind pagination

### ISSUE THREAD

**Issue by hans2103** [joomla/joomla-cms#40621]
While testing another paganation issue I stumbled upon this one. The pagination counter is hiding behind pagination on mobile. 
Why is there a float on paragraph with className `com-content-category-blog__counter`?

![Scherm­afbeelding 2023-05-17 om 16 08 41](https://github.com/joomla/joomla-cms/assets/639822/8411934f-e6df-4f91-93ee-c8bd92a5b3d9)

**Comment by brianteeman** [comment]
I assume the float is there for the desktop view

**Comment by richard67** [comment]
Closing as having a pull request. See #40623 .
