### ISSUE TITLE
Core Update site goes to disabled state

### ISSUE THREAD

**Issue by Yariz** [joomla/joomla-cms#40632]
### Steps to reproduce the issue
None

### Expected result
Keeps enabled

### Actual result
Goes disabled

### System information (as much as possible)
Has happened since version 3.8.

### Additional comments
Core Update site goes randomly (?) to disabled state and has to be enabled manually, after that update works as expected. However, update drops back to disabled and I haven't found any logical reason for this. Periods between version updates are quite long, so I cannot say whether it drops on next day or next month.
When 4.2.9 was released, I enabled update (once again) and when logged in today, Joomla told me it was still 4.2.9 and up-to-date, but the latest version currently is 4.3.1.

**Comment by Yariz** [comment]
Once again, manual enable let me to update to latest version and core update is still enabled (so far...)

**Comment by brianteeman** [comment]
if your server can not successfully connect to the update server regularly then it will disable itself

**Comment by Yariz** [comment]
OK. Is there a way to re-enable it automatically?

**Comment by brianteeman** [comment]
No. It is being disabled because of your server. You need to ask your hosts to fix the server
