### ISSUE TITLE
Module menu tree not displaying correctly

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#40636]
### Steps to reproduce the issue
With J4 sample data
Creat a 'Test child' of the 'New feature: Workflows' menu item in the Main blog menu
Open Breadcrumbs Module for edit
Navigated to Menu Assignment tab
Select 'Only pages selected'.
The 'Test child' was displayed at the bottom of the list instead of in the tree under the 'New feature: Workflows' menu item

### Expected result
The 'Test child' menu item should be displayed in the tree under the 'New feature: Workflows' menu item

### Actual result
The 'Test child' menu item is displayed at the bottom of the list

### Additional comments
Problem also exists for the 'All pages except those selected' tab

https://forum.joomla.org/viewtopic.php?f=808&t=1001819

**Comment by brianteeman** [comment]
please post some screenshots

**Comment by Webdongle** [comment]
Just double checked was PEBKAC.  I must have been 1/2 asleep

**Comment by brianteeman** [comment]
So please close it
