### ISSUE TITLE
[4.3] Quick Icons module: Problem with Languages Icon

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#40647]
### Steps to reproduce the issue
On the main control panel, edit the Quick Icons module by selecting the **Show Items with Count** value for the **Languages Icon**.

![Screenshot_1](https://github.com/joomla/joomla-cms/assets/8440661/3a4fb796-e657-462f-89ef-6b479cb35e85)

Having 2 languages ​​on the site (together with English), we see one less on the main page. If we remove "our" language, the main page will still show one. If we set 2 or more languages, the main page will again show one.

![Screenshot_2](https://github.com/joomla/joomla-cms/assets/8440661/7ee3c254-ee42-414d-8371-134909779e29)

**Comment by Kostelano** [comment]
The model displays "published" languages. But we will always have the default language 1..?

By analogy with other icons - there we also display only published elements.

Then it makes no sense for the language parameter to display a quantity, it should just be a link to the installed languages (similar to media, styles / templates, smart search, etc). Or the number of installed languages, which will be different from the logic of other icons.

https://github.com/joomla/joomla-cms/blob/c3593e96dc68b67df3337c2f0caa2ba2dcbdf05e/administrator/components/com_languages/src/Controller/LanguagesController.php#L51-L67

**Comment by brianteeman** [comment]
The count is not a count of languages installed on the site
The count is a count of the content languages on the site

**Comment by richard67** [comment]
> The count is a count of the content languages on the site

To be more precise: Published content languages.

@Kostelano Please check and report back if the number is shown correctly when you have more than 1 content language published. Thanks in advance.

**Comment by brianteeman** [comment]
> > The count is a count of the content languages on the site
> 
> To be more precise: Published content languages.
> 

ofc - should have used more precise language

> @Kostelano Please check and report back if the number is shown correctly when you have more than 1 content language published. Thanks in advance.

that's how I concluded it was for content languages ;')

**Comment by Kostelano** [comment]
Yes, these are content languages.

But, one way or another, something needs to be fixed. For example, a link that should lead to content languages, and not to install languages.

**Comment by brianteeman** [comment]
yes the link is wrong

**Comment by alikon** [comment]
please test #40671
