### ISSUE TITLE
Joomla! Input Cookie Class

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40651]
libraries/src/Input/Cookie.php

**$secure**    Indicates that the cookie should only be transmitted over a secure HTTPS connection from the client. When set to TRUE, the cookie will only be set  if a secure connection exists. On the server-side, it's on the programmer  to send this kind of cookie only on secure connection (e.g. with respect to $_SERVER["HTTPS"]).

**$httpOnly**  When TRUE the cookie will be made accessible only through the HTTP protocol. This means that the cookie won't be accessible by scripting languages, such as JavaScript. This setting can effectively help to reduce identity theft through XSS attacks (although it is not supported by all browsers).

For both of these we set a value of **false** if it is not explicitly set as **true**. Shouldn't we always be setting this as true and be secure by default.

There _may_ be a b/c issue with such a change but security fixes always beat b/c issues iirc

@joomla/security-leads

**Comment by dgrammatiko** [comment]
>  pretty much every cookie, that is not security-related (like the session cookie is - that's why it has that flag set).

The session cookie has the same value as the CSRF which is widely available (if a page has a properly instantiated a Form) which invalidates (in most cases) the argument. In sort, I'm supporting the idea for a default true value.

My 2c

**Comment by SniperSister** [comment]
> The session cookie has the same value as the CSRF 

Nope. The CSRF token is a random token which is stored in the session, it does NOT have the same value.

**Comment by brianteeman** [comment]
closed due to lack of interest
