### ISSUE TITLE
Configured Captcha is not being used for the login form

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#40659]
### Steps to reproduce the issue
1. Configure at least one Captcha plugin and have it selected for use
2. Open login form

### Expected result
A Captcha is visible and required to login

### Actual result
No Captcha is required
![image](https://github.com/joomla/joomla-cms/assets/32301627/8f688fda-3db9-4782-9c67-402bfd0f751b)

### Additional comments
The Captcha is only used for the remind, reset and registration forms, but the login form should receive it as well not only for consistency but also to prevent malicious bots from spamming login attempts.

**Comment by alikon** [comment]
should'nt be more secure to use MFA for login ? instead of Captcha ?

**Comment by Chaosxmk** [comment]
It's less of a security issue and more of an anti-spam issue.

**Comment by brianteeman** [comment]
This really should be closed. It is working as intended and as stated above there is no spam issue
