### ISSUE TITLE
mod_articles_news | exclude_current // REVERSE

### ISSUE THREAD

**Issue by reilldesign** [joomla/joomla-cms#40661]
### Describe the solution you'd like

The module allows to exclude the current article. This is very helpful!
But the reverse case is also very important. How can I give the current article its own class to style it?

**Comment by drmenzelit** [comment]
That is not really an issue, but a question that should be posted in the forum (https://forum.joomla.org).

**Comment by reilldesign** [comment]
It was meant more as a feature request. If the current post gets a css class like .current it could be styled. This is handy for a menu like list view.

**Comment by rdeutz** [comment]
Can be done with an overwrite, no need for a core enhancement.
