### ISSUE TITLE
[4.3.2] fa-spin definitions > Why?

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#40663]
Hi guys, 
Joomla 4.3.x is running with Font Awesome 5.x

Into the Joomla .../media/system/css/joomla-fontawesome.css file I can find seven fa-spin definitions (eight "spin").

But, as far as I know, fa-spin in Font Awesome does not exist, while there is the [fa-spinner](https://fontawesome.com/v5/iconsfa-spinnerspinner?f=classic&s=regular).

Are you sure that the fa-spin definitions are still needed ?

**Comment by ReLater** [comment]
I find exactly one `.fa-spin` definition in `media\system\css\joomla-fontawesome.css`. And also in `media\system\css\joomla-fontawesome.css` (the original!).

```
.fa-spin, .icon-spin {
  -webkit-animation: fa-spin 2s infinite linear;
          animation: fa-spin 2s infinite linear;
}
```

All other fa-spin finds define the animation.

`@keyframes fa-spin {...}`

- With `fa-spin` class you can make any icon rotate. if you add this class additionally.
- In contrast, the `fa-spinner` class has its predefined icon that rotates.

**Comment by joomleb** [comment]
@ReLater 
Thank you very much for your detailed explication  with which I'm been able to find the [Font Awesome page explication](https://fontawesome.com/v5/docs/web/style/animate)

**Comment by chmst** [comment]
Obviously not a joomla core issue. Thanks @ReLater
