### ISSUE TITLE
Language .ini files in parent templates take preference over those in child templates.

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#40660]
### Steps to reproduce the issue

Create a child template of Cassiopeia.
Add file tpl_cassiopeia_mytemplate.ini containing the following line:
TPL_CASSIOPEIA_XML_DESCRIPTION="My Cassiopeia child template."
Create / edit a child template style.

### Expected result

TPL_CASSIOPEIA_XML_DESCRIPTION uses the child template text.
All other language constants use the Cassiopeia text.

### Actual result

TPL_CASSIOPEIA_XML_DESCRIPTION displayed as expected.
All other language constants displayed without translation.

### System information (as much as possible)

PHP 8.2

### Additional comments

**Suggested fix**
File: com_templates/src/Model/StyleModel.php
Replace lines 399-402 with...

   // Default to using parent template language constants
   $lang->load('tpl_' . $data->parent, $client->path)
        || $lang->load('tpl_' . $data->parent, $client->path . '/templates/' . $data->parent);
   // Optional overrides for child template language constants
   $lang->load('tpl_' . $template, $client->path)
        || $lang->load('tpl_' . $template, $client->path . '/templates/' . $template);

**Comment by BrainforgeUK** [comment]
Test - install a child template from a zip file.
See screenshot for actual result.
![screen shot 2023-05-27 at 08 32 25](https://issues.joomla.org/uploads/1/927f529247b4df88490a76059d551334.png)
See screenshot for expected result.
![screen shot 2023-05-27 at 08 32 25](https://issues.joomla.org/uploads/1/e7409a40cc0762318d252a27ff3f47ed.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40660">issues.joomla.org/tracker/joomla-cms/40660</a>.</sub>

**Comment by alikon** [comment]
please test #40665 

you don't need to open an issue if have already a pr
