### ISSUE TITLE
Can't insert youtube video into article

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#40673]
### Steps to reproduce the issue
Create a new article
select insert->media->put url into "source" box.
hit save.
Video does not display.

### Expected result

video included in article

### Actual result

no video shown

### System information (as much as possible)
J! 4.3.1

### Additional comments
This worked fine in J! 3.9

**Comment by brianteeman** [comment]
Unable to replicate

**Comment by brianteeman** [comment]
Works fine for me https://www.youtube.com/watch?v=ul3mcXMX0gA&ab_channel=LearnJoomla4

**Comment by N6REJ** [comment]
iframes were blocked.
