### ISSUE TITLE
"Joomla" OR "Joomla!"

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#40672]
This issue concerns the correct use of the Joomla! name. Seeing the treadmark policies, they indicate to always use it with an exclamation point (https://drive.google.com/file/d/0By_CBGYGBbU8SWg1bUlrUHhRb2M/edit?resourcekey=0-MtMv9wSayXoOEkk5BLenSQ page 15)

If we search form " joomla " (without the !) in the release files we have 1378 matches across 656 files.

Some of these are in the language files:
site: 9 matches across 7 files
administrator: 161 matches across 64 files

(I do not exclude that the numbers are greater as there may be occurrences without spaces before and after the text)

Shall we fix them all?
Do we want to correct them only in the language file?

**Comment by Razzo1987** [comment]
@Trademark & Licensing Team (@bayareajenn @sebastienlapoux @jeckodevelopment)

**Comment by brianteeman** [comment]
Please see https://manual.joomla.org/docs/user-interface-text/joomla_name_usage where you will find your answer

**Comment by zero-24** [comment]
Closing as the question is solved

**Comment by Razzo1987** [comment]
So this is correct?
![image](https://github.com/joomla/joomla-cms/assets/906604/356e9a19-c64a-48a3-ad11-8b3b1713bc86)
