### ISSUE TITLE
[4.3] Custom template thumbs visible only if template is inheritable

### ISSUE THREAD

**Issue by pioada** [joomla/joomla-cms#40688]
### Steps to reproduce the issue
Create custom template.
Add template thumbs to media/templates/site/{template name}/images.

### Expected result
Template thumb should be visible in template manager (backend)

### Actual result
"preview" text is displayed instead of the thumb.

### System information (as much as possible)
Joomla 4.3.2

### Additional comments
In administrator/com_templates/src/Service/HTML/Templates.php in line 55 it first checks if template is inheritable. I think this part of code should be change. It should only check if thumb file exists in media folder.

**Comment by dgrammatiko** [comment]
> Add template thumbs to media/templates/site/{template name}/images.

The path `media/templates/site/{template name}/images` is **only** used by modern templates (ie supporting child templates). Legacy templates for B/C reasons still expect their thumbs in the `templates/{template name}/`

**Comment by alikon** [comment]
closing as expected behaviour

**Comment by pioada** [comment]
Exactly. I'm creating a modern template based on Cassiopeia. My template wont be inheritable.
In my templateDetail.xml file inheritable is 0 (<inheritable>0</inheritable>). Thumbs is not show.
Thumbs is displayed only if I set inheritable = 1.
This is because in file administrator/com_templates/src/Service/HTML/Templates.php in line 55 it first check if this is inheritable template and inheritable is TRUE. If not then it go to next condition which is "old" template (legacy).
In first condition it should check if thumb exists in "new" location because inheritable is not required and can be omitted in "new" templates.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40688">issues.joomla.org/tracker/joomla-cms/40688</a>.</sub>

**Comment by dgrammatiko** [comment]
> My template wont be inheritable.

That's not how it works. By definition modern templates **ARE** inheritable

**Comment by pioada** [comment]
Ah, ok. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40688">issues.joomla.org/tracker/joomla-cms/40688</a>.</sub>
