### ISSUE TITLE
[4.3] 404 when quickicons for disabled components are active

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#40684]
### Steps to reproduce the issue
Disable components, for example com_contact. Activate  the icon for this component in the quickicon module. 

### Expected result
Quickicons for disabled components are hidden 

### Actual result
![grafik](https://github.com/joomla/joomla-cms/assets/1035262/1b506051-7ec9-4c01-bae8-5125f8d14ce7)

Click on one of these icons. The result: 404 - component not found

### System information (as much as possible)
See #38267

**Comment by brianteeman** [comment]
> Quickicons for disabled components are hidden

The problem with that occurs when a user sets a component to show in the quick icon module and then doesnt know why the icon is not displayed

**Comment by chmst** [comment]
True. A solution could be: disabling the button and add an information "Component disabled"

**Comment by brianteeman** [comment]
is that any different to the 404?

**Comment by brianteeman** [comment]
Is this what you would want?

![image](https://github.com/joomla/joomla-cms/assets/1296369/9d7f3981-a0ed-4753-8125-a008bd8ac076)

**Comment by chmst** [comment]
I thought about that and no, I don't see any benefit when links to non-existing items are visible.

**Comment by chmst** [comment]
Please test #40715
