### ISSUE TITLE
Joomla 4.3.2 - Storage Engine memory disabled issue

### ISSUE THREAD

**Issue by bellu** [joomla/joomla-cms#40697]
### Steps to reproduce the issue
Create a new article and save it.

### Expected result
A new article in the CMS.

### Actual result
Save failed with the following error: Storage engine MEMORY is disabled (Table creation is disallowed).
My website on Google Cloud raises this error every time, that i try to save an article in the backend.

I found that the Indexer is trying to use a table with engine MEMORY, but on Google Cloud this kind of engine is not allowed.

administrator/components/com_finder/src/Indexer/Indexer.php

`990:                 $db->setQuery('ALTER TABLE ' . $db->quoteName('#__finder_tokens') . ' ENGINE = MEMORY');`
`994:                 $db->setQuery('ALTER TABLE ' . $db->quoteName('#__finder_tokens_aggregate') . ' ENGINE = MEMORY');`

administrator/components/com_finder/sql/install.mysql.sql

`360:    ENGINE=MEMORY DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;`
`379:   ENGINE=MEMORY DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;`

### System information (as much as possible)
Joomla 4.3.2
Hosting Google Cloud

### Additional comments

I think should be provided a fallback, like InnoDB engine, in case that the memory engine is not allowed.

**Comment by brianteeman** [comment]
Closing as the reported issue was answered and the op did not reply
