### ISSUE TITLE
Media manager doesn't respect path attribute

### ISSUE THREAD

**Issue by laoneo** [joomla/joomla-cms#40690]
### Steps to reproduce the issue
- Go to /administrator/index.php?option=com_media&path=local-images:/sampledata
- Type in the url /administrator/index.php?option=com_media&path=local-images:/banners

### Expected result
The media manager shows the contents of the banners directory.

### Actual result
The media manager redirects to the sampledata directory.

### System information (as much as possible)
Probably be a regression of #40013 as it happens only on Joomla 4.3.2.

### Additional comments
Ping @dgrammatiko.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40691 . Thanks in advance.

**Comment by laoneo** [comment]
Another one https://github.com/joomla/joomla-cms/pull/40704.
