### ISSUE TITLE
Error 500 on user registration (J4.3.2)

### ISSUE THREAD

**Issue by RedStar87** [joomla/joomla-cms#40696]
### Steps to reproduce the issue

Open the J4 user registration page: https://inspection.amtsystems.net/inscription

### Expected result

Joomla registration component should display the right registration page

### Actual result

Page cannot be found with "Error 500 Internal Server Error" accordingly the Firefox Inspector console.

### System information (as much as possible)

Joomla 4.3.2, PHP 8.0

### Additional comments

The registration is activated in user parameters, the menu item is published with "Public"  access. The .htaccess is well configured.

**Comment by brianteeman** [comment]
Maybe this will help you

https://inspection.amtsystems.net/inscription?template=cassiopeia

 Attempt to assign property "link" on null

**Comment by RedStar87** [comment]
> Maybe this will help you
> 
> https://inspection.amtsystems.net/inscription?template=cassiopeia
> 
> Attempt to assign property "link" on null

Hello Brian!

The menu item is well published and I cleared cache few times already (Joomla including and browser). I re-created a new menu item but still the same... The user rights are the same - no changes there. Don't know how to solve that...

Thanks again.
Max.

**Comment by richard67** [comment]
@RedStar87 Do you use the "User - Terms and Conditions" plugin described here https://docs.joomla.org/Chunk4x:Extensions_Plugin_Manager_Edit_User_Group/en in section "User - Terms and Conditions" at the bottom, and if so, have you selected or created an article linked in the "Terms & Conditions Article" field in the plugin's settings? If so: Maybe that article has been deleted in the mean time?

That's just my guess, and I might be wrong. I guess so because the error happens in file "[ROOT]/plugins/user/terms/src/Field/TermsField.php" in line 49 https://github.com/joomla/joomla-cms/blob/4.3-dev/plugins/user/terms/src/Field/TermsField.php#L49 .

**Comment by obuisard** [comment]
I agree with Richard @richard67, the article for the terms and conditions is set but may no longer exist.
Check the User plugin 'Terms and Conditions' and the article you have selected.
This error will happen if the article has been deleted (after being trashed) and is used by the plugin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40696">issues.joomla.org/tracker/joomla-cms/40696</a>.</sub>

**Comment by RedStar87** [comment]
Hello everyone.

In fact it was the missing **"Terms & Conditions"** article inside the plugin.

@richard67 @obuisard Thanks a lot for your support. I really appreciate your help and the great Joomla community.

Have a nice week.

Kind Regards,
Max.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40696">issues.joomla.org/tracker/joomla-cms/40696</a>.</sub>

**Comment by RedStar87** [comment]
@brianteeman Thank you too. Appreciate it.

This topic can be closed now.

Max.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40696">issues.joomla.org/tracker/joomla-cms/40696</a>.</sub>
