### ISSUE TITLE
The Media Manager does not support PDF files

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#40692]
### Steps to reproduce the issue

- Add pdf to the Allowed Extensions.
- Add pdf to the Valid document extensions (file types).
- Open a post, select a text (link text) and upload a PDF via Media, try to insert a link.

### Expected result
The PDF is uploaded, it appears in the Media manager, but cannot be linked.

### Actual result
The PDF is uploaded, it appears in the Media manager, but cannot be linked.

### System information (as much as possible)
J.4.3.2, PHP 8.1

### Additional comments
A media manager should, as the name says, be able to manage media, i.e. also files other than pictures.

**Comment by brianteeman** [comment]
Pdf work fine. Please see https://www.youtube.com/watch?v=TyZucw2ljK4

**Comment by drmenzelit** [comment]
Which editor are you using? How are you trying to insert the link?

**Comment by Quy** [comment]
@hytsch No problem uploading/linking an PDF using Media. Please advise the editor you are using as requested previously.

**Comment by Quy** [comment]
Closing due to no response with additional info.
