### ISSUE TITLE
J 4.3.4, character issues in aliases

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#40703]
### Steps to reproduce the issue

Create a new article.
Enter the article title: Türkçe

_We have the same problem when we create a new menu link._

### Expected result

Alias: tuerkce

### Actual result

Alias: turkce

### System information (as much as possible)

Joomla! 4.3.2
PHP Version 8.1.18
And other information:
[systeminfo-2023-06-01T21_43_11+03_00.txt](https://github.com/joomla/joomla-cms/files/11628457/systeminfo-2023-06-01T21_43_11%2B03_00.txt)

### Additional comments

It is possible to get the same problem with letters such as Ö Ç Ü.

Images showing the problem:

![alias_j4 3 2](https://github.com/joomla/joomla-cms/assets/423588/e19ada3a-ffa8-45cc-b006-3a50e7df133e)

![alias_j4 3 2-new](https://github.com/joomla/joomla-cms/assets/423588/4c330007-29bb-44ae-8f12-46a0b8ebf4e6)

Regards

**Comment by alikon** [comment]
did you experienced this issue starting from 4.3.2 ? or it was already present in earlier versions?

**Comment by joomlaphp** [comment]
> 4.3.2'den itibaren bu sorunu yaşadınız mı? veya önceki sürümlerde zaten mevcut muydu?
Hi @alikon 
Yes, I had this problem in earlier versions as well and users had it. When a user from the J support group wrote this problem again, I checked the problem and it continues.

**Comment by joomlaphp** [comment]
> did you experienced this issue starting from 4.3.2 ? or it was already present in earlier versions?

Hi @alikon
Yes, I had this problem in earlier versions as well and users had it. When a user from the J support group wrote this problem again, I checked the problem and it continues. To be honest I forgot to report the problem.

**Comment by Hackwar** [comment]
Do you have the turkish language installed and is the content set to the turkish language?

**Comment by joomlaphp** [comment]
> Do you have the turkish language installed and is the content set to the turkish language?

Yes, https://issues.joomla.org/tracker/joomla-cms/36164#event-654187, we will do the issue that I opened before, as there is no other choice :) . Thanks again.

**Comment by brianteeman** [comment]
The solution is as described in the link you reference https://issues.joomla.org/tracker/joomla-cms/36164#event-654187 You need to have a localise.php in the language pack with the correct transliteration rules. An example is present in that issue

I just checked and the transliteration rules are not present.

@tecpromotion can you point the translator of the turkish language pack to this issue and #36164

As this can not be fixed in core (only the language pack) this should be closed.
