### ISSUE TITLE
[Atum] Same width for Quickicons

### ISSUE THREAD

**Issue by wwwiiimmm** [joomla/joomla-cms#40701]
Quickicons have different widths when the modules have different number of icons.

**Example 1:**
If 1 icon is visible in the 3rd party module the icon stretches to full width.

**Example 2:**
When giving the QI-modules more space, i.e. by toggling the side menu.
The 3 icons in the System module and the 4 icons in the Notifications module have different widths.

Also see attachment...

The width is styled by _quickicons.scss
On line 8 you will find:
grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));

Replacing 'auto-fit' with 'auto-fill' all quickicons get the same width no matter how many icons there are.
![screen shot 2023-06-01 at 12 30 59](https://issues.joomla.org/uploads/1/e058b8fd73ac36d81e58cb6f2affb06c.jpg)

**Comment by drmenzelit** [comment]
Would you create a pull request for this?

**Comment by N6REJ** [comment]
@wwwiiimmm the file your looking for is ```build/media_source/templates/administrator/atum/scss/blocks/_quickicons.scss```  This is ony available in github dev branches. which in this case would be 4.3-dev.
You'll need to run "npm ci" after the change to see it changed.

**Comment by N6REJ** [comment]
closed as we have a pr
