### ISSUE TITLE
Form class : showon on fields don't run over the fields group

### ISSUE THREAD

**Issue by rolandalsace** [joomla/joomla-cms#40708]
### Steps to reproduce the issue
When called in a fields group a showon wich call over this group don't run
In J3 it was correct

Exemple :
			&lt;field 
				name="chrono_live"
				type="radio"
				class="btn-group btn-group-yesno"
				label="COM_GSKIEPREUVES_CHRONOLIVE_LABEL"
				description="COM_GSKIEPREUVES_CHRONOLIVE_DESC"
				value="1"
				default="0"
			&gt;
				&lt;option value="1"&gt;JYES&lt;/option&gt;
				<option value="0"&gt;JNO&lt;/option&gt;
			&lt;/field&gt;
			
			<fields name="chrono_params" > 
				<field 
					name="live_typeclt" 
					type="list" 
					default="off" 
					class="grp-chrono-live"
					id="live_typeclt"  
					label="COM_GSKIEPREUVES_CHRONOLIVE_TYPECLT_LABEL" 
					description="COM_GSKIEPREUVES_CHRONOLIVE_TYPECLT_DESC"
					showon="chrono_live:1"
					>
	  				<option value="off">COM_GSKIEPREUVES_CHRONOLIVE_TYPECLT_OPTION_OFF</option>
	  				<option value="mch">COM_GSKIEPREUVES_CHRONOLIVE_TYPECLT_OPTION_MCH</option>
				</field>
				
			</fields>
			<field 
				name="chrono_live_info"
				type="note"
				class="grp-chrono-live alert alert-info" 
				label="COM_GSKIEPREUVES_CHRONOLIVEINFO_LABEL" 
				description="COM_GSKIEPREUVES_CHRONOLIVEINFO_DESC"
				showon="chrono_live:1"
			 />

The showon of named fiel live_typeclt don't run.

**Comment by brianteeman** [comment]
Is this still an issue. There have been a lot of bug fixes to showon since your report
