### ISSUE TITLE
[5.x] Install languages

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#40718]
it is currently not possible to install any languages in joomla 5 making it hard to truly test

**Comment by zero-24** [comment]
There are two ways extend the existing 4.x file and allow them still to be installed as within J5 its IIRC still used. On the other way would be to implement an full 5.0 language XML, generate it here: https://github.com/joomla-extensions/pkg_languagepack/blob/master/com_languagepack/site/models/export.php#L65 

In the past we had a few packages pre-tested and manually allowed while they of course are also not 100% translated into J5 yet. But I would like to let that be done by @HLeithner as he is also one of the few with the required access to the infrastructure. ;)

**Comment by HLeithner** [comment]
We still need to figure out a workflow for crowdin with 2 major versions.

**Comment by brianteeman** [comment]
at a minimum we need to have one language available for j5 or we can't test

**Comment by brianteeman** [comment]
Reminder that languages still can not be tested with 5.0.0 alpha 2

**Comment by HLeithner** [comment]
Only the installation from the server right? as mention earlier, codesprint is this weekend and I hope I find sometime to create a workflow for joomla 5 translations with @tecpromotion

**Comment by brianteeman** [comment]
Sorry never heard of any codesprint?

**Comment by HLeithner** [comment]
it's for TUF so not directly related for languages but since stefan is there we hopefully find sometime to fix the language stuff

**Comment by brianteeman** [comment]
Still not possible to test anything to do with languages in Joomla 5 :(

**Comment by HLeithner** [comment]
Why not? https://downloads.joomla.org/language-packs/translation5 doesn't work?

**Comment by brianteeman** [comment]
![image](https://github.com/joomla/joomla-cms/assets/1296369/3bc4839f-c79d-4c6c-8b73-382ee93527a5)

![image](https://github.com/joomla/joomla-cms/assets/1296369/58ebce89-9a72-45b9-8ac1-457cd9c9db7f)

**Comment by HLeithner** [comment]
ah ok install from web, I will check this thanks for the reminder

**Comment by brianteeman** [comment]
sending another reminder. Am I the only person testing Joomla?

**Comment by brianteeman** [comment]
> Why not? https://downloads.joomla.org/language-packs/translation5 doesn't work?

nope - that just gives a 404

**Comment by zero-24** [comment]
It does not give a 404 for me, I'm missing something?
![image](https://github.com/joomla/joomla-cms/assets/2596554/0ba8ce56-af1b-487a-baa8-816f8d5b0b6f)

The 5er Update Server has also been pepared but have to be tested, deployed and the SQL Update written: https://github.com/joomla-extensions/pkg_languagepack/pull/106/files

**Comment by zero-24** [comment]
Ah ok that looks actually like an access issue than. You can download the latest release for now here for testing if you want to: https://github.com/joomlagerman/joomla/releases/tag/5.0.0v1-alpha2

But the permission issue has to be fixed too you are right.
