### ISSUE TITLE
Checking Extension Upgrades

### ISSUE THREAD

**Issue by rgtr** [joomla/joomla-cms#40723]
### Steps to reproduce the issue
Click the extensions notification upgrade with some upgrades required. Its slow.
BEFORE extensions are shown, click system. 
A green tick appears erroneously.

### Expected result
a list of extensions to upgrade

### Actual result
a Green tick !

Checking for extensions is very quick and displays those needed quickly.

### System information (as much as possible)
PHP Built On 	Linux web6.lhr.stackcp.net 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64
Database Type 	mysql
Database Version 	10.4.26-MariaDB-log
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	No
PHP Version 	8.1.17
Web Server 	Apache
WebServer to PHP Interface 	fpm-fcgi
Joomla! Version 	Joomla! 4.3.2 Stable [ Bora ] 30-May-2023 16:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0 

### Additional comments
Been happening for a while.

**Comment by brianteeman** [comment]
Impossible to comment without knowing the list of extensions

**Comment by Quy** [comment]
losing due to no response with additional
