### ISSUE TITLE
Display Media

### ISSUE THREAD

**Issue by rgtr** [joomla/joomla-cms#40722]
### Steps to reproduce the issue
Create a sub/sub/sub/ directory e.g. images\sigplus\seasons\spring_23
Upload some images to the lowest level

### Expected result
Images are there but are not shown

### Actual result
Images are there but are not shown

### System information (as much as possible)

PHP Built On 	Linux web6.lhr.stackcp.net 3.10.0-1160.88.1.el7.x86_64 #1 SMP Tue Mar 7 15:41:52 UTC 2023 x86_64
Database Type 	mysql
Database Version 	10.4.26-MariaDB-log
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	No
PHP Version 	8.1.17
Web Server 	Apache
WebServer to PHP Interface 	fpm-fcgi
Joomla! Version 	Joomla! 4.3.2 Stable [ Bora ] 30-May-2023 16:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0 

### Additional comments
Image intensive site. https://tdocplus.co.uk/linnpark

**Comment by brianteeman** [comment]
Unable to replicate

![image](https://github.com/joomla/joomla-cms/assets/1296369/c1f3b4c1-faf2-461b-998c-2bef680a3be7)

**Comment by obuisard** [comment]
Can't replicate either, with or without the thumbnails enabled.
Do you get any error in the browser console?
Do you get any error when the site is in debug mode with error reporting set to 'maximum'?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40722">issues.joomla.org/tracker/joomla-cms/40722</a>.</sub>

**Comment by DavidBoggitt** [comment]
Bit of a stab in the dark, but I think I've had something like this and the issue was with Akeeba Admin Tools. Do you have that installed?

**Comment by Quy** [comment]
Closing due to no response with additional info.
