### ISSUE TITLE
Error 403 when i upload a picture in admin

### ISSUE THREAD

**Issue by IndianSpirit** [joomla/joomla-cms#40730]
### Expected result
I found a bug in Joomla 4.3.2, this bug is present since this version.

I can't upload pictures in the admin area, in contact, in some modules, in some components. The media manager works.

A "modal" window opens with an Error 403.
The error has only existed since version 4.3.2, before everything worked.

Tested on 3 different websites, with different browsers. My hoster says it's not the server.

Can someone understand the error?

### System information (as much as possible)
Joomla 4.3.2
PHP 8.1

### Additional comments
I hope I've entered everything correctly, sorry, I'm posting here for the first time...

**Comment by chmst** [comment]
> I hope I've entered everything correctly, sorry, I'm posting here for the first time...

Don't worry - we'll try to find out what happens. I cannot replicate the issue - at least in com_contact and in my own modules  I can upload images without problems and in other places as well. 

Could you inspect your webspace and check permissions on your media folders?

**Comment by brianteeman** [comment]
also please post a screenshot of the 403 error message - it might help identify the source

**Comment by IndianSpirit** [comment]
Hello, that was probably a mistake by my provider. Everything worked fine this morning.
I have to ask what was going on there.
sorry...

**Comment by alikon** [comment]
please close the issue

**Comment by alikon** [comment]
thanks @IndianSpirit
