### ISSUE TITLE
Option "including ip adress of sender" to the contact form

### ISSUE THREAD

**Issue by ilya800918** [joomla/joomla-cms#40747]
### Is your feature request related to a problem? Please describe.

Internet scams, frauds. When one person write from the different names and emails from one or similar ip.

### Describe the solution you'd like

Maybe it should to add option "including ip adress of sender" to the contact form settings? To get an email with ip adress of my conversation partner.

**Comment by rdeutz** [comment]
Closing this, it seems to my quite unclear what the reason of the request is and what the solutio will make better.
