### ISSUE TITLE
Advanced search : URL links on multi-language documents (language = all) don't work

### ISSUE THREAD

**Issue by Pierre-2023** [joomla/joomla-cms#40740]
This is my first contribution, and I'm sorry if my bug report isn't quite up to your standards.

### Steps to reproduce the issue

Joomla 4.3.2 advanced search links problem : URL links on multi-language documents (language = all) doesn't work, for example with edocman (https://joomdonation.com) or with DJ-Catalog2 (https://dj-extensions.com).

The link for documents in French + German doesn't work if the language of the target document is "all". With Joomla 3.10.x (before the migration) everything worked perfectly 

### Expected result

In English: mon-site-joomla/en/download/formular/document-pdf
In French: mon-site-joomla/fr/**telechargement/formulaires**/document-pdf

### Actual result

In English: mon-site-joomla/en/download/formular/document-pdf
In French: mon-site-joomla/fr/**download/formular**/document-pdf

### System information (as much as possible)

Joomla 4.3.2 (french)
PHP 8.1.19
MySQLi 10.5.20-MariaDB-log 

### Additional comments

Copy of the response from edocman support :
« Hi, To solve this kind of problem, you should create the same document for all available languages (on your site), this is an issue of Joomla Finder component, currently, document "CITIZEN K16" has language is all, **and it will have the issue with Joomla search finder**. 
Thanks
Dam »

**Comment by alikon** [comment]
@joomdonation  can you please check too

**Comment by joomdonation** [comment]
@alikon The extension is maintained by a different developer in in my team. I will talk to him to find a solution. Personal, if it works fine for Joomla core articles, then the problem comes from the extension itself and developer will have to find a solution for it.

**Comment by Hackwar** [comment]
This isn't really a Joomla problem, but issues in the third party extension. Closing this one.
