### ISSUE TITLE
[5.0] Icon for dashboard changed in fontawesome

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#40748]
### Steps to reproduce the issue
The icon we used for dashboard doesn't exist any more in fontawesome. The new one makes the the menu bar look a bit frayed.

### Actual result

![grafik](https://github.com/joomla/joomla-cms/assets/1035262/bea82263-c6e9-4447-83ae-26be2092f885)

**Comment by brianteeman** [comment]
yes I spotted that as well. 

grid-horizontal should work

**Comment by chmst** [comment]
Shululd work yes. There seem to be many grid icons. It would be best to have something similar as now, So we don't need new screenshots for ducumentation.

**Comment by chmst** [comment]
Better grid icons are not free, and in free icons I cannot find a better replacement. Closing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40748">issues.joomla.org/tracker/joomla-cms/40748</a>.</sub>

**Comment by Fedik** [comment]
They looks really ugly to me. My first thought was that it is a bug in icon rendering.
I suggest: `fa-bars`, `fa-barcode`, `fa-list`, `fa-folder`, `fa-layer-group`

**Comment by chmst** [comment]
Same here. But I tried different icons - and when I asked users - everyone had other opinion.

**Comment by brianteeman** [comment]
grip is probably the closest to the icon in j3 - 6 blobs instead of 4

![image](https://github.com/joomla/joomla-cms/assets/1296369/e14def10-e4a0-4e77-a162-228c45de4519)

**Comment by chmst** [comment]
The grip  - yes,. Looks always a bit ragged but better than now.

**Comment by Fedik** [comment]
`fa-bars`
![Screenshot 2023-08-20_12-14-00](https://github.com/joomla/joomla-cms/assets/1568198/477948fb-a846-457a-840c-38d57035c560)

`fa-bars-staggered`
![Screenshot 2023-08-20_12-24-19](https://github.com/joomla/joomla-cms/assets/1568198/999ae648-9db5-4a5f-9eab-a98e3774b889)

`fa-brands fa-joomla`
![Screenshot 2023-08-20_12-27-28](https://github.com/joomla/joomla-cms/assets/1568198/c6cf6b6f-74a3-4b8f-a1a5-5359641ce9bc)

`fa-compress`
![Screenshot 2023-08-20_12-22-26](https://github.com/joomla/joomla-cms/assets/1568198/5561df08-9edf-4aed-a8a0-9ca68b418290)

`fa-align-justify`
![Screenshot 2023-08-20_12-25-37](https://github.com/joomla/joomla-cms/assets/1568198/cf6468b0-c3f3-4bad-8b70-09dc8b3ac688)

`fa-square`
![Screenshot 2023-08-20_12-12-25](https://github.com/joomla/joomla-cms/assets/1568198/bc933272-c0b8-4aa9-a820-6ac60d361037)

`fa-square-full`
![Screenshot 2023-08-20_12-18-07](https://github.com/joomla/joomla-cms/assets/1568198/f13c3b66-ff1b-4ed7-bd7c-16dee6072f7a)

`fa-folder`
![Screenshot 2023-08-20_12-12-45](https://github.com/joomla/joomla-cms/assets/1568198/3bef8740-4fc6-4d25-b2f6-d0dfb0dbfce2)

`fa-grip`
![Screenshot 2023-08-20_12-20-09](https://github.com/joomla/joomla-cms/assets/1568198/9fcc8de0-f78e-4837-84b1-1fc81d9951e7)

`fa-layer-group`
![Screenshot 2023-08-20_12-13-24](https://github.com/joomla/joomla-cms/assets/1568198/1e0a8322-9dda-40e9-8a52-5e4f1e65a066)

`fa-barcode`
![Screenshot 2023-08-20_12-14-22](https://github.com/joomla/joomla-cms/assets/1568198/9acde085-0993-40ed-a7bc-fb539a908ef1)

I like:
```
fa-bars
fa-brands fa-joomla
fa-compress
fa-layer-group
```

And `barcode` looks interesting :)

Pick your favorites, and in the end we will count which is more preferable. 
Also anyone can suggest an icon.

**Comment by brianteeman** [comment]
they are all nice icons but do they convey the meaning of a dashboard

**Comment by chmst** [comment]
This is also my question. I've asked in the UX channel

**Comment by Fedik** [comment]
It only about visual perception. 
And it is very subjective: how a dashboard should look like.

The idea is to pick your icons (not only from my very "subjective list"), and let's see what people like more from this.
Btw, `fa-microsoft` looks like a good icon for it  :smile: but we cannot pick it.

**Comment by HLeithner** [comment]
if you don't like the new one please import the old one as svg and add it to the icon library, I personal would like to have svg sprites but iirc fedir or dimitries are not so happy how it could be implemented (can't remember exactly the reason and person^^)

**Comment by crystalenka** [comment]
Isn't border-all pretty close? Maybe?

I'm in favor of importing the old one because even though we call it a dashboard, it's more of a quick access page. A dashboard would provide more info than what we currently do, imho, so unless we add functionality for like some kind of analytics or something on the page, better to stick with what people know and not mess with expectations too much. :) thank you @chmst for bringing it up!

**Comment by angieradtke** [comment]
Changing a familiar icon always involves a new learning process.  The new font- awesome icon reminds me too much of the CSS grid.  The other suggestions already have a different meaning.
So either we use a svg see attachment black and white, or we think of something completely new that is more in line with the dashboard -thought.  Why does Dimitris want to stay with Font-Awesome ?

All the best  Angie

![dashboard](https://github.com/joomla/joomla-cms/assets/1172403/20eef9df-a156-4949-a6b3-3446ea3c52c0)
![dashboard_white](https://github.com/joomla/joomla-cms/assets/1172403/ff926dfc-179a-4da6-92e4-53da770bf665)

**Comment by chmst** [comment]
I like the idea of having "our" dashboard icon as svg (and maybe other important icons too).

**Comment by HLeithner** [comment]
yesterdays maintainer meeting decided to import the v5 images as svg till we have a better solution for an iconmanager (or similar)

@chmst is in charge for the PR

**Comment by chmst** [comment]
Please test https://github.com/joomla/joomla-cms/pull/41443
