### ISSUE TITLE
joomla 3.10.11 pls fix padch

### ISSUE THREAD

**Issue by jooomla** [joomla/joomla-cms#40749]
### Steps to reproduce the issue

Warning: session_start(): Failed to read session data: user (path: /var/lib/lsphp/session/lsphp73) in /home/radio-guru.ru/public_html/libraries/joomla/session/handler/native.php on line 260
Error: Failed to start application: Failed to start the session **when site no have database see this error ))**

0 syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) maybe changed when change php version

### System information (as much as possible)

centos 7 joomla 3.10.11

### Additional comments

ye

**Comment by zero-24** [comment]
Please check the running PHP Version: https://freek.dev/1598-how-to-check-which-version-of-php-you-are-running and make sure you are running an supported version for Joomla 3.10. When you need more help please reach out to your host or the Joomla Forum: https://forum.joomla.org

Closing here :)
