### ISSUE TITLE
Honor update server changelog URL

### ISSUE THREAD

**Issue by ron4mac** [joomla/joomla-cms#40756]
### Is your feature request related to a problem? Please describe.
When the is no 'changelogurl' in the local manifest but there IS a 'changelogurl' in the update server manifest, it is ignored.

### Describe the solution you'd like
At the very least, respect the presence of the changelog as pointed to by the update server. There could be a case for the update server pointer to actually have more priority.

**Comment by richard67** [comment]
Thanks for reporting this issue. However, it seems that it has been reported before. See #40056 . Closing this one here as duplicate. Feel free to reopen it if you think this is wrong.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40756">issues.joomla.org/tracker/joomla-cms/40756</a>.</sub>

**Comment by ron4mac** [comment]
Thanks, Richard. It's not quite the same issue, though. If an author updates a package, the update manager should use the changelog pointed to by the update server. As it is now, no changelog can be viewed if there is no changelogurl in the database manifest, or if there is a url it could be the wrong one because the server update points elsewhere.

**Comment by richard67** [comment]
@ron4mac Yes, not exactly the same, but to me it seemed to cover your issue, too, I.e. if that issue is solved, yours would be solved, too. If that is wrong you can reopen your issue on GitHub, or ask me to do so.

**Comment by Mika17420** [comment]
there seems to be another problem with UTF-8 encoding in the changelog which does not react. newline after accents

**Comment by Mika17420** [comment]
Sole with <![CDATA[ ]]>
`<item><![CDATA[Ajout de la colone "<b>Cote</b> dans l'affichage "<b>Liste des documents avec critères de recherche </b>".]]></item>`
