### ISSUE TITLE
[4.3.4 & 5.0] Pagination issue

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#40750]
### Steps to reproduce the issue
1. create tags Tag1 and Tag2
2. create articles so that only with Tag1 is greater than 5 and with both tags too
3. create a Menu1 type Tagged Items for Tag1 and Menu2 type Tagged Items for both tags
4. in the frontend select Menu1 and display pagination
5. select second page in pagination of Menu1

### Expected result
the second page of menu1 opened

### Actual result
the second page of menu2 opened

**Comment by 1inkin** [comment]
example page with this issue:
https://fstec.ru/eksportnyj-kontrol/dokumenty-ek

![screen shot 2023-06-10 at 18 39 56](https://issues.joomla.org/uploads/1/f49296b93e6593e951f1a24b6747dc03.jpg)![screen shot 2023-06-10 at 18 39 57](https://issues.joomla.org/uploads/1/bcdad90c235a3dba7f87028ea03c7be3.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40750">issues.joomla.org/tracker/joomla-cms/40750</a>.</sub>

**Comment by 1inkin** [comment]
the issue appears when:
1. create Menu1 with items of Tag1
2. create another Menu2 with items of Tag1 and Tag2 with a full match.
3. after that pagination of Menu1 from the second page will be directed to the Menu2 page<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40750">issues.joomla.org/tracker/joomla-cms/40750</a>.</sub>

**Comment by 1inkin** [comment]
Joomla 4.3.4. Issue is still relevant<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40750">issues.joomla.org/tracker/joomla-cms/40750</a>.</sub>

**Comment by Quy** [comment]
Please test #42162. Thanks.
