### ISSUE TITLE
Forgot password - No e-mail for user with access to backend?

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#40757]
### Steps to reproduce the issue

- Add a registered user to an (extra) usergroup with access rights to the backend.
- Enable login on the frontend.
-  Go to the frontend and use the 'forgot password' link to request a password reset.

### Expected result
- Receive an email with the reset code / link

### Actual result
- No mail has been send.

### System information (as much as possible)
Joomla 4.3.2
PHP 8.1.18

### Additional comments

The frontend does show a message 'An email has been send...' but no mail is received. When the user is only 'registered' without having access rights to the backend the mail is send / received OK.

I guess this message is always shown to anyone who enters any email address for security reasons so it won't reveal if a user with the entered email exists.

But in this case an email should be send? Or is it not possible to change a password for a user that also has backend access?

Am I correct in assuming there is no 'forgot password' functionality from the backend login page?

**Comment by brianteeman** [comment]
I can not replicate the reported problem. Are you sure that you dont have a security extension installed that is preventing it. I know that admintools has an option to disable the ability to reset a password in this way.

**Comment by jjnxpct** [comment]
We do have Admin Tools installed. In the firewall there is an option 'Disable password reset for specific User Groups' but this is set to NO. 

But I did a check with the admintools firewall disabled. (rename the plugin file) And after that the email was send OK. So I might need to check some other settings in Admin Tools or contact them to figure this out. 

Thanks for this Brian! 

So i guess this issue is solved here.

**Comment by zero-24** [comment]
Closing thanks, when you found it please post here too for people finding that issue later.

**Comment by jjnxpct** [comment]
The Admin Tools developers confirmed this was an issue with their extension. And they able to fix this. I tested it on our site with a development version of Admin Tools and the issue was solved. So this will probably be available in the next Akeeba Backup release.
