### ISSUE TITLE
Conditional custom fields with showon (front-end)

### ISSUE THREAD

**Issue by HDInfautre** [joomla/joomla-cms#40762]
Hello
Since version 4.3, a new feature allows you to hide fields on the administration side only: https://github.com/joomla/joomla-cms/pull/39051

There's an external plugin that does the same thing on the front-end.
The request is to merge or create the ability to assign showon to the front-end

REgards

**Comment by obuisard** [comment]
A PR is on the way, it will address the display of custom fields in the frontend (subforms included).
Some testing remains to be done for the contact form custom fields that are added to emails.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40762">issues.joomla.org/tracker/joomla-cms/40762</a>.</sub>

**Comment by obuisard** [comment]
Check https://github.com/joomla/joomla-cms/pull/41104 for a solution. Please test!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40762">issues.joomla.org/tracker/joomla-cms/40762</a>.</sub>

**Comment by alikon** [comment]
closing as we have a pr #41104
