### ISSUE TITLE
Media Manager bypasses browser cache (.htaccess)

### ISSUE THREAD

**Issue by Mich-es** [joomla/joomla-cms#40787]
### Steps to reproduce the issue
Create a folder with more than 500 images in the Joomla Media Manager. Add the following to the .htaccess:

Oops, I can't insert source code here? Use a picture instead 

![grafik](https://github.com/joomla/joomla-cms/assets/58422824/7f3a3edb-824f-4322-8324-21a635580848)

Connect your PC to a smartphone with a poor internet connection!

### Expected result
I now expect that after calling up the folder once, all images/graphics are saved in the browser cache

### Actual result
J4 attaches a timestamp to "EVERY" image/graphic, which bypasses the .htaccess rules. 

### System information (as much as possible)
PHP 8.1
10.5.18-MariaDB
J4.3.2

### Additional comments
I love Joomla, but I work a lot on the road and have image folders with a lot of content. I recently became desperate because I could no longer select images while on the road. The connection to the internet was bad and the Joomla media manager completely reloaded the images every time. Working was not possible because the media manager always bypassed the settings in the .htaccess with the timestamp behind each graphic. 

Fortunately, I was able to get help:
https://forum.joomla.de/thread/18614-der-media-manager-in-j4-ist-suboptimal-timestamp-bei-bilder/?postID=132406#post132406

Suggestion: Why don't you just add a timestamp only to the pictures/graphics that were actually edited? Then it will work again and I think that will not only reduce the traffic on the Internet, but will also be a great thing for many people.

**Comment by brianteeman** [comment]
The comments in the german language forum post from @bembelimen and @SniperSister are more helpful than using the local cache

**Comment by richard67** [comment]
Closing as having a pull request. Please test #40893 . Thanks in advance.
