### ISSUE TITLE
Article URLs (A, B and C) open in new window instead in parent window

### ISSUE THREAD

**Issue by Daan-VL** [joomla/joomla-cms#40789]
### Steps to reproduce the issue
In an article, on the **Images and Link** tab, under **Link A** (or B or C) select **Open in parent window** as the URL target window.

### Expected result
When viewing the page with the links (Link A, B or C), and clicking the link, I expect to open the specified URL in the parent window.

### Actual result
URL opens in a new tab in the browser.

### System information (as much as possible)
Client: Windows 10 Home 22H2; browser: MS Edge 114.0.1823.51 (Officiële build) (64-bits), both in Dutch.

### Additional comments
The "URL Target Window" option also provides a value: Use Global. However, in Common settings I cannot find a global setting for this option.

**Comment by brianteeman** [comment]
The global setting can be found in the second tab of the article options

I am unable to replicate your reported error. For the avoidance of doubt can you confirm with the default cassiopeia template

**Comment by Daan-VL** [comment]
I cannot replicate the problem any longer. Changed to the default template and the problem seems to be vanished. Changed back to my corrent template, and the problem does not occur anymore.
Meanwhile I also found the the options for the URL Target Window in the Global setting's Article options. I must have had a black-out for a moment... Sorry for any inconvenience.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40789">issues.joomla.org/tracker/joomla-cms/40789</a>.</sub>

**Comment by richard67** [comment]
Closing as not a core issue. Details see previous comment.
