### ISSUE TITLE
Can the "Media" editor button be used to change an image?

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#40786]
This is kind of a follow up to this https://github.com/joomla/joomla-cms/issues/37054

As far as I see, with TinyMCE we have two Image buttons.
- The image icon in the toolbar, which allows for a simple image URL to be entered, but without the ability to browse and select an image.
- And the "Media" editor button under "CMS Content", which allows to enter the Joomla Media Manager, select an image etc.

Now, the problem is: what about if you want to change an image that you've already added to the article? For example, you want to select another one.

Normally, you would click on the image, and then click on the "Image" button to change it. But this only opens the "simple" image URL interface that allows you to change the URL.

Is there no way to click on an image already inserted, and use the Media Manager to change the image? This can be done easily in JCE, but it seems there is no way to do this in TinyMCE?

**Comment by brianteeman** [comment]
> Is there no way to click on an image already inserted, and use the Media Manager to change the image?

Just click on the already inserted image and then use the media manager again to select a different image.

![images](https://github.com/joomla/joomla-cms/assets/1296369/8607d574-978c-4348-b586-5766eb4c7f7d)

**Comment by brianteeman** [comment]
Not sure why there is a "feature" label on this as it already exists

**Comment by alikon** [comment]
lack of knowledge 😨

**Comment by AndySDH** [comment]
Well, it's not exactly the same, as when you re-click the Media button, the file explorer does not start from the folder of the image already inserted, but instead, it starts from the last location you used it.

That would be a nice improvement, if in this case the Media Manager started from the same path of the already inserted image that you're trying to edit (that's what JCE does as well).

**Comment by PhilippSPOTTERON** [comment]
Struggling with Tiny MCE Usability, too.
The image button is unusable (yes there is the dropdown, but it confuses clients aka bad usability)
Same also for the link button > no selection of e.g. Joomla Menu items.

Are there any plugins, etc that fix Tiny MCE's lack of (basic) usability features?
