### ISSUE TITLE
Banners 'Select By Keyword' Not Functional

### ISSUE THREAD

**Issue by cozioscob** [joomla/joomla-cms#40987]
### Problem identified
Banner component & module 'Select By Keyword' not working. e.g. adding keyword 'all' to an article and adding the same keyword to a banner module and related banner results in no banner showing.
I believe this is due to article keywords functionality being removed as it's no longer necessary for SEO. However this is necessary for the Banner component keyword targetting to behave correctly. Can we reinstate some form of keyword functionality?
Keywords '_are_' working for related articles functionality which is promising, just not for banners. 

### Proposed solution
Reinstate keyword functionality for banners

### Open questions
Is this possible?

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/39016

**Comment by richard67** [comment]
Closing as having a pull request. Please test #39016 . Thanks in advance.

**Comment by cozioscob** [comment]
https://github.com/joomla/joomla-cms/pull/39016 Not working for me either on my live site running 4.3.2 or a fresh install of 4.3.2 or 4.4.0-alpha2-dev. e.g. [here](http://keswickwebdesign.co.uk/test/index.php/test-menu)
Turning off Select By Keyword in the banner module shows banner, turning on (with keyword 'test' setup in the article and for the banner)

**Comment by MacJoom** [comment]
@cozioscob #39016 has not been merged yet - you could test this which would advance the process

**Comment by cozioscob** [comment]
> @cozioscob #39016 has not been merged yet - you could test this which would advance the process

To be clear, I've:
1) Replaced BannersModel.php, ArticleModel.php, ArticlesModel.php, SiteApplication.php, BannersHelper.php from 39016 on my working site, no success (in fact it broke my site layout)

2) Replaced BannersModel.php, ArticleModel.php, ArticlesModel.php, SiteApplication.php, BannersHelper.php in a fresh install of 4.3.2 with no change to banner visibility using keyword setup

3) Replaced BannersModel.php, ArticleModel.php, ArticlesModel.php, SiteApplication.php, BannersHelper.php in a fresh install of 4.4.0-alpha2-dev with no change to banner visibility using keyword setup

**Comment by MacJoom** [comment]
@cozioscob You can try with the packages from here: https://ci.joomla.org/artifacts/joomla/joomla-cms/4.3-dev/39016/downloads/66712/ - i tested this and it works fine.

**Comment by MacJoom** [comment]
Thank you very much - could you please open a new issue for the "No client" problem - i can then look into it. A screenshot of the 1064 error would also be helpful

**Comment by cozioscob** [comment]
Here you go. [#40996](https://github.com/joomla/joomla-cms/issues/40996)
