### ISSUE TITLE
Banners 'Select By Keyword' When Using 'No Client' Not Functional

### ISSUE THREAD

**Issue by cozioscob** [joomla/joomla-cms#40996]
### Steps to reproduce the issue
Banner component & module 'Select By Keyword' not working if there is No Client selected. e.g. adding keyword 'all' to an article and adding the same keyword to a related banner while choosing 'No Client' in the module results in no banner showing.

### Expected result
Banner is shown when 'No Client' is selected and Select By Keyword is selected

### Actual result
Banner is not shown

### Additional comments
As per conversation in [#40987](https://github.com/joomla/joomla-cms/issues/40987) and initially raised in [#39016](https://github.com/joomla/joomla-cms/pull/39016)
Error with no client selected is
Warning: Undefined array key 4 in ----/public_html/components/com_banners/src/Model/BannersModel.php on line 231
Also showing a 1064 error on the homepage only of my particular site, screengrab attached (other pages no error unless debug is on and max error reporting, banner just doesn't show.
<img width="706" alt="Screenshot 2023-06-21 at 13 18 43" src="https://github.com/joomla/joomla-cms/assets/137033923/2b039690-0374-437e-9dbb-424e789e316d">

**Comment by MacJoom** [comment]
I can confirm the issue - apart from the 1064 error.

**Comment by alikon** [comment]
@MacJoom  so we can close this one for #40996 ?

**Comment by MacJoom** [comment]
yesss please

**Comment by alikon** [comment]
please test #39016
