### ISSUE TITLE
Joomla4 Bug: Cannot find user with ID: 67 on saving article

### ISSUE THREAD

**Issue by StefBakker** [joomla/joomla-cms#41008]
### Steps to reproduce the issue
1. Create 2 user accounts.
2. Create an article with user account 1.
3. Delete user account 1.
4. Edit article that was created by account 1.
5. Error occurs: 
Invalid field: Created by
Cannot find user with ID: 67

### Expected result
Save the article. Because users cannot save the article anymore.

### Actual result
Error message: 
Invalid field: Created by
Cannot find user with ID: 67

And article is not saved.

### System information (as much as possible)
CMS: Joomla 4.3.2
PHP: 8.2.0

**Comment by Quy** [comment]
See draft PR #40269.

**Comment by richard67** [comment]
See also other PR #41048 .

**Comment by brianteeman** [comment]
This should be closed as there are several pull request to address it

**Comment by Hackwar** [comment]
Closing since we have 2 PRs for this.
