### ISSUE TITLE
[4.3.2] User Time Zone - Default doesn't seem to work in frontend

### ISSUE THREAD

**Issue by travisrisner** [joomla/joomla-cms#41003]
### Steps to reproduce the issue

- Set up a user in the admin and enable MFA, ensure timezone set to Default
- Login to the frontend and go to an edit profile view

### Expected result

- Added and last used times for the active MFA should show in the timezone of the website I would assume (since the user was set to default), but that doesn't seem to be the case unless I edit the user in the admin and specifically set their timezone.

**Comment by chmst** [comment]
Not quite sure if I understand your issue correctly. Could you please give a real example? Which time zone is your default time-zone?

**Comment by travisrisner** [comment]
I have my default timezone in global site settings set to America/Chicago. 

I have the user's timezone set to Use Default

When I view something on the frontend logged in as that user (like MFA last used time), it's not using the America/Chicago timezone to display the time of last MFA use, etc to the user.

**Comment by Hackwar** [comment]
I created a PR. Please test #43191. Since we have a PR, I'm closing this issue.
