### ISSUE TITLE
Missing batch function for tags

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#41029]
### Steps to reproduce the problem
Create a tag X. Mark some other tags, go to batch tasks, try to subordinate the marked tags to tag X.

### Expected result
The "Batch processing for selected tags" dialogue offers the possibility to select a tag, just as is the case with posts and categories, with menu items.

### Actual result
The "Batch processing for selected keywords" dialogue does not offer the possibility to subordinate tags to another tag.

### System information (as far as possible)
Joomla 4.3.2, PHP 8.1

### Additional comments
The tag component has (unfortunately) hardly evolved since its introduction. This is a pity because tags are a powerful tool for optimising accessibility. If the component had at least the Joomla-typical range of functions, this would already be a great gain! :)

**Comment by Quy** [comment]
Duplicate #23304?

**Comment by alikon** [comment]
i think so 
plus we have a pr #38583

so i'll close this one in favour of https://github.com/joomla/joomla-cms/issues/23304

@hytsch thanks for reporting
