### ISSUE TITLE
Smart Search: search by category (Adv search) does not filter by language

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#41038]
### Steps to reproduce the issue
Create a smart search page enabling advanced search in a multi-language site

### Expected result
the list of Category (to restrict search) shows just categories in current language

### Actual result
All categories are shown, also in non current language

### System information (as much as possible)
Joomla 4.3.2 PHP 8.1

**Comment by richard67** [comment]
Closing as having a pull request. See #41470.
