### ISSUE TITLE
Show a module with option "On all pages except those selected" not working

### ISSUE THREAD

**Issue by egloffmark** [joomla/joomla-cms#41036]
### Steps to reproduce the issue

I am using Joomla! 4.3.2 Stable and when I like to show a module with the menu assignment option "On all pages except those selected" it get always shown regardless which menu items I have selected. I tested it with the default "Cassiopeia" theme.

1. Go to the "Content > Sites Modules" configuration
2. Open the module "Breadcrumbs"
3. Set the "Menu Assignment", select "On all pages except those selected"  and deselect the Menus where the module has not to be shown e.g. "Home"
4. Save the changes

![image](https://github.com/joomla/joomla-cms/assets/7382336/d174375b-9cbc-4c60-8a6c-38781296ab7a)

![image](https://github.com/joomla/joomla-cms/assets/7382336/8862d864-9eda-4f08-a444-c6354c60d7ed)

### Expected result
The modules should not be shown for menu items if they have not been assigned

### Actual result
The modules is always shown

### System information (as much as possible)
Joomla! 4.3.2 Stable
Xampp Windows with PHP 8.2.4

### Additional comments
This issue seems not to working since I Joomla know, since version 2.x. Why got this never fixed?

**Comment by egloffmark** [comment]
Apologize misinterpreted the settings, so it is working fine.

**Comment by brianteeman** [comment]
Maybe this will help https://brian.teeman.net/joomla/896-modules-nowhere
