### ISSUE TITLE
[5.0] "node build/build.js --versioning" fails due to missing file "admin-users-mail.min.js"

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#41066]
### Steps to reproduce the issue

On a clean, current 5.0-dev branch, run `php ./build/build.php --remote=HEAD --exclude-gzip --exclude-bzip2`.

### Expected result

Build suceeds.

### Actual result

```
> joomla@5.0.0 versioning
> node build/build.js --versioning

[Error: ENOENT: no such file or directory, lstat '/home/richard/lamp/public_html/joomla-cms-5.0-dev/build/tmp/1687872657/media/com_users/js/admin-users-mail.min.js'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/home/richard/lamp/public_html/joomla-cms-5.0-dev/build/tmp/1687872657/media/com_users/js/admin-users-mail.min.js'
}
`npm run versioning` did not complete as expected.
```

### System information (as much as possible)

Current 5.0-dev branch where PR #40302 has been merged.

### Additional comments

The problem seems to be that the `build/media_source/com_users/joomla.asset.json` file still contains the assets. They haven't been removed with #39374 from that file and so were not added back with #39431 , and later with #40385 they were not marked as deprecated.

The question is now if we can remove them from the `build/media_source/com_users/joomla.asset.json` without such a deprecation.

The documentation PR for the deprecation has not been merged yet: https://github.com/joomla/Manual/pull/98 .

**Comment by richard67** [comment]
Possibly it just needs to remove the assets from build/media_source/com_users/joomla.asset.json ... but the problem is they were not marked as deprecated. @HLeithner What shall we do?

**Comment by HLeithner** [comment]
I fixed this already locally in the alpha2 packages
