### ISSUE TITLE
[5.x] WebAuthn Login Fails

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#41072]
### Steps to reproduce the issue

1. Set Web Authentication for a user and set it to standard method
2. Log out from backend
3. Try to log-in again with this user and click on button "Validate with your Authenticator"

### Expected result
The user gets logged in after entering his PIN (in my case Windows Hello)

### Actual result

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/4d6fb285-09a8-4007-b2a1-0d39959455da)

### System information (as much as possible)
Joomla  5.0 alpha 2
Mozilla Firefox
Windows Hello

**Comment by HLeithner** [comment]
Thanks for the report, I was able to replicate the issue.

**Comment by HLeithner** [comment]
you can fix it for your current installation by adding back:

`use Joomla\CMS\Factory;` 
in the file:
[plugins/multifactorauth/webauthn/src/Extension/Webauthn.php](https://github.com/joomla/joomla-cms/commit/a8a2dc29a527f9256ab9be5c9b20e375d5d9602a#diff-69c1e4f628be1e26e220a064a4de8ecb65b500d6eeabf87aa3a6d19ddee696d2)

**Comment by richard67** [comment]
@dautrich Please test #41073 . Before testing, revert the workaround provided by Harald.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #41073 . Thanks in advance.
