### ISSUE TITLE
single dash character removed when word joomla is used in alias field (menu)

### ISSUE THREAD

**Issue by propellerhuvud** [joomla/joomla-cms#41074]
### Steps to reproduce the issue
In Menu Manager (Main menu), create a new menu item with header "Homepage in Joomla".
Type of item in this case was Joomshaper PageBuilder, and an arbitrary page selected.
Let Joomla! create the alias field automatically.
When the Menu item is saved, the alias shown is: "homepage-injoomla" -> the "dash" preceeding the word joomla has been removed.
A workaround is to place two dash characters between "in" and "joomla" -> (homepage-in--joomla), which results in a proper alias string, after the second dash has been erroneously removed by the system.
It does not matter what words I use before the word joomla, the effect is still the same.

### Expected result
"homepage-in-joomla"

### Actual result
"homepage-injoomla"

### System information (as much as possible)
Found in Joomla! 4.3.2 Stable [ Bora ]
Accessed with Firefox 114.0.2 on MacOS Big Sur 11.7.8
Site runs on Linux/Litespeed, PHP 8.0.28, MySQL 10.5.21-MariaDB-cll-lve

### Additional comments
The language I use is Swedish, hope you can understand the screenshot. :smile:![screen shot 2023-06-27 at 20 41 19](https://issues.joomla.org/uploads/1/4d579598e557e05a0dc85a9697339918.png)

**Comment by ChristineWk** [comment]
Cant' confirm:
![screen shot 2023-06-27 at 21 07 02](https://issues.joomla.org/uploads/1/bc713f863bfe5be94355fecbc9223cc6.jpg)

![screen shot 2023-06-27 at 21 09 45](https://issues.joomla.org/uploads/1/a7cadd85e26eb5736520f2f65dbadd32.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41074">issues.joomla.org/tracker/joomla-cms/41074</a>.</sub>

**Comment by propellerhuvud** [comment]
Thank you Christine for testing!
Don't know if it's some included library causing this for me, was suprised to see it at all.
I will keep testing some more on other sites/configurations.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41074">issues.joomla.org/tracker/joomla-cms/41074</a>.</sub>

**Comment by chmst** [comment]
Cannot confirm either. Maybe it is your language in combination of a menu extension?

**Comment by Quy** [comment]
Closing for now. If you can reproduce it, then this can be reopened. Thanks.
