### ISSUE TITLE
RSS Feeds not working in 4.3.2 System.Xml.XmlException

### ISSUE THREAD

**Issue by SysAdminWVS** [joomla/joomla-cms#41080]

**Comment by SysAdminWVS** [comment]
When I load the rss feed link (index.php?format=feed&type=rss) to a feed reader (like feedbro extension of firefox) with joomla version 4.3.2 I get and error "Invalid XML".

On my self-programmed XML-Reader I get an xml exception :smile: 

28.06.2023 13:41:39 System.Xml.XmlException: Es sind mehrere Stammelemente vorhanden. Zeile 2, Position 2.
   bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
   bei System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   bei System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   bei System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   bei System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
28.06.2023 13:42:09 private void ProcessFeed(object source, ElapsedEventArgs e) System.EventArgs

(There are more than one root node)

I need urgently a bug fix.

Best Regards

Steffen




<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41080">issues.joomla.org/tracker/joomla-cms/41080</a>.</sub>

**Comment by SysAdminWVS** [comment]
When I do the same on Joomla 3.10.11 everything works fine!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41080">issues.joomla.org/tracker/joomla-cms/41080</a>.</sub>

**Comment by brianteeman** [comment]
please use the forum for support

**Comment by SysAdminWVS** [comment]
Hello richard67,

thank you for your hint.

At this time the site is an intranet site and has no connection to the internet.

I will create a nat to it and then test the feed on the validator.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41080">issues.joomla.org/tracker/joomla-cms/41080</a>.</sub>

**Comment by SysAdminWVS** [comment]
Hello richard67,

I've just created access to the intranet site from the internet.

Here are the results of the feed validator

This feed is valid, but interoperability with the widest range of feed readers could be improved by implementing the following recommendations.

    line 10, column 155: Self reference doesn't match document location [help]

        ... a4/index.php?format=feed&amp;type=rss"/>
                                                     ^

    line 49, column 0: description should not contain object tag (4 occurrences) [help]

        			<guid isPermaLink="true">https://webwvs.wvs-basa.de/intranet/joomla4/inde ...


I think the problem is on the "self" link:

href="https://webwvs.xxxx.de/intranet/joomla4/intranet/joomla4/index.php?format=feed&amp;type=rss"

intranet/joomla4/intranet/joomla4 -> this is duplicated!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41080">issues.joomla.org/tracker/joomla-cms/41080</a>.</sub>

**Comment by SysAdminWVS** [comment]
Here is the complete atom tag

<generator>Joomla! - Open Source Content Management - Version 4.3.2</generator>
<atom:link rel="self" type="application/rss+xml" href="https://webwvs.xxx.de/intranet/joomla4/intranet/joomla4/index.php?format=feed&amp;type=rss"/>
<language>de-de</language>

(I changed the domain name for security)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41080">issues.joomla.org/tracker/joomla-cms/41080</a>.</sub>

**Comment by wilsonge** [comment]
@Hackwar seems routing related for non-html outputs

**Comment by SysAdminWVS** [comment]
Hello again,

I try to get it work for 3 weeks now.

My application was originally designed to use the System.Xml.Linq class to read the rss feed.

string feedUrl = "https://feedurl of joomlal";

XDocument rssfeedxml;
XNamespace namespaceName = "http://www.w3.org/2005/Atom";
rssfeedxml = XDocument.Load(feedUrl);

If I run the application I get an Exception :

System.Xml.XmlException: Es sind mehrere Stammelemente vorhanden. Zeile 2, Position 2.
bei System.Xml.XmlTextReaderImpl.Throw(Exception e)
bei System.Xml.XmlTextReaderImpl.ParseDocumentContent()
bei System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
bei System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
bei System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
bei System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)


So I tried to switch to using System.ServiceModel.Syndication class

XmlReaderSettings settings = new XmlReaderSettings();
settings.ConformanceLevel = ConformanceLevel.Fragment;
var reader = XmlReader.Create(feedUrl,settings);
var feed = SyndicationFeed.Load(reader);

if I run this code, I get also an Exception :

System.Xml.XmlException: Das Element mit dem Namen 'br' und dem Namespace '' ist kein zulässiges Feedformat.
bei System.ServiceModel.Syndication.SyndicationFeed.Load[TSyndicationFeed](XmlReader reader)

If I switchback the feedurl to joomla 3 everything works fine again on both classes.
I also tried different other feeds of the internet, working also fine with my .net code.
 
If I use the joomla 4 rss-link in FeedReader 3 the feed is loaded.
If I download the xml file using the rss-feed link and do a xml-analysis in notepad++ no problems are found.

 That drives me crazy. What is the problem on this?

Why the joomla 3 xml-Code is working and the joomla 4 not?

 best regards

**Comment by SysAdminWVS** [comment]
Hello,

I hope I coould find the problem between the xml code of Joomla 3.11.12 and 4.3.3.

I've downloaded the xml-Code and compared it with noptepad++. The only relevant diifference between the code is, that in the <description> tag if there is <![CDATA> a line break than in 3.11.12 there is a <CR><LF> in 4.3.3 there is only a <LF>. 
May be that lets my code crushing?

Next I will try to load the xml code from file not from uri and will see if it works if i replace in 4.3.3 the <LF> with <CR><LF>.

I hope someone can tell me, how to patch it in joomla, so I could test it directly with the syndication module.

best regards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41080">issues.joomla.org/tracker/joomla-cms/41080</a>.</sub>

**Comment by SysAdminWVS** [comment]
Hello,

I hope I coould find the problem between the xml code of Joomla 3.11.12 and 4.3.3.

I've downloaded the xml-Code and compared it with noptepad++. The only relevant diifference between the code is, that in the decsription tag if there is <![CDATA> a line break than in 3.11.12 there is a CR/LF in 4.3.3 there is a LF only  .
May be that lets my code crushing?

Next I will try to load the xml code from file not from uri and will see if it works if i replace in 4.3.3 the with .

I hope someone can tell me, how to patch it in joomla, so I could test it directly with the syndication module.

best regards<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41080">issues.joomla.org/tracker/joomla-cms/41080</a>.</sub>

**Comment by SysAdminWVS** [comment]
Hello,

today I updated to Joomla 4.4 and the issue is still not solved. Due to security I need to update frrom joomla 3 to 4 but I can't as long as the problem is not fixed.
My question is, if there is anybody working to fix this problem, or if there is a workarround on this.

Please let me know how I can go ahead.

best regards

**Comment by SysAdminWVS** [comment]
Hello,

I have updated to joomla 4.4.2 the code of my rss-client-app.

When I try to download the rss feed to string

using (WebClient client = new WebClient())
{
    string xmlContent = client.DownloadString(feedUrl);
    SyndicationFeed feed = SyndicationFeed.Load(System.Xml.XmlReader.Create(new System.IO.StringReader(xmlContent)));
.
.
.
}

I get this in the xmlContet var 

"<br />\n<b>Deprecated</b>:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in <b>C:\\inetpub\\wwwroot\\intranet\\joomla4\\libraries\\vendor\\joomla\\application\\src\\Web\\WebClient.php</b> on line <b>286</b><br />\n<br />\n<b>Deprecated</b>:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in <b>C:\\inetpub\\wwwroot\\intranet\\joomla4\\libraries\\vendor\\joomla\\application\\src\\Web\\WebClient.php</b> on line <b>289</b><br />\n<br />\n<b>Deprecated</b>:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in <b>C:\\inetpub\\wwwroot\\intranet\\joomla4\\libraries\\vendor\\joomla\\application\\src\\Web\\WebClient.php</b> on line <b>292</b><br />\n<br />\n<b>Deprecated</b>:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in <b>C:\\inetpub\\wwwroot\\intranet\\joomla4\\libraries\\vendor\\joomla\\application\\src\\Web\\WebClient.php</b> on line <b>295</b><br />\n<br />\n<b>Deprecated</b>:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in <b>C:\\inetpub\\wwwroot\\intranet\\joomla4\\libraries\\vendor\\joomla\\application\\src\\Web\\WebClient.php</b> on line <b>298</b><br />\n<br />\n<b>Deprecated</b>:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in <b>C:\\inetpub\\wwwroot\\intranet\\joomla4\\libraries\\vendor\\joomla\\application\\src\\Web\\WebClient.php</b> on line <b>301</b><br />\n<br />\n<b>Deprecated</b>:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in <b>C:\\inetpub\\wwwroot\\intranet\\joomla4\\libraries\\vendor\\joomla\\application\\src\\Web\\WebClient.php</b> on line <b>304</b><br />\n<br />\n<b>Deprecated</b>:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in <b>C:\\inetpub\\wwwroot\\intranet\\joomla4\\libraries\\vendor\\joomla\\application\\src\\Web\\WebClient.php</b> on line <b>307</b><br />\n<br />\n<b>Deprecated</b>:  stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in <b>C:\\inetpub\\wwwroot\\intranet\\joomla4\\libraries\\vendor\\joomla\\application\\src\\Web\\WebClient.php</b> on line <b>310</b><br />\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\n\n<rss version=\"2.0\" xmlns:atom=\"http://www.w3.org/2005/Atom\">\n\t<channel>
.
.
.

Thats why my rss app is not working. It seems to be a bug in Joomla?

Any suggestions welcome.

Best regards

Steffen<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41080">issues.joomla.org/tracker/joomla-cms/41080</a>.</sub>

**Comment by Hackwar** [comment]
Thanks for your response. It seems as if you are using PHP 8.2? Can you check if you are sending a HTTP_USER_AGENT? Looking at the code, it seems as if that is empty on your system, which creates this error.

**Comment by Quy** [comment]
https://github.com/joomla-framework/application/pull/121 fixes this issue.

**Comment by SysAdminWVS** [comment]
Hello Quy,

I replaced the WebClient.php with the fixed Version

https://github.com/joomla-framework/application/blob/797ece2d3a52442d463010842df5f50f6ecc188d/src/Web/WebClient.php

I run my application again and looked at the returned XML-String. 

The problem is solved using the bug fix.

It is so sad to me, that it needs more tnan a half year to find the reason and get the solution.

great thanks and best regards

Bl0ckS1z3

**Comment by alikon** [comment]
closing as  fixed upstream
