### ISSUE TITLE
[5.0] Smart Search  -  Button Throws JS Error

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#41089]
### Steps to reproduce the issue

1. In backend, go to Components - Smart Search - Index
2. Click button Maintenance and click on "Clear Index"
3. OK on the "Are you sure ...."
4. Click button "Start the Indexer"

### Expected result
A pop-up window appears to show the progress of the indexing process

### Actual result
Button "Start the Indexer" doesn't work. In devtools, a JS error can be seen. Backend freezes.

![Indexer_Start_Button](https://github.com/joomla/joomla-cms/assets/7933215/e77804f0-261b-4aca-9445-224f3f854e31)

### System information (as much as possible)
J5 alpha 2
PHP 8.2
Mozilla firefox

### Additional comments
Clicking on the "Index" button in the top bar of the window works as desired.

**Comment by Hackwar** [comment]
We have a PR with #41094. Closing this one.
