### ISSUE TITLE
[4.x] createTable strips \\ so cannot load Joomla\\CMS\\Table\\

### ISSUE THREAD

**Issue by Flowman** [joomla/joomla-cms#41084]
### Steps to reproduce the issue

I am trying to use this code to load the User table.

$table = Factory::getApplication()->bootComponent('com_users')->getMVCFactory()->createTable('User', 'Joomla\\\\CMS\\\\Table\\\\');

But the createTable strips all \\\\ and the prefix becomes JoomlaCMSTable and that wont work.

Old school code like this works but it is deprecated and will be removed.

$table = Table::getInstance('User', 'Joomla\\\\CMS\\\\Table\\\\')

We should be able to do the same through the createTable function.

### Expected result

The table should be loaded.

### Actual result

Null is returned as the class name is stripped.

### System information (as much as possible)

PHP Version | 8.0.28
nginx/1.23.1
Joomla! 4.3.2 Stable [ Bora ] 30-May-2023 16:00 GMT

**Comment by richard67** [comment]
@Flowman I think you misunderstand the meaning of the 2nd parameter `$prefix` of the `createTable` function. The prefix should be according to the application name, e.g. "Administrator" or "Site".

You can see that here in the `createTable` function's code https://github.com/joomla/joomla-cms/blob/4.3-dev/libraries/src/MVC/Factory/MVCFactory.php#L215-L234 and here in the `getClassName` method https://github.com/joomla/joomla-cms/blob/4.3-dev/libraries/src/MVC/Factory/MVCFactory.php#L260-L273 .

In your example this means you should use:

`$table = Factory::getApplication()->bootComponent('com_users')->getMVCFactory()->createTable('User', 'Administrator');`

To avoid deprecated logs (if switched on) and be prepared for the future, you should also pass the database object with the optional 3rd parameter `$config`:

`$table = Factory::getApplication()->bootComponent('com_users')->getMVCFactory()->createTable('User', 'Administrator', ['dbo' => $db]);`

with `$db` being the database object. In a CMS plugin you can just use `$this->db`.

Let me know if this works for you and we can close this issue.

Thanks in advance.

**Comment by Flowman** [comment]
This return NULL

$table = Factory::getApplication()->bootComponent('com_users')->getMVCFactory()->createTable('User', 'Administrator');

It is because the user table is in the Library\src\Table location and not in the com_user component. 

That is why if you look anywhere in the code that requires the User table it still uses the legacy function.

$table = Table::getInstance('User', 'Joomla\\\\CMS\\\\Table\\\\')

Will the User table be moved in Joomla 5.0?

**Comment by laoneo** [comment]
Use the old way with getInstance as the user table is still in the main namespace in libraries. For now there is no other way and it will not be moved in 5.

**Comment by stell** [comment]
We also have tables in our library. Is this still the best way to use them?
`$table = Table::getInstance('User', 'Mylib\\Library\\Table\\MyTable')`

**Comment by joomdonation** [comment]
As `Table::getInstance` was deprecated, I would use the following code :

- If the table belong to a component, use the recommended syntax:

```php
Factory::getApplication()->bootComponent('...')->getMVCFactory()->createTable($name, $prefix, $config)
```

- Otherwise, use `new` directly

```php
$table = new \Joomla\CMS\Table\User($db);
```

You could get $db from container like:

```php
$db = Factory::getContainer()->get(DatabaseInterface::class);
```
Or if inside a model

```php
$db = $this->getDatabase();
```

I think nothing more we can discuss here, so I'm closing this issue. Feel free to open if you think there is still something to discuss.
