### ISSUE TITLE
[4] mod_articles_news needlessly calls content.prepare on article introtext

### ISSUE THREAD

**Issue by ManuelHu** [joomla/joomla-cms#41086]
### Steps to reproduce the issue
* Have a site with at least one enabled content plugin that does some sort of content replacement and adds some scripts (i.e. image gallery tools, video embedding...)
* Create an article that contains some content that triggers the content plugin (i.e. adds scripts to the output)
* Add a `mod_articles_news` module to any position
* Select the category of the article created above
* Disable the showing of the intro text in the module options
* Observe the HTML output in the frontend: The intro text is _not_ shown (as expected), but scripts that were added are in the output

### Expected result
* Content is only `content.prepare`d if it is actually selected to be shown

### Actual result
* Content is always `content.prepare`d, even if the introtext is not displayed.

### System information (as much as possible)
Joomla 4.3

### Additional comments

In `mod_articles_category`, the preparation only happens if the option to show the introtext is set:
https://github.com/joomla/joomla-cms/blob/507922c74e5ea76504e2ba98aac70e3124dbcce8/modules/mod_articles_category/src/Helper/ArticlesCategoryHelper.php#L274-L277

In `mod_articles_news`, there is no such condition
https://github.com/joomla/joomla-cms/blob/507922c74e5ea76504e2ba98aac70e3124dbcce8/modules/mod_articles_news/src/Helper/ArticlesNewsHelper.php#L137

This behavior is already like this in 3.10.

**Comment by ManuelHu** [comment]
I would work on a PR to fix this, can we get this still into 4.3? Especially because the behavior is quite old, and this might break some sites relying on this inconsistent behavior?

**Comment by chmst** [comment]
A PR will be appreciated, thank you. The release managers will decide about the version.

**Comment by alikon** [comment]
closing as we have a pr #411107
