### ISSUE TITLE
When assign permissions to articles category, flexbox doesn't show the entire group name

### ISSUE THREAD

**Issue by mariantanase** [joomla/joomla-cms#41090]
### Steps to reproduce the issue

I created 2 different groups of users, groups that have slightly long names. When I want to assign a group to a certain category of items, the entire group name does not show up and as a result I cannot distinguish between them.
As a workaround can the column be enlarged to display the full name? Or better to insert a tooltip with the group name.

### System information (as much as possible)
Joomla 4.3.2
PHP 8.1.20
Screen resolution: 1920 x 1080

**Comment by brianteeman** [comment]
Expanding the column to fit any length of text will not be a great solution - especially on smaller screens and tooltips are not great either as you would need to check each group to find the obne you are looking for.

However I have the perfect solution for you.

Create a user.css file in the atum template.
The exact file location is `/media/templates/administrator/atum/css/user.css`
This file will not be overwritten by updates so it is safe.
In that file put the following css. NOTE it does not begin with a dot
```
joomla-tab>div[role=tablist] {
  text-wrap: wrap
}
```

You will now see something like this - which I think is the best solution f0or you other than chosing shorter names.

![image](https://github.com/joomla/joomla-cms/assets/1296369/6a439c12-bd3a-4238-b1b6-a6c4c40c21b8)

**Comment by mariantanase** [comment]
Thanks Brian,

Because it didn't work for me with `text-wrap`, I modified it this way and it works:
```
joomla-tab > div[role="tablist"] {
  white-space: pre-wrap;
}
```

**Comment by richard67** [comment]
So this issue can be closed?
