### ISSUE TITLE
Enhance translation "Empty trash"

### ISSUE THREAD

**Issue by crimle** [joomla/joomla-cms#41106]
### Steps to reproduce the issue
In the Back-End, go to 
- Content > Articles or 
- Content > Categories or 
- Menus > All Menu Items or 
- System > Modules. 
Click [Filter Options] then [Select Status] = «Trash». Now we can see a button [Empty Trash].

### Actual result
In my opinion, this button's caption is not very precise. «Empty Trash» implies that clicking will empty the whole trash. By the way, this is exactly what the corresponding command in Microsoft Windows does. But in Joomla this is not the case. Only the **selected items** are removed from the trash.

### Expected result
I suggest a caption that is more precise. Examples to discuss:
a) «Delete from trash»
b) «Remove from trash»
c) «Delete permanently»

**Comment by chmst** [comment]
I thought the same many times, but always forgot. Would you like to make the PR yourself? 
My favourite is c) Delete permanently.

**Comment by crimle** [comment]
If only I knew how to do that (a PR). I know what it is, just barely.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41106">issues.joomla.org/tracker/joomla-cms/41106</a>.</sub>

**Comment by chmst** [comment]
Please test https://github.com/joomla/joomla-cms/pull/41116

**Comment by chmst** [comment]
Please test https://github.com/joomla/joomla-cms/pull/41119 on joomla 5..0 dev

**Comment by richard67** [comment]
Closing as having a pull request. Please test #43841 . Thanks in advance.
