### ISSUE TITLE
Delete with SqlSrv

### ISSUE THREAD

**Issue by toperf** [joomla/joomla-cms#4110]
#### Steps to reproduce the issue
Deleting on a JModelAdmin with an SqlSrv database, the returned query fails because it tries to "limit" the delete query

#### Expected result
DELETE FROM CommercialOffer WHERE [id] = '15'

#### Actual result
SELECT * FROM ( DELETE , ROW_NUMBER() OVER (ORDER BY (select 0)) AS RowNumber FROM CommercialOffer WHERE [id] = '15') _myResults WHERE RowNumber BETWEEN 1 AND 0

#### System information (as much as possible)
Joomla! 3.3.3

#### Additional comments
On libraries\joomla\database\query.php I put a "return $query;" on line 411, which looks to have made the trick. But I feel the other "cases" should be looked too as by nature the update should not have a "limit". Although I have encountered no problems with updates as it is.

**Comment by roland-d** [comment]
Hello @toperf

Thank you for your contribution.

The last comment here was on August 14 2014. So the question is, Is this issue/pull request still valid?
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4110">issues.joomla.org/joomla-cms/4110</a>.</sub>

**Comment by brianteeman** [comment]
Closed due to lack of response for further information - it can always be reopened if that is provided<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4110">issues.joomla.org/joomla-cms/4110</a>.</sub>
