### ISSUE TITLE
Unable to select frontend language for user

### ISSUE THREAD

**Issue by adatso** [joomla/joomla-cms#41109]
I have encountered an error that makes it impossible to assign frontend language to the user, neither in the frontend nor in the backend user profile settings. 

[screen shot 2023-07-03 at 18 21 49](https://issues.joomla.org/uploads/1/9448858e19d4a7e80e585f3be9676ca6.gif)

Fix below...

backend:
/administrator/components/com_users/src/Model/UserModel.php (line 142)
<pre>$form->setFieldAttribute('language', 'type', 'frontend_language', 'params');</pre>
replace by<pre>$form->setFieldAttribute('language', 'type', 'language', 'params');</pre>

frontend:
/components/com_users/src/Model/ProfileModel.php (line 152)
<pre>$form->setFieldAttribute('language', 'type', 'frontend_language', 'params');</pre>
replace by<pre>$form->setFieldAttribute('language', 'type', 'language', 'params');</pre>

Why is that? Because I don't see any mention of "frontend_language" in the XML forms. I hope this fix will be included in j4.3.3

**Comment by chmst** [comment]
I cannot replicate this issue. Have you activated content languages? 

> Why is that? Because I don't see any mention of "frontend_language" in the XML formsWhy is that? Because I don't see any mention of "frontend_language" in the XML forms

This is the FrontendLanguageFiled.

**Comment by adatso** [comment]
ok, it's clear here. but what if third-party extensions are used, such as falang, where default home pages should be set to all? <pre>// Select the language home pages. why is this necessary, why not leave standard language selection in user profile (frontend/backend)?
        $query->select('l.home, l.language')
            ->innerJoin($db->quoteName('#__menu') . ' AS l ON l.language=a.lang_code AND l.home=1 AND l.published=1 AND l.language <> ' . $db->quote('*'))
            ->innerJoin($db->quoteName('#__extensions') . ' AS e ON e.element = a.lang_code')
            ->where('e.client_id = 0')
            ->where('e.enabled = 1')
            ->where('e.state = 0');</pre><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41109">issues.joomla.org/tracker/joomla-cms/41109</a>.</sub>

**Comment by adatso** [comment]
why is this necessary, why not leave the standard language selection in the user profile?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41109">issues.joomla.org/tracker/joomla-cms/41109</a>.</sub>

**Comment by chmst** [comment]
We had no issue for that until now. Could you check if this is caused by your template?

**Comment by chmst** [comment]
yes - after longer time and no additional information
