### ISSUE TITLE
Hard coded colors instead of css variables

### ISSUE THREAD

**Issue by hans2103** [joomla/joomla-cms#41105]
Media/templates/site/cassiopeia/scss/vendor/bootstrap/_buttons.scss

what is the use of hard coded colors when we work with css variables instead?
https://github.com/joomla/joomla-cms/blob/3a44db8641eead95a4ee517dd31ab7059c095922/build/media_source/templates/site/cassiopeia/scss/vendor/bootstrap/_buttons.scss#L17-L39

**Comment by brianteeman** [comment]
are you referring to using $white instead of var(--something) ??

**Comment by hans2103** [comment]
See screenshot below where `.btn-secondary` has both css variables as scss variables.

**Comment by richard67** [comment]
Closing as having a pull request.
