### ISSUE TITLE
Webservices com_user create group error

### ISSUE THREAD

**Issue by tsesl** [joomla/joomla-cms#41113]
### Steps to reproduce the issue
`curl --location '{{base_url}}api/index.php/v1/users/groups' --header 'Content-Type: application/json' --data '{"title": "Group Title", "parent_id": 1}'`

### Expected result
Response Code: 200 OK
Body: `
{
    "links": {
        "self": "{{base_url}}api/index.php/v1/users/groups"
    },
    "data": {
        "type": "groups",
        "id": "...",
        "attributes": {
            "id": ...,
            "parent_id": 1,
            "lft": ...,
            "rgt": ...,
            "title": "Group Title"
        }
    }
}`

### Actual result
Response Code: 400 Bad Request
Body: `{
    "errors": [
        {
            "title": "Field required: id"
        }
    ]
}`

### System information (as much as possible)
Joomla 4.3.2

### Additional comments
The "id" field attribute Required is "true". Thats causes the validation of the model to fail on save.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #41141 . Thanks in advance.
