### ISSUE TITLE
[4.4] [5.0] Cli update

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41115]
### Steps to reproduce the issue
using latest 4.4
set the update channel to testing `https://update.joomla.org/core/nightlies/next_major_list.xml`
from the command line verify that an update is available
`php .\cli\joomla.php core:check-updates`

![image](https://github.com/joomla/joomla-cms/assets/1296369/0387e1d0-8ef2-4467-9a76-908289fc1e5b)

from the command line do the update
`php .\cli\joomla.php core:update`

### Expected result
update completes without error

`administrator\logs\joomla_update.php`
contains details of the update

### Actual result
![image](https://github.com/joomla/joomla-cms/assets/1296369/6210d915-cd1f-4a2c-a90c-e6d36d23296c)

`administrator\logs\joomla_update.php`
no details of the update

### Additional comments
appears to have update to j5 but dont know if it actually did everything

**Comment by richard67** [comment]
Possibly related to or caused by #40257 .

**Comment by alikon** [comment]
if you change
[use Joomla\CMS\Filesystem\File;](https://github.com/joomla/joomla-cms/blob/d05b8fde5738cdf7e3f7ecc2cc8b925111fce3bf/libraries/src/Console/UpdateCoreCommand.php#L13)

to 

`use Joomla\Filesystem\File;`

should work

**Comment by richard67** [comment]
> if you change [use Joomla\CMS\Filesystem\File;](https://github.com/joomla/joomla-cms/blob/d05b8fde5738cdf7e3f7ecc2cc8b925111fce3bf/libraries/src/Console/UpdateCoreCommand.php#L13)
> 
> to
> 
> `use Joomla\Filesystem\File;`
> 
> should work
> 
> but is already like that in 5.0

Yes, but when updating from 4.4 it might still be the 4.4 PHP file which is running.

**Comment by alikon** [comment]
yes should be changed on 4.4 too then

**Comment by HLeithner** [comment]
File::exists have to be replaced by `is_file()` or `file_exists()`

**Comment by alikon** [comment]
please test https://github.com/joomla/joomla-cms/pull/41117
