### ISSUE TITLE
[5.0] cropper-module

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41124]
### Steps to reproduce the issue
`npm i`

### Expected result
all js is build without notices etc

### Actual result
'cropper-module' is imported by build/media_source/plg_media-action_crop/js/crop.es6.js, but could not be resolved – treating it as an external dependency

**Comment by Fedik** [comment]
It is just a build warning. It will continue to work normally, 

I have made a fix for it, as part of #41070, when made update for a build script for Codemirror.
You can try test it there :wink:
