### ISSUE TITLE
context issue com_tag.tag instead of com_tags.tag

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#41136]
### Steps to reproduce the issue
in com_tags/tmpl/tag/default.php and list.php there is

 <?php echo HTMLHelper::_('content.prepare', $this->tags_title, '', 'com_tag.tag'); ?>

it shall be

 <?php echo HTMLHelper::_('content.prepare', $this->tags_title, '', 'com_tags.tag'); ?>

this is a context error

**Comment by alikon** [comment]
would you like to submit a pull request ? @ced1870

**Comment by MacJoom** [comment]
Thank you @ced1870 for instructions, please test the PR

**Comment by alikon** [comment]
closing as we have a pr https://github.com/joomla/joomla-cms/pull/41150
