### ISSUE TITLE
[4.3] Articles:Edit  -  Preview fails with 404 if publishing date in the future

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#41130]
### Steps to reproduce the issue

1. Create an article with a publishing date in the future
2. Save the article
3. Click on Preview

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/61a50d40-f1de-40d9-babd-ae882bc0e9fb)

### Expected result
The article preview is displayed  -or-  a login screen is presented (behavior for no longer published articles)

### Actual result
An error message appears (Error 404)

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/e1f1e7d4-7083-4d80-8e6b-308b96f32001)

### System information (as much as possible)
Joomla 4.3.2, PHP 8.1.15

### Additional comments
If the "Finish Publishing Date" lies in the past ....

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/25666581-9644-4ab1-889c-9fd32c0e7463)

.... a login screen is shown:

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/c0800885-4afc-4bb5-acaa-98f314e283b5)

**Comment by dautrich** [comment]
I'm in doubt whether the logic here is adequate. IMHO the preview should be shown regardless of ACL and/or publishing dates. 

Look at the use case: The user is in the backend and has sufficient rights to edit an article. He saves the article and now wants to see the result, because there might be some need for improvement. To be able to preview the article in the backend is a big enhancement over J3. So give him/her the preview regardless of other restrictions like missing user rights or not reached publishing date or expired publishing date! And without the need to login first to preview the article.

**Comment by alikon** [comment]
there is still this one open #24132

so i'll close this in favour of #24132

@dautrich thanks for reporting

**Comment by dautrich** [comment]
Did you see my additional comment from today? What do you think about that?

**Comment by alikon** [comment]
@dautrich yes, i've read that.
and i've some memories about, i've even submitted a "bad" pr #35488

please continue on #24132
