### ISSUE TITLE
500 Library path /components/com_quix/helpers cannot be found.

### ISSUE THREAD

**Issue by AdminOG** [joomla/joomla-cms#41144]
I hope you may help me on this issue. My website is 80% ready. but there is a problem suddenly and I can't view my dashboard or edit anything. 

![screen shot 2023-07-12 at 00 40 42](https://issues.joomla.org/uploads/1/20d97a0c6031533d5207b484266d2b3a.png)

**Comment by alikon** [comment]
you should disable the system plugin quix, 
as it is not a core one i'm closing  the issue
