### ISSUE TITLE
PHP deprecation notice when checking user agent

### ISSUE THREAD

**Issue by ron4mac** [joomla/joomla-cms#41142]
### Steps to reproduce the issue
Access the Joomla instance when there is no user agent in the request

### Expected result
No PHP error, warning or notice

### Actual result
PHP Deprecated: stripos(): Passing null to parameter #1 ($haystack) of type string is deprecated in libraries/vendor/joomla/application/src/Web/WebClient.php on line 286

### System information (as much as possible)
Joomla version 4.3.2
PHP Version 8.1.21

### Additional comments
Causes an issue in my development of an appliance that accesses Joomla in raw format via curl seeking image data. The notice corrupts the image data. I would rather not do development work without error reporting.

**Comment by Quy** [comment]
Related #39960
