### ISSUE TITLE
SVG file not found (404)

### ISSUE THREAD

**Issue by KeesZNL** [joomla/joomla-cms#41148]
### Steps to reproduce the issue
Several days ago I upgraded a website from J3.10.10 to J4.3.2. For registered users only there are SVG+XLM interactive schemes for work instructions in the J3 site which are not shown in the J4 site. (File not found 404) Those schemes are produced by Visio and exported to SVG.
I checked filetypes as well as the mimetypes (SVG, image/svg+xml, application/svg+xml) in: 

- Server settings
- Joomla settings
- JCE settings
Simulated the error on a different server in a different J4 site. Same error.
### Expected result
![J3 Scheme](https://github.com/joomla/joomla-cms/assets/138786515/98c6a7c9-8d7a-49e9-ac7d-b94c5f320f48)
### Actual result
![J4 Scheme 404](https://github.com/joomla/joomla-cms/assets/138786515/84724505-a4ce-419b-afe0-48e080978ba4)

### System information (as much as possible)
[systeminfo-2023-07-12T10_41_45+02_00.txt](https://github.com/joomla/joomla-cms/files/12025791/systeminfo-2023-07-12T10_41_45%2B02_00.txt)

### Additional comments
I need those SVG schemes urgently for registered users.
See: https://issues.joomla.org/tracker/joomla-cms/38532

**Comment by KeesZNL** [comment]
Sorry Brian, I made two mistakes. So I have to apologize!
1) The Pre-live site where the error occurs is not residing in its original root folder so the "embed" was pointing to the wrong folder.
2) I added "svg" in the JCE-profile to Image Manager so its possible to upload svg-files as well.
So this issue can be dropped.
However, I did setup a [test J4-site](https://keesvanzwieten.nl/joomla_svg_prob/index.php "Test site") to reproduce the errors. In that site I can reproduce the error of #40729, as well i can demonstrate was is going wrong about #38788. If you want to, i will move over the link to one of these issues. Those errors occurs in my "Pre-live" site as well and are disturbing. For privacy reasons I am not allowed to grant you acces to that site.
Kind regards. 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41148">issues.joomla.org/tracker/joomla-cms/41148</a>.</sub>

**Comment by richard67** [comment]
@KeesZNL Yes, if you can reproduce the other 2 issues, post there and provide a link. Maybe it helps to come forward with these. Closing here as stated above. Thanks for reporting.
