### ISSUE TITLE
5.x Compatibility Plugin

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41158]
### Steps to reproduce the issue
Clean install of j5 alpha
Go to plugin manager and display filters

### Expected result
all filters display

### Actual result
the first filter (status) does not display

### Additional comments
I finally tracked it down. The field type in the xml is "plugin_status" but the actual field is "pluginstatus"

In joomla 4 this is resolved by classmap which creates an alias between the two

In Joomla 5 (on a clean install) it would appear that this classmap is NOT used by default UNLESS the new system-backwardcompatibility plugin is enabled. _it is not enabled by default_

It is easy for me to change the field name BUT that is fixing the symptom not the cause.

the classmap says deprecated 6.0 so I would expect it to work until 6.0
I do not expect that I have to enable an additional plugin for the classmap to work

**_a clean install of joomla 5 should not require this plugin to be enabled_**

**Comment by brianteeman** [comment]
merging #35743 would be a good start

**Comment by PhocaCz** [comment]
> the classmap says deprecated 6.0 so I would expect it to work until 6.0
I do not expect that I have to enable an additional plugin for the classmap to work

This is similar to e.g. JURI: JLoader::registerAlias('JUri', '\\Joomla\\CMS\\Uri\\Uri', '6.0');
