### ISSUE TITLE
PHP 8.2 warning

### ISSUE THREAD

**Issue by ced1870** [joomla/joomla-cms#41157]
### Steps to reproduce the issue

Use Joomla 4.3.3 with PHP 8.2.7
you can go in the admin options, for example in the com_contact options

### Actual result

Get a warning :
 Deprecated: Creation of dynamic property JFormFieldMediaJce::$mediatype is deprecated in C:\wamp64\www\joomla4dev\libraries\src\Form\FormField.php on line 591

**Comment by chmst** [comment]
This is related to the JCE, not the Joomla Core. Are you sure to have the latest version of JCE?

**Comment by ced1870** [comment]
fixed ! thanks
I was not expecting JCE to render an error this such areas
