### ISSUE TITLE
[5.0] Formatting stripped in TinyMCE after save

### ISSUE THREAD

**Issue by bayareajenn** [joomla/joomla-cms#41164]
### Steps to reproduce the issue
Download and install Joomla 5.0.0alpha3
Create an article
Add an ordered or unordered list
Save article
Watch your formatting disappear like sand sifting through your fingers on a windy day

### Expected result
That the formatting would stay

### Actual result
The formatting is removed on Save

### System information (as much as possible)
5.0.0alpha3 
PHP8.1
MySql 8.0
Windows 10
Firefox

### Additional comments
This bug is not present in 5.0.0alpha2

**Comment by richard67** [comment]
> Download and install Joomla 5.0.0alpha3

@bayareajenn You mean 5.0.0-alpha3-dev, i.e. a nightly build? The latest alpha was alpha2, see https://github.com/joomla/joomla-cms/releases .

**Comment by bayareajenn** [comment]
Yes, a nightly build from yesterday (and the day before).

**Comment by bayareajenn** [comment]
I forgot that Harald asked me to tag @Fedik and @dgrammatiko for this one.

**Comment by Fedik** [comment]
@HLeithner This comes from https://github.com/joomla/joomla-cms/blob/5e3d8489c3f5bea3074c6005b9be42b2d9927d04/administrator/components/com_content/forms/article.xml#L56
And works when Compatibility plugin is enabled.

That probably need to check for all exiting forms where `JComponentHelper::filterText` is used

**Comment by brianteeman** [comment]
confirmed

**Comment by HLeithner** [comment]
Fixing it should be easy but I am asking myself why no exception is thrown when the filter it's not found

**Comment by chmst** [comment]
I noticed that also images disappear completely

**Comment by HLeithner** [comment]
we have a pull request #41259
