### ISSUE TITLE
[4.4.2 & 5.0.2] Displaying a list of articles from Popular Tags Module

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#41179]
### Steps to reproduce the issue
1. create tags Tag1 and Tag2
2. create an article with both tags Tag1 and Tag2
3. create menu Tagged Items with both tags Tag1 and Tag2 with Match Type - All
4. create Popular Tags Module
5. Joomla Global Configuration parameter SEF = Yes
6. on frontend page of menu Tagged Items select some tag in Popular Tags Module

### Expected result
the page with articles of the selected tag is displayed

### Actual result
a page with no articles found is displayed

### Additional comments
![screen shot 2023-07-17 at 15 18 39](https://issues.joomla.org/uploads/1/61b1d1ab1d2e807233c9ced6fffc8bcd.jpg)
![screen shot 2023-07-17 at 15 18 50](https://issues.joomla.org/uploads/1/17cf7e022d70de5f70d7d5e35cbafed0.jpg)![screen shot 2023-07-17 at 15 19 11](https://issues.joomla.org/uploads/1/661ef11a4f56fb61ec5f4b45834235e3.jpg)![screen shot 2023-07-17 at 15 19 21](https://issues.joomla.org/uploads/1/166ea158315b6bb180a6d3ffd09112de.jpg)![screen shot 2023-07-17 at 15 19 30](https://issues.joomla.org/uploads/1/a25bd3a38d40efd62e2e808f4b998fbe.jpg)![screen shot 2023-07-17 at 15 19 39](https://issues.joomla.org/uploads/1/80c36884995e6fc3e8fc89e92fc9742a.jpg)

**Comment by brianteeman** [comment]
Sorry I cannot replicate this. The forums are really the best place for support

**Comment by 1inkin** [comment]
this is weird.  i get to do it every time.  this is a issue, not a wrong usage.  when a tag is opened from a module, it is added to the menu item's filter.  as a result, it turns out that the page is filtered by the exact match of tag1, tag2 and tag1 again. so the filter turns out to be incorrect and gives an empty result<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41179">issues.joomla.org/tracker/joomla-cms/41179</a>.</sub>

**Comment by 1inkin** [comment]
this issue is relevant for the Joomla Global Configuration parameter SEF = Yes<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41179">issues.joomla.org/tracker/joomla-cms/41179</a>.</sub>

**Comment by 1inkin** [comment]
Joomla 4.3.4. Issue is still relevant<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41179">issues.joomla.org/tracker/joomla-cms/41179</a>.</sub>

**Comment by alikon** [comment]
if you unpublish step 3. it works.... strange

**Comment by 1inkin** [comment]
And works if step 5 = No

**Comment by 1inkin** [comment]
This issue can be observed without Popular Tags Module. you can click on the Tag that is displayed inside the article<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41179">issues.joomla.org/tracker/joomla-cms/41179</a>.</sub>

**Comment by 1inkin** [comment]
This issue fixed in #42716<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41179">issues.joomla.org/tracker/joomla-cms/41179</a>.</sub>

**Comment by alikon** [comment]
closing as fixed by #42716
