### ISSUE TITLE
[4.3.3] Better language string

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#41171]
Hi guys, 
the language string 
COM_USERS_PROFILE_VALUE_NOT_FOU=”Website default”
line 101 .../language/en-EN/com_users.ini

It is used in User Profile fields page when the user still has not choose any value (left it empty).

It would be really better as: ”Not configured" or something similar,

Do you agree ?

**Comment by sayfrndship1234** [comment]
Please contribute to the language to upload your string.

**Comment by joomleb** [comment]
@sayfrndship1234 
Please, How?
Can you give me some instructions?

**Comment by sayfrndship1234** [comment]
try there : https://joomla.crowdin.com/

**Comment by zero-24** [comment]
Hi,

when you want to change the original value of that language string please send a PR against this repo changing this line here:
https://github.com/search?q=repo%3Ajoomla%2Fjoomla-cms+COM_USERS_PROFILE_VALUE_NOT_FOU+language%3AINI&type=code

Please find some instructions on how to do it here: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

ps @sayfrndship1234 crowdin is there only for translation but not for the original en-GB language the root for that is within this repo. ;)

**Comment by alikon** [comment]
please test #41435
