### ISSUE TITLE
Admin: Contact view does not load with a large user base

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#41187]
### Steps to reproduce the issue

Have a site with a large number of users (in the thousands).
In the console, go to the Contacts page.

### Expected result

The page loads just fine.

### Actual result

The page loads after a long time or not at all (the page times out).

### System information (as much as possible)

Joomla 4, PHP 8.0

### Additional comments

The root of the problem is:
When loading the Contacts page, the batch action contains a field that allows the selection of users (to batch associate contacts with users).

The user field used for the batch is found under: layouts/joomla/html/batch/user.php
It calls Joomla\CMS\HTML\Helpers\User userlist function, which queries ALL users, minus the blocked ones. 

That's where if fails.

The issue actually exists in Joomla 3, but only after the batch modal has been opened (the page gets unresponsive then).

**Comment by brianteeman** [comment]
This can potentially happen with modules, menus and categories as well but its much less likely that you would ever have enough to cause a problem.

I'm not even sure why there is even a batch functionality to associate multiple contacts to a single user. What is the real world usecase for this?

**Comment by obuisard** [comment]
I actually had a client using it, but to be honest, it is a niche case.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41187">issues.joomla.org/tracker/joomla-cms/41187</a>.</sub>

**Comment by AndySDH** [comment]
Still an issue in Joomla 5...

**Comment by alikon** [comment]
please test #44600
