### ISSUE TITLE
[5.0] Potential upgrade issue, that can lead to blocked backend

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#41181]
When user decide to update the site via FTP, he/she will get a blocked backend.
That because #38149 add new column to DB `__menu_types`, but DB Fixer will not be accesible due to crash of menu rendering.

We need to find way to avoid such situation.

**Comment by HLeithner** [comment]
We don't support update with ftp since joomla 1.x or 2.x? don't know but it's not a supported upgrade path at least since joomla 3.

I'm closing this but thanks for looking.

**Comment by Fedik** [comment]
Well, at least I warned :)

We already had such issue when auto update failed, and backend was locked, due to unfinished DB update.
User will not be able to recovery esialy.

It not aquestion if we support or not. I wrote about FTP as quick example.

**Comment by HLeithner** [comment]
That's a problem we can't fix with our current way of upgrading. Needs some rewrite of the update to detect failures. Maybe with checkpoints or something. But in such cases use the backup or apply the schema update manually should be enough. Ymmv

**Comment by Fedik** [comment]
This is a module, and I think about wrap ModuleRendered->render() it in to try/catch. 
I had this idea for long time. In some cases It is also cause a broken rendering on the site: half normal page with another half is error page.

In oposite to plugins that hard to `try/catch`, the module's `try/catch` should be okay. What do you think?
