### ISSUE TITLE
[5.0.0-alpha3-dev] Formatting and images are removed from custom modules before safe

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#41190]
### Steps to reproduce the issue

Fresh installation with 5.0.0-alpha3-dev from nightly builds. (TinyMCE is default editor)
Go to site modules - open new module of type Custom
or install sample blog data and open the banner module, which contains some formatted text.
Insert an image.
Save 

### Expected result
The module ist stored and contains the image as in all former versions.

### Actual result
No image in the module and all formatting disappeared. 

### System information (as much as possible)
5.0.0-alpha3-dev, php 8.2

**Comment by brianteeman** [comment]
see #41164

**Comment by chmst** [comment]
thx!  close as duplicate
