### ISSUE TITLE
Cassiopeia: cannot select locally installed font

### ISSUE THREAD

**Issue by sm8ps** [joomla/joomla-cms#41193]
### Steps to reproduce the issue

- Install font locally under '/media/templates/site/cassiopeia/fonts/' and register it in '/media/templates/site/cassiopeia/css/user.css'
  - Verify that is is working by adding a rule to 'user.css'
- Edit style of template Cassiopeia > Advanced > Fonts Scheme: select font

### Expected result

The locally installed font should be listed under "Fonts from Folder".

### Actual result

The only font listed under "Fonts from Folder" is "Roboto (local)".

### System information (as much as possible)

Joomla 4.3.3 running on Apache/2.4.41 (Ubuntu) with PHP Version 8.0.29 (FPM/FastCGI).

### Additional comments

BTW, I did add "woff2" to Templates: Styles (Site) > Templates > Valid Font Formats. IMHO this should included in the standard settings.

**Comment by sm8ps** [comment]
Added additional comment about font format "woff2"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41193">issues.joomla.org/tracker/joomla-cms/41193</a>.</sub>

**Comment by brianteeman** [comment]
There is no functionality to dynamically populate that list from the fonts in the folder. It would be a good addition

**Comment by richard67** [comment]
You could create a child template and then edit the "useFontScheme" field in the templateDetails.xml file: https://github.com/joomla/joomla-cms/blob/4.3-dev/templates/cassiopeia/templateDetails.xml#L90-L104

**Comment by sm8ps** [comment]
Thanks @brianteeman,  @richard67! Your points explain the situation and point me to a work-around.

**Comment by richard67** [comment]
@sm8ps You could create a css file based on this one https://github.com/joomla/joomla-cms/blob/4.3-dev/build/media_source/templates/site/cassiopeia/scss/global/fonts-local_roboto.scss and use it in your child template's XML in the same way.

Can we close this issue now as it is not a core bug?

**Comment by sm8ps** [comment]
Sure! Done.
