### ISSUE TITLE
Calendar field is not working when format="%a %e %b %Y" is used

### ISSUE THREAD

**Issue by madanedeepali** [joomla/joomla-cms#41194]
### Steps to reproduce the issue

Create a calendar field in any component's XML file with the following details
`<field name="nextdate" 
    class="inputbox" format="%a %e %b %Y" 
    timeformat="24" filter="server_utc" 
    translateformat="false" showtime="false"
     singleheader="false" todaybutton="false" 
     weeknumbers="false" filltable="false"
      type="calendar" label="Next Date" description=" Enter the next date" hint=" you can select the next date in the format "/>`
   

### Expected result

The selected date should get saved in the database in the respected table.

### Actual result
Saved Successfully message gets displayed not an error but the date is not getting saved in the database.

### System information (as much as possible)
The issue is present in both Joomla3 and Joomla4 

### Additional comments
You can also try adding this field in the core Joomla contact component for cross-checking it does not work there also

**Comment by madanedeepali** [comment]
@dziudek @pollen8 @elkuku can you check ASAP

**Comment by chmst** [comment]
What do?  you mean with %e? 
I cannot find this in the date https://www.php.net/manual/de/datetime.format.phptime format

**Comment by madanedeepali** [comment]
%e means Day of the month without leading zeros (1 to 31)
You can refer to the document here https://docs.joomla.org/Calendar_form_field_type

**Comment by madanedeepali** [comment]
@chmst any update on the above issue

**Comment by madanedeepali** [comment]
@joomla-cms-bot @dziudek @pollen8 What are your thoughts on this

**Comment by brianteeman** [comment]
please do not tag people. especially repeatedly. No idea why you chose those people but one is a bot and another is not active

**Comment by chmst** [comment]
Sorry, the link is: https://www.php.net/manual/en/datetime.format.php and I did not read correctly  my apologies. 

I tested you field with php 8.2 and got a deprecated message at save, but the input is saved correctly in the database.

![grafik](https://github.com/joomla/joomla-cms/assets/1035262/8f27f909-da5e-47ff-8178-2ad88ba12d37)

**Comment by Fedik** [comment]
@madanedeepali you missing `filterformat="D j M Y" ` in your XML.
Hovewer there also another bug.

Please test #41224

**Comment by madanedeepali** [comment]
@Fedik Added filterformat="D j M Y"  in the XML file still facing the same issue

**Comment by Fedik** [comment]
@madanedeepali please test the fix #41224, then it will work
