### ISSUE TITLE
CategoryNode::getParent() is missing in API documentation

### ISSUE THREAD

**Issue by robbiejackson** [joomla/joomla-cms#41197]
The function `getParent` is not present for [CategoryNode](https://api.joomla.org/cms-4/classes/Joomla-CMS-Categories-CategoryNode.html "CategoryNode") in Joomla 4. The function is present in [Joomla 3 CategoryNode API](https://api.joomla.org/cms-3/classes/Joomla.CMS.Categories.CategoryNode.html#method_getParent "Joomla 3 CategoryNode API"), but as it's not marked as deprecated there I assume that it's omitted by accident.

Maybe it got missed when a number of CategoryNode functions were extracted into NodeTrait.

**Comment by richard67** [comment]
Hmm, NodeTrait uses the ImmutableNodeTrait: https://github.com/joomla/joomla-cms/blob/4.3-dev/libraries/src/Tree/NodeTrait.php#L23

And this has the getParent function: https://github.com/joomla/joomla-cms/blob/4.3-dev/libraries/src/Tree/ImmutableNodeTrait.php#L87

So maybe it’s just the API docs missing it?

**Comment by robbiejackson** [comment]
Yes I wrote some code and confirmed that the function is still there and accessible. So it's just the API DOCs which are missing it for some reason. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41197">issues.joomla.org/tracker/joomla-cms/41197</a>.</sub>

**Comment by brianteeman** [comment]
Probably for the same reason I discovered and started to fix regarding fqn

**Comment by richard67** [comment]
Or it has problems to resolve it when a method is inside a trait which is used by another trait which then is used in the class?

**Comment by Hackwar** [comment]
The documentation has been updated and fixed and now this should be fine. I'm closing this issue, but if you still have this problem, please post here again and I will open the issue back up again.
