### ISSUE TITLE
[5.0] deprecated warning if the showon attribute in a custom field does not match the pattern 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#41217]
### Steps to reproduce the issue

Make a custom field and enter some string into the field for attributes.
It is not clear how such a showon attribute should look like and you can enter whatever. 

![grafik](https://github.com/joomla/joomla-cms/assets/1035262/f7076b7b-145b-495f-a5a5-33e752e0a911)

### Expected result
An error message or  ignoring the input if it does not meet the required pattern.

### Actual result

![grafik](https://github.com/joomla/joomla-cms/assets/1035262/4087d9b3-02df-4e51-87a0-259045bf5a5e)

### System information (as much as possible)
php 8.2, joomla 5.0.0 dev

### Additional comments
It would help to add an example for a correct showon Attribute to the description.

**Comment by chmst** [comment]
Related https://github.com/joomla/joomla-cms/pull/41104

**Comment by brianteeman** [comment]
I made the same mistake the other day. The syntax is the same as when it is used in an xml file. so it is **_fieldname:value_**

**Comment by chmst** [comment]
I know the syntax in xml files ( I am good with copy / paste :) )  - but who knows what users will enter?

**Comment by brianteeman** [comment]
add it to the help or the description then - seems an appropriate use

**Comment by alikon** [comment]
closing as we have a pr https://github.com/joomla/joomla-cms/pull/41460
please test #41460
