### ISSUE TITLE
URL's in login module

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#41218]
### Steps to reproduce the issue
- Create a login module
- Make it show up on the homepage of the website
- Create a menu item to the user login ('login')
- Point the module to this menu item

### Expected result
Links in the module (Password reset and username links) should point to:
https://websitename.com/login/?view=reset
https://nwebsitename.com/login?view=remind
And the pages should appear to reset / remind

### Actual result
The links have these URL's:
https://websitename.com/component/users/reset?Itemid=101
https://websitename.com/component/users/remind?Itemid=101
Clicking on the does not show the forms for remind or reset.

### System information (as much as possible)
Joomla 4.3.3
PHP 8.0.29
SEF URLS enabled and using .htaccess

### Additional comments
Maybe a routing issue? II also tried it on the default Joomla template. Same issue. But maybe I am missing something??

**Comment by jjnxpct** [comment]
Only when you go to the menu item 'login' the URL are correct. But on all other pages they are non-sef.

**Comment by jjnxpct** [comment]
I am not sure if the URL's are meant to be 'coupled' to the menu item that is set in the module settings. Maybe not... I did find a way to make it work in our template so the links do work and show the appropriate forms. 

So maybe expecting SEF URL's based on the menu item is not the right expectation?

**Comment by Hackwar** [comment]
Indeed, there is no connection between the different views, so the login view is not a parent for the "forgot password" view, etc. There is no automation which would result in a "nice" URL for those other views. I also don't see how we could change this in a way which is backwards compatible and wouldn't create issues on other sites. My solution would be an extension which checks the site health and reports among other things missing menu items for these views.

**Comment by Hackwar** [comment]
As I wrote earlier, this is expected behavior so I'm closing this issue.
