### ISSUE TITLE
SmartSlider 3 - Error 404 with Joomla 4.3.3

### ISSUE THREAD

**Issue by Javo2986** [joomla/joomla-cms#41221]
Following message is being received while trying to edit configuration parameters on a slide:

![error404](https://github.com/joomla/joomla-cms/assets/140462853/7afa8644-5e86-4bef-a288-c55e1921dccf)

Many workarounds has been applied:
-Disable/Enable SEF on Global Configuration + URL Rewriting parameters
-Reinstalling SmartSlider Module
-Create/recreate slides with SEF enabled/disabled
-Edit manually configuration.php file

Any suggestion to fix this issue?

Thanks!

**Comment by brianteeman** [comment]
Please contact the makers of SmartSlider for support or try the Joomla forum (https://forum.joomla.org)

**Comment by chmst** [comment]
Closing this as it is not a Joomla Core issue
