### ISSUE TITLE
Article blog media - choose images from existing media instead of upload

### ISSUE THREAD

**Issue by Kachoudas** [joomla/joomla-cms#41223]
### Is your feature request related to a problem? Please describe.

In the current version 4.3.3 of Joomla you can upload images for an article as Featured Image or Gallery Images when the article format is Gallery.
Uploaded images are automatically stored in a folder structure like images/year/month/day.
This gets very hard to maintain after a while as it's not possible to group or structurize images in any way.

### Describe the solution you'd like

Instead of only being able to upload images there should be a way to choose images from the media manager which have been uploaded previously or optionally upload a new image to a specified folder.

### Additional context

Current state: only upload of new images possible
![image](https://github.com/joomla/joomla-cms/assets/138502300/1fbaa13c-5e53-4bb7-8f57-134636ae0475)

preferred state: choose images from media manager
![image](https://github.com/joomla/joomla-cms/assets/138502300/56dd5351-ce73-4fb9-a3dc-9dd5279cbcca)

**Comment by brianteeman** [comment]
That is not the standard set of fields. In the standard image fields you can do everything you asked for.

**Comment by Kachoudas** [comment]
I just realized that this tab is added by the template Shaper Helix Ultimate even if the template is not set as standard.
Thank you for the hint.
I will refer the suggestion to the template maintainers.
This topic can be closed in the meantime.
