### ISSUE TITLE
[5.0] Schemaorg removes existing richdata without replacement

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41231]
### Steps to reproduce the issue
Install joomla sampledata on a site without the new schemaorg plugins
check the source of the home page and you will find **multiple** pieces of rich data
See screenshot for example
![image](https://github.com/joomla/joomla-cms/assets/1296369/119c4996-ac78-44ce-bc3e-068aba0ea31e)

Upgrade site to include the new schemaorg plugins 

### Expected result
The same richdata is present (even if it is now in the head in json+ld format)

### Actual result
The richdata is not the same
![image](https://github.com/joomla/joomla-cms/assets/1296369/25258ace-b152-4af8-b5bc-604ce8cea382)

**Comment by brianteeman** [comment]
The only way to keep richdata such as author on all existing articles is to manually create richdata with one of the plugins for every single article

**Comment by HLeithner** [comment]
I can't replicate this issue...
I tested it on one of my upgraded real websites and get the correct.
For you it seems if the fallback plugin (Content - Joomla) not kicked in, can you please go to the plugin settings, check the settings and save them again?

**Comment by brianteeman** [comment]
Where you testing the homepage of the default sampledata?

**Comment by HLeithner** [comment]
News article

**Comment by brianteeman** [comment]
So please test the same thing that I reported and you will see the problem

**Comment by brianteeman** [comment]
From what I can tell the fallback only works on a single article view. Anything else such as blog or featured and some modules lose there data

**Comment by HLeithner** [comment]
I found the bug, missing return statement, I will create a pr

**Comment by HLeithner** [comment]
pr created can you please test if this fixes the category/feature view? closing this for pr #41250
