### ISSUE TITLE
[5.0] schemeorg escaped

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41249]
If you look at the json+ld in the head of your document it is not easy to read (as a human) due to all the escape characters. Are they needed? Looking at the spec it appears we have gone a step too far with escaping the slashes

https://w3c.github.io/json-ld-syntax/#restrictions-for-contents-of-json-ld-script-elements

## Hard to read
`<script type="application/ld+json">{"@context":"https:\/\/schema.org","@graph":[{"@type":"Organization","@id":"https:\/\/j5.test\/#\/schema\/Organization\/base","url":"https:\/\/j5.test\/"},{"@type":"WebSite","@id":"https:\/\/j5.test\/#\/schema\/WebSite\/base","url":"https:\/\/j5.test\/","name":"5 alive","publisher":{"@id":"https:\/\/j5.test\/#\/schema\/Organization\/base"},"potentialAction":{"@type":"SearchAction","target":"https:\/\/j5.test\/index.php\/en\/search?q={search_term_string}","query-input":"required name=search_term_string"}},{"@type":"WebPage","@id":"https:\/\/j5.test\/#\/schema\/WebPage\/base","url":"https:\/\/j5.test\/index.php\/en\/","name":"Home","description":null,"isPartOf":{"@id":"https:\/\/j5.test\/#\/schema\/WebSite\/base"},"about":{"@id":"https:\/\/j5.test\/#\/schema\/Organization\/base"},"inLanguage":"en-GB"}]}</script>`

## Easier to read
`<script type="application/ld+json">{"@context":"https://schema.org","@graph":[{"@type":"Organization","@id":"https://j5.test/#/schema/Organization/base","url":"https://j5.test/"},{"@type":"WebSite","@id":"https://j5.test/#/schema/WebSite/base","url":"https://j5.test/","name":"5 alive","publisher":{"@id":"https://j5.test/#/schema/Organization/base"},"potentialAction":{"@type":"SearchAction","target":"https://j5.test/index.php/en/search?q={search_term_string}","query-input":"required name=search_term_string"}},{"@type":"WebPage","@id":"https://j5.test/#/schema/WebPage/base","url":"https://j5.test/index.php/en/","name":"Home","description":null,"isPartOf":{"@id":"https://j5.test/#/schema/WebSite/base"},"about":{"@id":"https://j5.test/#/schema/Organization/base"},"inLanguage":"en-GB"}]}</script>`

**Comment by HLeithner** [comment]
funny I added this code for better debugging in the system plugin:
`$schemaString = $schema->toString('JSON', ['bitmask' => JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE]);`

**Comment by HLeithner** [comment]
I changed the output in https://github.com/joomla/joomla-cms/pull/41250
