### ISSUE TITLE
[5.0] schemaorg unexpected destructive behaviour

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41251]
### Steps to reproduce the issue
1. Add some values to the blogposting schema, save and close and check that the schema you entered is included on the front end
2. Re-open the article. Switch to the schema tab and add some values to the person schema, save and close and check that the schema you entered is included on the front end
3. Re-open the article and go to the blogposting schema. Do Nothing. Go to the main tab and edit the article. Save and close and check that the schema you entered is included on the front end

### Expected result
1. Blogposting Schema is used in the json+ld
2. Person Schema  is used in the json+ld AND the data -previously entered in the Blogposting schema is still present in the admin
3. Person Schema  is used in the json+ld AND the data -previously entered in both the Blogposting and Person schema is still present in the admin

### Actual result
1. Blogposting Schema is used in the json+ld
2. Person Schema  is used in the json+ld AND the data -previously entered in the Blogposting schema has been removed WITHOUT any notification of this destructive change
3. empty Blogposting Schema  is used in the json+ld AND the data -previously entered in the Person schema has been removed WITHOUT any notification of this destructive change

### Additional comments
Perhaps I added all the fields in one schema and saved, went to look at another schema to see if it was relevant decided it wasnt. changed something else in the articvle and saved. Now I just lost all the data I previously entered

**Comment by HLeithner** [comment]
> Re-open the article. Switch to the schema tag and add some values to the name schema, save and close and check that the schema you entered is included on the front end

not sure what you mean with schema "tag", I can'T find a Schema Type "tag" also the "name" schema doesn't exists. can you please be specific which types you select where?

**Comment by brianteeman** [comment]
**sorry** - typos now corrected in original post
tag => tab
name => person

**Comment by HLeithner** [comment]
about the removed content, why do you think it's unexpected?  You change the type and you don't see it any longer right?

So it's gone like everywhere else in joomla too, like changing the category. We don't save data somewhere hidden if you switch types. That wouldn't make anysense for me.

**Comment by brianteeman** [comment]
Changing the category is not comparable. That is a switch from one category to another and can just as easily be switched back. This is user created data that is completely removed without any notification. There is nowhere in Joomla that does a destreuctive change without notice.

If you look at fields that is why we dont allow you to change a field type after it has been created because you would lose user created data.

**Comment by HLeithner** [comment]
> Changing the category is not comparable. That is a switch from one category to another and can just as easily be switched back. This is user created data that is completely removed without any notification. There is nowhere in Joomla that does a destructive change without notice.

it is compare able, in both cases you get new fields

> If you look at fields that is why we dont allow you to change a field type after it has been created because you would lose user created data.

and it not nice for the user, I have in mind to change this that you at least can switch between compatible field types, like text,phone,email,url or similar fields.

**Comment by brianteeman** [comment]
> it is compare able, in both cases you get new fields

Only if you set up custom fields
AND only if you setup those fields per category

Hey and guess what if you change the category back then the data the user entered is still there.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/assets/1296369/2d29da58-b037-477e-a8e3-7a6b79cec89f

**Comment by HLeithner** [comment]
thanks you found a bug in custom fields, can you please create a issue based on your finding, it's not ok that we leave garbage in the database.

**Comment by brianteeman** [comment]
No it is NOT a bug

**Comment by HLeithner** [comment]
of course it's a bug, data that are no longer used by the article have to be removed. As example if you use the custom fields to filter for articles which has a field "awesometext" and you search for "yes" in this field you will still get the articles which are not longer belong to your filter criteria because it is not longer in the relevant category and this is wrong.

**Comment by brianteeman** [comment]
after x years is not an expected feature?

**Comment by HLeithner** [comment]
https://github.com/joomla/joomla-cms/issues/8244 is from 2015 and I would expect it's still a valid bug.

But in this case it breaks functionality and saves wrong/not longer valid data.

So no I don't see this as unexcpected feature.

**Comment by brianteeman** [comment]
how is that even remotely related

**Comment by HLeithner** [comment]
an answer of your

> after x years is not an expected feature?

just because something behaves like that for years it doesn't mean that it's expected.

**Comment by brianteeman** [comment]
so completely off-topic and unrelated. And you wonder why people dont contribute

**Comment by brianteeman** [comment]
Closed as clearly no one else sees this as a problem
