### ISSUE TITLE
Tags » Tagged Items 404 when a tag unpublished

### ISSUE THREAD

**Issue by shane-clickingmad** [joomla/joomla-cms#41264]
### Steps to reproduce the issue
Setup a menu item for "Tags » Tagged Items" and select multiple tags, one of which is unpublished.

### Expected result
Page to show all items of the selected published tags

### Actual result
404 page is shown

### System information (as much as possible)
Joomla 4.3.3

**Comment by Hackwar** [comment]
This is actually expected behavior. If you have a menu item which is linked to some content and that content is unpublished (in this case the tag), then it should throw a 404 and not fall back onto something else.

**Comment by Hackwar** [comment]
yes
