### ISSUE TITLE
[5.0] schemaorg filename

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41261]
I dont know the convention for capitalisation on filenames but this looks to be wrong

plugins\schemaorg\blogposting\src\Extension\Blogposting.php
plugins\schemaorg\jobposting\src\Extension\JobPosting.php

If it is wrong then the namespace statements will need to be updated as well to match (and maybe elsewhere)

**Comment by brianteeman** [comment]
@richard67 if the filename is changed does there need to be something done to remove the installed file  on case sensitive os

**Comment by richard67** [comment]
> @richard67 if the filename is changed does there need to be something done to remove the installed file on case sensitive os

@brianteeman See here: https://github.com/joomla/joomla-cms/blob/5.0-dev/administrator/components/com_admin/script.php#L2311-L2319 . The tool which I use to generate/update the lists of deleted files and folders will also generate/update this list of renamed files.

**Comment by brianteeman** [comment]
Thanks @richard67 now lets see if anyone answers if the filename is right or wrong

**Comment by bembelimen** [comment]
Filename is wrong, you're right. [Fixed it here](https://github.com/joomla/joomla-cms/pull/41260/files#diff-5801e2fa6be4cc5e28c07c6f20e0a2d816aad9fa5168e2a5d6746f981f64386e)

**Comment by brianteeman** [comment]
Needs to be fixed the way @richard67 explained

**Comment by HLeithner** [comment]
we are in alpha, we have no upgrade promise between alpha so no it's not needed to do it like described by @richard67 

I'm closing this since we have a PR #41260

**Comment by richard67** [comment]
> we are in alpha, we have no upgrade promise between alpha so no it's not needed to do it like described by @richard67

@HLeithner That does not mean that we should break updates just because we can. Anyway, I will add that one line when I will make the deleted files and so on the next time.

**Comment by HLeithner** [comment]
it's use less to have this rename for all version upgrades till 5.4 in the update script.

**Comment by richard67** [comment]
> it's use less to have this rename for all version upgrades till 5.4 in the update script.

@HLeithner The same applies for all the other renames in the list. So you want  real updates for alphas just to save a few nanoseconds on each update? Maybe we should remove that function for renaming completely and just let things break like it was before we added that function.

So what I take from this is that I should stop to maintain the lists of deleted files and folders and renamed files in the 5.0-dev branch because it was obviously useless all the time.

**Comment by brianteeman** [comment]
In the distant past we had a policy NOT to support updates during development cycle but that changed. I forget when. Clearly that decision was made because we have been providing sql and file updates

**Comment by brianteeman** [comment]
Might as well stop building the nightly updates as well
