### ISSUE TITLE
[5.0] schemaorg Deprecated: Function strftime()

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41265]
### Steps to reproduce the issue
with the Blogposting schema use the date picker to add a date for published and modified date

### Expected result
date selected

### Actual result
Deprecated: Function strftime() is deprecated in libraries\src\Form\Field\CalendarField.php on line 322

![image](https://github.com/joomla/joomla-cms/assets/1296369/128d67cb-1580-4bee-95d4-5183e5748f41)

### System information (as much as possible)
php 8.1.10

### Additional comments
also tested with #41260 but no change

**Comment by korenevskiy** [comment]
It looks like we created a request at the same time, you created an ISSUE, I created a PR. I haven't seen your ISSUE.   😊

**Comment by richard67** [comment]
Closing as having a pull request. Please test #41266 . Thanks in advance.

**Comment by brianteeman** [comment]
Please re-open - that PR doesnt work

**Comment by joomdonation** [comment]
I don't understand how this feature works yet. However, to prevent this deprecated warnings, we should add missing `filterformat="Y-m-d"` after this line https://github.com/joomla/joomla-cms/blob/5.0-dev/plugins/schemaorg/blogposting/forms/schemaorg.xml#L156

We should search for all calendar fields under plugins/schemaorg folder and add the missing filterformat definition.

**Comment by bembelimen** [comment]
Wouldn't it be better to just fix it here: https://github.com/joomla/joomla-cms/blob/4.3-dev/libraries/src/Form/Field/CalendarField.php#L322C36-L322C36 ?

**Comment by joomdonation** [comment]
> Wouldn't it be better to just fix it here: https://github.com/joomla/joomla-cms/blob/4.3-dev/libraries/src/Form/Field/CalendarField.php#L322C36-L322C36 ?

Unfortunately, there is no reliable solution, see https://github.com/joomla/joomla-cms/pull/41266 for an example attempt. The easiest solution would be adding translateformat="true" to these fields, I made PR https://github.com/joomla/joomla-cms/pull/41453 for that. Please test, thanks !
