### ISSUE TITLE
[5.0] TinyMCE plugin source code (CodeMirror) not working

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#41278]
### Steps to reproduce the issue

Click button for `Source code +`

### Expected result

Here J4.3
![image](https://github.com/joomla/joomla-cms/assets/66922325/4bb97b24-0367-4868-a87a-e94989e69ac5)

### Actual result

![image](https://github.com/joomla/joomla-cms/assets/66922325/18e04c5f-0e64-412f-9c28-250e24d381d9)

### System information (as much as possible)

5.0.0-alpha4-dev

**Comment by HLeithner** [comment]
hmm I can replicate this on a new installation @Fedik any change to take a look at this?

**Comment by Fedik** [comment]
It need to be rewriten to support codemirror 6

**Comment by HLeithner** [comment]
oh I thought that was part of the initial pr. are we able to do this before the next release?

**Comment by Fedik** [comment]
Before one of next, for sure ;)

**Comment by HLeithner** [comment]
hmm... since motion is running in production about the releases I'm not sure what next is ;-)

**Comment by dgrammatiko** [comment]
@Fedik please consider https://github.com/joomla/joomla-cms/pull/40682 as it’s doing some basic cleanup 😉

**Comment by Fedik** [comment]
The fix will be there #41289, if I will finish it :)
