### ISSUE TITLE
[4.4][5.0] [Bootstrap 5.3] list group item action missing border

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#41284]
### Steps to reproduce the issue

create new menu item

### Expected result

J4.3-dev
![image](https://github.com/joomla/joomla-cms/assets/66922325/0c307e4e-a40b-4a25-bf84-74acfccc9a88)

### Actual result

J4.4-dev
![image](https://github.com/joomla/joomla-cms/assets/66922325/820b1026-7ab1-46ad-93eb-7f5d7196381d)

### Additional comments

![image](https://github.com/joomla/joomla-cms/assets/66922325/62f8b350-230b-4d00-beab-a6c91bbf8490)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #41286 . Thanks in advance.
