### ISSUE TITLE
[4.4][5.0] [Bootstrap 5.3] colour issue module loginsupport

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#41283]
### Steps to reproduce the issue

open backend

### Expected result

J4.3-dev
![image](https://github.com/joomla/joomla-cms/assets/66922325/1ac872ad-5414-4c29-a074-673d7de6f251)

### Actual result

J4.4-dev
![image](https://github.com/joomla/joomla-cms/assets/66922325/9f1d3dc6-109f-4e05-816d-58cacaa48e4b)

### Additional comments

```diff
 .card {
   [...]
   height: var(--card-height);
+  color: var(--body-color);
   word-wrap: break-word;
   [...]
 }
```

**Comment by richard67** [comment]
Closing as having a pull request. Please test #41286 . Thanks in advance.
