### ISSUE TITLE
Window title for contact is no longer displayed in the backend

### ISSUE THREAD

**Issue by WM-Loose** [joomla/joomla-cms#41281]
Backend /Site / configuration
In Joomla version 4.3.3 the window tile for contact is no longer displayed in the backend. 
You can activate it, but there is no display. It still worked in version 4.3.2.

Info from deltapapa german JForum:
https://forum.joomla.de/thread/19081-kontakt-mit-anzahl-im-dashboard-wird-nicht-mehr-angezeigt/

![1](https://github.com/joomla/joomla-cms/assets/99647423/8a8647d8-7514-4988-a6ef-1809257bec32)

**Comment by WM-Loose** [comment]
Link to Joomla Issue Tracker:
https://issues.joomla.org/tracker/joomla-cms/41280

**Comment by brianteeman** [comment]
fixed - please test #41282 

(issue tracker and github are the same thing - you dont need to create the report twice)

Can be closed

**Comment by WM-Loose** [comment]
thank you for the info

**Comment by richard67** [comment]
Closing as having a pull request. Please test #41282 . Thanks in advance.
