### ISSUE TITLE
Contact quick icon on the dashboard (home page of the administrator area) does not load

### ISSUE THREAD

**Issue by deltapapa01** [joomla/joomla-cms#41280]
After updating to Joomla 4.3.3, the quick icon "Contact" is no longer loaded in the backend in the administrator dashboard.
Neither with number or without number of contacts.
Test with J5 Alpha 4 DEV also confirmed the behavior.

PHP: 8.2.8

**Comment by brianteeman** [comment]
confirmed

**Comment by brianteeman** [comment]
Please test #41282

**Comment by richard67** [comment]
Closing as having a pull request. Please test #41282 . Thanks in advance.
