### ISSUE TITLE
mod_custom don't pull up custom classes.

### ISSUE THREAD

**Issue by SinProgress** [joomla/joomla-cms#41287]
In the advanced options you can enter the classes you want to use to customize the module, but it doesn't load them.

**Comment by alikon** [comment]
please add more details and/or use the issue template,  otherwise is hard to answer

**Comment by brianteeman** [comment]
Usually this is because the module chrome being used does not support the output of classes

**Comment by brianteeman** [comment]
This can be closed for the reason I stated above.
