### ISSUE TITLE
com_messages notification plugin not sending/creating message

### ISSUE THREAD

**Issue by bazmoth** [joomla/joomla-cms#41294]
### Steps to reproduce the issue
Create a new user group with permission core.manage on com_messages, add user to this group. Create a content transition (workflow) that sends a notification to this new group.
(likely possible to replicate multiple ways)

### Expected result
A new message sent to a user (in a user group that is not super user), when an article transition is performed.

### Actual result
No message is created/emailed to the user in question.

### System information (as much as possible)
Joomla 4.3.3

### Additional comments
This looks like a typo in this file: plugins/workflow/notification/notification.php on line 202, "com_message" instead of "com_messages" in the authorisation condition.

**Comment by brianteeman** [comment]
Thank you for reporting this. Yoiu are right its definitely a typo and I have created a pull request to fix it see #41295

**Comment by alikon** [comment]
please test #41295
