### ISSUE TITLE
[J4.4] API categories description

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#41291]
### Steps to reproduce the issue

Do an API call and set the category description:
![image](https://github.com/joomla/joomla-cms/assets/906604/2727e434-3aca-4137-8621-0883860d4d6e)
```
{
    "access": 1,
    "alias": "cat 2",
    "extension": "com_content",
    "language": "*",
    "note": "",
    "parent_id": 1,
    "published": 1,
    "title": "Title 3",
    "description": "TEXT"
}
```

### Expected result
 in the body result the description field must be visible

### Actual result
no description:
![image](https://github.com/joomla/joomla-cms/assets/906604/6844bd16-eb23-4af0-801f-791da1a97925)

### System information (as much as possible)

Joomla 4.4

### Additional comments
Same problem on all categories (like content) and with GET categories (List of Categories)

**Comment by alikon** [comment]
please test #41307
