### ISSUE TITLE
Can't Json decoding media type field

### ISSUE THREAD

**Issue by giudansky** [joomla/joomla-cms#41306]
I'm updating my J3/J4 template which uses the media type custom fields in a subform, exactly with the new metadata you're reporting.

I'm getting my custom field including the media type, JSON decoding it as I always did. (And as it still seems to be the way):
$rawData = json_decode($myFields['image-gallery'], true);

The problem is $rawdata always result "$rawData is not set". Json in the db is plain and correct.
Echoing $myFields['image-gallery'] without decoding, prints out an "ul class=fields-container li" list with the media images, so everything is there. This is strange because i'm expecting to get my raw json data!
![screen shot 2023-08-02 at 06 25 48](https://issues.joomla.org/uploads/1/0211138069a476c2c1d10571644915db.jpg)

Tried everything, but missing something please help me

Thanks

**Comment by brianteeman** [comment]
Take a look at cleanImagueURL in the for developers section https://github.com/joomla/joomla-cms/pull/30784

**Comment by giudansky** [comment]
I saw it. But the problem looks like I can't decode json. I'm only able to echo the subform with media custom field, resulting in a ul li render but no raw data.
Json decode does not work. When i'll be able to get the raw data for sure I will use cleanImageURL, but it seems to be a problem before that.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41306">issues.joomla.org/tracker/joomla-cms/41306</a>.</sub>

**Comment by Hackwar** [comment]
Where do you get your $myFields from? It looks like that array is built from the ->value attributes of the fields and not ->rawvalue. The former contains a pre-rendered version of the data, the later contains the raw data.

**Comment by giudansky** [comment]
I'm getting custom fields in this way:

```
// GET CUSTOM FIELDS
use \Joomla\Component\Fields\Administrator\Helper\FieldsHelper;

$jcfields = FieldsHelper::getFields('com_content.article', $this->item, true);
$myFields = array();
foreach ($jcfields as $field) {
	$myFields[$field->name] = $field->value;
}
```

**Comment by richard67** [comment]
@giudansky As Hannes said, you have to use rawvalue:

`$myFields[$field->name] = $field->rawvalue;`

**Comment by Hackwar** [comment]
As said, you are getting the data from the wrong place. So I'm closing this here. If you feel like this has been closed wrongly, please respond again and we'll open it again.
