### ISSUE TITLE
Menu Item Module Assignment Part Toggle All Does Not Work As Expected

### ISSUE THREAD

**Issue by JoomlaTema** [joomla/joomla-cms#41309]
### toggle should display a dropdown to select sub menu items.

See attached video please.

**Comment by JoomlaTema** [comment]
See Attached video please: https://youtu.be/YcusLGeInnM<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41309">issues.joomla.org/tracker/joomla-cms/41309</a>.</sub>

**Comment by Quy** [comment]
@C-Lodder Can you please look into this? Thanks.
