### ISSUE TITLE
Notify users when they are assigned to a new user group

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#41315]
I stumbled on this suggestion while browsing joomla forum and I think it's a legitimate feature:
Notify users when they are assigned to a new user group
...unless, like the OP, it does exist and I didn't know how to do it.

**Comment by Hackwar** [comment]
Yes, this is a usefull feature for some sites, but for basically all sites out there, the expectation for "what should happen when" are completely different. In the end, this is a very good feature for the third party extensions market. Joomla itself will not implement something like this.
