### ISSUE TITLE
Joomla 4.3.3 New User Notification Email Clear Password

### ISSUE THREAD

**Issue by thering1975TG** [joomla/joomla-cms#41328]
### Steps to reproduce the issue
I edited the Users: New User - en-GB email template with custom HTML (for users created in backend)
Used the {password} Tag to insert the users password into the email (selected from insert tags on RHS)

### Expected result

Email should show the users password that was created by admin in the backend

### Actual result

Email shows the words: {PASSWORD_CLEAR} where the password tag was inserted, all other tags show the correct information

### System information (as much as possible)
Joomla! 4.3.3 Stable [ Bora ] 11-July-2023 16:00 GMT
PHP 8.1.21
10.11.3-MariaDB-1
utf8mb4_general_ci
Apache/2.4.57 (Debian) OpenSSL/3.0.9 mod_fcgid/2.3.9
fpm-fcgi

### Additional comments

As mentioned the username, email and site url tags display correctly, only the password tag shows as {password_clear}

**Comment by richard67** [comment]
@thering1975TG Have you edited the right email template? There are several different ones for user activation. As far as I understand, the one which you want to use is named "Users: New account with admin activation (with PW)" and has as description:

> Notification about new account to the user, which will now have to be activated by an admin. The cleartext password is included in the mail.

When editing that template, the "Insert Tags" section has a tag "password_clear". That's the one you want to be sent.

Please check and report back if that helps you. Thanks in advance.

**Comment by richard67** [comment]
In general only the email templates marked with a green frame in the following screenshot sent a cleartext password:
![2023-08-07_j3-issue-41328](https://github.com/joomla/joomla-cms/assets/7413183/ea365bc5-f933-4e2e-bdae-021cb1abf343)

**Comment by brianteeman** [comment]
I am unable to replicate this.

I changed the email for the following template
![image](https://github.com/joomla/joomla-cms/assets/1296369/561d9533-4eba-4267-ae91-a9df48f287d5)

![image](https://github.com/joomla/joomla-cms/assets/1296369/39f11677-bed7-44f3-8157-4b5f4a281094)

I registered a new user from the admin and the email received contained the correct replacement values
![image](https://github.com/joomla/joomla-cms/assets/1296369/a0bf84ae-0c83-47db-a91d-61e2c0e05cbd)

**Comment by Quy** [comment]
Closing due to no response from the poster.
