### ISSUE TITLE
remove archived content from finder / smart search

### ISSUE THREAD

**Issue by nzyeehaa** [joomla/joomla-cms#41339]
while I have a number of issues with smart search and the old search is not working on my upgraded site...
I have made a clean install of J4.1 to test the smart search / finder operation.

#### filters were unable to remove archived pages

on my clean install I added a page called...
- published art which was published
- unpublished art which was unpublished
- archived art which was archived
- trashed art which was trashed

and did a search for _art_ - finder displays ...
- published art
- **archived art**

I don't want archived pages showing up in my search results...
to stop this "_feature_" from happening...
open `administrator\components\com_finder\src\Indexer\Adapter.php`
navigate to the bottom of the page - (line 901 on my file) and look for "case 2: " then comment it out like this...

```
// Published ~and archived items only~ should return a published state
case 1:
// case 2:
return 1;
```
go to administrator panel > components > smart search > index and press the "index" button at the top

search should omit them from search results. (Your mileage may vary - you may need to delete the index and do a re-index)

**Be aware** - future updates may break these changes, so until they are included in the core, you may need to redo this process every time you update Joomla.

Hope it helps someone.

(explanation...
case -2 is trashed
case 0 is unpublished
case 1 is published
case 2 is archived)

_Originally posted by @nzyeehaa in https://github.com/joomla/joomla-cms/discussions/37754#discussioncomment-2825628_

**Comment by nzyeehaa** [comment]
@Hackwar I first reported this some time ago, but it is still happening in 4.3.3 so have manually updated files as listed above

**Comment by Hackwar** [comment]
I have been thinking about this a lot and I was about to refuse this feature. However, I then saw that we had an option for this in com_search, so I've written a PR to add this into 5.0. Please test PR #41504 

Since we have a PR, I'm closing this issue.

**Comment by nzyeehaa** [comment]
@Hackwar  thanks and good work...

for the indecision...
Joomlas native workflow **hides** archived pages.
in the front end,
a page marked archived does not show in a blog/list layout (tested with fresh install/cassiopeia)
a page marked archived does not show on the homepage (tested with fresh install/cassiopeia)
>if you specifically enter the articles url it _will_ show - but this may be due to a current routing issue

in the backend, 
search for an archived article and it will not show up
archived pages are **hidden** unless you specifically filter for archived
