### ISSUE TITLE
Handling periods in com_finder search string

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#41338]
### Steps to reproduce the issue

Enter search string **.net**

### Expected result

All occurrences of **.net** found
For instance: _I am looking for a **.net** developer_

### Actual result

Nothing found

### System information (as much as possible)

PHP 7.2

### Additional comments

Searching for string **net** works i.e. without the period prefix.
See function tokenise($input) in Languager.php for search string parsing.
I thought I might be able to override this with a _finder_ plugin but there is no obvious way to do that.

**Comment by brianteeman** [comment]
I can confirm this and consider this a bug

**Comment by alikon** [comment]
please test #41353
