### ISSUE TITLE
Joomla 5 articles loos HTML format

### ISSUE THREAD

**Issue by Frits1969** [joomla/joomla-cms#41331]
I try Joomla 5.0.0Alpha3

I do not know if it is a bug or something I can fix by my self.
I creat of modify an article in TinyMCE. When I save the article, I lost all my text format. So I don't have any HTML caracters in the CodeMirror editor.

I can fix my text by create a good looking text, copy the HTML code and past it in the database in ....content
But I believe that's not the way.

**Comment by Fedik** [comment]
Hi, thanks for the reaport.
The fix for this bug will be there #41259

**Comment by Frits1969** [comment]
Thanks @Fedik for the link to the isue. But it is a lot of text in English. I do not understand. Do I need to do some thing to fix it or can I wait for Alpha4 or Beta1? 
I'm not hurry for this.
