### ISSUE TITLE
Joomla 4.3.3  Class "Joomla\Component\Installer\Administrator\Service\HTML\Updatesites" not found 

### ISSUE THREAD

**Issue by Lordnnud** [joomla/joomla-cms#41337]
### Steps to reproduce the issue
brand new virgin install of Joomla 4.3.3 with php 8 and Mysql

After install logged into admin and went to system -> Updates -> Joomla

### Expected result
for it to work

### Actual result

     0 Class "Joomla\Component\Installer\Administrator\Service\HTML\Updatesites" not found 

Call stack
# 	Function 	Location
1 	() 	JROOT/administrator/components/com_installer/src/Extension/InstallerComponent.php:50
2 	Joomla\Component\Installer\Administrator\Extension\InstallerComponent->boot() 	JROOT/libraries/src/Extension/ExtensionManagerTrait.php:180
3 	Joomla\CMS\Application\CMSApplication->loadExtension() 	JROOT/libraries/src/Extension/ExtensionManagerTrait.php:51
4 	Joomla\CMS\Application\CMSApplication->bootComponent() 	JROOT/administrator/components/com_joomlaupdate/src/Controller/DisplayController.php:61
5 	Joomla\Component\Joomlaupdate\Administrator\Controller\DisplayController->display() 	JROOT/libraries/src/MVC/Controller/BaseController.php:678
6 	Joomla\CMS\MVC\Controller\BaseController->execute() 	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
7 	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() 	JROOT/libraries/src/Component/ComponentHelper.php:361
8 	Joomla\CMS\Component\ComponentHelper::renderComponent() 	JROOT/libraries/src/Application/AdministratorApplication.php:143
9 	Joomla\CMS\Application\AdministratorApplication->dispatch() 	JROOT/libraries/src/Application/AdministratorApplication.php:186
10 	Joomla\CMS\Application\AdministratorApplication->doExecute() 	JROOT/libraries/src/Application/CMSApplication.php:293
11 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT/administrator/includes/app.php:61
12 	require_once() 	JROOT/administrator/index.php:32 

### System information (as much as possible)

Setting 	Value
PHP Built On 	Linux cloud217.xxxxx.co.uk 4.18.0-305.17.1.lve.el7h.x86_64 #1 SMP Wed Sep 8 04:44:37 EDT 2021 x86_64
Database Type 	mysql
Database Version 	5.7.43
Database Collation 	utf8_general_ci
Database Connection Collation 	utf8mb4_general_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	Yes
PHP Version 	8.0.29
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 4.3.3 Stable [ Bora ] 11-July-2023 16:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/116.0

**Comment by Lordnnud** [comment]
I'm running this in a sub-domain. My environment is hosted by Plesk.

looking at log file I see :-1: 

[Tue Aug 08 09:29:15.103866 2023] [fcgid:warn] [pid 698316:tid 140142662125312] [client 34.240.128.230:52484] mod_fcgid: stderr: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/vhosts/xxxxxxxx.co.uk/httpdocs/libraries/vendor/joomla/string/src/phputf8/ord.php on line 28
[Tue Aug 08 09:29:15.111032 2023] [fcgid:warn] [pid 698204:tid 140142492739328] [client 34.240.128.230:52500] mod_fcgid: stderr: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/vhosts/xxxxxxxx.co.uk/httpdocs/libraries/vendor/joomla/string/src/phputf8/ord.php on line 28
[Tue Aug 08 09:29:15.114047 2023] [fcgid:warn] [pid 698262:tid 140142509524736] [client 34.240.128.230:52512] mod_fcgid: stderr: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/vhosts/xxxxxxxx.co.uk/httpdocs/libraries/vendor/joomla/string/src/phputf8/ord.php on line 28
[Tue Aug 08 09:29:15.976749 2023] [fcgid:warn] [pid 698262:tid 140142484346624] [client 34.240.128.230:52528] mod_fcgid: stderr: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/vhosts/xxxxxxxx.co.uk/httpdocs/libraries/vendor/joomla/string/src/phputf8/ord.php on line 28
[Tue Aug 08 09:29:15.992783 2023] [fcgid:warn] [pid 698262:tid 140142433990400] [client 34.240.128.230:52524] mod_fcgid: stderr: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/vhosts/xxxxxxxx.co.uk/httpdocs/libraries/vendor/joomla/string/src/phputf8/ord.php on line 28
[Tue Aug 08 09:44:57.217209 2023] [fcgid:warn] [pid 698316:tid 140142543095552] [client 38.153.31.223:55608] mod_fcgid: stderr: PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /var/www/vhosts/xxxxxxxx.co.uk/httpdocs/libraries/vendor/joomla/string/src/phputf8/ord.php on line 28, referer: https://www.xxxxxxxx.co.uk/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41337">issues.joomla.org/tracker/joomla-cms/41337</a>.</sub>

**Comment by Quy** [comment]
> running this in a sub-domain. My environment is hosted by Plesk.

Is this a different installation? If yes, please advise Joomla version. Please post line 28 in /libraries/vendor/joomla/string/src/phputf8/ord.php.

**Comment by Lordnnud** [comment]
This issue is closed, after a lot of work, turns out that the FTP upload was in someway corrupting a file.

Uploaded using another method, everything works as it should.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41337">issues.joomla.org/tracker/joomla-cms/41337</a>.</sub>
