### ISSUE TITLE
Joomla 4.3.2 User Manager Error

### ISSUE THREAD

**Issue by dirkbai** [joomla/joomla-cms#41341]
### Hello we're just in the process of updating our Website Steiger.org to Joomla 4.

We created a copy of the Website https://demo.steiger.org/ for testing. Unfortunately, there is an Error (Screenshot Error 1) with the User Managers. There is also an Error at the Login that might be related (Screenshot Error 2)![screen shot 2023-08-09 at 09 35 28](https://issues.joomla.org/uploads/1/460bf5b723b536c241612fc34b508b27.jpeg).

### Expected result
Please help us to resolve this Errot that the User Manager works again.

### System information (as much as possible)
Joomla 4.3.2 User Manager Error

### Additional comments

![screen shot 2023-08-09 at 09 35 30](https://issues.joomla.org/uploads/1/905b16bcd03c8b2e3fb6d2e12daef06a.jpeg)

**Comment by alikon** [comment]
that's not a core joomla issue, come from easyblog

**Comment by brianteeman** [comment]
As @alikon says. This issue comes from easyblog and not Joomla itself and you should contact tyhe developers of easyblog.


Can be closed as not core.
