### ISSUE TITLE
Article intro image is not shown when file extention is in caps

### ISSUE THREAD

**Issue by AboutTimeIT** [joomla/joomla-cms#41343]
Create two images, one of them has to be with the file-extention in CAPS.
Upload both files by FTP (not via media manager)
Both files should be visable in the media manager and one of them with caps as extention
Create a new Article and select the file with the CAPS as intro image.
Is should not get visable.
Select the image with small caps. The image should get visable.

Upload an image wit a caps extention by the media upload. The extention should be changed to small caps.

### Expected result
I would expect both extentions to get visable

### Actual result
Image with cpas file extention is not visable

### System information (as much as possible)
Joomla! 4.3.3

### Additional comments
Uploaded an image via FTP (Filezilla) with the extention in CAPS
(example: test.JPG)
The image path is shown in the Article under the view of the image with the extention in caps.
But the image is not shown.

When the same image, with the extention in caps, is uploaded by the mediafolder upload then the extention is changed to small caps. (example: test.jpg).
When added this image as an Article intro image then the image is shown.

This is also in the Custom Field media

**Comment by richard67** [comment]
Is your webserver a Linux server? Or Windows?

**Comment by AboutTimeIT** [comment]
![screen shot 2023-08-09 at 11 22 41](https://issues.joomla.org/uploads/1/0d83d11b6850b08c3ef32b80d6b390ab.jpg)![screen shot 2023-08-09 at 11 22 43](https://issues.joomla.org/uploads/1/8ed4bb0d49c37a9a3062fbf3a261d28d.jpg)![screen shot 2023-08-09 at 11 22 45](https://issues.joomla.org/uploads/1/27af69363aa55095388874f94053a0c7.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41343">issues.joomla.org/tracker/joomla-cms/41343</a>.</sub>

**Comment by AboutTimeIT** [comment]
Build System 	Linux
PHP Version 	8.1.14<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41343">issues.joomla.org/tracker/joomla-cms/41343</a>.</sub>

**Comment by chmst** [comment]
Are both file extentions allowed in media options?

**Comment by brianteeman** [comment]
I can confirm the reported issue.

A fix is to add the capitalised extension in the media options for allowed image extensions

![image](https://github.com/joomla/joomla-cms/assets/1296369/4f862f32-51bf-4a0a-a840-6ae11918a7c4)

However I consider this as a bug or unexpected behaviour as the media manager itself has no problem displaying the uppercase file its just 9in the field preview

**Comment by alikon** [comment]
plese test #41356
