### ISSUE TITLE
Feature Request for Joomla 5.x - Add a parameter for edit menu item in Category List

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#41346]
### Is your feature request related to a problem? Please describe.
The Category List has a nice feature to offer an “add item” button. 
The Joomla Router is searching for the nearest Item that has added item feature and redirects the user there.
Which is almost a bug for me.
For example:
I have a Menu Item Press releases and in the Second Level “Add Press release”
I have a Menu Item Jobs and in the Second Level “Add Job”.

When I click on the “Add Article” Button in the Menu Item Jobs, I get redirected to the menu item press/add-pressrelease
Because that's the first item edit element the router can find.

I already reported that to @Hackwar, and it's just like the router works.

### Describe the solution you'd like

My dream-solution would be that the router would look for the “nearest item” and not the first.
But another solution could be a selection in the category list to select where the Add Button should redirect to.

### Additional context
Adding Articles from the Frontend is for some use cases very mandatory because some are just “Guest” at the site and should not do anything in the backend. I have this issue for two independent NGO websites and one Company, where the members submit articles through this categorylist. For me it's a bug.

**Comment by brianteeman** [comment]
dupliacte of #39558  ?

**Comment by coolcat-creations** [comment]
Thank you, yes! Closing then...
