### ISSUE TITLE
[4.3] Creating template files with minus sign fails

### ISSUE THREAD

**Issue by ManuelHu** [joomla/joomla-cms#41368]
### Steps to reproduce the issue
* Open a template in the com_templates file browser
*  Try to create a (e.g. PHP) file that contains a minus sign, e.g. enter `contains-minus` as a file name

### Expected result
The file `contains-minus.php` is created. This is a totally valid filename.

### Actual result
The file is not created, and an error message is shown:

https://github.com/joomla/joomla-cms/blob/ae2a409d5496a489a2638f0cbf442356aa89a163/administrator/language/en-GB/com_templates.ini#L158

The error message states that the action should indeed be allowed...

### System information (as much as possible)
* Joomla 4.3

### Additional comments
The bug has been introduced in PR #38987, that removed the trailing `-` after the `0-9` in the regex. Was there any reason to this, @brianteeman?

**Comment by ManuelHu** [comment]
This is especially bad, as files with underscores cannot be used as module/component/... layout overrides, e.g.

https://github.com/joomla/joomla-cms/blob/642de295a9fe1220c05643c437aae416e4fbe11b/libraries/src/Form/Field/ModulelayoutField.php#L134-L135

**Comment by brianteeman** [comment]
there is no problem at all creatig a file with an underscore

**Comment by ManuelHu** [comment]
That's right, you can create files with underscores. But you cannot create a file with a minus sign - sorry about the confusion...

**Comment by richard67** [comment]
Closing as having a pull request. See #41369 .
