### ISSUE TITLE
Option "Browser Page Title" not working

### ISSUE THREAD

**Issue by wegwei** [joomla/joomla-cms#41372]
### Steps to reproduce the issue
I create an article and add a title into the field "Browser Page Title" in the tab "Options" - e.g. "xxx my SEO optimized title-text xxx".
Then I create a menu-item for this article. Here (in the menu-item) I do NOT add text into the field "Browser Page Title" in the tab "Page Display", the field is still empty. 

### Expected result
The title-tag (<title></title>) in the code of the frontend should show the title which I have set into the article, into the field "Browser Page Title" (= xxx my SEO optimized title-text xxx). 

### Actual result
It shows the wront text in the  title-tag (<title></title>): It shows the "MENU title" (= the wording of the textlink in the menu) instead of the "Browser Page Title" (= xxx my SEO optimized title-text xxx). 

### System information (as much as possible)
Joomla! 4.3.3 with YOOtheme Version 4.0.10

### Additional comments
I refer to the issue [#28468 ](https://github.com/joomla/joomla-cms/issues/28468) . a comment here says that the issue is solved: https://github.com/joomla/joomla-cms/pull/39249. but it isn't...

**Comment by coolcat-creations** [comment]
Agree, just tested with Cassiopeia and same issue.

**Comment by brianteeman** [comment]
Browser page title from the article is only used when there is NO single menu item for the article eg when the article is in a blog category or featured view

**Comment by coolcat-creations** [comment]
@brianteeman what was the aim of this fix then: https://github.com/joomla/joomla-cms/pull/39249 ?

**Comment by brianteeman** [comment]
dont really know but it is inside a code block that says
        // If the menu item is not linked to this article

**Comment by brianteeman** [comment]
no. the code you are referring to will only be used If the menu item is not linked to this article

**Comment by coolcat-creations** [comment]
It says: Expected result AFTER applying this Pull Request

Joomla use Browser Page Title **setup in the article** for Browser Page Title.

**Comment by wegwei** [comment]
hm. It is not logical. 

It is okay that the menu-item-title is overwriting the article-item-title. 

But it is not logical when the PAGE title is being displayed instead of the browser title (which was specially inserted).

It really seems to be a bug. The fact that the error has already been fixed in the past confirms that. Maybe the fix was lost by accident during an update. It would be great if this could be corrected again.

Many thanks

**Comment by wegwei** [comment]
P.S. stop. I've made a mistake in my description. Not the PAGE title is displayed - but the MENUE title (the link text which is visible in the menue). But nethertheless - it is not logical and it does not change the problem itself.

**Comment by brianteeman** [comment]
@wegwei can you please give a full description of exactly what you are doing and what is displayed and what you expect to be displayed.

**Comment by wegwei** [comment]
no problem.
-> I have updated the first post "Steps to reproduce the issue..." with the correct wording and with more details.

**Comment by wegwei** [comment]
If necessary I could send some screenshots?

**Comment by wegwei** [comment]
hi brian, yes, your scenario describes the actual result. 

but this is not logical: If this was the planned scenario, so it would be necessary very often to add the title twice: in the article for showing it by listing in category blogs and also in the menu item for showing through direct links. 

in practical use it is very often needed to list articles through category blog AND to set a link to some of the content pages. so it would be necessary to add the title tag *** twice. by doing seo optimizations it is also necessary to update both... I can't imagine that this is the conceptual planning.

*** and the handling of the meta tag "description" is similar. but this issue is in another way unlogical:
by changing the meta description in the menu item it is NOT displayed and it shows still the meta description out of the article item.

please find both scenario in the screenshot: 

![title2](https://github.com/joomla/joomla-cms/assets/142310020/5b573e88-c22d-4314-af3a-a8c38dabfac3)

**Comment by brianteeman** [comment]
> in practical use it is very often needed to list articles through category blog AND to set a link to some of the content pages. 

Never had a need for that myself but I just checked and if you do that then both articles will of course use the settings for the inidividual menu item

**Comment by wegwei** [comment]
thanks brian for your help.

yes, we are using the described scenario very often and for us it would be important to solve the issue. 

I would be happy if the developers would take up this issue.

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/41452 should solve this issue. Please help testing, thanks !
