### ISSUE TITLE
Action Log: Block/Unblock user

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#41374]
### Describe the solution you'd like
The Joomla Action Logs currently don't log when a user is blocked or unblocked. These activities should be logged as well.

**Comment by alikon** [comment]
can go on 4.4 or should go to 5.0 ?

**Comment by brianteeman** [comment]
Its a new feature so it has to be 5.x

**Comment by alikon** [comment]
please test #41377

**Comment by Hackwar** [comment]
We are also not logging when a user is deleted.
