### ISSUE TITLE
com_tag add fields

### ISSUE THREAD

**Issue by JoomlaBelarus** [joomla/joomla-cms#41375]
### Is your feature request related to a problem? Please describe.
I want to add additional field in tag. I need add a link. If possible use field from template in Jommla4 - its good, but now it is not working.

**Comment by Jan-dax** [comment]
It would be very cool if the tag component had the same fields with links, as for example in the content, then it would not be a problem to write there a link to a file, and in the constructor yootheme use the output of only this field
