### ISSUE TITLE
[4.3] Filtering for non-core extensions closes the searchbar

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#41382]
### Steps to reproduce the issue
* open /administrator/index.php?option=com_installer&view=manage
* Select the last filter "non-core extensions"

### Expected result
* page releoad
* searchbar is still open

### Actual result
* page releoad
* searchbar is closed open

**Comment by brianteeman** [comment]
Confirmed

**Comment by alikon** [comment]
please test #41383
