### ISSUE TITLE
Mismatched tag ids/tag names in articles webservice/api

### ISSUE THREAD

**Issue by phihu** [joomla/joomla-cms#41392]
Hey everyone, 
I rarely work with joomla, but ran into this issue.

The issue also seems to affect the filter functionality (but I had no time to properly test this) and might be related to issues #38355, #40068 and #40069.

At least for the wrong API return the cause seems quite clear (see below).

### Steps to reproduce the issue

Request any article via the webservice/API that has tags assigned to it.
The ids and names of the tags are/might be mismatched (could have been caused by re-sorting/changes to the tags hierarchy/nesting).

This is the basic tag structure:

![screen1](https://github.com/joomla/joomla-cms/assets/1455315/71cd6a69-e23a-4bd6-a685-bfce189d8db7)
![screen2](https://github.com/joomla/joomla-cms/assets/1455315/044b26f8-b861-4199-b9b1-aeffccbca391)

And an article with tags "M" (ID 2), "T" (ID 3) and "D" (ID 26) assigned to it.

### Expected result
Result having matching IDs/names 

```javascript
...
state: 1,
tags: {
   2: "M...",
   3: "T...",
  26: "D..."
}
...
```

### Actual result
IDs/name do not match

![result](https://github.com/joomla/joomla-cms/assets/1455315/0a4d3103-c1d8-4aa6-b75a-e1e4861647fd)

### System information (as much as possible)

Joomla! Version: 4.3.3
PHP Version: 8.1.21

### Additional comments

The cause for the mismatched API return can be found here:
[api/components/com_content/src/View/Articles/JsonapiView.php](https://github.com/joomla/joomla-cms/blob/4.3-dev/api/components/com_content/src/View/Articles/JsonapiView.php#L217-L232)

In both cases highlighted `$tagsIds` and `$tagsNames` do not (necessarily) match (automatically) and should be properly checked/associated with each other or their right order has to be guaranteed. 

Perhaps it would be better to either fetch the tag data including the names based on the item ID (see [`TagsHelper::getTagIds`](https://github.com/joomla/joomla-cms/blob/4.3-dev/libraries/src/Helper/TagsHelper.php#L470)) or to change the underlying queries, so that both the tags within the items object and the return from `getTagIds` have a guaranteed (and stable) order.
At first glance, `getTagIds` does not seem to have any order specified in the query - which means, it is not guaranteed.

Again, unfortunately I really know very little about joomla's structure and the effect changes might have, so unfortunately I cannot provide a fix.

**Comment by alikon** [comment]
please test #41397

**Comment by phihu** [comment]
First of all: Thanks for the quick response! 
You added `ORDER BY` statements to `TagsHelper::getTagNames` but none to `TagsHelper::getTagIds`, yet both methods are beeing called in  [JsonapiView.php](https://github.com/joomla/joomla-cms/blob/4.3-dev/api/components/com_content/src/View/Articles/JsonapiView.php#L217-L232). Further: Are you sure the order of the tag IDs derived from the item object are guaranteed/save?

**Comment by alikon** [comment]
@phihu  i've refactored https://github.com/joomla/joomla-cms/pull/41397  can you please test 
thanks in advance
