### ISSUE TITLE
[4.4] [5.0] Borders nearly invisible

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#41400]
### Steps to reproduce the issue

Checkboxes and the ordering minimenu was always very hard to see but now in J5 it is nearly invisible on my monitors.

Left screen: 4.3.4, Right screen: 5.0.

![grafik](https://github.com/joomla/joomla-cms/assets/1035262/12eb7586-9d55-4e44-8d37-e697d5cfb7f1)

**Comment by heelc29** [comment]
Exist also in 4.4 with bootstrap 5.3; already mentioned by @Quy https://github.com/joomla/joomla-cms/pull/41101#issuecomment-1646336897

**Comment by richard67** [comment]
I've changed the title so that it's clear that it's also an issue with 4.4.

**Comment by brianteeman** [comment]
the recent template updatyes for 5.1 seem to have massively improved this

![image](https://github.com/joomla/joomla-cms/assets/1296369/1f611fb5-6bc8-456d-bfae-c746e4c0fcc5)

**Comment by Quy** [comment]
Confirmed it is darker in v5.1.
