### ISSUE TITLE
compiler optimized functions 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41420]
is there any reason that we dont globally optimize all functions? 
https://tideways.com/profiler/blog/compiler-optimized-php-functions

especially as it can be automated

@HLeithner @wilsonge

**Comment by brianteeman** [comment]
should add that now is the ideal time to do it - it was not accepted in the build up to j4 as it was already beta iirc

**Comment by brianteeman** [comment]
> No recollection of reasons why/why not. seems more than reasonable at a glance through that blog post though

will create merge conflicts was the given reason https://github.com/joomla/joomla-cms/pull/33357#issuecomment-827627256

**Comment by Stuartemk** [comment]
> should add that now is the ideal time to do it - it was not accepted in the build up to j4 as it was already beta iirc

Yes, now is the ideal time to do it

**Comment by brianteeman** [comment]
see #41427
