### ISSUE TITLE
4.4 Debug language frontend to super admin logged

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#41438]
### Is your feature request related to a problem? Please describe.
Please introduce the possibility of debugging the language for super admin logged in the frontend while users can navigate the site normally

**Comment by brianteeman** [comment]
Is this not already possible ?

![image](https://github.com/joomla/joomla-cms/assets/1296369/9134bdb5-e712-4560-9bc3-fbd5d2021d4f)

**Comment by Stuartemk** [comment]
> Is this not already possible ?
> 
> ![image](https://user-images.githubusercontent.com/1296369/263066808-9134bdb5-e712-4560-9bc3-fbd5d2021d4f.png)

If the debbug plugin is enabled with the super user group selected and debugging language is enabled in the global configuration, when displaying the frontend of the site without logging in, the constants and value strings should not be displayed since default users are invited (they are not super user) but the value strings or constants are displayed. This is especially important on live or online sites as it is very useful to be able to debug the language without displaying the values ​​or constants to guests, and only displaying the values ​​or string constants to super user. In addition, it would also be very useful to be able to access the .ini files from the Backend within Joomla to be able to search and modify from within Joomla without an IDE or external text editor and, if necessary, make use of language override. Without these features it is very time consuming to have to access the language .ini files from outside of Joomla and switch to the Backend within Joomla to modify the .ini or override it.
![Screenshot_20230824_123809](https://github.com/joomla/joomla-cms/assets/54377809/9bdf1379-c48a-4c1d-b8ed-b0aeee480100)
![Screenshot_20230824_123205](https://github.com/joomla/joomla-cms/assets/54377809/0fc22551-33bd-45b6-a720-19fe88d481ef)

**Comment by brianteeman** [comment]
>  the value strings or constants are displayed. 

That is a bug

**Comment by Fedik** [comment]
The language debuging is a Global option, the same as Debug.
And ideally it should not be used on live site.

The Debug plugin works as expected.

It more like feature request.

**Comment by Fedik** [comment]
I would sugest to crate a global permission `core.debug`, similar to `core.admin`, `core.manage`.
Then it can be applied to global parameters: `debug`, `debug_lang`.

**Comment by brianteeman** [comment]
@fedik it seems odd to me that no debug functionality occurs if the user does not have the permissions for the debug plugin but when it comes to wrapping the text strings with ** that occurs based on the global setting only

**Comment by Fedik** [comment]
> no debug functionality occurs if the user does not have the permissions for the debug plugin

Debuggin still runnig independently from plugin. Example when you get a fatal error, you will see a page with detailed error trace. It also affects some other app stuff.

The plugin only for display collected information. It's permission only to display or not the "debug bar" .

With a language it is a bit tricky, because it is part of Language class. 
Curently we cannot controll what to display from the plugin.

**Comment by Fedik** [comment]
Hm, we probably can try to disable lang_debug, onAfterInitialise event with $language->setDebug(false), from plugin.
Hovewer it still may have a diferent behavior for public users.
Need to test some time.

**Comment by brianteeman** [comment]
> With a language it is a bit tricky, because it is part of Language class.

yes I saw that

**Comment by rdeutz** [comment]
I don't see the use case. Debugging shouldn't be regulary done on live sites.

**Comment by brianteeman** [comment]
> I don't see the use case. Debugging shouldn't be regulary done on live sites.

That's not a valid reason to kill this feature request.
