### ISSUE TITLE
4.4 Be able to edit the .ini language files from the Backend

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#41439]
### Is your feature request related to a problem? Please describe.

It would be very useful to be able to access the language .ini files both readonly for constant and string lookups and overriding language overrides ( avoiding modifying the original joomla .ini files as little as possible), as well as in Edit for edit the .ini files directly (especially for 3rd party components, modules, templates and plugins; )

**Comment by brianteeman** [comment]
How is what you are requesting any different to the language override facility already available

**Comment by Stuartemk** [comment]
> How is what you are requesting any different to the language override facility already available

The current override function works well, but it does not contain the possibility to see or modify the .ini files, to be clearer I will give an example: even if the super user group is chosen in the plugin and it is chosen to show constants in the configuration global constants are shown to all users including guest users, so in an online site it is not possible to use mshow language constants, which forces you to have to access the .ini files to find the string value using an external text editor and see what constant it corresponds to to return to the Backend and override the language, that is, in the override you can only modify the value of the constant if you know which constant to modify already that the search that is done inside override searches inside override (the search is not done inside the original language files) If the original language .ini files could be accessed from the Joomla Backend they could be quickly searched and found the corresponding constant that returns the value on the frontend and could be more easily overridden in the existing language override tool. This problem has been around since the beginning of existence in Joomla, forcing you to jump from the Joomla Backend to an external editor to find the constant and back to the Backend with each language string to modify, so when there are 2 or 3 chains is not that much work but if there are many constants it becomes heavier than climbing Mount Everest

**Comment by brianteeman** [comment]
why not search for the constant in the language override component

**Comment by Stuartemk** [comment]
> why not search for the constant in the language override component

You can't look for something you don't know. You need to access the original .ini to find the constant that is returned on the frontend. On an online site you can't show constants only to super user since it also shows constants to guest users.

**Comment by brianteeman** [comment]
Sorry I meant to write search for the value not constant

**Comment by Stuartemk** [comment]
> Lo siento, quise escribir buscar para el valor no constante

If you search for the string value of the constant within "Language Overrides" it will only search within the files in "Language Overrides" that is, within constants already modified and NOT within the original .ini files, so if you search for example the value "Example Value" that corresponds to the constant COM_MY_COMPONENT_EXAMPLE_VALUE"
COM_MY_COMPONENTE_EXAMPLE_VALUE = "Example Value"

As long as the value and the constant have not been added inside "Language Overrides" it will not be in your files and there is no point in looking for it there, so if you know the value since it is in the frontend but you don't know the constant since On the online site, even if you select the super user group and show constants, it is shown to all users, including GUESTS, and since it is an online site, you will not want that, you will not want all users to see the language constants, so it is not option and you have no other option than to have to look for the constant that corresponds to "Example Value" in the original .ini file to be able to know its constant, only then you have to return to the Backend to enter COM_MY_COMPONENTE_EXAMPLE_VALUE = "Example Value" inside "Language Overrides"

As you can see it is not efficient at all.

On the other hand, if you could see the .ini files from the Backend as you do with the template files, it would at least be a little or much easier.
![Screenshot_20230824_154225](https://github.com/joomla/joomla-cms/assets/54377809/3fd53882-65a1-400a-bca6-b6759356a4e3)

**Comment by brianteeman** [comment]
> If you search for the string value of the constant within "Language Overrides" it will only search within the files in "Language Overrides" that is, within constants already modified and NOT within the original .ini files

Not true

**Comment by Stuartemk** [comment]
> > If you search for the string value of the constant within "Language Overrides" it will only search within the files in "Language Overrides" that is, within constants already modified and NOT within the original .ini files
> 
> Not true

Are you sure that "Language Overrides" searches inside all third party values of all components, modules, plugins and templates of all languages and Joomla addition?

I may be wrong but it seems to me that you are wrong.

I am not criticizing, the purpose is to solve, not to argue.

**Comment by brianteeman** [comment]
> 
> Are you sure that "Language Overrides" searches inside all third party values of all components, modules, plugins and templates of all languages and Joomla addition?
> 

Yes

**Comment by brianteeman** [comment]
@richard67 I am going to remove the feature label for now. From what I can tell the requested functionality is not needed as searching by value is already available and that solves the usecase.

@Stuartemk if you have an extension where you can not use the override component to search for its value please can you share it.

**Comment by Quy** [comment]
Closing due to no response with additional info.
