### ISSUE TITLE
[5.0] Error when creating an task 

### ISSUE THREAD

**Issue by webgras** [joomla/joomla-cms#41454]
### Steps to reproduce the issue
1. Go to "System" - "Scheduled Tasks"
2. create a new task (i.e. "Set Site Offline")
3. set some example name, fill in the necessary fields
4. save the task

### Expected result
Task is saved

### Actual result
An error has occurred.
Call to undefined method Joomla\Component\Scheduler\Administrator\Table\TaskTable::getCurrentUser() 
![Screenshot 2023-08-26 at 11-17-48 Error 0](https://github.com/joomla/joomla-cms/assets/10774704/97328b0b-c1bf-4dbe-aa46-51de282c4325)

### System information (as much as possible)
PHP 8.2
5.0.0-beta1-dev (nightly built)

**Comment by webgras** [comment]
@laoneo can you have look?

**Comment by joomdonation** [comment]
@webgras PR https://github.com/joomla/joomla-cms/issues/41454 should fix this issue. Please test, thanks !
