### ISSUE TITLE
[5.0] In Blog Sample Data update content, tags from "Joomla4" to "Joomla5"

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#41459]
### Steps to reproduce the issue
- Joomla 5 nightly build (25.8.23)
- with Blog Sample Data installed

You can find it for example here:
- index.php/component/tags/tag/joomla-4
- index.php/blog/your-modules
- index.php/sample-layouts/articles/joomla

**Comment by wilsonge** [comment]
Hint for those who want to fix this: https://github.com/joomla/joomla-cms/blob/5.0-dev/administrator/language/en-GB/plg_sampledata_blog.ini#L137

**Comment by brianteeman** [comment]
please test #41480
