### ISSUE TITLE
[5.0] Users manager: enable/disable icon triggers error

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#41450]
### Steps to reproduce the issue
In Joomla 5 go to Users > Manage, click on an Enabled icon to enable or disable a user account

![users](https://github.com/joomla/joomla-cms/assets/1217850/e0d8195f-64ef-4485-95dd-e652fda618a5)

### Expected result
The user account should be enabled or disabled

![Screenshot from 2023-08-26 10-34-20](https://github.com/joomla/joomla-cms/assets/1217850/ecc131fe-4cfc-4ae4-8ded-37a6a5de4f9c)

### Actual result
Instead an error occurs. And when you click the back button, the enabled/disabled state has changed anyway.

> An error has occurred.
0 Joomla\CMS\Event\User\AfterSaveEvent::setErrorMessage(): Argument #1 ($value) must be of type string, null given, called in /usr/local/apache2/htdocs/libraries/src/Event/AbstractEvent.php on line 205

![Screenshot from 2023-08-26 10-32-07](https://github.com/joomla/joomla-cms/assets/1217850/19df4956-7324-44ba-807a-cda1a486ce9d)

**Comment by brianteeman** [comment]
bug confirmed

**Comment by alikon** [comment]
same as  (https://github.com/joomla/joomla-cms/pull/41377#issuecomment-1694227663)

**Comment by Fedik** [comment]
Please test #41464

**Comment by pe7er** [comment]
Thanks!
