### ISSUE TITLE
[5.0] Deprecated: mb_strtolower() in search

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#41456]
### Steps to reproduce the issue
- Joomla 5 nightly build (25.8.23)
- with Blog Sample Data installed
- php 8.1.12
- MariaDB 10.4.27
- no 3rd components installed

with a search term and a start and end date (Assuming typography is required, and beginning date before Saturday, 26 August 2023, and ending date before Tuesday, 29 August 2023, the following 2 results were found.) I get this error message:
Deprecated: mb_strtolower(): Passing null to parameter #1 ($string) of type string is deprecated in C:\xampp\htdocs\joomla5\libraries\vendor\joomla\string\src\phputf8\mbstring\core.php on line 120

**Comment by Hackwar** [comment]
I can't replicate this.

**Comment by Quy** [comment]
Closing due to no response with additional info.
