### ISSUE TITLE
Module position forcing selection.

### ISSUE THREAD

**Issue by xtech86** [joomla/joomla-cms#4146]
#### Steps to reproduce the issue

Create a module and manually type in it's position for example:

mymodule_position

And save, all is perfect.

Then create another module and type in it's position for example:

mymodule

It will always auto select mymodule_position and will not let your select mymodule until any modules assigned to mymodule_position have been unassigned.

**Comment by brianteeman** [comment]
@Kixo are you able to contribute the code for that - sounds like a good solution

**Comment by Kixo** [comment]
I am sorry but I am very bad with time lately (deadlines) so I cannot solve this one any time soon...

**Comment by brianteeman** [comment]
Hi you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4146">issues.joomla.org/joomla-cms/4146</a>.</sub>
