### ISSUE TITLE
[5.0] Deprecated:  trim() ... when adding a tag in article

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#41466]
### Steps to reproduce the issue
- Joomla 5 nightly build (25.8.23)
- php 8.1.12
- MariaDB 10.4.27

I get this message in the error.log when I add a tag to an article:
PHP Deprecated:  trim(): Passing null to parameter #1 ($string) of type string is deprecated in C:\\xampp\\htdocs\\joomla5\\components\\com_tags\\src\\Controller\\TagsController.php on line 39, referer: http://localhost/joomla5/administrator/index.php?option=com_content&view=article&layout=edit&id=12

**Comment by Hackwar** [comment]
Please test the fix for this in #41509. Since we have a PR, I'm closing this one.
