### ISSUE TITLE
Archived articles shown with a strange path in breadcrumbs module

### ISSUE THREAD

**Issue by pl71** [joomla/joomla-cms#41476]
### Steps to reproduce the issue
Have some archived articles from different categories.
Make a breadcrumbs module.
Make module 'Articles - Archived'
In the frontend choose a month to display archived content.
Check what is displayed in the breadcrumbs module.

### Expected result
Actually, no idea what to expect there in case we have archived content from different categories.

### Actual result

Some strange and random path.

### System information (as much as possible)

The currently installed Joomla! version is "‎4.3.4"

**Comment by brianteeman** [comment]
It really is impossible to offer aany advice from the information given. What is "strange and random path"

**Comment by pl71** [comment]
After some playing with the menu assignment within Module "Modules: Articles - Archived" this strange behavior stopped. 
Presently Menu assignment is back on `all pages`.
And archived content is displayed on the `home` page where we have no breadcrumbs.
The only annoying thing is that this home page has a page title "News" which is not quite appropriate for the old archives.
You can close the issue if you can not reproduce it.
Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41476">issues.joomla.org/tracker/joomla-cms/41476</a>.</sub>

**Comment by brianteeman** [comment]
closed
