### ISSUE TITLE
[5.0] schemaorg types are not translatable

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#41471]
### Steps to reproduce the issue

enable language debug
open article edit view

### Expected result

all options should be translatable

### Actual result

![image](https://github.com/joomla/joomla-cms/assets/66922325/a4846cf1-dacd-4987-89f1-6d795e3d410a)

**Comment by HLeithner** [comment]
That are the official types from schema.org, so it make sense to make them not translatable.

On the other side you can translate temp if you just simple add them to your override.ini
BlogPosting=" What ever you want"

Closing this as expected
