### ISSUE TITLE
[5.0] tinyMCE migration faulty from prior versions of 5.0

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#41473]
### Steps to reproduce the issue

update from 5.0.0-alpha to 5.0.0-beta1-dev

### Expected result

jtemplate icon should be still there
![image](https://github.com/joomla/joomla-cms/assets/66922325/d60ac669-f288-4b0f-9410-5128aa4763c6)

### Actual result

jtemplate icon is missing
![image](https://github.com/joomla/joomla-cms/assets/66922325/4455f4ca-7533-40fb-9cf7-bd4f17df19da)

### Additional comments

in parameter of plugin (in database) it is now jjtemplate (double j)
![image](https://github.com/joomla/joomla-cms/assets/66922325/5cd3a248-2247-47d4-b471-7b88c3f23b19)

#40626: migrateTinymceConfiguration is triggered because `version_compare('5.0.0-alpha/beta', '5.0.0', 'ge')` is false
https://github.com/joomla/joomla-cms/blob/6e420fbd5762af276dcd2a587b47da4d3ae770e4/administrator/components/com_admin/script.php#L2295-L2307

@dgrammatiko @richard67

**Comment by HLeithner** [comment]
@Fedik ?

**Comment by dgrammatiko** [comment]
The double `jj` means that the upgrade procedure run twice, the first changed `template` to `jtemplate` and the second the `jtemplate` to `jjtemplate`. @richard67 any clues why?

**Comment by heelc29** [comment]
It's a new installation of j5 - so it is already `jtemplate`.
Then I do an update from 5.0.0-alpha --> 5.0.0-beta1-dev (nightly)

In the postflight function of `administrator\components\com_admin\script.php` it do an version compare which is false for 5.0.0 alpha or beta versions `version_compare($this->fromVersion, '5.0.0', 'ge')` and `migrateTinymceConfiguration` is executed

After this it's `jjtemplate`

**Comment by richard67** [comment]
> https://github.com/joomla/joomla-cms/pull/40626 : migrateTinymceConfiguration is triggered because `version_compare('5.0.0-alpha/beta', '5.0.0', 'ge') is false`

@heelc29 That's indended, we want to run it when updating from 5.0 alpha versions.

@dgrammatiko The problem is that after the replacement, the value still contains "template", so it will match and be replaces again and again. We need a check (in addition to the version compare) if the parameters contain one of the old values which is not there after a successful replacement. Or we have to use regexp_replace so we can use the beginning of sting anchor.

**Comment by dgrammatiko** [comment]
>  it do an version compare which is false

Ok, that explains why it happens. I have no clue if we should guard against it but should be doable

**Comment by richard67** [comment]
@dgrammatiko Do you want to provide a fix, and I review it? Or vice versa?

**Comment by dgrammatiko** [comment]
> Do you want to provide a fix, and I review it? Or vice versa?

Go ahead and I'll do the testing

**Comment by richard67** [comment]
> Go ahead and I'll do the testing

@dgrammatiko It may take a while because I have to go shopping for food soon before they close.

**Comment by richard67** [comment]
The easiest check would be if we already have a `'jtemplate'`. If that is the case, the replacement has already been made or we are already on a J5 where it is right.

**Comment by dgrammatiko** [comment]
Yup, you can add something like
```
if (!str_contains($params['configuration']['toolbars'][$setIdx]['menu'], 'template) {
 // add to the array
}
// exec the str_replace
```

**Comment by dgrammatiko** [comment]
>  It may take a while because I have to go shopping for food soon before they close.

@richard67 no worries, I'll do the PR

**Comment by dgrammatiko** [comment]
@heelc29 could you test https://github.com/joomla/joomla-cms/issues/41473

Upgrading again should not result to `jjtemplate` assuming that you cleanup the db data before

**Comment by heelc29** [comment]
There is a PR #41475
