### ISSUE TITLE
[5.x] Difference in icon font weight

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41482]
When you compare visually the display of the icons in 4 and 5 you can see that the icons in 5 appear to be _thinner_

This is an observation not necessarily a bug - I leave that for others to decide

![image](https://github.com/joomla/joomla-cms/assets/1296369/50f36bf3-a1e5-4d6f-a6a5-bfae38a5afc0)

**Comment by chmst** [comment]
Many icons in fontawesome have changed. Compare the menu icons, for exaple users icon andtoggle icon. Also the coq in dashboard modules. Not a bug as long as they are at least similiar.

**Comment by brianteeman** [comment]
>  Not a bug as long as they are at least similiar.

I was just raising awareness **if** someone wanted to address it
