### ISSUE TITLE
[5.0] Darkmode disabled

### ISSUE THREAD

**Issue by rabidgrowth** [joomla/joomla-cms#41515]
### Steps to reproduce the issue

use Joomla! 5.0 beta or from the github

### Expected result

I have darkmode when add data-bs-theme="dark" at < html > tag (I edit index.php now for test, I make JavaScript for autochanged darkmode later)

### Actual result

I have not darkmode

### System information (as much as possible)

macos ventura
Google Chrome last update
php 8.2
unsure mysql

### Additional comments

Atum, problem is build/media_source/templates/administrator/atum/scss/_variables.scss:
```
// Disable dark mode in J4.4 - it's going to cause major b/c breaks to introduce. We will enable it in 5.0
$enable-dark-mode:                 false;
```

Cassiopeia, problem is same build/media_source/templates/site/cassiopeia/scss/tools/variables/_variables.scss :
```
// Disable dark mode in J4.4 - it's going to cause major b/c breaks to introduce. We will enable it in 5.0
$enable-dark-mode: false;
```

This joomla 5. Has to be enable, no? Sorry if i make mistake.

**Comment by HLeithner** [comment]
The darkmode is still work in progress, if you want to help you can have a look at https://github.com/joomla/joomla-cms/pull/41409

**Comment by rabidgrowth** [comment]
Thank you for answer HLeithner! I look at #41409 and report result later. But he is only for Atum, no? I report Atum and Cassiopeia.

Cassiopeia has darkmode work in progress? Just ask to know for my later templates. I do not want use my css to do frontend darkmode for clients. Much work but not pay much, you know. Thank you for next reply. Sorry for my bad english.

**Comment by HLeithner** [comment]
Nobody is working on dark mode for Cassiopeia afaik.

**Comment by rabidgrowth** [comment]
Thank you for answer!

**Comment by ThomMaas** [comment]
New template<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41515">issues.joomla.org/tracker/joomla-cms/41515</a>.</sub>
