### ISSUE TITLE
Saving of Startpage Article results in 500 Error

### ISSUE THREAD

**Issue by PhilippSPOTTERON** [joomla/joomla-cms#41514]
### Steps to reproduce the issue

Login with Administrator account (not super administrator)
Edit startpage article
Click save & close
> 500 Error 

KExceptionError | Fatal Error [500]
Error: Maximum execution time of 30 seconds exceeded
.../libraries/vendor/joomla/string/src/phputf8/mbstring/core.php:94

89 * @return mixed string or FALSE if failure
90 * @package utf8
91 */
92 function utf8_substr($str, $offset, $length = FALSE){
93     if ( $length === FALSE ) {
94         return mb_substr($str, $offset);
95     } else {
96         return mb_substr($str, $offset, $length);
97     }
98 }
99 

Error occurs both with frontend editing and backend regular article editing.

Super Admin Account works and has no error.
Administrator accounts can save other articles without error.

### Expected result

Saving

### Actual result

KExceptionError | Fatal Error [500]
Error: Maximum execution time of 30 seconds exceeded
.../libraries/vendor/joomla/string/src/phputf8/mbstring/core.php:94

89 * @return mixed string or FALSE if failure
90 * @package utf8
91 */
92 function utf8_substr($str, $offset, $length = FALSE){
93     if ( $length === FALSE ) {
94         return mb_substr($str, $offset);
95     } else {
96         return mb_substr($str, $offset, $length);
97     }
98 }
99 

### System information (as much as possible)
Joomla: 4.3.4
PHP 7.4.30
MySQLi 10.1.48-MariaDB-0ubuntu0.18.04.1
Caching Disabled
Gzip Disabled

**Comment by brianteeman** [comment]
any error message beginning with K refers to the 3rd party koowa library

**Comment by richard67** [comment]
@PhilippSPOTTERON If you (temporarily) switch on debug system in global configuration, you should get a stack trace when the error happens? Is that the case? If so, please post the stack trace here (copy of the text or screenshot).

**Comment by PhilippSPOTTERON** [comment]
I only get this error:

![image](https://github.com/joomla/joomla-cms/assets/32574792/086eac77-95af-4a45-adbc-eb96c601d2bb)

(Debug is on in global config)

**Comment by richard67** [comment]
@PhilippSPOTTERON It seems this Koowa thing breaks debugging or showing the stack trace, or you have switched on debug language and not debug system, or you use a non-core template which does that.

**Comment by brianteeman** [comment]
after 7 months is there really any point in this staying open
