### ISSUE TITLE
com_users: create a page (url) to allow a registered user to cancel registration.

### ISSUE THREAD

**Issue by spamzini** [joomla/joomla-cms#41512]
I believe that it is **essential** to create a system to allow a registered user to cancel his registration independently.

**Comment by brianteeman** [comment]
This already exists - see this tutorial. https://docs.joomla.org/J3.x:Privacy

**Comment by richard67** [comment]
> This already exists - see this tutorial. https://docs.joomla.org/J3.x:Privacy

The document links to another one with details about the request processing workflow: https://docs.joomla.org/J3.x:Information_Request_Workflow_in_Privacy_Component

This then has a section "Removal Request".

But the workflow described there still needs a super user for the "Delete Data" step, which also blocks the user login.

@brianteeman Is this what you mean?

**Comment by brianteeman** [comment]
yes

**Comment by spamzini** [comment]
Hi, it's different.
I mean a page where a user can delete his subscription/registration directly.

**Comment by brianteeman** [comment]
I dont see that as ever being something in core. Perhaps some of the extensions offer this?

**Comment by richard67** [comment]
It would just increase the existing problem of content (e.g. articles, menu items, modules, whatever else) having an invalid user ID e.g. in the created by or modified by fields.

**Comment by spamzini** [comment]
> I dont see that as ever being something in core. Perhaps some of the extensions offer this?

My suggest is  a Feature Request for the Joomla 5 development. 
Every website has a "delete" link and i would like to have by core, not by a plugin.

**Comment by spamzini** [comment]
> It would just increase the existing problem of content (e.g. articles, menu items, modules, whatever else) having an invalid user ID e.g. in the created by or modified by fields.

It's possible to change the user id of the "orphan item" in a "general father user"?

**Comment by brianteeman** [comment]
There are lots of consequences to consider depending on the site structure. Its not just a simple delete

**Comment by richard67** [comment]
For reference: This has been discussed in past, and there were several attempts to implement this feature, but it was rejected in past with good reasons. See e.g. #19023 and #20173 .

**Comment by chmst** [comment]
@spamzini could you describe a use case? Why should a user be able to do that? 

Do you want that with this action all content of this user is deleted? This would hava a huge impact as it was explained before. 

What I see in other systems: The users data are not loger visible - wherever he is author of an article, his name is changed to "ghost". Would this meet your request?

**Comment by spamzini** [comment]
> @spamzini could you describe a use case? Why should a user be able to do that?
> 
> Do you want that with this action all content of this user is deleted? This would hava a huge impact as it was explained before.
> 
> What I see in other systems: The users data are not longer visible - wherever he is author of an article, his name is changed to "ghost". Would this meet your request?

Dear Crhistiane,
There are two different scenarios:
1) "Creator" user who creates content or interacts with the site in any way
2) "Registered" user who does not create anything and accesses only a site that has content protected by ACL.

At this point the user goes to the "Delete my registration" link because he no longer wants to be registered on the site. There is a confirmation page with a further request to enter the password and a link sent to the email with a token (similar to the registration one).
On this page, system reminds the user that any contents inserted/uploaded/created (also through other components), must be canceled before the user is canceled.

In both user cases i think it is preferable to anonymize: setting "User deleted" instead of the username and "mail@mail.xx" and keeping the ID and put automatically the user in a group "Deleted user". This way absolutely nothing happens to the ACL tree. In the automatic cancellation confirmation e-mail, it's important to underline "please note that any contents inserted are still present and it is necessary to contact the site administrator for a possible removal".
Sorry for the english.... google translate helps me.

**Comment by rdeutz** [comment]
As explained before there is much more to consider when deleting a user account. Currently we want to anonymize data as a first step. There will be still not a fully automated process in core for the user to delete themself. And we don't want this.
