### ISSUE TITLE
Caching of Javascript language strings broken in Joomla 4.3.4

### ISSUE THREAD

**Issue by ViscountVic** [joomla/joomla-cms#41516]
### Steps to reproduce the issue

It's difficult to give a test case for this, so I just wanted to get a sanity check before creating a test case and submitting a PR.

The problem is ... in an extension with cacheable views, if you add JS language strings with ...

JText::script('FOO_BAR');

The expected result ...

### Expected result

... is that when your view loads from cache, you still have your translated strings in Joomla.JText in the Javascript.

But the actual result ...

### Actual result

.. is you get the untranslated FOO_BAR string.

### System information (as much as possible)

Joomla 4.3.4

### Additional comments

If turn off cache features, then string loading right. First time string can be loaded, but after refresh page string will be missed in joomla.jtext array.

**Comment by dgrammatiko** [comment]
How are you creating the cached pages?

**Comment by ViscountVic** [comment]
Standart System Cache -> ON - Conservative caching
Platform Specific Caching - OFF

First test:
Cache Handler - File
Second test: 
Cache Handler - Redis

**Comment by dgrammatiko** [comment]
Both fail?

**Comment by ViscountVic** [comment]
> Both fail?

Yes, same problem in both variants. I checked hosting version, then local server backup version. Same result in 2 different servers - text without translation. If I'm turning off "Standart System Cache" then all working right - I have translated JavaScript strings.

**Comment by dgrammatiko** [comment]
I can replicate this. Here were my steps:

- turn on caching selecting `Conservative`
- edit the module menu layout and added `\Joomla\CMS\Language\Text::script('MOD_MENU_FIELD_TAG_ID_LABEL');`
- Checked the string in the browser with `Joomla.Text._('MOD_MENU_FIELD_TAG_ID_LABEL')` and got back `MOD_MENU_FIELD_TAG_ID_LABEL`

Worth noting that the cached file contains the translated strings but those are not added to the JSON object thus not available in the browser:

<img width="1680" alt="Screenshot 2023-09-01 at 13 08 39" src="https://github.com/joomla/joomla-cms/assets/3889375/8cf4c784-4b95-4ff6-8927-df87482e5b86">

**Comment by dgrammatiko** [comment]
@ViscountVic let me know if https://github.com/joomla/joomla-cms/pull/41541 fixed the problem

**Comment by Fedik** [comment]
Interesting, Script Options works as expected, and Text not, but it also part of ScriptOptions.

To reproduce use following PHP, in `components/com_content/src/View/Article/HtmlView.php` in `display()`:
```php
Text::script('JYES');
$this->document->addScriptOptions('yes', 'Yes');
$this->document->getWebAssetManager()
    ->addInlineScript('console.log(Joomla.getOptions("yes", "nope") + " " + Joomla.Text._("JYES", "Nope"))', [], ['type' => 'module']);
```

And check browser console:
Expected: `Yes Yes`

After cache enabled:
First request: `Yes Yes`
All following requests: `Yes Nope`

**Comment by dgrammatiko** [comment]
@Fedik I think the merge should be deep by default (now iirc is shallow replace)

**Comment by Fedik** [comment]
Which merge do you mean?

**Comment by dgrammatiko** [comment]
https://github.com/joomla/joomla-cms/blob/17585ed34a69de1e715d55da29d4eedc3f1a9ea0/libraries/src/Document/Document.php#L561

**Comment by Fedik** [comment]
Ah, I know, it do not restore `Text::$strings`, it stay empty, 
and any further call of `Text::script()`, override everything in scriptOptions.

hmhm

**Comment by dgrammatiko** [comment]
I think the `mergeHeadData` needs also the code for passing the text to script options: https://github.com/joomla/joomla-cms/blob/17585ed34a69de1e715d55da29d4eedc3f1a9ea0/libraries/src/Document/HtmlDocument.php#L167-L170

**Comment by Fedik** [comment]
Nope, that should be deleted in future, it not in use.
I have some ideas, need to test.

**Comment by Fedik** [comment]
It just a trash in the cache, it not used later :wink: 
You can ignore that. I will do some test and will make a PR.
If I right, the probblem in the Text class.

**Comment by dgrammatiko** [comment]
I'll bet my money here: https://github.com/joomla/joomla-cms/blob/17585ed34a69de1e715d55da29d4eedc3f1a9ea0/libraries/src/Cache/Cache.php#L496

**Comment by Fedik** [comment]
How much? :smile:

**Comment by dgrammatiko** [comment]
100 EUR 😃

**Comment by Fedik** [comment]
I will send you my Bank account info :smile:

**Comment by Fedik** [comment]
Please test #41543
