### ISSUE TITLE
Changing emai template doesn't have an effect.

### ISSUE THREAD

**Issue by lionated88** [joomla/joomla-cms#41521]
### Steps to reproduce the issue
When I change the email template in the mail template editor, it has no effect, the system sends the content of the Language file rather than the content of the mail template I edited and saved on the backend.

### Expected result

My changes being applied to the sent email

### Actual result

My changes doesn't apply, on the backend it looks like it saved what I edited, but the content of the sent email is the content of a language constant.

### System information (as much as possible)

php: Linux xxx.com 4.18.0-305.17.1.lve.el7h.x86_64 #1 SMP Wed Sep 8 04:44:37 EDT 2021 x86_64
dbserver: mysql
dbversion: 5.7.43
dbcollation: utf8mb4_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 8.1.22
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.3.4 Stable [ Bora ] 22-August-2023 16:00 GMT
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36

**Comment by brianteeman** [comment]
Which mail template did you edit
Which email did you receive

**Comment by lionated88** [comment]
I editet com_users.registration.user.self_activation_w_pw, end I get this email but the original version, not the edited.

**Comment by brianteeman** [comment]
Have you set joomla to send the password
![image](https://github.com/joomla/joomla-cms/assets/1296369/144c8e6e-50f8-4456-868c-4d99548ee84e)

If not then you are editing the wrong email

**Comment by lionated88** [comment]
Yes that's correct. 

However, I'm extremely sorry for wasting your time, I figured out the issue. It works as it should when I use the joomla registration form, the issue is with SEBLOD, because I was using a user form of that component, and it looked like it works as it should as it is sending the correct email template based on the configuration of joomla user settings, but the content of th email isn't from the mail template settings but from somewhere else. I will contact them. 

Should I delete this issue from here?
