### ISSUE TITLE
[5.0] drag and drop

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41527]
### Steps to reproduce the issue
Try to drag and drop an images into tinymce

### Expected result
image uploaded etc

### Actual result
nothing happens in the browser

browser console shows a js error
```
Uncaught TypeError: Cannot read properties of undefined (reading 'uploadUri')
    at uploadFile (plugin.js:40:33)
    at reader.onload (plugin.js:141:9)
```

**Comment by brianteeman** [comment]
doh - updated report

**Comment by dgrammatiko** [comment]
I know what's wrong there, the options in v6 need another approach. Will do a PR
