### ISSUE TITLE
Update notice received in access language not receiver's language

### ISSUE THREAD

**Issue by MarkRS-UK** [joomla/joomla-cms#41533]
The cause of this is (slightly) speculative.
Today I received a (Joomla) upgrade notice from my website in French, despite my "personal" language, and the site default, being English.   I assume this is because the site was accessed "in" French, as the site is multi-lingual and does include a French translation.

### Steps to reproduce the issue
(If I'm correct) Set up a multi-lingual site with a not-current version.
Access a page in a language other than the administrator's default

### Expected result
Administrator receives an upgrade notification email in her default language.

### Actual result
Administrator receives an upgrade notification email in the accessed language.

### System information (as much as possible)
J! 4.3.4

**Comment by richard67** [comment]
As far as I know that's how it works, i.e. desired behaviour, not a bug. But I'm not 100% sure, so let's wait for feedback from others.

**Comment by brianteeman** [comment]
this is the expected behaviour

**Comment by richard67** [comment]
@brianteeman Do you know if we already have some issue about that, or a feature request?

**Comment by brianteeman** [comment]
probably but dont know for certain if its still open

**Comment by richard67** [comment]
See e.g. #17595 , and it was also one aspect of issue #8285 .
