### ISSUE TITLE
SimpleXMLElement::xpath(): Unfinished literal

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#41546]
### Steps to reproduce the issue
Install nightly build.
Install Blog Sample Data.
Edit profile in the frontend.

### Actual result
`Warning: SimpleXMLElement::xpath(): Unfinished literal in C:\xampp\htdocs\Joomla_5.0.0-beta1-dev-Development-Full_Package\libraries\src\Form\Form.php on line 1250`

![xpath](https://github.com/joomla/joomla-cms/assets/368084/e32dd02a-f07d-40aa-8d20-872cae0aa09b)

**Comment by brianteeman** [comment]
strange. I was using that page a lot today while testing.creating https://github.com/joomla/joomla-cms/pull/41539 and I didnt see that

**Comment by Quy** [comment]
I saw this error prior to testing #41539. I will try again tomorrow nightly build.

**Comment by heelc29** [comment]
Maybe fixed by https://github.com/joomla/joomla-cms/pull/41342 ?

**Comment by brianteeman** [comment]
good spot!!

**Comment by Fedik** [comment]
It the same as #41256 and #41508
As @heelc29 wrote the fix is in #41342
