### ISSUE TITLE
[5.0] When installing languages while installing joomla dynamic property Update::$sha256 is deprecated

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#41553]
### Steps to reproduce the issue
* Install joomla with deprecation messages showing
* Install an language after joomla installation
* check xhr request, doesn't return a valid json string instead the deprecation message

### Expected result
works

### Actual result
error message (install of the language seems to work)

### System information (as much as possible)
Php 8.2

### Additional comments
```
<br/><b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$sha256 is deprecated in <b>/web/j006.verlauf.at/libraries/src/Updater/Update.php</b> on line <b>418</b><br/><br/><b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$sha384 is deprecated in <b>/web/j006.verlauf.at/libraries/src/Updater/Update.php</b> on line <b>418</b><br/><br/><b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$sha512 is deprecated in <b>/web/j006.verlauf.at/libraries/src/Updater/Update.php</b> on line <b>418</b><br/>
```

**Comment by Ruud68** [comment]
Not only when installing languages, but also when updating Joomla itself:
```
Deprecated: Creation of dynamic property Joomla\CMS\Updater\Update::$sha256 is deprecated in ...libraries/src/Updater/Update.php on line 418
Deprecated: Creation of dynamic property Joomla\CMS\Updater\Update::$sha384 is deprecated in ...libraries/src/Updater/Update.php on line 418
Deprecated: Creation of dynamic property Joomla\CMS\Updater\Update::$sha512 is deprecated in ...libraries/src/Updater/Update.php on line 418
Deprecated: Creation of dynamic property Joomla\CMS\Updater\Update::$section is deprecated in ...libraries/src/Updater/Update.php on line 418
```
![screen shot 2023-11-29 at 08 25 08](https://issues.joomla.org/uploads/1/85290a3c1b47e54ef77c33a97fd80b4f.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41553">issues.joomla.org/tracker/joomla-cms/41553</a>.</sub>

**Comment by alikon** [comment]
please test #42429
