### ISSUE TITLE
The server returned a "500 - Whoops, looks like something went wrong."

### ISSUE THREAD

**Issue by Scorptech** [joomla/joomla-cms#41569]
### Steps to reproduce the issue

I'm moving to a new hosting service running on a plesk system. Before I migrate over my old sites, I wanted to test the J5 Alpha on my ISP's new hosting service. Their new service cannot allocate a temporary url, so I have to resolve the IP to the temp domain and add this to my local hosts file. 

### Expected result

I expected to see the standard Joomla installation screen

### Actual result

When I ran the url to do the install, the following error came up:- 

The server returned a "500 - Whoops, looks like something went wrong."

### System information (as much as possible)

**Having spoken to a Joomla expert after sending him the following error:-** 

GET /installation/ HTTP/1.0

Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0      19.7 K Apache access
2023-08-31 19:30:14   Error    31.170.7.57                 AH01071: Got error 'PHP message: PHP Fatal error: Declaration of Joomla\\CMS\\Log\\DelegatingPsrLogger::log($level, Stringable|string $message, array $context = []): void must be compatible with PsrExt\\Log\\LoggerInterface::log($level, $message, array $context = []) in /var/www/vhosts/scorpiontechnology.ie/joomla5demo.com/libraries/src/Log/DelegatingPsrLogger.php on line 77'

**He commented on this and said:**

The bit in that error that is suspect is the "PsrExt". 
 
That string doesnt exist in the whole Joomla 5 code base.
 
The actual Psr\Log\LoggerInterface and the DelegatingPsrLogger.php both have the same compatible method signatures and DelegatingPsrLogger.php has not changed since May 2023 - and nothing important was changed then. 
 
A quick google and It seems PsrExt\Log\LoggerInterface   comes from user land PECL packages (which *IS* a hosting issue) so it might be that somewhere in your hosts PHP configuration (in cPanel PHP Modules?) you can disable things named like PHP Pecl extension PSR ?
 
**I emailed the ISP with his comment and they said:** 

So basically, it seems the code being deployed is not compatible - perhaps with the latest instance of PSR that is available currently.

Note that we have version 1.2.0 of the PECL PSR component installed - which is the latest one on release, and which runs "PSR-18" - the latest format that has been published as of that version.

It is possible that Joomla 5 might have code that does not suit this formatting requirement or otherwise is using draft formatting or formatting not released as of yet on general use.

The only way around this would be to deploy the website to your own Cloud server etc. and test it there - plus install draf/alpha components, but realistically as it is in Alpha I would suggest waiting until [at least] a Release Candidate and then review the overall.

As a note, it would be very unlikely that the underlying hosting system - Plesk, would not support Joomla 5 when the time comes (for general release) but it would be more likely that certain components would not be available at an Alpha stage - some components may need to be installed that are not as of yet on general release or supported by the vendor/OS etc..

### Additional comments

So at the moment, we cannot move forward with j5 installs for testing on the new hosting account due to this error. I hope this helps as part of the alpha build.

**Comment by brianteeman** [comment]
Almost certainly everything your "expert" and your "isp" have said is wrong.

Question 1
Where sis you download the alpha from? This will almost certainly let me solve your problem

**Comment by Scorptech** [comment]
Hi Brian,

I downloaded the alpha version from the Joomla website. 

https://developer.joomla.org/news/902-joomla-5-0-alpha1-test-the-future-of-joomla.html

Regards

Alan

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41569">issues.joomla.org/tracker/joomla-cms/41569</a>.</sub>

**Comment by brianteeman** [comment]
Thats a VERY old version from May

You should download the current alpha which is version 4 (https://developer.joomla.org/news/909-joomla-5-0-alpha-4-your-last-chance-to-add-a-feature.html)

To avoid complications you should remove all the files you currently have from alpha 1 before extracting the alpha4 zip

**Comment by Scorptech** [comment]
Hi Brian, 

I did a clean install using Alpha 4 and the same error came up with the following issue.

2023-09-03 19:49:16	Error	31.170.7.57	500	GET /installation/index.php HTTP/1.0

2023-09-03 19:49:16	Error	31.170.7.57	404	GET /favicon.ico HTTP/1.0

2023-09-03 19:49:16	Error	31.170.7.57		AH01071: Got error 'PHP message: PHP Fatal error: Declaration of Joomla\\CMS\\Log\\DelegatingPsrLogger::log($level, Stringable|string $message, array $context = []): void must be compatible with PsrExt\\Log\\LoggerInterface::log($level, $message, array $context = []) in /var/www/vhosts/[domainname}/joomla5demo.com/libraries/src/Log/DelegatingPsrLogger.php on line 77'


Regards

Alan


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41569">issues.joomla.org/tracker/joomla-cms/41569</a>.</sub>

**Comment by brianteeman** [comment]
So you have a a file path issue

**Comment by Scorptech** [comment]
Hi Brain, 

I agree that this could be a problem. The way they have setup the new Plesk hosting system and recommending that customers use a hosts file, does not sit well with me and this could be one of the issues as to why J5 is not even loading the installation page due to a path issue. however, the splash error 500 screen does show up, so it is seeing the directory.  

So I went back to my old hosting account and this DOES allow for temp URL's. J4 works fine on this system. So, I did a clean install and tried the process again, but again, the 500 server error came up:- 

http://d1673633-147525.blacknighthosting.com/installation/index.php

Now this old hosting account only supports MySQL5 (they have php 8.1 installed), but I would expect the installation screen to come up at least.

So it's a bit of a mystery as to why both hosting packages are not loading J5. The only other issue is that website caching is in place and
maybe when I try again in the morning, it will work, i don't know? 

Regards

Alan

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41569">issues.joomla.org/tracker/joomla-cms/41569</a>.</sub>

**Comment by Scorptech** [comment]
Hi, 

I've now installed Joomla 5 Beta 1 but experiencing the same issue. :-(

Regards

Alan<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41569">issues.joomla.org/tracker/joomla-cms/41569</a>.</sub>

**Comment by Scorptech** [comment]
The error that is coming up also says that it is an "Apache Error". 

2023-09-04 16:44:39	Error	31.170.7.57		AH01071: Got error 'PHP message: PHP Fatal error: Declaration of Joomla\\CMS\\Log\\DelegatingPsrLogger::log($level, Stringable|string $message, array $context = []): void must be compatible with PsrExt\\Log\\LoggerInterface::log($level, $message, array $context = []) in /var/www/vhosts/scorpiontechnology.ie/joomla5demo.com/libraries/src/Log/DelegatingPsrLogger.php on line 77'				Apache error

If that helps to solve the issue.

Regards

Alan <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41569">issues.joomla.org/tracker/joomla-cms/41569</a>.</sub>

**Comment by Scorptech** [comment]
Hi, 

I've now added a full domain rather than a temp URL to make sure that there is no path issue, but I'm still getting the 
500 server error issue. 

Regards 

Alan



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41569">issues.joomla.org/tracker/joomla-cms/41569</a>.</sub>

**Comment by alikon** [comment]
thank you for the feedback
