### ISSUE TITLE
[5.0] Toolbar present in ModalSelect dialog

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#41572]
### Steps to reproduce the issue

compare 4.4 or 5.0-alpha 4 with latest 5.0-dev (contains #40462) @Fedik 

### Expected result

no toolbar present

### Actual result

toolbar present, eg
![image](https://github.com/joomla/joomla-cms/assets/66922325/1414ea95-d5d5-42b3-a9d1-0368524cae9f)
![image](https://github.com/joomla/joomla-cms/assets/66922325/44fe8bd3-dac4-4d1a-b9c3-7c33a79d7767)

**Comment by Fedik** [comment]
@heelc29 where from your first screenshot?

**Comment by Fedik** [comment]
Please test #41578
