### ISSUE TITLE
[5.0] removed in 5.0 ??

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41573]
https://github.com/joomla/joomla-cms/blob/acd25e5a79b3a1dc2f96681a024ce4940c34ad68/libraries/src/HTML/HTMLHelper.php#L93

Is this and the other similar notices in this file still correct?

**Comment by heelc29** [comment]
> Is this and the other similar notices in this file still correct?

I think no, if you enable log and open cpanel ...

```
WARNING ::1	deprecated	Support for registering functions is deprecated and will be removed in Joomla 5.0, use the service registry instead - [ROOT]\libraries\src\HTML\HTMLHelper.php - Line 202
WARNING ::1	deprecated	Support for a three segment service key is deprecated and will be removed in Joomla 5.0, use the service registry instead - [ROOT]\libraries\src\HTML\HTMLHelper.php - Line 92
```

**Comment by brianteeman** [comment]
I know thats what it says I am asking if its true or will they be removed in 6.0

**Comment by wilsonge** [comment]
6.0 per the updated b/c policy. think @bembelimen just missed it in his pass through

**Comment by brianteeman** [comment]
see #41594
