### ISSUE TITLE
[5.0] Display issues after Dark Mode support

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#41571]
### Steps to reproduce the issue

compare 4.4 or 5.0-alpha 4 with latest 5.0-dev (contains #41409) @wilsonge 

### Expected result

![image](https://github.com/joomla/joomla-cms/assets/66922325/1c1aa7d4-dc7d-4dc9-94ad-1f347238b371)
![image](https://github.com/joomla/joomla-cms/assets/66922325/97dbd879-abbb-4541-9933-ff9909656989)
![image](https://github.com/joomla/joomla-cms/assets/66922325/3946e3f4-07cf-4354-ace5-382903dfcc94)
![image](https://github.com/joomla/joomla-cms/assets/66922325/6997697a-e7ed-4ace-9b2e-ef965d1a9b79)

### Actual result

- background of table (also language table)
![image](https://github.com/joomla/joomla-cms/assets/66922325/86ff669a-9979-496c-b000-500dd0de7478)

- background list
![image](https://github.com/joomla/joomla-cms/assets/66922325/a2378347-8f46-4ef3-8e70-cbfb7ae976f5)

- background arrow (also some more of these kind of fields)
![image](https://github.com/joomla/joomla-cms/assets/66922325/20420529-056e-4105-aef3-96ef692f5caa)

- background and form of toolbar buttons
![image](https://github.com/joomla/joomla-cms/assets/66922325/1db00383-296d-402f-a2d9-ad85ed607846)

**Comment by brianteeman** [comment]
confirmed

**Comment by wilsonge** [comment]
Thankyou. I’m aware of this and the stuff @Quy mentioned in the original post. I’m currently on holiday but will address this as soon as I can when I’m back (on Friday).

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/blob/4.3-dev/build/media_source/templates/administrator/atum/scss/_variables.scss#L49

In the meantime if anyone else is interested in solving this specific one before I get back. In most these places we’re using this action variable which is supposed to be blue. So we need to figure out in J4 why it was white in most cases!

**Comment by brianteeman** [comment]
there is a variable that is not defined causing issues

`var(--bg-color);`

looking at the code before the pr this was always 
`$white;`

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/41615

First PR (fixes the 4th screenshot here)

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/41626 

Second PR fixes the 3rd screenshot for the form selects

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/41627

Third PR fixes the 1st screenshot for installation tables

**Comment by richard67** [comment]
@wilsonge Do the 3 PRs #41625 , #41626 and #41627 together fix this issue? or is there something remaining?

**Comment by wilsonge** [comment]
Final fix here https://github.com/joomla/joomla-cms/pull/41772
