### ISSUE TITLE
[5.0] Naming of Scheduled Task plugins should be harmonized

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#41607]
### Steps to reproduce the issue

Attempt to create a new scheduled task to get the panel with the available task types (= plugin names) shown.

Check if the titles follow a common scheme.

### Expected result

Common scheme for naming task types.

### Actual result

Most task types just have a title without any pre- or suffix.

But one has a prefix "Task - " and one has a suffix "- Task". This looks odd.

![2023-09-05_j5-task-types](https://github.com/joomla/joomla-cms/assets/7413183/d0cf2526-8687-49c0-b6ab-e653e8207931)

Maybe the description of the "Joomla Update Notification" task type should be shortened a bit.

### System information (as much as possible)

All tasks just have a title without any "Task" pre- or suffix.

### Additional comments

It just needs to change 2 language strings, but I'm already tired and still busy with something else, and in the next 2 days I will not have much time, so I created this issue for documentation and in case if someone finds time before me.

**Comment by richard67** [comment]
> can we do it on #41603 imho

@alikon If you ask the author

**Comment by alikon** [comment]
as we are taliking about task names, the easy & fast way to do it, is in 1 pr only
@brianteeman

**Comment by richard67** [comment]
> as we are taliking about task names, the easy & fast way to do it, is in 1 pr only @brianteeman

I think it's the task **plugin** names which are shown on the "create new task" screen.

**Comment by brianteeman** [comment]
seperate issue = seperate pr - please!

**Comment by alikon** [comment]
one way or another fine for me

**Comment by alikon** [comment]
please test #42574

> Maybe the description of the "Joomla Update Notification" task type should be shortened a bit.

if someone will suggest a description why not
