### ISSUE TITLE
[5.0Beta1] strlen php8.1

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41605]
### Steps to reproduce the issue
Create an admin module for a newsfeed

### Expected result
No errors

### Actual result
`PHP Deprecated:  strlen(): Passing null to parameter #1 ($string) of type string is deprecated in \libraries\src\Table\Module.php on line 154`

### System information (as much as possible)
php 8.1

### Additional comments
looking at the code I guess this might be generated by other modules as well

**Comment by HLeithner** [comment]
Do you have a stack trace please?

**Comment by brianteeman** [comment]
No, would have posted it if I had. The only error is in the logs - sorry

**Comment by alikon** [comment]
please test #41763
