### ISSUE TITLE
[5.0.0 beta1] Action buttons css

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#41622]
### Steps to reproduce the issue
Have a look on the action buttons in edit screens: 

![grafik](https://github.com/joomla/joomla-cms/assets/1035262/52dfd757-6201-4900-bdb7-3c897ea37c58)
![grafik](https://github.com/joomla/joomla-cms/assets/1035262/d87e95d3-9051-4f0e-a38d-6bd83757ae95)

This appears only in 5.0.0 beta1, not in 4.4.0 beta1

Win11, Firefox and Chrome, PHP 8.2

**Comment by brianteeman** [comment]
Closing this as a duplicate report (and we have a pr #41615
