### ISSUE TITLE
[5.x][PHP 8.2] Extensions ChangeLog display not working due to deprecation warning

### ISSUE THREAD

**Issue by conseilgouz** [joomla/joomla-cms#41635]
### Steps to reproduce the issue
Load any extension that has an associated changelog file, for example https://extensions.joomla.org/extension/edition/editors/switch-editor-2/
Go to System/Extensions, search for switch editor in extensions list and click on underlined version number to display changelog content.
### Expected result
changelog is displayed

### Actual result
Error message : SyntaxError: Unexpected token '<', "
"... is not valid JSON 
In errorlog,  
[07-Sep-2023 13:06:09 UTC] PHP Deprecated:  Creation of dynamic property Joomla\CMS\Changelog\Changelog::$changelogs is deprecated in D:\laragon6-------------\www\j5beta\libraries\src\Changelog\Changelog.php on line 275
[07-Sep-2023 13:06:09 UTC] PHP Deprecated:  Creation of dynamic property Joomla\CMS\Changelog\Changelog::$changelog is deprecated in D:\laragon6-------------\www\j5beta\libraries\src\Changelog\Changelog.php on line 275
[07-Sep-2023 13:06:09 UTC] PHP Deprecated:  Creation of dynamic property Joomla\CMS\Changelog\Changelog::$item is deprecated in D:\laragon6-------------\www\j5beta\libraries\src\Changelog\Changelog.php on line 275

### System information (as much as possible)
PHP 8.2, Joomla 5.0 Beta 1

### Additional comments
In Joomla 4, Changelog class extends CMSObject and, in Joomla 5, it's a class on its own.

**Comment by conseilgouz** [comment]
I think adding #[\AllowDynamicProperties] in libraries/src/Changelog/Changelog.php should work

**Comment by HLeithner** [comment]
#[\AllowDynamicProperties] is not a longterm solution

**Comment by Fedik** [comment]
I cannot reproduce it.
I have installed linked extension on Joomla 5 beta1, set error_reaporting to maximum,
But there no error when looking a change log for this extension.

**Comment by conseilgouz** [comment]
@Fedik PHP 8.2 ?

**Comment by Fedik** [comment]
ah, yeah, not 8.2 :)
Will try again later

**Comment by conseilgouz** [comment]
If you set **error reporting** to **none**, you won't see deprecated lines and changelog display is OK.

Error reporting to _maximum_ adds the deprecated lines at the beginning of $output in administrator\components\com_installer\src\Controller\ManagerController.php, line 176 causing then JSON Error.

**Comment by Fedik** [comment]
The deprecation trigger comes from here https://github.com/joomla/joomla-cms/blob/1e7527b60ec42032abe7bfb9c000bacf38f65845/libraries/src/Changelog/Changelog.php#L271-L273
This code looks strange.

It not 5.0 specific. But general.

There also an issue that the changelog does not display full list. which is already reaported #37774
I suspect these issue is connected.

Hovewer I have no idea what this `startElement`/`endElement` are doing here.

**Comment by conseilgouz** [comment]
> It not 5.0 specific. But general.

In Joomla 4, Changelog class extends CMSObject which contains #[\AllowDynamicProperties]

**Comment by conseilgouz** [comment]
See https://github.com/joomla/joomla-cms/pull/40999

**Comment by Fedik** [comment]
You are right
