### ISSUE TITLE
Can not edit articles while logged into front end. J5 beta1

### ISSUE THREAD

**Issue by gwstyles** [joomla/joomla-cms#41637]
### Actual result;   If difficulties persist, please contact the website administrator and report the error below.

    0 Class "JPlugin" not found

**Comment by brianteeman** [comment]
what extensions do you have installed?

is this an update or a clean install?

enable debug mode in global config and then post the stack trace - or justg look at the first line of that and you will see the culprit

**Comment by gwstyles** [comment]
I have installed, akeeba ,German language,country database and hash cash. It is the hash cash extension that is stopping editing. Shame I am fond of that extension.
