### ISSUE TITLE
Clear cache in J5 beta

### ISSUE THREAD

**Issue by gwstyles** [joomla/joomla-cms#41630]
Try and clear cache in J5

### Actual result = An error has occurred.

    0 Joomla\CMS\Event\Cache\AfterPurgeEvent::setSubject(): Argument #1 ($value) must be of type string, null given, called in D:\wamp64\www\j5\libraries\src\Event\AbstractEvent.php on line 205

**Comment by richard67** [comment]
Fixed with PR #41620 . Feel free to reopen this issue here if you think this is wrong.

**Comment by gwstyles** [comment]
Tested #41620 and it has fixed the issue for me.

**Comment by richard67** [comment]
> Tested #41620 and it has fixed the issue for me.

Thanks for reporting back.
