### ISSUE TITLE
Error while update from 4.3.4 to 5.0.0-beta1 - Unknown column 'a.ordering' in 'order clause'

### ISSUE THREAD

**Issue by sergeytolkachyov** [joomla/joomla-cms#41639]
Update via file upload in com_joomlaupdate. 

Stack trace

![image](https://github.com/joomla/joomla-cms/assets/6236403/d81f387d-1749-4b2f-9c7a-f727d0b00a2c)

**Comment by richard67** [comment]
Updating to 5.0 always has to be done from the latest 4.4. direct update from 4.3.x to 5.0.0 is not supported.

E.g. the update SQL scripts from 4.4 will not be there and so not run when updating directly from 4.3.x to 5. This is currently only one update SQL script, but it might become more during the live time of 4.4.

The same applies to deleting obsolete files and folders on update. Things which would be deleted when updating from 4.3 to 4.4 before updating to 5 will not be deleted when updating directly from 4.3 to 5.

**Comment by richard67** [comment]
In addition it seems to me that this update SQL script from J5 has not run, and that causes the error: https://github.com/joomla/joomla-cms/blob/5.0-dev/administrator/components/com_admin/sql/updates/mysql/5.0.0-2023-07-12.sql

So it seems the SQL update has failed with an SQL error before that script has run.

**Comment by richard67** [comment]
If you have a backup of the 4.3.4 before the update, restore that update using an empty folder for the files and an empty database for the database part. Then restore your custom files, e.g. .htaccess, php.ini, whatever you had. Then update the update 4.3.4 first to 4.4.0-beta1, and after that to 5.0.0-beta1.

Could you do that and report back if that worked?

Thanks in advance.

**Comment by MarcinGolec13** [comment]
the same problem..... unsolved - any ideas?
