### ISSUE TITLE
Use Space better in list views in the backend

### ISSUE THREAD

**Issue by jduerscheid** [joomla/joomla-cms#41631]
### Is your feature request related to a problem? Please describe.

During my work on Issue #38335 and Pullrequest #41557, the discussion started that too much space is wasted in the backend lists views and that we should refactor these views. In my opinion, it is not sensible to do this directly within the scope of the original feature, as there are also several things to consider that should be thought through beforehand, especially with regard to a11y.

### Describe the solution you'd like

As much as possible, the list views in the backend should be revised so that they are also useful on smaller screens.

### Additional context

Feature #38335 
Pull Request #41557

**Comment by Quy** [comment]
Closing per PR #41557
