### ISSUE TITLE
5.0 Strange SiteApplication::getPathway() call

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#41653]
### Steps to reproduce the issue

See the code for `SiteApplication::getPathway()`, it calls parent method with arguments but parent method doesn't have arguments.

```
    public function getPathway($name = 'site', $options = [])
    {
        return parent::getPathway($name, $options);
    }
```

### Expected result

No arguments or arguments applied

### Actual result

No arguments are applied.

**Comment by joomdonation** [comment]
I think we can just remove `getPathway` method from `SiteApplication`. It does nothing different from it's parent but causes this confusing.

**Comment by rdeutz** [comment]
Closing because we have a PR #43385
