### ISSUE TITLE
Creating a new "user" does not send the account information to the user

### ISSUE THREAD

**Issue by mlwales** [joomla/joomla-cms#41684]
### Steps to reproduce the issue
Create a new user and set the "force" password option to "on or yes"

### Expected result
A message sent to the user informing them of the account creation.
I remember this being done in Joomla 3.x.
The information included:
 a) their user name
 b) the temporary password.
 a) a url to the website back end.
In Joomla 4.x, the person does not receive any message in either their inbox or spam folders

### Actual result
No message is received by the new user.

### System information (as much as possible)
Joola 4.x.

**Comment by obuisard** [comment]
Hello! There is a way to enable/disable user notifications.
Did you make sure the notifications are indeed enabled?
This is set in the User plugin Joomla!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41684">issues.joomla.org/tracker/joomla-cms/41684</a>.</sub>

**Comment by Quy** [comment]
Closing due to no response.
