### ISSUE TITLE
Forgot password features not working in Joomla 4.x

### ISSUE THREAD

**Issue by mlwales** [joomla/joomla-cms#41683]
Log in from the front-end (assumes there is a Login menu option)
The login page has options to:  Forgot Password and Forgot Username.
Choosing either of those asks for your email address and the message:
"Please enter the email address for your account. A verification code will be sent to you. Once you have received the verification code, you will be able to choose a new password for your account."
  After entering the email address and clicking on "Submit" results in the message:
"If the email address you entered is registered on this site you will shortly receive an email with a reminder."

### Expected result
Receive a message with instructions to reset either password or username.

### Actual result
The email is never received in the inbox or spam at the specified email address.
The email provided is the email associated with the user's login account.

### System information (as much as possible)
Joomla 4.x.x (actual test was done on 4.3.3 and 4.3.4

**Comment by Quy** [comment]
Since this is the only report, I assume it is a local issue, otherwise, we would have received many more reports. Have you checked with your hosting provider?

**Comment by dautrich** [comment]
@mlwales Did you enter the email address of a superuser. I did that by accident and never got any mail (which maybe is the designed behavior). Subsequently, I entered the email address of a normal, registered user: Everything worked fine.

**Comment by Quy** [comment]
Closing due to no response and as suggested a possible case for the issue.
