### ISSUE TITLE
[5.0] Double toolbar in image

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#41687]
### Steps to reproduce the issue
Add an image into an article or via an custom field media. The toolbar in the modal window is duplicated.

![grafik](https://github.com/joomla/joomla-cms/assets/1035262/75fd0fec-2dd6-4dab-bb66-3933699e3a03)

### Additional comments
Fresh installation of 5.0.0. beta 1

**Comment by Fedik** [comment]
The fix is there https://github.com/joomla/joomla-cms/pull/41600 :wink:

**Comment by chmst** [comment]
oops, thank you
