### ISSUE TITLE
Cannot select tags in article on Joomla 4.3.4 with PHP version 8.1

### ISSUE THREAD

**Issue by absillitoe** [joomla/joomla-cms#41691]
### Steps to reproduce the issue

With a lot of tags (I have between 200 and 300), when creating a new article or editing an existing one, and trying to assign a tag, the message "No results match" is received. 

On Joomla 4, it is necessary to type the first few letters of a tag, and then those tags which correspond are displayed, allowing you to select one, However, with PHP 8.1,22 when typing a few letters of an existing tag, the message "No results match" is received.

### Expected result

The corresponding tags should be displayed. 

### Actual result

The message "No results match" is received.

### System information (as much as possible)

PHP Built On 	Linux gnldm1080.siteground.biz 3.12.18-clouder0 #3 SMP PREEMPT Wed May 25 12:13:20 EEST 2022 x86_64
Database Type 	mysql
Database Version 	5.7.39-42-log
Database Collation 	utf8mb4_general_ci
Database Connection Collation 	utf8mb4_general_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	Yes
PHP Version 	8.1.22
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 4.3.4 Stable [ Bora ] 22-August-2023 16:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/117.0 

### Additional comments

The problem goes away after reverting to PHP 8.0.30.

**Comment by heelc29** [comment]
@absillitoe Can you please check if the fix of https://github.com/joomla/joomla-cms/pull/41509 solves your problem?

**Comment by absillitoe** [comment]
@heelc29 I installed the patch tester, made and entered a Github token and fetched the data, but I don't seem to get patch #41509. What am I doing wrong?

**Comment by heelc29** [comment]
You're not doing anything wrong. The PR is already merged and therefore does not need any further human tests and is no longer available in the patch tester.
So now you have 3 other options:
- Update to [4.3.5 nightly build](https://developer.joomla.org/nightly-builds.html) as the fix of #41509 will be released with 4.3.5 – not for production websites!
- Manually update the file `components/com_tags/src/Controller/TagsController.php` with the changes from #41509 ´
- Check your server logs if you see something like this `PHP Deprecated: trim(): Passing null to parameter https://github.com/joomla/joomla-cms/pull/1 ($string) of type string is deprecated in C:\xampp\htdocs\joomla5\components\com_tags\src\Controller\TagsController.php on line 39` described in the issue #41466

**Comment by absillitoe** [comment]
Sorry for the delay. I cannot get my XAMPP installation to work since I updated it, so I have been able to use option 1. Not sure how to do option 2 correctly. I didn't see any error message when I looked, but perhaps I'm looking in the wrong place. Probably, your modification will fix my problem.

**Comment by absillitoe** [comment]
@heelc29 Finally managed to get my XAMPP working with PHP 8.1 and the tags seem to work fine on there. Do I need to do anything else?

**Comment by alikon** [comment]
if it is solved @absillitoe  please close the issue

**Comment by heelc29** [comment]
You can close this issue and wait for the release of J4.3.5 (3 October 2023)

**Comment by absillitoe** [comment]
Thank you alikon and heelc29.
