### ISSUE TITLE
[5.0] Tinymce plugin Call to undefined method 

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41709]
### Steps to reproduce the issue
Open the tinymce plugin

### Expected result
plugin opens

### Actual result
**0 Call to undefined method Joomla\Plugin\Editors\TinyMCE\Extension\TinyMCE::getKnownButtons()**

![image](https://github.com/joomla/joomla-cms/assets/1296369/f02bb051-bd1d-4226-bc2f-cbcad05ffd83)

### Additional comments
This is caused by the untested but merged PR [5.0] TinyMCE use EditorProvider and Editor event #41599

**Comment by Fedik** [comment]
Yeah, I forgot to check that, please test the fix https://github.com/joomla/joomla-cms/pull/41711
