### ISSUE TITLE
ModuleHelper::getModule returns null when using com_ajax interface with module

### ISSUE THREAD

**Issue by CrazySeb69** [joomla/joomla-cms#41715]
### Steps to reproduce the issue
1. With custom developed module set "Module Assignment" to anything else than "On all pages" on module configuration. 
2. Use module with ajax call using com_ajax interface
3. ModuleHelper::getModule returns object with null values (modue title, position, params, etc)
4. When using module without com_ajax ModuleHelper::getModule returns values correctly.

### System information (as much as possible)
Dockerized Joomla 4.x with PostgreSQL database

**Comment by Fedik** [comment]
>  to anything else than "On all pages" on module 

When you asign your module to specific page, then it can be shown only there.
And com_ajax does not know what page is active.

You have to do your AJAX request with specified `Itemid=x` parameter in URL, where `x` is a active menu ID.
You can get current `Itemid` with: `$app->getInput()->get('Itemid')`
