### ISSUE TITLE
[5.0] passkey registration broken

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#41719]
### Steps to reproduce the issue

try to add a new passkey
![image](https://github.com/joomla/joomla-cms/assets/66922325/49deae50-66bb-4ab4-b950-0165bc10770a)

### Expected result

registration should work

### Actual result

![image](https://github.com/joomla/joomla-cms/assets/66922325/8f280a0d-b050-40c6-897b-963fb8a9924e)
`Joomla\Plugin\System\Webauthn\Extension\Webauthn::onAjaxWebauthn(): Argument #1 ($event) must be of type Joomla\CMS\Event\Plugin\System\Webauthn\Ajax, Joomla\CMS\Event\Plugin\AjaxEvent given, called in libraries\vendor\joomla\event\src\Dispatcher.php on line 454`

### Additional comments

#41524 @Fedik

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/41720
