### ISSUE TITLE
[4.4] com_privacy unable to filter by subject

### ISSUE THREAD

**Issue by andyforrest** [joomla/joomla-cms#41718]
### Steps to reproduce the issue

- Have users consent to privacy policy with different subjects
- Go to admin component to view privacy consents
- Filter by subject

### Expected result

- Privacy consent will filter by the selected subject

### Actual result

![image](https://github.com/joomla/joomla-cms/assets/46865032/a5f6c726-4beb-4a31-9956-d58a347939f7)

**Comment by chmst** [comment]
Please test https://github.com/joomla/joomla-cms/pull/41726
