### ISSUE TITLE
Deleting duplicate "-2" alias of contact name will end up in Error incorrect integer value

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#41713]
### Steps to reproduce the issue
1. Fill new contact under some category
2. Use "Save"
3. Use "Save as copy"
4. In this copy will be end of alias -2
5. Delete this end "-2" of alias  
6. Save
7. Result: Save failed with the following error: Another Contact in this category has the same alias.
8. Delete all in alias line, to automaticaly generate new alias 
9. Save
10. Result is empty alias(will not generate new one) and an ERROR:  Save failed with the following error: Incorrect integer value: '' for column `database`.`blabla_contact_details`.`hits` at row 1

### Expected result
Generate new alias according to Name

### Actual result
Result is empty alias(will not generate new one) and an ERROR:  Save failed with the following error: Incorrect integer value: '' for column `database`.`blabla_contact_details`.`hits` at row 1

### System information (as much as possible)
Windows 10, XAMPP, php 8

**Comment by brianteeman** [comment]
bug confirmed

**Comment by Georocha** [comment]
Testei o passo a passo. O erro acontece realmente quando exclui o alias-2 pois ele encontrou outro alias com mesmo nome na categoria. Se você excluir o alias para gerar automaticamente e não editar o nome do seu contato, apresentará novamente o erro. Mas se editar o nome do contato da copia, o arquivo salvou com sucesso.
Informações do meu sistema: Linux, XAMPP, php 8, Joomla 4.3.3

**Comment by alikon** [comment]
please test #42968
