### ISSUE TITLE
[5.0] Warnings in inlinehelp

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#41729]
Warning: Trying to access array offset on value of type null in /web/ibraries/src/MVC/View/FormView.php on line 244

Warning: Trying to access array offset on value of type null in /web/libraries/src/MVC/View/FormView.php on line 246

Seems the `$formConfig` could be empty

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/41890
