### ISSUE TITLE
[4.3.4] Itemid in versioning not working with zerofill ID

### ISSUE THREAD

**Issue by JoomlaN00b** [joomla/joomla-cms#41747]
### Steps to reproduce the issue
Table with zerofill for ID in database with versioning. 
For example ID 0012 and 0202

### Expected result
History is saved and fetched correctly.

### Actual result
If editing entry with ID 0202:
History is saved in table _history with $typeAlias.202
Versioning does not work because it tries to fetch $typeAlias.0202 in backend.
So no history is shown and versioning is unable to be used.

### Additional comments
If the solution is "stop using zerofill stupid" :smile: Then I would appreciate tips on how to force fetch :item_id without zerofill in custom component model file. Thanks!

**Comment by JoomlaN00b** [comment]
Solved it for my custom component by changing my models

public function getItem($pk = null)

and adding

$item->ID = intval($item->ID);<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41747">issues.joomla.org/tracker/joomla-cms/41747</a>.</sub>

**Comment by alikon** [comment]
thanks for reporting
