### ISSUE TITLE
Batch Option Not Available for Admin Usergroup for Articles or Menu Items

### ISSUE THREAD

**Issue by hpgodwin** [joomla/joomla-cms#41752]
### Steps to reproduce the issue
Have usergroup role set to Administrator
Go to Content > Articles
Select an article
Open Actions
Batch is missing as an option

### Expected result
Go to Content > Site Modules 
Select a module
Select Actions
Batch is an option for administrator

### Actual result
Batch Option is missing as an Action if role is only administrator and user has articles selected

### System information (as much as possible)
Joomla Version: Joomla! 4.3.4 Stable [ Bora ] 22-August-2023 16:00 GMT
PHP Version: 	7.4.3-4ubuntu2.19
User Agent:     Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36 Edg/116.0.1938.81

### Additional comments
Users with Administrator role had the ability to use Batch Operation on J3, we recently upgraded to Joomla 4 and users have noticed they don't have the option with regards to Articles anymore. 
I have tested changing the ![screen shot 2023-09-14 at 09 36 20](https://issues.joomla.org/uploads/1/3024081a536c097083a4d41ede9306a8.png)User Permissions and allowing all does not bring back the Batch Option.![screen shot 2023-09-14 at 09 36 22](https://issues.joomla.org/uploads/1/58f1157e97e1b25a189ef9ccd5b7e43a.png)

**Comment by Fedik** [comment]
Check that user have all these access:
https://github.com/joomla/joomla-cms/blob/1e7527b60ec42032abe7bfb9c000bacf38f65845/administrator/components/com_content/src/View/Articles/HtmlView.php#L219-L221

I suspect `core.execute.transition` is missing

**Comment by hpgodwin** [comment]
This was exactly the fix - thank you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41752">issues.joomla.org/tracker/joomla-cms/41752</a>.</sub>

**Comment by peteruoi** [comment]
I found the same problem for administrator account and till i found this topic it wasn't easy to find the fix. My site also came from an updated version of joomla 3. Maybe we add the fix to the migration script and administrator core.execute.transition make it true?
