### ISSUE TITLE
Nested conditional if

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#41760]
We have quite a few instances of if statements being wrapped in an if statement. Surely the two conditions should be combined into a single if??

### Example
https://github.com/joomla/joomla-cms/blob/78bb192670753c46b374cbaf56440a00266892e9/administrator/components/com_categories/src/Model/CategoryModel.php#L374-L378

```
 if (!$this->getCurrentUser()->authorise('core.admin', $data['extension']) && isset($data['rules']) { 
      unset($data['rules']); 
 }
```

**Comment by alikon** [comment]
the 1st one is more readable imho

**Comment by Quy** [comment]
Each expression on its own line should make it as readable.
```
        if (
            !$this->getCurrentUser()->authorise('core.admin', $data['extension'])
            && isset($data['rules'])
        ) {
            unset($data['rules']);
        }
```

**Comment by skbhagat0502** [comment]
I am working in this issue.

**Comment by Empire101231** [comment]
> We have quite a few instances of if statements being wrapped in an if statement. Surely the two conditions should be combined into a single if??
> 
> ### Example
> https://github.com/joomla/joomla-cms/blob/78bb192670753c46b374cbaf56440a00266892e9/administrator/components/com_categories/src/Model/CategoryModel.php#L374-L378
> 
> ```
>  if (!$this->getCurrentUser()->authorise('core.admin', $data['extension']) && isset($data['rules']) { lovethr24@gmail.com 
>       unset($data['rules']); 
>  }
> ```
