### ISSUE TITLE
[5.0] Dark Mode and template parameter options & A11y

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#41778]
We have two places in core where we make users choose options:
1. The link color. This is not AA a11y compatible in Dark Mode - bootstrap itself has two separate colors for this. Do we want to give users the options to have dark and light mode 
2. The template 'special' color. This text is basically invisible in dark mode

![41409-permissions](https://github.com/joomla/joomla-cms/assets/368084/a6282c3a-32e5-453d-821a-db89b921872f)

Again do we want to have separate colors for this or not? It's presumably going to be hard to have a color that gives A11y compliance in both light and dark modes.

**Comment by HLeithner** [comment]
Different color make sense i think

**Comment by dgrammatiko** [comment]
@HLeithner @wilsonge I'm not convinced that there such a need for another colour. Here's my take with [Muta](https://github.com/dgrammatiko/muta)
<img width="1728" alt="Screenshot 2023-09-17 at 21 03 37" src="https://github.com/joomla/joomla-cms/assets/3889375/f8e57f5f-a35f-4d44-8332-1d13a884ed40">
 
<img width="1726" alt="Screenshot 2023-09-17 at 21 03 27" src="https://github.com/joomla/joomla-cms/assets/3889375/055aa0d7-f82d-4ccc-ab00-ac166788f1f7">

**Comment by wilsonge** [comment]
I’m marking this one as a release blocker as whether we merge the color changes or not these template params need dealing with

**Comment by dgrammatiko** [comment]
> these template params need dealing with

There's still a need to deal with the `-rgb` vars for these colours. In muta I'm doing it directly in the js of the field but for atum (due to b/c) there should be some update fn in the PHP to introduce these values in the db table styles.

**Comment by wilsonge** [comment]
So my intention I think at this point is to remove the special color. When this issue was originally written we used the special color in 5 places in scss. It turned out after review 3 of these places were old code that was no longer used after all the different J4 admin template versions.

So effectively there were two places. the permissions dropdown. I think this can be safely removed and have made a PR for that in #42006. That just leaves `btn-secondary` buttons in the toolbar. I don't even think we have any of these in core. But we just need to find a different accent color for them. Because the existing one won't work in dark mode anyhow....

Then we can either remove the special color completely or leave it in but deprecated for b/c

**Comment by brianteeman** [comment]
as far as I can tell btn-secondary no longer uses the special colour

**Comment by brianteeman** [comment]
Looks like this can be closed
