### ISSUE TITLE
[5.0] Dark Mode calendar icon

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#41781]
Reminder for SVG icon color missing in PR https://github.com/joomla/joomla-cms/pull/41743

@wilsonge

**Comment by C-Lodder** [comment]
Don't forget the arrow icons:

![image](https://github.com/joomla/joomla-cms/assets/2019801/4cec2dc4-87e5-4475-ab9a-c97720aabad9)

As these icons are actions, the contrast needs changing

**Comment by Quy** [comment]
Fixed per #42986.
