### ISSUE TITLE
[5.0] Dark Mode: MFA

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#41794]
![mfa](https://github.com/joomla/joomla-cms/assets/368084/2708e59f-1374-416a-b004-1d2e51d91776)

**Comment by wilsonge** [comment]
Background fix here, buttons as in the arrow and images themselves will have to come in a later PR as they are much harder :D

**Comment by brianteeman** [comment]
the problem is with the class `btn-outline-primary`

Can you add a release blocker on this one please.

**Comment by brianteeman** [comment]
The easiest option is to use the same scss as for .subhead buttons

Not sure what the best way to do that with scss though so will leave it someone else to try

**Comment by brianteeman** [comment]
and for the images you can just do
```
.img {
filter:invert(1);
}
```

**Comment by brianteeman** [comment]
Can be closed as fixed elsewhere in 5.1

![image](https://github.com/joomla/joomla-cms/assets/1296369/0e1b2bec-d632-4cb8-aef4-a991d7c94483)

**Comment by Quy** [comment]
The white background of the image should be fixed.

**Comment by brianteeman** [comment]
I wouldnt change the images myself. They are all consistently sized, have good contrast and consistent backgrounds.

![image](https://github.com/joomla/joomla-cms/assets/1296369/05651f87-da7b-4f18-acc2-0ff22c723c7c)

**Comment by Quy** [comment]
The white background
