### ISSUE TITLE
[com_fields] Subform loses List Values when drag & dropping rows

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#41791]
### Steps to reproduce the issue

**Preparing Child Fields**
- Go to Content -> Fields
- Make sure you already have some custom fields created, one of these should be of type 'List', with a few options under "List Values"

**Preparing Subform**
- Create a new Subform field. Under "Fields" add any field you want, one of these should be the List field you created earlier.
- When creating the Subform field, go to the Options tab, and under the Form Options, set the Layout to 'Form'.

**Replicating the issue**
- Create a new article or edit an existing article.
- Edit the subform field in the article and add a few subform rows (even a couple is fine)
- Make sure to fill in the list child field for each row
- Now try to drag & drop a row up or down to re-order the rows

### Expected result

You'd expect that all values in the child fields retain their value when re-ordering the rows.

### Actual result

The values of the List child field get deleted upon re-ordering.

Here is a quick video showing the issue:
https://drive.google.com/file/d/1cr1LJejZSCsmXuzXw_vPe-HguPx9iZ6G/view?usp=sharing

### System information (as much as possible)

Joomla 4.3.4

### Additional comments

- This is not an issue when the Subform uses the 'Table' layout. This issue only happens when using the 'Form' layout.
- NB: The 'Form' layout can either be chosen manually in the Form Options, or it kicks in automatically when there are more than 4 sub fields.

**Comment by Fedik** [comment]
Does it lossing the value in the form that already saved, or only for newly selected but not saved?

**Comment by AndySDH** [comment]
Does it lossing the value in the form that already saved, or only for newly selected but not saved?
Both

**Comment by Fedik** [comment]
Hm, no, only for unsaved.
It something related to Choices re-init, while changing location in DOM
https://github.com/joomla/joomla-cms/blob/4.3-dev/build/media_source/system/js/fields/joomla-field-fancy-select.w-c.es6.js

Can use following, to reproduce:
```xml
<field type="subform" name="subform" label="subform" multiple="true">
  <form>
    <field type="list" name="list" label="list" layout="joomla.form.field.list-fancy-select">
      <option value="1">1</option>
      <option value="2">2</option>
      <option value="3">3</option>
      <option value="4">4</option>
    </field>
  </form>
</field>
```

**Comment by AndySDH** [comment]
Ah you're right. It only happens with unsaved values, my bad.

**Comment by tkuschel** [comment]
Which database and version is in use? I have another problem with tables consisting of field 'ordering' which is buggy since update mariadb 10.11.4 to 11.1.2 Perhaps there is a correlation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41791">issues.joomla.org/tracker/joomla-cms/41791</a>.</sub>

**Comment by AndySDH** [comment]
No, there is no correlation to databases at all here. This is a javascript issue.

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/42332
