### ISSUE TITLE
No text in "User Profile" fields

### ISSUE THREAD

**Issue by les3trapelles** [joomla/joomla-cms#41792]
### Steps to reproduce the issue
Mark as Optional/Required any user profile filed in "User - Profle" plugin

### Expected result
The name of the profile field should appear inside the input box.

### Actual result
Nothing appears in the input box.

### System information (as much as possible)
PHP 8.2.8
Web server Apache 2.4
Joomla 4.3.4
MySQL 8.0.34

**Comment by Quy** [comment]
Please provide screenshot to explain exactly what you want.

**Comment by les3trapelles** [comment]
Here you have two screenshots. One if of the form in Joomla 3 where the user profile field "Country" has the name and the asterisc. The second one is the form in Joomla 4 but it does not appear any name and neither any asterisc.
![FireShot Capture 298 - USER ACCOUNT - joom3](https://github.com/joomla/joomla-cms/assets/114411706/f2087b38-fb7e-4927-bb0f-2404570a5115)
![FireShot Capture 299 - USER ACCOUNT - joom4](https://github.com/joomla/joomla-cms/assets/114411706/e3568ae5-4228-4b65-901d-bcd6f0b0ab7d)

**Comment by Quy** [comment]
This is from a clean installation without the issue you reported. Are you using a 3rd-party template that could be the culprit?

![41792](https://github.com/joomla/joomla-cms/assets/368084/0be793e8-5ed0-43a0-a9ec-01dfa1ed1dd9)

**Comment by Quy** [comment]
Closing as non-reproducible. Please ask assistance in [Joomla Forum](https://forum.joomla.org/).
