### ISSUE TITLE
[5.0] Dark Mode: Editors

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#41801]
Should these be white background?

![dropdown](https://github.com/joomla/joomla-cms/assets/368084/f4b47b01-6a65-4204-8b94-d8f4d1a82ec1)

**Comment by wilsonge** [comment]
The dropdown nope. Fix here https://github.com/joomla/joomla-cms/pull/41804

Tiny more complicated - there is a dark theme but you have to detect in the plugin whether the template supports dark mode (e.g. atum does but casseopia doesn't)

**Comment by wilsonge** [comment]
Is everything here now either fixed or covered in #42322 ?
