### ISSUE TITLE
[5.0] Dark Mode: Modules

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#41802]
![modules](https://github.com/joomla/joomla-cms/assets/368084/7dd7946f-1178-411c-b4e5-0123331b2419)

**Comment by wilsonge** [comment]
How do we feel about sharing the colors between this and the cpanel quick icons? Slightly larger rework to set some SCSS variables for that but gives UI consistency going forward

**Comment by Quy** [comment]
Yes as they do look similar with the + icon.

**Comment by wilsonge** [comment]
Fix https://github.com/joomla/joomla-cms/pull/41920
