### ISSUE TITLE
[5.0] Dark Mode: Menu Dashboard Home icon

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#41818]
![menu-dashboard-home](https://github.com/joomla/joomla-cms/assets/368084/d3e4bb0d-62fe-415b-a6d3-d367dfd76c8c)

**Comment by wilsonge** [comment]
in light mode is the fact it's not a white background visible to you (we use "white-offset"). to me it's invisible and i'd just like to remove the background. but checking first it's not just i'm blind!

**Comment by Quy** [comment]
Yes, and change the icon to white in dark mode.

**Comment by wilsonge** [comment]
Fix: https://github.com/joomla/joomla-cms/pull/41919
