### ISSUE TITLE
[4.3.4] Problem Media Manager with large item names

### ISSUE THREAD

**Issue by Mich-es** [joomla/joomla-cms#41839]
### Steps to reproduce the issue
Create a picture an name it withe more than 20 charakters
Upload in media library 
New Article select picture and try to rename it

### Expected result
I can rename the picture

### Actual result
I cant rename the picture - see screenshot
![Unbenannt](https://github.com/joomla/joomla-cms/assets/58422824/1cb6fb3c-0e87-4297-930a-6528005c96d4)
![Unbenannt1](https://github.com/joomla/joomla-cms/assets/58422824/2605d49b-9e77-4d7a-a466-eb5a7d5ec772)

### System information (as much as possible)
J4.3.4

**Comment by brianteeman** [comment]
Unable to replicate

**Comment by Mich-es** [comment]
I can reproduze this with Joomla 5.0.1

**Comment by brianteeman** [comment]
![image](https://github.com/joomla/joomla-cms/assets/1296369/ee0a9778-9e4a-437f-adf6-26fe3bab6a30)

![image](https://github.com/joomla/joomla-cms/assets/1296369/79c16f64-7fed-4fcf-97ee-ef56bf43290e)

**Comment by Mich-es** [comment]
FIRST create a picture with more than 20 charakters (try out up to 80 charakters to reprouce it)
THAN try to rename it

**Comment by brianteeman** [comment]
![media](https://github.com/joomla/joomla-cms/assets/1296369/cec1aff4-560c-4301-ab0f-3dd609ca272f)

**Comment by Mich-es** [comment]
On your screenshot, rename picture 2.jpg up to 80 charakters or more an than try it again to rename it

**Comment by brianteeman** [comment]
The tool is called licecap

![media2](https://github.com/joomla/joomla-cms/assets/1296369/409d2529-0885-4a0a-b7eb-ef4b253301f8)

**Comment by Mich-es** [comment]
![test](https://github.com/joomla/joomla-cms/assets/58422824/e01cefe5-fc19-4c78-bdc6-e40a65bb5634)

**Comment by Mich-es** [comment]
No error Message
The long file name moves the selection area to the left into the area that is no longer visible. Just try it out and make the file name long enough until this bug occurs. Please bear in mind that you do not always have high screen resolutions. So please also try CTRL+

PHP 8.2
Joomla 5.0.1

**Comment by brianteeman** [comment]
ah - I think I finally understand what you are saying.

When the filename is very long it pushes the dropdown menu off to the left of the screen and it can at some resolutions or screen positions push the menu off the screen completely.

Is that correct?

I can think of a few possible solutions
1. Use css to truncate the display of the filename 
2. Change the alignment of the dropdown menu items
3. Separate the display of the filename and dropdown

**Comment by Mich-es** [comment]
> Is that correct?

Yes, finally someone who understands me :-)

**Comment by brianteeman** [comment]
Example solution

![example](https://github.com/joomla/joomla-cms/assets/1296369/5a155fb3-39ef-4817-b211-c9bc55241812)

**Comment by Mich-es** [comment]
Yes, this looks good!

One more thing - if you extend the file name, the entire image area slides down and you wonder where the images have disappeared to 
![test](https://github.com/joomla/joomla-cms/assets/58422824/b41e3fb3-3281-4e3e-92d3-b8a9009ab3de)

**Comment by brianteeman** [comment]
Ok. Will prepare a fix later today

**Comment by Quy** [comment]
Fixed per #42691. Thanks!
