### ISSUE TITLE
[4.3.4] Sort List Category on new article

### ISSUE THREAD

**Issue by Mich-es** [joomla/joomla-cms#41837]
### Steps to reproduce the issue
Create more than 10 numbered entries in a category.
Create a new article and select the newest category

### Expected result
The newest category appears

### Actual result
The oldest category appears and you have to type everything to get to the newest category

![screen shot 2023-09-20 at 10 49 26](https://issues.joomla.org/uploads/1/75810b74f27f1e66501e0e264663d372.jpg)

### System information (as much as possible)
J4.3.4

**Comment by Quy** [comment]
Have you tried to manually sort them under Content > Categories?

![41837](https://github.com/joomla/joomla-cms/assets/368084/b75befda-ce32-42e2-997c-f817722dd8c6)

**Comment by Mich-es** [comment]
Thanks for the feedback - Ok, that works, but you have to figure it out first. The field looks like a search field, which should not be based on the sorting in the backend - because these can be arranged in this way for various reasons. 
It would be better to sort the whole thing by date, so the newest category is always on top, if that's possible in this search field.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41837">issues.joomla.org/tracker/joomla-cms/41837</a>.</sub>

**Comment by brianteeman** [comment]
> It would be better to sort the whole thing by date, so the newest category is always on top, if that's possible in this search field.

While it would be better in your scenario it would not be in other category structures eg

![image](https://github.com/joomla/joomla-cms/assets/1296369/b1aa787d-1cd9-46bd-818f-090b29165092)

**Comment by rdeutz** [comment]
Expected behaviour. I am sorry that it doesn't fit your needs, but there is a way to get what you want. I am closing this.
