### ISSUE TITLE
[5.0] PHP Warnings in Versions - Cannot declare class \joomla\cms\table\contenttype, because the name is already in use

### ISSUE THREAD

**Issue by hendrikbehncke** [joomla/joomla-cms#41835]
### Steps to reproduce the issue
Open the Versions of an article or category 

### Actual result

There are two PHP Warnings

Warning
: Cannot declare class \joomla\cms\table\contenttype, because the name is already in use in
/var/www/html/joomla-5/libraries/loader.php
on line 576

Warning
: Cannot declare class \joomla\cms\table\contenthistory, because the name is already in use in
/var/www/html/joomla-5/libraries/loader.php
on line
576

<img width="1698" alt="Screenshot 2023-09-20 at 16 44 06" src="https://github.com/joomla/joomla-cms/assets/4417047/6cb6a10f-002b-4af6-9c87-148cb9bc1e14">

### System information (as much as possible)
Joomla 5.0 Beta 2
PHP 8.1.23

**Comment by richard67** [comment]
@hendrikbehncke Is it a new installation of 5.0.0 Beta 2? Or has it been upgraded from a lower version? If the latter: From which version?

**Comment by HLeithner** [comment]
can't replicate the issue with 5.0.0 beta2...

**Comment by hendrikbehncke** [comment]
@richard67 I have upgraded from 5.0.0 Beta 1 using the Beta 2 Update Package: https://github.com/joomla/joomla-cms/releases/download/5.0.0-beta2/Joomla_5.0.0-beta2-Beta-Update_Package.zip

**Comment by richard67** [comment]
@hendrikbehncke And the Beta 1 was a new installation? Or did that also have an update history?

**Comment by hendrikbehncke** [comment]
@richard67 Had another look into it. It happens when the Backward Compatibility Plugin is enabled.
Happens in a fresh 5.0 installation and in an upgraded version from 4.3.4

**Comment by HLeithner** [comment]
fixed the one of the messages in #41853 so closing this here, but I can't find the second one
