### ISSUE TITLE
Can't save personal module in front

### ISSUE THREAD

**Issue by Mika17420** [joomla/joomla-cms#41833]
### Steps to reproduce the issue

modify front module with administrator right

### Expected result

missing publish label

**Comment by Mika17420** [comment]
status not active

**Comment by richard67** [comment]
@Mika17420 Could you provide more information? E.g. which Joomla version do you use? The heading "System information (as much as possible)" in the prepared text for the issue was not there for nothing.

**Comment by richard67** [comment]
@Mika17420 Sorry, why closed? has your issue been solved? Or just hit the wrong button?
