### ISSUE TITLE
'More Information' popover in pre-update check references 'Live Update' tab which no longer exists

### ISSUE THREAD

**Issue by bayareajenn** [joomla/joomla-cms#41845]
### Steps to reproduce the issue
In 4.4.0 beta 3:
1. Install at least one extension that has a potential upgrade issue (Gantry 5, JCE, Solidres, HTTPHeaders).
2. Go to the Joomla update component and click the Options button in the Top Toolbar on the right.
3. In Update Source, enter the Update Channel Custom URL, Minimum Stability Development, and enter the Custom URL for J5 nightlies (https://update.joomla.org/core/nightlies/next_major_list.xml).
![update-source-2023-09-20_13-54-16](https://github.com/joomla/joomla-cms/assets/5952595/bc9844c8-c051-47bb-9e02-8b6a46358e64)
4. Click Save & Close in the Top Toolbar.

Now, look at your list of Extensions that need attention. Some will have a little link next to them that says "More Information". This opens a popover in which the last sentence says "For more information about the relevant plugins please check the 'Live Update' tab."
![remove-sentence-2023-09-20_13-17-54](https://github.com/joomla/joomla-cms/assets/5952595/2ea795db-d198-472b-86b5-7004c860286d)

But there is no 'Live Update' tab in J4. This sentence should be removed.

### Expected result
That there wouldn't be a sentence that leads to confusion since there is no 'Live Update' tab.

### Actual result
Confusion. There is no 'Live Update' tab.

### System information (as much as possible)
Windows 10
PHP 8.1
Joomla 4.4.0 beta 3 from today's nightlies

**Comment by richard67** [comment]
Closing as having a pull request. Please test #42047 . Thanks in advance.
