### ISSUE TITLE
Installer,Database type only one option "None"

### ISSUE THREAD

**Issue by brent51** [joomla/joomla-cms#41849]
### Steps to reproduce the issue
Joomla Installer,
Joomla! 5.0.0-beta2

Database Configuration,
Select the database type.

### Expected result

Database type has multiple options

### Actual result
There is only one option "None"

### System information (as much as possible)
win10
php v8.2.9

**Comment by richard67** [comment]
Which options are available depends on which PHP extensions for database clients are available.

For MySQL or MariaDB it either needs the mysqli or the pdo_mysql extension.

Can you check if the problem is that both are not available?

**Comment by alikon** [comment]
same as #42115
