### ISSUE TITLE
[5.0] Dark Mode: Language Overrides

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#41860]
![dark-language-override](https://github.com/joomla/joomla-cms/assets/368084/88953076-571e-4fd9-a033-6ec7d8f4ad87)

**Comment by wilsonge** [comment]
This kinda comes under https://github.com/joomla/joomla-cms/issues/41778 - the latter list is styled with the global action theme color and the upper is the info theme color.

**Comment by Quy** [comment]
Fixed per #42757.
