### ISSUE TITLE
http requestm filename missing slash lead to 404

### ISSUE THREAD

**Issue by CharlesGueunet** [joomla/joomla-cms#41896]
### Steps to reproduce the issue

I installed Joomla, behind an NGinx server, using the [recommended config file](https://docs.joomla.org/Nginx).  
The install process worked as expected and the connection with the DB is working as expected.  
The administrator module (`ROOT_URL/administrator`) is working well and gives no error / warning.

however, loading the main site (`ROOT_URL/index.php`), the login page looks like a pure HTML page and I have a lots of 404 error in the network panel.
Some of the js files also present in the administrator module seem to be found correctly and the http request have the right filename.  
The erroneous ones all looks like this:

```
GET |  
scheme | http
host | ROOT_URL (replaced)
filename | /mediasystemjsmessages.js
```
### Expected result

I would expect these request to contains slash between modules:
```
filename | /media/system/js/messages.js
```

### System information (as much as possible)

* Joomla 4.3.2-1  (From AUR)
* Arch Linux
* NGinx
  * Slightly modified php-fpm config
* maria db
* PHP 8.2
* tested on firefox

**Comment by richard67** [comment]
@CharlesGueunet Which Joomla version have you installed?

**Comment by CharlesGueunet** [comment]
> @CharlesGueunet Which Joomla version have you installed?

Ooops, it is the 4.3.2-1 (from the AUR)   I have updated the main description accordingly. Thanks

**Comment by richard67** [comment]
@CharlesGueunet What is "AUR"?

**Comment by CharlesGueunet** [comment]
It is simply the way I installed Joomla, it relies on [this specific script](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=joomla) which simply download the joomla archive and put it under `/usr/share/webapps/joomla` and handle permission.

I can git clone on the folder and this would give the same result.

**Comment by richard67** [comment]
@CharlesGueunet How shall a reader of this issue know this? That's why I had asked.

**Comment by CharlesGueunet** [comment]
I can try to spend some time debugging this, but I have no idea where to start. Can someone point me where these URI are built in the joomla codebase ?

**Comment by richard67** [comment]
Do you use an ".htaccess" file in the Joomla root folder or a parent folder of that folder? If so: What happens if you replace that by the "htaccess.txt" coming with Joomla, i.e. rename ".htaccess" to e.g. ".htaccess.bak" and then "htaccess.txt" to ".htaccess"?

**Comment by CharlesGueunet** [comment]
From my understanding, `.htaccess` is for Apache.  I use the NGinx server with the config file recommended on the joomla website (more details are given on the description).  
I still tried your suggestion, with no avail. No change in behavior.

I should add that when I inspect the dom, client side, I already have invalid uri, looking like this:
```
<link href="[/mediatemplatessitecassiopeiacssvendorjoomla-custom-elementsjoomla-alert.css?0.2.0](view-source:http://joomla.gueu.net/mediatemplatessitecassiopeiacssvendorjoomla-custom-elementsjoomla-alert.css?0.2.0)" rel="stylesheet" data-asset-name="webcomponent.joomla-alert" />
```
I do not think the NGinx engine is involved in writting the URI like that, and I assume it is already invalid, but I am not sure about this.

**Comment by richard67** [comment]
Ah sorry, I forgot it was NGinx.

**Comment by CharlesGueunet** [comment]
Going further, I played around with some PHP file to understand the issue.

File : **libraries/src/Document/Renderer/Html/ScriptRenderer.php**  
In [renderElement](https://github.com/joomla/joomla-cms/blob/f8584d24a73386c45d87be92d378e1be74894aae/libraries/src/Document/Renderer/Html/ScriptsRenderer.php#L142)  

The `$src` variable already contains invalid entries. Here is a log of values taken by this variable for the main page loading:

```
   1   │ mediavendorjqueryjsjquery.js
   2   │ mediamod_menujsmenu-es5.js
   3   │ mediasystemjscore.js
   4   │ mediatemplatessitecassiopeiajstemplate.js
   5   │ mediasystemjskeepalive-es5.js
   6   │ mediasystemjsmessages-es5.js
   7   │ 
   8   │ 
   9   │ mediasystemjskeepalive.js
  10   │ mediasystemjsfieldspasswordview.js
  11   │ mediasystemjsmessages.js
  12   │ mediaplg_system_debugjsdebug.js
  13   │ mediavendorjqueryjsjquery.js
  14   │ mediasystemjscore.js
  15   │ mediatemplatessitecassiopeiajstemplate.js
  16   │ mediasystemjsmessages-es5.js
  17   │ 
  18   │ 
  19   │ mediasystemjsmessages.js
  20   │ mediaplg_system_debugjsdebug.js
  21   │ mediavendorjqueryjsjquery.js
  22   │ mediasystemjscore.js
  23   │ mediatemplatessitecassiopeiajstemplate.js
  24   │ mediasystemjsmessages-es5.js
  25   │ 
  26   │ 
  27   │ mediasystemjsmessages.js
  28   │ mediaplg_system_debugjsdebug.js
```

All "/" are missing already here. I will try to backtrace this. If someone knows where this variable comes from, it would be of much help.

@Fedik it seems you are the main author of this function, do you have anything that could help me ?

**Comment by Fedik** [comment]
Try create an article with url, like:
```html
<a href="foo/bar/page.html">Test link</a>
```
And tell how link is rendered on your site

**Comment by CharlesGueunet** [comment]
I created an article with 2 links are requested.
The two links are correctly written:

```html
<p>This is a test with a link:</p>
<p> </p>
<p>The<a title="link1" href="[/foo/bar/page.html](view-source:http://[hidden]/foo/bar/page.html)"> link1</a></p>
<p>The<a title="link2" href="[/foo/bar/page.js](view-source:http://[hidden]/foo/bar/page.js)"> link2</a></p>
```

Here is the resulting page:

![image](https://github.com/joomla/joomla-cms/assets/5412579/3faff114-437c-4a75-bd64-76cbfdf0c384)

**Comment by Fedik** [comment]
hm, okay, maybe not as link but as text.
well, something on your installation changes the rendering. Can be any plugin or server config.

`renderElement` can produce this only if any of plugin overide HTMLHelper, or the assets in genreal.
Or server modifying your output and so debug is wrong also.

Many many possible reasons, but does not looks like comes from joomla core.

**Comment by CharlesGueunet** [comment]
adding "/" in the text or in the title also lead to "/" in the article as expected.

This is a fresh install with a single user, 0 plugins and no fancy configuration.

Could my nginx interfere with how the php handle the link source before the page is written ? All the log I wrote where written with a `file_put_contents` in the PHP code so I could avoid any interference with my server.

**Comment by Fedik** [comment]
I do not see any reason why it could happen in core, without extra modification.

>   All the log I wrote where written with a file_put_contents

Then I realy have no idea, 
Try maybe a new clean installation, and try without modifing nginx config.

**Comment by CharlesGueunet** [comment]
I continue my investigations.

Seems like in `WebAssetItem.php ::  resolvPath`,  `$file` contains the "/" before the  call to `HTMLHelper::_`  and none after:

Exemple
```
 before:  plg_system_debug/debug.min.js
 after:   mediaplg_system_debugjsdebug.js
```

I will try to understand how the `HTMLHelper` works, seems like it is not an easy one.

**Comment by Fedik** [comment]
It uses `HTMLHelper::_('script', $path)` or `HTMLHelper::_('stylesheet', $path)` to get a final path.
Wich by default implemented in `HTMLHelper::script()` and `HTMLHelper::stylesheet()`, but also can be overiden by any plugin.

**Comment by Hackwar** [comment]
Is this still an issue?

**Comment by CharlesGueunet** [comment]
> Is this still an issue?

I do not know, I have installed joomla on another distribution and as it worked I removed this one. If I had a penny to bet, I would say the issue was due to the communication with the database that somehow stripped the string from some special character, but I am not a php / web specialist.

I think we can close this.

**Comment by Hackwar** [comment]
thanks. Closing.
