### ISSUE TITLE
Allowed Extensions png 2 times

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#41898]
Hi guys,
Why is the "Media Options > Allowed Extensions: png" listed two times ?

I add an image here for you
![Screenshot_20230923-132142780~2 (1)](https://github.com/joomla/joomla-cms/assets/14607633/2aeef75f-16dc-4e12-be80-3dca70c8d25d)

**Comment by brianteeman** [comment]
see #41900

**Comment by richard67** [comment]
Closing as having a pull request. Please test #41900 . Thanks in advance.
