### ISSUE TITLE
[4.3.4] Category List uses <th> element within <tbody> where it should be <td>

### ISSUE THREAD

**Issue by keithgrimes** [joomla/joomla-cms#41892]
### Steps to reproduce the issue
Create a new menu entry which is defined as a 'Category List'
Ensure the appropriate category is also selected. 

### Expected result
When rendering 

<table class="com-content-category__table category table table-striped table-bordered table-hover">
            <caption class="visually-hidden">
                Articles            </caption>
            <thead>
                <tr>
                    <th scope="col" id="categorylist_header_title">
                        <a href="#" onclick="Joomla.tableOrdering('a.title','asc','', document.getElementById('adminForm'));return false;" class="hasTooltip" data-bs-placement="top" data-bs-original-title="Select to sort by this column">Title</a>                    </th>
                                                                                                                                        </tr>
            </thead>
            <tbody>
                        <tr class="cat-list-row0">
                                **<td class="list-title" scope="row">**
                                            Printing your walks programme :                         <a href="/component/users/login.html?Itemid=435&amp;return=aW5kZXgucGhwP29wdGlvbj1jb21fY29udGVudCZ2aWV3PWFydGljbGUmaWQ9NDgxOnByaW50aW5nLXlvdXItd2Fsa3MtcHJvZ3JhbW1lJmNhdGlkPTEwOA==" class="register">
                            Register to read more …                        </a>
                                 **</td>**
                         </tr>

### Actual result

<table class="com-content-category__table category table table-striped table-bordered table-hover">
            <caption class="visually-hidden">
                Articles            </caption>
            <thead>
                <tr>
                    <th scope="col" id="categorylist_header_title">
                        <a href="#" onclick="Joomla.tableOrdering('a.title','asc','', document.getElementById('adminForm'));return false;" class="hasTooltip" data-bs-placement="top" data-bs-original-title="Select to sort by this column">Title</a>                    </th>
                                                                                                                                        </tr>
            </thead>
            <tbody>
                        <tr class="cat-list-row0">
                                **<th class="list-title" scope="row">**
                                            Printing your walks programme :                         <a href="/component/users/login.html?Itemid=435&amp;return=aW5kZXgucGhwP29wdGlvbj1jb21fY29udGVudCZ2aWV3PWFydGljbGUmaWQ9NDgxOnByaW50aW5nLXlvdXItd2Fsa3MtcHJvZ3JhbW1lJmNhdGlkPTEwOA==" class="register">
                            Register to read more …                        </a>
                                 **</th>**
                         </tr>

### System information (as much as possible)

Linux / mysql platform. PHP 8.0 / 8.1
Joomla 4.3.4

### Additional comments

The file components/com_content/tmpl/category/default_articles.php line 174 states 

                <th class="list-title" scope="row">

This should be 

                <td class="list-title" scope="row">

**Comment by chmst** [comment]
We use this in Joomla for accessibility of tables. The <th> is not only for the table header but indicates the "main" cell in a row. 
Here is a nice description: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/th with example.

**Comment by richard67** [comment]
Closing as expected behaviour. See the link in the previous comment for the explanation. It is perfectly valid to have a th in a table row in the tbody. The `scope="row"` makes clear that it is the row's header.

**Comment by keithgrimes** [comment]
Many thanks for clarifying and for the quick response.
