### ISSUE TITLE
[5.0] Unable to delete user group

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#41906]
### Steps to reproduce the issue
delete a user group

### Expected result
group gone

### Actual result
```
0 Joomla\CMS\Event\Model\ModelEvent::setContext(): Argument #1 ($value) must be of type string, array given, called in /web/darmplus.verlauf.at/libraries/src/Event/AbstractEvent.php on line 205

Call stack
--
# | Function | Location
1 | () | JROOT/libraries/src/Event/Model/ModelEvent.php:75
2 | Joomla\CMS\Event\Model\ModelEvent->setContext() | JROOT/libraries/src/Event/AbstractEvent.php:205
3 | Joomla\CMS\Event\AbstractEvent->setArgument() | JROOT/libraries/src/Event/AbstractEvent.php:115
4 | Joomla\CMS\Event\AbstractEvent->__construct() | JROOT/libraries/src/Event/AbstractImmutableEvent.php:51
5 | Joomla\CMS\Event\AbstractImmutableEvent->__construct() | JROOT/libraries/src/Event/Model/ModelEvent.php:55
6 | Joomla\CMS\Event\Model\ModelEvent->__construct() | JROOT/libraries/src/Application/EventAware.php:106
7 | Joomla\CMS\Application\WebApplication->triggerEvent() | JROOT/administrator/components/com_users/src/Model/GroupModel.php:282
8 | Joomla\Component\Users\Administrator\Model\GroupModel->delete() | JROOT/libraries/src/MVC/Controller/AdminController.php:152
9 | Joomla\CMS\MVC\Controller\AdminController->delete() | JROOT/administrator/components/com_users/src/Controller/GroupsController.php:65
10 | Joomla\Component\Users\Administrator\Controller\GroupsController->delete() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
11 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
12 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
13 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
14 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
15 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
16 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
17 | require_once() | JROOT/administrator/index.php:32
18 | require_once() | JROOT/public/administrator/index.php:16

```

### System information (as much as possible)
5.0.0-beta2

**Comment by heelc29** [comment]
Something with the event mapping is wrong:

https://github.com/joomla/joomla-cms/blob/fa0800b39a09dc8a9a0126a3636d6e5d8b4a5fe9/libraries/src/Event/CoreEventAware.php#L130-L131

`User\xxxDeleteEvent` will work, but I'm not sure if this is the "right" event ...

---

https://github.com/joomla/joomla-cms/blob/fa0800b39a09dc8a9a0126a3636d6e5d8b4a5fe9/administrator/components/com_users/src/Model/GroupModel.php#L282
https://github.com/joomla/joomla-cms/blob/fa0800b39a09dc8a9a0126a3636d6e5d8b4a5fe9/administrator/components/com_users/src/Model/GroupModel.php#L291

**Comment by Fedik** [comment]
hm, this 2 events does not follow the parent implementation of delete() events: https://github.com/joomla/joomla-cms/blob/2d99f3bb4b68688f71f6f915ceb715e51d969e19/libraries/src/MVC/Model/AdminModel.php#L845-L848

Almost all Model events requires `context` value, but here it is missing.

**Comment by HLeithner** [comment]
better to normalize it now?

**Comment by Fedik** [comment]
it probably will be need own event class, because `onUserAfterDeleteGroup` https://github.com/joomla/joomla-cms/blob/2d99f3bb4b68688f71f6f915ceb715e51d969e19/administrator/components/com_users/src/Model/GroupModel.php#L291
Is very different from model onAfterDelete. It more like a copy/paste of onUserDeleteEvent, which have nothing to do with UserGroup.

The issue, that it wil make an incosistency, because onUserBeforeSaveGroup and onUserAfterSaveGroup is perfectly fit in to Model events,

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/41916
