### ISSUE TITLE
[5.0] Event argument error on installing from invalid URL.

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#41907]
### Steps to reproduce the issue

Try to install an extension from invalid URL, debug is enabled.

### Expected result

See only "Could not open..." Joomla warning.

### Actual result

PHP error

```
An error has occurred.
0 Joomla\CMS\Event\Installer\InstallerEvent::onSetPackage(): Argument #1 ($value) must be of type ?array, bool given, called in \libraries\src\Event\AbstractEvent.php on line 225
```

### System information (as much as possible)

Joomla5 nightly

**Comment by HLeithner** [comment]
@Fedik can you have a look please?

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/41914
