### ISSUE TITLE
[5.0.] Blog sample data - New Feature

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#41913]
Blog Sample data cotain an article "New Feature: Workflow" 

![grafik](https://github.com/joomla/joomla-cms/assets/1035262/8ae984ef-e1e6-472b-9a04-1a942114d730)

### Describe the solution you'd like
Workflow is no longer New Feature. We can remove the new feature label from this text. 

If a native speaker writes a similar text for the Giuded Tour I could add it as "New Feature" into Blog sample data.

**Comment by rdeutz** [comment]
Could we for now just remove the "New feature:"?

**Comment by Quy** [comment]
Please test #43386. Thanks.
