### ISSUE TITLE
Adding images in TinyMCE editor from Subform Custom Field

### ISSUE THREAD

**Issue by easypony** [joomla/joomla-cms#41915]
### Steps to reproduce the issue
Have TinyMCE as default editor
Create a custom field of type "editor" assigned to a subfield (along with other text fields).
Start a new article
Switch to the 'Fields' tab for the subform and repeat the subform a few times.
In the second (or third, makes no difference) TinyMCE editor field use "CMS Content" button to add image where the cursor is placed

### Expected result
To see the image in the part of the TinyMCE editor where the cursor was placed

### Actual result
The image is loaded into the first TinyMCE editor instance before any content that was already there.

### System information (as much as possible)
Joomla 4.3.4

### Additional comments
Could it as easy as a seperate ID for each editor instance?

**Comment by Fedik** [comment]
Well, unfortunately the media select (and field) still need a work, to transform to dialog, and to use new xtd-buttons api to make it work. It still valid bug. Maybe something for 5.1.
Other xtd-buttons was more easy, and they already works good in 5.0.


It is a known issue, but cannot really find any older opened.

**Comment by easypony** [comment]
To confirm there will be no fix for version 4?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41915">issues.joomla.org/tracker/joomla-cms/41915</a>.</sub>

**Comment by Fedik** [comment]
Correct

**Comment by easypony** [comment]
Cheers<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41915">issues.joomla.org/tracker/joomla-cms/41915</a>.</sub>

**Comment by brianteeman** [comment]
This should be closed

**Comment by Fedik** [comment]
Why? it is valid bug

**Comment by brianteeman** [comment]
sorry I thought this was fixed in 5.0

**Comment by Fedik** [comment]
The fix will be there, please test https://github.com/joomla/joomla-cms/pull/42288
