### ISSUE TITLE
[4.4.0-beta2] WebAuthn Login Fails

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#41911]
### Steps to reproduce the issue

1.    Set Web Authentication for a user and set it to standard method
2.    Log out from backend
3.    Try to log-in again with this user and click on button "Validate with your Authenticator"

### Expected result
The user gets logged in after entering his PIN (in my case Windows Hello)

### Actual result
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/2def3d9b-75c0-4739-993f-ff9124ff94af)

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/852b15ca-20b2-496b-92b4-acf30b2d8155)

### System information (as much as possible)
Joomla 4.4.0 beta 2
Mozilla Firefox
Windows Hello

### Additional comments
I got the same (or a very similar) error when testing J5alpha1. This was reported as #41072.

**Comment by dautrich** [comment]
@richard67  I assume that the patch will be similar (or equal) to the one in J7alpha. Can you provide it to me so that I can rescue my current installation?!

**Comment by richard67** [comment]
The fix was this: #41073 . Not sure if it applies here in the same way. Am at work, can’t check details now.

**Comment by dautrich** [comment]
@richard67 

> The fix was this: https://github.com/joomla/joomla-cms/pull/41073
I know

> Am at work, can’t check details now.
Don't worry! I'm not at all in a hurry.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #41917 . Thanks in advance.
