### ISSUE TITLE
Getting a Joomla 4 API component to work with language files

### ISSUE THREAD

**Issue by cappuccinonet** [joomla/joomla-cms#41944]
### Steps to reproduce the issue
When programming a component for an API in Joomla 4, the config contains the following language file definitions:
```
<api>
    <files folder="api">
        <folder>src</folder>
    </files>
    <languages folder="api">
        <language tag="en-GB">language/en-GB/com_mycomponent.ini</language>
        <language tag="en-GB">language/en-GB/com_mycomponent.sys.ini</language>
    </languages>
</api>
```
The component installs without errors, but the language files in the folder /api/language/en-GB/* of the component aren't copied to the folder /api/language/en-GB/ as described here https://www.dionysopoulos.me/book/com-lang.html.

When I copy the language files manually, they are interpreted correctly. Languages other than en-GB do not seem to work.

### Expected result

All language files within the <api> element should be copied to the /api/language folder.

### System information (as much as possible)

Joomla 4.3.4

**Comment by Fedik** [comment]
> All language files within the element should be copied to the /api/language folder.

Not really. It was like that long time ago.

Nowaday all language files should be within component:
for Site `components/com_example/language`, 
for API `api/components/com_example/language`, 
for Administrator `administrator/components/com_example/language`,

**Comment by brianteeman** [comment]
@Fedik sorry that is not correct

**Comment by richard67** [comment]
@cappuccinonet Could you post the content of the manifest XML of that component?

**Comment by cappuccinonet** [comment]
@richard67 Just fixed the markup to show up the code. 
Before opening this thread I posted the question [on Stackexchange](https://joomla.stackexchange.com/questions/33383/getting-a-joomla-4-api-component-to-work-with-language-files "https://joomla.stackexchange.com/questions/33383/getting-a-joomla-4-api-component-to-work-with-language-files")
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41944">issues.joomla.org/tracker/joomla-cms/41944</a>.</sub>

**Comment by richard67** [comment]
Where in the zip file of the package are the language files located? Reading [this answer on Stackexchange](https://joomla.stackexchange.com/a/33385) I would assume they are located inside the "api" folder in the zip, not in a subfolder of that. Or do you have them inside folder "api/language" in the zip, and the "api" folder is at the first level inside the zip? Then your XML should be:

```
<api>
    <files folder="api">
        <folder>src</folder>
    </files>
    <languages folder="api/language">
        <language tag="en-GB">language/en-GB/com_mycomponent.ini</language>
        <language tag="en-GB">language/en-GB/com_mycomponent.sys.ini</language>
    </languages>
</api>
```

Not sure if that will work, but that's how I understand that answer on Stackexchange.

**Comment by cappuccinonet** [comment]
They are located here:
```
<extension> 
   ...
   <namespace path="src">MyCompany\Component\MyExtension</namespace>
   ...
   <administration>
      <files folder="admin">
         ...
      </files>
      <languages folder="admin">
        <language tag="en-GB">language/en-GB/com_mycomponent.ini</language>
        <language tag="en-GB">language/en-GB/com_mycomponent.sys.ini</language>
      </languages>
   <administration>
   ...
   <api>
      <files folder="api">
         <folder>src</folder>
      </files>
      <languages folder="api/language">
         <language tag="en-GB">language/en-GB/com_mycomponent.ini</language>
         <language tag="en-GB">language/en-GB/com_mycomponent.sys.ini</language>
      </languages>
   </api>
   ...
</extension>
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41944">issues.joomla.org/tracker/joomla-cms/41944</a>.</sub>

**Comment by cappuccinonet** [comment]
The files itself are located inside the zip like this:
```
/admin/language/en-GB
/api/language/en-GB
```
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41944">issues.joomla.org/tracker/joomla-cms/41944</a>.</sub>

**Comment by brianteeman** [comment]
```
      <languages folder="api/language">
         <language tag="en-GB">en-GB/com_mycomponent.ini</language>
         <language tag="en-GB">en-GB/com_mycomponent.sys.ini</language>
      </languages>
```

**Comment by cappuccinonet** [comment]
@brianteeman I tried that too, but it failed to work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41944">issues.joomla.org/tracker/joomla-cms/41944</a>.</sub>

**Comment by Fedik** [comment]
> Fedik sorry that is not correct

I mean, it what is prefered.
You just place your language under component, and all works:

```xml
<administration>
  <files folder="admin">
    <folder>language</folder>
    ...    
  </files>
<administration>

<api>
  <files folder="api">
      <folder>language</folder>
      ...
  </files>
</api>

<files folder="site">
  <folder>language</folder>
  ...
</files>
```

There was a discussion here some years ago, but it will be hard to find.

**Comment by Fedik** [comment]
> I tried that too, but it failed to work.

What @brianteeman suggested should work, maybe one paths is incorect,
you also can try other way around:
```xml
<api>
      <files folder="api">
         <folder>src</folder>
      </files>
      <languages folder="api">
         <language tag="en-GB">language/en-GB/com_mycomponent.ini</language>
         <language tag="en-GB">language/en-GB/com_mycomponent.sys.ini</language>
    </languages>
</api>
```

But I would suggest to try what I wrote in previous comment, it much more clean and easy.

**Comment by heelc29** [comment]
@cappuccinonet Could you please test #43152?

**Comment by richard67** [comment]
Closing as having a pull request. Please test #43152 . Thanks in advance.
