### ISSUE TITLE
[5.0b3] Error accessing template styles in admin

### ISSUE THREAD

**Issue by masonboswell** [joomla/joomla-cms#41940]
### Steps to reproduce the issue

I have a custom template based on Cassiopeia that does not have any folders in the media directory other than images.  5.0 Beta 3 appears to be assuming there is a CSS folder.  When I click on the template styles entry for my template in the backend, I get the error: 

"Joomla\Filesystem\Folder::files: Path is not a folder. Path: [ROOT]/media/templates/site/mycassiopeia/css/global/".

I am attaching my template in case you need it to repro, rename it with a ZIP extension since this bug tracker won't let me upload a ZIP.  It is pretty much Cassiopeia but downloads Bootstrap from CDN and does not depend on the current Joomla system version of Bootstrap.  Also attaching screenshots of the error.  

### Expected result

I should see my template style settings and not receive an error.  

### Actual result

An error is displayed. 

### System information (as much as possible)

MacOS Sonoma running XAMPP 8.2.4.  

### Additional comments

Call stack
#	Function	Location
1	()	JROOT/libraries/vendor/joomla/filesystem/src/Folder.php:337
2	Joomla\Filesystem\Folder::files()	JROOT/libraries/src/Form/Field/FilelistField.php:210
3	Joomla\CMS\Form\Field\FilelistField->getOptions()	JROOT/libraries/src/Form/Field/ListField.php:63
4	Joomla\CMS\Form\Field\ListField->getInput()	JROOT/libraries/src/Form/FormField.php:1045
5	Joomla\CMS\Form\FormField->renderField()	JROOT/layouts/joomla/edit/fieldset.php:43
6	include()	JROOT/libraries/src/Layout/FileLayout.php:128
7	Joomla\CMS\Layout\FileLayout->render()	JROOT/libraries/src/Layout/LayoutHelper.php:76
8	Joomla\CMS\Layout\LayoutHelper::render()	JROOT/layouts/joomla/edit/params.php:170
9	include()	JROOT/libraries/src/Layout/FileLayout.php:128
10	Joomla\CMS\Layout\FileLayout->render()	JROOT/libraries/src/Layout/LayoutHelper.php:76
11	Joomla\CMS\Layout\LayoutHelper::render()	JROOT/administrator/components/com_templates/tmpl/style/edit.php:97
12	include()	JROOT/libraries/src/MVC/View/HtmlView.php:416
13	Joomla\CMS\MVC\View\HtmlView->loadTemplate()	JROOT/libraries/src/MVC/View/HtmlView.php:204
14	Joomla\CMS\MVC\View\HtmlView->display()	JROOT/administrator/components/com_templates/src/View/Style/HtmlView.php:86
15	Joomla\Component\Templates\Administrator\View\Style\HtmlView->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:697
16	Joomla\CMS\MVC\Controller\BaseController->display()	JROOT/administrator/components/com_templates/src/Controller/DisplayController.php:68
17	Joomla\Component\Templates\Administrator\Controller\DisplayController->display()	JROOT/libraries/src/MVC/Controller/BaseController.php:730
18	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
19	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()	JROOT/libraries/src/Component/ComponentHelper.php:361
20	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/AdministratorApplication.php:150
21	Joomla\CMS\Application\AdministratorApplication->dispatch()	JROOT/libraries/src/Application/AdministratorApplication.php:195
22	Joomla\CMS\Application\AdministratorApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:306
23	Joomla\CMS\Application\CMSApplication->execute()	JROOT/administrator/includes/app.php:58
24	require_once()	JROOT/administrator/index.php:32

**Comment by dgrammatiko** [comment]
What is inside your joomla.assets.json?

**Comment by masonboswell** [comment]
There was an error in tmeplateDetails.xml.  This can be closed.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41940">issues.joomla.org/tracker/joomla-cms/41940</a>.</sub>

**Comment by richard67** [comment]
Thanks for reporting back. Closing as not a core issue.
