### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by biochama1** [joomla/joomla-cms#41950]
### Steps to reproduce the issue
Hello, 
My website https://www.1.biochama.com is not oppening. Appears just a blank page. Can you check Whats happening please. 
Thank you.

**Comment by richard67** [comment]
This repository here is for bug reports. For support questions you should use the support forum https://forum.joomla.org/ .

Without any information provided by you about what has been changed before it stopped to work, e.g. if an update has caused this, and about which Joomla version it is, nobody can help.

**Comment by alikon** [comment]
as already reported here https://github.com/joomla/joomla-websites/issues/1924 and 

here https://github.com/joomla/joomla-websites/issues/1924#issuecomment-1737310339

i'm closing this
