### ISSUE TITLE
[5.0] Dark Mode: Actions dropdown on hover

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#41954]
Text should be white to match the dropdowns under Filter Options on hover.

![dark-actions-dropdown](https://github.com/joomla/joomla-cms/assets/368084/18ea26fe-f512-4022-96ff-7339aaee675f)

![dark-status-dropdown](https://github.com/joomla/joomla-cms/assets/368084/e7f051dd-101d-4156-ab28-5a824e5b0e75)

**Comment by wilsonge** [comment]
![image](https://github.com/joomla/joomla-cms/assets/1986000/a83a7a58-b41a-4b5a-a9cb-b1079f91c3b9)

The status dropdowns are pretty browser specific :)

**Comment by wilsonge** [comment]
This sets a color - but no guarentee that it exactly matches the other dropdowns because as i say i think the selects are chosen by the browser https://github.com/joomla/joomla-cms/pull/42004
