### ISSUE TITLE
[5.0] Installation - select dropdown icon missing

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#41961]
### Steps to reproduce the issue

- Clone `5.0-dev`
- Open installation page

### Actual result

> 404 Not found - installation/template/images/select-bg-dark.svg

![image](https://github.com/joomla/joomla-cms/assets/2019801/ae79c513-9808-4415-a9ce-36253497b3f1)

**Comment by wilsonge** [comment]
Someone needs to copy the select dark image in from the administrator template here https://github.com/joomla/joomla-cms/tree/5.0-dev/build/media_source/templates/administrator/atum/images to https://github.com/joomla/joomla-cms/tree/5.0-dev/installation/template/images

**Comment by andycodes3** [comment]
Hey ! pls assign me this issue

**Comment by wilsonge** [comment]
We don't assign issues in this repo but please feel free to make a pull request
