### ISSUE TITLE
Install From Web - Clear button always disabled

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#41966]
### Steps to reproduce the issue

1. Go to administrator/index.php?option=com_installer&view=install
2. Navigate to the "Install From Web" tab
3. Type something in the "Search" box
4. Press `Enter` or click the search button

### Expected result

Text remains in the input box and "Clear" button becomes enabled

### Actual result

Text is emptied from the input and "Clear" button is still disabled.
It's always disabled, so can never be used.

**Comment by brianteeman** [comment]
Confirmed

**Comment by brianteeman** [comment]
Sorry - just realised that this bug is in code in the other repo https://github.com/joomla/install-from-web-server

**Comment by Hackwar** [comment]
I created a copy of this issue in the right repo and mentioned you guys. Since this is the wrong repo for this, I'm closing this issue.
