### ISSUE TITLE
[5.0] Dark mode - Field error colour contrast

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#41962]
### Steps to reproduce the issue

1. Open the installation page in dark mode
2. Trigger an error on one of the input fields

### Actual result

The red contrast does not need the necessary accessibility standards

![image](https://github.com/joomla/joomla-cms/assets/2019801/c8b3d743-3117-4c31-bcd2-623819d08996)

**Comment by wilsonge** [comment]
Fix https://github.com/joomla/joomla-cms/pull/42005
