### ISSUE TITLE
[5.0] Dark Mode - Install From Web hover

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#41964]
### Steps to reproduce the issue

1. Go to `administrator/index.php?option=com_installer&view=install`
2. Navigate to the "Install From Web" tab
3. Hover over any extension

### Actual result

![image](https://github.com/joomla/joomla-cms/assets/2019801/dbe7b4e3-eafb-4faf-b20b-4db1683c4acd)

**Comment by wilsonge** [comment]
Fix https://github.com/joomla/joomla-cms/pull/42003
