### ISSUE TITLE
TinyMce changes the structure of the code. Cannot turn that off.

### ISSUE THREAD

**Issue by niosme** [joomla/joomla-cms#41972]
### Steps to reproduce the issue
e.g. a valid html code which is

`
<a href="https://www.google.com">
    <img src="pic_trulli.jpg" alt="Trulli" width="500" height="333">
    <div class="content">
        <div class="title">Title</div>
        <div class="subtitle">Subtitle</div>
    </div>
</a>
`
### Expected result

The same as the above without any changes

### Actual result

Tiny Mce manipulates it. There is no selection to stop it from doing it in plugin but tinymce offers that in the initialization of it to not manipulate the things we type inside.Also the above is a valid html5 structure.

The result we get is

`<p ><a href=" https://www.google.com"> <img src="pic_trulli.jpg" alt="Trulli" width="500" height="333" / >< /a>< /p>
< div class="content">
    < div class="title">Title</div>
    < div class="subtitle">Subtitle</div>
< /div>`

Added some spaces cause it breaks down here.Even the tinymce closes the a tag before it should close which is wrong structure.Shouldn't be an option to prevent thoses modifications on tinymce or initialize it in a better way?

### System information (as much as possible)

Without even saving the article or module. 

### Additional comments

Also in url if we just use just the '/' it turns it into the domain we have at the moment which will make a problem when we will transfer it. Its not handled by the joomla which turns it into your domain in the frontend.The tinymce before saving the module or article manipulates our structure and data which doesnt allow do custom things which are acceptable from html5.

**Comment by niosme** [comment]
Actual Result 

`<p><a href="https://www.google.com"> <img src="pic_trulli.jpg" alt="Trulli" width="500" height="333" /></a></p>
<div class="content">
    <div class="title">Title</div>
    <div class="subtitle">Subtitle</div>
</div>`

**Comment by brianteeman** [comment]
This is resolved in tinymce 6 which is included in Joomla 5 which should be released next month.

**Comment by niosme** [comment]
Woah! Nice news to hear.
So we can wait to be fixed in Joomla 5. Thanks for that information.

**Comment by richard67** [comment]
Closing as already fixed in Joomla 5 by using TinyMCE 6. Joomla 5 will be released in a few weeks, so not soooooo long to wait.
