### ISSUE TITLE
[5.0] Dark Mode: Usability issue  -  Template Editor

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#41979]
### Steps to reproduce the issue

1. Install J5.0.0 Beta3 using Dark mode
2.  Navigate to the template editor
3. Try to edit some CSS

### Expected result
Possible

### Actual result
Not possible (white font on white background)

![Screenshot 2023-09-28 at 13-04-02 Templates Customise (Cassiopeia) - Nick Dautrich - Administration](https://github.com/joomla/joomla-cms/assets/7933215/6b44a32a-6a94-4627-89ac-c8537e441fda)

### System information (as much as possible)
J 5.0.0 Beta3
Windows 10 Dark mode
Firefox dark mode

### Additional comments
Close, if it's already known

**Comment by GASOLINE** [comment]
How set it to light mode?

**Comment by werefkin** [comment]
> How set admin (atum) template to light mode?

that would be a nice feature. I don't like the dark mode in the form it is now. My solution for now is to use Dark reader extension, it makes the colors readable and possible to use css editor.
