### ISSUE TITLE
[5.0] Dark Mode: Usability issue  -  Template Overrides

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#41978]
### Steps to reproduce the issue
1. Install J5.0.0 Beta3 using Dark mode
2. Navigate to template overrides

### Expected result
Good-looking list of overrides

### Actual result
Barely readable list of overrides (dark blue font on black background)

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/fb6a13e6-a82a-4365-8052-abaff35a173d)

### System information (as much as possible)
J 5.0.0 Beta3
Template Skylar_J4 from Joomla51
Windows 10 Dark mode
Firefox dark mode

### Additional comments
Close, if it's already known

**Comment by wilsonge** [comment]
I think this one should be addressed by this PR https://github.com/joomla/joomla-cms/pull/41925

**Comment by alikon** [comment]
closing as we have a pr to test https://github.com/joomla/joomla-cms/pull/41925
