### ISSUE TITLE
[5.x] Uninstall a 'file' type extension

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#41999]
### Steps to reproduce the issue

Uninstall a 'file' type extension such as a language pack

### Expected result
Uninstalled correctly

### Actual result
Error

![image](https://github.com/joomla/joomla-cms/assets/17835460/876f2b3a-b691-40c6-be5a-a181037342e8)

### System information (as much as possible)

Joomla 5.0 Beta 3

**Comment by Fedik** [comment]
It is fixed in 4.4-dev https://github.com/joomla/joomla-cms/blob/2c0296b082caf41ab625a9a9d6743721b0a0afbc/libraries/src/Installer/Adapter/FileAdapter.php#L219
Will be in next 5.0 after upmerge

**Comment by joeforjoomla** [comment]
Yes i confirm that it works.
