### ISSUE TITLE
select user with ajax in com_content

### ISSUE THREAD

**Issue by JoomlaBelarus** [joomla/joomla-cms#41991]
### Is your feature request related to a problem? Please describe.
Is it possible to make selection user in Publishing  -field Created By in the sa,e way as we select tag in article 
![image](https://github.com/joomla/joomla-cms/assets/111335878/b3ec9b24-69b3-4509-aa3a-b9257c4391a8)
![image](https://github.com/joomla/joomla-cms/assets/111335878/9888d399-c07b-4226-b1ca-0196a3842625)

**Comment by Fedik** [comment]
The field have a dialog to select user, click that litle button to open it:
![Screenshot 2023-09-29_12-22-39](https://github.com/joomla/joomla-cms/assets/1568198/0d5af424-8eb9-4d0b-93fb-57de957f24e0)

The dialog allows to filter user not only by name but by other parameters.
