### ISSUE TITLE
[4.4] "Alias" for components, modules and templates.

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#41996]
### Is your feature request related to a problem? Please describe.

I would like to natively be able to use an "Alias" for components, modules and templates, although for components I think it is essential for security, practicality and comfort. It would be wonderful to have it in 4.4 or at least version 5.

### Additional context
Possibly also a great help for custom SEO

**Comment by dgrammatiko** [comment]
I guess I might answer this one.

> although for components I think it is essential for security

Concerning security Joomla 5 allows a public folder with almost the entirety of the site logic being hidden from the served directory. Check https://github.com/joomla/joomla-cms/pull/41446 or https://studio.youtube.com/video/PTQ12Qd47Pk/edit

> be able to use an "Alias" for components, modules and templates

This has 2 folds, the static assets and the PHP. For the static assets it would be very wasteful to do any aliasing as Joomla would have to copy a lot of files to multiple directories with practically no benefit (security through obscurity). For the PHP part you have to realise that the only part that actually exposes its name (only in non SEF mode) is the component in the URL (something like `index.php?option=com_content`) so modules and templates WON'T benefit from such a strategy!

> Possibly also a great help for custom SEO

Assuming that achieving better SEO is through SEF URLs then the alias makes zero sense (as the `option=com_content` is completely hidden in the URL (a SEF URL looks like `something/category/some-title`.

In sort, Joomla 5 comes with better security options (public folder) and aliasing most parts of the system would add more overhead and almost no real benefit.

**Comment by Stuartemk** [comment]
> I guess I might answer this one.
> 
> > although for components I think it is essential for security
> 
> Concerning security Joomla 5 allows a public folder with almost the entirety of the site logic being hidden from the served directory. Check #41446 or [demo](https://www.youtube.com/watch?v=PTQ12Qd47Pk)
> 
> > be able to use an "Alias" for components, modules and templates
> 
> This has 2 folds, the static assets and the PHP. For the static assets it would be very wasteful to do any aliasing as Joomla would have to copy a lot of files to multiple directories with practically no benefit (security through obscurity). For the PHP part you have to realise that the only part that actually exposes its name (only in non SEF mode) is the component in the URL (something like `index.php?option=com_content`) so modules and templates WON'T benefit from such a strategy!
> 
> > Possibly also a great help for custom SEO
> 
> Assuming that achieving better SEO is through SEF URLs then the alias makes zero sense (as the `option=com_content` is completely hidden in the URL (a SEF URL looks like `something/category/some-title`.
> 
> In sort, Joomla 5 comes with better security options (public folder) and aliasing most parts of the system would add more overhead and almost no real benefit.

Thanks for answering.

Regarding com_component, how feasible would it be to create an alias com_xxxxxx or better yet a simple alias of xxxxxx without com_ ?

Including third-party components since those who look for vulnerabilities the first thing they look at is the URL, for that reason I also thought about modules and templates.

**Comment by brianteeman** [comment]
This makes no sense at all. Aside from it not really making anything more secure changing the name of the component will have zero impact on the url

**Comment by Stuartemk** [comment]
> This makes no sense at all. Aside from it not really making anything more secure changing the name of the component will have zero impact on the url

Okay. However it is still for custom SEO, that is, it frees you from URL strings, suppose for example you share a URL that includes /com_jdownloads/ (it is horrible and unattractive) it can be any other just an example, I wish that instead I could put the alias of /downloads/ or /box/ or whatever aluas I want.

**Comment by brianteeman** [comment]
a URL should never contain the name of the component if it is using the joomla router and you have setup the component correctly.

**Comment by brianteeman** [comment]
@quy what information is required? This should just be closed

**Comment by Quy** [comment]
Just waiting for a final response from the OP before closing, but yours will do. Thanks.
