### ISSUE TITLE
[5.0] error pages language select

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#42016]
### Steps to reproduce the issue

check error pages after #41934 was merged
@HLeithner

### Expected result

language names should not be surrounded by quotes

### Actual result

language names (at the moment only en-GB) are surrounded by quotes
![image](https://github.com/joomla/joomla-cms/assets/66922325/3129cbf3-28de-4c66-9d48-ebce26561246)

### Additional comments
Maybe this happens because the lang files are processed by build tools (npm) and they do not support comments?
https://github.com/joomla/joomla-cms/blob/f8584d24a73386c45d87be92d378e1be74894aae/build/build-modules-js/error-pages.es6.js#L44

**Comment by HLeithner** [comment]
I created a revert PR #42019 thanks for the report closing this...
