### ISSUE TITLE
Is changelogurl working in Package Type ?

### ISSUE THREAD

**Issue by Mika17420** [joomla/joomla-cms#42029]
### Steps to reproduce the issue
betwwen : http://www.microbib.fr/maj/portail/pm7.xml
`		<element>pkg_microbib</element>
		<client>0</client>
		<type>package</type>
		<version>7.6.1</version>
		<changelogurl>http://microbib.fr/maj/portail/microbib_updates.xml</changelogurl>`

### Expected result

http://microbib.fr/maj/portail/microbib_updates.xml

**Comment by richard67** [comment]
@Mika17420 Could you check and report back if your issue is identical with this one #40056 ? Thanks in advance.

**Comment by Mika17420** [comment]
This is exactly my problem. Thanks for your feedback
