### ISSUE TITLE
[5.0] Dark Mode: empty items screen - learn more button - colour contrast

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#42025]
### Steps to reproduce the issue

![grafik](https://github.com/joomla/joomla-cms/assets/1035262/fe2a3f7e-424b-4fcf-99c7-d0fb13a2589b)

**Comment by Quy** [comment]
Fixed in #42010.

![42025](https://github.com/joomla/joomla-cms/assets/368084/0f894b2f-ccaf-4598-b15a-4d665cb915ee)

**Comment by alikon** [comment]
closing as there is a pr https://github.com/joomla/joomla-cms/pull/42010.
