### ISSUE TITLE
[5.0] upgrade kills seo

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42035]
### Steps to reproduce the issue
Install 4.4 and the blog sample data.
Check the source of the blog page and you will see various schema settings and values

![image](https://github.com/joomla/joomla-cms/assets/1296369/ae01c11f-79da-48e9-8fce-25b3baeb5cb7)

Upgrade to j5

### Expected result
At a minimum the existing schema settings are maintained

### Actual result
All schema settings are removed without any notification at all. Resulting in a site with changed schema (none at all) which will kill a sites seo

![image](https://github.com/joomla/joomla-cms/assets/1296369/09ca73a4-58f5-4128-850a-4582bc4a0e26)

### Additional comments
If you know the hidden secret you can discover that there is a plugin setting to enable the original schema data and prevent you from editing thousands of articles.

BUT if you check the plugin it shows that those hidden settings are enabled.

![image](https://github.com/joomla/joomla-cms/assets/1296369/c9b76464-0318-41ef-846d-1d590b1dc206)

Ah wait with the new plugin the rich data is now inside a json file in the head. Lets check that and see what data is in it.

![image](https://github.com/joomla/joomla-cms/assets/1296369/ba9713c2-31ff-4ed9-a9ce-c51e8ef9d5f0)

As you can see the data is not the same at all.

**Comment by richard67** [comment]
> Ah wait with the new plugin the rich data is now inside a json file in the head. Lets check that and see what data is in it.

>As you can see the data is not the same at all.

@brianteeman That's the structured data for the breadcrumbs, not for the blog or blog items.

**Comment by brianteeman** [comment]
@richard67 yes I know. The structured data for the blog items is completely gone. If you believe that structured data is important for SEO then, as the code stands, you will need to add structured data to every content item. And that is if you know about this on upgrade and not wait until your SEO is damaged

**Comment by brianteeman** [comment]
Looks like this bug was fixed once by @HLeithner in https://github.com/joomla/joomla-cms/pull/41250 but broken again later - perhaps with #41260

**Comment by brianteeman** [comment]
closed as we have a pr
