### ISSUE TITLE
[5.0] Hmmm,  classmap.php disappeared from /libraries/

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#42039]
I think that /libraries/classmap.php was very handy when updating components.
Well, I guess that it's related to the new Behaviour - Backward Compatibility plugin.

**Comment by HLeithner** [comment]
yes since all classes in this file are deprecated we moved the file to the b/c plugin folder. So this is expected behaviour

**Comment by ghazal** [comment]
Being a bit slow on the uptake, I found my beloved classmap list. 
Sorry.

**Comment by uglyeoin** [comment]
> /plugins/behaviour/compat/src/classmap/classmap.php

Thanks
