### ISSUE TITLE
[5.0] Disapearing captcha on update

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42033]
### Steps to reproduce the issue
Enable recaptcha on a joomla 4 site
Upgrade to joomla 5

### Expected result
recaptcha still present.

(of course I know the secret that it has been removed from j5)

So there should be at a minimum a post installation notice for those users that were using recaptcha that is has been removed. there site is no longer protected by any captcha and a recommendation on what they should do.

### Actual result
They think the upgrade has failed because the captcha they had setup and configured on j4 is no longer working

**Comment by brianteeman** [comment]
Follow up to the above report.

While global configuration now no longer shows any captcha available

![image](https://github.com/joomla/joomla-cms/assets/1296369/482580a2-48ab-46b4-bf9f-b97f12d9202e)

The individual components still state that the now removed captcha plugin is in use (but of course doesnt exist)

![image](https://github.com/joomla/joomla-cms/assets/1296369/fdaea2c1-811d-49d4-902f-4716313372c5)

![image](https://github.com/joomla/joomla-cms/assets/1296369/219a8620-0d41-4f13-8064-8020d660a895)

![image](https://github.com/joomla/joomla-cms/assets/1296369/e7d378cb-7983-4c27-a969-8025dfaae598)

**Comment by bayareajenn** [comment]
I've added to the upgrade from 4.4.x to 5.x planning and step by step doc (it's not on the docs wiki yet). I don't have answers on your very valid statements:

> So there should be at a minimum a post installation notice for those users that were using recaptcha that is has been removed. there site is no longer protected by any captcha and a recommendation on what they should do.

I have asked for answers though so I can add them to the doc. Thanks for bringing this up Brian.

**Comment by richard67** [comment]
On updated sites the invisible Google captcha should still be available, so a recommended solution for a postinstall message and the docs could be to enable that and use that.

**Comment by bayareajenn** [comment]
Yes, if I enable the Invisible reCAPTCHA plugin, it will display in the Default Captcha drop-down in Global Config. I'll add that to the doc. Thanks, @richard67.

**Comment by richard67** [comment]
> Yes, if I enable the Invisible reCAPTCHA plugin, it will display in the Default Captcha drop-down in Global Config. I'll add that to the doc. Thanks, @richard67.

@bayareajenn Welcome. But this applies only for updated sites. On new installations the core doesn’t ship any captcha plugin. But it still ships the possibility to use 3rd party captcha plugins.

**Comment by brianteeman** [comment]
The doc is great but we all know that only a certain percentage will read it.

**Comment by bayareajenn** [comment]
> The doc is great but we all know that only a certain percentage will read it.

I know. I can only control and do what I can do and have the ability to do.

**Comment by bayareajenn** [comment]
> > Yes, if I enable the Invisible reCAPTCHA plugin, it will display in the Default Captcha drop-down in Global Config. I'll add that to the doc. Thanks, @richard67.
> 
> @bayareajenn Welcome. But this applies only for updated sites. On new J5 installations the core doesn’t ship any captcha plugin. But it still ships the possibility to use 3rd party captcha plugins.

Ohhhhh, that's important information, Richard. I will make that note in the upgrade doc. I'm afraid I have to leave it to Harald and Benjamin and Marketing to address how to address communication on new installations. I don't know where that information should go. I do like the idea of a post installation message.

**Comment by TLWebdesign** [comment]
For a nice user experience there should be a notice before people upgrade if they are using the old captcha plugin. Then ideally there should be proper documentation about how to upgrade to the invisible Recaptcha version or how to find a different solution since we stopped shipping any alternative with J5, and not 2 line notice in the manual of Joomla that links to the generic extensions website.

**Comment by AMurray2016** [comment]
Suggestions for resolving this:

- Add a post-install message as already suggested
- Add some sort of pre-install notification (such as in the Preupdate check) advising users such plugins will be removed, which gives them the opportunity at that point to cancel the update if they want to continue using the Recaptcha at that point.
- And/or additional to the above, make the plugin available in the JED - **Official Extensions category** (as was done with Weblinks)

**Comment by brianteeman** [comment]
I have done what I can to raise this important issue and request that it is a release blocker. I can only do so much.

**Comment by brianteeman** [comment]
Closing as no one is interested

**Comment by Shemeam** [comment]
As a joomla user of 10 years+ the removal of the captcha plugin in J5 is very disconcerting.
Why was it removed, where can I download the same plugin to manually intall please (I have tried others and none of them seem to work).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42033">issues.joomla.org/tracker/joomla-cms/42033</a>.</sub>
