### ISSUE TITLE
[5.0] In dark mode, the number display is not legible

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#42045]
If I want to display the number of articles or categories in the administrator module, the number is shown in white on a light grey background. 
You need to change the colour of the number of items.
Thanks

<img width="1289" alt="Capture d’écran 2023-10-03 à 20 52 46" src="https://github.com/joomla/joomla-cms/assets/26197929/0e50b49f-5047-4ec4-a7d3-8d66c8ec4a78">

**Comment by brianteeman** [comment]
Please test #42050

**Comment by richard67** [comment]
Closing as having a pull request. Please test #42050 . Thanks in advance.
