### ISSUE TITLE
[5.0 RC] Plugin Behaviour - Backward Compatibility

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#42040]
As I admit I am of two minds about Behaviour - Backward Compatibility plugin being activated or not by default, I think it should be made more obvious somewhere.
For example, I was testing a component today in J5. While it's not activated by default, there was an error. But had it been activated by default, I'd never known about this error.
Just my two cents.

**Comment by HLeithner** [comment]
if you are a extension developer you should follow https://manual.joomla.org/migrations/44-50/ which has an entry for the b/c plugin.

For end users it's mostly not so important except they are interessted in better performance and then it will be mentioned in the upgrade procedure. We also plan/think about a quick icon which shows the status of the b/c plugin.
