### ISSUE TITLE
[4.3.4] Submenu items marked as public appear under the wrong menu item if it's parent has different access level

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#42041]
### Steps to reproduce the issue
Create three menu items;
1. Root level, public access
2. Root level, registered user access
3. Child of the registered user access item, public access
![image](https://github.com/joomla/joomla-cms/assets/32301627/bee82d93-d08c-4772-b0bb-6d673eaa2e09)

Open the frontend of the site, and observe the menu when not logged in

### Expected result
The only item that should be visible is the root level, public access item

### Actual result
The root level, public access item has a child item that belongs to another menu item.
![image](https://github.com/joomla/joomla-cms/assets/32301627/b09b9a96-bd06-4d11-bc5d-a7b38300c316)

### Additional comments
I am currently unable to test if this bug also exists in 4.4 or 5.0, but unless how menu items are fetched in those versions, I imagine the bug will occur there as well.

**Comment by brianteeman** [comment]
it has existed for many many years - at least back to 3.0 but probably earlier

**Comment by Chaosxmk** [comment]
So is this a "will not fix"?

**Comment by Quy** [comment]
Duplicate #40739

**Comment by Quy** [comment]
Closing as duplicate. Thanks.
