### ISSUE TITLE
Changing directory permissions to unwritable after synchronizing the folder with the site via Google Drive

### ISSUE THREAD

**Issue by a7951396** [joomla/joomla-cms#42048]
### Steps to reproduce the issue
I upload the folder with the Joomla website, which is located on an SSD in the Open Server Panel directory (I also tried Xampp, Wamp) via Google Drive to a remote drive so that there is a backup copy and synchronize these folders.

### Expected result
In the system settings of the Joomla admin panel on the Folder Permissions tab, permissions for all directories are set to writable.

### Actual result
In the system settings of the Joomla admin panel on the Folder Permissions tab, permissions for many directories are set to un writable. This happens immediately after the files finish downloading to the remote drive. 

### System information (as much as possible)
Windows 10 Education Edition
Version 22H2
Installation date 03/09/2022
OS build 19045.3448
Interoperability Windows Feature Experience Pack 1000.19044.1000.0

Processor AMD A8-6600K APU with Radeon(tm) HD Graphics 4.19 GHz
RAM 16.0 GB
Device code 0A0C0B67-D3AD-41EE-8D6D-5CEE330345A8
Product code 00328-00000-00000-AA343
System type 64-bit operating system, x64 processor
Pen and touch input Pen and touch input are not available for this monitor

### Additional comments

I also use the Google Drive desktop application. Disabling synchronization and completely deleting the Google Drive program and rebooting the system does not help return everything to the way it was.
![2023-10-05_09-34-29](https://github.com/joomla/joomla-cms/assets/86480184/8c4d5a8e-6335-4c8c-bf9b-d4139d23e4b9)
![2023-10-05_09-58-58](https://github.com/joomla/joomla-cms/assets/86480184/32e0f61c-2415-45f7-a6ce-3d69114b7fdd)

**Comment by gwstyles** [comment]
See https://forum.joomla.org/viewtopic.php?f=808&t=1004151<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42048">issues.joomla.org/tracker/joomla-cms/42048</a>.</sub>

**Comment by a7951396** [comment]
I created this topic and the problem is not solved in it

**Comment by brianteeman** [comment]
This is nothing to do with Joomla and all to do with how google drive works. There are plenty of documents online regarding running xampp etc with google drive

**Comment by richard67** [comment]
Closing as not a core issue. The issue tracker here is only for issues with Joomla CMS.

**Comment by a7951396** [comment]
> This is nothing to do with Joomla and all to do with how google drive works. There are plenty of documents online regarding running xampp etc with google drive

This topic is not about running XAMPP from Google drive, it's about the fact that after syncing a folder on my ssd drive with a remote folder on Google drive, something happens to the cms files on my local drive, after which the permissions become unwritten, and disabling synchronization and/or deleting the Google drive program and the reboot does not return the permissions back to the writable ones, I have to reinstall the cms completely.

**Comment by brianteeman** [comment]
When you do the sync it is changing the permissions on the files. Removing the sync and/or removing google drive does not change the permissions. You will need to do that yourself in windows. No need to reinstall anything. This is NOTHING to do with joomla!!

Google is your friend for this - an example is
https://www.uwec.edu/kb/article/drives-establishing-windows-file-and-folder-level-permissions/

**Comment by a7951396** [comment]
> When you do the sync it is changing the permissions on the files. Removing the sync and/or removing google drive does not change the permissions. You will need to do that yourself in windows. No need to reinstall anything. This is NOTHING to do with joomla!!
> 
> Google is your friend for this - an example is https://www.uwec.edu/kb/article/drives-establishing-windows-file-and-folder-level-permissions/

I have done everything that is written in this article more than once, including changing the owner of the folders, but it does not help.

**Comment by brianteeman** [comment]
Sorry no idea then - it is nothing to do with joomla - my expertise on other things is restricted

**Comment by a7951396** [comment]
I do not know what exactly the problem is here - in my windows, in Google Drive or in Joomla, or in general in everything at once, if possible, play it on your PC, it won't take long. I just won't use Google drive for Joomla.

**Comment by brianteeman** [comment]
I know for a fact that it is not joomla - I have better things to do with my free time

**Comment by a7951396** [comment]
this message is not just for you

**Comment by brianteeman** [comment]
the answers are out there you just have to think what google drive is for (**sharing**) and then you will hopefully understand

https://www.google.com/search?q=file+permissions+change+in+windows+when+shared+with+google+drive&oq=file+permissions+change+in+windows+when+shared+with+goo&gs_lcrp=EgZjaHJvbWUqBwgBECEYoAEyBggAEEUYOTIHCAEQIRigATIHCAIQIRigATIHCAMQIRigATIHCAQQIRigATIHCAUQIRigAdIBCTE3Njc2ajBqNKgCALACAA&sourceid=chrome&ie=UTF-8

**Comment by a7951396** [comment]
It would be so simple, I wouldn't create a theme here, I know how to use Google. Writing files to Google drive does not change access rights, at least in the file properties the permission does not change, I checked.

**Comment by a7951396** [comment]
Google Drive tech support told me that they have no right to test third-party software.

**Comment by richard67** [comment]
Joomla does not change the permissions of all files and folders at runtime, it only fixes wrong filesystem permissions of the files and folders of a 3rd party extension when installing that extension. It might be that permissions are fixed when making a new installation of Joomla (not sure now), so that might be the reason why it helps to make a new installation, but it does not change them during normal operation, and so Joomla definitely can’t be the reason for your problem.

So again: Please stop trying to get a solution here. Here is the place for issues with Joomla, not for supporting hosting questions or such things.

**Comment by a7951396** [comment]
ок
