### ISSUE TITLE
[5.0] Calendar missing svg

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42052]
### Steps to reproduce the issue
Open a calendar field (light or dark) and check the console. You will see a 404 for the image used for the dropdown arrow as shown in the image below

It should look similar to

![image](https://github.com/joomla/joomla-cms/assets/1296369/0363c3f6-9541-4943-8377-2271b87746b7)

Instead it looks like
![image](https://github.com/joomla/joomla-cms/assets/1296369/86923fd0-190b-485b-8312-4dbb161de8ce)

This is a bug introduced by @wilsonge in #41743

`https://j5.test/media/system/css/images/select-bg.svg 404 (Not Found)`

Should be 
`https://j5.test/media/system/images/select-bg.svg`

**Comment by dgrammatiko** [comment]
https://github.com/joomla/joomla-cms/pull/42060

**Comment by alikon** [comment]
please test #42060
