### ISSUE TITLE
[5.0] Dark Mode: Menu Assignment

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#42055]
![dark-menu-assignment](https://github.com/joomla/joomla-cms/assets/368084/467a72ae-c2f2-48f7-a372-a5391a7f2c0b)

![light-menu-assignment](https://github.com/joomla/joomla-cms/assets/368084/8f3b8527-e369-4a96-bd01-9ddd5ee0bfa2)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #42057 . Thanks in advance.
