### ISSUE TITLE
[5.0] Uncaught TypeError: e.editors is undefined

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#42056]
![mail-templates](https://github.com/joomla/joomla-cms/assets/368084/b0a36b25-0efa-4088-8d8c-11379df32463)

### Steps to reproduce the issue
Edit a mail template.
Insert a tag.
See browser console.

### Additional comments
Not an issue in v4.4.

**Comment by richard67** [comment]
Looks as if conditional chaining could also be helpful here ... ping @dgrammatiko .

**Comment by dgrammatiko** [comment]
I’ll have a look in a bit, unless @Fedik could patch it

**Comment by Fedik** [comment]
It looks like the script missing `editors` dependency

**Comment by dgrammatiko** [comment]
@Fedik you were right, https://github.com/joomla/joomla-cms/pull/42058

**Comment by richard67** [comment]
Closing as having a pull request. Please test #42058 . Thanks in advance.

**Comment by dgrammatiko** [comment]
@Fedik kinda irrelevant but could we skip the console.warn on the .min.js and only have it in the .js (debug)? I'm talking about this:
![Screenshot 2023-10-05 at 16 33 23](https://github.com/joomla/joomla-cms/assets/3889375/fb198e26-fbf5-44d0-8582-cf3c052b64ee)

**Comment by Fedik** [comment]
Can skip, but I did not wanted to bother with it ;)
