### ISSUE TITLE
[5.0] Call to undefined method Joomla\CMS\Form\Field\UserField::getCurrentUser()

### ISSUE THREAD

**Issue by skurvish** [joomla/joomla-cms#42063]
### Steps to reproduce the issue

Install 5.0 standalone, nothing else. Open the contacts in the admin side. Click the plus to create a new contact.

### Expected result

New contact form opens.

### Actual result

Call to undefined method Joomla\CMS\Form\Field\UserField::getCurrentUser()

### System information (as much as possible)

J5.0.0-rc2-dev-Development-Full_package
PHP 8.2 on Ubuntu 22.04.3 LTS

### Additional comments
![Screenshot from 2023-10-05 15-05-12](https://github.com/joomla/joomla-cms/assets/8654397/2124466a-1b0a-4810-8206-936113e33d60)

**Comment by alikon** [comment]
https://github.com/joomla/joomla-cms/blob/dba7bdd8596d853f09392c102ede3f646669628e/libraries/src/Form/Field/UserField.php#L82

there is no more static  call

**Comment by Fedik** [comment]
I cannot reproduce it on latest changes 5.0-dev branch.
I can create the contact wiithout the error.

**Comment by skurvish** [comment]
Intreresting. Let me start over again and see if it is replicatable.

**Comment by skurvish** [comment]
Started over and am now not getting the error. No idea what happened the first time. Closing.
