### ISSUE TITLE
Dialog modal with 0 height when uninstalling extensions in Safari

### ISSUE THREAD

**Issue by mk-webdev** [joomla/joomla-cms#42065]
### Steps to reproduce the issue
Use Safari when trying to uninstall any extension.

### Expected result
A dialog opens with buttons to confirm deletion.

### Actual result
Just the border of the dialog appears and renders the whole site unclickable since the dialog is technically open. Manually setting the height in CSS directly on the dialog helps.

### System information (as much as possible)
Joomla 5.0.0 RC, Safari V16.6 on MacOS Ventura 13.5.2

### Additional comments
Seems to be a simple CSS issue:
![Bildschirmfoto 2023-10-05 um 21 20 27](https://github.com/joomla/joomla-cms/assets/53147450/02c34488-c0df-454b-8c08-472603bc6155)
May be the same on other options using a dialog modal, but I don't know where else it is used.

**Comment by richard67** [comment]
A new installation of 5.0.0 RC? Or updated from a previous version?

**Comment by brianteeman** [comment]
Confirmed with that old version of safari

![image](https://github.com/joomla/joomla-cms/assets/1296369/44caa9a1-fd1c-4781-8558-5c245e6d5cad)

**Comment by Fedik** [comment]
What is wrong with safari?
It says https://caniuse.com/mdn-css_properties_height_fit-content `height: fit-content` is supported since 2015

**Comment by Fedik** [comment]
I think I have found a fix, will do PR sometime later

**Comment by mk-webdev** [comment]
> A new installation of 5.0.0 RC? Or updated from a previous version?

Updated from the latest beta

**Comment by mk-webdev** [comment]
> Confirmed with that old version of safari
> 
> ![image](https://user-images.githubusercontent.com/1296369/273030762-44caa9a1-fd1c-4781-8558-5c245e6d5cad.png)

Issue remains after updating to the latest version (Safari 17.0, MacOS Sonoma 14.0)

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/42079
