### ISSUE TITLE
[5.0] Dark Mode: Manage Folders/New File buttons

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#42069]
System > Site Templates
Click `Cassiopeia Details and Files`.
Click `Manage Folders` button.
See vertical dark lines.
Click `New File` button.
See vertical dark lines.

![dark-manage-folders](https://github.com/joomla/joomla-cms/assets/368084/f68e8367-fc5a-4eb9-8b92-97486d9d1ac1)

**Comment by brianteeman** [comment]
Please test #42057 its the same issue so the same fix
