### ISSUE TITLE
Ensure latest bootstrap version

### ISSUE THREAD

**Issue by 1337180** [joomla/joomla-cms#42068]
### Steps to reproduce the issue
Check the version of bootstrap.

### Expected result
Update to x.x.2 -> 5.3.2

**Comment by brianteeman** [comment]
Joomla 5 which will ship in a few weeks included bootstrap 5.3.2 - it is not always possible to update i,,ediately as there may be breaking changes

**Comment by Fedik** [comment]
As @brianteeman wrote, Joomla 5 will include latest bootstrap 5.3.2.

I closing here.
