### ISSUE TITLE
MS SQL: Menu Item SQL Statements Missing Values for Non-NULL Fields

### ISSUE THREAD

**Issue by adrianfso** [joomla/joomla-cms#4207]
#### Steps to reproduce the issue
Adding a new menu item to the Main Menu using MS-SQL Server and Windows Server 2008 with IIS 7.5.

#### Expected result
A new menu item is created.

#### Actual result
An error which prevents the menu items from being created.

Msg 515, Level 16, State 2, Line 1: Cannot insert the value NULL into column 'path', table '#__menu'; column does not allow nulls. INSERT fails. The statement has been terminated.

#### System information (as much as possible)
IIS 7.5 / Joomla 3.3.5 / Windows Server 2008 R2

#### Additional comments
Link to the original report on the previous tracker page: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=31459&start=0

**Comment by waader** [comment]
This is still a problem in mssql which basically renders mssql unusable for use in combination with joomla. I suggest a practical solution for the 3.x series and a makeover of the database schema - as suggested at another place by @alikon - for 4.x. Otherwise this deadlock situation will continue forever.

**Comment by muckypuddle** [comment]
Did this get any further? Only today came across a need to use SQL Server and hit the NOT NULL issue. I like @waader suggestion - practical solution for J3.X, and a rethink for 4.X.

**Comment by mahagr** [comment]
Looks like someone ran the same issue while installing Gantry5 to MSSQL. MySQL is all good.

I'm keeping the issue in Gantry5 open for now; I'd rather to fix it in here, but as most of us, I'm also lacking a proper environment (and knowledge) to test it out.

Which way we should go for: adding the default values in JTable or fixing the database fields?

**Comment by wilsonge** [comment]
It depends on the logical thing. For example if the data is a json field it makes sense to set a default of an empty json object in the table class. If it's an optional field that isn't always populated you fix the database fields to be not null and you take it on a case by case basis

**Comment by roland-d** [comment]
Hello @adrianfso 

Thank you for your contribution.

The last comment here was on 5th June. Can you create a pull request for this issue?

If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4207">issues.joomla.org/joomla-cms/4207</a>.</sub>

**Comment by roland-d** [comment]
@adrianfso I see you already created a pull request. Thanks, I will close this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4207">issues.joomla.org/joomla-cms/4207</a>.</sub>
