### ISSUE TITLE
[5.0] Dark Mode: Cron Expression

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#42077]
### Steps to reproduce the issue
Edit a task.
Select `Cron Expression` under `Execution Rule` dropdown.

![dark-cron-match](https://github.com/joomla/joomla-cms/assets/368084/1edbdc7d-dc29-4e04-a8e8-e7e2c1874ad2)

**Comment by brianteeman** [comment]
please test #42078

**Comment by Quy** [comment]
Thank you!
