### ISSUE TITLE
[5.0] alerts dark mode

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42084]
![image](https://github.com/joomla/joomla-cms/assets/1296369/12b1d22b-ca15-4574-ac28-841ab90ea88d)

Would it not be better for the dark mode to be something like the following example

![image](https://github.com/joomla/joomla-cms/assets/1296369/118ada85-582e-4d53-93f1-9d3eddabbbe7)

@wilsonge @HLeithner

**Comment by brianteeman** [comment]
(updated with correct image)

**Comment by HLeithner** [comment]
can be done in pr #42010 please check with design by @coolcat-creations and @MacJoom for the pr

At the moment I would like to only merge really broken stuff anymore into 5.0.0

**Comment by coolcat-creations** [comment]
Its done already in the draft don't know if @MacJoom will implement in the PR or should I do it?

**Comment by MacJoom** [comment]
I will do it my PR

**Comment by brianteeman** [comment]
That pr is still broken

**Comment by code-inhub** [comment]
So is this issue closed?
