### ISSUE TITLE
[5.0] Associations: Layout default not found

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#42087]
### Steps to reproduce the issue
Install German.
Install Multilingual Sample Data.
Edit an article.
Click Associations button.

### Actual result
![associations-target](https://github.com/joomla/joomla-cms/assets/368084/650ac7c8-2446-4fc2-bcdf-a572a9840a23)

### Additional comments
Not an issue in v4.4

**Comment by richard67** [comment]
Possibly caused by PR #40462 ?

**Comment by richard67** [comment]
I have that error on the edit view of the article at the right side of the associations side-by-side view. There is no target language selected. As soon as I select a target language, the error disappears and the article edit view at the right side is ok.

**Comment by richard67** [comment]
Next issue: The "Clear" button at the right side of the side-by-side view doesn't do anything, regardless if I have used the "Change Target" button before or not.

**Comment by richard67** [comment]
Next idea for a possible cause: PR #40462 .

**Comment by richard67** [comment]
The network analysis in my browser's developer tools show an internal server error for the GET request to this URL: `https://www.joomla-50-dev.vmubu01.vmnet2.local/administrator/index.php?option=com_content&view=article&extension=com_content&tmpl=component&task=article.article-en-gb&id=1`

**Comment by richard67** [comment]
It seems the `&task=article.article-en-gb` is the problem.

When selecting the right target language, the GET request goes to
`https://www.joomla-50-dev.vmubu01.vmnet2.local/administrator/index.php?option=com_content&view=article&extension=com_content&tmpl=component&task=article.edit&id=1`

**Comment by dgrammatiko** [comment]
@Fedik are you willing to work on this one or should I give it a go?

**Comment by Fedik** [comment]
I have found where it comes from,
Please test https://github.com/joomla/joomla-cms/pull/42096
