### ISSUE TITLE
[5.0] Documentation 404 for setting up local env

### ISSUE THREAD

**Issue by code-inhub** [joomla/joomla-cms#42086]
### Steps to reproduce the issue
1. Go to README.md and further to -> section:  [How to get a working installation from the source](https://github.com/joomla/joomla-cms#how-to-get-a-working-installation-from-the-source)
2. It is written there : "For detailed instructions please visit [https://docs.joomla.org/Special:MyLanguage/J5.x:Setting_Up_Your_Local_Environment](https://docs.joomla.org/J5.x:Setting_Up_Your_Local_Environment)"
It is not found.

**Comment by brianteeman** [comment]
#I have created the help page so this has been resolved and can be closed

**Comment by alikon** [comment]
thanks
