### ISSUE TITLE
Client Side URL validation fails despite of correct URL

### ISSUE THREAD

**Issue by magicmonty** [joomla/joomla-cms#42093]
### Steps to reproduce the issue

I have a form with the following field:

```xml
<field name="saleslink" label="COM_MAGICCAL_GIGVIEW_SALESLINK" type="url" validate="url" scheme="http,https" class="validate-url" />
```

I fill the field with the following URL

https://25935.reservix.de/tickets-tisch-theater-show-n-6-in-dresden-im-feldschloesschen-stammhaus-saal-hamburg-2-og-am-4-10-2023/e1934310

### Expected result

Tthe form should be saveable without problems

### Actual result

The client side Validation kicks in despite the fact, that the URI is perfectly valid

### System information (as much as possible)

PHP 8.2.11
Joomla-Version: Joomla! 4.3.4 Stable [ Bora ] 22-August-2023 16:00 GMT
DB: 10.4.31-MariaDB

### Additional comments

This worked fine in Version 4.0.4. The issue appeared after an upgrade to 4.3.4

**Comment by brianteeman** [comment]
> The client side Validation kicks in despite the fact, that the URI is perfectly valid

and says what?

**Comment by Quy** [comment]
Closing due to no response.
