### ISSUE TITLE
[5.0] Dark mode - configuration user options

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#42094]
### Steps to reproduce the issue

The submenu color on hover should be white

![grafik](https://github.com/joomla/joomla-cms/assets/1035262/6eac36fb-32bf-4cd5-84a9-09af12213a76)

**Comment by brianteeman** [comment]
Can not replicate

![image](https://github.com/joomla/joomla-cms/assets/1296369/6158dd81-d639-426a-a2d1-2f61f7fb766e)

**Comment by chmst** [comment]
Your screen is different, see the background right. Will do a fresh build ad check again.

**Comment by brianteeman** [comment]
Thats because you are not testing 5.0 but instead the possible pr for a future version #42080 which is very broken

**Comment by Quy** [comment]
Closing as this is an issue with PR #42010.
