### ISSUE TITLE
If an SVG image is selected in list view, then the height and width values are zero

### ISSUE THREAD

**Issue by QuotesUK** [joomla/joomla-cms#42101]
### Steps to reproduce the issue
Follows on from #39543 and #39538
https://github.com/joomla/joomla-cms/issues/39543
https://github.com/joomla/joomla-cms/issues/39538

Select an SVG image from media list view

### Expected result
Width and height will be correctly set

### Actual result
Width and height is set to zero

### System information (as much as possible)
Joomla 4.3.4
PHP 8.1

### Additional comments
Works correct when SVG image is selected from media thumbnail view

**Comment by dgrammatiko** [comment]
@dgrammatiko reminder
