### ISSUE TITLE
Add option for Linked Category in the "Articles - Category" site module

### ISSUE THREAD

**Issue by QuotesUK** [joomla/joomla-cms#42113]
### Is your feature request related to a problem? Please describe.
In the "Articles - Category" site module there is an existing option to gives links to article titles. However there isn’t a corresponding one for the category. This results in nested lists of linked article titles under plain text category names.

There is an option to enable category display. However this adds the category name in brackets after every article title. This category text appears in linked format with no option for plain text.

Existing options:

```
Plain Text Category
- Plain Text or Linked Article Title (Optional Linked Category)
- Plain Text or Linked Article Title (Optional Linked Category)
- Plain Text or Linked Article Title (Optional Linked Category)
```

<img width="1120" alt="Screenshot" src="https://github.com/joomla/joomla-cms/assets/3391399/7f17a4ca-e4ab-416a-a71c-0e57c5afa1d8">

### Describe the solution you'd like
Add a new display option - Linked Category
a) Allow the option to toggle the grouped category headings from plain text to linked
b) Allow the option to display categories in brackets with or without links

```
Plain Text or Linked Category
- Plain Text or Linked Article Title (Optional Plain Text or Linked Category)
- Plain Text or Linked Article Title (Optional Plain Text or Linked Category)
```

### Additional context
In my opinion the existing option for adding linked categories bloats the list unnecessarily. There is no need to repeat the category name in brackets after an article title when it could appear once as the heading. My main interest is in the simpler option A.

This is what I would like to achieve:
```

Linked Category
- Linked Article Title
- Linked Article Title
- Linked Article Title
```

**Comment by QuotesUK** [comment]
A template override is the only way to achieve this at the moment. That is why I have suggested an update to the module options. Clean output of a nested list with or without links on titles and categories ought to be a simple starting point but it isn’t catered for. The bracketed option for category links after every title is bloated.

**Comment by rdeutz** [comment]
I am closing this for two reasons, it is a very specific use case and it can be done with an overwrite. 

Thanks for bringing this up.
