### ISSUE TITLE
Webinstaller - 5.0.0-rc2 - Not able to select any database type

### ISSUE THREAD

**Issue by j-stahlhut** [joomla/joomla-cms#42115]
Joomla Installer Joomla! 5.0.0-rc2
### Steps to reproduce the issue
Frees install - Under Database Configuration
No items under database type:

### Expected result
At least MySQLi

### Actual result
None

### System information (as much as possible)
Debian GNU/Linux 10 (buster)
Apache/2.4.38 (Debian)
PHP 8.2.11 

### Additional comments
Have tried with both English and Danish language 

![Joomla_install_5 0 0-rc2](https://github.com/joomla/joomla-cms/assets/78488381/e752a4c3-bcbf-4ec4-9259-d7e87c329b9c)

**Comment by tkuschel** [comment]
similar to #41849

**Comment by brianteeman** [comment]
What **exact** version of mysql is running?

**Comment by j-stahlhut** [comment]
mariadb  Ver 15.1 Distrib 10.3.39-MariaDB, for debian-linux-gnu (x86_64)
I guess I miss the sql client when I upgraded from PHP ver 7.4
I have used Joomla ver. 4, but it also failed when I upgraded the PHP.

**Comment by brianteeman** [comment]
have you enabled the mysql extension in php

The fact that you are not being presented with any database options suggests that you have not

**Comment by j-stahlhut** [comment]
Bingo.
Thank you for pointing in the right direction.
