### ISSUE TITLE
setting option for display custom field

### ISSUE THREAD

**Issue by reilldesign** [joomla/joomla-cms#42110]
### Is your feature request related to a problem? Please describe.

There should be the option to determine whether and where the field is displayed: category blog view, article view or both. In many cases, a display in the category blog view is disturbing and undesirable.

### Describe the solution you'd like

A possibility to determine the display via dropdown. The default value could be both as is currently the case.

### Additional context

I am not sure if it is the same as issue #38758.

**Comment by rdeutz** [comment]
I think it is very close to #38758, if you think something is missing there please comment on the other issue.
