### ISSUE TITLE
[5.0] Unreadable CSS file in dark mode

### ISSUE THREAD

**Issue by Magnytu2** [joomla/joomla-cms#42112]
When you switch to dark mode, CSS files are unreadable. Only in dark mode. I think this is due to the editor. Joomla! 5 RC2

<img width="1621" alt="Capture d’écran 2023-10-10 à 18 31 31" src="https://github.com/joomla/joomla-cms/assets/26197929/20eae0c9-8479-4e31-86ec-c2e35813a91f">

**Comment by Quy** [comment]
Duplicate #41979 #41801. Thanks for reporting.
