### ISSUE TITLE
[4.3.4 to 5.0] Deprecated: SimpleXMLElement::addAttribute()

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#42122]
### Steps to reproduce the issue

Enable Maximum error reporting.
Enable System - Language Code.
Enable System - Language Filter.
Install German language.
Install Blog Sample Data.
Edit a category that has language All.
Click Associations button.

### Actual result
```
Deprecated: SimpleXMLElement::addAttribute(): Passing null to parameter #2 ($value) of type string is deprecated in \administrator\components\com_categories\src\Model\CategoryModel.php on line 483

Deprecated: SimpleXMLElement::addAttribute(): Passing null to parameter #2 ($value) of type string is deprecated in \administrator\components\com_categories\src\Model\CategoryModel.php on line 483

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in \administrator\components\com_categories\src\View\Category\HtmlView.php on line 149
```

![add-attribute](https://github.com/joomla/joomla-cms/assets/368084/3f55bf96-2415-4ab9-8dab-9cb1cac4a8f3)

### System information (as much as possible)
From v4.3.4 to v5.0

**Comment by richard67** [comment]
Closing as duplicate report. See #30603 .
