### ISSUE TITLE
There needs to be an option to disable dark mode in J5 Atum

### ISSUE THREAD

**Issue by bebetteraperson** [joomla/joomla-cms#42134]
After testing J5 and seeing there's no way to disable Dark mode other than in my OS settings, I find this to be a very large problem. I've found a components that aren't dark-mode friendly yet, including Akeeba backup. Expecting all developers to go back and redesign their products is not only asking too much, but most won't. This is a simple design issue that can be fixed by a plugin that can turn this feature off imo. Please consider shipping this with the first release as I can already expect the backlash. Thanks all

**Comment by toby07801** [comment]
Absolutely! Please add an option either in global settings / admin template settings / or per-user settings to disable dark mode or set the preferred behaviour. (On / Off / Automatic)

I, like many, have Windows default set to always be dark, but that does not mean I want this to to be affecting websites I visit. There needs to be an override!

The Joomla interface looks rather horrific a the moment using dark mode...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42134">issues.joomla.org/tracker/joomla-cms/42134</a>.</sub>

**Comment by brianteeman** [comment]
interesting

**Comment by simbus82** [comment]
Is dark mode really not configurable? In fact I also couldn't find an option but I thought it was due to the "beta state" of the DM. I use Chrome in dark mode, but I could never use Joomla's dark mode (or other backends where writing or managing content is important). Lot's of applications and websites now gives the choice "On/Off/Auto" for Dark Mode (if it exists at a style level).

**Comment by GASOLINE** [comment]
> interesting

Sorry Brian,
It's not interesting. It's one more thing that makes me fall out of love with Joomla. Using Joomla since 2005 but lately I don't know what's happening. The migration to J4 was a nightmare and another change for my clients (the dark mode) is something they will question. It makes me look less professional.
There should ALWAYS be an option to choose dark/light mode. And the dark mode (that's off course personal) looks very aweful to me.
Hopefully it will be changed very soon. I'm not willing to update clients at the moment.

**Comment by Fedik** [comment]
> I also couldn't find an option 

It in your OS configuration.

In general.
It seems to me that people misunderstood the difference between "dark mode" and "dark theme" or not fully understand, when they enable "dark mode" in their OS. Additionally whole "dark mode" trending only make everything more confusing.

Joomla added "dark mode" to follow your OS preferences. There no way to overide `@media (prefers-color-scheme: dark)` Browser behavior.

**Comment by cod3blox** [comment]
It could be made an optional decision by putting @media (prefers-color-scheme: dark) rules in a seperate css file, which is only included when mayba a "Include Dark Mode" switch is enabled in the Atum template configuration.

At least now many of the external components are not ready for this mode. It renders parts of components unreadable (black fonts on dark backgrounds etc.).
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42134">issues.joomla.org/tracker/joomla-cms/42134</a>.</sub>

**Comment by simbus82** [comment]
> > I also couldn't find an option
> 
> It in your OS configuration.
> 
> In general. It seems to me that people misunderstood the difference between "dark mode" and "dark theme" or not fully understand, when they enable "dark mode" in their OS. Additionally whole "dark mode" trending only make everything more confusing.
> 
> Joomla added "dark mode" to follow your OS preferences. There no way to overide `@media (prefers-color-scheme: dark)` Browser behavior.

I have Windows 11 set in dark mode, and Chrome with a dark theme (desktop chrome doesn't have the dark mode). With these settings, Facebook, Instagram, X, etc., automatically switch to a dark mode. However, lot's of "modern" website has the option to let me choose, and I have selected the light mode despite my OS and browser settings. 

Facebook
![image](https://github.com/joomla/joomla-cms/assets/1375730/f006ccd0-640e-4223-97b1-54635b22051f)

X - Twitter
![image](https://github.com/joomla/joomla-cms/assets/1375730/9c9aee27-bf5f-4e29-a69d-de42e705f3a8)

Instagram
![image](https://github.com/joomla/joomla-cms/assets/1375730/c848732c-89fb-4a24-ac4f-804d3dcc78f6)

October CMS
![image](https://github.com/joomla/joomla-cms/assets/1375730/e5cd825c-4021-4cfb-a2dd-139db809b074)

**Comment by hikashop-nicolas** [comment]
I was also surprised that there was no option to be able to change this. Abidding by the OS/browser behavior by default is nice, but providing the option to divert from it if necessary seems like a good idea.

**Comment by Fedik** [comment]
You guys probably need to look for OS dark theme, not dark mode :wink: 

> It could be made an optional decision by putting media (prefers-color-scheme: dark) rules in a seperate css file,

That can work

**Comment by simbus82** [comment]
> You guys probably need to look for OS dark theme, not dark mode 😉

The world is full of behavioral varieties, those who do marketing and develop products know this well.
Certain things are globally established. We have brought you some global examples.

> That can work

Yep! It remains to be understood whether it is a function of the Joomla backoffice or specific to the template.

**Comment by dgrammatiko** [comment]
> There no way to overide @media (prefers-color-scheme: dark) Browser behavior.

@Fedik actually that's not exactly true. I'm doing that (without extra CSS files) with Muta: https://muta.dgrammatiko.dev (which I offered to the project but probably rejected [tbh nobody even answered])

**Comment by Feenders** [comment]
The Autum theme is based on Bootstrap 5. Indeed, it uses the BS5 mechanism for auto dark mode.

Look at the switch in the upper right corner on the bootstrap site. 
https://getbootstrap.com/
It just changes the attribute of the root-html tag from data-bs-theme="dark" to data-bs-theme="light".

I am pretty sure it will only need some extra css to add this functionality to the template.

**The dark bootstrap admin theme looks awfully and irritating. I am pretty sure we will not update any site to joomla 5 if it stays like this.**

**Comment by GASOLINE** [comment]
> > There no way to overide @media (prefers-color-scheme: dark) Browser behavior.
> 
> @Fedik actually that's not exactly true. I'm doing that (without extra CSS files) with Muta: https://muta.dgrammatiko.dev (which I offered to the project but probably rejected [tbh nobody even answered])

Thanks, That's what we want. But I can't get it to display in light mode. See no option and no slider.

**Comment by dgrammatiko** [comment]
> But I can't get it to display in light mode. See no option and no slider.

This might help:
<img width="1722" alt="Screenshotx" src="https://github.com/joomla/joomla-cms/assets/3889375/795c92ee-27c8-4472-9278-a6bd4cb3904f">

**Comment by GASOLINE** [comment]
> > But I can't get it to display in light mode. See no option and no slider.
> 
> This might help: <img alt="Screenshotx" width="1722" src="https://user-images.githubusercontent.com/3889375/277161736-795c92ee-27c8-4472-9278-a6bd4cb3904f.png">

The issue was I need to log out and login again. Than I have that option otherwise I got an error I'm not allowed to see that page. Joomla is very annoyig lately. I use it for myself and clients since 2005 but I start to fall out of love.

**Comment by dgrammatiko** [comment]
> The issue was I need to log out and login again. Than I have that option otherwise I got an error I'm not allowed to see that page.

The part that you need to logout/login is a strange behaviour. The other one also annoys me...

**Comment by GASOLINE** [comment]
> > The issue was I need to log out and login again. Than I have that option otherwise I got an error I'm not allowed to see that page.
> 
> The part that you need to logout/login is a strange behaviour. The other one also annoys me...

I see that the logout/login issue was there also in J3 already. So something was/is going wrong there but not a major thing if you know what to do.

**Comment by dgrammatiko** [comment]
> So something was/is going wrong there but not a major thing if you know what to do.

Do you mind opening an issue with the steps and the expected/actual result?
Thanks

**Comment by GASOLINE** [comment]
> > So something was/is going wrong there but not a major thing if you know what to do.
> 
> Do you mind opening an issue with the steps and the expected/actual result? Thanks

It's not an issue with your template, I also have this on other Joomla 5 sites with standard templates only.

![image](https://github.com/joomla/joomla-cms/assets/958515/5eb5257f-8996-4932-8d72-43402d1d8637)

**Comment by it-basixs** [comment]
Hello.

You can use these instructions to use a button to change the dark mode.
Ihr könnt diese Anleitung nutzen, um eine Schaltfläche zum Umstellen des Darkmode zu verwenden.

[Your text to link here...](https://it-networks.de/dev-blog/tutorial-joomla-5-dark-mode-switcher-modul-erstellen-backend "Darkmode Switch")

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42134">issues.joomla.org/tracker/joomla-cms/42134</a>.</sub>

**Comment by Feenders** [comment]
Thank you. The solution from it-basixs is easy, small and works like a flaw.

Maybe you should make a pull request.

**But anyway, Joomla5 is not yet an option for productive use.**
The compatibility plugin makes it clear. Joomla is under such heavy development that even the core components are not compatible with changes.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42134">issues.joomla.org/tracker/joomla-cms/42134</a>.</sub>

**Comment by brianteeman** [comment]
> The compatibility plugin makes it clear. Joomla is under such heavy development that even the core components are not compatible with changes.

Really? Thats news to me!

**Comment by chmst** [comment]
> The compatibility plugin makes it clear. Joomla is under such heavy development that even the core components are not compatible with changes.

Which one?

**Comment by brianteeman** [comment]
I have live sites running without that plugin

**Comment by fgsw** [comment]
Maybe @Feenders means this (happens after disable plugin Behaviour - Backward Compatibility):

![Untitled1](https://github.com/joomla/joomla-cms/assets/147295380/f0c74a05-d5e8-442b-a0c6-2edad668a064)

Its a site without 3rd party extension, test on J5.0.0 and J5.0.1.

**Comment by alikon** [comment]
if you can detail step by step how to reproduce it, maybe better to open a new proper issue
... this sounds like a dark mode issue not a plugin Behaviour - Backward Compatibility issue
my 0.02€

**Comment by brianteeman** [comment]
The class JPlugin does NOT exist anywhere in Joomla 5. So the only way it can be present and produce the error is by having an installed extension

**Comment by alikon** [comment]
so did you mean that somethings has not been reported from  the pre-update check ?
cause i've tryed to reproduce it , without success, with some extensions but probably  with not a  reproducible one;
 that's why i'm asking for step by step info

**Comment by fgsw** [comment]
@brianteeman Its true, stack say it is the cloudpanel by CloudAccess:

![Untitled](https://github.com/joomla/joomla-cms/assets/147295380/3b6ef1ef-0283-4e1a-a879-085098dd1288)

I wasn't aware that this plugin is installed as i started the site via https://launch.joomla.org/.

**Comment by jjnxpct** [comment]
Back to the dark mode switch: I tested the custom module solution to be able to swicht from dark to light mode. This is a nice solution, for now. I do hope there will be a more permanent fix (added option) for this in Joomla. I browsed through some issues and I think there something brewing? #42221
