### ISSUE TITLE
J 4.3.4 Batch Process button missing in Admin Menu

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#42132]
### Steps to reproduce the issue

When I try to use the batch process in Admin menu there is no "process" button:
<img width="789" alt="grafik" src="https://github.com/joomla/joomla-cms/assets/828371/a864935b-fdac-48e9-b3b6-c6c236b38870">

### Expected result
Process Button

### Actual result
No Process Button

### System information (as much as possible)
J 4.3.4, Backend, logged in as Super User

**Comment by brianteeman** [comment]
Can not replicate on 4.3.4, 4.4rc, 5.0rc

![image](https://github.com/joomla/joomla-cms/assets/1296369/f7ef59fa-0e71-493d-86c9-bbee88b2670c)

**Comment by brianteeman** [comment]
Sorry missed that part of your report.

This is a known bug in 4.3.4 and fixed in 4.4+

![image](https://github.com/joomla/joomla-cms/assets/1296369/01025164-4d02-4371-a9ed-594064435ff0)

**Comment by coolcat-creations** [comment]
Alright, thank you!

**Comment by brianteeman** [comment]
thought it had been fixed originall in a much earlier version https://github.com/joomla/joomla-cms/pull/36762

**Comment by coolcat-creations** [comment]
seems it came back :-) Should it be reopened then?

**Comment by brianteeman** [comment]
no as my screenshot was from 4.4
