### ISSUE TITLE
[5.0] Only two available languages

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42141]
Joomla 5.0 is scheduled for release tomorrow (17th) is it really correct that there are only two lmaguages available?

https://update.joomla.org/language/translationlist_5.xml

![image](https://github.com/joomla/joomla-cms/assets/1296369/9153b8a9-9605-4dc9-9d3e-f6ac2b33d03f)

Checking further on the downloads site I can see that many more language packs are available for joomla 5

https://downloads.joomla.org/language-packs/translations-joomla5

@tecpromotion @HLeithner

**Comment by HLeithner** [comment]
No the language packs are note available, the categories for each language we have in 4 has been created but they are empty till the responsible language maintainer adds the language for joomla 5

**Comment by brianteeman** [comment]
Sorry - didnt check the downloads to see if there were any files in the categories.

Would it not make sense to offer the j4 versions for now. Not a great experience otherwise for new installs

**Comment by HLeithner** [comment]
will check what we can do

**Comment by joomlaphp** [comment]
I added language packs for 5 versions to the language directory. Also the icon is not visible.

`https://downloads.joomla.org/media/com_ars/environments/ars-joomla5x.png`

![1](https://github.com/joomla/joomla-cms/assets/423588/9d242930-f456-4c4c-b6d5-39cff4ddc7fb)

**Comment by HLeithner** [comment]
that's the wrong repository / issue to report this, never the less the issue is known and a image should be available shortly

**Comment by brianteeman** [comment]
Closing - too late now
