### ISSUE TITLE
Reflected XSS All Clients - com_categories

### ISSUE THREAD

**Issue by rbeins** [joomla/joomla-cms#42143]
### Steps to reproduce the issue
Removed for security reasons

**Comment by richard67** [comment]
@rbeins In addition to my previous comment, I don't see that the `$extensions` value somehow goes into the html output. It is only passed to the getAssociations method here https://github.com/joomla/joomla-cms/blob/5.0-dev/administrator/components/com_categories/src/Controller/AjaxController.php#L61 , and that method uses the md5 of the serialization of that value to create a query key here: https://github.com/joomla/joomla-cms/blob/5.0-dev/libraries/src/Language/Associations.php#L63 .

It is not passed to the html output and not saved in database, so I don't see how the described XSS should be possible.
