### ISSUE TITLE
SQL Injection - com_privacy

### ISSUE THREAD

**Issue by rbeins** [joomla/joomla-cms#42144]
Removed security report

**Comment by richard67** [comment]
@rbeins You have been told in your previous issue on how to report security issues, see the comment here: https://github.com/joomla/joomla-cms/issues/42143#issuecomment-1764915038 .

I repeat again here: Please check https://github.com/joomla/joomla-cms/security/policy how to report security issues using the [online form](https://developer.joomla.org/security/contact-the-team.html) . Thanks in advance.

**Comment by richard67** [comment]
The removed description has been forwarded to the security strike team. They will check and act accordingly. But in future please report security issues in the previously mentioned way and not here. Thanks.

**Comment by SniperSister** [comment]
For the record: the reported issue is a false positive.
