### ISSUE TITLE
Saving User Profile from the frontend, logs you out of the backend

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#42151]
### Steps to reproduce the issue

- Note: In Global Configuration -> System, "Shared Session" must be disabled to reproduce the issue
- Create a Menu Item of type "Users » Edit User Profile", call it "Edit Profile"
- Keep the backend open in a browser tab
- Open another tab, go to the frontend, click on the "Edit Profile" Menu Item 
- Simply save your profile from the frontend by pressing "Save"
- Go back to the backend tab, refresh. You've been logged out of the backend.
(on the other hand, you're still logged-in the frontend)

### Expected result

You should not be logged out of the backend just because you edited your profile. That makes no sense.

### Actual result

You are logged out from the backend by just editing your profile from the frontend.

### System information (as much as possible)

Can be reproduced on all Joomla 4.x versions, including 4.4.x, as well as the newest Joomla 5.x

**Comment by richard67** [comment]
Do you have "shared sessions" enabled in global configuration?

**Comment by AndySDH** [comment]
Shared Session is disabled.

I tested the issue with Shared Session enabled, and the issue didn't happen.

So I guess the issue is only **without** "Shared Session" enabled.

**Comment by fgsw** [comment]
Issue confirmed.

**Comment by alikon** [comment]
please test #42284
