### ISSUE TITLE
Joomla\CMS\Filesystem\Path::check() - Snooping out of bounds @ /webdata/public/images/

### ISSUE THREAD

**Issue by toddpage** [joomla/joomla-cms#42156]
### Steps to reproduce the issue

Upgraded to Joomla 4.3.4 from 3.x

Click on content in side menu then on media

get the following error

Joomla\CMS\Filesystem\Path::check() - Snooping out of bounds @ /webdata/public/images/

### Expected result

list and browse  /images directory

### Actual result

Blank

### System information (as much as possible)

LAMP 
php 7.4.33

images is a symbolic link to /webdata/public/images/

**Comment by Quy** [comment]
Duplicate #30616?

**Comment by Quy** [comment]
Closing as duplicate.
