### ISSUE TITLE
4.4.0 - Class "Joomla\Plugin\System\Skipto\Extension\Skipto" not found 

### ISSUE THREAD

**Issue by tbganesha1688** [joomla/joomla-cms#42165]
### Steps to reproduce the issue

Install Joomla! 4.4.0 Upgrade Package (.tar.gz)

### Expected result

Upgrading to 4.4.0 should be working fine

### Actual result

Got error message Class "Joomla\Plugin\System\Skipto\Extension\Skipto" not found both at backend and frontend

### System information (as much as possible)

AlmaLinux 8, PHP 8.1

### Additional comments

Upgrade from Joomla 4.3.4 to Joomla 4.4.0

**Comment by brianteeman** [comment]
> Install Joomla! 4.4.0 Upgrade Package (.tar.gz)

How have you performed the update? The update component only supports zip files

**Comment by richard67** [comment]
When you just unpack the tar.gz file without using the update component, then database updates and other things which have to run with the update will not run.

**Comment by tbganesha1688** [comment]
Please close this ticket. The issue has gone if I upgrade as @richard67 and @brianteeman tell me. Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42165">issues.joomla.org/tracker/joomla-cms/42165</a>.</sub>

**Comment by richard67** [comment]
> Please close this ticket. The issue has gone if I upgrade as @richard67 and @brianteeman tell me. Thank you.

@tbganesha1688 Am happy to read that. Thanks for reporting back.

Closing as not a core issue.
