### ISSUE TITLE
[4.4.0] Error message after update from 4.3.4

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#42161]
### Steps to reproduce the issue
When updating from J4.3.4 to J4.4.0, sometimes an error message regarding a missing class appears. The version info in the top bar still indicates 4.3.4. The error message offers to return to the dashboard, which works. After that, everything seems to be okay. The log file joomla_update.php doesn't show any error.
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/d2772092-9390-40c6-826a-b6b59703aaf2)

This happens only occasionally, not on all updates. 

### Expected result
After update, the message about the new version is displayed. You're supposed to go to the dashboard.

### Actual result
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/1d512ed1-795d-4ca0-8b7a-d7ce8eecdc46)

### System information (as much as possible)
Joomla 4.4
PHP 8.2.2
MySQL 8.0.33

**Comment by woluweb** [comment]
Delete the file administrator/cache/autoload_psr4.php

If that does not solve, then unzip the Updata package and again delete the file administrator/cache/autoload_psr4.php

Actually, see https://docs.joomla.org/J4.x:Fix_%22Reinstall_Joomla!_core_files%22_in_4.4.0_broke_Installation_and_backend_login

**Comment by dautrich** [comment]
@woluweb 
The update has been run without issues. The only nasty thing is the error message. After that, frontend and backend work without any issues.

**Comment by richard67** [comment]
So the message came only one time and after using the back to dashboard button all works without having to delete the autoloader file manually? If so, does the backend show the right version, or still the 4.3.4?

The class mentioned in the message belongs to the Backwards Compatibility plugin for J5, which is already installed on 4.4.0 but not doing anything, just for being present when later updating to to 5. No idea what could try to access this class in J4.4, except of the procedure which generates the autoloader file.

We might have to dig deeper to see what happens. Unfortunately I cannot reproduce the issue.

**Comment by dautrich** [comment]
@richard67 
> So the message came only one time and after using the back to dashboard button all works without having to delete the autoloader file manually? If so, does the backend show the right version, or still the 4.3.4?

The message come just once. After navigating to the dashboard, it shows the proper version 4.4.0. I didn't delete the autoloader file.
If a remember correctly, I saw this message two times when updating e site to 4.4.0; did that for about a dozen sites.

**Comment by richard67** [comment]
Maybe some kind of caching issue? @dautrich Do you have the PHP opcache extension enabled on these 2 sites?

**Comment by dautrich** [comment]
@richard67 

I never cared about opcache. System information tells me that Zend Opcache is up and running:

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/1cf47d64-6674-4de4-a921-fc0360d08f56)

All my websites are hosted by 1blu. So I assume that this cache is up and running for all my websites (I didn't check closer).

**Comment by richard67** [comment]
Yes, but it could be some kind of timing issue with that. Anyway that's just an idea and would be hard to reproduce.

**Comment by richard67** [comment]
The updater should invalidate the opcache for every modified and deleted file, so that should not be an issue, but who knows, maybe there is still something missing.

**Comment by dautrich** [comment]
Maybe it would be better not to invest too much time into this issue. 
Another idea: Why not add a sentence to the FAQ? Something like: 
“Some users have occasionally seen the following error message:  xxx. This shouldn't be seen as a serious error message and can be ignored.”

**Comment by richard67** [comment]
> Another idea: Why not add a sentence to the FAQ? Something like: “Some users have occasionally seen the following error message: xxx. This shouldn't be seen as a serious error message and can be ignored.”

Godd idea. @dautrich Can you do that? Or maybe release managers @laoneo @MacJoom ?

**Comment by dautrich** [comment]
@richard67  I don't have any rights on joomla.org

**Comment by dautrich** [comment]
Didn't happen on later updates anymore. No reproducible. Closed by the author.
