### ISSUE TITLE
Joomla Database missing, cannot repair

### ISSUE THREAD

**Issue by h4b4n3r0** [joomla/joomla-cms#42178]
### Steps to reproduce the issue
I am currently using Joomla 4.3.4 and did a hosted install via my hosting provider (they installed Joomla 4 for us).
My goal is to update to Joomla 4.4.

When navigating to "System -> Updates -> Joomla" it tells me that my Database structure is not running the latest version and I should fix it by navigating to "System -> Maintenance -> Database" and repair it.

![screen shot 2023-10-20 at 02 05 04](https://issues.joomla.org/uploads/1/3c5f77837f5273357b164faf301028ea.png)

However, when following this path, in the image the Joomla database is missing and I can only see the databases of two plugins. I "repaired" these two databases, however I cannot see the Joomla database nor repair it.

![screen shot 2023-10-20 at 02 05 04](https://issues.joomla.org/uploads/1/e626a754b0261ebd78b38388dbe67ac0.png)

### Expected result
The Joomla database should appear and one should be able to repair it.

### Actual result
The Joomla database is not visible and I cannot repair it.

### System information (as much as possible)
If you need more information let me know.

### Additional comments

When looking for the issue I found out, that this might be because some entries in the database missing:
https://issues.joomla.org/tracker/joomla-cms/38594

Our database entries currently look like this: 

![screen shot 2023-10-20 at 02 14 43](https://issues.joomla.org/uploads/1/25a85985d4bb1fd3978a7a4549f8e7aa.png)

![screen shot 2023-10-20 at 02 14 52](https://issues.joomla.org/uploads/1/145af112fecaf5fbfbaec5f9c4ec5f93.png)

I am happy to provide more information.
Thanks for helping out!
Kind regards
id3aFly

**Comment by brianteeman** [comment]
Your host didn't do the install correctly. But dont worry we can fix that.

You need to do exactly what is instructed in the issue you found.
Find the id for files_joomla and then add a record in __schemas

**Comment by richard67** [comment]
@Id3aFly Please do as @brianteeman suggested, follow the instructions in this comment https://github.com/joomla/joomla-cms/issues/38594#issuecomment-1227065736 in that issue and report back if that helps. Thanks in advance.

**Comment by Id3aFly** [comment]
It helped. Thanks a lot for the super quick support!
