### ISSUE TITLE
[4.4.0]cannot use passkey to login

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#42177]
### Steps to reproduce the issue
install joomla 4.4.0
try login with passkey option
### Expected result
successful login after entering correct pin
### Actual result
Login fails after correct pin entered with :
**Unknown column 'u.name' in 'field list'**
### System information (as much as possible)
php 8.2.4
mysql v5.7. (same problem with 8.1)
### Additional comments
Passkey option had been working with joomal 4.3.4 and works successfully with joomla V5.0

**Comment by richard67** [comment]
When you switch on debug and increase error reporting to maximum, do you get shown a stack trace? If yes, could you post a screenshot or a text copy here? Thanks in advance.

**Comment by jschmi102** [comment]
hi,
thanks for your hints. I did some testing and found that the causer was a bad (old) plugin. After cleanup problem disapeared.

**Comment by richard67** [comment]
@jschmi102 Thanks for checking and reporting back.
