### ISSUE TITLE
cli console update - untranslated string

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42170]
### Steps to reproduce the issue
Install a clean joomla 4.4 set the update channel to next and then from the cli perform an update to j5
` php .\cli\joomla.php core:update  `

### Expected result
Update completes and the update log has no untranslated strings

### Actual result
update completes with the following untranslated string
```
2023-10-18T20:25:33+00:00	INFO -	update	End of SQL updates.
2023-10-18T20:25:33+00:00	INFO -	update	COM_JOOMLAUPDATE_UPDATE_LOG_UNINSTALL_EXTENSIONS
2023-10-18T20:25:36+00:00	INFO -	update	Deleting removed files and folders.
```
### System information (as much as possible)

PHP 8.1.3 (cli)
mysql-8.0.30-winx64

**Comment by Fedik** [comment]
Interesting, the string is new in 5.0 and not for 4.4.
The updater executing script.php from 5.0, but language loaded before the execution, from 4.4.

Maybe it make sense to have update log untranslated at all, it could simplify a loot of things :)

**Comment by brianteeman** [comment]
going to close this as its such a rare case its not worth the time to fix
