### ISSUE TITLE
[4.x][5.x] Smart Search lang constants in result taxonomies

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#42176]
### Steps to reproduce the issue
1. Setup a Joomla site as multi-lingual.
2. In your Smart Search menu item, enable the "Result Taxonomy" setting (under Options tab).
3. Go to your front-end and perform a search.

### Expected result
Show the taxonomy information.

### Actual result
Show language constants.
![taxonomies](https://github.com/joomla/joomla-cms/assets/1838041/0841684c-3a5a-4729-8830-e67197f3f32a)

### System information (as much as possible)
In my tests happens both in J4.x and J5.x

### Additional comments
Found issue https://github.com/joomla/joomla-cms/issues/37229
Which is closed as fixed, but it is not the case, in my tests.

**Comment by Quy** [comment]
Confirmed. @Hackwar

**Comment by Hackwar** [comment]
Disable debug mode.

**Comment by HLeithner** [comment]
if the issue still exists after disabling debug mode please reopen the issue or post here again. thanks

**Comment by sakiss** [comment]
Indeed. Seems to happen only in debug mode.

**Comment by Hackwar** [comment]
Since Smart Search checks if the lang string exists and if not, falls back to a generalized string, it doesn't fall back when the debug mode is enabled, so that you can copy the key and create the fitting translation.
