### ISSUE TITLE
[5.0] Joomla Update Still Using old Default Text from 4.x

### ISSUE THREAD

**Issue by jweaver0312** [joomla/joomla-cms#42187]
### Steps to reproduce the issue
Log into administrator panel and go to Joomla update (System -> Update -> Joomla)

### Expected result
The text should say:

Currently no update available.
You are on the "Default" update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (5.x)

### Actual result
See attached screenshot
![screen shot 2023-10-20 at 22 10 04](https://issues.joomla.org/uploads/1/90fa288e7fd4f4cd1c5f67370d3bf653.png)

The text currently says:
Currently no update available.
You are on the "Default" update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (4.x)

**Comment by Quy** [comment]
You must be using an outdated language pack. This was updated in PR #41481.
