### ISSUE TITLE
cli create public folder

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42181]
### Steps to reproduce the issue
I couldnt find any docs so I am going by the instructions in the original pr

After installing joomla I then try to use the cli to create the public_folder

`$ php cli/joomla.php site:create-public-folder`

```
Create a public folder
======================

 Please enter the absolute path to the public folder:
 > /home/xxxxxxxxxxn/xxx.com/testcreatepublicfolder


In PublicFolderGeneratorHelper.php line 199:
                                                          
  Call to undefined function Joomla\CMS\Helper\symlink()  
                                                          

```

a folder /home/xxxxxxxxxxn/xxx.com/testcreatepublicfolder is created. it has two **empty** folders in it

/home/xxxxxxxxxxn/xxx.com/testcreatepublicfolder/administrator
/home/xxxxxxxxxxn/xxx.com/testcreatepublicfolder/api

### System information (as much as possible)
php81

**Comment by Fedik** [comment]
[Simplink](https://www.php.net/function.symlink) function is disabled on your server.

I think the CLI script should check availability of it, it may be disabled on many other servers.

**Comment by brianteeman** [comment]
Good catch
![image](https://github.com/joomla/joomla-cms/assets/1296369/0324ebdb-86d4-46e9-8a68-476005117fe5)

I tried on three servers with different providers and I see now it is disabed on all of them

**Comment by brianteeman** [comment]
and on the windows machine nothing is disabled and it still fails

**Comment by richard67** [comment]
Because on Windows symlinks are different and the symlink method only works on Unixoids?

**Comment by richard67** [comment]
https://www.php.net/manual/en/function.symlink.php .. should work on Windows, too, I just see.

**Comment by richard67** [comment]
Hmm, a comment there says:

> Symlinks on windows  are created by Symlink() which accept only absolute paths  but not relative paths .relative paths on windows are not supported for symlinks

**Comment by dgrammatiko** [comment]
> Symlinks on windows are created by Symlink() which accept only absolute paths but not relative paths

@richard67 the code is already converting the (possible) relative paths to absolute:
https://github.com/joomla/joomla-cms/blob/4c799de22c35981eb8373d3a7cfaa276b505275a/libraries/src/Helper/PublicFolderGeneratorHelper.php#L104

Maybe there's a need to use `DIRECTORY_SEPERATOR` instead of `/`, but not on windows so can't really test it

**Comment by Hackwar** [comment]
Windows requires admin privileges to create the symlink.

**Comment by brianteeman** [comment]
> Windows requires admin privileges to create the symlink.

Maybe it does but it still doesnt work on linux.

>   Call to undefined function Joomla\CMS\Helper\symlink()  

The actual problem is that symlink is disabled in php on the server and as of php 8.0 the error message does not indicate that the function is disabled but says it is undefined
Reference [php watch](https://php.watch/versions/8.0/disable_functions-redeclare)

As @Fedik says

> [Simlink](https://www.php.net/function.symlink) function is disabled on your server.
> 
> I think the CLI script should check availability of it, it may be disabled on many other servers.

**Comment by brianteeman** [comment]
See #42705
