### ISSUE TITLE
Joomla 5.0.0 - Class "Psr\Log\LogLevel" not found in symfony error-handler

### ISSUE THREAD

**Issue by conathan** [joomla/joomla-cms#42186]
### Steps to reproduce the issue
Extract the files from https://downloads.joomla.org/cms/joomla5/5-0-0/Joomla_5.0.0-Stable-Full_Package.tar.gz?format=gz , and setup database configuration.

### Expected result
example.com/installation to give the normal joomla install

### Actual result
Fatal error: Uncaught Error: Class "Psr\Log\LogLevel" not found in /misc/5/000/267/030/6/user/web/wordpress.ncoulson.com/joomla/libraries/vendor/symfony/error-handler/ErrorHandler.php:112

Stack trace:
#0 /misc/5/000/267/030/6/user/web/wordpress.ncoulson.com/joomla/libraries/bootstrap.php(57): Symfony\Component\ErrorHandler\ErrorHandler::register() 
#1 /misc/5/000/267/030/6/user/web/wordpress.ncoulson.com/joomla/installation/includes/framework.php(27): require_once('/misc/5/000/267...')
#2 /misc/5/000/267/030/6/user/web/wordpress.ncoulson.com/joomla/installation/includes/app.php(26): require_once('/misc/5/000/267...')
#3 /misc/5/000/267/030/6/user/web/wordpress.ncoulson.com/joomla/installation/index.php(32): require_once('/misc/5/000/267...')
#4 {main} thrown in /misc/5/000/267/030/6/user/web/wordpress.ncoulson.com/joomla/libraries/vendor/symfony/error-handler/ErrorHandler.php on line 112

### System information (as much as possible)
AlmaLinux 8.8 (Bravenet Web Hosting)
php 8.0, 8.1 and 8.2 - latest

### Additional comments
Tested on 8.1/8.2 at bravenet.com (technically 8.0 as well, which gave the "you need 8.1 minimum"

Reran the same tests with Joomla 4.3.4, no issues

**Comment by conathan** [comment]
Adding to this, our environment does have php-PsrLog installed, pulled in by composer.  (Remi's PHP Repositories).  Had someone reach out and advise this may be related.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42186">issues.joomla.org/tracker/joomla-cms/42186</a>.</sub>

**Comment by conathan** [comment]
Further testing, with composer and php-PsrLog removed, no change.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42186">issues.joomla.org/tracker/joomla-cms/42186</a>.</sub>

**Comment by conathan** [comment]
I was wondering how to take this further,  This is affecting our entire hosting environment for customers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42186">issues.joomla.org/tracker/joomla-cms/42186</a>.</sub>

**Comment by Fedik** [comment]
Check whether file `vendor/psr/log/src/LogLevel.php` exist, and it is not corrupted.
Also may be something with filesystem read-access.
I cannot think many other resons why the class cannot be found.

**Comment by conathan** [comment]
That turned out to be it.  We have a git repository that imports this for use as a one click installer.  .gitignore had log in it, (now changed to /log), that meant source/libraries/vendor/psr/log was not included.  Resolved.


Thank you,  (hrm, don't see a option to close the ticket from here, let's see)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42186">issues.joomla.org/tracker/joomla-cms/42186</a>.</sub>

**Comment by alikon** [comment]
thanks for reporting
