### ISSUE TITLE
Backward Compatibility Plugin - Which installed extensions use it?

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#42207]
### Is your feature request related to a problem? Please describe.

I would like to be able to see (after a J4 to J5 update) what installed extensions make use of the Backward Compatibility Plugin. This might save us some trial and error work (disable the plugin and see what happens...). That would also help us to determine the moment we can disable the BC plugin without any issues.

### Describe the solution you'd like

A list / log somewhere that can tells me / the site admin which plugins make use of the BC plugin.

### Additional context

I am not sure if this is possible at all (technically). or maybe its is possible already?

Maybe the update screen from 4 to 5 could also somehow tell us what extensions will be needing the plugin?

**Comment by web54** [comment]
I do agree with this request
My site is in j5 with compatibility plugin enabled
And I do not know exactly what are the extensions I have to update or delete to be uptodate with j5

**Comment by micker** [comment]
Interesting

**Comment by jjnxpct** [comment]
Maybe the 'actions' from the plugoin cam be logged (and viewed) somewhere so we can see what extensions were affected by the plugin.

**Comment by zero-24** [comment]
Hmm i do only see that this could be archived by an code scan. The problem is that even when we just find one line of b/c code which is only triggered a few times without the plugin this codeline would crash. An logging would only catch when the code itself is triggered while testing.
