### ISSUE TITLE
J5: Need to fix colors for Code Mirror in Dark mode

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#42201]
<img width="1403" alt="Снимок экрана 2023-10-22 в 18 58 47" src="https://github.com/joomla/joomla-cms/assets/3432048/b2bb0c95-08c5-4ead-9ebb-03261d99126c">
<img width="1820" alt="Снимок экрана 2023-10-22 в 19 16 51" src="https://github.com/joomla/joomla-cms/assets/3432048/66872066-1308-49f3-ac4b-6d93beba4cb3">

Joomla 5.0.0. Code Mirror is chosen.
See how it looks like in Dark mode. And there is no button to switch to Light mode.
But would be better to add special styles for Code Mirror making it compatible to dark mode.

**Comment by richard67** [comment]
Closing as duplicate report. See #42148 just a few rows below this one here.

**Comment by richard67** [comment]
… and #42134 for the switching off dark mode part.
