### ISSUE TITLE
[4.4.0] Get Article with Fields of type List over Webservices returns empty array

### ISSUE THREAD

**Issue by DonPedro34** [joomla/joomla-cms#42200]
### Steps to reproduce the issue

Add a new Field of type List to your Article. Select a value and save the article.

Get the Article over the Webservices API

GET /api/index.php/v1/content/articles/{{yourArticleId}}

### Expected result

"Fieldname": {
   "1": "1"
},

### Actual result

"Fieldname": [0]

### System information (as much as possible)

PHP Built On	Linux dd51504 5.4.0-164-generic #181-Ubuntu SMP Fri Sep 1 13:41:22 UTC 2023 x86_64
Database Type	mysql
Database Version	10.5.22-MariaDB-1:10.5.22+maria~ubu2004-log
Database Collation	utf8mb4_general_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	Yes
PHP Version	8.1.22
Web Server	Apache
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 4.4.0 Stable [ Pamoja ] 17-October-2023 16:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36

### Additional comments

This works in Release 4.3.4

**Comment by richard67** [comment]
@alikon Could you have a look on this issue? Thanks in advance.

**Comment by alikon** [comment]
please test #42206
