### ISSUE TITLE
[5.0] ConsoleApplication doesn't load Behaviour plugins

### ISSUE THREAD

**Issue by OctavianC** [joomla/joomla-cms#42210]
### Steps to reproduce the issue
- Upload this test plugin which uses deprecated code 
 [testplugin.zip](https://github.com/joomla/joomla-cms/files/13112893/testplugin.zip)
- Enable it:
 
![image](https://github.com/joomla/joomla-cms/assets/1422378/3a5ef420-1fb0-4727-af2e-3587bce9fe7b)

- Open the terminal and run:
`php cli/joomla.php`

### Expected result
![image](https://github.com/joomla/joomla-cms/assets/1422378/f826f515-b3c7-4f23-a247-415aee1f8579)

### Actual result
![image](https://github.com/joomla/joomla-cms/assets/1422378/030c1eb7-ea7e-49ac-b6c3-9ad2afb2571e)

### Additional comments
Seems the Behaviour - Backward Compatibility plugin isn't loaded in the ConsoleApplication.

**Comment by richard67** [comment]
Ping @HLeithner .

**Comment by HLeithner** [comment]
looks like a bug yes, also the console application should load the behavior plugins

**Comment by HLeithner** [comment]
btw. I think this issue also exists in 4.4?

**Comment by alikon** [comment]
only system and console are imported if i'm not wrong, form 4.0 iirc
https://github.com/joomla/joomla-cms/blob/4c799de22c35981eb8373d3a7cfaa276b505275a/libraries/src/Application/ConsoleApplication.php#L254-L256

**Comment by thefbi79** [comment]
It was I who reported this to RS Form. Same problem with Acymailing.

Never had any problems before Joomla 5, so with older versions it works perfectly, I use it on over 30 sites.

**Comment by OctavianC** [comment]
> btw. I think this issue also exists in 4.4?

Backward Compatibility plugin has no functionality in 4.4 and aliases are still loaded from libraries/classmap.php. This is an issue with 5.0.0 only.
I think I have a pull request for this.

**Comment by alikon** [comment]
please test #42217

**Comment by richard67** [comment]
> > btw. I think this issue also exists in 4.4?
> 
> Backward Compatibility plugin has no functionality in 4.4 and aliases are still loaded from libraries/classmap.php. This is an issue with 5.0.0 only. I think I have a pull request for this.

@OctavianC I think what @HLeithner meant was the general issue that behaviour plugins are not loaded by the ConsoleApplication in general, not particularly related to the BC plugin.

**Comment by richard67** [comment]
So the question is if that shall be fixed in 4.4-dev, too, or not. @HLeithner Could you clarify that?
