### ISSUE TITLE
[5.0] The names CustomFields are not translated into the alias name when saving.

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#42211]
### Steps to reproduce the issue
If you create a custom field for the material. We will indicate the name of the field not in English but in another language, even in German or in Russian. At the same time, we will not specify the alias of the field. When saving, the alias of the field will have the name "-1"

### Expected result
But the name should be translated in Latin letters.

### Actual result
the alias has the value "-1"

**Comment by HLeithner** [comment]
Is this issue new? Or is it the behavior the same  in 4.4 ?

**Comment by korenevskiy** [comment]
> Is this issue new? Or is it the behavior the same in 4.4 ?

There is NO such problem now (j4,j5). This problem was when testing J5 BETA.
Closing ISSUE
