### ISSUE TITLE
[4.4.0] update Weblinks package V4.3.1

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#42213]
### Steps to reproduce the issue
try to update weblinks package via joomla updater 
### Expected result
package is updated
### Actual result
Fails:
![screenshot](https://github.com/joomla/joomla-cms/assets/69053785/118705fe-de3d-414e-ad91-c50f2faf46be)

### System information (as much as possible)
Joomla v4.4.0 (and Joomla 5.0)
php 8.2

**Comment by richard67** [comment]
That’s an issue of Weblinks, not of the Joomls core. See this comment about how to fixing: https://github.com/joomla-extensions/weblinks/issues/539#issuecomment-1776908394

Closing as not a core issue.
