### ISSUE TITLE
Webservice api is leaving articles in checked-out status

### ISSUE THREAD

**Issue by oorzaak** [joomla/joomla-cms#42219]
### Steps to reproduce the issue
enable webservice api in Joomla 5 site and set up api access for a user 
set up a script on remote site for connection with api and updating articles using the api and user credentials
run script from remote site in order to update articles in Joomla 5 site 

### Expected result
the articles in J.5 site being updated and in not-checked out status as tested before in J.4 version of the same site

### Actual result
the articles being updated and in checked-out status

### System information (as much as possible)
J.5.0.0
php 8.1.14
10.4.27-MariaDB-cll-lve

**Comment by oorzaak** [comment]
Sorry, System info should be:
J.5.0.0
php 8.1.24
10.5.22-MariaDB <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42219">issues.joomla.org/tracker/joomla-cms/42219</a>.</sub>

**Comment by alikon** [comment]
unable to replicate

**Comment by oorzaak** [comment]
Thanks for taking a look at it. At the time that I wrote it, this issue was constistent. However, today I cannot replicate it anymore, either.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42219">issues.joomla.org/tracker/joomla-cms/42219</a>.</sub>
