### ISSUE TITLE
"Forgot your password" unable to send email

### ISSUE THREAD

**Issue by vicn1222** [joomla/joomla-cms#42222]
### Steps to reproduce the issue

Install Joomla as default. 
Global Configuration -> Server -> Mailer = "PHP Mail".

"Forgot your password" unable to send email.

### Expected result

Email should be sent

### Actual result

No email is sent

### System information (as much as possible)

Joomla 5.0
Red Hat RHEL 9

### Additional comments

The cause

In file libraries/src/Mail/MailerFactory.php, line 83

<PRE>
 if ($mailer->setFrom($mailfrom, MailHelper::cleanLine($fromname), false) === false) {
</PRE>

needs to be changed to

<PRE>
 if ($mailer->setFrom($mailfrom, MailHelper::cleanLine($fromname), true) === false) {
</PRE>

The php "mail" needs $additional_params = "-fsupport@mydomain.com"

<pre>
mail(
    string $to,
    string $subject,
    string $message,
    array|string $additional_headers = [],
    string $additional_params = ""
): bool
</pre>

**Comment by vicn1222** [comment]
Looking at the maillog, without the $additional_params = "-fsupport@mydomain.com", the sender email becomes


from=<apache@T140.localdomain>
<PRE>
Oct 26 14:47:52 T140 postfix/qmgr[1679]: 4A0FE803386F4: from=&lt;apache@T140.localdomain&gt;, size=957, nrcpt=1 (queue active)
</PRE>
The email is then rejected by gmail-smtp-in.l.google.com with message

<PRE>
This mail has been blocked because the sender is unauthenticated. 550-5.7.26 Gmail requires all senders to authenticate with either SPF or DKIM. 550-5.7.26  550-5.7.26  Authentication results: 550-5.7.26  DKIM = did not pass 550-5.7.26  SPF [t140.localdomain]
</PRE><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42222">issues.joomla.org/tracker/joomla-cms/42222</a>.</sub>

**Comment by chmst** [comment]
Closing as this is not a joomla core. https://support.google.com/mail/thread/210192174/how-to-authenticate-dkim-or-spf?hl=en 
Maybe you can ask for support on https://forum.joomla.org

**Comment by HLeithner** [comment]
As Christiane mentioned, this is not a Joomla issue, anyway please don't use php mail function, use smtp instead.

**Comment by pe7er** [comment]
> As Christiane mentioned, this is not a Joomla issue, anyway please don't use php mail function, use smtp instead.

The reason to use SMTP is that your SMTP server (if configured correctly) adds a DKIM signature to your outgoing emails.
Gmail requires all senders to authenticate with either SPF or DKIM.
The PHP mail and sendmail methods don't add a DKIM signature.
