### ISSUE TITLE
[4][5][bug] webservices: when patching Articles all the existing associated Tags are lost

### ISSUE THREAD

**Issue by woluweb** [joomla/joomla-cms#42229]
### Steps to reproduce the issue

Update/patch Article(s) using the Joomla WebServices (example of script: https://slides.woluweb.be/api/api.html#6-2-update-joomla-articles-with-the-api)

All the patched Articles are correctly updated... but they have lost all their associated Tags

### Expected result

Tags should not be deleted when patching articles with the Webservices.

(btw, is it already possible add or replace Tags using when Posting or Patching Articles with webservices? If so, how? Txs!)

**Comment by MacJoom** [comment]
I can confirm this bug - will work on it.
Imho it is not possible to add or replace tags in articles yet.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #42233 . Thanks in advance.
