### ISSUE TITLE
TinyMCE Setting linebreak with  doesn´t work

### ISSUE THREAD

**Issue by BPBlueprint** [joomla/joomla-cms#42224]
### Steps to reproduce the issue
1. Go to System > Plugins > "Editor - TinyMCE"
2. Set "New Line" to `<br>`-element (instead of `<p>`-Element)
3. Write some text and try to break the line with ENTER-key

### Expected result
get a linebreak with with `<br>` Element

### Actual result
linebreak with `<p>` Element

### System information (as much as possible)
Joomla 5.0.0.0, Windows 11, Firefox and Chrome 

### Additional comments
Doing Shift+Enter gives a `<br>`-Linebreak ... but for sure only pressing ENTER should make a `<br>`

**Comment by richard67** [comment]
@BPBlueprint I've allowed myself to edit the description of your issue and add tickmarks ` around the html elements because otherwise the html markup is not shown on GitHub.

**Comment by alikon** [comment]
please test https://github.com/joomla/joomla-cms/pull/42227
