### ISSUE TITLE
Editor - TinyMCE don't work

### ISSUE THREAD

**Issue by Darko-F** [joomla/joomla-cms#42226]
### Steps to reproduce the issue
Upgrade Joomla from 4.40 to Joomla 5

### Expected result
See Editor - TinyMCE bars when try to edit article

### Actual result
When try edit  Article get only a Article Text string.
Can't enter any text
After disable Editor - TinyMCE plugin code mirror editor works.

### System information (as much as possible)
PHP Version	8.1.13
Web Server	LiteSpeed
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 5.0.0 Stable [ Kuboresha ] 17-October-2023 16:00 GMT
Database Version	10.4.24-MariaDB-cll-lve-log

**Comment by Darko-F** [comment]
When try to edit article I get console error 

![screen shot 2023-10-27 at 09 14 51](https://issues.joomla.org/uploads/1/7dc0704b9b425dad5d5fe410ab7b6094.png) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42226">issues.joomla.org/tracker/joomla-cms/42226</a>.</sub>

**Comment by Darko-F** [comment]
![screen shot 2023-10-27 at 09 16 16](https://issues.joomla.org/uploads/1/5a45ef74c25208881c9f2f2fce4ee0f3.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42226">issues.joomla.org/tracker/joomla-cms/42226</a>.</sub>

**Comment by jeff-71** [comment]
Just do a hard browser refresh and it will be fine. Its a new version of tinymce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42226">issues.joomla.org/tracker/joomla-cms/42226</a>.</sub>

**Comment by Darko-F** [comment]
I did delete before all caches in Joomla and in browser, but only after I close and hard reset browser it start working.
Thank you sir.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42226">issues.joomla.org/tracker/joomla-cms/42226</a>.</sub>
