### ISSUE TITLE
TinyMCE Setting: using Headlines and more is possible, even the buttons are not activated

### ISSUE THREAD

**Issue by BPBlueprint** [joomla/joomla-cms#42225]
### Steps to reproduce the issue
Go to System > Plugins > "Editor - TinyMCE"
Remove buttons like "bold", "italic", "blockquote", "paragraph" (SAVE SETTINGS)
Go to article and enter some text. Mark some text in the editor

### Expected result
No chance to format the text with bold or italic or blockquote or paragraph

### Actual result
I get a pop-up toolbox with the possibility to use bold or italic or blockquote or paragraph

### System information (as much as possible)
Windows 11, Joomla 5.0.0, Firefox and Chrome

**Comment by brianteeman** [comment]
You have not disabled the ability to make something bold. You have just removed the button. The hotkeys still work for example.

To remove the _popup toolbox_ you need to disable the context menu
![image](https://github.com/joomla/joomla-cms/assets/1296369/675e5848-5918-497c-8464-ebf45190364c)

**Comment by BPBlueprint** [comment]
Hi Brian, thanks for your answer.
But look at my screenshot, Context Menu is disabled.![screen shot 2023-10-27 at 08 01 31](https://issues.joomla.org/uploads/1/fa83a8ce8d0e33284b2f00ad2b701ba7.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42225">issues.joomla.org/tracker/joomla-cms/42225</a>.</sub>

**Comment by brianteeman** [comment]
Sorry my mistake - it is quickbars and not context menu and we do not provide an option to disable that at this time. When I added it I was probably trying to add another option to an already crowded ui

**Comment by BPBlueprint** [comment]
Ok, thanks.
So means for me, looking for another editor-extension.

Maybe some day it will be added by Joomla!-core again, so that I donot need to install extra plugins.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42225">issues.joomla.org/tracker/joomla-cms/42225</a>.</sub>

**Comment by brianteeman** [comment]
It could be added to joomla but I would need a maintainers approval

**Comment by BPBlueprint** [comment]
I think I can do what I need with JCE extension, even I prefore not installing unnecessary extensions.
Thanks
