### ISSUE TITLE
[5.0] j+a get out of the code editor?

### ISSUE THREAD

**Issue by alejman2009** [joomla/joomla-cms#42235]
### Steps to reproduce the issue
1-Have as Deafult Editor TinyMCE
2-Access the editor to any article.
3-Open the extended menu with ...
4-Select the Source code+ option "<>"
5-write in the code "ja"

### Expected result

It writes "ja" in the code.

### Actual result

closes the Source code window witout saving.

### System information (as much as possible)

Joomla! packaged by Bitnami Debian GNU/Linux 11 (Bullseye)

### Additional comments

It look like this.

**Comment by Fedik** [comment]
`j + a` is "Save" shortcut
![Screenshot 2023-10-28_14-49-08](https://github.com/joomla/joomla-cms/assets/1568198/5be0d112-4a3f-45ab-87a3-e2d37c5e11cc)

**Comment by brianteeman** [comment]
it happens because the focus is not in the code editor when it opens

**Comment by Fedik** [comment]
> the focus is not in the code editor when it opens

It happens even with focus

**Comment by brianteeman** [comment]
sorry was looking on an old site. Confirming it happens all the time

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/42258
