### ISSUE TITLE
Formatting is lost in extensions

### ISSUE THREAD

**Issue by zino666** [joomla/joomla-cms#42231]
Hello,
I did my updates first to J. 4.4 and then to 5.0 - everything went smoothly.

Already with the update to 4.4 I noticed that I could no longer format download descriptions in Phoca, for example (H1, H2, etc.). I then updated to 5.0 but the error still persisted. I then got the update to Phoca Download 5.0.0 Beta from Phoca. But even now the error still exists.

Everything works - posts in Joomla, categories, ..... everything can be formatted, just not in extensions. There are also no error messages. After saving, the formatting is simply gone.

I tried different editors or changed the script handling, tried different PHP versions, tried different browsers, turned backwards compatibility off and on, repaired the database, cleared the cache,...

I just do not get any further.

Template: Cassiopeia

In the morning I worked on the site, then I updated to 4.4 and when I wanted to continue working the system no longer accepted my formatting.

Apart from the update, nothing has changed in the meantime, it definitely has something to do with the update. The question, however, is whether it has to do with the "code optimization" suggested by the update or with the "clean code"!?

**Comment by brianteeman** [comment]
The one thing you havent said is if you have contacted the developer of the extensions

**Comment by zino666** [comment]
Phoca offers another update but this doesn't work either.

I'm also currently observing the following: If you filter in extensions, you have to filter again after each save.

**Comment by brianteeman** [comment]
you didnt answer the question.

**Comment by PhocaCz** [comment]
Hi, in version 4.0.8 this should be OK, the problem was in filter="\Joomla\CMS\Component\ComponentHelper::filterText"

You can download the latest version here: https://www.phoca.cz/download/68-phoca-download/4-phoca-download-component

Jan

**Comment by ChristineWk** [comment]
> Hi, in version 4.0.8 this should be OK, the problem was in filter="\Joomla\CMS\Component\ComponentHelper::filterText"
> 
> You can download the latest version here: https://www.phoca.cz/download/68-phoca-download/4-phoca-download-component
> 
> Jan

Thank you Jan,
FYI: I suggested that to the TE yesterday in the German Joomla forum

**Comment by Quy** [comment]
Closing as not a core issue.
