### ISSUE TITLE
Bug mod_related_items in Joomla 4.4

### ISSUE THREAD

**Issue by nunoms00** [joomla/joomla-cms#42243]
### Steps to reproduce the issue

I upgraded to Joomla 4.4 and now the mod_related_items module appears in the categories and empty, using the card style. I only want it to appear in the article details.

### Expected result

Show the module only inside the article

### Actual result

The empty module appears, with the module title.

**Comment by brianteeman** [comment]
Confirmed. The rewrite of the module for Joomla 4 has introduced this bug.

In 4.3 if there were no related items then the module was not rendered. 
In 4.4 if there are no related items then the module is rendered

**Comment by alikon** [comment]
please test #42245
