### ISSUE TITLE
[5.0] CodeMirror Editor - missing syntax highlighting

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#42241]
### Steps to reproduce the issue
Open for example a PHP file in template file editor (with CodeMirror editor - this is default)

### Expected result
Syntax highlighting for different code parts like variables, operator, etc. should be displayed.

### Actual result
Syntax highlighting for different code parts like variables, operator, etc. is missing (in comparison to Joomla 4 version)

Joomla 5:
![codemirror](https://i.imgur.com/wQ2YLWW.png)

![codemirror](https://i.imgur.com/y2zSwu8.png)

Joomla 4
![codemirror](https://i.imgur.com/CiGHXAR.png)

![codemirror](https://i.imgur.com/rjQ4mEJ.png)

### System information (as much as possible)
Joomla 5

**Comment by brianteeman** [comment]
it is a different version of codemirror - not everything is the same

**Comment by HLeithner** [comment]
The new CodeMirror 6.0 php highlighter works different then the last one. It might or might not be expected please open an issue at https://github.com/codemirror/dev/issues
I'm closing this here because it's an upstream issue.

thanks for reporting
