### ISSUE TITLE
Joomla Sidebar module overlaps content  

### ISSUE THREAD

**Issue by DrJrO** [joomla/joomla-cms#42242]
Hey their, 

struggling since hours didn't found a solution. One of my local projects has the issue that the sidebar Module overlaps the content in the main if I minimalize the width of the window.

Tried out positions, z-index (what would if it would work not fix the problem I guess) and I didn't come to an solution.

Using Joomla 4 and Cassiopeia.

would be very thankful about help.

**Comment by brianteeman** [comment]
Please use the forum for support
