### ISSUE TITLE
[5] Contacts: Change linked user to '- No User-' fails

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#42255]
### Steps to reproduce the issue

1. Create a contact
2. select a linked user
3. select button '- No User-'.

### Expected result
No user is linked to the contact.

### Actual result
User stay linked.

### System information (as much as possible)

php: Linux lamp302.cloudaccess.net 3.10.0-962.3.2.lve1.5.81.el6h.x86_64 #1 SMP Wed May 31 12:07:35 UTC 2023 x86_64
dbserver: mysql
dbversion: 8.0.34-cll-lve
dbcollation: utf8mb4_0900_ai_ci
dbconnectioncollation: utf8mb4_0900_ai_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 8.1.24
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 5.0.0 Stable [ Kuboresha ] 17-October-2023 16:00 GMT
compatpluginenabled: true
compatpluginparameters: classes_aliases:"1", es5_assets:"1"
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0

**Comment by HLeithner** [comment]
I can confirm this, @Fedik could the new modal code be the reason?

**Comment by Fedik** [comment]
yeap

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/42256
