### ISSUE TITLE
Fatal error: Uncaught UnexpectedValueException: JIT on Windows is not currently supported in

### ISSUE THREAD

**Issue by dugz-1611** [joomla/joomla-cms#42268]
### Steps to reproduce the issue
Download Joomla
Extract files to joomla Xammp folder
Start up Xammp services
Go to localhost/joomla/

### Expected result
Should open the installer page for Joomla to enter user details

### Actual result
Throws an error:

{main} thrown in C:\Users\dugz1\XAMMP\htdocs\joomla\libraries\vendor\phpseclib\phpseclib\phpseclib\bootstrap.php on line 28

### System information (as much as possible)

Windows 11, Xammp 3.3.0

**Comment by heelc29** [comment]
Duplicated report https://github.com/joomla/joomla-cms/issues/42142

**Comment by Quy** [comment]
Please test PR #42190. Thanks.
