### ISSUE TITLE
Backend Menu - Dropdowns: white color on white backgroaund

### ISSUE THREAD

**Issue by heli63** [joomla/joomla-cms#42272]
### Steps to reproduce the issue

After Update to Joomla 4.4. all Dropdowns are not visible any more as the font-color is set to white and the background is white as well

### Expected result

black font-color

### Actual result
@media (prefers-color-scheme: dark)
.ph-topmenu-black ul.dropdown-menu li a {
    color: #fff;
}
in main.css:163

**Comment by heli63** [comment]
Sorry, I posted this too early, it was a Phoca-Toomenu-Problem that is solved<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42272">issues.joomla.org/tracker/joomla-cms/42272</a>.</sub>

**Comment by drmenzelit** [comment]
Closing as solved
