### ISSUE TITLE
[J5 Tempalte] The main problem with the black mode of the administrator template.

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#42276]
### What needs to be fixed
The general style of the dark mode template. I am ashamed to install J5 for clients, dark mode is very bad. The frames of the tables are brighter than the text, you should understand that this is a disaster of the template design.

### Why this should be fixed
A lot of lines, strokes, glow. For example, let's look at the settings panel. The frames of tables and lists strain the brain, the brain gets tired. 
Let's compare it with the dark theme of GITHUB. We see that the color of the borders is much darker than the color of the text. But in the dark Joomla theme, the brightness of the frames is much brighter than the useful content. Are you sure this is an accessible mode?

### How would you fix it
The colors of the frames of tables and lists of Articles, Categories, Users, Settings pages should be made several times darker than the text, so that they are darker than the text, not lighter. The main thing on the page is the text, not the frames.  
You can use the frame color from GITHUB. 
Remove the underlining of links, but make underscores only when hovering the mouse or highlighting. Or make the underline color translucent. 
Make white inscriptions with normal(medium) weight text. Make the border-colors of the translucent so that they are darker.

### Side Effects expected
Many summers ago, the first Joomla 4 template was also bad. But we have finished it, now we need to bring the dark theme. Just inverting the colors of the white theme into a dark theme is very bad. To begin with, a person has eye receptors that see only black and white in the dark, so it is impossible to invert colors with a simple movement.

##  Let's discuss the amendments and post screenshots with examples here.

**Comment by Fedik** [comment]
Thanks for your comments.
You can test upcoming version https://github.com/joomla/joomla-cms/pull/42010 , when it will be finished.
