### ISSUE TITLE
Custom Images URL

### ISSUE THREAD

**Issue by TheAFKGamer10** [joomla/joomla-cms#42277]
### Is your feature request related to a problem? Please describe.

Insted of having the images link be https://website.com/images/file.jpg, if it is posible to make the link custom, like https://website.com/i/file.jpg.

### Describe the solution you'd like

To have a field in the settings of media in witch you are able to name the folder in witch the files are in. Something like the 'Path to Files Folder' but making it change the entire url as well.

**Comment by richard67** [comment]
@TheAFKGamer10 You can change the base folder in the settings of the „Filesystem - local“ plugin. Then the images and files folders can be set in the settings of the media manager. Is that not sufficient?

**Comment by ssnobben** [comment]
I think you can ask these questions also in the forum https://forum.joomla.org/viewforum.php?f=811&sid=9e56a61fb0f010503d2b5dab97653cb3 and/or also read the Joomla manual about this ie https://docs.joomla.org/J4.x:Media:_Options and then if a solution is missing make a ticket here.. but seems Rickard explain also Cheers!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42277">issues.joomla.org/tracker/joomla-cms/42277</a>.</sub>

**Comment by TheAFKGamer10** [comment]
> I think you can ask these questions also in the forum https://forum.joomla.org/viewforum.php?f=811&sid=9e56a61fb0f010503d2b5dab97653cb3 and/or also read the Joomla manual about this ie https://docs.joomla.org/J4.x:Media:_Options and then if a solution is missing make a ticket here.. but seems Rickard explain also Cheers!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42277">issues.joomla.org/tracker/joomla-cms/42277</a>.</sub>

I could have asked it in the form, but I didn't know it was already a future. The help button in the settings page for media does not show this page. That is why I didn't know it was already implemented.

This also awnsers the future, so this be closed.
