### ISSUE TITLE
com_finder, indexer. No visible message if finder plugins are disabled

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#42296]
### Steps to reproduce the issue
Disable finder plugins, then start indexer. 

You see a progressbar and a message for a few seconds, then the message disappears,. 
Konsole shows a message like "no content could be indexed", but no information why. 

### Expected result
The indexer shows a message like "Could not index your content. Please check if the finder plugins are activated." Or something informative

### Actual result
You see a progressbar and a message for one second, then the message disappears,. 
Konsole shows a message like "no content could be indexed", but no information why.

**Comment by alikon** [comment]
please check #42299

**Comment by alikon** [comment]
please test https://github.com/joomla/joomla-cms/pull/44632
