### ISSUE TITLE
switch administration language

### ISSUE THREAD

**Issue by Laurent-Cosmic** [joomla/joomla-cms#42290]
### Is your feature request related to a problem? Please describe.
I have from time to time to use user guide for some extensions in English when my administration is usually in French (my mother tongue)

### Describe the solution you'd like
As English and French are installed on all my website, I will be happy to have a switch button to switch language of administration not changing parameters in my user profile.  a bit like the switch language we have on website...

**Comment by heelc29** [comment]
Do you know this button? Here you can change the language for the active session.
![image](https://github.com/joomla/joomla-cms/assets/66922325/c3677cf0-2090-4e28-bcda-93d4d6d764a5)

**Comment by Laurent-Cosmic** [comment]
Hello
thanks for the information 
no I did not notice this button which exactly what I want :D 

I see that we can add a button for language but not to reach this screen on the dashboard...  do you know if there is a way to add a button to reach this specific screen in the dashboard?

**Comment by drmenzelit** [comment]
You can create a custom module for the dashboard and set a link to that view. I'm closing the issue, since it is not really an issue. Maybe the forum is the better place to ask.
