### ISSUE TITLE
Language "Dutch" cannot be installed in Joomla 5

### ISSUE THREAD

**Issue by Johanv74** [joomla/joomla-cms#42295]
### Steps to reproduce the issue
I install Joomla 5.0.0 on a online enviroment (sub domain) (in Dutch installation Language) via the kickstart.php option.
After a succesfull installation I choose the option Install additional languages (Extra talen installeren).
Noting happened, not able to install the Dutch language, notting happening.

### Expected resI amult
The posability to install the Duch installation Language.

### Actual result
No installtion Dutch languague in Joomla 5.

### System information (as much as possible)
PHP Version | 8.1.15
Database Version	10.4.27-MariaDB-cll-lve
JooUser Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/118.0.0.0 Safari/537.36mla! Version	Joomla! 5.0.0 Stable [ Kuboresha ] 17-October-2023 16:00 GMT

### Additional comments
After cleanup and loggin in the back-end. I'm able to installl the dutch Language via System > Languages > Install Languages and place an check mark for dutchs language.

**Comment by Quy** [comment]
Duplicate #39139
