### ISSUE TITLE
5.0 Issue in Firefox on Windows, Tiny MCE not loaded.

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#42291]
### Steps to reproduce the issue
I found these errors in a customers console when giving support:

![grafik](https://github.com/joomla/joomla-cms/assets/828371/5c3adf13-a078-4560-88a2-7bc98d2a1e56)

Says: 
) Uncaught TypeError: Error when resolving the module specifier "editor-api". Relative module specifiers must begin with "./", "../* or "/".
) Uncaught TypeError: Error resolving the module specifier "joomla.dialog". Relative module specifiers must start with "./", "../" or "/".
- Uncaught TypeError: Error resolving the module specifier "editor-api", Relative module specifiers must start with "./", "../" or "/".
) Uncaught TypeError: Error when resolving the module specifier "editor-api". Relative module specifiers must start with "./", "../" or "/".
) Uncaught TypeError: Error when resolving the module specifier "editor-api", relative module specifiers must start with "./", "../" or "/".
) Uncaught TypeError: Error resolving the module specifier "joomla.dialog". Relative module specifiers must start with "./", "../" or "/*.
- Uncaught TypeError: Error resolving the module specifier "joomla.dialog", relative module specifiers must start with " ../" or "/".
- The Components object should no longer be used. It will be removed soon.

### Expected result
Tiny MCE should load

### Actual result
Does not load in that browser (Firefox, Windows)

### System information (as much as possible)
Joomla 5.0.0

**Comment by dgrammatiko** [comment]
Only browsers that support import maps are supported, ie: https://caniuse.com/import-maps
If you need to support browsers without import maps support in the template you can load this polyfill: https://www.npmjs.com/package/es-module-shims#es-module-shims

**Comment by coolcat-creations** [comment]
But its the core tiny MCE ? What do I need to do?

**Comment by dgrammatiko** [comment]
Add this:
```html
<script async src="https://ga.jspm.io/npm:es-module-shims@1.8.1/dist/es-module-shims.js"></script>

```
before `<jdoc:include type="scripts" />` https://github.com/joomla/joomla-cms/blob/c9b318106e9b34b3d736f3bd2c8c04968701bcfa/templates/cassiopeia/index.php#L132 in the head of your template to check if this is your problem. BTW what's the version of FF?

**Comment by coolcat-creations** [comment]
But why in Cassiopeia, it's in Atum in the backend? 
I am sorry I dont know the customers version number I clicked in the meeting on check for updates and it said that everything is up to date. But I dont know the exact version number on their windows.

**Comment by dgrammatiko** [comment]
> But why in Cassiopeia, it's in Atum in the backend?

Sorry, I thought it was a front end template by the screenshot, try the same as above in the Atum: https://github.com/joomla/joomla-cms/blob/c9b318106e9b34b3d736f3bd2c8c04968701bcfa/administrator/templates/atum/index.php#L106

>  it said that everything is up to date

Well, the error is that the `relative module specifier` should start with `.` but obviously it starts with a letter, because there's an import map that should resolve the path. I'm getting to technical here, but the point is that their FF is not up to date, actually it's more than 1 1/2 yrs old.

If you care to understand the problem I've explained how this tech is working here: https://github.com/joomla/joomla-cms/pull/41034

The thing that is not very clear though is which browsers J5 actually supports ootb. Anyways could you please verify that things work normally with the polyfill?

**Comment by Fedik** [comment]
What Dimitris said: Update your Firefox to latest version.
If it not an option then use `$wa->useScript('es-module-shims');` to enable polyfill.

Do NOT do this https://github.com/joomla/joomla-cms/issues/42291#issuecomment-1793512471 :smile: 

I am closing here.

**Comment by coolcat-creations** [comment]
Because I was confused, I will add more context here for people that don't understand what's going on (like me) and end up here :-)
Apparently something in Joomla 5 was changed so that Browser versions that are older as 2023 (also Longtime Support and Extended Support Versions) will have issues displaying the tiny MCE Editor. To fix this the Admin Template needs to load the Polyfill script. But the better solution is to ask the organisation administrator to update the browser.
Hope this summary was correct.

**Comment by Fedik** [comment]
One more note.

> To fix this the Admin Template needs to load the Polyfill script

This also can be done via plugin, onBeforeCompileHead event.
