### ISSUE TITLE
MFA and Silent Login

### ISSUE THREAD

**Issue by jhrenshaw** [joomla/joomla-cms#42308]
### Steps to reproduce the issue
Clean installation of Joomla 5.0
Create user and set up MFA (I used a Yubikey) and passkey (same Yubikey)
In User options, make sure 'MultiFactor Authentication after Silent Authentication' is set to 'No' and 'Response Types' set to the default 'cookie, passwordless'
Login using a passkey

### Expected result
Shouldn't be required to use MFA method

### Actual result
Are required to use MFA method

### System information (as much as possible)
Standard Linux box, PHP 8.2, MySQL 8.0.32, Joomla 5.0

**Comment by Tuxar7** [comment]
I am facing the same issue after upgrading from Joomla 4.4. Please assign issue and fix it.

**Comment by jjnxpct** [comment]
I noticed the same thing after upgrading a website from J4 to J5. After logging in with a passkey (I use 1Password to store my paskeys) I should not have to also use 2FA (Yubikey in my case) to log in.

**Comment by Tuxar7** [comment]
Just made the upgrade to Joomla 5.0.3 and the problem still persists

**Comment by jjnxpct** [comment]
This issue is still present in the latest 5.1 development release. I would be great if this could be fixed in a next release.

**Comment by jjnxpct** [comment]
I don't think this issue will be addressed in Joomla 5.2?

**Comment by jjnxpct** [comment]
Great! Thanks @brianteeman .

**Comment by richard67** [comment]
Closing as having a pull request. Please test #43796 . Thanks in advance.
