### ISSUE TITLE
Back to Top Button in Cassiopeia Template is black after once clicked

### ISSUE THREAD

**Issue by NGC6888** [joomla/joomla-cms#42302]
### Steps to reproduce the issue
Go to a Website with Cassiopeia Template e.g.
https://www.sternwarte-ursensollen.de/

Scroll down and click "Back to Top Button" on right lower corner.
Do it again!

### Expected result
Back to Top Icon should be normal Layout

### Actual result
Back to Top Icon is filled with template color with no arrow

### System information (as much as possible)
Joomla4 and Joomla5

New behavior is in Joomla4 since V 4.2

### Additional comments
![screen shot 2023-11-07 at 11 21 09](https://issues.joomla.org/uploads/1/0846d6a66e89ac0f94cf43ecab0f03b3.jpg)
![screen shot 2023-11-07 at 11 21 43](https://issues.joomla.org/uploads/1/0876c1ccbb5b156d056cf7e17fb9754a.jpg)

**Comment by drmenzelit** [comment]
The issue was already reported, if I remember right. Please check https://github.com/joomla/joomla-cms/pull/41749

**Comment by richard67** [comment]
Closing as having a pull request. Please test #42504 . Thanks in advance.
