### ISSUE TITLE
[5.0] Dialog: aria-label for Close button is not translated

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#42301]
### Steps to reproduce the issue
Enable Debug Language.
Edit an article.
Under Publishing tab > Created by, click user icon to display the modal dialog.
Using Web Developer Tools, select the Close button to inspect it.

### Expected result
`aria-label="**Close**"`

### Actual result
`<button type="button" aria-label="Close" class="button-close btn-close" data-button-close=""></button>
`

**Comment by brianteeman** [comment]
Please test #43058

**Comment by Quy** [comment]
Thank you!
