### ISSUE TITLE
Joomla 5.0.0 TinyMCE not working on smartphone anymore

### ISSUE THREAD

**Issue by NGC6888** [joomla/joomla-cms#42304]
### Steps to reproduce the issue
Set Editor to TinyMCE
Login on a Site with smartphone (iPhone / Android) e.g.
http://betatest1.sternwarte-ursensollen.de/index.php/en/?view=form&layout=edit
Use credentials:
User: TestUser
Pass: TestUser0012

Edit Articel with smartphone

### Expected result
Articel should be not in "code view"

### Actual result
Articel is in code view

If Editor is switched to JCE, everything is OK, so TinyMCE should be the cause.

### System information (as much as possible)
Joomla 5.0.0
Cassiopeia Template
Updated from Joomla 4.4 to Joomla 5.0
PHP 8.2

### Additional comments
Bug was also reported here:
https://forum.joomla.org/viewtopic.php?f=834&t=1005146

Quote:
Fresh install of Joomla 5.0.0, when trying to edit an article with Tiny MCE (default settings) on smartphone in the Site Front-End, it only shows the HTML source code of the article content, but not the formatted HTML output anymore.

On Joomla 4.x it worked as expected, so i guess this is a hick-up in J5 / new Tiny MCE?

Reproduce:
- create an article in the backend
- assign the article to a menu item
- log in on site front-end with android smart phone (Google Chrome)
- try editing the article on the smartphone

Thanks,
Clem
Top

End Quote

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/42306
