### ISSUE TITLE
TinyMCE templates don't work in J5

### ISSUE THREAD

**Issue by camminateinfriuli** [joomla/joomla-cms#42319]
### Steps to reproduce the issue
With J4.4.0 and previous the Insert Template worked in TinyMCE, after updating to J5 clicking on Insert Template nothing happens or the cursor moves over the text.

### Expected result
Clicking on Insert Template should open the window to select one of the TinyMCE templates

### Actual result
clicking on Insert Template nothing happens or the cursor moves over the text.

### System information (as much as possible)
J5.0.0

### Additional comments
TinyMCE templates are not yet deprecated, they say it will be from version 7

**Comment by Fedik** [comment]
Please test the fix https://github.com/joomla/joomla-cms/pull/42321
