### ISSUE TITLE
[5.x] tinymce content template

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42318]
### Steps to reproduce the issue
create a simple txt file in the html/tinymce folder of your template

Use the content template icon in an article
![image](https://github.com/joomla/joomla-cms/assets/1296369/5f8585d4-a5be-4bd4-b86d-526eb564c300)

### Expected result
modal opens with list of templates to select

### Actual result
nothing happens. js message in console

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'title')

![image](https://github.com/joomla/joomla-cms/assets/1296369/b79ea3dc-d9e2-47e9-a49a-26e0b7f79b0e)

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/42321

**Comment by camminateinfriuli** [comment]
I tested #42321 now the button responds but says there are no templates defined![screen shot 2023-11-08 at 16 34 13](https://issues.joomla.org/uploads/1/25dd22922ecbaa96b21c614cbef4cad6.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42318">issues.joomla.org/tracker/joomla-cms/42318</a>.</sub>
