### ISSUE TITLE
Show Cassiopeia  "Back to Top" Button as soon as site is scrolled and not only on Bottom of page

### ISSUE THREAD

**Issue by NGC6888** [joomla/joomla-cms#42312]
### What needs to be fixed
The "Back to Top" Button should be always shown as soon as site is scrolled down as it was implemented in early versions of cassiopeia template.

### Why this should be fixed
Better usability with smartphones as button is always there

### How would you fix it
Momentarily it can be fixed with this entry in user.css

.back-to-top-link {position: fixed;}

### Side Effects expected
none

Exampel Site:
http://joomla4-ignitegallery.sternwarte-ursensollen.de/index.php/en/

**Comment by sandewt** [comment]
Related to https://github.com/joomla/joomla-cms/pull/41749

**Comment by richard67** [comment]
Closing as having a pull request. Please test #43057 . Thanks in advance.
