### ISSUE TITLE
[5.0.0] Smart Search image not always displaying in results

### ISSUE THREAD

**Issue by djalondon** [joomla/joomla-cms#42320]
### Problem identified

When Result Image is set to Show in Smart Search, the Intro image doesn't display in the search result if there's a space in the file name

### Proposed solution

If the image can display elsewhere in the site with a space in the filename, it should display in search results

**Comment by sandewt** [comment]
Related to #41749

**Comment by ssnobben** [comment]
Any update when this bug can be fixed?

**Comment by Hackwar** [comment]
This bug should be fixed with #42725. Please test this change. Since we have a PR, I'm closing this issue.
