### ISSUE TITLE
[5.0] System Information: Strange value at "Joomla Backward Compatibility Plugin"

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#42338]
### Steps to reproduce the issue
Install Joomla 5.0 (you can use the nightly build, the result is the same), go to **System** --> **System Information**, in the **Joomla Backward Compatibility Plugin** line I see a strange value.

![Screenshot_1](https://github.com/joomla/joomla-cms/assets/8440661/1ba99ef4-8b75-4b1e-a7c6-f1a5e6743166)

Joomla 5.0,
PHP 8.1.9,
Apache 2.4,
MariaDB 10.8.4

**Comment by HLeithner** [comment]
This is expected output.
