### ISSUE TITLE
[5.0.0] Bug lc_collate Postgres 16 when showing joomla sysinfo

### ISSUE THREAD

**Issue by alexandreelise** [joomla/joomla-cms#42335]
### Steps to reproduce the issue
Install joomla:5-php8.2-fpm docker image with FrankenPHP
with Postgres 16 docker image
Go to admin area.
Try to show system info

### Expected result
System info is correctly shown

### Actual result
42704 42704, 7, ERROR: unrecognized configuration parameter "lc_collate"

### System information (as much as possible)
Ubuntu 22.04 LTS
Docker Desktop 1.25.0
Joomla 5.0.0
PHP 8.2.12
SAPI: FrankenPHP
Caddyserver

### Additional comments
This issue might be related to the fact that lc_collate was removed in Postgres 16.

https://git.postgresql.org/gitweb/?p=postgresql.git;a=commit;h=b0f6c437160db640d4ea3e49398ebc3ba39d1982

But the joomla manual recommends to use Postgres 16 when installing Joomla 5

**Comment by alexandreelise** [comment]
Possibly related to this code:
- https://github.com/joomla-framework/database/blob/d440247b1e07710f22d5e07650393fbd9364b01e/src/Pgsql/PgsqlDriver.php#L117
- https://github.com/joomla-framework/database/blob/d440247b1e07710f22d5e07650393fbd9364b01e/src/Pgsql/PgsqlDriver.php#L133

**Comment by alexandreelise** [comment]
Works with Postgres 15.4 as expected. Not with Postgres 16 as described in the issue.
![screenshot-auto-install-joomla-frankenphp-postgres-docker-2023-11-12-18-03-53](https://github.com/joomla/joomla-cms/assets/51425450/a14770ee-1255-42e0-b160-38d27a7a00f2)

**Comment by xaiyeon** [comment]
hi @alexandreelise 
I'm using docker compose, with joomla5 and postgres 16,  images: joomla:5.0.0-php8.2-fpm, postgres:16.0 and won't even connect; ```PostgreSQL Connection Error``` 
my joomla5 service env, ex:
```
    environment:
      - JOOMLA_DB_TYPE=pgsql
      - JOOMLA_DB_HOST=prodpgbrands16:5435
      - JOOMLA_DB_USER=admin
      - JOOMLA_DB_PASSWORD=password123%
      - JOOMLA_DB_NAME=thedatabase
      - JOOMLA_LOAD_SAMPLE_DATA=no
      - PHP_MEMORY_LIMIT=512M
      - ACME_AGREE=true
      - PHP_UPLOAD_MAX_FILESIZE=1GB
```
how/anyone? do I have to try 15.4 ?

**Comment by alexandreelise** [comment]
Hi @xaiyeon,
You might want to try https://github.com/alexandreelise/frankenphp-joomla. It's not to do self-promotion. It's to point you to an example that works flawlessly and that you can base your code on. You could rather want to try using postgres:15-bookworm (latest Debian codename)  docker image. One side note, don't forget to use pgsql in your joomla configuration dbtype

**Comment by alikon** [comment]
please test https://github.com/joomla-framework/database/pull/295

**Comment by teoberi** [comment]
Why is this not in 5.0.2?

**Comment by richard67** [comment]
Please test #44316 . Thanks in advance.
