### ISSUE TITLE
User self delete error /libraries/src/Event/AbstractEvent.php on line 225

### ISSUE THREAD

**Issue by ssnobben** [joomla/joomla-cms#42339]
Hi 

I have a Joomla 5.0.1 new updated site and when a user that is new register to the site and then self delete his profile he get this error message and is not deleted from the user system.

Error message: 

"0
Joomla\CMS\Event\Model\DeleteEvent::onSetSubject(): Argument #1 ($value) must be of type object, array given, called in /libraries/src/Event/AbstractEvent.php on line 225"

### Actual result
User get error message and not deleted from the Joomla 5 system.

### System information (as much as possible)
Joomla 5.0.1 dev php 8.1.23

**Comment by alikon** [comment]
Are you using a 3rd party extension ?

**Comment by ssnobben** [comment]
Yes I think this is releated to EasySocial issue...
