### ISSUE TITLE
Property 'mime_type' of argument 'item' of event onFetchMediaItems has a wrong item. Valid: string

### ISSUE THREAD

**Issue by uoppah** [joomla/joomla-cms#42354]
### Steps to reproduce the issue
Content -> Media manager 
Message error "Property 'mime_type' of argument 'item' of event onFetchMediaItems has a wrong item. Valid: string"
I read that to solve the problem you need to enable fileinfo in php.ini
I contacted my hosting provider but fileinfo is already enabled.
I copied the site locally with xampp and it works fine.

What could be the solution?

Thanks, Simone
### System information (as much as possible)
joomla 4.4

PHP Version 8.2.10
fileinfo
fileinfo support enabled
libmagic 540

**Comment by Quy** [comment]
Related #39711

**Comment by Quy** [comment]
Under System > System Information, what is the value of `Fileinfo Available`?

**Comment by uoppah** [comment]
Fileinfo Available 	Yes

**Comment by alfonzog** [comment]
chmod 644 for files into folder

**Comment by uoppah** [comment]
nothing has changed

**Comment by uoppah** [comment]
I've solved the problem.
