### ISSUE TITLE
Improvements to the dark color scheme of Joomla 5 administration

### ISSUE THREAD

**Issue by impressionestudio** [joomla/joomla-cms#42351]
### Steps to reproduce the issue
Enable dark color mode in Windows (or IOS) and visit the Joomla 5 administration area .

### Expected result
Expected a nice dark theme that is really smooth to the eyes.

### Actual result
1. The design is not good because the text is a few worlds surrounded by many blocks and borders with different color.
2. Some colors have intense contrast.

### System information (as much as possible)
Joomla 5.0

### Additional comments
Please see the image below for a description of the design issues.
I believe that a graphic designer could easily improve the colors.

![screen shot 2023-11-15 at 17 12 25](https://issues.joomla.org/uploads/1/6c9952ffad1dc6fc8bbb328f33dba615.png)

**Comment by Quy** [comment]
Thank you for your feedback. Please test PR #42010.

**Comment by impressionestudio** [comment]
Thanks for the answer. It seems that I didn't search well for any relevant issue. 
(I am sorry, I am not able to test any PR.)
