### ISSUE TITLE
Apostrophe (single straight quote ' ) not allowed in email (js validation error)

### ISSUE THREAD

**Issue by JamesNGarrett** [joomla/joomla-cms#42357]
### Steps to reproduce the issue

Try to create a user with an apostrophe (single straight quote ' ),  in the username part of the email like DeloresO'Grady@example.com

### Expected result

Email is accepted.

### Actual result

Email is declared invalid.

### Additional comments

This was previously (in 2016) discussed here: https://github.com/joomla/joomla-cms/issues/6982

And fixed here: https://github.com/joomla/joomla-cms/pull/12835

But the email validation regex in media/system/fields/js/validate is currently set to not allow '

```
    this.setHandler('email', value => {
        const newValue = punycode.toASCII(value);
        const regex = /^[a-zA-Z0-9.!#$%&’*+/=?^_`{|}~-]+@[a-zA-Z0-9-]+(?:\.[a-zA-Z0-9-]+)*$/;
        return regex.test(newValue);
    });
```

**Comment by drmenzelit** [comment]
Which Joomla version are you using?

**Comment by drmenzelit** [comment]
Problem confirmed in Joomla 5.0

**Comment by brianteeman** [comment]
very strange that its passing the specific unit test for this `tests\Unit\Libraries\Cms\Mail\MailHelperTest.php`

**Comment by JamesNGarrett** [comment]
To be clear this is a js validation error and not a server side error. Hence the unit test passes.

An email with a smart (not straight) apostrophe (eg o’reilly@there.com) passes js validation and fails on save.
