### ISSUE TITLE
Malformed User Actions Log Notification Mail

### ISSUE THREAD

**Issue by luktaas** [joomla/joomla-cms#42353]
### Steps to reproduce the issue

Take an article, make a change and save and close.

### Expected result

The {message} field in the User Actions Notification Mail should be: (example):
"User <a href=\"{accountlink}\">{username}</a> updated the {type} <a href=\"{itemlink}\">{title}</a>" + {date} + {extension} + {username}
>>"User XXX updated article XXX + {date} + {extension} + {username}

### Actual result

**PLG_SYSTEM_ACTIONLOGS_CONTENT_UPDATED**	2023-11-15 20:05:50 UTC	Articles	Luk Thijs

### System information (as much as possible)

Joomla 5.0.0
PHP 8.1.24

### Additional comments

The issue remains when changing languages.

**Comment by Quy** [comment]
Fixed in PR #40033 pending to be merged. Thanks for the report.

**Comment by Quy** [comment]
Fixed per #40033.

**Comment by luktaas** [comment]
Does anyone know why this issue is still unresolved ?
Are currently on J5.1.0 and I see no change.
I have several sites with several Front-End users and it's not very convenient to have to open the Back-End all the time instead of being properly informed via email.

**Comment by brianteeman** [comment]
The issue was closed as it was fixed with #40033 for Joomla 5.1.0
If you are still experiencing non translated emails then please create a NEW issue.
