### ISSUE TITLE
[5.0] npm fails on windows

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42356]
Since the change to lightningcss I am unable to successfully conmplete `npm install`

```
PS C:\laragon\www\j5> npm install
npm WARN deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

> joomla@5.0.1 install
> node build/build.js --prepare

node:internal/modules/cjs/loader:1051
  throw err;
  ^

Error: Cannot find module '../lightningcss.win32-x64-msvc.node'
Require stack:
- C:\laragon\www\j5\node_modules\lightningcss\node\index.js
- C:\laragon\www\j5\build\build-modules-js\error-pages.es6.js
- C:\laragon\www\j5\build\build.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at Object.<anonymous> (C:\laragon\www\j5\node_modules\lightningcss\node\index.js:21:22)
    at Module._compile (node:internal/modules/cjs/loader:1233:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1287:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12)
    at Module.require (node:internal/modules/cjs/loader:1115:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'C:\\laragon\\www\\j5\\node_modules\\lightningcss\\node\\index.js',
    'C:\\laragon\\www\\j5\\build\\build-modules-js\\error-pages.es6.js',
    'C:\\laragon\\www\\j5\\build\\build.js'
  ]
}

Node.js v20.5.1
npm ERR! code 1
npm ERR! path C:\laragon\www\j5
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node build/build.js --prepare

npm ERR! A complete log of this run can be found in: C:\Users\brian\AppData\Local\npm-cache\_logs\2023-11-16T17_13_46_278Z-debug-0.log

```

**Comment by Fedik** [comment]
No idea,
Maybe try to remove whole `\node_modules\` folder manualy, and run it again.

**Comment by brianteeman** [comment]
already did that before posting

**Comment by N6REJ** [comment]
Can confirm even using the very latest nodejs which was released on the 13th ( 21.2.0 )
<img width="775" alt="image" src="https://github.com/joomla/joomla-cms/assets/1850089/b920aeaf-cb81-4103-aea3-eb7d26e0f99a">
[2023-11-17T00_37_50_556Z-debug-0.log](https://github.com/joomla/joomla-cms/files/13385510/2023-11-17T00_37_50_556Z-debug-0.log)

**Comment by brianteeman** [comment]
It appears to be a fairly frequent issue with npm and lightningcss that has effected different platforms (not just windows) with npm not fetching the optional dependencies which maybe are not optional after all

![image](https://github.com/joomla/joomla-cms/assets/1296369/8ef48662-bed8-4bb4-8693-09b3060fc503)

**Comment by brianteeman** [comment]
Looks like I have fixed it by deleting \node_modules AND package-lock.jason

**Comment by chmst** [comment]
Did not help for me.

  code: 'MODULE_NOT_FOUND',
  requireStack: [
    'D:\\xampp\\htdocs\\joomla-50\\node_modules\\lightningcss\\node\\index.js',   
    'D:\\xampp\\htdocs\\joomla-50\\build\\build-modules-js\\error-pages.es6.js',  
    'D:\\xampp\\htdocs\\joomla-50\\build\\build.js'

**Comment by brianteeman** [comment]
tried again and it failed again. deleting everything is not a fix.

**Comment by Fedik** [comment]
Hmhm, does command `npm install lightningcss-win32-x64-msvc` work for you, or it end up with error?

**Comment by brianteeman** [comment]
If you do that and then try to do a full npm install you just move on to the next error message which is also from the same PR 

Embedded Dart Sass couldn't find the embedded compiler executable. Please make sure the optional dependency sass-embedded-win32-x64 is installed in node_modules.

**Comment by brianteeman** [comment]
Seems to be a common problem with platform specific optional dependencies https://github.com/npm/cli/issues/4828

**Comment by chmst** [comment]
Thank you both very much for investigating! This is somehow annoying as I have only windows

**Comment by brianteeman** [comment]
More than annoying

**Comment by chmst** [comment]
It works on 5.1 - dev

**Comment by Fedik** [comment]
I think it not upmerged yet.
Does it work on 4.4? the original PR was for 4.4-dev

**Comment by chmst** [comment]
not on 4.4.1 - dev.  But other error. 

![grafik](https://github.com/joomla/joomla-cms/assets/1035262/5f44e457-64f4-405b-839a-76f462f41a20)

**Comment by Fedik** [comment]
I have tried to test it on VirtualBox Win10, node v20.9.
4.4-dev works.

5.0-dev: 
Does not work, 
Need to remove `package-lock.json` file and  `node_modules` folder. Then it work for me.

**Comment by brianteeman** [comment]
Which is not realistic

**Comment by Fedik** [comment]
I would make you video, but VirtualBox so slow, it will take ages :smile:

**Comment by Fedik** [comment]
Can you please try lock file from this PR https://github.com/joomla/joomla-cms/pull/42361

**Comment by chmst** [comment]
tested and works

**Comment by Fedik** [comment]
Okay, will count this as a fix  https://github.com/joomla/joomla-cms/pull/42361.

**Comment by brianteeman** [comment]
the pr was closed but the problem still exists!!!
please reopen

**Comment by coolcat-creations** [comment]
I had this issue as well but solved it with that:

nvm uninstall node
arch -x86_64 zsh 

arch -x86_64 zsh

rm -rf node_modules
rm package-lock.json
npm install

nvm install node
source ~/.nvm/nvm.sh

**Comment by bembelimen** [comment]
Please check with the current 5.0-dev branch.

**Comment by brianteeman** [comment]
appears to be ok - thx
