### ISSUE TITLE
some css text not visible

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#42352]
### Steps to reproduce the issue
create a custom.css
Enter content

### Expected result
syntax coloring is as before.

### Actual result
some content is white on white.
<img width="234" alt="image" src="https://github.com/joomla/joomla-cms/assets/1850089/e54589ef-e76b-4f40-a5a0-f46d46a5564c">
<img width="269" alt="image" src="https://github.com/joomla/joomla-cms/assets/1850089/7632bb9d-46bf-4d02-b00a-b10e1298c868">
<img width="370" alt="image" src="https://github.com/joomla/joomla-cms/assets/1850089/b8230158-3b4b-44e1-b70d-76d34deb3d9e">
<img width="255" alt="image" src="https://github.com/joomla/joomla-cms/assets/1850089/1ec1871f-8ff0-4eb1-b96c-595e0f834d56">

**Comment by N6REJ** [comment]
happens with .php files also 
<img width="583" alt="image" src="https://github.com/joomla/joomla-cms/assets/1850089/69f4571a-e7bb-4958-b6c7-721317c9dd4a">

**Comment by Quy** [comment]
Fixed in PR #42322.

**Comment by N6REJ** [comment]
ty @Quy I'll close it.
