### ISSUE TITLE
[5] Bottom-border in Success-Message in History-Window missing

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#42358]
### What needs to be fixed
Missing Bottom-border in green Success-Message:
![version](https://github.com/joomla/joomla-cms/assets/147295380/4181a08e-c5d1-435b-a8ea-24026e2fc4ea)

**Comment by Quy** [comment]
Which browser/operating system as I am unable to replicate?

![42358](https://github.com/joomla/joomla-cms/assets/368084/86cba41c-ac86-4e54-b80a-6e752cf00c66)

**Comment by fgsw** [comment]
PHP Built On 	Linux lamp302.cloudaccess.net 3.10.0-962.3.2.lve1.5.81.el6h.x86_64 #1 SMP Wed May 31 12:07:35 UTC 2023 x86_64
Database Type 	mysql
Database Version 	8.0.34-cll-lve
Database Collation 	utf8mb4_general_ci
Database Connection Collation 	utf8mb4_0900_ai_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	Yes
PHP Version 	8.1.24
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 5.0.0 Stable [ Kuboresha ] 17-October-2023 16:00 GMT
Joomla Backward Compatibility Plugin 	Enabled (classes_aliases:"1", es5_assets:"1")
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0

**Comment by Quy** [comment]
Is this happening to all alerts or only this one? Is the zoom level increased?

**Comment by fgsw** [comment]
It happens to other alerts too.

The zoom level is not increased.

In safari the bottom-border is shown.

**Comment by Quy** [comment]
Are you using the latest version of Firefox? If yes, what is its version?

**Comment by fgsw** [comment]
>  User Agent Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0

**Comment by fgsw** [comment]
Not only Contacts, also Articles: Edit > Associations > Edit > Save:

![article-modal](https://github.com/joomla/joomla-cms/assets/147295380/c4acdbf7-3184-4edf-b178-b984da9e28a9)

**Comment by fgsw** [comment]
Not only Contacts, Articles, also Menu item: Edit > Associations > Edit > Save:
![menu-item](https://github.com/joomla/joomla-cms/assets/147295380/13509ce6-0f09-480b-9ed4-872f87f4403a)

**Comment by fgsw** [comment]
![success](https://github.com/joomla/joomla-cms/assets/147295380/20c3284f-7e71-44ff-ae59-3e60903ab51f)

**Comment by fgsw** [comment]
In Frontend the bottom-border is shown.

**Comment by fgsw** [comment]
The screenshot (source: com_media) shows 2 messages, only the second have no border. Looks like something is hiding the border of the second message:

<img width="541" alt="2messages" src="https://github.com/joomla/joomla-cms/assets/147295380/23365fd0-b803-4721-b5f1-18d0621f6db5">

**Comment by fgsw** [comment]
Its a small issue, no need to keep it open. Thanks @Quy for your time.
