### ISSUE TITLE
[4.4.0 Bug] Drag & Drop does not run

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#42367]
Hi guys, 
PHP 7.4.33 & 8.1.x + Joomla 4.4.x
Joomla is using the nice drag & drop feature, but it is not running on mobile.

Example case:
I edit the TinyMCE plugin and I want to add some icons to the Set 0 preset. I could add the Add link amd Remove Link buttons by dragging them into the toolbar from the All available menus and buttons area at the top of the plugin configuration page.

On Android Chrome, Wiki browsers the drag & drop is not running.
On Android Firefox Is "running", but practically impossible to use.
This is true also with "Desktop Mode" enabled 

**Solution**
As far as I understand [this is](https://stackoverflow.com/questions/75653513/drag-and-drop-for-mobile-devices) 

Can you confirm the bug ?
Do you agree with the simple solution ?

**Comment by brianteeman** [comment]
The drag and drop api is not well supported on mobile browsers https://caniuse.com/?search=draganddrop

Personally I wouldnt expect to be able to do everything on a mobile browser - just day to day content editing
