### ISSUE TITLE
[5] Contacts Options: Image not shown in Frontend

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#42362]
### Steps to reproduce the issue

Select in Contacts **Options** an Image:
![contact-image](https://github.com/joomla/joomla-cms/assets/147295380/70bcdbc2-2cdb-4332-9ec6-8793492e6863)

### Expected result
Image is shown in every contact on frontend.

### Actual result
Image is not shown in any contact on frontend.

### System information (as much as possible)
PHP Built On 	Linux lamp302.cloudaccess.net 3.10.0-962.3.2.lve1.5.81.el6h.x86_64 #1 SMP Wed May 31 12:07:35 UTC 2023 x86_64
Database Type 	mysql
Database Version 	8.0.34-cll-lve
Database Collation 	utf8mb4_general_ci
Database Connection Collation 	utf8mb4_0900_ai_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	Yes
PHP Version 	8.1.24
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 5.0.0 Stable [ Kuboresha ] 17-October-2023 16:00 GMT
Joomla Backward Compatibility Plugin 	Enabled (classes_aliases:"1", es5_assets:"1")
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/119.0 

### Additional comments

1. No Menu is used for a contact
2. No Image is selected in a contact itself
3. Contacts are assigned to users.

My guess was the image selected in contact options is used as placeholder for every contact as long as a single contact don't have an own image selected.

**Comment by fgsw** [comment]
New to me: The image is shown in the frontend for **categories** ( Menu Item Type ```List Contacts in a Category```). Select another image in a category replace the image of contact options.

**Comment by alikon** [comment]
please test #43126
