### ISSUE TITLE
[4.4 & 5 Bug] Link Icon class p-2

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#42368]
Hi guys,
as far as I see, to the "Menu Item > Link Type >  Link Icon class" a fixed "p-2" attribute class is applied.

That is spacing also on the left side, moving all the menu items on the right and creating  a bad ordering column, confusion with the sub menu items that are not using icons, for example.

It should be "pe-2"
https://getbootstrap.com/docs/5.3/utilities/spacing/
Please, Can you confirm it ?
Please, Where can we manually edit and fix it ?

Maybe, it would be better to add it through CSS instead to use the fixed Bootstrap attribute. It would be simpler for customers to personalize it, if needed.

Please, Why you choose to add there a padding space instead of a margin space ?

**Comment by chmst** [comment]
Did you also try with a right-to-left language?

**Comment by brianteeman** [comment]
@chmst pe-2 is a logical css property so should work the same in both

**Comment by joomleb** [comment]
@chmst sure, that's why I reported the Bootstrap link:
"...e - (end) for classes that set margin-right or padding-right in LTR, margin-left or padding-left in RTL..."

**Comment by joomleb** [comment]
Hi guys,
as far as I investigated these should be the lines to change:
…/modules/mod_menu/tmpl/default_component.php - line 44 and 47
…/modules/mod_menu/tmpl/default_heading.php - line 23 and 26
…/modules/mod_menu/tmpl/default_separator.php - line 23 and 26
…/modules/mod_menu/tmpl/default_url.php - line 36 and 39

**1** - @brianteeman Can you confirm me ? 
If confirmed and if you want I can prepare the PR...

**2** - What is the best solution for you ? Padding pe-2 or Margin me-2 ?

**Comment by brianteeman** [comment]
Sorry I don't understand what you are trying to solve

![image](https://github.com/joomla/joomla-cms/assets/1296369/cd503b01-e334-48c9-8fec-ec5586096a9a)

**Comment by joomleb** [comment]
Hi @brianteeman 
I thought it was clear and sorry for my English.

1 - The Link Icon class should only take care to space itself from the menu item title. So, only on the right (left on LTR), because in case of a mod menu in a vertical view, as it is now p-2, is moving all the menu items with the icons on the right. This creates a bad vertical alignment, where menu items of the same level (some menu items can have the icon, some mo,) are not well aligned. And creating confusion with the sub menu items, where a 1st level menu item with icon could be vertically aligned with a 2nd level menu item that is not using icon.

 - p-2 https://photos.app.goo.gl/gKxfeHVyKhXUibR57
 -  pe-2 https://photos.app.goo.gl/ueeyzb5DYAYEzFFT6

Is it clear now what I mean ?

2 - Then I asked you if it is better to use padding (as it is now) or margin.
Anyway we can also say that to add a spacing class there it is not a must, Why ?
Well, simply because when I'm setting the "Menu Item > Link Type > Link Icon class: ..." a Joomla user can add what he wants, also a pe-2 class (or me-2, p-2).
So, to add a fixed class there it is not a must, dire it cannot be "p-2" attribute class.

I remain available

**Comment by brianteeman** [comment]
Thanks for the screenshots. Makes perfect sense now.

Please submit a pull request so that others can test and review.

**Comment by chmst** [comment]
As you write, everyone can add own classes and removing the class makes it flexible. 

But it is a b/c break, it affcts existing menus.

**Comment by brianteeman** [comment]
> As you write, everyone can add own classes and removing the class makes it flexible.
> 

The p-2 class is hardcoded :(

> But it is a b/c break, it affects existing menus.

> 6.1.7 Rendered markup
> For the time being, rendered markup is not subject to our backwards compatibility promise.

**Comment by chmst** [comment]
> The p-2 class is hardcoded :(

I wanted to say that I prefer removing the class completely and not change it to pe- or anything else.

**Comment by joomleb** [comment]
Hi guys,
@brianteeman before to going on with the PR,
Please, Can you confirm me that "to completely remove the p-2 classes" is the chosen solution ?

**Comment by joomleb** [comment]
> Hi guys, @brianteeman before to going on with the PR, Please, Can you confirm me that "to completely remove the p-2 classes" is the chosen solution ?

@brianteeman I know you have thousands of things here, so maybe you lost this. Just to remember you that I'm waiting your confirmation before to going on...

**Comment by brianteeman** [comment]
it is really nothing to do with me. just create a pr how you think it is best and then maintainers and release oleads will make a decision. my opinion is no more important and valid than yours
