### ISSUE TITLE
[4.4] Guide Tours Modal problem

### ISSUE THREAD

**Issue by JoomlaBelarus** [joomla/joomla-cms#42372]
### Actual result
I see now only in one site under J4.4. Problem with guided tours window. It open, and dialog with start tour see not in center window, but in center of all page. First i think about some plugin and try to unpublic same, i try to reinstall core files,  i change script files in system guidetours plugin folder- it's the same.

### System information (as much as possible)
Joomla 4.4, YOOtheme Pro, FALANG, JCE. PHP 8.2.11, 10.8.8-MariaDB

### Additional comments
In Chrome at code view, at part "calculated" this <div aria-describedby="tourinfo-description" aria-labelledby="tourinfo-label" role="dialog" tabindex="0" class="shepherd-has-cancel-icon shepherd-has-title shepherd-element shepherd-theme-arrows shepherd-centered shepherd-enabled" data-shepherd-step-id="tourinfo" data-popper-placement="bottom" style="position: fixed;left: 50%;top: 50%;transform: translate(-50%, -50%);height: 90vh;">    block i see with big height - they calc ALL PAGE (i have 50  item in category at one page). Normally height this block must calc only for visible window
P.S.  Edit  media/plg_system_guidedtours/css/guidedtours.css in line 148 add top:30vh!important;  and now i see block with start tour, but next update - and :(
.shepherd-enabled.shepherd-element {
  opacity: 1;
  visibility: visible;
  top:30vh!important; 
}

**Comment by fgsw** [comment]
More than 50 Articles showing: can't conform issue. 

Test on 4.4.3-dev, no 3rd-Party like you have.

**Comment by brianteeman** [comment]
I am unable to replicates this.

**Comment by Quy** [comment]
Closing as non-reproducible.
