### ISSUE TITLE
[4.4] UserFactoryAware and 3rd party extensions

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#42373]
### Steps to reproduce the issue

Forum users are reporting **Issue After Updating to Joomla 4.4.0: "UserFactory not set" Error in ActionlogModel**. See https://forum.joomla.org/viewtopic.php?p=3707474&sid=52962b8597e3e7dd5a757ea2034c440f#p3707474

This looks like a backward compatibility break when a third party extension triggers the Action Log plugin. It would be good to have some sort of fix or an explanation.

### Additional comments

See https://github.com/joomla/joomla-cms/pull/40337

**Comment by richard67** [comment]
@laoneo Could you check this issue? Thanks in advance.

**Comment by laoneo** [comment]
Without a stack trace it is hard to peovide a fix.

**Comment by toivo** [comment]
@laoneo there is one here: https://forum.joomla.org/viewtopic.php?f=812&t=1005011#p3705244<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42373">issues.joomla.org/tracker/joomla-cms/42373</a>.</sub>

**Comment by laoneo** [comment]
It would be interesting to see how the `EasyBlogControllerPosts` class is loading the model. I guess not through `bootComponent()`. If it instantiates the model directly, then it needs to set the factory. Honestly I'm a bit hesitant here to catch that exception directly in the model.

**Comment by ssnobben** [comment]
Hi guys any update & solutions for this one?

**Comment by laoneo** [comment]
Test https://github.com/joomla/joomla-cms/pull/44358.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #44358 . Thanks in advance.
