### ISSUE TITLE
Forgot password fails if there is a space before the e-mail address

### ISSUE THREAD

**Issue by thomaslanger** [joomla/joomla-cms#42374]
### Steps to reproduce the issue

Any Joomla 3, 4 or 5 site. Use the password reset funktion in site/frontend.

1. Insert your e-mail address in the form and add a space at the beginning. E.g. " test@e.mail". You will receive no e-mail.
2. Insert your e-mail address correct in the form and submit. In the e-mail, click on the link and your browser shows the second step with the code filled. Now insert your e-mail address in the form as in 1., with the space at the beginning. If you submit the form you get a notice that the user ist not found.

If you add the space at the end, then you receive the Mail and you can reset the password as expected.

### Expected result

1. receive the e-mail
2. show next step to set Password.

### Actual result

User not found. No E-mail is send or in step #2 you can't reset your password because User not found

### System information (as much as possible)

Testet with Joomla 3.10.12, Joomla! 3.10.13-elts , Joomla! 4.4 and Joomla! 5.0
PHP 8.1
MySQL 5.7 (J3+J4) (mamp)
MariaDB 11.1.2 (J5)

### Additional comments

It seems that the space is not removed and the input is passed on to the database. This results in a SQL query like
SELECT * FROM #__users WHERE LOWER(`email`) = LOWER(" your@input.here")
If you add the space at the end you get 
SELECT * FROM #__users WHERE LOWER(`email`) = LOWER("your@input.here ")
The second query will find your user because MySQL ignores the space.

**All e-mail addresses should be processed with the PHP command trim().**

Why is this important: We have many users who copy/paste their email into forms. Another source of error could be browser autofill.

**Comment by Quy** [comment]
How did you bypassed the browser's email validation?

![42374](https://github.com/joomla/joomla-cms/assets/368084/68b83a65-0b68-4d0d-b447-33e12660ca1d)

**Comment by brianteeman** [comment]
@quy I never see that

**Comment by Quy** [comment]
The input type is `email`. In Firefox and Chrome. i get the tooltip after clicking the Submit button. 

![42374-markup](https://github.com/joomla/joomla-cms/assets/368084/25a0740b-d286-41f5-ac9f-9b94335748b5)

**Comment by brianteeman** [comment]
as shown below I do not see that

![forgot](https://github.com/joomla/joomla-cms/assets/1296369/fa8bec9a-ef3a-4f77-b6e4-d3b4c6c4c152)
