### ISSUE TITLE
[5.0.1-rc1][UX] TinyMCE builder is always displayed with dark skin

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#42378]
### Steps to reproduce the issue

disable darkmode
open options of TinyMCE plugin

### Expected result

TinyMCE is display with light skin
![image](https://github.com/joomla/joomla-cms/assets/66922325/bb486b9f-06c4-45cc-9e7d-5f18e83f7322)

### Actual result

TinyMCE is displayed with dark skin
![image](https://github.com/joomla/joomla-cms/assets/66922325/123be6f6-34c4-4ea7-8c1e-a0f0b30e4c62)

### Additional comments

behavior change with https://github.com/joomla/joomla-cms/pull/42322 @wilsonge

**Comment by bembelimen** [comment]
Hi  @heelc29 ,
did you switch after you called the editor in dark or before you entered the backend?

![grafik](https://github.com/joomla/joomla-cms/assets/1229869/4f011148-14ee-4bba-94d0-1e772e5f3c79)

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/42322

>  Unlike the template which will actually flick over immediately once the OS is changed this will not change until the page is next reloaded.

**Comment by bembelimen** [comment]
Ahh, sorry, found it now.

**Comment by Fedik** [comment]
That happen because `oxide-dark/skin.min.css` override `oxide/skin.min.css`:

https://github.com/joomla/joomla-cms/blob/43a9aab4992d3048e8f2ee5091cd76959fc52acc/layouts/plugins/editors/tinymce/field/tinymcebuilder.php#L64-L65

The builder does not use any code to manage tinymce styles, it added directly to document.

**Comment by wilsonge** [comment]
Yeah we can revert that line I guess. I'd forgotten totally about the tinymce builder. It's not tinymce in anyway - just custom divs and styling to mimic it. So unless we conditionally load the css files in javascript and break CSP we're kinda screwed whatever happens I guess (maybe we can template override - but seems like kinda overkill?)

**Comment by Fedik** [comment]
I have reverted it for now, please test https://github.com/joomla/joomla-cms/pull/42392

**Comment by brianteeman** [comment]
sorry - i missed that this was the plugin setup page
