### ISSUE TITLE
[5.1] Menu item "List Contacts in a Category" wrong categories offered in modal

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#42379]
### Steps to reproduce the issue
Fresh installed Joomla 5.1 without content, only standard categories present.
Category "Uncategorised" in Content has the id 2, category "Uncategorised" in Contacts has the id 4.
Create a menu item "List Contacts in a Category", click on "Select a Category"

### Expected result
The modal opens and the list contains the category "Uncategorised" with id 4

### Actual result
The modal opens and the list contains the category "Uncategorised" with id 2, in frontend you get an error: 404 Category not found

**Comment by Fedik** [comment]
I see, I forgot append `$extension` to the link. In J5.0 it is: https://github.com/joomla/joomla-cms/blob/d38a8ffb0d8f2b4579422fc3d229eb60ffa1b1be/administrator/components/com_categories/src/Field/Modal/CategoryField.php#L102-L106

I will do PR later.

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/42391
