### ISSUE TITLE
Joomla 5.0 + cassiopeia is not valid in https://validator.w3.org/

### ISSUE THREAD

**Issue by xarlien** [joomla/joomla-cms#42380]
### Steps to reproduce the issue

Install fresh Joomla 5.0, install czech language, switch language content to czech (english is off). Do new content in czech language, do thist content in menu as "HOME".

### Expected result

Valid website

### Actual result

Nonvalid website by https://validator.w3.org/ becouse:
Element meta is missing one or more of the following attributes: itemprop, property.
From line 74, column 5; to line 74, column 26
age">↩    <meta content="cs-CZ">↩    ↩

### System information (as much as possible)
clear Joomla 5.0 + czech language 5.0 and Cassiopeia template

### Additional comments

Problem is in /components/com_content/tmpl/article/default.php

**Comment by xarlien** [comment]
Im not i code professional, but this is valid:

<meta property="dc:language" content="cs-CZ"><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42380">issues.joomla.org/tracker/joomla-cms/42380</a>.</sub>

**Comment by xarlien** [comment]
Im not i code professional, but this is valid:

meta property="dc:language" content="cs-CZ"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42380">issues.joomla.org/tracker/joomla-cms/42380</a>.</sub>

**Comment by brianteeman** [comment]
please test #43123
