### ISSUE TITLE
PHP 8.2 Issue by custom field type with custom properties

### ISSUE THREAD

**Issue by liuvz** [joomla/joomla-cms#42382]
### Steps to reproduce the issue

1. Joomla 4.4 or Joomla 5 on PHP 8.2 or PHP 9
2. create an own field type "myfield" on some component "mycomponent"
3. in the custom field xml defination there is a custom property "my_property"
4. the field looks like: <field name="some_name" type="myfield" my_property="some_value" ... />

### Expected result

It works as it usually did on PHP 5.6 / 7 / 8.1

### Actual result

Warnings "Dynamic Properties are deprecated" on PHP 8.2
Fatal Error on PHP 9 

### System information (as much as possible)

Joomla 4.4 or Joomla 5 on PHP 8.2 or PHP 9

### Additional comments

https://php.watch/versions/8.2/dynamic-properties-deprecated
Note that setting a dynamic property from within the __set method is still deprecated.

Unfortunately in the file /libraries/src/Form/FormField.php the dynamic property could exist in the case, which I described before.

**Comment by joomdonation** [comment]
@liuvz Shouldn't you add the missing properties to your custom field class to prevent these warning? The fields from core should work fine. If you see any fields from Joomla core having this issue, please report it back so that It could be fixed

Otherwise, this issue should be closed.

**Comment by liuvz** [comment]
@joomdonation Thank you for your reply. You are right, indeed the properties were not defined in the class of custom field type. I was using the tool component-creator.com, in their program some properties are missing in some of their custom field type classes, I will report the issues to them.
This issue can be closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42382">issues.joomla.org/tracker/joomla-cms/42382</a>.</sub>

**Comment by joomdonation** [comment]
Thanks @liuvz. Closing this issue.
