### ISSUE TITLE
Non-required custom fields have default value

### ISSUE THREAD

**Issue by keep** [joomla/joomla-cms#42397]
### Steps to reproduce the issue
- Add a new custom field with the type 'integer'
- Do not mark it as required. 
- Create an article and check the new field instance

### Actual result
The field generates a dropdown from 1 to 100 or as per the values set for first/last/step. Although it is not required, the form submits with the first option of the dropdown. Essentially, there is no difference whether it is marked as required or not.

The list-type fields produces a similar behavior.

### Expected result

I'm uncertain about the appropriate solution: 
Should there be an empty option as the first choice? Or perhaps an option to somehow remove/disable/not use the custom field for the current article? While, with a list-type field, I can manually add an empty option, it doesn't seem like an elegant solution. 
Moreover, I don't actually need the field's value when I haven't marked it as required, even if it's empty. Perhaps it would be beneficial not to add the record to #__fields_values as well.

### System information (as much as possible)
Joomla 5.0.0
PHP 8.2.12
MariaDB 10.6.15

**Comment by Quy** [comment]
Duplicate #27877

**Comment by Quy** [comment]
Closing as duplicate. Thanks for the report.
