### ISSUE TITLE
Password Strength not taking symbol @ into score

### ISSUE THREAD

**Issue by akfaisel** [joomla/joomla-cms#42394]
### Steps to reproduce the issue
1. Go to Joomla 4 or 5 Registration page - https://docs.joombri.in/login?view=registration
2. Enter the password Qwerty@12 

### Expected result
Password meter is supposed to say **Password accepted**

### Actual result
But getting **Password doesn't meet site's requirements.**

### System information (as much as possible)
This happens with both Joomla 4 and 5.

### Additional comments

In media\system\js\fields\passwordstrength.js, the score is calculated at 
```
score += this.constructor.calc(value, /[$!#?=;:*\-_€%&()`´]/g, this.special, mods);
```
The above line is supposed to include @ symbol
```
score += this.constructor.calc(value, /[@$!#?=;:*\-_€%&()`´]/g, this.special, mods);
```
End users (who use @ for their passwords) are confusing as why the password is not accepted.

**Comment by richard67** [comment]
And without the ‘@‘ it is accepted? I would assume it is not because it simply is too short, regardless of the ‘@‘ .

**Comment by alikon** [comment]
closing as there is a pr #42395
