### ISSUE TITLE
[4.4, 5.0] Mssing Plus icon on the "Add Module to Dashboard Button"

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#42396]
### Steps to reproduce the issue
The "Add a Module to Dashboard Button" does not show a Plus Icon. It is hidden by an inline style.  (Compatibility Plugin?)

Strange enough - this is only on OLINE sites.

### Expected result

On LOCAL sites - win11, xampp the icon is visible 

![grafik](https://github.com/joomla/joomla-cms/assets/1035262/9cb05a44-be83-4292-ac42-afc2769d5658)

### Actual result

ONLINE - different hosters, different sites. different Version: V4.4, 5.0, 5.0.1

![grafik](https://github.com/joomla/joomla-cms/assets/1035262/784b2f9d-d4f8-424a-8a81-08009c530e57)

**Comment by brianteeman** [comment]
1. can you try different browsers to rule out a browser plugin?
2. cant be the compatibility plugin as thats not present in 4.4
3. i cant replicate this on any if my sites local or hosted
4. i notice in the screenshot one is english and the other is german?

**Comment by chmst** [comment]
Good idea - it seems to be a browser plugin - - it is only on Firefox! Really strange - but so we know that it is not Joomla.

Language and Compatiility Plugin are not in scope, I have tested with ifferent langages and with fresh and updated sites.

**Comment by ChristineWk** [comment]
Tried with light mode and dark mode. Can see the plus icon.
Joomla 5.0.0
Joomla 4.4.1-dev
![screen shot 2023-11-24 at 10 44 22](https://issues.joomla.org/uploads/1/8e2b5b6d3371fb60a8257499952843ba.jpg)
![screen shot 2023-11-24 at 10 45 11](https://issues.joomla.org/uploads/1/d224b700de8216f3407a4653cd966cee.jpg)
OT: Strange, wrote a post and uploaded 2 screenshots. under: Preview I don't see anything.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42396">issues.joomla.org/tracker/joomla-cms/42396</a>.</sub>

**Comment by brianteeman** [comment]
it would be good to find out which browser extension is causing the problem. Perhaps there is a valid reason it is doing that and we can take appropriate action.

**Comment by chmst** [comment]
The plus icon is back ... seems that I got a fiirfox hickup. Closing.

**Comment by brianteeman** [comment]
Thanks for updating
