### ISSUE TITLE
Web Links shows 'Undefined variable $userId' above every link

### ISSUE THREAD

**Issue by jrmain** [joomla/joomla-cms#42405]
### Steps to reproduce the issue

1. Upgrade Joomla site with Web Links from 3.x to 4.4.0.
2. Navigate to Web Links on web site.
3. Select a category to list links in that category.

### Expected result
Links are listed, with their descriptions, and work.
No errors or warnings are displayed.

### Actual result
Links are listed, with their descriptions, and work.
However, above every link I see this:
```
Warning: Undefined variable $userId in
/var/www/sitepath/components/com_weblinks/tmpl/category/default_items.php
on line 87
```

### System information (as much as possible)
Ubuntu Linux 18.04.6
Apache
PHP 8.0.29

### Additional comments
Web Links were working fine on the Joomla 3. site.

**Comment by Quy** [comment]
Please post Weblink issues to https://github.com/joomla-extensions/weblinks. Thank you.
