### ISSUE TITLE
Invalid path in the template editor

### ISSUE THREAD

**Issue by ambltsk** [joomla/joomla-cms#42408]
Joomla 4.4.0 (as well as 4.4.1 and 5.0.1) indicates the wrong path in the template editor. Because of this, it is impossible to edit files.

### Steps to reproduce the issue
My actions are as follows: "System" -> "Site Templates", in the drop-down list I select: "Site", then "Cassiopeia Details and Files" and move to the editor. 

### Expected result
Root folders should be specified as "/templates/cassiopeia/" and "/media/templates/site/cassiopeia/".

### Actual result
But in the editor, the root folders are listed as: "/administrator/templates/cassiopeia/" and "/media/templates/administrator/cassiopeia/".

### System information (as much as possible)
PRETTY_NAME="Ubuntu 22.04.2 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.2 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy

PHP 8.1.2-1ubuntu2.14 (cli) (built: Aug 18 2023 11:41:11) (NTS)

Server version: Apache/2.4.52 (Ubuntu)
Server built:   2023-10-26T13:44:44

### Additional comments
When trying to open a file for editing, a message appears that "Source file not found."
Is this a bug? Being treated?

**Comment by fgsw** [comment]
Can't confirm (J 5.0.0):

![Untitled](https://github.com/joomla/joomla-cms/assets/147295380/cec4982a-9702-46c0-a082-1b101eecc951)

**Comment by ambltsk** [comment]
And I have like this
![Снимок](https://github.com/joomla/joomla-cms/assets/43585479/56b0eed3-da17-4f13-9ee4-2215da3c6992)

**Comment by brianteeman** [comment]
There is something seriouslty odd in your install as it is showing the tinymce editor which should not be displayed in that component

**Comment by ambltsk** [comment]
I had other editors disabled because TinyMCE stopped being displayed (remark: it was solved by resetting the browser cache). I turned on the other two editors, but nothing has changed along the way.
![Снимок](https://github.com/joomla/joomla-cms/assets/43585479/aa57a210-fc31-4ded-bbb3-7c12233d324c)

**Comment by ambltsk** [comment]
> Can't confirm (J 5.0.~0~1):

What version of PHP do you have?

**Comment by fgsw** [comment]
> What version of PHP do you have?

 8.1.24 

> Are you using mysql?

mysql  8.0.34-cll-lve 

![sys](https://github.com/joomla/joomla-cms/assets/147295380/72f079bd-1952-44c1-a23c-50885a7af6d3)

**Comment by alikon** [comment]
i'm able to replicate with postgres

![image](https://github.com/joomla/joomla-cms/assets/181681/2ae0f6f9-6ca7-4a98-9789-36f68ea07e14)

**Comment by alikon** [comment]
please test #42569

**Comment by richard67** [comment]
@ambltsk Could you test the mentioned pull request #42569 ? It would be a great help because every pull request needs 2 successful test by humans, and we don't have many testers with PostgreSQL databases. I have already tested it with success, so it needs just one more tester. Thanks in advance.

**Comment by ambltsk** [comment]
Of course, I will test and describe the result in the near future. Now the main job takes up a lot of time. I myself am interested in the performance of joomla with postgres.

**Comment by ambltsk** [comment]
I have tested this change, I confirm it works.
