### ISSUE TITLE
Article - Categories module renders incorrect categories

### ISSUE THREAD

**Issue by petervukovic** [joomla/joomla-cms#42404]
### Steps to reproduce the issue

1. Install fresh Joomla 4.4.4
2. Create a category "Colors" with this structure:

- Colors
  - Blue
    - Baby Blue
    - Sky Blue
  - Green
    - Leaf Green
    - Mint Green

3. Create an "Article - Categories" module with the following setup:

Parent Category: Colors
Category Descriptions: Hide
Number of Articles: Hide
Subcategories: Hide
First Subcategories: All
Maximum Level Depth: 1

### Expected result

The module displays first subcategories only:
- Blue
- Green

### Actual result

The module displays all categories including subcategories as a flat list:

Blue
Baby Blue
Sky Blue
Green
Leaf Green
Mint Green

### System information (as much as possible)

Apache 2.4.54
PHP 8.2
MySQL 5.7.39

![screen shot 2023-11-27 at 12 34 38](https://issues.joomla.org/uploads/1/80974cdd26e2c0f97a8a1d7c63fcd2ab.png)![screen shot 2023-11-27 at 12 34 38](https://issues.joomla.org/uploads/1/a4c4dfc0c6091db0bd66b6e22ca631e5.png)![screen shot 2023-11-27 at 12 34 38](https://issues.joomla.org/uploads/1/c2d277d3da0ab9f86b91176cbf38ff8d.png)

**Comment by brianteeman** [comment]
Bug confirmed

**Comment by alikon** [comment]
solved by #42925
