### ISSUE TITLE
custom files folder / images folder doesn't work under content > media

### ISSUE THREAD

**Issue by jaburio** [joomla/joomla-cms#42411]
### Steps to reproduce the issue
1. install new fresh jos5.0.1 (seen since 5.0.0)
2. create your own custom media dir inside webroot, e. g. "mediatest" and the subdir "img" for images
3. go to system => global configuration => media
4. change "path to files folder" to "mediatest" an "path to images folder" to mediatest/img"
5. save and exit
6. go to content => media

### Expected result
the content of the new custom media dir is shown (empty in the upper case)

### Actual result
the content of the default media dir "/images" is still shown

### System information (as much as possible)
jos5.0.1 (clean and new installed from zip https://downloads.joomla.org/)
php8.1.26 fpm-fcgi 
kernel 5.10.0-25-amd64
10.8.8-MariaDB

### Additional comments
clear cache and log out and in again did not fix it

**Comment by richard67** [comment]
You need to adjust the base folder in the "FileSystem - Local" plugin, too, if your custom folder is not child of the "images" folder.

**Comment by Quy** [comment]
Duplicate  #38965
