### ISSUE TITLE
0 - Call to a member function format() on bool

### ISSUE THREAD

**Issue by ctokepa** [joomla/joomla-cms#42417]
### Steps to reproduce the issue
So there is a bug when trying to set birth date upon registration using Bulgarian language. The date format is wrong. The dates are divided by dots not dashes which causes crash and an error message. This error is not present when setting you main language to English. The problem is in joomla.ini file. The date format in Bulgarian language is wrong. ![screen shot 2023-11-29 at 08 14 05](https://issues.joomla.org/uploads/1/56b2cc571066bc3baea685dbd0b482d3.png)

### Additional comments

![screen shot 2023-11-29 at 08 14 05](https://issues.joomla.org/uploads/1/8c2ee68e1800d5ce7fda63ea5a607326.png)

**Comment by Quy** [comment]
@tecpromotion Can you please help? See related #40364.

**Comment by Hackwar** [comment]
So... Unfortunately I don't understand Bulgarian, so I don't know what has been discussed in the bulgarian forum to the other issue, but I also see that the bulgarian language pack is vastly outdated. I logged into crowdin and proposed a fix to the date as well, but I actually don't know the further process for this. What do we do with this issue? The fix has been put up in crowdin, it is not exactly something in the power of the people who manage the issue tracker... Can we close this issue?

**Comment by tecpromotion** [comment]
I have informed the Bulgarian translator. 
Unfortunately, the last release for Joomla 4 was some time ago and there is no package for Joomla 5 yet.

**Comment by Hackwar** [comment]
I'm closing this issue, since it is rather a problem of the bulgarian translation and not of the CMS itself. Everything we can do in the CMS repo has been done. Thank you for reporting this.

**Comment by marto42** [comment]
Fixed!
I replaced the wrong code at /language/bg-BG/joomla.ini file:
DATE_FORMAT_LC="l, d F Y"
DATE_FORMAT_LC1="l, d F Y"
DATE_FORMAT_LC2="l, d F Y H:i"
DATE_FORMAT_LC3="d F Y"
DATE_FORMAT_LC4="d-m-Y"
DATE_FORMAT_LC5="d-m-Y H:i"
DATE_FORMAT_LC6="d.m.Y H:i:s"
DATE_FORMAT_JS1="d-m-y"
DATE_FORMAT_CALENDAR_DATE="%d.%m.%Y"
DATE_FORMAT_CALENDAR_DATETIME="%d.%m.%Y %H:%M:%S"
DATE_FORMAT_FILTER_DATE="d-m-Y"
DATE_FORMAT_FILTER_DATETIME="d-m-Y H:i:s"

...with orginal code:

DATE_FORMAT_LC="l, d F Y"
DATE_FORMAT_LC1="l, d F Y"
DATE_FORMAT_LC2="l, d F Y H:i"
DATE_FORMAT_LC3="d F Y"
DATE_FORMAT_LC4="Y-m-d"
DATE_FORMAT_LC5="Y-m-d H:i"
DATE_FORMAT_LC6="Y-m-d H:i:s"
DATE_FORMAT_JS1="y-m-d"
DATE_FORMAT_CALENDAR_DATE="%Y-%m-%d"
DATE_FORMAT_CALENDAR_DATETIME="%Y-%m-%d %H:%M:%S"
DATE_FORMAT_FILTER_DATE="Y-m-d"
DATE_FORMAT_FILTER_DATETIME="Y-m-d H:i:s"

And everything work correctly. I should I tell bulgarian translation team to fix it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42417">issues.joomla.org/tracker/joomla-cms/42417</a>.</sub>
