### ISSUE TITLE
Wrong language string MOD_MENU_HELP_SUPPORT_OFFICIAL_LANGUAGE_FORUM

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#42424]
### Steps to reproduce the issue
Click Help in the Home Dashboard.
Have a look at Additional Help, the third line.

### Expected result
The value of "MOD_MENU_HELP_SUPPORT_OFFICIAL_LANGUAGE_FORUM"
Whats is the value? 
MOD_MENU_HELP_SUPPORT_OFFICIAL_LANGUAGE_FORUM="Official Language Forums" ; If you have displayed the specific language forum, use something like "Official French Forum" in your language.
There is a comment in it for translaters?

### Actual result
The comment is also shown in the backend.
When I have a look at the Dutch backend, I do see that the first part shows translated, the comment is shown in English. In Crowdin I don't see the comment.
![screen shot 2023-11-29 at 16 18 42](https://issues.joomla.org/uploads/1/954e4a321a70514daee13e722f9acaa0.jpg)

### System information (as much as possible)
J5

**Comment by brianteeman** [comment]
See #42425
