### ISSUE TITLE
Select button in Images and Links doesn't work

### ISSUE THREAD

**Issue by OldMan-Jakob** [joomla/joomla-cms#42438]
### Steps to reproduce the issue

Hi
I just rebuilt my site with Joomla 5. I transferred the content only using SPTransfer without any problems.
However, today I wrote a new article and in the second tab "Images and Links" I wanted to add a pre-prepared image and the green button to select an image.

### Expected result

A pop-up opens allowing me to select an image stored on the server

### Actual result

Nothing happened when clicking the green select button

### System information (as much as possible)
PHP Built On	Linux b3.tophost.ch 3.10.0-962.3.2.lve1.5.81.el7.x86_64 #1 SMP Wed May 31 10:36:47 UTC 2023 x86_64
Database Type	mysql
Database Version	10.5.23-MariaDB
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	No
PHP Version	8.1.25
Web Server	LiteSpeed
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 5.0.1 Stable [ Kuboresha ] 28-November-2023 16:00 GMT
Joomla Backward Compatibility Plugin	Enabled (classes_aliases:"1", es5_assets:"1")
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36 OPR/105.0.0.0

### Additional comments

My workaround was to copy the path to the image in the images folder and add that in the path-space below the image, and that worked. But the selector button does not.

**Comment by OldMan-Jakob** [comment]
Uncaught DOMException: Failed to execute 'querySelectorAll' on 'Document': '#button-1-Tabs-&-Accordions_editors-xtd_image_modal' is not a valid selector.
    at https://davidjakob.com/media/vendor/bootstrap/js/modal.min.js?5.3.2:1:8310
    at Array.forEach (<anonymous>)
    at https://davidjakob.com/media/vendor/bootstrap/js/modal.min.js?5.3.2:1:8170
3joomla-field-media.min.js?7b9940:4 Uncaught TypeError: this.modalElement.open is not a function
    at JoomlaFieldMedia.show (joomla-field-media.min.js?7b9940:4:4047)

Note: Tabs and Sliders is not used on this page


I am using JCE Editor

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42438">issues.joomla.org/tracker/joomla-cms/42438</a>.</sub>

**Comment by alikon** [comment]
let's close then
