### ISSUE TITLE
tags lose active menu item on selection.

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#4243]
it seems there is possible an issue with tags right now where when you select a tag that has no menu item ( say a single tag on a article ) $active becomes NULL so everything gets confused.
I tried the "show tags" extension and core tags and both have the same result.  This was discovered using joostrap's pressmag template though the same thing happens with base v3.
http://screencast.com/t/tPvPEiLtUsMC shows the error being produced and  http://pastebin.com/pXKFtef8 shows $menu array after clicking.

**Comment by brianteeman** [comment]
@N6REJ Has this been resolved by the PR as @Hackwar suggested. Please test and report back or this issue will be closed automatically in a few weeks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4243">issues.joomla.org/joomla-cms/4243</a>.</sub>

**Comment by brianteeman** [comment]
Closing as per statements above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4243">issues.joomla.org/joomla-cms/4243</a>.</sub>
