### ISSUE TITLE
Joomla 4.4.1 Link wrong to update Package

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#42433]
### Steps to reproduce the issue

If I click on this link:
<img width="892" alt="grafik" src="https://github.com/joomla/joomla-cms/assets/828371/0e398483-f13e-4d3b-a085-1737e4557262">
the same site opens in a new tab.

### Expected result

The update packages downloads should open in a new window

### Actual result
the same site opens in a new tab.

### System information (as much as possible)
Joomla 4.4.x

**Comment by brianteeman** [comment]
that link is a direct download of the package - not a website link

**Comment by coolcat-creations** [comment]
It's not, it's opening the same site in a new tab ?

**Comment by brianteeman** [comment]
Not for me

**Comment by coolcat-creations** [comment]
Probably the link is missing if the update channel is not available as on this site 🤔 it's because of an unknown issue on the hosting that I can't update directly but always have to upload a package

**Comment by brianteeman** [comment]
So this should be closed then?

**Comment by drmenzelit** [comment]
Closing as not confirmed issue

**Comment by coolcat-creations** [comment]
No, why is this closed? It affects sites that have no possibility to update, so a correct link is even more important there?
