### ISSUE TITLE
Class 'Joomla\CMS\Application\CMSApplication' not found after installing directly a plugin from Joomla platform

### ISSUE THREAD

**Issue by sogocoltd** [joomla/joomla-cms#42435]
### Problem identified
Class 'Joomla\CMS\Application\CMSApplication' not found after installing directly a plugin from the Joomla platform.

### Open questions
Any suggestions to fix this issue? I am a newbie so would like to get specific solution steps in detail.
Thanks in advance!

**Comment by brianteeman** [comment]
What was the plugin you installed?
What version of Joomla are you using?

**Comment by brianteeman** [comment]
You have obviously tried to install an extension that is not compatible with your exceedingly old, insecure and unsupported version of Joomla. This site is only for development of new features and solving bugs in supported versions of Joomla. Instead you should go to https://forum.joomla.org and seek help there.

This can be closed here

**Comment by alikon** [comment]
you can disable the plugin via phpmyadmin
