### ISSUE TITLE
[4.4.1] Language .ini file not parsing in v4.4.1 - worked OK in v.4.4.0

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#42432]
### Steps to reproduce the issue

Have a language .ini file with the following string.

PLG_ACCESSMESSAGE="This location must be accessible to PHP.&lt;br/>
Your &lt;i>open_basedir&lt;/i> configuration in &lt;i>php.ini&lt;/i> may restrict this."

### Expected result

Language file parsed OK.

### Actual result

Language file parsed OK in 4.4.0 but not in 4.4.1

Remove the new lineline in the text and language file now parses.

PLG_ACCESSMESSAGE="This location must be accessible to PHP.&lt;br/>Your &lt;i>open_basedir&lt;/i> configuration in &lt;i>php.ini&lt;/i> may restrict this."

### Additional comments

_libraries/src/Language/LanguageHelper.php_
Why has INI_SCANNER_RAW been added to parse_ini_file / parse_ini_string on lines 423, 425?

@parse_ini_file($fileName, false, INI_SCANNER_RAW);

Works in most cases, but got a couple of extensions where it fails to parse the language file.

**Example parses OK**
PLG_ACCESSMESSAGE="This location must be accessible to PHP.&lt;br/>Your &lt;i>open_basedir&lt;/i> configuration in &lt;i>php.ini&lt;/i> may restrict this."

**Exampe does not parse**
PLG_ACCESSMESSAGE="This location must be accessible to PHP.&lt;br/>
Your &lt;i>open_basedir</i> configuration in &lt;i>php.ini</i> may restrict this."

**Comment by bembelimen** [comment]
Please see https://github.com/joomla/joomla-cms/issues/42416.
