### ISSUE TITLE
{4.4.1} multi-line language entries in ini-files incorretly processed, corrupt display 

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#42440]
### Steps to reproduce the issue
Update to joomla 4.4.1 or 5.0.1
check extension's  language displays  

### Actual result
Multi line language entries in ini-files cause corrupted display (only language keys are displayed)

### System information (as much as possible)
Jooml 4.4.1 or Joomla 5.0.1
php 8.2
### Additional comments
If multi-line strings are moved to single line, problem disapears.
I think this is a serious bug e.g. Extensions's displays on backend and frontend are affected and may not fix problem easily.

**Comment by brianteeman** [comment]
see #42416
