### ISSUE TITLE
Patch call to api/index.php/v1/articles/{{articleId}} ignores the Tags IDs

### ISSUE THREAD

**Issue by DonPedro34** [joomla/joomla-cms#42443]
### Steps to reproduce the issue

Update any Article in your system with Patch setting the Tag attribute with the IDs of you choice:

Body Example: 
{"tags": [ 1, 2, 3, 4 ]}

### Expected result

In the result under "data": { "attributes": { "tags":  the ids should now be listed.

### Actual result

Nothing happens, "tags" attribute stays empty or unchanged if you already have other tags IDs added to your Article.

### System information (as much as possible)

System Information
Setting	Value
PHP Built On	Linux dd42202 5.4.0-167-generic #184-Ubuntu SMP Tue Oct 31 09:21:49 UTC 2023 x86_64
Database Type	mysql
Database Version	10.5.22-MariaDB-1:10.5.22+maria~ubu2004-log
Database Collation	utf8mb4_general_ci
Database Connection Collation	utf8mb4_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	Yes
PHP Version	8.1.22
Web Server	Apache
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 5.0.1 Stable [ Kuboresha ] 28-November-2023 16:00 GMT
Joomla Backward Compatibility Plugin	Enabled ()
User Agent	Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36

**Comment by alikon** [comment]
side effect from #42233

**Comment by alikon** [comment]
please test #42486

**Comment by DonPedro34** [comment]
Works thanks.

**Comment by alikon** [comment]
@DonPedro34 
please go to https://issues.joomla.org/tracker/joomla-cms/42486, click on Test this to report your test result as Success

**Comment by DonPedro34** [comment]
Ehm, your link leads to a 404 page.

**Comment by alikon** [comment]
you are right 🤕 
some synch issue has happened on the tracker
