### ISSUE TITLE
[5] Contact versions: Deprecated warning if 'created by'-user is deleted

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#42445]
### Steps to reproduce the issue

1. Create and save a contact by user 'One'
2. delete user 'One'
3. Open the contact created at step 1
4. click its versions-button

### Expected result
No deprecated warning

### Actual result
Deprecated: htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /mnt/data/vhosts/casite-1455743.cloudaccess.net/httpdocs/administrator/components/com_contenthistory/tmpl/history/modal.php on line 103

![deprecated](https://github.com/joomla/joomla-cms/assets/147295380/87c6217e-3c49-44aa-b90c-7d3976b3d005)

### System information (as much as possible)
PHP Built On 	Linux lamp302.cloudaccess.net 3.10.0-962.3.2.lve1.5.81.el6h.x86_64 #1 SMP Wed May 31 12:07:35 UTC 2023 x86_64
Database Type 	mysql
Database Version 	8.0.34-cll-lve
Database Collation 	utf8mb4_general_ci
Database Connection Collation 	utf8mb4_0900_ai_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	Yes
PHP Version 	8.1.24
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 5.0.1 Stable [ Kuboresha ] 28-November-2023 16:00 GMT
Joomla Backward Compatibility Plugin 	Enabled (classes_aliases:"1", es5_assets:"1")
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:120.0) Gecko/20100101 Firefox/120.0

**Comment by chmst** [comment]
Please test #42458
