### ISSUE TITLE
[4.x][5.0] Articles with publish_up > now not shown in frontend article list for users with edit-state permission

### ISSUE THREAD

**Issue by ManuelHu** [joomla/joomla-cms#42452]
### Steps to reproduce the issue
* Create a content category 
* create articles in it, some which are published. some of it with publish_up in the future, and some set to hidden
* Create a user group and grant access to edit and edit-state *for this category only*
* create a category list menu item
* log into the frontend with a user part of the aforementioned group

### Expected result
The list should show all articles (published, hidden, and with published_up > now)

### Actual result
Only the published and hidden articles are shown. The ones with have published_up in the future are not listed

### System information (as much as possible)
* Joomla 4.4.1, 5.0.1
* PHP 8.2
* Template Cassiopeia

### Additional comments
1. By "guessing" the link to an article that is not listed, the user can view the contents and also edit the state, as expected with the edit-state permission. Only the list does not show the articles
3. If a(nother) user has global edit-state access to com_content, all articles are shown

**Comment by richard67** [comment]
Closing as having a pull request. See #42694 .
