### ISSUE TITLE
[4.4] Call to undefined method Joomla\Filesystem\File:getExt() in Joomla 4.4

### ISSUE THREAD

**Issue by sonvnn** [joomla/joomla-cms#42460]
### Steps to reproduce the issue

1. Add this code `echo Joomla\Filesystem\File:getExt('name.jpg');` to your code in Joomla 4.4
2. Go to front-end see issue

### Expected result
Return `jpg` in front-end

### Actual result
Call to undefined method Joomla\Filesystem\File:getExt()
![287413316-217cfc8e-bd98-4180-b439-37fb28a69712](https://github.com/joomla/joomla-cms/assets/3204103/e6a1c424-4f11-4574-ac42-3e5a7efa8eaa)

### System information (as much as possible)
Joomla 4.4.x

**Comment by toivo** [comment]
The actual result is expected behaviour. Use Joomla\CMS\Filesystem\File instead.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42460">issues.joomla.org/tracker/joomla-cms/42460</a>.</sub>

**Comment by sonvnn** [comment]
@toivo Yes I know it. But `Use Joomla\CMS\Filesystem\File` will be deprecated in J6. So I don't want to use it.
![Screen Shot 2023-12-05 at 08 58 04](https://github.com/joomla/joomla-cms/assets/3204103/125aa3d0-a231-457d-8f4c-e371f9c1e2e1)

**Comment by joomdonation** [comment]
It would be nice if the method can be backported to be available on Joomla 4.4.x. But as I know, this is not possible with our policy.

So for the time being, I think you will need to use `Joomla\CMS\Filesystem\File` as @toivo suggested and replace it with `Joomla\Filesystem\File` when you can drop support for Joomla 4.

**Comment by alikon** [comment]
closing as per explanation given
