### ISSUE TITLE
Updating an old component gives "Failed deleting inaccessible file..." for non-existent files

### ISSUE THREAD

**Issue by parapente** [joomla/joomla-cms#42468]
I updated an old site to Joomla 4 and while trying to update an old component I ran across the error message "Failed deleting inaccessible file...". Forcing File::delete to log the file requested for deletion I found that the error was appearing when Joomla tried to remove non-existent files. Path::canChmod returns false if the file doesn't exist so File::delete throws an exception with the above-mentioned message. If a file is requested for deletion and it already doesn't exist, wouldn't be better if the File::delete method returned true?

**Comment by brianteeman** [comment]
surely that would just hide an error.

**Comment by alikon** [comment]
same as #42495
please continue there #42495
