### ISSUE TITLE
Joomla 5.0.1. Failed to install language pack ""

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#42476]
### Steps to reproduce the issue

I made a subdomain like sub.domain.com and exctacted Joomla 5.0.1 installation package there.
htaccess.txt is not yet renamed.
I initiated installation process and all was fine until the step of installing translation packages.

Russian chosen as a language of installation interface and I attempting to install Russian translation package, but get the following error:

<img width="799" alt="Снимок экрана 2023-12-06 в 15 25 45" src="https://github.com/joomla/joomla-cms/assets/3432048/533aeb2e-d636-4deb-8a9b-d2c14c686b13">

<img width="793" alt="Снимок экрана 2023-12-06 в 15 25 38" src="https://github.com/joomla/joomla-cms/assets/3432048/efb8901c-7e58-4dfb-a570-e8c6b545620a">

I attempted to choose another language to make sure it is not the problem related to Russian package, e.g. I chosen German and the issue is the same.
I used Firefox functionality to translate the page into English without leaving the process of installation (to show the community a problem. thus there might be some incorrect terms after machine translation):

<img width="893" alt="Снимок экрана 2023-12-06 в 15 30 25" src="https://github.com/joomla/joomla-cms/assets/3432048/07b49b47-2d20-4ea6-ba6c-a52bd53f618c">

_Failed to install language pack ""_

I skipped installing translation package and see Finishing the installation step:
<img width="961" alt="Снимок экрана 2023-12-06 в 15 28 34" src="https://github.com/joomla/joomla-cms/assets/3432048/9aeee077-483d-47ed-84d1-e7fcf9b9c93a">

Have a look there is still a message "please choose language packages to install" on the next step despite the fact the installing of language packages is the previous step.

Then I returned back,  skipped installing language packages, then returned back to the previous step and repeated this operation few times and finally got this error:
Unknown error deleting the installation folder.

Conclusion:

This issue is not related to translation package. My assumption: 
1. it is problem related to hosting (Hostinger).
2. Perhaps there is some issue in J5.0.1.

**Additional technical information about the environment:**
Joomla 5.0.1
Database Version 10.5.19-MariaDB-cll-lve
PHP Version 8.2.5
Web Server LiteSpeed
WebServer to PHP Interface litespeed

**Comment by drmenzelit** [comment]
Duplicate or similar to #42295 ?

**Comment by Quy** [comment]
Closing as duplicate. Thanks for the report.
