### ISSUE TITLE
Serialization of 'Closure' is not allowed when attempting to send email

### ISSUE THREAD

**Issue by chrisdavenport** [joomla/joomla-cms#42482]
### Steps to reproduce the issue
The problem occurs in the MailerFactory::createMailer method.  This attempts to clone the $defaultConfiguration which is a Registry that includes the data from configuration.php as well as the system DI container.  If this DI container happens to contain an anonymous function (closure) then the clone statement fails with a fatal "Serialization of 'Closure' is not allowed" error.

I'm not sure how you can set up a simple test for this.  In my case I was using League Tactician as a command bus, but that's a lot of code to have to set up for a test.

### Expected result
No fatal error when attempting to send an email.

### Actual result
"Serialization of 'Closure' is not allowed" error.

### System information (as much as possible)
Joomla 4.x
PHP 8.1

### Additional comments
The fix is quite simple.  Just replace

`$configuration = clone $this->defaultConfiguration;`

with

`$configuration = new Registry($this->defaultConfiguration);`

in `/libraries/src/Mail/MailerFactory.php`.  The Registry class itself will produce a copy which safely copies closures.

**Comment by alikon** [comment]
please test #42819
