### ISSUE TITLE
issues.joomla.org/tracker down. Composer dependencies require PHP version >= 8.1.0

### ISSUE THREAD

**Issue by ReLater** [joomla/joomla-cms#42488]
### Steps to reproduce the issue

@ChristineWk reported that https://issues.joomla.org/tracker/ is down with error message

`Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 8.1.0". `

I confirm.

**Comment by fgsw** [comment]
Issue solved.

**Comment by Quy** [comment]
Thanks for the report.

**Comment by ChristineWk** [comment]
Received today the above message again
@ReLater @Quy 
thks.

**Comment by ChristineWk** [comment]
should now work again.
