### ISSUE TITLE
Pagination for articles on author contact page in joomla 3.10.x

### ISSUE THREAD

**Issue by itmagpro** [joomla/joomla-cms#42483]
### What needs to be fixed

Need pagination for articles list on author contact page in joomla 3.10.x.

### Why this should be fixed

In case, when "Count materials view" as All and author have huge items (like 5000 or 50 000 for example), then for display page need lot time and server resource! Show All author materials consume a lot time and server sesource!

### How would you fix it

We how to some can make pagination in default_articles.php template?

### Side Effects expected

Pagination for articles list on author contact page in joomla 3.10.x

### Full description

Hello, Bro!

We have latest joomla 3.10.x

In materials settings we have knob "Author as link", "Show author materials" and "Count materials view" (5/10/20/etc/All)

Author materials links generate as list in template /components/com_contact/views/tmpl/contact/default_articles.php

```
<?php if ($this->params->get('show_articles')) : ?>
<div class="contact-articles">
	<ul class="nav nav-tabs nav-stacked">
		<?php foreach ($this->item->articles as $article) : ?>
			<li>
				<?php echo JHtml::_('link', JRoute::_(ContentHelperRoute::getArticleRoute($article->slug, $article->catid, $article->language)), htmlspecialchars($article->title, ENT_COMPAT, 'UTF-8')); ?>
			</li>
		<?php endforeach; ?>
	</ul>
</div>
<?php endif; ?>
```

but without pagination ;(

In case, when "Count materials view" as All and author have huge items (like 5000 or 50 000 for example), then for display page need lot time and server resource!

I have question: we how to some can make pagination in default_articles.php template?

**Comment by brianteeman** [comment]
Joomla 3.x is no longer supported

**Comment by itmagpro** [comment]
> Joomla 3.x is no longer supported

No right answer! I ask other...

**Comment by Sulpher** [comment]
The idea is good - it is definitely will be useful to make a new layout for com_user component and add pagination on this layout. But it could be actual to do in further versions of Joomla 4/5 if any contributor will decide to do that.

**Comment by rdeutz** [comment]
I have my doubts that this make so much sense. You will only get a long list of articles and if you have 50000 Articles for a user you need a different way of presenting the content to the visitor. Even with a pagination nobody with go thru 100 pages to find an article. You should think about categories or tags or a good search or whatever but not a pagination for the contact page.

I am closing this.
