### ISSUE TITLE
Bug in "Modules: Articles - Latest": Unregistered users can access hidden articles!

### ISSUE THREAD

**Issue by TLBAV** [joomla/joomla-cms#42487]
### Steps to reproduce the issue

Recently I added the "Articles - Latest" module to our front page to display the activity of changed articles. Today we noticed that public users without login can click to the link of an article which is usually available for registered users only. The article opens! This seems to be a heavy bug of that module.

### Expected result

Unregistered users have to log in before the article is displayed.

### Actual result

Article is displayed without login.

### System information (as much as possible)

We are using Joomla 4.3.3

**Comment by TLBAV** [comment]
No, I tested after logging out, then in a private browser tab and then with another browser on another machine.

When logged in the link is the same as in the menu bar and like this:
https://www.mydomain.eu/index.php/menuname/submenuname/articlename

But when logged out the link is like this and directly goes into the real article:
https://www.mydomain.eu/index.php?view=article&id=1234:articlename&catid=2

**Comment by brianteeman** [comment]
Are you sure that you set the article to registered. Not just the menu

**Comment by TLBAV** [comment]
Thank you for the hint! Yes, that's it, the article had been public but the menu had been registered.

Now it's working. Bug closed.
