### ISSUE TITLE
BC issue with Joomla\Filesystem\File::delete()

### ISSUE THREAD

**Issue by Elfangor93** [joomla/joomla-cms#42495]
### Steps to reproduce the issue

Try to delete a non-existent file by execute the following line within Joomla > 4.4:
`$res = \Joomla\Filesystem\File::delete(JPATH_ROOT . 'test.php');`

### Expected result

`$res = true`

### Actual result

PHP Error `Joomla\Filesystem\File::delete: Failed deleting inaccessible file test.php`

### System information (as much as possible)

Wampserver v3.3.1 on Windows 10 (64bit)
Joomla v4.4.1
PHP v8.1.2
MySQL v5.7.37

### Additional comments

The old delete method (`$res = \Joomla\CMS\Filesystem\File::delete(JPATH_ROOT . 'test.php');`) returns true when deleteing a non-existent file. With the new class `\Joomla\Filesystem\File`, a PHP Error is thrown instead. This BC break stops some extension installation scripts from beeing executed correctly.

Example: https://github.com/JoomGalleryfriends/JG4-dev/pull/161

**Comment by Elfangor93** [comment]
I propose eighter to make sure `\Joomla\Filesystem\File::delete()` returns true again when deleteing a non-existent file or change all occurrences of `\Joomla\Filesystem\File::delete()` such that it outputs for example a warning like `Trying to delete file "test.php" but file didn't exist.` instead of throwing an error which end the whole execution and leave a half-installed extension behind.

**Comment by richard67** [comment]
The change from the CMS to the Framework filesystem library was made with PR #40257 .

A simple and I personally think sufficient fix could be to wrap calls to `File::delete()` into an `if (is_file(...))` like it is e.g. proposed here #42088 for 4.4-dev (and already done in 5.0-dev) or at other places.

@Hackwar Any other ideas?

**Comment by alikon** [comment]
> sufficient fix could be to wrap calls to File::delete() into an if (is_file(...)) like it is e.g. proposed here https://github.com/joomla/joomla-cms/pull/42088 for 4.4-dev (and already done in 5.0-dev)

me too i think so

@Elfangor93  can you provide an extensions so we can do some tests ?

**Comment by Elfangor93** [comment]
>can you link an extension so we can do some tests

We came across this issue when trying to update JoomGallery from version 3.6.2 to version 4.0.0. See https://github.com/JoomGalleryfriends/JG4-dev/pull/161#issuecomment-1768409883.

**Steps to reproduce the error with JoomGallery**
1. Setup [Joomla 3.10.12](https://downloads.joomla.org/de/cms/joomla3)
2. Install [JoomGallery 3.6.2](https://www.en.joomgalleryfriends.net/downloads/category/34-component.html) 
3. Update Joomla to 4.4.x using com_joomlaupdate
4. Install [JoomGallery 4.0.0-dev](https://github.com/Elfangor93/JG4-dev/tree/script-uninstallModules)

**Comment by richard67** [comment]
Closing as having a pull request. See #42533 .
