### ISSUE TITLE
[com_finder] showing content plugins shortcodes in the result

### ISSUE THREAD

**Issue by machadoug** [joomla/joomla-cms#42494]
### Steps to Reproduce the Issue

1.  Begin by creating an article containing a content plugin shortcode, such as {loadposition contact}.
2.  Execute the Smart Search Indexer.
3.  Proceed to search for the term "contact."

### Expected Result

The anticipated outcome is to view the plugin's content, specifically the contact module **position**, or alternatively, the removal of the shortcode from the search result.

### Actual Result

Upon searching for "contact," the result displays the shortcode instead of the expected content.

### System Information

Joomla Version: Latest - Joomla 5.

### Additional Comments

Presenting the shortcode to users is currently not meaningful. It would be beneficial to implement a mechanism allowing content plugins to exclude their shortcodes from the search results. Another approach could involve utilizing the process content plugins on the Smart Search results. This can be achieved by incorporating the following code into the file components/com_finder/tmpl/search/default_result.php:

```php
$full_description = HTMLHelper::_('content.prepare', $full_description);
```

**Comment by machadoug** [comment]
Apologies for the confusion; it appears I made an error. In reality, it does work with the loadposition in Joomla 5. I mistakenly tested it with a third-party content plugin, but my initial example involved loadposition. I'll conduct another test and keep you informed of the results.

**Comment by richard67** [comment]
Thanks for checking and reporting back.
