### ISSUE TITLE
RE Joomla 5.0.1

### ISSUE THREAD

**Issue by OodlesJobs** [joomla/joomla-cms#42501]
### Problem identified
I have installed Joomla 5.0.1 on Localhost along with Xampp designed the website. Now everything seems perfect on the Localhost, menu's everything works great, however when i go to FTP onto Host it doesnt work and comes up with The server returned a "500 - Whoops, looks like something went wrong."

If it works perfect on Local host, why would it not work on host!

### Proposed solution
?

### Open questions
Has anyone had this before with Joomla 5/ is it a bug or is this a hosting issue?

**Comment by Quy** [comment]
Please post support questions @ https://forum.joomla.org/. Thanks.
