### ISSUE TITLE
[5.x] Changelog modal colours in dark mode

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#42506]
### Steps to reproduce the issue

The changelog modal is still showing a white background in certain areas in dark mode.

Not sure if there's an easier way to reproduce, other than adding your own changelog: https://docs.joomla.org/Adding_changelog_to_your_manifest_file

### Actual result

![image](https://github.com/joomla/joomla-cms/assets/2019801/f76d722f-5825-4e95-b411-e9c4c4c1dabd)

**Comment by Quy** [comment]
Fixed per #42986.
