### ISSUE TITLE
[5.0.1] Compile error after installation language ps-AF

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#42511]
### Steps to reproduce the issue

1. Installation language ps-AF (Pashto Afghanistan).
2. activate content language ps-AF
3. set ps-AF as default administrator language.

### Expected result
Language work.

### Actual result
System Error Page: ``` Fatal error: Cannot declare class En_GBLocalise, because the name is already in use in /mnt/data/vhosts/casite-1461580.cloudaccess.net/httpdocs/administrator/language/ps-AF/localise.php on line 23```

![Screen Shot 2023-12-14 at 09 11 23](https://github.com/joomla/joomla-cms/assets/147295380/d3a18f85-28db-4840-b3c6-339a4f4b5177)

![Screen Shot 2023-12-14 at 09 13 39](https://github.com/joomla/joomla-cms/assets/147295380/d6f9dff5-fb3b-4158-a367-7859eb4ab432)

### System information (as much as possible)

![Untitled](https://github.com/joomla/joomla-cms/assets/147295380/3c7dd375-0cb2-483b-93ff-137e16ab67dd)

**Comment by alikon** [comment]
should be 

`abstract class Ps_AFLocalise`

**Comment by fgsw** [comment]
The error happen 

1. after activate content language 
2. and set the language to default administrator language.

**Comment by fgsw** [comment]
A mail is send to the Team Coordinator of Pashto Afghanistan - Translation for Joomla 5.x.

**Comment by fgsw** [comment]
As the issue still exist it would be better if ps-AF isn't shown in the backend.

**Comment by fgsw** [comment]
closing as reported in https://github.com/joomla/core-translations/issues/961
