### ISSUE TITLE
[5.1] phpunit update

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42528]
The version of phpunit currently used (9.6) is end of support on Feb 2nd. We can not currently upgrade to the latest stable release (10) as at least one test will need to be updated

**Joomla\Tests\Unit\Libraries\Cms\Session\SessionManagerTest::testDestroySessionsWithFailure**
> The at() matcher has been deprecated. It will be removed in PHPUnit 10. Please refactor your test to not rely on the order in which methods are invoked.

**Comment by rdeutz** [comment]
closing because we have a PR https://github.com/joomla/joomla-cms/pull/43381

**Comment by brianteeman** [comment]
The PR does not solve the issue reported as even with that pr we are still using an out of date and unsupported version of phpunit
