### ISSUE TITLE
Issue with menu type Tagged items, J.4.4.1

### ISSUE THREAD

**Issue by oorzaak** [joomla/joomla-cms#42529]
### Steps to reproduce the issue
Create a new Joomla 4.4.1 site, with no extra extensions or templates installed. Engage SEF urls and make sure they are working correctly (e.g. rename htaccess.txt to .htaccess if necesseary on your server).

In the Tags component, create 2 parent tags, e.g. "Healthcare" and "Money", and create 3 child tags, two of them under the first parent, e.g.  "Healthcare > Covid", "Healthcare > Mental health", and  on under the second parent, e.g. "Money > Taxes". 

Then create two menu items of the type Tagged items. The first menu item is called "Healthcare" and we select the two child tags "Covid" and "Mental health" as cirteria for displaying items on this page. The second menu item is called "Money" and we select the child tag "Taxes".

Create some dummy articles and make sure that alle tags are assigned to one or more articles, with this restriction for clarity of the test: assign only one tag to each article. 

On the menu item Healthcare you will see all articles with one of the child tags of Healthcare assigned, and on the menu item Money you will see articles with the child tag of Money assigned.

Now visit the article detail page of an article has the child tag Covid assigned. In a default Joomla installation the tag Covid will be displayed in the article view and it will be clickable. if not, please enable this. Click the tag, so you are taken to the page: Root/Healthcare/Covid

### Expected result
The page Root/Healthcare/Covid should display only articles that have the tag Covid assigned (this is also the actual result on a live site of ours that is on an earlier version of J.4.x)

### Actual result
The page Root/Healthcare/Covid displays articles that have either child tag of the parent tag Healthcare assigned
When I disable SEF urls the behavior is as expected.

### System information (as much as possible)
Joomla 4.4.1
php 8.1.26
MariaDB 10.5.23
Apache

### Additional comments
At the time of writing I have this test site displaying this issue: https://j441.oorzaak-develop.nl/

**Comment by josefromeo12** [comment]
Absolutely! When discussing Joomla setups or configuring websites, attention to detail is key. Similarly, understanding "Zimeton para que sirve" in the context of health is about recognizing its potential benefits, particularly in addressing blood circulation and microcirculation concerns. Just as organizing tags in Joomla helps streamline content, exploring the purpose of medications like Zimeton contributes to comprehending their potential health advantages, like aiding in circulatory health.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42529">issues.joomla.org/tracker/joomla-cms/42529</a>.</sub>

**Comment by oorzaak** [comment]
Hi, anyone interested in solving this issue, please? I cannot solve it by myself and it is keeping me from updating my live site...

**Comment by RickR2H** [comment]
Closed! Please test PR #42716 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42529">issues.joomla.org/tracker/joomla-cms/42529</a>.</sub>

**Comment by Slava287** [comment]
Hello. https://joomla.stackexchange.com/questions/33641/duplicate-issue-when-using-tags-component-as-a-menu-item Similar problem on joomla 5. Is there a solution?

**Comment by oorzaak** [comment]
Hi, 

I am happily using the patch for J.4 that was made by @RickR2H for this issue.

However, now that I want to upgrade the site to J.5 I see that the issue is present in J.5, like @Slava287 mentioned. And the file components/com_tags/src/Service/Router.php has changed in J.5, so I do not know how to take the patch to J.5.

My questions:

- Is there someone who has the knowledge (and is willing) to make this patch J.5 compatible?
- Would it be possible to make this patch part of the J.5 core code?
