### ISSUE TITLE
[4.x] Child templates doesn't load translations

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#42538]
### Steps to reproduce the issue
* Create a language file in parent template with entries
* Create a language file in child template with the same entries different content
* output the language strings

### Expected result
* child template has the child translations

### Actual result
* child template has the parent translations

**Comment by brianteeman** [comment]
1. which folder are you creating the language file in
2. what is the filename of the child language file
3. if you enable language debug does it show both language files

**Comment by brianteeman** [comment]
I am unable to replicate the error. I have tested with a language file in the main languages/en-GB/tpl_cassiopeia_lang.ini folder and in templates\cassiopeia_lang\language\en-gb\tpl_cassiopeia_lang.ini

**Comment by HLeithner** [comment]
true file is loaded if you name it correctly, but the order is wrong, the parent template overrides the content of the child template.

**Comment by HLeithner** [comment]
strange, in the de debuglist ist the child template file above the parent template file in the list?

**Comment by brianteeman** [comment]
![image](https://github.com/joomla/joomla-cms/assets/1296369/78bfea35-45f9-4c5c-9781-1dac6298b6ee)

**Comment by HLeithner** [comment]
interesting my ordering is different... also I have com_content between child and parent, I will have a look where the problem happens. Closing this for now.
