### ISSUE TITLE
In restricted User Config - can´t go back from categories details

### ISSUE THREAD

**Issue by flow-motion** [joomla/joomla-cms#42539]
### Steps to reproduce the issue

I created a new user, that should be able to post content just in one categorie. So i did a new accesslevel and a new usergroup. set the rightslevels. In backend i now see Articles / Articles Categories and Media. When i go to Categrories and open one of these - there is no "save and close" or even a close button. 

### Expected result
Would´nt it be a good thing to get back to Dashboard?

### Actual result
No Button

### System information (as much as possible)
J 4.4.1

**Comment by dariohill** [comment]
[Drift Hunters](https://drift-hunters2.co) is a great game in the drift racing genre and offers players many hours of entertainment and excitement.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42539">issues.joomla.org/tracker/joomla-cms/42539</a>.</sub>

**Comment by fgsw** [comment]
> set the rightslevels

can you give more information so your issue can reproduced?

**Comment by flow-motion** [comment]
Hi fgsw - Uh - thats some days ago... hell... I did the things, written in the entry post. I really can´t tell you anymore, what was the exact thing i did. I guess i could solve the problem...

**Comment by fgsw** [comment]
@flow-motion Thanks for the information that the issue is solved.
