### ISSUE TITLE
Article Version Compare returns empty "Changes" column though differences exist

### ISSUE THREAD

**Issue by sebastian-lwa** [joomla/joomla-cms#42531]
### Steps to reproduce the issue
- Create Article with some content
- Save article
- Open article again and add some content
- Save article
- Open Versioning, select both versions and compare

### Expected result
- Content shown in columnn "Changes" with changes marked

### Actual result
- Empty column "Changes"

### System information (as much as possible)
Joomla 5.0.1 installation updated from 4.4.1. 

### Additional comments
Article Version comparison worked fine in 4.4.1 before the update
Have enabled debug, cannot see anything strange in the queries list or the log (neither of the Joomla log nor the PHP log of the server)

![screen shot 2023-12-17 at 08 11 31](https://issues.joomla.org/uploads/1/fce355d0e64f7963e714411ae42b6402.png)

**Comment by alikon** [comment]
confirmed

**Comment by brianteeman** [comment]
javascript error

![image](https://github.com/joomla/joomla-cms/assets/1296369/284cadff-9041-489f-8d18-41f9f2de881e)

**Comment by sebastian-lwa** [comment]
Thank you for confirmation, good to know it can be reproduced. I will just wait for this to be fixed in some upcoming build, right?
Cheers, Sebastian<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42531">issues.joomla.org/tracker/joomla-cms/42531</a>.</sub>

**Comment by alikon** [comment]
fixed by #42755
