### ISSUE TITLE
ur-PK installation language pack - all versions

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42549]
This should be removed. There is no data in the metadata so it will never be displayed as an option. No one noticed this because it appears as an empty line at the top of the select.

I have not done a PR to remove it as it looks like it needs to be handled upstream on crowdin or it will keep coming back and will be merged again with no data.

https://github.com/joomla/joomla-cms/blob/291c56513553d56b92d7093b85cadd961add90b1/installation/language/ur-PK/langmetadata.xml#L12-L17

![image](https://github.com/joomla/joomla-cms/assets/1296369/dd3fa0a5-2af1-4574-ad4c-91c63296c2e6)

![image](https://github.com/joomla/joomla-cms/assets/1296369/e7fe1ec0-6d8c-4f88-a299-cf904732ca7f)

cc @tecpromotion

**Comment by brianteeman** [comment]
@tecpromotion there is hardly anything in the language file either. Not really enough to justify its existence

**Comment by dariohill** [comment]
Drift Hunters is a great game in the drift racing genre and offers players many hours of entertainment and excitement.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42549">issues.joomla.org/tracker/joomla-cms/42549</a>.</sub>
