### ISSUE TITLE
[5.0.1] Bad colour contrast in media manager file list 

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#42541]
### Steps to reproduce the issue
Select an element in media, list view. The selected element has schould have color white 

![grafik](https://github.com/joomla/joomla-cms/assets/1035262/5de0973b-ff9b-4a39-a66c-db550f0bfdef)

**Comment by brianteeman** [comment]
should be fixed by adding color:white to https://github.com/joomla/joomla-cms/blob/f8cca4479a19e0238686ef18a62de2774d528dd0/build/media_source/com_media/scss/components/_media-browser.scss#L383

**Comment by Quy** [comment]
Please test PR #42544. Thanks.
