### ISSUE TITLE
robots.txt.dist minor update

### ISSUE THREAD

**Issue by QuotesUK** [joomla/joomla-cms#42543]
### Steps to reproduce the issue
Download and unpack Joomla_5.0.1-Stable-Full_Package.zip
Open robots.txt.dist

### Expected result
Disallow: /component/

### Actual result
not listed

### System information (as much as possible)
Joomla 5.0.1

### Additional comments
/components/ is already listed, this matches the installed directory
Smart Search uses a path of domain.tld/component/finder/search?q=needle
/component/ needs to be added to exclude Smart Search results

**Comment by brianteeman** [comment]
This would not be the correct fix as it would also include any other urls with /component/

The correct fix is for you to create a menu item for the smart search component (it does not have to be a visible menu item)

**Comment by richard67** [comment]
Yes, and for tha menu item you can set the noindex nofollow directive in the menu item parameters.

Closing as expected behavior.
