### ISSUE TITLE
[4.4.1] Mail Templates: Users: New account with self-activation [German] wrong placeholders

### ISSUE THREAD

**Issue by flkoch** [joomla/joomla-cms#42540]
### Steps to reproduce the issue
Go to System > Mail Templates and click on the Users: New account with self-activation template to edit in German language.
In the editor click the buttons to reset to the default contents.

### Expected result
Default contents should include the proper placeholders for username, activation link etc.

### Actual result
Instead of the actual placeholders only %s is displayed.

### System information (as much as possible)
Running the Joomla version 4.4.1 on a FreeBSD shared hosting with PHP8.1.25 on Apache with a MariaDB10.6.15 database. German and English language activated.

### Additional comments
![image](https://github.com/joomla/joomla-cms/assets/18426845/37105aa3-38c9-4b71-b668-527ef8bb9146)

**Comment by brianteeman** [comment]
Unable to replicate

![image](https://github.com/joomla/joomla-cms/assets/1296369/7b047c34-80a0-4ba4-ac20-2300a589e6e6)

**Comment by chmst** [comment]
@flkoch you are shure that your german language files are up to date? And no extensions are active with an own user activation feature

**Comment by flkoch** [comment]
I have updated from Joomla 3 and there is no extension hooked into the user registration. In addition, in the English version the template is reset as it should.
Is there any possibility the update did not replace the German template correctly?
Any help is appreciated, though I now entered the placeholders manually to get an email with helpfull information instead of the %s.

**Comment by brianteeman** [comment]
sounds like you did not update the german language files

**Comment by flkoch** [comment]
I was not aware the language files would not auto update to the latest version after upgrading to Joomla4.
But this seems to be the issue.
Thanks for your help.
