### ISSUE TITLE
Dutch flag not showing on different locations in website front and back

### ISSUE THREAD

**Issue by superknutsel** [joomla/joomla-cms#42548]
### Steps to reproduce the issue
Install a fresh Joomla 4 or 5 website and add the Duth language.

### Expected result
When for example checking the content languages I would expect the Dutch flag to be shown just like the British one.

### Actual result
The image of the flag is not showing. Both in the frontend as in the backend there is no image shown. 
Inspecting the code it shows that the source of the image is empty and just showing src=""
Checked that the image is present and it is.

### System information (as much as possible)
Fresh Joomla 5.0.1 install with PHP 8.2 and MySQLi 8.0.35

**Comment by hans2103** [comment]
@superknutsel please add the screenshot you've added to the Mattermost channel too.

**Comment by brianteeman** [comment]
Can not replicate

![image](https://github.com/joomla/joomla-cms/assets/1296369/7985d8a2-563b-406c-9254-584f786cb4e3)

**Comment by superknutsel** [comment]
Interesting, I will try an install again a different way to see if that makes any difference. It should not but will try to see if we learn something.

**Comment by Quy** [comment]
I can not reproduce it either. Let's close it for now. If/when you have the time to investigate further, this can be addressed. Thanks.
