### ISSUE TITLE
[4.4|5.x] If using filter.state instead of filter.published, deleting an item is not possible

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#42554]
### Steps to reproduce the issue

https://github.com/joomla/joomla-cms/blob/b38856dfec12c0755084e10b66579f18abf4cc6b/libraries/src/MVC/View/ListView.php#L254

only checks for filter.published but since we support (or should replace not sure about the bigger picture) filter.state we also should support it in the ListView.

**Comment by brianteeman** [comment]
That statement can not be correct as we use filter.state in banners, fields, messages and scheduler

**Comment by HLeithner** [comment]
the reason why they work is because non of the joomla core `htmlview` classes extends from the `ListHtmlView` class, they have all a copy of this. The class has been introduced but no one had the time to move our own classes to the new utility class.

**Comment by brianteeman** [comment]
This is a perfect example then of where not using the issue template and/or not giving a detailed post causes confusion and wastes time.

If nothing else the title of the issue is factually incorrect

**Comment by Quy** [comment]
PR #38797

**Comment by brianteeman** [comment]
oh that's too funny. Guess this can be closed then as @HLeithner already created a pr

**Comment by HLeithner** [comment]
yeah sadly it's not funny, your wording remembers me why I don't like to go to the tracker anymore and reduce my engagement. Second which is also not funny is that not many people in joomla care about developers.

thanks @Quy finding my pr...

**Comment by brianteeman** [comment]
thanks for wasting my time
