### ISSUE TITLE
[5.0] After upgrading from 4.4.1 to 5.0.1, update channel is still set to 4.x

### ISSUE THREAD

**Issue by Chaosxmk** [joomla/joomla-cms#42553]
### Steps to reproduce the issue
1. Install fresh Joomla 4.4.1 site
2. Change the update channel from default to the next Joomla
3. Install the update, upgrading to 5.0.1
4. Change the update channel back to default

### Expected result
Since the site now runs Joomla 5, updates and reinstalls should be using Joomla 5.x

### Actual result
The update page states that updates and reinstalls will be using 4.x

**Comment by woluweb** [comment]
I updated 2 J4.4.1 website to J5.0.1 recently
- one last week
- another one a few hours ago

I cannot reproduce your issue.

Indeed on both sites I have the following message on `/administrator/index.php?option=com_joomlaupdate` :

`You are on the "Default" update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (5.x)`

Same message btw
- *before* clicking on the "Check for updates" button
- *after* clicking on it

**Comment by brianteeman** [comment]
it's aggressive caching. 

Same as reported https://github.com/joomla/joomla-cms/issues/36497

**Comment by richard67** [comment]
@Chaosxmk Did you have that issue with a different language than English (GB)? Or also with English (GB)? If only with a different language, then it might need to update that language to a suitable version for Joomla.

**Comment by Chaosxmk** [comment]
I had the issue with the French translation. It's entirely probable that I just hadn't updated the language files or the aggressive caching caused confusion.
