### ISSUE TITLE
Blog Intro Image - class "pull-right" does not work

### ISSUE THREAD

**Issue by gosforth** [joomla/joomla-cms#42564]
For some reason class "pull-right" does not work on first page of the Blog (Intro Image). It only works on article page `<div class="com-content-article item-page">`
It always keeps left

![obraz](https://github.com/joomla/joomla-cms/assets/20846275/ab2b9671-8d66-4c07-8fe7-227d43575f6d)

**Comment by Quy** [comment]
Please use `float-end` per inline hep.

**Comment by Quy** [comment]
Please use https://forum.joomla.org/ for support questions. Thanks.

**Comment by gosforth** [comment]
It does not work. Maybe this is template problem.

**Comment by gosforth** [comment]
I've checked - this is not template problem. Must be something with Joomla 4
