### ISSUE TITLE
Blog intro image class 'float-start' or 'float-end' does not work

### ISSUE THREAD

**Issue by gosforth** [joomla/joomla-cms#42575]
float-end or start class works only for 'Full article image'.
![float](https://github.com/joomla/joomla-cms/assets/20846275/7fd536d3-0a26-4ee0-9629-31f2157bc37d)

**Comment by Quy** [comment]
Which Joomla version and template? Please provide screenshot(s).

**Comment by gosforth** [comment]
Joomla 4,  5.0.1
Article=>Images and links Intro image & Full Article image set to 'float-start'. 
The result: 

![intro-image](https://github.com/joomla/joomla-cms/assets/20846275/6925128d-8758-4fb7-9550-785fdf8149a5)
![article-image](https://github.com/joomla/joomla-cms/assets/20846275/a2831c85-961f-408c-a0ed-c5691d2ede06)

**Comment by Quy** [comment]
Which front-end template are you using as I am not able to reproduce. See screenshot.

It is hard to troubleshoot with your screenshots. It is best to use the Joomla forum for support questions. https://forum.joomla.org/

![42575-float](https://github.com/joomla/joomla-cms/assets/368084/cac744e3-e867-4a89-88b8-b4bb66b0a5ea)
