### ISSUE TITLE
Integer custom field cannot deal with big range of numbers.

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#42579]
### Steps to reproduce the issue
Create an "Integer" custom field.
In its settings set:
First : 10000
Last: 10000000

![Articles-Edit-Field-joomla4-Administration](https://github.com/joomla/joomla-cms/assets/1838041/50700886-609b-4884-9c99-2e0478f8569f)

Now open an article.

### Expected result
Load the article.

### Actual result
Blank page.
The browser hangs as it has to create a big drop-down.

### Additional comments
The drop-down solution is not ideal at all.
1. The admin/user has to scroll a long list, to find a number.
2. It hangs when dealing with big range of numbers (as reported). I faced that many times when i tried to use it for prices.

My suggestion is to replace the drop-down with the [input number](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number). That solves the problems i reported and has all the features of the current "Integer" (min, max, step).

**Comment by brianteeman** [comment]
Just create a text field with a filter integer.

With such a giant range of values no one is going to want to scroll through a list

**Comment by richard67** [comment]
Would be cool if we could have different layouts for that field, like dropdown (which we have now) and slider. For such large ranges a slider could be appropriate.

**Comment by Fedik** [comment]
Using such big range obviously will cause a problem somewhere: or server on client side. it is expected.
For now can use what @brianteeman suggested.

If you just want to ask for new custom field that implement "number" input, then please edit the issue description so it is clear "Feature request", or open a new issue for it.

Thanks.

btw: Joomla already have this field type https://github.com/joomla/joomla-cms/blob/e2170c8a6224ebb6ed754853de0d5e1b97ba1ce9/libraries/src/Form/Field/NumberField.php#L29, but not as custom field.

**Comment by brianteeman** [comment]
BTW the number field is very limited in functionality on safari
https://caniuse.com/input-number

**Comment by sakiss** [comment]
Guys as a developer i can find the way out.
The point of this, is to fix or improve the way it works.
Any range that exceeds 1000 numbers renders it useless and this a very usual real world case.

@brianteeman not sure that i get the safari limitations. As far as i can see any version after 2010 seems to support this.

Anyway, if the release leader wants to fix that, i can create a PR.

**Comment by Quy** [comment]
Please submit PR. It should also fix #27877. Thanks.

**Comment by sakiss** [comment]
I need to get a green flag from the release leader.

**Comment by LadySolveig** [comment]
Sure 🟢 thank you @sakiss 🚀  great if we can also fix the issue @Quy mentioned with your PR.
Many thanks for your willingness.

**Comment by brianteeman** [comment]
> 
> @brianteeman not sure that i get the safari limitations. As far as i can see any version after 2010 seems to support this.
> 

There was an error on the caniuse website that has now been resolved. So no safari issues anymore

**Comment by rdeutz** [comment]
@sakiss do you still wnat to fix the issue?

**Comment by sakiss** [comment]
@rdeutz yes i will create a PR soon.
