### ISSUE TITLE
UserFactory not set in Joomla\Component\Users\Administrator\Model\UserModel

### ISSUE THREAD

**Issue by skurvish** [joomla/joomla-cms#42577]
### Steps to reproduce the issue

Delete a user

### Expected result

User is deleted

### Actual result

error: UserFactory not set in Joomla\Component\Users\Administrator\Model\UserModel

### System information (as much as possible)
J! 5.0.1, php 8.2, runmning on CentOs7

### Additional comments
No idea how/why this started. Below is the stack trace:

1	()	JROOT/libraries/src/User/UserFactoryAwareTrait.php:45
2	Joomla\Component\Users\Administrator\Model\UserModel->getUserFactory()	JROOT/administrator/components/com_users/src/Model/UserModel.php:333
3	Joomla\Component\Users\Administrator\Model\UserModel->delete()	JROOT/libraries/src/MVC/Controller/AdminController.php:152
4	Joomla\CMS\MVC\Controller\AdminController->delete()	JROOT/libraries/src/MVC/Controller/BaseController.php:730
5	Joomla\CMS\MVC\Controller\BaseController->execute()	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
6	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()	JROOT/libraries/src/Component/ComponentHelper.php:361
7	Joomla\CMS\Component\ComponentHelper::renderComponent()	JROOT/libraries/src/Application/AdministratorApplication.php:150
8	Joomla\CMS\Application\AdministratorApplication->dispatch()	JROOT/libraries/src/Application/AdministratorApplication.php:195
9	Joomla\CMS\Application\AdministratorApplication->doExecute()	JROOT/libraries/src/Application/CMSApplication.php:306
10	Joomla\CMS\Application\CMSApplication->execute()	JROOT/administrator/includes/app.php:58
11	require_once()	JROOT/administrator/index.php:32

**Comment by alikon** [comment]
related to #42373

are you using 3rd party extensions ?

**Comment by skurvish** [comment]
Sure, a number of them. Not EasyBlog though. This only started to happen when I moved from J4 to J5. There were no changes to my addons between the 2 versions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42577">issues.joomla.org/tracker/joomla-cms/42577</a>.</sub>

**Comment by alikon** [comment]
fine closing  it for now as not core issue

**Comment by ssnobben** [comment]
Yes have the same issue with EasySocial there can not delete users Joomla 5.0.1.

**An error has occurred.

    0 UserFactory not set in Joomla\Component\Actionlogs\Administrator\Model\ActionlogModel** 

# | Function | Location
-- | -- | --
1 | () | JROOT/libraries/src/User/UserFactoryAwareTrait.php:45
2 | Joomla\Component\Actionlogs\Administrator\Model\ActionlogModel->getUserFactory() | JROOT/administrator/components/com_actionlogs/src/Model/ActionlogModel.php:58
3 | Joomla\Component\Actionlogs\Administrator\Model\ActionlogModel->addLog() | JROOT/administrator/components/com_easysocial/includes/actionlog/actionlog.php:105
4 | SocialActionlog->log() | JROOT/administrator/components/com_easysocial/includes/controller.php:112
5 | EasySocialControllerMain->logAction() | JROOT/administrator/components/com_easysocial/controllers/sefurls.php:42
6 | EasySocialControllerSefUrls->purge() | JROOT/libraries/src/MVC/Controller/BaseController.php:730
7 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/administrator/components/com_easysocial/easysocial.php:114
8 | require_once() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:71
9 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}() | JROOT/libraries/src/Dispatcher/LegacyComponentDispatcher.php:73
10 | Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
11 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/AdministratorApplication.php:150
12 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT/libraries/src/Application/AdministratorApplication.php:195
13 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:306
14 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/administrator/includes/app.php:58
15 | require_once() | JROOT/administrator/index.php:32
