### ISSUE TITLE
Latest two full releases missing files

### ISSUE THREAD

**Issue by Bwsusa** [joomla/joomla-cms#42578]
### Steps to reproduce the issue
extract Joomla 440 and 441 Stable Full zips and compare them to 403
particularly the atum template files.

### Expected result
440 and 441 to the similar file structure as 403 with some changes

### Actual result
440 and 441 are missing files.
template broken, modules missing etc.

### System information (as much as possible)
This was a migration from 3.9.12 to 4.4.1 using the guide.

### Additional comments
i didn't compare the cms just admin and templates as my migration was fubar.

**Comment by alikon** [comment]
i don't know which guide have you followed
the update from 3  to 4 must start from 3.10.x and not from 3.9.x
https://docs.joomla.org/Joomla_3.x_to_4.x_Step_by_Step_Migration
