### ISSUE TITLE
[5.0.1] PHP file layout consistency

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#42589]
### Is your feature request related to a problem? Please describe.
I am currently going through updated file changes. I don't understand the difference between the following layouts (for example, in :
html/com_content/article/default.php lines 93-97
```
        <?php
        if [code here]
        endif;
        ?>
````
 and 98-100

```
        <?php if [code here]
        endif; ?>
```
and similar inconsistencies further on in the file and in other files.

### Describe the solution you'd like
Could the team in charge of this please agree on a house style for this?
Thanks.

**Comment by HLeithner** [comment]
technical it's the same, since we don't have a code style für template files, choose one and be consistent. There are cases where it looks better to use the other form, then it's ok as long as we don't have a definitive codestyle to use.

**Comment by Scrabble96** [comment]
I realise it's technically the same, but it just means that because someone, when changing some other code for a PR, has also changed (for example):
```
<?php if
```` 
to 
```
<?php 
if
```
it's yet another few keystrokes and time required to update the files that would otherwise flag up as a 'changed' file every time if it wasn't updated, and it has to be done manually for every site where there is an override for those files.
