### ISSUE TITLE
[4.x] [5.x] Uninstall language process could be improved

### ISSUE THREAD

**Issue by bembelimen** [joomla/joomla-cms#42596]
### Steps to reproduce the issue
=> Install a language pack (e.g. during installation)
=> Go to ```System => Manage => Extensions```
=> Filter for languages and then try to uninstall one

=> Error message

### Expected result

Better explaination (and a direct link?) that you have to uninstall the package not the language

### Actual result

Just a mention to uninstall the package (which is not there, when you filter for "language")

It's not a "programmer bug" but an UX issue

@jonrz and @crystalenka

**Comment by MacJoom** [comment]
#42602 does not fix this issue

**Comment by richard67** [comment]
Closing as having a pull request. Please test #42607 . Thanks in advance.
