### ISSUE TITLE
[5.0.1] In Menu Item Type / Category Blog Some options don't work as they should

### ISSUE THREAD

**Issue by walturbo** [joomla/joomla-cms#42592]
### Steps to reproduce the issue
- Enable voting in articles
- Create a _Category_ and insert some _Articles_ into it
- Create a new _Menu Item_ and select type _Category Blog_
- Choose the article category we created
- In the _Blog Layout_ tab, in my case, I selected _0 Leading Articles_ and _6 Intro Articles_ in _3 Colums_
- On the _Options_ tab I select _Author_, _Publish Date_ and _Voting_: show
 
<img width="425" alt="options" src="https://github.com/joomla/joomla-cms/assets/4063964/b05fc838-3d94-4ae8-b271-20cfbba234c9">

### Expected result
In the frontend, inside the article, view _Author_, _Publish Date_ and _Voting_

### Actual result
In the frontend, inside the article, I see Author, Publish Date and Voting. But now I also see Author and Publish Date in the Category Blog view (Voting doesn't).

<img width="578" alt="category-blog" src="https://github.com/joomla/joomla-cms/assets/4063964/66179f62-2940-40fb-8eba-07eef619a4dd">

### System information
- Joomla 5.0.1
- PHP 8.3.0
- MySQLi 10.6.15-MariaDB

### Additional comments
I think it is correct to separate the options of the _Article_ view from those of the _Category Blog_ view so that you can choose what to activate and in which view to activate them.

Also, I expected to see voting results within the _Category Blog_ view, but that's not the case. For users, a preview of the Votes can make them click on one Article rather than another.

At this point, Search Engines, with the appropriate markup based on https://schema.org/AggregateRating, would certainly appreciate being able to view the ratings that have been given to an _Article_ even within a _Category Blog_ view.

Other options also behave abnormally, for example if I want to show the _Creation Date_ of the _Article_ it will only work on the _Article_ but not on _Category Blog_.

**Comment by brianteeman** [comment]
Please confirm that this problem exists with the default cassiopeia template and without any template overrides

**Comment by walturbo** [comment]
Ok, I hadn't tried, I was using Helix Ultimate. With Cassiopeia I confirm that the infobox in Category Blog is complete (I also see the stars of the votes) and I confirm that everything works inside the article too.

I will contact the company asking for explanations. Thank you

**Comment by Quy** [comment]
Closing as not a core issue.
