### ISSUE TITLE
[4.x][5.x] text not visual readable (error_login)

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#42600]
### Steps to reproduce the issue

- do not log in to the backend
- visit `https://example.tl/administrator/index.php?option=com_admin&view=sysinfo&format=text`

### Expected result

All text should be visual readable
![image](https://github.com/joomla/joomla-cms/assets/66922325/5559b447-603d-4941-a003-5d4b055019f1)

### Actual result

text not visual readable (white text on white background)
![image](https://github.com/joomla/joomla-cms/assets/66922325/0a58bd66-07bf-4401-86b8-7bf44bc35c04)
![image](https://github.com/joomla/joomla-cms/assets/66922325/82b38acd-a8fb-4dfe-a7b9-d94deadb08cb)

### System information (as much as possible)

J4.4 and J5.x

**Comment by brianteeman** [comment]
Confirmed

**Comment by richard67** [comment]
Closing as having a pull request. Please test #42616 . Thanks in advance.
