### ISSUE TITLE
Plugin\Finder\Content\Extension\Content::onFinderAfterSave() error

### ISSUE THREAD

**Issue by ssnobben** [joomla/joomla-cms#42617]
### Steps to reproduce the issue
Creating a user with registration get this error

**Get error 
Joomla\Plugin\Finder\Content\Extension\Content::onFinderAfterSave(): Argument #1 ($event) must be of type Joomla\CMS\Event\Finder\AfterSaveEvent, Joomla\Event\Event given, called in /libraries/vendor/joomla/event/src/Dispatcher.php on line 454**

### Expected result
No error and process finalise as expected

### Actual result
get stuck there after final step

### System information (as much as possible)
Joomla 5.0.1 PHP 8.1.25
MySQL (PDO) 11.0.4-MariaDB-1:11.0.4+maria~ubu2204 
Caching Disabled Gzip Disabled 

### Additional comments
Want to know if this is correlated related to Joomla 5.0.1 with previous updates or 3pds that causing this error. If there is some old plugins that causing this from Joomla or maybe 3pds. I also have a problem with Finder indexing that never ends finalize but then after I stop it it have done some indexing.

**Comment by Fedik** [comment]
Most likely comes from 3rd extension.
Please try to disable 3rd plugins for Finder, one by one, to find wich plugin cause the error.

**Comment by ssnobben** [comment]
yes I did an it comes from this plugin that cuasing this when enabled:  Plugins: Smart Search - Content

**Comment by Fedik** [comment]
I do not have this error with Plugins: Smart Search - Content.
maybe broken upgrade or still some 3rd extension doing some overview.

Try enable Debug, and then copy full stacktrace of the error.

**Comment by Hackwar** [comment]
Any news about this?

**Comment by Quy** [comment]
Closing for now. This can be reopened if additional info is provided to reproduce the issue. Thanks.

**Comment by ssnobben** [comment]
Yes the solution for  seems working ok now after this fix. This still an issue

`A PHP Exception occurred on your site. Here you can find the stack trace:
Exception Type: TypeError
File: /var/www/www.site.com/plugins/finder/content/src/Extension/Content.php
Line: 175
Message: Joomla\Plugin\Finder\Content\Extension\Content::onFinderAfterSave(): Argument #1 ($event) must be of type Joomla\CMS\Event\Finder\AfterSaveEvent, Joomla\Event\Event given, called in /var/www/www.site.com/libraries/vendor/joomla/event/src/Dispatcher.php on line 454
#0 /var/www/www.site.com/libraries/vendor/joomla/event/src/Dispatcher.php(454): Joomla\Plugin\Finder\Content\Extension\Content->onFinderAfterSave()
#1 /var/www/www.site.com/administrator/components/com_easysocial/includes/compatibility.php(783): Joomla\Event\Dispatcher->dispatch()
#2 /var/www/www.site.com/administrator/components/com_easysocial/includes/cluster/cluster.php(2618): ESDispatcher::trigger()
#3 /var/www/www.site.com/administrator/components/com_easysocial/includes/group/group.php(1744): SocialCluster->save()
#4 /var/www/www.site.com/administrator/components/com_easysocial/models/groups.php(2270): SocialGroup->save()
#5 /var/www/www.site.com/components/com_easysocial/controllers/groups.php(295): EasySocialModelGroups->createGroup()
#6 /var/www/www.site.com/libraries/src/MVC/Controller/BaseController.php(730): EasySocialControllerGroups->store()
#7 /var/www/www.site.com/components/com_easysocial/controllers/controller.php(67): Joomla\CMS\MVC\Controller\BaseController->execute()
#8 /var/www/www.site.com/components/com_easysocial/easysocial.php(100): EasySocialController->execute()
#9 /var/www/www.site.com/libraries/src/Dispatcher/LegacyComponentDispatcher.php(71): require_once('...')
#10 /var/www/www.site.com/libraries/src/Dispatcher/LegacyComponentDispatcher.php(73): Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}()
#11 /var/www/www.site.com/libraries/src/Component/ComponentHelper.php(361): Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch()
#12 /var/www/www.site.com/libraries/src/Application/SiteApplication.php(218): Joomla\CMS\Component\ComponentHelper::renderComponent()
#13 /var/www/www.site.com/libraries/src/Application/SiteApplication.php(261): Joomla\CMS\Application\SiteApplication->dispatch()
#14 /var/www/www.site.com/libraries/src/Application/CMSApplication.php(306): Joomla\CMS\Application\SiteApplication->doExecute()
#15 /var/www/www.site.com/includes/app.php(58): Joomla\CMS\Application\CMSApplication->execute()
#16 /var/www/www.site.com/index.php(32): require_once('...')
#17 {main}
Request information
GET variables
Array
(
)
POST variables
Array
(
    [cid] => Array
        (
            [0] => 21
            [1] => 22
            [2] => 23
            [3] => 24
            [4] => 25
            [5] => 27
            [6] => 28
            [7] => 29
            [8] => 30
            [9] => 31
            [10] => 32
            [11] => 33
            [12] => 301
            [13] => 302
            [14] => 303
            [15] => 305
            [16] => 307
            [17] => 348
        )

    [es-fields-22] => fsafdfafds
    [es-fields-23] => fsafdfafds
    [es-fields-24] => <p>sdfafdsa</p>
<p>&nbsp;</p>
<p>dfafdaf</p>
    [group_type] => 1
    [photo_albums] => 1
    [videos] => 1
    [es-fields-29] => 1
    [es-fields-30] => 1
    [es-fields-32] => Array
        (
            [source] => 
            [path] => 
            [data] => {"top":null,"left":null,"width":null,"height":null}
            [type] => 
            [name] => 
        )

    [es-fields-33] => Array
        (
            [data] => 
            [position] => 
        )

    [group_notification] => 1
    [audios] => 1
    [events] => 1
    [es-fields-305] => 1
    [es-fields-307] => 1
    [conditionalRequired] => 
    [currentStep] => 1
    [task] => store
    [boxchecked] => 0
    [option] => com_easysocial
    [controller] => groups
    [6971a840af41cb316e9de77d732cb821] => 1
)

COOKIE variables

Array
(
    [linkedin_rescue_state] => afc132a6c4a9ced4b1f038e58db46787
    [81dbc6c0e8060ce065ce1f9025ed2ea1] => odhchuege2v13ehq5ei8ear4f7
    [a5e4d6bfa5193f2e9c9d384efe68c1ad] => 4f0g359flmbqt8ccqb75ie44ui
    [_ga_DPYRW84SWK] => GS1.1.1730044634.1.1.1730044678.0.0.0
    [_ga] => GA1.1.1561123787.1730044634
    [visitortime] => 1730044664912
    [cookieconsent_status] => dismiss
    [joomla_user_state] => logged_in
)

REQUEST variables

Array
(
    [cid] => Array
        (
            [0] => 21
            [1] => 22
            [2] => 23
            [3] => 24
            [4] => 25
            [5] => 27
            [6] => 28
            [7] => 29
            [8] => 30
            [9] => 31
            [10] => 32
            [11] => 33
            [12] => 301
            [13] => 302
            [14] => 303
            [15] => 305
            [16] => 307
            [17] => 348
        )

    [es-fields-22] => fsafdfafds
    [es-fields-23] => fsafdfafds
    [es-fields-24] => <p>sdfafdsa</p>
<p>&nbsp;</p>
<p>dfafdaf</p>
    [group_type] => 1
    [photo_albums] => 1
    [videos] => 1
    [es-fields-29] => 1
    [es-fields-30] => 1
    [es-fields-32] => Array
        (
            [source] => 
            [path] => 
            [data] => {"top":null,"left":null,"width":null,"height":null}
            [type] => 
            [name] => 
        )

    [es-fields-33] => Array
        (
            [data] => 
            [position] => 
        )

    [group_notification] => 1
    [audios] => 1
    [events] => 1
    [es-fields-305] => 1
    [es-fields-307] => 1
    [conditionalRequired] => 
    [currentStep] => 1
    [task] => store
    [boxchecked] => 0
    [option] => com_easysocial
    [controller] => groups
    [6971a840af41cb316e9de77d732cb821] => 1
)
SERVER variables
Array
(
    [REDIRECT_HTTP_AUTHORIZATION] => 
    [REDIRECT_HTTPS] => on
    [REDIRECT_SSL_TLS_SNI] => www.site.com
    [REDIRECT_STATUS] => 200
    [HTTP_AUTHORIZATION] => 
    [HTTPS] => on
    [SSL_TLS_SNI] => www.site.com
    [HTTP_HOST] => www.site.com
    [HTTP_USER_AGENT] => Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:131.0) Gecko/20100101 Firefox/131.0
    [HTTP_ACCEPT] => text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/png,image/svg+xml,*/*;q=0.8
    [HTTP_ACCEPT_LANGUAGE] => sv-SE
    [HTTP_ACCEPT_ENCODING] => gzip, deflate, br, zstd
    [HTTP_REFERER] => https://www.site.com//en/what-to-do-grupper/step/1/
    [CONTENT_TYPE] => multipart/form-data; boundary=---------------------------22782878322051455441201297079
    [CONTENT_LENGTH] => 6722
    [HTTP_ORIGIN] => https://www.site.com
    [HTTP_DNT] => 1
    [HTTP_SEC_GPC] => 1
    [HTTP_CONNECTION] => keep-alive
    [HTTP_COOKIE] => linkedin_rescue_state=afc132a6c4a9ced4b1f038e58db46787; 81dbc6c0e8060ce065ce1f9025ed2ea1=odhchuege2v13ehq5ei8ear4f7; a5e4d6bfa5193f2e9c9d384efe68c1ad=4f0g359flmbqt8ccqb75ie44ui; _ga_DPYRW84SWK=GS1.1.1730044634.1.1.1730044678.0.0.0; _ga=GA1.1.1561123787.1730044634; visitortime=1730044664912; cookieconsent_status=dismiss; joomla_user_state=logged_in
    [HTTP_UPGRADE_INSECURE_REQUESTS] => 1
    [HTTP_SEC_FETCH_DEST] => document
    [HTTP_SEC_FETCH_MODE] => navigate
    [HTTP_SEC_FETCH_SITE] => same-origin
    [HTTP_SEC_FETCH_USER] => ?1
    [HTTP_PRIORITY] => u=0, i
    [PATH] => /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    [SERVER_SIGNATURE] => 
    [SERVER_SOFTWARE] => Apache/2.4.52 (Ubuntu)
    [SERVER_NAME] => www.site.com
    [SERVER_ADDR] => xxx.xxx.xxx.xx
    [SERVER_PORT] => 443
    [REMOTE_ADDR] => xxx.xxx.xxx.xx
    [DOCUMENT_ROOT] => /var/www/www.site.com
    [REQUEST_SCHEME] => https
    [CONTEXT_PREFIX] => 
    [CONTEXT_DOCUMENT_ROOT] => /var/www/www.site.com
    [SERVER_ADMIN] => webmaster@site.com
    [SCRIPT_FILENAME] => /var/www/www.site.com/index.php
    [REMOTE_PORT] => 60909
    [REDIRECT_URL] => /en/what-to-do-grupper/step/1/
    [GATEWAY_INTERFACE] => CGI/1.1
    [SERVER_PROTOCOL] => HTTP/1.1
    [REQUEST_METHOD] => POST
    [QUERY_STRING] => 
    [REQUEST_URI] => /en/what-to-do-grupper/step/1/
    [SCRIPT_NAME] => /index.php
    [PHP_SELF] => /index.php
    [REQUEST_TIME_FLOAT] => 1730044680.621
    [REQUEST_TIME] => 1730044680
)
`

**Comment by Hackwar** [comment]
I disagree that this is a Joomla bug. This is triggered by a third party extension and that third party extension on their homepage is only claiming Joomla 4 support.

**Comment by Fedik** [comment]
By looking the trace, it the same as https://github.com/joomla/joomla-cms/issues/43103
The bug is in EasySocial, see linked comment https://github.com/joomla/joomla-cms/issues/43103#issuecomment-2026045805
