### ISSUE TITLE
Com_Search: Class "JEventDispatcher" not found

### ISSUE THREAD

**Issue by peterhulst** [joomla/joomla-cms#42625]
### Steps to reproduce the issue
- Module Search (=com_search) is added
- Perform a search

### Expected result
- the search is found

### Actual result
Error:
0 - Class "JEventDispatcher" not found
Call stack:
JROOT/components/com_search/models/search.php:231
JROOT/libraries/src/MVC/View/AbstractView.php:152
JROOT/components/com_search/views/search/view.html.php:41

### System information (as much as possible)
PHP 8.1.26
10.5.22-MariaDB-cll-lve
Joomla! 4.4.1 Stable [ Pamoja ] 28-November-2023 16:00 GMT

### Additional comments
----

**Comment by toivo** [comment]
The result is expected, because Joomla 4 does not have the class JEventDispatcher. The Search component, com_search is part of Joomla 3 and it is not required in Joomla 4. Joomla 4 uses Smart Search, com_finder. 

It is better to post these types of issues first to the Joomla! forum, https://forum.joomla.org.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42625">issues.joomla.org/tracker/joomla-cms/42625</a>.</sub>

**Comment by ssnobben** [comment]
"The Search component, com_search is part of Joomla 3 and it is not required in Joomla 4. Joomla 4 uses Smart Search, com_finder." hmmm 

Why is it not then removed in Joomla 4 and Joomla 5? 
How can it then be possible to add the "Module Search (=com_search) is added" if it not work in Joomla 4 & 5? If so serious bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42625">issues.joomla.org/tracker/joomla-cms/42625</a>.</sub>

**Comment by ssnobben** [comment]
Maybe releated to issue I have here too https://issues.joomla.org/tracker/joomla-cms/42617<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42625">issues.joomla.org/tracker/joomla-cms/42625</a>.</sub>

**Comment by toivo** [comment]
com_search was decoupled from Joomla 4. Version 4.1.0 is available (not tested): https://github.com/joomla-extensions/search/releases<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42625">issues.joomla.org/tracker/joomla-cms/42625</a>.</sub>

**Comment by peterhulst** [comment]
Hellom
Thanks for all replies.
When: _'The Search component, com_search is part of Joomla 3 and it is not required in Joomla 4. Joomla 4 uses Smart Search, com_finder.'_
it should be removed from the repository. A module which is not working/supported anymore should not be included.
And I reported here in the issue tracker, because it is a (serious) bug and not a forum question.
(remark: thera are more third party Joomla 4 components using JEventDispatcher e.g. JCE; so all these components are getting problems I guess).

Regards,
Peter

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42625">issues.joomla.org/tracker/joomla-cms/42625</a>.</sub>

**Comment by peterhulst** [comment]
Remerk 2: I upgraded from Joomla 3.10. May that's why com_search is there. It is not removed during upgrading.
May be it is an idea to check obsolete modules and remove them.

Regards,
Peter<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42625">issues.joomla.org/tracker/joomla-cms/42625</a>.</sub>

**Comment by peterhulst** [comment]
Remark 3: or offer an update of com_search. The https://raw.githubusercontent.com/joomla-extensions/search/main/manifest.xml does offer version 4.0.1-dev, but that is nog visible in the standard update path.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42625">issues.joomla.org/tracker/joomla-cms/42625</a>.</sub>

**Comment by embar-** [comment]
Proposal to enhance Update procedure: 
- make list of deprecated function (e.g. JEventDispatcher, JRequest)
- prior upgrade test scan all source code of website and inspect modules having obsolete functions
- propose to disable or remove identified modules/plugins/extensions and name/notify them. 
- Additionaly send names with versions to Joomla database to mark these modules as incompatible for upgrade for others (users and developers) to know too; this database could be more reliable source for flagging modules not with warning, but with exact info/problem for no-go of upgrade with them enabled.
- even if user decides not to remove these blamed modules/plugins/extensions, disable them during upgrade.
This would safe head aches of less experienced web admins.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42625">issues.joomla.org/tracker/joomla-cms/42625</a>.</sub>

**Comment by embar-** [comment]
This feature suggested here: https://issues.joomla.org/tracker/joomla-cms/42626<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42625">issues.joomla.org/tracker/joomla-cms/42625</a>.</sub>

**Comment by Hackwar** [comment]
As has been written here, there is an update to com_search which fixes this issue. Closing this issue.
