### ISSUE TITLE
Enhancement of Upgrade: update positions to the closest ones

### ISSUE THREAD

**Issue by embar-** [joomla/joomla-cms#42627]
### Steps to reproduce the issue

Upgrade Joomla 3.10 with Protostar or Beez3 template to Joomla 4.4 default template (Cassiopeia template)

### Expected result

All items/modules (logo, menu, header, footer, side panels) are visible.

### Actual result

Only main content (articles) is visible. menu, header, search, side panels are not visible. You need to re-assign new positions manually for each item/module. 

### System information (as much as possible)

Joomla 3.10 upgrade to Joomla 4.4

### Additional comments

Positions defined for Joomla 3.10 with Protostar or Beez3 template are different from  Joomla 4.4 default template (Cassiopeia template). Please automatically update position's name during upgrade to the closest ones while upgrading from old default template to new default template, e.g.:
- position-0 > search
- position-1 > menu
- position-2 > main-bottom
- position-3 > main-top
- position-7 > sidebar-right
- position-8 > sidebar-left

Joomla3 Protostar positions:
![Joomla3 Protostar positions](https://www.cloudaccess.net/images/multithumb_thumbs/b_700_0_16777215_00_images_protostar_modulemap3.jpg "Joomla3 default template positions") 

Joomla4 Cassiopeia positions:
![Joomla4 Cassiopeia positions](https://docs.joomla.org/images/2/28/J4x-cassiopeia_template_explained_positions.png "Joomla4 default template positions")

**Comment by embar-** [comment]
Corrected Joomla 3.9>3.10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42627">issues.joomla.org/tracker/joomla-cms/42627</a>.</sub>

**Comment by embar-** [comment]
Yes, I actually upgraded from 3.10. Edited description. Anyway, this proposal for upgrade from Joomla 3 to 4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42627">issues.joomla.org/tracker/joomla-cms/42627</a>.</sub>

**Comment by alikon** [comment]
an usefull reading https://docs.joomla.org/Joomla_3.x_to_4.x_Step_by_Step_Migration

**Comment by embar-** [comment]
If you wrote link above regarding fact that Joomla 3 Protostar is not compatible with Joomla 4.x – I understand this. 
But this is cause, way I propose to at least help migrate items/modules to correct positions. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42627">issues.joomla.org/tracker/joomla-cms/42627</a>.</sub>

**Comment by Hackwar** [comment]
I'm sorry, but I will have to decline this new feature. First of all, it isn't exactly trivial to make sure that people are using protostar, haven't modified it and that the module with that position isn't used in any other template. I also don't really like changing content of people without them knowing. However, this would also require a new feature in Joomla 4.4 and 4.4 only has bugfix support at this point. So we wont implement this feature.
