### ISSUE TITLE
[5.x] Padding missing in joomla dialog (frontend)

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#42622]
### Steps to reproduce the issue

open any editor-xtd that opens a modal (article, contact, fields, module, ...)
![image](https://github.com/joomla/joomla-cms/assets/66922325/dd0202e1-f91e-436c-b1ef-ae2f9f8da585)

compare padding of content in the modal between backend and frontend

at least the alert doesn't look pretty

### Expected result

backend:
![image](https://github.com/joomla/joomla-cms/assets/66922325/f1692914-a2c4-4449-9020-a2f0b9b4cff3)
![image](https://github.com/joomla/joomla-cms/assets/66922325/967e6f6a-a11a-456e-8c7d-e81bd3a30236)

### Actual result

frontend:
![image](https://github.com/joomla/joomla-cms/assets/66922325/3b153b5e-4fc5-4d81-a8d5-528246c8e85c)
![image](https://github.com/joomla/joomla-cms/assets/66922325/4b8b8ee0-b961-4e98-b2a7-1842934f1c3f)

### System information (as much as possible)

J5.0.1 (also J5.0.2-rc2)

### Additional comments

This is from J4.4 (frontend) - BS modal
![image](https://github.com/joomla/joomla-cms/assets/66922325/6e6c2b48-3eba-4928-abf6-f0bf37c6533e)

**Comment by Fedik** [comment]
It is fixed for 5.1-dev with one of merged Dialog PRs

**Comment by heelc29** [comment]
Oops, that's right

![image](https://github.com/joomla/joomla-cms/assets/66922325/64522652-2af0-4496-b582-91bb2835de6e)
