### ISSUE TITLE
Enhancement of Upgrade: automatically disable external modules/plugins/extensions having deprecated functions

### ISSUE THREAD

**Issue by embar-** [joomla/joomla-cms#42626]
### Steps to reproduce the issue

1. Have installed Joomla 3.10 with enabled plugins, having incompatibilities in later versions (4, 5), like
- JD Social Share (uses JRequest::getVar)
- Regular Labs (uses JEventDispatcher)
- com_search (uses JEventDispatcher)
- AllediaFramework (uses JEventDispatcher)
2. Do upgrade to Joomla 4.4

### Expected result

Joomla notify these incompatibilities and automatically disable during upgrade if not removed

### Actual result

Incompatible/deprecated functions (e.g. JEventDispatcher, JRequest) from external  modules/plugins/extensions break Joomla after upgrade.

### System information (as much as possible)

Joomla 3.10 upgrade to 4.4

### Additional comments

Proposal to enhance Upgrade procedure:

- Make list of deprecated function (e.g. JEventDispatcher, JRequest).
- Prior upgrade test scan all source code of website and inspect modules having obsolete functions
- Propose to disable or remove identified modules/plugins/extensions and name/notify them.
- Additionally send names with versions to Joomla database to mark these modules as incompatible for upgrade for others (users and developers) to know too; this database could be more reliable source for flagging modules not with warning, but with exact info/problem for no-go of upgrade with them enabled.
- Even if user decides not to remove these blamed modules/plugins/extensions, disable them during upgrade.

**Comment by embar-** [comment]
files having JEventDispatcher function after upgrade from 3.9 to 4.4![screen shot 2024-01-08 at 15 59 59](https://issues.joomla.org/uploads/1/9c6912132aad7afeb00677f58359830d.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42626">issues.joomla.org/tracker/joomla-cms/42626</a>.</sub>

**Comment by alikon** [comment]
before the update there is already a Pre Update check  with information about  extensions compatibility
https://docs.joomla.org/J3.x:Pre-Update_Check

**Comment by embar-** [comment]
Pre Update Check is nice, but it could be improved: 
- It could mark not all external modules/plugins, but separate those who actually has incompatible functions in PHP files.
- It could have one-click button to disable them all, or remove/delete one-by-one<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42626">issues.joomla.org/tracker/joomla-cms/42626</a>.</sub>

**Comment by micker** [comment]
Cool propose !

**Comment by Hackwar** [comment]
Thank you for your proposal, but again, this is not a trivial task to find out if an extension is compatible. We already provided the pre-update-check to give you hints, but the final decision has to be made by the user themselfs. Besides all of that, this would also be a new feature for Joomla 4.4 or even 3.10 and 4.4 is only in bugfix mode and 3.10 isn't supported at all. So because of this, I'm going to have to deny this feature request.
