### ISSUE TITLE
[5.0] Select article for menu item

### ISSUE THREAD

**Issue by hpbdesign1esOG** [joomla/joomla-cms#42621]
### Steps to reproduce the issue

1. Create a new Menu Item for a Single Article
2. Select Article > Select
3. After click on a Article nothing happens

### Expected result

New Article in Inputbox

### Actual result

Nothing happens... the Article is not selectable in the modal

![screen shot 2024-01-06 at 17 17 03](https://issues.joomla.org/uploads/1/419b8c600495cf8dd6c96f7a6ce7c97b.png)

### System information (as much as possible)

Joomla Version: Joomla! 5.0.1 Stable [ Kuboresha ]
PHP Version: 8.2.9
MariaDB Version 10.5.23

**Comment by hpbdesign1esOG** [comment]
i forgott there are no erros in browser console<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42621">issues.joomla.org/tracker/joomla-cms/42621</a>.</sub>

**Comment by fgsw** [comment]
Try without 3rd-Party-Extension (Almy Canonical).

**Comment by hpbdesign1esOG** [comment]
Hi fgsw, thank you I disabled Aimy, but it did not change anything...

**Comment by hpbdesign1esOG** [comment]
Also tried with Aimy uninstalledn no change :(

**Comment by chmst** [comment]
Sorry to insist here, but this is a very important place and we must investigate. I worked today with menus and created several articles from menus, all worked as expected.

@hpbdesign1esOG could you please double check your extensions, if there is any plugin which could have a side effect here? And delete the browser cache?

**Comment by hpbdesign1esOG** [comment]
Hi Christiane, thank you, I did all you asked, but I could not find any issue, i even changed the PHP Version and reinstalled core files, and now I have a testside with the same problem not being able to select an artice for a menu item...

**Comment by Quy** [comment]
Can you reproduce this on a clean installation with no 3rd-party extensions?

**Comment by hpbdesign1esOG** [comment]
Hi Quy, this problem is not in my clean testsite... What else can I do please, it seems that uninstalling all extentions does not fix it :(

**Comment by Quy** [comment]
Sorry this is not the proper channel for support/questions. Please use https://forum.joomla.org/ . If a bug is found, report back here. Thank you.
