### ISSUE TITLE
[4.4.2-rc2-dev] Require Password Reset does not work

### ISSUE THREAD

**Issue by toivo** [joomla/joomla-cms#42628]
### Steps to reproduce the issue
Login to the backend as a member of Super Users. 
Create a new user and turn on the option 'Require Password Reset'.
Login to the frontend as the newly created user.

### Expected result
Cannot proceed without resetting the password.

### Actual result
Can proceed without resetting password.

### System information (as much as possible)
Joomla 4.4.1 on Linux, Joomla 4.4.2-rc2-dev, Joomla 5.0.2-rc2-dev on localhost

### Additional comments
Reported and confirmed at the forum topic https://forum.joomla.org/viewtopic.php?f=811&t=1006461
Previous, still open Issue Tracker item https://github.com/joomla/joomla-cms/issues/38788

**Comment by fgsw** [comment]
Issue confirmed, but why a new issue?

**Comment by toivo** [comment]
To get the bug the attention it requires to get it fixed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42628">issues.joomla.org/tracker/joomla-cms/42628</a>.</sub>

**Comment by alikon** [comment]
i guess this one #40729

**Comment by LadySolveig** [comment]
#38788 #39895

**Comment by brianteeman** [comment]
Just as on the forum - **please** do not "bump" issues in this way

**Comment by bembelimen** [comment]
Thanks for reporting it. Closed as it already exists. Let's continue at the existing issue.
