### ISSUE TITLE
[5.0.2][4.4.2] Filter on core/non-core extensions REGRESSION

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42637]
### Steps to reproduce the issue
Go to extensions manage and filter by core/non-core extensions

![image](https://github.com/joomla/joomla-cms/assets/1296369/b018623f-1c32-4a9d-8721-642e027043f5)

### Expected result
Filtering works

### Actual result
Non-core filter produces zero results
Core filter produces results for the non-core extensions only

### System information (as much as possible)
joomla 5.0.2
tested on muliple sites
Type | version
-- | --
mysql | 8.0.30
mariadb | 10.5.22

### Additional comments
This is caused by the changes in https://github.com/joomla/joomla-cms/pull/42576 which I verified by reverting the changes in that PR

Note I only tested on j5 but as the change was first merged in 4.4 I assume the same problem exists there

cc @richard67

**Comment by richard67** [comment]
Closing as having a pull request. Please test #42638 . It is made for 4.4-dev, but if you can test only with 5.0.2 then apply the change of the PR by manual edit of the one file modified by that PR and test with 5.0.2. Thanks in advance.
