### ISSUE TITLE
[4.4.2 & 5.x bug] Allow User Registration: No - redirection

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#42633]
Hi guys,
when "Joomla Users Manage > Options > User Options > Allow User Registration: No" clicking on the Registration menu item it automatically redirect to the Login page. 

Now, being that a Joomla site OR: 
**A** - It never allow Registrations. In this case the Admin sure has never created a registration menu item
**B** - It temporary not allow registration for different reasons. In this case the Registration page could contain important information useful to show for this temporary disabling.

So, that redirection feature, under the "Allow User Registration: No" condition, should be applied clicking on the Register Button into the Registration page and NOT clicking on the Registration menu item that should continue to work as always.

Do you agree ?

**Comment by joomleb** [comment]
Hi @Braintree ,
Happy new year!

> Not 100% certain I understand but from what I can tell then the answer is no

Please, Why?

**Comment by joomdonation** [comment]
I also do not agree with the suggested change. When you disable user registration, the registration form should not be accessible, not depends on whether you create menu item to link to registration form or not.

For your need, I'm afraid of you will have to implement some override yourself to remove Registration Link from public accessible. I'm closing this issue for now because this is the change would never be implemented in core. Feel free to re-open if you want to discuss more about it.

**Comment by joomleb** [comment]
Hi guys,
I continue to believe that you are not considering the real application use cases of that feature. That is the start point of this suggestion. I mean:

@joomdonation "...When you disable user registration..." - A Joomla site:

**A** - OR It **never** allow Registrations. In this case the Admin _sure has never created a registration menu item_. (Sure to build a Joomla site and to don't use the Registration it is a real silly case, but it could be).

**B** - OR It _**temporary** not allow registration for different reasons._ In this case
- the Registration page could contain important information useful to show for this temporary disabling.
- I should always be able to share the Registration page (while right now sharing the Registration menu item will share the the Login page)

As far as I know, there are no other use cases, Right? If I'm wrong, Please, Which are ?!?
Having said this, the reasoning must start from point B...

@joomdonation "...the registration form should not be accessible..." = Maybe a fine solution could be "to split" the setting feature:
"Joomla Users Manage > Options > User Options > Allow User Registration: Yes / No Never (as it is now, as you are writing, it covers the A case) / No Temporary (as I'm suggesting here for the B case) "

I hope is clear what I wrote, if not, I remain available.
@fgsw Please, What you do not understand exactly?
