### ISSUE TITLE
J!5.0 CodeMirror full screen editing has no background overlay

### ISSUE THREAD

**Issue by jurysystem** [joomla/joomla-cms#42647]
### Steps to reproduce the issue

Open an article in the CodeMirror editor and press F10 for full screen editing

### Expected result

Full page should be masked so only the editor is visible

### Actual result

Background is visible, making full page editing useless

### System information (as much as possible)
J!5.0.2, PHP 8.3

**Comment by getimo** [comment]
Same problem here with same config.

**Comment by brianteeman** [comment]
Please test #42683
