### ISSUE TITLE
[5.1] Languages can not be installed

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42641]
### Steps to reproduce the issue
with [5.1.0 Alpha 2](https://developer.joomla.org/news/923-your-first-glimpse-at-joomla-5-1-0-alpha-2.html) or the current 5.1 branch on github you can not install or update any languages. 

This is because of this line 

`<targetplatform name="joomla" version="5.[0]"/>`

There are **several** problems here
1. The first is the obvious one that the targetplaform needs to be updated
2. The second is that as far as i can remember you have always been able to install a language for an older release if there is not a current one available. That is why we display the following message and do not disable the install button or the re-install button

![image](https://github.com/joomla/joomla-cms/assets/1296369/b9b938b3-0a65-4280-8868-f983892ba17e)

but if you try to install it then you get the wonderfully helpful error message

![image](https://github.com/joomla/joomla-cms/assets/1296369/fb540f96-dd35-4842-9e52-e78431c366b6)

3. If you had language XXv5.0.1 and update Joomla to 5.1 then even if there is a language update XXv5.0.2.9 you can not update to it. But you will still be reminded to update 

![image](https://github.com/joomla/joomla-cms/assets/1296369/06af4339-de20-4cc0-86ab-2f8cb9408918)

![image](https://github.com/joomla/joomla-cms/assets/1296369/8325d3dc-b248-4948-a16d-626db9ab312e)

And the slightly more helpful error message

![image](https://github.com/joomla/joomla-cms/assets/1296369/6150efbf-18cf-46a7-bc17-ccafdbc43d29)

## Summary
Language files are not the same as extensions. There is generally no serious problem if the only one available to uise if from an earlier release.

**Comment by richard67** [comment]
The targetplatform issue (item 1 in the list) seems to be resolved with the merged PR https://github.com/joomla-extensions/pkg_languagepack/pull/109 . E.g. for Belarusian (be-BY) at https://update.joomla.org/language/details5/be-BY_details.xml :
```
<targetplatform name="joomla" version="5.[01]"/>
```

The 2nd item seems to be resolved with with the 1st one. Installing a language works now on 5.1-dev without any problem.

The 3rd item I haven't checked yet, but I would assume it's also resolved.

@brianteeman Could you check?

**Comment by brianteeman** [comment]
it appears to work although I do wonder whats the point in having `version="5.[01]"/>` as someone will need to remember that it needs to be updated every release. Might as well just be for all 5.x versions

**Comment by tecpromotion** [comment]
> it appears to work although I do wonder whats the point in having `version="5.[01]"/>` as someone will need to remember that it needs to be updated every release. Might as well just be for all 5.x versions

It's on my list. Thanks.

**Comment by HLeithner** [comment]
internal documentation should be updated
