### ISSUE TITLE
parent element of JGLOBAL_SHOW_FULL_DESCRIPTION to be same code in Joomla!

### ISSUE THREAD

**Issue by sinahaghparast** [joomla/joomla-cms#42649]
### Steps to reproduce the issue
I search "JGLOBAL_SHOW_FULL_DESCRIPTION" in Joomla!

four file used "JGLOBAL_SHOW_FULL_DESCRIPTION" string...
administrator/components/com_modules/tmpl/module/edit.php
administrator/components/com_plugins/tmpl/plugin/edit.php
administrator/components/com_scheduler/tmpl/task/edit.php
administrator/components/com_templates/tmpl/style/edit.php

each element that used "JGLOBAL_SHOW_FULL_DESCRIPTION", have a parent element with onclick attribute...
It is better that all four files use the same coding style.

### Expected result
Clean code
Uniform code

### Actual result
Easier troubleshooting because it doesn't work in com_templates

**Comment by Quy** [comment]
Please test PR  #42651. Thanks.
