### ISSUE TITLE
Menu >> Menu Assignment >> Assign to Menu Items >> All. Not working

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-cms#42642]
### Steps to reproduce the issue
- Edit any module in the admin area
- Go to Menu Menu Assignment tab
- Select 'Only on the pages selected'
- All items should be ticked on
- Untick one menu item
- Tick on Assign to Menu Items >> All

### Expected result
All menu items should be ticked on

### Actual result
The menu item that was unticked stays unticked

### System information (as much as possible)
 The currently installed Joomla! version is ‎4.4.2

**Comment by brianteeman** [comment]
Is this the same as #41185 ??

**Comment by Quy** [comment]
Closing as duplicate. Thanks for confirming.
