### ISSUE TITLE
Attempt to read property "field_mappings" on null in libraries/src/MVC/View/CategoryFeedView.php

### ISSUE THREAD

**Issue by AlainKnaff** [joomla/joomla-cms#42658]
### Steps to reproduce the issue

access URL such as the following
http://site.lu/language/menu/page.feed?view=category&id=10&type=atom"

### Expected result

Page should be served without any PHP error in the log

### Actual result

PHP message: PHP Warning:  Attempt to read property "field_mappings" on null in .../libraries/src/MVC/View/CategoryFeedView.php on line 50; PHP message: PHP Warning:  Attempt to read property "common" on null in .../libraries/src/MVC/View/CategoryFeedView.php on line 50

### System information (as much as possible)

Joomla 4.4.2
PHP 8.2

**Comment by Hackwar** [comment]
I can not replicate this. It looks rather like your #__content_types table does not contain all necessary data. Can you check that and compare it against a fresh installation?
