### ISSUE TITLE
French Language Bug

### ISSUE THREAD

**Issue by lemarcgagnon** [joomla/joomla-cms#42650]
### Steps to reproduce the issue

Make a bilingual site english and french

### Expected result

that it works but there is a typo in the code :smile: 

administrator/language/fr-CA/localise.php line 23 should read :: abstract class Fr_CALocalise :: not "EN_CA"

### Actual result

after the correction all works

### System information (as much as possible)

joomla 5

### Additional comments

just a type

**Comment by richard67** [comment]
I've notified the Translation Team Coordinator for the French translations.

**Comment by lemarcgagnon** [comment]
I should have mentioned it is for the French Canadian version...

Thanks

Le sam. 13 janv. 2024, 16:30, Richard Fath ***@***.***> a
écrit :

**Comment by richard67** [comment]
> I should have mentioned it is for the French Canadian version... Thanks

Well, the coordinator of the Translation Team is the same for the France and Canada versions.

**Comment by tecpromotion** [comment]
This can and should be fixed in Crowdin.
@richard67 please close this issue.
