### ISSUE TITLE
Syndication module in J4/5 should display an image only just as in J3.

### ISSUE THREAD

**Issue by peterhulst** [joomla/joomla-cms#42664]
### Is your feature request related to a problem? Please describe.

In Joomla 3 it was possible to display an image instead of a text for the syndication.
In Joomla 4/5 you are not able to display an icon only. The class .icon-feed can be overriden with a background image (see additional context) but it is never displayed (no text before </span> possible in: aria-hidden="true"></span>';
Also: in the code for the syndication module  in J4/5 (see additional context) the variable $textClass is mentioned, but it is not set and thus empty.

### Describe the solution you'd like

Modify the syndication code just as in Joomla 3

### Additional context

Possible override for icon-feed:
<style type="text/css">
.icon-feed {
background: url(media/system/images/livemarks.png) no-repeat;
}

Code mod_syndicate: default.php from J4.4.2

$linkText = '<span class="icon-feed m-1" aria-hidden="true"></span>';
$linkText .= '<span ' . $textClass . '>' . (!empty($text) ? $text : Text::_('MOD_SYNDICATE_DEFAULT_FEED_ENTRIES')) . '</span>';

**Comment by brianteeman** [comment]
> In Joomla 4/5 you are not able to display an icon only. 

Yes you can

![image](https://github.com/joomla/joomla-cms/assets/1296369/2ff8f6d5-9dd5-434b-967a-e4bb4b50108a)

![image](https://github.com/joomla/joomla-cms/assets/1296369/0df19f0c-1dbd-4faa-aa36-dfd1e1e16b57)

**Comment by peterhulst** [comment]
Hello,
When display label = No, also no image is displayed.
(a link to an image in the label is not possible).

**Comment by brianteeman** [comment]
I just looked at the module in j3 and the options are exactly the same https://docs.joomla.org/Help310:Extensions_Module_Manager_Syndication_Feeds/en

**Comment by peterhulst** [comment]
The options are indeed the same, but the implementation in J3 is different.
In J3 : system/livemarks.png is added as feed-image, while in J4/5 it isn't.

**Comment by brianteeman** [comment]
I doubt very much that anyone would want to undo that change. To achieve what you want (sorry it wasn't clear before) you can simply do a template override for the module

**Comment by peterhulst** [comment]
Okay Brian, I will  make a template override. Thanks.

**Comment by alikon** [comment]
closing as solvable with template override
