### ISSUE TITLE
Poll System as module should be part of Core Joomla 

### ISSUE THREAD

**Issue by sayfrndship1234** [joomla/joomla-cms#42672]
Poll System as module should be part of Core Joomla - 
I want to add that into Joomla core, can anyone tell me 
- any specific requirements to add it
- are you agree to add it?
Recently I was needed to add poll system, 
but I then realize that there is no core Poll system available,
so I decided to add it to core Joomla, I am already a Joomla contributor, 
but still not experienced with core Joomla addition,
Big win for Joomla over wordpress is that, Joomla does not much rely on third party feature as like wordpress do,
third party can be problem, if third party extension stopped creating future updates, while there is not such issue in core.
Tha's why my request should be accepted.

Thanks

**Comment by brianteeman** [comment]
A poll component used to exist in Joomla but it was removed in 1.6

**Comment by ssnobben** [comment]
hmm is this a wanted needed standard feature for a CMS like Joomla? 

There is some Poll extensions for Joomla and isnt this taking to much efforts for Joomla core developer to maintain this "extra" feature too? I think this is better in hand of the 3pds devs.. here is one Poll comp that can be used, forked and extended for people that need it. https://extensions.joomla.org/extension/sexy-polling-reloaded/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42672">issues.joomla.org/tracker/joomla-cms/42672</a>.</sub>

**Comment by rdeutz** [comment]
The chance to have a poll component added to core is zero. We are trying to reduce the core components and this is special need for just a few people. As we have extensions in the extensions directory for this need I am closing this one.
