### ISSUE TITLE
Tinymce can't type in Text area

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#42674]
### Steps to reproduce the issue

Create or edit an Article

### Expected result
Able to type text

### Actual result
Admin and frontend no cursor unable to type in the text area

### Additional comments
Firefox browser logged in as Super User

**Comment by brianteeman** [comment]
Which version of Joomla?
Which version of php?
Are there any js errors in the console?

**Comment by Webdongle** [comment]
I put the version when I created the issue but don't see that field in github or issues.org.  It's 5.02.  PHP is 8.2.14.
It doesn't happen on localhost but two of us so far  that have experienced on a live Host.  I use ionos and have rarely had problems with their server setups.  But this appears to be specific to something on the sever setup? https://forum.joomla.org/viewtopic.php?f=834&t=1006704

**Comment by Webdongle** [comment]
OK closing as found the problem.  Tinymce stopped working after I installed JCE.  Even though Tinymce is set default editor it will not work when JCE is installed.

**Comment by brianteeman** [comment]
If correct then tha5ts a nasty bug in jce as no extension should break core functionality

**Comment by Webdongle** [comment]
Yes agreed.  Has been confirmed by another tester

>  Installed JCE 2.9.60 and TinyMCE does not work. Looks like JCE 2.9.60 interferes with TinyMCE.
https://forum.joomla.org/viewtopic.php?f=834&t=1006704&p=3712604#p3712604

I have placed a report to JCE admin, hopefully they will fix it soon.

**Comment by Webdongle** [comment]
JCE has an update that fixes the previous JCE error
