### ISSUE TITLE
Joomla! 4.4.2 and 5.0.2 "--cassiopeia-color-hover:" not working anymore

### ISSUE THREAD

**Issue by Splatt3ry** [joomla/joomla-cms#42679]
"--cassiopeia-color-hover:" no longer works in Joomla! 4.4.2 and 5.0.2.
If you move the mouse cursor over a link, the link color no longer changes.
Not even with a completely new "vanilla" installation, without extensions or anything else.

Up to version 4.4.1 and 5.0.1 it still worked.

(Temporary solution)
https://forum.joomla.org/viewtopic.php?f=815&t=1006519

https://forum.joomla.org/viewtopic.php?f=815&t=1004868
(not working anymore in 5/4.X.2)

### Expected result
Link color changes when you move the mouse cursor over it. 

### Actual result
Nothing happens.

### System information (as much as possible)
HOST: IONOS
DB: mySQL 8.0.32 
PHP-Version: 8.2.14

**Comment by brianteeman** [comment]
Probably something to do with the changes made https://github.com/joomla/joomla-cms/pull/42504

**Comment by Quy** [comment]
@RickR2H

**Comment by RickR2H** [comment]
I'll look into it...

**Comment by RickR2H** [comment]
Please test PR #42794<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42679">issues.joomla.org/tracker/joomla-cms/42679</a>.</sub>

**Comment by Splatt3ry** [comment]
Since 4.4.4 and 5.0.1 it's working again. Thank you
