### ISSUE TITLE
[5.x] 404 with SEF and no menu

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42686]
### Steps to reproduce the issue
With SEF on
Create a new category
Create a new article in that category
Create a new Articles - Latest module for that category
On the front end click on the article in the module
Repeat with SEF off

(the module is just used to make it easy to test. the same is true for search results etc)

### Expected result
Article loaded

### Actual result
SEF on - 404
SEF off - Article loaded

**Comment by richard67** [comment]
@brianteeman I assume URL rewriting was off and no `.htaccess` file was used, is that right? If yes, does it also happen with URL rewriting on and an `.htaccess` file?

**Comment by brianteeman** [comment]
.htaccess was present in all tests

**Comment by richard67** [comment]
> .htaccess was present in all tests

@brianteeman And URL rewriting? Was that on or off in Global Config?

**Comment by brianteeman** [comment]
sef on => url rewriting

**Comment by richard67** [comment]
> sef on => url rewriting

@brianteeman No, that's not the same. "Search Engine Friendly URLs (Yes/No)" and "Use URL Rewriting (Yes/No)" are 2 different swictehs in Global Configuration. I assumed that "SEF on" means  "Search Engine Friendly URLs = Yes."

**Comment by brianteeman** [comment]
For the avoidance of doubt these are the two settings I tested with

![image](https://github.com/joomla/joomla-cms/assets/1296369/b2c661e3-ba4c-4ca1-8ac3-797df5e41da0)

![image](https://github.com/joomla/joomla-cms/assets/1296369/7ef5cb44-e959-4321-b14b-31b14a79ac2e)

**Comment by richard67** [comment]
@brianteeman Thanks. Would be maybe worth a test if the issue also happens without URL rewriting (and so without `.htaccess? file), just to rule that out.

**Comment by Hackwar** [comment]
can you check if #42989 solves this?
