### ISSUE TITLE
J5 module articles-categories shows subdirectories when excluded

### ISSUE THREAD

**Issue by nzyeehaa** [joomla/joomla-cms#42680]
### Steps to reproduce the issue
add category >_**products**_
add subcategory >_products_>**_level1_**
add subcategory >_products_>_level1_>_**level2**_
add subcategory >_products_>_**level1a**_
add module _articles-categories_
-set module to show list from **_products_** category
-set subcategories to **_hide_**

### Expected result
subcategory >_products>level1>**level2**_ should not be shown

- level1
- level1a

### Actual result
subcategory >_products>level1>level2_ IS **incorrectly** shown

- level1
- level2
- level1a

### System information (as much as possible)
happens since 4.4 upgrade
happens on 5.0.2
happens on fresh install

### Additional comments
-set module subcategories to **show**
and problem still exists, BUT also shows additional and correct nested list with subcategory
suggesting error is in iteration of categories 

- level1
- - level2
- level2
- level1a

![cat](https://github.com/joomla/joomla-cms/assets/45002354/e0ef70fa-7664-4dca-948b-c0b106c01d2e)

**Comment by ot2sen** [comment]
Why would you expect some of the subcategories from the products category to show and others not, with your setting of hide subcategories from products level?

**Comment by ot2sen** [comment]
Tested it as the report made more sense when thinking twice :) and it surely does return some unexpected results.
Screenshot is from test with all configs on and the two drop items set to All. 
![Test_mod_articles-categories_j5](https://github.com/joomla/joomla-cms/assets/790445/c6b11ab4-29ec-473c-9b6b-b33655eebbc0)

**Comment by richard67** [comment]
Duplicate to #42404 ?

**Comment by alikon** [comment]
solved by #42925
