### ISSUE TITLE
[5.x] Indexer batch size

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42684]
Critical error preventing search

### Steps to reproduce the issue
Go to the Smart search component options and set
- Batch index size - to 5 (just so we can show the bug)
- Enable Logging

Clear the search index
Do a new index

### Expected result
Index runs and completed

### Actual result
Index stops with an "undefined" error after 5 items
`administrator/logs/indexer.php` says
![image](https://github.com/joomla/joomla-cms/assets/1296369/9c448c8e-15fe-4aee-9787-8b6b15567eb7)

Doesnt matter which finder plugins are enabled so that error message is not helpful

Doesnt matter what the batch index size is set to it will always stop after the first batch

### Additional comments
php 8.1
php 8.2
joomla 5.0.2

**Comment by brianteeman** [comment]
![scan](https://github.com/joomla/joomla-cms/assets/1296369/ec56b653-4e8f-463a-8de3-d2fc35ebc1cc)

**Comment by brianteeman** [comment]
Any suggestions how to debug this? It happens 100% time on this live site

**Comment by Hackwar** [comment]
Can you check if this fixes your issue? #42693

**Comment by brianteeman** [comment]
It made no difference. :(

Note that there is no problem when using finder from the CLI

**Comment by Hackwar** [comment]
I can't reproduce it either. If you could open up your browser console and see what the AJAX request returned, we might get a bit wiser.

**Comment by brianteeman** [comment]
Sorry - I completely forgot to check the console

`
XHR finished loading: GET "redacted/administrator/index.php?option=com_finder&tmpl=component&format=json&task=indexer.start&4148e24ac0e4697f439dcf0791759050=1"
`

`
XHR failed loading: GET "redacted/administrator/index.php?option=com_finder&tmpl=component&format=json&task=indexer.batch&4148e24ac0e4697f439dcf0791759050=1"
`

`
GET redacted/administrator/index.php?option=com_finder&tmpl=component&format=json&task=indexer.batch&4148e24ac0e4697f439dcf0791759050=1 net::ERR_HTTP2_PROTOCOL_ERROR
`

**Comment by Hackwar** [comment]
Do you have any additional information in the network tab about the failing AJAX request?

**Comment by brianteeman** [comment]
The network tab just shows the same information

**Comment by Hackwar** [comment]
Without additional information I unfortunately can't help you further.

**Comment by brianteeman** [comment]
No idea what additional information I can provide or how to find it

**Comment by Hackwar** [comment]
Maybe try to see what the result is with debug mode switched on?

**Comment by brianteeman** [comment]
Making some progress - will feedback later

**Comment by Hackwar** [comment]
Any news?

**Comment by brianteeman** [comment]
It was a false dawn. Firefox gave a different error message in the console NS_ERROR_NET_INTERRUPT but apparently that's the normal message for FF when chrome says ERR_HTTP2_PROTOCOL_ERROR

Apache logs did have this extra info but I cant see anything from it
`Invalid status line from script 'index.php': 0, referer: redacted/administrator/index.php?option=com_finder&view=indexer&tmpl=component`

**Comment by brianteeman** [comment]
With a lot of help from scalahosting we located the cause of the problem.
It was a 3pd plugin from @ahotzler https://github.com/ahotzler/plg_content_prismsyntaxhighlighter
