### ISSUE TITLE
Mobile: Problem with Submenu (Navigation) and high-resolution smartphones

### ISSUE THREAD

**Issue by Mich-es** [joomla/joomla-cms#42689]
### Steps to reproduce the issue
Hi, a problem that has been bugging me for a long time :-)
Smartphone (Samsung Galaxy S23 Ultra).
Click posts or cache

### Expected result

The submenu should be visible

### Actual result
The submenu has disappeared and is not visible.

It has moved to the right. You have to swipe to the left to see the menu

![Screenshot_20240122_115856_Firefox](https://github.com/joomla/joomla-cms/assets/58422824/5778cd42-8006-4c0f-8fd1-f0f656302caa)
![Screenshot_20240122_115907_Firefox](https://github.com/joomla/joomla-cms/assets/58422824/09a3c8fb-ebe0-4473-b6c6-1af9c0b7c4de)

### System information (as much as possible)
J5.0.2
PHP 8.2

### Additional comments

I don't know if this is the case with every smartphone - I can't test it. I use FF on my smartphone

**Comment by Quy** [comment]
Please test PR #42728. It is for v4.4 but it will be upmerged to v5.
