### ISSUE TITLE
Reloading intro and full image if I change the article category.

### ISSUE THREAD

**Issue by PetarG-hr** [joomla/joomla-cms#42707]
I often find myself writing an article, not paying attention to which category it's in, setting up the intro and full image, then when I change the category I have to set up the intro and full image again. If I save the article, I can change the category later without any issues, the images remain.

**Comment by brianteeman** [comment]
I am unable to replicate this. Please provide more information on your site,

What version of Joomla?
Which editor are you using?

**Comment by PetarG-hr** [comment]
Joomla latest, TinyMCE, please see pic
![prob4](https://github.com/joomla/joomla-cms/assets/81492410/1097f3f6-00ef-45c8-960c-02d6dd9ccaf1)
![prob3](https://github.com/joomla/joomla-cms/assets/81492410/8442df4f-64db-4a11-a7d5-e7bcc6f835c4)
![prob2](https://github.com/joomla/joomla-cms/assets/81492410/94bd5586-49b1-4481-b24b-0b38e1256c0e)
![prob1](https://github.com/joomla/joomla-cms/assets/81492410/b8700f50-f292-4902-af99-ccfa91fcb026)

**Comment by brianteeman** [comment]
I can see from that screenshot that you have some sort of plugin installed as that is **not** the standard interface for the image field

**Comment by PetarG-hr** [comment]
yes it is ECONA
https://www.firecoders.com/joomla-extensions/econa
I will try with plugin disabled
Thnx

**Comment by Quy** [comment]
Closing as not a core issue.
