### ISSUE TITLE
Segmentation fault when debugging language

### ISSUE THREAD

**Issue by irbian** [joomla/joomla-cms#4270]
#### Steps to reproduce the issue
Segmentation fault when debugging language if there is an overriden string key starting with "_"

**Comment by brianteeman** [comment]
I can no longer replicate this. I assume it has been resolved elsewhere - if that is not the case and yu can provide new instructions to replicate the issue it can always be re-opened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4270">issues.joomla.org/joomla-cms/4270</a>.</sub>

**Comment by infograf768** [comment]
remains an error/missing functionality: debug lang does not take into account the override ini

**Comment by infograf768** [comment]
oops, debug overrides is now fixed
