### ISSUE TITLE
Cassiopeia not compatible with safari

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#42713]
### Steps to reproduce the issue
Brows the site with Safari

### Expected result
Menus work correctly

### Actual result
menus act strangely

### Additional comments

Reported in the forum by wilsonpro
https://forum.joomla.org/viewtopic.php?f=840&t=1006764
And mahaha
https://forum.joomla.org/viewtopic.php?p=3712718#p3712718

**Comment by brianteeman** [comment]
This really needs more information such as which exact version of safari

**Comment by stimpsonjcat** [comment]
It might be related to an issue I reported earlier: https://github.com/joomla/joomla-cms/issues/42439

**Comment by Webdongle** [comment]
Closed in favour of #42439

**Comment by brianteeman** [comment]
it is only related if its with the same old verrsion of safari
