### ISSUE TITLE
Menu item 'Show Page Heading' has no corresponding Article option 

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#42712]
### Steps to reproduce the issue
Look for the Article Option for 'Show Page Heading'

### Expected result
Find it and change to 'Show'

### Actual result
Can't be found

### Additional comments
There is a 'Title' setting in Article Options but that has no affect on displaying the Page Title

https://docs.joomla.org/Help4.x:Menu_Item:_New_Item/en#pagedisplay
>Show. Page Heading. Show the Browser Page Title in the heading of the page (If no optional text entered - will default to value based on the Menu Item Title). The Page heading is usually displayed inside the HTML-tag 'H1'.
Title. Show the Article's Title

**Comment by drmenzelit** [comment]
I don't understand what you are looking for, the Page Heading is set in the menu item not in the article ...

**Comment by Webdongle** [comment]
@drmenzelit
The Page Heading setting defaults to 'Use Global'.  There is no Global setting for Page Heading.

**Comment by Webdongle** [comment]
Ah that's where it is
