### ISSUE TITLE
Missing user in article version list

### ISSUE THREAD

**Issue by stimpsonjcat** [joomla/joomla-cms#42723]
### Steps to reproduce the issue

Set versioning on for articles. Create a new article and save it. Make changes to the article or have an other user with the correct rights make changes. Open the article in the admin and click on the Versions button.

### Expected result

In previous versions of Joomla in the list view of all versions I could see in one glance who altered a version.

### Actual result

Now there's only a date, save state and character count. The name of the user is missing. I have to open the version and scroll down to see who modified that specific version.

### System information (as much as possible)

Joomla 4.4.2
PHP 8.2.15

**Comment by Quy** [comment]
It is visible in the desktop view. This column is configured to not be visible in tablet/mobile views.

![42723](https://github.com/joomla/joomla-cms/assets/368084/a7c8538d-58f8-472b-9ffe-cb10512b523b)

**Comment by Quy** [comment]
Closing as it is related to #42439.
