### ISSUE TITLE
All Menu Items => Select Menu do not works

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#42733]
### Steps to reproduce the problem
Create several menus and several menu items in the menus. Select a menu under "All Menu Items" in the "Select Menu" dropdown.

### Expected result
The selected menu is filtered and only the menu items of this menu appear in the list.
### Actual result
The filter does not work, instead the system displays the error message "The Menu type doesn't exist.".
### System information (as far as possible)
j 5.0.2, php 8.1.27

**Comment by hytsch** [comment]
The problem exists with umlauts in the title (Menü)

**Comment by brianteeman** [comment]
confirmed

**Comment by alikon** [comment]
please test #42738
