### ISSUE TITLE
Media Manager empty

### ISSUE THREAD

**Issue by seamlink-aalves** [joomla/joomla-cms#42731]
I've upgraded to the latest version of Joomla from version 3.x but I no longer can list the image folder content in Media Manager. I'm also using JCE File Manager in articles and it has no problem listing folders and files.

I've checked the response from `index.php?option=com_media&format=json&mediatypes=0,1,2,3&task=api.files&path=local-images:/` but the response is empty. 

In the empty Media Manager I can create and list a folder. It is correctly created in the server. If I do it the other way arround, creating the folder in the server, it is not listed in the Media Manager. I checked the owner and permitions (755) are exactly the same either when creating in the server or creating through Media Manager.

The path to images folder is configured correctly in configurations. My setting is currently "images".

### Steps to reproduce the issue
I navigate to Media Manager and is does not list files or folders

### Expected result
I should see files or folders that are available in the server.

### System information (as much as possible)
Joomla version: 4.4.2
PHP: 8.3.1

**Comment by richard67** [comment]
How did you do the upgrade and from which 3.x starting version exactly?

**Comment by seamlink-aalves** [comment]
The update was done from version 3.10.12 using the update process documented in Joomla site. I had to update the template and several plugins, components and modules to make it work of course. This issue is one that I haven't been able to solve.

**Comment by dgrammatiko** [comment]
> I'm also using JCE File Manager in articles and it has no problem listing folders and files.

Unistall JCE and report back if that solved the problem

**Comment by richard67** [comment]
Is the plugin „Filesystem - Local“ enabled and does it point to the right folder in its configuration options?

**Comment by seamlink-aalves** [comment]
I had previously checked this plugin. It is enabled and points to the correct folder. I also added another path and it shows in the left panel where the tree was supposed to appear. 

Please note that the left panel shows the entry for the image folder, but the right panel is empty.

**Comment by Quy** [comment]
In the browser's developer tools under Network>Response, I assume `data` is empty.

![42731-media-manager](https://github.com/joomla/joomla-cms/assets/368084/248cdd69-914e-4208-9888-bbd1212bb0d0)

**Comment by seamlink-aalves** [comment]
> I've checked the response from index.php?option=com_media&format=json&mediatypes=0,1,2,3&task=api.files&path=local-images:/ but the response is empty.

The response is empty and there is a javascript error trying to do a JSON.parse of an empty or undefined variable.

**Comment by Hackwar** [comment]
Can you see what the response is that the browser gets?

**Comment by seamlink-aalves** [comment]
The request get a status 200 but the reponse is empty.

**Comment by Hackwar** [comment]
Can you enabled debug mode and set error reporting to maximum and see again what it says?

**Comment by Quy** [comment]
> The response is empty and there is a javascript error trying to do a JSON.parse of an empty or undefined variable.
@seamlink-aalves Please post the javascript error.

**Comment by Quy** [comment]
Closing due to no response.
