### ISSUE TITLE
Joomla\Filesystem\Path: Fix incorrect non-empty path check

### ISSUE THREAD

**Issue by sousa9g** [joomla/joomla-cms#42737]
### Steps to reproduce the issue

Uses Joomla\Filesystem\Path::clean() to check for an empty path

### Expected result

It should throw \InvalidArgumentException

### Actual result

No thrown exception

### System information (as much as possible)

We discovered this issue with Joomla 5 when it uses Joomla\Filesystem\Path instead of the old one Joomla\CMS\Filesystem\Path (which worked well)

### Additional comments

As this is an issue with Joomla 5 (and Joomla Framework actually), I am not really sure where to submit this bug report, so I submitted in both joomla-cms and joomla-framework.

https://github.com/joomla-framework/filesystem/pull/63

**Comment by Quy** [comment]
This has to be fixed upstream so closing here. Thanks for the report.
