### ISSUE TITLE
Menu Item "Save as Copy" bug - create something with Menu Item Alias functionality instead of 

### ISSUE THREAD

**Issue by denvarel** [joomla/joomla-cms#42745]
### Steps to reproduce the issue
1 I have opened an menu item, Menu Item Type: Author Listings;
2 I have made changes at Title and alias
3 I have made changes into Author Settings tab - Changed the usergroup 
3 I have used the "save as a copy" button
4 I have published the new menu item

 

### Expected result

To have a new menu element with his own functionality

### Actual result

In frontend a new menu item appears with the new Title but with the same alias as the parent has! The functionality of the new menu item is exactly the same as the item original parent. Basically is 1:1 duplicate of the initial menu item with no changes into alias, page title, etc. The only change is at the displayed menu item name.  I get another menu item named differently but is working like an Menu Item Alias.

### System information (as much as possible)
Joomla 5.0.2
PHP 8.1.27
MySQLi 10.5.23-MariaDB-cll-lve
Caching Disabled 

### Additional comments
I will try to use "save as copy" with different menu item Types. 
If the new menu items will act like a menu aliases as well then i will update this.

**Comment by denvarel** [comment]
I have used the same procedure for an Category Blog type menu element. The result is the one expected: a new menu item with a different category blog is displayed. The alias is as well changed, everything is normal. 

It seems that Author listing meny type is the culprit. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42745">issues.joomla.org/tracker/joomla-cms/42745</a>.</sub>

**Comment by denvarel** [comment]
The creation of a new Menu Item Type: Author Listings have the same buggy functionality. Instead of having it own alias and group filter functionality, is like an alias of the first existing Menu Item Type: Author Listings from the main menu.

Further order change on the menu items order confirms:

The all following Menu Item Type: Author Listings from a menu are having the functionality of the first element, as it is saved in joomla order. Is impossible to create multiple Menu Item Type: Author Listings since all of those are acting as the first one redirect.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42745">issues.joomla.org/tracker/joomla-cms/42745</a>.</sub>

**Comment by brianteeman** [comment]
That menu type is not part of the core joomla install - it must be from an extension you have installed and you should seek support from the developer of that extension

**Comment by denvarel** [comment]
Ups. My bad! 

I have used the JA Purity IV - Joomla 5 package. 

I will check with them.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42745">issues.joomla.org/tracker/joomla-cms/42745</a>.</sub>

**Comment by Quy** [comment]
Closing as not a core issue.
