### ISSUE TITLE
[5.0] Email cloaking is not working

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#42743]
### Steps to reproduce the issue
Add an email address to an article or custom module and add space at end ensure it becomes a live email mailto link
(Only just noticed this as most of my sites use contact forms and don't advertise email addresses)

### Expected result
View the email in front-end page source code and/or with inspector tool and the email should be disguised with JavaScript

### Actual result
It isn't,
but emails are protected in a J4 site that I keep for reference

### System information (as much as possible)
Edit: The "Content - Email Cloaking" plugin is active and set to "As linkable mailto address"

**Comment by brianteeman** [comment]
I can see from both of those screenshots that you are using a template override.

These are screenshots without any template override

Joomla 4
![image](https://github.com/joomla/joomla-cms/assets/1296369/1e28d662-6ca4-4822-8f18-0035f411b0f3)

Joomla 5
![image](https://github.com/joomla/joomla-cms/assets/1296369/14fd06b4-7e29-44a7-aa7a-97118697c633)

**Comment by chmst** [comment]
@Scrabble96 can you check the console, if there is a javascript error?

**Comment by Scrabble96** [comment]
No JS errors.

**Comment by brianteeman** [comment]
You are using template overrides as I have already shown!!

**Comment by Scrabble96** [comment]
Ok. [I can't really see your images any bigger as when I click on them I just get a blank page with the URL https://private-user-images.githubusercontent.com/1296369/30... etc]

I tracked it down. The difference was that I had this in my article default.php code:

```
          <?php echo $this->item->introtext; ?>
          <?php echo $this->item->fulltext; ?>
```
and the new version has this:
```
        <?php echo $this->item->text; ?>
```
Somehow I'd missed that when checking file updates.

**Comment by brianteeman** [comment]
```
          <?php echo $this->item->introtext; ?>
          <?php echo $this->item->fulltext; ?>
```

Yes that is your override and it is why it is breaking. fulltext does not process plugins. Only introtext and text do that. That is true for joomla 4 and joomla 5

But the good news is that I made a pr yesterday that fixes that

**Comment by Scrabble96** [comment]
Great. Thanks.
