### ISSUE TITLE
[4.xxx] {5.xx] plugin> content ->fields  prepare fulltext missing

### ISSUE THREAD

**Issue by angieradtke** [joomla/joomla-cms#42740]
### Steps to reproduce the issue

I have created an override of  an article view to restructure the content.
 I have separated intro and full text and positioned the article image in between.

	<?php echo $this->item->introtext; ?>
	....
	<?php echo LayoutHelper::render('joomla.content.full_image', $this->item); ?>
	...
	<?php echo $this->item->fulltext; ?>

 As a result, the plugin for inserting the custom fields is no longer executed. 
 The reason for this is that it only reacts to  intro  ($item->introtext;) and entire text ($item->text)
Adding a function for   $item->fulltext helps

### Solution
```

 // Prepare the fulltext
              if (property_exists($item, 'text') && strpos($item->fulltext, 'field') !== false) {
            $item->fulltext = $this->prepare($item->fulltext, $context, $item);
        }

**Comment by brianteeman** [comment]
Created the pull request for you #42744

**Comment by angieradtke** [comment]
Thanks Brian  .-)

**Comment by alikon** [comment]
closing as we have a pr #42744
