### ISSUE TITLE
Fr_CA language package has incorrect localise classname

### ISSUE THREAD

**Issue by liamhanks** [joomla/joomla-cms#42742]
### Steps to reproduce the issue
Install clean 5.0.2 with the French Canada language package set as default front-end language.

### Expected result
Website displays in Canadian French.

### Actual result
Error 500 on frontend, and some backend screens (ex., Global Configuration screen).

### System information (as much as possible)

I'm running this loacally on Windows (XAMPP) PHP 8.1.4, MariaDB 10.4.24.

### Additional comments

The error stack trace reveals:

Compile Error: Cannot declare class En_CALocalise, because the name is already in use

C:\xampp\htdocs\betaec\administrator\language\fr-CA\localise.php:23

Changing the abstract classname from En_CALocalise to Fr_CALocalise appears to resolve the issue.

**Comment by brianteeman** [comment]
Please see https://github.com/joomla/joomla-cms/issues/42650

**Comment by Quy** [comment]
Closing per https://github.com/joomla/joomla-cms/issues/42650#issuecomment-1893215364. Thanks Brian!
