### ISSUE TITLE
Tag language error on multilingual sites

### ISSUE THREAD

**Issue by rikaryoo** [joomla/joomla-cms#42751]
Friends, I have 2 multilingual websites, but I noticed that the content tag is not separating the content.

I add the text and tags in Portuguese
I add the text and tags in English

I configure the modules and tag menu to display the tags for the selected language, but they appear all together, I believe that the tags are not being separated in the database, as the texts are.

Joomla 5.0.2 - PHP8.2 - Mysql8

![Captura de tela 2024-02-02 113356](https://github.com/joomla/joomla-cms/assets/139914747/49798773-3871-4913-b09d-b60af702689f)

**Comment by fgsw** [comment]
Is the language filter set to Current?

![Untitled](https://github.com/joomla/joomla-cms/assets/147295380/8090ab8a-38b8-40fa-9d83-931a2efc9c86)

**Comment by rikaryoo** [comment]
Yes, it is marked for current, but even so the tags for different languages are getting mixed up.

Both the menu and the tag module were created for each language as recommended by the Joomla documentation. and I noticed that this happens in Joomla 5

I noticed this behavior after upgrading from Joomla 4 to 5.

**Comment by fgsw** [comment]
Have you test without 3rd-Party-Extensions?

**Comment by rikaryoo** [comment]
I used Joomla5 with Cassiopeia and got the same error, I looked in the logs for something out of the ordinary and everything was fine, nothing related to Tags.

**Comment by fgsw** [comment]
Maybe you get more response at [forum](https://forum.joomla.org/).

**Comment by rikaryoo** [comment]
> Maybe you get more response at [forum](https://forum.joomla.org/).

I posted it with the intention of checking whether it was a bug or not.

Thanks

**Comment by fgsw** [comment]
Can you please to close it here? If its a bug, please reopen it with a link to the forum-thread, thanks.
