### ISSUE TITLE
Add ability to minimise Accessibility Options icon.

### ISSUE THREAD

**Issue by Moosites** [joomla/joomla-cms#42753]
### Is your feature request related to a problem? Please describe.
I enable the accessibility plugin on every site but giving users who don't need it the option to minimise it would be nice. Perhaps even users who DO need and use it might like to minimise the icon once their selections have been made thus reducing the distraction the icon causes when using the site.

### Describe the solution you'd like
An additional option in the menu to minimise the icon.

### Additional context
The accessibility plugin is an excellent move by Joomla. I don't see the ability to minimise it as 'fixing a problem' more like enhancing a progressive solution.
![active](https://github.com/joomla/joomla-cms/assets/158487492/256f59f0-b8af-4087-a94a-bde4c61ab745)
![menu](https://github.com/joomla/joomla-cms/assets/158487492/34b714f9-5148-45cc-b54d-32b023f78c34)
![minimised](https://github.com/joomla/joomla-cms/assets/158487492/58721d61-05d2-4a7a-9660-0860f544f49f)

**Comment by Quy** [comment]
This will be implemented in #43143.
