### ISSUE TITLE
Password being send with new user mail despite "user" option "send password" being "no"

### ISSUE THREAD

**Issue by phunsoft** [joomla/joomla-cms#42750]
### Steps to reproduce the issue
Set user option:
System -> Global Configuration -> Users -> Send Password = NO

Add new user, fillout fields including password. Hit "save & close"

### Expected result
Mail being sent to new user, but password NOT being included in the mail due to the configuration setting:

System -> Global Configuration -> Users -> Send Password = NO

### Actual result
Mail sent to new user AND password is shown in mail.

### System information (as much as possible)
Fresh Joomla 4.4.2 installation on Linux server
Template: Cassiopeia 
PHP 8.1.26
MySQL 8.0.32

### Additional comments

Passwords shold never ever be sent automatically by email.

**Comment by Kostelano** [comment]
How does a user log in if he doesn't know the password?

Sending a letter is carried out not by the **Users** component, but by plugin **User - Joomla**.

> PLG_USER_JOOMLA_NEW_USER_EMAIL_BODY="Hello {NAME},\n\n\nYou have been added as a User to {SITENAME} by an Administrator.\n\nThis email has your username and password to log in to {URL}\n\nUsername: {USERNAME}\nPassword: {PASSWORD}\n\n\nPlease do not respond to this message as it is automatically generated and is for information purposes only."
PLG_USER_JOOMLA_NEW_USER_EMAIL_SUBJECT="New User Details"

**Comment by phunsoft** [comment]
The user is informed about the password by a separete communication, such as messenger app, separate mail, phone call, etc, etc.

But the bug to me is that there seems to be an option that lets the admin choose whether the password is sent or not, but it is not honoured.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42750">issues.joomla.org/tracker/joomla-cms/42750</a>.</sub>

**Comment by brianteeman** [comment]
The functionality to send the password or not is for the emails created when a user registers for themself and not when the admin creates a user account. (I agree that''s not clear)

The good news however is that the emails created when the admin creates a user account are done using mail templates and you can customise that as you wish.

Go to the system -> mail templates and select the Users: New User template

You will then see that you can customise everything in that email including if you want to include the password or not.

**Comment by brianteeman** [comment]
PS personally I always set **Require Password Reset** when I create a new user.

**Comment by phunsoft** [comment]
This worked as described by you. Thanks. 
It really isn't obvious what excatly this setting is for.

I'm gonna close this issue as resolved.

BTW, requiring password reset is of no help if the initial password was "stolen" from the initial mail. The thief can reset to whatever he wants.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42750">issues.joomla.org/tracker/joomla-cms/42750</a>.</sub>

**Comment by phunsoft** [comment]
It seems I cannot close thi issue myself, can I? if not, what do I need to do to mark the issue as closed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42750">issues.joomla.org/tracker/joomla-cms/42750</a>.</sub>

**Comment by alikon** [comment]
yes you can.... 😄
