### ISSUE TITLE
Facebook Links

### ISSUE THREAD

**Issue by Dave-Skye** [joomla/joomla-cms#42763]
### Steps to reproduce the issue

If a facebook page is set to link to to a Joomla 4 website, the the return url is something like this.

https://www.website.co.uk/?fbclid=IwAR2Swzbda3oEmj5dkJAkwNvlrjrrhzr88D3a0sTgUjAm_BqURsUc4Uy-mTc

### Expected result

We would expect the website to load and ignore the facebook tracking code.

### Actual result

Yhe website does not load and we get 500 Internal Server Error
An internal server error has occured.

### System information (as much as possible)

This can be fixed with 2 lines added tot he .htaccess file.

RewriteCond %{QUERY_STRING} "fbclid=" [NC]
RewriteRule (.*) /$1? [R=301,L]

The problem with this fix is that Google Analytics cannot then see that the traffic came from facebook and records it as direct traffic.

**Comment by ReLater** [comment]
After testing some Joomla sites I can not confirm that query strings like 

`?fbclid=IwAR2Swzbda3oEmj5dkJAkwNvlrjrrhzr88D3a0sTgUjAm_BqURsUc4Uy-mTc`

lead to an 500 error in Joomla 3, 4, 5 per se.

Did you read already this thread in Joomla forum? https://forum.joomla.org/viewtopic.php?t=998394

especially comment:

> The problem is nothing to do with Joomla. The problenm is because you are using litespeed as a web server and the litespeed cache on the server is not configured correctly. Probably something to do with the drop query string configuration

**Comment by Dave-Skye** [comment]
Hello

I am not using litespeed as a web server.

**Comment by brianteeman** [comment]
I have also tested this on multiple web sites and can not confirm a 500 error message.

Please enable debug in global config and trigger the error on your site.

This should now display a Stack trace - please copy and paste that here

**Comment by Dave-Skye** [comment]
@brianteeman 

I have the .htaccess fixed disabled on the site in question and debug enabled. Not sure what else to do.

The URL : https://www.heronfield.co.uk/?fbclid=IwAR2Swzbda3oEmj5dkJAkwNvlrjrrhzr88D3a0sTgUjAm_BqURsUc4Uy-mTc

**Comment by brianteeman** [comment]
Now that you shared the url to your site I can see that you ARE using litespeed and that the 500 message is being generated by litespeed and not by joomla. I am not a litespeed expert but everything I wrote in tyhe referenced forum post should be relevant.

This is not a joomla problem.

![image](https://github.com/joomla/joomla-cms/assets/1296369/3ddd7a1a-0510-4475-8449-6682c260e9ab)

**Comment by Quy** [comment]
Closing as not a core issue.
