### ISSUE TITLE
[5.0] comment request - why is fields_values.item_id a varchar(255) type?

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#42767]
### Problem identified
I am trying, in phpMyAdmin, to create a database View linking the content table with the fields_values table in order to filter out those articles where a custom date/time field has a date less than now. The column to link the the two tables together, I thought, would be content.id and fields_values.item_id, but no: content.id is an int(10) type and fields_values.item_id is a varchar(255) type. Why?

### Open questions
Shouldn't fields_values.item_id be an int(10) type?

**Comment by Quy** [comment]
See #35795.
