### ISSUE TITLE
Scheduler Web Cron link is not generated

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#42775]
### Steps to reproduce the issue
1. Open Scheduled Tasks component options.
2. Enable "Web Cron", see empty "Webcron Link".
3. Save options, with enabled or disabled " Reset Access Key", try different variants.

### Expected result
Webcron Link is auto-populated

### Actual result

Webcron Link is empty

### System information (as much as possible)

PHP 8.2, Joomla 5.0.1, System Caching enabled.

**Comment by Quy** [comment]
I cannot reproduce this issue.

![42775-webcron](https://github.com/joomla/joomla-cms/assets/368084/466a62bf-bb47-4e71-b7a2-25b1a6df2b71)

**Comment by Quy** [comment]
Closing as non-reproducible.
