### ISSUE TITLE
[5.X] Global Checkin scheduler plugin fails on SQL Views

### ISSUE THREAD

**Issue by HLeithner** [joomla/joomla-cms#42772]
If you have a component which uses SQL Views for data preparation which is not update able the scheduler task fails.

### Steps to reproduce the issue
1. create a view based on #__content which is not update able (not adding the content id should work)
2. setup the scheduler task global checkin
3. checkout an item on #__content
4. run a test on the global checkin task

### Expected result
works

### Actual result
fails with the result:
```json
{
    "success": false,
    "message": "The target table jgb3i_jd_2_categories of the UPDATE is not updatable",
    "messages": null,
    "data": null
}
```

### System information (as much as possible)
j5.0.2

### Additional comments
jdiction uses view wit xml columns for translating table entries.
Manual Global Checkin works as expected.

**Comment by brianteeman** [comment]
related issue #41149 ?

**Comment by alikon** [comment]
i'm unable to reproduce with this view
```sql
CREATE VIEW `#__blog` AS SELECT `title` ,`checked_out` ,`checked_out_time` FROM `#__content`
```

 global checkin task runs fine

**Comment by HLeithner** [comment]
yes because this view is updateable, you need a view which does a bit more (I extract xml and override existing columns)

**Comment by HLeithner** [comment]
> related issue #41149 ?

no it's a completely different topic

**Comment by alikon** [comment]
ah ok my bad

so with this view

```sqL
CREATE VIEW j510_blog AS
 select title, checked_out, checked_out_time from j510_content
 union ALL
Select  'a', null, null 
```

![image](https://github.com/joomla/joomla-cms/assets/181681/da2af2f0-ec91-45ce-80ab-a645e83f52be)

then the task will fail

![image](https://github.com/joomla/joomla-cms/assets/181681/2c00f1e8-52f6-4027-9ff9-37bab735cb56)


i think we need to exclude from ` $tables = $db->getTableList();`  the non updatable views

i'll check better after work

**Comment by HLeithner** [comment]
https://github.com/joomla-framework/database/blob/3.x-dev/src/Mysqli/MysqliDriver.php#L630

should only return tables (like the postgres version)

`SHOW FULL TABLES WHERE Table_type='BASE TABLE'`

should work, (it returns 2 columns but the called loadColumn() returns only the first column so should be fine)

**Comment by alikon** [comment]
yes indeed

**Comment by HLeithner** [comment]
thanks for the framework pr https://github.com/joomla-framework/database/pull/297 I think we can close this here
