### ISSUE TITLE
[5.x] _updates table updare_id

### ISSUE THREAD

**Issue by joomleb** [joomla/joomla-cms#42786]
Hi guys,
PHP 8.1.x + Joomla 5.x (and also  Joomla 4.x) new installations...

Please, Why is the _updates table installed with update_id column value starting from 130 instead of 1?

**Comment by richard67** [comment]
> Hi guys, PHP 8.1.x + Joomla 5.x (and also Joomla 4.x) new installations...
> 
> Please, Why is the _updates table installed with update_id column value starting from 130 instead of 1?

@joomleb Why is that a problem for you?
