### ISSUE TITLE
[5.1] MFA - Fixed Code results in an error

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#42796]
### Steps to reproduce the issue
1. Install the 5.1 nightly build,
2. Publish the plugin "Multi-factor Authentication - Fixed Code",
3. Create a fixed code MFA method and try to login at the front.

`0 Property autocomplete not found in Joomla\Component\Users\Administrator\DataShape\DataShapeObject `

> This plugin is only meant to be used as an example for developers interested in creating their own plugins.

It's stated, but it won't work.

![Screenshot_1](https://github.com/joomla/joomla-cms/assets/8440661/1ed603ce-402a-470d-b847-841e55d007b2)

**Comment by alikon** [comment]
please test #42796
