### ISSUE TITLE
[4.4] Deprecated:  strftime() in calendar field

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#42790]
### Steps to reproduce the issue
Switch on error-reporting.

Add a calendar field to component and forget the  translateformat="true" 
or manipulate one of the calendar fields in article.xml

Deprecated: Function strftime() is deprecated in .... \libraries\src\Form\Field\CalendarField.php on line 322

### System information (as much as possible)
php 8.2

**Comment by Quy** [comment]
See PR #41266 & #41444

**Comment by joomdonation** [comment]
In the `CalendarField`, we have two format parameters:

- `format`: Uses by client side (javascript) to parse/format datetime value. The format is equals with the format used in PHP strftime function https://www.php.net/manual/en/function.strftime.php (which is deprecated now)
- `filterformat`: Uses by server side (PHP) to parser/format datetime value. The accepted format are defined here https://www.php.net/manual/en/datetime.format.php

To prevent warnings, you need to:

1. Set translateformat="true"
2. Or add `filterformat` attribute to your field. The value in this attribute must be equivalent to the value in `format` attribute. Example field:

```xml
<field
			name="created"
			type="calendar"
			label="Created Date"
			format="%Y-%m-%d"
                        filterformat="Y-m-d"
			showtime="true"
			filter="user_utc"
		/>
```

As the solution is there already, I'm closing this issue.
