### ISSUE TITLE
Save and New Menu Item has an issue if saving to a parent

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#42808]
### Steps to reproduce the issue
Create a new Menu Item.
Single Article.
Create the Article.
Add a parent to the menu.
Hit Save and New

### Expected result
Saves new menu without errors

### Actual result
Saves the menu but also says it can't save the menu because of an already existing menu alias.  It's like it tries to save it twice.
This does not occur if you do not have a parent item in the menu.

This does not happen if the menu item already exists with no parent and you add a parent.

### System information (as much as possible)

[systeminfo-2024-02-13T22 16 47+00 00.txt](https://github.com/joomla/joomla-cms/files/14272830/systeminfo-2024-02-13T22.16.47%2B00.00.txt)

### Additional comments
Here's a YouTube video of it:
https://youtu.be/mdLOE-MZUf4

Not sure if it's related but the same thing happens for Save and New in creating a menu (not a menu item)

**Comment by Quy** [comment]
Not reproducible. Probably related to #42810.

**Comment by uglyeoin** [comment]
Host could not replicate it either. I have no idea what it could be. Perhaps a temporary glitch somehow.
