### ISSUE TITLE
[5.0.2] File Checksum Failed when updating to 5.0.3rc1

### ISSUE THREAD

**Issue by wwwiiimmm** [joomla/joomla-cms#42816]
### Steps to reproduce the issue
Set the update channel of a 5.0.2 site to Testing and minimum stability to Release Candidate
Click Start update

### Expected result
Site updates to 5.0.3rc1

### Actual result
Page reloads with warning "File Checksum failed".

### System information (as much as possible)
Joomla 5.0.2
PHP 8.2.15
MySQL 8.0.33

**Comment by alikon** [comment]
confirmed
![image](https://github.com/joomla/joomla-cms/assets/181681/e463881e-b2b6-43c7-912e-43c09b6ab713)

maybe something not updated on https://update.joomla.org/core/test/extension_test.xml

**Comment by alikon** [comment]
as we have now 5.0.3 stable, and the checksum works as expected
i close the issue
