### ISSUE TITLE
Help button fails to open help screen when clicked on the question mark

### ISSUE THREAD

**Issue by chrisdavenport** [joomla/joomla-cms#42818]
### Steps to reproduce the issue
Go to any screen which has a help screen, for example Content -> Articles.
Click on the text "Help" of the help toolbar button and you will see the appropriate help screen.  However, if you click on the question mark to the left of the text you will get a much larger blank window with "about:blank" in the address bar.

### Expected result
Clicking anywhere on the help button (even on the question mark) should open the appropriate help screen.

### Actual result
The help screen only opens if the user clicks on the text of the help button.

### System information (as much as possible)
Chrome on Ubuntu 22.04.
php 8.1
Joomla 4.4.2 and Joomla 5.0.2 (same behaviour on both).

**Comment by brianteeman** [comment]
Confirmed. Clicking exactly on the icon opens a blank window

**Comment by Quy** [comment]
In browser's console: `Opening multiple popups was blocked due to lack of user activation.`

@dgrammatiko line 49 [#39727](https://github.com/joomla/joomla-cms/pull/39727/files#diff-aa2ef4867785da9d07f7d4f5e13ec2d5a7a96469e4dea6ead91a595d92fbc537)

**Comment by dgrammatiko** [comment]
@Quy can you add this css and check:

```css
.btn > * { pointer-events: none; }
```

**Comment by Quy** [comment]
@dgrammatiko I will submit a PR. Thank you for the fix!

**Comment by dgrammatiko** [comment]
@Quy change the code to `button > * { pointer-events: none; }`. the `.btn` class could be applied to links also...

**Comment by Quy** [comment]
Thanks for the report. Please test #42820.
