### ISSUE TITLE
J5.x add new tags _> Help points to J3:how-to instead of J4:how-to

### ISSUE THREAD

**Issue by DjoeC** [joomla/joomla-cms#42812]
### Steps to reproduce the issue
Official docker J5.0.2 image:
Components -> Tags -> Learn more

### Expected result
[Link to J4: help](https://docs.joomla.org/J4.x:How_To_Use_Content_Tags_in_Joomla "https://docs.joomla.org/J4.x:How_To_Use_Content_Tags_in_Joomla") or J5: equivalent

### Actual result
[Link to J3: help](https://docs.joomla.org/Special:MyLanguage/J3.x:How_To_Use_Content_Tags_in_Joomla! "https://docs.joomla.org/Special:MyLanguage/J3.x:How_To_Use_Content_Tags_in_Joomla!")
which contains substantially less usable information

### System information (as much as possible)
Latest official Docker J5.0.2 image

### Additional comments
none

**Comment by brianteeman** [comment]
Please see #42815 which is for j4 and will be upmerged eventtually in to j5
