### ISSUE TITLE
Cannot center an image in editor

### ISSUE THREAD

**Issue by cmirnow** [joomla/joomla-cms#42813]
### Steps to reproduce the issue

If "Figure Caption" is set, you cannot center (right, left, justify) an image.

![1](https://github.com/joomla/joomla-cms/assets/10660173/8f23d7ff-4cca-46cc-bc8d-d1b4c51d96dc)

### Actual result

```
<p><img style="display: block; margin-left: auto; margin-right: auto;" src="images/banners/white.png" width="234" height="74" loading="lazy" data-path="local-images:/banners/white.png" /></p>
<figure class="image align-center"><img src="images/banners/white.png" alt="test" width="234" height="74" loading="lazy" data-path="local-images:/banners/white.png" />
<figcaption>test</figcaption>
</figure>
<figure class="image align-right"><img src="images/banners/white.png" alt="test" width="234" height="74" loading="lazy" data-path="local-images:/banners/white.png" />
<figcaption>test</figcaption>
</figure>
```

### System information (as much as possible)

Joomla 5.0.2
php 8.2

### Additional comments

![2](https://github.com/joomla/joomla-cms/assets/10660173/4e2a493c-e1be-4784-987b-f58cedb047f8)
![3](https://github.com/joomla/joomla-cms/assets/10660173/5c155cba-2246-4d52-bfaa-90a5c568c832)

**Comment by TheNourhan** [comment]
Can you give me the path of this page?

**Comment by TheNourhan** [comment]
this problem does not appear for me

<img width="642" alt="Screenshot 2024-02-17 111743" src="https://github.com/joomla/joomla-cms/assets/109472010/63508229-205b-4dce-be97-be51b1946f54">

**Comment by cmirnow** [comment]
Just copy the HTML I showed in my first post and paste it, deleting everything else, into any Joomla article. And now open the page on the web.

I see this problem as in my old blog, which is upgraded to Joomla 5.0.2. And the same problem is inherent in the clean Joomla installation I did at your request, which contains all the default configurations.

Take a look. Open the source code of [this](https://masterpro.ws/automatic-joomla-cache-cleaning) page. Centering a single image in an article doesn't work::

```
<figure class="image align-center">
------
</figure>
```

**Comment by chmst** [comment]
This should be text-center, ot align-center. 
I there a template override?

**Comment by cmirnow** [comment]
> I there a template override?

@chmst , 
> ...the same problem is inherent in the clean Joomla installation I did at your request, which contains all the default configurations.

This problem appeared on my blog that I upgraded to Joomla 4.
The same problem exists immediately after a new installation of Joomla 4 and an upgrade to Joomla 5.
If you don't believe me, I am willing to provide full access to the test site.

P.S. The Joomla admin panel did not show any notifications about new or old overrides.

**Comment by cmirnow** [comment]
> This should be text-center, not align-center. I there a template override?

@chmst , I don't understand what this has to do with template overrides. The error shows itself **in the text editor**, in the default template Cassiopeia, on a newly installed Joomla, where there are no extensions from third-party developers.

![align](https://github.com/joomla/joomla-cms/assets/10660173/208ed481-4f1d-4fd4-8267-2c6c086030dd)

**Comment by Quy** [comment]
TinyMCE uses classes that are not in Bootstrap with Cassiopeia. Use `text-center` for center and `text-end` for right. See #35606 for discussion. Let's close this one and continue the discussion in the other issue.

**Comment by chmst** [comment]
The classes are for the figure container, not for the image 

In your example: align-center is for vertically centering the image (not visible here), text-center is what you need 
![grafik](https://github.com/joomla/joomla-cms/assets/1035262/585ee3e4-26af-4c48-98e1-24fb6f88e9b0)

Questions like that are better in forum.loomla.org, Tere are many supporters who can help you.  This is for bugs in Jooma core and so I'll close this here.

**Comment by cmirnow** [comment]
> In your example: align-center is for vertically centering the image (not visible here), text-center is what you need

I agree.
This is the reason why the editor icon that misleads users is Joomla's problem and not the user's problem:

![align](https://github.com/joomla/joomla-cms/assets/10660173/197cdf99-c759-4be8-8053-ecefbd4fb661)

![align1](https://github.com/joomla/joomla-cms/assets/10660173/e1490476-31c4-4d85-b4a9-441017f79534)


You are probably just now becoming aware of this incorrect problem, which does not testify in favor of the professionalism of Joomla developers:

@chmst :
> This should be text-center, not align-center. I there a template override?

OK. If the development team has no desire to fix obvious problems, I have nothing to add. I wish you success on the Joomla user forum, @chmst .
