### ISSUE TITLE
[4.4.3rc1] Joomla Next doesn't find update to J5

### ISSUE THREAD

**Issue by wwwiiimmm** [joomla/joomla-cms#42817]
Joomla 4.4.3rc1 doesn't find the update for 5.x
Maybe a bug or expected?

### Steps to reproduce the issue
First update 4.4.2 to 4.4.3rc1
Then change the update channel to Joomla Next.

### Expected result
Being able to update to J5

### Actual result
Page displays Check for updates.
Clicking the Check for updates reloads the page with a successful "Checked for updates".

### System information (as much as possible)
Joomla 4.4.3rc1
PHP 8.2.15
MySQL 8.0.33

**Comment by richard67** [comment]
I think it’s expected. Release candidates are not for production sites, and there is no update path from 4.4.3-rc1 to 5. when you update to 4.4.3 (stable) next week, the update to 5.0.3 will be found after that. 4.4.3 and 5.0.3 are scheduled for Tuesday next week.
