### ISSUE TITLE
Save & Close, Save & New, Save don't work when creating a new menu (not an item a whole menu)

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#42810]
### Steps to reproduce the issue
Go to create a new menu
Try to save it.

### Expected result
Saves menu. 
And it DOES save the menu but...

### Actual result
Says menu type already existed

Same for:
Save & New
Save & Close
Save

It does allow you to edit an existing menu and change the alias and save it.

### System information (as much as possible)

[systeminfo-2024-02-13T22 16 47+00 00.txt](https://github.com/joomla/joomla-cms/files/14272895/systeminfo-2024-02-13T22.16.47%2B00.00.txt)

### Additional comments
Here's a YouTube Video
https://youtu.be/Pjwpuhppx7Q

**Comment by brianteeman** [comment]
Can not replicate. Sounds like another litespeed configuration error.

**Comment by uglyeoin** [comment]
Interesting.  Ok I will contact my host and revert.

**Comment by Hackwar** [comment]
Any news?

**Comment by uglyeoin** [comment]
Sorry have just given my host super user access so they can test it. Will let you know what they say.

**Comment by uglyeoin** [comment]
Host could not replicate it either.  I have no idea what it could be.  Perhaps a temporary glitch somehow.
