### ISSUE TITLE
Website not being displayed on Apple Devices

### ISSUE THREAD

**Issue by OldMan-Jakob** [joomla/joomla-cms#42823]
### Steps to reproduce the issue
1. Open Browser on iPhone navigate to https://davidjakob.com - I tried with Safari and Chrome double-checked with friend
2. As above but with iPad - that's the devices I had to test with
### Expected result

2. Site opens with slideshow module (Gantry Template) with all necessary navigation

### Actual result

Only the logo, hamburger button and cookie consent button show up. Body is black, menu doesn't do anything, cookie button doesn't do anything.

### System information (as much as possible)
All parts of the site are up-to-date

System Information
Setting	Value
PHP Built On	Linux b3.tophost.ch 3.10.0-962.3.2.lve1.5.81.el7.x86_64 #1 SMP Wed May 31 10:36:47 UTC 2023 x86_64
Database Type	mysql
Database Version	10.6.17-MariaDB
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb3_general_ci
Database Connection Encryption	None
Database Server Supports Connection Encryption	No
PHP Version	8.1.27
Web Server	LiteSpeed
WebServer to PHP Interface	litespeed
Joomla! Version	Joomla! 5.0.2 Stable [ Kuboresha ] 9-January-2024 16:00 GMT
Joomla Backward Compatibility Plugin	Enabled (classes_aliases:"1", es5_assets:"1")

### Additional comments

This seems to be limited to Apple, as I have had no other complaints. I don't know if it's just my site or if it affects other Joomla/Gantry websites. Be good if it could be confirmed one way or another

**Comment by brianteeman** [comment]
I just tested your site on the iphone with out problem - screenshot below which features a photo taken a few hundred yards from where I am sitting

![image](https://github.com/joomla/joomla-cms/assets/1296369/3bf857f9-69d3-41ed-882b-a06ee772d7fd)

**Comment by OldMan-Jakob** [comment]
I'm perplexed! Thanks for checking. The devices used to check were 1 old
iPhone in Switzerland and one very new and up-to-date one in France, Same
with the iPad's.
I looked at the source and can't see anything to do that.
I'd be grateful for any ideas?

**Comment by brianteeman** [comment]
maybe they are being blocked by the content of your site which many will consider to be inflmatory or even offensive. Either way it is clearly not a joomla core code problem and this issue report should be closed

**Comment by OldMan-Jakob** [comment]
OK. I get that. Good grief!
Thanks.

Regards
David<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42823">issues.joomla.org/tracker/joomla-cms/42823</a>.</sub>

**Comment by alikon** [comment]
closed as not a core issue
