### ISSUE TITLE
Convert Images to .webp or .AVIF on upload

### ISSUE THREAD

**Issue by Jezjames** [joomla/joomla-cms#42821]
### Is your feature request related to a problem? Please describe.
For easy image optimization and SEO optimization. 
Can the project edit the image uploader to alow the images uploaded to .webp or avif file formats which are more compresed, load faster and better optizied.

### Describe the solution you'd like
Edit or allow the joomla uploader to convert images to .webp or .avif file formats on upload

**Comment by ssnobben** [comment]
Think you can use extensions also to fix this example https://storejextensions.org/extensions/jspeed.html "  •Images conversion to WebP and AVIF: Images can be converted in realtime to the WebP and AVIF next generation format" + (Adaptive Contents)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42821">issues.joomla.org/tracker/joomla-cms/42821</a>.</sub>

**Comment by alikon** [comment]
@Jezjames please don't double post https://github.com/joomla/joomla-cms/discussions/42822
