### ISSUE TITLE
Unicode characters in article title generates strange alias

### ISSUE THREAD

**Issue by Petike1007** [joomla/joomla-cms#42826]
### Steps to reproduce the issue
Save an article with a title contains ü or ö characters (hungarian)

### Expected result
The alias should contain u or o

### Actual result
The actual alias is ue or oe 

### System information (as much as possible)
Joomla 5.0.2
PHP 8.2.10
10.4.10 mariaDb

### Additional comments
After the first save it generates ue or oe, but if I delete the alias and save the article again it generates well (u or o)
I don't want to turn on the unicode characters option at system settings as it would save the characters as it is (ü or ö) and that's not good for seo

**Comment by chmst** [comment]
Seems t be duplicate  to https://issues.joomla.org/tracker/joomla-cms/42734
Could you please test https://github.com/joomla/joomla-cms/pull/42741, if this helps?

**Comment by brianteeman** [comment]
The actual result you report is the expected result. In other words the expected result is for ü to be transposed as ue

**Comment by brianteeman** [comment]
I dont see what the bug is here. IT looks like the expected behaviour to me
