### ISSUE TITLE
Hebrew language calendar field issue. 

### ISSUE THREAD

**Issue by hkwebpark** [joomla/joomla-cms#42828]
The website is currently operating on Joomla 5.0.2. Following the most recent upgrade, the calendar functionality is no longer operational

HTMLHelper::_('calendar',$date , 'date', 'filter_date1', '%Y-%m-%d');

![image](https://github.com/joomla/joomla-cms/assets/16019691/18a17e65-19b5-432c-a5c0-b4aec3f0044d)

### System information 

- Database Type 	mysql
- Database Version 	10.5.23-MariaDB-0+deb11u1
- PHP Version 	8.2.15
- Joomla! Version 	Joomla! 5.0.2 Stable [ Kuboresha ] 9-January-2024 16:00 GMT
- Joomla Backward Compatibility Plugin 	Enabled ()

**Comment by brianteeman** [comment]
Where did you get the hebrew translation from? I dont see one for Joomla 5 yet.

**Comment by Quy** [comment]
Closing due to no response.
