### ISSUE TITLE
[5.0] Feature request: filter and sort articles by custom field

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#42831]
### Is your feature request related to a problem? Please describe.
EDIT: to clarify, this is a front-end feature request.

For example, when displaying a category blog or list of future events, the only two ways to hide an article after the event date is passed is to -
a. add an 'unpublish' date
b. add an 'unfeature' date if the blog or list only shows featured items.

Both options rely on the person adding the event - who is not necessarily the site admin but quite likely someone non-technie adding the article from the front end - also adding the correct 'unpublish' or 'unfeature' date and time as there is no current way (afik) to make these options mandatory.

### Describe the solution you'd like
If a mandatory custom calendar field (with 'show time') is assigned to the event category then when creating the menu item there would be the option to both:
a. filter the category by the custom calendar field where the value in the custom field is greater than today (or any other chosen date).
b. sort by the custom date (ASC/DESC)

### Additional context
This function could apply to other types of field, e.g. an email field and to filter where the field is or is not empty.

**Comment by brianteeman** [comment]
That would be very non-performant unless you only have a few articles

**Comment by rdeutz** [comment]
Thanks for your feature request. Sort and filter based on custom fields would be a good feature for Joomla. There is already a discussion about this: https://github.com/joomla/joomla-cms/discussions/42430

In this specific case you can solve the problem with a few lines in a plugin. It would get the event date and use it as unpublish date when the event is saved. 

Because we have a discussion about this feature in general and there is another solution I am closing this issue. Feel free to add your request to the discussion with more details.

**Comment by nibra** [comment]
Also see https://github.com/joomla/rfc/blob/cck/proposed/cck-meta.md

**Comment by SemaphoreOxalis** [comment]
> That would be very non-performant unless you only have a few articles
And what is the performant way ?

@Scrabble96 In the same situations we use ArticleAnywhere Pro plug-in which offer all the options needed in a custom override until we get a core option.
EasyLayout offer this options too but it's an over-complicated option for a "simple" task.

**Comment by Scrabble96** [comment]
> @Scrabble96 In the same situations we use ArticleAnywhere Pro plug-in which offer all the options needed in a custom override until we get a core option. EasyLayout offer this options too but it's an over-complicated option for a "simple" task.

Thanks @SemaphoreOxalis, the ArticlesAnywhere Pro looks like it does just what I want. I'll give it a try.
