### ISSUE TITLE
[5.0] CodeMirror: Can’t indent using tab key in the CodeMirror editor

### ISSUE THREAD

**Issue by pedro-olaia** [joomla/joomla-cms#42837]
### Steps to reproduce the issue
Set default editor as CodeMirror then create or open any element like an article, category or module in joomla administration area where the editor can be used, click inside the editor area and press the tab key on the keyboard.

### Expected result
indent using tab key in CodeMirror editor

### Actual result
Pressing the Tab key takes the cursor from the editing area to the next button out of the editor. 

### System information (as much as possible)
Joomla! Version: Joomla! 5.0.2 Stable
PHP Version: 8.1.10
Database Type: mysql
Database Collation: utf8mb4_general_ci

**Comment by brianteeman** [comment]
> https://codemirror.net/examples/tab/

> By default, CodeMirror does not handle the Tab key. This isn't an oversight—it is an intentional decision to make the default configuration pass the ["no keyboard trap"](https://www.w3.org/TR/WCAG21/#no-keyboard-trap) criterion of the W3C Web Content Accessibility Guidelines.

> Some users browse the web without access to a pointing device, and it is really unfriendly towards such users to have focusable inputs that they cannot escape from.

**Comment by Quy** [comment]
Closing as expected behavior.

**Comment by pedro-olaia** [comment]
In J!4 was possible to use the Tab key but only on CodeMirror. Thank you for the very effective explanation!
