### ISSUE TITLE
edit own vs edit acl

### ISSUE THREAD

**Issue by peteruoi** [joomla/joomla-cms#42843]
### Steps to reproduce the issue

Author has the edit own articles permission. Go to a categolry list with article of him inside and you want be able to see them if unpublished.
Add author the edit permission now can see both his unpublished but can edi all the other too (which is unwanted) 

### Expected result
I Expect when edit own is on then he can see his articles

### Actual result
He cannot. Only if he has the edit all articles can see his articles (both unpublished and published)

### System information (as much as possible)

joomla 4.4.3

If it's not a bug then at least it's an inconsistency of what you expect with the permission edi and edit own

Thanks!

**Comment by Quy** [comment]
Duplicate #35687?

**Comment by Quy** [comment]
Closing as duplicate.
