### ISSUE TITLE
Banners application crashes

### ISSUE THREAD

**Issue by counterpoint** [joomla/joomla-cms#42841]
### Steps to reproduce the issue

Create a Joomla 5.0.2 site. Go to admin interface. Select component Banners. Exact result may vary. On Debian 12 with PHP 8.2 the site crashes and records an error "AH01067: Failed to read FastCGI header".

### Expected result

Displays banners information

### Actual result

Site crashes

### System information (as much as possible)

Debian 12 PHP-FPM 8.2 Joomla 5.0.2

### Additional comments

This can also affect third party software that calls the relevant method.

Line 42 sets $date:
$date = Factory::getDate();
This is then used in a bind to a SQL statement. But it is an object. It works if changed to:
$date = (string) Factory::getDate();

**Comment by webchun** [comment]
I experience the same issue. When I publish a banner module or even access this page : administrator/index.php?option=com_banners&view=banners with Joomla installed on PHP 8.2.4, it crashes the website. Not only with Joomla 5, but I also experience the issue with Joomla 4.4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42841">issues.joomla.org/tracker/joomla-cms/42841</a>.</sub>

**Comment by counterpoint** [comment]
Sorry, forgot to mention that the file referred to that contains the error is .../administrator/components/com_banners/src/Helper/BannersHelper.php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42841">issues.joomla.org/tracker/joomla-cms/42841</a>.</sub>

**Comment by Quy** [comment]
I cannot reproduce either. Please enable debug mode and set error reporting to maximum to get a stack trace.

**Comment by alikon** [comment]
from my old memories could help
https://serverpilot.io/docs/error-failed-to-read-fastcgi-header/

**Comment by webchun** [comment]
I have set the error reporting to maximum and enabled the debug mode, but no stack trace shows up. The issue disappeared when I commented out this line in mod_banners.php: BannersComponentHelper::updateReset(); 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42841">issues.joomla.org/tracker/joomla-cms/42841</a>.</sub>

**Comment by joomdonation** [comment]
I cannot reproduce the issue, too. However, I can see that the code is wrong. @webchun @counterpoint Could you please modify this line of code https://github.com/joomla/joomla-cms/blob/4.4-dev/administrator/components/com_banners/src/Helper/BannersHelper.php#L42 to:

```php
$date = Factory::getDate()->toSql();
```

Then check it again to see if the error is gon?

**Comment by counterpoint** [comment]
Debug and error reporting maximum were already enabled. But since the problem causes PHP to crash, diagnostics of that kind are not feasible. That made the problem difficult to track, since the only initial information was that there was a problem somewhere - probably in PHP code. PHP crashes may well be specific to a precise environnment. But Debian 12 is pretty mainstream. This link provides similar information to the link provided by @alikon but is not specific to Wordpress and indicates that a PHP error is the most common of the possible causes - https://bobcares.com/blog/apache-error-failed-to-read-fastcgi-header/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42841">issues.joomla.org/tracker/joomla-cms/42841</a>.</sub>

**Comment by joomdonation** [comment]
@counterpoint  You are right. I just checked the code more and see that (string) $date and $date->toSql() result in same value. However, I would use $date->toSql() to make it consistent with other places in Joomla. For example https://github.com/joomla/joomla-cms/blob/4.4-dev/components/com_content/src/Model/ArticleModel.php#L184 and https://github.com/joomla/joomla-cms/blob/4.4-dev/components/com_content/src/Model/ArticleModel.php#L202 (Who knows if we use a DB driver using a date format different with Y-m-d H:i:s)

Do you want to make PR with the suggested change?

**Comment by counterpoint** [comment]
That makes sense @joomdonation, although (string) is a lot more efficient. What is PR?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42841">issues.joomla.org/tracker/joomla-cms/42841</a>.</sub>

**Comment by counterpoint** [comment]
Thanks @joomdonation. Sorry, but I'm not familiar with making git pull requests and do not have time to find out. I've precisely identified the fault, that should be enough.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42841">issues.joomla.org/tracker/joomla-cms/42841</a>.</sub>

**Comment by counterpoint** [comment]
Thanks @joomdonation that's great.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42841">issues.joomla.org/tracker/joomla-cms/42841</a>.</sub>

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/42869 should address this issue. Please test it if you can. Thanks !
