### ISSUE TITLE
Deprecated: mb_strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated

### ISSUE THREAD

**Issue by RickR2H** [joomla/joomla-cms#42846]
### Steps to reproduce the issue
Set error reporting to maximum
Create a category blog menu item
Set PHP to 8.2 or higher
Open the blog layout page on the frontend

### Expected result
No deprecation warning

### Actual result
You'll get the error: Deprecated: mb_strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in C:\wamp64\www\roc\public_html\libraries\vendor\joomla\string\src\phputf8\mbstring\core.php on line 44

This is probably caused by the email cloak plugin. When this plugin is disabled, the error is gone.

### System information (as much as possible)
J5.0.3 / Apache / PHP 8.2

**Comment by richard67** [comment]
@RickR2H Do you get a call stack shown when switching on "Debug System" in Global Configuration? If yes, post a screenshot or text copy here. Thanks in advance.

**Comment by RickR2H** [comment]
@richard67 Here is the call stack

![image](https://github.com/joomla/joomla-cms/assets/5610413/91dc7ff0-6271-42ab-a05b-acb9796cbecb)

**Comment by alikon** [comment]
i was able to replicate the issue only with this hack, from
https://github.com/joomla/joomla-cms/blob/56c130c86eb0d0219d8d932f21c019cde49b8e09/plugins/content/emailcloak/src/Extension/EmailCloak.php#L65

to

`$text = $this->cloak(null);`

btw
to be on the safe side #42865

**Comment by PhocaCz** [comment]
This problem still can occur (version Joomla 5.0.3) in case, e.g. some 3pd extension uses:

```HTMLHelper::_('content.prepare', $description);```

and the description is null (replace the description variable with anything), then this null is chained to cloak method and StringHelper::strpos method which then produces this error in vendor/joomla/string/src/phputf8/mbstring/core.php:45

I didn't test if there can be some place which can hypothetically use null in HTMLHelper::_('content.prepare', ...); in core, but there is a lot of places in core:

- EmailCloak (plugins/content/emailcloak/src/Extension/EmailCloak.php 122, 127)
- StringHelper::strpos (libraries/vendor/joomla/string/src/StringHelper.php 147)
- utf8_strpos (vendor/joomla/string/src/phputf8/mbstring/core.php 45)
which can simply prevent it.

Either by adding (string) or a condition preventing method calls with null.

Jan

**Comment by artemismatla** [comment]
having the same issue! when i disable the plugin "Content - Email Cloaking" the error is fixed. do we need that plugin "Content - Email Cloaking" ?? what is it for? it will get resolved in the next joomla uopdate?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42846">issues.joomla.org/tracker/joomla-cms/42846</a>.</sub>

**Comment by chmst** [comment]
Yes, we need this plugin. The problem is fixed in version 5.1. as you can see here: https://github.com/joomla/joomla-cms/pull/42865

**Comment by brianteeman** [comment]
plus you should never run a live site with error reporting on

**Comment by artemismatla** [comment]
> plus you should never run a live site with error reporting on

that site, with error reporting on, is the demo site for the checks before we update the live one!

**Comment by StefanSTS** [comment]
Request to reopen this issue for J4 and J5.

Switching on and off the content plugin email cloak toggles this error in J 4.4.10.
/libraries/vendor/joomla/string/src/phputf8/mbstring/core.php on line 41

Line 41 is in this function:

function utf8_strpos($str, $search, $offset = false)
{
    if ($offset === false) {
        return mb_strpos($str, $search); // line 41
    } else {
        return mb_strpos($str, $search, $offset);
    }
}

The same function is in J 4.4.10 and J 5.2.3.

Since this is a generic function that might not be used by email cloak only, I suggest to check in this function, if $str is set.

Additionally the fix for J5 https://github.com/joomla/joomla-cms/pull/42865 might be ported to J4 if you feel that fixing it in both places is needed.

**Comment by StefanSTS** [comment]
Request dropped.
After discussion on Mattermost, I drop this request, since it will not be fixed in Joomla 4 that only receives security fixes. 
And for J5 it is expected that the calling function is not delivering empty values.
