### ISSUE TITLE
[5.0.2] File Checksum Failed when updating to 5.0.3

### ISSUE THREAD

**Issue by komodore** [joomla/joomla-cms#42851]
### Steps to reproduce the issue

Set the update channel of a 5.0.2 site to stable
Click Start update

### Expected result

Site updates to 5.0.3

### Actual result

Page reloads with warning "File Checksum failed".

### System information (as much as possible)

Joomla 5.0.2
PHP 8.2.15
10.5.24-MariaDB

**Comment by Quy** [comment]
Duplicate #42816
