### ISSUE TITLE
cli scheduler:run breaks if --live-site does not end with /

### ISSUE THREAD

**Issue by svanschu** [joomla/joomla-cms#42859]
### Steps to reproduce the issue
This  line fails
`php cli/joomla.php scheduler:run -i 1 --live-site 'http://localhost:43000'`

number 1  is the  rotate Logs  task, but it happens with any other as well

This line succeeds
`php cli/joomla.php scheduler:run -i 1 --live-site 'http://localhost:43000/'`

### Expected result
successful run

### Actual result
![grafik](https://github.com/joomla/joomla-cms/assets/806395/1841436a-a70a-45f6-b36e-e6ae062b9b8c)

If you start debugging and stop on every exception, it stops with

`RuntimeException: Could not parse the requested URI http://localhost:43000cli/joomla.php`

in libraries/vendor/joomla/uri/src/AbstractUri.php line 367 parse($uri)

### System information (as much as possible)
Tested with J5.0

### Additional comments
I only found the symptoms yet, but not the root cause

**Comment by svanschu** [comment]
Found the spot.

In `libraries/vendor/joomla/application/src/AbstractWebApplication.php` line 820 `$uri .= $this->input->server->getString('SCRIPT_NAME');` the SCRIPT_NAME gets added without checking if there is a `/` in between or not.

**Comment by Quy** [comment]
Closing per PR #42860. Thank you!

**Comment by svanschu** [comment]
@Quy  No that's indeed a different error, which is sadly not related to the PR.
