### ISSUE TITLE
Module Frontend Edit Cancel

### ISSUE THREAD

**Issue by Dave-Skye** [joomla/joomla-cms#42862]
### Steps to reproduce the issue

When editing a module from the frontend, if you save and close, it returns you to the same page. If I hit cancel (rather than save and close) it returns you to the websites homepage.

### Expected result

I would expect if I cancel it should keep you on the same page and not return you to the home page, which is very annoying.

### System information (as much as possible)

Found the same result on 4.4.3 and 5.0.3

### Additional comments

Does not happen of J3.

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/42870 should fix this issue. Please help testing to get the issue sorted. Thanks !
