### ISSUE TITLE
PHP Requirements for Joomla 5

### ISSUE THREAD

**Issue by sdrawdenek** [joomla/joomla-cms#42887]
### Is your feature request related to a problem? Please describe.

Fresh install of Joomla 5 on server throws Error 500 unless following PHP Moddule is selected:

nd_mysql

This is the case for Joomla 5 when using PHP 8.1 or 8.2

### Describe the solution you'd like

Add nd_mysql to the list under More Information for Joomla! 5 at:

https://manual.joomla.org/docs/next/get-started/technical-requirements/

List currently reads:

Modules: json, simplexml, dom, gd, mysqlnd or pgsql

Should it read:

Modules: json, simplexml, dom, gd, nd_mysqli, mysqlnd or pgsql

### Additional context

Only observed the above on server run my one UK hosting provider

**Comment by alikon** [comment]
please do it yourself https://github.com/joomla/Manual

**Comment by Quy** [comment]
Reported to https://github.com/joomla/Manual/issues/230
