### ISSUE TITLE
[5.0] HTML Error 414 on Smart Search

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#42889]
### Steps to reproduce the issue

1. Go to URL https://www.systemtest.neudorf-mkk.de/
2. Click on "Suchen" in the top horizontal navigation
3. Enter "joomla 4" in the search field and click button "Suchen"
4. Click on any of the results

### Expected result
The respective page of the website is displayed.

### Actual result

1. An extremely long URL is created (s. the browser's status bar):

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/09b88e17-70b2-45b6-9584-70b5ca1a5189)

2. You get an HTML error 414 ("Request-URI too lond")

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/1cf70ca8-f5aa-42b3-964a-cd1e9ece2e37)

### System information (as much as possible)
Joomla 5.0.3
PHP 8.2.2
MySQL 8.0.33

### Additional comments

1. When searching for "joomla" or "joomla version" or "joomla 51", everything works fine. So the issue seems to be related to the digit (or string?) 4 in the search field.
2. The testsite is not really small, but contains more than 1.200 articles with several access levels.
3. I've not been able to reproduce the issue on a small test site (https://www.current.rolfdautrich.de, search for "joomla 5").

**Comment by brianteeman** [comment]
the long string in the url is a base64 decoded string of the terms to highlight on the page.

**Comment by dautrich** [comment]
@brianteeman 
Do you have an idea why "joomla 4" produces such a long string, while "joomla 51" makes a relatively short one?

**Comment by Fedik** [comment]
Change Smart Serach configuration. Change "Word Match" to "Match exactly".

**Comment by Fedik** [comment]
It happens because you have set "Word Match" to "Match words containing the search term anywhere". 
And this produce huge result while searching for `4` https://github.com/joomla/joomla-cms/blob/f8003bc3e6fb44caddd15e1a2146de382a8203b6/administrator/components/com_finder/src/Indexer/Query.php#L1262-L1266

**Comment by Fedik** [comment]
I set it as a bug, we at least should limit the number of terms to highlighting.
Similar to what Hannes already made for JS https://github.com/joomla/joomla-cms/pull/41463

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/42921

**Comment by dautrich** [comment]
The issue was filed for J5.0, but the resulting PR #42921 is for J4.4, as of the headline. Does it apply to J5.0 as well?

**Comment by Fedik** [comment]
The bug affects both 4.x and 5.x, 
After fixing 4.x it will be upmerged to 5.x

**Comment by Fedik** [comment]
I think you have a different configuration for Smart search for j4 and j5.

The error will not happen on default installation, with default parameters. 
Only when you change them. Check my previous comments, or the description in the linked PR.

**Comment by dautrich** [comment]
I have set the Smart Search configuration as described in your testing instructions. And "Word Match" is set to exactly this option on my faulty site.

**Comment by Fedik** [comment]
Another reason that your test installation for j4 has less amount of content than my.
