### ISSUE TITLE
SMTP setup for Server causes SMTP 221 errors

### ISSUE THREAD

**Issue by iandingwall** [joomla/joomla-cms#42897]
### Steps to reproduce the issue
In Global Configuration - System you set up the SMTP email as the email type along with the server name, port, TLS email address, username & password. You then Press the test email button at the bottom of the form. 

I found that you it looked better to set the SMTP email settings then <Save& Close> and then come back into the Global Configuration server settings and then press the test button to have an expected result.

Once SMTP is fully setup with a <Green> Expected results test, if you go into the Contacts form and attempt to send an email to one of the contracts, it again comes up with either of the <green> Expected or <Red>Actual result error.

### Expected result
You get a green bar along the top of the screen stating:
"The email was sent to {email address}using SMTP. You should check that you've received the test email."

Is you send an email with the Contacts option it should give "Thank you for your email."

### Actual result
get an intermittent error message with SMTP 221 error of the form
"The following From address failed: {as set in server global config} : MAIL FROM command failed,{domain} Service closing transmission channel ,221,SMTP server error: MAIL FROM command failed Detail: {domain} Service closing transmission channel SMTP code: 221"

### System information (as much as possible)
Joomla v4.4.3
PHP 8.2
My SQL 5.7 (yes its just out of support) but hosting does not yet support anything newer :(
Swapped from PHPmailer to SMTP so the emails are Authorised to match DMARC processing.
It looks like the services is just stuffing text into the buffer and the FROM: smtp address is read incorrectly. I have not checked the code as I am no fluent in PHP.

### Additional comments
This looks to be intermittent in both the global configuration server setup test SMTP and also on the <contacts> function in the main web site. The same error is happening 50% is of the time....

**Comment by iandingwall** [comment]
This is the example error message I received<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42897">issues.joomla.org/tracker/joomla-cms/42897</a>.</sub>

**Comment by richard67** [comment]
The steps to reproduce the issue seem to be incomplete, they just say „In the“.

**Comment by iandingwall** [comment]
I have updated the original text of the issue, sorry I did not notice the form chopped out the text... Happy to answer with any more specific information.

**Comment by Quy** [comment]
Is the FROM value coming from the form?

**Comment by iandingwall** [comment]
The from address comes from the system - global configuration - <server> tab -  {from name} <{From email}> fields

**Comment by Quy** [comment]
Have you contacted your hosting/SMTP provider for assistance?

**Comment by iandingwall** [comment]
No, is there away to activate debug inside Joomla while using SMTP outbound email or could you point me to the code module and I will have a look at what is going on, stripping into a test harness. I have swapped to the SMTP support inside joomla as I now need "Authenticated" emails to better support DMARC processing of outbound emails.

**Comment by Quy** [comment]
Is this a recent issue? Which Joomla version did it started? We would have received many more reports if it was an issue with Joomla. I have 5 sites using SMTP2Go service without issues. There is a free plan that you may want to try to determine if is an issue with your SMTP provider.

**Comment by Quy** [comment]
Since this is most likely an issue with your setup, please use the [Joomla forum](https://forum.joomla.org/) for support.

**Comment by iandingwall** [comment]
ok close this ticket. I am just running debug to look at the SMTP response messages for both failed and ok messages. its about 50/50 if it works or not.. 

thank you for the help :)

**Comment by iandingwall** [comment]
please close. I will open a new ticket if I see an actual explicit fault...
