### ISSUE TITLE
What is the advantage of using the "validationtext" tag in the text element?

### ISSUE THREAD

**Issue by balvard** [joomla/joomla-cms#42919]
### Steps to reproduce the issue
In XML file we have a tag called "validationtext".
This element is not useful because it is not translatable.
### Expected result
data-validation-text="Please fill Title"

### Actual result
data-validation-text="TITLE_FILL_ELEMENT"

### System information (as much as possible)
In the .ini file :
TITLE_FILL_ELEMENT="Please fill Title"

### Additional comments

Please fix this file : layouts\joomla\form\field\text.php
At line : 98
!empty($validationtext) ? 'data-validation-text="' . $validationtext . '"' : '',
Change this line to this :
!empty($validationtext) ? 'data-validation-text="' . Text::_($validationtext) . '"' : '',
Thanks.

**Comment by Quy** [comment]
@dgrammatiko Hopefully you can provide additional information on this attribute. Thanks. 
https://github.com/joomla/joomla-cms/commit/f0ba73a8933fb4bd386e12f03ad215623eed9ec9#diff-7195eb75172e6bd0b450db0f22c89a8a24d8e65afd2d06df17d83e7c278d4d0bR74

**Comment by dgrammatiko** [comment]
The `data-validation-text` is used in the validation script (client side) in order devs to have the option to set a custom invalid state message PER FIELD: https://github.com/joomla/joomla-cms/blob/d72d639197dc7d7c880536c0ba0a7e80f107ab48/build/media_source/system/js/fields/validate.es6.js#L110

FWIW the platform itself with the newest native formvalidation supports a similar thing (although the attributes reflect the invalid state)

**Comment by Hackwar** [comment]
I created #43198 to fix this. Closing this issue. Thanks for your report.
