### ISSUE TITLE
[4.4] [PHP 8.1] Fixes Deprecated: strtolower(): Passing null to string in libraries\vendor\joomla\filter\src\InputFilter.php on line 213

### ISSUE THREAD

**Issue by makaveli1563** [joomla/joomla-cms#42913]
Fixes Deprecated: strtolower(): Passing null to parameter https://github.com/joomla/joomla-cms/pull/1 ($string) of type string is deprecated in libraries\vendor\joomla\filter\src\InputFilter.php on line 213

I wrote about this problem here #42836 
The problem remained after the update Joomla.

**Comment by Quy** [comment]
Have you reported the issue to the extension developer?
