### ISSUE TITLE
mod_articles_categories displaying the sub-sub-categories twice

### ISSUE THREAD

**Issue by woluweb** [joomla/joomla-cms#42924]
### Steps to reproduce the issue

It seems there is a bug on J4/J5 for mod_articles_categories ("This module displays a list of categories from one parent category.").

In the Module, select a Parent Category
- which has Sub-Categories
- having in turn Sub-Sub-Categories

### Expected result

We should have a nice hierarchy
- with Sub-Categories
  - and their respective Sub-Sub-Categories

### Actual result

Each Sub-Sub-Category appears twice
- :white_check_mark: correctly as child of their parent
- :x: but also a second time *at the same level* as their parent

### System information (as much as possible)

Was working fine under J3.
Issue tested both on J4 and J5.

### Additional comments

Cassiopeia is not having any override for this module (only for mod_menu and mod_custom) so the issue would be
- at the Joomla level
- and not at the Cassiopeia level

**Comment by joomdonation** [comment]
PR https://github.com/joomla/joomla-cms/pull/42925 should fix the issue. Please help testing, thanks !
