### ISSUE TITLE
Joomla 5.0.3: Sorting Custom Fields by field group not working

### ISSUE THREAD

**Issue by webvendora** [joomla/joomla-cms#42922]
### Steps to reproduce the issue
Try to sort the custom fields by clicking on the field group header 

### Expected result
Sorted list in the admin backend

### Actual result

Service Unavailable

The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later.

### System information (as much as possible)
 PHP 8.1
Joomla 5.0.3.

**Comment by fgsw** [comment]
```administrator/index.php?option=com_fields&view=fields&context=com_users.user```: Sort article, contact, user custom fields by field groups give ```Forbidden You don't have permission to access /administrator/index.php on this server.```

**Comment by brianteeman** [comment]
I can not replicate this. The 503 message is coming from your server. In my experience this has been triggered by a bad apache mod_security rule and you should ask your hosts to check their logs which should giv4e more details

**Comment by Quy** [comment]
I cannot replicate either with the server error and permission access.

**Comment by fgsw** [comment]
Thanks @brianteeman @Quy for info, then its a issue of cloudaccess.
