### ISSUE TITLE
[4.4] Override issue in child template

### ISSUE THREAD

**Issue by vtheod** [joomla/joomla-cms#42931]
### Steps to reproduce the issue

If I make some overrides in child template's html/layouts folder, the overrides are not working.

### Expected result

Overrides should work

### Actual result

Overrides doesn't work

### System information (as much as possible)

PHP version: 8.2.16
Web Server: Apache
Joomla version:  ‎4.4.3

**Comment by chmst** [comment]
In general, layout overrides work very well. 
Could you please describe your problem in detail?
Or ask in forum.joomla.org, this is a better place for this kind of issues.

**Comment by dgrammatiko** [comment]
@chmst I guess it’s all about https://github.com/joomla/joomla-cms/pull/39308 and the parent issue https://github.com/joomla/joomla-cms/issues/39306

**Comment by Quy** [comment]
@dgrammatiko OK to close this one as it is a duplicate of #39306?

**Comment by dgrammatiko** [comment]
@Quy dont ask me ask @vtheod

**Comment by alikon** [comment]
if I understand correctly
not a core issue
