### ISSUE TITLE
[5.1] abandoned composer dependencies

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#42952]
After #42945 merged, there are many "abandoned" warnings during composer install @laoneo @LadySolveig 

https://ci.joomla.org/joomla/joomla-cms/74324/1/6
![image](https://github.com/joomla/joomla-cms/assets/66922325/a5fb94a7-53d6-4890-b874-0159c37bf6c1)

**Comment by richard67** [comment]
Maybe it just needs to change this line https://github.com/joomla/joomla-cms/blob/5.1-dev/composer.json#L105
from `"web-token/signature-pack": "^3.2.10",`
to `"web-token/jwt-library": "^3.3.1"`?

**Comment by heelc29** [comment]
> Maybe it just needs to change this line https://github.com/joomla/joomla-cms/blob/5.1-dev/composer.json#L105 from `"web-token/signature-pack": "^3.2.10",` to `"web-token/jwt-library": "^3.3.1"`?

I tried it just 5 minutes ago 😅

**Comment by heelc29** [comment]
> Hmm, yes, seems not to help.
> 
> Maybe we can't really avoid that because it's caused by that library's composer.json files?

It works ... there is no longer a warning
![image](https://github.com/joomla/joomla-cms/assets/66922325/01e80e3e-4fef-49fa-ba3f-cff320540eb2)

**Comment by richard67** [comment]
> > Hmm, yes, seems not to help.
> > Maybe we can't really avoid that because it's caused by that library's composer.json files?
> 
> It works ... there is no longer a warning

@heelc29 What did you change? I changed line 105 in the composer.json from `"web-token/signature-pack": "^3.2.10",` to `"web-token/jwt-library": "^3.3.1"`, but that did not help here. If you have a fix: Could you make a PR?

**Comment by richard67** [comment]
Hmm, I did now run a `composer update web-token/jwt-library` in addition to the mentioned change, and that seems to fix it.

**Comment by richard67** [comment]
I will make a PR in a few minutes.

**Comment by richard67** [comment]
@heelc29 I see you already created one ... would have been helpful to mention that here and to close this issue like we do it when we have a PR for it.

**Comment by richard67** [comment]
Closing as having a pull request. See #42954 .

**Comment by heelc29** [comment]
> @heelc29 I see you already created one ... would have been helpful to mention that here and to close this issue like we do it when we have a PR for it.

Was not sure if its the "right" fix...

**Comment by richard67** [comment]
I wasn't sure either, but if it is ok it will also need my follow up PR #42955 .
