### ISSUE TITLE
Updating Bootstrap from 5.3.2 to 5.3.3

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#42964]
### What needs to be fixed
[Bootstrap 5.3.3](https://blog.getbootstrap.com/2024/02/20/bootstrap-5-3-3/)

**Comment by laoneo** [comment]
Thanks for reporting. As we do regularly updates of all our dependencies during development phase of minor or major releases, we don't need an extra issue for a bootstrap update. This will be solved with pr's like #42945 and are managed by the release managers and maintainers. SO I'm closing this one.
