### ISSUE TITLE
[5.1] tuf no transport

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#42973]
### Steps to reproduce the issue
Clean install of 4.4.3 with the sample data
Updated to 5.1.0 beta1 by downloading the zip from j.org and then using the upload and update feature of com_installer
Upgrade proceeded without error
Database check shows no problems
update logs shows no problems
apache logs shows no problems

### Steps to see the Problems
Check for Joomla or Extension Updates
#### **0 No transport driver available.**

<details><summary>Call Stack</summary>

| # | Function | Location |
| --- | --- | --- |
1 | () | JROOT\libraries\vendor\joomla\http\src\HttpFactory.php:40
2 | Joomla\Http\HttpFactory->getHttp() | JROOT\libraries\src\TUF\TufFetcher.php:74
3 | Joomla\CMS\TUF\TufFetcher->__construct() | JROOT\libraries\src\Updater\Adapter\TufAdapter.php:77
4 | Joomla\CMS\Updater\Adapter\TufAdapter->getUpdateTargets() | JROOT\libraries\src\Updater\Adapter\TufAdapter.php:44
5 | Joomla\CMS\Updater\Adapter\TufAdapter->findUpdate() | JROOT\libraries\src\Updater\Updater.php:264
6 | Joomla\CMS\Updater\Updater->getUpdateObjectsForSite() | JROOT\libraries\src\Updater\Updater.php:165
7 | Joomla\CMS\Updater\Updater->findUpdates() | JROOT\administrator\components\com_joomlaupdate\src\Model\UpdateModel.php:189
8 | Joomla\Component\Joomlaupdate\Administrator\Model\UpdateModel->refreshUpdates() | JROOT\administrator\components\com_joomlaupdate\src\Controller\DisplayController.php:80
9 | Joomla\Component\Joomlaupdate\Administrator\Controller\DisplayController->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:730
10 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:143
11 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:361
12 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:150
13 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:195
14 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:306
15 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:58
16 | require_once() | JROOT\administrator\index.php:32
</details> 

### System information (as much as possible)

<details><summary>System Information</summary>
=============
System Information
=============
php: Windows NT MINI-ME 10.0 build 22631 (Windows 11) AMD64
dbserver: mysql
dbversion: 8.0.30
dbcollation: utf8mb4_unicode_ci
dbconnectioncollation: utf8mb4_0900_ai_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 8.2.16
server: Apache/2.4.54 (Win64) OpenSSL/1.1.1q PHP/8.2.16
sapi_name: apache2handler
version: Joomla! 5.1.0-beta1-dev Development [ Kudumisha ] 20-February-2024 16:31 GMT
compatpluginenabled: true
compatpluginparameters: 
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36

=============
PHP Settings
=============
memory_limit: 512M
upload_max_filesize: 2G
post_max_size: 2G
display_errors: true
short_open_tag: false
file_uploads: true
output_buffering: true
open_basedir: 
session.save_path: xxxxxx
session.auto_start: 0
disable_functions: 
xml: true
zlib: true
zip: true
mbstring: true
fileinfo: true
gd: true
iconv: true
intl: true
max_input_vars: 1000
=============
PHP Information
=============

	=============
	apache2handler
	=============
	Apache Version: Apache/2.4.54 (Win64) OpenSSL/1.1.1q PHP/8.2.16
	Apache API Version: 20120211
	Server Administrator: xxxxxx
	Hostname:Port: j443.test:0
	Max Requests: Per Child: 0 - Keep Alive: on - Max Per Connection: 100
	Timeouts: Connection: 60 - Keep-Alive: 5
	Virtual Server: Yes
	Server Root: xxxxxx
	Loaded Modules: core mod_win32 mpm_winnt http_core mod_so mod_access_compat mod_actions mod_alias mod_allowmethods mod_asis mod_auth_basic mod_authn_core mod_authn_file mod_authz_core mod_authz_groupfile mod_authz_host mod_authz_user mod_autoindex mod_cgi mod_dir mod_env mod_headers mod_include mod_isapi mod_log_config mod_mime mod_negotiation mod_rewrite mod_setenvif mod_socache_shmcb mod_ssl mod_version mod_php

	
</details>

### Additional comments
A clean install from github of the 5.1 branch produces the same error

**Comment by alikon** [comment]
is curl extension enabled ?

**Comment by alikon** [comment]
i've got the same result when no curl

**Comment by joomdonation** [comment]
For some reasons, this line of code https://github.com/joomla/joomla-cms/blob/5.1-dev/libraries/src/TUF/TufFetcher.php#L74 hardcode to only allow Curl transport instead of using the available transport (I remember @wilsonge asked about it before)

Could you please try to change that line of code to just:

```php
$this->httpClient    = $httpClient ?? Factory::getContainer()->get(HttpFactoryInterface::class)->getHttp();
```

Then try again to see if it works well ?

**Comment by alikon** [comment]
yes it was on #42900 https://github.com/joomla/joomla-cms/pull/42900#issuecomment-1965480093

**Comment by brianteeman** [comment]
ok so I can confirm it is a curl related issue

With curl enabled - no problems
Without curl enabled - tuf no transport
Without curl enabled AND code change from https://github.com/joomla/joomla-cms/issues/42973#issuecomment-1981314080 - update checks just hang

**Comment by brianteeman** [comment]
As Joomla worked perfectly without curl this should be a release blocker until resolved

**Comment by SniperSister** [comment]
See https://github.com/joomla/joomla-cms/pull/43002
