### ISSUE TITLE
Feature request - toolbar button for Extensions Update on Extensions Mange and vice versa

### ISSUE THREAD

**Issue by rogercreagh** [joomla/joomla-cms#42980]
From Manage Extensions I find I frequently need to go to Update Extensions and vice versa.

In J3 it was easy to move between system installer functions because of the installer specific sub-menu. This of course has gone in J5 (and J4 I guess) and the system menu item on the left doesn't expand. So once you are in the Extension Updater view there is no way to get out without going back to the whole system page and selecting the module you want.

The extension installer and extension manage views both have a toolbar button to get to the other to compensate for the lack of a proper submenu.

Quick and simple fix for my immediate problem would be to provide a toolbar button [Extension Updates] on the Manage view to get to the Updater page, and [Manage Extensions] toolbar button on the Updater page to get out of that page after updating an extension.

A better fix would be to bring back the sub menu for the system menu for top level groups and also to provide better toolbar cross linking between views in a group as above.

Being in the process of updating some J3 sites to J5 I'm finding this a massive loss of admin usability in J5/4.

**Comment by Quy** [comment]
Related #26409

**Comment by rogercreagh** [comment]
> Related #26409

ROFL - I've read that thread, and indeed it is relevant. There is an answer - the hidden setting on the admin menu module to bring back the proper system menu.

WTF this wasn't the default, at least for admins, god only knows. I can see that it might be useful to hide the system menu for non (super-)admins, but 100% of people who are administrators of a joomla site are admins or super-admins and are frequently needing to access these links. Yes that might be only 10% of total 'users' but if you piss them off enough they'll go elsewhere.

The only reason I'm messing with J5 now is that I'm starting a new site and thought I'd give it a try. I needed one of my own components so thought I'd try converting it - nightmare. Completely rewritten. Begining to wish I'd gone the easy route and stuck with J3 for the new site. I certainly won't be converting any of the existing sites to j5 - life is too short.

It all comes down to the stupid decision taken to make J4 more like Wordpress (which itself went mad when it introduced its block editor a while back). Just because other CMS look like that doesn't mean that its a good idea.

What would have been a good idea would have been to in parallel develop a non-breaking update to J3 to use php8 and updated bootstrap & jquery and kept it alive for at least 5 years in parallel.

**Comment by brianteeman** [comment]
I doubt very much that god has any opinion on the Joomla user interface

**Comment by alikon** [comment]
please test #42985
