### ISSUE TITLE
[4.4.3]php Warnings in DatabaseModel.php

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#42981]
### Steps to reproduce the issue
select "system->database" at admin backend 
### Expected result
should see info about db-structures
### Actual result
reports "No problems" but got (php) warning:
```
Warning: Attempt to read property "schemapath" on null in C:\myjoomla\administrator\components\com_installer\src\Model\DatabaseModel.php on line 180

Warning: Trying to access array offset on value of type null in C:\myjoomla\administrator\components\com_installer\src\Model\DatabaseModel.php on line 180
```

### System information (as much as possible)
php v8.2
mySQL V8.1
### Additional comments
warnings are displayed beacuse of php-error reporting

**Comment by alikon** [comment]
do you have any extensions?
can you check if they are compliant to https://docs.joomla.org/Manifest_files#Update_of_the_SQL_Schema
