### ISSUE TITLE
downloadable font: Glyph bbox was incorrect

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#42998]
### Steps to reproduce the issue
Login Admin
Inspect page ... Console

### Expected result
No errors should show

### Actual result
>downloadable font: Glyph bbox was incorrect (glyph ids 1 2 3 4 5 8 9 10 11 12 13 14 16 17 19 22 24 28 32 34 35 38 39 40 43 44 45 46 47 48 49 55 56 58 59 61 63 64 68 76 77 78 82 83 84 85 92 103 108 109 110 113 115 122 123 128 131 134 135 152 155 162 163 164 168 170 171 173 175 176 177 184 187 192 197 202 203 210 213 216 217 218 220 221 223 226 227 234 235 237 238 243 245 247 249 250 254 265 267 268 270 271 272 273 276 277 279 280 283 284 288 291 292 295 297 298 299 302 303 306 309 313 314 317 322 328 329 330 335 336 338 341 343 346 347 350 352 356 357 358 359 364 367 370 371 373 379 381 382 384 388 391 393 394 395 396 398 399 403 405 408 409 410 417 419 420 421 422 437 438 441 446 447 449 453 454 458 460 461 462 465 470 475 477 478 479 482 485 490 491 492 493 496 498 501 502 504 506 507 508 509 511 512 517) (font-family: "Font Awesome 6 Brands" style:normal weight:400 stretch:100 src index:0) source: http://localhost/j502/media/vendor/fontawesome-free/webfonts/fa-brands-400.woff2?v=005c9a
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. fontawesome.min.css:6:237
Elements matching selector: .fa, .fa-classic, .fa-sharp, .fas, [class^="icon-"], [class*=" icon-"], .fa-solid, .far, .fa-regular, .fab, .icon-joomla, .fa-brands
NodeList(122) [ span.fas.fa-bars, span.fas.fa-home.fa-fw, span.fas.fa-wrench.fa-fw, span.fas.fa-users.fa-fw, span.fas.fa-plus.ltr, span.fas.fa-th-large, span.fas.fa-list.fa-fw, span.fas.fa-plus.ltr, span.fas.fa-plus.ltr, span.fas.fa-plus.ltr, … ]
Unknown property '-moz-osx-font-smoothing'.  Declaration dropped. fontawesome.min.css:6:672
Unknown property 'speak'.  Declaration dropped. fontawesome.min.css:6:116274
Error in parsing value for '-webkit-text-size-adjust'.  Declaration dropped. template.min.css:1:5515
Unknown pseudo-class or pseudo-element '-moz-focus-outer'.  Ruleset ignored due to bad selector. template.min.css:1:34911
Ruleset ignored due to bad selector. template.min.css:1:35310
Unknown property 'orphans'.  Declaration dropped. template.min.css:1:245302
Unknown property 'widows'.  Declaration dropped. template.min.css:1:245311
XHRGET
http://localhost/j502/index.php?option=com_ajax&format=raw&plugin=RunSchedulerLazy&group=system
[HTTP/1.1 200 OK 106ms]

### Additional comments
Happens on live site as well as localhost

**Comment by brianteeman** [comment]
System information (as much as possible)
?

**Comment by Webdongle** [comment]
Localhost
PHP Built On 	Windows NT LAPTOP-U0DC46MD 10.0 build 19045 (Windows 10) AMD64
Database Type 	mysql
Database Version 	8.0.27
Database Collation 	utf8mb4_unicode_ci
Database Connection Collation 	utf8mb4_0900_ai_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	Yes
PHP Version 	8.2.15
Web Server 	Apache/2.4.51 (Win64) PHP/8.2.15 mod_fcgid/2.3.10-dev
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 5.0.3 Stable [ Kuboresha ] 20-February-2024 16:00 GMT
Joomla Backward Compatibility Plugin 	Enabled (classes_aliases:"1", es5_assets:"1")
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0 

Livesite
PHP Built On 	Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Database Type 	mysql
Database Version 	10.6.15-MariaDB-1:10.6.15+maria~deb11-log
Database Collation 	utf8mb3_general_ci
Database Connection Collation 	utf8mb4_general_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	Yes
PHP Version 	8.2.16
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 5.0.3 Stable [ Kuboresha ] 20-February-2024 16:00 GMT
Joomla Backward Compatibility Plugin 	Enabled ()
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42998">issues.joomla.org/tracker/joomla-cms/42998</a>.</sub>

**Comment by heelc29** [comment]
Please check: https://github.com/joomla/joomla-cms/pull/42721

**Comment by Webdongle** [comment]
Yes that looks like the same error.  Can't test it because patch tester does not work on my test site.  But closing in favour of #42721
