### ISSUE TITLE
SiteRouter in system plugin constructor or service provider causes 404

### ISSUE THREAD

**Issue by joeforjoomla** [joomla/joomla-cms#42991]
### Steps to reproduce the issue
Any system plugin used to get a SiteRouter instance from the container in the constructor or in the service provider, causes a 404 page

Include a call to: Factory::getContainer()->get('SiteRouter')
in a system plugin  constructor or in its service provider

### Expected result
All works in B/C way

### Actual result
404 Page not found

### System information (as much as possible)
Joomla 5.1 Beta 1

![404pages](https://github.com/joomla/joomla-cms/assets/17835460/02c52356-44ae-419b-bd3b-1a6b47cf8227)

**Comment by Hackwar** [comment]
Closing since we have a PR: #43009
