### ISSUE TITLE
[5.1] Adjust loading background color in dark mode

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#43014]
### Steps to reproduce the issue
Go to System > Install > Language
Install a language.

![42986-loading-bg](https://github.com/joomla/joomla-cms/assets/368084/6b1328fc-97f3-4048-996a-585087060bf1)

**Comment by Quy** [comment]
Maybe a light grey.

**Comment by Quy** [comment]
Related request: https://github.com/joomla/joomla-cms/pull/42757#issuecomment-1964823935

**Comment by brianteeman** [comment]
please try #43018

**Comment by dgrammatiko** [comment]
Please test https://github.com/joomla/joomla-cms/pull/43023

**Comment by Quy** [comment]
@brianteeman @dgrammatiko Thank you!
