### ISSUE TITLE
Smart search showing unpublished articles in auto suggest

### ISSUE THREAD

**Issue by kalyan227** [joomla/joomla-cms#4301]
Using Joomla 2.5.20 version .

Created a article . It is indexed in Smart search section. Now i tried to search the same word in SEARCH module . It is showing in Smart search auto suggest without any issue.

Now I  have unpublished article in article Manager. 
Now i tried to search the same word in SEARCH module . In Search module  i can see the unpublished article title showing in aut suggest . which is not correct and search results are coming as expected "No results found" as the article is unpublished which is ok. 

I wanted to hide unpublished articles from Smart search auto Suggestions

**Comment by brianteeman** [comment]
Closing as we have a PR #4401 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4301">issues.joomla.org/joomla-cms/4301</a>.</sub>
