### ISSUE TITLE
Frontend Images and Links not displaying properly

### ISSUE THREAD

**Issue by stormskipper** [joomla/joomla-cms#43019]
### Steps to reproduce the issue

I switched on Display Frontend Images and links, so I can edit these from the front end.
(Options / Articles/Editing Layout / Frontend Images and Links - Show
The images don't show.
Tried JCE, TinyMCE and NoEditor - all the same.

Also if you click on "select" to select an image you get a greyed out modal box and the only way out is to refresh the page.

### Expected result

Displays images in front end editor Images and Links tab. Click on Select image and you can actually select an image.

### Actual result

No images displayed on the Images and Links tab. Greyed out modal box when you click on Select image.

### System information (as much as possible)

For the Images and Links tab:

Fired up the console and it's giving me 
Uncaught TypeError: window.bootstrap.Modal.getInstance is not a function
    at HTMLElement.connectedCallback (joomla-field-media.min.js?7b9940:4:3220)
    at joomla-field-media.min.js?7b9940:4:8331

The code it's objecting to in joomla-field-media.min.js is:
        if (this.button.addEventListener("click", this.show),
        this.modalElement && window.bootstrap && window.bootstrap.Modal && !window.bootstrap.Modal.getInstance(this.modalElement) && Joomla.initialiseModal(this.modalElement, {
            isJoomla: !0
        }),

It doesn't like getInstance(this.modalElement) && Joomla.initialiseModal(this.modalElement,

When you click the Select button the error is:
Uncaught TypeError: window.bootstrap.Modal.getInstance is not a function
    at HTMLElement.connectedCallback (joomla-field-media.min.js?7b9940:4:3220)
    at joomla-field-media.min.js?7b9940:4:8331

This bit of code:
 if (this.button.addEventListener("click", this.show),
        this.modalElement && window.bootstrap && window.bootstrap.Modal && !window.bootstrap.Modal.getInstance(this.modalElement) && Joomla.initialiseModal(this.modalElement, {
            isJoomla: !0
        }),

### Additional comments
Joomla 5.0.3 - all up to date

**Comment by dgrammatiko** [comment]
Please confirm that your browser is supporting [Import Maps](https://caniuse.com/import-maps) (ie the version is in the green ones)

**Comment by dgrammatiko** [comment]
Then remove jce and try again

**Comment by stormskipper** [comment]
![imagesandlinks](https://github.com/joomla/joomla-cms/assets/96434783/a17f049a-f5d6-413c-bfcd-bb2c9995723b)

Removed jce - just the same

**Comment by stormskipper** [comment]
Ah - it's a template problem. I switched to Cassiopia and that is ok.
I'm using ja-stark.
I'll have to ask them.
