### ISSUE TITLE
Tags result of article summary error 0 a key is required

### ISSUE THREAD

**Issue by wegwb** [joomla/joomla-cms#43012]
### Problem identified
If i choose a tag to show associated articles the system runs in a call stack: 
# | Function | Location
-- | -- | --
1 | () | JROOT/libraries/vendor/joomla/database/src/DatabaseQuery.php:1994
2 | Joomla\Database\DatabaseQuery->bind() | JROOT/libraries/vendor/joomla/database/src/DatabaseQuery.php:2108
3 | Joomla\Database\DatabaseQuery->bindArray() | JROOT/libraries/vendor/joomla/database/src/DatabaseQuery.php:1879
4 | Joomla\Database\DatabaseQuery->whereIn() | JROOT/libraries/src/Helper/TagsHelper.php:628
5 | Joomla\CMS\Helper\TagsHelper->getTagItemsQuery() | JROOT/components/com_tags/src/Model/TagModel.php:154
6 | Joomla\Component\Tags\Site\Model\TagModel->getListQuery() | JROOT/libraries/src/MVC/Model/ListModel.php:222
7 | Joomla\CMS\MVC\Model\ListModel->_getListQuery() | JROOT/libraries/src/MVC/Model/ListModel.php:271
8 | Joomla\CMS\MVC\Model\ListModel->getItems() | JROOT/components/com_tags/src/Model/TagModel.php:99
9 | Joomla\Component\Tags\Site\Model\TagModel->getItems() | JROOT/libraries/src/MVC/View/AbstractView.php:152
10 | Joomla\CMS\MVC\View\AbstractView->get() | JROOT/components/com_tags/src/View/Tag/HtmlView.php:139
11 | Joomla\Component\Tags\Site\View\Tag\HtmlView->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:660
12 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT/components/com_tags/src/Controller/DisplayController.php:68
13 | Joomla\Component\Tags\Site\Controller\DisplayController->display() | JROOT/libraries/src/MVC/Controller/BaseController.php:693
14 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
15 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT/libraries/src/Component/ComponentHelper.php:361
16 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT/libraries/src/Application/SiteApplication.php:208
17 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT/libraries/src/Application/SiteApplication.php:249
18 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT/libraries/src/Application/CMSApplication.php:293
19 | Joomla\CMS\Application\CMSApplication->execute() | JROOT/includes/app.php:61
20 | require_once() | JROOT/index.php:32

Joomla Version 4.43  updated from J3, J 2.5, J 1 . Previously used K2 CCK and migrated data into regular Joomla articles

PHP erstellt für | Linux server25 5.4.270-1.el8.elrepo.x86_64 #1 SMP Fri Mar 1 17:08:26 EST 2024 x86_64
-- | --
mysql
8.0.36
utf8mb3_unicode_ci
utf8mb4_0900_ai_ci
Keine
Nein
8.2.16
Apache
cgi-fcgi
Joomla! 4.4.3 Stable [ Pamoja ] 20-February-2024 16:00 GMT
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:123.0) Gecko/20100101 Firefox/123.0
----------------------------------------------------------------------------------------------------

### Proposed solution
I havent yet but i think there are some problems with the db table structure

### Open questions
How can i fix this issue?

**Comment by Hackwar** [comment]
Did you go to System -> Database and clicked repair?

**Comment by Hackwar** [comment]
I looked into this a bit deeper and it seems as if your `#__content_types` table is not correct. It should contain several entries, on a default Joomla 5 site it should be at least 13. It seens as if your table does not containt the necessary data.

**Comment by Quy** [comment]
@Hackwar Can this be closed?

**Comment by wegwb** [comment]
Hey @Hackwar your solution  bring me a step forward.  No errors - But if i choose a tag to show any related article  the result is:  no entrys found. Is there any other table that ive to check?

**Comment by Hackwar** [comment]
The content has to be in the #__ucm_content table as well. I would ask you to get further support at for example forum.joomla.org Since this seems to be an issue of a broken installation and not of a bug in Joomla, I'm going to close this. Thanks for reporting.
