### ISSUE TITLE
[5.1] Install from Web in dark mode

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#43016]
### Steps to reproduce the issue
Go to System > Install > Extensions > Install from Web
Click List View button.
Hover an extension.
Click on an extension.

![install-from-web-list-view](https://github.com/joomla/joomla-cms/assets/368084/eb3eb192-f877-48bc-9a28-352278aac978)

![install-from-web-detail](https://github.com/joomla/joomla-cms/assets/368084/34c1672c-d3d2-4687-b333-e31cb9e0d802)

**Comment by brianteeman** [comment]
Please test #43017

**Comment by alikon** [comment]
closing as we have a pr #43017
