### ISSUE TITLE
[5.1] Error in joomla-field-media.js

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#43022]
### Steps to reproduce the issue
Install the nightly build, then the demo data. Go to the front, log in, a menu will be available on the right - select template settings.

Pay attention to the LOGO item. The buttons for selecting an image also do not work.

![Screenshot_1](https://github.com/joomla/joomla-cms/assets/8440661/21ffdf9f-5d8b-4334-ad25-57ea56908cdc)

The console reports a problem in `media/system/js/fields/joomla-field-media.js`:

> Uncaught TypeError: The specifier "joomla.dialog" was a bare specifier, but was not reassigned to anything. Associated module specifiers must begin with "./", "../" or "/".

**Comment by dgrammatiko** [comment]
Please confirm that your browser is supporting [Import Maps](https://caniuse.com/import-maps) (ie the version is in the green ones)

**Comment by Kostelano** [comment]
Sorry, I forgot to mention the browser. I use Firefox, the latest version available - 123.0.1 x64.

**Comment by Quy** [comment]
@Fedik

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/43080
