### ISSUE TITLE
[5.1.0]: Difference in positioning of menu/top toolbar between Light/Dark Mode - Admin backend

### ISSUE THREAD

**Issue by exlemor** [joomla/joomla-cms#43029]
### Steps to reproduce the issue
Log in to Joomla 5.1.0 and switch between Light Mode and Dark Mode... you will notice that the menu on the left side feels like it is 
moving and the top menu bar on the right is growing/shrinking [due to additional border pixels]

### Expected result
The switching of Light/Dark mode should not 'change' the look of the layout.

### Actual result
The menu on the left moves down 1-2 pixels and the menu on the top right [User menu, etc] grows/shrinks due to an additional border pixel being added/removed.

### System information (as much as possible)
Macbook Pro Intel i9 / Safari version 17.3.1 (19617.2.4.11.12)
MySQL version | 8.0.36
PHP version | 8.2.16

**Comment by exlemor** [comment]
![J5 1-new-Light-Mode](https://github.com/joomla/joomla-cms/assets/2597232/202e17e7-4022-4464-8954-a9d9b291bedc)
![J5 1-new-Dark-Mode](https://github.com/joomla/joomla-cms/assets/2597232/fe0bd0ae-fe06-49ba-b043-c104e8cf8101)

**Comment by brianteeman** [comment]
Confirmed maybe this gif will demo it better than a still image

![epicpen_cNnnKQjmxt](https://github.com/joomla/joomla-cms/assets/1296369/a9feea99-9773-440f-8d28-c1e394323a19)

**Comment by brianteeman** [comment]
please test #43138
