### ISSUE TITLE
Guided Tours fails to autostart

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#43026]
Last night the welcome to joomla guided tour was merged with autostart functionality. My understanding was that this means that the tour started automatically when you log in to admin - unless you have dismissed it.

I have done a completely new install and verified in the database that autostart=1 for the tour

I have cleared all cookies, cache and local storage

I log in to the admin and the tour does not autostart 

I check the db and see that it now says autostart=0

If anyone else can replicate this then its a release blocker as this is a main new feature

**Comment by obuisard** [comment]
Thanks Brian,
I have created a new install (using MySQL) and the tour started. So far, I cannot replicate it.

**Comment by brianteeman** [comment]
I found the problem but its almost certain that no one would do that in the real world so can be closed
