### ISSUE TITLE
[5.1.0]: Changing Assigned User Groups in Users in Batch mode fails with error

### ISSUE THREAD

**Issue by exlemor** [joomla/joomla-cms#43032]
### Steps to reproduce the issue
Created 2 test users, test-user-2 and test-user-3, gave them Administrator and Publisher & Manager permissions respectively.
Then used User -> Actions -> Batch -> to Add to Group: Editor those 2 users with Add to Group option and Require Password Reset: No selected. Finalize with Process button which gives error found in ### Actual Result section below

### Expected result
Just like in J5.0.3, it should change the Users Groups - in this case add Editor to their permissions.

### Actual result
error in orange appears: 
Batch process failed with following error: Insufficient information to perform the batch operation.

![screenshot_2446](https://github.com/joomla/joomla-cms/assets/2597232/4f709635-e1b0-4f9d-b712-fda04861e955)

(Also, why is this a warning in orange when the operation fails - shouldn't it be in red?)

### System information (as much as possible)
Macbook Pro Intel i9 / Safari version 17.3.1 (19617.2.4.11.12)
MySQL version | 8.0.36
PHP version | 8.2.16

**Comment by brianteeman** [comment]
> (Also, why is this a warning in orange when the operation fails - shouldn't it be in red?)

yes probably - there are quite a few inconsistencoes like that

**Comment by alikon** [comment]
please test #43050

**Comment by exlemor** [comment]
@alikon Thank you so much for fixing that! you rock! 🚀
