### ISSUE TITLE
[5.1] Guided Tours broken in 5.1.0-beta2-dev

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#43040]
### Steps to reproduce the issue

Using a repo clone: git pull; npm ci;

### Expected result

All working yesterday.

### Actual result

Message above Home Dashboard:
```
Warning
: Attempt to read property "autostart" on null in
/Users/ceford/Sites/joomla-cms5/plugins/system/guidedtours/src/Extension/GuidedTours.php
on line
166
```

Select a tour: Red error message: Oh no! It looks like your tour is off track. The tour exited and cannot run.

### System information (as much as possible)

Firefox on MacOS. Joomla 5.1.0-beta2-dev updated today.

**Comment by alikon** [comment]
iirc you need to run https://github.com/joomla/joomla-cms/blob/5.1-dev/administrator/components/com_admin/sql/updates/mysql/5.1.0-2024-03-08.sql

**Comment by ceford** [comment]
Thanks for that - problem fixed.
