### ISSUE TITLE
Better clarification is needed for MySQL database installation of Joomla 5.0.3

### ISSUE THREAD

**Issue by davidalanroth** [joomla/joomla-cms#43049]
During the installation of Joomla 5.0.3 of the MySQL database it asks the user to:

Either a username you created or a username provided by your host.
Either a password you created or a password provided by your host. 

For better clarification, I believe it should be changed to make it clear this is a username for the MySQL database user, and the MySQL database user password. There are two video tutorials I have seen where it shows people enter "root" which may work in some installations, but it isn't clear this is the root to administrate the MySQL database or the root user on a Linux server. It needs to be clear this is for the MySQL database user and the accompanying password, and not the server or hosting account login credentials. I propose these two messages be changed to:

Enter the MySQL database username you created or is provided by your host.
Enter the MySQL database username's password you created or is provided by your host.

**Comment by richard67** [comment]
Joomla also supports MariaDB and PostgreSQL, so the suggested text with „MySQL“ would be wrong.

**Comment by davidalanroth** [comment]
The installation page prompts the user for MySQLi as selected. So only
MySQL input fields should be valid to collect and the message displayed
asking for input. If PostgreSQL requires something else, there should be a
screen for PostgreSQL. MariaDB is the same as MySQL. I've been using Joomla
since 2006, and this is one of those things that makes it confusing for new
people to use Joomla. We need to be looking to make it easier for new
people to use Joomla.

**Comment by brianteeman** [comment]
Follwoing that reasoning then it should also say that the hostname is not the server name or the domain name. But we dont do that because it would make no sense as we are on the database configuration page. Which is why we would not expect you to enter your hosting username in the following fields.

**Comment by davidalanroth** [comment]
It isn't clear to new people what to do from my experience. This is the
feedback I've been getting. I recommend Joomla and people abandon it
telling me they couldn't finish installing it. A small change would matter,
because if you can't get past installation, you can't see the benefits over
the other CMS systems. I realize it is more work to improve something to
make it more intuitive for new people to use. Think of it from the point of
view of a person new to Joomla who might never have used a CMS or a
database before. I'm not alone in seeing people recommend to their employer
these commercial CMS products when we all know Joomla would have entirely
handled their organizations needs. It is troublesome that since I started
with Joomla in 2006 that the audience of Joomla enterprise users is much
smaller than it should be.

**Comment by brianteeman** [comment]
I dont see the need myself but here is a pull request that changes the text used during the installation so others can decide

#43049

**Comment by davidalanroth** [comment]
![Screenshot 2024-03-16 at 6 45 17 AM](https://github.com/joomla/joomla-cms/assets/294931/c9a8a52d-45d1-4e73-adac-80cd8f382d84)

Latest of what Drupal is doing for Database Configuration during installation (attached screenshot) just to get another data point.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #43054 . Thanks in advance.
