### ISSUE TITLE
[5.1] Sample Data install fails

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#43047]
### Steps to reproduce the issue
Try to install the same data and it just hangs

browser console says

![image](https://github.com/joomla/joomla-cms/assets/1296369/17925d62-b71c-4cab-910c-cb9934ba0299)
```

Uncaught TypeError: Cannot read properties of undefined (reading 'icon')
    at sampledataAjax (sampledata-process.min.js?8e9c3e:4:506)
    at sampledataApply (sampledata-process.min.js?8e9c3e:4:2676)
    at HTMLButtonElement.<anonymous> (sampledata-process.min.js?8e9c3e:4:2905)

```

**Comment by Fedik** [comment]
I cannot reproduce. I tried on latest 5.1 branch, and it works fine. 

I can get an error only when enable "show error maximum", but even then I get an error message instead of "hangs".
(however this is because PHP deprecation, I think it a known issue)

**Comment by richard67** [comment]
> Try to install the same data and it just hangs

@brianteeman Typo „same“/„sample“? Or did you mean „Try to install the same sample data again“?

**Comment by brianteeman** [comment]
found the problem localy - needed to rebuild the js scripts.
