### ISSUE TITLE
[5.1] Help not configured

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#43041]
### Steps to reproduce the issue

In 5.1 select any Help button

Or this URL as an example:

https://help.joomla.org/proxy?keyref=Help51:Site_Global_Configuration&lang=en

### Expected result

A Help screen

### Actual result

A 404

### Additional comments

I would like to see the proxy changed so that all versions of 5.x fetch the same content.

**Comment by brianteeman** [comment]
two different problems here.

1. proxy on the help server needs updating
2. php build/helpToc.php needs to be run to update the index

Both of these are always missed on new releases

**Comment by ceford** [comment]
I think @wilsonge usually takes care of this. I don't know if anyone else knows what to do.

**Comment by brianteeman** [comment]
This should be marked as a release blocker

**Comment by Quy** [comment]
This is no longer an issue in v5.1rc.

**Comment by brianteeman** [comment]
yes it is still an issue. 
> two different problems here.
> 
> 1. proxy on the help server needs updating
> 2. php build/helpToc.php needs to be run to update the index
> 
> Both of these are always missed on new releases

Only the proxy has been done

**Comment by brianteeman** [comment]
This can probably be closed now that we have the great new pr from @LadySolveig #43250 #43251

**Comment by ceford** [comment]
Agree!
