### ISSUE TITLE
permissions to edit, delete, etc. tags when editing on the front page do not work

### ISSUE THREAD

**Issue by pablop76** [joomla/joomla-cms#43048]
### Steps to reproduce the issue
Create a user and assign it to a group, e.g. Manager
Set global configuration -> tags -> permissions -> manager -> deletion -> Disallowed

### Expected result
Log in to the front of the page, edit the article and remove the tag.
This should be impossible

### Current result
The user can still remove tags

### System information (as much as possible)
Joomla 4, Joomla 5
php 8.1

### Additional comments

**Comment by brianteeman** [comment]
The delete permission you have set is to control deletion of the tag NOT the removal of a tag from an article.

To the best of my knowledge its not possible to prevent someone who can edit an article from being able to add or remove tags. 

However the folks at forum.joomla.org will probably know more.

This is not a bug and can be closed
