### ISSUE TITLE
[5.1] Joomla Darkmode Save as Submenu

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#43059]
### What needs to be fixed
Wrong colors in submenu of the save button
<img width="251" alt="grafik" src="https://github.com/joomla/joomla-cms/assets/828371/cff9df84-da6e-4b10-8943-3f7bc28d73ec">

**Comment by brianteeman** [comment]
what is wrong? It looks consistent to me

**Comment by coolcat-creations** [comment]
Thought the background should be green or not? We can leave it like that if the contrast ist enough

**Comment by brianteeman** [comment]
The other backgrounds on dropdowns are not coloured. 

And I see it as being consistent with the published box. 
![image](https://github.com/joomla/joomla-cms/assets/1296369/b94a88bf-f6e3-49b0-9f71-2cfa60d31ede)
![image](https://github.com/joomla/joomla-cms/assets/1296369/0ed1c3bf-74ff-4ed5-a1bc-dfc8ba15de42)



As for the contrast maybe the accessibility team can comment.

**Comment by Quy** [comment]
Here is one that is colored.

![43059-menu](https://github.com/joomla/joomla-cms/assets/368084/69bb5486-989f-47b0-bb1f-61596a3b7d5a)

**Comment by brianteeman** [comment]
that one is coloured in both light and dark

**Comment by coolcat-creations** [comment]
Ok thank you, will close it then :)
