### ISSUE TITLE
UX: Save ¦ Close button are in the reverse order in modal windows

### ISSUE THREAD

**Issue by jsubri** [joomla/joomla-cms#43062]
### Steps to reproduce the issue
Existing site or a fresh install with sample data+ create a new contact
Main Menu => Add a new menu => Menu Item Type = "Single Contact"
Pick the newly created contact, stay in that form
use the Edit button for this contact
Bottom of the modal the Close button is on the left side and Save on the right side

### Expected result

Save ¦ Save & Close ¦ Close

### Actual result

![save](https://github.com/joomla/joomla-cms/assets/5349333/d9ce8c80-c097-4bda-932c-84bcf5dd8cde)

### System information (as much as possible)

J4.4, J5.03
PHP 8.2

### Additional comments
We have the same behavior in the modal window for Content - Edit a single article

**Comment by brianteeman** [comment]
As the modals have been re-written for j5 please check to see if the problem exists there

**Comment by Quy** [comment]
Closing as not an issue in v5.1.

![43062](https://github.com/joomla/joomla-cms/assets/368084/4256ec83-b03d-40e9-8f60-dd829f5157d0)
