### ISSUE TITLE
[5.1] Add module dialog - close button

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#43077]
### Steps to reproduce the issue

In your administrator dashboard, click on "Add module to the dashboard" to open the dialog.

The close the dialog using the "X" button in the top right.

### Expected result

Modal closes

### Actual result

The modal closes, but then the page instantly refreshes

![image](https://github.com/joomla/joomla-cms/assets/2019801/5c20d02d-7dff-46f1-bead-590045cb1295)

**Comment by Fedik** [comment]
It is by design
