### ISSUE TITLE
[5.1] Custom module not visible on dashboard

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#43078]
### Steps to reproduce the issue

1. In your administrator dashboard, click on the "User Dashboard" button
![image](https://github.com/joomla/joomla-cms/assets/2019801/7d2d14e9-8920-4ec3-b709-f36f71ce764c)

2. Click on "Add module to the dashboard"
![image](https://github.com/joomla/joomla-cms/assets/2019801/403708df-e885-4249-9c5d-f52789617218)

3. Select a "Custom" module type
4. Add some dummy content (position is already pre-populated)
5. Click "Save"

### Expected result

Module should be visible on the User dashboard

### Actual result

Module not visible

**Comment by Fedik** [comment]
hm, cannot reproduce, it works for me.
What the position name in the module form popup? Should be `cpanel-users`

**Comment by C-Lodder** [comment]
I'll try a fresh install later on today.

The position was pre-populated with `cpanel-users`

**Comment by brianteeman** [comment]
It is possible that it is published and you didnt see it as it was not where it expected it to be - that's just happened to me. I was looking at the bottom of the page for the newly created module but it was actually near the top

**Comment by brianteeman** [comment]
@C-Lodder did you resolve this?
