### ISSUE TITLE
[5.0,4.4] Finder: part of search input data is not available for plugins (code)

### ISSUE THREAD

**Issue by pioada** [joomla/joomla-cms#43087]
### Steps to reproduce the issue
Create a plugin that will change search input data, eg. rename from custom project to Joomla! data names, add input data, etc.

### Expected result
The plugin should be able to access / change all search input data.

### Actual result
The plugin can access / change ONLY sort input data ("o" and "od" parameters).

### System information (as much as possible)
Joomla 4.4.3. Same in 5.0.3.

### Additional comments
Problem is in components/com_finder/src/Model/SearchMode in populateState function.
Order input data is retrieved from "input data", and that is whay it is available for plugins (code).
All other data is retrieved from "input request data" and thats whay it is not available for plugins.
Changing $request to $input make it works as expected.

**Comment by Hackwar** [comment]
I created a PR to change this: #43091 Since we have a PR, I'm closing this issue. Please have a look and test the PR.
