### ISSUE TITLE
Cannot set up Cron Task for Smart Search in Joomla 4 / 5

### ISSUE THREAD

**Issue by Gratia-Mira** [joomla/joomla-cms#43099]
### Steps to reproduce the issue
Create a cron taks:
php -d memory_limit=512M httpdocs/cli/joomla.php finder:index

### Expected result
Task is successfully completed

### Actual result
Error message:
```
Symfony\Component\ErrorHandler\Error\UndefinedFunctionError {#164
  #message: "Attempted to call function "simplexml_load_file" from namespace "Joomla\CMS\Language"."
  #code: 0
  #file: ".httpdocs/libraries/src/Language/LanguageHelper.php"
  #line: 614
  trace: {
    .httpdocs/libraries/src/Language/LanguageHelper.php:614 {
      Joomla\CMS\Language\LanguageHelper::parseXMLLanguageFile($path)
      › // Try to load the file
      › $xml = simplexml_load_file($path);
      › 
    }
    .httpdocs/libraries/src/Language/LanguageHelper.php:516 { …}
    .httpdocs/libraries/src/Language/Language.php:203 { …}
    .httpdocs/libraries/src/Language/LanguageFactory.php:35 { …}
    .httpdocs/libraries/src/Language/CachingLanguageFactory.php:45 { …}
    .httpdocs/libraries/src/Service/Provider/Application.php:130 { …}
    .httpdocs/libraries/vendor/joomla/di/src/ContainerResource.php:176 { …}
    .httpdocs/libraries/vendor/joomla/di/src/Container.php:96 { …}
    .httpdocs/cli/joomla.php:75 { …}
  }
}
```

### System information (as much as possible)
Joomla 4 and 5
Linux
Plesk

### Additional comments
SimpleXML is enabled
https://joomla.stackexchange.com/questions/33733/cannot-set-up-cron-task-for-smart-search-in-joomla-4

**Comment by brianteeman** [comment]
The answers give in stackexchange seem correct. Ig you enter php -v at the command line what is the output

**Comment by Gratia-Mira** [comment]
It is actually a precautionary measure taken by the provider. 

Is there a way to call this task (https://www.edition-nehemia.ch/j3/administrator/index.php?option=com_finder&view=indexer&tmpl=component) via the Scheduled Tasks plugin?
A simple request (with token) doesn't seem to work either?

In other words, it would help me if you could tell me the function that triggers indexing.

**Comment by alikon** [comment]
`It is actually a precautionary measure taken by the provider.`

ask them to allow you to execute that cron task

not a core issue imho
