### ISSUE TITLE
Pb upload Large pdf file to Joomla 4

### ISSUE THREAD

**Issue by Mika17420** [joomla/joomla-cms#43096]
### Steps to reproduce the issue
I try to transfer a PDF file to the image folder of my Joomla 4. But it keeps telling me that the file is too large.
My php settings are good at 8Mo and last try 64Mo. The media/config setting is 4MB. But as soon as I send my pdf which is 1.7 MB it systematically reduces the media settings to 2 MB.
I tried to change the settings in php myadmin and it systematically resets 2MB in the settings
I have several sites and the problem is the same everywhere
an idea ?

**Comment by Quy** [comment]
Please use Joomla forum for support questions. https://forum.joomla.org/

**Comment by Mika17420** [comment]
I'm sorry.
I already did it but no answers. And so I have the impression that it could be a bug in Joomla

**Comment by Quy** [comment]
In php.ini, please check `post_max_size`

```
; Maximum size of POST data that PHP will accept.
; Its value may be 0 to disable the limit. It is ignored if POST data reading
; is disabled through enable_post_data_reading.
; https://php.net/post-max-size
post_max_size=40M
```

**Comment by Mika17420** [comment]
Thanks Quy.
This is already what I did
post_max_size : 64MB
upload_max_filesize 64 MB too
Afterwards I set the max upload in media to 10 MB. This seems to register but when I leave the page where I try to download a file it systematically gives me 2 MB. Even if I go directly to change the settings in php mysql

**Comment by Quy** [comment]
Go to System > Extensions.
What is the `Maximum upload size` value?
If it is 2MB, then please consult with your hosting provider to custom override this value.

**Comment by Mika17420** [comment]
as I said previously:
upload_max_filesize 64 MB

**Comment by Mika17420** [comment]
![params](https://github.com/joomla/joomla-cms/assets/17899369/f05ecc8e-4045-4c60-9b59-582a6b64d669)

**Comment by Mika17420** [comment]
> Go to System > Extensions. What is the `Maximum upload size` value? If it is 2MB, then please consult with your hosting provider to custom override this value.

![upload](https://github.com/joomla/joomla-cms/assets/17899369/20634c9c-78fe-43e7-b3e5-c971c3ece38d)
sorry, maybe this was the answer you wanted ?

**Comment by Mika17420** [comment]
Any changes I make to the media settings are not saved. By checking in the mysql table, I can observe the change but as soon as I refresh the page the initial configuration reappears
