### ISSUE TITLE
[5.1] Dark Mode final Version. Not view select item in control select

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#43097]
field `folderlist` in custom module for 
```XML
<field type="folderlist" multiple="true" />
```
![изображение](https://github.com/joomlagerman/joomla/assets/6898474/24dfc765-b9c8-43bb-86ab-86f82f50c68f)

**Comment by brianteeman** [comment]
Not sure I understand you OR I cannot replicate

I changed `plugins\fields\imagelist\imagelist.xml` so that the first field has multiple="true"

D:\repos\j51\plugins\fields\imagelist\imagelist.xml

**Comment by brianteeman** [comment]
Never mind I see the problem now that I saved the form. There is abackground but it is hard to see

**Comment by coolcat-creations** [comment]
This should have been fixed by https://github.com/joomla/joomla-cms/pull/44211 can you test?

**Comment by Quy** [comment]
Confirmed fix. Thanks for the report.
