### ISSUE TITLE
Menu javascript accessibility error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#43101]
### Steps to reproduce the issue
Create a menu with at least one menu item of type URL that has an icon class as shown in the screenshot below

![image](https://github.com/joomla/joomla-cms/assets/1296369/f3761c8c-3b34-4e35-8b60-6b1196a04c88)

Display that menu in a module with the default layout

![image](https://github.com/joomla/joomla-cms/assets/1296369/0e1eb733-fbd9-4382-86ed-d29221a67f5a)

Visually this will be displayed correctly 

![image](https://github.com/joomla/joomla-cms/assets/1296369/57909559-7e8d-4714-a7d8-c868ed11d267)

However if you look at the generated code you will see that the icon has been given focus by the addition of a tabindex.

![image](https://github.com/joomla/joomla-cms/assets/1296369/b4d50c5c-9d42-4c4a-80f2-9c1268fce03d)

This causes several accessibility and usability problems. 

**ARIA hidden element must not be focusable or contain focusable elements**
Using the aria-hidden="true" attribute on an element removes the element and ALL of its child nodes from the accessibility API making it completely inaccessible to screen readers and other assistive technologies, That is what we want for the icon BUT the addition of the tabindex now gives it focus. 

So now the menu item has two focussable elements but only one of them does anything. For example if you are tabbing through the page you will need to tab twice. Once to focus on the icon (which does nothing as it is hidden) and a second time to focus on the link.

![meu](https://github.com/joomla/joomla-cms/assets/1296369/cd12d9ac-8e13-44e9-983b-78aadf79a98d)

I believe that the problem is locaated in the javascript here 

https://github.com/joomla/joomla-cms/blob/3db2bf32bf567679a5b41ae1382e38de62ddff3e/build/media_source/mod_menu/js/menu.es6.js#L40-L45

**Comment by C-Lodder** [comment]
I have a feeling this was done for icons that trigger a dropdown menu, or maybe menu items with a `separator` type.
The core template has changed drastically since J4 was first worked on, so dropdowns now use the correct semantics.

Maybe the logic can be changed so that `tabindex` is only added to the `<span>` when the parent element is not `<a>`?

Like so:

```
if (spanEl) { 
   if (spanEl.parentNode.nodeName !== 'A') {
     spanEl.tabIndex = '0';
   }
   spanEl.addEventListener('mouseover', topLevelMouseOver(topLevelEl, settings)); 
   spanEl.addEventListener('mouseout', topLevelMouseOut(topLevelEl, settings)); 
 } 
```
