### ISSUE TITLE
SEF links in J4 different from J3 (in J3 the SEF is correct)

### ISSUE THREAD

**Issue by peterhulst** [joomla/joomla-cms#43104]
### Steps to reproduce the issue
J3.10.12 and 4.4.3
- Search Engine Friendly URLs: Yes
- Use URL Rewriting: Yes
- Articles with keyword(s)
- Publish e.g. module Articles - Related
- Display the same article in J3 and J4.
- Look at the links in module Articles - Related

### Expected result
- SEF-Links in J3 and J4 are equal e.g.:
- https://(domain)/186-uitslagen-2008-2017/buurcontactommelander-loopcircuit-200817/845-eemsmondloop-Uithuizermeeden-10-en-5-km-18-september-2010

### Actual result
- SEF-Links in J3 and J4 are different. In J4 no SEF is visible.
- J3: https://(domain)/186-uitslagen-2008-2017/buurcontactommelander-loopcircuit-200817/845-eemsmondloop-Uithuizermeeden-10-en-5-km-18-september-2010
**- J4: https://(domain)/?view=article&id=845:eemsmondloop-Uithuizermeeden-10-en-5-km-18-september-2010&catid=186**

### System information (as much as possible)
J3.10.12 and 4.4.3
- Search Engine Friendly URLs: Yes
- Use URL Rewriting: Yes
- Articles with keyword(s)

### Additional comments
- It happens with converted articles (from J3 --> J4) as well as new articles
- The articles are not linked to a menu item.

**Comment by Hackwar** [comment]
The last line in your description is what is the main point in this. This is not a bug, but actually expected behavior. At least more or less. Yes, we would want to have a URL without query parameters, but that is already tackled by #42989. But besides that, this is intended behavior and you would have to create the right menu structure for your site to work in such a manner.

**Comment by peterhulst** [comment]
Thanks you for your answer.  Although it is expected behaviour, it does not explain the difference between J3 (with nice URLs) an J4 (with ugly URLs). Has  the router in J4 changed that much and why? The menu structure is not changed between my J3 an J4 version.

**Comment by Hackwar** [comment]
The router between 3 and 4 has been made more strict and to bail earlier when the resulting URL would not be desirable. However, as I wrote, there is one change in there, which I'm trying to fix with #42989. Feel free to test that PR.
