### ISSUE TITLE
[5.1] Can't be updated to Joomla ‎5.1.0-beta2

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#43100]
### Steps to reproduce the issue
I use the DEFAULT update channel. There is a problem with updating to beta 2.

Technical requirements have been met, based on the information on the page https://manual.joomla.org/docs/next/get-started/technical-requirements.

_PHP 8.1,
MariaDB 10.8,
Apache 2.4_

![Screenshot_1](https://github.com/joomla/joomla-cms/assets/8440661/e34fd1cb-43df-42f6-bf8b-8a4e9cdfa4b3)

**Comment by Kostelano** [comment]
If you change the channel, for example, to Testing and select the Beta level (and earlier), you can update.

**Comment by richard67** [comment]
@Kostelano From which version are you updating? From 5.1.0-beta1? Or from a nightly (something with "-dev" at the end of the version)? Or from 5.0.3?

**Comment by Kostelano** [comment]
Just in case, I just installed a completely virgin version of 5.1-beta1 and the problem is the same.

**Comment by richard67** [comment]
@Kostelano What happens if you stay on the Default channel and in the Extension Installer's settings change the "Minimum Stability" from "Stable" to "Beta" (Or Alpha)?

I know, it seems strange that this setting in zhe extensions Installer also is relevant for the core, but that's how it is for historic reasons.

The issue here is that when the PHP or the database version would be the reason, the versions would be added to the information, see my PR #42489 , but that does not include the information about stability when the minimum stability requirement was not met, as that in past has always resulted only in the message that no update was found, which now it seems to result in the "Update found but requirements not fulfilled" message.

**Comment by Kostelano** [comment]
> @Kostelano What happens if you stay on the Default channel and in the Extension Installer's settings change the "Minimum Stability" from "Stable" to "Beta" (Or Alpha)?

I checked. In this case, the update is available and you can perform it.

> As that in past has always resulted only in the message that no update was found, which now it seems to result in the "Update found but requirements not fulfilled" message.

That's exactly how it is

**Comment by richard67** [comment]
I can try to make a PR to fix that in the one or other w<y, but not before weekend. If someone is faster let me know.

**Comment by SniperSister** [comment]
@richard67 yes, makes sense!

**Comment by HLeithner** [comment]
that's only one part of the story we discussed this in the tuf team and also the stability is a problem. removing this would fix the message that the server doesn't fit the update but wouldn't allow you to install beta2 over beta1.

**Comment by wojsmol** [comment]
@HLeithner Then IMHO this case should have at at least separate language string explaining the issue.

**Comment by richard67** [comment]
Anyway, my suggested change seems not to be enough, it seems it needs to change more. Am working on it.

**Comment by richard67** [comment]
Hmm, my suggested change works, but there is something which is confusing regarding the minimum stability.

When being on the "Testing" update channel, the Joomla Update component shows a "Minimum Stability" parameter in the options, but only then.

But the parameter which is used for the check is the "Minimum Stability" parameter from the Extension Manager's options, and that may be different. See the code here: https://github.com/joomla/joomla-cms/blob/5.1-dev/libraries/src/Updater/ConstraintChecker.php#L219

I think we have to change the `checkStability` method of the ConstraintChecker so it gets the minimum stability to be checked as a parameter, and the calling function has to set that parameter right.

In case of the Joomla Update component always the parameter from the options of this component should be used, and that parameter should always be shown, regardless of the update channel, or alternatively when it is hidden, i.e. the update channel is anything else than "Default" or maybe also "Next", then "Stable" has to be used.

**Comment by richard67** [comment]
I have a fix ready. PR will come later tonight or tomorrow.

Curious readers may already have a look on https://github.com/joomla/joomla-cms/compare/5.1-dev...richard67:5.1-dev-updater-minimum-stability .
