### ISSUE TITLE
[5.x] CodeMirror 6 JS highlighting not working

### ISSUE THREAD

**Issue by OctavianC** [joomla/joomla-cms#43113]
### Steps to reproduce the issue
Go to Administrator - Templates -  Cassiopeia Details and Files - open any `js` file such as `template.js`

### Expected result
Syntax highlighting

### Actual result
No syntax highlighting & Javascript error
![image](https://github.com/joomla/joomla-cms/assets/1422378/5cc8a299-39e9-4559-b1e6-3774dc764e94)

**Comment by alikon** [comment]
please test #43114

**Comment by Linkedla** [comment]
I test the patch and it is working for me.
![image](https://github.com/joomla/joomla-cms/assets/9966317/27cda25c-2fe5-4a6a-879a-46c44816a869)
