### ISSUE TITLE
[5.1] Collapsed admin menu hover issue

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#43121]
### Steps to reproduce the issue

Open backend and close menu and hover over `Home Dashboard`

### Expected result

J5.0.3
![image](https://github.com/joomla/joomla-cms/assets/66922325/9e48cc54-c74f-41bb-b7d9-3db5c6d8f43c)

### Actual result

J5.1.0-beta3-dev - Light Mode
![image](https://github.com/joomla/joomla-cms/assets/66922325/00eca940-67a1-485a-bde8-6d9a388d81b1)
J5.1.0-beta3-dev - Dark Mode
![image](https://github.com/joomla/joomla-cms/assets/66922325/45a02521-5549-45f8-a26a-77fbf72e2d53)

**Comment by brianteeman** [comment]
I have a fix for lightmode but the dark mode i doont have a clue

`build\media_source\templates\administrator\atum\scss\_variables.scss`
![image](https://github.com/joomla/joomla-cms/assets/1296369/f4e160a5-9a34-4c94-a680-dd7bb1c30b89)

**Comment by heelc29** [comment]
I think this is the reason in dark mode:
https://github.com/joomla/joomla-cms/blob/cf8bfec5fe58aacce09a9603546c93ff2b44f21a/build/media_source/templates/administrator/atum/scss/blocks/_sidebar.scss#L294

... but then there is a layout change due the border (related to #43029?)
![image](https://github.com/joomla/joomla-cms/assets/66922325/ecdfd483-6194-4341-86c9-bcf983eec32c)

**Comment by brianteeman** [comment]
polease test #43134
