### ISSUE TITLE
[5] editors-xtd return mutiple buttons

### ISSUE THREAD

**Issue by Tazzios** [joomla/joomla-cms#43128]
### Is your feature request related to a problem? Please describe.
In Joomla 3 and 4 it was possible to return an array of buttons with one plugin. In joomla 5 only the last button is shown. O`m not sure or this is on purpose or not so I made a feature request instead of a bug, and I`m probably the only one who runs into this issue. :)

### Describe the solution you'd like
Support to return an array of buttons (and also show them) instead of only one (latest) button.

### Additional context
I have made a plugin which user can use to create own buttons, but in J5 it does only show the latest button of the array.
https://github.com/Tazzios/Universal-buttons/

**Comment by brianteeman** [comment]
see also #40472

**Comment by Fedik** [comment]
In Joomla 5, also should work.
Hovewer there a new API, I suggest to update old code. 
Please follow https://manual.joomla.org/docs/building-extensions/plugins/editors-xtd-plugin

For old buttons, I think there a bug in resolving legacy buttons, when there an array https://github.com/joomla/joomla-cms/blob/4e62d6a1a9c95d8b3815f09003022ec418a362ea/libraries/src/Editor/Button/ButtonsRegistry.php#L132-L148
Need to check

**Comment by Tazzios** [comment]
@Fedik That is fast! Tested your solution and it works. 
Will look at the Joomla 5 documentation.

**Comment by Fedik** [comment]
Please visit https://issues.joomla.org/tracker/joomla-cms/43129
and click this litle button 
![Screenshot 2024-03-23_18-39-41](https://github.com/joomla/joomla-cms/assets/1568198/b2f4373b-ff0f-49db-ad28-46b62b811b7e)


to set your test result
