### ISSUE TITLE
Page Break Errors

### ISSUE THREAD

**Issue by wizzard102** [joomla/joomla-cms#43132]
### Steps to reproduce the issue
create an article with page breaks in it.
the apache server side log says the following everytime someone loads the page it is filling server side logs pages quickly.

![Screenshot 2024-03-24 072243](https://github.com/joomla/joomla-cms/assets/100698976/ade64807-5f31-4168-bc98-16baec2d3fd4)

### Expected result
no errors in the server log from it

### Actual result
this is the page that generates the error all the time
![Screenshot 2024-03-24 075814](https://github.com/joomla/joomla-cms/assets/100698976/1d573679-4544-4ee1-ab4b-8193dd88944d)

### System information (as much as possible)
joomla 5.0.3

php 8.2

**Comment by wizzard102** [comment]
[Sun Mar 24 11:11:33 2024] [error] [client ] AH01071: Got error 'PHP message: PHP Warning:  Undefined property: stdClass::$slug in /home/virtual/----------/b/-------/public_html/plugins/content/pagebreak/src/Extension/PageBreak.php on line 280; PHP message: PHP Warning:  Undefined property: stdClass::$slug in /home/virtual/-----------/b/--------------/public_html/plugins/content/pagebreak/src/Extension/PageBreak.php on line 302; PHP message: PHP Warning:  Undefined property: stdClass::$slug in /home/virtual/------/b/----------/public_html/plugins/content/pagebreak/src/Extension/PageBreak.php on line 302; PHP message: PHP Warning:  Undefined property: stdClass::$slug in /home/virtual/----------/b/----------/public_html/plugins/content/pagebreak/src/Extension/PageBreak.php on line 302; PHP message: PHP Warning:  Undefined property: stdClass::$slug in /home/virtual/vps-ae3fb4/b/b552371735/public_html/plugins/content/pagebreak/src/Extension/PageBreak.php on line 342'<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43132">issues.joomla.org/tracker/joomla-cms/43132</a>.</sub>

**Comment by Hackwar** [comment]
This looks like the code which triggers the event is not providing the correct input. Do you have a template override which maybe triggers this (again) with wrong inputs?

**Comment by Quy** [comment]
Closing due to no response with additional info.
