### ISSUE TITLE
punycode missing

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#43148]
Check the zip release for Joomla 5.0.3 and 4.4.3

In the folder `media\vendor\punycode\` there is only a licence file

**Comment by dgrammatiko** [comment]
> In the folder media\vendor\punycode\ there is only a licence file

Expected. The library is `imported` [here](https://github.com/joomla/joomla-cms/blob/8eefbf2375217f4ddaf7ddf3c5eba055b768f93e/build/media_source/system/js/fields/validate.es6.js#L6) so there's no need to serve it as a stand alone script

**Comment by brianteeman** [comment]
I know - which is why we need to remove the folder etc

**Comment by dgrammatiko** [comment]
Removing these lines https://github.com/joomla/joomla-cms/blob/8eefbf2375217f4ddaf7ddf3c5eba055b768f93e/build/build-modules-js/settings.json#L555C1-L558C9 should do it

**Comment by brianteeman** [comment]
also need to add to the list of files and folders removed on update

**Comment by dgrammatiko** [comment]
Richard has a script that does that automatically iirc

**Comment by Hackwar** [comment]
Are you guys creating a PR to remove that?

**Comment by brianteeman** [comment]
fixed in #43162
