### ISSUE TITLE
"Link Image" to menu item is adding unnecesary alt atribute

### ISSUE THREAD

**Issue by pl71** [joomla/joomla-cms#43141]
Isn't an image next to a menu item [decorative](https://www.w3.org/WAI/tutorials/images/decorative/#example-2-decorative-image-as-part-of-a-text-link) only?

### Steps to reproduce the issue
1. Have a menu item and add a **Link Image** from Menus: Edit Item/link Type
2. Check page source:

### Expected result
`<a href="/menu-item-1"><img src="/images/path-to/filename.jpg" alt="" decoding="async">...`

### Actual result
`<a href="/menu-item-1"><img src="/images/path-to/filename.jpg" alt="menu-item-1" decoding="async">...</a>
`

### Device and system info

* What version of Joomla were you using?
J 5.0.3

* What device were you using? (eg, phone, laptop)
desktop

* What web browser were you using? (eg, Chrome, Safari)
Firefox

* If you were using assistive technology, please let us know the device or software you were using (eg VoiceOver, JAWS, sip-and-puff device, etc)

### Additional comments

As per [PageSpeed Insights](https://pagespeed.web.dev/) 

> Informative elements should aim for short, descriptive alternative text. Alternative text that is exactly the same as the text adjacent to the link or image is potentially confusing for screen reader users, because the text will be read twice.

**Comment by Quy** [comment]
Closing per PR  #40675. Thanks.
