### ISSUE TITLE
[5.1] Performance guided tours autostart feature

### ISSUE THREAD

**Issue by heelc29** [joomla/joomla-cms#43153]
### Steps to reproduce the issue

open administration and visit dashboard (debug enabled)

### Expected result

Only 1 additional database query to check if autostart necessary
- when yes: then load all data (translation, steps, ...)
- when no: don't load additional stuff

### Actual result

38 database queries (4 additional after autostart feature)
![image](https://github.com/joomla/joomla-cms/assets/66922325/95f5b76b-3375-4ee9-b64c-cdec5dadcbda)

warning about untranslated strings (only visible in debug bar, because they are not necessary to load)
![image](https://github.com/joomla/joomla-cms/assets/66922325/30b6c237-19d5-4ca8-ae21-ae625f654207)

**Comment by brianteeman** [comment]
Confirmed. Didnt dig into the queries but there is no reason for the language strings to be loaded if the guided tour has been disabled

**Comment by obuisard** [comment]
In the TourModel.php, I propose we have an extra function called isAutostart() that does a simple query without using getTour() which does the extra work for nothing if the autostart is set to 0.
