### ISSUE TITLE
[5.1.0_RC2] Checksum Error on Update

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#43150]
### Steps to reproduce the issue

1. Clone a site with J5.0.3
2. In Global Configuration, configure **Update Server** to "Test" and **Minimum Stability** to "Release Candidate"
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/e100b03f-0c2e-40c1-9e6a-9a19338c8b1f)

3. Ignore warnings in pre-update check
4. Start the Joomla backup

### Expected result
Update runs smoothly

### Actual result
Update fails with a checksum warning 

The log file reveals a wrong download file:
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/50be80d6-2a3e-40e7-949c-3aa6acbee5e3)

### System information (as much as possible)
J5.0.3
PHP 8.3.3
MySQL 8.0.33
[joomla_update.php.txt](https://github.com/joomla/joomla-cms/files/14744803/joomla_update.php.txt)

### Additional comments
Sorry: Headline wrong. Should read [5.1.0_Beta2]

**Comment by Quy** [comment]
PR  #43147 removes Testing channel so probably this will be a non issue.

**Comment by richard67** [comment]
There was indeed a mistake in the testing update site with the check sum, but as this update source has been removed with PR #43147 , this issue has been solved.

Closing for that reason.
