### ISSUE TITLE
[5.1] cpanel card border in dark mode

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#43158]
### Steps to reproduce the issue

the size of the Dashboard Panels is different between light and dark mode;

![image](https://github.com/joomla/joomla-cms/assets/906604/a86bfb94-5a66-448b-a218-415eab8a6ec5)
![image](https://github.com/joomla/joomla-cms/assets/906604/648e844e-8f54-428f-a45a-31a657cc4fb9)

(in the first case you can read the text)

### Expected result

same height

### Actual result

different height

### Additional comments

the reason is a border on dark mode:
![image](https://github.com/joomla/joomla-cms/assets/906604/38b611d9-593e-4c4c-843e-7d32c6767665)

which adds a minimum of separation from the background (the colors are too dark), but which change the size from the light

**Comment by brianteeman** [comment]
Not sure I see the problem you are describing.

**Comment by Razzo1987** [comment]
in the homepage check the position of the lowest element on the page as you change from dark to light mode.
It moves down a few pixels in dark mode because Dashboard Panels in dark mode have a border of 1 pixel.

Removing the border makes it unusable (the colors were made darker, although I think we had rejected that choice), but leaving it makes the elements move....

**Comment by brianteeman** [comment]
personaly not worried about a pixel shift here.

**Comment by Quy** [comment]
Closing as expected behavior. It does not affect using Joomla. Majority of people including myself would not have even not noticed it. Thanks.
