### ISSUE TITLE
[5.1] sidebar border

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#43159]
### Steps to reproduce the issue

if you switch between light and dark m ode the left sidebar is different the item menù position little move

### Expected result

same text position on the item menù

### Actual result

different text position on the item menù

### Additional commen

there is a border on the dark mode sidebar:

![image](https://github.com/joomla/joomla-cms/assets/906604/3b5cd234-c210-4828-aa69-43629eb09939)

![image](https://github.com/joomla/joomla-cms/assets/906604/872f58cc-a124-40c8-a3b5-a3d05079fb29)

**Comment by brianteeman** [comment]
can you retest with the changes from the pr I mentioned before
