### ISSUE TITLE
[5.1] dark mode right scrollbar

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#43157]
### Steps to reproduce the issue
Clean install.
Go to administrator/index.php?option=com_content&view=articles

Switch between the light and dark mode

### Expected result
No right bar

### Actual result

![image](https://github.com/joomla/joomla-cms/assets/906604/0d8ed497-660e-40e4-a121-9b34541994c9)

![image](https://github.com/joomla/joomla-cms/assets/906604/a2569730-eb93-42c5-b92f-a2643a4c27d8)

### System information (as much as possible)

no right scrollbar on darkmode

**Comment by brianteeman** [comment]
its because there is a slight difference in the size of the screen. can you check if #43138  solves it for you

**Comment by Razzo1987** [comment]
Yes #43138 solve the problem:
![image](https://github.com/joomla/joomla-cms/assets/906604/db858c51-c03c-4153-a76c-1cfa9d3a4709)

Thanks you @brianteeman ! <3
