### ISSUE TITLE
Scheduler Web Cron is capturing the article id instead of the task id

### ISSUE THREAD

**Issue by uGE70** [joomla/joomla-cms#43154]
### Steps to reproduce the issue

1) Check that your website is using a Joomla article as the home page in your main menu (with an article id).
2) Copy the basic Scheduler Web Cron link and paste it in any browser: https://www.domain.com/component/ajax/?plugin=RunSchedulerWebcron&group=system&format=json&hash=hashstring
3) In file /plugins/system/schedulerunner/src/Extension/ScheduleRunner.php, var_dump the result of line 205:
 $id = (int) $this->getApplication()->getInput()->getInt('id', 0);
var_dump($id);
exit;

### Expected result
I should get id=0 and the task scheduling should work properly without any additional id parameter.

### Actual result

I get the current homepage article id. Adding &id=0 in the web cron link is solving the issue.

### System information (as much as possible)

Joomla 5.0.3 / 4.4.3, PHP 8.2 or less. Infomaniak shared hosting (task planner).

### Additional comments

Thanks for your much appreciated work

**Comment by Hackwar** [comment]
Can you take a look at #42989 and see if this fixes your issue?

**Comment by uGE70** [comment]
Hello,
Thanks for your message.
- I installed Joomla 5.2-dev and Patch Tester,
- added a single article as homepage,
- applied two patches: #42989 and #42854,
- set Disallow non-SEF URLs to yes in the SEF plugin.
I still get the article id instead of 0 in the scheduler plugin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43154">issues.joomla.org/tracker/joomla-cms/43154</a>.</sub>

**Comment by Hackwar** [comment]
Thank you. I'll have a look what can be done here.

**Comment by Hackwar** [comment]
Can you check #43164 if that helps you?

**Comment by uGE70** [comment]
Hello,
Thanks a lot for your work. I've applied the patch and now it's working as expected.

**Comment by Hackwar** [comment]
Then please comment accordingly in the PR. I'm closing this issue now, since we have that PR.
