### ISSUE TITLE
Module assignment to home page affects all other pages regardless of their own assignments

### ISSUE THREAD

**Issue by gssimon** [joomla/joomla-cms#43165]
### Steps to reproduce the issue
It appears that no matter what menu link I assign my custom module to, if I assign the module to the home menu, then it shows on all pages.  If I don't assign it to the home menu, but to other links, then the module doesn't show up on any pages.  I've tried this on the Cassiopeia template with SEF turned off in the global configurations.  Using the 'On all pages' and 'No pages' work, but I still think it's because all/none basically turn it on/off on the home link.

Setup
1.  Create 3 simple single articles.
2.  Create 3 menu link to each article.  No parent/child relationship.  Set one to Home.
3.  Make a custom module and set it to any template position.

Test
1.  Check that the custom module is on all 3 menu link pages.
2.  Assign the module to any page other than the home menu link and reload all 3 pages.  The module disappears from all 3 pages.
3.  Assign the module to only the home menu link and reload all 3 pages.  The module now appears on all 3 pages.

### Expected result
The custom module should only appear/not appear on the pages I selected.

### Actual result
The module assignment only works on the home page, but affects all pages regardless of whether the module is assigned to them or not.

### System information (as much as possible)
Joomla! version
  4.4.3 Stable.  Fresh install.
PHP version
  8.3.4 
MySQL version
  5.7.23
Plugins installed
  DirectPHP
  ASM No Admin

### Additional comments
- SEF is turned off
- All articles have their own menu link.  No parent/child.

**Comment by Hackwar** [comment]
I can not replicate this. This would also be a major bug in our system and we would have heard about this before. Can you make sure that you are really using this feature correctly in the module manager? Can you post the URLs where you see that on your test system and describe the menu item setup?

**Comment by gssimon** [comment]
Here's a video of what I'm experiencing.  I will try to reinstall a fresh copy to see if the problem still exists.  Sorry about the static in the audio.  Forgot to turn off the sound capture.

https://drive.google.com/file/d/19zGRZrrnVG3o0NfpDLywG8Dbc68es_KC/view?usp=sharing

**Comment by brianteeman** [comment]
> All articles have their own menu link. No parent/child.

But in your video you are not using the menu link. If you were using the menu link then you would see &itemid=XX in the url. That is the glue that holds the system together and is what controls which modules to display

**Comment by gssimon** [comment]
Thanks for the reply.  I'm not sure what you mean by the menu link.  How to I go about getting that URL?

**Comment by gssimon** [comment]
Quick follow up.  I tried addind &itemid=XX where XX is the ID of the menu link, but the results are the same as not adding the itemid.

**Comment by gssimon** [comment]
@brianteeman Ok.  I did get it to work now adding the &Itemid=XX.  I guess it's capital I in the front.  Thanks for your help.  It's add that Joomla doesn't just add this to the link displayed in the menu item.

**Comment by brianteeman** [comment]
Joomla does when you actually use the menu

**Comment by Hackwar** [comment]
If you use Route::_() to generate your links, all that is done automatically for you.

**Comment by Hackwar** [comment]
This seems to be a user error, so I'm closing this.
