### ISSUE TITLE
Joomla 5.0.3 - LoadModule

### ISSUE THREAD

**Issue by mehkriakram** [joomla/joomla-cms#43174]
### Steps to reproduce the issue
call {LoadModuleID xxx}

### Expected result
Module xxx shows up as content on the page. 

### Actual result
In Site Modules - > Module Name -> Menu Assignment Tab, 
if i DON'T enable the module to show on that menu item linked to the article, the {LoadModuleID xxx} won't load module xxx

if i enable the module, then I see two instances of module xxx. one instance from the article that's calling {LoadModuleID XXX} and one may be from the menu assignments 

### Additional comments
i wonder if i call nested articles (one article from another) and the other article is not listed in the menu, if LoadModuleID will work or not or if i have to create hidden menu items just for this.

**Comment by brianteeman** [comment]
This is really a question for the forum but basically the module must be enabled for the menu. What I always do is set the module to be enabled for all pages but place it in a fake position. Then it will load when you load it inside the article and wont appear anywhere else
