### ISSUE TITLE
[5.0.3] Unable to install new languages

### ISSUE THREAD

**Issue by morphinestyle** [joomla/joomla-cms#43183]
The problem occurred with a new installation.

### Steps to reproduce the issue:
Click on Languages
Click on Install Languages

### Expected result:
The list of installable languages ​​should appear

### Actual result
"No Matching Results" appears

### System information (as much as possible)
Joomla 5.0.3
PHP 8.2.15
MariaDB 10.11.7
OpenLiteSpeed

**Comment by ReLater** [comment]
Confirmed. I think the reason is that the necessary language list XML has an error or doesn't exist. See image, please.

https://update.joomla.org/language/translationlist_5.xml

![grafik](https://github.com/joomla/joomla-cms/assets/20780646/d9e36f35-d182-4d67-bfa5-0bda51af4850)

**Comment by Razzo1987** [comment]
I think it is a problem with the language server, not a bug in the Joomla core.
Try downloading a package from https://downloads.joomla.org/it/language-packs/translation5 and even from there it gives error.

**Comment by tecpromotion** [comment]
Bug confirmed with https://update.joomla.org/language/translationlist_5.xml
We are working on it. @bembelimen @LadySolveig @HLeithner

**Comment by HLeithner** [comment]
Should work again. thanks for the report and @wilsonge for fixing it.
