### ISSUE TITLE
Emotional , My Joomla was not launch up. It just shown  ' failed install ' , I can`t find what i was wrong in the progress.

### ISSUE THREAD

**Issue by fhvknb** [joomla/joomla-cms#43185]
### Problem identified
Joomla Version: 5.0.3
PHP Version: 8.2
Mysql(PDO) Version: 8.0.37
Apache Version: 2.4
Install shown message: 
![image](https://github.com/joomla/joomla-cms/assets/19361229/55139b4d-0731-4b8f-9348-d55797cee86f)
![image](https://github.com/joomla/joomla-cms/assets/19361229/6a0fb932-f80e-45e3-91cc-99f690127335)
Why, Why, Why?

### Proposed solution
someone can help me find the reason and solve this error? thank you guys

**Comment by richard67** [comment]
> Joomla Version: 5.0.4

How can that be? The latest stable release right now is 5.0.3. Have you used a nightly build or a patched package for a pull request, which both would have version 5.0.4-dev - mind the "-dev" at the end - which means "development version on the way to 5.0.4?

**Comment by ssnobben** [comment]
Please go to Joomla forum and ask for help there. This is Joomla core development area and this kind of error you better get help in Joomla forum. Follow this link [https://forum.joomla.org/viewforum.php?f=837](https://forum.joomla.org/viewforum.php?f=837)

Joomla 5 is very stable, fast, secure and easy to use. So hope you can get this right. But there is no Joomla 5.0.4 yet :)

**Comment by xiang510** [comment]
> Please go to Joomla forum and ask for help there. This is Joomla core development area and this kind of error you better get help in Joomla forum. Follow this link https://forum.joomla.org/viewforum.php?f=837
> 
> Joomla 5 is very stable, fast, secure and easy to use. So hope you can get this right. But there is no Joomla 5.0.4 yet :)

I am sorry,  My Joomla version is 5.0.3, I typed it wrong. Thanks.

**Comment by xiang510** [comment]
> > Joomla Version: 5.0.4
> 
> How can that be? The latest stable release right now is 5.0.3. Have you used a nightly build or a patched package for a pull request, which both would have version 5.0.4-dev - mind the "-dev" at the end - which means "development version on the way to 5.0.4?

I am sorry,  My Joomla version is 5.0.3, I typed it wrong.  Why did I get an error message on the top picture

**Comment by richard67** [comment]
@xiang510 Could you check if the PHP extension "mbstring" is available and enabled?

**Comment by xiang510** [comment]
> @xiang510 Could you check if the PHP extension "mbstring" is available and enabled?

@richard67 Thanks.  Install success. I followed this guide and configured env, I don`t know  "mbstring" extension is required.
 ![image](https://github.com/joomla/joomla-cms/assets/19361229/876628b1-6a99-4aa0-b1a1-75b31efd8cd5)
