### ISSUE TITLE
[5.1.0 RC1] Extensions check stuck

### ISSUE THREAD

**Issue by conseilgouz** [joomla/joomla-cms#43196]
### Steps to reproduce the issue

Update a test website from version 5.0.3 to 5.1.0 RC 1

### Expected result

Joomla update OK

### Actual result

Extension check get stuck in media/com_joomlaupdate/js/default.js with error at line 302 because of a bunch of deprecated messages

### System information (as much as possible)
PHP 8.3.3, Laragon on PC Windows

### Additional comments
![joomla5 1 0rc1](https://github.com/joomla/joomla-cms/assets/19435246/703fc18a-42ee-4b84-8e63-12f842cc99a9)

**Comment by conseilgouz** [comment]
Sorry, I messed up, trying to update from 5.1.0 beta 2 to 5.1.0 RC.

**Comment by conseilgouz** [comment]
Hi,

I took me a while but I found the condition when this occurs : enable Error reporting to default or higher.

In this case, ajax answer contains a lot of notice message : 

<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$jversion.full is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Object\LegacyPropertyManagementTrait.php</b> on line <b>135</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$folder is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Updater\Update.php</b> on line <b>452</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$changelogurl is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Updater\Update.php</b> on line <b>452</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$jversion.full is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Object\LegacyPropertyManagementTrait.php</b> on line <b>135</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$folder is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Updater\Update.php</b> on line <b>452</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$changelogurl is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Updater\Update.php</b> on line <b>452</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$jversion.full is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Object\LegacyPropertyManagementTrait.php</b> on line <b>135</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$folder is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Updater\Update.php</b> on line <b>452</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$changelogurl is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Updater\Update.php</b> on line <b>452</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$jversion.full is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Object\LegacyPropertyManagementTrait.php</b> on line <b>135</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$folder is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Updater\Update.php</b> on line <b>452</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$changelogurl is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Updater\Update.php</b> on line <b>452</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$jversion.full is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Object\LegacyPropertyManagementTrait.php</b> on line <b>135</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$changelogurl is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Updater\Update.php</b> on line <b>452</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$jversion.full is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Object\LegacyPropertyManagementTrait.php</b> on line <b>135</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$changelogurl is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Updater\Update.php</b> on line <b>452</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$jversion.full is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Object\LegacyPropertyManagementTrait.php</b> on line <b>135</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$jversion.full is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Object\LegacyPropertyManagementTrait.php</b> on line <b>135</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$jversion.full is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Object\LegacyPropertyManagementTrait.php</b> on line <b>135</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$changelogurl is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Updater\Update.php</b> on line <b>452</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$jversion.full is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Object\LegacyPropertyManagementTrait.php</b> on line <b>135</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$changelogurl is deprecated in <b>D:\laragon6-------------\www\j503rc\libraries\src\Updater\Update.php</b> on line <b>452</b><br />

**Comment by conseilgouz** [comment]
![issue_43196](https://github.com/joomla/joomla-cms/assets/19435246/616b03d0-6f5c-4c3e-b36c-dbc3181b5f15)

**Comment by conseilgouz** [comment]
First notice comes from administrator\components\com_joomlaupdate\src\Model\UpdateModel.php line 1630 : 
$update->set('jversion.full', $joomlaTargetVersion);

**Comment by brianteeman** [comment]
very odd. I am using laragon and php 8.3.3 on windows and I have not been able to replicate this

**Comment by conseilgouz** [comment]
It only appears if you set error reporting to default.

**Comment by conseilgouz** [comment]
checkCompatibility in UpadteModel is used for non core extension.
So if you have any non core extension, you'll see these notices.

**Comment by conseilgouz** [comment]
I just tried on a clean 5.0.3 version with latest Akeeba backup : same error.

**Comment by brianteeman** [comment]
> I took me a while but I found the condition when this occurs : enable Error reporting to default or higher.

I checked with error reporting set to maximum

> Update a test website

I missed this part and was just checking for updates. Will test again

**Comment by conseilgouz** [comment]
To fix this, we have to add the missing definitions in libraries/src/Updater/Update.php.
I'm trying to create a new PR to fix this, but, as I already have one in progress, I can't achive this.

**Comment by brianteeman** [comment]
I still cant replicate the error

**Comment by wojsmol** [comment]
@brianteeman `Deprecated: Creation of dynamic property` type of warning is specific to php 8.2+.

**Comment by brianteeman** [comment]
I am using 8.3.3

**Comment by conseilgouz** [comment]
PR #43226  fixes this.
It took me a while to figure out it had to apply to Joomla 5.0.

**Comment by richard67** [comment]
Closing as having a pull request. See #43226
