### ISSUE TITLE
Joomla v6.0 Update Package Manifest Incorrect Version

### ISSUE THREAD

**Issue by jcss** [joomla/joomla-cms#43193]
###Download Joomla 6.0 Update Package from nighly builds. Login in Joomla 6.0 as Administrator. Select System-Update->Joomla. Scroll down an select Upload and Update. Select/Open the downloaded Joomla Update Package. Check I'mm aware message.Click Update. Lengthy message displays current version6.0.0-qlpha-dev, update version package is 5.1.0-beta3-dev, can't down grade version. Confirmed by edebugin com_joomlaupdat UpdtaeModel,php checkManifestXML function.

### Expected resultJoomla update failure message stating current version is 6.0.0-alpha-dev; update package version 5.1.0-beta3-dev.
Conclusion; JOOMLA 6.0.0 uPDATE PACKAGE HAS INCORRECT MANIFEST VERSION NUMBER

**Comment by Hackwar** [comment]
Thank you for reporting this, however right now we don't have maintainer for Joomla 6 and there is no official official work yet done on Joomla 6. It is basically just a branch to prepare some things for 6.0. That said, the bugs you see are "expected". We will fix this when development officially starts. For now we are closing this.
