### ISSUE TITLE
Joomla 5.2 Update Package Fails - Incorrect joomla.xml version

### ISSUE THREAD

**Issue by jcss** [joomla/joomla-cms#43197]

**Comment by Hackwar** [comment]
I'm really sorry for shooting you down like this again, but Joomla 5.2 development actually only really starts today and nightly builds are only that: Nightly builds of Joomla which you can use in testing environment to test stuff. It is not meant for a live website and it is not guaranteed to be always working. This specific issue will be dealt with in the next few days "automatically".

**Comment by pe7er** [comment]
@jcss Thanks for reporting the issue with the incorrect joomla.xml version!
I did a new 5.1 > 5.2 upmerge, corrected the version/internal name/datetime and will make it available later today. 
Please use this 5.2 alpha version only for testing purposes.
Thanks!
