### ISSUE TITLE
Subform fields won't render zero values

### ISSUE THREAD

**Issue by redonioncreative** [joomla/joomla-cms#43194]
### Steps to reproduce the issue

I have a subform, which has a number of text fields. The text fields will usually need to display a '0' value.

### Expected result

When trying to access the field value from the article frontend (in this instance, the Yootheme builder), the value 0 should render in any applicable fields

### Actual result

Wherever the 0 should be, nothing is rendered. Whether the value is a field default value, or a manually entered one, the value of '0' will not render. If the same field is applied as an article field, and not a subform field, the 0 value renders fine. Even on the same article, the same field that is contained within the subform will not be rendered

### System information (as much as possible)

Joomla 4.4.3, PHP8.3

**Comment by Quy** [comment]
I cannot replicate. Can you test with a clean installation without Yootheme to replicate the issue?

![43194](https://github.com/joomla/joomla-cms/assets/368084/ba36c9ea-921b-499f-a452-618df7ad26e0)

**Comment by Quy** [comment]
Closing as non-reproducible.
