### ISSUE TITLE
Untranslated string for warning message in update:extensions:check CLI

### ISSUE THREAD

**Issue by chrisdavenport** [joomla/joomla-cms#43206]
### Steps to reproduce the issue
Arrange for an extension update site to have an invalid URL (eg. temporarily mangle the URL in the extensions database).  Then run
`php cli/joomla.php update:extensions:check` from the command line.

### Expected result
Warning message something like
`[WARNING] Update: Could not open update site #4 "xxxxxxxxxxx Package Update Site", URL: https://example.com/xxxxx/update.xml`

### Actual result
`[WARNING] JLIB_UPDATER_ERROR_OPEN_UPDATE_SITE`

### System information (as much as possible)
Joomla 4.4.3
PHP 8.1

### Additional comments
The string exists in `administrator/language/en-GB/lib_joomla.ini` and `language/en-GB/lib_joomla.ini` so the problem is that the language file is not being loaded at the appropriate time.

**Comment by alikon** [comment]
confirmed

**Comment by richard67** [comment]
Closing as having a pull request. See #43208 .
