### ISSUE TITLE
A change in the structure of the com_categories from extension to context similar to com_fields

### ISSUE THREAD

**Issue by sinahaghparast** [joomla/joomla-cms#43213]
### Steps to reproduce the issue
Currently, each component can use com_categories once. 

### Expected result
If the com_categories is similar to the com_fields, by defining different texts (CONTEXT), it is possible to use the com_categories multiple times in the same component. Now the com_fields has such a capability.

### Actual result
By changing one component, more scenarios can be covered.
For example Students MVC needs category, and Schools MVC needs category too. 
context=com_example.students and context=com_example.schools

### Additional comments
I've done this example for com_fields by adding numbers and was able to save a lot of coding. It is really similar to this scenario for com_categories, so that different scenarios can be covered with little coding.

**Comment by sinahaghparast** [comment]
index.php?option=com_categories&view=categories&extension=com_content
>>>change to>>>
index.php?option=com_categories&view=categories&context=com_content.article<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43213">issues.joomla.org/tracker/joomla-cms/43213</a>.</sub>

**Comment by Hackwar** [comment]
The parameter has a different name, but you can actually use the same structure right now. If you want, you can use &extension=com_content.fields to have an additional category tree. I'm doubting that we will rename the parameter, due to legacy reasons.

**Comment by sinahaghparast** [comment]
Please explain the old reasons. Maybe we can find a solution for it. I know that this can be implemented, but in my opinion, the code itself should be self-explanatory and not require trial and error by the developer.

**Comment by rdeutz** [comment]
> Currently, each component can use com_categories once.

The first statement in you description is wrong. You can you use as much categories trees as you want, you only have to add something to the extension parameter like 

extension=com_demo.tree1
extension=com_demo.tree2
extension=com_demo.tree3
extension=com_demo.tree4
