### ISSUE TITLE
[5.1.0-rc1] Notifications red

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#43218]
### Steps to reproduce the issue

Just installed 5.1RC1 and an extension i am working on. The Global Configuration screen has three red Notifications.

### Expected result

Four green notifications.

### Actual result

On green (Joola is up to date) and three red. Two work but the Unknown extensions button gives an error:

```
An error has occurred.

    0 Attempt to assign property "name" on null 

Call Stack
# 	Function 	Location
1 	() 	JROOT/libraries/src/Updater/Adapter/ExtensionAdapter.php:73
2 	Joomla\CMS\Updater\Adapter\ExtensionAdapter->_startElement() 	 
3 	xml_parse() 	JROOT/libraries/src/Updater/Adapter/ExtensionAdapter.php:287
4 	Joomla\CMS\Updater\Adapter\ExtensionAdapter->findUpdate() 	JROOT/libraries/src/Updater/Updater.php:263
5 	Joomla\CMS\Updater\Updater->getUpdateObjectsForSite() 	JROOT/libraries/src/Updater/Updater.php:164
6 	Joomla\CMS\Updater\Updater->findUpdates() 	JROOT/administrator/components/com_installer/src/Model/UpdateModel.php:275
7 	Joomla\Component\Installer\Administrator\Model\UpdateModel->findUpdates() 	JROOT/administrator/components/com_installer/src/Controller/UpdateController.php:113
8 	Joomla\Component\Installer\Administrator\Controller\UpdateController->find() 	JROOT/libraries/src/MVC/Controller/BaseController.php:730
9 	Joomla\CMS\MVC\Controller\BaseController->execute() 	JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
10 	Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() 	JROOT/libraries/src/Component/ComponentHelper.php:361
11 	Joomla\CMS\Component\ComponentHelper::renderComponent() 	JROOT/libraries/src/Application/AdministratorApplication.php:150
12 	Joomla\CMS\Application\AdministratorApplication->dispatch() 	JROOT/libraries/src/Application/AdministratorApplication.php:195
13 	Joomla\CMS\Application\AdministratorApplication->doExecute() 	JROOT/libraries/src/Application/CMSApplication.php:306
14 	Joomla\CMS\Application\CMSApplication->execute() 	JROOT/administrator/includes/app.php:58
15 	require_once() 	JROOT/administrator/index.php:32 
```

### System information (as much as possible)

MacOS (intel), Apache, MySQL 8.0.33, PHP 8.3.1

**Comment by ceford** [comment]
Ah! Seems the Red notifications are related to my own plugin. I uninstalled it an the buttons went green.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43218">issues.joomla.org/tracker/joomla-cms/43218</a>.</sub>

**Comment by ceford** [comment]
Seems I defined an update server but did not provide one. Mea Culpa!

**Comment by brianteeman** [comment]
@ceford so it was actually a good thing to do as testing should always include testing for when things go wrong as well as for when they are correct

**Comment by roppit** [comment]
I having the same outcome with 3 red buttons and same arror: An error has occurred. 
    0 Attempt to assign property "name" on null 
which plugin was it about?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43218">issues.joomla.org/tracker/joomla-cms/43218</a>.</sub>
