### ISSUE TITLE
[5.1] UI issue in Atum administrator template

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#43212]
### Steps to reproduce the issue

1. Move to System - Site Templates - <yourtemplate>
2. Take a close look at the button bar (From Save to Close File)
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/d9bac2b2-79e0-4c16-8966-c08559cad099)

3. You see the buttons Delete File and Close File directly adjacent to each other and both displayed with red background.

### Expected result
The buttons should be displayed at some distance from each other and with different backgrounds.

- The Close File button should be displayed in third position (after Save & Close).
- It should have a background associated with a warning (i.e. orange). 

### Actual result
You might accidentally click the Delete File button when you just want to close the file.

**Comment by dautrich** [comment]
@brianteeman 
I perfectly understand that this not a critical issue, but more something like a feature request for a minor UI change. But why not think about it?

**Comment by brianteeman** [comment]
I was clarifying it for others reading your post who might have assumed that the file would be deleted immediately so didnt actually click on it to see.

IIRC this has been raised before with the UX team

**Comment by chmst** [comment]
I was dealing with that here https://issues.joomla.org/tracker/joomla-cms/40167 but we have to find a solution for all close and cancel and delete buttons.

**Comment by chmst** [comment]
Please test  #43592
