### ISSUE TITLE
[5.1.0 rc1] - Fix unclear Text Message in All Menu Items area Batch Action process

### ISSUE THREAD

**Issue by exlemor** [joomla/joomla-cms#43214]
### Steps to reproduce the issue
While testing Joomla 5.1.0. RC1 during/after the Release Testing meeting, I came across a not so easy to understand message...

I needed to test Batch operations in the Menus Area and I happen to click on All Menu Items...
There, I selected the 'Blog' menu entry (created for me when I installed the Sample Data set), then clicked on Actions --> Batch.

The explanation message (which feels like an error or at least a notice/warning etc yet is not in orange etc ) says:

**Batch process the selected menu items**

To use batch processing, please first select a Menu in the manager.

yet, that last line is confusing...

It should say:

To use batch processing, please first select the - Select Menu - entry in the dropdown above on this screen.

In case, it is easier to see it in action, please watch the short video below:

https://github.com/joomla/joomla-cms/assets/2597232/60bf27eb-c0c6-4762-a424-070844d3ce9e

### Expected result
A better, easier to understand, more descriptive error-like message:

To use batch processing, please first select the - Select Menu - entry in the dropdown above on this screen.

### Actual result

To use batch processing, please first select a Menu in the manager.

( not clear. It is English but contextually confusing, leading to incorrect steps ).

### System information (as much as possible)

Any Joomla 4.x and 5.x system same message/behavior.

**Comment by richard67** [comment]
Closing as having a pull request. See #43215 .

@exlemor If you already know that you will make a PR there is no need to create an issue. The PR is enough.

**Comment by exlemor** [comment]
Hi @richard67, sorry about that, it's actually my first PR ever ;) and I initially created an Issue instead of a PR by mistake but @bembelimen was nice enough to walk me through the whole process... :)
