### ISSUE TITLE
New user be registered to multi group automatically.

### ISSUE THREAD

**Issue by sinahaghparast** [joomla/joomla-cms#43221]
### Steps to reproduce the issue
New user be registered to multi group automatically.
/administrator/index.php?option=com_config&view=component&component=com_users
New_User_Registration_Group Field be able to select multi option.

**Comment by brianteeman** [comment]
??????

**Comment by sinahaghparast** [comment]
### Issue Title:
Allow New Users to Join Multiple Groups Upon Registration from the Frontend

### Description:
Currently, Joomla allows administrators to assign new users to multiple groups from the backend. However, this functionality is not available on the frontend during the user registration process. I propose an enhancement to enable the selection of multiple user groups at the time of registration from the frontend.

### Steps to Reproduce:
1. A new user registers on the site through the frontend.
2. During registration, the user is automatically assigned to one default group.

### Expected Result:
The `New_User_Registration_Group` field should allow for the selection of multiple groups. As a result, when a new user registers from the frontend, they should be able to be associated with multiple predefined groups simultaneously.

### Actual Result:
Currently, the user is only able to be assigned to one group during the frontend registration process.

### System Information:


### Additional Comments:
This enhancement would streamline the process for users who need to be part of multiple groups, reducing the need for administrator intervention post-registration.

**Comment by brianteeman** [comment]
There are extensions available for this

**Comment by rdeutz** [comment]
If you have multiple groups in your system then this is for a reason. You want to give users different rights or they should have access to different parts of the system. This isn't something you can fully automate, it needs user interaction.

I might oversee something here so I am not closing this but convert it to a discussion to find out what the goal for it is or understand better the requierements/use case.
