### ISSUE TITLE
Cannot installed some language(S) at initial install time

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#43222]
### Steps to reproduce the issue

Create a fresh joomla 5.0.3 install then choose "add additional languages" during install time.
I chose "french, hungarian & swedish"

### Expected result
language packs install

### Actual result

![image](https://github.com/joomla/joomla-cms/assets/1850089/3305f0d7-3ef6-4821-8a58-cfa18c5a9b92)

### System information (as much as possible)

[systeminfo-2024-04-06T15_10_55+00_00.txt](https://github.com/joomla/joomla-cms/files/14893961/systeminfo-2024-04-06T15_10_55%2B00_00.txt)

**Comment by brianteeman** [comment]
1. Can you please retest just installing one additional language 
2. Can you please retest just installing two additional language 

This will help see if you are hitting the described issue with timeouts

**Comment by brianteeman** [comment]
Installed fine for me

![image](https://github.com/joomla/joomla-cms/assets/1296369/8f1ad83a-ea5d-4fc0-963c-888f279dd54a)

**Comment by N6REJ** [comment]
> 1. Can you please retest just installing one additional language
> 2. Can you please retest just installing two additional language
> 
> This will help see if you are hitting the described issue with timeouts

I did try two because the hungarian one did not show green but it still gave the same error, I will try just one and get back with you

**Comment by N6REJ** [comment]
What is your *amp stack environment?

**Comment by brianteeman** [comment]
php 8.3.3, apache 2.4.57, nysql 8.0.30

**Comment by Quy** [comment]
Installed successfully with 3 languages. Maybe an issue with your internet connection.

**Comment by Hackwar** [comment]
I had this issue with 5.2, but with 5.1 it is working. Please test if this is still the issue with 5.1.

**Comment by N6REJ** [comment]
I haven't abandoned this just been insanely busy

**Comment by N6REJ** [comment]
I'm not sure what happened before but I can't replicate this now either.  I'm closing this
