### ISSUE TITLE
Version note system for articles acting strange

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#43244]
### Steps to reproduce the issue
open article and add a version note.
save article notice version note shows.
open article create new version note.
save
notice article not changed for existing article.
change SOMETHING
add note
save article
notice last note is now gone and replace with the latest note.

### Expected result
new version is created on each save including the note if any
This image is after "save & close" was used with no note and then the article reopened and version checked.
![image](https://github.com/joomla/joomla-cms/assets/1850089/9dc9e1b7-5c84-48fe-a505-1441af08c799)

### Actual result
version is create but notes are seemingly only the last 2.
![image](https://github.com/joomla/joomla-cms/assets/1850089/50fae1bf-23d1-4ba4-9525-af6379a25751)
![image](https://github.com/joomla/joomla-cms/assets/1850089/85896172-cf95-487b-8b73-c7ecbabbfd1a)

### System information (as much as possible)
[systeminfo-2024-04-10T08_28_02+00_00.txt](https://github.com/joomla/joomla-cms/files/14929909/systeminfo-2024-04-10T08_28_02%2B00_00.txt)

**Comment by brianteeman** [comment]
Works as expected for me

![image](https://github.com/joomla/joomla-cms/assets/1296369/ff7e306b-889e-4550-8c89-8a071bbbf363)

Please use the forum for support

**Comment by N6REJ** [comment]
I disagree with your statement that this is a support issue.

**Comment by N6REJ** [comment]
Confirmed its fine.  Sorry @brianteeman

**Comment by brianteeman** [comment]
apology accepted
