### ISSUE TITLE
Joomla 4.4.3 Admin panel Button click to Preview article Error code: Article not found

### ISSUE THREAD

**Issue by bsylwek** [joomla/joomla-cms#43245]
### Steps to reproduce the issue
Joomla 4.4.3 go to Admin panel Button --> click to Preview article  - 404 Error code: Article not found

The preview did not work when the article was not published and there was this error. The preview only works when the article is published.

php 8.1.10

How to solve it?

Global Configuration system analysis and Maximum

Error code: Article not found

components/com_content/src/Model/ArticleModel.php:218
Call stack
# Function Location
1 () JROOT/components/com_content/src/Model/ArticleModel.php:218
2 Joomla\Component\Content\Site\Model\ArticleModel->getItem() JROOT/libraries/src/MVC/View/AbstractView.php:152
3 Joomla\CMS\MVC\View\AbstractView->get() JROOT/components/com_content/src/View/Article/HtmlView.php:110
4 Joomla\Component\Content\Site\View\Article\HtmlView->display() JROOT/libraries/src/MVC/Controller/BaseController.php:660
5 Joomla\CMS\MVC\Controller\BaseController->display() JROOT/components/com_content/src/Controller/DisplayController.php:121
6 Joomla\Component\Content\Site\Controller\DisplayController->display() JROOT/libraries/src/MVC/Controller/BaseController.php:693
7 Joomla\CMS\MVC\Controller\BaseController->execute() JROOT/libraries/src/Dispatcher/ComponentDispatcher.php:143
8 Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() JROOT/components/com_content/src/Dispatcher/Dispatcher.php:56
9 Joomla\Component\Content\Site\Dispatcher\Dispatcher->dispatch() JROOT/libraries/src/Component/ComponentHelper.php:361
10 Joomla\CMS\Component\ComponentHelper::renderComponent() JROOT/libraries/src/Application/SiteApplication.php:208
11 Joomla\CMS\Application\SiteApplication->dispatch() JROOT/libraries/src/Application/SiteApplication.php:249
12 Joomla\CMS\Application\SiteApplication->doExecute() JROOT/libraries/src/Application/CMSApplication.php:293
13 Joomla\CMS\Application\CMSApplication->execute() JROOT/includes/app.php:61
14 require_once() JROOT/index.php:32
Top

**Comment by alikon** [comment]
see #24132
