### ISSUE TITLE
Field group help non-existent

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#43252]
### Steps to reproduce the issue
create a new field group
go to the options tab
click the ? at the top right.

### Expected result
Joomla doc page displays showing help for the fields(?) shown

### Actual result
you get a blank screen
![image](https://github.com/joomla/joomla-cms/assets/1850089/d4000918-a12f-4059-b78e-3ac0afbe64d4)

### System information (as much as possible)

[systeminfo-2024-04-10T08_28_02+00_00.txt](https://github.com/joomla/joomla-cms/files/14940300/systeminfo-2024-04-10T08_28_02%2B00_00.txt)

**Comment by drmenzelit** [comment]
Can't reproduce the issue on Joomla 5.0.3
![grafik](https://github.com/joomla/joomla-cms/assets/9153168/003eaae7-60be-4bac-8d08-a23f3d15a5d7)

**Comment by N6REJ** [comment]
Was using 4.4.3

**Comment by brianteeman** [comment]
I am trying very hard to be polite to you - but just like every other time all your reports have not been confirmed and you always end up apologising and saying it was your site/server. It is not unreasonable to ask you to spend a little time verifying your issue on a secondary site/server before asking others to look at the problem.

**Comment by Quy** [comment]
Cannot reproduce with v4.4.4. Is this happening with the other `? Help` buttons?

**Comment by N6REJ** [comment]
@Quy this is very strange.  I did a complete roll back of all of yesterdays work and when I first opened the field group, went to options and checked helped it showed.  I closed the group reopened it and this time it failed
![image](https://github.com/joomla/joomla-cms/assets/1850089/95e2ad7a-3d5b-4d9f-8c30-cf483135bd48)
Did a CTRL+F5 in chrome and it came back.  So apparently its a chrome issue, I guess.  I had just cleared all caches and everything 3 or 4 days ago so it SHOULDN"T be that *shrug*

@brianteeman My beef is the assumption its my site/server.  In this case it clearly wasn't.  Nothing wrong asking me to first check my other sites.  Had I had more then 4 hrs sleep/day the last 7 days MAYBE I would've thought of that.  On the other hand I'm 62yrs old with failing memory so maybe not!
your statement
>Saves all of us time to work on real issues.

Was what set me off.  That implys that my issues are not real and important.  I understand if the group has to test something that isn't a true bug its a waste of man hours.  I don't discount that.  But verbage is everything!
You and I have a very short fuse with each other so verbage matters even more in those cases.  And yes, I"m trying to be polite with you too.
I find lots of things that I don't report, either because I don't want to get into a pissing contest with you ( 90% of the time, ) OR because I don't have the mental energy to figure out what really is going on.
EXAMPLE.. tonight I updated bearsampp to 5.3 I think it was.. and I noticed right away that things looked strange.  Hovering over the right hand "clean cache" button cause it to turn white with light gray text.  But hovering over the one from cache cleaner worked fine.  
The entire layout just didn't have the right "feel", so I rolled back and threw away all my work because I had no clue what MIGHT have triggered it and have way way too many things to get done.  I'm so far behind schedule that even down is up!

**Comment by brianteeman** [comment]
doubt it will be a chrome issue. no idea what but I doubt that. _over lunch i had a quick scan through the 70+ issues you have opened here and in far too many cases they have resulted in "cannot reproduce" by whoever tried. so forgive me for asking you to check on another server before reporting. I am **not** criticising bearsampp!! I would be asking the same thing of anyone who regularly finds issues that others cannot replicate. Its best practice, as you know, when bug testing to try and find any unique/different settings, as that can often lead to the root cause and probably explain why functionality fails for one person but not for anyone els.e
