### ISSUE TITLE
Atum is loading fontawesome.min.css in the administrator side.

### ISSUE THREAD

**Issue by pl71** [joomla/joomla-cms#43269]
### What needs to be fixed
Atum is loading `fontawesome.min.css` i/o `joomla-fontawesome.min.css`.

### Why this should be fixed
I want some consistency between backend and frontend regarding article creation and representation.

### How would you fix it
remove the redundancy CSS file in the Atum template. Use  `joomla-fontawesome.min.css` from Joomla core.

### Side Effects expected
The appearance of the Atum template should be checked.

**Comment by brianteeman** [comment]
> I want some consistency between backend and frontend

What inconsistencies are you seeing - can you provide some examples please

**Comment by pl71** [comment]
@brianteeman Sorry, it seems to be a JCE issue. Now it is resolved by adding `joomla-fontawesome.min.css` to the custom css-es in its global configuration. Otherwise, fontawesome was not present in the editor area.

**Comment by Quy** [comment]
Closing as not a core issue.

**Comment by brianteeman** [comment]
add it to the list of issues caused by that extension
