### ISSUE TITLE
[5.1.0-rc2] Image Private Messages

### ISSUE THREAD

**Issue by Razzo1987** [joomla/joomla-cms#43270]
### Steps to reproduce the issue
1. Create 2 different user, both with "Receive System Emails" enabled.
2. Form one user send a Private Message to the other
3. Insert an image in the message body (eg. `https://<your joomla>/images/sampledata/cassiopeia/nasa1-1200.jpg`):
![image](https://github.com/joomla/joomla-cms/assets/906604/ba2bf38c-7948-4563-814a-0cc9d2f2c7f8)
4. Send the message
5. Check your inbox mail
6. Logout and login thi the oter user
7. Check your Private Messages

### Expected result
5. Mail have the image
7. Private Messages must have the image

### Actual result
5. Mais haven't the image:
![image](https://github.com/joomla/joomla-cms/assets/906604/85dc9c90-bd7a-4eaa-9f25-ca1a7996639c)
7. your Private Messages have the wrong image url
![image](https://github.com/joomla/joomla-cms/assets/906604/626bbb2c-d9ce-4a76-8d5e-cb5fbbc5d160)

### System information (as much as possible)
Joomla 5.1.0-rc2

### Additional comments
The image url does not have the initial /
![image](https://github.com/joomla/joomla-cms/assets/906604/fc563d2f-243f-4101-b654-0d03de50f1ee)
If the URL begins without a slash, it will be relative to the current page. Example: src="img_girl. jpg". If the URL begins with a slash, it will be relative to the domain.

@brianteeman It could be related to PR https://github.com/joomla/joomla-cms/pull/42448 ?

**Comment by brianteeman** [comment]
#42448 was about adding images etc to the mail TEMPLATE so that you can do some branding
What you are talking about here is adding an image to the private message. Different thing

**Comment by Razzo1987** [comment]
Ok, is different bug :(

**Comment by Kubik-Rubik** [comment]
This is not a bug of the Messaging component but a feature provided by the TinyMCE editor to convert absolute URLs to relative URLs.

To "fix" this issue, go to "System" - "Plugins" - "Editor TinyMCE" and set the option **URLs** to **Absolute**:

<img width="419" alt="grafik" src="https://github.com/joomla/joomla-cms/assets/1976103/f2345faf-d29d-4c67-b952-612515283f7a">

**Comment by brianteeman** [comment]
Sorry but that is not correct for this. Making that change will change it everywhere not just in private messages.

**Comment by Kubik-Rubik** [comment]
Yes, you are right. I explained the reason for this behaviour.

We need to apply the same logic for such relative URLs as we do in the SEF plugin (add the base path if required - \Joomla\Plugin\System\Sef\Extension\Sef::onAfterRender).

**Comment by brianteeman** [comment]
The correct way to address this is in the messaging component where the editor is rendered. Too late for me to write tested and working code but it would be something like

```
$params = ['relative_urls' => 'true']
$content = $editor->display($name, $content , $width, $height, $col, $row, true, $id, null, null, $params);
```

**Comment by Hackwar** [comment]
Actually we have to apply the logic of the SEF plugin partially to the output. Setting this option for tinymce will break the moment people use a different editor. Basically we have to copy the code to make the URLs absolute from the SEF plugin to the output of the message. Any takers?

**Comment by Quy** [comment]
Please test PR #43897. Thanks.
