### ISSUE TITLE
[5.0.3] Bug with archived categories and menu

### ISSUE THREAD

**Issue by JoomlaBelarus** [joomla/joomla-cms#43271]
### Steps to reproduce the issue

Create new category or change your some category, with articles -  status to archive.  
Create new menu item - Articles-> Archiwed Articles and try to select this archived category - they are not wisible in categories list for select

### System information (as much as possible)

Joomla 5.0.3. PHP 8.2, MariaDB 10.8

### Additional comments

Is it possible for visible archived categories for  select in menu?

**Comment by brianteeman** [comment]
The menu item is to display archived **articles** inside a category
No articles inside an archived **category**

This allows you to have articles in various states inside the came category. In other words you can change an article to the archive status without haivng to move it to another category.
