### ISSUE TITLE
Editor not shown in German

### ISSUE THREAD

**Issue by thuebschmann** [joomla/joomla-cms#43286]
### Steps to reproduce the issue
Update Joomla Germen Language
Open Editor

### Actual result

Editor not shown

### Additional comments

If i create an Language overeide 
<pre>
JLIB_JS_AJAX_ERROR_PARSE="Ein Parsing-Fehler trat bei der Verarbeitung der folgenden JSON-Daten auf:<code>%s</code>"
</pre>
editor ist allready shown

**Comment by tecpromotion** [comment]
@thuebschmann please create an issue with more information here https://github.com/joomlagerman/joomla/issues/new/choose

**Comment by HLeithner** [comment]
I'm closing this since it seems to be the wronger issue tracker. thanks stefan

**Comment by thuebschmann** [comment]
@tecpromotion I Create an Issue https://github.com/joomlagerman/joomla/issues/3164<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43286">issues.joomla.org/tracker/joomla-cms/43286</a>.</sub>
