### ISSUE TITLE
Plugin XML Form Field Description Not Being Displayed

### ISSUE THREAD

**Issue by 2dpi** [joomla/joomla-cms#43281]
### Steps to reproduce the issue

Add a description attribute to any plugin XML field. Access the plugin in the admin area. 

The description does not appear below the relevant form input field.

### Expected result

Description text to display below the relevant form input field.

### Actual result

No description text is displayed.

### System information (as much as possible)

Joomla! 5.0.3

### Additional comments

CSS Class added to all fields with descriptions 

class="hide-aware-inline-help d-none" - Is this intentional and if so where can it be disabled?

Description text seems to work when an additional XML file is included.

**Comment by Quy** [comment]
Click on the `Toggle Inline Help` button in the upper right corner.

**Comment by Kubik-Rubik** [comment]
Yes, starting with Joomla! 4, the descriptions are hidden by default, and the user must enable it manually with the `Toggle Inline Help` button (just as @Quy said).

**Comment by alikon** [comment]
closing as expected behaviour

**Comment by 2dpi** [comment]
Thx, that makes sense. 

Guess I missed the memo :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43281">issues.joomla.org/tracker/joomla-cms/43281</a>.</sub>
