### ISSUE TITLE
 [5.1] Update FontAwesome to 6.5.2

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#43285]
### Is your feature request related to a problem? Please describe.

 Update FontAwesome to 6.5.2

### Describe the solution you'd like

[https://github.com/FortAwesome/Font-Awesome/releases/tag/6.5.2](https://github.com/FortAwesome/Font-Awesome/releases/tag/6.5.2)

### Additional context
Joomla is currently using FontAwesome to 6.5.1
+ update to Bootstrap 5.3.3 
[https://github.com/joomla/joomla-cms/issues/42964](https://github.com/joomla/joomla-cms/issues/42964)

**Comment by HLeithner** [comment]
As already mentioned in #42964 we have a timeline when we update 3rd party dependencies.
The next scheduled update (as long as it's not a security update) is on 03. Sep 2024 with 5.2 beta1.

I'm closing this for now.
