### ISSUE TITLE
cannot delete image in media manager

### ISSUE THREAD

**Issue by o-joomla-issues** [joomla/joomla-cms#43280]
### Steps to reproduce the issue
Upload image
Mark/check image
Click delete button

### Expected result
File deleted

### Actual result
Error message "Error deleting the item."
Image not deleted

### System information (as much as possible)
Joomla! ‎5.0.3
PHP 8.3.4 as fpm-fcgi on nginx

### Additional comments
Folder owner/rights were checked and are ok
Happens in either images root folder or any sub folder
Image can be deleted with third party file(media manager like the one from Joomla Content Editor

**Comment by brianteeman** [comment]
Is it a specific image or any image?

**Comment by o-joomla-issues** [comment]
Fixed typo in title<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43280">issues.joomla.org/tracker/joomla-cms/43280</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Check the browser console for errors. Also, check the server response from the action for more information in the network tab of the developer tools. Increase the error level and enable the debug mode to get a more detailed error message and the error stack.

**Comment by o-joomla-issues** [comment]
Hi Victor,

checking the console actually helped: server was configured to reject DELETE requests as suggested by some Joomla hardening tips for J3.

Problem solved, it's not a Joomla issue.

Sorry for causing inconvenience and thank you supporting the Joomla project so very much.

**Comment by Kubik-Rubik** [comment]
Awesome! It's my pleasure to support the Joomla! project.

Please close the issue.

**Comment by o-joomla-issues** [comment]
In case anyone stumbles across similar problems: do not block any of GET|HEAD|POST|DELETE request methods for Joomla 4.x+<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43280">issues.joomla.org/tracker/joomla-cms/43280</a>.</sub>
