### ISSUE TITLE
Redirect component: Wrong error message shown when not collecting URLs

### ISSUE THREAD

**Issue by kauffeld** [joomla/joomla-cms#43298]
I am using German Language in Joomla so some English term may not be correct.

### Steps to reproduce the issue

In Joomla administration dashboard go to System - Plugins
Select System - Redirect
Deactivate Collect URLs
Save and close

Go to Redirects 

### Expected result

A warning message with Id 'COM_REDIRECT_COLLECT_MODAL_URLS_DISABLED' should occur.

### Actual result

An error message with Id 'COM_REDIRECT_PLUGIN_MODAL_DISABLED' occurs.

### System information (as much as possible)

Error occurs with Joomla 5.1.0. With 5.0.3 the message was ok.

### Additional comments

When collection URLs the message is ok.

**Comment by brianteeman** [comment]
See #42447

**Comment by brianteeman** [comment]
No idea at all why I posted that comment - sorry

**Comment by brianteeman** [comment]
This is a bug, Looking into it now

**Comment by kauffeld** [comment]
Ok, that's what I expect and that's how it was before Joomla 5.1.0

**Comment by Fedik** [comment]
I have moved the message from controller to the layout.
Not sure why I change "notice" to "warning", maybe mixed up something.
I will make PR later.

**Comment by brianteeman** [comment]
its your logic for determining if the plugin is enabled or not that I dont understand

**Comment by Fedik** [comment]
Yes, I mean, it should stay the same as before. 
I not remember why I did change message type.

**Comment by brianteeman** [comment]
I dont think you realised you had. I think the logic you ghave for testing what is enabled etc is wrong and thats what confused you. It sure as hell confused me.

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/43402
