### ISSUE TITLE
Trailing Slash Issue In Joomla 5.1 Canonical Homepage

### ISSUE THREAD

**Issue by Geoffresh** [joomla/joomla-cms#43294]
### Steps to reproduce the issue
In the SEF plugin, set "enforce URLS without trailing slash" and inspect the homepage and a sub page (example.com and example.com/page1). Notice that the canonical is correct for example.com/page1 but example.com has a canonical with a trailing slash.

### Expected result
Canonical follows the URL without trailing slash.

### Actual result
URLs follow the correct non trailing slash while the canonical for the homepage contains the trailing slash.

### System information (as much as possible)
Joomla 5.1

### Additional comments
I am happy to say that I've successfully updated to Joomla 5.1 on my website. I can see from the release notes that there are some SEO items for the SEF plugin that have been added.
https://www.joomla.org/announcements/re ... -here.html

Specifically this one about the trailing slash.
https://github.com/joomla/joomla-cms/pull/42702

This works great! However, I am noticing a strange issue with the homepage canonical now. It is still generating a URL to have a trailing slash even though all of the URLs are supposed to not have the trailing slash. For example. If in the SEF plugin you set "enforce URLS without trailing slash" that works for the URLs in subfolders, but not for the domain. So in the browser you will see https://example.com but for the canonical you will see "https://example.com"

**Comment by rfmjoe** [comment]
as far as i know, joomla core hat no "canonical" link feature built in. So this might rely to the plugin/component you are using maype?

**Comment by Geoffresh** [comment]
Hi rfmjoe,

Thank you for your response. The plugin actually does have this feature. When you access this plugin, place your domain in the "Site Domain" field (without the trailing slash) and you'll see that your pages now generate a canonical tag in the HTML.

Thank you,
Geoffrey<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43294">issues.joomla.org/tracker/joomla-cms/43294</a>.</sub>

**Comment by Geoffresh** [comment]
Hi Richard,

Thank you for your response. Yes, this is like I describe so it must be a bug. Please see the attached screenshot. 
<img width="801" alt="Screenshot 2024-04-18 at 8 04 23 AM" src="https://github.com/joomla/joomla-cms/assets/129969858/3d04683f-3ca3-43e0-b840-4ec15ab9d722">

**Comment by Geoffresh** [comment]
Out of curiosity, is this something that the Joomla core team will work on? Is there a process to submit this for consideration? I'm just not sure what the next steps would be to advocate for this.

Thank you

**Comment by richard67** [comment]
Wait until someone makes a pull request for it, or if you have an idea how to solve it make a pull request yourself.

**Comment by Hackwar** [comment]
So, the way you are using this feature, it is actually very counterproductive. I would strongly suggest to disable the "canonical" option again. As was described, this is to define a canonical domain, but it will definitely NOT create a canonical URL. If your site needs canonical URLs because you have the same content available via different URLs, this will mean that each of those differing URLs with the same content will have their current URL as canonical Tag set. That makes this absolutely useless and actually makes Google ignore the canonical tag and in worst case penalize you. 

Looking at this, my position would be, that this is a wontfix, since the slash after the domain never creates a duplicate content.

**Comment by Hackwar** [comment]
Sicne there was no response in the last 2 weeks and for the reasons stated above, I'm closing this issue. If you feel this is not correct, please respond here and we can see if we reopen this ticket or if we need a new ticket.
