### ISSUE TITLE
Syntax error in joomla 5.1.0 upgrade file

### ISSUE THREAD

**Issue by nikitakothari06** [joomla/joomla-cms#43302]
### Steps to reproduce the issue
Execute administrator\components\com_admin\sql\updates\mysql\5.1.0-2024-02-24.sql file's query manually.

### Expected result
Should not throw a syntax error.

### Actual result
#1064 - You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '-----------------------------------------------------------
#__upd' at line 1

### System information (as much as possible)
Joomla 5.0.1
PHP 8.1
Mysql 8.0

### Additional comments
Line 27 comment should be in the following way.(space after two --) in administrator\components\com_admin\sql\updates\mysql\5.1.0-2024-02-24.sql file
"-- ---------------------------------------------------------"

**Comment by richard67** [comment]
@nikitakothari06 Not really an issue as the updater doesn't execute the SQL script as such, but it splits it into the individual statements and executes each statement individually, so that syntax error will never happen with a Joomla update.

Nevertheless we can fix it of course.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #43306 . When having tested, please go to the pull request in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/43306 and use the blue "Test this" button at the top left corner, then sn select your test result and finally submit.

Thanks in advance.
