### ISSUE TITLE
collectLayoutData() feature (#42709) crashes subforms

### ISSUE THREAD

**Issue by dawe78** [joomla/joomla-cms#43303]
### Steps to reproduce the issue
- create a test view
- create forms (see attached txt-files)
- preset data in test model:
```php
protected function loadFormData()	{
    $data = new \stdClass();
    $data->title = "Test entry";
    $data->subform = array();
		
    $subItem = new \stdClass();
    $subItem->id = 2;
    $subItem->listfield = array(2,3);
    $subItem->date_1 = mktime(0,0,0,11,10,2019);
    $subItem->date_2 = mktime(0,0,0,11,15,2019);
    $data->subform[] = $subItem;

    $subItem = new \stdClass();
    $subItem->id = 3;
    $subItem->listfield = array(1,3);
    $subItem->date_1 = mktime(0,0,0,11,10,2020);
    $subItem->date_2 = mktime(0,0,0,11,15,2020);
    $data->subform[] = $subItem;
    return $data;
}
```
- call view in backend

### Expected result
Form fields are rendered with loaded data

### Actual result
Form fields (calendar) are all set to current date; only loaded once per fieldname, not per subform element

### System information (as much as possible)
Ubuntu 22.04
Apache 2 Webserver
PHP 8.3
Joomla 5.1.0

### Additional comments
If I comment out line 1353 in /libraries/src/Form/FormField.php (do not used previous stored layoutData), eg.

if ($this->layoutData) {
    //return $this->layoutData;
}

forms fields are loaded as expected.

**Comment by dawe78** [comment]
I could not upload these files, so I put it here:

Main form:
```
<?xml version="1.0" encoding="UTF-8"?>
<form>
    <fieldset name="general">
        <field name="id" type="text" default="0" label="JGLOBAL_FIELD_ID_LABEL" required="true" readonly="true" class="readonly" />
        <field name="title"  type="text" required="true" label="Test" description=""/>
	<field name="subform" type="subform" clayout="joomla.form.field.subform.repeatable-table" formsource="path_to_subform/subform_test.xml" multiple="true" label="Subform" description="" />
    </fieldset>
</form>
```

Subform:
```
<?xml version="1.0" encoding="UTF-8"?>
<form>
    <fieldset name="general">
        <field name="id" type="text" default="0" label="JGLOBAL_FIELD_ID_LABEL" required="true" readonly="true" class="readonly" />
        <field name="listfield" layout="joomla.form.field.list-fancy-select" type="list" required="true" label="List" description="" multiple="1">
		<option value="1">option 1</option>
		<option value="2">option 2</option>
		<option value="3">option 3</option>
        </field>
        <field name="date_1" type="calendar" required="1" label="date 1" description=""/>
        <field name="date_2" type="calendar" required="1" label="date 2" description=""/>
    </fieldset>
</form>
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43303">issues.joomla.org/tracker/joomla-cms/43303</a>.</sub>

**Comment by brianteeman** [comment]
> type="subform" clayout=

is that a typo?

**Comment by dawe78** [comment]
Edit: this issue seems to match only for table-subforms, layout joomla.form.field.subform.repeatable-table. If default layout is set (I disabled by adding c before layout as in above example) everything works fine.

So two edits for example:
- for reproducing issue, "clayout" for subform layout in above example must be renamed to layout
- if subform default layout is set, there is no issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43303">issues.joomla.org/tracker/joomla-cms/43303</a>.</sub>

**Comment by Fedik** [comment]
Ah, I get it, it nothing to do with subform.
It a bug in calendar field, the fix is there https://github.com/joomla/joomla-cms/pull/43234
Please test it to be sure.

Thanks.

**Comment by dawe78** [comment]
@Fedik fix checked, works, thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43303">issues.joomla.org/tracker/joomla-cms/43303</a>.</sub>
