### ISSUE TITLE
[J5.1] Usability Issue - Switching Between Dark And Light Modes

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#43307]
### Summary

Dark Mode in J5.1 is a major improvement over J5.0. A huge 'Thanks' to Elisa and all the other contributors! But there is still some distance to go. Even if Dark mode in Joomla core would be perfect, there are still a number of extensions, which don't work perfectly in Dark Mode. This forces the user to switch between dark and light modes frequently.

But in core, there are some weak points as well, some of which I address with this issue:

### The dark mode switch, a hidden feature
As written above, it is sometimes necessary to switch between dark and light mode. J5.1 does even implement a switch to do so easily, at least in theory. But the feature is most perfectly hidden, when updating from a previous Joomla version:

- The switch is not available by default, ... 
- ... but must be activated by the user with the following process:
    - The user has to navigate to the Atum style page. There he is supposed to do a Save (or Save & Exit), even if not doing any (other) change. 
    - And, miraculously, the switch appears in the User Menu!

IMHO, the switch should be visible by default, also if updating from a previous version.

### Even when the switch is visible, it is still misleading. 
When in dark mode, the user sees a symbol for 'night' and reads 'Dark Mode'. 

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/27384d12-42dd-4957-9e67-b9eaea95b13b)

I propose to modify the menu item like this: An icon for the current state followed by an action like 'Switch to ... Mode'. For the two possible states:

- (fa-moon) Switch to Light Mode
- (fa-sun) Switch to Dark Mode

### Steps to reproduce the issue

1. Install a fresh J5.0.3
2. Update to J5.1.0
3. Open the backend
4. Find the User menu in the top right corner

### Expected result

- As described above, the Dark / Light Mode switch should be activated by default. 
- The switch should be labelled as described above.

### Actual result

- The Dark / Light Mode switch is not visible.
- Even after the cumbersome activation process, it is misleading.

### System information (as much as possible)

J5.1.0
PHP 8.2 / 8.3
MySQL 8.0.33

**Comment by brianteeman** [comment]
Sorry but your comments are not correct.

On a CLEAN install of joomla there is nothing to do. The selector is available by default.

**Comment by brianteeman** [comment]
As for the comment about the switch being misleading - I agree. 

In this case the display is the "current" state and clicking on it will change to the opposite state

This is the same "problematic" issue we have throughout Joomla that we have never resolved in 18 years. Look at the State button/icon in the article manager. The behaviour is the same.

![image](https://github.com/joomla/joomla-cms/assets/1296369/d89e1a23-02b3-497e-9e94-5dc2a1ba33bf)

The display is the "current" state (published) and clicking on it will change to the opposite state (unpublished)

For everyone that expresses an opinion that this pattern is correct there is another person who expresses the opinion that it is wrong. Joomla can't win in this case. 

As we have grown accustomed to this behaviour since forever for the status buttons changing the dark mode to work in an opposite direction would be more confusing and not less

**Comment by dautrich** [comment]
@brianteeman 

You're perfectly right! On a clean install, the switch is enabled by default, but not when updating from a previous J5 to J5.1.
Therefore, the update process should enable the switch. I have updated my previous comment.

**Comment by dautrich** [comment]
I don't completely agree to your second comment. Your example shows just a button of 'checkbox' type, where there is no room for longer explanations. Not so in the user menu. My proposal is to show the current state plus an action to change the state.

**Comment by brianteeman** [comment]
> Therefore, the update process should enable the switch.

Thats a BUG. And easy to fix

**Comment by brianteeman** [comment]
> I don't completely agree to your second comment. Your example shows just a button of 'checkbox' type, where there is no room for longer explanations. Not so in the user menu. 

we have the longer explanations in the "tooltip" and that gets even more inconsistent as you use it. 

The amount of space in the user menu is language dependent but I am definitely open to seeing a mockup that will show both the current state and how to chanage to another state. Sadly the UX group appears to be no more.

**Comment by brianteeman** [comment]
@richard67 This works localy but no idea if it is good enough and/or if the same can be done in postgres

```

UPDATE `#__template_styles`
SET `params` = CONCAT(SUBSTRING(`params`, 1, LENGTH(`params`) - 1), ', "colorScheme": "os"}')
WHERE `template` = 'atum'
AND `params` NOT LIKE '%colorScheme%';
```

This SQL statement updates the params field in the #__template_styles table for the template named 'atum'. It appends ,"colorScheme": "os"} to the existing value of params, but only if the params field does not already contain 'colorScheme'.

This update ensures that the color scheme parameter is added to the params field for the 'atum' template if it doesn't exist already, without duplicating it if it's already present.

**Comment by richard67** [comment]
@brianteeman In J5 we can use json functions due to the raised db version requirements. So no need for such risky string replacements on json strings. We have already some example in some 5.x update SQL script which shows how it can be done here, too. I can’t search it now. But if you grep the 5.x update SQL scripts for „json“ (case-insensitive) you may find it.

**Comment by brianteeman** [comment]
i did try json first - lol will do it that way

**Comment by richard67** [comment]
@brianteeman Example for MySQL/MariaDB: https://github.com/joomla/joomla-cms/blob/5.1-dev/administrator/components/com_admin/sql/updates/mysql/5.0.0-2023-08-21.sql

For PostgreSQL: https://github.com/joomla/joomla-cms/blob/5.1-dev/administrator/components/com_admin/sql/updates/postgresql/5.0.0-2023-08-21.sql

The script changes an existing parameter and not adds a new one, but that should be very similar.

Documentation:
- https://dev.mysql.com/doc/refman/8.0/en/json-modification-functions.html
- https://mariadb.com/kb/en/json_replace/
- https://mariadb.com/kb/en/json_extract/
- https://www.postgresql.org/docs/12/functions-json.html

**Comment by richard67** [comment]
P.S.: On weekend I might have time to help more, if necessary.

**Comment by dautrich** [comment]
> The amount of space in the user menu is language dependent but I am definitely open to seeing a mockup that will show both the current state and how to chanage to another state. Sadly the UX group appears to be no more.

I've played around a little bit with my browser's devtools.

See here a mockup of my proposal in English language:
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/710ee0fc-f280-46b8-a387-2f0d533f476f)

The width of the menu seems to be dynamic, Therefore, this would even work for German despite the lengthy German words:
![grafik](https://github.com/joomla/joomla-cms/assets/7933215/99542e43-5333-4c58-9fdd-ca8ee77bf381)

**Comment by brianteeman** [comment]
the first thing I thought when I saw this was why do you have the wrong icon.

**Comment by brianteeman** [comment]
> I read it like this: It's the current state, followed by the action to change to the alternate state.

and thats the problem as I said before. 50% will read it one way and 50% will read it another.

**Comment by dautrich** [comment]
I didn't invent it like this. But at least the text of the menu item should explain its use. And that's what I propose.

**Comment by dautrich** [comment]
@coolcat-creations @chmst @LadySolveig 

This issue consists of two parts, that might better be handled independently:

1. The Dark Mode switch does appear in J5.1.0 only after some strange process.
2. I made a proposal to modify the text on the Dark Mode switch.

Number 1 has been identified as a bug. PR  #43310 has been created and merged.

I'm in doubt how to handle number 2. I have made a proposal in this issue (see my post dated April 19, 2024, and the subsequent discussion with Brian Teeman). As I don't see any progress on this issue, I see two options:

- I give up and close this issue without further action.
- I close this issue and open a new one with just my proposal.

What do you think?

**Comment by brianteeman** [comment]
How about this.

The icon represents the current state and the text identifies what you can switch between

![image](https://github.com/joomla/joomla-cms/assets/1296369/01a7959b-3672-4efa-9914-67b337e18bee)

![image](https://github.com/joomla/joomla-cms/assets/1296369/3774d96a-1727-49c4-84f8-0d10604e212b)

**Comment by dautrich** [comment]
Much better than the current solution.

**Comment by brianteeman** [comment]
i will make a pr in the morning and see what others think

**Comment by brianteeman** [comment]
ok - so i lied - did the PR now. #43454

**Comment by richard67** [comment]
Closing as having a pull request. See #43454 .
