### ISSUE TITLE
Unexpected error on extension update

### ISSUE THREAD

**Issue by BrainforgeUK** [joomla/joomla-cms#43319]
### Steps to reproduce the issue

Using Extensions: update (.../administrator/index.php?option=com_installer&view=update) attempt to update a plugin which relies up a third party component.

The plugin must be enabled.
Note: Error does not occur if the plugin is disabled.

The error occurs because the preparePreUpdate() function loads the plugin. This invokes the plugin constructor. In the example encountered the plugin assumes it has been loaded by that third party component, but of course in this case it is being loaded by com_installer.

### Expected result

Sensible error message explaining where the problem is.

### Actual result

Class XXXXXXXXXXXX not found error message.
Leaves updater wondering what its about.

### System information (as much as possible)

PHP 8.2

**Comment by BrainforgeUK** [comment]
Fixed in Pull Request #43321<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43319">issues.joomla.org/tracker/joomla-cms/43319</a>.</sub>

**Comment by brianteeman** [comment]
Sure we've siad it before but if you intend to immediately create a pull request then there is no need to create an issue - it serves no purpose and just wastes maintainers time
