### ISSUE TITLE
Please, build in consistent functionality for Prev/Next buttons in a sequential serie of single articles

### ISSUE THREAD

**Issue by sthopd** [joomla/joomla-cms#43314]
Hello,
Is Joomla only meant for publishing newspapers, magazines and blogs?
I want to write an online educational book by means of Joomla 5 as publication medium.
The book consists of hundreds of pages (on paper) that are not always written in the correct order of the ongoing story.
The book will be created by 'progressive insight' and is continuously adjusted/corrected (online digital reconstruction).
This means that new webpages (Single Articles) are frequently inserted between existing pages in Joomla-FrontEnd.
Is this digitally possible in Joomla5 Frontend?
Joomla has the 2 separate, simple buttons: 1. on the left side of (some?) webpages (Single Article): '<Prev' 
2. and on the right side of (some?) webpages: 'Next>'.

The current Joomla-functionality of the Prev/Next buttons is too simple, because it only takes into account the sequence of 'publish_up' or 'created date'. At least, that's how it seems.
Is it possible that Joomla developers extend the Settings-functionality in such a way that the webmaster or author can set and edit the sequential order of Prev/Next hops between story-pages? 
The author needs to adjust the sequence of existing articles (Previous page/Next page) to fit the reading-order of an ongoing story, to make it comprehensible and lively for online visitors or students.
For example: the way how it is done in Moodle LMS.
In other words:
Is it possible to program (in code) an expansion of the existing functionality for the Prev/Next buttons (as an extra settings-option in the backend/admin-dashboard) for example:

a) Couple the sequential articles read-order of Previous/Next buttons to the sequential item-order in the (sub)menu designated by the author?
or:
b) Couple the sequential articles read-order of Previous/Next buttons to the sequential item-order in the designated (sub)category?

Regards,
sthopd

Joomla 5.0.3
Template: Cassiopeia (bare).

**Comment by brianteeman** [comment]
I belive what you are asking for is as shown in this video ?


https://github.com/joomla/joomla-cms/assets/1296369/a12c70f7-05d5-4387-958d-eb3be0d05378
