### ISSUE TITLE
J5.0.3 Media Manager doesn't like capital names like file.JPG

### ISSUE THREAD

**Issue by thetexian** [joomla/joomla-cms#43315]
### Steps to reproduce the issue
File named IMG_455.JPG
In media manager edit mode, resized and cropped. Upon save, nothing changed. No messages, no acknowledgement.

### Expected result
Expected result is change to image

### Actual result
No change. No message

### System information (as much as possible)
J 5.0.3 Media Manager

### Additional comments
When file renamed to IMG_455.jpg, worked as designed
Media manager doesn't like capitalized filetypes apparently.

**Comment by brianteeman** [comment]
I just added this for you to the relevant open issue. #43220

**Comment by dgrammatiko** [comment]
Should be fixed with https://github.com/joomla/joomla-cms/pull/43295

**Comment by richard67** [comment]
Closing as fixed with #43295 .

**Comment by brianteeman** [comment]
sorry to say but 43295 does not fix this

**Comment by dgrammatiko** [comment]
FWIW it's not the filename the problem but the capitalized extension. I thought the mentioned PR would fix this but I had to revert some code when I realized that the canvas element has some inconsistent functionality across browsers and also realizing that introducing more formats for the editing part is a major change that can't happen before 6.0 or it would break all existing plugins.

**Comment by dgrammatiko** [comment]
Please test: https://github.com/joomla/joomla-cms/pull/43325

**Comment by richard67** [comment]
Closing as having a pull request. Please test #43325 . Thanks in advance.
