### ISSUE TITLE
Too many redirects error when password reset is active and MFA is required

### ISSUE THREAD

**Issue by benyrfg** [joomla/joomla-cms#43311]
### Steps to reproduce the issue
1. Create new user with "Require Password Reset" option active, add user to "Registered" user group
2. In the Users -> Options -> Multi-factor Authentication set "Enforce Multi-factor Authentication" for "Registered" user group like this: 
![Screenshot - 2024-04-18T224615 701](https://github.com/joomla/joomla-cms/assets/16369993/14bf4709-5284-4dce-b06d-ed0ca109b941)
3. Go to the frontend and try to log-in

### Expected result
User should by asked for new password and then set-up MFA method

### Actual result
Error: Too_Many_Redirects
In the URL is first displayed "/my-profile?view=methods", then "/my-profile?layout=edit" (it alternates when reload)

### System information (as much as possible)
Joomla 5.1
Also tested on Joomla 5.0.3
Tested on Cassiopeia 
PHP 8.2.12
MariaDB 10.5.22
Linux www10 5.14.0-362.24.1.el9_3.0.1.x86_64

**Comment by Quy** [comment]
Duplicate #40729

**Comment by Quy** [comment]
Closing as duplicate. Thanks for the report.

**Comment by benyrfg** [comment]
After updating to 5.1.4 this issue persists.

**Comment by Hackwar** [comment]
I created a PR #44521 to fix this. Please test. Since we have a PR, I'm closing this issue.
