### ISSUE TITLE
[5.1]Joomla Update

### ISSUE THREAD

**Issue by djfermin** [joomla/joomla-cms#43329]
### Steps to reproduce the issue
update 5.0.3 to 5.1
![image error](https://i.imgur.com/seJ04y7.png "image error")

### Expected result
https://www.fervent-swirles.46-231-5-100.plesk.page/administrator/

mysqli_sql_exception > mysqli_sql_exception
HTTP 500 Whoops, looks like something went wrong.

Unknown column 'autostart' in 'field list'

mysqli_sql_exception
Show exception properties

in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php (line 138)
in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php -> prepare (line 138)
in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php -> __construct (line 1020)
in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/vendor/joomla/database/src/DatabaseDriver.php -> prepareStatement (line 1785)
DatabaseDriver->setQuery() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/administrator/components/com_guidedtours/src/Model/TourModel.php (line 548)

                ->from($db->quoteName('#__guidedtours'))
                ->where($db->quoteName('published') . ' = 1')
                ->where($db->quoteName('uid') . ' = :uid')
                ->bind(':uid', $uid, ParameterType::STRING);
     **       $db->setQuery($query);**
            try {
                $result = $db->loadResult();
                if ($result === null) {
                    return false;

TourModel->isAutostart() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/plugins/system/guidedtours/src/Extension/GuidedTours.php (line 172)
in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/vendor/joomla/event/src/Dispatcher.php -> onBeforeCompileHead (line 454)
Dispatcher->dispatch() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Document/Renderer/Html/MetasRenderer.php (line 62)
MetasRenderer->render() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Document/HtmlDocument.php (line 575)
HtmlDocument->getBuffer() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Document/HtmlDocument.php (line 894)
HtmlDocument->_renderTemplate() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Document/HtmlDocument.php (line 647)
HtmlDocument->render() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Document/ErrorDocument.php (line 139)
ErrorDocument->render() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Error/Renderer/HtmlRenderer.php (line 70)
HtmlRenderer->render() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Exception/ExceptionHandler.php (line 136)
ExceptionHandler::render() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Exception/ExceptionHandler.php (line 73)
ExceptionHandler::handleException() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Application/CMSApplication.php (line 336)
CMSApplication->execute() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/administrator/includes/app.php (line 58)
require_once('/var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/administrator/includes/app.php') in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/administrator/index.php (line 32)

mysqli_sql_exception

Unknown column 'autostart' in 'field list'

in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php (line 138)
in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php -> prepare (line 138)
in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php -> __construct (line 1020)
in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/vendor/joomla/database/src/DatabaseDriver.php -> prepareStatement (line 1785)
DatabaseDriver->setQuery() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/administrator/components/com_guidedtours/src/Model/TourModel.php (line 548)

                ->from($db->quoteName('#__guidedtours'))
                ->where($db->quoteName('published') . ' = 1')
                ->where($db->quoteName('uid') . ' = :uid')
                ->bind(':uid', $uid, ParameterType::STRING);
**            $db->setQuery($query);**
            try {
                $result = $db->loadResult();
                if ($result === null) {
                    return false;

TourModel->isAutostart() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/plugins/system/guidedtours/src/Extension/GuidedTours.php (line 172)
in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/vendor/joomla/event/src/Dispatcher.php -> onBeforeCompileHead (line 454)
Dispatcher->dispatch() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Document/Renderer/Html/MetasRenderer.php (line 62)
MetasRenderer->render() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Document/HtmlDocument.php (line 575)
HtmlDocument->getBuffer() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Document/HtmlDocument.php (line 894)
HtmlDocument->_renderTemplate() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Document/HtmlDocument.php (line 647)
HtmlDocument->render() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Application/CMSApplication.php (line 1073)
CMSApplication->render() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Application/AdministratorApplication.php (line 434)
AdministratorApplication->render() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/libraries/src/Application/CMSApplication.php (line 311)
CMSApplication->execute() in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/administrator/includes/app.php (line 58)
require_once('/var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/administrator/includes/app.php') in /var/www/vhosts/fervent-swirles.46-231-5-100.plesk.page/httpdocs/administrator/index.php (line 32)

### System information (as much as possible)

PHP 8.2.18
Aplicacion FPM servido por Apache

### Additional comments

the front is good

**Comment by richard67** [comment]
@djfermin Could you post the content of the log file from the update, administrator/logs/joomla_update.php? It seems the update was not complete so the database updates were not complete.

**Comment by benyrfg** [comment]
Same issue whem updating from 5.0.3 to 5.1 administration fellt down with Error 500

Unknown column 'autostart' in 'field list'
mysqli_sql_exception
Show exception properties
in /data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php (line 138)
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/vendor/joomla/database/src/Mysqli/MysqliStatement.php#L138)-> prepare (line 138)
in /data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php -> __construct (line 1020)
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/vendor/joomla/database/src/DatabaseDriver.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/vendor/joomla/database/src/DatabaseDriver.php#L1785)-> prepareStatement (line 1785)
DatabaseDriver->setQuery(object(MysqliQuery))
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/administrator/components/com_guidedtours/src/Model/TourModel.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/administrator/components/com_guidedtours/src/Model/TourModel.php#L548)(line 548)
`            ->from($db->quoteName('#__guidedtours'))            ->where($db->quoteName('published') . ' = 1')            ->where($db->quoteName('uid') . ' = :uid')            ->bind(':uid', $uid, ParameterType::STRING);        $db->setQuery($query);        try {            $result = $db->loadResult();            if ($result === null) {                return false;`
TourModel->isAutostart('joomla-welcome')
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/plugins/system/guidedtours/src/Extension/GuidedTours.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/plugins/system/guidedtours/src/Extension/GuidedTours.php#L172)(line 172)
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/vendor/joomla/event/src/Dispatcher.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/vendor/joomla/event/src/Dispatcher.php#L454)-> onBeforeCompileHead (line 454)
Dispatcher->dispatch('onBeforeCompileHead', object(BeforeCompileHeadEvent))
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Document/Renderer/Html/MetasRenderer.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Document/Renderer/Html/MetasRenderer.php#L62)(line 62)
MetasRenderer->render(null, array(), null)
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Document/HtmlDocument.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Document/HtmlDocument.php#L575)(line 575)
HtmlDocument->getBuffer('metas', null, array())
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Document/HtmlDocument.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Document/HtmlDocument.php#L894)(line 894)
HtmlDocument->_renderTemplate()
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Document/HtmlDocument.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Document/HtmlDocument.php#L647)(line 647)
HtmlDocument->render(false, array('template' => 'atum', 'directory' => '/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/administrator/templates', 'debug' => 2, 'csp_nonce' => null, 'templateInherits' => '', 'params' => object(Registry), 'file' => 'error.php'))
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Document/ErrorDocument.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Document/ErrorDocument.php#L139)(line 139)
ErrorDocument->render(false, array('template' => 'atum', 'directory' => '/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/administrator/templates', 'debug' => 2, 'csp_nonce' => null, 'templateInherits' => '', 'params' => object(Registry), 'file' => 'error.php'))
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Error/Renderer/HtmlRenderer.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Error/Renderer/HtmlRenderer.php#L70)(line 70)
HtmlRenderer->render(object(mysqli_sql_exception))
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Exception/ExceptionHandler.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Exception/ExceptionHandler.php#L136)(line 136)
ExceptionHandler::render(object(mysqli_sql_exception))
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Exception/ExceptionHandler.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Exception/ExceptionHandler.php#L73)(line 73)
ExceptionHandler::handleException(object(mysqli_sql_exception))
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Application/CMSApplication.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/libraries/src/Application/CMSApplication.php#L336)(line 336)
CMSApplication->execute()
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/administrator/includes/app.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/administrator/includes/app.php#L58)(line 58)
require_once('/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/administrator/includes/app.php')
in [/data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/administrator/index.php ](file:///data/5/9/59869c13-0263-4efa-bf71-568708af0344/petben.cz/sub/transition/administrator/index.php#L32)(line 32)

**Comment by djfermin** [comment]
> Could you post the content of the log file from the update, administrator/logs/joomla_update.php? It seems the update was not complete so the database updates were not complete.

sorry.
I don't feel it. delete everything and install a backup.

**Comment by brianteeman** [comment]
Based on the last comment there is no point in keeping this issue open (my 2c)
