### ISSUE TITLE
PHP 8.2 Legacy Error in WebClient.php not solved by #42830

### ISSUE THREAD

**Issue by ssabatini** [joomla/joomla-cms#43334]
### Steps to reproduce the issue

View PHP Error log for Joomla site with PHP 8.2.X.
Look for warnings "stripos(): Passing null to parameter https://github.com/joomla/joomla-cms/pull/1 ($haystack) of type string is deprecated ..."

### Expected result

No warnings regarding "stripos(): Passing null to parameter https://github.com/joomla/joomla-cms/pull/1 ($haystack) of type string is deprecated ..." anymore.

### Actual result

#42830 has fixed this warning only in the function `detectBrowser()`, but the same warning (with the same reason) is produced by the functions `detectEngine()` and `detectPlatform()`.

Additionally, the function `detectRobot()` does as well not test if the user agent is `null`.

**Comment by alikon** [comment]
please check https://github.com/joomla-framework/application/pull/124

**Comment by ssabatini** [comment]
@alikon The fix looks good. The first fix with issue #42830 should be unnecessary now; the `if ($userAgent !== null)` in the method `detectBrowser` can be removed.

**Comment by Quy** [comment]
Please test https://github.com/joomla-framework/application/pull/131

**Comment by ssabatini** [comment]
The fix [131](https://github.com/joomla-framework/application/pull/131) does not solve null $userAgent in `detectEngine($userAgent)` and `detectPlatform($userAgent)`. I would propose to use the solution provided in [124](https://github.com/joomla-framework/application/pull/124).

**Comment by richard67** [comment]
Closing as having a pull request. Please test #44585 . Thanks in advance.
