### ISSUE TITLE
[J4][J5] Sub categories of homepage get the slug of the home menu item

### ISSUE THREAD

**Issue by StefanSTS** [joomla/joomla-cms#43346]
### Steps to reproduce the issue
__First test__

- Add category *blog* and sub category *sub-blog*.
- Add articles in each category e.g. with alias blog-article-01, sub-blog-article-01
- Add menu item for category blog *blog*. Set to default page to make it the home page.

__Second test__
- Add menu item for the sub category below category blog.

### Expected result
__Both tests__
- URLs for Home
example.com/
- URL for blog article blog-article-01
example.com/blog-article-01
- URL for sub blog article sub-blog-article-01
example.com/sub-blog/sub-blog-article-01

### Actual result
__First Test__ as expected
example.com/
example.com/blog-article-01
example.com/sub-blog/sub-blog-article-01

__Second Test__ 
example.com/
example.com/blog-article-01
example.com/blog/sub-blog/sub-blog-article-01

### Additional comments

example.com/sub-blog/sub-blog-article-01
vs.
example.com/blog/sub-blog/sub-blog-article-01

This happens if you add a menu item for the sub category.
The links should be the same in both tests.

__Two URLs - same page__
example.com/ and
example.com/blog
show the same content. The alias blog should never appear anywhere.

**Comment by Hackwar** [comment]
I'm sorry, but this is expected behavior and has been like this since Joomla 1.5. You are creating a sublevel of the home menu item and we are only removing the alias for the actual home menu item, not for any other menu items. This is not a bug.
