### ISSUE TITLE
Media Manager is wrongly initialised by TinyMCE when accessed from a front-end submenu item

### ISSUE THREAD

**Issue by NicolasDerumigny** [joomla/joomla-cms#43344]
### Steps to reproduce the issue
Edit an article in a submenu, e.g. `menu/article`. Try to access "media" in "CMS Content" using TinyMCE.

### Expected result
The media manager starts.

### Actual result
The media manager window loads `/menu/index.php?option=com_media&view=media&tmpl=component&e_name=jform_articletext&asset=675&mediatypes=0,1,2,3&author=36` and displays "File not found. "

### System information (as much as possible)
Joomla 5.1.0 on Nginx 1.22.1, PHP 8.2.18.

### Additional comments
Patchable by adding a "/" before the URL at https://github.com/joomla/joomla-cms/blob/5.1-dev/plugins/editors-xtd/image/src/Extension/Image.php#L187. I can make an MR but I am not familiar with Joomla's internal. It was working fine on 4.4, not sure what caused the issue.

**Comment by brianteeman** [comment]
Do you have an .htaccess file in use?
If you do please can you post the contents

**Comment by brianteeman** [comment]
I was thinking aloud for possible changes

**Comment by brianteeman** [comment]
Bug Confirmed

**Comment by brianteeman** [comment]
Please test #43373

**Comment by Fedik** [comment]
Does it also broken with "Codemiror" or "Editor none"?

**Comment by NicolasDerumigny** [comment]
I do not think it is possible to open the media manager from these editors, is it?

**Comment by brianteeman** [comment]
> Does it also broken with "Codemiror" or "Editor none"?

testing



> I do not think it is possible to open the media manager from these editors, is it?

Yes they appear as buttons below the editor

**Comment by brianteeman** [comment]
tested with editor none - same problem
tested my pr with editor none - fixed

**Comment by Fedik** [comment]
Hm, how is your menu set up? 
I have:
```
- Test Article => Article view
- - Test article 2 => Article2 view
```
And when I trying edit any of it, I still able to open media manager without error.

**Comment by NicolasDerumigny** [comment]
Mine is:
```
- Category Blog #1
- - Category Blog #2
```
And I try to edit an article displayed on the category blog#2, i.e. `blog1/blog2/alias`.

**Comment by Fedik** [comment]
Thanks, I got it now

**Comment by Fedik** [comment]
@brianteeman PR is good, please test

**Comment by Fedik** [comment]
Pleae test another one https://github.com/joomla/joomla-cms/pull/43376
