### ISSUE TITLE
Smart Search Indexer Error

### ISSUE THREAD

**Issue by philmarty** [joomla/joomla-cms#43348]
Hello,

I tried to index the smart search of my website using CLI but I get the following error: 

php -d memory_limit=512M joomla.php finder:index
Finder Indexer
==========================

 Starting Indexer
 Setting up Smart Search plugins
 Setup 5986 items in 0.025 seconds.
  * Processed batch 1 in 3.199 seconds.
  * Pausing processing for 1 seconds &hellip;
  * Continuing processing of batch &hellip;
  * Processed batch 2 in 3.486 seconds.
  * Pausing processing for 1 seconds &hellip;
  * Continuing processing of batch &hellip;
  * Processed batch 3 in 2.79 seconds.
  * Pausing processing for 1 seconds &hellip;
  * Continuing processing of batch &hellip;
  * Processed batch 4 in 5.246 seconds.
  * Pausing processing for 1 seconds &hellip;
  * Continuing processing of batch &hellip;
  * Processed batch 5 in 3.771 seconds.
  * Pausing processing for 1 seconds &hellip;
  * Continuing processing of batch &hellip;
  * Processed batch 6 in 3.436 seconds.
  * Pausing processing for 1 seconds &hellip;
  * Continuing processing of batch &hellip;
  * Processed batch 7 in 3.137 seconds.
  * Pausing processing for 1 seconds &hellip;
  * Continuing processing of batch &hellip;

**In Behavior.php line 49:**                                                                                     
  **Call to undefined method Joomla\CMS\Application\ConsoleApplication::getDocument()** 
                                                                                     

finder:index [--minproctime MINPROCTIME] [--pause PAUSE] [--divisor DIVISOR] [--live-site [LIVE-SITE]] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [--] <command> [<purge>]

### System information (as much as possible)
Joomla 4.4.3
PHP 8.1

### Additional comments
I tired also through the backend and I get that error :
Smart Search Indexer
An Error Has Occurred
syntax error, unexpected token "<"

Where is the problem, please?
Best regards

**Comment by Hackwar** [comment]
This is a problem of either a third party finder plugin or of a third party content plugin which doesn't behave properly in the Smart Search context.

**Comment by philmarty** [comment]
Ok, but how can I find the plugin causing the crash?

**Comment by Hackwar** [comment]
For others who stumble upon this: If you have a finder plugin which is acting up, you can simply open the browser console, then run the indexing process and look at the last ajax request which was run. In the data, you see which plugins were run and which still have stuff to process. The next plugin with 0 processed entries is the one creating your issues.
