### ISSUE TITLE
[5.1] TinyMCE: can't insert media in article 

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#43365]
### Steps to reproduce the issue
In an article try to insert a PDF file (CMS Content -> Media)

### Expected result
You can insert a link to or you get an iframe with the PDF

### Actual result
Javascript error, insert button doesn't work for download PDF. Iframe seems to be inserted, after saving the article, the iframe dissapears

![grafik](https://github.com/joomla/joomla-cms/assets/9153168/765b2056-5592-4af6-bcb2-d88c4d0d6bed)

### System information (as much as possible)
Joomla 5.1
PHP 8.1.28 / 8.2.18
MySQL 8.0.35  / MariaDB 10.6.15

**Comment by brianteeman** [comment]
Confirm the error with the download
No problem with the insert, it produces an object which is saved without error
![image](https://github.com/joomla/joomla-cms/assets/1296369/a43ce4bb-16f4-4493-b208-aaa6d962a292)

**Comment by Fedik** [comment]
This need to be relaced to `editorInst.getSelection()` https://github.com/joomla/joomla-cms/blob/fc51f46b14148d9558d896a379b6682ee9bd430a/build/media_source/system/js/fields/joomla-media-select.w-c.es6.js#L243

I will make PR, later

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/43374

**Comment by Quy** [comment]
Please test PR #43716. Thanks.
