### ISSUE TITLE
CLI core:update returns exit code 1

### ISSUE THREAD

**Issue by 35grain** [joomla/joomla-cms#43366]
### Steps to reproduce the issue
Run the `core:update` command.

### Expected result
If everything goes as intended, exit code 0 is expected.

### Actual result
Exit code 1 is returned.

### System information (as much as possible)
Joomla 5.x. PHP 8.2.17.

### Additional comments
This currently makes automation tasks fail, as anything other than 0 is considered as a failure. Is this intended behavior?

**Comment by brianteeman** [comment]
What exact version are you updating from

**Comment by 35grain** [comment]
Initially I updated from 5.0.2 but the same happens with 5.1.

**Comment by Hackwar** [comment]
What is your complete output of the command? It should display `Joomla core updated successfully!` as last line in the output and return a 0 exit code. That is the code since 4.4 actually. Are you absolutely sure that the update was 100% successfull?

**Comment by alikon** [comment]
if you already have the latest Joomla! version then the exit code is 1

**Comment by 35grain** [comment]
Unfortunately I don't have the output for the update from 5.0.2 to 5.1, however everything seems operational so it is difficult to tell if something went wrong. But 

> if you already have the latest Joomla! version then the exit code is 1

is more or less what I was hoping to figure out whether or not this is the intended behavior. Will try to work around this then. Thanks!
