### ISSUE TITLE
Consistency of "unpublished" -icon colours

### ISSUE THREAD

**Issue by Engholm** [joomla/joomla-cms#43375]
### Steps to reproduce the issue
Since J4 the "unpublished" -status of articles are grey / muted colored. Within the article overview they are cloured grey. By choosing an associated article, you'll find red coloured unpublished-buttons.

### Expected result
UnpublishedIcons have a global defined same colour

### Actual result
Different colours (grey/red) for unpublished-icon

### System information (as much as possible)
Joomla 4.x / 5.x Backend

### Additional comments
I would like to see better consistency. And it wouldn't hurt the Joomla 4/5 backend to get a little more colour again. So red should be the visual approach

**Comment by brianteeman** [comment]
Please post some screenshots

**Comment by Engholm** [comment]
just figured out, the uploader on issues.joomla.org doesn't work (tried Firefox / Chrome / Win11)

![deactivated_status_1](https://github.com/joomla/joomla-cms/assets/1927499/7249ef2a-73d4-4362-a4c9-99b882068424)
![deactivated_status_2](https://github.com/joomla/joomla-cms/assets/1927499/d9cc4620-ac68-4e39-9750-f893b719452a)

**Comment by brianteeman** [comment]
thank you

**Comment by mabdelaziz77** [comment]
@chmst Please check this fix #43424

**Comment by richard67** [comment]
Closing as having a pull request. Please test #43424 . Thanks in advance.
