### ISSUE TITLE
Module class is not applied to custom module

### ISSUE THREAD

**Issue by luX0r-reload** [joomla/joomla-cms#43372]
### Steps to reproduce the issue
Create a Custom module and set a Module class.

### Expected result
Module class appears in front-end.

### Actual result
Module class doesn't appears in front-end.

### System information (as much as possible)
Ubuntu 22.04.4
PHP 8.1.2
MariaDB 10.6.16
Apache/2.4.52
Joomla! 5.1.0 Stable [ Kudumisha ]
Joomla Backward Compatibility Plugin Disabled

### Additional comments
Template: just a Cassiopeia child template, but the issue is on the default Cassiopeia too.

**Comment by RickR2H** [comment]
In what position was the module added? Did you try to change the module chrome style? When a position has a style of "none" in the template, the styles are not applied. Try setting it to "card" or "noCard".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43372">issues.joomla.org/tracker/joomla-cms/43372</a>.</sub>

**Comment by luX0r-reload** [comment]
Menu position. Module style is on Inherited. Changing style not affect the result.
