### ISSUE TITLE
Global config ignored

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#43394]
### Steps to reproduce the issue
Go to global config and set debug to "on"
hit save
set to off, 
hit save

### Expected result
debug follows button settings, & configuration.php is changed.

### Actual result
globacl config is completely ignored and debug is stuck on.

### System information (as much as possible)
https://kuj5.klasusers.com/
[systeminfo-2024-04-27T18_02_36+00_00.txt](https://github.com/joomla/joomla-cms/files/15139205/systeminfo-2024-04-27T18_02_36%2B00_00.txt)

**Comment by brianteeman** [comment]
AS ALWAYS - unable to replicate

**Comment by chmst** [comment]
J 5.1 ? 
I cannot replicate this issue, in my installation the settings are as expected. Online and on localhost.

**Comment by N6REJ** [comment]
right, but what I'm saying is changing it in the backend does nothing.. it's only if you edit the confitg file maunally that it does anytthung BUT, the debug still shows.
![image](https://github.com/joomla/joomla-cms/assets/1850089/282990c6-82d4-4c93-bb4e-705740a27cbd)
Check the link I gave.
@brianteeman your snide remark is unnecessary and unhelpful

**Comment by N6REJ** [comment]
> J 5.1 ? I cannot replicate this issue, in my installation the settings are as expected. Online and on localhost.

yes mam

**Comment by N6REJ** [comment]
another proof of that is that it says "display_offline_message" to true but clearly its ignored

**Comment by N6REJ** [comment]
> J 5.1 ? I cannot replicate this issue, in my installation the settings are as expected. Online and on localhost.

if you set debug to on and then hit save does it revert to off?  Ours does

**Comment by brianteeman** [comment]
seriously. Come on Bear - you've been around long enough now to surely realise that that setting is about the message which would be displayed WHEN the site is off

![image](https://github.com/joomla/joomla-cms/assets/1296369/fb9fdecd-8223-4118-8510-58f9efc10f90)

**Comment by N6REJ** [comment]
before hitting save
![image](https://github.com/joomla/joomla-cms/assets/1850089/37623534-4d58-4de9-b6c2-23a84c242f8e)

after save
![image](https://github.com/joomla/joomla-cms/assets/1850089/88462402-95ab-40cb-8d90-88c629b22207)
![image](https://github.com/joomla/joomla-cms/assets/1850089/dc17fb0e-341b-4ee0-8224-2a44165f99f9)

**Comment by brianteeman** [comment]
Your porblem is simple. Lets approach this logicaly.

Changes made by editing the configuration.php file work
Changes made using the global config settings in Joomla do not work

What can we conclude from this. Two possibilities
1. There is a bug in joomla preventing changes in global config 
2. There is something specific to your system preventing Joomla from saving the changes in global config.

We can rule out option 1 (until someone else can repeat it)

So lets look closer at option 2 - What can we test

When you press save in joomla after making a change does it actually say anything. It should be
![image](https://github.com/joomla/joomla-cms/assets/1296369/0494b9d5-c794-44e4-9c40-04a612c7edd8)

If it says saved but nothing has been saved - please post a screenshot to prove that Joomla is telling lies

**Comment by Fedik** [comment]
Maybe you have PHP "opcache" issue, kind of. 
That can explain why your config does not changes immediately.

Joomla trying to do `opcache_invalidate` when it is available.

**Comment by AlisonAMG** [comment]
Hi Brian Per your request. 
https://app.screencastify.com/v3/watch/V8XxhOtnvNra8ex5xfJl

**Comment by N6REJ** [comment]
just to add to what @AlisonAMG said, we've already reinstaleld core files

**Comment by AlisonAMG** [comment]
Hi @Fedik Not using OPCache but am using Cache Cleaner by RegLabs. It is set to clear on save but have also been using the clear button. 

Thanks to anyone helping out.

**Comment by brianteeman** [comment]
reinstalling core files almost NEVER solves anyything

Your video clearly shows that when you try to save it does not as there is no confirmation message

What do you think that means?

It can only mean one thing - Joomla was unable to write to the configuration.php file

This is a server config issue

**Comment by AlisonAMG** [comment]
Thanks Brian - Will look into that.

**Comment by brianteeman** [comment]
you can easily verify that assertion.

take a backup of the site and install it on a known good server. Happy to do that on my server

**Comment by AlisonAMG** [comment]
This is a known good server. The live J3 site is rolling on it. 

If you would like to give it a spin the BU is 1.1 GB

**Comment by brianteeman** [comment]
you can backit up excluding the images/ and that should make it a lot smaller. Send it to me by whatever method is best for you

**Comment by AlisonAMG** [comment]
Sent the link to you via MM Brian. Obv at your convenience.

**Comment by brianteeman** [comment]
As expected. Installed on a known good server provided to me by https://www.scalahosting.com/joomla-vps.html and it works perfectly.

Not a Joomla bug so can be closed. (Will take a further look to see what caused the problem but its not a core bug)

**Comment by AlisonAMG** [comment]
Many thanks Brian for your assistance.

**Comment by brianteeman** [comment]
For reference the problem was a php config issue.

The max_input_vars was 1000 which would normally be just enough but as this site had a large number of user groups and access levels the limit was reached when saving config and eventually would be reached when aving modules and menu items

Unfortunately this error doesnt usually make any visual display - its just in your server logs.

The clue is that it would appear to save BUT no Joomla Save message will be displayed.

We did discuss in the past some form of notification when this happens but I forget the outcome

**Comment by brianteeman** [comment]
> We did discuss in the past some form of notification when this happens but I forget the outcome

Found it
https://github.com/joomla/joomla-cms/pull/7456

This would have identified the problem immediately

**Comment by brianteeman** [comment]
Can someone close this please. It was not a joomla bug and it has been resolved
