### ISSUE TITLE
Pagination not working on page form menu item with similar tags

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#4339]
#### Steps to reproduce the issue
- Create a number of articles (more then 5) and give them the same tag.
- Create a menu item 'Tagged Items', show pagination on, Item selection option -> Max items 5.
- Click on the menu item in the frontend
- Click on page 2, or 'next' in the pagination.

#### Expected result

The next page should be shown.

#### Actual result

The current (start) page is shown.

#### System information (as much as possible)

Joomla 3.3.4.
Also tried this with the Beez3 template.

#### Additional comments
Related to this?
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=30453

**Comment by brianteeman** [comment]
I can no longer recreate this issue. I am assuming it has been resolved elsewhere and am closing this. If you feel this is still an issue with the current release of Joomla it can always be re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4339">issues.joomla.org/joomla-cms/4339</a>.</sub>

**Comment by Disaron** [comment]
Joomla! 3.4.5
Users manager.
Apply filter (by groups for example).
Pagination not working.

I see that state list.start can be empty after calling JModelList::populateState() method even I set this state in populateState to not null value.
