### ISSUE TITLE
[5.2] Usability: One Articles Module to Rule Them All

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#43404]
In Joomla 5.2 we would like to have **one new “Site Articles” module** with parameters to replace all individual Site Article modules in the future:
- Articles - Archived
- Articles - Categories
- Articles - Category
- Articles - Latest
- Articles - Most Read
- Articles - Newsflash
- Articles - Related

In Joomla 5.2 we just want to have this module as extra module. 
From Joomla 6 on, we could consider to stop shipping the old modules with new installations,
and automatically convert them to the new module. 

The new module should allow multiple category selection using the "fancy select" class.

@webgras compared the functionality of the old Articles modules in a spreadsheet:
https://docs.google.com/spreadsheets/d/13893BpWLdTBL1Wpe3PH3O6G7zQOFE_8oiqMBeh95f6M/edit#gid=0

**Comment by brianteeman** [comment]
While I support the idea of a NEW module the idea that there could ever be a migration/conversion would be almost impossible to achieve. You only need to read the JCM etc to see some of the creative ways that these modules have been used with layouts and overrides. Thinking of just a few of my own I cant see anyway that they could be migrated/converted

**Comment by HLeithner** [comment]
I would suggest not to write migration code and it's not really needed, we just don't ship mod_articles_* in the future (maybe directly starting with 5.2) and have a good documentation how the migration could be done manually.

So you don't need to implement all features the old modules have and which maybe doesn't make sense anymore and on the other side you can make new features not having a b/c issue.

**Comment by brianteeman** [comment]
Is this the sort of thing you are looking for

![image](https://github.com/joomla/joomla-cms/assets/1296369/a18cf23c-582b-45c3-a5e8-dd89582919d7)

![image](https://github.com/joomla/joomla-cms/assets/1296369/faf66b34-c36b-4583-9f8e-87f77fb2dec1)

![image](https://github.com/joomla/joomla-cms/assets/1296369/ee9e095e-31ac-4b13-a2f0-56ef910abf21)

**Comment by drmenzelit** [comment]
Yes

**Comment by brianteeman** [comment]
Should be ready for review by the end of the week

**Comment by brianteeman** [comment]
Please see #43610

**Comment by richard67** [comment]
Closing as having a pull request. Please test #43738 . Thanks in advance.
