### ISSUE TITLE
TinyMce Editor iframe and general

### ISSUE THREAD

**Issue by niosme** [joomla/joomla-cms#43407]
### Steps to reproduce the issue

Put this into text editor code

<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d24578.379315757487!2d22.4165888!3d39.64302065!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sel!2sgr!4v1714479981262!5m2!1sel!2sgr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

### Expected result

Show map iframe

### Actual result

Puts sandbox="" and prevents to load the iframe and becomes

<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m12!1m3!1d24578.379315757487!2d22.4165888!3d39.64302065!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!5e0!3m2!1sel!2sgr!4v1714479981262!5m2!1sel!2sgr" width="600" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade" sandbox=""></iframe>

Also in sandbox we cannot add values or edit it so allow something to work. Always remains empty so restricts everything.
I cannot figure out how to change it and allow iframes work somehow.

### System information (as much as possible)
Joomla 5.0.1
Php 8.2

### Additional comments
i setted it as use joomla filters and joomla filters setted to none. Shouldn't this be initialized somehow so no changes happened to any value?
Tiny mce at final keeps editing text and doennt allow even a custom structure or something like that:
```

<a>
   <img/>
  <div>
     <div></div>
     <div></div>
  </div>
</a>
```

**Comment by brianteeman** [comment]
This is intended behaviour and implements the security hardening in tniymce

https://youtu.be/OGZ06TCdJHc?si=Z0sSHlVaV-OP0wRi&t=64

**Comment by niosme** [comment]
Followed your video and It does the same behaviour... Puts the sandbox inside!

**Comment by brianteeman** [comment]
yes it is supposed to put the sandbox there. As I said this is a security change from tinymce https://www.tiny.cloud/docs/tinymce/latest/7.0-release-notes/#security-fixes

**Comment by zeroalphagit** [comment]
> This is intended behaviour and implements the security hardening in tniymce
> 
> https://youtu.be/OGZ06TCdJHc?si=Z0sSHlVaV-OP0wRi&t=64

This doesn't work for me either. **Joomla 5.1.0** 

I understand this is done for security but I can't find any solution to allow me to embed youtube videos with iframe which makes this a complete annoying bug

**Comment by macstalker** [comment]
Workaround:

Install TinyMCE Configuration Modifier plugin https://github.com/nikosdion/plg_system_tinymod
Then add:
{
    "sandbox_iframes": false
}
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43407">issues.joomla.org/tracker/joomla-cms/43407</a>.</sub>

**Comment by woluweb** [comment]
> Workaround:
> 
> Install TinyMCE Configuration Modifier plugin https://github.com/nikosdion/plg_system_tinymod Then add: { "sandbox_iframes": false }
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/43407](https://issues.joomla.org/tracker/joomla-cms/43407).

I do confirm: with this tinymod plugin you can "tweak" TinyMCE's default configuration.
But in my case, instead of disabling sandbox altogether (it was introduced for security reasons) with
{ "sandbox_iframes": false }
I have given a try to the following configuration suggested on Mattermost by @RickR2H and I do confirm that it does work (even if we don't mention "PDF" nor "/images" nor the domain name of the concerned website)

```
{
    "selector": "textarea",
    "sandbox_iframes": "true",
    "sandbox_iframes_exclusions": [
        "youtube.com",
        "youtu.be",
        "vimeo.com",
        "player.vimeo.com",
        "dailymotion.com",
        "embed.music.apple.com",
        "open.spotify.com",
        "giphy.com",
        "dai.ly",
        "codepen.io"
    ]
}
```

**Comment by brianteeman** [comment]
it could well be that I misunderstood the advice from tinymce and applied the security fix incorrectly

**Comment by woluweb** [comment]
> it could well be that I misunderstood the advice from tinymce and applied the security fix incorrectly

I am happy that we have a workaround for this, but it is indeed weird that 
- on the one hand Joomla allow to embed a PDF via the official Joomla Media Manager
- but at the same time that Joomla would block an embedded PDF when using the official Joomla Wysiwyg Editor
:)

So I guess that
- we should at least allow embedding PDFs stored locally on the website
- and also maybe offer a way to configure those exclusions (the default list is nice for a start, but of course each website has its own needs)

**Comment by Quy** [comment]
Please test PR #43716. Thanks.

**Comment by zeroalphagit** [comment]
> >Workaround:
> Install TinyMCE Configuration Modifier plugin https://github.com/nikosdion/plg_system_tinymod

**Confirm this works great on Joomla 5.1.1**

Just a tip to install this plugin you have to download the .zip file but extract the plg_system_tinymod-main\plugins\system\tinymod folder. Then make a new zip file of that tinymod folder and upload & install to joomla
> 
> ```
> {
>     "selector": "textarea",
>     "sandbox_iframes": "true",
>     "sandbox_iframes_exclusions": [
>         "youtube.com",
>         "youtu.be",
>         "vimeo.com",
>         "player.vimeo.com",
>         "dailymotion.com",
>         "embed.music.apple.com",
>         "open.spotify.com",
>         "giphy.com",
>         "dai.ly",
>         "codepen.io"
>     ]
> }
> ```

**Comment by micker** [comment]
hello i update my site in 5.1.2 but problem still here ... all my youtube video are ko, we realy need to add a plugin and this configuration ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43407">issues.joomla.org/tracker/joomla-cms/43407</a>.</sub>

**Comment by bembelimen** [comment]
Disable in the TinyMCE plugin the following option:
![grafik](https://github.com/joomla/joomla-cms/assets/1229869/cbabf4a6-b7b1-4983-a0bb-42b4f1cc1e67)

**Comment by micker** [comment]
ok thanks

**Comment by alexandreelise** [comment]
> > Workaround:
> > Install TinyMCE Configuration Modifier plugin https://github.com/nikosdion/plg_system_tinymod Then add: { "sandbox_iframes": false }
> > This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/43407](https://issues.joomla.org/tracker/joomla-cms/43407).
> 
> Txs for the suggestion [@macstalker](https://github.com/macstalker) ! I do confirm: with this tinymod plugin you can "tweak" TinyMCE's default configuration. But in my case, instead of disabling sandbox altogether (it was introduced for security reasons) with `{ "sandbox_iframes": false }` I have given a try to the following configuration suggested on Mattermost by [@RickR2H](https://github.com/RickR2H) and I do confirm that it does work (even if we don't mention "PDF" nor "/images" nor the domain name of the concerned website)
> 
> ```
> {
>     "selector": "textarea",
>     "sandbox_iframes": "true",
>     "sandbox_iframes_exclusions": [
>         "youtube.com",
>         "youtu.be",
>         "vimeo.com",
>         "player.vimeo.com",
>         "dailymotion.com",
>         "embed.music.apple.com",
>         "open.spotify.com",
>         "giphy.com",
>         "dai.ly",
>         "codepen.io"
>     ]
> }
> ```

Hi @woluweb, thanks for suggesting this. I would like to add `gist.github.com` to this list since it's quite popular too. But I understand that everyone would like to add it's favourite tool and obviously we can't add everything under the sun in this list. People will have to make their own list for their own use cases.

> 
> ```
> {
>     "selector": "textarea",
>     "sandbox_iframes": "true",
>     "sandbox_iframes_exclusions": [
>         "youtube.com",
>         "youtu.be",
>         "vimeo.com",
>         "player.vimeo.com",
>         "dailymotion.com",
>         "embed.music.apple.com",
>         "open.spotify.com",
>         "giphy.com",
>         "dai.ly",
>         "codepen.io",
>         "gist.github.com"
>     ]
> }
> ```
