### ISSUE TITLE
New to Joomla! Forum link need new href

### ISSUE THREAD

**Issue by sinahaghparast** [joomla/joomla-cms#43413]
### Steps to reproduce the issue
After installing new Joomla 5.1.0, in Postinstall component (/administrator/index.php?option=com_postinstall address), the first message is "Welcome to Joomla!", in this message "New to Joomla! Forum" link is exists. 

current href = https://forum.joomla.org/viewforum.php?f=808 (General Questions/New to Joomla! 4.x)
correct href = https://forum.joomla.org/viewforum.php?f=834 (General Questions/New to Joomla! 5.x)

**Comment by alikon** [comment]
please test #43414
