### ISSUE TITLE
The schemaorg entry is deleted if no data has been received from the form

### ISSUE THREAD

**Issue by MSGroupFM** [joomla/joomla-cms#43422]
### Steps to reproduce the issue

When saving materials in Joomla 5.1 not through the standard form of the control panel (for example, YOOtheme Pro), the schemaorg is deleted.

### Expected result

The schemaorg plugin should ignore form submission without a schema.

### Actual result

Schemaorg plugin removes a record from a table _schemaorg

### System information (as much as possible)

Joomla 5.1

### Additional comments

**Comment by fgsw** [comment]
> (…) not through the standard form of the control panel (for example, YOOtheme Pro), (…)

So this is a issue of Yootheme?

**Comment by alex-revo** [comment]
This issue fixed with Yootheme Pro 4.4.12+

**Comment by brianteeman** [comment]
Please close this as it is not and was not a joomla bug.
