### ISSUE TITLE
[5.2.0] Access denied in statistic plugin

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#43423]
### Steps to reproduce the issue
Fresh installation on localhost,  win 11, xampp, php 8.2.
Answer "yes I'll help Joomla" on statistic plugin. 

Then: 
https://github.com/joomla/joomla-cms/blob/5.2-dev/plugins/system/stats/src/Extension/Stats.php#L408
gives an empty result and the message 

Exception: Access Denied

### Expected result
No error message

### Actual result
![grafik](https://github.com/joomla/joomla-cms/assets/1035262/981f73d4-edec-438a-aa6f-d5be6b7ced49)

### Additional comments

**Comment by HLeithner** [comment]
haha, that's a really funny or better useless function...
No idea why we would like to "check" if it's a "xmlhttprequest" request, should this be a protection against automated scripts? clicking on a link per error? and if why?

beside that the plugin or parts of it should be converted to a scheduled task.

**Comment by brianteeman** [comment]
I "suspect" that this is because 5.2 is not yet a recorded version on the stats server and you should create a pr to update that their and this can be closed.

https://github.com/joomla/statistics-server/blob/c3f12a0cd304075b55e4dd5f2bafa5c161d2da14/versions/joomla.json#L1

**Comment by HLeithner** [comment]
added it, does it help? (also added it to the documentation....)

**Comment by chmst** [comment]
Yes, it helps! Thank you.

**Comment by brianteeman** [comment]
glad it worked
