### ISSUE TITLE
Administrator error in StyleModel.php

### ISSUE THREAD

**Issue by rikaryoo** [joomla/joomla-cms#43421]
### Steps to reproduce the issue

When clicking on the "Options button" at the top right of the template, clicking save redirects to this link:

my domain /administrator/index.php?option=com_config

which generates an "Internal Server Error"

several extensions affected, including Easy Job Manager and JCE

### Expected result

This message indicates a PHP error related to the StyleModel.php file in
your site. Specifically, it looks like the code is trying to access a
property called "parent" on something that is not actually an object, but
instead of an array. This can happen for a number of reasons, such as lack of
unexpected data or data structures.

### Actual result

Works with limitations and redirects without saving changes to Internet Server Error

### System information (as much as possible)

Joomla 5.1
PHP 8.2
Mysql 8

Easy Jobs Manager 5.3.0
JCE Editor 2.9.63

### Additional comments

I'm not a programmer, but I identified this problem when I found myself unable to solve a problem that was affecting my websites, after upgrading from version 5.0.3 to 5.1.

see attached images:

![error-1](https://github.com/joomla/joomla-cms/assets/139914747/850fa690-56e7-4000-be66-8081dfe521ef)
![error-2](https://github.com/joomla/joomla-cms/assets/139914747/35a652f7-1942-4376-b059-1d2a3ebe1ea6)
![error-3](https://github.com/joomla/joomla-cms/assets/139914747/98025360-ad86-4e2f-a3d2-ef584a2e3634)
![error-4](https://github.com/joomla/joomla-cms/assets/139914747/f6097c46-9064-4173-a372-20d1aa7f7814)

**Comment by exlemor** [comment]
Hi @rikaryoo, (I'm NO expert but from what I know/understand) this does not appear to be a Joomla issue but an Easy Job Manager issue, have you reached out to JoomBoost ?

from what I can compare to other extensions, they are not generating the correct link when clicking on Options:

https://www.domainname.com/administrator/index.php?option=com_config&view=component&component=com_NAMEOFCOMPONENT&path=&return=aHR0cHM6Ly93d3cuanVubml0aS5jb20vYWRtaW5pc3RyYXRvci9pbmRleC5waHA%2Fb3B0aW9uPWNvbV9vc21hcA%3D%3D

(if yours is cut off at https://www.domainname.com/administrator/index.php?option=com_config as you can see, there is quite a bit missing)

Hope that helps.

**Comment by rikaryoo** [comment]
@exlemor thank you for your feedback, my understanding of support was different from yours, thank you for clarifying.

I will contact support again. Which made me post here that the error also happened in JCE, which in J5.0.3 worked fine.

If in doubt, I'll close the tip and look for an answer.

Thank you for your help and your time!!!

**Comment by chmst** [comment]
Thanks.  I close this for now. Also JCE is an extension and not part of the core.
