### ISSUE TITLE
Missing options in RSS feed module

### ISSUE THREAD

**Issue by SoundHunter1** [joomla/joomla-cms#43428]
### Is your feature request related to a problem? Please describe.
We load RSS feed content into our website, this works good with the buildin Joomla 4 feed module.
But we like to have a bit more control about it.

### Describe the solution you'd like
In our case we miss the options to disable the `<title>` and `<link>` from the RSS feed, we only want to display the discription part.
Also an option to disable `<li>` (list element) which has been hardcoded in the module on line 89.
What we do now is disabling line 89 to 102 in default.php (https://github.com/joomla/joomla-cms/blob/4.4-dev/modules/mod_feed/tmpl/default.php) what does the trick. But it is way better to have the options default build in so overwriting Joomla updates are no problem anymore.

**Comment by brianteeman** [comment]
You do not need to edit that file!! That is why you can create a template override. https://docs.joomla.org/J4.x:Template_Overrides

**Comment by brianteeman** [comment]
This can be closed

**Comment by SoundHunter1** [comment]
> You do not need to edit that file!! That is why you can create a template override. https://docs.joomla.org/J4.x:Template_Overrides

Of course, totally overseen! Thank you for your quick reply I gonna create the override.
Have a good day!
