### ISSUE TITLE
Define custom value for the total of page to display inside the pagination

### ISSUE THREAD

**Issue by carlitorweb** [joomla/joomla-cms#43447]
### Is your feature request related to a problem? Please describe.

The total of page to display is set _hardcode_ inside the Pagination class
https://github.com/joomla/joomla-cms/blob/e11bd13a7e60b40bac729472d20675164ed30bbe/libraries/src/Pagination/Pagination.php#L157

### Describe the solution you'd like
Can be one or both:

- Define a global configuration param
- Define a param in the menu items where pagination is set

**Comment by brianteeman** [comment]
What is the use case for changing this

**Comment by carlitorweb** [comment]
Allow the users define the amount of page they want list in their pagination layout, depending of they template design. Right now if 10 is to big for your layout, you need change the layout trought a override and hidde this page list, leaving only the previous and next buttons.
