### ISSUE TITLE
[5.1] UI issue on MFA in Dark Mode

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#43448]
### Steps to reproduce the issue

1. Prepare a J5.1 website with a backend user configured to use multiple MFA options (i.e. Passkey as default, TOTP, Backup Codes).
2. Switch backend to Dark Mode.
3. Logout and login again with the backend user from 1. by entering userid and password.
4. On screen “Multifactor Authentication” click “Select a different method”

### Expected result
Captions on the following screen are clearly legible.

### Actual result
Captions on the following screen are not legible:

![grafik](https://github.com/joomla/joomla-cms/assets/7933215/c47f5f0c-5543-41b9-816a-66f47290a04b)

### System information (as much as possible)
J5.1.0 (local via Laragon)
Apache 2.4.59
PHP 8.3.8
MySQL 8.0.36

**Comment by brianteeman** [comment]
The work done in #41799 was not complete and needs to be repeated for administrator\components\com_users\tmpl\captive\select.php

**Comment by coolcat-creations** [comment]
I basically repeated what @brianteeman said ;)

**Comment by wilsonge** [comment]
I am getting married tomorrow so unlikely to do this any time soon. Sorry!

**Comment by coolcat-creations** [comment]
Congrats @wilsonge 😍

**Comment by dautrich** [comment]
@wilsonge  All the best wishes for your great event!

**Comment by richard67** [comment]
Closing as having a pull request. Please test #44209 . Thanks in advance.
