### ISSUE TITLE
Branches in CONTRIBUTING.md are not up to date

### ISSUE THREAD

**Issue by muhme** [joomla/joomla-cms#43442]
### Problem identified

named branches `3.10-dev` ... `5.0-dev` in file `.github/CONTRIBUTING.md` are not up to date

### Proposed solution

update with 4.4-dev, 5.1-dev, 5.2-dev and 6.0-dev

### Open questions

can be documented or linked to an existing document:
* why is 4.4-dev the default github branch and not the current 5.1-dev?
* which branch should normally be used
* mention check in PR only in one branch
* mention PR will be passed on to other branches later

**Comment by rdeutz** [comment]
closing as we have a PR

**Comment by muhme** [comment]
Thanks Robert, now it's clearer for me
