### ISSUE TITLE
500 Error in Smart Search When Viewing Results During Indexing

### ISSUE THREAD

**Issue by AlexanderCkm** [joomla/joomla-cms#43443]
### Steps to reproduce the issue
1. Start the Smart Search indexer in the Joomla admin panel.
2. While the indexer is running, access a Smart Search results page that includes the result with the manually emptied 'object' value.
3. Observe that a 500 error occurs.

### Expected result
No 500 error should occur while browsing Smart Search results, regardless of the indexing status. Results with incomplete data should not appear until fully indexed.

### Actual result
A 500 error occurs stating "Attempt to assign property 'cleanURL' on bool" when attempting to browse Smart Search results that include items currently being indexed with an empty 'object' value.

### System information (as much as possible)
Joomla 4.4.4
PHP 8.1

### Additional comments
This issue occurs due to the indexer temporarily setting the 'object' column to an empty value during the indexing process, which leads to deserialization issues when accessed before the indexing is complete.

**Comment by richard67** [comment]
@AlexanderCkm There is no need to create an issue AND a pull request if you already know you will make a pull request. The pull request alone is sufficient in that case. And when we have a pull request for an issue, we close that issue. Please do that yourself next time when you have opened an issue and later make a pull request for it. Thanks in advance,

**Comment by richard67** [comment]
Closing as having a pull request. See #43444 .
