### ISSUE TITLE
Cypress System Tests fail when writing configuration.php 

### ISSUE THREAD

**Issue by muhme** [joomla/joomla-cms#43465]
(edited)

### Steps to reproduce the issue
* new Joomla installation as github clone as described in https://github.com/joomla/joomla-cms/tree/4.4-dev/tests/System 
* npm run cypress:run -- --spec 'tests/System/integration/install/Installation.cy.js'

### Expected result
* Cypress.based Joomla installation runs without errors, 'Install Joomla' spec is passing
* `configuration.php` parameters like $mailer = 'smtp' are set correct
* `configuration.php` file mask is still read-only (444)

### Actual result
```
  1) Install Joomla
       Install Joomla:
     CypressError: `cy.task('writeFile')` failed with the following error:

> EACCES: permission denied, open './configuration.php'
```

### System information (as much as possible)
* seen with local Joomla installations on macOS 14.4.1, Windows 11 and Linux
* does not occur on Linux with `root` user (as typically in Docker container based installation)
  * in Linux `root` installation there is the file mask 777 from the web-server created `configuration.php` file, which may be another problem

### Additional comments
* the read-only (444) file mask of `configuration.php` will likely be the cause
* workaround for Linux, macOS and Windows WSL 2 is to run the installation step as `root` user who is able to overwrite a read-only file:
  * `sudo npx cypress run --spec 'tests/System/integration/install/Installation.cy.js'`
  * this needs Cypress to be installed for `root` user or you use actual users Cypress installation cache, e.g.
    * `sudo CYPRESS_CACHE_FOLDER=$HOME/.cache/Cypress npx cypress run --spec 'tests/System/integration/install/Installation.cy.js'`
* ongoing  pull request is https://github.com/joomla/joomla-cms/pull/43466

**Comment by alikon** [comment]
please test #43466
