### ISSUE TITLE
Comma in Article Title

### ISSUE THREAD

**Issue by tadosborn** [joomla/joomla-cms#43472]
### Steps to reproduce the issue
When a comma is included in the title, the article cannot be deleted.  It drops from view in the Admin area, but remains in the database.  The article is being displayed in blog layout and duplicates were being displayed but not shown in the list of articles.

### Expected result
When an article is deleted, it should be deleted from the content table.

### Actual result
Article remains in the blog layout even when deleted or disabled in the admin area for articles.  

### System information (as much as possible)
Joomla 5.1.0
PHP 8.3.7
MariaDB 11.0.3

### Additional comments
Deleting record from database manually fixes issue of phantom articles.

**Comment by chmst** [comment]
How did you delete the article?  Did you set the status to "trashed"? 
Then filter the content for trashed articles and activate the "empty trash" action?

**Comment by tadosborn** [comment]
The duplicate articles were in the trashed articles and disappeared from there as well when trash emptied.  They remained in the database until they were manually removed via database.

**Comment by chmst** [comment]
I cannot replicate this issue. If the title does not contain a comma then it is deleted from the database? Are you using an extension?

**Comment by brianteeman** [comment]
unable to replicate

**Comment by tadosborn** [comment]
I’m not making this up!

**Comment by brianteeman** [comment]
happy to take a look at your site. email me your site access details

**Comment by tadosborn** [comment]
joomlaadmin
J00mla1111

https://cowoi.com/
Articles: Edit - Colorado Women of Influence - Administration (cowoi.com)<https://cowoi.com/administrator/index.php?option=com_content&view=article&layout=edit&id=14>

**Comment by chmst** [comment]
Please do not post account data - this is visible all over the world. Please change this account at once! Email @brianteeman as he said.

**Comment by brianteeman** [comment]
I logged in and changed the password (for the reasons stated above)

I created an article called Joomla,Joomla and was able to delete it

To confirm that it was really deleted I tried to create another article with the same name which I was able to do and then I deleted that article as well.

**Comment by tadosborn** [comment]
I referenced the article that was and still is an issue.

**Comment by tadosborn** [comment]
There is no obvious way to provide login credentials when it was asked.  Perhaps some instructions when you are asking for login credentials would be helpful.

**Comment by brianteeman** [comment]
I have logged back in and deleted the article you referred to id=14

No problems


https://github.com/joomla/joomla-cms/assets/1296369/4a0ea853-2fbe-485f-9b20-8347b0c08e92

**Comment by tadosborn** [comment]
I’m not trying to convince you that there is a bug.  I’m informing you that there is a bug.
This interaction makes me feel like this isn’t a legitimate concern for the team to investigate.  I’ve been working with Joomla for 20 years.
Do with the info what you wish.  I found it to be an issue that the team should investigate.

**Comment by brianteeman** [comment]
I have very generously logged in to your website and had no problem at all with deleting the article. I recorded everything I did so that you can see that.

**Comment by tadosborn** [comment]
Generously?  I don’t appreciate the dismissive and condescending tone.  Keep in mind that my intent is to help.
I’m done with this conversation.

**Comment by chmst** [comment]
> I’m done with this conversation.

So I close this. We can re-open if other users have the same issue. 

@brianteeman thank you very much for investigating.
