### ISSUE TITLE
[5.1] A big syntax error: implode() in com_ajax

### ISSUE THREAD

**Issue by korenevskiy** [joomla/joomla-cms#43470]
[/components/com_ajax/ajax.php](https://github.com/joomla/joomla-cms/blob/076864d32fc529007cf05d003426f24e4cc239f3/components/com_ajax/ajax.php#L230C12-L230C46) line 230 

```php
$out = implode((array) $results);
```
As we know, the first attribute of the "`implode`" function is a separator for combining. But here the "`implode`" function is written without a separator.
true format:
```php
implode(string $separator, array $array) : string
```

**Comment by korenevskiy** [comment]
Error due to PHP syntax confusion. Where there is no system for the order of function parameters.

**Comment by Fedik** [comment]
It is valid use of implode(), check the description https://www.php.net/manual/en/function.implode

> Alternative signature (not supported with named arguments):
> implode(array $array): string

You can close the issue. Thanks.

**Comment by korenevskiy** [comment]
> You can close the issue. Thanks.

You're right, I had a mistake in another one.

**Comment by korenevskiy** [comment]
```php
        } elseif (\is_scalar($results)) {
            // Output string/ null
            $out = (string) $results;
        } else {
```
@Fedik 
Tell me please.
In the com_ajax component, the returned value is reduced to a string.
Can the user return a `new JsonResponse `type object. 
But then this object will not be brought to the line. and it will be glued together and cause an error.

Do I need to do PR or is this normal behavior? Should we make the code more flexible?
