### ISSUE TITLE
The date of special publication from and to will not be saved if you do not have special enabled for the article

### ISSUE THREAD

**Issue by webmasterab** [joomla/joomla-cms#43486]
### What needs to be fixed
If I fill in the fields for Start Featured and Finish Featured in an article when publishing and I save the article, they will be cleared again if you do not have the Featured box set to yes in the content tab.

### Why this should be fixed
Could it be possible that you fill in all these fields but you have not yet made the article Featured? A message will appear, where you can also indicate that you still want to put the article on Featured.

I had to find out why the values ​​were not saved.

### Side Effects expected

This has been translated from Dutch using Google Translate.

Hope we can find a solution.

**Comment by chmst** [comment]
Duplicate https://github.com/joomla/joomla-cms/issues/43467

**Comment by Quy** [comment]
Closing as duplicate.
