### ISSUE TITLE
Frontend Media-Popup 404 if submenu and rewrite active

### ISSUE THREAD

**Issue by tidenhub** [joomla/joomla-cms#43480]
### Steps to reproduce the issue
1) Activate URL-Rewrite in the backend
2) Create 2nd level menu entry and link it to a single article
3) Go and edit this article in the frontend (Editor TinyMCE, but I don't think this matters.)
4) Use the button “Add Media / Image”

### Expected result
Showing of Media-Manager

### Actual result
Media-Popup shows Error 404

### System information (as much as possible)
php: Linux efe13562d1e4 5.4.0-131-generic #147~18.04.1-Ubuntu SMP Sat Oct 15 13:10:18 UTC 2022 x86_64
dbserver: mysql
dbversion: 8.0.34-26
dbcollation: utf8mb4_general_ci
dbconnectioncollation: utf8mb4_0900_ai_ci
dbconnectionencryption: 
dbconnencryptsupported: false
phpversion: 8.2.17
server: Apache/2.4
sapi_name: fpm-fcgi
version: Joomla! 5.1.0 Stable [ Kudumisha ] 16-April-2024 16:00 GMT
compatpluginenabled: true
compatpluginparameters: classes_aliases:"1", es5_assets:"1"
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36

**Comment by brianteeman** [comment]
Thank you for reporting this. I believe that this has been fixed with https://github.com/joomla/joomla-cms/pull/43376 and will be in the upcoming 5,1,1 release
