### ISSUE TITLE
5.1.1rc1 Reports as Stable

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#43496]
![image](https://github.com/joomla/joomla-cms/assets/1296369/8b3bf502-1277-4180-b2fc-cdfbde65e7c2)

![image](https://github.com/joomla/joomla-cms/assets/1296369/d07c201f-4de0-47df-8e81-23828603003c)

**Comment by bembelimen** [comment]
Hi @brianteeman , thanks for reporting the issue, it should be fixed now.
