### ISSUE TITLE
[5.2] Add missing Toggle inline help button to plugin modal / dialog

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#43501]
### Is your feature request related to a problem? Please describe.

In the back-end a lot of forms have extra information that becomes visible when you click on "Toggle inline help".
It will display some description if the language file has a "description" field.

In the back-end you sometimes open a Modal for editing something and those are missing the "Toggle inline help" button. 
PR https://github.com/joomla/joomla-cms/pull/43296 made by @Ruud68 fixes that for "Edit Plugin Settings"

### Describe the solution you'd like

We would like to have the "Toggle inline help" button functionality in every Modal where there's inline help available.

**Comment by brianteeman** [comment]
I have added the button to the module modal. I cant see anywhere else it should be added
