### ISSUE TITLE
Css a.btn in <joomla-alert> web component

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#43504]
### Steps to reproduce the issue
Visit your Joomla admin site and Inject the following html in the `<div id="system-message-container">`

```
<joomla-alert type="warning" close-text="Close" dismiss="true" style="animation-name: joomla-alert-fade-in;" role="alert">
<button type="button" class="joomla-alert--close" aria-label="Close"><span aria-hidden="true">×</span></button>
<div class="alert-heading">
<span class="warning"></span>
<span class="visually-hidden">Warning</span>
</div>
<div class="alert-wrapper">
<div class="alert-message"><div class="d-flex">
<a class="btn btn-primary ms-4" href="#someModal" data-bs-toggle="modal">Some Action</a>
</div>
</div>
</div>
</joomla-alert>
```

### Expected result
The button's text to be easily readable.

### Actual result
The button's text can hardly be read.
![alert_css](https://github.com/joomla/joomla-cms/assets/1838041/098b6091-fda9-4c65-b708-6c13e2ef9a06)

### System information (as much as possible)
J5.1.0

### Additional comments
Seems to be caused by that css:
```
#system-message-container joomla-alert[type="warning"] a {
  color: var(--state-warning-text);
  text-decoration: underline;
}
```

Found in the: media/templates/administrator/atum/css/vendor/joomla-custom-elements/joomla-alert.min.css

**Comment by dgrammatiko** [comment]
Try: 


```html
    <joomla-alert type="warning" close-text="Close" dismiss="true" style="animation-name: joomla-alert-fade-in;" role="alert">
        <button type="button" class="joomla-alert--close" aria-label="Close"><span aria-hidden="true">×</span></button>
        <div class="alert-heading">
            <span class="warning"></span>
            <span class="visually-hidden">Warning</span>
        </div>
        <div class="alert-wrapper">
            <div class="alert-message">
                <div class="d-flex">
                    <p>whatever</p>
                    <button type="button" class="btn btn-primary ms-4" data-bs-toggle="modal" data-bs-target="#exampleModal">Some Action</button>
                </div>
            </div>
        </div>
    </joomla-alert>
```

output: 
<img width="1455" alt="Screenshot 2024-05-21 at 9 30 14 PM" src="https://github.com/joomla/joomla-cms/assets/3889375/b132c171-288e-47d2-b682-3774c389be67">

FWIW `<a>` should not be used for actions, the semantically correct tag is `<button>`

**Comment by Pinkeltje** [comment]
It happens to have <a> as link i.e. when linking to a developers website to get paid version.
![2024-05-22 Screenshot 382](https://github.com/joomla/joomla-cms/assets/8941310/9644f65f-41df-4a10-8fbc-3a323c59b0f5)
Quick fix is adding this to css:
`.alert.alert-warning btn a {
	color: #fff;
}`
![2024-05-22 Screenshot 383](https://github.com/joomla/joomla-cms/assets/8941310/cff409da-0615-4948-b3fe-a45655f8b20d)

**Comment by sakiss** [comment]
Guys i know how to fix in on my own. The issue is opened for a fix in the 1st  place.

**Comment by Pinkeltje** [comment]
Same with alert info. 
![2024-05-23 Screenshot 384](https://github.com/joomla/joomla-cms/assets/8941310/2b13b687-f59f-47ba-96c7-7ad499f906cc)

**Comment by rdeutz** [comment]
@sakiss the fix is use a button. The other mentioned places are from 3rd part extensions and out of the scope of the core.
