### ISSUE TITLE
Minor error in mod_weblinks

### ISSUE THREAD

**Issue by Pinkeltje** [joomla/joomla-cms#43524]
### Steps to reproduce the issue
Create module mod_weblinks with multiple categories

### Expected result
Category title only

### Actual result
Category title with ; at the eind

### System information (as much as possible)
Joomla 5.1

### Additional comments
Error in tmpl/default.php on line 55
`        endif; ?>;`
Should be
`        endif; ?>`

**Comment by Quy** [comment]
Please post Weblink issues to https://github.com/joomla-extensions/weblinks. Thank you.
