### ISSUE TITLE
[5.1] Tags und Duplicate

### ISSUE THREAD

**Issue by Slava287** [joomla/joomla-cms#43543]
### Steps to reproduce the issue
Create any menu with a tag.
Example recepty.mobi/postnye-retsepty.html

### Expected result
By entering: 
/postnye-retsepty/fsdkljfsd
/postnye-retsepty/total-garbage
/postnye-retsepty/abcdefgh

The pages are available and duplicate the page: recepty.mobi/postnye-retsepty.html
There should be a 404 error when I enter:
/postnye-retsepty/fsdkljfsd
/postnye-retsepty/total-garbage
/postnye-retsepty/abcdefgh
But for some reason it’s not there, but a duplicate is triggered.

### Actual result
Page
/postnye-retsepty/fsdkljfsd
/postnye-retsepty/total-garbage
/postnye-retsepty/abcdefgh

200 Ok and duplicate the page /postnye-retsepty.html

### System information (as much as possible)

 Joomla! 5.1.0 Stable cgi-fcgi 8.3.1

### Additional comments
I tried on many sites, the problem exists. Does anyone know how this can be solved?

**Comment by Hackwar** [comment]
Hello @Slava287, I wrote a PR #44540 to fix this. Please test. Since we have a fix, I'm closing this PR.
