### ISSUE TITLE
[5.2] Usability: Back-end - Add total number of items to Page Navigation

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#43548]
## Problem identified

In the Joomla back-end, most components offer an overview of their items, complete with filters at the top to help you to filter the items. One of these filters is list[limit]. However, admins do not have an immediate overview over the number of items in the list, before and after applying the filters. 

If you want to find out the total number of items, 
you need to set the List Limit filter to 10, 
navigate to the last page (e.g., page 3), 
count the items on that page, 
and then add the page number of the previous pages multiplied by 10.

## Proposed solution

To make Joomla more user-friendly, it would be great to have a "total" counter at the bottom near the pagination. This counter should show the number of items available after applying the filters. 
This feature would be useful for all components in the back-end.

![Image](https://github.com/joomla/joomla-cms/assets/1217850/1dc97685-35fa-47c7-b7b3-73c7a1b52d17)

**Comment by brianteeman** [comment]
please see #43570

**Comment by HLeithner** [comment]
closing since we have a pr
