### ISSUE TITLE
[5.2] Usability: Media Manager > edit image > contain instead of cover (think of vertical images)

### ISSUE THREAD

**Issue by woluweb** [joomla/joomla-cms#43552]
## Problem identified

Currently, if you Edit an image in the Media Manager, sometimes only part of the image is visible (especially if you have a vertical image as illustrated on the screenshots below. If necessary play with the width and height of your browser window to see the issue).

This makes it for example very difficult to crop an image because
- you don't see the whole image
- and you can't even "scroll" the image

![Image](https://github.com/joomla/joomla-cms/assets/4510979/d4538148-6eec-4846-8f50-fff59aa6074a)
![Image](https://github.com/joomla/joomla-cms/assets/4510979/91261b74-c4e2-4db3-8e44-dc7f010fe72e)

## Proposed solution

Instead of displaying the image with "cover", the Media Manager Edit Container should display it with "contain".

**Comment by brianteeman** [comment]
unable to replicate 
![scroll](https://github.com/joomla/joomla-cms/assets/1296369/1c42c9fb-5d40-4dea-84f0-c3ceabe6cd76)

**Comment by brianteeman** [comment]
Still cannot replicate this bug report
