### ISSUE TITLE
[5.1] Problem: Menu items with Item Selection Options doesn't work

### ISSUE THREAD

**Issue by Kadmon06** [joomla/joomla-cms#43558]
Update: The cause of the problem is with the Route66 plugin installed on the website.

### Steps to reproduce the issue

Create two tags, "A" and "B".
Create an article, titled "1", tag it with "A".
Create an article, titled "2", tag it with both "A" and "B".
Create an article, titled "3", tag it with "B".
Create a new menu item.
Choose Tags - Tagged Items

From the Tags option, first select tag "A" and then tag "B".

TEST 1

Go to Item Selection Options, choose Any.

### Expected result

When selecting the menu, all of the tagged articles (1, 2, 3) will be displayed, as they all contain either tag "A" or tag "B".

TEST 2

Go to Item Selection Options, choose All.

### Expected result

When selecting the menu, ony article 2 will be displayed, as it is the only one that contain both tag "A" and tag "B".

### Actual result

When selecting the menu, article 1 and 2 will be displayed, as they contain tag "A".
Any further tags after the first tag are ignored in the list.

### System information (as much as possible)

Joomla 5.1.0
Multi-language site

### Additional comments

For a while (probably up to 4.0) Item Selection didn't work. Then it was fixed, and up until now, it seemed to work.

As it's a multi-language site, I tried switching the language of the Tag to All, I tried switching the menu item language to All, but changing the language doesn't seem to change the behaviour.

**Comment by Quy** [comment]
Closing as a non core issue.
