### ISSUE TITLE
[5.2] Usability: Media Manager - Allow SVG images

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#43550]
## Problem identified
Currently

1. it's not possible to use Joomla's Media Manager to upload SVG images. When you try to upload an .svg you get an error message:

![Image](https://github.com/joomla/joomla-cms/assets/1217850/6a9aa06a-b4bb-4d09-a0d3-903190ce7e0e)

2. SVG images uploaded via FTP are not shown in the media manager.

The question of how to upload .svg images is frequently asked in Joomla forum:
https://forum.joomla.org/viewtopic.php?t=998705
https://forum.joomla.org/viewtopic.php?t=975327

## Proposed solution
Add support for .svg images in Joomla to Upload *and* Display in media manager (and so to use anywhere like in Articles etc).

Currently, users have to configure the Media Manager *manually* as follows:
- Media > Options > Allow Extensions > add "svg"
- Media > Options > Legal Image Extensions (File Types) > add "svg"
- Media > Options > Legal MIME Types > add "image/svg+xml"

The idea is to have this added by default for new installations (probably not on existing installations, unless there is for exampla a check that it has not already been added manually).

Note:
As far as we know, the Joomla core already checks SVG content for potentially harmful code.
When adding this feature we should make extra sure that this works correctly to not introduce security issues.

**Comment by Fedik** [comment]
Please try https://github.com/joomla/joomla-cms/pull/38536
You should get a better message why your SVG is not allowed.
