### ISSUE TITLE
[5.2] Usability: Media Manager - tick checkbox of newly uploaded Media

### ISSUE THREAD

**Issue by woluweb** [joomla/joomla-cms#43554]
## Problem identified

When uploading 1 (or several) Media (image, document, ...) in the Media Manager, the Media is not "selected" meaning that the users have to *manually*
1. search for that Media
2. tick its checkbox

before being able to click on Insert or Edit or whatever.

Illustration of ticked checkbox:
![ticked-checkbox](https://github.com/joomla/joomla-cms/assets/4510979/e80567c3-fd5c-42a7-a891-7365454060dc)

## Proposed solution

 Automatically *tick the checkbox" of the newly uploaded Media.

**Comment by rdeutz** [comment]
@Quy please close when it is clearly a duplicate
