### ISSUE TITLE
[5.2] Usability: add Versioning to Menu Item edit

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#43551]
The Article and Category edit forms have a handy "Versions" option. 
Which is great when you accidentally save changes in the wrong place. 

![Image](https://github.com/joomla/joomla-cms/assets/1217850/6973888e-34da-49d5-a393-07c40048efb2)

Adding the "Versions" functionality to the Menu Item edit screen would be a great feature.

![Image](https://github.com/joomla/joomla-cms/assets/1217850/86945887-bb43-447a-84b2-bed1b1727a5a)

**Comment by rdeutz** [comment]
This sounds like a good idea in the first place. But this leads to many new problems, e.g. if you change the alias a couple of times and then use a version from the past you can have conflicts. It will be a nightmare with the URL and the router. I am strongly against this.

**Comment by Hackwar** [comment]
I also don't see the benefit of adding this. In case of a menu item to com_content, the article or category could have been deleted and all of a sudden you get a broken menu item. Menu items also aren't overly complex items (or shouldn't be) so that a versioning here rarely makes sense.

**Comment by Fedik** [comment]
While I am agree with all previous comments, I still think we can implement this feature, but without "restore" functionality.
Because one of the advantages of use versioning is to see what and when something was changed, and by whom (especialy for sites with multiple managers).

**Comment by pe7er** [comment]
This possible future feature has been discussed in yesterday's weekly CMS Maintenance meeting. 
It was decided that if someone is willing to code this functionality, then it could be merged.

If someone can code this functionality, please do.
