### ISSUE TITLE
Unable to install languages

### ISSUE THREAD

**Issue by Pinkeltje** [joomla/joomla-cms#43565]
### Steps to reproduce the issue
Go to system - languages and click install languages

### Expected result

List with languages to install

### Actual result
Error: Can't retrieve XML from https://update.joomla.org/language/translationlist_5.xml

### System information (as much as possible)

Joomla 5.0.1 and 5.1.1
**Joomla 4.4.4 and 4.4.5 are ok!**

### Additional comments
Tested on several sites and different servers

**Comment by pe7er** [comment]
I can confirm that two of my multilingual Joomla 5.1.1 websites have under "Update Sites" (System > Update Sites) 
for each language a link to "Accredited Joomla! Translations" https://update.joomla.org/language/translationlist_5.xml

On a Joomla 4 website the "Accredited Joomla! Translations" points to ``https://update.joomla.org/language/translationlist_4.xml`` which is working.

It seems like there is an issue with the update server for the Joomla 5 language files.

**Comment by pe7er** [comment]
@Pinkeltje For me https://update.joomla.org/language/translationlist_5.xml is working again and it gives the XML with all language packages.
Could you please check again?

**Comment by Pinkeltje** [comment]
@pe7er Checked and is working now!
