### ISSUE TITLE
Related Article Module sort articles

### ISSUE THREAD

**Issue by leetempest** [joomla/joomla-cms#43567]
### Is your feature request related to a problem? Please describe.
Kind of! There is no option within the Related Articles module to select how to display the articles, wether this is sorted by date ascending / descending, featured, article order etc.
Currently the module displays the selected number of articles in ascending date order, which on my clients site is displaying articles dated back in 2011.

### Describe the solution you'd like
An option within the module config to select how the related articles are sorted and displayed.

**Comment by leetempest** [comment]
So found a 'hack' to the RelatedItemsHelper.php file by adding:

  ->order('a.id DESC');

after line 116.

However this will be over written on any Joomla update I suspect.

**Comment by drmenzelit** [comment]
It is not a good idea to do changes in core files ;-)
What you can do is create an override for the module and add `sort($list);` after line 18, that will change the order of the elements in the array.

**Comment by drmenzelit** [comment]
It is not a good idea to do changes in core files ;-)
What you can do is create an override for the module and add 
```
usort($list, function($a, $b) {
    return strtotime($b->created) - strtotime($a->created);
});
```
after line 18, that will display the newest article first.

**Comment by brianteeman** [comment]
The new (not ready yet) combined content module will support this functionality

**Comment by rdeutz** [comment]
As Brain said we are planning to work on the article modules for Joomla6 and this will include something you need. Because of the limited resources we have I don't want to spend time on the current modules. So I am closing this. Would be great when you check the new version of the article module when done and test.
