### ISSUE TITLE
com_finder not found

### ISSUE THREAD

**Issue by dailydealsuk** [joomla/joomla-cms#43569]
I think I deleted smart search years ago, and now I need it. Been searching for days and can't find a way to reinstall. 

I figured this was my best shot. 

when I go to /administrator/index.php?option=com_finder it says 

An error has occurred.
404 Component not found.

I'm using J4.4.5

Really sorry if this is the wrong place to post.

**Comment by brianteeman** [comment]
You need to re-install core joomla as you have been advised in the forum.

This can be closed
