### ISSUE TITLE
ScheduleRunner::runWebCron using menu's  id

### ISSUE THREAD

**Issue by brbrbr** [joomla/joomla-cms#43576]
### Steps to reproduce the issue

- Create a menu item with a single article and make it the default menu (or any other menu item with an id=)
- Create a Webcron Link 
- Execute the Webcron

### Expected result

Execution of task(s) due to execution. From the inline help:

`By default, requesting this base link will only run tasks due for execution. To execute a specific task, use the task's ID as a query parameter appended to the URL: BASE_URL&id=<taskId>`

(Thus the id retrieved from the input in ScheduleRunner::runWebCron should be zero.)

### Actual result

The id in runWebCron is set to the id from the menu item, I think it is parseRawRoute adding the id.

So only the tasks matching that ID is executed, if there is any task with that id.

### Additional comments

The problem is resolved by adding a &id=0 to the Webcron Link.  Which is a minor inconvenience, but shouldn't that be the default base url??

**Comment by brbrbr** [comment]
This issue is resolved with PR #43164

**Comment by alikon** [comment]
so let's close it
