### ISSUE TITLE
Plugin for vote article!

### ISSUE THREAD

**Issue by Pierantonio** [joomla/joomla-cms#43571]
Do you know if there is a plugin, possibly free, to vote on articles with Joomla 5.1.1 - Thanks in advance!

**Comment by brianteeman** [comment]
it is part of the core joomla release

**Comment by richard67** [comment]
This here is a place to report bugs but not a place to ask for availability of extensions.

Please use the support forum for such questions.

And as Brian said, votings for articles is part of the CMS core.

**Comment by Pierantonio** [comment]
Sorry sorry and sorry!
