### ISSUE TITLE
[5.1.1] Do not open archived articles via a direct link

### ISSUE THREAD

**Issue by 1inkin** [joomla/joomla-cms#43572]
### Steps to reproduce the issue
1. open the page of the published article.
2. save the link of opened article.
3. save the article in an archive state.
4. open the article via the link.

### Expected result
the article with archive state cannot be opened via a direct link

### Actual result
the article with archive state opened like article with published state

### Additional comments
if user has saved a link to the article, then he can view this article as published, even if it is already in the archive. it misleads the user.

**Comment by brianteeman** [comment]
Why do you expect that behaviour

Archived does not mean unpublished

**Comment by HLeithner** [comment]
That's expected behavior. The Status says nothing about the url/location of the article. Only Status trashed and unpublished all others are published. I'm closing this.
