### ISSUE TITLE
[5.x] Can't make Ldap integrated plugin to work

### ISSUE THREAD

**Issue by Chico0008** [joomla/joomla-cms#43578]
### Steps to reproduce the issue
activate and configure Ldap authentification plugin
mayber need a update/better help on configuring ?

### Expected result
new user login with his ldap username/password
user automativally integrated in joomla and success login

### Actual result
user unknown, can't access

### System information (as much as possible)
Serveur : Linux Ubuntu 22.04lts
Joomla : 5.0 then updated to 5.1
apache 2.4, PHP 8.1, Mariadb 15.1

Other site using ldap works fine, even with SSO.

maybe i need help to know what i should configure
![image](https://github.com/joomla/joomla-cms/assets/58886243/355e9dff-c8aa-4786-a182-9d3963cd333a)

the only log i can get : 
`2024-05-30T13:35:13+00:00       INFO 10.0.1.107 ldapfailure     Le mot de passe ne correspond pas au nom d'utilisateur, ou vous n'avez pas encore de compte.
`

My joomla is in french/

**Comment by Quy** [comment]
Duplicate #42218?

**Comment by Quy** [comment]
Maybe #41858 can be of help.

**Comment by Chico0008** [comment]
Cool
#41858 helped me
only have to put this
![image](https://github.com/joomla/joomla-cms/assets/58886243/dbab9a85-1508-456b-9f0f-37b53584c201)
and all works fine.

Thanks.
Maybe publish a updated documentation to help people configure this native plugin :)

**Comment by rdeutz** [comment]
I hope a documentation change will be a result of the mentioned issue
