### ISSUE TITLE
J5.1.1 module position "none" has some characters on the right and left that do not belong there

### ISSUE THREAD

**Issue by WM-Loose** [joomla/joomla-cms#43583]
Joomla 5.1.1 - German
The name of the module position "none" has some characters on the right and left that do not belong there.

![1](https://github.com/joomla/joomla-cms/assets/99647423/f135f4e5-f54f-4164-9d4c-e1c127fb005d)

backend, modules, options

German Language Version 5.1.1.1

**Comment by chmst** [comment]
Same in Englisch. It is a language string. You can override the language if you want.
Why is this an issue for you?

**Comment by WM-Loose** [comment]
In Joomal 4.4.5 it is displayed as a normal word without the characters next to it. So I assumed it was a typo. I didn't notice it myself and just got a notification about it today.
![2](https://github.com/joomla/joomla-cms/assets/99647423/9b071ca2-3ff5-4500-bd45-f51c6f50b38f)

**Comment by WM-Loose** [comment]
![3](https://github.com/joomla/joomla-cms/assets/99647423/21392323-4d52-4bb3-bf32-cf2274d75597)

**Comment by brianteeman** [comment]
I cannot comment about the german language pack but the core en-GB has used this text since at least joomla 3.0

**Comment by Fedik** [comment]
That is kind of expected, it more like indication of "non real" position, while you still can have:
```
<jdoc:include type="modules" name="keine"/>
```

I am closing here.
