### ISSUE TITLE
Different colors and / or positon for close and delete button in template/file editing

### ISSUE THREAD

**Issue by Ralf8m** [joomla/joomla-cms#43584]
### Steps to reproduce the issue
When editing templates / files - I would like the DELETE button to be floated to the right (it remains red).  Close file - perhaps another icon but make the button yellow and leave it in place.

I've accidentally clicked on it a few times - of course a warning comes up - but well, from the user experience that would be more logical - at least in my opinion.

![file_editing](https://github.com/joomla/joomla-cms/assets/34646901/e94b5558-82ec-4bb0-8bc1-a65d884652ca)

### Expected result
Other icon - button color and positioning of the button.

### System information (as much as possible)
Joomla 5.1.1

**Comment by chmst** [comment]
Duplicate #43212

**Comment by Ralf8m** [comment]
OOps thanks @chmst don't have seen that issue. I'll close mine ;)
