### ISSUE TITLE
5.1.1 update is not found

### ISSUE THREAD

**Issue by peteruoi** [joomla/joomla-cms#43591]
### Steps to reproduce the issue
Have a site in 5.1.0 (migrated)
Search for  joomla updates. None found

### Expected result
FOund 5.1.1

### Actual result
none found even after trying a lot of times

### Additional comments
The sollution probably is returning the joomla update channel to stable and not to next (It was left to next cause of migration).
After changing it to stable it worked

**Comment by rdeutz** [comment]
expected behauviour

**Comment by brianteeman** [comment]
Are you sure this is the expected behaviour? Maybe my memory fails me but prior to 5.1 if you were on joomla 5.0.1 and channel next then you would be notified about 5.0.2.

Even if my memory is wrong a user on j4 had to set the channel to next to get j5 and at no point are they told to change their update channel to stable then **none of these users will ever see an update to j5**. The only reason @peteruoi would not even have known there was a new release of 5 was because they saw that information elsewhere

**Comment by brianteeman** [comment]
please re-open

the joomla 5 next channel shows that 5.1.1 is available so the user should have been notified of 5.1.1 release. So clearly it is NOT expected behaviour that you have to change the channel

https://github.com/joomla/update.joomla.org/blob/master/www/core/j5/next.xml

**Comment by richard67** [comment]
> please re-open
> 
> the joomla 5 next channel shows that 5.1.1 is available so the user should have been notified of 5.1.1 release. So clearly it is NOT expected behaviour that you have to change the channel
> 
> https://github.com/joomla/update.joomla.org/blob/master/www/core/j5/next.xml

@brianteeman That XML is only relevant for 5.0 to 5.1 updates. For 5.1.x to 5.1.y updates the TUF repository is used: https://update.joomla.org/cms/targets.json .

**Comment by richard67** [comment]
P.S.: On 5.1 the default and next update channels use the same update URL. The difference is in the "channel" properties in the json (see link in my previous comment). On 5.x that would be "5.x" for the default and "6.x" for the next channel.

**Comment by brianteeman** [comment]
That explains where the bug is then

**Comment by brianteeman** [comment]
if you think it is acceptable not to change the behaviour and not to let users know about security or bug fixes then I guess it is the expected behaviour. clearly I disagree

**Comment by peteruoi** [comment]
> Are you sure this is the expected behaviour? Maybe my memory fails me but prior to 5.1 if you were on joomla 5.0.1 and channel next then you would be notified about 5.0.2.
> 
> Even if my memory is wrong a user on j4 had to set the channel to next to get j5 and at no point are they told to change their update channel to stable then **none of these users will ever see an update to j5**. The only reason @peteruoi would not even have known there was a new release of 5 was because they saw that information elsewhere

Correct.

This could almost be characterised as security risk as the magnificent feature of joomla that informs the admins that a new update is on could be made useless.
At the very least (if the above is difficult to be implemented) make a new post install message after mifration from a major version that the users are strongly encouraged to change the update channel to joomla stable.

**Comment by brianteeman** [comment]
Of course it is a security risk!!

**Comment by richard67** [comment]
The author of an issue can always reopen it on GitHub if they think closing was wrong.

**Comment by peteruoi** [comment]
i don't have access to re-open. I personally have this corrected for me as now i know and i have changed the update channel manually. i still believe that other users won' t be as informed as me and joomla's backend is gonna give them a wrong feeling of secureness. I understand that now nothing can happened for the already migrated sites but i believe we can make it correct for the sites soon to be migrated

**Comment by rdeutz** [comment]
Sorry guys you are right makes sense to have 5.1.1 offered as update when on channel next.

**Comment by peteruoi** [comment]
https://www.facebook.com/groups/joomlanospam/permalink/10159616746300997/
maybe this is relevant?

**Comment by Scrabble96** [comment]
Am I right in thinking that for those who updated 5.0x to to 5.1.0, it automatically changed the channel to 'Next'. But as 5.1.1 is not being flagged up as a 'Next', no-one will ever get notifications of an update in future, until version 6 comes along. Is that right? Can 5.1.2 have a 'Next' tag that then reverts the channel back to 'Default'?

**Comment by brianteeman** [comment]
Just to further confirm that not showing the update to 5.1.1 for user on the NEXT update channel this is the information displayed when you are on that channel

COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATES_INFO_NEXT="You are on the &quot;%s&quot; update channel. Through this channel you'll receive notifications for all updates of the current Joomla release (5.x) and you will also be notified when the future major release (6.x) will be available. Before upgrading to 6.x you'll need to assess its compatibility with your environment."

**Comment by Scrabble96** [comment]
And also to clarify, I was alerted of an upgrade from 5.0.3 to 5.1.0 and had not changed the channel from 'default' to 'next'. 
It would appear that part of the upgrade to 5.1.0 changed the channel to 'next'. 
Despite what it says in the notice you give above for the 4x to 5x upgrade (which is different) alerts for 5.1.0 to 5.1.1 were not received.

As an aside, the version history page at https://docs.joomla.org/Joomla!_CMS_versions is out of date, or does it never include the latest versions?

**Comment by richard67** [comment]
Closing as having a pull request. Please test #43695 . Thanks in advance.

**Comment by richard67** [comment]
New PR is #43717 . Please test. Thanks in advance.
