### ISSUE TITLE
Custom text field: HTML filter active after migration to J5 

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#43603]
### Steps to reproduce the problem
Create a text custom field in Joomla 3. Insert a text with a special character in an article, for example ‘Price: EUR 10 > million’. save the article. The entered value is displayed correctly. Migrate the website to Joomla 4 and then to Joomla 5.

### Expected result
The content in custom fields is displayed correctly.

### Actual result
The filter ‘safe HTML’ is applied to the text field mentioned above. This cleans the existing values in custom fields, the above example then reads ‘Price: EUR million’.

### Additional comments

**Comment by hytsch** [comment]
I assume that it is sufficient to create the custom fields in J4, fill them with content and then migrate them to j5, but I have not been able to test this.

**Comment by brianteeman** [comment]
Need to check with @jsst but I am fairly sure that this is the intended behaviour now to santize the input field otherwise there is a security vulnerability. 

cc @SniperSister

**Comment by SniperSister** [comment]
That is indeed intended behavior. J3.x lacked a reasonable filtering settings for com_fields.

**Comment by brianteeman** [comment]
This should be closed as the expected behaviour
