### ISSUE TITLE
Vote plugin is displayed even when disabled inside article

### ISSUE THREAD

**Issue by romFle** [joomla/joomla-cms#43612]
### Steps to reproduce the issue
- search plugin Content - vote
- enable plugin
- save and close
- open main article
- switch to tab "options"
- set option "content vote" to hide
- save and close
- open start page

### Expected result
- no grey star icons are displayed in main article

### Actual result
- vote star icons are displayed in every article, independent of option was set to hide or to show

### System information (as much as possible)
Joomla 5.1.0
Database version: 8.0.36-0ubuntu0.22.04.1
Webserve: apache
PHP: 8.3.7

**Comment by Quy** [comment]
I cannot reproduce. Are you using Cassiopeia or a custom template?

**Comment by romFle** [comment]
I use the standard Cssiopeia template only with colors modified.

![Display on main startpage](https://github.com/romFle/screenshots/blob/main/joomlaMainArticle.jpg?raw=true)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43612">issues.joomla.org/tracker/joomla-cms/43612</a>.</sub>

**Comment by Quy** [comment]
Please reupload screenshots.

**Comment by romFle** [comment]
![joomlaVoteDisplayError](https://github.com/joomla/joomla-cms/assets/171659113/174a9ed2-503a-4a47-8671-02c8ad5fa883)

I hope the upload works now. This is how the main article (title of first screenshot, and options are second screenshot) is displayed. I woud expect, that the stars were not displayed.

**Comment by chmst** [comment]
How did you set the vore parameter in the menu options? The menu settig ha higher priority that the setting of the article.

**Comment by romFle** [comment]
Damned - this causes the visibility. You 're right - change settings for menu entry and article together works fine..
My mistake - Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43612">issues.joomla.org/tracker/joomla-cms/43612</a>.</sub>
