### ISSUE TITLE
Deprecation warnings on admin login screen on PHP 8.2

### ISSUE THREAD

**Issue by RickR2H** [joomla/joomla-cms#43613]
### Steps to reproduce the issue
- Make sure you are on PHP 8.2 or higher version
- when logged in put the Error reporting on maximum
- Logout
- The login screen has deprecation warning

### Expected result
No warnings

### Actual result
Deprecation warnings

Warning: Attempt to read property "metadata" on array in C:\laragon\www\testsite\libraries\src\Language\LanguageHelper.php on line 52

Warning: Trying to access array offset on value of type null in C:\laragon\www\testsite\libraries\src\Language\LanguageHelper.php on line 56

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in C:\laragon\www\testsite\libraries\src\HTML\Helpers\Select.php on line 557

### System information (as much as possible)
Joomla 5.1.1 / PHP 8.2

**Comment by brianteeman** [comment]
Do you have multiple languages installed?

**Comment by RickR2H** [comment]
I did a migration and I notices somehow the Dutch language was installed two times. I uninstalled both versions and reinstalled the language. Now the errors are gone. I'll close the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43613">issues.joomla.org/tracker/joomla-cms/43613</a>.</sub>

**Comment by chmst** [comment]
If it is a migration - are there still overrides?
