### ISSUE TITLE
Buenas, la descripción del sitio web o pagina web sale con letras chinas.

### ISSUE THREAD

**Issue by andreGF12** [joomla/joomla-cms#43619]
### Steps to reproduce the issue
[Prueba](https://drive.google.com/file/d/1_YDW1F9_fQRT92Uik4SWitN8R2OWiTYL/view?usp=sharing "Web Alterada")

### Expected result

Que vuelva la descripcion como estaba antes

### Actual result

Descripcion de la web alterada con letras chinas

### System information (as much as possible)
```php
<?php
class JConfig {
	public $MetaDesc = 'Aquí encontrarás las herramientas que necesitas para aprender sobre bienes raíces y emprendimiento.';
	public $MetaKeys = 'inversion, inmobiliaria, alvaro gil, arequipa, franquicia, casas, lotes, departamentos,';
}
```

### Additional comments

Apesar que la configuration.php esta bien salen esas letras chinas

**Comment by brianteeman** [comment]
The website shown in the google results screenshot is not joomla

**Comment by rdeutz** [comment]
wrong place, ask in the [forum.joomla.org](https://forum.joomla.org/viewforum.php?f=24&sid=19f7a03872fc6f6b87c68362df10a58d)

**Comment by andreGF12** [comment]
Pero si cuando busco soporte me manda a esta pagina<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43619">issues.joomla.org/tracker/joomla-cms/43619</a>.</sub>
