### ISSUE TITLE
[5.2] Consistency: Users (front-end) - Front-end Overview + Single User view

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#43614]
Joomla is used for all kinds of websites. It is also great for magazine websites with articles and authors, association websites with members, portals with users, etc. However, currently in the Joomla **front-end** you **cannot display lists of users** without 3rd party extensions.

We would like to have:
- [ ] a **front-end model** and a **view** to **display a list of users**
- [ ] a **front-end model** and a **view** to **display an individual user**

In a lot of cases you could create a template override, add some code to get data from a model. In case of com_users you cannot use the back-end model in the front-end. To access the com_users back-end model you'll need some authentication so that only works for registered users who are logged in. Therefore we would like to include front-end models in com_users.

Some years ago I created a PR for this for Joomla 4 which was closed. 
Maybe some parts of the code can be re-used: https://github.com/joomla/joomla-cms/pull/25030

The following are guidelines for what we would like to see in a front-end Users Overview and Single User View for com_users.

## Users Overview
- Because of **security and privacy**, a list of users should **only be displayed** when it has **a published menu item**. To display a list of Authors, you'll need to create a menu item like "Contributors" (alias "contributors"). The internal like might be something like /index.php?option=com_users&view=users&id=3 (the author group has id: 3). The link that should work would be example.com/contributors 
- If there's **no Menu Item** created to display a list of Super Users, then /index.php?option=com_users&view=users&id=8 (the Super Users group has id: 8) should trigger an error (404?) and **not display** the users.
- It should be possible to **exclude specified users** from the list of users
- Maybe **some fields** from the Users table should **not be added** to the front-end model, like password, otpKeys and API token.

### Adding a menu item for Users Overview
A new "Users List" or "List Users" view should be created: 
![menu-item-type](https://github.com/joomla/joomla-cms/assets/1217850/d04a6b83-1966-4f95-bf5d-039bca172184)

The menu item edit should have an option to select one or more User Groups, and an option to exclude single users from the overview. The example below shows a multiple select option. It would be better to use the "fancy select" for both fields to make it easier to add multiple groups/users. 
![menu-item-edit2](https://github.com/joomla/joomla-cms/assets/1217850/10dfd766-80eb-4cc1-be9e-8fb41d7d338e)

### Front-end view of User Overview
The front-end User Overview should display some columns with information. The columns should be configurable in the menu item. The Names of the user should link to an individual User page.
![front-end-users-overview](https://github.com/joomla/joomla-cms/assets/1217850/3eb68ad7-0dd1-4bc8-82ed-880c3a2f0a78)

### Adding a menu item for Single User
A new "Single User" view should be created, just like the "Users List" view above. The menu item should have some options to display or hide User details (by default: hide) 

## Single User View
- A single User page should **only be displayed** when it has a **published Single User menu item**, or when there's a published Users Overview menu item for its User Group.
- I'm not sure about the best SEF for Single User pages that do not have a menu item. Using the "username" might be a security issue. Using the Name field might be not unique enough. Maybe for the time being use the UserID?
- Users **should not be displayed** with links like index.php?option=com_users&view=users&id=42

![front-end-single-users](https://github.com/joomla/joomla-cms/assets/1217850/73463344-cc6d-4775-be2b-cdd3d0aed03d)

In some cases, like with a magazine website, it would be nice to display all articles written by a "Contributor". For that a separate module "Content by User" can be created. That way the **Single User page** can be a **sort of place holder** for **other** (3rd party) **modules** that are specific for that user.

**Comment by brianteeman** [comment]
Wouldnt this be the same as using the existing contact creator plugin and then displaying a list of contacts#?

**Comment by brianteeman** [comment]
Also pretty sure that displaying a list of individual users to exclude will be a massive performance issue on a site with a lot of users. We've seen that before for relatively small lists such as when we tried to display a select list of all folders in the media plugins

**Comment by pe7er** [comment]
> Wouldnt this be the same as using the existing contact creator plugin and then displaying a list of contacts#?

No, I know the contract creator plugin. 
And the contract creator plugin workaround is not what we want:
- It duplicates data from the Users table into the Contacts table, which is unnecessary overhead
- It does not keep the Contacts table in sync with the Users table.
- Furthermore we don’t need the contact form functionality of com_contacts, nor all those fixed contact fields.

Instead, we want to create views **using the existing data** (no duplicates) 
and make these views **more flexible** by making it possible to display the **Custom Fields** currently already available in **Users**.

**Comment by pe7er** [comment]
> Also pretty sure that displaying a list of individual users to exclude will be a massive performance issue on a site with a lot of users. We've seen that before for relatively small lists such as when we tried to display a select list of all folders in the media plugins

True!
We could consider a different approach: Instead of displaying a massive list of users, we could add functionality to com_users that allows us to display or hide individual users. And in the new front-end view in com_users we would only display users who aren't set to hidden. That way we could avoid those performance issues.

**Comment by brianteeman** [comment]
Looking at the previous PR (which I never understood why you closed it) I see a reference to an RFC you also created - in that RFC it says it was being taken to the production dept for a decision. https://github.com/joomla/rfc/pull/19#issuecomment-741891351 Was that ever done?

**Comment by brianteeman** [comment]
As for the exclusions I would do this by usergroup not by user. For example on one of my sites I have two parallel usergroups "public members" and "private members"
