### ISSUE TITLE
Cypress System Test fails on 2nd run if cmsPath set

### ISSUE THREAD

**Issue by muhme** [joomla/joomla-cms#43622]
### Steps to reproduce the issue
Having an installation with cmsPath set != "." e.g. cmsPath="/tests/www/cmysql/" like drone does
```
> npx cypress run
> npx cypress run
```
### Expected result

The system test suite is executed twice without errors like with cmsPath="."

### Actual result

First time the system test suite is executed without errors. Second time it is failing in the first step 'Install Joomla':
```
  Install Joomla
    1) Install Joomla


  0 passing (6s)
  1 failing

  1) Install Joomla
       Install Joomla:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#jform_language`, but never found it.
      at Context.installJoomla (webpack://joomla/./node_modules/joomla-cypress/src/joomla.js:10:0)
```

### System information (as much as possible)

Seen on docker drone system tests clone, branch 4.4-dev

### Additional comments

Obvious reason is missing `cmsPath` in `tests\System\integration\install\Installation.cy.js` with
```
    cy.exec('rm configuration.php', { failOnNonZeroExit: false });
```

👉 Workaround is to delete file `configuration.php` in directory `cmsPath` before 2nd test run.

This is a minor issue and i will create a PR afterwards together with #43620.

**Comment by rdeutz** [comment]
You can create a PR directly an issue is not needed.

**Comment by muhme** [comment]
thx, i have already created PR directly

**Comment by alikon** [comment]
closing as we have a pr #43656
