### ISSUE TITLE
Cypress System Test fails on 2nd Windows run

### ISSUE THREAD

**Issue by muhme** [joomla/joomla-cms#43620]
### Steps to reproduce the issue
```
> npx cypress run
> npx cypress run
```
### Expected result

The system test suite is executed twice without errors, like on macOS or Linux.

### Actual result

First time the system test suite is executed without errors. Second time it is failing in first step 'Install Joomla':
```
  Install Joomla
    1) Install Joomla


  0 passing (6s)
  1 failing

  1) Install Joomla
       Install Joomla:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `#jform_language`, but never found it.
      at Context.installJoomla (webpack://joomla/./node_modules/joomla-cypress/src/joomla.js:10:0)
```

### System information (as much as possible)

Seen on Windows 11 Pro, Laragon with Cmder, branch 4.4-dev

### Additional comments

Obvious reason is `tests\System\integration\install\Installation.cy.js` with
```
    cy.exec('rm configuration.php', { failOnNonZeroExit: false });
```
There is no `rm` command on Windows. 

:point_right:  Workaround is to delete `configuration.php` before 2nd test run.

This is a minor issue and i will create a PR afterwards.

**Comment by alikon** [comment]
closing as we have a pr #43656
