### ISSUE TITLE
Please implement an input field for Matomo scriptcode (web analytics) in HTML Head of J5

### ISSUE THREAD

**Issue by sthopd** [joomla/joomla-cms#43621]
Hello,
Please make a webpage in the Admin Dashboard of Joomla5 (backend), where webmasters can enter script code for Web Analytics / Statistics, for example: code of Matomo 5.0 (https://matomo.org/) or Google Analytics 4.
The Javascript code of Matomo (or Google Analytics) must be punched into the Head-tag of every (frontend) web page of my site.
How can this be done with existing functionality?
Regards, Sthopd

**Comment by brianteeman** [comment]
https://matomo.org/faq/new-to-piwik/how-do-i-install-the-matomo-analytics-tracking-code-on-joomla/

**Comment by sthopd** [comment]
Thanks for the URL.
