### ISSUE TITLE
Special characters are transferred to the alias

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#43630]
### Steps to reproduce the problem
Create a menu item, e.g. ‘Allgäu cheese’

### Expected result
the alias is: allgaeuer-kaese--ein-traum

### Actual result
the alias is: «allgäuer-käse-–-ein-traum«

### System information (as far as possible)
j5.1.1

**Comment by brianteeman** [comment]
In global configuration - change unicode alias to no

![image](https://github.com/joomla/joomla-cms/assets/1296369/e5ef3561-feac-482c-9651-9df2269aa536)

**Comment by brianteeman** [comment]
Thank you, it was a pleasure to help you.
