### ISSUE TITLE
[5.1.1] Creating a child template of Cassiopeia produces two copies in Styles

### ISSUE THREAD

**Issue by Scrabble96** [joomla/joomla-cms#43632]
### Steps to reproduce the issue
Open Cassiopeia Details and Files and click the 'Create Child Template' button, name it, e.g. 'child' and select Cassiopeia as the template style to base it on.
Close Cassiopeia and then go to template styles

### Expected result
To see:
Cassiopeia - Default           (ID) 11
Cassiopeia_child - Default  (ID) 12

### Actual result

Screenshot:
![duplicate-J5-child-template-style](https://github.com/joomla/joomla-cms/assets/36987494/a7f794d1-0da2-4e0f-959a-bf9b876fff38)
### System information (as much as possible)
Joomla 5.1.1

### Additional comments
Which one should be deleted?

**Comment by chmst** [comment]
You have added the additionla style (copy of cassiopeia Default) to your child template. 
You can delete this additional style if you don't need it.

**Comment by dgrammatiko** [comment]
> Which one should be deleted?

- The `cassiopeia_child - Default` is the style **created** but the default values of the `templateDetails.xml`
- The `Cassiopeia_child, copy of Cassiopeia - Default` is an actual copy of the cassiopeia active settings, (with any changes reflected)

Usually you want the child template to inherit all the style changes of the parent, so if that's the case then delete the one with id=12. If you want to alter the child and you don't care for any of the parent settings (ie start from an empty slate) then delete id=13.

**Comment by Scrabble96** [comment]
Thank you, both.
