### ISSUE TITLE
Joomla Permissions Issue - Slow Performance and Timeouts with Non-Super Users

### ISSUE THREAD

**Issue by MayaSima** [joomla/joomla-cms#43649]
### Description:
I am experiencing performance issues with Joomla permissions on version 5.1.1. I created a group intended to have backend access, specifically to create or edit content. While everything works fine in general, accessing Content >> Articles is extremely slow and often times out or crashes the page. This issue arises when attempting to list articles. However, this problem does not occur when you log in as a Super User.

### Steps to Reproduce:
1.     Create a new user group with permissions to create or edit content.
2.     Log in as a user from this group.
3.     Navigate to Content >> Articles.

### Expected Result:
The articles list should load efficiently without significant delay or timeouts.

### Actual Result:
The page loads extremely slowly, often timing out and crashing.

### Debugging Information:
Using the Joomla debugging tool, we discovered that:
-     For non-Super Users, Joomla checks the asset table permissions for each article individually.
-     This behavior does not occur with Super Users.

###  Screenshot:
The attached screenshot shows a profile trace comparison:
-         Left: Profile trace of a Super User.
-         Right: Profile trace of a user with set permissions.

### Attachment
![Screenshot 2024-06-13 143030](https://github.com/joomla/joomla-cms/assets/13040479/05c7fdb2-ffd3-4f61-8a7a-71ddb6acd854)

### Question:
Can you confirm if this is a bug or native Joomla behavior?

### Environment:
-     Joomla Version: 5.1.1
-     Number of Articles: ~9000

### Additional Information:
The issue seems to be tied to how Joomla processes permissions for non-Super Users, causing a performance bottleneck when listing a large number of articles. Any insights or workarounds to alleviate this issue would be greatly appreciated.

**Comment by Fedik** [comment]
This happens because `Access::preloadPermissions()` preloads pemissions for ALL 9000 articles 
(which is around 90MB from your screenshot) 
https://github.com/joomla/joomla-cms/blob/2d99f3bb4b68688f71f6f915ceb715e51d969e19/libraries/src/Access/Access.php#L269

I set it as bug, however I have no idea how it can be fixed. 
But I can understand that it gives a really bad experience of use the content editing.

It probably for all Joomla versions. Cannot find older similar issue about it.

**Comment by Fedik** [comment]
> Any insights or workarounds to alleviate this issue would be greatly appreciated.

You can try hack the 
https://github.com/joomla/joomla-cms/blob/2d99f3bb4b68688f71f6f915ceb715e51d969e19/libraries/src/Access/Access.php#L155
And change ` $preload` to  `$preload = false`

However it is illegal. And I told you nothing, someone hacked my account. This message will self destroyed in few days :neckbeard:

**Comment by Fedik** [comment]
Okay, I think now instead one large DB query you get a few hundrets of small DB queries.

Another thing to try is to plreload only needed items, that in the current view.
Try, edit the articles list layout `administrator/components/com_content/tmpl/articles/default.php`
And place following code for preload, somewhere around line 70 (before the html rendering):
```php

$accessWorkAround = new class () extends \Joomla\CMS\Access\Access
{
    // Preload only needed items
    public static function verySmartPreload($assetType, $assetsList, $key = 'id')
    {
        $extensionName = self::getExtensionNameFromAsset($assetType);

        /** @var \Joomla\Database\Mysql\MysqlDriver $db */
        $db    = Factory::getContainer()->get(\Joomla\Database\DatabaseInterface::class);
        /** @var \Joomla\Database\Mysql\MysqlQuery $query */
        $query = $db->getQuery(true);
        $query->select($db->quoteName(['id', 'name', 'rules', 'parent_id']))
            ->from($db->quoteName('#__assets'))
            ->where(
                $db->quoteName($key) . ' IN ('
                . implode(',', $query->bindArray($assetsList, \Joomla\Database\ParameterType::STRING)) . ')'
            );

        $assets = $db->setQuery($query)->loadObjectList();

        foreach ($assets as $asset) {
            self::$assetPermissionsParentIdMapping[$extensionName][$asset->id] = $asset;
            self::$preloadedAssets[$asset->id]                                 = $asset->name;
        }

        // Temporary mark as preloaded
        self::$preloadedAssetTypes[$assetType] = true;
    }

    public static function resetVerySmartPreload($assetType)
    {
        unset(self::$preloadedAssetTypes[$assetType]);
    }
};
$assetsList = [];
foreach ($this->items as $item) {
    $assetsList[] = 'com_content.article.' . $item->id;

    if (!empty($item->catid)) {
        $assetsList[] = 'com_content.category.' . $item->catid;
    }
}

$accessWorkAround::verySmartPreload('com_content.article', $assetsList, 'name');
```

then at the end of the file:
```php
<?php $accessWorkAround::resetVerySmartPreload('com_content.article'); ?>
```
And please tell us if it help.
The editing form still will be slow, however the list view should be much faster.

**Comment by Fedik** [comment]
After some testing, I think the actual slowdown is somewhere in `‎ArticlesModel::getListQuery()` in the Administrator model https://github.com/joomla/joomla-cms/blob/50726beb7853340ae72458c6479a297988a8fb9e/administrator/components/com_content/src/Model/ArticlesModel.php#L232-L266

it takes a few seconds to load 20 articles from 40k on my test.
If I remove workflow Joins, it still more than a second. 
Interestingly `‎ArticlesModel::getListQuery()` in the Site model works much faster.
@richard67 do you have an idea what can be a bottleneck in this query?

Access preloading still preloads a lot, but it is doing it fast.

**Comment by Fedik** [comment]
It sems a few things: 
- workflow joins, 
- languages joins, 
- users joins, 
 
When I removing them, everything works much faster.

**Comment by Fedik** [comment]
Ah, it the same as https://github.com/joomla/joomla-cms/issues/43701 I missed it, sorry.

**Comment by richard67** [comment]
> @richard67 do you have an idea what can be a bottleneck in this query?

@Fedik No idea. Is already the part which you have linked (lines 232 to 266) so slow, without all that stuff which might be added later below? What I remember from some other issue is that it could be faster when changing the 3 inner joins to the workflow tables to left joins: https://github.com/joomla/joomla-cms/blob/50726beb7853340ae72458c6479a297988a8fb9e/administrator/components/com_content/src/Model/ArticlesModel.php#L264-L266

**Comment by richard67** [comment]
> Ah, it the same as #43701 I missed it, sorry.

@Fedik Yes, that's the one where I saw the thing with inner or left join for the workflow tables.

**Comment by Fedik** [comment]
Yea, with LEFT it 0.5s faster, but still slow in total :smile: 
Hmhm

it probably would be much smarter to split it to few queries:
load Articles,
load language data
load User data
load workflow data

Okay, maybe not that easy.

**Comment by brianteeman** [comment]
Kill workflow, problem solved :)

**Comment by Fedik** [comment]
> Kill workflow, problem solved

It is not only workflow

**Comment by brianteeman** [comment]
but it makes no sense to query workflow tables when its not being used.

**Comment by Fedik** [comment]
Issue with access check hopefully will be fixed in https://github.com/joomla/joomla-cms/pull/44078.
I close this issue for now. Thanks for reaport.
