### ISSUE TITLE
Info alert message and success button - need to fix the colour

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#43661]
### Steps to reproduce the issue

There is an alert message (alert alert-info) and success button whose colour is not nice.
Let's make it white.

Screenshot:
<img width="1113" alt="Снимок экрана 2024-06-16 в 00 01 14" src="https://github.com/joomla/joomla-cms/assets/3432048/86fa1bb5-27fc-481f-880d-1eb145739ba7">

The issue occurs due to  this rule:
```
.alert.alert-info a {
  color: var(--state-info-text);
}

```

### Expected result

The solution is to add an extra rule like  that:

`.alert.alert-info .btn-success a {color:#fff}
`
And we will get perfect result:
<img width="1118" alt="Снимок экрана 2024-06-16 в 00 04 38" src="https://github.com/joomla/joomla-cms/assets/3432048/b09fe1ad-f957-42a1-a231-7a450c1bcbb4">

Dark mode is OK.

### System information (as much as possible)
Joomla 5.1.1

**Comment by Quy** [comment]
Related #43708

**Comment by Quy** [comment]
Closing as duplicate.
