### ISSUE TITLE
TasksListCommand 'Next Run' incorrect and deprecated warning DateTime

### ISSUE THREAD

**Issue by brbrbr** [joomla/joomla-cms#43665]
### Steps to reproduce the issue

Create a scheduled task with Execution Rule on Manual
execute the command line scheduler:list 

### Expected result

Table with 'Next run' for above task set to Never

### Actual result

'Next run' set to 'DUE!'
PHP Deprecated:  DateTime::__construct(): Passing null to parameter #1 ($datetime) of type string is deprecated in libraries/src/Date/Date.php 

The deprecated warning also shows in the Tasks view when a task crashed.

### System information (as much as possible)

joomla 5.1 
php 8.3

### Additional comments

As a site note, The Captions 'Test Task' and 'Run Test' in the Tasks view is a kind of misleading.

It suggests a kind of dry run, while the tasks are actually executed. So 'Run Task' and 'Run' would be more appropriate.

**Comment by alikon** [comment]
please test #43750 for the cli part

**Comment by Quy** [comment]
> As a site note, The Captions 'Test Task' and 'Run Test' in the Tasks view is a kind of misleading.
> 
> It suggests a kind of dry run, while the tasks are actually executed. So 'Run Task' and 'Run' would be more appropriate.

Please test PR  #36725.

**Comment by brbrbr** [comment]
> > As a site note, The Captions 'Test Task' and 'Run Test' in the Tasks view is a kind of misleading.
> > It suggests a kind of dry run, while the tasks are actually executed. So 'Run Task' and 'Run' would be more appropriate.
> 
> PR #36725.

That PR seams a bit broken.
