### ISSUE TITLE
Field Groups - search by ID:

### ISSUE THREAD

**Issue by robertparts** [joomla/joomla-cms#43679]
### Steps to reproduce the issue
Field Groups 
Give to search field ID:5

### Expected result
Find a row with id 5

### Actual result
An error has occurred.
0 Cannot use positional argument after named argument

Open "Field Groups" again - same error (and no any group to show)
### System information (as much as possible)
PHP 8.1
Joomla 5.1.1

### Additional comments
error	Uncaught Throwable of type Error thrown with message "Cannot use positional argument after named argument". Stack trace: #0 [ROOT]/libraries/vendor/joomla/database/src/DatabaseDriver.php(651): Joomla\Database\Mysqli\MysqliStatement->execute()
#1 [ROOT]/libraries/vendor/joomla/database/src/DatabaseDriver.php(1304): Joomla\Database\DatabaseDriver->execute()
#2 [ROOT]/libraries/src/MVC/Model/BaseDatabaseModel.php(164): Joomla\Database\DatabaseDriver->loadObjectList()
#3 [ROOT]/administrator/components/com_fields/src/Model/GroupsModel.php(230): Joomla\CMS\MVC\Model\BaseDatabaseModel->_getList()
#4 [ROOT]/libraries/src/MVC/Model/ListModel.php(271): Joomla\Component\Fields\Administrator\Model\GroupsModel->_getList()
#5 [ROOT]/libraries/src/MVC/View/AbstractView.php(159): Joomla\CMS\MVC\Model\ListModel->getItems()
#6 [ROOT]/administrator/components/com_fields/src/View/Groups/HtmlView.php(87): Joomla\CMS\MVC\View\AbstractView->get()
#7 [ROOT]/libraries/src/MVC/Controller/BaseController.php(697): Joomla\Component\Fields\Administrator\View\Groups\HtmlView->display()
#8 [ROOT]/administrator/components/com_fields/src/Controller/DisplayController.php(69): Joomla\CMS\MVC\Controller\BaseController->display()
#9 [ROOT]/libraries/src/MVC/Controller/BaseController.php(730): Joomla\Component\Fields\Administrator\Controller\DisplayController->display()
#10 [ROOT]/libraries/src/Dispatcher/ComponentDispatcher.php(143): Joomla\CMS\MVC\Controller\BaseController->execute()
#11 [ROOT]/libraries/src/Component/ComponentHelper.php(361): Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch()
#12 [ROOT]/libraries/src/Application/AdministratorApplication.php(150): Joomla\CMS\Component\ComponentHelper::renderComponent()
#13 [ROOT]/libraries/src/Application/AdministratorApplication.php(195): Joomla\CMS\Application\AdministratorApplication->dispatch()
#14 [ROOT]/libraries/src/Application/CMSApplication.php(306): Joomla\CMS\Application\AdministratorApplication->doExecute()
#15 [ROOT]/administrator/includes/app.php(58): Joomla\CMS\Application\CMSApplication->execute()
#16 [ROOT]/administrator/index.php(32): require_once('...')
#17 {main}

**Comment by chmst** [comment]
Please test #43774.
