### ISSUE TITLE
  success / message not mapped to SymfonyStyle in ConsoleApplication

### ISSUE THREAD

**Issue by brbrbr** [joomla/joomla-cms#43683]
### Steps to reproduce the issue

enqueueMessage a message with type success or message in a CLI application

### Expected result

message displayed as success in bright green

### Actual result

message displayed as comment

### Additional comments

CMSApplicationInterface::MSG_SUCCESS is not defined at all. 

layouts/joomla/system/message.php does not map MSG_SUCCESS  but here it work as the $type itself  is used as fallback.

the $methodmap in ConsoleApplication::doExecute does not map 'success' nor 'message'

I have an installer script using enqueueMessage , would be nice to have the information colored in the CLI as well.

**Comment by alikon** [comment]
you can do like this

https://github.com/joomla/joomla-cms/blob/dd08e285b4fb22a627ddfe2b7f5b5037875f5ea6/libraries/src/Console/AddUserCommand.php#L175

**Comment by brbrbr** [comment]
I'm looking at scripts that are designed to run in the Administror/Site Applications using enqueuMesage. In this case installation scripts.

The method ConsoleApplication::doExecute maps the types in the message queue to SymfonyStyle methods, however the methodMap is incomplete (compared to the joomla.system.message layout) and missing the success and message types.

I could rewrite my own installation scripts to distinguish between a Console and Administrator application, however, I do not control other packages. And ConsoleApplication::doExecute is designed to do the work for me.

**Comment by alikon** [comment]
closing as we have a pr #43688
