### ISSUE TITLE
Smart search content map status resets

### ISSUE THREAD

**Issue by bassmanpaul** [joomla/joomla-cms#43681]
When using the smart search component under the content maps we have one category (News) unpublished in order to prevent news articles from appearing in the search. However, when you create a new article in the news category it re-enables the News category in the content map. Surely, this defeats the purpose of being able to publish/unpublish content map items if they just get republished automatically? Is this a bug or standard behaviour?

### Steps to reproduce the issue

1. Unpublish a category in Smart Search / Content Maps.
2. Create a new article and assign to category.
3. Go back and refresh Content Maps.

### Expected result

The category should remain disabled to prevent indexing of articles in that category.

### Actual result

The category is re-enabled and the newly created article has been indexed.

### System information (as much as possible)

Joomla 4.4.5

**Comment by Hackwar** [comment]
This has been fixed in Joomla 5.0, so please update to the latest 5.x version. We will not fix this in 4.x.
