### ISSUE TITLE
J 4.x.x + - Add an unique id to fields table

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#43707]
### Is your feature request related to a problem? Please describe.
Yes If I want to perform database operations on the fields table I run always into issues because there is no unique id for each record. I am not able to to quick changes in the database or perform a complicated value update if something is wrong there.

### Describe the solution you'd like
Add column with unique id

**Comment by HLeithner** [comment]
I'm closing this here and collect it in #43709 also we don't collect feature requests anymore in issues
