### ISSUE TITLE
[5.2] SEO: Schema.org - global options / prefill

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#43711]
Joomla's default schema.org functionality is a great tool that improves SEO with structured data. 
However, manually adding it to each article is quite some work.

![Image](https://github.com/joomla/joomla-cms/assets/1217850/dec87f26-9a80-4dd2-a211-6510f2ce4235)

Could we automate this process a bit:

1. Add a button to **auto-populate** the **schema fields** from **existing data** from the **article**. 
Like the headline from the title, the image from the intro image, and the publication date from the Published Up field.
2. Add an option to **apply "global" category settings** on the articles in that category.

Such improvements would improve the workflow save a lot of time!

**Comment by felixkat** [comment]
> Add a button to auto-populate the schema fields from existing data from the article.
> Like the headline from the title, the image from the intro image, and the publication date from the Published Up field.

Maybe the possibility of doing this in batch across all articles or article by category?


Is the #___schemaorg table the only reference table?  Is it safe to manually populate the table using data from #___content?

**Comment by uglyeoin** [comment]
This is closed.  Did it get implemented @pe7er ?
