### ISSUE TITLE
redis cache deletes ALL session keys

### ISSUE THREAD

**Issue by yossibeck** [joomla/joomla-cms#43718]
in this file 
libraries/src/Cache/Storage/RedisStorage.php

### Steps to reproduce the issue

1. setup a redis server
2. define that server as a cache_handler + session_handler 
3. use the same server for redis_server_host + session_redis_server_host
4. start caching stuff - and login 
on the first delete of a non group cache - you'll lose all of your sessions 
the easiest way to do that is to connect to redis with 
````
redis-cli -h <host name>
HOST-NAME:PORT>monitor
````
and you'll see after a while these commands:
````
HOST-NAME:PORT>KEYS "*"
HOST-NAME:PORT>DEL <session-id 1>
HOST-NAME:PORT>DEL <session-id 2>
HOST-NAME:PORT>DEL <session-id 3>
....
````

### Expected result
only *-cache-* keys should be deleted 

### Actual result
all keys are deleted from the server 

### Additional comments
if we set TTL - why do we even need the code going and deleting the keys ?

**Comment by richard67** [comment]
Closing as having a pull request. See #43719 .

@yossibeck In case if you are not familiar yet with our practice: We close an issue when there is a PR to solve it. That's different to how some other repositories handle it. And if you want to open an issue and already know you will solve it with a PR, it does not even need the issue. Just the PR is sufficient in that case.

Thanks for reporting the issue and creating this PR.

**Comment by yossibeck** [comment]
@richard67 - thanks for clarifying 
the only reason I see for this issue is this question:
_if we set TTL - why do we even need the code going and deleting the keys ?_

**Comment by richard67** [comment]
> @richard67 - thanks for clarifying the only reason I see for this issue is this question: _if we set TTL - why do we even need the code going and deleting the keys ?_

@yossibeck Well, if it is just a question then the right place would be in [discussions](https://github.com/joomla/joomla-cms/discussions).
