### ISSUE TITLE
I sent a security vuln report through the contact form & security@joomla.org but got not response after 7 days

### ISSUE THREAD

**Issue by mwaraem** [joomla/joomla-cms#43710]
### Steps to reproduce the issue
I'm a security researcher working with a security company. I've recently discovered a vulnerability in the Joomla! CMS framework and reported to both security@joomla.org and the form presented at the security strike team page. My email address is mwaraem@gmail.com and I confirm I tested the CMS on version 5.1.1

### Expected result
Hopefully I can get in touch with the security steam and get some response to the report

**Comment by HLeithner** [comment]
@mwaraem thanks for contacting us, it seems we had some troubles with our ticketing system. We solved this now and will comeback to you shortly.

I'm closing this issue since we received your message now
