### ISSUE TITLE
[4.4] The total number of votes is not (never) visible.

### ISSUE THREAD

**Issue by sandewt** [joomla/joomla-cms#43728]
### Steps to reproduce the issue

Enable the vote plugin and show the total number of votes (param setting)

### Expected result

The total number of votes is visible, after setting the relevant parameter

### Actual result

The total number of votes is NOT visible, after setting the relevant parameter

### System information (as much as possible)

Joomla 4.4.4

### Additional comments

PR #42934 is the cause, because class="visually-hidden"

**Comment by Quy** [comment]
Please test #43740. Thanks.
