### ISSUE TITLE
Joomla! Project plugin "CAPTCHA - invisible reCAPTCHA" version 3.8 doesn't work

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#43721]
Our website runs Joomla 5.1.0 and we use invisible reCAPTCHA for a user form. In the Joomla! Project plugin "CAPTCHA - invisible reCAPTCHA" version 3.8, I introduced the proper Google reCAPTCHA v3 codes. And everything seemed to work fine. During the second half of may, numerous "attacks" on our user form happened. I could see that, using the Google reCAPTCHA graphical visualisation of the attacks. There I saw numerous "attacks" having scores of 0,1 (this points to high risk users of the form). BUT, these "attacks" were NOT stopped by reCAPTCHA! So we ended up with numerous junk mails. I tried to see where I misconfigured the plugin or where I could set a threshold for the score (e.g. 0,5), but I didn't find it.
So I turned to a third-party plugin, the SharkyKZ plugin "Captcha - reCAPTCHA v3" version 1.1.1. In this plugin a threshold value for the score can be added. I added 0,5.
And a couple of days ago, we again had two "attacks". And this time, both of them were stopped by reCAPTCHA.
So I came to the conclusion that the default Joomla! Project plugin "CAPTCHA - invisible reCAPTCHA" version 3.8 DOES NOT DO THE JOB! Or am I not using it properly?

**Comment by Fedik** [comment]
That correct, the older reCAPTCHA from Google does not always protect from spam. And it was removed from Joomla 5.
reCAPTCHA v3 is better, however Joomla does not rely on 3d services anymore, and do not provide plugin for it.

**Comment by Omroepmuseum** [comment]
About "... do not provide plugin for it". In our Joomla we do have a plugin "CAPTCHA - onzichtbare reCAPTCHA" (Dutch) version 3.8 from Joomla! Project. That's the one using Google reCAPTCHA v3 but NOT doing the job!
So, why do I see thie plugin. Last update for this plugin was 01-11-2017!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43721">issues.joomla.org/tracker/joomla-cms/43721</a>.</sub>

**Comment by Fedik** [comment]
idk, Joomla never had  reCAPTCHA v3 in core.
the invisible reCAPTCHA stays If you made upgrade from 3.8.
