### ISSUE TITLE
htaccess - Options +FollowSymLinks

### ISSUE THREAD

**Issue by sinahaghparast** [joomla/joomla-cms#43737]
### Problem identified
In .htaccess file "Options +FollowSymLinks" in some servers not OK...

### Proposed solution
Be using "Options +SymLinksIfOwnerMatch" instead of "Options +FollowSymLinks"

### Open questions
Can I change htaccess.txt file in 5.2 branch?

**Comment by richard67** [comment]
There is already a pull request for the 4.4-dev branch: #43005

**Comment by brianteeman** [comment]
as there is a PR already shouldnt this be closed?

**Comment by richard67** [comment]
> as there is a PR already shouldnt this be closed?

@brianteeman I’m not sure in this case. The comments in the PR look as if it is subject of a discussion if it shall be done or not. If course if the PR is still actual and not abandoned the issue can be closed.
