### ISSUE TITLE
[5.1] CLI Update channel

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#43732]
Use the cli to set the joomla update channel
You have FOUR choices as shown in the error message when you get it wrong
[default, next, testing, custom]
![image](https://github.com/joomla/joomla-cms/assets/1296369/1cfdb0a7-10bd-45f6-8b3a-4115a15d305b)

If you try to change the joomla update channel to any of those 4 choices then you will get a success message and when you use the cli to check which channel you are on it will confirm your choice

![image](https://github.com/joomla/joomla-cms/assets/1296369/3f9cac42-2443-48a9-8c07-1920729046d0)

However there are only three possible update channels now since the testing channel was removed #43147 from the web interface but the code is still present in the console `libraries\src\Console\CheckJoomlaUpdatesCommand.php`

You should not be able to successfully set the update channel to testing from the CLI but it appears that you can

![image](https://github.com/joomla/joomla-cms/assets/1296369/615ed68a-0f6e-4f30-b4ab-e4eab94a72a0)

**Comment by richard67** [comment]
Closing as having a pull request. Please test #43764 . Thanks in advance.
