### ISSUE TITLE
[5.1] Email cloaking inactive in search index results  - com_finder

### ISSUE THREAD

**Issue by ChristineWk** [joomla/joomla-cms#43749]
### Steps to reproduce the issue
E-mail addresses are not obfuscated in the index search results 

### Actual result
From Forum.de example:
https://forum.joomla.de/thread/21208-e-mail-verschleierung-inaktiv-in-ergebnissen-des-suchindex/?postID=156388#post156388
Thank you.

**Comment by ChristineWk** [comment]
Since the links may be provided by the thread creator, in addition:

Correct cloaking: https://musiktage-salzgitter.de/impressum.html

No cloaking: https://musiktage-salzgitter.de/component/finder/search.html?q=thomas&Itemid=101<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43749">issues.joomla.org/tracker/joomla-cms/43749</a>.</sub>

**Comment by SniperSister** [comment]
See #44641
