### ISSUE TITLE
[5.1.2rc] package-lock

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#43743]
The version in package,json should match the version in package-lock.json

https://github.com/joomla/joomla-cms/blob/0c045c2fb0ae10e175f6bc7c462adc0f2fef083f/package.json#L3

https://github.com/joomla/joomla-cms/blob/0c045c2fb0ae10e175f6bc7c462adc0f2fef083f/package-lock.json#L3

**Comment by brianteeman** [comment]
RC2 has now been released with the same error

**Comment by brianteeman** [comment]
why do we bother to test and report things

**Comment by rdeutz** [comment]
It's not an error. The lock file is changed when we do package updates, obviously this wasn't the case for 5.1.2. Another situation when the lock file is updated is when a package is published. We are not doing this and it is not needed.

We could delete the file and make npn install, that would create a new lock file with the current joomla version. Or we delete the version from package.json, it is not really needed. We will discuss this at the next Maintainers Meeting.

**Comment by brianteeman** [comment]
clearly you are incorrect Robert or it would not have been silently updated

https://github.com/joomla/joomla-cms/blob/2b28735195558a397b239cb45f6518fdd3f2b9c3/package-lock.json#L3

**Comment by LadySolveig** [comment]
Just for you, to make you happy 🫶 @brianteeman

**Comment by rdeutz** [comment]
> clearly you are incorrect Robert or it would not have been silently updated

no I am not, anything I have written was correct

**Comment by brianteeman** [comment]
> Just for you, to make you happy 🫶 @brianteeman

thank you.
