### ISSUE TITLE
Joomla 5.1.2-rc2 in default channel

### ISSUE THREAD

**Issue by BaeFell** [joomla/joomla-cms#43756]
### Steps to reproduce the issue

Check for updates on a Joomla site running Joomla 5.1.1 in the default channel

### Expected result

No Joomla updates

### Actual result

Joomla 5.1.2-rc2 is available for download

**Comment by brianteeman** [comment]
same here

**Comment by jjnxpct** [comment]
Yes I noticed this as well....

**Comment by richard67** [comment]
The issue has been fixed meanwhile. There was a mistake (wrong "stability" tag) on the update site. To get rid of the cached update in database you may go to the extensions manager and use the button to check for updates. This will also clear the update to Joomla 5.1.2-rc2 from database.

Please check and report back.

Thanks in advance.

**Comment by BaeFell** [comment]
> The issue has been fixed meanwhile. There was a mistake (wrong "stability" tag) on the update site. To get rid of the cached update in database you may go to the extensions manager and use the button to check for updates. This will also clear the update to Joomla 5.1.2-rc2 from database.
> 
> Please check and report back.
> 
> Thanks in advance.

That worked! Thank you very much!

**Comment by richard67** [comment]
Thanks for reporting back.

**Comment by webeznet** [comment]
That did not work for me because the Joomla! (5.1.2-rc2) upgrade was already applied to my site, how to i get it back to a stable version? or do i just wait for new upgrade? why is there no new upgrade to fix this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43756">issues.joomla.org/tracker/joomla-cms/43756</a>.</sub>

**Comment by richard67** [comment]
> That did not work for me because the Joomla! (5.1.2-rc2) upgrade was already applied to my site, how to i get it back to a stable version? or do i just wait for new upgrade?

Joomla does not do automated updates. So if your site has been updated it eas your deliberate decision.

Tonight the stable 5.1.2 will be released. Joomla will find it and offer it in the backend. You update to that and you are back in the stable track.

> why is there no new upgrade to fix this?

Sorry,  it if you have decided to do the update and have not made a backup before then Joomla can’t fix that for you.

**Comment by webeznet** [comment]
Understood, that makes total sense, thank you. I did do the upgrade from watchful and I was not paying attention to the upgrade version, so defiantly my fault for running the upgrade. I was assuming Joomla had the correct upgrade path set.. And i do have a back up every night so i could have restored, just would rather push forward.. thanks so much for clarifying...
