### ISSUE TITLE
If modules with loadmoduleid and loadposition have been inserted into a post, "Edit" of the post can no longer be opened in the frontend

### ISSUE THREAD

**Issue by WM-Loose** [joomla/joomla-cms#43768]
### Steps to reproduce the issue
Set in an article loadposition or loadmoduleid

### Expected result
open the article in frontend

### Actual result
the article can no longer be opened and edited in the frontend

### System information (as much as possible)
J5.1.2
PHP8.3
DB: 10.5.25-MariaDB

**Comment by WM-Loose** [comment]
Joomla 4 works fine

**Comment by chmst** [comment]
Cannot replicate in J5. Which extension are installed and used?

**Comment by WM-Loose** [comment]
UIKIT Plugins an templates from joomlaplates but we are testing in the moment and later, we sent more informations.

**Comment by WM-Loose** [comment]
The error suddenly no longer appears and can no longer be reproduced. We have never experienced anything like this before. 
I am closing the error, which cannot have anything to do with Joomla.
