### ISSUE TITLE
[5.1] Fancy-select hidden inside Subfom field

### ISSUE THREAD

**Issue by sakiss** [joomla/joomla-cms#43769]
### Steps to reproduce the issue
Create a subform field and use a fancy-select inside it.

The code is used is:
```
 <field
                    name="sorting_rules"
                    type="subform"
                    label="Sorting rules"
                    layout="joomla.form.field.subform.repeatable-table"
                    icon="list"
                    multiple="true"
            >
                <form hidden="true" name="list_sorting_rules" repeat="true">
                    <field
                            name="name"
                            type="list"
                            label="Select"
                            multiple="false"
                            layout="joomla.form.field.list-fancy-select"
                            required="true"
                    >
                            <option value="a">A</option>
                            <option value="b">B</option>
                            <option value="c">C</option>
                            <option value="d">D</option>
                            <option value="e">E</option>
                    </field>
                </form>
            </field>
```
You can inject that in any component's `config.xml `  or a menu item's xml to check it.

### Expected result
The drop-down options to be visible.

### Actual result
Not visible
![fancy-select-subform](https://github.com/joomla/joomla-cms/assets/1838041/00a6dac1-4e88-4ee9-be47-159c296aa90f)

### System information (as much as possible)
Joomla 5.1.2

**Comment by Quy** [comment]
Duplicate #38346?

**Comment by Fedik** [comment]
yes, it is duplicate.
and there is no way to fix it with table layout, 
you can test new grid layout https://github.com/joomla/joomla-cms/pull/42347

thanks

**Comment by sakiss** [comment]
For anyone facing the same, it happens only with the `repeatable-table` layout.
You can change the subform field layout to `joomla.form.field.subform.repeatable` and it will work. Though with a bit different look and feel.
Also you can try #42347 as mentioned above.
