### ISSUE TITLE
Joomla_5.1.2-Stable-Full_Package.tar.gz seems double-gzipped

### ISSUE THREAD

**Issue by jschleus** [joomla/joomla-cms#43785]
I downloaed the gzipped tarball

https://downloads.joomla.org/cms/joomla5/5-1-2/Joomla_5-1-2-Stable-Full_Package.tar.gz?format=gz

but it seems that the file has a problem since the original tarball has been probably gzipped twice:

OK, the MD5 sum of the downloaded file is identical to that on the webpage:
&nbsp;&nbsp;6d48da7c15be52ac7b5710b1baaa5f3f  Joomla_5.1.2-Stable-Full_Package.tar.gz

The file size is 24053891 bytes and the "file" command says:
&nbsp;&nbsp;gzip compressed data

But executing "gunzip" on that file the file size is unexpectedly only slightly increased (now 24055717 bytes) and the "file" command says still:
&nbsp;&nbsp;gzip compressed data

But renaming the new tar file to tar.gz and executing "gunzip" again creates now as expected a much larger
file (89016320 bytes) and the "file" command says now as expected:
&nbsp;&nbsp;POSIX tar archive (GNU)
 
Jens

**Comment by felixkat** [comment]
I can confirm:-

**Joomla_5.1.2-Stable-Full_Package.tar.gz** contains **Joomla_5.1.2-Stable-Full_Package.tar** which is gzip despite the tar extension. 

Within **Joomla_5.1.2-Stable-Full_Package.tar** is **Joomla_5.1.2-Stable-Full_Package** (no extension) which is a tar file.

**Comment by HLeithner** [comment]
Sorry that it took so long, fixed it now.
