### ISSUE TITLE
Cassiopeia Colour Themes

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#43799]
Cassiopeia Colours

The cassiopeia template ships with two colour themes

- build\media_source\templates\site\cassiopeia\scss\global\colors_alternative.scss
- build\media_source\templates\site\cassiopeia\scss\global\colors_standard.scss

I can't determine exactly why they were created in this way but I would assume that the variables in these schemes would be sufficient to completely override the bootstrap colours.

However that this not the case as they only change some parts but not all.

An easy example is to look at a primary button when using the alternative colour theme where it is clear that the active state is not correct.

### Normal

![image](https://github.com/user-attachments/assets/fb1c08d4-0586-453a-834e-459cef79e646)

### Hover

![image](https://github.com/user-attachments/assets/c4c6e4bb-70de-4fa2-86db-3b309367827c)

### Active

![image](https://github.com/user-attachments/assets/c480cb76-b127-415e-96c2-a2ab1ada2d2f)

## Moving Forward

My non-css expert eye says that we are setting the variables wrong and instead of creating --cassiopeia-* variables we should be using the Bootstrap color system (https://getbootstrap.com/docs/5.3/customize/color/) - maybe we are not using that as that is newer to bootstrap than when cassiopeia was created.

Is this something we should address now - or would it be considered to be a b/c break that would have to wait for Joomla 6 where we can completely re-assess the way that we are customising bootstrap?

**Comment by dgrammatiko** [comment]
The reason is that bootstrap uses `--bs-name-of-the-variable` but Joomla is using `--name-of-the-variable`, there was an issue: https://github.com/joomla/joomla-cms/issues/42074

> Is this something we should address now

The sort answer is yes but it needs some work

**Comment by chmst** [comment]
It is something we should address and I also think that this needs some work. Is it possile to make it compatible with cassiopeia and child templates in existing installations?

**Comment by brianteeman** [comment]
@chmst I reported this as a bug not a feature

**Comment by chmst** [comment]
For me it is not a bug - it does not affect the usage of Joomla. As you said, fixing this now is a band-aid. It should be seen in a bigger context for improvement of the whole frontend template and be planned also with release managers.

**Comment by brianteeman** [comment]
whatever - guess it will go in the do nothing pile so I am closing it
