### ISSUE TITLE
Error in microdata after updating to Joomla! 5.1.2 Stable

### ISSUE THREAD

**Issue by Slava287** [joomla/joomla-cms#43797]
### Steps to reproduce the issue
Open any page of the material where the standard rating is enabled. Check the page via: https://search.google.com  Micro markup for Product rating has appeared.

### Expected result
Product markup should not appear

### Actual result
https://search.google.com/test/rich-results/result/r%2Fproduct?id=Kue1LLBJ8JpysM_LInStSw&hl=en
![2024-07-16_183241](https://github.com/user-attachments/assets/a8218a99-8acb-4ffa-90f1-55fb3543d609)

### System information (as much as possible)
PHP 8.3.1 Apache
Joomla! 5.1.2 Stable

**Comment by Quy** [comment]
Upgraded from which Joomla version? So this was not an issue before v5.1.2?

**Comment by Slava287** [comment]
That's right, in the previous version there was no such problem. Joomla 5.1.1

**Comment by Quy** [comment]
I don't see anything in [5.1.2 changelog](https://github.com/joomla/joomla-cms/milestone/127?closed=1) that could have caused this. I don't fully understand the issue you are referring to. Please elaborate further. Thanks.

**Comment by Slava287** [comment]
https://test.recepty.mobi/kulinarnye-sovety/kak-varit-kukuruznuyu-krupu.html

https://search.google.com/test/rich-results/result?id=Fs2g5njbrveI-j5m-O0LzQ&hl=en

![2024-07-22_200612](https://github.com/user-attachments/assets/8e6a5323-298e-429d-b49a-3c73c3ede288)

I can roll back to the previous version of joomla and you will see that there will be no such micro markup. There is this problem when displaying the rating

**Comment by Fedik** [comment]
@Slava287 It is called microdata
@Quy I think this one https://github.com/joomla/joomla-cms/pull/42934

**Comment by Fedik** [comment]
I think that PR need to revert

**Comment by Quy** [comment]
@conseilgouz Your input please.

**Comment by Quy** [comment]
Please test #43827. Thanks.
