### ISSUE TITLE
Joomla 4.4.6+ Hide Add module if not enough rights

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#43798]
### Steps to reproduce the issue
1) Create a backend Admin group that has no rights to add a backend module
2) The Button to create a module is shown
<img width="623" alt="grafik" src="https://github.com/user-attachments/assets/9846e9e1-38b3-4c8d-8beb-2f6745c38565">

3) When you click on it this error appears
<img width="796" alt="grafik" src="https://github.com/user-attachments/assets/341bd5ba-2aef-40dd-bdb4-1d9817a420f7">

### Expected result
The button should not be shown

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/42467

**Comment by coolcat-creations** [comment]
oops thanks!
