### ISSUE TITLE
[5.1.2] Using radio buttons with the "switcher" layout produces a JavaScript error in subforms

### ISSUE THREAD

**Issue by mattelkins-bluefrontier** [joomla/joomla-cms#43800]
### Steps to reproduce the issue

1. Add the following subform to a form:

```
<field
    name="switcher_test_subform"
    type="subform"
    label="Switcher Test"
    multiple="true"
    layout="joomla.form.field.subform.repeatable">
    <form>
        <fieldset>
            <field
                name="switcher_test"
                type="radio"
                label="Switcher Test"
                layout="joomla.form.field.radio.switcher"
                default="0"
                >
                <option value="0">JNO</option>
                <option value="1">JYES</option>
            </field>
        </fieldset>
    </form>
</field>
```

2. Access the form and click + to add a subform item.

### Expected result

The subform item is created and added to the subform.

### Actual result

The subform item is created and added to the subform, but the following JavaScript error occurs, which interferes with any other JavaScript attempting to run.

```
TypeError: Cannot read properties of null (reading 'nodeName')
    at joomla-field-subform.js?25ff4b:305:31
    at Array.forEach (<anonymous>)
    at JoomlaFieldSubform.fixUniqueAttributes (joomla-field-subform.js?25ff4b:263:14)
    at JoomlaFieldSubform.addRow (joomla-field-subform.js?25ff4b:195:10)
    at JoomlaFieldSubform.<anonymous> (joomla-field-subform.js?25ff4b:95:16)
```

(Error trace taken with debug mode enabled.)

### System information (as much as possible)

Joomla 5.1.2
PHP 8.3.8

**Comment by Fedik** [comment]
For note: the bug caused as result of fixing another bug :smile: 
- https://github.com/joomla/joomla-cms/pull/43660

**Comment by richard67** [comment]
Closing as having a pull request. See #43804 .

**Comment by sakiss** [comment]
I confirm that as well
