### ISSUE TITLE
Add Development Container Configuration and GitHub Codespace Support

### ISSUE THREAD

**Issue by alebak** [joomla/joomla-cms#43802]
### Is your feature request related to a problem? Please describe.

As a developer, setting up a local development environment for Joomla! can be time-consuming and prone to configuration issues. This can discourage new contributors and slow down the development process.

### Describe the solution you'd like

I propose adding a development container configuration and GitHub Codespace support for the Joomla! project. This feature would enable developers to quickly spin up a pre-configured development environment with all the necessary tools and dependencies. Similar functionality is already available in projects like [WordPress](https://github.com/WordPress/wordpress-develop/), making it easier for developers to contribute and streamline the development workflow.

### Additional context

- Reduce the time and effort required to set up a local development environment.
- Ensure consistency in development environments across different contributors.
- Lower the barrier to entry for new developers wanting to contribute to Joomla.
- Improve the overall development experience and productivity.

Thank you for considering this feature request.

**Comment by brianteeman** [comment]
We do have docker containers available https://hub.docker.com/_/joomla

**Comment by alebak** [comment]
Hello @brianteeman!

It is not the same. The concept of 'Development Containers' goes beyond a simple Docker image and makes it easier for the developer to have his IDE configured, even, without the need to install additional applications or tools.!

It's not the same thing. The concept of [Development Containers](https://containers.dev/) goes further and is much more powerful than a simple Docker image and makes it easier for the developer to have his IDE configured, even, without the need to install additional applications or tools.

**Comment by brianteeman** [comment]
I am aware it is not the exact same thing

**Comment by Hackwar** [comment]
Looks interesting. Would you be willing to work on that?

**Comment by alebak** [comment]
Hi @Hackwar, 

I am going to try to send PR using the Wordpress devcontainer as a sample.

**Comment by Hackwar** [comment]
Thank you.

**Comment by richard67** [comment]
Closing as having a pull request. See #44128 .
