### ISSUE TITLE
Custom Fields | Display description in the admin

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#43805]
### Steps to reproduce the problem
* Create a custom field, e.g. a text field
* Add a description

### Expected result
The description is displayed in the admin below the field.

### Actual result
The description is not displayed in the admin.

**Comment by brianteeman** [comment]
![image](https://github.com/user-attachments/assets/918eead9-c40e-42c3-a456-d12492feffcd)

**Comment by hytsch** [comment]
Thanks for the tip. A difference to J4 that I hadn't realised. - Is there a way to show these descriptions by default so that the content managers don't have to search for them?

**Comment by brianteeman** [comment]
No there is not

**Comment by hytsch** [comment]
I should certainly have read more about the differences between j4 and j5 - but I wouldn't have looked here... - The purpose of this new functionality is not entirely clear to me, but I do see problems with content managers who can no longer find the old familiar information. - 
Would a feature request that switches off this new functionality and displays the description of a field in the ‘classic’ way have any chance? What do you think?

**Comment by brianteeman** [comment]
Joomla 4 was released **Aug 17, 2021 ** with descriptions always displayed below the field 
Joomla 4.1 was released ** Feb 15, 2022** with descriptions displayed when toggled

**Comment by Quy** [comment]
Closing as related to #39545
