### ISSUE TITLE
[5.1] cli installation

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#43807]
### Steps to reproduce the issue
download and extract joomla5.1.2 in a new folder
at the command line try to install joomla interactively

`php installation/joomla.php install`

### Expected result
Installation Complete

### Actual result
Error as soon as you get asked for the admin password question and you are stuck in a loop

`Deprecated: rtrim(): Passing null to parameter #1 ($string) of type string is deprecated in \libraries\vendor\symfony\console\Helper\QuestionHelper.php on line 427`

![image](https://github.com/user-attachments/assets/03a4d956-02f2-435a-9fa8-00310919f5cc)

### System information (as much as possible)
php 8.2.16

**Comment by brianteeman** [comment]
ignore the deprecation comment the first part of the error is 
The system cannot find the path specified

**Comment by brianteeman** [comment]
further debugging and it only happens when in interactive mode on the admin and db passwords. When it is in non-interactive mode there is no problem and the message #"The system cannot find the path specified" is never displayed

**Comment by brianteeman** [comment]
I saw in another PR you wrote that you have found another issue in the installer - was it this
https://github.com/joomla/joomla-cms/pull/41213#issuecomment-1646963539

**Comment by HLeithner** [comment]
It's a bit hard to debug since I can't replicate the issue, also the error messages is a php native error message... so I'm not sure which path it's searching for...
