### ISSUE TITLE
Tags | Batch function incomplete

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#43806]
### Steps to reproduce the problem
* Create multiple tags, tag A, tag B, tag C.
* Try to subordinate tags B and C under the main tag A and proceed in the same way as for articles: select tags B and C, choose the batch function

### Expected result
The batch function offers the option of moving several tags under another in the dialogue.

### Actual result
This option is not available

### Additional comments
Whether we structure posts hierarchically in categories, MenuItems or tags is the same for a user. The batch function should therefore always offer this function, just as it does for articles, categories and menu items.

**Comment by Quy** [comment]
Please check if #41927 solves this issue. Thanks.

**Comment by Quy** [comment]
Please test PR #41927.
