### ISSUE TITLE
Timing Featuring an Article (Start featured) does not work

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#43816]
### Steps to reproduce the problem
Set the publication date ‘Start Featured’ and save the post

### Expected result
The publication date ‘Start Featured’ is saved.

### Actual result
The publication date ‘Start Featured’ is not saved - the database field remains empty.

**Comment by brianteeman** [comment]
Please search before posting - especially when it was you that posted it the first time!!

#43467
