### ISSUE TITLE
[5.1] Mfa::getConfigurationInterface thows error if called from other component.

### ISSUE THREAD

**Issue by Flowman** [joomla/joomla-cms#43812]
### Steps to reproduce the issue

If calling the function Mfa::getConfigurationInterface from a 3-party component it throws an asset error. 

There is no "com_users.two-factor-list" asset of a "script" type in the registry. 

### Expected result

No error should be thrown.

### Actual result

Asset error. 

### System information (as much as possible)

dbserver: mysql
dbversion: 8.0.21-12.1
phpversion: 8.3.8
server: nginx/1.25.4
version: Joomla! 5.1.1 Stable [ Kudumisha ] 28-May-2024 16:00 GMT

### Additional comments

The issues is here. 

https://github.com/joomla/joomla-cms/blob/896c091ed8067dea379179f381f083054c425e79/administrator/components/com_users/src/Helper/Mfa.php#L80

```
if (!$app->getInput()->getCmd('option', '') === 'com_users') {
```

should be

```
if (!($app->getInput()->getCmd('option', '') === 'com_users')) {
```

or

```
if ($app->getInput()->getCmd('option', '') !== 'com_users') {
```

**Comment by Quy** [comment]
Thanks for the report. Please test #43818 for v4.4 to be upmerged.
