### ISSUE TITLE
linking to a contact

### ISSUE THREAD

**Issue by bristolramblers** [joomla/joomla-cms#43811]
If I create a link in an article I can specify if the link is to open in a new window.  This works fine for a link to an article or url but not for a contact

### Expected result
expect contact page to open in a new window but it opens in the same window.

### System information (as much as possible)
in joomla 5 but maybe earlier versions.

**Comment by Pinkeltje** [comment]
Unable to reproduce

**Comment by bristolramblers** [comment]
Thanks Astrid
I find that it now works for me.  It didn't work properly the other day.
Tony
________________________________
