### ISSUE TITLE
[5.1] EmailRule unique should look at input instead of form.

### ISSUE THREAD

**Issue by Flowman** [joomla/joomla-cms#43821]
### Steps to reproduce the issue

Kind of hard to explain. I am making a 3-party component that using the EmailRule to check for unique="true".

On save it will always fail with "Exception has occurred. UnexpectedValueException: The email address you entered is already in use. Please enter another email address." 

The issue is that in the FormController in the save function we are not loading the form data. So when we get to the validation, the form data is always empty but the EmailRule is checking for form data to validate uniqueness.

The fix for it is to change:

https://github.com/joomla/joomla-cms/blob/183985b4a7b9adf8d20b29964e11994cef5a226f/libraries/src/Form/Rule/EmailRule.php#L167

to

```
$userId = (int) $input->get('id', 0); 
```

This will check the submitted data instead of the form load data.

### Expected result

Be able to validate unique email

### Actual result

Exception has occurred. 
UnexpectedValueException: The email address you entered is already in use. Please enter another email address.

### System information (as much as possible)

dbserver: mysql
dbversion: 8.0.21-12.1
phpversion: 8.3.8
server: nginx/1.25.4
version: Joomla! 5.1.1 Stable [ Kudumisha ] 28-May-2024 16:00 GMT

**Comment by Fedik** [comment]
As you know a fix, can you make a PR?

**Comment by HLeithner** [comment]
please check that `$input` is not `null` when creating the PR

**Comment by richard67** [comment]
Closing as having a pull request. See #43822 .
