### ISSUE TITLE
Email cloak plugin inserts duplicate HTML tag id in some cases

### ISSUE THREAD

**Issue by ggppdk** [joomla/joomla-cms#4383]
#### Steps to reproduce the issue
I am not sure if this can be easily reproduced,
but it is clear that it is very much possible, it was reported in FLEXIcontent forums after upgrading to J2.5.25

1. Display the same article twice in same page
2. the email cloak plugin will insert,the second time, the same HTML tag id,
resulting in not proper cloacking of the second email

#### Expected result
Expected would be to have unique HTML tag ids

#### Actual result
non-unique HTML tag ids

#### System information (as much as possible)
J2.5.25 / J3.3.4
emailcloak plugin triggered by FLEXIcontent component

#### Additional comments
-- Maybe instead of this code (class JHtmlEmail, function cloak()):

$rand = rand(1, 100000);
$replacement = '<span id="cloak' . $rand . '">' ...

-- We can use:

static $rand = null;
if ($rand === null) $rand = rand(1, 100000); // initialize to random
$rand = $rand + 1;  // now give unique IDs
$replacement = '<span id="cloak' . $rand . '">' ...

**Comment by brianteeman** [comment]
Is this still an issue in joomla or is it specific to flexicontent?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4383">issues.joomla.org/joomla-cms/4383</a>.</sub>

**Comment by ggppdk** [comment]
Hello
no it is not related to FLEXIcontent,

and i made a correction to my initial posting, the problem is not with the random number as i thought:

--> the problem is that we use HTML tag id in JS to find the email to cloak

so you can not print the cloaked email (twice):
(some users may want to output the article text in 2 places)

echo $article_text;
...
echo $article_text;

--> because you will get a  duplicate HTML tag_id

a solution would be to change code to look for all occurences of a classname

**Comment by zero-24** [comment]
@ggppdk can you provide code for it?

**Comment by brianteeman** [comment]
I have tested this by creating two articles in one category. Each article has the same email address entered twice. 

I then created a blog view to display these articles. This means that the cloaked email is present 4 times in total on the same page

All 4 email addresses have unique ID

See the screeenshots

![vq5a](https://cloud.githubusercontent.com/assets/1296369/5738664/bd542a56-9be6-11e4-9c37-ecdf7ac0c3bf.png)
![mmuc](https://cloud.githubusercontent.com/assets/1296369/5738692/e56e3e46-9be6-11e4-8696-2ce5016629c0.png)

**Comment by zero-24** [comment]
@brianteeman 
Yes this is ok. But if i understand @ggppdk right you can repoduce this by adding e.g. a content plugin that echo twice

```
<?php echo $this->item->text; ?>
<?php echo $this->item->text; ?>
```

So we have the same (prepared) text twice on the page. It is not the same (dublicate) email adress it is the same content :smile: IF you have the emails only the same email adress twice this will work ok and this is expected.

**Comment by brianteeman** [comment]
Is that a real world situation?

I also tested by publishing the article and the newsflash module on the
same page and the ID is still unique. Even with the article and two
identical newsflash modules the IS is still unique

On 14 January 2015 at 13:00, zero-24 <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman>
> Yes this is ok. But if i understand @ggppdk <https://github.com/ggppdk>
> right you can repoduce this by adding e.g. a content plugin that echo twice
>
> <?php echo $this->item->text; ?>
> <?php echo $this->item->text; ?>
>
> So we have the same (prepared) text twice on the page. It is not the same
> (dublicate) email adress it is the same content [image: :smile:] IF you
> have the emails only the same email adress twice this will work ok and this
> is expected.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/4383#issuecomment-69912490>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
>Is that a real world situation?

I don't know but this is a behavior there the ID is not unique maybe @ggppdk can explain in with more details / `real world` examples.

**Comment by brianteeman** [comment]
I am just reluctant to introduce new code and therefore potential bugs just
because...

On 14 January 2015 at 13:10, zero-24 <notifications@github.com> wrote:

> Is that a real world situation?
>
> I don't know but this is a behavior there the ID is not unique maybe
> @ggppdk <https://github.com/ggppdk> can explain in with more details / real
> world examples.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/4383#issuecomment-69913516>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ggppdk** [comment]
please don't misunderstand me

i just "reported" or "identified" an issue, less common, yes i agree

it is not possible to use the cloacked email text in 2 places

-- a similar example -more common-  example would be not being able to use an image twice in same page.

I don't say to fix or change something if it is not worth doing it, i can agree with Brian maybe this will not be supported or done in a future version

I could certainly provide a proper tested fix for this if i had more time,

or if it was a big problem for myself, i would certainly take time to make a pull request that utilizes a unique class name per email address instead of tag-id

Regards

**Comment by brianteeman** [comment]
> it is not possible to use the cloacked email text in 2 places

But I showed that you can

On 14 January 2015 at 13:29, Georgios Papadakis <notifications@github.com>
wrote:

> please don't misunderstand me
>
> i just "reported" or "identified" an issue, less common, yes i agree
>
> it is not possible to use the cloacked email text in 2 places
>
> -- a similar example -more common- example would be not being able to use
> an image twice in same page.
>
> I don't say to fix or change something if it is not worth doing it, i can
> agree with Brian maybe this will not be supported or done in a future
> version
>
> I could certainly provide a proper tested fix for this if i had more time,
>
> or if it was a big problem for myself, i would certainly take time to make
> a pull request that utilizes a unique class name per email address instead
> of tag-id
>
> Regards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/4383#issuecomment-69915643>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ggppdk** [comment]
Yes they are

but if you print them twice, you get same HTML tag id, and the email cloaking no longer works

**Comment by mbabker** [comment]
If @zero-24 simple example is accurate, then the only way to duplicate this issue is if you're outputting the same object multiple times as each object that processed through the `onContentPrepare` event creates unique IDs.  I think I'd close this as a known issue that won't be fixed; if you're outputting an object multiple times, you're going to get what is in that object multiple times.

**Comment by zero-24** [comment]
>but if you print them twice,

print them twice mean not twice with the editor but twice with code like:

```
<?php echo $this->item->text; ?>
<?php echo $this->item->text; ?>
```

**Comment by zero-24** [comment]
>if you're outputting an object multiple times, you're going to get what is in that object multiple times.

agree.

**Comment by ggppdk** [comment]
So we can accept this known issue:

if article text is used in 2 places, email cloaking will be only done in 1 of them, and close this issue

**Comment by mbabker** [comment]
Yes.  If you really need to output the same data object twice, the only clean solution is to repeat all the steps that go into creating `$this->item` (using [ContentViewArticle](https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/article/view.html.php) as an example) using a new variable so that you are again fetching the raw data and processing that data through each of the plugins.

**Comment by ggppdk** [comment]
That could be a solution, but you can not control what content plugins do:
-- e.g. some other 3rd party content plugin could be incrementing a counter, or adding something into the DB

so in some cases we will create a different problem,

in general (for future coding) if we can avoid designing like that item text will only be displayed once, then better do it

--> i mean in the cases that this is possible !
e.g. for email cloaking it could have been done, if author of the code was aware of this while writting the code

**Comment by brianteeman** [comment]
Closing based on the comments above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4383">issues.joomla.org/joomla-cms/4383</a>.</sub>

**Comment by SuperSonic45** [comment]
I have the same issue.
I created custom HTML module with text including email address and publish it in position that defined in my template twice (in header and in footer).
Next i open front-end page (home, for example) and both email cloaked with the same id and i can see first email at the top, but instead of second email at the bottom i see text "This email address is being protected from spambots. You need JavaScript enabled to view it." (of course Javascript is on in my browser).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4383">issues.joomla.org/joomla-cms/4383</a>.</sub>

**Comment by ggppdk** [comment]
You will need to create 2 different custom HTML modules (duplicating the contents). This should work.
