### ISSUE TITLE
[5.1] Running a single test

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#43832]
### Steps to reproduce the issue
Follow the instructions 
> You can execute single test specs, e.g. to run the installation step only.
```
npm run cypress:run --spec tests/System/integration/install/Installation.cy.js
```

### Expected result

Just the installation test is run

### Actual result

All tests are run

![zjIRRA9HIB](https://github.com/user-attachments/assets/d4a4453a-11e7-478d-8956-328ce7b5dff6)

### System information (as much as possible)
windows 11

**Comment by muhme** [comment]
Thank you for following the instructions and testing. This was my mistake and is already corrected with [43731 ](https://github.com/joomla/joomla-cms/pull/43731). The correct command is:
```
npx cypress run --spec tests/System/integration/install/Installation.cy.js
```

sorry
Heiko
