### ISSUE TITLE
schemaorg entry isn't removed from #___schemaorg table when removing \ trashing an article.

### ISSUE THREAD

**Issue by felixkat** [joomla/joomla-cms#43830]
### Steps to reproduce the issue

Create an article, give it a title, select the schema tab and select a schema type, then save.  This is enough for the testing.

The article will appear as an entry in #___content table and the schema reference will be in the #___schemaorg table.

Trash the article and empty trash. 

### Expected result

 The entry will be deleted from the #___content and  #___schemaorg tables.

### Actual result

The entry remains in the #___schemaorg table leaving a stale record.

### System information (as much as possible)

Joomla 5.1.2 tested on Linux and Windows.

### Additional comments

The only way to remove the #___schemaorg entry is to edit article, select schema tab, change schema type to none, save and then remove the article!

Technically the stale records shouldn't cause an issue but they shouldn't be there.

**Comment by chmst** [comment]
Thank for reporting. Which Joomla Version is it?
