### ISSUE TITLE
Joomla 5.1.2 en-GB Language error

### ISSUE THREAD

**Issue by eaciudad** [joomla/joomla-cms#43837]
### Steps to reproduce the issue
I upgraded to 5.1 and I am getting these errors. I have reloaded core files and I am not sure if it is missing the en-GB file but it seems to be there. Has anyone else exprienced this?

Here are the errors:

+ /language/en-GB/joomla.ini
lib_joomla	
+ /language/en-GB/lib_joomla.ini
plg_system_djjquerymonster	
- /administrator/language/en-GB/plg_system_djjquerymonster.ini
- /administrator/language/en-GB/en-GB.plg_system_djjquerymonster.ini
- /plugins/system/djjquerymonster/language/en-GB/plg_system_djjquerymonster.ini
+ /plugins/system/djjquerymonster/language/en-GB/en-GB.plg_system_djjquerymonster.ini
plg_system_kunena.sys	
- /administrator/language/en-GB/plg_system_kunena.sys.ini
- /administrator/language/en-GB/en-GB.plg_system_kunena.sys.ini
- /plugins/system/kunena/language/en-GB/plg_system_kunena.sys.ini
+ /plugins/system/kunena/language/en-GB/en-GB.plg_system_kunena.sys.ini
plg_system_regularlabs	
- /libraries/regularlabs/language/en-GB/plg_system_regularlabs.ini
- /libraries/regularlabs/language/en-GB/en-GB.plg_system_regularlabs.ini
- /plugins/system/modals/language/en-GB/plg_system_regularlabs.ini
- /plugins/system/modals/language/en-GB/en-GB.plg_system_regularlabs.ini
- /plugins/system/regularlabs/language/en-GB/plg_system_regularlabs.ini
+ /plugins/system/regularlabs/language/en-GB/en-GB.plg_system_regularlabs.ini
plg_system_modals	
- /administrator/language/en-GB/plg_system_modals.ini
- /administrator/language/en-GB/en-GB.plg_system_modals.ini
- /plugins/system/modals/language/en-GB/plg_system_modals.ini
+ /plugins/system/modals/language/en-GB/en-GB.plg_system_modals.ini
plg_system_modulesanywhere	
- /administrator/language/en-GB/plg_system_modulesanywhere.ini
- /administrator/language/en-GB/en-GB.plg_system_modulesanywhere.ini
- /plugins/system/modulesanywhere/language/en-GB/plg_system_modulesanywhere.ini
+ /plugins/system/modulesanywhere/language/en-GB/en-GB.plg_system_modulesanywhere.ini
plg_system_sourcerer	
- /administrator/language/en-GB/plg_system_sourcerer.ini
- /administrator/language/en-GB/en-GB.plg_system_sourcerer.ini
- /plugins/system/sourcerer/language/en-GB/plg_system_sourcerer.ini
+ /plugins/system/sourcerer/language/en-GB/en-GB.plg_system_sourcerer.ini
plg_system_weblinks	
- /administrator/language/en-GB/plg_system_weblinks.ini
+ /administrator/language/en-GB/en-GB.plg_system_weblinks.ini
plg_system_gantry5.sys	
- /administrator/language/en-GB/plg_system_gantry5.sys.ini
- /administrator/language/en-GB/en-GB.plg_system_gantry5.sys.ini
- /plugins/system/gantry5/language/en-GB/plg_system_gantry5.sys.ini
+ /plugins/system/gantry5/language/en-GB/en-GB.plg_system_gantry5.sys.ini
plg_system_gantry5	
- /administrator/language/en-GB/plg_system_gantry5.ini
- /administrator/language/en-GB/en-GB.plg_system_gantry5.ini
- /plugins/system/gantry5/language/en-GB/plg_system_gantry5.ini
- /plugins/system/gantry5/language/en-GB/en-GB.plg_system_gantry5.ini
files_gantry5_nucleus	
- /language/en-GB/files_gantry5_nucleus.ini
+ /language/en-GB/en-GB.files_gantry5_nucleus.ini
tpl_g5_hydrogen_positions	
- /templates/g5_hydrogen/custom/language/en-GB/tpl_g5_hydrogen_positions.ini
+ /templates/g5_hydrogen/custom/language/en-GB/en-GB.tpl_g5_hydrogen_positions.ini
tpl_g5_hydrogen	
- /templates/g5_hydrogen/language/en-GB/tpl_g5_hydrogen.ini
+ /templates/g5_hydrogen/language/en-GB/en-GB.tpl_g5_hydrogen.ini
- /templates/g5_hydrogen/custom/language/en-GB/tpl_g5_hydrogen.ini
- /templates/g5_hydrogen/custom/language/en-GB/en-GB.tpl_g5_hydrogen.ini
- /language/en-GB/tpl_g5_hydrogen.ini
- /language/en-GB/en-GB.tpl_g5_hydrogen.ini
com_content	
+ /language/en-GB/com_content.ini
com_djmediatools	
- /language/en-GB/com_djmediatools.ini
- /language/en-GB/en-GB.com_djmediatools.ini
- /components/com_djmediatools/language/en-GB/com_djmediatools.ini
+ /components/com_djmediatools/language/en-GB/en-GB.com_djmediatools.ini
mod_djclassifieds_menu	
- /language/en-GB/mod_djclassifieds_menu.ini
- /language/en-GB/en-GB.mod_djclassifieds_menu.ini
- /modules/mod_djclassifieds_menu/language/en-GB/mod_djclassifieds_menu.ini
+ /modules/mod_djclassifieds_menu/language/en-GB/en-GB.mod_djclassifieds_menu.ini
plg_fields_calendar	
+ /administrator/language/en-GB/plg_fields_calendar.ini
plg_fields_checkboxes	
+ /administrator/language/en-GB/plg_fields_checkboxes.ini
plg_fields_color	
+ /administrator/language/en-GB/plg_fields_color.ini
plg_fields_editor	
+ /administrator/language/en-GB/plg_fields_editor.ini
plg_fields_imagelist	
+ /administrator/language/en-GB/plg_fields_imagelist.ini
plg_fields_integer	
+ /administrator/language/en-GB/plg_fields_integer.ini
plg_fields_list	
+ /administrator/language/en-GB/plg_fields_list.ini
plg_fields_media	
+ /administrator/language/en-GB/plg_fields_media.ini
plg_fields_radio	
+ /administrator/language/en-GB/plg_fields_radio.ini
plg_fields_sql	
+ /administrator/language/en-GB/plg_fields_sql.ini
plg_fields_subform	
+ /administrator/language/en-GB/plg_fields_subform.ini
plg_fields_text	
+ /administrator/language/en-GB/plg_fields_text.ini
plg_fields_textarea	
+ /administrator/language/en-GB/plg_fields_textarea.ini
plg_fields_url	
+ /administrator/language/en-GB/plg_fields_url.ini
plg_fields_user	
+ /administrator/language/en-GB/plg_fields_user.ini
plg_fields_usergrouplist	
+ /administrator/language/en-GB/plg_fields_usergrouplist.ini
plg_content_jw_allvideos	
- /administrator/language/en-GB/plg_content_jw_allvideos.ini
+ /administrator/language/en-GB/en-GB.plg_content_jw_allvideos.ini
plg_content_plgzhosmmap	
- /administrator/language/en-GB/plg_content_plgzhosmmap.ini
+ /administrator/language/en-GB/en-GB.plg_content_plgzhosmmap.ini
plg_content_plgzhosmmap_article_overview	
- /administrator/language/en-GB/plg_content_plgzhosmmap_article_overview.ini
+ /administrator/language/en-GB/en-GB.plg_content_plgzhosmmap_article_overview.ini
tpl_	
- /templates//language/en-GB/tpl_.ini
- /templates//language/en-GB/en-GB.tpl_.ini
plg_system_cookiesck	
- /administrator/language/en-GB/plg_system_cookiesck.ini
+ /administrator/language/en-GB/en-GB.plg_system_cookiesck.ini
plg_schemaorg_article	
+ /administrator/language/en-GB/plg_schemaorg_article.ini
plg_schemaorg_custom	
+ /administrator/language/en-GB/plg_schemaorg_custom.ini
plg_schemaorg_blogposting	
+ /administrator/language/en-GB/plg_schemaorg_blogposting.ini
plg_schemaorg_book	
+ /administrator/language/en-GB/plg_schemaorg_book.ini
plg_schemaorg_event	
+ /administrator/language/en-GB/plg_schemaorg_event.ini
plg_schemaorg_organization	
+ /administrator/language/en-GB/plg_schemaorg_organization.ini
plg_schemaorg_person	
+ /administrator/language/en-GB/plg_schemaorg_person.ini
plg_schemaorg_recipe	
+ /administrator/language/en-GB/plg_schemaorg_recipe.ini
plg_schemaorg_jobposting	
+ /administrator/language/en-GB/plg_schemaorg_jobposting.ini
plg_system_debug	
+ /administrator/language/en-GB/plg_system_debug.ini

**Comment by chmst** [comment]
There are lots of language files missing, most of the belong to extensions. This is not a Joomla core issue. You did not write from where you updated. But in any case, the right place for you to get help is forum.joomla.org

**Comment by chmst** [comment]
No core issue

**Comment by eaciudad** [comment]
Upgraded from 5.0 to 5.1 to 5.1.2. Where did all the files go? Including
the Joomla en-GB, All extensions language are missing? where I can see if
the files are literally there?
Thank you

**Comment by brianteeman** [comment]
the right place for you to get help is forum.joomla.org
