### ISSUE TITLE
Website Name Insert

### ISSUE THREAD

**Issue by colinjeremiahbernard** [joomla/joomla-cms#43856]
### Steps to reproduce the issue
Just write the name of your intended site in the labelled box and see that it does not adhere or accept. 
### Expected result
Flicker and accept the registered new name permanently.
### Actual result
No changes apart from the error message. 
### Additional comments
New website names should be readily accepted or elaborate if there is a specific way in doing it.

**Comment by Hackwar** [comment]
Where are you typing in what, clicking what to achieve which result? What happens instead? Your description does not nearly contain enough information.

**Comment by colinjeremiahbernard** [comment]
I am talking about setting a New name to the site on the start page .....
joomla.com

Em sáb., 27 de jul. de 2024 10:29, Hannes Papenberg <
***@***.***> escreveu:

**Comment by chmst** [comment]
Maybe you have a screenshot where you want to see the name? 
But I think that you can find support - also in your language on https://forum.joomla.org.

**Comment by colinjeremiahbernard** [comment]
There you are, after two attempts, the error message persists. Check the
screenshots attached. Note that language is not an issue.
Best regards,
Colin.

**Comment by chmst** [comment]
Sorry, I get : Whoops! That unsubscribe link isn't valid for your account. Pst the completet Error Message please.

**Comment by Quy** [comment]
Please report issue here: https://github.com/joomla/joomla-websites/issues/new?title=%5Bjlaunch%5D%20
