### ISSUE TITLE
Menu item with Font Awesome in Link Class is always displayed in UPPERCASE

### ISSUE THREAD

**Issue by peterhulst** [joomla/joomla-cms#43867]
![Schermafbeelding 2024-07-31 223920](https://github.com/user-attachments/assets/58349b11-c1db-4c2e-9a3f-8e345430f22d)
### Steps to reproduce the issue

Add a Font Awesome 
e.g. 'fas fa-info-circle' in Menu Item after 'Link Class' in 'Link Type'

### Expected result
[fas fa-info-circle]Blog
(in Cassiopeia and other templates).

### Actual result
[fas fa-info-circle]BLOG
(in Cassiopeia and other templates).
See attached figure.

### System information (as much as possible)
In Joomla 4.4.6 the display is as expected.
In Joomla 5+ (including 5.2 alpha) the display is BLOG

### Additional comments
[fas fa-info-circle] = Font Awesome 6 Free display works as expected
a css override (text-transform: capitalize;) does not work.

**Comment by brianteeman** [comment]
I do this all the time and cannot replicate your finding.
Using core joomla only 5.x all versions
![image](https://github.com/user-attachments/assets/8505ff4a-b62d-4fca-9f31-9daec53389f7)

![image](https://github.com/user-attachments/assets/39e22d74-ee6d-4036-a079-ad9bba469959)

![image](https://github.com/user-attachments/assets/43d64ab9-26fa-4101-a6e7-25cf32d96f23)

**Comment by peterhulst** [comment]
Thank you Brian for the quick respons.

I used 'Link Class' for the ICON (just as i did in J3 & J4), because using 'Link Icon Class' does not display icon in the Menu.
Now I think that is template related (Purity III).

You are using 'Link Icon Class' in Cassiopeia. That also work fine also for me in Cassiopeia.

However the behavior above with the ICON in Link Class giving the UPPER case menu text remains strange and unexpected, also in Cassiopeia.

**Comment by brianteeman** [comment]
Well as I have shown the correct and working way is to use Link Icon Class

The reason it does not work correctly when you use the Link Class is that you are applying the fontawesome font to the icon AND the text. the fontawesome font does not have lowercase letters

**Comment by Quy** [comment]
Closing as a 3rd party template issue and as explained by Brian.
