### ISSUE TITLE
Joomla 4 upgrade to Joomla 5: missing email template in #__mail_templates

### ISSUE THREAD

**Issue by sousa9g** [joomla/joomla-cms#43861]
### Steps to reproduce the issue

When I updated my J4 site to J5, my new J5 site only had 02 mail templates (source: https://github.com/joomla/joomla-cms/blob/5.1-dev/administrator/components/com_admin/sql/updates/mysql/5.0.0-2023-09-02.sql#L8-L10)

However a clean Joomla 5 installation has about 30 email templates (source: https://github.com/joomla/joomla-cms/blob/5.1-dev/installation/sql/mysql/supports.sql#L411C1-L440C5)

Is it an update bug (missing entries in the SQL update file?)

**Comment by brianteeman** [comment]
the updates folder contains the sql to be applied on  updating your existing installation. So it will only contain records for mail templates that you do not already have.

By the sounds of it you have not upgraded Joomla with either the web based update component or the cli update commands ??

**Comment by richard67** [comment]
The other mail templates should have been created when installing Joomla 4 or updating from Joomla 3.10 to 4. See e.g. administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-03-09.sql , administrator/components/com_admin/sql/updates/mysql/4.0.0-2020-12-20.sql , administrator/components/com_admin/sql/updates/mysql/4.1.0-2021-11-20.sql , ...

**Comment by sousa9g** [comment]
Thanks for your feedback.

I upgraded using com_joomlaupdate, but I recalled my first upgrade attempt had errors and this issue could be a result of that, some updates did not run as expected I think.
