### ISSUE TITLE
Joomla\Plugin\Behaviour\Compat\Extension\Compat Error at install

### ISSUE THREAD

**Issue by tibbsterx** [joomla/joomla-cms#43876]
### Steps to reproduce the issue

On fresh install, right after providing all user and DB info, this pops-up an no install stops.
It appears the install was very quick also

see screenshot attached

**Comment by chmst** [comment]
Could you please add your screen shot?

**Comment by brianteeman** [comment]
This should be closed as its impossible to respond to without a screenshot or system information.

**Comment by ssdheerawat** [comment]
Facing this issue after upload site on production 

<img width="713" alt="Image" src="https://github.com/user-attachments/assets/4739272c-e2a9-462e-9193-218620e63973" />
