### ISSUE TITLE
[5.1] UI Issue in Backend on multiple MFA options

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#43890]
### Steps to reproduce the issue
1. Create a backend user with multiple MF alternatives, i.e. Passkey, TOTP, Backup codes. 
2. Set dark mode.
3. Login to the backend with this user.
4. Click on button "Select a different method"

### Expected result
All options on the subsequent form are completely legible.

### Actual result
White font on white background:
![grafik](https://github.com/user-attachments/assets/7e4d169d-cfdd-4efe-9931-20c4c671bc92)

### System information (as much as possible)
J5.1.2

### Additional comments
For reference, the same screenshot for light mode:
![grafik](https://github.com/user-attachments/assets/5c19236a-022c-4be2-b3ea-cbcece5d88cd)

**Comment by brianteeman** [comment]
Please search for existing issues before creating a new one - especially when the existing issue is your own.

see #43448
