### ISSUE TITLE
Language override in 5.2.0 alpha4-dev

### ISSUE THREAD

**Issue by fontanil** [joomla/joomla-cms#43911]
### Steps to reproduce the issue
Install a version of Joomla! 5.1.2 or use a site with that version.
Migrate to version 5.2.0 alpha4-dev, open the language overrides page

### Expected result
The overrides page.

### Actual result
An error has occurred.
    0 Undefined constant "JPATH_" 
in JROOT\administrator\components\com_languages\src\Model\OverridesModel.php:74 

### System information (as much as possible)
PHP 8.1.28 local server

### Additional comments
Error does not occur with Alpha 3 version

**Comment by brianteeman** [comment]
confirmed

**Comment by brianteeman** [comment]
The problem is caused by the changes made by @Hackwar WITH https://github.com/joomla/joomla-cms/pull/43230

**Comment by brianteeman** [comment]
Same problem and same cause with other extensions

![image](https://github.com/user-attachments/assets/f0cbcf2e-c207-489f-8b6b-c8db28f408d5)

**Comment by brianteeman** [comment]
I have created a PR to revert this for now #43918
