### ISSUE TITLE
[5.2] installation with wrong database data

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#43917]
### Steps to reproduce the issue
Build a fresh Joomla, but us a table prefix without underscore. The user gets messages and the installation progressbar. No information, how to continue.

### Expected result
The message appears on the input form for database connection, same as with other database connection errors 

### Actual result
![grafik](https://github.com/user-attachments/assets/dceec887-2868-4580-9ee7-8590bd908975)

### System information (as much as possible)
J 5.2,  PHP 8.3

**Comment by brianteeman** [comment]
This is the same problem as reported by @joejoomla here #42289

**Comment by Quy** [comment]
Closing as duplicate.
