### ISSUE TITLE
Character limit for #__fields.fieldparams

### ISSUE THREAD

**Issue by keep** [joomla/joomla-cms#43929]
#__fields.fieldparams is a TEXT field in the database with a maximum length of 65,535 characters. When I use a List type field with options, Joomla! stores it as JSON, like this:

{"header":"","multiple":1,"options":{"options0":{"name":"My Option 1","value":"My Option 1},"options1":{"name":"My Option 2","value":"My Option 2"}}}

When I need a lot of options, especially if they are a bit longer, it can easily reach the character limit.

What do you think about using MEDIUMTEXT instead of TEXT?

**Comment by alikon** [comment]
after #42606 it make sense

**Comment by fgsw** [comment]
> after [#42606](https://github.com/joomla/joomla-cms/pull/42606) it make sense

@alikon Should it get a ```Feature```-label (#42606 was merged in January 2024)?

**Comment by alikon** [comment]
please test #44238
