### ISSUE TITLE
404 Tagged Items Menu Item When Both Public and Registered Tags

### ISSUE THREAD

**Issue by sdwjoomla** [joomla/joomla-cms#43920]
### Steps to reproduce the issue
Create a tag with access level Public
Create a tag with access level Registered
Assign public tag to an article with the access level Public
Assign registered tag to an article with the access level Registered
Create Menu Item Tags > Tagged Items
Access the frontend - do not login

### Expected result

List with the public article

### Actual result

404 Tag not found 

### System information (as much as possible)

Joomla 4.4.x
MySQL 8.0.23
PHP 8.1.29

**Comment by brianteeman** [comment]
Confirmed with sample blog data and setting one of the tags to registered

**Comment by alikon** [comment]
please test #43922
