### ISSUE TITLE
Move button in subform not alway working directly

### ISSUE THREAD

**Issue by buro26-tom** [joomla/joomla-cms#43928]
**Describe the bug**
I tested the reordering of items in the subform. When clicking and dragging with the move button it will not always work directly. I found that I had to click multiple times before I can drag and drop.

**To Reproduce**
1. Go to subform
2. Click on move icon
3. Drag to change order

**Expected behavior**
After clicking and dragging the items the should change the order.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome, Firefox
 - Version Newest (auto update)

**Additional context**
Strange thing is, sometimes it works directly, not per definition after an refresh or something, can't figure out when it works like it should or why sometimes it doesn't.

If helpful I can provide a GIF screen video

**Comment by Quy** [comment]
>     4. See error

What is the error? Which Joomla version?

> If helpful I can provide a GIF screen video

Yes please.

**Comment by Quy** [comment]
Closing due to no response.
