### ISSUE TITLE
A warning is issued when using CalendarField

### ISSUE THREAD

**Issue by rigin** [joomla/joomla-cms#43947]
### Steps to reproduce the issue

```
<field
			id="created"
			name="created"
			type="calendar"
			required="false"
			label="JGLOBAL_CREATED_DATE"
			description="JGLOBAL_CREATED_DATE_DESC"
			class="inputbox"
			size="16"
			format="%Y-%m-%d %H:%M:%S"
            />
```

### Expected result

Output of the Calendar field

### Actual result

Output of the Calendar field 
At the same time, a warning is issued.
Deprecated: Function strftime() is deprecated in ****/public_html/libraries/src/Form/Field/CalendarField.php on line 323

**Comment by chmst** [comment]
See here: https://github.com/joomla/joomla-cms/issues/42790

**Comment by brianteeman** [comment]
The documentation needs updating with that information

**Comment by Quy** [comment]
Please test  PR  #44114.
