### ISSUE TITLE
[5.2] menu item filter break

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#43940]
Another break from #43230 @Hackwar 

### Steps to reproduce the issue
Trash a menu item

### Expected result
Menu item is only displayed when the filter is set to trashed

### Actual result
Menu item is displayed

### Additional comments
reverting the change in #43230 and it works as expected

**Comment by fgsw** [comment]
I can confirm this behaviour using Modules (Site + Admin), but not for menu items.

**Comment by Hackwar** [comment]
Fixed it in #43941. Please test.
