### ISSUE TITLE
Text strings in PA

### ISSUE THREAD

**Issue by Valdnet** [joomla/joomla-cms#43956]
### Steps to reproduce the issue
1. Log in to the Administration Panel.
2. Install the Polish language pack.
3. Set the installed Polish language pack for the Administration Panel.
4. Go to the Start Desktop.

### Expected result
Translated text strings (marked in red):

![obraz](https://github.com/user-attachments/assets/04089eb0-8912-4192-8b19-1ffd223a5734)

### Actual result
Untranslated text strings.
Text strings appear in ini files in Polish translation.

### Joomla version
5.1.3

### Language pack version
PL 5.1.2
Downloads: https://github.com/JoomlaPolska/jezyk-J4/releases/tag/v5.1.2.1

**Comment by richard67** [comment]
Duplicate report to #35587 ? And see also #36954 .

**Comment by Quy** [comment]
Closing as duplicate.
