### ISSUE TITLE
Filter articles by check-In status

### ISSUE THREAD

**Issue by QuotesUK** [joomla/joomla-cms#43957]
### Is your feature request related to a problem? Please describe.
When a user does not close an article it is checked-out to them and becomes locked for other users. Although there are options for auto-closing and manually clearing locked articles (Global Check-in) there isn’t a way to see a list of them.

### Describe the solution you'd like
In the Article list view add the option to sort or filter by check-in status

### Additional context
The padlock icon is inline, so it isn’t possible to sort by column

**Comment by brianteeman** [comment]
Why would you want to do this. What is the use case.

**Comment by QuotesUK** [comment]
To see which articles are locked. I would like to improve the editing hygiene of a user by showing them the impact of their not-closing (it would help if we can both see, when discussing over the phone, or to send a screenshot). I do not want to change the status as other users may have genuine reasons for leaving a lock. I do not want to auto-close or use global check-in.

Filter by author does not help because users can edit other author’s articles.

The user log does not show the article title.

A list of locked articles also helps me as admin to see what users are up to. I can hover over the lock icon and see the user details. However there isn’t a way to shorten the list of articles to show locked articles only and it isn’t practical to display or paginate through hundreds of articles.

**Comment by QuotesUK** [comment]
Possible idea for implementation without affecting User Interface - use prefix locked:  (similar to id: author: content: )

**Comment by brianteeman** [comment]
locked: authorname ??

**Comment by brianteeman** [comment]
please see #43965

**Comment by alikon** [comment]
closing as we have a pr #43965
