### ISSUE TITLE
[5.2] After Extension installation: Notification don't show links

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#43951]
### Steps to reproduce the issue
1. Installation Patchtester
2. See Notification:
![Untitled](https://github.com/user-attachments/assets/5f4c44ac-8067-4667-ae67-fd7b5153b2b7)

### Expected result
The Link is visible like in 4.x

### Actual result
See Screenshot

### Device and system info

* What version of Joomla were you using?
5.2 nightly build

* What device were you using? (eg, phone, laptop)
macbook air

* What web browser were you using? (eg, Chrome, Safari)
Firefox 129.0.1

**Comment by brianteeman** [comment]
probably the same as https://github.com/joomla/joomla-cms/issues/43708

**Comment by fgsw** [comment]
@brianteeman thanks, closing.
