### ISSUE TITLE
Error on saving a calendar field

### ISSUE THREAD

**Issue by coolcat-creations** [joomla/joomla-cms#43973]
I tried to test the PR #42185 and added these Fields into a form:
<field
	name="no_week_numbers"
	type="calendar"
	label="Test"
	description="Test without weeknumbers and time 24h"
	showtime="true"
	weeknumbers="false"
/>

<field
	name="week_numbers"
	type="calendar"
	label="Test"
	description="Test with weeknumbers and time 24h"
	showtime="true"
/>

when trying to save, no matter if before the patch or after (thats why I am opening an issue) it shows following error:
Deprecated
Function strftime() is deprecated in
/libraries/src/Form/Field/CalendarField.php on line 323

### Expected result
no Error

### Actual result
Deprecated Message

### System information (as much as possible)
PHP 8.1 tested with Joomla 5.2 beta2

**Comment by fgsw** [comment]
@coolcat-creations similar report #43947

**Comment by coolcat-creations** [comment]
ok, sorry - closing as duplicate
