### ISSUE TITLE
Button Translations Backend J3 /J4 /J5 The update source table is not up to date. Please restore the update sources.

### ISSUE THREAD

**Issue by WM-Loose** [joomla/joomla-cms#43979]
Whenever I run "Install languages" in J5, I get a message saying that the update source is not correct and that I should restore it. I've tried all of that and I can't get any further. The error already existed in J3 and was simply carried over into the migration to J4 and J5. Can anyone tell me where I can download the en-GB language pack to install it? It simply cannot be found in the translations on the Joomla download page. Reinstalling the core file doesn't help either. I'm at a loss.

**Comment by brianteeman** [comment]
the en-gb language is not available on its own as an installable pack - it is simply part of the core installation.

I have never heard of this error message that you are getting and have not seen any reports of this either. Can you post some screenshots of the error

**Comment by WM-Loose** [comment]
You're welcome, Brian, I've tried so many things already.
It can only be an error in the database that I just can't find or have no idea where to tackle the problem. Has no one else had this problem of not being able to install languages ​​in the backend? I just can't imagine that. What's much worse, I think, is that a problem like this is carried over from J3 through 2 migrations to J4 and then J5 and possible errors are then not eliminated by the updated core. Everything else, like installing from the web catalog or installing extensions, works without any problems.
![1](https://github.com/user-attachments/assets/f7e015a6-cee9-450b-8be8-fc3ed281b564)
![2](https://github.com/user-attachments/assets/7192ac3a-b0e6-4cc5-91f3-f2e67977abaa)

**Comment by WM-Loose** [comment]
I can also provide a backup of the J5.1.3 installation if you want to investigate it. I can also provide a backup of the old J3 installation where this error already exists.

**Comment by WM-Loose** [comment]
![4](https://github.com/user-attachments/assets/d21d9f1c-4930-4e02-b98c-323f9658e4c1)

**Comment by WM-Loose** [comment]
I found something here but it didn't help me either.
https://www.web-consultant.at/joomla-cms/joomla-anleitung/problem-beim-sprachen-installieren

**Comment by brianteeman** [comment]
The information in that post makes sense and its cause (a faulty template custom install) makes sense to me. Are you sure you followed all the instructions in that post? If you send me a backup I can take a look when I get the time

**Comment by WM-Loose** [comment]
Yes, I've tried everything but have never experienced anything like this before. I'll send you a link to your email address to download the backup including the DB.

**Comment by brianteeman** [comment]
I found the problem

Your list of update sites should look like
![image](https://github.com/user-attachments/assets/08665127-7c45-40a1-9e29-09e1a15e1c23)

You do not have an entry for the en-GB language pack

Go to your database and the table #__update_site_extensions

You should have TWO entries that have the same update_site_id but I am guessing you only have ONE for the GERMAN Language but nothing for the english

Go to the #__extensions table and find the entry for the english language pack and take a note of the ID. In my case it is ID 240

![image](https://github.com/user-attachments/assets/b16f69fa-4a01-4fb8-80c4-404caab9ca64)

Go to the #__update_sites table and find the id for the accredited joomla translations. In my case it is ID 9

![image](https://github.com/user-attachments/assets/121db417-4694-495f-9c64-618c033421e4)

Now go back to the  #__update_site_extensions table

If you have a record with the extension id for english then it incorrectly will not have the correct update_site_id (in my case the correct data is 9 and 240

![image](https://github.com/user-attachments/assets/8e6ad898-2e26-4aff-abcf-f15925488d6b)

If you do not have a record for the english language then create a NEW record in that table with the ID values you found earlier

**Comment by brianteeman** [comment]
this should be closed - it is not a core issue.
