### ISSUE TITLE
PHP Deprecated: Creation of dynamic property on updates check

### ISSUE THREAD

**Issue by M-Falken** [joomla/joomla-cms#43988]
**Steps to reproduce the issue**
The automatic check of updates when you access the Admin Panel

PHP Deprecated:  Creation of dynamic property Joomla\CMS\Updater\Update::$length is deprecated in /libraries/src/Updater/Update.php on line 486

https://github.com/joomla/joomla-cms/blob/f6bebdd73088886772a59d5a332da9025899b766/libraries/src/Updater/Update.php#L486

Joomla! 5.1.3
php 8.3.10

**Comment by kayohf** [comment]
For now would be good to just set the AllowDynamicProperties attribute -> https://www.php.net/manual/en/class.allowdynamicproperties.php

**Comment by alikon** [comment]
same as #44284

**Comment by rdeutz** [comment]
Duplicate, so I am closing this one, see #44284 for more information, thanks for reporting though
