### ISSUE TITLE
 [5.2] Adapt Multilingual Sample Data as #43862 is merged

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#43989]
### Is your feature request related to a problem? Please describe.
Merged Pull Request #43862 removed restrictions for home language menu items. Multilingual Sample Data should adapt for 5.2-User.

Now after the installation Language home menu items are in separate menus:
![Untitled](https://github.com/user-attachments/assets/47d0ff43-784b-44df-99c9-e67a60cac022)

### Describe the solution you'd like
Multilingual Sample Data for 5.2-User install Language home menu items in "Main Menu":
![Untitled2](https://github.com/user-attachments/assets/b72046f6-bb20-4cf1-9c71-3168049140f6)

**Comment by brianteeman** [comment]
I am not sure. Just because you can now put all the home menu items for each language in a single menu doesnt mean it is best practice to do that and the sample data should be showcasing best practice

**Comment by fgsw** [comment]
> the sample data should be showcasing best practice

@brianteeman good argument, thanks.
