### ISSUE TITLE
Cookies Secure flag

### ISSUE THREAD

**Issue by toonetcreation** [joomla/joomla-cms#44018]
Hi,

I have done some tests with this website https://developer.mozilla.org and this result is sometimes displayed : https://i.imgur.com/eZRH4gb.png

I have found this : https://developer.mozilla.org/en-US/docs/Web/Security/Practical_implementation_guides/Cookies

Could you please correct this?

Thanks

L.

**Comment by brianteeman** [comment]
possibly related https://github.com/joomla/joomla-cms/issues/40651

**Comment by toonetcreation** [comment]
ok but why #40651 is closed ?

**Comment by SniperSister** [comment]
Have you set Force SSL to Yes?

**Comment by toonetcreation** [comment]
yes, same problem.

**Comment by SniperSister** [comment]
I'm unable to reprodue the issue. Please provide further information as requested in the "bug report" issue template.

**Comment by toonetcreation** [comment]
my bad, problem was located only on 1 website.
works now, I have found the problem.
thanks again
