### ISSUE TITLE
[5] Guided Tours - Options Help link missing.

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#44015]
### Steps to reproduce the issue

Go to System / Guided Tours and select the Options button in the Toolbar
Select Guided Tours: Options Help button in the Toolbar

### Expected result

A Help page - one does exist.

### Actual result

A 404 Not found page.

### Additional comments

This link is missing from config.xml:

	<help key="Guided_Tours:_Options"/>

**Comment by obuisard** [comment]
Thank you for reporting this issue.
Please test PR #44026.
Thank you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44015">issues.joomla.org/tracker/joomla-cms/44015</a>.</sub>

**Comment by obuisard** [comment]
I am closing this issue since we have a PR addressing it.
