### ISSUE TITLE
[j5] tags view is broken by language filter

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#44017]
### Steps to reproduce the issue

- In com_tags option Set filter langue to ALL
- Create a link to tags
- Search a tag

if you have X component how are using tag, com_content provide doesn't provide good url
/?view=article&id=119&catid=33 instead of an good SEF urls

if we set current langage option or a langage that display only article not other component but with good url

link for testing
https://revuethomiste.fr/arbre-de-mots-cles/metaphysique

Thanks for any help

**Comment by micker** [comment]
no return ?

**Comment by brianteeman** [comment]
would have helped if you had completed the requested information when you open an issue - specifically the version of Joomla being used

Your title says the view is broken but in your description it just says the url is not what you want
