### ISSUE TITLE
Deprecated: PDO::quote(): Passing null in MysqlDriver.php line 736

### ISSUE THREAD

**Issue by frgiraud** [joomla/joomla-cms#44013]
### Issue description
When I display a specific page (extension acymailing - e-mails archive using menu entry), I have this message.
https://ctd.ufolep91-volley.org/index.php/ctd/archives-lettres-de-2024-2025/archive/listing
* Deprecated: PDO::quote(): Passing null to parameter #1 ($string) of type string
is deprecated in /.../libraries/vendor/joomla/database/src/Mysql/MysqlDriver.php on line 736
 
But I also have had the same message at end of the "acymailing 9.8.1" installation :
* pack : installation effectuée.
* AcyMailing package containing the component and its core plugins and modules
* Deprecated: PDO::quote(): Passing null to parameter #1 ($string) of type string is deprecated in /.../libraries/vendor/joomla/database/src/Mysql/MysqlDriver.php on line 736
* Deprecated: PDO::quote(): Passing null to parameter #1 ($string) of type string is deprecated in /.../libraries/vendor/joomla/database/src/Mysql/MysqlDriver.php on line 736

It's probably warnings, because the page is displayed and the installation was done.

### System information
Joomla!: 4.4.8
PHP 8.1.29
MySQL (PDO) 5.7.42-log  

php: Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
dbserver: mysql
dbversion: 5.7.42-log
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
dbconnectionencryption: 
dbconnencryptsupported: true
phpversion: 8.1.29
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 4.4.8 Stable [ Pamoja ] 27-August-2024 16:00 GMT
useragent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0

### MysqlDriver.php on line 736
Is part of: public function escape($text, $extra = false)
Line is: $result = substr($this->connection->quote($text), 1, -1);
* Method to escape a string for usage in an SQL statement.
* Oracle escaping reference:
* http://www.orafaq.com/wiki/SQL_FAQ#How_does_one_escape_special_characters_when_writing_SQL_queries.3F
* SQLite escaping notes:
* http://www.sqlite.org/faq.html#q14
* Method body is as implemented by the Zend Framework
* Note: Using query objects with bound variables is preferable to the below.
* @param   string   $text   The string to be escaped.
* @param   boolean  $extra  Unused optional parameter to provide extra escaping.
* @return  string  The escaped string.
* @since   1.0

**Comment by Hackwar** [comment]
This is a bug in Acymailing and not in Joomla. They are handing in a NULL value instead of a string at the right place. Please report that to them directly.
