### ISSUE TITLE
FIX number of parameters at ArgumentCountError exception @ bcmath_compat

### ISSUE THREAD

**Issue by tkuschel** [joomla/joomla-cms#44028]
I have fixed a bug in exception reporting of composer phpseclib/bcmath_compat 2.0.2,
see https://github.com/phpseclib/bcmath_compat/pull/6
In the meantime, the bcmath_compat is updated to version 2.0.3;

How is this normally handled here? Should I make a pull request for a modified composer.json file or does anybody do an update check of external tools regularly?
Thomas

**Comment by Hackwar** [comment]
If you could create a PR work an updated composer.json and corresponding lock file, we can merge that for 5.2.

**Comment by richard67** [comment]
Closing as having a pull request. See #44036 .
