### ISSUE TITLE
Can you confirm if Joomla still does not include a built-in `J_FILE` field type for subforms?

### ISSUE THREAD

**Issue by madanedeepali** [joomla/joomla-cms#44034]
Hello Joomla Community,

I’m reaching out to clarify the current status of the J_FILE field type in Joomla. Based on my research and discussions, it appears that Joomla has had ongoing issues related to the J_FILE field type, particularly in the context of subforms. I am referencing several related issues and articles:

[Joomla Issue #12832](https://github.com/joomla/joomla-cms/issues/12832) which outlines challenges with file handling.
[Component Creator Issue #191](https://github.com/aDaneInSpain/component-creator-issues/issues/191) and [Issue #128](https://github.com/aDaneInSpain/component-creator-issues/issues/128) which also address related problems.
Given these past discussions and reported issues, I would like to confirm if Joomla currently supports a built-in J_FILE field type specifically for subforms. If not, are there any workarounds or updates planned that might address this functionality?

Any insights or updates from the community would be greatly appreciated.

Thank you!

**Comment by chmst** [comment]
Thanks for your interest in Joomla. Your links are from 2016. Now we have Joomla Version 5.1.
Please check the new code first, this will answer your questions.
