### ISSUE TITLE
On the start page /?start=0 works

### ISSUE THREAD

**Issue by Mich-es** [joomla/joomla-cms#44049]
### Steps to reproduce the issue
Call up your start page and set the parameters /?start=0 behind it

### Expected result
The same behaviour as with all other /?start=x parameters 404 not found

### Actual result
The start page is displayed

### System information (as much as possible)
PHP 8.2
J 5.1.4

### Additional comments
The problem is that Google indexes both the start page with and without the parameter and treats it as non-canonical...
![grafik](https://github.com/user-attachments/assets/f6f0bea2-b943-4515-8ee0-2e8f3424d97a)

**Comment by PhocaCz** [comment]
Hi, maybe it is somehow related to changes in 5.1.3, 4.4.7

https://www.joomla.org/announcements/release-news/5910-joomla-5-1-3-and-4-4-7-security-and-bug-fix-release.html

When testing, prior version do not add suffix: start=0 to the links, new version add this suffix.

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/44069

**Comment by Mich-es** [comment]
It works!
The question is - how do I get the already indexed articles out of the search index again? 
The reason: articles with /?start=0 are still retrievable

**Comment by Mich-es** [comment]
Hello friends,
I don't know if there is a direct connection, but since J5.1.2 the combination /index.php has been indexed by the search engines again.
