### ISSUE TITLE
[5] Privacy: Consents language file not loaded.

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#44054]
### Steps to reproduce the issue

Have a user confirm acceptance of the Privacy Policy on login (Enable the System - Privacy Consent plugin)
Go to the administrator Privacy / Consents page.

### Expected result

The Subject should be a translated string: Privacy Policy

### Actual result

The Subject is a string key: PLG_SYSTEM_PRIVACYCONSENT_SUBJECT

### Additional comments

I have traced this problem to plugins/system/privacyconsent/src/Extension/PrivacyConsent.php where the following block of code is missing from line 39 and following:

```

    /**
     * Load the language file on instantiation.
     *
     * @var    boolean
     * @since  3.9.0
     */
    protected $autoloadLanguage = true;
```
It was present in Joomla 4.

**Comment by Fedik** [comment]
I think it should be translated by com_privacy, 
The consent plugin inserts untranslated string: https://github.com/joomla/joomla-cms/blob/d38a8ffb0d8f2b4579422fc3d229eb60ffa1b1be/plugins/system/privacyconsent/src/Extension/PrivacyConsent.php#L175-L183

**Comment by alikon** [comment]
please test #44192
