### ISSUE TITLE
Admin menu ‘All articles list’ inherits filter setting from previously requested page

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#44083]
### Steps to reproduce the problem
Create two categories, A and B, with subcategories A1, A2, B1, B2 and a third subcategory level A1.1, A1.2, A2.1, A2.2, B1.1, B1.2, B2.1, B2.2, and with a number of articles on all three levels main category as well as in the subcategories.
Create an administrator menu with two MenuItems of the type Articles: List All Articles):
The first MenuItem is: Articles A and shows all articles from category A on 2 levels.
The second MenuItem, Articles B, shows the articles of category B - WITHOUT a default for the level.

### Expected result
The menuItem ‘Articles A’ always shows me all articles up to subcategory level 2.
The menuItem ‘Articles B’ always shows me all articles (including the subcategories, as no levels are defined)

2.### Actual result
If I FIRST click on MenuItem ‘Articles B’, I get all articles (category and subcategories. If I then click on MenuItem ‘Articles B’, the system shows me the articles from category A up to level 2, without the subcategory level 3. If I NOW click on MenuItem ‘Articles B’ again, the filter ‘Levels’ of the previous view remains.

### System information (as far as possible)
J 5.1.4, PHP 8.3

### Additional comments
Filter settings are incorrectly applied.

**Comment by brianteeman** [comment]
same as #42133 ?

**Comment by Quy** [comment]
Closing as duplicate.
