### ISSUE TITLE
[5.2] Missing Guided Tour

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#44089]
### Steps to reproduce the issue
Log in to the admin as a Manager

### Expected result
Guided Tours module shows all **relevant** tours

### Actual result
The Guided Tours module does not include the Category tour

**Comment by obuisard** [comment]
It looks like it has something to do with the same issue I just discovered:
As a manager, I get:

![image](https://github.com/user-attachments/assets/9f68b88d-7400-4bf8-b120-2b9c3a8f0f0e)

When I click the +, I get:

![image](https://github.com/user-attachments/assets/8a4e2d2d-ed15-40e2-956b-b3a3c4d51ec0)

I will investigate further.

**Comment by obuisard** [comment]
No, it's unrelated.

When we select tours, we check for core.manage authorization. 
Which means, we check for com_categories and not com_content.
