### ISSUE TITLE
[5.2] Articles Module: problem with category option as link

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#44088]
### Steps to reproduce the issue
The new module has an option:

> MOD_ARTICLES_FIELD_SHOWCATEGORYLINK_LABEL="Category Link"

Category as link is never shown as an option because:

`showon="title_only:0[AND]show_category:1[AND]card_link:0"`

This `card_link:0` needs to be removed or revised.
I didn't find where this is used, but it is also available in the single plugin file with demo data:
`plugins\sampledata\blog\src\Extension\Blog.php`

**Comment by drmenzelit** [comment]
Closing since we have a PR: https://github.com/joomla/joomla-cms/pull/44144
