### ISSUE TITLE
[5.2] There is no information about the new option in the tour about creating a tour

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#44094]
### Steps to reproduce the issue
In my opinion, it would be right to make changes to the tour **How to create a guided tour** - add a step with automatic start, telling a little about the new added feature in 5.2.

![Screenshot_1](https://github.com/user-attachments/assets/f0de3ee0-3995-40ba-875a-09ddef8d685e)

After "Component Selector" you immediately go to the step of saving the tour and not a word about the new option.

**Comment by tecpromotion** [comment]
The tour "Whats new in Joomla! 5.2" only appears when updating and not for new installations. 
And testing is only possible with nightly builds or from tonight with the update package to beta 3.

**Comment by Kostelano** [comment]
You didn't get it, I'm talking about the new option - automatic tour start. Go through the tour to understand what I mean.

![Screenshot_1](https://github.com/user-attachments/assets/a8c446cb-8755-47e4-9ad3-8145f19b397c)

After step 6 comes 7 - save, not 7 - automatic start and then save.

**Comment by brianteeman** [comment]
confirmed

**Comment by tecpromotion** [comment]
I get it now @Kostelano

@obuisard good catch here. Do you have time to create a PR for this? We should definitely build that into 5.2.0.

**Comment by obuisard** [comment]
I will make time to create the PR to add the step, but it is not a critical bug fix so I doubt this will be included into 5.2.0, as the next release is RC 1.

**Comment by brianteeman** [comment]
it is a critical bug when you are declaring this as a major feature of the release
