### ISSUE TITLE
[5.2] Problem with tour step How to add steps to a guided tour

### ISSUE THREAD

**Issue by Kostelano** [joomla/joomla-cms#44096]
### Steps to reproduce the issue
Go through tour **How to add steps to a guided tour**. I don't see any errors in the console, but for some reason step 3 has a weird window appearance.

![Screenshot_2](https://github.com/user-attachments/assets/947909f6-b3fb-41c0-bb1d-04e02e622c38)

**Comment by tecpromotion** [comment]
What exactly do you mean by ‘weird window appearance’?
Do you mean the distance to the bottom edge @Kostelano?

**Comment by Kostelano** [comment]
@tecpromotion Yes, this always happens to me with the 3rd step.

**Comment by brianteeman** [comment]
I think you are confused (and I was too) between tours that progress to the next step by pressing a button and tours that progress by interacting with Joomla. 

However I also noticed that there is no BACK button on some steps and there really should be. 

Its just bad ui and ux

**Comment by tecpromotion** [comment]
@obuisard please check. Thanks.

**Comment by obuisard** [comment]
Konstantin @Kostelano, please check PR#44104. Thank you!
