### ISSUE TITLE
Incorrect Hungarian translation for "heading" in TinyMCE

### ISSUE THREAD

**Issue by rkrisztian** [joomla/joomla-cms#44097]
### Steps to reproduce the issue

- Configure the default editor to be TinyMCE.
- Log in using the Hungarian language.
- Create a new article.
- Click on the dropdown saying "Bekezdés" (which means "Paragraph" in English)

### Expected result

I should see dropdown entries like "1. címsor", "2. címsor", "3. címsor", ..., "6. címsor".

### Actual result

I see dropdown entries like "1. fejléc", "2. fejléc", "3. fejléc", ..., "6. fejléc".

### System information (as much as possible)

Should not be relevant here, but let me know if you need something.

### Additional comments

In the `language/hu-HU` folder I executed `grep -ri Fejléc` and found the following relevant results:

```none
./mod_articles_news.ini:MOD_ARTICLES_NEWS_TITLE_HEADING="Fejléc szint"
./tpl_cassiopeia.ini:TPL_CASSIOPEIA_FONT_SYSTEM_HEADING="Fejlécbetűkészlet verem"
```

All of these are translated incorrectly to Hungarian, because "heading" should be translated to "címsor". The translator probably mistaken "heading" with "header", which indeed means "fejléc". But the correct translation for "heading" is "címsor".

**Comment by brianteeman** [comment]
The language strings in media/vendor/sa11y are not created by the Joomla project but are from https://github.com/ryersondmp/sa11y/ and you should report those errors there.

For any language string located in administrator/languages or /languages I am sure @tecpromotion can point you in the correct direction for those translations

**Comment by tecpromotion** [comment]
@rkrisztian please use the contact options with the translator at https://volunteers.joomla.org/teams/joomla-cms-language-team or go directly to https://joomla.crowdin.com/cms/hu and correct the strings. The proofreader will then certainly take a look at it.
