### ISSUE TITLE
J5 help files do not work

### ISSUE THREAD

**Issue by gwstyles** [joomla/joomla-cms#44100]
### Steps to reproduce the issue
Install J5.1.4 , go to Help/Joomla help and click on any help file and nothing happens?

### Expected result
It works

### Actual result
Nothing, no errors, no logs.

### System information (as much as possible)
Full FPA available at https://forum.joomla.org/viewtopic.php?f=839&t=1012021
Brief J 5.1.4, php 8.3 server lightspeed.

**Comment by gwstyles** [comment]
Correct url https://forum.joomla.org/viewtopic.php?f=839&t=1012021

**Comment by tecpromotion** [comment]
confirmed

**Comment by brianteeman** [comment]
index.php:1 Mixed Content: The page at 'https://www.example.com/administrator/index.php?option=com_admin&view=help' was loaded over HTTPS, but requested an insecure resource 'http://help.joomla.org/proxy/index.php?option=com_help&keyref=Help51:Start_Here'. This request has been blocked; the content must be served over HTTPS.

**Comment by brianteeman** [comment]
was there a redirect to https in place on the help server previously that has been lost in the server migrations @carcam

**Comment by tecpromotion** [comment]
And in case someone tests it in 5.2.0-beta, the links with _Help52_ don't yet exist.

**Comment by tecpromotion** [comment]
@gwstyles, could you please check whether you can access this link: https://help.joomla.org/proxy?keyref=Help51:Start_Here&lang=en
And whether this matches the link in the source code when you access yourdomain.tld/administrator/index.php?option=com_admin&view=help. Thanks.

**Comment by HLeithner** [comment]
Can't replicate for 5.1, 5.2 may not have any entries yet.

**Comment by gwstyles** [comment]
This is the url I get; https://xxxx.com/administrator/index.php?option=com_admin&view=help
When hovering on a help file I get   https://help.joomla.org/proxy?keyref=Help51: Admin_modules_Multilingual_Status&Lang=en

**Comment by brianteeman** [comment]
Weird that I can confirm the problem on one server but not on another

**Comment by tecpromotion** [comment]
@gwstyles There is a missing colon in your URL after **Modules:**
Correct link: https://help.joomla.org/proxy?keyref=Help51:Admin_Modules:_Multilingual_Status&lang=en

**Comment by HLeithner** [comment]
> Weird that I can confirm the problem on one server but not on another

can you check your configuration.php please?

public $helpurl = 'https://help.joomla.org/proxy?keyref=Help{major}{minor}:{keyref}&lang={langcode}';

**Comment by gwstyles** [comment]
No I have the colon, I just missed it, very hard to see the url. I am long in the tooth...

**Comment by brianteeman** [comment]
https://github.com/user-attachments/assets/2e4fb16c-1e72-43f0-9a83-d073de0e0d23

**Comment by brianteeman** [comment]
@hleithner - bingo give that man a prize. That is indeed the problem

**Comment by HLeithner** [comment]
is this a new site or a page from an older joomla version? (at least the config file)

**Comment by brianteeman** [comment]
it is a site that has been upgraded from 3.x
other updated sites are ok - weird

**Comment by gwstyles** [comment]
I have just discovered after watching Brian's video  that turning Privacy badger Off for my site and Voila it all works.

**Comment by tecpromotion** [comment]
@gwstyles please close the issue if your problem has now been resolved. Thank you.
