### ISSUE TITLE
5.2.0-beta3: Can't install languages through the normal "Install Languages" interface

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#44112]
### Steps to reproduce the issue
Try to install a language through 

> administrator/index.php?option=com_installer&view=languages

### Actual result

<img width="326" alt="Screenshot 2024-09-18 at 17 24 05" src="https://github.com/user-attachments/assets/118b1245-ca09-48d6-a3f3-c49ce2be1c50">

### Additional comments

If one downloads the language pack from 

> https://downloads.joomla.org/language-packs/translations-joomla5

It can be installed through Extensions: Install

> administrator/index.php?option=com_installer&view=install

**Comment by brianteeman** [comment]
This is normal and expected behaviour with all new versions as none of the language packs have version 5.2 in **yet**

**Comment by tecpromotion** [comment]
@infograf768 you are welcome to test one of these language packs: https://github.com/joomlagerman/joomla/releases/tag/5.2.0v1-beta3

**Comment by infograf768** [comment]
Sorry folks was at the hospital for a facelift.
I guess things may have changed too concerning install language packs as I have the feeling it was possible in the past to install through the language installer a pack from an earlier version if none was available for the J! version concerned. Missing strings were displayed in en-GB. 

@tecpromotion 
I guess your packs are fine as the manifest targets the correct beta but using the extension installer does not care anyway as I explained above. Not every translation team release packs for betas afaik.

If not a bug, then maybe should it be considered as a missing feature imho.
