### ISSUE TITLE
admin login - backend and user login frontend

### ISSUE THREAD

**Issue by kr34tor369** [joomla/joomla-cms#44121]
### Steps to reproduce the issue
Login from administrator panel > Global Configuration > change timezone from UTC to America/Phoenix

### Expected result
You should be logged into the backend of your joomla website as administrator.

### Actual result
You will be logged out and unable to log back in as administrator and all users will be unable to login to their accounts from the frontend.

### System information (as much as possible)
    Joomla! Instance :: Joomla! 5.1.4-Stable (Kudumisha) 27-August-2024
    Joomla! Configured :: Yes | Writable (644) |
    Configuration Options :: Offline: false | SEF: true | SEF Suffix: false | SEF ReWrite: true | .htaccess/web.config: Yes | GZip: true | Cache: true | CacheTime: 60 | CacheHandler: file | CachePlatformPrefix: false | FTP Layer: false | Proxy: false | LiveSite: | Session lifetime: 15 | Session handler: memcached | Shared sessions: false | SSL: 2 | Error Reporting: none | Site Debug: false | Language Debug: false | Default Access: Public | Unicode Slugs: false | dbConnection Type: mysqli | PHP Supports J! 5.1.4: Yes | Database Supports J! 5.1.4: Yes | Database Credentials Present: Yes |

    Host Configuration :: OS: Linux | OS Version: 4.18.0-513.18.1.lve.2.el8.x86_64 | Technology: x86_64 | Web Server: LiteSpeed | Encoding: gzip, deflate, br, zstd | System TMP Writable: Yes | Free Disk Space : 949.33 GiB |

    PHP Configuration :: Version: 8.2.23 | PHP API: litespeed | Session Path Writable: Yes | Display Errors: 0 | Error Reporting: 32767 | Log Errors To: | Last Known Error: | Register Globals: | Magic Quotes: | Safe Mode: | Allow url fopen: 1 | Open Base: | Uploads: 1 | Max. Upload Size: 128M | Max. POST Size: 128M | Max. Input Time: -1 | Max. Execution Time: 300 | Memory Limit: 768M

    Database Configuration :: Version: 8.0.36-cll-lve (Client:mysqlnd 8.2.23) | Database Size: 32.69 MiB | #of Tables with config prefix:  170 | #of other Tables:  0 | User Privileges : GRANT ALL

    Detailed Environment :: wrote:
    PHP Extensions :: Core (8.2.23) | date (8.2.23) | libxml (8.2.23) | openssl (8.2.23) | pcre (8.2.23) | sqlite3 (8.2.23) | zlib (8.2.23) | bz2 (8.2.23) | calendar (8.2.23) | ctype (8.2.23) | curl (8.2.23) | hash (8.2.23) | filter (8.2.23) | ftp (8.2.23) | gettext (8.2.23) | json (8.2.23) | iconv (8.2.23) | SPL (8.2.23) | pcntl (8.2.23) | random (8.2.23) | readline (8.2.23) | Reflection (8.2.23) | session (8.2.23) | standard (8.2.23) | mbstring (8.2.23) | shmop (8.2.23) | SimpleXML (8.2.23) | tokenizer (8.2.23) | xml (8.2.23) | litespeed () | i360 (8.2.2) | bcmath (8.2.23) | dba (8.2.23) | dom (20031129) | enchant (8.2.23) | fileinfo (8.2.23) | gd (8.2.23) | igbinary (3.2.15) | imap (8.2.23) | intl (8.2.23) | ldap (8.2.23) | exif (8.2.23) | memcache (8.2) | memcached (3.2.0) | msgpack (2.2.0) | PDO (8.2.23) | mysqlnd (mysqlnd 8.2.23) | mysqli (8.2.23) | odbc (8.2.23) | pdo_mysql (8.2.23) | PDO_ODBC (8.2.23) | pdo_pgsql (8.2.23) | pdo_sqlite (8.2.23) | pgsql (8.2.23) | Phar (8.2.23) | posix (8.2.23) | pspell (8.2.23) | redis (5.3.7) | soap (8.2.23) | sockets (8.2.23) | sysvmsg (8.2.23) | sysvsem (8.2.23) | sysvshm (8.2.23) | tidy (8.2.23) | xmlreader (8.2.23) | xmlwriter (8.2.23) | xsl (8.2.23) | clos_ssa (1.0) | ionCube Loader (13.3.1) | Zend OPcache (8.2.23) | Zend Engine (4.2.23) |
    Potential Missing Extensions :: zip |

    Switch User Environment :: PHP CGI: Yes | Server SU: Yes | PHP SU: Yes | Potential Ownership Issues: No 

    Folder Permissions :: wrote:
    Core Folders :: images/ (755) | components/ (755) | modules/ (755) | plugins/ (755) | language/ (755) | templates/ (755) | cache/ (755) | logs/ (---) | tmp/ (775) | administrator/components/ (755) | administrator/modules/ (755) | administrator/language/ (755) | administrator/templates/ (755) | administrator/logs/ (755) | api/ (755) |

    Elevated Permissions (First 10) :: forum/cache/ (777) | forum/files/ (777) | forum/images/avatars/upload/ (777) | forum/store/ (777) | tmp/ (775) | 

    Database Information :: wrote:
    Database statistics :: Uptime: 755079 | Threads: 27 | Questions: 2057989485 | Slow queries: 3798 | Opens: 10353933 | Flush tables: 3 | Open tables: 131072 | Queries per second avg: 2725.528 | 

    Extensions Discovered :: wrote:
    Components :: Site ::
    Core ::
    3rd Party:: WF_DIRECTIONALITY_TITLE (2.9.80) ? | WF_LISTS_TITLE (2.9.80) ? | WF_ARTICLE_TITLE (2.9.80) ? | WF_BROWSER_TITLE (2.9.80) ? | WF_AUTOSAVE_TITLE (2.9.80) ? | WF_FORMATSELECT_TITLE (2.9.80) ? | WF_CLEANUP_TITLE (2.9.80) ? | WF_REFERENCE_TITLE (2.9.80) ? | WF_SPELLCHECKER_TITLE (2.9.80) ? | JCE - Noneditable (1.0.0) ? | WF_MEDIA_TITLE (2.9.80) ? | WF_VISUALBLOCKS_TITLE (2.9.80) ? | WF_IMGMANAGER_TITLE (2.9.80) ? | WF_FONTCOLOR_TITLE (2.9.80) ? | WF_PRINT_TITLE (2.9.80) ? | WF_LINK_TITLE (2.9.80) ? | WF_FONTSIZESELECT_TITLE (2.9.80) ? | WF_KITCHENSINK_TITLE (2.9.80) ? | WF_SOURCE_TITLE (2.9.80) ? | WF_CLIPBOARD_TITLE (2.9.80) ? | WF_NONBREAKING_TITLE (2.9.80) ? | WF_CHARMAP_TITLE (2.9.80) ? | WF_EMOTIONS_TITLE (2.9.80) ? | WF_WORDCOUNT_TITLE (2.9.80) ? | WF_FULLSCREEN_TITLE (2.9.80) ? | WF_HELP_TITLE (2.9.80) ? | WF_STYLESELECT_TITLE (2.9.80) ? | WF_ANCHOR_TITLE (2.9.80) ? | WF_FONTSELECT_TITLE (2.9.80) ? | WF_LANGCODE_TITLE (2.9.80) ? | WF_PREVIEW_TITLE (2.9.80) ? | WF_CONTEXTMENU_TITLE (2.9.80) ? | WF_TEXTCASE_TITLE (2.9.80) ? | WF_HR_TITLE (2.9.80) ? | WF_STYLE_TITLE (2.9.80) ? | WF_ATTRIBUTES_TITLE (2.9.80) ? | WF_VISUALCHARS_TITLE (2.9.80) ? | WF_SEARCHREPLACE_TITLE (2.9.80) ? | WF_TABLE_TITLE (2.9.80) ? | WF_LINKS_JOOMLALINKS_TITLE (2.9.80) ? | WF_POPUPS_JCEMEDIABOX_TITLE (2.9.80) ? | WF_FILESYSTEM_JOOMLA_TITLE (2.9.80) ? | WF_LINK_SEARCH_TITLE (2.9.80) ? | WF_AGGREGATOR_[youtube]_TITLE (2.9.80) ? | WF_AGGREGATOR_AUDIO_TITLE (2.9.80) ? | WF_AGGREGATOR_VIMEO_TITLE (2.9.80) ? | WF_AGGREGATOR_DAILYMOTION_TITLE (2.9.80) ? | WF_AGGREGATOR_VIDEO_TITLE (2.9.80) ? |

    Components :: Admin ::
    Core :: com_workflow (4.0.0) 1 | com_privacy (3.9.0) 1 | com_actionlogs (3.9.0) 1 | com_menus (4.0.0) 1 | com_login (4.0.0) 1 | com_plugins (4.0.0) 1 | com_languages (4.0.0) 1 | com_wrapper (4.0.0) 1 | com_users (4.0.0) 1 | com_joomlaupdate (4.0.3) 1 | com_mails (4.0.0) 1 | com_templates (4.0.0) 1 | com_postinstall (4.0.0) 1 | com_contenthistory (4.0.0) 1 | com_media (3.0.0) 1 | com_search (3.0.0) 1 | com_banners (4.0.0) 1 | com_cache (4.0.0) 1 | com_content (4.0.0) 1 | com_installer (4.0.0) 1 | com_fields (4.0.0) 1 | com_redirect (4.0.0) 1 | com_finder (4.0.0) 1 | com_tags (4.0.0) 1 | com_checkin (4.0.0) 1 | com_admin (4.0.0) 1 | com_modules (4.0.0) 1 | com_scheduler (4.1.0) 1 | com_categories (4.0.0) 1 | com_associations (4.0.0) 1 | com_config (4.0.0) 1 | com_cpanel (4.0.0) 1 | com_guidedtours (4.3.0) 1 | com_messages (4.0.0) 1 | com_ajax (4.0.0) 1 | com_newsfeeds (4.0.0) 1 |
    3rd Party:: Droppics (3.2.28_light) 1 | Content - droppics (2.5.20) 1 | Editors-xtd - Droppics (2.5.20) 1 | com_phocacommander (5.0.1) 1 | com_akeebabackup (9.9.6) 1 | COM_JCE (2.9.80) 1 | FAQ Book Pro (5.0.1) 1 | Dropfiles (5.7.10_light) 1 | System - Dropfiles (5.7.10_light) 1 | plg_jce_links_dropfiles (5.7.10_light) 1 | K2 - dropfiles (5.7.10_light) 1 | Editors-xtd - Dropfiles (5.7.10_light) 1 | Content - dropfiles (5.7.10_light) 1 | com_bfstop (1.5.2) 1 | com_gantry5 (5.5.19) 1 | com_osdownloads (2.2.9) 1 | Droppics (3.2.28_light) 1 | Content - droppics (2.5.20) 1 | Editors-xtd - Droppics (2.5.20) 1 | Content - Dropeditor (2.5.20) 1 | Dropfiles (5.7.10_light) 1 | System - Dropfiles (5.7.10_light) 1 | plg_jce_links_dropfiles (5.7.10_light) 1 | K2 - dropfiles (5.7.10_light) 1 | Editors-xtd - Dropfiles (5.7.10_light) 1 | Content - dropfiles (5.7.10_light) 1 | Editor - DropEditor (2.5.20) 1 | Joomunited updater (1.0.0) 1 | System - Dropeditor (2.5.20) 1 | DropEditor (2.5.20) 1 | COM_OSMAP (5.0.17) 1 | com_admintools (7.6.1) 1 | COM_FAQ (1.0.0) 1 | COM_CONVERTFORMS (4.4.5) 1 |

    Modules :: Site ::
    Core :: mod_custom (3.0.0) 1 | mod_articles_popular (3.0.0) 1 | mod_stats (3.0.0) 1 | mod_related_items (3.0.0) 1 | mod_tags_similar (3.1.0) 1 | mod_feed (3.0.0) 1 | mod_articles_latest (3.0.0) 1 | mod_articles_news (3.0.0) 1 | mod_wrapper (3.0.0) 1 | mod_users_latest (3.0.0) 1 | mod_breadcrumbs (3.0.0) 1 | mod_finder (3.0.0) 1 | mod_articles_archive (3.0.0) 1 | mod_footer (3.0.0) 1 | mod_languages (3.5.0) 1 | mod_syndicate (3.0.0) 1 | mod_menu (3.0.0) 1 | mod_banners (3.0.0) 1 | mod_articles_categories (3.0.0) 1 | mod_login (3.0.0) 1 | mod_articles_category (3.0.0) 1 | mod_whosonline (3.0.0) 1 | mod_tags_popular (3.1.0) 1 | mod_search (3.0.0) 1 | mod_random_image (3.0.0) 1 |
    3rd Party:: mod_convertforms (1.0) 1 | mod_gantry5_particle (5.5.19) 1 | MOD_OSDOWNLOADSFILES (2.2.9) 1 |

    Modules :: Admin ::
    Core :: mod_custom (3.0.0) 1 | mod_post_installation_messages (4.0.0) 1 | mod_title (3.0.0) 1 | mod_submenu (3.0.0) 1 | mod_frontend (4.0.0) 1 | mod_multilangstatus (3.0.0) 1 | mod_feed (3.0.0) 1 | mod_toolbar (3.0.0) 1 | mod_quickicon (3.0.0) 1 | mod_latest (3.0.0) 1 | mod_stats_admin (3.0.0) 1 | mod_loginsupport (4.0.0) 1 | mod_version (3.0.0) 1 | mod_guidedtours (4.3.0) 1 | mod_menu (3.0.0) 1 | mod_privacy_status (4.0.0) 1 | mod_sampledata (3.8.0) 1 | mod_latestactions (3.9.0) 1 | mod_login (3.0.0) 1 | mod_logged (3.0.0) 1 | mod_privacy_dashboard (3.9.0) 1 | mod_user (4.0.0) 1 | mod_messages (4.0.0) 1 | mod_popular (3.0.0) 1 |
    3rd Party:: Invalidate Cache (0.0.11) 1 |

    Libraries ::
    Core ::
    3rd Party:: Regular Labs Library (24.8.21262) 1 | lib_xef (1.4.1) 1 | file_fof40 (4.1.1) ? |

    Plugins ::
    Core :: plg_authentication_cookie (3.0.0) 1 | plg_authentication_ldap (3.0.0) 0 | plg_authentication_joomla (3.0.0) 1 | plg_api-authentication_basic (4.0.0) 0 | plg_api-authentication_token (4.0.0) 1 | plg_privacy_actionlogs (3.9.0) 1 | plg_privacy_user (3.9.0) 1 | plg_privacy_consents (3.9.0) 1 | plg_privacy_content (3.9.0) 1 | plg_privacy_message (3.9.0) 1 | plg_system_jooa11y (4.2.0) 1 | plg_system_logout (3.0.0) 1 | plg_system_redirect (3.0.0) 0 | plg_system_actionlogs (3.9.0) 1 | plg_system_accessibility (4.0.0) 0 | plg_system_log (3.0.0) 1 | plg_system_skipto (4.0.0) 1 | plg_system_shortcut (4.2.0) 1 | plg_system_debug (3.0.0) 1 | plg_system_schemaorg (5.0.0) 1 | plg_system_sef (3.0.0) 1 | plg_system_highlight (3.0.0) 1 | plg_system_languagefilter (3.0.0) 0 | plg_system_httpheaders (4.0.0) 1 | plg_system_languagecode (3.0.0) 0 | plg_system_fields (3.7.0) 1 | plg_system_cache (3.0.0) 0 | plg_system_privacyconsent (3.9.0) 0 | plg_system_webauthn (4.0.0) 1 | plg_system_remember (3.0.0) 1 | plg_system_task_notification (4.1) 1 | plg_system_stats (3.5.0) 0 | plg_system_guidedtours (4.3.0) 1 | plg_system_schedulerunner (4.1) 1 | plg_sampledata_multilang (4.0.0) 1 | plg_user_profile (3.0.0) 0 | plg_user_contactcreator (3.0.0) 0 | plg_user_terms (3.9.0) 0 | plg_user_token (3.9.0) 1 | plg_user_joomla (3.0.0) 1 | plg_installer_webinstaller (4.0.0) 1 | plg_installer_folderinstaller (3.6.0) 1 | plg_installer_packageinstaller (3.6.0) 1 | plg_installer_urlinstaller (3.6.0) 1 | plg_installer_override (4.0.0) 1 | plg_schemaorg_blogposting (5.0.0) 1 | plg_schemaorg_article (5.1.0) 1 | plg_schemaorg_custom (5.1.0) 1 | plg_schemaorg_organization (5.0.0) 1 | plg_schemaorg_recipe (5.0.0) 1 | plg_schemaorg_jobposting (5.0.0) 1 | plg_schemaorg_person (5.0.0) 1 | plg_schemaorg_event (5.0.0) 1 | plg_schemaorg_book (5.0.0) 1 | plg_content_confirmconsent (3.9.0) 0 | plg_content_emailcloak (3.0.0) 1 | plg_content_loadmodule (3.0.0) 1 | plg_content_finder (3.0.0) 1 | plg_content_pagebreak (3.0.0) 1 | plg_content_pagenavigation (3.0.0) 1 | plg_content_fields (3.7.0) 1 | plg_content_joomla (3.0.0) 1 | plg_content_vote (3.0.0) 0 | plg_finder_tags (3.0.0) 1 | plg_finder_content (3.0.0) 1 | plg_finder_contacts (3.0.0) 1 | plg_finder_newsfeeds (3.0.0) 1 | plg_finder_categories (3.0.0) 1 | plg_webservices_redirect (4.0.0) 1 | plg_webservices_menus (4.0.0) 1 | plg_webservices_privacy (4.0.0) 1 | plg_webservices_media (4.1.0) 1 | plg_webservices_plugins (4.0.0) 1 | plg_webservices_installer (4.0.0) 1 | plg_webservices_tags (4.0.0) 1 | plg_webservices_content (4.0.0) 1 | plg_webservices_banners (4.0.0) 1 | plg_webservices_modules (4.0.0) 1 | plg_webservices_templates (4.0.0) 1 | plg_webservices_newsfeeds (4.0.0) 1 | plg_webservices_users (4.0.0) 1 | plg_webservices_languages (4.0.0) 1 | plg_webservices_messages (4.0.0) 1 | plg_webservices_config (4.0.0) 1 | plg_filesystem_local (4.0.0) 1 | plg_extension_namespacemap (4.0.0) 1 | plg_extension_finder (4.0.0) 1 | plg_extension_joomla (3.0.0) 1 | plg_task_sessiongc (5.0.0) 1 | plg_task_check_files (4.1) 1 | plg_task_deleteactionlogs (5.0.0) 1 | plg_task_globalcheckin (5.0.0) 1 | plg_task_updatenotification (5.0.0) 1 | plg_task_rotatelogs (5.0.0) 1 | plg_task_privacyconsent (5.0.0) 1 | plg_task_requests (4.1) 1 | plg_task_site_status (4.1) 1 | plg_actionlog_joomla (3.9.0) 1 | plg_quickicon_overridecheck (4.0.0) 1 | plg_quickicon_downloadkey (4.0.0) 1 | plg_quickicon_joomlaupdate (3.0.0) 1 | plg_quickicon_phpversioncheck (3.7.0) 1 | plg_quickicon_eos (4.4.0) 1 | plg_quickicon_privacycheck (3.9.0) 1 | plg_quickicon_extensionupdate (3.0.0) 1 | plg_editors-xtd_article (3.0.0) 1 | plg_editors-xtd_menu (3.7.0) 1 | plg_editors-xtd_module (3.5.0) 1 | plg_editors-xtd_pagebreak (3.0.0) 1 | plg_editors-xtd_fields (3.7.0) 1 | plg_editors-xtd_readmore (3.0.0) 1 | plg_editors-xtd_image (3.0.0) 1 | plg_multifactorauth_email (4.2.0) 0 | plg_multifactorauth_yubikey (3.2.0) 0 | plg_multifactorauth_totp (3.2.0) 0 | plg_multifactorauth_webauthn (4.2.0) 0 | plg_multifactorauth_fixed (4.2.0) 0 | plg_workflow_featuring (4.0.0) 1 | plg_workflow_publishing (4.0.0) 1 | plg_workflow_notification (4.0.0) 1 | plg_fields_user (3.7.0) 1 | plg_fields_media (3.7.0) 1 | plg_fields_integer (3.7.0) 1 | plg_fields_calendar (3.7.0) 1 | plg_fields_url (3.7.0) 1 | plg_fields_subform (4.0.0) 1 | plg_fields_checkboxes (3.7.0) 1 | plg_fields_editor (3.7.0) 1 | plg_fields_list (3.7.0) 1 | plg_fields_color (3.7.0) 1 | plg_fields_radio (3.7.0) 1 | plg_fields_usergrouplist (3.7.0) 1 | plg_fields_sql (3.7.0) 1 | plg_fields_textarea (3.7.0) 1 | plg_fields_text (3.7.0) 1 | plg_fields_imagelist (3.7.0) 1 | plg_search_tags (3.0.0) 1 | plg_search_content (3.0.0) 1 | plg_search_contacts (3.0.0) 1 | plg_search_newsfeeds (3.0.0) 1 | plg_search_categories (3.0.0) 1 | plg_media-action_rotate (4.0.0) 1 | plg_media-action_resize (4.0.0) 1 | plg_media-action_crop (4.0.0) 1 | plg_behaviour_compat (5.0.0) 1 | plg_behaviour_taggable (4.0.0) 1 | plg_behaviour_versionable (4.0.0) 1 | plg_captcha_recaptcha_invisible (3.8) 0 |
    3rd Party:: PLG_CONVERTFORMSTOOLS_CALCULATIONS (1.0) 1 | PLG_CONVERTFORMSTOOLS_CONDITIONALLO (1.0) ? | PLG_CONVERTFORMSTOOLS_PDF (1.0) 1 | PLG_CONVERTFORMSTOOLS_TASKS (1.0) 1 | Editor - DropEditor (2.5.20) 1 | plg_editors_codemirror (6.0.0) 1 | plg_editors_jce (2.9.80) 1 | plg_editors_tinymce (6.8.4) 1 | PLG_CONVERTFORMS_ERRORLOGGER (1.0) 1 | PLG_CONVERTFORMS_ACYMAILING (1.0) 1 | PLG_CONVERTFORMS_EMAILS (1.0) 1 | System - Dropfiles (5.7.10_light) 1 | plg_system_ospamanot (2.1.4) 1 | PLG_SYSTEM_CONVERTFORMS (1.0) 1 | PLG_SYSTEM_MODALS (14.1.0) 1 | PLG_SYSTEM_REGULARLABS (24.8.21262) 1 | plg_system_osmylicensesmanager (2.0.17) 1 | System - Dropeditor (2.5.20) 1 | plg_system_nrframework (5.0.47) 1 | plg_system_gantry5 (5.5.19) 1 | plg_system_bfstop (1.5.2) 1 | plg_system_sl_scrolltotop (2.0.0) ? | plg_system_jce (2.9.80) 1 | PLG_SYSTEM_ADMINTOOLS (7.6.1) 1 | Joomunited updater (1.0.0) 1 | plg_installer_jce (2.9.80) 1 | Content - dropfiles (5.7.10_light) 1 | Content - Dropeditor (2.5.20) 1 | Content - droppics (2.5.20) 1 | Content - pdfviewer (1.4.0) 1 | plg_content_jce (2.9.80) 1 | PLG_CONTENT_OSDOWNLOADS (2.2.9) 1 | PLG_OSMAP_JOOMLA (5.0.17) 1 | K2 - dropfiles (5.7.10_light) 1 | plg_gantry5_preset (5.5.19) 0 | plg_extension_jce (2.9.80) 1 | PLG_ACTIONLOG_ADMINTOOLS (7.6.1) 0 | plg_quickicon_gantry5 (5.5.19) 1 | PLG_QUICKICON_AKEEBABACKUP (9.9.6) 1 | plg_quickicon_jce (2.9.80) 1 | PLG_EDITORS-XTD_CONVERTFORMS (1.0) 1 | PLG_EDITORS-XTD_MODALS (14.1.0) 0 | Editors-xtd - Droppics (2.5.20) 1 | Button - pdfviewer (1.3.0) 1 | Editors-xtd - Dropfiles (5.7.10_light) 1 | plg_fields_mediajce (2.9.80) 1 | PLG_CONVERTFORMSAPPS_EMAIL (1.0) 1 | PLG_CONVERTFORMSAPPS_ACYMAILING (1.0) 1 | plg_contact_antispamextended (1.0.3) 1 | plg_jce_links_dropfiles (5.7.10_light) 1 | plg_captcha_turnstile (1.4.0) 1 | 

    Templates Discovered :: wrote:
    Templates :: Site :: g5_helium (5.5.19) 1 | cassiopeia (1.0) 1 | jf_simone (1.0) 1 |
    Templates :: Admin :: atum (1.0) 1 | 

### Additional comments
I have researched a cause and remedy for the last 3 days including seeking assistance in the joomla forum with no avail. (https://forum.joomla.org/viewtopic.php?f=839&t=1012015&p=3731035#p3731035) I have also contacted my hosting provider to make there wasd nothing going on at the server that would block the login. I did not change anything other than the timezone and now when I try to log in, the page refreshes with no errors. I turned on error reporting and debugging and there are no errors when attempting to log in. The only error messages that I can get is when you try to log in from the frontend from any account whether admin or user you will receive this error:
 
The page isn’t redirecting properly

An error occurred during a connection to arizonadejure.org.

    This problem can sometimes be caused by disabling or refusing to accept cookies.

I have tried every browser I can think of and every computer and mobile device available to me with no avail. Hopefully this can be figured out soon as it is very difficult to admin from cpanel.

**Comment by fgsw** [comment]
Expected and actual result is the same?

**Comment by richard67** [comment]
@kr34tor369 The actual result should describe what happens, the expected result should describe how it should be.

**Comment by kr34tor369** [comment]
@richard67 your right, I am new at this part, It was late and I guess I thought it was asking the expected result of the error. Is there a way to edit that section to reflect the proper information? I don't see anywhere to edit.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44121">issues.joomla.org/tracker/joomla-cms/44121</a>.</sub>

**Comment by richard67** [comment]
> @richard67 your right, I am new at this part, It was late and I guess I thought it was asking the expected result of the error. Is there a way to edit that section to reflect the proper information? I don't see anywhere to edit.

@kr34tor369 YOu can go to the issue directly on GitHub here: https://github.com/joomla/joomla-cms/issues/44121 . There is a "..." link at the right top corner of the issue description box. It opens a pull-down menu which should have an "Edit" option for you as you are the author of the issue.

**Comment by kr34tor369** [comment]
It seems that somehow session_handler was set to memcached instead of database in the configuration.php file. After setting it to database, I am able to login and users can login from frontend. All I did was change the timezone in Global Configuration from the joomla admin backend and was logged out after saving the change and was unable to login. I cannot say what session_handler was set to because I never changed anything in that regard. I don't see how it is possible for joomla to just change it to memcached but something happened and memcached wont allow the session to renew. So as long as sesion_handler is set to 'database' or 'filesystem', admin login seems to work fine and registered users can login without the cookie error.

**Comment by Hackwar** [comment]
If your server does not support memcached, the option won't work. In any case, since this isn't a bug in Joomla, I'm closing this issue.
