### ISSUE TITLE
[5.2] Articles module - Read more link without Title

### ISSUE THREAD

**Issue by JeroenMoolenschot** [joomla/joomla-cms#44135]
The Read more link always shows Read more: with title, even when you set the Read More with Title to Hide

### Steps to reproduce the issue
Set Display options > Title Only to **No**
Set "Read More" Link to **Show**
Read More with Title to **Hide**

### Expected result
Show only a button with "Read more"

### Actual result
![afbeelding](https://github.com/user-attachments/assets/116913a3-97d0-4921-a9bb-feb104b9aeb4)

### System information (as much as possible)
 The currently installed Joomla! version is ‎5.2.0-beta3

### Additional comments
Also the Read More Limit (characters) don't seem to work. The complete title is shown.

**Comment by HLeithner** [comment]
@drmenzelit can you please have a look?

**Comment by chmst** [comment]
We have a PR #43457, this should resolve the usability issue. 
See also #41192

**Comment by brianteeman** [comment]
Bug confirmed. The problem is that the module is using the params set in the content component and not the params set in the module

**Comment by RickR2H** [comment]
Closed! Please test: #44136 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44135">issues.joomla.org/tracker/joomla-cms/44135</a>.</sub>
