### ISSUE TITLE
[5.1.4] addInlineScript does not work

### ISSUE THREAD

**Issue by jschmi102** [joomla/joomla-cms#44131]
addInlineScript does not work on 5.1.4

I've developed a module, which inserts an inline script. This works fine on all of my sites but does not on one single site though this has the same joomal version as all the other systems.
There is no error shown it just does not work. Strange is for me that insertion of scripts or styleseets work fine.

I tried to debug but could not find out anything, Checked plugins but its seems that none is involved (e.g. hhtp-header is disabled).

would be great, if someone helps to find out whats going wrong.
### Steps to reproduce the issue
```
$wa->registerAndUseScript("js_weather0", "media/mod_js_weather/js/RGraph.common.lib.js");
$wa->registerAndUseScript("js_weather1", "media/mod_js_weather/js/RGraph.line.js");
	
$script = $helper->create_inline_script();
$wa->addInlineScript($script);
```

### Expected result
all scripts should be there
### Actual result
only the script files are ok.
Inline script is missing
### System information (as much as possible)
joomla 5.1.4
php 8.2.4

**Comment by brianteeman** [comment]
From the limited information you have provided it is impossible to debug why your extension does not work on a specific site and does work on other sites

**Comment by jschmi102** [comment]
hi, 
did a print_r on the retuncode of  "$wa->addInlineScript($script);"
and saw these last infos::
`,,,,

["onWebAssetRegistryChangedAssetOverride"]=> object(Joomla\Event\ListenersPriorityQueue)#591 (1) { ["listeners":"Joomla\Event\ListenersPriorityQueue":private]=> array(1) { [0]=> array(1) { [0]=> object(Closure)#878 (2) { ["this"]=> *RECURSION* ["parameter"]=> array(1) { ["$event"]=> string(10) "" } } } } } ["onWebAssetRegistryChangedAssetRemove"]=> object(Joomla\Event\ListenersPriorityQueue)#880 (1) { ["listeners":"Joomla\Event\ListenersPriorityQueue":private]=> array(1) { [0]=> array(1) { [0]=> object(Closure)#607 (2) { ["this"]=> *RECURSION* ["parameter"]=> array(1) { ["$event"]=> string(10) "" } } } } } } } } ["activeAssets":protected]=> array(1) { ["script"]=> array(3) { ["xx_weather0"]=> int(1) ["xx_weather1"]=> int(1) ["inline.fdd212cdd0684aec80324a770a7a7748"]=> int(1) } } ["locked":protected]=> bool(false) ["dependenciesIsActual":protected]=> bool(false) ["sortedAssets":protected]=> array(1) { ["script"]=> array(0) { } } } 
`

**Comment by HLeithner** [comment]
Don't use `$wa = Factory::getApplication()->getDocument()->getWebAssetManager();` if it's not really needed (for example in the view you can use $this->getDocument()....)

Also You don't need `$wa->useScript();` because you use register**AndUse**Script already.

**Comment by HLeithner** [comment]
@jschmi102 I tried to make your comment more readable but didn't was really successfully, can you repost with correct styling and maybe not use print_r instead use var_dump or at least pretty copy-paste please.

**Comment by jschmi102** [comment]
hi,
what do you think? 
If you have an application which runs perfectly with 5 systems  and does not wit one singel system. Woluld you think the application is the problem orr the failing system? 

So I did the most reasonable: I used a working backup/restore of the failing sytem. And what happened? My extension is working now on this system.
