### ISSUE TITLE
Use of deprecated function strftime()

### ISSUE THREAD

**Issue by tavaba** [joomla/joomla-cms#44152]
### Steps to reproduce the issue
1. In the Global Configuration, set 'Error Reporting' to 'Maximum'
2. Open any  form that has a date field.

### Expected result
The form is shown.

### Actual result
Error message
PHP Deprecated:  Function strftime() is deprecated in C:\inetpub\joomla\libraries\src\Form\Field\CalendarField.php on line 322

### System information (as much as possible)
Windows 10
IIS
PHP 8.3.11

**Comment by fgsw** [comment]
Joomla-Version?

**Comment by richard67** [comment]
Duplicate report to #43947 . Please test  PR  #44114 . Thanks in advance.
