### ISSUE TITLE
[5.2] Fix filtering exclude and include articles mod_articles

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#44150]
### Steps to reproduce the issue
#44142 was merged with an outstanding issue

### Expected result
The module can be set to list a selection of articles AND to not include the current article in the list

### Actual result
This is not possible because the option to exclude the current article is only available if you have defined a list of articles to exclude. This option should be independent of any other settings.

USE CASE
I want to include articles 1,2,3,4,5 in the module but I do not want to include the article I am currently viewing

**Comment by chmst** [comment]
Please test the draft PR #44197. It resolves your issue and enables more filtering.

**Comment by drmenzelit** [comment]
New PR: #44213
