### ISSUE TITLE
Cassiopeia mobile menu collapse bug

### ISSUE THREAD

**Issue by xeno024** [joomla/joomla-cms#44174]
### Steps to reproduce the problem
I install a fresh J4/J5 on localhost, set up a couple of tiered menus, set the menu to Collapsible Dropdown in the main module settings. Then the error comes up, randomly.
I open the hamburger menu, open a submenu, close the main menu with that submenu open, open it again, close it, and play this for x amount of time, and then something gets stuck, and the submenus that are open don't respond to anything.

### System information (as far as possible)
I have experienced this bug in Joomla4 and 5. Also with a J4 or J5 version on an unknown server, with multiple browsers, the mentioned page:

https://cassiopeia.joomla.com/help/menu-module

**Comment by alikon** [comment]
please don't double post 
closed in favour of #44140
