### ISSUE TITLE
[5.3][PWA] Progressive Web App for Joomla

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#44172]
### Is your feature request related to a problem? Please describe.
@Joomla currently does not have support for creating PWA out of the box, and PWA can easily replace a native app for Android, iOS, Windows, MacOS and other OS.

### Describe the solution you'd like
I suggest adding PWA support to Joomla https://github.com/joomla/joomla-cms/discussions/44182

**What does this mean?**
This means that only 1 additional page with PWA settings will be added to the `Control Panel` + 3 files for PWA to work (`app.webmanifest` + `sw.js` + `offline.html`)

I have created topics with example files that I suggest adding to Joomla:
`app.webmanifest` (manifest.json): https://github.com/joomla/joomla-cms/issues/19877
`sw.js` & `offline.html`: https://github.com/joomla/joomla-cms/issues/44171
`share_target` (Web Share API): https://github.com/joomla/joomla-cms/issues/44311 

### Additional context
 What are Progressive Web Apps? - [https://web.dev/articles/what-are-pwas](https://web.dev/articles/what-are-pwas)
@W3C: Web Application Manifest - [https://www.w3.org/TR/appmanifest/](https://www.w3.org/TR/appmanifest/)
@MDN: Web App Manifest - [https://developer.mozilla.org/docs/Web/Manifest](https://developer.mozilla.org/docs/Web/Manifest)
@PWA-Builder PWA Docs - [https://docs.pwabuilder.com/](https://docs.pwabuilder.com/)
@Microsoft PWA Docs - [https://microsoft.github.io/win-student-devs/#/30DaysOfPWA/README](https://microsoft.github.io/win-student-devs/#/30DaysOfPWA/README)

@PWA-Builder (testing your PWA from @Microsoft) - [https://www.pwabuilder.com/](https://www.pwabuilder.com/)

**Comment by richard67** [comment]
Does it really need this new issue  in addition to #19877 ?

**Comment by richard67** [comment]
If this issue here combines all, why does it then need the other two issues? Isn’t one issue enough? It is not really helpful to have several issues for one thing. Remember, this repository is maintained by volunteers, and their work should not be made more complicated that necessary.

**Comment by alikon** [comment]
i'm closing this in favour of #44171
