### ISSUE TITLE
Guided tour in Joomla 5.2 rc1and rc2

### ISSUE THREAD

**Issue by gwstyles** [joomla/joomla-cms#44181]
### Steps to reproduce the issue
In admin the new guided tour opens. try hide forever or cancel to close the guided tour,it closes. Navigate elsewhere or refresh page and guided tour reappears?

### Expected result
It stays closed.

### Actual result
It reappears consistently.

### System information (as much as possible)
J 5.2 rc1, php 8.3.11, litespeed server.

### Additional comments
None.

**Comment by brianteeman** [comment]
Are you able to check in the database AFTER clicking hide or cancel and report the values stored in the #_user_profiles table

**Comment by gwstyles** [comment]
No, I click on cancel and then go to system but automatically guided tour starts again. user_profile table is empty.

**Comment by brianteeman** [comment]
>  I also got "Something went wrong while saving tour state information! Response error." for the first time.

Ah - that makes sense (would have been good if you had included the error message in your report) - that was supposed to be fixed by https://github.com/joomla/joomla-cms/pull/44082 cc @obuisard

**Comment by gwstyles** [comment]
I didn't get the error message at first.

**Comment by obuisard** [comment]
Hello @gwstyles,

on a new install with PHP 8.3.7, I cannot reproduce the issue.
What is the database used?

on an update from beta 2, I also do not get any issue.

Please go to your Super User account. Save the profile.
Make sure you have records in the user_profiles table (that will check records can be added to the table).

**Comment by gwstyles** [comment]
I updated from beta 2.
I have records in #__user_profiles table.
I have autostart in #__guidedtours .
DB used MySql version	10.6.19-MariaDB-cll-lve-log.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44181">issues.joomla.org/tracker/joomla-cms/44181</a>.</sub>

**Comment by gwstyles** [comment]
I have now deleted the site and installed J 5.1.4 and then updated to 5.2 rc1 completely vanilla and it appears to work as it should.So updating from various previous versions seems to cause the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44181">issues.joomla.org/tracker/joomla-cms/44181</a>.</sub>

**Comment by tecpromotion** [comment]
> I have now deleted the site and installed J 5.1.4 and then updated to 5.2 rc1 completely vanilla and it appears to work as it should.So updating from various previous versions seems to cause the issue.

Thank you for your feedback.

**Comment by obuisard** [comment]
Thank you @gwstyles for reporting it.

**Comment by chmst** [comment]
> I think it is safe to close this issue, there was no other report of that behavior from the release test group.

I had this too. Updated from 5.1.4 and could not "hide forever" during the first tests. Now it is hidden. Maybe a cache effect?

**Comment by brianteeman** [comment]
> I think it is safe to close this issue, there was no other report of that behavior from the release test group.

No its not safe to close. Its a bug that needs to be fixed

**Comment by fgsw** [comment]
@gwstyles Can you change the title to a meaninful one?

**Comment by gwstyles** [comment]
I have just updated to rc2 from rc1 and the guided tours are behaving worse now when I click on "Whats new in joomla 5.2!" A much smaller pop up appears and locks the back end.Nothing works,you have to log out of admin and log back in to gain control of Admin. This is a vanilla install of J5.1.4 to rc1 and now rc2.
@fgsw title changed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44181">issues.joomla.org/tracker/joomla-cms/44181</a>.</sub>

**Comment by gwstyles** [comment]
Addendum akeeba and admin tools are installed on the site, so not quite vanilla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44181">issues.joomla.org/tracker/joomla-cms/44181</a>.</sub>

**Comment by fgsw** [comment]
> I have just updated to rc2 from rc1 and the guided tours are behaving worse now when I click on "Whats new in joomla 5.2!" A much smaller pop up appears and locks the back end.Nothing works,you have to log out of admin and log back in to gain control of Admin. This is a vanilla install of J5.1.4 to rc1 and now rc2.

Can't confirm after update nightly builds ```Joomla_5.1.5-dev-Development-Full_Package``` > ```Joomla_5.2.0-rc3-dev-Development-Update_Package```. Click on ```Hide forever``` all works.

**Comment by gwstyles** [comment]
I have just uninstalled everything non joomla and retested and I have the same. I tried to upload a screen dump but it doesn't seem to let me?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44181">issues.joomla.org/tracker/joomla-cms/44181</a>.</sub>

**Comment by gwstyles** [comment]
I updated from J 5.1.4 not 5.1.5 dev.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44181">issues.joomla.org/tracker/joomla-cms/44181</a>.</sub>

**Comment by gwstyles** [comment]
![Image](https://github.com/user-attachments/assets/7a3ffe67-6271-4bb2-9a19-c383828a6616)

**Comment by gwstyles** [comment]
My apologies to all, I just discovered my default admin template is Muta I installed that after the original problem with rc1 and forgot, I just changed it to Atum and it does behave as it should. Getting too old for this...

**Comment by obuisard** [comment]
> ![Image](https://github.com/user-attachments/assets/7a3ffe67-6271-4bb2-9a19-c383828a6616)

Apparently the Muta template includes an overridden version of the Guided Tours's css file, which does not contain the latest updates made to the CSS to accommodate the new functionality added to 5.2.
