### ISSUE TITLE
[5.2] New articles module - read more limit doesn't work

### ISSUE THREAD

**Issue by paternax** [joomla/joomla-cms#44185]
### Steps to reproduce the issue
Set in the Display options - Read more limit to 20

![Image](https://github.com/user-attachments/assets/94fe7c4e-c78c-4cc0-9f86-ed305fc15cc6)

### Expected result
The Read more line should be cut after 20 characters

![Image](https://github.com/user-attachments/assets/73b23c31-dddd-4e6d-818a-d01ae26c5d81)

### Actual result

The whole Read more line is shown

### System information (as much as possible)

Joomla 5.2rc1, PHP 8.2

**Comment by Quy** [comment]
Fixed per #44179 pending merge. Thanks for the report.

**Comment by Quy** [comment]
Please test PR #44189. Thanks for the report.
