### ISSUE TITLE
[5.2.0 rc1] Articles Module - Setting to Columns to 3 or 4 Only Displays 2 using Cassiopeia

### ISSUE THREAD

**Issue by sdwjoomla** [joomla/joomla-cms#44186]
### Steps to reproduce the issue

- Set template style to Cassiopeia
- A module should be published in the sidebar
- Create a new module of type Articles
- Set the Max Number of Columns to 3 or 4
- Assign module to a position such as main-bottom

### Expected result
3 or 4 columns of content
The number of articles present on the screen

### Actual result
2 columns display no matter if 3 or 4 selected
![Image](https://github.com/user-attachments/assets/4a3481ca-1c75-479b-a03c-954a5a9940b4)
![Image](https://github.com/user-attachments/assets/3142ef49-5668-4f68-8704-bc3b5b3ff372)

### System information (as much as possible)
5.2.0-rc1
PHP 8.2.23
Template Cassiopeia

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/43738#issuecomment-2206152867

**Comment by dautrich** [comment]
This might be the designed behavior, if we assume a minimum width for a column in the new Articles module. But to be honest, I didn't check the code.

**Comment by brianteeman** [comment]
yes it is the designed behaviour even if it is confusing and not documented

**Comment by paternax** [comment]
It would be best, when the field "Max. Number of Columns" would be deactived if the Template - Layout ist set to static. 
There should be a hint in the inline help which explains the dependencies between layout type in the template options and columns in the module.

**Comment by chmst** [comment]
From usabilty point of view this is not sufficient. If a user changes the template layout to fluid for mod_articles he can destroy his site. 
Can we find a solution without grid?

**Comment by dautrich** [comment]
@paternax 
> It would be best, when the field "Max. Number of Columns" would be deactived if the Template - Layout ist set to static. There should be a hint in the inline help which explains the dependencies between layout type in the template options and columns in the module.

Why would you want to deactivate the field for a static layout? I don't see a reasonable argument for that.
The bigger issue is the lack of inline help, describing the different options and their interferences,

**Comment by brianteeman** [comment]
> The bigger issue is the lack of inline help, describing the different options and their interferences,

No the bigger issue is that it doesnt work how you would expect it to work. If you have to write an explanation of why something doesnt work then you are just proving that the code is wrong

**Comment by dautrich** [comment]
My comment wasn't about bad functionality. I like the new module with its multipurpose approach.

**Comment by drmenzelit** [comment]
It is always difficult to take all possibilities into account. That is why I named the field "Max. number of columns", it would be not more than 3, but it can be less ;-) If someone has a better solution, please let me know.
A documentation of the module is in work.

**Comment by drmenzelit** [comment]
https://docs.joomla.org/Help5.x:Site_Modules:_Articles

**Comment by aefferenpriv** [comment]
I just upgraded to 5.2 as well and now my home menu can't show 4 columns of articles. New created menus have same issue. Former created menus do not have this issue. Based on the hints provided I can't get it corrected. See www.rabbitdesign.nl. Home screen articles 'a mess'. when you select from left menu i.e. 1977 it shows how it was in the home menu as well. Any hints where to look to fix this?

**Comment by drmenzelit** [comment]
@aefferenpriv your problem is not related with this already merged PR. You should better ask in the forum (forum.joomla.org), but from a short check of your site, I think the second article (42165 - Mercedes-AMG F1 W14 E Performance Pull-Back) contains some div elements that are interfering with the display of the columns.

**Comment by aefferenpriv** [comment]
@drmenzelit my apologies, I will turn to the joomla forum. Anyway thanks for your hint. Much appreciated.
