### ISSUE TITLE
The actions menu in the admin isn't working on mobile

### ISSUE THREAD

**Issue by stimpsonjcat** [joomla/joomla-cms#44198]
### Steps to reproduce the issue
When I open the admin on my mobile phone (iPhone / Safari) and either go to users or articles, I select one or more articles / users from the list. Then I click in the top right corner to open the menu and click on 'Actions'.

### Expected result

This should open the submenu to give you a choice i.e. to delete an article or user.

### Actual result

The whole menu is closed.

### System information (as much as possible)

iPhone iOS 17 with Safari 
Both Joomla 4.4.8 and Joomla 5.1.4

### Additional comments
This has always been working fine. Not sure when the bug appeared.

**Comment by richard67** [comment]
Closing as having a pull request. Please test #44199 . Thanks in advance.
