### ISSUE TITLE
Joomla_5.1.4-Stable-Full_Package.tar.gz seems double-gzipped

### ISSUE THREAD

**Issue by henrikalves** [joomla/joomla-cms#44201]
Dear Joomla Team,

I encountered an issue with the gzipped tarball for Joomla version 5.1.4, which can be downloaded from the following URL: https://downloads.joomla.org/cms/joomla5/5-1-4/Joomla_5-1-4-Stable-Full_Package.tar.gz?format=gz

Steps to reproduce:

1. Download the file using the provided link.
2. Run the command `gunzip Joomla_5.1.4-Stable-Full_Package.tar.gz`
3. Use the file command on the resulting .tar file. `file Joomla_5.1.4-Stable-Full_Package.tar`

Expected result: The .tar file should be a valid, uncompressed tar archive.

previous version 5.1.3:
```
Joomla_5.1.3-Stable-Full_Package.tar: POSIX tar archive (GNU)
```

Actual result: The file command shows the following output:

```
Joomla_5.1.4-Stable-Full_Package.tar: gzip compressed data, from Unix, original size modulo 2^32 89282560
```

It seems that the .tar file has also been compressed again

Could you please look into this?

Best regards,
Henrik

#### Additional comments
seems to have happened before in #43785

**Comment by rdeutz** [comment]
A tar file is uncompressed archive of files and a tar.gz is the compressd version. If you want to extract it then you can do it in one step with 

tar -xzf Joomla_5.1.4-Stable-Full_Package.tar.gz

or you do it in two steps

gzip -d Joomla_5.1.4-Stable-Full_Package.tar.gz
tar -xf Joomla_5.1.4-Stable-Full_Package.tar

Not an error andthing is fine

**Comment by henrikalves** [comment]
> A tar file is uncompressed archive of files and a tar.gz is the compressd version. If you want to extract it then you can do it in one step with
> 
> tar -xzf Joomla_5.1.4-Stable-Full_Package.tar.gz
> 
> or you do it in two steps
> 
> gzip -d Joomla_5.1.4-Stable-Full_Package.tar.gz tar -xf Joomla_5.1.4-Stable-Full_Package.tar
> 
> Not an error andthing is fine

yes but in this case the tar file is not uncompressed its compressed
