### ISSUE TITLE
J4.4.8 - Mobile display - click on "dropdownlist actions" generate the close of the menu

### ISSUE THREAD

**Issue by fuscage** [joomla/joomla-cms#44218]
### Steps to reproduce the issue
Change the width of your browser to display like a "mobile" (or try with on your mobile )
Go to the content list (articles)
Click on the checkbox and try to archieve => you click on the "toggler-toolbar-icon" and after, when you try to click on the actions dropdownlist, the "toggler-toolbar" closes on itself : 

![Image](https://github.com/user-attachments/assets/6779eecc-df21-40de-a942-7cc07dc4e403)

### Expected result

Can click on dropdownlist actions to choose an action

### Actual result

the "toggler-toolbar" closes on itself

### System information (as much as possible)
joomla 4.4.8

### Additional comments
it's ok on joomla 4.4.6

**Comment by fgsw** [comment]
Duplicate report #44198, test #44199 .

**Comment by richard67** [comment]
Closing as duplicate report and because there is already a fix which will be available in the upcoming releases 4.4.9 and 5.2.0 which are scheduled for next week.
