### ISSUE TITLE
CustomField Option Search Index Taxonomie / and Taxonomie, Smart Index Error 

### ISSUE THREAD

**Issue by adiheutschi** [joomla/joomla-cms#44210]
### Steps to reproduce the issue
CustomField type Textarey, select the option Search: add as Taxonomy or Makes searchable and add as Taxonomy. Create posts with more than 256 characters of content in the CustomField. Perform Smart Search Index. In my case, there was already the CustomField Textarea and many posts with content in the CustomField.

### Expected result

Smart Search indexing should run without errors

### Actual result
See Printscreen

An error has occurred. Data too long for column 'title' at row 1

Debug Error Message:

Warning: Undefined property: stdClass::$value in /home/ad487/public_html/administrator/components/com_finder/src/Indexer/Helper.php on line 433

Warning: Undefined property: stdClass::$value in /home/ad487/public_html/administrator/components/com_finder/src/Indexer/Helper.php on line 440
{"force":false,"options":{"word_match":"exact","show_taxonomy":"1","show_description":"1","description_length":255,"show_image":"0","image_class":"","link_image":"0","show_date":"1","show_url":"1","gather_search_statistics":"0","allow_empty_query":"0","show_autosuggest":"1","show_suggested_query":"1","show_explained_query":"1","show_advanced":"1","show_advanced_tips":"1","expand_advanced":"0","show_date_filters":"0","sort_order":"relevance","sort_direction":"desc","highlight_terms":"1","opensearch":"1","opensearch_name":"","opensearch_description":"","tuplecount":"1","batch_size":"50","title_multiplier":"1.7","text_multiplier":"0.7","meta_multiplier":"1.2","path_multiplier":"2","misc_multiplier":"0.3","enable_logging":"1","language_default":"","filter_commonwords":"0","filter_numerics":"0","memory_table_limit":20971},"weights":{"1":1.7,"2":0.7,"3":1.2,"4":2,"5":0.3},"startTime":"2024-10-04 14:38:01","batchSize":50,"batchOffset":0,"totalItems":0,"pluginState":[],"start":0,"complete":0,"rendered":"Result Object<\/legend>
url<\/dt>
index.php?option=com_content&view=article&id=<\/dd>
route<\/dt>
index.php?option=com_content&view=article&id=<\/dd>
title<\/dt>
<\/dd>
description<\/dt>
<\/dd>
published<\/dt>
<\/dd>
state<\/dt>
0<\/dd>
access<\/dt>
<\/dd>
language<\/dt>
*<\/dd>
publish_start_date<\/dt>
<\/dd>
publish_end_date<\/dt>
<\/dd>
start_date<\/dt>
<\/dd>
end_date<\/dt>
<\/dd>
list_price<\/dt>
<\/dd>
sale_price<\/dt>
<\/dd>
type_id<\/dt>
3<\/dd>
defaultLanguage<\/dt>
de-DE<\/dd><\/dl><\/fieldset>Additional Elements<\/legend>
layout<\/dt>
article<\/dd>
context<\/dt>
com_content.article<\/dd>
params<\/dt>
{\"article_layout\":\":default\",\"show_title\":\"0\",\"link_titles\":\"0\",\"show_intro\":\"0\",\"info_block_position\":\"0\",\"info_block_show_title\":\"1\",\"show_category\":\"0\",\"link_category\":\"0\",\"show_parent_category\":\"0\",\"link_parent_category\":\"0\",\"show_associations\":\"0\",\"flags\":\"1\",\"show_author\":\"0\",\"link_author\":\"0\",\"show_create_date\":\"0\",\"show_modify_date\":\"0\",\"show_publish_date\":\"0\",\"show_item_navigation\":\"1\",\"show_vote\":\"0\",\"show_readmore\":\"1\",\"show_readmore_title\":\"0\",\"readmore_limit\":100,\"show_tags\":\"1\",\"record_hits\":\"1\",\"show_hits\":\"0\",\"show_noauth\":\"0\",\"urls_position\":0,\"captcha\":\"0\",\"show_publishing_options\":\"1\",\"show_article_options\":\"0\",\"show_configure_edit_options\":\"0\",\"show_permissions\":\"0\",\"show_associations_edit\":\"0\",\"save_history\":\"1\",\"history_limit\":10,\"show_urls_images_frontend\":\"0\",\"show_urls_images_backend\":\"1\",\"targeta\":0,\"targetb\":0,\"targetc\":0,\"float_intro\":\"right\",\"float_fulltext\":\"right\",\"category_layout\":\":default\",\"show_category_title\":\"0\",\"show_description\":\"0\",\"show_description_image\":\"0\",\"maxLevel\":\"-1\",\"show_empty_categories\":\"0\",\"show_no_articles\":\"1\",\"show_category_heading_title_text\":\"1\",\"show_subcat_desc\":\"1\",\"show_cat_num_articles\":\"1\",\"show_cat_tags\":\"1\",\"show_base_description\":\"1\",\"maxLevelcat\":\"-1\",\"show_empty_categories_cat\":\"0\",\"show_subcat_desc_cat\":\"0\",\"show_cat_num_articles_cat\":\"0\",\"num_leading_articles\":1,\"blog_class_leading\":\"\",\"num_intro_articles\":4,\"blog_class\":\"\",\"num_columns\":2,\"multi_column_order\":\"0\",\"num_links\":4,\"show_subcategory_content\":\"0\",\"link_intro_image\":\"0\",\"show_pagination_limit\":\"0\",\"filter_field\":\"hide\",\"show_headings\":\"0\",\"list_show_date\":\"0\",\"date_format\":\"\",\"list_show_hits\":\"0\",\"list_show_author\":\"0\",\"display_num\":\"10\",\"list_show_votes\":\"0\",\"list_show_ratings\":\"0\",\"orderby_pri\":\"none\",\"orderby_sec\":\"rdate\",\"order_date\":\"published\",\"show_pagination\":\"2\",\"show_pagination_results\":\"1\",\"show_featured\":\"show\",\"show_feed_link\":\"1\",\"feed_summary\":\"0\",\"feed_show_readmore\":\"1\",\"sef_ids\":1,\"custom_fields_enable\":\"1\",\"workflow_enabled\":\"0\"}<\/dd>
metadata<\/dt>
{}<\/dd>
summary<\/dt>
<\/dd>
body<\/dt>
<\/dd>
metaauthor<\/dt>
<\/dd>
jsfield_vorderseite<\/dt>
<\/dd><\/dl><\/fieldset>Instructions<\/legend>
Title context<\/dt>
[\"title\",\"subtitle\",\"id\"]<\/dd>
Text context<\/dt>
[\"summary\",\"body\"]<\/dd>
Meta context<\/dt>
[\"meta\",\"list_price\",\"sale_price\",\"metakey\",\"metadesc\",\"metaauthor\",\"author\",\"created_by_alias\",\"jsfield_vorderseite\"]<\/dd>
Path context<\/dt>
[\"path\",\"alias\"]<\/dd>
Misc context<\/dt>
[\"comments\"]<\/dd><\/dl><\/fieldset>Taxonomies<\/legend>
Type<\/dt>
[{\"title\":\"Article\",\"state\":1,\"access\":1,\"language\":\"\",\"nested\":false}]<\/dd>
Category<\/dt>
[{\"title\":\"ROOT\",\"state\":1,\"access\":1,\"language\":\"\",\"nested\":true,\"node\":{\"id\":\"root\",\"asset_id\":0,\"parent_id\":0,\"lft\":0,\"rgt\":139,\"level\":0,\"extension\":\"system\",\"title\":\"ROOT\",\"alias\":\"root\",\"description\":\"\",\"published\":1,\"checked_out\":null,\"checked_out_time\":null,\"access\":1,\"params\":\"{}\",\"metadesc\":\"\",\"metakey\":\"\",\"metadata\":\"\",\"created_user_id\":0,\"created_time\":\"2009-10-18 16:07:09\",\"modified_user_id\":0,\"modified_time\":\"2009-10-18 16:07:09\",\"hits\":0,\"language\":\"\",\"numitems\":null,\"slug\":\"1:root\",\"assets\":null,\"note\":\"\",\"path\":\"\",\"version\":1}}]<\/dd>
Language<\/dt>
[{\"title\":\"*\",\"state\":1,\"access\":1,\"language\":\"\",\"nested\":false}]<\/dd><\/dl><\/fieldset>"}

### System information (as much as possible)

Joomla Version 5.1.4 PHP 8.1,8.2,8.3

**Comment by rdeutz** [comment]
looks like a duplicate, closing this one
