### ISSUE TITLE
Increased size of article, category and menu titles

### ISSUE THREAD

**Issue by pioada** [joomla/joomla-cms#44231]
Can we increase size of article, category and menu titles to make Joomla more flexible and use it not only for blogs but also for non-standard, highly specialized purposes like eg. gov websites with legal acts which sometimes have very long titles.
Currently the maximum length of titles in Joomla is 255 characters (varchar field in DB) while in WP it is Text field (65,535 characters).
This change will increase flexibility of Joomla.
More over, it is possible to migrate from Joomla to WP with few clicks, but very difficult the other way round. This could be the first step to make it possible in future.
Changing the size of titles requires changing the length of the title field in the table "finder_links" (if full titles are required in that table).

**Comment by fgsw** [comment]
Double issue, opened in "Discussions" by @pioada at Sep 5, 2024: #44021

**Comment by pioada** [comment]
Yes, but there were no comments there so I assumed that everyone agreed with my proposal :) and moved it to issues.
Theoretically, this only requires changes to the forms and database structure. The column in the database will increase so there should be no problems with that. But I don't know how com_finder will react to this.

**Comment by brianteeman** [comment]
Please close this and stick to the discussion. We have enough to track without duplications

**Comment by chmst** [comment]
@pioada if nobody commented on discussion, it is proably because no one is interested in this question. 

My tip: Write write  '<h2>' Title long as you want '</h2>' in the article and set the param show_title off.
