### ISSUE TITLE
Smart search filter options text hardcoded

### ISSUE THREAD

**Issue by Pinkeltje** [joomla/joomla-cms#44249]
### Steps to reproduce the issue
Create a new filter in Smart Search

### Expected result

All options shown as language constants thus enabling multilanguage and/or translation

### Actual result
Text "Events" is hardcoded.
![Image](https://github.com/user-attachments/assets/b36bbb18-5856-4f6a-822a-6df1adfb3741)
Same in frontend
![Image](https://github.com/user-attachments/assets/499c90a8-8262-43df-ae67-71acfdc4bb38)

### System information (as much as possible)
Joomla 5.1.4

**Comment by fgsw** [comment]
Is "Events" from a Core-Component?

A 5.2-Installation using Sample data Multilingual + Blog show:

![Image](https://github.com/user-attachments/assets/629f2b08-e10d-4388-bfbe-065a58e2d22f)

**Comment by Pinkeltje** [comment]
Found it:
PLG_FINDER_QUERY_FILTER_BRANCH_P_EVENT
PLG_FINDER_QUERY_FILTER_BRANCH_S_EVENT
Somehow it shows fixed text Event when installing finder plugin for events extension like JEM of RSEvents. But language overrides now solved it.

**Comment by richard67** [comment]
So this issue can be closed?
