### ISSUE TITLE
Blank page on extensions page link

### ISSUE THREAD

**Issue by lushdomain** [joomla/joomla-cms#44244]
FYI

The URL from the link:

Uses [Joomla! Update System

[https://extensions.joomla.org/support/knowledgebase/item/joomla-update-system-requirement/](url)

from the extensions pages, just below the download button for the extension just returns a blank page.

There's no console error recorded, just empty html

<html><head></head><body></body></html>

**Comment by fgsw** [comment]
Report the issue at https://github.com/joomla/jed-issues/issues/new

**Comment by Quy** [comment]
Closing as this is the wrong repo to report this issue. Thanks.
