### ISSUE TITLE
Cache buttons not displayed on 5.2.0 (tested on RC2 to RC4)

### ISSUE THREAD

**Issue by fontanil** [joomla/joomla-cms#44247]
### Steps to reproduce the issue

Open the system page, goto cache

### Expected result

buttons delete, delete all and Clear expired cache displayed

### Actual result

on some sites buttons delete, delete all and Clear expired cache are no more displayed

### System information (as much as possible)

Joomla! 5.2.0 RC2 to RC4, PHP 8.1 to 8.3, MariaDB 10.5 and 10.6

### Additional comments
Tested on several sites: some display the buttons, other not. No error in the console
error reporting to maximum, debugging to on. 
What can explain that?

![Image](https://github.com/user-attachments/assets/f546d84e-bd17-49aa-a567-2588470bcee3)

**Comment by fontanil** [comment]
On another test site, PHP 8.1 MariaDB 10.5and 5.2.0-beta2: no buttons

All sites were previously in 5.1.4

**Comment by fontanil** [comment]
#> On another test site, PHP 8.1 MariaDB 10.5and 5.2.0-beta2: no  @buttons
> 
> All sites were previously in 5.1.4
> 
> The source of the page for the toolbar: `
> 
> 
> [ Options ](index.php?option=com_config&view=component&component=com_cache&path=&return=aHR0cHM6Ly9qb2FrdHJlZTIucGFyLXJvYmVydGcuZnIvYWRtaW5pc3RyYXRvci9pbmRleC5waHA%2Fb3B0aW9uPWNvbV9jYWNoZQ%3D%3D) `

**Comment by uGE70** [comment]
I also founf the message "Select the Clear Expired Cache button in the toolbar to delete all expired cache files." is a bit confusing when this button isn't visible anymore, because the cache folder is empty. I thought there was something wrong with the cache buttons at first.

**Comment by Quy** [comment]
Please test PR #44349. Thanks.
