### ISSUE TITLE
Deprecation warning / MySQL / Warning: #1681 Integer display width is deprecated and will be removed in a future release.

### ISSUE THREAD

**Issue by schultz-it-solutions** [joomla/joomla-cms#44258]
Not sure this qualifies as a "bug report". I stumbled accross this deprecation warning in another setting (not Joomla! related).
However I belief it is worth checking if Joomla! needs to act on this one.

### Additional comments
On installing an (non Joomla!) application on a PHP / MySQL instance, I received the above mentioned deprecation warning:

Warning: #1681 Integer display width is deprecated and will be removed in a future release.

The (suggested) solution is to get rid of all the INT(x) declarations in the database and replace them with just  INT declarations.
The "display width do not affect the storage size of the data type" according to my research
https://stackoverflow.com/questions/58938358/mysql-warning-1681-integer-display-width-is-deprecated

So it might be useful to deal with this issue, before users get confused by these deprecation warnings

cheers
Ruediger Schultz

**Comment by alikon** [comment]
thanks for reporting, for what i'm aware of joomla are not impacted by this
 maybe @richard67  can confirm

**Comment by richard67** [comment]
That has been fixed for the Joomla core long time ago, but I haven't checked recently if someone has reintroduced that deprecated display widths for integers.

**Comment by schultz-it-solutions** [comment]
The latest websites I setup (from scratch) with Joomla 4 and 5 still have those "int(10)" declarations.

**Comment by richard67** [comment]
> The latest websites I setup (from scratch) with Joomla 4 and 5 still have those "int(10)" declarations.

I've just checked all SQL files for 5.2-dev and they do not use any "int(" or similar.

What might have happened in your case is following.

For MySQL 8 the display widths for integer types were deprecated, but MariaDB still uses them and used default values when they are not given like it is in our SQL files. So if you e.g. export a database from MariaDB and import it into MySQL 8, you will get a lot of deprecated warnings.

@schultz-it-solutions Are you using MariaDB?

**Comment by schultz-it-solutions** [comment]
Sorry for this confusion.
@richard67 
I just checked the 4.2 branch and you are right, there are no INT(x) declarations - so they have been removed long time ago as you said.

your answer is spot on. That is most probably exactly what happend:
My development environment is on MariaDB (where those INT(x) values were probably included by MariaDB while setting up the database.
The production system for that application is on MySQL, which threw those deprecation warnings, when we "inital loaded" the database from the MariaDB test environment.

Please consider this issue closed!

cheers
Ruediger

**Comment by richard67** [comment]
Closing as not a core issue. See previous comments for explanation. @schultz-it-solutions Anyway thanks for reporting. Better safe than sorry.
