### ISSUE TITLE
[5.3] Can't select menu item type

### ISSUE THREAD

**Issue by drmenzelit** [joomla/joomla-cms#44250]
### Steps to reproduce the issue
Create a menu item, click on Select Menu Item Type

### Expected result
You can select a menu type

### Actual result
You can't
![Image](https://github.com/user-attachments/assets/99a43a22-e06b-49c6-8ba8-3c11e76947f2)

### System information (as much as possible)
Joomla 5.3.0-alpha1-dev

**Comment by fgsw** [comment]
Issue confirmed.

**Comment by drmenzelit** [comment]
Changes introduced with https://github.com/joomla/joomla-cms/pull/44164

**Comment by rdeutz** [comment]
Closing as we are having a fix
