### ISSUE TITLE
Some core XML manifests (partially) wrong

### ISSUE THREAD

**Issue by leeroy1821** [joomla/joomla-cms#44252]
### Steps to reproduce the issue

Install new Joomla! 5.2 rc2

Look in side XML manifest files for Joomla! extensions

### Expected result

XML manifest files have only files and folders I see in Joomla! 5.2

### Actual result

I find XML manifest files with old files and folders. Maybe old joomla 3 left over?

* com_admin, has backend `forms` folder
* com_banners, has frontend language files
* com_messages, has frontend language files
* com_users, has frontend `layouts` folder
* com_actionlogs, has backend `layouts` folder
* com_workflow, has backend `access.xml`
* lib_joomla, has `compat` `joomla` and `legacy` folders but not folders I see in side `libraries`
* mod_stats_admin, has 4 languages which are not in Joomla!
* plg_editors_tinymce, has media/editors not media/plg_editors_tinymce

### System information (as much as possible)

Joomla! 5.2 rc2

I have checked 5.2-dev branch, same problem

### Additional comments

Not high priority. I read https://manual.joomla.org/docs/web-services-api/ and I understand the right way. If annoying just close. Thx

**Comment by richard67** [comment]
Well the manifests for core extensions have not really been maintained in recent times. It was once subject of discussions to completely remove them. But I understand that they currently are not really good examples.

**Comment by brianteeman** [comment]
I made a PR to fix these #444269 but have not yet done the mod_stats_admin language string as that needs a different PR with a deprecation notice.

**Comment by brianteeman** [comment]
PR to mark unused language strings  created #44271 

I believe this issue can now be closed as completed

**Comment by richard67** [comment]
Closing as having a pull request. Please test #44269 . Thanks in advance.
