### ISSUE TITLE
iframe menu item no relative url allowed

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#44262]
### Steps to reproduce the issue
Create a menu item type Wrapper >>> iframe
In the url field place a relative url (as per https://docs.joomla.org/Help5.x:Menu_Item:_Iframe_Wrapper#Form_Fields)

In the Advanced tab set 'Auto Add' to No
Give the menu item a Title and save

### Expected result
The item will save and will appear in the front end 

### Actual result
The url is prefixed with http://http///
An error message appears
Invalid URL: URL schema is missing in http:///index.php/typography. Please add one of the following at the beginning: http, https, ftp, ftps, gopher, mailto, news, prospero, telnet, rlogin, sftp, tn3270, wais, mid, cid, nntp, tel, urn, ldap, file, fax, modem, git.
(I used typography as the target)

### Additional comments
I tried by prefixing the relative url with http:/// as said in the error message and it saved but prefixed the url with http://

Looks like the 'Auto Add' setting is being ignored and the docs are incorrect?

**Comment by rdeutz** [comment]
Joomla Version?

**Comment by rdeutz** [comment]
Tried to break it with 5.2, works as I think it should work.

**Comment by SniperSister** [comment]
See #44315 and #44316

**Comment by richard67** [comment]
Closing as having a pull request. Please test #44314 . Thanks in advance.
