### ISSUE TITLE
[5.2] Unstyled Help pages

### ISSUE THREAD

**Issue by ceford** [joomla/joomla-cms#44265]
### Steps to reproduce the issue

Select any Help button in Joomla 5.2

### Expected result

Help page as in 5.1

### Actual result

The Help page is unstyled and comes with the Other Languages line at the top.

### System information (as much as possible)

Firefox and Google Chrome on Mac

### Additional comments

Console says:

None of the “sha384” hashes in the integrity attribute match the content of the subresource. The computed hash is “VMFuiq1CexX3pTawzpDQc6a+kD3nwPRwfvLfjswvgDmhAZkdhjWlQGn5qi4Bdyfh”.

**Comment by brianteeman** [comment]
Bug confirmed

**Comment by brianteeman** [comment]
Also the exact same problem from the help dashboard

**Comment by tecpromotion** [comment]
I get an error in the console:

`Failed to find a valid digest in the 'integrity' attribute for resource 'https://help.joomla.org/media/css/help.css?id=e20b125433d3c5b775062c8b7292e9de' with computed SHA-384 integrity 'VMFuiq1CexX3pTawzpDQc6a+kD3nwPRwfvLfjswvgDmhAZkdhjWlQGn5qi4Bdyfh'. The resource has been blocked.`

**Comment by tecpromotion** [comment]
We now have a merged PR https://github.com/joomla/help.joomla.org/pull/71 and are waiting for the CDN deployment. After that, it should work again. Incidentally, unfortunately this is not something that will not work properly in 5.2. The problem has existed for some time.

**Comment by Hackwar** [comment]
Now it works. Closing issue.
