### ISSUE TITLE
[5.2][SEF] Articles and categories are not redirected to versions of pages without IDs

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#44263]
### Steps to reproduce the issue
1. Articles -> Optoions -> Integration -> Routing -> Remove IDs from URLs -> Yes
2. System -> Plugins -> System - SEF -> Strict Routing -> Yes

If your website previously had **disabled** `SEF` options, then old links that have an ID's will not be automatically redirected to new versions of pages without an ID's.

For example: 
1. a category that had an ID will not be automatically redirected to a version of the category without an ID (the page will be available here at the old URL)
2. an article that had an ID will not be automatically redirected to a version of the article without an ID (there will be a 404 error here)

### Expected result
these pages will be automatically redirected to new versions without ID:
`site.com/category/11-super-category` -> `site.com/category/super-category`
`site.com/category/1-article` -> `site.com/category/article`

### Actual result
`site.com/category/11-super-category` -> `site.com/category/11-super-category` (the same page)
`site.com/category/1-article` -> `site.com/404` (404 page)

### System information (as much as possible)
Joomla 5.2
![Image](https://github.com/user-attachments/assets/59e78dff-ca24-4c32-a5d2-4771a61f3829)
![Image](https://github.com/user-attachments/assets/a5469a76-f5b2-4093-8340-9ab4d3d9ecef)

### Additional comments
other types of redirects work well, but redirecting pages with an ID to a version without an ID does not work at all.

**Comment by Hackwar** [comment]
Are you saying that this worked on the past or that you are expecting this from the new strict routing option?

**Comment by Hackwar** [comment]
URLs with modern routing in J3 will be identical in J4. URLs without modern routing in J3 will be identical in J4 as long as there isn't more than one level of categories after the part of the menu item. URLs in J4 and J5 are identical.

**Comment by Hackwar** [comment]
We did not claim that strict routing will fix all issues and solve all site setups. The current changes don't support what you are asking for. To be a bit blunt: if your site has IDs enabled, then didn't disable them, at least not now. This isn't a bug, but a feature request.
