### ISSUE TITLE
Existing tags not appearing when start typing in create article

### ISSUE THREAD

**Issue by astrodene** [joomla/joomla-cms#44279]
### Steps to reproduce the issue
open a new article and start typing a known tage into the tag box

### Expected result
a filtered list of tags appears getting more accurate the more you type

### Actual result
an unfiltered list of 30 exiting tags appears which stays the same until you have typed 3 letters after which no tags appear

### System information (as much as possible)
5.2.0. Updated from previous release version

**Comment by fgsw** [comment]
Which Joomla-Version? Is it a fresh install, an update …?

**Comment by fgsw** [comment]
Can you give System Informations (as much as possible) in the opening comment so users get basic information at beginning of thread.

**Comment by Quy** [comment]
Please post to Joomla forum for support questions. https://forum.joomla.org/
