### ISSUE TITLE
PluginHelper::getPlugin returns array as default - object expected

### ISSUE THREAD

**Issue by brbrbr** [joomla/joomla-cms#44270]
### Steps to reproduce the issue
Disable the SEF plugin and enable maximum login

### Expected result

No warnings

### Actual result

Warning: Attempt to read property "params" on array in [ROOT]libraries/src/Component/Router/Rules/MenuRules.php

### System information (as much as possible)

Joomla 5.2

### Additional comments

PluginHelper::getPlugin should probably return an empty object for  $plugin !== null

**Comment by Fedik** [comment]
As result of:
- https://github.com/joomla/joomla-cms/pull/42989

**Comment by Hackwar** [comment]
Ok, I understand what one has to do with the other. I'll create a PR to fix that. In the meantime I created #44282 to introduce a new method for retrieving a list of plugins. Thanks for reporting this.
