### ISSUE TITLE
Media manager error, when "Path to Files Folder" field contain folder that not in the plugin "FileSystem - Local", COM_MEDIA_ERROR_ACCOUNT_NOT_FOUND

### ISSUE THREAD

**Issue by spike277** [joomla/joomla-cms#44277]
### Steps to reproduce the issue
If the standard image directory is changed under Plugins System File System, TinyMCe produces an error message
COM_MEDIA_ERROR_ACCOUNT_NOT_FOUND

Please fix it. Thanks

**Comment by brianteeman** [comment]
This appears to be the result of the changes made in https://github.com/joomla/joomla-cms/pull/43579

I can replicate the bug and if I revert the changes in that PR the bug is cleared.

Hope that helps someone to resolve the bug

**Comment by Fedik** [comment]
It is not very clear how to reproduce the error.
After update to 5.2 TinyMCE works, drag&drop upload works, for me.

**Comment by Fedik** [comment]
I found it can only happen when "Media: Options" => "Path to Files Folder" field contain folder that not in the plugin "FileSystem - Local".
Can someone confirm?

**Comment by Fedik** [comment]
Okay, anyway. To fix this error on your site, please make sure the folder in "Media: Options" => "Path to Files Folder"  also chosen in he plugin "FileSystem - Local".

It is strange behavior of Media manager, in https://github.com/joomla/joomla-cms/blob/d61c52e8d6920dface811cba064649a3c7524a26/administrator/components/com_media/src/Provider/ProviderManagerHelperTrait.php#L151

The https://github.com/joomla/joomla-cms/pull/43579  uncovered this bug.

**Comment by brianteeman** [comment]
> To fix this error on your site, please make sure the folder in "Media: Options" => "Path to Files Folder" also choosen in the plugin "FileSystem - Local".

That only partialy works. If you select a root folder eg plugins in the filesystem-local then you have to select a subfolder of plugins in tinymce. Leaving it empty in tinymce does not default to the plugins folder and still gives the error,

Either way thats not a real fix just a temp fix until code can be fixed and released.

**Comment by Fedik** [comment]
> If you select a root folder eg plugins in the filesystem-local then you have to select a subfolder of plugins in tinymce. 

Let say you have folder `files`. Then you have to:
- Edit Media manager global options, set "Path to Files Folder" to `files`
- Edit plugin "FileSystem - Local", and select `files` there.

Then TinyMCE will work even with empty value, all upload will be directly in to `files/` fodler.

> Either way thats not a real fix just a temp fix until code can be fixed and released.

Yeap.

**Comment by brianteeman** [comment]
it did not work for me with the empty as you described

**Comment by spike277** [comment]
@Fedik I know thanks, but thats no option for me. I hope for fix. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44277">issues.joomla.org/tracker/joomla-cms/44277</a>.</sub>

**Comment by Fedik** [comment]
Please test https://github.com/joomla/joomla-cms/pull/44313

**Comment by spike277** [comment]
Your solution in #44313 works only in Backend, Frontend still the same error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44277">issues.joomla.org/tracker/joomla-cms/44277</a>.</sub>

**Comment by LuxLOL** [comment]
This also happens if the Path to Files Folder or Images Folder has an uppercase.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44277">issues.joomla.org/tracker/joomla-cms/44277</a>.</sub>
