### ISSUE TITLE
Pre-update check for extensions never stops (returning a json error)

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#44284]
### Steps to reproduce the issue

I have tried to move a couple Joomla 5.1 sites to 5.2 under PHP 8.2.
I waited for the pre-update checker to finish its job of checking extensions.

### Expected result

Pre-update checks ends.

### Actual result

They never do.

### System information (as much as possible)

5.1 to 5.2 update
PHP 8.2.19
MySQL 8.0.32

### Additional comments

This is the error I get when looking at the data before the json info is parsed:

![Image](https://github.com/user-attachments/assets/a61a0cbd-dafc-4975-9af5-9c89ed674c3c)

```
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$length is deprecated in <b>E:\bearsampp\www\MyWork_5_latest_free\libraries\src\Updater\Update.php</b> on line <b>486</b><br />
<br />
<b>Deprecated</b>:  Creation of dynamic property Joomla\CMS\Updater\Update::$length is deprecated in <b>E:\bearsampp\www\MyWork_5_latest_free\libraries\src\Updater\Update.php</b> on line <b>486</b><br />
{"success":true,"message":null,"messages":null,"data":{"compatibility": ...
```

Having the warning in the response forces the json parsing to fail.

**Comment by exlemor** [comment]
I had the same issue on one site - initially I tried doing so as a test from an iPhone 15 Pro (via Safari) and also then when I got home from a laptop running Safari 18 same result/issue as above

**Comment by alikon** [comment]
can you check adding declaration of `$length`  in the Joomla\CMS\Updater\Update class , should solve

**Comment by rdeutz** [comment]
You can set the errror reporting to none, then you can continue with the update

**Comment by alikon** [comment]
#44307 will remove the deprecation

**Comment by richard67** [comment]
Closing as having a pull request. See #44307 .
