### ISSUE TITLE
https://magazine.joomla.org/faq dark mode

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-cms#44290]
### What needs to be fixed
https://magazine.joomla.org/faq in dark mode

### Why this should be fixed
It's not legible

### How would you fix it
Change the css to 
[data-rlta-element=container][data-rlta-state=ready][data-rlta-theme=neutral][data-rlta-type=accordions]>[data-rlta-element=button]
{
    color:black; /* or joomlas own 'black' color*/
    background-color: #fff;
    transition: background-color 200ms, border 200ms;
}

### Side Effects expected
None

**Comment by brianteeman** [comment]
Please report this to https://github.com/joomla/joomla-websites/issues/new?title=[jcm]%20&body=Please%20describe%20the%20problem%20or%20your%20issue

**Comment by rdeutz** [comment]
as Brian said, this is the wrong repo
