### ISSUE TITLE
[5.2] Articles do not have a [Print] or [Email] button.

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#44309]
### Steps to reproduce the issue
Open any article on the Joomla 5.2 website and you will not find the `Print` and `Email` button, even in the `Control Panel` settings you will not find the option to enable these buttons.

### Expected result
This is a screenshot of an article from Joomla 3, which had similar buttons.
These buttons have existed in Joomla articles since the creation of the CMS.

![Image](https://github.com/user-attachments/assets/651ed884-5e79-4c64-b1dc-1c8416160dc2)

### Actual result
These buttons don't even exist in Joomla 5.2

### System information (as much as possible)
Joomla 5.2

### Additional comments
These buttons should be returned to Joomla, they have always been part of Joomla.

**Comment by Quy** [comment]
See https://github.com/joomla/joomla-cms/pull/24025

**Comment by brianteeman** [comment]
There are a lot of extensions available that will offer you a "share" functionality. Joomla core can not include everything. 

https://extensions.joomla.org/category/social-web/social-share/

**Comment by brianteeman** [comment]
You cannot use web-share as it is not supported by all the browsers that joomla supports. That is a hard limit.

**Comment by HLeithner** [comment]
thanks for your feature request, but I'm closing this, since it's not expected that this feature will land in joomla. As already mentioned we have extensions in the JED which already solve this.
