### ISSUE TITLE
[5.2] Admin menu recovery mode

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#44317]
### Steps to reproduce the issue
Create a new admin menu. Either use a preset or add a menu item to it.
Publish this new admin menu in a module in position menu
After the message to turn on the menu recovery mode is displayed make sure you click on it to enable recovery mode

### Expected result
no errors

### Actual result
you might need to navigate to another page but a series of errors are displayed such as

Warning: Undefined property: Joomla\CMS\Menu\AdministratorMenuItem::$element in /home/public_html/administrator/modules/mod_menu/src/Menu/CssMenu.php on line 319

Warning: Undefined property: Joomla\CMS\Menu\AdministratorMenuItem::$class in /home/public_html/administrator/modules/mod_menu/src/Menu/CssMenu.php on line 495

**Comment by chmst** [comment]
Losing as there is a PR. Please test [#44318](https://github.com/joomla/joomla-cms/pull/44318)

**Comment by chmst** [comment]
Re-opening. The PR https://github.com/joomla/joomla-cms/pull/44318 fixes all PHP warnings, but not the issue with recovery mode.

**Comment by chmst** [comment]
Please test https://github.com/joomla/joomla-cms/pull/44318 again with recovery mode.
