### ISSUE TITLE
Firefox refuses to login

### ISSUE THREAD

**Issue by ConfidantCommunications** [joomla/joomla-cms#44325]
### Steps to reproduce the issue

Clear all cookies/session storage then login using Firefox, either front or back end.

### Expected result

You're logged in!

### Actual result

You are not logged in! No errors displayed on screen or in console.

### System information (as much as possible)

Firefox 131.0.3
Joomla! Version	5.2.0
PHP Version	8.2.23

### Additional comments
Chrome does not have this problem. I have AdminTools installed.

**Comment by Quy** [comment]
Please submit to Joomla forum for support. https://forum.joomla.org/

PS: I have no issues logging in with Firefox 131.0.3.
