### ISSUE TITLE
HTTP ERROR 400

### ISSUE THREAD

**Issue by HuynhMi** [joomla/joomla-cms#44344]
### Steps to reproduce the issue
These days, when I access my joomla website,

The page shows 

This page isn’t working
If the problem continues, contact the site owner.
HTTP ERROR 400

![Image](https://github.com/user-attachments/assets/2e745750-3881-45ff-b8a7-5c23dbe8a6ca)

### Additional comments
To resolve it temporarily, I need to clean the cache on browser.
What is the reason and how to solve it ?
My Joomla version is 5.2.0.

**Comment by fgsw** [comment]
Asked on [forum](forum.joomla.org)?

**Comment by HuynhMi** [comment]
@fgsw Can I ask for the issue link on forum ?

**Comment by fgsw** [comment]
> Can I ask for the issue link on forum ?

Thats what i have asked.

**Comment by Quy** [comment]
Please post to Joomla forum for support. https://forum.joomla.org/
