### ISSUE TITLE
Getting deprecation error strftime() function in Joomla5 with php 8.2

### ISSUE THREAD

**Issue by aberenguer78** [joomla/joomla-cms#44346]
### Is your feature request related to a problem? Yes Please describe.
I'm getting this error in the core class relative to joomla directory \libraries\src\Form\Field\CalendarField.php on line 323
Error:
Deprecated: Function strftime() is deprecated in C:\xamppPHP8.2\htdocs\joomla5\libraries\src\Form\Field\CalendarField.php on line 323

### Describe the solution you'd like
Substitute the function for the proper solution provided for this deprecation error. Search in Chat GPT

**Comment by aberenguer78** [comment]
This problem happens in releases of PHP 8.2 with joomla 5.2.0

**Comment by fgsw** [comment]
Duplicate report to https://github.com/joomla/joomla-cms/issues/43947. Close this issue and test Pull Request https://github.com/joomla/joomla-cms/pull/44114.

**Comment by alikon** [comment]
please test https://github.com/joomla/joomla-cms/pull/44114.

**Comment by aberenguer78** [comment]
I can not close, I consider that the solution provided is not good.
