### ISSUE TITLE
Frontend Editing not working on multi language page

### ISSUE THREAD

**Issue by mgretz** [joomla/joomla-cms#44355]
### Steps to reproduce the issue

I have a multi language page (en and de) where the user can edit on the frontend. Editing Modules is working as expected, but editing articles is not. You can hit save or save and close, but the changes where not saved into the database. 

I have a similar Webpage but without mulit language, there it is working as expected.

Both webpages are running joomla 5.2, php > 8.1.30 and mysql 8.0.39. It is also not working when logged in as super user, so i would doubt it is a privilege issue.

**Comment by fgsw** [comment]
Can't confirm, see Screenshots. Articles by "Multilingual Sample Data" modified and saved.

![Image](https://github.com/user-attachments/assets/da2db9f6-1d3e-4583-9f00-733840954a10)
![Image](https://github.com/user-attachments/assets/8964f60d-1a82-437a-a843-5aaef7ed82f4)
![Image](https://github.com/user-attachments/assets/e139cd25-3ae2-4d80-955a-6c89b402a454)

**Comment by ssnobben** [comment]
Go to forum post your settings there FPA.. better help directly with people. Forum Post Assistant (FPA) [https://forum.joomla.org/viewforum.php?f=806&sid=6290bc49c848b856534744275aa49e48](https://forum.joomla.org/viewforum.php?f=806&sid=6290bc49c848b856534744275aa49e48 "FPA")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44355">issues.joomla.org/tracker/joomla-cms/44355</a>.</sub>

**Comment by mgretz** [comment]
If anyone has the same issue:

The old google recatpcha v3 plugin was the cause. I uninstalled it and now frontend editing works as expected.

Frontend Editing also gaves the following error:

_empty solution not allowed. Invalid field: Captcha_
