### ISSUE TITLE
Joomla Update Options

### ISSUE THREAD

**Issue by dagroupinc** [joomla/joomla-cms#44352]
### Steps to reproduce the issue

Feature Request:

With the faster release schedule and the various potential compatibility issues it would be nice if the update component of Joomla could give you the option of what version of Joomla to update to.

For instance we're running v4.4.9 and would like to update/upgrade to v 5.1.4 and use the check extension/plugin feature but the only option Joomla gives us is to update to v5.2 which our environment is ready for.

**Comment by ssnobben** [comment]
Why you need to go to 5.1.4 instead of 5.2? Who told you that?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44352">issues.joomla.org/tracker/joomla-cms/44352</a>.</sub>

**Comment by dagroupinc** [comment]
1) I meant to say that not all of my extensions are compatible with 5.2
2) It would be nice to have the option or flexibility in Joomla to decide which version to upgrade to. (I could do this manually by uploading the 5.1.4 update but that circumvents the extension/plugin version check in Joomla)

**Comment by brianteeman** [comment]
That would be a bad idea. We always want people to be using the latest release.

**Comment by dagroupinc** [comment]
1) sites are running J4.4.9 or 5.1
2) we do incremental updates/upgrades to minimize issues such as extension and plug in conflicts
3) I’m not typically an early adopter of Joomla updates  (ie from 4 to 5) because of bugs

We eventually update but these are the reasons we prefer to do it in a managed and controlled way to minimize disruptions to our clients

**Comment by richard67** [comment]
That would technically mean that we have to keep entries in our update sites for all versions. I don't think that's a good idea.

**Comment by brianteeman** [comment]
This should be closed. It is bad practice not to install the current version espec if there is a security issue. As already stated by the op they can still chose to update to an out of date release using the upload and update option. Joomla shouldnt be doing anything more ergo there is nothing more to do here.

**Comment by bembelimen** [comment]
5.1.x is not a supported version anymore and it's not recommended to use it. Please use only the latest version of either the supported versions.

Before new (major/minor) versions are released there is [plenty of time to test before](https://github.com/joomla/joomla-cms/releases?q=candidate&expanded=true).
