### ISSUE TITLE
Show constants as tooltip debugging language Joomla 5.2

### ISSUE THREAD

**Issue by Stuartemk** [joomla/joomla-cms#44351]
Ideally, when activating the language debugging plugin in the backend, the debugging would be visible in the frontend only for the site administrator, but instead of showing all the constants in the frontend, the value would be shown "normally" but underlined, thanks to that the frontend would not become unreadable and neither would it deform the entire structure of the page as it currently happens, and that when positioning the cursor over the underlined value, the constant would be shown in the tooltip, in this way it is much more readable, more orderly and more intelligent, since generally when doing the debugging it knows exactly what is the value that it wants to overwrite but the constant of that value is unknown. In conclusion, instead of showing all the constants at the same time, it is better to show the values ​​in an identifiable way and only show the constant when hovering over the value. For example:

<u>value to change</u>

**Comment by brianteeman** [comment]
Why do you even want to know what the constant is. It is not needed for creating an override.

https://github.com/user-attachments/assets/9ad8d73b-f813-4122-9be0-aa774f024d7b

**Comment by brianteeman** [comment]
This should be closed here as you already opened the same subject at discussions. Posting the same thing in multiple places is not productive #42690
