### ISSUE TITLE
Admin Mobilre View

### ISSUE THREAD

**Issue by dagroupinc** [joomla/joomla-cms#44353]
### Steps to reproduce the issue
When logging in as an Admin using a mobile device the user interface is very poor and difficult to use. Can you make the UI more user friendly and easier to use? 

The pancake menu, Control Panel, and Toolbar text is very small and could be larger (iPhone 14)

Not that I use an iPhone to manage Joomla sites that often but occasionally I need to

**Comment by ssnobben** [comment]
What version of Joomla are you using? I just tested with Joomla 5.2 and its very easy to see and manage everything in Joomla backend also with mobile phone if that one is not stone age of course. The pancake menu you just click on and then you have all menus floating out no problem for me to see it very good and clear and you can use your phone/fingers to zoom in too if you know how to do that :)The control Panel is easy to navigate and do what you want and I was surprices how easy it was to use it though I guess most admin like me uses it when on desktop computer. The toolbar and all actions are on very easy to see modules covering what you need to do. And you know you can also modified set up your backend as you like so you just see and use the things you need there i f logged in as admin by mobile. Joomla 5 is very fast, secure and easy to use so I dont understand this complaining about something that is very good in Joomla. Sorry but maybe then change mobile phone if it and you can use the zoom function there?  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44353">issues.joomla.org/tracker/joomla-cms/44353</a>.</sub>

**Comment by dagroupinc** [comment]
using iPhone 15 — not that I use mobile that often . . .
• UI is much better in v5.x (sooooo much better!)
• UI is a bit difficult in v4.x which is what I was referring to (say'n bye bye)
• Only comment is that it might be nice if the categories like Site, System, etc. were collapsable so that you don't have to scroll as much. Not a biggie.

No real criticism just thoughts. Been a user since J1.5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44353">issues.joomla.org/tracker/joomla-cms/44353</a>.</sub>

**Comment by brianteeman** [comment]
interesting that you find v5 to be so much better than v4 on mobile as there has been hardly any changes at all to the UI

**Comment by Hackwar** [comment]
As you said yourself, Joomla 5 is acceptable in that regard. I don't see us doing major changes here. Because of that I'm going to close this ticket.
