### ISSUE TITLE
New article module from J5.2.0 deactivates sticky header!

### ISSUE THREAD

**Issue by WM-Loose** [joomla/joomla-cms#44369]
After a long search we found out the following:

If you use the new (from J5.2.0) post module and assign it to a module position, the sticky header (which appears when scrolling down with the menu and should always remain visible at the top) is deactivated (bypassed) on this page.

This only happens, however, if you use "Display / Layout / Horizontal" in the settings in the new module. If you switch to "Vertical", the sticky header function is executed again and the header appears on the page when scrolling down.

![Image](https://github.com/user-attachments/assets/fcde00aa-ddf0-4f8a-a73d-3b1c5b8e660b)

At first I thought that there was a conflict with Astroid Framework 3.1.6 and Template Two (and other templates designed for it), but now that it's also happening with the Joomshaper Helix Ultimate Framework with the helix ultimate template, I suspect a BUG in the new post module.

What's striking is that it only happens when the display layout is set to horizontal. In this case, the module completely removes the sticky header and deactivates this function. Not good at all...

You're welcome to test it yourself.

What now?

**Comment by drmenzelit** [comment]
Please test #44327

**Comment by WM-Loose** [comment]
Unfortunately not, even after the adjustment it doesn't work and the header still disappears.
![Image](https://github.com/user-attachments/assets/90c3f165-7a68-4e27-a468-4ed5f3f9617e)
![Image](https://github.com/user-attachments/assets/15cb34f1-691e-4d69-8688-72cc4286ced2)

**Comment by drmenzelit** [comment]
Did you installed the package from the PR or only the patch? It is a PR where you need to run npm to build the CSS files correctly. If you only change the mod-articles.css it will not work, because the old code is still in the minified version of the file (mod-articles.min.css)

**Comment by fgsw** [comment]
@WM-Loose post your test result at the Pull request #44327

**Comment by WM-Loose** [comment]
OK. I just made the change as shown in the screenshots. 
I'll test the package later. 
I can't say yet whether I'll be able to do it today.

**Comment by WM-Loose** [comment]
Please understand me. I always look for the PR download and it would be nice if we were always given a direct link here. 
Is this the link to the PR download and install with Code and download zip?

https://github.com/joomla/joomla-cms/tree/5.2-dev

**Comment by drmenzelit** [comment]
You can download the package here: https://artifacts.joomla.org/drone/joomla/joomla-cms/5.2-dev/44327/downloads/79997/
![Image](https://github.com/user-attachments/assets/669c66c7-2f95-4bd3-b134-712326fc1b05)

**Comment by WM-Loose** [comment]
Test successful. 
The sticky header now works.
Thanks

**Comment by fgsw** [comment]
@WM-Loose can you open https://issues.joomla.org/tracker/joomla-cms/44327 and 
- login with your github-account
- click button "Test this"
- mark "Tested successfully"

Now the test count as successfull.
