### ISSUE TITLE
[5.2] Error with trashing items when items are checked out

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#44364]
### Steps to reproduce the issue
In articles overview (probably also in other components). You need at least one item which is chechecked out by another user. 
Then mark this item and one or more other items and activate the actions button trash. 

### Expected result
All items except the checked-out item are trashed

### Actual result
No item is trashed but the message says "n-1 items are trashed" plus "checked-out" message

![Image](https://github.com/user-attachments/assets/1161b631-14e0-45a7-b86c-f46ba59f4cd6)

**Comment by alikon** [comment]
please check #44392
