### ISSUE TITLE
[5.3] Undefined array key

### ISSUE THREAD

**Issue by Quy** [joomla/joomla-cms#44363]
### Steps to reproduce the issue
Install 5.3 nightly build.
See warning in the last installation step.

### Actual result
![Image](https://github.com/user-attachments/assets/c3c3e0bd-0204-494e-b644-2e15c5fe97e6)

**Comment by HLeithner** [comment]
I would expect that it's might be related to https://github.com/joomla/joomla-cms/pull/44162 

/cc @Hackwar

**Comment by Quy** [comment]
PR  #44461
