### ISSUE TITLE
J4.4.9 Author alias not loading on article instead of created by

### ISSUE THREAD

**Issue by fusedNL** [joomla/joomla-cms#44374]
1. Create an article
2. Under publishing put a different name for Author alias
3. Load the article on the front end

Input:

![Image](https://github.com/user-attachments/assets/d42a807d-3adc-4c98-8a9c-ffa88a394498)

Output:
![Image](https://github.com/user-attachments/assets/a87254fe-4b24-4103-9971-09d0a02fb239)

Desired output:
Name should be the created by alias

**Comment by fgsw** [comment]
Can't confirm:

![Image](https://github.com/user-attachments/assets/07bd73cf-b56f-4462-a573-a5eca4289dde)
![Image](https://github.com/user-attachments/assets/87774d10-981e-439c-869d-def52290f112)

**Comment by fusedNL** [comment]
What could possibly be the issue here? I have loaded through a custom layout override the following code to debug. 

`<?php
// Force the use of created_by_alias if it exists, or fallback to author
$this->item->author = !empty($this->item->created_by_alias) ? $this->item->created_by_alias : $this->item->author;
echo 'Debug Author Alias: ' . $this->item->author;
?>`

Other steps I have tried are checking the database direct, clearing the cache, all to no resulkt.

**Comment by brianteeman** [comment]
Have a look t how core joomla does this. The code is in `layouts\joomla\content\info_block\author.php`

**Comment by fusedNL** [comment]
@brianteeman yes, that is where I copied the override from. It looks working there but just doesnt render the output the same way. So cannot find anything odd in the database or the core / overrides. 

As a background it is a site migrated from J3 to J4. I added a new article into the system and it brings the same result. The alias is not loaded.

`<?php

/**
 * @package     Joomla.Site
 * @subpackage  Layout
 *
 * @copyright   (C) 2013 Open Source Matters, Inc. <https://www.joomla.org>
 * @license     GNU General Public License version 2 or later; see LICENSE.txt
 */

defined('_JEXEC') or die;

use Joomla\CMS\HTML\HTMLHelper;
use Joomla\CMS\Language\Text;

?>
<dd class="createdby" itemprop="author" itemscope itemtype="https://schema.org/Person">
    <span class="icon-user icon-fw" aria-hidden="true"></span>
    <?php $author = ($displayData['item']->created_by_alias ?: $displayData['item']->author); ?>
    <?php $author = '<span itemprop="name">' . $author . '</span>'; ?>
    <?php if (!empty($displayData['item']->contact_link) && $displayData['params']->get('link_author') == true) : ?>
        <?php echo Text::sprintf('COM_CONTENT_WRITTEN_BY', HTMLHelper::_('link', $displayData['item']->contact_link, $author, ['itemprop' => 'url'])); ?>
    <?php else : ?>
        <?php echo Text::sprintf('COM_CONTENT_WRITTEN_BY', $author); ?>
    <?php endif; ?>
</dd>
`

**Comment by brianteeman** [comment]
without seeing the rest of your template, overrides etc its not possible to comment further. Even with that information this is **not** the place to fix the code in your template.

**Comment by Quy** [comment]
Please submit to Joomla forum for support. https://forum.joomla.org/

**Comment by fusedNL** [comment]
@brianteeman agreed, even with any of the overrides disabled it still isnt working out of the box. Thought it might be a bug in the core hence my post here. I will check whether the current site template has issues.
