### ISSUE TITLE
URL in email broken with Mail Template Layout

### ISSUE THREAD

**Issue by leeroy1821** [joomla/joomla-cms#44377]
### Steps to reproduce the issue

Mail template `com_users.password_reset`

HTML Body:
```html
<p>Hello,</p>
<p>
	A request has been made to reset your {SITENAME} account password. To reset your password, you will need to submit this verification code to verify that the request was legitimate.
</p>
<p>
    The verification code is {TOKEN}
</p>
<p>
	Click <a href="{LINK_HTML}">here</a> and proceed with resetting your password.    
</p>
<p>
    Thank you.
</p>
```

### Expected result

URL in email is correct: `https://www.mysite.com/component/users/reset.html?layout=confirm&amp;token=blablabla&amp;Itemid=123`

### Actual result

URL in email is broken: `https://www.mysite.com/https://www.mysite.com/component/users/reset.html?layout=confirm&amp;token=blablabla&amp;Itemid=123`

The `https://www.mysite.com` is dobled in email.

### System information (as much as possible)

* Joomla! 5.2.0
* PHP 8.3.13

### Additional comments

When I put Mail Template Layout to No, problem not exist. Make me think Mail Template Layout is problem.

I look in MailTemplate. Line 331 `$htmlBody = MailHelper::convertRelativeToAbsoluteUrls($htmlBody);`. Add `var_dump($htmlBody);` next to it. I see `<a href="https://www.mysite.com/{LINK_HTML}">`. But LINK_HTML already have `https://www.mysite.com/`! This comes the problem, no?

I move `$htmlBody = MailHelper::convertRelativeToAbsoluteUrls($htmlBody);` after the big if layout and problem not exist.

**Comment by webmasterab** [comment]
I also have this URL problem with the emails that are now sent by Joomla 5.2.

Very annoying.
How nice that there is a solution soon.
However, it is better to submit this as a pull request, then if it works and the test is successful, it can be adopted in the core.

Do you know how to create a pull request?

**Comment by leeroy1821** [comment]
I made pull request https://github.com/joomla/joomla-cms/pull/44378

Thanks!

**Comment by fgsw** [comment]
@leeroy1821 can you close this Issue as you have created a Pull Request?

**Comment by leeroy1821** [comment]
Close issue. See all Pull Request https://github.com/joomla/joomla-cms/pull/44378  Thanks!
