### ISSUE TITLE
Under MySQL 5.1, upgrading Joomla 2.5 to 3.3.6 fails on SQL update 3.1.0

### ISSUE THREAD

**Issue by joeyadams** [joomla/joomla-cms#4437]
I get the following message when I try to upgrade Joomla from 2.5.18 to 3.3.6 under MySQL 5.1 and IIS 8:

    Fatal error: Call to undefined method RuntimeException::get() in C:\inetpub\wwwroot\libraries\joomla\error\error.php on line 803

MySQL 5.1+ is listed as the minimum and recommended version for Joomla 3.x in [Technical Requirements][1].

By looking at logs/joomla_update.php, I saw that it stopped on update 3.1.0.  When I run the SQL updates manually (replacing #_ with jos) on a 2.5.18 database, I get an error on the 3.1.0 update:

    ERROR 1366 (HY000) at line 93: Incorrect integer value: '' for column 'created_user_id' at row 1

Here is the offending SQL command:

    INSERT INTO `#__tags` (`id`, `parent_id`, `lft`, `rgt`, `level`, `path`, `title`, `alias`, `note`, `description`, `published`, `checked_out`, `checked_out_time`, `access`, `params`, `metadesc`, `metakey`, `metadata`, `created_user_id`, `created_time`,`created_by_alias`, `modified_user_id`, `modified_time`, `images`, `urls`, `hits`, `language`, `version`)
    VALUES (1, 0, 0, 1, 0, '', 'ROOT', 'root', '', '', 1, 0, '0000-00-00 00:00:00', 1, '{}', '', '', '', '', '2011-01-01 00:00:01','', 0, '0000-00-00 00:00:00', '', '',  0, '*', 1);

The problem is in `'', '2011-01-01 00:00:01'`.  It is supplying `''` instead of `0` for the `created_user_id`.  This command fails on MySQL 5.1, but succeeds on MySQL 5.5.

 [1]: http://www.joomla.org/technical-requirements.html

**Comment by brianteeman** [comment]
In the absence of any repsonse I am closing this as a duplicate report of #4311 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4437">issues.joomla.org/joomla-cms/4437</a>.</sub>
