### ISSUE TITLE
xml sha verification for update server

### ISSUE THREAD

**Issue by tkuschel** [joomla/joomla-cms#44370]
I've already fallen into the trap twice now of using a checksum (sha256, sha384, sha512) for the downloadable extension file with a line break or spaces like in the file “https://update.joomla.org/core/j4/default.xml” shown here when creating the XML according to the instructions on https://manual.joomla.org/docs/building-extensions/install-update/update-server/#extension-server-type.
After all, the lower and upper case of the sha value is currently taken into account and an additional trim for the value would make it easier for a developer to make fewer mistakes when creating it.
Currently, you are not allowed to set a line break or spaces between the html directives, e.g. with \<sha512\> and \</sha512\>, otherwise the update for the extension will not shown (without any comment).

It would of course also be possible to change the instruction so that it is clear in the description that no characters other than the SHA code should be placed between the html directives. But then why is a `strtolower($hashRemote)` set in the comparison of the two hashes? - In my opinion, a trim command is appropriate, as already provided in PR #44336.
What do you think, is there something against this addition?

Best regards Thomas

### Steps to reproduce the issue
* Presrequisites
    
    * You need a (self-written) extension with a version number that is already installed on your Joomla CMS.
    * You also need an update server on which a new version of this extension is available.

- Create an extension package for a component for Joomla, with a new version (version > active version on Joomla)
- Make an update service according to the instructions of https://manual.joomla.org/docs/building-extensions/install-update/update-server/
- Zip the extension and create a `sha512sum \<myextension\>.zip`
- Extend the update-server file with the specified sha512 value between the html derivatives \<sha512\> and \<\sha512\> as described in https://manual.joomla.org/docs/building-extensions/install-update/update-server/#extension-server-type
- Use a line break and spaces, just like in the description.

### Expected result
In the backend `<yourside>/administrator`, in the tab "notification": after displaying "checking extensions..." a red field "update is available (1)" is shown. And we can start an update process.

### Actual result
In the backend `<yourside>/administrator`, in the tab "notification":  a green colored "Extensions are up to date." is shown.
No update of the extension is available.

### System information (as much as possible)
Joomla 5.2, also with Joomla 5.0 and Joomla 5.1 series.

### Additional comments
PR #44336

**Comment by alikon** [comment]
closing as we have a pr https://github.com/joomla/joomla-cms/pull/44336

**Comment by tkuschel** [comment]
The issue still exists because PR 44336 is not being processed.
