### ISSUE TITLE
ArticleModel broken in CLI

### ISSUE THREAD

**Issue by leeroy1821** [joomla/joomla-cms#44395]
### Steps to reproduce the issue

Make CLI app which create instance of ArticleModel: `$article = \Joomla\CMS\Factory::getApplication()->bootComponent('com_content')->getMVCFactory()->createModel('Article', 'Administrator');`

### Expected result

I get model object

### Actual result

```
[TypeError]                                                                                                          
  Joomla\CMS\Workflow\Workflow::__construct(): Argument #2 ($app) must be of type ?Joomla\CMS\Application\CMSApplication, Joomla\CMS\Application\ConsoleApplication given, called in ....../libraries/src/MVC/Model/WorkflowBehaviorTrait.php on line 90        
```

### System information (as much as possible)

* Joomla! 5.2.0
* PHP 8.3

### Additional comments

Problem is in `\Joomla\CMS\Workflow\Workflow::__construct`. Method is:
`public function __construct(string $extension, ?CMSApplication $app = null, ?DatabaseDriver $db = null)`
should be
`public function __construct(string $extension, ?CMSApplicationInterface $app = null, ?DatabaseDriver $db = null)`
because \Joomla\CMS\Application\CliApplication implements CMSApplicationInterface, not extends CMSApplication.

**Comment by alikon** [comment]
thanks for reporting follow #40653
