### ISSUE TITLE
Admin menu Articles List does not work (anymore)

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#44394]
### Steps to reproduce the problem
Create 
- an Admin Menu, 
- an Admin Menu module,
- an Admin Menu Item, type List All Articles, and set the filter to a content category (e.g. Blog from the example data) 
### Expected result
- Clicking on the MenuItem in the administrator filters the posts of the category 'Blog'
### Actual result
- The system shows all posts, the filter does not work.
### System information (as far as possible)
- j5.2.0
- php 8.3

**Comment by brianteeman** [comment]
Confirmed 

This seems to be a duplicate report of #44305

**Comment by alikon** [comment]
duplicate
