### ISSUE TITLE
[5.2] Js error with custom admin menu item for components

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#44408]
### Steps to reproduce the issue
Create an admin menu module
Create a link of type Components Menu Container

### Bug 1
Click on any of the show/expand links (see screenshot)
![Image](https://github.com/user-attachments/assets/63786a9b-e40b-4f03-9fa8-53f68cf9703a)

### Bug 2
Click on any of the show/hide buttons (see screenshot
![Image](https://github.com/user-attachments/assets/1088140f-214e-41c6-a6b8-0504eb4264d2)

### Expected result
Links work

### Bug 1
```
Uncaught TypeError: Cannot read properties of null (reading 'innerHTML')
    at treeselectmenu.min.js?7a21e4:4:66
```
### Bug 2
```
admin-item-edit_container.min.js?47c6ca:4 Uncaught TypeError: s(...).map is not a function
    at HTMLInputElement.h (admin-item-edit_container.min.js?47c6ca:4:332)

```

**Comment by C-Lodder** [comment]
Bug 2 code fix:
> getTreeElements(root).forEach((element) => toggleState(element, selfChecked));

Still looking into Bug 1
