### ISSUE TITLE
Plugin vote on article did not save new vote

### ISSUE THREAD

**Issue by Microstudioweb** [joomla/joomla-cms#44415]
### Steps to reproduce the issue
1 - enable plugin content vote
2 - enable global configuration --> article --> show vote
3 - create an article in a category (this article must not have a direct menu voice)

### Expected result
when open the article see rating stars and you can vote it.

after you vote you see a message and ratingValueand, ratingCount will be update.

### Actual result
you did not see the rating stars and vote submit button.

### System information (as much as possible)
Joomla 5.1
Joomla 5.2

default template

### Additional comments
if you force the view of rating stars and try to vote
anyone any messages appear and ratingValueand, ratingCount remain the same.

**Comment by brianteeman** [comment]
Cannot confirm

https://github.com/user-attachments/assets/9f347644-13d2-42c7-b2ee-fcdf62efb688

**Comment by Quy** [comment]
Closing as non-reproducible. Please ask help in Joomla Forum. https://forum.joomla.org/
