### ISSUE TITLE
Create thumbnails fails - "FileSystem - Local" plugin - Image library

### ISSUE THREAD

**Issue by MacJoom** [joomla/joomla-cms#44417]
### Steps to reproduce the issue

Enable the thumbnail generation in the "FileSystem - Local" plugin for the images folder (default)

### Expected result

When going to media in the images folder, the media is displayed with thumbnails (from /media/cache/com_media/thumbs/images)

### Actual result

No files, Error message:imagecolorsforindex(): Argument #2 ($color) is out of range

### System information (as much as possible)

Joomla 5.2.0
PHP 8.2

### Additional comments

A PR from me is on the way.

**Comment by brianteeman** [comment]
it is to do with the transparency in the image

**Comment by MacJoom** [comment]
yes partly - i did the thumbnail generation for a few thousand files but it the error was only with this one...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44417">issues.joomla.org/tracker/joomla-cms/44417</a>.</sub>

**Comment by alikon** [comment]
closed as we have a pr #44418
