### ISSUE TITLE
Admin Article Search Box - helper text is off-screen

### ISSUE THREAD

**Issue by QuotesUK** [joomla/joomla-cms#44427]
### Steps to reproduce the issue
Go to Administrator > Articles
Hover Pointer over the Search Box

### Expected result
To be able to read the helper text

### Actual result
Helper text is partially visible
![Image](https://github.com/user-attachments/assets/2b44edb0-5c30-4ea5-9935-1e9c79c32535)

### System information (as much as possible)
Present in Joomla 5.2.0 and 5.2.1

### Additional comments
Perhaps adjust width or switch to displaying below

**Comment by fgsw** [comment]
@QuotesUK This is reported at #44086, please close your double report.

**Comment by Quy** [comment]
Please test PR #44433.
