### ISSUE TITLE
[5.2] reCAPTCHA Invisble plugin STILL fails execution after Joomla! Core update 5.2.1

### ISSUE THREAD

**Issue by maggus** [joomla/joomla-cms#44431]
The [original issue](https://github.com/joomla/joomla-cms/issues/44294) hasn't been fixed with Joomla! 5.2.1.

Joomla! 5.2.1 **AGAIN** delivers CSS and JS files for `plg_captcha_recaptcha_invisible` which breaks the plugin functionality.

Why do you still overwrite the asset files?

**Comment by Fedik** [comment]
Sorry for that. 
[The fix](https://github.com/joomla/joomla-cms/pull/44306) was not merged in to 5.2.1.
It is excpect to be in 5.2.2, if we get more testers there.
