### ISSUE TITLE
CoreButtonsTrait back() generates wrong button text

### ISSUE THREAD

**Issue by MaxxDau** [joomla/joomla-cms#44432]
### Steps to reproduce the issue
`$toolbar = Toolbar::getInstance();
 $toolbar->back('foobar');`

### Expected result
`<a href="javascript:history.back();">foobar</a>`

### Actual result
`<a href="javascript:history.back();">back</a>
`

### System information (as much as possible)
5.2.0

### Additional comments
https://github.com/joomla/joomla-cms/blob/30a64b3fcc07fa643184ee48137e92f239868582/libraries/src/Toolbar/CoreButtonsTrait.php#L155
Current:
```
public function back(string $text = 'JTOOLBAR_BACK'): LinkButton
    {
        return $this->link('back', $text)
            ->url('javascript:history.back();');
    }
```
Solution:
```
public function back(string $text = 'JTOOLBAR_BACK'): LinkButton
    {
        return $this->link($text, 'javascript:history.back();');
    }
```

**Comment by chmst** [comment]
@Steinweber as you know the solution, would you like to make a PR?

**Comment by Quy** [comment]
PR #44509
