### ISSUE TITLE
Standard batch mechanism is missing for tags

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#44442]
### Is your function request related to a problem? Please describe it.
Posts, menu items, categories can be structured by batch: several items, a, b, c... can be conveniently subordinated to another item, d. The ability to organise tags hierarchically is fine, but as a real joomla component, the tag component should also offer the same batch functions as the content or menu component.

### Describe the solution you want
Tags can be structured hierarchically via batch

**Comment by fgsw** [comment]
Filter by ```is:pr is:open batch tag```give:
5.3: #41927 
6.0: #40613
