### ISSUE TITLE
[5.2.1] Wrong sized Cancel Button in Cassiopeias add verification code frontend page

### ISSUE THREAD

**Issue by some1new** [joomla/joomla-cms#44472]
### Steps to reproduce the issue

Set template  to Cassiopeia, go to frontend, enter as registered.
Enter your Profil, enter edit profil and scroll down to add verification Code button, press.
At the bottom of this page you see that "Cancel" is only defined as a href, not as button, so wrong CSS is trigged and that for the cancel button is wrong sized.

### Expected result

Cancel Button should look like at page "Edit Profil"

### Actual result

Wrong sized cancel button on adding verification code page.

### System information (as much as possible)

J 5.2.1 under php 8.2

### Additional comments

![Image](https://github.com/user-attachments/assets/06332813-a304-4a3b-ab04-3b432ec85251)
![Image](https://github.com/user-attachments/assets/057e107f-a262-4d22-bd7a-bd105b333024)

**Comment by fgsw** [comment]
Issue confirmed:

![Image](https://github.com/user-attachments/assets/be9e083a-454f-4a09-a414-c227796bfe51)
