### ISSUE TITLE
reCAPTCHA plugin no longer available in Joomla 5

### ISSUE THREAD

**Issue by teivanov** [joomla/joomla-cms#44481]
### Problem identified
reCAPTCHA plugin was removed from Joomla 5

### Proposed solution
Include reCAPTCHA plugin in Joomla 5

### Open questions
Hello,

Could you please provide feedback on the reasons for removing the built-in reCAPTCHA plugin from Joomla 5? I've read some discussions on that topic, but I'm unable to find any justification on that decision. I know there are some third-party captcha plugins, but I believe the majority of the Joomla community would prefer to rely on a built-in plugin that offers better maintenance, support and security rather than using third-party plugins. 

Any information on that topic would be much appreciated. Thanks.

**Comment by bembelimen** [comment]
If you're interested in maintaining a reCAPTCHA joomla-extension repository feel free to create such a version and contact the [Maintainer Team](https://volunteers.joomla.org/teams/cms-maintenance-team).

**Comment by teivanov** [comment]
reCAPTCHA was an important feature and the decision to remove it brings a lot of confusion and questions from the Joomla community. The fact that there's no clear justification on it doesn't help either. So the goal of this issue is to get a visibility on the reasoning for removing reCAPTCHA.

**Comment by brianteeman** [comment]
The justification was that the version of recaptcha that was shipped was very outdated and not gdpr compatible AND that there were many captcha solutions freely available on the extension directory

**Comment by Fedik** [comment]
reCaptcha 2 and "reCaptcha invisible" no longer provide sufficient protection against spam https://github.com/joomla/joomla-cms/issues/43721.
reCaptcha 3 is better, but you have to look for existing solutions or you can follow @bembelimen comment.

Joomla does not rely on 3d services anymore (kind of), and do not provide plugin for it in core.
