### ISSUE TITLE
sample data Error on update to 5.2.2. rc1

### ISSUE THREAD

**Issue by Stevec4** [joomla/joomla-cms#44503]
### Steps to reproduce the issue
Manually updated with the upgrade zip file from ver 5.2.1

### Expected result

No errors

### Actual result
Error occurred with the following message
Joomla\Filesystem\Folder::files: Path is not a folder. Path: [ROOT]/images/sampledata

### System information (as much as possible)
PHP 8.2
Joomla 5.2.1 to 5.22
no sample data is installed

**Comment by brianteeman** [comment]
Fixed with https://github.com/joomla/joomla-cms/pull/44483
