### ISSUE TITLE
[5.3] com_content: Sequence of Read More and Article Info

### ISSUE THREAD

**Issue by dautrich** [joomla/joomla-cms#44508]
### Is your feature request related to a problem? Please describe.

![Image](https://github.com/user-attachments/assets/e389959c-5a64-4425-8e2a-307b0879a8f4)

If an article with a Read More button is displayed in the category blog and the article is configured to display the article info below the article, the sequence, in which the parts of the article are displayed, is like this:

1. Intro text
2. Article Info
3. Read More button

![Image](https://github.com/user-attachments/assets/e19dc291-f9f0-4874-8b43-3091c26ee2d9)

IMHO, this sequence isn't really logical. To me, the Read More button belongs to the article itself, while the article info is something, which I would put into the footer of a document I prepare for print.

### Describe the solution you'd like

The user should be able to display the Read More button above the article info:
![Image](https://github.com/user-attachments/assets/4e7a6857-0fdd-4b5e-9141-2e6f370ba492)

To maintain backward compatibility, there should be an additional configuration option for the sequence of article info and Read More button. That configuration option should only be selectable, when the article info is displayed below the article.

### Additional context

Applies to all Joomla version from 3.x to 5.x, but should only be implemented from 5.3.

**Comment by brianteeman** [comment]
this sort of think is best in a template override. Its literally just moving a couple of lines

**Comment by dautrich** [comment]
I've learned that "We have always done it like this!" is not a valid management argument. 

I understand that this can be achieved by a very simple override. But the implementation of an additional configuration option in Joomla core shouldn't be an extremely heavy task as well.

**Comment by brianteeman** [comment]
The more options you add the more complex the software. 

This is exactly what the template override feature is for.

**Comment by dautrich** [comment]
I agree with you on KISS. And yes, the more options we have, the more complex our software will become.

On the other hand, I'm convinced that this little feature:

- will be used by many users (not only me),
- will be easily implemented and will not complicate com_content too much.

**Comment by laoneo** [comment]
Pretty sure you can even change the ordering with CSS grid and no override.

**Comment by chmst** [comment]
Thank you for your feature request. The manitainer team has decided that in this case no new parameter is added to the core. A template override is simple.
