### ISSUE TITLE
Remove tags from multiple articles using the batch function

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#44526]
### Does your feature request relate to a problem?
The batch function allows me to add tags to posts as I wish. It would be nice if you could also do the opposite: delete tags from specific posts.

### Describe the desired solution
Extend the existing 'move' and 'copy' options to include the 'remove' option

**Comment by fgsw** [comment]
@hytsch do you mean #40613?

**Comment by brianteeman** [comment]
Duplicate report (again!!!) please close

**Comment by chmst** [comment]
@hytsch your request will be available in J6.0
