### ISSUE TITLE
Additional columns in the article list

### ISSUE THREAD

**Issue by hytsch** [joomla/joomla-cms#44529]
### Is your feature request related to a problem? Please describe.
The creation date is not always the most important date when working with articles. Often the publication date or the editing date of an article would be much more important. A column with these values ​​is missing in the admin.

### Describe the solution you'd like
Additional columns or ability to display additional columns.

### Additional context
With the new function to show/hide columns, the 'space requirement' argument should be superfluous.

**Comment by fgsw** [comment]
@hytsch do you mean this:

![Image](https://github.com/user-attachments/assets/c03578db-52a6-4902-9cbb-55ddcf09b1e0)

**Comment by hytsch** [comment]
exactly, but as a column in which the values ​​are displayed.

**Comment by fgsw** [comment]
please try:

![Image](https://github.com/user-attachments/assets/bd97c5ee-7761-47c4-9091-27c3ba052ed9)

**Comment by brianteeman** [comment]
Please close - the functionality already exists

**Comment by hytsch** [comment]
thanks, @fgsw !
