### ISSUE TITLE
Creating prepared statements using a bound variable multiple times throws exception

### ISSUE THREAD

**Issue by mariograf** [joomla/joomla-cms#44531]
### Steps to reproduce the issue
Create a simple prepared statement with a parameter, which is used more than once, and bind it to a variable. The following code example doesn't make sense but shows the problem:

```
$db = \Joomla\CMS\Factory::getContainer()->get('DatabaseDriver');
$someValue = 2;
$query = $db->getQuery(true)
    ->select('*')
    ->from('#__action_logs')
    ->where('id < :someValue AND user_id < :someValue ;')
    ->bind(':someValue', $someValue);
$db->setQuery($query);
$db->execute();
```

### Expected result
All occurences of the parameter (:someValue) should be replaced and the query should be executed successfully.

### Actual result
Exception: The number of variables must match the number of parameters in the prepared statement

### System information (as much as possible)
Joomla 4.4.9

### Additional comments
The error occurs using Joomla 4.4.9 but seems to be fixed in Joomla 5.2.1. Of course, there is an easy workaround (using different placeholders) but it took me a while to understand the problem (my original Sql statement was more complicated), so I think its worth to fix it to save others from having the same problem.

**Comment by Quy** [comment]
It's possible to use one variable for all bind values and ParameterTypes. 
See example in manual: https://manual.joomla.org/docs/general-concepts/database/select-data/

```
$query = $this->db->getQuery(true)
	->select($this->db->quoteName(array('id', 'password')))
	->from($this->db->quoteName('#__users'))
	->where($this->db->quoteName('username') . ' = :username')
	->where($this->db->quoteName('password') . ' = :password')
	->bind([':username', ':password'], $credentials['username']);
```

**Comment by mariograf** [comment]
@Quy Thank you for the quick response! Yes, I read the docs and saw this, but did not find any hint mentioning, that a parameter is not allowed to be used more than once. Even weirder that there is a different behaviour in different versions of joomla (4.4.9 / 5.2.1) without any documentation.

**Comment by fgsw** [comment]
@mariograf Can you update the docs?

**Comment by mariograf** [comment]
@fgsw Sorry for the late reply. I'm actually not sure what the desired behaviour of this feature is. In addition I tried the example Quy provided but also got an error message (although it was a different one). So maybe there is something wrong with my setup. I'm not a Php developer and don't want to spread missinformation.
