### ISSUE TITLE
I can't update to Joomla 5.2.2

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#44533]
### Steps to reproduce the issue
1. Check for Updates
2. Currently no update available.

### Expected result
Joomla 5.2.2

### Actual result
![Image](https://github.com/user-attachments/assets/48b8fe4f-e43e-454f-aaf7-1f9405882114)

### System information (as much as possible)
Joomla 5.2.1

### Additional comments
Have you paused updating to 5.2.2 or am I the only one who has this error and can't update to 5.2.2?

**Comment by bembelimen** [comment]
The update server has some issue, we're working on it to get it fixed.

**Comment by bembelimen** [comment]
Should be fixed now.
