### ISSUE TITLE
Weblinks (com_weblinks) custom fields missing from front end edit

### ISSUE THREAD

**Issue by pnkr** [joomla/joomla-cms#44536]
### Steps to reproduce the issue
Create some custom fields for weblinks.
Create a menu in frontend (Submit a Web Link)

### Expected result
When I click the Submit a Web Link, there should be the tab of the custom field that I added and have set to edit (both frontend and backend).

### Actual result
There is only the main block of fields to be filled

### System information (as much as possible)
Joomla 5.2.1
PHP 8.2

**Comment by brianteeman** [comment]
Weblinks is no longer a core part of Joomla. Please post this at the dedicated weblinks repository https://github.com/joomla-extensions/weblinks

Can be closed.
