### ISSUE TITLE
Easier way to show the custom fields in the view

### ISSUE THREAD

**Issue by pnkr** [joomla/joomla-cms#44537]
### Steps to reproduce the issue
I create the custom fields list that I want (Text, subforms, sql etc).

### Expected result
There should be a premade function that I can give the custom field name and id and appear in that place.

### Actual result
Trying to show the custom field in my custom view in the place that I want is very time consuming.
I must add declaration in the form I must loop all fields search and find what i want. And this has to be done in a lot of places for each view.

**Comment by brianteeman** [comment]
It already exists in the field options

![Image](https://github.com/user-attachments/assets/730c07ef-b55b-4e2b-aa52-b1697472e67e)

**Comment by pnkr** [comment]
that option is to show it to the view. I want for the add new weblink where I am an admin and i add a new weblink from the frontend to be able to fill it
