### ISSUE TITLE
[5.3] Joomla CCK: multicategories for articles

### ISSUE THREAD

**Issue by 4digitalworld** [joomla/joomla-cms#44541]
### Is your feature request related to a problem? Please describe.
It's 2024 and @Joomla has been around for almost 20 years, but still doesn't have a multi-category feature for articles.

All current options can't solve the problem of how to add display of `one article` in **different categories**, and this is the main part of any CCK, because on the Joomla ideas portal the CCK feature [was](https://web.archive.org/web/20160531064701/http://ideas.joomla.org/forums/84261-joomla-idea-pool) the most popular.

![Image](https://github.com/user-attachments/assets/dc14d29f-4184-4103-8d04-6a10f37d1e3c)

This feature has been requested many times already: https://github.com/joomla/joomla-cms/issues/9838 https://github.com/joomla/joomla-cms/issues/16553 https://github.com/joomla/joomla-cms/issues/23126 https://github.com/joomla/joomla-cms/issues/25619 https://github.com/joomla/joomla-cms/pull/24454

### Describe the solution you'd like
I suggest adding an option `additional categories` for `articles`.
Each article has **one main category**, based on which the canonical URL is created and also each article can have additional categories in which this article will also be displayed.

There should be an option to create the main SEF URL for the article: 

1. use the URL of the main category 
2. use the URL of the main and each additional category (adding a `rel=canonical` tag for the URL of the main category).

### Additional context
**Here's what was done for Joomla CCK:**
* [x] Infinite nesting of categories
* [x] Multilingual associations
* [x] Fields and field groups
* [x] Tags
* [x] Microdata
* [x] Workflow
* [ ] Custom shortcodes [#44506](https://github.com/joomla/joomla-cms/issues/44506)
* [ ] Multicategories

We are almost at the finish line for `CCK` to be completely ready.

Joomla is a CMS, which implies creating **large websites** with tens of thousands of articles and hundreds of categories, if you use CMS to create a website with 10-15 pages, you can use regular `HTML`+`CSS`.

I have been using Joomla since 2008 from version `1.0` and then I migrated to version `1.5`, `2.5`, `3.4` - `3.9`, `4.0` and now I use `5.2` and `multicategories` are still **a very necessary feature**. 

I have a very negative experience using 3rd-party extensions, because one day many 3rd-party extensions that I used stopped updating and I had to look for an alternative every time. 

I have very little trust in 3rd-party solutions when it comes to **creating articles**. 
I would trust 3rd-party developers with components such as forums, galleries, online stores, sliders and everything like that, but not creating articles.

**Comment by fgsw** [comment]
Discussion: "Simple Joomla CCK", Dec 21, 2022, #39461

**Comment by brianteeman** [comment]
Please close this here and continue in the existing discussion

**Comment by Hackwar** [comment]
And it is still an existing discussion about this feature. You are very welcome to discuss in that discussion how to achieve this, but we are not going to keep several duplicate reports open. Therefore I'm closing this one.

**Comment by brianteeman** [comment]
Doesnt make it the wrong place. Opening lots of issues for the same thing will not make it happen any quicker. At the end of the day any code needs someone to create it.

**Comment by peteruoi** [comment]
Without commenting on the topic itself, creating a new issue as feature request after some years from the previous one under a new era or new technological conditions or a different perspective or proposal may be legit. Of course keeping the older ids for reference it could be better closing the old one and keeping open the new one
