### ISSUE TITLE
[5.2] Smart Search / Finder - How to exclude searching for articles CREATED BY author in smart search?

### ISSUE THREAD

**Issue by pixelhexe** [joomla/joomla-cms#44549]
### Is your feature request related to a problem? Please describe.

It's an old problem with smart search and finder content plugin: users searching for a string will see all articles that an author **has created** (if the search string is an author's name), no matter whether his name is found elsewhere in the article or not.

As described already [in 2015](https://github.com/joomla/joomla-cms/issues/7976):
I would like to have the search to exclude the author from the index, so that search results returned only show articles in which the author is mentioned in content but not articles created by author.

The only possibility I found is a core hack in 
[\plugins\finder\content\src\Extension\Content.php ](https://github.com/joomla/joomla-cms/blob/5.2-dev/plugins/finder/content/src/Extension/Content.php#L324)

1. comment the following lines:
// $item->addInstruction(FinderIndexer::META_CONTEXT, 'metaauthor');
// $item->addInstruction(FinderIndexer::META_CONTEXT, 'author');
// $item->addInstruction(FinderIndexer::META_CONTEXT, 'created_by_alias');  

2. empty the search index
3. reindex

### Describe the solution you'd like

Add an option in the finder content plugin **to limit search results only to article content** and exclude search by author who has created an article. 

Please note that the option of "Taxonomies to index" -> "Author" is not the same! I don't want to generally exclude artices from an author. I just do not want to find these articles in my search results on searching by author's names. 

It's a little difficult to explain. In other words: for example if an author's name is mentioned in an item as in an imprint page, this article of course should be found in my search results. But not all articles which are written by this author.

**Comment by Hackwar** [comment]
I've marked this as bug, since it can be argued that with the switches in the finder plugins this should also control indexing the value for search as well, so we could fix this in 5.2. If it is decided to do this in 5.3, we should also add tags and some other data in there, too.

**Comment by pixelhexe** [comment]
Thank you @Hackwar! I just tried my first PR - this would be a quite simple bugfix. 

As far as I have tested, the author data is automatically indexes - independantly of the taxonomy option "Author" in the smart search plugin. Probably this taxonomy makes only sense with search filters or advanced searching. 

My PR is just a proposal and surely needs more testing or other suggestions...

**Comment by richard67** [comment]
Closing as having a pull resuest. See #44554 .
