### ISSUE TITLE
Ability to create pretty URLs without the need to add an article to the menu

### ISSUE THREAD

**Issue by orschiro** [joomla/joomla-cms#44548]
Hi team, 

We have many websites that have very user-unfriendly URLs such as [1] because the corresponding article is not added to a menu.

I would like to ask if it's possible to add a feature that provides readable URLs without the need to add an article to a menu and subsequently set its menu status to hidden?

Thank you!

[1] https://www.ztm.de/buddy/?view=article&id=902&catid=2

**Comment by Hackwar** [comment]
Please make sure that you are using Joomla 5.2, since we did several changes there. The next fix is coming with #43992.

**Comment by orschiro** [comment]
This is great, thank you, Hannes!

Looking forward to 5.3 and going to ensure we are updating to 5.2. :)

**Comment by Hackwar** [comment]
Since this has been (partially) fixed in 5.2 and another fix has been added in 5.3, I'm closing this one.
