### ISSUE TITLE
[5.2.2] Password view functionality doesn't work

### ISSUE THREAD

**Issue by pioada** [joomla/joomla-cms#44557]
### Steps to reproduce the issue
Go to Global configuration > server tab > Mail section
Choose Mailer: SMTP, SMTP Authentication: Yes. Modify password button doesn't work.
Password field is still disabled. It is not possible to add / modify password.
Dev console show error:
Uncaught TypeError: s is null in media/system/js/fields/passwordview.min.js?a335da:4 (passwordview.min.js:4:157)

### Expected result
Possible to add / modify password

### Actual result
Password field is still disabled. It is not possible to add / modify password.

### System information (as much as possible)
Joomla 5.2.2

**Comment by brianteeman** [comment]
Please test https://github.com/joomla/joomla-cms/pull/44555
