### ISSUE TITLE
Cannot change password for SMTP account.

### ISSUE THREAD

**Issue by superknutsel** [joomla/joomla-cms#44553]
### Steps to reproduce the issue
In the Global configuration go to the Server tab and check the console messages. 

### Expected result
No errors in the console and being able to change the password for the authentication of the SMTP account.

### Actual result
There is an error in the console like this:

Uncaught TypeError: can't access property "getAttribute", toggleButton is null
    togglePassword https://domain.com/media/system/js/fields/passwordview.js?a335da:10
    togglePassword https://domain.com/media/system/js/fields/passwordview.js?a335da:8
    EventListener.handleEvent* https://domain.com/media/system/js/fields/passwordview.js?a335da:79
    <anonymous> https://domain.com/media/system/js/fields/passwordview.js?a335da:80
passwordview.js:10:32
    togglePassword https://domain.com/media/system/js/fields/passwordview.js?a335da:10
    forEach self-hosted:157
    togglePassword https://domain.com/media/system/js/fields/passwordview.js?a335da:8
    (Async: EventListener.handleEvent)
    <anoniem> https://domain.com/media/system/js/fields/passwordview.js?a335da:79
    <anoniem> https://domain.com/media/system/js/fields/passwordview.js?a335da:80

And I cannot change the password.

### System information (as much as possible)
Joomla 5.2.2, PHP 8.2.5

### Additional comments
See this issue : [https://github.com/joomla/joomla-cms/pull/44362](https://github.com/joomla/joomla-cms/pull/44362)

**Comment by brianteeman** [comment]
different error same page if you are not using smtp prevents you changing the database 

![Image](https://github.com/user-attachments/assets/6379dc45-c51b-4a83-8d12-7bd282650c94)

```
Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at passwordview.min.js?a335da:4:159
    at Array.forEach (<anonymous>)
    at HTMLDocument.c (passwordview.min.js?a335da:4:82)
```

**Comment by rdeutz** [comment]
Please check https://github.com/joomla/joomla-cms/pull/44555, closing here.
