### ISSUE TITLE
Joomla 5.2.2 - Deprecation error message HTMLHelper.php class

### ISSUE THREAD

**Issue by aberenguer78** [joomla/joomla-cms#44573]
### Steps to reproduce the issue

When opening my custom module appears this deprecation error:
Deprecated: Automatic conversion of false to array is deprecated in C:\xamppPHP8.2\htdocs\joomla5\libraries\src\HTML\HTMLHelper.php on line 810

The error message is in joomla root\libraries\src\HTMLHelper.php line 810

### Expected result

No deprecation message is shown

### Actual result
The deprecation message is shown

### System information (as much as possible)
Joomla 5.2.2
PHP 8.3.13

### Additional comments
Solution provided by chat gpt:

Solution add this line in 810: (Solution provided by chat gpt - deprecation happens in php 8.2)
$options = is_array($options) ? $options : [];
$options['relative'] = $options['relative'] ?? false;

**Comment by chmst** [comment]
Please don't try that again. https://github.com/joomla/joomla-cms/issues/44568#issuecomment-2514606881
