### ISSUE TITLE
Smart search index showing PHP error instead of content map filter dropdown

### ISSUE THREAD

**Issue by emmettculley** [joomla/joomla-cms#44584]
### Steps to reproduce the issue
I am seeing the following error messages on the Smart Search: Indexed Content page when I click on the filter options button:

Warning: Undefined array key 7 in /bitnami/joomla/administrator/components/com_finder/src/Field/ContentmapField.php on line 109

Warning: foreach() argument must be of type array|object, null given in /bitnami/joomla/administrator/components/com_finder/src/Field/ContentmapField.php on line 1

Then repeats for keys 8, 4 and 2.

I altered the code in the ContentmapField.php file using:  

if (isset($parents[$parent]))

Doing that seemed to resolve the issue as the content map filter dropdown appeared when clicking on the filter options button and seemed to have the correct content.

I seems to me that this is a databasse issue, but I have no idea how or why.  Please see attached picture of a database query on the finder_taxonomy table.  It looks like there are extra rows, compared to another site where we haven't attempted to "fix" the search index.

### Expected result

To see content map filter dropdown instead of error messages.

### Actual result

Not able to select any content map filters

### System information (as much as possible)

Joomla: 5.2.2

Operating System: Fedora Linux 41
KDE Plasma Version: 6.2.4
KDE Frameworks Version: 6.8.0
Qt Version: 6.8.0
Kernel Version: 6.11.10-300.fc41.x86_64 (64-bit)
Graphics Platform: Wayland
Processors: 32 × AMD Ryzen 9 5950X 16-Core Processor
Memory: 125.7 GiB of RAM
Graphics Processor: AMD Radeon RX 550 / 550 Series

### Additional comments

I am just now learning about the ins and outs of smart search.  I suspect that my attempt to limit what is searched has somehow gone wrong.

**Comment by fgsw** [comment]
@emmettculley Can you look at #44184 if this is a duplicate report?

**Comment by emmettculley** [comment]
Yes, that seems to be the same issue.



Why am I not able to add a screenshot file?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44584">issues.joomla.org/tracker/joomla-cms/44584</a>.</sub>

**Comment by richard67** [comment]
Closing as duplicate report. See #44184 . Thanks for confirming.

@emmettculley For adding screenshots it's easier to do it on GitHub than in the issue tracker.
