### ISSUE TITLE
Action Logs for com_contact frontend actions are not recorded

### ISSUE THREAD

**Issue by AndySDH** [joomla/joomla-cms#44589]
### Steps to reproduce the issue

- Make sure the Contacts component is enabled in the User Action Logs global configuration
- Display a Contact via the frontend (eg. via menu item)
- Edit the contact and save

### Expected result

- An action for the contact being updated should be added to the Action Log

### Actual result

- No action is recorded.

(On the other hand the Action is recorded normally if the contact is edited through the backend)

### System information (as much as possible)

- Latest Joomla 5 version.

**Comment by fgsw** [comment]
Can't confirm; used default values.
####  Test System Information
PHP Built On 	Darwin Air.local 23.6.0 Darwin Kernel Version 23.6.0: Thu Sep 12 23:34:49 PDT 2024; root:xnu-10063.141.1.701.1~1/RELEASE_X86_64 x86_64
Database Type 	mysql
Database Version 	8.0.35
Database Collation 	utf8mb4_0900_ai_ci
Database Connection Collation 	utf8mb4_0900_ai_ci
Database Connection Encryption 	None
Database Server Supports Connection Encryption 	Yes
PHP Version 	8.3.9
Web Server 	Apache/2.4.58 (Unix) OpenSSL/1.1.1u mod_fastcgi/mod_fastcgi-SNAP-0910052141
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 5.3.0-alpha2-dev Development [ Timu ] 26-November-2024 17:01 GMT
Joomla Backward Compatibility Plugin 	Disabled
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:133.0) Gecko/20100101 Firefox/133.0

**Comment by AndySDH** [comment]
Follow the test instructions. It's impossible that you can't confirm.

**Comment by brianteeman** [comment]
I can confirm that when editing a contact in the front end it is not logged in the UAL as shown in the image below where I edited a contact in the admin then logged in to the front end and did the same

![Image](https://github.com/user-attachments/assets/fa862b8b-4e00-41c7-86c8-fd0bff834222)

**Comment by fgsw** [comment]
@brianteeman Thanks for the screenshot. Now i understand the issue and can confirm. 

Sorry for false alarm @AndySDH.

**Comment by alikon** [comment]
please test #44596
