### ISSUE TITLE
Installation stuck if a wrong password is inserted

### ISSUE THREAD

**Issue by PixedBo** [joomla/joomla-cms#44583]
### Steps to reproduce the issue

Install a joomla from scratch, use a password that does not meet the minimum requirements for password:

![Image](https://github.com/user-attachments/assets/900a7c1a-4701-47e5-ac47-c19ff63f0cd5)

### Expected result

Some kind of error that prevent me to clic the "go the next step" button

### Actual result

I can go on and configure the database, after that i receive a blocking message and can't return to previous steps

![Image](https://github.com/user-attachments/assets/f3870b9f-bc2d-4b4f-9819-0ff8b0417181)

The error says: "password is too short, Password must be at least 12 characters". And then I can't return to modify the passowrd or anywhere. It just stuck here. I have to reload the whole page and start from the beginning

### System information (as much as possible)

Database: 10.6.17-MariaDB-cll-lve-log
PHP: 8.2

**Comment by fgsw** [comment]
@PixedBo Please close the duplicate report of #42289.

**Comment by richard67** [comment]
Closing as duplicate report. See #42289 . Thanks for reporting.
