### ISSUE TITLE
Joomla fr-FR, "date of birth" translation mislead users

### ISSUE THREAD

**Issue by vcmb-cyclo** [joomla/joomla-cms#44595]
### Steps to reproduce the issue
ADMIN - USER - Profile - Date of Birth
LANGAGE = FRENCH (User and Admin)

### Expected result
Help message mislead User as they ask to enter date in the US way YYYY-MM-DD
But if Langage(date) is set to FR : date must be enter in DD-MM-YYYY 
Translation help (translation) tell user to enter WRONG format which cause Users to fail to enter their date of Birth...

### Solution - FIX - Workaround
Modify translation file : administrator\language\fr-FR\plg_user_profile.ini

Change lines 15-16-17 to reflect correct French langage:

PLG_USER_PROFILE_FIELD_DOB_DESCRIPTION="Jour-Mois-Année, par exemple 27-01-2019." ; Adapt to the format you entered in the 'DATE_FORMAT_CALENDAR_DATE'
PLG_USER_PROFILE_FIELD_DOB_HINT="JJ-MM-AAAA" ; Adapt to the format you entered in the 'DATE_FORMAT_CALENDAR_DATE'
PLG_USER_PROFILE_FIELD_DOB_LABEL="Date de naissance"

### System information (as much as possible)
Tested under Joomla 5.22

### Additional comments
Update to pass to Translation fr-FR Team (Mihaly)

BR, Gilles

**Comment by fgsw** [comment]
@vcmb-cyclo Please report at https://github.com/joomla/core-translations

**Comment by brianteeman** [comment]
This should be closed and handled with the translation team directly
