### ISSUE TITLE
Add plugin event to com_users ResetModel::processResetConfirm

### ISSUE THREAD

**Issue by peter1szalatnay** [joomla/joomla-cms#44598]
### Is your feature request related to a problem? Please describe.

Joomla has events for all steps in a password reset chain except for the confirmation step.

Our site are using both email address and username for logons. But the username is hidden everywhere on the site. 

When I use wants to reset their password they don't know what the randomly generated username is for the confirmation step.

### Describe the solution you'd like

A before plugin event before the username checkup would help us with checking up the username from the email address and change the form data.

**Comment by Fedik** [comment]
> ... the randomly generated username is for the confirmation step.

This is issue with implementation on your side.
Usualy when I use email instead of username for User managment, I just copy the email to username field, then all works smoothly.

**Comment by alikon** [comment]
close as we have a pr #44599
