### ISSUE TITLE
Modify password button not working in Global Configuration

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#44606]
### Steps to reproduce the issue

Go to the Global Configuration and click on the 'Modify' button next to either the database password or the SMTP password.

### Expected result
Make the passworld field editable so a new password can be filled in.

### Actual result
Nothing happens.

### System information (as much as possible)
Joomla 5.2.2
PHP 8.3.13
Chrome 131.0.6778.139 

### Additional comments

In the console I see this error:

passwordview.min.js?ae41a603ad7720bdbe5536dce07ff1d5:4 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at passwordview.min.js?ae41a603ad7720bdbe5536dce07ff1d5:4:159
    at Array.forEach (<anonymous>)
    at HTMLDocument.c (passwordview.min.js?ae41a603ad7720bdbe5536dce07ff1d5:4:82)

**Comment by fgsw** [comment]
@jjnxpct Please close double report of https://github.com/joomla/joomla-cms/issues/44553. Related, merged Pull Request: https://github.com/joomla/joomla-cms/pull/44555.
