### ISSUE TITLE
[5.2.2] Unable to Change SMTP Email Password in Global Configuration

### ISSUE THREAD

**Issue by sdwjoomla** [joomla/joomla-cms#44610]
### Steps to reproduce the issue
New Joomla Install of 5.2.2
Check configuration.php is writable, if not update permissions
Edit Global Configuration
Mailer set to SMTP
SMTP Authentication set to Yes
Enter username and tap Modify to update password 

### Expected result
Password field to become writable to update password

### Actual result
Nothing happens
Console lists 
passwordview.min.js?a335da:4 Uncaught TypeError: Cannot read properties of null (reading 'getAttribute')
    at passwordview.min.js?a335da:4:159
    at Array.forEach (<anonymous>)
    at HTMLDocument.c (passwordview.min.js?a335da:4:82)

### System information (as much as possible)
Joomla 5.2.2
PHP 8.2.24

### Additional comments
configuration.php was not writable, manually updated permissions prior to attempting to change the SMTP email password

**Comment by fgsw** [comment]
@sdwjoomla Please close double report of https://github.com/joomla/joomla-cms/issues/44553. Related, merged Pull Request: https://github.com/joomla/joomla-cms/pull/44555.
