### ISSUE TITLE
Captcha label visible without captcha plugin actively

### ISSUE THREAD

**Issue by peterhulst** [joomla/joomla-cms#44614]
### Steps to reproduce the issue
1. Disable (all) captcha plugins.
2. Allow Captcha on Contact: None Selected.
3. Template: default Cassiopeia without overrides.
4. Go to user registration in frontend.
5. Look at the label Captcha*.
 
### Expected result
Label Captcha* is NOT visible with NO captcha plugin activated.

### Actual result
Label Captcha* is visible.

### System information (as much as possible)
- Joomla 5.2.2
- PHP 8.2.26 / 8.3.14

### Additional comments
See steps before

**Comment by brianteeman** [comment]
Is the component still set to use captcha

Is global confgiguration still set to use captccha

Are you using a template override

**Comment by peterhulst** [comment]
Allow Captcha on Contact: None Selected.

With standard Cassiopeia with NO template overrides it is still visible.

**Comment by brianteeman** [comment]
User registration not contact so you should be checking the user component and the global configuration

![Image](https://github.com/user-attachments/assets/5d9f4cc2-2648-413d-8d11-45cfd17d0f9a)


![Image](https://github.com/user-attachments/assets/ad223920-c51b-465a-b987-2790b7e005c6)

**Comment by peterhulst** [comment]
I have checked. **Both are None Selected.**

**Comment by chmst** [comment]
Cannot replicate. Do you have extension which inject this field?

**Comment by peterhulst** [comment]
> Cannot replicate. Do you have an extension which injects this field?

No I don't have

**Comment by brianteeman** [comment]
I cannot replicate this

**Comment by chmst** [comment]
@peterhulst please post a screenshot

**Comment by sandewt** [comment]
I can confirm this issue

**Comment by peterhulst** [comment]
@sandewt @brianteeman **I have good news**: 
- after switching to **- None Selected -** the Captcha* display disappeared. 
- _And to my surprise:_ switching back to: **Use Global ( - None Selected -)** it remains disappeared.

I have to mention that my website was updated from 4.4.9 --> 5.2.2, so may be that the behaviour of some stored (or not stored) parameter in 4.4.9 was changed in 5.2.2.

So I thing there was initially some undefined value stored.

Regards

**Comment by chmst** [comment]
Please test this PR https://github.com/joomla/joomla-cms/pull/44619.
I found this while investigating here.

**Comment by peterhulst** [comment]
@chmst With PR #44619 the option Use Global ( - None Selected -)  disappeared. 
I think that is okay, although I can not test it again, because the initial behaviour can not be initialised again after my previous report.

**Comment by fgsw** [comment]
@peterhulst Please close the issue as its solved.
