### ISSUE TITLE
User Registration Emails are not sent in J5.2.2 (in J4.4.9 & J3.10 it was working properly)

### ISSUE THREAD

**Issue by peterhulst** [joomla/joomla-cms#44620]
### Steps to reproduce the issue
- PHP Mail is used (in both J4.4.9 and J 5.2.2 and also J 3.10
- Send test mail works as expected in J4 and J5
- Create a new user
-  User Registration mails should be sent to confirm the emailadress
-  The new user is created in J4 and J5
-  The provider email settings are not changed from J3 to J5.

### Expected result
 The User Registration mails are sent in both J4 and J5 (and it worked too in J3)
A message that the mail is sent is displayed for the user.
The new user is created.

### Actual result
The User Registration mails are sent in  J3, J4 but **NOT sent in the updates J5**
Same as expected:
A message that the mail is sent is displayed to the user.
The new user is created.

### System information (as much as possible)
The J5.2.2 is an updated J4.4.9 version (coming from J3.10). In J3.10, J4.4.9 everything works as expected without modification on the provider site. Also J4.4.9 in a subdomain remains working as expected.
PHP 8.2.26 or 8.3.18 makes no difference.

### Additional comments
Switching to SMTP makes no difference (a bug in 5.2.2 makes it impossible to use it with an SMTP user with a password).

**Comment by fgsw** [comment]
> Switching to SMTP makes no difference (a bug in 5.2.2 makes it impossible to use it with an SMTP user with a password).

Reported: https://github.com/joomla/joomla-cms/issues/44553. Related, merged Pull Request: https://github.com/joomla/joomla-cms/pull/44555.

**Comment by peterhulst** [comment]
**GOOD NEWS:** 
Using PHP Mail, the problem could not be reproduced anymore (in PHP 8.2.26 and PHP 8.3.18)
**Everything works now as expected, without changing any settings.**

_The only explanation could be that at the website provider something was not working properly_

**Comment by Hackwar** [comment]
Since it isn't a Joomla bug, I'm closing this one.
