### ISSUE TITLE
Password fields are no longer clickable in Global Configuration

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#44676]
Joomla 5.2.2. I go to Global Configuration and configuring Mail fields > SMTP.
When I attempting to click on "Modify" password button,  nothing happens.
<img width="1359" alt="Image" src="https://github.com/user-attachments/assets/d414e0a5-6ea2-47a0-b987-8bddacaec518" />

I see this error in the console:
/media/system/js/fields/passwordview.min.js?a335da

<img width="567" alt="Image" src="https://github.com/user-attachments/assets/ea054e34-5a35-400b-80aa-5ddd1ad39c10" />

The same goes to Database Password.

**Comment by fgsw** [comment]
@Sulpher Please close double report of https://github.com/joomla/joomla-cms/issues/44553. Related, merged Pull Request: https://github.com/joomla/joomla-cms/pull/44555.
