### ISSUE TITLE
Cannot disable the Template Editor

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#4491]
From what I can tell If I want to give access to the Template manager then I have to give access to the template editor as well. While I might always want people to change a style I might not want them to be able to edit the files in the template

**Comment by zero-24** [comment]
Moving to `Confirmed` now we need to code and define which access we should use. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4491">issues.joomla.org/joomla-cms/4491</a>.</sub>
