### ISSUE TITLE
onUserLogout cannot be correctly aborted

### ISSUE THREAD

**Issue by heimburg** [joomla/joomla-cms#4497]
#### Steps to reproduce the issue

- create a user plugin with an onUserLogout() event
- return false from this plugin

#### Expected result

Expected behavior (based on orthogonality and code review) is if any plugin returns false, the logout process is aborted. In that case, onUserLogoutFailure event is triggered. If the logout is successful, onUserAfterLogout is triggered instead.

#### Actual result

If you return false, the appropriate events are triggered. However, the user is still "mostly" logged out anyway. This is because plugins/user/joomla/joomla.php does its logging-out code in onUserLogout, rather than in onUserAfterLogout.

As a result, it is not actually possible to abort the logout process. Either the return values should not be checked at all, or the stock plugins should use onUserAfterLogout instead. Or a new onUserBeforeLogout event added, I guess.

#### System information (as much as possible)

Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

#### Additional comments

Apologies if this is the wrong place for API issues.

**Comment by zero-24** [comment]
Closing as we have now a PR by @jackkum here: https://github.com/joomla/joomla-cms/pull/5603 Thanks :smile:
