### ISSUE TITLE
Template id is not present in setTemplate() 

### ISSUE THREAD

**Issue by lucianito20012000** [joomla/joomla-cms#4503]
I have an extension having this lines of code:

$app = JFactory::getApplication();
$template = $app->getTemplate(true); 
$style = $template->id; //I use the template id number in my extension 

I used Virtue Mart to reproduce the error. VM has an option to pick the template you want to use in the store. It ignores the default template you select in the "template manager" and reset the template by which you choose. Something like this:

$query = 'SELECT `template`,`params` FROM `‪#‎__template_styles‬` WHERE `id`="'.$template.'" ';
[etc, etc]...
$res = $db->loadAssoc();
$registry = new JRegistry;
$registry->loadString($res['params']);
$template = $res['template']; //the name of the template
....[etc,etc]..
$app->setTemplate($template,$registry); //setTemplate() accepts 2 arguments: template (string) and the template style parameters (mixed).

In this point the element "id" (that I use in my extension) is missed. 

#### Expected result

I propose to modify setTemplate() adding the id of the template as an argument.

 The questions are:

1) Is there any other way (unknown by VM -and by me- ) to re-set the template including the template id in the object?

2) should setTemplate() be changed like:

public function setTemplate($template, $styleParams=null, $id=null )
{
if (is_dir(JPATH_THEMES . '/' . $template)) {
$this->template = new stdClass();
$this->template->template = $template;
$this->template->id = $id;
if ($styleParams instanceof JRegistry) {
$this->template->params = $styleParams;
}
else {
$this->template->params = new JRegistry($styleParams);
}
}
}

**Comment by vdespa** [comment]
There has been little activity on this issue, so I am closing it for the moment. If anybody objects, it can be reopened anytime. Thanks @all!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4503">issues.joomla.org/joomla-cms/4503</a>.</sub>

**Comment by RaimisErvit** [comment]
Maybe on 3.7 work setTemplateStyle() or other sets where can set template ID ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4503">issues.joomla.org/tracker/joomla-cms/4503</a>.</sub>
