### ISSUE TITLE
Weblink Module not appearing in front-end; Weblink menu item shows as "unpublished"

### ISSUE THREAD

**Issue by adrianfso** [joomla/joomla-cms#4657]
#### Steps to reproduce the issue
Create Weblink items in the backend, ensuring they're set to published in any category. Create a new module of "Weblinks" type, ensuring the category and a valid position are selected.

In addition, create a new menu item of the "Weblinks" type (single category display).

#### Expected result
The module should appear on all pages in the selected position. 

In addition, the menu item created should also display the category of Weblinks as published.

#### Actual result
The position seems to be rendered, but the content is not. 

In addition, the menu item does display the Weblinks, but a tag called "unpublished" appears on the page. "Unpublished" appears whether or not the user is signed into the front-end.

#### System information (as much as possible)
MSSQL, IIS, J!3.3.6

#### Additional comments
There seems to be an issue with the "publish" calculations. Also, there aren't any files in the "components/weblinks/views/weblink/tmpl/" folder (other than index.html). Is that supposed to be empty?

**Comment by brianteeman** [comment]
Closing here as the PR was created against the weblinks repo - thanks https://github.com/joomla-extensions/weblinks/pull/16<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4657">issues.joomla.org/joomla-cms/4657</a>.</sub>
