### ISSUE TITLE
Move all Platform @since version numbers into Joomla version numbers

### ISSUE THREAD

**Issue by javigomez** [joomla/joomla-cms#4704]
Please see all the details of this task at the Coding Standards repository: https://github.com/joomla/coding-standards/issues/85

**Comment by brianteeman** [comment]
Has this been done yet @javigomez

**Comment by brianteeman** [comment]
I am closing this as it is just a todo note and not a real issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4704">issues.joomla.org/joomla-cms/4704</a>.</sub>

**Comment by photodude** [comment]
Cross reference https://github.com/joomla/coding-standards/issues/85

@brianteeman how are "TODO" notes being tracked as tasks that could/should be addressed?
