### ISSUE TITLE
Alias field for "External URL" menu item type does not exist

### ISSUE THREAD

**Issue by titanomachy** [joomla/joomla-cms#4706]
## Steps
Responsive menu's compatible for touch devices need a top level menu item you can click or press on to enable sub-menu functionality You do not want a hover for small screen touch devices.  

To do this in Joomla with Bootstrap 3.3 I need:

1. a top level menu item.
2. the external URL feature 
2. a hash tag (#) as link value 
 
If I - instead - would use an (e.g.) individual article it does not work. Users on touch devices will be redirected to that article instead of seeing the sub-menu. 

## Issue
The issue with the aforementioned 'solution' is that the URL for a sub-menu item has a strange format. It has a date, and a time stamp in it. Like this: example.com/2014-10-16-00-38-41/article-name.

It does not use the category in the URL, and it does not use the name of the external link as a URL. Such an URL does not tell people where the article belongs to. 

An alias field, just like the other menu item types have, would solve this. Except it is not there for the "External URL" menu type.

## Solution
Instead of using the date time stamp in the URL, enable the alias field in the backend for creating the URL.

**Comment by diesl** [comment]
I came here while searching for solutions about the same issue (bootstrap mobile). Well, there is a workaround for the bootstrap problem. But the original problem when using "External URL" still exists:

> The issue with the aforementioned 'solution' is that the URL for a sub-menu item has a strange format. It has a date, and a time stamp in it. Like this: example.com/2014-10-16-00-38-41/article-name.

My suggestion is to unhide the alias field. Joomla tries to be smart here, but in the end, does and can not catch all possibilities. I have not found a good argument why it is hidden and can not be changed.

@titanomachy I would suggest to reopen this issue even if your personal problem can be solved with a workaround

**Comment by brianteeman** [comment]
Did you try Joomla 3.4 - as far as I can see you can create any alias you
want to with a menu item of type External URL

On 26 February 2015 at 00:18, diesl <notifications@github.com> wrote:

> I came here while searching for solutions about the same issue (bootstrap
> mobile). Well, there is a workaround for the bootstrap problem. But the
> original problem when using "External URL" still exists:
>
> The issue with the aforementioned 'solution' is that the URL for a
> sub-menu item has a strange format. It has a date, and a time stamp in it.
> Like this: example.com/2014-10-16-00-38-41/article-name.
>
> My suggestion is to unhide the alias field. Joomla tries to be smart here,
> but in the end, does and can not catch all possibilities. I have not found
> a good argument why it is hidden and can not be changed.
>
> @titanomachy <https://github.com/titanomachy> I would suggest to reopen
> this issue even if your personal problem can be solved with a workaround
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/4706#issuecomment-76093567>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
See https://github.com/joomla/joomla-cms/pull/4932 which was merged and is present in 3.4

**Comment by diesl** [comment]
Thanks for the information. Seems like a good timing that Joomla 3.4 has been released right now.
