### ISSUE TITLE
jQuery Tooltip script error TypeError: JQuery(...).tooltip is not a function

### ISSUE THREAD

**Issue by frogydiak** [joomla/joomla-cms#4719]
#### Steps to reproduce the issue
Installed Joomla v3.3.6 in localhost using XAMPP 1.8.2-5 and without any other component installed you can see an inline javascript file loaded in the head that is calling jQuery tooltip and popover. And that was causing the Error in Firebug Console.

I installed SmartSlider 2 component from http://www.nextendweb.com. I was wondering why their module disappears when I add a new module in any position. When I look at firebug console, I am getting "TypeError: JQuery(...).tooltip is not a function". That error stopped javascript to make nextendweb.com slider module to work.

#### Expected result
jQuery tooltip and popover shouldn't be loaded or called when there is no use for it. 

#### Actual result
![screen shot 2014-10-16 at 22 41 30](http://issues.joomla.org/uploads/1/97c3500f12b1d3558abae3ff7cae9b41.png)

#### Additional comments
Fix is from nextendweb.com support (Gabor Racz):

This error is probably coming from this file: libraries/cms/html/bootstrap.php

Look for this code, it's probably at line 481.:
$script[] = "\t jQuery('" . $selector . "').tooltip(" . $options . ");";

change it to this:
$script[] = "\t if ( jQuery.isFunction(jQuery.fn.tooltip) ) jQuery('" . $selector . "').tooltip(" . $options . ");";

After changing line 481, I then got an error on popover, then around line 380.:
jQuery('" . $selector . "').popover(" . $options . ");

Change like 380 to:
if ( jQuery.isFunction(jQuery.fn.popover) ) jQuery('" . $selector . "').popover(" . $options . ");

The hack nextendweb.com provided worked, their slider module worked fine and I'm not seeing the javascript error anymore.

**Comment by IberoMedia** [comment]
Still a problem with Joomla 3.4.0

After a clean install w/o sample data, console reports:

![hastooltip_undefined_function](https://cloud.githubusercontent.com/assets/1542188/6767273/9b15dca0-cfe4-11e4-838c-d17098095883.png)

![hastooltip_error](https://cloud.githubusercontent.com/assets/1542188/6767274/9f8e2d00-cfe4-11e4-9bb7-cc36e6be734d.png)

**Comment by flashfs** [comment]
I was having this same problem upgrading from 2.5.8 to 3.4.1. After some research, listed all my JavaScript libraries with Web Developer Firefox's extension, and found that I was loading another jQuery library from Hot Image Slider module that was in conflict with the one from Joomla.

**Comment by Fedik** [comment]
would be good to know on which page exactly it happens, at least ...

**Comment by shadow-kun** [comment]
Confirmed, previous fix still works... now to do that pull request.

**Comment by zero-24** [comment]
´Closing as we have a pull request by @shadow-kun  here: #7016 Thanks

**Comment by adamasantares** [comment]
It happend when you use Pagination class.
jimport('joomla.html.pagination');
