### ISSUE TITLE
If no records are present and click on delete track button then also confirmation pop up and message "0 records are deleted" is displayed.

### ISSUE THREAD

**Issue by amithadkar** [joomla/joomla-cms#4765]
#### Steps to reproduce the issue
1. Open Banner->Tracks.
2. Delete all records.
3. After deleting all records again click on "Delete Tracks" button.
4. Verify the result.

#### Expected result
If records are not present then pop up message and confirmation message should not be displayed.

#### Actual result
If records are not present then pop up message and confirmation message is displayed.

#### System information (as much as possible)
PHP Built On Windows NT 6.2 build 9200
Database Version 5.6.12-log
Database Collation utf8_general_ci
PHP Version 5.4.12
Web Server Apache/2.4.4 (Win64) PHP/5.4.12
WebServer to PHP Interface apache2handler
Joomla! Version Joomla! 3.3.7-dev Development [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent Mozilla/5.0 (Windows NT 6.1; rv:32.0) Gecko/20100101 Firefox/32.0

#### Additional comments
![screen shot 2014-10-17 at 06 42 59](http://issues.joomla.org/uploads/1/d74407df57a51934e1bd31da0be5dde2.jpg)

**Comment by brianteeman** [comment]
See #6871<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4765">issues.joomla.org/joomla-cms/4765</a>.</sub>
