### ISSUE TITLE
Add Spinner field in upcoming joomla version

### ISSUE THREAD

**Issue by MansiGarach9** [joomla/joomla-cms#4804]
#### Steps to reproduce the issue
Spinner field is missing in Joomla. This can be added as a new feature.

#### Expected result
http://jqueryui.com/spinner/

#### Actual result
This is a new feature.

**Comment by zero-24** [comment]
Closing as there was no reaction since `18 Oct 2014` this can allways reopen if we have code. Thanks :smile:
