### ISSUE TITLE
Joomla.JText._('LANGUANGE_CONSTANT') not working without mootools library

### ISSUE THREAD

**Issue by durgesh4** [joomla/joomla-cms#4839]
#### Steps to reproduce the issue
Use Joomla.JText._('LANGUANGE_CONSTANT') in any of the the js file
Include the file in the components view

Also use the JLoader import for replacing the language constant
& call the specified function
foe eg.

// Import helper for declare language constant
JLoader::import('ExampleFrontendHelper', JUri::root().'components/com_example/helpers/example.php');
// Call helper function
ExampleFrontendHelper::getLanguageConstant();

Enable the Mootools for the enable template & check the language constant working properly
Disable the mootools for the template & check the language constant not replaced properly.
#### Expected result
It should also be working with the Mootools disbaled.

#### Actual result
Not working without mootols

#### Additional comments
IS it necessary to enable mootools  for using Joomla language constant in the js files?

**Comment by mbabker** [comment]
Is this still an issue?

**Comment by dgt41** [comment]
It shouldn't be because core.js is not mootools dependent

**Comment by gunjanpatel** [comment]
I have go through the issue description and also tested, found that it work without Mootools. 
So, we can close this issue now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4839">issues.joomla.org/joomla-cms/4839</a>.</sub>

**Comment by gunjanpatel** [comment]
Set to "closed" on behalf of @gunjanpatel by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4839">issues.joomla.org/joomla-cms/4839</a>
