### ISSUE TITLE
Admin activation of users by email link not working if logged in to frontend

### ISSUE THREAD

**Issue by rvbgnu** [joomla/joomla-cms#4841]
#### Steps to reproduce the issue

Set up user registration to require admin to activate new users. Login to frontend as administrator in your default browser. In other browser create a new user. Once you receive the "verification" link, at the new user email address, copy and paste the link in the other browser, not your default one (where you logged in with your admin user) Click on the activation link. 

#### Expected result

 When successful, we got the message "The user's account has been successfully activated and the user has been notified about it."

#### Actual result

The default browser just shows the site frontend without message that the user has been activated.

#### System information (as much as possible)

Joomla 2.5.28-dev

#### Additional comments

Initial issue Submitted By: Torben Wölm - Open Date: 2013-09-14 03:55:07
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=32007&start=0

I can reproduce the issue on 2.5.28-dev, it is still there. But it has been fixed in 3.3.x but with different PRs, revert from regression. Please help me to find what code should be back ported from 3.3.x, if possible, to fix this in 2.5.x!

**Comment by Bakual** [comment]
I'm closing this issue since Joomla 2.5 is no longer supported and thus this will not be fixed anymore.
