### ISSUE TITLE
Search module doesn't like all categories

### ISSUE THREAD

**Issue by cdalibtek** [joomla/joomla-cms#4928]
#### Steps to reproduce the issue
* Create an article with in a subcategory
* Search for article with the search module
* Click on link

#### Expected result
* Article to display properly

#### Actual result
* Article loads behind image on home page

#### System information (as much as possible)
Joomla 3.3
Template theme1311

#### Additional comments
For example:
* Go to http://www.cdalibrary.org/events
* Click the article link to LEGO-Rama.  It takes you to http://www.cdalibrary.org/events/41-events/annual-events/80-lego-rama
* Go to http://www.cdalibrary.org/events
* Use the search box and search for "lego"
* Click on link to LEGO-Rama.  It takes you to http://www.cdalibrary.org/41-events/annual-events/80-lego-rama

As you will see, the search results excludes the /events/ portion of the path.

Other articles load correctly.  It just seems to be related to the category or subcategory it is in.  I moved the article to another sub category from the same parent and it loads just fine.  I copied the subcategory it works under and put the article under that and it doesn't work; it has the same problem.

Perhaps it will only work with the first subcategory?  I am not sure.

Christopher

**Comment by cdalibtek** [comment]
Sorry, I haven't had much time to come back to this.  I'm wondering if you can explain your answer.  I don't understand what you mean in your instructions.

**Comment by brianteeman** [comment]
Wow two years
