### ISSUE TITLE
Menu item redirecting wrongly

### ISSUE THREAD

**Issue by clinchergt** [joomla/joomla-cms#4934]
#### Steps to reproduce the issue

1. create an article for registered users only,
2. create a menu item to aforementioned article,
3. go to the front-end of the site and log in,
4. access the article through the menu item,
5. log out,
6. click menu item.

#### Expected result
Get error explaining I'm not authorized to access the article since I'm not logged in.

#### Actual result
Get redirected to the site's homepage.

#### System Information
Database: 5.5.40-0ubuntu0.14.04.1
PHP: 5.5.9-1ubuntu4.4 
Joomla version: Joomla! 3.3.6 Stable
Joomla platform version: Joomla Platform 13.1.0 Stable
User Agent: Mozilla/5.0 Firefox/33.0

#### Additional Information

Make sure to use an incognito/private browsing window to ensure that neither cookies nor the cache will affect the testing.

If you try accessing the article without ever having logged in, you'll get what was described in the "Expected result" section, so it's the logging in that's causing this behaviour after logging out.

**Comment by zero-24** [comment]
Closing as we have a PR by @clinchergt here: https://github.com/joomla/joomla-cms/pull/5019 Thanks
