### ISSUE TITLE
In Joomla! 3.3.6 the subcategories in menu items do not display on the frontend.

### ISSUE THREAD

**Issue by nemmar** [joomla/joomla-cms#4937]
#### Steps to reproduce the issue
Hi,
I have attached 12 screenshots of this Joomla bug issue.

In Joomla! 3.3.6 the subcategories in menu items do not display on the frontend. They displayed correctly prior to the upgrade from J2.5x to J3.3x and I did not change any menu/category/article display settings.

I have all the menu item settings set to "Global". The menu items use the "Global" Article Manager Option settings.
I didn't change any settings before or after upgrading from J2.5x to J3.3x so it should have stayed the same with subcategories displaying like they used to.

The subcategories are not listed on the "List All Categories" menu item pages. For example, if you go to this test site page:
http://2test-directory.nemmar.net/animals-wildlife

Only the top level categories display and no subcategories display. All the top level and sub-level categories should be displaying (like they did prior to the upgrade) on the "List All Categories" menu item pages. You can see examples of sub-categories that should be but are not displaying on the main page at:
http://2test-directory.nemmar.net/animals-wildlife/environmental-and-wildlife-conservation
http://2test-directory.nemmar.net/animals-wildlife/land-species

I cleared the cache and also tested this in Protostar template and my Joostrap template and the same problem occurs in both so it probably is a Joomla 3.3x bug.

#### Additional comments

![screen shot 2014-10-26 at 07 45 00](http://issues.joomla.org/uploads/1/8bc57f94f173b4bd1cbcdd069a9487d9.jpg)
![screen shot 2014-10-26 at 07 45 00](http://issues.joomla.org/uploads/1/a9ba57b270c1813e97d2a0b19dee0511.jpg)![screen shot 2014-10-26 at 07 45 00](http://issues.joomla.org/uploads/1/b27bfd8380e476442ebed8805bde39f4.jpg)![screen shot 2014-10-26 at 07 45 00](http://issues.joomla.org/uploads/1/582f847c12604b87d654b8d8e5e23559.jpg)![screen shot 2014-10-26 at 07 45 00](http://issues.joomla.org/uploads/1/09e6dc85c474e8389995373677893928.jpg)![screen shot 2014-10-26 at 07 45 00](http://issues.joomla.org/uploads/1/166a998e09bf183b9d2a2cc5aeb3de79.jpg)![screen shot 2014-10-26 at 07 45 01](http://issues.joomla.org/uploads/1/956467d21129bcc1b40b207597726562.jpg)![screen shot 2014-10-26 at 07 45 01](http://issues.joomla.org/uploads/1/5db8416a1962090faf19193f38b4cc0b.jpg)![screen shot 2014-10-26 at 07 45 01](http://issues.joomla.org/uploads/1/0eb383aaca4e8388ed3aed1478373795.jpg)![screen shot 2014-10-26 at 07 45 01](http://issues.joomla.org/uploads/1/2d5d507e4df5b4ad15257cb778de1efa.jpg)![screen shot 2014-10-26 at 07 45 01](http://issues.joomla.org/uploads/1/3c44f1c36d01b0b088ef3c2f26e59c07.jpg)![screen shot 2014-10-26 at 07 45 01](http://issues.joomla.org/uploads/1/c386a732680432b81d291008104b82b7.jpg)

**Comment by Harmageddon** [comment]
Closing this, as #5469 is merged.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4937">issues.joomla.org/joomla-cms/4937</a>.</sub>

**Comment by fbc** [comment]
This seems to be broken again in the recent Joomla Versions

**Comment by ghost** [comment]
@fbc can you please open a new Issue as Comments on closed Issues didn't get much Notice.
