### ISSUE TITLE
Table definitions for #_contentitem_tag_map are different

### ISSUE THREAD

**Issue by sovainfo** [joomla/joomla-cms#4943]
installation/sql/<db>/joomla.sql contains different definitions for a unique key. For MySQL it specifies type_id, content_item_id, tag_id. For both PostgreSQL it specifies type_alias, content_item_id, tag_id.
It is not difficult to make them the same, the question is which one is right?

Couldn't say from the usage of the table in Joomla, maybe the people from the SQL Performance had a look into this.

**Comment by alikon** [comment]
we need to use the same pk key on all db's
in this case the mysql pk is the one
