### ISSUE TITLE
Incorrect base meta tag for SSL websites

### ISSUE THREAD

**Issue by GregoryRusakov** [joomla/joomla-cms#4961]
I've recently moved my website to SSL and found that Base meta tag is still "http" not "https".
But if I change this line:
$buffer .= $tab . '<base href="' . $document->getBase() . '" />' . $lnEnd;

to this one:
$buffer .= $tab . '<base href="' .Juri::base(). '" />' . $lnEnd;

in file:
libraries/joomla/document/html/renderer/head.php

then everything works fine and Base meta tag is correct on all https pages.

**Comment by brianteeman** [comment]
As @Hackwar says please answer why you have @live_site set and why if you are now on https you didnt change it. 

I have set this issue to 'Information Required' and it will be closed in a few weeks if there are no updates<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4961">issues.joomla.org/joomla-cms/4961</a>.</sub>

**Comment by superdeluxxx** [comment]
Very weird that this problem still exists. I also just hardcoded it in: 

if (!empty($base))
		{
			$buffer .= $tab . '<base href="https://www.website.com/" />' . $lnEnd;
		}

Now everything is working fine.  Force SSL put the site into a loop

**Comment by brianteeman** [comment]
@superdeluxxx do you have a setting in live_site

**Comment by superdeluxxx** [comment]
In the configuration.php its set as  

$live_site = 'https://www.domain.com'; 

if that is what you mean. 
But that didn't kept the <base href="http://www.domain.com/"> from being shown without the httpS

**Comment by brianteeman** [comment]
Please try without anything being set fr live_site. You shouldnt need it

**Comment by zero-24** [comment]
Clsoing as we have a Pull Requrst: https://github.com/joomla/joomla-cms/pull/6270<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4961">issues.joomla.org/joomla-cms/4961</a>.</sub>

**Comment by nsplogin** [comment]
Nice Post
Hello
www.berg.gorbach.ph.ucla.edu/news-2/
http://www.berg.gorbach.ph.ucla.edu/news-2/
https://www.berg.gorbach.ph.ucla.edu/news-2/
[url=https://berg.gorbach.ph.ucla.edu/news-2/] Hello [/url]
<a href="https://berg.gorbach.ph.ucla.edu/news-2/"> Hello </a>
[Hello](https://berg.gorbach.ph.ucla.edu/news-2/)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4961">issues.joomla.org/tracker/joomla-cms/4961</a>.</sub>

**Comment by nsplogin** [comment]
I have never seen such blogs ever before that have completed things with all details I want.     <a href="https://www.scholarshipsgov.in/">Scholarship</a>
<a href="https://www.scholarshipsgov.in/www-scholarships-gov-in-2021-22/">Scholarship 2021-22</a>
<a href="https://www.scholarshipsgov.in/nsp-2-0-scholarship/">NSP 2.0 Scholarship</a>
       Sinkoth :-)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4961">issues.joomla.org/tracker/joomla-cms/4961</a>.</sub>

**Comment by scholarshippost** [comment]
Thank you for sharing. Excellent post…! It is a very great idea and unique content. Thank you so much.      <a href="https://www.nspgov.in/">NSP</a>
<a href="https://www.nspgov.in/aishe-login/">AISHE Login</a>
<a href="https://www.nspgov.in/national-scholarship-2022-23/">National Scholarship 2022-23</a>
          Sinkoth :-)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4961">issues.joomla.org/tracker/joomla-cms/4961</a>.</sub>

**Comment by imofullform** [comment]
Nice post author. Thank you. Keep it up. This article is very informative. It is very useful for me. Kindly share more articles with me. I shall be very thankful to you.  <a href="https://www.a2zfullformlist.com/">A2Z Fullform List</a>
<a href="https://www.a2zfullformlist.com/sme-full-form/">SME Full Form</a>
<a href="https://www.a2zfullformlist.com/rmp-full-form/">RMP Full Form</a>
       Sinkoth :-)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4961">issues.joomla.org/tracker/joomla-cms/4961</a>.</sub>

**Comment by ourjharkhand** [comment]
Found your post interesting to read. I cant wait to see your post soon. Good Luck with the upcoming update. This article is really very interesting and effective.     <a href="https://ourjharkhand.com/">Our Jharkhand</a>
<a href="https://ourjharkhand.com/e-pass-jharkhand-online-registration/">E Pass Jharkhand Online Registration</a>
<a href="https://ourjharkhand.com/e-uparjan-jharkhand/">E Uparjan Jharkhand</a>
<a href="https://nebsit.in/contact-us.html">Contact Us</a>
     Sinkoth :-)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4961">issues.joomla.org/tracker/joomla-cms/4961</a>.</sub>

**Comment by computertyingtest** [comment]
Thanks For sharing this Superb article. I use this Article to show my assignment in college<a href="https://atozwebsitereview.com/">.</a>
 it is useful For me Great Work              Sinkoth :-)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4961">issues.joomla.org/tracker/joomla-cms/4961</a>.</sub>

**Comment by computertyingtest** [comment]
Thank you so much for sharing excellent information share with your visitor. Your posts are very so cool and unique. I’m impressed by the details that you’ve on this website article. I am coming back to your website for more soon<a href="https://www.blog.typingspeedtestonline.com/">.</a>
                                Sinkoth :-)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4961">issues.joomla.org/tracker/joomla-cms/4961</a>.</sub>

**Comment by computertyingtest** [comment]
Thank you so much for sharing excellent information share with your visitor. Your posts are very so cool and unique. I’m impressed by the details that you’ve on this website article. I am coming back to your website for more soon<a href="https://oldcoinsellingbazaar.com/old-coin-sell-bank/">.</a>
                                Sinkoth :-)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4961">issues.joomla.org/tracker/joomla-cms/4961</a>.</sub>

**Comment by digitalindia02** [comment]
Really I enjoy your site with effective and useful information. It includes a very nice post with a lot of our resources.thanks for sharing. I enjoy this post.

[STS Karnataka](https://www.digitalindiagov.in/www-sts-karnataka-gov-in-login/)
[Labour Registration](https://www.digitalindiagov.in/labour-registration/)
[E- District Kerala](https://www.digitalindiagov.in/e-district-kerala/)
[SSA Gujrat Updated](https://www.digitalindiagov.in/ssa-gujarat-updated/)
[Digital Seva](https://www.digitalindiagov.in/digital-seva-updated/)
[CSC Login](https://www.digitalindiagov.in/csc-login-updated/)
[Meebhoomi Updated](https://www.digitalindiagov.in/meebhoomi-updated/)
[PMAY CSC Login Update](https://www.digitalindiagov.in/pmjay-csc-login-updated/)



S.Gupta<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4961">issues.joomla.org/tracker/joomla-cms/4961</a>.</sub>

**Comment by digitalindia02** [comment]
Thank you for sharing. Excellent post…! It is a very great idea and unique content. Thank you so much. 

[NSP Portal](https://www.nspgov.in/www-nsp-portal/)
[NSP Scholarship Renewal](https://www.nspgov.in/nsp-scholarship-renewal-2022-23/)
[National Scholarship Last Date 2022](https://www.nspgov.in/national-scholarship-last-date-2022/)
[NSP National Scholarship](https://www.nspgov.in/nsp-national-scholarship/)
[NSP Scholarship List 2022](https://www.nspgov.in/nsp-scholarship-list-2022/)
[Last Date NSP Scholarship 2022](https://www.nspgov.in/last-date-nsp-scholarship-2022-23/)
[National Scholarship Portal](https://www.nspgov.in/national-scholarship-portal-renewal-2022-23/)

S.Gupta<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4961">issues.joomla.org/tracker/joomla-cms/4961</a>.</sub>

**Comment by digitalindia02** [comment]
Thank you so much as you have been willing to share information with us. We will forever admire all you have done here because you have made my work as easy as ABC


[NSP Portal](https://www.scholarshipsgov.in/www-nsp-portal/)
[NSP Scholarship Renewal](https://www.scholarshipsgov.in/nsp-scholarship-renewal-2022-23/)
[National Scholarship Last Date 2022](https://www.scholarshipsgov.in/national-scholarship-last-date-2022/)
[NSP National Scholarship](https://www.scholarshipsgov.in/nsp-national-scholarship/)
[NSP Scholarship List 2022](https://www.scholarshipsgov.in/nsp-scholarship-list-2022/)
[Last Date NSP Scholarship 2022](https://www.scholarshipsgov.in/last-date-nsp-scholarship-2022-23/)
[National Scholarship Portal](https://www.scholarshipsgov.in/national-scholarship-portal-renewal-2022-23/)
[NSP Updated](https://www.scholarshipsgov.in/nsp-updated/)


S.Gupta<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4961">issues.joomla.org/tracker/joomla-cms/4961</a>.</sub>

**Comment by digitalindia02** [comment]
Very interesting article my friend Arthur. Link Building is a very important process in creating authority on blogs, so it is essential to use tools like the ones mentioned above. I'll save the page for future reading :)

[Number Location Tracker](https://www.mobilenumbertrackeronline.com/number-location-tracker-online-in-india/)
[Moblile Phone Location](https://www.mobilenumbertrackeronline.com/mobile-phone-location/)
[Track Locational](https://www.mobilenumbertrackeronline.com/track-location-of-a-mobile-number/)
[Last Location](https://www.mobilenumbertrackeronline.com/last-location-of-mobile-number/)
[Mobile Phone Number Search](https://www.mobilenumbertrackeronline.com/mobile-phone-number-search/)
[Mobile No Tracking 2](https://www.mobilenumbertrackeronline.com/mobile-no-tracking-2/)
[Mobile Number Tracker](https://www.mobilenumbertrackeronline.com/mobile-number-tracker-with-google-map-updated/)


S.Gupta<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4961">issues.joomla.org/tracker/joomla-cms/4961</a>.</sub>

**Comment by brianteeman** [comment]
@digitalindia02 are you really so stupid to think that this sort of spam will work

**Comment by Hackwar** [comment]
The user has been reported.
