### ISSUE TITLE
mod_tags_similar helper does not check core_publish_up or core_publish_down times/dates

### ISSUE THREAD

**Issue by heleneross** [joomla/joomla-cms#4979]
Joomla version 3.3.6
Using mod_tags_similar, the helper returns items marked as published using core_state=1 but it also returns items which have expired as no check is made on the core_publish_up or core_publish_down columns

Tested by editing the article published state and publish up and down dates.

I fixed it by editing mod_tags_similar/helper.php

added at line 42
```
$now         = JFactory::getDate()->toSql();
$nullDate    = $db->getNullDate();
```

and then modified the published tags where query
```
// Only return published tags
$query->where($db->quoteName('cc.core_state') . ' = 1 ')
     ->where('(' .$db->quoteName('cc.core_publish_up') . '=' . $db->quote($nullDate) . ' OR ' .$db->quoteName('cc.core_publish_up') . '<=' . $db->quote($now) . ')')
     ->where('(' . $db->quoteName('cc.core_publish_down') . '=' . $db->quote($nullDate) . ' OR ' .$db->quoteName('cc.core_publish_down') . '>=' . $db->quote($now) . ')');
```

**Comment by brianteeman** [comment]
OK I went ahead and created the PR #5606 
Please test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4979">issues.joomla.org/joomla-cms/4979</a>.</sub>
