### ISSUE TITLE
add placeholder on getinput('name', $placeholder); for ouput html 

### ISSUE THREAD

**Issue by alexonbalangue** [joomla/joomla-cms#4985]
#### Steps to reproduce the issue
i trying to edit from libreary getinput with use this function getinput($name, $placeholder);

#### Expected result
not show placeholder on ouput source code (html)

possible to adding this!!!

**Comment by mbabker** [comment]
From what I can tell placeholders are supported based on the HTML specification (http://www.w3.org/TR/html5/forms.html#the-placeholder-attribute) and have been since our 3.2 release.  Our form field API uses the `hint` attribute in the XML forms to display these.
