### ISSUE TITLE
jCaption  code added twice when cache enabled

### ISSUE THREAD

**Issue by adonismedia** [joomla/joomla-cms#4998]
When cache is enabled on first page load the system shows one caption, this is because the page has only just cached the first version of the page to the browser, assuming the cache plugin is enabled with browser caching enabled.

When the page is reloaded the jCaption code is added to the

tags again and the caption is added twice because the code is in the tags twice and thus running twice. Of course the first one was cached to the browser then readied on page load as the cached version is loaded by the browser.
jCaption needs to be updated in order to prevent this happening when cache is enabled.

**Comment by brianteeman** [comment]
Sorry no one has replied before @adonismedia 

I have no idea how to replicate this issue - can you explain step by step please

**Comment by brianteeman** [comment]
After nearly two months without response for the requested information I am closing this issue at this time. It can always be reopened if further information is provided as had been requested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4998">issues.joomla.org/joomla-cms/4998</a>.</sub>
