### ISSUE TITLE
Uploaded filenames are too limited

### ISSUE THREAD

**Issue by okonomiyaki3000** [joomla/joomla-cms#5001]
#### Steps to reproduce the issue
Go the media manager and upload an image with an @ in the name like:
filename@2x.jpg

I suppose I don't need to tell you why you might want to do this actually.

#### Expected result
The file will be uploaded with its name intact.

#### Actual result
The @ sign is stripped. Because MediaControllerFile calls JFile::makeSafe() which remove any slightly interesting characters from the file name.

#### System information (as much as possible)
Doesn't matter.

#### Additional comments
https://en.wikipedia.org/wiki/Filename

**Comment by zero-24** [comment]
Moving to `Needs Review` so a Maintainer can decide if this should changed or not. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5001">issues.joomla.org/joomla-cms/5001</a>.</sub>

**Comment by roland-d** [comment]
The PLT has decided not to implement this change and keep the current behavior. Thank you for your contribution.
