### ISSUE TITLE
JFolder::create fails when using open_basedir

### ISSUE THREAD

**Issue by stAn47** [joomla/joomla-cms#5012]
It seems that JFolder improperly parses open_basedir and prevents creation of folder. My open_basedir is set within defines.php file as this: 

ini_set('open_basedir', dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.':'.dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR.'vm2onj25'.DIRECTORY_SEPARATOR); 

my paths (as seen from php): 
/web/vm2/purity (is the joomla root)

i want to enable openbasedir to: 
/web/vm2/*
and 
/web/vm2onj25/*

the real linux paths as seen by apache document root
/srv/www/domain.com/web/vm2/
php's chroot is set to: 
/srv/www/domain.com

tested on php5.6 + xdebug (but the same behaviour should be on all php versions)
Joomla version 3.3.6

best regards, stan

**Comment by roland-d** [comment]
Hello @stAn47,

Thank you for your contribution.

The last comment here was on 13 November 2014. So the question is, Is this issue/pull request still valid?
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5012">issues.joomla.org/joomla-cms/5012</a>.</sub>

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5012">issues.joomla.org/joomla-cms/5012</a>.</sub>
