### ISSUE TITLE
Add Multiple Category Selection Option for Banners

### ISSUE THREAD

**Issue by heyjoecampbell** [joomla/joomla-cms#5057]
#### Steps to reproduce the issue

In specific banner the category is limited to single selection

#### Expected result

Have the ability to select multiple categories that a banner can be shown

**Comment by brianteeman** [comment]
Closing as expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5057">issues.joomla.org/joomla-cms/5057</a>.</sub>
