### ISSUE TITLE
com_search cut all short words when search by all phrase

### ISSUE THREAD

**Issue by alex-filat** [joomla/joomla-cms#5079]
It seems wrong when search by all phrase like 'vase 24 sm' then com_search leave only 'vase' and do not inform about. I think when we serch with mode 'all phrase' than 'vase 24 sm' is legal resonable phrase from logic point of view and  it has almost the same effect on performance like 'vase'.

**Comment by brianteeman** [comment]
Is this with regular search or smart search?
I couldnt replicate it with regular search<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5079">issues.joomla.org/joomla-cms/5079</a>.</sub>

**Comment by alex-filat** [comment]
Probably you cannot reproduce because if you use search phrase 'vase 24' then component displays full phrase but searches only by 'vase' because it cuts all short words.

**Comment by brianteeman** [comment]
I suspect that this is your problem
https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/en-GB.localise.php#L62

You will see that there is a lower limit defined of 3 characters

On 15 January 2015 at 17:51, alex-filat <notifications@github.com> wrote:

> Probably you cannot reproduce because if you use search phrase 'vase 24'
> then component displays full phrase but searches only by 'vase' because it
> cuts all short words.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5079#issuecomment-70129109>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by delfweb** [comment]
No it is not my problem.
If you search by long phrase which is combination of long(ligal - satisfy all filter criterias) and short words then phrase must be used with short worlds. If i want serach by phrase 'vase 24' i am exactly want to see VASES 24 sm long and not VASES 34 sm or any other. If serch phrase consists from two short phrases f.e. 'sm 34' then it is not ligal because all phrases not passed filter conditions.

**Comment by brianteeman** [comment]
Sorry but I disagree - it is exactly your problem - any search term that is smaller than the value set will be ignored. To change it for your site you need to change the minimum search length<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5079">issues.joomla.org/joomla-cms/5079</a>.</sub>

**Comment by alex-filat** [comment]
No it is still not. If i limit search world by 2 characters then server could be crushed in easy way.
Probably it is difficult for understanding but it makes real problems for our client and as a result for us.
I understant that all participant very busy and would not be involved into descovering diffucult thing like this, but it does not make Joomla better. This task was considerted 5 monthes and now it is rejected.
All of this just frustrating. Nice direction, keep this way.

**Comment by mbabker** [comment]
Just as described, the issue relates to the method that was linked to above.  When searching with the "older" search component, there is a method that checks the length of each term in the search and filters anything that doesn't match the minimum length.  By default, this means a search will exclude any term with only 1 or 2 characters.  "vase 24" is considered two terms as the terms are split by spaces, and "24" does not match the three character minimum so is stripped.  As coded, the existing behavior is correct.  What it sounds like you're looking for is an extended logic which would allow "vase 24" as a single term, that would require quite a bit of work on the search platforms and our language parsing capabilities and is borderline not feasible at this time (in my opinion).

**Comment by alex-filat** [comment]
Hi Michael, i have already made pull request with all nessesary improvements we are using inside our company. It is very small change in code , i just cannot understand how to connect this discussion to pull request, i would be very appreciate if you help https://github.com/joomla/joomla-cms/pull/5442.

**Comment by infograf768** [comment]
Would be interesting to provide a way to override the xx-XX.localise.php in a similar way we provide language constants/values override in language manager.
