### ISSUE TITLE
No more selectable tags in select box (type=tags) after first one is saved

### ISSUE THREAD

**Issue by ghost** [joomla/joomla-cms#5090]
Joomla 3.3.6 and current staging 3.4.0. PHP 5.4, XAMPP. Default settings.
(I remember that this issue was already mentioned in a German forum thread but don't find it at the moment.)

Test instructions:

1) Create 4 tags in com_tags component if you have none already.
2) Open an article or contact or category or... (everywhere same behaviour)..
3) Select just 1 tag. You'll see all 4 tags in select box. All are selectable.
4) Save item.
5) Try to select a 2nd tag. Select box is empty. No selectable tag.
6) Remove tag by clicking on close cross of the tag. Only this tag is shown and selectable in select box.
7) All other tags can only be received by typing title into tag field.

**Comment by bertmert** [comment]
This is still an issue in 3.4.0 stable

**Comment by zero-24** [comment]
Closing as we have a PR by @bertmert<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5090">issues.joomla.org/joomla-cms/5090</a>.</sub>
