### ISSUE TITLE
[SEO] - Deleted Tags not redirecting to 404 Error page.

### ISSUE THREAD

**Issue by ManuxGR** [joomla/joomla-cms#5148]
Did a search and didn't find similar issue so i am posting.

Create and delete a tag.
Paste the expired url.
You will be redirected to a normal page which displays this message -> "No matching items were found."

GWMT returns 404 Soft error.

It's also been reported here http://forum.joomla.org/viewtopic.php?f=712&t=836170

Please if this is already fixed point me to the solution.

Thanks :)

**Comment by elkuku** [comment]
This is just a **TEST** - Please ignore me :wink:

**Comment by zero-24** [comment]
Closing as we have a PR that fix it at #8040
