### ISSUE TITLE
Why custom path taking highest priority in Layout

### ISSUE THREAD

**Issue by mManishTrivedi** [joomla/joomla-cms#5157]
Joomla has already provided layout with great overriding option. But I feel one issue with layout-overriding.  When I put custom base-path then it would not be overridden. So I want to override JLayoutFile class in my extension and change sequence of path priority. 

Following path priority followed
1. templates/mytemplate/html/layouts/com_mycomponent
2. components/com_mycomponent/layouts
3. templates/mytemplate/html/layouts
4. base_path (custom path set by me)
5. layouts

I need feedback from Joomla-developers.  
@phproberto   @Bakual  @mbabker

**Comment by zero-24** [comment]
Closing as we have a still open PR at #3231 Thanks.
