### ISSUE TITLE
Front end module editing with select box

### ISSUE THREAD

**Issue by brbrbr** [joomla/joomla-cms#5158]
Website has a module with a dropdown menu ( &lt;select> )

for example a custom html module with

&lt;select>
&lt;option>one&lt;/option>
&lt;option>two&lt;/option>
&lt;/select>

user is logged in and module front end editing is enabled

Each attempt to select an option results in a on.mouseenter for the jmoddiv event and the selectbox loses focus

thus it gets impossible to select an option
appears to be a known issue with mouseenter/mouseleave
http://stackoverflow.com/questions/6212309/problem-with-jquery-mouseleave-firing-when-container-has-select-box

**Comment by brianteeman** [comment]
I am unable to replicate this after the following the test instructions above on the latest release of Joomla. Please can you confirm that you are still having this issue and provide more information how to replicate it.

This issue will be closed automatically if there is no further information.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5158">issues.joomla.org/joomla-cms/5158</a>.</sub>

**Comment by roland-d** [comment]
@brbrbr I cannot reproduce the issue either. The dropdown options are selectable even when front-end module editing is enabled.

Please provide clearer instructions if you still have the issue on how to reproduce the issue. If no reply is received within 4 weeks, this issue will be closed.

Thanks for understanding.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5158">issues.joomla.org/joomla-cms/5158</a>.</sub>

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5158">issues.joomla.org/joomla-cms/5158</a>.</sub>
