### ISSUE TITLE
Missing TFA tab: edit user account in administrator using link in upper-right corner dropdown menu

### ISSUE THREAD

**Issue by Klipper** [joomla/joomla-cms#5162]
The extra tab for Two Factor Authentication(TFA) is missing when trying to edit the user-account in administrator.

How to reproduce: 
- The tab is only missing when you choose 'Edit Account' menu-item from the User dropdown-menu at the upper right corner of the administrator.( Above the Joomla! logo + name).

- Both Two Factor Authentications plugins are enabled. (Doesn't matter if the plugins are enabled for front-end, back-end or both)
- When accessing user-accounts using the user manager, or clicking a link in the 'logged-in users module' on the administrator control-panel, the TFA-tab is present.

- The missing TFA-tab is a problem for back-end users, like authors, who have no access to the user manager or logged-in users module. The only possibility to access/edit their profile is using the dropdown menu at the upper right corner. 
In current situation they cannot edit their profile for securing their account with TFA, because of missing TFA-tab.

**Comment by brianteeman** [comment]
Based on the comments above I am closing this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5162">issues.joomla.org/joomla-cms/5162</a>.</sub>
