### ISSUE TITLE
Pagination in Tags menuitem doesn't have an end, if set via URL/request (?start=x or ?limitstart=x).

### ISSUE THREAD

**Issue by cwps** [joomla/joomla-cms#5164]
In Pagination if _limitstart_ is set more than the last page via URL or request, the result always giving the last page articles list.
I found this when I try to implement JQuery Infinite Scroll in 'Tagged Items' menu item type. It giving me literally infinite scrolling the page.

#### Steps to reproduce the issue
1. Clean install Joomla 3.3.6 without additional data.
2. Create a number of articles and give them the same tag.
3. Create a menu item type 'Tagged Items'.
  - On 'Pagination' tab: set Display Select to Hide, Pagination to Show.
  - On 'Item Selection Option' tab: set the Maximum Items so it will give pagination on the front-end.
4. Click on the menu item in the front-end
5. Go to the last page, and via URL change the x in _?start=x_ (or ?limitstart=x for non sef) to eg. 9999999.

#### Expected result
Empty list page, or display error that the page doesn't exist, or 404 page.

#### Actual result
Always return to the last page of that menu item.

#### System information (as much as possible)
Database Version:	5.5.38
Database Collation:	latin1_swedish_ci
PHP Version:	5.3.10
Web Server:	Apache/2.2.22 (Ubuntu)
WebServer to PHP Interface:	apache2handler
Joomla! Version	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT

**Comment by brianteeman** [comment]
Closed your issue
Hi you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.
