### ISSUE TITLE
Category (name of menu item) is not displayed (for blog or category) of articles in hyperlinks (on hompage)

### ISSUE THREAD

**Issue by radik10** [joomla/joomla-cms#5182]
#### Steps to reproduce the issue
Install clean (with no content) joomla 3.2.7 or 3.3.6 and create 1 new category, and create 2-3 articles in the created category. Create blok menu item of crated articles as hompage. Click in created menu item (blog) on fronend - and see hyperlink in browser. If you want to have blog (not featured) of articles from desired category this is problem...

#### Expected result
After  clean installation of J3.2.7 or J3.3.6 there is missing category for articles displayed in that blog - in hyperlink of article - see example below.

Example: category name: "category 1", menu item (for blog) "category 1" and 2 articles in this category "article 1" and "article 2" - and these articles are displayed in blog, e.g. for homepage.

In J2.5 there was link for blog/category list "www.mypage.xx/category-1/1-article-1" but in joomla 3.2.7 or J 3.3.6 (new installs) there is for article in blog only: "www.mypage.xx/1-article-1"  - WHY???? category is important for webpage structure, even more if you upgrading from J25 to J3+ (you want to have same links to articles) - because of SEO rankings a good orientation on pages... Obviously there is missing "name of menu item".

same problem is for list of categories, breadcrumbs... - there is missing category name (name of menu item) in hyperlink to article.

**I thing it is bug of Joomla 3.2.7 and newer - there are missing some files...**

Live example with 2 articles (articles belongs to category "destinacia" and it is also name for menu of blog is here:
http://joomlatest336.r-art.sk/, corect links for articles belonging to blog or category lists must be: http://joomlatest336.r-art.sk/index.php/destinacia/2-zupkov and not http://joomlatest336.r-art.sk/index.php/2-zupkov as is now!

#### Actual result

hyperlinks without categories (of articles) or manu item names - if you have blog of categorized articles as hompage

#### System information (as much as possible)
same resaults on
J3.2.7 with PHP 5.3.8, MySQL 5.5.16 
or 
J 3.3.6 with PHP 5.3.27, MySQL 5.5.33

**Comment by nickdring** [comment]
Hey Brian, is this a bug in Joomla or a feature?

**Comment by brianteeman** [comment]
This is definitely the expected behaviour. If you have a menu item of / then the articles linked to from that will always be /article

I have gone back to joomla 2.5 and the behaviour is exactly the same

If you want the articles linked to from the home page to include the category name then you will need to have an additional menu item that points to that category<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5182">issues.joomla.org/joomla-cms/5182</a>.</sub>
