### ISSUE TITLE
Hide the sidebar

### ISSUE THREAD

**Issue by montano** [joomla/joomla-cms#5187]
![extension manager install](https://cloud.githubusercontent.com/assets/873620/5166176/badc770e-73bb-11e4-93aa-13083fe01261.png)

I applied the upgrade package to J3.3.6 and the Hide the Sidebar function does not seem to work.  I will try it on a clean install.

**Comment by brianteeman** [comment]
After several weeks without reply I am closing this - if it is still an issue it can always be reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5187">issues.joomla.org/joomla-cms/5187</a>.</sub>
