### ISSUE TITLE
FormFieldEditor does not pass colums value

### ISSUE THREAD

**Issue by rb-nk** [joomla/joomla-cms#5209]
#### Steps to reproduce the issue
Create form with 
```
  <field name='description'
  type="editor" 
  cols="5"
  rows="5"
  label='COM_NKCOMP_FIELD_GROUPTARGET_LABEL'
  description='COM_NKCOMP_FIELD_DESC'
  required="true"
  buttons="false"
  filter="JComponentHelper::filterText"
/>
```
When rendered in components administration view, the value for the attribute "cols" is not shown in the HTML output for the according textarea element. 

#### Expected result

Value for cols should be passed to HTML-Element.

#### Actual result

Empty attribute in HTML-Element textarea: cols=""

#### System information (as much as possible)
Linux, Apache2, php 5.4

#### Additional comments
traced it down to libraries/cms/form/field/editor/editor.php line 249:

```
249c249
< $this->name, htmlspecialchars($this->value, ENT_COMPAT, 'UTF-8'), $this->width, $this->height, $this->cols, $this->rows,
---
> $this->name, htmlspecialchars($this->value, ENT_COMPAT, 'UTF-8'), $this->width, $this->height, $this->columns, $this->rows,
```
In JFormFieldTextarea is no class variable "cols" but a class variable "columns".

**Comment by zero-24** [comment]
Closing as we have a PR: #7277
