### ISSUE TITLE
Login redirect to media manager

### ISSUE THREAD

**Issue by gilestaylor** [joomla/joomla-cms#5211]
#### Steps to reproduce the issue
Login session timed out when selecting the media manager
Login again and the redirect will send you to the 
administrator/index.php?option=com_media&view=mediaList&tmpl=component&folder=
with no access to menus 

#### Expected result
Media manager screen with administrator options available with the folders displayed as iframes

#### Actual result
Stuck in the images folder with no navigation tools, you have to edit the url to get out of this page.

#### System information (as much as possible)
Joomla 3.3.6
Database Version	5.5.29
Database Collation	latin1_swedish_ci
PHP Version	5.4.10
Web Server	Apache
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by spignataro** [comment]
Fixed issue with pull request here: https://github.com/joomla/joomla-cms/pull/7472<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5211">issues.joomla.org/joomla-cms/5211</a>.</sub>

**Comment by brianteeman** [comment]
Closing as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5211">issues.joomla.org/joomla-cms/5211</a>.</sub>
