### ISSUE TITLE
Category alias can't contain only numbers and dashes

### ISSUE THREAD

**Issue by erichforler** [joomla/joomla-cms#5215]
#### Steps to reproduce the issue
1. Create a category named "projects"
2. Create a second category named p1 and make it a child of "projects".
3. Create a third category named 1.2.3 and make it a child of p1. Save it with the default alias 1-2.3.
4. Create a menu entry of the List All Categories type and select "projects". 
5. Go to the front end of the site and navigate to the new menu entry. 
6. Click on it so that you see subcategory p1. 
7. Click on p1 so that you see the subcategory 1.2.3. 
8. Click on 1.2.3

Make sure that your Article Manager | Options | Category | Empty Categories, is set to Show.

#### Expected result
Should display an empty category list. 

#### Actual result
You get a 404 error. 

#### System information (as much as possible)
LAMP stack. 
Joomla 3.3.6

#### Additional comments
If you put any text character at the start of the alias string (eg. v1-2-3 instead of just 1-2-3) the problem goes away. 

Summary
Alias should not allow only numbers.

**Comment by brianteeman** [comment]
Setting to needs review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5215">issues.joomla.org/joomla-cms/5215</a>.</sub>

**Comment by KlausKrippeit** [comment]
@test not reproducible<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5215">issues.joomla.org/joomla-cms/5215</a>.</sub>

**Comment by astridx** [comment]
I tested it with the sample data and I see wrong articles. The first article belongs to the categorie Components ….

**Comment by zero-24** [comment]
Closing as we have a PR here that fix that in a B/C way: https://github.com/joomla/joomla-cms/pull/8141 

Thanks :smile:
