### ISSUE TITLE
Fatal error: Call to a member function checkAnswer()...[Captcha]

### ISSUE THREAD

**Issue by ITPrism** [joomla/joomla-cms#5218]
When I try to send a message to a user via contact form, I receive this error.

**_Fatal error: Call to a member function checkAnswer() on a non-object in ...\libraries\cms\form\rule\captcha.php on line 52_**

NOTE:
To reproduce the bug, you have to configure the captcha to work for contacts. 
When it works with captcha, you must **disable the plugin "Captcha - ReCaptcha"**.
Now, when you try to send a message via contact form, you will get that error.

**Comment by zero-24** [comment]
@ITPrism you need to disable the Captcha at the global configuration:
![captcha_disable](https://cloud.githubusercontent.com/assets/2596554/7731224/49cbdeac-ff1f-11e4-8b00-91b2e5520e42.PNG)

Please notice also the red message into of the contact for. Closing as no issue. Thanks :smile:
