### ISSUE TITLE
Available updates are not shown immediately

### ISSUE THREAD

**Issue by clausw** [joomla/joomla-cms#5263]
My joomla-installation is in german, so i hope my translation of menu-items and buttons are understandable!
=> the fields for lables, version, ... are missing in the github-form "issues/new"

#### Steps to reproduce the issue
1. Login in Joomla backend
=> Available update is shown in the left menu "maintenance#Extension updates available (1)"
2. Click on "Extension updates available" => administrator/index.php?option=com_installer&view=update
3. No update will be shown!
4. The user have to select "search for updates" to show the available updates

#### Expected result
The  available update are shown, after click on "maintenance#Extension updates available" on page administrator/index.php?option=com_installer&view=update, without an additional click on "search for updates" (Aktualisierung suchen)

#### Actual result
No updates are shown after click on "maintenance#Extension updates available"

#### System information (as much as possible)
Joomla: 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT 
Browser: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0 

#### Additional comments
It is an minor mistake, but for security updates, it will be better to show the update immediately, because some user select the menu-item and don't click on "seatch for updates" and so they don't install available updates (me to, at the first steps with J!3.3!)

**Comment by NathanHawks** [comment]
Any particular reason found updates aren't being stored in the database in components/com_installer/controllers/update.php, InstallerControllerUpdate::ajax around line 189?

Cuz I'm looking for a bug to fix :)

**Comment by Bakual** [comment]
Fixed already with a different approach in staging with https://github.com/joomla/joomla-cms/pull/6727
