### ISSUE TITLE
For menu item type "Menu Heading" the "Link Type" tab is blank

### ISSUE THREAD

**Issue by AndyGaskell** [joomla/joomla-cms#5332]
#### Steps to reproduce the issue
1. Log into Joomla admin
2. Go to "Menus" -> "Main Menu" -> "Add New Menu Item"
3. For the "Menu Item Type" field select "Menu Heading"
4. Click on the "Link Type" tab, it is blank.

#### Expected result
The "Link Type" tab for other menu item types lets you set "Link Title Attribute", "Link CSS Style", "Link Iimage"  ans "Add Menu Item".
In Joomla! 2.5.27 these properties were set-able for "Menu Heading" menu item types.

#### Actual result
The "Link Type" tab is blank. I would have expected to be able to set the same attributes for "Menu Heading" menu items types.

#### System information (as much as possible)
First noticed in Joomla! 3.3.6 but also seen in Joomla! 3.3.1

System Information
PHP Built On 	Linux penguin.directrouter.co.uk 2.6.32-531.23.3.lve1.2.66.el6.x86_64 #1 SMP Fri Sep 12 10:57:40 EDT 2014 x86_64
Database Version 	5.6.21
Database Collation 	utf8_general_ci
PHP Version 	5.4.32
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:33.0) Gecko/20100101 Firefox/33.0 

#### Additional comments
Looking at the documentation at https://docs.joomla.org/Help33:Menus_Menu_Item_Menu_Item_Heading and the screen grab there, these tabs have evolved a bit.

If folk think this is a fair bug I'm happy to try and code up a fix.

I checked my Apache logs and didn't see any warnings.

I noticed the FireBug console puts out 2 lines...
Use of getAttributeNode() is deprecated. Use getAttribute() instead. mootools-core.js (line 108)
content is null tab-events.js (line 40) <System>

I googled this and didn't really find anyone else with the same issues. Perhaps not many folk use the combination of "Menu Heading" and "Link Type" tab.

This is the first bug I've submitted, hope this is ok.

Thanks!

[screen shot 2014-12-06 at 00 20 35](http://issues.joomla.org/uploads/1/8dea08e82c68a9b519763537bae0de9e.png)
[screen shot 2014-12-06 at 00 20 32](http://issues.joomla.org/uploads/1/e99290f778f887288592eda7537b839b.png)

**Comment by brianteeman** [comment]
See #6004 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5332">issues.joomla.org/joomla-cms/5332</a>.</sub>
