### ISSUE TITLE
Wrong URL on featured articles page in Google

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#5389]
#### Steps to reproduce the issue

I've created one-page website with the only menu item "Home" (standard featured articles mode)
As a result I see Google have indexed a wrong URL:

[domainname]/component/content/featured.html?id=featured

I've noticed it on different websites I've created. So, I suppose it's kind of bug.

**Comment by Sulpher** [comment]
@Kubik-Rubik Hello Viktor, of course. Here are two websites:
1. [removed] - one-page site 
Google indexed [removed].com/?view=featured 
(I've tried to deny access to /?view=featured via robots.txt)
1. http://joomlabook.ru - little experimental website 
   Google indexed joomlabook.ru/component/content/featured.html?id=featured

**Comment by roland-d** [comment]
Hello @Sulpher 

Thank you for your contribution.

The last comment here was on December 11, 2014. So the question is, Is this issue/pull request still valid? If it is still valid, what should be the solution?
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5389">issues.joomla.org/joomla-cms/5389</a>.</sub>

**Comment by brianteeman** [comment]
closed as per the last comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5389">issues.joomla.org/joomla-cms/5389</a>.</sub>

**Comment by Sulpher** [comment]
Hello @roland-d, 
Thanks for reply. There is no such problem with latest Joomla version anymore.
