### ISSUE TITLE
ACL heritage on module editing

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#5397]
#### Steps to reproduce the issue
joomla 3.4 beta2
test 1
1 one groupe X in editor group
2 editing module in front **work**

test 2
1 one groupe X in editor group
2 disable editing module for group X
3 allow editing group X for specific module
2 editing module for this specific module in front **doesn't work**

test 3
1 one groupe X in editor group
2 disable editing group X for specific module
3 disable editing module in front **work**

test 4
1 one groupe X in registred group
2 editing module in front **disable ok**
3 allow group X to editing specific module **doesn't work**

#### Expected result

i don't understand why i can't create a user group and allow editing module specificly in heritage mode : 

->disable editing for all module ->actived for specific module

Sorry for my bad english

**Comment by brianteeman** [comment]
@sanderpotjer could you check this please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5397">issues.joomla.org/joomla-cms/5397</a>.</sub>

**Comment by micker** [comment]
i redo my test
1 create a group
2 disable module edition for this group
3 activaved edition module for specific module 
=> rule is green but doesn't work

1 create group
2 enable module edition for this group
3 desactived module edition for specific module
=> rule is green and it work ....
but not realy good solution if you have 20 modules and need to create a group how can edit specific module ...

**Comment by micker** [comment]
update to 3.4 beta 1 same issue with front-end editing rule
for groupe allow editing in spcific module doesn't work if parent not allowed
=> module button editing appear but we can't edit
default module ACL
![screen shot 2015-02-02 at 12 47 38](http://issues.joomla.org/uploads/1/bfb6c630fa45f451633b0d49a69a8dfa.jpg)
specific module acl
![screen shot 2015-02-02 at 12 45 17](http://issues.joomla.org/uploads/1/9aadba5feffacd320b681820f2e17501.jpg)

some idea ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5397">issues.joomla.org/joomla-cms/5397</a>.</sub>

**Comment by micker** [comment]
on beta2 display is better => 
![screen shot 2015-02-04 at 00 43 38](http://issues.joomla.org/uploads/1/5ccf0e773853f58c8c0fc256d667e76a.jpg)
but we can't do this
denied editing all module for group and allow editing for specific module
can you coinfirm that is normal ? (not realy powerfull)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5397">issues.joomla.org/joomla-cms/5397</a>.</sub>

**Comment by micker** [comment]
for @sanderpotjer @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5397">issues.joomla.org/joomla-cms/5397</a>.</sub>

**Comment by micker** [comment]
cge for inherite ... ACL seems to be ok in backend
but front-end say that user can't edit module 
![screen shot 2015-02-04 at 02 18 15](http://issues.joomla.org/uploads/1/8b4a6eb866927f73da9fd38f74c97730.jpg)![screen shot 2015-02-04 at 02 18 16](http://issues.joomla.org/uploads/1/ef1b0dbf9c1a46fb57407819d9beaf54.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5397">issues.joomla.org/joomla-cms/5397</a>.</sub>

**Comment by micker** [comment]
nobody to check this ?

**Comment by sanderpotjer** [comment]
I'm happy to look into this, but won't have time for it before this weekend.

**Comment by micker** [comment]
ok no problem if you need a site for test i can send you my access

**Comment by micker** [comment]
hello friendly bump
tested on beta 3 => same error<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5397">issues.joomla.org/joomla-cms/5397</a>.</sub>

**Comment by micker** [comment]
firendly bump<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5397">issues.joomla.org/joomla-cms/5397</a>.</sub>

**Comment by micker** [comment]
test on rc error still alive<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5397">issues.joomla.org/joomla-cms/5397</a>.</sub>

**Comment by mbabker** [comment]
> denied editing all module for group and allow editing for specific module
> can you coinfirm that is normal ? (not realy powerfull)

This is normal given the current ACL system.  Once you explicitly set an option, a child object cannot override it.  So if you explicitly set deny on the component level for a group to edit modules, any child groups of that group will not be able to edit nor will you be able to allow access to a specific module in this manner.

To accomplish what I think you're suggesting, here is what I did in a testing environment:

1) Create a new group and set the Group Parent as Public (by default, public permissions are all set to inherit so there are no hard defines set yet)
2) If you want the group to be able to edit modules in the backend, in the Global Configuration you'll need to give this group "Admin Login" permission.  If you want the group to be able to edit modules in the frontend, in the Global Configuration you'll need to give this group "Site Login" permission.  Do not change any other values.
3) In the Module Manager, if you want users in the group to be able to edit modules in the backend, you'll need to give the user "Access Administration Interface" permission.  If you want them to be able to edit all modules from the frontend, you'll need to give them "Frontend Editing" permission.  Do not change any other value.
4) In the module(s) you want this group to be able to edit, give them "Edit" permission.  You should also set "Frontend Editing" if you want to allow users to edit modules on the frontend.
5) Depending on the types of permissions you've given the group, you may need to add your group to the "Registered" or "Special" viewing access groups so they see all of the correct info.
6) You should now have a user group which is able to edit only the specific modules you want them to.

**Comment by micker** [comment]
Hello thanks for explain but if you read my last test inherit doesnt work...
If i use inherit in module config (not allow) and after allow on specific module
Display say that ls ok un autorisation
In front editing icon is display but impossible to édit....
If i do same config in category that work
Inherit in module rule doesnt work
I van send you a link for testing

**Comment by Bakual** [comment]
@micker See the merged PR #6113 Michael did yesterday. I think that's exactly the issue you describe and which should be fixed with current staging (not yet fixed in RC).

**Comment by micker** [comment]
ok i switch on pr #6113 for testing patch thanks

**Comment by zero-24** [comment]
@micker as #6113 is merged can we close the issue here?

**Comment by zero-24** [comment]
Closing as we have a merged PR (#6113). If we have still issues please open a new issue that describes the current behavior with the patch. Thanks :+1:
