### ISSUE TITLE
JHelperTags missing table include call

### ISSUE THREAD

**Issue by paul-muckypuddle** [joomla/joomla-cms#5404]
When using getTagItemsQuery() in JHelperTags you can specify whether or not to include_children. Setting this to 'true' ends up in a call to getTagTreeArray() (line 511), whereby an attempt is made to instantiate an JTable object (line 642). However, as the include path isn't updated to include the necessary tables folder this fails, and calling the isLeaf() method (line 644) on the supposed JTable results in:

Fatal error: Call to a member function isLeaf() on a non-object in /home/account/public_html/libraries/cms/helper/tags.php on line 647

I think the fix is just to update the include path before the instantiation - tried it on my J! 3.3.6 install and the error disappears.

**Comment by roland-d** [comment]
Hello @paul-muckypuddle

Thank you for your contribution.

The last comment here was on December 11, 2014. So the question is, Is this issue/pull request still valid? I noticed the line numbers are no longer matching.

If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5404">issues.joomla.org/joomla-cms/5404</a>.</sub>

**Comment by brianteeman** [comment]
Closed as per the last comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5404">issues.joomla.org/joomla-cms/5404</a>.</sub>
