### ISSUE TITLE
JHelperTags potentially uses wrong database

### ISSUE THREAD

**Issue by okonomiyaki3000** [joomla/joomla-cms#5417]
#### Steps to reproduce the issue
This part is tricky. You will need two databases and some custom code that is able to operate on both of them. Let's say you create an instance of `JTableContent`, it registers a `JTableObserverTags` to handle some stuff related to tags. This, in turn, uses a `JHelperTags` to store, delete, etc. So, for example, lets say you have two Joomla! installations, A and B. A has a custom component that access B's database, get an instance of `JTableContent` and manipulate that in some way. When it saves or performs some other observable operation, `JHelperTags` may be called upon to do something with B's tags but some of its functions will be operating on A's database while others will operate on B's. The most likely result is that you will lose some tag associations from the article you're working on but other, worse issues may also be possible.

#### Expected result
Well, you'd expect that when you perform some operation on B's content, tag associations will not be lost or corrupted or whatever. 

#### Actual result
You may lose tag associations, you may have other problems.

#### System information (as much as possible)
Well, not really relevant except that this could only occur if you're working on more than one database.

#### Additional comments
Yes, I know this is quite obscure. It is, nevertheless, a real issue.

**Comment by roland-d** [comment]
Hello @okonomiyaki3000 

Thank you for your contribution.

The last comment here was on December 13, 2014. So the question is, Is this issue/pull request still valid? If so, could you do a pull request for this?

If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5417">issues.joomla.org/joomla-cms/5417</a>.</sub>

**Comment by okonomiyaki3000** [comment]
The problems with this code are not apparent unless javascript is being run in "strict" mode so the first thing you need to do to test it is to put:
```javascript
"use strict";
```
Just inside the closure. Then, go to any page that uses the html5fallback file. The article edit page in the administrator, for example. Look in your browser's console. You should see some errors. This patch fixes those errors.

**Comment by brianteeman** [comment]
Closed as per the comment above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5417">issues.joomla.org/joomla-cms/5417</a>.</sub>
