### ISSUE TITLE
Install from web not working if administration forces SSL

### ISSUE THREAD

**Issue by sisko1990** [joomla/joomla-cms#5421]
#### Steps to reproduce the issue
Install a Joomla! 3.3.6 with "Install from Web" under "Extension Manager" -> "Install". Force SSL in Joomla! configuration for at minimum for Administration. Then try to use the "Install from Web" Tab. 

#### Expected result
It should work as without any SSL.

#### Actual result
Doesn't work, because the browser (tested it with Firefox and Chrome) will not load no SSL content (http://extensionscdn.joomla.org) in an SSL encrypted site (the administration).

#### System information (as much as possible)
Joomla! 3.3.6; Firefox 34.0

#### Additional comments
It would be enough to get a SSL certificate for extensionscdn.joomla.org, so this request is possible: https://extensionscdn.joomla.org

**Comment by brianteeman** [comment]
As the entire Install from Web code is currently being re-written I am going to close this as it refers to the old code base. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5421">issues.joomla.org/joomla-cms/5421</a>.</sub>
