### ISSUE TITLE
Cache Lite storage handler ignores options passed in constructor

### ISSUE THREAD

**Issue by codealfa** [joomla/joomla-cms#5422]
#### Steps to reproduce the issue
Create a cache object using JCache::getInstance(), for eg.;

$options = array(
    'defaultgroup' => 'custom_group',
    'checkTime'    => TRUE,
    'caching'      => 1,    
    'application'  => 'site',
    'language'     => 'en-GB',
    'lifetime'     => 60 * 60 * 60
);

$cache = JCache::getInstance($options);

Set cache handler to CacheLite in Global Configurations. 

#### Expected result
The options passed to the Cache object constructor should overwrite the options in Global Configurations. For instance if caching is off then caching should still work because caching is set to 1 in the options.

#### Actual result
Options passed to the Constructor are widely ignored. If caching is turned off in Global Configurations then no caching occurs. If it is turned on then the lifetime in Global Configurations is used.

I can get it to work by setting:
$cache->setCaching(1);
$cache->setLifeTime(60 * 60 * 60);

But then checkTime is ignored and cache is created every time instead of using the existing cache. 

If caching is turned on in Global Configurations then everything works as expected.

#### System information (as much as possible)
Windows 7
Joomla 3.6.6
PHP 5.4.34
Chrome

**Comment by brianteeman** [comment]
Hi 

Sorry that no one has replied to this before. Is this still an issue with the current release of Joomla or has it been resolved elsewhere?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5422">issues.joomla.org/joomla-cms/5422</a>.</sub>

**Comment by brianteeman** [comment]
Closed due to inactivity - it can always be reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5422">issues.joomla.org/joomla-cms/5422</a>.</sub>

**Comment by svenbluege** [comment]
This is still an issue. I'm currently encountering this issue as well.
