### ISSUE TITLE
Problem with ampReplace on Contact

### ISSUE THREAD

**Issue by GreenLion1010** [joomla/joomla-cms#5441]
Hi Community,

i have certain content items with a hyperlink to a contact item.
now i have the problem, that joomla is converting the "&" to "&amp;" to create the link to navigate to the contact.
the link i got in the contenct element is: index.php?option=com_contact&amp;view=contact&amp;id=3&amp;catid=95&amp;Itemid=435

but thats wrong with all the &amp; tags.

i use the jce editor to create these links.
but also if i disable the editor, i get the links like above shown, which causes the following error on the page:  Notice: Trying to get property of non-object in /srv/www/vhosts/kubler.ch/httpdocs/templates/as002057/index.php on line 42

hop you can help me with that issue - i'm not very common on the joomla base classes / core.

Thank you and kind regards
Greenlion

**Comment by brianteeman** [comment]
After one month with no update or confirmation I am closing this issue. If it is still an issue please provide more information.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5441">issues.joomla.org/joomla-cms/5441</a>.</sub>
