### ISSUE TITLE
return URL is not preserved after login failure page reload

### ISSUE THREAD

**Issue by rriemvis** [joomla/joomla-cms#5454]
#### Steps to reproduce the issue

Setup a site with guest and registered type of users with a standard login access on a menu item. Non-registered users should be given guest permissions.
Define a menu item that can only be accessed with registered user rights.
Try to access this menu item by providing the URL directly without being logged in.
Now the login form should appear.

Try to log in with an existing user **but wrong password**.
You should get an error message.
Now try to log in with the correct password.

#### Expected result
You are redirected to the target menu link.

#### Actual result
You are **not** redirected to the target menu link.

#### System information (as much as possible)
Joomla 2.5.19, basic setup with guest and registered users

#### Additional comments
The reason for this is that the return URL which is passed in the form as a hidden input parameter is not preserved after reloading the login page due to the login error.

**Comment by Bakual** [comment]
I'm closing this issue since Joomla 2.5 is no longer supported and thus this will not be fixed anymore.
If the issue still exists in Joomla 3.x, please open a new issue for it.
