### ISSUE TITLE
Article:: List of Tag is getting shown in auto-suggest at the time of article creation but not at the time of Edit article

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5455]
Step-1:
-Create an article & check auto-suggest there will be long list of tag, select only 1 tag (If you have created earlier , Suppose there 5 tag in the list)
-Save the article 
-Refer screenshot-Firefox-2

Step-2
-edit the same tag
-There you will see only 1 tag, which you have added earlier at the time creation, the auto-suggestion value will not be there
-Refer screenshot-Firefox-3![screen shot 2014-12-17 at 09 00 12](http://issues.joomla.org/uploads/1/9830ea9f35f37b5707722ef1299b422a.png)![screen shot 2014-12-17 at 09 00 15](http://issues.joomla.org/uploads/1/33e7bc3105582b11e6d5eb98216a72f0.png)

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/issues/5601
