### ISSUE TITLE
Incorrect cache folder size reported in Cache Manager

### ISSUE THREAD

**Issue by codealfa** [joomla/joomla-cms#5457]
#### Steps to reproduce the issue
Take note of the different folder size reported in Cache Manager. If you compare it with the folder size when viewing the actual folders with a file explorer program you'll see they're different.

#### Expected result
Folder size reported should match the folder size in a file explorer. I noticed the difference because an application I developed calculated the size of a folder of interest and it was different that that in Cache Manager but corresponded to the file explorer.

I'm using Windows 7 and PHP 5.5. I viewed the folders with Windows Explorer. Cache handler was set to 'File' at time of testing.

**Comment by brianteeman** [comment]
After over three months without response for the requested information I am closing this issue at this time. It can always be reopened if further information is provided as had been requested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5457">issues.joomla.org/joomla-cms/5457</a>.</sub>

**Comment by piotr-cz** [comment]
For me the values are correct when there are no subfolders included.

Cache component shows Number of files: 0 size: 0 when there are subfolders included in cached groups.

Subfolders get pretty convenient when working with complex extensions.

**Comment by mukul21** [comment]
Cache component shows Number of files: 0 size: 0 when there are subfolders included in cached groups. [Lyricsfed](http://www.lyricsfed.com "")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5457">issues.joomla.org/tracker/joomla-cms/5457</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@mukul21 please open a new Issue as Comments on a closed one didn't get much Notice.

[How to reporting bugs.](https://docs.joomla.org/Filing_bugs_and_issues)

**Comment by mukul21** [comment]
Cache component shows Number of files: 0 size: 0[Lyrics](http://www.lyricsfed.com "")when there are subfolders included in cached groups.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5457">issues.joomla.org/tracker/joomla-cms/5457</a>.</sub>

**Comment by mukul21** [comment]
Cache component shows Number of files: 0 size: 0[Lyrics](http://www.lyricsfed.com "")when there are subfolders included in cached groups.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5457">issues.joomla.org/tracker/joomla-cms/5457</a>.</sub>

**Comment by brianteeman** [comment]
(deleted spam)

**Comment by mukul21** [comment]
brianteeman Whoo is this mother fucker?? Remove this user from joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5457">issues.joomla.org/tracker/joomla-cms/5457</a>.</sub>
