### ISSUE TITLE
Create Article:: Cursor is not getting shown in Description Area on chrome browser

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5464]
-Go to create article view [back-end]
-Enter article title
-Click on description area
-cursor will not be seen but It allows us to write.
-Refer screenshots.

Testing Environment:
OS: Windows-7
Browser: Firefox 34.0.5

**Comment by brianteeman** [comment]
Closed as a duplicate report and resolved elsewhere<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5464">issues.joomla.org/joomla-cms/5464</a>.</sub>
