### ISSUE TITLE
Template Manager: Customise Template :: UI Issue with buttons on Safari Version 5.1.7 (7534.57.2)

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5489]
-Log into the back-end
-Go here: sitename/administrator/index.php?option=com_templates&view=template&id=504&file=aG9tZQ==
-Click on New file button
-There you will see UI issue with button in pop-up

Testing environment:
OS: Windows-7
Browser: Safari Version 5.1.7 (7534.57.2)

Thanks & Best Regards,
Aasim Ali

![screen shot 2014-12-22 at 05 54 52](http://issues.joomla.org/uploads/1/edd15996dbd259ec069fc25825d77290.png)![screen shot 2014-12-22 at 05 55 03](http://issues.joomla.org/uploads/1/16134cbdc98c74cc07985662623d4c89.png)

**Comment by brianteeman** [comment]
@bakual @Hutchy68 I think @hackwar is right on this one and we should simply update the requirements page. No poinr in supporting a dead browser and wasting time fixing issues with it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5489">issues.joomla.org/joomla-cms/5489</a>.</sub>

**Comment by brianteeman** [comment]
Changed status to needs review so that we still have it open until the PLT decides about the recommendation for changing the supported browser version as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5489">issues.joomla.org/joomla-cms/5489</a>.</sub>

**Comment by zero-24** [comment]
Closing as the doc page is updated with the following message:

`
Apple has dropped all support of MS Windows Safari starting with Safari 6. Browser compatibility with MS Windows Safari is not guaranteed. Please use a different browser or the Apple OS native Safari version. See this article for more information.
`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5489">issues.joomla.org/joomla-cms/5489</a>.</sub>
