### ISSUE TITLE
RFC - A Joomla Admin Menu Manager  

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#5492]
The Joomla admin menus are one of the few things in Joomla that you cannot truly customise. The location of the menu items is as a result of arbitrary decisions made many years ago.

### Why have all the components under one menu? 
Wouldn't you like to perhaps separate the utilities from the content creation components.

### Why is content a top level menu item?
It is just a component. I am sure the logic was that it was a component that is used so often that it deserves its own place. But what if you don't use com_content and use com_seblod - or you even have a photo gallery as your main content creating component.

Wouldn't it be great if you could build and customise the admin menu however you want? I am sure many people have had this thought as well but have you ever looked at the code that generates the menus in the Joomla admin? If you have then I am pretty sure that you will have run away scared.

> All the menu items except for the Components menu are hard coded with lots of if statements to cope with the few places that we have options.

I am proposing that we switch the entire admin menu system to be database driven and customisable via an admin menu component. Thecomponent will allow people to move menu items, create and remove top level menus etc.

### Backwards compatibility
By default without any modifications the site should look exactly the same.
The big BC issue to address is where do the menu links for NEW components that a user installs get created. The problem is that the user could have removed the "components" top level menu. I would suggest that just as we have to flag a top level menu item as default homepage in the frontend we would have to flag a top level menu item in the admin as well for the default location that new component menu items are created.

### Multilanguage issues
Unlike the frontend I would suggest that the admin menu manager can only manage ONE menu and not one per language. Instead of user created menu titles as in the front end we can continue to use the strings from the language files. This will ensure that a site with multiple admin languages installed will only need to manage one menu and that everything will be in the same place in all languages.

### Database issues
Currently the jos_extensions table contains all extensions so we would just need to update that table to contain the id for the menu link

**Comment by jrseliga** [comment]
Originally I suggested creating an entirely separate MVC to handle the administrator menu. I followed that up with scrapping the idea of an additional MVC and simply modifying the current.

I was able to get a elementary version of the latter working, but realized potential problems from an administrative perspective. Taking a step back, I approached the problem with the former in mind (creating an entirely new MVC for the administator menu), and after getting a similarly basic version working realized that too introduces it's own set of problems.

I'm going to return to approaching the problem from the "modify the current MVC" perspective.
- Creating an additional MVC is wasteful when accounting for maintenance. In reality it would be a one-to-one copy of the current MVC files in com_menus with a small number of modifications. Why manage almost identical code twice?
- The only difference between a site menu and administrator menu would be a single column (client_id) in the database. As a result displaying site or administrator menus is best handled with a simple filter.

I'll try and push an early stage alpha branch within the next few days. I will list the most glaring issues here that prevent it from even being labelled "beta" with the hope that it will be a foundation or catalyst for others to provide perspective and assistance.

**Comment by brianteeman** [comment]
Awesome - really looking forward to trying it out and to "make it happen®"

On 3 January 2015 at 18:44, Justin Seliga <notifications@github.com> wrote:

> Originally I suggested creating an entirely separate MVC to handle the
> administrator menu. I followed that up with scrapping the idea of an
> additional MVC and simply modifying the current.
>
> I was able to get a elementary version of the latter working, but realized
> potential problems from an administrative perspective. Taking a step back,
> I approached the problem with the former in mind (creating an entirely new
> MVC for the administator menu), and after getting a similarly basic version
> working realized that too introduces it's own set of problems.
>
> I'm going to return to approaching the problem from the "modify the
> current MVC" perspective.
>
>    - Creating an additional MVC is wasteful when accounting for
>    maintenance. In reality it would be a one-to-one copy of the current MVC
>    files in com_menus with a small number of modifications. Why manage almost
>    identical code twice?
>    - The only difference between a site menu and administrator menu would
>    be a single column (client_id) in the database. As a result displaying site
>    or administrator menus is best handled with a simple filter.
>
> I'll try and push an early stage alpha branch within the next few days. I
> will list the most glaring issues here that prevent it from even being
> labelled "beta" with the hope that it will be a foundation or catalyst for
> others to provide perspective and assistance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5492#issuecomment-68604882>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
See also https://github.com/joomla/joomla-cms/issues/5131#issuecomment-69486166

**Comment by bluezeyes** [comment]
That sounds really interesting!
Based on still existing com_menu with just a flag adminmenu :-)

Just one question why not indicating with a second flag, let's say fff to make it possible for using in frontend too?
With a little component for com_menu looking for that flag to add it to an existing frontend menu, 
For users who are allowed to access the backend.

The visible admin menu items in frontend would be still based on the acl they belong to,  the designated user have an admian(sub)menu with shortcuts to the components he is allowed to access. 
And for customization the Administrator / super user can steer if an backend menu item is additionally visible for a user group in front end or not. 
For the security aspect there would be still the backend authentication w /wo TFA, etc. 

Just my 2c

**Comment by brianteeman** [comment]
@jrseliga did you ever manage to push something to review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5492">issues.joomla.org/joomla-cms/5492</a>.</sub>

**Comment by parthlawate** [comment]
I'm assuming there has been no action on this ? I'm planning to get this done & will submit a PR

**Comment by brianteeman** [comment]
GREAT!!!!

On 3 March 2016 at 11:26, Parth Lawate <notifications@github.com> wrote:

> I'm assuming there has been no action on this ? I'm planning to get this
> done & will submit a PR
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5492#issuecomment-191717311>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by puneet0191** [comment]
@parthlawate Could you please share your work on this, as we have added this suggestion as one of the project idea's for GSoC https://docs.joomla.org/GSOC_2016_Project_Ideas#Project_III:_Administrator_Menu_Editor

One of the student has started preparing proposal around this, if you could help, it would be great. Just join our GSoC Group to take part in the conversation https://groups.google.com/forum/?hl=en#!forum/jgsoc-2016

Regards,
Puneet Kala<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5492">issues.joomla.org/joomla-cms/5492</a>.</sub>

**Comment by parthlawate** [comment]
@puneet0191 Yes @coolbung showed me that. I need to do this anyways for some work stuff so need to do it quickly maybe in the like the next 6 weeks or so. Not sure if via GSOC it will go that fast ? I will ask @coolbung to talk to you see how we can coordinate !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5492">issues.joomla.org/joomla-cms/5492</a>.</sub>

**Comment by puneet0191** [comment]
@parthlawate Actual coding doesn't start on this until 23rd April, so more than 6 weeks before we have someone working on this. https://developers.google.com/open-source/gsoc/timeline?hl=en

We need to make a decision on this project soon, if you are going to cover complete scope of the suggestion than according to me it makes no sense to have the project on the Idea's list. @coolbung Please let me know about this soon. 

Regards,
Puneet Kala<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5492">issues.joomla.org/joomla-cms/5492</a>.</sub>

**Comment by parthlawate** [comment]
Oh ok.. in that case let me see if i can schedule this part for later so that we can still have it as a GSOC project. We are preparing a document which builds on this RFC to detail how it all needs to work. Let me ask @coolbung to share that with you. Based on that you can discuss if GSOC plans for that entire scope or part of it. If its part of it, we can take up the GSOC code and add to it to complete the same. I can also have someone from our team help mentoring this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5492">issues.joomla.org/joomla-cms/5492</a>.</sub>

**Comment by flash1452** [comment]
@parthlawate 
Hey,
I am looking forward to work on this project in GSoC 2016 and i have been advised by one of the mentors to get some information on what changes exactly is required under this project.If you can give some feedback on the modifications to be done in the Joomla administrator menu,it would be of great help.
Also i would like to si=uggest some of my own modifications.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5492">issues.joomla.org/joomla-cms/5492</a>.</sub>

**Comment by puneet0191** [comment]
@parthlawate Do you have any update on this please? student has started preparing the draft proposal, it will be very helpful if you could share details. @coolbung Do you have any thing on this? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5492">issues.joomla.org/joomla-cms/5492</a>.</sub>
