### ISSUE TITLE
Parameters Functions

### ISSUE THREAD

**Issue by configzone** [joomla/joomla-cms#5506]
#### Steps to reproduce the issue
After install/updating Joomla latest version (3.3.6) system will able to open Parameters section however it not able to save/save and close/cancel functions after updating any of settings in components and inbuilt configs.

#### Expected result

buttons should work after clicking on.

**Comment by brianteeman** [comment]
After 3 weeks with no further update I am closing this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5506">issues.joomla.org/joomla-cms/5506</a>.</sub>
