### ISSUE TITLE
Menu Manager - Select Article display needs "Display All" etc

### ISSUE THREAD

**Issue by rowby** [joomla/joomla-cms#5529]
#### Steps to reproduce the issue

Go to Joomla Menu Manager.  Under Details Tab select Menu Item Type.  Select Single Article (or similar article selection)  Then back in Menu Manager "Select Article".  You are then given a list of articles, which you can filter by Category, Status, etc.  However it only displays a few of the filtered results.  

My suggestion is, like the article manager, the user should be able to select from a dropdown the number of items to be displayed, i.e. 25, 50, 75 100 or All."

#### Expected result

The expected result limits the user to approx 25 items.

#### Actual result

The expected result limites the user to approx 25 items.

#### System information (as much as possible)

Joomla standard installation.  Joomla 3.6.3.

#### Additional comments

Just like the article manager, the Menu manager should allow the user to select whether they want to display all or just a few.  This is particularly helpful when there are a large amount of articles, and the user wants to see them ALL at once (or 100 at once, for example) rather than just a few (25) items.

Don't know if this is a "bug" or a feature enhancement request.  Not sure where to put feature enhancement requests, so if this is the wrong place for that please let me know where to repost this. 

Thanks

Rowby

**Comment by GunnarBs** [comment]
I do not see the issue. You are presented with 25 articles and a pagination. you can search for text strings and filter by different. How many menu items are you creating?

If you do not find your article, open a second browser window and go into the article screen there where you can display more and sort. Should be easy to just filter by a few characters to type.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5529">issues.joomla.org/joomla-cms/5529</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this as the expected behaviour. It would not be practical to display an unlimited list in a fixed size modal window. If someone wants to submit a PR then it can always be tested but and reconsidered<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5529">issues.joomla.org/joomla-cms/5529</a>.</sub>

**Comment by rummybocom** [comment]
[wingo]( https://rummybo.com/ "wingo")
[wingo casino]( https://rummybo.com/blog/53.html "wingo casino")
[wingo 2]( https://rummybo.com/blog/54.html "wingo 2")
[wingo](https://indiakashrummy.com "wingo")
[wingo casino](https://indiawinzogames.com "wingo casino")
[wingo 2](https://india-rummy-nabob.com "wingo 2")
[rummy circle](https://indiarummyplusgame.in "rummy circle")
[rummy](https://india-playship.com "rummy")
[rummy wealth](https://india-cardbaazi.com "rummy wealth")
[rummy nabob](https://india-rummy-titans.com "rummy nabob")
[rummy glee](https://india-rummy-pro.com "rummy glee")
[rummy gold](https://indiakhelplay.com "rummy gold")
[rummy modern](https://indiabigcash.live "rummy modern")
[junglee rummy](https://indiampl.live "junglee rummy")
[holy rummy](https://india-rummy-verse.com "holy rummy")
[rummy east](https://india-kick-rummy.com "rummy east")
[rummy ola](https://indiakickrummy.com "rummy ola")
[rummy ares](https://india-a23-rummy.com "rummy ares")
[royally rummy](https://india-poki.com "royally rummy")
[rummy culture](https://india-rummy-cue.com "rummy culture")
[rummy noble](https://indiaearnkaro.com "rummy noble")
[rummy joy](https://india-a23.com "rummy joy")
[rummy mate](https://indiaa23rummy.com "rummy mate")
[rummy perfect](https://india-rummy-circle.in "rummy perfect")
[all rummy app](https://indiatajrummy.com "all rummy app")
[rummy meet](https://india-rummy-culture.com "rummy meet")
[yono rummy](https://india-coolold-games.com "yono rummy")
[rummy 51 bonus](https://indiarummynabob.com "rummy 51 bonus")
[rummy time](https://india-rummy-most.com "rummy time")
[rummy star](https://indiaonlinerummy.com "rummy star")
[rummy yes](https://indiarummycircle.in "rummy yes")
[rummy golds](https://india-earnkaro.com "rummy golds")
[rummy loot](https://indiadangalgames.com "rummy loot")
[rummy game](https://indiarummytitans.com "rummy game")
[rummy holy](https://india-rummy-plusgame.in "rummy holy")
[rummy gold apk](https://indiarummyplus.com "rummy gold apk")
[rummy all app](https://india-rrummy.com "rummy all app")
[rummy app](https://indiarummymost.com "rummy app")
[a23 rummy](https://india-silk-rummy.com "a23 rummy")
[rummy best](https://india-adda52-rummy.com "rummy best")
[royal rummy](https://indiarummyprime.com "royal rummy")
[rummy royally](https://indiarummywealth.com "rummy royally")
[rummy circle app download](https://indiasilkrummy.com "rummy circle app download")
[rummy satta](https://indiaadda52rummy.com "rummy satta")
[vip rummy](https://india-junglee-rummy.com "vip rummy")
[rummy vip](https://indiafirstgames.in "rummy vip")
[rummy modern apk](https://indiaace2three.com "rummy modern apk")
[joy rummy](https://india-mpl-rummy.com "joy rummy")
[all rummy app list](https://indiarummyverse.com "all rummy app list")
[top 20 rummy 51 bonus](https://indiaplayship.com "top 20 rummy 51 bonus")
[rummy mars](https://india-deccan-rummy.com "rummy mars")
[rummy most](https://indiajungleerummy.com "rummy most")
[rummy apk](https://india-rummy-passion.com "rummy apk")
[rummy deity](https://india-bigcash.live "rummy deity")
[online rummy](https://indiampllive.com "online rummy")
[rummy tour](https://indiadeccanrummy.com "rummy tour")
[holy rummy apk](https://india-winzogames.com "holy rummy apk")
[all rummy app list 51 bonus](https://india-classic-rummy.com "all rummy app list 51 bonus")
[rummy rules](https://indiarummyglee.com "rummy rules")
[ek rummy](https://indiarummybaazi.com "ek rummy")
[rummy master](https://india-rummy-wealth.com "rummy master")
[rummy wealth apk](https://mpl-live.com "rummy wealth apk")
[rummy meta](https://indiampl.in "rummy meta")
[rummy all](https://india-rummy-prime.com "rummy all")
[rummy passion](https://india-9apps.com "rummy passion")
[new rummy app 2023 51 bonus](https://india-gamezy.com "new rummy app 2023 51 bonus")
[rummy leader](https://india-getmega.com "rummy leader")
[rummy star apk](https://indiaclassicrummy.com "rummy star apk")
[rummy circle download](https://india-kash-rummy.com "rummy circle download")
[rummy rani](https://india-rummy-time.com "rummy rani")
[rummy list](https://india-ace2three.com "rummy list")
[rummy online](https://india-player-zpot.com "rummy online")
[rummy model](https://indiacoololdgames.com "rummy model")
[rummy royal](https://indiaplayrummy.com "rummy royal")
[rummy circle app](https://indiakhelplayrummy.com "rummy circle app")
[rummy club](https://indiacardbaazi.com "rummy club")
[rummy bloc](https://indiarummyculture.com "rummy bloc")
[rummy circle apk](https://india-khelplay-rummy.com "rummy circle apk")
[hello rummy](https://india-rummy-glee.com "hello rummy")
[all rummy](https://indiapoki.com "all rummy")
[rummy ola apk](https://india-dangal-games.com "rummy ola apk")
[rummy nabob apk](https://india-classi-crummy.com "rummy nabob apk")
[rummy circle login](https://indiagetmega.com "rummy circle login")
[rummy 51 apk](https://indiajungleerummy.in "rummy 51 apk")
[deccan rummy](https://indiahowzat.com "deccan rummy")
[rummy go](https://india-play-rummy.com "rummy go")
[color rummy](https://indiagamezy.com "color rummy")
[new rummy app](https://indiaa23.com "new rummy app")
[rummy all list](https://indiarummycue.com "rummy all list")
[yono rummy apk](https://india9apps.com "yono rummy apk")
[rummy glee max](https://indiarrummy.com "rummy glee max")
[rummy ares apk](https://indiarummytime.com "rummy ares apk")
[rummy moment](https://indiaplayerzpot.com "rummy moment")
[modern rummy](https://india-rummy-plus.com "modern rummy")
[rummy app download](https://india-online-rummy.com "rummy app download")
[rummy download](https://india-firstgames.in "rummy download")
[indian rummy](https://india-taj-rummy.com "indian rummy")
[g rummy](https://india-howzat.com "g rummy")
[rummy east apk](https://indiarummypassion.com "rummy east apk")
[rummy blast](https://india-khelplay.com "rummy blast")
[holi rummy](https://indiarummyapp.com "holi rummy")
[rummy game download](https://indiarummybo.in "rummy game download")
[111 rummy 51 bonus](https://indiarummybo.com "111 rummy 51 bonus")
[bappa rummy](https://indiagameapps.com "bappa rummy")
[rummy gold 51](https://indiaallrummy.com "rummy gold 51")
[rummy bindaas](https://indiarummytop.com "rummy bindaas")
[rummy grand](https://indiarummyall.com "rummy grand")
[rummy mate apk](https://indiarummyapps.com "rummy mate apk")
[classic rummy](https://indiarummyapk.in "classic rummy")
[rummy league](https://indiarummyapk.com "rummy league")
[colour rummy](https://indiaallrummy.in "colour rummy")
[rummy cafe](https://india-rummy-baazi.com "rummy cafe")
[rummy holi](https://indiarummyapp.in "rummy holi")
[how to play rummy](https://7up-cards-down.com "how to play rummy")
[rummy gold - indian](https://rummy-rain.in "rummy gold - indian")
[rummy golds apk](https://rummycards7.com "rummy golds apk")
[rummy bonus 51 rupees free](https://gamescardss.com "rummy bonus 51 rupees free")
[rainbow rummy](https://7up-cards-down.in "rainbow rummy")
[rummy morden](https://rummy-rain.com "rummy morden")
[ultimate rummy](https://mad-cards.com "ultimate rummy")
[rummy games](https://7up-cards-up.in "rummy games")
[all rummy game](https://mad-cards.in "all rummy game")
[rummy bonus](https://7up-cards-up.com "rummy bonus")
[play rummy](https://rummy-up.in "play rummy")
[best rummy app](https://rummycards-up.in "best rummy app")
[rummy yes apk](https://play-cards.in "rummy yes apk")
[wow rummy](https://mad-rummy.com "wow rummy")
[rummy palace](https://mad-rummy.in "rummy palace")
[rummy glee apk](https://cardsplay-3.in "rummy glee apk")
[rummy glee 51 bonus](https://pokerup-play.com "rummy glee 51 bonus")
[rummy apps](https://pokerup-play.in "rummy apps")
[rummy glee 51](https://rummycards-up.com "rummy glee 51")
[rummy culture download](https://rummy-up.com "rummy culture download")
[rummy nobob](https://cardsplay-3.com "rummy nobob")
[rummy teen patti](https://rummycards7.in "rummy teen patti")
[rummy 100 rupees free](https://dragon-play.in "rummy 100 rupees free")
[holly rummy](https://gamescardss.in "holly rummy")
[rummy all app list](https://rummywager.com "rummy all app list")
[teen patti rummy](https://cardscharm.com "teen patti rummy")
[rummy circle customer care number](https://rummyfeverfun.com "rummy circle customer care number")
[rummy app list](https://rummytango.com "rummy app list")
[royally rummy apk](https://rummyforte.com "royally rummy apk")
[mpl rummy](https://rummyrevive.com "mpl rummy")
[all rummy app list 41 bonus](https://pureplayrummy.com "all rummy app list 41 bonus")
[rummy meet apk](https://rummywager.in "rummy meet apk")
[rummy noble apk](https://cardscharm.in "rummy noble apk")
[rummy nobel](https://rummyfeverfun.in "rummy nobel")
[rummy time download](https://rummytango.in "rummy time download")
[rummy loot apk](https://rummyforte.in "rummy loot apk")
[rummy joy apk](https://rummyrevive.in "rummy joy apk")
[royal rummy apk](https://pureplayrummy.in "royal rummy apk")
[rummy pro](https://rummyrave.com "rummy pro")
[rummy gold -](https://rummyzoom.com "rummy gold -")
[rummy gold download](https://cardspyre.com "rummy gold download")
[playship rummy](https://glidegamble.com "playship rummy")
[rummy welth](https://rummyrave.in "rummy welth")
[rummy buddy](https://rummyzoom.in "rummy buddy")
[rummy gold apk download](https://cardspyre.in "rummy gold apk download")
[rummy wealth yes](https://glidegamble.in "rummy wealth yes")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5529">issues.joomla.org/tracker/joomla-cms/5529</a>.</sub>
