### ISSUE TITLE
JCategories::getChildren invalid behaviour

### ISSUE THREAD

**Issue by berserkerx** [joomla/joomla-cms#5530]
#### Steps to reproduce the issue
Create test site with 3 categories. Call JCategories::getInstance('Content')->get('root')->getChildren(true);

#### Expected result
Array of 3 categories.

#### Actual result
Array of single category item.

#### System information (as much as possible)
OpenServer, PHP 5.4, Joomla 3.3.6.

#### Additional comments

**Comment by zero-24** [comment]
Closing as we have a merged PR that should fix the issue see #6440

**Comment by rummybocom** [comment]
[wingo](https://blackjack-rummy.net "wingo")
[wingo casino](https://blackjack-rummy.com "wingo casino")
[wingo 2](https://rocket-league-app.in "wingo 2")
[rummy circle](https://dragon-tiger-casino.in "rummy circle")
[rummy](https://crash-game-online.in "rummy")
[rummy wealth](https://dragon-tiger-download.in "rummy wealth")
[rummy nabob](https://dragon-vs-tiger-ame.in "rummy nabob")
[rummy glee](https://dragon-vs-tiger-casino.in "rummy glee")
[rummy gold](https://rocket-league.in "rummy gold")
[rummy modern](https://rocketleague-login.in "rummy modern")
[junglee rummy](https://blackjack-21.in "junglee rummy")
[holy rummy](https://blackjack-free.in "holy rummy")
[rummy east](https://rocket-league-download.in "rummy east")
[rummy ola](https://rocketleague-apk.in "rummy ola")
[rummy ares](https://rocketleague-online.in "rummy ares")
[royally rummy](https://dragon-vs-tiger-tricks.in "royally rummy")
[rummy culture](https://crash-game.in "rummy culture")
[rummy noble](https://dragon-vs-tiger-app.in "rummy noble")
[rummy joy](https://crash-bandicoot.in "rummy joy")
[rummy mate](https://crash-play.in "rummy mate")
[rummy perfect](https://blackjack-download.in "rummy perfect")
[all rummy app](https://crash-free.in "all rummy app")
[rummy meet](https://blackjack-online.in "rummy meet")
[yono rummy](https://rocketleague-app.in "yono rummy")
[rummy 51 bonus](https://rocketleague-download.in "rummy 51 bonus")
[rummy time](https://blackjack-play.in "rummy time")
[rummy star](https://rocketleague-free.in "rummy star")
[rummy yes](https://rocket-league-play.in "rummy yes")
[rummy golds](https://dragon-tiger-live.in "rummy golds")
[rummy loot](https://dragon-vs-tiger-rummy.in "rummy loot")
[rummy game](https://dragon-tiger--app.in "rummy game")
[rummy holy](https://rocket-league-free.in "rummy holy")
[rummy gold apk](https://rocketleague-game.in "rummy gold apk")
[rummy all app](https://dragon-tiger-online.in "rummy all app")
[rummy app](https://dragon-vs-tiger-slots.in "rummy app")
[a23 rummy](https://rocketleague-play.in "a23 rummy")
[rummy best](https://dragon-tiger-777.in "rummy best")
[royal rummy](https://dragon-vs-tiger-apk.in "royal rummy")
[rummy royally](https://blackjack-rummy.in "rummy royally")
[rummy circle app download](https://crash-online.in "rummy circle app download")
[rummy satta](https://dragon-tiger-rummy.in "rummy satta")
[vip rummy](https://blackjack-casino.in "vip rummy")
[rummy vip](https://dragon-tiger-slots.in "rummy vip")
[rummy modern apk](https://crash-bandicoot-games.in "rummy modern apk")
[joy rummy](https://crash-casino.in "joy rummy")
[all rummy app list](https://blackjack-poker.in "all rummy app list")
[top 20 rummy 51 bonus](https://dragon-vs-tiger-tricks.com "top 20 rummy 51 bonus")
[rummy mars](https://dragon-vs-tiger-casino.com "rummy mars")
[rummy most](https://dragon-vs-tiger-app.com "rummy most")
[rummy apk](https://dragon-vs-tiger-rummy.com "rummy apk")
[rummy deity](https://dragon-vs-tiger-slots.com "rummy deity")
[online rummy](https://7up-down-game.com "online rummy")
[rummy tour](https://black-jack-rummy.net "rummy tour")
[holy rummy apk](https://black-jack-play.net "holy rummy apk")
[all rummy app list 51 bonus](https://black-jack-play.com "all rummy app list 51 bonus")
[rummy rules](https://7up-down-rummy.com "rummy rules")
[ek rummy](https://black-jack-rummy.com "ek rummy")
[rummy master](https://black-jack-download.com "rummy master")
[rummy wealth apk](https://black-jack-slots.com "rummy wealth apk")
[rummy meta](https://7up-down-rummy.net "rummy meta")
[rummy all](https://7up-down-free.com "rummy all")
[rummy passion](https://black-jack-game.com "rummy passion")
[new rummy app 2023 51 bonus](https://7up-down.net "new rummy app 2023 51 bonus")
[rummy leader](https://black-jack-777.com "rummy leader")
[rummy star apk](https://7updown-poker.com "rummy star apk")
[rummy circle download](https://7up-7-down.net "rummy circle download")
[rummy rani](https://7updown-poker.net "rummy rani")
[rummy list](https://7updown-app.com "rummy list")
[rummy online](https://7updown-download.com "rummy online")
[rummy model](https://7updown-apk.net "rummy model")
[rummy royal](https://7up-7-down-game.com "rummy royal")
[rummy circle app](https://7up-7-down.com "rummy circle app")
[rummy club](https://7up-7-down-free.com "rummy club")
[rummy bloc](https://7updown-apk.com "rummy bloc")
[rummy circle apk](https://7updown-trick.com "rummy circle apk")
[hello rummy](https://7updown-app.net "hello rummy")
[all rummy](https://7updown-download.net "all rummy")
[rummy ola apk](https://7updown-dome.com "rummy ola apk")
[rummy nabob apk](https://7updown-trick.net "rummy nabob apk")
[rummy circle login](https://7up-7-down-poker.com "rummy circle login")
[rummy 51 apk](https://7up-7-down-free.net "rummy 51 apk")
[deccan rummy](https://7up-7-down-play.net "deccan rummy")
[rummy go](https://7up-7-down-game.net "rummy go")
[color rummy](https://7up-7-down-trick.com "color rummy")
[new rummy app](https://7up-7-down-dome.com "new rummy app")
[rummy all list](https://7up-7-down-trick.net "rummy all list")
[yono rummy apk](https://7up-down-play.com "yono rummy apk")
[rummy glee max](https://7up-down-trick.com "rummy glee max")
[rummy ares apk](https://7up-down-dome.com "rummy ares apk")
[rummy moment](https://7up-down-apk.com "rummy moment")
[modern rummy](https://7up-down-app.com "modern rummy")
[rummy app download](https://7up-7-down-free.in "rummy app download")
[rummy download](https://rocket-league-free.com "rummy download")
[indian rummy](https://rocketleague-play.com "indian rummy")
[g rummy](https://rocketleague-site.com "g rummy")
[rummy east apk](https://rocket-league-site.com "rummy east apk")
[rummy blast](https://rocket-league-app.com "rummy blast")
[holi rummy](https://rocket-league-play.com "holi rummy")
[rummy game download](https://dragon-tiger-777.com "rummy game download")
[111 rummy 51 bonus](https://dragon-vs-tiger-apk.net "111 rummy 51 bonus")
[bappa rummy](https://dragon-tiger-game.net "bappa rummy")
[rummy gold 51](https://dragon-tiger-rummy.net "rummy gold 51")
[rummy bindaas](https://dragon-tiger-rummy.com "rummy bindaas")
[rummy grand](https://dragon-tiger-online.com "rummy grand")
[rummy mate apk](https://crash-online.net "rummy mate apk")
[classic rummy](https://rocketleague-game.net "classic rummy")
[rummy league](https://7up-down-apk.in "rummy league")
[colour rummy](https://7up-down-app.in "colour rummy")
[rummy cafe](https://7up-7-down-trick.in "rummy cafe")
[rummy holi](https://7up-7-down-poker.in "rummy holi")
[how to play rummy](https://rocketleague-login.com "how to play rummy")
[rummy gold - indian](https://7updown.net "rummy gold - indian")
[rummy golds apk](https://7updown-free.com "rummy golds apk")
[rummy bonus 51 rupees free](https://7updown-game.com "rummy bonus 51 rupees free")
[rainbow rummy](https://7up-down-trick.in "rainbow rummy")
[rummy morden](https://7up-down.in "rummy morden")
[ultimate rummy](https://7up-7-down.in "ultimate rummy")
[rummy games](https://7up-7-down-app.in "rummy games")
[all rummy game](https://7up-down-download.in "all rummy game")
[rummy bonus](https://7up-7-down-download.in "rummy bonus")
[play rummy](https://7up-7-down-game.in "play rummy")
[best rummy app](https://7up-7-down-play.in "best rummy app")
[rummy yes apk](https://7up-down-rummy.in "rummy yes apk")
[wow rummy](https://7up-down-play.in "wow rummy")
[rummy palace](https://7up-down-dome.in "rummy palace")
[rummy glee apk](https://7up-down-poker.in "rummy glee apk")
[rummy glee 51 bonus](https://7up-down-game.in "rummy glee 51 bonus")
[rummy apps](https://7up-down-free.in "rummy apps")
[rummy glee 51](https://7up-7-down-dome.in "rummy glee 51")
[rummy culture download](https://blackjack-download.com "rummy culture download")
[rummy nobob](https://blackjack-poker.net "rummy nobob")
[rummy teen patti](https://blackjack-play.net "rummy teen patti")
[rummy 100 rupees free](https://7updown-play.com "rummy 100 rupees free")
[holly rummy](https://7updown.online "holly rummy")
[rummy all app list](https://7updown-free.net "rummy all app list")
[teen patti rummy](https://7updown-game.net "teen patti rummy")
[rummy circle customer care number](https://crash-play.com "rummy circle customer care number")
[rummy app list](https://crash-play.net "rummy app list")
[royally rummy apk](https://7updown-download.in "royally rummy apk")
[mpl rummy](https://7updown-play.net "mpl rummy")
[all rummy app list 41 bonus](https://7updown-play.in "all rummy app list 41 bonus")
[rummy meet apk](https://black-jack-online.in "rummy meet apk")
[rummy noble apk](https://7updown-game.in "rummy noble apk")
[rummy nobel](https://black-jack-play.in "rummy nobel")
[rummy time download](https://black-jack-download.in "rummy time download")
[rummy loot apk](https://crash-game-online.com "rummy loot apk")
[rummy joy apk](https://black-jack-casino.in "rummy joy apk")
[royal rummy apk](https://7updown-app.in "royal rummy apk")
[rummy pro](https://7updown-dome.in "rummy pro")
[rummy gold -](https://7updown-poker.in "rummy gold -")
[rummy gold download](https://dragon-tiger-slots.com "rummy gold download")
[playship rummy](https://rocketleague-app.net "playship rummy")
[rummy welth](https://rocketleague-free.net "rummy welth")
[rummy buddy](https://rocketleague-free.com "rummy buddy")
[rummy gold apk download](https://rocketleague-apk.com "rummy gold apk download")
[rummy wealth yes](https://rocketleague-app.com "rummy wealth yes")
[new gold rummy](https://rocketleague-game.com "new gold rummy")
[rummy nabob 777](https://rocketleague-apk.net "rummy nabob 777")
[rummy culture app](https://dragon-tiger-live.com "rummy culture app")
[rummy sun 51 bonus](https://7up-7-down-apk.in "rummy sun 51 bonus")
[rummy wealth 51 bonus](https://blackjack-free.com "rummy wealth 51 bonus")
[rummy all apk](https://blackjack-free.net "rummy all apk")
[a23 rummy download](https://dragon-tiger-777.net "a23 rummy download")
[rummy cash game](https://7up-down-poker.com "rummy cash game")
[rummy king](https://7up-7-down-apk.com "rummy king")
[rummy joy 51 bonus](https://crash-free.com "rummy joy 51 bonus")
[rummy circle game](https://7up-7-down-app.net "rummy circle game")
[rummy rummy](https://crash-casino.site "rummy rummy")
[rummy culture apk](https://7up-7-down-poker.site "rummy culture apk")
[rummy gold 100](https://crash-bandicoot.site "rummy gold 100")
[gold rummy](https://crash-free.site "gold rummy")
[rummy teen patti joy](https://7up-7-down-apk.net "rummy teen patti joy")
[culture rummy](https://crash-free.net "culture rummy")
[rummy prime](https://7up-7-down-app.com "rummy prime")
[dash rummy](https://crash-bandicoot.net "dash rummy")
[rummy star 41 bonus](https://7updown-free.in "rummy star 41 bonus")
[rummy online cash game app download](https://7updown-trick.in "rummy online cash game app download")
[lucky rummy](https://black-jack-777.in "lucky rummy")
[rummy try](https://7updown-apk.in "rummy try")
[rummy arena](https://black-jack-21.in "rummy arena")
[new rummy app 2023](https://black-jack-rummy.in "new rummy app 2023")
[rummy gold 2](https://black-jack-slots.in "rummy gold 2")
[51 bonus rummy](https://7updown.in "51 bonus rummy")
[rummy sarkal](https://black-jack-game.in "rummy sarkal")
[rummy circle online](https://rummy-card.in "rummy circle online")
[rummy rainbow](https://rummyfree.in "rummy rainbow")
[rummy wake](https://rummy-games.in "rummy wake")
[7 rummy](https://rummy-cash.com "7 rummy")
[rummy money](https://rummy-free.in "rummy money")
[jungle rummy](https://rummy-play.com "jungle rummy")
[rummy ares 2](https://rummy-rum.com "rummy ares 2")
[9 rummy](https://rummy-rum.in "9 rummy")
[real rummy](https://junglee-rummy.com "real rummy")
[rummy bonus 51](https://jungleerummy-games.in "rummy bonus 51")
[rummy culture app download](https://junglee-rummy-cards.in "rummy culture app download")
[rummy sarkar](https://jungleerummy-login.in "rummy sarkar")
[rummy modern apk download](https://rummy-download.in "rummy modern apk download")
[rummy sun 51 bonus download](https://jungleerummy-free.com "rummy sun 51 bonus download")
[rummy 51](https://rummy-play.in "rummy 51")
[rummy best apk](https://rummy-500.in "rummy best apk")
[rummy all game](https://junglee-rummy-21.in "rummy all game")
[rummy gilli](https://jungleerummy-download.in "rummy gilli")
[rummy bhai](https://junglee-rummy-cards.com "rummy bhai")
[rummy blast world](https://jungleerummy-login.com "rummy blast world")
[rummy modern king](https://rummy-free.com "rummy modern king")
[rummy 75 bonus](https://jungleerummy-app.com "rummy 75 bonus")
[rummy 51 bonus list](https://jungleerummy-download.com "rummy 51 bonus list")
[rummy dhan](https://jungleerummy21.com "rummy dhan")
[rummy wealth apk download](https://jungleerummy-games.com "rummy wealth apk download")
[rummy modern pro](https://junglee-rummy-21.com "rummy modern pro")
[play rummy online real money](https://jungleerummy-free.in "play rummy online real money")
[rummy apna](https://rummy-cash.in "rummy apna")
[rummy gold - downloadable content](https://jungleerummy21.in "rummy gold - downloadable content")
[rummy vs](https://jungleerummy-app.in "rummy vs")
[rum rummy](https://newrummyapp.io "rum rummy")
[rummy guru](https://newrummyapplist.io   "rummy guru")
[rummy holy apk](https://todaynewrummyapplist.com "rummy holy apk")
[rummy star gold](https://dragonvstiger.io "rummy star gold")
[rummy time app](https://dragonvstigergame.in "rummy time app")
[rummy wealth 999](https://rummygame.io "rummy wealth 999")
[junglee rummy circle](https://webplayrummy.com "junglee rummy circle")
[rummy noob](https://swiftrummy.com "rummy noob")
[rummy old](https://rummywebplay.in "rummy old")
[indifun rummy](https://rummyweb.in "indifun rummy")
[glee rummy](https://swiftrummy.in "glee rummy")
[my 11 circle rummy](https://webplayrummy.in "my 11 circle rummy")
[rummy sets](https://rummyvibe.in "rummy sets")
[online rummy game](https://rummyvibe.com "online rummy game")
[holy rummy apk download](https://crazerummy.in "holy rummy apk download")
[rummy meat](https://rummyrise.in "rummy meat")
[rummy game list](https://CrazRummy.in "rummy game list")
[rummy gold plus](https://CrazRummy.com "rummy gold plus")
[rummy apk download](https://RummyCraz.com "rummy apk download")
[rummy best app](https://RummyCraz.in "rummy best app")
[rummy joy gold](https://fbrummy.com "rummy joy gold")
[rummy ninja](https://fbrummy.in "rummy ninja")
[perfect rummy](https://kurummy.com "perfect rummy")
[best online rummy cash games](https://kurummy.in "best online rummy cash games")
[rummy earn](https://lmrummy.com "rummy earn")
[rummy world](https://lmrummy.in "rummy world")
[junglee rummy login](https://oxteenpatti.com "junglee rummy login")
[rummy gogo](https://pattiapk.com "rummy gogo")
[rummy nabob all game](https://realmoneyrummy.com "rummy nabob all game")
[rummy areas](https://rummyfb.com "rummy areas")
[rummy mat](https://rummyfb.in "rummy mat")
[rummy bonus 50 rupees free](https://rummyku.com "rummy bonus 50 rupees free")
[rummy gold real cash](https://rummyku.in "rummy gold real cash")
[junglee rummy app](https://rummyusd.com "junglee rummy app")
[junglee rummy download](https://rummywu.com "junglee rummy download")
[rummy good](https://rummywu.in "rummy good")
[new rummy](https://teenpattibo.com "new rummy")
[go rummy](https://teenpattiox.com "go rummy")
[rummy time apk](https://travelrummy.com "rummy time apk")
[rummy nabob 51 bonus](https://wurummy.com "rummy nabob 51 bonus")
[new rummy app 51 bonus](https://wurummy.in "new rummy app 51 bonus")
[rummy all games](https://rummy25.com "rummy all games")
[holy rummy 51](https://rummy26.com "holy rummy 51")
[rummy circle 24x7](https://rummy27.com "rummy circle 24x7")
[rummy satta 51 bonus](https://rummy34.com "rummy satta 51 bonus")
[ares rummy](https://rummy35.com "ares rummy")
[rummy baaz](https://rummy36.com "rummy baaz")
[rummy new app](https://rummy37.com "rummy new app")
[rummy gold pro](https://rummy45.com "rummy gold pro")
[rummy calchar](https://rummy46.com "rummy calchar")
[rummy 41 bonus](https://rummy47.com "rummy 41 bonus")
[rummy ares login](https://rummy53.com "rummy ares login")
[rummy cash](https://rummy54.com "rummy cash")
[rummy cards](https://rummy56.com "rummy cards")
[cash rummy](https://rummy57.com "cash rummy")
[roz rummy](https://rummy62.com "roz rummy")
[rummy 50 bonus](https://rummy63.com "rummy 50 bonus")
[rummy nabob apk download](https://rummy64.com "rummy nabob apk download")
[rummy baba](https://rummy65.com "rummy baba")
[rummy block](https://rummy67.com "rummy block")
[new rummy app 2024 51 bonus](https://rummy71.com "new rummy app 2024 51 bonus")
[top rummy apps](https://rummy72.com "top rummy apps")
[rummy bo](https://rummy73.com "rummy bo")
[online rummy free](https://rummy74.com "online rummy free")
[rummy est](https://rummy75.com "rummy est")
[r rummy](https://rummy76.com "r rummy")
[rummy modren](https://rummy92.com "rummy modren")
[rummy hobi 51 bonus](https://rummy93.com "rummy hobi 51 bonus")
[rummy account](https://rummy94.com "rummy account")
[rummy ares apk download](https://rummy97.com "rummy ares apk download")
[123 rummy](https://15rummy.com "123 rummy")
[rummy circle online cash game](https://16rummy.com "rummy circle online cash game")
[666e rummy](https://17rummy.com "666e rummy")
[rummy satta apk](https://25rummy.com "rummy satta apk")
[nabob rummy](https://26rummy.com "nabob rummy")
[rummy gill](https://27rummy.com "rummy gill")
[joy rummy apk](https://34rummy.com "joy rummy apk")
[rummy bears](https://35rummy.com "rummy bears")
[wealth rummy](https://36rummy.com "wealth rummy")
[rummy eras](https://37rummy.com "rummy eras")
[rummy yas](https://45rummy.com "rummy yas")
[rummy 9](https://46rummy.com "rummy 9")
[rummy west](https://47rummy.com "rummy west")
[rummy bonus apps](https://53rummy.com "rummy bonus apps")
[rummy health](https://54rummy.com "rummy health")
[rummy gams](https://56rummy.com "rummy gams")
[gamezy rummy](https://57rummy.com "gamezy rummy")
[rummy east apk download](https://62rummy.com "rummy east apk download")
[rummy all game list](https://63rummy.com "rummy all game list")
[rummy gili](https://64rummy.com "rummy gili")
[teen patti rummy 51 bonus](https://65rummy.com "teen patti rummy 51 bonus")
[rummy deity apk](https://67rummy.com "rummy deity apk")
[777 rummy](https://71rummy.com "777 rummy")
[rummy east 51 bonus](https://72rummy.com "rummy east 51 bonus")
[rummy 777](https://73rummy.com "rummy 777")
[indian rummy app download](https://74rummy.com "indian rummy app download")
[rummy nobal](https://75rummy.com "rummy nobal")
[rummy perfect apk](https://76rummy.com "rummy perfect apk")
[13 card rummy](https://92rummy.com "13 card rummy")
[rummy league apk](https://93rummy.com "rummy league apk")
[rummy helpline number](https://94rummy.com "rummy helpline number")
[time rummy](https://97rummy.com "time rummy")
[rummy movement](https://boteenpatti.com "rummy movement")
[rummy earning app](https://BrazilGameApk.Com "rummy earning app")
[rummy bonus app](https://BrazilGameApp.Com "rummy bonus app")
[rummy app 51 bonus](https://BrazilGameDownload.Com "rummy app 51 bonus")
[all rummy 51 bonus](https://indiabiggame.in "all rummy 51 bonus")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5530">issues.joomla.org/tracker/joomla-cms/5530</a>.</sub>
