### ISSUE TITLE
Create article>Description Text Area :: 'Insert link' pop-up is not responsive in mobile view & also 'Toggle editor' button is not placed correctly.

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5536]
-Log into the administrator panel using android mobile
-Go to article manager
-Create new article
-Click on insrt link button
-Check the pop-up

**'Ok' & 'Cancel' button is not visible even there is no horizantal scroller**
-Refer screenshot

Testing Environment.
-Device type: Mobile (Micromax A102)
-Screen Resolution:854 x 480 pixels 
-Screen Mode: vertical 
-Browser: Opera Mini(26.0.1656.87080) & Firefox(34.0.1)
-Os:Andriod 4.4.2

Refer both screenshots.![screen shot 2014-12-28 at 05 21 40](http://issues.joomla.org/uploads/1/a59e2993c70a19eff8bd95fbf16966ae.png)
![screen shot 2014-12-28 at 05 21 58](http://issues.joomla.org/uploads/1/26cde036858242164a2a900f2ba35fb0.png)

Best Regards,
Aasim Ali

**Comment by zero-24** [comment]
Moving to `Confirmed` as the issue that was opend by @infograf768 is still open in there Tracker :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5536">issues.joomla.org/joomla-cms/5536</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for creating this but it would appear that this has been resolved elsewhere in the code base. If this is not correct then this can be re-opened

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5536">issues.joomla.org/joomla-cms/5536</a>.</sub>
