### ISSUE TITLE
3.3.6: Joomla Help: Extension link is redirected to 404

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5548]
-Log into the administrator panel
-Go to sitename/administrator/index.php?option=com_admin&view=help
-Click on 'getting started with Joomla'3.3>Extension links
-Refer screenshots.

![screen shot 2014-12-29 at 01 33 18](http://issues.joomla.org/uploads/1/37502816553ddd331f5664b41a219b99.png)
![screen shot 2014-12-29 at 01 33 28]
(http://issues.joomla.org/uploads/1/5d5e8c3d6722a16ae8cfce0a8a54439f.png)
![screen shot 2014-12-29 at 01 36 30](http://issues.joomla.org/uploads/1/f16cb748be90fba20c96304ad1fe1de1.png)

Best Regards,
Aasim Ali

**Comment by brianteeman** [comment]
@Hutchy68 Can I close this here as it is really an issue regarding the docs server and not the joomla code - if I understand it correctly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5548">issues.joomla.org/joomla-cms/5548</a>.</sub>

**Comment by Hutchy68** [comment]
Closing, will create issue on different repo when repo with help component for help proxy is created by @mbabker
