### ISSUE TITLE
Users are no sent back to restricted article after login

### ISSUE THREAD

**Issue by kiabo** [joomla/joomla-cms#5553]
# Steps to reproduce the issue

**Case 1 - without login module**
Create an article with a registered access.
Login on frontend to get a direct link to this article. Copy it.
Logout and try to access a copied link as a guest.
Try to login!

**Case 2 - with login module**
Create and publish a login module in all pages. 
Create an article with a registered access.
Login on frontend to get a direct link to this article. Copy it.
Logout and try to access a copied link as a guest.
Try to login!
You'll be redirected to default menu page and not to the article.

## Expected result

A com_users component with login form, resulting in a redirect to original page, in this case, the article.

## Actual result

You have the message: 
"Error
You are not authorised to view this resource."

And just it. 

If you don´t have a login module in all pages, the users can´t login.
Even if you publish de login module, the users will be redirected to default menu page.

## Additional comments

If the marketing team wants to create a campaign linked to an registered article (in intranets for example), it will be impossible unless they use a third part extension.

**Comment by brianteeman** [comment]
After over two months without response for the requested information I am closing this issue at this time. It can always be reopened if further information is provided as had been requested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5553">issues.joomla.org/joomla-cms/5553</a>.</sub>
