### ISSUE TITLE
Once you have tagged an item you can't add any more tags

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#5554]
#### Steps to reproduce the issue
Create some tags (e.g.: Tag1, Tag2, Tag3)
Edit an item (Article, Contact... whatever is "taggable")
Add one or more (not all) tags (you can select between Tag1, Tag2, Tag3)
Save the item
Edit that item again
Try to add a new tag

#### Expected result
You should see a list of the "remaining" (not assigned) tags

#### Actual result
You see a list of the tags already assigned to that item

#### Workaround
Use batch tagging

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/5601

**Comment by wilsonge** [comment]
Reopening this as the code in #5601 is just wrong in so many ways and we need to consider a proper fix for this issue

**Comment by zero-24** [comment]
Closing as the issue looks fixed by #5630 Thanks :smile:
