### ISSUE TITLE
Tooltips misaligned in BS modals

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#5555]
#### Steps to reproduce the issue
Open a modal using BS (e.g.: "Batch")
Hover on a label

#### Expected result
Tooltips should be aligned to the label

#### Actual result
Tooltips are moved quite far to the right

#### Additional comments
@dgt41: Dimitris, I'm quite sure we've already seen that and a solution was found, but... I can't remember what it was... (a CSS job, for sure) Do you remember?

**Comment by nternetinspired** [comment]
Yes, the solution would to apply the tool-tip label fix from the other PR and to also wrap the select within another div, eg: `<div class="controls">`, as presumably that is also set to be an inline-block element.

**Comment by smz** [comment]
Browsing through issue I found this one *I* opened sometime ago.

I also brought out this issue in https://github.com/joomla/joomla-cms/issues/7247 (*which has been closed*)

Unhappily we still have this issue, but the reasons for it are now clearer to me (*or at least I have this presumption...*) and I don't think there is a viable solution.

Please see my analysis in https://github.com/joomla/joomla-cms/pull/7248#issuecomment-114709397

I don't know if this should be closed...
