### ISSUE TITLE
Cannot disable automatic email notification when user registration

### ISSUE THREAD

**Issue by phalouvas** [joomla/joomla-cms#5556]
#### Steps to reproduce the issue
From back end
In Users component options have:
- allow user registration
- send password to NO
In plugins->user->joomla options disable emails notification during registration.

#### Expected result
When a user register not to get any notification email.

#### Actual result
The email notification is send not matter what.

#### System information (as much as possible)
Joomla 3.3.6

#### Additional comments
The problem found to be on file:
/joomla_path/components/com_users/models/registration.php
line 502. You must change this line with below:

$user_plugin = JPluginHelper::getPlugin('user', 'joomla');
                $mail_to_user = json_decode($user_plugin->params)->mail_to_user;
                if ($mail_to_user) {
                    $return = JFactory::getMailer()->sendMail($data['mailfrom'], $data['fromname'], $data['email'], $emailSubject, $emailBody);
                } else {
                    $return = true;
                }

I will try to put the fix in Git.

**Comment by PhilETaylor** [comment]
I was able to replicate this, and after testing your proposed solution, I mangled it to create foundation of a merge-able PR #5594

**Comment by itsam** [comment]
The issue still remains on 3.4.5

**Comment by Bakual** [comment]
@itsam Check the "User - Joomla!" plugin. The notification is controlled there.

**Comment by itsam** [comment]
@Bakual Thanks for the prompt reply. Yes I did and I believe no matter the choice the notification email is sent anyway!

**Comment by Bakual** [comment]
If you believe it's still an issue, please open a new issue instead of writing on a closed one.
Then it can be properly tested and confirmed.
