### ISSUE TITLE
Issues with favicon (?)

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#5559]
Am I the only one having issues with favicon (both frontend and backend) with the latest staging code? I don't see it anymore **or** I see it randomly. I also don't see a request (GET) for it while monitoring network activity...

Have we changed something at this regard?

**Comment by brianteeman** [comment]
Closed see #5580 and/or #5566 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5559">issues.joomla.org/joomla-cms/5559</a>.</sub>
