### ISSUE TITLE
Accessibility issue>Joomla Article>Tag:: Can we add 'Search' & 'Clear text' ? button near  search text field

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5563]
**Back-end:**
-Create an article (article name: Test for the best)
-assign a tag (joomla)

**Front-end**
-Click over the article title 
-Click on the assigned tag
-It will redirect to a search field
-Enter title and press enter [keyboard Enter]

**Accessibility problem**
Suppose, user does not have keyboard or keyboard 'Enter' button is not working! So, there should be an alternative.
![screen shot 2014-12-30 at 09 06 19](http://issues.joomla.org/uploads/1/22b98950e54b8fefdbb811f2b183e348.png)![screen shot 2014-12-30 at 09 06 27](http://issues.joomla.org/uploads/1/3027bb4ed9dcf495966afe57b5919955.png)![screen shot 2014-12-30 at 09 06 31](http://issues.joomla.org/uploads/1/f0e43f13d9d356338b0b4ac5a3860adc.png)

**Comment by zero-24** [comment]
Closing as we have a PR here by @FPerisa at #8199
