### ISSUE TITLE
Create Article:: Can we change the placeholder message for 'Tag' 

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5570]
-Log into the administrator panel 
-Go to article manager
-Create new article
-Check place holder message for tag
-----------------------------------------------------------------
**It should be-**
**Placeholder message for tag field: Type or select some option**

-Select means, selecting the tag from available list, but there is a facility to create own tag by typing the term. So, Placeholder message must be more usable or easy to understand

![joomla3 4 0 staging](https://cloud.githubusercontent.com/assets/10045599/5586986/10afb06e-9104-11e4-9c78-07c5f6bc385e.png)

**Comment by infograf768** [comment]
This Tag field is not only used for Articles.
The string used is a global string: `JGLOBAL_SELECT_SOME_OPTIONS`. 
It is used as placeholder in formbehavior.php (ROOT/libraries/cms/html/formbehavior.php) when the field is marked as `multiple` in the `chosen` method.
We "could" override the string in our various core components ini files after making sure that we have no other fields marked as `multiple`. But not sure this is the right solution.

**Comment by brianteeman** [comment]
In com_modules you have the same situation for module positions and we use the message
Type or select a position

I am going to create a PR for this to be
Type or select a tag<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5570">issues.joomla.org/joomla-cms/5570</a>.</sub>

**Comment by rdeutz** [comment]
that's not saying what are the options, I think it is more: Type and press enter for a new tag or type and select an existing

I know it is long but that would be a correct description

**Comment by brianteeman** [comment]
Correction I dont see how to easily make that change - maybe someone else can<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5570">issues.joomla.org/joomla-cms/5570</a>.</sub>

**Comment by brianteeman** [comment]
@rdeutz how is the message for module positions any different to that needed for tags? Am I mising something

**Comment by rdeutz** [comment]
The behaviour is the same, the difference is that a tag or positions will be created. Is the same lang-tag used?

**Comment by brianteeman** [comment]
The code for selecting tags and the code for selecting modules is
completely different from what I could tell although the behaviour is the
same - hence my suggested language string

On 19 January 2015 at 12:56, Robert Deutz <notifications@github.com> wrote:

> The behaviour is the same, the difference is that a tag or positions will
> be created. Is the same lang-tag used?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5570#issuecomment-70488437>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
Closing as we have a PR here: https://github.com/joomla/joomla-cms/issues/8041
