### ISSUE TITLE
Issues with SQL server

### ISSUE THREAD

**Issue by rbsl-mohit** [joomla/joomla-cms#5572]
default values are not in proper format.

function used to get values  : getTableColumns

uses the following query : 
'SELECT column_name as Field, data_type as Type, is_nullable as \'Null\', column_default as \'Default\'' .		' FROM information_schema.columns WHERE table_name = ' . $this->quote($table_temp)

it has the default values as follows : 

 4 => 
    object(stdClass)[18]
      public 'Field' => string 'core_params' (length=11)
      public 'Type' => string 'text' (length=4)
      public 'Null' => string 'YES' (length=3)
      public 'Default' => string '(NULL)' (length=6)
  5 => 
    object(stdClass)[117]
      public 'Field' => string 'app_params' (length=10)
      public 'Type' => string 'text' (length=4)
      public 'Null' => string 'YES' (length=3)
      public 'Default' => string '(NULL)' (length=6)
  6 => 
    object(stdClass)[118]
      public 'Field' => string 'ordering' (length=8)
      public 'Type' => string 'int' (length=3)
      public 'Null' => string 'NO' (length=2)
      public 'Default' => string '((0))' (length=5)
  7 => 
    object(stdClass)[119]
      public 'Field' => string 'published' (length=9)
      public 'Type' => string 'tinyint' (length=7)
      public 'Null' => string 'NO' (length=2)
      public 'Default' => string '((0))' (length=5)

So when inserting values it insert the not available vlaues with these defualt values so following issue occurs : 

22018 [Microsoft][SQL Server Native Client 11.0][SQL Server]Conversion failed when converting the varchar value '((0))' to data type tinyint.SQL=INSERT INTO [joomla_xyx] ([level],[owner_id],[user_id],[class],[object_id],[message],[user_ip],[created_date],[content],[read],[position],[previous_token],[current_token]) VALUES ('1','','644','yxz','0','Configuration Updated','127.0.0.1','2014-12-31 12:02:16','','((0))','','','ac50ef3ed6e12b029c88cf9eea97b482')

**Comment by rbsl-mohit** [comment]
Hi,

Sorry but i didn't get you. 

It may help, Please look at the screen shot of the system information of the Joomla kit that i am using.

![screenshot_180](https://cloud.githubusercontent.com/assets/3022128/5594373/a0395210-926e-11e4-9e44-fa032a9ca52e.png)

**Comment by brianteeman** [comment]
Sorry I missed your reply.

This should have been fixed in the upcoming Joomla 3.4

If you download the latest development version and install that (not on a live site) and test it again it will really help. If the problem has gone please post here and we can close it. If the problem still exists please post here and the bug can be looked at.

https://github.com/joomla/joomla-cms/archive/staging.zip<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5572">issues.joomla.org/joomla-cms/5572</a>.</sub>

**Comment by brianteeman** [comment]
After almost two months without response i am closing this issue (it can always be reopened if the question is answered)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5572">issues.joomla.org/joomla-cms/5572</a>.</sub>
