### ISSUE TITLE
Article Manager: Articles::  'show the sidebar' button is NOT getting shown fully in  'Small tablet landscape (800x600)' & 'Tablet portrait (768x1024)'

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5574]
Go to article list view and check the sidebar for screen resolution 'Small tablet landscape (800x600)' & 'Tablet portrait (768x1024)'

![screen shot 2014-12-31 at 08 10 02](http://issues.joomla.org/uploads/1/6f830609cd7fe813e72ec6edad6aa8b9.png)

**Comment by brianteeman** [comment]
Closing as this is not present in current master and has presumably been fixed elsewhere
