### ISSUE TITLE
Recaptcha is not turned off

### ISSUE THREAD

**Issue by jjsjjs** [joomla/joomla-cms#5581]
#### Steps to reproduce the issue
Turn on reCaptcha and also the plugin.
Turn it off. In configuration.php you can see it is turned off, but actually it stays on.
So registration still asks for recaptcha. But there is no code to see.
Even with recaptcha turned on in configuration and the plugin published there is no captcha code to see. Google API keys are entered correct.
Joomla 3.3.6
Tested several templates, so it seems no template issue.
thanks!

#### Expected result

No captcha or a captcha image when all activated

#### System information (as much as possible)
Setting 	Value
 
PHP Built On 	Linux vx05wb01.vertixo.com 2.6.32-5-amd64 #1 SMP Fri May 10 08:43:19 UTC 2013 x86_64
Database Version 	5.5.9
Database Collation 	latin1_swedish_ci
PHP Version 	5.3.25
Web Server 	Apache/2
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; rv:34.0) Gecko/20100101 Firefox/34.0

**Comment by PhilETaylor** [comment]
I have tested this and cannot find a problem

I:

1) Enabled the plugin, inputing valid keys from Google

Checked registration page - no captcha box to be seen (its not broken - its not there)

2) Enabled default captcha of ReCaptcha in Joomla Global Config

Checked registration page - I see a fully functioning reCaptcha Challenge box

3) Disabled default captcha of ReCaptcha in Joomla Global Config 

Checked registration page - no captcha box to be seen (its not broken - its not there)

Therefore I cannot replicate your problem with the latest joomla-cms master branch.

I have also tested with Enabling the Default Captcha in Joomla Global Config, and DISABLING this plugin, and that gives me this page with no captcha, but a very in your face message telling you why:

![screenshot 2015-01-02 23 16 02](https://cloud.githubusercontent.com/assets/400092/5600600/6075d24a-92d5-11e4-8ae4-ee1bd5b92896.png)

Therefore I can only conclude this works as advertised :)

**Comment by jjsjjs** [comment]
Hello Phil,

the same picture i get when everything is enabled and captcha picture is 
there.
Now i tested with several templates, also the originals.
And everytime cleared the cache.
Now i installed "the new recaptcha" from joomtech and this one does 
work, also on the Frre Metro template from Joomlashine.
I noticed the link to google was slightly different--> 
https://www.google.com/recaptcha/api/siteverify  and in recaptcha.php it 
is without verify
I changed this and it still did not work, so it is also not the link 
which in previuos cases was the cause.

For now as long as the version of joomtech works i'm happy.
Allthough i'm not happy with this because the original should also be 
able to work.

Thanks for your input !
Jerry
Phil Taylor schreef op 3-1-2015 om 0:16:

**Comment by PhilETaylor** [comment]
I'm sorry I was unable to replicate your problem at all.

**Comment by brianteeman** [comment]
I am closing this at this time it can always be reopened of others report the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5581">issues.joomla.org/joomla-cms/5581</a>.</sub>

**Comment by jjsjjs** [comment]
ok no problem, thanks.
As the joomtech version works, i can live with it :)

Brian Teeman schreef op 3-1-2015 om 1:09:
