### ISSUE TITLE
Postgres sample data - Publishing dates and Author

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#5583]
Install Joomla with the default sample data set using POSTGRES

You will see on the home page that it says the article is expired.

Now log in and check the publishing dates for the article - as can be seen in the screenshots the default values are wrong

![screen shot 2015-01-01 at 13 37 29](http://issues.joomla.org/uploads/1/0bbf404eb5266659645b883320a533fe.png)

I am not sure if this is an error in the sql data set or as a result of recent PR from @bakual and @wilsonge for handling the date on postgres

**Comment by brianteeman** [comment]
There are other issues also relating to default values

![screen shot 2015-01-01 at 13 44 21](http://issues.joomla.org/uploads/1/28d0750f8cf8c16ee262f05c191e55c2.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5583">issues.joomla.org/joomla-cms/5583</a>.</sub>

**Comment by wilsonge** [comment]
The expired articles was solved by https://github.com/joomla/joomla-cms/pull/3803 but there was a mssql issue that we would never get good data on to fix

**Comment by brianteeman** [comment]
OK I am closing this as a duplicate report
