### ISSUE TITLE
TypeError: this.toggleFocus.create is not a function

### ISSUE THREAD

**Issue by jimbrooking** [joomla/joomla-cms#5585]
In Firefox, running Joomla 3.3.6 (Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT ), template is ProtoStar

#### Steps to reproduce the issue
Search module (smart search) published in Position 0 (Search) and appears on the screen.
Error displayed in Firebug on page load:
TypeError: this.toggleFocus.create is not a function... this.onCommand.bind(this, [false])).addEvent('focus', this.toggleFocus.create(
	
Error from autocompleter.js (line 121, col 233)

Unpublish the Search module and no error appears

#### Expected result

Would like to not have this error appear because I would like to use Smart Search on my site. The appearance of the error seems to have unwanted side-effects on other Javascript used on different pages. 

#### Actual result

See above

#### System information (as much as possible)

PHP Built On 	Linux host381.hostmonster.com 3.12.32.1415814620 #1 SMP Wed Nov 12 11:53:28 CST 2014 x86_64
Database Version 	5.5.40-36.1-log
Database Collation 	utf8_general_ci
PHP Version 	5.4.34
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0 

#### Additional comments
This error appears to exhibit the same symptom as http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=29691_ but as far as I can see the patch for that bug is applied in my version of Joomla.

**Comment by smz** [comment]
This should be already fixed in 3.4.0-dev (upcoming rev).
In it Smart Search is also in a waaaaaay better shape, globally.
If you can, try the latest nightly build (not for production!).

**Comment by brianteeman** [comment]
Cannot replicate in 3.4beta1 and based on the comment of @smz and the lack of response from the original poster I am closing this at this time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5585">issues.joomla.org/joomla-cms/5585</a>.</sub>
