### ISSUE TITLE
Menu Manager: Menus:: UI issue, when we rotate the mobile mode from landscape to portrait

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5588]
-Log into the administrator panel using android mobile
-Go to Menu Manager: Menus [lANDSCAPE MODE]
-Change the mode from landscape to portrait and check UI
**Note this issue is not there in joomla 3.3.6**

**Testing Environment.**
-Device type: Mobile (Micromax A102)
-Screen Resolution:854 x 480 pixels 
-Screen Mode: portrait
-Browser: opera mini 26.0
-Os:Android 4.4.2

Refer all screenshots.
![screen shot 2015-01-02 at 01 15 24]
(http://issues.joomla.org/uploads/1/fa5aa0fa3a4396e72b09d2bad24d0a02.png)

![screen shot 2015-01-02 at 01 15 44](http://issues.joomla.org/uploads/1/bc41ec6e0b280730130b03b094131406.png)

**Comment by brianteeman** [comment]
I cannot replicate this on my android devices running chrome. Can you please retest with chrome to see if it is an Opera mini issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5588">issues.joomla.org/joomla-cms/5588</a>.</sub>

**Comment by aasimali** [comment]
@brianteeman 
This is not browser specific. It seems, It is joomla 3.4-dev specific.
 **The issue is there on chome too on my device** I have tested this issue with different different browsers on 2 different android versions.

**Testing Environment**
Browsers: Chrome(33.0.1750.136) , Firefox(34.0.1) & Browser: opera mini 26.0
Android:4.2.2 and 4.4.2
RAM: 2.00GB
CPU: Octa-core1.7GHz
**Step to replicate this issue**
1. Log into the Joomla back-end [Joomla 3.4 Dev)
2.Go to menu manager
3. Rotate the screen to lanscape mode 
4. Change the mode, Landscape to portrait
------------------------------------------------------
Note:
**I also test the same functionality on Joomla 3.3.6 stable but I am not getting this issue.**

![chrome-menu manager](https://cloud.githubusercontent.com/assets/10045599/5601698/454c0ddc-9338-11e4-855b-df42d5439c03.png)

Can you please retest this issue in above mentioned test environment?

**Comment by brianteeman** [comment]
I have retested with staging using both opera mini and chrome on a nexus 4
running android 5 and a nexus 7 running android 4.4

I still cannot replicate either issue

**Comment by aasimali** [comment]
@brianteeman  Thank you for retesting this issue.
** To replicate this issue, you have to retest this in the same environment, which I have mentioned above'**
It might possible that issue will not be there in nexus.

**Comment by brianteeman** [comment]
Well as I dont have your tablet then thats not going to be possible

**Comment by aasimali** [comment]
@brianteeman 
Okay! But, I hope, the testing team will have most of the devices. Can you please ask them to test this issue either on **Xiaomi Redmi Note** or **Micromax A102**? IF POSSIBLE
Thank you!
Have a great weekend.

**Comment by brianteeman** [comment]
Your hope is unfounded - do you realise how many different android devices
there are? (It looks as if both of the devices you name are only available
in India)

On 3 January 2015 at 12:00, Aasim Ali <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman>
> Okay! But, I hope, the testing team will have most of the devices. Can you
> please ask them to test this issue either on *Xiaomi Redmi Note* or *Micromax
> A102*? IF POSSIBLE
> Thank you!
> Have a great weekend.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5588#issuecomment-68592762>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by aasimali** [comment]
@brianteeman 
There are thousand of devices but I am using these two and I have tested the same issue on both :smiley: 
**I am asking because the same issue is not there on Joomla 3.3.6**

**Comment by mbabker** [comment]
The updated code to deal with the toolbar and sticking it isn't foolproof.
We're dynamically resizing the container at 481 pixels and wider
viewports.  At 480, which is when the toolbar collapses and you have to hit
the button to expand it, we stop resizing the container.  So yes, there is
an issue if you're resizing the viewport and you jump from a width of 481
pixels or greater to a width of 480 pixels or less.

**Comment by GunnarBs** [comment]
I can reproduce the issue (Dolpin Browser, Joomla 3.4.0). It is not very clear from the first posting: The button new is there but should not after you turn the device. When you click on the Toolbar, all buttons appear. When click again, they disappear, also the wrongly displayed new button.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5588">issues.joomla.org/joomla-cms/5588</a>.</sub>

**Comment by brianteeman** [comment]
Closed as a known issue that can not be resolved without a forced refresh on a change in orientation or dimensions<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5588">issues.joomla.org/joomla-cms/5588</a>.</sub>
