### ISSUE TITLE
Site says Verify Code not correct(after clicking registration email link), but people can log-in

### ISSUE THREAD

**Issue by jjsjjs** [joomla/joomla-cms#5592]
#### Steps to reproduce the issue
Create an account
click the action link in the email send by the system

#### Expected result
Activation Complete

#### Actual result
Site Displaying: Activation Code not correct
People get confused thinking it does not work.
But still they can log-in with their created account and username/password

#### System information (as much as possible)
Database Version 	5.5.9
Database Collation 	latin1_swedish_ci
PHP Version 	5.3.25
Web Server 	Apache/2
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; rv:34.0) Gecko/20100101 Firefox/34.0

**Comment by PhilETaylor** [comment]
Cannot replicate on Joomla 3.3.6
Cannot replicate on joomla/joomla-cms master

**Comment by brianteeman** [comment]
Tested with 3.3.6
Set user options for New User Account Activation to self
Created a new user on the front end
Confirmed in the User Manager that the account has been created with enabled and activated both showing red cross
Checked on the front end that the user cannot login 
Clicked on email link
Got message that the account was now active
Confirmed in the User Manager that the account has been created with enabled and activated both showing green tick
Checked on the front end that the user can login 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5592">issues.joomla.org/joomla-cms/5592</a>.</sub>

**Comment by infograf768** [comment]
> Database Collation latin1_swedish_ci

This is totally incorrect btw! The collation for any joomla site should be utf8

**Comment by gwsdesk** [comment]
Followed same steps as Brian to try to reproduce issue but cannot neither on J3.3.6 nor on J3.4.0 Alpha<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5592">issues.joomla.org/joomla-cms/5592</a>.</sub>

**Comment by jjsjjs** [comment]
This is strange, I checked in phpmyadmin and it says utf8_general_ci

So how can it state latin1_swedish_ci ?


infograf768 schreef op 3-1-2015 om 9:02:

**Comment by infograf768** [comment]
>This is strange, I checked in phpmyadmin and it says utf8_general_ci

You may be confusing the collation of the tables with the general collation of the database.

**Comment by Webdongle** [comment]
@test Unable to confirm error ... system works as expected

Tested with 3.3.6 migrated from 2.5
Set user options for New User Account Activation to Admin
Created a new user on the front end
Modal message "Your account has been created and a verification link has been sent to the email address you entered. Note that you must verify the account by clicking on the verification link when you get the email and then an administrator will activate your account before you can login."
Checked in Users >>> User manager Account was created but not Enabled or activated

Clicked on email link of the email sent to the new user
Checked in Users >>> User manager Account was created but not Enabled or activated
Modal message "Your email has been verified. Once an administrator approves your account, you will be notified by email, and you can login to the site."
Checked in Users >>> User manager Account was created but not Enabled or activated

Clicked the activation link that was in the email to admin
Modal message "The user's account has been successfully activated and the user has been notified about it."
Checked in Users >>> User manager Account was created and Enabled and activated

All emails, links and messages were sent/displayed in the correct sequence.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5592">issues.joomla.org/joomla-cms/5592</a>.</sub>

**Comment by Webdongle** [comment]
Forgot to mention that Recapture was used in the registration form when I tested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5592">issues.joomla.org/joomla-cms/5592</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this at this time as multiple people have been unable to confirm this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5592">issues.joomla.org/joomla-cms/5592</a>.</sub>
