### ISSUE TITLE
Category Manager: Articles :: Wrong message after publishing sub-category.

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5596]
-Go to  Category Manager: Articles
-Create a main category (Sya QA)
-Create another sub-category(parent- QA)
-unpublish the parent category(QA)
-Both parent & sub category will get unpublished.
-Click on sub-category publish button and check the message.

Note, A success message will display for publish category, but the status will remain same 'unpublished'

Solution: Change the message, Display an usable message, so that user can understand it.
![screen shot 2015-01-03 at 01 41 01](http://issues.joomla.org/uploads/1/c57cc2e0a89bdda3f4dc03411ff3c3f8.png)

**Comment by infograf768** [comment]
I confirm the issue.

**Comment by aasimali** [comment]
Thank you @infograf768 
Have a great day.

**Comment by zero-24** [comment]
Closing as we have a PR that fix it at #8038

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/8065
