### ISSUE TITLE
Article Manager: Articles:: Usability issue, Can we rename the column name for better usability? I suggest, it should be 'Created Date' instead of 'Date'

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5597]
-Go to article list view and check the date column.
-Is it really meaningful?
-Refer screenshot please and read the text written over the screenshot!

![screen shot 2015-01-03 at 03 17 58](http://issues.joomla.org/uploads/1/8def0587e38144e0b66b48f88733e126.png)

**Comment by zero-24** [comment]
Closing as we have a PR: https://github.com/joomla/joomla-cms/pull/5598 Thanks @aasimali<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5597">issues.joomla.org/joomla-cms/5597</a>.</sub>
