### ISSUE TITLE
System message: wrong html structure created by javascript Joomla.renderMessages function

### ISSUE THREAD

**Issue by peterader** [joomla/joomla-cms#5602]
#### Steps to reproduce the issue
- go to forgot password page
- press submit without entering anything

The javascript validation displays an erorr with incorrect HTML structure:

#### Expected result

< div id="system-message-container">
< div id="system-message">
< div class="alert alert-error">

#### Actual result

< div id="system-message-container">
< div id="system-message" class="alert alert-error">

#### System information (as much as possible)

Joomla 3.3.6

#### Additional comments

The structure is defined in two places and should be identical:

- media\system\js\core-uncompressed.js
- layouts\joomla\system\message.php

**Comment by zero-24** [comment]
Closing as we have a Pull here #7278
