### ISSUE TITLE
Insert with specific ID

### ISSUE THREAD

**Issue by okonomiyaki3000** [joomla/joomla-cms#5618]
In the sql update files for 2.5.28 (`administrator/components/com_admin/sql/updates/...`) we have an insert query something like:

```sql
INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`) VALUES
(900, 'plg_quickicon_eosnotify', 'plugin', 'eosnotify', 'quickicon', 0, 1, 1, 1, '', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0);
```

This will fail if there is already an extension installed with id 900. It would be better to not specify an id and allow the auto-increment to set it. Like so:

```sql
INSERT INTO `#__extensions` (`name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`) VALUES
('plg_quickicon_eosnotify', 'plugin', 'eosnotify', 'quickicon', 0, 1, 1, 1, '', '{}', '', '', 0, '0000-00-00 00:00:00', 0, 0);
```

**Comment by brianteeman** [comment]
IIRC 900 is in a protected range that only the core can use <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5618">issues.joomla.org/joomla-cms/5618</a>.</sub>

**Comment by zero-24** [comment]
yes regular new extensions starts with ID 10000

![screen shot 2015-01-05 at 04 29 30](http://issues.joomla.org/uploads/1/fc44b7be05839bf817f4972b8add00f4.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5618">issues.joomla.org/joomla-cms/5618</a>.</sub>

**Comment by brianteeman** [comment]
Closing as expected behaviour - not an issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5618">issues.joomla.org/joomla-cms/5618</a>.</sub>

**Comment by okonomiyaki3000** [comment]
Somehow I had a site where this didn't happen properly. Not sure why.
