### ISSUE TITLE
Configuration setting>session lifetime:: Validation is required for zero & negative value input

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5619]
-Validation is required for zero & negative value input, 
-If the user enters the negative & zero value accidently in the session lifetime text field, The entire site stops working. 
-Displays this message 
**The most recent request was denied because it contained an invalid security token. Please refresh the page and try again.** 
-I did everything hard refresh, close & relaunch the browser, etc. but still the problem was same. 
-I overcome this issue by changing the value manually in **configuration. php** file 
-So,as an end user,I suggest,Validation is needed.

![screen shot 2015-01-05 at 02 36 48](http://issues.joomla.org/uploads/1/65c10271124e5dfa65b1808103735ad8.png)

**Comment by jackkum** [comment]
I can create PR.
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/model/form/application.xml#L714
```xml
<field
	name="lifetime"
	type="number"
	default="15"
	label="COM_CONFIG_FIELD_SESSION_TIME_LABEL"
	description="COM_CONFIG_FIELD_SESSION_TIME_DESC"
	required="true"
	filter="integer"
	size="6"
	min="5"
	validate="number" />
```
and add number.php here https://github.com/joomla/joomla-cms/tree/staging/libraries/joomla/form/rule
```php
class JFormRuleNumber extends JFormRule
{
	public function test(SimpleXMLElement $element, $value, $group = null, JRegistry $input = null, JForm $form = null)
	{
		// If the field is empty and not required, the field is valid.
		$required = ((string) $element['required'] == 'true' || (string) $element['required'] == 'required');

		if (!$required && empty($value))
		{
			return true;
		}

		$min   = isset($element['min']) ? (int)$element['min'] : null;
		$max   = isset($element['max']) ? (int)$element['max'] : null;

		if(!is_null($min) && $min > $value)
		{
			return false;
		}

		if(!is_null($max) && $max < $value)
		{
			return false;
		}

		return true;
	}
}
```
but that not help without this http://issues.joomla.org/tracker/joomla-cms/4653
it is help, but the error message will not show.

**Comment by NathanHawks** [comment]
@jackkum I don't think he was requesting a message be shown. I think he was saying, that is the error he is shown, after being locked out of the site when the faulty entry is allowed. I believe validation is all @aasimali was asking for, perhaps also with a sane minimum value (because 1 is enough to be a major hassle for many users; I should think 5 or more would be enough.)

**Comment by aasimali** [comment]
@NathanHawks @jackkum 
Yes! I'm asking for the validation, Do not allow to enter the zero & negative value in it.
Show an usable message: **You can't enter zero & negative value**

**Comment by gunjanpatel** [comment]
Set to "closed" on behalf of @gunjanpatel by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5619">issues.joomla.org/joomla-cms/5619</a>

**Comment by gunjanpatel** [comment]
Closing as we have code for this issue in #5624 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5619">issues.joomla.org/joomla-cms/5619</a>.</sub>
