### ISSUE TITLE
Install from Web images broken link

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#5620]
#### Steps to reproduce the issue
Install Joomla
Navigate to Extension manager
Activate 'Install from Web'

#### Expected result
Extensions with images are displayed

#### Actual result
Images do not display![screen shot 2015-01-05 at 05 28 44](http://issues.joomla.org/uploads/1/eb5cf2572656fe9661aba9e2f3f0f3cb.png)

**Comment by zero-24** [comment]
Closing here as it is not a Joomla Core issue and it is allready reported on the `Install from Web` Issue Tracker see: https://github.com/joomla-extensions/install-from-web-client/issues/12

But IIRC this are issues with the new moving to the new JED<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5620">issues.joomla.org/joomla-cms/5620</a>.</sub>

**Comment by PhilETaylor** [comment]
Just creating a link to https://github.com/joomla-extensions/install-from-web-client/issues/10 as well
