### ISSUE TITLE
User Manager:: There is no option in toolbar for deactivate the user from user manager

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5622]
-Go to user manager
-Check the filter 'Active', There are 2 option activated/unactivated
-But the question is: **How to deactivate a user from user manager?**
![screen shot 2015-01-06 at 00 31 57](http://issues.joomla.org/uploads/1/ef97874cc18810890a14472860d19987.png)

**Comment by zero-24** [comment]
@aasimali 

`Unactivated` are user that don't klick the registration link in there email. If you what to Block a user you have the `Block` and `Unblock` button. If the activation link don't work for any reason you can `Activate` with the `Activate` Button :smile:

**Comment by aasimali** [comment]
Thanks @zero-24 ze
