### ISSUE TITLE
Create New User:: Password & confirm password fields should be mandatory.

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5623]
-Go to create new user view
-Create a new user,keep blank password & confirm password fields and click over the save button

-**If we keep these two fields blank and save the user, The user account is getting created but that user cannot login because password field is mandatory.**

![screen shot 2015-01-06 at 00 43 25](http://issues.joomla.org/uploads/1/3ce506cd6c152664b827554644552f6b.png)
![screen shot 2015-01-06 at 00 43 36](http://issues.joomla.org/uploads/1/a5ba7c48c60732395ddf0944dcc5538f.png)

**Comment by zero-24** [comment]
@aasimali if you add a user without PW Joomla generates a random PW and send it via Email. Have a look into your emails. :smile: 

![new_user_details](https://cloud.githubusercontent.com/assets/2596554/5625484/e5188e40-957b-11e4-9103-f05cbbffe53c.JPG)

**Comment by aasimali** [comment]
thanks @zero-24  :smiley:

**Comment by aasimali** [comment]
-I am reopening this issue because, There is an usability issue.
-While creating user from front-end all the fields are mandatory
-While creating user from back-end only 3 fields are mandatory!
-In this case, We should display a message 'an email is sent to your email ID containing password'

**Comment by rdeutz** [comment]
That's because in the backend an administrator creates a user and in the frontend it is the user itself. I don't see a usability issue here.

**Comment by aasimali** [comment]
@rdeutz 
Yes! But I am seeing! For example: 
-You are a 'super user' of xyz site & you create an another super user, While creating super user, You 
do not enter password & confirm password because they are not mandatory fields. 
-Account is getting created and an email is also getting sent to the entered email ID, but who knows            that? The only familiar user of Joomla knows! **What about the new users?**

**Comment by rdeutz** [comment]
I still think this isn't a big issue if any. On the other side it doesn't hurt if we have a message you are proposing. Can you make a PR?

**Comment by infograf768** [comment]
When creating a user in back-end, the password and confirm password ARE mandatory, as far as I know (staging)
![screen shot 2015-01-06 at 09 44 27](https://cloud.githubusercontent.com/assets/869724/5626210/be2a07b6-9588-11e4-9c73-160f1214dc02.png)

**Comment by aasimali** [comment]
@infograf768 
I also have the staging site and I updated the package yesterday! I need to check this current package. So,give me a minute please!

**Comment by infograf768** [comment]
```
<input id="jform_password" class="validate-password required" type="password" aria-required="true" required="required" maxlength="99" size="30" autocomplete="off" value="" name="jform[password]">
```

**Comment by aasimali** [comment]
@infograf768 
I am sorry to say, but in the current package, it is not fixed. If it is fixed at your staging site, then, Its amazing.
I have downloaded & installed the package from here: http://developer.joomla.org/cms-packages/

![joomla nightly builds](https://cloud.githubusercontent.com/assets/10045599/5626433/5521b876-95b1-11e4-8cb9-e3140e7e76a2.png)
![joomla 3 4 staging administration user manager add new user](https://cloud.githubusercontent.com/assets/10045599/5626442/73fb0af4-95b1-11e4-98c8-bed07f155f8e.png)

**Comment by infograf768** [comment]
hmm, weird

A clean staging install does the same as you show

**Comment by infograf768** [comment]
Ok, I found out:

The password and confirm password fields become required when the Joomla User Plugin "Notification Mail to User" is set to No.
![screen shot 2015-01-06 at 10 24 38](https://cloud.githubusercontent.com/assets/869724/5626637/46687be4-958e-11e4-8ec1-4c984c5c2513.png)

**Comment by aasimali** [comment]
@infograf768 Hmmm! Yes, Its weird.
It might possible, someone has forgotten to commit the code. So, should I keep this issue open till it is not getting fixed in the package? Or should I close this?

**Comment by aasimali** [comment]
@infograf768  Yes! It works. Thanks :)

**Comment by aasimali** [comment]
@infograf768 
Yes! It works. when 'notification mail to user' is set to 'NO'
-But if it set to 'Yes' Then, Can we display a message? 'User is created successfully and an email is sent to entered email ID containing password'

**Comment by infograf768** [comment]
A message would be good indeed. In good English.

**Comment by aasimali** [comment]
@infograf768 Yes! I agree :+1:  :smile:

**Comment by brianteeman** [comment]
I am closing this because as explained it is not correct for these fields to be marked as required in this case 

If someone wants to create a PR for the message as suggested please create a new PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5623">issues.joomla.org/joomla-cms/5623</a>.</sub>
