### ISSUE TITLE
UX / UI Review for moblie devices needed

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#5628]
We need a `UX / UI Review` (what option gets hidden on phones) for the following components

- com_redirect
- com_messages
- com_banners (Tracks view only)
- com_search
- com_finder (filters view only)
- com_media
- com_installer (discover, manage, update, updatesites)
- com_languages

**Comment by brianteeman** [comment]
Please see #5629 does that address everything on your list (plus a few more)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5628">issues.joomla.org/joomla-cms/5628</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman 

>Please see #5629 does that address everything on your list (plus a few more)

it only adress the com_installer updatesites view. All other do still need a PR / review. :smile:

With review i don't mean `check all boxes` ATM there dont hidden something on phones that looks bad

**Comment by brianteeman** [comment]
I only addressed the list views in #5629 I did not look at any item views

This was because right now on the majority of them you cant use the toolbar
that is present

On 6 January 2015 at 20:25, zero-24 <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman>
>
> Please see #5629 <https://github.com/joomla/joomla-cms/pull/5629> does
> that address everything on your list (plus a few more)
>
> it only adress the com_installer updatesites view. All other do still need
> a PR / review. [image: :smile:]
>
> With review i don't mean check all boxes ATM there dont hidden something
> on phones that looks bad
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5628#issuecomment-68927666>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
closing here as i have open one PR per reviewed view.

UI/UX Review for com_redirect on mobile devices #5665
UI/UX Review for com_messages on mobile devices #5666
UI/UX Review for com_banners tracks view on mobile devices #5667
UI/UX Review for com_search on mobile devices #5668
UI/UX Review for com_finder on mobile devices #5669
UI/UX Review for com_installer discover view on mobile devices #5670
UI/UX Review for com_installer updatessits view on mobile devices #5671
UI/UX Review for com_language view overrides on mobile devices #5672
UI/UX Review for com_languages content view on mobile devices #5673
