### ISSUE TITLE
onTagAdd and onTagRemove plugin events

### ISSUE THREAD

**Issue by Greblys** [joomla/joomla-cms#5631]
Do you think these plugin events are useful and should be introduced? I needed those today for one feature, but ended up creating database triggers.

**Comment by zero-24** [comment]
Moving to `Needs Review` so a Maintainer can decide if this should included or not. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5631">issues.joomla.org/joomla-cms/5631</a>.</sub>

**Comment by csthomas** [comment]
I added some proposal at https://github.com/joomla/joomla-cms/pull/9307
Can you take a look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5631">issues.joomla.org/joomla-cms/5631</a>.</sub>

**Comment by brianteeman** [comment]
Closing as we have a PR for review
