### ISSUE TITLE
 Extension Manager: Install :: Language constant missing 'FILES_JOOMLA_XML_DESCRIPTION'

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5633]
-Go to  Extension Manager: Install 
-Download the package from here: http://developer.joomla.org/cms-packages/
-latest package 7 jan 2015
-Install the latest joomla 3.4 dev package
-There you will see language constant missing
**FILES_JOOMLA_XML_DESCRIPTION**

![screen shot 2015-01-07 at 02 51 18]
(http://issues.joomla.org/uploads/1/9721679276c7d0c93f9a8d49d9939b5b.png)

**Comment by infograf768** [comment]
This screenshot displays a message "Installing file was successful"
What have you installed?
The string is present in core:
FILES_JOOMLA_XML_DESCRIPTION="Joomla! 3 Content Management System"

**Comment by infograf768** [comment]
Oh, you installed the joomla FULL package through extension manager...

**Comment by aasimali** [comment]
@infograf768 
Yes! I installed the latest package, That I installed every day, but I have never seen this issue before.

![joomla nightly builds](https://cloud.githubusercontent.com/assets/10045599/5643233/e152dbde-967b-11e4-9bef-9b97320b180c.png)

**Comment by infograf768** [comment]
I just did this with the same Update package on a 3.3.6 site and I can't reproduce.

**Comment by aasimali** [comment]
Yes! Because I am not installing it on 3.3.6 site. I am installing it on staging site 3.4-dev package. Just upgraded the 6th jan 2015 package to 7th jan 2015 package

**Comment by infograf768** [comment]
I would not consider this as a bug as the proposed update package is not designed to upgrade a staging instance.

**Comment by aasimali** [comment]
okay! But, How can I update the package? any other alternative for the same? I wanna keep my code up to date for testing/retesting purpose.

**Comment by infograf768** [comment]
I guess just do not expect the description to be translated (to be checked)
In any case using Eclipse/Git or directly git with CLI would update a test site
