### ISSUE TITLE
User Manager: Add New User:: Wrong message, If 'confirm password' is not same as 'password'

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5635]
**Prerequisites: Plugin Manager: User - Joomla>Notification Mail to User>'NO'** 

-Go to 'User Manager: Add New User'
-Fill Name,login name, Password, email id correctly but do not enter the same password in 'confirm password' field and click on save button
-Check the message,**That should be error message instead of warning**

**Message should be:- **Confirm password** must be same as **password**'

![screen shot 2015-01-07 at 04 15 20](http://issues.joomla.org/uploads/1/9f45d9d7d46e57991c691cc2c6456db0.png)
![screen shot 2015-01-07 at 04 15 32](http://issues.joomla.org/uploads/1/79631ace8f0194880f3b74b064d44d72.png)

**Comment by aasimali** [comment]
![screen shot 2015-01-07 at 06 18 05](http://issues.joomla.org/uploads/1/817375d99abe65f27460930ebb6326cc.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5635">issues.joomla.org/joomla-cms/5635</a>.</sub>

**Comment by zero-24** [comment]
Moving to `Confirmed` Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5635">issues.joomla.org/joomla-cms/5635</a>.</sub>

**Comment by infograf768** [comment]
Patch here: https://github.com/joomla/joomla-cms/pull/6913

FYI, the patch does the same as elsewhere for the confirm password error, i.e. it will be a Warning

**Comment by zero-24** [comment]
Thanks Closing here as we have a PR by @infograf768 :+1:
