### ISSUE TITLE
User Manager: Users:: Message should be 'User unblocked' instead of 'User Enabled'

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5637]
-Go to 'User Manager>User' 
-Unblock a user 
-Check the message. 
-Message should be:- **user unblocked**
![screen shot 2015-01-07 at 05 47 59](http://issues.joomla.org/uploads/1/f500b77576eff74607e922f6e00af23f.png)

**Comment by brianteeman** [comment]
This is one of those cases where we sadly use one function for two slightly
different purposes  so we have mixed messages and I am not certain on the
best approach.

You will see that the toolbar has buttons `block` and `unblock`
There is a column `enabled`
Items in this column have tooltips `block this user` and `unblock`

From my perspective there is a difference between enable a user ie approve
their registration and block a user ie they have been bad

I am going to close this here and add it to the task list for User
Interface Text review
https://github.com/joomla/user-interface-text/issues/24

Thanks for reporting this

**Comment by aasimali** [comment]
You're welcome @brianteeman :)
