### ISSUE TITLE
Smart Search missing content

### ISSUE THREAD

**Issue by ckubs** [joomla/joomla-cms#5638]
Discovered that my database was very large after few days after switching from wordpress to Joomla. Discovered that Smart Search is responsable for this.
Before it's deactivation pushed purge index button instead of the delete one and 2 thirds of my articles from the old blog are now gone on the frontend, with both Jcomments comments.
Is it anything I ca do to repair that? :(

 I can't find a proper documentation on that regard and I can't register on Joomla forum because I get an error that I have a spamming IP althoug my ip is not listed on stopfotumspam website.

**Comment by infograf768** [comment]
The Purge button on Smart Search should not delete your contents, but only the data used for smart search (i.e. the contents of the _finder tables).

**Comment by ckubs** [comment]
@infograf768 Thanks for your response. Don't know what happened but my articles aren't completely deleted, but just missing from the frontend. Fortunatelly I managed to get my IP unbanned on Joomla( I didn'e even had an account on their forum before) and make an account there to post my issue. And in the meantime opened the edit page of an article that it was missing from the frontend, unpublished it, published again and now it appears. Since I have almost a hundred of them but my knowledge in that regard is limited I guess I have to do that with all of them, one by one.
