### ISSUE TITLE
Language Cookied

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#5639]
#### Steps to reproduce the issue
In the System - Language Filter plugin there is a option to set the cookie lifetime.

The tooltip says Default is a Year but I havent got a clue if that is correct from the screenshot.

![screen shot 2015-01-07 at 15 13 17](http://issues.joomla.org/uploads/1/be49611c182ea553223d787e30058f36.png)

**Comment by javigomez** [comment]
mmm, year has value 1: https://github.com/joomla/joomla-cms/blob/staging/plugins/system/languagefilter/languagefilter.xml#L57-L64 and it indeed uses a year: https://github.com/joomla/joomla-cms/blob/staging/plugins/system/languagefilter/languagefilter.php#L674

**Comment by brianteeman** [comment]
So this is wring then
https://github.com/joomla/joomla-cms/blob/staging/plugins/system/languagefilter/languagefilter.xml#L60

On 7 January 2015 at 21:27, javier gomez <notifications@github.com> wrote:

> mmm, year has value 1:
> https://github.com/joomla/joomla-cms/blob/staging/plugins/system/languagefilter/languagefilter.xml#L57-L64
> and it indeed uses a year:
> https://github.com/joomla/joomla-cms/blob/staging/plugins/system/languagefilter/languagefilter.php#L674
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5639#issuecomment-69095072>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by javigomez** [comment]
yup,
