### ISSUE TITLE
Show / Hide button or select

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#5641]
In the majority of screens where there are only two options eg show/hide option it is is a button group

But on some screens it is a select. IS there a reason for this that escapes me or is it a bug that should I create a PR for

![screen shot 2015-01-07 at 15 54 10](http://issues.joomla.org/uploads/1/ac4a15871660075bdb42bf5c0877de56.png)

![screen shot 2015-01-07 at 15 54 14](http://issues.joomla.org/uploads/1/03bd6298567ca51e9d33889fbb05fdfe.png)

**Comment by chrisdavenport** [comment]
I think it's a bug.

**Comment by brianteeman** [comment]
Me too but I wanted to be sure before creating a pr

**Comment by chrisdavenport** [comment]
Not sure, but I think some of them might have 3 options: Hide, show and Use global.  Should still be button groups though.

**Comment by brianteeman** [comment]
IIRC the decision was that if there were more than 2 options then it would
be a select

On 7 January 2015 at 22:04, Chris Davenport <notifications@github.com>
wrote:

> Not sure, but I think some of them might have 3 options: Hide, show and
> Use global. Should still be button groups though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5641#issuecomment-69100644>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by chrisdavenport** [comment]
Okay, fair enough.  The main thing is to be consistent.

**Comment by brianteeman** [comment]
exactly. The one thing I keep seeing is a default value in the xml that is
not the actual setting on a site with the test data installed ;(

On 7 January 2015 at 22:19, Chris Davenport <notifications@github.com>
wrote:

> Okay, fair enough. The main thing is to be consistent.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5641#issuecomment-69102930>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Looking through the code it looks like we have cases where if there were only two options eg LTR and RTL we could have a button group or a list. There doesnt appear to be much logic in the decision which to go for<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5641">issues.joomla.org/joomla-cms/5641</a>.</sub>

**Comment by mbabker** [comment]
For fields that are scanning for something (like the alternate layout ones), those should probably stay a list as there isn't a defined number of options for those.  In other places where there are only two options (and can only be two), I'd say making them consistent on a toggle is appropriate.

**Comment by brianteeman** [comment]
Yeah I was excluding ones that are dynamic. There are still about 30 that
seem to be arbitrary as a select. One possible reason that this was done in
some cases was because the text was long. Still not really sure thats a
valid reason.

In the Language Manager Edit Override for example there is a select box to
chose Value or Constant. It can never be anything other than those two. By
making it a Select it means two clicks to change the value.

On 7 January 2015 at 23:57, Michael Babker <notifications@github.com> wrote:

> For fields that are scanning for something (like the alternate layout
> ones), those should probably stay a list as there isn't a defined number of
> options for those. In other places where there are only two options (and
> can only be two), I'd say making them consistent on a toggle is appropriate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5641#issuecomment-69114666>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
When I looked at this issue in the past, I considered that we should if possible use list when the choice is not between Positive and Negative action, this because of the use of Green and Red colours when only 2 choices.
If we had a css that would use other colours, That would solve that issue.

**Comment by brianteeman** [comment]
That would be OK (I guess) if we consistently used that but we dont

On 8 January 2015 at 09:35, infograf768 <notifications@github.com> wrote:

> When I looked at this issue in the past, I considered that we should if
> possible use list when the choice is not between Positive and Negative
> action, this because of the use of Green and Red colours when only 2
> choices.
> If we had a css that would use other colours, That would solve that issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5641#issuecomment-69155903>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Please see #5641 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5641">issues.joomla.org/joomla-cms/5641</a>.</sub>
