### ISSUE TITLE
Menu Manager: Creation of new Menu Items fails, resets connection

### ISSUE THREAD

**Issue by 5prock3t** [joomla/joomla-cms#5642]
Steps to reproduce the issue

1) Open a menu in backend menu manager
 2) Choose to create a new item (any option, local articles or external web urls)
 4) Click Save or Save & Close

Expected result

Menu item should be created

Actual result

Save of menu item fails with web page connection reset

System information (as much as possible)

New install of Joomla 3.4.0-dev from GitHub 1/7/15

System Information
 
PHP Built On 	Windows Server 2012 R2 6.2 build 9200 (Unknown Windows version Standard Edition) i586
Database Version 	10.50.6000
Database Collation 	MSSQL UTF-8 (UCS2)
PHP Version 	5.4.24
Web Server 	Microsoft-IIS/8.5
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.4.0-dev Development [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0 

Additional comments

Spun up 3.4.0-dev to test fixes for Microsoft SQL server hosted Joomla with point release build and consider use with full release. Found setup completes but editing/creation of new menu items cannot be done, page resets.

**Comment by Chris-Sch** [comment]
I have the same problem with a Windows Server 2008 R2.

Have some one find a way to fix this issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5642">issues.joomla.org/joomla-cms/5642</a>.</sub>

**Comment by n9iels** [comment]
I cannot confirm this issue, so I think this was an issue on from your side.

Can you confirm this issue is solved now?

**Comment by brianteeman** [comment]
@n9iels were you testing with IIS and MSSQL ?

**Comment by n9iels** [comment]
No, didn't do that. I'm sorry, missed that part :)

**Comment by brianteeman** [comment]
Thought so ;)

On 10 October 2015 at 16:21, Niels van der Veer <notifications@github.com>
wrote:

> No, didn't do that. I'm sorry, missed that part :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5642#issuecomment-147099149>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Thank you for creating this but it would appear that this has been resolved elsewhere in the code base. If this is not correct then this can be re-opened

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5642">issues.joomla.org/joomla-cms/5642</a>.</sub>
