### ISSUE TITLE
List views: Success message is not visible for the resolution 'Mobile portrait (320x480)','Mobile landscape (480x320)' & 'Small tablet portrait (600x800)'

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5643]
I applied the patch #5627 and select box functionality is working fine, But an issue is coming due to this patch.
-**Success message is not visible**

-Go to user manager
-Block or unblock the user
-It will display a message, but that message will not be visible [UI Issue]

![screen shot 2015-01-07 at 23 33 26](http://issues.joomla.org/uploads/1/8c4f13250e47c0735d092ec1cf937756.png)![screen shot 2015-01-07 at 23 33 35](http://issues.joomla.org/uploads/1/d75eb4aaf7cff8fce9fe88714dff3771.png)![screen shot 2015-01-07 at 23 33 39](http://issues.joomla.org/uploads/1/58958abc389ad73daee546a63f7ce18d.png)

**Comment by infograf768** [comment]
Same issue when editing a user and Save and Close.

**Comment by brianteeman** [comment]
Please make sure you have completely cleared the browser cache on your
device

On 8 January 2015 at 09:45, infograf768 <notifications@github.com> wrote:

> Same issue when editing a user and Save and Close.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5643#issuecomment-69156879>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by aasimali** [comment]
@brianteeman 
-I have cleared the browser cache but the issue is still there.
-I also have tested the same in Incognito windows. issue still exist

![screenshot_2015-01-08-15-26-02](https://cloud.githubusercontent.com/assets/10045599/5660916/8dafeb72-974b-11e4-940e-
160dffd9ebcc.png)
![screenshot_2015-01-08-15-27-37](https://cloud.githubusercontent.com/assets/10045599/5660917/93fced9a-974b-11e4-9241-040d36466513.png)

**Comment by brianteeman** [comment]
Confirmed

On 8 January 2015 at 10:03, Aasim Ali <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman>
> -I have cleared the browser cache but the issue is still there.
> -I also have tested the same in Incognito windows. issue still exist
>
> [image: screenshot_2015-01-08-15-26-02]
> <https://cloud.githubusercontent.com/assets/10045599/5660916/8dafeb72-974b-11e4-940e-%0A160dffd9ebcc.png>
> [image: screenshot_2015-01-08-15-27-37]
> <https://cloud.githubusercontent.com/assets/10045599/5660917/93fced9a-974b-11e4-9241-040d36466513.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5643#issuecomment-69158892>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
I am going to close this here so it can be handled with the PR #5627 as it hasnt been merged yet<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5643">issues.joomla.org/joomla-cms/5643</a>.</sub>

**Comment by aasimali** [comment]
Okay.
Thank you @brianteeman  :)

**Comment by zero-24** [comment]
>I am going to close this here so it can be handled with the PR #5627 as it hasnt been merged yet

hmm i don't know how to fix it. The same issue is in lastest staging so i would vote to reopen here and handel it different. The mentiored PR only `adding back the select boxes` as i can't (don't know how) fix it. And it is unrealted to the PR/Changes. :smile:

**Comment by brianteeman** [comment]
Sorry for the confusion this is indeed unrelated to #5627 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5643">issues.joomla.org/joomla-cms/5643</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we finally have a PR for testing #9703<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5643">issues.joomla.org/joomla-cms/5643</a>.</sub>
