### ISSUE TITLE
 Menu Manager: Add Menu :: Display a correct error message for the better usability

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5648]
-Go to menu manager:Add menu
-Enter valid title
-Click on menu type text field, enter press button[keyboard space] Do not write anything
-click on save 
-Check the message, **It should be error message instead of warning, It should work same as article works**

 ![screen shot 2015-01-09 at 08 36 28](http://issues.joomla.org/uploads/1/fa294ced07958e32030a7968cd52dffc.png)
![screen shot 2015-01-09 at 08 36 40](http://issues.joomla.org/uploads/1/2493f45442c0955699d393a34064e97c.png)

**Comment by brianteeman** [comment]
I dont have a problem with this message

On 9 January 2015 at 14:38, Aasim Ali <notifications@github.com> wrote:

> -Go to menu manager:Add menu
> -Enter valid title
> -Click on menu type text field, enter press button[keyboard space] Do not
> write anything
> -click on save
> -Check the message, *It should be error message instead of warning, It
> should work same as article works*
>
> [image: screen shot 2015-01-09 at 08 36 28]
> <https://camo.githubusercontent.com/7ef731df73471b2fe56d2f77fe1ad4094d4b5032/687474703a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f66613239346365643037393538653332303330613739363863643532646666632e706e67>
> [image: screen shot 2015-01-09 at 08 36 40]
> <https://camo.githubusercontent.com/ccc3605d83fbc2cfd0be71a5953a1892ab6e19cf/687474703a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f32343933663435343432633039353536393964333933613334303634653937632e706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5648>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
