### ISSUE TITLE
Custom Module position not working: manual entered

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#5649]
#### Steps to reproduce the issue
With kunena you can add modules on some positions like: kunena_announcement

lists off all module positions:
http://www.kunena.org/docs/Module_Positions 

So when i go to module manager, selecting a module. I want to enter the position. but it isn't working. I typ kunena_announcement then i see: Add custom position "kunena_announcement" 
But it isn't creating a custom position.

#### Expected result

save the entered position

#### Actual result

Position not saved

#### System information (as much as possible)

J3.X

**Comment by brianteeman** [comment]
Works for me I use  this everyday. After typing the name press enter

**Comment by 810** [comment]
oh thnx brian, maybe its better to make button (btn-link) Add custom position "test2". so when you click on it, its saving the position.  without having to enter. 

Now users (me included) thinks when you entered the position it will saved automatically,

**Comment by brianteeman** [comment]
Feel free to submit a PR bjut you will also have to change the behaviour
for tags and maybe some other stuff

On 9 January 2015 at 14:58, Jelle Kok <notifications@github.com> wrote:

> oh thnx brian, maybe its better to make button (btn-link) Add custom
> position "test2". so when you click on it, its saving the position. without
> having to enter.
>
> Now users (me included) thinks when you entered the position it will saved
> automatically,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5649#issuecomment-69344377>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
The tooltip for this is completely wrong and is from Joomla 2.5

I will create a new one <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5649">issues.joomla.org/joomla-cms/5649</a>.</sub>

**Comment by brianteeman** [comment]
I have corrected the tooltip #5651 and am closing this at this time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5649">issues.joomla.org/joomla-cms/5649</a>.</sub>
