### ISSUE TITLE
Menu Manager: New Menu Item :: Menu item is getting created without title

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5650]
-Go to Menu Manager: New Menu Item
-Enter spaces in title (don't write anything') 
-Select menu item 
-save the menu item
-Check, menu item is getting created without title

![screen shot 2015-01-09 at 08 51 36](http://issues.joomla.org/uploads/1/3001ed4a2c02d5f693198ca18041a1af.png)
![screen shot 2015-01-09 at 08 51 47](http://issues.joomla.org/uploads/1/0c68e8017a23ba2de47bace607bd8afb.png)

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5650">issues.joomla.org/joomla-cms/5650</a>.</sub>

**Comment by kim07** [comment]
thanks

**Comment by thebeuving** [comment]
Pull request: https://github.com/joomla/joomla-cms/pull/5974<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5650">issues.joomla.org/joomla-cms/5650</a>.</sub>
