### ISSUE TITLE
Article manager- > Alignment of hits column and counts messed up

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#5658]
#### Steps to reproduce the issue
1. Go to the article manager
2. Article should be present with number of hits.

#### Expected result
The number of hits should be center aligned with the column
#### Actual result
Alignment is disturbed

#### System information (as much as possible)
chrome Version 39.0.2171.95 m
Joomla! 3.3.6 Stable [ Ember ] 01-October-2014
Joomla Platform 13.1.0 Stable![screen shot 2015-01-10 at 01 14 42](http://issues.joomla.org/uploads/1/f36306128897a6f98f22e96b1a81c7b6.png)

**Comment by pe7er** [comment]
Fix (Pull Request) https://github.com/joomla/joomla-cms/pull/5696<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5658">issues.joomla.org/joomla-cms/5658</a>.</sub>
