### ISSUE TITLE
Redirect Manager Administrator Search Functionality not working

### ISSUE THREAD

**Issue by puneet0191** [joomla/joomla-cms#5659]
I have found this issue in the latest, against the stagging branch, issue can be recreated by doing the following:
1) go to redirect Manager in the Administrator
2) click on new, and create a new link with following values: 
     srcURL: administrator/index.php/dummysrc11922476755
     destURL: administrator/index.php/dummydest11922476755
     status: Enabled
3) Click on save and close
4) Repeat step 2, 3 with different SRC, and DEST URls to create multiple entries.
5) Enter srcURL: administrator/index.php/dummysrc11922476755 in the search Field, select Filter as All and click on search button. 
6) Results are not filtered.

![image](https://cloud.githubusercontent.com/assets/3048593/5690797/d2b2231e-98c9-11e4-92bc-06a5eb2b896e.png)

**Comment by infograf768** [comment]
I confirm search is broken in redirect manager:
"Empty string passed to getElementById()."

**Comment by infograf768** [comment]
Supplementary information: The issue here is on Firefox Macintosh. Safari works fine.

**Comment by puneet0191** [comment]
The issue is also present on Chrome, Windows machine

**Comment by pe7er** [comment]
I confirm the issue on Chromium (=Chrome) & Iceweasel (=FireFox) on Debian 8

**Comment by thebeuving** [comment]
https://github.com/joomla/joomla-cms/pull/5972

**Comment by zero-24** [comment]
Closing here as we have a PR by @thebeuving --> https://github.com/joomla/joomla-cms/pull/5972 Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5659">issues.joomla.org/joomla-cms/5659</a>.</sub>

**Comment by javigomez** [comment]
thanks @thebeuving ^_^
