### ISSUE TITLE
While resizing the editor put the limit for the Height and Width

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#5660]
#### Steps to reproduce the issue
1 Go to the article manager, create new article.
2. Re-size the editor.

#### Expected result
1. Width & height should have some limit of re-sizing  

#### Actual result
View get disturbed if we increase the size.

#### Additional comments

![screen shot 2015-01-10 at 04 06 59](http://issues.joomla.org/uploads/1/f052b99ea23aa386dd8d3fdf8f9a5a1f.png)![screen shot 2015-01-10 at 04 06 59](http://issues.joomla.org/uploads/1/43165912732bb3a5e01560176fd1e7d5.png)

**Comment by zero-24** [comment]
confirmed @uthorat<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5660">issues.joomla.org/joomla-cms/5660</a>.</sub>

**Comment by infograf768** [comment]
What we can do is introduce the choice to resize only vertically. I can't think of something else.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5660">issues.joomla.org/joomla-cms/5660</a>.</sub>

**Comment by zero-24** [comment]
Agree make sense to me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5660">issues.joomla.org/joomla-cms/5660</a>.</sub>

**Comment by infograf768** [comment]
On it now.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/5680<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5660">issues.joomla.org/joomla-cms/5660</a>.</sub>

**Comment by uthorat** [comment]
Thank you for considering my test case.

I would like to test it,but dont know how ?
Can you provide me required information to test this issue

**Comment by zero-24** [comment]
@uthorat you can use com_patchtester

https://docs.joomla.org/Component_Patchtester_for_Testers

- install com_patchtester
- apply the patch
- test the function (new option on the tinymce plugin)
- report the result back to @infograf768 's PR #5680

**Comment by uthorat** [comment]
Okay thanks for the information  @infograf768  :)
Will get back to you with feedback


Warm Regards,
Umesh Thorat<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5660">issues.joomla.org/joomla-cms/5660</a>.</sub>

**Comment by zero-24** [comment]
Closing here as we have the PR by @infograf768 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5660">issues.joomla.org/joomla-cms/5660</a>.</sub>
