### ISSUE TITLE
Media Manager -> Parent folder should have hover effect,if we select the sub folders or files

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#5661]
#### Steps to reproduce the issue
1.Go to the media manager
2.Select the thumbnail view.
3.Go to any subfolder.

#### Expected result
parent folder should have hover effect ,if we select the child /sub folder / file.
user get the easy track for the folder.![screen shot 2015-01-10 at 05 29 36](http://issues.joomla.org/uploads/1/4d57516aa740aeee8e831d821ccf2cc2.png)

#### Actual result
Unable to track which folder we are selecting .
There is no any hover effect

**Comment by brianteeman** [comment]
Do you mean like this? That is what I have

![vj](https://cloud.githubusercontent.com/assets/1296369/5691450/9b812242-98be-11e4-8cdb-c16179b9a6b3.png)

**Comment by uthorat** [comment]
Yes, You are correct.

Now Click on any file ,the hover effect is gone from the parent folder.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5661">issues.joomla.org/joomla-cms/5661</a>.</sub>

**Comment by brianteeman** [comment]
Ah ok I see what you mean - you want some sort of visual indicator to show
which folder you are in active all the time

On 10 January 2015 at 11:54, umesh <notifications@github.com> wrote:

> Yes, You are correct.
>
> Now Click on any file ,the hover effect is gone from the parent folder.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/5661
> <http://issues.joomla.org/tracker/joomla-cms/5661>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5661#issuecomment-69453334>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by uthorat** [comment]
Yes.. You got my point .
Active window should have hover effect

**Comment by brianteeman** [comment]
Easier said than done unfortunately. There is no active element being set
from what I can see

On 10 January 2015 at 12:13, umesh <notifications@github.com> wrote:

> Yes.. You got my point .
> Active window should have hover effect
> On 10 Jan 2015 17:41, "Brian Teeman" <notifications@github.com> wrote:
>
> > Ah ok I see what you mean - you want some sort of visual indicator to
> show
> > which folder you are in active all the time
> >
> > On 10 January 2015 at 11:54, umesh <notifications@github.com> wrote:
> >
> > > Yes, You are correct.
> > >
> > > Now Click on any file ,the hover effect is gone from the parent
> folder.
> > > ------------------------------
> > > This comment was created with the J!Tracker Application
> > > <https://github.com/joomla/jissues> at
> issues.joomla.org/joomla-cms/5661
> > > <http://issues.joomla.org/tracker/joomla-cms/5661>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> https://github.com/joomla/joomla-cms/issues/5661#issuecomment-69453334>.
> >
> > >
> >
> >
> >
> > --
> > Brian Teeman
> > Co-founder Joomla! and OpenSourceMatters Inc.
> > http://brian.teeman.net/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/joomla/joomla-cms/issues/5661#issuecomment-69453763>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5661#issuecomment-69453821>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by uthorat** [comment]
Yes it's difficult to do this functionality. But its great that we got new
challenge :)

**Comment by brianteeman** [comment]
This issue has been resolved (in a different way) with #5722<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5661">issues.joomla.org/joomla-cms/5661</a>.</sub>
