### ISSUE TITLE
Media Manager -> If we are in home directory ,then hide the back button which is used to get home directory

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#5662]
#### Steps to reproduce the issue
1. Go to the Media Manager.
2. You see the back button on home directory

#### Expected result
Back button should not be present on home directory.

#### Actual result
Back button present on home directory.

**Comment by ashishsfb** [comment]
Yes, I also think back button should not be placed in home directory.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5662">issues.joomla.org/joomla-cms/5662</a>.</sub>

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/5704
