### ISSUE TITLE
Fatal Error with search statistics

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#5674]
#### Steps to reproduce the issue
1. In com_search options enable search statistics
2. in the front end perform various search
3. Set error reporting to maximum
4. open com_search - you might need to press search results but eventually you will get
`Fatal error: Call to undefined method JApplicationAdministrator::getParams() in components/com_tags/models/tag.php on line 173`

As this completely breaks com_search I am marking this priority 2 according to the docs

**Comment by brianteeman** [comment]
Here is a video 

https://www.dropbox.com/s/5onz39546941r09/search-fatal-error.mp4?dl=0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5674">issues.joomla.org/joomla-cms/5674</a>.</sub>

**Comment by zero-24** [comment]
Closing if four of this PR: https://github.com/joomla/joomla-cms/pull/5675<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5674">issues.joomla.org/joomla-cms/5674</a>.</sub>
