### ISSUE TITLE
False link generation on the Frontend `List Contacts in a Category` view

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#5678]
#### Steps to reproduce the issue

- install staging or 3.3.6 with testing samepledata
- create 2 menu entrys that use the view `List Contacts in a Category` with the category `Sample Data-Contact` (e.g. at the `top` navigation)
- name the first `public` and the other `registerd` (only for better understanding :smile:)
- hide some information for the `public` menu entry (e.g. `Contact's Position` `Email` `Street Address` or others)
- access the `public` view.
- all works ok the information are hidden
- access the `registerd` menu link
- nothing works as it is the same link as for the `public` menu entry.

Example links (public; works ok)
http://www.example.com/index.php/orchester/mitwirkende (public view with hidden information)
Click on one list entry:
http://www.example.com/index.php/orchester/mitwirkende/2-name-vorname (public view with hidden information)

(registerd; dont work)
http://www.example.com/index.php/intern/mitgliederverzeichnis/ (same category but without hidden information)
Click on one list entry:
http://www.example.com/index.php/orchester/mitwirkende/12-name-vorname (false link as this is with hidden infos)
correct link (that works ok)
http://www.example.com/index.php/intern/mitgliederverzeichnis/12-name-vorname

#### Expected result

Links like `http://www.example.com/index.php/intern/mitgliederverzeichnis/12-name-vorname` for the internal `registerd` menu entry instead of `http://www.example.com/index.php/orchester/mitwirkende/12-name-vorname`

#### Actual result

False link that move to the `public` information (some are hidden e.g.)

current / false link (on the registed view): `http://www.example.com/index.php/orchester/mitwirkende/12-name-vorname`
expected link: `http://www.example.com/index.php/intern/mitgliederverzeichnis/12-name-vorname`

#### Additional comments

works ok on 2.5.x

#### Joomla Bugs Reference

http://www.joomla-bugs.de/forum/index.php?topic=639.msg3018#msg3018

**Comment by richard67** [comment]
@zero-24 Is the test description correct?
The URLs for the registered menu item contain a folder "intern", but in your test instruction is nothing about "intern": The name you suggested is "registerd" (mind the missing "e" between "r" and "d"), and so the alias will also be "registerd", if nothing else entered, and so where shall the "intern" come from?
And the name "public" of the public one does not occur in any of the URLs. Instead of this, "orchester" is used in the URLs. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5678">issues.joomla.org/joomla-cms/5678</a>.</sub>

**Comment by zero-24** [comment]
@richard67 
Yes the links are corrcet. These are `real live` examples how this can look. (see JB Reference) 

Here the links as per example:
Example links (public; works ok)
`http://www.example.com/index.php/public` (public view with hidden information)
Click on one list entry:
`http://www.example.com/index.php/public/34-park-site/2-webmaster` (public view with hidden information)

(registerd; dont work)
`http://www.example.com/index.php/registerd` (same category)
Click on one list entry:
`http://www.example.com/index.php/public/34-park-site/2-webmaster` (false link as this is with hidden infos)
correct link (that works ok)
`http://www.example.com/index.php/registerd/34-park-site/2-webmaster`
