### ISSUE TITLE
component language can not load

### ISSUE THREAD

**Issue by maihuayi** [joomla/joomla-cms#5681]
#### Steps to reproduce the issue
if the language file have this line.

COM_XXX_WEIBO_QQ_NO_ENABLE="XXX"

then component language can not be load. 
if drop this line,then this component language can load.

#### Expected result
component language can load.

#### Actual result
component language can not load

#### System information (as much as possible)
joomla3.3

**Comment by brianteeman** [comment]
Please try without using _QQ_ in the string as that has special meaning and
is replaced by &quot;

On 12 January 2015 at 10:03, maihuayi <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> if the language file have this line.
>
> COM_XXX_WEIBO_QQ_NO_ENABLE="XXX"
>
> then component language can not be load.
> if drop this line,then this component language can load.
> Expected result
>
> component language can load.
> Actual result
>
> component language can not load
> System information (as much as possible)
>
> joomla3.3
> Additional comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5681>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by maihuayi** [comment]
Hello
I droped "QQ", the component language file can be loaded.:))
Thank you!
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5681">issues.joomla.org/joomla-cms/5681</a>.</sub>
