### ISSUE TITLE
Inline style in com_media

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#5684]
In `com_media there is some inline style https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_media/views/media/tmpl/default.php#L24

Any reason that this can not be moved to the template css?

I couldn't see any other inline styles excepts in template overrides

**Comment by losedk** [comment]
Hmm are the two classes even used anywhere?

**Comment by brianteeman** [comment]
I couldnt find them - but perhaps with the progress bar for file uploads -
I dont know

On 12 January 2015 at 13:50, Peter Lose <notifications@github.com> wrote:

> Hmm are the two classes even used anywhere?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5684#issuecomment-69571813>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Buddhima** [comment]
Hi,
I think it's relevant to flash image uploader which was removed.
Thank You!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5684">issues.joomla.org/joomla-cms/5684</a>.</sub>

**Comment by brianteeman** [comment]
Oh goodie so it can be removed then

On 14 January 2015 at 04:53, Buddhima Wijeweera <notifications@github.com>
wrote:

> Hi,
> I think it's relevant to flash image uploader which was removed.
> Thank You!
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/5684
> <http://issues.joomla.org/tracker/joomla-cms/5684>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5684#issuecomment-69869043>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
See #5724 for PR to remove these useless inline styles<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5684">issues.joomla.org/joomla-cms/5684</a>.</sub>
