### ISSUE TITLE
Administration system Information -> check the alignment . text get outside the template

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#5686]
#### Steps to reproduce the issue
1. Go to the System Information
2. Php setting

#### Expected result
Text ![screen shot 2015-01-12 at 08 15 59](http://issues.joomla.org/uploads/1/bbaa93ec734c372e5270acc21bb88431.png)should be in template size and the exceed text should start with the new line

#### Actual result
Exceed the template.

**Comment by brianteeman** [comment]
Can you provide a screenshot please to avoid misunderstanding? Right now I
dont see what the issue is from your description

On 12 January 2015 at 14:15, umesh <notifications@github.com> wrote:

> Steps to reproduce the issue
>
>    1. Go to the System Information 2.Php setting
>
> Expected result
>
> Should be in template size and the exceed text should start with the new
> line
> Actual result
>
> Exceed the template.
> System information (as much as possible) Additional comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5686>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by uthorat** [comment]
Please check 

Sorry for the inconvenience !!! 

![Uploading Template Manager  Edit Style.png . . .]()

**Comment by uthorat** [comment]
![template manager edit style](https://cloud.githubusercontent.com/assets/10463754/5704332/71231ada-9a96-11e4-9fe5-b81ab5d312ef.png)

**Comment by uthorat** [comment]
Sorry for the inconvenience !!!! 

![administration system information](https://cloud.githubusercontent.com/assets/10463754/5704347/a133ae42-9a96-11e4-8ef1-38f6239187ae.png)

**Comment by brianteeman** [comment]
OK so this is two separate issues 
1. Line length and not wrapping on the system information page
2. Toggle selection which you have created a separate issue for?
(Thats why it is best to always submit one issue for every different report)

I will do a pull request to fix the line length wrap - thanks for reporting it
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5686">issues.joomla.org/joomla-cms/5686</a>.</sub>

**Comment by losedk** [comment]
We can just add the class break-word introduced by #5525

**Comment by brianteeman** [comment]
Yes that's what I will do. Just haven't been able to setup my local php to
disable functions so I can test

**Comment by brianteeman** [comment]
See #5697 for a fix - please test.

Note you can only test this with the staging branch as it relies on a recent commit<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5686">issues.joomla.org/joomla-cms/5686</a>.</sub>

**Comment by uthorat** [comment]
I Checked this patch .
I didn't see any changes here.
The disable functions word is not breaking. If you change the screen resolution then only you can see the effect.

I checked on following resolution
1280 x 1024
1366 x 768

Is anything I am missing ?
Please provide us the information.
