### ISSUE TITLE
Edit template -> Is needed 2 same option of  "Toggle Selection" in template manager for site templates

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#5687]
#### Steps to reproduce the issue
1. Go to the template manager.
2. Open the site template
3. Go to the menus assignment

#### Expected result
Should have only one option of toggle selection

#### Actual result
There are 2 same option which works same.![screen shot 2015-01-12 at 08 26 49](http://issues.joomla.org/uploads/1/9a5227d99fb2e85a4f1b1b817c3500f2.png)

**Comment by brianteeman** [comment]
Go to a site with more than one menu and you will see.

**Comment by uthorat** [comment]
@brianteeman 
Thanks for the clarification.

Don't you think ,we should add  tool-tip about that buttons for the better usability purpose ?

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5687">issues.joomla.org/joomla-cms/5687</a>.</sub>

**Comment by brianteeman** [comment]
Feel free to submit a pull request

**Comment by Margreet137** [comment]
question: is there a status update of this issue?
I think maybe it is a suggestion to change the name of the first button in something like Toggle all selections.
Because this is what this button does.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5687">issues.joomla.org/joomla-cms/5687</a>.</sub>

**Comment by zero-24** [comment]
>I think maybe it is a suggestion to change the name of the first button in something like Toggle all selections.

@Margreet137 can you submit a pull request? see: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by uthorat** [comment]
@Margreet137 Yes. Change the text or provides the appropriate tooltip for this.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5687">issues.joomla.org/joomla-cms/5687</a>.</sub>

**Comment by uthorat** [comment]
@Margreet137 
I am not geek like you :) I have tried but cant make it. 
Can someone submit a pull request on the behalf of me ;)
![template](https://cloud.githubusercontent.com/assets/10463754/9130202/1aa4bfdc-3cfe-11e5-865f-ccfcc865e612.png)

**Comment by brianteeman** [comment]
I will look and see if I can change the text of the first toggle as
suggested.

**Comment by uthorat** [comment]
@brianteeman Thank you :)

**Comment by brianteeman** [comment]
Please see and test #7650 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5687">issues.joomla.org/joomla-cms/5687</a>.</sub>
