### ISSUE TITLE
Global Configuration:: Unwantedly application is forcing to enter the SMTP Port number

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5688]
-Go to 'Global Configuration'> 'Server'
-Select **SMTP** in Mailer drop-down option
-Do not enter smtp port, click on save button

--------------------------------------------
-Now change the option from SMTP to PHP Mail
-Enter all the required field and save it.
-**Application will force to enter the smtp port number, which is not the part of PHP Mail**
![screen shot 2015-01-12 at 09 05 10](http://issues.joomla.org/uploads/1/5d24f0b9d43dfe9251452f8f60120a28.png)

**Comment by brianteeman** [comment]
I cant replicate this as SMTP port has a default value of 25 already entered and it is not possible to save it without any value so I cannot follow your instructions. Can you please retest<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5688">issues.joomla.org/joomla-cms/5688</a>.</sub>

**Comment by brianteeman** [comment]
Are you installing using the joomla installer as this is what places the default value of 25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5688">issues.joomla.org/joomla-cms/5688</a>.</sub>

**Comment by aasimali** [comment]
No, I am not installing using joomla installer.
It is something a part of negative testing! You can only reproduce the issue, If you'll follow all the steps.
Thanks.

**Comment by aasimali** [comment]
Even! If you keep 'smtp port' blank, and click on '**Cancel**' button. It does not work.

**Comment by brianteeman** [comment]
And I can only break things if I don't follow the instructions. Sorry but I
just dont see the point in this

On 14 January 2015 at 13:48, Aasim Ali <notifications@github.com> wrote:

> Even! If you keep 'smtp port' blank, and click on '*Cancel*' button. It
> does not work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5688#issuecomment-69917739>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by aasimali** [comment]
Okay! No problem!
I have a very simple scenario for you! Anybody can stuck in it.

**-Go to 'Global Configuration'> 'Server'
  -Select SMTP in Mailer drop-down option
  -Do not enter smtp port (keep blank), click on CANCEL button**

**Comment by brianteeman** [comment]
That is because it is a required field and it will ALWAYS have data in it
if Joomla is installed correctly - so you can not keep it blank

Leaving it to others now - I am not wasting my time on issues that cant
happen in the real world. For me it is the same as saying Joomla doesnt
work if I dont have a database



On 14 January 2015 at 14:06, Aasim Ali <notifications@github.com> wrote:

> Okay! No problem!
> I have a very simple scenario for you! Anybody can stuck in it.
>
>
>
> *-Go to 'Global Configuration'> 'Server' -Select SMTP in Mailer drop-down
> option -Do not enter smtp port (keep blank), click on CANCEL button*
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5688#issuecomment-69920027>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Not sure but please see if #5738 resolves this for you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5688">issues.joomla.org/joomla-cms/5688</a>.</sub>

**Comment by brianteeman** [comment]
Closing this at this time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5688">issues.joomla.org/joomla-cms/5688</a>.</sub>
