### ISSUE TITLE
Install from Web: images broken

### ISSUE THREAD

**Issue by nonumber** [joomla/joomla-cms#5689]
Ever since the new JED has gone live, the images in the 'Install from Web' in Joomla 3 have been broken.
The JED was already made aware of this just after launch weeks ago, and far before that BEat (who seems to be the one responsible for the 'Install from Web' part) was notified about the pending changes in the API/connection.

Still this issue is not fixed.

Personally I find it pretty bad marketing to have a broken feature like this in all Joomla 3 installs.
No idea who should fix it or how (as it is not on github, afaik).
And no idea how to get the attention of the people who do know.
Hope posting this issue helps...

![screen shot 2015-01-12 at 09 14 07](http://issues.joomla.org/uploads/1/21bc9d38dfab4482378fa45151cd7531.png)

**Comment by aasimali** [comment]
Yes! I also saw that issue before. The issue is there in stable 3.3.6 & also on staging 3.4-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5689">issues.joomla.org/joomla-cms/5689</a>.</sub>

**Comment by PhilETaylor** [comment]
Confirmed. I see this issue too but I doubt there is anything I can do about it ;-) 

The Image urls being like this http://extensionscdn.joomla.org/components/com_mtree/img/listings/s/40281.png which is a 404 page 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5689">issues.joomla.org/joomla-cms/5689</a>.</sub>

**Comment by nonumber** [comment]
The issue will be on all Joomla 3 setups, regardless of the version.
The entire 'Install from Web' block is loaded from an external source.

**Comment by mbabker** [comment]
It's a [known issue](https://github.com/joomla-extensions/install-from-web-client/issues/10) and is being worked out by the JED team and the folks maintaining the Install from Web feature (see [the JED tracker](https://joomlaextensionsdirectory.atlassian.net/browse/JDEV-588) for the latest updates).

**Comment by Kubik-Rubik** [comment]
This MUST be fixed as soon as possible. I'm already in contact with the people in charge!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5689">issues.joomla.org/joomla-cms/5689</a>.</sub>
