### ISSUE TITLE
Extension Manager: Install>Install from web:: Loader missing, when we change the value in 'Sort by opportunity' filter in grid view

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5690]
-Go to 'Extension Manager: Install>Install from web'
-Select Grid View 
-Change the value from 'Sort by opportunity' to Sort by rating, name etc

**Please check this in incognito windows/Private window to understand it in better way**

![screen shot 2015-01-12 at 09 16 01](http://issues.joomla.org/uploads/1/bfbc057dae5ab6a42aa1acf650f91d18.png)

**Comment by brianteeman** [comment]
The Install from web plugin is not part of the core and has its own issue tracker (confusing I know) please can you open an issue there https://github.com/joomla-extensions/install-from-web-plugins<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5690">issues.joomla.org/joomla-cms/5690</a>.</sub>

**Comment by aasimali** [comment]
Yeah! Sure will report it there. :)
Thanks
