### ISSUE TITLE
Extension Manager: Install>Install from web:: Add tooltip for View (Grid view & List view)

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5691]
-Refer screenshot to understand it in a better way
![screen shot 2015-01-12 at 09 22 35](http://issues.joomla.org/uploads/1/c0b50231f82d02569e37fd785628d422.png)

**Comment by losedk** [comment]
I think the icons are self explanatory

**Comment by brianteeman** [comment]
This plugin is not part of the core - please raise an issue on the Install from web plugin repository https://github.com/joomla-extensions/install-from-web-plugins<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5691">issues.joomla.org/joomla-cms/5691</a>.</sub>
