### ISSUE TITLE
Back-end: Login view:: Can we slightly change the warning message, If username & password are blank

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5692]
-Go to  sitename/administrator
-Keep both fields blank(username & password)
-Click on Login button
-Application will display a message, which is good but not so much usable

-message should be: Warning: **Empty username and password  not allowed** 
![screen shot 2015-01-12 at 09 31 05](http://issues.joomla.org/uploads/1/900fbeaf6abfdec2821b52cd1c76608d.png)

**Comment by brianteeman** [comment]
It isnt as simple as changing the string<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5692">issues.joomla.org/joomla-cms/5692</a>.</sub>

**Comment by aasimali** [comment]
@brianteeman 
Yes! I understand. You have to validated it on login trigger before to display this message

**Comment by brianteeman** [comment]
Being realistic there is little chance of someone writing the code required to resolve this edge case so I am closing it. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5692">issues.joomla.org/joomla-cms/5692</a>.</sub>
