### ISSUE TITLE
mysqli_close(); warning in every page with the latest staging

### ISSUE THREAD

**Issue by dgt41** [joomla/joomla-cms#5695]
I get a warning on every page: 
Warning: mysqli_close(): Couldn't fetch mysqli in /Applications/MAMP/htdocs/libraries/joomla/database/driver/mysqli.php on line 209

![screen shot 2015-01-12 at 10 42 12](https://cloud.githubusercontent.com/assets/3889375/5710677/d29123b4-9aac-11e4-95c6-60c613a2dc7c.png)

Setting
 
PHP: Built On	Darwin MacBook-Pro.local 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64

Database Version: 5.5.38
Database Collation:	utf8_general_ci
PHP Version:	5.5.18
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.4.0-dev Development [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/600.2.5 (KHTML, like Gecko) Version/8.0.2 Safari/600.2.5

**Comment by zero-24** [comment]
@dgt41 I'm unable to confirm (using a `live server` and no MacBook) Can you try a clean install?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5695">issues.joomla.org/joomla-cms/5695</a>.</sub>

**Comment by dgt41** [comment]
This seems be an awkward error in my setup. I cannot replicate this anymore, thus I am closing it!
