### ISSUE TITLE
Users -> Mass mail user -> Editor should have fixed height & width

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#5699]
#### Steps to reproduce the issue
1. Go to the Users
2. Select the Mass mail user
3. Change the height and width of editor.

#### Expected result
Editor should have the fixed height and width.

#### Actual result
If you change the editor size, view get disturbed. 
Please refer the snap.

#### Additional comments
![screen shot 2015-01-12 at 23 55 11](http://issues.joomla.org/uploads/1/86ab7c474a1b1933149f874d1b45613b.png)

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5699">issues.joomla.org/joomla-cms/5699</a>.</sub>

**Comment by brianteeman** [comment]
this is not an issue in IE as its not resizable The only way I know how to do this is with css3 `resize:none`
[source](http://davidwalsh.name/textarea-resize)

Now to work out how to use the less files to create a PR


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5699">issues.joomla.org/joomla-cms/5699</a>.</sub>

**Comment by brianteeman** [comment]
OK looks like I did it the correct way not as above

Please test #5721 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5699">issues.joomla.org/joomla-cms/5699</a>.</sub>
