### ISSUE TITLE
Module Manager -> Ordering is not getting saved

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#5702]
#### Steps to reproduce the issue
1. Go to the module manager
2. Click on ordering
3. Set the order.
4. Surf the other options ( I mean go to the other manager i.e template or plugin manager)
5. Again come to the module manager ,you will see the by default ordering 
#### Expected result
The ordering which we set should be applied

#### Actual result
By default ordering get applied

#### Additional comments

![screen shot 2015-01-13 at 01 04 53](http://issues.joomla.org/uploads/1/7919b75f194728d4c033d7394c46ad54.png)

**Comment by infograf768** [comment]
I do not confirm this.
Do not forget to filter by position when you want to see the order.

**Comment by uthorat** [comment]
Okay !!!
If this Manually set order is not getting saved, then why are you using this functionality.

It's great if we do this.
You can check in the plugin manager ,the ordering is getting saved.

**Comment by infograf768** [comment]
The order of the modules is relative to their position. The order is saved all right.
In the plugin manager, there is no position.

**Comment by brianteeman** [comment]
I also have no problem with this feature. To avoid confusion I have made a quick video

https://www.dropbox.com/s/7p4kiow18him4yi/moduel-positions.mp4?dl=0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5702">issues.joomla.org/joomla-cms/5702</a>.</sub>

**Comment by uthorat** [comment]
Got the point @brianteeman 

Thanks for the video ;) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5702">issues.joomla.org/joomla-cms/5702</a>.</sub>

**Comment by brianteeman** [comment]
So can I close this?

**Comment by uthorat** [comment]
Yes sure .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5702">issues.joomla.org/joomla-cms/5702</a>.</sub>
