### ISSUE TITLE
problem with joomla image display

### ISSUE THREAD

**Issue by hdmd4allz** [joomla/joomla-cms#5705]
hello everyone...
i need helps here with joomla ver 3.3.6

i want to link/show image using custom html
but when i click save and preview..the image not showing. 
only showing the words/script
when i check it back the coding/script its add " \ " to the script/coding.

example:
i put this script/coding to custom html

<a href="http://www.newmovie.com/f27/unbroken-2014- /"> <img title="Unbroken (2014)" src="http://s7.postimg.org/vepkfmenv/Unbroken_2014_dvd.jpg" style="padding:5px" alt="Unbroken (2014) " border="0" height="170" width="120"></a>

after i save the script/coding its become like this

<a href=\"http://www.newmovie.com/f27/unbroken-2014- /\"> <img title=\"Unbroken (2014)\" src=\"http://s7.postimg.org/vepkfmenv/Unbroken_2014_dvd.jpg\" style=\"padding:5px\" alt=\"Unbroken (2014) \" border=\"0\" height=\"170\" width=\"120\"></a>

and the image wont appears because of those " \ "

Anyone can helps me solve this problem? pls tells me how to fixed it.

**Comment by brianteeman** [comment]
Please use forum.joomla.org for support.
