### ISSUE TITLE
Joomla 3.4.0_dev installfile action

### ISSUE THREAD

**Issue by thinkerytim** [joomla/joomla-cms#5710]
I have a component manifest / installfile that is working fine for install / update with any Joomla < 3.4.

Upgrading Joomla to the `3.4.0_dev` release to test my stuff against the new code presents a problem.

When I dump the `$action` parameter in the `preflight`, it is always `install`, never `upgrade` even when the component has been successfully installed already. This results in multiple duplicate component installs (eg. there will be 4-5 'com_mycomponent' entries in the manage extensions list). It seems that for some reason the installer isn't recognizing the component is already installed.

As I said, the same file works fine with Joomla up to 3.3.6, and installs or upgrades appropriately.

**Comment by mbabker** [comment]
Would you be able to test https://github.com/joomla/joomla-cms/pull/5677?  I know a couple small regressions slipped in, which were addressed in that PR alongside cleaning up the update path, but I've not yet seen any issues with the route being set incorrectly.

**Comment by thinkerytim** [comment]
That patch does seem to resolve the issue. Thanks

**Comment by zero-24** [comment]
Thanks for the crosstest @thinkerytim so i closing here. Can you add your successful test there with a comment in #5677 ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5710">issues.joomla.org/joomla-cms/5710</a>.</sub>
