### ISSUE TITLE
Question Code Style - line break syntax

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#5711]
I checked the coding style guide http://joomla.github.io/coding-standards/?coding-standards/chapters/html.md and I couldn't see an answer. 

Which of the following is correct for joomla code style so we are consistent
`<br/> <br> <br />`

**Current Staging contains**
`<br>` 9 (in vendor libraries)  
`<br/>` 26 in 10 files  
`<br />` 111 in 51 files  

Happy to do the PR to make it consistent just need to know what it should be.

**Comment by zero-24** [comment]
@brianteeman 

I think `<br>` is a good solution for html but it don't work for xhtml (<- but I'm not sure if we use any xhtml.)

Here are some resorces:
http://stackoverflow.com/questions/1946426/html-5-is-it-br-br-or-br

It is also supported for all our supported browsers:
http://www.w3schools.com/tags/tag_br.asp<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5711">issues.joomla.org/joomla-cms/5711</a>.</sub>

**Comment by mbabker** [comment]
I really don't remember if we were aiming to be XHTML compliant or not, but that should weigh in on things.  As far as personal preference goes, I lean towards `<br />`.

**Comment by rdeutz** [comment]
Protostar is xhtml so <br /> would be correct, <br /> is also allowed in HTML5. I would use <br /> (with a space between r and /

**Comment by brianteeman** [comment]
Ok I will prepare a PR for `<br />`

Is someone able to document it on the code style documentation?

On 13 January 2015 at 19:30, Robert Deutz <notifications@github.com> wrote:

> Protostar is xhtml so
> would be correct,
> is also allowed in HTML5. I would use
> (with a space between r and /
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5711#issuecomment-69804032>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
See #5713 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5711">issues.joomla.org/joomla-cms/5711</a>.</sub>

**Comment by zero-24** [comment]
>Is someone able to document it on the code style documentation?

done can you have a look into it?

https://github.com/joomla/coding-standards/pull/94

**Comment by brianteeman** [comment]
Thanks @zero-24

On 13 January 2015 at 21:10, zero-24 <notifications@github.com> wrote:

> Is someone able to document it on the code style documentation?
>
> done can you have a look into it?
>
> joomla/coding-standards#94
> <https://github.com/joomla/coding-standards/pull/94>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5711#issuecomment-69820667>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
