### ISSUE TITLE
Module Manager: Modules :: 'Trash' button is not working as expected, Even, I am confused! How could you trash a module? Which is already trashed.

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5726]
-**Go to ' Module Manager: Modules'
-Trash a module
-Go to trash module list (select status=trash in drop-down)
-Check trash module will have a button 'Trash'
-Finding it difficult to understand the functionality that button.**

![screen shot 2015-01-14 at 07 26 38](http://issues.joomla.org/uploads/1/915bd8673822b52b520d542a09d86283.png)

**Comment by brianteeman** [comment]
I can confirm that it doesnt do anything

**Comment by JoomliC** [comment]
Hi!

I have created a PR with a fix : https://github.com/joomla/joomla-cms/pull/5730

Cyril<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5726">issues.joomla.org/joomla-cms/5726</a>.</sub>

**Comment by zero-24** [comment]
Closing here as we have a PR: https://github.com/joomla/joomla-cms/pull/5730<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5726">issues.joomla.org/joomla-cms/5726</a>.</sub>
