### ISSUE TITLE
Notice: Undefined index: published in C:\wamp\www\joomla\libraries\cms\helper\tags.php on line 888

### ISSUE THREAD

**Issue by vzenix** [joomla/joomla-cms#5732]
#### Steps to reproduce the issue
Use the funcion JHelperTags::searchTags() in component whithout param.

#### Expected result
Function to search tags

#### Actual result
Notice: Undefined index: published in C:\wamp\www\joomla\libraries\cms\helper\tags.php on line 888

#### System information (as much as possible)
Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT 

#### Additional comments
Fix: Change line 888:
if (is_numeric($filters['published']))
to
if ( isset($filters['published']) && is_numeric($filters['published']) )

**Comment by zero-24** [comment]
@vzenix can you submit your fix as pull request?

If you need help see here: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

Thanks.

**Comment by zero-24** [comment]
@vzenix it is this line in staging https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/helper/tags.php#L921

**Comment by vzenix** [comment]
I do, thanks

https://github.com/joomla/joomla-cms/pull/5733
