### ISSUE TITLE
Language filter does not work for categories

### ISSUE THREAD

**Issue by toslan** [joomla/joomla-cms#5734]
#### Steps to reproduce the issue

Assume you have a multilanguage site with Lang1 and Lang2 languages activated in frontend. You have 2 menus to show content in Lang1 and Lang2 languages: MenuLang1 and MenuLang2. Create new category CatLang1 in backend category manager and assign Lang1 to it. Create new article ArtLang2 in this category and assign Lang2 to it. Add menu item showing just added category blog to each of menus (MenuLang1 and MenuLang2).

#### Expected result

On frontend only MenuLang1 item should show CatLang1 category but MenuLang2 should filter it out. No articles should be shown in CatLang1 since ArtLang2 has wrong language.

#### Actual result
Both MenuLang1 and MenuLang2 shows CatLang1 category. CatLang1 in MenuLang2 shows ArtLang2. Category is not filtered by language. 

#### System information (as much as possible)

Database Version 	5.5.41-log
Database Collation 	utf8_general_ci
PHP Version 	5.3.29
Web Server 	Apache/2.2.29 (Win32)
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by JoomliC** [comment]
Created a PR with a fix to be tested ;-)
https://github.com/joomla/joomla-cms/pull/5740

Thank you!
Cyril
