### ISSUE TITLE
Extension Manager: Update :: 'Update' button should be in disabled state, If there are no updates available

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5737]
**Pre-requisites: Update should not available**

-Go to 'Extension Manager: Update'
-Click on Update button
-It will ask to select an option

![screen shot 2015-01-15 at 07 34 26](http://issues.joomla.org/uploads/1/86b317e954efe3bbfe7671bb530be148.png)

**Comment by aasimali** [comment]
![screen shot 2015-01-15 at 07 39 45](http://issues.joomla.org/uploads/1/9641a4168085b9349262145e0fe2f7c4.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5737">issues.joomla.org/joomla-cms/5737</a>.</sub>

**Comment by mbabker** [comment]
This isn't a simple task.  Our toolbar code doesn't really support states at all right now, and it isn't just this view that has the issue.  If someone wants to take on a project adding this type of support, I'm sure people would welcome it, but with what we have in the code base at this very moment it isn't something that can be accomplished.

**Comment by zero-24** [comment]
@mbabker is this a starting point? https://github.com/joomla/joomla-cms/pull/2111

**Comment by mbabker** [comment]
Yes and no.  That PR very specifically focuses on an implementation in the Isis template to show/hide buttons based on selected items.  A more complete solution would be to enhance the underlying toolbar code to define states for toolbar buttons during loading, this way anyone using the toolbar API would be able to have this feature available.

**Comment by brianteeman** [comment]
I am closing this PR as we have a PR to address this #7592 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5737">issues.joomla.org/joomla-cms/5737</a>.</sub>
