### ISSUE TITLE
Extension Manager: Install Languages:: Incorrect Label name Header

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5749]
**-Go to Extension manager> Install Languages
-Check Name on header 
-It should be same as 'Extension manager: Install ,'Extension manager: Manage,'Extension    manager: Update', 'Extension manager: Discover etc
-They all should have same naming convention**

![screen shot 2015-01-16 at 03 30 10](http://issues.joomla.org/uploads/1/dc5b434ace29819517f2c7258533cbca.png)

**Comment by zero-24** [comment]
@brianteeman is this fixed with your `mega patch`?

**Comment by brianteeman** [comment]
Yes and it can be closed here

On 16 January 2015 at 09:45, zero-24 <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> is this fixed with your mega
> patch?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5749#issuecomment-70230170>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
Closing as per comment by @brianteeman Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5749">issues.joomla.org/joomla-cms/5749</a>.</sub>

**Comment by aasimali** [comment]
@brianteeman 
I hope this one will also be resolved in your mega patch?

-Extension Manager: Check Database (Incorrect name on header)
![extension manager database](https://cloud.githubusercontent.com/assets/10045599/5788415/636d0230-9e5a-11e4-92b5-3f450ab7b761.png)

**Comment by zero-24** [comment]
@aasimali oops yes your are right there are not fixed with @brianteeman 's mega patch: https://github.com/joomla/joomla-cms/pull/5615 here is a PR that fix it: https://github.com/joomla/joomla-cms/pull/5784

**Comment by aasimali** [comment]
@zero-24 
Thank you :smile:
