### ISSUE TITLE
Extension Manager: Install Languages:: Display the  'No matching Results' message , If there search result not exist

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5750]
-Go to extension manager>Install Languages
-Search an invalid keyword
-Ideally, application should display a message **'No matching Results'**

![screen shot 2015-01-16 at 03 35 49](http://issues.joomla.org/uploads/1/b050dec61a6adc0a4f1fe028ff5ff2e4.png)![screen shot 2015-01-16 at 03 35 54](http://issues.joomla.org/uploads/1/901343c2d2a118c8162209a8786c121c.png)

**Comment by zero-24** [comment]
Confirmed; And Closing as we have a pull request. Can you have a look into it? https://github.com/joomla/joomla-cms/pull/5751<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5750">issues.joomla.org/joomla-cms/5750</a>.</sub>
