### ISSUE TITLE
Duplicated functionality adds UI clutter and damages UX

### ISSUE THREAD

**Issue by nternetinspired** [joomla/joomla-cms#5754]
This relates somewhat to the ongoing discussion in https://github.com/joomla/joomla-cms/issues/5522 and, in particular, my opinion that extraneous options should be removed in order to improve the admin UI.

In all list views the search tools bar contains a filter which allows the table to be sorted according to a particular table header, though table views can already be sorted by simply clicking the table header in question (an action which I believe is more intuitive). This means we have two separate methods to perform *exactly the same function*: 

![screen shot 2015-01-16 at 11 25 11](https://cloud.githubusercontent.com/assets/1090182/5775557/6175ffe6-9d73-11e4-9efb-c6f400d8d8e4.png)

In a UI where we already have a great number of options, and ongoing issues of how to best present these to a user in a useful way, duplicating functionality for no obvious reason seems to be counterproductive.

Removing the table filter dropdown would free up toolbar space that could be used for a more useful filter, currently hidden by default in the search tools dropdown (another issue noted in https://github.com/joomla/joomla-cms/issues/5522) ; a double win.

I propose that we consider removing the table-sort dropdown in all views.

**Comment by brianteeman** [comment]
Fine by me. Go for it

**Comment by infograf768** [comment]
There may be some issues to think of.
For example, in the articles view, we can only filter Featured descending or ascending via that filter.

**Comment by nternetinspired** [comment]
That is a good example @infograf768 but isn't that really a bug with the status header? Clicking the header doesn't filter by status, as one would expect, it only sorts by published unpublished. 

Featured, trashed and archived are also article statuses, aren't they? If they aren't they shouldn't be included in the status column.

**Comment by zero-24** [comment]
Moving to `Needs Review` so a Maintainer can decide if this should included or not. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5754">issues.joomla.org/joomla-cms/5754</a>.</sub>

**Comment by sovainfo** [comment]
As long as you need to click the column twice to get descending order, I object to removing table-sort dropdown.

**Comment by brianteeman** [comment]
This change was rejected by the PLT when @pe7er tried to include it in is recent PR to move the search filters<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5754">issues.joomla.org/joomla-cms/5754</a>.</sub>

**Comment by nternetinspired** [comment]
I can't say I'm surprised, the vast majority of contributors to, and maintainers of, this project clearly don't care much for good UX.

I can only assume that someone, somewhere, is getting some sort of kick-back for every dropdown that is included in the admin UI.

Anyone willing to give me odds on my being able to _add_ a completely useless admin option without resistance?

**Comment by Bakual** [comment]
The reason why it was rejected was because the dropdown in some views actually has options to sort the table which aren't available by table headers (like sorting by category in article manager).
Imho, part of a good UX is also that it is consistent across every view. So we decided to leave it everywhere instead of having some views with the dropdown and some without.

**Comment by nternetinspired** [comment]
The other way to look at it would be that the article manager is missing the category column…

**Comment by Bakual** [comment]
One could sure argue if the category should have its own column or if it's fine where it is now.
But that wasn't suggested in the PR back then.

Another suggestion which was dicussed in the PR regarding that dropbox was to split it up into two instead of that single long one. One for the ordering field and one for ASC/DESC (like in weblinks). Cuts the options down to half and makes it less ugly.

**Comment by nternetinspired** [comment]
Less options (with the same result) is a great suggestion, though I don't think asc/desc really warrants a select field on its own. Why not just stick them in the same dropdown? Something like this:

![screen shot 2015-11-12 at 22 51 30](https://cloud.githubusercontent.com/assets/1090182/11133874/92df8890-8990-11e5-8e02-9d59e13fc54c.png)

TBH, I think we just need to get rid of a lot of options, they're really killing Joomla admin right now. There's waaay to much stuff on display. There's only two items I want to see above my entries, a sort field and a search box, everything else just gets in the way.

I'm really not trying to just be a critic here, but I honestly think the project needs to take a long hard look at how we present options to admin users. There's a reason WP is storming ahead, and it isn't because it has a better codebase or more features.

**Comment by Bakual** [comment]
I have no clue how you did that dropdown box, but it looks nice. How does that work?

Fully agree with the "we have to many options". We have many options within Joomla which can be achieved as well with simple layout overrides.

**Comment by nternetinspired** [comment]
>  I have no clue how you did that dropdown box, but it looks nice. How does that work?

On one level it's incorrect, as it isn't using `<select>`, the dropdown `<form>` contains just two `<ul>` elements. Semantics aside, on a UX front it works. It works _really_ well. FYI, this shot is from the equivalent view to Article Manager Craft CMS https://buildwithcraft.com/

**Comment by Bakual** [comment]
Ah I see. :)
