### ISSUE TITLE
Archived articles list filter / pagination issue

### ISSUE THREAD

**Issue by appnweb** [joomla/joomla-cms#5764]
Hi,

On one of our customers website, we noticed a bug with the filter and pagination of archived articles. 

As long as we do not use the filter except for the number of article, the pagination act normally. If we use the year or month filter, for exemple year 2013, and then click on page 2, the year / month filter does a reset and the archive is displayed the right number of article forward but loosing the year criteria.

We noticed that on a joomla 2.5.27 but as we are going to upgrade to joomla 3 soon, we decided to go for some testing on fresh installations of joomla 2.5.28 and joomla 3.3.6 with just the demo data and some articles for the purpose of the test.

Both show the same bug.

You can see exemples on the fresh installations we used for testing, filtering with year 2013 :

Joomla 3.3.6 http://test.anw-sandbox.ch/index.php/archive

Joomla 2.5.28 http://test25.anw-sandbox.ch/index.php/archive

#### System information (as much as possible)

Joomla 3.3.6 / 2.5.28
PHP 5.5.9 

#### Additional comments

Thanks for your help

**Comment by tripledm** [comment]
Have the exact same problem, did you manage to find the solution?

**Comment by tripledm** [comment]
same problem also on Joomla 2.5.27, did you manage to find the solution?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5764">issues.joomla.org/joomla-cms/5764</a>.</sub>

**Comment by appnweb** [comment]
Sorry for the late answer.

No I did not find any real solution. It's possible to escape the problem by selecting display all by default and hide the pagination filter, then the year and month filter work correctly. 

Still looking for a better solution of course but no other idea until now.

**Comment by albertodibiagio** [comment]
Hi,
i'm a beginner and i found the same problem with category list article, pagination and filter.
When try to navigate to second page in a list filtered by a 'list.filter' the filter's value was resetted.
I solved by setting the AdditionalUrlParam in the pagination object before calling pagination->getPagesLinks(); in this way in default_articles.php:
if ($this->state->get('list.filter') != "" ) 
			$this->pagination->setAdditionalUrlParam("filter-search", $this->escape($this->state->get('list.filter')));
		echo $this->pagination->getPagesLinks();

i hop this will help you.

TU

**Comment by brianteeman** [comment]
See #6158 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5764">issues.joomla.org/joomla-cms/5764</a>.</sub>
