### ISSUE TITLE
User - Joomla! plugin is not initialized -  Notification Mail to User problem

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#5765]
#### Steps to reproduce the issue

- Install a Joomla site
- Enable "Allow User Registration"
- Register a new user in the front-end
- No activation mail

#### Expected result

- An activation email to the user

#### Actual result

- No activation mail

#### System information (as much as possible)

"User - Joomla!" plugin shows a default xml configuration. But, it is not initially saved in the extensions table. You must save at least one the plugin to activate the options.

**Comment by infograf768** [comment]
I do not confirm this issue.
Once more: the User - Joomla plugin "Notification mail to user" explicitely deals with the mail sent when the user is created in back-end, NOT in frontend.

![screen shot 2015-01-17 at 07 55 44](https://cloud.githubusercontent.com/assets/869724/5788019/4f8d2e02-9e1e-11e4-86a5-04770070b78e.png)

**Comment by anibalsanchez** [comment]
I have just installed a Joomla! 3.4.0-dev.

## User - Joomla!

-  Auto-create Users = Yes
-  Notification Mail to User = Yes
-  Force Logout for all sessions? = Yes

## Initial #__extensions table, plg_user_joomla

params={"strong_passwords":"1","autoregister":"1"}

## Post save state #__extensions table, plg_user_joomla

If you access the plugin and *just save it*

params={"autoregister":"1","mail_to_user":"1","forceLogout":"1"}

Thus, plugin params are not persisted after installation, with the default xml configuration values.

**Comment by anibalsanchez** [comment]
I sent a new PR: https://github.com/joomla/joomla-cms/pull/5794

This one can be closed. Txs.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5765">issues.joomla.org/joomla-cms/5765</a>.</sub>

**Comment by Kubik-Rubik** [comment]
See referecend PR, I close this one. Thanks!
