### ISSUE TITLE
Missing category in com_banners list view

### ISSUE THREAD

**Issue by natselection** [joomla/joomla-cms#5769]
Somewhere between J! 2.5 and 3.3 the category column was removed from the com_banners list view. 

2.5 URL: /administrator/index.php?option=com_banners
3.3 URL: /index.php?option=com_banners&view=banners

I know there's probably 10 people that actually use that component and it will probably be decoupled from the core at some point but having the category in the list view is very useful for those that do use it.

**Comment by zero-24** [comment]
@natselection it is still there but a bit changed:

![banners_per_category](https://cloud.githubusercontent.com/assets/2596554/5785774/397a6afa-9ddb-11e4-922f-01d86cf56838.PNG)

**Comment by brianteeman** [comment]
Based on @zero24 comment I am closing this at this time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5769">issues.joomla.org/joomla-cms/5769</a>.</sub>
