### ISSUE TITLE
Unable to install from github using install from URL with current staging

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#5772]
#### Steps to reproduce the issue

- install staging: https://github.com/joomla/joomla-cms/archive/staging.zip
- try to install via URL: https://github.com/joomla-extensions/patchtester/releases/download/2.0.beta/com_patchtester.zip

#### Expected result

Install runs and finish successful

#### Actual result

![screen shot 2015-01-16 at 17 43 17](http://issues.joomla.org/uploads/1/523f5f046d4d77ca0dd2245b0f2ee09f.png)

#### System information (as much as possible)

Apache 2.4.10, MySQL 5.6.21, PHP 5.6.3, phpMyAdmin 4.2.11, OpenSSL 1.0.1, XAMPP Control Panel 3.2.1, Webalizer 2.23-04, Mercury Mail Transport System 4.63, FileZilla FTP Server 0.9.41, Tomcat 7.0.56 (with mod_proxy_ajp as connector), Strawberry Perl 7.0.56 Portable

Xampp Version 5.6.3 / PHP 5.6.3 see: https://www.apachefriends.org/download.html

**Comment by brianteeman** [comment]
I just tried this without issue. Do you still have the problem?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5772">issues.joomla.org/joomla-cms/5772</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman still the same issue here. mybe a problem with xampp?

**Comment by zero-24** [comment]
Closing looks like a issue with xampp. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5772">issues.joomla.org/joomla-cms/5772</a>.</sub>
