### ISSUE TITLE
Text Banners Limited to 10 Items in Banner module

### ISSUE THREAD

**Issue by gsmela** [joomla/joomla-cms#5773]
In Joomla 1.5 I used a banner module to create a listing of text banner ads. Basically, the module would list about 18 text ads. They appeared as a simple list in the module in alpha order. If you clicked on each text ad (really just a company name) it would open that company's website. The advantage to doing it this way was a simple tracking method built in to the Joomla banner system.

I just tried to do the same thing in Joomla 3.36 and it limits you to a maximum of ten banners. In Joomla 1.5 you could **type** in your entry - in the case I used I had 18. In Joomla 3.3 you are limited to a **pulldown that allows 1 - 10**. I believe it would be beneficial to change the pulldown selector to the previous text box option. Thank you.

**Comment by zero-24** [comment]
Closing as we have a PR that moves the limit to `20`. https://github.com/joomla/joomla-cms/pull/5787

I don't like the idea with a **text box option** But feel free to submit code.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5773">issues.joomla.org/joomla-cms/5773</a>.</sub>

**Comment by gsmela** [comment]
Thank you zero-24. May I ask why you don't care for the text box option? (Not a criticism as I am just trying to understand why it was changed from 1.5.) I am new to this and would love to participate more as the process is fascinating. Thank you again for your work.

**Comment by pe7er** [comment]
I am curious too why @zero-24 does not like a text box option.

I prefer a text field for Count:
- a drop down option with 20 items seems not very efficient
- other modules, like Latest News, all have a text field for "Count"
- and what if you want to show 21 or more banners ;-)

**Comment by zero-24** [comment]
reopen<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5773">issues.joomla.org/joomla-cms/5773</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Please provide a PR with the field type **text** and filter **integer**. Thanks!

**Comment by Erftralle** [comment]
As this issue is solved with #5804 one could close here.
