### ISSUE TITLE
Extension Manager: Discover,Manage & Update :: Help & Option button order is incorrect

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5775]
-Go to 'Extension Manager: Discover'
-Check the ordering of button (option : Help)
-**Correct ordering is: Help : Option**

-------------------------------------
-Go to 'Extension Manager: Manage'
-Check the ordering of button (option : Help)
-**Correct ordering is: Help : Option**

-------------------------------------
-Go to 'Extension Manager: Update'
-Check the ordering of button (option : Help)
-**Correct ordering is: Help : Option**

![screen shot 2015-01-17 at 02 32 02](http://issues.joomla.org/uploads/1/ae2fcb814ad3e8e3c457ffee105f8263.png)

**Comment by Erftralle** [comment]
This issue has been solved with #6071.
