### ISSUE TITLE
Extension Manager: Install> Install from directory:: Why 2 messages(warning + Error) for invalid path

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5776]
Go to 'Extension Manager: Install'
select 'Install from directory'
Enter Invalid path
click on install button

**Suggestion: We should not display 2 messages for 1 problem**

![screen shot 2015-01-17 at 02 37 38](http://issues.joomla.org/uploads/1/0ed443f27fb888a6fd364f36d7c02058.png)

**Comment by brianteeman** [comment]
I have honestly no idea why I set this to information required - removing that<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5776">issues.joomla.org/joomla-cms/5776</a>.</sub>

**Comment by Bakual** [comment]
It's generated here: https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/installer/helper.php#L223

One could probably change the category from `jerror` to `installer` or whatever. The `jerror` category is a special one which ends up in the message queue and thus is shown to the user.

However I'm not sure if we want to hide that. In this case it may not be useful. But in other cases it may actually help track down why an extension would not install.

**Comment by brianteeman** [comment]
Based on the comments from @bakual above I am closing this as it is the desired behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5776">issues.joomla.org/joomla-cms/5776</a>.</sub>
