### ISSUE TITLE
Extension Manager: Install>Install from URL:: UI issue, when we install something from URL

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5777]
**Prerequisites: sidebar should be open**

-Go to 'Extension Manager: Install>Install from URL'
-Enter Url 
-click on install
-Check sidebar
![screen shot 2015-01-17 at 02 53 47](http://issues.joomla.org/uploads/1/7cc3d7e753f5feb7a57a6083f3cf768c.png)

**Comment by zero-24** [comment]
IIRC this is expected and comes from the joomla logo :smile: so you don't klick anything and abort the current prozess.

**Comment by aasimali** [comment]
I know the difference between expected & actual :smiley: (Seems you did not get me correctly)
Entire page should be white! why the left portion is fully visible!

**Comment by zero-24** [comment]
ahh ok Thanks :+1: I understand that you don't expect the white area.

**Comment by aasimali** [comment]
I expect the entire area should be partially visible! But now, Left side portion is fully visible.
Thanks @zero-24

**Comment by brianteeman** [comment]
I am closing this as it appears to have been resolved elsewhere as I can not replicate it in Joomla 3.5beta5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5777">issues.joomla.org/joomla-cms/5777</a>.</sub>
