### ISSUE TITLE
Extension Manager: Install>Install from URL:: Don't redirect to another page for invalid url [If Possible)

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5778]
-Go to 'Extension Manager: Install>Install from URL' 
-Enter Invalid Url(enter 'www.googlecom/etc/etc' instead of 'www.google.com/etc/etc'  
-Click on install
-It will redirect to an Error page
-Ideally, Application should not redirect to another page (If POSSIBLE) OR change the button name(if not possible)

![screen shot 2015-01-17 at 03 09 31](http://issues.joomla.org/uploads/1/fcaa0ac6ec63e246c80fd9ade4633a4e.png)
![screen shot 2015-01-17 at 03 09 39](http://issues.joomla.org/uploads/1/c8731d20eb81eed3fabc7d7550dd2863.png)

**Comment by brianteeman** [comment]
There are two different scenarios
1. The invalid url - we get a correct message
2. The invalid domain - we get the "couldn't resolve host message" above

**Comment by aasimali** [comment]
@brianteeman 
Sorry for the delay in reply! ( I was on leave)
1. Correct
2.Correct but needs small improvement for making UX more solid.(As per my point of view) 

For the second scenario: Can't we change the button name from **'Return to control Panel' TO 'Return to Extension Manager'**

**Comment by Bakual** [comment]
Afaik, the error page always links back to the control panel (or site homepage in frontend). Because the error page doesn't really know where the error came from and what would be a safe page to link to.

The only solution I would see is to try to catch the error in com_installer and show a message instead of the error page. But that could be a bit tricky.

**Comment by mbabker** [comment]
See #5892

**Comment by Bakual** [comment]
Ah, easier than I expected when one knows where to look :+1: 

Closing this in favor of the PR.

**Comment by aasimali** [comment]
@Bakual 
Thank you for finding out the solution & adding PR for this issue.
