### ISSUE TITLE
Module Manager: Modules:: Cross button should not be there in filter for site(x) [It should be there only for administrator]

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5782]
-Go to 'Module Manager: Modules'
-Check first drop-down under filter option

![screen shot 2015-01-17 at 03 41 23](http://issues.joomla.org/uploads/1/107a887743288778b318d206b6d89f05.png)

**Comment by brianteeman** [comment]
I am closing this as the module manager has been reworked and and the X is no longer present<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5782">issues.joomla.org/joomla-cms/5782</a>.</sub>
