### ISSUE TITLE
Media Manager:: Display a pop-up, If the image is not selected & user click over the 'Delete' button

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#5785]
-Go to 'Media Manager'
-Do not select any image 
-Click on delete button
-Page will be refreshed but nothing happen
-Display a pop please

![screen shot 2015-01-17 at 04 11 52](http://issues.joomla.org/uploads/1/c911bd52498f97cfdfe7a592daf1fe80.png)

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/5807

**Comment by brianteeman** [comment]
Please test #5808 as #5807 has been closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5785">issues.joomla.org/joomla-cms/5785</a>.</sub>
