### ISSUE TITLE
JBrowser::hasFeature removed but use in JBrowser source code

### ISSUE THREAD

**Issue by Quibi** [joomla/joomla-cms#5788]
#### Steps to reproduce the issue

The JBrowser::hasFeature() has been removed from Joomla CMS 3.x. However, this removed function is used in the very JBrowser source code. Specifically, hasFeature() is called at /libraries/joomla/environment/browser.php line 607 (inside function isViewable).

I think that hasFeature() should be removed from JBrowser source code and an alternative algorithm should be used at that point.

To reproduce this error, I wrote this code:

	$browser = JBrowser::getInstance(null, "");
	$browser->isViewable('foo/nothing');

#### Expected result

True or False

#### Actual result

Fatal error: Call to undefined method JBrowser::hasFeature() in /libraries/joomla/environment/browser.php on line 607

#### System information (as much as possible)
Joomla CMS 3.3 (staging)

#### Additional comments

If JBrowser::hasFeature is directly call, you get a " Fatal error: Call to undefined method JBrowser::hasFeature()...", such as running:

	$browser = JBrowser::getInstance();
	$browser->hasFeature('image');

**Comment by zero-24** [comment]
Thanks here is a PR for that :smile: https://github.com/joomla/joomla-cms/pull/5791

**Comment by Quibi** [comment]
Thanks a lot.
