### ISSUE TITLE
Media Manager: thumbnails.css / .less missing in front end for beez / third party templates

### ISSUE THREAD

**Issue by Harmageddon** [joomla/joomla-cms#5790]
#### Steps to reproduce the issue
1) Switch your site's default template to beez3 or a third party template.
2) Log in to frontend with a user account, that can edit or create an article in frontend.
3) Create / edit an article in frontend.
4) Click the "insert image" button.

#### Actual result
![screen shot 2015-01-17 at 06 10 21](http://issues.joomla.org/uploads/1/62e12af7bdd928430bf1430dad0385d2.png)

#### Expected result
![screen shot 2015-01-17 at 06 10 23](http://issues.joomla.org/uploads/1/a1668050d7e60eb91f46650a5d967712.png)

Reported by user MrMusic in a german Joomla! Forum ([thread](http://www.joomlaportal.de/joomla-3-x-templates-und-design/316587-media-manager-im-frontend.html "thread")). I can confirm this. I'm not sure, but I think this worked before. On first glance, the file media/jui/less/thumbnails.less or media/jui/css/thumbnails.css is missing here.

Tested on current master and 3.3.6 with the same result.

**Comment by wilsonge** [comment]
I presume you expected and actual images are the wrong way around here?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5790">issues.joomla.org/joomla-cms/5790</a>.</sub>

**Comment by Harmageddon** [comment]
@wilsonge Yes, you're right. Thank you! I've corrected the original post.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5790">issues.joomla.org/joomla-cms/5790</a>.</sub>

**Comment by bembelimen** [comment]
I looked into this issue and found the following points:

- the first problem is, that beez does not load bootstrap by default => solution: add com_media to the template parameters
- then we see, that we cannot see anything: beez supports bootstrap only in the inde.php and not in the component.php => add the code to the component.php

```php
$app            = JFactory::getApplication();
$templateparams	= $app->getTemplate(true)->params;
$bootstrap      = explode(',', $templateparams->get('bootstrap'));
$jinput         = JFactory::getApplication()->input;
$option         = $jinput->get('option', '', 'cmd');

if (in_array($option, $bootstrap))
{
	JHtml::_('bootstrap.framework');
	// Load optional rtl Bootstrap css and Bootstrap bugfixes
	JHtml::_('bootstrap.loadCss', true, $this->direction);
}
```

- now we have styled boxes without images. Problem: the default bootstrap (from the media folder) does not know icon-folder-2 => we have to rename all icon-folder-2 to icon-folder-close
- now the li-elements are not in one line => add pull-left to the li elements or add ".thumbnails > li" to the beez css
- last but not least we have to style the link hover color

**Comment by bembelimen** [comment]
Other solution: put every style property to the beez template css (like icon, etc.) to use it without any bootstrap stuff

**Comment by chmst** [comment]
As much as I see in the german forums, it would be a good idea to remove the beez template completely fom the core - there are too many questions and problems around it.

**Comment by AndyGaskell** [comment]
I think it'd be good to find a solution to this.

It means that using the media manager when front-end-editing is dependent on the template having the required bootstrap bits.  This is a use case that many template developers do not test against I think.

Perhaps com_media, when loaded via an iFrame, should have all the styles it needs loaded from within the component.

So, I'm thinking, perhaps this is less of an issue with beez, and more of an issue in that com_media does not include all the styles that it needs to function nicely.

Just some thoughts, I'll have a ponder and see if I can put together some code for this.

**Comment by dgt41** [comment]
Just a hint:
Remove from administrator/components/com_media/views/images/tmpl/default.php 
```
<div class="tabbable">
	<ul class="nav nav-tabs">
		<li class="active"><a href="#browse_tab" data-toggle="tab"><?php echo JText::_('COM_MEDIA_BROWSE_FILES') ?></a></li>
		<li><a href="#upload_tab" data-toggle="tab"><?php echo JText::_('COM_MEDIA_UPLOAD') ?></a></li>
	</ul>

	<div class="tab-content">
```
as well as lines 147-148 and lines 162-163. This will bring back the old (no tabs view ) and therefore should be easier.

**Comment by dgt41** [comment]
@Harmageddon @AndyGaskell @bembelimen  try #8373

**Comment by AndyGaskell** [comment]
Thanks @dgt41 for the pointers, I'll do some reading of that code and ticket.
I need to have a bit more of a dig into it here, it seems like it might be an issue cause locally related to the template CSS not being loaded into the iFrame.
My thinking, initially, was to add the required css to /media/media/css/popup-imagemanager.css but that may not be ideal, I'll dig into it further.

**Comment by dgt41** [comment]
@AndyGaskell another hint: that modal contains two iframes (the first one is the view images and inside that one there is another iframe from the view medialist (where the icons are). So the solution must cover both views...

**Comment by brianteeman** [comment]
Thank you for submitting this issue/pull request. The media manager is currently being completely rewritten and I have notified the development team about this issue for their consideration. I am closing this here at this time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5790">issues.joomla.org/joomla-cms/5790</a>.</sub>
