### ISSUE TITLE
Not able to create a folder when uploading images in "Images and links" pane

### ISSUE THREAD

**Issue by kairoen** [joomla/joomla-cms#5795]
Reporting a bug that should be fixed in Joomla 3.4
When creating a New article, and you set introimage and full article image in "Images and links" tab, you are not allowed to create folder, and you are not allowed to overwrite images With the same name.

It should be a option to do this, because the user finds this confusing. When using JCE Texteditor, you have a much more options rather than the included texteditor.

**Comment by zero-24** [comment]
@kairoen 
>and you are not allowed to overwrite images With the same name.

Overriding will come with the new media manager but this is not yet in 3.4 see: http://issues.joomla.org/tracker/joomla-cms/3839

> you are not allowed to create folder

confirmed but IIRC this view is designed for adding images e.g. a article image and not to manage the media manger. (Just my 2 cents)

**Comment by brianteeman** [comment]
Changing status to confirmed. This is a big frustration for many users<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5795">issues.joomla.org/joomla-cms/5795</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for submitting this issue/pull request. The media manager is currently being completely rewritten and I have notified the development team about this issue for their consideration. I am closing this here at this time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5795">issues.joomla.org/joomla-cms/5795</a>.</sub>
