### ISSUE TITLE
Sort order for Featured Articles is different

### ISSUE THREAD

**Issue by kairoen** [joomla/joomla-cms#5796]
The way sort order Works in Joomla 3.3 is just great, but when it comes to sortorder for "Featured Articles", this Works a bit different. As a Developer, my Clients finds this very confusing - and the sortorder should be the same as sortordering articles or menuitems.

**Comment by brianteeman** [comment]
Please explain how it is different<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5796">issues.joomla.org/joomla-cms/5796</a>.</sub>

**Comment by kairoen** [comment]
Sort order for articles you use the first column in article view. Just drag and drop. But for Featured Articles, you have to use the old up/down arrows used in earlier versions of Joomla. It is not consistent UI

**Comment by brianteeman** [comment]
Ah now I understand what you are referring to. This is a known issue and one that cannot be currently resolved as the field used for ordering featured articles is different to the one used for all articles<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5796">issues.joomla.org/joomla-cms/5796</a>.</sub>
