### ISSUE TITLE
Content override (feature request)

### ISSUE THREAD

**Issue by kairoen** [joomla/joomla-cms#5798]
As a template developer, I really miss a feature to override the content output. Sometimes the output needs to be organized and displayed differently for a full flexible design. As for today, you do not have an option to override the output for multiple views. Changing the views in com_content, will be set for the whole site.

The feature I am missing is to be able to override the content view in a template, with different views/output based in settings for a menu. Here is an example

1. Override the com_content view in the template, and in \template\mytemplate\html\com_content\views\article I create a copy of default.php. I call this file defaultStyle1.php, and make modifications to this file.
2. To activate this view, I change the settings for a menuitem, and choose style "defaultStyle1".

If this is possible, a template designer can make various outputs, and no longer bound to the limitation that is for current version of Joomla. The same functionality is available as for modules.

**Comment by brianteeman** [comment]
Are you asking for something different to what can be achieved here https://docs.joomla.org/Layout_Overrides_in_Joomla<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5798">issues.joomla.org/joomla-cms/5798</a>.</sub>

**Comment by brianteeman** [comment]
After almost two months without response i am closing this issue (it can always be reopened if the question is answred)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5798">issues.joomla.org/joomla-cms/5798</a>.</sub>
