### ISSUE TITLE
JForm 'safehtml' filter uses 'string'

### ISSUE THREAD

**Issue by cppl** [joomla/joomla-cms#5799]
`JForm::filterField($element, $value)` appears to have a copy&paste issue in the `safehtml` case, specifically it calls `clean()` with a type of 'string':

	// Filter safe HTML.
	case 'SAFEHTML':
		$return = JFilterInput::getInstance(null, null, 1, 1)->clean($value, 'string');
		break;

It appears the only choice developers have is `raw` if a JForm field needs to include HTML tags, not sure why this hasn't been found before.

**Comment by brianteeman** [comment]
See #5800<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5799">issues.joomla.org/joomla-cms/5799</a>.</sub>
