### ISSUE TITLE
Empty div of system messages in templates

### ISSUE THREAD

**Issue by proweb** [joomla/joomla-cms#5802]
#### Steps to reproduce the issue
Install Joomla
Open frontpage and click "View source"
Befor component part you will find empty 
``` html
<div id="system-message-container">  </div>
```

#### Expected result
Expected clean normal markup of all Joomla templates
not to see usless empty div in markup of templates then we have no system messages

#### Actual result
``` html
<div id="system-message-container">  </div>
```
On all pages

#### Additional comments
Why I need this div then I have no any message?

**Comment by dgt41** [comment]
I am afraid we need the id so that the script knows where to inject their code
