### ISSUE TITLE
Error at article Creation

### ISSUE THREAD

**Issue by kshitijSharma2014** [joomla/joomla-cms#5812]
I was running tests on joomla-cms branch "3.4 dev"  and got errors.
Please follow the steps to re-create the error in your local machine
  step 1: go to article manager.
  step 2: click on New article.
  step 3: click save and close

![articleerror](https://cloud.githubusercontent.com/assets/6698117/5793487/2766e69a-9f6b-11e4-9ff6-f501cf45dee9.JPG)

**Comment by kshitijSharma2014** [comment]
@javigomez  can you confirm this.
thanks

**Comment by zero-24** [comment]
@kshitijSharma2014 I'm unable to replicate this via the instuctions on staging.

>I was running tests on joomla-cms branch "3.4 dev" and got errors.

@kshitijSharma2014 34-dev is outdated please use staging instead: https://github.com/joomla/joomla-cms/archive/staging.zip

IIRC we have staging only as we have PRs that point to it.

**Comment by zero-24** [comment]
oops I mean IIRC we have 34-dev only as we have PRs that point to it. :smile:

**Comment by infograf768** [comment]
Closing as this code is absent from staging.
