### ISSUE TITLE
Menu Item Tagged List showing Unpublished Categories, leading to 404 Category Error.

### ISSUE THREAD

**Issue by mikegrahamjones** [joomla/joomla-cms#5814]
#### Steps to reproduce the issue

No where in the SQL query for CallStack; does it filter out unpublished categories.

JROOT\libraries\legacy\model\legacy.php:332
JROOT\libraries\legacy\model\list.php:276
JROOT\libraries\legacy\model\list.php:310
JROOT\libraries\legacy\model\list.php:171
JROOT\components\com_tags\models\tag.php:85
JROOT\libraries\legacy\view\legacy.php:398
JROOT\components\com_tags\views\tag\view.html.php:51
JROOT\libraries\legacy\controller\legacy.php:693
JROOT\components\com_tags\controller.php:54
JROOT\libraries\legacy\controller\legacy.php:730
JROOT\components\com_tags\tags.php:15
JROOT\libraries\cms\component\helper.php:352
JROOT\libraries\cms\component\helper.php:332
JROOT\libraries\cms\application\site.php:191
JROOT\libraries\cms\application\site.php:237
JROOT\libraries\cms\application\cms.php:251
JROOT\index.php:40

#### Expected result

Unpublished Categories should be hidden from Menu Item "Tagged List".

#### Actual result

Unpublished Category (which is tagged) is appearing within Menu Item "Tagged List".

#### System information (as much as possible)

PHP Built On	Windows NT MICHAEL-PC 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) i586
Database Version	5.5.27
Database Collation	utf8_general_ci
PHP Version	5.4.7
Web Server	Apache/2.4.3 (Win32) OpenSSL/1.0.1c PHP/5.4.7
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.99 Safari/537.36

#### Additional comments

SELECT m.type_alias, m.content_item_id, m.core_content_id, count(m.tag_id) AS match_count,  MAX(m.tag_date) as tag_date, MAX(c.core_title) AS core_title,MAX(c.core_alias) AS core_alias, MAX(c.core_body) AS core_body, MAX(c.core_state) AS core_state, MAX(c.core_access) AS core_access,MAX(c.core_metadata) AS core_metadata, MAX(c.core_created_user_id) AS core_created_user_id, MAX(c.core_created_by_alias) AS core_created_by_alias,MAX(c.core_created_time) as core_created_time, MAX(c.core_images) as core_images,
  CASE WHEN c.core_modified_time = '0000-00-00 00:00:00' THEN c.core_created_time ELSE c.core_modified_time END as core_modified_time,MAX(c.core_language) AS core_language, MAX(c.core_catid) AS core_catid,MAX(c.core_publish_up) AS core_publish_up, MAX(c.core_publish_down) as core_publish_down,MAX(ct.type_title) AS content_type_title, MAX(ct.router) AS router,
  CASE WHEN c.core_created_by_alias > ' ' THEN c.core_created_by_alias ELSE ua.name END AS author,ua.email AS author_email

  FROM gvgfi_contentitem_tag_map AS m

  INNER JOIN gvgfi_ucm_content AS c 
  ON m.type_alias = c.core_type_alias 
  AND m.core_content_id = c.core_content_id 
  AND c.core_state IN (1) 
  AND (c.core_publish_up = '0000-00-00 00:00:00' OR c.core_publish_up <= '2015-01-18 23:09:17') 
  AND (c.core_publish_down = '0000-00-00 00:00:00' OR  c.core_publish_down >= '2015-01-18 23:09:17')

  INNER JOIN gvgfi_content_types AS ct 
  ON ct.type_alias = m.type_alias

  LEFT JOIN gvgfi_users AS ua 
  ON ua.id = c.core_created_user_id

  WHERE m.tag_id IN (3,2,4,5,6,7,8,9,10) 
  AND m.type_alias IN ('com_content.category') 
  AND c.core_access IN (0,1,5)

  GROUP BY m.type_alias, m.content_item_id, m.core_content_id

  ORDER BY MAX(`c`.`core_title`) ASC

**Comment by mikegrahamjones** [comment]
![screen shot 2015-01-18 at 17 31 13](http://issues.joomla.org/uploads/1/d06fad292cbddfdf67fc7220702351c9.png)
![screen shot 2015-01-18 at 17 31 23](http://issues.joomla.org/uploads/1/cff21d59ae0e8f510451832b1f5d917f.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5814">issues.joomla.org/joomla-cms/5814</a>.</sub>

**Comment by mikegrahamjones** [comment]
I've fixed it upon saving within Category Edit screen; but I still believe a feature should be added to check for inconsistencies between Tags and Categories; since the SQL query (as it seems does not pull the same data from the Category Table).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5814">issues.joomla.org/joomla-cms/5814</a>.</sub>

**Comment by mikegrahamjones** [comment]
Because it kind of defeats the purpose of using the Category Index, to "unpublish" a category, if you're still required to Save within the category itself; in order for changes to take maximum effect.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5814">issues.joomla.org/joomla-cms/5814</a>.</sub>

**Comment by brianteeman** [comment]
Confirmed on 3.5.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5814">issues.joomla.org/joomla-cms/5814</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #10304
