### ISSUE TITLE
[4.0] RFC - Article State is confusing

### ISSUE THREAD

**Issue by nternetinspired** [joomla/joomla-cms#5819]
A thought relating to https://github.com/joomla/joomla-cms/pull/5803, are we confusing 'State' with 'Status' and combining the two in the UI when they should not be combined?

Currently we lump together published/unpublished, archived/not-archived, featured/not-featured and trashed/not-trashed but it seems to me that only published/unpublished is a state, the others are more like special categories (statues) because an article can exist both with a state and a status.

For example an article can be featured _and_ unpublished, and the same is true of archived articles. Trashed is a bit different, as you can't publish/unpublish a trashed article.

**Comment by nternetinspired** [comment]
I would suggest that we therefore redefine these as:

State: published / unpublished / trashed
Status*: featured / archived

* or another, more appropriate, name.

**Comment by brianteeman** [comment]
Sounds good but I would assume we need a status for an item that is not
featured or archived as well

**Comment by nternetinspired** [comment]
> Sounds good but I would assume we need a status for an item that is not
featured or archived as well

I don't think so, because not-featured and not-archived are both equal to the default status of an article.

**Comment by nternetinspired** [comment]
And throughout the UI we already have the syntax to support that. For example, when viewing featured articles the toolbar option reads 'unfeature'. The same is true in the trashed article view.

**Comment by brianteeman** [comment]
I guess it depends on how it is displayed.

In general I agree with what you are saying

**Comment by brianteeman** [comment]
How would this be displayed?

One change we can make right now is to change strings like these from
COM_CONTACT_TOGGLE_TO_FEATURE="Toggle to change contact state to 'Featured'"
COM_CONTACT_TOGGLE_TO_UNFEATURE="Toggle to change contact state to 'Unfeatured'"
to
COM_CONTACT_TOGGLE_TO_FEATURE="Toggle to change contact status to 'Featured'"
COM_CONTACT_TOGGLE_TO_UNFEATURE="Toggle to change contact status to 'Unfeatured'"

**Comment by brianteeman** [comment]
Featured and archived are different in the database

Featured is its own column

Archived is a value of 2 in the State column

So I can see how we can change Featured to be status - its just a language string but archived is different (Or do i misunderstand part of what you are saying)

**Comment by nternetinspired** [comment]
I'd even cut it to just:

COM_CONTACT_TOGGLE_TO_FEATURE="Toggle contact 'Featured' status"

Then the UNFEATURE strings are no longer needed then.

**Comment by brianteeman** [comment]
What about using a generic string
JGLOBAL_CLICK_TO_TOGGLE_STATUS="Click on icon to toggle status."


On 19 January 2015 at 10:55, Seth Warburton <notifications@github.com>
wrote:

> I'd even cut it to just:
>
> COM_CONTACT_TOGGLE_TO_FEATURE="Toggle contact 'Featured' status"
>
> Then the UNFEATURE strings are no longer needed then.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5819#issuecomment-70475965>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Thats an easy change to make

On 19 January 2015 at 10:57, Brian Teeman <brian@teeman.net> wrote:

> What about using a generic string
> JGLOBAL_CLICK_TO_TOGGLE_STATUS="Click on icon to toggle status."
>
>
> On 19 January 2015 at 10:55, Seth Warburton <notifications@github.com>
> wrote:
>
>> I'd even cut it to just:
>>
>> COM_CONTACT_TOGGLE_TO_FEATURE="Toggle contact 'Featured' status"
>>
>> Then the UNFEATURE strings are no longer needed then.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joomla/joomla-cms/issues/5819#issuecomment-70475965>.
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nternetinspired** [comment]
> So I can see how we can change Featured to be status - its just a language string but archived is different 

You're right! I was under the (false) impression that an archived item could also be unpublished, I see now it can't. That said I do still think that 'archived' as a state is illogical. While it may be architected differently, it probably shouldn't be. I think it would make more sense as a kind of special status like featured.

**Comment by nternetinspired** [comment]
> JGLOBAL_CLICK_TO_TOGGLE_STATUS="Click on icon to toggle status."

A generic string would be even better, I agree. What about simply: 

JGLOBAL_CLICK_TO_TOGGLE_STATUS="Click to toggle item status."

**Comment by brianteeman** [comment]
So lets do one thing at a time. As it looks to me like we need to also
change the way featired is displayed in the contact list to be consistent
with the article list.

I will do a PR now to use JGLOBAL_CLICK_TO_TOGGLE_STATUS="Click to toggle
item status."


On 19 January 2015 at 11:01, Seth Warburton <notifications@github.com>
wrote:

> So I can see how we can change Featured to be status - its just a language
> string but archived is different
>
> You're right! I was under the (false) impression that an archived item
> could also be unpublished, I see now it can't. That said I do still think
> that 'archived' as a state is illogical. While it may be architected
> differently, it probably shouldn't be. I think it would make more sense as
> a kind of special status like featured.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5819#issuecomment-70476673>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nternetinspired** [comment]
> I will do a PR now to use JGLOBAL_CLICK_TO_TOGGLE_STATUS="Click to toggle
item status."

:+1:

**Comment by brianteeman** [comment]
Actually just looked at it and as the layouts are different in the two
places this is used (articles and contacts) I think it is going to be
better to have

JGLOBAL_TOGGLE_FEATURED_STATUS="Toggle featured status."

(I dont like using the word click)

On 19 January 2015 at 11:10, Seth Warburton <notifications@github.com>
wrote:

> I will do a PR now to use JGLOBAL_CLICK_TO_TOGGLE_STATUS="Click to toggle
> item status."
>
> [image: :+1:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5819#issuecomment-70477531>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
Archived IS a state, not Featured

**Comment by nternetinspired** [comment]
> JGLOBAL_TOGGLE_FEATURED_STATUS="Toggle featured status."

Even better. I agree, I also don't like click.

> Archived IS a state, not Featured

Yes, I realise that now. I don't think that is very intuitive though, so my question now is whether it would be better implemented as a status like 'featured' in future.

**Comment by brianteeman** [comment]
Re Archived

Thats a bigger change

**Comment by nternetinspired** [comment]
I agree.

**Comment by nternetinspired** [comment]
Can we all agree that featured is not a state though? 

If we can then it has implications here:https://github.com/joomla/joomla-cms/pull/5803

**Comment by brianteeman** [comment]
Please see and test https://github.com/joomla/joomla-cms/pull/5823

On 19 January 2015 at 11:21, Seth Warburton <notifications@github.com>
wrote:

> I agree.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5819#issuecomment-70478744>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
I agree that featured is not a state either architecturally or logically

On 19 January 2015 at 11:22, Seth Warburton <notifications@github.com>
wrote:

> Can we all agree that featured is not a state though?
>
> If we can then it has implications here:#5803
> <https://github.com/joomla/joomla-cms/pull/5803>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5819#issuecomment-70478876>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nternetinspired** [comment]
I've just noticed that com_contact does not mix featured into the status column. I think it's far better the way it is done in com_contact that con_content:

![screen shot 2015-01-19 at 11 29 02](https://cloud.githubusercontent.com/assets/1090182/5799806/8ec69232-9fce-11e4-9b97-836c2d7c905a.png)

**Comment by brianteeman** [comment]
I was thinking the complete opposite

On 19 January 2015 at 11:30, Seth Warburton <notifications@github.com>
wrote:

> I've just noticed that com_contact does not mix featured into the status
> column. I think it's far better the way it is done in com_contact that
> con_content:
>
> [image: screen shot 2015-01-19 at 11 29 02]
> <https://cloud.githubusercontent.com/assets/1090182/5799806/8ec69232-9fce-11e4-9b97-836c2d7c905a.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5819#issuecomment-70479754>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nternetinspired** [comment]
Status, as we currently have it, is a sortable column that mixes both logical publication states and the featured status. They don't belong in the same column.

Related: the search tools filter allows you to filter by published/trashed/archived but not featured. That is correct IMO.

**Comment by photodude** [comment]
I agree with this change.

**Comment by wilsonge** [comment]
OK we can't change archive to be like featured until at least J4 - because it's a big b/c change. You can if you want make UX changes for 3.6 to separate featured from the status'

Removing from the needs review pile

**Comment by andrepereiradasilva** [comment]
i also agree with feature not being in the states column

**Comment by marcochirienti** [comment]
I agree with "featured status" not being in the ''state" column.
And I think that the use of the words "state", "status", and "spublished" should be "standardized" in J4.
Actually there are, for similar purpose,  columns with different names in different tables (state or published).
Filters are of type "status" and with name "published".
Language labels use "STATE" or "STATUS" are used interchangeably.

**Comment by brianteeman** [comment]
Updated the title to show 4.0

**Comment by brianteeman** [comment]
Closing this as we now have a new ui under development
