### ISSUE TITLE
[TinyMCE] Textarea attributes (width, height, etc) not working.

### ISSUE THREAD

**Issue by daveli** [joomla/joomla-cms#5820]
This issue appears in Joomla 3.3.6 and can be viewed in com_content when creating a new article. You will notice that the height of the default editor (TinyMCE) is 550px when it should be 500px as stated in the code when the editor is initialized. It seems that since TinyMCE 4 parsing the height, width, cols, rows etc from the textarea element are not working anymore due to an API changes.

**Comment by brianteeman** [comment]
The height is being correctly set to 550px by the tinymce plugin.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5820">issues.joomla.org/joomla-cms/5820</a>.</sub>

**Comment by daveli** [comment]
If I get this right, that would mean that I cannot change the height of a specific editor field, as this was possible in the past.

I tried adding the height parameter to [article.xml](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/models/forms/article.xml#L26 "") with no effect. Changing the default editor to JCE seems to change the height.
I assume it should change the height since this is part of the parameters for the Editor Field in Joomla see: [Editor_form_field_type](https://docs.joomla.org/Editor_form_field_type "https://docs.joomla.org/Editor_form_field_type")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5820">issues.joomla.org/joomla-cms/5820</a>.</sub>

**Comment by brianteeman** [comment]
Take a look at how it is done with the custom html module<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5820">issues.joomla.org/joomla-cms/5820</a>.</sub>

**Comment by studio42** [comment]
Hi, it's really not working! Joomla 3.4.1
Tested with different settings, you cannot anymore set the height in tinyMce. Only the textarea height is set.

**Comment by infograf768** [comment]
Tested with TinyMCE.
Setting a custom height in the editor form.
I confirm that this was possible in 2.5.x (it overrides the height defined in Tiny parameters), not in 3.4.1/staging.

**Comment by infograf768** [comment]
Looks like it works though with codemirror and no editor.

**Comment by Mathewlenning** [comment]
Looks like the Javascript function is only built with the default plugin params. I found it and I'll do a PR

**Comment by zero-24** [comment]
Closing as we have a PR. Please test there: #8106

Thabks
