### ISSUE TITLE
Article title with html (spans breaks)

### ISSUE THREAD

**Issue by joris85** [joomla/joomla-cms#5830]
#### Steps to reproduce the issue
If i ad a article title and i ad a span, it strips it.

#### Expected result
The result i want is that i can add a break or span or maybe an icon in the title.
So no html stripping or maybe allow a few things.

Does any body know the reason that this is not possible? 
I think there is a reason for it though :-)

**Comment by rgmears** [comment]
I agree that it would be good to be able to add HTML to titles. Especially character entities like &#8212; or &mdash;, etc.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5830">issues.joomla.org/joomla-cms/5830</a>.</sub>

**Comment by rgmears** [comment]
... make that &amp;#8212; and &amp;mdash;<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5830">issues.joomla.org/joomla-cms/5830</a>.</sub>

**Comment by brianteeman** [comment]
You can already use `&mdash`

On 20 January 2015 at 14:39, rgmears <notifications@github.com> wrote:

> ... make that &#8212; and &mdash;
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/5830
> <http://issues.joomla.org/tracker/joomla-cms/5830>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5830#issuecomment-70662789>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
Great. What about &amp;middot; (which is for a mini-bullet &middot; ) or &amp;#8226; ( which is for bullet &#8226; ) ?

**Comment by brianteeman** [comment]
Have you tried it yourself? did it work?

On 20 January 2015 at 14:55, Robert G Mears <notifications@github.com>
wrote:

> Great. What about &middot; (which is for a mini-bullet · ) or &#8226; (
> which is for bullet • ) ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5830#issuecomment-70665499>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by joris85** [comment]
Thanks for the tips! Did not know this so nice to know.
The bullet works.

But this is not wat i was looking for, i really want to use span or break in the titles

**Comment by rgmears** [comment]
@brianteeman 
The letters work, but not the numbers. Tried that a couple of years ago and it didn't work. Nice that it does now.

Still, I agree with @joris85 . It would be nice to be able to add <span>TITLE</span> for styling reasons. Although this could be done as an override in the respective file; except it would appear on all pages using that file, some where it may not be needed..

**Comment by rgmears** [comment]
@joris85 
You can use &amp;nbsp; (non-breaking space) to join two words if that helps. But it disappears in the title box.

**Comment by nternetinspired** [comment]
It's safer to strip html from titles. Yes, you might only want to use a `<span>` but allowing any html allows the possibility that malicious code is inserted there too.

**Comment by rgmears** [comment]
Is the same the case if one does an override which adds a span element inside an H1 or H2, etc?

**Comment by Bakual** [comment]
There are two issues I see. One is what Seth mentioned, allowing all HTML would result in a small security risk. So we need to filter it for sure similar to what we do with the article body.
The second and imho bigger issue would be that the article title is not only used in a HTML page. It is also used to build a feed and depending on installed extensions maybe even in other enviroments. Not all of them will be happy with HTML in a title and could break.
Even if we're strictly talking about a HTML page, what looks good on the article page itself doesn't necessary look fine on the list (front- or backend), modules or wherever the title is shown as well.

**Comment by nternetinspired** [comment]
> The second and imho bigger issue would be that the article title is not only used in a HTML page. It is also used to build a feed and depending on installed extensions maybe even in other environments. Not all of them will be happy with HTML in a title and could break.

This is a very good point. You definitely don't want that in your RSS feed or `<title>` so you'd need to do a strip-html on everywhere but the actual page content. As it's already possible to do this stuff with plugins, like [JB Type](http://extensions.joomla.org/extension/jb-type) for example, I'd say that there isn't much of a case for including such functionality in core, given that 99.98% of users wouldn't ever want to do this.

**Comment by rdeutz** [comment]
Yeah, sometimes this would be nice. But there are ways to do it e.g. "--" in title will be replaced with break. I think it is very specific and to have a solution for all cases is complicated to find.

**Comment by joris85** [comment]
The solution, a parameter :) allowed html characters. Or html yes or no.

**Comment by mbabker** [comment]
Wouldn't work well at all.  If the param is set to yes for one user but no for another, then the user who is allowed to insert HTML to the title will gripe because their HTML is being stripped by someone else.  Also, we **REALLY** don't need anymore parameters anywhere IMO; the backend needs to go on a parameter diet.  The current behavior is consistent and it works for the "normal" use cases.

**Comment by roland-d** [comment]
I also think this is not something we should add into the core. As for yet another parameter, please no. There are way too many already. My suggestion is to close this PR as I don't see this going to get merged.

**Comment by Bakual** [comment]
Closing per comments from 3 PLT and other valued community members

**Comment by joris85** [comment]
why a filter per user? You can leave some resposibility to the admin right? Just filter or not. If it goes wrong you set it on filter and done. 

Common even wordpress i can add spans and a much more pro cms cant. And if you put the option in core than no need for override the core for those who can use this option.

If you ask me there is really no reason to not add it to the core. Default filter and possible to add accepted characters
