### ISSUE TITLE
RFC Possible regression on modals!!!

### ISSUE THREAD

**Issue by dgt41** [joomla/joomla-cms#5832]
##### This regards the css changes made with #4575 

It seems that the changes in PR #4575 have some negative results on [3PD code](https://github.com/joomla/joomla-cms/pull/4575#issuecomment-70591897)

###### Some insight from my point of view and the reason I decided to change the width of the modals:

First of all that PR was part of a series of PRs {#4513 #4514 #4561 #4562 #4563} that tried to convert most of the mootools modals to use the bootstrap code. The problem that I faced in the process was the width of the modal, which was defined to some predefined pixels [width: 580px;] and that made a lot of the modals look really weird. There were two options to solve this problem:
1 Define some css values every time a modal needed some space, see [here](https://github.com/dgt41/joomla-cms/commit/3e35931601e23e47ab6664820b28a19e72722895) 
2 Make the initial modal values bigger so that can accommodate any iframe size, started [here](https://github.com/joomla/joomla-cms/pull/4561#discussion-diff-18761927)

Initially I followed the first path, but somewhere along the way I switched to editing the bootstrap modal less file and so a predefined width: 80%; came along.

Since all the bootstrap modals, also in this case, is uniquely named (class="multiLangModal") I propose to either 
add the style overrides directly to the template.less of isis and hathor
OR 
use define (add some) styles when the modal is generated

PLT please advise what will be the best solution for this and I will provide the changes.

**Comment by 810** [comment]
Any news?
