### ISSUE TITLE
Ordering Access Levels

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#5834]
If you look at the access levels in any filter then you will see that there appears to be no logical order. It is not alphabetical or hierarchical or by ID.

Looking into this further it would appear that the "sort" is based on the value of `ordering` in `#__viewlevels`

Here we can see that in a clean install 

id |title |	ordering  
--------|----|----
|1|Public|	0	
|2|Registered |1
|3|Special|	2
|5|Guest|	0
|6|Super Users|	0	

So the order they are displayed in is the illogical Public, Guest, Super, Registered, Special

I like order. Dont care what order as long as there is some logic behind it

I thought about changing the ordering values in the DB but thats no good as new access levels are always created with an ordering value of 0

It looks to me as if the ordering column is a remnant of something either no longer used or never implemented ** but ** it is being used in the queries and that is preventing any logical sorting order.

To get some order back I thought we could just Change the install data to give all of these an ordering of 0 and then they would be alpha sorted which is true in `/index.php?option=com_users&view=levels` but not in the filters. 

Not something I have been able to resolve with my skill level but I would have thought a real developer could find and fix it easily.

**Comment by JoomliC** [comment]
Hi Brian,

In this file : ROOT/libraries/cms/html/access.php the first order is by levels ordering, and after by title if same ordering.
I agree with you that ordering of pre-defined access levels is not well set on fresh install, and not ordered by ordering ASC as it should be in com_users access levels view (and as it is in filter and select field input).

I think this PR could solve issue, and keep it logical in all places : https://github.com/joomla/joomla-cms/pull/5899

Cyril<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5834">issues.joomla.org/joomla-cms/5834</a>.</sub>

**Comment by brianteeman** [comment]
Please see #5899 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5834">issues.joomla.org/joomla-cms/5834</a>.</sub>
