### ISSUE TITLE
$root_user automatic deletion don't work

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#5836]
#### Steps to reproduce the issue

- add the $root_user value to the configuration.php (see: https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F#Method_1:_configuration.php_file)
- Login into the backend
- notice the message
- try the link to remove the root user entry automatically (`Click here to try to do it automatically.`)

`http://www.example.org/administrator/index.php?option=com_config&task=application.removeroot&38c457982fff49a4c11a46989cd3b10f=1`
#### Expected result

the $root_user var gets removed from the configuration.php.

#### Actual result

```
Warning: Creating default object from empty value in JROOT\administrator\components\com_config\config.php on line 28

Fatal error: Call to undefined method stdClass::execute() in JROOT\administrator\components\com_config\config.php on line 31
```

#### Additional comments

It works with 2.5.28

**Comment by brianteeman** [comment]
I can confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5836">issues.joomla.org/joomla-cms/5836</a>.</sub>

**Comment by prasoon2211** [comment]
I looked into this. The error is in `./administrator/components/com_config/controller/application/removeroot.php`, line 107 where the `$controllerName` is found wrong and that returns a bool instead of a `JController`. I'll submit a patch soon.

**Comment by brianteeman** [comment]
Great

On 22 January 2015 at 09:46, Prasoon Shukla <notifications@github.com>
wrote:

> I looked into this. The error is in
> ./administrator/components/com_config/controller/application/removeroot.php,
> line 107 where the $controllerName is found wrong and that returns a bool
> instead of a JController. I'll submit a patch soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5836#issuecomment-70995261>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
Thanks @prasoon2211 PR is https://github.com/joomla/joomla-cms/pull/5867 closing here<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5836">issues.joomla.org/joomla-cms/5836</a>.</sub>

**Comment by cferrarini** [comment]
Detected the same error messages when clicking on the "Options" Gear Icon top-right corner - Managing articles or Menus.
It is a fresh installation of 3.65 Joomla Yootheme Master 2 demo.
It is curious that I do not recognize the path '/home/storage/c/71/41/chmconsultores3'...


Warning: Creating default object from empty value in /home/storage/c/71/41/chmconsultores3/public_html/site/administrator/components/com_config/config.php on line 28

Fatal error: Call to undefined method stdClass::execute() in /home/storage/c/71/41/chmconsultores3/public_html/site/administrator/components/com_config/config.php on line 31<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5836">issues.joomla.org/tracker/joomla-cms/5836</a>.</sub>
