### ISSUE TITLE
Wrong text: Category Manager: Articles

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#5853]
#### Steps to reproduce the issue
Backend
Go to Content - Category Manager
The header is Category Manager: Articles
#### Expected result

Category Manager: Categories

#### Actual result

Category Manager: Articles

#### System information (as much as possible)

![screen shot 2015-01-21 at 10 24 08](http://issues.joomla.org/uploads/1/8b2050140868f9c9766b5e0efa5cd3b5.png)

**Comment by mbabker** [comment]
This is expected behavior.  It is designed to tell you which extension's categories you're managing (same can be seen with the banner component).

**Comment by brianteeman** [comment]
Yes it can be a little confusing but it is the correct text for the reasons
that @mbabker explained. If you go to the banners and contact components
you will see it clearly.

**Comment by MartijnMaandag** [comment]
Yes I do understand now what the intention is.
The banners helped me to understand. They are better as the Articles, but still confusing because there is no Category Manager.
I do suggest the following:
Change the Banners - Categories from 
**Category Manager: Banners**
Into
**Banner Manager: Categories**
This way the Categories inside Banners have the same heading as Banners, Clients and Tracks.
For Contacts, Newsfeeds and Web Links  the same;-)
And the Articles?
I did attach an example where the structure is the same as Banners. Change the header from
**Category Manager: Articles**
into
**Article Manager: Categories**
![screen shot 2015-01-22 at 04 45 17](http://issues.joomla.org/uploads/1/ae3c406ea08d129d5a294737813142b5.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5853">issues.joomla.org/joomla-cms/5853</a>.</sub>

**Comment by brianteeman** [comment]
I see what you mean. I understand why it is named the way it is. It's the
category component. But I like your idea. I will bring it up with the
interface working group.
