### ISSUE TITLE
Possible 0 day

### ISSUE THREAD

**Issue by Hemn77** [joomla/joomla-cms#5855]
#### Steps to reproduce the issue
Could not login to the admin panel for my website, once checked the database, realised all the username/passwords were changed to admin/admin.
Had a backup from a month ago, downloaded a current version of the site to check if the MD5 of the files matched, found nothing suspicious amongst the files. Not sure if it is one incident and something wrong with other services or is it joomla specific. So, I thought I should report it here just to have it looked into even if brief. 

##### Modules Installed 
NoNumber Advanced
NoNumber Extension 
Phoca Font
Adeeba Backup 
Easy Frontended SEO 
Advanced Module Manager
NoNumber Extension Manager
Content - RokInjectModule 
##### System Info 
Database Version 	5.5.40-cll
Database Collation 	utf8_general_ci
PHP Version 	5.4.28
Web Server 	Apache/2.2.27 (Unix) mod_ssl/2.2.27 OpenSSL/0.9.8e-fips-rhel5 mod_bwlimited/1.4
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0 

#### Additional comments
There are no other admins on the system, but everyone was made an admin on the system. The number of users were about 10 as the site is mainly about giving information out but it is amongst the 200's websites within the country according to Alexa. 

I changed the password  and username for the two main admins and deleted the rest. I have also changed the password to the database.

**Comment by mbabker** [comment]
Report security issues to the Joomla! Security Strike Team (JSST) at security@joomla.org or with the [JSST contact form](http://developer.joomla.org/contact-security-team.html), please do not use the public tracker for security issues.
