### ISSUE TITLE
in com_finder Publish up/down filtering don't really work

### ISSUE THREAD

**Issue by Hoffi1** [joomla/joomla-cms#5859]
Caused by a typo in FinderModelSearch::getListQuery()
line 234 should instead of
```	$query->where('(l.publish_start_date = ' . $nullDate . ' OR l.publish_end_date <= ' . $nowDate . ')')``` 
be 
```	$query->where('(l.publish_start_date = ' . $nullDate . ' OR l.publish_start_date <= ' . $nowDate . ')')```
(...start... instead of ...end...)

Test:
create articles with
(1) Publish up in past and Publish down in future
(2) Publish up and down in past
(3) Publish up and down in future
(4) Publish up in past, no Publish down
(5) Publish up in future, no Publish down
and let finder find them all.
It should show (1) and (4).
But it shows (4) and (5).

**Comment by zero-24** [comment]
@hoffi1 can you create a pull request against staging?

If you need help please have a look into this doc page:
https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

Thanks! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5859">issues.joomla.org/joomla-cms/5859</a>.</sub>

**Comment by Hoffi1** [comment]
@zero-24: done, PR pending. :smile:

**Comment by zero-24** [comment]
Thanks so i close here as we have a PR here: https://github.com/joomla/joomla-cms/issues/5869 Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5859">issues.joomla.org/joomla-cms/5859</a>.</sub>
