### ISSUE TITLE
Deactiveted Contact still listed on website

### ISSUE THREAD

**Issue by Johan1990** [joomla/joomla-cms#5860]
#### Steps to reproduce the issue
- Create an contact (person) in Joomla!
- Add a menu with categorie list of all categories
- Check if contact is listed
- Go to backend and deactivated the contact
- Now go back to the website and refresh

#### Expected result
- Contact will still not be shown

#### Actual result
- Contact still be shown!

#### System information (as much as possible)
- Google Chrome
- Joomla 3.3.6 Dutch

**Comment by brianteeman** [comment]
I suspect this is a cache issue

Please go to to System->Clear Cache
Do you have a list of cached items there
Select them all and then Delete the cache

On 21 January 2015 at 22:40, Johan1990 <notifications@github.com> wrote:

> Steps to reproduce the issue
>
>    - Create an contact (person) in Joomla!
>    - Add a menu with categorie list of all categories
>    - Check if contact is listed
>    - Go to backend and deactivated the contact
>    - Now go back to the website and refresh
>
> Expected result
>
>    - Contact will still not be shown
>
> Actual result
>
>    - Contact still be shown!
>
> System information (as much as possible)
>
>    - Google Chrome
>    - Joomla 3.3.6 Dutch
>
> Additional comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5860>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Johan1990** [comment]
Thanks for your Quick respons!

Don't think so, the contacts (a few) where deactivated for months.
I also cleared my cache in Joomla. It was still the same.

Regards,
Johan


Verstuurd vanaf mijn iPhone

> Op 21 jan. 2015 om 23:54 heeft Brian Teeman <notifications@github.com> het volgende geschreven:
> 
> I suspect this is a cache issue 
> 
> Please go to to System->Clear Cache 
> Do you have a list of cached items there 
> Select them all and then Delete the cache 
>

**Comment by brianteeman** [comment]
Can you temp switch to one of the default templates eg protostar. Is the
contact gone,? If so then its a bug in your template

**Comment by brianteeman** [comment]
I cant replicate this with default joomla contact component and the default protostar template<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5860">issues.joomla.org/joomla-cms/5860</a>.</sub>

**Comment by Johan1990** [comment]
Hi,

I have tried to make a new contact and replicate the problem again.
Strange enough, it works now!
Make the contact, saw the contact listed, deactivated the contact, and 
he was gone.
Don't know what was the problem yesterday....
Maybe it was still the cache because I'm using know another computer. 
Altough, when I completely removed the contact (from trash also), the 
contact was gone yesterday.
Can't explain it any more. Maybe you know?

For know, problem solved (I think)!

Thanks!!

Regards, Johan

Brian Teeman schreef op 2015-01-22 00:12:

**Comment by zero-24** [comment]
Thanks for the feedback @Johan1990 so I'm closing here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5860">issues.joomla.org/joomla-cms/5860</a>.</sub>
