### ISSUE TITLE
Media form field uses mootools modal

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#5861]
We're still using the mootools modal for the media manager window (https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/form/field/media.php#L374, mootools behaviour called on https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/form/field/media.php#L204).

It would be nice to convert this to the bootstrap modal after @smanzi 's awesome improvements in https://github.com/joomla/joomla-cms/pull/5087 and remove this mootools dependency

Posting it as an issue to remind me or let someone else (@dgt41 or @smanzi ?) work on it as not gonna have the time until early next week to be able to work on this.

**Comment by dgt41** [comment]
I have some code already, so whenever ready (the renderer part) will make any edits and create a PR 😄
Repo [here](https://github.com/dgt41/joomla-cms/tree/_field_media)
Also I think part of 3.5 should be:
#4563 Admin com_messages modal
#4645 Admin com_templates modals
#4661 Admin com_menus modals
#5652 Plugins editors-xtd modals
#5654 Form field content history
#5655 Form field User

**Comment by dgt41** [comment]
#5871 Form field Media

**Comment by dgt41** [comment]
Also another (hopefully this is the last one)
#5873 User note modal

Right now, some of those (old) PRs have conflicts or need some touches since the changes of #5087, will do it after 3.4 is out

**Comment by brianteeman** [comment]
Has this been resolved elsewhere? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5861">issues.joomla.org/joomla-cms/5861</a>.</sub>

**Comment by wilsonge** [comment]
This is just a list of PR's I think. The media manager using Mootools definitely got resolved

**Comment by dgt41** [comment]
Except the xtd buttons everything else is already solved. The xtd buttons is another one that needs to be done...
