### ISSUE TITLE
Problem with Repeatable form field type and type field MEDIA

### ISSUE THREAD

**Issue by Orsey** [joomla/joomla-cms#5868]
Hello everyone.
I have problem with Repeatable form field type when I added field type "media" in Repeatable form.
After repeated fields, window of media component do not open in modal window, his open as one page.

**Comment by Fedik** [comment]
it already fixed #3574 
and will be available with next Joomla! 3.4

**Comment by zero-24** [comment]
Thanks for the update @Fedik so i closing here as `Fixed in Code Base`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5868">issues.joomla.org/joomla-cms/5868</a>.</sub>

**Comment by Orsey** [comment]
Thanks for all. This is realy working.

**Comment by motamedimasoud** [comment]
how it worked for U Orsey i have problem when i want to save one pic it doesent save or it doesent cancell the page<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5868">issues.joomla.org/joomla-cms/5868</a>.</sub>

**Comment by Orsey** [comment]
motamedimasoud, I'm applied changes in two files, which have been described in this page https://github.com/joomla/joomla-cms/pull/3574/files. And after that, he began to work, and all changes in repeatable fields are saved very good.
