### ISSUE TITLE
Menutype does not stay the same when doing Save&New

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#5870]
When creating a new menu item and clicking Save&New, the menutype is reset to nothing again. This is in contrast to the module manager, where Save&New directly shows the same moduletype again. I would encourage to always show the same menutype when clicking Save&New in the menu manager. If you didn't want the same type again, you would have to click on the modal anyway and if you do want the same menutype, you save 2 pageloads and a large amount of time.

**Comment by dgt41** [comment]
:+1:

**Comment by nternetinspired** [comment]
+100 This would be a really great change, it is something that has bugged mw for a long time.

What are your thoughts on implementing a similar behaviour for article category settings?

**Comment by elkuku** [comment]
:+1:

**Comment by yvesh** [comment]
Great idea

**Comment by brianteeman** [comment]
@Hackwar is this something you can code?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5870">issues.joomla.org/joomla-cms/5870</a>.</sub>

**Comment by Hackwar** [comment]
I'll take a look.

**Comment by brianteeman** [comment]
After so long without any code for anyone to test and see if this really is a great new feature I am closing this at this time. If someone creates the code then of course it will be reviewed. Thanks <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5870">issues.joomla.org/joomla-cms/5870</a>.</sub>
