### ISSUE TITLE
Position of Maintenance in Sidebar Control Panel

### ISSUE THREAD

**Issue by hvdmeer** [joomla/joomla-cms#5881]
#### Steps to reproduce the issue
The maintenance part in the sidebar is at the bottom of this sidebar. If your are not using a larger resolution (mine is 1440x900) it will we at the bottom of my screen and partly not visible.

I believe it's preferred that everyone can see immediately if there are any updates available. In my case I can't see if my extensions are up-to-date.

Is it possible to either have control of the sorting or that perhaps the maintenance part can be moved up so it will be visible for all (monitor) screens 

![Sidebar at 1440x900](http://i.imgur.com/PoI4SwK.png "Sidebar at 1440x900")

#### Expected result
Great visibility of updates

**Comment by brianteeman** [comment]
If your joomla is not up to date an additional message is displayed at the
top of the screen

**Comment by hvdmeer** [comment]
Is it? I'll check that. Also for the extensions?

**Comment by hvdmeer** [comment]
This added after an edit on Github, do edits not show on issues.joomla.org? 

Strike that, the update of Joomla is clearly visible in top. But I tested a extension and that was shown below my taskbar.

I was noticing the extension behavior not realizing that the Joomla updates are visible on top.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5881">issues.joomla.org/joomla-cms/5881</a>.</sub>

**Comment by zero-24** [comment]
>Strike that, the update of Joomla is clearly visible in top. But I tested a extension and that was shown below my taskbar.

This comes with the Update to 3.4 the PR was:  https://github.com/joomla/joomla-cms/pull/3411

If you have a Joomla and Extensionupdate it will look like:
https://docs.google.com/file/d/0ByOZwT1tIrz8UGg5cVA2dEd5Nmc/edit?pli=1

else you have one message.

**Comment by hvdmeer** [comment]
Okay, I searched the issues but I guess missed that one. Thanks. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5881">issues.joomla.org/joomla-cms/5881</a>.</sub>

**Comment by zero-24** [comment]
Thanks for the update @hvdmeer So I closing here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5881">issues.joomla.org/joomla-cms/5881</a>.</sub>
