### ISSUE TITLE
Unnecessary Mootools in Comboxbox

### ISSUE THREAD

**Issue by bassmanpaul** [joomla/joomla-cms#5889]
I've noticed that Mootools seems to be loaded in when the JForm combobox is used, but as far as I can tell the combobox runs on pure jQuery? Is there any reason for this? 

This is in all Joomla 3 series.

#### The File:
`libraries/cms/html/behavior.php line 214~`

#### The Code:
```
// Include MooTools framework
static::framework();
```

#### Should it be?:
```
// Include jQuery
JHtml::_('jquery.framework');
```

The combobox js that is eventually loaded in is:

`media/system/js/combobox-uncompressed.js`

**Comment by dgt41** [comment]
@bassmanpaul this is already solved in 3.4. You can try the latest staging (http://developer.joomla.org/cms-packages/) to check it out!
