### ISSUE TITLE
Change language file to NOT recommend using the mysql "root" user

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#5897]
Maybe a quick one for @brianteeman's efforts of one PR a day?

![screenshot 2015-01-27 22 25 25](https://cloud.githubusercontent.com/assets/400092/5928490/8a4521aa-a673-11e4-9da3-44371d680f00.png)

**Comment by brianteeman** [comment]
I am trying to think of the right wording that is appropriate for local and
remote installs

On 27 January 2015 at 22:27, Phil Taylor <notifications@github.com> wrote:

> Maybe a quick one for @brianteeman <https://github.com/brianteeman>'s
> efforts of one PR a day?
>
> [image: screenshot 2015-01-27 22 25 25]
> <https://cloud.githubusercontent.com/assets/400092/5928490/8a4521aa-a673-11e4-9da3-44371d680f00.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5897>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by PhilETaylor** [comment]
I actually thought I changed this in a PR years ago, maybe that was something else... 

Really, local installs should not use the "root" mysql user either - but developers (just like me) are lazy and use root all the time during development - Its still bad practice for all the same reasons as using the linux root user ... but then I dont need to educate you on that :) (and yes, I ALWAYS login as root on linux servers too haha).

It should be something along the lines of "This is the username of the user that has read/write permissions on the database"

I also think the database name should come before the user/pass :-) but thats just me :)

**Comment by brianteeman** [comment]
On 27 Jan 2015 22:34, "Phil Taylor" <notifications@github.com> wrote:
>
> I actually thought I changed this in a PR years ago, maybe that was
something else...
>

That was prefilling admin as the super user name

> Really, local installs should not use the "root" mysql user either - but
developers (just like me) are lazy and use root all the time during
development - Its still bad practice for all the same reasons as using the
linux root user ... but then I dont need to educate you on that :) (and
yes, I ALWAYS login as root on linux servers too haha).
>
> It should be something along the lines of "This is the username of the
user that has read/write permissions on the database"

I will write something tomorrow. Probably a bit less techy than that

>
> I also think the database name should come before the user/pass :-) but
thats just me :)

I will check and see what others do

**Comment by infograf768** [comment]
I indeed use `root` all the time locally.
I guess we can indeed change this, explicitely explaining that, even locally, it is a good idea to change settings to not use `root` but keep that word in the tip.
Be aware though that this change would require all installation ini files to be updated.

**Comment by brianteeman** [comment]
As we are in language string freeze for anything that would need translation this will have to be done after the 3.4 release.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5897">issues.joomla.org/joomla-cms/5897</a>.</sub>

**Comment by PhilETaylor** [comment]
So I guess this will not make 3.4.1 if the language is already frozen again? :-(

**Comment by infograf768** [comment]
Specially if no PR was made... Also, installation ini files changes requires a specific freeze to get as many as possible ready before the next release.

**Comment by PhilETaylor** [comment]
@infograf768 - Well I cant make a PR as:

1) I dont know which files, in what languages, you wish me to change, last time I tried to change a language it ended up in a million different people asking for a million different tiny changes

2)  Probably best for @brianteeman to provide some non developer fluffy english words instead of anything I could come up with

**Comment by zero-24** [comment]
@PhilETaylor @brianteeman please have a look into https://github.com/joomla/joomla-cms/pull/6721

**Comment by zero-24** [comment]
Closing here as we have a PR: https://github.com/joomla/joomla-cms/pull/6721 so PLT can decide if this should be changed or not.

**Comment by zero-24** [comment]
Restoring the state before #6721 as it is closed now
