### ISSUE TITLE
Local language folders are not used in com_finder and com_postinstall

### ISSUE THREAD

**Issue by st-anton** [joomla/joomla-cms#5900]
Both components look for the language file of the referencing plugin / component in the CORE language only (JROOT/administrator/language/). They look up the extensions name in the database and try to access the language files. The 'usual' behaviour of looking in the CORE language folder first and afterwards the extensions private folder does not exist.

Usage of local language files is defined in [JROOT/administrator/language/de-DE/de-DE.com_biblestudy.ini](JROOT/administrator/language/de-DE/de-DE.com_biblestudy.ini) and discussed in [http://issues.joomla.org/tracker/joomla-cms/5872#event-61189](http://issues.joomla.org/tracker/joomla-cms/5872#event-61189) and below.

#### System information
Present in Joomla! 3.3.6

**Comment by infograf768** [comment]
This behavior is normal. Our core components do not provide extension language folders.

**Comment by Bakual** [comment]
@infograf768 I think what he means is that com_finder and com_postinstall should search for language files of 3rd party extensions in the local folders first like we do everywhere else.

Apparently they only search for langaueg files in the global folders.

I don't know if that is true, I haven't verified. But I think that's what he means.

**Comment by bcordis** [comment]
I can verify this on latest build. There Joomla dos not look at the locale component language folder for string under the com_finder and com_postinstsll. Right now we are having to do work around a for this.

This should be looking for this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5900">issues.joomla.org/joomla-cms/5900</a>.</sub>

**Comment by chrisdavenport** [comment]
Hi @st-anton you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.  Thank for raising the issue.

**Comment by chrisdavenport** [comment]
Set to "closed" on behalf of @chrisdavenport by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5900">issues.joomla.org/joomla-cms/5900</a>
