### ISSUE TITLE
Nowhere to add Recaptcha 2.0 Snippet at end of form(s)

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#5902]
#### Steps to reproduce the issue

Register a site at Google Recaptcha to get API Keys.
Insert generated Keys in Plugin
Instructions from Google :
Add Snippet to index.php : <script src='https://www.google.com/recaptcha/api.js'></script>
Add Snippet to End of form(s) : <div class="g-recaptcha" data-sitekey="????????????????????????????"></div>

#### Expected result
Fields to enter Snippets

#### Actual result

No Fields available

#### Additional comments
 -> Nowhere to do this except as an override. Maybe add appropriate fields in the plugin or Fields in the Contact Manager Options

**Comment by brianteeman** [comment]
https://docs.joomla.org/How_do_you_use_Recaptcha_in_Joomla%3F

**Comment by coolman01** [comment]
That description refers to recaptcha version 1.0

Version 2.0 has different instructions from google

**Comment by brianteeman** [comment]
You only have to follow the instructions I gave you - the plugin does everything else for you. Please try and follow the instructions and you will see.

**Comment by coolman01** [comment]
Thanks Brian.
I've been using recaptcha for years, but as I read in the announcement for joomla 3.4 beta, one new addition is the choice between recaptcha version 1.0 and version 2. I've tested it out now on my testsite and I see what you mean. Apparently I can ignore the instructions supplied by google.com/recaptcha when registering my domain for a key.
Sorry for my confusion.
![recaptcha](https://cloud.githubusercontent.com/assets/6746747/5937546/2098f988-a6f1-11e4-84b9-c9fc6c413444.jpg)
