### ISSUE TITLE
Visual clutter in Hathor > Global Configuration

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#5906]
The permission section in hathor > global configuration is somewhat distorted/misplaced.

This is how it looks like in firexfox 35.0.1:

![hathor_firefox](https://cloud.githubusercontent.com/assets/9270310/5937764/fbdbdb3a-a6f3-11e4-969a-b1b58c897e83.png)

And here a screenshot taken from IE 11:

![hathor_ie](https://cloud.githubusercontent.com/assets/9270310/5937777/2227ad28-a6f4-11e4-9741-9e8d164c5305.png)

It displays nice though in google chrome. Tested with latest staging.

**Comment by brianteeman** [comment]
The issue us that the tabs are not being loaded<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5906">issues.joomla.org/joomla-cms/5906</a>.</sub>

**Comment by waader** [comment]
Thanks @brianteeman. The solution/problem can be found here: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/view/application/html.php#L77

Simply setting hidemainmenu to false would solve the problem. The question is, if it breaks something?

**Comment by brianteeman** [comment]
That comes from https://github.com/joomla/joomla-cms/pull/4844

On 29 January 2015 at 15:03, waader <notifications@github.com> wrote:

> Thanks @brianteeman <https://github.com/brianteeman>. The
> solution/problem can be found here:
> https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/view/application/html.php#L77
>
> Simply setting hidemainmenu to false would solve the problem. The question
> is, if it breaks something?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5906#issuecomment-72039051>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by waader** [comment]
Thanks! How did you find the "responsible" patch so quick?

@dgt41 Could you have a look at this?

**Comment by brianteeman** [comment]
From the link you gave me I clicked on History at the top

On 29 January 2015 at 15:11, waader <notifications@github.com> wrote:

> Thanks! How did you find the "responsible" patch so quick?
>
> @dgt41 <https://github.com/dgt41> Could you have a look at this?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5906#issuecomment-72040339>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by dgt41** [comment]
@waader It’s not related to #4844. It’s more a clearfix problem (try renaming tab class to clearfix 😉 )

**Comment by brianteeman** [comment]
No that is not correct. Yes changing class=tab to class=clearfix will
resolve the layout clutter but that is not what it is supposed to look like
- it is supposed to be in tabs.

See this screenshot from 3.3.6 showing the 5 tabs Site - system- server -
permissions - text filters

[image: Inline images 1]

On 29 January 2015 at 15:21, Dimitris Grammatiko <notifications@github.com>
wrote:

> @waader <https://github.com/waader> It’s not related to #4844
> <https://github.com/joomla/joomla-cms/pull/4844>. It’s more a clearfix
> problem (try renaming tab class to clearfix [image: 😉] )
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5906#issuecomment-72042158>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by waader** [comment]
@dgt41 Sorry, I can't do anything with it. I am lost.

**Comment by waader** [comment]
@brianteeman  Thanks for the info. Learned something.

**Comment by dgt41** [comment]
@brianteeman I was comparing the output with safari, thus I thought is a clearfix problem. But honestly I cannot relate the problem to disable menu PR.

**Comment by brianteeman** [comment]
I dont know why it relates to that PR but reverting it resolves the issue

On 29 January 2015 at 15:35, Dimitris Grammatiko <notifications@github.com>
wrote:

> @brianteeman <https://github.com/brianteeman> I was comparing the output
> with safari, thus I thought is a clearfix problem. But honestly I cannot
> relate the problem to disable menu PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5906#issuecomment-72044669>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by waader** [comment]
Just change the parameter to false.

**Comment by dgt41** [comment]
@brianteeman @waader Found the problem https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/hathor/index.php#L128
If this line changed to `<?php if ($app->input->getInt('hidemainmenu')) : ?>` remove the `!` all work fine
So I think we should see why this line breaks the tabs...

**Comment by dgt41** [comment]
Actually is easier to revert #4844

**Comment by waader** [comment]
Reading this is http://stackoverflow.com/questions/12671708/whats-jrequestsetvarhidemainmenu-1 I would agree to revert #4844.

**Comment by dgt41** [comment]
Ok,  please test: #5925

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5906">issues.joomla.org/joomla-cms/5906</a>.</sub>
