### ISSUE TITLE
When upgrade from 3.3.6 to 3.4 beta1 some menu items have been moved to the trash

### ISSUE THREAD

**Issue by francescodim** [joomla/joomla-cms#5908]
.

**Comment by mbabker** [comment]
Can you provide details?  What items, site/admin, etc.

**Comment by francescodim** [comment]
![senza titolo-1](https://cloud.githubusercontent.com/assets/6338179/5955292/c2d2c994-a7a1-11e4-8e95-b2da17523dcd.jpg)

same site menu items have the field "published" set to -2 in db

**Comment by brianteeman** [comment]
Do you have a backup of the site before the upgrade you can share so people
can test and see it happen

**Comment by brianteeman** [comment]
Closing at this time as it may have been specific to the beta release. It can always be reopened if necessary<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5908">issues.joomla.org/joomla-cms/5908</a>.</sub>
