### ISSUE TITLE
Return error when try installation extension with more one relates libraries

### ISSUE THREAD

**Issue by shandak** [joomla/joomla-cms#5909]
#### Steps to reproduce the issue
In release version all work as expected.
Bug in J3.4.0b1 when try install components with relate libraries ex:
&lt;libraries&gt;
   &lt;library name="redshop"/&gt;
   &lt;library name="tcpdf"/&gt;
&lt;/libraries&gt;
First library install as expected.
When joomla try install second library, he try copy files who set in first xml library.

#### Expected result
All relates libraries must be install.

#### Actual result
Broken installation process. Error: Library %s: Could not copy files from the source![screen shot 2015-01-28 at 07 11 11](http://issues.joomla.org/uploads/1/7513d77edb5cf437c180f41d3aa626aa.png)

**Comment by mbabker** [comment]
Do you have a package that can be tested with?  As far as I'm aware, the core system has never su

**Comment by mbabker** [comment]
Ugh, fat finger on mobile, sorry.

... never supported this style XML which would mean you have to process this in an install script.  With some tweaking in the JInstaller library, it is suggested to not use the singleton JInstaller::getInstance to fetch an instance because of object caching.  Maybe you're hitting this issue?

**Comment by shandak** [comment]
You right, i have some process in install script. 
But for each library use new object $install = new JInstaller. 
So cache cant be set there as i understand.
In bottom exmple function with install libraries
private function installLibraries($parent)
	{
		// Required objects
		$installer = new JInstaller;
		$manifest  = $parent->get('manifest');
		$src       = $parent->getParent()->getPath('source');

		if ($nodes = $manifest->libraries->library)
		{
			foreach ($nodes as $node)
			{
				$extName = $node->attributes()->name;
				$extPath = $src . '/libraries/' . $extName;
				$result  = 0;

				if (is_dir($extPath))
				{
					$result = $installer->install($extPath);
				}

				$this->_storeStatus('libraries', array('name' => $extName, 'result' => $result));
			}
		}
	}<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5909">issues.joomla.org/joomla-cms/5909</a>.</sub>

**Comment by shandak** [comment]
Guys thank you for help, i find a cache. Realy i use singleton. Need move $installer = new JInstaller; in foreach.
Issue can be closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5909">issues.joomla.org/joomla-cms/5909</a>.</sub>

**Comment by zero-24** [comment]
Closing as requested thanks for the update<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5909">issues.joomla.org/joomla-cms/5909</a>.</sub>
