### ISSUE TITLE
Frontend edit: category list, not adding new article to chosen category

### ISSUE THREAD

**Issue by ptopenweb** [joomla/joomla-cms#5911]
#### Steps to reproduce the issue
Create a menu item with category list, chose a category other than uncategorized.
In frontend edit create "New" to create an article in that category, some text and save.

#### Expected result
Ths article should be same saved in the chosen category (the one the menu item points). 

#### Actual result
Ths article is not saved in the chosen category. 

#### System information (as much as possible)
Joomla 3.3.6
Default template

#### Additional comments
Also there seems to be similiar problems with the languague combobox too (try in a multilangue setup).

**Comment by brianteeman** [comment]
I can not confirm this on a clean install using the default templates and using the testing sample data

**Comment by ptopenweb** [comment]
Will test again.

**Comment by ptopenweb** [comment]
yes you are right, the problem has on one plugin.
It's working properly
