### ISSUE TITLE
Backend mobile menu dropdown stops working

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#5912]
On smaller devices, the mobile menu toggle seems to be acting oddly.

**1st click** = menu slide down
**2nd click** = menu slide up
**3rd click** = menu slide down
**4th click** = Nothing happens

No errors are appearing in the console log when it stops working.

Tested on Firefox (latest stable, developer and beta) and Chrome (latest).

![mobile-menu](https://cloud.githubusercontent.com/assets/2019801/5940466/fe0a2c40-a702-11e4-82d8-e6450e62b8a0.jpg)

I've started trying to debug the issue and will submit a pull request if I find a solution

**Comment by brianteeman** [comment]
Weird I can see that too

On 28 January 2015 at 15:39, Lodder <notifications@github.com> wrote:

> On smaller devices, the mobile menu toggle seems to be acting oddly.
>
> *1st click* = menu slide down
> *2nd click* = menu slide up
> *3rd click* = menu slide down
> *4th click* = Nothing happens
>
> No errors are appearing in the console log when it stops working.
>
> Tested on Firefox (latest stable, developer and beta) and Chrome (latest).
>
> [image: mobile-menu]
> <https://cloud.githubusercontent.com/assets/2019801/5940466/fe0a2c40-a702-11e4-82d8-e6450e62b8a0.jpg>
>
> I've started trying to debug the issue and will submit a pull request if I
> find a solution
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5912>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by C-Lodder** [comment]
@brianteeman - fixed the issue. See: https://github.com/joomla/joomla-cms/pull/5913

**Comment by zero-24** [comment]
Closing here as we have a PR by @C-Lodder https://github.com/joomla/joomla-cms/pull/5913 Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5912">issues.joomla.org/joomla-cms/5912</a>.</sub>
