### ISSUE TITLE
sidebar is meshing up debug output on modals

### ISSUE THREAD

**Issue by dgt41** [joomla/joomla-cms#5916]
#### Modals rendering is weird when debug is on

On the latest staging try:
create a user note
Enable debug
go to administrator/index.php?option=com_users&view=users
click on the display  note button
observe the rendered modal
Broken:
![screen shot 2015-01-29 at 4 07 23](https://cloud.githubusercontent.com/assets/3889375/5951267/8d5af98c-a76d-11e4-8453-36fb10bccca5.png)

If we take out the j-toggle-main, the j-toggle-main and set width to 97% in the respected divs everything is back to normal:
![screen shot 2015-01-29 at 4 07 03](https://cloud.githubusercontent.com/assets/3889375/5951263/5bcde78a-a76d-11e4-93f8-97523932c0fe.png)

**Comment by infograf768** [comment]
Closing as PR is proposed https://github.com/joomla/joomla-cms/issues/5917
