### ISSUE TITLE
The sidebar arrow jumps when there is a message in com_installer

### ISSUE THREAD

**Issue by javigomez** [joomla/joomla-cms#5920]
This is a very minor issue.

#### Steps to reproduce the issue
Check this video: http://www.youtube.com/watch?v=Calf4MOuhzc
If you install a component in joomla administrator you will see the effect.

The problem is that Messages div is over the rest of the contents of the page

#### Expected result
The arrow to open the menu sidebar doesn't jump after sidebar collapses

#### Actual result
The arrow to open the sidebar jumps after the sidebar collapses

**Comment by brianteeman** [comment]
Also please see #5928 it "might" be a related bug

**Comment by designbengel** [comment]
Seems this issue is solved by another PR ? I have a different icon in nothing is "jumping".

**Comment by zero-24** [comment]
Thanks @designbengel Closing here.
