### ISSUE TITLE
Button order 3.4 Options Help

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-cms#5921]
![help-options](https://cloud.githubusercontent.com/assets/736887/5955981/955a3b4c-a7a0-11e4-8b72-0b17cfb03625.png)

What is the correct order of the two buttons highlighted on the screenshot - Options Help.
 
Check these pages linked from the sidebar of Extension Manager:

Install [Help Option]
Update [Option Help]
Manage [Options Help]
Discover [Options Help]
Database [Help Options]
Warnings [Help Options]
Install Lang [Help Options]
Update sites [Options Help]

**Comment by brianteeman** [comment]
I would go with help- options

**Comment by brianteeman** [comment]
Having looked closer it appears that the standard everywhere is Help - Option

I will do a PR to standardise on this

Good fin @Hils Consistency Rocks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5921">issues.joomla.org/joomla-cms/5921</a>.</sub>

**Comment by Hils** [comment]
Thanks for checking Brian and thank you for doing the PR. I did actually just fork 3.4-dev to exercise my PR muscles but you will be far faster than me - cheers!

**Comment by brianteeman** [comment]
Sorry @hils I am going to have to re-open this one and leave the PR to someone else.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5921">issues.joomla.org/joomla-cms/5921</a>.</sub>

**Comment by Hils** [comment]
no problem. Has someone said they would do it or should I try and do it tomorrow?

**Comment by brianteeman** [comment]
Go for it

On 29 January 2015 at 12:04, Hils <notifications@github.com> wrote:

> no problem. Has someone said they would do it or should I try and do it
> tomorrow?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5921#issuecomment-72013609>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
@hils Just shout if you need help :smile:

**Comment by Hils** [comment]
Thank you Thomas! It is my morning job tomorrow - will try my best :)

**Comment by zero-24** [comment]
@Hils 

Just a tip
>I did actually just fork 3.4-dev 

Please send the PR against `staging` and not `3.4-dev` as  `3.4-dev` is out of sync and the last changes are in the `staging` branche. :smile: 

IIRC `3.4-dev` is only not deleted to not autoclose the still open PRs against it.

**Comment by Hils** [comment]
Great tip and thanks for thinking! Will fork staging and delete my 3.4-dev fork in the morning :)

**Comment by brianteeman** [comment]
Please see #6071 for a solution<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5921">issues.joomla.org/joomla-cms/5921</a>.</sub>
