### ISSUE TITLE
editing module in front doesn't work (random error)

### ISSUE THREAD

**Issue by micker** [joomla/joomla-cms#5927]
very strange problem ...
i allow editing module in front ..
some module work but some other not ... 
link to edit ok
url to edit ok
but we are redirect on same page without form ....
i can send some access for testing

**Comment by zero-24** [comment]
@micker can you add some more information? What version of Joomla?

Have you try the current beta? https://github.com/joomla/joomla-cms/releases/tag/3.4.0-beta1

**Comment by brianteeman** [comment]
Is it a specific module type<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5927">issues.joomla.org/joomla-cms/5927</a>.</sub>

**Comment by micker** [comment]
yes beta 1
custom module sometime...
in same page => some one can be edit .. and other not, alway redirect to same page (loop)
it's realy strange

**Comment by brianteeman** [comment]
I can't replicate this. Can you send me access via the contact form on my blog http://brian.teeman.net so I can try yo replicate it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5927">issues.joomla.org/joomla-cms/5927</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for sending the details. 

I was able to edit all the modules EXCEPT for the ones that you specified in your email.

I suspect it may be an issue with your template as I can see some issues with it. For example if you switch to protostar you will see that you have `Bauzelle" />` on screen in the top right.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5927">issues.joomla.org/joomla-cms/5927</a>.</sub>

**Comment by micker** [comment]
i checkedmore ... i am not sure about template i found this code in header
<meta property="og:title" content="<div class="editable" data-id="34" data-context="article" data-type="title" data-itemtype="article" contenteditable="true">Toulouse</div>" />
=> that broke html in front
maybe it's in relation with an other error in backend
menu edition view
ReferenceError: $K2 is not defined
$K2(document).ready(function () {
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5927">issues.joomla.org/joomla-cms/5927</a>.</sub>

**Comment by micker** [comment]
sorry i forgot => protstar have same problme with html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5927">issues.joomla.org/joomla-cms/5927</a>.</sub>

**Comment by brianteeman** [comment]
I think it is fair to say that you have an issue on your site that is
showing itself in multiple ways one of which is in the front end module
edit feature.

sorry i forgot => protstar have same problme with html
------------------------------
This comment was created with the J!Tracker Application
<https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/5927
<http://issues.joomla.org/tracker/joomla-cms/5927>.

—
Reply to this email directly or view it on GitHub
<https://github.com/joomla/joomla-cms/issues/5927#issuecomment-72382450>.

**Comment by micker** [comment]
it's maybe a editor problem ...if i desactived arkeditor no error but acl heritage is strange => report to ark team
.. continu here
http://issues.joomla.org/tracker/joomla-cms/5397<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5927">issues.joomla.org/joomla-cms/5927</a>.</sub>

**Comment by brianteeman** [comment]
Closing as problem is resolved when removing non core extension<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5927">issues.joomla.org/joomla-cms/5927</a>.</sub>
