### ISSUE TITLE
alert of extension update - missing in list of updates

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-cms#5931]
![extension-update-available](https://cloud.githubusercontent.com/assets/736887/5976202/223fa690-a883-11e4-8ca8-23e7b01343d2.PNG)

[sitename]/administrator/index.php

Using the 'update now' button goes to next screen which says there is no extension update available.

![extension-update-available-not](https://cloud.githubusercontent.com/assets/736887/5976237/6c4a1630-a883-11e4-9c30-58dceb28b302.PNG)

**Comment by brianteeman** [comment]
Press Find Updates - what do you get?

I bet it will find something

(and yes this is plain daft)

On 30 January 2015 at 13:26, Hils <notifications@github.com> wrote:

> [image: extension-update-available]
> <https://cloud.githubusercontent.com/assets/736887/5976202/223fa690-a883-11e4-8ca8-23e7b01343d2.PNG>
>
> [sitename]/administrator/index.php
>
> Using the 'update now' button goes to next screen which says there is no
> extension update available.
>
> [image: extension-update-available-not]
> <https://cloud.githubusercontent.com/assets/736887/5976237/6c4a1630-a883-11e4-9c30-58dceb28b302.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5931>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hils** [comment]
Clicking the 'not very obvious' discover button top left which is out of direct view - ie admin's eye is drawn immediately to the 'there are no updates' alert. Would it not be better if the sequence of views was first view above and, if there is an update, move straight to the third view so stop the need for the intermediate 'discover' action when it has already been discovered by Joomla. Very confusing.

![extension-update-available-discover](https://cloud.githubusercontent.com/assets/736887/5976327/6435c092-a884-11e4-8c34-75bb8fac017e.PNG)

**Comment by Hils** [comment]
we cross-posted! I was only half done :D

**Comment by brianteeman** [comment]
I 10000000% agree with you hils

Unfortunately the last time I brought this up it was shouted down very

On 30 January 2015 at 13:32, Hils <notifications@github.com> wrote:

> we cross-posted! I was only half done :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5931#issuecomment-72200757>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hils** [comment]
Well let those who disagreed last time please show the logic AGAINST this suggestion! Thanks :)

**Comment by mbabker** [comment]
If I'm not mistaken, there was once upon a time immediate display of extension updates when you clicked the quick icon link...

**Comment by brianteeman** [comment]
The reasoning was that it was very slow. You will need to search for the
explanation by IIRC @nikosdion

**Comment by brianteeman** [comment]
I "think" this is where the discussion took place #3775 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5931">issues.joomla.org/joomla-cms/5931</a>.</sub>

**Comment by brianteeman** [comment]
I have updated the title to be clearer about the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5931">issues.joomla.org/joomla-cms/5931</a>.</sub>

**Comment by Hils** [comment]
Thanks for finding that Brian. Let me know if you want this closed. It looks like we might not find a Developer to agree :(  (the alert isn't missing is it? - re title update)

**Comment by brianteeman** [comment]
alert of extension update - missing in list of updates

I personally dont want it closed. I see it as a bug

On 30 January 2015 at 14:46, Hils <notifications@github.com> wrote:

> Thanks for finding that Brian. Let me know if you want this closed. It
> looks like we might not find a Developer to agree :( (the alert isn't
> missing is it? - re title update)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5931#issuecomment-72211379>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nikosdion** [comment]
@brianteeman Nope, it wasn't me. I also don't understand why exactly we don't show the updates immediately. We've polled the update sites, we know if there's a new version, what's the big deal? If nothing else we can change that plugin's link to force the refresh when clicked.

**Comment by zero-24** [comment]
@nikosdion 

> If nothing else we can change that plugin's link to force the refresh when clicked.

What link is needed? This: 
`index.php?option=com_installer&view=update&task=update.ajax` or something new?

**Comment by nikosdion** [comment]
I'm not talking about the URL it reads the data from. This can't change (of course). I'm talking about the URL it takes you when you click on the update found message. Now it takes you to the update view of com_installer but we could force it to show the refresh update information URL. I'm not in front of my regular computer now, I can't give you the correct URLs :(

**Comment by brianteeman** [comment]
My apologies @nikosdion I thought you had said something about this being
very slow if you had a lot of extsions and a lot of extension sites to poll

On 30 January 2015 at 15:15, Nicholas K. Dionysopoulos <
notifications@github.com> wrote:

> I'm not talking about the URL it reads the data from. This can't change
> (of course). I'm talking about the URL it takes you when you click on the
> update found message. Now it takes you to the update view of com_installer
> but we could force it to show the refresh update information URL. I'm not
> in front of my regular computer now, I can't give you the correct URLs :(
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5931#issuecomment-72215856>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nikosdion** [comment]
Well, it is, but that happens anyway when you click on the refresh updates button. This efficiency problem is why we have a maximum cache time and why it is possible that only some (not all) of the update sites being hit in one update request by the plugin. This would explain why if I release an update now you might now see it until up to 24 hours (depending on your settings, default is 6 hours) later: the old update is cached on your site. But if the cache had to do anything with it you wouldn’t be notified about the update, at all.=

**Comment by brianteeman** [comment]
So there is no problem in fixing this issue that @hils has reported

On 30 January 2015 at 15:25, Nicholas K. Dionysopoulos <
notifications@github.com> wrote:

> Well, it is, but that happens anyway when you click on the refresh updates
> button. This efficiency problem is why we have a maximum cache time and why
> it is possible that only some (not all) of the update sites being hit in
> one update request by the plugin. This would explain why if I release an
> update now you might now see it until up to 24 hours (depending on your
> settings, default is 6 hours) later: the old update is cached on your site.
> But if the cache had to do anything with it you wouldn’t be notified about
> the update, at all.=
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5931#issuecomment-72217504>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mbabker** [comment]
In theory you should be seeing whatever data is already in the updates table when you click those buttons.  So I'm mildly curious what's causing that to not happen.

**Comment by nikosdion** [comment]
The fix MIGHT introduce another issue. When you click on that update button you will try reloading all update sites. This MIGHT lead to a blank page due to timeouts or memory outage (usually the former). Basically, you can’t win unless you are willing to go to an AJAX solution for fetching updates, one update site at a time which will be slower but not prone to showing a blank page. It will, however, be prone to not working at all on all those hosts which screw up the response from AJAX requests and all those sites with badly written plugins that inject HTML or who-knows-what even in format=raw requests. So, no, I was wrong: you can’t win. At least the solution we currently have is consistent in its inconsistency and there is a viable, albeit non obvious, workaround.=

**Comment by nikosdion** [comment]
@mbabker I’d venture that Progressive caching is enabled.=

**Comment by infograf768** [comment]
We also have a similar issue for Extension Manager=> Install Languages.
I always have to click on Find languages when opening a new session.

**Comment by brianteeman** [comment]
Also see #5263 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5931">issues.joomla.org/joomla-cms/5931</a>.</sub>

**Comment by zero-24** [comment]
Closing as fixed in staging here: https://github.com/joomla/joomla-cms/pull/6727 Thanks!
