### ISSUE TITLE
Regression: Link to articles created by a contact are broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#5936]
Display a contact on frontend after making sure that display articles is set to show.
The user linked to that contact should have at least created one article.

Results:
31-Jan-2015 15:24:34 UTC] PHP Notice:  Undefined property: stdClass::$catid in /Applications/MAMP/htdocs/trunkgitnew/components/com_contact/views/contact/tmpl/default_articles.php on line 20
[31-Jan-2015 15:24:34 UTC] PHP Notice:  Undefined property: stdClass::$language in /Applications/MAMP/htdocs/trunkgitnew/components/com_contact/views/contact/tmpl/default_articles.php on line 20

The line concerned is
```
<?php echo JHtml::_('link', JRoute::_(ContentHelperRoute::getArticleRoute($article->slug, $article->catid, $article->language)), htmlspecialchars($article->title, ENT_COMPAT, 'UTF-8')); ?>
```
This apparently happens because of this PR
https://github.com/joomla/joomla-cms/pull/5276

I guess it needs a similar code change introduced in pagenavigation.php in
https://github.com/Hackwar/joomla-cms/commit/0d3ef7c076c92715e6e2371f38f8c25cd72bf105

i.e. in the contact model getContactQuery method

**Comment by infograf768** [comment]
Changing $article->catid to $article->catslug as in `components/com_content/views/featured/tmpl/default_links.php` solves the $catid Notice, but I could not find any way to correct the issue with $article->language)

**Comment by wilsonge** [comment]
Please try the fix in https://github.com/joomla/joomla-cms/pull/5937
