### ISSUE TITLE
class 'JFolder' not found in 'JFormFieldFileList' on creating a language of content

### ISSUE THREAD

**Issue by Aeliot-Tm** [joomla/joomla-cms#5938]
#### Steps to reproduce the issue

try to create a language of content in admin-side.

#### Expected result

Page fall with the error "class 'JFolder' not found in /libraries/joomla/form/fields/filelist.php"
![screen shot 2015-02-01 at 11 33 22](http://issues.joomla.org/uploads/1/28f596e253057ca5508345cc97255ae2.png)

#### System information (as much as possible)

Computer: noutbook HP620 WT162EA#AKD

PHP Built On:	Windows NT 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) i586
Database Version:	5.5.25
Database Collation:	utf8_general_ci
PHP Version:	5.3.13
Web Server:	Apache/2.2.22 (Win32) mod_ssl/2.2.22 OpenSSL/1.0.1c PHP/5.3.13
WebServer to PHP Interface:	apache2handler
Joomla! Version	Joomla!: 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version:	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by wilsonge** [comment]
Well this is interesting. Because the line of code that imports that class (https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/filelist.php#L12) has existed since 2010. Anyone got some fun ideas?

**Comment by mbabker** [comment]
I can't reproduce this on current staging nor on a 3.3.6 site.  Can you verify you have a file at `libraries/joomla/filesystem/folder.php` and that the permissions on the file are valid?

**Comment by Aeliot-Tm** [comment]
-> wilsonge
Thenk you for link.
I compared my file with a copy of the file on github and found the cause of the error. The problem is that I have no two lines. I do not know how it happened, but that is what it is.
![no_jfolder_in_filelist_answer](https://cloud.githubusercontent.com/assets/8513062/6005470/9de1c1bc-ab1b-11e4-8ef8-4f4bba481c00.png)

**Comment by wilsonge** [comment]
Glad to hear it's fixed now! Let us know if you find out what happened :)
