### ISSUE TITLE
Feed-reader crashes site if source is not a newsfeed

### ISSUE THREAD

**Issue by dirk-graetz** [joomla/joomla-cms#5939]
#### Steps to reproduce the issue
Ad a new "Module Feed Display" and set as Feed URL: http://www.google.com/robots.txt

#### Expected result
Message "Feed not available" in module position

#### Actual result
Site crash

Warning: XMLReader::read(): An Error Occurred while reading in \libraries\joomla\feed\factory.php on line 71

#### System information (as much as possible)
Joomla 3.3.6 / Apache 2.4.4 / PHP 5.5.3 / MySQL 5.6.11

#### Additional comments
We include a newsfeed which is sometimes down. In this case the feed-server returns a page with text/plain content - and our site crashes.
It makes no difference to include feed via module or via News Feed Manager.

**Comment by infograf768** [comment]
Confirmed.

**Comment by brianteeman** [comment]
With the same faulty link as above in the newsfeed component view on the frontend i got a different error

`Fatal error: Maximum execution time of 30 seconds exceeded in /Applications/MAMP/htdocs/Joomla_3.4.0-beta1-Beta-Full_Package/libraries/joomla/feed/factory.php on line 72`

In the module view I get

`Fatal error: Maximum execution time of 30 seconds exceeded in /Applications/MAMP/htdocs/Joomla_3.4.0-beta1-Beta-Full_Package/libraries/joomla/feed/factory.php on line 69`
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5939">issues.joomla.org/joomla-cms/5939</a>.</sub>

**Comment by DannyBoyk** [comment]
The loop where this read error occurs appears to be the issue.  When a non-XML document is read, the while loop never terminates, and it appears the XMLReader class continues to allocate memory until something like this eventually occurs:
```
PHP Fatal error: Allowed memory size of 205520896 bytes exhausted (tried to allocate 179834881 bytes) in /home/usr/public_html/libraries/joomla/feed/factory.php
```

I do not believe the XMLReader class is being used properly.

The fix is to change the loop from:
```
do
{
	$reader->read();
}
while ($reader->nodeType !== XMLReader::ELEMENT);
```

to something like this:
```
while ($reader->read())
{
	if ($reader->nodeType == XMLReader::ELEMENT)
	{
		break;
	}
}
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5939">issues.joomla.org/joomla-cms/5939</a>.</sub>

**Comment by zero-24** [comment]
Closing as we have a PR by @DannyBoyk here: https://github.com/joomla/joomla-cms/pull/6980 Thanks :smile:

**Comment by sbaheti56** [comment]
Thanks DannyBoyk 
it worked like wonders :smile:  Thank you so much !!!

keep doing good work :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5939">issues.joomla.org/joomla-cms/5939</a>.</sub>
