### ISSUE TITLE
System configuration - Cache Handler is not possible to set cache storage 'File'

### ISSUE THREAD

**Issue by kanich** [joomla/joomla-cms#5940]
#### Steps to reproduce the issue
Open Joomla administration. System/Global Configuration parameter Cache Handler is empty if no memcache(d) or redis handlers are available on the server. It is not possible to set cache storage 'File'. 

#### Expected result
System/Global Configuration parameter Cache Handler must have selection option 'File' with or without other cache handlers are available on the server.

**Comment by sural98** [comment]
I have uploaded Joomla 3.3.6 installation with "file" as cache handler in config file.
nginx, php-fpm with apc powered virtual server "disabled" "file" option and now shows only "apc" as cache handler in config file. No "file" in drop-down.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5940">issues.joomla.org/joomla-cms/5940</a>.</sub>

**Comment by zero-24** [comment]
@kanich @sural98 

Is your cache path writable? As this is the check to be supported. See: https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/cache/storage/file.php#L258

**Comment by kanich** [comment]
I tested fresh installation of Joomla 3.4.0 b1 on win7 as well as on debian (wheezzy) in both cases the file directory 'cache' (standard cache dir location) has writable path (0755 on debian). Results are still same. It is not possible to select 'File' cache storage.

**Comment by kanich** [comment]
The issue closing was my mistake - sorry ;-)

**Comment by kanich** [comment]
In latest Joomla version 3.4.0b2 is Cache Handler 'File' selection working. Only tiny problem is in language file /administrator/language/en-GB/en-GB.lib_joomla.ini : 
JLIB_FORM_VALUE_CACHE_FILE="file."
have to be
JLIB_FORM_VALUE_CACHE_FILE="File" as it was defined in all previous versions of Joomla<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5940">issues.joomla.org/joomla-cms/5940</a>.</sub>

**Comment by brianteeman** [comment]
I did a PR to fix the typo on the strings #5992  - thanks

Is there anything else or are you saying it is all working for you now and I can close this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5940">issues.joomla.org/joomla-cms/5940</a>.</sub>

**Comment by kanich** [comment]
Thanks - #5940 already closed.

 

  _____
