### ISSUE TITLE
It seems a bug in 3.3.6 - Category association

### ISSUE THREAD

**Issue by gccstat** [joomla/joomla-cms#5941]
I've just done a manual upgrade from 3.3.4 to 3.3.6. I was working with 3.3.4 just fine, able to associate English categories with their corresponding Arabic ones...

After doing the upgrade, now I'm unable to do so. In matter of fact, when I'm trying to associate, it pops up the model that list the categories in which I have to chose from, but when I chose a category it doesn't select it, instead it opens the editing page of that category inside the model!!!

So, would you please help me in this one, please?![screen shot 2015-02-02 at 02 29 25](http://issues.joomla.org/uploads/1/b57c55db647324809277f6199f45734b.jpg)

**Comment by gccstat** [comment]
What does this mean? Are you able to re-produce the problem??<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5941">issues.joomla.org/joomla-cms/5941</a>.</sub>

**Comment by zero-24** [comment]
@gccstat can you explain in more detail how you can reproduce the problem? I'm not sure what is the issue here. BTW my view look like:
![issue](https://cloud.githubusercontent.com/assets/2596554/6064174/9320e594-ad5c-11e4-863e-97a5003069b5.PNG)


>What does this mean? Are you able to re-produce the problem??

@brianteeman adds only the label that this issue don't have code attached. :smile:

**Comment by gccstat** [comment]
Ahaa ;)
You need to go a step further. What happen when you chose a category to be associated? for me it opens that category's editing page! and that's the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5941">issues.joomla.org/joomla-cms/5941</a>.</sub>

**Comment by gccstat** [comment]
See my view, it doesn't look the same![screen shot 2015-02-05 at 12 25 51](http://issues.joomla.org/uploads/1/63746aec3fa8abd1637612ab8d1ac257.jpg)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5941">issues.joomla.org/joomla-cms/5941</a>.</sub>

**Comment by gccstat** [comment]
The problem is solved.
I got an advice to copy /administrator/components/com_categories/views/categories/tmpl/modal.php
from the original 3.3.6 Joomla package to my website. A strange thing I saw, this file wasn't there in my website. I copied it, and it works :smile: 

Thank you so much for your support.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5941">issues.joomla.org/joomla-cms/5941</a>.</sub>
