### ISSUE TITLE
Scrollbar won't work if menu dropdown exceeds heigth of window

### ISSUE THREAD

**Issue by sural98** [joomla/joomla-cms#5942]
#### Steps to reproduce the issue
1- Create 40 menus (for a 32-language installation)
2- Create menu items as needed
#### Expected result
Click "Menus" dropdown to scroll down and click the menu you want
#### Actual result
Browser's scrollbar will work independent of "menus" drop-down height.
That is you won't be able to scroll down the "menus" drop-down.

#### System information (as much as possible)
Wamp server for 64-bit Windows 7, Joomla 3.4.0-beta1
Screen 21'', 1920x1080

#### Additional comments
This was the case in previous Joomla releases.
Tested in Firefox, Opera 25

**Comment by brianteeman** [comment]
Duplicate report of #5131<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5942">issues.joomla.org/joomla-cms/5942</a>.</sub>
