### ISSUE TITLE
Discover install is broken when adapter is already loaded

### ISSUE THREAD

**Issue by ercanozkaya** [joomla/joomla-cms#5945]
#### Steps to reproduce the issue

Run the following code:

```
$installer = new JInstaller();
$installer->loadAllAdapters();

$result = $installer->discover_install($EXTENSION_ID_TO_BE_INSTALLED);
```

#### Expected result

Extension should be installed

#### Actual result

Installation failure + PHP Notice (+ a PHP warning down the road) following this execution path:

* JInstaller::loadAllAdapters caches all adapter types in $_adapters
* JInstaller::discover_install lazy loads the adapter here:
https://github.com/joomla/joomla-cms/blob/3.4.0-beta1/libraries/cms/installer/installer.php#L510
* Since the adapter is already loaded the $params variable is never set in the adapter.
* JInstallerAdapterPlugin::prepareDiscoverInstall is called. 
* It tries to find the client info by doing $this->extension->client_id. However since $this->extension has never been populated by the installer this value is null. 
* Next line tries to access $client->path here but $client is an array.
https://github.com/joomla/joomla-cms/blob/3.4.0-beta1/libraries/cms/installer/adapter/plugin.php#L305

A notice is generated and the object is in an undetermined state.

I think a proper fix here would be abstracting the code in JInstaller in a getAdapter method. This method would set the parameters in the returned object whether it was just constructed or not.

**Comment by roland-d** [comment]
@mbabker Is this related to or are you handling this in your refactoring?

**Comment by mbabker** [comment]
I'll dig in to it over the next couple of days.

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/6024

**Comment by zero-24** [comment]
Closing as we have a RTC PR https://github.com/joomla/joomla-cms/pull/6024 Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5945">issues.joomla.org/joomla-cms/5945</a>.</sub>
