### ISSUE TITLE
Weblinks component forgets fields contents on error

### ISSUE THREAD

**Issue by dforsi** [joomla/joomla-cms#5948]
#### Steps to reproduce the issue

1. Add a weblink (eg. "Test" in category "Test").
2. Add another weblink with the same title and in the same category as the first one.

#### Expected result

When the duplicated weblink is submitted an error message is displayed and the edit form is displayed and the fields content is preserved.

#### Actual result

When the duplicated weblink is submitted an error message is displayed and the edit form is displayed with all fields empty.

#### System information (as much as possible)

Setting 	Value
 
PHP Built On 	Linux debian 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt2-1 (2014-12-08) i686
Database Version 	5.5.40-1
Database Collation 	latin1_swedish_ci
PHP Version 	5.6.4-4
Web Server 	Apache/2.4.10 (Debian)
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101 Firefox/31.0 Iceweasel/31.3.0

**Comment by brianteeman** [comment]
I can not replicate this

On 2 February 2015 at 16:27, dforsi <notifications@github.com> wrote:

> Steps to reproduce the issue
>
>    1. Add a weblink (eg. "Test" in category "Test").
>    2. Add another weblink with the same title and in the same category as
>    the first one.
>
> Expected result
>
> When the duplicated weblink is submitted an error message is displayed and
> the edit form is displayed and the fields content is preserved.
> Actual result
>
> When the duplicated weblink is submitted an error message is displayed and
> the edit form is displayed with all fields empty.
> System information (as much as possible)
>
> Setting Value
>
> PHP Built On Linux debian 3.16.0-4-686-pae #1
> <https://github.com/joomla/joomla-cms/pull/1> SMP Debian 3.16.7-ckt2-1
> (2014-12-08) i686
> Database Version 5.5.40-1
> Database Collation latin1_swedish_ci
> PHP Version 5.6.4-4
> Web Server Apache/2.4.10 (Debian)
> WebServer to PHP Interface apache2handler
> Joomla! Version Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
> Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ]
> 24-Apr-2013 00:00 GMT
> User Agent Mozilla/5.0 (X11; Linux i686; rv:31.0) Gecko/20100101
> Firefox/31.0 Iceweasel/31.3.0
> Additional comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5948>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by dforsi** [comment]
I should have mentioned that it works on the backend but I get empty fields on the frontend.

I can reproduce this with a fresh 3.3.6 install to which I only added a menu item "Submit a Web Link".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5948">issues.joomla.org/joomla-cms/5948</a>.</sub>

**Comment by brianteeman** [comment]
Before I test can you confirm that you have tested with one of the default
templates

**Comment by dforsi** [comment]
Yes I'm using protostar on the Site part (and isis on Adminsitrator), but I get the same with Beez3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5948">issues.joomla.org/joomla-cms/5948</a>.</sub>

**Comment by Bakual** [comment]
This repository is no longer the place where the Weblinks extensions is maintained. I'm closing this issue for that reason.
Can you please open an issue on the weblinks repo (https://github.com/joomla-extensions/weblinks)?

**Comment by brianteeman** [comment]
I can confirm this issue on the front end

WebLinks is moved to an external component as of j3.4 which is released in a few weeks. I am not sure what the situation is with reporting bugs with weblinks

@wilsonge can you state what should happen with weblinks issues please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5948">issues.joomla.org/joomla-cms/5948</a>.</sub>

**Comment by brianteeman** [comment]
Thanks @bakual - our posts crossed

On 2 February 2015 at 17:57, Thomas Hunziker <notifications@github.com>
wrote:

> This repository is no longer the place where the Weblinks extensions is
> maintained. I'm closing this issue for that reason.
> Can you please open an issue on the weblinks repo (
> https://github.com/joomla-extensions/weblinks)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5948#issuecomment-72503883>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
