### ISSUE TITLE
Change how tooltips look

### ISSUE THREAD

**Issue by rgmears** [joomla/joomla-cms#5957]
Change ToolTips as noted:

![screen shot 2015-02-03 at 08 35 54](http://issues.joomla.org/uploads/1/2f04d87f44113665af0895e90035400a.png)

Not a bug; just a recommended style change.

**Comment by rgmears** [comment]
Regardless the content, the text size should be increased. Or the colours switched. Tiny white text on a black background is difficult to read.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5957">issues.joomla.org/joomla-cms/5957</a>.</sub>

**Comment by rgmears** [comment]
> Perhaps we could use the Bootstrap popover instead of the tooltip

That would work. My altered styling is similar to the popover. Contrary to what Brian said in the user-interface group I think the only file that needs changing is the tooltip.less (in the template folder) which, once compiled, will change the template.css. This would have to be done for both ISIS and HATHOR. Is that correct?

**Comment by rgmears** [comment]
Except the a popover places content to the right while a tooltip places content above.

**Comment by losedk** [comment]
![skaermbillede 2015-02-03 kl 18 36 03](https://cloud.githubusercontent.com/assets/1738811/6025536/8e7ebc44-abd3-11e4-9e35-e6ccc5350327.png)

**Comment by dgt41** [comment]
@rgmears @losedk please don’t change the tooltips with popovers. Also I would like to have tooltips with different style than popovers

**Comment by losedk** [comment]
@dgt41 I'm not changing anything :) I just think it's better to use the std. Bootstrap features, if they were to change.

**Comment by rgmears** [comment]
@dgt41 How would you like the tooltip to be different. Is my original suggestion (at the top) acceptable. My intention was to replace the tiny white text on black -- which is difficult to read -- with something more legible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5957">issues.joomla.org/joomla-cms/5957</a>.</sub>

**Comment by rgmears** [comment]
How do I upload LESS and CSS files here?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5957">issues.joomla.org/joomla-cms/5957</a>.</sub>

**Comment by Bakual** [comment]
You edit the LESS file and run https://github.com/joomla/joomla-cms/blob/staging/build/generatecss.php afterwards. That will regenerate the CSS files.

**Comment by rgmears** [comment]
@Bakual
Created two pull requests: isis/less/template.less and isis/less/variables.less 
Not sure what to do next.

**Comment by Bakual** [comment]
If you only use the GitHub UI, then you will not be able to run it.
If you work with a local branch, you run the generatecss.php file using `php generatecss.php` (assuming PHP is set up to run from CLI like this).

Also it would be great if you could create one PR instead of the two. With the GitHub UI, you can go to one PR and see what branch it originates from, and the select that branch in your repo and navigate to the file you want to change. Edit that file while still having that branch active and it will automagically update your PR with the changes.

**Comment by rgmears** [comment]
I am changing three files: two LESS files and then the generated CSS file. How do I do that in one pull request. And I do not know what you mean by running the generatecss.php file. How? I do not know how to use Command Line. Sorry. (Designer not programmer)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5957">issues.joomla.org/joomla-cms/5957</a>.</sub>

**Comment by Bakual** [comment]
you will not be able to do that using the GitHub UI since you would need to run it locally from command line and then push it back using Git.
You can try to apply the changes manually, I think being a designer you know better than me how to create a CSS file from LESS. Just make sure you make your edits in the existing branch in your repo.
Follow that link to get to the `patch-1` branch of your own fork: https://github.com/rgmears/joomla-cms/tree/patch-1
Everything you change in that branch, automatically becomes part of your PR https://github.com/joomla/joomla-cms/pull/5982. So just edit the other two files within that branch.

**Comment by rgmears** [comment]
I created three PRs, one for each file. The template.css file was (as were the others) copied from my local installation. I use a compiler called WinLess. (It's not the best but it works.) For whatever reason the template.css file did not get saved by GitHub. However, when I first saved it it did not record changes correctly. 

There are now three patch files: rgmears-patch-1, patch-1, and patch-2. It would appear I should delete two of them. The first one &mdash; rgmears-patch-1 &mdash; appears to be the one you have linked to PR #5982. Is that correct?

**Comment by rgmears** [comment]
Apologies. The template.css file was saved by GitHub. it is in rgmears-patch-1. How do I move the other two in to that PR?

**Comment by Bakual** [comment]
You go to the branch and edit a file there while having that branch active. So go to https://github.com/rgmears/joomla-cms/tree/rgmears-patch-1 and navigate to https://github.com/rgmears/joomla-cms/blob/rgmears-patch-1/administrator/templates/isis/less/template.less and https://github.com/rgmears/joomla-cms/blob/rgmears-patch-1/administrator/templates/isis/less/variables.less and click the edit button there.

**Comment by rgmears** [comment]
Duh.  Thanks Thomas. It's done.

Shall I delete the other two: patch-1 and patch-2 ?

**Comment by Bakual** [comment]
Yes, please close the PRs and afterwards you can delete the branches.

**Comment by rgmears** [comment]
Done.

**Comment by rgmears** [comment]
How do we add the Pull Request to this thread?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5957">issues.joomla.org/joomla-cms/5957</a>.</sub>

**Comment by infograf768** [comment]
You don't. Just create a new PR and cross link to this Issue.

**Comment by rgmears** [comment]
So this doesn't count?

(https://github.com/rgmears/joomla-cms/pull/1)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5957">issues.joomla.org/joomla-cms/5957</a>.</sub>

**Comment by rgmears** [comment]
New PR: [#6022 - Change tooltip appearance] (http://issues.joomla.org/tracker/joomla-cms/6022)
