### ISSUE TITLE
Bug in Issue Tracker

### ISSUE THREAD

**Issue by gwsdesk** [joomla/joomla-cms#5961]
#### Steps to reproduce the issue
Submitted Issue #5960 . Screen refreshes and I get as attached error![screen shot 2015-02-03 at 22 38 44](http://issues.joomla.org/uploads/1/38bba7b9051060a473804b9e910351ff.jpg)

**Comment by zero-24** [comment]
@gwsdesk I'm closing here as this is a issue on the Inns Tracker see here: http://issues.joomla.org/tracker/jtracker/606 Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5961">issues.joomla.org/joomla-cms/5961</a>.</sub>

**Comment by gwsdesk** [comment]
Than the instructions need to be changed. They read: To report a bug in the Joomla! bug trackers, you need to create a tracker item. Once the tracker item is created, the developers will check the validity of it and act accordingly. 

Maybe this should read than : "open issue in jtracker " with link :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5961">issues.joomla.org/joomla-cms/5961</a>.</sub>
