### ISSUE TITLE
Using the old loading GIF in the Joomla updater

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-cms#5962]
We are using the old  loader image instead of the new Joomla loader graphic in the updater component . Needs to be changed to the new one
![selection_033](https://cloud.githubusercontent.com/assets/673176/6035526/6a2bd786-ac5b-11e4-9c10-d3e599924997.png)

**Comment by zero-24** [comment]
Thanks moving to confirmed :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5962">issues.joomla.org/joomla-cms/5962</a>.</sub>

**Comment by brianteeman** [comment]
Personally I prefer to use the progress bar in this situation. The download is much much bigger than most extensions and it is important for users to see that something is happening. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5962">issues.joomla.org/joomla-cms/5962</a>.</sub>

**Comment by Bakual** [comment]
I think he means the circle in the middle, not the progress bar. In other places, that was changed to a animated Joomla logo.

**Comment by brianteeman** [comment]
Ah - ok then that would make sense

**Comment by Fedik** [comment]
but it really have sense there as there already the progress bar?
maybe just remove it?

**Comment by brianteeman** [comment]
Also true

On 4 February 2015 at 13:30, Fedir Zinchuk <notifications@github.com> wrote:

> but it really have sense there as there already the progress bar?
> maybe just remove it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5962#issuecomment-72854091>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by dgt41** [comment]
If anyone is about to make a pr for this may I propose to get the style of progress bar as in finder indexer #5386.
should be something like:
```html
	<div id="progress" class="progress progress-striped active">
		<div id="progress-bar" class="bar bar-success" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
	</div>
```

**Comment by JoomliC** [comment]
@dgt41 :+1:  for me ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5962">issues.joomla.org/joomla-cms/5962</a>.</sub>

**Comment by brianteeman** [comment]
Please see #9238 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5962">issues.joomla.org/joomla-cms/5962</a>.</sub>
