### ISSUE TITLE
Language Constant missing -> FILES_JOOMLA_XML_DESCRIPTION

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#5966]
#### Steps to reproduce the issue
1. Previously I had joomla beta 1 version.
2. Upload the new joomla version (beta2) by using extension manager.
![screen shot 2015-02-04 at 05 56 30](http://issues.joomla.org/uploads/1/ab88e5b537b44550eb0844ce429bdc86.png)
(I dont know i.e this is correct method or not for upgrade the beta1 to beta2 version )

#### Expected result
Language Constant should be present

**Comment by EugeneVdovenko** [comment]
For last version bug is exists
![j3-error-install_com](https://cloud.githubusercontent.com/assets/9274923/6366221/7553c5b4-bcd3-11e4-9106-ae70e77cece0.png)

**Comment by infograf768** [comment]
The string exists in ROOT/language/en-GB/en-GB.files_joomla.sys.ini
FILES_JOOMLA_XML_DESCRIPTION="Joomla! 3 Content Management System."

**Comment by infograf768** [comment]
@EugeneVdovenko
concerning com_skeleton, I have no issue on a 3.4.0.
( https://github.com/eddieajau/joomla-extension-skeleton/releases )

![screen shot 2015-02-25 at 08 13 36](https://cloud.githubusercontent.com/assets/869724/6366474/50578e7e-bcc6-11e4-9cd1-3bae0d2d861d.png)

**Comment by EugeneVdovenko** [comment]
Ok. I download com_skeleton from https://github.com/eddieajau/joomla-extension-skeleton/releases. But...
![j3-error-install_com_2](https://cloud.githubusercontent.com/assets/9274923/6414778/33c37e44-beab-11e4-99f0-38bf4506ee4e.png)

**Comment by brianteeman** [comment]
Like @infograf768 concerning com_skeleton, I have no issue on a 3.4.0.
( https://github.com/eddieajau/joomla-extension-skeleton/releases )<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5966">issues.joomla.org/joomla-cms/5966</a>.</sub>

**Comment by N6REJ** [comment]
I had the same problem with beta rc2

**Comment by infograf768** [comment]
I guess the error is due to a bad update to one of the beta/RC version.

**Comment by jessicadunbar** [comment]
I get the same when i update to 3.4.1 
![screen shot 2015-03-21 at 3 45 28 pm](https://cloud.githubusercontent.com/assets/1581195/6766773/1b8ff18e-cfe2-11e4-83a5-bde88567c962.png)

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/6532
