### ISSUE TITLE
Code unreadable in notepad

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#5969]
![image](https://cloud.githubusercontent.com/assets/1986000/6043093/d80a5842-ac81-11e4-8e5f-eabe1347d48f.png)

Tried to edit some code but it didn't render properly in notepad :( Can we fix this pls.

**Comment by brianteeman** [comment]
I'm afraid you will have to use a real editor that understands line breaks
such as notepad++

http://superuser.com/questions/362087/notepad-ignoring-linebreaks

On 4 February 2015 at 15:24, George Wilson <notifications@github.com> wrote:

> [image: image]
> <https://cloud.githubusercontent.com/assets/1986000/6043093/d80a5842-ac81-11e4-8e5f-eabe1347d48f.png>
>
> Tried to edit some code but it didn't render properly in notepad :( Can we
> fix this pls.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5969>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Oops my email re-opened the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5969">issues.joomla.org/joomla-cms/5969</a>.</sub>
