### ISSUE TITLE
Sidebar animation gets stuck

### ISSUE THREAD

**Issue by losedk** [joomla/joomla-cms#5970]
Sometimes I experience that the sidebar animation gets stuck on hover. 

Please see the attached video:
https://www.dropbox.com/s/48qlqkmw2fij7kh/sidebar.mov?dl=0

**Comment by dgt41** [comment]
Confirmed, I ve seen this as well

**Comment by JoomliC** [comment]
I'm not able to reproduce this on beta2.
Are you able to have the same issue on beta2 or only on staging ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5970">issues.joomla.org/joomla-cms/5970</a>.</sub>

**Comment by dgt41** [comment]
@JoomliC This might be Safari 8 specific problem. Are you testing it with Safari?

**Comment by losedk** [comment]
I'm gonna test in some different browsers later tonight. This issue exist both in staging and in beta2

**Comment by JoomliC** [comment]
@dgt41 will test later on Safari 8 (my macbook has an older installed version).
Tested on Firefox, and no issue.
@losedk To be sure i understand how to reproduce the bug, is this one happens only when you click on "clear" button of the search input ?

**Comment by losedk** [comment]
@JoomliC Nope, it happens when hovering the animation regardless of the action.

I think this is a Safari specific problem, I don't experience it in Firefox or Chrome (on mac)

**Comment by losedk** [comment]
Looked deeper into the problem, it origins from the collapse class in Isis index.php on line 204
```
<div class="subhead-collapse collapse">
```

I would recommend removing the class, as it seems to only effect Safari

**Comment by JoomliC** [comment]
@losedk do you have tested with this PR https://github.com/joomla/joomla-cms/pull/6340 ?
Due to a few sidebar changes, it could maybe solve the issue in 3.4.0 ;-)

**Comment by losedk** [comment]
@JoomliC Just tested. It's the same:

![skaermbillede 2015-03-12 kl 15 23 25](https://cloud.githubusercontent.com/assets/1738811/6619616/d1598fa2-c8cb-11e4-88da-8216492e3f6f.png)

**Comment by JoomliC** [comment]
@losedk I was not able to reproduce exactly what you have on Safari 8, but i have a wrong animation of the sidebar (similar to your issue).
And it's true that if we remove the collapse, it's working fine : 
<pre><div class="subhead-collapse"></pre>

So, i wonder what for this "collapse" is, and if we could remove it... @dgt41 what's your opinion about this ? Should we create a PR to remove the "collapse" in subhead-collapse ?

**Comment by dgt41** [comment]
This collapse I think is the way to represent the toolbar as accordion for mobiles. If we remove it then the toolbar buttons will always be visible. Let me look at it later on when I will be at my desk...

**Comment by losedk** [comment]
Yeah, if removing the class the toolbar is always present

**Comment by JoomliC** [comment]
Thanks for this info @dgt41 !

**Comment by dgt41** [comment]
@JoomliC @losedk maybe you want to try this:
on isis/index.php insert 
```javascript
			$('.subhead-collapse').on('hidden', processScrollInit).on('shown', processScrollInit);
```
after line 283

See if that corrects the problem

**Comment by losedk** [comment]
@dgt41 doesn't fix the problem :/

![skaermbillede 2015-03-15 kl 15 46 35](https://cloud.githubusercontent.com/assets/1738811/6656411/7893ccaa-cb2a-11e4-9c27-eec3b5a1491b.png)

**Comment by dgt41** [comment]
@losedk @JoomliC Can you check that #6696 is solving this problem?

**Comment by losedk** [comment]
@dgt41 Just tested it. It doesn't solve the problem :/

![skaermbillede 2015-05-06 kl 12 06 10](https://cloud.githubusercontent.com/assets/1738811/7491285/4c1c217c-f3e8-11e4-9b80-a2e490d16fe5.png)

**Comment by dgt41** [comment]
@losedk One more try:
with #6696 open template.js and paste:
```javascript
				if (window.isisStickyToolbar == 1) {
					processScrollInit();
					processScroll();

					$(window).on('resize', processScrollInit);
					$(window).on('scroll', processScroll);
				}
```
after line 206 (after the } press return and the paste this snippet)
and after line 180 (same)
It should work, as it will re initiate the toolbar/header every time that the sidebar is evaluated!

**Comment by losedk** [comment]
@dgt41 I'm not getting the problem where the actual sidebar get's stuck, but I'm stil experiencing this: 

![skaermbillede 2015-05-06 kl 14 58 16](https://cloud.githubusercontent.com/assets/1738811/7493435/1d720d78-f401-11e4-9320-e5eabd673347.png)

**Comment by dgt41** [comment]
@losedk but that is on a page without sidebar (single edit pages don’t have sidebar, right?)

**Comment by losedk** [comment]
@dgt41 yeah. But both problems origins from ```<div class="subhead-collapse collapse">```

**Comment by dgt41** [comment]
@losedk in current staging if you remove the last `<script>` in index.php of isis, you should not get any problems, therefore this is the code that messes up the display. Sometimes it fires to early, (I think) and the final result is a mess…
Maybe we should re write that little thing there

**Comment by JoomliC** [comment]
@dgt41 Sorry for slow response...
As i'm not able to reproduce the issue both on imac or macbook, i can't tell you if #6696 is solving this issue, but i have applied this patch, and eveything is working fine!
Cyril

**Comment by dgt41** [comment]
@JoomliC Thanks, hope to see you @ JAB!
