### ISSUE TITLE
Displaying of text in User Profile not correct

### ISSUE THREAD

**Issue by jjsjjs** [joomla/joomla-cms#5975]
#### Steps to reproduce the issue
Look at Your User Profile

#### Expected result
1st : complete text
2nd : The actual date of birth on the same line as Date of Birth:

#### Actual result
1st- Text: The date of birth entered should use the format Year-Month-Day, i.e. 0000-00-00	(optional)

is cut off, you only see: The date of birth entered sh

2nd the actual date of birth is not on the same line as Date of Birth:

#### System information (as much as possible)
Joomla 3.3.6

#### Additional comments
This happens on UK as on NL language, so it's not an language fault

So what i did is change a bit in plugins\user\profile\profiles\profile.xml
and swapped a few lines line 103 - 114

<field name="dob_spacer" 
				type="spacer"
				class="text"
				label="PLG_USER_PROFILE_SPACER_DOB"
			/>
<field
				name="dob"
				type="calendar"
				label="PLG_USER_PROFILE_FIELD_DOB_LABEL"
				description="PLG_USER_PROFILE_FIELD_DOB_DESC"
				format="%Y-%m-%d"
				filter="server_utc"
			/>

to

<field
				name="dob"
				type="calendar"
				label="PLG_USER_PROFILE_FIELD_DOB_LABEL"
				description="PLG_USER_PROFILE_FIELD_DOB_DESC"
				format="%Y-%m-%d"
				filter="server_utc"
			/>
			<field name="dob_spacer" 
				type="spacer"
				class="text"
				label="PLG_USER_PROFILE_SPACER_DOB"
			/>

So no the line Date of Birth and the actual date are on the same level,
but the dob_spacer text is still cut off

**Comment by jjsjjs** [comment]
oh i forgot....the calender is not working at all<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5975">issues.joomla.org/joomla-cms/5975</a>.</sub>

**Comment by brianteeman** [comment]
Can you replicate this with one of the default joomla templates?

I have tested this on 3.3.6 and 23.4beta2 with the protostar template and a
few of my own  and can NOT replicate any of the issues

On 4 February 2015 at 18:05, jjsjjs <notifications@github.com> wrote:

> oh i forgot....the calender is not working at all
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/5975
> <http://issues.joomla.org/tracker/joomla-cms/5975>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/5975#issuecomment-72905682>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by jjsjjs** [comment]
Thanks, i can confirm.
Sorry did'nt think of it myself to check first with a standard template.
I used the Joomlashine JSN-Metro Free template, this is causing this and other faults apperantly.

thanks very much.
You may close this ticket.
I will oped a ticket at Joomlashine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5975">issues.joomla.org/joomla-cms/5975</a>.</sub>
