### ISSUE TITLE
Editor plugins - jInsertEditorText

### ISSUE THREAD

**Issue by okonomiyaki3000** [joomla/joomla-cms#5978]
Editor plugins are required to create a globally accessible Javascript function `jInsertEditorText` which is used to insert some text into the editor. The function is passed the string to be inserted and an editor instance so that, if you have two or more editors on the same page, it will still work. The problem is that it will not work if you have two or more different types of editors on the same page. OK, this doesn't actually happen but, in theory, it's possible. You could have an instance of CodeMirror and an instance of TinyMCE on the same page. They both try to write their own version of `jInsertEditorText` but only one of them will actually work because the implementation of the function is different for each editor. 

I can envision some possible fixes but they will surely break BC. Maybe something to consider before 4.0.

**Comment by zero-24** [comment]
Closing as this issue have the Re-evaluate for v4.0 label :smile:
