### ISSUE TITLE
Location of language files (README)

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#5987]
In the readme file we have a broken link to "Directory of non-accredited language packs."

Has that been moved or removed from the JED?

**Comment by ot2sen** [comment]
Yes, JED made a change on Feb. 1st 2014. PR added https://github.com/joomla/joomla-cms/pull/6059<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5987">issues.joomla.org/joomla-cms/5987</a>.</sub>
