### ISSUE TITLE
Menú item alias to menú external url is not working

### ISSUE THREAD

**Issue by irbian** [joomla/joomla-cms#5990]
#### Steps to reproduce the issue
- Create a menú item url, called "External", pointing to http://joomla.org
- Create a menú item alias, pointing to "External"

#### Expected result
- A correct redirection

#### Actual result
- A broken link to something like http://mydomain.com/?Itemid=119

#### System information (as much as possible)
Joomla 3.3.6
index.php removed from url

**Comment by joomdonation** [comment]
I can confirm the issue.

**Comment by joomdonation** [comment]
OK. I created a small PR https://github.com/joomla/joomla-cms/pull/5995 to fix this issue. Please test it when you have time.

**Comment by wilsonge** [comment]
Closing as there is a fix proposed in #5995
