### ISSUE TITLE
Send mail problem

### ISSUE THREAD

**Issue by rodriciru** [joomla/joomla-cms#5993]

**Comment by infograf768** [comment]
That is certainly not going to help, unless you describe the whats and where....  :)

**Comment by brianteeman** [comment]
Closing as there is no content in this issue.

@rodriciru Please create an issue with full details of your problem

**Comment by rodriciru** [comment]
Sorry.
it works perfectly.
Was a problem whit spanish traduction, who makes me crazy.
When you send a mail you can choose bcc, but in spanish translation, this options say that BCC hidess SENDER and not Recipents!!
