### ISSUE TITLE
System Debug Count of queries missing

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#5997]
When the system debug is enabled the number of queries is not counted on the front end - it always displays 0

Works correctly though in the admin

![screen shot 2015-02-06 at 06 47 37](http://issues.joomla.org/uploads/1/d952b44803a94b19a0a6f562a494f52f.png)

**Comment by zero-24** [comment]
Closing as we have a PR by @prasoon2211 https://github.com/joomla/joomla-cms/pull/6013<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5997">issues.joomla.org/joomla-cms/5997</a>.</sub>
