### ISSUE TITLE
Missing Tag-Filter in Frontend-ArticlesModel (should use the same load-functions like in the backend)

### ISSUE THREAD

**Issue by Robdebert** [joomla/joomla-cms#5998]
![screen shot 2015-02-06 at 07 02 43](http://issues.joomla.org/uploads/1/b2087b0af96345cc8d0f7904caf1d3b5.png)#### Steps to reproduce the issue

Because mod_articles_category is missing some functions, i needed to create a copy of it with extended features. Steps:

1) Create a new module, with the intention to display articles filtered by category-id and tags.
2) Use this to get the article-list-model:
$articles = JModelLegacy::getInstance('Articles', 'ContentModel', array('ignore_request' => true));

3) Problem is:  you cannot simply add a filter-state like this:
$filter_tag = $params->get('filter_tag', '');
if ($filter_tag) {
    $articles->setState('filter.tag', (int)$filter_tag);
}

That is, because only the backend-model has this filter. The frontend-model does not. And i didn't found a solution in the documentations to get the instance of an admin-model.	

#### Expected result
Frontend-Model should either provide the same methodes as the backend-model, or there needs to be a possibility to get the instance of a backend-model using JModelLegacy::getInstance
or anything else, that provides a filtering-method that can be accesses using the framework and not own mysql-queries.

#### Actual result

See description above.

#### System information (as much as possible)

Joomla 3.3.6 stable release.

#### Additional comments

\administrator\components\com_content\models\articles.php:
Admin - ContentModelArticles already uses filter_tag variables (See lines 56, 111, 297).

\components\com_content\models\articles.php -> Missing filter-functions for tags.![screen shot 2015-02-06 at 07 02 43](http://issues.joomla.org/uploads/1/a3c3f505b5fcef80766cbc613889237d.png)

**Comment by rdeutz** [comment]
setting the prio to low, see https://docs.joomla.org/Bug_and_Issue_Tracker_Priority for more information<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5998">issues.joomla.org/joomla-cms/5998</a>.</sub>

**Comment by danielsmink** [comment]
This is quite annoying. It's almost one year later. Any chance this will be fixed in 3.5?

**Comment by rdeutz** [comment]
As long as nobody makes a patch, it will stay here forever

**Comment by danielsmink** [comment]
I'll see what I can do. It took 10 minutes to get it working with query parameters locally. But I have to check more places before I submit a PR.

**Comment by danielsmink** [comment]
PR is in @rdeutz

**Comment by brianteeman** [comment]
Closing as we have a PR - please test #8846 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5998">issues.joomla.org/joomla-cms/5998</a>.</sub>
