### ISSUE TITLE
Potential PHP Notices/Warnings in JInstallerHelper class

### ISSUE THREAD

**Issue by bassmanpaul** [joomla/joomla-cms#6000]
I experienced a scenario where I was testing an install package (which was corrupt) and it brought to light a couple of PHP notices in the `JInstallerHelper` class.

#### The File:

**libraries/cms/installer/helper.php** line 197 & 221

#### Issue 1 (line 197):

```php
$dirList = array_merge(JFolder::files($extractdir, ''), JFolder::folders($extractdir, ''));
```

As `JFolder::files()` & `JFolder::folders()` can return `false` which would break `array_merge()`. One solution would be type casting:

```php
$dirList = array_merge((array)JFolder::files($extractdir, ''), (array)JFolder::folders($extractdir, ''));
```

#### Issue 2 (line 221):

```php
if (!count($files))
```

Again `JFolder::files()` could return `false` so the `count()` of `false` would be **1** as opposed to **0**. (see: http://php.net/manual/en/function.count.php#example-5167) Therefore as this is a false positive may I suggest something like:

```php
if (!$files || !count($files))
```
or
```php
if (!is_array($files) || !count($files))
```

If everyone likes the suggestions I will happily create a Pull Request.

**Comment by wilsonge** [comment]
A PR would be awesome thanks! Awesome spot!

**Comment by zero-24** [comment]
@bassmanpaul can you add a PR with that changes? Here is a simple step by step guide how to do it: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by bassmanpaul** [comment]
Done:

https://github.com/joomla/joomla-cms/pull/6026

**Comment by zero-24** [comment]
Closing as we have a PR thanks @bassmanpaul <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6000">issues.joomla.org/joomla-cms/6000</a>.</sub>
