### ISSUE TITLE
JInput::getArray() applies wrong filters

### ISSUE THREAD

**Issue by Erftralle** [joomla/joomla-cms#6008]
If using the JInput::getArray() function without parameters e.g.
```
        $mypostdata = $myapp->input->post->getArray();
```
and the post data contains variables having values matching a JInputFilter type e.g. 'integer', 'int', 'float' etc. these values will be applied as filter in the following function code:
```
				if (is_null($datasource))
				{
					$results[$k] = $this->get($k, null, $v);
				}
```
When calling the function without parameters the function uses the class property 'data', which is an associative array with variable names and their values.

So, a POST variable 'myinputstring' containing a string value 'integer' will be returned as an integer containing a 0, which is definetly a wrong behaviour.

Wouldn't it be better to detect a parameterless function call to apply 'RAW' filters in that case?

**Comment by Erftralle** [comment]
Opened pull request #6035 with a proposal for a fix.

**Comment by zero-24** [comment]
Closing here as we have a PR by @Erftralle here: https://github.com/joomla/joomla-cms/pull/6035 Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6008">issues.joomla.org/joomla-cms/6008</a>.</sub>
