### ISSUE TITLE
Custom HTML Module Appears on All Categories/SubCategories

### ISSUE THREAD

**Issue by sural98** [joomla/joomla-cms#6011]
#### Steps to reproduce the issue
1- Create a menu item of type "List All Categories"
2- No menu item will be assigned to any of the subcategories of the chosen category
3- Create a custom HTML module and assign to the newly created menu item

#### Expected result
Module should appear only on page listing categories of the top category.

#### Actual result
Module appears on all subcategories/pages besides the assigned page.

#### System information (as much as possible)
Apache 2.4.9, MySQL 5.6.17, PHP 5.5.12, Joomla 3.4-beta2

**Comment by brianteeman** [comment]
The menu item is inherited this is expected behaviour

**Comment by nternetinspired** [comment]
The same should happen with any Joomla module, as @brianteeman says, that is the expected behaviour.
