### ISSUE TITLE
Links to JED in "Install from Web"

### ISSUE THREAD

**Issue by rgmears** [joomla/joomla-cms#6014]
#### Steps to reproduce the issue
Go to Install from Web under Extensions/Extension Manager.
Click on the Votes / Reviews link at the top of each item.

#### Expected result
Page for the extension on the JED should open in a new tab.

#### Actual result
404 Component Not Found page.

Does this for all items as far as I can tell.

**Comment by mbabker** [comment]
Please see https://github.com/joomla-extensions/install-from-web-server/pull/4 and linked issues.
