### ISSUE TITLE
Extension Manager search results are not middle-clickable

### ISSUE THREAD

**Issue by rulatir** [joomla/joomla-cms#6023]
#### Steps to reproduce the issue

Search in the Extensions Manager.

#### Expected result

Search results should be middle-clickable, so that the user can open several results in background tabs, read them separately and then go back to the extension manager to search more or scroll to further results.

#### Actual result

Search results are not middle-clickable. The only way to see details of a result is to left-click on it, which unloads the search results listing. If I want to examine further results, I must search again. This is inefficient and cumbersome.

**Comment by zero-24** [comment]
@rulatir i'm not sure do we speak about this view?

![extensionmanger](https://cloud.githubusercontent.com/assets/2596554/6111325/48d77dfc-b088-11e4-9c39-04e6d9f3235c.PNG)

I think we cant open it for extra information can we?

**Comment by prasoon2211** [comment]
@zero-24 I think that @rulatir is talking about the module manager where links are clickable. Also, I think that `Crtl+Click` works just fine for opening stuff in new tabs. But I guess some people might be more comfortable with the middle mouse button.

As for the fix, I suppose we can add this little [snippet](http://stackoverflow.com/a/7554617) with some modification into the JS for the module manager (and any other places where a similar situation occurs.) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6023">issues.joomla.org/joomla-cms/6023</a>.</sub>

**Comment by zero-24** [comment]
@rulatir @prasoon2211 It works good for me using last Chrome on beta3 with the modul, plugin, menu and content mangers.

@rulatir can you add more information e.g. your browser? Is it possible that your mouse don't support it? Thanks!

**Comment by rulatir** [comment]
No, we are talking about the view that is literally named "Extension Manager" - the view where you land when you open the "Extensions" dropdown menu in the main menu bar, and select the first item labelled "Extension Manager" in the English version:

![extension_manager](https://cloud.githubusercontent.com/assets/677694/6203487/35b44524-b525-11e4-92e9-3d4ad7c81535.png)

(please ignore missing images in search results - this is either my adblock messing with them, or the image server has some problems, I don't really care about this)

I made this screenshot while hovering over the link in the first package in the results - "Kunena". As you can infer from the URL tooltip in the bottom left corner of the browser window, this link is just &lt;a&nbsp;href="#"&gt;, and its ability to "get me" to that Kunena thing relies completely on javascript onclick handler and AJAX.

This is not right.

Hyperlinks should actually lead to what they promise, right there in the markup. In-place AJAX reloading is cool, but it is an enhancement that should be built on top of the basic hyperlink functionality, rather than replace it. The basic hyperlink functionality is precisely what enables middle click (or shift+click, or context menu action) in any browser, and completely for free. You don't need to program it. You *may* need to program the server side though, as it may be the case that only the AJAX route is currently implemented.

**Comment by mbabker** [comment]
I'd suggest filing a ticket via https://github.com/joomla-extensions/install-from-web-client as that is the team maintaining the Install from Web functionality.  As implemented, there are only a few "real" hyperlinks pointing to external resources (I think mostly JED links).  Otherwise, this implementation is built to navigate from within this view and isn't designed to serve content outside of the CMS like you would suggest via middle clicking.  Actually, if you're looking for the content as a standalone tab, you're better suited viewing the extension's listing on the JED versus this listing.

**Comment by rulatir** [comment]
Understood, thanks.
