### ISSUE TITLE
Trailing line in layouts/joomla/content/tags.php ?

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#6027]
### Is this a trailing line ?
``` php
use Joomla\Registry\Registry;
```
#### in layouts/joomla/content/tags.php
``` php
defined('JPATH_BASE') or die;

use Joomla\Registry\Registry;

JLoader::register('TagsHelperRoute', JPATH_BASE . '/components/com_tags/helpers/route.php');
```
Checked in 
[github](https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/content/tags.php)

**Comment by mbabker** [comment]
The line is fine.  That line tells PHP to load a namespaced class into a file for use without needing to always use the fully qualified class name.  Please see http://php.net/manual/en/language.namespaces.php for more details.
