### ISSUE TITLE
Limited Copy failed message at component update

### ISSUE THREAD

**Issue by kentanilsson** [joomla/joomla-cms#6048]
#### Steps to reproduce the issue
Make a file only readable (r--r--r--) that should be replaced by component update .
Start update

#### Expected result
-1 An error occured
Copy failed <source file> to <destination file>

#### Actual result
-1 An error occured
Copy failed

#### System information (as much as possible)
J3.3.6
PHP 5.4 , 5.5
Linux 12.04 , 14.04
Akeeba backup 1.5.5 (component to be updated)

#### Additional comments
Current message leaves user in the dark and has no clue where to start looking for the problem

#### Proposed fix
File : /libraries/joomla/filesystem/file.php
if (!@ copy($src, $dest))
{					  JLog::add(JText::sprintf('JLIB_FILESYSTEM_ERROR_COPY_FAILED',$src,$dest), JLog::WARNING, 'jerror');

return false;
}

File: /language/en-GB/en-GB.lib_joomla.ini
JLIB_FILESYSTEM_ERROR_COPY_FAILED="Copy failed %s to %s"

**Comment by brianteeman** [comment]
It would appear that this was resolved in 3.4 as the message I get is correct

Copy failed.

JInstaller: :Install: Failed to copy file /Applications/MAMP/htdocs/joomla-cms/tmp/install_55432a0101abd/components/com_jce/jce.php to /Applications/MAMP/htdocs/joomla-cms/components/com_jce/jce.php

Component Update: Failed to copy site files.
