### ISSUE TITLE
SQL Errors in com_search whit MSSQL.

### ISSUE THREAD

**Issue by vzenix** [joomla/joomla-cms#6054]
#### Steps to reproduce the issue
Go to: /index.php?searchword=tag&ordering=newest&searchphrase=all&option=com_search

#### Expected result
Search Results.

#### Actual result
[Microsoft][SQL Server Native Client 11.0][SQL Server] Column 'yawcx_contact_details.name' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause. SQL=SELECT * FROM ( SELECT a.name AS title, '' AS created, a.con_position, a.misc, CASE WHEN DATALENGTH(a.alias) != 0 THEN (CAST(a.id as NVARCHAR(10))+':'+a.alias) ELSE CAST(a.id as NVARCHAR(10)) END as slug, CASE WHEN DATALENGTH(c.alias) != 0 THEN (CAST(c.id as NVARCHAR(10))+':'+c.alias) ELSE CAST(c.id as NVARCHAR(10)) END as catslug, (a.name+','+a.con_position+','+a.misc) AS text,('Contacts'+' / '+c.title) AS section,'2' AS browsernav , ROW_NUMBER() OVER (ORDER BY a.name DESC) AS RowNumber FROM yawcx_contact_details AS a INNER JOIN yawcx_categories AS c ON c.id = a.catid WHERE (a.name LIKE '%tag%' OR a.misc LIKE '%tag%' OR a.con_position LIKE '%tag%' OR a.address LIKE '%tag%' OR a.suburb LIKE '%tag%' OR a.state LIKE '%tag%' OR a.country LIKE '%tag%' OR a.postcode LIKE '%tag%' OR a.telephone LIKE '%tag%' OR a.fax LIKE '%tag%') AND a.published IN (1,2) AND c.published=1 AND a.access IN (1,1,2) AND c.access IN (1,1,2) GROUP BY a.id, a.con_position, a.misc, c.alias, c.id ) _myResults WHERE RowNumber BETWEEN 1 AND 50

[Microsoft][SQL Server Native Client 11.0][SQL Server]The column 'note' was specified multiple times for '_myResults'. SQL=SELECT * FROM ( SELECT a.id, a.title, a.alias, a.note, a.published, a.access, a.checked_out, a.checked_out_time, a.created_user_id, a.path, a.parent_id, a.level, a.lft, a.rgt, a.language, a.created_time AS created, a.note, a.description, CASE WHEN DATALENGTH(a.alias) != 0 THEN (CAST(a.id as NVARCHAR(10))+':'+a.alias) ELSE CAST(a.id as NVARCHAR(10)) END as slug , ROW_NUMBER() OVER (ORDER BY a.created_time DESC) AS RowNumber FROM yawcx_tags AS a WHERE a.alias <> 'root' AND (a.title LIKE '%tag%' OR a.alias LIKE '%tag%') AND a.access IN (1,1,2) ) _myResults WHERE RowNumber BETWEEN 1 AND 50

#### System information (as much as possible)
IIS
MSSQL
Joomla 3.3.6

#### Additional comments
1º Error: Add in group clausule a.name, a.alias, c.title because GROUP BY is diferent in MySQL.
(/plugin/search/contacts/contacts.php)
2º Error: Delete 'a.note', because have 2 in "SELECT" and this can provoke a crash in MSSQL.
(/plugin/search/tags/tags.php)

**Comment by waader** [comment]
I can confirm that search is also broken in the current staging branch.

**Comment by zero-24** [comment]
Closing here as we have a PR by @alikon Thanks: https://github.com/joomla/joomla-cms/pull/6082<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6054">issues.joomla.org/joomla-cms/6054</a>.</sub>

**Comment by alikon** [comment]
@zero-24 the #6082 fix only the 2nd issue reported by @vzenix 
i'm still looking for the 1st one

**Comment by zero-24** [comment]
Thanks @alikon I re-open here than.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6054">issues.joomla.org/joomla-cms/6054</a>.</sub>

**Comment by alikon** [comment]
@zero-24 sorry now the #6082 should solve both so this can be closed

**Comment by zero-24** [comment]
So I closing here. Thanks for the patch and update here @alikon <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6054">issues.joomla.org/joomla-cms/6054</a>.</sub>
