### ISSUE TITLE
Bug in router

### ISSUE THREAD

**Issue by MarkRS-UK** [joomla/joomla-cms#6056]
I think this is a simply "wasteful" bug rather than actually causing an application failure of any kind.

## Problem

libraries/joomla/application/route.php, line 58.
_
if (!is_array($url) && (strpos($url, '&') !== 0) && (strpos($url, 'index.php') !== 0))_

the latter two checks fail if either item checked for is at the beginning of the string checked.

This is perhaps unlikely for "&", but almost guaranteed for "index.php".

The router is always re-executed because of this,even if it's not required.

## Solution

Change the line to

_if (!is_array($url) && !(strpos($url, '&') === false) && !(strpos($url, 'index.php') === false))_

How many other places in the codebase are like this?

**Comment by MarkRS-UK** [comment]
On further conversation it appears that this solution is not correct or helpful.
Can this issue item be removed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6056">issues.joomla.org/joomla-cms/6056</a>.</sub>

**Comment by Bakual** [comment]
Closing as requested.
