### ISSUE TITLE
Consistency in Columns alignment

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#6076]
Some columns are left aligned and some columns are centred. Thats ok but almost all the titles are left aligned so it looks odd.

![screen shot 2015-02-12 at 16 11 41](http://issues.joomla.org/uploads/1/4825de470e9b2f519dd5a1f741383282.png)

It would look a lot better if the alignment of the headings matched the content - example
**Option 1**
![screen shot 2015-02-12 at 16 13 26](http://issues.joomla.org/uploads/1/0e9e3569112248417cb823dc65b4eddb.png)

**Option 2**
![screen shot 2015-02-12 at 16 14 55](http://issues.joomla.org/uploads/1/68017f62b1ba02a2aad7c20d5c153dd2.png)

**Comment by brianteeman** [comment]
@nternetinspired any thoughts?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6076">issues.joomla.org/joomla-cms/6076</a>.</sub>

**Comment by nternetinspired** [comment]
In an LTR document, and most definitely in a table, all *copy* should be left aligned. The only exception I would make to that rule would be for items without text, like buttons and checkboxes, which usually look better centrally aligned within their `<td>`.

**Comment by brianteeman** [comment]
what about with numbers?

Just want to get a complete answer before doing a big PR

On 13 February 2015 at 10:29, Seth Warburton <notifications@github.com>
wrote:

> In an LTR document, and most definitely in a table, all *copy* should be
> left aligned. The only exception I would make to that rule would be for
> items without text, like buttons and checkboxes, which usually look better
> centrally aligned within their <td>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6076#issuecomment-74233799>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nternetinspired** [comment]
Well the browser default is left-aligned, as it is with the whole document. There's cases where, from a typographical perspective, it may be desirable to right align a column of numbers: http://practicaltypography.com/grids-of-numbers.html but I feel that's overkill here and requires far too much manual intervention.

Bootstrap's behaviour is to not apply any alignment on table contents: http://getbootstrap.com/css/#tables so this is strictly a template-designers choice and one which I personally don't feel is correct. In this case I think the appearance would be improved and the template codebase lightened simply by allowing the browser to do its thing and left-align everything. TBH even left aligned buttons and checkboxes look fine to me, I only highlighted those as a possible item where there might be valid disagreement (form elements aren't typically part of a normal table content).

**Comment by nternetinspired** [comment]
You'd get a :+1: from me remove all .center classes on table cells.

**Comment by brianteeman** [comment]
yeah thats what I plan to do - especially when we have it on a thead and
not on a td and vice versa

On 13 February 2015 at 10:51, Seth Warburton <notifications@github.com>
wrote:

> You'd get a [image: :+1:] from me remove all .center classes on table
> cells.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6076#issuecomment-74236269>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by JoomliC** [comment]
:+1: for changes!

My opinion: left for text, center for icons/images and right for numeric (id is always on the right now, and could be right align).
Almost as you did @brianteeman in Option 2 ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6076">issues.joomla.org/joomla-cms/6076</a>.</sub>

**Comment by b2z** [comment]
> My opinion: left for text, center for icons/images and right for numeric

:+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6076">issues.joomla.org/joomla-cms/6076</a>.</sub>

**Comment by brianteeman** [comment]
I suspect that any changes made now would be overwritten by changes in 3.5 for JLayouts so am putting this on the backburner for now @phproberto and adding a 3.5 milestone
