### ISSUE TITLE
Extension Update Alert & Process 3.4 beta3

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-cms#6091]
Extension update alert :

![update-available](https://cloud.githubusercontent.com/assets/736887/6199433/248e7962-b43b-11e4-892f-7f66dd813317.png)

Clicking on the update now button goes to :

![update-available-2](https://cloud.githubusercontent.com/assets/736887/6199443/76f37676-b43b-11e4-95ea-1ec432282915.png)

which shows no extension update available.

The behavior I would expect is for 'update now' button to go to a list of extensions that I could look at then choose whether or not & what to update. So either the text on the button should be changed to something like 'review' or there is a bug giving a wrong result. Or the original update alert is wrong.

Hoping that makes sense! I am available for interrogation ;)

**Comment by brianteeman** [comment]
Isnt this a duplicate report of your own #5931<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6091">issues.joomla.org/joomla-cms/6091</a>.</sub>

**Comment by Hils** [comment]
Sorry! Shows how confusing it actually is. (Just updated from beta 2 to 3 without tea). Thanks for picking that up.
