### ISSUE TITLE
JUI > Bootstrap > Fluid offsetting - wrong margin-left in JUI bootstrap-extended.less

### ISSUE THREAD

**Issue by photografx** [joomla/joomla-cms#6093]
Since i based my newer templates on protostar to follow "JUI" i found the following error(?) in in my latest template first i thought i got something wrong, but then i went back to base protostar ... tested in 3.3.6 & 3.4.0 RC1 (Update 20.02.2014)
 
#### Steps to reproduce the issue
Take the protostar template (or any other based on JUI) 
Make a layout with offsetted Columns (spans)

#### Expected result
I've made an example with origninal bootstrap 2.3.2 on my test-server
[http://test.photografx.eu/bootstrap-fluid-test](http://test.photografx.eu/bootstrap-fluid-test "http://test.photografx.eu/bootstrap-fluid-test")

#### Actual result
Here an installation of Joomla 3.4.0 RC1 on my testing server,
I made a quick & dirty edit to the original protostar shipped with it
[http://test.photografx.eu/j3-test](http://test.photografx.eu/j3-test "http://test.photografx.eu/j3-test")

#### System information (as much as possible)
Found the Issue in 3.3.6
Tried to reproduce in 3.4.0 beta3 with Success ;)

#### Additional comments
the error ist not in the protostar template itself but in the **media/jui/less** folder
i found some strange/wrong (to me) overrides of the right percent values of the mixins.less

in the **bootstrap-extended.less** 
the offset-overrides starting @ line 96 to line 128
**If I comment these lines out, offsetting in the template layout works as intended by bootstrap ... **

it looks like that they rather "belong to"
/* Nav List Offset */ starting @ line 86

I am currently running the great [LESS Compiler PlugIn](http://extensions.joomla.org/extensions/extension/miscellaneous/development/less-compiler "LESS Compiler PlugIn")
with Client-side Compiler enabled so i could (an you can) easyly track down the corresponding LESS files with Firebug plus [FireLESS Extension](https://addons.mozilla.org/en-US/firefox/addon/fireless/ "FireLESS Extension")

kind regards
AlexxJ

**Comment by photografx** [comment]
if you need Joomla or ftp acces to my testing space plz let me know ...

**Comment by photografx** [comment]
so i will try to attach code ...

**Line 86 to 155 of the /media/jui/less/bootstrap-extended.less**

/* Nav List Offset */
.nav-list > li.offset > a {
	padding-left: 30px;
	font-size: 12px;
}
.blog-row-rule,
.blog-item-rule {
	border: 0;
}
/* START 
The following lines influencing the bootstrap row-fluid - Layout in Templates using JUI
seems that they rather belon to nav list offset ? */

.row-fluid .offset1 {
  margin-left: 8.382978723%;
}
.row-fluid .offset2 {
  margin-left: 16.89361702%;
}
.row-fluid .offset3 {
  margin-left: 25.404255317%;
}
.row-fluid .offset4 {
  margin-left: 33.914893614%;
}
.row-fluid .offset5 {
  margin-left: 42.425531911%;
}
.row-fluid .offset6 {
  margin-left: 50.93617020799999%;
}
.row-fluid .offset7 {
  margin-left: 59.446808505%;
}
.row-fluid .offset8 {
  margin-left: 67.95744680199999%;
}
.row-fluid .offset9 {
  margin-left: 76.468085099%;
}
.row-fluid .offset10 {
  margin-left: 84.97872339599999%;
}
.row-fluid .offset11 {
  margin-left: 91.489361693%;
}

/* END  */

/* Navbar Buttons */
.navbar .nav > li > a.btn {
	padding: 4px 10px;
	line-height: 18px;
}

/* Nav Tabs Dark */
.nav-tabs.nav-dark {
	border-bottom: 1px solid #333;
	text-shadow: 1px 1px 1px #000;
}
.nav-tabs.nav-dark > li > a {
	color: #F8F8F8;
}
.nav-tabs.nav-dark > li > a:hover {
  border-color: #333 #333 #111;
  background-color: #777777;
}
.nav-tabs.nav-dark > .active > a, .nav-tabs.nav-dark > .active > a:hover {
  color: #ffffff;
  background-color: #555555;
  border: 1px solid #222;
  border-bottom-color: transparent;
}<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6093">issues.joomla.org/joomla-cms/6093</a>.</sub>

**Comment by adriaan6** [comment]
Dear Sir/Madam,

I have upgrade my Joomla version to: 3.4.0 and now i have a problem with my Protostar template.. The menu is not correctly displayed.


Can someone tells me what's going wrong and what i must change to solve this problem? without restoring a back-up.



www.bredero-backup.com/site2



I looking forward to hear from you, thanks and have a nice day!



Regards,

Adriaan<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6093">issues.joomla.org/joomla-cms/6093</a>.</sub>

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6093">issues.joomla.org/joomla-cms/6093</a>.</sub>
