### ISSUE TITLE
redirects to website index after saving article

### ISSUE THREAD

**Issue by eloelo22** [joomla/joomla-cms#6095]
#### Steps to reproduce the issue
edit or make a new article then save

#### Expected result
redirects back to the saved article

#### Actual result
redirects to front end index page

#### System information (as much as possible)
PHP Built On	Linux lax03.web.com.ph 2.6.32-531.23.3.lve1.2.66.el6.x86_64 #1 SMP Fri Sep 12 10:57:40 EDT 2014 x86_64
Database Version	5.5.40-cll
Database Collation	latin1_swedish_ci
PHP Version	5.4.36
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by eloelo22** [comment]
sorry the expected result should be it will redirect back to the article<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6095">issues.joomla.org/joomla-cms/6095</a>.</sub>

**Comment by Hils** [comment]
I can't reproduce this on Joomla 3.4.0 beta 3.

Editing article in admin then pressing save redirects back to the article.

**Comment by rdeutz** [comment]
Not 100 % clear but I think you meant the front end editing. Checked a blog layout/article list and edited an article and got redirected to the view I originally came from what I think is the correct behauviour. I used 3.3.6.

**Comment by infograf768** [comment]
@Hils 

I think the poster os speaking about frontend, not backend.


We do not use Save + Save & Close in front-end. Just Save.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6095">issues.joomla.org/joomla-cms/6095</a>.</sub>

**Comment by Hils** [comment]
OK - thanks - newbies need precise testing instructions :)

**Comment by rdeutz** [comment]
sorry wasn't aware that setting the state to "unconfirmed Report" will close the issue, have set it now to "information required". @eloelo22 could you please describe with more detail what you did, thanks!

**Comment by brianteeman** [comment]
I can confirm this behaviour on creating a NEW article but I would say this was expected behaviour as Joomla has no way of knowing where that article should be displayed
I can NOT confirm this behaviour on editing an existing article - on save I am returned to the article

Can you please test your site using the default protostar template to ensure that this is not a template issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6095">issues.joomla.org/joomla-cms/6095</a>.</sub>

**Comment by eloelo22** [comment]
hi sorry for the unclear description here is what i did i log in to the joomla administrator and edited the content after which i clicked saved the expected result should be a redirect to the same article in edit mode but instead it redirects to my website index page same is true with clicking save&close

**Comment by infograf768** [comment]
I can't reproduce the issue here.

**Comment by devsaurin** [comment]
@eloelo22 can you please confirm, your administrator template is set to one of default template (isis/Hathor)?

**Comment by eloelo22** [comment]
its the isis sorry been busy for a while

**Comment by ostana** [comment]
Hi!
I'm also experiencing the same situation with joomla 2.5.28.
- when i try to save / save & close / cancel a new article or re-edit an old article i'm redirected back to homepage and the article in not save; also the session remain open;
- when i open "gbobal configuration" try to edit the offline custom message then save / save & close / cancel i'm redirected back to homepage and also the session remain open;
- i open "template manager"/defaut template (Yougrids - Default) then proceed directly to save / save & close /close,  i'm redirected back to homepage and  the session remain open;
- however modules (and plugins) saving did not redirect to home page but to modules list as usual.

I saw this same post on STACKOVERFLOW and a user gave this reply:
    "I have seen this happen because of two reasons: 1) a third party plugin could be causing the problem 2) you are using an old 2.5 template for administrator, try using Isis. Take a look at your php / apache error logs there may be a clue there if the issue lies with a plugin."

So i changed my default admin template from "Bluestork - Default" to "Hathor - Default", uninstall my JCE-editor but the same behaviour (redirect to homepage) still continues.
I check all log files to find any error message but nothing.

I would be happy if anyone could give an idea of the cause.
Thank you
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6095">issues.joomla.org/joomla-cms/6095</a>.</sub>

**Comment by eloelo22** [comment]
i am the same person who posted the question on STACKOVERFLOW but the suggestions weren't that helpful at all that is why i decided to post it here hoping to solve the problem i can't update any content on my website

**Comment by dgt41** [comment]
Try changing the session handler either to file or database but for sure don't leave it as none. Hope it helps

**Comment by eloelo22** [comment]
on the part of that remains open?

**Comment by devsaurin** [comment]
If this issue is regarding Joomla!2.5.28 only then, you should check this; http://www.joomla.org/announcements/release-news/5574-joomla-2-5-28-released.html

More, I have checked with fresh installation of Joomla 2.5.28 with both admin templates and not able to reproduce the issue. I doubt there must be some plugin causing this issue. Better to compare your active plugins against fresh copy of Joomla installation.

Before that you might do one thing; try to Global Check-In and check your issue against this step. I have noticed this type of behavior, when multiple admins are on desk. (This is just to give a try.)

**Comment by tecpromotion** [comment]
The same problem occurs for 2 days in one of my Joomla! 3.3.6 installations. Save button works, Save & Close button deletes the /administrator string from the URL and then brings a 404 error.

**Comment by rdeutz** [comment]
@tecpromotion What did you change within the last two days? Any update off PHP or so?

**Comment by brianteeman** [comment]
any htaccess changes

**Comment by tecpromotion** [comment]
@rdeutz YES, PHP Version Update from 5.3 -> 5.4 -> 5.6. Any ideas?
@brianteeman No htaccess changes.

**Comment by tecpromotion** [comment]
My Problem is solved!
In combination with Git and another version level on the server it came to this behavior. Joomla! 3.3.6 reinstalled over it and everything works again as expected.

**Comment by eloelo22** [comment]
i guess re-installing is the answer by the way thank you for the help

**Comment by brianteeman** [comment]
It is completely unclear who still has an issue and in what circumstances. I am closing this and if you still have this issue on the current supported version of Joomla please create a new issue. Thanks

**Comment by jservices** [comment]
I just started experiencing this issue. I tried copying a fresh fileset but that did not help. I then looked for any error messages but nothing. Then I realized I made some mod_sec changes and voila. Below is the rule that was causing the problem. Not sure if it is too strict a rule or a coding issue, but there you have it, for me at least. DIsabling this rule problem solved.

#
# -=[ Libinjection - XSS Detection ]=-
#
# Ref: https://libinjection.client9.com/
# Ref: https://speakerdeck.com/ngalbreath/libinjection-from-sqli-to-xss
#
SecRule REQUEST_COOKIES|!REQUEST_COOKIES:/__utm/|REQUEST_COOKIES_NAMES|ARGS_NAMES|ARGS|XML:/* "@detectXSS" "msg:'XSS Attack Detected via Libinjection', id:'973343', phase:request, severity:'CRITICAL', rev:'2', ver:'OWASP_CRS/3.0.0', maturity:'1', accuracy:'9', t:none,t:removeNulls,t:utf8toUnicode,t:urlDecodeUni,t:htmlEntityDecode,t:jsDecode,t:cssDecode, block, ctl:auditLogParts=+E, capture, tag:'OWASP_CRS/WEB_ATTACK/XSS', tag:'WASCTC/WASC-8', tag:'WASCTC/WASC-22', tag:'OWASP_TOP_10/A3', tag:'OWASP_AppSensor/IE1', tag:'CAPEC-242', tag:'https://libinjection.client9.com/', logdata:'Matched Data: %{TX.0} found within %{MATCHED_VAR_NAME}: %{MATCHED_VAR}', setvar:'tx.msg=%{rule.msg}', setvar:tx.xss_score=+%{tx.critical_anomaly_score}, setvar:tx.anomaly_score=+%{tx.critical_anomaly_score}, setvar:tx.%{rule.id}-OWASP_CRS/WEB_ATTACK/XSS-%{matched_var_name}=%{tx.0}"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6095">issues.joomla.org/joomla-cms/6095</a>.</sub>

**Comment by xstelios** [comment]
Hi there.. I'm just newbie here and after searching so long about a solution to this problem i can tell that i couldn't find a solution.

I am just another one who is facing the above problem with J 3.4.8. i have tried almost everything with no luck. The strange is that the problem doesn't appear on my localhost but only when it's live on web.

Any help please??

**Comment by devsaurin** [comment]
I encounter with similar issue while path for **tmp** and **log** folder was not set properly. Setting path properly resolved the issue.

**Comment by BrunoBieri** [comment]
I had exactly the same problem in my Joomla 3.5.1 installation. The solution was to disable the "ModSecurity" feature of my space hoster as described here: http://stackoverflow.com/a/29051850/1306012  [Date of link: April 09 2016]

**Comment by B1717** [comment]
I had the same issue (redirected to frontpage; on backend article Save \ Save & Close).
This fix for me was similar, but specifically, in:
WHM Home » Security Center » ModSecurity Vendors  » Manage Vendors.
Disabling the whole OWASP ModSecurity Core Rule Set worked,

So then I checked,and it was 2 rules causing the problem:
rules/REQUEST-41-APPLICATION-ATTACK-XSS.conf
rules/REQUEST-42-APPLICATION-ATTACK-SQLI.conf

**Comment by uglyeoin** [comment]
is there a way to correct this behaviour when editing in the front end?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6095">issues.joomla.org/tracker/joomla-cms/6095</a>.</sub>
