### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by Aeliot-Tm** [joomla/joomla-cms#6099]
I have records in "error_log" file:
PHP Warning:  Invalid argument supplied for foreach() in <site>/administrator/components/com_content/models/article.php on line 486

#### Steps to reproduce the issue

Edit an article in front-end.

#### System information (as much as possible)

Setting	Value
 
PHP Built On	Windows NT 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) i586
Database Version	5.5.25
Database Collation	utf8_general_ci
PHP Version	5.3.13
Web Server	Apache/2.2.22 (Win32) mod_ssl/2.2.22 OpenSSL/1.0.1c PHP/5.3.13
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36

**Comment by waader** [comment]
I can not reproduce that problem using the current staging branch. Can you retry with 3.4.0-Beta3 or the current staging branch?

**Comment by Aeliot-Tm** [comment]
One more information.
I switched on reporting of all errors in my local server. I edit my "php.ini" and write: "error_reporting = E_ALL"

**Comment by waader** [comment]
That is my standard setting. Did you try with the current staging branch?

**Comment by brianteeman** [comment]
After several weeks with no response I am closing this - it can always be reopened if the requested information is provided<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6099">issues.joomla.org/joomla-cms/6099</a>.</sub>
