### ISSUE TITLE
Error when copying beez or hathor in template manager

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#6103]
When I go to template manager and try to copy the beez or hathor template I get this messages:

![joomla34_template](https://cloud.githubusercontent.com/assets/9270310/6227228/3c42fcea-b69d-11e4-905b-9f15276f9100.png)

On the other hand copying isis or protostar does work. I tested this on linux and windows.

**Comment by Hils** [comment]
Using 3.4.0 beta 3 I can copy Hathor & Beez with no errors. (I can also duplicate them). Windows 8.1

**Comment by waader** [comment]
Thanks for testing! I retried with beta3 on linux and had the same problem. Looking in the tmp directory I see that everything is there but the index.html. 

The problem seems to be the reference of index.html in templateDetails.xml.

When I delete this line then I can copy the template successfully. There was some cleanup of index.html files lately. And I couldn´t find a reference to index.html in protostar. So it seems that it was overlooked.

**Comment by Hils** [comment]
Before I check 'deeper' - this is a screenshot of the new template I made from Beez - Beez copied :
![copy-template](https://cloud.githubusercontent.com/assets/736887/6227989/36e3dc6e-
b69e-11e4-87e4-1c0174a7a501.PNG)

that does prove that it copied successfully doesn't it? I did the same with Hathor, successfully.

**Comment by Hils** [comment]
trying again with screenshot
![copy-template](https://cloud.githubusercontent.com/assets/736887/6228044/de7d9686-b69e-11e4-900e-7e5a8f30185f.PNG)

**Comment by Bakual** [comment]
It may be different in a new beta3 installation vs an updated one from 3.3.6.

**Comment by losedk** [comment]
I can confirm the problem. And removing index.html from templatedetails.xml solves the problem

**Comment by Hils** [comment]
for my info: I thought I should be testing on the latest beta - is that wrong please?

**Comment by losedk** [comment]
The problem exists in the latest beta

**Comment by Hils** [comment]
or maybe I should have both set up - I am working on a live server. Don't answer me now - I can ask questions after 3.4.0 is released :) I was just trying to pick a low hanging fruit.

**Comment by Hils** [comment]
"The problem exists in the latest beta" - not on my live test website as my screenshot shows.

**Comment by losedk** [comment]
![skaermbillede 2015-02-17 kl 13 56 40](https://cloud.githubusercontent.com/assets/1738811/6228488/d0e155ea-b6ac-11e4-8670-d68d7bd906d6.png)

**Comment by losedk** [comment]
Anyhow we should delete ```<filename>index.html</filename>``` as the file doesn't exist

**Comment by brianteeman** [comment]
See #6108 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6103">issues.joomla.org/joomla-cms/6103</a>.</sub>
