### ISSUE TITLE
Add more than 1 picture set back to root

### ISSUE THREAD

**Issue by maristo1958** [joomla/joomla-cms#6110]
#### Steps to reproduce the issue
Add a second photo to an article
#### Expected result
You go back to the folder where the photos are
#### Actual result
you go back to the root
#### System information (as much as possible)
Linux www.ditiswijk.nl 3.16.0+ #3 SMP Wed Sep 24 12:51:00 UTC 2014 x86_64
db 5.5.41-0+wheezy1-log
phpv 5.4.36-0+deb7u3
webs Apache/2.2.22 (Debian)
Joomla! 3.3.6 Stable 
Joomla Platform 13.1.0 Stable [ Curiosity ]
#### Additional comments
Previous version you go back to the folder you worked in

**Comment by prasoon2211** [comment]
I can confirm this behaviour but I'm not so sure whether this is a bug. I also checked the 3.3.0 version and found the same behaviour (as staging) there as well. And even if some earlier version of Joomla did keep track of the history while inserting images, this behaviour was evidently removed in the more recent versions and so again, I'm not very sure about this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6110">issues.joomla.org/joomla-cms/6110</a>.</sub>

**Comment by zero-24** [comment]
Thanks. Moving to `Needs Review` so a maintainer can review and see if this is expected behavior or not :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6110">issues.joomla.org/joomla-cms/6110</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this as the expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6110">issues.joomla.org/joomla-cms/6110</a>.</sub>
