### ISSUE TITLE
Error when creating module or component override on windows installation

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#6111]
I tried to create a module/component override in the template manager on an windows installation with the current staging branch. These are the errors I get:

![joomla34_modul_override](https://cloud.githubusercontent.com/assets/9270310/6231606/0d6c98e8-b6c7-11e4-9867-004d0caa77f7.png)

The problem lies in administrator/components/com_templates/models/template.php at line 656

				$return = $this->createTemplateOverride($override . '/tmpl', $htmlPath);

respective Line 660

				$return = $this->createTemplateOverride($override . '/tmpl', $htmlPath);

When str_replace is invoked on Line 706

				$htmlFolder = $htmlPath . str_replace($overridePath, '', $folder);

one will get this - wrong - path as a result when using '/tmpl'
				C:\Program Files (x86)\Ampps\www\joomla34\modules\mod_articles_category\tmpl/default.php

and this - right - path as a result when using DIRECTORY_SEPARATOR . 'tmpl'
				/default.php

Should I change '/tmpl' to DIRECTORY_SEPARATOR  . 'tmpl' or is there a better solution.

**Comment by waader** [comment]
I don´t want to use the "Constant". All I say is that it solves the problem and as I know no better solution I ask for one.

**Comment by sovainfo** [comment]
This is the reason the introduction of DIRECTORY_SEPARATOR in paths needs to be reverted. Any extension manipulating paths needs to cater for platform differences. Now, of course without DS, that was removed with J3!

**Comment by mbabker** [comment]
I'd find it too coincidental if that change managed to break this function as everything in there was previously not using the JPATH_ constants, using `DIRECTORY_SEPARATOR` to break paths, and being standardized to the platform via `JPath::clean()`.

**Comment by waader** [comment]
JPatch::clean() was the answer I look for. Thank you!

**Comment by zero-24** [comment]
Closing as we have a RTC PR here: http://issues.joomla.org/tracker/joomla-cms/6118<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6111">issues.joomla.org/joomla-cms/6111</a>.</sub>
