### ISSUE TITLE
Learning demo data has weblinks article

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla-cms#6112]
#### Steps to reproduce the issue
Install 3.4.0 RC with learning demo data
You will see article link in front to 'Weblinks' in the 'All Modules' menu at left.

In administration this same article is listed in the 'Popular articles' module at the landing page. "Weblinks Module  C 2011-01-01 "

https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/sample_learn.sql#L159
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/sample_learn.sql#L160
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/sample_learn.sql#L323-L324
and
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/sample_learn.sql#L386
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/sample_learn.sql#L444

#### Additional comments
Cosmetic in the learning data but probably still should be removed or have a text explaining that com_weblinks has been removed and can be installed from x-ressource.

**Comment by brianteeman** [comment]
There are also links to the help in every article that point to 3.1 help files<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6112">issues.joomla.org/joomla-cms/6112</a>.</sub>

**Comment by alikon** [comment]
but probably should be better to write updated contents

**Comment by infograf768** [comment]
Closing as we have a patch https://github.com/joomla/joomla-cms/issues/6136

**Comment by ot2sen** [comment]
Think I made a mistake in the report because I think it was the testing data I added. (and the learning then had same weblinks mentions :)  ).
In testings it is the following lines:
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/sample_testing.sql#L156-L157
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/sample_testing.sql#L324-L326
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/sample_testing.sql#L401
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/sample_testing.sql#L451

A quick browse of the postgresql and azuresql didnt reveal any weblinks mentions
