### ISSUE TITLE
Typo in pt-BR translation

### ISSUE THREAD

**Issue by cbahiana** [joomla/joomla-cms#6121]
#### Steps to reproduce the issue
During installation, on the sample content selection screen,string INSTL_SAMPLE_DATA_SET

#### Expected result
Conteúdo de exemplo padrão, em Inglês (GB)

#### Actual result
Conteúdo de exemplo pardrão, em Inglês (GB)

**Comment by prasoon2211** [comment]
Seems right to me. http://goo.gl/adTKoK

I'll send in a PR soon.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6121">issues.joomla.org/joomla-cms/6121</a>.</sub>

**Comment by Bakual** [comment]
Closing in favor of PR
