### ISSUE TITLE
ERROR_XML_LOAD - simplexml_load_file libxml_disable_entity_loader setting is shared between threads

### ISSUE THREAD

**Issue by stovesy** [joomla/joomla-cms#6129]
Sorry for the not overly technical report.

I've been getting spurious ERROR_XML_LOAD. After a little bit of googling, it seems that this is caused by a setting which is under the control of my web host, and as far as I can gather, it may be due to other threads affecting a global setting.

http://stackoverflow.com/questions/20534866/intermittent-simplexml-load-file-i-o-warning-on-local-joomla-site

The main point of error was in language.php
$xml = simplexml_load_file($path);

Changing to this
		$prevSetting = libxml_disable_entity_loader(false);
		$xml = simplexml_load_string(file_get_contents($path));
		libxml_disable_entity_loader($prevSetting);

has helped, but I'm still having errors in the admin, so I am guessing there are other occurrences of simplexml_load_file($path);

I also gather that setting libxml_disable_entity_loader(false) could cause some security issues.

I wonder if this needs investigating. Again, sorry for my lack of bug reporting etiquette.
PHP Version 5.4.17
Thread Safety	disabled
libXML support	active
libXML Compiled Version	2.7.6
libXML Loaded Version	20706
libXML streams	enabled

Simplexml support	enabled
Revision	$Id: 692516840b2d7d6e7aedb0bedded1f53b764a99f $
Schema support	enabled

XML Support	active
XML Namespace Support	active
libxml2 Version	2.7.6

**Comment by mbabker** [comment]
Relevant PHP bug - https://bugs.php.net/bug.php?id=64938

**Comment by brianteeman** [comment]
As this is a php bug and not a joomla bug can it be closed here?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6129">issues.joomla.org/joomla-cms/6129</a>.</sub>
