### ISSUE TITLE
Installation configuration.php tooltip text warning overflows from popup

### ISSUE THREAD

**Issue by ramdesh** [joomla/joomla-cms#6141]
#### Steps to reproduce the issue
1. Start a new installation of Joomla! where the root directory is not writable.
2. Proceed to pre-installation check. 
3. Mouse-over the warning label saying 'No!' next to 'configuration.php Writable'

#### Expected result
The tooltip text within the message popup should be readable.

#### Actual result
The displayed tooltip text overflows the popup, making it unreadable.

#### System information (as much as possible)
Ubuntu 14.04
PHP 5.5.9
Browsers: Chrome 39.0, Firefox 34.0

#### Additional comments
Please see screenshot
![screen shot 2015-02-21 at 13 05 23](http://issues.joomla.org/uploads/1/90d25eeb9bf12979763c6362f3e105dd.png)

**Comment by ramdesh** [comment]
This can be fixed by changing adding *white-space:pre-wrap* to *bootstrap-extended.min.css*. Is it acceptable to fix bootstrap files? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6141">issues.joomla.org/joomla-cms/6141</a>.</sub>

**Comment by zero-24** [comment]
Closing in as we have a PR: https://github.com/joomla/joomla-cms/pull/6142

PS @ramdesh you don't need to add a issue and a pull request for the same issue. If you have code the PR against staging is enough. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6141">issues.joomla.org/joomla-cms/6141</a>.</sub>
