### ISSUE TITLE
same og:description and keywords in all joomla article

### ISSUE THREAD

**Issue by geeksorbit** [joomla/joomla-cms#6147]
I installed several plugins to improve my seo result. But at end of the day. it has produced some bugs, which I can't resolve. All of my article pages are coming with same og:description and og:keywords.
I have uninstalled those plugins successfully and cleared the cache. But still I have the issue. 
I installed:
  [ByeByeGenerator](http://extensions.joomla.org/extensions/extension/site-management/seo-a-metadata/byebyegenerator "ByeByeGenerator")

  [Tagmeta](http://extensions.joomla.org/extensions/extension/site-management/seo-a-metadata/tag-meta "TagMeta")

  [Link with Article Images on Facebook](http://extensions.joomla.org/extensions/extension/site-management/seo-a-metadata/link-with-article-images-on-facebook "Link with Article Images on Facebook")
  

#### System information (as much as possible)
All of my article pages are coming with same og:description and og:keywords.

#### Additional comments

My Website Link is : [Geeksorbit.com](http://geeksorbit.com "Geeksorbit.com")
There are several articles in the home page. You can find all the articles have same og:description and og:keywords.

**Comment by dgt41** [comment]
These come from K2. Take a look at plugins/system/k2/k2.php and you will find the code that injects those metas. 

This is not a Joomla problem!

**Comment by zero-24** [comment]
Closing as not Joomla Core. Maybe this should be reported to K2 people if it is not a settings problem. Thanks @geeksorbit and @dgt41 for checking.

And please @geeksorbit update to the last version of Joomla. As your version is very outdated (following the manifest file and your build details here)!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6147">issues.joomla.org/joomla-cms/6147</a>.</sub>
