### ISSUE TITLE
Menus dropdown on menu items manager

### ISSUE THREAD

**Issue by sural98** [joomla/joomla-cms#6151]
This is a known menu admin problem that needs improvement.
Menu Manager: Menu Items are listed based on alphabetically listed menus.
Imagine a multi-language Joomla of 133 menus and hundreds of menu items.
Menu selection dropdown could be removed so that search tools can be effectively used in such an environment.

#### System information (as much as possible)
Wampserver, Joomla 3.4.0RC, Windows 7

**Comment by brianteeman** [comment]
Sorry that no one ever replied to you.

Could you please describe your issue more clearly as it is a little confusing - perhaps including screenshots will help.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6151">issues.joomla.org/joomla-cms/6151</a>.</sub>

**Comment by sural98** [comment]
Joomla menu manager is menu-based not menu item-based. It loads the first menu (A-Z). Search tools can work within that menu only. If menu manager loads all menu items regardless of menu, search tools can effectively do its job in case you have lots of MENUS with lots of menu items. This feature is the most needed in a multi-language installation of 133 menus and hundreds of menu items.
Thanks for your concern.
![menus](https://cloud.githubusercontent.com/assets/1849490/11150433/b18b1ba6-8a30-11e5-9783-bb8c8b676b93.png)

**Comment by sural98** [comment]
https://github.com/joomla/joomla-cms/pull/8411
That was what I wanted.
I applied on 3.4.8

**Comment by brianteeman** [comment]
Closing as we have a PR that needs testing before it can be merged<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6151">issues.joomla.org/joomla-cms/6151</a>.</sub>
