### ISSUE TITLE
Com_Patchtester Beta-2 Bug

### ISSUE THREAD

**Issue by gwsdesk** [joomla/joomla-cms#6152]
https://github.com/joomla-extensions/patchtester/releases/tag/2.0.0.beta2

Install and move mouse over Title. This should bring up the info screen with the full description how to reproduce and test. Only shows one line. 

![screen shot 2015-02-23 at 03 15 51](http://issues.joomla.org/uploads/1/d16fe027811da3a7f181b2bc06d07be2.jpg)

**Comment by mbabker** [comment]
The tooltip is purposefully truncated to 50 characters max instead of displaying the entire description (since some of the issues can have very lengthy descriptions).  The GitHub and JIssue buttons open the issue in a new window where you can see all of the info.

I can lengthen the tooltip some, but I don't think showing the full description there is a good idea.

**Comment by gwsdesk** [comment]
No I do acknowledge it is not a good idea but the old version showed a 
lot more and therefor I was wondering. Thanks for clarifying this for me :)
On 2/23/2015 8:36 PM, Michael Babker wrote:
>
> The tooltip is purposefully truncated to 50 characters max instead of 
> displaying the entire description (since some of the issues can have 
> very lengthy descriptions). The GitHub and JIssue buttons open the 
> issue in a new window where you can see all of the info.
>
> I can lengthen the tooltip some, but I don't think showing the full 
> description there is a good idea.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/joomla/joomla-cms/issues/6152#issuecomment-75541419>.
>

-- 

Leo Lammerink
MD GWS - Enterprise Ltd
Skype: gwsgroup
www.gws-desk.com <http://www.gws-desk.com> | www.gws-host.com 
<http://www.gws-host.com> | www.gws-deals.today <http://gws-deals.today>

**Comment by Bakual** [comment]
Closing this issue as it relates to com_patchtester which is located at https://github.com/joomla-extensions/patchtester

Also it looks like it already cleared itself.
