### ISSUE TITLE
[JED] Broken images URL's in Joomla Extension Directory

### ISSUE THREAD

**Issue by Red-Lolik** [joomla/joomla-cms#6153]
Changed links to images in http://extensions.joomla.org/
That's why they do not show.
![administrator_index_php_option com_installer](https://cloud.githubusercontent.com/assets/4174845/6325996/1b3a4920-bb5e-11e4-88c1-d3b64820e858.png)

**Comment by sovainfo** [comment]
See https://github.com/joomla/joomla-cms/issues/5689

**Comment by infograf768** [comment]
Closing as issue is well known and not yet solved
See https://github.com/joomla-extensions/install-from-web-server/pull/4
