### ISSUE TITLE
"Nothing to update" is not an error condition

### ISSUE THREAD

**Issue by Paladin** [joomla/joomla-cms#6157]
When updating a component that has had no schema changes since inception, the installer will reject the update with a SQL error, despite the db saying there is no sql error. This is caused because the installer library file is set to treat the "no schema updates, in history of component" as an error condition.

This is wrong. At any later point in the update cycle, the installer will cheerfully accept that no schema update was necessary for the update; the only "special" point is code updates that haver never required schema updates.

Pull Request submitted to fix this issue:
https://github.com/joomla/joomla-cms/pull/6156

**Comment by Paladin** [comment]
Um, what do you think a Pull Request *is*, you silly bot?

**Comment by zero-24** [comment]
@Paladin 

>Um, what do you think a Pull Request is, you silly bot?

hehe :smile:

You do not longer need to open a issue if you have a pull. So you can close here.

A issue has per definition no code attached :smile: So @joomla-cms-bot is right here :smile:

**Comment by Bakual** [comment]
Closing in favor of the PR #6156

**Comment by Paladin** [comment]
Ya beat me to it. I just came in here to close it myself.
