### ISSUE TITLE
Postgresql: Search in Module Manager gives an error

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#6159]
Go to the Module Manager in Backend and try to search for a term. You should get this error:

Error

SQL=SELECT a.id, a.title, a.note, a.position, a.module, a.language,a.checked_out, a.checked_out_time, a.published+2*(e.enabled-1) as published, a.access, a.ordering, a.publish_up, a.publish_down,l.title AS language_title,uc.name AS editor,ag.title AS access_level,MIN(mm.menuid) AS pages,e.name AS name FROM "invtf_modules" AS a LEFT JOIN "invtf_languages" AS l ON l.lang_code = a.language LEFT JOIN invtf_users AS uc ON uc.id=a.checked_out LEFT JOIN invtf_viewlevels AS ag ON ag.id = a.access LEFT JOIN invtf_modules_menu AS mm ON mm.moduleid = a.id LEFT JOIN invtf_extensions AS e ON e.element = a.module WHERE (a.published IN (0, 1)) AND a.client_id = 0 AND e.client_id =0 AND (a.title REGEXP 'tag' OR a.note REGEXP 'tag') GROUP BY a.id, a.title, a.note, a.position, a.module, a.language,a.checked_out,a.checked_out_time, a.published, a.access, a.ordering,l.title, uc.name, ag.title, e.name,l.lang_code, uc.id, ag.id, mm.moduleid, e.element, a.publish_up, a.publish_down,e.enabled SQL=SELECT a.id, a.title, a.note, a.position, a.module, a.language,a.checked_out, a.checked_out_time, a.published+2*(e.enabled-1) as published, a.access, a.ordering, a.publish_up, a.publish_down,l.title AS language_title,uc.name AS editor,ag.title AS access_level,MIN(mm.menuid) AS pages,e.name AS name FROM "invtf_modules" AS a LEFT JOIN "invtf_languages" AS l ON l.lang_code = a.language LEFT JOIN invtf_users AS uc ON uc.id=a.checked_out LEFT JOIN invtf_viewlevels AS ag ON ag.id = a.access LEFT JOIN invtf_modules_menu AS mm ON mm.moduleid = a.id LEFT JOIN invtf_extensions AS e ON e.element = a.module WHERE (a.published IN (0, 1)) AND a.client_id = 0 AND e.client_id =0 AND (a.title REGEXP 'tag' OR a.note REGEXP 'tag') GROUP BY a.id, a.title, a.note, a.position, a.module, a.language,a.checked_out,a.checked_out_time, a.published, a.access, a.ordering,l.title, uc.name, ag.title, e.name,l.lang_code, uc.id, ag.id, mm.moduleid, e.element, a.publish_up, a.publish_down,e.enabled ORDER BY "position" asc,a.ordering ASC LIMIT 20 SQL=SELECT a.id, a.title, a.note, a.position, a.module, a.language,a.checked_out, a.checked_out_time, a.published+2*(e.enabled-1) as published, a.access, a.ordering, a.publish_up, a.publish_down,l.title AS language_title,uc.name AS editor,ag.title AS access_level,MIN(mm.menuid) AS pages,e.name AS name FROM "invtf_modules" AS a LEFT JOIN "invtf_languages" AS l ON l.lang_code = a.language LEFT JOIN invtf_users AS uc ON uc.id=a.checked_out LEFT JOIN invtf_viewlevels AS ag ON ag.id = a.access LEFT JOIN invtf_modules_menu AS mm ON mm.moduleid = a.id LEFT JOIN invtf_extensions AS e ON e.element = a.module WHERE (a.published IN (0, 1)) AND a.client_id = 0 AND e.client_id =0 AND (a.title REGEXP 'tag' OR a.note REGEXP 'tag') GROUP BY a.id, a.title, a.note, a.position, a.module, a.language,a.checked_out,a.checked_out_time, a.published, a.access, a.ordering,l.title, uc.name, ag.title, e.name,l.lang_code, uc.id, ag.id, mm.moduleid, e.element, a.publish_up, a.publish_down,e.enabled ORDER BY "position" asc,a.ordering ASC

**Comment by alikon** [comment]
i think  the REGEXP function is mysql only 
in postgresql should be ~* or SIMILAR TO 
in MSSQL i don't know 

i'll look into...

**Comment by zero-24** [comment]
Closing as we have a PR: http://issues.joomla.org/tracker/joomla-cms/6188<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6159">issues.joomla.org/joomla-cms/6159</a>.</sub>
