### ISSUE TITLE
MSSQL: Similar tags module gives an error

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#6160]
The Similar tags module gives the following error:

42 [Microsoft][SQL Server Native Client 11.0][SQL Server]Invalid column name 'count'.SQL=SELECT [m].[core_content_id],[m].[content_item_id],[m].[type_alias],COUNT( [tag_id]) AS [count],[ct].[router],[cc].[core_title],[cc].[core_alias],[cc].[core_catid],[cc].[core_language],[cc].[core_params] , ROW_NUMBER() OVER (ORDER BY [count] DESC) AS RowNumber FROM [aqmag_contentitem_tag_map] AS [m] INNER JOIN [aqmag_tags] AS [t] ON m.tag_id = t.id INNER JOIN [aqmag_ucm_content] AS [cc] ON m.core_content_id = cc.core_content_id INNER JOIN [aqmag_content_types] AS [ct] ON m.type_alias = ct.type_alias WHERE [m].[tag_id] IN (2,3,4,5) AND t.access IN (1,1) AND (cc.core_access IN (1,1) OR cc.core_access = 0) AND ([m].[content_item_id] <> 24 OR [m].[type_alias] <> 'com_content.article') AND [cc].[core_state] = 1 AND ([cc].[core_publish_up]='1900-01-01 00:00:00' OR [cc].[core_publish_up]<='2015-02-23 18:18:17') AND ([cc].[core_publish_down]='1900-01-01 00:00:00' OR [cc].[core_publish_down]>='2015-02-23 18:18:17') GROUP BY [m].[core_content_id],[m].[content_item_id],[m].[type_alias],[ct].[router],[cc].[core_title],[cc].[core_alias],[cc].[core_catid],[cc].[core_language],[cc].[core_params]

**Comment by pmorrisarctg** [comment]
At first look of the error it looks like the column [count] is still being referenced for tag sorting. The core test data must be updated for conform to MS SQL code. Does that help? We can take a look at this module and update the data if needed. Looks like it may be.

**Comment by waader** [comment]
I have install the testing sample data but could not spot a problem here. I suspect that the query is not build in a compatible way.

**Comment by pmorrisarctg** [comment]
Yes the sample data has column=count. There must be another instance that needs to be corrected in the sample data. We can take a look? 

Thanks again.
Patrick

**Comment by waader** [comment]
That would be great. Thanks!

**Comment by brianteeman** [comment]
It has been 9 months since the last comment - is this still an issue or has it been resolved elsewhere and can be closed?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6160">issues.joomla.org/joomla-cms/6160</a>.</sub>

**Comment by waader** [comment]
I will retest at the weekend.

**Comment by waader** [comment]
This issue can be closed as it is not present anymore. Thanks!

**Comment by zero-24** [comment]
Thanks
