### ISSUE TITLE
Error 404 Activating Install from Web Tab

### ISSUE THREAD

**Issue by sonkoral** [joomla/joomla-cms#6165]
#### System information (as much as possible)

PHP Built On	Darwin MacBook-Pro.local 14.1.0 Darwin Kernel Version 14.1.0: Mon Dec 22 23:10:38 PST 2014; root:xnu-2782.10.72~2/RELEASE_X86_64 x86_64
Database Version	5.5.38
Database Collation	latin1_swedish_ci
PHP Version	5.5.14
Web Server	Apache/2.2.26 (Unix) mod_fastcgi/2.4.6 mod_wsgi/3.4 Python/2.7.6 PHP/5.5.14 mod_ssl/2.2.26 OpenSSL/0.9.8zc DAV/2 mod_perl/2.0.8 Perl/v5.18.2
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.4.0-beta1 Beta [ Ember ] 27-January-2015 20:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

#### Additional comments

I'm getting an error 400 message when activating the Install from Web tab on localhost. I dumped the install and reinstalled again thinking it was just that instance, but got the error 400 message again.

1. downloaded J3.4 beta1 from site
2. unzipped into htdocs/j34b1 (localhost)
3. installed via web installer
4. tried to activate Install from Web tab.

Using MAMP Version 3.0.6. - Anyone else having a problem with this?

"Warning
Update: :Extension: Could not open http://appscdn.joomla.org/webapps/jedapps/webinstaller.xml

Error connecting to the server: 404"

**Comment by rdeutz** [comment]
Due some technically problems we are disabling the install from web for the time we are fixing the problem. So the plugin install should work later again but you will be not able to install extensions when we are done with disabling.

**Comment by sonkoral** [comment]
Thank you. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6165">issues.joomla.org/joomla-cms/6165</a>.</sub>
