### ISSUE TITLE
Joomla 3.3.6 Add :Install from Web responses with Tralala

### ISSUE THREAD

**Issue by loconel** [joomla/joomla-cms#6166]
#### Steps to reproduce the issue
Click in Joomla 3.3.6 
Extension
Extension Manager
Add "Install from Web" tab

#### Expected result

Install menu

#### Actual result

response is text: TRALALA

#### System information (as much as possible)

Diagnosis: 

jedapps_jsonpcallback({"success": true, "message": "", "messages": null, "data": {"html": "<div class=\"com-apps-container\"><div class=\"row-fluid\"><h1>TRALALA<\/h1><\/div><\/div>","pluginuptodate":1 }})
http://appscdn.joomla.org/webapps/index.php?format=json&option=com_apps&view=dashboard&product=Sm9vbWxhIQ==&release=My4z&dev_level=Ng==&list=grid&pv=MS4wLjU=&callback=jedapps_jsonpcallback

**Comment by mbabker** [comment]
Some of the CDN nodes apparently still have a cached test message in there.  This isn't a hack, we promise.  See https://twitter.com/joomla/status/570364784077451265 for more info.
