### ISSUE TITLE
Incorrect Joomla 3.4.0 .tar.bz2 dowload link

### ISSUE THREAD

**Issue by shur** [joomla/joomla-cms#6167]
When I visited Joomla releases page https://github.com/joomla/joomla-cms/releases
and tried to download Joomla 3.4.0 .tar.bz2 archive I got 404 error.

I figured out this line:
> New Joomla! Installations .tar.bz2 | .tar.gz | .zip

has incorrect link to .tar.bz2 archive.

Same problem in these releases:
Joomla! 3.4.0
3.4.0 Release Candidate
3.4.0 Beta 3

**Comment by infograf768** [comment]
Corrected for Joomla_3.4.0-Stable-Full_Package.tar.bz2

RC and beta3 are no more use, so I did not touch them.
