### ISSUE TITLE
J3.4 admin submenu items not scollable on smartphone

### ISSUE THREAD

**Issue by hans2103** [joomla/joomla-cms#6174]
I cannot scroll through the sub menu items of the J3.4 administrator menu on my smartphone.

- get your smartphone
- log in on administrator
- click the hamburger to open the main menu
- click the menu item components to open the dropdown
- try to scroll down on this list of sub menu items
- notice that it will not work... you will scroll the entire page... I was expecting that only the content in the menu would scroll.

people cannot open the third, fourth and latter sub menu items of Components.

**Comment by brianteeman** [comment]
@hans2103 I could confirm this by resizing my browser but I could NOT confirm it on a real smartphone where the same menu works perfectly on the same site<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6174">issues.joomla.org/joomla-cms/6174</a>.</sub>

**Comment by brianteeman** [comment]
@hans2103 Please can you test #6190 and let us know if this fixes the problem for you

**Comment by zero-24** [comment]
Moving to `Information Required` as we wait for response by @hans2103<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6174">issues.joomla.org/joomla-cms/6174</a>.</sub>

**Comment by hans2103** [comment]
Will test it tomorrow

**Comment by hans2103** [comment]
#6190 describes my problem.
This issue can be closed since it's duplicate with #6190.
