### ISSUE TITLE
Problem with multiulanguage site after upgrad to J3.4

### ISSUE THREAD

**Issue by CarstenSp** [joomla/joomla-cms#6176]
#### Steps to reproduce the issue
Upgrade from multilanguage site Joomla 3.3.6 to 3.4

#### Expected result
Frontend does not work (site cannot be loaded).

#### System information (as much as possible)
Languages installed prior to J3.4 do not have an Access level assigned in
Extensions->Languages->Content
Each content language must be accessed and saved with "Public" access level to make language switching available in J3.4

**Comment by brianteeman** [comment]
Please see #6172 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6176">issues.joomla.org/joomla-cms/6176</a>.</sub>

**Comment by Seppo48** [comment]
Hello I bought today Falang 2.0.0 for Joomla 3.4.
After instalation i get the following error message in the backend

An error has occurred .

    1146 Table ' SUNSHINE_TEST.mhoqa_falang_tableinfo ' does not exist SQL = SELECT tablename joomla , tablepkID FROM ` mhoqa_falang_tableinfo`

It is impossible to install it ! Does anyone have an idea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6176">issues.joomla.org/joomla-cms/6176</a>.</sub>

**Comment by infograf768** [comment]
@Seppo48 
This is not related to Joomla core. Please contact the falang developer .```
