### ISSUE TITLE
Missing Element in frontendediting.js

### ISSUE THREAD

**Issue by WS-Theme** [joomla/joomla-cms#6177]
#### Steps to reproduce the issue

When you are logged in into the Frontend and the Hover Buttons for Module Editing are Active, the Tooltip breaks and is not valid. This happens cause in the call for the Tooltip a Attribute is Missing!

#### Additional comments

In Frontendediting.js (the uncompressed Version for better overview) there is something missing in line 121!

Actual: .tooltip({"container": false, placement: tooltipPlacer})

Must be: .tooltip({"container": false, html: true, placement: tooltipPlacer})![screen shot 2015-02-25 at 08 24 46](http://issues.joomla.org/uploads/1/435f3b1814500f252ac7af2ceb238451.png)

**Comment by Bakual** [comment]
Since you seem to know where the issue is, can you create a Pull Request?
See https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests for how to do it. We can help you if you have questions.
This way it can be tested.

**Comment by brianteeman** [comment]
I can NOT confirm this - perhaps its a language ini file issue?

![screen shot 2015-02-25 at 08 36 27](http://issues.joomla.org/uploads/1/dc4cd36746cc5dcb7d8d2b661f735bcc.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6177">issues.joomla.org/joomla-cms/6177</a>.</sub>

**Comment by WS-Theme** [comment]
Yes but I personally have disabled the HTML Option for public Tooltips!! So it's definitly missing, when the Tooltip is called again, the HTML Option is missing and must be reinitialised!

In Frontend I have disabled cause of this:

Insert HTML into the tooltip. If false, jQuery's text method will be used to insert content into the DOM. Use text if you're worried about XSS attacks.

For registered Users I think it's no problem!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6177">issues.joomla.org/joomla-cms/6177</a>.</sub>

**Comment by brianteeman** [comment]
As we have a PR I am closing this here so the conversation is in one place - see #6179 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6177">issues.joomla.org/joomla-cms/6177</a>.</sub>

**Comment by WS-Theme** [comment]
Exactly!! Sorry for Double Postings! I only want to bring Joomla to a better Level! And Frontend Editing for example is important ... but at the Moment, Frontend Editing is generally a Horrible Thing!

For example: we and a Partner a Elite Authors at Envato with nearly 5.000 sold Templates, but most Templates work on Bootstrap 3 which is conflicting extremely with Bootstrap 2 Mark Up that comes for default ...

**Comment by brianteeman** [comment]
No problem about the double posting it is normal

As for BS3 then you will love what is happening with J3.5 as it will make
your life much easier

On 25 February 2015 at 18:48, Oli <notifications@github.com> wrote:

> Exactly!! Sorry for Double Postings! I only want to bring Joomla to a
> better Level! And Frontend Editing for example is important ... but at the
> Moment, Frontend Editing is generally a Horrible Thing!
>
> For example: we and a Partner a Elite Authors at Envato with nearly 5.000
> sold Templates, but most Templates work on Bootstrap 3 which is conflicting
> extremely with Bootstrap 2 Mark Up that comes for default ...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6177#issuecomment-76028593>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by WS-Theme** [comment]
Really Brian? Is is planned to add B3 Support for J3.5?? Never heared about this!

**Comment by brianteeman** [comment]
It is planned to make some changes to allow for easier support of other
frameworks

On 25 February 2015 at 21:25, Oli <notifications@github.com> wrote:

> Really Brian? Is is planned to add B3 Support for J3.5?? Never heared
> about this!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6177#issuecomment-76063476>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by WS-Theme** [comment]
Yes I have seen :+1: in Joomla 3.7 yes :-)

**Comment by bembelimen** [comment]
Could someone provide a (free) template which "supports" this bug?
