### ISSUE TITLE
Codemirror Can't Type Forward Slash

### ISSUE THREAD

**Issue by BettonDesign** [joomla/joomla-cms#6181]
#### Steps to reproduce the issue
Set Codemirror as default editor.
Either create a new article or edit an existing article.
Type a forward slash ( / ) in the editor window.

#### Expected result
A forward slash appears in the editor window

#### Actual result
Nothing appears in the editor window.

#### System information (as much as possible)
PHP Built On 	Linux 908539.vps-10.com 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 23:32:49 UTC 2014 x86_64
Database Version 	5.5.42-cll-lve
Database Collation 	utf8_general_ci
PHP Version 	5.5.13
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.4.0 Stable [ Ember ] 24-February-2015 23:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0

**Comment by BettonDesign** [comment]
Codemirror bug and fix can be found here: https://github.com/codemirror/CodeMirror/commit/076afcb14e8be6[Your text to link here...](https://github.com/codemirror/CodeMirror/commit/076afcb14e8be635439e1689d8c3af2ffcfbce85 "https://github.com/codemirror/CodeMirror/commit/076afcb14e8be635439e1689d8c3af2ffcfbce85")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6181">issues.joomla.org/joomla-cms/6181</a>.</sub>

**Comment by PhilETaylor** [comment]
PR #6280 ready for testing

**Comment by PhilETaylor** [comment]
suggest closing this in favor of https://github.com/joomla/joomla-cms/pull/6150
