### ISSUE TITLE
Jstring not loaded on Joomla 3.4

### ISSUE THREAD

**Issue by akurczyn** [joomla/joomla-cms#6183]
#### Steps to reproduce the issue
A module has the following line:
$fullnoimage = Jstring::substr_replace($fullnoimage, '', $ini, $fin - $ini + 1);

#### Expected result
It should just return the expected string replacement.

#### Actual result
Fatal error: Class 'Jstring' not found in .../default_parse.php on line 46 

#### System information (as much as possible)
Joomla 3.3.6 updated to 3.4

#### Additional comments
AFAIK the way the call is being made is correct, does it need to be done differently on Joomla 3.4?

**Comment by Fedik** [comment]
try `JString`

**Comment by akurczyn** [comment]
That works. Is there areason why this was case insensitive before and now it is not?

**Comment by Fedik** [comment]
in global PHP class and methods is case insensitive,

in Joomla, class autoloader depend a lot from it,
it worked before because `JString` was loaded already somewhere else

**Comment by mbabker** [comment]
With some refactoring between 3.3.6 and 3.4.0, JString went from a class that was loaded very early in the stack to being a class that can optionally not be used at all in a request cycle.  For many autoloaders, the first use of a class is going to be the most sensitive to cases.  So for consistency, it's best to always use the case as it's declared by the class.

**Comment by akurczyn** [comment]
Thanks a lot for the help!

**Comment by kappadev** [comment]
Hi guys, i installed yesterday Joomla 3.4.1 and some K2 modules don't show up properly and i get the error: Class 'Jstring' not found in .../default_parse.php on line 46

i understand what you say above but i don't know how to fix it, i'm not a programmer but if you tell me how i'll manage it i believe :-)

thanks in advance

**Comment by ogonzy** [comment]
This help really worked for me. Thank you very much for posting.
