### ISSUE TITLE
Website out after automatic update to 3.4

### ISSUE THREAD

**Issue by jschmi01** [joomla/joomla-cms#6184]
ran automatic upgrade from 3.3.6 to 3.4. After Upgrade my Website was'nt accessible anymore, as recursive redirects happened to .../index.php?. (should be ../index.php/?lang=en)
Problem was caused by language switcher system plugin (my site is multi lingual). Problem could only be fixed by going to Language Manager -> Content and clicking  on every language and doing a save&close. This happened to all of my sites where language switcher plugin was enabled. 

Is this a bug or special situation? 

At least there should be a post-installation hint, as this took quite a time to find out.

**Comment by PhilETaylor** [comment]
Known issue resolved already 

see: https://github.com/joomla/joomla-cms/issues/6169
