### ISSUE TITLE
Component Menu does not scroll

### ISSUE THREAD

**Issue by SwingShoes** [joomla/joomla-cms#6185]
#### Steps to reproduce the issue
If Components Menu on Isis Admin Template has many items and falls below bottom border of window, it will not scroll to reveal additional menu items. This is a problem for small viewports of netbooks, macbook airs, or just when the window size is reduced.  

#### Expected result
Menu should scroll if additional items are contained.

#### Actual result
Does not scroll. Impossible to see additional menu items. 

#### System information (as much as possible)
Joomla 3.4 and prior versions. 

#### Additional comments
This issue has been mentioned before and is always ignored. It seems trivial, but it is illogical for a menu to not scroll to reveal its contents.

**Comment by brianteeman** [comment]
Thanks for reporting this - we already have an open issue #5131 so I am closing this as a duplicate<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6185">issues.joomla.org/joomla-cms/6185</a>.</sub>
