### ISSUE TITLE
Language Filter Plugin not detecting browser language

### ISSUE THREAD

**Issue by sriadmin** [joomla/joomla-cms#6186]
#### Steps to reproduce the issue
After updating Joomla 3.3.6. to Joomla 3.4 the mulilingual website fails to open in the language set by the browser. Worked flawlessly in Joomla 3.3.6.

**Comment by sveinaberg** [comment]
I have the same problem, and our site goes into a redirect loop with the language filter plugin enabled. I don't have time to study the code, but an upload of the previous version seems to fix it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6186">issues.joomla.org/joomla-cms/6186</a>.</sub>

**Comment by brianteeman** [comment]
Please see #6171 for a solution<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6186">issues.joomla.org/joomla-cms/6186</a>.</sub>

**Comment by brianteeman** [comment]
Sorry I meant #6172 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6186">issues.joomla.org/joomla-cms/6186</a>.</sub>

**Comment by sveinaberg** [comment]
Strangely enough, the redirect loop happened only in Chrome. In Firefox, the site opened, but it was not possible to change the language.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6186">issues.joomla.org/joomla-cms/6186</a>.</sub>

**Comment by sriadmin** [comment]
Thank you for your comments! I can confirm that installing the previous version of the languagefilter plugin shipped in Joomla 3.3.6 fixes the issue. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6186">issues.joomla.org/joomla-cms/6186</a>.</sub>

**Comment by infograf768** [comment]
It is not advised to exchange the languagefilter versions.
It is very simple to just re-save your Content Languages.
For the future we will have a patch.

**Comment by zero-24** [comment]
Closing here as this can be fixed by resave the content language at the language manager and will be fixed with: https://github.com/joomla/joomla-cms/pull/6194 for 3.4.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6186">issues.joomla.org/joomla-cms/6186</a>.</sub>
