### ISSUE TITLE
DI Package alias bug

### ISSUE THREAD

**Issue by vess** [joomla/joomla-cms#6187]
The Bug is fixed in the framework package, but still exists within the CMS.
See https://github.com/joomla-framework/di/pull/10

**Comment by zero-24** [comment]
Closing here as we have a PR by @mbabker https://github.com/joomla/joomla-cms/pull/6192<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6187">issues.joomla.org/joomla-cms/6187</a>.</sub>
