### ISSUE TITLE
error notices are "none", when I change, then I get "content encoding error" and have lost all

### ISSUE THREAD

**Issue by jojo12** [joomla/joomla-cms#6189]
#### Steps to reproduce the issue
my error notices are "none", when I change e.g. to "standard", then I get "content encoding error" and don't reach anymore backend and frontend, until I change back in configuration.php the error notices to "none"

#### Actual result
my error notices are "none", when I change e.g. to "standard", then I get "content encoding error" and don't reach anymore backend and frontend, until I change back in configuration.php the error notices to "none"

#### System information (as much as possible)
Joomla! 3.4 stable updated from 3.3.6.
Einstellung 	Wert
 
PHP erstellt für 	Linux server46.hostfactory.ch 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64
Datenbankversion 	5.5.40-0+wheezy1
Datenbankzeichensatz 	utf8_general_ci
PHP-Version 	5.4.36-0+deb7u3
Webserver 	Apache
PHP-Interface für den Webserver 	cgi-fcgi
Joomla!-Version 	Joomla! 3.4.0 Stable [ Ember ] 24-February-2015 23:00 GMT
Joomla!-Plattform-Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Browsererkennung 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:35.0) Gecko/20100101 Firefox/35.0 

#### Additional comments
the same window comes on some other places but cannot say all.![screen shot 2015-02-25 at 14 39 11](http://issues.joomla.org/uploads/1/25af60e2cceecc7ad4b61de7407a5b54.png)

**Comment by PhilETaylor** [comment]
Disable Gzip encoding in Joomla Global Configuration in Joomla Admin or edit manually /configuration.php and set 

```$gzip = '0';```

Something on your server is already Gzipping the response, so Joomla doesnt need to.

**Comment by jojo12** [comment]
Thanks, this solved it! Can be closed
