### ISSUE TITLE
Extension Manager - Database Debug Console Rendering Issue

### ISSUE THREAD

**Issue by Mathewlenning** [joomla/joomla-cms#6193]
While installing J 3.4.0, the install threw an error trying to update the database. Although there were no really negative side effects that I could find, the database schema wasn't updated, so I navigated to the  Extension Manager - Database view to run the fix. 

That is when I noticed the debug console was rendering incorrectly with the new sidebar. 

Here is a screenshot

![extension manager - database](https://cloud.githubusercontent.com/assets/3743651/6385171/9b3f265c-bda9-11e4-96e3-da201f92c536.png)

To reproduce go to the #__schema table and change the joomla version number to 3.3.6 then view the  Extension Manager - Database view.

**Comment by pcmitsis** [comment]
With an old version i was able to reproduce your error. But with the latest staging branch it is fixed. The error was in this [file](https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/js/template.js). Download the latest version and you will be fine! 

This issue should close!

Cheers,
Panos

**Comment by zero-24** [comment]
Closing as this issue is fixed by @Harmageddon with: https://github.com/joomla/joomla-cms/commit/bc868e6b9c2ee7fecec10224de21e6a20baaf03f Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6193">issues.joomla.org/joomla-cms/6193</a>.</sub>

**Comment by pcmitsis** [comment]
You are welcome @zero-24 !

**Comment by Mathewlenning** [comment]
Awesome =^D great work @hannes

Sincerely,
Mathew Lenning

Babel-university.com

P.S. This message was sent via iPhone, so please forgive any errors

**Comment by Mathewlenning** [comment]
I mean @Harmageddon

Sincerely,
Mathew Lenning

Babel-university.com

P.S. This message was sent via iPhone, so please forgive any errors
