### ISSUE TITLE
Installation packages with small php files fail 'safe' file checks  

### ISSUE THREAD

**Issue by GeraintEdwards** [joomla/joomla-cms#6196]
when installing an uploaded package file the $_FILES data is passed through a safety filter via JFilterInput::isSafeFile but for short PHP files the check 
```php
if ($options['php_tag_in_content'] && strstr($buffer, '<?php'))
```
BUT if one of the files in the zip file is short e.g. 
```php
<?php 
defined('_JEXEC') or die('Restricted access');
```
then the zip algorithm doesn't compress the content when creating the zip package and leaves the raw file content in the zip file.  This means that the uploaded file will incorrectly fail this safety check when there is no reason for it to do so.

**Comment by Bakual** [comment]
Should be already fixed with https://github.com/joomla/joomla-cms/pull/6180

Closing.
