### ISSUE TITLE
InstallerModelDatabase::fixSchemaVersion() malformed SQL INSERT query

### ISSUE THREAD

**Issue by lmcculley** [joomla/joomla-cms#6204]
Lines [152-157](https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_installer/models/database.php#L152-L157) of `/administrator/components/com_installer/models/database.php` improperly uses the `set` clause with an `insert` query. 

```
// Add new row.
$query->clear()
	->insert($db->quoteName('#__schemas'))
	->set($db->quoteName('extension_id') . '= 700')
	->set($db->quoteName('version_id') . '= ' . $db->quote($schema));
$db->setQuery($query);
```

And should instead be similar to the following:
```
$query->clear()
	->insert($db->quoteName('#__schemas') . " (" . $db->quoteName('extension_id') . "," . $db->quoteName('version_id') . ") ")
	->values('700, ' . $db->quote($schema));
$db->setQuery($query);
```

**Comment by zero-24** [comment]
Closing here as we have a PR: https://github.com/joomla/joomla-cms/pull/6219 Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6204">issues.joomla.org/joomla-cms/6204</a>.</sub>

**Comment by phproberto** [comment]
Merged. Thanks!
