### ISSUE TITLE
Warning Message when saving duplicate alias title does not give proper message

### ISSUE THREAD

**Issue by Josh-Lewis** [joomla/joomla-cms#6206]
**Intro:**

As of Joomla 3.4 alias incrementing was implemented making it possible for users to more easily create articles with the same name. If an article named "joomla-tutorial" already existed and someone creates another one, the alias will automatically become "joomla-tutorial-1" and so on. In the backend when submitting an already existing alias it says "Warning Alias already existed so a number was added at the end. You can re-edit the article to customise the alias." which is an informative warning. However when submitting an article on the frontend it says "Warning COM_CONTENT_SAVE_WARNING". The language constant does not display the intended message for frontend users, but does for backend users.

**Expected Result:**

Ideally when submitting an article with a duplicate alias on the frontend it should say "Warning Alias already existed so a number was added at the end. You can re-edit the article to customise the alias" so that it's consistent with the backend and is informative to the user instead of displaying a language constant.

**System Information:**
 
Database Version 	5.5.32-31.0-log
Database Collation 	utf8_general_ci
PHP Version 	5.5.17
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.4.0 Stable [ Ember ] 24-February-2015 23:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:36.0) Gecko/20100101 Firefox/36.0

**Comment by brianteeman** [comment]
I can confirm that there is a string without value
COM_CONTENT_SAVE_WARNING

I think it needs to be a slightly different message though on the front end as you cannot directly change an alias on the front end.

Perhaps
COM_CONTENT_SAVE_WARNING="Alias already existed so a number was added at the end. You can re-edit the article in the Administrator to customise the alias."

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6206">issues.joomla.org/joomla-cms/6206</a>.</sub>

**Comment by brianteeman** [comment]
Please see #6208 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6206">issues.joomla.org/joomla-cms/6206</a>.</sub>

**Comment by Josh-Lewis** [comment]
Thanks for the pull request Brian. While the word choice you have is decent (You can re-edit the article in the Administrator to customise the alias) not everyone has access to the backend. On community sites it's much more likely that users do not have access to the backend.

From my point of view anyone who has a decent understanding of Joomla would know where to edit an article alias. But I could see how some wouldn't know.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6206">issues.joomla.org/joomla-cms/6206</a>.</sub>

**Comment by brianteeman** [comment]
So does it need something like "If you want to change the alias, please
contact a site administrator"

Completely open to any and all suggestions

On 27 February 2015 at 08:48, Josh-Lewis <notifications@github.com> wrote:

> Thanks for the pull request Brian. While the word choice you have is
> decent (You can re-edit the article in the Administrator to customise the
> alias) not everyone has access to the backend. On community sites it's much
> more likely that users do not have access to the backend.
>
> From my point of view anyone who has a decent understanding of Joomla
> would know where to edit an article alias. But I could see how some
> wouldn't know.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/6206
> <http://issues.joomla.org/tracker/joomla-cms/6206>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6206#issuecomment-76357393>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Josh-Lewis** [comment]
That word choice works pretty good. It properly informs users and administrators. In addition to that it informs non admins that it can be changed by the right people. :-)

**Comment by brianteeman** [comment]
Updated PR #6210

**Comment by Josh-Lewis** [comment]
Thanks Brian. :-)
