### ISSUE TITLE
3.4  Clear Cache Not Working It is a blank white Page

### ISSUE THREAD

**Issue by greenlizzard24** [joomla/joomla-cms#6209]
#### Steps to reproduce the issue
Upgraded from 3.36 to 3.4, purged the cache went to the menu system>>Clear Cache 
#### Expected result

Page to Clear Cache

#### Actual result
Blank Screen

Fatal error: Cannot redeclare class CacheHelper in /home/vol8_5/gl-domains.cu.cc/gldo_14811349/htdocs/administrator/components/com_cache/helpers/cache.php on line 18

#### System information (as much as possible)

Setting	Value
 
PHP Built On	Linux freeweb10.byetcluster.com 2.6.32-531.23.3.lve1.3.6.el6.x86_64 #1 SMP Mon Sep 29 16:27:54 CEST 2014 x86_64
Database Version	5.6.22-71.0
Database Collation	latin1_swedish_ci
PHP Version	5.4.35
Web Server	Apache
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.4.0 Stable [ Ember ] 24-February-2015 23:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36

**Comment by brianteeman** [comment]
What are your settings for cache in the global configuration?
Do you have the system cache plugin enabled

This information will help testers



On 27 February 2015 at 09:36, greenlizzard24 <notifications@github.com>
wrote:

> Steps to reproduce the issue
>
> Upgraded from 3.36 to 3.4, purged the cache went to the menu system>>Clear
> Cache
> Expected result
>
> Page to Clear Cache
> Actual result
>
> Blank Screen
>
> Fatal error: Cannot redeclare class CacheHelper in /home/vol8_5/
> gl-domains.cu.cc/gldo_14811349/htdocs/administrator/components/com_cache/helpers/cache.php
> on line 18
> System information (as much as possible)
>
> Setting Value
>
> PHP Built On Linux freeweb10.byetcluster.com
> 2.6.32-531.23.3.lve1.3.6.el6.x86_64 #1
> <https://github.com/joomla/joomla-cms/pull/1> SMP Mon Sep 29 16:27:54
> CEST 2014 x86_64
> Database Version 5.6.22-71.0
> Database Collation latin1_swedish_ci
> PHP Version 5.4.35
> Web Server Apache
> WebServer to PHP Interface apache2handler
> Joomla! Version Joomla! 3.4.0 Stable [ Ember ] 24-February-2015 23:00 GMT
> Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ]
> 24-Apr-2013 00:00 GMT
> User Agent Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/40.0.2214.115 Safari/537.36
> Additional comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6209>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by greenlizzard24** [comment]
Hi 
System cache is not turned on, and the plugin is not enabled

**Comment by brianteeman** [comment]
> what are the cache settings in global configuration

And did this happen when the page loaded or after you pressed delete?

On 27 February 2015 at 10:28, greenlizzard24 <notifications@github.com>
wrote:

> Hi
> System cache is not turned on, and the plugin is not enabled
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6209#issuecomment-76372262>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by greenlizzard24** [comment]
it happened when the page loaded, I never got to see the cache files, iot was just a blank page

**Comment by brianteeman** [comment]
what are the cache settings in global configuration

**Comment by greenlizzard24** [comment]
cache setting are disabled in the system settings and plugin is also disabled

**Comment by brianteeman** [comment]
Reset priority according to standard https://docs.joomla.org/Bug_and_Issue_Tracker_Priority
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6209">issues.joomla.org/joomla-cms/6209</a>.</sub>

**Comment by brianteeman** [comment]
@greenlizzard24 are you still having this issue? It is odd because we have had no other reports <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6209">issues.joomla.org/joomla-cms/6209</a>.</sub>

**Comment by greenlizzard24** [comment]
Hi Brian,
I have sorted it out it was only on that one installation, it looks as though the file was may have been corrupted from 3.3.6, so I re-installed the said file from a 3.3.6 installation then re-installed 3.4 and now everything works fine. All other upgrades have been smooth sailing. Thank you for all your help all the same.

Regards
Gerald

**Comment by paceit** [comment]
Hi, I am also experiencing this problem and finding it hard to resolve! Sometimes the home page blanks, and other times the menu links lead to a blank page.  Clearing all the cache always fixes it (temporarily).  This started from J 3.3.X I believe. I have progressively upgraded to 3.6.2 to try to clear it. I also went through all components, modules, plugins to ensure I am on latest releases.  Previously it was happening multiple times per day, now it worked fine for about a week, and then started again.  I had Progressive caching on, and cache_lite, but now have switched off caching. Any suggestions where else to look?

**Comment by ggppdk** [comment]
You have PHP 5.x ? right

white page means a fatal error
- without the actual error we do not know if this a Joomla bug **or 3rd party extension that is failing**, (or server software bogus ?)

How to find the reason for this:
- Search through the apache log (ask your web-host where this is located), and look at the time that you had blank page, and you will find the error
- also if you do not mind the errors showing at frontend (temporarily), then you can **temporarily enable "Error reporting"** at Joomla Global config and then after finding the error message disable it again (set to system default)

it may be better to set error reporting to "Maximum" instead of "Simple",
because before the PHP fatal error you may get a related PHP notices / warnings
