### ISSUE TITLE
bug in languagefilter plugin in jommla 3.4

### ISSUE THREAD

**Issue by fcocquit** [joomla/joomla-cms#6211]
#### Steps to reproduce the issue
after upgrading to 3.4 i get issues in the language filter plugin:
Notice: Trying to get property of non-object in C:\xampp\htdocs\mywebsite\plugins\system\languagefilter\languagefilter.php on line 172

Notice: Undefined index: nl-NL in C:\xampp\htdocs\mywebsite\plugins\system\languagefilter\languagefilter.php on line 620

Notice: Trying to get property of non-object in C:\xampp\htdocs\mywebsite\plugins\system\languagefilter\languagefilter.php on line 172

#### Actual result

Disabling the plugin makes the website work (although no language filter is applied of course)

#### System information (as much as possible)
windows 8.1, xamppconfiguration (but same issues on the live website - had to downgrade again

**Comment by infograf768** [comment]
Re-save all your Content Languages.
see:
https://github.com/joomla/joomla-cms/pull/6194
and
https://github.com/joomla/joomla-cms/pull/6195

**Comment by roland-d** [comment]
Closing this report as it has been resolved in #6194.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6211">issues.joomla.org/joomla-cms/6211</a>.</sub>
