### ISSUE TITLE
Plugin Recaptcha and Mootools on Joomla 3.4

### ISSUE THREAD

**Issue by Qlimax90** [joomla/joomla-cms#6212]
Hi everyone,

in /plugins/captcha/recaptcha/recaptcha.php from line 55 to 79, is there any reason why the new recaptcha is loading the mootools library? Especially on line 76 Mootools gets loaded by JHtml::_('script', $file, true, true);

I think the following code would be better:

switch ($version)
		{
			case '1.0':
				$theme = $this->params->get('theme', 'clean');

				$file = $app->isSSLConnection() ? 'https' : 'http';
				$file .= '://www.google.com/recaptcha/api/js/recaptcha_ajax.js';
				$document->addScriptDeclaration('jQuery( document ).ready(function()
				{
					Recaptcha.create("' . $pubkey . '", "' . $id . '", {theme: "' . $theme . '",' . $lang . 'tabindex: 0});});'
				);
				break;
			case '2.0':
				$theme = $this->params->get('theme2', 'light');

				$file = $app->isSSLConnection() ? 'https' : 'http';
				$file .= '://www.google.com/recaptcha/api.js?hl=' . JFactory::getLanguage()
						->getTag() . '&onload=onloadCallback&render=explicit';
				
				$document->addScriptDeclaration('var onloadCallback = function() {'
					. 'grecaptcha.render("' . $id . '", {sitekey: "' . $pubkey . '", theme: "' . $theme . '"});'
					. '}'
				);
				break;
		}
		$document->addScript($file);

Best regards

**Comment by zero-24** [comment]
@Qlimax90 can you submit the changes as PR?

If you need help or don't know how you can have a look here: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6212">issues.joomla.org/joomla-cms/6212</a>.</sub>

**Comment by brianteeman** [comment]
Closing as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6212">issues.joomla.org/joomla-cms/6212</a>.</sub>
