### ISSUE TITLE
problem menu Protostar 3.4.0

### ISSUE THREAD

**Issue by adriaan6** [joomla/joomla-cms#6221]
Dear Sir/Madam,

I have upgrade my Joomla version to: 3.4.0 and now i have a problem with my Protostar template.. The menu is not correctly displayed.

Can someone tells me what's going wrong and what i must change to solve this problem? without restoring a back-up.

www.bredero-backup.com/site2

I looking forward to hear from you, thanks and have a nice day!

Regards,

Adriaan

**Comment by losedk** [comment]
You need to remove span3 from ```<div class="well _menu span3">```

**Comment by adriaan6** [comment]
Dear "losedk" thanks! in which file i must remote this?

**Comment by losedk** [comment]
@adriaan6 I think you can fix it in the menu module in the backend

**Comment by adriaan6** [comment]
@losedk thanks!. I have found the option in the backend to change it to: "well" or "no", I have selected no, instead of well. But the menu is now different of the Original menu.

Is theire any option to get the look/feel from the "old" menu back?

**Comment by losedk** [comment]
@adriaan6 Just use well. Are you seeing span3 anywhere in the module settings?

**Comment by Hils** [comment]
the padding/margin round the image doesn't look right either (particularly padding-right) but I am nor sure whether that is default or not.

**Comment by adriaan6** [comment]
nope i don't see span 3.. must i look inside the FTP in the files?

Maybe i can send you my login details, so you can look in the Joomla panel? i use the English language of Joomla.. but don't know where i must look to change the right one so the lay-out is the same as before the upgrade.. i have another site, but upgrade this site at the moment i know what i must change in Joomla so the menu works correctly (and is displayed correctly) thanks for your help at this moment!

**Comment by Siliconheart** [comment]
To remove span<number> from modules go to advanced tab in Module settings and set 'Bootstrap Size' to 0. That worked for me. [More info here](http://blog.ngel.ru/2015/03/joomla-strikes-again-340-and-protostar.html "More info here.")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6221">issues.joomla.org/joomla-cms/6221</a>.</sub>

**Comment by adriaan6** [comment]
Dear @Siliconheart perfect!! it works:-) thanks!!

**Comment by Siliconheart** [comment]
Glad to help! Does the issue need to be closed now?

**Comment by adriaan6** [comment]
yep, it can be closed! thanks:)

**Comment by vickiB** [comment]
1-Latest Article, 2-User Menu and 3-Login Form by default are assigned position 7 on the protostar template.  When I upgraded from 3.3 to 3.4 those 3 modules were collapsed together.  Siliconheart's solution worked for me.  In my site administrator I used System, Control Panel, Module Manager to edit each of the latest article and user menu modules and used the advanced tab and set the Bootstrap Size to 0 - Bootstrap Size was defaulting to 1.  After I saved those changes the right panel correctly displayed those three modules.  I also changed the Image Module in (position 3) using the advanced tab I set Bootstrap Size to 0 it had been 1.  Now the image banner is back to the same size it was prior to the upgrade.   Thank you so much Siliconheart!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6221">issues.joomla.org/joomla-cms/6221</a>.</sub>

**Comment by sagarapawar** [comment]
i have same problem after update to 3.4 joomla my site manu position change
pls help
my site:- http://sandeepbhargava.com/#home <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6221">issues.joomla.org/joomla-cms/6221</a>.</sub>

**Comment by Bakual** [comment]
The collapsed modules are indeed a feature which was not working for some module chromes. THat has been fixed in Joomla 3.4. The default value for the Bootstrap parameter is 0. If it's botched after the update it means you probably played around with the settings once, and since it didn't have any effect you left it on another value. With the update it now has an effect and will make your module look ugly.
On the other hand, it allows for very powerfull things. You can have multiple modules in the same place and specify the width of each indivually using that parameter.
