### ISSUE TITLE
Recaptcha plugin throws "Undefined variable: challenge"

### ISSUE THREAD

**Issue by thekrotek** [joomla/joomla-cms#6227]
#### Steps to reproduce the issue

Just use recaptcha plugin with version 2.0 and error reporting on maximum. Or try to submit rcaptcha using AJAX.

#### Expected result

Successfully submitted form.

#### Actual result

I submit form using AJAX and due to this error I akways get the same response:

Notice:  Undefined variable: challenge in /mysite/plugins/captcha/recaptcha/recaptcha.php on line 158

This message will also pop, when error reporting is set to maximum.

#### System information (as much as possible)

Joomla 3.4, custom form.

#### Additional comments

Fix is very simple: $challenge variable should be defined any possible way. For example, you may add this line for version 2.0:

$challenge = $input->get('g-recaptcha-response', '', 'string');

**Comment by brianteeman** [comment]
As you have identified an issue and a solution please can you submit a Pull Request so that it can be tested and merged.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6227">issues.joomla.org/joomla-cms/6227</a>.</sub>

**Comment by thekrotek** [comment]
You mean Github? Honestly, I never did a single pull request in my life and not sure, how to properly do this...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6227">issues.joomla.org/joomla-cms/6227</a>.</sub>

**Comment by brianteeman** [comment]
It is very simple especially for a single file change
https://docs.joomla.org/Filing_bugs_and_issues#Issue_a_pull_request_directly_on_Joomla.21.27s_GitHub_repository

As a developer you really should find it very easy indeed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6227">issues.joomla.org/joomla-cms/6227</a>.</sub>

**Comment by Bakual** [comment]
Simplest way (I think)  is explained here: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by PhilETaylor** [comment]
Confused, as the proposed line is already in the Joomla source code:

https://github.com/joomla/joomla-cms/blob/staging/plugins/captcha/recaptcha/recaptcha.php#L129

**Comment by PhilETaylor** [comment]
Can you provide more information, maybe an example of the "custom form" you are using? I think this might be a non-joomla issue and more a custom implementation issue...

**Comment by PhilETaylor** [comment]
Ah I get it now... PR #6235 ready for testing

**Comment by thekrotek** [comment]
Thank you! Will try to create PR next time :-)
