### ISSUE TITLE
Recaptcha plugin $code variable is obsolete

### ISSUE THREAD

**Issue by thekrotek** [joomla/joomla-cms#6228]
#### Steps to reproduce the issue

Use recaptcha plugin and do not define $code for 'onCheckAnswer' event.

#### Expected result

Successfully submitted form.

#### Actual result

Throws an error:

Warning:  Missing argument 1 for PlgCaptchaRecaptcha::onCheckAnswer() in /mysite/plugins/captcha/recaptcha/recaptcha.php on line 114

#### System information (as much as possible)

Joomla 3.4, custom form.

#### Additional comments

Fix is very simple: remove $code variable from onCheckAnswer() function definition. It's obsolete and never used.

**Comment by brianteeman** [comment]
As you have identified an issue and a solution please can you submit a Pull Request so that it can be tested and merged.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6228">issues.joomla.org/joomla-cms/6228</a>.</sub>

**Comment by mbabker** [comment]
How are you triggering the event?  In [JCaptcha::checkAnswer()](https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/captcha/captcha.php#L187) the code variable is defined before calling the plugin event.

Yes, the variable is not used in this plugin, however it appears that the base API expects to use it (perhaps with other captcha providers).

**Comment by thekrotek** [comment]
I'm using the standard $dispatcher->trigger('onCheckAnswer', '') line. I understand the backwards compatibility with other captcha plugins, but at least $code variable can be optional:

public function checkAnswer($code = '')

That was my initial point.

**Comment by PhilETaylor** [comment]
|This code is cleaned up in my other PR https://github.com/joomla/joomla-cms/pull/6235/files#L114

**Comment by zero-24** [comment]
Closing as we have a PR by @PhilETaylor https://github.com/joomla/joomla-cms/pull/6235<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6228">issues.joomla.org/joomla-cms/6228</a>.</sub>

**Comment by PhilETaylor** [comment]
The PR is now clean and ready for testing/merging
