### ISSUE TITLE
Problem loading front page after updating to 3.4

### ISSUE THREAD

**Issue by maofree** [joomla/joomla-cms#6239]
Hi
after updating from 3.3.6 to 3.4 I can't see the front page. The back-office is ok. I can see that the url is not right, with url-friendly enabled at the end there are two slash, instead without there is a question mark after index.php. it is the first time that I get this type of error with joomla.
I've disabled cache, url-friendy, gzip compression, enabled maximum error log, removed .htaccess, removed robot.txt, clean browser cache, clean joomla cache, reboot my local server, tried with different browsers, changed to a default joomla theme. The front page gives the same error.
I don't think it dipends on some version of my debian scrips, because it is the last and the control panel works well.
thanks
bye

![1111](https://cloud.githubusercontent.com/assets/653230/6430172/13218dde-bfff-11e4-96ed-6f112f23bd75.png)
![2222](https://cloud.githubusercontent.com/assets/653230/6430173/133f97d4-bfff-11e4-871b-36f4f7b91bc0.png)

**Comment by wilsonge** [comment]
Are you running multilingual site?

**Comment by maofree** [comment]
yes

**Comment by maofree** [comment]
yes I think it is due from "System - Language Filter",  disabling it I can see the hidden article

**Comment by Hackwar** [comment]
http://forum.joomla.org/viewtopic.php?f=707&t=874568&sid=e14b233ddfdfe5ca6820e3f742fd4d39&p=3271069#p3270983<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6239">issues.joomla.org/joomla-cms/6239</a>.</sub>

**Comment by maofree** [comment]
thanks Hackwar
yes that suggestion solve this issue

bye
