### ISSUE TITLE
Change code in view default_address.php com_contact

### ISSUE THREAD

**Issue by Pinkeltje** [joomla/joomla-cms#6240]
Contact address is a textarea, so expected behaviour should be that line breaks are allowed. Core view places all information in one line.
Think it would be an improvement to change line 31 from:
`<?php echo $this->contact->address .'<br/>'; ?>`
to
`<?php echo nl2br($this->contact->address) .'<br/>'; ?>`

**Comment by PhilETaylor** [comment]
PR now attached #6243

**Comment by Pinkeltje** [comment]
Thx!
