### ISSUE TITLE
Create contact menu item if there is only one SuperUser 3.4.0 dev

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-cms#6245]
Creating a menu item to a contact form - single user. This site only has one user - the original SuperUser. This is the person I want to be the contact. But the SuperUser doesn't show in the selection box so unable to chose him/her.
![single-contact](https://cloud.githubusercontent.com/assets/736887/6430432/b22a16b0-c001-11e4-87d6-e67ff70af0cd.png)

Is this expected behavior please?

(To recreate on a site with no users except the original SuperUser - go to Menu >>new menu item>> and create a new one -  'contact form, single user' and try and choose the SuperUser as the contact. )

**Comment by losedk** [comment]
Can't reproduce this

![skaermbillede 2015-03-01 kl 12 14 36](https://cloud.githubusercontent.com/assets/1738811/6430502/8da03a58-c00c-11e4-9b99-cc4e0b35ffa5.png)

**Comment by Hils** [comment]
So is there more info you need me to add? Please elaborate.

**Comment by PhilETaylor** [comment]
Have you first created the Contact and linked the Contact to the User in the Contacts Extension BEFORE attempting to create a Menu link to the Contact ?

(oh how Joomla makes life complex....)

Steps:

1) Extensions -> Contacts -> Contacts
2) New 
3) Name it - select a linked user 
4) save and close
5) Menus -> main Menu
6) New -> Menu Item Type: Select -> Contacts ->Single Contact -> Select Contact : Select 
7) Then you will see the contact ready to be linked to

Power in Simplicity....

Nothing to fix. No Issue apart from understanding.

**Comment by Hils** [comment]
Phil - thank you! I was only trying to set up a quick contact so I could test one of your PRs. Much appreciate your kind answer. I need to remember that 3.4 is still Joomla and not some alien CMS I just met ;)

**Comment by PhilETaylor** [comment]
Can you confirm that after doing the above steps the initial reported issue is resolved and this github issue can be closed please?

**Comment by Hils** [comment]
will do shortly :)

**Comment by Hils** [comment]
Confirm except it is Components>>Contacts rather than Extensions>>Contacts. Closing now. Thanks again.

**Comment by PhilETaylor** [comment]
Components and Extensions... whats the difference... they are all plugins ... :-) :-) #PowerInSimplicityLost.

**Comment by Hils** [comment]
Ha! No issue to me but it could be an issue when directing someone where to find something ;)
