### ISSUE TITLE
Articles - Archived modules does not group by month

### ISSUE THREAD

**Issue by wolm** [joomla/joomla-cms#6246]
#### Steps to reproduce the issue
Place a standard Articles - Archive module, set it to show 10 months

#### Expected result
List of 10 year/month Links to the archive component

#### Actual result
List of 10 links to february 2015.

#### System information (as much as possible)
Joomla 3.4.0
MySQL 5.6.21

#### Additional comments
Seems to be a problem in modules/mod_articles_archive/helper.php

The query has been changed from

		$query->select($query->month($db->quoteName('created')) . ' AS created_month')
			->select('created, id, title')
			->select($query->year($db->quoteName('created')) . ' AS created_year')
			->from('#__content')
			->where('state = 2 AND checked_out = 0')
			->group('created_year DESC, created_month DESC');

to

		$query->select($query->month($db->quoteName('created')) . ' AS created_month')
			->select('created, id, title')
			->select($query->year($db->quoteName('created')) . ' AS created_year')
			->from('#__content')
			->where('state = 2 AND checked_out = 0')
			->group('created_year, created_month, created, id, title')
			->order('created_year DESC, created_month DESC');

**Comment by Erftralle** [comment]
Confirmed. Opened pull request #6263.

**Comment by zero-24** [comment]
Closing as we have a PR Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6246">issues.joomla.org/joomla-cms/6246</a>.</sub>
