### ISSUE TITLE
Joomla 3.4 update corrupts protostar websites

### ISSUE THREAD

**Issue by DiGwork** [joomla/joomla-cms#6255]
Hi I administer quite a few websites. This weekend I updated  two of them to Joomla 3.4 and found exsactly the same issue in both. They both run the Protostar template on frontend. I have an image module in possition 3 and in both sites this image in the module has been squished to the left side of the website! I won't be updating any of the other sites until I can find a solution to this issue!

**Comment by losedk** [comment]
Could you provide some more info? Perhaps a link or some screenshots

**Comment by DiGwork** [comment]
![selection_049](https://cloud.githubusercontent.com/assets/6685896/6440765/191f0a14-c0e9-11e4-8b8c-4e497aa91820.png)

**Comment by DiGwork** [comment]
Hi Losedk the URL is: http://DiGwork.com

**Comment by DiGwork** [comment]
I have used another position for the other site for now as it is a client site

**Comment by losedk** [comment]
Go to your module > Advanced > Module Class Suffix > and remove span1

**Comment by DiGwork** [comment]
Do you mean Bootstrap? as there is no in Module Class suffix it is empty?

**Comment by losedk** [comment]
could you take a screenshot of the settings?

**Comment by DiGwork** [comment]
![selection_050](https://cloud.githubusercontent.com/assets/6685896/6440898/a1fe4b8c-c0ea-11e4-957b-2891c1445a8e.png)

**Comment by losedk** [comment]
Yeah, just change the bootstrap size to 0

**Comment by DiGwork** [comment]
Yeah that solved it thanks a mill. Do you know of any other issues I might still incure as I upload other sites?

**Comment by losedk** [comment]
You're welcome! 

You shouldn't experience any issues when upgrading to 3.4

**Comment by DiGwork** [comment]
;) Thanks for the help Peter

**Comment by losedk** [comment]
No problem. Could you close the issue again?

**Comment by brianteeman** [comment]
Closed as requested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6255">issues.joomla.org/joomla-cms/6255</a>.</sub>

**Comment by N6REJ** [comment]
I ran into the same issue on several modules, opening, saving, fixes the 
issue for me
Bear
