### ISSUE TITLE
Postgresql: Add user note gives an error

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#6262]
Try to add a user note. When hitting the save button you get an error due to a violation of a not-null-constraint in column "modified_user_id".

**Comment by brianteeman** [comment]
Closing as we have a PR #6265 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6262">issues.joomla.org/joomla-cms/6262</a>.</sub>
