### ISSUE TITLE
emailadres with .xx not allowed, .xxx is allowed at registration through remote database

### ISSUE THREAD

**Issue by peanuts68** [joomla/joomla-cms#6271]
#### Steps to reproduce the issue
I built a plugin for external authentication. Visitors supply a membershipnumber and password, than an external database provides fullname, username and emailadress to the plugin, than users are registered through the standard Joomla procedure. 
When the provided emailadress contains .xx, registration breaks. When the emailadress contains .xxx, registration is allowed. 
Adding a 'x' to the .xx mailadress in the authentication plugin resolves the issue, but leaves me with unusable mailadresses. As soon as I strip the x off again, registration breaks again.
#### Expected result
Mailaccounts with .xx should be usable as well for registration through external authentication (the field validation is not used).

#### Actual result
Email with .xx breaks registration.

#### System information (as much as possible)
Joomla 3.3.6 (can't upgrade to 3.4 because of extensions that are not compatible)
PHP version 	5.3.26
Webserver 	Apache/2.2.24 (Unix) DAV/2 PHP/5.3.26 mod_ssl/2.2.24 OpenSSL/0.9.8y
WebServer 	apache2handler
Joomla!         3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT

**Comment by brianteeman** [comment]
Please create a test site with 3.4 without your extensions that are not
compatible (weird)

If you can then confirm that you still have the issue in 3.4 it can be
investigated. If it is only an issue in 3.3.6 then sorry but you will have
to update

On 3 March 2015 at 09:19, peanuts68 <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> I built a plugin for external authentication. Visitors supply a
> membershipnumber and password, than an external database provides fullname,
> username and emailadress to the plugin, than users are registered through
> the standard Joomla procedure.
> When the provided emailadress contains .xx, registration breaks. When the
> emailadress contains .xxx, registration is allowed.
> Adding a 'x' to the .xx mailadress in the authentication plugin resolves
> the issue, but leaves me with unusable mailadresses. As soon as I strip the
> x off again, registration breaks again.
> Expected result
>
> Mailaccounts with .xx should be usable as well for registration through
> external authentication (the field validation is not used).
> Actual result
>
> Email with .xx breaks registration.
> System information (as much as possible)
>
> Joomla 3.3.6 (can't upgrade to 3.4 because of extensions that are not
> compatible)
> PHP version 5.3.26
> Webserver Apache/2.2.24 (Unix) DAV/2 PHP/5.3.26 mod_ssl/2.2.24
> OpenSSL/0.9.8y
> WebServer apache2handler
> Joomla! 3.3.6 Stable [ Ember ] 01-October-2014 02:00 GMT
> Additional comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6271>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Reset priority according to standard https://docs.joomla.org/Bug_and_Issue_Tracker_Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6271">issues.joomla.org/joomla-cms/6271</a>.</sub>

**Comment by peanuts68** [comment]
Hello Brian, thanks for your quick reply, I just stumbled on another issue, I think it might be related.
See [this issue on validation](https://github.com/joomla/joomla-cms/pull/4899 "email validation")
I'll try to upgrade and see if this fixes it. 
Next time when testing, perhaps use two letter extensions as well : ) I saw the team has thouroughly tested all kinds of adresses, but accidentily none with .xx. Many thanks to the team for their efforts. I'll keep you posted.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6271">issues.joomla.org/joomla-cms/6271</a>.</sub>

**Comment by brianteeman** [comment]
I personally tested .xx on 3.4 just now with no problem

**Comment by peanuts68** [comment]
Mmm, no luck. I upgraded to 3.4.0, issue still remains the same. When I try to register with .xx the registration breaks. When I try to register with a .com adress, the registration works fine. 
Don't know where to look to fix this myself. I found several reg-expressions for validation, but they are all used for forms. Somewhere their is a helper or a part of the Usercomponent that seems to be using a different validation.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6271">issues.joomla.org/joomla-cms/6271</a>.</sub>

**Comment by peanuts68** [comment]
Small addition: a .xx adress in the external database breaks registration. A .xxx adress in the external database works fine, than i can register. Using the registration form is not a problem for .xx users, the form is ok. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6271">issues.joomla.org/joomla-cms/6271</a>.</sub>

**Comment by peanuts68** [comment]
Did a test on an older Joomla 2.5 site, doesn't work their either. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6271">issues.joomla.org/joomla-cms/6271</a>.</sub>

**Comment by peanuts68** [comment]
Tested the regex, on http://www.regexr.com/, the regex posted in the other topic works fine for .xx, so thats not the isssue. Also tested if the gmail-authentication-plugin works with my site. That works too (but gmail uses .xxx so no surprise there).

**Comment by peanuts68** [comment]
Did another test. Modified the gmail-plugin to this:
	$emailadres = (string) $email;
	//strip off the m 
	$postadres = str_replace("m", "", $emailadres);
	$response->email         = $postadres;
This allows me to register with blabla@gail.co, instead of blabla@gmail.com.
Have to think about what this means. Any pointers?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6271">issues.joomla.org/joomla-cms/6271</a>.</sub>

**Comment by peanuts68** [comment]
Problem solved, was not a Joomla bug after all. The database passed an extra record which was 'stuck' to the emailadres for .xx visitors, making their adress too long for validation. I didn't know this extra record was added. 
You can erase my question/bugreport. Thanks for the efforts of the Joomla team and bug-squad anyhow.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6271">issues.joomla.org/joomla-cms/6271</a>.</sub>
