### ISSUE TITLE
Template assignment broken in 3.4

### ISSUE THREAD

**Issue by weeblr-dev** [joomla/joomla-cms#6272]
#### Steps to reproduce the issue
Try to perform menu item assignment from a template style edit page, using the Menus assignment tab. You get a javascript error when trying to use the toggle buttons: $$ is not a function.
IMPORTANT: this will not happen with Joomla default template (ie Beez), though the problem is indeed in Joomal and not in external templates

#### Expected result
Working assignment

#### Actual result
Javascript error

#### System information (as much as possible)
Joomla 3.4

#### Additional comments
Looks like mootools is needed in /administrator/components/com_teplates/views/style/tmpl/edit_assignement.php. However, it is not explicitely loaded by com_templates, which leads to the error.
This problem is hidden in Joomla! default templates because both of them have a "media" field in their params, which requires mootools and does load it. However, any template that doesn't have such a field will fail (I'm using Yootheme's yoo_katana for instance). Again, this has nothing to do with the templates themselves.

**Comment by brianteeman** [comment]
Confirmed with a really basic template that has no fields at all<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6272">issues.joomla.org/joomla-cms/6272</a>.</sub>

**Comment by dgt41** [comment]
@brianteeman can you close this?  The respected pr with the fix was already merged for 3.4.1

**Comment by zero-24** [comment]
Closing thanks @dgt41 for the fix.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6272">issues.joomla.org/joomla-cms/6272</a>.</sub>
