### ISSUE TITLE
updating extensions notification problem

### ISSUE THREAD

**Issue by peteruoi** [joomla/joomla-cms#6279]
#### Steps to reproduce the issue
check joomla backend dashboard. 
"All extensions are up to date"

Extension->Extension Manager->update->Find updates

#### Expected result
mod roksprocket new version 2.1.3

#### Actual result

There are no updates available at the moment. Please check again later. 

#### Additional comments

I have 4 3.3.6 joomla sites in a unmanaged vps with ispconfig. So server settings (php-mysql) is the same for all of them. In one of them however the joomla updater found the new version of roksprocket. The other three sites dont fint it no matter how many times i press find updates. It's really odd so if someone has any idea what to do to find the bug is more than welcome:)

**Comment by mbabker** [comment]
Since you're still on 3.3.6, I'd suggest checking the `#__update_sites` database table to make sure all update sites are enabled (in 3.4, you can do this directly in the Extension Manager).

**Comment by brianteeman** [comment]
This is almost certainly an issue with an update server being disabled
inside that one site. This has been resolved in Joomla 3.4 with a new
option to check this.

Please upgrade to 3.4 and check

On 3 March 2015 at 15:22, peteruoi <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> check joomla backend dashboard.
> "All extensions are up to date"
>
> Extension->Extension Manager->update->Find updates
> Expected result
>
> mod roksprocket new version 2.1.3
> Actual result
>
> There are no updates available at the moment. Please check again later.
> System information (as much as possible) Additional comments
>
> I have 4 3.3.6 joomla sites in a unmanaged vps with ispconfig. So server
> settings (php-mysql) is the same for all of them. In one of them however
> the joomla updater found the new version of roksprocket. The other three
> sites dont fint it no matter how many times i press find updates. It's
> really odd so if someone has any idea what to do to find the bug is more
> than welcome:)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6279>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
I am marking this information based ont he advice from @mbabker above and the recommendation to upgrade to 3.4

If this does or does not work please report back <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6279">issues.joomla.org/joomla-cms/6279</a>.</sub>

**Comment by peteruoi** [comment]
updating to joomla 3.4 and going to updates sites. Then enabling the disabled sites solved the issue :) 
Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6279">issues.joomla.org/joomla-cms/6279</a>.</sub>

**Comment by zero-24** [comment]
Closing thanks for the update here!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6279">issues.joomla.org/joomla-cms/6279</a>.</sub>
