### ISSUE TITLE
Db Error in sample_learn.sql

### ISSUE THREAD

**Issue by DanGthatRokGallery** [joomla/joomla-cms#6281]
#### Steps to reproduce the issue
Open Joomla_3.4.0-Stable-Full_Package.zip\installation\sql\mysql\sample_learn.sql
In the "#__assets" you have:

(172, 96, 178, 179, 7, 'com_content.article.70', 'Smart Search', '{"core.delete":[],"core.edit":[],"core.edit.state":[]}'),

Whereas in the "#__content" Table you have:
(70, 170, 'Smart Search', 'smart-search', '<p>This module provides search using the Smart Search component. You should only use it if you have indexed your content and either have enabled the Smart Search content plugin or are keeping the index of your site updated manually. <a href="https://help.joomla.org/proxy/index.php?option=com_help&amp;amp;keyref=Help31:Extensions_Module_Manager_Smart_Search">Help</a>.</p><div class="sample-module">{loadmodule finder,Smart Search}</div>', '', 1, 67, '2011-01-01 00:00:01', 123, 'Joomla', '0000-00-00 00:00:00', 0, 0, '0000-00-00 00:00:00', '2012-01-17 03:42:36', '0000-00-00 00:00:00', 

#### Expected result
Matching item ID's

#### Actual result
Mismatched ID's with match 172 and 170

So there is a conflict with "#__assets"

(170, 50, 217, 218, 6, 'com_content.article.68', 'Captcha', '{"core.delete":[],"core.edit":[],"core.edit.state":[]}'),

#### System information (as much as possible)
Fresh download and install of Joomla_3.4.0-Stable-Full_Package.zip
Local MAMP for WINDOWS - PHP 5.6.3 - Joomla 3.4

**Comment by brianteeman** [comment]
Thank you for reporting this - sorry no one replied for so long.

We are aware that there are a few issues like this in the sample data. The method of creating and managing sample data is being completely changed to prevent issues like this so I am closing this at this time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6281">issues.joomla.org/joomla-cms/6281</a>.</sub>
