### ISSUE TITLE
[tests] Find a solution for read System Messages from System Tests

### ISSUE THREAD

**Issue by javigomez** [joomla/joomla-cms#6285]
Currently the markup for messages in administrator looks like:

```html
<div class="alert alert-success">
	<h4 class="alert-heading">Message</h4>
	<p>Configuration successfully saved.</p>
</div>
```

![screen shot 2015-03-03 at 19 34 44](https://cloud.githubusercontent.com/assets/1375475/6469328/c1d56e30-c1db-11e4-9649-c17cd91c9c46.png)

There is no easy way with Codeception and Selenium to place a locator for the message in the assertion:

```php
$I->see('Configuration successfully saved.' );
// $I->waitForText('Configuration successfully saved.', 10, '.page-title');
// $I->see('Configuration successfully saved.','h3');
// $I->see('Configuration successfully saved.','#messages'); // with XPath
// $I->see('Configuration successfully saved.','.message'); // with XPath
```

We could probably add a css class to the messages because missing a xPath locator affects dramatically the performance of the test (see: https://docs.joomla.org/Testing_Joomla_Extensions_with_Codeception#Always_add_xPath_locators_to_your_tests)

**Comment by mbabker** [comment]
I'm just guessing since I know nothing about Codeception, can you use the `system-message-container` div ID that the messages are wrapped in?  You should have something like this for the full container:

```html
<div id="system-message-container">
	<button type="button" class="close" data-dismiss="alert">&times;</button>
	<div class="alert alert-success">
		<h4 class="alert-heading">Message</h4>
		<p>Configuration successfully saved.</p>
	</div>
</div>
```

Then you should be able to do some sort of an advanced xpath using `div#system-message-container div.alert-success p`

**Comment by javigomez** [comment]
Thanks Michael. Yup! you are right. That option is always there but the idea is that with a few tweaks in the Template (for example using more IDs properly) we can make the work of creating the system test much easier.

I plan to create several issues like this so we can review all them afterwards when we consider reviewing the admin template for 3.5

**Comment by javigomez** [comment]
It will also make the logs look nicer, in the following example some elements are easily localizable and don't need XPath and some do (the XPath ones look not that cool):

![screen shot 2015-03-03 at 20 26 34](https://cloud.githubusercontent.com/assets/1375475/6470292/00d99bb8-c1e3-11e4-83ce-79fc4fa998d7.png)

**Comment by pbwebdev** [comment]
Not 100% sure but it might be worth adding in an alert tag as well
https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_alert_role

**Comment by zero-24** [comment]
Closing as we have a RTC PR here: https://github.com/joomla/joomla-cms/pull/7070<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6285">issues.joomla.org/joomla-cms/6285</a>.</sub>
