### ISSUE TITLE
Articles - Newsflash doesn't use custom 'Read more' text

### ISSUE THREAD

**Issue by tovac** [joomla/joomla-cms#6287]
#### Steps to reproduce the issue
1. Create an article and add a 'Read more'-Link into the content of the article.
2. Put a custom Read More Text at the option-panel of the article
3. Create a Newsflash module with the category of the created article and put it to a visible position at the page
4. Click "show" at the 'Read more ...' Link in the options of the newsflash module

#### Expected result
The custom 'Read more' Text is shown at the 'Read more'-Button

#### Actual result
The standard 'Read more' Text ('Read more') is shown at the 'Read more'-Button

#### System information (as much as possible)
Joomla 3.4.0
PHP 5.5.17

#### Additional comments
Have a look to
http://forum.joomla.org/viewtopic.php?f=708&t=796643

**Comment by bertmert** [comment]
It's easy to establish this behaviour inside a custom module override.
See mod_articles_category/tmpl/default.php line 59 ff as an example.

Because of backwards compatibility it would be necessary to introduce a new option/parameter for mod_articles_news. Something like "Use alternative readmore". Default value: no.

You have to customize helper.php, manifest xml and default.php. Is it worth the effort?

(Be aware, that the linked forum post is bad bad code, not just because it's a core hack.)

**Comment by houbahoubi** [comment]
Hello
Sorry to disturb you on this topic but I don't know where I can post bugs ?
The readmore link with a link to register doesn't work on the newsflash module on Jommla 3.4.1. 
Here is my topic to understand more :
http://forum.joomla.org/viewtopic.php?f=706&t=884342
thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6287">issues.joomla.org/joomla-cms/6287</a>.</sub>

**Comment by bertmert** [comment]
> I don't know where I can post bugs

Click green button *New Issue*!

**Comment by houbahoubi** [comment]
Sorry I don't see a green button "New issue" ;-(

So Yes of course thanks for your help ! I try to explain, I am french and I hope you can follow my translations ;-)

In "content" > "Article manager" click on "options". In article tab, select "yes" for "Show Unauthorised Links" and save.
Choose an article, and select an "enregistered access" for it. That's all if I well remember.
Now if you are not login in the fronted you can see a link readmore like that "please register to read more".
Then try to click on this link from an article in a blog area and do the same from the module newsflash.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6287">issues.joomla.org/joomla-cms/6287</a>.</sub>

**Comment by bertmert** [comment]
![new-issue](https://cloud.githubusercontent.com/assets/11038612/7402730/31cd6812-eecf-11e4-8372-c300d2cc962a.jpg)

**Comment by mbabker** [comment]
If you're coming from issues.joomla.org as @houbahoubi is then you need to be on the tracker list view (which is the site's homepage or what you get when clicking the "Tracker" button in the menu) then you'll see a green "New Item" button.  The UI there is also translated to help our non-native English speakers get around.

**Comment by bertmert** [comment]
@mbabker Thank you for explanation.

@houbahoubi Sorry for confusing you (and me ;-) !!

We don't need a new issue because I've already created a PR. Please test it. https://github.com/joomla/joomla-cms/pull/6864

**Comment by houbahoubi** [comment]
@mbabker yes my comment was wrote here : http://issues.joomla.org so no new button here. I understand but it's perturbing because we don't know that we need to go on Github. I am not a developper so I am not familiar on this platform and how to use it.

@bertmert not a problem ;-)

**Comment by zero-24** [comment]
As we have a PR that fixes the issue i'm closing here :smile: #6864 is the PR by @bertmert Thanks!
