### ISSUE TITLE
Edit Article Column Tooltip inserts br tag instead of parsing them

### ISSUE THREAD

**Issue by Josh-Lewis** [joomla/joomla-cms#6288]
**Producing the Issue:**

Attached to this tracker is a screen shot showing a tooltip displaying a BR tag instead of actually breaking a line.

![screen shot 2015-03-03 at 18 23 01](http://issues.joomla.org/uploads/1/625eb2603393e69b9376f14b92782550.png)

To produce this create an article list (category list) menu item and set the display to show the edit column. Set the site template to Protostar. Login on the frontend. View the article list and hover over one of the edit icons in the list.

**Expected Result:**

One would expect the br tags to render and display author/page information on separate lines. On other templates the br tags also display.

**Comment by Erftralle** [comment]
I think this issue has already been solved with pull request #6226.

**Comment by Josh-Lewis** [comment]
I actually looked for that before posting. :-P Glad it will be resolved. :-)
