### ISSUE TITLE
Consistency in the Usage of Terms

### ISSUE THREAD

**Issue by imanickam** [joomla/joomla-cms#6292]
#### Steps to reproduce the issue

In the back-end, in the screen "Extension Manager: Update Sites", the words Enable and Publish are used interchangeably.  Likewise, the words Disable and Unpublish are used interchangebly.

The buttons say "Enable" and "Disable" whereas the bubble help text says "Publish Item" and "Unpublish Item" respectively.  

#### Expected result

The terminologies used should be standardized.![screen shot 2015-03-03 at 23 26 47](http://issues.joomla.org/uploads/1/25239d77baa6554c9a53d445fa7f2dce.jpg)

**Comment by imanickam** [comment]
We do not create these Update Sites links.  They are taken from the xml files of the extensions/templates/languages.

So, based on the function of the screen, IMHO, the terms "Enable" and "Disable" are correct.   

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6292">issues.joomla.org/joomla-cms/6292</a>.</sub>

**Comment by infograf768** [comment]
Please test patch
https://github.com/joomla/joomla-cms/pull/6297
