### ISSUE TITLE
Issue with multilingual sites after Joomla 3.4 update

### ISSUE THREAD

**Issue by guywalder** [joomla/joomla-cms#6295]
#### Steps to reproduce the issue
Update a Multilingual site to Joomla 3.4 
Not effecting all sites!

#### Expected result
Site loads o.k. after update. Component pages appear as blank. Replacing languagefilter.php under plugins/system/languagefilter solved the issue.

**Comment by brianteeman** [comment]
Please see https://docs.joomla.org/Category:Version_3.4.0_FAQ

**Comment by guywalder** [comment]
I'm sorry but that's not the issue I was reporting of. 
In some of my multilingual sites, after updating to Joomla 3.4 the website won't load. 
Turning off "Remove URL Language Code" under "System - Language Filter" seems to solve this.
