### ISSUE TITLE
Remove hathor

### ISSUE THREAD

**Issue by nonumber** [joomla/joomla-cms#6303]
Is there any good reason not to remove hathor completely?
Pretty much everything is half broken and nothing gets tested in/for it.

**Comment by nonumber** [comment]
PS: I'd happily create the PR to remove it ;)

**Comment by losedk** [comment]
+1 :)

**Comment by n9iels** [comment]
I thought the Hathor template was build as a special User actability template. I'm not sure if there a people who using it. So also a +1 for me.
But are we aloud to a modification like this for Joomla! 3.5?

A related question can be: should we remove the legacy icons to? I'm pointing to the old .png icons you can use for the com_content instead of the Bootstrap Iconset. There is currently no real parameter in the configuration for it, only a `true` or `false` in the code.

**Comment by nonumber** [comment]
hathor was supposed to be the accessible admin template. But interest has been lost in it. No development is being done on it. Isis has surpassed hathor on the accessible side quite some time ago.
In my view hathor doesn't serve any purpose apart from exposing the unprofessional side of Jooma, In other words: bad for image and marketing. It is hurting Joomla.

**Comment by n9iels** [comment]
Definitely agree with that!

**Comment by dgt41** [comment]
Following the web links path, that shouldn't be very hard!

**Comment by JoomliC** [comment]
I thought both hathor and Isis to be removed when a new admin template will be available ?

But i truly agree that this admin template is not a good example of the Joomla 3 potential!
+1 ;)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6303">issues.joomla.org/joomla-cms/6303</a>.</sub>

**Comment by brianteeman** [comment]
Moving to needs review s this is a decision for the PLT<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6303">issues.joomla.org/joomla-cms/6303</a>.</sub>

**Comment by Hackwar** [comment]
Isis is the new template that was added. Bluestork was the old template up to 2.5

**Comment by Hackwar** [comment]
Could we maybe go through Hathor and see which accessibility features have not been included in Isis yet, transfer those and maybe provide an alternative CSS style for Isis for better contrast? Then we could really simply drop Hathor.

**Comment by brianteeman** [comment]
as there is an a11y working group now can we not leave it to the experts

On 16 March 2015 at 21:25, Hannes Papenberg <notifications@github.com>
wrote:

> Could we maybe go through Hathor and see which accessibility features have
> not been included in Isis yet, transfer those and maybe provide an
> alternative CSS style for Isis for better contrast? Then we could really
> simply drop Hathor.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6303#issuecomment-81948495>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by nonumber** [comment]
Any news on that team? Who is in it? Couldn't find it on http://volunteers.joomla.org/working-groups

**Comment by Bakual** [comment]
Peter Bui started one only recently. You can directly contact him I think.

**Comment by nonumber** [comment]
ok, thanks

**Comment by Hackwar** [comment]
@brianteeman I wanted to propose a solution that does not simply throw away the knowledge in Hathor or that lets it rott in some repo somewhere. Support wont get better for it, when it is a seperate extension. But if there is such a group, they are definitely a good fit for this. :smile:

**Comment by Gitjk** [comment]
"Pretty much everything is half broken and nothing gets tested in/for it."

Are you shure you didn't mix that up with Bluestork? My Hathor template looks fine and I often use it when I have for example a working copy and a live site open at the same time. With one using Hathor and the other using Isis its helps (visually) to prevent acidentially selecting a wrong tab and experimenting with the live site instead of with the working copy..

**Comment by nueckman** [comment]
@Gitjk, you could just edit isis parameters (e.g. color) to achieve that

**Comment by nonumber** [comment]
I've been looking through the hathor html. I haven't seen anything interesting so far that would make it better from an accessibility point of view. And if there is, then I don't see why that couldn't be easily ported over to isis.
So - as far as I see it - there could be some visual accessibility improvements to isis, if that would warrant the RIP of hathor. That wouldn't be too hard at all.

**Comment by nonumber** [comment]
PS: Yes, I'll try to get in touch with Peter Bui to ask where the accessibility working group is at.

**Comment by dgt41** [comment]
All needed in isis is:
1. this plugin https://github.com/paypal/bootstrap-accessibility-plugin , modified to work with bs 2.3.2
2. one template style with inverted colors
3. one template style with increased contrast
4. bring all fonts sizes to some better values (increase them)

It shouldn’t be that much work if few people work as a group.
You can count me in!

**Comment by JoomliC** [comment]
Accessibility Working Group ?
A first job could be this : https://github.com/joomla/joomla-cms/issues/5898#issuecomment-75892897 

@dgt41 :+1: 
I agree with a group, but all this is UX, and seems that UX group is not active... (no member)
I would be glad to join!

**Comment by pbwebdev** [comment]
Funny, I was just talking to @nonumber about that plugin on Skype.

Your wish list @dgt41 is great! We have a lot more to add too. Don't want to clog this thread with too many things but instead I'll create separate issues for each thing that we need to think about adding in.

Thank that will work better.

**Comment by jmccabe** [comment]
Does anyone know how many Joomla installations there are worldwide, and how many admins of those sites currently use Hathor?

**Comment by nonumber** [comment]
No, we don't know, as Joomla doesn't send stats to a central server.

**Comment by jmccabe** [comment]
So, what you're suggesting is that you should remove a feature that could, in fact, be in use by every administrator who uses Joomla. Is that wise?

**Comment by mbabker** [comment]
Could make the same argument against taking any extension out of the core Joomla distro and making it available standalone (like weblinks was).

**Comment by jmccabe** [comment]
You could, yes. That would suggest removing Hathor is a feasible proposition as long as it remains available as an installable template (at least for some time) for those who want to use it. Doing it that way you should be able to determine how many times it's installed after it's removed from the core and hence determine how important it is to users before deciding to abandon it completely.

**Comment by brianteeman** [comment]
That would only show NEW installs. Any upgraded site would still have the
existing templates installed.

**Comment by mbabker** [comment]
It would log the download if an existing site updated the template too.  What we wouldn't catch is if any existing site never updated or just flat out uninstalled it.

**Comment by jmccabe** [comment]
But if an existing site just never updated then surely it wouldn't matter?

**Comment by nonumber** [comment]
@jmccabe I think you are missing the point here.
hathor was born to be the accessible template in Joomla.
We have gone a long way since that decision and isis has become a lot more accessible in the process.
Not only that, but hathor remains forgotten in development. It has become neglected and buggy. New features are near-never tested on hathor. And improvements to the admin template are always done to isis, never to hathor. There are no plans to renew hathor in any way.
So keeping hathor in Joomla simply means we are giving people the possibility to use a no-longer tested, developed and updated piece of old code.

As said, removing hathor from future installs and updates would not influence setups using hathor. It wouldn't remove the template from those updates.

**Comment by nonumber** [comment]
> that could, in fact, be in use by every administrator who uses Joomla

No, it can't. For one, isis is the default template. We all know how many people stick with the defaults (read: many).
And secondly, I don't use hathor, neither does Michael and I believe Brian sticks with isis too.
So worst case scenario is that all but 3 administrators use hathor. Seeing these do not include Michael, Brian or me, I don't see a reason to take them seriously. _just kidding_

**Comment by Bakual** [comment]
You can add me to the list of non-Hathor users. Makes us a small minority of at least 4 people :smile:

**Comment by dgt41** [comment]
5 with me😂

**Comment by jmccabe** [comment]
With all due respect @nonumber, I think you're missing my point. I'm not saying don't remove it ever, just make sure that the people who are using it have an easy way of finding out that it's being removed and/or is no longer supported and make sure they're given adequate warning of when it's going to disappear.

There's no better way to piss people off than take away features they find indispensable without any warning.

**Comment by nueckman** [comment]
I think there might be a reason why we have something like an accessibility working group, so let's them decide if hathor is still desired or required.

It seems more important to me to find a way to "deprecate" an extension. Maybe just an EOL flag in the manifest. We can't assure that every developer will use this, but it would be very convenient for all users.

**Comment by OctavianC** [comment]
+1 to remove Hathor. If we remove it from the package, people using it will not be affected. New installs are using Isis as the default template so no issue here as well.

If there is a need for Hathor, I think it can be decoupled and listed as a separate extension, just like com_weblinks.

**Comment by poorgeek** [comment]
As a user of Hathor I'd like to see it stay until the isis theme can be evaluated and the Joomla accessibility statement updated to reflect the results of the evaluation.

**Comment by nonumber** [comment]
Year old now. So no use in keeping this open.

**Comment by philip-sorokin** [comment]
I'am suprised that it has not been dropped yet. This discussion is 2 years old, but Hathor died much earlier. RIP.

**Comment by zero-24** [comment]
Btw. It is dropped in 4.0 already :) we cant do this in 3.x because of B/C
