### ISSUE TITLE
Side bar close icon should not be an X

### ISSUE THREAD

**Issue by brianpeat** [joomla/joomla-cms#6310]
#### Steps to reproduce the issue
Log into the admin and visit a page that uses the side bar, such as the Article Manager

#### Expected result
The icon to collapse the left side bar should be a circle left chevron symbol like this: < to denote that it can be closed.

#### Actual result
Instead it is an X icon, which is usually used to denote "close for good".

#### System information (as much as possible)
Any version of 3.4, it's an interface change, not a bug in functionality.

#### Additional comments
I've attached a screen shot of the before/after of this. This change would likely require an update to the IcoMoon font, which I suspect is why the X is being used (the IcoMoon font does not contain a circle < icon)

Another option would be to replace the X with this IcoMoon character "\e00c" which gives a left arrow in the circle.![screen shot 2015-03-04 at 13 10 26](http://issues.joomla.org/uploads/1/5d20a763f67648a49d70f6cbbd6f3d2d.jpg)

**Comment by mbabker** [comment]
The current icon was chosen IIRC because of instances where the UI is in a RTL language and the sidebar is on the right side.

**Comment by brianpeat** [comment]
Could it not be flipped based on the rtl flag? Just curious. It just seems odd to have an X there. I notice the OPEN icon is a right arrow, so obviously that one is being flipped when the side bar is on the other side (or I assume it is).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6310">issues.joomla.org/joomla-cms/6310</a>.</sub>

**Comment by mbabker** [comment]
All I could find on it was https://github.com/joomla/joomla-cms/pull/5141 and I guess it was just a preference.

**Comment by spignataro** [comment]
I think the icons need to be more prominent than what they are.

**Comment by JoomliC** [comment]
@mbabker You're right, it was just a preference, after a long debate (over 3 PR, where #5141 is the latest one.

In my opinion, this could be improved. @brianpeat you could find other suggestion screenshots on #5141 ;-)
<blockquote>
This change would likely require an update to the IcoMoon font, which I suspect is why the X is being used (the IcoMoon font does not contain a circle < icon)
</blockquote>
Yes, this was one of the reason!
The icomoon could be updated, as for example in this PR #6247, i've made a suggestion to remove the * from label required layout (and strings of translation) to use icon-asterisk (but no icon-asterisk really exists as it it is the same icon as for icon-unfeatured and icon-star-empty : a star).

The question is who and how it is possible to update joomla icomoon font ? Or is the json file is available somewhere ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6310">issues.joomla.org/joomla-cms/6310</a>.</sub>

**Comment by infograf768** [comment]
The change is very simple:
```
diff --git a/administrator/templates/isis/js/template.js b/administrator/templates/isis/js/template.js
index 9419423..2c17c48 100644
--- a/administrator/templates/isis/js/template.js
+++ b/administrator/templates/isis/js/template.js
@@ -67,10 +67,10 @@
 			var $sidebar = $('#j-sidebar-container');
 
-			var open_icon = 'icon-cancel';
+			var open_icon = 'icon-arrow-left-2';
 			var closed_icon = 'icon-arrow-right-2';
 
 			if (jQuery(document.querySelector("html")).attr('dir') == 'rtl')
 			{
-				open_icon = 'icon-cancel';
+				open_icon = 'icon-arrow-right-2';
 				closed_icon = 'icon-arrow-left-2';
 			}
diff --git a/layouts/joomla/sidebars/toggle.php b/layouts/joomla/sidebars/toggle.php
index 28d6164..8cc274a 100644
--- a/layouts/joomla/sidebars/toggle.php
+++ b/layouts/joomla/sidebars/toggle.php
@@ -21,4 +21,4 @@
 	onclick="toggleSidebar(false); return false;"
 	>
-	<span id="j-toggle-sidebar-icon" class="icon-cancel"></span>
+	<span id="j-toggle-sidebar-icon" class="icon-arrow-left-2"></span>
 </div>
```

which gives:
![screen shot 2015-03-05 at 08 48 33](https://cloud.githubusercontent.com/assets/869724/6501124/b02a07f6-c314-11e4-8e6a-974970f6e517.png)

and in RTL
![screen shot 2015-03-05 at 08 48 09](https://cloud.githubusercontent.com/assets/869724/6501125/b8d18352-c314-11e4-921a-e56c15f16390.png)

**Comment by JoomliC** [comment]
@infograf768 Yes, it's simple, as the script already allow this ;-)

I don't remember where exactly the decision for "close" cross...
I think it was maybe in @roland-d initial PR, where the close cross was decided (i know just that it was my suggestion, as the cross in the sidebar container, and mean "close".)

But due to the many changes done between @roland-d PR and final 3.4.0 sidebar, i think we can actually change the close icon to the arrow icon.
Left/Right icons seems good for me.
@infograf768 and @brianpeat : Do you want to create the PR, or do i create this PR ? (with maybe a little ajustement for arrow margin)

**Comment by PhilETaylor** [comment]
I think there is also a common opinion that a collapsing sidebar is of no real value and should be removed :)

**Comment by roland-d** [comment]
@brianpeat The discussion on which icon to use is one that will never reach a mutual agreement. It almost needs to be yet another option :) My personal favorite is still the hamburger icon as this seems to be used more for menus. At this moment, I personally don't care too much about which icon we have as long as there is a space to click.

The one thing to keep in mind is indeed RTL languages when going with an icon that is direction sensitive.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6310">issues.joomla.org/joomla-cms/6310</a>.</sub>

**Comment by PhilETaylor** [comment]
Re: Hamburgers - the web is finally waking up the fact that that icon is pathetic... 
https://lmjabreu.com/post/why-and-how-to-avoid-hamburger-menus/
http://exisweb.net/menu-eats-hamburger

**Comment by spignataro** [comment]
Here is my beef with the disappearing menu now working with it for some time. It serves 0 purpose as most of the options are necessary. Hiding menus isn't a problem - but hiding options to change your view you shouldn't hid. It is fine for the top filters because those aren't used as regular. 

With some user testing on my end our clients found no use for it and it was often confusing as these items are used quite a bit. Also the UI does not match the rest of the UI in Joomla! therefore a detachment from the backend look and feel. In some cases it feels that it was forced by a 3rd party plugin. 

It just doesn't feel natural.

**Comment by brianteeman** [comment]
The filters that it is hiding should always have been on the top where they
belong and as proposed last year by the ux team. The same is true for the
useless menu items which are just duplicates of the top menu. Again
something fproposed and rejected by the ux team. When you accept both of
those proposals you have nothing left to go in the sidebar and you achieve
the desired effect of having a full width list view

**Comment by mbabker** [comment]
So opinions about the sidebar aside, can we come to a consensus on the icons and stop trying to adjust the sidebar in some form every other release?

**Comment by PhilETaylor** [comment]
refactor to make it a horizontal sub menu like @brianteeman states - and remove the sidebar completely… :) Job done :-) Then never have to come back to this issue..

**Comment by brianpeat** [comment]
Why not just change the icon for 3.4.1 and leave it. I'd also suggest making the font size 18px to make the button a bit bigger. 

Then we can revisit a completely overhaul for 3.5. The UX group is working on that kind of thing anway, so arguing over removing it in the 3.4 stream seems like a waste of time to me.

I'll let someone else do the PR as I don't know how to do that. Anyway, one more argument to make it an arrow for now is that when it's CLOSED it's an arrow pointing out. Seems to me it should be an arrow pointing in when it's open to keep it more uniform. Changing to a hamburger to me denotes a menu, not a collapsable panel thats open by default.

Just my 2 cents.

**Comment by mbabker** [comment]
:facepalm:

Being blunt, I think it'd be nice to get some stability in the layouts (in some form, nearly every release has changed something about the admin... control panel organization, search tools, sliding sidebar, Joomla logo position).  And as it is, there are discussions starting on a totally new admin template.  So if I had BDFL voting rights, I'd suggest just getting the icon consistent (arrow does seem to make more sense) and leaving the sidebar be as a relic of Isis' design and letting the new template get things "right" (term loosely defined since I doubt we'll all agree on what that is).

**Comment by roland-d** [comment]
I also think that we simply need a new backend template, one that replaces the current two that we have. How it should look like, I leave that to the bright minds of UX :)

**Comment by brianpeat** [comment]
Right, that's exactly what I'm suggesting. Just fix the arrow for consistency and leave it. Moving or removing it is not for this discussion at all. That's for the UX team to decide for a later release.

**Comment by brianpeat** [comment]
So the submission should be to replace the X with the left arrow (already part of the IcoMoon font), and then make sure in RTL languages, the icon codes are reversed so the arrow points right when open and left when closed. And yes, the padding needs to be a bit more when closed. The arrow is barely noticeable over there on the edge.

To me that's the least amount of changing until something new gets designed for another release. It's more of a fix than a redesign.

**Comment by mbabker** [comment]
:+1: Sounds good to me

**Comment by JoomliC** [comment]
+1 for me and PR done : https://github.com/joomla/joomla-cms/pull/6327

It's not yet possible to remove the sidebar, and as @roland-d said : "I also think that we simply need a new backend template, one that replaces the current two that we have."
I will be at jab15, and it could be a good place to share ideas about a new admin template. I will have some to share, and with no need of a sidebar ;-)

**Comment by spignataro** [comment]
I have started the conversation here: https://docs.google.com/a/corephp.com/document/d/1DGYxjK8WXxU1UQooNTBlpk7j_TVQ0pnZTa-ti8K2WzQ/edit#heading=h.tgukxergexec

We don't just need a new backend - but we really need a usable, functional, *accessible*, standards driven backend.

**Comment by zero-24** [comment]
Closing as we have a PR by @JoomliC https://github.com/joomla/joomla-cms/pull/6222<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6310">issues.joomla.org/joomla-cms/6310</a>.</sub>

**Comment by zero-24** [comment]
Wrong link. :smile: correct PR is: https://github.com/joomla/joomla-cms/pull/6327<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6310">issues.joomla.org/joomla-cms/6310</a>.</sub>
