### ISSUE TITLE
Frontend User Edit: wrong link(href) on "Calcel" button

### ISSUE THREAD

**Issue by fluctuate** [joomla/joomla-cms#6311]
#### Steps to reproduce the issue
Problem comes on Frontend "User Profile Edit" page and when i click on "Cancel" button.
In fact, when i click on "Cancel" button joomla redirects in the some page, i.e. "User Profile Edit" page.

#### Expected result
Clicking "Cancel" button Joomla must redirect me on "User Profile" view page (and not in edit page).
I fixed this problem rewriting "href" property on cancel button tag.
See line 128 on file: "/components/com_users/views/profile/tmpl/edit.php"

#### System information (as much as possible)
3.3.6

**Comment by n9iels** [comment]
In my opinion it is just the expected behavior. A link like <i>User Profile Edit</i> is made for a shortcut to the edit page of a user profile.  The cancel button is logically also a shortcut back.

**Comment by fluctuate** [comment]
I think that if i click on Cancel button then i have to rturn on view page.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6311">issues.joomla.org/joomla-cms/6311</a>.</sub>

**Comment by fluctuate** [comment]
I've just noticed that joomla 3.4 has the same problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6311">issues.joomla.org/joomla-cms/6311</a>.</sub>

**Comment by brianteeman** [comment]
Closing as we have a PR for testing #8402<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6311">issues.joomla.org/joomla-cms/6311</a>.</sub>
