### ISSUE TITLE
'/' Key Disabled in Template Editor

### ISSUE THREAD

**Issue by crystalenka** [joomla/joomla-cms#6313]
#### Steps to reproduce the issue
Open the template manager.
Click on 'templates' in the side bar.
Open a template of your choice, and create a new file.
Begin writing code - if you try to use the '/' key it is disabled unless you have an open tag. This is a problem because file paths, etc. will frequently need to use this key.

#### Expected result
Allow use of '/' key even if there is no open tag.

#### Actual result
'/' key is disabled unless there is an open tag; if there is an open tag '/' key triggers an automatic closing tag.

**Comment by infograf768** [comment]
Closing a redundant issue.
see https://github.com/joomla/joomla-cms/pull/6280
and
https://github.com/joomla/joomla-cms/pull/6150
