### ISSUE TITLE
Protostar template in 3.4: Why is modal 80% width of screen width?

### ISSUE THREAD

**Issue by tranduyhung** [joomla/joomla-cms#6315]
Hi,

Could anyone give me any reason why we need to set the width of modal to 80% in 3.4's Protostar template?

I couldn't find a commit for this in the commit history. Maybe I missed it while browsing the commits.

Now the modal takes 80% width of the screen, so wide.

![home_-_2015-03-05_14 17 40](https://cloud.githubusercontent.com/assets/503262/6500761/a9b61aee-c342-11e4-8960-28138da7eae0.png)

https://github.com/joomla/joomla-cms/blob/staging/templates/protostar/css/template.css#L6162

```
div.modal {
	position: fixed;
	top: 5%;
	left: 50%;
	z-index: 1050;
	width: 80%;
	margin-left: -40%;
	background-color: #fff;
	border: 1px solid #999;
	border: 1px solid rgba(0,0,0,0.3);
	*border: 1px solid #999;
	-webkit-border-radius: 6px;
	-moz-border-radius: 6px;
	border-radius: 6px;
	-webkit-box-shadow: 0 3px 7px rgba(0,0,0,0.3);
	-moz-box-shadow: 0 3px 7px rgba(0,0,0,0.3);
	box-shadow: 0 3px 7px rgba(0,0,0,0.3);
	-webkit-background-clip: padding-box;
	-moz-background-clip: padding-box;
	background-clip: padding-box;
	outline: none;
}
```

**Comment by dgt41** [comment]
Try #4575

**Comment by brianteeman** [comment]
Closing as the question has been answered<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6315">issues.joomla.org/joomla-cms/6315</a>.</sub>
