### ISSUE TITLE
"Info: You are not a Registered Customer yet. Please provide your Billing Information."

### ISSUE THREAD

**Issue by manojb05** [joomla/joomla-cms#6318]
After successfully registering, when a user clicks "Checkout>>", they are redirected to the Billing Address page, with an error message:

"Info: You are not a Registered Customer yet. Please provide your Billing Information."

The problem is, this info was already entered during the user's registration.  If you re-enter it, the same problem will continue to happen.  Why is VM not storing the billing address data?. How can i rectify the issue?

Virtumart 1.9 & Joomla 1.5.

**Comment by Fedik** [comment]
well, two thing: 
Joomla 1.5 not supported anymore, please do upgrade...
Your problem related to Virtumart,  please contact Virtumart developers to get support

**Comment by manojb05** [comment]
thanks fedik your prompt reply. I don't get the any supportive link from google. if you have any idea please let me know

**Comment by Fedik** [comment]
try  [Virtumart forum](http://forum.virtuemart.net/)

**Comment by manojb05** [comment]
thanks fedik
