### ISSUE TITLE
Joomla 3.4 isis admin template save buttons don't work 

### ISSUE THREAD

**Issue by SimonHodgkiss** [joomla/joomla-cms#6319]
#### Steps to reproduce the issue

Fresh install of Joomla 3.4

#### Expected result

Save buttons inside isis admin template working & not working

#### Actual result

Working or not working

#### System information (as much as possible)

Joomla 3.4 
PHP - 5.4.38 
Save buttons don't work

Joomla 3.4
PHP - 5.4.36 
Save buttons working fine

**Comment by PhilETaylor** [comment]
Not a Joomla problem.

Have you cleared your browser cache?

What does the Javascript console of your browser say the Javascript issue is?

**Comment by SimonHodgkiss** [comment]
I've tested on several machines with different browser programs as well all giving the same problem.

The Javascript console says:

TypeError: document.formvalidator is undefined <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6319">issues.joomla.org/joomla-cms/6319</a>.</sub>

**Comment by PhilETaylor** [comment]
Which EXACT save button?

**Comment by SimonHodgkiss** [comment]
Any save buttons, on any section of the admin.

Save, Save & Close, Save & New

For adding menu items or articles or anything where them buttons are shown at the top.

The close button works fine tho. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6319">issues.joomla.org/joomla-cms/6319</a>.</sub>

**Comment by PhilETaylor** [comment]
And one more question - is this using Joomla 3.4.0 Stable as released, or from the joomla-cms staging git branch ?

**Comment by SimonHodgkiss** [comment]
Stable release though cPanel Installatron plugin - I also believe my friend did an upgrade from 3.3.6 to the stable version from Joomla which resulted in the same problem. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6319">issues.joomla.org/joomla-cms/6319</a>.</sub>

**Comment by dgt41** [comment]
> TypeError: document.formvalidator is undefined

That means something went wrong in the update procedure, so you don’t have the correct /libraries/cms/html/behavior.php
You can copy it from github manually!

**Comment by SimonHodgkiss** [comment]
I created a fresh install using installatron plugin for cpanel that wasn't and update though.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6319">issues.joomla.org/joomla-cms/6319</a>.</sub>

**Comment by PhilETaylor** [comment]
DONT use installatron - use a manual installation, Who knows what crap cPanel or installatron have done to the source distributed files

**Comment by dgt41** [comment]
The only thing I can say with certainty is that function formvalidator was introduced in 3.4, so something strange goes on here!

**Comment by SimonHodgkiss** [comment]
Thats very true :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6319">issues.joomla.org/joomla-cms/6319</a>.</sub>

**Comment by PhilETaylor** [comment]
I'm just reconfiguring for PHP  5.4.38 and will test this then...

**Comment by SimonHodgkiss** [comment]
Thanks, 

Just remembered both installs was using installatron on 2 different servers. 

The only difference been the php versions 

So perhaps the installatron isn't a problem let me know what you find<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6319">issues.joomla.org/joomla-cms/6319</a>.</sub>

**Comment by PhilETaylor** [comment]
I cannot recreate this issue with PHP Version 5.4.38 on localhost with ampps. 

I believe this is not a Joomla issue, more likely to be a server configuration or installatron installation issue.

**Comment by SimonHodgkiss** [comment]
Thanks, it's fixed now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6319">issues.joomla.org/joomla-cms/6319</a>.</sub>

**Comment by PhilETaylor** [comment]
Care to comment how?

**Comment by SimonHodgkiss** [comment]
Copied the file (/libraries/cms/html/behavior.php) from the 1 that worked to the 1 that didn't and that fixed it
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6319">issues.joomla.org/joomla-cms/6319</a>.</sub>

**Comment by PhilETaylor** [comment]
Did you backup the file you replaced? can you provide a copy for me to inspect? We might be able to provide feedback to installatron

**Comment by SimonHodgkiss** [comment]
Yes I have the file, www.mals.xyz/bak-behavior.php

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6319">issues.joomla.org/joomla-cms/6319</a>.</sub>

**Comment by PhilETaylor** [comment]
Thats no use as it cannot be loaded as its a PHP file being parsed by PHP :) rename the extension please.

**Comment by SimonHodgkiss** [comment]
http://www.mals.xyz/bak-behavior.txt

Forgot about that!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6319">issues.joomla.org/joomla-cms/6319</a>.</sub>

**Comment by PhilETaylor** [comment]
That file you provided is identical to the distributed /libraries/cms/html/behavior.php in Joomla 3.4.0

**Comment by enesbil** [comment]
Just had the same issue. The problem was because of Cloudflare. Solved by purging cloudflare-cache.

**Comment by Zhigalin** [comment]
If someone is reading this with the same problem on joomla 3.4.3:
Substitute the contents of /media/system/js/validate.js with this:
https://raw.githubusercontent.com/joomla/joomla-cms/925c3fa5d512b9aff8c5b470804d282fb1b70afb/media/system/js/validate.js

**Comment by franz-wohlkoenig** [comment]
@Zhigalin thanks for contributing. 

I guess its more helpful to write at the [forums](https://forum.joomla.org/) cause this repository concerns Joomla coding and this Issue is closed since more than 2 Years.
