### ISSUE TITLE
setMetaData name with captitals?

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#6330]
#### Steps to reproduce the issue

Put this in the template index.php:
$doc->setMetaData('msapplication-TileColor', '#b4285f');

#### Expected result
meta name="msapplication-TileColor" content="#b4285f"

#### Actual result
meta name="msapplication-tilecolor" content="#b4285f"
(No more uppercase characters on the meta name.)

#### System information (as much as possible)
Joomla 3.4.0

#### Additional comments
The file libraries/joomla/document/document.php -> public function setMetaData sets the $name to: 

$name = strtolower($name);

But I believe the name of the tag I want to include in the template need to have the uppercase characters. Why is this strtolower added here?

**Comment by jjnxpct** [comment]
https://msdn.microsoft.com/en-us/library/ie/dn255024%28v=vs.85%29.aspx
"Be aware that preset values are case-sensitive and must be specified using the case shown."<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6330">issues.joomla.org/joomla-cms/6330</a>.</sub>

**Comment by PhilETaylor** [comment]
http://www.w3.org/TR/html5/document-metadata.html#attr-meta-name 

This states:

```Names are case-insensitive, and must be compared in an ASCII case-insensitive manner.```

And then goes on in 4.2.5.2 Other metadata names to show several examples of capitalised first letters of Names.  (Keyword, Synonyms etc...)

Therefore it should not really matter if Joomla makes them lowercase or not really..

**Comment by PhilETaylor** [comment]
PR Opened. #6345

**Comment by zero-24** [comment]
Closing as we have a PR thanks @PhilETaylor https://github.com/joomla/joomla-cms/pull/6345<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6330">issues.joomla.org/joomla-cms/6330</a>.</sub>
