### ISSUE TITLE
New Joomla htaccess breaks htpasswd protection of administrator

### ISSUE THREAD

**Issue by vancanneyt** [joomla/joomla-cms#6339]
When updating root .htaccess file to the latest provided with Joomla 3.4 and you have your administrator directory password protected with .htaccess/htpasswd. Then you can't access the administrator page (404 not found). When re-adding the line in the image) it works again. 
![schermafbeelding 2015-03-06 om 14 24 58](https://cloud.githubusercontent.com/assets/6499796/6526076/f2ba38c6-c40d-11e4-8bfe-a1adf6894f3a.png)

**Comment by brianteeman** [comment]
For reference this is when the change was made
https://github.com/joomla/joomla-cms/commit/e5eb98ab4fe88cdc43e3b0118d6c55cbfb8759fd



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6339">issues.joomla.org/joomla-cms/6339</a>.</sub>

**Comment by brianteeman** [comment]
Raising the priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6339">issues.joomla.org/joomla-cms/6339</a>.</sub>

**Comment by PhilETaylor** [comment]
in your custom /administrator/.htaccess please try adding:

ErrorDocument 401 default

And see if that helps in your server environment (to be clear, add this in YOUR CUSTOM /administrator/.htaccess and not in the Joomla .htaccess in /.htaccess)

**Comment by vancanneyt** [comment]
Okay, that did help. But i think the same question will be asked a lot for all users that use Cpanel,DirectAdmin etcetera; the default password protect directories function in those systems doesn't add that line making the users backend unreachable if they wanna password protect it. Should Joomla add some docs about that to inform users?

**Comment by PhilETaylor** [comment]
This DEPENDS on your own server configuration. 

Standard configurations of Apache will have a default handler for 401 errors - unlike your non standard configuration. 

you might also need a 403 line too 

```
ErrorDocument 403 default
ErrorDocument 401 default
```

For information Akeeba Admin Tools has this feature, and their forum and documentation talk about this issue and how to resolve it. 

As Joomla doesn't provide any feature to secure your /administrator/ with a .htaccess and as this change to the code htaccess will work in standard apache configurations (ones where the webhost has not overruled the 401/403 handlers) I don't see that this is anything that Joomla needs to educate or document about.

**Comment by PhilETaylor** [comment]
Please can you tell me who your webhost is? (Dreamhost? Hostgator? Fasthosts? Bluehost?)

**Comment by PhilETaylor** [comment]
This also appears to be a common issue for DirectAdmin control panel users. Still - not a Joomla issue. 

Suggest closing this.

**Comment by vancanneyt** [comment]
Ok, thx closing it. Maybe i'll talk to the directadmin guys about it ;-) seems common on their default installations
