### ISSUE TITLE
Absence of the ";" at the end of file /media/system/js/frontediting.js

### ISSUE THREAD

**Issue by sonosergio** [joomla/joomla-cms#6344]
the absence of the ";" at the end of file /media/system/js/frontediting.js cause error in plugin as rookboster when user is logged in frontend
#### Steps to reproduce the issue
use rookboster in joomla site

#### Expected result
error javascript because rokbooster insert all javascript in single line

#### System information (as much as possible)
Joomla 3.4

**Comment by PhilETaylor** [comment]
PR #6346 ready for testing.

**Comment by mbabker** [comment]
See #6346 for patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6344">issues.joomla.org/joomla-cms/6344</a>.</sub>
