### ISSUE TITLE
Upgrade Joomla template from Joomla 1.5 to Joomla 3

### ISSUE THREAD

**Issue by manojb05** [joomla/joomla-cms#6347]
Hi, 
I have a e-commerce website template is made joomla 1.5  how can i upgrade with joomla please help for the same step by step.... u guys have any tutorial please share..

**Comment by brianteeman** [comment]
This is the tracker for reporting bugs. Please check http://forum.joomla.org and http://docs.joomla.org

**Comment by zero-24** [comment]
https://docs.joomla.org/J2.5:Upgrading_a_Joomla_1.5_template_to_Joomla_2.5

**Comment by zero-24** [comment]
oops wrong link this is the right one: https://docs.joomla.org/Migrating_a_Template_from_Joomla_1.5_to_3.x

**Comment by manojb05** [comment]
thanks
