### ISSUE TITLE
Optimization of the robots.txt for components's media files (JS, CSS ...)

### ISSUE THREAD

**Issue by garstud** [joomla/joomla-cms#6361]
Some components install their JS, CSS and images in their own **/assets** directory instead of using the **media** tags in the XML manifest.

It may sense to optimize the robots.txt to give the ability for GoogleBot to access theses files.
I suggest to modify the robots.txt with theses lines :

Replace the line :
<pre>Disallow: /components/</pre>

By theses 3 lines :
<pre>Allow: /components/*/assets/css/*.css$
Allow: /components/*/assets/js/*.js$
Disallow: /components/</pre>

This way, GoogleBot will be able to validate that Joomla sites are more '**Mobile Compatible**'.

More infos in my article on Mobile site optimization (sorry, this is a french article so i give you the auto-translate url) :
https://translate.google.com/translate?hl=en&sl=fr&tl=en&u=http%3A%2F%2Fwww.garstud.com%2Fjoomla%2F12-joomla%2F25-optimisation-joomla-pour-la-compatibilite-mobile.html

**Comment by Fedik** [comment]
for me it is the components issue,
I would ask the component developers to move their /assets to /media

Joomla use this long time ago, and I wonder why they still use /assets :smile: 
lazy people :smile:

**Comment by bertmert** [comment]
Please see closed issue
https://github.com/joomla/joomla-cms/pull/6098

**Comment by brianteeman** [comment]
We cant have rules for everything - we can only have rules for standard behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6361">issues.joomla.org/joomla-cms/6361</a>.</sub>

**Comment by brianteeman** [comment]
In addition as Allow is not part of the standard for robots.txt I am closing this
(You can confirm this yourself using the robots.txt checker referred to in the file itself)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6361">issues.joomla.org/joomla-cms/6361</a>.</sub>

**Comment by garstud** [comment]
Ok, i understand and i agree to close this PR. Devs should used the **media** tag!

For the **'Allow'** directive, you should notice that the most actives bots (google, bing, ...) support this non-standard directive, and that make sense to optimize the "mobile-fiendly" required by Google.
(see 'Allow' directive : http://www.garstud.com/images/stories/blog/joomla/google_compat_mobile4.png )

And I speak in my article about using many 'User-agent' to be sure to give correct directives to correct bots.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6361">issues.joomla.org/joomla-cms/6361</a>.</sub>
