### ISSUE TITLE
Templates manager. Windows Manage folders and Create Or Upload a New File.

### ISSUE THREAD

**Issue by Orsey** [joomla/joomla-cms#6362]
Hello everyone.

In Windows Manage folders and Create Or Upload a New File, I do not see some folders if if they do not fall in the viewing area of my browser window. This popup window do not have scrollbar and does not react to scroll of mouse because it's have fixed position. I have to use the zoom of the browser window to access the hidden folders.

CSS style for my resolution (1600 x 900) screen may be so

.modal-body .column {
  width: 50%;
  float: left;
  display: block;
  height: 570px;
  overflow: auto;
}

**Comment by bertmert** [comment]
This issue has been fixed by
https://github.com/joomla/joomla-cms/pull/6351
