### ISSUE TITLE
7-zip support in the Extension Manager

### ISSUE THREAD

**Issue by mladenb** [joomla/joomla-cms#6364]
#### Steps to reproduce the issue
Go to the Extension Manager in the admin area.
Install the extension from the uploaded 7-zip archive.

#### Expected result
Component installs successfully.

**Comment by N6REJ** [comment]
Are you talking about .7z files or standard zip file made by 7 zip?
Bear

**Comment by mladenb** [comment]
I'm talking about standard 7z files.

**Comment by pcmitsis** [comment]
I think that this can't be done since php doesn't provide a 7zip extension (at least one that i am aware of). My answer is based on [this documentation](http://php.net/manual/en/refs.compression.php) and [this forum](http://stackoverflow.com/questions/3888497/7z-extension-for-php).

Cheers!

**Comment by brianteeman** [comment]
Based n the information above from @pcmitis this is not possible so I am closing this issue. Sorry<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6364">issues.joomla.org/joomla-cms/6364</a>.</sub>
