### ISSUE TITLE
Category Blog Paging Dispaly

### ISSUE THREAD

**Issue by jawill** [joomla/joomla-cms#6367]
#### Steps to reproduce the issue

Upgrade from 3.3.6 to 3.4

#### Expected result

Category blog paging is vertical with list dots displayed.  The first image was captured immediately before upgrading to 3.4 and the second image was taken immediately after upgrading to 3.4. ![screen shot 2015-03-08 at 20 04 35](http://issues.joomla.org/uploads/1/ece03e4c58efb22a4ff5e8065224c497.gif)

#### Additional comments

![screen shot 2015-03-08 at 20 06 26](http://issues.joomla.org/uploads/1/4b2072edd092416e096f3c7d8ce270a9.gif)

**Comment by bertmert** [comment]
Cannot confirm any issues concerning pagination during updates to 3.4.0

Second image seems to be standard pagination footer of Joomla core (and missing CSS for inlined grouping).
First one seems to be an overriden one (normally/correctly done by html/pagination.php or html/layouts/joomla/pagination/xy.php inside your template folder).

Maybe you made your changes for pagination not in an update secure file?

**Comment by jawill** [comment]
The first image was done right before upgrading to 3.4.  The second one was done right after the upgrade.  No other changes were made to the template or otherwise.  I use a template that uses the Warp framework, but as I stated, everything was working properly prior to the Joomla update and _no_ other changes were made to the website.  It happened on three different websites (all using Warp.)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6367">issues.joomla.org/joomla-cms/6367</a>.</sub>

**Comment by jawill** [comment]
I should also mention, I did not make any changes to paging before or after the upgrade.  I was using paging as it comes from Joomla and the Warp framework without modification.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6367">issues.joomla.org/joomla-cms/6367</a>.</sub>

**Comment by brianteeman** [comment]
Clearly then it is an issue with Warp

On 9 March 2015 at 22:39, jawill <notifications@github.com> wrote:

> The first image was done right before upgrading to 3.4. The second one was
> done right after the upgrade. No other changes were made to the template or
> otherwise. I use a template that uses the Warp framework, but as I stated,
> everything was working properly prior to the Joomla update and *no* other
> changes were made to the website. It happened on three different websites
> (all using Warp.)
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/6367
> <http://issues.joomla.org/tracker/joomla-cms/6367>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6367#issuecomment-77959748>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by bertmert** [comment]
Yes, yootheme confirmed pagination override bug 2 weeks ago.

**Comment by N6REJ** [comment]
I have seen multiple issues where the .css is not being picked up FULLY 
in numerous templates... try adding !important to css to see if that 
cures it.
Bear

**Comment by jawill** [comment]
Thanks to everyone for there help.  I have received a new version of the Warp framework.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6367">issues.joomla.org/joomla-cms/6367</a>.</sub>
