### ISSUE TITLE
Wrong name on flags

### ISSUE THREAD

**Issue by diego065** [joomla/joomla-cms#6374]
Hello everyone!
I just upgrading to joomla 3.4 and I get a very strange issue.. I've got the correct flags displayed (and the redirect also work good) but the title of the images are all wrong except for the Italian language: every flag show English (UK) on hoover!
Same results if I use the drop down menu instead of flags.. all the languages are English (UK), only "Italiano" is correct!
Do you have any suggestion on how to resolve this issue?
Thanks

**Comment by zero-24** [comment]
@diego065 we have issues with multilanguage in 3.4 can you check that all content languages have a access level normaly public?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6374">issues.joomla.org/joomla-cms/6374</a>.</sub>

**Comment by Hackwar** [comment]
I can't confirm this issue. Could it be that you have a template override in your template for the mod_languages module?

**Comment by diego065** [comment]
@zero-24 Yes, all the content (actually just the test article in all the 4 languages) have public access!
@Hackwar I'm using the free template by joomfreak (jf_taman) and I don't have any other issue... 
I repeat, all the links are working good.. it's only the flags that have wrong titles!

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6374">issues.joomla.org/joomla-cms/6374</a>.</sub>

**Comment by diego065** [comment]
![screen shot 2015-03-11 at 13 00 13](http://issues.joomla.org/uploads/1/3512ea167e6b251bb9b84ebc4d824884.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6374">issues.joomla.org/joomla-cms/6374</a>.</sub>

**Comment by Hackwar** [comment]
"I only have one flat tire. The other 3 are fine, so it can't be an issue with the tires." We told you that you should check if there is a template override for the mod_languages module in your template and if that is the case, remove it. If that fixes it, you have to either contact the template dev or fix it yourself. I told you that I tested it on my end and that I looked through the code and that there is nothing obvious that could create such a behavior. So PLEASE check your template.

**Comment by infograf768** [comment]
Tested that template "jf_taman'. It has no override for mod_languages. Although it has an error
```
Notice: Undefined variable: bodyClass in ROOT/templates/jf_taman/index.php on line 198
```
the name of flags is OK.

Can you look at the Content Languages Manager and check the names of these?

**Comment by diego065** [comment]
Thanks @infograf768 !
And also thanks for your suggestion.. I finally found the name in that section!!! But that is strange because it happen after I update to the new version!
Anyway, now I solved the issue!
Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6374">issues.joomla.org/joomla-cms/6374</a>.</sub>
