### ISSUE TITLE
Move "Install from Web" to the last tab position

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#6375]
Right now "Install from Web" shows this message "We are sorry but due..."

There is no defined date when the new "Install from Web" is going to be available.

Meanwhile, to avoid this message, plugin can be moved to the last tab position, just a simple change in webinstaller.xml:

					default="1"

PD: I would send a PR but I cannot find where webinstaller repo is located. https://github.com/emavro/webinstaller?

**Comment by dgt41** [comment]
Try: https://github.com/joomla-extensions/install-from-web-client

**Comment by anibalsanchez** [comment]
Done! https://github.com/joomla-extensions/install-from-web-client/pull/19

**Comment by zero-24** [comment]
Thanks @anibalsanchez i closing here as we have a PR aginst the webinstaller client repo.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6375">issues.joomla.org/joomla-cms/6375</a>.</sub>
