### ISSUE TITLE
Users option tabs do not appear for fa-IR (RTL) language

### ISSUE THREAD

**Issue by MAT978** [joomla/joomla-cms#6379]
While "playing" with JM's PR 6377 in persian language, I discovered that option tabs for users don't appear the way expected...
RTL issue?

#### Steps to reproduce the issue

install Persian language (fa-IR) on staging or 3.4.0
Set Administrator language to Persian
Go to: 'User Manager: Users' -> 'Super User'

#### Expected result

Like for en-GB we should see for fa-IR and be able to use option tabs: "Assigned User Groups" and "Basic Settings" (SC #1)

![screen shot 2015-03-10 at 07 34 01](http://issues.joomla.org/uploads/1/63936918b7a608382ed53d33b4d89061.png)

#### Actual result

For fa-RI the option tabs: "Assigned User Groups" and "Basic Settings" do not appear (SC #2)
![screen shot 2015-03-10 at 07 34 29](http://issues.joomla.org/uploads/1/2ed4a1254c0e362db3f7a8334b9d5e8e.png) 

#### System information (as much as possible)

Windows NT 6.1 build 7601 (Windows 7 Ultimate Edition Service Pack 1) i586
Database Version	5.5.36
PHP Version	5.4.27
Web Server	Apache/2.4.9 (Win32) OpenSSL/0.9.8y PHP/5.4.27
Joomla! Version	Joomla! 3.4.1-dev Development [ Ember ] 24-February-2015 23:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

Browsers: chrome, FF, Yandex

**Comment by infograf768** [comment]
@MAT978 

This, I think, is related to the fact that the pack available is not yet the good one (3.4.0.1). You have installed fa-IR_joomla_lang_full_3.3.6v1.zip
It is due to the js.
See: https://github.com/joomla/joomla-cms/issues/6207

Next available pack should solve it.

**Comment by MAT978** [comment]
@infograf768 
thank you for pointing.
then this can be Closed - thanks
