### ISSUE TITLE
Password length in User Manager not recognized on Reset PW

### ISSUE THREAD

**Issue by gwsdesk** [joomla/joomla-cms#6380]
http://forum.joomla.org/viewtopic.php?f=706&t=876254

I can reproduce that. A Password rest of 4 digits despite being set to '8' is not recognized.

I spoke to Michael Babker on the JBS-Skype and he states:

_just on a quick glance the reset_complete.xml form just needs updated to add the password validation in there, that’s assuming there aren’t any other hacks needed in the controller or model_

**Comment by n9iels** [comment]
confirmed, I make a PR for it in a minute :+1:

**Comment by zero-24** [comment]
Closing as we have a PR by @n9iels https://github.com/joomla/joomla-cms/pull/6382<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6380">issues.joomla.org/joomla-cms/6380</a>.</sub>
