### ISSUE TITLE
Cannot run installation joomla 3.4 on my server

### ISSUE THREAD

**Issue by nov22** [joomla/joomla-cms#6386]
#### Steps to reproduce the issue
go to website
http://www.nov22.nazwa.pl/ok/okna/installation/index.php

#### Expected result

Run the istallation

#### Actual result
Warning: require(/home/nov22/ftp/ok/okna/libraries/ClassLoader.php): failed to open stream: No such file or directory in /home/nov22/ftp/ok/okna/libraries/composer_autoload.php on line 22

Fatal error: require(): Failed opening required '/home/nov22/ftp/ok/okna/libraries/ClassLoader.php' (include_path='.:/usr/share/pear/') in /home/nov22/ftp/ok/okna/libraries/composer_autoload.php on line 22

#### Additional comments
I don't know what to do, Joomla installation is fresh, I copied files twice on the server

**Comment by brianteeman** [comment]
Please use the forum for installation support http://forum.joomla.org
