### ISSUE TITLE
Search for language string produces incomplete list

### ISSUE THREAD

**Issue by GunnarBs** [joomla/joomla-cms#6390]
#### Steps to reproduce the issue
1. Go to Extensions Language Manager.
2. Overrides
3. New (a search box appears at the right)
4. search for 'username' as constant
A result list should appear
5. Click on 'more results'

#### Expected result
All results should appear.
I do not get: MOD_LOGIN_VALUE_USERNAME

If I search for 'value_username', the entry appears, so the search works.

**Comment by bertmert** [comment]
Cannot reproduce

![overri0](https://cloud.githubusercontent.com/assets/11038612/6596895/d66404ce-c7f8-11e4-9a18-873c96b2b3fc.jpg)
![overr1](https://cloud.githubusercontent.com/assets/11038612/6596900/dc3ff308-c7f8-11e4-9d6c-dddc740b45f1.jpg)

**Comment by bertmert** [comment]
Correction!!!!!

Could reproduce it but just sometimes.
First I tested with a Joomla updated from Joomla 3.2 ... ... .. 3.4.0 and XAMPP.
Then newly installed 3.4.0 and XAMPP
Both: Could not reproduce.

Then an online 3.4.0 updated from 2.5.28
Could reproduce.

**Comment by bertmert** [comment]
Addition:
Made a local copy of online page. Could also reproduce on XAMPP.

Checked table #__overrider (this is the caching table for search): MOD_LOGIN_VALUE_USERNAME exists as entry but not displayed as search result..

**Comment by bertmert** [comment]
Addition:
It depends on the number of search results. When "MOD_LOGIN_VALUE_USERNAME" is one of the first 20 hits it'll be displayed. The more-reults link is just displayed once (max. 20 hits). Afterwards it's hidden because somehow a necessary more value is calculated wrongly.

**Comment by bertmert** [comment]
I will provide a PR today. Bug found.

**Comment by GunnarBs** [comment]
I can confirm that your fix works! Hope it goes in the main branch soon.

**Comment by bertmert** [comment]
Please confirm successful test in PR not here. We need 2 good tests there.
