### ISSUE TITLE
Redirect Manager Manual Entries Only

### ISSUE THREAD

**Issue by DaveOzric** [joomla/joomla-cms#6404]
Hello, I am finding a need for the redirect manager but do not want to fill the database with all the auto discovery entries on high traffic sites. Takes too much work to manage and delete the non relevant entries. One site had thousands of entries and deleting them took a long time because changing to all and deleting them crashed the site.

Is there no way to allow this to be enabled but ONLY redirect or add the ones I put in myself? If I enable the plugin it's all or nothing. I have to reorganize some sites menus or even new sites replacing old static/wp sites are in need of redirects. It's just a very useful feature overall but hobbled by this missing setting.

Thank you

#### Additional comments

There is not really a JED option for replacing it or I would use that. Since it appears to be on the list to keep this would be a great new option!

**Comment by zero-24** [comment]
@DaveOzric do you know this option at the plugin itself?

![collect_urls](https://cloud.githubusercontent.com/assets/2596554/6630306/bf282cc0-c917-11e4-82d6-7519956b5345.PNG)

**Comment by DaveOzric** [comment]
I have no such setting on any of my 2.5 or 3.3.6 websites. Is this a 3.4 feature?

![2015-03-12_183812](https://cloud.githubusercontent.com/assets/1801991/6630445/0eb6fe78-c8e7-11e4-80c5-3f312f7a9129.jpg)

**Comment by DaveOzric** [comment]
Wow, that was not mentioned in the Joomla 3.4 features anywhere. I just installed 3.4 and there it is! That is very good news.

Thanks

**Comment by zero-24** [comment]
@DaveOzric 

>Is this a 3.4 feature?

Yes we have may hidden features in 3.4. Maybe you can have a look into the advanced settings you need to enable it at the options form com_redirect. Than you can set the status code for your redirect.

@DaveOzric can you close here if it fix your issue?

**Comment by DaveOzric** [comment]
Yes it's in the new 3.4 plugin settings.
