### ISSUE TITLE
Multilanguage does not work on J3.4

### ISSUE THREAD

**Issue by wildafrica** [joomla/joomla-cms#6415]
#### Steps to reproduce the issue
Install multilanguage on Joomla. I upraded from J3.3.6, Joomla was multilanguage, after upgrade to J3.4 multilanguage does not work.

#### Actual result
Does not work

#### System information (as much as possible)

J3.4, MySql 5.5, PHP 5.4.x, Apache 2.

#### Additional comments

Sorry for my English. After upgrade J3.3.6 to 3.4 multilanguage stop work.

Notice: Undefined index: cs-CZ 

plugins/system/languagefilter/languagefilter.php on line 172

Notice: Trying to get property of non-object in
plugins/system/languagefilter/languagefilter.php on line 172

When I changed languagefilter.php from J3.3 it works with some small errors.

**Comment by brianteeman** [comment]
Please see https://docs.joomla.org/J3.x:Infinite_error_loop_on_multilanguage_sites
