### ISSUE TITLE
UX: Move Next/Back Button during the installation to the bottom

### ISSUE THREAD

**Issue by joomla-agency** [joomla/joomla-cms#6422]
#### Steps to reproduce the issue
Start a fresh Joomla 3.x installation.
Fill out the needed steps. If you use a device with a small screen size (e.g. Netbook,Smartphones, Tablets), you need to fill out for e.g. the Mysql credentials. Now if you reach the bottom of the Page, you need to scroll to top to click Next Button. 

#### System information (as much as possible)
Joomla 3.4.0

**Comment by brianteeman** [comment]
This change would also possibly resolve an accessibility issue that it is
currently impossible to reach the NEXT button without using a mouse

**Comment by sovainfo** [comment]
To avoid needing to scroll to the bottom suggest to fix them or at least have them both top and bottom.

**Comment by joomla-agency** [comment]
The Code has the following effect.
![new_buttons](https://cloud.githubusercontent.com/assets/1765163/6656846/8514c102-cb37-11e4-84b9-5efe830d2d13.png)

**Comment by joomla-agency** [comment]
Or we can make a sticky Menu Version like this: http://getbootstrap.com/2.3.2/examples/sticky-footer.html

**Comment by brianteeman** [comment]
Please see #6444<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6422">issues.joomla.org/joomla-cms/6422</a>.</sub>
