### ISSUE TITLE
Login Joomla logo is not retina proof

### ISSUE THREAD

**Issue by quantz16** [joomla/joomla-cms#6438]
When you see the login screen from Joomla administrator on an Apple computer with a retina display, you can see the Joomla logo is not sharp/retina proof. This problem is also present on a HD display, for example the Nexus 5 with Android.
Maybe there can be used a retina proof logo, or a logo with a higher resolution.

Regards,
Maarten

**Comment by mbabker** [comment]
@jessicadunbar or @chiaraaliotta could one of you (or someone in Marketing) send me updated logos to replace those we're currently using in the CMS?  There are a few graphics at https://github.com/joomla/joomla-cms/tree/staging/images and the Isis template graphics are at https://github.com/joomla/joomla-cms/tree/staging/administrator/templates/isis/images

**Comment by chiaraaliotta** [comment]
Hello Michael,

Thanks  that you asked. I shared the link with the new files to David and
Jess many times, but here you are:

https://drive.google.com/open?id=0B-WMsfRg_wivSV83SzZzZ2tRM2M&authuser=1

Also it was shared recently in my last post about the brand manual.

If you can, please update those links in GitHub with new the new files and
share them with me.
Also if you can update these files in our CMS itself, that it is using the
old Joomla! logo in flat version with a strange registration mark alignment.

Thank you,



2015-03-15 18:06 GMT+02:00 Michael Babker <notifications@github.com>:

> @jessicadunbar <https://github.com/jessicadunbar> or @chiaraaliotta
> <https://github.com/chiaraaliotta> could one of you (or someone in
> Marketing) send me updated logos to replace those we're currently using in
> the CMS? There are a few graphics at
> https://github.com/joomla/joomla-cms/tree/staging/images and the Isis
> template graphics are at
> https://github.com/joomla/joomla-cms/tree/staging/administrator/templates/isis/images
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6438#issuecomment-81129867>.
>



-- 



*Chiara Aliotta*

*Founder & Art Director at Until SundayJoomla! Brand Manager *

www.untilsunday.it

**Comment by mbabker** [comment]
Thanks!  I'll try to work on updating this stuff for the CMS.

**Comment by ralain** [comment]
Consider adding an srcset attribute to the relevant img tags and link to the 2x images from there. I think most of the browsers that matter support it by now, or will in the near future.

**Comment by pe7er** [comment]
You created this issue sometime ago. As no one else has shown any interest in providing the code, I am closing this issue at this time. 
If code is provided (a pull request) it can always be re-examined.

BTW: There's an option to configure the admin logo in the Joomla back-end template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6438">issues.joomla.org/joomla-cms/6438</a>.</sub>
