### ISSUE TITLE
Language names appear with parentheses in wrong place

### ISSUE THREAD

**Issue by credenceweb** [joomla/joomla-cms#6445]
#### Steps to reproduce the issue
If the site is using only left to right (LTR) languages, the languages names in the admin login drop-down list appear in the following way: English (en-GB) or French (fr).

![login_ok_ltr_only_001](https://cloud.githubusercontent.com/assets/11488582/6656867/bebbefb2-cb0e-11e4-9204-221413e064a9.png)

If a right -to-left reading language is the default admin language to the site (such as Persian or Arabic), the LTR languages then do not display correctly. Instead they show with two left parentheses, one in the wrong place, as such: 
(English (en-GB or (French (fr
![login_not_ok_arabic_default_admin_rtl](https://cloud.githubusercontent.com/assets/11488582/6656869/cec7cc64-cb0e-11e4-9191-93fe4d714315.png)
![login_not_ok_persian_default_admin_rtl](https://cloud.githubusercontent.com/assets/11488582/6656870/d2262478-cb0e-11e4-84f7-2913a4958a7a.png)

#### Expected result
The display needs to be corrected so the LTR languages show in the following way:

English (en-GB) or French (fr) 

#### System information (as much as possible)
This has been tested on Joomla staging

**Comment by brianteeman** [comment]
I can confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6445">issues.joomla.org/joomla-cms/6445</a>.</sub>

**Comment by brianteeman** [comment]
I am not sure of the correct way to resolve this but two useful resources explaining the reason etc can be found here

http://stackoverflow.com/questions/5741522/brackets-displays-wrongly-for-right-to-left-display-style
http://stackoverflow.com/questions/18375417/in-right-to-left-languagelike-arabic-and-hebrew-bracket-reversed

Its all to do with the fact that you are displaying an LTR string in an RTL document<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6445">issues.joomla.org/joomla-cms/6445</a>.</sub>

**Comment by infograf768** [comment]
There is no way that I know to solve this well known issue.

**Comment by brianteeman** [comment]
Please see #6449 for a solution<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6445">issues.joomla.org/joomla-cms/6445</a>.</sub>
