### ISSUE TITLE
Administration menu does not show all entries for submenus on mobile

### ISSUE THREAD

**Issue by GunnarBs** [joomla/joomla-cms#6453]
#### Steps to reproduce the issue

You can use a default install with Isis as administrator template. I just tried it on the 90 Minute test drive available on Joomla Homepage.

Open/Login to Administration. Resize your browser window so that the mobile menu appears.

Open the mobile menu. All main menu entries will be shown. 
Open the sub-menu components. Only the first entries will be shown.

Reason for this is a fixed height: div class="nav-collapse in collapse" style="height: 256px;"

Now the interesting part: 
Close the menu and open it again. Now the menu is usable, the above line has changed to:
div class="nav-collapse in collapse" style="height: auto;"
To reset to error constellation just reload the page.

So, I guess there is a little bug that the code responsible for setting auto is not called on first load.

#### Expected result
All sub-menu items visible.

#### Actual result

Only items visible which fit in the first 256px of menu.

#### System information (as much as possible)

3.4.0

**Comment by JoomliC** [comment]
Hello @GunnarBs this is fixed for 3.4.1, and the patch is here : http://issues.joomla.org/tracker/joomla-cms/6298
;-)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6453">issues.joomla.org/joomla-cms/6453</a>.</sub>

**Comment by GunnarBs** [comment]
Yes, fix works. Thanks for pointing out. I used administrator in my search...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6453">issues.joomla.org/joomla-cms/6453</a>.</sub>
