### ISSUE TITLE
JFormFieldTextArea maxlength support

### ISSUE THREAD

**Issue by fruppel** [joomla/joomla-cms#6459]
Hi,

is there a reason why JFormFieldTextArea does not support the maxlength attribute?
Can I add it?

**Comment by zero-24** [comment]
@fruppel feel free to open a PR with the needed changes. So we can discuss there.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6459">issues.joomla.org/joomla-cms/6459</a>.</sub>

**Comment by zero-24** [comment]
Hehe there was a PR for that here: https://github.com/joomla/joomla-cms/issues/6460 So I'm closing here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6459">issues.joomla.org/joomla-cms/6459</a>.</sub>
