### ISSUE TITLE
Install an extension from Web - (Not Working)

### ISSUE THREAD

**Issue by Yiannistaos** [joomla/joomla-cms#6464]
Hello,

From the top menu -> Extensions -> Extension Manager -> Install -> Install from the web

I've get this message "We are sorry but due to technical reasons we have had to disable the Install from Web Service. We are working to get it back online as soon as possible. To find extensions please use the Joomla! Extensions Directory at http://extensions.joomla.org".

Is this an issue that will resolved in version 3.4.1?

Thanks.
![extension manager install](https://cloud.githubusercontent.com/assets/8467542/6675747/73e9c18a-cc2b-11e4-9197-95d8c74181c9.png)

**Comment by brianteeman** [comment]
This issue is unrelated to the joomla version

**Comment by zero-24** [comment]
@Yiannistaos This is a known issue. But nothing we can fix at the core. The working Group behind the Install from Web feature is working on it.

As it is no Joomla Core Bug I closing here. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6464">issues.joomla.org/joomla-cms/6464</a>.</sub>
