### ISSUE TITLE
Request a filter for Module Manager

### ISSUE THREAD

**Issue by iamkeng** [joomla/joomla-cms#6468]
#### Steps to reproduce the issue
I would like to request more a filter, filter by assigned menu for Module Manager(module list page). When new user install Joomla and use Sample data and input the content by modify existing article. Somtime he/she want to know what modules are assigned by one of menu that he/she want to know. Thus I think this filter is necessary to use.

#### Expected result
The users can filter by 'Assigned Menu' that he/she want to filter.

**Comment by iamkeng** [comment]
I try to add this filter and this is the files that I done, you can download from http://demo.colorpack.net/module-manager-files.zip . Please try them.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6468">issues.joomla.org/joomla-cms/6468</a>.</sub>

**Comment by infograf768** [comment]
Does not work here.

**Comment by iamkeng** [comment]
@infograf768  What's the results that you got?

**Comment by bertmert** [comment]
@iamkeng 
- Install current staging Joomla plus test sample data
- Add your code to files modules.php and view.html.php
- Goto Module Manager
- Check module "Top Menu (Atomic Template) ". 2 assigned menu items. Close module.
- In your filter field search for "Typography Atomic" and select.
- Page reloads. Nothing changed.
- Your filter returns to "nothing selected".

**Comment by iamkeng** [comment]
I include the modules that assigned to  'All' menus too.

**Comment by bertmert** [comment]
Believe us. Nothing happens when you select a menu item with your filter. 

There are several modules afterwards in the list with entry "Selected" in column "Pages" that are NOT assigned to menu item "Typography Atomic".

Create a Pull Request! Then it will be easier to test/discuss this issue.

**Comment by iamkeng** [comment]
What is  a Pull Request? How can I do that?

**Comment by brianteeman** [comment]
https://docs.joomla.org/My_first_pull_request_to_Joomla!_on_Github

**Comment by iamkeng** [comment]
@brianteeman  I done the steps from your link and commited already but I cannot push my codes. Am I finished all steps?

**Comment by brianteeman** [comment]
@wilsonge @roland-d can you help out @iamkeng with making the Pull Request please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6468">issues.joomla.org/joomla-cms/6468</a>.</sub>

**Comment by Bakual** [comment]
I like that doc better for first time users: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

Aside that, you should not deal with https://github.com/joomla/joomla-platform. That's an outdated one. Work with the repo we are here (https://github.com/joomla/joomla-cms)

**Comment by andrepereiradasilva** [comment]
Please test https://github.com/joomla/joomla-cms/pull/9987

**Comment by brianteeman** [comment]
Closed as this has now been addressed with #9987<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6468">issues.joomla.org/joomla-cms/6468</a>.</sub>
