### ISSUE TITLE
Count of articles can't be configured at com_contacts contact form

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#6474]
#### Steps to reproduce the issue

- Create a new contact
- assign it to a user (e.g. site admin)
- create more than 10 items with the site admin (or the user you choose) e.g. 12
- enable the "Show Articles" option for the contact
- see the contact at the frontend
- you see only 10 items not all and can't configure this value

#### Expected result

It is possibel to configure the com_contact article count for the article tab.

#### Actual result

Currently it is not possibel to configure the com_contact article count for the article tab.

#### System information (as much as possible)

ATM this value (10) is hardcoded:
https://github.com/joomla/joomla-cms/blob/staging/components/com_contact/models/contact.php#L399
https://github.com/joomla/joomla-cms/blob/staging/components/com_contact/models/contact.php#L348-401

#### Additional comments

See: http://www.joomla-bugs.de/forum/index.php/topic,655.0.html
and
http://forum.joomla.de/index.php/Thread/136-Autorbeitr%C3%A4ge-Anzahl-10stk-erh%C3%B6hen/

**Comment by bertmert** [comment]
OK, I will start a PR tomorrow. Please stop me if somebody has started one yet! A dozen files to change...

**Comment by bertmert** [comment]
See PR https://github.com/joomla/joomla-cms/pull/6485

**Comment by zero-24** [comment]
Closing as we have a PR thanks @bertmert
