### ISSUE TITLE
Can NOT install RC1

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#6487]
#### Steps to reproduce the issue
Use joomla updater on a clean install of 3.4 to upgrade to 3.4rc1

#### Expected result
successful update

#### Actual result

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'admin://components/com_admin/postinstall/languageaccess340.php', 'admin_postinst' at line 2 SQL=INSERT INTO `zg5mu_postinstall_messages` (`extension_id`, `title_key`, `description_key`, `action_key`, `language_extension`, `language_client_id`, `type`, `action_file`, `action`, `condition_file`, `condition_method`, `version_introduced`, `enabled`) VALUES (700, 'COM_CPANEL_MSG_LANGUAGEACCESS340_TITLE', 'COM_CPANEL_MSG_LANGUAGEACCESS340_BODY', '', 'com_cpanel', 1, 'message', ', '', 'admin://components/com_admin/postinstall/languageaccess340.php', 'admin_postinstall_languageaccess340_condition', '3.4.1', 1);]

**Comment by infograf768** [comment]
See
https://github.com/joomla/joomla-cms/pull/6478

**Comment by brianteeman** [comment]
Knew I had seen it somehwere - thanks
