### ISSUE TITLE
Logo corrupt?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#6491]
In the admin the joomla logo being used in the top right hand corner has been trimmed and does not contain the entire image
administrator/templates/isis/images/logo.png

This is a screenshot of the logo zoomed to show the issues.If you look you will see it is cropped at the bottom and at the top left it appears to be missing part of the green

![screen shot 2015-03-18 at 10 13 18](http://issues.joomla.org/uploads/1/6df838381db2197549b1d958f5652f0e.png)

**Comment by brianteeman** [comment]
I am assuming that this is something to do with the way the image has been resized<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6491">issues.joomla.org/joomla-cms/6491</a>.</sub>

**Comment by mbabker** [comment]
The replacement in https://github.com/joomla/joomla-cms/pull/6447/files should be a bit better cropped I think.  Care to compare with that?

**Comment by brianteeman** [comment]
million times better

On 18 March 2015 at 15:37, Michael Babker <notifications@github.com> wrote:

> The replacement in https://github.com/joomla/joomla-cms/pull/6447/files
> should be a bit better cropped I think. Care to compare with that?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6491#issuecomment-83023859>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
closing in favour of #6447<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6491">issues.joomla.org/joomla-cms/6491</a>.</sub>
