### ISSUE TITLE
Top menu disappear in Joomla administrator 3.4 !

### ISSUE THREAD

**Issue by JRelland** [joomla/joomla-cms#6496]
#### Steps to reproduce the issue
Perhaps from this action: I changed the "Super Users" label into a French expression "Administrateur Système".
Note that the administrator page is ok with the "Administrator" account. I renamed Super Users but always the pb!

#### Expected result
I should have a administrator page with the top menu :)

#### Actual result
See the screenshot.
T![screen shot 2015-03-18 at 12 28 58](http://issues.joomla.org/uploads/1/e6f4be2cd43993da5e63ed44ede4fc1f.png)
I have lost the top menu (except link to visualise the site and user account link (on the right) and I have lost the left menu.
I can naviguate in the content page part.

#### System information (as much as possible)
The same with Chrome and FireFox.
Windows 8.1, HP Pavillion
Remote hosting (French OVH).
Site Information

    OS Linux w
    PHP 5.4.38
    MySQLi 5.1.73-2+squeeze+build1+1-log
    Heure 18:26
    Cache Désactivé
    GZip Désactivé
    Utilisateurs 3
    Articles 18

#### Additional comments

Note that admin functionalies are ok with the "Administrator" account (but no more with the "Super Users" Account !

### Thank you for your time and consideration
José: jose.relland@gmail.com
France

**Comment by dgt41** [comment]
Do you have any errors logged in your browser’s console?
Have you tried to clear your browser’s cache or try another browser?

**Comment by Fedik** [comment]
screenshot from K2 component 
can you please try on Article form?

**Comment by brianteeman** [comment]
This really is a question for the forum as it is for support on a specific site. As you have already posted there I am closing this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6496">issues.joomla.org/joomla-cms/6496</a>.</sub>

**Comment by JRelland** [comment]
Hi, thank you for your time and consideration.
I solved this problem by an intervention in the database. I modified Super User account labels and, I think, I confused Super user and Super User(s). In the database I corrected the right label and everything was ok!

@dgt41  Yes I clear the browser’s cache and try another browser. Nothing
@Fedik With article, same screen (without top menu)

I understand this is a weel-know issue. 
I supposed, the pb come from you can modify already affected ACL label and this modification is not propogated in the user account.

 Thank you again for your time.
