### ISSUE TITLE
Images & Links for articles missing in frontend editing

### ISSUE THREAD

**Issue by htmgarcia** [joomla/joomla-cms#6506]
By creating/editing an article in frontend the "Images & links" tab is missing.

I assume this may be reported before, but I didn't find a issue related.

**Comment by dgt41** [comment]
Check the user’s rights (ACL)!

**Comment by bertmert** [comment]
Did you activate it in com_content options?
/administrator/index.php?option=com_config&view=component&component=com_content

And maybe setting is disabled in article > Tab Configure Edit Screen

**Comment by brianteeman** [comment]
The default is for this not to be enabled on the front end

![screen shot 2015-03-19 at 12 27 15](http://issues.joomla.org/uploads/1/d9f1b19bed2915497f0262fc431b05f1.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6506">issues.joomla.org/joomla-cms/6506</a>.</sub>

**Comment by htmgarcia** [comment]
Thanks guys!

That happen when a feature is not being used :D I'm glad is already in the core.

**Comment by brianteeman** [comment]
Its been there for a very very very long time :d

On 19 March 2015 at 23:29, Valentín <notifications@github.com> wrote:

> Thanks guys!
>
> That happen when a feature is not being used :D I'm glad is already in the
> core.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6506#issuecomment-83802927>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by htmgarcia** [comment]
Maybe better keep it enable by default then :)

**Comment by brianteeman** [comment]
I dont remember the reasoning for the default behaviour being the way it is
- sorry

I assume there was a good reason

On 20 March 2015 at 15:41, Valentín <notifications@github.com> wrote:

> Maybe better keep it enable by default then :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6506#issuecomment-84051948>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
