### ISSUE TITLE
com_tags missing a global float option

### ISSUE THREAD

**Issue by modernmagic** [joomla/joomla-cms#6511]
This does not appear to be working.  I am still trying to figure out why.

<?php $imgfloat = (empty($images->float_intro)) ? $this->params->get('float_intro') : $images->float_intro; ?>
				<div class="pull-<?php echo htmlspecialchars($imgfloat); ?> item-image">

I also believe com tags / options should have a global default for the floats.

**Comment by brianteeman** [comment]
What is not working? What are you expecting to happen? What actually happens? Where are you using this code?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6511">issues.joomla.org/joomla-cms/6511</a>.</sub>

**Comment by modernmagic** [comment]
Sorry for the noob posting.  

1. There does not appear to be a "global setting" for the tag image float even though it is an option in the dropdown menu.
![screen shot 2015-03-23 at 10 11 27 am](https://cloud.githubusercontent.com/assets/2553410/6786494/db3d1f58-d149-11e4-9e2f-4f230d4d8b1c.png)
2. Since there is no "Global settings", that options does not apply a direction.
3. That code was copied from  components/com_tags/views/tags/tmpl/default_items.php 

Again sorry, just trying to help but I am not a developer, but more of an implementer/agency.

**Comment by brianteeman** [comment]
Thanks for clarifying things and reporting the issue. The more information
you provide the easier it is for people to see what isnt working and what
needs to be done

On 23 March 2015 at 17:52, modernmagic <notifications@github.com> wrote:

> Sorry for the noob posting.
>
>    1. There does not appear to be a "global setting" for the tag image
>    float even though it is an option in the dropdown menu. [image: screen
>    shot 2015-03-23 at 10 11 27 am]
>    <https://cloud.githubusercontent.com/assets/2553410/6786494/db3d1f58-d149-11e4-9e2f-4f230d4d8b1c.png>
>    2. Since there is no "Global settings", that options does not apply a
>    direction.
>    3. That code was copied from
>    components/com_tags/views/tags/tmpl/default_items.php
>
> Again sorry, just trying to help but I am not a developer, but more of an
> implementer/agency.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6511#issuecomment-85122812>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by locii** [comment]
Hi Jeff,

Thats possibly a template issue. Does it happen with Protostar as well as the template you are using?

**Comment by modernmagic** [comment]
Since there is no Global float settings for images, it does not appear that this would be a template issue.
![screen shot 2015-03-25 at 9 18 02 am](https://cloud.githubusercontent.com/assets/2553410/6829323/02970a82-d2d0-11e4-92cb-43ff5e085827.png)

But, yes if I switch to protostar the images do not float unless each tag is set to float in its own "Edit Tag/Images options".

**Comment by modernmagic** [comment]
I see that I have created some confusion with a poor issue title.  I have changed it to "com_tags missing a global float option"

**Comment by brianteeman** [comment]
Closing this really old issue with a PR #11401<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6511">issues.joomla.org/joomla-cms/6511</a>.</sub>
