### ISSUE TITLE
Package installation in Joomla 3.4

### ISSUE THREAD

**Issue by jayss** [joomla/joomla-cms#6523]
#### Steps to reproduce the issue
Create a clean new joomla site in localhost, install a package.

#### Expected result
Install successfully.

#### Actual result

Copy failed!

#### Additional comments
I check that there is not a folder named 'packages' under folder 'administrator/manifests', so that make copy failed. I have to create this folder manually to make the installation finished.

**Comment by brianteeman** [comment]
Please provide an example package that fails. Clearly this is not a general
issue as everyday thousands of packages are installed

**Comment by Fedik** [comment]
I had similar issue on clean installation 3.4 before, and fixed it in the same way as described by @jayss  (create folder named 'packages' under folder 'administrator/manifests')

but I thought it something wrong with my hosting, so I was not very concerned for it :smile: 
unfortunately I do not remember what the package I tried :rabbit:

**Comment by infograf768** [comment]
The folder exists in core and releases:
https://github.com/joomla/joomla-cms/tree/staging/administrator/manifests

**Comment by brianteeman** [comment]
I wonder if it is related to #6180<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6523">issues.joomla.org/joomla-cms/6523</a>.</sub>

**Comment by Fedik** [comment]
@infograf768 but I think on clean installation Joomla do not install `pkg_weblinks.xml` so can be that why it fail ... just theory, currently I cannot confirm ... will need to try clear installation with latest RC build

**Comment by infograf768** [comment]
Do you mean we have to include an index.html in the folder as we do for tmp and logs ?

**Comment by brianteeman** [comment]
Ah - that would make sense. The empty folder was created for me without a problem but as we already know there can be problems creating empty folders on some servers then it would make sense that we do add the index.html to this folder as well

**Comment by brianteeman** [comment]
Created a quick PR #6524 to add the index.html file to the manifests folder. This should therefore ensure that the manifests folder is always created<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6523">issues.joomla.org/joomla-cms/6523</a>.</sub>

**Comment by Bakual** [comment]
Closing as PR is merged.
