### ISSUE TITLE
Field type "media" inside "Repeatable" field does not show preview

### ISSUE THREAD

**Issue by Thammada** [joomla/joomla-cms#6530]
If a field type "media" is inside "repeatable" field, when the preview attribute of "media" field is set to "true" of "tooltip" no image is previewed when a file is selected.

**Comment by zero-24** [comment]
@Thammada can you provide example code?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6530">issues.joomla.org/joomla-cms/6530</a>.</sub>

**Comment by Fedik** [comment]
I can confirm it,
@zero-24 as example you can use xml from that pull #3574

I have no idea how it can be fixed, without another dirty hack :rabbit:

**Comment by jrmcar** [comment]
Hi,
I'm a student, interested in joomla and i would like to contribute (first time).
I don't really understand how to re-create the bug. Can someone help me please ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6530">issues.joomla.org/joomla-cms/6530</a>.</sub>

**Comment by Thammada** [comment]
@zero-24  the following xml snippet can be used as an example
```xml
<field name="test" type="repeatable" icon="list"
        label="Test" description="Test descr"
        default=""
        maximum="5">
    <fieldset hidden="true" repeat="true">
        <field name="test_media" type="media" directory=""
            label="media" description="test_media"/>
    </fieldset>
</field>
```

The issue is caused by the function `incresseAttrName` (should be increaseAtrrName by the way) in /media/system/js/repeatable.js which renames all input fields to avoid duplicate input ids by appending an integer suffix. However the code which is used to update the preview of the `type="media"` also use suffixes like `_preview_empty` and `_preview_img`. 

For example `id="field_name"` becomes `id="field_name-1"` and `id="field_name_preview_img"` becomes `id="field_name_preview_img-1"` but the preview function looks for `id="field_name_preview-1_preview_img"`

I suggest fixing in repeatable.js by using a prefix instead of suffix to prevent duplicate ids, would there be another conflict in that case?

**Comment by wilsonge** [comment]
I'm going to close this issue in favour of #6882 which is the same issue but has a more detailed conversation in - to keep things in one place :)
