### ISSUE TITLE
Iframe not working with standard templates

### ISSUE THREAD

**Issue by MAD-King** [joomla/joomla-cms#6533]
#### Steps to reproduce the issue
I have editor off. When placing an Iframe e.g.

<iframe style="width:120px;height:240px;" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" src="//ws-na.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=US&source=ss&ref=ss_til&ad_type=product_link&tracking_id=theangger-20&marketplace=amazon&region=US&placement=B00N3PVU1C&asins=B00N3PVU1C&linkId=LTVXKQK3LGRBH52J&show_border=true&link_opens_in_new_window=true">
</iframe>

into a content, code is there, but not showing on frontend with Beez3 and Protostar template.
#### Expected result
Iframe should show up on frontend

#### Actual result
Not showing anything on frontend

#### System information (as much as possible)

PHP Built On 	Linux gator4153.hostgator.com 3.12.35.1418868451 #1 SMP Wed Dec 17 20:10:32 CST 2014 x86_64
Database Version 	5.5.40-36.1
Database Collation 	utf8_unicode_ci
PHP Version 	5.4.38
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.4.0 Stable [ Ember ] 24-February-2015 23:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 

#### Additional comments
Tried it with latest versions of FF, IE, Chrome and PaleMoon.

**Comment by brianteeman** [comment]
Are you doing this as a Super User?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6533">issues.joomla.org/joomla-cms/6533</a>.</sub>

**Comment by MAD-King** [comment]
Yes, from the backend.

**Comment by vdespa** [comment]
Could not replicate the issue in the staging branch. I have tried this as Super User, with no editor. I have used an iframe from YouTube. Had no issues saving or displying on the website. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6533">issues.joomla.org/joomla-cms/6533</a>.</sub>
