### ISSUE TITLE
Upload for component does not accept 7zip compressed files.

### ISSUE THREAD

**Issue by shadow-kun** [joomla/joomla-cms#6536]
#### Steps to reproduce the issue
get a component, go add to archive, have it set to compress. Upload via com_installer. 

#### Expected result
To install a component

#### Actual result

Errors can't read file.

#### System information (as much as possible)

Dreamhost hosting server. Database seperated on to own system. Using super user to upload.

**Comment by brianteeman** [comment]
are you referring to files archived as .7z

If so then they are not supported and cannot be supported as there is no
server side support that can be guaranteed to be present

On 22 March 2015 at 09:28, shadow-kun <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> get a component, go add to archive, have it set to compress. Upload via
> com_installer.
> Expected result
>
> To install a component
> Actual result
>
> Errors can't read file.
> System information (as much as possible)
>
> Dreamhost hosting server. Database seperated on to own system. Using super
> user to upload.
> Additional comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6536>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by shadow-kun** [comment]
No, zip files created with 7zip<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6536">issues.joomla.org/joomla-cms/6536</a>.</sub>

**Comment by brianteeman** [comment]
Can you provide an example zip file please

**Comment by shadow-kun** [comment]
http://beta.shadowreaper.net/com_events.zip<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6536">issues.joomla.org/joomla-cms/6536</a>.</sub>

**Comment by brianteeman** [comment]
Sorry this is not a joomla problem - I cant extract that zip file on my Mac either using the native mac tools<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6536">issues.joomla.org/joomla-cms/6536</a>.</sub>

**Comment by shadow-kun** [comment]
Fair enough< I think I figured it out just then, it was in deflate64 or the standard deflate compression. Please close this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6536">issues.joomla.org/joomla-cms/6536</a>.</sub>

**Comment by brianteeman** [comment]
Closed as requested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6536">issues.joomla.org/joomla-cms/6536</a>.</sub>
