### ISSUE TITLE
Joomla Update 3.4.1 and Virtuemart

### ISSUE THREAD

**Issue by MAD-King** [joomla/joomla-cms#6537]
#### Steps to reproduce the issue
After updating the buttons in the product section on VM 3.0.6.2 do not work anymore. Cannot save, cancel, or save & close.

#### System information (as much as possible)
PHP Built On 	Linux gator4153.hostgator.com 3.12.35.1418868451 #1 SMP Wed Dec 17 20:10:32 CST 2014 x86_64
Database Version 	5.5.40-36.1
Database Collation 	utf8_unicode_ci
PHP Version 	5.4.38
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by Bakual** [comment]
Did you ask the developers of VM first? Maybe they have more insight in what went wrong in their code.
My first bet is that they somehow rely on MooTools being loaded without loading it themself.

**Comment by MAD-King** [comment]
I also reported this bus at the VM dev site.

**Comment by dgt41** [comment]
I will suggest an easy solution:
copy layouts/joomla/toolbar to administrator/templates/isis/html/layouts/joomla/toolbar
edit base.php
insert `JHtml::_('behavior.framework');` after `defined('_JEXEC') or die;`
Problem solved BUT you are loading mootools every time that the toolbar is rendered 😕

**Comment by brianteeman** [comment]
https://docs.joomla.org/Bug_and_Issue_Tracker_Priority
Reset to correct level<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6537">issues.joomla.org/joomla-cms/6537</a>.</sub>

**Comment by gwsdesk** [comment]
Sorry but this is a non Jooomla issue and should be handled by VM?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6537">issues.joomla.org/joomla-cms/6537</a>.</sub>

**Comment by MAD-King** [comment]
You are right. I restored it to Joomla 3.4.0 with VM 3.4.0.6 on it and the same issue. It is definitely VM.
Thank you
