### ISSUE TITLE
Reset password page contains label twice.

### ISSUE THREAD

**Issue by islavi** [joomla/joomla-cms#6538]
#### Steps to reproduce the issue
1. Perform reset password
2. The page where user insert new password and confirm password contains the label: "To complete the password reset process, please enter a new password." twice.

#### Expected result
The label should appear once, only for the fieldset

#### Actual result
The label appears twice (for each field in the fieldset.

#### Additional comments
The problem is in: components\com_users\views\reset\tmpl\complete.php
Need to move the line: <p><?php echo JText::_($fieldset->label); ?></p> 
above <fieldset> element.

**Comment by zero-24** [comment]
@islavi can you send you change as PR aginst staging with the needed changes? https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by zero-24** [comment]
Closing as we have a PR by @dneukirchen here: https://github.com/joomla/joomla-cms/pull/6540 Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6538">issues.joomla.org/joomla-cms/6538</a>.</sub>
