### ISSUE TITLE
Logout redirect bug with Joomla 3.4.1

### ISSUE THREAD

**Issue by Ruud68** [joomla/joomla-cms#6549]
Hi,
yesterday upgraded my 3.4 site to 3.4.1. Today I noticed that there is a bug with the logout redirection.

I have set my login module to redirect to my home page.
In version 3.4 the redirect goes to my url/
In version 3.4.1 the redirect goed to /component/content/article?id=8

I reverted to 3.4 (restore) and the redirection was working okay again.
I have attached screen captures to show that this not only impacts the url but also 'defaces' the website :(

correct redirect:
![34redirect](https://cloud.githubusercontent.com/assets/2733197/6777272/524cb286-d148-11e4-8c16-0b1a59dc7dc6.png)

incorrect redirect:
![341redirect](https://cloud.githubusercontent.com/assets/2733197/6777275/5bcc267a-d148-11e4-969e-d437acc32ba9.png)

**Comment by infograf768** [comment]
This could be related to
https://github.com/joomla/joomla-cms/pull/6034

**Comment by Ruud68** [comment]
Hi, tested #6542 and although the redirected page looks better, the url is stil wrong:
e.g. on another site it redirects to: https://mydomain/blog-overzicht?view=categories
where it should redirect to https://mydomain/blog-overzicht

**Comment by rdeutz** [comment]
Confirmed, I also see a difference in the menu item link. With Testdata I have

**in 3.4.0**
Home == "index.php"

**in 3.4.1**
Home == "index.php?option=com_content&view=article&id=24&Itemid=435"

**Comment by wilsonge** [comment]
@Hackwar looks like a routing issue (although not certain by any means on that)

**Comment by rdeutz** [comment]
revert #6034 doesn't solve this problem, it seems that the change (problem) is the home URL. It redirects to the home page and that is usually "index.php" or "/". For the test data that is the same as "index.php?option=com_content&view=article&id=24&Itemid=435" because that is the link behind it. So as I said 

> in 3.4.0
> Home == "index.php"
> 
> in 3.4.1
> Home == "index.php?option=com_content&view=article&id=24&Itemid=435"

**Comment by rdeutz** [comment]
it is a changed behaviour of JRoute for the home page

**Test Data**
Itemid=435 is the homepage 

JRoute::_('index.php&Itemid=435');

for 3.4.0 it returns "index.php"
and for 3.4.1 it returns "index.php?option=com_content&view=article&id=24&Itemid=435"

**Comment by Ruud68** [comment]
it's not 'limited' to the homepage but to every menu entry that you redirect to:
I have a menu 'blog-overzicht' that logout redirects to, so my url should be [mydomain]/blog-overzicht but it redirects to [mydomain]/component/cjblog/?view=categories

**Comment by GJM52355** [comment]
Since our update to Joomla! 3.4.1 we do have the same issue like Ruud68. In our case both redirections, the login as well as the logout, are not working correct. Today I have installed the VTEM Login-module, but no change.

**Comment by cogfactory** [comment]
Having the same issue, but with login redirect.  It directs to the long form URL, and not the SEF URL like it did in version 3.4.0 and previous.  Are versions tested before they are released?

**Comment by philowantage** [comment]
Having same issue as cogfactory.  Both login and logout redirects wrong with Joomla! 3.4.1.  Worked ok with 3.4.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6549">issues.joomla.org/joomla-cms/6549</a>.</sub>

**Comment by Hackwar** [comment]
@cogfactory yes, releases are being tested. However, with several thousand files and most likely infinite combinations of features and settings, not everything can be tested 100%.

I was the one that rewrote the helper of mod_login here #6034 and for some of this issue I have to take the blame. However I also have to say that I actually thought that this would be merged into 3.5 and not into a patch release. Looking at the code, I think #6542 should fix the problem. Please test if that solves your issue.

**Comment by philowantage** [comment]
@Hackwar Yes, https://github.com/joomla/joomla-cms/pull/6542 fixed my issues on a production site. i.e. Both login and logout redirects.  Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6549">issues.joomla.org/joomla-cms/6549</a>.</sub>

**Comment by cogfactory** [comment]
@Hackwar Will 6542 disrupt a live website?

**Comment by Hackwar** [comment]
@cogfactory no. But you should know how to apply such a patch.

**Comment by Ruud68** [comment]
Hi, another use case where it is going wrong:
I have a menu item: Titel / kantelingsalfabet that is a menu item alias for menu entry 'kantelingsalfabet' that displays a 'category blog'

the reason I want this is for seo purposes: I do not want the url to be [mydomain]/titel/kantelingsalfabet but [mydomain]/kantelingalfabet.

Works like a charm :)

but. when I set the logout redirect (for testing) to the menu item 'Titel / kantelingsalfabet' It redirects me to [mydomain]/?Itemid=

when I set the redirect to menu entry that is the actual blog category, then I get really unexpected behaviour.
the redirect url = [mydomain]/in-het-nieuws/24-titels/het-kantelingsalfabet
the 'in-het-nieuws' was the menu entry I was on when I pressed logout: so it constructs an redirect url of where I was with where i should be going to.....

So definitely something wrong...

**Comment by Hackwar** [comment]
Menu item alias menu items (what a cool name) are not able to route anywhere. They are an alias, not another menu item. So creating a menu item alias with title "kantelingsalfabet" will not create a url /kantelingsalfabet. Otherwise we would have the duplicate content issue that we are actually trying to avoid with the menu item alias.

Regarding your other problem: Do you get that behavior when #6542 is applied to that site?

**Comment by Ruud68** [comment]
response in #6542 :)

**Comment by cogfactory** [comment]
#6542 Solved my issue.  Thank you for your input and support.  Joomla rocks!

**Comment by GJM52355** [comment]
Since I am a Joomla user only and not familiar with the application of patches, can I expect the issue being solved with Joomla 3.4.2?

**Comment by wilsonge** [comment]
We merge the patches as soon as we have two positive tests on an issue. Assuming we get these tests then yes it will be solved in 3.4.2.

**Comment by GJM52355** [comment]
Thank You!

**Comment by infograf768** [comment]
see:
https://github.com/joomla/joomla-cms/pull/6542#issuecomment-86600970

for the right code to test

**Comment by Ruud68** [comment]
fix in here: https://github.com/joomla/joomla-cms/pull/6542#issuecomment-86489519 tested and can confirm that this is working correctly
