### ISSUE TITLE
Frontend editing: Save & Close Button

### ISSUE THREAD

**Issue by joomla-agency** [joomla/joomla-cms#6552]
CMS: Joomla 3.4.1
Actual Situation:
If you edit an article in the Frontend View and click on "Save" the article get saved and return back to the article. In the Joomla Backend we have an another behaviour. The "Save" button saves the changes article. The "Save and Close" Button brings you back to the Article Liste view.

Propose:
Can the Frontend editing "Save" Button act like the backend button? And can we add additionaly a "Save and Close" Button for the Frontend Editing? 

![frontend](https://cloud.githubusercontent.com/assets/1765163/6778990/0e35e24c-d158-11e4-904a-19deb7f03786.png)

**Comment by brianteeman** [comment]
Feel free to submit a Pull Request with your proposed code

**Comment by brianteeman** [comment]
In the absence of any PR or comments on this issue in 8 months I am closing this at this time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6552">issues.joomla.org/joomla-cms/6552</a>.</sub>
