### ISSUE TITLE
Ajax calls do not work when calling ImportPlugins in controller

### ISSUE THREAD

**Issue by MartinTop** [joomla/joomla-cms#6553]
#### Steps to reproduce the issue
1. Create a function in a controller.
2. Add JPluginHelper::importPlugin( 'yoodiy' ); to it
3. Output a json encoded string 
<pre>$document->setMimeEncoding('application/json');
echo json_encode('myresult');
</pre>
4. Call the above function using ajax
5. Ajax response contains a special character that prevents javascript from decoding the response.

##### Additional remarks
1. Sample code available upon request
2. We cannot trigger events from ajax calls

**Comment by MartinTop** [comment]
Added screenshots![screen shot 2015-03-23 at 06 43 46](http://issues.joomla.org/uploads/1/112a2dc7ec4451403c9c0534737ab003.png)![screen shot 2015-03-23 at 06 43 48](http://issues.joomla.org/uploads/1/0161e13b439ee9f6ab8ef4365d594032.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6553">issues.joomla.org/joomla-cms/6553</a>.</sub>

**Comment by heleneross** [comment]
I am also having the same error - firefox reports json error, chrome says there is an extra <<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6553">issues.joomla.org/joomla-cms/6553</a>.</sub>

**Comment by Devportobello** [comment]
I'm unable to reproduce your issue, you need to provide more code.

What does your plugin?

Are you using some JS libraries? eg: Jquery

Moreover, i think you not use the proper way:
Use "JResponseJson" to handle the output, eg:
<code>echo new JResponseJson(array('data'=>'test'),'Success');<code>

In controller context you can use <code>$this->input</code> has place of <code>JFactory::getApplication()->input</code>

**Comment by MartinTop** [comment]
Hi Devportobello,

Thank you for your suggestions regarding code.

We've resolved the problem, one of our plugin's files was encoding in UTF8 With BOM.

Regards.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6553">issues.joomla.org/joomla-cms/6553</a>.</sub>
