### ISSUE TITLE
Problems with the joomla pagination

### ISSUE THREAD

**Issue by spignataro** [joomla/joomla-cms#6557]
All of these screenshots show irregularities with the Joomla! pagination. Most importantly the ... is just a number between the two numbers in the middle. For example it will do 149 ... 151. This really isn't a good way of doing pagination and needs to be put through more testing and thought process.

![screen shot 2015-03-23 at 10 58 25 am](https://cloud.githubusercontent.com/assets/72186/6782729/48257cd0-d14c-11e4-8d31-5c8f08ab0af0.png)
![screen shot 2015-03-23 at 11 00 32 am](https://cloud.githubusercontent.com/assets/72186/6782730/482fe81e-d14c-11e4-88bb-782d2e5e16ed.png)
![screen shot 2015-03-23 at 11 02 16 am](https://cloud.githubusercontent.com/assets/72186/6782731/4835662c-d14c-11e4-9469-0e1973f85b37.png)
![screen shot 2015-03-23 at 11 02 45 am](https://cloud.githubusercontent.com/assets/72186/6782732/4835c144-d14c-11e4-8d7c-fc0fc4e16d9e.png)
![screen shot 2015-03-23 at 10 57 50 am](https://cloud.githubusercontent.com/assets/72186/6782735/4dd80a8a-d14c-11e4-8fb5-484aba3388d6.png)

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #10240<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6557">issues.joomla.org/joomla-cms/6557</a>.</sub>
