### ISSUE TITLE
missing div in categories_default.php

### ISSUE THREAD

**Issue by achimoks** [joomla/joomla-cms#6565]
Problem in layouts/joomla/content/categories_default.php

Since update to 3.4.1 there is no line 13 with an opening div

...div class="categories-list<?php echo $displayData->pageclass_sfx;?>" ...

to get the page class for a menu item of type category blog but still a closing div like in the 3.4.0 version of this file.

#### Steps to reproduce the issue
Create a menu item of type category blog with a given page class.

#### Expected result
Get a div with class "categories-list" and the page class value.

#### Actual result
No div but a closing one at the end.

#### System information (as much as possible)
Joomla 3.4.1 an 3.4.0

#### Additional comments
Using the file of 3.4.0 works fine.

**Comment by wilsonge** [comment]
@phproberto you ballpark. Related to https://github.com/joomla/joomla-cms/commit/958b508d693b3d0a7791838438307c03735cfdc2

**Comment by bertmert** [comment]
@achimoks It looks like your template is using overrides and you have to add this line there yourself.
https://github.com/joomla/joomla-cms/commit/958b508d693b3d0a7791838438307c03735cfdc2#diff-de5637928f579ce271a9b7e5438201c4R26

**Comment by achimoks** [comment]
Thanks a lot for the answers ... yes, it was a problem of my template that uses overrides on base of an earlier release.
