### ISSUE TITLE
com_contact from tables to DIV and CSS

### ISSUE THREAD

**Issue by scottjgd** [joomla/joomla-cms#6566]
With Google getting tighter and tighter on it algorithms. It only makes sense to make the change to a more friendly SEO layout instead of nested tables.

**Comment by wilsonge** [comment]
Hi,
I don't believe there have been any nested tables in com_contact since Joomla 1.5?

**Comment by C-Lodder** [comment]
@scottjgd - The only table for com_contact is in

>components\com_contact\views\featured\tmpl\default_items.php

But there are no nested tables
