### ISSUE TITLE
When caching is turned on in system configuration, unwanted code is output on pages

### ISSUE THREAD

**Issue by cuttingd** [joomla/joomla-cms#6567]
When caching is turned on, I receive output similar to the following at the top of my pages:

{idkey=7913b0[url=http%3A%2F%2Fgtfamily.org%2Frethink-easter][title=reThink+Easter][desc=]}{cmp_start idkey=1393[url=http%3A%2F%2Fgtfamily.org%2Frethink-easter][title=reThink+Easter][desc=]}

And the following is output at the bottom of the page:

{cmp_end}{idkey=7913b1[url=http%3A%2F%2Fgtfamily.org%2Frethink-easter][title=reThink+Easter][desc=]} 

The following is my system information:

Setting 

Value 

  

PHP Built On  Linux rs5.websitehostserver.net 2.6.32-531.17.1.lve1.2.60.el6.x86_64 #1 SMP Tue Jul 8 11:25:32 EDT 2014 x86_64  
Database Version  5.5.40-cll  
Database Collation  utf8_general_ci  
PHP Version  5.4.38  
Web Server  Apache  
WebServer to PHP Interface  cgi-fcgi  
Joomla! Version  Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT  
Joomla! Platform Version  Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT  
User Agent  Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0

**Comment by brianteeman** [comment]
Which cache and what settings

**Comment by cuttingd** [comment]
Global configuration, system settings

**Comment by brianteeman** [comment]
And what exact settings. There are several settings for cache

**Comment by cuttingd** [comment]
Cache settings under the system tab of global configuration. Doesn't matter whether I chose conservative or progressive caching. File is the only cache handler available and cache time is set to 15.

**Comment by brianteeman** [comment]
A quick google search for the error indicates that it is probably coming from a social sharing module or plusin you have installed on your site that is not behaving itself<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6567">issues.joomla.org/joomla-cms/6567</a>.</sub>
