### ISSUE TITLE
Warning Class assigned to Popular Articles

### ISSUE THREAD

**Issue by JoshuaLewis** [joomla/joomla-cms#6568]
As of Joomla 3.4 I noticed the admin index have an orange label for popular articles as seen here:

![screen shot 2015-03-23 at 23 04 21](http://issues.joomla.org/uploads/1/9a28d5fae00d84659050bd2adfd1abe5.png)

This is due to the class "badge-warning" being assigned when articles have a lot of hits (perhaps over 1,000). Seems strange to have a lot of blaring orange labels on that section of the page. On a different site of mine with less popular articles it looks like this:

![screen shot 2015-03-23 at 23 04 18](http://issues.joomla.org/uploads/1/c8662f935cb14e2f5b905c669dddaa05.png)

This feels much friendlier on the eyes. Any thoughts on this subject? I'm sure there are many sites that have many articles over 1,000 hits.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/5646

**Comment by richard67** [comment]
Well, I agree the new colouring is maybe confusing.

I think a web site admin would get nervous when too few visits and happy when many.
With this in mind, I would expect the colouring scheme be vice versa, i.e. very low hit count = red, low hit count = orange, medium hit count = blue and high hit count = gray (or better: green?).

And it would be more useful even if the threshold values from one level to the other would be configurable.

Am curious on opinions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6568">issues.joomla.org/joomla-cms/6568</a>.</sub>

**Comment by richard67** [comment]
P.S.: If I get much positive feedback on my comment above, I could try to make a PR (pull request, patch) for it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6568">issues.joomla.org/joomla-cms/6568</a>.</sub>

**Comment by brianteeman** [comment]
Based on the fact that there have been no other comments on this in the last 8 months I am closing this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6568">issues.joomla.org/joomla-cms/6568</a>.</sub>

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6568">issues.joomla.org/joomla-cms/6568</a>.</sub>
