### ISSUE TITLE
Page navigator wont work

### ISSUE THREAD

**Issue by lmrex** [joomla/joomla-cms#6570]
On articles, if in the search tools we have a category selected, the page navigator wont leave the first page.

You click next, end or the number you want to go and it remains on number one

**Comment by sovainfo** [comment]
See https://github.com/joomla/joomla-cms/issues/6544

**Comment by zero-24** [comment]
Closing as dublicate of: https://github.com/joomla/joomla-cms/issues/6544<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6570">issues.joomla.org/joomla-cms/6570</a>.</sub>
