### ISSUE TITLE
J3.4.1 Modules not conforming to Joomla ACL

### ISSUE THREAD

**Issue by jchungerford** [joomla/joomla-cms#6576]
![screen shot 2015-03-24 at 13 05 09](http://issues.joomla.org/uploads/1/98da9c8833a5d873c37d9b82fd4a304c.png)#### Steps to reproduce the issue
From Backend, Set module to Super User access.  Clear server/browser caches. Navigate to a site Frontpage as guest. Module shows on Frontpage to Guest when it should not.

#### Expected result
Module to be hidden from Guest

#### Actual result
Module is shown

#### System information (as much as possible)
OCCURS ON:
Joomla 3.4 & 3.4.1

TEMPLATE:
JoomlArt / JomSocial Socialize Template 2.0 T3 Framework 2.4.5

OPERATING SYSTEM:
Windows 7

BROWSER:
Chrome, Firefox 

#### Additional comments
Also Using JomSocial v4.0.1 Component as Frontpage.

**Comment by brianteeman** [comment]
Can you replicate this with one of the core modules and templates? Or with any other module. This sounds more like a bug in the module  than with Joomla

**Comment by jchungerford** [comment]
I will attempt<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6576">issues.joomla.org/joomla-cms/6576</a>.</sub>

**Comment by zero-24** [comment]
@jchungerford any result here? I can not replicate this with e.g. the Similar Tag module. Thanks :smile:

**Comment by jchungerford** [comment]
After perusing through all of the user groups - the "Guest" User Access Level had all types from Guest to Super User checked.  I'm not sure how that occurred and am maybe thinking that this was caused either by a bug in the upgrade from 3.4 to 3.4.1 OR an admin made these changes in the backend without my knowledge for some odd reason.  I would lean towards an upgrade bug to potentially look at as some other folks have noticed something similar happening on their dev environments.

You can close this thread as it was a local issue as stated above but I would keep an eye out for a potential bug altering the Guest Access level during upgrading.

**Comment by massixone** [comment]
Quite similar problem here,
After upgrade to Joomla 3.4.1 I noticed that a module that has to be hidden to registered users is visible instead.
I verified the ACL, but ACL Level 'Guest' has ONLY 'Guest' Viewing Access (and its parent is 'Public'). There must be something in the code since it does not look like a configuration issue, at least on my site: www.diprimio.com.
Any suggestion?
