### ISSUE TITLE
Class 'Joomla\Application\AbstractApplication' not found

### ISSUE THREAD

**Issue by IberoMedia** [joomla/joomla-cms#6577]
I updated Joomla 2.5.28 to 3.4.1 and when running a Joomla standalone application I get error: **Fatal error: Class 'Joomla\Application\AbstractApplication' not found in [ROOT]\libraries\joomla\application\base.php on line 20**

I have read many post talking about the same problem indicating the *update was incomplete*. Hence, I installed a fresh Joomla 3.4.1 and implemented Joomla standalone application files as per this Joomla official tutorial **https://docs.joomla.org/How_to_create_a_stand-alone_application_using_the_Joomla!_Platform**

Even in the fresh Joomla 3.4.1 I get the same error Fatal error: **Class 'Joomla\Application\AbstractApplication' not found in [ROOT]\libraries\joomla\application\base.php on line 20**

Some of the posts I read talked about a path libraries/joomla/application/src hinting the AbstractApplication class would be located here. But the upgraded install I first mentioned, the fresh install I did to replicate the problem, and the files listed here in Git ( libraries/joomla/application/src ), all are missing a folder called [ROOT]/libraries/joomla/application/src

I don't know whether that folder and its content are necessary. But the fact is I am unable to get a Joomla standalone application to work, even the simple one from the Joomla official tutorial I linked to in the second paragraph.

**Comment by mbabker** [comment]
That page is heavily outdated.

A minimal application bootstrap can be found in our CLI scripts (https://github.com/joomla/joomla-cms/blob/3.4.1/cli/update_cron.php#L15-L34 is a good example).  As long as you include the includes/defines.php, libraries/import.legacy.php, and libraries/cms.php files, you'll get mostly the same bootstrap process that the main CMS apps go through.  The two libraries files will take care of getting all the CMS infrastructure loaded into place and you should be able to go from there.

**Comment by Bakual** [comment]
Closing as not a core issue.

**Comment by alex7r** [comment]
It's core issue.
- I've installed J3.6.2

- Installed some libraries with composer.

Everything is loading.

- Updating to J3.6.4

Libraries installed with composer are not loading.

- Composer update.

Class 'Joomla\Application\AbstractApplication' not found

**Comment by brianteeman** [comment]
Please don't comment on closed issues as they don't get seen. Please open a new issue
