### ISSUE TITLE
Hathor Display # in list views cannot be changed

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#6578]
Test:
- Change backend template to Hathor.
- Go to Content > Article manager
- You need more than 5 articles. So batch/copy some if you don't have.
- Change setting Display # below list to 5. Click Submit. Just sometimes it works (depends on if a value is already written in session I think) and you'll see 5 items now.
- Change setting now to a higher value. Click Submit. Page reloads. Doesn't work. Still 5 items. You cannot change value a second time.
- Try now in other list views. Same issue. Just one change possible.

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6578">issues.joomla.org/joomla-cms/6578</a>.</sub>

**Comment by phproberto** [comment]
I'm preparing a fix based on the concept in https://github.com/phproberto/joomla-cms/tree/4467-categories. That's the only real fix for this as it will prevent storing arrays & objects in the session for the same variables.

**Comment by brianteeman** [comment]
@phproberto I know its "only" hathor but were you able to make a fix for this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6578">issues.joomla.org/joomla-cms/6578</a>.</sub>

**Comment by poorgeek** [comment]
Any movement on this now that the referenced issues have been resolved? I'm still seeing this issue in 3.4.8.

**Comment by franz-wohlkoenig** [comment]
On Joomla! 3.7.0-beta1 Issue exists.

**Comment by brianteeman** [comment]
Based on the current status of hathor I am closing this
