### ISSUE TITLE
Autodetect tmp-Path

### ISSUE THREAD

**Issue by sisko1990** [joomla/joomla-cms#6579]
It would be great if Joomla! can autodetect the tmp-Path by getting the environment variable "$TMP" (as well: "$TEMP" or "$TMPDIR").
Some users don't know exactly the tmp-Path, so if they provide something wrong, there is no posibility for Joomla! to install extensions, because it can not write to the wrong provieded tmp-Path.

**Comment by bertmert** [comment]
tmp directory of server environment and tmp directory of Joomla configuration are different things.

**Comment by joomdonation** [comment]
I think there is a "Reset" or "Set Default" button to allow reset the temp path would be good. When users click on reset, we can set that path to JPATH_ROOT . '/tmp' folder. It would help end users reset that path when they need (for example, when they move the site to different server or after uploading file from local computer to server....)

**Comment by mbabker** [comment]
It's already an option in the Global Config to change the temp path.  Short of a system health screen somewhere, I don't think we need to be adding more buttons or options to an already busy interface.

**Comment by joomdonation** [comment]
I know there is option to change the temp path. However, how an end-user who doesn't know the root path of the site (JPATH_ROOT) can change it to correct path? Maybe I missed that option somewhere?

**Comment by joomdonation** [comment]
For now, when I have to fix that path for customers, I have to upload a PHP file to server, run it to get the root path, and then update the temp path config option to correct value (so that extensions could be installed....).

**Comment by mbabker** [comment]
I'm not saying it's a completely bad idea.  I just don't want us adding more buttons or options basically anywhere right now without thinking it through fully.  We already have too many options by trying to let the user configure everything in the GUI.

If we're going to start adding system health functions, this scenario being one of them, I'd rather see focus on a buildout of that type of feature with a full suite of checks versus having a button for this in the Global Config, the Database "Fix" view in the Extension Manager, etc.

**Comment by phproberto** [comment]
> I know there is option to change the temp path. However, how an end-user who doesn't know the root path of the site (JPATH_ROOT) can change it to correct path? Maybe I missed that option somewhere?

Maybe just a message showing the results of `getcwd()` as "Suggest path"

**Comment by joomdonation** [comment]
@phproberto I think "Suggested path" could simply be JPATH_ROOT . '/tmp'. I just don't know how/where we should/can display it.

**Comment by brianteeman** [comment]
I am a bit confused how you get a situation with incorrect tmp and log folder paths. The joomla installer creates these - the end user does not need to know anything about their server setup as Joomla has set these up for them<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6579">issues.joomla.org/joomla-cms/6579</a>.</sub>

**Comment by bertmert** [comment]
> I am a bit confused how you get a situation with incorrect tmp and log folder paths

E.g. when you move a page. Often asked and answered in forums how to correct these paths and how to determine it. And even if I know how to I would be happy sometimes to see a hint in the backend "absolute path to your Joomla" ;-) Also the most popular extension to copy / move Joomla e.g, to another folder on same server keeps the old paths if you don't pay attention.

**Comment by brianteeman** [comment]
I assume you mean move a site not move a page

I dont see why you would ever use that "most popular extension" when you
only need to move a site on the same server. But even if you did the "hard
bit" on finding the path, the absolute root, will not have changed. It
would only change on a new server and that "most popular extension" will
detect a new server and correctly write the paths

But PR always welcome if you really think it is needed

On 12 November 2015 at 21:49, bertmert <notifications@github.com> wrote:

> I am a bit confused how you get a situation with incorrect tmp and log
> folder paths
>
> E.g. when you move a page. Often asked and answered in forums how to
> correct these paths and how to determine it. And even if I know how to I
> would be happy sometimes to see a hint in the backend "absolute path to
> your Joomla" ;-) Also the most popular extension to copy / move Joomla e.g,
> to another folder on same server keeps the old paths if you don't pay
> attention.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6579#issuecomment-156246619>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by bertmert** [comment]
But the last foldername has changed in the absolute path. E.g. when you copy a site to another folder on the same server old tmp and log paths work fine for e.g. a temporarily subdomain until you delete or rename the old folder. Suddenly installations fail and so on. 

I don't know, too, where to show this information so that it is really helpul when a """normal""" user needs it. I made some fruitless PR trials in March.

**Comment by PhilETaylor** [comment]
This just needs closing...

**Comment by brianteeman** [comment]
Why - it's a reasonable request

**Comment by brianteeman** [comment]
Ignore my last comment

**Comment by PhilETaylor** [comment]
If you are trying to install extensions and cannot because you have an invalid tmp_path then one hopes that you are also the same person that has access to Joomla Global Configuration, the System Information page and a tiny bit of knowledge of the server environment your site is on, or can create ANY folder and set the tmp path to that. 

Joomla makes assumptions on first installation. These are correct assumptions and sets the paths right

If a "web master" subsequently moves the site and then doesn't update his paths then maybe he should consider his credentials for moving sites... it should not be up to Joomla to think "oh this path doesnt exist and you are trying to upload an extension... hmm... let me GUESS where to store my tmp data for you.... "

There is no reason for Joomla to ever have to guess where to put its tmp data. It should be specified by the "web master" in control of the site.

**Comment by PhilETaylor** [comment]
ah - duly ignored @brianteeman :)

**Comment by rdeutz** [comment]
This should be the responsible of the "site owner/Webmaster", closing
