### ISSUE TITLE
Menu item and K2 item do not adhere to access set (Registered/Special)

### ISSUE THREAD

**Issue by aptol1952** [joomla/joomla-cms#6592]
update to Joomla 3.4.1

On menu item with access registered and special they show in menu even if not logged in.

This also happens on K2 item with access special or registered. 

Need to resolve this issue asap.

**Comment by brianteeman** [comment]
I can not replicate this on a clean install of Joomla. Are you saying that it worked and then you updated to 3.4.1 and then it stopped working

**Comment by aptol1952** [comment]
Correct! it worked on 3.3.4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6592">issues.joomla.org/joomla-cms/6592</a>.</sub>

**Comment by aptol1952** [comment]
And now I also do not get my menu in administrator<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6592">issues.joomla.org/joomla-cms/6592</a>.</sub>

**Comment by zero-24** [comment]
I'm unable to replicate. Please try to fix the database and re-save the menu itm again. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6592">issues.joomla.org/joomla-cms/6592</a>.</sub>

**Comment by codelogixuk** [comment]
I have this same issue in Joomla 3.4.3.
A menu item that is marked as special or registered is not shown at all. A few people have observed this same issue.
