### ISSUE TITLE
Making an article or module exit impossible without clicking save or cancel

### ISSUE THREAD

**Issue by makinero** [joomla/joomla-cms#6593]
Hello,

I don't know if it's the right place to suggest an improvement.

When we edit a module or an article (front or backoffice), it would be judicious to add a JS alert "Please leave the article using the "save" or "cancel" button" when we try to leave by closing the browser tab or window.

A lot of users locks articles or modules, I can unlock them but that bother me and disturbs everyone.

Thank you

**Comment by Fedik** [comment]
I think such feature will annoying everyone a lot more :smile:

**Comment by dgt41** [comment]
There was an attempt but didn’t go that well #5815

**Comment by codeeditor** [comment]
I agree with @Fedik. For me such feature will be annoying.

**Comment by hgh-esn** [comment]
I agree with @Fedik. For me such feature will be annoying too.

**Comment by brianteeman** [comment]
Setting to Needs Review so theCMS maintainers can make a decision to close or continue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6593">issues.joomla.org/joomla-cms/6593</a>.</sub>

**Comment by chrisdavenport** [comment]
I'm going to pass this whole idea over to the UX people and let them decide if they want to proceed.  I think the idea has merit, but also could be annoying to some users.  If we do proceed then it needs to be consistent so it's going to be bigger than just this PR. I'm going to close this issue for now on that basis.  Thank you for your contribution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6593">issues.joomla.org/joomla-cms/6593</a>.</sub>
