### ISSUE TITLE
Joomla 3.4.1 Administrator Menu missing completely

### ISSUE THREAD

**Issue by aptol1952** [joomla/joomla-cms#6599]
i am at odds. Updated to Joomla 3.4.1 from 3.3.6

When trying to use administrator function all menu items are not appearing. Totally locked out of my site's backend. Front end is working fine.

http://authorsguildoftn.org

I looked at usergroups and access but do not see any problem. Logging in with Super user access or Administrator access ditto

i hope someone can help me with this critical issue

This is same using Hathor or Isis

**Comment by n9iels** [comment]
you mean when you go to the administrator side?
In that case I think it is an issue from your side... I don't have nanny problems with the menu

**Comment by brianteeman** [comment]
Please use the forum http://forum.joomla.org for site specific support<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6599">issues.joomla.org/joomla-cms/6599</a>.</sub>

**Comment by blaqvirus** [comment]
Im Facing the same problem i fixed the prefix_viewlevels and and the backend menu is still not appearing what can i do next<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6599">issues.joomla.org/joomla-cms/6599</a>.</sub>

**Comment by Bakual** [comment]
You can post on the forum. This issue tracker here is not meant for support requests.
