### ISSUE TITLE
Bug in Joomla 3.4x Banner Manager > Edit Client > Global setting

### ISSUE THREAD

**Issue by nemmar** [joomla/joomla-cms#6601]
Hi,

There is a bug in Joomla 3.4x Banner Manager.

When you try to save a Banner Client with the "Use Global" setting for Track Impressions and Track Clicks, it will save the changes as "No" instead of Use Global.

Steps to reproduce bug error:
1) Go to Banner Manager > Options > save global options as "Yes" for Track Impressions and Track Clicks settings. See attached screenshot 1

2) Go to Banner Manager > Clients > Edit Client screen and select "Use Global" for Track Impressions and Track Clicks settings and Save. It will change to "No" for those settings. See attached screenshot 2

![2015-03-28 banner settings 1](https://cloud.githubusercontent.com/assets/9383382/6882750/3827bb26-d567-11e4-9a01-5b35a1d634ec.JPG)

![2015-03-28 banner settings 2](https://cloud.githubusercontent.com/assets/9383382/6882751/3b2a0004-d567-11e4-86c9-24affdc58883.JPG)

**Comment by infograf768** [comment]
Issue confirmed.

**Comment by alikon** [comment]
cab you test with this one #6602

**Comment by nemmar** [comment]
Hi,
I just noticed something else that might be related to this issue. I'm not an expert with Joomla Banner Manager so it's possible this related item is not a bug. I have attached a screenshot.

Steps to reproduce bug error:
1) Go to Banner Manager > Banner Category Manager > Edit a Banner Category > in the Publishing tab screen:
Hits always stays at zero 0 and never changes even though the Banner Category is showing Impressions in the Tracks screen.

![2015-03-29 banner category hits counter](https://cloud.githubusercontent.com/assets/9383382/6886348/39608e4a-d608-11e4-9b1c-0b21468177f8.JPG)

**Comment by brianteeman** [comment]
closed please see #6602 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6601">issues.joomla.org/joomla-cms/6601</a>.</sub>
