### ISSUE TITLE
Broken Link in JOOMLA! PROJECT TRANSLATION AND LOCALIZATION POLICY

### ISSUE THREAD

**Issue by stekanius** [joomla/joomla-cms#6603]
In the below link
http://community.joomla.org/translations/translation-policy.html 

and by extending the 
*Terms and Conditions for acceptance as a Joomla Translation Team*
under the Joomla! Translation Team Agreement

there is a hyperlink in 14. in the words **"mission, vision and values"** that seems to be broken

**Comment by mbabker** [comment]
Corrected
