### ISSUE TITLE
Selection dialog of articles when creating a new menu is blank

### ISSUE THREAD

**Issue by alanandrew** [joomla/joomla-cms#6604]
#### Steps to reproduce the issue
I am encountering the above problem when trying to create a new menu in Joomla 3.3.6 & 3.4.x

I can select the menu item type "e.g. Article" but when attempting to select the actual article it opens to a blank dialog which used to display all the available articles. 

![screen shot 2015-03-29 at 06 29 32](http://issues.joomla.org/uploads/1/d48ff8de470270b05d7918e7a0bf2c56.png)
#### Expected result
A selection showing all available articles or images to select as the menu target

#### Actual result
The selection list dislog is blank
![screen shot 2015-03-29 at 06 30 46](http://issues.joomla.org/uploads/1/0309e83323f3ca3f7b9f14057a38af94.png)

#### System information (as much as possible)
Desktop Win7 8GB RAM
PHP 5.6.x

#### Additional comments
This used to work in version 3.3.4 but I have not created any menus since. 
Now it's just blank. So now I cannot create a new menu item.
The same problem occurs when trying to select a Link Type image. In fact, this problem occurs everywhere in Joomla.

However, I can insert images when using the Text editor JCE and the like.

Can anybody please assist with this problem?

Not sure if this issue is affecting only me maybe due to some setting, I just do not know.

**Comment by zero-24** [comment]
@alanandrew i'm unable to confirm this issue with 3.4.1

![unable_to_confirm](https://cloud.githubusercontent.com/assets/2596554/6887222/729ada30-d658-11e4-90e0-56bfbfd3a86b.PNG)

- Please try to clean your cache (browser and joomla)
- please refresh your joomla files. (donload 3.4.1, extract, remove the folder `installation` overwrite all files)

And try again.

**Comment by ggppdk** [comment]
Often a blank page means a php fatal error, try setting error reporting to "maximum" in Global config/Server TAB (if you don't have this already),
and if you are lucky a PHP error will appear inside the blank page

also sometimes a PHP fatal error could be hidden inside non visible tags e.g. <script>...</script>, try doing (inside the blank popup): "This frame/view HTML source" or similar

**Comment by alanandrew** [comment]
@ggppdk - I did what you recommended with no luck - the HTML code shows no error at all
@zero-24 - I also did what you recommended with no luck - the problem still exists.

However, what I did do was create a new clean install on a localhost connected to the same database on the hosted server and it works on the localhost. I'm thinking to create a clean install on a sub-folder on the hosted server and test from there.   What do you think?

BTW the host company cannot help because they do not get involved with dev issues.

**Comment by alanandrew** [comment]
@ggppdk & @zero-24 - I have found the problem with this issue - after some investigation I discovered that it was being caused by a bug in an extension that I had installed some time ago.  Disabled the extension (I was not using it anyway) and the problem went away.
