### ISSUE TITLE
Unnecessary closing div tag

### ISSUE THREAD

**Issue by QkiZMR** [joomla/joomla-cms#6607]
#### Steps to reproduce the issue
Display weblinks component. Unnecessary </div> tag in /components/com_weblinks/views/categories/tmpl/default.php causes mess in template. Line number 17.

#### Expected result
Correct display of weblinks component. Solution is create weblinks override without closing div tag.

#### Actual result
Mess in weblinks in custom template.

#### System information (as much as possible)
Linux, Apache![screen shot 2015-03-29 at 11 14 32](http://issues.joomla.org/uploads/1/22d6246d37c08daa680716d60814e4b9.png), Mysql

#### Additional comments

![screen shot 2015-03-29 at 11 14 32](http://issues.joomla.org/uploads/1/f4cf9f73adfce0449ed41039a26ec1d0.png)

**Comment by brianteeman** [comment]
The weblinks component is no longer part of the core of joomla - please post here https://github.com/joomla-extensions/weblinks/issues
