### ISSUE TITLE
show_page_heading issue in com_tags/tags

### ISSUE THREAD

**Issue by michelvvl** [joomla/joomla-cms#6610]
show_page_heading doesn't work for component "List of all tags" because of a small error in 
components/com_tags/views/tags/tmpl/default.php at line 19:
	<?php if ($this->**state**->get('show_page_heading')) : ?>
should be replaced by:
	<?php if ($this->**params**->get('show_page_heading')) : ?>

#### System information (as much as possible)

Joomla! Version	Joomla! 3.3.5 Stable [ Ember ] 30-September-2014 14:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by joomdonation** [comment]
This issue is fixed in Joomla 3.4.1 with this PR https://github.com/joomla/joomla-cms/pull/6274. So upgrade your site to latest version of Joomla and the issue will be gone.
