### ISSUE TITLE
failed to load phpmailer.xml

### ISSUE THREAD

**Issue by remotehelp** [joomla/joomla-cms#6611]
After update 3.4.0 -> 3.4.1 (_Joomla_3.4.x_to_3.4.1-Stable-Patch_Package.zip_) I get this:
> FILES_JOOMLA_XML_DESCRIPTION
> Warning: simplexml_load_file(): I/O warning : failed to load external entity "/public_html/administrator/manifests/libraries/phpmailer.xml" in /public_html/libraries/cms/installer/installer.php on line 1936 Warning: simplexml_load_file(): I/O warning : failed to load external entity "/public_html/administrator/manifests/libraries/phpmailer.xml" in /public_html/libraries/cms/installer/installer.php on line 2148

**Comment by zero-24** [comment]
@remotehelp can you try to explain a bit more how you can reprouce the error? Aotomatic update useing the Joomla update component? Or manually update? is the file `/public_html/administrator/manifests/libraries/phpmailer.xml` there or not?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6611">issues.joomla.org/joomla-cms/6611</a>.</sub>

**Comment by brianteeman** [comment]
wasnt that file moved

On 30 March 2015 at 22:47, zero-24 <notifications@github.com> wrote:

> @remotehelp <https://github.com/remotehelp> can you try to explain a bit
> more how you can reprouce the error? Aotomatic update useing the Joomla
> update component? Or manually update? is the file
> /public_html/administrator/manifests/libraries/phpmailer.xml there or not?
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/6611
> <http://issues.joomla.org/tracker/joomla-cms/6611>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6611#issuecomment-87841720>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
hmm still here: https://github.com/joomla/joomla-cms/blob/staging/administrator/manifests/libraries/phpass.xml Or i missunderstand you? @brianteeman

**Comment by mbabker** [comment]
PHPMailer is uninstalled as an extension between 3.3 and 3.4 in favor of the Composer integration.  So the manifest is deleted.

**Comment by brianteeman** [comment]
that is phpass not phpmailer



On 30 March 2015 at 22:53, zero-24 <notifications@github.com> wrote:

> hmm still here:
> https://github.com/joomla/joomla-cms/blob/staging/administrator/manifests/libraries/phpass.xml
> Or i missunderstand you? @brianteeman <https://github.com/brianteeman>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6611#issuecomment-87842905>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
Woops wrong file. Yes you are right @brianteeman 

phpmailer not phpass :smile: PHPMailer is moved correct! https://github.com/joomla/joomla-cms/tree/staging/libraries/vendor/phpmailer/phpmailer

**Comment by remotehelp** [comment]
@zero-24 manually update _Joomla_3.4.x_to_3.4.1-Stable-Patch_Package.zip_ ... is not file and not dir :) /public_html/administrator/manifests/libraries/phpmailer.xml no !isset()

...but if try again install _Joomla_3.4.x_to_3.4.1-Stable-Patch_Package.zip_ then I again get:
> Warning: simplexml_load_file(): I/O warning

**Comment by brianteeman** [comment]
Please explain what you mean by "manually update"

**Comment by remotehelp** [comment]
@ brianteeman you are noob?:) Select and upload _Joomla_3.4.x_to_3.4.1-Stable-Patch_Package.zip_ ... and install through Joomla installer ... of course  :)

**Comment by brianteeman** [comment]
I am not a mind reader

On 31 March 2015 at 09:29, remoteshaman.com <notifications@github.com>
wrote:

> @ brianteeman you are noob?:) Select and upload
> *Joomla_3.4.x_to_3.4.1-Stable-Patch_Package.zip* ... and install through
> Joomla installer ... of course :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6611#issuecomment-87993983>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sovainfo** [comment]
The installation using Extension manager -> Install is NOT considered "manually update". Manual update is known as extracting the distribution and replacing the files using a filemanager. Used at a time when updating wasn't as complex as it is now. Today you need to do a lot more to manually update.

Guess that takes care of who is the noob here!

**Comment by remotehelp** [comment]
@sovainfo - another noob?:) logically, if I extracting the distribution and replacing the files using a filemanager then from where I get "Warning: simplexml_load_file(): I/O warning"?

I mean auto update if patch load and install trough "Extension manager - Update - Find update - Install".

If trough "Extension manager -> Install" is NOT considered "auto update" as is and "Extension manager - Update - Find update - Install", and at least semi-manual! :)

Ok, I noob, and you also ;), but warning still exist.

**Comment by mbabker** [comment]
You obviously had a failed update getting to 3.4.  As part of the 3.4 update, the PHPMailer manifest was removed from the filesystem and the extension entry in the database deleted.  For you to be receiving this error message indicates that the extension is still in the database.  This can be confirmed via the Extension Manager's Manage view; filter for PHPMailer.

**Comment by remotehelp** [comment]
@mbabker Thanks!

I removed the record from the database `DELETE FROM "xxx_db"."xxx_extensions" WHERE "xxx_extensions"."name" = "PHPMailer"` and warning disappeared.
