### ISSUE TITLE
Bug in Joomla 3.4x Banner Manager > Tracks. Shows hourly counts instead of daily counts.

### ISSUE THREAD

**Issue by nemmar** [joomla/joomla-cms#6617]
Hi,
I noticed something else that might be related to the other Banner Manager bug I reported. I added this as a comment to the other bug report but that thread I think was already closed so I'm posting it as new issue. I'm not an expert with Joomla Banner Manager so it's possible this related item is not a bug. I have attached a screenshot.

Steps to reproduce bug error:
1) Go to Banner Manager > Banner Category Manager > Edit a Banner Category > in the Publishing tab screen:
Hits always stays at zero 0 and never changes even though the Banner Category is showing Impressions in the Tracks screen.
2) The Banner Manager > Tracks screen keeps adding new rows of info every HOUR instead of Daily for each Banner. Shouldn't it only list each Banner's impressions once per day instead of every hour of each day? 

https://github.com/joomla/joomla-cms/issues/6601#issuecomment-87430341
.
![2015-03-29 banner category hits counter](https://cloud.githubusercontent.com/assets/9383382/6919613/8afa2bd8-d786-11e4-8ad9-e63d216106c8.JPG)

**Comment by brianteeman** [comment]
That hit count is for displaying the number of hits on the display of the category itself NOT for any banners in the category. Truthfully there is NO way at all for this ever to be displayed so the hit count can never increase because it is never hit. It is only there because the category manager is used for multiple components

**Comment by nemmar** [comment]
Hi Brian,

Okay, but what about question 2 of my post?
I'm not a Joomla expert but this seems to not be working the way the Joomla Help screen explains it should.

2) The Banner Manager > Tracks screen keeps adding new rows of info every HOUR instead of DAILY for each Banner. Shouldn't it only list each Banner's impressions once per day instead of every hour of every day?
The hourly impression tracking creates tons of pages in the Tracks screens over time. I would think that would be a waste of database space and unnecessary Tracks screens.

I have attached 3 screenshots of my Joomla 3.4x settings related to the Client and Banner Tracking.
I apologize if this is not a bug but let me know if I should instead post this as a question on the Joomla.org forum instead of GitHub.
.
![2015-03-31 banner manager tracks impressions](https://cloud.githubusercontent.com/assets/9383382/6923874/75da7a7a-d7a2-11e4-9902-ffe933b8a5e2.JPG)
.
![2015-03-31 banner manager global settings](https://cloud.githubusercontent.com/assets/9383382/6923889/81a9673a-d7a2-11e4-98b2-639717b8d9fa.JPG)
.
![2015-03-31 banner manager client settings](https://cloud.githubusercontent.com/assets/9383382/6923895/8aa2552c-d7a2-11e4-8c3a-5f9b6c2bc63a.JPG)

**Comment by brianteeman** [comment]
that is a bug

On 31 March 2015 at 17:41, nemmar <notifications@github.com> wrote:

> Hi Brian,
>
> Okay, but what about question 2 of my post?
> I'm not a Joomla expert but this seems to not be working the way the
> Joomla Help screen explains it should.
>
> 2) The Banner Manager > Tracks screen keeps adding new rows of info every
> HOUR instead of DAILY for each Banner. Shouldn't it only list each Banner's
> impressions once per day instead of every hour of every day?
> The hourly impression tracking creates tons of pages in the Tracks screens
> over time. I would think that would be a waste of database space and
> unnecessary Tracks screens.
>
> I have attached 3 screenshots of my Joomla 3.4x settings related to the
> Client and Banner Tracking.
> I apologize if this is not a bug but let me know if I should instead post
> this as a question on the Joomla.org forum instead of GitHub.
> .
> [image: 2015-03-31 banner manager tracks impressions]
> <https://cloud.githubusercontent.com/assets/9383382/6923874/75da7a7a-d7a2-11e4-9902-ffe933b8a5e2.JPG>
> .
> [image: 2015-03-31 banner manager global settings]
> <https://cloud.githubusercontent.com/assets/9383382/6923889/81a9673a-d7a2-11e4-98b2-639717b8d9fa.JPG>
> .
> [image: 2015-03-31 banner manager client settings]
> <https://cloud.githubusercontent.com/assets/9383382/6923895/8aa2552c-d7a2-11e4-8c3a-5f9b6c2bc63a.JPG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6617#issuecomment-88164989>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by kobiavr** [comment]
is there any update about this bug ?

**Comment by wojsmol** [comment]
@nemmar @kobiavr see PR https://github.com/joomla/joomla-cms/pull/8825

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #8825 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6617">issues.joomla.org/joomla-cms/6617</a>.</sub>

**Comment by wojsmol** [comment]
@nemmar @kobiavr see PR https://github.com/joomla/joomla-cms/pull/8825
