### ISSUE TITLE
content from a remote server with javascript

### ISSUE THREAD

**Issue by franzpeter** [joomla/joomla-cms#6618]
#### Steps to reproduce the issue
There are content providers like Icecat, who offer a method to get content from a remote server into local page via Javascript. So you can display that inside a Joomla article for example by inserting that code (if tinymce for example is configured to allow js). It will get encoded with CDATA. I did try out but receive DOM error while using with Joomla. Creating a normal php file (not Joomla) works without any problem. Tried with WP: no problem. So I think there may be a problem with Joomla. Did add a picture![screen shot 2015-03-31 at 09 36 37](http://issues.joomla.org/uploads/1/2398c987d3cf57aa191e631450cd2910.png) to better demonstrate what I mean.

#### Expected result
correct display, loading everything and showing up

#### Actual result
DOM error, picture gallery not loaded.

#### System information (as much as possible)
Joomla 3.4.1

**Comment by franzpeter** [comment]
You can check here. It is a simple php page that by default and without joomla works without problems. [Your text to link here...](https://www.2in1-online.com/tester.php "Test page")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6618">issues.joomla.org/joomla-cms/6618</a>.</sub>

**Comment by OctavianC** [comment]
- `Blocked loading mixed active content "http://live.icecat.biz/js/live-current.js"`
Your example page doesn't work because it's using SSL while your script inclusion isn't.
- I've just tested this in a default Joomla! installation and everything works fine.
![untitled-1](https://cloud.githubusercontent.com/assets/1422378/6922226/5b2ec976-d7d2-11e4-85de-3507a0434c92.jpg)
- I also disabled tinyMCE (all editors are known to cause issues when you're trying to embed your own code) and switched to "Editor - None" during my test.

**Comment by franzpeter** [comment]
OctavianC, and you do not get something like SyntaxError: DOM Exception 12: An invalid or illegal string was specified.
tlive-current.js:2:236435
Morelive-current.js:2:236778
renderlive-current.js:2:247317
allLoadedlive-current.js:2:246939
clive-current.js:2:369900
successlive-current.js:2:370316
onloadlive-current.js:2:369069
?
On my localhost I have no SSL, but getting that error above!
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6618">issues.joomla.org/joomla-cms/6618</a>.</sub>

**Comment by brianteeman** [comment]
Sorry but this is a support type question and belongs on the forum not on the core joomla issue tracker

**Comment by franzpeter** [comment]
I do not understand why it was closed. The issue does not exist using the protostar template but it exists using beez template. Beez produces the DOM exception 12, protostar does not.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6618">issues.joomla.org/joomla-cms/6618</a>.</sub>
