### ISSUE TITLE
Joomla activation links in https

### ISSUE THREAD

**Issue by conflate-nl** [joomla/joomla-cms#6635]
When Joomla is viewed in https mode with a valid certificate, and a new user wants to create an account, the activation link which is send to their e-mail contains the secure host name twice and therefor makes the link not clickable.
When manually removing one of the host names the activation does work!

The link will start like this: https://www.example.comhttps://www.example.com/

**Comment by brianteeman** [comment]
I just checked this on my own site with no problem at all

Thank you for registering at Brian Teeman. Your account is created and must be activated before you can use it.
To activate the account click on the following link or copy-paste it in your browser:
https://brian.teeman.net/reg?task=registration.activate&token=removedfortracker

After activation you may login to https://brian.teeman.net/ using the following username and password:
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6635">issues.joomla.org/joomla-cms/6635</a>.</sub>

**Comment by conflate-nl** [comment]
Thanks for the quick response!

Could this be caused by using SEF? I don't see the ?task=  in the link, it's a SEF url

**Comment by brianteeman** [comment]
Are you running your site in dutch? I am wondering if it is a bug in the dutch language file

**Comment by conflate-nl** [comment]
It happens on sites running either nl-NL or en-GB. 
I'll try to see if I can temporarily disable SEF and see if it still happens

**Comment by brianteeman** [comment]
Sef is obviously enabled on my site as you can see

**Comment by conflate-nl** [comment]
Ok, I found the problem. It turned out to be JoomSEF. I had a test site and when I completely removed JoomSEF, the problem was gone. So it's clearly not a Joomla problem!

Thanks for helping!

**Comment by mibert** [comment]
Hi Conflate,

could you let me know, how you have finally fixed this issue?
I am facing exactly same issue on various Joomla Components like Kunena and Geocode Factory.

Also I am using JoomSEF

Best regards

**Comment by zero-24** [comment]
@mibert please try the JoomSEF Support if it is a JoomSEF issue Thanks :smile:

**Comment by conflate-nl** [comment]
Hi Mibert, 

Unfortunately I haven't found a solution. I'v simply removed JoomSEF and used the default Joomla SEF, which was not a problem for this particular site. 

Regards

**Comment by mibert** [comment]
Thanks for your reply anyway.

Best regards and have a good day

**Comment by mibert** [comment]
I found a solution together with Artio. Just in case someone has same issue. Just let me know.
