### ISSUE TITLE
Alphanumeric primary keys, code change

### ISSUE THREAD

**Issue by ChrisDo84** [joomla/joomla-cms#6637]
#### Steps to reproduce the issue
I'm writing a component and use the Build-In functions getForm() and loadFormData() to load data from the tables.
I'm using UUIDs as primaray keys for my tables to a void a guessing of IDs stored in the database. Unfortunately Joomla is expecting that IDs are always numeric:

I had to change a line in the file
/libraries/legacy/model/admin.php    Line 858 
if ($pk > 0)

should be
if (!is_null($pk))

Please confirm and change in the next version. 
The behavior seems to be the same. 

#### Expected result
Allow alpha-numeric primary keys

**Comment by bertmert** [comment]
```
!is_null($pk)
```
is always true because of line 855
```
$pk = (!empty($pk)) ? $pk : (int) $this->getState($this->getName() . '.id');
```
Why don't you use your own method getItem in your component model? You can override the parent method there.

**Comment by ChrisDo84** [comment]
Okay,
I didn't thought about it :-)
This could be a solution, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6637">issues.joomla.org/joomla-cms/6637</a>.</sub>
