### ISSUE TITLE
wrong creation-timestamp set when article-save2copy

### ISSUE THREAD

**Issue by hgh-esn** [joomla/joomla-cms#6647]
#### Steps to reproduce the issue

Go into the article-manager
Edit an article
Make a new article by save as copy button.  [save2copy - function]
Look to the article option (creation-date/-time, saving-date/-time)

You will find:
creation-date/-time is the **source date/time.**  .... and that is wrong !!!!!!!!
saving-date/-time   is the saved date/time

#### Expected result

The creation-date/-time of the new article has to be set to the actual date/-time. 
The new article has a new id and has never been saved explicitly, except for the saving to create it. Therefor it has to be handled like a very new one.

The saving-date/-time must be empty at that time.

#### Actual result

The creation-date of the new article is set to the one by the old-article.
That is wrong, because the new article has a new id and has never exist before.

The saving-date is set to the actual date.

#### System information (as much as possible)

J 3.4.1  
My be so in older and future versions too.

#### Additional comments

The result must be the same, as when we do it in single steps

creation-date/-time is the actual date/time.
saving-date/-time   is the saved date/time.

When doing it via "save2copy"
creation-date/-time is the **source date/time.**  .... and that is wrong !!!!!!!!
saving-date/-time   is the saved date/time

Another problem is, that the so created "new" articles are not shown in the list of the latest articles.

**Comment by mbabker** [comment]
I wouldn't necessarily call this a bug.  When you create a new article, you can input your own creation time and if that is empty then the current time is used.  If any time should be adjusted during the copy process, it should be the modified time (as it was newly updated), otherwise the create/publish times shouldn't be touched as they can be specified by a user.

**Comment by hgh-esn** [comment]
> I wouldn't necessarily call this a bug. 
In the reported case I definitivly see not so.

What do we do:

1. We want to create a new article with content in it from an already existing article ... to work with it further on.
2. So we edit the source-article and use the "save as a copy" function to create the new article.
3. The new article is created and the editor goes into it.
4. Now we can work further in the new article.

In 99% of all cases, the user forgets to set the creation-date/-time explizit.
So it is more useful to do this automatically.

The result must be the same, as when we do it in single steps like this.
========================================================================
1. Open source-article an put the content into scratch.
2. Close source-article
3. Create a new article by the joomla standard-process.
4. Paste in the content
5. Save the new article. 

If you do it in single steps, 
creation-date/-time is the actual date/time.
saving-date/-time   is the saved date/time.

When doing it via "save as copy"
creation-date/-time is the **source date/time.**  .... and that is wrong !!!!!!!!
saving-date/-time   is the saved date/time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6647">issues.joomla.org/joomla-cms/6647</a>.</sub>

**Comment by mbabker** [comment]
You're proposing to alter a system wide behavior in this case.  When an item is copied, the entire record is copied as is with the only modifications being to unpublish the item and change the title/alias to fit uniqueness rules if need be.  As the current time is used only if a time is not specifically input into those fields, you're also suggesting that the copy process removes the created time, modified time, and published time.  Making this change would not affect only articles; all extensions inheriting from the core MVC layer would be affected by this change.  And I personally don't believe it is a change that should be made; it alters a core behavior and makes my data input questionable.  If I open an article, change the title, remove the alias, and change the created time before clicking "Save as Copy", I expect my copied record to have those changes and the original record to be unchanged; with your suggestion my created time would be lost.

**Comment by hgh-esn** [comment]
> ....  the create/publish times shouldn't be touched as they can be specified by a user

The create/publish times shouldn't be touched by a user. ! 
That are system-nearly times, so they should only be touched by a admin.

**Comment by hgh-esn** [comment]
> I expect my copied record to have those changes and the original record to be unchanged; with your suggestion my created time would be lost.

You may be right, but that is user-controlled and hand-made and so miles away from an automatized IT-process.

**Comment by mbabker** [comment]
I'd say that's a totally separate issue then if you want to suggest that the created/publish times should be ACL limited.  As is, anyone who has permissions to create/edit content on a site has the ability to specify these items.

There is no way to know if the time specified was system generated or user input.  So the options are to either always reset the time or never reset it.

**Comment by hgh-esn** [comment]
Hi,

sorry, but by closing the problem it is not resolved and it will continue to be wrong, because you get two different creation-dates, when creating an article about two different ways.

1. Create an article with the "new-button" and look to the creation date.
2. Do the same opening an existing article, make changes to the new content and press the save2copy-button. Then take a look to the creation-date.

In the first way, the creation-date is set to the date of the act. day in an automatic joomla-process..
In the second way the creation-date stays to that of the copied article. In that way the date isn't changed. It must be changed manually by the user. I guess, this will be forgotten in more than 90% of all cases.

One result therefore is, that the "newest article"-modul will not show the save2copy-created article without manually update the creation-date. That is "IT by hand" - far away from any automatic process which could be easily done be joomla itself.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6647">issues.joomla.org/joomla-cms/6647</a>.</sub>

**Comment by JDTravel** [comment]
Hi,
The saveascopy behaviour may be technically correct to copy accross the original created datestamp of the article, but from a practical stand point I agree with user hgh-esn, that it should create a new current datestamp.   <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6647">issues.joomla.org/tracker/joomla-cms/6647</a>.</sub>
