### ISSUE TITLE
Modules in multilanguage are displayed twice

### ISSUE THREAD

**Issue by GunnarBs** [joomla/joomla-cms#6651]
I am trying to set up our german site with english also.

As far as I see I have to maintain the menus 3 times (en for all english browsers, de for all german browsers and all for the rest).

If I maintain three modules (EN, DE, ALL), the module ALL will be displayed always, so the module will be shown double, once in EN, once in ALL.

Further, if a spanish browser comes along, it will display the module of DE as this is the site language. It would be much better to display the module EN. (Again, if I turn on ALL also, it will display module in DE and ALL).

#### Steps to reproduce the issue

Install english and german as languages. Make sure content (extensions - language manager) is available in both languages. You do not need a menu in both languages.
In PlugIn System - Language filter set all to YES, except cookies.
Create a custom HTML module with some text. Set language to EN.
Create a module with some different text. Set language to DE.
Create a module with some different text. Set language to All.

Assign these modules to one menu item.

Assuming your browser language is EN, you should see text for EN and All. (only EN would be correct).

Change site language to DE.
Change your browser language to spanish. You need to remove browser language english. I testet on google chrome.

Call the page again. You should only see All, but see DE and All modules.

#### Expected result

Show only one module.

#### Actual result

Shows two modules.

#### System information (as much as possible)

Joomla 3.4.1

#### Additional comments

It would be much easier for the maintainer if he could set a default language which is used, if the system does not have a matching language. Having a german site, I would like chinese users to see the english content without copying everything. The big benefit would be to maintain only two menu structures and not three. It may be easier for the programmers as well, seeing the problems with the correct module selection.

**Comment by Gitjk** [comment]
I'm shure you misunderstood the multilanguage configuration tutorials. Just unpublish your 'All' modules and configure the System language filter plugin according to your prefered options. You need only en and de modules. However afaik there is no Joomla extension which switches languages depending on the user's IP address, but of course chinese users are able to click their prefered language flag.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6651">issues.joomla.org/joomla-cms/6651</a>.</sub>

**Comment by brianteeman** [comment]
@Gitjk is correct. You do not need to set anything for ALL. All means it will display on ALL languages NOT on languages other than DE and EN. 

> It would be much easier for the maintainer if he could set a default language which is used, if the system does not have a matching language.

This is done in the Language manager

In other words when EN is set in the Language manager as the default site language then in your example this will be displayed to all users who are now shown the DE language<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6651">issues.joomla.org/joomla-cms/6651</a>.</sub>

**Comment by GunnarBs** [comment]
@Gitjk 
a) I could not find multilanguage tutorials, this page seems very outdated and not comprehensive at all: https://docs.joomla.org/Adding_multi-language_support
b) I do not require an extension for IP resolving. Joomla reads the webbrowser languages.
c) I did extensive testing before raising this issue, but may have been confused, because Menu requires ALL, EN and DE, while modules apparently do not.
@brianteeman 
d) I searched the internet for various tutorials, but none stated, which language is used, when a user has a language set, which is not any of the defined site languages. I figured, this means he will get ONLY modules ALL, so in this case he would get an empty page if All is not defined. Will check if EN is delivered.

**Comment by brianteeman** [comment]
Sadly Gunnar you guessed wrong

On 6 April 2015 at 15:42, GunnarBs <notifications@github.com> wrote:

> @Gitjk <https://github.com/Gitjk>
> a) I could not find multilanguage tutorials, this page seems very outdated
> and not comprehensive at all:
> https://docs.joomla.org/Adding_multi-language_support
> b) I do not require an extension for IP resolving. Joomla reads the
> webbrowser languages.
> c) I did extensive testing before raising this issue, but may have been
> confused, because Menu requires ALL, EN and DE, while modules apparently do
> not.
> @brianteeman <https://github.com/brianteeman>
> d) I searched the internet for various tutorials, but none stated, which
> language is used, when a user has a language set, which is not any of the
> defined site languages. I figured, this means he will get ONLY modules ALL,
> so in this case he would get an empty page if All is not defined. Will
> check if EN is delivered.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6651#issuecomment-90083587>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
Although it is a tutorial for 2.5 (we have more associations in 3.x) this may be of help:
http://multilingual.demojoomla.com/

You can login in admin to see the settings.

**Comment by infograf768** [comment]
My tests show here that if a user has set as site default language a language which is NOT also a Content Language, then, when logging, the user will be redirected to the same language where the login module or the login menu item was present.

I guess an improvement would be to NOT let choose by a user a language which is not also a Content Language with a home, etc.
