### ISSUE TITLE
Menu Manager: New Menu Item:: Error message needs to be more usable to tell the problem in simple words

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#6654]
-Go to Menu Manager: New Menu Item
-Select Single article option in **Select Article** Field
-Do not select any article
-Click on Save/Save & Close

You will see an error message, But that needs to be more usable

**Expected error: You have not selected any article, Please select an article**

![screen shot 2015-04-04 at 04 11 31](http://issues.joomla.org/uploads/1/7cd41662ac5f4365dfacd6176965e1c4.png)

**Comment by dgt41** [comment]
@zero-24 Can you close this one. There are 3 PRs that correct this #6885, #6888 and #6889

**Comment by zero-24** [comment]
Closing as requested by @dgt41 Thanks :smile:
