### ISSUE TITLE
Menu Manager: New Menu Item:: Display a message 'No matching results', If there is no records as per filter selection, while selecting single article in pop-up

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#6655]
-Go to Menu Manager: New Menu Item
-Select Single article option in Select Article Field
-Select an article
-A pop-up will open
-apply any invalid filter
-Check, there is no message

**Expected Message: 'No matching results'**

![screen shot 2015-04-04 at 04 27 44](http://issues.joomla.org/uploads/1/b6789c80c5fcc6842ce96ce19411f975.png)

**Comment by brianteeman** [comment]
For info this is not just on the select single article menu type - same is true on single contact (tested) and probably more<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6655">issues.joomla.org/joomla-cms/6655</a>.</sub>

**Comment by brianteeman** [comment]
This is resolved by #7231 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6655">issues.joomla.org/joomla-cms/6655</a>.</sub>
