### ISSUE TITLE
Regressions: In Submit and edit article in front-end

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#6662]
Login frontend as superuser.

=> Display menu item "Submit and article"

Click on Cancel.
result: A tip display on the Title field "Please fill out this field" and you can't cancel Submitting an article.

![screen shot 2015-04-05 at 02 46 31](http://issues.joomla.org/uploads/1/c0f30345216e70cef15f8a28f8f0594a.png)

=> When editing an article, click on the Article button at bottom of the text-area.

The modal displays but, as soon as you click on one of the filters, the display breaks havoc and no dropdown shows with filters choice for the filter chosen

![screen shot 2015-04-05 at 02 47 21](http://issues.joomla.org/uploads/1/467367f516b51f0375d47b4c7d345d45.png)

**Comment by brianteeman** [comment]
I couldnt replicate the Cancel issue but I could replicate the filter issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6662">issues.joomla.org/joomla-cms/6662</a>.</sub>

**Comment by Fedik** [comment]
I can replicate Cancel issue ... seems something wrong with that #6587  I need check.
And can replicate second problem also

**Comment by brianteeman** [comment]
Ah - i didnt have #6587 applied yet

On 5 April 2015 at 09:46, Fedir Zinchuk <notifications@github.com> wrote:

> I can replicate Cancel issue ... seems something wrong with that #6587
> <https://github.com/joomla/joomla-cms/pull/6587> I need check.
> And can replicate second problem also
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6662#issuecomment-89735934>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Fedik** [comment]
for Cancel action fix, please test #6664

**Comment by Fedik** [comment]
and for other issue #6667 , but there still issue with category dropdown
