### ISSUE TITLE
Fatal error: Class 'idna_convert' not found in /var/www/test/.protect/.libraries/joomla/string/punycode.php on line 52

### ISSUE THREAD

**Issue by remotehelp** [joomla/joomla-cms#6663]
Hello shit-coders!;)

When I move plugins directory, then I get this: "Fatal error: Class 'idna_convert' not found in /var/www/test/.protect/.libraries/joomla/string/punycode.php on line 52"

Why shit-coders instead JPATH_ROOT don't uses JPATH_PLUGINS constant for included lib's?;( - "JLoader::register('idna_convert', JPATH_ROOT . '/libraries/idna_convert/idna_convert.class.php');"

???;(

Fack...

**Comment by brianteeman** [comment]
Abusive language to coders is not acceptable<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6663">issues.joomla.org/joomla-cms/6663</a>.</sub>

**Comment by remotehelp** [comment]
@brianteeman Sorry friend, - please change JPATH_ROOT to JPATH_LIBRARIES in /joomla/string/punycode.php :)

**Comment by brianteeman** [comment]
https://docs.joomla.org/Filing_bugs_and_issues#Issue_a_pull_request_directly_on_Joomla.21.27s_GitHub_repository

On 5 April 2015 at 10:14, remoteshaman.com <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> Sorry friend, - please
> change JPATH_ROOT to JPATH_LIBRARIES in /joomla/string/punycode.php :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6663#issuecomment-89738446>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
