### ISSUE TITLE
AdminTasks module not sorting by category or respecting list count

### ISSUE THREAD

**Issue by Willroz** [joomla/joomla-cms#6668]
#### Steps to reproduce the issue
Enable the AdminTasks module in the Module Manager
Create two Task-Categories (Cat-a & Cat b) in the component.
Assign 'Cat-a' to the existing module.
Create a new AdminTasks module and assign it to 'Cat-b'
Set list count at 5 (default)
Create enough tasks to test. Assign half to 'Cat-a', half to 'Cat-b'

#### Expected result
The original module should only show tasks for 'Cat-a'
The new module should only show tasks for 'Cat-b'
Each list should be 5 items long

#### Actual result
All tasks are appearing in both modules
Count set to show 5 items shows more

Images of misbehavior
![screen shot 2015-04-05 at 09 21 02](http://issues.joomla.org/uploads/1/8112b82c9429b2fa18176f48bbfda05f.png)

![screen shot 2015-04-05 at 09 21 02](http://issues.joomla.org/uploads/1/7b6922d1ea497df7f7c496f44ee47506.png)

#### System information (as much as possible)
I can verify that this is happening on a couple of my sites that were built in J! 3.3.6 and updated to 3.4.1 via the updater. I haven't had time to test on a fresh 3.4.1.

![screen shot 2015-04-05 at 09 25 24](http://issues.joomla.org/uploads/1/c556bda7872bfbeef151834518074073.png)

#### Additional comments
Can anyone else replicate this issue.

**Comment by brianteeman** [comment]
Not sure what module this is but it is NOT part of the core of Joomla. I suggest that you contact the developer of this extension

**Comment by Willroz** [comment]
Hi Brian,

A quick look shows that it came in as part of an Admin Template we were looking into for our customized back-end. With the timing of it all, I just thought it was a new feature added to 3.4 that I was unaware of.

Thanks for the quick response and pointing me in the right direction.
Will<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6668">issues.joomla.org/joomla-cms/6668</a>.</sub>
