### ISSUE TITLE
Possible missing break in bin\keychain.php at line 77?

### ISSUE THREAD

**Issue by photodude** [joomla/joomla-cms#6672]
Is there a reason for the missing break statement at line 77 in bin\keychain.php at the `case 'change':`? 
Seems like this would be (or could cause) an error by omission.

**Comment by bertmert** [comment]
@photodude Please let us know: Which file you are talking about? Too many lines 77 in Joomla... ;-)

**Comment by photodude** [comment]
Sorry I forgot to add that...
bin\keychain.php
line 77 is part of the switch
'switch ($this->input->args[0])'
and the case
'case 'change':'

**Comment by zero-24** [comment]
@photodude i have just open a PR against the uptream repo so the people there can decide see: https://github.com/joomla-framework/keychain/pull/6

Thanks :+1:

**Comment by photodude** [comment]
@zero-24 I debated opening a PR for this, but I was unsure if it was intentional, and what logic could behind and intentional omission of a break at this point the the switch case. Hence opening an issue and posing the question.
If it was intentional, and not an omission, it should have been commented as such and likely should have been the first item in the switch-case. Otherwise I agree that a break statement is needed as you have done in the joomla-framework/keychain#6 PR.

Looking at the phpunit test for keychain at keychain/Tests/KeychainTest.php, I'm not sure that a "change" case is tested.

**Comment by zero-24** [comment]
Thanks @photodude but as this file is, as far i know. Never used with the main repo and we have the upstream dependency i will close here with the referr to the framework PR: https://github.com/joomla-framework/keychain/pull/6

If the folks behind the framework decide to merge this i guess it will be synced it into the main repo.

Thank you!
