### ISSUE TITLE
Add a means to preview content.

### ISSUE THREAD

**Issue by AgrarPirat** [joomla/joomla-cms#6678]
Dear Joomla Team,

we (your users) need a way to comfortable and reliably preview content before it is published. Sure there are third party components, but unfortunately non of them is working flawlessly. An other, more reliable option is to have a local Joomla installation to compose content and copy the article (and it's assets) onto the life server where it then can be scheduled for publication.
Needless to say that this is very cumbersome and feels like we (Joomla users) are still stuck in the early 2000s. So please, add a way to preview content. It's high time by now.

**Comment by bertmert** [comment]
Set Access of article to Special (or create a new User group for the purpose), log in in frontend. Preview, correct as necessary and set Access to Public when all is fine then.
