### ISSUE TITLE
Can't Cancel Out of Backend Forms that Have Required Fields

### ISSUE THREAD

**Issue by orware** [joomla/joomla-cms#6683]
#### Steps to reproduce the issue

This is happening on a number of backend forms but for sure on:
Creating a new menu item (I have a lot of categories/articles in my test database at the moment so I can't get back into the Add New Article/Category views at the moment but I'm pretty sure it was happening on both of those).

Basically what you do is open up one of those Add New [Menu Item,Article,Category] screens and then try and hit the Cancel button...instead of Canceling out and returning you to the List view, the first required field is highlighted and you can't leave the page (which to me, isn't the behavior I would expect).

At the moment I haven't taken a closer look to try and see what's happening (if it's simply Google Chrome's form behaviors or if it's the actual Joomla Forms JavaScript), but if it's an issue in our JavaScript it should definitely be fixable.

#### Expected result

You're returned to the list view.

#### Actual result

You stay on the Add New screen and the first required field is highlighted.

#### System information (as much as possible)

Windows, one of the newer XAMPPs running PHP 5.5, Google Chrome, latest version of Joomla checked out from GitHub.

**Comment by bertmert** [comment]
Did you check this patch PR already?
https://github.com/joomla/joomla-cms/pull/6664

**Comment by orware** [comment]
@bertmert Thanks for pointing out that one for me...it looks like mine would be a duplicate so we can just close it since it seems to be resolved in #6664 as you pointed out (when I pull in the latest changes from GitHub again I should be able to see the fix that's already been merged in).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6683">issues.joomla.org/joomla-cms/6683</a>.</sub>

**Comment by orware** [comment]
I'm going to go ahead and close this one since it's already fixed in #6664
