### ISSUE TITLE
reagrangeOrderingValues should not change values in all <input type=text />  in sortablelist.js

### ISSUE THREAD

**Issue by VitUrzh** [joomla/joomla-cms#6685]
/media/jui/js/sortablelist.js
In the function reagrangeOrderingValues
Such as '[type=text]' replaced by '.text-area-order'
Then will change only one INPUT with class "text-area-order"

**Comment by zero-24** [comment]
@VitUrzh I'm not a JS guy but can you tell us the issue that you have? I don't understand what you try to say to us :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6685">issues.joomla.org/joomla-cms/6685</a>.</sub>

**Comment by brianteeman** [comment]
After two weeks without reply I am closing this. It can always be reopened if the requested information is provided<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6685">issues.joomla.org/joomla-cms/6685</a>.</sub>
