### ISSUE TITLE
Toggle SSL verification in JHttp cURL transport

### ISSUE THREAD

**Issue by haydenyoung** [joomla/joomla-cms#6688]
#### Steps to reproduce the issue
Access a test api such as https://dev.api.ean.com.

#### Expected result
Access the REST endpoint without error.

#### Actual result
The underlying cURL application is throwing an invalid certificate error.

#### System information (as much as possible)
Joomla 3.3.4
Ubuntu 14.04 Server
curl 7.37.1-1ubuntu3.2
php5 5.5.12+dfsg-2ubuntu4.3

#### Additional comments
JHttpTransportCurl requires additional options for toggling CURLOPT_SSL_VERIFYPEER and CURLOPT_SSL_VERIFYHOST. Whilst the issues is actually with the ssl certs being provided by the server, it is should be recognized that the configuration of many external REST providers cannot be controlled by the developer so developers should have the option to turn off this verification for testing purposes.

**Comment by zero-24** [comment]
Closing here as we have a PR here: https://github.com/joomla/joomla-cms/pull/6692
