### ISSUE TITLE
Tags not visible in frontpage and category blog view

### ISSUE THREAD

**Issue by antoniotheant** [joomla/joomla-cms#6690]
#### Steps to reproduce the issue

Article Manager Options / Show Tags = Show

Menus / Main menu / Home (Featured articles-all categories) / Show Tags = Show

Menus / Main Menu / People (Category blog) / Show Tags = Show

#### Expected result

Tags visible

#### Actual result

No tags in frontpage (Home) neither in Category blog

#### System information (as much as possible)

Joomla 3.4.1 with Gantry based template (Afterburner2)
PHP Built On 	Linux webxc49s03.ad.aruba.it 2.6.32-504.3.3.el6.x86_64 #1 SMP Wed Dec 17 01:55:02 UTC 2014 x86_64
Database Version 	5.5.42-37.1-log
Database Collation 	latin1_swedish_ci
PHP Version 	5.5.22
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:36.0) Gecko/20100101 Firefox/36.0 

#### Additional comments

Maybe it is a bug

**Comment by queengab** [comment]
Hi,

i think this an issue for joomla forum. 

Anyway i think you have to verifiy the template views of category and featured. 
The original position is...components/com_content/views/category/tmpl/default
and so the same for featured

You may create an ovveride of your template/yourtemplate/html/com_content and the create a directory for featured and one for category. 
You can search on google joomla 3 ovveride.

Try to change tempalte with beez and see if you are the same behaviour.

Bye
Gabriele

**Comment by antoniotheant** [comment]
Thanks for reply.
No tags with Beez too.

**Comment by queengab** [comment]
Ok.
You can proceed as follows:
Please make sure on category or featured template default.php in
components/com_content/views/category/tmpl/default.php, you can find tags condition of publication inside. If there isn't create an ovveride of this view. 

Instead you find the tags condition, you can try to change properties inside tags option. Probably tags don't publish on category for this reason.
But i vouch you that tags works also on categories.

Bye 
Gabriele

**Comment by antoniotheant** [comment]
Thanks again
but please, this is a default joomla feature and it doesn't work with default template like beez. Why I need to override something?
It is a fresh new install, anyway. Tags are ok and work fine in module like Gavick News Show Pro 5 on the same site.
Bye

**Comment by sovainfo** [comment]
See https://github.com/joomla/joomla-cms/pull/6625
Note that you need info block split or bottom

**Comment by antoniotheant** [comment]
Thanks for reply sovainfo but no, they don't fix my problems. The second one is for single article menu item and it doesn't show Tags (in above, bottom or split position) in Blog Category view anyway.

**Comment by sovainfo** [comment]
Thanks for correcting. 
The Category blog is designed to always show tags above (when configured to show). Check the menu item settings or overrides when not showing. See lines 29/31 of blog_item.php
