### ISSUE TITLE
Multiple Textarea/Editor Parameters in a Module Fail to Save

### ISSUE THREAD

**Issue by webmonkiee** [joomla/joomla-cms#6694]
#### Steps to reproduce the issue
Create a custom module that has two or more textarea (or editor) field types.

#### Expected result
Expect fields to save correctly.

#### Actual result
ALL fields (including text, menuitem, etc... types) are cleared and not saved.

#### System information (as much as possible)
Joomls! 3.4.1

#### Additional comments
This seems to have happened after the Joomla! 3.4.1 update.

**Comment by brianteeman** [comment]
Hi Jonathan - can you please supply some sample code - it will make it easier for people to test etc.

Also resetting the priority according to https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6694">issues.joomla.org/joomla-cms/6694</a>.</sub>

**Comment by webmonkiee** [comment]
Thanks Brian.

Here is the module xml file that is causing the initial issue. Basically any module with multiple textarea or editor field types.

<?xml version="1.0" encoding="utf-8"?>
<extension type="module" version="3.1" client="site" method="upgrade">
	<name>zHomepage Triple</name>
	<author>Zuno Studios</author>
	<creationDate>December 2014</creationDate>
	<copyright>Copyright (C) 2014 Zuno Studios. All rights reserved.</copyright>
	<license>http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL</license>
	<authorEmail>zunous@zunostudios.com</authorEmail>
	<authorUrl>www.zunostudios.com</authorUrl>
	<version>1.0.0</version>
	<description>This module displays three items—mainly used on the homepage</description>
	
	<files>
		<filename module="mod_zhomepage_triple">mod_zhomepage_triple.php</filename>
		<folder>tmpl</folder>
		<folder>language</folder>
		<filename>mod_zhomepage_triple.xml</filename>
	</files>
	
	<languages>
		<language tag="en-GB">en-GB.mod_zhomepage_triple.ini</language>
		<language tag="en-GB">en-GB.mod_zhomepage_triple.sys.ini</language>
	</languages>
	
	<config>
		
		<fields name="params">
			
			<fieldset name="basic">
				
				<field name="display_title" type="text" label="Display Title" description="" />
				<field name="display_subtitle" type="text" label="Display Sub-title" description="" />
				
				<field name="spacer1" type="spacer" label="&lt;h3&gt;Item 1&lt;/h3&gt;" />
				
				<field name="image1" type="media" label="Image/icon" description="Image to use above the copy" />
				<field name="title1" type="text" label="Title" description="Headline that appears below the image/icon" />
				<field name="copy1" type="textarea" label="Copy" description="Text that appears below the image/icon" />
				<field name="menuitem1" type="menuitem" label="Menu Item for Link" description="Select a menu item that the button for this item will link to">
					<option value="">-Select a menu item-</option>
				</field>
				<field name="buttontext1" type="text" label="Button Text" description="Text that will be displayed in the button" />
				
				<field name="spacer2" type="spacer" label="&lt;h3&gt;Item 2&lt;/h3&gt;" />
				<field name="image2" type="media" label="Image/icon" description="Image to use above the copy" />
				<field name="title2" type="text" label="Title" description="Headline that appears below the image/icon" />
				<field name="copy2" type="textarea" label="Copy" description="Text that appears below the image/icon" />
				<field name="menuitem2" type="menuitem" label="Menu Item for Link" description="Select a menu item that the button for this item will link to">
					<option value="">-Select a menu item-</option>
				</field>
				<field name="buttontext2" type="text" label="Button Text" description="Text that will be displayed in the button" />
				
				<field name="spacer3" type="spacer" label="&lt;h3&gt;Item 3&lt;/h3&gt;" />
				<field name="image3" type="media" label="Image/icon" description="Image to use above the copy" />
				<field name="title3" type="text" label="Title" description="Headline that appears below the image/icon" />
				<field name="copy3" type="textarea" label="Copy" description="Text that appears below the image/icon" />
				<field name="menuitem3" type="menuitem" label="Menu Item for Link" description="Select a menu item that the button for this item will link to">
					<option value="">-Select a menu item-</option>
				</field>
				<field name="buttontext3" type="text" label="Button Text" description="Text that will be displayed in the button" />
							
			</fieldset>
			
			<fieldset name="advanced">
				
				<field
					name="layout"
					type="modulelayout"
					label="JFIELD_ALT_LAYOUT_LABEL"
					description="JFIELD_ALT_MODULE_LAYOUT_DESC" />
				
				<field name="show_top_arrow" type="list" default="1" label="Top Arrow" description="Select whether to show the top arrow">
					<option value="1">Show</option>
					<option value="0">Hide</option>
				</field>
				
				<field name="show_bottom_arrow" type="list" default="1" label="Bottom Arrow" description="Select whether to show the bottom arrow">
					<option value="1">Show</option>
					<option value="0">Hide</option>
				</field>
				
				<field name="moduleclass_sfx" type="text" default="" label="Module Class Suffix" description="fieldMODULECLASSSUFFIX" />
				
				<field name="owncache" type="list" default="1"
					label="COM_MODULES_FIELD_CACHING_LABEL" description="COM_MODULES_FIELD_CACHING_DESC" >
					<option value="1">JGLOBAL_USE_GLOBAL</option>
					<option value="0">COM_MODULES_FIELD_VALUE_NOCACHING
					</option>
				</field>
			
				<field name="cache_time" type="text" default="900"
					label="COM_MODULES_FIELD_CACHE_TIME_LABEL" description="COM_MODULES_FIELD_CACHE_TIME_DESC" />
			
			</fieldset>
			
		</fields>
		
	</config>

</extension><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6694">issues.joomla.org/joomla-cms/6694</a>.</sub>

**Comment by bertmert** [comment]
I **cannot** confirm/replicate for J!3.4.1 and Staging (2015-04-05).

I made some tests with several core modules where I added something like this in XML file (2 editors, 2 textareas).

```
...
	<customContent />
	<config>
 <fields name="params">
  <fieldset name="basic">

<!--ADD THIS-->
<field name="articletext" type="editor"
label="articletext"
filter="JComponentHelper::filterText" buttons="false" />

<field name="articletextarea" type="textarea"
label="articletextarea" />

<field name="articletext2" type="editor"
label="articletext2"
filter="JComponentHelper::filterText" buttons="true" />

<field name="articletextarea2" type="textarea"
label="articletextarea2" />
<!--/ADD THIS-->
...
```

Then I copied your whole CONFIG block to core modules. Also no problems. All fields were saved correctly.

**Comment by anamikakush** [comment]
Hello,

I am facing the same problem and i have 5 editor fields in custom module params and i have few text boxes fields, After filling the content in Editor and make it save then value of all the fields get blank/clean. 

It is working on localhost but when i upload on the server then it doesn't work. Please help to resolve the issue.

Regards,
Anamika<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6694">issues.joomla.org/joomla-cms/6694</a>.</sub>

**Comment by webmonkiee** [comment]
Hey @anamikakush we're still having this issue ourselves, but only on some sites in some instances. Even different sites on the same server are having issues—some work and others do not.

I'm not sure what it could be and we're still trying to exactly pin-point it ourselves.

-Jon

**Comment by brianteeman** [comment]
@webmonkiee please check your php error logs on the sites where it fails for any error message about max_input_vars<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6694">issues.joomla.org/joomla-cms/6694</a>.</sub>

**Comment by brianteeman** [comment]
It is several months since the request for further information which has not been provided. I am closing this at this time - it can always be re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6694">issues.joomla.org/joomla-cms/6694</a>.</sub>
