### ISSUE TITLE
CodeMirror 'Highlight Active Line' Enabled by Default

### ISSUE THREAD

**Issue by jneubauer** [joomla/joomla-cms#6695]
#### Steps to reproduce the issue
* Install Joomla 3.4
* Enable CodeMirror as the editor
* Open any content - notice the "active line" or html element your cursor is in (e.g. a paragraph, h3, etc.) is highlighted in blue - a confusing highlight since it's the same color the browser highlights _selected_ text in. screenshot: http://monosnap.com/image/1VKZ0zawTBTdohBCXpTn1G1j1WXUJr

#### Expected result
The CodeMirror plugin has the 'Highlight Active Line' parameter disabled by default - this highlighting should not be occurring. Screenshot of CodeMirror plugin parameters interface on a fresh install: http://monosnap.com/image/0ruDR2pTvv7T0saMRwBLXvB4uAL1UX

#### Actual result
The highlighting should not be happening unless this parameter is enabled. Currently you have to enabled the parameter, save the plugin, disable the parameter, and save the plugin again (different from just toggling it on and off and saving it once) in order to get the highlighting off. Screenshot of highlighting off (the state it _should_ be in from the beginning): http://monosnap.com/image/GQTgpX2paVQvTvz1mMfbImeKLiq72c

**Comment by Margreet137** [comment]
This issue I also encountered.
While testting at the pbf session I had a fresh installation of Joomla 3.4
When opening content everything is highlighted in blue.
The setting of the code mirror is Highlight active lins is OFF.
WWhen selecting text I have the color gray-blue (not much contrast).
After adjusting the setting Highlight active line to ON (save and close) end then setting back to OFF (save and close). It works like you expect due to thesetting of the code mirror.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6695">issues.joomla.org/joomla-cms/6695</a>.</sub>

**Comment by jneubauer** [comment]
Since this is still open, I figured I'd at least give it a look and see if I could sort it out.

In the sql file for installing Joomla, it looks like we only set default states for 10 of the 19 parameters the codemirror plugin has. Is there a reason for this? https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L573

My initial thought was to just add this one as one that we set by default, to ensure that the behaviour matches what is expected - but I'm thinking there might be an actual reason as to why we don't set default values for these other parameters.

Is that assumption correct?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6695">issues.joomla.org/joomla-cms/6695</a>.</sub>

**Comment by brianteeman** [comment]
Yes that is the bug we are not setting a default value so while the plugin says it is off it isnt until you save. Do you want to have a go at fixing that?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6695">issues.joomla.org/joomla-cms/6695</a>.</sub>

**Comment by brianteeman** [comment]
Closing s we have a PR now - thanks - see #7653 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6695">issues.joomla.org/joomla-cms/6695</a>.</sub>
