### ISSUE TITLE
False positive for isInstalled() due to querying element

### ISSUE THREAD

**Issue by nicksavov** [joomla/joomla-cms#6697]
I'm not 100% sure this is a bug, but here goes:

#### Steps to reproduce the issue
1) Uninstall weblinks
2) Install OSMap ([https://github.com/OSTraining/OSMap/releases/download/v3.0.2/com_osmap_free_3.0.2.zip](https://github.com/OSTraining/OSMap/releases/download/v3.0.2/com_osmap_free_3.0.2.zip ""))
3) In the administrator control panel (administrator/index.php), you should see an internal server error for the "Site Information" module:
> Error 1146: Table '_weblinks' doesn't exist SQL=SELECT COUNT(id) AS count_links FROM _weblinks WHERE state = 1

#### Expected result
The "Site Information" module should work. I'm guessing the error should be caught and it should degrade gracefully.

#### Actual result
Error 1146: Table '_weblinks' doesn't exist SQL=SELECT COUNT(id) AS count_links FROM _weblinks WHERE state = 1

#### Additional comments

It's because of this code:
[https://github.com/joomla/joomla-cms/blob/3.4.1/libraries/cms/component/helper.php#L102](https://github.com/joomla/joomla-cms/blob/3.4.1/libraries/cms/component/helper.php#L102 "")

It's querying for the "element", however the weblinks plugin in OSMap uses an element of "com_weblinks" because it's a weblinks plugin.

**Comment by brianteeman** [comment]
The issue does happen with your code BUT When you look at all other plugins you will see that the element is in the form "contacts" and not "com_contacts"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6697">issues.joomla.org/joomla-cms/6697</a>.</sub>

**Comment by Bakual** [comment]
I don't think we have a naming convention for the "element". The query actually is missing to check for the "type" as well since it's supposed to only return component entries.

https://github.com/joomla/joomla-cms/pull/6701 should fix this.

**Comment by brianteeman** [comment]
Only going by the fact that no other core plugin uses com_ in the element

On 8 April 2015 at 09:37, Thomas Hunziker <notifications@github.com> wrote:

> I don't think we have a naming convention for the "element". The query
> actually is missing to check for the "type" as well since it's supposed to
> only return component entries.
>
> #6701 <https://github.com/joomla/joomla-cms/pull/6701> should fix this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6697#issuecomment-90842910>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
Yep, core does use other element names. OSMap uses the names XMap originally used.
Neverthless the query is wrong anyway. We want to retrieve components only and thus need to filter by them :)

**Comment by Bakual** [comment]
Ignore my PR. Michael was earlier and does the same :smile:
