### ISSUE TITLE
Robots.txt to restricted for Google

### ISSUE THREAD

**Issue by miarava** [joomla/joomla-cms#6702]
The problem exists for a long time but will be worse in a few weeks as soon as google will change its policy regarding none mobile pages.

http://googlewebmastercentral.blogspot.de/2015/02/finding-more-mobile-friendly-search.html

The Google crawler is not allowed to receive content from the following nessecary locations to determine if the page is mobile friendly.

Disallow: /media/
Disallow: /modules/
Disallow: /plugins/
Disallow: /templates/
Disallow: /images/

These locations are important due to the possibility to store some of your code in all of those locations.

Check your Homepage! https://www.google.com/webmasters/tools/mobile-friendly/?utm_source=wmc-blog&utm_medium=referral&utm_campaign=mobile-friendly

If we dont act now a lot of Joomla homepages will be removed from mobile search results in the future.

**Comment by brianteeman** [comment]
Please check the updated robots.txt that was introduced in 3.4 to address
this.

**Comment by miarava** [comment]
Havent seen that, sorry.
Unfortunately the rules are still to restrictive.
There are a lot of plugin/module developers who store there css in the plugin/module folder and this code needs to be accesed to or it might interfere with mobile compatibility.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6702">issues.joomla.org/joomla-cms/6702</a>.</sub>

**Comment by brianteeman** [comment]
They shouldnt be storing it there. They should be storing it in /media. If
you want to change the rules on your own site then you can always edit them

On 8 April 2015 at 10:18, miarava <notifications@github.com> wrote:

> Havent seen that, sorry.
> Unfortunately the rules are still to restrictive.
> There are a lot of plugin/module developers who store there css in the
> plugin/module folder and this code needs to be accesed to or it might
> interfere with mobile compatibility.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/6702
> <http://issues.joomla.org/tracker/joomla-cms/6702>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6702#issuecomment-90857540>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Fedik** [comment]
@miarava it because that developers are lazy, 
we should not change Joomla! just because some lazy guy do not want make things right

**Comment by miarava** [comment]
I'm with you on this but that dosen't change the fact that myself and a lot of other developers have to fix hundrets of joomla installations and are unable to update the system because there might be changes to the robots.txt file.

**Comment by brianteeman** [comment]
Why are you unable to update the system? Makes no sense. #ycfs

**Comment by Fedik** [comment]
well, even if Joomla! will use that suggestion you still need to update all robots.txt in your installations manually ... joomla will not change it for you, because it could reset all custom rules that user already added manually, in that file

**Comment by miarava** [comment]
I agree. Already wrote a simple script to handle this problem. Maybe i should have thought about that.

## For people finding this post via Google
This is the crude script. Might help if you have to fix this the robots.txt on multiple servers with multiple joomla installations.
http://nopaste.linux-dev.org/?454235
Use with caution. There are way fewer checks in this script than necessary.

**Comment by PhilETaylor** [comment]
@miarava The Joomla Update distributions (for any decent version, like the Joomla 3.4.x series) all now use robots.txt.dist and so your customisations to robots.txt should never be wiped out on an update.
