### ISSUE TITLE
Kicks from admin

### ISSUE THREAD

**Issue by nukassel** [joomla/joomla-cms#6719]
#### Steps to reproduce the issue
Set, quick start template Purity III
Install the package Russian localization for admin
Did defaulted Russian language admin
Tried to edit any item
Click "Apply" or "Save" or "Apply and Save" (Then throws from admin)

#### Expected result
Should pop up message was successfully saved.
#### Actual result
A window appears authorization administration site.
#### System information (as much as possible)
Full information: http://piter1.dns-rus.net/phpinfo.php 
#### Additional comments
This error does not work only in the menu items, but also in any part of the site where you want to save something.
P.S. sorry for my English, I use a translator.

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org
