### ISSUE TITLE
Removed COM_CONTENT_MORE_ARTICLES?

### ISSUE THREAD

**Issue by flashfs** [joomla/joomla-cms#6723]
The constant COM_CONTENT_MORE_ARTICLES still exists in the language files, but it isn't showing anymore on the frontend.

With Joomla 2.5 we can see a <code>< h3><?php echo JText::_('COM_CONTENT_MORE_ARTICLES'); ?>< /h3></code> in /components/com_content/views/featured/tmpl/default_links.php file. With Joomla 3 it isn't there anymore, so there is nothing between the intro articles and the link articles on the frontpage.

**Comment by infograf768** [comment]
It is present in 
/templates/beez3/html/com_content/featured/ default_links.php 
and
/templates/beez3/html/com_content/category/blog_links.php

**Comment by flashfs** [comment]
But if the constant is present in a language core file, I see no sense its reference existing only on a template. But I can be wrong...

**Comment by zero-24** [comment]
@flashfs 

>But if the constant is present in a language core file, I see no sense its reference existing only on a template. But I can be wrong...

Currently beez3 are core files. ;)

We can't remove langstrings until 4.0 for B/C reasons following our B/C

>6.1.6 Language keys

>Changing or deleting a language key is considered a backwards compatibility break. Adding new ones is not. Substantially changing the meaning associated with a language key is a compatibility break. Rephrasing something for a more accurate description or proper en-GB grammar is not.

see: http://developer.joomla.org/cms/development-strategy.html

So I'm closing here as Expeced behavior :smile: Thanks!
