### ISSUE TITLE
MSSQL Cannot creating Menu Item of "External URL" Joomla 3.3.6 

### ISSUE THREAD

**Issue by desmondhughes** [joomla/joomla-cms#6725]
I tried to create an external link to a pdf file but it doesn't accept the option. This is on a freshly installed version of Joomla.

**Comment by brianteeman** [comment]
Please test on the latest release of Joomla which is 3.4.1 as there have been a LOT of fixes

**Comment by desmondhughes** [comment]
Thanks will try that and will let you know.

**Comment by desmondhughes** [comment]
Hi Brian,

 

Every time I try to do an update it pops up a msg saying “The archive file is corrupt, truncated or the archive parts are missing”

 

Thanks for your help

Desmond

**Comment by zero-24** [comment]
@desmondhughes 

Try to download and install: https://github.com/joomla/joomla-cms/releases/download/3.4.1/Joomla_3.4.1-Stable-Full_Package.zip

**Comment by desmondhughes** [comment]
I don’t want to overwrite my current installation because I will loose all my changes. Why doesn’t the update work?

**Comment by zero-24** [comment]
upps wrong package :smiley: This is the same as the updater will taken: https://github.com/joomla/joomla-cms/releases/download/3.4.1/Joomla_3.4.1-Stable-Update_Package.zip

**Comment by desmondhughes** [comment]
Can you tell me briefly how to install the update using an external file?

**Comment by zero-24** [comment]
>Can you tell me briefly how to install the update using an external file?

1. Option
- download
- updload as extension

2. option
- use the install from URL feature.
- paste the URL
- try the install button :smile:

**Comment by desmondhughes** [comment]
Sorry I am having so much crap with this installation:

 

fsockopen(): unable to connect to ssl://github.com:443 (Unable to find the socket transport &quot;ssl&quot; - did you forget to enable it when you configured PHP?)

**Comment by zero-24** [comment]
>Sorry I am having so much crap with this installation:

Localhost? Try to use option 1 :smile:

**Comment by desmondhughes** [comment]
I tried these options:

 

Install from directory:

Error

Please enter a package directory

 

Install from URL:

 

fsockopen(): unable to connect to ssl://github.com:443 (Unable to find the socket transport &quot;ssl&quot; - did you forget to enable it when you configured PHP?)

**Comment by zero-24** [comment]
>Install from directory:

Try: https://docs.joomla.org/J3.x:Updating_Joomla_(Install_Method)

**Comment by desmondhughes** [comment]
I still get this error:

 

fsockopen(): unable to connect to ssl://docs.joomla.org:443 (Unable to find the socket transport &quot;ssl&quot; - did you forget to enable it when you configured PHP?)

 

I need to set something in the PHP config

**Comment by zero-24** [comment]
>I still get this error:

hehe not install as URL :smile: read as there is explained how you can install the update :smile:

**Comment by desmondhughes** [comment]
Ok you got me, where must I read?

**Comment by zero-24** [comment]
>Ok you got me, where must I read?

https://docs.joomla.org/J3.x:Updating_Joomla_(Install_Method)

**Comment by desmondhughes** [comment]
Sorry I did not read the email correctly so yes I have tried all those options mentioned in that link but none work for me. I don’t know what I have missed. I have done it many times before.

**Comment by zero-24** [comment]
>Sorry I did not read the email correctly so yes I have tried all those options mentioned in that link but none work for me. I don’t know what I have missed. I have done it many times before.

hmm than only the following will work to become the last version.
- backup you site
- download the full package (https://github.com/joomla/joomla-cms/releases/download/3.4.1/Joomla_3.4.1-Stable-Update_Package.zip)
- extract
- remove the folder `installation
- copy and replace all files
- run a database fix at the backend

**Comment by desmondhughes** [comment]
Ok I finally installed the update using the “install from directory” thanks.

 

But the reason why I did the update was to fixed the problem where I cannot create a menu option for an external linked file. When I select “External URL” it does nothing. But if I use a fresh install it does work.

**Comment by desmondhughes** [comment]
After Installing, can I just copy the backed up files from the site that didn’t work correctly over the files in he new installation?

**Comment by zero-24** [comment]
>When I select “External URL” it does nothing. But if I use a fresh install it does work.

try to clean your cache (Joomla and Browser Cache)
try a databse fix (Extension -> Extension Manger --> Database --> Button Fix)

**Comment by desmondhughes** [comment]
Did what you said but still nothing....

**Comment by zero-24** [comment]
>Did what you said but still nothing....

hmm as a new install works but only the updated not please try to compare files and database. Sorry I can't do anything remotly ;)

**Comment by desmondhughes** [comment]
I appreciate all your help. It is so frustrating when a small thing like this stops a site from going live. I guess I will have to install a whole new site and add my changes manually again. 


Sent from my Samsung Galaxy smartphone.-------- Original message --------

**Comment by zero-24** [comment]
As it works on the new installed joomla and it looks like there are other issues like

>fsockopen(): unable to connect to ssl://github.com:443 (Unable to find the socket transport &quot;ssl&quot; - did you forget to enable it when you configured PHP?)

I guess we can close here? Can we?

**Comment by desmondhughes** [comment]
We can. :-(


Sent from my Samsung Galaxy smartphone.-------- Original message --------
