### ISSUE TITLE
Problem with smartsearch suggestion dropdown showing

### ISSUE THREAD

**Issue by janstieler** [joomla/joomla-cms#6726]
Hello,
today I noticed on a new Joomla Website that somthing is strange with the indexed smartsearch from Joomla and its searchterm suggestion.
As example I want to search through "Max Musterman".
Now I start to write Max. On writing I see the dropdown with the suggestion "Max Musterman". But after I finished writing "Max" the suggestion is hidden and after I write a space after "Max" it will showing again.

This is not really a good usability, is this normal in Joomla or what can I do to correct the suggestion dropdown?

I'm using Joomla 3.4.1

Kind regards

**Comment by Margreet137** [comment]
The smart search function works just as described in this issue.
But I think this is the right way it works (in my experience)
It is similar to the way Google works.
If you have a search string with two words.
In your case smart search finds a complete word Max and then it stops. When you need two words you must give a space and then smart search knows you need more words. It works like you expected you get new suggestions.
After typing Max Musterman smart search finds an exact match and stops.
I have tested it on the pbf with the search related items and it works just as you described.

I think this is right and intended as the developers want it.
If I am wrong then would someone of the developers give a comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6726">issues.joomla.org/joomla-cms/6726</a>.</sub>
