### ISSUE TITLE
keepalive does not "keep alive" when session handler not a database and session time bigger than few minutes

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#6730]
Keepalive does not "keep alive" when session handler not a database and session time   bigger than few minutes

#### Steps to reproduce the issue
* set session handler to something different from database, example set "none" (will be used PHP default, in most cases it is "file" session handler)
* set session time 60 minutes or even more
* open article to edit, and go drink a tea/coffee for next 15 minutes
* after coffee is done, try refresh previous opened page

#### Expected result
you still see the form for edit article

#### Actual result
You get login page

#### Additional comments
could be need wait more than 15 minutes, this depend from the server configuration

**Comment by zero-24** [comment]
@Fedik as this is fixed by #4904 i will close here. Thanks :smile:
