### ISSUE TITLE
Joomla 3.4.1 generating url addresses that I have not created

### ISSUE THREAD

**Issue by desaby** [joomla/joomla-cms#6733]
#### Steps to reproduce the issue
I do not know how to reproduce the issue. I do not know where we get this strange bug, but Joomla generates strange url addresses. Set to exist url Joomla add parts of other existing addresses and receives a long combination which leads to a completely different page
/Someone url addresses sre in Cyrillic /
Example:
Original page:
www.loto-bilety.com/zolotoy-klyuch-proverity-bilet-862-tirazh-07-02-2015.html
Wrong URL:www.loto-bilety.com/zolotoy-klyuch-proverity-bilet-863-tirazh-14-02-2015/13-%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%BE%D0%B9-%D0%BA%D0%BB%D1%8E%D1%87/35-zolotoy-klyuch-proverity-bilet-862-tirazh-07-02-2015.html

Furthermore all pages load with or without .html at the end.
#### Expected result
Аassigned address

#### Actual result
Combination of URL addresses

#### System information (as much as possible)
Joomla 4.41, All SEO settings set to YES, Unicode Aliases to NO with YES is same.
Ubuntu Server Edition
Apache: 2.4.10-1-beget-reuseport
mysql: percona 5.6.21-70.0-1-beget
PHP: 5.5.20

#### Additional comments
Same problem with 3.36 ticket [#6435]

**Comment by Fedik** [comment]
Joomla 4.41 ? 
where I can download it? :smile:

**Comment by Fedik** [comment]
Please check that comment https://github.com/joomla/joomla-cms/issues/6435#issuecomment-81140419

**Comment by infograf768** [comment]
At one moment or another you surely have set Unicode alias to Yes, which has let you create these unicode urls. They are fine. 

Example:
http://www.loto-bilety.com/%D0%B0%D1%80%D1%85%D0%B8%D0%B2-%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%BE%D0%B9-%D0%BA%D0%BB%D1%8E%D1%87.html
(http://www.loto-bilety.com/архив-золотой-ключ.html)

www.loto-bilety.com/zolotoy-klyuch-proverity-bilet-863-tirazh-14-02-2015/13-%D0%B7%D0%BE%D0%BB%D0%BE%D1%82%D0%BE%D0%B9-%D0%BA%D0%BB%D1%8E%D1%87/35-zolotoy-klyuch-proverity-bilet-862-tirazh-07-02-2015.html

is the same as
www.loto-bilety.com/zolotoy-klyuch-proverity-bilet-863-tirazh-14-02-2015/13-золотой-ключ/35-zolotoy-klyuch-proverity-bilet-862-tirazh-07-02-2015.html

When using Firefox or Chrome, copying the urls gets the percent encodings. If you use Safari you will directly get the real characters.

**Comment by desaby** [comment]
Problem is that I did not creat them. 
.../13-золотой-ключ/35-zolotoy-klyuch-proverity-bilet-862-tirazh-07-02-2015.html this thing appear from some kind of bug after real part of url wich is: www.loto-bilety.com/zolotoy-klyuch-proverity-bilet-863-tirazh-14-02-2015.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6733">issues.joomla.org/joomla-cms/6733</a>.</sub>

**Comment by pl71** [comment]
Yes, Google indexed some strange URL:
/menu_1/sub_menu_1/xx-category_1, where xx is some number.
Actually I never created such link.

**Comment by desaby** [comment]
I remove links from google webmaster tools but new strange links appear. It is really very strange.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6733">issues.joomla.org/joomla-cms/6733</a>.</sub>

**Comment by PhilETaylor** [comment]
There is no problem to fix here - recommend closing this.

**Comment by Bakual** [comment]
Various modules and views from component create links which may not be exactly what you have created as menu item. Those may even be 3rd party extensions.

It's a known issue which likely gets improved with the new router proposed by Hannes. But most likely you will still see some of them even with that work being merged.

If you can find out where exactly the links are generated, we could maybe help you. But most likely it's a topic which should be handled on the forum first.

Closing for now.
