### ISSUE TITLE
Problem with inputting Cyrillic symbols in Com_Tags

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#6739]
#### Steps to reproduce the issue
I've noticed a problem when I'm trying to input tags in Cyrillic symbols. 
For instance, Russian word "Альбом" (Album). 
The system strip or replace some letters. 
I've tried in FF and Chrome (latest versions) in article edit mode at administration and front-end side.

#### Expected result
Words in Cyrillic shouldn't be stripped. We must get exactly the word we're inputting.

#### Actual result
When I'm inputting a word Альбом, the system automatically strip letters and makes Альб or replace symbols and generate Альом. The same problem with another words when I'm using Cyrillic symbols.

#### System information (as much as possible)
Joomla 3.4.1. But I've noticed this issue in earlier versions too (3.3.6+)

#### Additional comments
Here are animated screens to show the problem:
https://www.dropbox.com/s/ehe7m4xdqw4gun5/ff.gif?dl=0 - attempt to input a word Album in Russian. Administration side. Article edit mode.
https://www.dropbox.com/s/8gmqdp2wud5d6g0/joomlaportal.gif?dl=0 - the same issue in front-end. but there is no problem with English equivalent of this word (Album).

**Comment by infograf768** [comment]
Have you tried setting Unicode Alias to Yes in Global Configuration?
Here, if I do so, I get:
http://localhost:8888/trunkgitnew/component/tags/tag/21-альбом.html
for
![screen shot 2015-04-11 at 08 37 15](https://cloud.githubusercontent.com/assets/869724/7100511/3a0e609c-e026-11e4-9da9-1c1ae67954f4.png)

tag was created as:

![screen shot 2015-04-11 at 08 40 46](https://cloud.githubusercontent.com/assets/869724/7100514/7d4cc010-e026-11e4-82de-b97529fe8a4c.png)

**Comment by Sulpher** [comment]
No, I am always avoid using Unicode alias to keep URLs in Latin.
All com_content aliases automatically transliterates into Latin symbols when I'm assigning Russian localization. I.e. Альбом gets albom alias. But problem not with saving or copying, the problem is in typing a word in Cyrillic.

**Comment by infograf768** [comment]
As you see, and taking the alias out of the scope, I had no issue here.

**Comment by Sulpher** [comment]
Did you type each letter or just copy / pasted this word? The problem appears when I am trying to input each symbol as I shown it at animated screenshots. Sometimes it's possible to input a word, in some case is not. Kind of floating bug.

**Comment by infograf768** [comment]
I have no Cyrillic keyboard, but I doubt that this would be related to Joomla.

**Comment by infograf768** [comment]
Sorry, I see now that it is not in the manager that you have issues, but in the dropbox.

**Comment by Sulpher** [comment]
I'll ask other users from local community to check out this issue to be sure it's not problem of my computer, but common problem. And come back with info. Thank you.

**Comment by AlekVolsk** [comment]
I hereby certify that the problem occurs, when values are entered in the national, non-English keyboard layout, only with manual set of values from the keyboard (not paste from clipboard) and then acquired by Enter. (translated into translate.google.com)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6739">issues.joomla.org/joomla-cms/6739</a>.</sub>

**Comment by infograf768** [comment]
Tested by changing my keyboard to Cyrillic and I confirm we do have an issue when creating a new tag in the "tag" type field.
Here, after typing 3 characters, the 4th one does display for a short time then does not display fully.
Going on typing does work although we do not see the glyph.
When finished typing, I had to use the top arrow on the keyboard to move back up to the line where I entered the new tag. Then the full text entered displays and hitting enter does work fine.
I guess the issue comes from the ajaxfield method.

**Comment by infograf768** [comment]
Thanks @phproberto  for looking at this.

**Comment by Fedik** [comment]
reason of the problem with word "Альбом" is that char `б` have same keycode as `,` (188) in english layout,
the tagajax field check this keycode for "add new tag"

**Comment by infograf768** [comment]
@Fedik
I had the same issue when not using `б`

**Comment by Fedik** [comment]
@infograf768 seems here a couple issues, first:
>  after typing 3 characters, the 4th one does display for a short time then does not display fully

and second with `б`, `,` keycode

**Comment by Fedik** [comment]
for first issue could be need to hack Chosen.js, in some reason it [do not see the value](https://github.com/joomla/joomla-cms/blob/staging/media/jui/js/chosen.jquery.js#L1221) and so reset the width

and about, keycode conflict, not sure how to fix it in b/c way, more simple it just remove [check for code 188](https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/html/tag.php#L196)

**Comment by brianteeman** [comment]
After over a year and no suggestions how to resolve this I am closing this,It can always be re-opened if smeone has an idea how to resolve this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6739">issues.joomla.org/joomla-cms/6739</a>.</sub>
