### ISSUE TITLE
Impossible to select 'all' items in lists anymore.

### ISSUE THREAD

**Issue by slibbe** [joomla/joomla-cms#6743]
#### Steps to reproduce the issue
Browse through list screens and try to set amount of items shown per page to 'all'.

#### Expected result
Possibility to select 'all'.

#### Actual result
'all' is not available to choose.

#### System information (as much as possible)
Joomla 3.4 , I can't tell since when this is the current situation.

#### Additional comments
In list screens as articles, menu_items and modules it is no longer possible to select 'all' at the bottom in order to avoid paging through loads of articles, menu_items, modules or whatever.
It can now only be invoked to browse through all by changing $list_limit in configuration.php to '0' . However this a general setting for all list screens.

**Comment by bertmert** [comment]
Cannot confirm/replicate.
Checked 4 Joomla 3.4.1. In any list view I could select ALL.

**Comment by bertmert** [comment]
> 'all' at the bottom

Or are you talking about template Hathor? If yes, it's a known issue https://github.com/joomla/joomla-cms/issues/6578.
Only fix at the moment is to use template Isis

**Comment by slibbe** [comment]
I see. We cheked this in different cases but didn't know it's at the top right now. Sorry for the confusion. This issue can be marked "closed".
