### ISSUE TITLE
Issues with the article module archive

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#6745]
#### Steps to reproduce the issue

- archive some articles
- enable and publish the archive modul
- at the frontend you will get something like this

![screen shot 2015-04-11 at 14 52 52](http://issues.joomla.org/uploads/1/178c85d26dff19904627aee9a6450e0d.png)
- the links look like:
`http://example.org/yyy/2009?view=archive&month=4` <- don't work. As it only use the month filter

Working would links like:
`http://example.org/yyy/index.php?view=archive&month=4&year=2009`

#### Expected result

Links would work and for every month we have one entry at the module

#### Actual result

we have more entry per month (see above) and the link don't apply the year to the filter.

#### System information (as much as possible)

The routing problems with the archive view are know:

https://github.com/joomla/joomla-cms/pull/5810

But i think if we disable the SEF routing here it will work?

#### Additional comments

Old reports:
https://github.com/joomla/joomla-cms/issues/5151
and
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=31698&start=25

`"The bug is a broken routing system, which will need a rewrite to actually work."`

Joomla Bugs referece:
http://www.joomla-bugs.de/forum/index.php/topic,666.msg3095.html#new

**Comment by Erftralle** [comment]
#6263 fixes at least the creation of multiple entries for the same month/year, but it does not fix the wrong SEF links. Therefore the router of com_content has to be modified. I spent some time to find a solution but unfortunately I did not make it.

**Comment by zero-24** [comment]
Thanks @Erftralle just tested and moved this PR to RTC

I will let this here open for the routing issue. Thanks!

**Comment by brianteeman** [comment]
@zero-24 I think it will be better if you close this one and create a new issue JUST for the routing issue

**Comment by zero-24** [comment]
Thanks @brianteeman Closing here. I will reopen an new issue later.

**Comment by kofaysi** [comment]
The issue still exist in J3.9.14. Did you, dear @zero-24, open a new issue for the routing issue, please? M

**Comment by zero-24** [comment]
Yes I did back then but it has not been solved yet. Please open a new issue so we can get someone working on that issue. Thanks!

**Comment by kofaysi** [comment]
https://github.com/joomla/joomla-cms/issues/27578
