### ISSUE TITLE
Login module redirects to non rewritten url (without alias from menu items)

### ISSUE THREAD

**Issue by markboos** [joomla/joomla-cms#6747]
#### Steps to reproduce the issue
Fresh Joomla 3.4.1 install, 
Install with the blog example: "Blog English (GB) exampledata"
Add new user with test, test
Use URL Rewriting = Yes
Rename htaccess.txt to .htaccess
Publish module "Login Form", Login Redirection Page = "About", Logout Redirection Page = "Home"

Go to homepage, for example http://www.projecten.eu
Login with test, test
After login you are redirected to http://www.projecten.eu/?id=1
While you should be redirected to http://www.projecten.eu/about

#### Expected result
When loging in, Redirect to http://www.projecten.eu/about
When loging out, Redirect to http://www.projecten.eu/

#### Actual result
Login: Redirect to http://www.projecten.eu/?id=1
Logout: Reditrecto to http://www.projecten.eu/about/9-blog?layout=blog

#### System information (as much as possible)
J.3.4.1
OS Linux
PHP 5.4.39
MySQL 5.5.41
Caching Disabled
GZip Disabled

htaccess:
                IndexIgnore *
                Options +FollowSymlinks
                Options -Indexes
                RewriteEngine On
                RewriteCond %{QUERY_STRING} base64_encode[^(]*\([^)]*\) [OR]
                RewriteCond %{QUERY_STRING} (<|%3C)([^s]*s)+cript.*(>|%3E) [NC,OR]
                RewriteCond %{QUERY_STRING} GLOBALS(=|\[|\%[0-9A-Z]{0,2}) [OR]
                RewriteCond %{QUERY_STRING} _REQUEST(=|\[|\%[0-9A-Z]{0,2})
                RewriteRule .* index.php [F]
                RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
                RewriteCond %{REQUEST_URI} !^/index\.php
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteRule .* index.php [L]

#### Additional comments
This seems to me since 3.4.0: on other websites i noticed after migration to 3.4.1 that the page urls after login were non rewritten by the login module. While before they were redirected to the rewritten url.

Go to page http://www.projecten.eu/about
Login with test, test
No error now, just the about page as expected.

From the (non-rewritten) logout page http://www.projecten.eu/about/9-blog?layout=blog
Login with test, test, then the redirect is ok again, but stays non-rewritten
http://www.projecten.eu/component/content/article?id=1

Is the htaccess rewrite code ok ? It seems to do its work only partially from the login module (stripping the "component/content/article" part).

**Comment by infograf768** [comment]
Can you test with staging as quite a few patches were done post 3.4.1 ?

**Comment by markboos** [comment]
Yes will do.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6747">issues.joomla.org/joomla-cms/6747</a>.</sub>

**Comment by markboos** [comment]
Tested in staging, and its solved.
Great to see things solved before  they are even reported ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6747">issues.joomla.org/joomla-cms/6747</a>.</sub>

**Comment by infograf768** [comment]
I guess this can be closed
