### ISSUE TITLE
Module Assingment for Custom HTML not working

### ISSUE THREAD

**Issue by MAD-King** [joomla/joomla-cms#6749]
#### Steps to reproduce the issue
created custom HTML module and assigned it to a position. Included or excluded pages where the module is shown or not.

#### Expected result
Module should be hidden on an excluded page

#### Actual result
Still shown on all pages

#### System information (as much as possible)
PHP Built On 	Linux gator4153.hostgator.com 3.12.35.1418868451 #1 SMP Wed Dec 17 20:10:32 CST 2014 x86_64
Database Version 	5.5.40-36.1
Database Collation 	utf8_unicode_ci
PHP Version 	5.4.38
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 

#### Additional comments
When I try to exclude or include pages the module gets always shown on all pages.
I tried it with Joomla 3.4.0 and 3.4.1
Problem in both versions.

**Comment by brianteeman** [comment]
Please describe in detailed steps exactly how you are trying to "exclude or
include pages the module gets always shown on"

On 12 April 2015 at 16:12, MAD-King <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> created custom HTML module and assigned it to a position. Included or
> excluded pages where the module is shown or not.
> Expected result
>
> Module should be hidden on an excluded page
> Actual result
>
> Still shown on all pages
> System information (as much as possible)
>
> PHP Built On Linux gator4153.hostgator.com 3.12.35.1418868451 #1
> <https://github.com/joomla/joomla-cms/pull/1> SMP Wed Dec 17 20:10:32 CST
> 2014 x86_64
> Database Version 5.5.40-36.1
> Database Collation utf8_unicode_ci
> PHP Version 5.4.38
> Web Server Apache
> WebServer to PHP Interface cgi-fcgi
> Joomla! Version Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
> Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ]
> 24-Apr-2013 00:00 GMT
> Additional comments
>
> When I try to exclude or include pages the module gets always shown on all
> pages.
> I tried it with Joomla 3.4.0 and 3.4.1
> Problem in both versions.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6749>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by losedk** [comment]
I can't reproduce this

**Comment by MAD-King** [comment]
Can I send someone from the dev team logins?

**Comment by brianteeman** [comment]
Sorry for the delay in replying. As it would appear to be specific to your site then the best place for support is the general forum http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6749">issues.joomla.org/joomla-cms/6749</a>.</sub>
