### ISSUE TITLE
Archieved articles view year selection hardcoded from 2005-now.

### ISSUE THREAD

**Issue by sam-suresh** [joomla/joomla-cms#6754]
#### Steps to reproduce the issue
Archived articles menu year selection hardcoded. 
To show from 2005-now

#### Expected result
Fetch archived articles years and show on dropdown.

#### Actual result

Showing all years from 2005-2015 (10 Years)

#### System information (as much as possible)

Joomla 3.4.1

**Comment by brianteeman** [comment]
Actually its hard coded to be this year minus 10 
https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/archive/view.html.php#L114<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6754">issues.joomla.org/joomla-cms/6754</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i agree with this, the years shouldn't be hardcoded, should only appear the years from with there are articles in the database.  Perhaps a form field generate with db values, similar to the position filed in the admin com_modules filter?

- https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/models/forms/filter_modules.xml#L33

- https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/models/fields/modulesposition.php

- https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/helpers/modules.php#L98

**Comment by brianteeman** [comment]
I was thinking that it should be dynamic based on the content
So if you have archived content from 1999 the year will start at 1999
but if you then delete that content and the oldest archived content is now
2002 the year will start at 2002

On 14 April 2016 at 11:47, andrepereiradasilva <notifications@github.com>
wrote:

> i agree with this, the years shouldn't be hardcoded, should only appear
> the years from with there are articles in the database. Perhaps a form
> field generate with db values, similar to the position filed in the admin
> com_modules filter?
>
>    -
>
>
>    https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/models/forms/filter_modules.xml#L33
>    -
>
>
>    https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/models/fields/modulesposition.php
>    -
>
>
>    https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/helpers/modules.php#L98
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6754#issuecomment-209876203>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
yes, get the year of the oldest archived article and start from that year.
it would work also, and maybe be simpler.

**Comment by sam-suresh** [comment]
When years displayed and no content, it is time wasting for users to search which year has archive and it is not relevant to show years without content.

It will be awesome if Joomla can fetch years based on archive availability.

**Comment by brianteeman** [comment]
Closed as we have a PR #10059 for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6754">issues.joomla.org/joomla-cms/6754</a>.</sub>
