### ISSUE TITLE
Multilanguage Problems with Falang

### ISSUE THREAD

**Issue by Seppo48** [joomla/joomla-cms#6757]
#### Steps to reproduce the issue

Hello I bought today Falang 2.0.0 for Joomla 3.4.
After instalation i get the following error message in the backend

An error has occurred .

    1146 Table ' SUNSHINE_TEST.mhoqa_falang_tableinfo ' does not exist SQL = SELECT tablename joomla , tablepkID FROM ` mhoqa_falang_tableinfo`

It is impossible to install it ! Does anyone have an idea

**Comment by rdeutz** [comment]
You should ask this question the Falang guys, this here is the Joomla issue tracker. Please close this issue.

**Comment by Seppo48** [comment]
Okay thank you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6757">issues.joomla.org/joomla-cms/6757</a>.</sub>
