### ISSUE TITLE
Isis sidebar needs some modifications for accessibility

### ISSUE THREAD

**Issue by dgt41** [joomla/joomla-cms#6758]
I recently went ahead and installed chrome vox plugin and tried it on backend with isis. There are many things that needs to be improved, but the most obvious is the faulty hidden sidebar. So try this:
go to `administrator/index.php?option=com_users&view=users`
and HIDE the sidebar!
now start navigating with the tab
the order after the help button on the toolbar is wrong!
It should be highlighting the search field but instead is highlighting the hidden elements of the sidebar!

How to solve this?
The script that hides/shows the sidebar should also inject `aria-hidden="true"` to the ul element when that is hidden and remove it when the sidebar is viewable.

**Comment by vinespie** [comment]
Adding attributes "aria-hidden" set to "true" and "tabindex" set to "-1" when sidebar is hidden. If visible these attributes are removed.

## Test instructions
1. Go to Admin
2. Go to users manager / article manager
3. Hide the sidebar
4. Start navigation with the tab
5. After the help button, you must go to search field
6. Show the the sidebar
7. Restart navigation whith the tab
8. You must pass in the sidebar links

**Comment by dgt41** [comment]
@vinespie I think you should open a pull request against staging, so we can close this issue. Other than that :+1:

**Comment by vinespie** [comment]
@dgt41I can not go back on the commit. Can you give me a tip?

**Comment by dgt41** [comment]
Try:
https://github.com/joomla/joomla-cms/pulls
press the green button New Pull Request
click on "compare across forks"
Select joomla staging and vinespie staging
Then just name the PR e.g. Accessibility enhancement for sidebar
and copy paste the description and testing instructions from here!

**Comment by roland-d** [comment]
@dgt41 This can't be merged since there is no pull request. Let's wait until @vinespie made his pull request.

**Comment by dgt41** [comment]
There is a PR #7024 that solves this
