### ISSUE TITLE
Joomla Database error

### ISSUE THREAD

**Issue by grxsolution** [joomla/joomla-cms#6759]
Can anyone tell me how to correct this Joomla Database Error?

Database schema version (3.3.6-2014-09-30) does not match CMS version (3.4.0-2015-02-26)

![database](https://cloud.githubusercontent.com/assets/11929523/7121808/1a98617a-e1e5-11e4-855b-34bf6bb6aed4.jpg)

**Comment by zero-24** [comment]
>Can anyone tell me how to correct this Joomla Database Error?

Try the `Fix` Button. :smile:

**Comment by grxsolution** [comment]
I did that didn't work.
