### ISSUE TITLE
Issue with category columns - not possible to have more than 1 column of sub-categories

### ISSUE THREAD

**Issue by radik10** [joomla/joomla-cms#6772]
#### Steps to reproduce the issue
create 1 main article category and later 2-3 sub-categories belonging to main category and display them (sub-categories) in menu item (index.php?option=com_content&view=categories&id=xy)

#### Expected result
to have possiblity display categories in blog format - in more than 1 column (as is possible to display more columns of articles (blog), or K2 categories).
Settings for articles in blog format are not working for categories...

#### Actual result
1 column, not possible to have more columns (of sub-categories) on frontend

#### System information (as much as possible)
Joomla 3.4.1

**Comment by brianteeman** [comment]
If I understand you correctly you are expecting the category lists to be displayed in more than one column. This is not something that the core of Joomla offers as a feature but you could probably achieve it on your own web site using a template override for that view

**Comment by radik10** [comment]
Hi, thanks for reply. Yes, categories should be possible display in more columns as blog is possible (to display in several columns). Joomla is extremely complicated, even if you want to override basic parts of template, like have different types for blog or category or categories.... and it takes longer time to load pages if you have special needs for template (because of override basic structure).

Everything in Joomla template should be only in few files, in one template folder, and not in many other as is now (like for example "layouts/joomla/... or components/com_content/... and temlates/... and that all only for 1 override of temlate).

Because of complicated structure of Joomla, there are components like K2, Seblod, Zoo... Unfortunately sometimes you have to use Joomla core files, and other CCk components are useless, and customize Joomla template files is then headache.
Joomla must be less complicated and more flexible for non coders (non programmers) because of her popularity - without of need of other components and modules or plugins for basic webpages. 
That's the idea for Joomla developing team.
Best regards.Radovan
 


     On Thursday, April 23, 2015 2:07 AM, Brian Teeman <notifications@github.com> wrote:
   

 If I understand you correctly you are expecting the category lists to be displayed in more than one column. This is not something that the core of Joomla offers as a feature but you could probably achieve it on your own web site using a template override for that view—
Reply to this email directly or view it on GitHub.   

   
     On Thursday, April 23, 2015 2:07 AM, Brian Teeman <notifications@github.com> wrote:
   

 If I understand you correctly you are expecting the category lists to be displayed in more than one column. This is not something that the core of Joomla offers as a feature but you could probably achieve it on your own web site using a template override for that view—
Reply to this email directly or view it on GitHub.   

   
     On Thursday, April 23, 2015 2:07 AM, Brian Teeman <notifications@github.com> wrote:
   

 If I understand you correctly you are expecting the category lists to be displayed in more than one column. This is not something that the core of Joomla offers as a feature but you could probably achieve it on your own web site using a template override for that view—
Reply to this email directly or view it on GitHub.   

   
     On Thursday, April 23, 2015 2:07 AM, Brian Teeman <notifications@github.com> wrote:
   

 If I understand you correctly you are expecting the category lists to be displayed in more than one column. This is not something that the core of Joomla offers as a feature but you could probably achieve it on your own web site using a template override for that view—
