### ISSUE TITLE
Archived categories not selectable in category filter of articles list (backend)

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#6776]
- Go to articles manager and find a category with articles in it:

![archive](https://cloud.githubusercontent.com/assets/11038612/7141710/b67ecc5c-e2d3-11e4-865b-6bb34c67b3e3.jpg)

- Have a look into category filter:

![archive2](https://cloud.githubusercontent.com/assets/11038612/7141908/ed96de54-e2d4-11e4-8031-870b117b221b.jpg)

- Go to articles manager > categories and set state of found category to archived:

![archive4](https://cloud.githubusercontent.com/assets/11038612/7141835/5f0e4bcc-e2d4-11e4-9a8e-4d10ab506ec8.jpg)

- Go back to articles list and try to filter by archived category.

![archive3](https://cloud.githubusercontent.com/assets/11038612/7141712/b685630a-e2d3-11e4-8cf1-9805749c4970.jpg)

**Comment by brianteeman** [comment]
I can confirm this.

Interestingly unpublished categories are displayed although wrapped in [ ]  to indicate they are unpublished I assume

**Comment by bertmert** [comment]
No, unpublished categories aren't wrapped in brackets here.

---
Just BTW: Maybe someone knows how to elaborate.
I tried to add small icons inside select options:
Bootstrap knows attributes like
data-iconset="icomoon" data-icon="icon-published"
I could implement them but just nasty hard coded and gave up.
(Joomla forms ignore these attributes in select options and Bootstrap chosen.js doesn't take them over).

**Comment by zero-24** [comment]
Closing as we have a PR by @bertmert here: #6960
