### ISSUE TITLE
Fatal error when using " rebuild " in the menu list ui

### ISSUE THREAD

**Issue by Pikkolo** [joomla/joomla-cms#6777]
#### Steps to reproduce the issue

Fatal error when using " rebuild " in the menu list ui

#### Expected result

A rebuilt menu

#### Actual result

 Fatal error: Call to undefined method MenusModelItem::getMessage() in /home/fabriz01/public_html/subhosting/rebirth/administrator/components/com_menus/controllers/menus.php on line 118

**Comment by Bakual** [comment]
I can't reproduce it, but looking at the code the line is executed when the rebuild actually failed.
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/controllers/menus.php#L118
Maybe someone knows how to get that rebuild to fail, so it's possible to reproduce this issue.

`$model->getMessage()` likely should be `$model->getError()` instead.

**Comment by sovainfo** [comment]
Delete row 1.

**Comment by Pikkolo** [comment]
Sorry, is that " Delete row 1 " directed to me ? What should I delete ? Please let me know If i should just leave this ticket and move my help request on joomla forum, I don't want to make mess in the wrong area of the support system

**Comment by Pikkolo** [comment]
Looks like it's fixed, i m closing this if you agree :3

**Comment by Bakual** [comment]
> Looks like it's fixed

It's not fixed, your rebuild just did work for whatever reason now and didn't fail anymore.

https://github.com/joomla/joomla-cms/pull/6783 fixes the issue in case of a failed rebuild.

**Comment by sovainfo** [comment]
The first issue of @Pikkolo is fixed, because he inserted row 1 as instructed on the forum. The second issue (this one) fixed by #6783 which fixes the wrong message in case a rebuild fails, and removing row 1 of #__menu is the way to test that.
