### ISSUE TITLE
Whenever trying to create a new menu voice

### ISSUE THREAD

**Issue by Pikkolo** [joomla/joomla-cms#6778]
#### Steps to reproduce the issue
Whenever trying to create a new menu voice

#### Expected result

A new menu voice

#### Actual result

Save failed with the following error: exception 'UnexpectedValueException' with message 'MenusTableMenu::_getNode(1, ) failed.' in /home/fabriz01/public_html/subhosting/rebirth/libraries/joomla/table/nested.php:1542 Stack trace: #0 /home/fabriz01/public_html/subhosting/rebirth/libraries/joomla/table/nested.php(783): JTableNested->_getNode(1) #1 /home/fabriz01/public_html/subhosting/rebirth/libraries/legacy/table/menu.php(215): JTableNested->store(false) #2 /home/fabriz01/public_html/subhosting/rebirth/administrator/components/com_menus/models/item.php(1254): JTableMenu->store() #3 /home/fabriz01/public_html/subhosting/rebirth/administrator/components/com_menus/controllers/item.php(267): MenusModelItem->save(Array) #4 /home/fabriz01/public_html/subhosting/rebirth/libraries/legacy/controller/legacy.php(728): MenusControllerItem->save() #5 /home/fabriz01/public_html/subhosting/rebirth/administrator/components/com_menus/menus.php(18): JControllerLegacy->execute('apply') #6 /home/fabriz01/public_html/subhosting/rebirth/libraries/cms/component/helper.php(391): require_once('/home/fabriz01/...') #7 /home/fabriz01/public_html/subhosting/rebirth/libraries/cms/component/helper.php(371): JComponentHelper::executeComponent('/home/fabriz01/...') #8 /home/fabriz01/public_html/subhosting/rebirth/libraries/cms/application/administrator.php(98): JComponentHelper::renderComponent('com_menus') #9 /home/fabriz01/public_html/subhosting/rebirth/libraries/cms/application/administrator.php(152): JApplicationAdministrator->dispatch() #10 /home/fabriz01/public_html/subhosting/rebirth/libraries/cms/application/cms.php(252): JApplicationAdministrator->doExecute() #11 /home/fabriz01/public_html/subhosting/rebirth/administrator/index.php(42): JApplicationCms->execute() #12 {main}

**Comment by sovainfo** [comment]
Please use the forum for these kind of issues, this is for changes to Joomla, not for issues in your environment.

Use phpMyAdmin to restore missing row:
INSERT INTO `#__menu` (`id`, `menutype`, `title`, `alias`, `note`, `path`, `link`, `type`, `published`, `parent_id`, `level`, `component_id`, `checked_out`, `checked_out_time`, `browserNav`, `access`, `img`, `template_style_id`, `params`, `lft`, `rgt`, `home`, `language`, `client_id`) VALUES
(1, '', 'Menu_Item_Root', 'root', '', '', '', '', 1, 0, 0, 0, 0, '0000-00-00 00:00:00', 0, 0, '', 0, '', 0, 43, 0, '*', 0);

**Comment by Pikkolo** [comment]
Sorry about posting issues in the wrong place, i ll go with forum from now on :) Thanks huge for your patience
