### ISSUE TITLE
Tag display order in articles

### ISSUE THREAD

**Issue by ch2856** [joomla/joomla-cms#6779]
#### Steps to reproduce the issue
insert tags to an article by the order you want, save it, and the tags will be order in a different way (by id? name?)

#### Expected result
To be set the order the user insert them.

#### Actual result
Joomla order

#### System information (as much as possible)
j3.4.1

RTL - Hebrew

#### Additional comments
 Tags order are important for Tags - Similar module and other related by tags extensions.

**Comment by brianteeman** [comment]
Thank you for your suggestion but it has been decided that this is not something that will be included in the core of Joomla.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6779">issues.joomla.org/joomla-cms/6779</a>.</sub>
