### ISSUE TITLE
Secure SMTP options labels

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#6798]
I think the SMTP protocol configuration in a little confusing.

For what i understand, it says:
- "SSL" for SMTPS (SMTP with SSL or TLS protocol)
- "TLS" for SMTP with StartTLS

So maybe they should be:
COM_CONFIG_FIELD_VALUE_SSL = "SSL/TLS"
and
COM_CONFIG_FIELD_VALUE_TLS = "StartTLS"

Like, for instance, the e-mail account configuration in Mozilla Thunderbird: None; StartTLS; SSL/TLS

**Comment by brianteeman** [comment]
Would need to check the code to see what we are doing  but this is a useful reference document explaining the different protocols available and the common naming problem

https://www.fastmail.com/help/technical/ssltlsstarttls.html<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6798">issues.joomla.org/joomla-cms/6798</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Yes, that exacly the problem i described.

For instance having an SMTP mail server with:
- port 25: SMTP + StartTLS Extension) + Auth
- port 465: SMTPS + Auth
- port 587: SMTP + StartTLS Extension + Auth
And only supporting TLS 1.0+ protocols. No SSL protocol support.

When configuring joomla:
- port 25 or 587 works on Joomla "TLS" option, so i think is really SMTP+StartTLS
- port 465 works on Joomla "SSL" option, so i think is really SMTPS

For joomla user configuration pourposes the security protocol (SSL or TLS) implemented by the SMTP mail server is not relevant. Presuming every thing else is ok, if the user server supports the same security protocol and ciphers of the smtp mail server it will be ok.
For that pourpose, is more relevant if it uses SMTP or SMTP+StartTLS or SMTPS and in witch port.

More info:
- SMTP https://tools.ietf.org/html/rfc5321
- SMTP Start TLS https://tools.ietf.org/html/rfc3207

**Comment by andrepereiradasilva** [comment]
Closed. PR
