### ISSUE TITLE
Field to attachment file in contact email form

### ISSUE THREAD

**Issue by boscobass** [joomla/joomla-cms#6800]
It would be interesting to joomla add an attachment field in the contact form? In the admin could have the option to display or not this field

**Comment by brianteeman** [comment]
Hi

There are several extensions for Joomla that will do this already.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6800">issues.joomla.org/joomla-cms/6800</a>.</sub>
