### ISSUE TITLE
Edit, Edit State, Edit Own... missing Edit State Own

### ISSUE THREAD

**Issue by pieter-groeneweg** [joomla/joomla-cms#6801]
I have "author group" allowed to "edit" and "edit state"..
I also have an "author group 2" allowed to "edit own".. and I would want them to allow "edit state own" too...

This works ok in front end but when I allow this group admin access, the "author group 2" also can "publish" or "unpublish", set "featured" or "unset featured" content from others in the back end article manager. I would expect same behaviour front and back end.

 I would expect some Edit State Own in back end too

vanilla Joomla! 3.4.1 on a LAMP STACK apache 2 and PHP5.4

**Comment by Webdongle** [comment]
Yes can confirm that when a user who is logged in admin and has 
Create ........ Inherited ... Allowed
Edit .......... Inherited ... Not Allowed
Edit State .... Inherited ... Allowed
Edit Own ...... Inherited ... Allowed
They can publish/unpublish/trash/ set favourite Articles that they have no authority to edit.![screen shot 2015-04-18 at 19 26 18](http://issues.joomla.org/uploads/1/a5045d121f613bfb5dee951a18657edf.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6801">issues.joomla.org/joomla-cms/6801</a>.</sub>

**Comment by Webdongle** [comment]
Yes can confirm that when a user who is logged in admin and has 
Create ........ Inherited ... Allowed
Edit .......... Inherited ... Not Allowed
Edit State .... Inherited ... Allowed
Edit Own ...... Inherited ... Allowed
They can publish/unpublish/trash/ set favourite Articles that they have no authority to edit.![screen shot 2015-04-18 at 19 26 18](http://issues.joomla.org/uploads/1/a5045d121f613bfb5dee951a18657edf.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6801">issues.joomla.org/joomla-cms/6801</a>.</sub>

**Comment by pieter-groeneweg** [comment]
Created overrides to the admin template.

http://forum.joomla.org/viewtopic.php?f=719&t=882978

Of course there will be more brilliant ways of doing (coding) this. But it may be of any use.

**Comment by brianteeman** [comment]
Thank you for your suggestion but it has been decided that this is not something that will be included in the core of Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6801">issues.joomla.org/joomla-cms/6801</a>.</sub>

**Comment by web54** [comment]
I found this topic from the forum.

I expect this can be included ( or find a hack) to joomla.
If it is possible it should be a good thing.

We should have some groups that are allowed to edit state of their own items in a category as they can do in a cck.
Today we have custom fields to make great things ... Just thing about reciepes site : if people are allowed to edit state of other it could be a mess ... 

Thanks in advance if you could think about it ...

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6801">issues.joomla.org/tracker/joomla-cms/6801</a>.</sub>

**Comment by bembelimen** [comment]
With Joomla! 4 you can create such a scenario with the workflow.

**Comment by web54** [comment]
Great, but nowadays almost all our projects are in j3 and we are waiting for j4 for a long time.
For instance, my actual project will perherps never be in j4.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6801">issues.joomla.org/tracker/joomla-cms/6801</a>.</sub>
