### ISSUE TITLE
Unicode problem in created_by_alias (and other filtered fields)

### ISSUE THREAD

**Issue by astrolinux** [joomla/joomla-cms#6803]
#### Steps to reproduce the issue
Put the à (&amp;agrave;) character as last character of the field (for example: Saccà)

#### Expected result
After saving the à character is trimmed because $filter->clean($data['created_by_alias'], 'TRIM') deletes the second byte of the à character in Unicode representation. Saved field returns Sacc instead of Saccà.

**Comment by infograf768** [comment]
I confirm, for the letter `à` indeed as it contains `0xA0`. 
Weird though as we use `chr(0xC2) . chr(0xA0)` in code.
Tested with other unicode glyphs without any issue.
Adding a space after the `à` before saving solves the issue.

**Comment by infograf768** [comment]
We may have a solution;
Change this line (261):
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/filter/input.php#L261
`$result = trim($result, chr(0xC2) . chr(0xA0));`
to
`$result = JString::trim($result, chr(0xC2) . chr(0xA0));`

Can you test?

**Comment by infograf768** [comment]
Patch here:
https://github.com/joomla/joomla-cms/pull/6806

**Comment by fontanil** [comment]
@test: works for me, thanks!
