### ISSUE TITLE
Menu assignment in template manager not working in 3.4.1

### ISSUE THREAD

**Issue by palmaid** [joomla/joomla-cms#6805]
Hi!

I assigment some menu to an other template, but in website, use just the default template.

**Comment by dgt41** [comment]
Which templates are you using? 
Do you get a javascript error in your browser’s console?
Provide some more info

**Comment by palmaid** [comment]
I tried more template, but the problem is general.
http://badski.emegjelenes.hu/ --> use blackwhite2 template in default (http://www.icetheme.com/).
I assigmented some menu to other template (Beez3, protostar, etc.), but it not detected.
I tried more browser, but the problem is same.

**Comment by palmaid** [comment]
This menu use Beez3 template: http://badski.emegjelenes.hu/hu/teli-ajanlatok/siberlet-akciok.html

**Comment by Bakual** [comment]
Tried to reproduce it on my testing server but it's working fine there.

**Comment by palmaid** [comment]
I turned on the "show error", and I get 2 SQL Error (duplicate): http://badski.emegjelenes.hu/en/winter-deals.html

Duplicate this:
SELECT m2.language, m2.id
  FROM badski_menu as m
  INNER JOIN badski_associations as a 
  ON a.id=m.id 
  AND a.context='com_menus.item'
  INNER JOIN badski_associations as a2 
  ON a.key=a2.key
  INNER JOIN badski_menu as m2 
  ON a2.id=m2.id
  WHERE m.id=207

And This:
SELECT c2.language,CONCAT_WS(':', c2.id, c2.alias) AS id
  FROM badski_categories as c
  INNER JOIN badski_associations as a 
  ON a.id = c.id 
  AND a.context='com_categories.item'
  INNER JOIN badski_associations as a2 
  ON a.key = a2.key
  INNER JOIN badski_categories as c2 
  ON a2.id = c2.id 
  AND c2.extension = 'com_content'
  WHERE c.id =13 
  AND c.extension = 'com_content'

**Comment by palmaid** [comment]
What does the "Duplicate queries" mean?

**Comment by Bakual** [comment]
It just means the code could perform more optimised because it fetchs the same information twice from the database. It's not an error itself.

**Comment by palmaid** [comment]
If I turn of "Search Engine Friendly URLs", it would work. But I would like to use "SEF".

**Comment by dgt41** [comment]
do you have an .htaccess ?
is it the one from joomla or custom?

**Comment by palmaid** [comment]
Thanks,
I solved!
The problem was: I used the iceShortCode plugin to themplate. If I disabled, it's work.
