### ISSUE TITLE
Default hreflang tag and including full list of translated pages (including own url)

### ISSUE THREAD

**Issue by gijs007** [joomla/joomla-cms#6809]
#### Steps to reproduce the issue
Make a site with multiple languages

#### Expected result
The main/default language for a page should have a hreflang="x-default" tag as explained here:
http://googlewebmastercentral.blogspot.nl/2013/04/x-default-hreflang-for-international-pages.html

Additionally each page should have all languages with their respective URL's listed, including its own URL. (currently it only lists different ones)

#### Actual result
Only the other languages have a hreflang tag set, the loaded page language is not included.
Additionally the default language is not marked with an "x-default" tag.

#### System information (as much as possible)
Not relevant

#### Additional comments
I've discovered this issue trough using [http://seorch.eu/](http://seorch.eu/ "")

![screen shot 2015-04-20 at 14 09 22](http://issues.joomla.org/uploads/1/c92c6251edc039772d13ec25c0603995.png)

I also suggest reading:
[http://moz.com/learn/seo/hreflang-tag](http://moz.com/learn/seo/hreflang-tag "")
For best practises.

**Comment by infograf768** [comment]
In staging, the alternate was corrected as it was broken since 3.4.0. 
See https://github.com/joomla/joomla-cms/pull/6569
It will be available in 3.4.2

At reading your post, I see an issue when " Remove URL Language Code" is set to yes in the languagefilter plugin.
In that case the default site language IS the domain and we may get for the home page
`<link href="http://localhost:8888/testwindows/trunkgitnew/" rel="alternate" hreflang="en-GB" />`
when the site default language is en-GB and we are on another language page which 

I doubt we could also add...
`<link rel="alternate" href="http://localhost:8888/testwindows/trunkgitnew/" hreflang="x-default" />

the other hreflang are fine:
```
<link href="http://localhost:8888/testwindows/trunkgitnew/fr/" rel="alternate" hreflang="fr-FR" />
  <link href="http://localhost:8888/testwindows/trunkgitnew/de/" rel="alternate" hreflang="de-DE" />
  <link href="http://localhost:8888/testwindows/trunkgitnew/it/" rel="alternate" hreflang="it-IT" />
  <link href="http://localhost:8888/testwindows/trunkgitnew/es/" rel="alternate" hreflang="es-ES" />
  <link href="http://localhost:8888/testwindows/trunkgitnew/ta/" rel="alternate" hreflang="ta-IN" />
```

FYI, I am here on the Macedonian home page:
I get:
`<base href="http://localhost:8888/testwindows/trunkgitnew/mk/" />`
and
`<link href="/testwindows/trunkgitnew/mk/" rel="canonical" />`

**Comment by infograf768** [comment]
We can patch though to add as alternate, when loading a home page as well as associations, the page displayed itself. Not really sure we should.

**Comment by brianteeman** [comment]
Rest priority according to https://docs.joomla.org/Bug_and_Issue_Tracker_Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6809">issues.joomla.org/joomla-cms/6809</a>.</sub>

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6809">issues.joomla.org/joomla-cms/6809</a>

**Comment by infograf768** [comment]
See PR https://github.com/joomla/joomla-cms/pull/6963

closing as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6809">issues.joomla.org/joomla-cms/6809</a>.</sub>

**Comment by margieoestreich** [comment]
Bonjour
Je veux dire que les points positifs n'aiment pas les sites qui sont faits avec l'aide d'un système de gestion de contenu. Le système de gestion de contenu est Joomla, donc les systèmes de recherche n'aiment pas les sites qui utilisent Joomla. Ces sites doivent être optimisés avec - <a href='https://sitechecker.pro/fr/'>https://sitechecker.pro/fr/</a>, un programme qui donnera des indices sur la façon d'augmenter votre site dans les moteurs de recherche.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6809">issues.joomla.org/tracker/joomla-cms/6809</a>.</sub>

**Comment by ghost** [comment]
@margieoestreich please open a new Issue as Comments on closed Issues didn't get much Notice and also write English, thanks.

**Comment by infograf768** [comment]
This is not an issue, it is a spam imho

**Comment by ghost** [comment]
thanks @infograf768. @brianteeman can you please delete the Spam-Comment?
