### ISSUE TITLE
syntax error in tags.php FOFFormFieldTag->getRepeatable line 244

### ISSUE THREAD

**Issue by grapeguy** [joomla/joomla-cms#6811]
In libraries/fof/form/field/tag.php on line 244 there is a '.' missing on the return line.

Currently reads as:
return '&lt;span class="' $this->id . ' ' . $class . '">' .
			$html .
			'&lt;/span>';

Should read as:

return '&lt;span class="' . $this->id . ' ' . $class . '">' . 
			$html .
			'&lt;/span>';

This was noticed when I loaded Joomal3.4.1 into Eclipse.

**Comment by bertmert** [comment]
See PR https://github.com/joomla/joomla-cms/pull/6813 please.

**Comment by zero-24** [comment]
Closing as this will be fixed by the next upstream update of fof :+1:  (see: https://github.com/joomla/joomla-cms/pull/6813)
