### ISSUE TITLE
Smart Search indexing

### ISSUE THREAD

**Issue by franzpeter** [joomla/joomla-cms#6812]
#### Steps to reproduce the issue
If clicking on index inside the Smart Search (finder) Joomla opens a modal window telling about the progress. In my case the progress bar does only show progress if the indexing process shows: optimizing tables. So that: Your content is being indexed. Do not close this window does not show any progress report. It starts to show something only if the table optimization takes place.

#### Expected result

continuous progress report

#### Actual result
progress bar remains empty until table optimization occurs.

#### System information (as much as possible)
Joomla 3.4.1
Debian 7.8
PHP: 5.4.3.6
NGINX with PHP-FPM support for nginx
#### Additional comments
Seems that the progressbar has a few issues. Did test it on localhost too without NGINX: problem remains. The progress bar does not show progress, only if process finishes.

**Comment by dgt41** [comment]
@franzpeter try to empty your trash for items, menus, categories and try again

**Comment by franzpeter** [comment]
There is no trash inside items, menus and categories. I did test it with different installations. I think it has something to do with the way the progress bar operates (output buffering or so).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6812">issues.joomla.org/joomla-cms/6812</a>.</sub>

**Comment by Fedik** [comment]
@franzpeter how much content do you have on your site?
you have this problem on the clear Joomla installation? 
or you got this problem after install some additional component/plugin?
and can you please check the browser console, is there any error while indexing?

**Comment by franzpeter** [comment]
I did a clean install, so nothing except of the default example data: learn Joomla. I see the same: it takes a while until receiving a progress indication. It is somehow staggered not fluent. Maybe it should be that way. I do not know. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6812">issues.joomla.org/joomla-cms/6812</a>.</sub>

**Comment by franzpeter** [comment]
I did try it with an old J 2.5 installatiion too, there is a direct progress indication, while with J 3 it takes a while if there is more content to index until receiving the first response for progress bar. It seems to have something to do with buffering but the question is: Why on the same localhost with the same configuration J 2.5 delivers direct response while with J 3 it takes a while to show something. If there is not very much content, it will not show the indexing process and the first response occurs while optimizing tables. If there is more content to index, it takes a while for first response (the green progress bar for indexing).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6812">issues.joomla.org/joomla-cms/6812</a>.</sub>

**Comment by janich** [comment]
It can take a while for it to respond with the first notice, but it is true that it also may stall underway.
Have you tried lowering the numbers in the settings?

For the stalling, I'd propose to just alert the error out so the user isn't sitting for hours thinking it is just slow?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6812">issues.joomla.org/joomla-cms/6812</a>.</sub>

**Comment by dgt41** [comment]
@franzpeter I’ll just say that #5433 and #5386 were the two PR’s responsible for all the bootstrap changes. You can trace the changes yourself and see that there were no changes in the PHP part responsible for the the data provided for the ajax part. Also the javascript itself responsible for the updating of the messages and the progress bar is just touched only to change the mootools part to Jquery. 
But I have to mention that one of testers had a similar problem with very slow performance and we finally traced it down to some trashed content, which once deleted performance was restored. I guess the indexer php code needs some improvements here and there but I am quite busy right now to dig into that, if you can make some improvements I surely will provide some tests and feed back.

**Comment by RedsAnDev** [comment]
A little idea: when I click on index button, maybe, a little bottom bar appear with a realtime feedback.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6812">issues.joomla.org/joomla-cms/6812</a>.</sub>

**Comment by chrisdavenport** [comment]
Hi @franzpeter You created this issue sometime ago but have not provided any code for people to evaluate. As no one else has done so either and there is no clearly defined way to reproduce the problem, I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6812">issues.joomla.org/joomla-cms/6812</a>.</sub>

**Comment by chrisdavenport** [comment]
Set to "closed" on behalf of @chrisdavenport by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6812">issues.joomla.org/joomla-cms/6812</a>
