### ISSUE TITLE
Enable all for Redirect Manager

### ISSUE THREAD

**Issue by ch2856** [joomla/joomla-cms#6814]
#### Steps to reproduce the issue
Choose sort "all" and try to Enable all
It will work with 100,50...

#### Expected result
Enable for all

#### Actual result
No change in status

#### System information (as much as possible)

joomla 3.4.1

#### Additional comments
All action with "all" dose not working.
It will work with 100,50...

**Comment by brianteeman** [comment]
I suspect php is running out of memory - how many items is ALL on your system<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6814">issues.joomla.org/joomla-cms/6814</a>.</sub>

**Comment by ch2856** [comment]
About 1,200, but I guess you right. I have tried it on the articles (about 6,000) and had the same results - no change in status. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6814">issues.joomla.org/joomla-cms/6814</a>.</sub>

**Comment by Bakual** [comment]
Closing as a server issue out of Joomla control.
