### ISSUE TITLE
inconsistency setting filter via url in usermanager

### ISSUE THREAD

**Issue by carsten888** [joomla/joomla-cms#6815]
#### Steps to reproduce the issue
go to 
administrator/index.php?option=com_menus&view=items&filter_access=2
open 'search tools'
see that the select for 'access' is set to group 'registered'.

go to 
administrator/index.php?option=com_users&view=users&filter_group_id=2
open 'search tools'
note that the users are not filtered to group 'registered'

#### Expected result
administrator/index.php?option=com_users&view=users&filter_group_id=2 should show only the registered users

#### Actual result
administrator/index.php?option=com_users&view=users&filter_group_id=2 does not filter the users to the group as set in the url.

#### System information (as much as possible)
Joomla 3.4.1

**Comment by brianteeman** [comment]
I believe the correct url for building links with preselected filters is on the format

> /administrator/index.php?option=com_users&filter[group_id]=2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6815">issues.joomla.org/joomla-cms/6815</a>.</sub>

**Comment by carsten888** [comment]
thank you
