### ISSUE TITLE
Data in _overrider table entry prevents moving a site

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#6816]
#### Steps to reproduce the issue

Create a multilingual site (in my case 4 languages) on an xampp localhost installation.
Create a number of language overrides in each language.
View table entries _overrider: tables contain huge numbers of language file entries with complete path, e.g. C:\\xampp\\htdocs\\.....
Save site with e.g. AkeebabBackup and move to online server site

#### Expected result

Change an ovverride without problems

#### Actual result

Attempt to change an Override - can't be done - it's disappeared
View table on new site: - still contains the C:\\xampp\\htdocs\\.....
That has caused a lot of problems by calling up wrong paths

#### System information (as much as possible)

Localhost:
System Information
Setting   Value
 
PHP Built On   Windows NT RESOLVE-2010 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) i586
Database Version   5.5.32
Database Collation   utf8_general_ci
PHP Version   5.4.19
Web Server   Apache/2.4.4 (Win32) OpenSSL/0.9.8y PHP/5.4.19
WebServer to PHP Interface   apache2handler
Joomla! Version   Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version   Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent   Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

Online Server:

PHP Built On   Linux srv11.tophost.ch 2.6.18-448.4.1.el5.lve0.8.69.1 #1 SMP Tue Jul 2 18:36:25 EEST 2013 x86_64
Database Version   5.5.42-cll
Database Collation   utf8_general_ci
PHP Version   5.4.39
Web Server   Apache
WebServer to PHP Interface   cgi-fcgi
Joomla! Version   Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version   Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent   Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.90 Safari/537.36

#### Additional comments

This causes a great deal of grief, as there appear to be thousands of entries in that table.
The issue was raised quite a long time ago, but not resolved. See:
[Joomlacode](http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=30686 "Joomlacode Tracker")

I see no alternative at the moment except to use a tool such as the db-replacer from nonumber to manually change all the path entries.
My question is, why does this item need the full path? And how can the problem be resolved prior to a move?

**Comment by infograf768** [comment]
Once an override string has been created, the only use of the table is for the Search function when creating/editing a new override.

Maybe we could just empty the table at the end of the session?

**Comment by infograf768** [comment]
Or we can create a Purge button in the overrides Manager.

**Comment by coolman01** [comment]
Sounds good to me. 
I wish I could programme a solution, but sadly, that's not my strength.

**Comment by coolman01** [comment]
Currently I need to know if I can just delete all the entries in this table before I move it or not.

Also, this has cost me two days in rebuilding a site. I have a new site with 8 languages coming up and I'd appreciate it if this issue would be taken up by someone. Whoever designed the part which makes use of this table, may be a good person to sort it out. Currently there are 4502 entries in this table. This does not help with efficiency.

**Comment by infograf768** [comment]
Normally, each time you click in the search field when editing or creating a new override, the table is fully deleted and reconstructed.
In any case, I made a PR instating a Purge button. Please test.
https://github.com/joomla/joomla-cms/pull/6827

**Comment by coolman01** [comment]
@infograf768 
Thanks very much. I copied the files and added them. The button appears as expected and purges as expected. thank you very much.

**Comment by zero-24** [comment]
I'm going to close this issue as we have a PR by @infograf768 here: https://github.com/joomla/joomla-cms/issues/6827 Thanks :smile:
