### ISSUE TITLE
Front end module edit position error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#6817]
#### Steps to reproduce the issue
Create a module and set the "Menu assignment" to "On all pages except those selected"
Go to the front end and open that module for editing. Dont change anything just immediately save it.

#### Expected result
The  "Menu assignment" will not have changed

#### Actual result
The  "Menu assignment" will have changed from "On all pages except those selected" to ""only on the pages selected"

**Comment by joomdonation** [comment]
I can confirm the issue and made a small PR https://github.com/joomla/joomla-cms/pull/6819 to fix it.
