### ISSUE TITLE
Contact component grammar update to language file

### ISSUE THREAD

**Issue by gilestaylor** [joomla/joomla-cms#6818]
#### Steps to reproduce the issue
COM_CONTACT_FORM_LABEL="Send an Email. All fields with an * are required."

#### Expected result
COM_CONTACT_FORM_LABEL="Send an Email. All fields with an * are required."

#### Actual result
COM_CONTACT_FORM_LABEL="Send an Email. All fields with an * are required."

#### System information (as much as possible)
Joomla 3.4.1

#### Additional comments
Change 'an' to 'a'
COM_CONTACT_FORM_LABEL="Send an Email. All fields with a * are required."
Line 42

**Comment by brianteeman** [comment]
Thanks for contributing - however it is not correct. The * is an asterisk
not a star so it is perfectly correct for it to be AN and not A

On 22 April 2015 at 11:47, gilestaylor <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> COM_CONTACT_FORM_LABEL="Send an Email. All fields with an * are required."
> Expected result
>
> COM_CONTACT_FORM_LABEL="Send an Email. All fields with an * are required."
> Actual result
>
> COM_CONTACT_FORM_LABEL="Send an Email. All fields with an * are required."
> System information (as much as possible)
>
> Joomla 3.4.1
> Additional comments
>
> Change 'an' to 'a'
> COM_CONTACT_FORM_LABEL="Send an Email. All fields with a * are required."
> Line 42
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6818>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by gilestaylor** [comment]
Ah I will tell the proof reader thanks Giles

[image: Giles Taylor Design] <http://www.giles-taylor-design.co.uk>

*Giles Taylor* Creative Director
Giles Taylor Design (GTD)
0118 321 3436

giles@giles-taylor.co.uk
www.giles-taylor-design.co.uk
@giles_designer <http://www.twitter.com/giles_designer>

**Comment by brianteeman** [comment]
If you want to change it for your own site you can do so with a language
override https://docs.joomla.org/J3.x:Language_Overrides_in_Joomla

On 22 April 2015 at 12:30, gilestaylor <notifications@github.com> wrote:

> Ah I will tell the proof reader thanks Giles
>
> [image: Giles Taylor Design] <http://www.giles-taylor-design.co.uk>
>
> *Giles Taylor* Creative Director
> Giles Taylor Design (GTD)
> 0118 321 3436
>
> giles@giles-taylor.co.uk
> www.giles-taylor-design.co.uk
> @giles_designer <http://www.twitter.com/giles_designer>
>
> On 22 April 2015 at 11:57, Brian Teeman <notifications@github.com> wrote:
>
> > Thanks for contributing - however it is not correct. The * is an asterisk
> > not a star so it is perfectly correct for it to be AN and not A
> >
> > On 22 April 2015 at 11:47, gilestaylor <notifications@github.com> wrote:
> >
> > > Steps to reproduce the issue
> > >
> > > COM_CONTACT_FORM_LABEL="Send an Email. All fields with an * are
> > required."
> > > Expected result
> > >
> > > COM_CONTACT_FORM_LABEL="Send an Email. All fields with an * are
> > required."
> > > Actual result
> > >
> > > COM_CONTACT_FORM_LABEL="Send an Email. All fields with an * are
> > required."
> > > System information (as much as possible)
> > >
> > > Joomla 3.4.1
> > > Additional comments
> > >
> > > Change 'an' to 'a'
> > > COM_CONTACT_FORM_LABEL="Send an Email. All fields with a * are
> required."
> > > Line 42
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/joomla/joomla-cms/issues/6818>.
> > >
> >
> >
> >
> > --
> > Brian Teeman
> > Co-founder Joomla! and OpenSourceMatters Inc.
> > http://brian.teeman.net/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/joomla/joomla-cms/issues/6818#issuecomment-95137227
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6818#issuecomment-95144819>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by chrisdavenport** [comment]
Maybe change it to "All fields with an asterisk (*) are required."?  That would avoid the cognitive mismatch for those folks who read it as "a star".

**Comment by infograf768** [comment]
@chrisdavenport 
tbh, such a change is a bit useless and would force TTs to also look at this change, specially when some use Transifex.

**Comment by brianteeman** [comment]
See #6877<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6818">issues.joomla.org/joomla-cms/6818</a>.</sub>
