### ISSUE TITLE
This one is related to forum

### ISSUE THREAD

**Issue by adi8i** [joomla/joomla-cms#6822]
This issue is related to forum, but i don't have where to post it, so please label it with question, i will close after response.

I can't access the forum, i have an account but it say my ip was used for .... no idea what, something like is on a black list. And was used for spam in 2008, at that time i was playing pokemon, really.... so is there any way to access forum ?

don't tell me to use proxy....

**Comment by mbabker** [comment]
Sorry to hear that.  There's some anti-spam measures on the forum, some of them based on IP address.  If you fill out [this form](http://community.joomla.org/index.php?option=com_rsform&formId=3) the moderator team will get your access fixed.
