### ISSUE TITLE
Cant delete category in backend

### ISSUE THREAD

**Issue by ssnobben** [joomla/joomla-cms#6824]
#### Steps to reproduce the issue
1. Create a new category
2. Create a new menu "List all categories" and choose that new category.
3. Create an new article to that new category
Check all work and then delete the new article, the new menu and then the new category.

You get an error that you cant empty trash for deleting the category. 
Error
Delete not allowed for category Test category.1 item is assigned to this category.

#### Expected result
Should be able to empty trash for that trashed category.

#### System information (as much as possible)

Joomla 3.4.1 multisite config

**Comment by brianteeman** [comment]
did you empty the article trash? If not then this is expected behaviour and
the error message is correct

You cant empty the category trash until any article that is assigned to the
category is completely removed. Otherwise you would not be able to restore
the article.

On 23 April 2015 at 11:32, ssnobben <notifications@github.com> wrote:

> Steps to reproduce the issue
>
>    1. Create a new category
>    2. Create a new menu "List all categories" and choose that new
>    category.
>    3. Create an new article to that new category Check all work and then
>    delete the new article, the new menu and then the new category.
>
> You get an error that you cant empty trash for deleting the category.
> Error
> Delete not allowed for category Test category.1 item is assigned to this
> category.
> Expected result
>
> Should be able to empty trash for that trashed category.
> Actual result System information (as much as possible) Additional comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6824>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ssnobben** [comment]
yes thats strange I empty the article trash and the menu trash but could not empty the category trash for some reason..

**Comment by brianteeman** [comment]
NOTE any trashed article that is in a category that is trashed will not
appear in the list of articles that can be trashed.

You must empty the article trash BEFORE you try and delete the category

On 23 April 2015 at 11:40, ssnobben <notifications@github.com> wrote:

> yes thats strange I empty the article trash and the menu trash but could
> not empty the category trash for some reason..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6824#issuecomment-95530571>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
If you do it in the wrong order then the article will still be there but
you cant see it. If you check the DB you will find it there. Quick fix is
to change the article state from -2 to 1 in the DB - then it is published
again and you can do things in the correct order

Hope that helps

On 23 April 2015 at 11:44, Brian Teeman <brian@teeman.net> wrote:

> NOTE any trashed article that is in a category that is trashed will not
> appear in the list of articles that can be trashed.
>
> You must empty the article trash BEFORE you try and delete the category
>
> On 23 April 2015 at 11:40, ssnobben <notifications@github.com> wrote:
>
>> yes thats strange I empty the article trash and the menu trash but could
>> not empty the category trash for some reason..
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joomla/joomla-cms/issues/6824#issuecomment-95530571>.
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ssnobben** [comment]
So Brian you test the work flow I present and it work for you?

**Comment by ssnobben** [comment]
FYI - I dont have that article in my DB.

**Comment by brianteeman** [comment]
In your workflow in the first post you dont say when you empty the trash

FYI - I dont have that article in my DB.

—
Reply to this email directly or view it on GitHub
<https://github.com/joomla/joomla-cms/issues/6824#issuecomment-95539352>.

**Comment by ssnobben** [comment]
I have find what is left in the db menu table now. Its the "main-menu-en" that point and have jumped to the only article in the system index.php?option=com_content&view=article&id=1 with published 1 flag.

So for some reason that seems cause of the problem and I dont know how this could happen..ok I will delete that db record and the problem should be solved.
