### ISSUE TITLE
article-version management - edit problem

### ISSUE THREAD

**Issue by hgh-esn** [joomla/joomla-cms#6828]
#### Steps to reproduce the issue

Go to the article-manager and open an article in edit-mode. 
Open the version-list and select a older version of the article. 
Restore it via "restore"-button.

You now come back to the edit-window and you can see the restored article-version in edit-mode.

Decide now to "cancel" editing the article. (This may happen, if the user decides so or by timeout ?).

#### Expected result

When the edit-process is canceled, all changes to the database must be rolled back or the save to the database must be canceled too.

#### Actual result

The article remains changed as done by the version-restore, even though the user has canceled the edit process

**Comment by brianteeman** [comment]
I think the only realistic option here would be to add a note when you restore a version that it will replace exisiting content which unless it has already been saved would be permanently lost. However in the scenario you describe it isn't lost and will be in the versions list to be restored.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6828">issues.joomla.org/joomla-cms/6828</a>.</sub>

**Comment by hgh-esn** [comment]
I think here is a generally problem with version-management.

When restoring an older version, it must only be temporarily loaded into the editor without directly saving it to the database.

When canceling the editor, nothing is saved and also nothing is written to the database - that's than ok.
When saving the article via the editot, the database is updated and all is ok too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6828">issues.joomla.org/joomla-cms/6828</a>.</sub>

**Comment by brianteeman** [comment]
I understand what you are saying but unfortunately the way that versions is implemented the action of restoring the version changes the database.

In the circumstance you described the user can just revert again to the previous version.

Closing at this time - with J4 the whole workflow will be changed anyway for this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6828">issues.joomla.org/joomla-cms/6828</a>.</sub>
