### ISSUE TITLE
Not possible to change menu settings for blog layout (all categories)

### ISSUE THREAD

**Issue by radik10** [joomla/joomla-cms#6834]
#### Steps to reproduce the issue
Not possible to change "pagination" and "pagination results" in menu blog layout - see image
Create main category, create subcategories and link main category to menu item. 
/administrator/index.php?option=com_menus&view=item&layout=edit&id=xy (display all categories menu type)
Image:
![J3.4.1. menu item bug for blog layout](http://joomla.r-art.sk/administrator-index.php--option=com_menus-and-view=item-and-layout=edit-and-id=xy%20-%20Administration%20-%20Menu%20Manager-%20Edit%20Menu%20Item.jpg "menu item bug for blog layout in settings")

#### Expected result
To have possibility to change settings for "pagination" and "pagination results" in menu blog layout

#### Actual result
Now is only 1 option available "Use global" but if you need to change it, you have problem

#### System information (as much as possible)
J 3.4.1., PHP 5.4.4, MySQL 5.5.25a

**Comment by brianteeman** [comment]
I can not confirm this.
The home page of my blog http://brian.teeman.net is setup exactly as you describe BUT as you can see I have set pagination and pagination results to hide on that menu item

![screen shot 2015-04-24 at 17 54 44](http://issues.joomla.org/uploads/1/db31767ca4fc9adf8f07ceb1a9763608.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6834">issues.joomla.org/joomla-cms/6834</a>.</sub>

**Comment by radik10** [comment]
Hi,thanks for reply.
I did not realize (in time of writing mycomment) that those two buttons (from my image) has something to do with cacheproblem - because other buttons has been possible to change (settings forblog). 
Interesting was, that this problem was in firefox and chrome browsers.But after deleting browser and joomla caches, that problem disappeared.So it was somehow my local problem. Sorry for my complain, best regards,Radovan 


     On Saturday, April 25, 2015 12:55 AM, Brian Teeman <notifications@github.com> wrote:
   

 I can not confirm this.
The home page of my blog http://brian.teeman.net is setup exactly as you describe BUT as you can see I have set pagination and pagination results to hide on that menu itemThis comment was created with the J!Tracker Application at issues.joomla.org/joomla-cms/6834.—
