### ISSUE TITLE
Joomla 3.3.6 Forgot my password link not working on secure site

### ISSUE THREAD

**Issue by Witchypaws** [joomla/joomla-cms#6836]
#### Steps to reproduce the issue

Attempt to login to frontend of joomla website through login module or menu link
Realise you forgot your password
Click the forgot your password link on the login form
Enter your email address
Receive the email with the link to retrieve or reset password
Click the link or paste the link, neither is working

#### Expected result

Be able to reset password and login

#### Actual result

Get following error message

Your password reset confirmation failed because the verification code was invalid. User not found

#### System information (as much as possible)
Joomla 3.3.6
Force secure site turned on so all pages are https://
SSL certificate on hosting working
User registration disabled
No link to view and update user profile provided as we don't really want them doing this
Twenty different ACL categories and user groups enabled

#### Additional comments
Resetting your password should be able to work no matter the configuration unless you have a function to turn it off

**Comment by mbabker** [comment]
Can you test this on the current release (3.4.1)?

**Comment by brianteeman** [comment]
I just tested this on my 3.4.1 web site using https with no problems. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6836">issues.joomla.org/joomla-cms/6836</a>.</sub>

**Comment by Witchypaws** [comment]
I will install it this week and retest

 

Please do not hesitate to call or email me if you have any further queries

 

Warm regards

 

Jacqui Blanch

Digital Design and Development

 <mailto:webmaster@jacquiblanch.com> webmaster@jacquiblanch.com

+61 7 5465 6190

**Comment by Witchypaws** [comment]
I will install it this week and retest

 

Please do not hesitate to call or email me if you have any further queries

 

Warm regards

 

Jacqui Blanch

Digital Design and Development

 <mailto:webmaster@jacquiblanch.com> webmaster@jacquiblanch.com

+61 7 5465 6190

**Comment by pe7er** [comment]
@Witchypaws 
Did you get a chance to test it with the current version?
Thanks!

**Comment by Witchypaws** [comment]
Sorry Peter

 

Had a death in the family last week, did not get there, will be getting there this week

 

Please do not hesitate to call or email me if you have any further queries

 

Warm regards

 

Jacqui Blanch

Digital Design and Development

 <mailto:webmaster@jacquiblanch.com> webmaster@jacquiblanch.com

+61 7 5465 6190

**Comment by brianteeman** [comment]
It has been more than one month since the last update on this. As no one else has been able to confirm the issue I am closing this at this time. If further information is provided (especially confirmation that you ave tested n 3.4.1) then it can always be re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6836">issues.joomla.org/joomla-cms/6836</a>.</sub>
