### ISSUE TITLE
3.4.1 update

### ISSUE THREAD

**Issue by alijen** [joomla/joomla-cms#6837]
#### Steps to reproduce the issue
see ref to links with more than one ocurrance with auto update to 3.4.1

#### Expected result
administrator access to back end

#### Actual result
white screen in admin access back end

#### System information (as much as possible)
3.4.1 update with admin 

#### Additional comments
ref http://issues.joomla.org/tracker/joomla-cms/6191

**Comment by brianteeman** [comment]
a white screen is an error message in disguise.

On 24 April 2015 at 18:19, alijen <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> see ref to links with more than one ocurrance with auto update to 3.4.1
> Expected result
>
> administrator access to back end
> Actual result
>
> white screen in admin access back end
> System information (as much as possible)
>
> 3.4.1 update with admin
> Additional comments
>
> ref http://issues.joomla.org/tracker/joomla-cms/6191
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6837>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
The referenced issue is coming from the FOF library we use. It has been fixed upstream and just needs to be passed down.
However as Brian said a white page doesn't mean it's the same error. Please check the Apache error log and post the exact error message that is logged.

Closing as the information given so far is of no value as it lacks the important details.

**Comment by alijen** [comment]
PHP Fatal error:  Class FOFModelFieldNumber contains 2 abstract methods 
and must therefore be declared abstract or implement the remaining methods (FOFModelField::range, FOFModelField::modulo) in domain/libraries/fof/model/field/number.php on line 130<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6837">issues.joomla.org/joomla-cms/6837</a>.</sub>

**Comment by alijen** [comment]
Please advise, one person resolved by changing the script to abstact and this worked for them. What is the exact script to be used and does that go on the line where it occurs in this case line 130? If you feel this item has been fixed and can be passed down, please supply instruction with how to update with a white screen admin panel. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6837">issues.joomla.org/joomla-cms/6837</a>.</sub>

**Comment by alijen** [comment]
Ive posted the exact error I am receiving and it appears to be solved with an update. I do not know how to make the update when I can't access the back end. Please advise. Thank you. Somehow managed to migrate and keep current with joomla without being a programmer, this one has me down on three sites, similar issue after the auto update to 3.4.1. 

----- Original Message -----

**Comment by alijen** [comment]
The fix I found that worked for this for three websites with the same error was to reinstall j3.4.1 (from my hostsite using mojo) then in cpanel renaming the new config file to disable it, then rename the backup config file the system generates to the operative file name configuration.php
