### ISSUE TITLE
missing alias prevents viewing by lower than super user

### ISSUE THREAD

**Issue by mandville** [joomla/joomla-cms#6838]
#### Steps to reproduce the issue
using extension with sql mapping eg rsform pro, 
create sql mapping without insert to alias
create content item using form, allowing item to be inserted to content via sql mapping, with content inserted into "description" , but not inserting content into alias.
view item in content articles noting that article has description but no alias.
 

#### Expected result
Viewing all items in content 

#### Actual result
viewing these items are not possible by lower than super user.
items need to be opened and alias rewritten to enable viewing by lower than super user.

#### System information (as much as possible)
PHP Built On 	Linux  2.6.32-504.3.3.el6.x86_64 #1 SMP Wed Dec 17 01:55:02 UTC 2014 x86_64
Database Version 	5.5.42-cll
Database Collation 	utf8_general_ci
PHP Version 	5.4.38
Web Server 	LiteSpeed
Joomla! Version 	Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; rv:37.0) Gecko/20100101 Firefox/37.0 

#### Additional comments
used latest version of rsform pro. may also happen on other cck that insert content. 
using rsform pro or similar to create an alias is the desired action but to only allow a super user to view non aliased items is still "weird"

**Comment by brianteeman** [comment]
I would suggest that you (rsform) are doing it wrong and that you should
always be creating content with an alias.

On 24 April 2015 at 22:27, mandville <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> using extension with sql mapping eg rsform pro,
> create sql mapping without insert to alias
> create content item using form, allowing item to be inserted to content
> via sql mapping, with content inserted into "description" , but not
> inserting content into alias.
> view item in content articles noting that article has description but no
> alias.
> Expected result
>
> Viewing all items in content
> Actual result
>
> viewing these items are not possible by lower than super user.
> items need to be opened and alias rewritten to enable viewing by lower
> than super user.
> System information (as much as possible)
>
> PHP Built On Linux 2.6.32-504.3.3.el6.x86_64 #1
> <https://github.com/joomla/joomla-cms/pull/1> SMP Wed Dec 17 01:55:02 UTC
> 2014 x86_64
> Database Version 5.5.42-cll
> Database Collation utf8_general_ci
> PHP Version 5.4.38
> Web Server LiteSpeed
> Joomla! Version Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
> Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ]
> 24-Apr-2013 00:00 GMT
> User Agent Mozilla/5.0 (Windows NT 6.1; rv:37.0) Gecko/20100101
> Firefox/37.0
> Additional comments
>
> used latest version of rsform pro. may also happen on other cck that
> insert content.
> using rsform pro or similar to create an alias is the desired action but
> to only allow a super user to view non aliased items is still "weird"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6838>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by bertmert** [comment]
...AND...
if an article is saved without an alias, absolutely no problem. Group Public can see it in frontend and group Manger can see it in backend.

I think it's field access that is 0 in your case.

**Comment by mandville** [comment]
![screen shot 2015-04-27 at 16 47 30](http://issues.joomla.org/uploads/1/3da7cade8a50f6b3175d4334461a0fba.jpg)agreed the article should not be able to be saved without an alias BUT, 
The category the item is saved to is registered users and above (not public).
the enclosed image shows the issue. 
The image shows a super user view.

there are 2 items with alias. the top and bottom item is viewable front end as in a public view category
the second item is a registered user category with no alias and not back end viewable by anyone below SU
adding an alias makes it viewable to all registered users. 

To fully replicate the issue add an item via a cck or direct into the sql without setting an alias as prev mentioned, entry via normal methods will auto create an "alias". 

temporary fix - SU opens the item then closes them to get J to auto create the alias. 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6838">issues.joomla.org/joomla-cms/6838</a>.</sub>

**Comment by brianteeman** [comment]
The problem is not with Joomla but with the way you are using rsform
sqlmapping and NOT completing all the fields.
This is not a core joomla issue

On 27 April 2015 at 22:47, mandville <notifications@github.com> wrote:

> [image: screen shot 2015-04-27 at 16 47 30]
> <https://camo.githubusercontent.com/de2605557704332610c382b2bc98d2ea2720ffc4/687474703a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f33646137636164653861353066366233313735643433333434363161306662612e6a7067>agreed
> the article should not be able to be saved without an alias BUT,
> The category the item is saved to is registered users and above (not
> public).
> the enclosed image shows the issue.
> The image shows a super user view.
>
> there are 2 items with alias. the top and bottom item is viewable front
> end as in a public view category
> the second item is a registered user category with no alias and not back
> end viewable by anyone below SU
> adding an alias makes it viewable to all registered users.
>
> To fully replicate the issue add an item via a cck or direct into the sql
> without setting an alias as prev mentioned, entry via normal methods will
> auto create an "alias".
>
> temporary fix - SU opens the item then closes them to get J to auto create
> the alias.
>
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/6838
> <http://issues.joomla.org/tracker/joomla-cms/6838>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6838#issuecomment-96830606>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by OctavianC** [comment]
Here to save the day: RSForm! Pro only performs the SQL query you've set up, it can't magically create the `alias` if you don't tell it to. Same goes for Joomla! - it has no control over who alters the tables manually, nor should it do anything in this regard.

**Comment by brianteeman** [comment]
Which is what I have been saying
