### ISSUE TITLE
Script (install) file should be run for libraries as well as all other packages

### ISSUE THREAD

**Issue by Kixo** [joomla/joomla-cms#6841]
#### Steps to reproduce the issue
Install library and try to use script file for preflight or any other methods.

#### Expected result
You should be able to run preflight and other methods when installing libraries

#### Actual result
Library is installed without running script file 

#### System information (as much as possible)
Any joomla version, any php, any system.

#### Additional comments
I checked and there is really not any reason why script (install) file should not be used when installing libraries. This is very important feature if you want to check / upgrade or do any action before or after the installation of the library.

**Comment by vdespa** [comment]
Hi Kixo,

Thanks for your report. I had tried to use the install script methods in one of my libraries. I could not find any issues. 

1. Make sure you define the script file in the library manifest file.

`<scriptfile>script.php</scriptfile>`

2. Make sure you name the class of the script like:

class yourlibrarynameInstallerScript {}

I am marking this for the moment as "Unconfirmed". If you still have issues, just reply with more details and this can be reopened anytime.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6841">issues.joomla.org/joomla-cms/6841</a>.</sub>

**Comment by vdespa** [comment]
Set to "closed" on behalf of @vdespa by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6841">issues.joomla.org/joomla-cms/6841</a>

**Comment by Kixo** [comment]
I tried again and it is working on install / update / preflight...
but when I try to do a preflight on the uninstall type it fails. I want to do some check before uninstall of the library (check some dependencies) and if something is wrong, I want to restrict the uninstall of that library. It seems that on library uninstall it does not trigger preflight method at all.

**Comment by mbabker** [comment]
There's still some underlying work needed in the extension adapters to get them 100% standardized.  The uninstall paths are part of that needed work.

**Comment by Kixo** [comment]
thanks @mbabker for quick response... I was just digging up this a bit and I see it is really not standardized... So preflight on uninstall method will not trigger as I see from the code.
