### ISSUE TITLE
Smart Search problem with index using shell

### ISSUE THREAD

**Issue by Sarge2013** [joomla/joomla-cms#6842]
Hello,
I found the following issue - Smart Search index works well using web backend admin interface.
But when I try to use shell 
php -q /var/www/html/alt/cli/finder_indexer.php
I have the following notices
Smart Search INDEXER
============================
Starting Indexer
Setting up Smart Search plugins
Setup 20 items in 0.12 seconds.
PHP Notice:  Undefined property: stdClass::$page_title in /var/www/html/alt/administrator/components/com_finder/helpers/indexer/adapter.php on line 793

Notice: Undefined property: stdClass::$page_title in /var/www/html/alt/administrator/components/com_finder/helpers/indexer/adapter.php on line 793
PHP Notice:  Undefined property: stdClass::$page_title in /var/www/html/alt/administrator/components/com_finder/helpers/indexer/adapter.php on line 793

Notice: Undefined property: stdClass::$page_title in /var/www/html/alt/administrator/components/com_finder/helpers/indexer/adapter.php on line 793

 * Processed batch 1 in 0.052 seconds.
Total Processing Time: 0.172 seconds.

How to fix it ?
Thanks in advance !

**Comment by chrisdavenport** [comment]
It's most likely a finder plugin that is the root cause of this issue.  Which plugins in the finder group do you have enabled?  Try re-indexing with only one plugin enabled at a time.  That should enable you to determine which plugin is causing the issue.

**Comment by Sarge2013** [comment]
Thank you fo the comment.
I have few articles written in Czech, English, Russian languages for Smart Search test.

Unfortunately...it's Smart Search - Content plugin (the most necessary one)
If I disable the one - I have normal shell issues like
php -d memory_limit=256M /var/www/html/alt/cli/finder_indexer.php
Smart Search INDEXER
============================
Starting Indexer
Setting up Smart Search plugins
Setup 6 items in 0.319 seconds.
 * Processed batch 1 in 3.694 seconds.
Total Processing Time: 4.013 seconds

When Smart Search - Content plugin enabled - again same notices
PHP Notice: Undefined property: stdClass::$page_title in /var/www/html/alt/administrator/components/com_finder/helpers/indexer/adapter.php on line 793
as above.

**Comment by chrisdavenport** [comment]
I was wrong, the problem was in the adapter and not the plugin.  PR should fix it.

**Comment by Sarge2013** [comment]
Thank you ! But what means "PR should fix it" ?
Is a fix will be published here - or included to a next release Joomla 3.4.2 ?

**Comment by chrisdavenport** [comment]
"PR" means "pull request" which is the means by which code changes are made.  I submitted a PR which will fix the issue that you have found.  You can see the PR here: #6847 

The procedure is that the PR requires at least 2 independent testers to confirm that the PR fixes the issue.  The PR is then moved to RTC ("ready to commit") status and it should then be included in the next Joomla release, which will most likely be 3.4.2.

So please test the PR and report what you find.  Only one more tester will then be needed.

In the meantime you can safely ignore the PHP notice as the bug does not affect the functioning of Smart Search at all.

Thanks for reporting the issue.

**Comment by brianteeman** [comment]
See #6847 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6842">issues.joomla.org/joomla-cms/6842</a>.</sub>
