### ISSUE TITLE
LessPHP outdated

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#6845]
Our current LessPHP version is 0.3.9, the current one is 0.5.0: https://github.com/leafo/lessphp

Even if there is a B/C break in that library there, we should really update this and see if we can somehow catch the change in our extending J class.

**Comment by Bakual** [comment]
To my knowledge, the newer releases are not compatible with Bootstrap 2.3.2. Which is why we never updated it.
I don't know what exactly isn't compatible.

**Comment by mbabker** [comment]
http://leafo.net/lessphp/changelog.html somewhat explains why we're stuck on the version we have.  If you can find the breaking change (https://github.com/leafo/lessphp/compare/v0.3.9...v0.4.0) maybe we can catch it in JLess.

**Comment by bertmert** [comment]
I'm using lessc 0.4.0 with Joomla 3 (/media/jui/less/) for a long time now and never had any problems.
Today I made some tests with template.less from Isis and Protostar (lessc 0.3.9, 0.4.0, 0.5.0) and got  exactly the same outputfiles template.css.
(I don't know if your discussion is going deeper than that. I never used JLess but the same default vars from class JLessFormatterJoomla for compilation )

**Comment by PLFoxNET** [comment]
Welcome,

I have a question, is there a way to file "libraries / fof / less / less.php" at the template level override? In Joomla 3.4 is still version 0.3.9, and I would like in one template to use newer versions 0.5.0

Is this feasible?

**Comment by Bakual** [comment]
You can't override it. But of course you can ship your own copy and use it in your template. Just `require_once` your copy and use it.

**Comment by brianteeman** [comment]
Setting to needs review so the CMS maintainers can make a decision on upgrading this or not.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6845">issues.joomla.org/joomla-cms/6845</a>.</sub>

**Comment by Bakual** [comment]
This can be closed since we have a PR for that: https://github.com/joomla/joomla-cms/pull/7687
