### ISSUE TITLE
Menu item type and article details improvement 

### ISSUE THREAD

**Issue by adi8i** [joomla/joomla-cms#6848]
Would be nice if you could improve menu item type layouts and article details. To customize this things overrides will be required, some functionality may be added here. If you want to add an intro image, the article will not look too good in category blog layout and so on. 
About article details, some options to display them as list or inline, etc.

So for future releases maybe you would like to add more configuration options for article display. :)

**Comment by Fedik** [comment]
>... maybe you would like to add more configuration options for article display

do not say that :smile: 
there already 10000 different options :smile:

**Comment by brianteeman** [comment]
This can all be achieved right now with template overrides.

On 26 April 2015 at 09:25, Fedir Zinchuk <notifications@github.com> wrote:

> ... maybe you would like to add more configuration options for article
> display
>
> do not say that [image: :smile:]
> there already 10000 different options [image: :smile:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6848#issuecomment-96343072>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
