### ISSUE TITLE
Protostar menu not responsive

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#6850]
#### Steps to reproduce the issue
View with mobile device or shrink the browser

#### Expected result
Menu should collapse 

#### Actual result
Menu does not collapse

#### Additional comments
https://github.com/joomla/joomla-cms/pull/6849 attempts to rectify this by collapsing the menu for mobile devices

**Comment by Webdongle** [comment]
Why close it ?

**Comment by brianteeman** [comment]
Because you have a Pull Request #6849 We only need one item on the tracker

On 28 April 2015 at 00:30, Webdongle <notifications@github.com> wrote:

> Why close it ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6850#issuecomment-96850302>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Webdongle** [comment]
Ah sorry ... I created the pull request after not realising it would auto create in issues.joomla.  Thanks
