### ISSUE TITLE
Receiving an error after attempting to click "Add install from the web tab"

### ISSUE THREAD

**Issue by NerdyKeith** [joomla/joomla-cms#6851]
I am currently creating my site through my localhost; I have yet to transfer it to a server. 

It seems that I can't actually install any templates, extensions or even images. I keep getting an error telling me that Joomla is unable to move the file. This is when I upload image from my computer. 

So I've had to insert images through my folder structure in Finder (on my mac). 

At the moment I am now trying to click the "Add install from the web tab" through the extensions and that is giving me an error too. 

When I click on it; I see this error

![joomla error](https://farm9.staticflickr.com/8743/17073787887_98b6e8f7c2_c.jpg "Joomla Error")

So I got this error by taking these steps

1. Went to localhost/mysitename/administrator
2. Click the Extensions tab, and selected "Extension Manager"
3. Clicked "Add 'Instal from web' Tab"

Any ideas on how to fix this issue? 

Thanks in advance

**Comment by brianteeman** [comment]
This is probably a problem with the file permissions on your local server. Please us the forum for support http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6851">issues.joomla.org/joomla-cms/6851</a>.</sub>
