### ISSUE TITLE
isis can't save all assigned page more then 1000 pages 

### ISSUE THREAD

**Issue by adilhoussam** [joomla/joomla-cms#6853]
#### Steps to reproduce the issue
Hello

I have multilanguage website with more than 2000 item menu

whene i save module i have a bug ( can save module assigned in (all page) ) but if i save with 1 page or page work fine 

#### Additional comments
bug juste in isis ( hathor  work fine )
--
sorry for my english is not good :)
if it is not clear I write in French?

**Comment by brianteeman** [comment]
This is a server problem and not a Joomla problem. The ONLY fix for this is
to get your host to change the php value for max_input_vars from the
default value of 1000 to something higher.
