### ISSUE TITLE
Upgrade 2.5 -> 3.4.1 =  "Browser is not defined" (JS)

### ISSUE THREAD

**Issue by HornFl4kes** [joomla/joomla-cms#6857]
## The issue
When I save the global configuration of a fresh new website migrated from joomla 2.5 to joomla 3.4.1 (by using the joomla updater component or the joomla 3.4.1 package). I get this error :
> Uncaught ReferenceError: Browser is not defined

Maybe is mootools declaration missing on this page ? 

## Step to reproduce the issue
1. Upgrade from Joomla Updater or with the migration package a joomla 2.5 website
2. Go to **Global configuration** page
3. Try to **save** your modifications on this page

**Comment by maskitto** [comment]
I have tested this on a fresh install of Joomla! 2.5.28 using the Joomla! Update Component and following the steps on https://docs.joomla.org/Joomla_2.5_to_3.x_Step_by_Step_Migration.
I was able to reproduce the issue after upgrading to 3.4.1 - saving global configuration worked but the error showed in the "Developer Tools" in Firefox (see screenshot).
Investigating it further I came across a report on the forums (http://forum.joomla.org/viewtopic.php?f=706&t=808842) where people seem to be seeing the same issue with other components and also in front-end.
The comments on forum post hint on it being somehow related to caching and I noticed that clearing joomla cache did not solve the issue. Only when I cleared the browser cache the error message went away, not showing again while testing. I cannot assure it will not come back at some point.
Not being a JS and mootools expert myself, I'll leave it to more experienced testers to try to find the source of the issue.
![screenshot - 04282015 - 10 58 55 pm](https://cloud.githubusercontent.com/assets/1383584/7383947/d32d4384-edfe-11e4-8f29-73feca124406.png)

**Comment by OctavianC** [comment]
I just reproduced the issue as well - although the fix is fairly easy. You just have to clear your browser's cache. In this particular case (Global Configuration not saving) the browser uses the old, cached version of `/media/system/js/validate.js`. Once you reload the page & clear the cache (usually `CTRL+F5` in Windows browsers) everything works fine. Perhaps the docs should point this out?

**Comment by zero-24** [comment]
Moving to `Information Required` until we have a respond by @HornFl4kes or @maskitto on the point by @OctavianC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6857">issues.joomla.org/joomla-cms/6857</a>.</sub>

**Comment by HornFl4kes** [comment]
Cleaning my browser cache, fix the problem. Thank you all :)
Should I close the issue ?

**Comment by zero-24** [comment]
Closing as requested that for the update @HornFl4kes

**Comment by HornFl4kes** [comment]
Why don't we add a get parameter (with the joomla version) when we include the js file to be sure not to use the cached version ? 

If it's a good fix, I can do so.
What do you think about this guys ?

**Comment by mbabker** [comment]
There are already a couple of ways in the core API to append a version to a media file, let's not add another.  Especially one that uses the application version.

**Comment by HornFl4kes** [comment]
Oh ok. I was not aware of this sorry.
Do we agree users shouldn't have to clean their cache when a website is migrated ?
