### ISSUE TITLE
Pull center image in article editor

### ISSUE THREAD

**Issue by adi8i** [joomla/joomla-cms#6862]
When you add an image in from article editor, and chose float center, the classs pull center will be added but will still be aligned left. 
![capture](https://cloud.githubusercontent.com/assets/9744973/7385101/e6880b82-ee47-11e4-9168-da82206c6e37.PNG)

Test it here: http://joomla-adi8i.c9.io/index.php/6-test-article-number-6

Or may be something wrong with my configuration, anyway if anyone could test would be great :)

**Comment by infograf768** [comment]
The tip explains you need a specific class.
![screen shot 2015-04-29 at 07 57 06](https://cloud.githubusercontent.com/assets/869724/7385422/01e4c1e2-ee46-11e4-959b-46df2109183b.png)

html code is, for example:
`<figure class="pull-center"><img title="a title" src="images/joomla_black.gif" alt="" /><figcaption>Center chosen in Image float</figcaption></figure>`

In Protostar, the css are:
```
figure {
	display: table;
}
figure.pull-center,
img.pull-center {
	margin-left: auto;
	margin-right: auto;
}
figcaption {
	display: table-caption;
	caption-side: bottom;
}
```

**Comment by Bakual** [comment]
In short: the template needs to support it, otherwise it will not work. Not a core issue.

**Comment by adi8i** [comment]
Ooook thanks for your answer :)
