### ISSUE TITLE
Routing issue with the archive view

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#6872]
#### Steps to reproduce the issue

- archive some articles
- enable and publish the archive modul
- at the frontend you will get something like this

![screen shot 2015-04-11 at 14 52 52](http://issues.joomla.org/uploads/1/178c85d26dff19904627aee9a6450e0d.png)
- The links look like:
`http://example.org/yyy/2009?view=archive&month=4` <- don't work. As it only use the month filter

Working would links like:
`http://example.org/yyy/index.php?view=archive&month=4&year=2009`

#### Expected result

Working links that produces a link that show something like:
`http://example.org/yyy/index.php?view=archive&month=4&year=2009`

#### Actual result

A Broken link that ignor the Year setting:
`http://example.org/yyy/2009?view=archive&month=4`

#### System information (as much as possible)

This is a know issue and e.g. described here: https://github.com/joomla/joomla-cms/pull/5810#issuecomment-70556347

**Comment by infograf768** [comment]
I can't reproduce the issue here as you can see on this screenshot (SEF off)

![screen shot 2015-05-01 at 09 01 35](https://cloud.githubusercontent.com/assets/869724/7427667/e80f4d72-efe0-11e4-8a6f-0fbcbf527766.png)

(SEF on )
![screen shot 2015-05-01 at 09 06 00](https://cloud.githubusercontent.com/assets/869724/7427686/583aface-efe1-11e4-9ec2-d43a9960870d.png)

**Comment by zero-24** [comment]
@infograf768 if you have SEF off please make sure that the Year and Month filter is set in the view. :smile: 

For me it is not see:
![year_filter_archive](https://cloud.githubusercontent.com/assets/2596554/7428145/f06b1e10-efea-11e4-9535-ea6366dc1095.PNG)

It allways only apply the month filter ;)

**Comment by infograf768** [comment]
in your example above, the year is not stated, only the month. As both articles were published in October, they both show.

1. To display the articles dates below the article title, I modified an archives menu item parameters to do such (but, if I do not have such a menu item, default would be global)
2. Not using that menu item, I click on an archived article in the module url obtained is:
`http://localhost:8888/trunkgitnew/index.php?option=com_content&view=archive&year=2015&month=3&Itemid=256`
=> the result displays with the filter set to the article month and year, i.e here March 2015
![screen shot 2015-05-01 at 11 32 43](https://cloud.githubusercontent.com/assets/869724/7428730/d3bc70b0-eff5-11e4-9cb5-a2055d7db24e.png)
3. I then change the month in the filter to `Month` and switch the year to 2014 in my example. I click on the filter Button. I get this url:
`http://localhost:8888/trunkgitnew/index.php?option=com_content&view=archive&Itemid=256`
the correct article is displayed:
![screen shot 2015-05-01 at 11 38 01](https://cloud.githubusercontent.com/assets/869724/7428760/8f8e7a36-eff6-11e4-8fb0-debadd2869ce.png)

4. If I change the filter to `Month` and `Year` then click on the Filter button, I get the same url and it displays correctly both articles as both Month and Year are not specified:

![screen shot 2015-05-01 at 11 41 01](https://cloud.githubusercontent.com/assets/869724/7428784/fb8e077e-eff6-11e4-84dc-642cfa319382.png)

The date used for filtering is the 'Published Date`.

No bug here. Works fine.

**Comment by zero-24** [comment]
>No bug here. Works fine.

Yes the filter generally work. But the SEF URLs that was created by the archive module are wrong. If i disable SEF all works ok :smile:

**Comment by infograf768** [comment]
All works OK when sef is on or off, but, when sef on, after Clicking on the Filter Button, if we have no menu item to Archives Articles, we may get an url of the type: http://localhost:8888/trunkgitnew/component/content/
No effect on display though.

**Comment by wojsmol** [comment]
Confirm problem described by @zero-24 that the year filter is not set after clicking on a link generated by the archive module.
