### ISSUE TITLE
mod_language adds language code

### ISSUE THREAD

**Issue by iamrobert** [joomla/joomla-cms#6874]
If the default site language "remove url language code" is checked - the mod_language language switcher still adds the language code.

I have applied this to J3.4:
https://github.com/joomla/joomla-cms/commit/22865214e51b7f77f999f10a34a141488b1073d7#commitcomment-10992787

The above correctly removes /tw/ from rel="alternate":
```
  <link href="http://localhost/htw3/index.php/about/doctors" rel="alternate" hreflang="zh-TW" />
```

However the language switcher - still adds /tw/:

```
<div class="mod-languages">
<ul class="lang-inline">
  <li class="" dir="ltr"> <a href="/htw3/index.php/tw/about/doctors"> 中文 </a> </li>
  <li class="lang-active" dir="ltr"> <a href="/htw3/index.php/en/about/doctors"> English </a> </li>
</ul>
</div>

Any ideas?

**Comment by infograf768** [comment]
The behaviour IS correct. No bug here at all
For a site where en-GB is the default site and Remove URL Language Code is set to Yes, we will get as alternate:

```
 <link href="http://localhost:8888/testwindows/trunkgitnew/" rel="alternate" hreflang="en-GB" />
  <link href="http://localhost:8888/testwindows/trunkgitnew/de/" rel="alternate" hreflang="de-DE" />
  <link href="http://localhost:8888/testwindows/trunkgitnew/it/" rel="alternate" hreflang="it-IT" />
  <link href="http://localhost:8888/testwindows/trunkgitnew/es/" rel="alternate" hreflang="es-ES" />
  <link href="http://localhost:8888/testwindows/trunkgitnew/mk/" rel="alternate" hreflang="mk-MK" />
  <link href="http://localhost:8888/testwindows/trunkgitnew/ta/" rel="alternate" hreflang="ta-IN" />
```

and the switcher will have the /en/ because it is <b>After clicking on the switcher</b> that the url language code is removed.
Alternate will work as desired.

**Comment by iamrobert** [comment]
My reason for asking is won't the redirect affect SEO:

"The link to "http://localhost/htw3/index.php/tw/" has resulted in HTTP redirection to "http://localhost/htw3/index.php/".

Search engines can only pass page rankings and other relevant data through a single redirection hop. Using unnecessary redirects can have a negative impact on page ranking."

Redirects also slow down page load.

**Comment by infograf768** [comment]
We have one redirect only.

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6874">issues.joomla.org/joomla-cms/6874</a>

**Comment by infograf768** [comment]
Closing. Thanks for your concern.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6874">issues.joomla.org/joomla-cms/6874</a>.</sub>
