### ISSUE TITLE
Routing errors when "Remove URL Language Code" is set in "Language filter"

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#6876]
#### Steps to reproduce the issue
- Have a multilingual site for which the default language code (e.g. en-UK) is hidden and a secondary language (e.g.: it-IT)
- have two valid URLs, one for the primray, one for the secondary language (e.g.: `http://nuovaicona.org/exhibitions-and-events/other-venues/luna-d-acqua` and `http://nuovaicona.org/it/mostre-ed-eventi/altre-sedi/luna-d-acqua`) The two URLs are associated, but that doesn't matter much.
- Assuming you already are *"in the primary language"* visit the first URL
- Now switch language to the secondary one using the language switcher
- Paste the primary language URL in the address bar of your browser

#### Expected result
The page should be displayed

#### Actual result
You get a 404

#### System information (as much as possible)
PHP Built On: 	Windows NT SMZ 6.3 build 9200 (Windows 8.1 Business Edition) i586
Database Version: 	5.6.23
Database Collation: 	utf8_general_ci
PHP Version: 	5.4.39
Web Server: 	Apache
WebServer to PHP Interface: 	apache2handler
Joomla! Version: 	Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version: 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: 	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0 

#### Additional comments
This bug creates **huge issues** when you are set in a secondary language, get an URL for the primary language from another source (e.g.: Google Search) and click on it. Instead of being routed to the correct page you get a 404.

No problems if the "Remove URL Language Code" options is **not** set in "Language filter".

**Comment by smz** [comment]
Sorry, the correct System information for the live site are:

PHP Built On: 	Linux smz.webserversystems.com 3.14.25-grsec.3.el5 #1 SMP Wed Mar 4 21:32:41 GMT 2015 x86_64
Database Version: 	5.5.40-36.1-log
Database Collation: 	utf8_general_ci
PHP Version: 	5.4.36
Web Server: 	Apache
WebServer to PHP Interface: 	cgi-fcgi
Joomla! Version: 	Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version: 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: 	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6876">issues.joomla.org/joomla-cms/6876</a>.</sub>

**Comment by infograf768** [comment]
Do you experience the same issue on 3.3.6?

**Comment by infograf768** [comment]
I have replaced the languagefilter.php with the one from 3.3.6 and it solves the issue here using staging.
This means we still have a regression...

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/6881

**Comment by zero-24** [comment]
as the PR is RTC i'm closing here. Thanks!
