### ISSUE TITLE
remove cacert.pem from distribution 

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#6879]
Joomla is being sneaky and distributing a cacert.pem (eg: http://curl.haxx.se/ca/cacert.pem) 

Should we be distributing it, especially as old versions are being distributed over time?

Should there be checks when Joomla releases are prepared to ensure its kept up to date?

Should it be configurable and updateable through a plugin or configuration setting?

Discuss.

ref: https://www.alledia.com/blog/why-updates/

**Comment by PhilETaylor** [comment]
@nicksavov drats I was about to update the current distributed version but I see you beat me to it 20113ad5c35a3b9818d57b69cdb982e4122eabe8

**Comment by zero-24** [comment]
@PhilETaylor I'm going to add the Request for Comment label here. Let me know if i should remove it. Thanks

**Comment by PhilETaylor** [comment]
@zero-24 Yup thats fine, I wanted to open it up to see what others thought

**Comment by btoplak** [comment]
As I commented on the referenced thread too, sorry Phil, but I absolutely disagree that removing root ca certificate bundle is the best solution. This is against the whole PKI security concept, and we are breaking the working parts to avoid errors. For the sake of security that would be a big step backwards.

By suggesting downloading/consuming cacert.pem file from an external source (without any assurance you will actually get it from a valid original website), you are getting customers in a high-risk situations. Even more using the plain HTTP links. Hint: Man-In-The-Middle attacks!!

The whole purpose of a root ca certificate bundles being distributed with browsers, OSes, cURL, Joomla, "other security-aware software", is to provide users with a locally available trustworthy start-point for further trust-level validation. If you have to grab it from external source you're in an untrustworthy environment and MITM attack is possible.

Points that are correct here are: 
* Joomla uses old root ca cert bundle, and it will be outdated now and then. The same happens with browsers, but they don't tend to discard the right approach distributing root ca certs with browsers. Best approach would be:
** updating the bundle file regularly, it's available on github, all of us interested can track the changes and send pull requests when needed https://github.com/bagder/ca-bundle/
** enabling users to choose/upload custom root ca cert bundle for using with J! framework
* users should be educated to push host to upgrade their server packages, source of most problems start there<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6879">issues.joomla.org/joomla-cms/6879</a>.</sub>
