### ISSUE TITLE
Event onContentPrepare for Category and Tag

### ISSUE THREAD

**Issue by marenkov** [joomla/joomla-cms#6880]
I have problem as developer of content-plugin.
I want to do "prepare content" for all objects: articles, categories and tags.
With articles I don't have any problems, in function 
onContentPrepare($context, $item, $params, $page)
in $item I get whole object of article.
But for category and tag I get only description-text.
But I need all properties.

**Comment by Grigory90** [comment]
+1 It would be nice!

**Comment by alikon** [comment]
@marenkov  please can you submit a Pull Request as you are a developer

**Comment by roland-d** [comment]
Hi you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6880">issues.joomla.org/joomla-cms/6880</a>.</sub>
