### ISSUE TITLE
Redirect frontend editing of module to backend administrator

### ISSUE THREAD

**Issue by heiro** [joomla/joomla-cms#6890]
Hello

The new feature to edit modules from frontend without having to login to admin is a big step forward for Joomla. I have however a problem with it, because my site template isn't customized for it. I have also taught my customer how to edit modules like it was in J 3.3 where you was redirected to backend when clicking on the edit icon. Then the backend Isis template was used for the edit window.

I have tried redirecting the urls that opens for each module, when clicking on the edit icon, to the backend edit window for that module, but cannot make it work. I wonder if there is anything I can do in the code to

EITHER:

1. Use another template than my default site template for the frontend editing window for modules (Isis or Protostar).

OR

2. Direct the user to backend administrator with that module opened for editing, like it was in J 3.3.

**Comment by brianteeman** [comment]
What template are you using. There is NOTHING in the default templates that
is customised for this to work. So you have an issue with something in your
template not following default behaviours and preventing it from working

On 4 May 2015 at 09:27, Heidi <notifications@github.com> wrote:

> Hello
>
> The new feature to edit modules from frontend without having to login to
> admin is a big step forward for Joomla. I have however a problem with it,
> because my site template isn't customized for it. I have also taught my
> customer how to edit modules like it was in J 3.3 where you was redirected
> to backend when clicking on the edit icon. Then the backend Isis template
> was used for the edit window.
>
> I have tried redirecting the urls that open for each module, when clicking
> on the edit icon, to the backend edit window for that module, but cannot
> make it work. I wonder if there is anything I can do in the code to
>
> EITHER:
>
>    1. Use another template than my default site template for the frontend
>    editing window for modules (Isis or Protostar).
>
> OR
>
>    1. Direct the user to backend administrator with that module opened
>    for editing, like it was in J 3.3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/6890>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by heiro** [comment]
I am using Artisteer template. Yes, it's right that it is an issue with my template, but I wonder if there is a way around before that is fixed. The edit view in the frontend template will also be quite different than what my customer is used to using the Isis template.Is there a file in the background where I can cutomize how the edit window is organised?

**Comment by brianteeman** [comment]
components/com_config/view/modules/tmpl
Contains the views for the front end module editing which can be overriden in the normal way.

As this is not an issue with the core of Joomla but with your poorly written template I am closing this issue here. You should really raise this issue with Artisteer or perhaps ask for help in the joomla support forum http://forum.joomla.org
