### ISSUE TITLE
Module position cannot be typed in on Isis template

### ISSUE THREAD

**Issue by vancata** [joomla/joomla-cms#6892]
#### Steps to reproduce the issue
1. Create a new module
2. Try to type in a new position name (that does not exist)

#### Expected result
The new position should be saved

#### Actual result
Nothing happens when the user tries to type in the position name

#### System information (as much as possible)
Joomla 3.4.1, tried with Chrome (latest version), Firefox (latest version), IE 11

#### Additional comments
The problem occurs when the user has deleted all default templates and has only his template with positions count less than 10. In that case the chosen plugin does not render search field where normally we put new position that does not exit. Read the comments for additional information.

**Comment by dgt41** [comment]
Are you pressing enter at the end of the naming of the position?

**Comment by vancata** [comment]
There is no text comming in the field when I'm typing the position name. I did try to press enter though, but with no avail.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6892">issues.joomla.org/joomla-cms/6892</a>.</sub>

**Comment by brianteeman** [comment]
I can't replicate this.

**Comment by dgt41** [comment]
Can you clear your browser’s cache and re try?

**Comment by vancata** [comment]
Just tried to clear the cache, same result. I haven't accessed the joomla site with IE and the problem was the same there so it's not cache. Please note that I use Joomla 3.4.1. From the drop down Position I can select any predefined position but I'm unable to type anything inside (new position name)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6892">issues.joomla.org/joomla-cms/6892</a>.</sub>

**Comment by dgt41** [comment]
Do you have any errors logged in browser’s console? I can’t replicate here

**Comment by vancata** [comment]
No errors in the console.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6892">issues.joomla.org/joomla-cms/6892</a>.</sub>

**Comment by vancata** [comment]
I'm using a fresh installation of joomla 3.4.1 (not an update)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6892">issues.joomla.org/joomla-cms/6892</a>.</sub>

**Comment by JoshuaLewis** [comment]
@vancata I can't replicate this either. Perhaps this takes place with a certain module? When creating a new custom HTML module with a fake position called "cat" it saves it just fine. Also try a different browser to see if it is browser specific.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6892">issues.joomla.org/joomla-cms/6892</a>.</sub>

**Comment by vancata** [comment]
I tried 3 different browsers but if the others can't reproduce it, then probably the problem is only on my computer.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6892">issues.joomla.org/joomla-cms/6892</a>.</sub>

**Comment by JoshuaLewis** [comment]
As mentioned before, perhaps it's module specific. Have you tried this with creating a custom html module? Is your Joomla installed on a server or your own computer?

**Comment by vancata** [comment]
I'm testing with custom HTML module, I tried on another joomla 3.4.1 (not fresh install but updated) and there I can see the field for typing the new position name. Then I inspected the problematic element and I can see that the control that renders the dropdown (it's a "Chosen jQuery plugin) has a class chzn-container-single-nosearch, which actually makes the search field disappear and I can't type anything. Now, why it has this class I have no idea.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6892">issues.joomla.org/joomla-cms/6892</a>.</sub>

**Comment by sovainfo** [comment]
Check for customized chosen library by extensions, likely template frameworks!

**Comment by brianteeman** [comment]
Reset priority https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6892">issues.joomla.org/joomla-cms/6892</a>.</sub>

**Comment by vancata** [comment]
YES, I figured it out. Finally I decided to check the joomla code and I can see that in the JHtmlFormbehavior class where the chosen jQuery plugin is configured, there is a "disable_search_threshold" option set to **10** by default. If the items in a chosen drop down are less then 10 then there is no search functionality because you don't really need search functionality for less than 10 items. BUT the search functionality is used to type in new position name. So in my case I had only 4 positions defined in my template (header, footer, mainmenu and content). So when I click on the position field to type my custom position chosen plugin sees that I have only 4 items in the control so it doesn't show the search input field and I can't type anything. So in case there is less than 10 positions the user won't be able to create new positions in the modules.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6892">issues.joomla.org/joomla-cms/6892</a>.</sub>

**Comment by sovainfo** [comment]
Suggest priority Very Low or Low in that case!

**Comment by vancata** [comment]
Well only because the template doesn't have more than 10 positions, the users won't be able to use a major part of module functionality (creating custom positions by typing in). I think this is pretty nasty bug. An easy solution would be to remove the threshold in general.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6892">issues.joomla.org/joomla-cms/6892</a>.</sub>

**Comment by sovainfo** [comment]
Suggest you read the document Brian referred to. Definitely a bug in Joomla. The entering of a position has nothing to do with searching the list. They shouldn't be related. 

The priority reflects how important it is for the community to fix this issue. Unfortunately your circumstances seem rare. It is not about the number of positions in your template. It is about the number of positions in your templates. Beez contains 16, protostar 18, add to that the 4 of your template and assuming they are used another 4 (Custom positions).
This suggests you removed the standard templates. The easy workaround of adding 2 custom positions to your template should bring back the functionality.

Would be surprised to find another site with only 1 frontend template with less then 5 positions.

**Comment by vancata** [comment]
I rest my case. On my site I've cleared the default templates (I'm purist freak), so this is why I had the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6892">issues.joomla.org/joomla-cms/6892</a>.</sub>

**Comment by sovainfo** [comment]
It only takes another purist that agrees on the fact the functionality should not be mixed. 

Advice to have an copy of protostar (different name) installed.

**Comment by brianteeman** [comment]
I can confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6892">issues.joomla.org/joomla-cms/6892</a>.</sub>

**Comment by JoshuaLewis** [comment]
I'm a bit of a purist myself and try to have as few extensions/templates installed. However I always keep Protostar installed for testing reasons with extensions. It allows me to prove to developers that something doesn't work with the current J version of Bootstrap.

**Comment by bertmert** [comment]
Just a quick and easy fix. 
Create a template override .../templates/isis/html/com_modules/module/edit.php

Just 4 lines needed in it
```
<?php
defined('_JEXEC') or die;
JHtml::_('formbehavior.chosen', 'select', null, array( 'disable_search_threshold' => 1 ) );
require(JPATH_ADMINISTRATOR.'/components/com_modules/views/module/tmpl/edit.php');
```

**Comment by brianteeman** [comment]
I am closing this at this time. A solution for the specific use case of only having one template with almost no defined modules has been provided by bertmert.
The reality is that although this is a valid issue it is an extreme edge case. Especially as currently if you remove a core template it will come back with the next update<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6892">issues.joomla.org/joomla-cms/6892</a>.</sub>

**Comment by bertmert** [comment]
See PR: https://github.com/joomla/joomla-cms/pull/8433
