### ISSUE TITLE
Duplicate RESET_COMPLETE_LABEL during password reset

### ISSUE THREAD

**Issue by ChuckNorrison** [joomla/joomla-cms#6894]
Hey i got a duplicate of COM_USERS_RESET_COMPLETE_LABEL in password reset page. I fixed it in com_users/views/reset/templ/complete.php (position of $fieldset->label).

			<fieldset>
                <p><?php echo JText::_($fieldset->label); ?></p>Label
				<?php foreach ($this->form->getFieldset($fieldset->name) as $name => $field) : ?>
					<div class="control-group">
						<div class="control-label">
							<?php echo $field->label; ?>
						</div>
						<div class="controls">
							<?php echo $field->input; ?>
						</div>
					</div>
				<?php endforeach; ?>
			</fieldset>

**Comment by losedk** [comment]
This is already fixed in #6540

**Comment by zero-24** [comment]
Closing as this will be fixed with the next CMS update. Thanks @ChuckNorrison and @losedk :smile:
