### ISSUE TITLE
Bug: Column path in tbl j25_menu is rebuilt out of wrong menu

### ISSUE THREAD

**Issue by tme5092** [joomla/joomla-cms#6907]
#### Steps to reproduce the issue
Having at least 2 Menus, say menu and menu2 (that ist column `menutype` in tbl `j25_menu`).  
Attached you find the menu structure at my project with replaced names. - I have marked the entries with id 120 and 239.
In the Joomla administration, after editing entry 239 and then save, column `path` is updated wrongly con![screen shot 2015-05-08 at 04 32 48](http://issues.joomla.org/uploads/1/815cbae00747485f425ecf7276c6bb37.png)taining some values of entry 120 (which is not the same menu).

#### Expected result
I expected entry 239 updated without contents of entry 120.

#### Actual result
see in description

#### System information (as much as possible)
Joomla 3.3.6
In ancient times had Joomla 1.5, updated to 2.5 and in turn to 3.x.

#### Additional comments
I could resolve the problem in `libraries/joomla/table/nested.php` in the 2 methods:  
* getPath($pk = null, $diagnostic = false)
* rebuildPath($pk = null)

Both functions select somehow their upper entries - I added `AND p.menutype = n.menutype` to the select queries which resolved the issue for me.

**Comment by brianteeman** [comment]
I had something very similar happen to be recently with a site upgraded from 1.0 to 1.5 to 2.5 and then 3.4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6907">issues.joomla.org/joomla-cms/6907</a>.</sub>

**Comment by brianteeman** [comment]
After almost  a year with no other reports I am closing this at this time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6907">issues.joomla.org/joomla-cms/6907</a>.</sub>
