### ISSUE TITLE
Regression: The Read More editor xtd button is broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#6909]
Create an article, add some text and try to insert a Read More via the Read More button.
The code `<hr id="system-readmore" />` is not inserted.

**Comment by Harmageddon** [comment]
I can confirm this issue with the recent staging branch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6909">issues.joomla.org/joomla-cms/6909</a>.</sub>

**Comment by infograf768** [comment]
I close this as we have a working patch here:
https://github.com/joomla/joomla-cms/issues/6911
