### ISSUE TITLE
Improve error message on update extension manager

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#6920]
#### Issue
You get a error when you are updating a beta release "with option: Minimum Stability- stable": 
"Invalid extension update"

Should be a better error message like:
"Extension update can't be installed by stability"

#### How to test
Install Kunena 4.0 beta 2 (https://github.com/Kunena/Kunena-Forum/releases) and find updates.

**Comment by brianteeman** [comment]
Is that message unique for updates with a minimum stability?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6920">issues.joomla.org/joomla-cms/6920</a>.</sub>

**Comment by 810** [comment]
I think its a global error message. I see no error msg here https://github.com/joomla/joomla-cms/blob/1e3eb590cda5e8b06f6f4c5feae7fd2d0e45528c/libraries/joomla/updater/adapters/extension.php#L131

But the next question is also, why I can see the update. I set the option as stable.

**Comment by vdespa** [comment]
As far as I know (and be aware I might be wrong), the minimum stability feature refers to the process of discovering updates (the `findUpdates` method).

The error you refer to (with the language string COM_INSTALLER_INVALID_EXTENSION_UPDATE), is actually triggered in the `InstallerModelUpdate::install` function (which has the comment "Handles the actual update installation.").<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6920">issues.joomla.org/joomla-cms/6920</a>.</sub>

**Comment by brianteeman** [comment]
Rather than change the language string (which I dont think we can as it is generic) isnt it better to resolve
> But the next question is also, why I can see the update. I set the option as stable.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6920">issues.joomla.org/joomla-cms/6920</a>.</sub>

**Comment by brianteeman** [comment]
Hi you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6920">issues.joomla.org/joomla-cms/6920</a>.</sub>
