### ISSUE TITLE
Default template not changing.

### ISSUE THREAD

**Issue by rickjs** [joomla/joomla-cms#6921]
Hi,

This is a problem on an existing installation of Joomla 3.4.1. Switching the default template to another template anyways stays at Hathor, will not switch to Isis. 

Problem: For the variable $paths on entering $this->getView function in the legacy controller, legacy.php, loses characters in $paths variable.

Rick

**Comment by brianteeman** [comment]
For support on specific issues please use the support forum http://forum.joomla.org

**Comment by N6REJ** [comment]
@rickjs I've tested your issue and it works fine, so either you've got a buggered install or your doing something wrong, which is why @brianteeman closed the issue and referred you to the forum.

**Comment by rickjs** [comment]
Hi,

Problem was not with Joomla, it's Netbeans. When debugging, clicking on the variable value, the value shows missing characters, hovering over the variable shows the correct value. 

Also, the Template change problem, somehow the user's default template got changed to Hathor. 

Problem solved.
