### ISSUE TITLE
rel="alternate" not applied to current page

### ISSUE THREAD

**Issue by Simonkloostra** [joomla/joomla-cms#6923]
#### Steps to reproduce the issue
Any mulilingual site, observe the source code. The source code shows a URL with a rel="alternate" metatag for the corresponding page of the alternative language. So, if the page is bilingual (say, english and dutch) and the current URL is an English one (say: http://example.com/en/current-english-article), only a reference to the Dutch page is shown, like this:
**link href="http://example.com/nl/dutch-article" rel="alternate" hreflang="nl-NL"** 

#### Expected result
Google requires the actual page you are on to also have a metatag rel="alternate" pointing to itself with the current language, like this:
**link href="http://example.com/en/current-english-article" rel="alternate" hreflang="en-GB" 
link href="http://example.com/nl/dutch-article" rel="alternate" hreflang="nl-NL"** 

#### Actual result
n.a.

#### System information (as much as possible)
n.a.

#### Additional comments
This is according to the official Google Webmaster guidelines at https://support.google.com/webmasters/answer/189077?hl=en:

"If you have multiple language versions of a URL, each language page must identify all language versions, including itself."

By the way: This is the first time I am reporting an issue here, so forgive me if me if I reported this incorrectly.

**Comment by smz** [comment]
You're right. I think I know what should be modified and I'll probably propose a PR to fix this...

Unrelated: when creating example URLs, please use the **example.(com | net | org)** domains. Your URLs are redirect to an existing commercial domain (salesforce.com). Fix, if you can...

@infograf768, can you please have a look at this and give an opinion?

**Comment by dgt41** [comment]
@smz Here is some code I use in my custom head.php that might be handy:
```php
		$languages = JLanguageHelper::getLanguages();
		foreach ($languages as $item=>$value)
		{
			if (JFactory::getLanguage()->getDefault() == $value->lang_code)
			{
				$buffer .= '<meta property="og:locale" content="' . htmlentities($value->lang_code, ENT_HTML5, 'UTF-8') . '" />';
				unset($languages[$item]);
			}
			else
			{
				$buffer .= '<meta property="og:locale:alternate" content="' . htmlentities($value->lang_code, ENT_HTML5, 'UTF-8') . '" />';
			}
		}
```

This will produce the meta open graph for locale, change the `go:locale:alternate` to `alternate` is all you need?

**Comment by smz** [comment]
@dgt41 That might work, but I think the correct place where to fix this behavior is `PlgSystemLanguageFilter::onAfterDispatch()`

**Comment by dgt41** [comment]
@smz Yeap, that’s the place! I use this in head because joomla doesn’t set any open graph metas by default. Of course for the ones that are already done by J you have to change the behavior in the respected place!

**Comment by smz** [comment]
BTW, I'm working on it: it is trivial for the home page, but a bit more tricky for other items...

**Comment by dgt41** [comment]
@smz If you need any help just Skype me!

**Comment by smz** [comment]
:+1: thanks!

**Comment by smz** [comment]
@dgt41 have a look at #6963...

**Comment by dgt41** [comment]
@test OK with a minor thing that needs some attention
![screen shot 2015-05-16 at 5 32 52](https://cloud.githubusercontent.com/assets/3889375/7666529/c023f700-fbf1-11e4-8e68-984994b75e10.png)

Try some article that has "*" all languages as selected language, the produced code is invalid (star is not a language!) Maybe a simple check if...

**Comment by smz** [comment]
Ooops! Wiil fix...
(please, further comments in #6963)

**Comment by dgt41** [comment]
Damn wrong window 😊

**Comment by dgt41** [comment]
@tesk OK here! Thanks Sergio!

**Comment by smz** [comment]
I think this can be closed as we have #6963 fixing this issue...

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6923">issues.joomla.org/joomla-cms/6923</a>

**Comment by infograf768** [comment]
Closing as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6923">issues.joomla.org/joomla-cms/6923</a>.</sub>
