### ISSUE TITLE
Pagination does not working with child categories in back-end

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#6924]
#### Steps to reproduce the issue
There is a problem with pagination in article manager when I'm using filter and select any child category. 

#### Expected result
Pagination should work correctly.

#### Actual result
When I'm using filter in articles manager and select child category, I unable to reach other page (pagination does not working).When I choose child category or just clear filter, there is no such problem,

#### System information (as much as possible)
Checked it with Joomla 3.4.1 and two different servers:

PHP 5.4.40 
PHP 5.5.24

5.5.37-MariaDB-wsrep-log
MYSQL 5.1.73

#### Additional comments
I've recorded a video with visual explanation of the issue:
https://www.dropbox.com/s/z6xghzbaqp7vwig/pafination-bug.mov?dl=0

**Comment by zero-24** [comment]
@Sulpher this is a known issue see for a fix here: https://github.com/joomla/joomla-cms/pull/6677 the first report was here: https://github.com/joomla/joomla-cms/issues/6544

As we allready have a fix i'm closing here Thanks.

**Comment by Sulpher** [comment]
zero-24, thank you!
