### ISSUE TITLE
Save, Save & Close, Save & New, Save as copy & Close not working

### ISSUE THREAD

**Issue by vinayprakashverma** [joomla/joomla-cms#6927]
error - 
FF - The connection was reset
IE - This page can't be displayed
GC - This webpage is not available ERR_CONNECTION_ABORTED

**Comment by zero-24** [comment]
@vinayprakashverma this sounds like a site specific issue as it will work here without any issues please try to clean your cache (Browser and Joomla if enabled).

For support on site specific issues please use the support forum http://forum.joomla.org Thanks :smile:

**Comment by vinayprakashverma** [comment]
Thanks for reply, but i tried with clear cache in all browsers and still getting same issue.
Please help me

**Comment by roland-d** [comment]
@vinayprakashverma For support you can use the forum as pointed out by @zero-24 . This issue tracker is for issues with the Joomla code not your site. Thank you.

**Comment by vinayprakashverma** [comment]
how can track in @zero-24, can you help me to resolve

**Comment by roland-d** [comment]
@vinayprakashverma Go to http://forum.joomla.org and ask your question there. This is not the place for it. Thank you.

**Comment by vinayprakashverma** [comment]
ok  thanks.
