### ISSUE TITLE
Archived Articles module doesn't show checked out items

### ISSUE THREAD

**Issue by aaron-harding** [joomla/joomla-cms#6928]
The archived articles module doesn't display articles that are checked out. I've had an instance where all the articles in a given month were checked out and so the month wasn't displayed in the module.

Is this intentional? I don't think this is in effect anywhere else in the CMS.

/modules/mod_articles_archive/helper.php line 39

    ->where('state = 2 AND checked_out = 0')

**Comment by zero-24** [comment]
Agree can you send a PR that fixes the issue?

Code is here: https://github.com/joomla/joomla-cms/blob/staging/modules/mod_articles_archive/helper.php#L39

If you don't know how to create a PR please see:
https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

If you have a open PR can you add the link and close here?

Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6928">issues.joomla.org/joomla-cms/6928</a>.</sub>

**Comment by aaron-harding** [comment]
https://github.com/joomla/joomla-cms/pull/6930

**Comment by zero-24** [comment]
Thanks @aaron-harding :+1:
