### ISSUE TITLE
Adding Articles, installing plugins or changing global config after install redirects to front end

### ISSUE THREAD

**Issue by AdamWarnock** [joomla/joomla-cms#6932]
I recently installed Joomla 3.4.1 and I can't create any articles, install any plugins, or make any changes to the Global Configuration. Every time I try, I'm redirected to the front end of the website. Strangely, I can create, edit and delete users and menus, and I can edit and delete, but not create, modules. I can also only edit (can't test deleting) menu items.

I'm at a loss for what the cause is since I can't enable error reporting. System information is below

**PHP Built On** 	Linux ww8.bwsit.net 2.6.32-504.12.2.el6.x86_64 #1 SMP Wed Mar 11 22:03:14 UTC 2015 x86_64
**Database Version** 	5.6.23
**Database Collation** 	latin1_swedish_ci
**PHP Version** 	5.4.39
**Web Server** 	Apache
**WebServer to PHP Interface** 	cgi-fcgi
**Joomla! Version** 	Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
**Joomla! Platform Version** 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
**User Agent** 	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:39.0) Gecko/20100101 Firefox/39.0

**Comment by AdamWarnock** [comment]
Also tried switching Database users. Same issue.

**Comment by dgt41** [comment]
This sounds like file permissions. Read this: https://docs.joomla.org/Verifying_permissions

**Comment by AdamWarnock** [comment]
I don't think it is because creating an article doesn't touch the file system beyond calling the PHP files, and that doesn't explain the redirecting issue. What's weird is I can't do some things that just involve adding, editing or removing a database entry, but some other things, like adding a user or a menu, I can.

Besides it appears that all of the file permissions are correct.

**Comment by zero-24** [comment]
>I'm at a loss for what the cause is since I can't enable error reporting.

You can edit the `configuration.php` and set error reporting to `maximum`

But please use the forum for site specific issues and not the Issue Tracker. http://forum.joomla.org/ Thank you. If you discover a Joomla Bug and can tell us how we can reproduce it this can allways be reopen. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6932">issues.joomla.org/joomla-cms/6932</a>.</sub>
