### ISSUE TITLE
Frontend edit menu item opens edit module window in J.3.4

### ISSUE THREAD

**Issue by heiro** [joomla/joomla-cms#6935]
Hi
When clicking on the 'edit menu item' icon in J.3.4.1, the window for editing the menu module opens in frontend, and not the window for editing the menu item. This happens when using the Protostar template. Mouse-over edit icons for 'Modules and menues' is chosen in the Global Configuration.

I mean to remember that it worked ok in J.3.3.6 when you was directed to the backend administrator for editing menu items.

**Comment by zero-24** [comment]
@heiro

In 3.4.0 we changed the setting to redirect to the frontend. With the next Joomla Version you will be abele to choose your setting in the com_modules Configuration see: https://github.com/joomla/joomla-cms/pull/6910
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6935">issues.joomla.org/joomla-cms/6935</a>.</sub>
