### ISSUE TITLE
Robots.txt with "Disallow: /cache/" do Google Penalize Your Site

### ISSUE THREAD

**Issue by Casporro** [joomla/joomla-cms#6939]
If you have the cache activated and the disallow:/cache/ on robots.txt... google can penalize your web, check it here: https://www.google.com/webmasters/tools/mobile-friendly/
The problem is that css, js and image files are blocked for google.

**Comment by pe7er** [comment]
I've experienced this behavior also with a 3rd party extensions that store its combined optimized CSS & JS files in /cache/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6939">issues.joomla.org/joomla-cms/6939</a>.</sub>

**Comment by Bakual** [comment]
Closing as we have a pending PR now (#6940).
