### ISSUE TITLE
Search Tools Filters - not consistent

### ISSUE THREAD

**Issue by pe7er** [joomla/joomla-cms#6941]
Most administrator components have a [Search Tools] button that triggers extra filter options.
I noticed two issues:
1. The order of the different filter option dropdown boxes is not consistent
2. The place of the filter options is not consistent: sometimes on top of the middle column, sometimes on the left

Most components have
Status | Category | Access | Language | Tag
and some have at random positions
Max Levels | Author

I'll create separate PRs to make it easier to test & discuss them.

## Overview:
**User Manager: Users**
State | Active | Group | Registration Date

**Menu Manager: Menu Items**
Status | Max Levels | Access | Language

**Article Manager: Articles**
Status | Category | Max Levels | Access | Author | Language | Tag

**Category Manager: Articles** (and Banners, Contacts, Newsfeeds, User Notes Categories)
Max Levels | Status | Access | Language | Tag

**Article Manager: Featured Articles**
Status | Category | Max Levels | Author | Access | Language | Tag

**Banner Manager: Banners**
Status | Client | Category | Language

**Banner Manager: Clients**
Status | Type

**Private Messages Manager: Messages**
Status

**Contact Manager: Contacts** [Filters in LEFT column]
Status | Category | Access | Language | Tag

**News Feed Manager: News Feeds** [Filters in LEFT column]
Status | Category | Access | Language | Tag

**Redirect Manager: Links** [Filters in LEFT column]
Status 

**Smart Search: Manage Indexed Content** [Filters in LEFT column]
Any Published State | Any Type of Content

**Smart Search: Manage Content Maps**[Filters in LEFT column]
Branches Only | Any Published State

**Smart Search: Manage Search Filters** [Filters in LEFT column]
Any Published State

**Tags** [Filters in LEFT column]
Status | Access | Language

**Comment by brianteeman** [comment]
closing this here as we have multiple PR to address the issue identified<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6941">issues.joomla.org/joomla-cms/6941</a>.</sub>
