### ISSUE TITLE
Not possible to sort featured articles

### ISSUE THREAD

**Issue by radik10** [joomla/joomla-cms#6957]
#### Steps to reproduce the issue
create 2-3 featured articles, create menu showing "featured article", display with default protostar template (frontend)

#### Expected result
If you change settings for featured articles (in menu - in layout tab) by "Article Order" or "Category Order", articles (all categories) in that menu link, order of articles (on front end) is not changed. Doesn't matter, if you change order in "content - featured articles"...

#### Actual result
It seems to be (articles) ordered according name of categories (from "a" to "z") and is ignoring seetings (for order) in menu.

#### System information (as much as possible)
joomla 341, MySQL 5.5.40-36.1, php 5.4.17 

#### Additional comments
tested on localhost and commercial servers

**Comment by zero-24** [comment]
@radik10 can you tell us what exactly combination don't work? I have just tested 2 random option and they work for me. (Hits and alpha sorting)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6957">issues.joomla.org/joomla-cms/6957</a>.</sub>

**Comment by radik10** [comment]
Hi, 

No, if you change anything, in menu "layout" settings for featured article menu item, result is same. Change order of articles in "featured articles" is not working - I mean - in administration you can change their order, but on fronend this change is not visible. 
I have created test site. On right menu are some options available for featured articles. That server is designed for Joomla, so I have no idea where is problem. Link to testing page:
[http://joomlatest.r-art.sk](http://joomlatest.r-art.sk/ "")
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6957">issues.joomla.org/joomla-cms/6957</a>.</sub>

**Comment by zero-24** [comment]
hmm i just see your page. To be sure can you try the `Least Hits` option? As it works good here.

If that works please try more than 2 articles and categories.

**Comment by radik10** [comment]
Hi,
I did some more menu items - please see http://joomlatest.r-art.sk/ 

Every article is in different category and I have changed date for every article.
Please let me know, thanks.Best regards,Radovan
 


     On Saturday, May 16, 2015 2:05 PM, zero-24 <notifications@github.com> wrote:
   

 hmm i just see your page. To be sure can you try the Least Hits option? As it works good here.If that works please try more than 2 articles and categories.—

**Comment by bertmert** [comment]
Is * Category Order* set to *No Order*?

**Comment by radik10** [comment]
Hi, 

 In menu "layout" settings the "category order" was set to "Use global". And settings in "article manager options > shared options > category order" was set to "category manager". Now I have changed it to "No order" and my links for featured articles works. Thanks for hint.
I think, is time make Joomla less complicated (administration and php code). All necessary settings must be at one (logical) place and please add "hint" (short help sentences) in settings (in administration, over settings) so people will know what is necessary (and where) to change. Now is big chaos in joomla administration.

And is time, I think, to create "F.A.Q" section on Joomla.org pages for basic problems, like was my(n) with ordering of featured articles. What you think?
Again, thanks for help.Best regards,Radovan
 


     On Sunday, May 17, 2015 1:56 AM, bertmert <notifications@github.com> wrote:
   

 Is * Category Order* set to No Order?—
Reply to this email directly or view it on GitHub.   

   
     On Sunday, May 17, 2015 1:56 AM, bertmert <notifications@github.com> wrote:
   

 Is * Category Order* set to No Order?—
Reply to this email directly or view it on GitHub.   

   
     On Sunday, May 17, 2015 1:56 AM, bertmert <notifications@github.com> wrote:
   

 Is * Category Order* set to No Order?—

**Comment by zero-24** [comment]
Thanks for the tip @bertmert and the reply by @radik10 i'm closing here now as it is no Code issue Thanks :smile:
