### ISSUE TITLE
Redirect item deletion over 100 quantity bug

### ISSUE THREAD

**Issue by exlemor** [joomla/joomla-cms#6962]
#### Steps to reproduce the issue

If you have Redirect Plugin enabled and leave it on on a website for a few weeks.. you will accumulate many many lines of data here:

http://www.joomlawebsite.com/administrator/index.php?option=com_redirect&view=links

In my case, I had 1,800 or so...

I chose to delete some 100 at a time and it did that successfully. Since there sadly wasn't a Delete All option, after having deleted some 900 of them and being left with 800-900 or so, I chose to Choose All in the Show Filter - the server had NO problem displaying all of the lines.

I then checked the checkbox to Select All lines - which it did successfully but when I went
to DELETE them all, it didn't delete ANY and just showed me the same list it showed a few seconds ago...

After some testing, when the amount of lines was 444 lines, it did delete them all [I assume if under 500 it deletes them all]
 
#### Expected result
It should have deleted all of the lines.

IF there is a hard limit where it can't/won't delete more than 500 items then it should show an error message saying something to that effect or better yet it should just delete any amount of lines even if it is takes a while! [and there should be an estimated counter of how many seconds/minutes a process will take ideally].

#### Actual result
It didn't delete ANY of the lines if the amount of lines to delete seems to be over 500+ and just showed me the same list it showed a few seconds prior...  i.e. it doesn't do anything - but if you delete smaller amounts than ALL [where all = over 500] and get the total number of lines to under 500 and THEN select ALL and delete them, it works.

#### System information (as much as possible)
php 5.4.29, joomla 3.4.1, mysql 5.5.42, Apache 2.2 via cgi-fcgi
on CentOS 6.6 x64_64bit 

#### Additional comments

**Comment by zero-24** [comment]
Hi @exlemor,

this is a known issue.

A workarround can be the new option in Joomla 3.4.0. Since 3.4.0 you can disable the collection of 404 URLs in the Redirect Plugins Option.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6962">issues.joomla.org/joomla-cms/6962</a>.</sub>

**Comment by exlemor** [comment]
Hi zero-24,

Thanks for the comment - I did search so as to not post a duplicate but didn't find anything about this issue.

Also, i'm not sure that your answer is really answering what I see as an issue here - it's one thing to disable the collection of 404 URLs - and I'm sure that would help reduce the quantity and another at being unable to delete over 500 entries no?

Plus - I'd still like a system where you know how long a delete/move operation would take but I realize that's not a bug but more of a feature request ;)


Cheers,

Emmanuel<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6962">issues.joomla.org/joomla-cms/6962</a>.</sub>

**Comment by zero-24** [comment]
> I did search so as to not post a duplicate but didn't find anything about this issue.

I personally have report this issue some times bevor at the exactly same component :smile: but i guess it was on the old joomlacode Tracker.

>and I'm sure that would help reduce the quantity and another at being unable to delete over 500 entries no?

It is just a workarround to not get so much redirects. No fix for the issue.

>Plus - I'd still like a system where you know how long a delete/move operation would take but I realize that's not a bug but more of a feature request ;)

Agree. And for 90% of the action it don't make sense to me as it will take more time to calculate then to execute :smile: As in the most cases it is quite fast.

**Comment by brianteeman** [comment]
I guess we could have a Purge button on the toolbar that would truncate the database table<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6962">issues.joomla.org/joomla-cms/6962</a>.</sub>

**Comment by brianteeman** [comment]
Please see #7586 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6962">issues.joomla.org/joomla-cms/6962</a>.</sub>
