### ISSUE TITLE
Unable to correctly setup articles associations

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#6965]
#### Steps to reproduce the issue
1. make a clean installation from the staging code and perform the *Extra Steps* installing **two** additional languages (e.g. fr-FR and it-IT). In the *Extra Steps* also check the "Activate the mulitlingual feature* option, so that example categories/articles are installed too
2. set-up association between the 3 language specific categories (maybe unneded step, but no problem)
3. try to set-up association between the 3 articles (starting from the en-GB one)

#### Expected result
You should be able to set up association between the en-GB article and the fr-FR and it-IT articles

#### Actual result
when trying to set up the association for the it-IT article you are offered the fr-FR one

#### System information (as much as possible)
PHP Built On: Windows NT SMZ 6.3 build 9200 (Windows 8.1 Business Edition) i586
Database Version: 5.6.23
Database Collation: utf8_general_ci
PHP Version: 5.4.39
Web Server: Apache
WebServer to PHP Interface: apache2handler
Joomla! Version: Joomla! 3.4.2-dev Development [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0

#### Additional comments
The *problematic* language seems to be the one with the lowest language ID
e.g. if (beside en-GB) you install ca-ES and fr-FR, it is fr-FR that becomes problematic

**Comment by smz** [comment]
Corrected comment above: ~~lowest~~ -> highest

**Comment by smz** [comment]
If instead of two additional languages you install three, then you have issues for two of them: only the language with the lowest ID seems to work.

**Comment by bertmert** [comment]
Confirmed.

**Comment by bertmert** [comment]
I think it's just a multiple CSS id *modalArticle*. Thus always the last modal box opens  (= the last language).  I will try a PR.

**Comment by bertmert** [comment]
Please see and test PR https://github.com/joomla/joomla-cms/pull/6971

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6965">issues.joomla.org/joomla-cms/6965</a>

**Comment by infograf768** [comment]
Closing as we have a PR

https://github.com/joomla/joomla-cms/pull/6971<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6965">issues.joomla.org/joomla-cms/6965</a>.</sub>
