### ISSUE TITLE
How to go to another page simultaneously refresh it ?

### ISSUE THREAD

**Issue by pumanitro** [joomla/joomla-cms#6969]
Hello

I have that table on my page : 
![http://screenshotuploader.com/i/1505/t70ce.png](http://screenshotuploader.com/i/1505/t70ce.png "Picture 1")
I am using this javascript function to change view by clicking on div's ("Your Acc", "Add new Acc") :

window.location.href='index.php?option=com_addyourteam&view=createacc&layout=default';
and on another page similar line : 
window.location.href='index.php?option=com_addyourteam&view=createacc&layout=default_addnewacc';

But when i change between page data there doesn't refresh :(
I must refresh page by clicking F5 to see results .

Please help me.

**Comment by Bakual** [comment]
Please use our Google Group (https://groups.google.com/forum/#!forum/joomla-dev-general) for developer specific support or our forum (http://forum.joomla.org) for user support.
