### ISSUE TITLE
JDatabaseDriver::splitSql doesn't support comments, transactions, etc..

### ISSUE THREAD

**Issue by julienV** [joomla/joomla-cms#6975]
The current splitSql function is very flawed, as it doesn't support basic comments, or more complex procedures and transactions.

as a consequence, if you have a comment followed by a query in your component sql update files, the query will be ignored.

for example, this will be seen as a comment instead of one comment + 1 query
```sql
# this is my comment
UPDATE TABLE #__example_table ADD column eg VARCHAR(255);
```
#### Steps to reproduce the issue
Create a new sql update file for a component in the installer zip, adding some dummy column, like above

#### Expected result
the query should run

#### Actual result
the query just following the comment is ignored

#### Additional comments
This is undocumented, and very hard to debug for extensions maintainers, as putting comment happens ;)

**Comment by vdespa** [comment]
SQL update files do not work well with C style comments (# comment).

Did you try using comments like:

 -- comment

Not sure, but you may also try to write a comment with 

/* Comment  */

Looking forward to your feedback. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6975">issues.joomla.org/joomla-cms/6975</a>.</sub>

**Comment by wilsonge** [comment]
@mbabker something to address in the framework as well

**Comment by julienV** [comment]
i checked, it works with --comment and /* comment*/
so it's just with # comment that there is an issue

**Comment by brianteeman** [comment]
I am going to close this at this time as a method has been shown for comments that works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6975">issues.joomla.org/joomla-cms/6975</a>.</sub>
