### ISSUE TITLE
Apostrophes in email addresses

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#6982]
Joomla doesn't allow ```'``` char in user email, JFormRuleEmail pattern has ` but not '

It is allowed to have an apostrophe ' in the e-mail address by the RF5322 standard as long as it is an ASCII character.

Irish email as example: o'sullivan@domain.com

**Comment by smz** [comment]
@Denitz: PR is #7005 - Can you please test it?

**Comment by zero-24** [comment]
closing as we have a PR. by @smz

**Comment by Denitz** [comment]
I see BC issue:
Initial 'grave accent' char ` (0x60) was replaced with 'single quote' ' (0x27), so all current emails with 0x60 will be invalidated and users won't be able to save profiles.

We should add new allowed char (single quote) to patterns but not replace any existing chars.

**Comment by Spudley** [comment]
This problem is still an issue -- Joomla still does not accept apostrophes in email addresses.

The PR that was referencing this issue has been closed without being merged, so please can the issue be re-opened?

**Comment by MisterGumpo** [comment]
I am having the same issue. I have a number of email addresses with apostrophes in them - and they are valid email addresses.

Can the issue be re-opened and the PR merged?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6982">issues.joomla.org/tracker/joomla-cms/6982</a>.</sub>

**Comment by brianteeman** [comment]
Pretty certain that this was recently done but in a different pr

**Comment by MisterGumpo** [comment]
Any idea what PR it's in? I can modify the core files and wait for the next Joomla update :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6982">issues.joomla.org/tracker/joomla-cms/6982</a>.</sub>

**Comment by brianteeman** [comment]
Search and ye shall find :)

#12835
