### ISSUE TITLE
[Feature request] Limit number of items displayed by com_tags

### ISSUE THREAD

**Issue by Bugsbane** [joomla/joomla-cms#6987]
Hi there,
I really need to be able to limit the number of items that show when someone clicks a com_tags menu item, preferably with some form of pagination or "Read more" button at the end.

**Comment by BuddhiEash** [comment]
As i can see already there's a drop-down to choose number of items should be displayed per page.Minimum is 5.Isn't it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6987">issues.joomla.org/joomla-cms/6987</a>.</sub>

**Comment by zero-24** [comment]
Moving to `Information Required` until @Bugsbane had time to look into it :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6987">issues.joomla.org/joomla-cms/6987</a>.</sub>

**Comment by Bugsbane** [comment]
@BuddhiEash - Where? I see an option titled "Show number of items", but the dropdown only shows "Show / Hide / Global" and the description of it sounds more like it's supposed to show how many items have this tag. Changing it to "Show" doesn't make any visible difference I can see.

I don't see any option to choose the number of items displayed. If you do let me know and I'l check.

**Comment by BuddhiEash** [comment]
@Bugsbane - I have attached a screenshot here.Please check and let me know you are talking about this option :smile: ?

![Joomla_tagged_comp](http://oi58.tinypic.com/b49kzk.jpg "Screenshot")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6987">issues.joomla.org/joomla-cms/6987</a>.</sub>

**Comment by Bugsbane** [comment]
@BuddhiEash - Ok, I can see where the confusion is now. No, I am not talking about that dropdown. That dropdown lets the *user* decide how many items will be shown, and even then, only changes from the default if the user knows how to change it and bothers to do so.

What I am talking about, is an option like what is in the category blog menu type, that allows the *administrator* to set how many items the user will see. For example, in the Category Blog type, the administrator (not the user) chooses how many items to display as leading, how many in columns and how many articles in links.

I'm not requesting all of the different layout options that are in category blogs, just the same ability for the administrator to choose the number of items displayed to the user.

**Comment by pixelhexe** [comment]
I am also missing this feature. By default it shows the number which is saved in the joomla configuration (> Site > field "list length" or something similar - this is the German translation).

**Comment by BuddhiEash** [comment]
@Bugsbane - Ok.Now i got clarified what's you are talking about.So simply you are asking for a pagination?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6987">issues.joomla.org/joomla-cms/6987</a>.</sub>

**Comment by pixelhexe** [comment]
- for me, it would be sufficient to determine the number of items to display when a user opens the menu item THE FIRST TIME. In your screenshot for example, it's "20" in the dropdown. This is by default the number of the joomla configuration and we don't have the option to alter this separately for com_tag menu items.

**Comment by Bugsbane** [comment]
I'd say that there is more than one acceptable solution to this. I only care about limiting how many items show when a user clicks the menu item. This could be by pagination (showing X items per page), or it could be, as @pixelhexe says, a way to change the default in the currnt frontend drop down.

I just want to avoid every user who clicks on my blog link, having to load a page that shows 20 separate posts on a single page (5 would be my ideal).

Pagination, with a way to set the number of items per page, probably would be the ideal though.

**Comment by bertmert** [comment]
Menu item Compact list of tagged items.

Settings are a bit confusing. At the moment you can limit the displayed number of items by setting:
- List Layouts > Display Select > Hide
- List Layouts > Pagination > Show
- Item Selection Options > Maximum Items: e.g. 2

![tagged](https://cloud.githubusercontent.com/assets/11038612/7792341/1618bed2-02b1-11e5-945f-d451609de04c.jpg)

**Comment by bertmert** [comment]
Please see and test PR https://github.com/joomla/joomla-cms/pull/7031/commits

**Comment by zero-24** [comment]
Closing as we have a PR by @bertmert #7031

**Comment by Bugsbane** [comment]
I'll test when I have some spare time.

**Comment by bertmert** [comment]
>  Does this work with list by tag menu type rather than compact list?

Test first provided PR! Let's see if it works and will get a RTC label. Afterwards next PR. Solution seems to be similiar.

I had a 50:50 chance to select desired menu item for this first PR because of insufficient informations ;-)
