### ISSUE TITLE
[3.5-dev] Unable to install as we get Fatal error: Class 'Joomla\String\StringHelper' not found

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#6989]
### How to reproduce

- download https://github.com/joomla/joomla-cms/archive/3.5-dev.zip
- try to install 3.5-dev
- You get this issue:

`Fatal error: Class 'Joomla\String\StringHelper' not found in E:\Server\htdocs\35dev\libraries\joomla\string\string.php on line 23`

This is the same reason why travis fails on 3.5-dev: https://travis-ci.org/joomla/joomla-cms/builds/62588602

## Other failures

The first failure on 3.5-dev was: https://github.com/joomla/joomla-cms/commit/1f2cface18f13473c52d89e071b12b15309bf15c

But with a different error:
`PHP Fatal error:  Call to undefined method Mock_JApplication_c39b9c17::getLanguageFilter() in /home/travis/build/joomla/joomla-cms/libraries/cms/language/multilang.php on line 41`

**Comment by mbabker** [comment]
Committed the missing file from when #6600 was manually merged at b9b2cf3

**Comment by zero-24** [comment]
:+1:
