### ISSUE TITLE
Captcha - ReCaptcha version 2 : The captcha appears fully ineffective

### ISSUE THREAD

**Issue by rich20** [joomla/joomla-cms#6999]
With Chromium you need only mark checkbox and then submit.
With Firefox (38.0 Ubuntu) it does not matter if you choose wrong images. You can submit. https://github.com/Kunena/Kunena-Forum/pull/3106#issuecomment-103945282
I've tested also registration with Joomla,  it's the same, Chromium works without input.

**Comment by zero-24** [comment]
@rich20 I can confirm this but it looks like that is a browser / google Problem.

Check the Google demo here: https://www.google.com/recaptcha/api2/demo

As it don't work on the google demo sites itself i guess we can't do much on our site / code.

**Comment by rich20** [comment]
Thanks for your reply. Yes, it's the same at the Google test page. So it's not a Joomla captcha problem.
