### ISSUE TITLE
Hashtag external url links to home

### ISSUE THREAD

**Issue by klatte88** [joomla/joomla-cms#7002]
#### Steps to reproduce the issue
Making a parent item with a systemlink external url with a "#"

#### Expected result
adds # to the end of the current url

#### Actual result
Goes to homepage and adds #

#### System information (as much as possible)
Joomla 3.4.1 
php 5.5.23 
firefox 38.0.1
Chrome 43.0.x

#### Additional comments
This has worked many times before.

**Comment by brianteeman** [comment]
If it is an EXTERNAL url and the only part of the url you give is a # then
that is exactly what I would expect to happen

On 21 May 2015 at 09:27, klatte88 <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Making a parent item with a systemlink external url with a "#"
> Expected result
>
> adds # to the end of the current url
> Actual result
>
> Goes to homepage and adds #
> System information (as much as possible)
>
> Joomla 3.4.1
> php 5.5.23
> firefox 38.0.1
> Chrome 43.0.x
> Additional comments
>
> This has worked many times before.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7002>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Deleted my previous comment

**Comment by brianteeman** [comment]
Sorry about my earlier reply - not enough coffee

I have created an external menu link #fred 
From the home page that will generate example.com/#fred
From the contact page that will generate example.com/contact#fred

I can not replicate your issue. Perhaps some more detailed instrcutions on how to replicate

**Comment by klatte88** [comment]
I probably deserved it tbh.... It turns out it was a plugin doing naughty things in the name of SEF, it has been put in its place. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7002">issues.joomla.org/joomla-cms/7002</a>.</sub>

**Comment by roland-d** [comment]
Closing the issue as it is not a Joomla core issue.
