### ISSUE TITLE
SQL error with Banner Manager

### ISSUE THREAD

**Issue by dbegit** [joomla/joomla-cms#7006]
#### Steps to reproduce the issue
Banner Manager: New Banner
Add a banner, save and you will get a SQL error.

#### Expected result
no SQL error.

#### Actual result

Error

Save failed with the following error: SQL=INSERT INTO "gqcy4_banners" ("cid","type","name","alias","imptotal","impmade","clicks","clickurl","state","catid","description","custombannercode","sticky","ordering","metakey","params","own_prefix","metakey_prefix","purchase_type","track_clicks","track_impressions","publish_up","publish_down","reset","created","language","created_by","created_by_alias","modified","version") VALUES (0,0,'banner','banner',0,0,0,'',1,3,'','',0,1,'','{"imageurl":"images\\/banners\\/header-right.jpg","width":"","height":"","alt":""}',0,'',-1,0,0,'1970-01-01 00:00:00','1970-01-01 00:00:00','''2015-06-22 00:00:00''','2015-05-22 04:52:59','*',NULL,'','1970-01-01 00:00:00',1) RETURNING id

#### System information (as much as possible)
Joomla! 3.4.1
PHP 5.6.8
Postgresql 8.4.20

**Comment by zero-24** [comment]
Closing as we have a PR by @alikon here: #7009
