### ISSUE TITLE
Discover package with different Extension types

### ISSUE THREAD

**Issue by novusidea** [joomla/joomla-cms#7007]
Hello, is there a way to discover a package with different types via "Extensions > Extension Manager > Discover"? So that can be detected and installed the package.

**Comment by zero-24** [comment]
Yes. Just place all files to there place after the install and try the Discover button. Joomla find now the new packages and if you install them all is ok now :)
But please use for site specific issues the support forum http://forum.joomla.org Thanks :smile:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7007">issues.joomla.org/joomla-cms/7007</a>.</sub>
