### ISSUE TITLE
Strange problem on the "page" cache

### ISSUE THREAD

**Issue by maofree** [joomla/joomla-cms#7014]
hi
I made some websites with joomla and yesterday I've found a problem when I made some changes on a text of an article.
for example if I add an 1 into the editor it appears on it, but in the fron-office no
only if I clean the cache of the item "page" and the browser's cache I can see it.
But if I go into global configuration page and set to "NO cache" from "progressive cache" I see that in the cache page the "page" item is always present and for all changes I need to remove that voice and then clean the browser's cache.
The strange thing is that in other sites (the are all with the same hosting but different servers and without any type of server cache) other 3 sites have this type of problem and other 2 sites work well with progressive cache enabled too (I can change their texts and see immediately them on the front-office).
All these sites are with joomla 3.4.1 and with the same configuration
However when the cache is not enabled the "page" item should not be presente in the cache list and it enabled all changes made in the editor should regenerate immediately its cache to permit to see every changes.
It is the first time that I get this problem and only in some sites and not all
http://www.anticotravaglio-monteriggioni.com

![2](https://cloud.githubusercontent.com/assets/653230/7783580/319c45b8-0147-11e5-8c0b-1ef8b05a8c0e.png)

![3](https://cloud.githubusercontent.com/assets/653230/7783582/35685b46-0147-11e5-8302-866712841d31.png)

thanks

bye

**Comment by bertmert** [comment]
Is plugin *System - Page Cache* activated? By default it's deactivated. And it's independent of global configuration settings and it uses folder page.

**Comment by maofree** [comment]
yes
thanks a lot
it is due from System - Page Cache
disabling it all it is ok

bye
