### ISSUE TITLE
Menu Manager > when clicking on button to (un)publish, all subitems are also (un)published whatever their initial status

### ISSUE THREAD

**Issue by woluweb** [joomla/joomla-cms#7018]
#### Steps to reproduce the issue

Go to Menu Manager.
Choose a menu where some menus have submenus
Take a menu item having several child items, some being published others unpublished
If you unpublish the parent item, all child items are also automatically unpublished.
The other way round : iff you then publish the parent item, all child items are automatically published.
With other words, you "loose" the status of all childs items (very annoying when you temporarily unpublish a menu item. If its child items had diverse status, you will never know again what their status was...)
Illustration (before/after) : 
![screen shot 2015-05-23 at 12 43 14](http://issues.joomla.org/uploads/1/630d8df2669c0dbf74a1797ce914132c.png)
![screen shot 2015-05-23 at 12 44 02](http://issues.joomla.org/uploads/1/3f34b837baad94e515d2bf8a45d7786f.png)
#### Expected result

When clicking on a publish/unpublish button of a menu item, you would expect to only affect the chosen element (not its childs).
#### Actual result

When clicking on a publish/unpublish button for a menu item, all its childs take the same status
Note that if you really EDIT the parent menu item and change there its status, when saving it does not affect the status of its child items (which _is_ the expect result)

**Comment by brianteeman** [comment]
I believe it is CORRECT and logical behaviour that if you unpublish a parent menu item that all submenus are also unpublished.

However I agree that it is not correct or logical that if you then publish a parent item all the submenu items are also published<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7018">issues.joomla.org/joomla-cms/7018</a>.</sub>

**Comment by woluweb** [comment]
Txs Brian for the quick feedback.
I understand your point of view in the sense that : "if a parent menu item is unpublished, the front-end should not show it of course, nor its child items... whatever their status".
[ And I do agree that, in a ideal world, people should even never have "unpublished" items if they want everything clean & tidy :-) ]

But being in backend, in many sites it happens many times that you have some unpublished menu items. And it is very confusing that Joomla takes initiative : you only publish/unpublish a menu item and -without any notice- all its childs get impacted.
(On top of that : if you edit the parent menu item and change its status there, its childs are not affected)
Personally, if I want to change the status of _several_ items in Menu Manager, I simply tick each of them.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7018">issues.joomla.org/joomla-cms/7018</a>.</sub>

**Comment by DanielvanBavel** [comment]
I will work on this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7018">issues.joomla.org/joomla-cms/7018</a>.</sub>

**Comment by sanderpotjer** [comment]
@DanielvanBavel any updates on this? Not sure what you are planning to work on?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7018">issues.joomla.org/tracker/joomla-cms/7018</a>.</sub>

**Comment by jlainezs** [comment]
The "problem" is that the publish button on the row it ends calling JTableNested::publish which updates the item and its children, while when editing the item it only saves the state.
To have the same behaviour on both cases I think the call to parent::publish on com_menus/models/item.php (around line 1631) should be changed
with a simple update of the given pk's and then return the result of the update. I can prepare a PR with this modification.
Any comments?


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7018">issues.joomla.org/tracker/joomla-cms/7018</a>.</sub>

**Comment by jlainezs** [comment]
By the way... the PR should be developed using the staging branch or the 3.6.x branch?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7018">issues.joomla.org/tracker/joomla-cms/7018</a>.</sub>

**Comment by andrepereiradasilva** [comment]
staging branch

**Comment by jlainezs** [comment]
Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7018">issues.joomla.org/tracker/joomla-cms/7018</a>.</sub>

**Comment by gunjanpatel** [comment]
Closing as we have PR #13242 for this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7018">issues.joomla.org/tracker/joomla-cms/7018</a>.</sub>
