### ISSUE TITLE
Modules > custom HTML > no versioning (like for articles)

### ISSUE THREAD

**Issue by woluweb** [joomla/joomla-cms#7019]
#### Steps to reproduce the issue
Versioning in Joomla is a quite recent feature, but very useful and very much appreciated.
Actually, custom HTML does not offer versioning, while it happens often that some user (or even yourself :-) ) does edit a Custom HTML module and for some reason has to come back to some previous version.
So far, versioning does not exist for Custom HTML

#### Expected result
Versioning should be "generalized" to Custom HTML

**Comment by sc00zy** [comment]
I was just looking for this... Too bad this isn't core stuff yet :-)

**Comment by Bakual** [comment]
It doesn't exist for any modules as far as I know.

**Comment by brianteeman** [comment]
Thank you for your suggestion but it has been decided that this is not something that will be included in the core of Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7019">issues.joomla.org/joomla-cms/7019</a>.</sub>
