### ISSUE TITLE
JLanguage getDefault() method

### ISSUE THREAD

**Issue by davidetaddei** [joomla/joomla-cms#7025]
#### Steps to reproduce the issue
In Joomla 3.4.1 the JLanguage class has method getDefault which returns the $default property which has a fixed value of 'en-GB', check file libraries/joomla/language/language.php at row 1114 and row 46.

#### Expected result
In my opinion the method should first check the value of the predefined language in the extensions -> language manager -> Installed - Site menu.

#### Actual result
At the moment it always returns 'en-GB'.

#### System information (as much as possible)
This is the default installation.

#### Additional comments
Is there a particulare reason why it has ben set like that?

**Comment by mbabker** [comment]
Structurally it'd be a bad idea to change JLanguage like this; it would couple a top level library API to a specific component's implementation.  Plus, if it were going to pull from the Language Manager's config, it should be app aware (so if you're in admin you should be getting the admin default).

One option would be to set the default when the object is created via JFactory based on this config.

**Comment by Fedik** [comment]
@davidetaddei  `JLanguage::getDefault()` return default language for "fallback",  means [used while string translation and translation not found](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/language/language.php#L41).
It not the same as the site default language.

But I think, something like `getFallbackLanguage()` would be more clear than `getDefault()` :smiley:

**Comment by brianteeman** [comment]
It has been 6 months since the last comment on this issue and based on the comments above I am closing this as it isn't going anywhere.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7025">issues.joomla.org/joomla-cms/7025</a>.</sub>
