### ISSUE TITLE
Value of "Show Subcategories Text" is ignored

### ISSUE THREAD

**Issue by isaac-s** [joomla/joomla-cms#7027]
#### Steps to reproduce the issue

In Global Configuration, set "Show Subcategories Text" to "Hide".
Create a categories hierarchy, and add a menu item of type "category/blog", pointing to a category that has subcategories.

#### Expected result

The "subcategories:" heading is not shown.

#### Actual result

The "subcategories:" heading is shown.

#### System information (as much as possible)

Joomla 3.4.1 running on Ubuntu 14.04.

#### Additional comments

Can provide backend access to demonstrate if needed.

**Comment by bertmert** [comment]
I cannot confirm this issue. Tested with staging package.
- Menu item type Articles > Category Blog.
Setting:
Category > Show Subcategories Text > Use Global
- Article Manager Options > Category > Show Subcategories Text > **Show**:

![subcatshow](https://cloud.githubusercontent.com/assets/11038612/7795058/75403a28-02d1-11e5-9df6-ee60b9a3980f.jpg)
- Article Manager Options > Category > Show Subcategories Text > **Hide**

![subcatshide](https://cloud.githubusercontent.com/assets/11038612/7795059/7542a862-02d1-11e5-8788-b8321a634b65.jpg)

- Templates: Protostar and Beez3.

**Comment by brianteeman** [comment]
I "think" this was a misunderstanding on the meaning of this option.

On 25 May 2015 at 10:32, bertmert <notifications@github.com> wrote:

> I cannot confirm this issue. Tested with staging package.
>
>    - Menu item type Articles > Category Blog. Setting: Category > Show
>    Subcategories Text > Use Global
>    - Article Manager Options > Category > Show Subcategories Text > *Show*
>    :
>
> [image: subcatshow]
> <https://cloud.githubusercontent.com/assets/11038612/7795058/75403a28-02d1-11e5-9df6-ee60b9a3980f.jpg>
>
>    - Article Manager Options > Category > Show Subcategories Text > *Hide*
>
> [image: subcatshide]
> <https://cloud.githubusercontent.com/assets/11038612/7795059/7542a862-02d1-11e5-8788-b8321a634b65.jpg>
>
>    - Templates: Protostar and Beez3.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7027#issuecomment-105182442>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by bertmert** [comment]
But confirmed for menu item Articles > Category List and Contacts > Category List.
I'll provide a PR.

**Comment by brianteeman** [comment]
Closing as we have a PR #7034 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7027">issues.joomla.org/joomla-cms/7027</a>.</sub>
