### ISSUE TITLE
Batch process articles completely broken

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#7038]
#### Steps to reproduce the issue
Install current staging with testing sample data
In article manager select multiple articles
Press batch on the toolbar
Select a tag eg red (same with all other batch options)
Click Process

#### Expected result
Batch action is performed

#### Actual result
>  Invalid controller: name='contact', format=''

If you have debug enabled then you will see further information

>Call stack
#	Function	Location
1	JApplicationCms->execute()	/Applications/MAMP/htdocs/joomla-cms-staging/administrator/index.php:47
2	JApplicationAdministrator->doExecute()	/Applications/MAMP/htdocs/joomla-cms-staging/libraries/cms/application/cms.php:252
3	JApplicationAdministrator->dispatch()	/Applications/MAMP/htdocs/joomla-cms-staging/libraries/cms/application/administrator.php:152
4	JComponentHelper::renderComponent()	/Applications/MAMP/htdocs/joomla-cms-staging/libraries/cms/application/administrator.php:98
5	JComponentHelper::executeComponent()	/Applications/MAMP/htdocs/joomla-cms-staging/libraries/cms/component/helper.php:372
6	require_once()	/Applications/MAMP/htdocs/joomla-cms-staging/libraries/cms/component/helper.php:392
7	JControllerLegacy::getInstance()	/Applications/MAMP/htdocs/joomla-cms-staging/administrator/components/com_content/content.php:20
 Return to Control Panel

#### System information (as much as possible)
This is with staging branch as at 09:00 GMT Tuesday 26 May

**Comment by infograf768** [comment]
I guess there was a copy/paste.

Change `contact.batch` to `article.batch` 
in
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/views/articles/tmpl/default_batch_footer.php#L15

**Comment by wilsonge** [comment]
PR https://github.com/joomla/joomla-cms/pull/7040
