### ISSUE TITLE
Joomla! 3.4.1 Stable - Causes issues

### ISSUE THREAD

**Issue by KarenBrown** [joomla/joomla-cms#7046]
#### Steps to reproduce the issue
I upgraded an Joomla installation today (local machine) as there was an update available to Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT.  Since then none of my "Save", "Save and Close" and "Save as a copy" buttons work.
Is there a way to roll back to a previous version?

**Comment by zero-24** [comment]
@KarenBrown please clean your browser and joomla cache. This should fix it :smile:

**Comment by zero-24** [comment]
For support on site specific issues please use the support forum http://forum.joomla.org Thanks :smile: This is a well known problem :smile:
