### ISSUE TITLE
Displaying User Profile Data in Contacts area, labels and values do not align vertically

### ISSUE THREAD

**Issue by robinne** [joomla/joomla-cms#7049]
#### Steps to reproduce the issue
Enable the "User - Profile" plugin.
Go to Plugin Manager, search for User - Profile. Enable it.

Create or update a User and include some User Profile data (address, city, region, country, zip, phone and website)
Users > User Management. Select a user, select the User Profile Tab.

Add a Contact, link it to the user.
Components > Contacts > New
Set "Linked User" to the user with the profile data filled out (in step 1)
Do not fill out any contact information, other than Name.

Configure Contacts options to show profile:
Components > Contacts > Options
Show Profile = Show
Create a menu item to display Contacts
Menus > Main Menu. Add:
Menu Item Type = Contacts > List All Contact Categories.
Select a Top Level Category: keep this at "Root"

Load website and navigate to the new menu item
Select the category (by default, will be "Uncategorised")
Select the Contact you have added

#### Expected result
Address value should line up with "Address 1" label. 
City value should line up with "City" label.
Region value should line up with "Region"
etc.

#### Actual result
Address value lines ups with "Address 1:".
City value is above "City:" label.
Region value is above "Region:" label.
etc.

#### System information (as much as possible)
Joomla 3.4.1
Windows 7
Chrome 43.0.2357.81 m, or IE 11

#### Additional comments
Screenshot of issue (viewing Contact details):

![screen shot 2015-05-27 at 11 18 16](http://issues.joomla.org/uploads/1/977088042e20e796a185da8ddfe32e8c.png)

**Comment by Bakual** [comment]
See #7345
Closing as we have a PR to test.
