### ISSUE TITLE
Per-article "Show intro text" option ignored

### ISSUE THREAD

**Issue by ZoFx** [joomla/joomla-cms#7050]
#### Steps to reproduce the issue
1. In "Global Configuration -> Articles" set "Show Intro Text" to "Show".
2. In the article options of a specific article, set "Show Intro Text" to "Hide".

#### Expected result
Option must be respected, intro text must be hidden.

#### Actual result
The intro text for this specific article is still shown in the article view.

#### System information (as much as possible)
Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
PHP-Version 	5.4.31

#### Additional comments
This bug seems to have been in Joomla for almost forever (at least since J1.6). It was covered in a Joomlacode issue, but never solved:
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=30249

**Comment by bertmert** [comment]
Are you taliking about a specific menu item type (list, featured, blog)?

**Comment by bertmert** [comment]
Tested with staging package of today 2015-05-28 05h.

Created a menu item Category Blog > Options > "Show Intro Text" > Use Global
In "Global Configuration -> Articles" set "Show Intro Text" to "Show".
In the article options of an article, set "Show Intro Text" to "Hide".

In view single article there's no intro text now. So please provide more detailed test instructions.

But, BTW, I would expect that I must set
menu item Category Blog > Options > "Show Intro Text" >  **Use Article Settings**
and not Use Global (?)

**Comment by ZoFx** [comment]
Thanks for looking into this. You're absolutely right - it's not a Joomla core issue in the first place.

Actually, with the com_content blog layout everything works as expected. The problems are related to the "DM pinbaord lite" category view component that I'm using. Unfortunately this thing doesn't offer an option to control if the intro text is displayed - so it certainly has to do with an improperly designed extension.

But still, even then the article view ist handled by com_content and I would expect it to respect the per-article setting independent of the categegory component? Or am I missing something?

**Comment by Bakual** [comment]
I had a look at the code of the extension and it doesn't seem to merge in the article params. So any parameter you set in the article isn't respected there.
And it doesn't use com_content to show the articles as far as I see.

Closing as it's not a core issue.

**Comment by ZoFx** [comment]
I thought it was com_content as I tried to turn off SEO und the URL of the article view (accessed via the extenstion category view) was:
index.php?option=com_content&view=article&id=18&catid=10&Itemid=250

But probably you're going to tell me that this works differently ... I still don't really seem to get, how joomla works at its heart :-).

**Comment by Bakual** [comment]
Ah, I see what you mean. You're right then. The article view itself is done by com_content. The other extension only does the list thing.
However that really works fine. One thing to check is the active menu item. I'd say the menu item with the ID 250 (&Itemid=250) is a single article menu item pointing to this article in question.
The reason is that the options from a specific "single article" menuitem take precedence over the settings in the article itself.

**Comment by ZoFx** [comment]
Great! Got it working. I'm very sorry to have bothered you with my incompetence on github when at last it isn't a bug at all. But I really appreciate your help, thanks a lot!

**Comment by Bakual** [comment]
If it is set to "Use Global" in the menu item, then it indeed should (and does) respect the article settings. At least it did in my tests.
