### ISSUE TITLE
Pagination broken when search filter active

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#7051]
Found in Joomla 3.4.1 and tested with Staging package of today 2015-05-28
- Go to backend.
- Copy an article using batch button e.g. article titled "Joomla! Testing" several times (30, 40).
- In search box enter *joo*, click search button.
- Go to pagination below list and try to change page.
- Pagination doesn't work Always page 1.

In frontend a similiar issue (Articles >> Category List). But there clicking the pagination clears search box.

**Comment by Bakual** [comment]
Closing since there is a PR #7052
