### ISSUE TITLE
Title field sometimes disappears in Safari

### ISSUE THREAD

**Issue by josien** [joomla/joomla-cms#7077]
#### Steps to reproduce the issue

- Use Safari on Mac, log in backend.
- Open an existing article or category or create a new article or category. 
- Look at title field.

#### Expected result

Mostly it just looks normal as it should.

#### Actual result

In some cases the title field is hidden behind the buttons on the top (Save/Save&Close, etc.). It happens occasionally, and it is difficult to find the circomstances in which the title field disappears. 

Reloading the page does not have an effect. Closing the article or category and opening it again sometimes helps. 

#### System information (as much as possible)
Safari 8.0.6
Joomla 3.4.1

#### Additional comments

If you can't reproduce this error, please try to open many articles (or categories) and close them until you find the error. I mostly see it after opening ~5 articles. 

See screenshot attached. 

![screen shot 2015-05-30 at 11 00 01](http://issues.joomla.org/uploads/1/d0aced3aff9990ff0d5adf1abeea89b8.png)

**Comment by losedk** [comment]
Already posted here #5970

**Comment by zero-24** [comment]
Closing as dublicated to #5970 Thanks :smile:
