### ISSUE TITLE
Article Meta Description not used

### ISSUE THREAD

**Issue by ridderr** [joomla/joomla-cms#7098]
#### Steps to reproduce the issue
The Meta Description specified with an article is not displayed in the meta tag in the head. Only the Site Meta Description tag (defined in Global Configuration) is used.
Google is complaining that all my Meta Description tags are the same.

Since I don't know an option to enable the arcticle Meta Description this looks like to be a bug to me.

#### Expected result
&lt;meta name="description" content="Article specific Meta Description as defined with the article"&gt;

#### Actual result
&lt;meta name="description" content="System defined Site Meta Description"&gt;

**Comment by zero-24** [comment]
@ridderr I'm unable to reprduce this on the last version. Can you try it on a plain 3.4.1? Maybe some Plugin jump in?

**Comment by ridderr** [comment]
@zero-24 ,thanks for your prompt feedback. I have tried again and now it is working??. Maybe it has something to do with the cache??
