### ISSUE TITLE
Trashed articles - final trash button republishes the article instead

### ISSUE THREAD

**Issue by gphood** [joomla/joomla-cms#7100]
#### Steps to reproduce the issue
Log into Administrator
Trash a standard article.
Filter the article view to see all trashed articles.
See the option buttons under Status, one of which is Trash
Click on the Trash button.
Remove the Trashed filter 
View the remaining Published articles

#### Expected result
When the article view filter is set for Trashed articles, the Trash button should completely delete the article from Joomla and that should be reflected in the Tooltip for that button.
After the final Trash, that article should no longer appear in the Article Manager.

#### Actual result
Hovering over the Trash button generates a Tooltip saying 'Publish Item'
Clicking on the Trash button republishes the article instead of completely removing it from the system.

#### System information (as much as possible)
Linux cloud hosting running PHP 5.512 and MySQL 5.6.21 and Apache
Joomla! 3.4.1 Stable

**Comment by brianteeman** [comment]
As the tooltip indicates the button there is used to toggle the state of the article from trashed to published.

To empty the trsh you need to select the items and click on the empty trash button on the toolbar

**Comment by gphood** [comment]
Hi Brian

Thanks for the quick feedback. Not sure how I missed the additional buttons above the filter buttons - I've actually used it before so I've no excuse. I was confused by the button still having the Trash icon on it, even though it publishes. I think I'd thought it was a reworked feature. Should it have a different icon on it?

**Comment by brianteeman** [comment]
Thats a valid point. 
Unfortunately though that button has two purposes. One to visually display the current status (remember you can display all articles in a single view) and to perform an action (republish). So I am really not sure what it could be changed to as it will always be a poor representation for one of the functions. Not ideal but I believe the current way is the best of a bad job

**Comment by gphood** [comment]
Righto - understood. Appreciate your time.
