### ISSUE TITLE
Youtube feed fail to procude clickable links in mod_feed

### ISSUE THREAD

**Issue by RemcoJanssen** [joomla/joomla-cms#7112]
#### Steps to reproduce the issue
Get your youtube feedurl for the new API, it looks something like:

https://www.youtube.com/feeds/videos.xml?channel_id=UCrLxxxxxxxxuFcov-Hlg
where UCrLxxxx etc. is your Channel Id, which you can get by watching this tutorial:
https://youtu.be/SjH_xA6zTzs

Enter this feed url into a mod_feed module.
publish the module

#### Expected result

A list of youtube video titles on which you can clik to go to the actual video on youtube

#### Actual result

A list of youtube video titles without a link, so you can't click to go to the video

#### System information (as much as possible)

Joomla 3.4.1 

#### Additional comments

The youtube rss entry looks like:

<entry>
<id>yt:video:PhIHPP_IUPQ</id>
<yt:videoId>PhIHPP_IUPQ</yt:videoId>
<yt:channelId>UCrLSAKxxxxxxxxxcov-Hlg</yt:channelId>
<title>
Real Road Racing op 2 en 3 mei in Hengelo Gld - Nieuwsmotor.nl
</title>
<link rel="alternate" href="http://www.youtube.com/watch?v=PhIHPP_IUPQ"/>
<author>
<name>Nieuwsmotor NL</name>
<uri>
http://www.youtube.com/channel/UCrLSAKxxxxxxxxxXuFcov-Hlg
</uri>
</author>
<published>2015-04-27T15:09:56+00:00</published>
<updated>2015-05-30T14:13:15+00:00</updated>
<media:group>
<media:title>
Real Road Racing op 2 en 3 mei in Hengelo Gld - Nieuwsmotor.nl
</media:title>
<media:content url="https://www.youtube.com/v/PhIHPP_IUPQ?version=3" type="application/x-shockwave-flash" width="640" height="390"/>
<media:thumbnail url="https://i1.ytimg.com/vi/PhIHPP_IUPQ/hqdefault.jpg" width="480" height="360"/>
<media:description>- meer info @ http://www.nieuwsmotor.nl</media:description>
<media:community>
<media:starRating count="1" average="5.00" min="1" max="5"/>
<media:statistics views="73"/>
</media:community>
</media:group>
</entry>

The uri variable in Joomla mod_feed has the value: id:video:PhIHPP_IUPQ instead of the url

**Comment by Bakual** [comment]
It may be because the feed isn't really RSS compliant. FeedValidator chokes quite a bit on it:
https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.youtube.com%2Ffeeds%2Fvideos.xml%3Fchannel_id%3DUCy6ThiEDnalZOd_pgtpBk1Q

Tested with the JaB feed: https://www.youtube.com/feeds/videos.xml?channel_id=UCy6ThiEDnalZOd_pgtpBk1Q

**Comment by brianteeman** [comment]
Resetting priority according to our standards https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7112">issues.joomla.org/joomla-cms/7112</a>.</sub>

**Comment by RemcoJanssen** [comment]
Sorry Brian, I did look at the priority list, but figured as with YT feed the module doesn't function it validated as urgent. 

Bakual, I agree that the feed should be valid, but as this is Youtube/Google, I think they are not going to change it for us...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7112">issues.joomla.org/joomla-cms/7112</a>.</sub>

**Comment by Bakual** [comment]
On the other hand, the modules is a newsfeed module. It's not a Youtube module :smile: 

From what I saw, it's out JFeed class which doesn't return a link property for the entries. Since JFeed uses SimpleXML to get the data, it may as well be an issue there. Which then again may come from the fact that Youtube doesn't generate a valid RSS feed.

**Comment by RemcoJanssen** [comment]
I didn't go as far as looking at that, instead I quick-fixed the issue by a template override and addition to the feed generation using:

if (stristr($feed[$i]->uri, 'yt:video')) {
$videocode = str_replace("yt:video:", "", $feed[$i]->uri);
$uri ="https://www.youtube.com/watch?v=".$videocode;
}

Which is not a good long-term solution, but works for my purpose.

**Comment by Bakual** [comment]
As long as you did a proper template override, this is fine as a long-term solution.

**Comment by zero-24** [comment]
Closing as it is resolved per template override and i not a core issue.
