### ISSUE TITLE
Multiple Textarea/Editor Parameters in a Module Fail to Save and field get clean

### ISSUE THREAD

**Issue by anamikakush** [joomla/joomla-cms#7116]
# Steps to reproduce the issue

Create a custom module that has Five or more textarea and editor field types.

# Expected result

Expect fields to save correctly.

# Actual result

ALL fields (including text, menuitem, etc... types) are cleared and not saved.

# System information (as much as possible)

Joomls! 3.4.1

**Comment by brianteeman** [comment]
Resetting priority according to our standards https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>

**Comment by anamikakush** [comment]
Dear, Please help me to resolve the issue soon so that we can upload the work on server.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>

**Comment by brianteeman** [comment]
If you supply a copy of the module it will help people to test <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>

**Comment by anamikakush** [comment]
Thanks for your quick reply, It is not allowing me to upload the text files, Can i just add the code here, Please advise<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>

**Comment by brianteeman** [comment]
Best to just add a link to somewhere people can download them from such as dropbox<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>

**Comment by anamikakush** [comment]
Thanks for your reply. Please find the code below:

--------------------------------------------------------------------------------------------------------

	
	
		<fields name="params">
	
		<fieldset name="tab1" label="TAB 1">

		
			
			<field type="radio" class="btn-group" name="tab_state_1" default="0" label="Show Tab" description="Show Tab">	
			</field>
			<field type="spacer" name="spacer_tab_1" label="&lt;h3&gt; Accordion Tab 1 Parameters &lt;/h3&gt;&lt;hr/&gt;" />
			<field name="tab_title_1" type="text" default="" label="Title" description="Enter Tab title" />
			
			<field type="radio" class="btn-group" name="title_state_1" default="1" label="Show Title" description="Show Title">
								</field>
			
			<field type="radio" class="btn-group" name="tab_number_1" default="1" label="Show Tab Number" description="Show Tab Number">
						</field>
			
			<field type="radio" class="btn-group" name="tab_icon_state_1" default="1" label="Show Icon" description="Show Icon">
					
			</field>
			<field name="tab_icon_1" type="text" default="" label="Tab Icon Class &lt;br/&gt; (&lt;a href='http://fortawesome.github.io/Font-Awesome/icons/' target='_blank'&gt;Use FontAwesome Icon&lt;/a&gt;)" description="Enter FontAwesome icon Class" filter="raw" showon="tab_icon_state_1:1" />
			
			<field type="radio" class="btn-group" name="tab_strip_state_1" default="1" label="Show Strip" description="Show Strip">
					
			</field>
			<field name="tab_strip_1" type="text" label ="Enter Strip Text" description="Enter Strip Text"/>	
			
			
			<field type="radio" class="btn-group" name="short_desc_state_1" default="1" label="Show Short Description" description="Show Short Description">
					
			</field>			
			<field name="short_desc_1" type="text" default="" label="Enter Short Description" description="Enter Short Description"  filter="raw" showon="short_desc_state_1:1" />			
			
			<field type="radio" class="btn-group" name="long_desc_state_1" default="1" label="Show Full description" description="Show Full description">

			</field>					
			<field name="long_desc_1" label ="Enter Full Description" description="Enter Full Description" type="editor" width="300" filter="safehtml" />	
			
			<field name="tab_title_color_1" type="text" default="#FFFFFF" label="Tab Title Color" description="Enter Tab Title Color" />
			<field name="tab_title_size_1" type="text" default="17px" label="Tab Title Size(px)" description="Enter Tab Title Size" />
			<field name="tab_bgcolor_1" type="text" default="#47C5F4" label="Tab Background" description="Enter Tab Background Color" />
			<field name="tab_short_desc_color_1" type="text" default="#FFFFFF" label="Short Desc Color" description="Enter Short description Size" />
			<field name="tab_short_desc_size_1" type="text" default="14px" label="Short Desc Size(px)" description="Enter Short Description Size" />
			<field name="tab_full_desc_color_1" type="text" default="#c7c7c7" label="Full Desc Color" description="Enter Full Desc Color" />
			<field name="tab_full_desc_size_1" type="text" default="14px" label="Full Desc Size(px)" description="Enter Tab Content Size" />
			<field name="tab_icon_color_1" type="text" default="#FFFFFF" label="Tab Icon Color" description="Enter Tab Icon Color" />
			<field name="tab_icon_size_1" type="text" default="3.4em" label="Tab Icon Size(px)" description="Enter Tab Icon Size" />		
			
		</fieldset>
		
				<fieldset name="tab2" label="TAB 2">		
			
			
			
			<field type="radio" class="btn-group" name="tab_state_2" default="0" label="Show Tab" description="Show Tab">
					
			</field>
			
			<field type="spacer" name="spacer_tab_2" label="&lt;h3&gt; Accordion Tab 2 Parameters &lt;/h3&gt;&lt;hr/&gt;" />
			
			<field name="tab_title_2" type="text" default="" label="Title" description="Enter Tab title" />
			
			<field type="radio" class="btn-group" name="title_state_2" default="1" label="Show Title" description="Show Title">
					
			</field>
			
			<field type="radio" class="btn-group" name="tab_number_2" default="1" label="Show Tab Number" description="Show Tab Number">
					
			</field>
			
			<field type="radio" class="btn-group" name="tab_icon_state_2" default="1" label="Show Icon" description="Show Icon">
					
			</field>
			<field name="tab_icon_2" type="text" default="" label="Tab Icon Class &lt;br/&gt; (&lt;a href='http://fortawesome.github.io/Font-Awesome/icons/' target='_blank'&gt;Use FontAwesome Icon&lt;/a&gt;)" description="Enter FontAwesome icon Class" filter="raw" showon="tab_icon_state_2:1" />
			<field type="radio" class="btn-group" name="tab_strip_state_2" default="1" label="Show Strip" description="Show Strip">
				
			</field>
			<field name="tab_strip_2" type="text" label ="Enter Strip Text" description="Enter Strip Text"/>
			<field type="radio" class="btn-group" name="short_desc_state_2" default="1" label="Show short description" description="Show short description">
					
			</field>			
			<field name="short_desc_2" type="text" default="" label="Enter Short Description" description="Enter ShortDescription" filter="raw" showon="short_desc_state_2:1" />			
			
			<field type="radio" class="btn-group" name="long_desc_state_2" default="1" label="Show Full description" description="Show Full description">
					
			</field>					
			<field name="long_desc_2" label ="Enter Full Description" description="Enter Full Description" type="editor" width="300" filter="safehtml" />		
			<field name="tab_title_color_2" type="text" default="#FFFFFF" label="Tab Title Color" description="Enter Tab Title Color" />			
			<field name="tab_title_size_2" type="text" default="17px" label="Tab Title Size(px)" description="Enter Tab Title Size" />
			<field name="tab_bgcolor_2" type="text" default="#1D9E74" label="Tab Background" description="Enter Tab Background Color" />
			<field name="tab_short_desc_color_2" type="text" default="#FFFFFF" label="Short Desc Color" description="Enter Short description Size" />
			<field name="tab_short_desc_size_2" type="text" default="14px" label="Short Desc Size(px)" description="Enter Short Description Size" />
			<field name="tab_full_desc_color_2" type="text" default="#c7c7c7" label="Full Desc Color" description="Enter Full Desc Color" />
			<field name="tab_full_desc_size_2" type="text" default="14px" label="Full Desc Size(px)" description="Enter Tab Content Size" />		
			<field name="tab_icon_color_2" type="text" default="#FFFFFF" label="Tab Icon Color" description="Enter Tab Icon Color" />
			<field name="tab_icon_size_2" type="text" default="3.4em" label="Tab Icon Size(px)" description="Enter Tab Icon Size" />
			
		</fieldset>

		
			<fieldset name="tab3" label="TAB 3">

			
			
			<field type="radio" class="btn-group" name="tab_state_3" default="0" label="Show Tab" description="Show Tab">
					
			</field>
			
			<field type="spacer" name="spacer_tab_3" label="&lt;h3&gt; Accordion Tab 3 Parameters &lt;/h3&gt;&lt;hr/&gt;" />
			
			<field name="tab_title_3" type="text" default="" label="Title" description="Enter Tab title" />
			
			<field type="radio" class="btn-group" name="title_state_3" default="1" label="Show Title" description="Show Title">
					
			</field>
			
			<field type="radio" class="btn-group" name="tab_number_3" default="1" label="Show Tab Number" description="Show Tab Number">
					
			</field>
			
			<field type="radio" class="btn-group" name="tab_icon_state_3" default="1" label="Show Icon" description="Show Icon">
					
			</field>
			<field type="radio" class="btn-group" name="tab_strip_state_3" default="1" label="Show Strip" description="Show Strip">
				
			</field>
			<field name="tab_strip_3" type="text" label ="Enter Strip Text" description="Enter Strip Text"/>
			<field name="tab_icon_3" type="text" default="" label="Tab Icon Class &lt;br/&gt; (&lt;a href='http://fortawesome.github.io/Font-Awesome/icons/' target='_blank'&gt;Use FontAwesome Icon&lt;/a&gt;)" description="Enter FontAwesome icon Class" filter="raw" showon="tab_icon_state_3:1" />
			
			<field type="radio" class="btn-group" name="short_desc_state_3" default="1" label="Show short description" description="Show short description">
				
			</field>			
			<field name="short_desc_3" type="text" default="" label="Enter Short Description" description="Enter ShortDescription" filter="raw" showon="short_desc_state_3:1" />			
			
			<field type="radio" class="btn-group" name="long_desc_state_3" default="1" label="Show Full description" description="Show Full description">
				
			</field>					
			<field name="long_desc_3" label ="Enter Full Description" description="Enter Full Description" type="editor" width="300" filter="safehtml" />
			<field name="tab_title_color_3" type="text" default="#FFFFFF" label="Tab Title Color" description="Enter Tab Title Color" />
			<field name="tab_title_size_3" type="text" default="17px" label="Tab Title Size(px)" description="Enter Tab Title Size" />
			<field name="tab_bgcolor_3" type="text" default="#3D85C6" label="Tab Background" description="Enter Tab Background Color" />
			<field name="tab_short_desc_color_3" type="text" default="#FFFFFF" label="Short Desc Color" description="Enter Short description Size" />
			<field name="tab_short_desc_size_3" type="text" default="14px" label="Short Desc Size(px)" description="Enter Short Description Size" />
			<field name="tab_full_desc_color_3" type="text" default="#c7c7c7" label="Full Desc Color" description="Enter Full Desc Color" />
			<field name="tab_full_desc_size_3" type="text" default="14px" label="Full Desc Size(px)" description="Enter Tab Content Size" />
			<field name="tab_icon_color_3" type="text" default="#FFFFFF" label="Tab Icon Color" description="Enter Tab Icon Color" />
			<field name="tab_icon_size_3" type="text" default="3.4em" label="Tab Icon Size(px)" description="Enter Tab Icon Size" />
			
		</fieldset>
		
				<fieldset name="tab4" label="TAB 4">

			
			
			<field type="radio" class="btn-group" name="tab_state_4" default="0" label="Show Tab" description="Show Tab">
					
			</field>
			
			<field type="spacer" name="spacer_tab_4" label="&lt;h3&gt; Accordion Tab 4 Parameters &lt;/h3&gt;&lt;hr/&gt;" />
			
			<field name="tab_title_4" type="text" default="" label="Title" description="Enter Tab title" />
			
			<field type="radio" class="btn-group" name="title_state_4" default="1" label="Show Title" description="Show Title">
					
			</field>
			
			<field type="radio" class="btn-group" name="tab_number_4" default="1" label="Show Tab Number" description="Show Tab Number">
					
			</field>
			
			<field type="radio" class="btn-group" name="tab_icon_state_4" default="1" label="Show Icon" description="Show Icon">
					
			</field>
			<field type="radio" class="btn-group" name="tab_strip_state_4" default="1" label="Show Strip" description="Show Strip">
				
			</field>
			<field name="tab_strip_4" type="text" label ="Enter Strip Text" description="Enter Strip Text"/>
			<field name="tab_icon_4" type="text" default="" label="Tab Icon Class &lt;br/&gt; (&lt;a href='http://fortawesome.github.io/Font-Awesome/icons/' target='_blank'&gt;Use FontAwesome Icon&lt;/a&gt;)" description="Enter FontAwesome icon Class" filter="raw" showon="tab_icon_state_4:1" />
			
			<field type="radio" class="btn-group" name="short_desc_state_4" default="1" label="Show short description" description="Show short description">
					
			</field>			
			<field name="short_desc_4" type="text" default="" label="Enter Short Description" description="Enter ShortDescription" filter="raw" showon="short_desc_state_4:1" />			
			
			<field type="radio" class="btn-group" name="long_desc_state_4" default="1" label="Show Full description" description="Show Full description">
					
			</field>					
				<field name="long_desc_4" label ="Enter Full Description" description="Enter Full Description" type="editor" width="300" filter="safehtml" />
			<field name="tab_title_color_4" type="text" default="#FFFFFF" label="Tab Title Color" description="Enter Tab Title Color" />
			<field name="tab_title_size_4" type="text" default="17px" label="Tab Title Size(px)" description="Enter Tab Title Size" />
			<field name="tab_bgcolor_4" type="text" default="#FFC0CB" label="Tab Background" description="Enter Tab Background Color" />
			<field name="tab_short_desc_color_4" type="text" default="#FFFFFF" label="Short Desc Color" description="Enter Short description Size" />
			<field name="tab_short_desc_size_4" type="text" default="14px" label="Short Desc Size(px)" description="Enter Short Description Size" />
			<field name="tab_full_desc_color_4" type="text" default="#c7c7c7" label="Full Desc Color" description="Enter Full Description Color" />
			<field name="tab_full_desc_size_4" type="text" default="14px" label="Full Desc Size(px)" description="Enter Full Description Size" />
			<field name="tab_icon_color_4" type="text" default="#FFFFFF" label="Tab Icon Color" description="Enter Tab Icon Color" />
			<field name="tab_icon_size_4" type="text" default="3.4em" label="Tab Icon Size(px)" description="Enter Tab Icon Size" />	
			
		</fieldset>
		
			<fieldset name="tab5" label="TAB 5">

			
			
			<field type="radio" class="btn-group" name="tab_state_5" default="0" label="Show Tab" description="Show Tab">
					
			</field>
			
			<field type="spacer" name="spacer_tab_5" label="&lt;h3&gt; Accordion Tab 5 Parameters &lt;/h3&gt;&lt;hr/&gt;" />
			
			<field name="tab_title_5" type="text" default="" label="Title" description="Enter Tab title" />
			
			<field type="radio" class="btn-group" name="title_state_5" default="1" label="Show Title" description="Show Title">
					
			</field>
			
			<field type="radio" class="btn-group" name="tab_number_5" default="1" label="Show Tab Number" description="Show Tab Number">
					
			</field>
			
			<field type="radio" class="btn-group" name="tab_icon_state_5" default="1" label="Show Icon" description="Show Icon">
					
			</field>
			<field type="radio" class="btn-group" name="tab_strip_state_5" default="1" label="Show Strip" description="Show Strip">
				
			</field>
			<field name="tab_strip_5" type="text" label ="Enter Strip Text" description="Enter Strip Text"/>
			<field name="tab_icon_5" type="text" default="" label="Tab Icon Class &lt;br/&gt; (&lt;a href='http://fortawesome.github.io/Font-Awesome/icons/' target='_blank'&gt;Use FontAwesome Icon&lt;/a&gt;)" description="Enter FontAwesome icon Class" filter="raw" showon="tab_icon_state_5:1" />
			
			<field type="radio" class="btn-group" name="short_desc_state_5" default="1" label="Show short description" description="Show short description">
				
			</field>			
			<field name="short_desc_5" type="text" default="" label="Enter Short Description" description="Enter ShortDescription" filter="raw" showon="short_desc_state_5:1" />			
			
			<field type="radio" class="btn-group" name="long_desc_state_5" default="1" label="Show Full description" description="Show Full description">
					
			</field>					
			<field name="long_desc_5" label ="Enter Full Description" description="Enter Full Description" type="editor" width="300" filter="safehtml" />	
			<field name="tab_title_color_5" type="text" default="#FFFFFF" label="Tab Title Color" description="Enter Tab Title Color" />
			<field name="tab_title_size_5" type="text" default="17px" label="Tab Title Size(px)" description="Enter Tab Title Size" />
			<field name="tab_bgcolor_5" type="text" default="#B90000" label="Tab Background" description="Enter Tab Background Color" />
			<field name="tab_short_desc_color_5" type="text" default="#FFFFFF" label="Short Desc Color" description="Enter Short description Size" />
			<field name="tab_short_desc_size_5" type="text" default="14px" label="Short Desc Size(px)" description="Enter Short Description Size" />
			<field name="tab_full_desc_color_5" type="text" default="#c7c7c7" label="Full Desc Color" description="Enter Full Desc Color" />
			<field name="tab_full_desc_size_5" type="text" default="14px" label="Full Desc Size(px)" description="Enter Tab Content Size" />
			<field name="tab_icon_color_5" type="text" default="#FFFFFF" label="Tab Icon Color" description="Enter Tab Icon Color" />
			<field name="tab_icon_size_5" type="text" default="3.4em" label="Tab Icon Size(px)" description="Enter Tab Icon Size" />	
			
		</fieldset>
			
			
			
			<fieldset name="advanced" >
				<field name="layout" type="modulelayout" label="JFIELD_ALT_LAYOUT_LABEL" description="JFIELD_ALT_MODULE_LAYOUT_DESC" />
				<field name="moduleclass_sfx" type="textarea" rows="3" label="COM_MODULES_FIELD_MODULECLASS_SFX_LABEL" description="COM_MODULES_FIELD_MODULECLASS_SFX_DESC" />
				<field name="cache" type="list" default="1" label="COM_MODULES_FIELD_CACHING_LABEL" description="COM_MODULES_FIELD_CACHING_DESC">
					<option value="1">JGLOBAL_USE_GLOBAL</option>
					<option value="0">COM_MODULES_FIELD_VALUE_NOCACHING</option>
				</field>
				<field name="cache_time" type="text" default="900" label="COM_MODULES_FIELD_CACHE_TIME_LABEL" description="COM_MODULES_FIELD_CACHE_TIME_DESC" />
				<field name="cachemode" type="hidden" default="itemid">
					<option value="itemid"></option>
				</field>
			</fieldset>
			
			
			
		</fields>
	</config>
</extension><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>

**Comment by AteDev** [comment]
Well, i create a module to help test [see here](https://github.com/AteDev/joomla-modules-test/tree/IS-7116).
Then i tested and watched on database, all of those params are saved in an table column of type "text", so there is a limitation of 2,147,483,647 characters (not pretty sure maybe this depend of kind of db ?). Maybe you reached this limit ?

**Comment by dgt41** [comment]
@anamikakush your problem is that nothing gets saved or the editor fields are not saved?

**Comment by anamikakush** [comment]
@dgt41 Thanks for your reply, If we filled all the value except Editor then all value gets saved but if we fill the value with editor then nothing gets save. So in short if we filled all the field value then nothing gets save.

I would like to mentioned that i am adding long data in editor, Currently, i am using the data below for the all editor,

# Data Added in All 5 Editor----

We've built the world's largest local marketplace, with 53.2 million active customers, 200+ million global subscribers, 600+ million deals sold to date, nearly 92 million mobile downloads, and innovative, proprietary technology and tools. 

More than 650,000 merchants have already been featured in our marketplace—put our experience and scale to work for you!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>

**Comment by anamikakush** [comment]
AteDev@ Thanks for your reply, Can you lease let me know that what should i need to do if i need to save the below content for each editor:

# Data Added in All 5 Editor----

We've built the world's largest local marketplace, with 53.2 million active customers, 200+ million global subscribers, 600+ million deals sold to date, nearly 92 million mobile downloads, and innovative, proprietary technology and tools.

More than 650,000 merchants have already been featured in our marketplace—put our experience and scale to work for you!
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>

**Comment by anamikakush** [comment]
@AteDev

Thanks for your quick reply,
In case of limit issue the specific field value should not store.
But when I try to save the data with long description ,none of field value is stored. Each field get blank after save while it all work fine if I change the editor field type to textarea type.

Please advice ,I need to store the data in separate table or something else can work.

Thank you in advance.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>

**Comment by dgt41** [comment]
@anamikakush can you apply #5839 and try again?

**Comment by anamikakush** [comment]
@dgt41 Thanks for your suggestion.

We have checked and followed the instruction but issue still doesn't get fixed. Still all the field are getting clear. 

When we save field tab value 1 by 1 editor then it works properly but we need to do same process by 5 times to store 5 editor field value. i.e we have created 5 tabs in one module and each tab have 1 editor and when we save 1 by 1 value then it works properly but when we fill all tabs editor value and try to save in once it is not working. Please advise.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>

**Comment by dgt41** [comment]
@anamikakush what is the mysql filed for <field type="editor" name="long_desc_1" label="Enter Full Description" description="Enter Full Description" width="300" filter="safehtml" />

If that is VARCHAR can you change it to TEXT or MEDIUMTEXT or LONGTEXT (you have to decide upon the data you are trying to store) for all the editor fields and report back?

**Comment by anamikakush** [comment]
@dgt41 Thanks for quick reply,

i have stored all editor field data in module params, and i have checked in database the type of params in module table is text.Please advice.

Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>

**Comment by dgt41** [comment]
@anamikakush  can you change it to LONGTEXT and report back?

**Comment by anamikakush** [comment]
@dgt41 Thanks for your response.

I have changed it to LONGTEXT and after filling all the fields details when i click on Save button then i got the below error:

1118 Row size too large (> 8126). Changing some columns to TEXT or BLOB or using ROW_FORMAT=DYNAMIC or ROW_FORMAT=COMPRESSED may help

Please help me to resolve this issue soon.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>

**Comment by anamikakush** [comment]
@dgt41 We are just entering about 10,000 characters in all the 5 editor field, I have changed it in LONGTEXT and SEMI TEXT as well but still not saving the value.

Please advise.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>

**Comment by anamikakush** [comment]
@dgt41 If you want then i can share you the website details where you can see that module and provide us the solution. Please provide me your email address where i can mail you admin details.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>

**Comment by brianteeman** [comment]
I have tested the module that you supplied with the latest joomla staging  and it works perfectly with the data that you said to enter in all 5 tabs

One possibility is to check your server error logs for any error referring to max_input_vars

This is not an issue with the core of Joomla<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7116">issues.joomla.org/joomla-cms/7116</a>.</sub>
