### ISSUE TITLE
Media manager performance suffers heavily when having lots of big files

### ISSUE THREAD

**Issue by irbian** [joomla/joomla-cms#7118]
I´m experiencing heavy performance hit when having lots of big files. My current case is 168 elements with 300kb size and 7000x4000 resolution. I know that this is not normal, but is the result of a pdf export and I´m still medling with the parameters.

I´m guessing that a simple approach would be deleting/allowing to disable the preview on the detail mode on the com_media. I guess that triying to load that many pictures is not being easy.

**Comment by brianteeman** [comment]
With the current media manager there really isnt anything that can be done and a new media manager is coming (hopefully in J3.5 or 3.6)

As a temporary measure I would recommend using JCE and its own media manager which will use thumbnail images AND has the option to disable the images

**Comment by zero-24** [comment]
As comment by @brianteeman i'm going to close this for now as `Known Issue` that hopfully can be fixed if we have the new media manager there :smile: 

`300kb size and 7000x4000 resolution`

It is just not only hard to load this to the backend (com_media) but also in the frontend specially on mobile devices.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7118">issues.joomla.org/joomla-cms/7118</a>.</sub>

**Comment by irbian** [comment]
just for the record, I´m doing lazy load, but I agree that it needs to be trimmed ^^U
