### ISSUE TITLE
1062 database error when upgrading from 2.5.28 to 3.4.1

### ISSUE THREAD

**Issue by superfoght** [joomla/joomla-cms#7120]
I struggled a lot with upgrading a Joomla 2.5.28 installation from 2.5.28 to 3.4.1
I have added the error I got, when I updated through the Joomla updater, in a txt file.
After updating and receiving the error, you can still navigate back to the Joomla control panel, but when you try to access different areas such as article, extensions etc. you receive errors such as

Fatal error: Call to a member function get() on a non-object in home\site-name\administrator\components\com_content\controllers\article.php on line 34

Fatal error: Call to a member function get() on a non-object in home\sitename\administrator\components\com_installer\controller.php on line 37

I am not really sure what causes this error. But I'm more than willing to share my Akeeba Backup file, if anyone wants my test data. It's the first time I've had this much trouble updating a Joomla site, but one of my own colleagues had the same issue and gave me the following advice, which I have pasted below:

What I did to actually get the site up and running was the following
Step 1 : Disabled the "Remember me" plugin before migrating

Step2 : Download the update package from here: http://www.joomla.org/announcements/release-news/5468-joomla-3-0-1-released.html The one that say (for updates from Joomla 2.5)

Step3: Install the package through the Joomla installer

After that I could continue updating Joomla through the Joomla updater

EDIT.. the tracker did not allow me to upload the txt file. Here is the full text:
1062 - An error has occurred.

Duplicate entry '1' for key 'PRIMARY' SQL=-- -- Dumping data for table `j25_content_types` -- INSERT INTO `j25_content_types` (`type_id`, `type_title`, `type_alias`, `table`, `rules`, 

`field_mappings`,`router`) VALUES (1, 'Article', 'com_content.article', '{"special":{"dbtable":"#__content","key":"id","type":"Content","prefix":"JTable","config":"array()"},"common":

{"dbtable":"#__core_content","key":"ucm_id","type":"Corecontent","prefix":"JTable","config":"array()"}}', '', '{"common":

[{"core_content_item_id":"id","core_title":"title","core_state":"state","core_alias":"alias","core_created_time":"created","core_modified_time":"modified","core_body":"introtext", 

"core_hits":"hits","core_publish_up":"publish_up","core_publish_down":"publish_down","core_access":"access", "core_params":"attribs", "core_featured":"featured", 

"core_metadata":"metadata", "core_language":"language", "core_images":"images", "core_urls":"urls", "core_version":"version", "core_ordering":"ordering", "core_metakey":"metakey", 

"core_metadesc":"metadesc", "core_catid":"catid", "core_xreference":"xreference", "asset_id":"asset_id"}], "special": [{"fulltext":"fulltext"}]}','ContentHelperRoute::getArticleRoute'), 

(2, 'Contact', 'com_contact.contact', '{"special":{"dbtable":"#__contact_details","key":"id","type":"Contact","prefix":"ContactTable","config":"array()"},"common":

{"dbtable":"#__core_content","key":"ucm_id","type":"Corecontent","prefix":"JTable","config":"array()"}}', '', '{"common":

[{"core_content_item_id":"id","core_title":"name","core_state":"published","core_alias":"alias","core_created_time":"created","core_modified_time":"modified","core_body":"address", 

"core_hits":"hits","core_publish_up":"publish_up","core_publish_down":"publish_down","core_access":"access", "core_params":"params", "core_featured":"featured", 

"core_metadata":"metadata", "core_language":"language", "core_images":"image", "core_urls":"webpage", "core_version":"version", "core_ordering":"ordering", "core_metakey":"metakey", 

"core_metadesc":"metadesc", "core_catid":"catid", "core_xreference":"xreference", "asset_id":"null"}], "special": 

[{"con_position":"con_position","suburb":"suburb","state":"state","country":"country","postcode":"postcode","telephone":"telephone","fax":"fax","misc":"misc","email_to":"email_to","defau

lt_con":"default_con","user_id":"user_id","mobile":"mobile","sortname1":"sortname1","sortname2":"sortname2","sortname3":"sortname3"}]}','ContactHelperRoute::getContactRoute'), (3, 

'Newsfeed', 'com_newsfeeds.newsfeed', '{"special":{"dbtable":"#__newsfeeds","key":"id","type":"Newsfeed","prefix":"NewsfeedsTable","config":"array()"},"common":

{"dbtable":"#__core_content","key":"ucm_id","type":"Corecontent","prefix":"JTable","config":"array()"}}', '', '{"common":

[{"core_content_item_id":"id","core_title":"name","core_state":"published","core_alias":"alias","core_created_time":"created","core_modified_time":"modified","core_body":"description", 

"core_hits":"hits","core_publish_up":"publish_up","core_publish_down":"publish_down","core_access":"access", "core_params":"params", "core_featured":"featured", 

"core_metadata":"metadata", "core_language":"language", "core_images":"images", "core_urls":"link", "core_version":"version", "core_ordering":"ordering", "core_metakey":"metakey", 

"core_metadesc":"metadesc", "core_catid":"catid", "core_xreference":"xreference", "asset_id":"null"}], "special": 

[{"numarticles":"numarticles","cache_time":"cache_time","rtl":"rtl"}]}','NewsfeedsHelperRoute::getNewsfeedRoute'), (4, 'User', 'com_users.user', '{"special":

{"dbtable":"#__users","key":"id","type":"User","prefix":"JTable","config":"array()"},"common":

{"dbtable":"#__core_content","key":"ucm_id","type":"Corecontent","prefix":"JTable","config":"array()"}}', '', '{"common":

[{"core_content_item_id":"id","core_title":"name","core_state":"null","core_alias":"username","core_created_time":"registerdate","core_modified_time":"lastvisitDate","core_body":"null", 

"core_hits":"null","core_publish_up":"null","core_publish_down":"null","access":"null", "core_params":"params", "core_featured":"null", "core_metadata":"null", "core_language":"null", 

"core_images":"null", "core_urls":"null", "core_version":"null", "core_ordering":"null", "core_metakey":"null", "core_metadesc":"null", "core_catid":"null", "core_xreference":"null", 

"asset_id":"null"}], "special": [{}]}','UsersHelperRoute::getUserRoute'), (5, 'Article Category', 'com_content.category', '{"special":

{"dbtable":"#__categories","key":"id","type":"Category","prefix":"JTable","config":"array()"},"common":

{"dbtable":"#__core_content","key":"ucm_id","type":"Corecontent","prefix":"JTable","config":"array()"}}', '', '{"common":

[{"core_content_item_id":"id","core_title":"title","core_state":"published","core_alias":"alias","core_created_time":"created_time","core_modified_time":"modified_time","core_body":"desc

ription", "core_hits":"hits","core_publish_up":"null","core_publish_down":"null","core_access":"access", "core_params":"params", "core_featured":"null", "core_metadata":"metadata", 

"core_language":"language", "core_images":"null", "core_urls":"null", "core_version":"version", "core_ordering":"null", "core_metakey":"metakey", "core_metadesc":"metadesc", 

"core_catid":"parent_id", "core_xreference":"null", "asset_id":"asset_id"}], "special": 

[{"parent_id":"parent_id","lft":"lft","rgt":"rgt","level":"level","path":"path","extension":"extension","note":"note"}]}','ContentHelperRoute::getCategoryRoute'), (6, 'Contact Category', 

'com_contact.category', '{"special":{"dbtable":"#__categories","key":"id","type":"Category","prefix":"JTable","config":"array()"},"common":

{"dbtable":"#__core_content","key":"ucm_id","type":"Corecontent","prefix":"JTable","config":"array()"}}', '', '{"common":

[{"core_content_item_id":"id","core_title":"title","core_state":"published","core_alias":"alias","core_created_time":"created_time","core_modified_time":"modified_time","core_body":"desc

ription", "core_hits":"hits","core_publish_up":"null","core_publish_down":"null","core_access":"access", "core_params":"params", "core_featured":"null", "core_metadata":"metadata", 

"core_language":"language", "core_images":"null", "core_urls":"null", "core_version":"version", "core_ordering":"null", "core_metakey":"metakey", "core_metadesc":"metadesc", 

"core_catid":"parent_id", "core_xreference":"null", "asset_id":"asset_id"}], "special": 

[{"parent_id":"parent_id","lft":"lft","rgt":"rgt","level":"level","path":"path","extension":"extension","note":"note"}]}','ContactHelperRoute::getCategoryRoute'), (7, 'Newsfeeds 

Category', 'com_newsfeeds.category', '{"special":{"dbtable":"#__categories","key":"id","type":"Category","prefix":"JTable","config":"array()"},"common":

{"dbtable":"#__core_content","key":"ucm_id","type":"Corecontent","prefix":"JTable","config":"array()"}}', '', '{"common":

[{"core_content_item_id":"id","core_title":"title","core_state":"published","core_alias":"alias","core_created_time":"created_time","core_modified_time":"modified_time","core_body":"desc

ription", "core_hits":"hits","core_publish_up":"null","core_publish_down":"null","core_access":"access", "core_params":"params", "core_featured":"null", "core_metadata":"metadata", 

"core_language":"language", "core_images":"null", "core_urls":"null", "core_version":"version", "core_ordering":"null", "core_metakey":"metakey", "core_metadesc":"metadesc", 

"core_catid":"parent_id", "core_xreference":"null", "asset_id":"asset_id"}], "special": 

[{"parent_id":"parent_id","lft":"lft","rgt":"rgt","level":"level","path":"path","extension":"extension","note":"note"}]}','NewsfeedsHelperRoute::getCategoryRoute'), (8, 'Tag', 

'com_tags.tag', '{"special":{"dbtable":"#__tags","key":"tag_id","type":"Tag","prefix":"TagsTable","config":"array()"},"common":

{"dbtable":"#__core_content","key":"ucm_id","type":"Corecontent","prefix":"JTable","config":"array()"}}', '', '{"common":

[{"core_content_item_id":"id","core_title":"title","core_state":"published","core_alias":"alias","core_created_time":"created_time","core_modified_time":"modified_time","core_body":"desc

ription", "core_hits":"hits","core_publish_up":"null","core_publish_down":"null","core_access":"access", "core_params":"params", "core_featured":"featured", "core_metadata":"metadata", 

"core_language":"language", "core_images":"images", "core_urls":"urls", "core_version":"version", "core_ordering":"null", "core_metakey":"metakey", "core_metadesc":"metadesc", 

"core_catid":"null", "core_xreference":"null", "asset_id":"null"}], "special": 

[{"parent_id":"parent_id","lft":"lft","rgt":"rgt","level":"level","path":"path"}]}','TagsHelperRoute::getTagRoute');

**Comment by Hutchy68** [comment]
Did you follow these instructions?

https://docs.joomla.org/Joomla_2.5_to_3.x_Step_by_Step_Migration<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7120">issues.joomla.org/joomla-cms/7120</a>.</sub>

**Comment by superfoght** [comment]
I just took a brief glance at the guide, and I believe I did all those steps, yes. I have upgraded quite a few sites and never had this happen to me. Maybe I was just lucky :smile: But I will try and restore the 2.5 version of site and run through that guide and report back what happens.. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7120">issues.joomla.org/joomla-cms/7120</a>.</sub>

**Comment by Hutchy68** [comment]
Also, was that site originally a 1.5 migrated to 2.5. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7120">issues.joomla.org/joomla-cms/7120</a>.</sub>

**Comment by superfoght** [comment]
Yes, I believe it was.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7120">issues.joomla.org/joomla-cms/7120</a>.</sub>

**Comment by superfoght** [comment]
Here is a video showing how I tried to upgrade it: http://screencast.com/t/GYbnZBx7B 

During the video I'm upgrading two components I know are outdated SH404SEF and redFORM to make sure they are not the cause of the harm :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7120">issues.joomla.org/joomla-cms/7120</a>.</sub>

**Comment by AteDev** [comment]
Did you already seen that: http://stackoverflow.com/questions/20738790/migrate-from-joomla-2-5-17-to-joomla-3-2-1-failed#answer-27715423

Seem your update has failed and stuck.

*I just want to point out the fatal error occured is on JInput, who was not instanciate in old JApplication.*

**Comment by bayareajenn** [comment]
I believe you still have incompatible extensions installed on the site. In your video I saw you go through packages and components and languages but not all the rest of the extensions.

Every single extension needs to be checked and either updated or uninstalled before updating from 2.5 to 3. I am unsure of the migration path for redform or sh404sef but you have to check with them to make sure that their package includes version for both before you update. Same with all the rest of your extensions including the template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7120">issues.joomla.org/joomla-cms/7120</a>.</sub>

**Comment by superfoght** [comment]
Thanks for the suggestions.

I restored the site, removed all third-party extensions and then tried to upgrade. Same issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7120">issues.joomla.org/joomla-cms/7120</a>.</sub>

**Comment by zero-24** [comment]
@superfoght Can you show us the entrys in `j25_content_types` bevor the update?

```sql
select * from j25_content_types;
```

If you have entrys please try:
- download last 3.4.1 update package: https://github.com/joomla/joomla-cms/releases/download/3.4.1/Joomla_3.4.1-Stable-Update_Package.zip
- go to: /administrator/components/com_admin/sql/updates/mysql/3.1.0.sql
- and replace that file with this here: https://github.com/zero-24/joomla-cms/blob/contentype_fix/administrator/components/com_admin/sql/updates/mysql/3.1.0.sql (diff: https://github.com/zero-24/joomla-cms/commit/020866170b9c4623a596c29559128fe55d8d57b0)
- pack it as update package
- try to install it as "normal" extension
- report the result back.

**Comment by brianteeman** [comment]
After over one month without further reply to the request for further information this issue is being closed. It can always be re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7120">issues.joomla.org/joomla-cms/7120</a>.</sub>

**Comment by stAn47** [comment]
i got the same problem, and it's caused by incomplete DB update. now the question is how can i update the database to joomla 3.5.1 schema when com_installer is not available... 

this is how i attempted the migration: 
- i disabled all plugins of all types except authentication - joomla + user - joomla
- i updated everything that was availble
- i disabled caching + cleared cache
- i must had adjusted server permisions so that file outside /administrator/index.php is accessible (/administrator/components/com_joomlaupdate/restore.php) --> i hope that this won't be needed when upgrading from joomla 3 to joomla 4 
- my original database on joomla 2.5 was all migrated to InnoDB engine which is highly optimized and prefered agains myisam on our production servers, the site had been migrated from joomla 1.5 before... 
- upon the upgrade, there is a javascript error in update.js "msg is undefined" (joomla 2.5.28), so to find out that i am getting 403 upon joomla update, i had to debug the update.js script in com_joomlaupdate
- after all i uploaded all joomla 3.5.1 files via ftp 

during the upgrade, i got the error which had caused all of the headache: 

Duplicate entry '801' for key 'PRIMARY' SQL=INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`) VALUES (801, 'weblinks', 'package', 'pkg_weblinks', '', 0, 1, 1, 0, '', '', '', '', 0, '0000-00-00 00:00:00', 0, 0);

i guess this was caused by not using locking on the table while the table is on innodb and too many writes at once can lead to index collisions, since it's not clear if the writes are in synchronious or asynchronious mode. (i had the same problem with JTableNested that was doing writes in a loop with thousands of entries - it always ran into an index collision)

now the question is - how to update the database schema when i cannot access any component in joomla except com_menus: 

Fatal error: Call to a member function get() on null in /administrator/components/com_installer/controller.php on line 37

same for others: 
Fatal error: Call to a member function get() on null in /municak.sk/demo/administrator/components/com_users/controller.php on line 60


thanks for any advice, 
best regards, stan

**Comment by stAn47** [comment]
ok, so this is how i fixed this: 

1. to be able to get into Database fixing part, i had to add
$this->input = JFactory::getApplication()->input;
into
\administrator\components\com_installer\controller.php
and
\administrator\components\com_login\controller.php

then the DB fix still could not run and i had to manually add a column which was required by the DB structure and it was dropped later on: 

ALTER TABLE `udx46_content` ADD COLUMN `title_alias`  VARCHAR( 255 ) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL DEFAULT ''

in mean time i created a file that updates all tables per SQL files in \administrator\components\com_admin\sql\updates\mysql\

https://github.com/stAn47/Joomla-3-Manual-Database-Update

Now i was able to visit the DB fix and run it without problems. Now the installation seems to be okay. 

best regards, stan
