### ISSUE TITLE
Joomla not installing in localhost

### ISSUE THREAD

**Issue by alisiddique** [joomla/joomla-cms#7121]
Stuck in here for few hours.

**Comment by alisiddique** [comment]
![screen shot 2015-06-04 at 07 13 56](http://issues.joomla.org/uploads/1/f72b6ebd9d23aa18717b5d9d3325a1db.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7121">issues.joomla.org/joomla-cms/7121</a>.</sub>

**Comment by Bakual** [comment]
Try raising the max_execution_time in the php.ini of your XAMPP installation. Your installation just timed out.
It's a known issue with that particular software that for some reason it's very slow when it applies the installation SQL files.
