### ISSUE TITLE
Email Cloaking fails on span with style in mailto link

### ISSUE THREAD

**Issue by AndrisZemitis** [joomla/joomla-cms#7123]
#### Steps to reproduce the issue
Create an article and insert this:
\<p>\<a href="mailto:some@email.com"\>\<span style="some: weird;"\>email: some@email.com\</span>\</a>\</p>

#### Expected result

email: some@email.com

#### Actual result
This email address is being protected from spambots. You need JavaScript enabled to view it.'; document.getElementById('cloak33437').innerHTML += ''+addy_text33437+'<\/a>'; //-->

#### System information (as much as possible)
Joomla 3.4.1 without any additional plugins, modules or components.

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7123">issues.joomla.org/joomla-cms/7123</a>.</sub>

**Comment by infograf768** [comment]
The issue does not come from the span and style (we do take care of this when we have a pure text or pure email address in the span) but from the word "email:" in "email: some@email.com".
I.e. we do not provide for text AND address together.

For example:
`<p><a href="mailto:joe@nowhere.com"><span style="font-style: 8pt;">Joe_fontsize8</span></a></p>`
or
`<p><a href="mailto:joe@nowhere16.com"><span style="font-size: 16pt;">joe@nowhere16.com</span></a></p>`
work perfectly.

You can solve your issue by using:
`<p><span style="some: weird;">email: </span><a href="mailto:some@email.com"><span style="some: weird;">some@email.com</span></a></p>`

**Comment by brianteeman** [comment]
Closed as expected behaviour as explained abpve<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7123">issues.joomla.org/joomla-cms/7123</a>.</sub>
