### ISSUE TITLE
Deleting contents associated to associations dont purge associations table

### ISSUE THREAD

**Issue by Devportobello** [joomla/joomla-cms#7127]
## Concept
When you use multilanguage site, you could use associations for menuitems, contents...

## Issue
When you setup associations between elements and then delete elements, associations table is not purged.
Dunno if this a real issue, but with many elements this table could be really filled. Moreover, this associations persist in table.

## Test
- Create 2 articles with 2 languages different.
- Associate them.
- In your database you will see 2 line in "#__associations" table, example:
```
id	context			key
1 	com_content.item 	9d603efd64821ea52e1c1921cee55305
2 	com_content.item 	9d603efd64821ea52e1c1921cee55305
```
- Remove 1 article.
- In your database, table "associations", same lines as before.

## Last
I know this could be fixed by a cron task script, but this is for developper, did we need to add something to handle that (plugin ?).

**Comment by infograf768** [comment]
I confirm the issue.
I am pretty sure it was working OK when we first implemented associations for menu items.

**Comment by brianteeman** [comment]
See #7583 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7127">issues.joomla.org/joomla-cms/7127</a>.</sub>
