### ISSUE TITLE
Smart Search module messed up when Parameters are on

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-cms#7132]
#### Steps to reproduce the issue
Just turn the search parameters on in smart search module, the layout is messed up and appears like in Attachment)
![screen shot 2015-06-06 at 03 41 33](http://issues.joomla.org/uploads/1/d5ffdb5c8126259680a8697d0c5666a1.png)

#### Expected result

Should look "more" like this
![screen shot 2015-06-06 at 03 41 51](http://issues.joomla.org/uploads/1/586f43d2a44ab29deaf53403bfc03a83.png)

#### System information (as much as possible)
Safari 8.0.5
Mac Os X 10.10.3

#### Additional comments
i could try to fix this, since it´s just a layout problem :)
Can someone confirm the bug?

**Comment by brianteeman** [comment]
Confirmed

**Comment by zero-24** [comment]
Closing as we have a PR by @designbengel here #7140 Thanks :+1:
