### ISSUE TITLE
Captcha 2.0: not working on Ie11 on registration view

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#7133]
On the registration, I can't get the captcha
on reset/remind, I get the captcha.

But when debugger on:
Line: 46
Error: Not a window
cb=gapi.loaded_0 (46,306)

**Comment by dBarboni** [comment]
This is happening on my site as well except I don't get the captcha on registration, reset, or remind. Refreshing the page or turning on 'Always refresh from server' in IE's dev tools and navigating to one of these pages gets the captcha to show.

**Comment by 810** [comment]
on the demo of captcha2 its always loaded, Only not on Joomla.

**Comment by dBarboni** [comment]
This is fixed in the 3.4.2 rc

**Comment by 810** [comment]
+1 on test  3.4.2 rc
