### ISSUE TITLE
Pagination in com_contact

### ISSUE THREAD

**Issue by ksandven** [joomla/joomla-cms#7144]
#### Steps to reproduce the issue

Set up a menu item to show all contacts in a category.
There is no pagination. Have tried adjusting the settings in both menu item and the com_content config. No luck.
Pagination works in com_content. I have not used any filters in the backend for contacts (someone mentioned this was a known bug).

**Comment by brianteeman** [comment]
It does and it doesnt work

Pagination works if you set it to show in the options BUT there is no option to set how many contacts to show. It currently can only show the number of contacts based on the default list limit in the global configuration<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7144">issues.joomla.org/joomla-cms/7144</a>.</sub>

**Comment by ksandven** [comment]
Hi Brian. No, it doesn't work at all for me. I have tested different settings in the global config. No matter how many I set, there is no pagination. I have tried setting it to Auto or Show in the Contacts global config and in the menu item. Same results.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7144">issues.joomla.org/joomla-cms/7144</a>.</sub>

**Comment by brianteeman** [comment]
Not sure what to say but it worked for me. I will post some screenshots
when I get home

**Comment by brianteeman** [comment]
Confirmed by @ksandven that he had an issue with a template override.

**Comment by Bakual** [comment]
Closing as it was a faulty template override.
