### ISSUE TITLE
[REGRESSION] - Bug in categories association

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#7151]
#### Steps to reproduce the issue

- have a multilingual site with three languages (en-gb, it-it, fr-fr)
- create three categories and assign each to one of the three languages
- (optional, I guess...) Have three articles, one for each language, assigned to the corresponding category and associated between themselves
- Try to set-up association between the three categories by editing one of the categories and associating it to the two remaining ones

#### Expected result
- The language assigned to the category you're editing shuld not be displayed under "Associations"
- You should be able to set-up associations

#### Actual result
- Also the language assigned to the category you're editing is displayed under "Associations"
- If you anyway try to set-up associations (for the remaining languages) the language for the currently edited category is **reset to "All"** and the following error message is displayed:
~~~
Notice
A category item set to All languages can't be associated. Associations have not been set.
~~~

**Comment by smz** [comment]
There is a **strong** indication that this is due to #6973 (which, BTW I cannot find in http://issues.joomla.org/ but only here in GitHub.  Strange...)

**Comment by brianteeman** [comment]
http://issues.joomla.org/tracker/joomla-cms/6973

On 11 June 2015 at 15:18, Sergio Manzi <notifications@github.com> wrote:

> There is a *strong* indication that this is due to #6973
> <https://github.com/joomla/joomla-cms/pull/6973> (which, BTW I cannot
> find in http://issues.joomla.org/ but only here in GitHub. Strange...)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7151#issuecomment-111151917>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by smz** [comment]
Thanks! Have you tried **searching** this by ID in http://issues.joomla.org/? Either I'm doing something wrong or...

**Comment by mbabker** [comment]
Filter on closed items and type "6973" in the search input.  That worked for me.

**Comment by zero-24** [comment]
>Thanks! Have you tried searching this by ID in http://issues.joomla.org/? Either I'm doing something wrong or...

OT: As it is merged/closed you need to seach for closed and not for open :smile:

**Comment by smz** [comment]
O.T.: Yes, I searched for "Closed": Problem was I was searching for "#6973" and not "6973"... My bad, but maybe we can strip the hash character if it is in first position...

**Comment by smz** [comment]
In any case, yes, **this is due** to #6973 
Original coder @pe7er may probably find out the reason quicker than I can...

**Comment by infograf768** [comment]
Found out, making PR now.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/7160

**Comment by Bakual** [comment]
Cosing as we have a PR
