### ISSUE TITLE
Uncessary  Tag for index.html in install.xml

### ISSUE THREAD

**Issue by imanickam** [joomla/joomla-cms#7155]
#### System information (as much as possible)
Joomla! 3.4.2

#### Additional comments

In Joomla, the file index.html is no longer used in the directories.

However, in the file install.xml the following line of code is there.
< filename>index.html</ filename>

The file install.xml is available in both the directories \administrator\language\en-GB and \language\en-GB.

Since en-GB is native to Joomla and not getting installed just like any other language pack, the issue is not seen. If someone copies thse file to create a language pack, the language pack installation will fail as there would not be any file named index.html.

Action to be taken:
Please remove the above mentioned tag from the install.xml files that are available in the directories mentioned.

**Comment by brianteeman** [comment]
Closed see #7157<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7155">issues.joomla.org/joomla-cms/7155</a>.</sub>
