### ISSUE TITLE
inadequate filtering of user-name during installation process

### ISSUE THREAD

**Issue by FrankyDE** [joomla/joomla-cms#7158]
#### Steps to reproduce the issue

Install Joomla! and use in the user-name a "forbidden character like:
< > \ " ' % ; ( ) &

In my case the credentials where:
Admin-User:	S9nFA7N7x7tL}jXOJqIx&vQk3jSF
JAdmin-Pass:	msevXL0Stl,BV7szpufhMwo10^IV8SRs

In the installation process this user/password combination was accepted, installation went fine, but one could not log-in any more. 

After I changed the username in the Database login was possible again.

#### Expected result

I would expect that during installation there would be a warning, that prevented me from choosing an username that renders the Superadministrator Login useless. Like the one that is used if one registers a new user in the backend.

#### Actual result

Installation with unusable username is possible. Therefore creating a not usable SuperAdmin account on installation

#### System information (as much as possible)

PHP Built On: Linux server11729.yco.de 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u1 x86_64
Database Version: 5.5.42-MariaDB-1~wheezy-log
Database Collation: utf8_general_ci
PHP Version: 5.4.39-0+deb7u2
Web Server: Apache
WebServer to PHP Interface: cgi-fcgi
Joomla! Version: Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:38.0) Gecko/20100101 Firefox/38.0

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7158">issues.joomla.org/joomla-cms/7158</a>.</sub>

**Comment by nn-medienagentur** [comment]
https://github.com/joomla/joomla-cms/blob/staging/installation/model/setup.php#L420 

$data['admin_user'] will be not validate!

https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/table/user.php#L190-L195
This is a check from com_users

**Comment by mbabker** [comment]
It has nothing to do with the JForm validation (which is what the first link points to).  The install app doesn't use the JTable classes to insert data, so the check in JTableUser will never be reached.

At a quick glance, enough of the app might be in place to be able to use JTable to insert the super user (and inherently run its validations), but it may also still be a long shot.

**Comment by Achal-Aggarwal** [comment]
How about using a validation rule to check/validate username on one or more than one criteria? It'll be simple and clean.

**Comment by framontb** [comment]
I did a rule that apply to the admin_user field of the installation form. Please, see above.

**Comment by dgt41** [comment]
I think that the javascript validation will be a better bet here, so adding one more handler for admin-user similar to the one in validation.js:
```Javascript
 	 	setHandler('username', function(value, element) {
 	 	 	var regex = new RegExp("[\<|\>|\"|\'|\%|\;|\(|\)|\&]", "i");
 	 	 	return !regex.test(value);
 	 	});
```

**Comment by framontb** [comment]
Could you add logic in the javascript function to inform the user about what were the bad characters?

**Comment by dgt41** [comment]
Please test: #10391

**Comment by dgt41** [comment]
The characters are automagically removed in real time

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7158">issues.joomla.org/joomla-cms/7158</a>

**Comment by zero-24** [comment]
Closing as we have a PR by @dgt41 here: https://github.com/joomla/joomla-cms/pull/10391<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7158">issues.joomla.org/joomla-cms/7158</a>.</sub>

**Comment by dgt41** [comment]
@framontb can you also make a PR with the server side validation, as that one is also correct!
