### ISSUE TITLE
Created by Alias removes accented “à” last letter

### ISSUE THREAD

**Issue by antoniotheant** [joomla/joomla-cms#7166]
#### Steps to reproduce the issue
Inserting names with accented à as last letter (like “Currà”) into “Created by Alias” field, Joomla 3.4.1 removes the letter, so i get a truncated name (like “Curr”).
Other accented letters (like ì, é, ò) work fine.![screen shot 2015-06-12 at 13 18 57](http://issues.joomla.org/uploads/1/ac0ba51c28d07cdf5b2888c5585bd968.jpg)

**Comment by brianteeman** [comment]
I cannot replicate this

Please confirm which language your joomla admin is in and which browser you
are using

On 12 June 2015 at 19:20, antoniotheant <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Inserting names with accented à as last letter (like “Currà”) into
> “Created by Alias” field, Joomla 3.4.1 removes the letter, so i get a
> truncated name (like “Curr”).
> Other accented letters (like ì, é, ò) work fine.[image: screen shot
> 2015-06-12 at 13 18 57]
> <https://camo.githubusercontent.com/b0d8bc4d26da157575c6121ea8ea06c71511c7e7/687474703a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f61633062613531633238643037636466356232383838633535383562643936382e6a7067>
> Expected result Actual result System information (as much as possible) Additional
> comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7166>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
Also check if you have unicode alias enabled or disabled.

**Comment by brianteeman** [comment]
That should have no effect on saving to the db Thomas

**Comment by infograf768** [comment]
The issue has already been solved for 3.4.2. See: https://github.com/joomla/joomla-cms/pull/6806

Please close Issue.

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7166">issues.joomla.org/joomla-cms/7166</a>
