### ISSUE TITLE
Maintenance Infos on last staging are dublicated?

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#7176]
#### Steps to reproduce the issue

- Install / update to lastest staging / nigly build from: http://developer.joomla.org/cms-packages/
- access the administrator backend
- see the Maintenance Infos
- the messages are twice?

#### Expected result

The picture below but the textes should be only on time there.

#### Actual result

![screen shot 2015-06-14 at 14 40 42](http://issues.joomla.org/uploads/1/f2e6e1c6b4bfd3232e58a60227ead4a7.png)

**Comment by wojsmol** [comment]
I tested it on the lastest staging branch and everything looks correct - maintenance infos appear only once.

**Comment by zero-24** [comment]
@wojsmol hmm please try the following:

- Install 3.4.1
- Update to the current Nightly Build using this package: http://developer.joomla.org/cms-packages/Joomla_3.4.x_to_3.4.2-dev-Development-Patch_Package.zip
- see the `Maintenance Infos`

I have just confirmed it with at least 2 Installs one from 3.4.1 -> Nightly Build and 3.3.6 --> 3.4.1 --> Nightly Build

**Comment by brianteeman** [comment]
Is it a javascript cache issue @zero-24

**Comment by zero-24** [comment]
Thanks @brianteeman you are correct.
