### ISSUE TITLE
PDo Find language

### ISSUE THREAD

**Issue by oleg-kosarev** [joomla/joomla-cms#7177]
#### Steps to reproduce the issue

Install with PDO ok. But index.php?option=com_installer&view=languages and click Find language error "SQLSTATE[HY000]: General error: 1364 Field 'data' doesn't have a default value".

Set with Server Database Settings->Database Type Mysqli no problem. 

#### Expected result
 ALTER TABLE `sjt8f_updates` CHANGE `data` `data` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL  

#### Actual result
ALTER TABLE `sjt8f_updates` CHANGE `data` `data` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL 

Next for install language
SQLSTATE[HY000]: General error: 1364 Field 'custom_data' doesn't have a default value
ALTER TABLE `sjt8f_extensions` CHANGE `custom_data` `custom_data` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL 

And next error 
SQLSTATE[HY000]: General error: 1364 Field 'system_data' doesn't have a default value
ALTER TABLE `sjt8f_extensions` CHANGE `system_data` `system_data` TEXT CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL 

#### Additional comments
This is a temporary solution to the problem, or even an error in the files?

**Comment by wilsonge** [comment]
This is PDO mysql right?

**Comment by brianteeman** [comment]
I just installed 3.4.2 RC with mysqlpdo and could not replicate this.

**Comment by oleg-kosarev** [comment]
wilsonge: Yes I'm MySQL with PDO. 

brianteeman: Yes install no problem. BUT INSTALL OR FIND languages OR EXTENSIONS problem. Joomla!, 3.4.3 i do not watch this error. Probably already it corrected. Although written in the stage. Now I will be tested on a clean system, the results of accomplish your goal later.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7177">issues.joomla.org/joomla-cms/7177</a>.</sub>

**Comment by brianteeman** [comment]
I have successfully installed multiple languages and extensions under mysql-pdo

I am closing this at this time - if you still have this issue please provide further information on how to replicate it and it can be re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7177">issues.joomla.org/joomla-cms/7177</a>.</sub>

**Comment by sitthykun** [comment]
Now I face the problem while I was installing VirtuaMart with Joomla! 3.4.3 

Warning
SQLSTATE[HY000]: General error: 1364 Field 'custom_data' doesn't have a default value

I have changed "COLLATE utf8_general_ci NULL DEFAULT NULL", alternatively, I still got the error.
my temporary solution is set dbtype to "mysql" instead of "pdomysql"
