### ISSUE TITLE
JFile::move() returns a string, not a boolean:

### ISSUE THREAD

**Issue by compojoom** [joomla/joomla-cms#7178]
I just found out that JFile::move() actually returns a string whenever the file cannot be found. The doc comment states that it returns boolen. So my check if (JFile::move()) fails in some situations. 
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/filesystem/file.php#L252

What would be the correct way to fix this in your opinion? Log the message and return false. Or show the message with Japplication()->enqueueMessage?

**Comment by mbabker** [comment]
```php
JLog::add(JText::_('JLIB_FILESYSTEM_CANNOT_FIND_SOURCE_FILE'), JLog::WARNING, 'jerror');

return false;
```

**Comment by zero-24** [comment]
Closing as we have a Pull Request here: https://github.com/joomla/joomla-cms/pull/7180
