### ISSUE TITLE
Video.js fullscreen doesnt work on Joomla Iframe wrapper

### ISSUE THREAD

**Issue by baouftou** [joomla/joomla-cms#7181]
Hello,

I've made a video gallery with video.js on joomla using joomla's iframe wrapper to load the php files. The link to it is: http://i-wedding.gr/index.php/en/videos

Now if you open the php on it own: http://www.i-wedding.gr/video.php the videos play nicely and fullscreen's working.

But throught the iframe wrapper on joomla videos play fine but fullscreen is not working. http://i-wedding.gr/index.php/en/videos I've been trying to find out why and i cant make sence.

Anyone here could help?
Thanks in advance,
Jim

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org

**Comment by baouftou** [comment]
I've fixed this myself. Posted it here:
https://github.com/videojs/video.js/wiki/Joomla-com_wrapper-allowfullscreen-for-video.js
