### ISSUE TITLE
select.radiolist: input does need to be outside of label

### ISSUE THREAD

**Issue by Hanmac** [joomla/joomla-cms#7190]
currently https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/html/select.php radiolist does define input inside its label, but thats wrong because with that input cant be selected
the code does need to be rewritten so that the input field is outside of its label (maybe with also adding a div around both input and label)

while searching i also found this:
https://github.com/joomla-framework/form/blob/master/src/Html/Select.php

in that one its more correct with the input outside of the label.

**Comment by Bakual** [comment]
Both
`<label><input type="radio" name="foo" value="bar">Bar</label>`
and
`<label for="foo_id">Bar</label><input type="radio" id="foo_id" name="foo_name" value="bar">
are valid syntax

So it's not wrong, just a possible flavor. And I think the way we have is related to Bootstrap 2.3.

**Comment by Hanmac** [comment]
then i dont know what wend wrong, but i cant select the input in the first way because the label somehow prevents that

**Comment by Bakual** [comment]
I don't know either.
You may want to ask in the forum (forum.joomla.org) and see where the issue is coming from.

**Comment by Hanmac** [comment]
found the bug, some other developer did make a click event on the label with preventDefault.
thats why the click on the input got prevented.

still thanks for the fast helping.
