### ISSUE TITLE
[New feature] Version History limit context

### ISSUE THREAD

**Issue by Devportobello** [joomla/joomla-cms#7191]
## Context
When using Joomla! versioning feature, we are able to fix a number of history limit in configuration.

## Actual limitation
This history limit is only applied of the component context eg: com_banners.
If you want to got (wanna keep using banners component for exemple) only 10 history limit for banner and 5 for client (dunno if this could be real) this is not possible.

## And now?
Adding another context, eg:
```xml
<field
	name="history_limit.banner"
	type="text"
	filter="integer"
	label="JGLOBAL_HISTORY_LIMIT_OPTIONS_LABEL"
	description="JGLOBAL_HISTORY_LIMIT_OPTIONS_DESC"
	default="5"
/>
```
This possibility could help in third application (got some component who need this new feature), also maybe in actual joomla component; just want to know (got some feedback) if people agree with that.
Or maybe im wrong and there is another way.

### Code
[Contenthistory Helper](https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/helper/contenthistory.php#L145-L151)
To
```php
// Load history_limit config from extension.
$aliasParts = explode('.', $this->typeAlias);
$context = (isset($aliasParts[1]))?'.'.$aliasParts[1]:'';
if ($maxVersions = JComponentHelper::getParams($aliasParts[0])->get('history_limit'.$context, 0))
{
	$historyTable->deleteOldVersions($maxVersions);
}
```
PLUS checking if only ```get('history_limit', 0))``` for B/C

**Comment by Bakual** [comment]
I don't think we need that anywhere in core. But if it's 
* simple code
* helps some 3rd party extensions
* is backward compatible

then I don't see why we can't add it.

**Comment by brianteeman** [comment]
As you have code to fix the problem. Can you send your changes as Pull Request? If you need help try this doc: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests else let us know what you need  :smile:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7191">issues.joomla.org/joomla-cms/7191</a>.</sub>

**Comment by Devportobello** [comment]
Closing for #https://github.com/joomla/joomla-cms/pull/7206
