### ISSUE TITLE
JMailHelper::isMailAddress allows numbers for domain

### ISSUE THREAD

**Issue by berserkerx** [joomla/joomla-cms#7193]
#### Steps to reproduce the issue
JMailHelper::isEmailAddress('q@7');

#### Expected result
false

#### Actual result
true

#### System information (as much as possible)
Joomla 3.4.1, OpenServer (Apache 2.2, PHP 5.3), MS Windows 7

#### Additional comments
The problem piece of code is (/libraries/joomla/mail/helper.php):

// No problem if the domain looks like an IP address, ish
$regex = '/^[0-9\.]+$/';

if (preg_match($regex, $domain))
{
	return true;
}

A bit better solution:

$regex = '^([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.
([01]?\\d\\d?|2[0-4]\\d|25[0-5])\\.([01]?\\d\\d?|2[0-4]\\d|25[0-5])$';

Source: http://www.mkyong.com/regular-expressions/how-to-validate-ip-address-with-regular-expression/

**Comment by zero-24** [comment]
@berserkerx as you have code to fix the problem. Can you send your changes as Pull Request? If you need help try this doc: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests else let us know what you need  :smile:

**Comment by zero-24** [comment]
Closing as we have an pull request. Thanks @berserkerx https://github.com/joomla/joomla-cms/pull/7212
