### ISSUE TITLE
Unable to add or modify viewlevels -- Joomla 3.4.1 -- unknown column metakey

### ISSUE THREAD

**Issue by mfoiret** [joomla/joomla-cms#7202]
#### Steps to reproduce the issue

When creating or updating viewlevels (within the administration site), I get this error : 
L'enregistrement a échoué avec l'erreur suivante : Unknown column 'metakey' in 'field list' SQL=UPDATE `u1vtf_viewlevels` SET `title`='Pharmacie',`ordering`='0',`rules`='[10,11,14,8]',`metakey`='' WHERE `id`='8'

Seems that a columnt metakey should exist in table viewlevels, but it's not the case.

#### Expected result

Should be able to create or modifiy viewlevels ...

#### Actual result

Error when create or modify viewlevels

#### System information (as much as possible)

I use Joomla 3.4.1 , upgraded from 3.4.0 and 3.3.6 (3.3.6 was an new install).
When checking database under extensions menu, joomla says database is up to date ...

Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

PHP exécuté sur	Linux webd228.xxl.ha.ovh.net 
Version de la base de données	5.1.73-2+squeeze+build1+1-log
Interclassement de la base de données	utf8_general_ci
Version de PHP	5.4.38
Serveur web	Apache
Serveur web pour interface PHP	fpm-fcgi

#### Additional comments

![screen shot 2015-06-19 at 04 36 44](http://issues.joomla.org/uploads/1/d3747989e5c8c5eceb1364f177aba562.jpg)

**Comment by brianteeman** [comment]
This sounds like an issue with an extension that you have installed as you are correct that this field does not exist in that table and there is no code in the core of Joomla that should generate that message

**Comment by Bakual** [comment]
Closing as not a core issue.

**Comment by mfoiret** [comment]
Exact, this error disappears when I disable all my plugins.
I'll check which plugin creates this trouble.
Thanks for your help.

**Comment by brianteeman** [comment]
I would check any SEO or metadata plugins

Please post back when you find out which one was the culprit
