### ISSUE TITLE
Save new article with changed permissions, permissions are not saved

### ISSUE THREAD

**Issue by AndrisZemitis** [joomla/joomla-cms#7205]
#### Steps to reproduce the issue

Create new Article, change Manager edit permissions to Denied and save article.

#### Expected result

Article edit permission for user group Manager should be denied.

#### Actual result

Article edit permission for user group Manager is still set to allowed. 

#### System information (as much as possible)

Clean Joomla 3.4.1 installation (demo instance from demojoomla.com).

**Comment by n9iels** [comment]
issue confirmed, when creating an new article, permission settings will be ignored when saving. When the article is created, permission settings working fine

**Comment by brianteeman** [comment]
Also confirming the issue on a new article. the permission changes only work on the second save<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7205">issues.joomla.org/joomla-cms/7205</a>.</sub>

**Comment by joomdonation** [comment]
Hi

I made a small PR to fix this issue https://github.com/joomla/joomla-cms/pull/7223. It is quite simple fix. Please test it when you have time so that we can get the issue fixed (maybe in 3.4.2).

**Comment by andy1945** [comment]
Am still getting this error after updating to 3.8.6

**Comment by infograf768** [comment]
@andy1945 
You are unlikely to get a response on an issue from 2015.
Please open a new issue with precise testing instructions on a 3.8.8 site
