### ISSUE TITLE
Missing name in Menu Item Types selection Iframe

### ISSUE THREAD

**Issue by javigomez** [joomla/joomla-cms#7207]
Hi, 

For the System Tests we need that the menu item selection iframe has a `name`.

Right now the iframe has no `name`. But WebDriver interacts with iFrames using the name attribute `name` of the iframe tag to manipulate the iframe (see http://codeception.com/docs/modules/WebDriver#switchToIFrame) 

We need someone to modify this to add the name to the iframe like in the following example:

![screen shot 2015-06-19 at 11 07 20](http://issues.joomla.org/uploads/1/a482c7d89c34ccf6f8f2a32f7bd17cbd.png)

any takers?

This issue was raised at: https://github.com/joomla-extensions/weblinks/issues/67

Thanks very much

**Comment by dgt41** [comment]
@javigomez I think you are gonna need this in more places. I will make a pr for all the bootstrap/iframe cases...

**Comment by dgt41** [comment]
@javigomez have a look at #7211

![screenshot 2015-06-19 20 53 09](https://cloud.githubusercontent.com/assets/3889375/8259533/d1c3d950-16c5-11e5-89eb-26e6ee0c1c11.png)

**Comment by zero-24** [comment]
Closing as we have a PR at #7211 Thanks :smile:

**Comment by javigomez** [comment]
thanks @zero-24 :)
