### ISSUE TITLE
Existing position changed to custom position after save

### ISSUE THREAD

**Issue by n9iels** [joomla/joomla-cms#7209]
This is a very minor, but noticeable bug:
1) Create a module and assign it to a exciting template position.
2) Save the module
3) Notice that the selected position now is displayed under: "Custom positions"

Not sure if this is done with a reason. So yes, please tell me why because I am wondering :)

**Comment by zero-24** [comment]
I can confirm it. But i also have no clue why?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7209">issues.joomla.org/joomla-cms/7209</a>.</sub>

**Comment by sovainfo** [comment]
The custom positions are those that have been used. Meaning you have module instances using those positions.

**Comment by brianteeman** [comment]
@sovainfo which suggests that the "issue" is the name "custom positions" which should therefore be renamed something link "positions in use" in this situation?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7209">issues.joomla.org/joomla-cms/7209</a>.</sub>

**Comment by brianteeman** [comment]
Something like this with the string being changed to Active Positions!

[screen shot 2015-06-23 at 03 11 33](http://issues.joomla.org/uploads/1/fe2a9b6bff1df53469b4b1058f049a49.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7209">issues.joomla.org/joomla-cms/7209</a>.</sub>

**Comment by n9iels** [comment]
I think that's a good solution. Because it says more about the below positions. I will make a PR for it in a minute

**Comment by sovainfo** [comment]
Agree with that or use "In use by modules". Maybe other can confirm that that is the issue, and what they prefer?
Also, I would like it to start with that category, most likely you are going to use what is already used.

**Comment by brianteeman** [comment]
@n9iels thanks
@sovainfo that will probably be too long

**Comment by sovainfo** [comment]
only 1 character longer is too long???
alternative: Used by modules

**Comment by zero-24** [comment]
Closing as we have #7252 that fix this issue :smile:
