### ISSUE TITLE
For site security using a password for the database account is mandatory

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#7214]
![screen shot 2015-06-20 at 00 01 16](https://cloud.githubusercontent.com/assets/400092/8264629/5b6ec0ce-16e0-11e5-9cf6-2b46260ea875.png)

**"For site security using a password for the database account is mandatory"**

But its not a mandatory field in the installation of Joomla....

Nor is it mandatory for a mysql database to actually need a password

Although I agree "For site security using a password" for the database is the best practice (and suicide not to) the help text stating its "mandatory" is not correct as it is perfectly possible to install Joomla with NO database password, and technically also possible as mysql doesn't require a password. 

Either the text needs changing or the field needs to be validated and forced to be mandatory

**Comment by brianteeman** [comment]
I think this is a matter of semantics.

I read it as saying if you want your site to be secure then it is mandatory to have password 
Not that it is mandatory to have a password on your database

**Comment by PhilETaylor** [comment]
It should be clear then - and not open to being interpreted incorrectly.

**Comment by PhilETaylor** [comment]
![screen shot 2015-06-20 at 00 25 20](https://cloud.githubusercontent.com/assets/400092/8264787/dfd75ffe-16e2-11e5-8c69-57fc14f4a17b.png)
![screen shot 2015-06-20 at 00 26 11](https://cloud.githubusercontent.com/assets/400092/8264792/fb8096c6-16e2-11e5-8b55-173ac259fb92.png)
![screen shot 2015-06-20 at 00 27 45](https://cloud.githubusercontent.com/assets/400092/8264796/327a1184-16e3-11e5-8c58-79bb43ba3f7e.png)
![screen shot 2015-06-20 at 00 29 13](https://cloud.githubusercontent.com/assets/400092/8264814/67b6c7b6-16e3-11e5-8981-ad8847d26afe.png)

![screen shot 2015-06-20 at 00 22 39](https://cloud.githubusercontent.com/assets/400092/8264773/822f343a-16e2-11e5-9901-fca53ec5f777.png)

**Comment by brianteeman** [comment]
If this was something in the last ten years we had people questioning I
would agree but that's not the case.

Until the likes of xampp stop being idiots and making it hard to set a
password and username then making this required is going to make it much
harder for users to try out Joomla locally.

**Comment by brianteeman** [comment]
Feel free to submit a pull request you know how to I think :)

**Comment by PhilETaylor** [comment]
Yes I know how to waste time on pull requests that no one wants to consider only for it to be ignored and a waste of my time. 

The whole "submit a pull request and if we like it then we will use it if we disagree with the slightest thing, or just don't like you, then thanks for spending hours on code, but we will just close the request, with no thanks" development process is flawed and a waste of good developers time. 

I've lost faith in random Speculative Pull Requests as a development process. Just like a lot of developers. 

Joomla's development is stalled because of the Speculative Pull Request development process. Hours of good developers time has been wasted on pull requests.
