### ISSUE TITLE
Disabling extensions with still published modules is possible

### ISSUE THREAD

**Issue by astridx** [joomla/joomla-cms#7222]
# See the issue

1. Go to the Extensions | Module Manager and ensure, that you have a modules of the type search for the location site witch is unpublished.

![snap1](https://cloud.githubusercontent.com/assets/9974686/8267657/a8ad071c-176a-11e5-8dc1-732829033a22.jpg)

2. Switch to Extension Manager|Manage and disable the Modul “Search” for the location site and see, that it is possible to disable this extension.

![snap2](https://cloud.githubusercontent.com/assets/9974686/8267661/c4613f1e-176a-11e5-8236-ecb036fcc338.jpg)

I think this is a failure, because I would expect, that it is not possible to disable an extension witch has published modules. I would expect a message, that I have to delete (or at least to unpublish) the modules.
What do you think. Worth it to find a solution?

**Comment by Bakual** [comment]
I think it's working as it should. By that logic, you would also have to remove/unpublish all modules before uninstalling them. Or remove any menu items before disabling/uninstalling a component.

That's just making the life more complicate for the user.

**Comment by astridx** [comment]
Thank you for your answer :-)
