### ISSUE TITLE
Problems with buttons Save and Save & Close (Joomla 3.4.1)

### ISSUE THREAD

**Issue by radiomanhead** [joomla/joomla-cms#7225]
#### Steps to reproduce the issue

Administrator Interface: when i upgrade from Joomla 3.3.3 to 3.4.1 using PHP 5.5.25

#### Expected result

Nothing special, just everything working fine

#### Actual result

The buttons Save and Save & Close does not work.

#### System information (as much as possible)

Joomla! Version: Joomla! 3.3.3 Stable
Upgrade Version: 
PHP Version: 5.5.25
Web Server: Apache: 3.4.1

**Comment by dgt41** [comment]
@radiomanhead You didn’t mention in which component you experience that. I am guessing this is a 3PD component and the cause for this is the fact that 3.4.1 toolbar is not loading mootools. If this is a custom component you wrote you have two options:
convert the script in the edit view to not require mootools (usually all it needs is write the `document.id` to `getElementById` and `formvalidation` to `formvalidator
or just load mootools `JHtml::_('behavior.framework'');`

If this is somebody else’s component, most probably they do have an update that solves that

**Comment by brianteeman** [comment]
And please clear your browser cache

On 21 June 2015 at 16:11, Dimitris Grammatiko <notifications@github.com>
wrote:

> @radiomanhead <https://github.com/radiomanhead> You didn’t mention in
> which component you experience that. I am guessing this is a 3PD component
> and the cause for this is the fact that 3.4.1 toolbar is not loading
> mootools. If this is a custom component you wrote you have two options:
> convert the script in the edit view to not require mootools (usually all
> it needs is write the document.id to getElementById and formvalidation to
> formvalidator
> or just load mootoolsJHtml::_('behavior.framework'');`
>
> If this is somebody else’s component, most probably they do have an update
> that solves that
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7225#issuecomment-113912516>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by radiomanhead** [comment]
The buttons doesn't work on any option of joomla: JCE editor, Tiny Editor, Saving any kind of configurations.... doesn't work at all, i can't save anything. (excuse my english my native languaje is spanish)

PS. I al ready clean the Browser and joomla Cache.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7225">issues.joomla.org/joomla-cms/7225</a>.</sub>

**Comment by Fedik** [comment]
@radiomanhead  please try check the browser console for any javascript error: on page open, on push the save button ... and tell us or make screenshot, if any...

> The buttons doesn't work on any option of joomla: JCE editor, Tiny Editor,

@dgt41 asked which Component you use: you tried make new item in Joomla Article/Category, or new content item in some other component? 
the editor does not matter in this case (in most cases)

**Comment by radiomanhead** [comment]
I'm trying a few things: new item in Joomla Article/Category, Some modifications in Global Configuration, add some new item in the menu,none of those things works.

The instalation of joomla is clean only the components, modules and plugin includes in the 3.3.3 original pack.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7225">issues.joomla.org/joomla-cms/7225</a>.</sub>

**Comment by ggppdk** [comment]
Preferably in firefox or chrome

1. Click "F12" to open browser tools,

2. go to console TAB, 

3. then click refresh the page,
- if there are errors in the console, copy them here

4. click save button
- if there are more errors copy them here

**Comment by radiomanhead** [comment]
Well, after two weeks with this issues in all mi websites today everything is working fine (and with no explanation). Thanks to everyone for yopur support and advice. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7225">issues.joomla.org/joomla-cms/7225</a>.</sub>

**Comment by ysramirez** [comment]
The problem is whit your cache browser just use CTRL+F5 in firefox

**Comment by msbroadway** [comment]
CTRL+F5 - thank you!  I can finally save using Firefox again.

**Comment by mylifefactory** [comment]
Change for a newer version of jquery.min.js

**Comment by homayr** [comment]
Hi Dear,
I upgraded to joomla 3.5 and now none of the buttons (Save, save and close etc works) except the close button. Can you please advise what it could be. And how to I get a newer version of jquery?
thanks

**Comment by brianteeman** [comment]
Make sure that you completely clear your browser cache

For further support please use the forum http://forum.joomla.org

On 16 June 2016 at 17:13, homayr <notifications@github.com> wrote:

> Hi Dear,
> I upgraded to joomla 3.5 and now none of the buttons (Save, save and close
> etc works) except the close button. Can you please advise what it could be.
> And how to I get a newer version of jquery?
> thanks
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7225#issuecomment-226535112>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8cScZWH7DWYqZGeL68PFiBMJAK4Sks5qMXZEgaJpZM4FIUo1>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by homayr** [comment]
Hi again, sorry but it did not work. Very strange in my simple module this is the message I am getting 
Custom 
Site
This module allows you to create your own Module using a WYSIWYG editor.

I can not even open the module. Please help

**Comment by homayr** [comment]
All my menu type have changed to custom

**Comment by brianteeman** [comment]
For further support please use the forum http://forum.joomla.org
