### ISSUE TITLE
Can't open administrator page 

### ISSUE THREAD

**Issue by snackmans** [joomla/joomla-cms#7226]
#### Steps to reproduce the issue
I can't open administrator page it always show this message 

Warning: require_once(/home4/snackman/public_html/www.icansurvive.com/administrator/components/com_users/models/user.php): failed to open stream: No such file or directory in /home4/snackman/public_html/www.icansurvive.com/plugins/authentication/joomla/joomla.php on line 105

Fatal error: require_once(): Failed opening required '/home4/snackman/public_html/www.icansurvive.com/administrator/components/com_users/models/user.php' (include_path='.:/opt/php54/lib/php') in /home4/snackman/public_html/www.icansurvive.com/plugins/authentication/joomla/joomla.php on line 105

What I have to do ?

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.Joomla.org
