### ISSUE TITLE
Template Bug

### ISSUE THREAD

**Issue by Karpatsky** [joomla/joomla-cms#7227]
Hi there. Check this [http://www.joomla.org/?template=](http://www.joomla.org/?template=  "http://www.joomla.org/?template= ") 
It looking not good in main Joomla site.
I have checked this at my projects - yea, looks like bad bug, when you add ?template after joomlasiteurl/

**Comment by Fedik** [comment]
it not bug it feature :smile:

**Comment by Karpatsky** [comment]
How can i off this awesome feature in my project then? )<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7227">issues.joomla.org/joomla-cms/7227</a>.</sub>

**Comment by Karpatsky** [comment]
Nice bank page http://gtbank.com/?template= <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7227">issues.joomla.org/joomla-cms/7227</a>.</sub>

**Comment by Fedik** [comment]
good question, let's wait someone with knowledge in this issue :wink:

**Comment by mbabker** [comment]
I can only reproduce the blank variable changing the template on 2.5 sites.  Using 3.x sites, the blank variable causes a blank page.  Nonetheless, https://github.com/joomla/joomla-cms/pull/7228 fixes it.

**Comment by mbabker** [comment]
Also to get the blank page, the hardcoded fallback (beez3 for 3.x) has to have no template styles enabled in the template style list.  Otherwise if you have a style for it, then it can render.

**Comment by zero-24** [comment]
Closing as we have a Pull by Michael :smile: #7228
