### ISSUE TITLE
com_installer possible missing tags 

### ISSUE THREAD

**Issue by nppsbh** [joomla/joomla-cms#7230]
Think there are missing some closing tags in com_installer
/administrator/components/com_installer/views/install/tmpl/default.php
after line 182 missing \</div>

/administrator/components/com_installer/views/database/tmpl/default.php
line 40 missing \</li>
after line 82 missing <?php echo JHtml::_('bootstrap.endTabSet'); ?>

**Comment by zero-24** [comment]
Closing as @OctavianC have a Pull Request with the changes here: https://github.com/joomla/joomla-cms/pull/7235 Thanks @nppsbh Good finds
