### ISSUE TITLE
Menu type modal automatically closes

### ISSUE THREAD

**Issue by javigomez** [joomla/joomla-cms#7241]
#### Steps to reproduce the issue
Install 3.4.2-rc2-dev, latest version from Staging.

Go to: Menu Manager -> Main Menu -> add menu item

Try to create a menu, you will notice that when you try to open the Menu Type modal it automatically gets closed. See this video: http://www.youtube.com/watch?v=z_qooPg-IcQ

#### Expected result
The menu type modal should remain until you select a menu type, instead of closing itself automatically

#### Actual result
The modal closes without giving time to interact with it.

#### System information (as much as possible)
I have seen the issue in a MacOS google chrome Version 43.0.2357.124 (64-bit)
also happening in latest firefox and latest safari

**Comment by dgt41** [comment]
There is no code to close the modal automatically in this view. Do you have any javascript errors logged?

**Comment by javigomez** [comment]
strange, i can't reproduce it anymore O_o'

Closing ^_^
