### ISSUE TITLE
[REGRESSION] - Scrollbar flashing in batch modals. Tooltips offset to the right

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#7247]
#### Description
In batch modals tooltips are not displayed and the main window scrollabar disappear when you move the mouse over a label.

#### Steps to reproduce the issue
- Open a batch modal (either in article manager or menu manager)
- Move the mouse over a label (e.g.: "Set language" in the Menu manager modal)
- The main window scrollbar, on the right side, will disappear and the modal will snap a little bit to the right (*really annoying*)
- ~~Tooltips are not displayed~~
- Tooltips are displayed with a great offset to the right

#### Additional comments

In Joomla 3.4.1 too Tooltips are missing, but the modal does not snap (*... and that's probably why I never noticed...*)

Tested with Windows 8.1, FF 38.0.5, Chrome 43.0

**Comment by smz** [comment]
@dgt41 I think this is due to the JS mods you made in #6964...

**Comment by smz** [comment]
In my original code the `modal-open` class was always added to `<body>`
With your PR you apply it only to **url** modals...

**Comment by smz** [comment]
... of course I meant to say the exact contrary of what I said! :smile:

**Comment by smz** [comment]
Actually tooltips are displayed, with a great offset to the right (*I don't know why in my first tests I wasn't seeing them...* :confused: )

**Comment by smz** [comment]
#7248 partially fix this (*without undoing the mods intrduced by @dgt41 in #6964*)

**Comment by brianteeman** [comment]
Closing as we have a PR #7248<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7247">issues.joomla.org/joomla-cms/7247</a>.</sub>

**Comment by smz** [comment]
I disagree on this being closed: #7248 is a **partial** fix to this issue, and does not pretend to fix the tooltips problem (*which IMHO should be fixed too before shipping 3.4.2*)
