### ISSUE TITLE
Wrong redirect after successfull login in second attempt

### ISSUE THREAD

**Issue by ChuckNorrison** [joomla/joomla-cms#7249]
Users login with a Login Module. If they type a wrong password, they come to a new side to correct the settings. Here they got redirected to a wrong link if login was successfull. The link is a Article-Link:
index.php/component/content/article?id=29

i dont know why and how to correct it, In my Login Module, Loginredirect after success is setup to a menuitem.

![unbenannt](https://cloud.githubusercontent.com/assets/2964146/8299915/52142d1a-197f-11e5-9b61-8cf9e415ce4e.JPG)

**Comment by OctavianC** [comment]
This seems related to this PR: https://github.com/joomla/joomla-cms/pull/6542

Can you please test with Joomla! 3.4.2 Release Candidate: https://github.com/joomla/joomla-cms/releases/tag/3.4.2-rc and report back the results?

**Comment by ChuckNorrison** [comment]
Thanks, it works with 3.4.2

**Comment by brianteeman** [comment]
Closed as fixed elsewhere<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7249">issues.joomla.org/joomla-cms/7249</a>.</sub>
