### ISSUE TITLE
select user group drop down list is empty in batch process for user manager

### ISSUE THREAD

**Issue by nor-azizah** [joomla/joomla-cms#7250]
#### Steps to reproduce the issue

under user manager click on batch tab

![screen shot 2015-06-23 at 01 11 05](http://issues.joomla.org/uploads/1/fe8d2ff2521b1a08acb0e123fd87dbe6.)

#### Expected result

Should be the list of user group listed in the drop down list

#### System information (as much as possible)

i'm using joomla 3.3

**Comment by brianteeman** [comment]
I cannot confirm this

Also please upgrade to the latest release of Joomla which at this time is 3.4.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7250">issues.joomla.org/joomla-cms/7250</a>.</sub>

**Comment by nor-azizah** [comment]
is there any other way to fix this in joomla 3? i find this very weird because other functions working well.
Please,really need help on this.

Thanks

**Comment by brianteeman** [comment]
The first thing you MUST do is to update to the current release. It might
be something that has already been fixed.

For support on using Joomla please use the forum http://forum.joomla.org

On 23 June 2015 at 08:49, nor-azizah <notifications@github.com> wrote:

> is there any other way to fix this in joomla 3? i find this very weird
> because other functions working well.
> Please,really need help on this.
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7250#issuecomment-114395011>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
