### ISSUE TITLE
Permissions are not saved when creating an article

### ISSUE THREAD

**Issue by javigomez** [joomla/joomla-cms#7251]
#### Steps to reproduce the issue
- Create a new  article
- fill the title and go to Permissions tab. Do changes there and SAVE & CLOSE
- open the article again and your modified permissions won't be there. Change them again and save, you will see that this time permissions are saved

See this video: http://www.youtube.com/watch?v=Dn8vlLsQqS0

#### Expected result
I see here, two options:

1.- make permissions to be saved the first time you create an article
2.- or permissions tab is hidden until you save for first time

This issue was discovered while testing: http://issues.joomla.org/tracker/joomla-cms/7243

**Comment by Bakual** [comment]
Will be fixed with https://github.com/joomla/joomla-cms/pull/7223
Closing as we have a PR.
