### ISSUE TITLE
REGRESSION: CodeMirror + J3.4.2-rc = Readmore Button in Content redirect to the Admin Dashboard

### ISSUE THREAD

**Issue by joomla-agency** [joomla/joomla-cms#7260]
#### Steps to reproduce the issue
Install Joomla 3.4.2-rc
Set you Editor to CodeMirror
Create a new Article and click on the ReadMore Button under the Editor

#### Expected result
After the you should see a readmore snippet in your Code

#### Actual result
You are redirected to the Admin Dashboard

#### System information (as much as possible)
Joomla 3.4.1 -> Joomla 3.4.2-rc
PHP 5.6.2
Mysql 5.6.19
Tested Browser: FireFox 38.0.5

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7260">issues.joomla.org/joomla-cms/7260</a>.</sub>

**Comment by brianteeman** [comment]
Raised priority based on https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7260">issues.joomla.org/joomla-cms/7260</a>.</sub>

**Comment by dgt41** [comment]
reverting this: https://github.com/joomla/joomla-cms/commit/1e2896ca1347e134e655ecf2bd3d09bf505e24b8 corrects the problem? If so I will provide a fix (this is an improvement and we should not revert it!)

**Comment by joomla-agency** [comment]
@dgt41 yes i revert to the old code and the Problem is gone.

**Comment by dgt41** [comment]
Actually best way to solve this is to revert that patch and edit tinyMCE so the read more will be injected always to the active editor (in case of multiple instances) 
so instead of
```
	public function onSetContent($editor, $html)
 	{
		return 'tinyMCE.get(\'' . $editor . '\').setContent(' . $html . ');';
 	}
 ```
we have this
```
	public function onSetContent($html)
 	{
			return 'tinyMCE.activeEditor.setContent(' . $html . ');';
 	}
 ```

**Comment by infograf768** [comment]
Please propose a patch. This is a regression.

**Comment by infograf768** [comment]
Changed title to add 'regression"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7260">issues.joomla.org/joomla-cms/7260</a>.</sub>

**Comment by dgt41** [comment]
Please test #7263

**Comment by Bakual** [comment]
Closing as we have a PR.
