### ISSUE TITLE
[REGRESSION] - Class 'JFolder' not found in languagefilter.php

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#7265]
#### Steps to reproduce the issue
- Have a multilingual site
- In Language Filter set Automatic Language Change to "Yes"
- Create an user and assign to him/her a language different from the default one
- Navigate to the default language home page
- Login with the above created user

#### Expected result
User logged in and redirected to assigned language

#### Actual result
You'll get an error:
`Fatal error: Class 'JFolder' not found in base-path/plugins/system/languagefilter/languagefilter.php on line 527`

#### Additional comments

I don't have the slightest clue why this is happening!

**Comment by smz** [comment]
More system info:
~~~
System Information
Setting 	Value
 
PHP Built On 	Windows NT SMZ 6.3 build 9200 (Windows 8.1 Business Edition) i586
Database Version 	5.6.23
Database Collation 	utf8_general_ci
PHP Version 	5.4.39
Web Server 	Apache
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.4.2-rc2-dev Release Candidate [ Ember ] 20-June-2015 23:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:38.0) Gecko/20100101 Firefox/38.0 
~~~

**Comment by mbabker** [comment]
#7266 should fix.  BTW, creating a PR on mobile isn't easy.
