### ISSUE TITLE
Negating user groups in Access Level

### ISSUE THREAD

**Issue by artur-stepien** [joomla/joomla-cms#7270]
It would be nice to have the option to negate users groups in Access Level (like in modules Menu Assignment).

**The problem**
I have 3 main groups of registered users:
- Registered
- Club Members
- Club Management

Each user in Club Members group and Club Management group is also a member of Registered group.

Some content I need to show only for those who are not Members or Management (for potential customers). The best solution would be to create new Access Level valid only for those users. But it is impossible because Registered group has also Members and Management.

I know it can be done by creating another Registered group for Members and Management but it would be to many groups and a little confusing. Also it can create a lot of unnecessary work and possibly break some components that use default registered group (Registered).

**How it could work**
With a possibility to negate users groups in Access Level I could just create a level with those rules:
_Registered AND NOT Club Members AND NOT Club Management_

**Interface changes**
Interface for that functionality would be very close to current version. With that difference that it would need a 3 levels check button or a select field (Users in that group, Users that are not in that group, Omit)

**Comment by Bakual** [comment]
> I know it can be done by creating another Registered group for Members and Management but it would be to many groups and a little confusing. Also it can create a lot of unnecessary work and possibly break some components that use default registered group (Registered).

It will not break components for sure. Except if they are really bad written and somehow hardcode things to a specific default access level.

I think your request would neglect the whole idea of a hierarchic ACL system. Why would you put them into the "Registered" group if they are not supposed to see things from that level?

What you likely need is a user group structure like this:

Public
|-- Registered
|--|-- Not Members
|--|-- Club Members
|--|--|-- Club Management

This your members and management inherits from registered permissions, and also the non-members do. But you can now set different permissions for members and non-members.

You then create a new view level for that non-member group. All will still see articles set as registered and your new advertisment article can be set to the new viewlevel.

And to make it perfect just set the default group for new registered users to that "Not Member" group.

**Comment by brianteeman** [comment]
I am closing this issue as @bakual has provided the recommended solution with the current ACL system.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7270">issues.joomla.org/joomla-cms/7270</a>.</sub>
