### ISSUE TITLE
"grecaptcha is not defined" from contact form with recaptcha 2.0 with Display Format set to Tabs, omitting Miscellaneous Information

### ISSUE THREAD

**Issue by kpetku** [joomla/joomla-cms#7272]
## Steps to reproduce the issue:
- Provisioned a fresh installation of core Joomla! 3.4.1
- Configured a captcha using the Joomla plugin configured with reCAPTCHA 2.0, Light theme, and valid credentials
- Set global Contact Manager options -> Contact -> Display Format to "Tabs"
- Created a new test contact, with the email address of test@example.org.  Under "Miscellaneous Information" stored the word "test"
- Created a new menu item, with a menu item type of "Single Contact", named "contact form test", with "Select Contact" pointed to "test contact" from above

## Expected result:
- On the fly changes of Contact Manager 'Display Format' options should not break the captcha on the contact form
- The "Miscellaneous Information" of a contact should be displayed with or without a reCAPTCHA 2.0 configured on a site

## Actual result:

- The Captcha does not render on the front end in the "Contact Form" tab as expected
- There is a javascript console error of: "Uncaught ReferenceError: grecaptcha is not defined"
- The "Miscellaneous Information" tab is not rendering
- When filling out the contact form and pressing the "Send Email" button, Joomla throws:
  "Warning
  Empty solution not allowed."

## System information:
```
PHP Version	5.5.19
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.125 Safari/537.36
```
## Other information:
- Changing the "Display Format" Contact Manager option to "Tabs" will cause the reCAPTCHA 2.0 captcha and subsequent "Miscellaneous Information" to improperly render
- Screenshot of the test contact form using the "Tabs" option:
![image](https://cloud.githubusercontent.com/assets/2693010/8385004/0d094796-1c13-11e5-813d-ddb062395e04.png)
- Screenshot of the same test contact form using the "Sliders" option:
![image](https://cloud.githubusercontent.com/assets/2693010/8385008/1482ffe4-1c13-11e5-8c10-006bdd09c31a.png)

Thank you for checking.

**Comment by brianteeman** [comment]
Thank you for your detailed report.

I have followed your instructions and tested using all three contact display options using Joomla 3.4.2RC and I am unable to replicate it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7272">issues.joomla.org/joomla-cms/7272</a>.</sub>

**Comment by kpetku** [comment]
Hi @brianteeman

It works fine for me when testing against Joomla 3.4.2RC.  I didn't see an issue for this when I searched, so sorry for the noise.

Thank you

**Comment by brianteeman** [comment]
No problem. Your very detailed report made it easy to test. I wish all
reports had such good instructions
