### ISSUE TITLE
Messed up maintenance info

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#7275]
I did a fresh installation with the current staging branch, went to the backend and noticed that the maintenance info looks cluttered. Obviously the text is displayed twice.

![template3_270515](https://cloud.githubusercontent.com/assets/9270310/8391386/838d476e-1cc2-11e5-950b-cb32322d72be.png)

**Comment by brianteeman** [comment]
Clear your browser cache and all will be fixed

**Comment by waader** [comment]
That was an easy fix.
