### ISSUE TITLE
wrong param in language file en-GB.com_media.ini

### ISSUE THREAD

**Issue by aaleksanyants** [joomla/joomla-cms#7282]
Found typo in language/en-GB.com_media.ini - please check the param on row 48: COM_MEDIA_FIELD_PATH_IAMGE_FOLDER_DESC
- should be:
COM_MEDIA_FIELD_PATH_IMAGE_FOLDER_DESC

**Comment by zero-24** [comment]
Here is a PR. Good find @aaleksanyants<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7282">issues.joomla.org/joomla-cms/7282</a>.</sub>

**Comment by zero-24** [comment]
hehe should like it :smile: see: https://github.com/joomla/joomla-cms/pull/7283<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7282">issues.joomla.org/joomla-cms/7282</a>.</sub>
