### ISSUE TITLE
Plugin media field type issue

### ISSUE THREAD

**Issue by nppsbh** [joomla/joomla-cms#7285]
Hi
I found a odd behavior in plugin using media field type.
Scenario where several media fields type exists.
If you select a image in one of those fields, but **not the first in the plugin** everything is working as expected, when you hover the image name nothing happens.
But if you also select an image in **the first media field type** in the plugin when you hover the image name it displays a tooltip with the file name, and that name will be always the name of the first media field type image, even if you hoover other media fields type.

**Comment by brianteeman** [comment]
This is a known issue. I can't find the tracker issue for it now (on phone)
but the issue was identified for the intro and full images in com_content

**Comment by brianteeman** [comment]
Found it #6799 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7285">issues.joomla.org/joomla-cms/7285</a>.</sub>

**Comment by nppsbh** [comment]
Sorry if duplicate. Didn't look enough.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7285">issues.joomla.org/joomla-cms/7285</a>.</sub>

**Comment by brianteeman** [comment]
Not a problem - better to report and let one of us check than not to report
at all

On 30 June 2015 at 11:10, nppsbh <notifications@github.com> wrote:

> Sorry if duplicate. Didn't look enough.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/7285
> <http://issues.joomla.org/tracker/joomla-cms/7285>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7285#issuecomment-117110684>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
