### ISSUE TITLE
Media field joomla

### ISSUE THREAD

**Issue by adilhoussam** [joomla/joomla-cms#7287]
Hello

#### Steps to reproduce the issue

create component joomla
Add field media ( look picture ) 

#### System information (as much as possible)

Joomla! 3.4.1

#### Additional comments
in hover in the second or third input i have in the title (path) of the first input( look picture ) 

#### XML
<field name="image1" type="media" label="COM_SWPROJETS_FORM_LBL_MARQUE_IMAGE1"
			description="Taille : 850x270" required="false" directory="/projets/" />

<field name="image2" type="media" label="COM_SWPROJETS_FORM_LBL_MARQUE_IMAGE2"
			description="Taille : 558x270" required="false" menu_published="0"
			filter="raw" directory="/projets/" option_on="Yes" option_off="Yes" />

<field name="image3" type="media" label="COM_SWPROJETS_FORM_LBL_MARQUE_IMAGE3"
			description="Taille : 270x270" required="false" menu_published="0"
			filter="raw" directory="/projets/" option_on="Yes" option_off="Yes" />

**Comment by adilhoussam** [comment]
XML FILE<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7287">issues.joomla.org/joomla-cms/7287</a>.</sub>

**Comment by adilhoussam** [comment]
BUG
![screen shot 2015-06-30 at 08 34 58](http://issues.joomla.org/uploads/1/0da3d183fe8e0ce2071bd93e0432b865.jpg)

XML FILE
![screen shot 2015-06-30 at 08 36 39](http://issues.joomla.org/uploads/1/79c73219eb3104ecf7c6b3e28ceb6a6a.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7287">issues.joomla.org/joomla-cms/7287</a>.</sub>

**Comment by brianteeman** [comment]
Closing as a known issue - please see #6799
