### ISSUE TITLE
after update to 3.4.2 there'sa notice for new update 3.4.1

### ISSUE THREAD

**Issue by jojo12** [joomla/joomla-cms#7288]
title says all

**Comment by brianteeman** [comment]
A notice where?

**Comment by tranduyhung** [comment]
If it is "Joomla! 3.4.1 is available: Update now", I don't see it in all of my 3.4.2 sites.

**Comment by jojo12** [comment]
strange, this was after resfreshi ng. 
Meanwhile I was away. When I came back and restarted, the notice is away. Sorry. Seems, it can be closed.
