### ISSUE TITLE
Registration Problems

### ISSUE THREAD

**Issue by mrelliottbrown** [joomla/joomla-cms#7290]
I am a beginning user, but several people trying to register at my site are getting the following result when trying to register: "You must specify a merge_vars value for the listsubscribe method"

This happens on both mobile and desktop, for Safari, Firefox and Chrome users (all latest versions).  Everyone associated with my company does NOT have problems, including not using company email addresses.  Please help.

**Comment by brianteeman** [comment]
For support on your site please use the forum http://forum.Joomla.org
