### ISSUE TITLE
Control panel showing updates unavailability twice

### ISSUE THREAD

**Issue by aaleksanyants** [joomla/joomla-cms#7291]
Here is what I get when entering the control panel after a short time of checking for joomla and extensions updates:
**Maintenance**

    **Joomla! is up-to-date.** **Joomla! is up-to-date.**	
    **All extensions are up-to-date.** **All extensions are up-to-date.**

**Comment by mbabker** [comment]
Please see https://docs.joomla.org/J3.x:Duplicate_Maintenance_Info and follow the instructions on the page.
