### ISSUE TITLE
Hamburger menubutton: No mainmenu in mobile Firefox on Android

### ISSUE THREAD

**Issue by Klipper** [joomla/joomla-cms#7293]
#### Steps to reproduce the issue
Just load administrator in mobile Firefox browser(Android). When pushing the Hamburgermenubutton, you are redirected to the homepage on the frontend.

#### Expected result
When pushing the Hamburgermenubutton we should see the administrators mainmenu as a vertical mobile menu.

#### Actual result
When pushing the Hamburgermenubutton, you are now redirected to the homepage on the frontend.

#### System information (as much as possible)
Latest Firefox mobile browser (Android)

#### Additional comments
This is very easy to fix:

Just add the attribute href with the "#" value: href="#" to the &lt;a....&gt; on line 154 of index.php of the isis template. So line 154 become:
&lt;a href="#" class="btn btn-navbar collapsed" data-toggle="collapse" data-target=".nav-collapse"&gt;

**Comment by Klipper** [comment]
BTW This issue was also present in previous Joomla versions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7293">issues.joomla.org/joomla-cms/7293</a>.</sub>

**Comment by Kubik-Rubik** [comment]
@Klipper Thank you for reporting this issue. Please do a Pull Request with the suggested change so that we can test it. Thank you!

**Comment by brianteeman** [comment]
I can confirm this

**Comment by PhilETaylor** [comment]
PR #7305 Attached - Please test.

**Comment by zero-24** [comment]
Closing as we have a PR thanks @PhilETaylor
