### ISSUE TITLE
Upgrade to joomla 3.4.2 compatibility

### ISSUE THREAD

**Issue by joomlart** [joomla/joomla-cms#7295]
Mistaken post. Sorry.

**Comment by zero-24** [comment]
Please add some more infos. I don't know what you try to say us Thanks :smile:

**Comment by brianteeman** [comment]
Closing - when you have an issue to report please provide detailed information.

(are you sure that you didnt mean to be posting to the Joomlart issue tracker?)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7295">issues.joomla.org/joomla-cms/7295</a>.</sub>
