### ISSUE TITLE
Session cookie in httponly

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#7297]
[Removed]

**Comment by zero-24** [comment]
Please report sec issues to the JSST and not in the public tracker :smile: Thanks. I have send them now your text thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7297">issues.joomla.org/joomla-cms/7297</a>.</sub>

**Comment by btoplak** [comment]
@zero-24 Just a sidenote - this wasn't vulnerability report as far as I can see. It was just secure coding advice.

**Comment by andrepereiradasilva** [comment]
Yes it was :)
