### ISSUE TITLE
Menu item type > Pop up window

### ISSUE THREAD

**Issue by KOMET38** [joomla/joomla-cms#7299]
#### Steps to reproduce the issue
Clicking on Menu item > Menu item type > Pop up window is opened

#### Expected result
Pop up window is freely movable

#### Actual result
Pop up window is fixed at the top of the screen

#### System information (as much as possible)

Joomla 3.4.2

**Comment by brianteeman** [comment]
All the "pop-ups" are modal windows and as they are intended to be the only thing you need to see there is no need to move it. That's the way that a modal works.

Why would you want to move it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7299">issues.joomla.org/joomla-cms/7299</a>.</sub>

**Comment by KOMET38** [comment]
Hi,

to make it more clearly I send you screenshots of the behavior in Joomla 3.4.1 and the new style of 3.4.2.. 

I don`t know if that style was your intention but for me the usability for pop up window of Menu style item in 3.4.2 is a little bit strange.






The way pop up window appears in Joomla 3.4.1:




The way pop up window appears in Joomla 3.4.2:


Am 01.07.2015 um 12:20 schrieb Brian Teeman <notifications@github.com>:

**Comment by brianteeman** [comment]
The screenshots did not work<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7299">issues.joomla.org/joomla-cms/7299</a>.</sub>

**Comment by RonakParmar** [comment]
I have compared both joomla 3.4.1 and joomla 3.4.2 menu item type pop-up.
Functionality wise, both are same, but design wise both are different.
I have found another issue, in joomla 3.4.2 while clicking on other tab in menu item pop-up, already open tab will not be close.
In joomla 3.4.1 while clicking on other tab in menu item pop-up, already open tab will be close.
please see the screen dump.![screen shot 2015-07-01 at 07 53 03](http://issues.joomla.org/uploads/1/e077e291b1978389b658d41e2c68ef55.png)![screen shot 2015-07-01 at 07 53 05](http://issues.joomla.org/uploads/1/1493ce370eed2e22e63da4547b4a065e.png)
![screen shot 2015-07-01 at 07 56 38](http://issues.joomla.org/uploads/1/bf4f2ec2a36260dc37e8d842e4c89dc2.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7299">issues.joomla.org/joomla-cms/7299</a>.</sub>

**Comment by mbabker** [comment]
Part of the design change is intentional.  There's effort to shift our modals from the MooTools based SqueezeBox to Bootstrap's own.

**Comment by brianteeman** [comment]
Other than the design change which is intentional as @mbabker stated what problem is there. I am afraid I dont follow you on that<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7299">issues.joomla.org/joomla-cms/7299</a>.</sub>

**Comment by opfeifer** [comment]
I have MUCH WORSE issue with the same Popup window in 3.4.3: it VANISHES after half a second!

I use Joomla 3.4.3 (!) and both Firefox 39.0 and Safari 5.1 show the same behavior: The Menu Item Type Selector window comes in, but vanishes again a split second later.

I found a solution to this problem, in a post from two years ago: There seems to be one excess comma in line 335 of  /media/system/js/modal-uncompressed.js  Deleting the comma solved the issue for me!

Here's the original post: http://forum.joomla.org/viewtopic.php?f=728&t=771934&p=3316424#p2993198<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7299">issues.joomla.org/joomla-cms/7299</a>.</sub>

**Comment by brianteeman** [comment]
@opfeifer I think you already commented elsewhere but this is a bug in redmigrator 

This Issue is now being closed as an intended change<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7299">issues.joomla.org/joomla-cms/7299</a>.</sub>

**Comment by opfeifer** [comment]
Um, can you elaborate a bit, or add a description? Does this mean redmigrator corrupts the above mentioned file (but the original joomla package contains the same file!) or is the bug that makes the window close somewhere else? Sorry for asking, but I could not find the info anywhere.

**Comment by brianteeman** [comment]
Based on comments elsewhere there is a conflict if you have redmigrator installed
