### ISSUE TITLE
Edit article front-end, featured (frontpage) setting is not saved well

### ISSUE THREAD

**Issue by Buro26-Vincent** [joomla/joomla-cms#7300]
#### Steps to reproduce the issue
1. Login front-end
2. Edit article
3. Set the option Featured to Yes
4. Save the article

#### Expected result
1. That the article shows up in special article overview (back-end)

#### Actual result
1. In Article overview (back-end) the article get's a "star"
2. In Special article overview (back-end) the article is not shown

#### System information (as much as possible)
Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT 

#### Additional comments
- The featured setting is correctly saved in the table #__content
- The featured stetting is not saved in the table #__content_frontpage
- In back-end saving featured setting works
- In front-end saving featured setting doesn't work

**Comment by brianteeman** [comment]
I have tried to replicate this in 3.4.1 and 3.4.2 and I can not<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7300">issues.joomla.org/joomla-cms/7300</a>.</sub>

**Comment by zero-24** [comment]
BTW if i understand it correct `#__content_frontpage` has nothing to do with featured only with ordering :smile: 

See: https://github.com/joomla/joomla-cms/blob/3.4.2/installation/sql/mysql/joomla.sql#L359-368

**Comment by Buro26-Vincent** [comment]
Ok, I'll show you:

The Featured article overview in back-end doesn't display Fetured items created from front-end:
![joomla - featured articles](https://cloud.githubusercontent.com/assets/11872342/8453507/a4e77962-1ff5-11e5-8c58-7f60e6b22dd3.JPG)

The Article overview however shows the star:
![joomla - articles](https://cloud.githubusercontent.com/assets/11872342/8453611/80d1c19e-1ff6-11e5-9421-58df3bd43fe4.JPG)

When creating a menu item and showing the Featured articles in front-end, they won't show up.

For back-end part of saving Featured setting:
See https://github.com/joomla/joomla-cms/blob/3.4.2/administrator/components/com_content/models/article.php#L538-L545 

For front-end part of saving Featured setting:
See https://github.com/joomla/joomla-cms/blob/3.4.2/components/com_content/models/form.php#L178-L195

When I add before form.php#L178-L195:
```
if (isset($data['featured'])) {
  $this>featured($data['id'], $data['featured']);
}
```
It works like it should. But maybe there's a better place to correct this.

**Comment by Bakual** [comment]
Can you create a PR with your code proposal? Then it could be tested.
See https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests if you don't know what a PR is :smile:

**Comment by RonakParmar** [comment]
I have tried to produce this issue in joomla 3.4.1 but not able to produce it.
I can see the featured article in featured article view. please see the screen dump.![screen shot 2015-07-01 at 06 58 56](http://issues.joomla.org/uploads/1/319451a362ba10a346a30b7342365229.png)![screen shot 2015-07-01 at 06 58 57](http://issues.joomla.org/uploads/1/2eca8cfa1277df2ef73a0c2c235e7ac8.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7300">issues.joomla.org/joomla-cms/7300</a>.</sub>

**Comment by brianteeman** [comment]
Dont know what to say - I have no problem or am I doing something different? Here is a video

https://www.dropbox.com/s/psh7hmep44144zf/featured.mp4?dl=0

**Comment by RonakParmar** [comment]
I have watched this video and got the same output as per the video.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7300">issues.joomla.org/joomla-cms/7300</a>.</sub>

**Comment by Buro26-Vincent** [comment]
Thanks, for all the answers, that looks like the problem is not in Joomla itself. Excuse me for that, I have to look further into it. I think it's a plugin problem.

**Comment by brianteeman** [comment]
I shall close it at this time. If you do find it was a Joola issue feel free to post here again and it can be re-opened
