### ISSUE TITLE
Broken Batch modal layout

### ISSUE THREAD

**Issue by chmst** [joomla/joomla-cms#7301]
Go to Com_content. You need > 5 several categories and alt least one article.
Activate the Batch icon
In 3.4.1 the dropdown of categories is visible in ful length

In 3.4.2 the Dropdown is cut 

![screen shot 2015-07-01 at 05 17 01](http://issues.joomla.org/uploads/1/fa5f3243c9bf26fd41b38beac3e6591e.png)
See the screens. a small patch resolves the problem. 

![screen shot 2015-07-01 at 05 17 13](http://issues.joomla.org/uploads/1/e176eceb6514bbd7a733c6cf4b20dacd.png)

**Comment by brianteeman** [comment]
Closed as we have a PR #7302 
You do NOT need to create an issue and a PR. The PR does it automatically<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7301">issues.joomla.org/joomla-cms/7301</a>.</sub>

**Comment by Jay-Jay-OPL** [comment]
Guys it seems that the issue explained above still occurs with the responsive menu starting with Joomla 3.4.3.  Where if the menu is long, it will be cut off.  These two threads explain the issue and include screenshots: 

http://forum.joomla.org/viewtopic.php?f=706&t=892016

http://forum.joomla.org/viewtopic.php?f=706&t=891691<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7301">issues.joomla.org/joomla-cms/7301</a>.</sub>
