### ISSUE TITLE
Language definitions not present in the message after updating

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#7306]
#### Steps to reproduce the issue
Update a Joomla 3.4.1 to 3.4.2 with the Extension Manager > Upload & Install Joomla Extension

#### Expected result
A message translated correctly

#### Actual result
The green message displayed is correctly 
Message
Installing file was successful.

but below it there's a language definition not translated:
 FILES_JOOMLA_XML_DESCRIPTION 

in some case  appears also this string
FILES_JOOMLA_ERROR_MANIFEST

**Comment by brianteeman** [comment]
I can confirm the issue BUT if i remember correctly the bug that causes
this was resolved in the 3.4.2 release so wont be seen in future updates

On 1 July 2015 at 17:39, ste <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Update a Joomla 3.4.1 to 3.4.2 with the Extension Manager > Upload &
> Install Joomla Extension
> Expected result
>
> A message translated correctly
> Actual result
>
> The green message displayed is correctly
> Message
> Installing file was successful.
>
> but below it there's a language definition not translated:
> FILES_JOOMLA_XML_DESCRIPTION
>
> in some case appears also this string
> FILES_JOOMLA_ERROR_MANIFEST
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7306>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
This was the PR in 3.4.2: https://github.com/joomla/joomla-cms/pull/6532 That should fix that issue for the next update. I guess you can test this if you try the upload / install the 3.4.2 package again but i'm not 100% sure else you can update the XML to label the zip file as 3.4.3 for testing ;)

**Comment by brianteeman** [comment]
As this has been resolved as stated above I am closing this at this time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7306">issues.joomla.org/joomla-cms/7306</a>.</sub>
