### ISSUE TITLE
Regression - cannot create smart search menu link

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#7309]
#### Steps to reproduce the issue
Create a new menu item for Smart Search

#### Expected result
Menu link created

#### Actual result
Invalid field: Date Filters
Invalid field: Advanced Search
Invalid field: Expand Advanced Search

First reported http://forum.joomla.org/viewtopic.php?f=706&t=890725&p=3314024#p3314024

**Comment by brianteeman** [comment]
Possibly #7308 has the same root cause<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7309">issues.joomla.org/joomla-cms/7309</a>.</sub>

**Comment by zero-24** [comment]
Closing as we have a PR at https://github.com/joomla/joomla-cms/pull/7312
