### ISSUE TITLE
"Default Access Level" is not applied when creating new article - it's always Access = "Guest"

### ISSUE THREAD

**Issue by michal-jomsocial** [joomla/joomla-cms#7314]
#### Steps to reproduce the issue

1. Browse to Backend -> System -> Global configuration -> Site
2. Set "Default Access Level" to any (e.g "Public"): http://prntscr.com/7nv1ix
3. Click "Save & Close"
4. Browse to Backend -> Content -> Article manager
5. Click "New"
6. Check "Access" at left column

#### Expected result

Access in articles should be follow settings in Global Configuration, in this case it should by "Public" by default.

#### Actual result

Access is set to "Guest" by default: http://prntscr.com/7nv29a

#### System information (as much as possible)

PHP Built On: Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
Database Version: 5.1.73-log
Database Collation: utf8_polish_ci
PHP Version: 5.4.42
Web Server: Apache
WebServer to PHP Interface: cgi-fcgi
Joomla! Version: Joomla! 3.4.2 Stable [ Ember ] 30-June-2015 12:00 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:34.0) Gecko/20100101 Firefox/34.0 

#### Additional comments

It happened after upgrade from Joomla! 3.4.1 to 3.4.2

**Comment by brianteeman** [comment]
Thanks for reporting this. I am however closing it as we already have a solution #7313 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7314">issues.joomla.org/joomla-cms/7314</a>.</sub>
