### ISSUE TITLE
Maintenance message twice shown after update to 3.4.2

### ISSUE THREAD

**Issue by MartijnMaandag** [joomla/joomla-cms#7315]
#### Steps to reproduce the issue
Go to the main administrator page
Look at the left bottom messages for Maintenance Joomla and Extnesions they are shown twice.

#### Expected result![screen shot 2015-07-02 at 05 01 11](http://issues.joomla.org/uploads/1/8092402902b514021e28fbf607863419.png)

One message for Joomla and one for extensions.

**Comment by zero-24** [comment]
Clean your Browser cache it is a know issue see: https://docs.joomla.org/J3.x:Duplicate_Maintenance_Info

**Comment by zero-24** [comment]
Thanks for reporting.
