### ISSUE TITLE
Codemirror editor doesn't work in fullscreen mode

### ISSUE THREAD

**Issue by e404-gh** [joomla/joomla-cms#7321]
<h4>Steps to reproduce the issue</h4>
<p>Update Joomla! from 3.4.1 to 3.4.2</p>

<h4>Expected result </h4>
<p>Codemirror editor run in fullscreen mode with shortcut (default F10) </p>

<h4>Actual result </h4>
<p>Editor Codemirror doesn't go in fullscreen mode and overlaps the page or adapts to the contents of the text area</p>

<h4>System information</h4>
<p>3.4.2 (Joomla Platform 13.1.0 Stable) , PHP 5.4.36,  5.5.5-10.0.15-MariaDB-wsrep, nginx/1.6.2   </p>

<h4>Additional comments</h4>
<p>It would seem a problem of css code.<br />
If we compare codemirror.min.css file versions (media/editors/codemirror/lib/codemirror.min.css), content in Joomla! 3.4.1 and 3.4.2, seems missing some line of code relating to class "CodeMirror-fullscreen" (and maybe also something else)</p>

**Comment by Fedik** [comment]
can confirm,
in 3.4.1 F10 toggle "fullscreen" , in 3.4.2/3.4.3 does not

**Comment by Fedik** [comment]
@okonomiyaki3000 maybe you know what happened with Codemirror  since 3.4.1? :wink:

ps: #7284 does not fix the problem

**Comment by okonomiyaki3000** [comment]
Hmm. I'll have a look.

**Comment by okonomiyaki3000** [comment]
I see the problem. I'll have a fix ready soon.

**Comment by okonomiyaki3000** [comment]
Here you go #7325

**Comment by e404-gh** [comment]
@okonomiyaki3000 
okay, now CodeMirror run in full screen mode, we hope that the fix is included in the next version of Joomla!

**Comment by okonomiyaki3000** [comment]
@e404-gh Until a release is out with this fix, there are a couple of ways you could fix it on your sites if you don't feel like waiting. 

You can implement the fix exactly as I have, by editing `plugins/editors/codemirror/codemirror.php` add this on line 73 (really anywhere in the `onInit` function):
```php
JHtml::_('stylesheet', $this->basePath . 'lib/addons.min.css');
```

Alternatively, you could append the contents of 
`media/editors/codemirror/lib/addons.min.css` to `media/editors/codemirror/lib/codemirror.min.css`
and
`media/editors/codemirror/lib/addons.css` to `media/editors/codemirror/lib/codemirror.css`

**Comment by zero-24** [comment]
Closing as we have a RTC PR. Thanks!

**Comment by andre-merzky** [comment]
The issue seems to have reappeared in `Joomla! 3.6.0 Stable` (or earlier), and the fixes described above don't seem to solve the issue at this point.  Do you happen to have any advice?  Thanks!

**Comment by brianteeman** [comment]
Its working perfectly for me - please use the forum for support http://forum.joomla.org

**Comment by andre-merzky** [comment]
thanks, will do!
