### ISSUE TITLE
language tag removed from url 

### ISSUE THREAD

**Issue by alxttr** [joomla/joomla-cms#7324]
#### Steps to reproduce the issue

Hi,

I set up a joomla multilanguage site. Categories, articles, menus, menus modules are per language. Joomla language switcher published for all language. Multilangual status checker published in backend (no flags from it). Published Default Home pages (including 1 assigned to language "All").

But when switching from the main language, the language tag (en,es..) is removed from url after browsing menu items other than the default of the chosen language. 

Main language: en
Additional language: es

#### Expected result
mysite.com/es/cat-es

#### Actual result
mysite.com/cat-es

#### System information (as much as possible)
Joomla 3.4.3

#### Additional comments
Changing to es it displays the correct page mysite.com/es. Clicking on cat-es menu item it goes to mysite.com/cat-es instead of mysite.com/es/cat-es. As well the html language tag goes to lang="en-gb"

**Comment by infograf768** [comment]
Is it a new site made with 3.4.3 or an updated site?

**Comment by alxttr** [comment]
It's an update from Joomla 3.4.2.
url to the site: romanians.co/carenavig
Here are the screenshots:
![plugin manager system language filter](https://cloud.githubusercontent.com/assets/788522/8495539/40aa7c8e-2166-11e5-9b0a-9b28b9134947.png)
![language manager content languages](https://cloud.githubusercontent.com/assets/788522/8495540/40af628a-2166-11e5-8a78-5a35d7b88cd8.png)

**Comment by infograf768** [comment]
Looks like this is related to your menu system or mistake in the language tag for these menu items.

I suggest you test with the default Protostar template and joomla menus

**Comment by infograf768** [comment]
Ot is also possible that JReviews is not multilingual compatible or need some specific settings

**Comment by europower** [comment]
This looks very similar to an issue i posted on the forum (http://forum.joomla.org/viewtopic.php?f=711&t=890828)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7324">issues.joomla.org/joomla-cms/7324</a>.</sub>

**Comment by infograf768** [comment]
I found out that the original issue is related to the plugin: System - JReviews SEF.
Unpublishing it solves the issue on a site I tested.

**Comment by alxttr** [comment]
Hi,
Yes, you are right. It did the trick. So it's not a joomla issue. 
Thx for your time and sorry for the trouble.
