### ISSUE TITLE
can't login to administrator. No error

### ISSUE THREAD

**Issue by dbegit** [joomla/joomla-cms#7326]
#### Steps to reproduce the issue
_server1_: backup database and joomla files
**mysqldump joomla -uroot -p > /tmp/joomla.sql**
**tar czvf joomla.tar.gz joomla**

When I can connect to administrator in server1
with a wrong login/password, there is a warning in yellow
"Warning
Username and password do not match or you do not have an account yet."
I can connect to administrator with a good login/pass
The front-end is OK (database connection OK)

_server2_: restore database and joomla files to another server
**mysql -u root -p joomla < /tmp/joomla.sql**
**tar xzvf joomla.tar.gz**
I can't login to administrator with good login/password. it reloads administrator/index.php with the login form.
And with wrong login/password, there is no warning!!!
The front-end is OK (database connection OK)

#### Expected result
the same result as server1 on server2.

#### Actual result
Does joomla configuration depends on hostname?

#### System information (as much as possible)
mysql 5.6.25
php 5.4.16
joomla 3.4.1

#### Additional comments
Thanks for your help!

**Comment by smz** [comment]
@dbegit Sorry, but you aren't reporting an issue: you're asking a support question, and this should be done in http://forum.joomla.org/

GitHub issues and the http://issues.joomla.org site are meant for reporting (new) issues of which you have a reasonable certainty...

Hint: Personally I'd use Akeeba Backup for that, and there are many very good reasons...
