### ISSUE TITLE
Menu of type Alias does not work when pointing to  external URL menus

### ISSUE THREAD

**Issue by ghasler** [joomla/joomla-cms#7334]
You currently can't use an Alias Menu that points to and External URL type menu.  This is an important feature since it allows you to use short URLs for long URLS which is a great for SEO and other reasons.  For example you can use http://example.com/index.php/shortname  instead of http://example.com/index.php/component/jak2filter/?Itemid=126&isc=1&category_id=1,14&xf_9=3&xf_12=7&xf_8=3. 

Reproduction:

1.   Create a Menu (EX)  of type 'External URL' and put any URL link into the field (internal or external ).  This menu does not have to be visible. 

2.   Create another menu (AL) of type Alias that points to the above menu (EX)

3.    Selecting menu (AL) results in a 404 not found

Expected behavior is that it would go to the URL defined in EX.

**Comment by brianteeman** [comment]
I can confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7334">issues.joomla.org/joomla-cms/7334</a>.</sub>

**Comment by brianteeman** [comment]
> Call stack
#	Function	Location
1	JApplicationCms->execute()	/Applications/MAMP/htdocs/Joomla_3.4.2-Stable-Full_Package/index.php:45
2	JApplicationSite->doExecute()	/Applications/MAMP/htdocs/Joomla_3.4.2-Stable-Full_Package/libraries/cms/application/cms.php:252
3	JApplicationSite->dispatch()	/Applications/MAMP/htdocs/Joomla_3.4.2-Stable-Full_Package/libraries/cms/application/site.php:230
4	JComponentHelper::renderComponent()	/Applications/MAMP/htdocs/Joomla_3.4.2-Stable-Full_Package/libraries/cms/application/site.php:191
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7334">issues.joomla.org/joomla-cms/7334</a>.</sub>

**Comment by bertmert** [comment]
>  it allows you to use short URLs for long URLS

Please clarify before I start a PR (that just would fix the 404 error by inheriting the URL in mod_menu).   
I don't see how to use this for short URLS and SEO. That would be a router faeture request.

**Comment by brianteeman** [comment]
Thank you for your suggestion but it has been decided that this is not something that will be included in the core of Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7334">issues.joomla.org/joomla-cms/7334</a>.</sub>
