### ISSUE TITLE
[Regression] Delete button on the media manager don't work after update to 3.4.2/3

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#7336]
#### Steps to reproduce the issue

Go to com_media
select (using the checkboxes at the images) some images
try to hit the delete button.

#### Expected result

In 3.4.1 all images gets deletet.

#### Actual result

In 3.4.2/3 nothing happens

#### Additional comments

The delete button can  be found here:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_media/views/media/view.html.php#L142-149

That calls a layout: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_media/layouts/toolbar/deletemedia.php

So that button call this: https://github.com/joomla/joomla-cms/blob/staging/media/media/js/mediamanager.js#L39

But I'm not sure what is the next step or what fails as it looks correct for me.

#### References (german)
http://www.joomla-bugs.de/forum/index.php/topic,677.0.html
and
http://forum.joomla.de/index.php/Thread/535-kleines-Problem-mit-Medien-Manager-bei-Joomla-3-4-3/

**Comment by zero-24** [comment]
The Javascript error I get is: `Uncaught ReferenceError: form is not defined`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7336">issues.joomla.org/joomla-cms/7336</a>.</sub>

**Comment by smz** [comment]
... we have #7338 ...
