### ISSUE TITLE
Missing link in case $modMenuId

### ISSUE THREAD

**Issue by minonario** [joomla/joomla-cms#7339]
Hi,

I got me with the following error in my application after update to version 3.4.3. I go to the menus list and in the column Linked Modules appears Notice: Undefined variable: link in .... /administrator/components/com_menus/views/menus/tmpl/default.php on line 207

When i check after the line 200 I realized that in creating the link to add menu module is the variable $link and is not previously defined, i guess is that the error. My solution was to assign the JRoute to the $link variable before the generation of the link.

Attach an image.

I hope this help you.

Greetings, Jose

![screen shot 2015-07-03 at 9 50 55 pm](https://cloud.githubusercontent.com/assets/10578976/8506118/9c226b86-21ce-11e5-9af5-94f5977afb21.png)

**Comment by zero-24** [comment]
See here for a PR https://github.com/joomla/joomla-cms/pull/7344<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7339">issues.joomla.org/joomla-cms/7339</a>.</sub>
