### ISSUE TITLE
Save buttons not working after 3.4.3 Upgrade

### ISSUE THREAD

**Issue by alexandrucotioras** [joomla/joomla-cms#7347]
#### Steps to reproduce the issue
Edit article, switch between editors, update global configuration.

#### Expected result
Page should reload and a 'Configuration updated' message should appear.

#### Actual result
Cannot save articles in Isis/Hathor template. Cannot switch between editors. Multiple buttons affected.

#### System information (as much as possible)
Joomla 3.4.3 (Official)
PHP 5.5.9-1ubuntu4.9
Mysql 5.5.42-MariaDB-1~trusty-wsrep
Nginx 1.8

#### Additional comments
Cleared cache in Joomla and Cloudflare.
Tried with Firefox and Chrome, both regular and in-private. Cleared cache and both, to no effect.
Downloaded ZIP package and copied over the install, issue still persists.
Restored files from old backup, no luck. 
Can you please advise the path of the file which should be edited (template.css or something)?   I looked into the templates and system folder and cannot find that file, nor isis/thor directory.
My setup is fine and this is not a cache related issue as it was working fine last week.

**Comment by brianteeman** [comment]
> Can you please advise the path of the file which should be edited (template.css or something)? I looked into the templates and system folder and cannot find that file, nor isis/thor directory.

What file were you looking for

**Comment by onimaro** [comment]
core.js problem in firebug 
TypeError: t is null
	

...t=document.getElementById("adminForm")),e&&(t.task.value=e),t.noValidate=!n;var ...

**Comment by alexandrucotioras** [comment]
Hi Brian,

I am looking for this variable JHTML::_('behavior.mootools';). It should be
in template.css, but I cannot find the isis/hathor template folder for the
backend. I tried using grep last night, got no result.
I already tried replacing /libraries/cms/html/behavior.php from github (#
6319) last night, with the same result.
Do you know if the mo-tools is already deprecated and it might cause this
issue?
Thanks for your quick response,

Regards,
Alexandru Cotioras

**Comment by alexandrucotioras** [comment]
Thank Onimaro for the output.
Do you know by chance how can I amend this?

**Comment by alexandrucotioras** [comment]
This is what happens when I try to revert prior to 3.4:

*Fatal error*: JUser::getParam(): The script tried to execute a method or
access a property of an incomplete object. Please ensure that the class
definition &quot;Joomla\Registry\Registry&quot; of the object you are
trying to operate on was loaded _before_ unserialize() gets called or
provide a __autoload() function to load the class definition in
*/var/www/libraries/joomla/user/user.php* on line *286*

I will google this in the meantime, just to let you know that I have fully
disabled Cloudflare and I am switching between various browsers to see if
it helps

**Comment by alexandrucotioras** [comment]
Hi All,

Issue seems to be sorted by downgrading to 3.2.1. I would suggest taking a
look at the bug though for future reference.
Please let me know if you need further details.

Kind regards

**Comment by alexandrucotioras** [comment]
Please disregard my previous post.
It seems I got where I started from. On 3.2.1, Save buttons work in Hathor,
but not in Isis.

**Comment by Fedik** [comment]
> downgrading to 3.2.1

it is very bad idea ...
I think there something really wrong with your installation ... which additional extensions do you use?

**Comment by alexandrucotioras** [comment]
Well...I have a lot:
Akeeba for backup
Cloudflare plugin
DMC Firewall
Editors: JCE/Rokpad
Scriptmerge
Clicksor
Komento
Mobile -Simple
Phoca GAE
Async social buttons
AIB
...plus others which are disabled for the moment. I remember they were all
working fine before.
Do you suggest disabling all of them? I think they are mostly designed for
the frontend, but I will give it a try.

**Comment by Fedik** [comment]
> I have a lot

that the answer on your issue :wink:
yes, you can try disable they one by one and check when the site will back to normal work,
also this can be helpfull  https://groups.google.com/forum/#!topic/joomla-dev-general/pJ8gi8LypuE in theory

**Comment by alexandrucotioras** [comment]
Hi Brian,

Thank you for the suggestions.
Although I have disabled all of the plugins as suggested, that didn't help.
The problem is related to Isis template. Fortunately, there is a
workaround. there is a template on Github which uses Bootstrap 3 style.
https://github.com/asika32764/joomla-bootstrap3-isis-template/releases
As long as the template works, I am happy enough.
I am disappointed though that motools is not working anymore, which I
believe it is the root cause of my issue. I prefer this workaround due to
the limited time and lack of programming skills.
Anyway, thanks for the support (I wasn't expecting someone to reply on
Sunday) and have a nice one.

**Comment by zero-24** [comment]
So we can close here @alexandrucotioras ?

**Comment by alexandrucotioras** [comment]
This case yes. As long as I have something in place that allows me to
publish, yes...go for it. Thank you all for your time
