### ISSUE TITLE
JPluginHelper::getPlugin($type, $plugin) dosent return id

### ISSUE THREAD

**Issue by shamsbd71** [joomla/joomla-cms#7355]
i have sent a pull request previously about making a modal edit layout for plugin and using that we can improve joomla user experience.

like: com_finder, com_redirect. they had settings from plugin and it show notice.
so to get plugin edit we need to create a function to get only plugin id.
so if i make it to return plugin id, it would be easy.

https://github.com/joomla/joomla-cms/pull/7259

this pull request include JPluginHelper update

**Comment by zero-24** [comment]
Thanks @shamsbd71 as we have that fix into your PR #7259 i close here. We don't longer need a issue if we have a pull ;) Thanks :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7355">issues.joomla.org/joomla-cms/7355</a>.</sub>
