### ISSUE TITLE
found problems in language files

### ISSUE THREAD

**Issue by aaleksanyants** [joomla/joomla-cms#7358]
1. admin/en-GB.com_config.ini
COM_CONFIG_FIELD_DEBUG_LANG_DESC="Select whether the debugging indicators (&lt;bold>**...**&lt;/bold>) or (&lt;bold>??...??&lt;/bold>) for the Joomla Language files will be displayed. Debug Language will work without Debug System being activated, but you will not get the additional detailed references that will help you correct any errors."
Comment: there are no BOLD tags in HTML spec, should be either STRONG or B
2. site/en-GB.tpl_beez3.sys.ini
TPL_BEEZ3_XML_DESCRIPTION="Accessible template for Joomla! Beez, the HTML 4 version."
Comment: Current Beez3 version is HTML5 based, this description remained unchanged since Beez_20 which really was HTML4 based, but things have changed since that...

**Comment by infograf768** [comment]
Agree. Can you make a PR?

**Comment by aaleksanyants** [comment]
Pardon, infograf768, would you please describe the meaning of making PR?

**Comment by brianteeman** [comment]
A pull request is the code to make the changes you proposed happen

See
https://docs.joomla.org/My_first_pull_request_to_Joomla!_on_Github
or as this is a simple change
https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

If you have problems just post back here and someone can help you OR make
the PR for you

On 7 July 2015 at 09:14, Andrey Aleksanyants <notifications@github.com>
wrote:

> Pardon, infograf768, would you please describe the meaning of making PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7358#issuecomment-119113955>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by aaleksanyants** [comment]
Seems I could do that...

**Comment by brianteeman** [comment]
Closing as we have pull requests for this - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7358">issues.joomla.org/joomla-cms/7358</a>.</sub>
