### ISSUE TITLE
HTML tags to be displayed as text in language files - possible issues

### ISSUE THREAD

**Issue by aaleksanyants** [joomla/joomla-cms#7367]
This report needs to be checked by more skilled user who knows if where are the following strings displayed. Might be the strings are processed to get displayed as text, but i feel there should be implemented an escape to show them properly, ie. &lt;figure> -> &amp;lt;figure&amp;gt;, &lt;img> -> &amp;lt;img&amp;gt; etc. Here are the strings:

admin/en-GB.com_media.ini	COM_MEDIA_ALIGN_DESC	"This will apply the classes 'pull-left', 'pull-center' or 'pull-right' to the '&lt;figure>' or '&lt;img>' element."
admin/en-GB.com_media.ini	COM_MEDIA_CAPTION_CLASS_DESC	"This will apply the entered class to the '&lt;figcaption>' element. For example: 'text-left', 'text-right', 'text-center'."
site/en-GB.com_media.ini	COM_MEDIA_ALIGN_DESC	"This will apply the classes 'pull-left', 'pull-center' or 'pull-right' to the '&lt;figure>' or '&lt;img>' element."
site/en-GB.com_media.ini	COM_MEDIA_CAPTION_CLASS_DESC	"This will apply the entered class to the '&lt;figcaption>' element. For example: 'text-left', 'text-right', 'text-center'."

**Comment by brianteeman** [comment]
They are displayed correctly

![vge0](https://cloud.githubusercontent.com/assets/1296369/8545446/b38662f2-24a6-11e5-8c62-69ac2bc4dccb.png)

**Comment by aaleksanyants** [comment]
I tried to replace with the appropriate HTML entities and they still do. Because there are too many places in language strings with HTML tags inserted just to change the appearance, how correct is to restrict their direct usage in a single module only because to display them as text?

**Comment by infograf768** [comment]
>how correct is to restrict their direct usage in a single module only because to display them as text?

Can you explain better what you suggest? The specific ones above are not html tags but pure text.

**Comment by aaleksanyants** [comment]
I would suggest to replace <figure> -> &lt;figure&gt;, <img> -> &lt;img&gt; etc.for not to prevent other HTML tags (if any) to serve as HTML tags instead of displaying them as text.

**Comment by infograf768** [comment]
TBH, all has been working fine until now the way we have been doing with the few we have.
Have you remarked other occurences than these few ones?

**Comment by brianteeman** [comment]
If they work (and they do) then we should leave it as it is - it is much
more readable and makes the life of translators easier

On 8 July 2015 at 09:57, infograf768 <notifications@github.com> wrote:

> TBH, all has been working fine until now the way we have been doing with
> the few we have.
> Have you remarked other occurences than these few ones?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7367#issuecomment-119504556>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
I would leave them unescaped in the language files as we have currently. It makes translations much easier.
If we need to escape them, we can (and already do) escape them when we need it. PHP has a command for that :smile:
