### ISSUE TITLE
Joomla installation is broken

### ISSUE THREAD

**Issue by javigomez** [joomla/joomla-cms#7388]
The error has started to happen today. So it must be related with a recent merge 

![screen shot 2015-07-09 at 05 41 53](http://issues.joomla.org/uploads/1/6d577b8bd259afb715d1f850c27af9e4.png)

The error that appears in the browser console is:

![screen shot 2015-07-09 at 05 42 36](http://issues.joomla.org/uploads/1/f79632ae4b8e1122a67ee68c92182395.png)

**Comment by brianteeman** [comment]
You posted the same image twice :)

**Comment by javigomez** [comment]
# Testing instructions
Download joomla from staging: https://github.com/joomla/joomla-cms/pull/6512

Try to install:
- fill the details of the first screen and click Next
- installation will halt.
- check your browser console you will see the error<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7388">issues.joomla.org/joomla-cms/7388</a>.</sub>

**Comment by zero-24** [comment]
Closing as we have a pull by @Fedik see: https://github.com/joomla/joomla-cms/pull/7391<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7388">issues.joomla.org/joomla-cms/7388</a>.</sub>
