### ISSUE TITLE
Backend update messages: Sting is shown twice

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#7389]
#### Steps to reproduce the issue

- Install Joomla  3.4.3
- Go to backend control panel
- Look at the maintenance shotcuts on the bottom / left.

#### Expected result

Only one line 'Joomla! is up-to-date'
Only One line 'Updates available'

#### Actual result

Two (duplicate) lines: 'Joomla! is up-to-date Joomla! is up-to-date'
Two (duplicate) lines: 'Updates available Updates available'

#### System information (as much as possible)
Joomla 2.4.3 (Dutch language)
Linux / Apache
PHP 5.4.42

#### Additional comments

![screen shot 2015-07-09 at 05 50 39](http://issues.joomla.org/uploads/1/15ff69d2752470900067e9def0657472.png)

In the HTML source code:

<li id="plg_quickicon_joomlaupdate">

    <a href="index.php?option=com_joomlaupdate">

        Joomla! is up-to-date

        Joomla! is up-to-date

    </a>

</li>
<li id="plg_quickicon_extensionupdate">

    <a href="index.php?option=com_installer&view=update&task=update.find&8d2fc84d26417676eb93c73550fdeffe=1">
        <span class="icon-asterisk">
            ::before

            Er zijn updates beschikbaar!

            <span class="label label-important"></span>
        </span>
        <span class="j-links-link">

            Er zijn updates beschikbaar!

            <span class="label label-important">

                1

            </span>
        </span>
    </a>

</li>

**Comment by zero-24** [comment]
@jjnxpct this is a known issue and will be fixed with 3.4.4 / 3.5.0 see: https://docs.joomla.org/J3.x:Duplicate_Maintenance_Info

There is also the fix ;)

**Comment by jjnxpct** [comment]
OK thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7389">issues.joomla.org/joomla-cms/7389</a>.</sub>

**Comment by zero-24** [comment]
No Problem :smile: Better report it twice than never ;)

**Comment by Glenn-iFactory** [comment]
Didn't solve the problem? Have upgraded to 3.4.4 and checked to make sure the upgrade updated the file correctly (it did) yet the issue persists. Also upgraded to 3.4.5 today with no change (given 3.4.5 is a security update that's no surprise).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7389">issues.joomla.org/joomla-cms/7389</a>.</sub>

**Comment by Bakual** [comment]
Make sure you clear the browser cache. You may have had a cached JavaScript there.

**Comment by Glenn-iFactory** [comment]
Yeah that must be the problem. Have moved to a staging environment and it didn't have that issue. Thanks!
