### ISSUE TITLE
Backend code editing: unable to view in full screen mode in 3.4.3

### ISSUE THREAD

**Issue by auditorj** [joomla/joomla-cms#7400]
-Before updating to 3.4.3, everything works fine, and after updating, back-end layout code editing was unable to view in full screen whether its ISIS or Hathor.

-Expected result: to view in full screen mode (f10) when editing the layout code.

-**Actual result:** The editing screen just expands downward without scroll bars appearing, and not full screen.![screen shot 2015-07-09 at 20 34 27](http://issues.joomla.org/uploads/1/505cfdff4abedbc12115be4faeba234e.png)

-System information:
Database Version	5.5.35-MariaDB
Database Collation	latin1_swedish_ci
PHP Version	5.4.16
Web Server	Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips mod_fcgid/2.3.9 PHP/5.4.16 mod_wsgi/3.4 Python/2.7.5
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.4.3 Stable [ Ember ] 2-July-2015 16:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36

-Additional comments: tried searching to fix issue but unable to find solution.

**Comment by zero-24** [comment]
Hi @auditorj ,

this is a know issue with 3.4.3 see the FAQ for the fix https://docs.joomla.org/J3.x:Codemirror_editor_fullscreen_mode :smile: 

As this is allready fixed I close this here.

**Comment by JoshuaLewis** [comment]
Thanks zero-24, I'm quite pleased to hear a fix for this has been made. :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7400">issues.joomla.org/joomla-cms/7400</a>.</sub>

**Comment by zero-24** [comment]
Yes. And it is also a just simple one ;) https://github.com/joomla/joomla-cms/pull/7325.diff

**Comment by auditorj** [comment]
Fixed :+1: 

Thank you @zero-24
