### ISSUE TITLE
@media print     printing urls and not able to stop from printing urls

### ISSUE THREAD

**Issue by darylkuchay** [joomla/joomla-cms#7407]
#### Steps to reproduce the issue
parrotfunzone.com, any article. Use the print icon at base of article and then click print from popup dialog. In the final preview before sending to printer we see urls next to each picture. 

@media print {
  a[href]:after {
    content: none !important;
  }
}

We have added the above snippet to all css documents that have "@media print" tags but urls still print and show on preview. This may be okay for development however we cant have end users seeing this as we are printing coloring books, certificates and more from our site to end users. 
#### Expected result

Joomla should have something in the admin interface for controlling printing and what assets get printed. Page breaks, etc. 

That being said after modifying all css documents with @media print we expected to not see url's in the printed pages any longer.

#### Actual result

URL's still print to pages and within print preview 

#### System information (as much as possible)

Yootheme avenue template with warp 7 framework. (ticket in to yootheme too).  

#### Additional comments

Modifying these documents in the past has worked. This time it does not. This is part problem and part feature request. 

Link to print preview:  http://parrotfunzone.com/explore-parrots/parrots-in-the-wild/where-do-parrots-come-from/african-parrots?tmpl=component&print=1&page=

**Comment by brianteeman** [comment]
That CSS looks correct BUT it is something that comes from your template CSS that you are trying to override and so it is not possible for the core of Joomla to override that so an option inside of Joomla will not work.

As you are using a yootheme template and the override is not working you really should be speaking to them.

**Comment by darylkuchay** [comment]
Thank you brianteeman,

I posted on yootheme before posting to github. Sadly the behavior is not exclusive to yootheme. This is more relative to a joomla item:

http://forum.joomla.org/viewtopic.php?f=706&t=869698&view=previous

http://stackoverflow.com/questions/585254/how-to-remove-the-url-from-the-printing-page

notice that stackoverflow does not have a solution!!

https://www.gavick.com/forums/cloudhost/hide-urls-on-printed-page-45376


And the list of links is endless with this issue. If all links were relative to yootheme I would concur with your recommendation. 

Yootheme offers a custom.css file that is the last css to load in the head of document. This document is meant to override normal template behavior. As this is simply not working and with countless links on internet (not yootheme) I have to assume that the issue is not with yootheme and with Joomla. 

If you can let me know that this is an issue with anything other than joomla I would love to read your words. 

Thank you in advance

**Comment by brianteeman** [comment]
Look at this site built with joomla by me http://www.sri2.net

Try to print a page with links eg the home page which has several links

You will get no links  printed out.

In the css of my template I have the following code

```css
 /* print css */
@media print {
    .noprint {
        display:none !important;
    }
    a:link:after, a:visited:after {  
      display: none;
      content: "";    
    }

**Comment by brianteeman** [comment]
Updated the relevant part of the css is just

```css


 /* print css */
@media print {
    a:link:after, a:visited:after {  
      display: none;
      content: "";    
    }

**Comment by darylkuchay** [comment]
I do very much appreciate your suggestions. One difference on your setup to my setup, You do not have the print and email icons available on your home page to test this with. Therefore I wonder if you are missing a step that I am taking to recreate? I get no urls when printing via keyboard shortcut. Its when I use the joomla icon for printing that I get the urls printed on the page next to each link and image. Without these icons on your home page the test is not recreating the situation. 

Please visit this url and then navigate to the bottom of the page and click on print icon:

http://parrotfunzone.com/explore-parrots/parrots-in-the-wild/where-do-parrots-come-from/african-parrots?tmpl=component&print=1&page=

Now visit same page and press keyboard shortcut for printing:

http://parrotfunzone.com/explore-parrots/parrots-in-the-wild/where-do-parrots-come-from/african-parrots


Urls still print on pages for images and links. 
CSS in "custom.css" (last to load) is:

@media print {
    .noprint {
    display:none !important;
}
    a:link:after, a:visited:after {  
      display: none;
      content: "";    
}
}
Since this "custom.css is the last css file to load (verifiable via view source) I have placed the code you provided there.
If using the joomla icon to print yields uncontrollable behavior would it be an ideal to allow admin control of the rules that get applied to this icon?   

I looked over my notes and you are partially correct. This was an issue in May 2015. Warp framework updated to version 7 and custom css rules would make urls go away from printed pages after update. 
Next event was that Joomla updated twice. 3.4.2 did not effect this issue however when joomla updated to 3.4.3 this issue resurfaced. 

I understand what you are saying with plugins being able to effect desired outcome however if a Joomla update is what caused then there are a number of other issues at hand mostly in development and probably documentation. This is why I said part feature request in my first post. This has been an issue for a long time based on the posts I am seeing on the internet on this subject. If the greater team that makes joomla usable and popular wants to point fingers then joomla as a whole will suffer. 

All current solutions for this resurfacing problem are temporary or "hack" in nature. It would be nice to see a control for this core joomla function within the admin interface. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7407">issues.joomla.org/joomla-cms/7407</a>.</sub>

**Comment by mbabker** [comment]
Are you including the CSS for your `@media` queries in your template's component.php file?  When passing a `tmpl=whatever` param in the URL, that decides which template file to use (defaults to index.php).  So if your media isn't getting loaded in that template file, then it's fully understandable why the print results aren't 100% as you'd expect.

**Comment by brianteeman** [comment]
You need to make sure that the component.php file in your template includes
your custom CSS.

**Comment by brianteeman** [comment]
just checked your site (I was on my phone before) and you are NOT loading
the media query on the print page - which as @mbabker confirmed (if you
dont believe me) is component.php

On 20 July 2015 at 15:50, Michael Babker <notifications@github.com> wrote:

> Are you including the CSS for your @media queries in your template's
> component.php file? When passing a tmpl=whatever param in the URL, that
> decides which template file to use (defaults to index.php). So if your
> media isn't getting loaded in that template file, then it's fully
> understandable why the print results aren't 100% as you'd expect.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7407#issuecomment-122909115>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by darylkuchay** [comment]
We learn something new each and every day. Thank you to my teachers for your patience and willingness! 

@mbabker and @brianteemen, Thank you very much! This has solved my immediate issue and has provided more opportunity for adjusting how printed pages look. I hope that this post is very visible as I am sure it will save others time in the future. 

Just needed to copy that custom.css from the editor to a document and ftp it to the same location that the other css documents were being called from within component.php and viola.

Cheers<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7407">issues.joomla.org/joomla-cms/7407</a>.</sub>

**Comment by brianteeman** [comment]
Glad you got there in the end. A shame that yootheme templates were not
coded to include the custom CSS file and that they obviously didn't answer
your support ticket.

**Comment by darylkuchay** [comment]
Agreed, apologies for misunderstanding the core issue and thank you again for fast and helpful support. Please consider and or mark this issue as solved.
