### ISSUE TITLE
change document title with content plugin does not work since Joomla! 3.4.1 in components\com_content\views\article\view.html.php

### ISSUE THREAD

**Issue by avjoomla** [joomla/joomla-cms#7408]
Up to Joomla! 3.4.0 it was possible to change the document title in the code of a content plugin.

In Joomla! 3.4.0 content plugins were triggered with the following code
(line 163) $results = $dispatcher->trigger('onContentAfterTitle', array('com_content.article', &$item, &$this->params, $offset));
Since Joomla! 3.4.1 the code was changeed to 
(line 1643) $results = $dispatcher->trigger('onContentAfterTitle', array('com_content.article', &$item, &$item->params, $offset));
So instead of &$this->params now &$item->params is used.

As $this->params is not set to the $item->params afterwards, changes made to the params in a content plugin are only available in the display function of the view class but not in the _prepareDocument function which actually does use the params.

The problem could be fixed by adding the following line to the display function after line 180
+ 181 $this->params = $item->params;
Alternatively the parameter passed to the plugin could be reverted to &$this->params whenever the content plugins are triggered. (line 163, 166, 169)
As far as I have seen, teh problem does orccur in all views of the com_content.

Regards,
Aicha

**Comment by brianteeman** [comment]
Do you have a plugin you can share that will help to make testing easier

**Comment by Bakual** [comment]
Did you try to use a different plugin event? Thing is that `onContentAfterTitle`isn't really meant for such tasks. It is meant to return a string which is displayed after the title.

**Comment by avjoomla** [comment]
I used the onContentPrepare event which is not working, too.

If you like, I could send you my plugin to test with.

**Comment by Bakual** [comment]
All `onContent` events aren't meant to change the document itself. They are meant to deal with the content passed in.
You could probably set the document title in a later (system) event. If you need the $item you could do it using two events. One of the `onContent...` events to fetch the needed data and a later one to alter the document title.

**Comment by avjoomla** [comment]
So this is an intended change in the interface? Because up to Joomla! 3.4.0 it worked with the onContent... events and that made a lot of sense to me. Which later event would you advice to use?

**Comment by Bakual** [comment]
I'd say it was an intended change, yes. I would have to search the change though.

I would probably use https://docs.joomla.org/Plugin/Events/System#onBeforeRender.

**Comment by avjoomla** [comment]
Thanks, I'll check on that event but I would really appreciate if somebody would check if this really is an intended change or not because, as I wrote, it made perfectly sense to me to be able to change the document parameteres at that point, too.

**Comment by Bakual** [comment]
Change was https://github.com/joomla/joomla-cms/pull/5016

**Comment by avjoomla** [comment]
Thanks for the information!
And yes, the onBeforeRender() event works perfectly for my purpose.
