### ISSUE TITLE
A forgotten call to helper.php in mod_submenu.xml

### ISSUE THREAD

**Issue by ghazal** [joomla/joomla-cms#7409]
#### Steps to reproduce the issue
In /administrator/modules/mod_submenu/mod_submenu.xml
line 14
There is still a call to helper.php while the file doesn't exist anymore.

I discovered this while struggling with an update from a 3.2 version to 3.4.3 where : 
/administrator/includes/subtoolbar.php
was not added.
Probably a wrong move from my part.

#### Expected result
No result

**Comment by zero-24** [comment]
Good find! Here is a PR for fixing that issue: https://github.com/joomla/joomla-cms/pull/7410
