### ISSUE TITLE
database error handling in Frontend

### ISSUE THREAD

**Issue by franzpeter** [joomla/joomla-cms#7428]
I do not know if it is a security issue. But if a component partly failed on installation in case of some additional database tables and you created a link in a Joomla menu for that component, you get a website error, that something was not found (error page). But is it necessary to show the full query, which produced the error on that page, even if debug is set to off?

#### Expected result
error page without full query

#### Actual result
error page with full query result.

#### System information (as much as possible)
Joomla 3.4.x

**Comment by franzpeter** [comment]
I have seen that it occurs with every db query, not only if a component failed to install completely. if a $db->execute failed you will see the full query which failed on the error page.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7428">issues.joomla.org/joomla-cms/7428</a>.</sub>

**Comment by roland-d** [comment]
Perhaps it should be an addition to these PRs:
https://github.com/joomla/joomla-cms/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Aalikon+handle+db+in%3Atitle

@alikon What do you think?

**Comment by Bakual** [comment]
There is actually already a try/catch block. But it is around the full query building (https://github.com/joomla/joomla-cms/blob/staging/components/com_content/models/article.php#L84-L242).
And it just shows the error message from the exception. So it doesn't help much.

I think better would be to just try/catch https://github.com/joomla/joomla-cms/blob/staging/components/com_content/models/article.php#L159 and raise a generic error message there.

**Comment by franzpeter** [comment]
Bakual, yes I think so. It should only show the query, which provokes an error if Joomla is set to report errors. Else it should tell that there is an error but not the db query to any user entering the page if error reporting is off.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7428">issues.joomla.org/joomla-cms/7428</a>.</sub>

**Comment by franzpeter** [comment]
The prefix for a db table for example is an additional security part. Else I could continue to use jos_. But just my opinion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7428">issues.joomla.org/joomla-cms/7428</a>.</sub>

**Comment by Bakual** [comment]
Actually, it should never show the query.
You can always set up the logger to log the database errors to a log file.

> The prefix for a db table for example is an additional security part. Else I could continue to use jos_. But just my opinion.

It's both, a security part but also a feature which allows to have multiple Joomla installations within the same database.

**Comment by alikon** [comment]
@roland-d
i think should be try/cathed
@Bakual 
i was  playing around https://github.com/alikon/joomla-cms/commit/d533b9610312e001706e5f19759453b5723817fd

may i have a some feedback....

**Comment by Devportobello** [comment]
Just want to remember some arg from this post: https://github.com/joomla/joomla-cms/pull/6591

**Comment by roland-d** [comment]
@alikon will propose a pull request and we can then test his solution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7428">issues.joomla.org/joomla-cms/7428</a>.</sub>

**Comment by brianteeman** [comment]
@alikon @rolandd was a PR created?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7428">issues.joomla.org/joomla-cms/7428</a>.</sub>

**Comment by roland-d** [comment]
I haven't seen or heard anything. Any update @alikon ?

**Comment by alikon** [comment]
Sorry guys, completely forgotten, hope can i have a look on weekend...

**Comment by brianteeman** [comment]
Thanks



On 8 June 2016 at 07:42, Nicola Galgano <notifications@github.com> wrote:

> Sorry guys, completely forgotten, hope can i have a look on weekend...
> On 7 Jun 2016 9:38 pm, "RolandD" <notifications@github.com> wrote:
>
> > I haven't seen or heard anything. Any update @alikon
> > <https://github.com/alikon> ?
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/joomla/joomla-cms/issues/7428#issuecomment-224390659
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AALFsWjcAKQLaJLRnE1v7nvI8--rpcJeks5qJci_gaJpZM4FXYir
> >
> > .
>
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7428#issuecomment-224502997>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8dQfNDlNsp-5T3JEKMhgCeezBaAtks5qJmRsgaJpZM4FXYir>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by alikon** [comment]
some works was already done see #8130
not sure if we want to not display the query (for example if error_reporting was setted to none)
any comments?

**Comment by mbabker** [comment]
My suggestion is that now that the database drivers throw a specific `JDatabaseExceptionExecuting` object on a query failure, the query should be removed from the Exception message and attached to the Exception object as a new property (a downstream catcher of the Exception could access the query via `$exception->getQuery();`).  It removes the need to reverse parse the table prefix out of the query, makes it so that the query is NOT displayed as part of the error message, but continues to make that data available in all required contexts.

There's really no reason the query needs to be attached to the main Exception object's error message.

**Comment by alikon** [comment]
@mbabker with #10801 plus some changes on https://github.com/mbabker/joomla-cms/blob/e0aa0ec5c8588cd2a74a0489466f7e811a424e7c/libraries/joomla/database/driver/postgresql.php#L1516 `function getErrorMessage()` we can do the job, i'm right ?

**Comment by mbabker** [comment]
`getErrorMessage()` should be deprecated and removed.  There's no reason to reverse parse the table prefix out of the query if it's attached to the Exception object as a different parameter and not the main message.

**Comment by alikon** [comment]
do you mean something like this #10949 ?

**Comment by brianteeman** [comment]
As we now have a PR I am closing this here so conversation is in only one place<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7428">issues.joomla.org/joomla-cms/7428</a>.</sub>
