### ISSUE TITLE
jos-Warning: exception 'RuntimeException' with message 'Unknown column 'header'

### ISSUE THREAD

**Issue by FreeMindedMedia** [joomla/joomla-cms#7429]
My website gives me some funny error for the 404 pages. Example: I have an menu item called 'News', and the linked is 'news.html'. but when I try to test the error page by adding a wrong to link 'neews.html'

*PROBLEM*
From --> news.html
To --> neews.html

I get the below error:
jos-Warning: exception 'RuntimeException' with message 'Unknown column 'header' in 'field list' SQL=SELECT `new_url`,`header`,`published` FROM `n2l56_redirect_links` WHERE `old_url` = 'http://www.barloworldpower.com/en/neews.html' LIMIT 0, 1' in /usr/www/users/domaintest/libraries/joomla/database/driver/mysqli.php:610 Stack trace: #0 /usr/www/users/domaintest/plugins/system/falangdriver/falang_database.php(99): JDatabaseDriverMysqli->execute() #1 /usr/www/users/domaintest/libraries/joomla/database/driver.php(1317): JFalangDatabase->execute() #2 /usr/www/users/domaintest/plugins/system/falangdriver/falang_database.php(278): JDatabaseDriver->loadObjectList('', 'stdClass') #3 /usr/www/users/domaintest/plugins/system/falangdriver/falang_database.php(411): JFalangDatabase->loadObjectList('', 'stdClass', true, NULL) #4 /usr/www/users/domaintest/plugins/system/redirect/redirect.php(86): JFalangDatabase->loadObject() #5 [internal function]: PlgSystemRedirect::handleError(Object(JException)) #6 /usr/www/users/domaintest/libraries/legacy/error/error.php(760): call_user_func(Array, Object(JException)) #7 [internal function]: JError::handleCallback(Object(JException), Array) #8 /usr/www/users/domaintest/libraries/legacy/error/error.php(218): call_user_func_array(Array, Array) #9 /usr/www/users/domaintest/libraries/legacy/error/error.php(179): JError::throwError(Object(JException)) #10 /usr/www/users/domaintest/libraries/legacy/error/error.php(254): JError::raise(1, 404, 'Article not fou...', NULL, true) #11 /usr/www/users/domaintest/components/com_content/models/article.php(173): JError::raiseError(404, 'Article not fou...') #12 /usr/www/users/domaintest/libraries/legacy/view/legacy.php(401): ContentModelArticle->getItem() #13 /usr/www/users/domaintest/components/com_content/views/article/view.html.php(37): JViewLegacy->get('Item') #14 /usr/www/users/domaintest/libraries/legacy/controller/legacy.php(690): ContentViewArticle->display() #15 /usr/www/users/domaintest/components/com_content/controller.php(79): JControllerLegacy->display(true, Array) #16 /usr/www/users/domaintest/libraries/legacy/controller/legacy.php(728): ContentController->display() #17 /usr/www/users/domaintest/components/com_content/content.php(17): JControllerLegacy->execute(NULL) #18 /usr/www/users/domaintest/libraries/cms/component/helper.php(392): require_once('/usr/www/users/...') #19 /usr/www/users/domaintest/libraries/cms/component/helper.php(372): JComponentHelper::executeComponent('/usr/www/users/...') #20 /usr/www/users/domaintest/libraries/cms/application/site.php(191): JComponentHelper::renderComponent('com_content') #21 /usr/www/users/domaintest/libraries/cms/application/site.php(230): JApplicationSite->dispatch() #22 /usr/www/users/domaintest/libraries/cms/application/cms.php(252): JApplicationSite->doExecute() #23 /usr/www/users/domaintest/index.php(45): JApplicationCms->execute() #24 {main}

*EXPECTED RESULTS*
From --> news.html
To --> neews.html

I am supposed to get an error page saying: page not found.

*SYSTEM INFO*
Joomla: 3.4.3
Database Version 	5.5.43-0+deb7u1 
PHP Version 	5.6.9-hetz1 
Web Server 	Apache

**Comment by zero-24** [comment]
@FreeMindedMedia Please go to the Backend and try to repair the Database. (Backend --> Extension --> Extension Manager --> Database --> repair)

IF that don't fix the issue execute the following SQL (replace `#__` with your Databaseprefix):

```sql
ALTER TABLE `#__redirect_links` ADD header smallint(3) NOT NULL DEFAULT 301;
ALTER TABLE `#__redirect_links` MODIFY new_url varchar(255);
```

**Comment by FreeMindedMedia** [comment]
Hi Zero-24, 

My Database table structure is up to date, and I did add the SQL Query, but I am still getting the same error.

**Comment by zero-24** [comment]
@FreeMindedMedia Than is something completly wrong. :smile: 

The message says `'Unknown column 'header' in 'field list'. With the first SQL you add the header column. Please check that the header exists in the Databse.

Than please clear you Joomla / Server / Browser cache.

**Comment by zero-24** [comment]
BTW. If you need more information / help please use the Joomla Forums at: forum.joomla.org Thanks :smile:

**Comment by FreeMindedMedia** [comment]
I would not get help, hence I had to downgrade to the previous version which was working fien.
