### ISSUE TITLE
nonSEF URLs in content in RSS or ATOM Feeds

### ISSUE THREAD

**Issue by dmsolutions** [joomla/joomla-cms#7437]
Links in an article are always nonSEF when viewed over RSS. Because they are reachable for google and other search engines over rss they are indexed with the wrong url from the feed and create a duplicate content problem.

#### Steps to reproduce the issue

You can see the problem live on our website on the following two rss feeds:
http://www.dmsolutions.de/glossar/feed/rss.html
http://www.dmsolutions.de/glossar/feed/atom.html

In these feeds you find different links in articles content such as "Domain" or "KK-Antrag" in article "Domainumzug". As you can see the links are nonSEF links which show up the content under nonSEF URLs. The problem is only in feeds, if you look at the original page "http://www.dmsolutions.de/glossar/" the links are correct and point to the SEF URL:
Domain = http://www.dmsolutions.de/glossar/domain.html
KK-Antrag = http://www.dmsolutions.de/glossar/kk-antrag.html

#### Expected result

URLs in feeds content should be only shown up as SEF URLs.

#### Actual result

URLs in feeds content show up as joomla standard URL without creating SEF URLs.

#### System information (as much as possible)

Joomla 3.4.3 (tested also with all other versions since Joomla 3.3)
Debian with Apache
Tested with php5.3 and php5.4
Tested with different combination of SEF activation (with or without suffix)

**Comment by Bakual** [comment]
If it helps someone figuring that out: Those URLs would be changed by the system/sef plugin in the `onAfterRender` event.

**Comment by mbabker** [comment]
`JDocumentRendererRSS` and `JDocumentRendererAtom` both convert URLs from relative to absolute.  The SEF plugin can only cope with relative URLs beginning with `index.php`.

**Comment by brianteeman** [comment]
Reset priority according to docs https://docs.joomla.org/Bug_and_Issue_Tracker_Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7437">issues.joomla.org/joomla-cms/7437</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #10442<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7437">issues.joomla.org/joomla-cms/7437</a>.</sub>
