### ISSUE TITLE
Images missing from update packages

### ISSUE THREAD

**Issue by jeffchannell** [joomla/joomla-cms#7438]
From Joomla! 3.3.x to 3.4.0, some images (like images/powered_by.png) were altered. Some were again altered for 3.4.2. The altered images do not appear in the update packages, so a fresh install of 3.4.3 differs from one that started with 3.4.1 and was updated to 3.4.3, and a site that was built prior to 3.4.0 and updated will differ as well.

This issue doesn't affect usability at all, and is likely "by design" to save space and bandwidth.

**Comment by mbabker** [comment]
There are certain "sample" images purposefully excluded from the update packages (https://github.com/joomla/joomla-cms/blob/staging/build/build.php#L232).  Part of the thinking is that most of these images were included only for the sample data and part of it (for me at least) is we wouldn't want to change the graphics someone is using on a production site in their content.

We could probably make it known somewhere these things change and if users would like the revised versions explain how they can get them.

**Comment by PhilETaylor** [comment]
ah this explains why myJoomla.com audits show these files as modified on sites that have been upgraded repeatedly - lightbulb moment :)

**Comment by mbabker** [comment]
Phil it's been this way for 18 months (https://github.com/joomla/joomla-cms/commit/412e9357636fb179b1dc504f24b5ecd83c727358), where have you been? :stuck_out_tongue_closed_eyes:

**Comment by PhilETaylor** [comment]
I have ```been``` ignoring the problem :) knowing it existed as a "thing" but not investing time to understand the ```why``` ;)

**Comment by jeffchannell** [comment]
Thanks @mbabker - I figured it was something like that, but wasn't sure if it was on purpose.

Closing.
