### ISSUE TITLE
Category selection - administrator

### ISSUE THREAD

**Issue by Rajiii4u** [joomla/joomla-cms#7449]
#### Steps to reproduce the issue

In  article manager , while using search tools, select "category" field shows trashed category items...

#### Expected result

Need to list out only categories item published....

#### Actual result
select category field displays all category items.......

#### System information (as much as possible)

3.4.3

#### Additional comments
Issue solved on changing filter_articles.xml file

**Comment by Rajiii4u** [comment]
it will be reolved by changing following values in form field:
path\administrator\components\com_content\models\forms\filter_articles.xml
From: "		<field
			name="category_id"
			type="category"
			label="JOPTION_FILTER_CATEGORY"
			extension="com_content"
			description="JOPTION_FILTER_CATEGORY_DESC"
			onchange="this.form.submit();"
			published="-2,0,1,2"
			>
			<option value="">JOPTION_SELECT_CATEGORY</option>
		</field>"

To: "		<field
			name="category_id"
			type="category"
			label="JOPTION_FILTER_CATEGORY"
			extension="com_content"
			description="JOPTION_FILTER_CATEGORY_DESC"
			onchange="this.form.submit();"
			published="0,1,2"
			>
			<option value="">JOPTION_SELECT_CATEGORY</option>
		</field>"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7449">issues.joomla.org/joomla-cms/7449</a>.</sub>

**Comment by Bakual** [comment]
Since you propose a code change, can you please do a Pull Request for it? This way it can be tested easily.
See https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests for how to do it.

**Comment by spignataro** [comment]
Please see pull request: https://github.com/joomla/joomla-cms/pull/7470<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7449">issues.joomla.org/joomla-cms/7449</a>.</sub>

**Comment by Bakual** [comment]
Closing this issue as we have a PR:
