### ISSUE TITLE
Missing indentation in form field type "menuitem"

### ISSUE THREAD

**Issue by ucfnet002** [joomla/joomla-cms#7485]
In a selfmade module I need to select a menuitem. So i used the standard form field type "menuitem". However, the resulting Dropdown don't shows any indentation, so all menuitems looks like they have the same level. In my case, with over 50 menuitems, it's really confusing finding the right item.

![screenshot_menuitem_no-indentation](https://cloud.githubusercontent.com/assets/6213131/8796027/ed8f5756-2f91-11e5-847e-cd01c3e834cb.png)
![screenshot_menu](https://cloud.githubusercontent.com/assets/6213131/8796028/ed934960-2f91-11e5-97af-05bcafa70305.png)

Tested on Joomla 3.4.3 with default Backend Template "isis".

**Comment by Devportobello** [comment]
You right, this is really hard with many items.
See this: https://github.com/joomla/joomla-cms/pull/6782
Milestone:  Joomla! 3.5.0 :)

**Comment by ucfnet002** [comment]
Thanks for pointing me to the right issue.

**Comment by brianteeman** [comment]
closing so the conversation is on just one issue
