### ISSUE TITLE
Pagination user manager when Search Tools present

### ISSUE THREAD

**Issue by LaurensGoedel** [joomla/joomla-cms#7486]
This issue is alot like #7194, but instead of the article manager, it is on the user manager.
When a filter is present, the pagination isn't working.

# Steps to reproduce the issue
1. Login in Joomla backend
2. Go to user manager
3. Open the filter and set a filter (for example the state to published)
4. Make sure you have more then one result page
5. Try to navigate to another page

# Expected result
The result expected is to get a number of users starting from the right start limit

# Actual result
Instead of different result page, you get the same results of page 1

# Systeminformation
* Using a clean install of Joomla 3.4.3 Stable version
* Default Isis template

# Additional comments
* When trying to debug, on the file /administrator/components/com_users/views/users/view.html.php, the list.start state is always 0, no matter what page is selected.
* It looks like the $app->input variable is somehow modified, because the limitstart is posted correctly

**Comment by Bakual** [comment]
Can you have a look if https://github.com/joomla/joomla-cms/pull/7487 fixes it?

Closing as we have a PR.

**Comment by LaurensGoedel** [comment]
#7487 fixes indeed the state filter.
As described, the group filter isn't working. I'll try to have a look at it later today

**Comment by Bakual** [comment]
Can you please add that comment to the PR :smile: ?
