### ISSUE TITLE
Website Resources Page Map Search Facility Broken

### ISSUE THREAD

**Issue by cmbr** [joomla/joomla-cms#7500]
Apparently the map, keyword, radius and category facility is not working correctly on the Joomla.org Website's [Resources Directory home page](http://resources.joomla.org/en/).

I tried the following scenarios:

Set the address to *United States*. The map display continues to show icons across the globe and there are 27 pages of results. (The total is 261 listings.) Many of the listings are for resources **not** in the United States.

Set the address to *Minnesota, United States*. There are now the same 261 listed resources. (Many of them are not in Minnesota.)

Set the address to *Europe*. Now there are 259 results. (Strangely, not 261 results.)

I opened a recently approved listing (Ryan Boog's *Happy Dog Web Productions*) and selected the word *psychology* that appears there. It's not a common word for Website companies so it shouldn't return many results. I cleared the address field, switched the condition to OR and entered *psychology* in the keyword field. The system returns 261 results.

I know Ryan is in Minnesota so I entered *Minnesota, United States* in the address field, switched the condition to AND while leaving *psychology* in the keyword field. The system returns zero results.

If I change the address field to *United States*, the system still returns zero results.

If I keep *United States* in the address field and use *Happy* as the keyword (the first name of the company), I see zero results.

By the way, are there more than 261 total resource listings in the database? I suspect the number of available registered companies and persons is greater than 261.

It doesn't matter if I share my location or not with the page. I tried this is both the Firefox browser and the Google Chrome browser running in Linux Mint. I don't see any errors reported in the Firebug console.

Note: There is no category available here in the Issue Tracker for *Joomla.org Website* so I choose *Search.* An administrator might be able to find a better classification.

**Comment by brianteeman** [comment]
This is the Issue tracker for the Joomla software. For issues with the Resources site please use the contact page on that site. http://resources.joomla.org/en/do-you-need-help

**Comment by cmbr** [comment]
Thank you, Brian. I did that last week. No response to date.

**Comment by brianteeman** [comment]
Sorry can't help you but this isn't the placw
