### ISSUE TITLE
Backend Modal instantly closes

### ISSUE THREAD

**Issue by Jinobix** [joomla/joomla-cms#7525]
All of a sudden whenever I am on the backend and I click something which would usually load a popup window, it quickly closes before I can do anything.
Example: Creating a new Menu Item, when I click "Select" next to "Menu Item Type*"
The window popups up then instantly closes before I can do anything.

Please help

**Comment by brianteeman** [comment]
Do you have redmigrator installed. We have had several reports of this and all of them were resolved by uninstalling redmigrator

**Comment by Jinobix** [comment]
We do not have redmigrator. However, we have the "Tracks" (league management) component which uses redCORE. Would this still cause an issue? This problem did not arise when we installed it though, only recently (and we have not updated Tracks or anything redCORE related recently)

**Comment by Jinobix** [comment]
Aaah, I just disabled all redCORE related in the manage extensions section::
redCORE Component.
redCORE - Libraries
redCORE - System plugin
redCORE - Language switcher

The window popup now shows. I guess this narrows it down.
Is there any pages/forums I can look at about this issue to help fix this?
For now I can temporarily disable these whenever I need the popup to show. (Temporary fix)

**Comment by brianteeman** [comment]
I would report this to redcomponent.com as you have just confirmed it is an
issue with their code and not the core

On 22 July 2015 at 16:09, Jinobix <notifications@github.com> wrote:

> Aaah, I just disabled all redCORE related in the manage extensions
> section::
> redCORE Component.
> redCORE - Libraries
> redCORE - System plugin
> redCORE - Language switcher
>
> The window popup now shows. I guess this narrows it down.
> Is there any pages/forums I can look at about this issue to help fix this?
> For now I can temporarily disable these whenever I need the popup to show.
> (Temporary fix)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7525#issuecomment-123753502>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
