### ISSUE TITLE
Delete Button in media manager not working

### ISSUE THREAD

**Issue by axel-rank** [joomla/joomla-cms#7544]
#### Steps to reproduce the issue

In media manager the **delete button** doesn't do anything onclick --> no function anymore.
Can't delete files or folders!

#### Expected result

delete files/folders

#### Actual result

no result

#### System information (as much as possible)

Joomla 3.4.3, PHP 5.6.11, Apache 2.2.29

**Comment by brianteeman** [comment]
I cant replicate this.

On 26 July 2015 at 14:34, axel-rank <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> In media manager the *delete button* doesn't do anything onclick --> no
> function anymore.
> Can't delete files or folders!
> Expected result
>
> delete files/folders
> Actual result
>
> no result
> System information (as much as possible)
>
> Joomla 3.4.3, PHP 5.6.11, Apache 2.2.29
> Additional comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7544>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
Known issue that will be fixed with 3.4.4: https://docs.joomla.org/J3.x:Delete_button_on_the_media_manager_does_not_work_anymore

Closing as allready fixed Thanks @axel-rank
