### ISSUE TITLE
Cannot turn off introtext in Category blog

### ISSUE THREAD

**Issue by jneubauer** [joomla/joomla-cms#7547]
#### Steps to reproduce the issue
Install Joomla 3.x
Create any article, and create menu item for category blog
in menu (or com_content) configuration, turn off "show intro text"
view menu item from front end and notice introtext still showing

#### Expected result
introtext shouldn't show when the configuration is set to not show it.

#### Additional comments
found the solution in components/com_content/views/category/tmpl/blog_item.php Line 44-46
the code to display introtext is not inside a conditional statement, it will always show, no matter what.
Solution coming in just a minute

**Comment by infograf768** [comment]
Please do not forget that featured is similar to category blog.

**Comment by jneubauer** [comment]
so I should probably check features for this same behavior too

**Comment by jneubauer** [comment]
JUst fixed the same in features (I think it added to the same pull request?) thanks @infograf768 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7547">issues.joomla.org/joomla-cms/7547</a>.</sub>

**Comment by infograf768** [comment]
I am afraid your patches are wrong
Please read:
https://github.com/joomla/joomla-cms/pull/7549#issuecomment-125014239

**Comment by infograf768** [comment]
Expected result is to SHOW or NOT the intro text when drilling down from the blog/featured, notin the blog or feature display themselves.

**Comment by jneubauer** [comment]
then why is this logic in the blog_item.php file to begin with? That makes no sense to put any of this logic in there (the if for show_intro) if there is no intention in any way to NOT show the introtext on the blog view.

**Comment by brianteeman** [comment]
See #7549 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7547">issues.joomla.org/joomla-cms/7547</a>.</sub>
