### ISSUE TITLE
Field calendar XML error DateTime J.3.4.3

### ISSUE THREAD

**Issue by alexonbalangue** [joomla/joomla-cms#7550]
Hello,
i have error Erreur: 0 DateTime::__construct(): Failed to parse time string (01-25-2012) at position 0 (0): Unexpected character
use function calendar https://docs.joomla.org/Calendar_form_field_type

**Comment by Bakual** [comment]
That string inbeed has an unexpected value. You need to pass the date in a format which can be understood by PHP. Usually it's safest to use the YYYY-MM-DD format. You using MM-DD-YYYY. FIx that and the calendar will work.

Closing as expected behavior.
