### ISSUE TITLE
JTableNested intentionally breaks the data

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#7551]
JTableNested::saveOrder() intentionally breaks the lft/rgt values of the nested set when reordering and then does a rebuild(). This is wrong on so many levels and a good explanation why the nested sets implementations in Joomla are broken so often.

**Comment by brianteeman** [comment]
Hi you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7551">issues.joomla.org/joomla-cms/7551</a>.</sub>
