### ISSUE TITLE
Language Switch Problem after upgrading Joomla

### ISSUE THREAD

**Issue by gilano** [joomla/joomla-cms#7562]
**[ENGLISH]**

I have a web portal in Joomla (version 3.4.3) that has been facing problems in terms of language switch since the upgrade for version 3.4.1.

**Current configuration:**
Joomla 3.4.3
Falang 2.1.0
VirtualDomains 1.3.1
PHP 5.4.42
Apache/2.2.15 (CentOS)

**Scenario:**
The portal is a unique Joomla installation with a group of different sites, each one accessed by a sub-domain configured in VirtualDomains. The official language of all sub-domains is Portuguese (pt-BR), though some sub-domains have versions in Portuguese (as standard language) and in English (en-GB). The multi-language content is managed by Falang, and the sub-domains by VirtualDomains. Joomla has the "Search Engine Friendly URLs" option set and uses Apache´s mod_rewrite. The Language Filter plugin is configured like this: Language Selection for new Visitors ->Site Language, Automatic Language Change -> No, Item Associations -> No, Remove URL Language Code -> YES, Cookie Lifetime -> Session, Add Alternate Meta Tags -> No.

**Problem:**
**1)** In some sub-domains, the Portuguese version simply is not loaded. Joomla returns a blank screen. If I access the English version in these same cases (adding "/en" at the end of the sub-domain address - even when the sub-domain has no content in English), the site is loaded despite the "/en" in the url. Please note that the site is not loaded when the url dos not show a "/en".
**2)** In other sub-domains, mainly those that have content in both languages (pt-br and en-gb), Joomla forces the site to be displayed in English only. The language is not switched even using the language switcher. 

**Actions:**
I have already disabled the Falang package, but the problem persists. What is worse is that the problem was continuous in version 3.4.1, becoming intermittent after upgrading to version 3.4.3. We have noticed that the link of the menu item defined as "HOME" in VirtualDomains does not have the root url of the site (subdomain.mysite.com) only, but the link with its alias (subdomain.mysite.com/alias-home). This is also valid for the links for language switch generated by the Language Switcher module. Language Switcher is generating the links (subdomain.mysite.com/alias-home) for pt-BR and (subdomain.mysite.com/en/alias-home) for en-GB. Through these links, with the alias of the home menu item, the site appears correctly either in English or in Portuguese (not causing the first problem mentioned). It seems that VirtualDomains could not define the menu item configured as "HOME" of the sub-domain, and, as such, Joomla becomes lost when displaying the initial page of the loaded sub-domain. Please remember that when setting the "Remove URL Code of the Language" option defined as "YES" in the Language Filter plugin, the "/pt" is not displayed in the URL of the sub-domains when loading their standard version in Portuguese. Another detail is that when the "Remove URL Code of the Language" option defined as "NO" and the Portuguese language standard addresses start to present the "/en", reported problems no longer occur.

----------------------------------------------------------------------

**[PORTUGUÊS]**

Possuo um portal em Joomla (versão 3.4.3) e desde a atualização para a versão 3.4.1 vem apresentando problemas com a funcionalidade de troca de idiomas.

**Configuração atual:**
Joomla 3.4.3
Falang 2.1.0
VirtualDomains 1.3.1
PHP 5.4.42
Apache/2.2.15 (CentOS)

**Cenário:**
O portal consiste em uma única instalação Joomla, com um conjunto de sites distintos acessados cada um por um subdomínio configurado no VirtualDomains. Oficialmente o idioma padrão de todos os subdomínios é o português (pt-BR), e alguns subdomínios possuem versões em português(como idioma padrão) e em inglês (en-GB). O conteúdo multi-idioma é gerido pelo Falang e os subdomínios pelo VirtualDomains. O Joomla está com a opção de "URLs Amigáveis" habilitada e usando o mod_rewrite do Apache. O pluguin de Filtro de Idioma está com as seguintes configurações: Seleção de Idioma para Visitantes -> Idioma do Site, Alteração Automática de Idioma -> Não, Item Associations -> Não, Remover Código URL do Idioma -> SIM, Cookie Lifetime -> Session, Acrescentar meta tags Alternativas -> Não.

**Problema:**
**1)** Em alguns subdomínios a versão em português simplesmente não carrega. O Joomla devolve uma tela branca. Nesses mesmos casos, se eu entro com a versão em inglês (acrescentando o "/en" após o endereço do subdomínio - mesmo que o subdominio não possua nenhum conteudo para o inglês) o site passa a aparece normalmente e o "/en" permanece no endereço do site.
**2)** Em outros subdomínios, principalmente aqueles que possuem conteúdo nos dois idiomas (pt-br e en-gb) o joomla força o site a ser exibido somente em inglês. Não adianta eu trocar para português que o site permanece no inglês. 

**Ações:**
Já desabiliei o pacote do Falang e o problema persistiu. O que agrava é que na versão 3.4.1 o problema era contínuo, após a atualização para 3.4.3, ficou intermitente. Precebemos também que o link do item de menu definido como "HOME" no VirtualDomains não possui o link somente com a url raiz do site (subdomain.mysite.com) e sim o link com seu alias (subdomain.mysite.com/alias-home). Isso vale também para os links para troca de idioma, gerados pelo modulo Language Switcher. O Language Switcher está gerando os links (subdomain.mysite.com/alias-home) para pt-br e (subdomain.mysite.com/en/alias-home) para en-gb. Por esses links, com o alias do item de menu home, o site aparece corretamente tanto em inglês como em português (não oacasionando o primeiro problema apresentado). Parece que o virtualdomains não está conseguindo definir o item de menu configurado como "HOME" do subdominio, e com isso, o Joomla se perde em exibir a página inicial do subdomínio carregado. Lembrando que com a opção de "Remover Código URL do Idioma" do plugin Filtro de Idiomas definida como "SIM", o "/pt" não é exibido na URL dos subdomínios quando carregam sua versão padrão em português. Outro detalhe, é que quando a opção "Remover Código URL do Idioma" é definida como "NÃO" e os endereços padrões do idioma português passam a apresentar o "/pt", os problemas relatados não ocorrem mais.

**Comment by infograf768** [comment]
You are using falang and virtual domains, both 3rd party extensions. Please contact their respective developers.

**Comment by zero-24** [comment]
Closing as this are issues with your 3rd party extensions.
