### ISSUE TITLE
Documentation Error - J3 User Registration

### ISSUE THREAD

**Issue by thenewbreed** [joomla/joomla-cms#7576]
#### Steps to reproduce the issue

The page in documentation for J3 for user registration directive, has a link that goes to info for J1.5: https://docs.joomla.org/Allowing_user_registration

Was looking for a way to turn off the user registration, but this option did not show up in global configuration under the main headers. I figured out to use the list on the left of components and choose "Users Manager" to configure users. But this was not immediately obvious. 

#### Expected result

Link to info on user registration for Joomla 3.4

#### Actual result

Link to info for user registration for Joomla 1.5

#### System information (as much as possible)

n/a

#### Additional comments

n/a

**Comment by brianteeman** [comment]
This is the issue tracker for the software not the documentation web site. That site is a wiki and you can create an account there and update the page. Thanks for spotting it and look forward to seeing it corrected

**Comment by MAT978** [comment]
Thank you @brianteeman and @thenewbreed, let me know if you need any help on the JDoc.
Thanks for spotting it

**Comment by MAT978** [comment]
Link changed on the JDocs to the 3.x series + tagged/marked for translation...
thanks
