### ISSUE TITLE
Getting Error while uploading joomla site on another server

### ISSUE THREAD

**Issue by sandijai** [joomla/joomla-cms#7580]
#### Steps to reproduce the issue

I had designed one joomla site and want to move to another server. I have followed the step but still site is not working. 

Old database details-
public $dbtype = 'mysqli';
	public $host = 'db';
	public $user = 'alkaram2';
	public $password = 'AK12345';
	public $db = '	';
	public $dbprefix = 'amr_'; 

I changed with new- 
public $dbtype = 'mysqli';
	public $host = 'localhost';
	public $user = 'alkaranh_alkarde';
	public $password = 'Sandy@123';
	public $db = 'alkaranh_alkardemo';
	public $dbprefix = 'Amr_';

Getting this error- Table 'alkaranh_alkardemo.Amr_session' doesn't exist SQL=INSERT INTO `Amr_session` (`session_id`, `client_id`, `time`) VALUES ('g8uhg5rpsm01pojp2jnuokbdr7', 0, '1438169400')

Website- alkaramqatar.com

**Comment by brianteeman** [comment]
I see that you have changed the database prefix from
public $dbprefix = 'amr_';
to
public $dbprefix = 'Amr_';

Is that correct?

Also this is the issue tracker for bugs/new development  in the Joomla
software and not for support.

Please use http://forum.joomla.org for support

On 29 July 2015 at 12:32, sandijai <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> I had designed one joomla site and want to move to another server. I have
> followed the step but still site is not working.
>
> Old database details-
> public $dbtype = 'mysqli';
> public $host = 'db';
> public $user = 'alkaram2';
> public $password = 'AK12345';
> public $db = ' ';
> public $dbprefix = 'amr_';
>
> I changed with new-
> public $dbtype = 'mysqli';
> public $host = 'localhost';
> public $user = 'alkaranh_alkarde';
> public $password = 'Sandy@123';
> public $db = 'alkaranh_alkardemo';
> public $dbprefix = 'Amr_';
>
> Getting this error- Table 'alkaranh_alkardemo.Amr_session' doesn't exist
> SQL=INSERT INTO Amr_session (session_id, client_id, time) VALUES
> ('g8uhg5rpsm01pojp2jnuokbdr7', 0, '1438169400')
>
> Website- alkaramqatar.com
> Expected result Actual result System information (as much as possible) Additional
> comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7580>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sandijai** [comment]
Thanks,it was as it is there. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7580">issues.joomla.org/joomla-cms/7580</a>.</sub>

**Comment by sandijai** [comment]
Thank you so much I just changed with a and its working fine.
alkaramqatar.com<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7580">issues.joomla.org/joomla-cms/7580</a>.</sub>

**Comment by N6REJ** [comment]
now go change your db user and password since its now all over the 
internet or you will surely get hacked.
Bear

**Comment by Bakual** [comment]
I deleted the sensible data from the initial post.
@sandijai Still follow the advise from @N6REJ to change the credentials. At least db user and password.

**Comment by brianteeman** [comment]
The "sensitive" data will still have been emailed to all emails subscribers so MUST be change

**Comment by Bakual** [comment]
> The "sensitive" data 

Ouch, corrected. That word I used had a complete different meaning than what I wanted to say.
