### ISSUE TITLE
Menu "active" class is not always applied correctly.

### ISSUE THREAD

**Issue by simplysites** [joomla/joomla-cms#7584]
See pull request #7574, thanks to @fruppel for the generic explanation.

When the base item of a menu module is not set to "current", under certain circumstances the "active" class is not applied correctly. Code suggestion (with different class) is available in the mentioned pull request.

If you have a menu like this:

    Level 1
        Level 2
            Level 3

and in your model you set the config to Base Item -> "Level 1", Start Level -> 2 the "active" class is not applied to the menu items.

**Comment by JoshuaLewis** [comment]
Do you have any code for us to test?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7584">issues.joomla.org/joomla-cms/7584</a>.</sub>

**Comment by brianteeman** [comment]
Hi you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7584">issues.joomla.org/joomla-cms/7584</a>.</sub>
