### ISSUE TITLE
Long drop-down sub menu gets cropped in Mobile View

### ISSUE THREAD

**Issue by Jay-Jay-OPL** [joomla/joomla-cms#7587]
I am using the Protostar Template.

After our recent upgrade to Joomla 3.4.3, longer sub-menus in the Top Menu are covered by featured articles on the home page which makes the sub-menus inoperable (useless).

The sub-menus work correctly on full screen monitors. This anomaly only happens when the screen is reduced in size for mobile devices. 

#### Steps to reproduce the issue
Create a menu where one parent menu category has many sub-menus (about 10 or 15)(children).  
Place this parent menu to be the last menu category in the menu.
Set this menu to be Position 1 in Protostar template.
View your site using a mobile phone. (Protostar Template)

#### Expected result
Should be able to view all the menu options in responsive mobile view.

#### Actual result
The menu gets cropped (cut-off).  
Visitor cannot see anymore menus with their mobile phone.
(see screenshots)

![Example 1](http://forum.joomla.org/download/file.php?id=112593&t=1 "Example 1")

![Example 2](http://forum.joomla.org/download/file.php?id=112527&t=1 "Example 2")

#### System information (as much as possible)
Joomla 3.4.3
OS Linux h
PHP 5.4.26
MySQL 5.0.96-community-log
Caching Enabled
GZip Enabled

#### Additional comments
There are two forum threads that explain this issue and they include screenshots:

http://forum.joomla.org/viewtopic.php?f=706&t=892016

http://forum.joomla.org/viewtopic.php?f=706&t=891691

**Comment by brianteeman** [comment]
Resetting the priority according to our docs https://docs.joomla.org/Priority

Please can you retry with the screenshots as they have not been uploaded. Or share a link to the effected web site<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7587">issues.joomla.org/joomla-cms/7587</a>.</sub>

**Comment by Jay-Jay-OPL** [comment]
Is there a way you can follow the links at the bottom?  Two help threads explain the issue, plus provide screenshots.  You will need to login to the help forum to view the screenshots.

Let me know if you can't see them.  I guess I can link them here somehow?

On MOB's thread, it provides a site link where you can see the issue on a live site.  My site is private, so I can't share the link, but his shows the same issue as I do.

Thanks in advance. :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7587">issues.joomla.org/joomla-cms/7587</a>.</sub>

**Comment by Jay-Jay-OPL** [comment]
Here are the screenshots and a link where you can see the issue yourself with a mobile phone or a tablet:

Site: http://www.djexplosionsd.com/

# First Screenshot shows the site above in Desktop View (long sub-menu and no problem there)
![screen shot 2015-07-31 at 13 11 39](http://issues.joomla.org/uploads/1/c185acf04312235eba95b747c2176455.jpg)


# Second Screenshot same site, but mobile view (same long sub-menu cropped can't view the rest of it).
![screen shot 2015-07-31 at 13 11 39](http://issues.joomla.org/uploads/1/9909b1c4a3961f118a335bdc8abfce39.jpg)


# This third screenshot is another site where it shows the same issue in Mobile View:
![screen shot 2015-07-31 at 13 11 39](http://issues.joomla.org/uploads/1/e12ac81acb5aba974da1c610a12ef4a6.jpg)

The reason why I think this is an urgent matter is that all sites that rely on Joomla's Protostar default template and using the default menu system is having this issue.  They may not be aware of it, but it's exits ever since the upgrade to Joomla 3.4.3

Plus there was another report that was fixed that had the same symptoms but for dropdowns to other components (modals).  Though they fixed that issue there, they were not aware of the menu system suffering from the same issue when in responsive view (mobile phones).  Here is the link: https://github.com/joomla/joomla-cms/issues/7301<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7587">issues.joomla.org/joomla-cms/7587</a>.</sub>

**Comment by brianteeman** [comment]
#7301 is completely unrelated to this

On 31 July 2015 at 19:20, Jay-Jay <notifications@github.com> wrote:

> Here are the screenshots and a link where you can see the issue yourself
> with a mobile phone or a tablet:
>
> Site: http://www.djexplosionsd.com/
> First Screenshot shows the site above in Desktop View (long sub-menu and
> no problem there)
>
> [image: screen shot 2015-07-31 at 13 11 39]
> <https://camo.githubusercontent.com/50498f53a171582cb603ba26e8cf4eb44698e8aa/687474703a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f63313835616366303433313232333565626139356237343763323137363435352e6a7067>
> Second Screenshot same site, but mobile view (same long sub-menu cropped
> can't view the rest of it).
>
> [image: screen shot 2015-07-31 at 13 11 39]
> <https://camo.githubusercontent.com/090a78867fefa4b426c2ecddaf1ce239bbecde3e/687474703a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f39393039623163346133393631663131386133333562646338616266636533392e6a7067>
> This third screenshot is another site where it shows the same issue in
> Mobile View:
>
> [image: screen shot 2015-07-31 at 13 11 39]
> <https://camo.githubusercontent.com/075ef5c829892ca30b997473631622361123b381/687474703a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f65313261633831616362356162613937346461316336313061313265663461362e6a7067>
>
> The reason why I think this is an urgent matter is that all sites that
> rely on Joomla's Protostar default template and using the default menu
> system is having this issue. They may not be aware of it, but it's exits
> ever since the upgrade to Joomla 3.4.3
>
> Plus there was another report that was fixed that had the same symptoms
> but for dropdowns to other components (modals). Though they fixed that
> issue there, they were not aware of the menu system suffering from the same
> issue when in responsive view (mobile phones). Here is the link: #7301
> <https://github.com/joomla/joomla-cms/issues/7301>
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/7587
> <http://issues.joomla.org/tracker/joomla-cms/7587>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7587#issuecomment-126775740>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Jay-Jay-OPL** [comment]
I see, so this is a new issue then?  The only reason I mentioned the other ticket was because it had the same effect where the dropdown menu was being cropped.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7587">issues.joomla.org/joomla-cms/7587</a>.</sub>

**Comment by brianteeman** [comment]
It is completely unrelated to that issue

On 31 July 2015 at 19:29, Jay-Jay <notifications@github.com> wrote:

> I see, so this is a new issue then? The only reason I mentioned the other
> ticket was because it had the same effect where the dropdown menu was being
> cropped.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/7587
> <http://issues.joomla.org/tracker/joomla-cms/7587>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7587#issuecomment-126777482>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Jay-Jay-OPL** [comment]
Fine, can we get passed this speed bump?  I am not debating, simply pointing that out in case it helps troubleshoot the issue.

**Comment by MixingOnBeat** [comment]
@Jay-Jay-OPL thanks for reporting this issue.  I am also honored that you used my site's screenshots. www.djexplosionsd.com

I just wanted to let you guys know that we plan to revert back the changes from the template, since many of our visitors are having a difficult time navigating thru the menus.  Ever since the introduction of the button menu, though it looks neat and clean, it introduced this bug and we haven't gotten a word from the devs if they are working on this issue or not?  Or at least a quick-fix while they publish another update at a later time.

Regardless of that issue the other ongoing issue is that for mobile browsers, when you have child menus, it's difficult to also click on them, since the parent menu is the one clickable and it will take you to that page instead.  I wish the timer would be extended so the end-user can select another link under the parent menu.

We use other web software (i.e. phpbb, wordpress, and etc.) and only Joomla has this ongoing problem with how the menu responds to different types of browsers and devices.  Hopefully the developers get together and fix this issue for us, since it's a bit frustrating for the end-users and at the same time making these devs look like amateurs by not being able to fix it for quite some time.  Well that's my opinion, sorry.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7587">issues.joomla.org/joomla-cms/7587</a>.</sub>

**Comment by infograf768** [comment]
Looks like the overflow is set to hidden in responsive-navbarr.less
```
  // Hide everything in the navbar save .brand and toggle button */
  .nav-collapse,
  .nav-collapse.collapse {
    overflow: hidden;
    height: 0;
  }
```
We have to add a css there.
Please test PR:
https://github.com/joomla/joomla-cms/pull/7629

I close this now, please discuss in the new PR

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7587">issues.joomla.org/joomla-cms/7587</a>

**Comment by infograf768** [comment]
See PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7587">issues.joomla.org/joomla-cms/7587</a>.</sub>

**Comment by MixingOnBeat** [comment]
Awesome guys!  The fix given here https://github.com/joomla/joomla-cms/commit/fa38882651daf5715de5252bced80c64c0ff678e to these files fixes the issue on my site.  If you wish to test or verify: www.djexplosionsd.com

I don't know if I should start a new tracker, but is there also a way to fix the time on how long a parent menu with child menus can be pressed on a phone before it becomes active?  

For example, press the "MUSIC" menu on my site with an Android phone, and you'll see a child menu under it.  But it opens briefly not allowing you to select anything else since the parent menu also takes you to a page.  Hopefully you understand what I mean.

**Comment by infograf768** [comment]
Please post your test result here:
http://issues.joomla.org/tracker/joomla-cms/7629
