### ISSUE TITLE
If we apply the filter (search tools), Pagination is not working

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#7588]
#### Steps to reproduce the issue
1. Go to the user manager
2. Apply any filter from the search tool.(Register date)
3. Now apply the pagination

#### Expected result
1. Pagination should work

#### Actual result
1. Pagination is not working![screen shot 2015-07-30 at 07 46 25](http://issues.joomla.org/uploads/1/ad1bd3919f1bb253f2a9a6b6a4bc3c7c.png)

**Comment by Bakual** [comment]
Can you try https://github.com/joomla/joomla-cms/pull/7487?

**Comment by uthorat** [comment]
@Bakual I am an tester, unable to add code. It will be good if you give me patch or it resolved in latest version of joomla :) .

I tried #7487 in patch tester. Which give me following error
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 4 SQL=SELECT COUNT(*) FROM `rl6gy_patchtester_pulls` AS `a` LEFT JOIN `rl6gy_patchtester_tests` AS `t` ON t.pull_id = a.pull_id WHERE (`a`.`title` LIKE '%#7487%') OR (`a`.`pull_id` = #7487).
Can you please help me out this ?
Is it my local issue or component issue ?

**Comment by mbabker** [comment]
Don't use the # symbol when searching items in the component, just enter the number or a title.

**Comment by brianteeman** [comment]
As we have a PR then this should really be closed but I am setting it to Information Required for a few days to give @uthorat time to test it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7588">issues.joomla.org/joomla-cms/7588</a>.</sub>

**Comment by uthorat** [comment]
Hello folks,

Unable to search patch. 
I had installed latest patch tester ie. Patch Tester 2.0.0.beta3
while fetching data, I got fatal error. Can you please check
Fatal error: Maximum execution time of 30 seconds exceeded in C:\xampp\htdocs\test341\libraries\joomla\http\transport\curl.php on line 182

os : Windows 7
joomla - 3.4.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7588">issues.joomla.org/joomla-cms/7588</a>.</sub>

**Comment by uthorat** [comment]
Is this my local machine issue or component issue.
Please advise<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7588">issues.joomla.org/joomla-cms/7588</a>.</sub>

**Comment by brianteeman** [comment]
I have no issue with the component

On 31 July 2015 at 11:14, umesh thorat <notifications@github.com> wrote:

> Is this my local machine issue or component issue.
> Please advise
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/7588
> <http://issues.joomla.org/tracker/joomla-cms/7588>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7588#issuecomment-126634514>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by zero-24** [comment]
@uthorat local maschine / xampp. increase the  Maximum execution time and set it e.g to `120` or `0` (no limit) it is because of the limitations of your local machine.

**Comment by zero-24** [comment]
I can not confirm this issue with the current code base (3.5.0-dev) it works for me.

Feel free to reopen if you still have the same problem with 3.5.0-dev. Thanks
