### ISSUE TITLE
Give the alert if user try to edit multiple records

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#7589]
#### Steps to reproduce the issue
1. Go to any list view ( User list)
2. Select the multiple user.
3. Try to edit the records

#### Expected result
There should be Alert showing, Select only one record for edit

#### Actual result
The very first record get open for edit.![screen shot 2015-07-30 at 08 04 42](http://issues.joomla.org/uploads/1/edaca4387a3d3fcf9c8dcc55b7f5aa4e.png)

**Comment by Bakual** [comment]
I don't think it's really an UX improvement in the end.

Currently you could say it has some intelligent guessing what the user wanted to do and just edits the first one selected. All works as expected (except if you really expected to edit multipe items at once).
If we add a warning box, you would only get a tedious dialog box to click away to get to the edit box. No real issue solved and no UX value added.

I'd say it's a feature the way it works now. Not a bug :smile:

**Comment by uthorat** [comment]
It will be great :)
Lets make it feature :)

**Comment by photodude** [comment]
@Bakual what if the message said " you can only select on item to edit" and gave the user the 3 options they could select from, [edit record one] [edit record two] [return to the list to select a different record]

An alternative that follows the current method, would require altering two of the buttons on the edit page and temporally storing the "selected list of items" to go through for edits. The two buttons to change would be [save & close] and [close] would need to be changed to something like [save & continue] and [close & continue] (meaning continue to the next item in the edit list) a counter would be good to add listing [editing X of Y items/records] and a new button to [close and exit edit list] to close and leave the editing of multiple records. Handling the checkin/checkout could get tricky, but as long as we only checkout/checkin one item at a time from the list, check if the next item that is available from the list, and provide a warning about no records in the list being available to edit. it shouldn't be to bad.

Or for a simple solution we could just hide the edit button if multiple items are selected...

**Comment by brianteeman** [comment]
See #7592 for a perfect solution

**Comment by uthorat** [comment]
Yes.. Its an perfect solution for my issue :)
Thank you
