### ISSUE TITLE
Help popup -> Top link redirects to wrong page

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#7590]
#### Steps to reproduce the issue
1. Click on help (which is on left side of any manager)
2. It will open popup, now increase the size of popup.
3. Go to bottom, you will see the Top.
4. Click on link.

#### Expected result
1. It will redirect to top of the page, not an another page.

#### Actual result
1. It redirects to different page.![screen shot 2015-07-30 at 08 10 08](http://issues.joomla.org/uploads/1/3e72fb371de9101efb668695ded87389.png)

**Comment by mbabker** [comment]
Well unless we coded something wrong in the help proxy's template, that should be working - https://github.com/joomla-projects/help-proxy/blob/master/tpl_help/index.php#L21 - A PR on that repo can get it fixed and we can push the update to the server when ready.

**Comment by uthorat** [comment]
Thank you for quick response.
Yes I will be waiting for that :)

**Comment by brianteeman** [comment]
@mbabker - thats not the correct piece of code. That is just the anchor for the top tag. The problem correctly identified by @uthorat is that the link does not contain the correct url.

I am looking into it now and will create a PR on that repo so closing here<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7590">issues.joomla.org/joomla-cms/7590</a>.</sub>

**Comment by brianteeman** [comment]
I submitted a Pull Request to the help proxy so hopefully will be fixed very soon. Thanks for reporting it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7590">issues.joomla.org/joomla-cms/7590</a>.</sub>

**Comment by mbabker** [comment]
Proxy site is updated.
