### ISSUE TITLE
Media manager-> Extra link present for go to previous folder

### ISSUE THREAD

**Issue by uthorat** [joomla/joomla-cms#7591]
#### Steps to reproduce the issue
1. Go to media manager.
2. Select any folder.
3. You will see the arrow and dotted line for go to prevous folder

#### Expected result
1. There should be one link either arrow or dotted line.
I would prefered the arrow.

#### Actual result
Both arrow and dotted line present![screen shot 2015-07-30 at 09 05 07](http://issues.joomla.org/uploads/1/a6019721573303211d68aaf322d32db6.png)

**Comment by brianteeman** [comment]
To be inconsistent you have to say that something else behaves differently.
That is not the case.
In fact you could say it is being perfectly consistent.

If you look at the information below that you will see a thumbnail image
AND filename in the two columns. BOTH of those are clickable.

So where is the inconsistency?

On 30 July 2015 at 15:05, umesh thorat <notifications@github.com> wrote:

> Steps to reproduce the issue
>
>    1. Go to media manager.
>    2. Select any folder.
>    3. You will see the arrow and dotted line for go to prevous folder
>
> Expected result
>
>    1. There should be one link either arrow or dotted line. I would
>    prefered the arrow.
>
> Actual result
>
> Both arrow and dotted line present[image: screen shot 2015-07-30 at 09 05
> 07]
> <https://camo.githubusercontent.com/d35c2fe7e204ebb82a54aa1cc576ef6a8b0b12be/687474703a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f61363031393732313537333330333231316436386161663332326433326462362e706e67>
> System information (as much as possible) Additional comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7591>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by uthorat** [comment]
@brianteeman I am saying about extra link which redirected to previous folder. 
I am totally agree with you that is "If you look at the information below that you will see a thumbnail image
AND filename in the two columns. BOTH of those are clickable."

There is two link which works same. Is it consistent..???(arrow and dotted line)

**Comment by Bakual** [comment]
I agree with Brian.
It makes more sense when you actually have files in the folder.

**Comment by brianteeman** [comment]
I understand exactly what you are saying and have zero problem with it.

On 30 July 2015 at 15:19, umesh thorat <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> I am saying about extra
> link which redirected to previous folder.
> I am totally agree with you that is "If you look at the information below
> that you will see a thumbnail image
> AND filename in the two columns. BOTH of those are clickable."
>
> There is two link which works same. Is it consistent..???(arrow and dotted
> line)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7591#issuecomment-126345336>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by uthorat** [comment]
Okay :) No issue .
