### ISSUE TITLE
Module Position field is not clickable inside a repeatable field

### ISSUE THREAD

**Issue by webchun** [joomla/joomla-cms#7595]
#### Steps to reproduce the issue
I tried to include Module Position field inside a Repeatable field.

#### Expected result
The repeatable module is show up and then when module position button is clicked the modal is show up and I'm able to add a module position

#### Actual result
The module position modal is showed up but the available module options are not clickable.

When I looked at the browser console I found this error message :
Uncaught TypeError: Cannot set property 'value' of nulljSelectPosition_jform_params_position @ index.php?option=com_templates&view=style&layout=edit&id=9:93onclick @ index.php?option=com_modules&view=positions&layout=modal&tmpl=component&function=jSelectPosition_jf…:108

#### System information (as much as possible)

Chrome 43
Mac OSX Yosemite

#### Additional comments

I have recorded a screencast please have a look here https://www.dropbox.com/s/cuhftczjjemtmu0/jbug.mp4?dl=0

**Comment by brianteeman** [comment]
Thank you for taking the time to report this.

This is a known issue which cannot be resolved with the repeatable field code. However the good news is that we will hopefully be  introducing a new subform feature in the next joomla release which should allow you to do exactly what you want.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7595">issues.joomla.org/joomla-cms/7595</a>.</sub>
