### ISSUE TITLE
Media vertical box size needs increasing.

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#7605]
in the media box for a very long time there has been an issue where the input field is just below the frame so you have to scroll down to access it.  It would be much better of the window size was increased.  Setting it to 722px makes it full size and looks wonderful.
I'm pretty sure the issue is in modal.js but I'm not skilled in jQuery enough to fix it.
```php
resize: function(size, instantly) {
		this.showTimer = clearTimeout(this.showTimer || null);
		var box = this.doc.getSize(), scroll = this.doc.getScroll();
		this.size = Object.merge((this.isLoading) ? this.options.sizeLoading : this.options.size, size);
		var parentSize = self.getSize();
		if (this.size.x == parentSize.x) {
			this.size.y = this.size.y - 50;
			this.size.x = this.size.x - 20;
		}
		if (box.x > 979) {
			var to = {
				width: this.size.x,
				height: this.size.y,
				left: (scroll.x + (box.x - this.size.x - this.options.marginInner.x) / 2).toInt(),
				top: (scroll.y + (box.y - this.size.y - this.options.marginInner.y) / 2).toInt()
			};
		} else {
			var to = {
				width: box.x - 40,
				height: box.y,
				left: (scroll.x + 10).toInt(),
				top: (scroll.y + 20).toInt()
			};
		}
		this.hideContent();
		if (!instantly) {
			this.fx.win.start(to).chain(this.showContent.bind(this));
		} else {
			this.win.setStyles(to);
			this.showTimer = this.showContent.delay(50, this);
		}
		return this.reposition();
	},
```

**Comment by dgt41** [comment]
@N6REJ You might have to re adjust the suggested code due to https://github.com/joomla/joomla-cms/pull/5871
We try to get away from mootools. Also the other PR is with a bootstrap modal which can be adjusted with css overrides 😉

**Comment by N6REJ** [comment]
ok,great... this was taken from the code currently in staging.

**Comment by N6REJ** [comment]
@dgt41 your pr looks like the best solution, should I close this one?

**Comment by dgt41** [comment]
@N6REJ Unfortunately mootools are quite hard to die so even if that PR gets merged sometime, there is a possibility that many users with old templates to still use the old (mootools) code. So I am no so sure if this should be closed. 
But what happens if you change the iframe value for height ? Should be quite easier...

**Comment by brianteeman** [comment]
@N6REJ CAn you please retest the issue with 3.5beta2 - it looks resolved to me but I am not 100% I was checking the correct place.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7605">issues.joomla.org/joomla-cms/7605</a>.</sub>

**Comment by N6REJ** [comment]
@brianteeman the tabbed modal solves the issue completely.  Close as resolved
