### ISSUE TITLE
Notice: Array to string conversion in administrator/components/com_contact/models/contacts.php on line 134

### ISSUE THREAD

**Issue by julienV** [joomla/joomla-cms#7618]
#### Steps to reproduce the issue
use a module that uses the backend model with several categories

#### Expected result
there shouldn't be any notice

#### Actual result
there is a notice
Notice: Array to string conversion in <root>/administrator/components/com_contact/models/contacts.php on line 134

#### System information (as much as possible)
joomla staging branch

#### Additional comments
it's just a samll inconsistency in backend models contact.
The filter category_id is expected to be a numeric or an array in getListQuery function, but the store id function assumes it's a string.
hence, setting the filter to an array triggers a warning:

Notice: Array to string conversion in <root>/administrator/components/com_contact/models/contacts.php on line 134

**Comment by zero-24** [comment]
@julienV If you have code / a pull request you don't need to open a issue :smile:  I will close here and copy the description to your pull request. Thanks :smile:
