### ISSUE TITLE
[3.5] [Regression] Extra Step (Language / Multilanguage Installation) don't work and send a Error

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#7620]
#### Steps to reproduce the issue

- download: http://developer.joomla.org/cms-packages/Joomla_3.5.0-dev-Development-Full_Package.zip
- try to install as normal joomla
- try to open the `Extra step` to install languages etc.
- it aborts with a `could not connect to mysql` issue.

#### Expected result

Extra step opend and we can install a language

#### Actual result

we get a error:
![screen shot 2015-08-03 at 14 27 10](http://issues.joomla.org/uploads/1/7021579d28a7ddf0ff354ad8982a2c7f.jpg)

#### System information (as much as possible)

Same behavior online (webhost) and local.

#### Additional comments

MySQL is up if I refresh the page I see the normal final screen of the installation and can login into the Backend and frontend. So there is no issue with mysql. Maybe we don't have the SQL Database information there?

**Comment by infograf768** [comment]
Confirmed and raised priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7620">issues.joomla.org/joomla-cms/7620</a>.</sub>

**Comment by zero-24** [comment]
Closing as we have a fix by @mbabker here #7626

**Comment by Kubik-Rubik** [comment]
Thank you @zero-24. The fix by @mbabker solves the problem.
