### ISSUE TITLE
Filter doesn't work with repeatable field child

### ISSUE THREAD

**Issue by webchun** [joomla/joomla-cms#7627]
#### Steps to reproduce the issue
I create this code on my xml file :
<pre>&lt;field name="rep_list" type="repeatable" icon="plus" description="List Desc" label="List Label"mdefault=""&gt;
    &lt;fields name="params"&gt;
        &lt;fieldset hidden="true" name="list_templates_modal" repeat="true"&gt;
	    &lt;field name="item_title" type="text" default="" label="Item Title" filter="raw"/&gt;
        &lt;/fieldset&gt;
    &lt;/fields&gt;
&lt;/field&gt;</pre>

#### Expected result

I'm expecting the output of **item_title** will be raw filtered

#### Actual result

Any html tag I entered for **item_title** is always removed

#### System information (as much as possible)

Joomla 3.4

#### Additional comments

The same behaviour is also present with safehtml filter

**Comment by Fedik** [comment]
you need apply filter and validation for the `parent` field `rep_list`, 
in current realisation of the repeatable field the `filter` and `validation` has no effect for children fields

**Comment by webchun** [comment]
Hi, it works. thanks! But what if I have 2 child fields and I need different filter for both of them?

**Comment by Fedik** [comment]
I would recommend write the custom filter, for your needs: `filter="MyComponentHelper::filterListField"`
```php
class MyComponentHelper
{
  public static function filterListField($inputString)
  {
   // ... here some code for filter
   // ... here some code for filter
   // ... here some code for filter
   // ... here some code for filter
    return $fitreredString;
  }

}
```

**Comment by Fedik** [comment]
but I think it is still valid issue,
would be good if Joomla handle it in the core

**Comment by webchun** [comment]
Yes I think so. Thanks anyway for the help

**Comment by webchun** [comment]
Anyway, just want to let you know, I just found that 'showon' also doesn't work with repeatable field childs<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7627">issues.joomla.org/joomla-cms/7627</a>.</sub>

**Comment by Fedik** [comment]
'showon fail'  is known issue, see #7770 and #6882

**Comment by webchun** [comment]
Ok thanks! Btw, I just found out that repeatable field doesn't work in the frontend editing too. It opens dark overlay only

**Comment by zero-24** [comment]
Closing as we have #6882 there @artur-stepien try to prepare a pull request for.

**Comment by Fedik** [comment]
@zero-24 field `Filter` thing do not related to javascript issue in #6882  :wink:

**Comment by zero-24** [comment]
hmm than i missinterpret your comment. Sorry than i reopen here. Thanks.

**Comment by brianteeman** [comment]
Thank you for taking the time to report this.

This is a known issue which cannot be resolved with the repeatable field code. However the good news is that we will hopefully be  introducing a new subform feature in the next joomla release which should allow you to do exactly what you want.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7627">issues.joomla.org/joomla-cms/7627</a>.</sub>
