### ISSUE TITLE
have problems with save close buttons in admin backend

### ISSUE THREAD

**Issue by LucyDemooon** [joomla/joomla-cms#7631]
iam using joomla 3.4.3 and the componente CKEditor
1. i cant edit any in the component menue
2. i cant click on save, save and apply, close button

error in f12 + console:

TypeError: t is null        
/media/system/js/core.js     
Line 1

**Comment by brianteeman** [comment]
Do you have the same issue when not using CKEditor?

**Comment by LucyDemooon** [comment]
its only in the editor config menu, al other working
iam going back to joomla 3.4.1 in this version its working

**Comment by brianteeman** [comment]
DO NOT go back to 3.4.1.

1. Make sure you have 100% cleared your browser cache
If that doesnt work
2. Test to see if it works with the default tinymce editor
If that does work
3. Report the bug to CKEditor - that is not part of the core of Joomla

On 5 August 2015 at 13:38, LucyDemooon <notifications@github.com> wrote:

> Reopened #7631 <https://github.com/joomla/joomla-cms/issues/7631>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7631#event-374142711>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
After several months without reply I am closing this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7631">issues.joomla.org/joomla-cms/7631</a>.</sub>
