### ISSUE TITLE
Users do not see 'Publishing' options with the Edit Own option set.

### ISSUE THREAD

**Issue by fribse** [joomla/joomla-cms#7633]
#### Steps to reproduce the issue

I have created a groups hierachy like this:
![screen shot 2015-08-05 at 08 32 36](http://issues.joomla.org/uploads/1/ea47f3482e872ad2ddcf2175b76cdb46.png)
I have defined rights like this:
![screen shot 2015-08-05 at 08 32 40](http://issues.joomla.org/uploads/1/c9ea09ba9052da445ec805458c0fcedd.png)
#### Expected result

I would expect to see these fields appear because of the 'Edit State' right being set.
![screen shot 2015-08-05 at 08 32 43](http://issues.joomla.org/uploads/1/e53d3384b84cf99e2dbf9b5b0ae23064.png)
#### Actual result

For users that has all the rights enabled, I see these fields. But if I just have the above set, I do not see it. I don't have any 'Forbidden' in the hierachy.
#### System information (as much as possible)

PHP Built On    Linux pro2.blanyecloud.net 2.6.18-471.3.1.el5.lve0.8.72xen #1 SMP Wed Mar 12 18:36:52 EDT 2014 x86_64
Database Version    5.6.23-log
Database Collation  utf8_general_ci
PHP Version     5.5.27
Web Server  Apache/2.2.29 (Unix) mod_ssl/2.2.29 OpenSSL/0.9.8e-fips-rhel5 DAV/2 mod_bwlimited/1.4 mod_perl/2.0.8 Perl/v5.8.8
WebServer to PHP Interface  cgi-fcgi
Joomla! Version     Joomla! 3.4.3 Stable [ Ember ] 2-July-2015 16:00 GMT
Joomla! Platform Version    Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

**Comment by osignell** [comment]
This seems to be the same thing as issue #7633 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7633">issues.joomla.org/joomla-cms/7633</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Cannot confirm Issue, tested on Joomla! 3.7.0-beta1.

**Comment by Bakual** [comment]
Closing as fixed in the meantime.
