### ISSUE TITLE
postStoreProcess tag method replaces all tags when false is set

### ISSUE THREAD

**Issue by joewebber** [joomla/joomla-cms#7635]
Caused by improper operator in /libraries/cms/helper/tags line 807, which should read:

`if (!$newTags && $replace == true)`

**Comment by Bakual** [comment]
Can you do a PR? Since you already propose a solution.
https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests explains how to create a PR using the web UI.

**Comment by Bakual** [comment]
Closing as we have a PR.
