### ISSUE TITLE
Back-end com_content "Images and Links" tab, Full Article Image mouseover tooltip...

### ISSUE THREAD

**Issue by JimDee** [joomla/joomla-cms#7647]
When you're on the back end inserting images... If you insert one image as the Intro image, and then another as the Full Article image.... If you then mouseover the intro image field (next to the eyeball) to get a preview of the path, that one shows the correct path in the little popup. However, if you mouseover the *full* article image field, the preview of the path shows the path for the intro image there. Tried this on 2 different sites on 3.4.3 and 3.4.1, so it's probably been there for a while... Probably just some adjustment in an XML file or something, but I wasn't sure where...

**Comment by JimDee** [comment]
Clarification: It could also be that the mouseover only shows the most *recently added* path in both places (e.g., if you add a full article image first, then the path in the popup is correct, but if you then add an intro image, then the preview path shows the full one).

**Comment by brianteeman** [comment]
This is a known issue with repeating fields but without a fix yet . see #6799<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7647">issues.joomla.org/joomla-cms/7647</a>.</sub>

**Comment by JimDee** [comment]
Ahh, yep!  Thanks.
