### ISSUE TITLE
Joomla - Menu save action overwrites third party changes.

### ISSUE THREAD

**Issue by vmindru** [joomla/joomla-cms#7651]
#### Steps to reproduce the issue

This video was recorded for Joomla Art as well. 
https://youtu.be/XH-dzwYG-oU 

1) Amend a submenu in a  menu  with MegaMenu, add 1 extra column. 
2) Open any menu that is part of the "menu" above and just click save.
3) The columns of submenu got overwritten. 

#### Expected result

mm_config settings do not get overwritten 

#### Actual result

mm_config settings :{\"rows\":[[{\"item\":157,\"width\":6},{\"item\":160,\"width\":6}]]},\"alignsub\":\"justify\"},\"item-151\":{\"sub\":{\"rows\":[[{\"item\":152,\"width\":12}]]}}}  get's removed 

#### System information (as much as possible)

Joomla: 3.4.3
Purity III: 1.1.5
T3:  2.5.0

**Comment by brianteeman** [comment]
This is not an issue with the core of Joomla.

**Comment by vmindru** [comment]
Same issue here: https://www.youtube.com/watch?v=XH-dzwYG-oU megamenu get's overwritten. 

[root@srv3 2]# diff v2 v1
17c17
<     "mm_config": "{\"mainmenu\":{\"item-101\":{\"sub\":{\"rows\":[]}}},\"mainmenu-cz\":{\"item-148\":{\"sub\":{\"rows\":[[{\"item\":157,\"width\":6},{\"item\":160,\"width\":6}]]},\"alignsub\":\"justify\"},\"item-151\":{\"sub\":{\"rows\":[[{\"item\":152,\"width\":12}]]}}},\"menude\":[],\"menucz\":[],\"mainmenu-en\":[],\"mainmenu-ru\":[]}", 
---
>     "mm_config": "{\"mainmenu\":{\"item-101\":{\"sub\":{\"rows\":[]}}},\"mainmenu-cz\":{\"item-148\":{\"sub\":{\"rows\":[]},\"alignsub\":\"justify\"},\"item-151\":{\"sub\":{\"rows\":[[{\"item\":152,\"width\":12}]]}}},\"menude\":[],\"menucz\":[],\"mainmenu-en\":[],\"mainmenu-ru\":[]}", 
[root@srv3 2]# 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7651">issues.joomla.org/joomla-cms/7651</a>.</sub>

**Comment by vmindru** [comment]
ups sorry that was ment for another github ... <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7651">issues.joomla.org/joomla-cms/7651</a>.</sub>
