### ISSUE TITLE
Getting Error while moving site from wamp to live server

### ISSUE THREAD

**Issue by sandijai** [joomla/joomla-cms#7652]
Hi,
I am getting erroe when I upload joomla website- 
Error displaying the error page: Application Instantiation Error: Table 'amberqac_kidoonew.ic27d_session' doesn't exist SQL=SELECT `session_id` FROM `ic27d_session` WHERE `session_id` = 'ufmt3dhh3tb6gevd61hbor4nf0' LIMIT 0, 1

Wamp DB- 
public $dbtype = 'mysqli';
	public $host = 'localhost';
	public $user = 'root';
	public $password = '';
	public $db = 'kidoojom';
	public $dbprefix = 'ic27d_';

Live DB- public $dbtype = 'mysqli';
	public $host = 'localhost';
	public $user = 'amberqac_kidoon';
	public $password = 'Hidden';
	public $db = 'amberqac_kidoonew';
	public $dbprefix = 'ic27d_';
Please guide me.

**Comment by rdeutz** [comment]
Best bet on this is that you made a mistake when moving the database. Don't think it is a Joomla-Bug. Check if you have the session table

**Comment by brianteeman** [comment]
For support on this you would be better using the forum. http://forum.joomla.org
