### ISSUE TITLE
JImage - transparent PNG quality

### ISSUE THREAD

**Issue by n3t** [joomla/joomla-cms#7655]
Joomla 3.x introduced some changes to JImage class which influence quality of resized PNGs with transparency. To demonstrate it see this images:

Original
![test](https://cloud.githubusercontent.com/assets/979699/9148333/c612810e-3d78-11e5-95b6-9b5e51717c75.png)

Resized in Joomla 2.5
![j25](https://cloud.githubusercontent.com/assets/979699/9148336/d3e9f8b6-3d78-11e5-8f38-c8a139d76a8c.png)

Resized in Joomla 3
![j30](https://cloud.githubusercontent.com/assets/979699/9148345/012a07e4-3d79-11e5-84b8-ab1ee26b0376.png)

Test code to resize is
```php
      $original = new JImage($src);
      $original->resize(140,140,false, JImage::SCALE_INSIDE);
      $original->toFile($dest,IMAGETYPE_PNG);
```

Tested on PHP 5.3.29 with GD 2.1.0 compatible, libPNG 1.6.12 
and on PHP 5.5.27 with GD 2.1.0 compatible, libPNG 1.2.49

this behavior is caused by setting explicitly transparent color in loadFile method. For some reason isTransparent() returns false in this case, so transparent color is set explicitly causing the image look like that. 

I am not sure why this code is at this place (loading image), as it seems to solve black background issue, when SCALE_FIT is used on resizing. However in resize method it is introduced again.

**Comment by n3t** [comment]
This patch solves the issue
https://github.com/n3t/joomla-cms/commit/6755fdfa52969cc4b38664f8862bdd7449d42837

**Comment by brianteeman** [comment]
Please submit that as a pull request

**Comment by n3t** [comment]
Pull request here https://github.com/joomla/joomla-cms/pull/7658

**Comment by Bakual** [comment]
Closing this issue since we have a PR.
