### ISSUE TITLE
Accordion on beez' contact page is broken

### ISSUE THREAD

**Issue by Harmageddon** [joomla/joomla-cms#7662]
This issue was first reported by the users Stefan4 and christine2 at a German support forum and confirmed by me. [Original Thread](http://www.joomlaportal.de/joomla-3-x-erweiterungen-komponenten/321425-kontakt-von-joomla-3-4-klappt-nicht-aus.html)

#### Steps to reproduce the issue
1. Create a contact linked to a user and enter some information (address, social media, misc. information).
2. Create a menu item for the contact:
  - Type: Single Contact
  - Contact Display Options - Display Format: Sliders
3. Set Beez3 as the template for this menu item (or as the default template for the whole site).
4. View the page in front end.

#### Actual result
After the page is loaded, all accordions are open, though only one should be. When you click on an accordion heading (Contact, Contact form, Links, Misc. information), the display changes a little, but it doesn't show or hide anything. On further clicks on the same heading, nothing happens at all.

I searched some time back, but couldn't find a state where this worked. Seems like the whole accordion functionality is missing in Beez.

And the next potential issue: Tabs don't seem to be supported at all in Beez' contact override. There is actually no occurrence of "Tab" in [templates/beez3/html/com_contact/contact/default.php](https://github.com/joomla/joomla-cms/blob/staging/templates/beez3/html/com_contact/contact/default.php).

**Comment by n9iels** [comment]
Confirmed, see the referenced pull request for the solution.
Thanks for reporting!

**Comment by zero-24** [comment]
Closing as we habe a Pull Thanks. https://github.com/joomla/joomla-cms/issues/8068
