### ISSUE TITLE
This webpage has a redirect loop Error

### ISSUE THREAD

**Issue by sandijai** [joomla/joomla-cms#7668]
Hi,
This site was working fine -http://kidoo-qa.com/kidooqa
Suddenly I am getting this error, I deleted all cookies but getting this error.
This webpage has a redirect loop
ERR_TOO_MANY_REDIRECTS

**Comment by Bakual** [comment]
Make sure all installed languages have a proper access level set. I remember that being an issue.
Other than that, please use the forums (http://forum.joomla.org/) for support requests.

This is the issue tracker for core itself.

**Comment by sandijai** [comment]
Hi,

Thank you but I am trying to create id here (http://forum.joomla.org/) but it is not allowing me to create a id.

I will really appreciate if you can help me to solve this problem. Because I design a new website http://kidoo-qa.com/kidoo and after sometime I faced this problem.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7668">issues.joomla.org/joomla-cms/7668</a>.</sub>

**Comment by Bakual** [comment]
Please see the FAQ there on the forums and ask one of the admins there.

**Comment by zero-24** [comment]
You need to register here: http://forum.joomla.org/ucp.php?mode=register 

This issue exists since 3.4.0. Please check your postinstall messages for more informations ;)

**Comment by infograf768** [comment]
Check if the issue is not the one here: https://github.com/joomla/joomla-cms/issues/7670 (i.e. not a multilang site)
