### ISSUE TITLE
Site goes into redirect loop - version 3.4.3

### ISSUE THREAD

**Issue by dhaval-desai** [joomla/joomla-cms#7670]
#### Steps to reproduce the issue

Create a brand new 3.4.3 site 
> Trash the article related to the default menu item 
> Now set the site to offline from Global Configuration. 
> grab popcorn and watch the front end go to redirect loop. 

#### Expected result

> Site should show offline page

#### Actual result

> Site shows redirect loop. 

#### System information (as much as possible)

Fresh Joomla 3.4.3 install

**Comment by infograf768** [comment]
Confirmed. It is sufficient to unpublish the article concerned.

**Comment by Kubik-Rubik** [comment]
Changed priority to "Low" according to our rules: https://docs.joomla.org/Bug_and_Issue_Tracker_Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7670">issues.joomla.org/joomla-cms/7670</a>.</sub>

**Comment by infograf768** [comment]
See PR here:
https://github.com/joomla/joomla-cms/pull/7676

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7670">issues.joomla.org/joomla-cms/7670</a>

**Comment by infograf768** [comment]
Closing as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7670">issues.joomla.org/joomla-cms/7670</a>.</sub>

**Comment by sandijai** [comment]
I am very new on joomla. Can somebody help to solve this problem.
Site is not a multilingual site. Language plugin is disable. 
Error- 
The page isn't redirecting properly

Firefox has detected that the server is redirecting the request for this address in a way that will never complete.

http://kidoo-qa.com/kidoo/?id=131

**Comment by Kubik-Rubik** [comment]
@sandijai This is not the place for support requests. Please ask your question in the forum: http://forum.joomla.org/

**Comment by sandijai** [comment]
What kind of question I can ask here? In forum I am not able to register , tried to contact administrator also but not result. 
I have this issue that's why I posted here.

**Comment by Bakual** [comment]
> What kind of question I can ask here? In forum I am not able to register , tried to contact administrator also but no result. 
I have this issue that's why I posted here.

This is really not the place to ask (support) questions. That's exactly what the forum is for. So please don't ask here anymore. The forum administrator will likely answer your request, just give them some time.
