### ISSUE TITLE
Marketing for Joomla: Include newsfeed module in backend control panel

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-cms#7678]
To make marketing communication for joomla easier it would be nice to have a backend module showing the newsfeed of the origin of chosen language. If no newsfeed is defined there could be a fall back to joomla.org Newsfeed.

With something like this we can reach more people who are using joomla and are not involved in the community yet. Publish Events like Joomla User Groups, Joomladays, JandBeyond, Worldconference and calling for volunteers.

**Comment by asysta** [comment]
very useful feature to promote news.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7678">issues.joomla.org/joomla-cms/7678</a>.</sub>

**Comment by infograf768** [comment]
What do you exactly mean by
"the newsfeed of the origin of chosen language. "

**Comment by designbengel** [comment]
I mean that each languagefile could contain the newsfeed link to the official newsfeed of the appropriate country.
For example german users would see the newsfeed of joomla.de with news about next usergroups, next joomladays, next international events. If none is set it could have a fallback to the joomla.org newsfeed. 

I think there is much potential to boost the reachability of people using joomla and to get them (more) involved in the community. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7678">issues.joomla.org/joomla-cms/7678</a>.</sub>

**Comment by infograf768** [comment]
IMHO, this could be done by anyone releasing a custom distribution (with the included newsfeed module), not in core.
Please imagine the issues:
How to decide which site will represent a language? It is not because it includes joomla in the site name that it is the best one for that language and contains equivalent content to joomla.org.

**Comment by Bakual** [comment]
From what I remember we used to have a feed module active in earlier Joomla Versions, but it was removed for a reason. Maybe it delayed the pageload or caused issues when the feed wasn't available. I don't remember.

**Comment by brianteeman** [comment]
It is still there in the postinstall messages.

There were numerous performance reasons why it was removed from the default
control panel AND it wouldnt work if you were behind a firewall such as on
an intranet

On 11 August 2015 at 12:03, Thomas Hunziker <notifications@github.com>
wrote:

> From what I remember we used to have a feed module active in earlier
> Joomla Versions, but it was removed for a reason. Maybe it delayed the
> pageload or caused issues when the feed wasn't available. I don't remember.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7678#issuecomment-129803493>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by asysta** [comment]
is it possible to integrate the news feed from each country in the suitable language ini file?
i mean when you install your language file, then you receive the right news Feed Url of the suitable country.

A solution for the performance or Firewalls are you can decide if you want the news feed in the installation process of joomla.

**Comment by Bakual** [comment]
> A solution for the performance or Firewalls are you can decide if you want the news feed in the installation process of joomla or not.

You can decide if you want them after the installation process already today. Just create the module and assign it to the cpanel :smile: 
I would not want to add such options into the installation itself.

**Comment by asysta** [comment]
i agree Thomas, but not all users are able to disable an admin module :-)

**Comment by Bakual** [comment]
I actually meant the other way. You can enable it after installation.

Honestly, there isn't so much on any news feed that justifies having the feed in the cpanel by default.

**Comment by asysta** [comment]
no effect for Marketing. no one enable that.

**Comment by Bakual** [comment]
> no effect for Marketing. no one enable that.

Agreed. Maybe also because nobody wants advertisment (even from Joomla itself) in their backend.

**Comment by asysta** [comment]
Please read the post at the top - sorry i called it marketing...

Publish Events like Joomla User Groups, Joomladays, JandBeyond, Worldconference and calling for volunteers.

**Comment by mbabker** [comment]
I agree that it's not something that should be enabled by default in the admin, for loads of reasons (behind a firewall/proxy, connectivity issues, etc.).  Adding a module to the install that's disabled would be a fair compromise but is about as useful as the current situation with no module.  And no, I would not suggest yet another option in our option happy CMS to enable/disable this in the installer.

**Comment by designbengel** [comment]
I understand your point regarding connectivity and on - but there should be a way to reach the users somehow and i thought this would be the easiest way... Are there another suggestions to get in touch with the enduser?

**Comment by asysta** [comment]
an admin module with a newsfeed is the easiest way to inform all users about interesting events and so on. country specific, Is there any way to have a admin module with the title news joomla newsfeed without the feed. you must activate the feed with a button , but you see the box in the admin panel , so the user can activate that if he wants, is this a solution?

**Comment by mbabker** [comment]
That would mean coding a brand new module specific for that use case instead of reusing the existing feed module.  In general, I don't think this (trying to engage users more) is a bad idea, I'm just not convinced loading feeds into the admin dashboard is the best option (but there really aren't many others).

Also, for it to be a country specific thing, the language packages would have to alter the module or load in a new one.  I wouldn't suggest coding that logic into this module too.

**Comment by brianteeman** [comment]
Sorry but you are assuming that the majority of site owners even know what
Joomla is and would be interested in the contents of the feed. Of the
millions of web sites using Joomla probably a very small % would be
interested in the contents of that feed.

On 11 August 2015 at 16:04, Michael Babker <notifications@github.com> wrote:

> That would mean coding a brand new module specific for that use case
> instead of reusing the existing feed module. In general, I don't think this
> (trying to engage users more) is a bad idea, I'm just not convinced loading
> feeds into the admin dashboard is the best option (but there really aren't
> many others).
>
> Also, for it to be a country specific thing, the language packages would
> have to alter the module or load in a new one. I wouldn't suggest coding
> that logic into this module too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7678#issuecomment-129890909>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by asysta** [comment]
I see this completely different.
why are Newsfeeds used in other system?
To inform about relevant news.

**Comment by brianteeman** [comment]
And my point is that for the majority of site owners this information is
NOT relevant

On 11 August 2015 at 16:14, asysta <notifications@github.com> wrote:

> I see this completely different.
> why are Newsfeeds used in other system?
> To inform about relevant news.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7678#issuecomment-129897508>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by asysta** [comment]
two different positions :-)

**Comment by Bakual** [comment]
My point is that it still is advertising for Joomla. And honestly, I doubt that newsfeed will contain any useful up-to-date information. Especially if it is country specific.

**Comment by designbengel** [comment]
We are trying to increase the ticket sells for joomladay germany, and that was one idea how to reach users which never heard of a joomladay - that´s why i opened this as a feature request. I understand your points about connectivity and on. It would be nice to have a brainstoring if there are other ways to reach all users?

**Comment by alikon** [comment]
Please do not put any kind of advertising in core, there are a lot of others channels and *.joomla.org sites for this kind of stuff

**Comment by asysta** [comment]
sorry i dont understand this opinion. We can use this feed for important information for users , country specific. The user should take the decision whether he wants the information feed or not.
Thats my opinion. Why should a user go to the the homepage joomla.org when he lives in germany oder, france spain or china. He wants information about joomla, Events, User Groups in his own language. Please see it from the user perspective.

**Comment by designbengel** [comment]
My customers do not have any contact to joomla.org or joomla.de site. I have to inform each one about joomladays and joomlausergroups. I bet not many integrators are informing their customers about that. It´s not about advertising - it´s more about community work and getting people involved into the community.

**Comment by alikon** [comment]
I know I'm a bit radical on this matter, 
"out the merchants from the temple"  , a lot of end users don't care about news of jevents or jcommunity and so on ,  in my opinion the backend is not the right place

**Comment by asysta** [comment]
Is there an alternative technology to a news Feed in the backend end possible to inform users.
I see no alternative than the backend

**Comment by infograf768** [comment]
1. Even if the confusion between language and country did not exist (and it does exist!)

2. Even if there were some sites providing this type of information per country (through IP checking and therefore NOT through the language files)

3. Even if the project was able to define which site in each country should be accepted (I have explained above why it is not possible and could lead to endless battles between theses site to become officially accepted). 
NOTE: this is why the language packs from the Translation Teams are "registered" and not "official" to show clearly that Joomla! project is not responsible for the translations provided.

In any case, Joomla project should NEVER provide in official releases a link to content from sites not belonging and controlled by the project. 
The reason is very simple: legal responsibility.
The project is totally unable to perform this control. 
Sites not belonging to the joomla.org family of sites are owned independently and such an automatic display could lead to real issues (wrong information, political messages, religious proselytism, etc.)

I suggest to close this issue.

**Comment by asysta** [comment]
not particularly constructive. I thought we were a community to discuss ideas .
It is possible that this is the wrong place to discuss this.

**Comment by infograf768** [comment]
>not particularly constructive.

What is not? The bare facts? 
Never wrote the question should not be posted and the idea not discussed. 
I just replied with what I think is the only possible reply to anyone proposing to include in releases such stuff. Sorry if you do not like it.

**Comment by Hils** [comment]
It is constructive @asysta and a valid comment from @infograf768 . 

The individual devs should be quite able to add a newsfeed if it is required, just as they can add content. In my view, Joomla 3x should stay as designed - a content management system - not a vehicle for Joomla marketing or news. If JUGS & JDay organizers feel they want to get local info to their users, they could always provide an extension ;)

**Comment by designbengel** [comment]
As i wrote above i do absolutely understand your points. 
I use Joomla since 2006 but i´m not involved that long in the community itself. 
Last JandBeyond i concluded in the "make it happen" session - that there is a wish to increase and strenghten the community. So i thought about this need and this was my idea how to get more people involved in the community. I don´t know about topics which were already discussed and features which are absolutely not wanted. So i close this topic - and maybe there will be someone arround at Joomladay germany or JandBeyond 2016 to discuss another ideas regarding this.

**Comment by Hils** [comment]
@designbengel it was a thoughtful idea & I hope you get more feedback from a JoomlaDay brainstorm! Good luck and welcome to our community :)
