### ISSUE TITLE
Backend: Tracking User activity (after permission) for better UX

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-cms#7679]
A plugin which tracks the click activity of a user could give us important informations about improving the usability of the backend. Of course only after user permission. Sending data could be included in the update process of joomla...

**Comment by mbabker** [comment]
Generally I think this is a good idea for the UX team.  But, this is something I'd be cautious about including into the core distro.

**Comment by dgt41** [comment]
@designbengel there was a proposal once again about this (can find it at the moment)
Also there are at least two repos with that:
https://github.com/eaxs/User-Activity
https://github.com/lahmizzar/PF_UserActivity

**Comment by dgt41** [comment]
Ahh sorry, misread this, the part of sending the data back to a Joomla server is not there on those links I posted above! But that will be a way to much sensitive data that people might not be willing to give away, just saying

**Comment by designbengel** [comment]
Maybe there could be a group of integrators, which are involved in the community and are willing to take part in those statistics. If 100 people install it on 10 Backends there would be a base of 1000 sites. 
I think such a click statistik would be quite enough to learn more about the users needs. Another Option could be to make a big survey and spread it everywhere.

**Comment by Fedik** [comment]
> Another Option could be to make a big survey and spread it everywhere.

I think it good idea, and require less human resources to support it, than for support "Tracking User activity" system.
Survey can be made after month of the latest joomla release, major or minor. Or before some changes. Or to find out with decision in some discusion.

**Comment by designbengel** [comment]
Seems the PLT had the same idea :)
http://developer.joomla.org/news/625-plt-goals-2015.html
"Objective 8.1: Gather anonymous usage information

For the 3.x branch, enhance the stats plugin started by Don Gilbert and merge it into core with a post-install message allowing users to enable the plugin. It cannot be an option in the installer due to third party install applications nor can it be an opt-out plugin due to legal and privacy concerns. In conjunction, deploy the server to collect and display the data. The server needs to be hardened to make spoofing false data extremely difficult.

Plugin code: https://github.com/dongilbert/jstats-plugin

Server code: https://github.com/dongilbert/jstats-server"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7679">issues.joomla.org/joomla-cms/7679</a>.</sub>

**Comment by chrisdavenport** [comment]
The proposed plugin will absolutely NOT track user activity.  That is not its purpose.  The intention is to gather statistics about platforms and versions so we can make informed decisions about such things.

**Comment by brianteeman** [comment]
Setting this Feature Request to needs review so that PLT can make a decision if this is something to pursue or not.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7679">issues.joomla.org/joomla-cms/7679</a>.</sub>

**Comment by wilsonge** [comment]
If the UX team need this then we can code it for them - but it's not something we would include by default. Just getting the existing basic server info was like pulling teeth out and to feature creep that would justify many of the arguments people came up with...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7679">issues.joomla.org/joomla-cms/7679</a>.</sub>

**Comment by lilliann123** [comment]
Honestly, Joomla is a good Content Management System but it's not very savvy with social networking, which in this day and age is pretty crucial. Centralpoint, however, contains every needed tool that you would want with a CMS and it is very savvy with social media, full screen video, and tons of other handy tools.  Using social media with Centralpoint was a breeze. I created a taxonomy type to define what went to social and made a rss feed that pulled that category. Now I can auto-schedule posts right from a central hub. Supporting full screen video is a great feature. It has to be uploaded in a special format, but the way it changes the site experience is great. I've never seen an easier system to customize modules with. I can add a few lines of xml in the module designer and the module now has the fields & functions for me to call within the page. Then I use a CP script to reference the field for display, and it's there and functioning...display, search, syndication, forms management...all in a shot. Every moment I shave off my day in speed I can use to innovate the system vs. maintain the train.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7679">issues.joomla.org/joomla-cms/7679</a>.</sub>
