### ISSUE TITLE
Joomla Truck Factor

### ISSUE THREAD

**Issue by gavelino** [joomla/joomla-cms#7682]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **Joomla** and obtained a value of **7**.

The developers responsible for this TF are:

Jean-Marie Simonet - author of 33% of the files
Michael Babker - author of 22% of the files
Andrew Eddie - author of 20% of the files
Rob Schley - author of 12% of the files
Johan Janssens - author of 10% of the files
Rouven WeÃŸling - author of 10% of the files
Elin Waring - author of 7% of the files

To validate our results, we would like to ask **Joomla** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **Joomla**?

(b) Do you agree that **Joomla** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **Joomla** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by brianteeman** [comment]
If you really look at the data properly you will see that all but two of
those people has not been a contributor for several years. In one case for
at least six years. So I gueß you can say we survived your bus factor. As a
PhD student I really would have expected you to spot that.

Also you are looking at commits which is not necessarily the same as code
authorship.

**Comment by mbabker** [comment]
Another thing that makes some of these numbers a little difficult to accurately measure is the fact that until the end of 2011, Joomla was using SVN for its source control (which tracks authorship differently than Git).  So for data from 2005 until the end of 2011, most of the authorship is going to be the individual who committed the change to the code base which isn't necessarily the individual who authored the change (luckily Git tracks that much better).

As Brian pointed out, 5 of the 7 you listed have largely been inactive for years (one does have recent commit activity for the first time in several years).  So answering the question about whether Joomla would be in trouble if those folks left the project, you'll find the answer is no.

Using data from here on GitHub, the [last 12 months](https://github.com/joomla/joomla-cms/graphs/contributors?from=2014-08-11&to=2015-08-11&type=c) shows at least 60 different commit authors to the repository.  So while some folks may have larger numbers or have touched higher numbers of lines of code, I think this would further solidify the argument that Joomla is not driven by a small number of developers.

**Comment by brianteeman** [comment]
How did you manage to determine that there were multiple authors for some
of the code? I assume you did as the seven you list are responsible
(according to your data) to more than 100% of the code.

**Comment by brianteeman** [comment]
This is not the place to discuss this. This is for code not trying to find validation for your flawed research as already pointed out above and elsewhere https://news.ycombinator.com/item?id=9874503
