### ISSUE TITLE
JModelAdmin class - method publish -

### ISSUE THREAD

**Issue by PhocaCz** [joomla/joomla-cms#7696]
Hi, 
Test environment: Joomla! 3.4.3 (13.1.0), PHP 5.5.6, MySQL 5.6.14

**JModelAdmin** class - method **publish()** includes the following code:

```php
JPluginHelper::importPlugin($this->events_map['change_state']);
```
( libraries\legacy\model\admin.php )

which then calls this event: **PlgContentJoomla** class method **onContentChangeState**
( plugins\content\joomla\joomla.php )

which throws an error for 3pd extensions which do not use Joomla!'s categories table:

Error:

**Unknown column 'a.state' in 'field list' SQL=SELECT a.id,a.state AS state, c.published AS cat_state,a.access, c.access AS cat_access FROM jos_3pd_extension AS a LEFT JOIN jos_categories AS c ON c.id = a.catid WHERE a.id = 3**

I didn't find any option to disable running this event for 3pd extensions (maybe my knowledge on this event handler is not sufficient) 

Thank you, Jan

**Comment by Bakual** [comment]
I don't see where that plugin method does run a query using "a.state". Are you sure this one is the source?
Also we use different state fields in core already. Eg `com_newsfeed` uses `published` and `com_content` uses `state`, so there should be a way to fix that somehow as it seems to work for both those components.

**Comment by AteDev** [comment]
The event "onContentChangeState" dont use context, triggering this event call all the method
[onContentChangeState](https://github.com/joomla/joomla-cms/blob/staging/plugins/content/joomla/joomla.php#L284-L300)

**Comment by PhocaCz** [comment]
Hi, thank you for the info, yes, I see it now, the "onContentChangeState" does not call this SQL, it is caused by SmartSearch plugins ( FinderIndexerAdapter class category changestate method).

I will try to find what is wrong there (relationship between extension: component and its finder (smart search plugin) and component which does not use standard Joomla! category feature), unfortunately for now I cannot say what exactly is causing this error, so maybe this issue should be marked as unconfirmed.

Thank you, Jan

**Comment by Bakual** [comment]
The smart search plugins should only trigger on their own extensions. So unless you use a context from another extensions, then they shouldn't do anything.

**Comment by Bakual** [comment]
>  so maybe this issue should be marked as unconfirmed.

I'm just going to close it for now. You can always open a new one or request this one to be reopened.
