### ISSUE TITLE
Please help to solve the problem with Joomla

### ISSUE THREAD

**Issue by makabs** [joomla/joomla-cms#7700]
Recently moved to another site hosting, then there were these mistakes. In joomle multiyazynost used, and this function does not work
This is a error code: 
Notice: Array to string conversion in /var/www/vhosts/weburl/httpdocs/libraries/joomla/cache/cache.php on line 585

Notice: Array to string conversion in /var/www/vhosts/weburl/httpdocs/libraries/joomla/cache/cache.php on line 585

**Comment by Bakual** [comment]
Please use the forums for support requests: http://forum.joomla.org/

This is the issue tracker for bugs in Joomla core and not the appropriate place for such requests. Thanks.
