### ISSUE TITLE
Categories are not reindexed on save

### ISSUE THREAD

**Issue by tgv604** [joomla/joomla-cms#7711]
#### Steps to reproduce the issue
1) Have smart search enabled incl. "categories" finder plugin
2) Edit a category: change title/alias/description, but do not touch state or access. Save.
3) Search for a relevant keyword to get this category in search results

#### Expected result
Updated title/alias/description of the category in search result

#### Actual result
Old title/alias/descriptipon

#### Additional comments

I believe a closing bracket should be moved from line 136 to line 133 in categories.php finder plugin. 

```php
			if (!$isNew && $this->old_access != $row->access)
			{
				// Process the change.
				$this->itemAccessChange($row);

				// Reindex the category item.
				$this->reindex($row->id);
			}
```
to  become 

```php
			if (!$isNew && $this->old_access != $row->access)
			{
				// Process the change.
				$this->itemAccessChange($row);
			}

			// Reindex the category item.
			$this->reindex($row->id);			
```

**Comment by laoneo** [comment]
Created a PR for this issue https://github.com/joomla/joomla-cms/pull/7769.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7711">issues.joomla.org/joomla-cms/7711</a>.</sub>

**Comment by laoneo** [comment]
Looks like that an issue is opened automatically http://issues.joomla.org/tracker/joomla-cms/7769.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7711">issues.joomla.org/joomla-cms/7711</a>.</sub>

**Comment by zero-24** [comment]
yes @laoneo If you add a pull we have a new item and going to close the original issue here :smile: Thanks
