### ISSUE TITLE
Exceptions when sorting feeds 'oldest first' in stead of 'newest first'

### ISSUE THREAD

**Issue by ronaldhoek** [joomla/joomla-cms#7727]
#### Steps to reproduce the issue

Create new newsfeed with the url:

    http://www.volleybal.nl/application/handlers/export.php?format=rss&type=vereniging&programma=8151&iRegionId=7000

On the 'Display' tab, set the 'Feed Display Order to' 'Oldest first'
Load the feed using an menu-item or some others means.

#### Expected result

No errors!

#### Actual result

The following errors are displayed (along the the content)

    Notice: Undefined property: stdClass::$items in D:\Xampp\htdocs\hwvvbenevia\components\com_newsfeeds\views\newsfeed\view.html.php on line 191

    Warning: array_reverse() expects parameter 1 to be array, null given in D:\Xampp\htdocs\hwvvbenevia\components\com_newsfeeds\views\newsfeed\view.html.php on line 191

#### System information (as much as possible)

Using Joomla 3.4.3
- XAMPP 3.2.1
- Apache/2.4.16 (Win32) OpenSSL/1.0.1p
- PHP/5.6.11
- MySQL 5.6.25

#### Additional comments

To remove the error, modify line 69 `$items = $categoryModel->getItems();` in the following `$item->items = $categoryModel->getItems();`

The error will no longer be shown, however it seems the sorting functionality does not work art all :(.
Maybe a result of the complete rewrite of the newsfeed code starting with Joomla 3.0

**Comment by peterpeter** [comment]
I can confirm this issue - in 3.4.5 and staging. 
The fix above fills only the empty var `$items` that is used in a `array_reverse()`. So the notice disapear. However, `$items` is not used for displaying the feed, and thus the ordering 'oldes first' not comes into effect.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7727">issues.joomla.org/joomla-cms/7727</a>.</sub>

**Comment by peterpeter** [comment]
I had a little time, so made a PR/Fix for that issue: #8347 ready for testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7727">issues.joomla.org/joomla-cms/7727</a>.</sub>

**Comment by zero-24** [comment]
Thanks. Closing as we have a PR :)

**Comment by ronaldhoek** [comment]
Working perfectly - thanks!
