### ISSUE TITLE
components/com_contact/views/contact/tmpl/default_form.php/L24

### ISSUE THREAD

**Issue by PhM1936** [joomla/joomla-cms#7728]
#### Steps to reproduce the issue
In components/com_contact/views/contact/tmpl/default_form.php on line 24 `</fieldset>` is missing `</fieldset>`

#### Expected result
Hover aspect of the formular is improuved for Name, E-mail, … .

**Comment by PhM1936** [comment]
One more point … The place to write the "Subject" is too large and goes outside the frame of others items (name, … ). I overcomme the difficulty by adding "max-width: 95%" on protostar/template.css L1635 ( I use it for my site) but I leave the choice of a better solution to some expert … I am not an informatician. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7728">issues.joomla.org/joomla-cms/7728</a>.</sub>

**Comment by zero-24** [comment]
Hi @PhM1936

>In components/com_contact/views/contact/tmpl/default_form.php on line 24 </fieldset> is missing </fieldset>

I can't find the missing `</fieldset>` in the current codebase as the line 24 gets closed here https://github.com/joomla/joomla-cms/blob/3.4.3/components/com_contact/views/contact/tmpl/default_form.php#L78

Do you have a different file? Are you on the last joomla version? Can you try a default template?

>The place to write the "Subject" is too large and goes outside the frame of others items (name, … ).

Where this happen? Can you show us a screenshot? Which window width do you have on testing?

**Comment by PhM1936** [comment]
Bonsoir,

Fast reaction !

On another site, I just copy the following text in components/com-contact … default_form.php :
	<div class="contact-form">
		<form id="contact-form" action="<?php echo JRoute::_('index.php'); ?>" method="post" class="form-validate form-horizontal">
			<fieldset>
				<legend><?php echo JText::_('COM_CONTACT_FORM_LABEL'); ?></legend>
				<div class="control-group">
					<div class="control-label"><?php echo $this->form->getLabel('contact_name'); ?></div>
					<div class="controls"><?php echo $this->form->getInput('contact_name'); ?></div>

	</fieldset> is missing just after le red </legend>

Subject place :



Here is how it looks after code modification in protostar which I basically use. Before, its white rectangle goes outside the white cadre in which the items of the formular are include.

I hope you understand my “frenchglish” !. Regards. Philippe.





Le 19 août 2015 à 22:04, zero-24 <notifications@github.com> a écrit :

Hi @PhM1936

In components/com_contact/views/contact/tmpl/default_form.php on line 24 is missing

I can't find the missing </fieldset> in the current codebase as the line 24 gets closed here https://github.com/joomla/joomla-cms/blob/3.4.3/components/com_contact/views/contact/tmpl/default_form.php#L78

Do you have a different file? Are you on the last joomla version? Can you try a default template?

The place to write the "Subject" is too large and goes outside the frame of others items (name, … ).

Where this happen? Can you show us a screenshot? Which window width do you have on testing?

**Comment by brianteeman** [comment]
After many months I am closing this as it does not appear to be an issue with the current codebase. It can always be reopened if that is not correct<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7728">issues.joomla.org/joomla-cms/7728</a>.</sub>
