### ISSUE TITLE
when Install From Web is installed, and slow, the overlay blocks other tabs

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#7730]
# Problem:

Slow responses from "Install from web" service mean that user is blocked from other actions waiting for the ajax to reply and render. 

# Steps to reproduce:

1) Install "Install from web" extension /administrator/index.php?option=com_installer&view=install

2) Wait for the Joomla service to be slow to respond... or fake it

3) Load the /administrator/index.php?option=com_installer&view=install page, and assume you dont want to install from web, you want to work with another of the tabs, click that tab

4) Note the loading throbber overlay prevents you from your quick and speedy workflow until the "Install from web" html loads from the ajax request

![screen shot 2015-08-19 at 21 51 30](https://cloud.githubusercontent.com/assets/400092/9368768/2f5021c4-46bd-11e5-9bdc-04cb0f4320fc.png)

![image 2015-08-19 at 9 56 10 pm](https://cloud.githubusercontent.com/assets/400092/9368779/38c3ef88-46bd-11e5-854a-2b7dbeeef8f7.png)

# To fix:

Ensure that the preventative loading overlay only overlays the one tab content and not the whole page

**Comment by dgt41** [comment]
There is a PR for that (also another couple bugs): https://github.com/joomla-extensions/install-from-web-client/pull/23
I would appreciate it if you can test that!

**Comment by PhilETaylor** [comment]
Ok thanks.
