### ISSUE TITLE
Sef Protocol not aplied neither  hreflang tag in languajefilteror canonical in Sef plugin

### ISSUE THREAD

**Issue by pedroll** [joomla/joomla-cms#7733]
#### Steps to reproduce the issue
Multiligual site migration to https entire site
Set livesite to "htps://..."
plugin Sef set to "https://..."

#### Expected result
Visit htttp://... version
Should be a tag canonical to https.
Should be alternate tags to https.

#### Actual result
No canonical tag.
hreflang tag show http instead https

**Comment by infograf768** [comment]
Are you using the Force SSL  parameter in Global Configuration?
If yes, I can make a patch to solve at least the alternate in multilanguage to get https.

**Comment by infograf768** [comment]
No reply to the information required. Changing status. It will be closed if no feeedback.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7733">issues.joomla.org/joomla-cms/7733</a>.</sub>

**Comment by brianteeman** [comment]
Closed due to lack of response<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7733">issues.joomla.org/joomla-cms/7733</a>.</sub>
