### ISSUE TITLE
[rfc] replace existing repeatable field

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#7749]
Current Repeatable field have problem with storage format and force to use JSON ... also very tricky in logic :smile: 

In my own work I use my own repeatable field, that have more clear logic to store the data, like:
```php
array(
  array(/*row 1 values*/),
  array(/*row 2 values*/),
  ...
  array(/*row N values*/)
)
```
Field values is sent to the server respectively to the fields hierarchy (groups) , and do not use hidden field with JSON value (as existing repeatable field). This is allow to handle the "repeatable value" as any other value from the form, in backend Model.

Also it do not use that tricky modal popup, and allow to use different layouts (table or simple div elements) to render the repeatable form. Only cons (but not really cons), it require external XML for subform.

So, **question**, whether will be interesting  to anyone if I try adapt it to Joomla core (for 3.5)?
Then we could deprecate existing Repeatable field.

otherwise just close this issue :smile: 

some screenshots:
`table`:
![screen 2015-08-22 17 51 05 1189x224](https://cloud.githubusercontent.com/assets/1568198/9424504/618206e4-48f7-11e5-9fff-1c4f4648a657.png)
![screen 2015-08-22 17 54 57 1246x174](https://cloud.githubusercontent.com/assets/1568198/9424500/5cc36a1c-48f7-11e5-9b97-8ecc200ca886.png)
`div` container:
![screen 2015-08-22 17 52 52 1216x404](https://cloud.githubusercontent.com/assets/1568198/9424508/74c486f0-48f7-11e5-9bc1-d769ea8cece8.png)

**Comment by uzielweb** [comment]
I support this change. The actual repeatable is crappy.

**Comment by peterlose** [comment]
This change would be awesome. I use the repeatable field quite a lot, and it really does suck :)

**Comment by dgt41** [comment]
:+1: from me as well

**Comment by roland-d** [comment]
@wilsonge Any thoughts?

**Comment by wilsonge** [comment]
:+1: to rework

**Comment by Fedik** [comment]
very well, then I will prepare the pull request soon

**Comment by Fedik** [comment]
So there it is #7749
Please test.
