### ISSUE TITLE
Replacement for Pagebreak Plugin

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#7750]
A new plugin needs to be written as a replacement for the current Pagebreak content plugin.

The current plugin has hardcoded HTML within its code and uses the old MooTools based sliders and tabs helpers for content.  A new plugin should use the Bootstrap based helpers for these options.  The output should also be generated through `JPluginHelper::getLayoutPath` which uses a similar tmpl folder structure found in components and modules (see the pagenavigation plugin for an example).

A new plugin is required for backward compatibility otherwise pages which are displayed using the existing sliders/tabs will probably be broken with a major HTML structure change.  The existing plugin, once a new plugin is complete, should then be deprecated.

**Comment by zero-24** [comment]
As we have a PR #7760 by @n9iels I'm going to close here. Thanks.
