### ISSUE TITLE
2 missing language keys

### ISSUE THREAD

**Issue by tranduyhung** [joomla/joomla-cms#7751]
There are 2 language keys which I can't find them anywhere in Joomla language files

JLIB_APPLICATION_ERROR_CREATE_NOT_PERMITTED - used in

https://github.com/joomla/joomla-cms/blob/master/administrator/components/com_media/controllers/folder.php#L168

JERROR_CORE_CREATE_NOT_PERMITTED - used in 

https://github.com/joomla/joomla-cms/blob/master/administrator/components/com_templates/models/style.php#L169 and https://github.com/joomla/joomla-cms/blob/master/administrator/components/com_modules/models/module.php#L398

If they are really missing. What language ini file should we add them to? Can we just simply say "Create not permitted." just like in com_media?

    COM_MEDIA_ERROR_CREATE_NOT_PERMITTED="Create not permitted."

**Comment by infograf768** [comment]
imho the constant `JLIB_APPLICATION_ERROR_CREATE_NOT_PERMITTED` should just be replaced by `COM_MEDIA_ERROR_CREATE_NOT_PERMITTED` in https://github.com/joomla/joomla-cms/blob/master/administrator/components/com_media/controllers/folder.php#L168

And a new string 
`JERROR_CORE_CREATE_NOT_PERMITTED="Create not permitted"` 
should be added to administrator/language/en-GB/en-GB.ini in alpha order (i.e after line 158)

**Comment by zero-24** [comment]
Closing as here is a PR: https://github.com/joomla/joomla-cms/pull/7752 Thanks @tranduyhung and @infograf768 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7751">issues.joomla.org/joomla-cms/7751</a>.</sub>
