### ISSUE TITLE
To much GitHub permissions I grant to issues.joomla.org

### ISSUE THREAD

**Issue by SDKiller** [joomla/joomla-cms#7755]
With all the respect - why just to open an issue here I need to grant read and **write** access to my repositories and access to organizations?

There is plenty enough sites using GitHub oauth and not asking me so much permissions.

**Comment by Bakual** [comment]
Can you please open that issue on the JIssues tracker. It isn't an issue with Joomla CMS.
See https://github.com/joomla/jissues or http://issues.joomla.org/tracker/jtracker

**Comment by mbabker** [comment]
This may be something we can adjust through GitHub's API, but by default there is no way to manage the grants of an application through the web interface.

As to the specific actions taken, access is required to allow our issue tracker application to post issues and comments on behalf of your user account (and other actions if allowed by ACL such as labels and milestones).  Repository data is never interacted with in the application nor are the authentication tokens stored anywhere (as the code is open source you can validate this yourself).

**Comment by SDKiller** [comment]
To make it clear - it was an issue opened on Joomla! Issue Tracker

There is probably a webhook configured there.

**Comment by Bakual** [comment]
> To make it clear - it was an issue opened on Joomla! Issue Tracker

 The "Joomla! Issue Tracker" is also known as "JIssues" or "JTracker". It has its own issue managing location which I linked above. Since it isn't an issue with the Joomla core itself.
