### ISSUE TITLE
If Plugin "User - Joomla! " is disabled no login possible

### ISSUE THREAD

**Issue by sisko1990** [joomla/joomla-cms#7762]
#### Steps to reproduce the issue
Disable the plug-in "User - Joomla!" and logout. Now you cannot login anymore in Joomla! after you activate the plug-in by hand in database.

Is that normal?
If yes, I suggest to show a warning or add a message in the description as in the "Authentication - Joomla" plug-in: "Warning! You must have enabled this plugin if you use the Joomla! user management or you will lose all access to your site."

Regards,
Jan

**Comment by zero-24** [comment]
Thanks Jan. Fix / language change is here: https://github.com/joomla/joomla-cms/pull/7763
