### ISSUE TITLE
Help icon invisible in frontpage login module when bootstrap enabled

### ISSUE THREAD

**Issue by jvdh20** [joomla/joomla-cms#7766]
#### Steps to reproduce the issue
1) make a template and add:
JHtml::_('bootstrap.framework');
JHtml::_('bootstrap.loadcss');
to enable bootstrap in your template.

2) Add a "Login" module for the frontpage.

3) Besure that the "Two Factor Authentication" plugins are enabled.

4) Visit your frontpage and be sure that you see the login module with the "Secret Key" field.

5) After the "Secret key" there is a span with the class "icon-help"

#### Expected result
The span with class "icon-help" should show a help icon.

#### Actual result
But it doesn't show an icon.
IF I CHANGE
class "icon-help"
ON LINE 72 AND 79 IN
modules\mod_login\tmpl\default.php
TO
class "icon-question-sign"
IT WORKS AGAIN

#### System information (as much as possible)
Joomla 3.4.3 

#### Additional comments
See attachments for printscreens before and after fix.![screen shot 2015-08-24 at 14 22 26](http://issues.joomla.org/uploads/1/7843c222cdb7eb836b8a668b487fe610.jpg)

**Comment by infograf768** [comment]
The class exists in Protostar:
```
.icon-question:before,
.icon-question-sign:before,
.icon-help:before {
	content: "\45";
}
```

**Comment by jvdh20** [comment]
It's very strange.
I haven't changed anything else in the Joomla core files.
But if I use class "icon-question-sign" it works in my template.
If I use class "icon-question" or "icon-help" it doesn't work in my template.

I found out that when I add the following CSS to my template it works.
But why should I have to add this CSS to my template?
The other icons with class "icon-user", "icon-lock" and "icon-star" work by default without adding any CSS.

@font-face {
	font-family: 'IcoMoon';
	src: url('../../../media/jui/fonts/IcoMoon.eot');
	src: url('../../../media/jui/fonts/IcoMoon.eot?#iefix') format('embedded-opentype'), url('../../../media/jui/fonts/IcoMoon.woff') format('woff'), url('../../../media/jui/fonts/IcoMoon.ttf') format('truetype'), url('../../../media/jui/fonts/IcoMoon.svg#IcoMoon') format('svg');
	font-weight: normal;
	font-style: normal;
}
[class^="icon-"]:before,
[class*=" icon-"]:before {
	font-family: 'IcoMoon';
	font-style: normal;
	speak: none;
}
.icon-question:before,
.icon-question-sign:before,
.icon-help:before {
	content: "\45";
}

**Comment by mbabker** [comment]
The core templates are compiled with the IcoMoon font set which includes some extra class names beyond Bootstrap's Glyphicons and some custom class names (to map to other icons).  So if you're using a template that doesn't include those icons or classes, it makes sense why things aren't quite displaying as you're expecting immediately.

**Comment by jvdh20** [comment]
Then It would be better that Joomla should only use the Bootstrap Glyphicons and not in some cases the IcoMoon font set or otherwise if Bootstrap is loaded also load the IcoMoon font set by default to prevent missing icons.

**Comment by mbabker** [comment]
If you include the `media/jui/css/icomoon.css` file in your template then IcoMoon will load.  The core templates have the CSS compiled into the main template's CSS file via the LESS files and that standalone CSS file is available as an option to make it easy to load in the extra icons.

The same type of issue would happen if only Glyphicons were in use because we've added several custom class name aliases (and even some icons that aren't available as part of Glyphicons).

**Comment by Bakual** [comment]
I'm closing this issue as it's an issue of the template and not the core.

If you don't like the class names used in core, feel free to create a template override to change them so it matches standard bootstrap. However i would rather add the needed CSS to support the present icon class.

**Comment by jvdh20** [comment]
Thanks mbabker but adding media/jui/css/icomoon.css load Glyphicons and IcoMoons on top of each other.
I stay with the solution:

@font-face {
 font-family: 'IcoMoon';
 src: url('../../../media/jui/fonts/IcoMoon.eot');
 src: url('../../../media/jui/fonts/IcoMoon.eot?#iefix') format('embedded-opentype'), url('../../../media/jui/fonts/IcoMoon.woff') format('woff'), url('../../../media/jui/fonts/IcoMoon.ttf') format('truetype'), url('../../../media/jui/fonts/IcoMoon.svg#IcoMoon') format('svg');
 font-weight: normal;
 font-style: normal;
 }

[class*=" icon-"]:before {
 font-family: 'IcoMoon';
 font-style: normal;
 speak: none;
 }
 .icon-question:before,
 .icon-question-sign:before,
 .icon-help:before {
 content: "\45";
 }<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7766">issues.joomla.org/joomla-cms/7766</a>.</sub>

**Comment by Bakual** [comment]
You should probably not use `JHtml::('bootstrap.loadcss');`. This is a command which we honestly should have never introduced.
You should instead buold your own template CSS from the LESS files. Then you can drop out the Glyphicons and replace them with IcoMoon.

**Comment by N6REJ** [comment]
I really don't understand how there can be a conflict between icomoon 
and glyphicon.  I don't have any and the class names are nothing alike.
icon-  versus glypihicon glyphicon-
Bear

**Comment by jvdh20** [comment]
The icons before the fields of the login form module are icons with classnames like "icon user", "icon-lock" and "icon-star". Icomoon uses the same classnames. Thats why the icomoon and glyphicon icons appear on top of each.

**Comment by mbabker** [comment]
Bootstrap 2.3 uses `icon-` names.  Bootstrap 3 uses `glyphicon-` names.

**Comment by jvdh20** [comment]
Thanks mbabker that would solve it when the newest Bootstrap becomes part of the core.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7766">issues.joomla.org/joomla-cms/7766</a>.</sub>

**Comment by Bakual** [comment]
We can talk about Bootstrap 4 for Joomla 4 :smile:

**Comment by N6REJ** [comment]
@mbabker thanks Michael that explains it.
