### ISSUE TITLE
Param SHOWON on field inside REPEATABLE fieldset

### ISSUE THREAD

**Issue by reenan** [joomla/joomla-cms#7770]
#### Steps to reproduce the issue

Create a XML file for a back end form.
In that XML file create a REPEATABLE field.
Inside the repeatable fieldset create 2 fields, make the second one param "showon" when field 1 is true or something like that.

#### Expected result

I was expecting the repeatable fieldset to show only the first field and when the condition is true, show the second field (the one with "showon" param)

#### Actual result

Repeatable field works fine but the fields with "showon" param comes visible EVEN IF the condition is FALSE!!

#### System information (as much as possible)

I do believe it happens because of some trouble related to the field's ID because when you're using repeatable field it puts the "_ID" on the field's name end and maybe the showon param is looking for something wrong due that "_ID" variable.

#### Additional comments

I found that bug while building a custom component to control, create and edit all kinds of forms in the website by using only the backend.

The problem ocourred when building the "create a form" part. My idea was to repeat a fieldset containing all basics info for each field and then, based on the selected TYPE of field show additional params (ex: max, min and step for range).

Thanks for your attention, hope it gets fixed soon!

**Comment by Fedik** [comment]
yeap,
I would say it is known issue #6882

**Comment by zero-24** [comment]
Closing as we have #6882 there @artur-stepien try to prepare a pull request for.
