### ISSUE TITLE
Contact "Miscellaneous Information" doesn't display

### ISSUE THREAD

**Issue by Silver0l** [joomla/joomla-cms#7780]
#### Steps to reproduce the issue

Select a Contact in "Contact Manager: Contacts"

Add Miscellaneous Information in the "Miscellaneous Information" tab.

Select the "Display tab" and ask to display Misc. Information by selecting "Show" for the Misc. Information field.

#### Expected result

I would like to see the miscellaneous contact information when the contact is selected on the front end.

#### Actual result

Miscellaneous contact information is not displayed. Other information are OK.
See
http://cabinet-morin.fr/index.php/contact

#### System information (as much as possible)

Joomla 3.4.3

#### Additional comments

Also changed the "Contact Display Options" in "Menu Manager: Edit Menu Item" to have  the "Misc. Information" field set to "Show", but no change.

Also changed the "Contact Manager Options" in a similar way with no result.

**Comment by infograf768** [comment]
Looks like you are not using the core contact layout but a custom template one.
I suggest you contact the template developer.

**Comment by Silver0l** [comment]
Yes, I am using Joomshaper's Radon template.

However, I changed the Template Style in "Menu Manager: Edit Menu Item" to "protostar - default" and I still have the same issue, just with a different look:
http://cabinet-morin.fr/index.php/contact

Best Regards
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7780">issues.joomla.org/joomla-cms/7780</a>.</sub>

**Comment by infograf768** [comment]
Looks like, at looking at the classes used, that you are still not using a core default setting.

**Comment by infograf768** [comment]
I have tested your template and, indeed, it contains an override for the contact display which has no code to display misc information.
See `templates/shaper_radon/html/com_contact/contact/default.php`
compare with 
https://github.com/joomla/joomla-cms/blob/staging/components/com_contact/views/contact/tmpl/default.php#L176-L210

I guess we can close this issue as it is not joomla related

**Comment by Silver0l** [comment]
Agreed.

**Comment by Silver0l** [comment]
Just if somebody has the same issue...

Replaced templates/shaper_radon/html/com_contact/contact/default.php with https://github.com/joomla/joomla-cms/blob/staging/components/com_contact/views/contact/tmpl/default.php and now it works.

**Comment by N6REJ** [comment]
no need to replace it REMOVE it, its an OVERRIDE
Bear

**Comment by booker1001** [comment]
Hi!
I had the same issue on my own template.
The solution written above solved my issue.
Thanks for the information!
:)
