### ISSUE TITLE
Wrong Class for the alerte message for 'saving an article' in the frontend

### ISSUE THREAD

**Issue by MAT978** [joomla/joomla-cms#7786]
#### Steps to reproduce the issue

- Login on frontend (template Protostar)
- Edit an article and save it

#### Expected result

The Class used for the alert message:

<pre>
Message
Article successfully saved.
</pre>

Should be "alert alert-success" and not "alert alert-message" as it is.
![screen shot 2015-08-30 at 11 52 58](http://issues.joomla.org/uploads/1/4594b5bb1a153b81710b12dbf1ecb5d5.png)
#### Additional comments
Note the right class is used in the backend

**Comment by infograf768** [comment]
Here is a patch: https://github.com/joomla/joomla-cms/pull/7788

**Comment by Bakual** [comment]
Closing as we have a PR
