### ISSUE TITLE
Empty H2 tag added on single article if show_article is hide dans show_author is show

### ISSUE THREAD

**Issue by Dezi168** [joomla/joomla-cms#7790]
#### Steps to reproduce the issue
Create an single with following article properties :
show_article : hide
show_author : show

#### Expected result
There should not be any code rendered for article title.

#### Actual result
An empty h2 tag is added to the code rendered
```
<h2 itemprop="name">
					</h2>
```

#### System information (as much as possible)
Any system (it is HMTL rendering)

#### Additional comments
To solve this problem : 
change lines 48 to 52 of file components/com_content/views/article/tmpl/default.php

actual code : 
```html
		<h2 itemprop="name">
			<?php if ($params->get('show_title')) : ?>
				<?php echo $this->escape($this->item->title); ?>
			<?php endif; ?>
		</h2>
```

modified code to solve the issue : 
```html
		<?php if ($params->get('show_title')) : ?>
		<h2 itemprop="name">
			<?php echo $this->escape($this->item->title); ?>
		</h2>
		<?php endif; ?>
```

**Comment by zero-24** [comment]
@Dezi168 that makes sense ;) Can you send your change as Pull Request against staging?

If you need help see here: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests Thanks :smile:

**Comment by brianteeman** [comment]
See #9142 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7790">issues.joomla.org/joomla-cms/7790</a>.</sub>
