### ISSUE TITLE
Re-edit article error #493

### ISSUE THREAD

**Issue by martinkolle** [joomla/joomla-cms#7792]
Guide: 
1. Edit article. 
2. "Save article" OR "Close"
3. Edit same article again. This gives a 493 error - you cannot acces this link directly. 
4. If I check th checkbox and click "Edit", I can edit the article again. 

Joomla: 3.4.3
I have upgraded Joomla earlier today. I have cleared cache, cookies and so on. I ahve also tried in safari and firefox (latest versions). 

Have any of you experienced this?

**Comment by Bakual** [comment]
Usually that happens if you're trying to open the form by using the "back" button of your browser. This would be intended behavior.
You always need to either click the article title in the list, or use the edit checkbox/button.

**Comment by martinkolle** [comment]
We do click in the list. 

The same happens in frontend. When we try to re-edit an article, we do get a 403 error.

Any idea? Cache, session, cookies?

![image](https://cloud.githubusercontent.com/assets/1416055/9681748/c91c8758-5300-11e5-819a-0cc5300a716e.png)

**Comment by martinkolle** [comment]
The error is caused in the following line: 
components/com_content/controller.php:98



``
// Check for edit form.
	if ($vName == 'form' && !$this->checkEditId('com_content.edit.article', $id))
	{
		// Somehow the person just went to the form - we don't allow that.
		return JError::raiseError(403, JText::sprintf('JLIB_APPLICATION_ERROR_UNHELD_ID', $id));
	}
``

This is similar to http://forum.joomla.org/viewtopic.php?f=624&t=589715&p=3153406#p3153406
