### ISSUE TITLE
Tag articles list doesn't care of navigation language

### ISSUE THREAD

**Issue by jlainezs** [joomla/joomla-cms#7793]
#### Steps to reproduce the issue
* Enable a multi language site.
* Create some articles in diferent languages and add the *same* tag to them. This seems a nonse but say you want to write an article aboout "Joomla! 3.4" in several languages. Of course wou may want to tag them with "Joomla! 3.4" in spite of the language.
* Create a tags module list, activate it on all pages, save and refresh the site.
* Click the tag which labels articles written in several languages.

#### Expected result
* You expect to see the articles list of the language you are browsing the site.

#### Actual result
* You get a list of articles tagged with the selected tag in any language.

#### System information (as much as possible)
* First seen on Joomla! 3.4.1 and reproduced on Joomla! 3.4.3
* PHP 5.6
* MySQL 5.1
* Apache 2.4 
* Seen on Windows 7, 8.1 and 10

#### Additional comments
Maybe this is a desired behaviour as you may want to show all articles tagged under certain tag, but at least there should be an option which let filter the articles list by the browsing language.

**Comment by infograf768** [comment]
Have you set the Tags Language Filter component parameter to use only "Current"?
![screen shot 2015-09-02 at 08 29 35](https://cloud.githubusercontent.com/assets/869724/9624420/f74610a0-514c-11e5-9cc1-4369637c07f4.png)

**Comment by jlainezs** [comment]
ups! I had the "Language Filter" setted to "All" . Tested setting it to "Current" and now is working as expected, so it is not a bug but my fault.

**Comment by zero-24** [comment]
Thanks for the response @jlainezs I'm going to close here now. Thanks.
