### ISSUE TITLE
Helvetica Neue - Default font looks horrible in backend

### ISSUE THREAD

**Issue by spignataro** [joomla/joomla-cms#7794]
![screen shot 2015-09-01 at 3 05 20 pm](https://cloud.githubusercontent.com/assets/72186/9613692/f7b82902-50ba-11e5-96d0-e2fcd6e721ca.png)

As you can see if you have Helvetica Neue as your default font the site looks HORRIBLE in the backend. Can we set the default font to be Helvetica vs Helvetica Neue.

**Comment by brianteeman** [comment]
Cant confirm (I removed all other font references just to be 100% certain I was using Helvetica Neue

![zfdk](https://cloud.githubusercontent.com/assets/1296369/9614550/5765d398-50ea-11e5-9c0e-acdf0759e6bd.png)

**Comment by spignataro** [comment]
Do you have that installed as a system font?

**Comment by brianteeman** [comment]
Yes its a default OSX font https://en.wikipedia.org/wiki/List_of_typefaces_included_with_OS_X

**Comment by spignataro** [comment]
This is on windows - I should have mentioned the OS that was being used.

*-- Steven Pignataro / CEO*
------------------------------------------------------
'corePHP'
Technology to power your core business

245 West Michigan Ave.
Battle Creek, MI 49017

Phone:    (269) 447-1830
Email:     steven@corephp.com
Web:      https://www.corephp.com
Support: https://support.corephp.com

Our locations: Battle Creek, MI | Chicago, IL | São Paulo, Brazil

**Comment by brianteeman** [comment]
Where did you download it from - sounds like a bad font (especially as this is the first report of a problem X years after the template was introduced)

**Comment by Fedik** [comment]
@spignataro which browser? and do you tried in different browsers?
for me it looks like wrong font...

**Comment by N6REJ** [comment]
There are LOTS of neue fonts and all behave differently.  Its the most 
forked font there is.
Bear

**Comment by brianteeman** [comment]
After several months with no response from the original poster I am closing this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7794">issues.joomla.org/joomla-cms/7794</a>.</sub>
