### ISSUE TITLE
"Please select the database type" testing Joomla_3.4.4-rc installation

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#7797]
Hi,

I have just downloaded and tested to install Joomla_3.4.4-rc.

Following the usual path, I am unable to install it, stopped with "Please select the database type".

Database Type * is MySQLi

When you move from Step 2 and Step 3, it is validated OK (installation/model/database, line 114).

However, when you finally click on Step 3/Next, it is checked again, $options->db_type is empty and the installation fails.

### System Information
 
* Database Version 	5.5.44-0ubuntu0.14.04.1
* Database Collation 	latin1_swedish_ci
* PHP Version 	5.5.9-1ubuntu4.11
* Web Server 	Apache/2.4.7 (Ubuntu)
* User Agent 	Mozilla/5.0 (X11; Ubuntu; Linux i686; rv:40.0) Gecko/20100101 Firefox/40.0

**Comment by brianteeman** [comment]
Confirmed I get exactly the same
https://www.dropbox.com/s/mle2lpakn1exngf/rc-install.gif

**Comment by Bakual** [comment]
@wilsonge Looks like a release blocker

**Comment by AlexRed** [comment]
I can confirm the problem

**Comment by Bakual** [comment]
Reverting #7381 solves the issue for me.

**Comment by infograf768** [comment]
>Reverting #7381 solves the issue for me.

same here.

**Comment by Kubik-Rubik** [comment]
Thank you @anibalsanchez for reporting this issue. I will provide a PR with a fix in some minutes.

**Comment by anibalsanchez** [comment]
Thank you @Kubik-Rubik for your future PR!

**Comment by Fedik** [comment]
please take a look #7799

**Comment by Kubik-Rubik** [comment]
Please test provided PR #7799, I will close this issue now.

**Comment by anibalsanchez** [comment]
@test OK - Joomla_3.4.4-rc with this patch can be installed
