### ISSUE TITLE
Weblinks: Button "Clear" don't work for "Search in Titles"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#7802]
Using Isis and typing something in Weblinks' "Search in Titles", i got Results, but Button "X" ("Clear") don't clear searchfield. 

For Example it works perfect searching an Weblink-Category. Difference: Weblink-Category is the Word "Clear" and Filters beside Search-Field; in Weblinks theres a Button "X" and Filters on left Side.

Regards

**Comment by roland-d** [comment]
@franz-wohlkoenig Thank you for reporting this issue. I have fixed the issue here: https://github.com/joomla-extensions/weblinks/pull/86

Since weblinks is now an external application, I am going to close this issue and it can be followed up in the fix I provided.

**Comment by franz-wohlkoenig** [comment]
@roland-d Thanks for fixing on Sunday. Is the Fix part of next J-Update 3.4.4. or have i to Download the Zip at joomla-extensions/weblinks?

**Comment by zero-24** [comment]
@franz-wohlkoenig this is not included into the main repo so i will not fixed with 3.4.4 i will be fixed with the next weblinks update. If you can test the fix we can merge it for the next weblinks release: joomla-extensions/weblinks#86

**Comment by franz-wohlkoenig** [comment]
@zero-24 Looks like tests are succesful, thanks for RTC.

**Comment by roland-d** [comment]
@franz-wohlkoenig You can make the simple change in your own installation for now if you don't want to wait till the next Weblinks release. Go to this page: https://github.com/joomla-extensions/weblinks/pull/86/files#diff-c69693f18e75a13a0d24907e20f71035R65 and look at the green line, you will see I changed the word **id** to **getElementById**. You can make that change in the file administrator/components/com_weblinks/views/weblinks/tmpl/default.php.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7802">issues.joomla.org/joomla-cms/7802</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Thanks for helping. Chances done and works as expected. Have a nice Day.
