### ISSUE TITLE
Joomla! Installation Error - 'Please select the database type'

### ISSUE THREAD

**Issue by puneet0191** [joomla/joomla-cms#7804]
**Issue in Staging Branch** Joomla! Installation fails with 'Please select the database Type Error' although database type was selected during the installation

Steps to recreate:
1) Open the Main Configuration page during the Installation steps, provide Site-Name, Admin email, username, password and click next
2) Go to Database Configuration page select the required database type, provide DB information, server information and click next
3) Go to finalisation page, select Install Sample Data as "none" and click on Install button

Installation fails and goes back to Database configuration page, with the following error

![image](https://cloud.githubusercontent.com/assets/3048593/9634603/2680dc84-51b0-11e5-8310-303871749632.png)

**Comment by Kubik-Rubik** [comment]
Please see https://github.com/joomla/joomla-cms/pull/7799

Thanks!

**Comment by zero-24** [comment]
@puneet0191 please see: https://github.com/joomla/joomla-cms/pull/7799 for a fix. Closing here.

**Comment by puneet0191** [comment]
Thanks guys! :smile:
