### ISSUE TITLE
Broken relative addressing images in newsfeed_com displays

### ISSUE THREAD

**Issue by MonkeyTrainer12** [joomla/joomla-cms#7805]
#### Steps to reproduce the issue

Not really a bug, but a common problem.  
Displaying RSS feeds using com_newsfeed, many providers mistakenly use relative addressing to display images.

#### Expected result

A feed display which includes imagery.

#### Actual result

A feed display which includes numerous broken image links.

#### System information (as much as possible)

I built a simple fix for Joomla 3.x

#### Additional comments

It's an easy fix. Add the following lines immediately before line 126 (the echo statement which prints the $text variable):

$domain = preg_replace( "~^(https?://[^/]*).*$~", "\\1/", $this->rssDoc[ $i ]->uri );
$text = str_replace( ' src="/', ' src="' . $domain, $text );

I'm currently supplying sites with an override html template which works fine, but I would prefer if this minor cleanup was included in the default Joomla Install.

**Comment by Kubik-Rubik** [comment]
Please create a Pull Request (PR) with your suggested solution, then we can test it! Example with the GitHub UI: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7805">issues.joomla.org/joomla-cms/7805</a>.</sub>

**Comment by conconnl** [comment]
@MonkeyTrainer12 can you please create a Pull Request, so we can test it for you and merge it into the core?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7805">issues.joomla.org/joomla-cms/7805</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #11414<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7805">issues.joomla.org/joomla-cms/7805</a>.</sub>
