### ISSUE TITLE
Update Symbol in Admin

### ISSUE THREAD

**Issue by Hils** [joomla/joomla-cms#7815]
I have just updated Joomla to RC2 and noticed the update symbol :
![update-symbol](https://cloud.githubusercontent.com/assets/736887/9683594/7036fa66-5309-11e5-96c9-c50155d7fbd8.PNG)

The upward arrow, to me, is confusing as it doesn't mean update. Doing an image search for 'update symbol' this is the result:
https://www.google.co.uk/search?q=update+symbol&espv=2&biw=1920&bih=969&tbm=isch&tbo=u&source=univ&sa=X&ved=0CCAQsARqFQoTCPf54qOw3ccCFQNZ2wodNg4PGA

This isn't a critcal problem but not sure where else to put it!

**Comment by zero-24** [comment]
@Hils this: https://docs.joomla.org/J3.x:Joomla_Standard_Icomoon_Fonts are the included Icomoon Icons maybe you can find something better there?

**Comment by zero-24** [comment]
maybe `loop` @Hils ?

**Comment by Hils** [comment]
loop looks exactly right! and if not, unblock / refresh / redo-2 might work too. Thanks for looking!

**Comment by zero-24** [comment]
If you have some time ;)

You need to replace `arrow-up-2` with `loop` here:

https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_joomlaupdate/views/default/view.html.php#L43
and
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_joomlaupdate/views/update/view.html.php#L34

**Comment by Hils** [comment]
thank you! Will finish urgent job and then 'attempt' it - thanks for your input!

**Comment by Hils** [comment]
Please see #7816 - thank you.
