### ISSUE TITLE
Regression? new 3.4.4 rc2 install fatal error when saving category access

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#7821]
Test: make a new installation of 3.4.4 rc2.
I used blog sample data.

make sure to enable the content - Smart Search plugin and all finder plugins.
Index in Smart Search component.

Then edit a category ( I chose the article blog category.
Change its access from Public to Registered and save;

I get here:
<b>Warning: Creating default object from empty value in /Applications/MAMP/htdocs/testnew/stagingcms/administrator/components/com_finder/helpers/indexer/adapter.php on line 557</b>

<b>Catchable fatal error: Argument 1 passed to PlgFinderContent::index() must be an instance of FinderIndexerResult, instance of stdClass given, called in /Applications/MAMP/htdocs/testnew/stagingcms/administrator/components/com_finder/helpers/indexer/adapter.php on line 330 and defined in /Applications/MAMP/htdocs/testnew/stagingcms/plugins/finder/content/content.php on line 244</b>

I did a var_dump of `$this->type_id` and I got a value.

I can repeat the error on a legacy multilingual test site updated to 3.4.4 but not on a legacy monolanguage site updated to 3.4.4

**Comment by infograf768** [comment]
Supplementary info: I only get this error when changing the Access, not Parent or status or language or textarea

**Comment by roland-d** [comment]
@infograf768 I tested this but I **cannot** reproduce the issue. Here is what I did:

1. Install Joomla 3.4.4 RC2
2. Enabled the Content - Smart search plugin
* Indexed the content in Smart Search
* Go to categories and open the Park blog category
* Changed the access level from Public to Registered
* Saved the category without a problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7821">issues.joomla.org/joomla-cms/7821</a>.</sub>

**Comment by Kubik-Rubik** [comment]
This is not related to the RC version, our QA (at my company) found the problem already in the previous stable version and it occurs only under some special circumstances. It's a bug in the Finder extension. I just didn't have the time to fix it yet but will do it.

**Comment by infograf768** [comment]
:+1:

**Comment by infograf768** [comment]
@Kubik-Rubik 
Do you know which special circumstances?

**Comment by roland-d** [comment]
@Kubik-Rubik Can you provide a follow-up please?

**Comment by zero-24** [comment]
@Kubik-Rubik any update on this or still just no time? ;)

**Comment by brianteeman** [comment]
Is this still an issue - if not can we close it? @Kubik-Rubik <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7821">issues.joomla.org/joomla-cms/7821</a>.</sub>

**Comment by Kubik-Rubik** [comment]
@brianteeman I think it is still an issue and I will tackle it soon! Please do not close this issue yet, thanks!

**Comment by brianteeman** [comment]
@Kubik-Rubik any update on this or still just no time? ;)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7821">issues.joomla.org/joomla-cms/7821</a>.</sub>

**Comment by brianteeman** [comment]
Monthly reminder to @Kubik-Rubik <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7821">issues.joomla.org/joomla-cms/7821</a>.</sub>

**Comment by Kubik-Rubik** [comment]
@brianteeman Grrrr, thank you! :-) Okay, I will try to look into it this week.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7821">issues.joomla.org/joomla-cms/7821</a>.</sub>

**Comment by brianteeman** [comment]
@Kubik-Rubik this is your final monthly reminder<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7821">issues.joomla.org/joomla-cms/7821</a>.</sub>

**Comment by infograf768** [comment]
FYI, I can't reproduce anymore on the same multingual test site now updated to 3.5.0

**Comment by brianteeman** [comment]
I am closing this as there is no sign of any contribution from @Kubik-Rubik despite multiple promises and the original poster can not replicate it any longer<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7821">issues.joomla.org/joomla-cms/7821</a>.</sub>
