### ISSUE TITLE
JPath.clean not works for phar:// or file://, for it will make // to /

### ISSUE THREAD

**Issue by Neugls** [joomla/joomla-cms#7823]
JPath.clean not works for phar:// or file://, for it will make // to /

like phar://a.phar/index.php,  in the JControllerLegacy.addPath, will call the JPath.clean, then the JPath.clean will replace the phar://a.phar/index.php to phar:/a.phar/index.php  then php will not find the file in phar

**Comment by roland-d** [comment]
Hello @Neugls,

Joomla is not supposed to be run from a Phar archive but needs to be unpacked and then run. So I don't see this is a bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7823">issues.joomla.org/joomla-cms/7823</a>.</sub>

**Comment by Fedik** [comment]
@roland-d I guess @Neugls mean support of Protocols and Wrappers http://php.net/manual/en/wrappers.php

**Comment by Neugls** [comment]
yes, it's not support  Protocols and Wrappers, and why joomla do not support phar

**Comment by roland-d** [comment]
@Neugls You asked why Joomla does not support phar, please see issue #4091 where the same question was asked.

As for the support of protocols and wrappers, I don't think that the clean() method is built with that intent. The JPath by it's very nature is meant to deal with local paths and nothing else.

As this is not something to be fixed, I am closing the issue. Thank you for your contribution.
