### ISSUE TITLE
Enabling Gzip in Joomla causes problems with facebook sharing

### ISSUE THREAD

**Issue by last-phoenix** [joomla/joomla-cms#7831]
#### Steps to reproduce the issue
1. Enable GZIP in administration panel.
2. Add facebook share button to site. 
3. Try to share article.

#### Expected result
A picture with article title and article text appears in the facebook share pop up window![screen shot 2015-09-07 at 12 11 54](http://issues.joomla.org/uploads/1/36220067b2e0537b8857298ea4f4e678.png)

#### Actual result
Only domain name with no article image or text appears in the facebook share pop up window![screen shot 2015-09-07 at 12 08 54](http://issues.joomla.org/uploads/1/0cedea290678720d20550e5a30f24ff4.png)

While using facebook debug tool - https://developers.facebook.com/tools/debug/og/object/ errors of missing og tags, like og:type, og:url and others are displayed. But when inspecting site source code, all the necessary og tags are present. 

#### System information (as much as possible)
Joomla 3.4.3
I'm actually using K2 CCK v 2.6.9, but I doubt if this makes any difference. 

#### Additional comments
This article helped me solve this problem - http://www.itoctopus.com/problems-with-sharing-links-of-a-joomla-website-on-facebook and the problem is described very clearly there.

**Comment by dgt41** [comment]
This is a known FACEBOOK problem. Quoting myself from #3643:

> Turns out that Facebook scraps ALWAYS the first 40k of data of a given page. That means if your page is more than that (the compressed one) then it will be partially downloaded, and because is compressed it will be broken.

You can use the plugin from that PR or use another one that also solves this problem.
PLT decided long ago to not trying to solve Facebook’s problems in the CMS!

**Comment by last-phoenix** [comment]
Thank you very much for pointing out the plugin!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7831">issues.joomla.org/joomla-cms/7831</a>.</sub>

**Comment by Bakual** [comment]
Closing issue as it's a Facebook bug.
