### ISSUE TITLE
Missing Title under module manager

### ISSUE THREAD

**Issue by auditorj** [joomla/joomla-cms#7835]
#### Steps to reproduce the issue
Backend Extension dropdown menu titles, Displaying Only Modules, Plugins, Templates, Language(s)

#### Expected result
Title should have been with Manager each.
Extension Manager, Module Manager, Plugins Manager, Template Manager, Language Manager

#### Actual result
Manager, Module, Plugins, Template, Language

#### System information (as much as possible)
Joomla! 3.4.4

#### Additional comments
This might be low only, :) but I guess it might confuse beginners :)

**Comment by mbabker** [comment]
It's a purposeful change.  See https://github.com/joomla/joomla-cms/commit/587d8460e9cd700902b453ae8914c54ea4feb35d and associated links.

**Comment by roland-d** [comment]
Hello @auditorj 

As pointed out by @mbabker this change was done on purpose, therefore I am going to close this issue. Thank you for your contribution.

**Comment by auditorj** [comment]
thank you :)
