### ISSUE TITLE
Hathor admin template add user note layout

### ISSUE THREAD

**Issue by auditorj** [joomla/joomla-cms#7836]
#### Steps to reproduce the issue
Add usernote on registered accounts.

#### Expected result
Proper layout should appear

#### Actual result
Review date is not in line, Version note disappeared?

#### System information (as much as possible)
Joomla! 3.4.4

#### Additional comments
attached screen shot. :)![screen shot 2015-09-08 at 22 23 53](http://issues.joomla.org/uploads/1/d8992a217b82e02c355c3286660e73ba.png)

**Comment by n9iels** [comment]
Confirmed, see the referenced pull request for a solution.

**Comment by zero-24** [comment]
Thanks. Closing as we have a PR here: https://github.com/joomla/joomla-cms/issues/8066
