### ISSUE TITLE
Icon tag doesn't save

### ISSUE THREAD

**Issue by syamvilakudy** [joomla/joomla-cms#7837]
I have created a new Custom HTML module with some html contents. But missing the below tag from the Editor
&lt;i class="fa fa-envelope-o"&gt;&lt;/i&gt;

I hope this is a bug in the WYSIWYG editor.
.

**Comment by Bakual** [comment]
You need to put content into the tag, otherwise it will be removed by the editor.
So make it a <i class="fa fa-envelope-o">&nbsp;</i> and it will work.

Closing as not a bug.
