### ISSUE TITLE
Breadcrumb - an item without a link does not show

### ISSUE THREAD

**Issue by teeuwis** [joomla/joomla-cms#7838]
#### Steps to reproduce the issue
Create a menu
Add a menu item of menu item type "Menu Heading"
Add a submenu item of menu item type "Individual Article"

Create a breadcrumb module for this menu and navigate to the submenu item.

#### Expected result

The breadcrumb module should show
Home > Menu Item > Sub Menu Item

#### Actual result
The breadcrumb module shows
Home > Menu Item

#### System information (as much as possible)
Not relevant

#### Additional comments
The bug is on line 58 of the file /modules/mod_breadcrumbs/tmpl/default.php
Below is the fix.

Please change
<?php $item->name; ?>

To
<?php echo $item->name; ?>

**Comment by Bakual** [comment]
Since you already propose a fix, can you please create a Pull Request?
See https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests for how to do it.

**Comment by teeuwis** [comment]
Ok, I think I just did. Posted correctly?

**Comment by Bakual** [comment]
Updated the PR with the information from here and changed the title to a more descriptive one.

Closing this issue as we have a PR.

**Comment by Saurabh1** [comment]
While working on a site, I found this issue still exist in latest version as well.
This doc says "The issue will be fixed in Joomla 3.4.5" https://docs.joomla.org/J3.x:The_breadcrumbs_module_does_not_show_the_items_not_linked
