### ISSUE TITLE
Updating Joomla from 3.4.3 to 3.4.4

### ISSUE THREAD

**Issue by franzpeter** [joomla/joomla-cms#7842]
#### Steps to reproduce the issue
It is difficult to describe it, but trying to do so. I have two websites. Both did run with Joomla 3.4.3. One did update without any problem by using Joomla update. The other one did start the update and after some time did show an eror message 504, Nginx timeout. But both pages do use Nginx.

#### Expected result
Update works without blank page or error message.

#### Actual result
For one page it works, for the other one did fail. I had to use the update package there. I did see a message telling error 504 Nginx timeout.

#### System information (as much as possible)
Debian Linux
DB version: 5.5.43
PHP 5.4.41
cgi-fcgi

**Comment by brianteeman** [comment]
I have the same problem from one site ground server but not the others. I
have raised a support ticket with them and will post back what they report

**Comment by Kubik-Rubik** [comment]
@brianteeman Ask them to increase the timeout parameters in the configuration files (http://www.nginxtips.com/504-gateway-time-out-using-nginx/).

**Comment by brianteeman** [comment]
Siteground have resolved the issue for me 
> I have managed to recreate the problem on my end. It was produced because the server was unable to resolve joomla.org properly, so I have consulted with our system administrators who managed to resolve the problem and now that functionality is working properly.

**Comment by franzpeter** [comment]
Yes, of course it is possible to increase the timeout. But what I do not understand is, that we have a progress bar inside the update procedure. Well I think it did the complete update but the text which says: installation was successful or the process, which does call that seems to produce that problem. Could the using of header('X-Accel-Buffering: no'); inside the updater solve that problem without changing the configuration files? Not every provider is nice like the siteground people.
Just as suggestion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7842">issues.joomla.org/joomla-cms/7842</a>.</sub>

**Comment by brianteeman** [comment]
Siteground stated 
> The problem was caused by a program called "named" which is a linux application and is connected to handling DNS, so we only needed to restart the said service in order to resolve the problem

Nothing to do with the gateway timeout parameters @Kubik-Rubik

**Comment by brianteeman** [comment]
@franzpeter the problem i was experiencing was BEFORE the progress bar starts

**Comment by franzpeter** [comment]
Nginx seems to have its own life. Sometimes it occurs before progressbar start, in my case after progress bar finished.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7842">issues.joomla.org/joomla-cms/7842</a>.</sub>

**Comment by brianteeman** [comment]
I am going to close this at this time - not sure if there is anything that joomla can do about this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7842">issues.joomla.org/joomla-cms/7842</a>.</sub>
