### ISSUE TITLE
Issue with Joomla update message

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#7844]
![image](https://cloud.githubusercontent.com/assets/1986000/9760371/6a420fce-56ec-11e5-9284-32d68358c80d.png)

Ocassionally it renders really badly for some unkown reason. On the same browser (chrome 45) I can't replicate this across all Joomla sites. A friend also saw this on firefox on another site - so it's not just me or the browser!

**Comment by roland-d** [comment]
@wilsonge Can it be cached CSS?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7844">issues.joomla.org/joomla-cms/7844</a>.</sub>

**Comment by Bakual** [comment]
Be sure to clear cache.
Did you maybe update from a version older than 3.4.3? Because I recall that issue from one of the last releases when something got changed there.

**Comment by roland-d** [comment]
This issue is already fixed in #7323 and the fix is included in 3.4.4, closing this as fixed.

**Comment by Bakual** [comment]
Ah, that's why I remembered that issue :smile:
