### ISSUE TITLE
Update notification double message

### ISSUE THREAD

**Issue by fly1ted** [joomla/joomla-cms#7851]
Hello,

I entered admin area and encountered that update notification gets broken. Has anyone else seen this?
![pic](https://cloud.githubusercontent.com/assets/8587695/9769719/7e107eda-5734-11e5-9667-62ef55155e37.png)

**Comment by roland-d** [comment]
Hello,

Thank you for your post but this has been reported and fixed already. See #7844 so I am going to close this as well, as it has already been fixed.
