### ISSUE TITLE
Joomla menu-item alias get's a data-toggle reference - brakes the menu-link

### ISSUE THREAD

**Issue by teeuwis** [joomla/joomla-cms#7852]
#### Steps to reproduce the issue
1. Create menu item alias
2. Link it to a menu-item in another menu
3. If you look in the html-code you see a data-toggle which prevents it from working properly.

#### Expected result
<ul class="nav menu"><li class="item-123"><a href="/link">Link</a></li></ul>

#### Actual result
<ul class="nav menu"><li class="item-123 active"><a data-toggle="dropdown" href="/link">Link <i class="fa fa-caret-down"></i></a></li></ul>

#### System information (as much as possible)
Joomla 3.4.4
Apache 2.x
MySQL 5
PHP 5.4

**Comment by brianteeman** [comment]
Your sample links have not been posted correctly here on github

I followed your instructions and could not replicate it

**Comment by teeuwis** [comment]
Ok, that's odd.
Here is what I did on a website of a client of mine:

I created a new menu which is not visible on the home menu, but only visible on (for example) http://domain.com/link
In the new menu I created a menu-alias linking to the home menu item of the main page.

I've attached a txt file with the expected result and the actual result. Maybe that clarifies it a bit.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7852">issues.joomla.org/joomla-cms/7852</a>.</sub>

**Comment by teeuwis** [comment]
![screen shot 2015-09-10 at 02 54 38](http://issues.joomla.org/uploads/1/9d7890979370d3b47b07dbb4f699719c.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7852">issues.joomla.org/joomla-cms/7852</a>.</sub>

**Comment by Bakual** [comment]
That sounds more like an issue from a template override, plugin or 3rd party menu module.
Core doesn't do that.

**Comment by teeuwis** [comment]
I apologize, it is a template override.

Let's close this one before anyone notices....<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7852">issues.joomla.org/joomla-cms/7852</a>.</sub>

**Comment by zero-24** [comment]
No Problem :smile:
