### ISSUE TITLE
"too much recursion" error since 3.4.4

### ISSUE THREAD

**Issue by thekrotek** [joomla/joomla-cms#7859]
Since 3.4.4 Joomla started to produce a "too much recursion" JavaScript error with core.js file in ALL my components, which use this code:

Joomla.submitbutton = function(task)
{
	if (task == 'sometask') {
		if (confirm("Do you really want to do this?")) {
	  		submitbutton(task);
  	  	}
	} else {
		submitbutton(task);
	}
}

This code worked perfectly for YEARS, but now it's broken. It actually was taken from some standard Joomla component lately.

Error pops, when you click a button on toolbar (Edit, Publish, Unpublish etc). All buttons are created using standard Joomla JToolBarHelper class.

Looks like an issue to me.

**Comment by Fedik** [comment]
`submitbutton()` is deprecated and internally use `Joomla.submitbutton` .. so you got recursion,
Correct code is:
```javascript
Joomla.submitbutton = function(task) {
 // some of your code 
 ...
 ...
 Joomla.submitform(task); // actually submit the form
}
```

**Comment by thekrotek** [comment]
Nice... So I should update all my components due to this doubtful "deprecation". Very smart.

Will Joomla.submitform(task) work for older versions of Joomla or should I add another version check just for this?

**Comment by Fedik** [comment]
Sorry for disappoint you, but `submitbutton()` deprecated since Joomla 2.5 and `Joomla.submitbutton` , `Joomla.submitform` added since then .. or maybe even in Joomla 1.6 .. 
Also your original code is incorrect ... 

so I wonder why you wonder :smile:

**Comment by thekrotek** [comment]
I wonder, because it worked perfectly upto 3.4.3.

**Comment by infograf768** [comment]
`Joomla.submitbutton and Joomla.submitform` are indeed present in 1.6.0 ;)

**Comment by Fedik** [comment]
there was some changes in `core.js` in 3.4.x, 
I guess that changes have uncovered your bug

I know it is a bit confused, because there no explanation,
but correct usage is to call `submitform()` inside `submitbutton()` .. but do not call `submitbutton()` inside `submitbutton()` ... 
no matter it is `Joomla.submitbutton()` (`Joomla.submitform()`) or  old `submitbutton()` (`submitform()`)

**Comment by Kubik-Rubik** [comment]
Thank you @Fedik for the explanation. I will close this issue since the code was used incorrectly even before the changes in the ```core.js```. @thekrotek Please update the code in your extensions!
