### ISSUE TITLE
Breadcrumbs menu item of type "text separator" not shown

### ISSUE THREAD

**Issue by Egnarts94** [joomla/joomla-cms#7862]
#### Steps to reproduce the issue
Install Joomla 3.4.4. Create 2 additional Items in the main menu (Home is the standard landing site). The first item is a "Text Separator" and the type of the 2nd item doesn't interest but it should be a child of the first item. Create a breadcrumb module and place it on the site. Choose the template "protostar". Now go to frontend and navigate to the site of the 2nd item and look at the text in the breadcrumb module.
I will give an example:
There is a menu item called "About us" which has the Type "Text Separator". It has one child menu item called "structure". Now if you navigate to the menu item "structure" and look in the breadcrumb:

#### Expected result
The breadcrumb path should display the name of the 1st item.
Example from above: breadcrumb should display: Home -> About us -> Structure

#### Actual result
But actually it displays not the "Text Separator" item.
Example from above: Home -> -> Structure
In some templates (like my template) it looks like: Home -> Structure

#### System information (as much as possible)
Joomla 3.4.4
my Template: Corvus Rockettheme

#### Additional comments
The same problem if the type is "menu heading".
I think the problem occours when the menu item has no reference (a href...).

Regards,
Egnarts

**Comment by Fedik** [comment]
please check if that #7839 fix the issue

**Comment by Egnarts94** [comment]
Yea, it can fix it. Thank you very much.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7862">issues.joomla.org/joomla-cms/7862</a>.</sub>
