### ISSUE TITLE
SEF canonical URL not working on SSL site

### ISSUE THREAD

**Issue by JanKrohn-Khalibre** [joomla/joomla-cms#7863]
#### Steps to reproduce the issue

* Install SSL certificate on web server
* enable "force ssl" on Joomla
* maintain "https://domain.com" as canonical domain

#### Expected result

Have canonical link in html header of each site

#### Actual result

Have no canonical link in any html header

#### System information (as much as possible)

Database Version  5.6.23  
Database Collation  latin1_swedish_ci  
PHP Version  5.6.13  
Web Server  Apache  
WebServer to PHP Interface  cgi-fcgi  
Joomla! Version  Joomla! 3.4.4 Stable [ Ember ] 8-September-2015 21:30 GMT  
Joomla! Platform Version  Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT  

#### Additional comments

Workaround: Use non ssl version as canonical. forced redirect to ssl will happen anyway.

**Comment by brianteeman** [comment]
There is no need to use force SSL on a correctly configured domain

**Comment by JanKrohn-Khalibre** [comment]
Very well, but canonical link doesn't work with https either when "forced ssl" is disabled...

**Comment by andrepereiradasilva** [comment]
Canonical only exists if the "Site Domain" field in the SEF system plugin parameters is filled with a domain different than the current Joomla site domain.

In 3.5.0 beta 5, you can see this check in https://github.com/joomla/joomla-cms/blob/staging/plugins/system/sef/sef.php#L43-L56

**Comment by infograf768** [comment]
This can be closed.
