### ISSUE TITLE
After the site closed, the front end can not log on.

### ISSUE THREAD

**Issue by DullKnight** [joomla/joomla-cms#7865]
3.4.4 version update, there is a problem:
After the site closed, the front end can not log on.

**Comment by Bakual** [comment]
What do you mean with "site closed"? Setting the site into offline mode?

**Comment by DullKnight** [comment]
yes, Setting the site into offline mode.

**Comment by infograf768** [comment]
I can't reproduce this issue

**Comment by DullKnight** [comment]
Web site offline, has been in the front to enter account information after clicking login loaded state, the last display can not be linked. But the site online with no problems.

**Comment by DullKnight** [comment]
The reason has been found.

**Comment by zero-24** [comment]
@DullKnight can you document the reason / problem you found for any one how find this issue via google?
