### ISSUE TITLE
Bug in hide.js (bugfix inclusive): Missing translation for Openmenu

### ISSUE THREAD

**Issue by raabigramm** [joomla/joomla-cms#7872]
Hi all,

in hide.js there's a bug in line 268 so that Openmenu does not get translated:

		$mobile = $('<div>', {id: 'mobile_select'}).html('<h2><a href=#" id="menuopener" onclick="return false;"><span>Openmenu</span></a></h2>').show();

The correct version is as follows:

		$mobile = $('<div>', {id: 'mobile_select'}).html('<h2><a href=#" id="menuopener" onclick="return false;"><span>'+Openmenu+'</span></a></h2>').show();

Thank you for including it to the sources.

Bye, Roland

**Comment by Kubik-Rubik** [comment]
@raabigramm Please create a Pull Request with your suggested change. Thank you!

**Comment by raabigramm** [comment]
Hi,

I'm sorry but I don't know how. I am confused since I'll have to compare versions first...

Bye, Roland

**Comment by n9iels** [comment]
You can use this documentation to make a Pull Request:
https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7872">issues.joomla.org/joomla-cms/7872</a>

**Comment by infograf768** [comment]
PR is here: https://github.com/joomla/joomla-cms/pull/7873



Closing the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7872">issues.joomla.org/joomla-cms/7872</a>.</sub>
