### ISSUE TITLE
/administrator returns error 404 not found

### ISSUE THREAD

**Issue by theoaks** [joomla/joomla-cms#7877]
When I try to access the administrator portal, I get a 404 not found error. I've tried to get help from different forums, but none is forthcoming.

**Comment by N6REJ** [comment]
This is not the right place for it, but check to see if you have a 
.htacces file and if so rename it so that its off.  Especially if this 
is local.
this will prevent any errors from blocking your access, then once you've 
figured it out you can redo it properly.
Bear

**Comment by Bakual** [comment]
Closing as this is not the place for support questions. Please use http://forum.joomla.org/.
