### ISSUE TITLE
Apostrophy in translation string not correctly escaped in javascript on admin com_menus item edit view

### ISSUE THREAD

**Issue by quayph** [joomla/joomla-cms#7880]
#### Steps to reproduce the issue

Joomla 3.4.4 with french translation in the administrator interface.
Créate a menu link to an article using administrator/com_menus.

#### Expected result
Buttons that work ! :-)

#### Actual result
Buttons in the main toolbar (Save, Save to new, Close etc..) non functional because of a javasript error.

`Uncaught SyntaxError: missing ) after argument list in /administrator/index.php?option=com_menus&view=item&layout=edit&id=117 Line 128`

This is the line 128 : You can see the un escaped apostrophy in the name attribute of the ``<iframe>`` tag. This prematurely closes the string. It concerns the "Select an article" button used to choose which article the menu item points to.

``modalBody.prepend('<iframe class="iframe" src="index.php?option=com_content&amp;view=articles&amp;layout=modal&amp;tmpl=component&amp;function=jSelectArticle_jform_request_id&amp;b85b96ca0b5914cb50fc400f9f4aaaef=1" name="Sélectionner ou changer l'article" height="300px" width="800px"></iframe>');``
 

#### System information (as much as possible)
Version de la base de données	5.5.43
Interclassement de la base de données	latin1_swedish_ci
Version de PHP	5.4.43
Serveur web	Apache
Serveur web pour interface PHP	apache2handler
Version de Joomla	Joomla! 3.4.4 Stable [ Ember ] 8-September-2015 21:30 GMT
Version de la plateforme Joomla!	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

#### Additional comments
I removed the apostrophy from the translation string in /administrator/language/fr-FR/com_content.ini line 24. The buttons work, but this is obvoiusly just a temporary workaround.

**Comment by infograf768** [comment]
I have already updated the french lang pack by taking off the quote. Just update the pack.
The original issue has now been solved.
See: https://github.com/joomla/joomla-cms/pull/7845
This can be closed.

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7880">issues.joomla.org/joomla-cms/7880</a>

**Comment by infograf768** [comment]
Closing as this is now solved in core (for next release)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7880">issues.joomla.org/joomla-cms/7880</a>.</sub>
