### ISSUE TITLE
Problem occured at the time of custom changes in TinyMCE

### ISSUE THREAD

**Issue by kiranlohar** [joomla/joomla-cms#7882]
if we insert custom attributes like width, rows, height to TinyMCE editor then its not working properly and only takes admin side HTML height and HTML width

**Comment by kiranlohar** [comment]
custom changes are not working<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7882">issues.joomla.org/joomla-cms/7882</a>.</sub>

**Comment by zero-24** [comment]
@kiranlohar can you give us some examples? I'm not sure that i understand it correct. do you use the `source code` mode of the TinyMCE or the `normal` mode? What are your filter settings?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7882">issues.joomla.org/joomla-cms/7882</a>.</sub>

**Comment by kiranlohar** [comment]
when i use attributes like height, width or rows  in code that time these
attributes are not working properly.

On Fri, Sep 18, 2015 at 2:53 AM, zero-24 <notifications@github.com> wrote:

> @kiranlohar <https://github.com/kiranlohar> can you give us some
> examples? I'm not sure that i understand it correct. do you use the source
> code mode of the TinyMCE or the normal mode? What are your filter
> settings?
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/7882
> <http://issues.joomla.org/tracker/joomla-cms/7882>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7882#issuecomment-141231847>.
>



-- 
Warm Regards
Kiran Lohar
Jr. PHP Developer
Tekdi Technology Pvt. Ltd.

**Comment by infograf768** [comment]
@kiranlohar 

As @zero-24 asked, please give a concrete example and eventual screenshots of what you are doing exactly.

**Comment by zero-24** [comment]
@kiranlohar 

Maybe also help if you tell us how you enter the codes ;) Do you use the `source code` mode of the TinyMCE or the `normal` mode? What are your filter settings?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7882">issues.joomla.org/joomla-cms/7882</a>.</sub>

**Comment by kiranlohar** [comment]
When I enter code like <.....  rows="5" height="500px" > then these
attribute are not working.



On Fri, Sep 18, 2015 at 1:42 PM, zero-24 <notifications@github.com> wrote:

> @kiranlohar <https://github.com/kiranlohar>
>
> Maybe also help if you tell us how you enter the codes ;) Do you use the source
> code mode of the TinyMCE or the normal mode? What are your filter
> settings?
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/7882
> <http://issues.joomla.org/tracker/joomla-cms/7882>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7882#issuecomment-141377534>.
>



-- 
Warm Regards
Kiran Lohar
Jr. PHP Developer
Tekdi Technology Pvt. Ltd.

**Comment by infograf768** [comment]
Where do you enter this code?... The parameter for the default height is set in TinyMce plugin for advanced mode and obtained via javacsript in
```
<script type="text/javascript">
				tinyMCE.init({

[...]
// Advanced Options
					resize: "both",
					height : "450",
```

**Comment by brianteeman** [comment]
As it has been several months since any comments on this issue and no reply to the last request I am closing this at this time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7882">issues.joomla.org/joomla-cms/7882</a>.</sub>
