### ISSUE TITLE
URL of website changes from root domain to server hostname

### ISSUE THREAD

**Issue by Opptur** [joomla/joomla-cms#7883]
#### Steps to reproduce the issue
Just access the website http://moisilbrasov.ro

#### Expected result
All the links should redirect you to a http://moisilbrasov.ro/... page.

#### Actual result
Almost all links redirect to http://webserver.moisilbrasov.ro/... pages. This is the server hostname, which has been set in Linux. This issue is not present in the administration section (/administrator).

#### System information (as much as possible)
OS: CentOS Linux 7.1.1503
Processor: Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz, 4 cores
Memory: 4 GB DDR3
Webpanel: Webmin 1.760 / Virtualmin 4.18
Apache Version: 2.4.6
MySQL Version: MariaDB 10.0.21
PHP Version: 5.4.16

#### Additional comments
This doesn't affect me at all, but I don't think it should act like this. All worked well before updating to Joomla 3.4.4 (from 3.4.3, using the automated updater). The only thing that had been modified into the server in that day were some software updates (subversion and mod_dav_svn via CentOS yum).![screen shot 2015-09-14 at 08 46 25](http://issues.joomla.org/uploads/1/6a1cab605a336d1f72774abafbdb3313.png)

**Comment by Opptur** [comment]
Oh, by the way, the administration section doesn't have this problem. That's why I think it's a Joomla bug.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7883">issues.joomla.org/joomla-cms/7883</a>.</sub>

**Comment by Opptur** [comment]
It seems that now the website adress toggles between the server IP (http://89.121.208.66), http://www.moisilbrasov.ro and http://moisilbrasov.ro. It is pretty weird.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7883">issues.joomla.org/joomla-cms/7883</a>.</sub>

**Comment by zero-24** [comment]
I have just tested the menu and all links are set to `http://moisilbrasov.ro` i can't see a problem there.

**Comment by Opptur** [comment]
It works as it should now, but I haven't changed a thing. I think it's a random issue. Please don't close this ticket, and give me more time to come with some proof. I have no reason to lie.

Anyway, if you hover over the orange image in the right site (one that has written on it "Orarul Elevilor"), the adress looks like this: http://webserver.moisilbrasov.ro. This is the issue I am talking about. It seems that this is the only place that it occurs in now. But it used to do that everywhere, even on this link (showing links as IP adresses).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7883">issues.joomla.org/joomla-cms/7883</a>.</sub>

**Comment by Bakual** [comment]
The orange image is from a custom HTML module. That means the link most likely was manually inserted in the editor and needs to adjiusted there. It's not created by Joomla itself.

**Comment by mbabker** [comment]
Just for reference, Joomla itself pretty much defaults to building relative URLs unless code is explicitly instructed to write an absolute URL if the target URL is on the same domain as the active request.  It's been a while since I looked at it, but I think the `$live_site` variable in the `configuration.php` file affects this behavior so it always uses the same domain.

So what this means basically is that when you access the site via its IP address or another (sub)domain that points to that same site, Joomla itself won't care and will write relative (non-domain-inclusive) links.  I'd check to make sure that if `$live_site` is set in your config file that it has a value that matches what you want your site to be.  Otherwise, Joomla itself pretty much doesn't write absolute links by default on HTML pages so shouldn't be causing the issue you're seeing (keyword shouldn't, not saying it's 100% impossible, it is code written by humans we're talking about here).

**Comment by Opptur** [comment]
Well, I find it weird that last night it had that problem but this morning it was all back to normal. I can see from time to time a change of adress (from http://moisilbrasov.ro to http://www.moisilbrasov.ro), but it doesn't do it anymore. It's pretty weird. I will wait for a couple of days and try to reproduce this issue.

The $live_site variable is blank. I have uploaded a picture with the way that issue manifests itself now. This is not a problem, but it used to show the IP adress of the server or even the hostname set in Linux (webserver.moisilbrasov.ro). I'll have to wait and see if that issue shows up ![screen shot 2015-09-15 at 11 01 33](http://issues.joomla.org/uploads/1/5e7937c3c46bcd2e121e5d35c911bfed.png)again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7883">issues.joomla.org/joomla-cms/7883</a>.</sub>

**Comment by brianteeman** [comment]
It's a caching issue.
Visit site from the non-www url and all the generated menu links will be
without the www as expected and previously explained.
Now visit the www url and you will see the previously generated cache
without the www in the URLs.
Return later and cache may have expired so you see the URLs generated
afresh.

**Comment by Opptur** [comment]
Well, you are right. After clearing the website cache and my browser cache, the problem doesn't show up anymore. So, then, it's no bug, just a browser cache issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7883">issues.joomla.org/joomla-cms/7883</a>.</sub>

**Comment by Bakual** [comment]
browser or server cache.

**Comment by brianteeman** [comment]
It is the web site cache not the server cache.

The correct way to resolve this is to ensure that your site is only ever
loaded with www

Google redirect non-www to www in htaccess for the how to

On 15 September 2015 at 19:21, Thomas Hunziker <notifications@github.com>
wrote:

> browser or server cache.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7883#issuecomment-140489579>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Oops that should have been
It is the web site cache not the BROWSER cache.


On 15 September 2015 at 19:30, Brian Teeman <brian@teeman.net> wrote:

> It is the web site cache not the server cache.
>
> The correct way to resolve this is to ensure that your site is only ever
> loaded with www
>
> Google redirect non-www to www in htaccess for the how to
>
> On 15 September 2015 at 19:21, Thomas Hunziker <notifications@github.com>
> wrote:
>
>> browser or server cache.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joomla/joomla-cms/issues/7883#issuecomment-140489579>
>> .
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Opptur** [comment]
Well, everything works fine now, and I don't know why. If the bug shows up again remains to be seen.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7883">issues.joomla.org/joomla-cms/7883</a>.</sub>

**Comment by Bakual** [comment]
Closing as not a core issue.
