### ISSUE TITLE
Behavior Modal loading mootools library unnecessarily

### ISSUE THREAD

**Issue by akfaisel** [joomla/joomla-cms#7887]
#### Steps to reproduce the issue
Importing the modal library loads mootools library which should be removed.

    JHtml::_('behavior.modal', 'a.modal');

#### Expected result

Do not load mootools library

#### Actual result

    <script src="/sitename/media/system/js/mootools-core.js" type="text/javascript"></script>
    <script src="/sitename/media/system/js/mootools-more.js" type="text/javascript"></script>

#### System information (as much as possible)

In * <root>/libraries/cms/html/behavior.php*, **public static function modal**, the following line is called which is not necessary at all. 

    // Include MooTools framework
    static::framework(true);

If we dig more down the same function, the script declaration has the syntax of jQuery.
```
// Attach modal behavior to document
$document
	->addScriptDeclaration(
	"
jQuery(function($) {
	SqueezeBox.initialize(" . $options . ");
	SqueezeBox.assign($('" . $selector . "').get(), {
		parse: 'rel'
	});
});
function jModalClose() {
	SqueezeBox.close();
}"
);
```

**Comment by zero-24** [comment]
@dgt41 can you have a look into here? I'm not on the latest state regarding JQuery / Mootools ;)

**Comment by dgt41** [comment]
But if you remove the mootools dependency then you get errors in your console and modal is not working:
![screen shot 2015-09-15 at 3 07 49](https://cloud.githubusercontent.com/assets/3889375/9876114/3f31a270-5bbc-11e5-8a64-ef7c465af7a4.png)

So, unfortunately modal.js needs the mootools scripts

**Comment by mbabker** [comment]
SqueezeBox is dependent on MooTools to function (see the project site http://digitarald.de/project/squeezebox/) so it is indeed a required dependency to load it.

**Comment by akfaisel** [comment]
I'm sorry, I have failed to check this without loading mootools. I guess
like modal.js should be upgraded or converted to be used with jQuery as
Joomla has already moved away from mootools.

**Comment by mbabker** [comment]
modal.js is the SqueezeBox modal.  IMO that shouldn't be touched unless they have a jQuery compatible version of their code, it's not our place to be hacking third party code.

**Comment by dgt41** [comment]
@akfaisel I thought that converting this script to Jquery would be a good thing. Yesterday. Today I realized that for some events people might be using mootools to program them, so unfortunately this cannot be done keeping backwards compatibility. Best way out of this is by using Bootstrap modal code...
