### ISSUE TITLE
Escape problem on final Installation

### ISSUE THREAD

**Issue by efEris** [joomla/joomla-cms#7889]
#### Steps to reproduce the issue
Install Joomla 3.4.4 in German language. 
Delete the installation directory.
The translation show html encoded text.

#### Expected result
Normal text.

#### Actual result
Double encoded text. See sceenshot.

**Comment by Bakual** [comment]
You forgot to attach the screenshot :smile:

**Comment by efEris** [comment]
Here the missing attachment... I missed the "start" button...

![screen shot 2015-09-15 at 07 31 45](http://issues.joomla.org/uploads/1/7c74079ef43a29b77eac910bda82ba21.jpg)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7889">issues.joomla.org/joomla-cms/7889</a>.</sub>

**Comment by Bakual** [comment]
Looks like it's wrong in the language file. @sisko1990 for you to check :smile:

**Comment by infograf768** [comment]
„installation“ can be used instead of the htmlentities (tested).

**Comment by zero-24** [comment]
Fixed by  @sisko1990 here. https://github.com/joomlagerman/joomla/commit/5109303e75a656a2026f8f5da6277a22013dbc8d should be fine with the next update. Thanks ;)
