### ISSUE TITLE
Popups don't open when an apostrophe is in the name

### ISSUE THREAD

**Issue by hikashop-nicolas** [joomla/joomla-cms#7890]
The problem happens on any page with a popup with an apostrophe in the name (for example the add to cart HTML button of the product edition page of the extension HikaShop Starter, or with languages other than english with some of the popups of the backend of Joomla itself).
Here is a thread about the issue with the proposed fix on this post:
http://www.hikashop.com/forum/install-update/879271-troubles-adter-upgrade-from-3-4-3-joomla-to-3-4-4.html#214269
And here is a thread on the French Joomla forum with the same problem:
http://forum.joomla.fr/showthread.php?211259-Bug-de-joomla-3-4-4-sur-les-liens-de-menu-type-article/page4
(they solved it by releasing a new language pack without the apostrophe in the name of the popups)

**Comment by dgt41** [comment]
This has been already resolved (in current staging) with https://github.com/joomla/joomla-cms/pull/7845
