### ISSUE TITLE
Tag Cloud Component Links Returning Blank Page

### ISSUE THREAD

**Issue by genemix** [joomla/joomla-cms#7898]
#### Steps to reproduce the issue
Go to my website at http://80sMixed.com | Scroll down a bit and see the Tag Cloud on the right hand side. Click any link with the tag cloud.

#### Expected result
The tag link should produce results based on the tagged subject.

#### Actual result
The tag link produces a blank web page with nothing on it.

#### System information (as much as possible)
Setting 	Value
 
PHP Built On 	Linux p3plcpnl0425.prod.phx3.secureserver.net 2.6.32-604.16.2.lve1.3.54.el6.x86_64 #1 SMP Mon Jul 27 11:32:29 EDT 2015 x86_64
Database Version 	5.5.42-cll-lve
Database Collation 	utf8_general_ci
PHP Version 	5.4.44
Web Server 	Apache/2.4.12
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.4.4 Stable [ Ember ] 8-September-2015 21:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; rv:40.0) Gecko/20100101 Firefox/40.0 

#### Additional comments
This started happening after the latest upgrades.

**Comment by mbabker** [comment]
Enable error reporting in your site's configuration.  A blank white page like this indicates a PHP error that is not being displayed.  After having an error message, further troubleshooting can happen.

**Comment by genemix** [comment]
Saw the error. Had to do with a plugin. I disabled the plugin named RokInjectModule. I don't inject modules into my content so I don't need it anyway. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7898">issues.joomla.org/joomla-cms/7898</a>.</sub>

**Comment by roland-d** [comment]
Thanks for reporting back. Closing this issue as it is not a Joomla issue.
