### ISSUE TITLE
Manual User activation not triggering emails

### ISSUE THREAD

**Issue by danielnitsak** [joomla/joomla-cms#7899]
I've just updated to 3.4.4, the site uses user verification as well as admin activation. Typically the user registers and receives an email to verify their address(1), the user clicks a link and this triggers an email to the administrator (2) to login and activate (enable) the user.

The admin then logs in and enables the user and activates their account however, at present this is not triggering any email to the user once they are enabled and activated. All is set correctly (3) and there is no explanation as to why this is not working correctly.

1.
![screen shot 2015-09-17 at 08 36 52](https://cloud.githubusercontent.com/assets/13118673/9926645/c0fc9d4e-5d17-11e5-8f0d-b7b3218178e0.png)

2.
![screen shot 2015-09-17 at 08 33 17](https://cloud.githubusercontent.com/assets/13118673/9926650/ce8326d6-5d17-11e5-9f92-30f2fa8c999e.png)

3.
![screen shot 2015-09-16 at 16 43 43](https://cloud.githubusercontent.com/assets/13118673/9908979/68f0bc92-5c96-11e5-9aff-426f382fab30.png)

**Comment by danielnitsak** [comment]
My sincere apologies, this is actually working perfectly.

**Comment by danielnitsak** [comment]
Further investigation on my site and blank test site shows that a manual "Activation" clicking the button from the backend (1) it fails to send the user email however, if the administrator clicks the verification link in their email, the newly registered user is sent an email.

The reason I feel this is flawed is that often, when ACL is in use, the newly registered user may need to be assigned to a user-group and in that instance the workflow of clicking an email link and then logging in is not efficient. 

Surely the action of clicking the "Activate" button should trigger an email as well?

![screen shot 2015-09-17 at 15 38 04](https://cloud.githubusercontent.com/assets/13118673/9934518/33a5f2d4-5d52-11e5-85bf-50cb1b75d074.png)

**Comment by infograf768** [comment]
Have you set the User - Joomla plugin to send a Notification mail to user?

**Comment by danielnitsak** [comment]
Yes, this is done, see below, I believe this is enabled by default or when the setting is changed in the User settings area:

![screen shot 2015-09-18 at 11 44 19](https://cloud.githubusercontent.com/assets/13118673/9956652/b00199de-5dfa-11e5-8a2d-e5f748648049.png)

Perhaps I wasn't specific enough, the notifications are being sent but only if the administrator clicks the URL with the token from their user verification email. The problem is that if there is additional steps to activating the user, the admin would likely login into the backend and not click the URL with the activation token (as this would notify the user before the additional steps were taken e.g. assigning to user groups), so the admin would login, assign the user to the specific group (when a default group does not apply) and then click the "Activate" button which is the red X and it's this that does not trigger for the "user enabled" email.

![screen shot 2015-09-17 at 15 38 04](https://cloud.githubusercontent.com/assets/13118673/9956700/09068c38-5dfb-11e5-9b6d-bc17ca6b9394.png)

**Comment by zero-24** [comment]
I'm not sure if we should implement that. So I'm setting that to `Needs Review`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7899">issues.joomla.org/joomla-cms/7899</a>.</sub>

**Comment by roland-d** [comment]
@danielnitsak Thank you for your suggestion but it has been decided that this is not something that will be included in the core of Joomla. If we send the mail when the activation button is clicked, it would be send every time the same user is activated. This can also happen if the user has requested a password reset, the activation is also disabled. The only way I see this happen is if someone builds the option to send the welcome mail. This may need to be part of a larger solution that deals with the emails Joomla sends.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7899">issues.joomla.org/joomla-cms/7899</a>.</sub>
