### ISSUE TITLE
Pagination issues in Joomla 3.4.2

### ISSUE THREAD

**Issue by Wilkins** [joomla/joomla-cms#7900]
Hi,

I'm having issues with the pagination in Joomla 3.4.2. (I tried upgrading to 3.4.4 but it didn't help)
I recently upgraded from Joomla 2.5.28 to Joomla 3.4.2.
I'm using JoomSEF for URL rewriting.

My website is for production, so I can't give you access the the administration zone, but I'm willing to give you all the details you need.

I have a list of news that I want to display as a category blog (see: http://www.celeste.fr/actualites/blog/ ). There is about 90 articles, and when I choose to display « introduction text » for 10 of them, they display fine, and the pagination sequence appears, but all the links in the pagination block redirect to the first page : http://www.celeste.fr/actualites/blog/ .

I tried to modify the pagination.php in my template to change the links to /actualites/blog/page-2 , /actualites/blog/page-3 , /actualites/blog/page-4 , etc. But it's not working either, because these URL are not working, they return a 404 error. (For now I redirected the  /actualites/blog/page-2 to  /actualites/blog/ for testing).

For now I'm displaying all the other articles as « title with link (# Links) » so users and search engines can find them.
Moreover I encountered a side effect problem because Joomsef only create URL for pages that are linked inside Joomla. So since the 2nd, 3rd ... pages did not display, there were no links to these articles anymore, so the SEF URL rewriting was not working for these new articles and they returned a 404. Which is a really bad side effect.

I wonder if this issue is linked with #4329 and #4330 but these ones seem resolved since 3.3.5

I'm available to help or test stuff. I'm also open for suggestions about Rewrite or SEF patchs.

Thanks.

**Comment by Bakual** [comment]
First, upgrade to 3.4.4 (even if it doesn't help, still do) and then make sure it's not an issue with JoomSEF (disable it and see if it works). It's most likely coming from there.

**Comment by brianteeman** [comment]
Also please check using one of the default templates (protostar or beeZ) as
there are regular reports of pagination issues in badly coded templates.

**Comment by Wilkins** [comment]
Ok, thanks for these suggestions, I'll try that today, and report to you.

**Comment by wilsonge** [comment]
Hi @Wilkins thought I'd follow up on this - did you manage to find out anything?

**Comment by brianteeman** [comment]
After several months without reply I am closing this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7900">issues.joomla.org/joomla-cms/7900</a>.</sub>
