### ISSUE TITLE
Unable to save params which are added through custom plugin

### ISSUE THREAD

**Issue by nareshbtech514** [joomla/joomla-cms#7903]
#### Steps to reproduce the issue
Hello,

I have been Working with Joomla from 3 years.

Now i get stuck with new Issue, unable to save a attribs param which is added through custom plug-in.

My requirement is to add couple of params through Plug-in and base on some condition i have to remove one param from these list.

I have used joomla $form api to do this but it didn't work.

**code:**

$form->loadFile('params', false);
if(!in_array($data->catid,$mappedCategories))
{
    $form->removeField("mappedCategory","attribs");
}

#### Expected result
Saving **mappedCategory** field to attribs list

#### Actual result
**mappedCategory** param removed from database when i save the article

**Comment by Bakual** [comment]
This is the issue tracker for the core CMS. For support requests please use the Google Group (https://groups.google.com/forum/#!forum/joomla-dev-general) or the forums (http://forum.joomla.org/)

Closing as not an issue within core.
