### ISSUE TITLE
Misclosed HTML tag in default.php template file of backend module: mod_multilangstatus

### ISSUE THREAD

**Issue by ggppdk** [joomla/joomla-cms#7906]
I am trying to eliminate as many HTML validation errors in backend as possible

I noticed that in J3.4.4 and staging branch too:

https://github.com/joomla/joomla-cms/blob/staging/administrator/modules/mod_multilangstatus/tmpl/default.php

Their is a `<button>` HTML Tag closed with an `</a>`

`$footer = '<button class="btn" data-dismiss="modal" aria-hidden="true">' . JText::_('JTOOLBAR_CLOSE') . '</a>';`

**Comment by wojsmol** [comment]
@ggppdk Please test #7907

**Comment by ggppdk** [comment]
Test ok,
and i see that there was a similar case of misclosed HTML Tag in com_users, that you patched too
