### ISSUE TITLE
Recaptcha core plugin onCheckanwser

### ISSUE THREAD

**Issue by Dekari** [joomla/joomla-cms#7921]
#### Steps to reproduce the issue

Use recaptcha plugin in custom component. Use multiple instances of it so each instance has it's own input name.

When you call the recaptcha plugin to validate you can pass the $code to validate instead of the "standard" code from input.

see the function declaration: public function onCheckAnswer(**$code = null**)

e.g.

$alldata = JFactory::getApplication()->input;
$cresponse     = $alldata->get('grecaptcharesponse','','string'); //here we have the catcha code to validate
     
  //call captcha plugin to validate code
  JPluginHelper::importPlugin('captcha');
  $dispatcher = JEventDispatcher::getInstance();  
  $res = $dispatcher->trigger('onCheckAnswer',$cresponse);

### Expected result

A true validation of the $cresponce

#### Actual result

Always false

#### System information (as much as possible)

Joomla! 3.4.4 Stable [ Ember ] 8-September-2015 21:30 GMT
PHP: 5.4.43
Mysql: 5.5.42-37.1-log

#### Additional comments

The issue is on the onCheckReponse function of the captch plugin where has the $code param that your are able to pass but in true code the $code param is totally ignored.

I have a solution to propose that working ok:

in /plugins/captcha/recaptcha.php replace (about line 127):

$response  = $input->get('g-recaptcha-response', '', 'string');

with:

 if (!empty($code))
     $response = $code;
 else
     $response  = $input->get('g-recaptcha-response', '', 'string');                
                
And issue will be solved.

thanks and i hope helped

christopher

**Comment by zero-24** [comment]
Hi :)

can you send your changes as pull request? The easy way is: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests 

let me know if you need help with it.

**Comment by Dekari** [comment]
Helo zero-24 i just made the pull request as u asked me.

Please inform me of any issues or questions

thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7921">issues.joomla.org/joomla-cms/7921</a>.</sub>

**Comment by zero-24** [comment]
Closing as we have a PR here: https://github.com/joomla/joomla-cms/pull/7940 Thanks @Dekari<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7921">issues.joomla.org/joomla-cms/7921</a>.</sub>
