### ISSUE TITLE
Joomla jos-warning

### ISSUE THREAD

**Issue by Thovt** [joomla/joomla-cms#7929]
Hello,
 
i think that after update joomla to 3.4.4 and when i click on the google result of my page (www.e3d.sK) the page dont loads but this is loaded:

jos-Warning: exception 'RuntimeException' with message 'Unknown column 'header' in 'field list' SQL=SELECT `new_url`,`header`,`published` FROM `nrios_redirect_links` WHERE `old_url` = 'http://e3d.sk/index.php/ponuka/recyklacia' LIMIT 0, 1' in /www/e/3/u59271/public_html/libraries/joomla/database/driver/mysqli.php:610 Stack trace: #0 /www/e/3/u59271/public_html/libraries/joomla/database/driver.php(1279): JDatabaseDriverMysqli->execute() #1 /www/e/3/u59271/public_html/plugins/system/redirect/redirect.php(86): JDatabaseDriver->loadObject() #2 [internal function]: PlgSystemRedirect::handleError(Object(JException)) #3 /www/e/3/u59271/public_html/libraries/legacy/error/error.php(760): call_user_func(Array, Object(JException)) #4 [internal function]: JError::handleCallback(Object(JException), Array) #5 /www/e/3/u59271/public_html/libraries/legacy/error/error.php(218): call_user_func_array(Array, Array) #6 /www/e/3/u59271/public_html/libraries/legacy/error/error.php(179): JError::throwError(Object(JException)) #7 /www/e/3/u59271/public_html/libraries/legacy/error/error.php(254): JError::raise(1, 404, '??l??nok nebol ...', NULL, true) #8 /www/e/3/u59271/public_html/components/com_content/models/article.php(163): JError::raiseError(404, '??l??nok nebol ...') #9 /www/e/3/u59271/public_html/libraries/legacy/view/legacy.php(401): ContentModelArticle->getItem() #10 /www/e/3/u59271/public_html/components/com_content/views/article/view.html.php(42): JViewLegacy->get('Item') #11 /www/e/3/u59271/public_html/libraries/legacy/controller/legacy.php(690): ContentViewArticle->display() #12 /www/e/3/u59271/public_html/components/com_content/controller.php(104): JControllerLegacy->display(true, Array) #13 /www/e/3/u59271/public_html/libraries/legacy/controller/legacy.php(728): ContentController->display() #14 /www/e/3/u59271/public_html/components/com_content/content.php(16): JControllerLegacy->execute(NULL) #15 /www/e/3/u59271/public_html/libraries/cms/component/helper.php(392): require_once('/www/e/3/u59271...') #16 /www/e/3/u59271/public_html/libraries/cms/component/helper.php(372): JComponentHelper::executeComponent('/www/e/3/u59271...') #17 /www/e/3/u59271/public_html/libraries/cms/application/site.php(191): JComponentHelper::renderComponent('com_content') #18 /www/e/3/u59271/public_html/libraries/cms/application/site.php(230): JApplicationSite->dispatch() #19 /www/e/3/u59271/public_html/libraries/cms/application/cms.php(252): JApplicationSite->doExecute() #20 /www/e/3/u59271/public_html/index.php(45): JApplicationCms->execute() #21 {main}

**Comment by zero-24** [comment]
please fix the database and try again ;) (Backend -> Extension -> Manage --> Database --> fix.)

**Comment by sovainfo** [comment]
Suggest to find out why the update failed and try updating again after restore of backup and fix of infra.
Although Database->Fix might add the missing column, consider it more important to update properly!

Also, you should use forum.joomla.org for issue's with migrating/updating. This is for changes to Joomla code, not for issues running a Joomla website!

**Comment by Thovt** [comment]
this doesnt work for me :(

**Comment by rdeutz** [comment]
as others already said, use the forum for problems like that, here isn't the right place. Closing it because it isn't a bug

**Comment by Thovt** [comment]
OK thanks
