### ISSUE TITLE
Fatal error after update from 3.4.1 to 3.4.4

### ISSUE THREAD

**Issue by fastslack** [joomla/joomla-cms#7931]
## How to reproduce

Just try to update from 3.4.1 to 3.4.4

## Return

```
Fatal error: Access level to JInstallerAdapterLibrary::prepareDiscoverInstall() 
must be public (as in class JInstallerAdapter) in 
/www/libraries/cms/installer/adapter/library.php on line 0
```

**Comment by mbabker** [comment]
It is public - https://github.com/joomla/joomla-cms/blob/3.4.4/libraries/cms/installer/adapter/library.php#L190 - this implies either a core hack or someone overloading the core class to me.

**Comment by Bakual** [comment]
It was changed from protected to public with https://github.com/joomla/joomla-cms/pull/6024
But that would have been done with Joomla 3.4.0. So if you have a 3.4.1, it should already be public. Or you have had a botched update when you went to 3.4.1.

**Comment by fastslack** [comment]
ok, closing
