### ISSUE TITLE
Access Level to pages doesn't work since 3.4.4

### ISSUE THREAD

**Issue by visualtribe** [joomla/joomla-cms#7933]
#### Steps to reproduce the issue
create a link to a page and give it an access level, Special, Registered, SuperUser

#### Expected result
If the user logs in and has that access level, page should show

#### Actual result
User or SuperUser get error:

Message
You do not have permission to go to this area.
SuperUser has access to everything. Cleared all cache. Dumped all browser cache. Used levels SuperUser, Registered, Special. All fail. 

Joomla 3.4.3 worked fine until update. 

#### System information (as much as possible)
Brand new install of Joomla 3.4.3 and creation of site. Updated site to Joomla 3.4.4. Issue started. Tested issue on another site that has been working fine for 3.4.3. Since Update no access to levels.

**Comment by dgt41** [comment]
Is this a link to an article or to some 3rd party developer component?

**Comment by visualtribe** [comment]
The link is to a third party link to form page to add a property. I tested it a Joomla login page and another component page, docman and the links worked. So when the link is set to a group their code affects the ability to get to the page?

**Comment by visualtribe** [comment]
In this issue tracker just created I am having issues with the menus showing up even if I am not logged in. 

http://issues.joomla.org/tracker/joomla-cms/7949

The link was to k2 item page.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7933">issues.joomla.org/joomla-cms/7933</a>.</sub>

**Comment by visualtribe** [comment]
I believe I have figured this out and from what I am seeing here it was from a Redirect plugin that I installed. I have taken it out and now the ACL works and the link passes correctly. Sorry for the inconvenience.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7933">issues.joomla.org/joomla-cms/7933</a>.</sub>

**Comment by visualtribe** [comment]
I believe I have found the cause of this. It was a redirect plugin that wasn't working with 3.4.4. I have taken it out. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7933">issues.joomla.org/joomla-cms/7933</a>.</sub>
