### ISSUE TITLE
Fix com_contact > created vcf in contactform can´t handle german umlauts

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-cms#7937]
#### Steps to reproduce the issue
Put in some contact information with ß ä ö ü inside and enable the Option .vcf for the contact view.
Download the vcf

#### Expected result
The vcf should contain the umlauts. 

#### Actual result
On Apple devices the umlauts are shown correctly but but not in outlook on windows.

#### Additional comments
I added utf8decoding in the code, that fixes the problem. As i´m not a developer please review also the way how i fixed it.

PR
https://github.com/joomla/joomla-cms/pull/7938

**Comment by brianteeman** [comment]
closed as we have a PR #7938 
@designbengel you dont need to create an issue on the tracker and a PR on github. When you create a PR on github it automagically adds it to the issue tracker<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7937">issues.joomla.org/joomla-cms/7937</a>.</sub>
