### ISSUE TITLE
filter articles on article category list view gone on pagination

### ISSUE THREAD

**Issue by mhehm** [joomla/joomla-cms#7943]
Steps to reproduce the issue:
- Install a fresh Joomla! 3.4.4 with blog english testing data.
- go to article manager and select all articles and batch copy them to increase number of articles to more then 50 article and publish all of them.
- go to menu manger and create a menu to category list to blog category with enabled title filter in list layout options.
- go to created menu in frontend and enter 'about' in title filter
- filter results have many items and pagination appear
- click on page 2 or other pages off pagination
- your filter gone and result of 'about' not showing. it show pagination result of all articles.

**Comment by RonakParmar** [comment]
Hi,

I have followed above steps and able to re-produce this issue in Joomla 3.4.4.

Regards,
Ronak Parmar.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7943">issues.joomla.org/joomla-cms/7943</a>.</sub>

**Comment by gunjanpatel** [comment]
I can also confirm the bug, followed the steps provided and not able to get filter work with pagination.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7943">issues.joomla.org/joomla-cms/7943</a>.</sub>

**Comment by brianteeman** [comment]
Confirmed as still an issues in 3.5beta2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7943">issues.joomla.org/joomla-cms/7943</a>.</sub>

**Comment by jlainezs** [comment]
Just sent a PR for this issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7943">issues.joomla.org/joomla-cms/7943</a>.</sub>

**Comment by gunjanpatel** [comment]
Set to "closed" on behalf of @gunjanpatel by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7943">issues.joomla.org/joomla-cms/7943</a>
