### ISSUE TITLE
Menu Manager does not work properly

### ISSUE THREAD

**Issue by visualtribe** [joomla/joomla-cms#7949]
#### Steps to reproduce the issue
Go to menu manager. Create a new menu. Menu not added to menu. 
and
Got to menu manager. Create Password reset in user. 
and 
Go to menu manager. Create Username Reminder Request

#### Expected result
Menu added to menua and works properly

#### Actual result
Menus not added in each case. 
In regards to password and username, I already had these two in my menu list. Since update of 3.4.4 don't work and go to a 404 page. I deleted them and was going to recreate, but after trash, they still show up in my menus. Won't go away and the new one with new name for link won't show up. 

#### System information (as much as possible)
Running Joomla 3.4.4 
Using SWMenuPro to style menus and never had an issue with it and didn't have an issue with it with 3.4.3

**Comment by visualtribe** [comment]
I have now experimented with these links and now they are showing up, but password and username page still go to 404. The trash menus are now gone, but take several refreshes to make them go away. Something also to this that I have stated before in another issue, when I make the link Super User Access the link shows up even if I am not logged in. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7949">issues.joomla.org/joomla-cms/7949</a>.</sub>

**Comment by brianteeman** [comment]
I see you other issue was resolved by removing a faulting 3pd plugin. Has this been resolved as well<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7949">issues.joomla.org/joomla-cms/7949</a>.</sub>

**Comment by visualtribe** [comment]
Yes seems to working now

**Comment by roland-d** [comment]
Closing as issue is resolved.
