### ISSUE TITLE
Error uninstalling Component 3.4.4

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#7954]
#### Steps to reproduce the issue

I uninstalled akeeba component and recieved
![screen shot 2015-09-27 at 17 21 52](http://issues.joomla.org/uploads/1/0e5f1fc45f1021403e090eb1a8f6a4b8.jpg)

idk if this is akeeba issue or not but based on the error I think its probably not.
#### Additional comments

**Comment by mbabker** [comment]
Gonna need a lot more data to try and work with that one.  `JDatabaseQueryElement` (the class that is in use on that line) is used by almost every query element so without knowing what element type it is or what data got plugged into it it's next to impossible to do anything other than say "yep, you've got an error message".

**Comment by rgblogs** [comment]
I think the error is somewhere related to user table.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7954">issues.joomla.org/joomla-cms/7954</a>.</sub>

**Comment by alikon** [comment]
I've uninstalled other components and pkgs without problems, could be related to that component which version are you using?

**Comment by brianteeman** [comment]
After several months without reply I am closing this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7954">issues.joomla.org/joomla-cms/7954</a>.</sub>
