### ISSUE TITLE
Extension manager search box doesn't clear

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#7957]
#### Steps to reproduce the issue
type in a search word in extension manager->manage->search 
complete search.
hit the X to clear the search field
delete keyword manually

#### Expected result
search keyword is removed

#### Actual result
screen flashes and word remains

#### System information (as much as possible)

![screen shot 2015-09-27 at 17 41 12](http://issues.joomla.org/uploads/1/348a15f71a129639b023f3fe7b55ec0b.jpg)

#### Additional comments

removing cookie removes the keyword and once again displays the listing.

**Comment by justinherrin** [comment]
I can not replicate this report. I am testing with a fresh install of 3.4.4, using Chrome and Firefox browsers on a Mac and everything is working normally as we would expect.

@N6REJ - is it a browser issue perhaps?

**Comment by rgblogs** [comment]
Yes, everything is working properly<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7957">issues.joomla.org/joomla-cms/7957</a>.</sub>

**Comment by N6REJ** [comment]
no, its not.. I've done 3 clean installs all with same behavior in chrome

**Comment by N6REJ** [comment]
problem still exists in 3.5.8 even on new install

**Comment by jemmyn** [comment]
Same issue with me. I have this on multiple installs all on the same server. Using Chrome or Safari same results. It happens no matter where I am searching, Modules, Articles, etc... No way to completely clear out the search once you have something in there. The only way to clear it is to logout of Joomla admin and back into it. It even affects the Intro Image and Full Article Image. Now that I have something specified in there I can not find a way to remove it. Click X the image path disappears and then click save and its back again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7957">issues.joomla.org/joomla-cms/7957</a>.</sub>

**Comment by izharaazmi** [comment]
@N6REJ Yes, that is related to the same root.

**Comment by N6REJ** [comment]
fix by upgrading suhosin the the very latest version available.

**Comment by brianteeman** [comment]
closing as proven to be an issue with suhosin (resolved in latest release) and not joomla<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7957">issues.joomla.org/joomla-cms/7957</a>.</sub>
