### ISSUE TITLE
Edit Module (Front end) Loses Module Position if Position not defined in Template XML

### ISSUE THREAD

**Issue by xmanflash** [joomla/joomla-cms#7964]
#### Steps to reproduce the issue
Assign a module to a custom position in the Joomla Administration, one that is not specified in the Template XML file.

Edit this module int eh Front end, and the custom Position isa not listed, causing the module to be aasigned to the first Position in the Position dropdown.

#### Expected result
The Custom Position should be retained.  This will cause many customers issues.

The workaround is to make sure we update the Template XML file with the custom positions, but this is not needed when editing in the Back End.

Cheers,
Pete

**Comment by alexonbalangue** [comment]
the config after [...]/tpl/[name]/html is config or create style Jinclude.on file module.php

**Comment by roland-d** [comment]
I am closing this issue as it no longer seems to be present in the current codebase as the front-end module editing only allows to choose a position from the current template. Thank you for your contribution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7964">issues.joomla.org/joomla-cms/7964</a>.</sub>

**Comment by brianteeman** [comment]
That's the problem @roland-d

If you try to edit a module that is not in the list of modules in the templatedetails.xml then you can no longer save it in that custom position

**Comment by xmanflash** [comment]
Roland - I don't think you understood the issue.

Module positions should not be limited to ones defined in the XML file 
in the front end editor, if you can still randomly create them and use 
them from the /administration/ section without needing to be in the xml 
file.

Cheers,
Pete

**Comment by mbabker** [comment]
Reopening.  As long as we support defining custom positions in the backend, saving the same record on the frontend should NOT cause data loss.

**Comment by brianteeman** [comment]
Looks like it is resolved by #7540

**Comment by roland-d** [comment]
Sorry guys, in that case I did misunderstand the issue.

**Comment by brianteeman** [comment]
@xmanflash looks like it is resolved by #7540 please test

**Comment by brianteeman** [comment]
I am closing this as it is fixed by #7540<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7964">issues.joomla.org/joomla-cms/7964</a>.</sub>
