### ISSUE TITLE
extension language pack uninstallation issue related to xml manifest file

### ISSUE THREAD

**Issue by WimVDK** [joomla/joomla-cms#7968]
#### Steps to reproduce the issue
Install either one of attached extension language packs
Try to uninstall them
Joomla installer throws an error

#### Expected result
Correct uninstallion

#### Actual result
yellow warning:

warning

Files Uninstaller: the manifest file is invalid or it was not found.

and a green message:

Message:
an error occured during uninstallation of file

However the language pack WAS succesfully removed.

#### System information (as much as possible)

Issue present in atleast Joomla! 3.4.3 and 3.4.4

#### Additional comments

I've contacted the developer who's component i use to do my translations with and create extension packages. I've included the entire chat history

Extensions used: Freestyle Translation manager to do the translation and create extension language packages
Additional attachments:

zipfile containing 
- word document with developer ticket support chat history
- extension language pack generated with the "Freestyle Translation Manager" (foxcontactbe.nl-BE.zip)

#### INFO DOWNLOAD LINK ####

https://goo.gl/pYgCnw

The problem:

The problem is in the file libraries\cms\installer\adapter\file.php. When installing a file package, it saves a copy of the xml manifest in the administrator/manifests/files folder with the same name of the file from the zip. When it comes to uninstall, the system assumes the manifest is in a file based upon the name of the package instead of what was installed so fails.

Workarround until the issue is fixed:

The only way around this is to name the manifest xml file based on the name

**Comment by infograf768** [comment]
Formatting of an extension lang pack obey to certain rules

Here is an extension lang pack working as should: https://www.dropbox.com/s/94ouv3kvnsqsmql/josdewplayer_fr-FR_1.0v1.zip?dl=0

Name in the xml
<name>josdewplayerfr-FR</name>

name of zip

josdewplayer_fr-FR_1.0v1.zip

Name of manifest xml as it is saved after install:
josdewplayerfr-FR.xml

See also https://docs.joomla.org/J2.5:Making_non-core_language_packs

**Comment by infograf768** [comment]
In the tutorial, it is clearly stated:

`<!-- Please use a unique name to make uninstall to work. Should be identical to your manifest filename. -->`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7968">issues.joomla.org/joomla-cms/7968</a>.</sub>

**Comment by WimVDK** [comment]
Perhaps, except i have no idea what you mean. I'm not the developer. I simply reported the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7968">issues.joomla.org/joomla-cms/7968</a>.</sub>

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7968">issues.joomla.org/joomla-cms/7968</a>

**Comment by infograf768** [comment]
Not an issue. it is part of the uninstall code and should be done correctly when creating file packages.

Closing as it is expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7968">issues.joomla.org/joomla-cms/7968</a>.</sub>
