### ISSUE TITLE
JDatabaseQuery::__toString() does not utilize unionAll query element

### ISSUE THREAD

**Issue by izharaazmi** [joomla/joomla-cms#7970]
It is observed that the `JDatabaseQuery::unionAll()` method creates a `JDatabaseQueryElement` named `unionAll`  [see JDatabaseQuery::unionAll()](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/query.php#L1716) which is never utilized when converting the JDatabaseQuery object to a real string query  [see JDatabaseQuery::__toString()](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/query.php#L259).
This results in an incorrect `query` string.

The unit test case uses `Reflection` class to get the value of `unionAll` element, which is not sufficient. Test case should be made as realistic as possible.  [see JDatabaseQueryTest::unionAllUnion()](https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/joomla/database/JDatabaseQueryTest.php#L1876)

There are multiple possible ways we can fix this, therefore I wanted to discuss it before making a PR.

**Comment by gunjanpatel** [comment]
Set to "closed" on behalf of @gunjanpatel by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7970">issues.joomla.org/joomla-cms/7970</a>

**Comment by gunjanpatel** [comment]
Closing as we have PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7970">issues.joomla.org/joomla-cms/7970</a>.</sub>
