### ISSUE TITLE
Cannot upload extension (un-safe)

### ISSUE THREAD

**Issue by breebee** [joomla/joomla-cms#7971]
Please help. i cannot upload a file due to not being safe. I need to override this how can i ?

**Comment by roland-d** [comment]
Please provide a description, otherwise I will have to close the issue. Thank you.

**Comment by breebee** [comment]
Sorry, it is in the is safe function in libraries/joomla/filter/input.php it is restricting my upload. If i remove the codes joomla breaks. How can i bypass this. Thank you

**Comment by breebee** [comment]
I have tried to remove all the array lists like 'php' 'zip' ect but it still gives me the error.

**Comment by roland-d** [comment]
This is not a support forum but to report issues on the Joomla code. To receive support please visit the http://forum.joomla.org page. Thank you.
