### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by dmdelane** [joomla/joomla-cms#7972]
Articles redirect to home page. When I click on a specific link the following error shows:

Fatal error: Call to a member function getPathway() on a non-object in /home/content/65/3461065/html/components/com_content/views/article/view.html.php on line 36

**Comment by rdeutz** [comment]
Could you please add more information about the version and environment you are using.

**Comment by dmdelane** [comment]
Joomla 2.5.27
K2 2.6.9

No new components or plugins, have a cron job running to clear cache. Its
been fine for weeks without any errors.

**Comment by dmdelane** [comment]
Let me know the other information needed

**Comment by alikon** [comment]
you are referring to an old version of Joomla
To receive support please visit the http://forum.joomla.org/viewforum.php?f=614 page.
