### ISSUE TITLE
Administrator cannot see Template files in Template Manager in Joomla 3.4.3

### ISSUE THREAD

**Issue by curlinggirl** [joomla/joomla-cms#7973]
#### Steps to reproduce the issue
Sign in as "Administrator", without "Superuser" rights into the back-end.
Go to "Extension Manager > Templates" and click on a Template to view and/or edit the CSS files

#### Expected result

Three tabs: "Editor", "Create Overrides", "Template Description" and a list of files, ie:

admin
css
css-compiled
custom
features
fields
fonts
html
images
etc.

#### Actual result

I get one tab: "Template Description" and no files.

#### System information (as much as possible)

The hosted system:
PHP 5.5.28
Joomla 3.4.3

I've been able to reproduce it on my local system (Mac):
PHP 5.6.3
MySQL 5.6.21
Joomla versions: 3.4.2, 3.4.3, 3.4.4

#### Additional comments

The "administrator" does not have a problem on version 3.4.1.
The "superuser" has no problem accessing the CSS files on any version.

I've cleaned cache, tried three different browsers, and enabled/disabled the "Preview Module Positions" with no difference.

Is this a new security measure? I most likely won't be permitted to be a superuser on the hosted system, but I need to be able to edit the CSS files.

Thank you,
Mary

**Comment by dgt41** [comment]
Few questions:
Does it work for Protostar and Beez? 
Which template are you using? 
Also are there any javascript errors logged in your browser’s console? Setting Error and report to Development are you getting any PHP errors?

**Comment by mbabker** [comment]
This was a purposeful change made with the 3.4.2.

**Comment by curlinggirl** [comment]
Thank you mbabker, I'll try to negotiate another solution.
