### ISSUE TITLE
Mobile enable offline login page

### ISSUE THREAD

**Issue by osignell** [joomla/joomla-cms#7977]
#### Steps to reproduce the issue

Put a site offline, open the page with a mobile phone or similar device

#### Expected result

Usable login screen is shown

#### Actual result

Zoomed out login screen is shown, requires user to manually zoom in before logging in.

#### Additional comments

Can be fixed by including:

&lt;meta name="viewport" content="width=device-width, initial-scale=1.0" /&gt;

in the <head> section of the /templates/system/offline.php file

**Comment by anibalsanchez** [comment]
In the same line, it would be great to add **autocorrect=off** and **autocapitalize=none** in username field.

In my sites, I have added this script in login view:

	$document->addScriptDeclaration('jQuery(document).ready(function(){
		jQuery("#username").attr("autocorrect", "off").attr("autocapitalize", "none");
	});');

**Comment by brianteeman** [comment]
Which mobile browser are you using? The default behaviour when  initial-scale
is not defined is for it to be 1.0

On 29 September 2015 at 09:49, Anibal Sanchez <notifications@github.com>
wrote:

> In the same line, it would be great to add *autocorrect=off* and
> *autocapitalize=none* in username field.
>
> In my sites, I have added this script in login view:
>
> $document->addScriptDeclaration('jQuery(document).ready(function(){
>     jQuery("#username").attr("autocorrect", "off").attr("autocapitalize", "none");
> });');
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7977#issuecomment-143976294>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by osignell** [comment]
The problem is visible on an iPhone 6 with both the built-in Safari browser and with Google Chrome. In both cases the login screen is shown correctly if initial-scale is explicitly set to 1.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7977">issues.joomla.org/joomla-cms/7977</a>.</sub>

**Comment by brianteeman** [comment]
Tested on iphone5 and android and cannot replicate.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7977">issues.joomla.org/joomla-cms/7977</a>.</sub>

**Comment by justinherrin** [comment]
I can see the issue on iPhone 5S using both Safari and Chrome apps.

**Comment by justinherrin** [comment]
I will work on a PR to help make the offline page a bit more mobile friendly. Stay tuned

**Comment by brianteeman** [comment]
Obviously there must be a non-standard default setting on that phone. No
harm in making the update though - thanks

On 29 September 2015 at 15:16, Justin Herrin <notifications@github.com>
wrote:

> I will work on a PR to help make the offline page a bit more mobile
> friendly. Stay tuned
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/7977#issuecomment-144074191>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by justinherrin** [comment]
PR #7981 has been created and is ready for testing

**Comment by brianteeman** [comment]
Sorry I completely misread the original report. I thought you were saying you had to zoom out in order to use it and not the opposite. Must not reply before I;ve had a coffee in future.

Closing as we have a PR
