### ISSUE TITLE
Newsfeed category image option confusing

### ISSUE THREAD

**Issue by rgblogs** [joomla/joomla-cms#7978]
#### Steps to reproduce the issue

Navigate to Joomla Administrator -> Components -> Newsfeeds -> Options -> Category

#### Expected result

"Show" should be on left and "Hide" should be on right.![screen shot 2015-09-29 at 04 56 34](http://issues.joomla.org/uploads/1/d95952764e6c0b1e7e4ed640cd22e429.png)

**Comment by alikon** [comment]
can you test #7983 ?

**Comment by zero-24** [comment]
Closing as we have a PR. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7978">issues.joomla.org/joomla-cms/7978</a>.</sub>
