### ISSUE TITLE
Plugin / Content - Page Break / Template CSS override

### ISSUE THREAD

**Issue by nblit** [joomla/joomla-cms#7982]
#### Steps to reproduce the issue
1. Create an article with two tables
2. Use Page Break to split the article:
2.1 Table1
2.2 Table2
3. In Extensions > Plugins enable Content-Page Break
3.1 Configure presentation style as pages
4. Browse to the article
4.1 Switch between pages

#### Expected result
Tables should retain their styling from template CSS

#### Actual result

Table2 does not retain styling from the Template CSS

#### System information (as much as possible)

PHP Built On	Windows NT RD000D3A7113A1 6.2 build 9200 (Windows Server 2012 Datacenter Edition) i586
Database Version	5.5.42-log
Database Collation	utf8_general_ci
PHP Version	5.5.26
Web Server	Microsoft-IIS/8.0
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.4.4 Stable [ Ember ] 8-September-2015 21:30 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36

#### Additional comments

Example of an article on our development site:

http://verifonehqhelp.azurewebsites.net/overview?showall=&start=1
-Note the style of table Supported devices
http://verifonehqhelp.azurewebsites.net/overview?showall=&start=2
-Note the style of table Value Proposition

**Comment by justinherrin** [comment]
Do both tables render properly if you do not use the Page Break option? If you had one single long article would both tables look correct?

**Comment by nblit** [comment]
Hi Justin,
When removing page breaks or disabling the plug in the tables render correctly.
Due to time constraints we have decided to force a specific CSS class so the table will look the same.

Thank you,
NB

**Comment by zero-24** [comment]
So we can close here? @nblit

**Comment by nblit** [comment]
Hmmmm, @zero-24 , are you implying that Joomla administrators should **not** use the Page Break core plugin? IMHO this needs to be investigated. a workaround is something temporary that should be resolved with a tested fix.

**Comment by mbabker** [comment]
Can you provide more details on how this can be tested?  Is there a difference in the tables in the content, is there some different page class(es) being applied?  Something that can give a lead as to what could be causing your particular issue would help others be able to recreate your issue.

**Comment by nblit** [comment]
This is the HTML code for table on page one:

<table border="1" style="width: 100%;">
<tbody>
<tr>
<td colspan="2"><strong>Verix</strong></td>
</tr>
<tr>
<td>Vx820 Duet</td>
<td>Dial, Ethernet</td>
</tr>
<tr>
<td>Vx820 PinPad</td>
<td>Dial, Ethernet</td>
</tr>
<tr>
<td>Vx680, Vx680 3G</td>
<td>3G, Dial, Ethernet</td>
</tr>
<tr>
<td>Vx805</td>
<td>Dial, Ethernet</td>
</tr>
<tr>
<td>Vx520, Vx520 3G</td>
<td>Dial, Ethernet</td>
</tr>
<tr>
<td>Vx675</td>
<td>3G, Dial, Ethernet (Not through BT base)</td>
</tr>
<tr>
<td>Vx690</td>
<td>3G, Dial, Ethernet (Not through BT base)</td>
</tr>
<tr>
<td>E355</td>
<td>WiFi</td>
</tr>
<tr>
<td colspan="2"><strong>V/OS</strong></td>
</tr>
<tr>
<td>MX915,MX925</td>
<td>Ethernet,Wifi</td>
</tr>
<tr>
<td>Ux300,Ux100</td>
<td>Ethernet</td>
</tr>
<tr>
<td colspan="2"><strong>RFS</strong></td>
</tr>
<tr>
<td>Mx760</td>
<td>Ethernet (Last supported release of agent 2.8.x)</td>
</tr>
<tr>
<td>MX850,MX860,MX870,MX880</td>
<td>Ethernet (Last supported release of agent 2.8.x)</td>
</tr>
</tbody>
</table>


This is the code for the table on page 2

<table border="1">
<tbody>
<tr>
<td><strong>Know Your Estate</strong></td>
<td>
<p>Know every device that is there within your estate. Understand the types of devices within the estate. Discover, monitor, manage, and report on all of the devices in your enterprise.</p>
</td>
</tr>
<tr>
<td><strong>Agile Estate</strong></td>
<td>Supports the latest payment requirements such as SmartCards, Electronic Wallets, and Promotional Campaigns.</td>
</tr>
<tr>
<td><strong>Security</strong></td>
<td>
<ul>
<li>- Maintain and enhance the security of your payment network.</li>
<li>- Introduce automated management with no compromise to PCI audit compliance. Schedule downloads automatically.</li>
<li>- Enable continuous monitoring of the location of all devices and their security status. VHQ provides the capability to identify devices that have not called the server or skipped a heartbeat or are tampered.</li>
</ul>
</td>
</tr>
<tr>
<td><strong>Verifone Hosted Service</strong></td>
<td>
<p>Available as a pay-as-you-go turnkey service hosted by Verifone or as licensed software that you can deploy in your data center.</p>
<p>- Enables the customers to get the latest and the greatest features or changes. <br>- Removes the hazzle to follow up on bugs that may not be opened by one customer.<br>- Easily accessible from anywhere in the world.<br>- Leverage Verifone’s full and powerful Infrastructure capabilities.</p>
</td>
</tr>
</tbody>
</table>


Hope this help

**Comment by mbabker** [comment]
I don't know if it is a core issue or a template issue.  But, on your page 2, the article contents are rendered after your template's `<div class="vhq-postcontent clearfix">` container.  On the other pages, the contents are placed inside a `<div class="vhq-article">` div within that postcontent container I mentioned before.  On that page specifically, the `vhq-article` div ends up being empty and the article contents are rendered after the `vhq-postcontent` container.  Without knowing the template or how the content is saved into the database (specifically where the `<hr id="system-readmore" />` lines are), there isn't much further I can go.

**Comment by alexonbalangue** [comment]
much better use a fusionlaize with default for article content "com_content" win large times than custom all as all components

**Comment by brianteeman** [comment]
After several months I am closing this as it appears to be specific to the template. If information is provided to replicate the issue with a core template it can always be reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7982">issues.joomla.org/joomla-cms/7982</a>.</sub>
