### ISSUE TITLE
impossible to create a new menu linked with a single article

### ISSUE THREAD

**Issue by elabrunye** [joomla/joomla-cms#7984]
![screen shot 2015-09-29 at 15 29 36](http://issues.joomla.org/uploads/1/6831d551670255e29a667db4ce4cc5fe.jpg)#### Steps to reproduce the issue
Open the menus page on the  administation site
Create a new menu, fill the title field
Select the type "menu linked with a single article"
Select the article to link with

#### Expected result
A list of article appears, and I can select my article

#### Actual result
The list is empty (see the enclosed snapshot), and when I close it, the page is blocked: impossible to clic on the cancel or save button.

#### System information (as much as possible)
Joomla 3.4.4

#### Additional comments
It was working well on Joomla 3.4.3

**Comment by elabrunye** [comment]
see also http://forum.joomla.fr/showthread.php?211259-Bug-de-joomla-3-4-4-sur-les-liens-de-menu-type-article
where other people got the same issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7984">issues.joomla.org/joomla-cms/7984</a>.</sub>

**Comment by dgt41** [comment]
Same issue as #7897, #7890 and #7880. It has been solved already with #7845.
Another solution is to update to the latest french language pack.

**Comment by elabrunye** [comment]
Thanks a lot.

**Comment by zero-24** [comment]
Closing as this is fixed with the lastest french language pack and globaly with the next Joomla Update :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7984">issues.joomla.org/joomla-cms/7984</a>.</sub>
