### ISSUE TITLE
Smart search category filter takes multiple categories with the same title as one category

### ISSUE THREAD

**Issue by oorzaak** [joomla/joomla-cms#7988]
#### Steps to reproduce the issue

In Content > Categories, create a category structure with titles like this:

Root
- Category 1
- - News items
- - Blog items
- Category 2
- - News items
- - Blog items

Create some dummy articles in all categories.
Activate smart search and make sure that the contents is indexed.

Then in Components > Smart Search > Filters, try to create a filter that limits smart search to this category:

Category 1 > Blog items

#### Expected result

As with all functionality in Joomla where categories are involved, I would expect to see that all categories are listed individually, even if they have the same title. This may be visualised in different ways but in the end each category has it's own id so the title doesn't really matter.

#### Actual result

When trying to create a search filter based on categories, with the category structure as shown above, the categories are listed as:

- Blog items
- Category 1
- News items
- Category 2

When checking "Blog items" in the filter definition, a search action returns articles from both Category 1 > Blog items and Category 2 > Blog items.

#### System information (as much as possible)

J.3.4.4

#### Additional comments

You might argue that categories should never have identical names. Yet I never before encountered a situation in Joomla where this was a problem. I think that a category structure like this one is perfectly normal from the users' point of view.

It seems to me that the smart search indexing system regards the category as just another chunk of contents, rather than taking into account the special nature of the categories system.

**Comment by oorzaak** [comment]
Sorry, the list markup of my dummy category structure is a bit messed up. Hope the idea is still clear.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7988">issues.joomla.org/joomla-cms/7988</a>.</sub>

**Comment by MartijnMaandag** [comment]
Yes this is a problem.
When you have a category strucrure: cars and motorbikes, with BMW in both, smartsearch makes no difference between BMW in the cars and the motorbikes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7988">issues.joomla.org/joomla-cms/7988</a>.</sub>

**Comment by chrisdavenport** [comment]
This is a known issue, but apart from ensuring that your category names are aways unique, I don't think there is a solution.  We could artificially add something to the category name in the index but that would also appear in the user interface.  There are also scenarios where the current behaviour is actually desired, which would make it difficult to achieve a fix without breaking backwards-compatibility.

I'm closing this issue at the present time.  If code (or a specific proposal for how to resolve the issue) is provided, it can always be re-examined.  Thanks for reporting the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7988">issues.joomla.org/joomla-cms/7988</a>.</sub>

**Comment by chrisdavenport** [comment]
Set to "closed" on behalf of @chrisdavenport by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7988">issues.joomla.org/joomla-cms/7988</a>

**Comment by panopt** [comment]
"It works badly, but at least we know it". 
Why did you close the bug?

**FREE IS NOT CHEAP !**
