### ISSUE TITLE
Category Blog layout issue when articles contain float left images and minimal text

### ISSUE THREAD

**Issue by robinne** [joomla/joomla-cms#7989]
#### Steps to reproduce the issue
Upload one or more images to joomla media directory, size approximately 100px x 100px.
Create an article category called "Test". Articles > Categories > New.
Create 2 or more articles, set their category to "Test".
For each article **Add a minimal amount of text to each article, only one or two lines of text**. 
For each article, under the Images and links tab, add an intro image approximately 100px x 100px.
Add a menu item to the Main Menu. Menu Item Type = Articles > Category Blog. Under choose a category, select your "Test" category.
Under the Blog Layout tab, set # of Leading Articles to 100.
Go to your website and use the new menu link to view your category blog page. The second article title does not clear the 1st article.

#### Expected result
Each Article should clear the prior article.

#### Actual result
The second article heading is directly next to article #1's image.
![screen shot 2015-09-30 at 10 59 57](http://issues.joomla.org/uploads/1/8bd9d228fe75ab260168409b9763831a.png)

#### System information (as much as possible)
Joomla 3.4.4. Tested on Chrome, IE 11

#### Additional comments
It looks like the class for each article, dynamically named "leading-0", "leading-1" etc needs css style: CLEAR:BOTH. Alternatively, look at the layout of menu item type "Featured Articles", this is similar to the blog layout, but does not exhibit the same issue.

**Comment by designbengel** [comment]
I don´t know if clear both fix this because you can set leading articles also into two colums and clear both will break that one. The clearfix needs to be inside the leading div i think? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7989">issues.joomla.org/joomla-cms/7989</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you for your contribution but it has been decided that this is not something that will be included in the core of Joomla!
