### ISSUE TITLE
Inconsistent Return Values in JFormRuleCaptcha

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#7991]
`JFormRule`, the base class for our form rule classes, documents the `test()` method as returning a boolean indicating whether a form field's value passes a rule.  `JFormRuleCaptcha` returns an `Exception` instance if `JCaptcha::checkAnswer()` returns a value that would be evaluated as false.  This form rule should be updated to follow the documented API.

**Comment by dgt41** [comment]
Is  this good enough:
```php
		// Test the value.
		if (!$captcha->checkAnswer($value))
		{
			return false;
		}
```
or we need to pass the error as well?

**Comment by mbabker** [comment]
The documented API is that a boolean is returned, so that should be it.  If we decide we want to change the API, that's another discussion (IMO it'd probably be more useful to throw Exceptions with a real error stack versus return boolean false here, but I don't know if that's something that can be done within the scope of the B/C rules).
