### ISSUE TITLE
How to use JText::sprintf('STRING', $VAR) in the JS file for Joomla.JText._('STRING')

### ISSUE THREAD

**Issue by durr04** [joomla/joomla-cms#7996]
Hello Guys,

I am using joomla language constant in the js file by using. Joomla.JText._('STRING');

But I want to use JText::sprintf('STRING', $VAR) in the JS file. Its not working for me.

**Comment by brianteeman** [comment]
This is the issue tracker for bugs and new features in the core of Joomla. For support and development questions please use either the forum (http://forum.joomla.org) or the development mailing list (https://groups.google.com/forum/#!aboutgroup/joomla-dev-general)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7996">issues.joomla.org/joomla-cms/7996</a>.</sub>
