### ISSUE TITLE
Global Configuration. Option "Cache Handler:File" gets lost

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#7997]
- Go to System > Global Configuration.
- Tabulator: System.
- Set Cache: ON
- Set Cache Handler: Cache_Lite.
- Save.
- Set Cache: OFF
- Save again.

- Try to set *Set Cache Handler: File*.

- No option "File" in select box.

- Only way to get it back is to create deleted folder
/administrator/cache/
via FTP.

**Comment by zero-24** [comment]
Closing as we have a PR @bertmert can you test here: #8004 Thanks.
