### ISSUE TITLE
Site Offline button in installation has suffered modifications

### ISSUE THREAD

**Issue by javigomez** [joomla/joomla-cms#7999]
#### Steps to reproduce the issue
install joomla from the current Staging in Github

Go to the first installation screen: Main Configuration

You will notice that the  Site Offline button has a new look that is not right:

![screen shot 2015-10-02 at 02 44 55](http://issues.joomla.org/uploads/1/111b8b4cc40fe7100f79dd63d023ef7d.png)

Before it was like:

![screen shot 2015-10-02 at 02 45 59](http://issues.joomla.org/uploads/1/40f0486e369f9ea5f400c51bf891fea3.png)

This change happened in the last 24hours, I noticed because is breaking the automated tests (https://github.com/joomla-projects/joomla-browser/blob/develop/src/JoomlaBrowser.php#L152)

#### Expected result
we would need this button to have back the default value as "no", and being able to change the values

#### Actual result
"Site Offline" do not work. If you click you can't change the value anymore, is broken:

![screen shot 2015-10-02 at 02 51 06](http://issues.joomla.org/uploads/1/04f89cf8bf22ca387a1caf4a644c9728.png)

#### System information (as much as possible)
This happens in Firefox, Chrome, Safari and Opera in Mac and Ubuntu

**Comment by infograf768** [comment]
We lost the class="btn-group btn-group-yesno"

**Comment by zero-24** [comment]
@okonomiyaki3000 can you have a look here? Looks like that happens because of this (now merged) PR: https://github.com/joomla/joomla-cms/pull/4022?

**Comment by zero-24** [comment]
Restoring this file (/libraries/joomla/form/fields/radio.php) from: https://raw.githubusercontent.com/joomla/joomla-cms/3.4.4/libraries/joomla/form/fields/radio.php gets the install working as bevor.

**Comment by okonomiyaki3000** [comment]
I don't know why the layout was putting radios inside of a list.. Was it like that years ago when I first made this pr or did I add it because I'm insane? We may never know. Unless we try to find out. But let's not care about that now. This fix should fix it.

**Comment by okonomiyaki3000** [comment]
If not, I'll have a look on monday.

**Comment by zero-24** [comment]
Closing as we have a PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7999">issues.joomla.org/joomla-cms/7999</a>.</sub>
