### ISSUE TITLE
Hi Can someone help to get back in the my Admin section on my website.

### ISSUE THREAD

**Issue by TREDWEAR** [joomla/joomla-cms#8002]
#### I seem to be locked out of my Admin section of my website. Is there a user & password that can be used for such situations.
Richard

**Comment by brianteeman** [comment]
Please see https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F

If you have any problems please use the forum (http://forum.joomla.org)

**Comment by TREDWEAR** [comment]
Hi Brian.  Thank you for getting back to me so quickly.  If i send you the ePanel or the FTP login what would it cost me so i can get back in to my admin site.  and can we setup an alternate User & Pass  so if this happens a again I can get back in to the site and reset.

Richard

TredWear Canada Ltd
richard@tredwearletters.ca<mailto:richard@tredwearletters.ca>
Phone: (902) 650-0152
Cell: (902) 956-1138
9 Whidden Road, Brookfield, NS
B0N 1C0



On Oct 2, 2015, at 3:06 PM, Brian Teeman <notifications@github.com<mailto:notifications@github.com>> wrote:


Please see https://docs.joomla.org/How_do_you_recover_or_reset_your_admin_password%3F

If you have any problems please use the forum (http://forum.joomla.org<http://forum.joomla.org/>)
