### ISSUE TITLE
Link to a restricted URL from outside of the browser did't work

### ISSUE THREAD

**Issue by dirk-graetz** [joomla/joomla-cms#8010]
#### Steps to reproduce the issue
1) Set the access level of a menu or an article to "registered"
2) Login and navigate to the URL (for example "domain.tld/login/profile")
3) Copy the entire URL into Word, Excel, PowerPoint or something like this
4) Click on the link 

#### Expected result
If still logged in: Open the linked page in an new browser tab.

If logged out (because of logging out or closing the browser in the meantime): Login-Page and after login redirect to the "registered" url.

#### Actual result
Logout-Page with button "log out"

#### System information (as much as possible)
Joomla 3.4.4; Clean install; Tested on various systems (local and on live sites).

#### Additional comments
???

**Comment by n9iels** [comment]
I can not reproduce the issue.

When I made a registered profile page (localhost/your-profile), and open this link in anther bower (so I am nog logged in) I see the login page. After login I am redirected to the profile page.
When I am logged in, and open this link I can open the profile page without any problems.

**Comment by dirk-graetz** [comment]
Hi Niels,
it's not a problem if you copy the link into the browser, it's a problem if
you ad the link to a MS Word-document and then klick on this link!
Please try the attached file with the link to your example page.

2015-10-08 21:39 GMT+02:00 Niels van der Veer <notifications@github.com>:

**Comment by n9iels** [comment]
Okay, strange...

Did the following:
1. Copy and past the link localhost/your-profile in a word document
2. ctrl + click on the link (this will open the link in your browswer)
3. logged in, and the page opens correctly
4. close the browser tab (so I am still logged in)
5. ctrl + click on the link in the word document
6. Getting a "logged out button" on the url localhost/login

So, issue confirmed. But no idea what cause it...

**Comment by peterpeter** [comment]
Hello
I can confirm that behaviour. The answer lies in the servers access.log:
Word does some kind of ping/linkprecheck, with a inbuild (and thus not logged in) Browser/HTTP-Class, and handles the standard-browser call based on the/these ping results. 

Below are the access.log entries of one of these 'word-link-click'
(stipped out some stuff)

"HEAD ../index.php?option=com_cpcalendar&view=entry&lang=de HTTP/1.1" 303 - "-" "Microsoft Office Word 2013"
"GET ../index.php?option=com_users&view=login&return=L2pvb21sY...&lang=de HTTP/1.1" 200 31021 "-" "Microsoft Office Word 2013"
"GET ../index.php?option=com_cpcalendar&view=entry&lang=de HTTP/1.1" 303 2841 "-" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; .... ms-office)"
"GET ../index.php?option=com_users&view=login&return=L2pvb21sYS9r.... HTTP/1.1" 200 31147 "-" "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.1; WOW64; Trident/7.0; ..... ms-office)"
"GET ../index.php?option=com_users&view=login&return=L2pvb21sYS9r...&lang=de HTTP/1.1" 200 33904 "-" "Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8010">issues.joomla.org/joomla-cms/8010</a>.</sub>

**Comment by peterpeter** [comment]
...and my systems standard browser was the last call, FireFox<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8010">issues.joomla.org/joomla-cms/8010</a>.</sub>

**Comment by dirk-graetz** [comment]
So no chance??<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8010">issues.joomla.org/joomla-cms/8010</a>.</sub>

**Comment by peterpeter** [comment]
Word does a kind of precheck of that link (as guest to a restricted area), and 'modifiy' the original link in word with the answer from the system (correct redirect to login). It's a behavior from Word. And in my opinion it's not possible to solve that on the joomla-side.

So yes, I would say, no chance, and suggest to close this issue.

**Comment by zero-24** [comment]
Closing as expected behavior Thanks @peterpeter and @dirk-graetz  :smile:
