### ISSUE TITLE
breadcrumbs ignores text separator menu items

### ISSUE THREAD

**Issue by lcdservices** [joomla/joomla-cms#8011]
To reproduce:
- create a menu item of type text separator
- create a menu item of type article (or something else) and set the text separator as parent
- navigate to the article menu item (child)
- observe the breadcrumbs

The breadcrumbs will be constructed like:
Home >  > Child

The text separator text is ignored, but space for it is left in the breadcrumbs. I believe the text separator menu item should be displayed, but not linkable. It's not uncommon to use those for first level drop down menus where you don't want the menu item itself to be a link.

**Comment by MAT978** [comment]
Could you check if the PR #7839 solve the problem?
Thanks

**Comment by rgblogs** [comment]
This has been now solved. I am also waiting for 3.4.5 version.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8011">issues.joomla.org/joomla-cms/8011</a>.</sub>

**Comment by infograf768** [comment]
For those that can't wait for 3.4.5 release, the correction is simple, add `echo` before `$item->name` 
```
diff --git a/modules/mod_breadcrumbs/tmpl/default.php b/modules/mod_breadcrumbs/tmpl/default.php
index b383a6f..cfb5514 100644
--- a/modules/mod_breadcrumbs/tmpl/default.php
+++ b/modules/mod_breadcrumbs/tmpl/default.php
@@ -55,7 +55,7 @@
 					</a>
 				<?php else : ?>
 					<span itemprop="name">
-						<?php $item->name; ?>
+						<?php echo $item->name; ?>
 					</span>
 				<?php endif; ?>
 ```

**Comment by zero24** [comment]
Set to "closed" on behalf of @zero24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8011">issues.joomla.org/joomla-cms/8011</a>

**Comment by blizam** [comment]
This code was not added to 3.4.5?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8011">issues.joomla.org/joomla-cms/8011</a>.</sub>

**Comment by mbabker** [comment]
RE: 3.4.5 release

> This release only contains the security fixes; no other changes have been made compared to the Joomla 3.4.4 release.

https://www.joomla.org/announcements/release-news/5634-joomla-3-4-5-released.html
