### ISSUE TITLE
Possible missing structured data for SearchResultsPage

### ISSUE THREAD

**Issue by Brujo-mlq** [joomla/joomla-cms#8028]
#### SEO Code Improvement for SearchResultsPage
Add code to SearchResultsPage for Structured Data Output on Frontend for the SearchResultsPage

https://schema.org/SearchResultsPage

**Comment by chrisdavenport** [comment]
Hi @Brujo-mlq you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8028">issues.joomla.org/joomla-cms/8028</a>.</sub>

**Comment by chrisdavenport** [comment]
Set to "closed" on behalf of @chrisdavenport by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8028">issues.joomla.org/joomla-cms/8028</a>
