### ISSUE TITLE
Title / words "Main Menu" not hidden

### ISSUE THREAD

**Issue by silviosams** [joomla/joomla-cms#8029]
#### Steps to reproduce the issue

After auto update from Joomla_3.4.3-Stable-Full_Package to 3.4.4 the title of Menu not hidden more.

Independent of disable all options, not hidden the words "Main Menu" in the site.

#### Expected result

Hidden the words "Main Menu"

#### Actual result

Not hidden

#### System information (as much as possible)

Version base Joomla_3.4.3-Stable-Full_Package

After auto update 3.4.4

#### Additional comments

For "correct" this issue I comment the source code:

templates/beez3/html/modules.php - line 22

from:
```php
<?php if ($module->showtitle) { ?> <h<?php echo $headerLevel; ?>><?php echo $module->title; ?></h<?php echo $headerLevel; ?>>
```

to:
```php
<!-- <?php if ($module->showtitle) { ?> <h<?php echo $headerLevel; ?>><?php echo $module->title; ?></h<?php echo $headerLevel; ?>> -->
```

**Comment by zero-24** [comment]
hmm this file was not changed since 30 Dec 2014 maybe the problem is not there..

**Comment by silviosams** [comment]
I think that the configured parameter cannot reaches to page modules.php.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8029">issues.joomla.org/joomla-cms/8029</a>.</sub>

**Comment by silviosams** [comment]
I I found another bug in the menu: the bold in the option selected not change, stay always in the first option.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8029">issues.joomla.org/joomla-cms/8029</a>.</sub>

**Comment by designbengel** [comment]
Maybe you made a corehack instead of an override on modules.php ?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8029">issues.joomla.org/joomla-cms/8029</a>.</sub>

**Comment by n9iels** [comment]
I tested the following situation on the latest staging version:
1. Change default template to beez3
2. Made a menu modal
3. Set the parameter "Show title" to hide

The title of the menu module is hidden now, so I can't reproduce the issue.
Also, I can't reproduce the bug with the active bold item.

**Comment by silviosams** [comment]
I dont understand because the problem occurs, i think that the selected option (variable) do not reaches the page.

I recreates the menu of the zero and clone the module menu, the bold error is solved, but the title still occurs.

Now i try install the version 3.4.4 of zero.

Thanks alot for you attention,

**Comment by alexonbalangue** [comment]
create fonction not show module title begin
 function moChrom_nones {
//not Write code $module->title used that
$echo $module->content;//add config what you want take charge default configuration backend advanced
}

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8029">issues.joomla.org/joomla-cms/8029</a>.</sub>
