### ISSUE TITLE
Invisible and active menu items instead of / or additionally to hidden menues

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-cms#8032]
To get an url without a visible menuitem you have to create a hidden menu. But maybe that url should match anyway to a given structure of the site. 

Cool solution would be to have menuitems published but same time invisible.

![screen shot 2015-10-07 at 14 49 28](http://issues.joomla.org/uploads/1/bc156f93735a2db69946d6277354c5c9.png)
![screen shot 2015-10-07 at 14 49 28](http://issues.joomla.org/uploads/1/6197dca575ab25247272134255c24e1e.png)

Any thoughts on this?

Thanks!

**Comment by sovainfo** [comment]
Consider "hidden menu" bad jargon from the past. That was when Joomla created a module when creating a menu. That doesn't happen anymore, menu's are hidden, (not shown in the frontend) unless you create a module that publishes it properly ( positions and context (menu items)).

Also menu items can be made invisible by setting access to a level not given to anybody.

**Comment by designbengel** [comment]
yes you are right. But when i want just a menuitem to be hidden i have to put it in a separate menu without a module. But what if i want to have the url accessable to everyone, put it in a existent structure but not showing the item in the frontend? 

For example a link to an application form which should be only accessable from a content text link but as well should have a nice url.

**Comment by sovainfo** [comment]
Already answered: Also menu items can be made invisible by setting access to a level not given to anybody.

**Comment by brianteeman** [comment]
There is an extension you can use for this from @betweenbrain
http://extensions.joomla.org/extensions/extension/structure-a-navigation/menu-systems/menu-wrench

On 7 October 2015 at 23:14, sovainfo <notifications@github.com> wrote:

> Already answered: Also menu items can be made invisible by setting access
> to a level not given to anybody.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8032#issuecomment-146347923>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by designbengel** [comment]
Thanks @brian i'll take a look at that. 

@sovainfo - if access is set to nobody - i hope nobody will have access. if not thats might be a bug? for the feature i meant the access should be allowed but invisible  :-)

**Comment by mbabker** [comment]
The quirk with that nobody group is you might inadvertently make it unmanageable too.  That's the only thing that I'd be concerned with going that route.

**Comment by sovainfo** [comment]
No, the access level only applies to visibility, the visibility of the menu item! Nothing to do with what it is pointing to!
Obviously, you could restrict it to Super users, to keep it manageable.

**Comment by mbabker** [comment]
I forget if it was on the forum or a thread here but there was a recent post where someone pointed out that if you assigned items to an access level that the Administrator user group wasn't a member of, even though by ACL they could edit the item, it didn't show up where they expected it to.  That's where my comment was based from.

**Comment by designbengel** [comment]
@sovainfo i don´t know if we are talking about the same things. I just gave a meuitem the accesslevel "registered" and when i point to the url the item had a login screen appears. like expected. wouldn´t make any sense other way for me.

The module @brianteeman recommended does exactly what i´m talking about (and more) - so maybe it´s even not a feature which is missing in the menuitem-manager but in the mod_menu.

**Comment by sovainfo** [comment]
Apart from the fact that doesn't make sense to me, it is the way Joomla works, when using an url you are not authorized to use. Using the url the menu item is pointing to gets you to the data provided you have access to it. When you don't like that url, move the menu item to a menu not presented to the frontend.
Suggest to wait for the new routing options, advice against this change to the menu system.

**Comment by designbengel** [comment]
@sovainfo sorry, from your answer i see that you didn´t understand what i tried to say - maybe because of my english, never mind. At least Brian understood me ;-)

**Comment by Fedik** [comment]
it is not so bad suggestion, sometimes I also miss for this feature :smile: 
@sovainfo it is have a sense, if need to get a nice URL, similar as in example from @designbengel

**Comment by brianteeman** [comment]
You can also achieve this by applying a class to the menu item to make it invisible. I regularly do that for the Home menu <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8032">issues.joomla.org/joomla-cms/8032</a>.</sub>

**Comment by skelgaard** [comment]
you can do a link class like menu-hidden and then just do a 
header ul.nav.menu li a.menu-hidden {
    display: none;
}
or the likings if depending on your template structure.

but hidden menu would be just as easy a way to do it instead of menu's not assigned to any modules

i have not tried the menu wrench module, and do not know if this is better or not than the simple css hide way.

if you want it totaly removed from the html, you could do a simple jQuerue('ul li.menu-hidden').parrent().remove(); which should remove it (this is untested)

the advantages of this, is that google should be able to index them, unless you have set the noindex parameter for the items, as they are in the html code, when google loads the page, which they are not in the hidden menu function.

**Comment by brianteeman** [comment]
Closing this as PR #8814 has been merged which does this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8032">issues.joomla.org/joomla-cms/8032</a>.</sub>
