### ISSUE TITLE
Restore icon in trash is misleading

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-cms#8033]
If i want to trash an item forever instead of all - i often click on the trash icon - although i already know it will restore the item. Because it´s like a magnet :-)

I think an undo icon would be much more suitable und understandable for the action which is behind it.

![screen shot 2015-10-07 at 14 58 30](http://issues.joomla.org/uploads/1/6c25d9b7d650b18a04f0a5f12592bef1.png)![screen shot 2015-10-07 at 14 58 33](http://issues.joomla.org/uploads/1/bf37967d385e8dbe9ef2523a685e14d2.png)

Thanks for feedback on this :)

**Comment by mbabker** [comment]
IMO if we went that route all of the icons would need to be changed.  Right now the icons represent the current status and clicking it performs an action opposite of that status (enabled -> disabled, trashed -> enabled, etc.).  To me it would seem a bit confusing and inconsistent if in that scenario the icon represented the action clicking that button performed.

There's definitely an argument for the change, but I'd personally suggest to look at it in a way that is consistent across the board.

**Comment by designbengel** [comment]
If that's the way it is, the trash icon for trashing items must be the opposite?

But yes i understand your point. Like featured/unfeatured published/unpublished. 

Maybe the request still has a chance because its really something that is not very userfriedly imho.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8033">issues.joomla.org/joomla-cms/8033</a>.</sub>

**Comment by mbabker** [comment]
Agree totally.  The main issue I think is that we're trying to do too much with that button/icon combination (it displays a status and acts as a toggle to change to another status) without being too clear about that.  Once you start clicking and get familiar with it, then the current workflow starts to make sense (but still isn't the most friendly thing at times).  Maybe that status column is best left to only showing the status without it being an actionable button/icon and the action links that you see attached to that button in places like the Article Manager (side note, why isn't that present in Category or Menu Manager lists?) gets turned into something more visible as a way to perform quick actions on an item (hate playing the "well WordPress does it this way" card, but the quick actions when you hover over a row on desktop are one of the few things in their admin UI I can actually figure out and understand without needing documentation).

**Comment by MAT978** [comment]
Asked about it few months ago annnnnnnd..... gone :stuck_out_tongue: 
Hope this time things can go forward!

**Comment by brianteeman** [comment]
Perhaps the solution is to have an image-icon to display the status and an button-icon to display the action?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8033">issues.joomla.org/joomla-cms/8033</a>.</sub>

**Comment by brianteeman** [comment]
Closing with other tickets so we just have one for this topic #9359<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8033">issues.joomla.org/joomla-cms/8033</a>.</sub>
