### ISSUE TITLE
Google got 503 response yet everyone else got 200 response

### ISSUE THREAD

**Issue by spignataro** [joomla/joomla-cms#8035]
So this is a tough one to explain. Please note I have not found the why in the code this is being caused but I can tell you that this caused a major SEO blip for our site for approx. 1 month. Here is the story of what happened and what we saw:

Approx. end of October we updated the latest release of Joomla! (I believe it was 3.3.3 or 3.4). Our site rendered properly to us and our users. So we saw nothing wrong in our tests. A few weeks later our traffic dropped from our organic traffic. How could this be? Our site was rapidly being taken out of Google with no stopping in sight. I went through and ran SEO tests, reviewed the results and all I got was google was getting a 503 error from our site. Yet I could not replicate it for the life of me and nothing was being reported to the logs other than the access from Google which was not helpful. 

It seemed that there was a change in Joomla! - but I couldn't figure it out. So after doing some research I found that Google was only rendering the top portion of our header on some of our pages and not the rest of the site. It was hitting a JS error and bailing on our site. Which didn't make any sense to me at all because Google indexes a ton of broken sites - yet it was unindexing us pretty quick.

The error was that tooltip was not defined. After some digging I found that it was related to the option Mouse-over Edit Icons for option in the global configurations. 

I changed it from Modules to None and Google was able to successfully start crawling the site again. It will take a few months to get back to where we where. But this is concerning that this option can be causing such an issue. On some components it wasn't rendering all of the JS files (most likely because those components turn them off - but why is tooltip even being rendered for this option when it is a ADMIN login only option? Is this a template issue or is this a Joomla! issue? I can't seem to see where we in our theme include tooltip so I am assuming that this is a Joomla! related issue and prolly should be properly put in the admin only login vs being available improperly to the public.

Well I hope that helps. It didn't work on Joomla! content category pages, Chronoforms, WordPress for Joomla!, Akeeba Subs (all of which is our primary portion of our site).

http://screencast.com/t/IE3olqQLJ5K  -> this is what I had to turn off to fix.

**Comment by brianteeman** [comment]
I really cant see how it could be anything in the core or by now we would have had thousands of reports of sites dropping of google<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8035">issues.joomla.org/joomla-cms/8035</a>.</sub>

**Comment by spignataro** [comment]
Not sure what to tell you other than I had to turn this off on a few of our sites and google was reporting 503 errors in Google Webmasters. 

The only thing that I can think of it is that it is related to Cache being turned on and that the system was incorrectly caching results for logged in users.

**Comment by brianteeman** [comment]
Which cache options? Maybe that will help to track it down although I still
cant see it

On 28 January 2016 at 13:54, spignataro <notifications@github.com> wrote:

> Not sure what to tell you other than I had to turn this off on a few of
> our sites and google was reporting 503 errors in Google Webmasters.
>
> The only thing that I can think of it is that it is related to Cache being
> turned on and that the system was incorrectly caching results for logged in
> users.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8035#issuecomment-176194806>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
Joomla doesn't generate a 503 except when the site is offline.

As for the module edit tooltip, it shouldn't show at all for Google since it isn't logged in.
But what changed recently last year is that Google now takes care of JS files, which means you should allow access to those files in your robots.txt file. Especially the /media folder needs to be allowed for crawling (compare with the robots.txt.dist).
Other than that check your .htaccess file if there is anything suspicious in there. You may also have been hacked.

Anyway this isn't a core issue for sure and thus I'm closing it.
If you need further assistance, feel free to sue the forums (http://forum.joomla.org)
