### ISSUE TITLE
Administrator user group incorrect Permissions

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#8037]
#### Steps to reproduce the issue
Create a user and and assign to the Administrator group
Open another browser (or log out of admin)
Try and log in admin with the new user
Error message
Warning
Username and password do not match or you do not have an account yet.

Login with super user navigate to global config and save
New user can now log in to admin.

#### Expected result
New user in Administrator Group should be able to log in admin without global config needing to be saved.

#### Actual result

Users in Administrator group are unable to login to admin before global config is saved

#### System information (as much as possible)
PHP Built On 	Windows NT MY-COMPUTER 6.2 build 9200 (Windows 8 Home Premium Edition) i586
Database Version 	5.6.26
Database Collation 	utf8_general_ci
PHP Version 	5.5.28
Web Server 	Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.5.28
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.4.5 Development [ Ember ] 8-September-2015 21:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0

#### Additional comments
"core.login.offline":[],
Is added to the Rules Field of the Root Asset Record of the Assets Table

Spotted in http://forum.joomla.org/viewtopic.php?f=708&t=895647

**Comment by n9iels** [comment]
I can not reproduce this issue, I did the following:
1. Create a new user, with username: admin2
2. Assign this user to the group "Administrator" (and no other group)
3. Logged out of the administrator page, and logged in with admin2

Results: logged in successful with administrator rights.

**Comment by Webdongle** [comment]
I have tried with 3 of my test installs and all failed until global config was saved.  Tested with a fresh install of staging and failed until global config was saved.  Installed a fresh Joomla 3.4.4 and no problem.

**Comment by k4lch** [comment]
Can confirm this on fresh install on localhost

**Comment by brianteeman** [comment]
Thank you for creating this but it would appear that this has been resolved elsewhere in the code base. If this is not correct then this can be re-opened

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8037">issues.joomla.org/joomla-cms/8037</a>.</sub>
