### ISSUE TITLE
Updating Problem

### ISSUE THREAD

**Issue by cortix** [joomla/joomla-cms#8043]
Hi,

When I try to update Joomla, I got this error ? I tried to install new stable update from folder tmp ....Can you help me ? Can you give some advice to solve it ? I cannot access to administrator panel and also website :( 

Warning: require(/home/berkaaxo/public_html/vet-arena.com/libraries/vendor/composer/autoload_namespaces.php): failed to open stream: No such file or directory in /home/berkaaxo/public_html/vet-arena.com/libraries/vendor/composer/autoload_real.php on line 26

Fatal error: require(): Failed opening required '/home/berkaaxo/public_html/vet-arena.com/libraries/vendor/composer/autoload_namespaces.php' (include_path='.:/usr/local/lib/php') in /home/berkaaxo/public_html/vet-arena.com/libraries/vendor/composer/autoload_real.php on line 26

**Comment by slibbe** [comment]
From what to what are you trying to update?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8043">issues.joomla.org/joomla-cms/8043</a>.</sub>

**Comment by BezouwenR** [comment]
Please, more information needed. From where to where is the update. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8043">issues.joomla.org/joomla-cms/8043</a>.</sub>

**Comment by cortix** [comment]
I had Joomla 3.3.6 version but As I understand I have installed wrong version. (Joomla_3.4.x_to_3.4.4-Stable-Patch_Package)... now I can not fix the problem... I am getting that error..

**Comment by hans2103** [comment]
Please download J3.4.4 full package and upload it to your website. 
(merge, not replace)
If you continue to have an error, please ask on the Joomla forum, not the Joomla issue tracker. 
https://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8043">issues.joomla.org/joomla-cms/8043</a>.</sub>
