### ISSUE TITLE
Missing text for menu-headings in breadcrumbs

### ISSUE THREAD

**Issue by hanusm** [joomla/joomla-cms#8063]
#### Steps to reproduce the issue
There is nothing to do to reproduce, missing echo in source.

line 58 in modules/mod_breadcrumbs/tmpl/default.php

should be <?php echo $item->name; ?> instead of <?php $item->name; ?> 

#### Expected result
some text > menu-heading > page-title

#### Actual result
some text > > page-title

#### System information (as much as possible)
Joomla 3.4.4

**Comment by n9iels** [comment]
This issue is already fixed in #7839, thanks for reporting!

**Comment by zero-24** [comment]
Thanks. Closing as allready fixed in code base for the next release
