### ISSUE TITLE
Allowing 'Create' in a Category enables Create for other categories

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#8069]
#### Steps to reproduce the issue
Create A user group with registered as parent
Select that group in 'Special' view/access level
In Global config permissions Allow Administrator Login and leave everything else Inherited
In Content >>> Article/Category/Featured Article >>> Options ... set 'Access Administration Interface' to 'Allowed'
Create a new category and set the permissions in that category for the new user group Allowed for Create, Delete, Edit, Edit State and Edit Own 
Create a new user and put the user in the new user group
Login Admin as the new user

#### Expected result
The new user should be able to Create, Delete, Edit, Edit State and Edit Own Articles in only the new category.  **They should not be able to Create more categories or Delete, Edit, Edit State and Edit Own for existing categories.**

#### Actual result
**The new user can create new categories because the Create button appears in the Category tab as well as the Article tab.**

#### Additional comments

Spotted as a result of this thread http://forum.joomla.org/viewtopic.php?f=719&t=895579

**Comment by n9iels** [comment]
Thanks for reporting this possible issue!

If I follow your steps to reproduce the issue and login with the created user, I don't have the opportunity to access any component or create items. The back-end looks like this:
![knipsel](https://cloud.githubusercontent.com/assets/2659866/10424436/7705ef08-70cf-11e5-9d2e-2ec5072b7d90.PNG)

Did you forget to describe a few steps? Or are there other permission settings changed?

**Comment by Webdongle** [comment]
My bad
Added "In Content >>> Article/Category/Featured Article >>> Options ... set 'Access Administration Interface' to 'Allowed'" to the instructions

In addition to the user being able to create Categories (which they should not be able to do)
The user can create Articles and set to the specific Category(which is expected behaviour) but is unable to delete any Article they create (which they should be able to do)

Before allowing Create, Delete, Edit, Edit State and Edit Own in a category
![permissions 02](https://cloud.githubusercontent.com/assets/1115202/10426826/b8b9781e-70db-11e5-9e2a-a9f6c62774bb.JPG)
![permissions 01](https://cloud.githubusercontent.com/assets/1115202/10426798/809623d8-70db-11e5-968d-59a948b9ed9f.JPG)

After adding Create, Delete, Edit, Edit State and Edit Own 
As you can see there is a Create button for Articles but not Trash can icon
![permissions 03](https://cloud.githubusercontent.com/assets/1115202/10426850/1782ee3e-70dc-11e5-8455-770bcc4854af.JPG)

But in Categories there is also a Create icon.  Clicking it allows the creation of Categories with no parent.  If Create should be allowed in the specific Category then the Trash can should also appear.  But surely the Create, Delete, Edit, Edit State and Edit Own should apply to only Articles for the Category
![permissions 04](https://cloud.githubusercontent.com/assets/1115202/10426935/e13b1c42-70dc-11e5-9d7b-2a82ec922974.JPG)

**Comment by n9iels** [comment]
Thanks for the clear instructions.
After following your steps I noticed the following:
- The user can create categories on the "no parent" level but can't edit them after creating.(they should not able to create categories on that level)
- There is no trash icon visible, but the user is allowed to delete his own articles. Not sure if this is done by a usability reason

**Comment by n9iels** [comment]
I made a PR for the problem that the user was able to create level 0 categories.

Can someone else look at the problem with the trash icon? I don't know exactly if this is a real problem, or done with a reason. Also not sure where or how I can fix that.

**Comment by Webdongle** [comment]
@n9iels 

Thanks quick work ...  PR # 8083 prevents the user creating Articles outside of the hierarchy of the Category they have Create Permissions for.  Have tested and added Test to that patch.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8069">issues.joomla.org/joomla-cms/8069</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for creating this but it would appear that this has been resolved elsewhere in the code base. If this is not correct then this can be re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8069">issues.joomla.org/joomla-cms/8069</a>.</sub>
