### ISSUE TITLE
Impossible to set cookie value to array

### ISSUE THREAD

**Issue by klas** [joomla/joomla-cms#8073]
Setter $value parameter in JInputCookie is declared as mixed, so it should accept array values, the same as other setters. But currently JInputCookie set method fails do do this is faulty as it tries to do just setcookie($name, $value) - which does not work for arrays. Cookies with array values need to be set for each array value separately with array keys in name - see example 3 here http://php.net/manual/en/function.setcookie.php

**Comment by klas** [comment]
## Steps to reproduce the issue
Run this code 
JFactory::getApplication()->input->cookie->set("arraytest", array("asssoc1"=>"assoc1value","asssoc2"=>"assoc2value" ),time() + 365 * 86400);

## Expected result
Cookies arraytest[asssoc1] with value "assoc1value", and arraytest[asssoc2] with value "assoc2value" beeing set

## Actual result
Warning: setcookie() expects parameter 2 to be string, array given in libraries\joomla\input\cookie.php on line 85
No cookie is set

**Comment by zero-24** [comment]
Closing as we have a PR. I'm going to copy your instructions. Thanks. https://github.com/joomla/joomla-cms/issues/8081
