### ISSUE TITLE
French language breaks jQuery

### ISSUE THREAD

**Issue by dkanchev** [joomla/joomla-cms#8090]
#### Steps to reproduce the issue

Install fr-FR language. Change the admin to use it. Go to:

Menu Item Type > Select > Articles > Single Article

Then select an article and some of the tabs will disappear. It seems the page doesn't load completely (for example: buttons details, options, Link Type, ...).

#### Expected result

The page should load without issues and all buttons should be loaded.

#### Actual result

When the fr-FR language is used the following jQuery doesn't work as expected:

jQuery(document).ready(function($) {
   $('#modalArticlejform_request_id').on('show', function() {
       $('body').addClass('modal-open');
       var modalBody = $(this).find('.modal-body');
       modalBody.find('iframe').remove();
       modalBody.prepend('<iframe class="iframe" src="index.php?option=com_content&amp;view=articles&amp;layout=modal&amp;tmpl=component&amp;function=jSelectArticle_jform_request_id&amp;04c98ebad81c83d2040b2c7882b7dfe9=1" name="Sélectionner ou changer l'article" height="300px" width="800px"></iframe>');
   }).on('hide', function () {
       $('body').removeClass('modal-open');
   });

The issue is caused by the "l'article" string and the single quote in it. It breaks the JS code wit this error in Firebug:

SyntaxError: missing ) after argument list

#### System information (as much as possible)

CentOS 6
PHP 5.6
MySQL 5.5

#### Additional comments

N/A

**Comment by dkanchev** [comment]
The issue is present on the joomla.com platform and several people have reported it already. It will be good if we have a fix soon :smile: Thanks guys!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8090">issues.joomla.org/joomla-cms/8090</a>.</sub>

**Comment by zero-24** [comment]
This is a known and already fixed issue. A fix will come with 3.4.5 or if you look at: #7845 Thanks

**Comment by infograf768** [comment]
The released French pack  3.4.4.2 has corrected the apostrophy (single quote) issue a long time ago...
Please update your language in Manage=>Update->Find Updates

**Comment by dkanchev** [comment]
Thank you for the info guys. Will update the package and will let you know if issues occur again :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8090">issues.joomla.org/joomla-cms/8090</a>.</sub>

**Comment by dkanchev** [comment]
Simply installing the latest version of the language pack is not enough. The following patches/commits should be applied as well:

https://github.com/joomla/joomla-cms/pull/7845/commits

The commits are still not part of the Joomla! latest stable version and thus simply updating the language pack does not resolve the issue I mentioned. The patches however resolve the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8090">issues.joomla.org/joomla-cms/8090</a>.</sub>

**Comment by infograf768** [comment]
@dkanchev 
Concerning French (and other languages lke Catalan) this is untrue as we took off the single quote in the fr-FR lang pack:

Evidently, the patch is needed, but one will NOT get the error with our modified lang packs in 3.4.4
We modified
`COM_CONTENT_CHANGE_ARTICLE="Sélectionner ou changer l'article."`
to
`COM_CONTENT_CHANGE_ARTICLE="Sélectionner ou changer cet article."`

**Comment by dkanchev** [comment]
@infograf768 I checked the latest package taken from the official translations page:

http://community.joomla.org/translations/joomla-3-translations.html
http://joomlacode.org/gf/project/jtranslation3_x/frs/?action=FrsReleaseBrowse&frs_package_id=6415
http://joomlacode.org/gf/download/frsrelease/20042/162673/fr-FR_joomla_lang_full_3.4.4v2.zip

It seems that the string is still the same in it:

Daniels-MacBook-Pro:Downloads Kanchev$ grep -R --color COM_CONTENT_CHANGE_ARTICLE fr-FR*
fr-FR.com_content.ini:COM_CONTENT_CHANGE_ARTICLE="Sélectionner ou changer cet article"
fr-FR.com_content.ini:COM_CONTENT_CHANGE_ARTICLE_BUTTON="Sélectionner / Changer"
fr-FR.plg_user_profile.ini:COM_CONTENT_CHANGE_ARTICLE="Sélectionner ou changer l'article."
fr-FR.plg_user_profile.ini:COM_CONTENT_CHANGE_ARTICLE_BUTTON="Sélectionner/Changer"

Either the links to the correct package should be updated or I did something wrong on my end!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8090">issues.joomla.org/joomla-cms/8090</a>.</sub>

**Comment by infograf768** [comment]
The string concerned in profile.ini is no more used in 3.4.4
In 3.4.4, content.ini is loaded each time we have a button to select/change an article.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/models/fields/modal/article.php
