### ISSUE TITLE
Link Preview in administration not working correctly with HTTPS

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#8109]
#### Steps to reproduce the issue
In "Global Configuration" set the parameter "Force SSL" -> "None" or "Administrator Only".
Use the control panel of Joomla 3 with HTTPS
Click on the  link "Preview" at the top right in the Joomla 3.

#### Expected result
Opens the frontend site in HTTP.

#### Actual result
Opens the frontend site in HTTPS and not in HTTP.

**Comment by AlexRed** [comment]
@test
Confirm the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8109">issues.joomla.org/joomla-cms/8109</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #9712<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8109">issues.joomla.org/joomla-cms/8109</a>.</sub>
