### ISSUE TITLE
Updating extension doesn't update the existing update servers path

### ISSUE THREAD

**Issue by webchun** [joomla/joomla-cms#8113]
#### Steps to reproduce the issue
1. Change the update server path for your extension
2. Install the update
3. From your administrator page go to Extensions > Manage > Update Sites
4. There is now a new update site item for the existing extension, with a different path

#### Expected result

Isn't it should be updating the existing path instead of creating a new one?

#### Actual result

There is now a new update site item for the existing extension, with a different path

#### System information (as much as possible)

Joomla 3.4.4

**Comment by vdespa** [comment]
As far as I remember I have noticed this weird behavior a while back. 

Do you have a sample basic extension with update servers that can be used for replicating / fixing / testing this issue? 

Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8113">issues.joomla.org/joomla-cms/8113</a>.</sub>

**Comment by webchun** [comment]
I have created and uploaded two dummy modules in here https://www.dropbox.com/s/rj98f0llle9a1wf/extract_first.zip?dl=0 , same modules with different updateserver path so you can try yourself. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8113">issues.joomla.org/joomla-cms/8113</a>.</sub>

**Comment by mbabker** [comment]
PlgExtensionJoomla handles the update site registration (why is this in a plugin!?) and uses the location as a faux primary key of sorts to decide whether to insert a new record.  IMO the whole management of this needs to go back to the drawing board, this should really be integrated into JInstaller and not coded in a way that gives the impression a URL can only be registered once.

**Comment by horus68** [comment]
related: [New Feature] Delete or rebuild update sites in update sites manager · Issue #8512 - https://github.com/joomla/joomla-cms/issues/8512

**Comment by brianteeman** [comment]
I am going to close this as a known issue at this time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8113">issues.joomla.org/joomla-cms/8113</a>.</sub>
