### ISSUE TITLE
Japanese menu collapse not working

### ISSUE THREAD

**Issue by anatak74** [joomla/joomla-cms#8115]
#### Steps to reproduce the issue
create an English menu with submenus
create a Japanese menu with submenus.

#### Expected result
English menu collapses and expands.
Japanese menu collapses and expands.

#### Actual result
Japanese menu is always shown fully expanded.

#### System information (as much as possible)
System Information
Setting 	Value
 
PHP Built On 	Linux oban 3.2.61-grsec-modsign #1 SMP Tue Aug 12 09:58:26 UTC 2014 x86_64
Database Version 	5.6.25-log
Database Collation 	utf8_general_ci
PHP Version 	5.6.10
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.4.4 Stable [ Ember ] 8-September-2015 21:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (X11; Linux i686; rv:41.0) Gecko/20100101 Firefox/41.0 

#### Additional comments
possibly because of Japanese double byte encoding.
screenshots on joomla forum here
http://forum.joomla.org/viewtopic.php?f=706&t=895658

website here
English version (click on English or French to see collapsed submenu)
http://www.test.anatak.com/index.php/
Japanese version (English and French submenu always visible)
http://www.test.anatak.com/index.php/jp/

**Comment by infograf768** [comment]
I confirm the issue here.

**Comment by brianteeman** [comment]
Hi you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and you have not then I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined. It probably needs to be a user experienced with the Japanese language who is able to do this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8115">issues.joomla.org/joomla-cms/8115</a>.</sub>
