### ISSUE TITLE
Why URLs of CSS / JS files do not have a version/hash variable appended to their URLs to bypass browser cache after upgrade

### ISSUE THREAD

**Issue by ggppdk** [joomla/joomla-cms#8118]
When you upgrade Joomla and some JS / CSS file have been updated
- any users browsing the website, backend of frontend, will get the old versions of the files from the browser cache.

Is there a reason that we do not append to the URLs:
?v=somehashvalue

There have been several invalid reports here, because of browser cache serving older JS / CSS files after Joomla is upgraded

**Comment by mbabker** [comment]
1) We should not use the CMS version number as that string ever.

2) We have at least 2 APIs that are supposed to be doing this that depend
on different things being set up correctly (and ironically I'm pretty sure
neither are used right).

**Comment by ggppdk** [comment]
I see about Joomla CMS version number

Then we could append a hash value that is calculated on 
- on Joomla version 
- and on or a per site string  (e.g site domain)

?v=hashValue

**Comment by mbabker** [comment]
Like I said, we already have two APIs which is supposed to support this:

[JDocument::addScriptVersion()](https://github.com/joomla/joomla-cms/blob/3.4.4/libraries/joomla/document/document.php#L487) and [JDocument::addStyleSheetVersion()](https://github.com/joomla/joomla-cms/blob/3.4.4/libraries/joomla/document/document.php#L562) within the JDocument API

[JHtml::includeRelativeFiles()](https://github.com/joomla/joomla-cms/blob/3.4.4/libraries/cms/html/html.php#L296) within the JHtml API (called via `JHtml::script()`, `JHtml::stylesheet()`, and `JHtml::image()`)

If neither of those APIs are working, fix them.  Don't add another way to do it.  Please.  We have too many duplicated APIs like this already.

**Comment by ggppdk** [comment]
sorry, i did not mean that they do not work,

i was asking why they are not used by Joomla CMS by default

**Comment by Devportobello** [comment]
Actually ```JHtml::script()``` ```JHtml::script()``` ```JHtml::image()``` dont allow to use query string in the ```$file``` arg :/

**Comment by zero-24** [comment]
I guess @mbabker means this: https://github.com/joomla/joomla-cms/blob/3.4.4/libraries/cms/html/html.php#L362-L496 with a MD5SUM file not adding a query string ;)

**Comment by mbabker** [comment]
Exactly that.  If there is a file named `MD5SUM` in the folder where the resource being called via the JHtml helpers resides at, the contents of that file (which should be a calculated hash based on the contents of the directory and changed anytime something in that directory changes) will be appended as the query string.

As for why they are not used by default, why does every media file require a query string by default?

**Comment by demis-palma** [comment]
> why does every media file require a query string by default?

Actually @ggppdk answered to this question in advance:

> When you upgrade Joomla and some JS / CSS file have been updated
> any users [...] will get the old versions of the files from the browser cache.

In my opinion, the query string should contain by default the timestamp of the resource.
For the cache purpose, it is equivalent to an hash, but it is faster than calculating an hash.

**Comment by piotr-cz** [comment]
If anyone is looking on information how to use the `MDSUM` file:
put such file in the assets folder and inside a md5 checksum of all assets contents.

**Comment by ggppdk** [comment]
About default behaviour

Using a string based on file's modification or creation time
- will not give out any info, 
- will cost almost nothing in time, since file will be read anyway by the server, 
- while it will avoid stale CSS / JS after upgrades that this topic is about

and also all proxies since - 5 years versions support query strings in the CSS / JS resources URLs

**Comment by brianteeman** [comment]
The code to do this was created a long time ago #1618 if i am correct

On 18 December 2015 at 20:20, Georgios Papadakis <notifications@github.com>
wrote:

> About default behaviour
>
> Using a string based on file's modification or creation time
>
>    - will not give out any info,
>    - will cost almost nothing in time, since file will be read anyway by
>    the server,
>    - while it will avoid stale CSS / JS after upgrades that this topic is
>    about
>
> and also all proxies since - 5 years versions support query strings in the
> CSS / JS resources URLs
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8118#issuecomment-165889613>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Checking 3.5beta 2 I see that both template.css and template.js have a version type parameter<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8118">issues.joomla.org/joomla-cms/8118</a>.</sub>
