### ISSUE TITLE
Contact page does not load proper com_user.profile XML

### ISSUE THREAD

**Issue by Hackwar** [joomla/joomla-cms#8120]
In components/com_contact/models/contact.php line 434 a JForm object is created and then send through the form plugin events. If a plugin properly reacts to the context given to the JForm object, namely 'com_users.profile', and tries to edit the XML via removeField() for example, the page crashes with a 500 error, because the JForm object never loaded any XML.

I'm wondering what this code is actually any good for, since it will definitely filter out any data from the user, except for the stuff that is added in in addition to the default data. Considering the amount of additional code that is being executed for this feature, I strongly suggest to drop it. I guess, no one ever used this code and it has been in the system like this for at least 4 years.

**Comment by brianteeman** [comment]
@hackwar as no one has replied to you in a long time on this I guess no one has a clue what it does either. We can either close this issue and move along or you can submit a PR to address the issue you ave identified. If no response is received then we will close this in a few weeks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8120">issues.joomla.org/joomla-cms/8120</a>.</sub>

**Comment by Hackwar** [comment]
I will provide a PR.

**Comment by Hackwar** [comment]
and please keep this open to remind me that I write one. :wink:

**Comment by brianteeman** [comment]
@Hackwar are you going to write the PR - its been almost a year - or shall i just close this.

**Comment by Hackwar** [comment]
Thank you for reminding me. I will look into this in the next 2 weeks. For future-me: If you did not provide a PR for this until June 4th 2017, this will be closed.

**Comment by franz-wohlkoenig** [comment]
Entry on my Calendar for 5th June.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8120">issues.joomla.org/tracker/joomla-cms/8120</a>.</sub>

**Comment by Hackwar** [comment]
See #16461 Closing this one. 😄

**Comment by brianteeman** [comment]
Thanks @Hackwar
