### ISSUE TITLE
tooltip "Full Article Image" set incorrect

### ISSUE THREAD

**Issue by tecpromotion** [joomla/joomla-cms#8121]
#### Steps to reproduce the issue
- Create new content item
- Go to tab "Images and links"
- add a new image in field "Full Article Image"
- No tooltip is showing/set

- add a new image in filed "Intro Image"
- Tooltip in "Intro Image" is showing/set
- AND tooltip in "Full Article Image" is showing/set with the value of "Intro Image"

New content item
- add a new image in field "Intro Image"
- Tooltip in "Intro Image" is showing/set
- AND tooltip in "Full Article Image" is showing/set without image selected

#### Expected result

- tooltip should show the right content to the selected image

#### Actual result

- if "Intro Image" is set the value is always the "Intro Image" tooltip

#### System information (as much as possible)

- Joomla 3.4.4

#### Additional comments

images attached

Bug reported by Reinhard Kampf Joomla User Group Nuremberg meetup 10/2015![screen shot 2015-10-21 at 13 32 59](http://issues.joomla.org/uploads/1/ed95e3831b6898e2e5cd6bb9015cae73.png)![screen shot 2015-10-21 at 13 33 00](http://issues.joomla.org/uploads/1/8de4350c410f29977106a81d0c4fd182.png)

**Comment by dgt41** [comment]
This has already been resolved with: https://github.com/joomla/joomla-cms/pull/8100

**Comment by dgt41** [comment]
Set to "closed" on behalf of @dgt41 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8121">issues.joomla.org/joomla-cms/8121</a>

**Comment by dgt41** [comment]
Closing here as it’s already fixed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8121">issues.joomla.org/joomla-cms/8121</a>.</sub>
