### ISSUE TITLE
Problem updating 3.3.1 to 3.3.6 / ERROR: INVALID AJAX DATA

### ISSUE THREAD

**Issue by localjapan** [joomla/joomla-cms#8122]
I have a problem with migrating Joomla 3.3.1 to 3.3.6.
Every time I try to update, a pop-up says "Error:Invalid Ajax Data" comes up and there is a broken form below to report the problem in HTML but it doesn't work. What can I do?

**Comment by vdespa** [comment]
Thank you for your bug report.

There is very little to begin with. Try to open the browser console and to look for XHR requests. Please provide the URLs and request data and the response data. 

This information is needed in order to replicate the problem you are experiencing. 

Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8122">issues.joomla.org/joomla-cms/8122</a>.</sub>

**Comment by localjapan** [comment]
Hi Mr.vdespa,

Thank you very much for your response.
I wasn't really sure which information you'd need, so I just copied the information I could find on the page. Please let me know if there's any other information you'd need to solve this issue.
Again, thank you very much for your help!!
↓
↓


URL: http://www.localjapan.com/administrator/index.php?option=com_joomlaupdate&task=update.install

Response: 
<div style="font-size:20px; text-align:center; line-height:1.5; padding:15px 0;">
    OOP! ERROR CODE 5500<br>
    This website page is display in error, Please use below form to report this error. Thank you. </div>
<form name="contact" method="POST" onSubmit="return validateForm()" action="error_report.php">
		<table width="456" border="0" align="center" cellpadding="0" cellspacing="5" bgcolor="#f3f3f3">
        <tr>
      
      <td colspan=3 valign="top" align="center">
	
	  <div style="font-size:16px;">Error report form:</div>
      
	  </td>
   </tr>
   <tr>
      <td height="28" valign="top">E-mail:</td>
      <td><input id="email" name="email" type="text"></td>
      <td><input style="font-size:18px; padding:5px 10px; cursor:pointer;" type="submit" value="Submit" name="submit"></td>
   </tr>
 
  
</table>
</form>

General:
Remote Address:50.87.248.56:80
Request URL:http://www.localjapan.com/administrator/components/com_joomlaupdate/restore.php
Request Method:POST
Status Code:200 OK

Response Headers:
view source
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:490
Content-Type:text/html
Date:Mon, 26 Oct 2015 22:02:08 GMT
Keep-Alive:timeout=10, max=497
Server:Apache
Vary:Accept-Encoding


Request Headers:
 (13)
Form Data
view source
view decoded
json:0qIuVgYGBgaaB44CzMeeXy8WqWB09sc%3D
