### ISSUE TITLE
Problem with protection Joomla 3.4.4

### ISSUE THREAD

**Issue by poviljaj** [joomla/joomla-cms#8123]
Hello, I use Joomla 3.4.4. The files with malware code appear on regular basis on the site. The virus code is executed by php eval . Could you please advise how to find out all such files and delete them? How to find the hole in protection of the site?

**Comment by n9iels** [comment]
GitHub is only for reporting bug in Joomla!. Please use the official forum, http://forum.joomla.org/, for support questions
