### ISSUE TITLE
Missing Translation in all languages

### ISSUE THREAD

**Issue by Worti2** [joomla/joomla-cms#8137]
<h4>Steps to reproduce the issue:</h4>
<p>Create a menue item with a list of all contact categories.</p>
<h4>Expected result:</h4>
<p>You will exptect a translation in the tooltip box, when you hover with the mouse over the numbers after the category name.</p>
<h4>Actual result:</h4>
<p>In the tooltip box there is only this string COM_CONTACT_NUM_ITEMS, and not the translation.</p>
<h4>System information (as much as possible):</h4>
<p>Joomla! 3.4.5 testenviroment without any extention.</p>
<h4>Additional comments:</h4>
<p>You will find the string here: components/com_contact/views/categories/tmpl/default_items.php</p>

**Comment by zero-24** [comment]
see: https://github.com/joomla/joomla-cms/pull/8139/files Thanks @Worti2 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8137">issues.joomla.org/joomla-cms/8137</a>.</sub>
