### ISSUE TITLE
Featured Items ordering is not set by drag and drop like articles and categories

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-cms#8138]
#### Steps to reproduce the issue
In Backend > Content > Articles the ordering is set by drag and drop
In /administrator/index.php?option=com_content&view=featured it´s still set like in older versions. And: the save button is an "order-icon" instead of a save icon.![screen shot 2015-10-24 at 08 05 34](http://issues.joomla.org/uploads/1/b3acef52cfe92dffb0588db35518dbe9.png)

**Comment by htmgarcia** [comment]
+1

**Comment by nishadi** [comment]
I have fixed this problem. Can you please guide as to how to send the PR as I am new here.

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8138">issues.joomla.org/joomla-cms/8138</a>.</sub>

**Comment by nishadi** [comment]
This PR includes the patch for this issue.
(https://github.com/joomla/joomla-cms/pull/9564 "https://github.com/joomla/joomla-cms/pull/9564")

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8138">issues.joomla.org/joomla-cms/8138</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR #9564 for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8138">issues.joomla.org/joomla-cms/8138</a>.</sub>
