### ISSUE TITLE
Smart Search: component + module on same page, auto suggest in module does not work

### ISSUE THREAD

**Issue by seagul30** [joomla/joomla-cms#8142]
to reproduce problem:
1. Add menu item "Smart Search", active plugin "Smart Search", index website with "Smart Search"
2. Add module "Smart Search" for all pages
3. Type a search string on a site without the component --> auto suggest works
4. Type a search string on a site with the component --> auto suggest in component works, auto suggest in modules does not work.

If there are two "Smart Search" modules on one page (without component) it is the same problem, only one module works.

Our suggestion: problem with duplicate id in html

**Comment by sudo-web** [comment]
I tried to reproduce this Issue but for some reasons it did‘t work

**Comment by vphat28** [comment]
can you check if there is the error message in browser console. This maybe  a javascript conflict with 3rd plugin

**Comment by brianteeman** [comment]
I am closing this at this time as it has not been reproduced and there has been no response to the request for further information. It can always be re-opened if updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8142">issues.joomla.org/joomla-cms/8142</a>.</sub>
