### ISSUE TITLE
Not a bug but a suggestion for MODAL Image selection

### ISSUE THREAD

**Issue by jayblaq** [joomla/joomla-cms#8177]
#### Steps to reproduce the issue
The current use of bootstrap wells etc in a modal for the top and the bottom can be confusing to users since the upload and navigations are hidden without scrolling etc.   I would like to suggest making the top thumbnail list or grid well fixed and the bottom upload a photo fixed as well.  Here is my suggestion.

#### Expected result
.browser {
height: 325px;
width: 100%;
overflow: auto;
position: relative;
margin: 40px 0 40px 0;
padding: 40px 0;
}

.well {
margin: 0px;
position: fixed;
top: 0;
width: 94%;
z-index: 2;
}

#### Additional comments

**Comment by dgt41** [comment]
There is another proposed way for this: using tabs. You can check it with #5871
