### ISSUE TITLE
on space in empty tags metadesc & metakey

### ISSUE THREAD

**Issue by lomart** [joomla/joomla-cms#8182]
I have just realized that the component com_tags systematically adds space in metadesc & metakey fields of the table #__tags
This causes meta site are substituted for those of the tag, since they are never empty.
This bug occurs on a Joomla 3.4.5, but not 3.4.1

#### Steps to reproduce the issue
Save a tag with empty metadesc. Reopen, i have a space

#### Expected result
empty

#### System information (as much as possible)

joomla 3.4.5

#### Additional comments

none

**Comment by deenison** [comment]
Confirmed on Joomla 3.5.0-beta, but not sure if it's really a bug.

I might be wrong on this, but it seems that Joomla forces the space character just to make sure that the related HTML meta-tags are created having no possible-misleading content for SEO, meaning that the overall description of the site and/or its keywords, may be very different of what those could be for a particular tag's own page.

Would be great to have someone with more experience having a status on this matter tho.

Best regards.

**Comment by bertmert** [comment]
Known and fixed already for 3.5.1.
https://github.com/joomla/joomla-cms/pull/8783
@deenison 
Please read comments in PR and related issue.

**Comment by brianteeman** [comment]
Closing as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8182">issues.joomla.org/joomla-cms/8182</a>.</sub>
