### ISSUE TITLE
Switch update server to HTTPS

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#8186]
Our update server now supports SSL connections.  The CMS should be updated to query `update.joomla.org` via HTTPS.

**Comment by zero-24** [comment]
see: https://github.com/joomla/joomla-cms/issues/8196

**Comment by mbabker** [comment]
Relevant - http://blog.ioactive.com/2016/01/drupal-insecure-update-process.html?m=1

**Comment by mbabker** [comment]
Closing due to the commentary in the now closed pull request and the reluctance as a whole to enforce HTTPS connections on `joomla.org` properties.

**Comment by wilsonge** [comment]
I think we now have everything ready to use https as of 3.6

**Comment by andrepereiradasilva** [comment]
IMO one thing missing. the joomlacode.org translations:

Example for pt-PT:
- URL 1 (https): https://update.joomla.org/language/translationlist_3.xml
- URL 2 (https): https://update.joomla.org/language/details3/pt-PT_details.xml
- URL 3 (http): http://joomlacode.org/gf/download/frsrelease/20263/163106/pt-PT_joomla_lang_full_3.5.1v1.zip

Also all language packs should use https in their manifest update server (not just en-GB) right?.

**Comment by mbabker** [comment]
The project doesn't have a SSL certificate for `joomlacode.org`, `opensourcematters.org`, or the `joom.la` vanity URL.

**Comment by andrepereiradasilva** [comment]
yes, you already told me i forgot.

but still
> Also all language packs should use https in their manifest update server (not just en-GB) right?.

**Comment by mbabker** [comment]
In a perfect world yes they would specify HTTPS in their manifests.  This also assumes they specify one (I don't know how they're structured so I don't know if they actually specify it or rely on the core's way of fetching the language packages to decide this).

**Comment by wilsonge** [comment]
joomlacode is dead soon. Me and Roland are getting together for 3 days at the end of June to finish the download site off i think (we organised it in Manchester)

**Comment by andrepereiradasilva** [comment]
> In a perfect world yes

*just a perfect world* :wink:

> they would specify HTTPS in their manifests. This also assumes they specify one (I don't know how they're structured so I don't know if they actually specify it or rely on the core's way of fetching the language packages to decide this).

They all specify the same update server URL `//update.joomla.org/language/translationlist_3.xml`, but pkg_en-GB specifies with HTTPS and all the others (currently) with HTTP.

**Comment by Bakual** [comment]
Those are done by the translators. All we could do is to remind them to change it to https. But honestly, JC is dead as George mentioned and we're better off to just change it when the new server is alive :smile:

**Comment by andrepereiradasilva** [comment]
> Those are done by the translators. All we could do is to remind them to change it to https. But honestly, JC is dead as George mentioned and we're better off to just change it when the new server is alive :smile:

sure just alerting to that, in case you guys didn't notice that.
