### ISSUE TITLE
Recaptcha does not work when used in javascript onload event

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#8188]
### Steps to reproduce the issue

The recaptcha do not work if you move the javascript execution to after the javascript onload event.

Configure recaptcha plugin with version 2.0 and put it working as default in system configuration.

Use any joomla plugin that allows you to move the javascript execution to after the page onload event. Load any page with the recaptcha form and see the recaptcha image does not load.

### Potencial solution

Use HTML5 "data-*" attributes when loading recaptcha.

Instead of:
```<script src="https://www.google.com/recaptcha/api.js?hl=__LANG__&amp;render=explicit" type="text/javascript">```
[...]
```<div id="jform_captcha" class=" required">```
[...]
```jQuery(document).ready(function($) {$(window).load(function() {grecaptcha.render("jform_captcha", {sitekey: "__RECAPTCHASITEKEY__", theme: "__RECAPTCHATHEME__"});});})```

Use:
```<script src="https://www.google.com/recaptcha/api.js?hl=__LANG__&amp;render=onload" type="text/javascript">```
[...]
```<div id="jform_captcha" class="g-recaptcha required" data-sitekey="__RECAPTCHASITEKEY__" data-theme="__RECAPTCHATHEME__"></div>```

Code in: https://github.com/joomla/joomla-cms/blob/staging/plugins/captcha/recaptcha/recaptcha.php (functions onInit and onDisplay)

See also https://developers.google.com/recaptcha/docs/display#config

### System information (as much as possible)

Joomla 3.4.5

**Comment by zero-24** [comment]
Cab you send you changes as pull request against the staging branch?

**Comment by andrepereiradasilva** [comment]
ok done it.
See https://github.com/joomla/joomla-cms/pull/8191

**Comment by zero-24** [comment]
Closing as we have a Pull. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8188">issues.joomla.org/joomla-cms/8188</a>.</sub>
