### ISSUE TITLE
Custom position for modules not possible when few template positions

### ISSUE THREAD

**Issue by Mushr0000m** [joomla/joomla-cms#8202]
#### Steps to reproduce the issue
1- Activate the "Content - Load Module" plugin
2- Disable all frontend template except one
3- Go inside a module and try to type a custom position in the "position" field

#### Expected result
Normally you should be able to type anything here to search for a position or create one. In this case to be able to load a module inside an article by creating a custom position like explained in the doc here https://docs.joomla.org/How_do_you_put_a_module_inside_an_article%3F.

#### Actual result
The search field in the dropdown doesn't appear because the dropdown is too short. In my case I have a custom template with 4 positions, and all other templates are disabled. So the dropdown doesn't show the search field. It's indeed impossible to create a position because there is no text field to write it.

#### System information (as much as possible)
Joomla 3.4.5

#### Additional comments
To resolve this the position field must always show the search field even if there is 0 positions in the dropdown. It's a simple option on the JS when creating dropdown from select input.

**Comment by brianteeman** [comment]
If I remember correctly this is a known issue when you have 4 or less
modules

On 29 October 2015 at 14:11, Mushr0000m <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> 1- Activate the "Content - Load Module" plugin
> 2- Disable all frontend template except one
> 3- Go inside a module and try to type a custom position in the "position"
> field
> Expected result
>
> Normally you should be able to type anything here to search for a position
> or create one. In this case to be able to load a module inside an article
> by creating a custom position like explained in the doc here
> https://docs.joomla.org/How_do_you_put_a_module_inside_an_article%3F.
> Actual result
>
> The search field in the dropdown doesn't appear because the dropdown is
> too short. In my case I have a custom template with 4 positions, and all
> other templates are disabled. So the dropdown doesn't show the search
> field. It's indeed impossible to create a position because there is no text
> field to write it.
> System information (as much as possible)
>
> Joomla 3.4.5
> Additional comments
>
> To resolve this the position field must always show the search field even
> if there is 0 positions in the dropdown. It's a simple option on the JS
> when creating dropdown from select input.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8202>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by bertmert** [comment]
I posted a workaround here
https://github.com/joomla/joomla-cms/issues/6892#issuecomment-99681019

**Comment by Bakual** [comment]
@bertmert Can you do a PR for that? Looks like an appropriate fix to me.

**Comment by Mushr0000m** [comment]
@bertmert : Thanks. :+1: for a PR

**Comment by bertmert** [comment]
See PR: https://github.com/joomla/joomla-cms/pull/8433
