### ISSUE TITLE
Joomla 3.4.4/3.4.5 isis admin template save buttons don't work

### ISSUE THREAD

**Issue by fula5** [joomla/joomla-cms#8204]
I am new to Joomla. I installed a Rockettheme " Ambrosia " with joomla template brings already included . Suddenly , without major changes, the buttons SAVE, SAVE AND EXIT, SAVE AND NEW, stop walking.

I read https://github.com/joomla/joomla-cms/issues/6319    and replace this file, unchanged.!

Forum on Rockettheme simply say maybe a corrupt Joomla. I upgraded to 3.4.5 and joomla remains unchanged.

Firefox console says to select any panel:
ReferenceError: Class is not defined
TypeError: Joomla.JMultiSelect is not a function

To try to press buttons Save:
ReferenceError: Browser is not defined
TypeError: document.formvalidator is undefined

Joomla 3.4.5
Php 5.4.45

I appreciate any help .

**Comment by vdespa** [comment]
I am sorry to hear you are having troubles. Unfortunately this is an issue tracker, not the support forum. There are other platforms where you can get more help.

Also the Rockettheme "Ambrosia" does not seem to be free for everybody to install. 

If you still think this is a bug in Joomla, please reply and improve replication instructions. 

Thanks for understanding.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8204">issues.joomla.org/joomla-cms/8204</a>.</sub>

**Comment by vdespa** [comment]
Set to "closed" on behalf of @vdespa by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8204">issues.joomla.org/joomla-cms/8204</a>

**Comment by fula5** [comment]
Everything I've read points to a bug in Joomla. This Article writing is misplaced? I wrote mine because I saw that before.  https://github.com/joomla/joomla-cms/issues/6319.
No one else has reported a problem like this?

Very Thanks.

**Comment by fula5** [comment]
References:
http://forum.joomla.org/viewtopic.php?t=875171
http://forum.joomla.org/viewtopic.php?f=706&t=874670

I see and apply all of this and still not working.

**Comment by vdespa** [comment]
I am not saying that it is not a bug. Put the information you offered is not possible for me to replicate the bug. 

Please try to offer replication instructions on a clean Joomla installation with a free template. 

Thanks for understanding.
