### ISSUE TITLE
Breadcrumbs links with extra spaces

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#8205]
### Steps to reproduce the issue

1- Use a fresh joomla install
Tip: Go to https://demo.joomla.org/ and launch a "Quick Joomla! Test Drive"
2- On chrome go to one article and mouseover the breadcumb link

### Expected result

Mouseover link only in text.

### Actual result

Link in text and in a space before/after the link.

### System information (as much as possible)

Joomla 3.4.5

### Additional comments

The problem is mod_breadcumbs template https://github.com/joomla/joomla-cms/blob/staging/modules/mod_breadcrumbs/tmpl/default.php#L51.

If you use tabs or spaces inside the HTML anchor tag (a) it will (at least chrome) render extra spaces space with link.

### Solution

Do not use tabs or spaces inside the anchor tag (a).
If agreed i can make a PR to solve this.

**Comment by n9iels** [comment]
I see a space after the a element of the breadcrumb, so issue confirmed.

If you have a solution, feel free to make a PR so we can test it :). Please note this issue number as well in the PR

**Comment by andrepereiradasilva** [comment]
Ok. Done.

**Comment by zero-24** [comment]
Closing as we have a PR.
