### ISSUE TITLE
PHP7 Incompatibility with in JHtmlSelect

### ISSUE THREAD

**Issue by Hanmac** [joomla/joomla-cms#8211]
there are still some access with `$group->$options['group.label']`
in `JHtmlSelect#groupedlist` in the `if (is_object($group))` section

```php
if (is_object($group))
			{
				// Sub-list is in a property of an object
				$subList = $group->$options['group.items'];

				if (isset($group->$options['group.label']))
				{
					$label = $group->$options['group.label'];
					$noGroup = false;
				}

				if (isset($options['group.id']) && isset($group->$options['group.id']))
				{
					$id = $group->$options['group.id'];
					$noGroup = false;
				}
			}
```

and in one line with:

`$key2 = is_object($val) ? $val->$options['option.key'] : $val;`

**Comment by zero-24** [comment]
Do you have code to fix that issue? If yes you can send a pull reqwuest against the staging branch :smile: 

If you need help you can have a look here: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by zero-24** [comment]
Closing as we have a Pull that is merged. Thanks :smile:
