### ISSUE TITLE
Multilanguage broken in 3.5.0-dev

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#8218]
Test:
Install a brand new 3.5.0-dev Joomla as a multilang site with a few languages.
Do not modify anything.

In frontend, switch between languages by using the language switcher flags.
The mainmenu module for the language desired will not display although the display is in the language concerned.
One needs to click a second time on the flag for the language to get the module to show.
Example in en-GB, one will get:
![screen shot 2015-10-31 at 07 33 47](https://cloud.githubusercontent.com/assets/869724/10862299/3b4071fe-7fa3-11e5-93a1-f948ada667f8.png)

and after the second click
![screen shot 2015-10-31 at 07 36 30](https://cloud.githubusercontent.com/assets/869724/10862294/2a7caa5e-7fa3-11e5-8f0c-4fd420b0b2f4.png)

I originally found the issue on my legacy multilanguage site updated to 3.5.0-dev

**Comment by Bakual** [comment]
It's related to #8012. Reverting that commit fixes it.
Also it only affects menus, not the module itself.

**Comment by wilsonge** [comment]
Ok so how about now instead of reverting we figure out exactly why it breaks things :P

**Comment by roland-d** [comment]
I have just done that :) Preparing the PR :P

**Comment by roland-d** [comment]
The PR to test is available at #8226 

Thanks for testing.

**Comment by Bakual** [comment]
Closing as we have a PR
