### ISSUE TITLE
3.5.0-dev Creating new article => Notice: Undefined variable: url

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#8220]
When creating a new article in back-end, we get this Notice (in logs)
PHP Notice:  Undefined variable: url in ROOT/layouts/joomla/html/formbehavior/ajaxchosen.php on line 41

**Comment by infograf768** [comment]
Also when editing an article, creating/editing a category, etc.

**Comment by dgt41** [comment]
check #8225

**Comment by zero-24** [comment]
Closing as we have a PR
