### ISSUE TITLE
com_category Error while using modal for making multilingual associations between the categories

### ISSUE THREAD

**Issue by kshitijSharma2014** [joomla/joomla-cms#8222]
#### Steps to reproduce the issue
See this video to understand the issue
https://www.youtube.com/watch?v=-qs2PiXCA3A&feature=youtu.be

1. install Joomla Multilingual website, French and English
2. Create category with Engligh (UK) language.
3. Create category with French (FR) language.
4. search for the english category in the search bar.
5. click on the category (english).
6. Go in the association section.
7. click on select.
8. search for the french category.
9. french category gets replaced by the english category
10. you will see the error.

#### Expected result
1. we get the french category on searching it in the modal

#### Actual result
2. Search fails

#### System information (as much as possible)
Macbook pro
El Capitan
Safari
firefox

**Comment by javigomez** [comment]
cc: @Kubik-Rubik, @infograf768

**Comment by infograf768** [comment]
Search is broken in the modal indeed (3.5.0-dev)

A. All French categories display in the modal when trying to associate any of them to the English category edited. This works fine
![screen shot 2015-10-31 at 11 38 09](https://cloud.githubusercontent.com/assets/869724/10863165/76d7bc88-7fc4-11e5-943b-79c72481446b.png)

B. Searching for a specific existing one does change display which is wrong.

**Comment by infograf768** [comment]
OK,
we do have indeed an issue for search in the modal as I said above BUT the original post is correct.

AFTER searching for a category in the categories manager list and THEN editing it we are in trouble because there was a patch merged to keep language and others list display parameters in memory some time ago.

**Comment by roland-d** [comment]
I have created a PR to fix this issue, please test #8227 so we can resolve this issue. Thanks.
