### ISSUE TITLE
Registered Default Access Default

### ISSUE THREAD

**Issue by trec-r** [joomla/joomla-cms#8229]
#### Steps to reproduce the issue
Install joomla or upgrade from 2. branch. - Log In Admin - Users - Access Levels - Registered

#### Expected result
Only Registered should be checked.

#### Actual result
Both Registered and Manager are checked.

#### System information (as much as possible)
Impacts at least 3.4.3 - 3.4.5 
We have checked about a dozen sites, all have the same problem. Upgraded sites from 2. did not have the issue before hand.

**Comment by schnuti** [comment]
I would say the default is ok. A user in the User Group "Manager" should be able to see Access Level "Registered". ie at least the same as a user in the User Group "Registered". Accesslevels are not diectl related to User Groups even if the default names are related.

**Comment by trec-r** [comment]
My bad. This is what happens when you don't have enough sleep and/or caffeine. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8229">issues.joomla.org/joomla-cms/8229</a>.</sub>

**Comment by brianteeman** [comment]
So can this be closed then?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8229">issues.joomla.org/joomla-cms/8229</a>.</sub>

**Comment by trec-r** [comment]
Yes this can be closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8229">issues.joomla.org/joomla-cms/8229</a>.</sub>

**Comment by brianteeman** [comment]
Closed as requested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8229">issues.joomla.org/joomla-cms/8229</a>.</sub>
