### ISSUE TITLE
Association tab not working in banners

### ISSUE THREAD

**Issue by kshitijSharma2014** [joomla/joomla-cms#8231]
#### Steps to reproduce the issue
1. Install multi-lingual Joomla
2. Go to banner categories
3. Click on Association
4. you will see a blank space

#### Expected result
we should see an option to select other banners to make an association

#### Actual result
We cannot see anything
![screen shot 2015-11-01 at 07 42 40](http://issues.joomla.org/uploads/1/ee723e7a41b369d592791b7909bd5b8d.png)
#### System information (as much as possible)
Macbook pro
safari
firefox

**Comment by infograf768** [comment]
There should never be an association tab for banners. It was never implemented for a simple reason: they are displayed by a module that can be tagged to any language.
Therefore this Association tab should go away... It is present now because it is implemented for Categories in general. Looking into it.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/8246

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8231">issues.joomla.org/joomla-cms/8231</a>

**Comment by infograf768** [comment]
Closing as we have a patch. Thanks for the report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8231">issues.joomla.org/joomla-cms/8231</a>.</sub>
