### ISSUE TITLE
German umlauts transformation instead of removing

### ISSUE THREAD

**Issue by designbengel** [joomla/joomla-cms#8241]
On image upload in tinymce umlauts are not transformed but removed.

For example: 
Übergrößenträger gets -> bergrentrger so it´s not readable any more.
In alias generation the umlauts are transformed right: ü to ue, ö to oe, ß to ss, ä to ae

thanks :)

**Comment by schnuti** [comment]
I think this is a well known problem. I have it myself. There is a function that makes the names "filesafe" but I think no one found a better general solution. File names allowed depend on the systems you work on. I think the common level for all is A-Z,a-z,0-9 and - , _. Personally I only use lower case a-z, 0-9 and _ , as lower and upper case are handled differently from system to system.

You have the same with the backend Media Manager.
Let's hope someone can change it to at least allow Western European characters. There are also Eastern European, Cyrillic and the asian characters that make life harder. ;).

**Comment by brianteeman** [comment]
For reference
http://www.tinymce.com/wiki.php/MCImageManager:filesystem.clean_names

On 2 November 2015 at 17:46, Ove Eriksson <notifications@github.com> wrote:

> I think this is a well known problem. I have it myself. There is a
> function that makes the names "filesafe" but I think no one found a better
> general solution. File names allowed depend on the systems you work on. I
> think the common level for all is A-Z,a-z,0-9 and - , _. Personally I only
> use lower case a-z, 0-9 and _ , as lower and upper case are handled
> differently from system to system.
>
> You have the same with the backend Media Manager.
> Let's hope someone can change it to at least allow Western European
> characters. There are also Eastern European, Cyrillic and the asian
> characters that make life harder. ;).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8241#issuecomment-153097610>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by schnuti** [comment]
Great! They have given it a thought. It would be nice to know what " things like åäö to aao" means more than handling the 3 swedish Umlauts.

If the editor is changed, the Media Manager has to handle it the same way, or there will be a mess with the filenames.

**Comment by brianteeman** [comment]
I'm going to close this at this time as a known issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8241">issues.joomla.org/joomla-cms/8241</a>.</sub>
