### ISSUE TITLE
Upgrading gives an 500 error when using OpCache

### ISSUE THREAD

**Issue by JensKirk** [joomla/joomla-cms#8249]
Hi Joomla devs :-)

Using OpCache and upgrading extensions gives could give an 500 error on both frontend and backend but often it "just" gives strande PHP erros in the backend.

Here is my recommandation for the next version of Joomla.

Insert this code before the upgrade is started:

    if (extension_loaded('Zend OPcache')) opcache_reset();

And perhaps also run the code above one more time just after upgrade.

I am manually doing it for my web clients that use OpCache on their sites.

OpCache is great and creates much faster pages but Joomla is not fully compatibable with it.

**Comment by tigasiap** [comment]
Terimakasih atas info yang telah diberikan 
http://goo.gl/enzrXl obat tradisional tbc tulang | http://goo.gl/5fC5E6 Pengobatan Tradisional Ejakulasi Dini | http://goo.gl/HBzjB7 ciri ciri orang kena penyakit tbc | http://goo.gl/X6aBFQ cara mengatasi ejakulasi dini pada pria | http://goo.gl/wYxrDP jamu agar tahan lama di ranjang | http://obatkankergetahbening.web.id/obat-benjolan-di-kepala-bagian-belakang/ Obat Benjolan Di Kepala Bagian Belakang | http://goo.gl/yDNdhO cara mengatasi ejakulasi dini | http://goo.gl/E806C0 obat kanker getah bening | http://goo.gl/iYL6ml obat kolesterol tenks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8249">issues.joomla.org/joomla-cms/8249</a>.</sub>

**Comment by JensKirk** [comment]
Can anyone fix this issue that goes for all versions of Joomla?

**Comment by andrepereiradasilva** [comment]
@JensKirk consider making a pull request to solve the issue you're describing.
See https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

More info: https://docs.joomla.org/Portal:Joomla!_Code_Contributors

**Comment by mahagr** [comment]
Issue #9515 has more detailed analysis on why the issue happens (also in Joomla Updater) and how to work around and/or fix it. Its a separate issue as its not using extension installer code, but happens because of the files change and depending on opcache settings, the change is not detected.

The solution is not to call `opcache_reset();` before installation, but right after files have been copied.

**Comment by brianteeman** [comment]
I am closing this here so we have just one topic

**Comment by mahagr** [comment]
Alright, I just need to remember to fix both of the issues then.. :)
