### ISSUE TITLE
Weird "password" and "notes" in backend "Components" menu

### ISSUE THREAD

**Issue by UberGruber** [joomla/joomla-cms#8252]
I've reported this issue here first, https://github.com/Fabrik/fabrik/issues/1559, since I thought it was related to their etension, but now that I'm working on another installation I noticed a similar voice this time referencing to one of the language package I installed. Look at this menu picture for reference:

![menu components](https://cloud.githubusercontent.com/assets/1172428/10861341/d02024ea-7f7b-11e5-9750-f6cb610e041d.png)

How come these random menu items spawn in the component section? Unfortunately I can just tell that the .xml files do not have anything wrongly formatted or else that can cause this I think.

What should I look for to help with this?

**Comment by zero-24** [comment]
what exactly joomla version do you running? When this come up on updating the external component or updating Joomla?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8252">issues.joomla.org/joomla-cms/8252</a>.</sub>

**Comment by UberGruber** [comment]
Using last joomla 3.4.5 on both sites. Unfortunately I really can't tell when they first appeared, I don't know if it's related to the last update, IIRC I saw this also on the other site that was on 3.4.4. and then updated to 3.4.5, but I'm not really sure.

**Comment by peterpeter** [comment]
I never had something similar, but I would search for the those entries in the #__menu table, and to wich extension they are linked in the #__extensions table.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8252">issues.joomla.org/joomla-cms/8252</a>.</sub>

**Comment by UberGruber** [comment]
On one site as stated in the linked issue are Fabrik plugins, in another site is a language package I installed so I don't think is related to a specific component. 
Maybe I should rename this issue more generic as "Weird plugin voice in backend Components menu"

**Comment by peterpeter** [comment]
Those entries in the components-menu are entries in the #__menu table, and are made by custom extensions while their installation/upgrade and have a column (extension_id) that references to entries in the #__extensions table. And thus leads you to the extension, who is responsible for that. I's up to you...

**Comment by tigasiap** [comment]
Terimakasih atas info yang telah diberikan 
http://goo.gl/enzrXl obat tradisional tbc tulang | http://goo.gl/5fC5E6 Pengobatan Tradisional Ejakulasi Dini | http://goo.gl/HBzjB7 ciri ciri orang kena penyakit tbc | http://goo.gl/X6aBFQ cara mengatasi ejakulasi dini pada pria | http://goo.gl/wYxrDP jamu agar tahan lama di ranjang | http://obatkankergetahbening.web.id/obat-benjolan-di-kepala-bagian-belakang/ Obat Benjolan Di Kepala Bagian Belakang | http://goo.gl/yDNdhO cara mengatasi ejakulasi dini | http://goo.gl/E806C0 obat kanker getah bening | http://goo.gl/iYL6ml obat kolesterol tenks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8252">issues.joomla.org/joomla-cms/8252</a>.</sub>

**Comment by infograf768** [comment]
We have had that kind of issues in the past when updating at the same time a language pack and Akeeba or Admin Tools (don't remember which one or if both)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8252">issues.joomla.org/joomla-cms/8252</a>.</sub>

**Comment by brianteeman** [comment]
Closed due to inactivity<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8252">issues.joomla.org/joomla-cms/8252</a>.</sub>
