### ISSUE TITLE
Allow numeric characters in JDocument format variable

### ISSUE THREAD

**Issue by subtext** [joomla/joomla-cms#8259]
In the JFactory class the format variable retrieved from the request uses the 'word' filter which strips out all numeric characters from the variable value and leaves only alpha characters. In order to add document types for video files such as m4v, mp4, etc... this change is needed to JDocument types which include numeric characters. Consider this example:

```php
$link = JRoute::_('index.php?option=com_video&format=m4v&id=y2VLUEh6crVq4hfV');
```

The router for the custom component returns a link in the form:

```
http://mysite.com/videos/y2VLUEh6crVq4hfV.m4v
```

However, following that link you will receive a view not found error message because the "type" variable will be returned as "mv" instead of "m4v" as the filter variable for JInput will strip out the numeric characters.

**Comment by subtext** [comment]
A pull request has been submitted #8260

**Comment by zero-24** [comment]
Closing as we have a PR here #8260 Thanks. I'm going to copy your description there.
