### ISSUE TITLE
Using two instances of module -> Articles - Category

### ISSUE THREAD

**Issue by saguweb** [joomla/joomla-cms#8270]
Currently attempting to use two instances of the module Articles - Category. However, the results for both listings always end up the same. The problem maybe in the fact that I'm referencing the same category but with different ordering and filtering. For example, I have one list ordered by Hits (Trending) and the other by Published Date (Latest).

Has anyone else experienced this? It works okay when I use a different category, but I suspect that the database call or reference is not unique when having this instance. Attached are the screenshots for each module: 
![Trending](https://cloud.githubusercontent.com/assets/15652105/10939332/762fd3d8-82c6-11e5-8284-b911ec4363b1.png)
![Latest](https://cloud.githubusercontent.com/assets/15652105/10939333/76330e72-82c6-11e5-9a56-cb0badf1ae19.png)

**Comment by saguweb** [comment]
Which code should I attach?

**Comment by zero-24** [comment]
@saguweb This is just a internal mark that this is a issue an no pull request ;)

**Comment by mbabker** [comment]
The code in the module generating the cache IDs does not use enough unique variables for the ID.  Basically it's an MD5 string of a serialized array containing the module name (mod_articles_category) and the current page's content item ID, category ID, or a null value if not meeting certain criteria.  It needs additional (known) values to make the resulting data more unique (using `$module->id` in that code will help).

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #11411<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8270">issues.joomla.org/joomla-cms/8270</a>.</sub>
