### ISSUE TITLE
Joomla CMS scaling issues

### ISSUE THREAD

**Issue by sandrodz** [joomla/joomla-cms#8273]
Hello,

I've dataset of 90,000 articles. 800,000 comments. And 28,000 tags. With traffic of 100,000 visitors per day.

System was getting by on J 1.5 + varnish. Since we upgraded to 3.4 J and tried to use J native caching things started to fall apart.

New article manager is very slow, I had to archive most of the articles, leaving only 10K in active state. Before archiving article manager wouldn't even load.

I'm curious if there is anyone in the community with similar big data experience? If there are any topic related known issues that can help?

**Comment by sandrodz** [comment]
I'm willing to share dataset if someone in J community is willing to take a look.

**Comment by Bakual** [comment]
@alikon @gunjanpatel Something for you guys :smile:

**Comment by alikon** [comment]
@sandrodz could you please ping us  https://volunteer.joomla.org/working-groups/sql-optimization-working-group or via glip 
we would like to investigate this a bit further

**Comment by gunjanpatel** [comment]
Yes that will help a lot @sandrodz Thank you guys.

**Comment by sandrodz** [comment]
I've registered at glip: sandrodz[@]gmail.com (in-house we use slack) now what do I do? :)

**Comment by alikon** [comment]
you have been invited now
we can close this one
