### ISSUE TITLE
JCaptcha parameters incorrect after first load

### ISSUE THREAD

**Issue by jeffchannell** [joomla/joomla-cms#8275]
In libraries/cms/captcha/captcha.php JCaptcha is incorrectly setting the plugin parameters, making it impossible to render more than one captcha on a single page.

JCaptcha::_load first fetches the plugin:

```
$plugin = JPluginHelper::getPlugin('captcha', $this->_name);
```

Then it sets the parameters:

```
$params = new Registry($plugin->params);
$plugin->params = $params;
```

Initially, $plugin->params is a JSON encoded string so the first run will load this into Registry and everything works as expected. The issue is that any subsequent runs of this code will result in the existing Registry being loaded into a new Registry, which leads to nested data.

This particular issue can be fixed by checking the parameters before setting them:
```
if (!($plugin->params instanceof Registry))
{
	$params = new Registry($plugin->params);
	$plugin->params = $params;
}
```
However, it may be that this bug is actually in Registry itself and this is just one area that it is manifested.

**Comment by zero-24** [comment]
@jeffchannell can you send your fix as pull request against the staging branch? If you need help please see: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by jeffchannell** [comment]
@zero-24 I'm not sure my patch is much more than a bandage, as it may be an issue with Registry:

```
use Joomla\Registry\Registry;
// test data
$json = json_encode(array('foo' => 'bar'));
// first run
$test1 = new Registry($json);
print_r($test1);
// second run
$test2 = new Registry($test1);
print_r($test2);
// third run
$test3 = new Registry($test2);
print_r($test3);
```

Output:
```
Joomla\Registry\Registry Object
(
    [data:protected] => stdClass Object
        (
            [foo] => bar
        )

    [separator] => .
)
Joomla\Registry\Registry Object
(
    [data:protected] => stdClass Object
        (
            [data] => stdClass Object
                (
                    [foo] => bar
                )

            [separator] => .
        )

    [separator] => .
)
Joomla\Registry\Registry Object
(
    [data:protected] => stdClass Object
        (
            [data] => stdClass Object
                (
                    [data] => stdClass Object
                        (
                            [foo] => bar
                        )

                    [separator] => .
                )

            [separator] => .
        )

    [separator] => .
)
```

**Comment by brianteeman** [comment]
I thought we already had a pull for this?

**Comment by jeffchannell** [comment]
@brianteeman if so, that's great! Do you have a link?

**Comment by jeffchannell** [comment]
@brianteeman found it:

https://github.com/joomla/joomla-cms/pull/7210

Same fix as what I posted above.

**Comment by brianteeman** [comment]
My memory rocks  despite the old age

**Comment by zero-24** [comment]
Closing as we have a PR that use that code<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8275">issues.joomla.org/joomla-cms/8275</a>.</sub>
