### ISSUE TITLE
Page Break plugin > Presentation Style bug

### ISSUE THREAD

**Issue by htmgarcia** [joomla/joomla-cms#8279]
Create an article with page breaks:
![breaks](https://cloud.githubusercontent.com/assets/4999794/10959552/90612dd2-833f-11e5-9879-585f66312a16.jpg)

Go to Extensions > Plugins > Content - Page Break
Set Presentation Style: *Sliders*
![sliders](https://cloud.githubusercontent.com/assets/4999794/10959508/096c5d7e-833f-11e5-8fa2-6a79c590e9f8.jpg)

Check the article in frontend, the content is hidden with inline CSS "display:none"
![hidden](https://cloud.githubusercontent.com/assets/4999794/10959525/3fc4217c-833f-11e5-93b9-e133cbe01515.jpg)

**Comment by tigasiap** [comment]
Terimakasih atas info yang telah diberikan 
http://goo.gl/enzrXl obat tradisional tbc tulang | http://goo.gl/5fC5E6 Pengobatan Tradisional Ejakulasi Dini | http://goo.gl/HBzjB7 ciri ciri orang kena penyakit tbc | http://goo.gl/X6aBFQ cara mengatasi ejakulasi dini pada pria | http://goo.gl/wYxrDP jamu agar tahan lama di ranjang | http://obatkankergetahbening.web.id/obat-benjolan-di-kepala-bagian-belakang/ Obat Benjolan Di Kepala Bagian Belakang | http://goo.gl/yDNdhO cara mengatasi ejakulasi dini | http://goo.gl/E806C0 obat kanker getah bening | http://goo.gl/iYL6ml obat kolesterol tenks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8279">issues.joomla.org/joomla-cms/8279</a>.</sub>

**Comment by schnuti** [comment]
I tested this but can not confirm. The inline CSS "display:none" hides page 1 from displaying twice.

I can confirm that there is a problem with sliders. They do NOT "slide". With parameter set to tabs they work more or less as supposed.
I'll open a new issue to suggest a change for sliders and tabs.

**Comment by htmgarcia** [comment]
I confirm Tabs works like a charm in my end. Actually I'll post a tutorial about it today in the JED blog.

About Sliders, I wonder if people need it? We can just remove that feature if we consider it useless.

**Comment by dgt41** [comment]
@htmgarcia @schnuti can you test #7760? It adds bootstrap tabs and sliders to the available options

**Comment by zero-24** [comment]
Closing as we have a PR that fix the issue. Thanks
