### ISSUE TITLE
Language: about the PLG_SYSTEM_UPDATENOTIFICATION

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#8285]
@nikosdion 

The string 
```
PLG_SYSTEM_UPDATENOTIFICATION_LANGUAGE_OVERRIDE_DESC="If you choose Auto (default), the update notification email to Super Users will be in the logged in user's front-end language at the time the plugin is triggered. In multi-language sites this can create confusion: the user's language may be one the Super User receiving the email doesn't speak. By selecting a language here you are forcing the update notification emails to be sent in this specific language."
```
is unclear, this for 3 reasons:
1. the language of the mail would be in the logged-in user's frontend language
Does that mean that a Super User has to be logged in for a mail to be sent? 
In back-end or front-end? Why wait for a Super logging?
2. In fact, the differenciation between multilanguage and monolanguage is wrong as a user preferred Site or Admin language can be in another language than another Super User ALSO in monolanguage.
3. Can't we change this behaviour and use,  for each super User, their admin preferred language? 

Another string `PLG_SYSTEM_UPDATENOTIFICATION_EMAIL_BODY` is extremely complex.
`; \n				Newline character. Use it to start a new line in the email. NO LINE SHOULD EXCEED 300 CHARACTERS!`
Why are characters limited to 300 per line? I thought the limit was 996 and to accomodate some old displays ideally limited to 80 (return not included).
Why is the en-GB value cut in such a weird way (at max 80 characters), i.e. why advising using 300 max instead of 80 max (if really necessary...)?:
```
This email is sent to you by your site to remind you of this fact. The Joomla!\n
project will never contact you directly about available updates of Joomla! on\n
your site.\n\n
================================================================================\n
```

**Comment by nikosdion** [comment]
1. No, that means that whatever language the system is running in when the plugin is triggered that's the language of the email being sent.

2. I know that, but this CANNOT be processed.

3. No. Because if there's no preferred language for the specified user Joomla! will revert to behaviour number 1 (load whatever random language the site is being displayed in).


You can EITHER use a CRON job and always load the correct language (at the expense of making it impossible for 99% of our users to set up this check) OR have the notification run as a plugin _but_ compromise at the expense of language flexibility. IMHO it makes much more sense agreeing with your Super Users that all update emails should be sent in e.g. English than trying to handle the massively complex task of loading the right language at any time.

If you wonder why: 10 Super Users with different language preferences require ~2-4 seconds to handle JUST the language loading. Add another 4-5 seconds to send the emails and we're talking about an increase in page load time in the order of 9 seconds. That's unacceptable. I'd rather send all emails in English (and slow Joomla! down by 2 seconds when emails are sent) than make Joomla! slow down for 9  or more seconds when emails are sent.

**Comment by infograf768** [comment]
@nikosdion
Sorry, but I do not understand fully your replies and one thing I am sure of is that these tips have to be modified as they are very unclear.
>that means that whatever language the system is running in when the plugin is triggered that's the language of the email being sent.

What does that mean? When exactly is the plugin triggered? 
Are mails sent when no user is logged but the site is visited by a guest/public? 
If it needs a Super User to be logged, what happens when multiple superUsers are logged at the same time?

Lets' take a simple example: I have a site which is not up to date with the latest update. 
No SuperUser logs in for 2 months. Will mails be sent during this period? 
If a non-SuperUser logs in, are the mails sent?
If any of these has to be logged, is it on frontend or backend or any?

>I know that, but this CANNOT be processed.

the matter is that the tip (PLG_SYSTEM_UPDATENOTIFICATION_LANGUAGE_OVERRIDE_DESC) is WRONG as the issue is NOT specific to multilanguage. I quote:
>In multi-language sites this can create confusion: the user's language may be one the Super User receiving the email doesn't speak. By selecting a language here you are forcing the update notification emails to be sent in this specific language.

It should rather say: 
>This can create confusion on sites where multiple languages are installed: [...]

==> You have not replied to the character limit per line of the message sent. What about it? Except if a TT is editing manually, they will not see your comments and try to mimic the values as they show in the tip.

Depending on your replies, I will propose some changes to these strings asap.

Side note:
>Because if there's no preferred language for the specified user [...]

There is always a preferred language for any specified user as the default language for admin or site is used when no specific other language is set for the user.

**Comment by nikosdion** [comment]
I am not going to reply to anything else. This plugin has been available in Admin Tools for 5+ years. Everyone –even users with zero experience– figured out how it works and nobody complains about it. So far it's taken me 10x more time to discuss it in Joomla! than it took me to write it! I am pasting the ENTIRE documentation of the plugin as I have it in Admin Tools:

------
Admin Tools Professional can send you e-mails to remind you of available updates to the Joomla! CMS. By default, when a new version is detected, it will send an email to all Super Administrators on your site notifying them of the available update. Even better, it goes one step further than simply notifying you of the availability of the new version. Clicking on the link found in the update notification email you are automatically taken to your site and forwarded to the relevant update page.

Update checks will be performed periodically, without having you to log in to your site's back-end. These checks will be performed as long as your site receives about page views every day at a minimum.
------

That's all. Please stop bugging me about this. I'm tired. I don't want to waste more time on trying to take features off my paid product and into Joomla! itself. Thank you.

**Comment by infograf768** [comment]
Thanks for your reply. I will propose a patch for these lang files.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/8315
