### ISSUE TITLE
Replace Mootols with Bootstrap 2 for article tabs and sliders

### ISSUE THREAD

**Issue by schnuti** [joomla/joomla-cms#8287]
When testing #8279 I saw that the tabs and sliders for pagebreaks in articles are using Mootools.
I think this should be changed to the use of Bootstrap. 

JHtml::_($style . '.start', JHtml::_($style . '.panel',  and JHtml::_($style . '.end');

Means: /html/sliders.php and /html/tabs.php are called.

It should be possible to rewrite this to use JLayouts for easy overrides for other frameworks than Bootstrap 2.  And probably reusable.

I'm not sure where the calls to JLayout should be added. Directly in the plugin or in the html-phps?

Another way is to use the methods in JHtmlBootstrap as is.

**Comment by dgt41** [comment]
Please test: https://github.com/joomla/joomla-cms/pull/7760

**Comment by schnuti** [comment]
Great! Exactly as proposed above. Will test it. 

This can be closed.
