### ISSUE TITLE
COM_BANNERS_FIELD_VALUE are taken as plurals

### ISSUE THREAD

**Issue by horus68** [joomla/joomla-cms#8295]
/administrator/en-GB.com_banners.ini has some similar keys (5) ends by numbers and are considered as Plurals when working with some translation software. 
They are not plurals and this caused issues when translating (not all languages has plurals and 5 is to much for all!)
Considering that this strings do not follow the normal way Joomla use for keys they should be changed.

File: https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/en-GB.com_banners.ini

The keys (line 129):
```
COM_BANNERS_FIELD_VALUE_1="Unlimited"
COM_BANNERS_FIELD_VALUE_2="Yearly"
COM_BANNERS_FIELD_VALUE_3="Monthly"
COM_BANNERS_FIELD_VALUE_4="Weekly"
COM_BANNERS_FIELD_VALUE_5="Daily"
```

Should be:
```
COM_BANNERS_FIELD_VALUE_UNLIMITED="Unlimited"
COM_BANNERS_FIELD_VALUE_YEARLY="Yearly"
COM_BANNERS_FIELD_VALUE_MONTHLY="Monthly"
COM_BANNERS_FIELD_VALUE_WEEKLY="Weekly"
COM_BANNERS_FIELD_VALUE_DAILY="Daily"
```

Note this other COM_BANNERS_FIELD_VALUE_ on the same file:
```
COM_BANNERS_FIELD_VALUE_CUSTOM="Custom"
COM_BANNERS_FIELD_VALUE_IMAGE="Image"
COM_BANNERS_FIELD_VALUE_USECLIENTDEFAULT="-- Use Client Default --"
COM_BANNERS_FIELD_VALUE_USECOMPONENTDEFAULT="-- Use Component Default --"
```

**Comment by horus68** [comment]
Related code files:
/administrator/components/com_banners/models/forms/filter_clients.xml
		<field name="purchase_type" type="list"
			label="COM_BANNERS_FILTER_PURCHASETYPE_LABEL"
			description="COM_BANNERS_FIELD_PURCHASETYPE_DESC"
			default="0"
			onchange="this.form.submit();"
		>
			<option value="">COM_BANNERS_SELECT_TYPE</option>
			<option value="1">COM_BANNERS_FIELD_VALUE_1</option>
			<option value="2">COM_BANNERS_FIELD_VALUE_2</option>
			<option value="3">COM_BANNERS_FIELD_VALUE_3</option>
			<option value="4">COM_BANNERS_FIELD_VALUE_4</option>
			<option value="5">COM_BANNERS_FIELD_VALUE_5</option>
		</field>
			
			
/administrator/components/com_banners/models/forms/client.xml
		<field name="purchase_type" type="list"
			label="COM_BANNERS_FIELD_PURCHASETYPE_LABEL" description="COM_BANNERS_FIELD_PURCHASETYPE_DESC"
			default="0"
		>
			<option value="-1">JGLOBAL_USE_GLOBAL
			</option>
			<option value="1">COM_BANNERS_FIELD_VALUE_1
			</option>
			<option value="2">COM_BANNERS_FIELD_VALUE_2
			</option>
			<option value="3">COM_BANNERS_FIELD_VALUE_3
			</option>
			<option value="4">COM_BANNERS_FIELD_VALUE_4
			</option>
			<option value="5">COM_BANNERS_FIELD_VALUE_5
			</option>
		</field>
		
		
/administrator/components/com_banners/models/forms/banner.xml
		<field name="purchase_type" type="list"
			label="COM_BANNERS_FIELD_PURCHASETYPE_LABEL" description="COM_BANNERS_FIELD_PURCHASETYPE_DESC"
			default="0">
			<option value="-1">COM_BANNERS_FIELD_VALUE_USECLIENTDEFAULT
			</option>
			<option value="1">COM_BANNERS_FIELD_VALUE_1
			</option>
			<option value="2">COM_BANNERS_FIELD_VALUE_2
			</option>
			<option value="3">COM_BANNERS_FIELD_VALUE_3
			</option>
			<option value="4">COM_BANNERS_FIELD_VALUE_4
			</option>
			<option value="5">COM_BANNERS_FIELD_VALUE_5
			</option>
		</field>
		
/administrator/components/com_banners/config.xml
		<field
			id="purchase_type"
			name="purchase_type"
			type="list"
			label="COM_BANNERS_FIELD_PURCHASETYPE_LABEL"
			description="COM_BANNERS_FIELD_PURCHASETYPE_DESC"
			default="0"
			>
			<option
				value="1">COM_BANNERS_FIELD_VALUE_1</option>
			<option
				value="2">COM_BANNERS_FIELD_VALUE_2</option>
			<option
				value="3">COM_BANNERS_FIELD_VALUE_3</option>
			<option
				value="4">COM_BANNERS_FIELD_VALUE_4</option>
			<option
				value="5">COM_BANNERS_FIELD_VALUE_5</option>
		</field>

**Comment by brianteeman** [comment]
Makes sense to me  to give the keys meaningful names - the only problem is
that there is a policy NOT to remove existing strings so we can't change
them we can only add new strings and that doesn't solve your specific
problem

On 6 November 2015 at 12:07, Horus68 <notifications@github.com> wrote:

> Related code files:
> /administrator/components/com_banners/models/forms/filter_clients.xml
> label="COM_BANNERS_FILTER_PURCHASETYPE_LABEL"
> description="COM_BANNERS_FIELD_PURCHASETYPE_DESC"
> default="0"
> onchange="this.form.submit();"
> >
> COM_BANNERS_SELECT_TYPE
> COM_BANNERS_FIELD_VALUE_1
> COM_BANNERS_FIELD_VALUE_2
> COM_BANNERS_FIELD_VALUE_3
> COM_BANNERS_FIELD_VALUE_4
> COM_BANNERS_FIELD_VALUE_5
>
> /administrator/components/com_banners/models/forms/client.xml
> label="COM_BANNERS_FIELD_PURCHASETYPE_LABEL"
> description="COM_BANNERS_FIELD_PURCHASETYPE_DESC"
> default="0"
> >
> JGLOBAL_USE_GLOBAL
>
> COM_BANNERS_FIELD_VALUE_1
>
> COM_BANNERS_FIELD_VALUE_2
>
> COM_BANNERS_FIELD_VALUE_3
>
> COM_BANNERS_FIELD_VALUE_4
>
> COM_BANNERS_FIELD_VALUE_5
>
> /administrator/components/com_banners/models/forms/banner.xml
> label="COM_BANNERS_FIELD_PURCHASETYPE_LABEL"
> description="COM_BANNERS_FIELD_PURCHASETYPE_DESC"
> default="0">
> COM_BANNERS_FIELD_VALUE_USECLIENTDEFAULT
>
> COM_BANNERS_FIELD_VALUE_1
>
> COM_BANNERS_FIELD_VALUE_2
>
> COM_BANNERS_FIELD_VALUE_3
>
> COM_BANNERS_FIELD_VALUE_4
>
> COM_BANNERS_FIELD_VALUE_5
>
> /administrator/components/com_banners/config.xml
> id="purchase_type"
> name="purchase_type"
> type="list"
> label="COM_BANNERS_FIELD_PURCHASETYPE_LABEL"
> description="COM_BANNERS_FIELD_PURCHASETYPE_DESC"
> default="0"
> >
> value="1">COM_BANNERS_FIELD_VALUE_1
> value="2">COM_BANNERS_FIELD_VALUE_2
> value="3">COM_BANNERS_FIELD_VALUE_3
> value="4">COM_BANNERS_FIELD_VALUE_4
> value="5">COM_BANNERS_FIELD_VALUE_5
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8295#issuecomment-154394295>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by horus68** [comment]
Next major version, maybe?

**Comment by brianteeman** [comment]
Yes it would have to be in j4 according to current policies

**Comment by Bakual** [comment]
To deal with the B/C issue we can leave the old strings there and just add new ones with better key names. Since the old ones would not be used anymore, it wouldn't matter if they are not translated because they are threated as plural.

**Comment by Bakual** [comment]
See and test https://github.com/joomla/joomla-cms/pull/8300.

**Comment by zero-24** [comment]
Closing as we have a PR. Thanks
