### ISSUE TITLE
J3.5 Beta1

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#8304]
On update sql error:

Duplicate entry '452' for key 'PRIMARY' SQL=INSERT INTO `#__extensions` (`extension_id`, `name`, `type`, `element`, `folder`, `client_id`, `enabled`, `access`, `protected`, `manifest_cache`, `params`, `custom_data`, `system_data`, `checked_out`, `checked_out_time`, `ordering`, `state`) VALUES (452, 'plg_system_updatenotification', 'plugin', 'updatenotification', 'system', 0, 1, 1, 0, '', '', '', '', 0, '0000-00-00 00:00:00', 0, 0);

**Comment by zero-24** [comment]
@810 please check which extension block that ID. Thanks

**Comment by 810** [comment]
for me extention id 452 is plg_captcha_nocaptcha

**Comment by zero-24** [comment]
This extension was never shiped in stable as far as i know this was changed bevor the release and merged into the "old" captcha plugin ;)

**Comment by zero-24** [comment]
Can you try updating from 3.4.5 stable to 3.5.0 beta. This should work as this plugin is not shiped with 3.4.5 :)

**Comment by 810** [comment]
clean J3.4.5 to J4.5.0 B1 is ok, no error

**Comment by zero-24** [comment]
Ok so i guess your other test System was a bit older and othen used for testing new releases? If yes than is the only question i can't 100% answer atm. Did we ship the nocaptcha plugin or got it merged with the old bevor stable?

**Comment by 810** [comment]
I think, this one: https://github.com/joomla/joomla-cms/pull/5323

**Comment by zero-24** [comment]
Yes but This gets reverted here: https://github.com/joomla/joomla-cms/pull/5888 and tgis goes also into 3.4.0 stabel ;)

**Comment by 810** [comment]
Ahh yes, that's the one. So I will close this issue.

**Comment by zero-24** [comment]
Thanks :)
