### ISSUE TITLE
Not the "official" blue for the loginBackgroundColor?

### ISSUE THREAD

**Issue by MAT978** [joomla/joomla-cms#8305]
Testing the 3.5 beta 1

following the latest brand manual here: http://issuu.com/joomladocs/docs/20150308_joomla_brandmanual_basic_d/1
or here: https://docs.joomla.org/JDOC:Colors
the color chosen for the loginBackgroundColor (#224c8f) is not an "official" one.

here are the different choices:
Blue
#0d6dab  (logo color)
#75bee9  (lighter)
Other Blue (from dark to light)
#25304f 
#4076a2 
#2383c6 
#91c5ea

**Comment by zero-24** [comment]
This is know see: https://github.com/joomla/joomla-cms/pull/7623

As implemented here: https://github.com/joomla/joomla-cms/pull/6703

Can you send a fix that we use the correct colors? (i don't know that we have official colors ;) #learneverydaysomethingnew 

Personaly i think the we should keep the original as default but... Ok lets choose a great official one ;)

**Comment by MAT978** [comment]
TBH, I don't care if we use an "official" one or not, it's just that this one is sooooooooo blue!

**Comment by zero-24** [comment]
I agree with you. Let the release leader / PLT decide on what color we go. Thanks for bringing it up. :+1:

**Comment by MAT978** [comment]
then maybe it's the right moment to ask him also to delete the btn gradient + forget the btn border radius.....
never know :wink:

**Comment by dgt41** [comment]
Let me know if #7610 is still valid 😃

**Comment by nonumber** [comment]
I suggest we change the default background color to: ##17568c
That is the same color used for the headerBackgroundHighlight
```
// Login
// -------------------------
@loginBackground:                  #17568c;

// Header
// -------------------------
@headerBackground:                 #1a3867;
@headerBackgroundHighlight:        #17568c;
```

Result:
![image](https://cloud.githubusercontent.com/assets/744259/11015076/8f2f7ad2-8550-11e5-84b9-7cb9966ec6fc.png)

**Comment by wilsonge** [comment]
Does that still fit with AA accessibility colour schemes?

**Comment by Bakual** [comment]
We certainly don't need to use an "official" colour here. That shouldn't be an argument.
The change was done as part of https://github.com/joomla/joomla-cms/pull/6703.

**Comment by MAT978** [comment]
It's for sure not an argument (see above), but it's a way to make it changed :p

**Comment by Bakual** [comment]
I agree with you that the current blue doesn't look that good. It jumps to much into the eye for a background that should stay in the back :smile:

**Comment by nonumber** [comment]
See: https://github.com/joomla/joomla-cms/pull/8345

**Comment by MAT978** [comment]
Closed as there's a PR - Thanks
