### ISSUE TITLE
UX: J3.5B1 add space alert on update extensions

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#8306]
Add space on alert info

![untitled](https://cloud.githubusercontent.com/assets/876623/11013039/efb49358-84fe-11e5-81a0-39bf3298e7a5.png)

**Comment by zero-24** [comment]
@810 Can You test: https://github.com/joomla/joomla-cms/pull/8282 Thanks

**Comment by 810** [comment]
@test  +1

**Comment by zero-24** [comment]
Thanks.
