### ISSUE TITLE
Install from Web broken in Joomla 3.5. Beta 1

### ISSUE THREAD

**Issue by ChrisHoefliger** [joomla/joomla-cms#8314]
#### Steps to reproduce the issue
Open Extensions => Manage => Install
Click the 'Add Install from Web' button
An Error msg appears saying 'Unable to find install package'

#### Expected result
Install from Web Tab appears

#### Actual result
It seems the plugin is not part of the distro.

#### System information (as much as possible)
Joomla! 3.5.0-beta Beta [ Ember ] 06-November-2015 24:00 GMT 
PHP 5.6.8, MySQL 5.5.41-log, Apache 2.2.27 MAMPP on Win 8.1

**Comment by zero-24** [comment]
The install from web guys Need to update The update server maybe @beat Can help here?

**Comment by beat** [comment]
@zero-24 Thanks for the heads-up! I will update this to add 3.5 version asap.

**Comment by zero-24** [comment]
Ok as it is nothing the core controls I will Close here. Thanks.

**Comment by 810** [comment]
Any progress on this one? @beat

**Comment by beat** [comment]
Sorry for delay. I will do a build and make available online for 3.5 in next days.

**Comment by JanKrohn-Khalibre** [comment]
@beat I've noticed the same issue happening on the 4.0.0-dev branch.
