### ISSUE TITLE
Drop the userspace PRNG, use random_compat

### ISSUE THREAD

**Issue by paragonie-scott** [joomla/joomla-cms#8325]
https://github.com/joomla/joomla-cms/blob/ec8a72f4cd0519786b9001dd3dd593131e7d32d2/libraries/joomla/crypt/crypt.php#L165-L246

When it comes to cryptography, there's basically no reason to not *always* use a CSPRNG.

PHP 7 ships with `random_bytes()` and `random_int()` for this exact purpose. For PHP 5 projects, check out the [random_compat](https://github.com/paragonie/random_compat) polyfill.

**Comment by mbabker** [comment]
See #8351
