### ISSUE TITLE
IFW return Unable to find install package

### ISSUE THREAD

**Issue by ot2sen** [joomla/joomla-cms#8331]
#### Steps to reproduce the issue
3.5.0 beta 1 Click manage -> try activate Install from web

#### Expected result
In 3.4.5 and earlier it would install the plugin and show the IFW. With 3.5.0 beta 1 it return an error ![screen shot 2015-11-08 at 03 47 13](https://issues.joomla.org/uploads/1/4486df3229a6a74df4b6a015acb2eaaa.png)

#### System information (as much as possible)
J 3.5.0 beta 1, tested locally PHP 5.6 and web PHP 7, same result. Was reported by a user first

**Comment by zero-24** [comment]
See: https://github.com/joomla/joomla-cms/issues/8314 @beat is aware ;)

**Comment by ot2sen** [comment]
Very good thanks. Will close this one then.
Didnt see the issue in the tracker. Will have to improve my search :)

**Comment by zero-24** [comment]
No Problem :) it was an closed issue so harder to find ;) Thanks for your report.
