### ISSUE TITLE
Chosen multiple select very limit

### ISSUE THREAD

**Issue by balvard** [joomla/joomla-cms#8339]
Salam
#### Steps to reproduce the issue
When use a select list with multiple property we expect to see place holder is same as we chose for this element.
But we see "Select some options" for default place holder.
#### Expected result
I want to see a diffrent place holder for each multiple select list .
if you have more than one multiple select list you cant understand which box for which select list !!!!!!
#### Actual result
You see "Select some options" for all select list.
#### System information (as much as possible)
for this issue chosen must use default placeholder property for each multiple select list like as single select list.
#### Additional comments
In formbehavior.php I see a wrong parameters.
parameter $options['placeholder_text_multiple'] must use as default when not set placeholder on each select list.
#### Priority 2
I guess need change source
#### Screen shots
[Current view](https://issues.joomla.org/uploads/1/dadc38dedb95f9d3668c41b88ce9fb70.png)
[Expected result](https://issues.joomla.org/uploads/1/eafa884d64c0d30663d745cb8f6ca6f6.png)

Best Reg.
Alireza Balvardi

**Comment by brianteeman** [comment]
Resetting priority according to https://docs.joomla.org/Bug_and_Issue_Tracker_Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8339">issues.joomla.org/joomla-cms/8339</a>.</sub>

**Comment by brianteeman** [comment]
As we can see below this is possible - so i am not sure exactly what the problem is that you have

![screen shot 2016-03-21 at 12 42 04](https://issues.joomla.org/uploads/1/058dd4b56348cc05d5cd70c4ebd46ae5.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8339">issues.joomla.org/joomla-cms/8339</a>.</sub>

**Comment by brianteeman** [comment]
Closed due to lack of response<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8339">issues.joomla.org/joomla-cms/8339</a>.</sub>
