### ISSUE TITLE
The joomla update 3 5 does not pass under Wamp

### ISSUE THREAD

**Issue by marie-louise2013** [joomla/joomla-cms#8359]
#### Steps to reproduce the issue

Tentative de mise à jour Joomla 3.5 par fichier télécharger sous wamp, j'ai testé sous Wamp 2.4 et 2.5

La mise à jour débute normalement puis fini sans résultat

(Attempt of update Joomla 3.5 by file to download under wamp, I made out a will under Wamp 2.4 and 2.5

The update begins normally then finished without result)

#### Expected result

Mise à jour Joomla 3.5 Beta

#### Actual result

Pas de mise à jour 

(No update)

#### System information (as much as possible)

Paramètres 	Valeur
 
PHP exécuté sur 	Windows NT DBCI34130 6.2 build 9200 (Windows 8 Home Premium Edition) AMD64
Version de la base de données 	5.6.17
Interclassement de la base de données 	utf8_general_ci
Version de PHP 	5.5.12
Serveur web 	Apache/2.4.9 (Win64) PHP/5.5.12
Serveur web pour interface PHP 	apache2handler
Version de Joomla 	Joomla! 3.4.5 Stable [ Ember ] 22-October-2015 21:30 GMT
Version de la plateforme Joomla! 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Navigateur 	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0

**Comment by n9iels** [comment]
Can you please translate you issue in English? :smile:

**Comment by infograf768** [comment]
De quelle façon précise avez-vous tenté de mettre à jour? 
(How did you precisely try to update?)
Merci de poster en Anglais sur Github.

**Comment by marie-louise2013** [comment]
I downloaded the file of béta update and I installed it as an extension

( (Translation made by Reverso)

**Comment by hvdmeer** [comment]
The Beta file is a complete install. So you should install it as a new install, not as an extension.

**Comment by richard67** [comment]
@hvdmeer There are complete install and also update containers available for download, and @marie-louise2013 used the update one, which can of course be installed like a normal extension, and so I think she did it right.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8359">issues.joomla.org/joomla-cms/8359</a>.</sub>

**Comment by MAT978** [comment]
Tested many diff config + workflows without any problems.
@marie-louise2013 please try again and let us know.
https://github.com/joomla/joomla-cms/releases

*fr-FR*
Je n'ai pas rencontré de problèmes lors de mes différents tests et méthodes de MAJ.
Merci de réessayer avec les packs.
https://github.com/joomla/joomla-cms/releases

**Comment by marie-louise2013** [comment]
Double problème visiblement, 
1) le premier vient de Wamp, car la l'installation de la mise à jour Release.zip fait exactement comme la version française.
2) sur site distant, la version française me note plug in installé, mais la mise a jour n'est pas faite
mais avec la version release après un message "504 gateway time out" la version Joomla 3.5 beta enfin installée je vais pouvoir continuer mes tests.
Merci de votre patience avec une nouvelle

Double problem apparently,
1) The first one comes from Wamp, because the installation of the update Release.zip makes exactly as the French version.
2) On-site distant, the French version plug in installed  note me, but the putting has in the daytime is not made but with the release version after a message " 504 gateway time out " the Joomla 3.5 version beta finally installed I am going to be able to continue my tests.
Thank you for your patience.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8359">issues.joomla.org/joomla-cms/8359</a>.</sub>

**Comment by brianteeman** [comment]
Closing at this time<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8359">issues.joomla.org/joomla-cms/8359</a>.</sub>
