### ISSUE TITLE
mssql: Create user note - save failes

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#8360]
Create a new user note and press save. You should get this error message:

DateTime::__construct(): Failed to parse time string (-1-11-30) at position 5 (-): Double timezone specification

**Comment by alikon** [comment]
unable to rerpoduce
do you have some specific settings?

**Comment by waader** [comment]
Sorry, I confused postgres with mssql.

**Comment by zero-24** [comment]
Sorry @waader our changes had crossed. I'm going to fix it back to mssql

**Comment by brianteeman** [comment]
closed as requested as it is resolved in #8666 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8360">issues.joomla.org/joomla-cms/8360</a>.</sub>
