### ISSUE TITLE
[3.5-beta1] Select hides behind batch modal footer

### ISSUE THREAD

**Issue by Bakual** [joomla/joomla-cms#8367]
### Issue
When trying to batch copy articles, I can't select anything from the category dropdown because it is hidden behind the modal footer:
![batch](https://cloud.githubusercontent.com/assets/1018684/11061496/d442be46-87a7-11e5-939d-b2a8d46efc94.PNG)

@dgt41 related to some of your changes?

**Comment by infograf768** [comment]
I confirm the issue

**Comment by akinom500** [comment]
I also confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8367">issues.joomla.org/joomla-cms/8367</a>.</sub>

**Comment by infograf768** [comment]
Issue comes from adding
+.modal-body {
+	padding: 5px 10px;
+	overflow: hidden;
+}
in
https://github.com/joomla/joomla-cms/pull/5871

**Comment by dgt41** [comment]
We can remove this line from the template.css but we have to add it in the media vie images otherwise the iframe won't scroll on mobile devices

**Comment by Bakual** [comment]
What about the padding? It looks worse with it in the batch modal (and probably others).
I think you can add the specific CSS to the template by using additionally the class field-media-wrapper as parent or something similar.

**Comment by dgt41** [comment]
That will work as well, but the changes are for the media field so they have to be template independent

**Comment by Bakual** [comment]
> they have to be template independent

The changes present are done for Protostar and Isis only, so they already depend on the template.

**Comment by dgt41** [comment]
Because only protostar and Isis use the bootstrap version....
I guess both ways will work!

**Comment by Bakual** [comment]
Do the change only for Isis and Protostar, and keep it specific to the media field.

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8367">issues.joomla.org/joomla-cms/8367</a>

**Comment by infograf768** [comment]
Closing as we have a patch https://issues.joomla.org/tracker/joomla-cms/8373<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8367">issues.joomla.org/joomla-cms/8367</a>.</sub>

**Comment by infograf768** [comment]
@zero-24 

This should be closed as we have a patch

**Comment by zero-24** [comment]
Done @infograf768
