### ISSUE TITLE
Blank Screen after Admin Login

### ISSUE THREAD

**Issue by tofoursquare** [joomla/joomla-cms#8370]
#### Steps to reproduce the issue
Whenever I type in my user name and password into the joomla admin for my website, it accepts it and then goes to a blank white screen. I cannot move past that or log into my admin to update/ make changes to our site.

#### Expected result
I should be able to log into my admin to make changes to our website.

#### Actual result
Software
-------------------------------------------------------------------------

Windows Version			Microsoft Windows 10 (10.0) Home 64-bit   (Build 10240) 
DirectX Version			12.0
Display adapter 0	
	Name			AMD Radeon R7 200 Series
	Board Manufacturer	ASUSTeK Computer Inc.
	Memory size		2 GB
	PCI device		bus 1 (0x1), device 0 (0x0), function 0 (0x0)
	Vendor ID		0x1002 (0x1043)
	Model ID		0x6613 (0x048B)
	Performance Level	0
		Core clock	300.0 MHz
		Memory clock	300.0 MHz
	Performance Level	1
		Core clock	780.0 MHz
		Memory clock	900.0 MHz

Processors Information
-------------------------------------------------------------------------

Processor 1			ID = 0
	Number of cores		4 (max 8)
	Number of threads	8 (max 16)
	Name			Intel Core i7 4770S
	Codename		Haswell
	Specification		Intel(R) Core(TM) i7-4770S CPU @ 3.10GHz
	Package (platform ID)	Socket 1150 LGA (0x1)
	CPUID			6.C.3
	Extended CPUID		6.3C
	Core Stepping		C0
	Technology		22 nm
	TDP Limit		65.0 Watts
	Tjmax			92.0 °C
	Core Speed		3890.7 MHz
	Multiplier x Bus Speed	39.0 x 99.8 MHz
	Stock frequency		3100 MHz
	Instructions sets	MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, EM64T, VT-x, AES, AVX, AVX2, FMA3
	L1 Data cache		4 x 32 KBytes, 8-way set associative, 64-byte line size
	L1 Instruction cache	4 x 32 KBytes, 8-way set associative, 64-byte line size
	L2 cache		4 x 256 KBytes, 8-way set associative, 64-byte line size
	L3 cache		8 MBytes, 16-way set associative, 64-byte line size
	FID/VID Control		yes

	Turbo Mode		supported, enabled
	Max non-turbo ratio	31x
	Max turbo ratio		39x
	Max efficiency ratio	8x
	O/C bins		none
	Ratio 1 core		39x
	Ratio 2 cores		38x
	Ratio 3 cores		36x
	Ratio 4 cores		35x
	TSC			3093.0 MHz
	APERF			3766.5 MHz
	MPERF			2993.6 MHz
	IA Voltage Mode		PCU adaptive
	IA Voltage Offset	0 mV
	GT Voltage Mode		PCU adaptive
	GT Voltage Offset	0 mV
	LLC/Ring Voltage Mode	PCU adaptive
	LLC/Ring Voltage Offset	0 mV
	Agent Voltage Mode	PCU adaptive
	Agent Voltage Offset	0 mV

	Temperature 0		27°C (80°F) [0x41] (Core #0)
	Temperature 1		30°C (86°F) [0x3E] (Package)
	Power 0			1.19 W (Package)
	Power 1			0.29 W (IA Cores)
	Power 2			n.a. (GT)
	Power 3			0.90 W (Uncore)
	Power 4			2.01 W (DRAM)
	Voltage 0		1.15 Volts (VID)
	Voltage 1		+0.00 Volts (IA Offset)
	Voltage 2		+0.00 Volts (GT Offset)
	Voltage 3		+0.00 Volts (LLC/Ring Offset)
	Voltage 4		+0.00 Volts (System Agent Offset)

#### System information (as much as possible)
See attachment

**Comment by n9iels** [comment]
This problem is not a bug in Joomla. (on the current version I can login without any problems). Please use http://forum.joomla.org for support questions
