### ISSUE TITLE
No possible to access all components (in admin) if you have installed them more (many)

### ISSUE THREAD

**Issue by radik10** [joomla/joomla-cms#8371]
#### Steps to reproduce the issue
use "isis" admin template and install 30-40 components and try them to access on display wider than 776px (height of display/monitor about 700-800px). Than try to reach latest installed components in the list of components menu - it is not possible. See attached image. Now it is possible all components only if you "zoom out" your browser view (ctrl+- in firefox).

#### Expected result
To have possibility to access all installed components with smaller monitor (display) and with many installed components also on smaller monitors/tablets (with template "isis").

#### Actual result
![Not possible to access all installed components (with smaller display)](http://joomla.r-art.sk/administrator-components-no-access.jpg "no access with many installed components")

#### System information (as much as possible)
joomla 3.4.5 and same problem with joomla 3.5.0 beta, tested with Firefox 42.0 and Chrome 46.0.2490.80 m, template "isis" - this problem is not with "hathor" template.

#### Additional comments
If you change width of browser under 775px, your admin backend has changed design, and changed menu, and therefore all components are accessible - this is problem with more components and smaller displays (monitor/tablet width of display if is larger than 776px) and with isis template.

**Comment by sovainfo** [comment]
See http://forum.joomla.org/viewtopic.php?f=706&t=825242#p3102613 and
http://forum.joomla.org/viewtopic.php?f=706&t=825242#p3256916 for workarounds

Also https://github.com/joomla/joomla-cms/issues/5492 for the discussion.

**Comment by radik10** [comment]
Hi, solution "http://forum.joomla.org/viewtopic.php?f=706&t=825242#p3256916" works only for "desktop" screens (width >775px), if you resize window for narrow screen, submenues are not visible and therefore not accessible. DEFINITLY this must be solved at Joomla level (at least J.3.5+). This "workaround" is not for 100%.
 


     On Tuesday, November 10, 2015 7:53 PM, sovainfo <notifications@github.com> wrote:
   

 See http://forum.joomla.org/viewtopic.php?f=706&t=825242#p3102613 and
http://forum.joomla.org/viewtopic.php?f=706&t=825242#p3256916 for workaroundsAlso #5492 for the discussion.—

**Comment by sovainfo** [comment]
Both workarounds are no solution to the issue, they just might help. 

When they don't help enough, suggest to create browser bookmarks and remove those items from the menu.

**Comment by brianteeman** [comment]
This looks like a good solution BTW this looks like a good solution https://ugate.wordpress.com/2013/06/28/scrollable-twitter-bootstrap-menus/

Its not just about having too many components you also have this issue when you have a lot of menus which is very common on a multilingual site

**Comment by brianteeman** [comment]
Please see #9347 for a proposed solution
