### ISSUE TITLE
Possible BUG in jForm getFieldAttribute

### ISSUE THREAD

**Issue by widesys** [joomla/joomla-cms#8381]
Hello, I have an instance of a form, I'm trying to get the default value of the field in the xml, in this case the default value is 0 (zero).

The problem occurs in getFieldAttribute role in "libraries/joomla/form/form.php"

This will return false because the default value is 0
if (($element instanceof SimpleXMLElement) && ((string) $element[$attribute]))

I believe that the correct test would be:
if (($element instanceof SimpleXMLElement) && isset($element[$attribute]))

The correct is to test if the attribute exists.

http://www.widesys.com.br/getFieldAttribute.webm

Thank you

**Comment by izharaazmi** [comment]
@widesys Please test this PR to make sure it works as expected now.

**Comment by widesys** [comment]
It works as expected.
Thank you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8381">issues.joomla.org/joomla-cms/8381</a>.</sub>

**Comment by brianteeman** [comment]
Closing as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8381">issues.joomla.org/joomla-cms/8381</a>.</sub>
