### ISSUE TITLE
Post Install Messages sort order

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#8382]
The Messages are displayed in ascending ID which means that the oldest ones are at the top. I know there are only 3 right now but it makes more sense to me that the newest message is always at the top (ORDER BY postinstall_message_id DESC )

I did try to fix this myself but only managed to ADD it to the ORDER by not change it

**Comment by zero-24** [comment]
@brianteeman please have a look here: https://github.com/joomla/joomla-cms/pull/8458
