### ISSUE TITLE
Layout consistency

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#8384]
In the layout files 
/layouts/joomla

Some have
defined('JPATH_BASE') or die;
Some have 
defined('_JEXEC') or die;

and readmore has neither

**Comment by brianteeman** [comment]
Happy to do a PR to fix this if someone can just say which is the correct option<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8384">issues.joomla.org/joomla-cms/8384</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman the correct is `defined('JPATH_BASE') or die;` for layouts. This is my last stand on this ;)

**Comment by brianteeman** [comment]
OK - PR on its way

On 12 November 2015 at 11:42, zero-24 <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> the correct is defined('JPATH_BASE')
> or die; for layouts. This is my last stand on this ;)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8384#issuecomment-156081439>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
See #8398 for a PR
