### ISSUE TITLE
JTableNested assumes 'alias' column

### ISSUE THREAD

**Issue by okonomiyaki3000** [joomla/joomla-cms#8388]
`JTableNested:rebuild()` fires a query that selects the primary key column of the table as well as the `alias` column. So it is assumed that any table (unless its class overrides this function) with a 'nested' structure will contain an `alias` column. Alas, this is not true. The `#__assets` table does not have an alias column. 

In practice, perhaps this never comes up because `JTableAsset` never has any reason to call `rebuild` but it should not be theoretically possible for this to happen either. `JTableAsset` should either override `rebuild` or `#__assets` should have an alias column or `JTableNested` should properly handle that case that a table does not have an `alias` column.

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/6307 I merged this 4 days ago which overrides the rebuild method :)
