### ISSUE TITLE
edit_assignment.php breaks after too many list items

### ISSUE THREAD

**Issue by Paradoxis** [joomla/joomla-cms#8410]
When loading a large amount of list items the nested menu breaks due to invalid HTML being produced. File: `/administrator/components/com_modules/views/module/tmpl/edit_assignment.php` 

**Joomla version:** 3.4.0
**Screenshot:**
![unnamed](https://cloud.githubusercontent.com/assets/6770124/11141444/c7d8b7b0-89e5-11e5-8540-ec81f57d6dea.png)

**Comment by zero-24** [comment]
@Paradoxis you use an outdated version of joomla please update your prod install atleast to 3.4.5 as it fixes a major sec issue. Than please try it again. If it still not work please try in a dev envoirment our last version 3.5.0-beta: https://github.com/joomla/joomla-cms/releases/tag/3.5.0-beta.

Please don't use 3.5.0-beta in your prod install.

Than please report back. Thanks.

**Comment by brianteeman** [comment]
I am unable to confirm this. 

The Joomla testing data has a very large set of menu items and it has no problem.

I am closing this at this time. If you are able to reproduce this with the current release of Joomla please post back and it can always be re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8410">issues.joomla.org/joomla-cms/8410</a>.</sub>
