### ISSUE TITLE
Upgrade from 3.3.6 to 3.4.5 break Menu in Dual language site

### ISSUE THREAD

**Issue by congpine** [joomla/joomla-cms#8414]
#### Steps to reproduce the issue
Sites 3.3.6 with 2 languages, switchable from the front-end.
Each set of menus associate with each language and it worked fine with 3.3.6
Site Default language is Vietnamese, the 2nd one is English
After upgrading to 3.4.5, the English language couldn't show any Menu. Vietnamese languages shows correct menu.
Please visit the site here:
Vietnamese: http://goo.gl/T2kwT6
English: http://goo.gl/rA2vV6
I tried to revert the code back to 3.3.6 and it works well again.
This is the Dev site that is using old code 3.3.6 : http://goo.gl/i6d6QE

**Comment by infograf768** [comment]
This is most certainly due to another change on your site as I see that the <head> is different. Display the resulting popup of the admin module multilanguage status to check and make sure that your template styles do load the correct mainmenu.

**Comment by congpine** [comment]
Thanks for your reply.
The <head> change could be due to the way Joomla loading up js, css in 3.4.5
I can re-replicate this issue by upload another backup files to the server ( 3.3.6), confirmed that English and Vietnamese languages work correctly.
As soon as I upgraded to 3.4.5, English menu just disappear when switching to English.
Can I send you a login so you can login and confirm it yourself?

Thanks for your help

**Comment by brianteeman** [comment]
After several months without activity and no other reports I a closing this at this time - it can always be reopened if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8414">issues.joomla.org/joomla-cms/8414</a>.</sub>
