### ISSUE TITLE
upgrading 3.4.5 to 3.5.0-beta1 with postgresql gives error

### ISSUE THREAD

**Issue by slibbe** [joomla/joomla-cms#8415]
#### Steps to reproduce the issue
1. Install Joomla 3.4.5 with postgresql
2. Set JoomlaUpdate to Testing
3. Do upgrade to 3.5.0-beta1

#### Expected result
ERROR: syntax error at or near ""#__contentitem_tag_map_idx_tag"" LINE 1: ...lTER TABLE "#__contentitem_tag_map" DROP INDEX "#__con... ^SQL=AlTER TABLE "#__contentitem_tag_map" DROP INDEX "#__contentitem_tag_map_idx_tag";

while site seems upgraded allright.

#### System information (as much as possible)
Parameters: PHP 5.6.14, Postgresql 9.3.10, Apache 2.4.16

**Comment by alikon** [comment]
@slibbe  can you test

**Comment by Bakual** [comment]
Closing as it is fixed with the merged PRs

**Comment by slibbe** [comment]
Sorry. Had no time to check. Suppose it's not needed anymore.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8415">issues.joomla.org/joomla-cms/8415</a>.</sub>
