### ISSUE TITLE
3.5.0 beta Hathor offline image, misplaced preview and clear controls

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#8423]
3.5.0 beta Staging 2015-11-13

Test:
- Select Hathor as standard backend template.
- Go to Settings > Global configuration > Site settings
- See field offline image

![offline-image](https://cloud.githubusercontent.com/assets/11038612/11153692/dec36a88-8a3a-11e5-996a-4f2911e94ebc.jpg)

**Comment by brianteeman** [comment]
I can confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8423">issues.joomla.org/joomla-cms/8423</a>.</sub>

**Comment by gautamtailored** [comment]
I have been facing the same issue in Hathor as default backend template.
Tested In:
OS : Windows 10
Browser : Mozilla Firefox Version 48
Joomla 3.5.1
Hathor as default backend template.![screen shot 2016-07-19 at 04 57 19](https://issues.joomla.org/uploads/1/bd5f0f98523c46cf0d4726764772c08c.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8423">issues.joomla.org/joomla-cms/8423</a>.</sub>

**Comment by bhavikTailored** [comment]
- I am able to reproduce this issue in Joomla 3.6.0
![screen shot 2016-07-19 at 05 08 22](https://issues.joomla.org/uploads/1/3961b9b5db0febdd091e3e6a10a141fa.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8423">issues.joomla.org/joomla-cms/8423</a>.</sub>

**Comment by brianteeman** [comment]
@C-Lodder if you want to attempt to resolve this one it would be great<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8423">issues.joomla.org/joomla-cms/8423</a>.</sub>

**Comment by C-Lodder** [comment]
@brianteeman - Is killing Hathor an option?

**Comment by brianteeman** [comment]
I wish it was but sadly not. This isn't a priority to fix but a would be
nice to fix

**Comment by C-Lodder** [comment]
I'll add it to my "to-do" list

**Comment by C-Lodder** [comment]
Is it just me or does **Isis** not have the "Offline Image" option?

**Comment by C-Lodder** [comment]
All done, just need to do RTL. Where the hell is the LESS file for this?

**Comment by brianteeman** [comment]
There may not be one for Hathor

**Comment by C-Lodder** [comment]
Yeah can't find one at all so just going to update the CSS file

**Comment by C-Lodder** [comment]
PR submitted: https://github.com/joomla/joomla-cms/pull/11534
