### ISSUE TITLE
Beez3 very small search button, without icon

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#8425]
Joomla 3.5.0 beta Staging 2015-11-13
Joomla 3.4.5

Test:
- Select Beez3 as standard template for frontend.
- Go to frontend and enter a search word in search module (top right of page)
- Search results page opens.
- See search button. Very small, no icon.

![beez3-search](https://cloud.githubusercontent.com/assets/11038612/11154286/bd22e4ea-8a3e-11e5-8ea6-ea17ab21da60.jpg)

**Comment by waader** [comment]
I confirm this problem.

**Comment by infograf768** [comment]
Same issue for smartsearch

**Comment by infograf768** [comment]
I am working on a patch. 
Left to Right allready solved + calendar icons in smartsearch Advanced search
It may take some time for RTL as it is badly broken in com_search

**Comment by infograf768** [comment]
Please test this PR:
https://github.com/joomla/joomla-cms/pull/8480
@waader @bertmert

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8425">issues.joomla.org/joomla-cms/8425</a>

**Comment by infograf768** [comment]
Closing as we have a PR: https://github.com/joomla/joomla-cms/pull/8480<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8425">issues.joomla.org/joomla-cms/8425</a>.</sub>
