### ISSUE TITLE
Confusing and not working Editor button module button : popup view top Style search

### ISSUE THREAD

**Issue by shamsbd71** [joomla/joomla-cms#8428]
#### Steps to reproduce the issue
Install new joomla 3.5 beta with sample data. go to article manager and edit any article.
click on module button on new tinyMCE editor. see top search option for module style

#### Expected result
not sure what is this for but i tried with some search type like: xhtml, html, raw but nothing worked and seems its not working at all

#### Actual result
it should be properly placed. not its looking very bad and not enough description to understand.

#### System information (as much as possible)
Windows 10 and WAMP with php 5.5

![screen shot 2015-11-14 at 01 07 51](https://issues.joomla.org/uploads/1/3ee4a7e31407a592f0330fd380c13d7c.png)

**Comment by dgt41** [comment]
This is just an input to append a specific style for the module. It won’t return anything, you need to know the available module styles (template dependent). If you think this is confusing please suggest some other label that will make this easier to grab.

**Comment by brianteeman** [comment]
This view does seem odd to me. The styling is different to module manager
(nicer).

As for adding the style I am not sure I see the need for this at all here
as you would normally define this in the module itself. (Does it replace
existing styles?)

**Comment by brianteeman** [comment]
I guess I am saying what is the use case for adding an additional style
option here.

**Comment by dgt41** [comment]
Setting the style here will override the saved module style, maybe this can be done with a button named advanced which will reveal the input. Anyhow, most of the users won’t use this option, I think

**Comment by brianteeman** [comment]
And that's the problem. It is the very first thing on the screen which
creates the impression it is important when as you suggest it will be
rarely used (have to say I can't think of a use case)

**Comment by shamsbd71** [comment]
oh! i got that finally!!! what is this for :)
i agree with @brianteeman it should be somewhere else or maybe we need to think a bit different way.
maybe something like this:
![module-popup](https://cloud.githubusercontent.com/assets/1936565/11163853/bfb34aae-8b08-11e5-8d78-71ca5c2be895.png)

**Comment by Bakual** [comment]
>  it will be used (have to say I can't think of a use case)

As for the usecase. Since here you load the module into an article, there isn't really a module style applied to it. I use this option often (eg by using the "well" style) so the module has a visual "border" (lack of knowing better word)

**Comment by brianteeman** [comment]
What is stopping you putting "well" in the module class suffix in the
normal way?

**Comment by Bakual** [comment]
That was only a (bad) example, depending on the template there are other styles where you can't achieve the same effect by just using a suffix. Like when they use a unique HTML structure around it.

**Comment by brianteeman** [comment]
Whats a good example then? :)

Either way it doesnt address the UI issue

> And that's the problem. It is the very first thing on the screen which
creates the impression it is important when as you suggest it will be
rarely used (have to say I can't think of a use case)

On 14 November 2015 at 15:03, Thomas Hunziker <notifications@github.com>
wrote:

> That was only a (bad) example, depending on the template there are other
> styles where you can't achieve the same effect by just using a suffix. Like
> when they use a unique HTML structure around it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8428#issuecomment-156709390>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by dgt41** [comment]
How about moving this block at the end of that page?

**Comment by shamsbd71** [comment]
Hey, i got my final suggestion:
** Remove this option complete to add style **

because when i select a module to insert with short-code, its already been defined in modules details settings, when i select it to load in article or anywhere it should be same as its defined in module. if i need raw output, i should change the module settings.

and to load module position : it should be at top like the previous attached pic, so to find any position i dont need to see the pagination and or search.

i think this is very simple :)

**Comment by shamsbd71** [comment]
if you all agree, i can create a pull request with removing that option ?

**Comment by brianteeman** [comment]
Personally thats exactly what I would submit a a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8428">issues.joomla.org/joomla-cms/8428</a>.</sub>

**Comment by brianteeman** [comment]
I created a PR for testing so closing this here see #11436
