### ISSUE TITLE
Adding 2 different JS editors in same page will insert duplicate JS functions

### ISSUE THREAD

**Issue by ggppdk** [joomla/joomla-cms#8429]
- Version: Joomla 3.x
- How to reproduce:
  add 2 different editors in the same page
  e.g. add tinymce and codemirror

you will get this javascript function to be added twice:

```
function jInsertEditorText( text, editor )
{
 ...
}
```
- Example of problem created:
  if you add codemirror after tinymce, then the XTD editor buttons will not work, because the codemirror's jInsertEditorText will be called (as it was added last)
- maybe this can be re-evaluted in J4.0 ?
  or is it possilbe to fix this without breaking all XTD button extensions ?

**Comment by dgt41** [comment]
I cannot imagine a solution for 3.x version that would be B/C and work for every 3pd component/plugin. I think this needs to be reviewed for 4.0...

**Comment by brianteeman** [comment]
Closed as we have a PR #12561
