### ISSUE TITLE
3.5.0 beta Hathor tooltips truncated in batch modal

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#8434]
3.5.0 beta staging 2015-11-13

Test
- Select Hathor as default backend template.
- Go to conten > articles (or other list view with batch button)
- Click batch button
- See tooltips

![tooltip-batch](https://cloud.githubusercontent.com/assets/11038612/11164473/c2f037d4-8af1-11e5-9dac-ae0d09519a9e.jpg)

**Comment by brianteeman** [comment]
I can confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8434">issues.joomla.org/joomla-cms/8434</a>.</sub>

**Comment by gautamtailored** [comment]
I have been facing the same issue in Hathor as default backend template.
Tested In:
  OS : Windows 10
  Browser : Google Chrome Version 51.0.2704.103
  Joomla 3.5.1
  Hathor as default backend template.
![screen shot 2016-07-19 at 04 31 55](https://issues.joomla.org/uploads/1/f54dad7106cbb98f586b6524cd8286d0.jpg)


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8434">issues.joomla.org/joomla-cms/8434</a>.</sub>

**Comment by brianteeman** [comment]
Looks like this has been fixed elsewhere as it is working ok in 3.6.1

![ooe3](https://cloud.githubusercontent.com/assets/1296369/17397924/2fdfeffa-5a32-11e6-991b-ee715ed13c2b.png)
