### ISSUE TITLE
Possible bug to to display Tags below content on frontend.

### ISSUE THREAD

**Issue by nemmar** [joomla/joomla-cms#8438]
Tags do not display with the "split" or "below" article config settings.
The issue and possible bug can be found posted on the Joomla forum:
http://forum.joomla.org/viewtopic.php?f=706&t=899171

**Comment by n9iels** [comment]
I created a single article menu item, and assigned an article to it. When I change the display parameter to "split" or "below", the tags are still visible.

Did you test this with the latest version of Joomla?

**Comment by nemmar** [comment]
Hi,
I'm using the latest version Joomla! 3.4.5 Stable. If it's not a Joomla bug, then maybe it's a template conflict with Joomla.
I can display the tags above but not split or below articles on my sites. Here are examples of single article menu items with the tags set to display below and split:
Below: http://www.1776.press/more/test-menu/test-single-article-tags-below
Split: http://www.1776.press/more/test-menu/test-single-article-tags-split
Above: http://www.1776.press/more/test-menu/test-single-article-tags-above

As you can see, the tags only display above the article. So if it's not a Joomla bug, then it must be a conflict with my template.

**Comment by brianteeman** [comment]
To confirm if it is an issue with your template or not (I suspect it is a
template override) you can try to replicate the issue using the protostar
template

**Comment by nemmar** [comment]
Hi Brian,

Yes, the problem still occurs with Protostar.
I switched those 3 menu items to use the Protostar template instead of the default Joostrap template. You can see those links now using Protostar and the split and below tag positions do not display. Could there be something else about my site that might cause this conflict, or do you think it's a Joomla bug?

**Comment by ot2sen** [comment]
Saw a user asking same question of tags below article how to show.
From what I can see, even in j3.5beta the issue occur when having all other article info setting to not show. The tags will only show if at least one of the article info settings is set to show, for example the 'Show Create Date'. Then the tags will appear below with below/split setting.

Tags do show above with all else set to not show. Only a below/split issue as I can see.

![tags_above_ok_all_red](https://cloud.githubusercontent.com/assets/790445/12898505/59d455e6-cead-11e5-9579-f83fd7b6f6d9.png)
![tags_below_or_split_ok_only_when_one_green](https://cloud.githubusercontent.com/assets/790445/12898506/59d8bad2-cead-11e5-9af9-4969c2fe5134.png)

**Comment by ot2sen** [comment]
Added a PR to allow the tags to show below article when all other article settings set to hide/no 
See https://github.com/joomla/joomla-cms/pull/9105

**Comment by brianteeman** [comment]
closing as we have a PR please test #9105<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8438">issues.joomla.org/joomla-cms/8438</a>.</sub>
