### ISSUE TITLE
Wrong linked redirection plugin on languages different than english

### ISSUE THREAD

**Issue by irbian** [joomla/joomla-cms#8441]
When you enter the Redirection component for first time, it will say you something like "Redirection plugin is not enabled" with a link to the plugin manager. But this will be search for the english string "System - Redirect", instead of the spanish (for example) one "Sistema - Redirección", so it won´t appear

**Comment by zero-24** [comment]
@irbian 

This is nothing the core controls ;) Please make sure you use the last version of the language pack. If yes please contact the spanish language coordinator and report the issue to him.

http://community.joomla.org/translations/joomla-3-translations.html#es-es

Thanks :)
