### ISSUE TITLE
Text remains after adding a new Tag to an article

### ISSUE THREAD

**Issue by dennis-tut** [joomla/joomla-cms#8446]
#### Steps to reproduce the issue
Created some tags (with varying length and some with more than 1 word)
Tried to add the tags with the auto-fill-feature (only typing a few characters and then selecting the suggested Tag)

#### Expected result
The text should reset and another tag can be added, starting with an empty string.
Also the cursor should remain in the input-box.

#### Actual result
Sometimes (it most often occurred when i had to retype because of a typo [Meaning i first typed "fino"->"fin"->"fini"]) the string didn't reset after i filled in the tag.
E.g. I typed "fini" and then selected "finished Projects", but then i had the tag added and after that the
"fini" was still there. Plus somehow my cursor left the box, meaning pressing backspace didn't remove the string,
but instead triggered the browser's "go to last page".
Besides, sometimes the problem would solve itself when tabbing out of the window and in again.
![Proof](http://dennlinger.bplaced.net/proof.png "example")

#### System information (as much as possible)
PHP Built On 	Linux CanisMajor 3.10.35 #5644 SMP Wed Oct 28 12:37:28 CST 2015 x86_64
Database Version 	5.5.44-MariaDB
Database Collation 	utf8_general_ci
PHP Version 	5.5.30
Web Server 	Apache
WebServer to PHP Interface 	fpm-fcgi 
Joomla! Version 	Joomla! 3.4.5 Stable [ Ember ] 22-October-2015 21:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; rv:42.0) Gecko/20100101 Firefox/42.0 

#### Additional comments
Note: This was produced on a modified Version of Joomla maintained by Synology Inc!
I will check if this bug appears on my other platforms, too.

**Comment by dennis-tut** [comment]
Edit:

It appears this is only a visual bug. Saving with the string still visible doesn't create another tag, but instead neglects it.
In my reproduced cases it now helped 100% with switching to another window.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8446">issues.joomla.org/joomla-cms/8446</a>.</sub>

**Comment by brianteeman** [comment]
Can you please confirm that you have replicated this issue on core unmodified joomla

**Comment by dennis-tut** [comment]
Can confirm this on unmodified joomla 3.4.5.
It happended most likely when correcting a typo in the tag, like mentioned in the original post.

**Comment by RonakParmar** [comment]
I have followed above steps and not able to reproduce this issue.

System information:
Joomla! Version: Joomla! 3.4.5 Stable [ Ember ] 22-October-2015 21:30 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
PHP Version: 5.5.30-1+deb.sury.org~precise+1
System Linux desktop 3.5.0-54-generic #81~precise1-Ubuntu SMP Tue Jul 15 04:02:22 UTC 2014 x86_64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8446">issues.joomla.org/joomla-cms/8446</a>.</sub>

**Comment by brianteeman** [comment]
I have not been able to replicate this on the current staging version of Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8446">issues.joomla.org/joomla-cms/8446</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for creating this but it would appear that this has been resolved elsewhere in the code base. If this is not correct then this can be re-opened

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8446">issues.joomla.org/joomla-cms/8446</a>.</sub>
