### ISSUE TITLE
JBrowser Opera detecteion

### ISSUE THREAD

**Issue by sergey-zero** [joomla/joomla-cms#8448]
Hi! I'm using the Opera 33.0. 
My user agent is: 
` Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36 OPR/33.0.1990.58 `

But JBrowser say it's the Chrome.
If i add this code (like chrome detection) into `joomla.environment.browse`
```
elseif (preg_match('|OPR[/ ]([0-9.]+)|', $this->agent, $version))
{
	$this->setBrowser('opera');
	list ($this->majorVersion, $this->minorVersion) = explode('.', $version[1]);
}
```
all working nice

**Comment by zero-24** [comment]
Hi,
Can you send your changes as pull request against the staging branche?

Here you can find help if you need help with it.

https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

If we have a pull request we can easy test and merge you changes. Thanks.

**Comment by zero-24** [comment]
Closing as we have a PR. Great Thanks https://github.com/joomla/joomla-cms/pull/8449
