### ISSUE TITLE
Tag Form Field does not display selected tags

### ISSUE THREAD

**Issue by svenbluege** [joomla/joomla-cms#8452]
#### Steps to reproduce the issue

- create a new article
- assign at least one tag
- save the article
- check the tag field

![screen shot 2015-11-16 at 14 40 20](https://issues.joomla.org/uploads/1/c348b989c12fc67d7e6dad947f5b4c0f.png) 

#### Expected result

If I add a tag I want it to be there after I saved the article. 

#### Actual result

The added tag is not visible.

#### System information (as much as possible)

Joomla 3.5 Staging Branch

#### Additional comments

Seems like the tag field is the problem here. It does not work for other forms too. I think the selected options are an array like 

```
Array ( [typeAlias] => [tags] => 2,3 )
```

**Comment by waader** [comment]
I can confirm your observation. Adding and saving one tag works, but adding a second one or more makes the assigned tags disappear.

**Comment by roland-d** [comment]
@svenbluege Thanks for your report, I am going to close it as it is the same as #8379 which contains a fix as well. Thank you for your contribution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8452">issues.joomla.org/joomla-cms/8452</a>.</sub>
