### ISSUE TITLE
Menu manager pagination broken in 3.5.0 beta

### ISSUE THREAD

**Issue by osignell** [joomla/joomla-cms#8456]
#### Steps to reproduce the issue

Install Joomla 3.5.0 beta
Open Administrator->Menus->Main menu
Add at least 5 new menu items
Change limit dropdown to "5"
Open search tools, select "Published".
Change to page 2, everything ok.
Change back to page 1, everything ok.
Open search tools again, select "- Select status-".
Try going to page 2 again.

#### Expected result

Page 2 shown

#### Actual result

Page 1 shown again

#### Additional comments

Please note that this is using 3.5.0 beta, so the changes regarding pagination included here do not fix this problem.

**Comment by osignell** [comment]
Additional info:

The reason for this seems to be that the limitstart value is reset on line 709 in libraries/legacy/model/list.php because new_state is null and cur_state is "1".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8456">issues.joomla.org/joomla-cms/8456</a>.</sub>

**Comment by Bakual** [comment]
Reverting https://github.com/joomla/joomla-cms/pull/7487 didn't fix it for me, can you try?

**Comment by Bakual** [comment]
limistart is reset when the code thinks the filter states changed :)

**Comment by osignell** [comment]
Reverting #7487 DOES actually fix the problem for me, you just have to try twice right after making the code change in order for the session to pick up the change.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8456">issues.joomla.org/joomla-cms/8456</a>.</sub>

**Comment by osignell** [comment]
correction.. it works if I use isset() without the additional check.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8456">issues.joomla.org/joomla-cms/8456</a>.</sub>

**Comment by infograf768** [comment]
I confirm
Using 
```
if (isset($filters[$name]))
			{
				$new_state = $filters[$name];
			}
```
solves this issue

**Comment by Bakual** [comment]
Can you check that the original issue with the user manager is solved as well this way?

**Comment by osignell** [comment]
The user manager works fine for me using the version with isset() only.

**Comment by Bakual** [comment]
Who wants to do the PR?

**Comment by infograf768** [comment]
Article Manager displays OK Unpublished articles (state = 0)
No problem either for modules.

**Comment by wojsmol** [comment]
@Bakual @infograf768 @osignell please test https://github.com/joomla/joomla-cms/pull/8467

**Comment by zero-24** [comment]
Closing as we have a PR
