### ISSUE TITLE
Administration  Folder Deleted

### ISSUE THREAD

**Issue by tofoursquare** [joomla/joomla-cms#8466]
#### Steps to reproduce the issue
Log in to back-end of site as normal.

#### Expected result
I should be able to log into my admin of the site.

#### Actual result
Goes to a blank page. I have inspected the elements and have come to find out that our site was hacked and they deleted our admin files. 

#### System information (as much as possible)
Joomla 3.4
Windows 10

#### Additional comments
Is there anyway to restore admin files as to log into the back-end once more?

**Comment by brianteeman** [comment]
You will need to restore your web site from a recent backup.

NOTE this issue tracker is not for support or for issues with individual web sites. Please use http://forum.joomla.org
