### ISSUE TITLE
Core Update sites https?

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#8469]
Should the links to the updated sites be changed from http to https?

**Comment by mbabker** [comment]
They tried.  They chickened out.  https://github.com/joomla/joomla-cms/pull/8196

**Comment by brianteeman** [comment]
Ah I knew it sounded familiar<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8469">issues.joomla.org/joomla-cms/8469</a>.</sub>

**Comment by Bakual** [comment]
Yes, they should be changed as well as the links in the XML files for the update streams itself (https://github.com/joomla/update.joomla.org/tree/master/www/core)
Tobias PR is still valid and will not cause any issues.

**Comment by brianteeman** [comment]
That PR is closed @bakual

**Comment by brianteeman** [comment]
Closing as the PR #8196 has been re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8469">issues.joomla.org/joomla-cms/8469</a>.</sub>
