### ISSUE TITLE
Help site link per user

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#8470]
It is possible in the admin to set a Help site per user. The options currently are "use-default, english and french"

However as soon as you click on the Refresh button the option to "use default" disappears

![screen shot 2015-11-17 at 13 54 59](https://issues.joomla.org/uploads/1/7fbc7c3849238355b26755c096fc8f95.png)

## after pressing refresh

![screen shot 2015-11-17 at 13 55 50](https://issues.joomla.org/uploads/1/9d6ac6487f832d5115eb8efacaacb73f.png)

**Comment by n9iels** [comment]
This problem can be fix by pushing the "Use default" option to the items array in `media/system/js/helpsite.js`

I tried, but I have one problem. The language string won't translate when I use this code:
```
items.push('<option value="">' + Joomla.JText._('JOPTION_USE_DEFAULT') + '</option>');
```
Anybody suggestions?

**Comment by RonakParmar** [comment]
I have followed above screen dump, able to reproduce this issue in Joomla 3.4.4.
System Information: 
PHP Version 5.5.30-1+deb.sury.org~precise+1
Apache Version: Apache/2.4.12 (Ubuntu)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8470">issues.joomla.org/joomla-cms/8470</a>.</sub>

**Comment by gunjanpatel** [comment]
Set to "closed" on behalf of @gunjanpatel by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8470">issues.joomla.org/joomla-cms/8470</a>

**Comment by gunjanpatel** [comment]
Closing as we have PR for this issue https://github.com/joomla/joomla-cms/pull/8572<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8470">issues.joomla.org/joomla-cms/8470</a>.</sub>
