### ISSUE TITLE
pgpool-II bug with standard_conforming_strings

### ISSUE THREAD

**Issue by rpvr** [joomla/joomla-cms#8476]
#### Steps to reproduce the issue
If you use postgres as db backend for joomla, and there is a pgpool istance in the middle, you will have to deal with this bug:
http://www.sraoss.jp/pipermail/pgpool-general/2013-August/002124.html

#### Additional comments
in /libraries/joomla/database/driver/postgresql.php there is a function "connect()", that after the connection sends a query 
pg_query('SET standard_conforming_strings=off');
for pgpool that will not work.
you should change the dns param

from
$dsn .= "dbname={$this->options['database']} user={$this->options['user']} password={$this->options['password']}";

to

$dsn .= "dbname={$this->options['database']} user={$this->options['user']} password={$this->options['password']} options='-c standard_conforming_strings=off'";

**Comment by brianteeman** [comment]
I have created a PR for this with your code - please test #9362<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8476">issues.joomla.org/joomla-cms/8476</a>.</sub>
