### ISSUE TITLE
Beez3 - "Advanced Search" link on smartsearch results page does not function

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#8482]
Contrary to the protostar template the "Advanced Search" button is displayed as link in the Beez3 template and the toggling does not work.

**Comment by infograf768** [comment]
I confirm. Looks like `collapse` does now work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8482">issues.joomla.org/joomla-cms/8482</a>.</sub>

**Comment by infograf768** [comment]
*now => `not`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8482">issues.joomla.org/joomla-cms/8482</a>.</sub>

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8482">issues.joomla.org/joomla-cms/8482</a>

**Comment by infograf768** [comment]
Closing as we have a patch:

https://github.com/joomla/joomla-cms/pull/8488<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8482">issues.joomla.org/joomla-cms/8482</a>.</sub>
