### ISSUE TITLE
Stats plugin misbehaving

### ISSUE THREAD

**Issue by dgt41** [joomla/joomla-cms#8484]
#### Problem
Go to admin area on a newly installed joomla
Don’t respond on the message about stats
Edit/create an article
Click on the button to insert an image

#### Actual result
![screenshot 2015-11-18 21 23 20](https://cloud.githubusercontent.com/assets/3889375/11251828/b94e7644-8e3b-11e5-8b39-c52c09703d30.png)

#### Expected result
Normal window

**Comment by Bakual** [comment]
Looks like it really wants you to answer that question :smile: 

But I agree it probably should not trigger in edit forms and modals.
Maybe safest way would be to only trigger the message in the cPanel?

**Comment by dgt41** [comment]
Easier to check if we are not on a modal 

```php
		if (JUri::getInstance()->getVar("tmpl") === "component")
		{
			return;
		}
```

**Comment by dgt41** [comment]
There is a patch #8485<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8484">issues.joomla.org/joomla-cms/8484</a>.</sub>
