### ISSUE TITLE
Duplicate language: language folder and in the folder of the plugin

### ISSUE THREAD

**Issue by carosouza** [joomla/joomla-cms#8486]
Hello everyone, sorry my note here, it's not a mistake, but the extensions below have in language folder and in the folder of the extension. I believe that it should only be in the language, ok?

admin language
==============
mod_multilangstatus
mod_version
mod_stats_admin

Plugin language
===============
system-> languagecode

Templates Language
==================
Bizz
Protostar

#### Steps to reproduce the issue
Check the above extensions

#### Expected result
Languages only in the languages folder

#### Actual result
Appear in the languages and in the extension folder

#### System information (as much as possible)
nothing

#### Additional comments
nothing

Thanks

Carosouza

**Comment by Bakual** [comment]
@infograf768 Guess that is for you to explain the history/intention of this :)

**Comment by infograf768** [comment]
We implemented this to demonstrate in core how works the new functionality that lets use the extension language folder.

We anyway had to do it for templates first on popular demand as people having unnstalled core templates wanted to be able to re-install them by using the Discover function. If we had not added the language folder in the extension (templates included), their constants will have remained displayed with no values.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8486">issues.joomla.org/joomla-cms/8486</a>.</sub>

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8486">issues.joomla.org/joomla-cms/8486</a>
