### ISSUE TITLE
grid.checkall does not working when not using grid.sort

### ISSUE THREAD

**Issue by Disaron** [joomla/joomla-cms#8497]
When using only grid.checkall and grid.id in list, but not using grid.sort or searchtools.sort, then checkbox grid.checkall does not select checkboxes, because [this](https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/html/grid.php#L123-L129) method does not call JHtml::_('behavior.core');

Maybe it's by design..? I create PR if not.

**Comment by Bakual** [comment]
Feel free to create a PR for it.
If a method needs behavior.core, it should always call it.

**Comment by brianteeman** [comment]
Closed as we have a PR #8500 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8497">issues.joomla.org/joomla-cms/8497</a>.</sub>
