### ISSUE TITLE
J3.4.5 and JRequest

### ISSUE THREAD

**Issue by Devportobello** [joomla/joomla-cms#8506]
After migrating to J3.4.5, one of my old third party extension who was using JRequest like that:
```php
// Require the base controller
require_once JPATH_COMPONENT.'/controller.php';

// Get an instance of the controller prefixed by *
$controller = JControllerLegacy::getInstance('Custom');

// Perform the Request task
$controller->execute(JRequest::getCmd('task'));

// Redirect if set by the controller
$controller->redirect();
```
Now didnt work when i want to do a particular task with subcontroller, eg: edit an item "?option=com_custom&task=item.edit&id=1";
I know JRequest is deprecated but for J4.0

```
JRequest::getCmd('task') = item.edit
JFactory::getApplication()->input->get('task','','CMD') = edit
```
so CustomController::execute is unable to do the task.
I tested only on backend and im unable to reproduce this on a fresh install ...

### How to test
after migrating, edit file: administrator/components/com_content/content.php
line 21: replace with
```php
$controller->execute(JRequest::getCmd('task'));
```
then try to edit an article.

**Comment by Bakual** [comment]
> I tested only on backend and im unable to reproduce this on a fresh install ...

Sounds more like a messed up update or a misbehaving 3rd party plugin then when you can't reproduce it on a clean install.

**Comment by Devportobello** [comment]
sound like messed up update... i closed this, sry wasting your time.
