### ISSUE TITLE
Joomla and Twig

### ISSUE THREAD

**Issue by adi8i** [joomla/joomla-cms#8507]
Hello.

Any chances to have a better integration of TWIG ?

e.g. To render Joomla articles from twig files. In Wordpress is possible if you use Timber, they have a bit different approach. Or if there's any other alternative ?

Twig is pretty cool and some of developers prefers to use it, although i am not that sure how to use it with Joomla.

https://github.com/jarednova/timber/wiki/Timber-docs#get_posts

**Comment by Bakual** [comment]
I doubt you can integrate it into Joomla 3. But as far as I remember it's a topic for Joomla 4.

**Comment by mbabker** [comment]
You could do it at the component level today (FOF3 supports Laravel's Blade that way).  But if you really wanted to use a "real" templating engine in Joomla, there'd have to be a lot of discussion and a lot of refactoring of the existing rendering mechanisms to do it.

**Comment by adi8i** [comment]
@mbabker is not possible to use Joomla API ?

**Comment by mbabker** [comment]
No.  JDocument and Twig (or any third party renderer) are incompatible.

**Comment by marcodings** [comment]
The tentative planning for Joomla does not include support for twig. 

From a resources standpoint the core will focus on Bootstrap 2 + 3 or 4. 

The planned J4 should have de possibility to add any custom renderer twig etc. This would however imply to also supply overrides for your redering engine for all core stuff and any extensions you are using.

If someone steps up and want to do that and hand that to core we can discuss that

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8507">issues.joomla.org/joomla-cms/8507</a>.</sub>
