### ISSUE TITLE
[New Feature] Delete or rebuild update sites in update sites manager

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#8512]
After updating Joomla and extensions a lot of times (since 1.7) we get a lot of obsolete update sites from domain changes, url changes, etc.

A feature i think is missing is a button to delete obsolete update sites or (even better) rebuild the update sites from the extensions XML files in update sites manager.

Note: Don't know if the last one is even possible.

**Comment by brianteeman** [comment]
You would have to rebuild from the extensions xml files otherwise you wouldnt know if something was obsolete.

**Comment by andrepereiradasilva** [comment]
Don't think so, just read them and check if the update site is right in the db.

For instance:
- don't exist in xml | exist in db: delete the update site from db.
- exist in xml | don't exist in db: add the update site.
- exist in xml | exist in db | is the same: do nothing
- exist in xml | exist in db | is different: update the db record with the xml one.

**Comment by andrepereiradasilva** [comment]
can be closed as we have a PR https://github.com/joomla/joomla-cms/issues/9744
