### ISSUE TITLE
Version History: toggling "keep forever" staus updates version author and date

### ISSUE THREAD

**Issue by tgv604** [joomla/joomla-cms#8522]
#### Steps to reproduce the issue
- Make sure version history is enabled for content
- Create an article, save it several times with some different content
- Login (at back-end) as a different user, open that article for editing, open version history modal window
- Toggle "Keep forever" state for any version and note their author and date changes

#### Expected result
- Version date and author would stay intact, "keep forever" status would change

#### Actual result
- Author and date get overwritten, so there's no way to figure who and when actually created that version

#### System information (as much as possible)
- Joomla 3.4.5

#### Additional comments
Function store() in /libraries/cms/table/contenthistory.php line 70 forces date and author update. It probably shouldn't if it's just a status change.

**Comment by tgv604** [comment]
v3.5 - still there<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8522">issues.joomla.org/joomla-cms/8522</a>.</sub>

**Comment by conconnl** [comment]
@tgv604 can you confirm this is still happening in 3.6 beta 2?
If so I will test your patch and try to find someone else who can test this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8522">issues.joomla.org/joomla-cms/8522</a>.</sub>

**Comment by infograf768** [comment]
I am making a patch right now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8522">issues.joomla.org/joomla-cms/8522</a>.</sub>

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8522">issues.joomla.org/joomla-cms/8522</a>

**Comment by infograf768** [comment]
Closing as we have a patch: Please test https://github.com/joomla/joomla-cms/pull/10975<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8522">issues.joomla.org/joomla-cms/8522</a>.</sub>
