### ISSUE TITLE
Admin submenu "Manage" takes you to "Install" instead of "Manage"

### ISSUE THREAD

**Issue by horus68** [joomla/joomla-cms#8526]
Admin submenu "Manage" (from Extensions menu) takes you to "Install" instead of the "Manage" option.
This also causes tab "Install from the Web" to be loaded every time an admin wants to "manage" slowing down his works... and JED!
This is not needed and also not useful.
A menu should take an user where it is logic to be taken to considering a fast work flow, not to where someone thinks its better (even if it was considering the Organization behind a software).

![2015-11-23 19_29_48-000397-definicoes](https://cloud.githubusercontent.com/assets/3055443/11347384/19e947a0-9219-11e5-8eb1-c753a6160340.png)

Related: I know this is an old discussion... but calling this admin menu "Extensions" when there is also a "Database", or "Warning" areas doesn't seem logic. The old "Installations" was more clear for users but I'm open to suggestions.

**Comment by brianteeman** [comment]
> Related: I know this is an old discussion... but calling this admin menu "Extensions" when there is also a "Database", or "Warning" areas doesn't seem logic. The old "Installations" was more clear for users but I'm open to suggestions

It has been called Extensions since at least 1.5

**Comment by zero-24** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8526">issues.joomla.org/joomla-cms/8526</a>.</sub>

**Comment by horus68** [comment]
Yes, it is called Extensions since least 1.5 (I said "old discussion" but my bad, I shouldn't bring that up here)
Regarding the main issue (Admin submenu "Manage" takes you to "Install" ) should this be changed?

**Comment by zero-24** [comment]
There for we have now the sub menus (3.5.0 +) ;)

**Comment by brianteeman** [comment]
Setting to Needs Review so a CMS maintainer can make a decision<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8526">issues.joomla.org/joomla-cms/8526</a>.</sub>

**Comment by roland-d** [comment]
Since we now have the submenu in Joomla, this is no longer an issue. Thank you all for contributing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8526">issues.joomla.org/joomla-cms/8526</a>.</sub>
