### ISSUE TITLE
unable to browse my Joomla site and log into backend

### ISSUE THREAD

**Issue by localjapan** [joomla/joomla-cms#8534]
We are unable to browse our Joomla website and also log into the backend site.(5500 or 440 error occurs)
The hosting server cleaned the files and suggested to ask developpers from Joomla.
Currently we are redirecting the site to our test wordpress site. But we'd like to keep the Joomla site.
It's a business website, so it's pretty urgent. Please help!

**Comment by Bakual** [comment]
Please use our forums for support requests: forum.joomla.org
This is the issue tracker for the CMS code itself.

**Comment by localjapan** [comment]
Hi, I thought I posted on joomla.org.
I am having a hard time finding where to report this issue. 
Would you kindly send me the direct URL for the support request?
Thank you!


  ----- Original Message -----

**Comment by zero-24** [comment]
forum.joomla.org ;) @localjapan
