### ISSUE TITLE
Composer feature not working

### ISSUE THREAD

**Issue by anuragac** [joomla/joomla-cms#8535]
#### Steps to reproduce the issue
Unknown

#### Expected result
autoload.php autoloaded in components section after successful installation of composer.json file

#### Actual result
No sign of new component installed

#### System information (as much as possible)
WAMP Server version 2.5 - Apache-2.4.9 - Mysql-5.6.17 - php5.5.12 - 64b

#### Additional comments

Please help with composer feature & guide to add new components.Thanks.

Anurag Asit Chakravorty

**Comment by Bakual** [comment]
The composer integration isn't meant to be used by extensions itself. It's primary use was for the core to fetch parts of it using composer (everything in /libraries/vendor/)

Can I ask you to take your question to https://groups.google.com/forum/#!forum/joomla-dev-general, which is the support forum for extension developer.
