### ISSUE TITLE
Fake URL Possible url manipulation.

### ISSUE THREAD

**Issue by metacreo** [joomla/joomla-cms#8537]
Still the same in Joomla 3.4.5
Router bug. Too many duplicate content errors.
Possible url manipulation.
http://yourdomain.com/en/news/55-item.html
http://yourdomain.com/en/category/55-item.html
http://yourdomain.com/en/fckoff/55-item.html
http://yourdomain.com/en/any-other/55-item.html
http://yourdomain.com/en/any/any/any/any/any/any/any/any/any/any/any/any/55-item.html

**Comment by zero-24** [comment]
Yes. Thanks for reporting. This is a known bug ;) But at least google don't care about duplicate content errors if it is on the same domain (e.g. example.org) ;)

There are plans and code for a new router but it is not ready yet to release. Feel free to test: https://github.com/joomla/joomla-cms/pull/8256

If you need help with testing see: https://docs.joomla.org/Testing_Joomla!_patches but as stated above it is not 100% ready yet ;)

So I'm closing here as duplicate report.

Thanks :)
