### ISSUE TITLE
batch proccess modal window broken

### ISSUE THREAD

**Issue by peteruoi** [joomla/joomla-cms#8539]
joomla 3.5 beta1
tested with Chrome, firefox, ie
When we press the batch button  for both categories and articles and then we press the drop down lists we cannot see all the items. (We can still select them with the down arrow on our keybaord but that not so cool :) )
![batch-moveorcopy](https://cloud.githubusercontent.com/assets/11295832/11409482/f516ed72-93c8-11e5-8aa0-79e59a6d5c17.png)
Maybe @dgt41 can have a look?

**Comment by dgt41** [comment]
I think we fixed that here: https://github.com/joomla/joomla-cms/pull/8373

**Comment by peteruoi** [comment]
@dgt41 sorry for my noobish question. I 'm just new to github and patch testing.
Can you plz tell me where should i download and test the latest joomla version? Cause i downloaded https://github.com/joomla/joomla-cms/releases/tag/3.5.0-beta 
and it was still there. I try use patchtester to install #8373 but it cant find 8373 (maybe cause merged?). Reply if possible so i can do some testing :) thanks in advance!

**Comment by dgt41** [comment]
@peteruoi that's ok, you can try that latest version here https://developer.joomla.org/cms-packages/

**Comment by peteruoi** [comment]
yep. It's fixed :) thanks for instructions! :+1:
