### ISSUE TITLE
Default CSS for Edit Module Button at front site

### ISSUE THREAD

**Issue by beautifultemplates** [joomla/joomla-cms#8548]
I think we should add the default CSS for Edit Module Button at front site instead add it in specify template.

So in template we can override it.

**Comment by zero-24** [comment]
Can you tell use which specific CSS do you mean? Do you mean: `nav menu nav-pills jmoddiv jmodinside` for the button or the CSS that is called later to style the com_config output?

The most can be found here: https://github.com/joomla/joomla-cms/blob/staging/media/system/css/frontediting.css That is in the media folder ;)

**Comment by beautifultemplates** [comment]
You can check this picture, when i use Protostar template, the module editing layout and edit button will have smooth style.

But the styles is defined in templates.css of protostar template, so when i develop new template, i have to write all this style. So i think we should define it in frontediting.css 
![screen shot 2015-11-28 at 11 02 33](https://cloud.githubusercontent.com/assets/16041536/11450033/aa6b3758-95bf-11e5-9f14-647ae45731ca.jpeg)
es again.
 
![screen shot 2015-11-28 at 10 57 56](https://cloud.githubusercontent.com/assets/16041536/11450012/fc3c8b1e-95be-11e5-975c-98a224d552ce.jpeg)

**Comment by bertmert** [comment]
Just to show the relevant CSS-classes. A friend of mine provided the following (ugly) code for templates that don't use bootstrap.

```
/* module editing frontend buttond */
body a.btn.jmodedit:before{
 content:"edit module";
 color:#fff !important;
 background-color:green !important;
 border: 1px solid black !important;
 padding:5px !important;
 font-size:20px !important;
 font-weight:bold !important;
}
 
/* menu editing frontend buttond */
body a.btn.jfedit-menu:before{
 content:"edit menu";
 color:#fff !important;
 background-color:green !important;
 border: 1px solid black !important;
 padding:5px !important;
 font-size:20px !important;
 font-weight:bold !important;
}
```

**Comment by Bakual** [comment]
I don't think template developers will like it when we load frontendedit.css on each pageload (at least when a user with edit permissions is logged in). It may very well break templates because the rules clash with existing rules.

Imho, things like that should be included in each template. We can do an example LESS file where we store the rules we use for Protostar, but I wouldn't do a CSS or load it automatically.

**Comment by beautifultemplates** [comment]
1. The template developer should use the prefix for his template to prevent it from breaking.

2. The default module, plugin, component of Joomla! should look smooth well.

As a template developer, this should help me a lot of time when make a template and it good for clients.

**Comment by Bakual** [comment]
When it's a LESS file, you can just include it in your template with one line. We can also additionally put it as CSS so templates can use import to load it. That's all fine. As long as we don't automatically load it.

**Comment by brianteeman** [comment]
Thank you for your suggestion but it has been decided that this is not something that will be included in the core of Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8548">issues.joomla.org/joomla-cms/8548</a>.</sub>
