### ISSUE TITLE
JFormFieldMedia Not rendering input field

### ISSUE THREAD

**Issue by bcordis** [joomla/joomla-cms#8556]
#### Steps to reproduce the issue

Look at any article image field no output.

#### Expected result

ability to chose image file from media selection.

#### Actual result

No input field rendered.

#### System information (as much as possible)
Setting	Value
 
PHP Built On	Darwin AmyCordsMacBook 15.0.0 Darwin Kernel Version 15.0.0: Sat Sep 19 15:53:46 PDT 2015; root:xnu-3247.10.11~1/RELEASE_X86_64 x86_64
Database Version	5.5.42
Database Collation	utf8_general_ci
PHP Version	5.6.10
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.5.0-beta Beta [ Ember ] 06-November-2015 24:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36

#### Additional comments

Tried to copy from github source no difference.

**Comment by bcordis** [comment]
index.php?option=com_content&view=article&layout=edit&id=1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8556">issues.joomla.org/joomla-cms/8556</a>.</sub>

**Comment by brianteeman** [comment]
Do you mean that you dont have the tab for adding "Images and Links" when front end editing

If that is the case then you need to make sure that you have enabled "Frontend Images and Links"  in the articles options as it is disabled by default

**Comment by bcordis** [comment]
This happens on all edit view on the backend. there is now output of the input field I can't find out any way to get it to show up. all i see is the label and now input. Still trying to find where it is breaking.

**Comment by bcordis** [comment]
Looking through the data at 0394584f6d00674c44049752b26098276f22adb9 there is a big change of code and it has brock the output.

**Comment by brianteeman** [comment]
I can't confirm this

**Comment by bcordis** [comment]
Fixed in latest versions of Joomla 3.5.0 Github. Closing.
