### ISSUE TITLE
Articles:Categories View - Pagination not working

### ISSUE THREAD

**Issue by aantic** [joomla/joomla-cms#8559]
#### Steps to reproduce the issue
Go to Content - Categories to list site Categories. Set pagination in upper right corner to any of the options available such as 5, 10, 20, 100 etc..., click on the pagination links 2,3,4...etc at the bottom

#### Expected result
Should go to page 2 listing of categories

#### Actual result
Only page refresh occurs and nothing else!

#### System information (as much as possible)
PHP Built On: 	Linux server.olympic.rs 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64
Database Version: 	5.5.46
Database Collation: 	latin1_swedish_ci
PHP Version: 	5.4.45
Web Server: 	Apache
WebServer to PHP Interface: 	apache2handler
Joomla! Version: 	Joomla! 3.4.5 Stable [ Ember ] 22-October-2015 21:30 GMT
Joomla! Platform Version :	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0 ![screen shot 2015-11-28 at 04 12 12](https://issues.joomla.org/uploads/1/6621b764a00fff2988deb097b2594d37.jpg)

**Comment by RonakParmar** [comment]
I have followed above steps and not able to reproduce this issue.

System information:
Joomla! Version: Joomla! 3.4.5 Stable [ Ember ] 22-October-2015 21:30 GMT 
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
PHP Version: 5.5.30-1+deb.sury.org~precise+1
System Linux tasol-desktop 3.5.0-54-generic #81~precise1-Ubuntu SMP Tue Jul 15 04:02:22 UTC 2014 x86_64
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8559">issues.joomla.org/joomla-cms/8559</a>.</sub>

**Comment by aantic** [comment]
OK, do you think this has to do with this issue https://github.com/joomla/joomla-cms/issues/8561#issuecomment-160277807

**Comment by RonakParmar** [comment]
I am not able to reproduce this issue https://github.com/joomla/joomla-cms/issues/8561#issuecomment-160277807 

System information:
Joomla! Version: Joomla! 3.4.5 Stable [ Ember ] 22-October-2015 21:30 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
PHP Version: 5.5.30-1+deb.sury.org~precise+1
System Linux desktop 3.5.0-54-generic #81~precise1-Ubuntu SMP Tue Jul 15 04:02:22 UTC 2014 x86_64

**Comment by aantic** [comment]
Definitely when I am at this link administrator/index.php?option=com_categories&view=categories
pagination doesn't work. I have many categories just to mention! 
I checked Module Manager pagination and it works OK!
