### ISSUE TITLE
Cannot Empty Category Trash

### ISSUE THREAD

**Issue by aantic** [joomla/joomla-cms#8561]
#### Steps to reproduce the issue
Select All or only one trashed category. 

#### Expected result
Empty trash

#### Actual result
Page refresh occurs and nothing else

#### System information (as much as possible)
PHP Built On: 	Linux server.olympic.rs 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64
Database Version: 	5.5.46
Database Collation: 	latin1_swedish_ci
PHP Version: 	5.4.45
Web Server: 	Apache
WebServer to PHP Interface: 	apache2handler
Joomla! Version: 	Joomla! 3.4.5 Stable [ Ember ] 22-October-2015 21:30 GMT
Joomla! Platform Version :	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0 

#### Additional comments
I tried fixing, repairing database...

**Comment by brianteeman** [comment]
Did you try clicking on the Rebuild toolbar button in the categories view?

**Comment by aantic** [comment]
I tried rebuilding All Categories, then only Trashed Categories but still cannot empty trash
![categories view rebuild trashed](https://cloud.githubusercontent.com/assets/8791467/11451615/7df1abdc-95cc-11e5-8ce0-422f42347e08.jpg)
![categories view rebuild](https://cloud.githubusercontent.com/assets/8791467/11451616/7df548be-95cc-11e5-88cd-0cac754b43c6.jpg)

**Comment by brianteeman** [comment]
I've seen this before where the asset table is borked

**Comment by RonakParmar** [comment]
I have trashed category and empty trash. That selected category has been deleted.
I have rebuilt database, and not able to see that deleted category, and it is correct.

**Comment by aantic** [comment]
I guess you mean asset table broken - is it possible to fix the asset table?
You are actually right I have no problem deleting newly created categories. The categories that cannot be deleted are trashed categories that were migrated from Joomla 2.5.28 to 3.4.5
How do I find these categories in the asset table?

**Comment by RonakParmar** [comment]
I have migrated Joomla 2.5.28 to 3.4.4 using this document and my new upgraded Joomla 3.4.4 site is working fine after migration. You can follow this steps.
https://docs.joomla.org/Joomla_2.5_to_3.x_Step_by_Step_Migration

**Comment by aantic** [comment]
This is not an issue here. After checking better I had some articles assigned to the trashed categories. That was part of the problem. The other remaining categories that were left over from the migration, I deleted by first changing their alias and then removing them!
