### ISSUE TITLE
303 response code on wrong URLs instead of 404 response code

### ISSUE THREAD

**Issue by Sulpher** [joomla/joomla-cms#8573]
#### Steps to reproduce the issue

I've tested new version of website had to make website offline and work on its SEO and to validate URLs in content.   I turned website offline in global configuration, then log in a front-end under super administrator's credentials and tried to enter any wrong URL.
Correct url: /about-us.html
Incorrect url that I'm trying to enter: /about-us222abcd.html
#### Expected result

I must get 404 response code when input wrong URL. 
#### Actual result

Redirect at index.php with 303 response code. 
#### System information (as much as possible)

I tested it with Joomla 3.4.5
#### Additional comments

It's happen when website is offline and because of these .htaccess rules:
## Begin - Joomla! core SEF Section.
# 

RewriteRule .\* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
# 
# If the requested path and file is not /index.php and the request
# has not already been internally rewritten to the index.php script

RewriteCond %{REQUEST_URI} !^/index.php
# and the requested path and file doesn't directly match a physical file

RewriteCond %{REQUEST_FILENAME} !-f
# and the requested path and file doesn't directly match a physical folder

RewriteCond %{REQUEST_FILENAME} !-d
# internally rewrite the request to the index.php script

RewriteRule .\* index.php [L]
# 
## End - Joomla! core SEF Section.

Please take a look this issue happens when website is offline and you're logged in as user with enough permissions (administrator and above) at front-end side. URLs should work correct in offline too.

**Comment by Sulpher** [comment]
Oh, the .htaccess code was stripped in the message above.

Here is it:

## Begin - Joomla! core SEF Section.
#
RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
#
# If the requested path and file is not /index.php and the request
# has not already been internally rewritten to the index.php script
RewriteCond %{REQUEST_URI} !^/index\.php
# and the requested path and file doesn't directly match a physical file
RewriteCond %{REQUEST_FILENAME} !-f
# and the requested path and file doesn't directly match a physical folder
RewriteCond %{REQUEST_FILENAME} !-d
# internally rewrite the request to the index.php script
RewriteRule .* index.php [L]
#
## End - Joomla! core SEF Section.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8573">issues.joomla.org/joomla-cms/8573</a>.</sub>

**Comment by Sulpher** [comment]
Damn.



I'm attaching the file.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8573">issues.joomla.org/joomla-cms/8573</a>.</sub>

**Comment by Sulpher** [comment]
![screen shot 2015-11-30 at 03 34 09](https://issues.joomla.org/uploads/1/750ef51f2b9af525512b6e9f4e5ebbf3.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8573">issues.joomla.org/joomla-cms/8573</a>.</sub>

**Comment by brianteeman** [comment]
I can confirm this on current staging<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8573">issues.joomla.org/joomla-cms/8573</a>.</sub>

**Comment by mbabker** [comment]
The code in the error handler does a redirect on a 404 condition and the site is in offline mode.  It doesn't account for additional things like whether the user is authenticated.  So if someone wants to fix this, that's the type of check that's needed, otherwise it's expected behavior.

**Comment by franz-wohlkoenig** [comment]
See no Difference between "Site offline" or "Site online": `index.php/menuname/artikelname-not-existing` redirect on `index.php/menuname`.

Tested on:
Joomla! 3.7.0-beta1
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by rvbgnu** [comment]
Looking into it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8573">issues.joomla.org/tracker/joomla-cms/8573</a>.</sub>

**Comment by ghost** [comment]
closed due the lack of Response. It can always reopened if needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8573">issues.joomla.org/tracker/joomla-cms/8573</a>.</sub>
