### ISSUE TITLE
Long article title issue in Breadcrumbs module.

### ISSUE THREAD

**Issue by RonakParmar** [joomla/joomla-cms#8575]
#### Steps to reproduce the issue
Select "protostar" as default template for front-end.
Create article with long title without space.
Login into site, and goto that article detail page.
See, Breadcrumbs module at site bottom having long title of article.

#### Expected result
Article title should be wrapped in Breadcrumbs module div structure.

#### Actual result
Long article title is going out of Breadcrumbs module div structure.

#### System information (as much as possible)
Joomla! Version: Joomla! 3.4.5 Stable [ Ember ] 22-October-2015 21:30 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
PHP Version: 5.5.30-1+deb.sury.org~precise+1
System Linux desktop 3.5.0-54-generic #81~precise1-Ubuntu SMP Tue Jul 15 04:02:22 UTC 2014 x86_64

#### Additional comments
Attached before and after screen dump.![screen shot 2015-11-30 at 06 53 45](https://issues.joomla.org/uploads/1/337666f4507c1debe4e7f2893269a419.png)

![screen shot 2015-11-30 at 06 53 46](https://issues.joomla.org/uploads/1/67ce1604914f3baf23169ab0f45d83f6.png)

**Comment by dodiaraculus17** [comment]
You can try my system, I think you will like it: https://github.com/Tecflare-Corporation/Easy-Large-Websites

**Comment by brianteeman** [comment]
It is NOT a long article title problem it is a user problem. Any real world title would not be a single string of text it would have spaces in it and then it will wrap - it will only not wrap if you have a crazy long string of text for your article title<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8575">issues.joomla.org/joomla-cms/8575</a>.</sub>
