### ISSUE TITLE
Core session code contains database r/w even when not using database

### ISSUE THREAD

**Issue by siliconalchemy** [joomla/joomla-cms#8577]
The core session calls in libraries/cms/application/cms.php - loadSession(), checkSession() contains database code. Session handling shouldn't touch the database per se, only if a db storage provider is used. If 'none' or memcache/redis etc are used then database shouldn't be touched as it pretty much guarantees deadlocks and clashes, and makes Joomla unuseable on consistent db clusters.

I think this is what this PR is trying to fix?
joomla/joomla-cms#6608

Please consider fixing this, it's really important to use Joomla in HA/cluster environment.

**Comment by mbabker** [comment]
All that PR fixes is doing the job of the session handler's `gc()` method.  The [checkSession()](https://github.com/joomla/joomla-cms/blob/3.5.0-beta/libraries/cms/application/cms.php#L164) method needs major rewrites as well.  Going a step further, https://github.com/joomla-projects/joomla-pythagoras/issues/62 identifies all flaws in current session handling code and fixing most of that is probably out of scope for the 3.x series unless there are some developers left who understand session handling and can clean the mess up.

**Comment by dodiaraculus17** [comment]
You can try my system, I think you will like it: https://github.com/Tecflare-Corporation/Easy-Large-Websites

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/pull/13322 makes the recording of session metadata optional in 4.0.  If accepted, that would fix this, if not accepted then architecturally this is a "won't fix" item.  Closing this issue in favor of the PR which would address this.
