### ISSUE TITLE
Email this link to a friend doesn't work with caching enabled

### ISSUE THREAD

**Issue by davidcibeles** [joomla/joomla-cms#8582]
#### Steps to reproduce the issue

Enable cache com_content
Load an article from the front-end component com_content
Open a new private browsing (To generate a new session)
Use "Email this link to a friend" from the icons
#### Expected result

The link is sent to a friend.
#### Actual result

COM_MAILTO_EMAIL_NOT_SENT

/components/com_mailto/controller.php

```
$link     = MailtoHelper::validateHash($this->input->get('link', '', 'post'));

if (!$link || !JUri::isInternal($link))
{
    // Non-local url...
    JError::raiseNotice(500, JText::_('COM_MAILTO_EMAIL_NOT_SENT'));

    return $this->mailto();
}
```
#### System information (as much as possible)

/components/com_content/helpers/icon.php
JHtmlIcon::email

```
line 90: $url = 'index.php?option=com_mailto&tmpl=component&template=' . $template . '&link=' . MailToHelper::addLink($link);
```

MailToHelper::addLink -> adds a URL to the mailto system and returns the hash.
But only in the first session!!
Later the others users will get the hash from the cached file.

/components/com_mailto/controller.php
And when the controller of com_mailto use MailtoHelper::validateHash 

```
Line 61: $mailto_links = $session->get('com_mailto.links', array());
```

This returns an empty array to de new users.

**Comment by dodiaraculus17** [comment]
You can try my system, I think you will like it: https://github.com/Tecflare-Corporation/Easy-Large-Websites

**Comment by infograf768** [comment]
@dodiaraculus17 

Please stop spamming our repo!

**Comment by Kubik-Rubik** [comment]
Spam deleted!

**Comment by bertmert** [comment]
@davidcibeles 
> Enable cache com_content

Where? How?

**Comment by brianteeman** [comment]
I can confirm that if you enable cache
Open an article and then open the same article in a private window
Using "Email this link to a friend" it was sent successfuly in the first window but in the private window I got a "Email could not be sent."
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8582">issues.joomla.org/joomla-cms/8582</a>.</sub>

**Comment by jobwol** [comment]
After mostly every Joomla update I'll get the errors on the option email to a friend. I found my solution on Voodish. You'll search for the file /components/com_mailto/controller.php

Locate the following line of code (approximately line 57):
if($timeout == 0 || time() - $timeout < 20) {

Change the line to the following:

if($timeout == 0 || time() - $timeout **>** 20) {
Save, Upload and test.
You can also increase the time from 20 to say 50.

Tnx to voodish<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8582">issues.joomla.org/tracker/joomla-cms/8582</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Issue still valid.

**Comment by AlexRed** [comment]
I can confirm in Joomla! 3.7.0-staging<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8582">issues.joomla.org/tracker/joomla-cms/8582</a>.</sub>

**Comment by AlexRed** [comment]
I can confirm the problem on Joomla! 3.7.1-dev (nightly Build)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8582">issues.joomla.org/tracker/joomla-cms/8582</a>.</sub>

**Comment by ghost** [comment]
Status is set on "Needs Review".

**Comment by rdeutz** [comment]
Set to pending, it's just a bug

**Comment by alikon** [comment]
i'm unable to reproduce this issue with current staging
![Screenshot from 2019-04-26 13-01-21](https://user-images.githubusercontent.com/181681/56803627-75bd6000-6823-11e9-8a8e-25bf7d7ca9d7.png)

p.s
i'll close this issue in a week if no other feedback

**Comment by ghost** [comment]
@alikon can we close this now as it always can be reopened - easier to manage?

**Comment by alikon** [comment]
closing as it seems no more reproducible 
it always can be reopened if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8582">issues.joomla.org/tracker/joomla-cms/8582</a>.</sub>
