### ISSUE TITLE
css issues

### ISSUE THREAD

**Issue by joo7** [joomla/joomla-cms#8584]
#### Steps to reproduce the issue
hello,

I tested css here: http://www.cssportal.com/css-validator/css-results.php
and the validator found 2 issues in /media/system/css/modal.css (joomla 3.4.5)
maybe this validator is not uptodate but it might be worth looking at?

best regards,
chris

Error: Line 152
Sorry, the at-rule @-moz-document is not implemented.

Error: Line 159 #sbox-window
Value Error : overflow (nullvisufx.html#propdef-overflow) none is not a overflow value

**Comment by dodiaraculus17** [comment]
You can try my system, I think you will like it: https://github.com/Tecflare-Corporation/Easy-Large-Websites

**Comment by joo7** [comment]
hi, thank you for the tipp,
      
      my intention is to help joomla development,
      feel free to use html-/css-validator on your cms,
      
      best regards, chris
      
    
    Am 03.12.2015 um 15:16 schrieb Thomas
      Wilbur:
    
    
      You can try my system, I think you will like it: https://github.com/Tecflare-Corporation/Easy-Large-Websites
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by infograf768** [comment]
@dodiaraculus17 

Please stop spamming our repo!

**Comment by Kubik-Rubik** [comment]
Spam deleted!

**Comment by dodiaraculus17** [comment]
Do you think you can help me on my project?

Date: Thu, 3 Dec 2015 06:36:54 -0800

**Comment by joo7** [comment]
please delete my reply including the spam-link
      too
    
    Am 03.12.2015 um 17:07 schrieb Viktor
      Vogel:
    
    
      Spam deleted!
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by mbabker** [comment]
There's a "report abuse" link on every user profile on GitHub.  Use it, I did.  The guy's account looks to have been suspended.

**Comment by joo7** [comment]
ok, thank you for the hint, best regards, chris
    
    Am 03.12.2015 um 17:43 schrieb Michael
      Babker:
    
    
      There's a "report abuse" link on every user profile on GitHub.
        Use it, I did. The guy's account looks to have been suspended.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by bertmert** [comment]
@joo7 

It's normal that CSS files include browser specific hacks nowadays even if it's not valid CSS (test bootstrap.css! ;-) ).
> Sorry, the at-rule @-moz-document is not implemented.

Contains Firefox specific rules. Other browsers shall ignore them. That's OK there.

> Error: Line 159 #sbox-window Value Error : overflow none is not a overflow value

Should be *hidden* instead of *none* (??)
I couldn't find any browser hack with *overflow: none;*

Provide a pull request! So, anybody is able to test it.
Here's a description:
https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by JoomliC** [comment]
I think we can close this issue as we have a PR : #8595
;-)
