### ISSUE TITLE
if (!class_exists($tableClass)) do not work

### ISSUE THREAD

**Issue by DylanLyu** [joomla/joomla-cms#8585]
Hi,
Sign in the background, the picture appears

Darwin+cfcd208495d565ef66e7dff9f98764da+01+[[]]

i try and tracking.
JTable::getInstance
if (!class_exists($tableClass)) do not work.
It looks like class_exists do not work.

Have any idea this problem occurs..
I use Joomla 3.3 version.

**Comment by dodiaraculus17** [comment]
You can try my system, I think you will like it: https://github.com/Tecflare-Corporation/Easy-Large-Websites

**Comment by mbabker** [comment]
No idea what your actual issue is, but `class_exists()` in general will only work with classes that have already been loaded or are in an autoloaded path.

**Comment by bertmert** [comment]
@DylanLyu 
Your site has been hacked!
