### ISSUE TITLE
php 7.0: Fatal Error: Cannot use 'String' 

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#8588]
#### Error
Fatal Error: Cannot use 'String' as class name as it is reserved in libraries/vendor/joomla/string/src/String.php on line 19

#### Versions
With official release of php 7.0
Joomla 3.5B1

**Comment by mbabker** [comment]
If you are calling `Joomla\String\String` directly you must change your calls to `Joomla\String\StringHelper` (added to Joomla 3.5).  For Joomla 3.4 and earlier compatibility you should call the deprecated `JString` class instead (in 3.4 it extends the `Joomla\String\String` class and 3.5 `Joomla\String\StringHelper`).

See https://github.com/joomla/joomla-cms/pull/6600 for more.

**Comment by 810** [comment]
yes, works thnx

**Comment by stAn47** [comment]
yes, sorry to be loud here, i just downloaded latest joomla from git and all of these are already solved and it's running nicely. 

i am looking forward for j3.4.6

best regards and best wishes, stan
