### ISSUE TITLE
When set to site offline, Joomla! in a subdirectory redirects to domain root

### ISSUE THREAD

**Issue by groovybluedog** [joomla/joomla-cms#8589]
When setting the site offline, I am redirected from the sub domain to the domain root.
This has happened to me for quite a few versions of 3.x but didn't happen in earlier 3.x versions when it was new.
I have fiddled with every server setting and cannot find something on my server that is causing it, so I have to assume that this is an issue with the Joomla! software. Unfortunately I can't test it on another server but I have done everything possible on my own, with no difference. Changing the "Offline Message" setting does nothing either.

#### Steps to reproduce the issue

On a fresh installation of Joomla!, log in to the ACP.
Go to global configuration and enable "Site Offline"
Go to the subdomain Joomla is located in and you are redirected to the domain root.
For example example.com/home is redirected to example.com, but only when the site is offline.

#### Expected result

The type of offline message I have set, such as the default offline message and the login form.

#### Actual result

I am redirected as explained.

#### System information (as much as possible)

http://pastie.org/private/pj1hpd8kd5qsxybuotig

**Comment by brianteeman** [comment]
I cannot replicate this

**Comment by groovybluedog** [comment]
What setup are you using; as in, what Apache/PHP differences do you have in your setup that are different to mine? All I can think of is some sort of Apache/PHP configuration error; even though I have fully met the installation requirements. Nobody on the forums have a clue, so I'm completely stuck.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8589">issues.joomla.org/joomla-cms/8589</a>.</sub>

**Comment by bertmert** [comment]
I think example.com/home is not called a subdomain.
E.g. home.example.com is a subdomain. Set the target of a subdomain like this to the subfolder /home..

See
https://en.wikipedia.org/wiki/Subdomain
> example.com/yn points to a directory within the example.com domain, not to a subdomain of example.com.

**Comment by brianteeman** [comment]
No matter if it should be called a Subdomain or subdirectory it still cannot be replicated.

I am closing this at this time - it can always be reopened if further information to replicate this is provided<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8589">issues.joomla.org/joomla-cms/8589</a>.</sub>
