### ISSUE TITLE
Pagination resets when disable or enable extension

### ISSUE THREAD

**Issue by n9iels** [joomla/joomla-cms#8592]
## The bug
When disable or enable an extension, the pagination resets, and your going back to page one

## How to reproduce
1. Go to Extension -> Manage -> Manage
2. Go to a page number higer than 1
3. Disable or enable an extension

## Expected result
The pagination number is saved, and after disable/enable an extension you stay on the current page

**Comment by brianteeman** [comment]
I can not confirm this with the current staging

**Comment by n9iels** [comment]
I'm sorry didn't test is on staging (Did not had the time, and I usually forget stuff like this :sweat_smile:)
Cose this now
