### ISSUE TITLE
Incorrect usage of "active" on breadcrumb text not menu item

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#8593]
#### Steps to reproduce the issue
Install and activate the Joomla! breadcrumbs module.  Visit a page.  Here is a demo website with it installed.
http://eoindemo.demojoomla.com/index.php/bread-crumbs-content

#### Expected result

Breadcrumbs with the class "active" on the active breadcrumb (page).  

#### Actual result

Active Breadcrumb is active, but text saying "you are here" is also active.  The first li does not need the class active on it (this is hard coded and never changes to inactive).  It's easy to undo with a HTML override, but it should be part of the core, it requires minimal testing and the change took me 20 seconds.

Here is a picture to better explain it.

![screen shot 2015-12-04 at 10 22 43](https://issues.joomla.org/uploads/1/b241a444cd2c54bae98b6cc270499e7b.png)

#### Additional comments

If I could upload a .zip file I would provide this fix for you, since I can't you can locate the issue here.

mod_breadcrumbs/tmpl/default.php

line 17

change 		li class="active" to li (remove the class)

**Comment by bertmert** [comment]
> If I could upload a .zip file I would provide this fix for you, since I can't you can locate the issue here

Try a pull request! So, anybody is able to test your code changes.
Here's a description:
https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by uglyeoin** [comment]
Thanks Bertmert.  Thinking about it, this change may require a change to the standard Joomla! template too.  I will test that and do two pull requests if need be.

**Comment by wojsmol** [comment]
@uglyeoin Any progress on this issue?

**Comment by infograf768** [comment]
I agree on the issue. But indeed this would require an override for Protostar and may change some templates display which do not use an override. Enough to qualify as not B/C, that is the question.

**Comment by uglyeoin** [comment]
I don't know @infograf768 I'm kind of a noob to this stuff.  @wilsonge can you provide information as to whether this is considered breaking b/c?  It is more likely to be templates that suffer than extensions (although not completely impossible).  I would be happy to submit a pull request for the core as well as any template changes for Protostar.  Is it possible to submit both?

**Comment by wilsonge** [comment]
I think it's fine to do. I'd just push it into 3.5 to be safe.

**Comment by uglyeoin** [comment]
Just to avoid additional work, Protostar will remain in J3.5?

**Comment by wilsonge** [comment]
Yes

**Comment by uglyeoin** [comment]
Ok I'll try to understand a pull request and submit one today

**Comment by wilsonge** [comment]
ty!

**Comment by wojsmol** [comment]
@uglyeoin https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests - ping me If you need help :smile:

**Comment by uglyeoin** [comment]
@wojsmol Thanks, I assume by ping you mean just @you ??

**Comment by wojsmol** [comment]
yes :smile:

**Comment by uglyeoin** [comment]
@wojsmol many thanks, I'll see how I go (expect me to ask for help lol)

**Comment by uglyeoin** [comment]
Here are my pull requests:

Joomla! Core (breadcrumbs module)
https://github.com/joomla/joomla-cms/pull/8929

Joomla! Core (protostar template)
https://github.com/joomla/joomla-cms/pull/8930

@wojsmol  I can't believe how easy that was!

**Comment by uglyeoin** [comment]
@bertmert  thanks for the link it was very useful

**Comment by uglyeoin** [comment]
@wojsmol you might want to check I did everything correctly at my end :)

**Comment by wilsonge** [comment]
PR in itself looks fine to me (haven't checked it actually works)

**Comment by uglyeoin** [comment]
@wilsonge cheers for checking the PR.  There goes the PR virginity.  Whoop whoop.

**Comment by infograf768** [comment]
For https://github.com/joomla/joomla-cms/pull/8930 I am not sure the way to go is modifying the css. I am more in favour of an override.

**Comment by wojsmol** [comment]
@infograf768 If we apply override in the protostar then none of templates shipped with Joomla!  will not show the appearance of mod_breadcrumbs based on https://github.com/joomla/joomla-cms/blob/staging/modules/mod_breadcrumbs/tmpl/default.php

**Comment by uglyeoin** [comment]
@infograf768 can you explain why you prefer an override to a less/css change?  I don't mind either way it's about the same amount of work and so long as it all works at the end I am happy.  I would however, prefer to do things the right way and learn for the future, anything you can do to assist is greatly appreciated.

**Comment by brianteeman** [comment]
Closed as issue was resolved with PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8593">issues.joomla.org/joomla-cms/8593</a>.</sub>
