### ISSUE TITLE
Improving asset search with 'alias' and 'id' filters

### ISSUE THREAD

**Issue by dfrassi** [joomla/joomla-cms#8597]
When our site begins to grow , it's really hard to find the information we seek. Besides Joomla it allows searches by title only, and often the titles are duplicated because they belong to different subcategories, when they really could use you can also search for alias and id . this change should be made ​​both on the filters of the lists , both in the secondary filters when it appears the drop down menu to the association of a category to a less , eg.
the lists that appear in the select menu
![selectmenu](https://cloud.githubusercontent.com/assets/897854/11607036/b40030b6-9b37-11e5-912c-b9c60ac6b0c4.jpg)
 of association among other things , it would be appropriate that the alias was shown next to the title , to be able to distinguish assets with duplicate titles

**Comment by brianteeman** [comment]
Showing the alias next to the title as suggested wont help as there is no reason for the alias of two items with the same name to be different if they are in different trees<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8597">issues.joomla.org/joomla-cms/8597</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for your suggestion but it has been decided that this is not something that will be included in the core of Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8597">issues.joomla.org/joomla-cms/8597</a>.</sub>
