### ISSUE TITLE
Improving asset search with 'parent' filter

### ISSUE THREAD

**Issue by dfrassi** [joomla/joomla-cms#8598]
It would be useful to add a filter ( "parent " ) as search criteria in the lists of hierarchical objects ( categories and menus ) . Now you can not understand the entire hierarchy without opening the whole tree and selecting " displays all pages " as a flter for pagination.

![gerarchia](https://cloud.githubusercontent.com/assets/897854/11607092/1c5cc226-9b3a-11e5-9594-8f0959a7b9e1.jpg)

**Comment by andrepereiradasilva** [comment]
there is a "max levels" filter in most of then.

**Comment by dfrassi** [comment]
It would be useful to select a parent and see all the underlying tree

**Comment by brianteeman** [comment]
Thank you for your suggestion but it has been decided that this is not something that will be included in the core of Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8598">issues.joomla.org/joomla-cms/8598</a>.</sub>
