### ISSUE TITLE
batch copy does not keep acl

### ISSUE THREAD

**Issue by peteruoi** [joomla/joomla-cms#8600]
Steps to reproduce the issue
1. create a category.
2. Go to its permission tab and make a change. (e.g registered->allow creating)
3. Go to Batch and Copy it somewhere else.

Expected result
The new category should have the changed permission in it too.

Actual result
It doesn't. It keeps the default.

Additional
The same applies to batch copy for articles too.
The batch move keeps the permissions.
There is an option during batch process that refers to access levels but that's the viewing levels stuff. So as long as there is no specific option shouldn't copy a category mean we copy the specific permissions too?

**Comment by infograf768** [comment]
Indeed. Code does not check/copy for the specific rules applied to the original item(s) (in all batches, not only categories or articles but also menu items, etc.) It could be done but implies quite some work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8600">issues.joomla.org/joomla-cms/8600</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
If batchcopy assets expect a copy, mean same Values also in ACL. An Issue for UX, @cpfeifer?

**Comment by AlexRed** [comment]
I can confirm in Joomla! 3.7.0-staging<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8600">issues.joomla.org/tracker/joomla-cms/8600</a>.</sub>

**Comment by cpfeifer** [comment]
It should keep as many values as possible. If I remember correctly, it's also an issue with nested categories and menu items losing parent item relationships, but it's been awhile since I've had to do that. It would be very helpful and help users avoid more steps.

**Comment by AlexRed** [comment]
I can confirm in Joomla! 3.7.0-RC2 for Category and Articles.
For me we need a message in the batch procedure that explains the copy not keep acl. While now appears "Set Access Level --> Keep original access levels" which can be misleading.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8600">issues.joomla.org/tracker/joomla-cms/8600</a>.</sub>

**Comment by ghost** [comment]
@nurcihandem as you wrote #21325 is this an issue you can look at?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8600">issues.joomla.org/tracker/joomla-cms/8600</a>.</sub>

**Comment by alikon** [comment]
closing as we have pr ready for testing #24730<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8600">issues.joomla.org/tracker/joomla-cms/8600</a>.</sub>
