### ISSUE TITLE
How about showing the select module in Modal

### ISSUE THREAD

**Issue by shamsbd71** [joomla/joomla-cms#8605]
## Description
I got some feedback that whenever we create a module 
1. we had to click "New"
2. It redirect us to a new page
3. We select one of item
4. It redirects us to another page to edit the module or create its instance

## Proposed solution
We can introduce the modal for Select or Chose module. So it will show through a modal with all select module list to create. After i select one of them, its gonna be Redirect to a new page.
so users dont need to go to another page to select a menu each time.

### Visual Presentation
![new_module](https://cloud.githubusercontent.com/assets/1936565/11614779/6f8adc56-9c77-11e5-8b10-7d1a497d34a5.png)

![module_modal](https://cloud.githubusercontent.com/assets/1936565/11614786/7c88f8a2-9c77-11e5-96f9-0512d0845ac1.png)

And after we select anyone of available module, it will change parent location, so would be good i think.

## Comment
I already built it in test. if you think its good i'll create a pull request too :)

**Comment by infograf768** [comment]
I am not sure that displaying the list of possible modules to select in a modal rather than the way it is now would change much in term of speed or UI.
As it is now, we click on New, the select Module page displays, we click on a module and are redirected to the new module to edit. Your proposal would just change the display of the list in a modal instead of the full page.

**Comment by bertmert** [comment]
I don't see any advantages. Displaying things in full width/height is always the better solution. Think of longer tooltips and vertically scrolling. I agree with @infograf768

**Comment by codexpert** [comment]
instead of modal window you can put a search. I really miss a search option there or a filtering

**Comment by brianteeman** [comment]
Pull requests are always welcome and then people will be able to evaluate if they feel its a good idea or not. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8605">issues.joomla.org/joomla-cms/8605</a>.</sub>

**Comment by brianteeman** [comment]
Closing at this time - in the absence of any code to review this is going nowhere<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8605">issues.joomla.org/joomla-cms/8605</a>.</sub>
