### ISSUE TITLE
Installing extensions in current Joomla! branch on PHP7

### ISSUE THREAD

**Issue by Radek-Suski** [joomla/joomla-cms#8609]
I installed Vagrant box with PHP7 and tried to install extension on it. I am getting following error.

#### Steps to reproduce the issue
Trying to install a component

#### Expected result
Successful installation.  

#### Actual result
Error message on a WPoD 
> Notice: upload_max_filesize of 2097152 bytes exceeded - file [install_package=com_sobipro_1.2.1.ES.tar.gz] not saved in Unknown on line 0
> Error displaying the error page: Application Instantiation Error: Failed to start the session because headers have already been sent by "" at line 0.

Memory limit is set to 512 MB

#### System information (as much as possible)

System file attached (no way, text files not allowed. Maybe we could consider to allow these)
https://cloud.sobi.pro/f/364d629c06/

#### Additional comments
Additionally any click inside the extension manager like for example "Add install from web" or trying to install from directory results in error:
> Notice: No file uploaded in Unknown on line 0
Error displaying the error page: Application Instantiation Error: Failed to start the session because headers have already been sent by "" at line 0.

**Comment by mbabker** [comment]
This sounds more like an environmental error than a code bug.  On OS X with PHP 7 installed via Homebrew every extension package I could find on my local system (extensions on the joomla.org sites, my own extensions, work projects, com_patchtester, and a weblinks package) all installed correctly on current staging.

**Comment by Radek-Suski** [comment]
Hmm, ok. I will check it. It was my first thought too (php upload path wrongly configured) but what wonders me is the "add install from web" issue. 
Thanks @mbabker

**Comment by mbabker** [comment]
That's gonna fail until someone updates their XML update manifest to support 3.5.

**Comment by Radek-Suski** [comment]
ok, seem you are right Michael (not that I am surprised). Installed the PHP7 bitnami stack and it works perfectly fine
