### ISSUE TITLE
Unable to click on 'Select' button when trying to create 'New Menu Item' after Upgrading from 3.4.1 to 3.4.5

### ISSUE THREAD

**Issue by Redline260** [joomla/joomla-cms#8613]
#### Steps to reproduce the issue

After logging into Joomla Admin, I select Menus > Main Menu > Add New Menu Item from the top of the page.
Within the 'New Menu Item' screen, when attempting to click on the 'Select' button for a Menu Item Type, The box to choose a menu item does not appear. It flashes up with a second then disappears again. There is no error message shown.

#### Expected result

The Menu Item Box should be displayed to allow a menu type to be chosen ie. article, component etc. 

#### Actual result

The Menu Item Box pops up for a second then disappears. This results in not being able to create any new menus within Joomla

#### System information (as much as possible)
Joomla! Instance :: Joomla! 3.4.5-Stable (Ember) 22-October-2015
Joomla! Platform :: Joomla Platform 13.1.0-Stable (Curiosity) 24-Apr-2013
Joomla! Configured :: Yes | Writable (644) | Owner: e30racin (uid: 1/gid: 1) | Group: e30racin (gid: 1) | Valid For: 3.4
Configuration Options :: Offline: 0 | SEF: 1 | SEF Suffix: 0 | SEF ReWrite: 0 | .htaccess/web.config: Yes | GZip: 0 | Cache: 1 | FTP Layer: 0 | SSL: 0 | Error Reporting: simple | Site Debug: 0 | Language Debug: 0 | Default Access: 1 | Unicode Slugs: 0 | Database Credentials Present: Yes

Host Configuration :: OS: Linux | OS Version: 3.12.18-clouder0 | Technology: x86_64 | Web Server: Apache | Encoding: gzip, deflate | Doc Root: /home/e30racin/public_html | System TMP Writable: Yes

PHP Configuration :: Version: 5.6.16 | PHP API: cgi-fcgi | Session Path Writable: Yes | Display Errors: 1 | Error Reporting: 30709 | Log Errors To: php_errorlog | Last Known Error: 06th December 2015 06:42:12. | Register Globals: | Magic Quotes: | Safe Mode: | Open Base: | Uploads: 1 | Max. Upload Size: 128M | Max. POST Size: 128M | Max. Input Time: 120 | Max. Execution Time: 120 | Memory Limit: 256M

MySQL Configuration :: Version: 5.5.44-37.3-log (Client:5.5.32) | Host: --protected-- (--protected--) | Collation: utf8_general_ci (Character Set: utf8) | Database Size: 13.67 MiB | #of Tables: 255

PHP Extensions :: Core (5.6.16) | date (5.6.16) | ereg () | libxml () | openssl () | pcre () | sqlite3 (0.7-dev) | zlib (2.0) | bcmath () | bz2 () | calendar () | ctype () | curl () | dba () | dom (20031129) | enchant (1.1.0) | hash (1.0) | fileinfo (1.0.5) | filter (0.11.0) | ftp () | gd () | gettext () | SPL (0.2) | iconv () | session () | intl (1.1.0) | json (1.2.1) | ldap () | mbstring () | mcrypt () | mysql (1.0) | mysqli (0.1) | pcntl () | standard (5.6.16) | PDO (1.0.4dev) | pdo_mysql (1.0.2) | pdo_pgsql (1.0.2) | pdo_sqlite (1.0.1) | pgsql () | Phar (2.0.2) | posix () | pspell () | readline (5.6.16) | Reflection ($Id: e1a2c576686e394757985fc88c2e6243ab2bb511 $) | imap () | shmop () | SimpleXML (0.1) | soap () | sockets () | exif (1.4 $Id: a0425de51ec3270d01522bf62d41bfe78893f78d $) | sysvmsg () | sysvsem () | tidy (2.0) | tokenizer (0.1) | wddx () | xml () | xmlreader (0.1) | xmlrpc (0.51) | xmlwriter (0.1) | xsl (0.1) | zip (1.12.5) | cgi-fcgi () | bz2_filter (0.1) | mailparse (2.1.6) | memcache (2.2.6) | memcached (2.2.0) | mhash () | ionCube Loader () | Zend Engine (2.6.0) |
Potential Missing Extensions :: suhosin |

Switch User Environment (Experimental) :: PHP CGI: Yes | Server SU: Yes | PHP SU: Yes | Custom SU (LiteSpeed/Cloud/Grid): Yes
Potential Ownership Issues: No 

Core Folders :: images/ (755) | components/ (755) | modules/ (755) | plugins/ (755) | language/ (755) | templates/ (755) | cache/ (755) | logs/ (755) | tmp/ (755) | administrator/components/ (755) | administrator/modules/ (755) | administrator/language/ (755) | administrator/templates/ (755) | 

Components :: SITE :: com_wrapper (3.0.0) | com_mailto (3.0.0) |
Components :: ADMIN :: com_plugins (3.0.0) | com_cpanel (3.0.0) | com_config (3.0.0) | com_modules (3.0.0) | com_users (3.0.0) | com_languages (3.0.0) | com_cache (3.0.0) | COM_TRACKS (3.0.beta.3.4) | Mailster (0.4.0) | com_admin (3.0.0) | ImageShow (4.8.5) | ImageShow (4.8.5) | [youtube] Gallery (4.2.9) | com_installer (3.0.0) | com_content (3.0.0) | com_redirect (3.0.0) | com_banners (3.0.0) | com_weblinks (3.4.1) | Admintools (3.6.5) | com_templates (3.0.0) | com_newsfeeds (3.0.0) | com_media (3.0.0) | com_tags (3.1.0) | com_postinstall (3.2.0) | com_checkin (3.0.0) | com_ajax (3.2.0) | com_login (3.0.0) | com_jhackguard (2.0.2) | Akeeba (4.4.3) | com_search (3.0.0) | com_finder (3.0.0) | COM_REDCORE (1.6.0) | com_messages (3.0.0) | com_categories (3.0.0) | com_joomlaupdate (3.0.0) | com_menus (3.0.0) | com_contenthistory (3.2.0) |

Modules :: SITE :: JSN ImageShow (4.8.5) | mod_wrapper (3.0.0) | mod_tracks_ranking (3.0.beta.3.3) | mod_breadcrumbs (3.0.0) | mod_finder (3.0.0) | mod_feed (3.0.0) | mod_custom (3.0.0) | MOD_REDCORE_LANGUAGE_SWITCHER (1.6.0) | mod_tags_popular (3.1.0) | mod_search (3.0.0) | mod_articles_latest (3.0.0) | mod_languages (3.0.0) | mod_footer (3.0.0) | mod_whosonline (3.0.0) | mod_tracks_teamsocial (3.0.beta.3.3) | mod_stats (3.0.0) | mod_articles_popular (3.0.0) | Mailster Subscriber (0.4.0) | Mailster Subscriber (0.4.0) | mod_login (3.0.0) | mod_articles_archive (3.0.0) | mod_articles_category (3.0.0) | mod_tracks_team_ranking (3.0.beta.3.3) | MOD_MH_SIMPLE_MARQUEE (rev 32) | mod_articles_categories (3.0.0) | mod_random_image (3.0.0) | [youtube] Gallery Module (4.2.9) | mod_syndicate (3.0.0) | mod_tracks_results (3.0.beta.3.3) | mod_weblinks (3.4.1) | mod_banners (3.0.0) | mod_tags_similar (3.1.0) | mod_articles_news (3.0.0) | mod_users_latest (3.0.0) | mod_menu (3.0.0) | mod_related_items (3.0.0) |
Modules :: ADMIN :: JSN ImageShow Quick Icons (4.8.5) | mod_quickicon (3.0.0) | mod_feed (3.0.0) | mod_custom (3.0.0) | mod_logged (3.0.0) | mod_multilangstatus (3.0.0) | mod_popular (3.0.0) | mod_submenu (3.0.0) | mod_title (3.0.0) | mod_login (3.0.0) | mod_version (3.0.0) | mod_status (3.0.0) | mod_stats_admin (3.0.0) | mod_toolbar (3.0.0) | mod_menu (3.0.0) | mod_latest (3.0.0) |

Plugins :: SITE :: plg_installer_webinstaller (1.0.5) | JHackGuard Plugin (2.0.2) | PLG_SYSTEM_MVC_OVERRIDE (1.4.10) | System - JSN ImageShow (4.8.5) | plg_system_log (3.0.0) | plg_system_cache (3.0.0) | plg_system_redirect (3.0.0) | plg_system_highlight (3.0.0) | plg_system_languagecode (3.0.0) | plg_j25_legacy (1.1) | plg_system_remember (3.0.0) | PLG_SYSTEM_REDCORE (1.6.0) | plg_system_sef (3.0.0) | System - jSGCache (1.3.0) | plg_system_p3p (3.0.0) | plg_system_logout (3.0.0) | plg_system_jsnframework (1.4.2) | System - Admin Tools (3.6.5) | plg_system_debug (3.0.0) | plg_system_languagefilter (3.0.0) | plg_editors-xtd_image (3.0.0) | PLG_TRACKS_INDIVIDUAL_EDITORXT (3.0.beta.3.3) | Button - ImageShow (4.8.5) | plg_editors-xtd_readmore (3.0.0) | plg_editors-xtd_article (3.0.0) | plg_editors-xtd_pagebreak (3.0.0) | plg_captcha_recaptcha (3.4.0) | Source Picasa (1.1.6) | Theme Classic (1.3.1) | PLG_REDPAYMENT_PAYPAL (1.6.0) | plg_twofactorauth_yubikey (3.2.0) | plg_twofactorauth_totp (3.2.0) | plg_finder_tags (3.0.0) | plg_finder_categories (3.0.0) | plg_finder_newsfeeds (3.0.0) | plg_finder_content (3.0.0) | plg_finder_contacts (3.0.0) | plg_finder_weblinks (3.4.1) | plg_content_geshi (2.5.0) | plg_content_emailcloak (3.0.0) | Content - [youtube] Gallery (4.2.9) | Content - JSN ImageShow (4.8.5) | plg_content_pagenavigation (3.0.0) | plg_content_loadmodule (3.0.0) | plg_content_finder (3.0.0) | plg_content_pagebreak (3.0.0) | Simple Image Gallery (by Jooml (3.0.1) | Simple Image Gallery (by Jooml (3.0.1) | plg_content_vote (3.0.0) | plg_content_joomla (3.0.0) | plg_extension_joomla (3.0.0) | plg_editors_tinymce (4.1.7) | plg_editors_codemirror (5.6) | plg_search_tags (3.0.0) | plg_search_categories (3.0.0) | plg_search_newsfeeds (3.0.0) | plg_search_content (3.0.0) | Search - Tracks (3.0.beta.3.3) | plg_search_contacts (3.0.0) | plg_search_weblinks (3.4.1) | plg_authentication_ldap (3.0.0) | plg_authentication_gmail (3.0.0) | plg_authentication_cookie (3.0.0) | plg_authentication_joomla (3.0.0) | plg_user_contactcreator (3.0.0) | plg_user_profile (3.0.0) | PLG_USER_TRACKS_AUTOREGISTER (3.0.beta.3.3) | plg_user_joomla (3.0.0) | plg_quickicon_extensionupdate (3.0.0) | plg_quickicon_joomlaupdate (3.0.0) | 

Templates :: SITE :: protostar (1.0) | siteground-j15-190 (1.0.0) | blog-sunny-orange (1.0) | blog-sunny-blue (1.0) | Siteground-j16-4 (1.0.0) | beez3 (3.1.0) | Clever (3.2) |
Templates :: ADMIN :: isis (1.0) | hathor (3.0.0) |

![screen shot 2015-12-08 at 05 20 26](https://issues.joomla.org/uploads/1/91c563c38f9831357b01c9b670a24425.jpg)

**Comment by Bakual** [comment]
Try first to clear browser caches and see if that fixes the issue. It's most likely a local browser issue.

**Comment by Redline260** [comment]
Hello, I have tried this and have had no success. I have tried using IE, Firefox and Chrome with no success. I can restore from backup to a previous version of Joomla (3.4.1) and can create menu items fine

**Comment by Bakual** [comment]
It's either a local issue or a broken update.
It's not a core issue.
