### ISSUE TITLE
3.5.0 Beta Protostar has menu assignments.

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#8622]
I' ve installed staging of today.

I wonder about menu assignments in Protostar template. Aren't these menu items normally assigned in Beez3?

![protostar-assigned](https://cloud.githubusercontent.com/assets/11038612/11665487/02c42862-9de8-11e5-996b-616aa733145f.jpg)

![protostar-assigned-2](https://cloud.githubusercontent.com/assets/11038612/11665499/083ec568-9de8-11e5-9622-e82df30a7849.jpg)

**Comment by brianteeman** [comment]
Thats the testing sample data - always been that way
