### ISSUE TITLE
JSortableList : cannot use input text other than order[]

### ISSUE THREAD

**Issue by NetAssoPro** [joomla/joomla-cms#8627]
#### Steps to reproduce the issue
Create a table and use JHtml::_('napcsortablelist.sortable');
In columns use some input or chosen list (because it generate a input text)

#### Expected result
Order normally without alter values in the input text.

#### Actual result
All values in imput text are altered

#### Additional comments

You need to update sortablelist.js and replace all the '[type=text]' by a class or catch by the name '[name="order[]"]'

**Comment by kaareloun** [comment]
+

**Comment by zero-24** [comment]
@NetAssoPro I'm not sure what do you try to do but `JHtml::_('napcsortablelist.sortable');` looks not like a Core feature? Maybe there is a 3rdparty extension / plugin?

Or do you mean: `JHtml::_('sortablelist.sortable');` -> Core API: https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/html/sortablelist.php#L41

**Comment by franz-wohlkoenig** [comment]
Is this still an Issue?

**Comment by NetAssoPro** [comment]
The problem exist for JHtml::_('sortablelist.sortable');

**Comment by brianteeman** [comment]
Please provide extra details for how to replicate this and why this is a problem otherwise this will be closed in a few weeks time

**Comment by Quy** [comment]
@brianteeman OK to close?

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 28th February 2018.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8627">issues.joomla.org/tracker/joomla-cms/8627</a>.</sub>
