### ISSUE TITLE
3.5.0 Beta. Install from Web: Unable to find install package

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#8628]
Maybe "known".

Test:
Install staging (Beta 3.5.0).
Go to Extensions > Manage > Install.
Click button "Add Install from Web tab".
==>
Error: Unable to find install package

The button
```
<button ... onclick="Joomla.submitbuttonInstallWebInstaller()">...</button>
```
The function calls
```
http://appscdn.joomla.org/webapps/jedapps/webinstaller.xml
```
which is available.
Also the package
```
http://appsserver.joomla.org/webapps/jedapps/downloads/plugin/plg_webinstaller_3.2v1.0.5.zip
```
that I could install via "Install from URL" without problems.

**Comment by brianteeman** [comment]
Indeed it is a known issue that @beat said would be fixed last month #8314
