### ISSUE TITLE
Joomla Date field Validation not working properly

### ISSUE THREAD

**Issue by durr04** [joomla/joomla-cms#8646]
#### Steps to reproduce the issue
1. Go to Joomla administrator Panel
2. Go to Content -> Article Manager 
3. Click on Create New Article Button
4. Insert any sample data
5. Go To Publishing Tab
6. Select Any date for Start publishing & Finish Publishing
7. Add any raw value in the date field (eg Any string like 'abcd1234')
8. It throws out error
 
Please check the screenshot attached

#### Expected result
IT should give validation message for wrong date 

#### Actual result
IT gives out error

#### System information (as much as possible)

![screen shot 2015-12-11 at 00 10 36](https://issues.joomla.org/uploads/1/67f3c6233d572b0502b4a95764c9b288.png)

**Comment by ggppdk** [comment]
Currently the filtering does not catch exceptions,
- same problem with the calendar field

see here: #8093

**Comment by joomdonation** [comment]
Hi

I made a PR to fix this issue. Please help testing https://github.com/joomla/joomla-cms/pull/8656 when you have some free time

**Comment by brianteeman** [comment]
Closing as we have a PR #8656 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8646">issues.joomla.org/joomla-cms/8646</a>.</sub>
