### ISSUE TITLE
showon: "not equal" or allow regular expressions

### ISSUE THREAD

**Issue by cn-tools** [joomla/joomla-cms#8647]
is it possible to get a condition "not equal" or maybe using the regular expression?

i use field type "filelist“ with option hide_none="0".
if the user select an item in the list filled by regular expression, i would like to see an additional field after file list. But at the developing time i don't know which files are available later.

**Comment by rdeutz** [comment]
Please ask you question in the forum (http://forum.joomla.org), issues on github is only for bugs
