### ISSUE TITLE
new ConfigModelApplication::storePermissions should use existing API

### ISSUE THREAD

**Issue by klas** [joomla/joomla-cms#8650]
New ConfigModelApplication::storePermissions reads and writes assets database table directly. 
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/model/application.php#L348
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/model/application.php#L416

Those queries should be replaced by usage of existing  API from JTableAsset , also we should avoid direct coupling with db structure here.
E.g. first query can be replaced by JTableAsset::loadByName

**Comment by brianteeman** [comment]
Closed as we have a PR #8651 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8650">issues.joomla.org/joomla-cms/8650</a>.</sub>
