### ISSUE TITLE
Error: You can't access the private section of this site.

### ISSUE THREAD

**Issue by alve89** [joomla/joomla-cms#8659]
I wrote an authentication plugin for Joomla 3.4.5. After logging in (with no other auth-plugins enabled) I got this message:

> You can't access the private section of this site.

First I thought this was a problem of my plugin, so I changed it to the following:

     public function onUserAuthenticate($credentials, $options, & $response)
     {
          $response->error_message = '';
          $response->fullname = 'Max Mustermann';
          $response->email	= 'mymail@domain.tld';
          $response->username = 'username';
          $response->status	= JAuthentication::STATUS_SUCCESS;
     }

So actually I should be authenticated immediately. But I still get the error message from above.

It's a absolutely fresh installation of Joomla with two main entries - one is set to "Public", the other one to "Registered".

Why can't I login?

**Comment by alve89** [comment]
I forgot to set the permission for guests to be allowed to login on frontend, so it is working fine now.
But is there a possibility to set which user-group a logged in user is allocated to?

**Comment by brianteeman** [comment]
The best place to discuss this is on the mailing list https://groups.google.com/forum/#!forum/joomla-dev-general
