### ISSUE TITLE
No logout after click on button

### ISSUE THREAD

**Issue by alve89** [joomla/joomla-cms#8660]
I wrote a simple authentication plugin (and the authentication works fine). But I can't logout using the logout-button.
I set the error_reporting level to maximum but I don't get any information why logging out doesn't work.

Could anyone give some hints please?

**Comment by brianteeman** [comment]
Please use the forum(http://forum.joomla.org) or the general developer mailing list (https://groups.google.com/forum/#!forum/joomla-dev-cms)
