### ISSUE TITLE
Regression - ordering broken in Newsfeed and Tags

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#8661]
Since the change to combine the two ordering selects into a single select (field plus direction) the ordering is completely broken

To test - install latest staging with sample data
Go to newsfeeds and try to sort by ID Ascending or ID Descending. The order should change but it doesnt
Go to tags and try to sort by ID or Title.  The order should change but it doesnt

**Comment by brianteeman** [comment]
Updated to include tags component<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8661">issues.joomla.org/joomla-cms/8661</a>.</sub>

**Comment by Bakual** [comment]
Do you know which PR it was that changed this select? Was it part of the Smart Search implementation?

**Comment by brianteeman** [comment]
Not had a chance to check but I would suspect so.
The problem probably came when the ordering select was changed from two boxes (field and direction) to the combined box

I discovered it while trying to create a single select for the two remaining places where there is a double select (banner-tracks and content-languages) and couldnt work out why it wasnt working

**Comment by bertmert** [comment]
Just had a short look
1.)
```
<input type="hidden" name="filter_order" value="<?php echo $listOrder; ?>" />
<input type="hidden" name="filter_order_Dir" value="<?php echo $listDirn; ?>" />
```
must be removed from default.php.

```
$sortFields = $this->getSortFields();
```
should be removed

JavaScript block
```
Joomla.orderTable = function()
```
should be removed

All
```
JHtml::_('grid.sort', 
```
must be
```
JHtml::_('searchtools.sort'
```

We had a similiar issue in com_contact some days ago.

**Comment by brianteeman** [comment]
Can you do a PR for Newsfeeds and Tags please - might be needed in other places but didnt spot any

**Comment by bertmert** [comment]
OK.

**Comment by brianteeman** [comment]
Thanks

**Comment by Bakual** [comment]
Personally I would prefer the two box select as I think the single box is getting confused with such many options. But that's me.
It's for sure better to be consistent and working obviously :smile:

**Comment by brianteeman** [comment]
See #8670 for a fix for Newsfeeds

**Comment by brianteeman** [comment]
Closed as we have  PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8661">issues.joomla.org/joomla-cms/8661</a>.</sub>
