### ISSUE TITLE
Associations ordering in menu item select

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#8665]
Install Joomla with multiple languages and in the menu manager you can order by "associations" from the select box

Install Joomla with a single language and in the menu manager you should not see the option to order by association from the the select box - but you do still have the option to sort by "Association descending"

At a guess the "requires" here https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/models/forms/filter_items.xml#L84 is only working on the first instance

**Comment by infograf768** [comment]
It's just a typo.
Please test https://github.com/joomla/joomla-cms/pull/8675

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8665">issues.joomla.org/joomla-cms/8665</a>

**Comment by infograf768** [comment]
Closing as we have a patch https://github.com/joomla/joomla-cms/pull/8675<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8665">issues.joomla.org/joomla-cms/8665</a>.</sub>
