### ISSUE TITLE
REGRESSION user notes userid

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#8667]
Testing in current staging when creating a user note the field for the User is marked as required but you can still save a note with selecting a user - making the whole thing useless

Previously it was not possible to save a user note without completing the required field

**Comment by brianteeman** [comment]
It seems to be ignoring the required="true" in the note.xml
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8667">issues.joomla.org/joomla-cms/8667</a>.</sub>

**Comment by infograf768** [comment]
Maybe this needs a special case in the model in LoadFormData

**Comment by infograf768** [comment]
I think it comes from https://github.com/joomla/joomla-cms/pull/5655

@dgt41 Please look at this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8667">issues.joomla.org/joomla-cms/8667</a>.</sub>

**Comment by dgt41** [comment]
@infograf768 more likely it's coming from: https://github.com/joomla/joomla-cms/pull/5655
I will look at this later on as I am awfully busy now

**Comment by dgt41** [comment]
For testing try adding `required"` after
https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/html/layouts/joomla/form/field/user.php#L53

**Comment by brianteeman** [comment]
No that doesnt do anything - thanks for taking a look

On 29 January 2016 at 13:25, Dimitri Grammatikogianni <
notifications@github.com> wrote:

> For testing try adding required" after
>
> https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/html/layouts/joomla/form/field/user.php#L53
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8667#issuecomment-176752625>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Closed as we have a Pr #9037 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8667">issues.joomla.org/joomla-cms/8667</a>.</sub>
