### ISSUE TITLE
Regression - Missing Error message - Com_messages

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#8669]
#### Steps to reproduce the issue
Go to Messages
Create New
Select "No user" as recipient
Enter Title and Subject
Click Send

#### Expected result
Error message that I need to select a user (although I'm not sure why there is a No User option)

#### Actual result
Empty error div

In 3.4.5 you would get an error message
Save failed with the following error: Invalid recipient

**Comment by infograf768** [comment]
The issue comes from this PR
https://github.com/joomla/joomla-cms/pull/5655

**Comment by bertmert** [comment]
I think here we should have

data-user-value="0"

https://github.com/joomla/joomla-cms/pull/5655/files#diff-50a8d2f3be40f3d2de5632473437af2cR28

**Comment by bertmert** [comment]
> although I'm not sure why there is a No User option

Because same modal view is used e.g. in article edit (Created by) or contact edit and the fields are readonly.

**Comment by bertmert** [comment]
See PR https://github.com/joomla/joomla-cms/pull/8678 and test please.

**Comment by brianteeman** [comment]
Closed as we have a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8669">issues.joomla.org/joomla-cms/8669</a>.</sub>
