### ISSUE TITLE
Joomla! 3.4.5 : Uncaught TypeError: Cannot read property 'task' of null at Core.js 1

### ISSUE THREAD

**Issue by TOuhrouche** [joomla/joomla-cms#8677]
I am having tons of issues creating any new item (articles, menu items...) after I upgraded my joomla installation to 3.4.5. 
For example, when I try to create a menu item or a new article, I get `Uncaught TypeError: Cannot read property 'task' of null`. After doing some research, it turns out the issue is coming from this form not having an id named `adminForm`:
`<form action="..." method="post" name="adminForm" id="item-form" class="form-validate">
...
</form>`  
Anyone got a clue of what can this be and how to fix it?

**Comment by ggppdk** [comment]
Your browser may be using old JS / Files
In pages that you have JS error did you force latest JS / CSS to be downloaded ?
PC: CTRL-F5
Safari: CMD + R
Linux: F5

**Comment by TOuhrouche** [comment]
Yes I did try a force reload of all my resources using the Chrome dev tools. I also tried purging expired files on Joomla but did not help.

**Comment by brianteeman** [comment]
Can you please confirm if you are still having this issue now that you have updated to 3.4.7 - I suspect that your upgrade to 3.4.5 may not have been successful or that you are having asset cache issues as we have seen no other reports of this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8677">issues.joomla.org/joomla-cms/8677</a>.</sub>

**Comment by TOuhrouche** [comment]
I tried everything I could to make it work but the problem persisted. I even uninstalled Joomla and reinstalled it over again, no luck. The issue seemed to be coming from data saved with the previous Joomla site. At last, I had to just delete all my database content and create everything from scratch :(

**Comment by izharaazmi** [comment]
@TOuhrouche Changing following should fix it, as you correctly discovered. But I wonder why it so happened in core in the first place; and that on Joomla update!
 
```html
<form action="..." method="post" name="adminForm" id="item-form" class="form-validate"> 
```
to
```html
<form action="..." method="post" name="adminForm" id="adminForm" class="form-validate"> 
```

Can you tell us which file(s) this code excerpt is from? Your old Joomla version before this update?

**Comment by brianteeman** [comment]
As the reporter has now resolved their issue I am closing this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8677">issues.joomla.org/joomla-cms/8677</a>.</sub>

**Comment by developementadda** [comment]
Thank you so much.
Its working fine for me. You saved me lot of time.
