### ISSUE TITLE
email cloaking

### ISSUE THREAD

**Issue by mjt78** [joomla/joomla-cms#8682]
#### Steps to reproduce the issue
Hi,
I have written a form vith an input type= email, with an initial value, like this:
<td> <?php echo	 "<input type='email' id='email1' name='email1' size='20' value='".$email1."' required />";?></td>

The generated code is the following:

<input id="email1" type="email" javascript'="" text="" value="<span id="cloak57499">Cette adresse e-mail est protégée contre les robots spammeurs. Vous devez activer le JavaScript pour la visualiser.</span><script type=" size="20" name="email1" ffpdm="y1mi0xlcronyrq87moof6p">

It is not correct; I think that in this case,it is not mandatory to activate the cloaking plugin.
Regards

**Comment by brianteeman** [comment]
Closing as nothing to do <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8682">issues.joomla.org/joomla-cms/8682</a>.</sub>
