### ISSUE TITLE
Relative URLs are not converted to absolute URLs in atom feed

### ISSUE THREAD

**Issue by skrwt** [joomla/joomla-cms#8683]
The atom feed does not convert relative URLs to absolute URLS inside the **content tag**.

Previously it did not convert them at all, which was fixed by this pull request https://github.com/joomla/joomla-cms/pull/3754.
However it was only fixed for the **summary tag**.

This leads to several problems, e.g. images with relative URLs are not displayed in RSS Readers (tested in Thunderbird 38.4.0), because the relative URL cannot be resolved.

I think the fix needs to be done [here on line 181](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/document/feed/renderer/atom.php#L181) and is trivial. 

Unfortunately I do not have resources to do a pull request right now.

**Comment by bertmert** [comment]
@Tobias2200 
>  I do not have resources to do a pull request

See:
https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by brianteeman** [comment]
Closed as we have a PR - please test #8726<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8683">issues.joomla.org/joomla-cms/8683</a>.</sub>
