### ISSUE TITLE
mod_articles_category settings update has broken display

### ISSUE THREAD

**Issue by jonboutell** [joomla/joomla-cms#8687]
The file 

    /modules/mod_articles_category/mod_articles_category.php

Pulls in the parameter "item_heading" on line 69. This is expected to be, and in the past was, an integer of the heading level (defaults to 4).

    $item_heading               = $params->get('item_heading');

Currently, when you create an articles_category module, the parameter (found under advanced tab) has been changed to header tag (param name "header_tag"). This is instead a string representation of the header to use, e.g. "h4".

This makes the module produce erroneous HTML. 

E.g.

    <div class="moduletable">
        <h3>Test Module</h3>
        <ul class="category-module">
            <li class="">
                **<h>**
                    <a class="mod-articles-category-title " href="/latest-news/open-days.html">
                        Open days and events
                    </a>
                **</h>**    
            </li>
        </ul>
    </div>

**Comment by bertmert** [comment]
> param name "header_tag"

This is NOT the Tag used inside the module. Just for headline above the module if you select a module style like xhtml or html5.

The strange thing is that the old param **item_heading** of the module itself was removed a longer time ago.
Don't remember but think an early 3 version. 
The guy who did it never answered to the question why.
He also removed the headline output from default.php but left code like you describe.

**Comment by jonboutell** [comment]
Quite right, didn't notice the old default override I had on :)
