### ISSUE TITLE
Upgrade 3.0>3.6 package keeps giving me a: Fatal error on line 165

### ISSUE THREAD

**Issue by Nuwie3944** [joomla/joomla-cms#8699]
Hi,
I am trying to upgrade and when I try install the upgrade package through the URL I get this message:

Fatal error: Maximum execution time of 30 seconds exceeded in ...public_html/backup/libraries/joomla/archive/tar.php on line 165

Can anyone help?

**Comment by brianteeman** [comment]
You should be doing an update using the Joomla Update component 

If you still have an issue then you can try to increase the maximum execution time on your server

Please use the forum (http://forum.joomla.org) for any further support

**Comment by Nuwie3944** [comment]
Yeah but the Joomla Update is giving me a 0 HTTP response message so I can't use that.
