### ISSUE TITLE
[3.4] Session Tokens (for spam prevention? looks like CSRF) are Predictable

### ISSUE THREAD

**Issue by paragonie-scott** [joomla/joomla-cms#8710]
https://github.com/joomla/joomla-cms/blob/952f2a6e68d300cfa5b041b50c0def56fb769fc4/libraries/joomla/session/session.php#L758-L780

[How to securely generate random ints and strings in PHP](https://paragonie.com/blog/2015/07/how-safely-generate-random-strings-and-integers-in-php)

Don't use `rand()`.

**Comment by mbabker** [comment]
See #8714

Unless there are characters in `JUserHelper::genRandomPassword()` that for whatever reason couldn't validate as a CSRF token that occasionally is included as part of a URL, just using that (which uses `random_bytes()`) is good enough.

**Comment by paragonie-scott** [comment]
Right. PR incoming.

**Comment by paragonie-scott** [comment]
Oh whoops, I didn't see your commit.

**Comment by paragonie-scott** [comment]
Yeah, I think `genRandomPassword()` is the way to go here.
