### ISSUE TITLE
Fix please Joomla.isChecked(this.checked);

### ISSUE THREAD

**Issue by denverkurt** [joomla/joomla-cms#8720]
Joomla 3

function return invalid value - '01-11-11-11-11-111111-1-1-1-1-1', because it calculates the result as a string
![screen shot 2015-12-17 at 00 45 12](https://issues.joomla.org/uploads/1/3b97dccd5c18ab2bae2ed68b2b248816.png)

**Comment by Fedik** [comment]
fix is there #8590

**Comment by brianteeman** [comment]
Thanks for reporting this. As @fedik mentioned a fix is already prepared and just needs a maintainer to merge it 
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8720">issues.joomla.org/joomla-cms/8720</a>.</sub>

**Comment by denverkurt** [comment]
Thanks
