### ISSUE TITLE
Category List menu item - article title link not clickable with registered access and show unauthorized link

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#8724]
#### Steps to reproduce the issue
Create a category and an article inside. Set article access to registered and set the read more separation in the article content to distinguish introtext from fulltext.
Create a menu item of type "Category List" referring to that category and with "Show unauthorized links" to YES.

#### Expected result
In the frontend article list, the article title should be a link to the article so that guest users can click on it and see the introtext.

#### Actual result
In the frontend article list, the article title is NOT clickable, there is instead a "Register to read more" link, so it is impossible to guest users to see the public introtext.

#### System information (as much as possible)
Joomla 3.4.6

**Comment by sovainfo** [comment]
Suspect this to work for a menu item type Category Blog because it shows intro's. Not expecting this to work for a list. The link would go to the article instead of a blog!

**Comment by Giuse69** [comment]
It does work for Category Blog but not for Category List and I think it should: the link goes to the article that should be shown as introtext to guest. Infact try this: change Access of the article to "Public" => in the Category List the article title has the link to the article view. Now change back access to "Registered" => in the Category List the article title loses the link, that's the problem: the title should remain as a link.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8724">issues.joomla.org/joomla-cms/8724</a>.</sub>

**Comment by sovainfo** [comment]
Again, it works as designed. The link is only provided when you have access to the content. The exception is for the blog view intro that provides the teaser. Trying to enable it for the list requires a technical redesign that people don't consider worth it. 

Even when you provide the technical redesign ( the code ) doubt whether it will be considered.

**Comment by brianteeman** [comment]
Thanks for submitting this issue but as stated this is the expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8724">issues.joomla.org/joomla-cms/8724</a>.</sub>
