### ISSUE TITLE
Register to read more => Login to read more

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#8725]
#### Steps to reproduce the issue
Message "Register to read more" should be "Log in to read more" since actually the link refers to login page, not to registration page.
COM_CONTENT_REGISTER_TO_READ_MORE
MOD_ARTICLES_CATEGORY_REGISTER_TO_READ_MORE

**Comment by sovainfo** [comment]
Considering that this functionality is provided as a teaser for unregistered users, think the message is appropriate for 99% of the cases. 

Technically you are correct that the requirement is to login. Expecting to have the proper authority once logged in. Obviously, you need to be registered for logging in. It is expected that users already registered know to only do this once and provide the login information. Those not registered are reminded to do so. Suggest to create a language override for those messages when that is not your use case. 

Wonder whether you should be using this feature in the first place! 
Hope you realize you might be exposing information you would expect to be protected.

**Comment by Giuse69** [comment]
Yes, I know, but even Joomla tooltip says in that option "You will need to log in to access the full item". It does not say "You will need to register to access the full item"; that's why I think this is not technically consistent and very easy to fix/align :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8725">issues.joomla.org/joomla-cms/8725</a>.</sub>

**Comment by sovainfo** [comment]
Even the tooltip is incorrect! 
You currently are not authorised. You need to change your situation so you gain that authorisation.
What you need to do is depending on your implemention. It is not possible to provide instructions that cover all situations. Which is why it covers the most common situation.

Again, use overrides when your situation is different. Don't consider this to be fixed. It can only be changed in something that is wrong for some situations as well. So, not possible to fix!

**Comment by creativeprogramming** [comment]
I agree with @Giuse69, the required action to get authorized is to login not register, implicitly, if not registered, you should register before (but it's not mandatory to register, e.g. Joomla got LDAP plugin and can have SSO plugins, in some sites registration is turned off, but users are just asked to login to see some content).

**Comment by sovainfo** [comment]
@creativeprogramming No, logging in is not getting you authorized. Not even when you managed to configure your site for SSO or LDAP (even more rare cases!). It simply gives you different authorization, if at all, not neccessarily the authorization required.

Again, the message is for the most common situation, not for the exceptional cases as mentioned above.
Feel free to use overrides when your situation is different.

**Comment by Giuse69** [comment]
@sovainfo well, that is your opinion: actually what makes the rest of the content being accessible is logging-in, not registering (if you are registerd but not logged in => you will not access the content.
Other proof is that clicking on the "register to read more" link the user is presented with the login form and only below there is an option to also register if the login is not possible.
Anyway I know how to override language but I thought it was useful for the coders to be more precise in this message, that's why I opened this thread. I won't insist anymore and leave the coders to decide, I will be happy in both cases :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8725">issues.joomla.org/joomla-cms/8725</a>.</sub>

**Comment by brianteeman** [comment]
Setting to needs review for a decision to be made to either make a change or to maintain the status quo. Otherwise it will go round in circles<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8725">issues.joomla.org/joomla-cms/8725</a>.</sub>

**Comment by chrisdavenport** [comment]
Debatable, but I see no reason to change it at this time.  A language string override is available if anyone wants to change it on their website.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8725">issues.joomla.org/joomla-cms/8725</a>.</sub>

**Comment by chrisdavenport** [comment]
Set to "closed" on behalf of @chrisdavenport by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8725">issues.joomla.org/joomla-cms/8725</a>
