### ISSUE TITLE
PHP 7 Readiness

### ISSUE THREAD

**Issue by AviMoto** [joomla/joomla-cms#8729]
#### Steps to reproduce the issue
There are class with reserved name "String", this cause to PHP fatal error in PHP version 7.0.0, the class used in the Joomla Output filter in the functions OutputFilter::stringURLSafe OutputFilter::stringURLUnicodeSlug

#### System information (as much as possible)
Web Server: Apache 2.4.17
PHP version: 7.0.0

**Comment by Kubik-Rubik** [comment]
Already fixed in 3.5 Beta 1 (Staging branch).

Though, thank you for reporting it!
