### ISSUE TITLE
Unable to display tags below content by setting Position of Article info to Below

### ISSUE THREAD

**Issue by aantic** [joomla/joomla-cms#8732]
#### Steps to reproduce the issue
In Articles:Options set Position of Article Info to Bottom or Split

#### Expected result
Show tags in below the article

#### Actual result
Tags are not visible

#### System information (as much as possible)
PHP Built On 	Linux server.olympic.rs 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64
Database Version 	5.5.46
Database Collation 	latin1_swedish_ci
PHP Version 	5.4.45
Web Server 	Apache
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.4.6 Stable [ Ember ] 15-December-2015 11:11 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0 

#### Additional comments
When Position of Article Info was set to Above the Tags show as expected above article

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8732">issues.joomla.org/joomla-cms/8732</a>.</sub>

**Comment by brianteeman** [comment]
Reset priority according to the documentation https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8732">issues.joomla.org/joomla-cms/8732</a>.</sub>

**Comment by brianteeman** [comment]
closing as we have a PR - please test #9105<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8732">issues.joomla.org/joomla-cms/8732</a>.</sub>
