### ISSUE TITLE
Global settings interface, not shown properly

### ISSUE THREAD

**Issue by adriannx** [joomla/joomla-cms#8733]
Today try to enter the menu "Global Settings" but the interface does not display properly. Anyone know what might be causing this issue?

This problem only occurs in the menu "Global Settings"
Capture:
![5589](https://cloud.githubusercontent.com/assets/5619504/11905410/639ddfa8-a594-11e5-9a94-32231d66bb6d.JPG)

My version joomla is: 3.4.6

Best Regards!

**Comment by ggppdk** [comment]
Maybe a 3rd party extension is doing this,

- inside Joomla root, edit file: configuation.php

Find line with "$error_reporting", and (temporarily) set like:
```
public $error_reporting = 'development';
```

- then revisit the Global setting , a PHP fatal should appear
- in rare cases it will not appear if inside a script TAG , or inside other hidden HTML, then do "view HTML source" and scroll to the bottom, hopefully the error will be there, otherwise you may have to check the web server log

**Comment by brianteeman** [comment]
Usualy this is caused because you have upgraded from a version that used different css. Just refresh your BROWSER cache

**Comment by sovainfo** [comment]
Please use forum.joomla.org to find the solution (probable forgot to refresh your browser) for your issue. This repository is for software issues, not issues in your infrastructure.

Request this to be closed.

**Comment by ggppdk** [comment]
Well by the looks of it, none CSS file is in effect it may well be a PHP fatal,
- also it is happening in Global settings, if it was CSS issue, then the menu would not appear correctly in previous screens too, right ?

I agree that this is better posted to forum.joomla.org and not here !
- this can be due to a 3rd party extension
- so such posts should be posted here only after confirming an error / issue inside Joomla CMS code by posting at forum.joomla.org, as this is not a support forum, right ?

**Comment by adriannx** [comment]
Hello guys, thanks for reaply.

I have checked that Is not a problem of update..

As for the mistake, I checked the file "error_log" and found nothing about this problem. It makes me think it could be a problem of javascript, and yes.. this problem only occurs in the menu "Global Settings"

Regards!

**Comment by adriannx** [comment]
Days ago i install and unistall the extensión Jdiction, and i found this file on root/

<?php
/**
 * @package jDiction
 * @link http://joomla.itronic.at
 * @copyright	Copyright (C) 2011 ITronic Harald Leithner. All rights reserved.
 * @license GNU General Public License v3
 *
 * This file is part of jDiction.
 *
 * jDiction is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, version 3 of the License.
 *
 * jDiction is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with jDiction.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
defined('_JEXEC') or die;

class jddbproxyInstallerScript {
	/**
	 * Constructor
	 *
	 * @param   JAdapterInstance  $adapter  The object responsible for running this script
	 */
	public function __construct(JAdapterInstance $adapter) {

	}
 
	/**
	 * Called before any type of action
	 *
	 * @param   string  $route  Which action is happening (install|uninstall|discover_install)
	 * @param   JAdapterInstance  $adapter  The object responsible for running this script
	 *
	 * @return  boolean  True on success
	 */
	public function preflight($route, JAdapterInstance $adapter) {
		switch ($route) {
			case 'uninstall':
				echo '<h2>'.JText::_("COM_JDICTION_UNINSTALLED").'</h2>';
				echo '<p>'.JText::_("COM_JDICTION_UNINSTALLED_INFO").'</h2>';

        // remove jdiction database driver from configuration.php
        $fname = JPATH_CONFIGURATION.'/configuration.php';
        $config = JFactory::getConfig();
        $config->set('dbtype', str_replace('jdiction_', '',$config->get('dbtype')));
        jimport('joomla.filesystem.file');
        JFile::write($fname, $config->toString('PHP', array('class' => 'JConfig')));

				break;
		}
	}
 
	/**
	 * Called after any type of action
	 *
	 * @param   string  $route  Which action is happening (install|uninstall|discover_install)
	 * @param   JAdapterInstance  $adapter  The object responsible for running this script
	 *
	 * @return  boolean  True on success
	 */
	public function postflight($route, JAdapterInstance $adapter) {
		switch ($route) {
			case 'install':
				echo '<h2>'.JText::_("COM_JDICTION_INSTALLED").'</h2>';
				echo '<p>'.JText::_("COM_JDICTION_INSTALLED_INFO").'</h2>';
				break;
			case 'uninstall':
				//can't becalled
				break;
			case 'discover_install':
				echo '<h2>'.JText::_("COM_JDICTION_UNINSTALLED").'</h2>';
				echo '<p>'.JText::_("COM_JDICTION_UNINSTALLED_INFO").'</h2>';
				break;
			case 'update':
				echo '<h2>'.JText::_("COM_JDICTION_UPDATED").'</h2>';
				echo '<p>'.JText::_("COM_JDICTION_UPDATED_INFO").'</h2>';
				break;
		}
	}
 
	/**
	 * Called on uninstallation
	 *
	 * @param   JAdapterInstance  $adapter  The object responsible for running this script
	 */
	public function uninstall(JAdapterInstance $adapter) {
		//Fallback because Joomla 2.5.4 doesn't call pre or postfilt on uninstall for type file
		$this->preflight('uninstall', $adapter);
	}
}

**Comment by ggppdk** [comment]
Did you try what i suggested about enabling error reporting ?

**Comment by adriannx** [comment]
Hello, here three people in total have the same problem: http://forum.joomla.org/viewtopic.php?f=708&t=902727

And cant enable the error Reporting cuz css does not load, not display the buttom for save. 

Regards!

**Comment by ggppdk** [comment]
@adriannx 

you have missed my instructions, 
- you do need to save anything


Inside Joomla root, edit file: configuration.php
Find line with "$error_reporting", and (temporarily) set like:
```
public $error_reporting = 'development';
```
then revisit the Global setting , a PHP fatal should appear

**Comment by adriannx** [comment]
Hello ggppdk thanks for reply,

Can see only this error: Fatal error: Class 'JdDatabase' not found in /home/inchjsok/public_html/libraries/joomla/database/driver/jdiction_mysqli.php on line 37

Best Regards!

**Comment by ggppdk** [comment]
Ok it seems there is a JDiction system plugin called "section"

- you can try going to Joomla plugin manager and disabling it

or uninstalling it via extension management

**Comment by adriannx** [comment]
Hello, but i no have that plugin installed, because I uninstalled the extension jdiction. Cant find..

Regards!

**Comment by ggppdk** [comment]
Maybe something went wrong with uninstalling, it was half-uninstalled

- possibly the system plugin "section" is NOT a plugin of JDiction
the fact that it is calling Jdiction DB driver, does not mean that it is a jDiction plugin

- it can be of another extension, it maybe NEEDED , and something else may break after doing the following:


Try renaming:
/home/.../public_html/plugins/system/section/section.php
to 
/home/.../public_html/plugins/system/section/section.bak

or backing up folder:
/home/.../public_html/plugins/system/section
and then deleting it.

- you should report your findings to the author of the extension
- this does not seem to be a Joomla bug, this should be closed

**Comment by adriannx** [comment]
Solved :)

PHP Fatal error: Class 'JdDatabase' not found in /~/libraries/joomla/database/[drive]/jdiction_mysqli.php on line 37, referer: http://~/administrator/index.php?option ... iew=manage 

If I rename the jdiction_mysqli.php to ~.php__, the error has disappeared.

To solve the problem simply delete the file jdiction_mysqli.php

Located in: /~/libraries/joomla/database/[drive]/jdiction_mysqli.php

Thanks for the help ggppdk!

Best Regards!
