### ISSUE TITLE
Language filter not working for categories with subcategories in "List All Categories" menu item

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#8738]
#### Steps to reproduce the issue
BACKEND:
Setup the site as multilingual.
Create a category CAT_A_EN with language English
Create a category CAT_A_IT with another language (ex. Italian) and associate to CAT_A_EN
Create an English menu item "List All Categories"
Create an Italian menu item "List All Categories"
FRONTEND:
everything works as expected with just one category shown in each language
BACKEND
Create a new category "CAT_B_EN" with language English as a subcategory of CAT_A_EN
Same for italian with "CAT_B_IT" as sucat of CAT_A_IT

#### Expected result
FRONTEND
Just CAT_A_EN OR CAT_A_IT is shown depending on current language

#### Actual result
FRONTEND
Both CAT_A_EN and CAT_A_IT are shown independent of current language

#### System information (as much as possible)
Windows 7 XAMPP

**Comment by infograf768** [comment]
I think this has been solved for 3.5.0
See https://github.com/joomla/joomla-cms/pull/7901

**Comment by infograf768** [comment]
and
https://github.com/joomla/joomla-cms/pull/8098

**Comment by brianteeman** [comment]
@Giuse69  Please can you retest with the current staging to confirm it has been resolved and report back so this can be closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8738">issues.joomla.org/joomla-cms/8738</a>.</sub>

**Comment by Giuse69** [comment]
The new "libraries\legacy\categories\categories.php" fixes the problem!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8738">issues.joomla.org/joomla-cms/8738</a>.</sub>

**Comment by brianteeman** [comment]
Great - closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8738">issues.joomla.org/joomla-cms/8738</a>.</sub>

**Comment by Giuse69** [comment]
WARNING: the modification in "libraries\legacy\categories\categories.php" solves the tracker problem but breaks the category association!
The language switch module now shows wrong URL: for example I am on "http://localhost/it/fotografia/lezioni" (IT) and the English flag shows "http://localhost/en/**fotografia/lezioni**" that is completely wrong as it should be "http://localhost/en/**photography/tutorials**" like it was before the change in categories.php.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8738">issues.joomla.org/joomla-cms/8738</a>.</sub>

**Comment by brianteeman** [comment]
Re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8738">issues.joomla.org/joomla-cms/8738</a>.</sub>

**Comment by infograf768** [comment]
Read above... This has also been solved.
https://github.com/joomla/joomla-cms/pull/8098

Please close this issue.

**Comment by Giuse69** [comment]
Ok, I used the categories.php version of #7998.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8738">issues.joomla.org/joomla-cms/8738</a>.</sub>

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8738">issues.joomla.org/joomla-cms/8738</a>

**Comment by infograf768** [comment]
Both fixed in code base<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8738">issues.joomla.org/joomla-cms/8738</a>.</sub>
