### ISSUE TITLE
Postgres create new or edit existing FAIL

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#8746]
#### Steps to reproduce the issue
With POSTGRES as the database create a new banner client and then create a second banner client
or
With POSTGRES as the database create a new articke and then create a second article

#### Expected result
Two clients created or two articles

#### Actual result
First client created
Attempt to create a second client produces the following error

> Error
Save failed with the following error: ERROR: duplicate key value violates unique constraint "#__banner_clients_pkey" DETAIL: Key (id)=(0) already exists.SQL=INSERT INTO "#__banner_clients" ("checked_out_time","id","name","contact","email","extrainfo","state","metakey","own_prefix","metakey_prefix","purchase_type","track_clicks","track_impressions") VALUES ('1970-01-01 00:00:00',0,'b','ab','ab@example.com','',1,'',0,'',-1,0,0) RETURNING id

First article created
Attempt to create a second article produces the following error
> Error
Save failed with the following error: ERROR: duplicate key value violates unique constraint "#__content_pkey" DETAIL: Key (id)=(0) already exists.SQL=INSERT INTO "#__content" ("id","title","alias","introtext","fulltext","state","catid","created","created_by","created_by_alias","modified","publish_up","publish_down","images","urls","attribs","version","metakey","metadesc","access","metadata","featured","language","xreference") VALUES (0,'affafaf','affafaf','','',1,2,'2015-12-20 13:51:33',722,'','2015-12-20 13:51:33','2015-12-20 13:51:33','1970-01-01 00:00:00','{"image_intro":"","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""}','{"urla":false,"urlatext":"","targeta":"","urlb":false,"urlbtext":"","targetb":"","urlc":false,"urlctext":"","targetc":""}','{"show_title":"","link_titles":"","show_tags":"","show_intro":"","info_block_position":"","show_category":"","link_category":"","show_parent_category":"","link_parent_category":"","show_author":"","link_author":"","show_create_date":"","show_modify_date":"","show_publish_date":"","show_item_navigation":"","show_icons":"","show_print_icon":"","show_email_icon":"","show_vote":"","show_hits":"","show_noauth":"","urls_position":"","alternative_readmore":"","article_layout":"","show_publishing_options":"","show_article_options":"","show_urls_images_backend":"","show_urls_images_frontend":""}',1,'','',1,'{"robots":"","author":"","rights":"","xreference":""}',0,'*','') RETURNING id

#### System information (as much as possible)
Current staging environment

#### Additional comments
Works perfectly with mysqli

**Comment by brianteeman** [comment]
Updated to show its not just banners but articles as well<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8746">issues.joomla.org/joomla-cms/8746</a>.</sub>

**Comment by waader** [comment]
I can not reproduce your findings. Testing with the current staging branch, with and without testing data installed, inserting multiple records for banner clients, banner categories, banners, articles etc. just worked.

My testing environment comprises php 5.4.16 and postgres 9.2.13.

**Comment by brianteeman** [comment]
My tests were with current staging of joomla
postgres 9.3.5
php 5.5.26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8746">issues.joomla.org/joomla-cms/8746</a>.</sub>

**Comment by brianteeman** [comment]
It is also impossible to edit an existing article - when you select an article to edit then instead of that article being opened you get a brand new empty article<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8746">issues.joomla.org/joomla-cms/8746</a>.</sub>

**Comment by brianteeman** [comment]
Closed as I can no longer replicate this with 3.4.8
@nikosdion also confirmed this via twitter<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8746">issues.joomla.org/joomla-cms/8746</a>.</sub>
