### ISSUE TITLE
Users Manager:: Pagination is not working after applying any filter

### ISSUE THREAD

**Issue by aasimali** [joomla/joomla-cms#8751]
Tested on Joomla 3.4.6

Go to Administrator panel
Go to Users menu
Select Manage

Apply any filter and then check the pagination

It will not work, Ideally, pagination should work
![administration users](https://cloud.githubusercontent.com/assets/10045599/11930866/50b957c0-a80d-11e5-955a-7d48ded33814.png)

**Comment by Fedik** [comment]
please test Joomla 3.5
it should be fixed in j 3.5 if I right remember, 
I think @Bakual have a better memory to confirm it :wink:

**Comment by Bakual** [comment]
Should be fixed indeed with https://github.com/joomla/joomla-cms/pull/7487

**Comment by aasimali** [comment]
Okay- But I guess, It must be merged into the latest Joomla Release 3.4.6, which we had released last week.

**Comment by Bakual** [comment]
No, that release was only a security release. There were no other bugfixes in it.
This will be fixed with 3.5.0.

Closing as it is already fixed in staging.

**Comment by aasimali** [comment]
Okay- Thank you guys :)
