### ISSUE TITLE
Notice on top of tag menu page in developer mode and search engine friendly mode

### ISSUE THREAD

**Issue by hakanara** [joomla/joomla-cms#8752]
Steps to reproduce the issue
Assign a tag to a menu item. (my menu item was in Turkish)
Set the site error reporting to developer mode
Set the site to search engine friendly URL's

Expected result
No notice

Actual result
Notice: Array to string conversion in /libraries/joomla/filter/input.php on line 232

System information (as much as possible)
I havent seen this notice in Joomla 3.4.5
The notice started with the 3.4.6 update.
Database Version 	5.6.26-cll-lve
Database Collation 	utf8_general_ci 
PHP Version 	5.4.45 

Additional comments
Enjoy life while you can

**Comment by bertmert** [comment]
Confirmed for J!3.4.6, PHP5.6.13

**Comment by bertmert** [comment]
In my case it was a plugin of mine. My fault.
A call like this
```
$ID = (int) $this->app->input->get('id');
```
creates the notice because id is an array in com_tags/tag view context.

After removing this line the notice was gone. So, I think it's not a Joomla issue.

(And I remember now that we had this already in 2 or 3 forum threads. Always 3rd extensions.)

**Comment by hakanara** [comment]
I have disabled all the "content" plugins (both Joomla and mine) and I still get the notice. I suspect that it has something to do with Turkish characters. 

What type was your plugin and what plugin was it?

**Comment by hakanara** [comment]
And the same notice disappears if the URLs are not search engine friendly. How would you explain this?

**Comment by bertmert** [comment]
It's a "private" system plugin in method onAfterRoute.

SEF off: It makes no difference. Still get the notice from my plugin. 
That makes sense (id[0]=25):
URL:
```
index.php?option=com_tags&view=tag&id[0]=25&Itemid=650
```

At the moment I use a quick fix and handle id always as array.
```
$ID = $this->app->input->get('id', array(), 'ARRAY');

... do more...
```
You can try debugging in
/libraries/joomla/input/input.php method get(...)
```
 public function get($name, $default = null, $filter = 'cmd')
 {
  if (isset($this->data[$name]))
  {
#DEBUG START
if ($filter == 'cmd' && is_array($this->data[$name]))
{
 $callers = debug_backtrace();
 echo 'DEBUG: '.print_r($callers[0],true);exit;
}
#DEBUG END
   return $this->filter->clean($this->data[$name], $filter);
  }

  return $default;
 }
```
Further discussions should be done in a forum I think.

**Comment by hakanara** [comment]
@bertmert very big thank you for your help and for your time. You were right, it was because of a non Joomla plugin. The thing is, I have never seen this notice before, especially before the update.
