### ISSUE TITLE
URL redirect to category list does not return correct  URL

### ISSUE THREAD

**Issue by webmaster-krainer** [joomla/joomla-cms#8753]
#### Steps to reproduce the issue
- create login form menu item
- redirect login to "index.php?option=com_content&view=category&id=12"

#### Expected result
on successfull login -> http://site.name/index.php?option=com_content&view=category&id=12

#### Actual result

http://site.name//index.php/component/content/category/12-krainer/ledenzone/ledenbladen

**Comment by webmaster-krainer** [comment]
redirecting to a single article (e.g. index.php?option=com_content&view=article&id=9) works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8753">issues.joomla.org/joomla-cms/8753</a>.</sub>

**Comment by PhilETaylor** [comment]
try appending the correct Itemid to the url as well

**Comment by webmaster-krainer** [comment]
The Itemid is correct:

URL  "http://site.name/index.php?option=com_content&view=category&id=12" typed into browser gives correct result.

also removing the last part "ledenzone/ledenbladen" and refreshing browser gives correct result.

This last part "ledenzone/ledenbladen" is category 12.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8753">issues.joomla.org/joomla-cms/8753</a>.</sub>

**Comment by webmaster-krainer** [comment]
Sorry, spoke to fast
Above URL only gave Articles in Category, not the category list.
http://site.name/index.php?option=com_content&view=category&id=12&Itemid=120   gives correct result

So there is no issue. :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8753">issues.joomla.org/joomla-cms/8753</a>.</sub>
