### ISSUE TITLE
Joomla create content plugin to add fields to article (com_content)

### ISSUE THREAD

**Issue by obonyojimmy** [joomla/joomla-cms#8754]
Am a beginner to joomla development ,id like to add extra fields to the article (com_content)component. I have read this article https://docs.joomla.org/Adding_custom_fields_to_the_article_component However it does not fully answer my question on when / how to add the extra fields to the table _content table , and when to add the inserted data .Any help is greatly appreciated .

si SO question link . http://joomla.stackexchange.com/q/14739/7463

**Comment by brianteeman** [comment]
This is the place to report issues with the core Joomla code and not for development support<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8754">issues.joomla.org/joomla-cms/8754</a>.</sub>

**Comment by sovainfo** [comment]
See https://groups.google.com/forum/#!forum/joomla-dev-general for support.
