### ISSUE TITLE
Joomla 3.4.7 Update: not possible to open Template in backend for changing settings

### ISSUE THREAD

**Issue by RoterNagel** [joomla/joomla-cms#8756]
#### Steps to reproduce the issue
1. Install Update
2. Click "Extentions > Templates"
3. Try clicking at for example "ISIS"

#### Expected result
Normaly you can open the Template and change some settings like colors.

#### Actual result
"Error
You are not permitted to use that link to directly access that page (#8)."
![Pic of the Error in Joomla](http://www.formativ.net/images/Administration_-_Templates__Styles.png "Pic of the Error in Joomla")

#### System information (as much as possible)
Joomla 3.4.7

**Comment by rdeutz** [comment]
please logout and login, it is a know bug 

https://docs.joomla.org/Category:Version_3.4.7_FAQ
