### ISSUE TITLE
_schemas version_id falsch

### ISSUE THREAD

**Issue by Stojsi** [joomla/joomla-cms#8759]
Die Version ID stimmt nicht, Joomla 3.4.7 ist installiert aber die Version Nr. in Version_id ist noch immer 3.4.0-2015-02-26

**Comment by PhilETaylor** [comment]
@Kubik-Rubik German?

**Comment by PhilETaylor** [comment]
I believe that there were no schema updates for Joomla 3.4.7 - so 3.4.0-2015-02-26 might well be the last that was needed... As long as no schema updates are available to apply then you are up to date.

No issue to resolve here.

**Comment by Kubik-Rubik** [comment]
Das ist korrekt, das aktuelle Schema ist 3.4.0-2015-02-26.

Hier darf nur auf  Englisch kommuniziert werden, bitte kein Deutsch!
