### ISSUE TITLE
Installation FTP Einstellungen

### ISSUE THREAD

**Issue by Stojsi** [joomla/joomla-cms#8760]
Bei einer neu Installation kommt seit v3.2 noch immer ein Fehler wenn man FTP Daten einträgt und auf PFAD und EINSTELLUNGEN PRÜFEN klickt!

Weiters wird das Installationsverzeichnis gelöscht und die Configuration.php nicht erstellt via FTP!

**Comment by infograf768** [comment]
Please write in English here.

**Comment by bertmert** [comment]
@Stojsi 
hier deutsches Anlaufstelle: http://www.joomla-bugs.de/forum/index.php
@all This is a URL for issue reporting in German
