### ISSUE TITLE
Update Prozess

### ISSUE THREAD

**Issue by Stojsi** [joomla/joomla-cms#8761]
Ein Update direkt, wenn nur FTP erlaubt ist, ist nicht möglich! Update nur via Extension Update mit der ZIP Datei möglich!

**Comment by Kubik-Rubik** [comment]
Only English here!

**Comment by PhilETaylor** [comment]
This doesn't sound like a Joomla issue but a web hosting issue - recommend closing unless opening poster can be more verbose in english with details of their problem. 

Kindest regards
Phil.

**Comment by rdeutz** [comment]
even it is in "German" a language I speak and understand, it isn't clear what this is about, closing it.

You can reopen, if you are not able to explain it in english you can send me an email [githubusername] at googlemail.com
