### ISSUE TITLE
Update 3.7.4 unable to create new menu item

### ISSUE THREAD

**Issue by LaurensGoedel** [joomla/joomla-cms#8763]
# Steps to reproduce the issue
1. Update to Joomla 3.4.7
2. Create a new menu item
3. Try to select the menu item type

# Expected result
Possible to fill in extra information about the just created menu item

# Actual result
Page is redirected back to new menu item, but all input is deleted.

# Possible solution
So far, i have no clue what a possible solution could be

**Comment by JacquesR** [comment]
Log out of the site, and back in, and see if that resolves it.
Similar to:
https://docs.joomla.org/J3.x:Unable_To_Edit_Article_3.4.7

**Comment by LaurensGoedel** [comment]
You are right @JacquesR ! Thanks!
