### ISSUE TITLE
Can't go to other than first page in users list view with categories filtered

### ISSUE THREAD

**Issue by marcodings** [joomla/joomla-cms#8764]
#### Steps to reproduce the issue

* select users | users in backend to list the users of a site
* open search tools and filter users by a group
* set you number of items displayed significantly low so you have pagination
* try to navigate to any other page in the list

#### Expected result

desired result would of course be to display the users in the selected page

#### Actual result

navigation to page fails, only the first page keeps getting displayed

#### System information (as much as possible)

J3.4.7

#### Additional comments

additionally applied 3.4.x to 3.4.7 update to make sure no files were missing

**Comment by joomdonation** [comment]
Seems the issue was fixed with this PR https://github.com/joomla/joomla-cms/pull/7487. It will be fixed in version 3.5.0. Please see https://github.com/joomla/joomla-cms/issues/8751 for similar report recently

**Comment by brianteeman** [comment]
Closed as a duplicate<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8764">issues.joomla.org/joomla-cms/8764</a>.</sub>
