### ISSUE TITLE
Remove - /bin/keychain.php

### ISSUE THREAD

**Issue by robbykotulla** [joomla/joomla-cms#8765]
In the current Joomla package is /bin/keychain.php file includet.
This file defines in line 14 a ../libraries/import.php dependencies, **which is not included in the package**.
If you call the file via browser, you get a fatal error (incl. indication of the absolute server path)

*Step By Step*
* Activate the Error-Reporting
* Call: your-joomla-domain.com/bin/keychain.php width any Browser
* Get the Fatal Error Message

```php
​Fatal error: Class 'Joomla\Application\AbstractApplication' not found in /libraries/joomla/application/base.php on line 23
```

**Comment by bertmert** [comment]
> This file defines in line 14 a ../libraries/import.php dependencies, which is not included in the package.

It's included! If you speak German: Why the error occurs was discussed yesterday in a German forum:
http://www.joomlaportal.de/joomla-3-x-installation/323446-fatal-error-class-joomla-application-abstractapplication-not-found.html#post1610912

I could reproduce the explanation by debugging and the guy is right.

**But if the file is still needed I don't know.**

**Comment by photodude** [comment]
I don't believe you call the keychain file directly. it's called by another file, and "provides is a way to load data from, and store data to an encrypted data source."

https://groups.google.com/forum/#!searchin/joomla-dev-platform/keychain/joomla-dev-platform/4y32Q8VlhCA/FxepGpNB408J

https://github.com/eBaySF/joomla-platform/wiki/Keychain

**Comment by robbykotulla** [comment]
I am aware that the file should not be called directly. The problem is that
they can be called directly! And outputs may a Fatal Error!

**Comment by photodude** [comment]
They why are you asking for the file to be removed? I suggest changing your issue title to reflect your issue.

**Comment by robbykotulla** [comment]
Thanks for your answer. I think the file is no longer needed for Joomla.
The Class Keychain is to my knowledge fully integrated into the platform.
Am 22.12.2015 19:55 schrieb "photodude" <notifications@github.com>:

**Comment by photodude** [comment]
Keychain "provides is a way to load data from, and store data to an encrypted data source." It is absolutely needed anytime the application, or a 3rd party extension needs to load or store data to an encrypted data source.

As far as I can tell the CMS does not currently utilize JKeychain from the framework, but there are 3rd party extensions which do.

**Comment by photodude** [comment]
Tested following the supplied steps, I could not replicate this issue.

**Comment by mbabker** [comment]
The JKeychain class is integrated in the platform.  The bin/keychain.php
file is a CLI utility to work with keychain objects.  So the file is still
useful and probably just needs updated with the proper CLI bootstrap for
the CMS.

**Comment by brianteeman** [comment]
Closed please see #8860<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8765">issues.joomla.org/joomla-cms/8765</a>.</sub>

**Comment by photodude** [comment]
@brianteeman did you mean #8820 ? I can't seem to find an #8860 in the tracker.

**Comment by brianteeman** [comment]
Oops

**Comment by brianteeman** [comment]
See #8820 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8765">issues.joomla.org/joomla-cms/8765</a>.</sub>
