### ISSUE TITLE
My site is messed up.

### ISSUE THREAD

**Issue by steelborn** [joomla/joomla-cms#8776]
First, I am unable to log into Joomla with my original account, so I created a new account.

Second, something is massively wrong with my site. I already checked with the hosting site, and they say it has to do with Joomla.

The pages are full of lines like this:

Strict Standards: Non-static method JLoader::import() should not be called statically in /home1/editguy/public_html/erikrosenbluh.net/libraries/joomla/import.php on line 29

My site is: erikrosenbluh.net

**Comment by bertmert** [comment]
You are using a completely outdated and unsecure(!) Joomla 1.5.15.
Your PHP version is not compliant with this Joomla version.
You should urgently upgrade, migrate to Joomla 3!
Please ask in a forum for help because this is an issue tracker for Joomla 3 here!

**Comment by Kubik-Rubik** [comment]
This is not a support forum! Please use the official forum to get help: http://forum.joomla.org/

Closed!
