### ISSUE TITLE
404 on pages that use 3rd party extension after update

### ISSUE THREAD

**Issue by adi8i** [joomla/joomla-cms#8779]
Hello.

After update to 3.4.7 pages that use 3rd party extension return 404, one of them is J Events.
Sometimes it works sometimes not, turning off SEF URL may help.

Anyone experiencing this?

**Comment by brianteeman** [comment]
Have you spoken to jevents?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8779">issues.joomla.org/joomla-cms/8779</a>.</sub>

**Comment by adi8i** [comment]
Not yet, is not just jevents. I was wondering if anyone else have a similar issue, or it's a potential issue on my end.

**Comment by brianteeman** [comment]
This is not the place for debugging issues on individual sites. I am closing this at this time.
