### ISSUE TITLE
Automatically added space character to blank metadata of tag items

### ISSUE THREAD

**Issue by hakanara** [joomla/joomla-cms#8781]
When you save a tag info, if you leave the meta keywords and meta description fields empty, automatically a space character is added to this field and the description is saved like this.

Then, no matter what you add to the meta description of the menu item of "tagged items", you get a space character (and no info ofcourse) in the meta description (and keywords) in the source code. I selected only one tagged item and linked it to the menu.

Additionally, tagged items page has meta author, but you dont see the author name only the user number as 62 or whatever (most probably the admin user number).

These are all weird, on top, I need to get $row->params->get('menu-meta_description') on tagged items menu page, it has most of the params including the keywords but not the description. Hard to understand. 

I accept that I am a newbie, but I checked the above issues from two different sites, one of which was a fresh installation only with sample data.

Last words: Keep up the good work! :-)

**Comment by bertmert** [comment]
Confirmed.

I think it's nonsense at all to output the author of one of the TAGS (not tagged items). If there are several creators of tags just one is respected (and not the name but the id).

```
  <meta name="keywords" content=" " />
  <meta name="author" content="40" />
  <meta name="description" content=" " />
```

**Comment by bertmert** [comment]
Please test https://github.com/joomla/joomla-cms/issues/8783 and https://github.com/joomla/joomla-cms/issues/8784

**Comment by brianteeman** [comment]
Closing as we have pull requests for testing. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8781">issues.joomla.org/joomla-cms/8781</a>.</sub>
