### ISSUE TITLE
How to put Joomla 3 files higher than wwwroot?

### ISSUE THREAD

**Issue by mistbow-git** [joomla/joomla-cms#8787]
Hi!

I want to be able to install Joomla in a folder outside than wwwroot, and
put only one file index.php in wwwroot and only css and js files there?
I'm tired to search for viruses among the numerous files joomla and among plug-ins!
In this case if I found more then one php file in wwwroot it is a virus (backdoor, shell? etc.)
Is this possible now?

Best Example is a Yii2 App Basic: https://github.com/yiisoft/yii2-app-basic/tree/master/web
All other extensions puts his files in assets folder.

Thanks!

**Comment by Bakual** [comment]
It's not possible without hacking the core files.
Please use our forums (forum.joomla.org) for future questions as this is the issue tracker.

**Comment by mistbow-git** [comment]
Ok!
Please change your joomla core files to support this installation in new builds!
