### ISSUE TITLE
hamburgermenu issuetracker not working in firefoxmobile

### ISSUE THREAD

**Issue by Klipper** [joomla/joomla-cms#8803]
#### Steps to reproduce the issue
Open the issuetracker in Firefox mobile(latest) on Android, or default 'Internet' browser (Samsung)
Push the hamburgermenu button.
The menu appears.
Try one of the menu-items: Nothing happens, except that the menu disappear again. 

#### Expected result
Navigate to the chosen menu-item

#### Actual result
Menu disappear, but no navigation to the chosen menu-item.

#### System information (as much as possible)
Latest Firefox mobile on Android 4.4

**Comment by brianteeman** [comment]
There is no such version as latest.

**Comment by brianteeman** [comment]
Sorry just saw you are reporting an issue about this tracker not joomla.
Please select the tracker project from the projects menu link and create an issue there
