### ISSUE TITLE
Fatal error: Uncaught exception RuntimeException .. The session is not started.

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#8807]
#### Steps to reproduce the issue

I am working on the latest staging. In the morning, when I return to the /administrator area, I get a fatal error message at the top of the login page.

If I try to login, it displays the warning "Your session has expired. Please log in again."

If I try to login again, I can finally access the backend site.

#### Expected result

No error messages. Login in a single step.

#### Actual result

	 Fatal error: Uncaught exception 'RuntimeException' with message 'The session is not started.' in /..../libraries/joomla/session/handler/native.php on line 221 RuntimeException: The session is not started. in /..../libraries/joomla/session/handler/native.php on line 221 Call Stack: 7.9009 3325852 1. JSessionHandlerNative->save() /.../libraries/joomla/session/handler/native.php:0 

#### System information (as much as possible)

Latest J3.5 staging on PHP 5.6.16-2+deb.sury.org~trusty+1

**Comment by peteruoi** [comment]
see #8808

**Comment by anibalsanchez** [comment]
Yes, it is the same issue, described at the administrator login.

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8807">issues.joomla.org/joomla-cms/8807</a>
