### ISSUE TITLE
Cannot empty Category trash

### ISSUE THREAD

**Issue by aantic** [joomla/joomla-cms#8809]
#### Steps to reproduce the issue
Make sure category does not contain any articles, published, unpublished nor trashed. Select the category and click the button Trash to send it to the Trash. Select the trashed category and try to Empty Trash. 

#### Expected result
This action should empty the trash

#### Actual result
Page reloads and nothing happens. I tried rebuilding but it doesn't help.

#### System information (as much as possible)
PHP Built On 	Linux server.olympic.rs 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64
Database Version 	5.5.46
Database Collation 	latin1_swedish_ci
PHP Version 	5.4.45
Web Server 	Apache
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0

**Comment by rgblogs** [comment]
Before clicking empty trash, select the category to delete from trash.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8809">issues.joomla.org/joomla-cms/8809</a>.</sub>

**Comment by aantic** [comment]
Of course. I selected the category before hitting the button Empty Trash.
Page only reloads and nothing happens!

**Comment by brianteeman** [comment]
For support please use the forum http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8809">issues.joomla.org/joomla-cms/8809</a>.</sub>

**Comment by aantic** [comment]
I am not sure why would you close the unsolved issue . I posted in Joomla forum one month ago.
http://forum.joomla.org/viewtopic.php?f=710&t=899465
Here are the images that show that I dont have any unpublished articles not trashed articles but still cannot empty the Trash. 
![cannot empty trash category](https://cloud.githubusercontent.com/assets/8791467/12049249/270a34ec-aee5-11e5-81e6-7a9d7042d72e.jpg)
![empty category](https://cloud.githubusercontent.com/assets/8791467/12049251/270e3f24-aee5-11e5-99dc-bebbfe89f399.jpg)
![no trashed articles](https://cloud.githubusercontent.com/assets/8791467/12049250/270bfe80-aee5-11e5-8af1-02958de803dd.jpg)
![no unpublished articles](https://cloud.githubusercontent.com/assets/8791467/12049252/27115a4c-aee5-11e5-84bf-8c4535cd9922.jpg)

**Comment by aantic** [comment]
I was just able to trash the category after changing its alias. I guess you can keep this issue closed!
