### ISSUE TITLE
Base URL formatted incorrectly causing site not find resources

### ISSUE THREAD

**Issue by aluidens** [joomla/joomla-cms#8810]
#### Steps to reproduce the issue
Upgraded from J3.4.6 to J3.4.7 (did not notice the issue here right away)
Upgraded from J3.4.7 to J3.4.8 (definately noticed the issue after awhile as the site is behind the CloudFlare service.

#### Expected result
Normal rendering of the site pages, resources, and links.

#### Actual result
The resources (e.g. pictures) could not be found. Thus these resource leave wholes in the page, and none of the links working either.

#### System information (as much as possible)
PHP Built On	Linux web2011.websitewelcome.com 3.12.41-77.ELK6.x86_64 #1 SMP Fri May 1 18:21:30 CDT 2015 x86_64
Database Version	5.5.42-37.1
Database Collation	utf8_general_ci
PHP Version	5.4.45
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

#### Additional comments
The base is supposed to be www.domain.com/en-us/ for the English version of the site. It renders the following as the base url www.domain.comhttp://www.domain.com/en-us/www.domain.com/
further rendering the following url (example) for resources www.domain.comhttp://www.domain.com/en-us/www.domain.com/images/green_leaf.png thus rendering the pages full of wholes with resources that could not be found.

SEF is enabled. Multi Language Plugin is enabled. 

I have created a local copy of the site on my machine from a backup that was still Joomla 3.4.7. The same issue appears. I have reverted back to an earlier backup with Joomla 3.4.6 version of the site, and the site's page was restored to normal. This is with the same exact .htaccess and configuration.php across the 3 Joomla versions.

So this issue might be pertaining to Joomla versions 3.4.7 and 3.4.8. The challenge is that 3.4.6 also has critical security vulnerabilities.

**Comment by ggppdk** [comment]
Is variable $live_site of your configuration.php non-empty ?

If non-empty what is the value of it ?
Try making it empty

In your localhost, did you try overwritting .htaccess with Joomla default htaccess.txt ?

**Comment by aluidens** [comment]
Thank you for your assistance.

Variable $live_site of your configuration.php is empty and always has been.

The .htaccess used before through J3.4.6, J3.4.7, and J3.4.8 have all been the same.
Testing with the htaccess.txt that came with J3.4.8 rendered the same result, basically the Base URL is formulated like this:

Using Google Chrome
On the live hosted site: 
www.domain.comhttp://www.domain.com/www.domain.com/

On the localhost copy of the site: localhost/domainfolder/localhost/domainfolder/http://localhost/domainfolder/localhost/domainfolder/domainfolder

Did comment out the "Options +FollowSymlinks" statement in the .htaccess file. This delivered the same exact results as above for both.

**Comment by brianteeman** [comment]
The forum is the best place for support on issues specific to your site. As I can see you already have a topic created there I am closing this here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8810">issues.joomla.org/joomla-cms/8810</a>.</sub>

**Comment by aluidens** [comment]
Brian,

Are you confirming that this issue is specific to my site only? That J3.4.7 and 3.4.8 are not introducing a bug that causes the Base URL being incorrectly formulated?

**Comment by brianteeman** [comment]
Yes
