### ISSUE TITLE
Label For Global Check-in

### ISSUE THREAD

**Issue by rgblogs** [joomla/joomla-cms#8811]
#### Steps to reproduce the issue

Edit an article. Close it without saving.

Go to System -> Global Check-in

You will see a number against content table.

#### Expected result

The color should be different.

#### Actual result

All numbers are blue.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/8813

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8811">issues.joomla.org/joomla-cms/8811</a>

**Comment by infograf768** [comment]
Closing as we have a patch https://github.com/joomla/joomla-cms/pull/8813<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8811">issues.joomla.org/joomla-cms/8811</a>.</sub>
