### ISSUE TITLE
Page doesn't load - admin login won't appear either

### ISSUE THREAD

**Issue by ReverendGuen** [joomla/joomla-cms#8812]
This started a few days ago apparently. My webpage loads only a white page... no error messages nothing  and the administrator page won't load either ... just a white page. I'm still running on v1.5 (yes I know it's out dated but I haven't had the time/capability to upgrade yet).... I need this page up and running as it is for our community charitable organization   ... the page is http://worldtreeministry.org   and I can't get anything to load. I am able to get into the cpanel via the host but that doesn't do me any good. Any ideas/fixes/anything would be greatly appreciated.

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8812">issues.joomla.org/joomla-cms/8812</a>

**Comment by infograf768** [comment]
1.5 is totally obsolete and we do not provide patches for that version.
Please use the forums to get help.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8812">issues.joomla.org/joomla-cms/8812</a>.</sub>
