### ISSUE TITLE
PHP 7.0 fatal error: Cannot use Joomla\\String\\String as String because 'String' is a special class name

### ISSUE THREAD

**Issue by Lyquix** [joomla/joomla-cms#8817]
#### Steps to reproduce the issue
Upgraded to PHP 7.0.1 in Ubuntu 14.04 using the following the steps:
$  add-apt-repository ppa:ondrej/php-7.0
$  apt-get update
$  apt-get install php7.0
$  a2dismod php5
$  service apache2 restart

Load home page of Joomla 3.4.7 site and get HTTP error 500. The following appears in Apache log:

[Wed Dec 30 16:27:01.296035 2015] [:error] [pid 11346] [client 192.168.56.101:58686] PHP Fatal error:  Cannot use Joomla\\String\\String as String because 'String' is a special class name in /srv/www/joomla.lyquix.dev/public_html/libraries/vendor/joomla/registry/src/Format/Json.php on line 12

#### Expected result

Home page loaded without errors

#### Actual result

HTTP error 500

Apache error log shows:

[Wed Dec 30 16:27:01.296035 2015] [:error] [pid 11346] [client 192.168.56.101:58686] PHP Fatal error:  Cannot use Joomla\\String\\String as String because 'String' is a special class name in /srv/www/joomla.lyquix.dev/public_html/libraries/vendor/joomla/registry/src/Format/Json.php on line 12

#### System information (as much as possible)

Ubuntu 14.04.2 LTS
PHP 7.0.1-4+deb.sury.org~trusty+1 (cli) ( NTS )
Apache server 2.4.7
Joomla 3.4.7

#### Additional comments

This is the first time I am submitting a bug here. I apologize if I am not following the right procedure or place. I would like to help.

**Comment by brianteeman** [comment]
Joomla 3.4.x is not compatible with php 7 as stated in the release
announcement.
The next version 3.5 scheduled for release in Feb will be the first version
that is

**Comment by Lyquix** [comment]
Got it. Thanks!

**Comment by VGerris** [comment]
I have the exact same issue when I installed gk_portfolio_quickstart_J!3.
The error is :
[pid 16618] [client 127.0.0.1:34022] PHP Fatal error:  Cannot use Joomla\\String\\String as String because 'String' is a special class name in /var/www/html/libraries/vendor/joomla/registry/src/Format/Json.php on line 12, referer: http://take1.unlockyoursoftware.com/administrator/index.php?option=com_admin&view=sysinfo

I am running Joomla 3.7.2. Would the install have messed up something?

I fixed it by extracting the full install over it, then I got back in.

**Comment by wojsmol** [comment]
This quickstart is probably not compatible with php 7.

**Comment by AndyGaskell** [comment]
I had the same issue with a Joostrap quickstart recently, I guess a lot of Template developers don't keep their quickstart packages up-to-date, which is fair enough I suppose, as that'd be a fair amount of work.

Dropping the latest Joomla install over the top of the files fixed it fine, as mentioned above.

**Comment by Billy-Bill** [comment]
I fixed the issue by reversing to PHP 5.6 from 7.1, updated Joomla and the plugins and then switched back to PHP 7.1. In my case the Hostgator control panel has a PHP selector  to do that. Cheers.
