### ISSUE TITLE
Blank  page administrator/index.php?option=com_content since update to 3.4.8

### ISSUE THREAD

**Issue by curtisuk** [joomla/joomla-cms#8821]
since updating to 3.4.8 and on any way I can find to view articles I get a blank page

administrator/index.php?option=com_content 

I have manual uploaded the latest files again from a fresh download.

**Comment by sovainfo** [comment]
Use forum.joomla.org and the documentation to resolve your issue. Return here with proper details when it turns out an issue with the Joomla software.

Suggest to close this!

**Comment by ashik685** [comment]
I have faced same issue , just make sure for everyone, clear your cache.
