### ISSUE TITLE
DateTime::__construct(): Failed to parse time string (jerror) at position 0 (j): The timezone could not be found in the database

### ISSUE THREAD

**Issue by entreprenor** [joomla/joomla-cms#8824]
#### Steps to reproduce the issue

I upload a plugin and tried ot install - it gives me the following error :
DateTime::__construct(): Failed to parse time string (jerror) at position 0 (j): The timezone could not be found in the database

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8824">issues.joomla.org/joomla-cms/8824</a>

**Comment by infograf768** [comment]
Looks like this was changed on github. Closing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8824">issues.joomla.org/joomla-cms/8824</a>.</sub>

**Comment by potenzatk** [comment]
Hello

Same error I have found when trying to install the new extension in my Joomla site please check below links.

http://prntscr.com/mum8ga

Database Version | 5.1.69
Database Collation | utf8_general_ci
PHP Version | 5.3.3
Web Server | Apache/2.2.15 (CentOS)
WebServer to PHP Interface | apache2handler
Joomla! Version | Joomla! 3.1.1 Stable [ Ember ] 26-April-2013 14:00 GMT
Joomla! Platform Version | Joomla Platform 12.2.0 Stable [ Neil Armstrong ] 21-September-2012 00:00 GMT


Thanks

**Comment by brianteeman** [comment]
Your joomla version is very very out of date and insecure
Your php version is end of life and insecure

Update everything and your problems will be solved
