### ISSUE TITLE
Tag Permissions not honoured in Article Edit

### ISSUE THREAD

**Issue by Terrox** [joomla/joomla-cms#8833]
I posted this in the forum. http://forum.joomla.org/viewtopic.php?f=708&t=903378

#### Steps to reproduce the issue
Set Permissions of Tag component to prevent Create for all access except Super Admin
Edit Article and create a new tag

#### Expected result
Should not be able to create a new tag when not permitted

**Comment by ggppdk** [comment]
I think with "permission" you mean "access level",
so your question is duplicate, it missed this thread:
https://github.com/joomla/joomla-cms/issues/8569

**Comment by Terrox** [comment]
No I mean tag component permissions, not ACL on a tag.

**Comment by ggppdk** [comment]
hhmm, i miss-read your original post, 
i thought you meant per indivudual tag permissions,
i will test

**Comment by ggppdk** [comment]
Tested with J3.5.0 beta,

I confirm the bug, 
- the "create" ACL of tag component is respected in the tags management, 
- but it is not used / respected in article edit form, in article edit form an editor is always allowed to create 

but the edit permission is also broken in 3 ways
if the user is not given "edit" ACL then 
- the existing tag assigments are not shown, they should be shown as readonly
- the user despite not having edit , user can still change them
- if user does not change them, and just saves the form, the old tag assignments are lost

strange how these have escaped or are these recently introduced bugs ?

**Comment by andrepereiradasilva** [comment]
@ggppdk @Terrox i think this is solved in latest staging. can you confirm?

**Comment by ggppdk** [comment]
without testing now, I do remember that i had tested a PR that fixed this

**Comment by andrepereiradasilva** [comment]
ok i think it's solved by this https://github.com/joomla/joomla-cms/pull/11211

**Comment by brianteeman** [comment]
I am closing this at this time as resolved by #11211 if that isnt the case it can always be reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8833">issues.joomla.org/joomla-cms/8833</a>.</sub>
