### ISSUE TITLE
Unknown column 'header' in 'field list' SQL=SELECT `new_url`

### ISSUE THREAD

**Issue by tiagovtg** [joomla/joomla-cms#8836]
ALTER TABLE `#__redirect_links` ADD COLUMN `header` smallint(3) NOT NULL DEFAULT 301;

**Comment by sovainfo** [comment]
See https://github.com/joomla/joomla-cms/pull/8788

Suggest to close this issue.

**Comment by tiagovtg** [comment]
tks
