### ISSUE TITLE
Hi, my site abvgdeika.kz is working, but when I try to go to the address abvgdeika.kz/administrator gives the material a 404 not found

### ISSUE THREAD

**Issue by Kazaku** [joomla/joomla-cms#8837]
Hi, my site abvgdeika.kz is working, but when I try to go to the address abvgdeika.kz/administrator gives the material a 404 not found![screen shot 2016-01-04 at 08 23 00](https://issues.joomla.org/uploads/1/0950c801a77f26e31774366ebe89fa3e.png)

**Comment by sovainfo** [comment]
Use forum.joomla.org for issues in your infrastructure. Properly report the issue when it turns out the code can be improved.

Suggest to close this issue as this is not code related!
