### ISSUE TITLE
Pressing enter/return on create menu takes you to create menus page

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#8839]
#### Steps to reproduce the issue

Create a new menu item, fill in the required fields, press enter/return.

#### Expected result
Expected behaviour is save menu item (and return to menu in question). i.e. exactly the same as save & close.

#### Actual result

You arrive at the create menus page.  The item does not get saved.

#### System information (as much as possible)

System Information
Setting	Value
 
PHP Built On	Linux mail.sfworksdev.co.uk 2.6.32-431.5.1.el6.x86_64 #1 SMP Wed Feb 12 00:41:43 UTC 2014 x86_64
Database Version	5.5.37
Database Collation	utf8_general_ci
PHP Version	5.4.37
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36

**Comment by brianteeman** [comment]
I can confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8839">issues.joomla.org/joomla-cms/8839</a>.</sub>

**Comment by infograf768** [comment]
Tests here show that this happens ONLY when the pointer is focussed inside a field, whether the menu item (and anything else in joomla back-end btw, each redirecting to different pages) is new or not.
When it is not new, it checks out the item.

Afaik enter/return has never be equivalent to Save in J. It only works for Search.

**Comment by infograf768** [comment]
It "could" work with a supplementary js targetting keyCode == 13 for keydown for the Save button I guess.

**Comment by Fedik** [comment]
Correct behavior for Joomla admin forms, when you push Enter:
nothing happens

Because we use JavaScript `Joomla.submitform` to submit the forms in administrator side, when user explicitly pushes the Save or Close or any other button.

Described here issue happens due `<button>` tag in new modal markup, that inside our `<form>` , that make `<form>` behavior like described in the first comment here.

**Comment by Fedik** [comment]
in theory, the solution is to add `type="button"` (like `<button type="button">...</button>`) to all these buttons in the modal markup, or replace them to simple `<a>` tag

**Comment by Fedik** [comment]
Fix is more hard than I expected ... need to search all call of `JHtml::_('bootstrap.renderModal',...` and edit `'footer' => '<button ...`  :smile: 
Hope there will be someone more brave than me :smile:

**Comment by wojsmol** [comment]
@Fedik  If will not find anyone brave the next few hours, I can handle this. Currently in Poland it is 4 in the morning and I have to rest :smile:

**Comment by wojsmol** [comment]
@Fedik @brianteeman @infograf768 @uglyeoin  please test PR https://github.com/joomla/joomla-cms/issues/8874

**Comment by wojsmol** [comment]
@wilsonge Please close as https://github.com/joomla/joomla-cms/pull/8874 is marged :smile:

**Comment by wilsonge** [comment]
Ty!

**Comment by uglyeoin** [comment]
Thanks
