### ISSUE TITLE
Tags Permisions not observed by Article or Category create screens

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#8840]
#### Steps to reproduce the issue

In Tags >>> Options set Create for Manager 'Denied'
Create a new user set User Group as Manager
Login as the new user create an Article in the Tag field type a new tag and press enter ... save the Article
Create a new Category in the Tag field type a new tag and press enter ... save the Category
Perform the creation Front and Back end
#### Expected result

No new Tag should be created
#### Actual result

New Tags are created even though Create Tag is 'Denied' for that user group

**Comment by brianteeman** [comment]
Reset priority according to documented standards https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8840">issues.joomla.org/joomla-cms/8840</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Setting in Tag-Options `Create: Denied` a user cannot create a Tag in Frontend. Looks like Issue is solved, tested on Joomla! 3.7.0-staging.

**Comment by brianteeman** [comment]
Can not confirm on current staging - must have been fixed elsewhere and can be closed @zero-24
