### ISSUE TITLE
Retrieving session expiration in wrong unit

### ISSUE THREAD

**Issue by renekorss** [joomla/joomla-cms#8843]
Docs and therefore source code too claims that `JSession::getExpire` returns expiration in minutes. But it is initialised as seconds. See [here](https://github.com/joomla/joomla-cms/blob/9e948130acb79d189255625df47c0b57afc00534/libraries/cms/application/cms.php#L718) and [here](https://github.com/joomla/joomla-cms/blob/3cfe5ab695825b5ed8edf22a8c227c7974968de9/libraries/joomla/factory.php#L595).

If session lifetime is set to 30 minutes in backend, it returns 1800.

Also, it is used to set `session.gc_maxlifetime` in [here](https://github.com/joomla/joomla-cms/blob/ea1abff73885def195d5bbe30b34b0a9d117013f/libraries/joomla/session/session.php#L906), which takes seconds.

So it works well, just description is misleading.

**Comment by Bakual** [comment]
Do you want to do a PR to change the description?

**Comment by renekorss** [comment]
Yes, no problem.

**Comment by Bakual** [comment]
Thanks. Closing this issue since we have a PR.

**Comment by Bakual** [comment]
Also copied description of the issue to the PR.
