### ISSUE TITLE
Hebrew article layout broken

### ISSUE THREAD

**Issue by mirono** [joomla/joomla-cms#8845]
#### Steps to reproduce the issue
This is the article definition:

<h4 dir="rtl"><img src="images/img_0555.jpg" border="0" alt="משפחת אופיר" title="משפחת אופיר" hspace="5" width="300" align="right" style="float: right; border: 0; margin: 5px;" />יעל ומירון אופיר</h4>
<p dir="rtl"><a href="index.php?option=com_content&amp;view=article&amp;id=46&amp;Itemid=2">יעל ומירון נפגשו ב-1993 ונישאו ב-1995 בקיבוץ עינת.</a> כיום אנו מתגוררים בדירה חמודה ביהוד.</p>
<h4 dir="rtl">דור עדי ויובל אופיר</h4>
<p dir="rtl">דור נולד ב-2002, עדי ב-2004 ויובל ב-2009.</p>

#### Expected result
In the old Joomla it was like in joomla1.ong

#### Actual result
Layout broken, like in joomla2.png

#### System information (as much as possible)
Setting 	Value
 
PHP Built On 	Linux ognius.com 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64
Database Version 	5.5.46-0ubuntu0.14.04.2
Database Collation 	utf8_general_ci
PHP Version 	5.6.16-2+deb.sury.org~trusty+1
Web Server 	nginx/1.4.6
WebServer to PHP Interface 	fpm-fcgi
Joomla! Version 	Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0 

#### Additional comments
Can provide additional information if needed.![screen shot 2016-01-05 at 08 54 02](https://issues.joomla.org/uploads/1/6844614193edc2094bf41a37b5f11e98.png)
![screen shot 2016-01-05 at 08 54 06](https://issues.joomla.org/uploads/1/e4ed1fba5777d19f46749c3993cbfc31.png)

**Comment by brianteeman** [comment]
Old Joomla = ???

**Comment by mirono** [comment]
Joomla! 2.5.11 Stable [ Ember ]

**Comment by brianteeman** [comment]
Sounds like an issue with your template.
As this tracker is for bugs in the core of Joomla I am closing this.

For support please use one of the following
http://forum.joomla.org
http://www.joomla.org.il/%D7%A4%D7%95%D7%A8%D7%95%D7%9D.html

On 5 January 2016 at 20:12, mirono <notifications@github.com> wrote:

> Joomla! 2.5.11 Stable [ Ember ]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8845#issuecomment-169118314>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
