### ISSUE TITLE
Upload large files

### ISSUE THREAD

**Issue by adriannx** [joomla/joomla-cms#8847]
Hello, 

I have configure the php.ini on my panel WHM, 

post_max_size 3000M
upload_max_filesize 400M
max_input_time 356
memory_limit 556M
max_execution_time 356

and configure "SecResponseBodyLimit"

The hard limit for 'SecResponseBodyLimit' is 1073741824 

I have gone ahead and increased the limit to the maximum. It is still possible that this limit is still to small. If that's the case then I may need to to either disable ModSecurity for this site.

But i do not wanna disable "ModSecurity", there is some alternative solution for uploading the large videos?

The idea is to upload videos of 400Mb per file and 3GB quantity.

Best Regards!

**Comment by brianteeman** [comment]
Hi

This is the issue tracker for BUGS etc in the core of Joomla - not for general support. Please use the forum http://forum.joomla.org
