### ISSUE TITLE
nginx, wrong base['path']

### ISSUE THREAD

**Issue by samanmohamadi** [joomla/joomla-cms#8849]
Hi, I use nginx with php-fpm in server .This condition  " `strpos(php_sapi_name(), 'cgi') !== false` "  [here](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/uri/uri.php#L156) cause `$script_name` to come from `$_SERVER['PHP_SELF']` (which is empty) instead of `$_SERVER['SCRIPT_NAME]`. so it makes baseurl empty and other problem.
I remove this condition temporarily to fix this issue.
should I change nginx config to fix it ?

**Comment by adamasantares** [comment]
Hi,
I'm not sure, but as I think you need to update php5-fpm config (host's pool). I think you can define the PHP_SELF manually...

**Comment by brianteeman** [comment]
Did you resolve this - it sounds like a server config issue and not a real joomla issue as many people use nginx for their joomla sites.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8849">issues.joomla.org/joomla-cms/8849</a>.</sub>

**Comment by samanmohamadi** [comment]
Resolved, The issue was from bad php and nginx configuration.
working setup : 

nginx : 
```
    location ~ \.php(.*)$ {
        include fastcgi_params;
        fastcgi_split_path_info       ^(.+\.php)(.*)$;
        fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
        fastcgi_param  PATH_INFO          $fastcgi_path_info;
        fastcgi_param  PATH_TRANSLATED    $document_root$fastcgi_path_info;


        fastcgi_pass unix:/var/run/php-fpm/php-fpm.sock;
        fastcgi_index index.php;
    }

```

php.ini : 
```
  cgi.fix_pathinfo=1
```
