### ISSUE TITLE
Multiple Login After Session Expiration

### ISSUE THREAD

**Issue by DigitalArtifex** [joomla/joomla-cms#8851]
#### Steps to reproduce the issue
Log in (tested with the Super User Account) and allow the session to expire. Log back in.

#### Expected result
Your session has been re-established since you provided proper credentials.

#### Actual result
A statement claiming your session has expired and asking you to log in, yet again.

#### System information (as much as possible)
PHP Built On 	Linux xxx x86_64
Database Version 	5.5.45-cll-lve
Database Collation 	latin1_swedish_ci
PHP Version 	5.4.43
Web Server 	Apache/2.4.12
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (X11; Linux x86_64; rv:43.0) Gecko/20100101 Firefox/43.0 

#### Additional comments
This happens in both front-end and back-end portions of the site and this installation of Joomla! has no plugins.

**Comment by identifican** [comment]
i have the same problem with the last update...

**Comment by andrepereiradasilva** [comment]
i can confirm this bug

**Comment by wilsonge** [comment]
Please try https://github.com/joomla/joomla-cms/pull/9619
