### ISSUE TITLE
Joomla SQL with sourcer

### ISSUE THREAD

**Issue by santosh1312** [joomla/joomla-cms#8857]
I wish to write a simple SQL to pull all fields from a joomla table & display in tabular form.
Using Joomla 3.4 & 'Sourcerer' plugin.

I am struggling for the last two days because lot of error messages.
Can anyone help me in giving a sample program.

**Comment by brianteeman** [comment]
This is the issue tracker for bugs and development of the core of joomla. For support please use the forum http://forum.joomla.org
