### ISSUE TITLE
Can't install languages/extensions on Joomla 3.4.8

### ISSUE THREAD

**Issue by sural98** [joomla/joomla-cms#8860]
Joomla 3.4.8 on Wampserver 64b (Apache 2.4.9, PHP 5.5.12, MySQL 5.6.17) for Windows
1- Cannot install languages
**Warning
Update: Could not open update site #3 "Accredited Joomla! Translations", URL: http://update.joomla.org/language/translationlist_3.xml**
BUT I can see the content at http://update.joomla.org/language/translationlist_3.xml
2- Cannot "install from web"
**Warning
Update: :Extension: Could not open http://appscdn.joomla.org/webapps/jedapps/webinstaller.xml
Error connecting to the server: Failed to connect to appscdn.joomla.org port 80: Timed out**
BUT I can see the content at  http://appscdn.joomla.org/webapps/jedapps/webinstaller.xml
On the other hand packages can be installed separately via ext manager.

**Comment by brianteeman** [comment]
Are you still having this problem? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8860">issues.joomla.org/joomla-cms/8860</a>.</sub>

**Comment by Jomimerlu** [comment]
I have the same issue. not let me install the component installation tab. Joomla does not let me update. The error that is;
Update: Could not open update site # 3 "Accredited Translations Joomla!", URL: http://update.joomla.org/language/translationlist_3.xml

**Comment by brianteeman** [comment]
This usually means that there is a problem connecting from your web server and you should speak to your hosts to make sure they havent blocked access.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8860">issues.joomla.org/joomla-cms/8860</a>.</sub>
