### ISSUE TITLE
SortableList.js: Drag&Drop sorting does not work with lines/elements of different height

### ISSUE THREAD

**Issue by svenbluege** [joomla/joomla-cms#8861]
#### Steps to reproduce the issue

* create three articles
** two normal articles
** one with a very long title
* open the articles list in the back end
* place the article with the very long title in the middle of the two others
* reload the page
* now drag and drop the article with the very long title to the top
* check the xhr request which is going out

![screen shot 2016-01-08 at 10 26 32](https://issues.joomla.org/uploads/1/be2d27942233f4507e1840b3a61989a1.png)

#### Expected result

Sorting lines with different heights should work

#### Actual result

If I sort lines with different heights I get random results since two item have the same ordering value.

**Comment by brianteeman** [comment]
I can not replicate this issue

**Comment by svenbluege** [comment]
@brianteeman Did you checked the console output I highlighted? Sometimes it seems to work but the order[] values which are send to the server should be disjunctive. In the highlighted example it's 113 instead of 123

**Comment by brianteeman** [comment]
Closed as we have a PR #9049 - please test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8861">issues.joomla.org/joomla-cms/8861</a>.</sub>
