### ISSUE TITLE
spelling error in /media/media/js/popup-imagemanager.js (imave  vs. image )

### ISSUE THREAD

**Issue by BastianWie** [joomla/joomla-cms#8865]
#### Steps to reproduce the issue
N/N

#### Expected result
string image in comment instead imave

#### Actual result
Comment shows imave

#### System information (as much as possible)
Joomla 3.4.8

**Comment by BastianWie** [comment]
Hm, looks like its already fixed inside:
https://github.com/joomla/joomla-cms/blob/staging/media/media/js/popup-imagemanager.js<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8865">issues.joomla.org/joomla-cms/8865</a>.</sub>

**Comment by 810** [comment]
then you can close the issue

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8865">issues.joomla.org/joomla-cms/8865</a>.</sub>
