### ISSUE TITLE
Can't search web install on install failure

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#8866]
I tried to install komento using the web install tab which failed and then tried to do a search and was unable to as shown
![capture](https://cloud.githubusercontent.com/assets/1850089/12217260/15f3fd4e-b6c1-11e5-90af-b0533fed5cf2.JPG)

**Comment by brianteeman** [comment]
I just tested and couldnt install komento either - but thats an issue with that extension and not joomla - perhaps hit the report button for that extension on the JED
I tried to search for another extension immediately after and had no problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8866">issues.joomla.org/joomla-cms/8866</a>.</sub>

**Comment by N6REJ** [comment]
strange, search has failed 3x on me to start...
Bear

**Comment by N6REJ** [comment]
fix by upgrading suhosin to the very latest version available.

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8866">issues.joomla.org/joomla-cms/8866</a>

**Comment by infograf768** [comment]
Closed as not Joomla core<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8866">issues.joomla.org/joomla-cms/8866</a>.</sub>
