### ISSUE TITLE
Recaptcha error

### ISSUE THREAD

**Issue by cdekok** [joomla/joomla-cms#8877]
Sometimes if the recaptcha is invalid during a refresh i get this error:
```
Warning: Invalid argument supplied for foreach() 
```
There seems to be a to do no idea what was supposed to be done, but adding a empty / array check around it will atleast avoid the error.
https://github.com/joomla/joomla-cms/blob/staging/plugins/captcha/recaptcha/recaptcha.php#L199

**Comment by brianteeman** [comment]
closing as we have a PR for testing #9305 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8877">issues.joomla.org/joomla-cms/8877</a>.</sub>
