### ISSUE TITLE
J! 3.4.8/3.5beta: IDN email displayed punycoded

### ISSUE THREAD

**Issue by Hoffi1** [joomla/joomla-cms#8880]
Let's say we have a Contact with email "lieschen@müller.de" and configured to show it on frontend.
Then we get a link (href) ```mailto:lieschen@xn--mller-kva.de``` which is ok, but also text "```lieschen@xn--mller-kva.de```" shown.

That's because ```JHtml::_('email.cloak',...``` is used which doesn't convert text to show back to utf-8.

I'll provide a PR soon... :smile:

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8880">issues.joomla.org/joomla-cms/8880</a>

**Comment by infograf768** [comment]
Closing as we have a patch

https://github.com/joomla/joomla-cms/pull/8881<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8880">issues.joomla.org/joomla-cms/8880</a>.</sub>
