### ISSUE TITLE
after upgrading to joomla 3.4.8, not able to login in the administrator

### ISSUE THREAD

**Issue by blackcondorweb** [joomla/joomla-cms#8883]
I upgraded my site from 3.2.x to 3.4.8 and after that i was not able to login.
after a week of searching and trying out the fixes from forums, i found out that the one causing my problem is that the session.secure-cookie setting in my php.ini was set to 1.

setting it to 0, i was able to login in 3.4.8.

i wonder why even though its value was set to 1, 3.2.x is just working fine. but 3.4.8 is not.

my php version is 5.4.44 on squeeze.

can you guys possibly confirm setting secure-cookie to 0 will not compromise the joomla site?

thanks

**Comment by roland-d** [comment]
I can confirm I can't login to:
* Joomla 2.5.28
* Joomla 3.3.6
* Joomla 3.4.4
* Joomla 3.4.8

when I have session.cookie_secure set to 1. So I don't think it is something new.

Like you I wonder why it is set to one as per default it is turned off in php.ini

**Comment by blackcondorweb** [comment]
hi @roland-d 

thanks for your reply.
i am thinking though that it is set 1 in our server because we are using https.

i'll be deploying j 3.4.8 (with https) in a while so i will know if it will make any difference if the value is 0 or 1.

**Comment by PhilETaylor** [comment]
Unable to replicate.

Steps taken:

1) Build a one-click server with Joomla 3.4.8 installed at DigitalOcean
2) SSH and change the php.ini setting session.cookie_secure = 1
3) Restart apache
4) install letsencrypt and install a SSL Certiicate
5) restart apache
6) Go to admin /administrator/ and login 
7) Result: I'm logged in... 

![screen shot 2016-01-12 at 12 57 02](https://cloud.githubusercontent.com/assets/400092/12264112/4fb7988e-b92c-11e5-9f09-0105fa27cffc.png)

**Comment by blackcondorweb** [comment]
Hi @PhilETaylor,

Thanks for your confirmation.
I confirmed as well that it doesn't matter whether the cookie_secure is On or Off in the https environment. I can just login to the site with either values.

So maybe I can say that this is not a joomla issue but a configuration mismatch.

Thanks for your help guys and I am closing this now.

**Comment by GitHubLarry2** [comment]
I had this same issue. I did a password reset from the site and also through the database with no luck. I had to restore the backup to gain access to the site. Also users weren't able to login either. Now I would like to update without an issue and I would prefer to keep the php.ini setting session.cookie_secure = 1. Any suggestions? Thank you

**Comment by GitHubLarry2** [comment]
I have upgraded again but I have made sure that my cookie cleaner does't remove the cookie for the site. So far I have no issues but lets see what happens when the cookie expires. At least I know how to recover.
See ya later!

**Comment by PhilETaylor** [comment]
Like I said, I investigated this issue fully and could not replicate the issue
