### ISSUE TITLE
Statistics disabled: Error on search component

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#8885]
#### Issue:
When you have disabled the statistics, you will get a system message on the search component on the backend.

#### Error message:
Gathering statistics disabled. Enable it in the Options. 

#### More info:
Joomla 3.5-beta

**Comment by brianteeman** [comment]
Sorry but what is the problem with that.

On 12 January 2016 at 13:14, Jelle Kok <notifications@github.com> wrote:

> Issue
>
> When you have disabled the statistics, you will get a system message on
> the search component on the backend
> Error message:
>
> Gathering statistics disabled Enable it in the Options
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8885>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by 810** [comment]
The new Statistics plugin has nothing todo with search component, so you shouldn't see the system error on the search component.

**Comment by brianteeman** [comment]
The message is NOTHING to do with the new plugin
The message is referring to the Gather Search Statistics setting in the
components options


On 12 January 2016 at 13:19, Jelle Kok <notifications@github.com> wrote:

> The new Statistics plugin has nothing todo with search component, so you
> shouldn't see the system error on the search component.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8885#issuecomment-170909035>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by 810** [comment]
srry, just realiste it. closing the issue
