### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by adamasantares** [joomla/joomla-cms#8891]
Hi all.
I found a little typo in argument name of JControllerLegacy::display($cachable = false, $urlparams = array());
I think it should be "$cacheable"...

**Comment by roland-d** [comment]
@adamasantares This is not really a typo because the variable name is named as such everywhere in the code. It may be a typo in the English spelling but not something that will be changed in the code as it has no real benefit. Thank you for your contribution.

**Comment by N6REJ** [comment]
@roland-d  please reopen this, the OP is correct... I'll be submitting a PR momentarily.
There are 28 uses of $cacheable in 4 files and 101 uses of $cachable in 41 files.

**Comment by mbabker** [comment]
If it were a class var or a parameter value (like that `fix_adress` thing in JSession), then leaving it alone would have to be the case because it's part of the API.  Internal method variables like that one, just fix them.  Ya, there's no benefit, but if someone wants to fix it what's the big deal?

**Comment by roland-d** [comment]
@N6REJ No need to re-open this, as your PR will be leading once you submit it.

**Comment by N6REJ** [comment]
done ... https://github.com/joomla/joomla-cms/pull/8896

**Comment by N6REJ** [comment]
ok, hopefully I did it right this time.

**Comment by N6REJ** [comment]
done, just waiting for confirmation and testing.
Bear
