### ISSUE TITLE
JObject

### ISSUE THREAD

**Issue by adamasantares** [joomla/joomla-cms#8892]
Sorry for post a question here, but I very want to known about JObject. It was deprecated but no comment about class that can be used instead? Right now JObject is still using in many current code....why?

**Comment by roland-d** [comment]
@adamasantares Questions can be posted on the Joomla! forum, so please post your question there. The URL is http://forum.joomla.org. Thank you.

**Comment by adamasantares** [comment]
ok, thank for reply.
