### ISSUE TITLE
Category Blog layout not work

### ISSUE THREAD

**Issue by KapulaGabor** [joomla/joomla-cms#8898]
#### Steps to reproduce the issue
I would like to displaying the Categories as a Blog. Not the Articles Blog Layout as we all know, but only just Categories:
index.php?option=com_content&view=category&id=1
and I get a Blog layout. (subcategories displayed as a Blog)

If I create a menu item, Item ID is automatically added:
index.php?option=com_content&view=category&id=1&Itemid=110
and the blog layout is gone. Transforming to usual Category List layout what is don't needed.

#### System information (as much as possible)
Joomla 3.4.6 and .7 and .8

**Comment by brianteeman** [comment]
Can you add some images please to better describe what is happening

The url should be either
index.php?option=com_content&view=category&layout=blog
for the blog layout
or
index.php?option=com_content&view=category
for the list layout

So your second example is working exactly as intended but can only happen if you had selected a menu item of type category list. If you had created a menu type of category blog then the view parameter would have been added to the url
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8898">issues.joomla.org/joomla-cms/8898</a>.</sub>

**Comment by KapulaGabor** [comment]
I can not reproduce the situation, I really sorry.

Thank you for your attention.
