### ISSUE TITLE
Smart Search - show result without rights

### ISSUE THREAD

**Issue by syswombat** [joomla/joomla-cms#8901]
Hello 

i found a error in the smart Search Module (Component).

#### Steps to reproduce the issue
if you add a article readable by a spez. group.

Smart search will still find it and give a preview (AjaxSearch) of the word(s) but after you search it will this is correct not find it.

#### Expected result

i Think if you are not logged in and not belong to the group it should not show up the word's

have a nice day
vincent

#### System information (as much as possible)
Joomla 3.4.8

**Comment by ggppdk** [comment]
Hi
by reading your description you mean the 
- Smart search module, words autocomplete is including words from unathorized articles

you should change title of your issue, this is has already been reported here:
https://github.com/joomla/joomla-cms/issues/8655

- also the unpublished articles are included
https://github.com/joomla/joomla-cms/issues/4301

The search index must include all articles regardless of being publication status which may be considered correct, what is not correct is not considering the state when index is queried for word autocomplete.

There is pull request for considering both access and publication status when the search index is being used for word autocomplete here:
https://github.com/joomla/joomla-cms/pull/4401

it does have some effect on the purformance but i do not know how much, i have not tested it

**Comment by brianteeman** [comment]
Thank you for creating this but as it is a duplicate report of #8655 I am closing this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8901">issues.joomla.org/joomla-cms/8901</a>.</sub>
