### ISSUE TITLE
Article loses his associated article when the association is changed in a copy of the original article

### ISSUE THREAD

**Issue by agilare** [joomla/joomla-cms#8907]
In Joomla 3.4.8, when I change the associated article (in other language) of an article previously created with "Save as a copy", an association of the original article is lost.

**Comment by infograf768** [comment]
In fact, when I tested Save as Copy an existing article "article_original" with an association, the association is transferred to the new article "article_original (2)".
This is a bug indeed.

**Comment by infograf768** [comment]
@andrepereiradasilva
Can you look at this? It is quite a bug, as, when editing again the original article (the one who lost its association) we get a Notice and warning when using your https://github.com/joomla/joomla-cms/pull/8914 PR

**Comment by infograf768** [comment]
@andrepereiradasilva 
In fact, the error comes from your PR https://github.com/joomla/joomla-cms/pull/8914 , see there my comments.

In any case, if you can solve this bug here, would be great. I am also looking.

**Comment by infograf768** [comment]
I think I found how to solve this. Making a PR now.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/8918

@agilare 
@andrepereiradasilva

**Comment by brianteeman** [comment]
Closing as we have a PR - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8907">issues.joomla.org/joomla-cms/8907</a>.</sub>
