### ISSUE TITLE
Tagged items view: number of items, dates and headers not shown even if requested

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#8916]
#### Steps to reproduce the issue
Go to Tag Component options and set: Show number of items = Show, Table Headings = Show, Show Date = Published.
Associate a tag to an article.
Go to front-end and select the article, click on the tag to go to tagged items view.

#### Expected result
Headers, number of items and Dates are displayed for the specific tag.

#### Actual result
None of them are shown, just the article title

#### System information (as much as possible)
Joomla 3.4.8 on Windows.

**Comment by brianteeman** [comment]
Reset priority according to docs https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8916">issues.joomla.org/joomla-cms/8916</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #11415<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8916">issues.joomla.org/joomla-cms/8916</a>.</sub>
