### ISSUE TITLE
Category list. Filter "Display #" loses "chosened" style if less then 25 items [3.5.0beta]

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#8919]
I don't know which steps are exactly needed to reproduce the issue.

This is what I did:
- Installed Joomla! 3.5.0-beta  staging 2016-01-17 with demo datas (testing).
- Opened menu item *All Front End Views* > *Article Category List*
- Changed category to: *Sample-Data Articels*.
- Tabulator *Category* > *Subcategory Levels*: ALL
- Saved.

- Went to *Content* > *Articles* > *Options* button
- Tabulator *Blog/Featured Layouts* > *Include Subcategories*: ALL
- Saved

Front end:
- Opened menu item.
- See image:
![chosen-not](https://cloud.githubusercontent.com/assets/11038612/12377765/04dc8c88-bd29-11e5-8225-28ce8f5f762d.png)

- Same result with all selections below 25.

- Changed to 25 or higher
- See image:
![chosened](https://cloud.githubusercontent.com/assets/11038612/12377767/0c92cd3e-bd29-11e5-888e-f9243f4cbe05.png)

- First test Firefox. Second test Chrome.
- No JS console errors.

## Addition:
- Enabled filter field Title for view.
- Searched for "joo".
- Got 4 hits.
- Now Display # always "not chosened".
![chosened-not](https://cloud.githubusercontent.com/assets/11038612/12377809/778fa6f6-bd2a-11e5-8224-e2f8e366a457.jpg)

**Comment by bertmert** [comment]
## Addition 2:
Really strange. All I found out meanwhile: When "not chosened" JHtml method *formbehavior.chosen* is NOT called at all.

Other find:
- Start with clean session:
![11](https://cloud.githubusercontent.com/assets/11038612/12378138/75a78466-bd35-11e5-9b1d-28bc7a32e6ef.jpg)

- Display # set to 25:
![12](https://cloud.githubusercontent.com/assets/11038612/12378141/95e49d36-bd35-11e5-9783-d5f86b78e5ce.jpg)

- Order by title ASC (headline)
![13](https://cloud.githubusercontent.com/assets/11038612/12378145/ac134b3e-bd35-11e5-8f1b-17bb4797fd5d.jpg)

- Order by title DESC (headline)
![14](https://cloud.githubusercontent.com/assets/11038612/12378147/c0c33792-bd35-11e5-8676-8865c279e96e.jpg)

**Comment by bertmert** [comment]
Made some investigations.

Primary reason for behavior above is article "Smart Search" inside category "Joomla!".
In article text there is plugin call
```
{loadmodule finder,Smart Search}
```
Module mod_finder has a line that loads "chosened selects". 
```
JHtml::_('formbehavior.chosen', 'select');
```
When I disable the line
```
#JHtml::_('formbehavior.chosen', 'select');
```
no "chosened selects" anymore. NEVER while paginating through list with articles of category Joomla!.

##BUT (after reactivating line)
Even if article "Smart Search". is NOT in the displayed list you'll see sometimes "chosened selects" while paginating..
It looks like that category list is loading more articles than needed (?).
Or in other words: That too many articles than needed in list are sent through plugins somewhere.

**Comment by brianteeman** [comment]
So its just an issue with the sample testing data?

**Comment by bertmert** [comment]
> So its just an issue with the sample testing data?

1) 

I don't know. It's not forbidden to enter line

```
{loadmodule finder,Smart Search}
```
or any other module call like this that uses formbehavior.chosen. Then you'll see described behavior with or without testing data.

It's not a problem for Protostar. There I will provide a PR (always "chosened style" in category list).

But Beez3 normally doesn't use "chosened selects". There it's a really strange behavior to have sometimes this or that style. I don't know a way to suppress already loaded formbehavior.chosen.

A way could be to use a special CSS class selector instead of "select" in all lines JHtml::_('formbehavior.chosen', 'select');

Please advise! Should Beez3 use "chosened selects" ON ALL PAGES or not? Sometimes it's forced to use them sometimes not.

2)
See comments below headline
 
> BUT (after reactivating line)

I think that's a performance issue. Why are articles sent through plugin events that are not relevant for the list page?
