### ISSUE TITLE
Unable to install Multilingual

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#8922]
with the current staging i'm unable to install a 2nd language for example
and got a javascript error
```
Uncaught TypeError: window.addEvent is not a function
```
![joomla web installer](https://cloud.githubusercontent.com/assets/181681/12378936/3f64ee48-bd4e-11e5-89c5-1f4c4e589f92.png)

something related to mootools removing @dgt41 ?

**Comment by dgt41** [comment]
@alikon yes, we removed Mootools from css installation. Let me check the scripts...

**Comment by dgt41** [comment]
@alikon Can you check https://github.com/joomla/joomla-cms/pull/8924

**Comment by dgt41** [comment]
Set to "closed" on behalf of @dgt41 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8922">issues.joomla.org/joomla-cms/8922</a>
