### ISSUE TITLE
Joomla\Utilities\ArrayHelper::toString() must be of the type array, string given

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#8923]
Argument 1 passed to Joomla\Utilities\ArrayHelper::toString() must be of the type array, string given, called in C:\wamp\www\joomla\libraries\joomla\document\renderer\html\head.php on line 119 

##### J3.5 build from now

**Comment by mbabker** [comment]
I long for the day the CMS enforces proper property types instead of consistently passing invalid arguments all over the API...

**Comment by 810** [comment]
Full error message:
Catchable fatal error: Argument 1 passed to Joomla\Utilities\ArrayHelper::toString() must be of the type array, string given, called in C:\wamp\www\develop\libraries\joomla\document\renderer\html\head.php on line 119 and defined in C:\wamp\www\develop\libraries\vendor\joomla\utilities\src\ArrayHelper.php on line 104

I also get:
Warning: Cannot modify header information - headers already sent by (output started at C:\wamp\www\develop\libraries\vendor\joomla\utilities\src\ArrayHelper.php:104) in C:\wamp\www\develop\libraries\kunena\error.php on line 264

**Comment by Leen29** [comment]
Hi I had the same thing in VirtueMart 3.0.12 and in Kunena in my test with Joomla 3.5 beta 2
then I adjusted the head.php at line 114 thru 125 turn off
/libraries/joomla/document/renderer/html/head.php 
maybe you can so continue with this solution that works for me
![headphpuitl](https://cloud.githubusercontent.com/assets/17086048/12854008/8cda6318-cc37-11e5-9c69-5f4f45b63d39.JPG)
[head.zip](https://github.com/joomla/joomla-cms/files/119595/head.zip)


on line 119

**Comment by 810** [comment]
The fix has just merged, on the next version it will be there. or you can download the package on git, and overwrite the files.

**Comment by 810** [comment]
closing this issue, since its merged.
