### ISSUE TITLE
Cannot update from Joomla 3.1.5 to 3.4.8

### ISSUE THREAD

**Issue by tanjenting** [joomla/joomla-cms#8927]
Hi,
I would like to update from Joomla 3.1.5 to 3.4.8 because our website have security issue before.
I just recovered it by Akeeba kickstart. 

I download Joomla_3.4.8-Stable-Update_Package.zip and try to update by extension manage with below 2 methods. The maximum upload file size is also changed to 16MB in PHP setting. 
1. Upload Package File
2. Install from Directory

Both can not succeed. At the same time, I update my Phoca download with method 1 and it works well. Please help to advise the solution. Thanks in advance.

Best regards,
Oscar

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.Joomla.org
