### ISSUE TITLE
Number form field negative number issue

### ISSUE THREAD

**Issue by mrDand0r** [joomla/joomla-cms#8928]
#### Steps to reproduce the issue
1. Create a number form field in a view form xml with the following minimum settings: 
<pre>
    name="mynumber" 
    type="number" 
    default="0" 
    min="-123" 
</pre>
2. Create a new item using the above form data
3. The form field shows a value of -123 (wrong)
4. Then set the value of the 'mynumber' field to 0 (zero) and save
5. The form field will again show the min-value of -123 (wrong)

#### Expected result
Correct behavior when using negative values

#### Actual result
If the value is set to <= 0 the field value is set to its min-value.
Also the default value is ignored and the field's min-value is used instead.

#### System information (as much as possible)
Joomla 3.5, PHP 5.6

#### Additional comments
I did some research on the form field code and it seems that the "empty value detection" is not working as expected. Since empty(0) will return true, the specified min-value will always be used. This is okay as long as you use positive numbers, but fails with negative.

Here's a suggestion on fixing this (File: libraries/joomla/form/fields/number.php:160)

replace

<pre>
$value = (float) $this->value;
$value = empty($value) ? $this->min : $value;
</pre>

with

<pre>
// Make sure to set a valid default value (use min if 'default' not set or 0 if 'default' and 'min' not set)
if($this->value === "") {
     if(isset($this->min)) {
          $value = (float) $this->min;
     } else {
          $value = 0;
     }
} else {
     $value = (float) $this->value;
}
</pre>

**Comment by wilsonge** [comment]
You're minimum data seems to have got lost in the first point - could you edit it please :)

**Comment by mrDand0r** [comment]
Sorry, just edited my post<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8928">issues.joomla.org/joomla-cms/8928</a>.</sub>

**Comment by joomdonation** [comment]
I think replace these two lines of code https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/form/fields/number.php#L160-L161 with this line should solve the issue:

```php
$value = is_numeric($this->value) ? (float) $this->value : $this->min;
```

**Comment by mrDand0r** [comment]
Yes, this fixes the issue.

But if optional "default" and "min" options are not set, $value will get **null** on an empty form.
Maybe it should be set to 0 to perfect this solution.

Something like this?
<pre>
$this->min = isset($this->min) ? $this->min : 0;
$value = is_numeric($this->value) ? (float) $this->value : $this->min;
</pre><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8928">issues.joomla.org/joomla-cms/8928</a>.</sub>

**Comment by brianteeman** [comment]
Closing as we have a PR for testing - see #9336
