### ISSUE TITLE
Check "upload_maxsize" for reasonable value

### ISSUE THREAD

**Issue by jo-sf** [joomla/joomla-cms#8938]
In the Joomla media management you can configure a maximum size for file uploads in megabytes, the default value is 10 MB. The tooltip informs you that the server has a maximum value for file uploads, but there is no feedback about the maximum reasonable value.

You might e.g. define a maximum size of 40 MB, and when uploading a file you get a message with this configured value. But when you send a file with about this size to the server you finally get the error message "This file is too large to upload" (here I assume that the system limit is smaller than the size of the file uploaded).

This happens with the current Joomla version 3.4.x as well as with previous versions.

It would be very helpful if you already get a warning (at least) when you save the options of the Joomla media management in the case that the maximum size value set is larger than the actual system limit.

I already inspected the source code whether there is any place where the options were checked prior to being saved in the database, but the only idea I found was that it would be necessary to implement a specific rule for that form field that implements the check against the actual system limit.

Moreover I found the method JFilesystemHelper::fileUploadMaxSize() which returns the maximum upload size (one small caveat with this method though: it doesn't cope with the `memory_limit` setting whereas this setting is checked too when it comes to a file upload, see: administrator/components/com_media/controllers/file.php).

If performing the check of the "upload_maxsize" option is best done by implementing a specific rule for that purpose then please inform me and I'll try to implement that rule and change the Joomla media management options form such that the rule will be applied to the value the user entered.

**Comment by brianteeman** [comment]
Thank you for submitting this issue/pull request. The media manager is currently being completely rewritten and I have notified the development team about this issue for their consideration. I am closing this here at this time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8938">issues.joomla.org/joomla-cms/8938</a>.</sub>
