### ISSUE TITLE
Menu Item Type 'List All Categories': category only contains expired articles, but still shows

### ISSUE THREAD

**Issue by Gerlof** [joomla/joomla-cms#8948]
#### Steps to reproduce the issue

Settings: Administrator > Global Article Options > tab Categories > change # Articles in Category to 'show'
#### Expected result

1) Categories containing only expired articles do not show
2) # Articles shown (after Category Title) is excluding # Articles expired
#### Actual result

In frontend, after clicking menu item with Menu Item Type 'List All Categories':
1) the Category containing only expired articles is still showing
2) # Articles expired is also included in # Articles (shown after listed Categories)
#### System information (as much as possible)

Joomla 3.4.8 on localhost
PHP 5.6.17
Windows Server 2008 R2 Standard Edition Service Pack 1))

**Comment by brianteeman** [comment]
"A category is only empty if it has no articles or sub categories"

I have tested this by unpublishing all the articles in a category and setting empty categories to hide. In this scenario the category is not listed. If you add a sub category then the category is correctly listed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8948">issues.joomla.org/joomla-cms/8948</a>.</sub>

**Comment by Gerlof** [comment]
Hi Brian,

Thanks for testing!
Do you mean that what I experience as an issue, actually is expected behaviour?
Right now I am implementing our new intranet environment, and I found it rather confusing that people can see a list of categories > click on it and then discover that the category is empty.
The confusing part is that you do not see all categories available for the menu item, but only the categories containing published/expired articels.

Regards
Gerlof

**Comment by brianteeman** [comment]
Sorry for never responding. Yes it is the expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8948">issues.joomla.org/tracker/joomla-cms/8948</a>.</sub>
