### ISSUE TITLE
Menus:Edit Item - Metadata section - Meta desctiption field for Tagged Items Layout not showing in source code!

### ISSUE THREAD

**Issue by aantic** [joomla/joomla-cms#8950]
#### Steps to reproduce the issue
Open up Menu item of type Compact list of tagged items. Click the tab Metadata and fill in the Meta Description field. Click the button Save or Save and Close!

#### Expected result
The Meta Description should be visible in source code!
If I open up the Tag that Compact list of tagged item is linked to, and click the Publishing tab and fill in the Meta Description and click the button Save or Save and Close, I get the following result in page source:
which is normal:
<meta name="description" content="Neos Marmaras je najveće naselje Sitonije, udaljeno od Soluna 118 km, sa prekrasnim plažama i bogatom sredozemnom vegetacijom..." />

#### Actual result
The Meta Description text is saved but not showing in page source - <meta name="description" content=" " />

#### System information (as much as possible)
Setting 	Value
 
PHP Built On 	Linux server.olympic.rs 2.6.32-431.3.1.el6.x86_64 #1 SMP Fri Jan 3 21:39:27 UTC 2014 x86_64
Database Version 	5.5.46
Database Collation 	latin1_swedish_ci
PHP Version 	5.4.45
Web Server 	Apache
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 6.1; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0 

#### Additional comments
As I mentioned the solution would be to fill in the Tag Meta Description field (Components - Tags) instead of Compact list of tagged menu item's Meta Description field

**Comment by bertmert** [comment]
This is a known issue and first step for fixing it is done (description in menu item)
https://github.com/joomla/joomla-cms/pull/8783

Pls. read also my comments there concerning descriptions for tags.

**Comment by brianteeman** [comment]
closed as per the comment above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8950">issues.joomla.org/joomla-cms/8950</a>.</sub>
