### ISSUE TITLE
My website doesn't work since a week

### ISSUE THREAD

**Issue by stefanodl** [joomla/joomla-cms#8962]
#### Steps to reproduce the issue
My website doesn't work. if i search www.catoodontotecnica.com it keep on charging but nothing happens. Bluehost said me that it is a Joomla problem. Can someone help me? It is very urgent. Thank you soo much.

#### Expected result
My website run regular

**Comment by bertmert** [comment]
Please ask in a forum because here is the issue/bug tracker for Joomla. Wrong place for your problem.
http:\\joomla.forum.org

**Comment by roland-d** [comment]
Closing this issue as it is not a core issue.
