### ISSUE TITLE
Not able to get params onContentBeforeDisplay via  get method in  3.5 beta

### ISSUE THREAD

**Issue by danyj** [joomla/joomla-cms#8963]
Testing 3.5.0 beta, 
in 3.4.8 we can get params via 

	public function onContentBeforeDisplay($context, $article, $params ){
		
		$show_vote = $params->get('show_vote');
		
		print_r($show_vote);

	}

in 3.5.0 beta I get 

    Fatal error: Call to a member function get()....

**Comment by ggppdk** [comment]
This is not controlled by the CMS itself
- but rather it is controlled by the component / extension, that is triggering the event. 

Thus unless it is a CORE component that is passing empty params, this is not a CMS bug of J3.5.0 beta

- many different extensions use it not just the CORE components
 - also some extensions may pass parameters that do not merge joomla global configuration at all, but i guess **they should always pass non-empty params ?**

For start **more specific information is needed**. You need to find the component or extension that is passing empty parameters and the exact place that this is happening. Edit your plugin method onContentBeforeDisplay, and add to it:
```
if ( empty($params) )
{
  echo "<pre>";
  debug_print_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
  echo "</pre>";
  die('Found empty params at ...');
}
```

**Comment by danyj** [comment]
@ggppdk  Thnx for the reply 
it is core , and joomla article category or item view, any content plugin that is requesting params in 

    onContentBeforeDisplay

is failing , 

here is your print 
![screenshot_16](https://cloud.githubusercontent.com/assets/2340172/12525116/38badcc0-c162-11e5-9d5a-83bfe683472e.jpg)


params are there , 
http://prntscr.com/9tkg41
the thing is that  

    $params->get

does not function on 3.5

I have 3 content plugins and they all have same issue.

**Comment by danyj** [comment]
I can "fix " my plugins by doing 

	if ( empty($params) ){
		return;
	}

in my functions but thing is that this worked without any issues before.

**Comment by ggppdk** [comment]
In current staging the events are triggered twice:

- once in JViewLegacy  with ->core_params which does not exist, thus the effect that you see
- and once in all views that extend JViewLegacy  e.g. ContentViewCategory 

https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/view/category.php#L161-L168

the empty parameters are coming from the 1st triggering, which should be easy to fix by replacing ->core_params with ->params 

about double event triggering i don't know

See conversation here:
https://github.com/joomla/joomla-cms/pull/8024
@wilsonge @mbabker

**Comment by danyj** [comment]
Thnx for the info , I will keep an eye on that thread.
