### ISSUE TITLE
Back-end: "Start Publishing" date is empty if article is published via "Publish Item" icon in Status column of Articles page

### ISSUE THREAD

**Issue by Wizard13** [joomla/joomla-cms#8964]
#### Steps to reproduce the issue
Create a new article, but before you save it, set Status to Unpublished.
Then, in the Articles page, where you see all the articles in a list, click the "Publish Item" icon (the white X in a red circle) in the Status column to publish the article.

#### Expected result
The article is now published and has a "Start Publishing" date.

#### Actual result
The article is now published, but does NOT have a "Start Publishing" date.

#### System information (as much as possible)
Joomla 3.4.8
Windows 7
PHP 5.4.45
MySQL 5.5.46

#### Additional comments
Without a "Start Publishing" date, modules like "Articles Latest" do not show this article. I have to manually go and set a "Start Publishing" date for the module to show it.

**Comment by bertmert** [comment]
Is known already
https://github.com/joomla/joomla-cms/issues/8740

Related PR is waiting for tests.

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8964">issues.joomla.org/joomla-cms/8964</a>

**Comment by infograf768** [comment]
Closed as there is a PR to test

https://github.com/joomla/joomla-cms/pull/8745<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8964">issues.joomla.org/joomla-cms/8964</a>.</sub>
