### ISSUE TITLE
Feeds are accessible when site is offline

### ISSUE THREAD

**Issue by Nepoh** [joomla/joomla-cms#8965]
When the site is in offline mode, access to all pages is denied and the offline message is displayed instead. But when the feed version of a page is requested (by adding ``?format=feed`` to the URL), the feed is returnd as if the site was not in offline mode.

#### Steps to reproduce the issue

- Take a newly installed Joomla site offline ("Site Offline" option in the Global Configuration)
- Try to access the main page that is created by default for new Joomla installations (a featured articles blog) in HTML and atom format. E.g.
  - ``/index.php`` vs. ``/index.php?format=feed``
  - or ``/index.php?option=com_content&view=featured`` vs. ``/index.php?option=com_content&view=featured&format=feed``

#### Expected result

When trying to access a feed, HTTP Error "503 Service Temporarily Unavailable" is returned and access to the resource is denied. The description in the configuration clearly says "Select whether access to the Site Frontend is available." so i would expect that all access is denied when the site is offline.

#### Actual result

The feed is returned (status code 200) as if the site was not in offline mode.

#### System information (as much as possible)

Fresh Joomla 3.4.8 installation on XAMPP for Windows

**Comment by brianteeman** [comment]
Sorry but thats now what "site offline" means

http://magazine.joomla.org/issues/issue-feb-2011/item/378-how-offline-is-joomla-offline-mode

On 22 January 2016 at 20:12, Nepoh <notifications@github.com> wrote:

> When the site is in offline mode, access to all pages is denied and the
> offline message is displayed instead But when the feed version of a page is
> requested (by adding ?format=feed to the URL), the feed is returnd as if
> the site was not in offline mode
> Steps to reproduce the issue
>
>    - Take a newly installed Joomla site offline ("Site Offline" option in
>    the Global Configuration)
>    - Try to access the main page that is created by default for new
>    Joomla installations (a featured articles blog) in HTML and atom format Eg
>       - /indexphp vs /indexphp?format=feed
>       - or /indexphp?option=com_content&view=featured vs
>       /indexphp?option=com_content&view=featured&format=feed
>
> Expected result
>
> When trying to access a feed, HTTP Error "503 Service Temporarily
> Unavailable" is returned and access to the resource is denied The
> description in the configuration clearly says "Select whether access to the
> Site Frontend is available" so i would expect that all access is denied
> when the site is offline
> Actual result
>
> The feed is returned (status code 200) as if the site was not in offline
> mode
> System information (as much as possible)
>
> Fresh Joomla 348 installation on XAMPP for Windows
> Additional comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/8965>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Nepoh** [comment]
That is unfortunate. I'm even more astonished after reading the article - thanks for the hint.
