### ISSUE TITLE
No login possible in front or backend

### ISSUE THREAD

**Issue by jjsjjs** [joomla/joomla-cms#8976]
#### Steps to reproduce the issue
Tunr on debug and error reporting

#### Expected result
JROOT\administrator/language/en-GB/en-GB.plg_system_jdom.ini : error(s) in line(s) 69
expected to login again but no......
at least the error is gone
No other errors, still no possibility to log-in
#### Actual result
the actual line in that file is:
JDOM_ADDRESSPICKER_Edit="Edit"

 while it should be:
JDOM_ADDRESSPICKER_EDIT="Edit"

#### System information (as much as possible)
Joomla 3.4.8

**Comment by brianteeman** [comment]
That is nothing to do with the core of joomla and is an add-on you have
written or installed. Please contact the developer of that add-on for
support.
