### ISSUE TITLE
When an admin disables the Show Email Icon in the content configuration,mail-to friend direct link possible

### ISSUE THREAD

**Issue by joomlolo** [joomla/joomla-cms#8979]
#### Steps to reproduce the issue

I disable show email icon, but Google references "http://mywebsite.fr/component/mailto/?tmpl=component&template=protostar&link=[random numbers]",also my template is not protostar but one I bought in a club the name is "risen_hope",I have to disable mailto in phpmyadmin and disallow url in robots.txt.

#### Expected result

When an admin disables the Show Email Icon in the content configuration, mail-to friend direct link must be desactived. 

#### Actual result

email can be sent directly by url and it is referenced by Google

#### System information (as much as possible)

joomla 3.4.8

#### Additional comments
on/off for "send to a friend",no direct link access(spamming),icon mail off = "send to a firend" off
still the same:
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=31636

http://forum.joomla.fr/showthread.php?208696-url-component-mailto-tmpl-component-index%C3%A9
so sorry for my bad English,but it is important so I prefer to tell about this it can be used for spamming

**Comment by infograf768** [comment]
I confirm the email can be sent here with
component/mailto/?tmpl=component&template=protostar&link=db9bf1e83606585c892e8eb7eb8bfcc71c0cbb8c

But if I change one figure in the random numbers (which I got from before disabling Show Email Icon), I get a message that Email could not be sent.

**Comment by brianteeman** [comment]
Yes that is correct - without a valid link (which you cant get unless it is published) while the form will appear it cannot be sent.

If google is referencing those links on YOUR site then it can only be because they were indexed on YOUR site when YOU had it enabled. If you no longer have those links you can either wait for google to update its index or use the google webmaster tools to remove them.

**Comment by joomlolo** [comment]
ok thanks infograf768 and brianteeman, it is jut my fault I understand,thanks.
