### ISSUE TITLE
PHP Fatal error when session times out

### ISSUE THREAD

**Issue by C-Lodder** [joomla/joomla-cms#8980]
- **Joomla 3.5-dev**
- **Environment**: Wampserver
- **PHP**: 5.5.12
- **MySQL**: 5.6.17
- **Database Collation**: utf8_general_ci
- **Session Handler**: database 

With the changes that have been made to the Session package, I'm now receiving 2 errors when the session times out in the backend:

```
Fatal error: Uncaught exception 'RuntimeException' with message 'The session is not started.' in C:\dev\joomla\libraries\joomla\session\handler\native.php on line 221
RuntimeException: The session is not started. in C:\dev\joomla\libraries\joomla\session\handler\native.php on line 221
```

The error appear when the session times out and I'm redirected back to the login page

![session](https://cloud.githubusercontent.com/assets/2019801/12565932/fb268b58-c3ae-11e5-94f9-9c879a7e76fe.png)

**Comment by brianteeman** [comment]
is this the same as #8808<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8980">issues.joomla.org/joomla-cms/8980</a>.</sub>

**Comment by wilsonge** [comment]
Closing as a duplicate
