### ISSUE TITLE
The BATCH and the DELETE button should be NOT together

### ISSUE THREAD

**Issue by PhilETaylor** [joomla/joomla-cms#8981]
![screen shot 2016-01-26 at 05 19 10](https://cloud.githubusercontent.com/assets/400092/12573084/740dd43a-c3ec-11e5-81e2-42899476bfaa.png)
I propose a change where the BATCH and the DELETE button are moved apart. 

In order to run a BATCH process you need to select a lot of "things" (say users in user manager) and then you move your mouse up to the BATCH button to run a batch process (like force password reset) - however it is also very very very very (note very) easy to click the delete button by mistake and thus all the entries that you have selected for batch process (lets say, 1000 users) are now deleted with no further "are you sure!?" messages - they are gone.. zip nada... gone... and then you have to waste an hour reinstalling from backup... if you had a backup... feel my pain here????

So a simple change that can ensure that quick clicking mistakes are avoided....

**Comment by Bakual** [comment]
We could also add a "Are you sure" message to the delete button in the user manager. I think the user manager is the only place where you directly can delete items. Other components have a "trash" state, you can't directly delete items from published state in those.

**Comment by Fedik** [comment]
:+1: for confirmation message here

**Comment by infograf768** [comment]
Direct Delete is also present for Templates styles, Overrides and Media

**Comment by PhilETaylor** [comment]
I prefer not to be asked "are you sure" - just distance the batch from the delete butttons by rearranging the order :) a quick fix with no additional JS to code/test :) Less chance of a slip and deleting 1000 users..

**Comment by infograf768** [comment]
We could just add a margin as this would work everywhere in core:
```
#toolbar-delete {
	margin: 0 20px 0 20px;
}
```
would give

![screen shot 2016-01-26 at 10 33 28](https://cloud.githubusercontent.com/assets/869724/12577073/561e737c-c418-11e5-86b9-50fe3e4967df.png)

**Comment by Fedik** [comment]
I think if action cannot be undone the confirmation is required, as you can push that button accidentally, no matter you place it, ... especially if you work with the kids near you :wink:

**Comment by infograf768** [comment]
or cats... ;)

**Comment by Bakual** [comment]
Afaik, the confirmation is already an option present for the delete button. You just need to activate it.

I wouldn't move the buttons, or you would have to move it in all places to be consistent.

**Comment by ssnobben** [comment]
Could I also mention something else that is very scary and that is.

Extension -- Manage --Manage left column and 

Let say you have many modules and you filter all and then you want to Refresh Cache then but by mistake instead press Uninstall. Here better to move Uninstall away from Refresh Cache..

**Comment by infograf768** [comment]
Now preparing a patch implementing an alert for all delete cases (Delete and Empty Trash buttons) and Uninstall.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/8995
Thank you for testing

**Comment by Bakual** [comment]
Closing as we have a PR.
