### ISSUE TITLE
Installation - js error when changing default language

### ISSUE THREAD

**Issue by alikon** [joomla/joomla-cms#8988]
#### Steps to reproduce the issue
install the current staging and change the default languge
in my case (from default:italian to english)
![installazione di joomla_lingua](https://cloud.githubusercontent.com/assets/181681/12591700/621263c2-c469-11e5-89a1-546142183213.png)

#### Expected result
able to change the language and go to the next step

#### Actual result
not able to go on got a js error spinner undefined
![spinner-js](https://cloud.githubusercontent.com/assets/181681/12591830/03d6326a-c46a-11e5-83a5-2b31dbae0800.PNG)

**Comment by dgt41** [comment]
@alikon but here is no entry at https://github.com/joomla/joomla-cms/blob/staging/installation/template/js/installation.js#L354
So I guess this is a cache problem?

**Comment by alikon** [comment]
i'm afraid of yes 
happend first installing an old 3.4.4  and then the current staing
