### ISSUE TITLE
com_wrapper auto-height error in IE

### ISSUE THREAD

**Issue by Denitz** [joomla/joomla-cms#8989]
javascript code in /media/com_wrapper should have

```
document.frames['blockrandom'].document.body.scrollHeight
```

but not

```
document.frames('blockrandom').document.body.scrollHeight
```

Note that auto-height actually works for IE only.

**Comment by wojsmol** [comment]
@Denitz  plase test https://github.com/joomla/joomla-cms/issues/8991

**Comment by Denitz** [comment]
Looks great!

**Comment by wojsmol** [comment]
@Denitz see https://docs.joomla.org/Testing_Joomla!_patches

**Comment by brianteeman** [comment]
Closing as we have a PR #8991<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8989">issues.joomla.org/joomla-cms/8989</a>.</sub>
