### ISSUE TITLE
"Your session has expired. Please log in again." On admin login page

### ISSUE THREAD

**Issue by marktaylor46** [joomla/joomla-cms#8993]
#### Steps to reproduce the issue
This is happening much more frequently after the J3.4.5 thoruh J3.4.8 updates. I often leave Joomla sites logged in during the day or overnight and naturally my sessions expires and Joomla just shows the login screen. However, when I then enter my login details, that is when I then get the "Your session has expired. Please log in again." message - which is completely bizarre to me, if I then enter the login details again I can log in. It occurs to me that if the joomla admin login screen is displayed for any reason then the obvious thing to do would be to clear down the session so that any entry of login details is then accepted first time around.

Here is a video link to show you what I mean - http://screencast.com/t/FEZmXbnJS

#### Expected result
login successful first time around

#### Actual result
"Your session has expired. Please log in again."

#### System information (as much as possible)
Joomla 3.4.8 any template

**Comment by Devportobello** [comment]
Linked to https://github.com/joomla/joomla-cms/issues/8851

**Comment by brianteeman** [comment]
Closing as a duplicate report<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8993">issues.joomla.org/joomla-cms/8993</a>.</sub>
