### ISSUE TITLE
Article in trashed list, the icon for publish item back should be changed as shows trashbin icon,Which gives user a confusing view whether  to delete it permanently  or not

### ISSUE THREAD

**Issue by jaisheela** [joomla/joomla-cms#9005]
#### Steps to reproduce the issue
1. Go to Content>>Articles
2. Delete Any of the article
3.Select the status as trashed
4.Now check the Status Column
5.Observe the icon or publish item

#### Expected result

Icon needs to be change ,It seems that you have to delete article permanently 

#### Actual result

Icon shows as trash bin

#### System information (as much as possible)

Ubuntu-OS

#### Additional comments

M![screen shot 2016-01-28 at 06 10 40](https://issues.joomla.org/uploads/1/855e2d5aedec33797c8c739b79adeba0.png)

**Comment by brianteeman** [comment]
The icon is displaying the status of the item not the action


On 28 January 2016 at 12:11, jaisheela <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> 1 Go to Content>>Articles
> 2 Delete Any of the article
> 3Select the status as trashed
> 4Now check the Status Column
> 5Observe the icon or publish item
> Expected result
>
> Icon needs to be change ,It seems that you have to delete article
> permanently
> Actual result
>
> Icon shows as trash bin
> System information (as much as possible)
>
> Ubuntu-OS
> Additional comments
>
> M[image: screen shot 2016-01-28 at 06 10 40]
> <https://camo.githubusercontent.com/12738d2ce0cc542d42d96711525d81db14a26688/68747470733a2f2f6973737565736a6f6f6d6c616f72672f75706c6f6164732f312f3835356532643561656465633333373937633863373339623739616465626130706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9005>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by jaisheela** [comment]
I think  we are already in trashed items list,there are no other status other than trash,Whats the use of showing it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9005">issues.joomla.org/joomla-cms/9005</a>.</sub>

**Comment by brianteeman** [comment]
You could be in status all

**Comment by jaisheela** [comment]
I  do agree for status ALL,But when its in trash list that time,its confusing for users and i am asking specifically when status in TRASHED<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9005">issues.joomla.org/joomla-cms/9005</a>.</sub>

**Comment by brianteeman** [comment]
This "issue" is not just for trashed. It is the same for all those icons.
What do you propose?

On 28 January 2016 at 12:54, jaisheela <notifications@github.com> wrote:

> I do agree for status ALL,But when its in trash list that time,its
> confusing for users and i am asking specifically when status in TRASHED
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9005
> <https://issues.joomla.org/tracker/joomla-cms/9005>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9005#issuecomment-176168178>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by jaisheela** [comment]
We can keep restore action ,it will also used for ALL status too

**Comment by brianteeman** [comment]
Closing with other tickets so we just have one for this topic #9359<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9005">issues.joomla.org/joomla-cms/9005</a>.</sub>
