### ISSUE TITLE
Installer ignores mysql statement after a comment

### ISSUE THREAD

**Issue by jsanchezgr** [joomla/joomla-cms#9008]
When installing a component, if the sql file has a line starting with # the following statement will be ignored. 

## SQL Snippet
```
# Insert content history rows

INSERT INTO `#__content_types` (`type_title`, `type_alias`, `table`, `content_history_options`)
...
```
The issue is in `splitSql() `method of `JDatabaseDriver`. where both lines are returned as a single one. After spliting, there is a check to ignore comments, so the entire line (comment and insert) is skipped. 

## JInstaller sinppet where splitSql() is called

```
// Create an array of queries from the sql file
$queries = JDatabaseDriver::splitSql($buffer);

if (count($queries) == 0)
{
	// No queries to process
	return 0;
}

// Process each query in the $queries array (split out of sql file).
foreach ($queries as $query)
{
	$query = trim($query);

	if ($query != '' && $query{0} != '#')
	{
		$db->setQuery($query);

		if (!$db->execute())
		{
			JLog::add(JText::sprintf('JLIB_INSTALLER_ERROR_SQL_ERROR', $db->stderr(true)), JLog::WARNING, 'jerror');

			return false;
		}
	}
}
```

**Comment by brianteeman** [comment]
Closing as we have a PR #9137<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9008">issues.joomla.org/joomla-cms/9008</a>.</sub>
