### ISSUE TITLE
No able to save or update article after update to 3.4.8

### ISSUE THREAD

**Issue by aamaiga** [joomla/joomla-cms#9012]
Hello, 
On the 27th of January I made an update to Joomla 3.4.8
Ever since, it seems that we cannot save anything we cannot save any new article or save changes made to an article.
so far I have tried
- Clearing the Joomla cache from within Joomla
- Clearing browser cache
- verifying that the Text filter is set correctly for users

Now I am at my wits end.
Can someone help me.

**Comment by brianteeman** [comment]
Please use the forum for support for your specific site http://forum.joomla.org
