### ISSUE TITLE
We force an logout on every update (regression)

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#9014]
#### Steps to reproduce the issue

Install beta1
Update e.g. via "Install from URL" to beta2

You can reproduce the Problem also via "over install" beta2 on the updated version.

#### Expected result

Update without problems and without logout.

#### Actual result

Logout...

#### Problem

I know that we need to flush the session once but not on every update since now that makes no sense, thanks. :)

**Comment by zero-24** [comment]
oops wrong cat. Please fix it to "Updating". Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9014">issues.joomla.org/joomla-cms/9014</a>.</sub>

**Comment by brianteeman** [comment]
Updates from beta to beta are not supported.

Unless we know what version they are updating from dont we still need to do it? Someone might be updating from 3.2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9014">issues.joomla.org/joomla-cms/9014</a>.</sub>

**Comment by zero-24** [comment]
>Unless we know what version they are updating from dont we still need to do it? Someone might be updating from 3.2

There need to be better ways to fix that.
You can require to update to 3.4.8 (that fixes that issue) and than you show the 3.5.x updates.

Or something like "isSessionFixed" befor flush it.

But hey i don't need to explain to my clients that on every joomla update they get logged out on every site and need to log in again.

>Updates from beta to beta are not supported.

This has nothing to do with a beta -> beta update :smile: 

Lets say George released 3.5 stable and not beta2 --> same problem.

Update from 3.4.8 -> 3.5.0 should not require a logout and login.

I know the limitations on beta -> beta updates but it also shows problems that the stabel release can have / got :smile: And I reported it here.

**Comment by Kubik-Rubik** [comment]
At the moment this is the only solution that fixes the session problem certainly. We have to get sure that the session is written / refreshed properly. This behavior can be changed in future, we'll think about it.

As this is a known, intentional issue, I will close this item for now.

**Comment by mbabker** [comment]
This needs to be re-opened.  The starting version was a release AFTER the session data handling was changed.  As presented the bug report is fully valid; if upgrading from < 3.4.8 to 3.5 the logout is expected to occur because of all the changes.  But if upgrading from >= 3.4.8 to 3.5 (includes beta-to-beta upgrades, supported or otherwise), the session is at a state that this migration/logout should not be necessary.

**Comment by joomdonation** [comment]
I haven't looked at the code which handle Joomla update, but I think we should have a way to solve this issue. Couldn't we get the current version of the site which is running the update, then only force logout if we upgrade from older version than 3.4.8 ?

Could you send me the link to the code which force logout? I will try to find a way to fix it.

**Comment by mbabker** [comment]
> haven't looked at the code which handle Joomla update, but I think we should have a way to solve this issue. Couldn't we get the current version of the site which is running the update, then only force logout if we upgrade from older version than 3.4.8 ?

No, you cannot.  The upgrade script (which is ultimately where this processing is happening) is first triggered after the filesystem is updated.  At that point it sees the new version number.  You could possibly make a change in the controllers or models to store the old version number in the user state, but that can't be relied on for this update because that code isn't out in production yet.

**Comment by joomdonation** [comment]
Yes. I was thinking about storing the old version number in session (or maybe even in a temp text file)... As I haven't looked at the code yet, so I will stop commenting for now. Someone fully understands the update process should be able to solve this issue.

**Comment by zero-24** [comment]
@wilsonge please add the `3.5.0 Release Blocker` Label here :smile:

**Comment by brianteeman** [comment]
Closing as we have a PR. please help test #9230
