### ISSUE TITLE
Joomla! 3.5 Beta 2 - Fatal Error when session expires

### ISSUE THREAD

**Issue by Kubik-Rubik** [joomla/joomla-cms#9015]
If the session expires in the backend you will be redirected to the login form (good) but an Fatal Error is thrown (bad):

```Fatal error: Uncaught exception 'RuntimeException' with message 'The session is not started.' in Joomla_3.5.0-beta2-Beta-Full_Package\libraries\joomla\session\handler\native.php:221 Stack trace: #0 [internal function]: JSessionHandlerNative->save() #1 {main} thrown in Joomla_3.5.0-beta2-Beta-Full_Package\libraries\joomla\session\handler\native.php on line 221```

@tampe125 Is it related to the changes you've provided for the session fix?

**Comment by tampe125** [comment]
Please take a look at #8808 and #9011

**Comment by Kubik-Rubik** [comment]
@tampe125 Damn, should have checked first the pull requests... :-) Thank you for the fast reply!
