### ISSUE TITLE
Administrator: Joomla icon in left upper corner does not link to /administrator anymore

### ISSUE THREAD

**Issue by Gerlof** [joomla/joomla-cms#9017]
#### Steps to reproduce the issue
1) open Administrator in 3.5.0beta2
2) try to click on Joomla icon in left upper corner
3) nothing happens

#### Expected result
Same behaviour as 3.4.8: clicking on Joomla icon redirects to /administrator (=shortcut to control panel)

#### Actual result
Nothing happens after click on icon

**Comment by infograf768** [comment]
I can't reproduce the issue here on staging.

**Comment by brianteeman** [comment]
I can't reproduce the issue here on staging.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9017">issues.joomla.org/joomla-cms/9017</a>.</sub>

**Comment by Gerlof** [comment]
Update: problem was caused by admin module 'Switch Editor' that was published in position 'menu'.
After unpublishing this module, the Joomla icon is clickable again.

Regards
Gerlof<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9017">issues.joomla.org/joomla-cms/9017</a>.</sub>

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9017">issues.joomla.org/joomla-cms/9017</a>.</sub>
