### ISSUE TITLE
New subitem after beining moved one position up goes on first position while drag and drop

### ISSUE THREAD

**Issue by tomaszs** [joomla/joomla-cms#9019]
#### Steps to reproduce the issue

1. Create a menu, where you have main item and 20 submitems.
2. Set display to 5 items per page
3. Move 10th subitem before 9th subitem but still under a main item.

#### Expected result

Subitem from 10th position is now on 9th position.

#### Actual result

Submitem is on first position.

#### System information (as much as possible)

Joomla! 3.4.8 Stable.

#### Additional comments

Problem lasts for some months now with previous Joomla versions also.

**Comment by brianteeman** [comment]
I have followed your instructions and I can not replicate it https://www.dropbox.com/s/i21on59tdo69ahq/9018.mp4?dl=0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9019">issues.joomla.org/joomla-cms/9019</a>.</sub>

**Comment by tomaszs** [comment]
I've viewed your replication test. Thank you for doing it. It seems you don't have this issue. Do you have an idea what can be other on my setting that makes it work wrong? Or what data i would need to provide to figure it out?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9019">issues.joomla.org/joomla-cms/9019</a>.</sub>

**Comment by brianteeman** [comment]
Sorry I cant think what may be causing it for you.

On 1 February 2016 at 11:54, tomaszs <notifications@github.com> wrote:

> I've viewed your replication test. Thank you for doing it. It seems you
> don't have this issue. Do you have an idea what can be other on my setting
> that makes it work wrong? Or what data i would need to provide to figure it
> out?
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9019
> <https://issues.joomla.org/tracker/joomla-cms/9019>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9019#issuecomment-177935963>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Did you resolve this? There was a report that there were issues if an item was so long it split onto two rows but this has been resolved in current staging<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9019">issues.joomla.org/joomla-cms/9019</a>.</sub>

**Comment by tomaszs** [comment]
Hello Brian,

Last time i checked i still had the issue. In what version was it fixed? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9019">issues.joomla.org/joomla-cms/9019</a>.</sub>

**Comment by brianteeman** [comment]
It will be in 3.5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9019">issues.joomla.org/joomla-cms/9019</a>.</sub>

**Comment by tomaszs** [comment]
Thanks for info. When it will go public i will update and try if it fixed things. I let you know.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9019">issues.joomla.org/joomla-cms/9019</a>.</sub>

**Comment by brianteeman** [comment]
I am closing it for now - it can always be re-opened if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9019">issues.joomla.org/joomla-cms/9019</a>.</sub>
