### ISSUE TITLE
Inappropriate term used in User Status admin module

### ISSUE THREAD

**Issue by jtherczeg** [joomla/joomla-cms#9020]
#### Steps to reproduce the issue

1. Login to a Joomla! Backend.
2. See the status bar at the bottom of the screen.

On the status bar of the Joomla! backend the "visitor" term is used for the displaying the number of the logged in users.

The term visitor means a general visitor of the site (check the privacy policies), not logged in to the private area, without any privileges and this may be deceptive for a new user, he/she may think this value shows the number of the total users currently browsing the site.

It would be highly recommended to replace this term with "registered" or "members" for version 3.5 as this module has been improved now.

**Comment by brianteeman** [comment]
Pull Requests welcome
See https://docs.joomla.org/My_first_pull_request_to_Joomla!_on_Github<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9020">issues.joomla.org/joomla-cms/9020</a>.</sub>

**Comment by jtherczeg** [comment]
Done, see https://github.com/joomla/joomla-cms/pull/9030<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9020">issues.joomla.org/joomla-cms/9020</a>.</sub>

**Comment by Bakual** [comment]
Closing as we have a PR.
