### ISSUE TITLE
Text rendering 'g' issues with Firefox and isis in User management

### ISSUE THREAD

**Issue by alexrij** [joomla/joomla-cms#9021]
#### Steps to reproduce the issue
Browser is firefox 44 on OS X. Joomla 3.4.8. I understand that text rendering issues (like 'g' and p not fully visible) with Firefox and isis backend template were fixed in earlier Joomla release as discussed in #5521 and #5456. I still have this issue in User management. ![Screenshot](https://issues.joomla.org/uploads/1/bf64b8064d672bba9e5bd3dad8509bfd.jpg)

#### Expected result
Appreciate to see a patch for this

thx Alex

**Comment by brianteeman** [comment]
Can you try again with the screenshot please

**Comment by alexrij** [comment]
thx, fixed now

Met vriendelijke groet,

Alex Rijpsma

e-mail: alex.rijpsma@gmail.com
Telefoon: 036-5384642
Mobiel: 06-51352994

**Comment by brianteeman** [comment]
Sorry - I cannot replicate this using the same firefox 44 on OS X. Joomla 3.4.8.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9021">issues.joomla.org/joomla-cms/9021</a>.</sub>

**Comment by alexrij** [comment]
thx for your feedback, i searched again and found a fix to the isis template css that fixed the issue.

`input[type=text], input[type=password], input[type=email], input[type=tel] {     height: 28px !important; }`
