### ISSUE TITLE
Joomla Calendar widget "change" event not firing for the input field

### ISSUE THREAD

**Issue by MatthewDaggitt** [joomla/joomla-cms#9025]
When the default calendar widget is used to choose a date, the "change" event for the attached input field is not fired.

#### Steps to reproduce the issue

Create a field of type="calendar" in an admin form. Then run the following script to attach the function to catch the "change" event.

    var calendar = jQuery(...);
    calendar.change(function() {
        console.log("hi");
    });

#### Expected result

When typing in the box or selecting the date from the calendar widget with the mouse, the string "hi" should be logged to the console.

![screen shot 2016-01-29 at 13 33 26](https://issues.joomla.org/uploads/1/dd1219fa95df8526308c8a8d6eadd78d.)

#### Actual result

The string "hi" is only logged to the console when typing in the box, not when a date on the calendar widget is clicked.

#### System information (as much as possible)

Joomla 3.4!

#### Additional comments

This is really irritating if you want to write some custom validation for two dates that depend on each other (e.g. start date and end date).

**Comment by flash1452** [comment]
@MatthewDaggitt I think a better way to trigger this event will be to use datepicker of Jquery 
http://stackoverflow.com/questions/11610797/trigger-function-when-date-is-selected-with-jquery-ui-datepicker

**Comment by MatthewDaggitt** [comment]
@flash1452 Thanks for your reply. Unfortunately (correct me if I'm wrong) I don't think the Joomla calendar widget uses the JQuery datepicker. Certainly `jQuery("#form_startdate").datepicker` is undefined.

Even if it does, shouldn't the Joomla calendar widget implement the standard event API?

**Comment by flash1452** [comment]
@MatthewDaggitt  If the standard event API is not working in this case then I think we can go for this little hack if it is possible.

**Comment by Ruchiranga** [comment]
Hi,
I am trying to reproduce the issue but I don't have a clear idea on how to perform "Create a field of type="calendar" in an admin form".
Could you please provide a detailed set of steps?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9025">issues.joomla.org/joomla-cms/9025</a>.</sub>

**Comment by MatthewDaggitt** [comment]
So in _admin/models/forms/event.xml_ I have:

    <?xml version="1.0" encoding="utf-8"?>
    <form>
	<fieldset>
         ...
         <field 
			name="startdate" 
			type="calendar" 
			label="Start date" 
			default="2016-01-01"
			description="The date the event starts on? (in the form YYYY-MM-DD)"
			format="%Y-%m-%d"
			class="validate-startdate"
         />
         ...
	</fieldset>
    </form>

and in _admin/views/event/tmpl/edit.php_ I have:

    ...
    <script type="text/javascript">
        var calendar = jQuery('.validate-startdate');
        calendar.change(function() {
            console.log("hi");
        });
    </script>

Is there anything else you need? If needs be I can link the full code of the entire component...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9025">issues.joomla.org/joomla-cms/9025</a>.</sub>

**Comment by brianteeman** [comment]
As the entire code for the calendar has been changed for 3.7 I am closing this. If you still have issues with the calendar code in 3.7 please open a new issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9025">issues.joomla.org/tracker/joomla-cms/9025</a>.</sub>
