### ISSUE TITLE
Hack cleanup question

### ISSUE THREAD

**Issue by FireFly9** [joomla/joomla-cms#9027]
I've just cleaned up a joomla hack on my j3.4.5
These 3 came where installed but which didn't show up on the secur.net search.... _as did a bunch of other ones, but which I did delete_
./libraries/joomla/github/gist.php 
./libraries/joomla/github/issues.php 
./libraries/joomla/github/pulls.php 
I assume I should delete these, as they are not on your list as far as I can see. 

Also there is an entire folder
./libraries/f0f/  (as opposed to fof)

Is it safe to delete this?

**Comment by brianteeman** [comment]
This issue tracker is for bugs with the core joomla software and not for support for specific web sites. Please use the forums for site support http://forum.joomla.org 

BTW f0f is a different version of the fof library used by many extensions<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9027">issues.joomla.org/joomla-cms/9027</a>.</sub>
