### ISSUE TITLE
Articles not loading in home page and single article menu items result in 404 error

### ISSUE THREAD

**Issue by mlstoppa** [joomla/joomla-cms#9028]
**Steps to reproduce the issue**
Go to http://sosdislessia-ferrara.it

**Expected result**
Home article loaded as main menu item is "featured articles".

**Actual result**
Blanks between breadcrumbs position and footer. Links to single articles result in 404 page.

**System information (as much as possible)**
PHP Built On : Linux webxc206rg03s05.ad.aruba.it 3.10.0-229.20.1.el7.x86_64 #1 SMP Tue Nov 3 19:10:07 UTC 2015 x86_64
Database Version : 5.5.46-37.6-log
Database Collation : latin1_swedish_ci
PHP Version : 5.5.31
Web Server : Apache
WebServer to PHP Interface : cgi-fcgi
Joomla! Version : Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version : Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 

**Additional information**
Joomla installation directory : /joomla
Docs root .htaccess (whole content) :
`RewriteCond %{REQUEST_URI} !^/joomla`
`RewriteRule ^(.*)$ joomla/$1 [L] `
/joomla/.htaccess (uncommented content) :
`IndexIgnore *`
`RewriteEngine On`
`RewriteCond %{QUERY_STRING} base64_encode[^(]*([^)]*) [OR]`
`RewriteCond %{QUERY_STRING} (<|%3C)([^s]*s)+cript.*(>|%3E) [NC,OR]`
`RewriteCond %{QUERY_STRING} GLOBALS(=|[|%[0-9A-Z]{0,2}) [OR]`
`RewriteCond %{QUERY_STRING} _REQUEST(=|[|%[0-9A-Z]{0,2})`
`RewriteRule .* index.php [F]`
`RewriteBase /joomla`
`RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]`
`RewriteCond %{REQUEST_URI} !^/index.php`
`RewriteCond %{REQUEST_FILENAME} !-f `
`RewriteCond %{REQUEST_FILENAME} !-d`
`RewriteRule .* index.php [L]`

**Additional comments**
Tries I've already made without result:

- changing template
- disabling plugins (the ones found on the web that might be related to this)
- disabling modules
- using different browser

Thank you for any help

**Comment by brianteeman** [comment]
This sounds like an issue with your redirect as joomla is installed in a subdirectory of your web space.

This issue tracker is for bugs with the core joomla software and not for support for specific web sites. Please use the forums for site support http://forum.joomla.org or http://forum.joomla.it/

**Comment by mlstoppa** [comment]
Already done without success, but I understand. Thank you
