### ISSUE TITLE
Admin Modules on mobile

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9031]
It is not possible to select or create a new admin module on a mobile as the select filter to switch from site to admin modules is inside a div with class hidden-phone

**Comment by brianteeman** [comment]
I had hoped that it would be as simple as removing the hidden-mobile hidden-tablet from here https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/layouts/joomla/searchtools/default/bar.php#L24

That works but doesnt look good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9031">issues.joomla.org/joomla-cms/9031</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman i'm working on it. Tomorrow i should have it done.
See https://github.com/joomla/joomla-cms/compare/staging...andrepereiradasilva:com_modules-modules-searchtools

But i have two doubts:

1. Is the modal view for modules still used?
I didn't found any call to modules modal view in current Joomla staging.
2. Is the ordering (drag and drop) of the modules in current staging working properly?
When draging it disabled a lot of option, but are the right ones disabled?

**Comment by brianteeman** [comment]
Sorry I missed this reply
1. i think it may be used only in the loadmodule editor button
2. not sure what you mean<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9031">issues.joomla.org/joomla-cms/9031</a>.</sub>

**Comment by andrepereiradasilva** [comment]
1. ok thanks. I think there is no way yet to put searchtools JLayouts on modals.
2. is resolved now see https://github.com/joomla/joomla-cms/pull/9120

**Comment by brianteeman** [comment]
The only thing I was referring to in this issue was that in mobile views the option to switch between site and admin is missing
![mwpo 1](https://cloud.githubusercontent.com/assets/1296369/13140996/04d12bf0-d62d-11e5-8a0f-b6f1a3e6f749.png)

in #9101 for langauges you resolved it
![w7cf](https://cloud.githubusercontent.com/assets/1296369/13141069/44e12f2e-d62d-11e5-90bb-ed64872d6695.png)

**Comment by andrepereiradasilva** [comment]
that also happens in menus view.
When i have time i will try to do a PR for resolving that issue in all views.

**Comment by brianteeman** [comment]
Thanks - I will leave this open for now

**Comment by andrepereiradasilva** [comment]
PR https://github.com/joomla/joomla-cms/pull/9151
Please test.
