### ISSUE TITLE
Lots of queries requesting article tags.

### ISSUE THREAD

**Issue by shur** [joomla/joomla-cms#9036]
I discovered that Joomla generates lots of queries requesting article tags. Often tag queries are unnecessary when tags are not used at all on a certain page, but these queries are still retrieved.

## How to test
Let's show e.g. 15 articles on a category blog page: _New Menu Item > Articles > Category Blog_
Leading Articles: 1
Intro Articles: 4
Links: 10

In _Joomla! Debug Console > Database Queries_ we have lots of similar queries like this:

```
SELECT `m`.`tag_id`,`t`.*

  FROM `sj3d2_contentitem_tag_map` AS m 

  INNER JOIN `sj3d2_tags` AS t  
  ON `m`.`tag_id` = `t`.`id`

  WHERE `m`.`type_alias` = 'com_content.article' 
  AND `m`.`content_item_id` = 36 
  AND `t`.`published` = 1 
  AND t.access IN (1,1)
```

This query retrieves tag information for an article, so there will be 15 such queries (one for each article we show).

**We decided not to show tags on this category page**. We go to menu item settings: 
_Options >  Show Tags : Hide_

There is no more tags on this category page. Now let's have a look at Database Queries in Joomla! Debug Console again. **We see nothing has changes, and we still get 15 queries for tag information that is not going to be used on this page**.

**Let's go further and show Articles Category Module on this category page**. In this module we show 15 articles from the same category. Something like this:
![category-blog-page](https://cloud.githubusercontent.com/assets/1245155/12701777/a5b264d2-c825-11e5-9f14-0922650aefdd.png)

Let's check how Database Queries have changed.
**We see +15 similar tag queries**. If it happens that articles in blog category and in the module are the same, the queries will be duplicated, which Joomla! Debug Console will inform you about.

## Summary
**We have a simple category page with one module. There are no tags showed on this page, but we still have 30 unnecessary tag queries:**
- 15 queries belong to Category Blog with settings Show Tags: Hide;
- 15 queries belong to Articles Category Module which never shows any tags.

I find such results awful and bad for site performance. Tags are not always used, often they are used just for several categories on a site, while the others don't use tags at all.
Why not making such categories display quicker?

## Possible fix

_Debug Console > Query Call Stack_ helped me to localize where it happens: 
`	JHelperTags->getItemTags()	JROOT\components\com_content\models\articles.php:663`

Open articles.php file and [find lines](https://github.com/joomla/joomla-cms/blob/staging/components/com_content/models/articles.php#L661):
```
			// Get the tags
			$item->tags = new JHelperTags;
			$item->tags->getItemTags('com_content.article', $item->id);
```

**Add condition depending on article Show Tags settings** so that we get tag information only when it's necessary: 

```
			// Get the tags
			if ($item->params->get('show_tags')) {
				$item->tags = new JHelperTags;
				$item->tags->getItemTags('com_content.article', $item->id);
			}
```

### Before:
**54 Queries** (includes 30 duplicates)
Database queries total: 66 ms
![category-blog-page-before](https://cloud.githubusercontent.com/assets/1245155/12701789/3bc8cbbe-c826-11e5-80cb-f47ac8364c9d.png)

### After:
**24 Queries** (0 duplicates)
Database queries total: 41 ms
![category-blog-page-after](https://cloud.githubusercontent.com/assets/1245155/12701791/48534954-c826-11e5-8ed1-458151419c58.png)

The results speak for themselves. 
**I'm not sure how valid my fix is**. **But I'm sure that this issue must be solved, and cannot be left as it is now**. Because creating tag queries for every article in cases when it's unnecessary seems to me a big mistake which can have a negative impact on site performance.

**Comment by brianteeman** [comment]
Please can you submit a PR so that people can test this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9036">issues.joomla.org/joomla-cms/9036</a>.</sub>

**Comment by shur** [comment]
> Please can you submit a PR ...

Done

**Comment by brianteeman** [comment]
Thanks - closing as we have a PR for testing #9038 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9036">issues.joomla.org/joomla-cms/9036</a>.</sub>

**Comment by shur** [comment]
Joomla 1.7.2 have LOTS of duplicate queries:

Joomla Debug Console:
![j172_duplicate-queries-for-tags](https://cloud.githubusercontent.com/assets/1245155/26489671/037edb52-4211-11e7-8dc7-b40af5c23c8f.png)

Duplicate Queries Example:
![j172_duplicate-queries-example](https://cloud.githubusercontent.com/assets/1245155/26489680/10397898-4211-11e7-9687-80f9f8cb352c.png)

Modules "Articles - Latest" and "Articles - Most Read" displaed on Category blog page.
THIS MODULES DON'T SHOW TAGS! So why do they create so many tag request queries?

**Comment by zero-24** [comment]
@shur i think the best would be to do a new PR / issue as this is closed since 1 Feb 2016.
