### ISSUE TITLE
Add support for URLs with no protocol in JDocumentRenderer

### ISSUE THREAD

**Issue by kavadas** [joomla/joomla-cms#9039]
#### Steps to reproduce the issue
Create an article with text containing a URL with no protocol. A good example could be an embed of a dailymotion video which contains no protocol in the iframe src of the embed code. Then try to view a feed containing that article. 

#### Expected result

The expected result is that the iframe src is not modified.

#### Actual result

Joomla tries to replace all relative links to absolute links in feeds. The function _relToAbs of JDocumentRenderer class considers incorrectly that URLs with no protocol are relative links and prepends the site's absolute URL to them.

#### System information (as much as possible)

Checked under Joomla! 3.4.8 and 3.5 BETA 2.

**Comment by brianteeman** [comment]
Not tested but what happens if it starts with //

**Comment by kavadas** [comment]
It prepends the site's URL in that case. So the src attribute becomes http://yoursite.com///www.dailymotion.com/embed/video/x3okfgt . <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9039">issues.joomla.org/joomla-cms/9039</a>.</sub>

**Comment by brianteeman** [comment]
I have no problem with that embed in an article when using no-editor or
when using tinymce (after allowing iframe in the plugin)

On 1 February 2016 at 12:29, Lefteris Kavadas <notifications@github.com>
wrote:

> It prepends the site's URL in that case. So the src attribute becomes
> http://yoursite.com///www.dailymotion.com/embed/video/x3okfgt .
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9039
> <https://issues.joomla.org/tracker/joomla-cms/9039>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9039#issuecomment-177951128>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by kavadas** [comment]
This is not related with the editor. The video is fine in the article page. The issue occurs in feed views where the JDocumentRenderer _relToAbs function is called. Try to view the RSS feed of the article's category and you should be able to reproduce the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9039">issues.joomla.org/joomla-cms/9039</a>.</sub>

**Comment by brianteeman** [comment]
Sorry I missed that part of your instructions. Will test again later.

**Comment by brianteeman** [comment]
I can confirm it now. If you have a fix please submit a pull request<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9039">issues.joomla.org/joomla-cms/9039</a>.</sub>

**Comment by ggppdk** [comment]
First, all embed urls if not having a protocol, should start with at least //   
all these fail
src="//www.youtube.com/embed/..."
src="//player.vimeo.com/video/..."
src="//www.dailymotion.com/embed/video/..."

@brianteeman  the fix is what you implied 
that '//' should be detected as absolute and not as releative by the relToAbs function

https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/document/renderer.php#L86
```
$text = preg_replace("/(href|src)=\"(?!http|ftp|https|mailto|data)([^\"]*)\"/", "$1=\"$base\$2\"", $text);
```
should be added the detection of '//'
aka be add |\/\/
```
$text = preg_replace("/(href|src)=\"(?!http|ftp|https|mailto|data|\/\/)([^\"]*)\"/", "$1=\"$base\$2\"", $text);
```

**Comment by kavadas** [comment]
The solution is indeed that simple. The regular expression should just ignore the URLs with no protocol. I have applied the exact same fix that @ggppdk provided and it's working for me.

**Comment by brianteeman** [comment]
Can you please create a Pull Request for this and then we can get this
fixed in the core

On 2 February 2016 at 08:51, Lefteris Kavadas <notifications@github.com>
wrote:

> The solution is indeed that simple. The regular expression should just
> ignore the URLs with no protocol. I have applied the exact same fix that
> @ggppdk <https://github.com/ggppdk> provided and it's working for me.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9039#issuecomment-178453262>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wojsmol** [comment]
@brianteeman @kavadas Olease test PR https://github.com/joomla/joomla-cms/pull/9046

**Comment by brianteeman** [comment]
Closing as we have a PR for testing #9046 Please test it so it can be accepted and merged<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9039">issues.joomla.org/joomla-cms/9039</a>.</sub>
