### ISSUE TITLE
Template "Menus assignment" is not available from the start at 3.4.8

### ISSUE THREAD

**Issue by kricore** [joomla/joomla-cms#9040]
This is more of a UX issue.
When you install a new template, which is not assigned to any menu items the "Menus assignment" tab is not available in the styles menu Extensions->Templates->Template.

It is only accessible after navigating to a menu item and manually assigning that particular template to a menu item. This creates some confusion.

**Comment by brianteeman** [comment]
Please can you give an example of a template where this is the case as I
cannot confirm this - sounds like an issue with the template

On 1 February 2016 at 12:04, Krikor Boghossian <notifications@github.com>
wrote:

> This is more a UX issue
> When you install a new template, which is not assigned to any menu items
> the "Menus assignment" tab is not available in the styles menu
> Extensions->Templates->Template
>
> It is only accessible after navigating to a menu item and manually
> assigning that particular template to a menu item This creates some
> confusion
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9040>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by kricore** [comment]
The odd thing using a different setup it works fine. 
Same template as well.

I will try to replicate the issue and the circumstances (all other templates where manually assigned to am menu item) and report it in a new post.
