### ISSUE TITLE
UTF-8 encoded tweets sent as unknown characters

### ISSUE THREAD

**Issue by mabdelaziz77** [joomla/joomla-cms#9043]
When using JTwitterStatuses class to send UTF-8 encoded statuses/tweets, they show as unknown characters.

**Comment by brianteeman** [comment]
@mbabker should this be an issue on the framework repo?

**Comment by mbabker** [comment]
Here and there, the CMS is still using the Platform version of all the API packages.

**Comment by brianteeman** [comment]
Thanks @mbabker for clarifying.

Closing as we have a PR
