### ISSUE TITLE
Blank (white) admin screen - not possible to load backend

### ISSUE THREAD

**Issue by radik10** [joomla/joomla-cms#9048]
#### Steps to reproduce the issue
install joomla 3.5.0 beta2 and try to login in to the administrator area

#### Expected result
open admin area

#### Actual result
blank (white) screen - there is error messasge (if you change $error_reporting = 'maximum'; in configuration.php):
"Fatal error: Can't use method return value in write context in ...administrator\modules\mod_version\helper.php on line 36"

#### System information (as much as possible)
Database Version: 5.5.25a
Database Collation: utf8_general_ci
PHP Version: 5.4.4
Web Server: Apache/2.4.2 (Win32) OpenSSL/1.0.1c PHP/5.4.4

**Comment by brianteeman** [comment]
Hi - thanks for reporting this.

It has however already been reported and fixed in the current staging release. Yu can verify this by downloading the current staging from https://github.com/joomla/joomla-cms/archive/staging.zip

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9048">issues.joomla.org/joomla-cms/9048</a>

**Comment by infograf768** [comment]
This has been solved in staging. See https://github.com/joomla/joomla-cms/pull/9003

Closing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9048">issues.joomla.org/joomla-cms/9048</a>.</sub>
