### ISSUE TITLE
The component menu in admin area is bigger than the higth and I can not access the last menus

### ISSUE THREAD

**Issue by fpaixao** [joomla/joomla-cms#9051]
![screen shot 2016-02-02 at 11 08 41](https://issues.joomla.org/uploads/1/00edec756c7d5ed91c6d377ada669ad2.png)#### Steps to reproduce the issue

#### Additional comments

The component menu in admin area is bigger than the higth and I can not access the last menus

**Comment by rdeutz** [comment]
there are a couple of issues already e.g. #5131 

Closing because this is a duplicate
