### ISSUE TITLE
Dangling fieldset in com_contacts default_form

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#9052]
there is a extra closing fieldset in the end of the form.

**Comment by N6REJ** [comment]
somehow I think I managed to do this wrong ;(

**Comment by brianteeman** [comment]
see #9055<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9052">issues.joomla.org/joomla-cms/9052</a>.</sub>

**Comment by richard67** [comment]
@N6REJ could you check PR #9055 and if ok, close this one here? I just tested PR #9055 with success.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9052">issues.joomla.org/joomla-cms/9052</a>.</sub>

**Comment by brianteeman** [comment]
Closed see #9055 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9052">issues.joomla.org/joomla-cms/9052</a>.</sub>

**Comment by N6REJ** [comment]
@brianteeman why was a new ticket made and a new pr?

**Comment by N6REJ** [comment]
@richard67 ty for testing.
