### ISSUE TITLE
Joomla won't update 3.3.6 to 3.4.8

### ISSUE THREAD

**Issue by texas1114** [joomla/joomla-cms#9063]
We restored a previous version of our website with Akeeba Backup, and are now trying to update our Joomla version from 3.3.6 to 3.4.8, but it is not updating. Some of the updates must have worked because we have the following in our Post-installation and upgrade messages, but the footer still says that we are in version 3.3.6:

- Since version 3.4.0
COM_CPANEL_MSG_HTACCESS_BODY
[Hide this message]
COM_CPANEL_MSG_ROBOTS_TITLE

- Since version 3.3.0
COM_CPANEL_MSG_ROBOTS_BODY
[Hide this message]
COM_CPANEL_MSG_LANGUAGEACCESS340_TITLE

- Since version 3.4.1
COM_CPANEL_MSG_LANGUAGEACCESS340_BODY
[Hide this message]

Does anyone have any experience with this?

**Comment by brianteeman** [comment]
This is the issue tracker for bugs and development of new features in the core of joomla. For specific help on your site please use the forum http://forum.joomla.org
