### ISSUE TITLE
Opensearch tag missing if caching enabled for search module

### ISSUE THREAD

**Issue by osignell** [joomla/joomla-cms#9065]
#### Steps to reproduce the issue

Create a search module, enable "OpenSearch Autodiscovery"
Enable caching for the Joomla site (conservative in my case, probably also progressive)
Load a page on the frontend several times.
#### Expected result

Opensearch LINK tag visible in HEAD on every page load.
#### Actual result

LINK tag is only visible the first time the page is loaded. No tag is visible on subsequent loads when there is cached version of the module stored in cache/mod_search
#### Additional comments

I fixed this temporarily on my site by disabling caching for the search module.

Is there a framework in place for including <head> tags for cached modules? I would assume the same situation might arise if a cached module loads a stylesheet or adds a javascript file. Is the "nohead" parameter in the JCache class related to this?

**Comment by brianteeman** [comment]
Confirmed on 3.5.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9065">issues.joomla.org/joomla-cms/9065</a>.</sub>

**Comment by mbabker** [comment]
In `JCache::setWorkarounds()` there is [an array](https://github.com/joomla/joomla-cms/blob/5d08c452a35e0ee49e2ab81b5b99a5e87a1f7261/libraries/joomla/cache/cache.php#L672) declaring what properties returned from `JDocumentHtml::getHeadData()` are ignored.  The OpenSearch tag is in one of the ignored properties.

**Comment by franz-wohlkoenig** [comment]
@mbabker so this Issue is expected behavior?

**Comment by mbabker** [comment]
As it is currently coded, yes.  That doesn't necessarily mean it is the right behavior.

**Comment by franz-wohlkoenig** [comment]
@mbabker then ist no issue and can be closed?

**Comment by mbabker** [comment]
It depends on how you look at it.  As the code is written, it is not an issue.  However, is the behavior as described when this issue was opened one that should not be addressed?

**Comment by franz-wohlkoenig** [comment]
@mbabker right. How to deal with this kind of Question > Button "PLT-Decision"? It's about don't losing Community-Input.

**Comment by ghost** [comment]
Status is set on "Needs Review".

**Comment by brianteeman** [comment]
From my perspective it is definitely a bug because I would expect/want this to be on every page and it doesnt make sense to remove it from the cache. We already have code if a cached module loads a stylesheet or adds a javascript file to make sure thats always there

**Comment by brianteeman** [comment]
Thank you for raising this issue. 

Joomla 3 is now in security only mode with no further bug fixes or new features.

As this issue doesn't relate to Joomla 4 it will now been closed. 

If we are mistaken and this does apply to Joomla 4 please open a new issue (and reference this one if you wish) with updated details for testing in Joomla 4.
cc @zero-24
