### ISSUE TITLE
"Set ItemID" parameter does not work in Smart Search module

### ISSUE THREAD

**Issue by nguyenanh91** [joomla/joomla-cms#9071]
Whatever set in that field, search results will always be displayed with the ItemID of homepage menu (When there's no menuitem of com_finder in the menu system)

I changed the code of **modules/mod_finder/helper.php** at line 48:
```php
if ($needId)
{
	$id = JFactory::getApplication()->input->get('Itemid', '0', 'int');
	$fields[] = '<input type="hidden" name="Itemid" value="' . $id . '" />';
}
```
to:
```php
if ($needId)
{
	$id = $paramItem ? $paramItem : JFactory::getApplication()->input->get('Itemid', '0', 'int');
	$fields[] = '<input type="hidden" name="Itemid" value="' . $id . '" />';
}
```

**Comment by brianteeman** [comment]
Closing as we have a PR #9072

@nguyenminh797 You do not need to create an Issue on the tracker and a pull request on github. Just create the pull request and it will be automagically on the issue tracker<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9071">issues.joomla.org/joomla-cms/9071</a>.</sub>
