### ISSUE TITLE
Cant select category during a forntend article Joomal 3x

### ISSUE THREAD

**Issue by philbertphotos** [joomla/joomla-cms#9082]
When a user editing tries to create an article from the frontend they are unable to choose a category unless they first save the article. This is a bit of a problem since they have to reedit the article just to move it to the correct category.

![02072016-160231](https://cloud.githubusercontent.com/assets/2892474/12875069/3b881514-cdb8-11e5-9835-f2ef03a04a9a.png)

**Comment by infograf768** [comment]
Looks like you are using a "Submit Article" menu item which has the option "Default Category" set to "Yes"

**Comment by brianteeman** [comment]
Agree with @infograf768 comments above. If you are still having problems please use the forum for support on your site http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9082">issues.joomla.org/joomla-cms/9082</a>.</sub>
