### ISSUE TITLE
Table Mysql inexistante à l'installation

### ISSUE THREAD

**Issue by gesualda** [joomla/joomla-cms#9085]
#### Actual result
installation joomla 3.5.2 (test en local)

[quote]
=> Lien admin : informations systeme
Erreur :
1146 La table 'performance_schema.session_variables' n'existe pas SQL=SHOW VARIABLES LIKE "collation_database"[/quote]
Apparemment la base n'est pas créer à l'installation

#### System information (as much as possible)
php 5.6.18 / 7.0.3
mysql 5.5.24 / 5.7.11
Apache 2.4.18

**Comment by MATsxm** [comment]
Bonjour @gesualda 

Il est préférable de parler anglais ici ou sur le Issue Tracker et as-tu d'abord cherché une réponse sur le forum ? http://forum.joomla.org/ 
ou même sur le forum français ? http://forum.joomla.fr/


>> Can be Closed by maintainers and reopen (in english :wink:)  if needed
