### ISSUE TITLE
Multiple reCaptcha on same page

### ISSUE THREAD

**Issue by LeGfrey** [joomla/joomla-cms#9088]
**Description**
When we have several reCaptcha (version 2.0) on same page. Only one is displayed.
It can be a problem if a module want to use the reCaptcha plugin to display his own captcha and we already have one on the page (for example on the user subscription page).

**Why do we have this issue ?**

This issue is here since : https://github.com/joomla/joomla-cms/commit/8da3451bce409a902d804ca685b73ea663d8a073

It seems the reCatpcha plugin only render the first reCaptcha div it encounter; as we use the onload mode since this commit.
> Defaults to onload, which will render the widget in the first g-recaptcha tag it finds.
(https://developers.google.com/recaptcha/docs/display)

Before the commit we used the explicit method, using some JavaScript to transforming a specific dom node into reCaptcha. So after several call to the plugin we had several reCaptcha.

Don't hesitate to notify me if I wasn't clear enough.

**Comment by brianteeman** [comment]
Please see #8867 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9088">issues.joomla.org/joomla-cms/9088</a>.</sub>

**Comment by brianteeman** [comment]
closed as duplicate report<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9088">issues.joomla.org/joomla-cms/9088</a>.</sub>
