### ISSUE TITLE
After switch from Arabic languages to English still showing RTL mode

### ISSUE THREAD

**Issue by L0rens0** [joomla/joomla-cms#9096]
#### Steps to reproduce the issue

After configuration Joomla association with Arabic and English language and turn on language switcher you need click on Arabic flag and website display correct, but when click on English flag after Arabic, RTL still present. Clicking again on the same language ( English) website will load in the right way. 

#### Expected result
After click on English flag after Arabic flag website must work correct, not display RTL mode still 

#### Actual result
After click on English flag after Arabic site itself is loaded with the right language.

#### System information (as much as possible)
System Information
Setting 	Value
 
PHP Built On 	Linux gator4189.hostgator.com 3.12.35.1418868451 #1 SMP Wed Dec 17 20:10:32 CST 2014 x86_64
Database Version 	5.5.42-37.1
Database Collation 	utf8_unicode_ci
PHP Version 	5.4.45
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (X11; Linux i686; rv:44.0) Gecko/20100101 Firefox/44.0 

#### Additional comments
Any help will be useful

**Comment by richard67** [comment]
@L0rens0 Should be solved with PR #9095. Can you test this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9096">issues.joomla.org/joomla-cms/9096</a>.</sub>

**Comment by richard67** [comment]
@L0rens0 Sorry, forget my previous comment. The PR I mentioned is not related to your issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9096">issues.joomla.org/joomla-cms/9096</a>.</sub>

**Comment by infograf768** [comment]
Which template are you using?

**Comment by L0rens0** [comment]
Hi,

Classic - Real Estate Joomla template
http://ordasoft.com/classic-real-estate-joomla-template.html

it is not default Joomla template, but do you suppose problem in template? not in Joomla? 



thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9096">issues.joomla.org/joomla-cms/9096</a>.</sub>

**Comment by brianteeman** [comment]
Please temporarily switch to a default template to confirm. It probably is
your template and this will confirm if that is correct or not.

**Comment by L0rens0** [comment]
Hello,

This issue happens with default template too.

You can see from screenhots Arabic language not work correct:

1 click - you can see how it woks: Language is Arabic, but content not display correct (no RTL)

https://issues.joomla.org/uploads/1/e5c2e674b1645f4c6969354f2df50733.png

2 click on flag - all works, check out below image

https://issues.joomla.org/uploads/1/46a860032e2ec23d8f4e72932e8b4a94.png

P.S. - if take old version of language switcher all works for previous issue, but it has other issue.

thanks

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9096">issues.joomla.org/joomla-cms/9096</a>.</sub>

**Comment by infograf768** [comment]
I tested this behaviour indeed when going to
http://q8creativerealestate.com/

Looks like it is an issue with some extensions installed on the site.

**Comment by brianteeman** [comment]
@L0rens0 have you resolved this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9096">issues.joomla.org/joomla-cms/9096</a>.</sub>

**Comment by brianteeman** [comment]
After almost a month without further response I am closing this at this time. It can always be re-opened if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9096">issues.joomla.org/joomla-cms/9096</a>.</sub>

**Comment by mhehm** [comment]
I have this issue on my site.

**Comment by infograf768** [comment]
@mhehm 

This issue is pretty old.
Which version of joomla are you using?
If 3.6.0, see
http://forum.joomla.org/viewtopic.php?f=711&t=929667#p3416850

**Comment by gptforjoomla** [comment]
I have this issue in joomla 3.9.1. I searched web and found that if i replace languagefilter.php of joomla 3.9.1 with languagefilter.php of joomla 3.3.6, this issue will fixed. but just associated items not work.
can you check why?
my joomla: 3.9.1
my php: 7.2

**Comment by infograf768** [comment]
As posted on the forum, this is generally due to a 3rd party extension. Template or component or plugin. Are you using SP Page Builder?

**Comment by gptforjoomla** [comment]
No. i do not using sp page builder. but i am using Helix3 template

**Comment by infograf768** [comment]
Can you test by switching to Protostar?

**Comment by gptforjoomla** [comment]
yes. I changed my site template to Protostar and tested now. the problem not solved.

**Comment by gptforjoomla** [comment]
My site is https://sibdiet.com. you can see it. I enabled debuging to see. please see today. (I want to return my template tomorrow.) (this is a live demo to test this problem. I and many other users have this problem.)

**Comment by infograf768** [comment]
@minijoomla 
You are loading some k2 stuff in your site
This is not a Joomla bug but something wrong in your settings/extensions.
No use to set debug on. It can't help for that.

Please ask for help in the forums a someone has to access your site as super user to try to find the culprit.

**Comment by gptforjoomla** [comment]
thank you for checking. i disabled installed system plugins one by one and tested. when i disabled "System - Helix Framework" plugin, the problem fixed.

**Comment by infograf768** [comment]
Ok. Therefore, as you use that template, I suggest you contact the company which provides this framework.
