### ISSUE TITLE
Language router gets confused with multiple menus pointing to same category

### ISSUE THREAD

**Issue by Giuse69** [joomla/joomla-cms#9100]
#### Steps to reproduce the issue
Setup site as multilingual (2 languages).
Create for each of the two languages:
1) a category CAT
2) a home menu item MENU_BLOG as Category Blog of CAT
3) a menu item MENU_LIST as Category List of CAT
Associate the menu items between the two languages (lang1 home to lang2 home, MENU_BLOG-lang1 with MENU_BLOG-lang2, MENU_LIST-lang1 to MENU_LIST-lang2).
Go to frontend, home page where the page is MENU_BLOG of CAT in lang1.

#### Expected result
The flag link for lang2 should point to HOME of lang2 that is MENU_BLOG-lang2.

#### Actual result
The flag link for lang2 points to another menu item: the MENU_LIST-lang2, probably fooled by having the same category pointed by two menus. Infact just unpublishing MENU_LIST in both languages makes the association between home menus work correctly.

#### System information (as much as possible)
windows 7

**Comment by infograf768** [comment]
As far as I remember, this is a known issue when we have 2 menu items displaying the same category, one as List, the other as Blog.

**Comment by Giuse69** [comment]
Ok,  since the exact Association is explicitly stored in the DB, it should be possible to use that instead of trying to recalculate with the router the other language menu item… am I right?

**Comment by Giuse69** [comment]
@infograf768: actually that is not the problem: also if the two menu items are of the same type (like both catefory blog), changing language when the user is on the home page is wrong: the navigation is not directed to the home page in the other language but to the other menu item pointing to the same category. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9100">issues.joomla.org/joomla-cms/9100</a>.</sub>

**Comment by brianteeman** [comment]
This is a known issue which cannot be resolved in this version of Joomla.  If code is provided (a pull request) it can always be re-examined.  I am closing this here at this time.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9100">issues.joomla.org/joomla-cms/9100</a>.</sub>

**Comment by Giuse69** [comment]
Just a question: I was not raising an issue on Joomla code/routing as a whole but only to the language switcher module that presents wrong hyperlinks on the language flags when the same category is pointed by multiple menu items: since the association between menu items in the different languages is stored in the DB, why the language switcher does not simply read from the #__associations table? Wouldn't it solve this issue?
Thanks

Giuse<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9100">issues.joomla.org/joomla-cms/9100</a>.</sub>

**Comment by Giuse69** [comment]
Hi, this issue with language switcher can be solved in Joomla 3.8 with improvements done in this 14 months?
thanks

Giuse<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9100">issues.joomla.org/tracker/joomla-cms/9100</a>.</sub>
