### ISSUE TITLE
head.php in libraries gives "ArrayHelper::toString() must be of the type array" line 119

### ISSUE THREAD

**Issue by joomlaproffs** [joomla/joomla-cms#9108]
We have problem in VirtueMart that category and product detail page not working. 

After removed some lines from below file, both page works well.

File Name     : libraries/joomla/document/renderer/html/head.php
Error details : Argument 1 passed to Joomla\Utilities\ArrayHelper::toString() must be of the type array, string given, called in /var/www/clients/client1/web35/web/libraries/joomla/document/renderer/html/head.php on line 119

Line no 115 to 120
```

	// Generate link declarations
	foreach ($document->_links as $link => $linkAtrr)
		{
			$buffer .= $tab . '<link href="' . $link . '" ' . $linkAtrr['relType'] . '="' . $linkAtrr['relation'] . '"';

			if ($temp = ArrayHelper::toString($linkAtrr['attribs']))
			{
				$buffer .= ' ' . $temp;
			}

			$buffer .= ' />' . $lnEnd;
		}
```

**Comment by joomlaproffs** [comment]
To add to this is that we are reunning a server Nginx, PHP 7.0.3 and MariaDB.

**Comment by andrepereiradasilva** [comment]
i think is the same issue described here 
https://github.com/joomla/joomla-cms/pull/8968

If so, it's already resolved in latest staging.
https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/document/renderer/html/head.php

**Comment by joomlaproffs** [comment]
Yup that fixed it, thanks
