### ISSUE TITLE
[modals.js] Usage of handler: 'string'

### ISSUE THREAD

**Issue by DonMartin** [joomla/joomla-cms#9112]
Im trying to use this type of handler (modals.js) to display a modal and set the content, i have spent many days without success this works actually? exists a example of use of this feature? thanks in advance

**Comment by brianteeman** [comment]
This isnt the best place to ask the question. This is for reporting bugs and adding features.

Please use the forum (http://forum.joomla.org) or probably the best place is https://groups.google.com/forum/#!forum/joomla-dev-general<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9112">issues.joomla.org/joomla-cms/9112</a>.</sub>

**Comment by DonMartin** [comment]
already tried but i'm not lucky there and here!!! thanks anyway!
