### ISSUE TITLE
Connection Reset on media manager form field

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#9113]
When inside the template and I hit "logo" instead of getting the normal media manager modal, I get the modal with "connection reset" internally.  this happens fairly quickly.
This is on a local host.  Using todays "staging".  Normal media manager works fine.
![connection reset](https://cloud.githubusercontent.com/assets/1850089/13018071/4542ac6c-d18d-11e5-8a6c-22c9f1c32d69.JPG)

**Comment by N6REJ** [comment]
update:  Saving template and then trying again made it work.

**Comment by infograf768** [comment]
I can't reproduce this with protostar

**Comment by richard67** [comment]
Me neither, can't reproduce with protostar.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9113">issues.joomla.org/joomla-cms/9113</a>.</sub>

**Comment by brianteeman** [comment]
Sounds like a local issue. I am closing this at this time
