### ISSUE TITLE
Classes added to Module Class Suffix in custom html module break in certain positions

### ISSUE THREAD

**Issue by N8Solutions** [joomla/joomla-cms#9115]
There is a bug where if you add a **class** to a **custom html module** using the **Module Class Suffix** box under the **Advanced** tab it replicates the classes entered showing it on the front end twice. Twice meaning that it adds the classes once around the container which includes the Title and a second time around the text inside the custom html module.

To duplicate this, simply add any **class** you want in the **Module Class Suffix** box for a **published custom html module**. Preferably a class that you can see such as a border or drop shadow. Make sure the custom html module is published in either one of the **Side** positions or the **Footer** positions such as these from the **Beez3** template.
Footer Top: position-9
Footer Middle: position-10
Footer Bottom: position-11
Left Middle: position-4
Left Bottom: position-5
Left Top: position-7
Right Middle: position-8
Right Bottom: position-6
Right Top: position-3

It appears to work fine if published elsewhere.

## This is also not template specific as I have reproduced this using Protostar, Beez3, and several other 3rd party templates.

Original Joomla forum post for this issue can be found here:
http://forum.joomla.org/viewtopic.php?f=728&t=906976

![screen shot 2016-02-13 at 07 00 48](https://issues.joomla.org/uploads/1/ba1189d163cbbc3e7920a3b2b1a05d16.png)
![screen shot 2016-02-13 at 07 00 48](https://issues.joomla.org/uploads/1/e5a297b41bb399f7ad830eb77de284e2.png)

**Comment by Webdongle** [comment]
Can confirm this is happening with Staging and 3.5.0 beta 2.

![custom 01](https://cloud.githubusercontent.com/assets/1115202/13028019/963b856c-d25a-11e5-8386-5727f025b167.JPG)

**Comment by Bakual** [comment]
It's the case for most modules. The reason is that this parameter is used both in the module chrome from the template and the module output itself.

I doubt we can change it without breaking something. Just write your CSS rules so it matches only one instance (eg combine your CSS rule with the other class present)

**Comment by Webdongle** [comment]
Yep, got it ... thanks

![custom 02](https://cloud.githubusercontent.com/assets/1115202/13029223/c2e74c9a-d27d-11e5-9838-c6cf6c2de321.JPG)
