### ISSUE TITLE
Package for Catalan language is always pending for update

### ISSUE THREAD

**Issue by jlainezs** [joomla/joomla-cms#9124]
#### Steps to reproduce the issue

1. Install catalan language pack (I did for frontend and backend).
2. Go to the control panel and let Joomla to check for updates. A pending update is shown. Click the link on the bottom left and an update for catalan language pack should appear.
3. Apply the update.
4. Go to the control panel and let Joomla to check for updates again. A pending update is reported. Click the link on the bottom left any you will see the same pending package you installed before.

#### Expected result

1. When the update is installed you expect to not apply it again.
2. After updating the language pack the package version should be 3.4.4.2

#### Actual result

1. The catalan language package is always pending of update.
2. After updating the language pack version shown on component management is 3.4.4.1

#### System information (as much as possible)

1. Ubuntu server on vagrant VM (found the same issue under Ubuntu server on a phisical machine)
2. Apache 2.4.16
3. PHP 5.6.14
4. MySQL 5.5
5. Joomla 3.4.8
6. Joomla Platform 13.1.0

#### Additional comments

There's an inconsistency between the update manifest and the downloaded package manifest. While the first says:

`<update>
   <name>Catalan</name>
   <description>Catalan Translation of Joomla!</description>
   <element>pkg_ca-ES</element>
   <type>package</type>`
   *`<version>3.4.4.2</version>`*
`   <downloads>
       <downloadurl type="full" format="zip">http://joomlacode.org/gf/download/frsrelease/20123/162726/ca-ES_joomla_lang_full_3.4.4v2.zip</downloadurl>
   </downloads>
   <targetplatform name="joomla" version="3.[012345]"/>
</update>`

the second says

`<version>3.4.4.1</version>`

I think that fixing the package manifest will solve the issue.

Maybe the updater should take in consideration this kind of incosistencies and doesn't allow to update an extension with different versions on the update manifest and in the install manifest.

**Comment by infograf768** [comment]
Please contact the Catalan Translation Coordinator:
http://community.joomla.org/translations/joomla-3-translations.html#ca-es

Not a core issue.

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9124">issues.joomla.org/joomla-cms/9124</a>

**Comment by infograf768** [comment]
Closed as not core.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9124">issues.joomla.org/joomla-cms/9124</a>.</sub>

**Comment by jlainezs** [comment]
Hi,

thanks for your fast reaction. I will contact them.
On the last line of the issue 'Additional comments' I say:

Maybe the updater should take in consideration this kind of 
incosistencies and doesn't allow to update an extension with different 
versions on the update manifest and in the install manifest.

Should I open an issue for this?

Regards,
Pep Lainez

------ Original Message ------

**Comment by infograf768** [comment]
@jlainezs 
The error has to be corrected in the package. 
Not sure we can disallow the update proposal as the package manifest saved in core will always be different from the .zip update.xml when there is a real update.
