### ISSUE TITLE
Joomla is hiding php errors

### ISSUE THREAD

**Issue by fazliddin** [joomla/joomla-cms#9125]
I am developing a custom auth plugin and accidentally assigned value from non existing var:
 `$a = $b['hello']`
 where $b is not initialized. error_reporting is set to development. In such cases normal scripts give an error, but joomla did not say anything. Instead I got `User not exists error`.

**Comment by Bakual** [comment]
Did you set the error reporting in Joomla configuration to development or in PHP?
Can you tell us a bit more in which place you expected the warning? Eg which plugin event / method your code was running in? Otherwise it's a bit hard to track down :smile:

**Comment by brianteeman** [comment]
It would be better if you asked this question at the Joomla! General Development forum https://groups.google.com/forum/#!forum/joomla-dev-general<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9125">issues.joomla.org/joomla-cms/9125</a>.</sub>
