### ISSUE TITLE
Search Tools -> Filters

### ISSUE THREAD

**Issue by syntaxerror** [joomla/joomla-cms#9127]
The wording "Search Tools" in t.ex. Articles list in admin (Content -> Articles) is a bit confusing, as it actually is a filter function, not being directly related to doing any search. Thus I would suggest changing it into t.ex. "Filters".

https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/en-GB.ini#L978-L981
https://github.com/joomla/joomla-cms/blob/staging/language/en-GB/en-GB.ini#L349-L352

**Comment by brianteeman** [comment]
Filters are search tools

**Comment by syntaxerror** [comment]
Kind of, but no - I don't agree.
We are filtering, not searching.

**Comment by brianteeman** [comment]
The filters are also used to enable you to limit the results of your search.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9127">issues.joomla.org/joomla-cms/9127</a>.</sub>

**Comment by syntaxerror** [comment]
Yes, but they can also be used without searching. Just to filter on a category.
Think outside the box for once.

**Comment by brianteeman** [comment]
It is your choice to disagree

On 15 February 2016 at 15:56, Rune Rasmussen <notifications@github.com>
wrote:

> Yes, but they can also be used without searching. Just to filter on a
> category.
> Think outside the box for once.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9127#issuecomment-184269629>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by syntaxerror** [comment]
Thanks for reminding us about why we shouldn't care to try to make a difference ...

**Comment by wilsonge** [comment]
Personally I think that Search Tools isn't the most intuitive name for end users as the *majority* of it is filtering. However @brianteeman is right that some of the things in search tools are more than just filtering (i'm especially thinking of the direction and the order by fields but there are other cases as well) so just calling it filtering isn't the right thing to do in my opinion. Maybe we can find another word to better describe it that more users would understand :)

**Comment by syntaxerror** [comment]
Thank you @wilsonge for writing something more than "I am always right and you are wrong. Agree or disagree, I don't care" type of stuff - it makes it easier to have a constructive dialogue that way. :)

And yes, you're right. "Order by" hasn't much to do with filtering (nor searching), but then the hover/help text is also wrong (Filter the list items) - if this actually is a option somewhere in the system. Though in the article list "Order by" is separated and always displayed, and not a part of the filters (those in read frame on the attached image).
![articles_list_joomla_admin](https://cloud.githubusercontent.com/assets/858132/13116870/4a2646ea-d5a6-11e5-8b34-335523d92dcd.png)

Anyhow, even "Search Filters" would be better than "Search Tools". But still it would be kind of confusing. Sometimes people just want to display all articles from a given category, and that's not seen on as searching, but filtering. Maybe we want to filter first, then search ...

**Comment by syntaxerror** [comment]
PS! Same thing, different placement and (correct) naming ...
![filter_or_search](https://cloud.githubusercontent.com/assets/858132/13196166/8bdf1636-d7cf-11e5-9eaf-3a6fede9e6e7.png)

**Comment by andrepereiradasilva** [comment]
That view still uses the old sidebar layout.
Needs to be updated.

**Comment by brianteeman** [comment]
"Filters and Search Tools" ? 

But probably thats too long especially in non english languages

FWIW the original term was chosen based on the google image search language
 ![screen shot 2016-03-01 at 02 58 58](https://issues.joomla.org/uploads/1/1504d088a0a342cf9edba970de69fabc.png)

(I have always assumed that google do considerable user and a/b testing before doing anything)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9127">issues.joomla.org/joomla-cms/9127</a>.</sub>

**Comment by syntaxerror** [comment]
"Filters and Search Tools" is a bit long yes, but surely more descriptive. Though, me personally still believes there is no real tools in there, just filters.So I still believes using just "Filters" or "Search Filters" would fit better, unless there is plans for extending it with tools of some kind.

Note! If Google is the definitive, it would be quite bad in many ways as they in Norwegian use something quite different for their translation. Using so radically different terms would t.ex. make English docs and refs quite useless.

In Norwegian they use "Innstillinger for søket", which directly and correctly translated is "Settings for the search", but they even have it wrong in their translation service when going from Norwegian to English. But from English to Norwegian 'Search Tools' will be translated "Søkeverktøy", which is the correct translation for this term, also used in Norwegian Joomla today ... :)

Anyhow, **and this is important**, Google Search is different than t.ex. the article list in Joomla. At Google you normally have to do a search first, then you can filter the result. In Joomla we see all articles listed, and can filter them on category etc. without searching.

**Comment by brianteeman** [comment]
Yes google is different - I was just explaining where the idea came from by
the person who created this code

**Comment by GABBAR1947** [comment]
Filtering takes an existing full list, and removes items based on  criteria that match/don't match.
Search takes a blank slate and adds to it based on criteria that match/don't match. So changing Search tools to filters does not seem to be a good idea.

**Comment by syntaxerror** [comment]
> Filtering takes an existing full list, and removes items based on criteria that match/don't match.

Yeah, and it's exactly what those options/tools can do, so I don't understand your conclusion.

**Comment by brianteeman** [comment]
Closed as we have a PR #9319<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9127">issues.joomla.org/joomla-cms/9127</a>.</sub>
