### ISSUE TITLE
PR #9131 causes SQL error when updating from 3.4.8

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#9132]
#### Steps to reproduce the issue

Create an update container from latest staging (which includes the commits from PR #9131).

You can find my container on http://test5.richard-fath.de/Joomla_3.5.0-beta2-Beta-Update_Package_staging.zip, this one includes also the (still open) PR #9045.

If you use http://test5.richard-fath.de/list_test3.xml as custom URL for the Joomla! Updater it will use my container.

Perform a Joomla! Updating using the Joomla! update component and the patched container.

#### Expected result

Update works.

#### Actual result

Update breaks before the 3 new plugins are installed (can be done with discover then).

Database shows errors.

When trying to fix with "Fix" button following SQL error is shown:

Specified key was too long; max key length is 767 bytes SQL=ALTER TABLE `#__session` MODIFY `session_id` varchar(400) NOT NULL DEFAULT '';

The fix fails, i.e. the database errors are still shown.

#### System information (as much as possible)

php: Linux info 3.0 #1337 SMP Tue Jan 01 00:00:00 CEST 2000 all GNU/Linux
dbversion: 5.1.73-log
dbcollation: utf8_general_ci
dbconnectioncollation: utf8_general_ci
phpversion: 5.6.15
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 3.5.0-beta2 Beta [ Ember ] 27-January-2017 23:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Windows NT 10.0; WOW64; rv:44.0) Gecko/20100101 Firefox/44.0

**Comment by richard67** [comment]
Hmm made a mistake with the category, should have been mysql instead of sql. Can I correct that myself somewhere?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9132">issues.joomla.org/joomla-cms/9132</a>.</sub>

**Comment by roland-d** [comment]
@richard67 I checked but there is no mysql category, only SQL in this case, so you are fine.

**Comment by wilsonge** [comment]
I just had this reported to me elsewhere. Fixed with https://github.com/joomla/joomla-cms/commit/fcb6d90b88209f4bf28ef3374f2bad55153fe0d3 then came across this - so closing this too!

**Comment by infograf768** [comment]
@wilsonge
See comments in https://github.com/joomla/joomla-cms/commit/fcb6d90b88209f4bf28ef3374f2bad55153fe0d3
