### ISSUE TITLE
3.5 beta, PHP 7, Cache_Lite, Deprecated message

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#9136]
Joomla 3.5 Staging (2016-02-15).
PHP Version 	7.0.2-nmm1
Web Server 	Apache
WebServer to PHP Interface 	fpm-fcgi

### How to reproduce:

Go to Global configuration.
Set Error reporting: Maximum.
Set Cache Handler: Cache_Lite
Save configuration.
You'll see:

> Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; Cache_Lite has a deprecated constructor in /usr/share/php/Cache/Lite.php on line 29

Also if cache is NOT enabled at all.

**Comment by mbabker** [comment]
This needs to be reported to the Cache_Lite maintainers.  Not a core CMS issue.

Tech details: The global config has a field to choose cache handlers.  The field relies on calling the handler's `isSupported()` method to tell the system whether a handler is supported in the environment.  [JCacheStorageCachelite::isSupported()](https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/cache/storage/cachelite.php#L345) will load the Cache_Lite class into memory and that will trigger the deprecation message.

Solution: Before PHP 8 (presumably when PHP will drop support for PHP 4 style constructors), the Cache_Lite maintainers need to refactor their class to use PHP 5 style constructors.

**Comment by brianteeman** [comment]
@mbabker nd the correct link for that is? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9136">issues.joomla.org/joomla-cms/9136</a>.</sub>

**Comment by mbabker** [comment]
https://pear.php.net/package/Cache_Lite/

But given they support PHP 4 still, they can't make the needed change until dropping support for that.

**Comment by brianteeman** [comment]
Thanks @mbabker - closing here as it is not a Joomla issue

**Comment by bertmert** [comment]
Thank you.
Looks like this is a known issue
https://pear.php.net/bugs/bug.php?id=21003
