### ISSUE TITLE
No association option in front-end article edit form (for multilingual sites)

### ISSUE THREAD

**Issue by geefthym** [joomla/joomla-cms#9141]
#### Steps to reproduce the issue
Login in front-end. Try to create/edit an article. Association option does not exist.

#### Expected result
If association option exists, front-end logged-in user can configure the articles in a full way in a multi-language site.

#### Actual result
Front-end logged-in user cannot configure the articles in a full way in a multi-language site.

#### System information (as much as possible)
System Information ---
PHP Built On 	Linux node1 3.2.0-4-amd64 #1 SMP Debian 3.2.73-2+deb7u2 x86_64
Database Version 	5.6.25-1~dotdeb+7.1
Database Collation 	utf8_general_ci
PHP Version 	5.5.30-1~dotdeb+7.1
Web Server 	Apache/2.2.22 (Debian)
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.4.0 Stable [ Ember ] 24-February-2015 23:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:44.0) Gecko/20100101 Firefox/44.0 

#### Additional comments![screen shot 2016-02-17 at 08 34 53](https://issues.joomla.org/uploads/1/2fba18e54a859b6a020585a73c29a5b2.png)
See screenshots. 1.png shows the first fields when trying to edit an article from front-end form.
2.png shows the last fields when trying to edit an article from front-end form. Association option could be present right after Language option.

![screen shot 2016-02-17 at 08 34 53](https://issues.joomla.org/uploads/1/3cdf63a35362dc37e5115095a1139ac2.png)

**Comment by brianteeman** [comment]
@infograf768 is there a technical reason for this or is it just that it was never coded<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9141">issues.joomla.org/joomla-cms/9141</a>.</sub>

**Comment by infograf768** [comment]
Nobody even tried to code this. It is extremely complex to do as there are a lot of aspects to consider, each one could easily mess up the site.  
As you may have remarked, we even prevent modifying the language and category when editing an already associated article in frontend.
Creating/modifying associations in frontend needs a full knowledge of existing associations in all categories + specific permissions.
As I see it, the only solution has to be global, i.e. a specific component that would deal with associations in backend and frontend. In frontend it could, for example, let create specific menu items dealing only with associations on existing articles, separated from the article editing itself. I am not aware of anybody working on this for the 3.x series.

Side Note:
@geefthym 
>Joomla! Version Joomla! 3.4.0 Stable [ Ember ] 24-February-2015 23:00 GMT

This version of Joomla is totally obsolete and vulnerable! Present version is 3.4.8 and 3.5.0 will soon be released.

**Comment by geefthym** [comment]
Thank you for answering @infograf768 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9141">issues.joomla.org/joomla-cms/9141</a>.</sub>

**Comment by brianteeman** [comment]
Closed at this time for the reason stated by @infograf768 above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9141">issues.joomla.org/joomla-cms/9141</a>.</sub>
