### ISSUE TITLE
missing echo in mod_breadcrumb/tmpl/default.php

### ISSUE THREAD

**Issue by nathan-4web** [joomla/joomla-cms#9143]
#### Steps to reproduce the issue

1) Create a menu with a Text separator parent, single article child.
2) Create a breadcrumb module anywhere on the page.
3) Navigate to the single article menu item (underneath the text separator)

#### Expected result

Home > Text Seperator (no link) > Single Article (active)

#### Actual result

Home >   > Single Article (active)

(the text separator is not displayed)

#### System information (as much as possible)

Joomla 3.4.8 (looks like as far back as 

#### Additional comments

Unless this is a feature, it looks like line 58 of modules/mod_breadcrumb/tmpl/default.php

<code><?php $item->name; ?></code>

should be

<code><?php **echo** $item->name; ?></code>

**Comment by brianteeman** [comment]
Thanks for reporting this. It has already been reported and fixed for 3.5
