### ISSUE TITLE
Iframe protocol for relative link is http when the site protocol is https, old issue ?

### ISSUE THREAD

**Issue by sscotti** [joomla/joomla-cms#9146]
I don't know if this is a problem, but I have some iframes on a Joomla! site that access content on the local server using relative URL's.  e.g.  /path/to/file.html, not using //pato/to/file.html.  The problem is that if I access the site using https://, the iframe protocol for some reason is set to http:// and the frame is not getting rendered in some browsers.  Why is that, and is there a fix.

**Comment by sscotti** [comment]
Seems to be possibly due to a <base href="http://domain.com/" /> statement at the beginning of the page ?

**Comment by Serirationale** [comment]
When you made the wrapper/iframe did you set it to “secure” under the metadata tab?

This may help?

**Comment by brianteeman** [comment]
I am assuming that means your site is accessible under both http and https??<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9146">issues.joomla.org/joomla-cms/9146</a>.</sub>

**Comment by sscotti** [comment]
Correct.  I actually found a solution with the setup that I have.  I have POWERADMIN installed and there is an option there to Convert all links to HTTPS when site is accessed over SSL  This seems to take care of the problem as the base href has the correct protocol and all of my other elements (e.g. an iframe in one case) also has the correct protocol.  For people that don't have SEO and Link Tools that comes with POWERADMIN it may be a problem, although I'm sure there are other ways around it.

**Comment by brianteeman** [comment]
The correct solution is to ONLY run the site on a single protocol

On 18 February 2016 at 08:05, Stephen D. Scotti <notifications@github.com>
wrote:

> Correct. I actually found a solution with the setup that I have. I have
> POWERADMIN installed and there is an option there to Convert all links to
> HTTPS when site is accessed over SSL This seems to take care of the problem
> as the base href has the correct protocol and all of my other elements
> (e.g. an iframe in one case) also has the correct protocol. For people that
> don't have SEO and Link Tools that comes with POWERADMIN it may be a
> problem, although I'm sure there are other ways around it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9146#issuecomment-185588545>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Closing as this is not a Joomla core issue but a site/hosting setup problem
