### ISSUE TITLE
Intro text is hidden on blogview

### ISSUE THREAD

**Issue by Burnardo** [joomla/joomla-cms#9149]
#### Steps to reproduce the issue
Upgraded Joomla 3.4.8 site to 3.5 beta 2 with Joomla_3.5.0-beta2-Beta-Update_Package.zip

All existing blogview menu-items that were supposed to show a list of articles and then title, intro-text with "read more" button, now only show title and "read more" button.

All the previously visible introtext parts are now hidden.

Is this due to a new feature that is introduced in 3.5, which requires article re-setting to these new features?
Regards,
Ben

#### Expected result
All articles in a category blogview show title, introtext and "read more" button.

#### Actual result
Only title, and "read more" button shows. Full article shows as expected, when clicked on "read more" or title.

#### System information (as much as possible)
3.5 beta2

**Comment by brianteeman** [comment]
are you using one of the default templates? If not can you please retest
with one of them

On 18 February 2016 at 13:39, Ben van Wetten <notifications@github.com>
wrote:

> Steps to reproduce the issue
>
> Upgraded Joomla 3.4.8 site to 3.5 beta 2 with
> Joomla_3.5.0-beta2-Beta-Update_Package.zip
>
> All existing blogview menu-items that were supposed to show a list of
> articles and then title, intro-text with "read more" button, now only show
> title and "read more" button.
>
> All the previously visible introtext parts are now hidden.
>
> Is this due to a new feature that is introduced in 3.5, which requires
> article re-setting to these new features?
> Regards,
> Ben
> Expected result
>
> All articles in a category blogview show title, introtext and "read more"
> button.
> Actual result
>
> Only title, and "read more" button shows. Full article shows as expected,
> when clicked on "read more" or title.
> System information (as much as possible)
>
> 3.5 beta2
> Additional comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9149>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Burnardo** [comment]
Hi Brian,

Just switched from my own template to Protostar.
In Protostar the blogview also does NOT show the introtext of the article.
(Next to this, both links (title and read-more button) give me a plank 
page with only: <class="item_title">  )

In "my own template" both links to full article work fine.

hope this helps,
Ben

**Comment by brianteeman** [comment]
I am not sure I understand your layout or how you achieved it

>  **list of articles** and then title, intro-text with "read more" button<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9149">issues.joomla.org/joomla-cms/9149</a>.</sub>

**Comment by Burnardo** [comment]
Would you like a PM with admin-details to see for yourself. That might 
be more clear than my explanation...
Ben
(is it possible for me to send a PM to you?)

**Comment by brianteeman** [comment]
No thanks - just post a screenshot

On 18 February 2016 at 15:03, Ben van Wetten <notifications@github.com>
wrote:

> Would you like a PM with admin-details to see for yourself. That might
> be more clear than my explanation...
> Ben
> (is it possible for me to send a PM to you?)
>
> > Ben van Wetten <mailto:ben@vanwetten.com>
> > donderdag 18 februari 2016 15:07
> > Hi Brian,
> >
> > Just switched from my own template to Protostar.
> > In Protostar the blogview also does NOT show the introtext of the
> > article.
> > (Next to this, both links (title and read-more button) give me a plank
> > page with only: <class="item_title"> )
> >
> > In "my own template" both links to full article work fine.
> >
> > hope this helps,
> > Ben
> >
> >
> > Brian Teeman <mailto:notifications@github.com>
> > donderdag 18 februari 2016 14:48
> > are you using one of the default templates? If not can you please retest
> > with one of them
> >
> > On 18 February 2016 at 13:39, Ben van Wetten <notifications@github.com>
> > wrote:
> >
> > > Steps to reproduce the issue
> > >
> > > Upgraded Joomla 3.4.8 site to 3.5 beta 2 with
> > > Joomla_3.5.0-beta2-Beta-Update_Package.zip
> > >
> > > All existing blogview menu-items that were supposed to show a list of
> > > articles and then title, intro-text with "read more" button, now
> > only show
> > > title and "read more" button.
> > >
> > > All the previously visible introtext parts are now hidden.
> > >
> > > Is this due to a new feature that is introduced in 3.5, which requires
> > > article re-setting to these new features?
> > > Regards,
> > > Ben
> > > Expected result
> > >
> > > All articles in a category blogview show title, introtext and "read
> > more"
> > > button.
> > > Actual result
> > >
> > > Only title, and "read more" button shows. Full article shows as
> > expected,
> > > when clicked on "read more" or title.
> > > System information (as much as possible)
> > >
> > > 3.5 beta2
> > > Additional comments
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/joomla/joomla-cms/issues/9149>.
> > >
> >
> >
> >
> > --
> > Brian Teeman
> > Co-founder Joomla! and OpenSourceMatters Inc.
> > http://brian.teeman.net/
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/joomla/joomla-cms/issues/9149#issuecomment-185731648
> >.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9149#issuecomment-185758305>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wojsmol** [comment]
@Burnardo  Provide a list of active plugins, which are not included in the Joomla! core Probably related https://github.com/joomla/joomla-cms/pull/8024#issuecomment-161182209 - point 1.

CC @wilsonge

**Comment by Burnardo** [comment]
Allright,

In this image you see a category blog, in which 2 columns are used for 
display. Showing 3 articles, they reveal only titles and read-more 
buttons, but not introtext.

Beneath that, the same picture is taken from the site with Joomla 3.4.8



This is the present state of the Joomla 3.4.8 website :



Hopefully you can get my idea now...

Regards,
Ben

**Comment by wilsonge** [comment]
I fixed the issue in #8024 this morning (https://github.com/joomla/joomla-cms/commit/fb4d375e14d33d2579e301c3e9d87d6115f94b97). Let's just hold this until I get beta 3 out this evening and then that will confirm if that was the cause of the issue!

**Comment by Burnardo** [comment]
OK,
I will use the beta3 as an upgrade to check my findings, once it is 
available.

Thank you,
Ben

**Comment by Burnardo** [comment]
After using the beta3 update package, my previously mentioned problem was solved.

Thank you for your excellent work,
Burnardo<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9149">issues.joomla.org/joomla-cms/9149</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for confirming - closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9149">issues.joomla.org/joomla-cms/9149</a>.</sub>
