### ISSUE TITLE
No attrib for $doc->addScript()

### ISSUE THREAD

**Issue by spignataro** [joomla/joomla-cms#9153]
public function addScript($url, $type = "text/javascript", $defer = false, $async = false)

The above is the function call for JDocument. We encounter problems all the time with Cloudflare not liking some Javascript and we use the following to push our javascript:

$doc = JFactory::getDocument();
$doc->addScript( 'path/to/javascript.js' );

It would be nice to have the ability to add attributes so that we can do something like the following:

$doc->addScript( 'path/to/javascript.js', array( 'data-cfasync="false"');

So that could print out the following:

<script data-cfasync="false" src="path/to/javascript.js"></script>  

This would allow Cloudflare to bypass using it's rocket loader on the javascript file that we know it is having a rough time with. 

This would also help with many other things besides cloudflare - but this is just an example.

**Comment by brianteeman** [comment]
Pull requests are welcome

On 18 February 2016 at 20:45, spignataro <notifications@github.com> wrote:

> public function addScript($url, $type = "text/javascript", $defer = false,
> $async = false)
>
> The above is the function call for JDocument. We encounter problems all
> the time with Cloudflare not liking some Javascript and we use the
> following to push our javascript:
>
> $doc = JFactory::getDocument();
> $doc->addScript( 'path/to/javascript.js' );
>
> It would be nice to have the ability to add attributes so that we can do
> something like the following:
>
> $doc->addScript( 'path/to/javascript.js', array( 'data-cfasync="false"');
>
> So that could print out the following:
>
> This would allow Cloudflare to bypass using it's rocket loader on the
> javascript file that we know it is having a rough time with.
>
> This would also help with many other things besides cloudflare - but this
> is just an example.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9153>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by dgt41** [comment]
It's already PR'd and waiting for merging https://github.com/joomla/joomla-cms/pull/8540

**Comment by dgt41** [comment]
@spignataro By the way you should always use `JHtml::_('script', '/whatever.js');` and not `addScriptDeclaration()`

**Comment by spignataro** [comment]
@dgt41 

I would recommend moving attribs to the beginning as putting in false, false, false, true, attrib() since that would just be programming long hand.

Also I am not using addScriptDeclaration() - we are using addScript()

**Comment by dgt41** [comment]
@spignataro rearranging the flags CANNOT happen in 3.x for B/C reasons
Also `addScript()` is NOT overridable so you are making things hard for others, not a good thing!

**Comment by spignataro** [comment]
Good point.

**Comment by brianteeman** [comment]
In light of above comments abut changes and the availability of #8540 which is in need of tests are you ok with me closing this one. 

Remember without tests #8540 will not be considered for merging

**Comment by brianteeman** [comment]
Closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9153">issues.joomla.org/joomla-cms/9153</a>.</sub>
