### ISSUE TITLE
Outdated Dependencies

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#9157]
The following Composer dependencies are outdated and require updates:

- [x] `joomla/filter` 1.1.6 installed, 1.2.0 latest
- [x] `joomla/session` 1.3.0 installed, 1.3.1 latest
- [x] `joomla/utilities` 1.3.3 installed, 1.4.0 latest
- [ ] `paragonie/random_compat` 1.0.10 installed, 1.2.1 latest
- [x] `phpunit/phpunit` 4.8.11 installed, 4.8.23 latest
- [x] `symfony/polyfill-php56` 1.0.0 installed, 1.1.0 latest
- [x] `symfony/yaml` 2.7.5 installed, 2.8.3 latest

**Comment by photodude** [comment]
Should the CMS specific versions of these packages also be updated? For example `joomla/filter` is not used by the CMS but a modified version is used located at `libraries/joomla/filter`.

**Comment by mbabker** [comment]
"Modified version" === "legacy code" and yes eventually all should be updated eventually to point to the newer stuff as able.

**Comment by photodude** [comment]
Would that also mean the some of the CMS specific changes need to be backported to the Framework?
For example the CMS filter version includes some additional code to "Strip Unicode Supplementary Characters when requested to do so" that the framework filter package is currently missing.

**Comment by mbabker** [comment]
Eventually, yes, but in that context they must be non-CMS dependent (so specifically the JFilterInput constructor portion that tries to use the database connection to decide to strip USC shouldn't be in the FW, basically it wouldn't support the -1 value for that param that the CMS does, which is perfectly acceptable; there is nothing that mandates the CMS has to use the FW classes verbatim and cannot extend them with app specific additions or changes).

**Comment by photodude** [comment]
Considering Outdated Dependencies; Should SimplePie be updated from 1.2 to 1.3.1?

**Comment by mbabker** [comment]
Should it?  Yes.  Will it actually be tested and merged?  Well, I leave the current outstanding PR as evidence...

**Comment by photodude** [comment]
Like so many other things, #8735 and #8734 didn't get enough attention when they were opened and now they have merge conflicts slowing/blocking testing.

More or less my question was directed towards what Dependencies should or shouldn't be included in the list to be updated.

**Comment by mbabker** [comment]
All of them.  Short of a B/C break that is impossible to work around, all dependencies should always be at the latest versions.

**Comment by photodude** [comment]
PHPUnit updated with merged PR #9203 
Filter package update is now included in PR #8681 (Needs review and Testing)

**Comment by wilsonge** [comment]
I just manually updated the session package as we aren't using it in core

**Comment by wilsonge** [comment]
Symfony dependencies updated with https://github.com/joomla/joomla-cms/commit/23ce025edff11382344d29e4ad04a6e7961f0da3 - YAML isn't used in core and manually reviewed the changes to the PHP 5.6 polyfill and they weren't patching functions we were using (and it's new to 3.5 anyhow)

**Comment by wilsonge** [comment]
Utilities done with https://github.com/joomla/joomla-cms/commit/8cb784f387662151384b69c6aad0504330b53524

**Comment by wilsonge** [comment]
Final dependency updated in #9320
