### ISSUE TITLE
Calendar Decreasing after save

### ISSUE THREAD

**Issue by TuSKan** [joomla/joomla-cms#9158]
Hi,

My form field *calendar* on administration site is decreasing **every** time I save the template. This is very annoying, because I have many calendar fields to input data on my template.

Please, someone help me to fix this.

**Comment by Bakual** [comment]
Please use the Google Group for support requests.https://groups.google.com/forum/#!forum/joomla-dev-general
It's related to the timezone and that you are only saving the date without any time.

**Comment by TuSKan** [comment]
I put the question there and no answer. Forme this is a bug, because this does not happen in my local machine, only on the server.

**Comment by Bakual** [comment]
Locking here.
