### ISSUE TITLE
why not support latest boostrap 3.3.6

### ISSUE THREAD

**Issue by alexonbalangue** [joomla/joomla-cms#9168]
#### Steps to reproduce the issue
Why not updated bootrap to version 3.3.6+? 

#### Expected result
Boostrap version still use.

**Comment by brianteeman** [comment]
Unfortunately it is not backwards compatible with precious versions if bootstrap so we can't. You can of course override it yourself in your own template.

**Comment by alexonbalangue** [comment]
ok thank your answering<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9168">issues.joomla.org/joomla-cms/9168</a>.</sub>
