### ISSUE TITLE
Bug in libraries\cms\html\html.php

### ISSUE THREAD

**Issue by softwareschreiber** [joomla/joomla-cms#9169]
#### Steps to reproduce the issue
If I use a form field type 'calendar' the field cannot show dates before 01.01.1970 or after 2038

#### Expected result
string representation of all dates

#### Actual result
empty inputvalue

#### System information (as much as possible)
The reason is the use of strftime() in html.prg function calendar():

$inputvalue = strftime($format, strtotime($value));

better could be:
$dat = DateTime::createFromFormat("Y-m-d H:i:s", $value);
$inputvalue = $dat->format(str_replace('%','',$format));

#### Additional comments
In source code of Joomla 3.5 this issue exist too.

Best Regards
Hartmut Schreiber

**Comment by photodude** [comment]
Looks like there is a Known issue with using PHP's `strftime()` as Not all conversion specifiers may be supported by the system's C library. More specifically, dates prior to Jan 1, 1970 - will not work on Windows, some Linux distributions, and a few other operating systems. Additionally, on some systems the date range may be limited to no earlier than the Unix epoch.

[Reference on this issue PHP manual for `strftime()`](http://php.net/manual/en/function.strftime.php)

Looks like there are a large number os systems specific caveats for using this function.

**Comment by softwareschreiber** [comment]
I think too. And it should be no Problem to fix this bug

**Comment by brianteeman** [comment]
Pull requests are welcome

**Comment by brianteeman** [comment]
Closing as we have a PR please test #9271

**Comment by photodude** [comment]
@brianteeman Should this be reopened since PR 9271 was rejected as a fix?

**Comment by flash1452** [comment]
@brianteeman Sorry,but i am unable to understand what actually this issue is all about.Is it about calendar not showing dates before 01.01.1970 or after 2038 (which is certainly the issue with the operating system one is using) OR is there something else that i am missing???

**Comment by photodude** [comment]
@flash1452 The code used for the calendar to "Format a local time/date according to locale settings" has system specific limitations. Preventing the calendar from using dates before 01.01.1970 or after 2038 on some systems (limitation is more specifically addressed in my first response).

An alternative to `strftime()` should be implemented to allow for correct function on all supported web servers. (unfortunately, there are some BC gotcha issues to deal with too while fixing this issue)

**Comment by flash1452** [comment]
@photodude Thanks,for your reply.So what other issues are to be handled alongside this one?

**Comment by brianteeman** [comment]
@dgt41 does your new calendar field address this? If so this can be closed

**Comment by dgt41** [comment]
@brianteeman there are tags in the xml for the field where a dev can set the min and max year that the field should accept. if nothing is provided then 1970 is the minimum and 2030 is the maximum by default (that was a blind copy over the params that existed in the old calendar). So I guess it will be handled better than the current code

**Comment by brianteeman** [comment]
OK - so I am closing this here as the new (to be merged) calendar will address this as stated above.
