### ISSUE TITLE
Do not open the site and the site editor.

### ISSUE THREAD

**Issue by DanilJe** [joomla/joomla-cms#9171]
#### Steps to reproduce the issue

When you open the site shows an error.

#### Actual result

####![screen shot 2016-02-19 at 17 52 14](https://issues.joomla.org/uploads/1/7f61ac8b2393a2944879f4a506b86a7e.) System information (as much as possible)

**Comment by brianteeman** [comment]
Please use the forum for support on your site http://forum.joomla.org
