### ISSUE TITLE
Ajax request and session time out

### ISSUE THREAD

**Issue by alex-filat** [joomla/joomla-cms#9172]
Hi,

I think should be some standard logic when we send ajax request while session is expired. System should redirect to login screen insteed to alert Ajax error message in js. It is easily to see in language component /administrator/index.php?option=com_languages&view=override&layout=edit when searching words. Go to this component , manually expire session (f.e. drop it in db) then serach for some word.

If look deep inside at the moment when session expired and we press search button (this function send json type ajax request), system response " 404 view not found [name, type, prefix]: login, json, loginView", it means that system does not handle situation at all.

I have more detailed information about this problem and actually can codding some solution but may be people who participated in developent of this part of architecture want to fix that.

Alex

**Comment by brianteeman** [comment]
Hi Alex
If you have some code then better to contribute that then wait for anyone else<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9172">issues.joomla.org/joomla-cms/9172</a>.</sub>

**Comment by brianteeman** [comment]
@alex-filat are you going to be providing the extra information and code or shall I just close this due to lack of interest

> I have more detailed information about this problem and actually can codding some solution but may be people who participated in developent of this part of architecture want to fix that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9172">issues.joomla.org/joomla-cms/9172</a>.</sub>

**Comment by alex-filat** [comment]
Hi Brian , please leave it for a while i remember about. It is not small thing, i'll try to find time at near future.

**Comment by brianteeman** [comment]
@alex-filat gentle bump<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9172">issues.joomla.org/joomla-cms/9172</a>.</sub>

**Comment by brianteeman** [comment]
@alex-filat second and final gentle bump or I will close this and you can create a new PR when you are ready to submit some code<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9172">issues.joomla.org/joomla-cms/9172</a>.</sub>

**Comment by andrepereiradasilva** [comment]
override edit view have keepalive session behaviour

See https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_languages/views/override/tmpl/edit.php#L15

**Comment by alex-filat** [comment]
Hi Brian, please close , i am everloaded  for now and cannot participare in
contribution.

**Comment by brianteeman** [comment]
Closed as requested. I hope at some time in the future @alex-filat will be able to contribute this.
