### ISSUE TITLE
ISIS back-end template recalls a famous terrorist organization

### ISSUE THREAD

**Issue by demis-palma** [joomla/joomla-cms#9176]
ISIS is an unlucky name for a Joomla back-end template.
A [Google image search](https://www.google.fr/search?q=isis&biw=1920&bih=954&source=lnms&tbm=isch&sa=X&ved=0ahUKEwigysj-uobLAhWJWRoKHVf4D-sQ_AUIBigB) returns executions, decapitations, and all kind of barbarisms, except the actual Joomla back-end screenshots.
(For those who don't know it, ISIS refers to the [Islamic State of Iraq and the Levant](https://en.wikipedia.org/wiki/ISIS))

Keeping in mind the due cultural differences, the word ISIS sounds to European people exactly like the word al-Qaida sounds to American people.

Would you ever create a Joomla template named al-Qaida? If the answer is no, you should seriously  consider to rename the ISIS template.

**Comment by brianteeman** [comment]
I am closing this here as it has been discussed many times on the CMS mailing list<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9176">issues.joomla.org/joomla-cms/9176</a>.</sub>

**Comment by demis-palma** [comment]
Does someone have a link to the mailing list discussion?
