### ISSUE TITLE
Modules Custom and loadposition. Double headline.

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#9179]
Test:
Joomla 3.4.8, 3.5.0beta, Protostar

- Create a module of type Custom.
Enter some text.
Enter a position like "somewhere".
Select module style "html5".
Set "Show Title": SHOW
Save and close.

-  Create 2nd module of type Custom.
Enter in editor
```
{loadposition somewhere}
```
Select an existing template position, e.g. "banner".
Set "Prepare Content": YES
Set "Show Title": HIDE
Select module style "none".
Save and close.

- Select 2nd module (check).
Click button Duplicate to create a copy.
Publish 3rd module.

See frontend:
2 headlines in one module. 
The whole HTML from module style is duplicated.

![screenshot_2modules](https://cloud.githubusercontent.com/assets/11038612/13197657/b29431b0-d7f4-11e5-91ae-9f2ccdaf3b45.jpg)

Cache is explicitely disabled in module 1.
No Joomla cache or cache plugin active.
same behavior when 3rd module has another position than 2nd

**Comment by xtech86** [comment]
Tested and confirmed this unique scenario causes title duplication. 

It seems like they are not being fully escaped somewhere. A quick source view shows the potential problem. 
<img width="648" alt="screenshot 2016-03-08 12 56 12" src="https://cloud.githubusercontent.com/assets/1400982/13602225/410576ee-e52d-11e5-9130-9885ac3de298.png">

**Comment by brianteeman** [comment]
Hi you created this issue sometime ago but have not provided any code for people to evaluate. As no one else has shown any interest in providing the code and it is a ery specialised and non standard thing to load a module inside a module I am closing this issue at this time. If code is provided (a pull request) it can always be re-examined.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9179">issues.joomla.org/joomla-cms/9179</a>.</sub>
