### ISSUE TITLE
Language name disambiguation

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9187]
where does the list of languages that can be installed come from?
I am asking because I notice that ALL the english language packs are just named English in the list of available languages that can be installed in the admin. (its not a problem in the installation as the names are in full there)
For example you only know one of the English languages is English (australian) if you look at the path in the Details URL column. fr-ca is listed as FrenchCA in the name field which is good but this isnt done  for english.

I am assuming it is something in the language XML file but no idea where to look to propose a change

**Comment by richard67** [comment]
I remember there was a discussion in one of @andrepereiradasilva 's PRs I helped with testing.

See [this comment](https://github.com/joomla/joomla-cms/pull/9101#issuecomment-182967345 "https://github.com/joomla/joomla-cms/pull/9101#issuecomment-182967345") by @infograf768 and the [comment just before that one](https://github.com/joomla/joomla-cms/pull/9101#issuecomment-182822470 "https://github.com/joomla/joomla-cms/pull/9101#issuecomment-182822470").

It seems these texts come from the XMLs and may be decided by the Translation Teams.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9187">issues.joomla.org/joomla-cms/9187</a>.</sub>

**Comment by brianteeman** [comment]
If you look at the installation language files they do not have this
problem as they are correctly named in the XML file there. So this is not
the same issue as mentioned in your link it is simply a bug in the XML
files which I don't have access to in order to fix.

**Comment by richard67** [comment]
Ah, I see. Sorry for confusion.

**Comment by brianteeman** [comment]
What the language is called is up to the TT but it must be unique and they
must use the same name in the installation language and the main language
pack

**Comment by mbabker** [comment]
It's all done by script.  https://github.com/joomla-projects/language-update-xml-generator/blob/master/translation_cron.php#L208 is the line in the cron file where the name gets processed for writing into the XML files.  The package list is coming from http://joomlacode.org/gf/project/jtranslation3_x/frs/.  The way it looks, someone just needs to rename the packages on JoomlaCode and the next time the cron runs after that it would all be fine.

**Comment by brianteeman** [comment]
I assumed something like that I just don't have the access to do it

**Comment by mbabker** [comment]
Ironically the user account that the cron job runs under doesn't have manage privileges on that project's files.  @infograf768 or @Bakual I'd assume would have that.

**Comment by brianteeman** [comment]
Using fr-ca as an example it's simply a case of renaming the package as the
script is ignoring the actual language name in the XML

**Comment by mbabker** [comment]
The cron generating the update XMLs doesn't use the data inside the actual package, rather the package name in JoomlaCode and the file name to extract out all the required info.

**Comment by brianteeman** [comment]
Yeah that's what I meant. Weird that it's not consistent with the
installation languages

**Comment by infograf768** [comment]
in fact, i just have to change the project name on jomlacode with the jomlacode naming restrictions. will make test to see if it is b/c with en-au. at least to differentiate the english packs.

**Comment by brianteeman** [comment]
Thanks. I think the same as with fr-ca is better than nothing

**Comment by infograf768** [comment]
No B/C issue, i.e. update went fine from older pack.
English AU already done.

Others done too, will be available in an hour or so.
Will be
English US
English CA
English AU

Also modified FrenchCA to French CA

**Comment by infograf768** [comment]
IMHO you can close.

**Comment by infograf768** [comment]
BTW, FYI
These names comes from the Releases Names.
If I want to get French CA, I have to add an underscore before CA and then another underscore before the lang tag:
![screen shot 2016-02-21 at 20 04 29](https://cloud.githubusercontent.com/assets/869724/13204693/b245f742-d8d6-11e5-9744-c811b53fe3d6.png)

**Comment by brianteeman** [comment]
Thank you very much. Closing
