### ISSUE TITLE
Install Languages duplicated in potsgres

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9188]
#### Steps to reproduce the issue
Install Joomla staging on a postrgresl database
Go to extensions install languages
Observe number of languages displayed
Click on find languages

#### Expected result
The list of available languages should not change

#### Actual result
Every language is repeated in the list

#### System information (as much as possible)
Joomla Staging as of Saturday 21 Feb

#### Additional comments
This only happens with a pgsql database - it is fine in mysql

@alikon Any ideas?

**Comment by alikon** [comment]
can confirm, i'll look at 
seems another  regression (language images) i guess?

**Comment by infograf768** [comment]
Not sure @alikon as the lang images are not used in that view and the RTC PR modifying the view does not either https://github.com/joomla/joomla-cms/pull/9089

**Comment by andrepereiradasilva** [comment]
that i now of this view has not been changed yet. And doesn't include language images.
There a PR https://github.com/joomla/joomla-cms/pull/9089 for some changes but that has not been merged yet.

**Comment by alikon** [comment]
yes is another issue see #9241

**Comment by brianteeman** [comment]
Closed now that we have a PR - please test #9241
