### ISSUE TITLE
Regression: Hathor list display number broken

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#9191]
#### Steps to reproduce the issue
On staging, using Isis, go to the Modules list display and change in the dropdown the number of items to display.
Works fine.

Then change template to Hathor, go to the modules list and change the Display# and click on submit.

![screen shot 2016-02-22 at 03 29 15](https://issues.joomla.org/uploads/1/c9986e2c8e9b18b3eed1d364cc4df154.png)
The number does not change.

**Comment by brianteeman** [comment]
Is this the same as #6578 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9191">issues.joomla.org/joomla-cms/9191</a>.</sub>

**Comment by infograf768** [comment]
Indeed, looks like it is.

**Comment by infograf768** [comment]
But it works fine here on a pure 3.4.8...

**Comment by infograf768** [comment]
Hmm, not so fine. After a few tries in various lists, it goes havock...
So same issue. Closing as duplicate.

**Comment by brianteeman** [comment]
Yeah - as you saw I have been pushing for a fix but nothing - the fact that
it is such an old bug with no other reports shows to me that its not a very
used feature or hathor is hardly used or both

On 22 February 2016 at 09:59, infograf768 <notifications@github.com> wrote:

> Hmm, not so fine. After a few tries in various lists, it goes havock...
> So same issue. Closing as duplicate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9191#issuecomment-187103747>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
