### ISSUE TITLE
Suggested improvements to template editor new file modal

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#9199]
#### Steps to reproduce the issue
start to create new file in template editor.  Modal box will pop up with a VERY long list of files.  to select the needed folder you must scroll down but then you lose the input box.
suggestion: assign column 2 to position "fixed"
My suggestion would be a simple fix if it were not for the fact that the modal box columns are allowed to flow outside the modal body.
if it were not for this flex would fix this this automatically and easily.

#### Expected result
column 2 appears along right edge of modal box.

#### Actual result
floats about 70% past the right edge of the modal body.

#### System information (as much as possible)
current staging.

#### Additional comments
I believe this is an area where flex really shines.  BS 4 will use flex alot for this type of behavior so fixing this now is being forward thinking...

**Comment by raua** [comment]
If we can create a inner-column div inside the column div, we can set the position fixed and will works like a charm.

**Comment by shubhamnba2009** [comment]
What is the file location in the current staging for this issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9199">issues.joomla.org/joomla-cms/9199</a>.</sub>

**Comment by brianteeman** [comment]
Closed please see #10100<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9199">issues.joomla.org/joomla-cms/9199</a>.</sub>
