### ISSUE TITLE
Specification of identifier field for smart search plugins.

### ISSUE THREAD

**Issue by miguelbgouveia** [joomla/joomla-cms#9205]
I was creating an smart search plugin for a specific component.
The problem is that component use a table where the identifier field don't have the 'id' name.
To resolve the problem it will be good if I could specified the field identifier name in cases that the name is other than 'id'.

I just create an pull request with the solution but it don't pass in the CI tool in some php versions.
The pull request is #9202

**Comment by brianteeman** [comment]
Please add this as a comment on #9202
