### ISSUE TITLE
Suggested improvement for Repeatable form field type.

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#9209]
#### Steps to reproduce the issue
create repeatable list.
view list & verify all "default" items are listed.
change xml to add or modify any default item.

#### Expected result
list will change

#### Actual result
list stays to previously selected 

#### Additional comments
I realize this is the current intended function, but as a developer it would be very convenient to "reset" the repeatable list table.  I can see where possibly a user MIGHT have that same need a time or two.
In my case during the design of the table I realized I could add another row and rename one of the elements, after doing so, those changes were not picked up, not even the addition of a new row.
```
"Elements":["body","H1","H2","H3","H4","H5","H6","p","a","i","ul","li","span.company-name","span.site-moniker"],
```
This is the new default.  Notice I changed the last two rows.
![image](https://cloud.githubusercontent.com/assets/1850089/13305773/818c5534-db23-11e5-9c2d-0ae801721580.png)
This is the result.

**Comment by dgt41** [comment]
I will suggest to let it die as the new one is going to replace it soon: https://github.com/joomla/joomla-cms/pull/7829

**Comment by N6REJ** [comment]
what new one?

**Comment by dgt41** [comment]
follow the link: #7829

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9209">issues.joomla.org/joomla-cms/9209</a>.</sub>

**Comment by N6REJ** [comment]
I think brian's got a auto-close macro with my name on it :P
