### ISSUE TITLE
Feature Request / Bug fix (?): Usage of symlinks

### ISSUE THREAD

**Issue by alve89** [joomla/joomla-cms#9210]
#### Steps to reproduce the issue
Create a symlink within a folder within Joomlas root - let's say /images - that points to a directory outside of Joomlas root.
Within a content - let's say an article - try to insert an image with the wizard.

#### Expected result
The directories of / within the symlink are shown and an image is selectable and insertable.

#### Actual result
The directories of / within the symlink are shown actually (the image file as well but without preview). The image is also selectable but due to no-content it is not inserted into the article.

#### System information (as much as possible)
Apache 2 on Linux 3.13 Ubuntu
PHP 5.6.17 (CGI)
MySQL 5.0
Joomla 3.4.8

#### Additional comments
Reason of this request: Our images are uploaded to a folder outside of Joomlas root. To avoid manually copying these files to Joomla/images this could be a great solution.

Additionally there are much more operation purposes:
Get files for a download application from an outside located folder.
Get videos.
Etc.

**Comment by richard67** [comment]
I cannot reproduce your issue.

I have my media outside the joomla folder, but on same level, so e.g. Joomla is in ~/joomla and my media is in ~/sitemedia, and in the Joomla folder I have a special subfolder, e.g. ~/joomla/sitemedia, and this has a folder structure with links to real files in some subfolders of ~/sitemedia. The subfolder structures in both sitemedia folders are same but this is not necessary, is just my taste.

The links in the ~/joomla/sitemedia structure point to the real files in the ~/sitemedia structure.

In Joomla media manager properties I adjusted the subfolder "sitemedia" (which means in this case the ~/joomla/sitemedia) as the starting point (media folder which is then shown as the root "/").

In .htacces I have set the "Options +FollowSymlinks".

When I now wanna inderst a pic in an article using the "Picture" button, I get the wizard and can browse the structure and see thumbnails of the pics and can select and insert them, see following screenshot:

![screen shot 2016-02-27 at 20 29 52](https://issues.joomla.org/uploads/1/89ff1165b0e4176d947e9e7c9eda27e5.png)

When I select the thumbnail, the url field is filled, and I can insert the pic into the article.

My media manager settings look like this:

![screen shot 2016-02-27 at 20 29 58](https://issues.joomla.org/uploads/1/ef5604a0c58d6f5bb4366c3d285d3790.png)

And on the shell inside sich a a listing of such a link looks like this:

(uiserver):u1234567:~/joomla2/sitemedia/audio/fade> ls -al fade-sunny-noises-2003_thumb_og.jpg
lrwxrwxrwx 1 u123456789 ftpusers 95 Feb 15  2015 fade-sunny-noises-2003_thumb_og.jpg -> /kunden/homepages/38/d1234567890/htdocs/sitemedia/audio/fade/fade-sunny-noises-2003_thumb_og.jpg

So I cannot reproduce or confirm your issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9210">issues.joomla.org/joomla-cms/9210</a>.</sub>

**Comment by richard67** [comment]
P.S.: Maybe the rason is that you use relative links, like gagalink -> ../dadadir/soandsofile.gif?

I suggest to use absolute links, like gagalink -> /path/to/some/dir/dadadir/soandsofile.gif.

Those won't break when you move around some folder.

**Comment by alve89** [comment]
Thank you for your hints!
So am I right that your links are linking the files directly? Because my symlink points to a folder that contains the images (see screenshot below).

![bildschirmfoto 2016-02-28 um 10 09 33](https://cloud.githubusercontent.com/assets/11487054/13378320/67d5d15a-de03-11e5-88ab-1a0e65f0bb0a.png)

First of all I added the .htaccess directive as mentioned above but this didn't achieved success.
Then - because the actual symlink was relative - I created an absolute one. See the listing below:

```
lrwxrwxrwx  1 ssh-w013f149 w013f149  108 Feb 28 10:16 images2 -> /www/htdocs/w013f149/cloud/STATIC_DATA_DIR/webm.suf/files/Save Uganda Foundation/website/website data/images
lrwxrwxrwx  1 ssh-w013f149 w013f149   93 Feb 24 20:02 images_from_cloud -> ../../cloud/STATIC_DATA_DIR/webm.suf/files/Save Uganda Foundation/website/website data/images
```

Joomla follows both links but both are displayed the same way (like you can see on the screenshot).

Do you have an idea what else I could do (if I do NOT want to symlink every file inside the target directory but the whole folder)?

**Comment by alve89** [comment]
I think I found the problem: It's the chmod 770 of STATIC_DATA_DIR. With 775 it works properly but it set automatically when I access the web interface of the cloud. :-(

Thank you anyway!

PS: It only works with the relative link, just fyi.

**Comment by richard67** [comment]
Yeah, I link the files, not the folders, sorry when it confused you.
