### ISSUE TITLE
mod_languages is ignoring full_name parameter when Use Dropdown is selected

### ISSUE THREAD

**Issue by artur-stepien** [joomla/joomla-cms#9224]
#### Steps to reproduce the issue
Add mod_languages module. Chose "Use Dropdown" and deselect "Languages Full Names".

#### Expected result
Only short names (PL,EN,RU) in languages select module

#### Actual result
Full names

#### System information (as much as possible)
Joomla! 3.4.8

#### Additional comments
Just a little fix.

**Comment by infograf768** [comment]
please read the instructions better:
If Use Dropdown is set to 'Yes', <br />the display options below will be ignored</u><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9224">issues.joomla.org/joomla-cms/9224</a>.</sub>

**Comment by artur-stepien** [comment]
I saw that. But the fact that **Languages Full Names** is still available when **Using Dropdown** is ON is misleading. Also there is no logical reason to disable this functionality when using dropdown.

**Comment by brianteeman** [comment]
Closed as there is a PR #9225 please continue the discussion there.

@artur-stepien you dont need to create an issue on the tracker when you create a PR on github. Magic happens and its automatically done<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9224">issues.joomla.org/joomla-cms/9224</a>.</sub>
