### ISSUE TITLE
SEF URLs Not Functioning for Search and Smart Search Modules

### ISSUE THREAD

**Issue by dcrabill** [joomla/joomla-cms#9226]
#### Steps to reproduce the issue
1) Enable SEF URLs and URL rewriting in Global Config
2) Rename htaccess.txt to .htaccess
3) Enter search term "test" into Search module Input box

#### Expected result
To land at a clean Search Resuts URL something to the effect of:
mysite.com/results

#### Actual result
Routed to:
mysite.com/component/search/?searchword=test&searchphrase=all&Itemid=101

#### System information (as much as possible)
Database Version	5.6.28-76.1-log
Database Collation	utf8_general_ci
PHP Version	5.6.18
Joomla! Version	Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT

**Comment by brianteeman** [comment]
That is working as intended

If you wish to have a url such as /results then you must create a menu link called results to the search component

If you require additional help on this please use the forum http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9226">issues.joomla.org/joomla-cms/9226</a>.</sub>
