### ISSUE TITLE
Media Manager replacement

### ISSUE THREAD

**Issue by artur-stepien** [joomla/joomla-cms#9229]
I know there where plans to create new media manager for feature versions. But was this started? Anyone volunteered? Current one is not only rusty. It lacks new features of modern browser, performance and usability.

If any one will have some time to discuss about this I can spend some time and create replacement.

**Comment by brianteeman** [comment]
There was a "new media manager" sprint in the Netherlands back in December (iirc) and the repo they were working on can be found here https://github.com/joomla-projects/media-manager-improvement

Maybe @roland-d or @yireo can provide further information<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9229">issues.joomla.org/joomla-cms/9229</a>.</sub>

**Comment by dgt41** [comment]
The current repo that me and @yireo are working on (unfortunately not much done lately on my side) is here: https://github.com/jissereitsma/media-manager-improvement
If you want to help please contact me on Skype to discuss the vision and the approach we are following
my Skype id is velocity-gr

**Comment by brianteeman** [comment]
Closed as question answered<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9229">issues.joomla.org/joomla-cms/9229</a>.</sub>
