### ISSUE TITLE
Menu Assignment tree closing before complete

### ISSUE THREAD

**Issue by severdia** [joomla/joomla-cms#9233]
#### Steps to reproduce the issue
Create a module (I created a Custom HTML module)
Create a large number of nested menus with nested menu items
Open the module menu assignment tab to assign locations.

#### Expected result
The menu tree is correctly rendered.

#### Actual result
The menu tree is only partially rendered correctly.

#### System information (as much as possible)
OS Linux s
PHP 5.6.18
MySQLi 5.5.31-30.3-log
Web server: Apache/2.2.24 (Unix) mod_hive/5.0 mod_ssl/2.2.24 OpenSSL/1.0.0-fips mod_auth_passthrough/2.1 mod_bwlimited/1.4 mod_fastcgi/2.4.6 mod_fcgid/2.3.6
Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT

#### Additional comments
See the attached screenshot showing multiple menus. The first menus and their menu items render correctly. But where a new menu starts, the closing `<ul>` tag is added prematurely. The list continues and it breaks both usage and display.

![screen shot 2016-02-27 at 9 32 40 am](https://cloud.githubusercontent.com/assets/355924/13374456/33ae1974-dd3a-11e5-9b87-dde7ea0d0124.png)

Also attached below is a code sample of that section of the page. The top part of the page (down to line 4000 or so) is correct, but the closing tag is added here instead of at the end of the `<li>` list.

[example.txt](https://github.com/joomla/joomla-cms/files/149472/example.txt)

**Comment by brianteeman** [comment]
Please can you retest against the current staging - I can't replicate this issue and I seem to recall this being resolved in a previous PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9233">issues.joomla.org/joomla-cms/9233</a>.</sub>

**Comment by severdia** [comment]
Verified as still a bug in current staging.

**Comment by brianteeman** [comment]
Weird as I dont see it - maybe I am not following your instructions correctly

![kfbb](https://cloud.githubusercontent.com/assets/1296369/13375000/8b96dd40-dd8c-11e5-8128-a476507b9e23.png)

**Comment by dgt41** [comment]
@severdia are you using advanced module manager in your test site?

**Comment by severdia** [comment]
No, I'm not using Advanced Module Manager. 

Do this to reproduce in staging:

1. Do a fresh install.
2. Replace the two default menu tables ( *_menu and *_menu_types) with a large multi-layer menu. See the attached SQL script. Make sure to update the table prefix to your own (no, that's not mine in the file).
3. Create a new custom module and try to assign a menu item.

[menu_tables.sql.zip](https://github.com/joomla/joomla-cms/files/149555/menu_tables.sql.zip)

**Comment by brianteeman** [comment]
Thanks Ron. I will retest with your supplied data in the morning

**Comment by brianteeman** [comment]
The good news is that I have imported the data and can see what you mean.

However the data is showing something else that is odd. If you try to collapse all the menus you can see that the "other menu" doesnt collapse properly.
![s6qp](https://cloud.githubusercontent.com/assets/1296369/13375845/f4f6d748-dda2-11e5-84aa-45c146b7ec9f.png)

This suggested to me that it was an issue in your "other menu" and nothing to do with the nested menus in the "plays menu". To test this theory I trashed the "other menu" and proved my theory as the "plays menu" now displays correctly.
![5jtg](https://cloud.githubusercontent.com/assets/1296369/13375873/73323e86-dda3-11e5-8407-5ceb40734d5a.png)

Conclusion there is nothing wrong with Joomla - the problem is somewhere in your database

**Comment by severdia** [comment]
Yes, I've just discovered in the Other menu there are menu items where a level is missing.

![screen shot 2016-02-27 at 2 54 19 pm](https://cloud.githubusercontent.com/assets/355924/13375941/21466110-dd62-11e5-912c-21768e1279f0.png)

Under "Reviews Extra" there are four menu item aliases that are somehow not mapped to a parent. Opening and re-saving those items fixed the issue. I'll close this. Thank you.

**Comment by brianteeman** [comment]
No problem glad to have helped
