### ISSUE TITLE
Showon modification

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#9235]
#### Steps to reproduce the issue
place form control in fieldset 1
place showon field in a different fieldset

#### Expected result
showon only functions if the condition is met

#### Actual result
showon shows always.

#### System information (as much as possible)

3.4.8 staging.

#### Additional comments
The reason you might want this is your "switch" might be used across multiple tabs.

**Comment by N6REJ** [comment]
not sure why the title says require but I'll leave that to others to solve.

**Comment by andrepereiradasilva** [comment]
> System information (as much as possible)
> 3.4.8 staging.

3.4.8 or 3.5.0 staging?

**Comment by N6REJ** [comment]
at this point would be 3.5 beta 2
Bear

**Comment by brianteeman** [comment]
Is this the same as #6744 ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9235">issues.joomla.org/joomla-cms/9235</a>.</sub>

**Comment by N6REJ** [comment]
yes
