### ISSUE TITLE
Conditional Fieldset feature request

### ISSUE THREAD

**Issue by N6REJ** [joomla/joomla-cms#9236]
#### Steps to reproduce the issue
Currently if your using a repeatable formfield there is an entire fieldset that is hidden unless the 
formfield meets its condition.  So its easily possible to turn and repeatable completely on/off based on user inputs.

#### Expected result
It would be useful if there was a "conditional" formfield where much like the repeatable your able to hide an entire fieldset.  This could also have a "modal" param much like showon where if it was active would display this sub-fieldset in a modal and where if not would just display it like normal.

#### Actual result
Currently not possible

#### Additional comments

This would be useful where there is a large group of parameters that don't make sense to display unless some other condition has been met.

**Comment by brianteeman** [comment]
I would say that if you want this as a modal then you can already use the repeatable field or the newly proposed subform and if you want them to be displayed as a group in the main body then you can already do this with the showon as can be seen in global configuration and most component options now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9236">issues.joomla.org/joomla-cms/9236</a>.</sub>

**Comment by N6REJ** [comment]
neither of those will let you simply turn on / off entire fieldsets.. showon doesn't work for fieldsets, and repeatable creates a view therefore it's its own fieldset.

**Comment by Bakual** [comment]
> showon doesn't work for fieldsets

It works for fieldsets in the component config: https://github.com/joomla/joomla-cms/pull/9668
If it's in the extension itself, you need to adjust the extension code to support it.
