### ISSUE TITLE
Search filters case sensitive in pgsql

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9242]
#### Steps to reproduce the issue
Go to extensions->install languages
Search for french

#### Expected result
two languages are found

#### Actual result
With Mysql you see two languages
With PGSQL you see zero languages

#### Additional comments
Repeat pgsql test with searching for French and you get matches

@alikon can you take a look please

**Comment by brianteeman** [comment]
Looks like it is only the search filter on the install languages page - the other search filters I tested were all ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9242">issues.joomla.org/joomla-cms/9242</a>.</sub>

**Comment by andrepereiradasilva** [comment]
just a question, did you test with this PR https://github.com/joomla/joomla-cms/pull/9089

**Comment by brianteeman** [comment]
No - I will apply that now and see if it is resolved by the changes you
made there

On 28 February 2016 at 12:48, andrepereiradasilva <notifications@github.com>
wrote:

> just a question, did you test with this PR #9089
> <https://github.com/joomla/joomla-cms/pull/9089>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9242#issuecomment-189864265>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Sorry to say that #9089 doesnt resolve it

On 28 February 2016 at 12:49, Brian Teeman <brian@teeman.net> wrote:

> No - I will apply that now and see if it is resolved by the changes you
> made there
>
> On 28 February 2016 at 12:48, andrepereiradasilva <
> notifications@github.com> wrote:
>
>> just a question, did you test with this PR #9089
>> <https://github.com/joomla/joomla-cms/pull/9089>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joomla/joomla-cms/issues/9242#issuecomment-189864265>
>> .
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
sure, it was just a wild guess.

I dont know much about PGSQL neither have the means to test, but maybe the problem should be in this line? https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_installer/models/languages.php#L128

**Comment by andrepereiradasilva** [comment]
if i'm right the same problem exists in other views (ex: newsfeeds).

**Comment by brianteeman** [comment]
Will check after lunch. If you are on a Mac then you can easily use
postgres with http://postgres.app

if i'm right the same problem exists in other views (ex: newsfeeds).

—
Reply to this email directly or view it on GitHub
<https://github.com/joomla/joomla-cms/issues/9242#issuecomment-189867591>.

**Comment by andrepereiradasilva** [comment]
no mac here i leave postgresql to others.
my interrest in just learn the more noticleble differences in queries between mysql and postgreSQL so when modfiying some code don't make regressions to postgresql.

**Comment by brianteeman** [comment]
News feeds is fine

On 28 February 2016 at 13:34, andrepereiradasilva <notifications@github.com>
wrote:

> no mac here i leave postgresql to others.
> my interrest in just learn the more noticleble differences in queries
> between mysql and postgreSQL so when modfiying some code don't make
> regressions to postgresql.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9242#issuecomment-189872517>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Looks like this might work http://alvinalexander.com/sql/sql-select-case-insensitive-query-queries-upper-lower but not sure 
@alikon should have the answer so I will wait for the maestro<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9242">issues.joomla.org/joomla-cms/9242</a>.</sub>

**Comment by alikon** [comment]
:laughing:

**Comment by brianteeman** [comment]
Closed as we have a PR #9244 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9242">issues.joomla.org/joomla-cms/9242</a>.</sub>
