### ISSUE TITLE
Duplicate Key Entry for idx_term in #__finder_terms after updating to 3.5b3 an running db fix again

### ISSUE THREAD

**Issue by swiffer** [joomla/joomla-cms#9249]
#### Steps to reproduce the issue

1. Run Database Fix Tool after upgrading to 3.5b3 on an utf8mb4 capable site

#### Expected result

1. Migrate Database to utf8mb4_general_ci

#### Actual result

1. An error is shown for #__finder_terms (idx_term) duplicate entry

#### Additional comments

1. Delete the Search index
2. Run Database migrations
3. Rebuild the search index

Fixes the Problem!

**Comment by wilsonge** [comment]
OK So I am super confused here - because this column is VARCHAR(75) length so we should never exceed it's length. I have tried several times and I'm unable to replicate this in anyway. Have you been able to identify the rows that are triggering this?

**Comment by swiffer** [comment]
sorry, i directly cleaned the index and rebuild it after running the migrations

**Comment by wilsonge** [comment]
Do you not have a copy of the original site (you should never run betas on production sites!) - but if not then I'll have to close this as neither me nor Eli could find a way to replicate the issue

**Comment by wilsonge** [comment]
OK As we don't have a copy of the data closing in favour of #9361 where we have some data we can use for replication purposes
