### ISSUE TITLE
TOS article: navigation possible in the modal

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#9250]
Create an article to use as Terms of Service.
Enable the User Profile plugin.
Set "Terms of service" to Required
Select the article in the "Select TOS Article" field

Then go to frontend and Create an account

Click on the "Terms of Service" link at bottom of the User Profile part.
![screen shot 2016-02-29 at 04 33 13](https://issues.joomla.org/uploads/1/c1422c91db2fb41069645f672eac5feb.png)

The Modal loads the article but it also displays a Navigation (Prev Next)

![screen shot 2016-02-29 at 04 31 06](https://issues.joomla.org/uploads/1/283d53d76ee72db0da070b2dcbe2f36c.png)

Click on one of the buttons: it will display another article in a full site view in the modal.
![screen shot 2016-02-29 at 04 31 57](https://issues.joomla.org/uploads/1/14fb3aaca520d2e2de0778676dda179e.png)

We should manage to not display Prev Next in the modal.

**Comment by brianteeman** [comment]
Surely its not just that page navigation link that you (I wouldnt bother myself) would want to disable. There may be other links on the page as well. For example in your screenshot there is a link to the author and the category.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9250">issues.joomla.org/joomla-cms/9250</a>.</sub>

**Comment by infograf768** [comment]
Indeed

**Comment by infograf768** [comment]
Oops, I am deleting this as the parameters have to be set in the article itself. Sorry for bothering.

**Comment by brianteeman** [comment]
I thought there must be a way ;)

On 29 February 2016 at 10:44, infograf768 <notifications@github.com> wrote:

> Oops, I am deleting this as the parameters have to be set in the article
> itself. Sorry for bothering.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9250#issuecomment-190149412>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
