### ISSUE TITLE
System Information paths

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9252]
The new feature to enable downloading system information by @Radek-Suski and @phproberto will obfuscate certain information in the download.

For example the following values from the configuration file 
log_path: xxxxxx
tmp_path: xxxxxx

But the same information is also downloaded as part of the folder permissions and is not obfuscated
Example
/Applications/MAMP/htdocs/joomla-cms-staging/logs:  writable
/Applications/MAMP/htdocs/joomla-cms-staging/tmp:  writable

**Comment by brianteeman** [comment]
The absolute path is also available in the information downloaded from the PHP information 
Example
=============
		error_log
		=============
		Local Value: /Applications/MAMP/logs/php_error.log
		Master Value: /Applications/MAMP/logs/php_error.log

		upload_tmp_dir
		=============
		Local Value: /Applications/MAMP/tmp/php
		Master Value: /Applications/MAMP/tmp/php<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9252">issues.joomla.org/joomla-cms/9252</a>.</sub>

**Comment by brianteeman** [comment]
To fix the error_log and the upload_tmp_dir we just need to add them to the phpInfoArray section of the protected $privateSettings 

Not sure how to fix the directory path part from the folder permissions section<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9252">issues.joomla.org/joomla-cms/9252</a>.</sub>

**Comment by wilsonge** [comment]
If you could do those two array elements would be appreciated Brian - then I'll repeatedly annoy @Radek-Suski until I get something back :D

**Comment by brianteeman** [comment]
give me 30

On 2 March 2016 at 00:03, George Wilson <notifications@github.com> wrote:

> If you could do those two array elements would be appreciated Brian - then
> I'll repeatedly annoy @Radek-Suski <https://github.com/Radek-Suski> until
> I get something back :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9252#issuecomment-190978293>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
sure :)

**Comment by brianteeman** [comment]
See #9274 for fix for
log_path: xxxxxx
tmp_path: xxxxxx

On 2 March 2016 at 00:10, George Wilson <notifications@github.com> wrote:

> sure :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9252#issuecomment-190982705>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Radek-Suski** [comment]
That should do the trick

**Comment by brianteeman** [comment]
@radek I couldnt work out how to obfuscate the file path to temp etc in the
file permissions tab. George had a go BUT that removed it from the web
interface as well

On 2 March 2016 at 10:20, Radek Suski <notifications@github.com> wrote:

> That should do the trick
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9252#issuecomment-191172292>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Sorry just saw your PR

On 2 March 2016 at 10:29, Brian Teeman <brian@teeman.net> wrote:

> @radek I couldnt work out how to obfuscate the file path to temp etc in
> the file permissions tab. George had a go BUT that removed it from the web
> interface as well
>
> On 2 March 2016 at 10:20, Radek Suski <notifications@github.com> wrote:
>
>> That should do the trick
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joomla/joomla-cms/issues/9252#issuecomment-191172292>
>> .
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
