### ISSUE TITLE
Plugin "content/joomla" "onContentAfterSave() Undefined variable: result

### ISSUE THREAD

**Issue by m4ucoder** [joomla/joomla-cms#9253]
#### Steps to reproduce the issue
Enable all errors reporting in php.
Add "exit()" to the end of the onContentAfterSave() method (this is for watching the error)
In the front-end, add a menu item "propose an article".
In the front-end do log as an user which can add article.
When the article is submitted, the following error is displayed:
Notice: Undefined variable: result in /home/plambotte/Public/projets/web/joomla3dev/component-factory/plugins/content/joomla/joomla.php on line 93

#### Expected result
No "notice" error

#### Actual result
Notice: Undefined variable: result in /home/plambotte/Public/projets/web/joomla3dev/component-factory/plugins/content/joomla/joomla.php on line 93

#### Proposed bug resolution:
Solution #1: Adding a default value for $result on the beginning of the method
Or solution #2: Add a default value for $result before the foreach (line#75)
$result = true;

**Comment by brianteeman** [comment]
Closing as we hve a PR for testing #9277 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9253">issues.joomla.org/joomla-cms/9253</a>.</sub>
