### ISSUE TITLE
Force to use HTML: Special Characters during component installation mysql queries

### ISSUE THREAD

**Issue by gunjanpatel** [joomla/joomla-cms#9254]
Not sure if it is a bug or not but found interesting.

#### Steps to reproduce the issue
While installing component I notice that my queries doesn't work in j3.5-beta3.

**Query Working in J3.4x**
```sql
INSERT IGNORE INTO `#__redshop_mail` (`mail_id`, `mail_body`) VALUES
	(1, '<p>To Admin, {username} </p>');
```

**The same query is not working in J3.5-beta3. While I change query as shown below it works.**
```sql
INSERT IGNORE INTO `#__redshop_mail` (`mail_id`, `mail_body`) VALUES
	(1, '&lt;p&gt;To Admin,&lt;/p&gt;');
```
To make it working in j3.5-beta3 I have to change,
`'<p>To Admin,</p>'` to `'&lt;p&gt;To Admin, {username} &lt;/p&gt;'`

Not sure what is changed in j3.5-beta3. But the same query works in j3.4.x and if I paste the query directly in mysql it works.

**Comment by andrepereiradasilva** [comment]
can you check if it worked in 3.5.0 beta 2?
https://github.com/joomla/joomla-cms/releases/download/3.5.0-beta2/Joomla_3.5.0-beta2-Beta-Full_Package.zip

**Comment by gunjanpatel** [comment]
@andrepereiradasilva it works with 3.5.0 beta 2. Only issue in 3.5 beta 3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9254">issues.joomla.org/joomla-cms/9254</a>.</sub>

**Comment by andrepereiradasilva** [comment]
just guessing maybe because of a change that was corrected today (see https://github.com/joomla/joomla-cms/commit/fc4324593c230594e95c561d425cfbb5410a0725)

Can if you rissue remains in latest staging
https://github.com/joomla/joomla-cms/archive/staging.zip

**Comment by wilsonge** [comment]
I don't *think* so - that issue was specifically dealing with hashtags that aren't present in the SQL file dump provided. I need some more information please gunjan - I don't really have enough here to work with

**Comment by flash1452** [comment]
I don't think it should happen in HTML because i have had experience of such errors in XML,not with HTML tags.

**Comment by gunjanpatel** [comment]
@wilsonge I am going to attach installer in which I am having issue. May be it will help to reproduce it.
[HelloWorldj3.5.beta3](https://github.com/joomla/joomla-cms/files/156444/helloworld.zip)

**Comment by javigomez** [comment]
I can confirm that it works in Joomla 3.5.0-beta2:

![screen shot 2016-03-03 at 10 20 44](https://cloud.githubusercontent.com/assets/1375475/13489986/41db8df8-e12a-11e5-9152-b2d247902ded.png)

While fails in Joomla 3.5.0-beta3:

![screen shot 2016-03-03 at 10 21 13](https://cloud.githubusercontent.com/assets/1375475/13489997/5042e2a6-e12a-11e5-8b0e-b19da1eecfc6.png)

**Comment by infograf768** [comment]
I could install OK HelloWorldj3.5.beta3 on staging (localhost)

**Comment by javigomez** [comment]
I have been able to isolate the problem. The issue happens when using a `#` symbol in the sql. This fails:

data.sql:

```sql
INSERT IGNORE INTO `#__helloworld_mail` (`mail_id`, `mail_name`, `mail_subject`, `mail_section`, `mail_order_status`, `mail_body`, `published`, `mail_bcc`) VALUES
	(24, 'Order Status Change Pending', 'Order Status Change Pending', 'order_status', 'P', '#', 1, ''),
	(25, 'Order Status Change Confirmed', 'Order Status Change Confirmed', 'order_status', 'C', '#', 1, '');
```

But if you remove the `#` at  `...'order_status', 'P', '#', 1, ''),...` and at `...er_status', 'C', '#', 1, '');`

It works

I'm attaching the example component refactored:

[com_helloworld.zip](https://github.com/joomla/joomla-cms/files/156542/com_helloworld.zip)

**Comment by javigomez** [comment]
I confirm @infograf768 comment the problem does not happen in staging:

![screen shot 2016-03-03 at 11 19 16](https://cloud.githubusercontent.com/assets/1375475/13491269/d4bf0030-e131-11e5-9cd4-8d64f2722d86.png)

It appears only testing against https://github.com/joomla/joomla-cms/releases/tag/3.5.0-beta3

**Comment by brianteeman** [comment]
Then this can be closed then as it has already been fixed

On 3 March 2016 at 10:20, javier gomez <notifications@github.com> wrote:

> I confirm @infograf768 <https://github.com/infograf768> comment the
> problem does not happen in staging:
>
> [image: screen shot 2016-03-03 at 11 19 16]
> <https://cloud.githubusercontent.com/assets/1375475/13491269/d4bf0030-e131-11e5-9cd4-8d64f2722d86.png>
>
> It appears only testing against
> https://github.com/joomla/joomla-cms/releases/tag/3.5.0-beta3
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9254#issuecomment-191694665>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ot2sen** [comment]
Adding the fix for driver.php from https://github.com/joomla/joomla-cms/commit/fc4324593c230594e95c561d425cfbb5410a0725  do solve the issue it seems
