### ISSUE TITLE
Database Error when upgrading from 3.5.0.beta2 to 3.5.0.beta3

### ISSUE THREAD

**Issue by coolman01** [joomla/joomla-cms#9255]
#### Steps to reproduce the issue
Upgrade a core version of Joomla 3.5.0 beta2 by using the installer to install the new version 3.5.0 beta3

#### Expected result

No errors

#### Actual result

Error in Database check.

#### System information (as much as possible)

PHP Built On	Windows NT DESKTOP-A55DI1C 6.2 build 9200 (Windows 8 Professional Edition) i586
Database Version	5.5.5-10.1.9-MariaDB
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.15
Web Server	Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.15
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.5.0-beta3 Beta [ Ember ] 28-February-2016 23:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

#### Additional comments

After installing the upgrade, I checked to see if anything was to be found under "Discover" then I checked the Database Tab and found the following error message:

Warning Database is not up to date!
1 Database Problem Found
. The Joomla! Core databse tables have not been converted yet to UTF-8 Multibyte (utf8mb4)

I used the "Fix" button and that solved the problem. Maybe this is nothing, but I thought I'd report it.

**Comment by brianteeman** [comment]
https://www.joomla.org/announcements/release-news/5646-joomla-3-5-beta-3-released.html


> This is a BETA release, that should only be used on test sites. Beta releases cannot be upgraded. Please note that you cannot upgrade from beta 2 to beta 3.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9255">issues.joomla.org/joomla-cms/9255</a>.</sub>
