### ISSUE TITLE
Attachment does not support Chinese

### ISSUE THREAD

**Issue by a7517** [joomla/joomla-cms#9256]
Attachment does not support Chinese

How can use the date named files

**Comment by a7517** [comment]
Date format file name is not good for you?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9256">issues.joomla.org/joomla-cms/9256</a>.</sub>

**Comment by brianteeman** [comment]
where do you mean? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9256">issues.joomla.org/joomla-cms/9256</a>.</sub>

**Comment by a7517** [comment]
Do not know how to modify, can be compatible with Chinese characters<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9256">issues.joomla.org/joomla-cms/9256</a>.</sub>

**Comment by brianteeman** [comment]
What do you mean by attachment? Maybe show a picture

**Comment by artur-stepien** [comment]
I think this is not Joomla! CMS related. This can be a problem with third party component cause there is no attachments functionality in pure Joomla CMS.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9256">issues.joomla.org/joomla-cms/9256</a>.</sub>

**Comment by a7517** [comment]
Attachment name does not support Chinese characters

**Comment by artur-stepien** [comment]
What attachments, Where, what is the name of the component. Or at least provide a URL

**Comment by a7517** [comment]
Media

**Comment by artur-stepien** [comment]
You have problem uploading or downloading files? What is the exact name of the file uploaded?

**Comment by a7517** [comment]
Chinese characters are not

**Comment by a7517** [comment]
example:阿图尔.jpg

**Comment by artur-stepien** [comment]
What is the Joomla Version?

**Comment by a7517** [comment]
All versions have this problem

**Comment by brianteeman** [comment]
If I remember correctly joomla only supports [a-z,A-Z] in filenames

**Comment by a7517** [comment]
China, Japan, Korea.....
Are required to support GBK characters

**Comment by artur-stepien** [comment]
I will can check if conversion and storing/serving such files is possible.

**Comment by infograf768** [comment]
this is an old issue that files can't contain utf8 glyphs in their names.
if i remember well, it is a matter of security.

**Comment by artur-stepien** [comment]
If so why not to try convert file names to a-z (I know that is worst idea) but still better then doing nothing.

**Comment by a7517** [comment]
There is no readability, bad for SEO

**Comment by artur-stepien** [comment]
SEO in file names is practically non-existing. This is more about ALT etc. But this is out of topic. When there is security risc with storing such names automatic conversion is better then nothing.

**Comment by a7517** [comment]
Suggest you can under reference:wordpress

**Comment by infograf768** [comment]
I confirm it is possible in wordpress. 
Hmm. I kind of remember though we had a lot of discussions about com_media on this.

**Comment by brianteeman** [comment]
Wasnt the problem that we dont know if the filesystem of the server supports those characters in filenames?

**Comment by brianteeman** [comment]
Thank you for submitting this issue/pull request. The media manager is currently being completely rewritten and I have notified the development team about this issue for their consideration. I am closing this here at this time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9256">issues.joomla.org/joomla-cms/9256</a>.</sub>
