### ISSUE TITLE
Searching in Install from Web

### ISSUE THREAD

**Issue by Avalonmist** [joomla/joomla-cms#9257]
#### Steps to reproduce the issue
1. in the admin side of Joomla, go to Extensions >> Install
2. On the Install from Web tab, click into the search field and type 'VirtueMart' (without quotes)
3. Click the magnifying glass search button
4. Look for "VirtueMart" within the search results.

#### Expected result
The Name of the extension should be weighted first and therefore the extension "VirtueMart" should have been first before any other extensions with "VirtueMart" in the description. Not sure why "Breezing Forms" keeps popping up first. Sort dropdown box should be defaulted to "Sort be Relevance" 

#### Actual result
The "VirtueMart" Extension is not listed, "Breezing Forms" is the first one listed which is not even close to "VirtueMart".

I even tried to go into the e-Commerce category and search from there but it jumped to the "Home" category and guess what? ... "Breezing Forms" is at the top.

#### System information (as much as possible)
Joomla 3.4.8

**Comment by brianteeman** [comment]
The Install from Web plugin has its own issue tracker. Please create the issue there https://github.com/joomla-extensions/install-from-web-client<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9257">issues.joomla.org/joomla-cms/9257</a>.</sub>
