### ISSUE TITLE
SMTP From address is not used with private messages

### ISSUE THREAD

**Issue by bluemonkmn** [joomla/joomla-cms#9261]
#### Steps to reproduce the issue

Configure the server global settings to use SMTP email and enter a value in the From address.
Use Components -> Messaging -> New Private Message to send a message from an admin with a different address to another user.
#### Expected result

User should receive an email to their configured email address that is from the SMTP from address with a reply-to reflecting the user email address who sent the message
#### Actual result

"SMTP Error: data not accepted" due to the fact that the SMTP server expects the From address to be on a local domain, but it was using the sender's email address instead. See http://joomla.stackexchange.com/questions/15444/smtp-email-failing-via-joomla-succeeding-outside-of-joomla
#### System information (as much as possible)

Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
Dreamhost web host
PHP version 5.5.26
Web Server: Apache
WebServer to PHP Interface: cgi-fcgi
SMTP configuration...
Send Mail: Yes
Mailer: SMTP
From email: bluemonkmn@sgdk2.enigmadream.com
From name: Benjamin Marty
Disable Mass Mail: No
SMTP Authentication: Yes
SMTP Security: None
SMTP Port: 25
SMTP Username: bluemonkmn@sgdk2.enigmadream.com
SMTP Password: (same password I used in other tests that worked)
SMTP Host: mail.sgdk2.enigmadream.com
#### Additional comments

The same test succeeds if I change the sending user's email address to match the SMTP From address.
It's not clear if this problem extends beyond private messages. that's just the easiest way I know how to test Joomla email.

**Comment by Kimball31** [comment]
PHP Mail has a similar, probably related issue on Joomla! 3.4.8, when using Mass Mail. 

Using Mass Mail, when I send to Super Users is the email is sent ok. But, when I send to Registered users the email is not sent. I'm sending as BCC in both cases. All of the other settings are the same. I only change from Super Users to Registered. 

In /administrator/php_mail.log the failed message has two "To:" recipients, the first one being empty.   

  mail() on [/home/nhrpoa/public_html/libraries/vendor/phpmailer/phpmailer/class.phpmailer.php:615]: 
  To:  -- 
  Headers: Date: Fri, 26 Feb 2016 15:30:07 -0600 
  To: undisclosed-recipients:; 
  From: NHRPOA <######@######.net> 
  Bcc: ######@######.com, ...   

The successful email to Super Users log looks like this:

  mail() on [/home/nhrpoa/public_html/libraries/vendor/phpmailer/phpmailer/class.phpmailer.php:615]: 
  To: ######@######.net -- 
  Headers: Date: Fri, 26 Feb 2016 13:18:36 -0600 
  From: NHRPOA <######@######.net> 
  Bcc: ######@######.com, ...
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9261">issues.joomla.org/joomla-cms/9261</a>.</sub>

**Comment by mbabker** [comment]
See https://github.com/joomla/joomla-cms/pull/13518 for testing.
