### ISSUE TITLE
Label problems

### ISSUE THREAD

**Issue by a7517** [joomla/joomla-cms#9263]
When using, Chinese characters input often wrong, it is difficult to choose

**Comment by brianteeman** [comment]
Can you please give some examples so people can see the problem. Maybe include pictures<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9263">issues.joomla.org/joomla-cms/9263</a>.</sub>

**Comment by a7517** [comment]
you can try the next<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9263">issues.joomla.org/joomla-cms/9263</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this as there is just not enough information that describes the problem or how to replicate it. It can always be reopened <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9263">issues.joomla.org/joomla-cms/9263</a>.</sub>
