### ISSUE TITLE
One can not add any JavaScript events in TinyMCE editor

### ISSUE THREAD

**Issue by konstantin-karetny** [joomla/joomla-cms#9268]
Even when I log in as Super Administrator with selected 'No Filtering' filter type in System => Global Configuration => Text Filters;
Even when I add 'script' in 'Valid Elements' field in 'Editor - TinyMCE' plugin settings;
I still can not add JavaScript events like ```onclick``` for tags in TinyMCE editor.
I think if I am Super Administrator with all rights I must have some opportunity to make some elementary actions like this one. Am I wrong?

**Comment by richard67** [comment]
What does the field "Prohibited Elements" in the plugin settings of TinyMCE (is at the very bottom of the 1st tab) contain?

If it contains "script", remove that, and it will work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9268">issues.joomla.org/joomla-cms/9268</a>.</sub>

**Comment by konstantin-karetny** [comment]
Sure I tried that, and it's allows me only to add a ```<script></script>``` tag, but I need to add an attribute ```onclick=""``` to an existing tag.
TinyMCE just deletes all event attributes like ```onclick``` at any settings, that's the problem.

**Comment by richard67** [comment]
Hmm, I see ... sorry for asking.

**Comment by konstantin-karetny** [comment]
Kein Problem!
Yes, try to play with this. Judging by deep gooling this is the old issue but there is no solution for now.
At least I have not found it yet.

**Comment by brianteeman** [comment]
Have you looked through the tinymce bug tracker?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9268">issues.joomla.org/joomla-cms/9268</a>.</sub>

**Comment by dgt41** [comment]
What is the tag that you are trying to put the `onclick`? `<a>` or something else?

**Comment by dgt41** [comment]
Also from tinymce' documentation:
> Also note that all event attributes are excluded by default since it's a bad practice to use inline script handles like "onclick". You can manually add extra elements and attributes using the extended_valid_elements option.

https://www.tinymce.com/docs/configure/content-filtering/#extended_valid_elements

**Comment by konstantin-karetny** [comment]
dgt41, I tried to add ```onclick``` to different tags.
Many thanks for link!
Now topic can be closed, the problem is solved.
I just set `*[*]` value for the 'Valid Elements' field, according to to the TinyMCE documentation:

> Use `*[*]` to include all elements and all attributes.

https://www.tinymce.com/docs/configure/content-filtering/#specialvariables

**Comment by brianteeman** [comment]
Closed as requested - this is a tinymce issue not one we can alter
