### ISSUE TITLE
[com_contact] list contacts in category - filter with pagination issue

### ISSUE THREAD

**Issue by appleandpear** [joomla/joomla-cms#9273]
#### Steps to reproduce the issue
On front-end when I display list of contacts in category (com_contact) i have e.g. 10 pages with contacts. When I use the filter search, it is working OK and pagination is showing "page 1 of 3". When I click on the second page, the filter search is disappearing and pagination is displaying "page 2 of 10" and I can see non-filtered contacts again.
To reproduce this issue you have to turn on the filter field in details of Menu Item under tab "List layouts": option "Filter field" should be selected on "Show".

#### Expected result
Keeping filter result on every page (pagination) as soon as I manually delete filter field.

#### Actual result
Bug.

#### System information (as much as possible)
Joomla 3.4.8
PHP 5.6.7

#### Additional comments
The same issue with archive articles was requested: https://github.com/joomla/joomla-cms/pull/6158

**Comment by flash1452** [comment]
I am getting a pagination only while displaying featured contacts,not in other contacts.

**Comment by appleandpear** [comment]
To reproduce this issue you have to turn on the filter field. In the backend you should create menu - navigate to:
Menus -> Main Menu (this is by default) -> New -> Choose menu item type: Contacts > list contacts in a Category.
Then choose sheet "List Layouts" and on the first dropdown option "Filter field" select "Show".
![zrzut ekranu 2016-03-03 o 21 01 54](https://cloud.githubusercontent.com/assets/17578382/13507519/312a72d6-e183-11e5-9a29-64b363974f8d.png)

![zrzut ekranu 2016-03-03 o 21 00 45](https://cloud.githubusercontent.com/assets/17578382/13507523/36f77470-e183-11e5-886e-b1054e7b6b1b.png)

**Comment by muhakh** [comment]
I tried the steps to reproduce the issue and I have the same issue.

**Comment by flash1452** [comment]
I have tested this and it works fine.

**Comment by NeerajTasol** [comment]
I have tested this issue and it works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9273">issues.joomla.org/joomla-cms/9273</a>.</sub>

**Comment by JamalTailored** [comment]
I have tested this issue in Joomla 3.4.8 in which you had tested. it's worknig fine

**Comment by brianteeman** [comment]
I can confirm that the issue still exists in Joomla 3.6rc2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9273">issues.joomla.org/joomla-cms/9273</a>.</sub>

**Comment by gunjanpatel** [comment]
Set to "closed" on behalf of @gunjanpatel by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9273">issues.joomla.org/joomla-cms/9273</a>

**Comment by gunjanpatel** [comment]
Closing as we have PR now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9273">issues.joomla.org/joomla-cms/9273</a>.</sub>

**Comment by brianteeman** [comment]
Reopening as the PR #9273 was not correct

**Comment by gunjanpatel** [comment]
Just to correct typo of above comment that PR is #9327 and that is not working so this one is reopened. :smile:

**Comment by brianteeman** [comment]
oops - thanks @gunjanpatel

**Comment by franz-wohlkoenig** [comment]
Issue exists also on Joomla! 3.7.0-staging.

**Comment by GeraintEdwards** [comment]
I am looking at this at JAB 2017

**Comment by franz-wohlkoenig** [comment]
closed as having PR #16482<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9273">issues.joomla.org/tracker/joomla-cms/9273</a>.</sub>
