### ISSUE TITLE
Media Manager Corrupts Images

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#9286]
#### Steps to reproduce the issue

Go to media manager
Click on choose image
click on upload very quickly.

#### Expected result

Image uploads

#### Actual result

If you wait for the file name to arrive give it a second then upload it will work.
If you click upload instantaneously the image will corrupt.

#### System information (as much as possible)

Setting	Value
 
Database Version	5.5.31-30.3-log
Database Collation	utf8_general_ci
PHP Version	5.5.32
Web Server	Apache/2.2.24 (Unix) mod_hive/5.0 mod_ssl/2.2.24 OpenSSL/1.0.0-fips mod_auth_passthrough/2.1 mod_bwlimited/1.4 mod_fastcgi/2.4.6 mod_fcgid/2.3.6
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

#### Additional comments

Hopefully not only me that can achieve this result.

**Comment by vdespa** [comment]
I am not sure I understood the replication steps. Would it be possible to attach a screenshot or two?

Thanks in advance!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9286">issues.joomla.org/joomla-cms/9286</a>.</sub>

**Comment by shubhamnba2009** [comment]
I have tried to replicate the steps on version 3.4.8 and latest staging version. But no such corruptness in image seems to occurs. Yeah, A screenshot or two will help probably if u can attach!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9286">issues.joomla.org/joomla-cms/9286</a>.</sub>

**Comment by brianteeman** [comment]
I cant replicate this - nor can I think of a way it is even possible<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9286">issues.joomla.org/joomla-cms/9286</a>.</sub>

**Comment by uglyeoin** [comment]
Yeah, my apologies, I can no longer replicate this issue.  It occurred several times yesterday and yesterday was not the first time.  I think it may be related to image size, although it does upload them correctly sometimes, but other times the bottom part of the image looks like static from an analogue TV with no TV channel.

**Comment by brianteeman** [comment]
Closing
