### ISSUE TITLE
any day api joomla3 increased and change!how we can be mastering api joomla3?

### ISSUE THREAD

**Issue by stackprogramer** [joomla/joomla-cms#9288]
#### Steps to reproduce the issue
hi,my friend ,joomla 3 is developed very fast.api joomla 3 is increased and changed fastly,
how we can obtain mastering api joomla 3 for developing new extension.
i know php,html,css,js,and some knowing about template joomla;

please guide me

**Comment by Bakual** [comment]
Please use our Google Group (https://groups.google.com/forum/#!forum/joomla-dev-general) or the forum (forum.joomla.org) for such requests.

**Comment by stackprogramer** [comment]
thanks
