### ISSUE TITLE
Joomla icon redirect in administrator view

### ISSUE THREAD

**Issue by Twincarb** [joomla/joomla-cms#9289]
#### Steps to reproduce the issue
in the host server I have a rule set-up to remove the trailing / from all webpages, I use Nginx and have the following rule
#remove trailing slash
rewrite ^/(.*)/$ /$1 permanent;

With the server set up as above with the rule enabled at server level
Click on icon-joomla top left when in the administrator view

#### Expected result
The expected page to be loaded is:
/administrator
/administrator/index.php

#### Actual result
The page errors out with a reported loop.
due to trying to go between administrator/ and administrator 

#### System information (as much as possible)
Joomla 3.4.8
Apache web server with Nginx in front

#### Additional comments
The only current way around this is to select System - Control Panel which is set up to load /administrator/index.php

**Comment by brianteeman** [comment]
Dont really think thats a bug that Joomla can deal with as it is specific to your non-standard hosting setup
It is normal on a web server that when you hit a folder then the default page as defined by the webserver will load<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9289">issues.joomla.org/joomla-cms/9289</a>.</sub>

**Comment by Twincarb** [comment]
The reason I raised it as a bug is it's the only admin url in the back end that doesn't display /index.php whereas System - Control panel is written with /index.php and both point to the same location so the behaviour appears inconsistent.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9289">issues.joomla.org/joomla-cms/9289</a>.</sub>

**Comment by SharkyKZ** [comment]
Your rewrite code is probably incorrect. Try this http://stackoverflow.com/a/9576121.

**Comment by infograf768** [comment]
I have to say we are not very consistent on this.
For Isis icon we use 
`href="' . $this->baseurl . '"`
this gives =>` /administrator`
For the status module we use
`href="' . JURI::base() . '"`
this gives => `/administrator/`

We could easily add index.php in both cases.

**Comment by brianteeman** [comment]
OK @infograf768 do you want to do a PR for that - good spot<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9289">issues.joomla.org/joomla-cms/9289</a>.</sub>

**Comment by infograf768** [comment]
OK, will do

**Comment by infograf768** [comment]
Here it is
https://github.com/joomla/joomla-cms/pull/9290

**Comment by infograf768** [comment]
O guess we can close this as there is a patch (still to be tested)

**Comment by brianteeman** [comment]
Thanks @infograf768 
Closed - please test #9290
