### ISSUE TITLE
mod_feed gives a fatal error when dates in RSS don't meet a RSS 2.0 Specification

### ISSUE THREAD

**Issue by EmilMassey** [joomla/joomla-cms#9291]
#### Steps to reproduce the issue
1. Add http://albertslund.lokalavisen.dk/section/senestenytrss as RSS feed URL
2. Visit the site where the module should be rendered

#### Expected result
No errors should be displayed to the website visitor - module should be rendered normally or not rendered at all. 

#### Actual result
Fatal error: DateTime::__construct(): Failed to parse time string (Tor, 03 Mar 2016 10:46:33) at position 0 (T): The timezone could not be found in the database

#### Additional comments
The problem here is that given feed is incorrect - the dates are inconsistent and some of them are in danish (day of week, e.g. Tor instead of Thu). According to RSS 2.0 at Harvard Law Specification, "All date-times in RSS conform to the Date and Time Specification of RFC 822, with the exception that the year may be expressed with two characters or four characters (four preferred).".

The parser should be prepared for a case when a RSS feed doesn't meet a specification.

**Comment by EmilMassey** [comment]
#9293 fixed for an incorrect date format, but it has to be tested if other non-standard RSS fields are not causing any problems.

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #9293 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9291">issues.joomla.org/joomla-cms/9291</a>.</sub>
