### ISSUE TITLE
ERROR: syntax error at or near ")" LINE 13 (PostgreSQL 9.5.1)

### ISSUE THREAD

**Issue by Dygear** [joomla/joomla-cms#9292]
#### Steps to reproduce the issue
git clone https://github.com/joomla/joomla-cms.git
git checkout 3.5-dev
Try the install process.

#### Expected result
Joomla Installs

#### Actual result
Once you get to the last page, and click install, this error comes up resulting in the install failing.

```ERROR: relation "#__redirect_links" does not existSQL=CREATE INDEX "#__redirect_links_idx_link_modifed" ON "#__redirect_links" ("modified_date")

ERROR: relation "#__redirect_links" does not existSQL=CREATE INDEX "#__redirect_links_idx_old_url" ON "#__redirect_links" ("old_url")

ERROR: syntax error at or near ")" LINE 13: ) ^SQL=CREATE TABLE "#__redirect_links" ( "id" serial NOT NULL, "old_url" varchar(2048) NOT NULL, "new_url" varchar(2048), "referer" varchar(2048) NOT NULL, "comment" varchar(255) NOT NULL, "hits" bigint DEFAULT 0 NOT NULL, "published" smallint NOT NULL, "created_date" timestamp without time zone DEFAULT '1970-01-01 00:00:00' NOT NULL, "modified_date" timestamp without time zone DEFAULT '1970-01-01 00:00:00' NOT NULL, "header" INTEGER DEFAULT 301 NOT NULL, PRIMARY KEY ("id"), )```


#### System information (as much as possible)
Ubuntu 14.04
nginx 1.9.12
PHP 7.0.3
PostgreSQL 9.5.1

#### Additional comments
Very much a SQL problem.

**Comment by richard67** [comment]
My fault, came with PR #9269 

I will see what I can find out, but help by anyone who has experience with PostgreSQL would be very welcome.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9292">issues.joomla.org/joomla-cms/9292</a>.</sub>

**Comment by alikon** [comment]
I will be able to help on this if needed

**Comment by richard67** [comment]
@alikon I have found the mistake alreaday, silly one. Will make a PR in a minute or two. But thanks for your offer, I come back to it if more problems.

**Comment by Dygear** [comment]
I'll follow along, I plan on using PostgreSQL in production at version 9.5.x.

**Comment by richard67** [comment]
@Dygear New PR for this issue is #9294 , please test.

@alikon If you wanna help and have time and PostgreSQL test db available: Please test #9294 , too.

**Comment by Dygear** [comment]
Just waiting for the CI tests to be done.

**Comment by richard67** [comment]
Done now

**Comment by Dygear** [comment]
Yep, it's good! Successfully installed using PostgreSQL 9.5.1 on PHP 7.0.3.

**Comment by richard67** [comment]
@Dygear Could you mark your test result ass success then at the issue tracker? Just go to [https://issues.joomla.org/tracker/joomla-cms/9294](https://issues.joomla.org/tracker/joomla-cms/9294l), click the "Test this" button at the to left area and then select the test result. Thanks.

**Comment by Dygear** [comment]
Done.
