### ISSUE TITLE
Background changing problems after 3.4.8 update in protostar template

### ISSUE THREAD

**Issue by pfeilmayer** [joomla/joomla-cms#9298]
Hello
Changing BG in protostar : 

body.site {
   border-top: 3px solid #0088cc;
   padding: 20px;
   background-color: #f4f6f7;
}

After the 3.4.8 update this does not work (protostar, joomla 3.4.8 ). 
I used a module to change the background color, called je animated background. I didn't notice that the background changed (into white with black coloured writing) until a few days ago. It was black (animated with the module - changed between a few shades of black) with white (or close to white) writing. Initially I disabled the module. No change. I uninstalled the module and tryied to edit template css. Still no dice. It seems I can't change the f background. And I think that this is a result of the last update to joomla to 3.4.8 .

Is there any way to restore previous version of the site ? OR more important question : Is there any way to change the bg and text color ? Even more important is to make that stupid module that changed the bg color to work again.
Perhaps the database was affected by the last joomla update because the file (template.css) doesn't do squat ?! I checked the DB in phpmyadmin and seems to be OK, but I'm far being an expert so it's just a presumption.

Thank you

P.S. Just to be sure, I made another fresh website from scratch, using Joomla 3.4.8. I ended up with the same problem. Can't change the BG with or without the module detailed above.

I uploaded 2 files : one, complete black bg is with Joomla 3.4.4 (I quess :) )and the black/white bg is with 3.4.8.

Please help me solve the problem as fast as possible. Thank you

**Comment by Demfier** [comment]
Hello pefeilmayer,
I wanted to ask you where exactly you were facing problems in changing the background?

I looked into your issue and started by 'Inspect Element' and changed set the 
background-color:#000 (Just for testing)

And the background color changed. So tell me if I'm missing something.Here's a screenshot of what I did and you can see that the whole background has changed to black.

![screen shot 2016-03-10 at 22 39 15](https://issues.joomla.org/uploads/1/1a8d93f1fc4522739090633e6ac53860.png)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9298">issues.joomla.org/joomla-cms/9298</a>.</sub>

**Comment by pfeilmayer** [comment]
Hello
I have modified one more time the template css .. and as you can see ... no joy.![screen shot 2016-03-11 at 09 27 00](https://issues.joomla.org/uploads/1/8b42e32ba97a2b0ec956969e6d2b0ea1.jpg)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9298">issues.joomla.org/joomla-cms/9298</a>.</sub>

**Comment by nikitadhiman** [comment]
May be I understood your problem. This happened with me too, when you try doing that by making code changes, these would be soon reverted if you update the template. The animated background module which you mentioned won't serve your purpose.
If you wish to retain the default template then prostar provides you the option to change the background very easily. (see the image) else the other option you have is to take the code of the template and modify it according to joomla template standard and then upload as a new template with different. Updating the template at later won't affect or revert your changes in this, you cann refer to this page in case you have any doubts about [template development](https://docs.joomla.org/Creating_a_basic_Joomla!_template)
![imageedit_1_4130467191](https://cloud.githubusercontent.com/assets/8037750/13730318/11ea06e2-e972-11e5-9dbe-689a22d799e2.png)

**Comment by pfeilmayer** [comment]
Hi
Thank you for your input.
Actually I allready tried that too.![screen shot 2016-03-13 at 13 02 27](https://issues.joomla.org/uploads/1/1d84d7c58e0c66aaf2bd95db65be60c6.jpg)
and still no joy :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9298">issues.joomla.org/joomla-cms/9298</a>.</sub>

**Comment by nikitadhiman** [comment]
@pfeilmayer , the only you can be joyful now is to take the template code and modify it according to your needs and then upload as new template. The best part of this process is that you can make any changes or introduce a new section in your template any time. This usually is not supported by many Joomla! templates available online

**Comment by brianteeman** [comment]
i am closing this at this time - using a module to change the css is completely the wrong way to do it.

As of Joomla 3.5 you can use a custom.css file for any css changes you want to make<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9298">issues.joomla.org/joomla-cms/9298</a>.</sub>
