### ISSUE TITLE
php warnings from error_log

### ISSUE THREAD

**Issue by aaleksanyants** [joomla/joomla-cms#9306]
#### Steps to reproduce the issue
unknown

#### Expected result
no PHP warnings should be registered

#### Actual result
PHP Warning:  Invalid argument supplied for foreach() in /home/gastro12/public_html/components/com_mailto/helpers/mailto.php on line 91
PHP Warning:  usort() expects parameter 1 to be array, boolean given in /home/gastro12/public_html/libraries/joomla/utilities/arrayhelper.php on line 418

#### System information (as much as possible)
Standard shared hosting

**Comment by brianteeman** [comment]
With the complete absence of any usable information this will be closed shortly.

At a minimum please state your system information and joomla version. (there is no such thing as standard shared hosting . 

But to be honest without knowing what you were doing to generate the php warning there is nothing that can be done

**Comment by aaleksanyants** [comment]
Hi Brian,

The problem is that I do NOT anything to get these errors, they are just recorded in error_log created by PHP, and there is no any additional information I could provide except of the warning messages I see there.

Regarding system, I have provided you with Joomla version (3.4.8) when submitting my report, and I don't think that providing you with Apache/PHP/MySQL version running on the server should help in any kind because the warnings are obviously generated because of missing params in called built-in functions.

On another side, if you suppose if what are the conditions that could cause these warnings and want to test them online, the address of the website is http://www.gastro.am

If there is anything else you need, please let me know.

**Comment by aaleksanyants** [comment]
Please also bear in mind that these warnings could be a result of hacking attempts and catching them will help you to increase the security. FYI, sites in Armenian or related to Armenia are always under attacks coming from Azerbaijan and Turkey...

**Comment by brianteeman** [comment]
They could also be caused by an extension that you have installed.

I am not trying to be awkward but from the information provided it is
impossible to help

On 5 March 2016 at 11:22, Andrey Aleksanyants <notifications@github.com>
wrote:

> Please also bear in mind that these warnings could be a result of hacking
> attempts and catching them will help you to increase the security. FYI,
> sites in Armenian or related to Armenia are always under attacks coming
> from Azerbaijan and Turkey...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9306#issuecomment-192623998>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by aaleksanyants** [comment]
> They could also be caused by an extension that you have installed.

Is there any way to track the calls made by third party extensions?

Just an idea: making the built-in error log generator more feature-loaded could help a lot in catching such attempts while its current implementation shows nothing except of hundreds of lines for "Invalid username or password". Why not to record params such as current URL and referring URL?

**Comment by mbabker** [comment]
You're referring to two different logging systems.  The log messages you posted come from PHP's error logging and that can be configured with full stack traces and whatnot.  Joomla's log system isn't designed as a full featured system (frankly it's all but garbage compared to platforms like Monolog), the design decision was that it's a glorified message container.  And truthfully in 99% of cases the page URL when the message is logged doesn't mean anything; if a logged error comes from a module the URL can be any page that module shows on for example.

**Comment by aaleksanyants** [comment]
I know that these logging systems are different, I just suggested to make the Joomla's logging system more reliable rather than filling log file with useless strings.

> if a logged error comes from a module the URL can be any page that module shows on for example

But this can be also caused by attempts of direct script calling and adding to it some unwanted  attributes, in such case recording of URLs will help in catching security holes...

**Comment by brianteeman** [comment]
Closing at this time as there is nothing that can be done with the information provided.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9306">issues.joomla.org/joomla-cms/9306</a>.</sub>
