### ISSUE TITLE
cant access my site after installing joomla on xamp local sever on windows 10 

### ISSUE THREAD

**Issue by kigh143** [joomla/joomla-cms#9308]
#### Steps to reproduce the issue
I downloaded the latest full package of joomla 
I then unzipped it and changed its name to joomla and placed it into the htdocs directory for xamp 
went through the installation part and it was successful when i tried to access the site it loaded a page with the login page as shown in the attachment. When you try the credentials it fails to  login.

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org
