### ISSUE TITLE
Redirects to administrator home page after logging in after session time-out

### ISSUE THREAD

**Issue by sanket0211** [joomla/joomla-cms#9309]
#### Steps to reproduce the issue
Go to any other tab under joomla administrator page.
Keep the Screen ideal for some time so that the session times - out. 
Now when you try to do anything you shall be redirected to login page.
After logging in, irrespective of which page you are on, you shall still be redirected to the home page.

**Comment by flash1452** [comment]
@sanket0211 This issue has been referenced before.See Issue #9016

**Comment by andrepereiradasilva** [comment]
duplicated issue of https://github.com/joomla/joomla-cms/issues/9016

I described better in a comment in that issues the problem.

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9309">issues.joomla.org/joomla-cms/9309</a>.</sub>
