### ISSUE TITLE
pdo:  Invalid datetime format

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#9310]
#### Steps to reproduce the issue

Install staging build

#### Expected result

Install joomla

#### Actual result

SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '0000-00-00 00:00:00' for column 'lastResetTime' at row 1

**Comment by brianteeman** [comment]
What were you doing to get that error message.

From what you have written I guessed it was during the install when using mysql(pdo) as the database driver.

I tested current staging and installed it with no sample data, blog sample data and testing sample data. All installed fine with no errorrs<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9310">issues.joomla.org/joomla-cms/9310</a>.</sub>

**Comment by kigh143** [comment]
hello, try using the sp staging. read about it on this link http://extensions.joomla.org/extensions/extension/access-a-security/site-security/sp-staging

**Comment by alikon** [comment]
unable to replicate the issue.
@kigh143 did you replicate the issue with that extension ?

**Comment by crayner** [comment]
It appears that 0000-00-00 00:00:00 is an invalid default for a datetime using PDO for MySQL.

**Comment by mbabker** [comment]
I'm going to suggest this is an issue with MySQL 5.7.  Installed from 838a459601e6007068ffb8e94b23764039e253b7 on my localhost (PHP 7.0.3, MySQL 5.6.22) and it worked fine.

**Comment by mbabker** [comment]
The other option, reading up on things, seems it may also have something to do with a combination of `NO_ZERO_DATE` and a combination of `STRICT_TRANS_TABLES` and `STRICT_ALL_TABLES` modes being enabled, and this wouldn't be MySQL version dependent (although 5.7 does use different defaults compared to 5.6).

**Comment by crayner** [comment]
I do not believe this is a MySQL 5.7 issue.  If so, it would fail using the mysqli driver, but it only fails on the PDO driver.  In testing the two drivers, are the settings of NO_ZERO_DATE, STRICT_TRANS_TABLES and STRICT_ALL_TABLES altered.  In testing, I only changed the setting of the database connection in Joomla,  Apache, PHP and MySQL are not change my me in the testing, but I do not discount the possibility that the DatabaseDriver alters these settings in code on Joomla 3.5

mbabker, are you using MySQLi or PDO as a database connection in Joomla for your test ?  For me, MySQLi works as expected, PDO fails.

Thanks, Craig

**Comment by mbabker** [comment]
The database driver doesn't alter the sql_mode at all.  And all my local tests were with PDO on MySQL 5.6.

I note the 5.7 difference since according to the documentation the default sql_mode for 5.7 is a setting that would prevent the 0000-00-00 00:00:00 date from working (if I've read it right).  I couldn't imagine why it would only affect the PDO driver and not the other MySQL based drivers too, but that's not something I've got a setup to dig into at the moment.

**Comment by mbabker** [comment]
Oh.  I got my answer.

The [mysql](https://github.com/joomla/joomla-cms/blob/3.5.0-rc/libraries/joomla/database/driver/mysql.php#L94) and [mysqli](https://github.com/joomla/joomla-cms/blob/3.5.0-rc/libraries/joomla/database/driver/mysqli.php#L186) drivers DO alter the sql_mode and they completely remove it.  The PDO driver does not.

**Comment by crayner** [comment]
and removing the NO_ZERO_DATE in my.ini  does correct the issue for MySQL 5.7.  Thanks Michael.  Good spotting..

Craig.

**Comment by crayner** [comment]
Yes clearing the sql_mode in the PDO driver fixes this issue.  

I altered JDatabaseDriverPdo in pdo.php at line 217.  Note that there is not break for pdomysql until after mysql.

`			case 'pdomysql':
				if (empty($this->options['driverOptions']))
					$this->options['driverOptions'] = array(PDO::MYSQL_ATTR_INIT_COMMAND => 'SET sql_mode=""');
				else
					$this->options['driverOptions'][PDO::MYSQL_ATTR_INIT_COMMAND] = 'SET sql_mode=""';
			case 'mysql':


hope this helps in the short term.  The reality is that driverOptions may be needed in the configuration.

Regards,

Craig

**Comment by 810** [comment]
yes removing all sql modes fixed the issue

**Comment by brianteeman** [comment]
Thank you for creating this but it would appear that this has been resolved elsewhere in the code base. If this is not correct then this can be re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9310">issues.joomla.org/joomla-cms/9310</a>.</sub>
