### ISSUE TITLE
Question: AMP-html (fresh news source)?!

### ISSUE THREAD

**Issue by alexonbalangue** [joomla/joomla-cms#9314]
hello
#### Additional comments

Next version you'll adding to do or simple all override? (its begening long override all files).

ps: https://www.ampproject.org/docs/get_started/about-amp.html 

regards thnks advances

**Comment by brianteeman** [comment]
https://groups.google.com/forum/#!topic/joomla-dev-cms/ynm0AabEbDg%5B101-125%5D<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9314">issues.joomla.org/joomla-cms/9314</a>.</sub>
