### ISSUE TITLE
Error Unable to find install package

### ISSUE THREAD

**Issue by kigh143** [joomla/joomla-cms#9318]
#### Steps to reproduce the issue
created a plugin to redirect a user to the page the choose in he settings options. 
made three pages , index.html to redirect user from the root directory, joomlaLoginPlugin.php and joomlaLoginPlugin.xml
when I tried to install it, i get an warning of "Warning
JInstaller: :Install: Can't find Joomla XML setup file."

**Comment by brianteeman** [comment]
Please use the forum (http://forum.joomla.org) or the mailing list for support https://groups.google.com/forum/m/#!forum/joomla-dev-general)

**Comment by kigh143** [comment]
Thanks Brian<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9318">issues.joomla.org/joomla-cms/9318</a>.</sub>

**Comment by kigh143** [comment]
I have actually found the problem in my xml file. The error is due to not closing the field tag. 

```php
<config>
	<fields name="params">
		<fieldset name="bassic" label="Login settings">
			<field name="menu_id" type="menuitem" label="select Redirect page"/> // this line was not closed 
		</fieldset>
	</fields>
</config>

```
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9318">issues.joomla.org/joomla-cms/9318</a>.</sub>
