### ISSUE TITLE
The 'Back to top' link at the bottom of the page redirects to the home page instead of scrolling up.

### ISSUE THREAD

**Issue by GABBAR1947** [joomla/joomla-cms#9321]
**Steps to reproduce the issue**

Try editing any module, let it be the Main Menu module. Enter various parameters in text boxes.Now click on 'Back to top' link at the bottom.

**Expected result**

The click on the link should result in the page scrolling upwards without the loss of any parameters.

**Actual result**

Instead the user is directed to the home page and thus, the parameters entered are also lost.

**Comment by brianteeman** [comment]
Are you talking about editing modules on the front end using the default
protostar template?

On 6 March 2016 at 21:19, Shubham Rathore <notifications@github.com> wrote:

> *
> *Steps to reproduce the issue **
> Try editing any module, let it be the Main Menu module. Enter various
> parameters in text boxes.Now click on 'Back to top' link at the bottom.
>
> *Expected result*
> The click on the link should result in the page scrolling upwards without
> the loss of any parameters.
>
> *
> *Actual result **
> Instead the user is directed to the home page and thus, the parameters
> entered are also lost.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9321>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by GABBAR1947** [comment]
Oh Yes.

**Comment by brianteeman** [comment]
Please see #9322 for a PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9321">issues.joomla.org/joomla-cms/9321</a>.</sub>
