### ISSUE TITLE
TinyMCE plugin stripping extended valid elements parameter text needed to permit schema.org markup

### ISSUE THREAD

**Issue by thndrbck** [joomla/joomla-cms#9323]
#### Steps to reproduce the issue

To set tinymce to accept schema.org markup, the Extended Valid Elements parameter needs to have the following value:

span[itemtype|itemscope|itemprop|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],div[itemtype|itemscope|itemprop|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],p[itemtype|itemscope|itemprop|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h1[itemtype|itemscope|itemprop|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h2[itemtype|itemscope|itemprop|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h3[itemtype|itemscope|itemprop|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h4[itemtype|itemscope|itemprop|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h5[itemtype|itemscope|itemprop|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h6[itemtype|itemscope|itemprop|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],a[itemprop|accesskey|charset|class|coords|dir<ltr?rtl|href|hreflang|id|lang|name|onblur|onclick|ondblclick|onfocus|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|rel|rev|shape<circle?default?poly?rect|style|tabindex|title|target|type],
#### Expected result

It is expected to have exactly that above in the parameter field after saving.
#### Actual result

span[itemtype|itemscope|itemprop|alignr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],div[itemtype|itemscope|itemprop|align,p[itemtype|itemscope|itemprop|alignltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h1[itemtype|itemscope|itemprop|alignh2[itemtype|itemscope|itemprop|alignltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h3[itemtype|itemscope|itemprop|alignh4[itemtype|itemscope|itemprop|alignltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h5[itemtype|itemscope|itemprop|alignh6[itemtype|itemscope|itemprop|alignltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],a[itemprop|accesskey|charset|class|coords|dirault?poly?rect|style|tabindex|title|target|type],
#### Additional comments

It strips out starting with the <div> definintion with this string: <center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title]

This string in the <p> definition: <center?justify?left?right|class|dir<

all this string in each of the <h> definitions: <center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],

and this string from the <a> definition: <ltr?rtl|href|hreflang|id|lang|name|onblur|onclick|ondblclick|onfocus|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|rel|rev|shape<circle?def

If this can be corrected, The tinymce plugin will be able to handle schema.org markup.

As it is now, using the above value for the extended valid elements parameter I can get some of the markup through for the span tag, but everything else fails

<div>
<div><strong>Sample Websites</strong></div>
<div><span itemprop="streetAddress">999 Street Ave.</span><br /> <span itemprop="addressLocality">Pleasantville </span><br /> <span itemprop="addressRegion">NY</span><br /> <span itemprop="postalCode">12345</span><br /> <span itemprop="addressCountry">USA</span></div>
</div>

**Comment by citizencontact** [comment]
Good info. Thanks. However, I would hope that the other attributes, "itemid" and "itemref" are also included.

span[itemtype|itemscope|itemprop|itemid|itemref|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],div[itemtype|itemscope|itemprop|itemid|itemref|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],p[itemtype|itemscope|itemprop|itemid|itemref|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h1[itemtype|itemscope|itemprop|itemid|itemref|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h2[itemtype|itemscope|itemprop|itemid|itemref|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h3[itemtype|itemscope|itemprop|itemid|itemref|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h4[itemtype|itemscope|itemprop|itemid|itemref|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h5[itemtype|itemscope|itemprop|itemid|itemref|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],h6[itemtype|itemscope|itemprop|itemid|itemref|align<center?justify?left?right|class|dir<ltr?rtl|id|lang|onclick|ondblclick|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|style|title],a[itemprop|itemid|itemref|accesskey|charset|class|coords|dir<ltr?rtl|href|hreflang|id|lang|name|onblur|onclick|ondblclick|onfocus|onkeydown|onkeypress|onkeyup|onmousedown|onmousemove|onmouseout|onmouseover|onmouseup|rel|rev|shape<circle?default?poly?rect|style|tabindex|title|target|type],

**Comment by franz-wohlkoenig** [comment]
Is this Issue solved by #12784?

**Comment by franz-wohlkoenig** [comment]
@thndrbck can you please test if this Issue still exist?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9323">issues.joomla.org/tracker/joomla-cms/9323</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
closed as no Reply. @thndrbck feel free to reopen for further Discussions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9323">issues.joomla.org/tracker/joomla-cms/9323</a>.</sub>
