### ISSUE TITLE
Accepting date before today's date in created on field while creating an article.

### ISSUE THREAD

**Issue by sanket0211** [joomla/joomla-cms#9324]
#### Steps to reproduce the issue
1. Login as an administrator. 
2. Create an article.
3. in the right side try putting date before today's date in created date field.

#### Expected result
1. you should be getting an error.

#### Actual result
2. the article gets successfully saved.

#### Additional comments
1. I can take up the issue if someone rechecks it, whether this issue actually persists.

**Comment by alikon** [comment]
i think is normal behaviuor not an issue

**Comment by sanket0211** [comment]
I think created on field should not be asked. As we save the article, it can automatically fetch the present date and time mention attach it with the article.

**Comment by Bakual** [comment]
It will automatically fetch the date if you leave it empty.
If you want to set another date, be it in past or present, you can fill it out.

Closing as expected behavior.
