### ISSUE TITLE
Joomla! 3.5.0-beta5:  Menu Item Type "K2 » Item listings » Categories" > Only Tabs "Details" and "Options" visible

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#9329]
#### Steps to reproduce the issue
Open in Joomla! 3.5.0-beta5 a  Menu Item Type "K2 » Item listings » Categories"
#### Expected result
Visible Tabs: Details, Options, Link Type, Page Display, Metadata, Module Assignment
#### Actual result
Visible Tabs: Details, Options
#### System information (as much as possible)
PHP 5.6.13
MySQLi 5.5.47-0+deb7u1
K2 v2.6.9
#### Additional comments
Joomla! 3.5.0-beta5:
![joomla 3 5 0-beta4](https://cloud.githubusercontent.com/assets/8235763/13572690/ebb346be-e47b-11e5-96eb-dc5bf5cc067a.JPG)
Joomla! 3.4.8
![joomla 3 4 8](https://cloud.githubusercontent.com/assets/8235763/13572694/f591cb6a-e47b-11e5-9268-55ceb25715d9.JPG)
Found this Issue only in this Menu Item Type. Same Issue after clear Cache, and LogOut / LogIn.

**Comment by xtech86** [comment]
Tested and confirmed it is not working.

**Comment by xtech86** [comment]
I have looked into this further and it appears to be caused by K2 using moo tools. Javascript error is reported on page. See:

```
				window.addEvent('domready', function(){
					if($('request-options')) {
						$$('.panel')[0].setStyle('display', 'none');
					}
					setTask();
				});
```

K2 need to update for jQuery usage.

**Comment by franz-wohlkoenig** [comment]
Thanks @xtech86 for looking in this. So its not an Joomla-Error i close this Issue.
