### ISSUE TITLE
Problem on update 2.5.28 -> 3.5.0 beta 5 (with joomla update component)

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#9331]
#### Steps to reproduce the issue

Upgrade from 2.5.28 (clean install with sample data) to 3.5.0 beta 5 using custom URL: `https://downloads.joomla.org/updates/cms/test/list_test_25to3x.xml`.

#### Expected result

Joomla upgraded without issues.

#### Actual result

> You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '--ALTER TABLE `#__redirect_links` MODIFY `new_url` varchar(255)' at line 5 SQL=-- -- The following statement has to be disabled because it conflicts with -- a later change added with Joomla! 3.5.0 for long URLs in this table -- --ALTER TABLE `#__redirect_links` MODIFY `new_url` varchar(255);

And joomla backend gets broken. 500 error on several backend pages after update.

#### System information (as much as possible)

Database Version: 5.5.5-10.0.24-MariaDB
PHP Version: 5.6.18

#### Additional comments

I think this only happens when upgrading from 3.3.6 or lower versions to 3.5.0 beta 4/5.

Maybe problem with sql comment (missing space after `--`)?
- https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/mysql/3.4.0-2014-09-16.sql#L6

- https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/postgresql/3.4.0-2014-09-16.sql#L6

- https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/sql/updates/sqlazure/3.4.0-2014-09-16.sql#L6

Can this also be the cause of the 500 error observed before on upgrade from lower versions? 

@richard67 can you check this one?

**Comment by richard67** [comment]
Yes, am just working on a PR to solve that. Of course I also could remove all comments from that sql update script, and hope we have no others with comments now and in future, but this would be the quck but not good solution.

**Comment by richard67** [comment]
@andrepereiradasilva Can you test if my new PR #9332 solves your problem?

**Comment by andrepereiradasilva** [comment]
mantainers you can close this as we have a PR

**Comment by richard67** [comment]
Yes. PR #9332 solves this problem here (not only for 2.5 but also for others, see comments there).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9331">issues.joomla.org/joomla-cms/9331</a>.</sub>
