### ISSUE TITLE
Class 'JEventDispatcher' not found

### ISSUE THREAD

**Issue by zyzak** [joomla/joomla-cms#9334]
hello

I got problems with Joomla

http://www.pcp.org.pl/

Fatal error: Class 'JEventDispatcher' not found in /home/asumera/ftp/libraries/joomla/application/base.php on line 127

whats wrong?

**Comment by zyzak** [comment]
Joomla 3.4........ PHP 5.3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9334">issues.joomla.org/joomla-cms/9334</a>.</sub>

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9334">issues.joomla.org/joomla-cms/9334</a>.</sub>
