### ISSUE TITLE
RFC - Simple, Flexible Blank Admin template

### ISSUE THREAD

**Issue by parthlawate** [joomla/joomla-cms#9337]
Customising the current Joomla admin template to specific use case scenarios is a little hard now. If we have a blank, easy to customise template with plenty of module positions it will add a lot of flexibility to decide how to present the backend. 

We plan to do this anyways for some client work, our plan is to submit a PR for the same by first creating a general use blank template and then proceeding with our client specific stuff. Any ideas, suggestions around this would be great to help us make it more powerful and suitable for many use cases. Any collaboration on this is of course welcome :) 

### Basic Features
- Plenty of Module positions including special Dashboard module positions
- Responsive
- Easy to white label - Custom Logo Upload , Custom FavIcon, 
### Good to haves

- Bootstrap 3 support and overrides for core extensions (can later be merged as default layouts)
- Color Palette chooser
- Split Menu support
- Drag and drop positioning and easy addition to add Dashboard modules 

### Related Addons/Components/Modules 
< These will need to be separate RFCs ideally>
- Admin Menu Manager - RFC proposed by @brianteeman about the Joomla Admin menu manager. 
- Dashboard Modules to show vital statistics
- Frequently Used/ Recently Used Pages module to aid navigation
- Spotlight search module for admin
- Admin Notifications
- Admin Activity Stream

**Comment by ronnikc** [comment]
We did earlier provide a Mockup as part of a process to work towards a new and more user friendly (and usercentric) administrator template.

The Mockup is available at: http://backendtemp.mathilde.intern.redweb.dk/

**Comment by brianteeman** [comment]
I suggest you speak to the UI/UX team as they are working on something<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9337">issues.joomla.org/joomla-cms/9337</a>.</sub>

**Comment by uglyeoin** [comment]
I would like it if the template was WCAG https://www.w3.org/TR/WCAG20/ compatible.  I think this would be a HUGE coup for the Joomla! project.  I was considering trying to do this myself.

**Comment by cpfeifer** [comment]
Hi everyone, I’m from the JUX team and I was directed to this conversation by many people today. We are just beginning the process of conceptualizing a new admin template. We would like create something that provides better UX as soon as version 3.6 and we want it to transition towards J4 concepts at the same time. Maintaining backward compatibility in 3.x releases is mandatory, and the J4 architecture will be more flexible, but our goal is to make admin improvements sooner than later because we know this is the number #1 concern in the community based on our research. We hear you, and we want to make it better for everyone.

We are just getting started and we want to see any ideas or concepts the community has. We’ll also be gathering community feedback in the very near future. If you’re interested in contributing to the JUX and assisting in this process, please fill out the JUX Team Application or send me a message. I’m happy to answer questions and provide more information, thanks for being involved. http://goo.gl/forms/CrUfP5Gtb0

**Comment by ChocLawrence** [comment]
Hi everyone,would this functionality be intergrateed into previous versions as well.It is a very cool idea and im interested in it

**Comment by parthlawate** [comment]
Thanks for the feedback so far ! 

1. @brianteeman have started coordinating via @cpfeifer with the JUX team
2. @ronnikc thanks for the mockup link. Will definitely consider those. However as a start, right now we are looking at creating a flexible with the required module positions etc and then actually Build a version that has modules and plugins that are centric to Admins of the typical 'Joomla as a CMS' use case. However we want it to be flexible enough to become say - an Ecommerce Dashboard/ Admin template or say a CRM Dashboard/Admin template by just changing the needed menus and modules 
3. @uglyeoin we would love help in this aspect (infact in all other aspects as well !) WCAG is something @pbwebdev (Pete Bui) had written about was working on if i'm not wrong ?  I'd read this article he'd written some time back http://magazine.joomla.org/issues/issue-november-2015/item/2894-accessibility-testing-the-colours-of-your-website
Do let me know if you can help . I'll submit some code as soon as we have something baseline usable. 
4. @ChocLawrence right now I'm focussing on the Joomla 3x series for this. 
5. @cpfeifer would be great if you can monitor this thread and give any inputs you can from the JUX team !

**Comment by dgt41** [comment]
@parthlawate I have to say good luck with this! I was trying to modernise (b/c) the isis for couple years now but too many people objected:
2014: https://github.com/joomla/joomla-cms/pull/4280
2015: https://github.com/joomla/joomla-cms/pull/7610

By the way bootstrap 3 CAN NOT be done in 3.x! 
As I said before good luck...

**Comment by parthlawate** [comment]
@dgt41 thanks for the inputs ! would be cool if you can help with this. I need this for a few projects so going to build it anyways. Just an attempt to see if we can get this in the core as an option. Current template can stay. not trying to replace that.  This is as the title says "Simple, Flexible Blank Admin template" that can be easily tweaked for various use cases. 

Our company sustainable open source policy needs that in every project we do we have to find a way of contributing to opensource. If it gets in it will be good for everyone. We are going to code it anyways so might as well do it in a way that considers most use cases and needs. 

Thanks for the inputs on 2014: #4280 , 2015: #7610 - We'll try and consider comments in them. 

Regarding BS3 -- that is a good to have. and can be made available as a configurable option. On the luck part thanks :) We are going to need it !

**Comment by uglyeoin** [comment]
@parthlawate thanks for the offer, I'm happy to help if I can.  I'm more of a front end coder than back end but I am quite well versed in what you should and shouldn't do to make a site accessible as I have created sites for disability charities in the past.

**Comment by cpfeifer** [comment]
@parthlawate - I'm happy to coordinate this, we're already coordinating with the 3.6 release team and obviously we're on the same page as marketing :) 

As I mentioned, any 3.x release needs to maintain backwards compatibility. Changing the core bootstrap implementation is not an option until J4, which will be much more flexible and will hopefully move us past this issue once and for all. For now, it's a big challenge we have to work around.

Again, if anyone wants to help please contact me. The JUX is actively seeking contributors for this specific project.

**Comment by brianpeat** [comment]
As a part of this new template, I'd love to see you add nested items to the list view in the menu manager. I created a mock up a few years back, but I have no idea if it's ever worked its way into the proper chains to get implemented. Here are the rough mock ups:

https://drive.google.com/file/d/0B21e4EKivj0gTm9FdVI4aUF2UEE/view
https://drive.google.com/file/d/0B21e4EKivj0gUDNQN1AwM0Y0eWs/view

**Comment by cpfeifer** [comment]
Thanks Brian. Do you have files for this that you can send me privately? We've got a few other admin templates that have a similar approach and style to this and we're building a sandbox to review and test the codes to see what will work best.

**Comment by brianpeat** [comment]
It was just a mock up in Adobe fireworks showing the basic idea. Not sure you'd gain anything from having the source files. Sorry :(

**Comment by cpfeifer** [comment]
It's all good, just curious :) It looks very similar to a custom admin template and some other ideas I've received so I'm getting the impression something along these lines could work. I'll let you know when I've got the sandbox up and you can check it out. Thanks again.

**Comment by brianpeat** [comment]
I posted the images at Parth's request, but I don't care WHO implements it. When you're dealing with a beefy mega menu, managing all those levels without being able to collapse it is really a pain. :)

**Comment by cpfeifer** [comment]
We're just getting started with the 3.6 process, collecting ideas and figuring out what will be possible within the timeframe. Nothing has been decided yet as far as I know.

**Comment by brianteeman** [comment]
Closed - no need for it to stay open if people are working on it. When you have something to show create a new PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9337">issues.joomla.org/joomla-cms/9337</a>.</sub>

**Comment by brianteeman** [comment]
Closed - no need for it to stay open if people are working on it. When you have something to show create a new PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9337">issues.joomla.org/joomla-cms/9337</a>.</sub>

**Comment by parthlawate** [comment]
Ok.. I thought RFC's were requests for comments where we can maintain it to keep getting feedback. We should have something to show in around a month. Will post updates then

**Comment by cpfeifer** [comment]
@brianteeman Thanks Brian, I agree.

With the short timeline for 3.6, a new admin template will most likely be a 3.7 or beyond release, but we have already started the groundwork. We need all the help we can get, it's a massive undertaking to create an addition like this to a 3.x release. We do have a team in Glip for this specific project, anyone who wants to join or contribute can contact me directly for more information. Thanks to everyone for your comments and contributions so far.

**Comment by parthlawate** [comment]
@cpfeifer Please add me to the glip team. We are very close now to showing a working version

**Comment by cpfeifer** [comment]
@parthlawate - do you have a repository, or can you make one? We don't have much going on with this in glip and I'd prefer to have working projects on Github as much as possible.

This effort got put on hold for a number of reasons. It is on the development roadmap, which was recently updated, slated for v3.10 release. All the time lines are still tbd, but a new admin template listed is planned for a J3 release. Just fyi. https://docs.joomla.org/Joomla_CMS_Development_Roadmap

**Comment by parthlawate** [comment]
Will share the repo once we clean it up a little bit..
