### ISSUE TITLE
Double Source code icon in editor TinyMCE

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#9339]
#### Steps to reproduce the issue
In Plugins: Editor - TinyMCE set the parameter Functionality to "Extended", then edit an article.

#### Expected result
One icon <> for Source code.

#### Actual result
Two icons <> for Source code (view image)

![screen shot 2016-03-08 at 04 48 00](https://issues.joomla.org/uploads/1/526b84a4ad4d992df9a1bd476bbc3f47.png)

**Comment by brianteeman** [comment]
Pull request coming

**Comment by brianteeman** [comment]
Please test #9341<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9339">issues.joomla.org/joomla-cms/9339</a>.</sub>
