### ISSUE TITLE
Info displayed in Languages: Installed (Site) are taken from admin language xml

### ISSUE THREAD

**Issue by stellainformatica** [joomla/joomla-cms#9342]
#### Steps to reproduce the issue
To see the issue open the file administrator/language/en-GB/en-GB.xml and for exemple modify the name in this way
<name>English (en-GB) admin</name>
Then go to Extensions > languages > Installed and look the infos about Site language.

#### Expected result
The info displayed are the data present in language/en-GB/en-GB.xml

#### Actual result
The info displayed are the data present in administrator/language/en-GB/en-GB.xml

![screen shot 2016-03-08 at 05 17 22](https://issues.joomla.org/uploads/1/5195e9300874229d764ad33fc06321a0.png)

**Comment by infograf768** [comment]
I confirm the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9342">issues.joomla.org/joomla-cms/9342</a>.</sub>

**Comment by brianteeman** [comment]
Is this really an issue? 

The language is "English (en-GB)" There is no such language as "English (en-GB) admin" so why would you write admin in there<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9342">issues.joomla.org/joomla-cms/9342</a>.</sub>

**Comment by stellainformatica** [comment]
It was just to see the issue, after the test you can put "English (en-GB)" as it was.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9342">issues.joomla.org/joomla-cms/9342</a>.</sub>

**Comment by infograf768** [comment]
@brianteeman  

we have an issue in the sense that only admin xml metadata is used.
For example, if you install a pack which creation date is different between site and admin (for any reason), then it is the admin infos which are going to be displayed in both cases.
It is not a big deal but should be corrected.

@andrepereiradasilva 
Can you have a look?

**Comment by brianteeman** [comment]
Thanks @infograf768 that use case with the dates makes sense

On 8 March 2016 at 11:37, infograf768 <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman>
>
> we have an issue in the sense that only admin xml metadata is used.
> For example, if you install a pack which creation date is different
> between site and admin (for any reason), then it is the admin infos which
> are going to be displayed in both cases.
> It is not a big deal but should be corrected.
>
> @andrepereiradasilva <https://github.com/andrepereiradasilva>
> Can you have a look?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9342#issuecomment-193742797>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
please test https://github.com/joomla/joomla-cms/pull/9344

**Comment by brianteeman** [comment]
Closed as we have a PR for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9342">issues.joomla.org/joomla-cms/9342</a>.</sub>
