### ISSUE TITLE
Edit Articles via Category List redirected to Start Page without opening Editor Modus (doesnt matter which Editor i use)

### ISSUE THREAD

**Issue by staniii1** [joomla/joomla-cms#9343]
#### Steps to reproduce the issue

Hi i got a Problem with **Editing my Articles**.
This **only happens** when an User of the Usergroup Author (or lower permission) **forgets to Check-Out** while Editing (e.g. "close Browser without Log-Out").
If he's actually Checking out this doesnt happen.

So on my Intranet Page are **2 existing Ways to Edit an Article**.
## # 1. Way (error)

![Edit Button](https://issues.joomla.org/uploads/1/9894cf6d672373f006057e3200f6d3a6.png)
Click on the Category in the MainMenu which opens a **Category List**. 
This Category List shows all my Articles within one Category, and next to them is an **Edit Button** for every Article in that list.
If i click  on the **Edit Button i get redirected to the Starting Site** **\- the Editor Mode doesnt even open.**
Additionaly the **Article gets Checked-in** (even if i just Checked-Out in the Backend)
Further Info: If i wait several hours/days between Checking-Out in the Backend and trying to Edit in the Front-End  it works - most of the time. 
Anways this is the Link the Edit Button calls:
http://_/_/index.php/de-de/mm-system/hse-managment?task=article.edit&a_id=65&return=aHR0cDovL2ludHJhbmV0LmV0aW1leC10Yy5jb20vaW50cmFuZXQvaW5kZXgucGhwL2RlLWRlL21tLXN5c3RlbS9oc2UtbWFuYWdtZW50
## 2. Way ( working)

![screen shot 2016-03-08 at 05 28 38](https://issues.joomla.org/uploads/1/267511485eb91594248f62dcee922ffe.png)
Open the Article **directly in the Menu (so no Category List involved)**. 
There is a gear icon which allows me to edit aswell. If i click that edit button **i get a diffrent
Link:**
http://_/_/index.php/de-de/mm-system/hse-managment/arbeits-u-gesundheitsschutzmanagment?task=article.edit&a_id=65&return=aHR0cDovL2ludHJhbmV0LmV0aW1leC10Yy5jb20vaW50cmFuZXQvaW5kZXgucGhwL2RlLWRlL21tLXN5c3RlbS9oc2UtbWFuYWdtZW50L2FyYmVpdHMtdS1nZXN1bmRoZWl0c3NjaHV0em1hbmFnbWVudA==

This Way it works without any problems.

But i have 800 Users and about 20 Editors daily.
Most of them use Way 1, since its the more common thing to do and yeah as expected some of them forget to check-out, daily...
So this means a lot of our Intranet Content is not able to get edited for days..
I would really appreciate if u could help me with that dilema.

**EDIT:**
Just checked my **php_error_log from Appache** - this **might be relevant**

[08-Mar-2016 11:48:44 Europe/Berlin] PHP Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\intranet\administrator\components\com_content\models\article.php on line 555

[08-Mar-2016 11:50:40 Europe/Berlin] PHP Notice: Undefined index: associations in C:\xampp\htdocs\intranet\administrator\components\com_content\models\article.php on line 553
#### Expected result

Both Ways should be possible OR
Disable Way 1.
#### System information (as much as possible)

Windows Server 2008 R2
XAMPP (Apache, MySQL)
Virtual Server VMware
Joomla 3.4.3

**Comment by staniii1** [comment]
//php_error_log from Appache - this might be relevant

[08-Mar-2016 11:48:44 Europe/Berlin] PHP Warning:  Invalid argument supplied for foreach() in C:\xampp\htdocs\intranet\administrator\components\com_content\models\article.php on line 555

[08-Mar-2016 11:50:40 Europe/Berlin] PHP Notice:  Undefined index: associations in C:\xampp\htdocs\intranet\administrator\components\com_content\models\article.php on line 553
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9343">issues.joomla.org/joomla-cms/9343</a>.</sub>

**Comment by ChocLawrence** [comment]
Hello,
Thanks for bringing the issue to notice.Im trying to look into the innner workings of Joomla.Im new to this community.Will be glad to help.ill appreciate if im enlightened on this issue.It is a very critical issue.Looking into it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9343">issues.joomla.org/joomla-cms/9343</a>.</sub>

**Comment by brianteeman** [comment]
@staniii are you still having this problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9343">issues.joomla.org/joomla-cms/9343</a>.</sub>

**Comment by staniii1** [comment]
Yeah i still have the Problem, sometimes.
In some cases you can fix it if the User that locked the Article Re-Logs.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9343">issues.joomla.org/joomla-cms/9343</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
- Article by Member of User Group "Author" which has closed his Browserwindow got as Superuser: `Checked out` in Menu "Category List".  
- After `Check-in` in Backend Article is editable in Frontend.

Looks like Issue resolved. Tested on 3.7-staging.

**Comment by franz-wohlkoenig** [comment]
@staniii1 can you please test if this Issue is solved in 3.7?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9343">issues.joomla.org/tracker/joomla-cms/9343</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this issue at this time as it now appears to be resolved. It can always be reopened if that is not the case.
