### ISSUE TITLE
An error has occurred must match character set with 2 factor authentication

### ISSUE THREAD

**Issue by uglyeoin** [joomla/joomla-cms#9349]
#### Steps to reproduce the issue
2 Factor Authentication must be enabled.  Every now and then it goes out of sync (or something goes wrong).  At that point if you enter in a two factor authentication you get the error message:

An error has occurred must match character set with 2 factor authentication

To log in you must remove any characters from 2FA and just use your user/password.

You then need to set up 2FA again.  Alternately you can delete the database entry and log in without that error message.

I can show you this issue on a live client site but it is hard to deliberately replicate.

#### Expected result

Log in.  Or an sensible error message that helps me to understand the issue.  Perhaps this is a sensible error message but I don't know what it means.  If it means something to someone can you assist me as it might help me to avoid the issue happening in the future.

#### Actual result

It looks like it logs in, but nothing is available except this error message:  An error has occurred must match character set with 2 factor authentication.  You then have to click "back to login" or some similar button.

#### System information (as much as possible)

This is a long standing issue that I have had over multiple websites.  I have spoken to my host in great length about it and they have tried to assist in many ways, I can provide that information if it is helpful.  In any event I find the error message unhelpful.

**Comment by wilsonge** [comment]
This sounds like this issue https://github.com/joomla/joomla-cms/issues/4126 which was basically related to when the secret key changes stuff blows up. Would this make sense?

**Comment by uglyeoin** [comment]
@wilsonge it is possible that I backed up on a staging server and transferred across.  I wouldn't say it's 100% though.  Does the secret key change when you do a Joomla! update?

**Comment by brianteeman** [comment]
no

On 9 March 2016 at 14:47, uglyeoin <notifications@github.com> wrote:

> @wilsonge <https://github.com/wilsonge> it is possible that I backed up
> on a staging server and transferred across. I wouldn't say it's 100%
> though. Does the secret key change when you do a Joomla! update?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9349#issuecomment-194326614>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by uglyeoin** [comment]
@wilsonge @brianteeman in which case let's assume it is the same issue until I can say for sure that it is not.

**Comment by riker1701d** [comment]
I experienced this error after setting up a new instance.
No Akeeba backup involved. No backup/restore of any sort was involved.
The site just stopped allowing 2FA access.
It was just updated to Version 3.6.3 a couple of days ago. Could that have affected it?
I regained access by renaming the twofactorauth directory then disabling and re-enabling the plugin  "Two Factor Authentication - Google Authenticator". I re-setup the 2FA for the user and it worked again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9349">issues.joomla.org/tracker/joomla-cms/9349</a>.</sub>

**Comment by wilsonge** [comment]
That's this issue https://github.com/joomla/joomla-cms/issues/12487 

Please test this patch https://github.com/joomla/joomla-cms/pull/12497
