### ISSUE TITLE
Module Popular Tags is not working properly

### ISSUE THREAD

**Issue by vitaly80** [joomla/joomla-cms#9351]
#### Steps to reproduce the issue
Create some materials with tags. Create module and sort by title.

#### Expected result

Most Pupular Articles, limit by Maximum and then sort by title

#### Actual result

Sort by title, limit by Maximum.

#### Additional comments

Truly the most popular articles are not subject to sampling.

**Comment by brianteeman** [comment]
The title that is displayed is the title of the tag not the article

On 9 March 2016 at 16:01, vitaly80 <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Create some materials with tags. Create module and sort by title.
> Expected result
>
> Most Pupular Articles, limit by Maximum and then sort by title
> Actual result
>
> Sort by title, limit by Maximum.
> System information (as much as possible) Additional comments
>
> Truly the most popular articles are not subject to sampling.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9351>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
As far as I can see this is working exactly as it is designed to work
The module displays a list of the most popular tags and sorts them depending on the settings in the module<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9351">issues.joomla.org/joomla-cms/9351</a>.</sub>

**Comment by vitaly80** [comment]
example:

tag | count
fauna | 5
flora | 4
nature | 2
oceans | 30


In module we want to see 3 most popular item, sorting by title.

Expecting:
fauna, flora, oceans ("slice" 3 most popular, and then sort by the title)

Actual Result:

fauna, flora, nature (sort by title, and then slice 3). MOST POPULAR TAG ON THE SITE "OCEANS" NOT SHOWING!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9351">issues.joomla.org/joomla-cms/9351</a>.</sub>

**Comment by brianteeman** [comment]
I see what you mean now. It is not working as a "popular" tag list at all - just as a list of tags

I will see if I can fix that in the morning<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9351">issues.joomla.org/joomla-cms/9351</a>.</sub>

**Comment by brianteeman** [comment]
Looking at the code it is completely missing any "order by count" which stops it from ever being a "popular" tags module

Unlike the "popular articles" module which does have it as seen here https://github.com/joomla/joomla-cms/blob/staging/modules/mod_articles_popular/helper.php#L73

@alikon your sql is far better than mine - any idea of the best way to do it for this module<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9351">issues.joomla.org/joomla-cms/9351</a>.</sub>

**Comment by vitaly80** [comment]
module works fine if sort by count, descending. but in cloud expecting, that displaying sort by title.

https://github.com/joomla/joomla-cms/blob/staging/modules/mod_tags_popular/helper.php it is not 3.4.8... and also not working as expecting.

lets see at
https://github.com/joomla/joomla-cms/blob/staging/modules/mod_tags_popular/helper.php#L84

```php
$query->order($order_value . ' ' . $order_direction);
```

expecting, i think should be:

```php
$query->order('count DESC');
```

then 
...
```php
$db->setQuery($query, 0, $maximum);
...
$results = $db->loadObjectList();
```php
...

I think that after this should be manual processing of $results(sorting by title, etc.)

Sorry for my worst English<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9351">issues.joomla.org/joomla-cms/9351</a>.</sub>

**Comment by brianteeman** [comment]
I agree

**Comment by SharkyKZ** [comment]
It works as expected, module name might be confusing. It's the default module for displaying tags. Ordering options are separate as stated in module description. It is a "popular tags" module when item count is used for ordering. When ordering by title, only title is meant to be taken into consideration. Example above would break the count direction (least popular tags wouldn't work) and alphabetical ordering.

**Comment by alikon** [comment]
@vitaly80  good catch
@brianteeman from a quick look  we have this staging query under the issue conditions

`
SELECT MAX(tag_id) AS tag_id, COUNT(*) AS count,MAX(t.title) AS title,MAX(t.access) AS access,MAX(t.alias) AS alias
FROM j35b2_contentitem_tag_map AS m 
INNER JOIN j35b2_tags AS t ON tag_id = t.id 
INNER JOIN j35b2_ucm_content AS c ON m.core_content_id = c.core_content_id 
WHERE t.access IN (1,1,5) AND t.published = 1 
AND m.type_alias = c.core_type_alias 
AND c.core_state = 1 
AND (c.core_publish_up = 0000-00-00 00:00:00 OR c.core_publish_up <= '2016-03-10 06:28:01') 
AND (c.core_publish_down = '0000-00-00 00:00:00' OR c.core_publish_down >= '2016-03-10 06:28:01') 
GROUP BY tag_id,title,access,alias 
ORDER BY count DESC LIMIT 0, 3
 `

lets call this query queryA
what we need to do is simply

`
select a.tag_id, a.count, a.title, a.access, a.alias 
from (queryA) A 
 order by a.title DESC
`
`i'll sumbit a pr in the weekend

**Comment by brianteeman** [comment]
If it is called popular tags module - then it is not working as expected
If it is called tags modules - then it is working as expected

Either way either the code or the text needs changing/fixing

On 10 March 2016 at 06:54, SharkyKZ <notifications@github.com> wrote:

> It works as expected, module name might be confusing. It's the default
> module for displaying tags. Ordering options are separate as stated in
> module description. It is a "popular tags" module when item count is used
> for ordering. When ordering by title, only title is meant to be taken into
> consideration. Example above would break the count direction (least popular
> tags wouldn't work) and alphabetical ordering.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9351#issuecomment-194701061>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Thanks @alikon - looks like the correct path to me - and far better than
the hack I was looking at ;)

**Comment by SharkyKZ** [comment]
It is working as a popular tags module when item count ordering and asc direction is selected. Or unpopular tags module when disc direction is selected. Or alphabetical when title ordering is selected. Etc. Forcing to select by count/desc would break this multifunctionality. A simple solution would be to add additional params to separately control display order. This would simply add another order query after the first one.

**Comment by brianteeman** [comment]
If there is no change in functionality then it cannot be called "popular
tags"

**Comment by brianteeman** [comment]
Closing as we have a PR for testing - #9376
@vitaly80 please test this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9351">issues.joomla.org/joomla-cms/9351</a>.</sub>

**Comment by vitaly80** [comment]
OK! Now works fine! Thanks @brianteeman , thanks @alikon !

**Comment by brianteeman** [comment]
@vitaly80 please can you record a successful test https://issues.joomla.org/tracker/joomla-cms/9376

**Comment by vitaly80** [comment]
Now testing many times, works perfect, but if enable "random" option - get error:

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'LIMIT 0, 2' at line 7 SQL=SELECT MAX(`tag_id`) AS tag_id, COUNT(*) AS count,MAX(t.title) AS title,MAX(`t`.`access`) AS access,MAX(`t`.`alias`) AS alias FROM `zwdj7_contentitem_tag_map` AS `m` INNER JOIN `zwdj7_tags` AS `t` ON `tag_id` = t.id INNER JOIN `zwdj7_ucm_content` AS `c` ON `m`.`core_content_id` = `c`.`core_content_id` WHERE `t`.`access` IN (1,1,5) AND `t`.`published` = 1 AND `m`.`type_alias` = `c`.`core_type_alias` AND `c`.`core_state` = 1 AND (`c`.`core_publish_up` = '0000-00-00 00:00:00' OR `c`.`core_publish_up` <= '2016-03-11 23:21:18') AND (`c`.`core_publish_down` = '0000-00-00 00:00:00' OR `c`.`core_publish_down` >= '2016-03-11 23:21:18') GROUP BY `tag_id`,`title`,`access`,`alias` ORDER BY LIMIT 0, 2

**Comment by vitaly80** [comment]
for me it successful) but for all cases - not(

**Comment by vitaly80** [comment]
$query->order('rand()');

works perfect!)

**Comment by vitaly80** [comment]
on 3.5 works fine.
