### ISSUE TITLE
Bad redirection when saving or canceling an article in backend

### ISSUE THREAD

**Issue by xstelios** [joomla/joomla-cms#9353]
#### Steps to reproduce the issue
It's is quite difficult to reproduce it as it happens only when the site is in a live hosting and not in localhost. Also it happens in some articles and not in all articles. I beleave it has something to do with the contents.

#### Expected result
To save or cancel editting the article and return to mysite/administrator/index.php?option=com_content

#### Actual result
With SEF's and URL Rewriting enabled, it goes to mysite/administrator/index.php?option=com_content&layout=edit&id=0 and displays 404 error page.
With SEF's and URL Rewriting disabled, it goes to mysite/index.php?option=com_content&layout=edit&id=0&lang=el and displays my homepage.

#### System information (as much as possible)
Joomla 3.4.8, PHP version 5.5.30, Multilanguage site

#### Additional comments
This started to happen when i updated my Joomla version from 3.4.1 to 3.4.8. 
The Same problem happens when i try to save or cancel some k2 items. 
I tried to disable all plugins but problem remains. 
I tried with different php versions but no luck. I did an optimization to Db, also with no luck.

**Comment by brianteeman** [comment]
There MUST be a difference between your livesite and your locahost sites or
they woldwork exactly the same

**Comment by xstelios** [comment]
No. There is absolutely no difference between live and local<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9353">issues.joomla.org/joomla-cms/9353</a>.</sub>

**Comment by brianteeman** [comment]
There must be an extension that is misbehaving as its not happening on a clean install of joomla or we would have had tens of thousands of reports of people not being able to perform the most basic of functions<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9353">issues.joomla.org/joomla-cms/9353</a>.</sub>

**Comment by infograf768** [comment]
If you get a link containing `&lang=el `, it means the site is set as a multilingual site. But the url language code `el` is never be used in back-end as the language filter plugin is only triggered in frontend.

**Comment by xstelios** [comment]
Yes.,my site is set as multilingual, I have mention it above. And i know that url language code is not used in backend. 
Finally i managed to save the articles without redirecting problems. As i mentioned in my 1st comment i belive it's has something to do with the contents of the articles. I'm saying that because i managed to save the article changing text format. 
Example:
I couldn't save `<p><a href="images/photo_gallery/vaptisi/vaptisi-1.jpg" rel="music[vaptisi]" title="Baptism"><img src="images/photo_gallery/vaptisi/vaptisi-1_tmb.jpg" alt="vaptisi" /></a></p>` 
but i managed to save `<p style="text-align: justify;"><a href="images/photo_gallery/vaptisi/vaptisi-1.jpg" rel="music[vaptisi]" title="Baptism Reception"><img src="images/photo_gallery/vaptisi/vaptisi-1_tmb.jpg" alt="vaptisi" /></a></p>`

I don't know if this has any relation or is a bug, but i know that my problem solved just adding the `<p style="text-align: justify;">`

**Comment by brianteeman** [comment]
That really makes little sense. The only thing I can think of (and its
based on it only happening on your live server and not localhost) is that
you are triggering some sort of issue from your host. Probably an apache
mod_security rule. If you check your server error logs and/or server
security logs there should be an entry to that effect

-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9353">issues.joomla.org/joomla-cms/9353</a>.</sub>
