### ISSUE TITLE
Refresh Manifest Cache failed: Extension is not currently installed.

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#9357]
#### Steps to reproduce the issue

In a Joomla 3.4.8, where beez3, protostar and hathor have been uninstalled, when it is upgraded to Joomla_3.5.0-rc.

#### Expected result

No warnings.

#### Actual result

Refresh Manifest Cache failed: Extension is not currently installed.
Refresh Manifest Cache failed: Extension is not currently installed.
Refresh Manifest Cache failed: Extension is not currently installed.

Error on updating manifest cache: (type, element, folder, client) = (template, beez3, beez3, 0)
Error on updating manifest cache: (type, element, folder, client) = (template, protostar, protostar, 0)
Error on updating manifest cache: (type, element, folder, client) = (template, hathor, hathor, 1)

#### System information (as much as possible)

Joomla 3.4.8.

**Comment by brianteeman** [comment]
The output is correct though

**Comment by mbabker** [comment]
You really can't uninstall anything bundled with core without causing errors somewhere (extension manifest refresh on update, SQL errors with the components, etc.)

**Comment by brianteeman** [comment]
As the error messages are accurate and informative and based on michaels comment I am going to close this. Really nothing we can do
