### ISSUE TITLE
UI/UX status icons/buttons - confusing

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9359]
This is a tracker to amalgamate #9005, #8511 and #8033 which all address the same issue

The status icons for an item show the current state eg trashed, published, unpublished
They also act as a toggle to reverse that status

Many people find this confusing. If you have a "button" with a delete icon is it logical to assume that when you select it then it will "un-trash" it. Buttons in the toolbar do not toggle they perform the action indicated by the icon.

**Comment by nikitadhiman** [comment]
Why don't we have an alt text for the present icons so as to avoid confusion? Would it be effective or should we add a new button indicating the function in more crisp manner?

**Comment by schnuti** [comment]
If you don't want this somewhat confusing mix of status and action you can move the actions to the drop down. You can remove the actions from the status buttons or keep them for convenience and old users/BC. It has to be handled the same way in ALL Joomla views. i.e. I suppose you can't remove the actions from the status buttons. Most 3. party developers have followed the Joomla practice. If you now change the behaviour this will be as confusing as with no change.
.
Add actions to com_content in backend, view : articles, default.php line 140...

    // Create dropdown items
    $action = $item->state ? 'unpublish' : 'publish';
    JHtml::_('actionsdropdown.' . $action, 'cb' . $i, 'articles');
    
    $action = $item->featured ? 'unfeature' : 'feature';
    JHtml::_('actionsdropdown.' . $action, 'cb' . $i, 'articles');
 
    $action = $archived ? 'unarchive' : 'archive';
    JHtml::_('actionsdropdown.' . $action, 'cb' . $i, 'articles');

Remove actions from status buttons line 136...

    <div class="btn-group">
    <?php echo JHtml::_('jgrid.published', $item->state, $i, 'articles.', false, 'cb', $item->publish_up, $item->publish_down); ?>
    <?php echo JHtml::_('contentadministrator.featured', $item->featured, $i, false); ?>

I've tested and this works as I supposed.

**Comment by pe7er** [comment]
Thanks for your code suggestion @schnuti. I've tested your code but IMHO it's not an improvement: 
while it might solve the confusion between some of the icons & actions, it removes the one-click publish/unpublish +  feature/unfeatured actions from the icons in the list view.

Those buttons are used a lot, and after this change you'll need two actions (click drop down & select) instead of just one click to publish/unpublish or feature/unfeatured any items.

**Comment by andrepereiradasilva** [comment]
i think all actions should be in the dropdown (except the current item state).

- Published
- Unpublish
- Archive
- Trash
- Delete (only for trashed items)

I made a PR

**Comment by schnuti** [comment]
@pe7er 
That*s why I splitted it into part1 and part2. Part2 disables the buttons! 
With a little more code it should be possible to add the other states as suggested above.

**Comment by andrepereiradasilva** [comment]
this is a little difference since https://github.com/joomla/joomla-cms/pull/10062/files

now it doesn't depend on the filter, but on the item state as it should.

But i still think all states should be in the actions dropdown.

**Comment by schnuti** [comment]
@andrepereiradasilva 
I agree ALL states should be shown. Why not publish an archived article without a second step? 
You could add delete to the list but then have to check if trashed and allowed to delete ...
Two steps deletion should be kept.

You also could change the state filter as only published and unpublished items are shown by default.  
I would like a change to show all by default but probably not every user. Or probably better show all but archived items. .. Another issue I suppose.

**Comment by designbengel** [comment]
Can we reactivate and discuss this at makeithappen?

**Comment by brianteeman** [comment]
There is another issue open to discuss this @designbengel

**Comment by lilliann123** [comment]
Joomla, itself, is very confusing.  This is why I moved over to Centralpoint and I couldn't be any happier.  Centralpoint allows you to code in 'literal' aspx. A lot of these other Content Management Systems, like Joomla, require you to learn all of their secondary operational constructs...which is an education in itself. Centralpoint does have a function library, but the actual coding aspect behind structuring functions is true aspx.  I've never seen an easier system to customize modules with. I can add a few lines of xml in the module designer and the module now has the fields & functions for me to call within the page. Then I use a CP script to reference the field for display, and it's there and functioning...display, search, syndication, forms management...all in a shot. Every moment I shave off my day in speed I can use to innovate the system vs. maintain the train.

**Comment by brianteeman** [comment]
Please don't spam the issue tracker.

**Comment by brianteeman** [comment]
So long and farewell
