### ISSUE TITLE
ModulesViewModules::$filterForm error after session timeout 

### ISSUE THREAD

**Issue by obuisard** [joomla/joomla-cms#9368]
#### Steps to reproduce the issue

Go to a module in edition. 
Let the session time out.
Start editing again. The login screen comes up.
Upon login, errors

#### Expected result

Upon login, the admin console should open on the modules page.

#### Actual result

Notice: Undefined property: ModulesViewModules::$filterForm in E:\wamp\www\MyWork_3_5\administrator\components\com_modules\layouts\joomla\searchtools\default\bar.php on line 17
Fatal error: Call to a member function getField() on a non-object in E:\wamp\www\MyWork_3_5\administrator\components\com_modules\layouts\joomla\searchtools\default\bar.php on line 17

#### System information (as much as possible)

PHP 5.4.12
Apache 2.4.4
MySQL 5.6.12

**Comment by andrepereiradasilva** [comment]
What is the joomla version?

**Comment by obuisard** [comment]
Joomla 3.5 RC. 
The Joomla! Issue Tracker shows the version, apparently GitHub does not...

**Comment by andrepereiradasilva** [comment]
i can't reproduce the error.
Any more information?

**Comment by obuisard** [comment]
When leaving the admin console in the middle of editing a module and the session times out, it is necessary to log back in and when you do, these errors occur. 
I realised you have to first use the 'search tools' button and select a module type for instance.
I could not reproduce the problem on a Joomla module (tried a few) but it does happen on a downloaded module LatestNewsEnhanced.

**Comment by C-Lodder** [comment]
+1

**Comment by dgt41** [comment]
Tip: maybe something like https://github.com/joomla/joomla-cms/pull/8272

**Comment by wilsonge** [comment]
That code is actually partially causing this error :P because those variables aren't being set. Actually the bigger mystery is why the redirect back to the modules view isn't changing the url.....

**Comment by dgt41** [comment]
Test this one: #9371

**Comment by wilsonge** [comment]
Closing in favour of #9371

**Comment by phoenixdenis** [comment]
Тоже мучался долго с это ошибкой после обновления до 3.5.1... 
Поставил Advanced Module Manager и всё стало работать...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9368">issues.joomla.org/joomla-cms/9368</a>.</sub>

**Comment by andrepereiradasilva** [comment]
english please

**Comment by phoenixdenis** [comment]
Install Advanced Module Manage.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9368">issues.joomla.org/joomla-cms/9368</a>.</sub>

**Comment by phoenixdenis** [comment]
and it work<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9368">issues.joomla.org/joomla-cms/9368</a>.</sub>
