### ISSUE TITLE
Warning JFolder::create: Infinite loop detected.

### ISSUE THREAD

**Issue by DiGwork** [joomla/joomla-cms#9374]
#### Steps to reproduce the issue
open front end on any page with a "category  List" menu item type

#### Expected result
no error message

#### Actual result
Warning
JFolder::create: Infinite loop detected.

#### System information (as much as possible)
PHP Built On	Linux ###################### #1 SMP Debian 3.2.73-2+deb7u3 i686
Database Version	5.5.47-0+deb7u1
Database Collation	latin1_swedish_ci
PHP Version	5.6.19-1~dotdeb+7.1
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

#### Additional comments

Error message appearing on any front end page derived from a menu item type "category  List"

**Comment by brianteeman** [comment]
Is this a brand new site?
What extensions do you have installed?

On 11 March 2016 at 13:41, Mark Simon <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> open front end on any page with a "category List" menu item type
> Expected result
>
> no error message
> Actual result
>
> Warning
> JFolder::create: Infinite loop detected.
> System information (as much as possible)
>
> PHP Built On Linux ###################### #1
> <https://github.com/joomla/joomla-cms/pull/1> SMP Debian 3.2.73-2+deb7u3
> i686
> Database Version 5.5.47-0+deb7u1
> Database Collation latin1_swedish_ci
> PHP Version 5.6.19-1~dotdeb+7.1
> Web Server Apache
> WebServer to PHP Interface cgi-fcgi
> Joomla! Version Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
> Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ]
> 24-Apr-2013 00:00 GMT
> User Agent Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML,
> like Gecko) Chrome/48.0.2564.116 Safari/537.36
> Additional comments
>
> Error message appearing on any front end page derived from a menu item
> type "category List"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9374>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by DiGwork** [comment]
No It has been running for some time now but tI recently backed it up with akeeba and moved to a new server.
Extentions 
Modules:
Widgetkit
Social Media Slider
tracking code
newsflash
footer
Projectfork Time tracking
User Activity - Project Fork Site
Search
Custom Html
Login Form
Main Menu
Breadcrumbs
mod_googlecrumbs
SS  Domain Checker
Dashboard Buttons
Simple email form

Plugins:
Authentication - Joomla	
 Authentication - Cookie	
Authentication - Gmail
Authentication - LDAP
Captcha - ReCaptcha
Community - My Projects	community
Content - OSYouTube Free
Content - Perfect Link with Article Images on Facebook	
Content - Fast Social Share
Content - Load Modules
Content - Joomla
Content - Smart Search
Content - Widgetkit
Projectfork Comments
Projectfork Notifications
Content - Projectfork Projects
Content - Projectfork Milestones
Content - Projectfork Tasks
Content - Projectfork Time Tracking
Content - Projectfork Forum
Content - Projectfork Repository
Content - Projectfork Designs
Content - RSForm! Pro
Content - Contact
Content - Email Cloaking
Content - Page Break
Content - Page Navigation
Content - Vote
Editor - JCE
Editor - CodeMirror
Editor - None
Editor - TinyMCE
Button - Article	editors-xtd
Button - Image	editors-xtd
Button - Page Break
Button - Readmore
Extension - Joomla
Smart Search - Tags
Smart Search - Categories
Smart Search - Contacts
Smart Search - Content
Smart Search - News Feeds
Smart Search - Web Links
Quick Icon - Akeeba Backup Notification
Quick Icon - Joomla! Update Notification	
Quick Icon - Joomla! Extensions Updates Notification
Quick Icon - JCE File Browser
Search - Categories	search
Search - Contacts
Search - Content
Search - News Feeds
Search - Web Links
Search - Tags
tags	Public	451
 		System - JCE	system	jce	Public	812
 		System - Akeeba Backup Update Check	system	akeebaupdatecheck	Public	819
 		System - Backup on update	system	backuponupdate	Public	820
 		System - OSSystem	system	ossystem	Public	804
 System - Widgetkit ZOO	system	widgetkit_zoo	Public	707
 		System - Widgetkit	system	widgetkit_system	Public	705
 		System - Widgetkit Joomla	system	widgetkit_joomla	Public	708
 		Webmaster Site Verification	system	webmastersiteverification	Public	753
 		T3 Framework	system	t3	Public	747
 		System - osolCaptcha	system	osolcaptcha	Public	710
 		System - eorisis: Verification	system	eorisis_verification	Public	755
 		System - Language Filter	system	languagefilter	Public	422
 		System - P3P Policy	system	p3p	Public	423
 		System - Logout	system	logout	Public	430
 		System - Debug	system	debug	Public	425
 		System - User Log	system	log	Public	426
 		System - Redirect	system	redirect	Public	427
 		System - Remember Me	system	remember	Public	428
 		System - Highlight	system	highlight	Public	440
 		System - SEF	system	sef	Public	429
 		System - Page Cache	system	cache	Public	424
 		System - Language Code	system	languagecode	Public	436
 		Two Factor Authentication - Google Authenticator	twofactorauth	totp	Public	448
 		Two Factor Authentication - YubiKey	twofactorauth	yubikey	Public	450
 		User - Profile	user	profile	Public	433
 		User - Contact Creator	user	contactcreator	Public	431
 		User - Joomla!

**Comment by brianteeman** [comment]
In that case it is something to do with your specific site (possibly something didnt get migrated across when you moved server - check your temp and log folder settings.

For more specific support please go to the forum http://forum.joomla.org

**Comment by DiGwork** [comment]
That forum is all corrupted right now and none of the posts show. But thanks for your attention.

**Comment by brianteeman** [comment]
It was earlier but seems perfect right now

On 11 March 2016 at 16:37, Mark Simon <notifications@github.com> wrote:

> That forum is all corrupted right now and none of the posts show. But
> thanks for your attention.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9374#issuecomment-195442388>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by DiGwork** [comment]
Oh Ok thank Brian
