### ISSUE TITLE
weblinks left as old version following 2.5 upgrade to 3.5

### ISSUE THREAD

**Issue by Twincarb** [joomla/joomla-cms#9377]
#### Steps to reproduce the issue
Install final version of Joomla 2.5
upgrade to 3.5 RC

#### Expected result
Joomla upgrades and all software from Joomla including weblinks is updated.

#### Actual result
Due to J2.5 having weblinks installed by default when the system is upgraded weblinks is ignored this leaves the admin to have to manually upgrade it, I believe it's more intuitive to upgrade weblinks if installed at the same time even though it's been removed from the core.

**Comment by brianteeman** [comment]
After the upgrade you should see that there is an extension update
available. (Which is for web links)

**Comment by brianteeman** [comment]
Closed as expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9377">issues.joomla.org/joomla-cms/9377</a>.</sub>
