### ISSUE TITLE
Blank system-messages

### ISSUE THREAD

**Issue by sapphireweb** [joomla/joomla-cms#9381]
## ------------   Requested Change ----------- ##

I am suggesting a very minor change to the /libraries/cms/application/cms.php file.  On line 230, 

if (!strlen($msg)) 

changes to 

if (!strlen(trim($msg)))

## ------------   Reason ----------- ##

I had been having an issue on my site with tons of empty system-message-component in pages each with a hidden UL of 40 or more items, all blank, causing empty messages.  After some digging, I found the problem. In a debug_backtrace, under com_blankcomponent, in the _messageQueue[] I was finding up to 50 of the following:

 Array(
   [message] => 
   [type] => message  ) 

In examining the the code for com_blankcomponent, I could not find anything that was adding anything to the messageque.  After changing the if statement in cms.php, the problem was resolved.

## ------------   Explanation / Hunch ----------- ##

Checking to see if !strlen($msg)) is normally sufficient to avoid adding blank messages.  However if a component has a blank message, where the length is greater than 0, but is only whitespace it will still be added to the que.  By adding trm(), we strip out all the erogenous spaces and other whitespace characters before checking the length of the message.

**Comment by andrepereiradasilva** [comment]
@sapphireweb can you do a PR for this?

**Comment by sapphireweb** [comment]
A PR?

**Comment by andrepereiradasilva** [comment]
PR = Pull Request
See https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by sapphireweb** [comment]
Oh... Ok... I thought this was the correct place to post this...

**Comment by sapphireweb** [comment]
Pull Request done. :)    (The problem with having worked with PC's since 1987 is that I know so many acronyms that it gets confusing.)

**Comment by andrepereiradasilva** [comment]
> (The problem with having worked with PC's since 1987 is that I know so many acronyms that it gets confusing.)

yeah i understand you ;)

**Comment by andrepereiradasilva** [comment]
actually you have not done the PR yet, you have just made a branch in your fork joomla-cms repository.
See https://github.com/sapphireweb/joomla-cms/tree/patch-1

Now you have to PR to joomla-cms main repository, staging branch.

When you complete the PR it will appear in this list 
https://github.com/joomla/joomla-cms/pulls

**Comment by andrepereiradasilva** [comment]
@brianteeman close as we have a PR (https://github.com/joomla/joomla-cms/pull/9403)?

@sapphireweb thanks for the PR

**Comment by brianteeman** [comment]
Closed please test #9403<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9381">issues.joomla.org/joomla-cms/9381</a>.</sub>
