### ISSUE TITLE
Regression: Unable to use Terms of Service with the core user plugin

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#9390]
#### Steps to reproduce the issue

1. install staging
2. go to the plugin manager
3. enable the plugin "User- Profile"
4. enable the option  "Terms of Service:"
5. add a article (next option) for Terms of Service. (just one random article)
6. try to register from the frontend

#### Expected result

You can register an account

#### Actual result

You got an error message `Invalid field:  No`

#### System information (as much as possible)

Joomla 3.5 RC
PHP7
Chrome

#### Additional comments

It makes no difference which option you choose `Agree` or `No` you allways got that error `Invalid field:  No`

**Comment by MATsxm** [comment]
Able to reproduce with ![screen shot 2016-03-12 at 12 44 05](https://issues.joomla.org/uploads/1/76162fba9d546d14104967d5a4ffc9a8.png)

what ever `Agree` or `No`is selected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9390">issues.joomla.org/joomla-cms/9390</a>.</sub>

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9390">issues.joomla.org/joomla-cms/9390</a>.</sub>

**Comment by infograf768** [comment]
Adding Regression to title<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9390">issues.joomla.org/joomla-cms/9390</a>.</sub>

**Comment by alikon** [comment]
not so sure is the correct way may i have some feedback on #9405

**Comment by brianteeman** [comment]
Closed -please test #9405 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9390">issues.joomla.org/joomla-cms/9390</a>.</sub>
