### ISSUE TITLE
Duplicate memcache(d) fields in Global Config after upgrade to J35RC

### ISSUE THREAD

**Issue by gaelicwinter** [joomla/joomla-cms#9391]
#### Steps to reproduce the issue

Have copy of live site J3.4.8
Upgrade to J3.5 RC

#### Expected result
Enjoy the memcache(d) control features

#### Actual result

See that the memcache(d) fields are duplicated

#### System information (as much as possible)

J3.4.8 => J3.5RC
Apache Version 2.4.18
PHP Version 5.5.31
MySQL Version 10.0.24-MariaDB

Rockettheme template with Gantry 4
![capture](https://cloud.githubusercontent.com/assets/6510266/13724450/0662f708-e83b-11e5-9277-d7bf6eb438fe.PNG)

**Comment by zero-24** [comment]
@gaelicwinter see here: https://github.com/joomla/joomla-cms/pull/9407 for a fix. Thanks for your report.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9391">issues.joomla.org/joomla-cms/9391</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #9407<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9391">issues.joomla.org/joomla-cms/9391</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman @gaelicwinter it is the wrong patch. Please reopen here. 

We have the same XML File in 3.4.8 (https://github.com/joomla/joomla-cms/blob/3.4.8/administrator/components/com_config/model/form/application.xml#L37-L128) and the names are also different. the secconde version should not be shown if you select "memcache" as we use `showon="cache_handler:memcached"` (note the `d`) so maybe showon is broken?

**Comment by brianteeman** [comment]
reopened

**Comment by andrepereiradasilva** [comment]
did you clean javascript cache? Ctrl+F5?

i got no problem and can't reproduce this.
Tried with `memcache` and `memcached`, all fine

Example for `memcache` in latest staging
![image](https://cloud.githubusercontent.com/assets/9630530/13730833/b384a64e-e952-11e5-9a43-5a700c9e0ea6.png)

**Comment by andrepereiradasilva** [comment]
@zero-24 can you reproduce this probem?

**Comment by gaelicwinter** [comment]
Some more info:

Basically I upgraded a copy of existing site that had caching set to Off - Caching Disabled.

I went to set Robots to No Follow and noticed that the Memcache(d) options were all showing.  Note on my original screenshot that caching is set to OFF and Cache Handler is set to File.  This was from the original site.  But the memcache options are all showing, and duplicated.  When I clicked Save for the Robots setting, the fields corrected themselves and I was unable to get it to show incorrectly again.

I repeated the process from restoration and upgrade and was unable to reproduce the problem.  I'll try again if you think its worth it.

**Comment by andrepereiradasilva** [comment]
i think it's only a browser cache issue, showon javascript file has changed in 3.5.0 so if the old one was in your browser cache you could have that kind of issues.

**Comment by gaelicwinter** [comment]
sounds good, you can close this issue and I'll watch for it when I upgrade other sites.  Sorry for the distraction.

**Comment by dfirsching** [comment]
I realize that this is closed, but this is exactly what I see on a site I upgraded from 3.4.8 to 3.5.0. I had not realized it until another admin complained to me about some modules showing up in wrong places, and she sent me a screenshot, but I could not duplicate it. I thought of cache and began looking, and then saw this same duplication of memcached settings in configuration.php as well as in the backend of the site. 
Has anybody else noticed this?  
![jmatest1-configuration-settings-memcache-4-1-2016](https://cloud.githubusercontent.com/assets/18220416/14219230/32369d20-f827-11e5-9f28-099b6541447c.JPG)

**Comment by zero-24** [comment]
Please clean your browser and joomla cache and see if you get still the same error. Thanks

**Comment by dfirsching** [comment]
You're right,it goes away... The site had previously been set to conservative caching, but I then turned caching off.  Could that have caused the problem, or was it unrelated? I can't duplicate it, but it is worrisome (and she sent me a screenshot).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9391">issues.joomla.org/joomla-cms/9391</a>.</sub>

**Comment by zero-24** [comment]
The joomla cache gets cleaned started with 3.5.1 on every update. You need to clear the browser cache by your self.

Yes it was realted to caching :)
