### ISSUE TITLE
[regression] we have broken the image selector form field

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#9393]
#### Steps to reproduce the issue

1. install staging
2. go to the article view
3. go to the tab "images and links"

#### Expected result

In joomla 3.4.8 we have:
![screen shot 2016-03-12 at 12 17 58](https://issues.joomla.org/uploads/1/cc874133276f86e57f83b1a836f12b16.jpg)

#### Actual result

With 3.5.rc we get:
![screen shot 2016-03-12 at 12 18 12](https://issues.joomla.org/uploads/1/03a05555aa15862ff0df3a688f9e526a.jpg)

#### System information (as much as possible)

Joomla 3.5RC
PHP7

#### Additional comments

It works with 3.4.8 and is broken now in 3.5 so it is a regression

**Comment by andrepereiradasilva** [comment]
i don't quite understand what is broken.

**Comment by mbabker** [comment]
The only change I see is less padding on the buttons.  Functionality wise, it's fine on current staging.

**Comment by brianteeman** [comment]
Seems ok to me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9393">issues.joomla.org/joomla-cms/9393</a>.</sub>

**Comment by dgt41** [comment]
In 3.4.x there was a PR that expanded the field because the tooltip was always the same  for multiple instances of the fields (e.g. intro, full). That was reverted as the tooltips are working correctly now.

**Comment by zero-24** [comment]
If the less padding is expected i'm fine. I have just noticed this browsing to the backend.
