### ISSUE TITLE
Confusing toolbars

### ISSUE THREAD

**Issue by nikitadhiman** [joomla/joomla-cms#9411]
The toolbars available at various locations are are often confused for their functions. Article section have exactly same toolbar as that of menu manager section. The options given might not be applicable to various sections where they have been placed at all. Hence, this creates difficulties for a naive user.

**Comment by brianteeman** [comment]
Please give examples

On 13 March 2016 at 19:01, Nikita Dhiman <notifications@github.com> wrote:

> The toolbars available at various locations are are often confused for
> their functions. Article section have exactly same toolbar as that of menu
> manager section. The options given might not be applicable to various
> sections where they have been placed at all. Hence, this creates
> difficulties for a naive user.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9411>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
In the absence of any reply I am closing this. If more information is provided it can always be reopened
