### ISSUE TITLE
Joomla_3.5.0-rc2: Unable to find install package

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#9415]
#### Steps to reproduce the issue
Update 3.4.8 > Joomla_3.5.0-rc2-Release_Candidate-Update_Package.zip
#### Expected result
Update-Success
#### Actual result
Warning JInstaller: :Install: Can't find XML setup file.
Error Unable to find install package
#### System information (as much as possible)
PHP 5.6.13
MySQLi 5.5.47-0+deb7u1
Update Channel: Joomla! Next. 
#### Additional comments
On Update-Channel: Testing all works. I write this because with former RC and beta there was not this Issue (there i download the RC/Beta and installed it per "Install Extensions").

**Comment by zero-24** [comment]
@franz-wohlkoenig please have a look here: https://github.com/joomla/joomla-cms/pull/9414

**Comment by franz-wohlkoenig** [comment]
Have read, wasn't able to understand, if it depends to what i've wrote. So i can close this Issue?

**Comment by wilsonge** [comment]
Yes - this should be fixed by #9414 - if you could test that would be greatly appreciated :)
