### ISSUE TITLE
Wrong message when unpublishing locked article

### ISSUE THREAD

**Issue by AndrisZemitis** [joomla/joomla-cms#9418]
#### Steps to reproduce the issue
Log in as user1 and create an article. Leave it open.
Log in as user2 and try to unpublish that article. 

#### Expected result
Get red-background-notification that article could not be unpublished as it is locked by another user.

#### Actual result
You get a green background Message "1 article unpublished.", though it is not unpublished as it is locked by user1.

#### System information (as much as possible)
Joomla 3.4.8

**Comment by brianteeman** [comment]
Which version of Joomla are you using
What level are both the users?


On 14 March 2016 at 10:29, AndyWorking <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Log in as user1 and create an article. Leave it open.
> Log in as user2 and try to unpublish that article. You get a green
> background Message "1 article unpublished.", though it is not unpublished
> as it is locked by user1.
> Expected result
>
> Get red-background-notification that article could not be unpublished as
> it is locked by another user.
> Actual result System information (as much as possible) Additional comments
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9418>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by AndrisZemitis** [comment]
Joomla version 3.4.8.
One user was superadmin, the other was administrator. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9418">issues.joomla.org/joomla-cms/9418</a>.</sub>

**Comment by brianteeman** [comment]
Which user was which? If I remember correctly a superuser can always open
an article even if it is checked out

On 14 March 2016 at 10:43, AndyWorking <notifications@github.com> wrote:

> Joomla version 3.4.8.
> One user was superadmin, the other was administrator.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9418
> <https://issues.joomla.org/tracker/joomla-cms/9418>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9418#issuecomment-196249635>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by AndrisZemitis** [comment]
Sorry, the user who tries to unpublish(so user2) is the superadmin. So either the article should be unpublished even if its locked or the message should change.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9418">issues.joomla.org/joomla-cms/9418</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Some more info about this

This is what user 2 (super admin) gets when making any action (publish, unpublich, trash or archive)
![image](https://cloud.githubusercontent.com/assets/9630530/15231922/e4a7b9ec-1895-11e6-9187-2ca6149f9077.png)

And if the user 2 (super admin) tries to edit the content
![image](https://cloud.githubusercontent.com/assets/9630530/15231981/2b959d56-1896-11e6-84fe-e2144de40f55.png)

the only way is a two step aproch. Checkin the item and then do any action.

The same happens in categories, contacts, and i think probably in all items that have checkin.

**Comment by ghost** [comment]
My Opinion: Expected behaviour.

**Comment by brianteeman** [comment]
Closed as expected behaviour
