### ISSUE TITLE
Update 3.5.0 rc2 to rc3 fails

### ISSUE THREAD

**Issue by bertmert** [joomla/joomla-cms#9430]
I'm a bit confused meanwhile and need an answer.

I could update all betas and rc versions via installer using update packages.

From RC2 to RC3 I get

```
Warning
JInstaller: :Install: Can't find Joomla XML setup file.
```

```
Error
Unable to find install package
```

Should updates work or not?
Thanks!q

**Comment by photodude** [comment]
I don't think Joomla updates through the extension manager are supported. I think you need to use the Joomla update component.

You get the same message in 3.4.8 extensions manager if you try to upload the RC3 update package.

**Comment by photodude** [comment]
Yep, Joomla updates through the extension manager were removed https://github.com/joomla/joomla-cms/commit/9a3149cfd1e51446a5344988c74514c260a88962

**Comment by digitalgarage** [comment]
Trying to update through the Joomla update component from 3.4.8 to rc3 I get error about the archive file corrupt, truncated or parts missing.

Anyone else getting this?... or am I alone :(

![2016-03-15_13-20-29](https://cloud.githubusercontent.com/assets/9042878/13766803/d602de34-eab0-11e5-8de1-9bf0691450e4.jpeg)

**Comment by bertmert** [comment]
Thanks for infos.

I changed to update via manager because com_joomlaupdate doesn't show updates with Update Channel "Testing" since version 3.5-i-dont-know.

**Not a real problem.** So, I will close here.

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/9469 for manual installations
