### ISSUE TITLE
No popup Add Exercises in Guru

### ISSUE THREAD

**Issue by inter-web** [joomla/joomla-cms#9431]
#### Steps to reproduce the issue
![no-popup_1](https://cloud.githubusercontent.com/assets/15849220/13767213/ef4fb958-ea2d-11e5-9a4c-b80c26656b0d.jpg)

#### Actual result

![no-popup](https://cloud.githubusercontent.com/assets/15849220/13767221/fc808c7e-ea2d-11e5-85fa-e712065394e6.jpg)

#### System information (as much as possible)
Joomla 3.4.8
Extensión: Guru 4 0 11 (ijoomla.com)
Versión Apache 	2.2.31
Versión PHP 	5.4.44
Versión MySQL 	5.5.48-cll
Arquitectura 	x86_64
Sistema operativo 	linux
Versión Perl 	5.8.8
Versión Kernel 	2.6.18-408.el5
cPanel Pro 	1.0 (RC1)  

#### Additional comments
This it's the code line

[-myweb.com-]/administrator/index.php?option=com_guru&controller=guruPrograms&task=addmedia&tmpl=component&cid[]=3

Thank You very much in advanced!

**Comment by wilsonge** [comment]
Sorry but looking at the issue you referenced this is a mistake made in Guru and should be reported to the developer of Guru. It is not an issue with Core Joomla.

I'm going to close this issue for now
