### ISSUE TITLE
Error in admin - Modules section not showing

### ISSUE THREAD

**Issue by TarponIke** [joomla/joomla-cms#9432]
#### Steps to reproduce the issue
Install Joomla 3.5 RC3 on environment described in "system information".

#### Expected result
No errors

#### Actual result
- "Error" message on top of all admin pages (no error code, just plain error).
- Menus not showing in drop down of admin menu.
- Error when trying to display modules in admin. No modules showing. "Out of sort memory". See attachment for details.

#### System information (as much as possible)
- Localhost
- Windows 7
- Uniform Server Zero XI (with standard config)
- php 5.5.30
- Database version 5.5.46
- sort_buffer_size = 64k

#### Additional comments
I'm running Joomla 3.4.8 perfectly on the same environment without any issues. Since this is a one-click upgrade I would expect there was no need for changing server configuration.
I've found that increasing the "sort_buffer_size" to 256k resolves the issue, but should that be necessary? Again, this is a one-click upgrade.

Sorry if this "issue" is mentioned elsewhere.

[Error when trying to view modules in backend-joomla35-rc3.docx]
(https://issues.joomla.org/uploads/1/293860e514d00e17d665cdcc577d7c57.docx)

![screen shot 2016-03-15 at 04 39 47](https://issues.joomla.org/uploads/1/e44467e16b16d405b2101ad0f02432e1.)

**Comment by brianteeman** [comment]
The sort_buffer_size is very low -way below the default mysql value
http://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_sort_buffer_size<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9432">issues.joomla.org/joomla-cms/9432</a>.</sub>

**Comment by TarponIke** [comment]
Ok, so this is not going to be an issue with any hosts?
Should I set the sort_buffer_size to 256k, or what would you recommend?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9432">issues.joomla.org/joomla-cms/9432</a>.</sub>

**Comment by brianteeman** [comment]
> Ok, so this is not going to be an issue with any hosts?

Shouldnt be - they would at least be using the defaults and most likely even higher

> Should I set the sort_buffer_size to 256k, or what would you recommend?

The default on my MAMP install is sort_buffer_size = 512K
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9432">issues.joomla.org/joomla-cms/9432</a>.</sub>

**Comment by TarponIke** [comment]
Just curious, is there any special change from 3.4.8 that have made the need for higher sort_buffer_size?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9432">issues.joomla.org/joomla-cms/9432</a>.</sub>

**Comment by hkhako** [comment]
I am using OpenShift as a host, and have a hard time changing the Sort_Buffer_Size for my MySQL cartridge.  It would be great if someone can point out the change that increased the sort buffer requirement.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9432">issues.joomla.org/joomla-cms/9432</a>.</sub>

**Comment by brianteeman** [comment]
To be honest I dont have any idea. It was just the original poster who determined that increasing the value fixed their problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9432">issues.joomla.org/joomla-cms/9432</a>.</sub>

**Comment by DaviRay** [comment]
I've encountered this same issue with OpenShift with their sort_buffer_size = 128K.
The OP dropped a hint that pointed me to the change that is causing this impact.

Version 3.4.8 uses the following parameters when creating most tables:
ENGINE=InnoDB DEFAULT CHARSET=utf8

Version 3.5.1 changed it to the following:
ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci

I do not know if it was intentional but that's the cause of it. My fresh, completely empty, install of Joomla 3.5.1 would not open the extensions > modules page. After re-creating the DB with the original parameters, it opens it just fine.
I am not sure if there are any other underlying effects by changing it but this is definitely the culprit.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9432">issues.joomla.org/joomla-cms/9432</a>.</sub>
