### ISSUE TITLE
Languages new content screen missing Myanmar flag entry

### ISSUE THREAD

**Issue by topazeagle** [joomla/joomla-cms#9433]
#### Steps to reproduce the issue
Languages New content Screen.
Images prefix field has no Myanmar flag. 

Language code should be my . ISO 639-1
Country code should be MM .  ISO 3166 code

So should have my_MM in drop down

You can see flag here https://en.wikipedia.org/wiki/Myanmar 

#### Expected result

Please add the flag and language to the drop down

#### Actual result

Not present

**Comment by andrepereiradasilva** [comment]
it was no flag because it seems there is no official joomla translation for Burmese (my ISO code) language.

See http://community.joomla.org/translations/joomla-3-translations.html

right @infograf768 ?

**Comment by infograf768** [comment]
Exact. We do not provide flags if we do not have a registered language pack.

**Comment by brianteeman** [comment]
Closed for the reasons stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9433">issues.joomla.org/joomla-cms/9433</a>.</sub>

**Comment by topazeagle** [comment]
Brian

I have created an empty Myanmar language pack prior to translation. I used sed to change all the file names to my-MM and looked inside some files for en-US and changed them to my-MM. I intend to translate it bit by bit as needed and resources become available. I thought I might need the flag somewhere. 

Perhaps it will work without a flag. In fact it crashes when I select Myanmar language. I will ask my support at Falang as they said they would help me with this before. 

Best regards, 

Dominic

**Comment by brianteeman** [comment]
@bakual Maybe this can become an official translation?

**Comment by Bakual** [comment]
@topazeagle I can set the language you up on Crowdin if you want to start an official package. It hopefully makes the life for you a bit easier with translating the strings.
To become an official language pack, you will have to get in contact with Ilagnayeru (MIG) Manickam (http://forum.joomla.org/memberlist.php?mode=viewprofile&u=224484). He will be able to set you up with everything needed and also give you the needed assistance.

**Comment by Bakual** [comment]
To add the language flag, you can just drop the file into `/media/mod_languages/images/`, that should do the trick.

**Comment by topazeagle** [comment]
Yes I see a lot of gif files in that directory prefixed by the language code. The drop down must read a list of prefixes from this directory rather than being read from the database. 

Thanks,

Dominic

**Comment by Bakual** [comment]
Yes, it's a simple filelist field which works from that directory.
