### ISSUE TITLE
RC2 - Calling installation folder after deleted

### ISSUE THREAD

**Issue by anabarcellos** [joomla/joomla-cms#9437]
**Steps to reproduce the issue**
Install new site on intranet unzipping full package folder.

**Result:**
After finishing the installation and removing the installation folder, when I click to open the site, it takes more than 6 MINUTES loading. After loading the first time, next times it loads normally.

/administrator loads fast, without any problem

Apache error log: 
[error] File does not exist: site/installation, referer: site/installation/index.php

I tested it 3 times.  

**Expected result**

Site should load fast after installation.
Installing 3.4.8 in the same server, it takes just one second to load.   

**Actual result**
New 3.5 installations take more than 6 minutes to load at the first time;

**System information (as much as possible)**
Server: SLES 11, PHP 5.3.19, MYSQL 5.5.39
INTRAnet - no communication with internet
no-ssl and ssl APACHE files

**Comment by andrepereiradasilva** [comment]
did you try with 3.5.0 RC3 (https://github.com/joomla/joomla-cms/releases/tag/3.5.0-rc3)

**Comment by mbabker** [comment]
Try disabling the "System - Joomla! Update Notification" and "System - Joomla! Statistics" plugins.  If you're on an intranet with no outside connection those won't work anyway and waste a lot of loading time (the stats plugin we have a 2 second coded in to for its HTTP POST to the stats server, the update plugin relies on the underlying updater library which doesn't have timeouts on its HTTP GET requests).

**Comment by anabarcellos** [comment]
@andrepereiradasilva Yes, the same happens in 3.5.0 RC3

@mbabker After testing in 5 new 3.5 RC3 installations, disabling sometimes both plugins, sometimes one OR the other,  I can say: 

**plg_system_stats** is the responsible for the **[error] File does not exist: site/installation, referer: site/installation/index.php** but this doesn't make any difference in the loading time. 

**plg_system_updatenotification** doesn't return APACHE error but is the responsible for the 6min20seconds loading time. 

I had to disable them directly in the database, because if I try to access /administrator before the site I have the same 6min20seconds of wait.    <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9437">issues.joomla.org/joomla-cms/9437</a>.</sub>

**Comment by mbabker** [comment]
For intranets your best bet is going to be to turn those off in the database as soon as you get updated or run new installations.  I ain't got the slightest clue why the stats plugin is trying to redirect to the install app (that somehow seems like a local config issue at first glance; Joomla only tries redirecting there if you have no configuration.php file AND the directory exists).  The update plugin is definitely going to cause headaches if you have no outside connection since the HTTP connector doesn't set a timeout by default.

**Comment by brianteeman** [comment]
I just installed RC3 on my laptop here in the pub with NO internet
connection. I had no problem at all. Everything worked perfectly and as
expected.

**Comment by anabarcellos** [comment]
It doesn't happen when I set enabled to plg_system_stats and plg_system_updatenotification in a 3.5-RC4 site updated from 3.4.8. Just in new installations in same intranet servers. Does it make any sense? Still testing here.  
 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9437">issues.joomla.org/joomla-cms/9437</a>.</sub>

**Comment by wilsonge** [comment]
OK I've added in a 20 second timeout to the update call https://github.com/joomla/joomla-cms/commit/332a2c04633397d8cc6a3f9dec37f2ae6ff56eb5 - so we shouldn't have it running for 6 minutes again.

I'm also really confused by the stats issue though :/ until i can understand what's going on there - it's pretty hard to fix :(

**Comment by brianteeman** [comment]
I am closing this at this time. @anabarcellos if you are still having the issue please provide more informmation<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9437">issues.joomla.org/joomla-cms/9437</a>.</sub>
