### ISSUE TITLE
[REGRESSION] Can't save user - TOS error

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#9438]
#### Steps to reproduce the issue

1. Use 3.5.0 RC3
2. Ativate "User - Profile" plugin
3. Edit a user in the backend
4. Try to save. 
5. Error! Please read the Terms of Service. You will not be able to register if you do not agree with them.

#### Expected result

User changes saved.

#### Actual result

Error! Please read the Terms of Service. You will not be able to register if you do not agree with them.

#### System information (as much as possible)

3.5.0 RC3

#### Additional comments

I think was caused by https://github.com/joomla/joomla-cms/pull/9405

@alikon can you have a look

**Comment by andrepereiradasilva** [comment]
@brianteeman can you reproduce this also?

**Comment by franz-wohlkoenig** [comment]
i'm not @brianteeman but can reproduce this.

**Comment by andrepereiradasilva** [comment]
@brianteeman 3.5.0 blocker label here?

**Comment by alikon** [comment]
i'm afraid was my fault in #9405 let me fix.....

**Comment by brianteeman** [comment]
This was reported before

On 15 March 2016 at 18:43, Nicola Galgano <notifications@github.com> wrote:

> i'm afraid was my fault in #9405
> <https://github.com/joomla/joomla-cms/pull/9405> let me fix.....
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9438#issuecomment-196967943>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Please see #9405 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9438">issues.joomla.org/joomla-cms/9438</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman https://github.com/joomla/joomla-cms/pull/9405 is a different thing.

**Comment by brianteeman** [comment]
I am confused @alikon 9405 was supposed to be the fix<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9438">issues.joomla.org/joomla-cms/9438</a>.</sub>

**Comment by brianteeman** [comment]
ok mea culpa for being confused then - it happens - its called old age

On 15 March 2016 at 18:56, andrepereiradasilva <notifications@github.com>
wrote:

> @brianteeman <https://github.com/brianteeman> #9405
> <https://github.com/joomla/joomla-cms/pull/9405> is a different thing.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9438#issuecomment-196972253>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by alikon** [comment]
`// Check that the tos are valid.

if ((!($data['profile']['tos'])) && ($this->params->get('register-require_tos', 0) == 2))
`

as usual my quick dirty trick

**Comment by wilsonge** [comment]
Closing as we have a PR

**Comment by andrepereiradasilva** [comment]
@aikon only those that don't change don't make mistakes.
