### ISSUE TITLE
ISIS Template Issue (

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#9444]
This issue came in via email from the forum - this is just to put it somewhere in the tracker so someone can look into it at some point:

> Hello

> Can you, in release 3.5, do the admin, in the isis template, "Association", did not appear in a column, and one row?

> At the moment, it takes a lot of space, and everything nice and comfortable. Only need to do 2nd line of code in the template.css template isis in the admin (row: 7819):
display: table-cell;
padding-right: 5px;

> Thank you!

**Comment by pe7er** [comment]
Is this issue related to this PR https://github.com/joomla/joomla-cms/pull/9449 ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9444">issues.joomla.org/joomla-cms/9444</a>.</sub>

**Comment by wilsonge** [comment]
Honestly I have no clue. This went in an email to Mike V which he forwarded onto me. Looking at it it seems likely (although the css files don't match up - but unable to check at the moment if it matches the 3.4.8 lines of code)

**Comment by infograf768** [comment]
same as #9449 indeed, and wrong imho. Commented there.

**Comment by infograf768** [comment]
this can be closed
