### ISSUE TITLE
Send Test Mail Message wrong

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9446]
#### Steps to reproduce the issue
In global config Mail Settings set send mail to NO
Try and send a test email with the new Send Test Mail button

#### Expected result
JLIB_MAIL_FUNCTION_DISABLED="The mail() function has been disabled and the mail can't be sent."

#### Actual result
JLIB_MAIL_FUNCTION_OFFLINE="The mail function has been temporarily disabled on this site, please try again later."

**Comment by andrepereiradasilva** [comment]
If you voluntarily disabled the site to not send mails. The mail function is offline.
> JLIB_MAIL_FUNCTION_OFFLINE="The mail function has been temporarily disabled on this site, please try again later."

If your server can't send mails because can't use mail function then is disabled.
> JLIB_MAIL_FUNCTION_DISABLED="The mail() function has been disabled and the mail can't be sent."

Maybe the text are not the better, but i think the behavior is correct.

This is processed in https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/mail/mail.php#L73-L111

**Comment by brianteeman** [comment]
> If you voluntarily disabled the site to not send mails. The mail function is offline.
trying again later will have zero effect at all because you have chosen to disable the mail functonality<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9446">issues.joomla.org/joomla-cms/9446</a>.</sub>

**Comment by andrepereiradasilva** [comment]
So, the only correction needed is the language variable.

> JLIB_MAIL_FUNCTION_OFFLINE="The mail function has been temporarily disabled on this site, please try again later."

Maybe?

> JLIB_MAIL_FUNCTION_OFFLINE="The mail function has been disabled by the administrator."

**Comment by shubhamnba2009** [comment]
What is the location of jlib_mail_function_offline language variable in language directory? Thanks in advance<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9446">issues.joomla.org/joomla-cms/9446</a>.</sub>

**Comment by andrepereiradasilva** [comment]
/language/en-GB/en-GB.lib_joomla.ini
and
/administrator/language/en-GB/en-GB.lib_joomla.ini

**Comment by brianteeman** [comment]
NO the language string doesnt need changing - the code is calling the wrong message as stated in the first post<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9446">issues.joomla.org/joomla-cms/9446</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i don't agree with you on this one brian.

IMHO:
- disabled: the system cannot send a mail, because the is no mail function in the system
- offline: the super user decided to put the mail function offline, the same logic as site offline.

**Comment by shubhamnba2009** [comment]
Than we are only left with making correction in the language variable. 
Or Brian u have any opinion on this?

**Comment by joo7** [comment]
I'm with brianteeman

disabled: system cannot sent, because super user DISABLED function = voluntarily/wanted

offline: system cannot sent, because of other (technical) reasons (site local, no internet connection...) = unwanted

**Comment by andrepereiradasilva** [comment]
and when you set the **site offline** in global configuration ... " system cannot sent, because of other (technical) reasons (site local, no internet connection...) = unwanted"

what i mean is offline for one thing (mail server) should have the same treatment as offline for the other thing (site). consistency

**Comment by joo7** [comment]
oh, sorry, true, we need consistency.
hm, some super user might not be aware when setting site offline, sent mail is disabled too...

**Comment by joo7** [comment]
If we leave the language-strings unchanged for consistency and since we don't know, if the function is temporarily or permanent offline and/or temporarily or permanent disabled, maybe the text can be formulated like this?

JLIB_MAIL_FUNCTION_OFFLINE="The mail function is currently disabled by an administrator in the global configuration. Please try again later or contact the webmaster/administrator of this website."
(maybe drop " in the global configuration")

JLIB_MAIL_FUNCTION_DISABLED="The mail() function is currently not available. Please try again later or contact the webmaster/administrator of this website."

**Comment by Kubik-Rubik** [comment]
@brianteeman Thank you for the finding. Could you please check the proposed English text? This will go into 3.5.1.

**Comment by brianteeman** [comment]
Changing the text is not the solution - as stated in the first post the code is giving the wrong error message

**Comment by mbabker** [comment]
I'm inclined to agree with the others here that the text just needs to be cleaned up.  Remove the "please try again later" part of the offline string.  The other choice is in `JMail::Send()` use the disabled string and phase out the offline string completely.

**Comment by joo7** [comment]
Ok, if "Send Mail" is set to "No" using "Send Test Mail" will result in:

JLIB_MAIL_FUNCTION_OFFLINE="The mail function is currently disabled by an administrator in the global configuration."

**Comment by joo7** [comment]
In case this might be confusing since a user using the "Send Test Mail" button has to be an administrator and is in the global configuration already:

JLIB_MAIL_FUNCTION_OFFLINE="The 'Send Mail' function is currently disabled here in the 'Mail Settings' by an administrator."

**Comment by sovainfo** [comment]
Suggest to solve the real issue here of poor UI design. The button should not be available when Send Mail is set to No!

**Comment by brianteeman** [comment]
How about instead of suggesting something you submit a pull request

On 28 April 2016 at 15:50, sovainfo <notifications@github.com> wrote:

> Suggest to solve the real issue here of poor UI design. The button should
> not be available when Send Mail is set to No!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9446#issuecomment-215450799>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by joo7** [comment]
@sovainfo good point, but is it UI if your mails stopped working, you go backend in global config and your test-button is gone? how would he know some other admin set Send Mail to No voluntarily?

**Comment by sovainfo** [comment]
@brianteeman Considering the differences of opinion on this issue not going to waste time on that.
@joo7 Same question for someone changing SMTP to PHPMail. With multiple Super Loosers there is a big chance things are not as you expected. Sounds obvious to me, when troubleshooting! First thing to check when mails stopped working is to see whether sending mails is enabled! If your first reaction is to test it, the inability to do that is leading you to the thing you should have done first.

**Comment by joo7** [comment]
@sovainfo right, things obvious to an experienced developer might not be obvious to beginners - isn't that what UX/UI is about? Who do we want to adress? I think we should give as much help and info to all. We should rather risk to repeat more than obvious info than do devtalk in a notice - from a viewpoint of a beginner :) He might not know where to look first. Do we want him to depend on developers? I don't think we should leave the "multiple Super Loosers" alone...

**Comment by sovainfo** [comment]
Rest my case! Glad I didn't waste my time!

**Comment by joo7** [comment]
@sovainfo Sorry, I still think you make a good point. Maybe grey button with tip: "'Test Mail' is disabled because 'Send Mail' is set to 'No'"?

**Comment by sovainfo** [comment]
@joo7 No problem, we are both entitled to our own opinions. I'll leave it up to Kubik-Rubik to decide and implement whatever is decided upon. You are the only one that gave his opinion on my proposal. Considering we disagree, I'll leave it at that.

**Comment by brianteeman** [comment]
Closed as we have a PR #11416<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9446">issues.joomla.org/joomla-cms/9446</a>.</sub>
