### ISSUE TITLE
Error Installing components on PDOMysql that have an update site in its XML manifest file

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#9447]
Full issue description at http://forum.joomla.org/viewtopic.php?f=706&t=912902&p=3377090#p3377090

**Comment by richard67** [comment]
Hmm, I just tested and cannot reproduce the isue with 3.5.0 RC 4: I could install weblinks with using the PDO driver for mysql, and weblinks has an update site in its manifest, as required for the test, and all worked well.

Is it maybe related to PHP versions? I tested with 7.

Or has it been solved somehow already since 3.4.8 for which the isue was reported?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9447">issues.joomla.org/joomla-cms/9447</a>.</sub>

**Comment by mbabker** [comment]
Trying to replicate, hitting other errors, but not this one.  Using the weblinks package they posted on https://github.com/joomla-extensions/weblinks/issues/193

PHP 5.5.31, 5.6.17, and 7.0.4 w/ PDO MySQL:

```sh
Warning

SQLSTATE[HY000]: General error: 1364 Field 'system_data' doesn't have a default value
Package Install: There was an error installing an extension: com_weblinks.zip
```

OK, let's try the Akeeba 4.5.5 package since that's what the forum user said they had issues with.

PHP 5.5.31, 5.6.17, and 7.0.4 w/ PDO MySQL:

```sh
Warning

SQLSTATE[HY000]: General error: 1364 Field 'system_data' doesn't have a default value
```

So I can't even get current versions of anything installed to test them.

Fine.  Switch over to MySQLi and install Akeeba 4.5.4 since the forum user suggested their issue was with updating the extension.  Then switch back to PDO MySQL to run the update.  Go into the component, hit his "Reload Update Information" button.  Now I'm here w/ PHP 5.6.17:

```sh
An error has occurred.
 HY000 SQLSTATE[HY000]: General error: 1364 Field 'data' doesn't have a default value
```

I give up.  I surely can't install or update extensions with Joomla's core update feature on a PDO MySQL setup, but it sure as hell isn't related to that forum post.

**Comment by richard67** [comment]
@mbabker Just for curiosity: You did that on a Joomla! 3.4.8 as reported in their forum, or on a 3.5.0 RC 4 (or staging) as I did?

**Comment by mbabker** [comment]
Current staging.  Because so much has changed since 3.4.8 it'd be pretty difficult to try and confirm an issue there then trace down whether it's fixed or not.

**Comment by brianteeman** [comment]
Which version of mysql are you on? I remember you had issues with other PDO related bug reports which I couldnt replicate on my pdo system with 5.5.42 and php 5.6.10
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9447">issues.joomla.org/joomla-cms/9447</a>.</sub>

**Comment by mbabker** [comment]
5.6.29

**Comment by brianteeman** [comment]
So i am pretty sure based on all of our previous testing that there is an issue which is specific to the mysql version<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9447">issues.joomla.org/joomla-cms/9447</a>.</sub>

**Comment by richard67** [comment]
I had tested with mysql version 5.5.47 and could not reproduce with weblinks.
I will test soon with lower version which does not support utf8mb4.

**Comment by richard67** [comment]
Hmm can also not replicate this with PHP 5.6.19 and mysql 5.1.73 on 3.5.0 RC 4 with installing weblinks. The record in the update site table has been added, no errors shown anywhere, also not in php error log file.

**Comment by andrepereiradasilva** [comment]
Could be this?

> MySQL is most likely in STRICT mode. Try running SET GLOBAL sql_mode='' or edit your my.cnf to make sure you aren't setting STRICT_ALL_TABLES or the like.

http://stackoverflow.com/questions/18751291/mysql-error-1364-field-display-name-doesnt-have-default-value

**Comment by wilsonge** [comment]
Possibly but then two things:
1) everyone here has run a maximum MySQL version of 5.6 - so it would have to be manually set to on
2) I think it's more likely to be a MySQL client issue rather than server issue - otherwise we would see this issue manifest on mysqli mode which @mbabker doesn't (as far as I understand)

**Comment by andrepereiradasilva** [comment]
@wilsonge, mysqli driver sets sql_mode mode to '', pdomysql driver doesn't, i think

See https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/driver/mysqli.php#L187

**Comment by mbabker** [comment]
```sql
SELECT @@sql_mode;

STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION
```

**Comment by andrepereiradasilva** [comment]
5.5.5-10.0.24-MariaDB
```sql
SELECT @@sql_mode

(empty)
```

So that seems to be the problem.
an empty sql_mode needs to be added to pdomysql driver too

**Comment by andrepereiradasilva** [comment]
@mbabker almost bet this (https://github.com/joomla/joomla-cms/pull/9380) is caused by the same thing

**Comment by mbabker** [comment]
Yes and no.  Yes in the fact that changing the `sql_mode` to the most permissive setting we can guarantees things will work.  No in the fact that the value that's trying to be given to the database is technically not valid for the schema but thanks to the loose session settings MySQL will take it.

**Comment by andrepereiradasilva** [comment]
right, but IMHO you have to options:
1. correct all queries and default values in the database (and you probably still have have issues with extensions) and allow all modes
2. or add also the `SET SESSION sql_mode = '';` to pdomysql driver like is already in mysql and mysqli drivers.

**Comment by wilsonge** [comment]
@mbabker can you temporarily turn off strict mode then and see if things resolve themselves so we at least replicate the issue :) that's going to at least allow people to reliably formulate a fix :)

**Comment by andrepereiradasilva** [comment]
BTW, can you confirm that changing the pdomysql sql_mode solves the issues?

**Comment by mbabker** [comment]
You do both.  The loose settings makes things consistent and makes sure things work, correcting the schema and PHP code to ensure valid values are being generated ensures a valid and consistent dataset across the board.  If I'm not mistaken we aren't doing something similar in for PostgreSQL or SQL Server, so something's gotta be working right in those environments.

**Comment by andrepereiradasilva** [comment]
> If I'm not mistaken we aren't doing something similar in for PostgreSQL or SQL Server, so something's gotta be working right in those environments.

or they don't enforce strict modes ... or something like that

**Comment by andrepereiradasilva** [comment]
> You do both. The loose settings makes things consistent and makes sure things work, correcting the schema and PHP code to ensure valid values are being generated ensures a valid and consistent dataset across the board.

Agree.

**Comment by mbabker** [comment]
Add this to the end of the PDO MySQL driver's connect method:

```php
// Set sql_mode to non_strict mode
$this->connection->query("SET @@SESSION.sql_mode = '';");
```

Now I get the message from the forum.

**Comment by wilsonge** [comment]
So you are running 5.6.29, yet Richard with 5.6.19 (presumably with strict mode off else hell would have broken loose for him) gets nothing. So I guess next step is to figure out if it's a server issue specific to a MySQL version or a client issue :/

**Comment by wilsonge** [comment]
We also need to go back and fix strict mode issues

**Comment by andrepereiradasilva** [comment]
> I had tested with mysql version 5.5.47 and could not reproduce with weblinks.

not 5.6.19 (that's his php version)
you need to stop going to the pub ... :D

**Comment by mbabker** [comment]
Well.  The sql_mode change both fixes and breaks things.  Extensions install fine, but none of the update sites are being added to the table.  Tried Akeeba, Weblinks, and my own stuff.  Nada.  Only in Akeeba is that specific error message being displayed for me, but it's not a stack trace you would expect.  The error page is getting rendered, then making matters worse the stack trace is on the line where I added the query for the sql_mode change.

![screen shot 2016-03-16 at 9 25 47 pm](https://cloud.githubusercontent.com/assets/368545/13833597/b93388ae-ebbd-11e5-8373-b132622bd54d.png)

**Comment by andrepereiradasilva** [comment]
that's the error message of the user in the forum

> HY000 SQLSTATE[HY000]: General error: 2014 Cannot execute queries while other unbuffered queries are active. Consider using PDOStatement::fetchAll(). Alternatively, if your code is only ever going to run against mysql, you may enable query buffering by setting the PDO::MYSQL_ATTR_USE_BUFFERED_QUERY attribute.

**Comment by mbabker** [comment]
Right but it's not in a place that's consistent with what the user's saying the error is.

**Comment by mbabker** [comment]
var_dump'ing the object getting passed into the error handler + the trace...

![screencapture-jcms-administrator-index-php-1458178594392](https://cloud.githubusercontent.com/assets/368545/13833768/30da21e6-ebbf-11e5-980d-b77990c42bb2.png)

**Comment by mbabker** [comment]
And turning off the debug plugin gets things working again for me.

**Comment by andrepereiradasilva** [comment]
it seems that are 3 different related things:
1. correct queries and default values in the database where sql_mode strict mode returns errors
2. add also the SET SESSION sql_mode = ''; to pdomysql driver like is already in mysql and mysqli drivers.
3. solve your latest problem that seems to be related to the forum user problem

**Comment by andrepereiradasilva** [comment]
@mbabker reggarding 3. did you try to add to the pdomysql driver?
```php
$this->connection->setAttribute(PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, true);
```

Reference: http://php.net/manual/en/ref.pdo-mysql.php

**Comment by mbabker** [comment]
Yep, made no difference with that unbuffered query thing.

**Comment by andrepereiradasilva** [comment]
did you added it before or after the ?
```php
// Set sql_mode to non_strict mode
$this->connection->query("SET @@SESSION.sql_mode = '';");
```

**Comment by mbabker** [comment]
Before.

**Comment by andrepereiradasilva** [comment]
ok... i cannot replicate your issue. Maybe another mysql default config changed in your version that is causing that.

**Comment by andrepereiradasilva** [comment]
and if you add
```
array_push($this->options['driverOptions'], array(PDO::MYSQL_ATTR_USE_BUFFERED_QUERY, true));
```

to the beggining of the pdomysql.php `connect` method? in other words add that flag on pdo connect, instead of being set after pdo connect.

**Comment by wilsonge** [comment]
I've fixed what I can from here in https://github.com/joomla/joomla-cms/issues/9461 - can people in here do some testing please?
