### ISSUE TITLE
Articles found via Tags give wrong author

### ISSUE THREAD

**Issue by tvoeten** [joomla/joomla-cms#9448]
#### Steps to reproduce the issue
Articles found by Tags (List of all tags) are shown a wrong author. It shows the logged in user or super administrator. At least not the correct author of the article.

See http://www.dorpsbelang.com/index.php/nieuws/tags/2-alv
or all other tags

**Comment by brianteeman** [comment]
Please can you test with the default protostar template to remove the possibility of it being an issue in your template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9448">issues.joomla.org/joomla-cms/9448</a>.</sub>

**Comment by tvoeten** [comment]
Few minutes ago I tested the issue with protostar template.
With protostar template the reported issue is not found.
So the problem is indeed the template (Yootheme Finch) and not the CMS.

Please close my issue, I will report the bug to Yootheme

Kind regards
Tom Voeten

Van: Brian Teeman [mailto:notifications@github.com]
Verzonden: woensdag 16 maart 2016 18:39
Aan: joomla/joomla-cms <joomla-cms@noreply.github.com>
CC: Vedin <tvoeten@vedin.nl>
Onderwerp: Re: [joomla-cms] Articles found via Tags give wrong author (#9448)


Please can you test with the default protostar template to remove the possibility of it being an issue in your template.

________________________________
This comment was created with the J!Tracker Application<https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9448<https://issues.joomla.org/tracker/joomla-cms/9448>.

**Comment by brianteeman** [comment]
Closing as an issue with the yootheme template
