### ISSUE TITLE
upgrade 3.4.8 to 3.5RC4 with postgres database gives errors

### ISSUE THREAD

**Issue by slibbe** [joomla/joomla-cms#9450]
#### Steps to reproduce the issue
Install new Joomla 3.4.8
Configure in Joomla Update Component the Update Channel to Testing 
Perform update to 3.5 RC4.

#### Expected result
All be fine. No errors on Extensions > Manage > Database .

#### Actual result
message " 0 ERROR: syntax error at or near ""#__contentitem_tag_map_idx_tag"" LINE 1: ...LTER TABLE "#__contentitem_tag_map" DROP INDEX "#__con... ^SQL=ALTER TABLE "#__contentitem_tag_map" DROP INDEX "#__contentitem_tag_map_idx_tag";"

When going to Extensions > Manage > Database following is shown:

 Warning: Database is not up to date!
3 Database Problems Found.
Other Information

Database schema version (3.4.4-2015-07-11) does not match CMS version (3.5.0-2016-03-01).
Table 'bsxro_redirect_links' does not have column 'new_url' with type varchar. (From file 3.5.0-2016-03-01.sql.)
Table 'bsxro_redirect_links' does not have column 'referer' with type varchar. (From file 3.5.0-2016-03-01.sql.)

#### System information (as much as possible)
See attachment; unfortunately systeminfo is not allowed as attachment.
 
PHP Built On	Linux scotchbox 3.13.0-55-generic #94-Ubuntu SMP Thu Jun 18 00:27:10 UTC 2015 x86_64
Database Version	9.3.10
Database Collation	en_US.UTF-8
Database Connection Collation	UTF8
PHP Version	5.6.14-1+deb.sury.org~trusty+1
Web Server	Apache/2.4.16 (Ubuntu)
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.5.0-rc4 Release Candidate [ Ember ] 16-March-2016 00:45 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

#### Additional comments
I have reproduced this with the same configuration. With MySQL no problems found on same procedure.

**Comment by zero-24** [comment]
Please try https://github.com/joomla/joomla-cms/pull/9451 :)

**Comment by zero-24** [comment]
@slibbe can you try with the missing ; applyed? Thanks.

**Comment by brianteeman** [comment]
Closed s we have a PR #9451<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9450">issues.joomla.org/joomla-cms/9450</a>.</sub>
