### ISSUE TITLE
SVG not working in Chrome & Firefox on User Reset, Remind, Tags & Search Results

### ISSUE THREAD

**Issue by saraheagle** [joomla/joomla-cms#9453]
I am using SVGs for the rounded background "signpost" shapes on http://cib.testcms.co.uk/ in the top right corner.
```
<svg class="icon icon-bgshapeConverted bgshape_turq">
<use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#icon-bgshapeConverted"></use>
</svg>
```
They work perfectly on all pages until I get to some Joomla pages with <forms> and they do not show. It only happens in Chrome & Firefox, they do work in IE. It happens on the default "Protostar" template too.

- Forgot your password? http://cib.testcms.co.uk/login?view=reset 
- Forgot your username? http://cib.testcms.co.uk/login?view=remind 
- Search Results > type something in search box (top left) 

I have tried removing elements on the page via Chrome >> Inspect element to see if something there was causing it. But that didn't help. Also if I make a copy of any page (view source >> select all >> C&P into new file >> view through browser) the SVGs do not show at all, so I'm not sure how to go about seeing what's causing the issue.

I wonder if it's something to do with jQuery?
I am very happy to help, but may need pointing in the right direction, I am a designer that can do a bit of coding.
Thanks

#### System information (as much as possible)
PHP Built On  Linux serv01.ukm2.siteground.biz 3.12.18-clouder0 #1 SMP Wed Oct 28 23:24:35 EET 2015 x86_64  
Database Version  5.6.28-76.1-log  
Database Collation  utf8_general_ci  
PHP Version  5.6.18  
Web Server  Apache  
WebServer to PHP Interface  cgi-fcgi  
Joomla! Version  Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT  
Joomla! Platform Version  Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT  
User Agent  Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko  

Safe Mode  Off  
Open basedir  None  
Display Errors  On  
Short Open Tags  On  
File Uploads  On  
Magic Quotes  Off  
Register Globals  Off  
Output Buffering  Off  
Session Save Path  /tmp  
Session Auto Start  0  
XML Enabled  Yes  
Zlib Enabled  Yes  
Native ZIP Enabled  Yes  
Disabled Functions  None  
Multibyte String (mbstring) Enabled  Yes  
Iconv Available  Yes

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org

**Comment by saraheagle** [comment]
Thanks, I have already, but I think this is a bug as it is _specific Joomla <form> code_ causing the issue and it happens on the default template. **_It is nothing to do with the template._**

If it is not a bug, can you explain why it is not?

**Comment by Bakual** [comment]
As Brian said, please use the forum. It's likely not related to core because it doesn't make sense that core would make your SVG a size of 0*0px. There is no such code which would do that.

**Comment by saraheagle** [comment]
Thank you, I realised as soon as I posted that I should have shown an example on a brand-new default Joomla installation.
If you look at http://testcms.co.uk/clean/ & http://testcms.co.uk/clean/index.php/login?view=remind in Chrome & the IE you can see the problem.

It does not make sense, but its clearly happening.
Sarah
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9453">issues.joomla.org/joomla-cms/9453</a>.</sub>

**Comment by Bakual** [comment]
It may be related to some JavaScript loaded by the form. But please again, use the forum to find out what causes this.
