### ISSUE TITLE
Media manager, image selection with fieldid does not work on Isis

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#9454]
#### Steps to reproduce the issue

I have found the case testing an extension. An image field (that was working in Joomla 3.4) is not working in 3.5.0rc4.

This is the button to choose an image for the image field.

			$remoteUrl = 'index.php?option=com_media&amp;view=images&amp;tmpl=component&amp;asset=com_myextension&amp;author=' . JFactory::getUser()->id . '&amp;fieldid=' . $idTag;
			$buttonId = $idTag . '_btn';

			JHtml::_('bootstrap.modal');
			$control[] = '<a id="' . $buttonId . '" href="#' . $idTag . '_modal" role="button" class="btn" data-toggle="modal" title="' . JText::_('JSELECT') . '">' . JText::_('JSELECT') . '</a>';
			$control[] = JHtmlBootstrap::renderModal(
					$idTag . '_modal',
					array(
					'url' => $remoteUrl,
					'title' => JText::_('JSELECT'),
					'height' => '600px', 'width' => '500px')
			);
#### Expected result

Selected image file is inserted in the image field.

#### Actual result

No action

#### System information (as much as possible)

3.5.0rc4

#### Additional comments

If Isis view override is removed, then the image selection works OK.

administrator/templates/isis/html/com_media/images/default.php

				<button class="btn btn-success button-save-selected" type="button" <?php if (!$this->state->get('field.id')):?>onclick="ImageManager.onok();window.parent.jModalClose();window.parent.jQuery('.modal.in').modal('hide');"<?php endif;?> data-dismiss="modal"><?php echo JText::_('COM_MEDIA_INSERT') ?></button>

administrator/components/com_media/views/images/tmpl/default.php

				<button class="btn btn-success button-save-selected" type="button" onclick="<?php if ($this->state->get('field.id')):?>window.parent.jInsertFieldValue(document.getElementById('f_url').value,'<?php echo $this->state->get('field.id');?>');<?php else:?>ImageManager.onok();<?php endif;?

@dgt41 ... I remember a related PR ...

**Comment by wilsonge** [comment]
@dgt41 I think this is one for you

**Comment by dgt41** [comment]
The button is the one on the modals footer or the one inside the modal?

**Comment by anibalsanchez** [comment]
The button inside the modal from media/images that calls the image insertion routine into the field.

**Comment by dgt41** [comment]
I cannot replicate this! @anibalsanchez is your browser's cache cleared? Which extension failed?

**Comment by ggppdk** [comment]
> If Isis view override is removed, then the image selection works OK.
> 
> administrator/templates/isis/html/com_media/images/default.php


Yes i confirm this issue,

isis backend template has an template override file ...
**administrator/templates/isis/html/com_media/images/default.php**
- which uses modal that is bootstrap based (if i remember correctly)

but com_media component has:
**administrator/components/com_media/views/images/tmpl/default.php**
- which uses modal that is mootools based (if i remember correctly) 

I have already made a workaround in my extension to load a copy of the component template file
```
JPATH_BASE.'/templates/'.$app->getTemplate().'/html/com_media/images/my_custom.php
```

but there must be several extensions with custom code,
- that may be effected by this, they will not be able to select media files

**Comment by dgt41** [comment]
Hmmm @ggppdk that doesn't make much sense:
The field SHOULD work out of the box. The current ISIS override DOESN'T need the onclick call (when a fieldId is passed) as that is done in the mediafield.js.
can you share the xml definition for such a failing field?

**Comment by ggppdk** [comment]
@dgt41 
you are right but ...
it is not an XML file not JForm !

I am calling inside media manager inside custom PHP code ...
similar as @anibalsanchez example
and i have seen 1 or 2 other extensions doing this

**Comment by dgt41** [comment]
OK, now it makes sense. I will change the code to incorporate such cases

**Comment by dgt41** [comment]
@anibalsanchez @ggppdk @wilsonge This is one of those chicken-egg situation: providing the old JinsertImage() breaks the repeatable field

**Comment by wilsonge** [comment]
OK How exactly are you guys using this field. I know you say PHP - but I need more information to make a decision about b/c. Like honestly my gut is that JFormFields are designed to work through JForm - if you are using things outside of this then we don't offer b/c on that. But willing to study code if you guys feel you are "using" the API correctly :)

**Comment by ggppdk** [comment]
Ok, this is not a complete solution, but maybe duplicate

administrator/components/com_media/views/images/tmpl/default.php
as:
administrator/components/com_media/views/images/tmpl/default_legacy.php

And require that all extensions using custom code to call media manager will need to add to their URL:
&layout=default_legacy

**Comment by ggppdk** [comment]
**But i think that there is 1 more problem here:**
- which is bad too:
adding an override that uses bootstrap modal in isis template and thus behaves differently than the template file of component, makes little sense and creates another problem

It means that if any site uses a different backend template that does not have an override like isis
then these will break  ?
- media field
- and repeatable field

**Comment by ggppdk** [comment]
@wilsonge 
Because i felt i was not using the API correctly
- that is why i did not file an issue

I am using JForm,
- but the field is not extending JFormField

About my code:
```
// We will use the mootools based media manager
JHtml::_('behavior.framework', true);

// Load the modal behavior script.
JHtml::_('behavior.modal'/*, '.fc_image_field_mm_modal'*/);

// Include media field JS, detecting different version of Joomla
if( file_exists($path = JPATH_ROOT.'/media/media/js/mediafield-mootools.min.js') ) $media_js = 'media/mediafield-mootools.min.js';
else if( file_exists($path = JPATH_ROOT.'/media/media/js/mediafield.min.js') ) $media_js = 'media/mediafield.min.js';
else $media_js = 'media/mediafield.js';

JHtml::_('script', $media_js, $mootools_framework = true, $media_folder_relative_path = true, false, false, true);

// Tooltips for image path and image popup preview
JHtml::_('behavior.tooltip', '.hasTipImgpath', array('onShow' => 'jMediaRefreshImgpathTip'));
JHtml::_('behavior.tooltip', '.hasTipPreview', array('onShow' => 'jMediaRefreshPreviewTip'));
...
...
...
$mm_link = 'index.php?option=com_media&amp;view=images&amp;layout=default_fc&amp;tmpl=component&amp;asset=com_flexicontent&amp;author=&amp;fieldid=\'+mm_id+\'&amp;folder=';
$select_existing = '
<div class="'.$input_grp_class.'">
	<div class="media-preview '.$add_on_class.' ">
		'.JHtml::tooltip($tooltip, $tooltip_options).'
	</div>
	<input type="text" name="'.$fieldname_n.'[existingname]" id="'.$mm_id.'" value="'.htmlspecialchars($img_path, ENT_COMPAT, 'UTF-8').'" readonly="readonly"
		class="existingname input-xxlarge field-media-input hasTipImgpath"  title="'.htmlspecialchars('<span id="TipImgpath"></span>', ENT_COMPAT, 'UTF-8').'" data-basepath="'.JUri::root().'"
	/>
	<a class="fc_image_field_mm_modal btn '.$tooltip_class.'" title="'.JText::_('FLEXI_SELECT_IMAGE').'" onclick="var mm_id=jQuery(this).parent().find(\'.existingname\').attr(\'id\'); currElement'.$field->id.'=mm_id; SqueezeBox.open(\''.$mm_link.'\', {size:{x: ((screen.width-120) > 1360 ? 1360 : (screen.width-120)), y: ((screen.height-220) > 800 ? 800 : (screen.width-220))}, handler: \'iframe\', onClose: function() { incrementValCnt'.$field->id.'(); } });  return false;">
		'.JText::_('FLEXI_SELECT').'
	</a>
	<a class="btn '.$tooltip_class.'" href="javascript:;" title="'.JText::_('FLEXI_CLEAR').'" onclick="var mm_id=jQuery(this).parent().find(\'.existingname\').attr(\'id\');  clearField'.$field->id.'(this); jInsertFieldValue(\'\', mm_id); return false;" >
		<i class="icon-remove"></i>
	</a>
</div>
';
```

**Comment by anibalsanchez** [comment]
In my case, the original button from media/images fixes the issue.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9454">issues.joomla.org/joomla-cms/9454</a>.</sub>

**Comment by ggppdk** [comment]
@anibalsanchez 

With your changes in the insert button
- it works in my case too without using a template override

And now i remember that indeed that was the problem, the changes in the insert button, not the use of bootstrap modal (sorry i recalled wrong)
- in my case i use Squeezebox modal and it works with the changes that you made in the insert button (and then my own code closes the Squeezebox modal)

So this seems to be backwards compatible.

Does your change break the repeatable field ?

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #9466<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9454">issues.joomla.org/joomla-cms/9454</a>.</sub>

**Comment by nareshvida** [comment]
Hi,

I am also facing the same problem with JA Platon theme. It was working fine with Joomla 3.4. The issue cause after Joomla Version update. Kindly help me.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9454">issues.joomla.org/joomla-cms/9454</a>.</sub>

**Comment by brianteeman** [comment]
@nareshvida you should check with the maker if the template for an update
