### ISSUE TITLE
Can't create a Banner (with PDO driver in MySQL 5.6.6+)

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#9455]
#### Steps to reproduce the issue

This is similar issue as the one solved in https://github.com/joomla/joomla-cms/pull/9380.

1. Use latest staging or RC4 with a MySql server 5.6.6+
2. Set the database driver as "PDO (MySQL)" in global configuration.
3. Create or edit a banner.

###### Note

If you don't have MySql 5.6.6+ you can emulate the error by setting the `sql_mode` in pdomydriver file. For that, add, after this line https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/driver/pdomysql.php#L149 the following code:
```php
$this->connection->query("SET @@SESSION.sql_mode = 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';");
```

#### Expected result

Banner saved.

#### Actual result

Doesn't work:
![image](https://cloud.githubusercontent.com/assets/9630530/13850488/031efec8-ec52-11e5-98c5-11c5654fc55d.png)

#### System information (as much as possible)

Latest staging / RC 4.

**Comment by wilsonge** [comment]
PR in https://github.com/joomla/joomla-cms/pull/9461
