### ISSUE TITLE
Can't find or install languages (with PDO driver in MySQL 5.6.6+)

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#9457]
#### Steps to reproduce the issue

This is similar issue as the one solved in https://github.com/joomla/joomla-cms/pull/9380 and to the issue described in https://github.com/joomla/joomla-cms/issues/9455.

Find languages

1. Use latest staging or RC4 with a MySql server 5.6.6+
2. Set the database driver as "PDO (MySQL)" in global configuration.
3. Go to "Extensions" -> "Install languages".
4. Click "Find Languages".

Install language
1. Use latest staging or RC4 with a MySql server 5.6.6+
2. Set the database driver as "PDO (MySQL)" in global configuration.
3. Go to "Extensions" -> "Install languages".
4. Select a language and install it.

###### Note

If you don't have MySql 5.6.6+ you can emulate the error by setting the `sql_mode` in pdomydriver file. For that, add, after this line https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/driver/pdomysql.php#L149 the following code:
```php
$this->connection->query("SET @@SESSION.sql_mode = 'STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION';");
```

#### Expected result

Languages found / Language installed.

#### Actual result

Doesn't work:
![image](https://cloud.githubusercontent.com/assets/9630530/13856152/c56dcb58-ec6b-11e5-9905-8c5c64c91f62.png)

![image](https://cloud.githubusercontent.com/assets/9630530/13856291/6ae2a504-ec6c-11e5-81a9-d46b8548b16d.png)

#### System information (as much as possible)

Latest staging / RC 4.

**Comment by zero-24** [comment]
I guess we need to add that field here with default values:
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/installer/adapter/language.php#L286

I guess we need similiar fixes to the other install adapters.

**Comment by jppcel** [comment]
I guess the problem is with the table '_updates'.

I have modified the date atribute on database to can receive null values and the problem is solved, but i think the problem must be solved of other form...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9457">issues.joomla.org/joomla-cms/9457</a>.</sub>

**Comment by wilsonge** [comment]
Temporary fix has been to force strict mode off (to match mysql and mysqli drivers). But I want this issue to remain open so we can implement the "correct" fix one day

**Comment by andrepereiradasilva** [comment]
ok i made a PR for this install languages problems so i will close this.
Any other problems with "PDO (MySQL)" in strict mode shoudl have an issue.

**Comment by andrepereiradasilva** [comment]
PR is https://github.com/joomla/joomla-cms/pull/11763 BTW :smile:
