### ISSUE TITLE
Updating to Joomla 3.5 through the administrator panel is unnecessarily complicated

### ISSUE THREAD

**Issue by photodude** [joomla/joomla-cms#9459]
#### Steps to reproduce the issue
Download the Joomla update package
Try to update Joomla through the Administrator interface.
Extension manager no longer allows Core updates (3.5 something made this change, Noted in #9430 )
Joomla Update does not allow a file upload the way that the extensions manager does, only via the update channel or via a custom URL

This leaves FTP file transfer as the only other option to update with a downloaded Core update package

#### Expected result
Three methods for Updates
File upload via Joomla Update ( as was done with the extension manager)
Update via the update channel via Joomla Update
Update via FTP upload

Message in the Extention manager does not direct people to use the Joomla Update component if they tried to use the Extention manager for a core update as was done in #9430 

#### Actual result
Only able to update Update via the update channel or Update via FTP upload (file overwriting)

#### System information (as much as possible)
Any system

#### Additional comments
Although I understand the reasons for Joomla core updates through the extension manager being removed; because the Joomla updates component doesn't allow for updating via an uploaded package the way that the extensions manager does. This over complicates the update process. I feel being stuck with updates only through FTP file transfer or via the update channel, is an issue to consider fixing. There are likely many users are going to be reporting the issue noted in #9430 

Additionally not having a message to explain the update method change to users is going to frustrate and annoy  people.

**Comment by mbabker** [comment]
> Additionally not having a message to explain the update method change to users is going to frustrate and annoy people.

Welcome to a chicken or egg scenario.  The Extension Manager doesn't know what extension is being installed or updated until after `JInstaller::install()` finishes (success or fail).  Can't plug a message into existing releases because we can't time travel.  The best that can be done on this one point is just write documentation that 99% of folks will probably ignore anyway.

**Comment by bertmert** [comment]
Sorry for a off topic question here that was asked in a forum: When com_joomlaupdates fails and when update package was uploaded via FTP. Does database fix button remove outdated files from webspace? Will script.php start then? Thanks

**Comment by photodude** [comment]
@mbabker so with our current chicken or egg scenario: from say 3.4.8 and attempting to install the 3.5 core update package via the Extension Manager results in a installation failure; and we have no way to plug a message into say the RC5 package to advise users who attempt that unsupported path?

Could we put in a "dummy" component to the package who's only job is to push a message out to users?

I agree "99% of folks will probably ignore" any written documentation we try to implement to mitigate this issue and user annoyance.

**Comment by mbabker** [comment]
Nope.  If the code isn't in an existing 3.x release then it can't be relied on for the Extension Manager upgrade route.  That's kinda why the Extension Manager upgrade route was dropped to begin with.

**Comment by photodude** [comment]
Could we use an [XML Manifest file](https://docs.joomla.org/Manifest_files) to do nothing but trigger a install message in the Extension Manager?

**Comment by mbabker** [comment]
Nope.  If the installer finds a valid manifest file it's going to try and run the install/update routines, and in an absolute worst case scenario that's going to mean your filesystem is nuked.

**Comment by mbabker** [comment]
Whatever manifest you ship HAS to be the Joomla core manifest.  Otherwise you run the risk of screwing stuff up.  Then whatever idea you come up with when a valid manifest is found MUST function on existing 2.5 and 3.x releases.  With 3.4 it's possible to get to the extension script file and trigger a preflight routine, but that has no awareness of how the install/update was triggered, so whatever you do in the preflight is going to affect the update component too.

**Comment by photodude** [comment]
Past design choices.... What can you do...

**Comment by wilsonge** [comment]
You do https://github.com/joomla/joomla-cms/pull/9469 :D Closing in favour of @nikosdion 's solution :)

**Comment by photodude** [comment]
Thanks @wilsonge glad to see a solution to this.
