### ISSUE TITLE
a new user can register a DOB in the future

### ISSUE THREAD

**Issue by Twincarb** [joomla/joomla-cms#9460]
#### Steps to reproduce the issue
enable User - Profile plugin
create a new user in the front or back end and add a date of birth in the future
edit a user from the front end and set DOB to a date in the future

#### Expected result
an error saying that they can't register as they have not been born yet

#### Actual result
no error is passed registration is able to complete

#### System information (as much as possible)
J3.5 rc4 

#### Additional comments
as an additional feature it could be worth considering an option for a minimum age requirement based on DOB. Nothing stopping anyone from selecting an age older than they are though

**Comment by zero-24** [comment]
Than we need additional checks here:https://github.com/joomla/joomla-cms/blob/staging/plugins/user/profile/profile.php#L352

I think the dob in the future should be ckecked but the min register age maybe should be better a custom profile plugin. But i cant take that decision.

**Comment by brianteeman** [comment]
The user profile plugin was only ever intended as an example of how to use a plugin to extend the user registration form. If you need something more specific or advanced then it is best to create something yourself<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9460">issues.joomla.org/joomla-cms/9460</a>.</sub>

**Comment by alikon** [comment]
a simple stupid check that can be easily added is this:   (dob < current date)

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #9493
