### ISSUE TITLE
Installing Joomla on PDO with strict mode fails

### ISSUE THREAD

**Issue by wilsonge** [joomla/joomla-cms#9465]
```
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'joomla350.vxj80_tags' doesn't exist

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'joomla350.vxj80_content_types' doesn't exist

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'joomla350.vxj80_categories' doesn't exist

SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes
```

Tables that aren't being created:
- #__banners
- #__banner_clients
- #__categories
- #__content_types
- #__finder_links
- #__tags
- #__ucm_content
- #__users
- #__user_keys

**Comment by richard67** [comment]
Am preparing PR to solve that. Be patient, will take some 1 or 2 hours. Have to do something else before, PR itself will not be that big.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9465">issues.joomla.org/joomla-cms/9465</a>.</sub>

**Comment by richard67** [comment]
PR #9467 for this issue is ready.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9465">issues.joomla.org/joomla-cms/9465</a>.</sub>

**Comment by wilsonge** [comment]
Closing as we have a PR
