### ISSUE TITLE
System Info .txt file not a text/plain MIME

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#9470]
#### Steps to reproduce the issue

Download a system info .txt file from the backend

#### Expected result

.txt file is downloaded with standard `text/plain` MIME type

#### Actual result

.txt file is downloaded with `text/x-c++` MIME (at least in my case, haven't had a chance to push the RC onto another server for testing)

#### System information (as much as possible)

PHP Built On	Darwin Michaels-MacBook-Pro.local 14.5.0 Darwin Kernel Version 14.5.0: Tue Sep 1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64 x86_64
Database Version	5.6.29
Database Collation	utf8mb4_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.4
Web Server	Apache/2.4.16 (Unix) PHP/7.0.4 OpenSSL/0.9.8zg
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.5.0-rc Release Candidate [ Ember ] 10-March-2016 00:30 GMT (staging branch @ 06ea85a914654ba8d092e96c3b7993bad4d65a1d)
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

#### Additional comments

Also see https://github.com/joomla/jissues/issues/760.  Because we have additional file validations in place, .txt files not matching the "normal" text/plain MIME fail validation when being uploaded into the issue tracker which prevents these files from being attached through that interface.  This is also a PHP environmental quirk as some environments seem to convert it to the right MIME anyway.

**Comment by andrepereiradasilva** [comment]
Please test https://github.com/joomla/joomla-cms/pull/9471

**Comment by brianteeman** [comment]
Closed as e have a PR #9471 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9470">issues.joomla.org/joomla-cms/9470</a>.</sub>
