### ISSUE TITLE
Language files will not come into force when the Chinese language pack appears "QQ"

### ISSUE THREAD

**Issue by ztj1993** [joomla/joomla-cms#9475]
#### Steps to reproduce the issue
Open any language package, will be the language of the package in the "QQ" character, the language package will be a complete failure.
As will:
COM_BANNERS_BANNERS_HTML_UNPIN_BANNER="Unpinned banner"
Modify as:
COM_QQ_BANNERS_HTML_UNPIN_BANNER="Unpinned banner"
And then the entire language file is invalid.

The above comes from software translation!
#### System information (as much as possible)
joomla 3.4.8 CN
Windows 8

**Comment by zero-24** [comment]
The QQ is an reserved string in The language files as we do quoting with "_QQ_". So i would say this is expected behavior. I'm correct @infograf768 ?

**Comment by brianteeman** [comment]
yes that is correct

On 19 March 2016 at 08:16, zero-24 <notifications@github.com> wrote:

> The QQ is an reserved string in The language files as we do quoting with "
> *QQ*". So i would say this is expected behavior. I'm correct @infograf768
> <https://github.com/infograf768> ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9475#issuecomment-198667208>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Closed as expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9475">issues.joomla.org/joomla-cms/9475</a>.</sub>

**Comment by infograf768** [comment]
Yep, in fact it is not `QQ` but `_QQ_` which is used in our pregmatch or str_replace, therefore
`COM_QQSOMETHING_ETC` would not be an issue.
