### ISSUE TITLE
Flags break menu layout in admin

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9479]
#### Steps to reproduce the issue
Create a multilingual site and make sure you have a menu and default menu item for each language
Make sure that one of the menus has a long name

The menu width will expand to fit the TEXT of the menu as seen below
![k3pu](https://cloud.githubusercontent.com/assets/1296369/13898373/f90f8008-edc6-11e5-885d-c89b4c90c3a6.png)

But if the menu has a flag it does not increase the column width causing the issue below
![um0o](https://cloud.githubusercontent.com/assets/1296369/13898379/1259012e-edc7-11e5-8f7c-4d6ae111f0f6.png)

**Comment by MATsxm** [comment]
Able to reproduce - confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9479">issues.joomla.org/joomla-cms/9479</a>.</sub>

**Comment by andrepereiradasilva** [comment]
confirmed

**Comment by JoomliC** [comment]
This is strange, as i don't have this issue with 3.5.0-rc4 and firefox 10.6.8 on mac OS...
![menu_at_its_maximun_lenght_authorized](https://cloud.githubusercontent.com/assets/2385058/13902246/023a7874-ee42-11e5-973c-c652a61e918e.png)

Note: i have tested many different text for menu, and no issue. The screenshot is with the maximum characters limit set for a menu title...

**Comment by MATsxm** [comment]
Same here, no prob with Edge 25.105 & FF 45.0.1 but issue confirmed on Chrome 49.0.2623.87 m (then Yandex)

**Comment by brianteeman** [comment]
Its broken in safari as well ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9479">issues.joomla.org/joomla-cms/9479</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #9713<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9479">issues.joomla.org/joomla-cms/9479</a>.</sub>
