### ISSUE TITLE
Notice when discovering extensions

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#9480]
PHP Notice:  Undefined property: InstallerModelDiscover::$_message in ROOT/administrator/components/com_installer/controllers/discover.php on line 30

**Comment by brianteeman** [comment]
I could not replicate this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9480">issues.joomla.org/joomla-cms/9480</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Maybe @infograf768 has a newer mysql version (5.6.something) where strict mode is enabled by default in session parameters?

I remember this message from testing another PR from @wilsonge with PDO driver and code hack to force strict mode.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9480">issues.joomla.org/joomla-cms/9480</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i CAN reproduce this in latest staging

> PHP message: PHP Notice:  Undefined property: InstallerModelDiscover::$_message in /path/to/joomla-staging/administrator/components/com_installer/controllers/discover.php on line 30

**Comment by andrepereiradasilva** [comment]
And guess what, it was added by me https://github.com/joomla/joomla-cms/commit/f8b05718662eb20b4e92a3dd73a58580bd37f1f6

I will try to solve

**Comment by andrepereiradasilva** [comment]
please test https://github.com/joomla/joomla-cms/pull/9484

**Comment by brianteeman** [comment]
Closed
