### ISSUE TITLE
Multilingual status module postgres error

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9486]
Opening this module under postgres produces

>  0 ERROR: function max(boolean) does not exist LINE 1: SELECT u.name, count(cd.language) as counted, MAX(cd.languag... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts.SQL=SELECT u.name, count(cd.language) as counted, MAX(cd.language='*') as all_languages FROM #__users AS u LEFT JOIN #__contact_details AS cd ON cd.user_id=u.id LEFT JOIN #__languages as l on cd.language=l.lang_code WHERE EXISTS (SELECT * from #__content as c where c.created_by=u.id) AND (l.published=1 or cd.language='*') AND cd.published=1 GROUP BY u.id HAVING (counted !=3 OR all_languages=1) AND (counted !=1 OR all_languages=0)

**Comment by waader** [comment]
I stumbled over this before and described my foundings in #8673. But I think we need the experience of a really wizard here: @alikon - Sorry for calling you again.

**Comment by alikon** [comment]
no problem but i need some help 
cause that query is unreadable......
what is supposed to do the Multilingual status module ??

**Comment by waader** [comment]
It is a bit complicated: http://community.joomla.org/blogs/community/1501-171-new-multilanguage-status-module.html

**Comment by brianteeman** [comment]
Closing as a duplicate of #8673

**Comment by infograf768** [comment]
@alikon 
That query is checking that if there is a contact set to a specific user and to a specific content language, then there are also contacts set to the same user in all other content languages, as otherwise it breaks.

The module displays such possible issues.
A contact set to a specific user and to ALL languages is fine.
```
COM_LANGUAGES_MULTILANGSTATUS_CONTACTS_ERROR="Some of the contacts linked to the user <strong>%s</strong> are incorrect."
COM_LANGUAGES_MULTILANGSTATUS_CONTACTS_ERROR_TIP="Warning! A user/author should have only one contact to which is assigned language 'All' OR one contact for each published Content Language."
```

**Comment by alikon** [comment]
@infograf768 hoping that i've understand #9492 ;)
