### ISSUE TITLE
joomla 3.4.1 ridirector issues

### ISSUE THREAD

**Issue by moshiurshahin** [joomla/joomla-cms#9488]
#### Steps to reproduce the issue

I need you to FIX a Joomla log out redirect issue. I recently changed my primary domain and SSL from olddomain.uk to newdomain.com. My problem is - after logging out of Joomla, user is redirected to https://www.olddomain.uk. I checked Joomla3.x, .htaccess, tmp, log, cache, login plugins to be okay.

#### Expected result

not ridirect

#### Actual result

ridirected

#### System information (as much as possible)

I need you to FIX a Joomla log out redirect issue. I recently changed my primary domain and SSL from olddomain.uk to newdomain.com. My problem is - after logging out of Joomla, user is redirected to https://www.olddomain.uk. I checked Joomla3.x, .htaccess, tmp, log, cache, login plugins to be okay.

#### Additional comments

plz resolve this within 2 days urgent

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org

**Comment by moshiurshahin** [comment]
i signed in but not to know how to post and how to get answered
