### ISSUE TITLE
Error in article template

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#9491]
#### Steps to reproduce the issue

- Article for registered users
- Show Intro Text  -> Show
- Show "Read More"	-> Show
- Show Unauthorised Links -> Yes
- Article has "Read More Text" (alternative readmore text in Options...)

Non register user try to read article

#### Expected result
should work...

#### Actual result
`Notice: Undefined property: stdClass::$alternative_readmore in .....\com_content\views\article\tmpl\default.php on line 146`

Alternative Read More string **is not** displayed

#### System information (as much as possible)
J! 3.4.8

#### Additional comments
in \com_content\views\article\tmpl\default.php on line 146:
`elseif ($readmore = $this->item->alternative_readmore) :`
must be changed to
`elseif ($readmore = $attribs->alternative_readmore) :`

At first sight and IMHO, all the logic around that point seems to be quite twisted: methink `elseif` @ line 151 will never be executed. Same for `else` @ line 153

The "Read More Text" in options seems to be an alternative to the "Read more" string, not the intro text in article. Why all those `JHtml::_('string.truncate'` for the **title**? In case `$this->escape($this->item->title)` Am I missing something?

**Comment by smz** [comment]
... and where is the `endif` or `else` for `<?php if ($params->get('access-view')):?>` @ line 93?
... unsure... botched indentation... really difficult to read...   :-/

**Comment by smz** [comment]
Actually there is more to do, I guess:

Take line 89:
~~~
	<?php if (isset($urls) && ((!empty($urls->urls_position) && ($urls->urls_position == '0')) || ($params->get('urls_position') == '0' && empty($urls->urls_position)))
		|| (empty($urls->urls_position) && (!$params->get('urls_position')))) : ?>
~~~
that's totally borked: `urls_position` is not int the `$urls` object (_you only have links and text there..._) and good day trying to override the globally set urls_position with article's settings!

What I did in my override is to move the `$attribs=json_decode($this->item->attribs);` statement at the very top of the template and then:
~~~
foreach ($attribs as $key => $value)
{
	if (!empty($attribs->$key))
	{
		$params->set($key, $value);
	}
}
~~~

Done! From there on no need for twisted logic: just use `$params->get()`

line 89 becomes:
~~~
if (isset($urls) && $params->get('urls_position', 0) == 0)
~~~
easy!

line 146 (_the one giving the ugly_ `Undefined property`) becomes:
~~~
if ($params->get('alternative_readmore', '') == '')
~~~
problem solved.

And you'll be sure that the options you set at the article level will override the global settings (_isn't this what we want?_)

**Comment by smz** [comment]
Sorry, I just realized that the code I gave above:
~~~
foreach ($attribs as $key => $value)
{
    if (!empty($value))
    {
        $params->set($key, $value);
    }
}
~~~
**is wrong**

With that code you cannot override a global parameter set, say, to 1, with a local (_at the article level_) value of 0 as 0 is considered empty() and thus it doesn't have a chance of overriding the global parameter.

Correct (_hopefully_) code should be:
~~~
foreach ($attribs as $key => $value)
{
    if ($value != '')
    {
        $params->set($key, $value);
    }
}
~~~

**Comment by smz** [comment]
Sorry for bumping this issue which doesn't seems to be of much interest, but while writing my own overrides to fix this, I discovered something new which can itself be a separate issue with deeper consequences and for which I don't have a solution (_particularly at the overrides level_).

To better comprehend what I'm trying to explain, please have a look at the following (_incomplete_) logical combinations table which describes what happens when changing an article option ("show_author") at the global (component) level, at the article level and at the menu item (single article) level. I'm also adding what I can get at my override level (_"smz" column_)

T = Show
F = Hide
X = Use Global

Global | Article | Menu | Joomla | smz
------ | ------- | ---- | ------ | ---
T | X | X | T | T
T | X | F | F | F
T | **F** | X | **T** | F
T | F | T | T | F
F | X | X | F | F
F | **T** | X | **F** | T

In the above table you can clearly see that **what is declared at the article level is royally ignored by Joomla**.

But there is something more. IMHO the logical behaviour should be that the hierarchy be:

**Global < Article < Menu item**

That is, what is declared at the global level is overridden by what is declared at the article level and this is overridden by what is declared at the menu item level.

The problem is that the "_article level parameters override logic_" is performed in the article **template** (_this is how it goes today_), but once we are inside article templates what is defined at the global level has already been overridden by what is declared at the menu item level, and the best we can achieve is to override this already combined parameter with what is declared at the article level (_which is what I'm achieving in my column "smz"_), and hence the hierarchy will be:

**Global < Menu Item < Article**

Questions are:
* Is this a bug?
* Should it be fixed?
* is the "**Global < Menu Item < Article**" hierarchy acceptable?
* Are there (_sure there are_...) B/C issues to address
* Could possible differences in behaviour be addressed by the introduction of a new global parameter (Old/New behaviour)?

**Comment by smz** [comment]
Just in case anybody's reading, I understood that although the problem **does exist** (_try the "Show author" thing above, if you are interested_), this (_I mean the article template_) is not the place where the issue must be solved.

The solution to the problem belongs to the view, where already parameters (_options_) are merged, but where something evidently something goes wrong...

**Comment by smz** [comment]
#9801 should solve the parameters hierarchy issue.

The template is still to be fixed for the "_Undefined property_" issue.

**Comment by smz** [comment]
So the _"hierarchy_" thing is now being discussed in #9801.

This leaves us with the remaining issues concerning `/com_content/views/article/tmpl/default.php`:

**1)** there is an "_Notice: Undefined property: stdClass::$alternative_readmore_" error generated at line 150 (_it was 146 at J! 3.4.8_): this is due to using `$this->item->alternative_readmore`, which is not set: that thing is today in `$attribs`, and not in `$this->item`.
IMHO we shouldn't need to use $attribs (_and hence json_decode it from_ `$this->item->attribs`) in the template. That `alternative_readmore` belongs to the params, I think, and should be ready available to template developers, but this is another story, I guess...

**2)** Line 91 (_the URLs thing_) is broken, in many senses: the logic is wrong and, beside that, `urls_position` is not to be found into the `$urls` object (_you only have_ `links` _and_ `text` _there, but not_ `url_position`)

Now, I will be **most grateful** if somebody else could go on fixing the above for a couple of reasons:
* Next week I'll be very busy and probably don't have the time to care about that too much.

* I'm quite senior, 61, my sight is not as it used to be and in templates I'm loosing myself between the scores of `<?php ... ?>`. Due to that I write my templates differently (_see:_ https://github.com/smz/tpl_pantarei _if interested_). For me putting my hands in standard Joomla templates is a royal pain in the back, and hence my request for somebody else to take over that...

Thanks!

**Comment by brianteeman** [comment]
Closed as we have a PR to resolve the alternative readmore text #11473<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9491">issues.joomla.org/joomla-cms/9491</a>.</sub>
