### ISSUE TITLE
Can't login as admin after failed update 

### ISSUE THREAD

**Issue by eqariu** [joomla/joomla-cms#9494]
Hello, 

I was updating from joomla version 2.5 but intenet cable was interrupted at 10%. Now it won't allow back end login and shows a completely blank page without any admin panel at all. but website front end is working. What am I gonna do? 

Thank you. 

David

**Comment by eqariu** [comment]
I was updating to joomla 3.1 by the way.

**Comment by nikitadhiman** [comment]
Even if the the update was interrupted, the admin panel would be visible showing the message that the update was not successful. If the frontend of the website is visible don't worry everything is completely fine. Check your connection and try again!

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org

**Comment by eqariu** [comment]
Thanks Dhiman for reply. 


The issue is not resolved even when internet resumed. Even on a different device. Thank you. 


Regards, 

David Kariuki. 



From: Nikita Dhiman

Sent: Sunday 20 March 3:02 pm

Subject: Re: [joomla-cms] Can't login as admin after failed update  (#9494)

To: joomla/joomla-cms

Cc: eqariu



Even if the the update was interrupted, the admin panel would be visible showing the message that the update was not successful. If the frontend of the website is visible don't worry everything is completely fine. Check your connection and try again!

**Comment by eqariu** [comment]
Thanks Brian for reply.


The issue is not resolved even when internet resumed. Even on a different device. Thank you.


Regards, 

David Kariuki.




Regards, 

David Kariuki. 



From: Brian Teeman

Sent: Sunday 20 March 3:03 pm

Subject: Re: [joomla-cms] Can't login as admin after failed update  (#9494)

To: joomla/joomla-cms

Cc: eqariu



Please use the forum for support http://forum.joomla.org
