### ISSUE TITLE
Pagination override not working on main page

### ISSUE THREAD

**Issue by QkiZMR** [joomla/joomla-cms#9495]
#### Steps to reproduce the issue
Pagination override not working on main page:
www.greencookies.pl/index.php?template=greencookies-mobile
but works ok on category view:
www.greencookies.pl/ciasta-i-desery/ciasteczka.html?template=greencookies-mobile&start=24Pagination override not working on main page:
www.greencookies.pl/index.php?template=greencookies-mobile
but works ok on category view:
www.greencookies.pl/ciasta-i-desery/ciasteczka.html?template=greencookies-mobile&start=24

#### Expected result
I want to work pagination override on all pages.I want to work pagination override on all pages.

#### Actual result
Pagination not working on main page.

#### System information (as much as possible)
Linux, Apache 2.4.7, PHP 5.5.9, MySQL 5.6.28, Joomla 3.4.8

#### Additional comments
Pagination override attached
[pagination.txt](https://github.com/joomla/joomla-cms/files/181267/pagination.txt)

**Comment by brianteeman** [comment]
This tracker is for bugs and features in the core of Joomla. For support on your specific site and your customisation please use the forum http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9495">issues.joomla.org/joomla-cms/9495</a>.</sub>

**Comment by QkiZMR** [comment]
But it is bug.

**Comment by QkiZMR** [comment]
fucker

**Comment by Kubik-Rubik** [comment]
Removed insult, issue locked!
