### ISSUE TITLE
The tld param has no effect for email validation

### ISSUE THREAD

**Issue by dziudek** [joomla/joomla-cms#9500]
The tld param for the email field form validation is not working - after adding it to the form XML there is no change. The issue is caused by fact that if even the tld param exists the assigned regex is exactly the same as the original regexp used for the email validation.

I've also created pull reqest for this issue.

**Comment by brianteeman** [comment]
Hi

You dont need to create an Issue and a Pull request. When you create a PR it automatically creates an entry on the issue tracker
