### ISSUE TITLE
2 different error messages for the same action in frontend or backend while registration

### ISSUE THREAD

**Issue by MATsxm** [joomla/joomla-cms#9502]
#### Steps to reproduce the issue

first apply #9493 to forbid a dob in the future while the User registration.
enable the plugin: User - Profile
and set date of birth as `Required`
- Try to register a new user on **backend** with a dob in the future
- Try to register a new user on **frontend** with a dob in the future
#### Expected result

Having for both cases (backend and frontend) the same error message.
#### Actual result

Error messages are different if you register a new user on frontend  or backend. 
On backend we have an **Error** `class="alert alert-error"`
and on frontend we have a Warning `class="alert"`.
**Backend**
![screen shot 2016-03-21 at 07 27 10](https://issues.joomla.org/uploads/1/0c544ff429c7756f5705ac9517707bb9.png)
**Frontend**
![screen shot 2016-03-21 at 07 27 37](https://issues.joomla.org/uploads/1/d8cd08783f24caa062d61851e7bc6e46.png)
#### System information (as much as possible)

3.5.0-rc4 **WITH** #9493 applied

**Comment by alikon** [comment]
I can confirm
...should be handled better from js side ?...

**Comment by franz-wohlkoenig** [comment]
Issue persist on 3.7-staging.

**Comment by GeraintEdwards** [comment]
I am looking at this at JAB 2017

**Comment by ghost** [comment]
Status is set on "Needs Review".

**Comment by rdeutz** [comment]
Let us use error in back and frontend, back to pending

**Comment by brianteeman** [comment]
closed see #19142
