### ISSUE TITLE
Post 3.5 upgrade schema issues

### ISSUE THREAD

**Issue by mbabker** [joomla/joomla-cms#9509]
- [ ] The `#__users.name` column is not migrated from 255 characters to 400 characters on upgrade to 3.5.0
- [ ] The `#__users` `idx_name` index is not resized to a max length of 100 characters on upgrade to 3.5.0
- [ ] The `#__menu` `idx_path` index is not resized to a max length of 100 characters on upgrade to 3.5.0
- [ ] The `#__user_keys` `user_id` index is not resized to a max length of 100 characters on upgrade to 3.5.0

**Comment by richard67** [comment]
@wilsonge Was something we wanted to discuss with Eli, if we shall enlarge more columns to avoid data loss than those which have some key (index) on it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9509">issues.joomla.org/joomla-cms/9509</a>.</sub>

**Comment by mbabker** [comment]
Well this one's inconsistent because the new install schema has the column length at 400 characters so I'm assuming in all the refactorings a change was made in one place and forgotten in the other.  To me it's no big deal but should be sorted for consistency.

**Comment by richard67** [comment]
@mbabker Oh, well then that's an old mistake. But I was sure I found them all, so is a bit my fault, too.

Did you find any other insonsistencies?

If so, let me know, and if not, let me know, too.

And do you want to make the PR? Or shall I do it then as soon as I got feedback from you?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9509">issues.joomla.org/joomla-cms/9509</a>.</sub>

**Comment by mbabker** [comment]
That was the only one I noticed looking explicitly after a forum post and confirming against an upgraded `joomla.org` property.

**Comment by mbabker** [comment]
@richard67 I updated the issue description with all the issues @wilsonge and I found from one user's database.  The following queries need to be run:

```sql
ALTER TABLE `#__menu` DROP KEY `idx_path`;
ALTER TABLE `#__menu` ADD KEY `idx_path` (`path`(100));
ALTER TABLE `#__users` DROP KEY `idx_name`;
ALTER TABLE `#__users` ADD KEY `idx_name` (`name`(100));
ALTER TABLE `#__user_keys` DROP KEY `series`;
ALTER TABLE `#__user_keys` ADD UNIQUE KEY `series` (`series`(100));
ALTER TABLE `#__user_keys` DROP KEY `series_2`;
ALTER TABLE `#__user_keys` ADD UNIQUE KEY `series_2` (`series`(100));
ALTER TABLE `#__user_keys` DROP KEY `series_3`;
ALTER TABLE `#__user_keys` ADD UNIQUE KEY `series_3` (`series`(100));
ALTER TABLE `#__user_keys` DROP KEY `user_id`;
ALTER TABLE `#__user_keys` ADD KEY `user_id` (`user_id`(100));
```

**Comment by mbabker** [comment]
And just to close the comments before I head off, on at least one `joomla.org` property I updated the indexes that needed to have lengths changed automatically downgraded themselves to a max length of 191 characters.  So it appears this too is a MySQL environmental thing that can be configured as the `joomla.org` properties upgraded OK but this one user's didn't.

**Comment by richard67** [comment]
Thanks Michael, with this info I can make a PR soon.

**Comment by richard67** [comment]
PR is #9510 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9509">issues.joomla.org/joomla-cms/9509</a>.</sub>

**Comment by wilsonge** [comment]
Closing as we have a PR

**Comment by richard67** [comment]
New PR is #9549 in replacement for #9510 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9509">issues.joomla.org/joomla-cms/9509</a>.</sub>

**Comment by richard67** [comment]
New PR is #9590 in replacement for #9549 , which before replaced #9510 .
