### ISSUE TITLE
Regression: Trying to use weblinks after upgrade to 3.5.0

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#9513]
I get here issues with weblinks on a legacy site: 

Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' SQL=SELECT COUNT() FROM `#weblinks` AS a LEFT JOIN `#languages` AS l ON l.lang_code = a.language LEFT JOIN #__users AS uc ON uc.id=a.checked_out LEFT JOIN #__viewlevels AS ag ON ag.id = a.access LEFT JOIN #__categories AS c ON c.id = a.catid WHERE (a.state IN (0, 1)) Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' SQL=SELECT a.id, a.title, a.alias, a.checked_out, a.checked_out_time, a.catid,a.hits, a.state, a.access, a.ordering, a.language, a.publish_up, a.publish_down,l.title AS language_title,uc.name AS editor,ag.title AS access_level,c.title AS category_title FROM `#weblinks` AS a LEFT JOIN `#languages` AS l ON l.lang_code = a.language LEFT JOIN #__users AS uc ON uc.id=a.checked_out LEFT JOIN #__viewlevels AS ag ON ag.id = a.access LEFT JOIN #__categories AS c ON c.id = a.catid WHERE (a.state IN (0, 1)) ORDER BY a.title asc LIMIT 0, 100 Illegal mix of collations (utf8mb4_unicode_ci,IMPLICIT) and (utf8mb4_general_ci,IMPLICIT) for operation '=' SQL=SELECT COUNT() FROM `#weblinks` AS a LEFT JOIN `#languages` AS l ON l.lang_code = a.language LEFT JOIN #__users AS uc ON uc.id=a.checked_out LEFT JOIN #__viewlevels AS ag ON ag.id = a.access LEFT JOIN #__categories AS c ON c.id = a.catid WHERE (a.state IN (0, 1))

**Comment by brianteeman** [comment]
I thought there was an update for weblinks to specifically address this? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9513">issues.joomla.org/joomla-cms/9513</a>.</sub>

**Comment by wilsonge** [comment]
There wasn't a web links fi . But this was what we released RC4 specifically to deal with. Please try again JM (commit that should have fixed this issue: https://github.com/joomla/joomla-cms/commit/6ac3dc4376a314e6aabd457c761936ba4ca2f79a) - note the language code should have a utf8mb4_bin not a utf8mb4_general_ci collation

**Comment by brianteeman** [comment]
sorry that I was confused

**Comment by wilsonge** [comment]
It's ok! I wasn't having a go at you!

**Comment by infograf768** [comment]
Yes, indeed. @wilsonge is correct.

I ran the query 
`ALTER TABLE `#__languages` MODIFY `lang_code` char(7) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL;` dn it is fixed.

closing.
