### ISSUE TITLE
Can't access the user object after upgrading to 3.5--all my code is broken

### ISSUE THREAD

**Issue by mortonsean** [joomla/joomla-cms#9514]
#### Steps to reproduce the issue
Using php in an iframe.  I was previously able to get the user id with

define( '_JEXEC', 1 );
define( '_VALID_MOS', 1 );
define( 'JPATH_BASE', realpath(dirname(__FILE__).'/..'));
define( 'DS', DIRECTORY_SEPARATOR );
require_once ( JPATH_BASE .DS.'includes'.DS.'defines.php' );
require_once ( JPATH_BASE .DS.'includes'.DS.'framework.php' );
$mainframe =& JFactory::getApplication('site');
$mainframe->initialise();
$session =& JFactory::getSession();
$user = JFactory::getUser();
 
but since upgrading, I get a "Failed to start the session because headers have already been sent" on pages that were working fine before.

**Comment by wilsonge** [comment]
Can you test this https://github.com/joomla/joomla-cms/commit/943f2e9197a412bf7295bb50ff94988e855c8805 fix please? I think it's a session bug we just fixed

**Comment by andrepereiradasilva** [comment]
since the code posted seems cropped by github, just to test, tried 3.5.0 without any patch with the following code and it worked.

To test, i created a file in the joomla root folder `test.php` with the following content
```php
<?php
define( '_JEXEC', 1 );
define( '_VALID_MOS', 1 );
define( 'JPATH_BASE', realpath(dirname(__FILE__)));
define( 'DS', DIRECTORY_SEPARATOR );
require_once ( JPATH_BASE .DS.'includes'.DS.'defines.php' );
require_once ( JPATH_BASE .DS.'includes'.DS.'framework.php' );
$mainframe = JFactory::getApplication('site');
$mainframe->initialise();
$session = JFactory::getSession();
$user = JFactory::getUser();
// dump values
var_dump($session);
var_dump($user);
?>
```

**Comment by brianteeman** [comment]
I am closing this at this time due to lack of response<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9514">issues.joomla.org/joomla-cms/9514</a>.</sub>

**Comment by wilsonge** [comment]
The answer though is you need to call $session->initialise
