### ISSUE TITLE
[3.5.0] Related Articles Module Fatal error

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#9518]
#### Steps to reproduce the issue

This has posted in the forum and was able to reproduce it.
See http://forum.joomla.org/viewtopic.php?f=710&t=913801

Some components give errors if a Related article module is enabled.

Enable a related items modules on all pages.
For instance enable search component.
Try to do a search in the frontend.

#### Expected result

Works fine.

#### Actual result

500 error with fatal error
```
Fatal error: Uncaught Error: Call to a member function setState() on boolean in /path/to/joomla/modules/mod_related_items/helper.php:44 
```

#### System information (as much as possible)

Joomla 3.5.0

##### Temporary solution to prevent fatal errors

Unpublish Related Articles Module.

##### Call stack

1	JApplicationCms->execute()	/path/to/joomla/index.php:49
2	JApplicationSite->render()	/path/to/joomla/libraries/cms/application/cms.php:263
3	JApplicationCms->render()	/path/to/joomla/libraries/cms/application/site.php:745
4	JDocumentHtml->render()	/path/to/joomla/libraries/cms/application/cms.php:1068
5	JDocumentHtml->_renderTemplate()	/path/to/joomla/libraries/joomla/document/html.php:477
6	JDocumentHtml->getBuffer()	/path/to/joomla/libraries/joomla/document/html.php:697
7	JDocumentRendererHtmlModules->render()	/path/to/joomla/libraries/joomla/document/html.php:411
8	JDocumentRendererHtmlModule->render()	/path/to/joomla/libraries/joomla/document/renderer/html/modules.php:42
9	JModuleHelper::renderModule()	/path/to/joomla/libraries/joomla/document/renderer/html/module.php:93
10	include()	/path/to/joomla/libraries/cms/module/helper.php:190
11	JModuleHelper::moduleCache()	/path/to/joomla/modules/mod_related_items/mod_related_items.php:22
12	JCacheControllerCallback->get()	/path/to/joomla/libraries/cms/module/helper.php:561
13	ModRelatedItemsHelper::getList()	/path/to/joomla/libraries/joomla/cache/controller/callback.php:157

**Comment by brianteeman** [comment]
I can confirm this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9518">issues.joomla.org/joomla-cms/9518</a>.</sub>

**Comment by brianteeman** [comment]
The contact component was the one it failed on for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9518">issues.joomla.org/joomla-cms/9518</a>.</sub>

**Comment by joomdonation** [comment]
The module should only be showed on article detail page, correct? Quick look at the module code, I think most of the code in ModRelatedItemsHelper should be moved into if block https://github.com/joomla/joomla-cms/blob/staging/modules/mod_related_items/helper.php#L58

Doing that should prevent the error.

**Comment by brianteeman** [comment]
Please test #9519<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9518">issues.joomla.org/joomla-cms/9518</a>.</sub>
