### ISSUE TITLE
Additional module classes doesn't show - quick fix

### ISSUE THREAD

**Issue by jerndorff** [joomla/joomla-cms#9522]
#### Steps to reproduce the issue
1) Install J3.5 in a PHP 5.3 environment
2) Install the plugin nnbootstrapparams (https://github.com/nn-medienagentur/plg_system_nnbootstrapparams) 
3) Install a bootstrapped template like masterBootstrap (http://www.masterbootstrap.com)
4) Add a few modules to the feature position and play with the bootstrap params in each module.

#### Expected result
In J3.4-8 you will see the additional bootstrap classes being added to each module rendering.

#### Actual result
In J3.5 none of the additional boostrap classes are being shown.

#### Quick Fix (temp. hack)
In libraries > joomla > document > document.php

change line 999 from:
**if (!class_exists($class))**
to
**if (class_exists($class))**

**Comment by mbabker** [comment]
That's not a valid fix.  Joomla 3.5 restructured the JDocument internal classes and the renderer loading function here gives preference to the new convention over the old.  Your change forces it to always use the old convention which would defeat the point of the change to begin with.

**Comment by jerndorff** [comment]
Thank you for pointing that out. The quick (and dirty) fix solved the issue for me at the moment, however I would love to see a proper fix to solve the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9522">issues.joomla.org/joomla-cms/9522</a>.</sub>

**Comment by brianteeman** [comment]
Rest priority according to docs https://docs.joomla.org/Priority<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9522">issues.joomla.org/joomla-cms/9522</a>.</sub>

**Comment by jerndorff** [comment]
Thank you, Brian.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9522">issues.joomla.org/joomla-cms/9522</a>.</sub>

**Comment by impleri** [comment]
Hrm. This does break BC.

A non-core dirty fix is changing the class name in NNBootstrapparams to JDocumentRendererHtmlModules and changing plgSystemNNBootstrapparams::onAfterInitialise to register JDocumentRendererHtmlModules instead of JDocumentRendererModules.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9522">issues.joomla.org/joomla-cms/9522</a>.</sub>

**Comment by jerndorff** [comment]
Thank you, impleri! Problem solved :)
