### ISSUE TITLE
Clear button (for any search) in Joomla back-end UI does not work in Chromium runing on Ubuntu

### ISSUE THREAD

**Issue by MgsGH** [joomla/joomla-cms#9527]
#### Steps to reproduce the issue
Use Chromium running on Ubuntu for accessing Joomla back-end.
Go to a search, for instance "articles". Enter something in the search field. 
Click the clear button, the text disappears - for a little while, but it is reloaded again

#### Expected result
An empty search box when clicking "Clear".

#### Actual result
Click the clear button, the text disappears - for a little while, but it is reloaded again

#### System information (as much as possible)
Ubunto 15.10 + Chromium Version 48.0.2564.116 Ubuntu 15.10 (64-bit)

#### Additional comments
Works fine with FF. Known Chromium problem??

**Comment by brianteeman** [comment]
Which version of Joomla? Is this a new install?

**Comment by MgsGH** [comment]
Hi,

Yes, the newest, the one that just came. But I had the same issue with the
previous version, 3.4.8 (?).

I, sort of, expected it to be solved by the new version, but no luck.

I could be on the Chromium side (?) I have not tested on Windows+Chrome.

/Magnus

**Comment by brianteeman** [comment]
If you never reported it then it wont have magically been fixed.
http://magazine.joomla.org/issues/issue-sept-2015/item/2837-did-they-fix-it-yet

I dont have windows here myself but everything works perfectly on chrome
under os x

**Comment by MgsGH** [comment]
Hi,

Same issue on windows 10 + Chrome. /Mgs

**Comment by MgsGH** [comment]
Hi - granted. But, I am quite new to Joomla (but not to CMSes and IS
general) so I assumed someone else must have noticed. Yes - someone else' s
problem - yet again... /Mgs

**Comment by brianteeman** [comment]
Is this on multiple sites or just your own site?

Obviously we want to resolve a bug but we have to be able to replicate it
and with no other reports of it to date then it does sound strange

**Comment by andrepereiradasilva** [comment]
> Same issue on windows 10 + Chrome. /Mgs

Can't reproduce this on Windows 10 + chrome

Did you refreshed the the browser cache?

**Comment by brianteeman** [comment]
I am wondering if there is some extension installed which is breaking things. Doesnt seem logical but if it was a browser issue we would be able to replicate it and have a LOT of reports<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9527">issues.joomla.org/joomla-cms/9527</a>.</sub>

**Comment by MgsGH** [comment]
Brian,

It got late here in Rome yesterday..

I have two sites on two different Joomla installations. One clean
installation, one with a few extensions.

I get the same issue on both :-/

This URL is only bought and Joomla installed:
http://www.birdobservatories.com/administrator/index.php

I have created a user "Brian".

Pwd next mail.

Give it a try.

/Mgs

**Comment by MgsGH** [comment]
joomlaBUG

**Comment by brianteeman** [comment]
Updated posts to remove username and password

**Comment by brianteeman** [comment]
As can be seen from the movie below I could not repeat the problem - or have i misunderstood you
![screen shot 2016-03-23 at 04 37 11](https://issues.joomla.org/uploads/1/360eedb0ece66cc99024f5f52770f034.gif)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9527">issues.joomla.org/joomla-cms/9527</a>.</sub>

**Comment by MgsGH** [comment]
Hi,

I have a video here, *showing* the problem:  https://www.dropbox.com/s/uik9ifyg9wyojre/061.MOV?dl=0

i am doing the same. 

/Mgs

**Comment by brianteeman** [comment]
Sorry I dont have a clue

By using other browsers you have narrowed the issue down to chrome
By other users with chrome not being able to replicate this on your site and using the same chrome browser we must conclude that the issue is somewhere within your chrome browser or local configuration. Perhaps a browser plugin?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9527">issues.joomla.org/joomla-cms/9527</a>.</sub>

**Comment by GABBAR1947** [comment]
@MgsGH I'm unable to replicate this issue as well. I tried it on chromium + ubuntu 15.10 and with the latest joomla version. This video shows the absence of any such issue. 
[(https://drive.google.com/file/d/0B_XvC-YHt047OElXUGdxMTJ5akk/view?usp=sharing)]
It might be a faulty extension that might be creating the problem on your system specifically. Do let me know if there is something that I'm missing.

**Comment by izharaazmi** [comment]
@MgsGH See #8421 and let us know if this the same. If so, it has a workaround mentioned too.

**Comment by brianteeman** [comment]
I dont think it can be the same issue as I was not able to replicate it from my computer**_ on the same site _**that @MgsGH was having issues with

**Comment by MgsGH** [comment]
Izhar,

Many thanks. This indeed sounds as the same issue.

/Magnus

**Comment by brianteeman** [comment]
Closed - nothing to be done in core<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9527">issues.joomla.org/joomla-cms/9527</a>.</sub>
