### ISSUE TITLE
Actualizar de 3.4.8 a 3.5

### ISSUE THREAD

**Issue by vampi2004** [joomla/joomla-cms#9529]
#### Steps to reproduce the issue
He actualizado de la 3.4.8 a 3.5. Instalación correcta. La parte de administración la veo correctamente. La web no sale nada.
I upgraded from 3.4.8 to 3.5. proper installation. The administration part I see correctly. The web nothing comes out, all white.

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org
