### ISSUE TITLE
Site broken with 3.5.1-dev staging due to B/C breaking commit for CLI Session fix

### ISSUE THREAD

**Issue by beat** [joomla/joomla-cms#9533]
# WARNING: 3.5.1-dev current git staging breaks sites:

I have my localhost test installation with Joomla git and CB 2.0.14 and a few CB plugin is working fine with Joomla 3.5.0 tag checkout, but switching to master I get blank page with:

Error displaying the error page: Application Instantiation Error: Application Instantiation Error

#### Expected result

Working website

#### Actual result

`Error displaying the error page: Application Instantiation Error: Application Instantiation Error`

in front-end and admin area.

#### System information (as much as possible)

PHP 7.0.4, Mysql 5.5, git staging branch

#### Additional comments

Reverting this commit https://github.com/joomla/joomla-cms/commit/943f2e9197a412bf7295bb50ff94988e855c8805 fixes my issue.

I have not yet debugged further the reason, as I'm waiting for comment from @mbabker on the commit thread.

However, as I see Joomla PLT merging PRs too quickly and twitter 3.5.1 noises, I wonder if there is a panic mode and would like to warn that a rush release with that commit would break many sites.

**Comment by wilsonge** [comment]
Duplicate of https://github.com/joomla/joomla-cms/issues/9520
