### ISSUE TITLE
I updated to Joomla 3.5 My PostgreSQL site had an error message

### ISSUE THREAD

**Issue by topazeagle** [joomla/joomla-cms#9537]
#### Steps to reproduce the issue

Upgrade to Joomla 3.5

#### Expected result

Successful upgrade

#### Actual result

ERROR: syntax error at or near ""#__contentitem_tag_map_idx_tag"" LINE 1: ALTER TABLE "#__contentitem_tag_map" DROP INDEX "#__conten... ^SQL=ALTER TABLE "#__contentitem_tag_map" DROP INDEX "#__contentitem_tag_map_idx_tag";

The system tells me that it has upgraded to Joomla 3.5. When I use the site it seems to work. All pages show without crashing. 

I did not get the message about submitting information to Joomla (once always etc) which I got from my mariaDB site. 

[systeminfo-2016-03-23T05-31-06+00-00.txt](https://github.com/joomla/joomla-cms/files/185440/systeminfo-2016-03-23T05-31-06.00-00.txt)
[JoomlaUpgradeERror.docx](https://github.com/joomla/joomla-cms/files/185442/JoomlaUpgradeERror.docx)

#### System information (as much as possible)

See attached files.

**Comment by waader** [comment]
Confirmed. I made a fresh joomla 3.4.8 installation, updated to 3.5 and get the same error you are reporting.

In file 3.5.0-2015-10-26.sql there are two alter table commands
ALTER TABLE "#__contentitem_tag_map" DROP INDEX "#__contentitem_tag_map_idx_tag";
ALTER TABLE "#__contentitem_tag_map" DROP INDEX "#__contentitem_tag_map_idx_type";

When changed to

DROP INDEX "#__contentitem_tag_map_idx_tag";
DROP INDEX "#__contentitem_tag_map_idx_type";

the should do the job.

**Comment by waader** [comment]
@alikon: Am I right? My problem here: I don´t know how to test this other than putting the commands in phpPgAdmin.

**Comment by alikon** [comment]
@waader follow #9602 for how to test

**Comment by brianteeman** [comment]
Closed as we have a PR #9602<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9537">issues.joomla.org/joomla-cms/9537</a>.</sub>
