### ISSUE TITLE
PostgreSQL: Warning: Database is not up to date!

### ISSUE THREAD

**Issue by waader** [joomla/joomla-cms#9538]
#### Steps to reproduce the issue
Make a fresh installation with Joomla 3.5 and check in the backend (Extensions > Manage > Database) whether there are any database problems.

#### Expected result
No problems are reported.

#### Actual result
4 Problems are found:

    Table 'az4v2_contentitem_tag_map' does not have index 'az4v2_contentitem_tag_map_idx_tag_name'. (From file 3.1.0.sql.)
    Table 'az4v2_redirect_links' does not have column 'old_url' with type varchar. (From file 3.5.0-2016-03-01.sql.)
    Table 'az4v2_redirect_links' does not have column 'new_url' with type varchar. (From file 3.5.0-2016-03-01.sql.)
    Table 'az4v2_redirect_links' does not have column 'referer' with type varchar. (From file 3.5.0-2016-03-01.sql.)

The problem with the varchar fields in __redirect_links can be easily mitigated. Just replace VARCHAR with character varying(2048). But I don´t know how to deal with the index. Pressing the fix button the index is applied but we don´t need the index anymore. Deleting the line in 3.1.0.sql is probably the wrong resolution.

#### Additional comments
The

**Comment by brianteeman** [comment]
I can confirm this - sorry for not spotting it in earlier tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9538">issues.joomla.org/joomla-cms/9538</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR for testing see #9595<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9538">issues.joomla.org/joomla-cms/9538</a>.</sub>
