### ISSUE TITLE
com_redirect admin doesn't remember sort state

### ISSUE THREAD

**Issue by waveywhite** [joomla/joomla-cms#9539]
#### Steps to reproduce the issue

1. In admin, go to the redirect component (Components > Redirect)
2. Make sure there are a few redirects in place, if not create a few
3. Click on the date twice to sort by most recent first
4. Click on New to create a new redirect and give it a URL which would be towards the end of alphabetical sorting, such as /xxx
5. Click Save & Close.

You will now return to the redirect component but the sort order will no longer be most recent first

#### Expected result

The sort order state should be remembered so the new URL should be first

#### Actual result

The sort order state returns to the default and the new URL is sorted alphabetically.

#### System information (as much as possible)

Joomla 3.5 on Ubuntu 14.04 LTS, Apache 2.4.7, PHP 5.5.9, Mysqli database drivers

**Comment by bertmert** [comment]
confirmed

**Comment by andrepereiradasilva** [comment]
i can correct this one when i have time (it can take a while).

**Comment by andrepereiradasilva** [comment]
please test https://github.com/joomla/joomla-cms/pull/9971

@brianteeman you can close this

**Comment by brianteeman** [comment]
Closed as requested
