### ISSUE TITLE
Warning: Database could not be updated

### ISSUE THREAD

**Issue by Bonitto** [joomla/joomla-cms#9543]
#### Steps to reproduce the issue
I had decoupled some of the joomla components no longer needed such as com_contacts, com_newsfeed etc so the columns the installer is looking for no longer exist. When I try to use the Fix option under Databases, I get an error Table 'icandywe_dev.#__newsfeeds' doesn't exist SQL=ALTER TABLE `#__newsfeeds` DROP COLUMN `filename`;![screen shot 2016-03-23 at 07 44 57](https://issues.joomla.org/uploads/1/6e66c8225865578cc7284a6ed16756af.png)

#### System information (as much as possible)
php: Linux serv01.us12.siteground.us 3.12.18-clouder0 #1 SMP Wed Jan 20 00:00:07 EET 2016 x86_64
dbversion: 5.6.28-76.1-log
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 7.0.4
server: Apache
sapi_name: cgi-fcgi
version: Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.116 Safari/537.36

#### Additional comments

![screen shot 2016-03-23 at 07 44 57](https://issues.joomla.org/uploads/1/82757dfd672b6e9e793559d190c755b6.png)

**Comment by mbabker** [comment]
See #8691<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9543">issues.joomla.org/joomla-cms/9543</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i think, you can't interrely decouple extensions as they will be added in an update and those kidn of problems can occur.
if i'm not mistaken, only com_weblinks has been decoupled from the core.

**Comment by Bonitto** [comment]
Ah, understood and thanks for the prompt reply. My question then is what is the fix to either add the tables back or is there another way to allow the database to be upgraded with these tables missing? 

Also on another note, if these are required core extensions why are users given the option to remove them if the proper checks have not been put in place to account for this? Not really pointing fingers but I would think more of these issues will arise from users who wish to remove the unused extensions.

**Comment by mbabker** [comment]
The protected flag for extensions is only designed to be used for extensions which if removed would cause the CMS to catastrophically fail.  com_newsfeeds isn't one of those.  It's kind of a "damned if you do, damned if you don't" thing.  You can remove it and things work fine until an update comes out with schema changes (and that exposes deeper issues with the CMS' lack of a good schema management API).

To put the table back, before updating copy the relevant schema from `https://github.com/joomla/joomla-cms/blob/<version>/installation/sql/<database_type>/joomla.sql` for the version you're upgrading from, then run the update.  That way ensures the update runs in full without error.  Post update, if you just put the tables back it should be fine.
