### ISSUE TITLE
reCaptcha breaks after update from 3.4.8 to 3.5 when in custom form

### ISSUE THREAD

**Issue by elioair** [joomla/joomla-cms#9544]
#### Steps to reproduce the issue
In a custom extension if the captcha plugin is initialized manually like so:
```php
JPluginHelper::importPlugin('captcha');
$dispatcher = JEventDispatcher::getInstance();
$dispatcher->trigger('onInit','my_captcha_div');
```
```html
<div id="my_captcha_div"></div>
```

#### Expected result
To display the google reCaptcha field

#### Actual result
No reCaptcha shown.

##### Code used in 3.4.8:
```php
// recaptcha.php
case '2.0':
	$theme = $this->params->get('theme2', 'light');
	$file  = 'https://www.google.com/recaptcha/api.js?hl=' . JFactory::getLanguage()->getTag() . '&amp;render=explicit';

	JHtml::_('script', $file, true, true);

	$document->addScriptDeclaration('jQuery(document).ready(function($) {$(window).load(function() {'
					. 'grecaptcha.render("' . $id . '", {sitekey: "' . $pubkey . '", theme: "' . $theme . '"});'
					. '});});'
				);
				break;
```

##### Code used in 3.5
```php
// recaptcha.php
else
		{
			$file = 'https://www.google.com/recaptcha/api.js?onload=JoomlaInitReCaptcha2&render=explicit&hl=' . JFactory::getLanguage()->getTag();
			JHtml::_('script', $file);
			JHtml::_('script', 'plg_captcha_recaptcha/recaptcha.min.js', false, true);
		}
```

The issue lies in the recent refactoring of the `onInit` method of the plugin where it ignores the element id set upon init and since the `plg_captcha_recaptcha/recaptcha.min.js` script's `JoomlaInitReCaptcha2` is not updated by the plugin params it looks for a `div` element like this one: 
```html
<div id="my_captcha_div" 
    class="g-recaptcha" 
    data-sitekey="xxxxxxxxxxxxxx" 
    data-theme="xxxx" 
    data-size="xxxx"></div>
```
After this modification it works. 

The issue lies in the fact that the extensions using the plugin in this fashion will have to either add the key manually (not a good option) or make some changes to make it work. I'm posting this as a reference too.

**Comment by andrepereiradasilva** [comment]
i think this has already responded by @Fedik in another PR.
See https://github.com/joomla/joomla-cms/pull/8867#issuecomment-170280458

**Comment by brianteeman** [comment]
Closed as stated above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9544">issues.joomla.org/joomla-cms/9544</a>.</sub>

**Comment by arrowthemes** [comment]
@elioair I'm trying to implement the captcha in a custom form and I'm facing the same issue where recaptcha isn't loaded. Could you help with the code to make it work in 3.6.x?

**Comment by elioair** [comment]
@arrowthemes Your container div should look like this:
```
<div id="your-div-id" 
    class="g-recaptcha"  // <---- has to have this class
    data-sitekey="xxxxxxxxxxxxxx"   // <---- has to have this
    data-theme="xxxx" 
    data-size="xxxx"></div>
```

or differently put 
```
<div class="g-recaptcha" data-sitekey="ENTER_HERE_SITEKEY" data-theme="light" data-size="compact"></div>
```
For the plugin setup you can also see [this](https://github.com/Kunena/Kunena-Forum/blob/develop/components/com_kunena/site/template/crypsis/layouts/message/edit/quickreply.php#L128).

If that fails I'd suggest looking in the above comment [#8867](https://github.com/joomla/joomla-cms/pull/8867#issuecomment-170280458) and the links referenced there and the div setup [here](https://github.com/joomla/joomla-cms/pull/9111). If nothing works, show me some code and I'd be happy to help further.
