### ISSUE TITLE
Select User field broken after 3.4.8 to 3.5.0 upgrade (worked well with RC4)

### ISSUE THREAD

**Issue by JoomliC** [joomla/joomla-cms#9545]
#### Steps to reproduce the issue
Upgrade from 3.4.8 to 3.5.0.
Go to any edition form (article...) where you can select a user (created by...)

#### Expected result
You should be able to select a user and it fills the field with user name (id).

#### Actual result
On one site, old mootools modal (was bootstrap one on 3.5.0-RC4)
On another site i've processed the same upgrade, i've got a broken boostrap modal (partially open with no content...)
On a test site where i was on RC4 and ugraded to 3.5.0, i have the still the new bootstrap modal full working!

#### Additional comments
@dgt41, @wilsonge : could it be related to a last change between 3.5.0-RC4 and 3.5.0 ?

**Comment by brianteeman** [comment]
Tested with a clean 3.5 and a site upgraded from 3.4.8 and couldnt see any issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9545">issues.joomla.org/joomla-cms/9545</a>.</sub>

**Comment by dgt41** [comment]
@JoomliC is that front end or back end?
If it's front end, are you using bootstrap 3?

**Comment by JoomliC** [comment]
Ok... thanks @brianteeman !
Will try again this evening on a clean 3.4.8 install, and upgrade...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9545">issues.joomla.org/joomla-cms/9545</a>.</sub>

**Comment by JoomliC** [comment]
@dgt41 backend.
But will do more enqueries, as not tested on a fresh install (have a few other extensions, but none that are known to be bad boys ;-) )
Will post in the evening, for now i had to change the form type to enter id in manual... and too busy now to check more farther, so maybe an isolated issue not related to Joomla... but strange one...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9545">issues.joomla.org/joomla-cms/9545</a>.</sub>

**Comment by JoomliC** [comment]
@dgt41 @brianteeman i close here as not able to reproduce the issue in all other websites i've updated...
And... It was due to third-party extensions... :-1: 

Sorry for this "fake" alert ;-)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9545">issues.joomla.org/joomla-cms/9545</a>.</sub>
