### ISSUE TITLE
Frontend: Symbol "Edit Module" hide Symbol "Edit Article"

### ISSUE THREAD

**Issue by franz-wohlkoenig** [joomla/joomla-cms#9546]
#### Steps to reproduce the issue

1. Append an Article to an  Menu Item Type "Single Article"
2. Menu > Options: Hide "Title" and "Intro Text"
3. Load a Module at Beginning of Article-Maintext

#### Expected result
Using of Symbol "Edit Module" and Symbol "Edit Article" is possible
#### Actual result
Symbol "Edit Module" hide Symbol "Edit Article"
#### System information (as much as possible)

- Joomla! 3.4.8
- PHP 5.6.13
- MySQLi 5.5.47-0+deb7u1

#### Additional comments

![edit-module-article](https://cloud.githubusercontent.com/assets/8235763/13988531/ac8bddf0-f10c-11e5-8ada-e9fd12fe45ed.JPG)

**Comment by Ruchiranga** [comment]
I'm trying to reproduce the issue. But I don't seem to clearly get what you mean by
"Load a Module at Beginning of Article-Maintext"
Can you please explain?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9546">issues.joomla.org/joomla-cms/9546</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Hi @Ruchiranga,

thanks for coming to this issue. What i mean that my Experince happened in an Article after the "Read More"-Line i insert a {loadmodule ++++}.

Regards

**Comment by brianteeman** [comment]
I cannot replicate this - I cannot get frontend editing at all for any module included in an article<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9546">issues.joomla.org/joomla-cms/9546</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Sorry, this behavoir depends on Advanced Module Manager (AMM), @brianteeman give me right hint to test on a Site without AMM where i also could not edit a module in an Article.
