### ISSUE TITLE
Insert module plugin filters

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9550]
#### Steps to reproduce the issue
Go to module manager and set a filter - eg position 8
Go to an article and try to insert a module - you will only be able to insert those modules in position 8

#### Expected result
Able to insert all modules

#### Actual result
Can only insert the modules based on the current filter in the module manager

#### System information (as much as possible)
3.5

#### Additional comments
Shouldnt the search filters be available in the module

**Comment by andrepereiradasilva** [comment]
did you try with this PR?
https://github.com/joomla/joomla-cms/pull/9232

**Comment by brianteeman** [comment]
No not yet. I posted quickly before leaving the house for the evening

**Comment by brianteeman** [comment]
Still I would not expect the list to be filtered in the module without any
searchtools

**Comment by brianteeman** [comment]
Yes #9232 will resolve this as it is a new and improved modal<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9550">issues.joomla.org/joomla-cms/9550</a>.</sub>

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9550">issues.joomla.org/joomla-cms/9550</a>.</sub>
