### ISSUE TITLE
ReCaptcha marked as optional in contact page

### ISSUE THREAD

**Issue by RoscioZ** [joomla/joomla-cms#9552]
#### Steps to reproduce the issue

Activate the ReCaptcha in contact form

#### Expected result
**Captcha ***

#### Actual result
**Captcha * (optional)** (image attached)
![ReCaptcha](http://i65.tinypic.com/21dka3t.png "ReCaptcha")

**Comment by brianteeman** [comment]
Confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9552">issues.joomla.org/joomla-cms/9552</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Confirmed

**Comment by andrepereiradasilva** [comment]
This PR (https://github.com/joomla/joomla-cms/pull/8473/files) added a layout override for the contact form, could it come from here?
@matrikular can you check?

**Comment by matrikular** [comment]
I will, give me a minute.

**Comment by brianteeman** [comment]
Closing as we have a PR for testing #9596

**Comment by RoscioZ** [comment]
Thank you very much!

**Comment by BitpopCoin** [comment]
Thanks I had this issue too.

Related, why is my form language override no longer working?
