### ISSUE TITLE
Duplicate (one more) rel="canonical" after updating to 3.5.0

### ISSUE THREAD

**Issue by scence** [joomla/joomla-cms#9556]
I've updated joomla to 3.5.0 and have duplicate canonical on a product page now:
 
"link href="/index.php/shop/store-frontpage/t-shirt-s/66-n-t-shirt-49-detail" rel="canonical" />
**link href="/index.php/shop/store-frontpage/t-shirt-s/66-n-t-shirt-49-detail?limitstart=0&amp;limit=int" rel="canonical" />"**

There is a testing page:
http://storebox.bambi.by/index.php/shop/store-frontpage/t-shirt-s/66-n-t-shirt-49-detail

I wonder how I could delete the second rel.

**Comment by SharkyKZ** [comment]
Update VirtueMart to 3.0.14 first. It had some router changes done, including removal of limitstart and limit from product URLs.

**Comment by chivitli** [comment]
I detected double canonicals as well for my custom component, now Joomla adds a second canonical where it didn't before, only the canonical I added myself was present.

I also lost the ability to unset Joomla generated canonical in K2 through K2 plugins, but this would work  again if I change the event Joomla sef uses back to `onAfterRoute` and change back to `JFactory` to get `$app` and `$doc` objects. However this does not fix the double canonical for a custom component. @andrepereiradasilva, since you made the performance optimization, could you confirm what impact would reverting just this part have on the performance?

**Comment by chivitli** [comment]
Also, Joomla still does not generate proper canonicals. Let's take the main site as an example:

For https://www.joomla.org/announcements/release-news/5654-joomla-3-5-is-here.html the canonical link set is the same, that's good. But what if alias changed? For the same page on https://www.joomla.org/announcements/release-news/5654-joomla-3-5-is-heeeeeeeeeeeeere.html canonical link becomes `<link rel="canonical" href="/announcements/release-news.html?catid=5654&id=5654:joomla-3-5-is-here">`. That's not good.

**Comment by scence** [comment]
I've updated VirtueMart to 3.0.14 and I have the same problem still  (without "?limitstart=0&limit=int" in the end of url now):

link href="http://storebox.bambi.by/index.php/shop/store-frontpage/t-shirt-s/66-n-t-shirt-49-detail" rel="canonical" />
  _<link href="/index.php/shop/store-frontpage/t-shirt-s/66-n-t-shirt-49-detail" rel="canonical"
_
I need to remove the second rel _<link href="/index.php/shop/store-frontpage/t-shirt-s/66-n-t-shirt-49-detail" rel="canonical_

**Comment by SharkyKZ** [comment]
Going back to #9333, assuming @ggppdk is correct, canonical should be made absolute even if no domain is set in plugin parameters. This would solve the issue above. Although the issue of removing canonical generated by plugin in favor of component remains.

**Comment by andrepereiradasilva** [comment]
> I also lost the ability to unset Joomla generated canonical in K2 through K2 plugins, but this would work again if I change the event Joomla sef uses back to onAfterRoute and change back to JFactory to get $app and $doc objects. However this does not fix the double canonical for a custom component. > @andrepereiradasilva, since you made the performance optimization, could you confirm what impact would reverting just this part have on the performance?

I don't think it will have much impact on performance. So be my guest, make a PR to revert it.

**Comment by andrepereiradasilva** [comment]
Please test Please test https://github.com/joomla/joomla-cms/pull/9565

**Comment by andrepereiradasilva** [comment]
@brianteeman i think you can close this as we have a PR.
@scence please test if that PR solves the issue too.

**Comment by scence** [comment]
I've reinstalled all updates and everything is ok now (one right rel canonical):

view-source:http://storebox.bambi.by/index.php/shop/t-shirt-s/66-n-t-shirt-49-detail

thanks everybody for help

**Comment by andrepereiradasilva** [comment]
@sence, sorry i don't understand. did you test with this (https://github.com/joomla/joomla-cms/pull/9565/files) changes?
