### ISSUE TITLE
Joomla dont save Template Params

### ISSUE THREAD

**Issue by fretelweb** [joomla/joomla-cms#9557]
#### Steps to reproduce the issue

Modify Isis param like logo and it dont save also dont save if I modify a parameter in different template.

**Comment by brianteeman** [comment]
I have been unable to replicate this

**Comment by brianteeman** [comment]
Can you please provide more information about your site so we can try to replicate it. If not this issue will be closed in a few weeks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9557">issues.joomla.org/joomla-cms/9557</a>.</sub>

**Comment by alexonbalangue** [comment]
i trying J3.5.1 and i confirm is work well after save params isis tpl on the backend
