### ISSUE TITLE
Mod articles categories - heavy load

### ISSUE THREAD

**Issue by Wertos** [joomla/joomla-cms#9558]
#### Steps to reproduce the issue

1)
mod_articles_categories - enable the display of the amount of material in the category
![](https://i.gyazo.com/b5f55152be50ac0997f4cd446ee94de8.png)
off count
![](https://i.gyazo.com/86b9ac9c24ce44abd2e6b1ea5b1c4383.png)
2)
mod_articles_categories
echo JRoute::_(ContentHelperRoute::getCategoryRoute($item->id) - plus 1 query for each category, in my case 46 queries!
#### System information (as much as possible)

Joomla 3.5
Percona Server(DB ~ 1.5Gb, ~83000 materials)
php 7.0.4
Linux 2.6.32-042stab108.8 x86_64
Intel(R) Xeon(R) CPU E5-2630 v3 @ 2.40GHz, 4 core
12 GB RAM
#### Additional comments

Sorry for my English

**Comment by candidosa2** [comment]
hello how can resolve

Fatal error: Class 'ContentHelperRoute' not found in /home/domain/public_html/modules/mod_articles_categories/tmpl/default_items.php on line 13<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9558">issues.joomla.org/tracker/joomla-cms/9558</a>.</sub>

**Comment by brianteeman** [comment]
@candidosa2 this sounds like a completely different issue to the one you have posted on<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9558">issues.joomla.org/tracker/joomla-cms/9558</a>.</sub>

**Comment by rvbgnu** [comment]
Hi @Wertos is this issue still relevant?
@nibra

**Comment by franz-wohlkoenig** [comment]
If this PR get no Response, it will be closed at 23th July 2017.

**Comment by ghost** [comment]
closed as stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9558">issues.joomla.org/tracker/joomla-cms/9558</a>.</sub>
