### ISSUE TITLE
Save, Save & Close Buttons not saving, nor executing events v3.5

### ISSUE THREAD

**Issue by leslieongit** [joomla/joomla-cms#9560]
#### Steps to reproduce the issue

Login into Administrator area  > Global Configuration > 

#### Expected result

No action when Save buttons are triggered

#### Actual result

No result at all 

#### System information (as much as possible)

Deployed on Linux Server

**Comment by b2z** [comment]
Have you tried to clean the browser cache?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9560">issues.joomla.org/joomla-cms/9560</a>.</sub>

**Comment by brianteeman** [comment]
Please ensure that you have completely cleared your browser cache

On 24 March 2016 at 09:01, Leslie Nyahwa <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Login into Administrator area > Global Configuration >
> Expected result
>
> No action when Save buttons are triggered
> Actual result
>
> No result at all
> System information (as much as possible)
>
> Deployed on Linux Server
> Additional comments
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9560>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by leslieongit** [comment]
Sorry I eventually started from scratch, will update my joomla to 3.5 once in done presenting the website

**Comment by brianteeman** [comment]
I am closing this at this time

**Comment by leslieongit** [comment]
Opened the site in Internet Explorer, managed to save. You were right, its a cache issue, best to open the work with Joomla in incognito in Chrome.
