### ISSUE TITLE
Joomla 3.5: Parse error in Smart Search on PHP 5.3.29

### ISSUE THREAD

**Issue by khanhlh** [joomla/joomla-cms#9561]
#### Steps to reproduce the issue
Enable Smart Search component and create a menu item to it.

#### Expected result
Smart search page

#### Actual result
Parse error: syntax error, unexpected '[', expecting ')' in components/com_finder/helpers/html/filter.php on line 112 

#### System information (as much as possible)
PHP 5.3.29

#### Additional comments
Can be fixed by change line 112 in components/com_finder/helpers/html/filter.php
From
```
$html .= JHtml::_('bootstrap.startAccordion', 'accordion', array('parent' => true, 'active' => 'accordion-' . array_keys($branches)[0]));
```
To
```
$branch_keys = array_keys($branches);
$html .= JHtml::_('bootstrap.startAccordion', 'accordion', array('parent' => true, 'active' => 'accordion-' . $branch_keys[0]));
```

**Comment by infograf768** [comment]
I confirm the error. 
@wilsonge 
I guess this is another blocker

**Comment by brianteeman** [comment]
Weird -I get it on 5.3.29 but not on 5.4.42 or higher

On 24 March 2016 at 09:40, infograf768 <notifications@github.com> wrote:

> I confirm the error.
> @wilsonge <https://github.com/wilsonge>
> I guess this is another blocker
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9561#issuecomment-200757189>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
I get it on 5.3.14
The proposed change sloves it, 
Now testing on 5.4.4
If it works, will propose the PR

**Comment by infograf768** [comment]
It does. Making PR now.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/9562

**Comment by brianteeman** [comment]
Closed as we have a PR for testing
