### ISSUE TITLE
Article counter ignores registered users

### ISSUE THREAD

**Issue by danpdanp** [joomla/joomla-cms#9563]
#### Steps to reproduce the issue

Backend -> Articles Management -> Counter visits Articles

#### Expected result

The counter advances after each visit Article, also logged users

#### Actual result

The counter advances only after visits from people who are not logged in; the count does not advance for logged-in users visits

#### System information (as much as possible)

joomla 3.5.0
5.5.40 database
php 5.5.23

**Comment by brianteeman** [comment]
I have updated the title for clarity<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9563">issues.joomla.org/joomla-cms/9563</a>.</sub>

**Comment by brianteeman** [comment]
I can confirm that if joomla is not recording a hit on an article if the user is logged in. Tested with both registered users and super users. Also tested in 3.4.8 where the same behaviour is observed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9563">issues.joomla.org/joomla-cms/9563</a>.</sub>

**Comment by mbabker** [comment]
Blame https://github.com/joomla/joomla-cms/pull/8887

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #9604<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9563">issues.joomla.org/joomla-cms/9563</a>.</sub>
