### ISSUE TITLE
Cannot load reset or remind form if clean urls are activated Joomla 3.4.8

### ISSUE THREAD

**Issue by arudat** [joomla/joomla-cms#9570]
#### Steps to reproduce the issue
I activated joomla language and language filter extensions. Now if I try to click on the password reset Link -> Page not found. If language filter is deactivated all is ok. Or if I disable mod_rewrite.

#### Expected result
The reset/remind /registration view

#### Actual result

foobar/de/?view=registration /failed
foobar/de/?view=remind /failed
foobar/de/?view=reset /failed
foobar/de/impressum /passed

it works when I change the jroute
`JRoute::_('index.php?option=com_users&view=remind&Itemid=' . UsersHelperRoute::getRemindRoute())`
to

` JRoute::_('?option=com_users&view=remind&Itemid=' . UsersHelperRoute::getRemindRoute())`

#### System information (as much as possible)

Joomla 3.4.8 migrated from 2.5.29 to 3.4
Fabrik 3.3.4
Apache (don't know verison)
Php 5.3.29

**Comment by brianteeman** [comment]
Please update to Joomla 3.5 and then open a new issue if you still have problems
