### ISSUE TITLE
Limit of 100 carachters in the title of a custom module

### ISSUE THREAD

**Issue by 82ghost82** [joomla/joomla-cms#9571]
#### Steps to reproduce the issue
From the admin backend create a custom module, extensions->modules->custom
The title is limited to 100 characters: this is a limitation if the title is more than 100 characters (if using nonumber sourcerer for example).
The limitation is in the id jform_title, with a maxlength=100

#### Expected result
Title should not be truncated

#### Actual result
Title is truncated if more than 100 characters

#### System information (as much as possible)
Joomla 3.5.0

**Comment by brianteeman** [comment]
Sorry but I am closing this as the expected behaviour

**Comment by bertmert** [comment]
Even if I rarely need a length like this and then use a custom module style plus language string as title:
Shouldn't this issue been discussed? The limit is given by database table #__modules (title, varchar, length 100). Other tables like content, categories, menu, tags, banners have a title length of 255. I don't understand why modules not.

**Comment by ComSpiration** [comment]
Hello,
I think this subject must be considered by the joomla developers.
The real problem is the impossibility to give a link to a module title, that should be considered by the joomla developers too... !!!
One of the two solutions must be in joomla 4! 
Thanks a lot! I love Joomla!

**Comment by Bakual** [comment]
Pleas eopen a new issue. Closed ones don't get much attention.
