### ISSUE TITLE
Menu manager break the menu level,  when create new menu item, after upgrade to 3.5

### ISSUE THREAD

**Issue by Fedik** [joomla/joomla-cms#9572]
I got whole menu broken after upgrade to 3.5, when tried create new menu item
... in some reason.

#### Steps to reproduce the issue
Go to menu manager and create new menu (any type), **without** parent.

**Before**
![screen 2016-03-24 17 43 51 500x418](https://cloud.githubusercontent.com/assets/1568198/14022600/2d2a9f96-f1e9-11e5-8c6e-18f7e9316aee.png)
**After**
![screen 2016-03-24 17 44 27 500x418](https://cloud.githubusercontent.com/assets/1568198/14022659/752ef6f2-f1e9-11e5-9ed2-5e3e7aafad4a.png)

Also it breaks the level for ALL menu items on the site.

#### System information (as much as possible)

php: Linux 3.13.0-55-generic # 
94-Ubuntu SMP Thu Jun 18 00:28:41 UTC 2015 i686
dbversion: 5.5.47-0ubuntu0.14.04.1
dbcollation: utf8_general_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 5.5.9-1ubuntu4.14
server: Apache/2.4.7 (Ubuntu)
sapi_name: apache2handler
version: Joomla! 3.5.1-dev Development [ Unicorn ] 21-March-2016 22:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

[systeminfo-2016-03-24T15-55-51+00-00.txt](https://github.com/joomla/joomla-cms/files/188160/systeminfo-2016-03-24T15-55-51.00-00.txt)

**Comment by Fedik** [comment]
hm, in database `#__menu`:
Joomla 3.4.x: `Menu_Item_Root` level = 0
Joomla 3.5.x: `Menu_Item_Root` level = 2 - changes after create a new menu item

Quick fix is to change `Menu_Item_Root` level to `0` in  `#__menu`, manually. And reorder menu items.
But after making a new menu item the issue is back.

**Comment by brianteeman** [comment]
Is this a very old site? I seem to recall this as an issue in the past and it was caused by an error in one of the migration components<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9572">issues.joomla.org/joomla-cms/9572</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@Fedik i can't reproduce this.

**Comment by Fedik** [comment]
hm, yes, they are old (since joomla 3.3.x) ... was 2 sites  on different servers, and one local dev setup (before upgrade they was 3.4.8)
@brianteeman do you remember which issue it was?

**Comment by photodude** [comment]
Off the top of my head, I think the menu **"Rebuild"** button was added to address something like this.

**Comment by bertmert** [comment]
An identical issue was reported in a german forum. There ALL levels were increased by 9 (10 instead 1 and so on) and lft/rgt had huge values. A friend of mine helped after some unsuccessfull tests:
- Save menu items again: unsuccessful.
- Create additional menu item in highest menu level (root): unsuccessful
- Click Rebuild button: All items in database table had a "root/" in field link afterwardss 
- Correcting table:
-- All level dicreased by 9 (9 to 0, 10 to 1 and so on).
-- All link: Remove "root/"
-- Set lft of ROOT to 0.
-- Click Rebuild button afterwards.
TE reported success but after a PM to him is not willing to test with a new menu item.

**Comment by brianteeman** [comment]
This doc should be relevant
https://docs.joomla.org/Fixing_the_assets_table<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9572">issues.joomla.org/joomla-cms/9572</a>.</sub>

**Comment by chrisdavenport** [comment]
@Fedik Are you using the PDO driver by any chance?

I can reproduce this exact behaviour using PDO.  For a possible explanation see #9601

**Comment by Fedik** [comment]
@chrisdavenport yes I use PDO,
I try test that PR soon

**Comment by Fedik** [comment]
yep, MySQLi works fine, PDO fail, 
I wonder what was changed there since 3.4.8, as there all worked fine

btw #9601 fix the issue

**Comment by Fedik** [comment]
see #9601 for fix
