### ISSUE TITLE
3.5 upgrade - List of contacts in a category no longer work

### ISSUE THREAD

**Issue by keynet** [joomla/joomla-cms#9576]
#### Steps to reproduce the issue
Upgrade from 3.4.8 (old site long since migrated from J1.5)
Menu items for lists of contacts in category just give blank screen

tried removing SEF URLS to see what URL is being called, and created a new one to compare as I've seen mention of menu issues
OLD URL http://<domain>/index.php?option=com_contact&view=*category*&id=51&Itemid=224&lang=en
NEW URL http://<domain>/index.php?option=com_contact&view=*categories*&id=51&Itemid=460&lang=en

Neither NEW nor OLD menu items work.

#### Expected result
Should work

#### Actual result
OLD URL - Totally blank screen
NEW URL - screen with menus, but empty window for contact listing

Also tried rebuilding all menus and menu items, clearing all caches - no effect

*NOTE* manually removing the &ItemID field from the URL makes the OLD URL work.
However I see an orange "unpublished" flag in the listing.

#### System information (as much as possible)

=============
System Information
=============
php: Linux 3.18.23-x1 #1 SMP Tue Nov 3 10:05:18 GMT 2015 i686
dbversion: 5.6.29
dbcollation: latin1_swedish_ci
dbconnectioncollation: utf8mb4_general_ci
phpversion: 5.5.31
server: Apache/2.2.31
sapi_name: apache2handler
version: Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
platform: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
useragent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

=============
PHP Settings
=============
safe_mode: false
display_errors: true
short_open_tag: true
file_uploads: true
magic_quotes_gpc: false
register_globals: false
output_buffering: false
open_basedir: 
session.save_path: xxxxxx
session.auto_start: 0
disable_functions: show_source, system, shell_exec, passthru, exec, phpinfo, proc_open, allow_url_include
xml: true
zlib: true
zip: true
mbstring: true
iconv: true
max_input_vars: 1000

=============
Configuration File
=============
offline: 0
offline_message: This site is down for maintenance.<br /> Please check later
display_offline_message: 1
offline_image: images/stories/icy.jpg
sitename: xxxxxx
editor: jce
captcha: recaptcha
list_limit: 20
access: 1
debug: 0
debug_lang: 0
dbtype: mysqli
host: xxxxxx
user: xxxxxx
password: xxxxxx
db: xxxxxx
dbprefix: xxxxxx
live_site: 
secret: xxxxxx
gzip: 1
error_reporting: simple
helpurl: https://help.joomla.org/proxy/index.php?option=com_help&keyref=Help{major}{minor}:{keyref}
ftp_host: 127.0.0.1
ftp_port: 21
ftp_user: xxxxxx
ftp_pass: xxxxxx
ftp_root: 
ftp_enable: 0
offset: Europe/London
mailonline: 1
mailer: mail
mailfrom: xxxxxx
fromname: xxxxxx
sendmail: xxxxxx
smtpauth: 0
smtpuser: xxxxxx
smtppass: xxxxxx
smtphost: xxxxxx
smtpsecure: none
smtpport: 25
caching: 1
cache_handler: file
cachetime: 60
MetaTitle: 1
MetaAuthor: 0
MetaVersion: 0
robots: 
sef: 0
sef_rewrite: 1
sef_suffix: 0
unicodeslugs: 1
feed_limit: 10
log_path: xxxxxx
tmp_path: xxxxxx
lifetime: 120
session_handler: database
MetaRights: 
sitename_pagetitles: 0
force_ssl: 0
frontediting: 0
feed_email: site
cookie_domain: 
cookie_path: 
asset_id: 1
proxy_enable: 0
proxy_host: 
proxy_port: 
proxy_user: 
proxy_pass: 
memcache_persist: 1
memcache_compress: 1
memcache_server_host: xxxxxx
memcache_server_port: 11211
memcached_persist: 1
memcached_compress: 0
memcached_server_host: xxxxxx
memcached_server_port: 11211
redis_persist: 1
redis_server_host: localhost
redis_server_port: 6379
redis_server_auth: 
redis_server_db: 0
massmailoff: 0
session_memcache_server_host: xxxxxx
session_memcache_server_port: 11211
session_memcached_server_host: xxxxxx
session_memcached_server_port: 11211
cache_platformprefix: 0

=============
Folder Permissions
=============
administrator/components:  writable
administrator/language:  writable
administrator/language/overrides:  writable
administrator/language/en-GB:  writable
administrator/manifests/libraries:  writable
administrator/manifests/files:  writable
administrator/manifests/packages:  writable
administrator/modules:  writable
administrator/templates:  writable
components:  writable
images:  writable
images/members-notcurrent:  writable
images/ships:  writable
images/headers:  writable
images/stories:  writable
images/members-associate:  writable
images/people:  writable
images/sampledata:  writable
images/smilies:  writable
images/.quarantine:  writable
images/members-full:  writable
images/banners:  writable
images/icons:  writable
images/M_images:  writable
language:  writable
language/overrides:  writable
language/en-GB:  writable
libraries:  writable
media:  writable
modules:  writable
plugins:  writable
plugins/captcha:  writable
plugins/attachments:  writable
plugins/arkevents:  writable
plugins/inline:  writable
plugins/authentication:  writable
plugins/content:  writable
plugins/editors-xtd:  writable
plugins/installer:  writable
plugins/finder:  writable
plugins/quickicon:  writable
plugins/twofactorauth:  writable
plugins/user:  writable
plugins/josetta_ext:  writable
plugins/jevents:  writable
plugins/editors:  writable
plugins/system:  writable
plugins/arkeditor:  writable
plugins/jem:  writable
plugins/extension:  writable
plugins/ajax:  writable
plugins/search:  writable
templates:  writable
configuration.php:  writable
cache:  writable
administrator/cache:  writable
log:  writable
tmp:  writable

**Comment by keynet** [comment]
Lists of RSS feeds are similarly affected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9576">issues.joomla.org/joomla-cms/9576</a>.</sub>

**Comment by brianteeman** [comment]
A totally blank screen (sometimes called a white screen of death) WSOD is a php error message in disguise
Go to the global configuration and set the error reporting to the highest available.
Go back to the problem page and you should now either see an error message on the screen OR in the server error logs<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9576">issues.joomla.org/joomla-cms/9576</a>.</sub>

**Comment by brianteeman** [comment]
Sometimes, due to a PHP error, a Joomla Extension can stop working and, without displaying an error, lead you to a blank page.

In that case, to find out why, do following:

1. Check server error logs (not access logs) if you have access to them. (cPanel or other control panels often allow this)
2. Go to Joomla Administration → Global configuration and enable Error Reporting to Maximum, you can also turn on debugging. – try the action again – if you still get a blank page then goto 3
3. put the following code at the END of the configuration.php file BEFORE the closing ?>

> ini_set( 'display_errors', true );
error_reporting( E_ALL ); 

4.Check the source of the white page – there might be still some HTML/Errors in the Page Source (Look in your web browser for the “View Source” option)

One of these should give you a nice detailed error message – which you can either email me directly or Google to find a  solution

Remember this: A White Page is just an Error Page where the error message has been suppressed by your configuration.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9576">issues.joomla.org/joomla-cms/9576</a>.</sub>

**Comment by keynet** [comment]
I switched off all caching, switched on debug and highest error reporting
I monitored tail -f on the apache error log, and nothing other than usual mod_security issues, certainly no PHP errors
There's nothing in the Joomla error log other than usual attempted login failures

If I add your lines above to configuration.php, the site gets in a redirection loop and is inaccessible.
When I switch debug on, I see quite a few "NO INDEX KEY COULD BE USED" Mysql errors, unsure if this is significant, but it doesn't look good.
There really is nothing (even viewing source) on the white pages, and no log 

Incidentally I can no longer take the site offline as I get redirect loop errors.
All this is very weird as the upgrade produced no errors and I've been using this Joomla installation for years (finally migrated from J1.5 last year)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9576">issues.joomla.org/joomla-cms/9576</a>.</sub>

**Comment by keynet** [comment]
I'm afraid I had to abandoned 3.5.0 now - reverted to 3.4.8. 
Too many weird behavioursa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9576">issues.joomla.org/joomla-cms/9576</a>.</sub>

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9576">issues.joomla.org/joomla-cms/9576</a>.</sub>
