### ISSUE TITLE
Upgrade from 3.4.8 to 3.5 gives article save issue

### ISSUE THREAD

**Issue by pkharbanda** [joomla/joomla-cms#9582]
#### Steps to reproduce the issue
There should be an article which is already created in version 3.4.8. Try and save that article. IT gives an error
Save failed with the following error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-38' for key 'PRIMARY'

Running on debug mode found there are couple of parameters which are null 
              "modified": "2016-03-25 05:02:04",
                            "modified_by": null,
                            "publish_up": "2016-03-17 16:10:57",
                            "publish_down": "",
                            "version": null,
                            "metakey": "",
                            "metadesc": "",
                            "access": "1",
                            "hits": null,
                            "language": "*",
                            "featured": "0",
                            "attribs": {

However the database have these parameters. 

#### Actual result Gives error
Save failed with the following error: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-38' for key 'PRIMARY'

#### System information (as much as possible)
Database Version	5.5.5-10.1.9-MariaDB
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.6.15
Web Server	Apache/2.4.17 (Win32) OpenSSL/1.0.2d PHP/5.6.15
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36

**Comment by chrisdavenport** [comment]
Possible duplicate of #9534.

**Comment by brianteeman** [comment]
Do you have smart search indexing enabled?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9582">issues.joomla.org/joomla-cms/9582</a>.</sub>

**Comment by pkharbanda** [comment]
Yes smart search indexing is enabled. Let me also see #9534 issues. I have tired "clear index" No errors but while saving the article same result

**Comment by pkharbanda** [comment]
Lets close the issue. Yes. I think driver needs to change Database Type to Mysqli.

**Comment by pkharbanda** [comment]
Thanks
