### ISSUE TITLE
Undefined variable in libraries/cms/application/cms.php after update from joomla 3.4.8 to joomla 3.5

### ISSUE THREAD

**Issue by boomsya** [joomla/joomla-cms#9587]
Notice: Undefined variable: this in /var/www/html/libraries/cms/application/cms.php on line 430

something wrong on lines:
```
// Inject this application object into the JMenu tree if one isn't already specified
if (!isset($options['app']))
{
	$options['app'] = $this;
}
```

php 5.4.35
mysql 5.5

**Comment by mbabker** [comment]
This isn't a core issue.  The method raising the error, `JApplicationCms::getMenu()`, is not declared as static and should not be called in a static manner.  If you're getting this error, it means that an extension is calling this method statically.

The correct way to call it is `JFactory::getApplication()->getMenu()`.

**Comment by boomsya** [comment]
but have no code `JApplicationCms::getMenu()` in sources
maybe another code can make this issue?

**Comment by mbabker** [comment]
There are a lot of ways it could be called...

- `JSite::getMenu()` and `JAdministrator::getMenu()` (since the legacy application classes are aliased)
- `JApplicationSite::getMenu()` and `JApplicationAdministrator::getMenu()`

```php
// $app could be any variable someone wanted to use, common ones are $app, $application, and $mainframe
$app = JFactory::getApplication();
$app::getMenu();
```

**Comment by boomsya** [comment]
i founded `JSite::getMenu()` in problem source and replaced to `JFactory::getApplication()->getMenu()` and error gone. thanks. it was `mod_mijopolls`
