### ISSUE TITLE
Transfert Joomla version 3.5.0

### ISSUE THREAD

**Issue by zaczeksob** [joomla/joomla-cms#9589]
#### Steps to reproduce the issue
Changing from Joomla 3.4.X to Joomla 3.5.0 
This changing was done with 
gestionnaire des extensions

Mise à jour de la version Joomla 3.4.X vers 3.5.0
Ce changement a été effectué via le gestionnaire des extensions dans Joomla même

#### Expected result
Joomla 3.5.0 OK
but...
some Modules and plugins doesn't work

le CMS Joomla 3.5.0 fonctionne 
mais...
plusieurs modules plugins ne fonctionnent plus !

#### Actual result
These modules doesn't work : Jevents, Community Builder, Kunena, Jdownload, and some others as Form Maker Lite, aso

Voisi les modules qui ne fonctionnent plus  : astonished: mile: Jevents, Community Builder, Kunena, Jdownload, and some others as Form Maker Lite, etc.

#### System information (as much as possible)
PHP 5.4.45 (OVH)

**Comment by brianteeman** [comment]
It is no longer possible to upgrade joomla with the extension manager. It MUST be done with the update component<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9589">issues.joomla.org/joomla-cms/9589</a>.</sub>

**Comment by mbabker** [comment]
For your extensions, make sure you've updated to the latest versions.  Kunena, Community Builder, and JEvents all have compatible Joomla 3.5 releases.

**Comment by zaczeksob** [comment]
ok thanks
