### ISSUE TITLE
Site not showing modules

### ISSUE THREAD

**Issue by mrmarketology** [joomla/joomla-cms#9591]
#### Steps to reproduce the issue
I am having trouble viewing all elements of my website mrmarketology.com which is explained in this video https://mrmarketology.wistia.com/medias/hg6j2akouw.  What I try to view it on my browser at home I do not see the Youbrick Engine module.  Also when I go to the an internal page such as http://mrmarketology.com/j/component/k2/item/102-content-creation-in-the-new-age I do not see the thumbnail or media content on the page. 
Last when I log into the admin I can not see the wysiwyg editor buttons nor will it save and close as it should on the module, articles and other settings.
When I asked others to view it, some could and some could not see the entire website.  
The video attached shows and here is a screenshot of someone who could see it.  http://prntscr.com/ajte3o

#### Expected result

To see the website wth the top module showing like here http://prntscr.com/ajte3o

#### Actual result

i do not see the top module

#### System information (as much as possible)

PHP Built On	Linux server3.websitehostserver.net 2.6.32-604.30.3.lve1.3.63.el6.x86_64 #1 SMP Sun Sep 27 06:34:10 EDT 2015 x86_64
Database Version	10.0.24-MariaDB
Database Collation	latin1_swedish_ci
PHP Version	5.6.18
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.4.8 Stable [ Ember ] 24-December-2015 19:30 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.87 Safari/537.36
Joomla Template - YouBrick from YouJoomla version 1.0.2

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org
