### ISSUE TITLE
Codemirror editor saves files with Windows EOL (CRLF)

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#9592]
Go to administrator=>Templates=>Beez=>Edit template
/administrator/index.php?option=com_templates&view=template&id=503

Edit a php file, for example: component.php
Save and close.

Now Manually open the file on the desktop with a TextEditor (I use BBEdit on Macintosh).

The file has now Windows EOL (CRLF) instead of Unix ending.

**Comment by okonomiyaki3000** [comment]
Does it make any difference whether you use FTP for writing to the file system or not?

**Comment by infograf768** [comment]
I do not use FTP in my tests. It is local only

**Comment by brianteeman** [comment]
Does it matter?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9592">issues.joomla.org/joomla-cms/9592</a>.</sub>

**Comment by brianteeman** [comment]
If i searched correctly and understood then this is the relevant issue at codemirror https://github.com/codemirror/CodeMirror/issues/3395<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9592">issues.joomla.org/joomla-cms/9592</a>.</sub>

**Comment by infograf768** [comment]
Not sure, @brianteeman
I understand it rather as a discussion about forcing the use of the same line ending of the precedent line when creating a new one.

@okonomiyaki3000 
I may have found a way to solve the issue in com_localise and waiting for @Valc to test.
See https://github.com/joomla-projects/com_localise/issues/297#issuecomment-201751381

**Comment by Valc** [comment]
I think than the applied patch after codemirror/CodeMirror#3395 issue allow mix EOLs, but seem that also allow set the EOL by default, such i can read from the manual:

> 
> lineSeparator: string|null
>     Explicitly set the line separator for the editor. By default (value null), the document will be split on CRLFs as well as lone CRs and LFs, and a single LF will be used as line separator in all output (such as getValue). When a specific string is given, lines will only be split on that string, and output will, by default, use that same separator.

At line 5317 of  ./media/editors/codemirror/lib/codemirror.js we have:

`option("lineSeparator", null, function(cm, val) {`

And seems that can to be forced to use "\n" changing to:

`option("lineSeparator", "\n", function(cm, val) {`

But not luck when i try to change the "null" by "\n":  it continues saving in windows format. I think than i don't know how to set correctly that one and maybe you can take a look there.

The stuff is that if before this patch:

https://github.com/codemirror/CodeMirror/commit/0d9dbab4bcb3bcfef596e9ce475efff5507765bb

We was saving files with UNIX format and no way by option to force the desired EOL,  for me the normal stuff is comeback to previous files, due open files with open files with UNIX/Linux EOL and obtain files with windows EOL does not seem a good idea.

Regards.

**Comment by infograf768** [comment]
Folks, I just tested with Editor None and I have the same issue.
Will now provide a PR implementing the same solution I used for com_localise.

**Comment by infograf768** [comment]
As this is not Codemirror specific and a PR ( https://github.com/joomla/joomla-cms/issues/9616 ) is ready to test, closing this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9592">issues.joomla.org/joomla-cms/9592</a>.</sub>
