### ISSUE TITLE
Mootools is still required by modals

### ISSUE THREAD

**Issue by creativeprogramming** [joomla/joomla-cms#9594]
Hi, is it time to get rid of the squeezebox modal implementation?

This is still a thing that requieres mootools, so it's not true that Joomla 3 is mootools free

**Comment by mbabker** [comment]
Nobody has ever claimed Joomla 3 is MooTools free and if they did they were mistaken.  The dependence on MooTools has loosened heavily with Joomla 3 and is almost non-existent, but until 4.0 Joomla will at least ship with MooTools (even if the day comes where no core APIs use it).

**Comment by creativeprogramming** [comment]
Ok sorry, anyway if you disable mootools scripts with Joomla 3, e.g. with a plugin, in order to optimize the page load time, you get squeezebox errors and lose some vital functions in admin backend that requirers modals. 

Any hope to see a replacement for this modal implementation before Joomla 4?

**Comment by mbabker** [comment]
Honestly, if you're running scripts that unloads core media then you need to be prepared for stuff not working right if there's an underlying dependency.  Every media library is explicitly loaded only when it is needed by something, so stuff like MooTools or jQuery aren't being arbitrarily loaded by Joomla on every page load (but thanks to so many things being dependent on it jQuery does end up in place more often than not).

Some modals are converted to Bootstrap modals, others aren't.  The ones that aren't are more complex to deal with (see the recent issues on here about the media and users fields for example).

**Comment by creativeprogramming** [comment]
Ok thanks for reply.

**Comment by creativeprogramming** [comment]
> Some modals are converted to Bootstrap modals, others aren't. The ones that aren't are more complex to deal with (see the recent issues on here about the media and users fields for example).

@mbabker 
I was thinnking to look for a drop-in replacement for the mootools modal implementation, not refactoring all the usages.

**Comment by mbabker** [comment]
AFAIK there isn't a drop in replacement for Squeezebox.
