### ISSUE TITLE
Can not get ID of stored item when using JTable to bind and store data

### ISSUE THREAD

**Issue by SPQRInc** [joomla/joomla-cms#9598]
#### Steps to reproduce the issue
On Joomla < 3.5 the following source worked perfectly:

```
// Lets store it!	
$row = JTable::getInstance('Message','BestiaTable');
$row->bind($data);
$row->check();
$store  = $row->store(); 
$id = $row->id;

```

On Joomla 3.5 $id is always NULL - but the data is still stored to the database.

#### Expected result

Returns ID

#### Actual result

Returns NULL

#### System information (as much as possible)

<img width="1068" alt="bildschirmfoto 2016-03-25 um 21 15 39" src="https://cloud.githubusercontent.com/assets/10261817/14053021/d3ccee72-f2ce-11e5-9d77-e9a56ee45998.png">

**Comment by brianteeman** [comment]
This is best placed on the mailing list and as you have already created a topic there I am closing this here. It can always be reopened if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9598">issues.joomla.org/joomla-cms/9598</a>.</sub>
