### ISSUE TITLE
Pagebreak insert wrong rel = canonical

### ISSUE THREAD

**Issue by WillerCT** [joomla/joomla-cms#9603]
Good morning,

on my website made with Joomla 3.4.8, I noticed that in all the multipage articles I wrote is only indexed the first page. Analyzing the source code of the other pages I noticed that there is the rel = canonical attribute to the first page. I think this is a big mistake because each page has a unique content that should contribute to the placement of any item. I managed to remove the code responsible of the problem and all the pages of the articles are now indexed.

I suggest you correct this behavior.

**Comment by andrepereiradasilva** [comment]
@WillerCT please test with this changes https://github.com/joomla/joomla-cms/pull/9565/files

**Comment by WillerCT** [comment]
With the modification that you suggested I get blank page. Instead I solved the problem with the modification indicated in this post http://forum.joomla.org/viewtopic.php?f=712&t=833986

This eliminates the rel = canonical<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9603">issues.joomla.org/joomla-cms/9603</a>.</sub>

**Comment by andrepereiradasilva** [comment]
> Instead I solved the problem with the modification indicated in this post http://forum.joomla.org/viewtopic.php?f=712&t=833986
> This eliminates the rel = canonical

Yes, if you remove the line of code that add the canonical the canonical is not added ...

> With the modification that you suggested I get blank page.

you get an white page? an white page is normally a php error in disguise.
please try to replace your `/plugins/system/sef/sef.php` file with this one https://raw.githubusercontent.com/andrepereiradasilva/joomla-cms/patch-6/plugins/system/sef/sef.php and tell me if all ok.

**Comment by WillerCT** [comment]
It is now all ok, the site is visible and rel = canonical absent.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9603">issues.joomla.org/joomla-cms/9603</a>.</sub>

**Comment by andrepereiradasilva** [comment]
oh i noticed now that you're on 3.4.8 (my mistake for not noticing), so the white page php error cames for that (there was changes in the SEF plugin from 3.4.8 to 3.5.0).

Anyway, if you do what i said in the comment before it should work fine.

**Comment by andrepereiradasilva** [comment]
ok thanks you.
@brianteeman i think this issue can be closed.

**Comment by WillerCT** [comment]
no no I switched to 3.5 ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9603">issues.joomla.org/joomla-cms/9603</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman this one can be closed

**Comment by brianteeman** [comment]
Closed as requested
