### ISSUE TITLE
feature request: add Font Awesome package to Joomla assets/media to allow developers sharing it

### ISSUE THREAD

**Issue by baijianpeng** [joomla/joomla-cms#9606]
#### Steps to reproduce the issue

Check the latest Joomla 3.5.0 installer package, there is NO** Font Awesome** inside.

#### Expected result

add Font Awesome package to Joomla assets/media to allow developers sharing it

#### System information (as much as possible)

Joomla 3.5.0

#### Additional comments

Since **Font Awesome is fully Open Source** and **GPL**software, and Joomla too, why not include Font Awesome inside Joomla core /media or /library folder to allow developers to use it directly from core?

Thank you.

**Comment by brianteeman** [comment]
It is never going to be possible to include everything with Joomla. There are already several extensions available to add fontawesome to your site<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9606">issues.joomla.org/joomla-cms/9606</a>.</sub>

**Comment by baijianpeng** [comment]
hi,

Why Joomla includes jQuery in core? Because we don't want every 3rd party
developer to "reproduce the wheel", we don't want to see every 3rd party
extension contains its own jQuery code. If Joomla core did not include
jQuery, then the 3rd party developer will NOT be  sure that the Joomla user
has already installed some plugin to load jQuery.

The same for Font Awesome: a developer is NOT sure if the Joomla admin has
already loaded Font Awesome on his Joomla installation, so, if the
developer want to show some icons in Font Awesome format, he has to include
this BIG font package inside his own extension!

Why not just include Font Awesome inside Joomla core to avoid such an
awkward?

Thank you.

baijianpeng


2016-03-26 21:43 GMT+08:00 Brian Teeman <notifications@github.com>:

**Comment by baijianpeng** [comment]
I just noticed that Joomla core uses "icomoon" font to render those icons
in core.

Well, if icomoon is as better as Font Awesome, maybe we can also
use icomoon.

Thank you.

2016-03-26 21:50 GMT+08:00 Joomlagate China <joomlagate@gmail.com>:

**Comment by smz** [comment]
@baijianpeng I too find Font Awesome fonts very useful and use thems in many of my projects.

Some time ago I developed a very basic and easy Joomla system plugin to load them, and, seeing that there is interest in that, I decided to update it with the latest available Font Awesome fonts and publish it in GitHub.

You can find it at: https://github.com/smz/plg_system_fontawesome

The plugin auto-enable itself once installed.

Feel free to use it as you wish for whatever purpose you want.

No warranty implied, as they say... :stuck_out_tongue_winking_eye:  

===================

As for your question about jQuery: Protostar (_the standard Joomla fronted template_) and Isis (_the backend template_), both are based on Bootstrap 2 that requires jQuery, so jQuery must be embedded for them to work.

smz
