### ISSUE TITLE
No Empty trash in banners component

### ISSUE THREAD

**Issue by Joomv** [joomla/joomla-cms#9609]
#### Steps to reproduce the issue
Go to banners, stick a banner in the trash
Select status trashed

#### Expected result
Empty trash button is shown

#### Actual result
Empty Trash button is not shown

#### System information (as much as possible)
Joomla 3.50 only
Tested in various environments - same result.
In 3.4.8 button appears as expected.

**Comment by infograf768** [comment]
Confirmed

**Comment by infograf768** [comment]
Making PR now.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/9611

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9609">issues.joomla.org/joomla-cms/9609</a>

**Comment by infograf768** [comment]
Closing as we have a patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9609">issues.joomla.org/joomla-cms/9609</a>.</sub>
