### ISSUE TITLE
TinyMCE Editor Crashed on Update.

### ISSUE THREAD

**Issue by Clayman99** [joomla/joomla-cms#9613]
#### Steps to reproduce the issue

After doing 3.5.0 update editr is not working and many pages including new article just hang and dont work.

I can provide login is required.

#### System information (as much as possible)

Setting 	Value
 
PHP Built On 	Linux cpanel.prmachinehosting.com.au 2.6.32-431.11.2.el6.x86_64 #1 SMP Tue Mar 25 19:59:55 UTC 2014 x86_64
Database Version 	5.5.48-cll
Database Collation 	latin1_swedish_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.5.29
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by brianteeman** [comment]
Almost certainly this is due to a plugin that you have installed on the
site. Check for any non-core plugins in the editor-xtd group and disable
them one at a time to work out which one is causing the problem

On 26 March 2016 at 22:22, Clayman99 <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> After doing 3.5.0 update editr is not working and many pages including new
> article just hang and dont work.
>
> I can provide login is required.
> Expected result Actual result System information (as much as possible)
>
> Setting Value
>
> PHP Built On Linux cpanel.prmachinehosting.com.au
> 2.6.32-431.11.2.el6.x86_64 #1
> <https://github.com/joomla/joomla-cms/pull/1> SMP Tue Mar 25 19:59:55 UTC
> 2014 x86_64
> Database Version 5.5.48-cll
> Database Collation latin1_swedish_ci
> Database Connection Collation utf8mb4_general_ci
> PHP Version 5.5.29
> Web Server Apache
> WebServer to PHP Interface cgi-fcgi
> Joomla! Version Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
> Joomla! Platform Version Joomla Platform 13.1.0 Stable [ Curiosity ]
> 24-Apr-2013 00:00 GMT
> User Agent Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101
> Firefox/45.0
> Additional comments
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9613>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Clayman99** [comment]
Thank you Sir for your quick response.... Im trying your tips now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9613">issues.joomla.org/joomla-cms/9613</a>.</sub>

**Comment by Clayman99** [comment]
![screen shot 2016-03-26 at 17 55 15](https://issues.joomla.org/uploads/1/3537dae7d80a1d6f893ecc802c236483.jpg)

Turned all these off and it was good as gold.   Thank you for your help.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9613">issues.joomla.org/joomla-cms/9613</a>.</sub>

**Comment by brianteeman** [comment]
You can safely turn on all but the first one on that list as they are core
plugins and work fine.

On 26 March 2016 at 22:55, Clayman99 <notifications@github.com> wrote:

> [image: screen shot 2016-03-26 at 17 55 15]
> <https://camo.githubusercontent.com/be8870518c2d911a6ebff50d4a914c654084f7dc/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f33353337646165376438306131643666383933656363383032633233363438332e6a7067>
>
> Turned all these off and it was good as gold. Thank you for your help.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9613
> <https://issues.joomla.org/tracker/joomla-cms/9613>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9613#issuecomment-201945442>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Closing as it has been resolved and was an issue with a joomlart extension<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9613">issues.joomla.org/joomla-cms/9613</a>.</sub>
