### ISSUE TITLE
Additional  wording to uninstall message

### ISSUE THREAD

**Issue by mandville** [joomla/joomla-cms#9614]
#### Steps to reproduce the issue

When uninstal an extension a message advising that the files will be deleted 

Request additional sentence adding.

"Database tables may have to be removed manually if not removed by the extension " 
Or similar

**Comment by brianteeman** [comment]
How about
Uninstalling an extension may not remove the database tables. If you wish to check and move them as well you will need to do this directly in the database

My only issue with adding this message is the "support cost" of explaining how to do that - if it is even necessary

**Comment by MATsxm** [comment]
A link to a JDoc tuto?

**Comment by mandville** [comment]
it would not be needed if developers cleaned up on uninstall. the line "Uninstalling an extension may not remove the database tables. " should suffice in most cases. 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9614">issues.joomla.org/joomla-cms/9614</a>.</sub>

**Comment by mbabker** [comment]
You'd need more wording than that.  I have an extension that when uninstalled does NOT remove user uploads even though they are uploaded and designed for use exclusively with that extension.  Specific exemptions on the uninstall message are just going to cause it to become excessively long (you have successfully uninstalled this extension however there may still be entries in the database or files in the filesystem relating to the extension's operation).  If it's decided there needs to be a "not everything was removed" message, I'd suggest keeping it at a generic level personally.

**Comment by brianteeman** [comment]
Ah yes @mbabker is correct- starting to get very complicated and I still dont see the real need for it myself<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9614">issues.joomla.org/joomla-cms/9614</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for your suggestion but it has been decided that this is not something that will be included in the core of Joomla.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9614">issues.joomla.org/joomla-cms/9614</a>.</sub>

**Comment by gwsdesk** [comment]
"it has been decided that this is not something that will be included in the core of Joomla."

I thought that this was "Open Source" and that discussions on issues would be public and decided by the "Community" ? You (and your fellows) have seemingly a 'secret' list of 'deciders' who make the decisions what is on/of with Joomla? Who make these decisions? Back to Mambo days?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9614">issues.joomla.org/joomla-cms/9614</a>.</sub>
