### ISSUE TITLE
Error  "You are not permitted to use that link to directly access that page" when using edit icon to access module from front end. Module editing set to administrator. 

### ISSUE THREAD

**Issue by karendunne** [joomla/joomla-cms#9615]
#### Steps to reproduce the issue

Have module options set to edit module via administrator (see screen shot)
Login to front-end
Click on edit icon for a module (see screen shot)
This next step would normally take the user to an open module for editing (see last screen shot)
Instead, it takes the user to the list of modules and gives this error:
"Error. You are not permitted to use that link to directly access that page (#90)"
The (#90) would be which ever the module ID is. (see screen shot)

#### Expected result

To be taken directly to the module for editing, as if I had opened it from the administrator to begin with 

#### Actual result

Leads to the module administrator page with the error highlighted in pink:
"Error. You are not permitted to use that link to directly access that page (#90)"
The (#90) would be which ever the module ID is.

#### System information (as much as possible)

Joomla 3.5 
PHP 5.6, also tested in 5.5 with same result
Safari 6.1.6
Firefox 45.0.1
Opera 36.0
Chrome 49.0.2623.108

#### Additional comments

I have tried this on three installations now and the issue is consistent. All three installations were Joomla 3.5. My other sites that are running 3.4.8 work as expected, meaning that when I click on the edit icon it immediately opens the module for editing via the administrator. ![screen shot 2016-03-26 at 21 02 04](https://issues.joomla.org/uploads/1/bf40d817746e18727bd83ad9b66f67a2.png)
![screen shot 2016-03-26 at 21 01 59](https://issues.joomla.org/uploads/1/9149cd5bd0410b36b63d4f44ad940e28.png)
![screen shot 2016-03-26 at 21 02 07](https://issues.joomla.org/uploads/1/1961273439a1973c70954f21a135bc1a.png)![screen shot 2016-03-26 at 21 02 10](https://issues.joomla.org/uploads/1/1c2613f5b9374c2327a233c009b7db93.png)

**Comment by franz-wohlkoenig** [comment]
I guess you don't use "Advanced Module Manager" (AMM) by NoNumbers. 

Had same issue with Core-Module-Manager and AMM if i used AMM 5.3.13. Using AMM 5.3.11 had not this Issue with Core-MM or AMM.

Happened on Sites using Joomla!3.4.8/php5.6 or J3.5/php7 ([Conversation on NoNumber-Forum](https://www.nonumber.nl/forum/advancedmodulemanager-pro/41403-you-are-not-permitted-to-use-that-link-to-directly-access-that-page))

**Comment by franz-wohlkoenig** [comment]
Problem on AMM is found and successfully fixed ([more on Forum](https://www.nonumber.nl/forum/advancedmodulemanager-pro/41403-you-are-not-permitted-to-use-that-link-to-directly-access-that-page?limitstart=0#56785)).

**Comment by marktaylor46** [comment]
I can confirm this issue too. I test with a brand new Joomla 3.5 clean installation (default english sample data) using Protostar template. The only thing I changed was in module manager options to change "edit module" from "site" to "administrator". As soon as you have logged into frontend and click to edit any module your will get the error message reported (whether or not you are logged into the backend).

Regards, Mark.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9615">issues.joomla.org/joomla-cms/9615</a>.</sub>

**Comment by alexmarketaccess** [comment]
Confirmed this is also happening with Joomla 3.5.1. I changed from Administrator to Site, and then I can edit modules in frontend. If I change to Administrator, and edit a module in frontend, I am redirected to backend and get the error messaged reported.

**Comment by andrepereiradasilva** [comment]
Confirmed happening also on latest staging.

To reproduce:
1. Go to com_modules options in the backend and set the frontend edit links as "Administrator" (actually also had the same error when using "Site")
 ![image](https://cloud.githubusercontent.com/assets/9630530/14856213/1de5ebc4-0c8f-11e6-90ec-d8787999b11a.png)

2. Go to global config and activate edit modules on frontend.
 ![image](https://cloud.githubusercontent.com/assets/9630530/14856282/5fd8397e-0c8f-11e6-9221-62cf6b9aed46.png)

3. Go to frontend, login and try to edit a module.
 ![image](https://cloud.githubusercontent.com/assets/9630530/14856332/8839be24-0c8f-11e6-90a5-2188e4232d89.png)

4. Result:
 ![image](https://cloud.githubusercontent.com/assets/9630530/14856412/d9ec8832-0c8f-11e6-90b5-5c81cd51255f.png)

More details: the error comes from here https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_modules/controller.php#L69.

**Comment by andrepereiradasilva** [comment]
@dgt41 can you check?

**Comment by karendunne** [comment]
is there a known timeline for this to be addressed? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9615">issues.joomla.org/joomla-cms/9615</a>.</sub>

**Comment by ggppdk** [comment]
@karendunne 
you may test this PR:

https://github.com/joomla/joomla-cms/pull/10753

**Comment by brianteeman** [comment]
Closing this so we just have one conversation in one place and we have a PR for testing #10753

**Comment by PhilETaylor** [comment]
Please close this as we have PR #13516 which ultimately resolves this with ease.
