### ISSUE TITLE
Message position in com_language

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9617]
#### Steps to reproduce the issue
Try to create a content language and you will see that the position of messages have a span10 when they should have a span12
![screen shot 2016-03-27 at 05 18 32](https://issues.joomla.org/uploads/1/cf43707761b256d628d477a428cde942.png)

**Comment by MATsxm** [comment]
confirmed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9617">issues.joomla.org/joomla-cms/9617</a>.</sub>

**Comment by infograf768** [comment]
on it.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/9621

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9617">issues.joomla.org/joomla-cms/9617</a>

**Comment by infograf768** [comment]
Closing as we have a patch https://github.com/joomla/joomla-cms/pull/9621<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9617">issues.joomla.org/joomla-cms/9617</a>.</sub>
