### ISSUE TITLE
Auto Purge Error Log setting in Global Configuration

### ISSUE THREAD

**Issue by sam-suresh** [joomla/joomla-cms#9620]
#### Steps to reproduce the issue
Currently error logs keep on expanding depending on the extensions used. Mostly PHP warnings/notices or 404s. 
Over the time, error logs used up the storage allocation.

#### Expected result
New setting in Global Configuration to auto purge the error logs with a preset interval like every 30 days.

**Comment by brianteeman** [comment]
If you are getting so many php notices and warnings you really need to get better extensions

**Comment by brianteeman** [comment]
404 should not be logged in any joomla logs anyway - only in server logs which joomla should not touch

**Comment by sam-suresh** [comment]
I manage a hosting and most of the clients error logs will go up to 10GB over months. Having such options will be helpful in this situation if it is possible.

**Comment by sam-suresh** [comment]
And not only me in this case. 
https://www.google.com/search?q=joomla+error+logs&ie=utf-8&oe=utf-8#q=joomla+error+logs+large

**Comment by brianteeman** [comment]
Are you talking about apache error logs?
If so then you really should be using logrotate

On 27 March 2016 at 13:38, Sam Suresh <notifications@github.com> wrote:

> I manage a hosting and most of the clients error logs will go up to 10GB
> over months. Having such options will be helpful in this situation if it is
> possible.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9620#issuecomment-202056154>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sam-suresh** [comment]
I'm referring to the error_log in Joomla folder.
Mostly PHP notices for extensions. 
Or possible to add a override option in Global Config without changing in PHP.INI something like Error reporting option in global configuration. 
A beginner Joomla users without php.ini access (or local php.ini disabled server) will end up large error logs over the time.

**Comment by brianteeman** [comment]
Seriously 10gb of php error logs is due to absolutely terrible extensions

You can of course turn off the logging of notices but s a web host you know
that

On 27 March 2016 at 13:50, Sam Suresh <notifications@github.com> wrote:

> I'm referring to the error_log in Joomla folder.
> Mostly PHP notices for extensions.
> Or possible to add a override option in Global Config without changing in
> PHP.INI something like Error reporting option in global configuration.
> A beginner Joomla users without php.ini access (or local php.ini disabled
> server) will end up large error logs over the time.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9620#issuecomment-202057549>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
This is down to server setup. It should not be Joomla's job to handle the
