### ISSUE TITLE
J3 3.4.7. to 3.5.0 upgrade Error - Table 'advexp_db.#__finder_links_termsc' doesn't exist.

### ISSUE THREAD

**Issue by exlemor** [joomla/joomla-cms#9625]
#### Steps to reproduce the issue
Upgraded to Joomla v3.5.0 from v3.4.7 via the built-in updater and it said that the Upgrade failed.

So then I followed the Method C - [upload via FTP, then Hit Database Fix and Discover] except I am stuck at Database Fix issue.

#### Expected result

Database Updated normally... 

#### Actual result

Error

Table 'advexp_db.#__finder_links_termsc' doesn't exist SQL=ALTER TABLE `#__finder_links_termsc` CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
Table 'advexp_db.#__finder_links_termsc' doesn't exist SQL=ALTER TABLE `#__finder_links_termsc` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

× Warning: Database is not up to date!
1 Database Problem Found.

The Joomla! Core database tables have not been converted yet to UTF-8 Multibyte (utf8mb4).

#### System information (as much as possible)

PHP Built On	                Linux host2.0one0.com 2.6.32-042stab094.7 #1 SMP Wed Oct 22 12:43:21 MSK 2014 x86_64
Database Version	        5.5.48-cll
Database Collation	        latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	                5.3.29
Web Server	                Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla!         3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

phpMyAdmin won't let me add Table 'advexp_db.#__finder_links_termsc', I have tried adding this code:

CREATE TABLE IF NOT EXISTS `xadv_finder_links_termsc` (
  `link_id` int(10) unsigned NOT NULL,
  `term_id` int(10) unsigned NOT NULL,
  `weight` float unsigned NOT NULL,
  PRIMARY KEY (`link_id`,`term_id`),
  KEY `idx_term_weight` (`term_id`,`weight`),
  KEY `idx_link_term_weight` (`link_id`,`term_id`,`weight`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

-- --------------------------------------------------------

and it replies: Table 'advexp_db.xadv_finder_links_termsc' doesn't exist

I tried:

CREATE TABLE `xadv_finder_links_termsc` (
  `link_id` int(10) unsigned NOT NULL,
  `term_id` int(10) unsigned NOT NULL,
  `weight` float unsigned NOT NULL,
  PRIMARY KEY (`link_id`,`term_id`),
  KEY `idx_term_weight` (`term_id`,`weight`),
  KEY `idx_link_term_weight` (`link_id`,`term_id`,`weight`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4;

and it replies again: Table 'advexp_db.xadv_finder_links_termsc' doesn't exist

#### Additional comments

Until this is fixed, I can't update the database for this site - I fear corruption.

**Comment by exlemor** [comment]
I 'was' able after spending quite a bit of time in PHPMyAdmin to fix the database so that I was able to then Fix the Database.

However this should still not be happening.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9625">issues.joomla.org/joomla-cms/9625</a>.</sub>

**Comment by richard67** [comment]
> Upgraded to Joomla v3.5.0 from v3.4.7 via the built-in updater and it said that the Upgrade failed.

Would be interesting to know details about how it failed, i.e. if there were errors shown and if so, which, or same for php error log (if enabled).

And it also would be good to know when it failed, after file writing was finished with 100% bar for a while, then the problem could have happened when updating the database, or before, then there could have been a problem with writing or deleting files or folders.

Then it could be possible to find out how it came to this unfixable state.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9625">issues.joomla.org/joomla-cms/9625</a>.</sub>

**Comment by jimiero** [comment]
I think this may be related also, I have com_newsfeeds uninstall from the website, and when updated to J3.5.0 I get this errors:

Table 'mytable_testdb.#__newsfeeds' doesn't exist SQL=SHOW COLUMNS IN `#__newsfeeds` WHERE Field = 'filename'
Table 'mytable_testdb.#__newsfeeds' doesn't exist SQL=SHOW COLUMNS IN `#__newsfeeds` WHERE field = 'description'
Table 'mytable_testdb.#__newsfeeds' doesn't exist SQL=SHOW COLUMNS IN `#__newsfeeds` WHERE field = 'version'
Table 'mytable_testdb.#__newsfeeds' doesn't exist SQL=SHOW COLUMNS IN `#__newsfeeds` WHERE field = 'hits'
Table 'mytable_testdb.#__newsfeeds' doesn't exist SQL=SHOW COLUMNS IN `#__newsfeeds` WHERE field = 'images'

**Comment by brianteeman** [comment]
As stated elsewhere that is to be expected as the update has no way of knowing that you have removed a core compoenent

**Comment by jimiero** [comment]
@brianteeman any way to get around this and so I can be able to run Database fix ? I also see there's another point there saying:

The Joomla! Core database tables have not been converted yet to UTF-8 Multibyte (utf8mb4).

**Comment by richard67** [comment]
@jimiero Your stuff is absolutely not related to this issue.

**Comment by richard67** [comment]
@jimiero  Do a "discovery extensions" and install back the com_newsfeeds which should be discovered, then use the database fix button. But this is not a support forum, so further question please to [http://forum.joomla.org/](http://forum.joomla.org/).
