### ISSUE TITLE
insertid return 0 when upgrade to 3.5

### ISSUE THREAD

**Issue by rickynguyen** [joomla/joomla-cms#9627]
#### Steps to reproduce the issue

1. Step1: Set JConfig $dbtype = 'pdomysql';
2. Step2: Insert new record to db

         $session = JFactory::getSession();
        $objectUpload = new stdClass();
        $objectUpload->Id = null;
        $objectUpload->machine_id = UploadHelper::getMachineId();
        $objectUpload->file_list = json_encode([$attachment]);
        $objectUpload->session_token = $session->getId();
        $objectUpload->attachment_key = $attachmentKey;
        $objectUpload->attachment_type = $attachmentType;
        $objectUpload->status = $isInitialize == 'true' ? 0 : 4;
        $objectUpload->add_timestamp = time();

        $result = JFactory::getDbo()->insertObject('#__upload_queue', $objectUpload, 'Id');

#### Expected result
        $result=>Id > 0
#### Actual result
        $result=>Id  == 0

#### System information (as much as possible)

[phpinfo.html.zip](https://github.com/joomla/joomla-cms/files/191572/phpinfo.html.zip)

**Comment by zero-24** [comment]
This is a known problem and sould be resolved with 3.5.1

You can also apply this patch here: https://github.com/joomla/joomla-cms/commit/aa99b1090981987109d4a23de2d46a7f28ee4c0f

**Comment by rickynguyen** [comment]
Thnk bro!
