### ISSUE TITLE
( ! ) Fatal error: Class 'JToolbarHelper' not found

### ISSUE THREAD

**Issue by hienduchuynh** [joomla/joomla-cms#9629]
#### Steps to reproduce the issue
- Upgrade Joomla 3.4.8 to Joomla 3.5.0
- Login Admin account in Frontend
- Edit a article
- Click Module button ( to load a module to article )

#### Actual result
( ! ) Fatal error: Class 'JToolbarHelper' not found

#### Solution
open administrator/components/com_modules/views/modules/view.html.php file and add 

```
if(!class_exists('JToolbarHelper')) {
   require_once JPATH_ADMINISTRATOR . '/includes/toolbar.php';
}
```
after 
`defined('_JEXEC') or die;`

**Comment by brianteeman** [comment]
Confirmed the error (not had chance to check the fix yet)

**Comment by zero-24** [comment]
@hienduchuynh

Can you send your changes as pull request against the staging branch?

**Comment by mbabker** [comment]
See #9637
