### ISSUE TITLE
after upgrading to 3.5.0 baseurl ?> no longer functional in template

### ISSUE THREAD

**Issue by sanderhartveld** [joomla/joomla-cms#9630]
#### Steps to reproduce the issue
upgrade to 3.5.0 from previous version 3.4.8
I have a logo in my template with a link to <?php echo $this->baseurl ?>

#### Expected result
the link should go to the baseurl 

#### Actual result
no value is produced

**Comment by andrepereiradasilva** [comment]
The link should be `href="<?php echo $this->baseurl ?>/"` (notice the slash on the end).

Or you can wait for 3.5.1 that will resolve that issue.

**Comment by andrepereiradasilva** [comment]
BTW this has solved here https://github.com/joomla/joomla-cms/pull/9575

@brianteeman can be closed.

**Comment by brianteeman** [comment]
Closed as requested
