### ISSUE TITLE
clear search in list view no longer working

### ISSUE THREAD

**Issue by sanderhartveld** [joomla/joomla-cms#9632]
#### Steps to reproduce the issue
In the administrator backend of Joomla 3.5.0 you can search on the pages that list articles or modules. 

#### Expected result
If you want to clear your search with the clear button Joomla should forget the search parameters

#### Actual result
Joomla remembers your search thus not allowing to view all items

#### System information (as much as possible)
this occured after upgrade to 3.5.0 from 3.4.8
PHP Version 5.6.17
suhosin v0.9.36

#### Additional comments

**Comment by brianteeman** [comment]
I cannot replicate this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9632">issues.joomla.org/joomla-cms/9632</a>.</sub>

**Comment by MixingOnBeat** [comment]
Hmm?  I believe you are experiencing an issue I reported since Dec. 2015 -- which never got fix.  Devs decided to blame it on PHP than try to figure out a global fix.  I use other PHP products and their search features work fine.

Check out this ticket: https://github.com/joomla/joomla-cms/issues/8641

A workaround, is replace your search box with a space, then press search, that will allow you to do another search and so on.  Sucks, but that's all we got for now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9632">issues.joomla.org/joomla-cms/9632</a>.</sub>

**Comment by izharaazmi** [comment]
@sanderhartveld Please include suhosin version in the system information above. Also see https://github.com/joomla/joomla-cms/issues/8421#issuecomment-172896473

**Comment by sanderhartveld** [comment]
@izharaazmi suhosin version added

**Comment by izharaazmi** [comment]
I created a plugin to workaround this issue. You can download it here https://github.com/izharaazmi/joomla-suhosinfix/releases.

Endorse me on [LinkedIn](http://in.linkedin.com/in/izharaazmi), if you feel like. :smile:

**Comment by MixingOnBeat** [comment]
@izharaazmi just loaded your plugin on Joomla 3.5.1 and it's working good.

I tested the search function first to see if in case 3.5.1 update would fix it, but no.  So I then loaded your plugin and enabled it.  Now I can clear my searches in the admin panel.

Thanks! :)

**Comment by sanderhartveld** [comment]
@izharaazmi it works for me too. Accept my linkedin invitation and I will endorse you.

Regards,
Sander

+31 (0)6 413 88 454 (mobile)

P
Denk aan het milieu; druk deze e-mail alleen af als het echt nodig is.


Groet,
Sander

+31 (0)6 413 88 454 (mobile)

P
Denk aan het milieu; druk deze e-mail alleen af als het echt nodig is.

> Op 9 apr. 2016 om 02:35 heeft MOB <notifications@github.com> het volgende geschreven:
> 
> @izharaazmi

**Comment by izharaazmi** [comment]
Can we close this?... as this is not a Joomla issue and has a working workaround provided.
Can this plugin find a place (don't know which category) in JED?

**Comment by sanderhartveld** [comment]
Yes, please close this

Groet,
Sander

+31 (0)6 413 88 454 (mobile)

P
Denk aan het milieu; druk deze e-mail alleen af als het echt nodig is.

**Comment by brianteeman** [comment]
Closed as requested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9632">issues.joomla.org/joomla-cms/9632</a>.</sub>
