### ISSUE TITLE
In Front-end article edit view, image option having faulty Caption Class drop down menu box.

### ISSUE THREAD

**Issue by shubhamnba2009** [joomla/joomla-cms#9639]
#### Steps to reproduce the issue
1.Go to front-end.
2.Select article and choose edit option.
3.From edit menu select image option.
4.Select Caption Class option.
5.Again click on Caption Class option

#### Expected result
The dropdown menu should disappear.

#### Actual result
The dropdown menu remains as it is.

#### System information (as much as possible)
joomla 3.5.0
 OS Windows
 PHP 5.6.15
 MySQL 5.5.5-10.1.9-MariaDB

#### Additional comments
Jquery might help here.

**Comment by MATsxm** [comment]
I don't know if it's the same issue but here's another step by step "how to reproduce":
-neither frontend or backend, Edit an article (TinyMCE)
-insert an image with the Tab: "Image"
-the dropdown menu for "Caption Class" doesn't appear like it should (see: the "Image float" dropdown menu)
-select for example: `text-left`then try to change it, it's not possible.

@shubhamnba2009 
Is this the same as yours?


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9639">issues.joomla.org/joomla-cms/9639</a>.</sub>

**Comment by shubhamnba2009** [comment]
Yeah this also and that once the dropdown menu is down it won't disappear on clicking again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9639">issues.joomla.org/joomla-cms/9639</a>.</sub>

**Comment by brianteeman** [comment]
Please test #9754<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9639">issues.joomla.org/joomla-cms/9639</a>.</sub>

**Comment by Bakual** [comment]
The caption class is a regular textfield, the "dropdown" you see is a suggestion list using the "datalist" HTML element. It's not meant to act like a regular select box as you can enter anything you want into that field.
How it behaves depends on the browser.

**Comment by brianteeman** [comment]
As that is not a UI convention we use anywhere else it causes the confusion above
