### ISSUE TITLE
Joomla 3.5 Submenu when install a component

### ISSUE THREAD

**Issue by diarcastro** [joomla/joomla-cms#9640]
#### Steps to reproduce the issue
Try to install a component with a submenu, like this: 
```
... <administration>
    <menu img="class:bill">com_bill</menu>
    <submenu>
    	<menu link="option=com_bill&amp;view=users" view="users" img="class:users" alt="Bill/Users">com_bill_users</menu>
		</submenu>
</administration> ...
```
#### Expected result
Bill Menu with Users submenu
![2016-03-28_17-10-58](https://cloud.githubusercontent.com/assets/2319600/14091819/19ca7e4a-f508-11e5-836b-4372f376b82b.png)

#### Actual result
Bill menu without a Users submenu
![2016-03-28_17-03-46](https://cloud.githubusercontent.com/assets/2319600/14091647/19aca858-f507-11e5-8b53-1dc2b3bd1f9b.png)

#### System information (as much as possible)
Joomla menu table
![2016-03-28_17-05-05](https://cloud.githubusercontent.com/assets/2319600/14091686/4f24b692-f507-11e5-9b32-df1ab3f2dcb3.png)

#### Additional comments
Also the menu item in database don't have a parent menu and component id.

The component installer install successfully in joomla 3.4.8

[Download demo bill component](http://we.tl/agd4Nc10HS)

**Comment by brianteeman** [comment]
I just installed it on my test site and it installed perfectly - see screenshot
![screen shot 2016-03-29 at 04 11 11](https://issues.joomla.org/uploads/1/a4175c18ba1dff2ee32cbd0f2263acf6.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9640">issues.joomla.org/joomla-cms/9640</a>.</sub>

**Comment by infograf768** [comment]
I confirm it works OK here too on staging/3.5.1-rc1

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9640">issues.joomla.org/joomla-cms/9640</a>.</sub>
