### ISSUE TITLE
3.4 to 3.5 Upgrade overwrites old Protostar CSS and JS

### ISSUE THREAD

**Issue by greenorca** [joomla/joomla-cms#9641]
#### Steps to reproduce the issue
Some modifications in Protostar template.css and template.js file on Jommla3.4 installation.
Upgrading from Joomla 3.4 to 3.5. overwrites/replaces these files without comment, therefore ruining any customizations in there...

#### Expected result
Customized protostar template is not altered by upgrade, or at least a notification is issued during upgrade process. 

#### Actual result
Customized protostar template is altered without notice by upgrade

#### System information (as much as possible)
I don't think it is system depended.

#### Additional comments
Beside that - good work guys!

**Comment by Bakual** [comment]
Of course it does. Never modify core files directly, they will be overwritten on updates.
If you want to customize the Protostar template, either add a user.css oder make a copy of the template (template manager allows to do so).

Closing as expected behavior.
