### ISSUE TITLE
3.4.8 to 3.5 Updade overwrites old Protostar CSS and JS

### ISSUE THREAD

**Issue by greenorca** [joomla/joomla-cms#9642]
#### Steps to reproduce the issue
Customize Protostar template.css and template.js
Run update.

#### Expected result
After updating, the website still looks as before. This worked fairly well on previous updates (

#### Actual result
Default Protostar template css and template.js replaced the customized files

#### System information (as much as possible)
3.4.8 --> 3.5; other than that I guess it is not a system specific thing...

#### Additional comments
Overall: great work guys!

**Comment by infograf768** [comment]
Customising protostar and expecting the behavior to be the same after an update where some stuff has been changed (for certainly good reasons)is wrong.

For sure it never happened in the past. You may have had a cache set which gave you the feeling it was the same.

The only way to be sure to keep your custom stuff is to Copy the template through Exensions=>Templates and use that instance of the core template. Evidently, it is strongly suggested to have a look at the changes introduced in core and use them or not in your copy.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9642">issues.joomla.org/joomla-cms/9642</a>.</sub>

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9642">issues.joomla.org/joomla-cms/9642</a>

**Comment by infograf768** [comment]
Closing as this is expected behavior.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9642">issues.joomla.org/joomla-cms/9642</a>.</sub>
