### ISSUE TITLE
Joomla 3.5.0 doesn't allow using underscore character in permission name

### ISSUE THREAD

**Issue by joomdonation** [joomla/joomla-cms#9645]
#### Steps to reproduce the issue

1. Open the file administrator/components/com_content/access.xml
2. Add a new permission which has underscore character (for example content.view_content) to component section. Example: 
`<action name="content.view_content" title="View Content" description="Allows viewing articles" />`
3. Go to System -> Global Configuration, select Articles component, Permissions tab (http://localhost/joomla35/administrator/index.php?option=com_config&view=component&component=com_content).
4. Try to change permission for **View Content** permission

#### Expected result

The permission successfully saved

#### Actual result

The permission is not saved.

#### System information (as much as possible)

Joomla 3.5.0

#### Additional comments

It was possible to working well before well before 3.5.0. So this issue can break third party extensions which use have permission name contains underscore character.

**Comment by brianteeman** [comment]
I can confirm this as a changed behaviour in 3.5 - I suspect it is something to do with the ajaxifying of that page<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9645">issues.joomla.org/joomla-cms/9645</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we have a PR #9648 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9645">issues.joomla.org/joomla-cms/9645</a>.</sub>
