### ISSUE TITLE
Batch move menu loses heirarchy

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9651]
#### Steps to reproduce the issue

Select a parent menu item and its children and batch move to a new menu
#### Expected result

Parent and children successfully moved
#### Actual result

Parent and children moved BUT all to the same level

**Comment by peteruoi** [comment]
and as a reminder a little relevant with batch actions #8600

**Comment by richard67** [comment]
@brianteeman Your expected result is wrong from my point of view. If you select the new target for all of the menu items, you will move them all to the new target, so I would expect actual result.

The result which you expect, I would expect after selecting the parent only and moving this one. It should move the parent including all children.

Or am I wrong?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9651">issues.joomla.org/joomla-cms/9651</a>.</sub>

**Comment by brianteeman** [comment]
If I select an entire tree and move it then I expect it to stay as a tree.
Why would I not?

**Comment by richard67** [comment]
Because you select same target for all. And when selecting the partent only and moving that, it copies the children with keeping the tree. So I would expect that to be desired behavior, but I agree with you that it confused me, too, when I first time noticed that.

**Comment by brianteeman** [comment]
Select all the items in a tree and MOVE to  new menu - all the items are
not at the same level in the new menu
Select all the items in a tree and COPY to  new menu - all the items are at
existing tree levels in the new menu

On 29 March 2016 at 18:50, Richard Fath <notifications@github.com> wrote:

> Because you select same target for all. And when selecting the partent
> only and moving that, it copies the children with keeping the tree. So I
> would expect that to be desired behavior, but I agree with you that it
> confused me, too, when I first time noticed that.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9651#issuecomment-202994225>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by richard67** [comment]
Oh, this is in fact inconsistent, so you are right and there is an issue. Sorry for having had doubts.

**Comment by franz-wohlkoenig** [comment]
Would expect same Behaviour on Move and Copy like its now at Move.

**Comment by alikon** [comment]
i'm unable to reproduce

[![testing](http://img.youtube.com/vi/-geEuYb4cYM/0.jpg)](http://www.youtube.com/watch?v=-geEuYb4cYM)

**Comment by brianteeman** [comment]
Thanks for the video @alikon
In your case you selected the parent only and it moved the parent and children and kept the tree (and I can confirm this)
But in my case I had selected the parent AND the children and when I did the move they were all now as root level (no hierarchy) but when I did a copy the hierarchy was maintained<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9651">issues.joomla.org/joomla-cms/9651</a>.</sub>

**Comment by richard67** [comment]
Question is: Which way should be the right one? It seems some prefer like it is now with copying, and some prefer like it is now with moving. Maybe it needs a kind of voting?

**Comment by franz-wohlkoenig** [comment]
Does one know Reason(s) for this Difference in Copy or Move?

**Comment by brianteeman** [comment]
I assume it is a bug

**Comment by alikon** [comment]
i'm not sure wich is the correct behviour for move & copy ,but,

in the case you select the parent and the children , and , we suppose that we are "moving a tree" 
i think the children does not matter if it is selected or not cause  the parent (tree) should be moved
where the selected children item is already in that tree
.... surely i'm supposing too much....

@franz-wohlkoenig yes, the batch modal  window is quite unusable can you open an issue?

**Comment by brianteeman** [comment]
There already is a fix for the modal iirc

**Comment by franz-wohlkoenig** [comment]
Started this Moment writing an Issue, stopped immediately; thanks @brianteeman

**Comment by simbus82** [comment]
For me is correct moving/copying the "tree" as is: it is very non-logic that if i select all voices from a tree then i see all voices moved/copied to the same level.

And there is no "clear" indication of how it works when we click the batch button... maybe is right to add a short guide in the modal window.

**Comment by brianteeman** [comment]
Is it correct that it works differently for move and copy?

On 31 March 2016 at 09:32, Simone Bussoni <notifications@github.com> wrote:

> For me is correct moving/copying the "tree" as is: it is very non-logic
> that if i select all voices from a tree then i see all voices moved/copied
> to the same level.
>
> And there is no "clear" indication of how it works when we click the batch
> button... maybe is right to add a short guide in the modal window.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9651#issuecomment-203796858>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by simbus82** [comment]
@brianteeman in my honest opinion, no.
If i have a tree, i want that is the same after a move or after a copy to other menu.
Maybe, for who have to "disassemble" a menu tree, we can add a yes/no radio "keep the level tree".

**Comment by brianteeman** [comment]
Sorry I misread your original comment as if you were saying the current
behaviour was correct. I should have drunk more coffee

On 31 March 2016 at 09:42, Simone Bussoni <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> in my honest opinion, no.
> If i have a tree, i want that is the same after a move or after a copy to
> other menu.
> Maybe, for who have to "disassemble" a menu tree, we can add a yes/no
> radio "keep the level tree".
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9651#issuecomment-203801740>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by simbus82** [comment]
I'm saying that you are right :-) The actual batch is not working very well, copy do a thing, move do another thing... a little confusing!

**Comment by brianteeman** [comment]
So long and farewell
