### ISSUE TITLE
Search feature on public pages not working after update to 3.5

### ISSUE THREAD

**Issue by MixingOnBeat** [joomla/joomla-cms#9654]
#### Steps to reproduce the issue

I just go to any public page where the search feature is available and enter a word to search.

#### Expected result

It should show me a page with the results.

#### Actual result

Just an empty white page.  No results, nothing.  Not even telling me that no results have been found.

#### System information (as much as possible)

OS Linux n
PHP 5.6.17
MySQL 5.6.29
Caching Enabled
GZip Enabled
Users 1
Articles 204

#### Additional comments

Not sure if it's related, but my site generates a new entry in my error_log when I test the search feature.  He is the latest entry (they are say the same).

`[29-Mar-2016 15:21:17 America/Toronto] PHP Fatal error:  Call to a member function setState() on boolean in /home/public_html/modules/mod_related_items/helper.php on line 44
`

When I was on Joomla 3.4.8. The search feature was working okay.

Now after I updated to Joomla 3.5 the search results gives me blank page. Not even the theme shows on the blank page. Broken maybe?

I updated from 3.4.8 to 3.5 via the Joomla! Update component. Plus I cleared my cache. I can't seem to understand why it's broken? Anyone?

**Comment by andrepereiradasilva** [comment]
i think this is the same issue of https://github.com/joomla/joomla-cms/issues/9518

Which is resolved on 3.5.1 RC2 by https://github.com/joomla/joomla-cms/pull/9519

**Comment by MixingOnBeat** [comment]
@andrepereiradasilva 

Thank you.  The fix proposed at: 3.5.1 RC2 by https://github.com/joomla/joomla-cms/pull/9519 fixes my issue with the Search bug I reported above.

**Comment by wilsonge** [comment]
I'm going to close this ticket then. But thank you very much for reporting this :) It's always better to get multiple reports than none at all!
