### ISSUE TITLE
"Button - Module"  plugin not installed during 3.5.0 update

### ISSUE THREAD

**Issue by jentekk** [joomla/joomla-cms#9656]
#### Steps to reproduce the issue
Manual upgrade from Joomla 3.4.8 to Joomla 3.5.0:
- uploaded the Joomla_3.5.0-Stable-Update_Package.zip file to my server, and unpacked it to the root folder.
Logged into my website and noted that Joomla had been updated to 3.5.0.
Fixed the database, and began looking through the Administrator area for any obvious issues. 

#### Expected result
Expected to see the Module Button at the bottom of the content editor (JCE)

#### Actual result
Module Button not showing up at the bottom of the Article JCE text-box. Went to Extensions/Plugins and noticed that the "Button - Module" had not been installed.

#### System information (as much as possible)
PHP Built On: Linux s3-xxxxx.xxxxx.com 3.14.25-grsec.3.el5 #1 SMP Thu Apr 2 14:45:16 UTC 2015 x86_64
Database Version: 5.5.40-36.1-log
Database Collation: utf8_general_ci
Database Connection Collation: utf8mb4_general_ci
PHP Version: 5.4.45
Web Server: Apache
WebServer to PHP Interface: cgi-fcgi
Joomla! Version: Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0 

#### Additional comments
Cleared the cache several times, even re-uploaded the zip file and unpacked it again, with no better results.

**Comment by jentekk** [comment]
So... I just went to: Extensions > Manage > Discover

There are a bunch of items including the "Button - Module" plugin that had not been installed.

I installed the plugin from there, enabled it and now we're good to go. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9656">issues.joomla.org/joomla-cms/9656</a>.</sub>

**Comment by jentekk** [comment]
Other items that had not been installed during the normal process, see screenshot.

![screen shot 2016-03-29 at 15 28 52](https://issues.joomla.org/uploads/1/731fafb0469bb357144b123951e9b613.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9656">issues.joomla.org/joomla-cms/9656</a>.</sub>

**Comment by richard67** [comment]
Yes, that's quiet normal after the manual update procedure you used.

See also the update documentation for 3.5.0 linked here: [https://docs.joomla.org/J3.x:Upgrading_from_Joomla_3.4.x_to_3.5](https://docs.joomla.org/J3.x:Upgrading_from_Joomla_3.4.x_to_3.5 "https://docs.joomla.org/J3.x:Upgrading_from_Joomla_3.4.x_to_3.5"), Step 3 for Method C.

After installing the discovered extensions, all should be updated.

It seems you used this method also before to update to 3.4.8, because some of the discovered extensions are older than 3.4.8.

So from my point of view there is no issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9656">issues.joomla.org/joomla-cms/9656</a>.</sub>

**Comment by richard67** [comment]
Sorry, I mean Step **5** and not Step 3 of Method C in the documentation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9656">issues.joomla.org/joomla-cms/9656</a>.</sub>

**Comment by jentekk** [comment]
Yes, after all that, there is no issue. Thank you, it really was my error. <<< embarrassed >>><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9656">issues.joomla.org/joomla-cms/9656</a>.</sub>

**Comment by zero-24** [comment]
Can you please close this issue than? ;)

**Comment by jentekk** [comment]
Thanks Zero, please bear with me. How do I close this???  :)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9656">issues.joomla.org/joomla-cms/9656</a>.</sub>

**Comment by jentekk** [comment]
Thanks to you both Richard and Zero. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9656">issues.joomla.org/joomla-cms/9656</a>.</sub>

**Comment by richard67** [comment]
Welcome ... always happy if something can be solved.
