### ISSUE TITLE
Problem with editing Modules from front end

### ISSUE THREAD

**Issue by carterdonald** [joomla/joomla-cms#9657]
#### Steps to reproduce the issue
tried to edit Modules from front end as Super User

#### Expected result
Module would open up so that it can be edited

#### Actual result
recieved the following message
"Calendar.setup:
  Nothing to setup (no fields found).  Please check your code"

#### System information (as much as possible)
Joomla 3.4 or 3.5 and Helix 3 Framework It also occurs on Joomla Project Templates

**Comment by brianteeman** [comment]
Was it a specific module or all modules<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9657">issues.joomla.org/joomla-cms/9657</a>.</sub>

**Comment by carterdonald** [comment]
All modules on all of the pages
Don

Sent from my iPad

On Mar 29, 2016, at 3:19 PM, Brian Teeman <notifications@github.com<mailto:notifications@github.com>> wrote:


Was it a specific module or all modules

________________________________
This comment was created with the J!Tracker Application<https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9657<https://issues.joomla.org/tracker/joomla-cms/9657>.

-

**Comment by brianteeman** [comment]
Thanks - then it makes no sense that  error message - are you sure that you
get the same error when using one of the default joomla templates eg
protostar as I can not replicate it

**Comment by carterdonald** [comment]
Yes - but I will try again right now
Don

Sent from my iPad

On Mar 29, 2016, at 4:51 PM, Brian Teeman <notifications@github.com<mailto:notifications@github.com>> wrote:

Thanks - then it makes no sense that error message - are you sure that you
get the same error when using one of the default joomla templates eg
protostar as I can not replicate it

-

**Comment by matrikular** [comment]
I can not recreate the issue.

Tested in Protostar with Menus (direct and partial ~ level), mod_custom and mod_articles_popular

**Comment by carterdonald** [comment]
Once I cleared the cash I was able to replicate in beez3.
Please let me know if you need access to my website front or backend.
All the best
Don

Sent from my iPad

On Mar 30, 2016, at 2:35 PM, matrikular <notifications@github.com<mailto:notifications@github.com>> wrote:


I can not recreate the issue.

Tested in Protostar with Menus (direct and partial ~ level), mod_custom and mod_articles_popular

-

**Comment by brianteeman** [comment]
Is it even possible to do frontend editing with beez?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9657">issues.joomla.org/joomla-cms/9657</a>.</sub>

**Comment by matrikular** [comment]
@brianteeman due to a bug (styling / markup) it isn't - I was wondering myself.

**Comment by brianteeman** [comment]
This makes no sense at all. No one has been able to replicate it and the original reporter @carterdonald reports the issue in somewhere the functionality does not exist. 

@carterdonald can you please confirm that you have this issue with Joomla 3.5.1 and using the protostar template<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9657">issues.joomla.org/joomla-cms/9657</a>.</sub>

**Comment by brianteeman** [comment]
It has been over a month since the request for further information. As there has been no response I am now closing this issue. It can always be reopened if the information is provided.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9657">issues.joomla.org/joomla-cms/9657</a>.</sub>
