### ISSUE TITLE
Joomla and extensions upgrade alert looks odd in desktop resolutions

### ISSUE THREAD

**Issue by jochendaum** [joomla/joomla-cms#9661]
#### Steps to reproduce the issue

- download and install Joomla < 3.5.0
- install not-up-to-date extension, ensure extension has auto-updater active
- login to Administrator backend

#### Expected result

After a couple of seconds you would be notified about a Joomla upgrade and Extension upgrades being available. These notifications would be best displayed below each other:
- This is common UX
- If the alert boxes are of different height due to screen resolution, they appear misaligned

There should also be visual space between the alert boxes to distinguish them. The space should be of a common "width" as used elsewhere in the control panel

#### Actual result

The boxes are beside each other in resolutions wider tnan 1200px
The boxes have no space between them

#### System information (as much as possible)

Should be reproducible on any desktop browser

**Comment by brianteeman** [comment]
Thanks for reporting this and submitting a Pull Request - you dont need to do both - when you submit the pull request it is automatically added to the issue tracker - so I am closing this as we have #9662<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9661">issues.joomla.org/joomla-cms/9661</a>.</sub>
