### ISSUE TITLE
BROKEN LINK HOME- JOOMLA 3.5 - GANTRY 5

### ISSUE THREAD

**Issue by zuluu8** [joomla/joomla-cms#9667]
#### Steps to reproduce the issue
i´m using joomla 3.5 with gantry 5. The logo particle should go to home, it do it at home page but not link from others sections in the same web.

#### Expected result

go alwayt to home

#### Actual result

ERROR 500

**Comment by zero-24** [comment]
@zuluu8 please try an default template to make sure that it is not a template issue.

Please confim that you use the last version of the template. If it work with the default template please contact your template provider ;)

Thanks.

**Comment by zuluu8** [comment]
i´m using the last version of the template, in fact is the default template of Gantry 5 (hydrogen template)

At gantry website told me i should explain this problem in this forum.

thank you.

**Comment by zero-24** [comment]
Great. That you found it can you close here than? Thanks.

**Comment by zuluu8** [comment]
@zero-24  i haven´t found the solution, please, what can i do?

**Comment by zero-24** [comment]
>At gantry website told me i should explain this problem in this forum.

this is no forum this is a issue tracker for bugs in the core system of Joomla ;) The forum is at forum.joomla.org :smile:

**Comment by zuluu8** [comment]
@zero-24   ok, i´m sorry i didn´t know it is a issue tracker, but an user of Gantry support send me this URL to explain the problem...

what can i do please? in the forum.joomla.org i posted the problem but users told me somebody broke something in the last version of joomla...

thanks.

**Comment by zuluu8** [comment]
i should finish this problem this week to finish my job :(

**Comment by zero-24** [comment]
I can't see any response that told you it is a problem with the core: http://forum.joomla.org/viewtopic.php?f=737&t=916009&p=3383413

I have just installed joomla-pkg_gantry5_v5.2.13.zip and joomla-tpl_g5_hydrogen_v5.2.13.zip. I can't see any logo that return a error 500.

>At gantry website told me i should explain this problem in this forum.

What gantry webseite?

**Comment by zuluu8** [comment]
http://www.joomla.formacionodontologica.com/

**Comment by zuluu8** [comment]
@zero-24 http://www.joomla.formacionodontologica.com/

**Comment by brianteeman** [comment]
This is not an issue for the tracker <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9667">issues.joomla.org/joomla-cms/9667</a>.</sub>

**Comment by zuluu8** [comment]
@zero-24 so, what do you think is the problem please?

**Comment by mahagr** [comment]
Behaviour of `JURI::base(true);` changed, which is fully described in issue #9554 which were then fixed in #9575.

**Comment by mbabker** [comment]
JUri behavior did NOT change.  The system SEF plugin previously dealt with
scenarios where the href attribute was completely empty, doesn't in 3.5.0,
and does again in 3.5.1.

**Comment by mahagr** [comment]
Thanks @mbabker, I'm seeing the issue now. :)
