### ISSUE TITLE
Internal server error on system information page in backend

### ISSUE THREAD

**Issue by jjnxpct** [joomla/joomla-cms#9672]
#### Steps to reproduce the issue

1. Switching from PHP 5.6.17 to PHP 7 on the server 
2. Open 'System' -> 'System Information' in the backend.

#### Expected result

Show system info...

#### Actual result

Internal Server Error

#### System information (as much as possible)

Linux
Database version: 5.5.44-MariaDB-cll-lve
Webserver: Apache/2
litespeed
Joomla! 3.5.0 Stable

#### Additional comments

Form the error logs:

[Wed Mar 30 15:39:32.944881 2016] [lsapi:error] [pid 978448:tid 140354095249152] [client 93.186.191.244:44338] [host www.inxpact.nl] Error receiving response header (lsphp is killed?): ReceiveResponseHeader: receive pkg hdr failed: ReceivePkgHdr: nothing to read from backend socket, referer: https://www.inxpact.nl/administrator/index.php?m9hqj1u6lj
[Wed Mar 30 15:39:32.944923 2016] [lsapi:warn] [pid 978448:tid 140354095249152] [client 93.186.191.244:44338] mod_lsapi: re-sending previously crashed request again (1), referer: https://www.inxpact.nl/administrator/index.php?m9hqj1u6lj
[Wed Mar 30 15:39:32.944955 2016] [lsapi:error] [pid 978448:tid 140354095249152] [client 93.186.191.244:44338] [host www.inxpact.nl] Backend error on sending request(GET /administrator/index.php?option=com_admin&view=sysinfo HTTP/1.1); uri(/administrator/index.php?option=com_admin&view=sysinfo) content-length(0) (lsphp is killed?): SendRequest: write to backend socket failed: errno 9, referer: https://www.inxpact.nl/administrator/index.php?m9hqj1u6lj
[Wed Mar 30 15:40:41.482596 2016] [lsapi:error] [pid 978558:tid 140354212747008] [client 93.186.191.244:44362] [host www.inxpact.nl] Error receiving response header (lsphp is killed?): ReceiveResponseHeader: receive pkg hdr failed: ReceivePkgHdr: nothing to read from backend socket, referer: https://www.inxpact.nl/administrator/index.php?option=com_cache
[Wed Mar 30 15:40:41.482639 2016] [lsapi:warn] [pid 978558:tid 140354212747008] [client 93.186.191.244:44362] mod_lsapi: re-sending previously crashed request again (1), referer: https://www.inxpact.nl/administrator/index.php?option=com_cache
[Wed Mar 30 15:40:41.482667 2016] [lsapi:error] [pid 978558:tid 140354212747008] [client 93.186.191.244:44362] [host www.inxpact.nl] Backend error on sending request(GET /administrator/index.php?option=com_admin&view=sysinfo HTTP/1.1); uri(/administrator/index.php?option=com_admin&view=sysinfo) content-length(0) (lsphp is killed?): SendRequest: write to backend socket failed: errno 9, referer: https://www.inxpact.nl/administrator/index.php?option=com_cache
[Wed Mar 30 15:42:21.255995 2016] [lsapi:error] [pid 978448:tid 140354204354304] [client 93.186.191.244:44390] [host www.inxpact.nl] Error receiving response header (lsphp is killed?): ReceiveResponseHeader: receive pkg hdr failed: ReceivePkgHdr: nothing to read from backend socket, referer: https://www.inxpact.nl/administrator/index.php?option=com_plugins&view=plugins
[Wed Mar 30 15:42:21.256036 2016] [lsapi:warn] [pid 978448:tid 140354204354304] [client 93.186.191.244:44390] mod_lsapi: re-sending previously crashed request again (1), referer: https://www.inxpact.nl/administrator/index.php?option=com_plugins&view=plugins
[Wed Mar 30 15:42:21.256070 2016] [lsapi:error] [pid 978448:tid 140354204354304] [client 93.186.191.244:44390] [host www.inxpact.nl] Backend error on sending request(GET /administrator/index.php?option=com_admin&view=sysinfo HTTP/1.1); uri(/administrator/index.php?option=com_admin&view=sysinfo) content-length(0) (lsphp is killed?): SendRequest: write to backend socket failed: errno 9, referer: https://www.inxpact.nl/administrator/index.php?option=com_plugins&view=plugins
[Wed Mar 30 15:44:05.897178 2016] [lsapi:error] [pid 978448:tid 140354305066752] [client 93.186.191.244:44452] [host www.inxpact.nl] Error receiving response header (lsphp is killed?): ReceiveResponseHeader: receive pkg hdr failed: ReceivePkgHdr: nothing to read from backend socket, referer: https://www.inxpact.nl/administrator/index.php?option=com_plugins
[Wed Mar 30 15:44:05.897211 2016] [lsapi:warn] [pid 978448:tid 140354305066752] [client 93.186.191.244:44452] mod_lsapi: re-sending previously crashed request again (1), referer: https://www.inxpact.nl/administrator/index.php?option=com_plugins
[Wed Mar 30 15:44:05.897240 2016] [lsapi:error] [pid 978448:tid 140354305066752] [client 93.186.191.244:44452] [host www.inxpact.nl] Backend error on sending request(GET /administrator/index.php?option=com_admin&view=sysinfo HTTP/1.1); uri(/administrator/index.php?option=com_admin&view=sysinfo) content-length(0) (lsphp is killed?): SendRequest: write to backend socket failed: errno 9, referer: https://www.inxpact.nl/administrator/index.php?option=com_plugins
[Wed Mar 30 15:44:16.634708 2016] [lsapi:error] [pid 978448:tid 140354095249152] [client 93.186.191.244:44468] [host www.inxpact.nl] Error receiving response header (lsphp is killed?): ReceiveResponseHeader: receive pkg hdr failed: ReceivePkgHdr: nothing to read from backend socket, referer: https://www.inxpact.nl/administrator/index.php?option=com_plugins
[Wed Mar 30 15:44:16.634756 2016] [lsapi:warn] [pid 978448:tid 140354095249152] [client 93.186.191.244:44468] mod_lsapi: re-sending previously crashed request again (1), referer: https://www.inxpact.nl/administrator/index.php?option=com_plugins
[Wed Mar 30 15:44:16.634781 2016] [lsapi:error] [pid 978448:tid 140354095249152] [client 93.186.191.244:44468] [host www.inxpact.nl] Backend error on sending request(GET /administrator/index.php?option=com_admin&view=sysinfo HTTP/1.1); uri(/administrator/index.php?option=com_admin&view=sysinfo) content-length(0) (lsphp is killed?): SendRequest: write to backend socket failed: errno 9, referer: https://www.inxpact.nl/administrator/index.php?option=com_plugins
[Wed Mar 30 15:44:55.081145 2016] [lsapi:error] [pid 978558:tid 140354347030272] [client 93.186.191.244:44528] [host www.inxpact.nl] Error receiving response header (lsphp is killed?): ReceiveResponseHeader: receive pkg hdr failed: ReceivePkgHdr: nothing to read from backend socket, referer: https://www.inxpact.nl/administrator/index.php?option=com_plugins
[Wed Mar 30 15:44:55.081189 2016] [lsapi:warn] [pid 978558:tid 140354347030272] [client 93.186.191.244:44528] mod_lsapi: re-sending previously crashed request again (1), referer: https://www.inxpact.nl/administrator/index.php?option=com_plugins[Wed Mar 30 15:44:55.081214 2016] [lsapi:error] [pid 978558:tid 140354347030272] [client 93.186.191.244:44528] [host www.inxpact.nl] Backend error on sending request(GET /administrator/index.php?option=com_admin&view=sysinfo HTTP/1.1); uri(/administrator/index.php?option=com_admin&view=sysinfo) content-length(0) (lsphp is killed?): SendRequest: write to backend socket failed: errno 9, referer: https://www.inxpact.nl/administrator/index.php?option=com_plugins

**Comment by brianteeman** [comment]
It is possible that your web host disables the ability to view phpinfo

To verify this you can create a standalone phpinfo file and see if it works https://mediatemple.net/community/products/dv/204643880/how-can-i-create-a-phpinfo.php-page<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9672">issues.joomla.org/joomla-cms/9672</a>.</sub>

**Comment by jjnxpct** [comment]
A php file with phpinfo(); also triggers a similar server error. My provider and helpdesk from Cloud Linux are investigating this issue as wel... <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9672">issues.joomla.org/joomla-cms/9672</a>.</sub>

**Comment by brianteeman** [comment]
That proves that it is not a joomla issue at all - so I am closing this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9672">issues.joomla.org/joomla-cms/9672</a>.</sub>
