### ISSUE TITLE
Library Uninstall Does Not Process Uninstall from Manifest

### ISSUE THREAD

**Issue by gsexton** [joomla/joomla-cms#9675]
#### Steps to reproduce the issue

Create a library that contains an uinstall block with a SQL file.
Install the library and then uninstall it.
#### Expected result

The SQL file defined in the uninstall block should be executed.
#### Actual result

The SQL Script is not executed.
#### System information (as much as possible)

Joomla 3.5

Viewing libraries/cms/installer/adapter/component.php, JInstallerAdapterComponent.uninstall() contains the block:
try
{
  $this->triggerManifestScript('uninstall');
} catch (RuntimeException $e){
// Ignore errors for now
}
A corresponding block is not present in library.php JInstallerAdapterLibrary.uninstall()

if this is deemed a NOTFIX or WONTFIX, then this page:

https://docs.joomla.org/Manifest_files

should be modified to explicitly reflect that uninstall scripts are not supported for library extensions.

**Comment by mbabker** [comment]
Will track this in https://github.com/joomla/joomla-cms/issues/6015 (technically it's two different issues but the long and short of it is it all boils down to things not running standardized paths at the moment).
