### ISSUE TITLE
3.5.x Test mail is not testing the correct mail configuration

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#9680]
#### Steps to reproduce the issue

In the global config, in test mail button i'm getting test mail ok even if the SMTP mail server or port domain is clearly wrong (doesn't exist).

#### Expected result

Use SMTP. and give an error when the server does not send the mail.

#### Actual result

Always `The email was sent successfully to user@example.com using SMTP. You should check that you've received the test email.`
MEssage ok, because it's using sendmail, not SMTP.

#### System information (as much as possible)

3.5.x

#### Additional comments

Only happens in the test mail in the global config, all other mail functions seem to work fine.

**Comment by brianteeman** [comment]
Confirmed - I get the same no matter what I try

**Comment by brianteeman** [comment]
Enabling the debugging @mbabker introduced  with #9678 shows nothing in the logs<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9680">issues.joomla.org/joomla-cms/9680</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i think is not generating an error because in my case is always using sendmail to send the mail, no matter if i choose to use SMTP.

**Comment by brianteeman** [comment]
I think the same

On 31 March 2016 at 11:35, andrepereiradasilva <notifications@github.com>
wrote:

> i think is not generating an error because in my case is always using
> sendmail to send the mail, no matter if i choose to use SMTP.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9680#issuecomment-203851231>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
so the mail server type var "Mailer" is not being used by phpmailer somehow.

**Comment by andrepereiradasilva** [comment]
It seems this go back to 3.5.0, not only 3.5.1 RC2, can you confirm also?

**Comment by brianteeman** [comment]
yes

**Comment by andrepereiradasilva** [comment]
@Kubik-Rubik can you check?

**Comment by Kubik-Rubik** [comment]
@andrepereiradasilva Yes, will do tomorrow / this weekend. Thanks!

**Comment by brianteeman** [comment]
@Kubik-Rubik any update. 

I hope this isnt going to be another PR you say you will look at every month :-p<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9680">issues.joomla.org/joomla-cms/9680</a>.</sub>

**Comment by brianteeman** [comment]
@kubik-rubik any update<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9680">issues.joomla.org/joomla-cms/9680</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i think this is solved by the changes made recently to JMail.

@brianteeman can you confirm?

**Comment by andrepereiradasilva** [comment]
ups no reallly something it gives errors sometimes it don't ...

**Comment by andrepereiradasilva** [comment]
please test https://github.com/joomla/joomla-cms/pull/10370

**Comment by andrepereiradasilva** [comment]
please test #10370

**Comment by Kubik-Rubik** [comment]
@andrepereiradasilva Thanks Andre for taking over here! I will test your PR. :+1:
