### ISSUE TITLE
PDOMysql driver limitations

### ISSUE THREAD

**Issue by fpaixao** [joomla/joomla-cms#9682]
#### Steps to reproduce the issue

install a new joomla extension with an error. A wrong foreing key, as an exemplo.
#### Expected result

Jommla  will notify: Mysql error #... table....
#### Actual result

Jommla  will notify: Mysql error  BUT DOES NOT INFORM THE TABLE!!!

**Comment by brianteeman** [comment]
Is this just with the PDO driver or with mysqli as well?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9682">issues.joomla.org/joomla-cms/9682</a>.</sub>

**Comment by andrepereiradasilva** [comment]
the code for Joomla PDO database driver is here https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/driver/pdo.php and here for pdomysql specific https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/database/driver/pdomysql.php

Maybe you can make a Pull Request for solving the issue,

**Comment by fpaixao** [comment]
This happens only if  using PDOMysql driver. The imySQL driver works perfectly.

**Comment by mbabker** [comment]
I looked earlier.  Joomla manually appends the executed SQL query to the error message that the underlying database connector uses for all the non-PDO based drivers.  This doesn't happen with the PDO driver.  This is also why SQL errors always display the full query on error screens.

If JLog were more PSR-3 structured I'd say that the query should be part of the context array and not displayed on screen in a message (but logged to the error log appropriately), but we don't have that option unfortunately as you can only give it a string to process (what's to be gained by showing the full query in an error message to the general public anyway?).

**Comment by mbabker** [comment]
Closing this.  Having the SQL query as part of the Exception message has been removed in 3.7, if you need the query in your error handling catch `JDatabaseExceptionExecuting` and call its `getQuery` method.
