### ISSUE TITLE
Image upload directly to the article

### ISSUE THREAD

**Issue by ZviadPochkhua** [joomla/joomla-cms#9684]
#### Steps to reproduce the issue
To upload image, you need to choose file from computer and upload it. 

#### Expected result

Image must be inserted in article just after upload.  Automatically. 

#### Actual result
You need first upload image, then find it and insert to article. 
There is no reason why files to be uploaded into Articles  >( Images and Links) must be first uploaded, then found and then inserted. This is the useless step with no logical need. 

#### System information (as much as possible)
Joomla 3x

#### Additional comments
![screen shot 2016-03-24 at 5 36 11 pm](https://cloud.githubusercontent.com/assets/18051871/14172502/6e8e22b8-f749-11e5-9b13-09458dcc957b.png)

**Comment by brianteeman** [comment]
Since Joomla 3.5 you have the option to drag and drop an image directly into your article<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9684">issues.joomla.org/joomla-cms/9684</a>.</sub>

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9684">issues.joomla.org/joomla-cms/9684</a>.</sub>

**Comment by ZviadPochkhua** [comment]
Thank you for you reply.  But Drag and Drop does not work with intro images.  Sorry if I misunderstand something.  We are running daily Newspaper and easy upload of images are very important to us.

**Comment by infograf768** [comment]
@ZviadPochkhua 

In 3.5.0 (and 3.5.1 to be released) it is possible to Upload and Insert an intro image:

![screen shot 2016-04-01 at 08 55 01](https://cloud.githubusercontent.com/assets/869724/14199808/a58fcfe8-f7e7-11e5-9134-c923df459381.png)
![screen shot 2016-04-01 at 08 55 11](https://cloud.githubusercontent.com/assets/869724/14199810/aa1adbca-f7e7-11e5-8b6a-fb0d4ca56b72.png)

**Comment by ZviadPochkhua** [comment]
@infograf768 Thank you very much. Sorry for bothering with this issue.  I’m very sorry but can you please specify where this "Change Image" is located?  and is it possible to insert uploaded file instantly. without finding it in database?
I’m using this version:  Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT

As we are running daily newspaper (finchannel.com), its important to have easy image upload for articles. Like with one insert and upload. as I see the current version requires upload first, then browsing the file in already uploaded database (that is not timesaving) and insert it manually.

**Comment by infograf768** [comment]
I get it when clicking on Select when Editing articles in back-end:
![screen shot 2016-04-01 at 14 10 26](https://cloud.githubusercontent.com/assets/869724/14206490/bdd72c5a-f813-11e5-8158-6dec71eebdb7.png)

**Comment by ZviadPochkhua** [comment]
@infograf768  very strange. I have these features below the the table. Anyway, as i understand, this is the same feature which allows first upload, then find file in images and insert as intro or full article image. 

The problem reported is that there are 3 separate steps to insert image.  1) Upload 2) Find file 3) Insert.
While it can be only one - Upload image instantly to intro or full.  (as in K2)

I don't see reason behind separation of the upload process.  When you upload photo in Article it means file is dedicated to this article. 

Can you please suggest me any way to upload intro image directly to article?

**Comment by infograf768** [comment]
No way I know using core.

**Comment by ZviadPochkhua** [comment]
@infograf768 maybe any idea of linking uploaded image to the insert function?

**Comment by ZviadPochkhua** [comment]
another idea to simplify image upload: 
Just after upload image into IMAGES and LINKS, it gives you the address of the image in green bar (see screenshot). So why not to copy this address automatically directly to IMAGE URL field located below?  
This will link file and avoid the boring and time wasting process of searching image in database.

**Comment by carlosilari** [comment]
I know what you want, download JCE and let me know
