### ISSUE TITLE
Joomla 3.5 stuck forever creating Index in Smart Search Component

### ISSUE THREAD

**Issue by ErikDeMartiis** [joomla/joomla-cms#9686]
#### Steps to reproduce the issue
Go to Component Menu and select "Smart Search" 
Click on "Index" button
The Smart Search Indexer overlay window appear...and stay forever
Opening the web inspector of the browser (I'm using Safari on El Capitain Mac Os X)I can read the JS error

SyntaxError: JSON Parse error: Unrecognized token '<'
parsejquery.min.js:4:16003
parseJSONjquery.min.js:4:16003
parseJSONjquery-migrate.min.js:1:2948
handleFailureindexer.js:65
jjquery.min.js:1:27314
fireWithjquery.min.js:1:28123
xjquery.min.js:4:22146
bjquery.min.js:4:26031

---

The LOG file
2016-03-31T12:30:16+00:00	INFO 127.0.0.1	-	Starting the indexer
2016-03-31T12:30:17+00:00	INFO 127.0.0.1	-	Starting the indexer batch process

only 2 lines...no errors, also if I set LOG to Development or Maximum (obviously, some lines of text more, like the query, but no errors)

#### Expected result
Joomla write content index

#### Actual result
Stuck forever on "Indexer Running"

#### System information (as much as possible)
iMac 10.11.3
Safari 9.0.3
Apache 2.2
PHP 5.6 (the same on 5.4)
Base Joomla 3.5 install with standard Example (Brochure English)

**Comment by ggppdk** [comment]
**You imply** but you do not say if you **have not* installed any 3rd party extensions ??
- if you have installed other extensions, maybe it is better to post first here: http://forum.joomla.org/

> SyntaxError: JSON Parse error: Unrecognized token '<'

- providing the JS error is of little use,
**it looks like** ?, the server responce is broken by some PHP error / warning / notice

- the:  **Unrecognized token '<'**
is probably **< br/ >**  of some PHP warning or notice being printed that breaks the JSON format of the server responce

you need to go to your browser and look at the server responce TEXT, which should reveal the real issue

See below an example of **proper response** using firefox and firebug, your browser has similar "Network" Tab to examine the server responce
- find it , and provide it here

![responce_firebug](https://cloud.githubusercontent.com/assets/5092940/14176658/ce678d4e-f75a-11e5-8bf3-f497d8b7c92d.png)

**Comment by ErikDeMartiis** [comment]
It's a new installation. No 3rd part extension.

![schermata 2016-03-31 alle 15 54 09](https://cloud.githubusercontent.com/assets/10062040/14177961/eda571d2-f758-11e5-8a70-fbd23ea2cbbe.png)

Regards
Erik

**Comment by chrisdavenport** [comment]
From the error message, it looks like your PHP has been compiled without iconv support.  I think you will have to ask your hosting company to install it for you.

**Comment by mbabker** [comment]
#9688 may be an alternative approach without requiring iconv support (at least in this instance).

**Comment by infograf768** [comment]
can you check if iconv is installed ?

**Comment by ErikDeMartiis** [comment]
BOOM!
iconv not activate was the problem.
I've activated this php extension from my web admin panel and now the indexing process is working.
Thank's for the support.

**Comment by infograf768** [comment]
could you test #9688 after desactivating iconv?

**Comment by ErikDeMartiis** [comment]
Sure.
Tested now.

I've turned off iconv. I've tried to do and indexing, but it failed. (OK)
Then I've used code contained in #9688, and then indexing; it worked!

Regards.

**Comment by zero-24** [comment]
Great so can you close this issue that and record you test on the Pull Request?
