### ISSUE TITLE
Fatal error when editing menu item where session expired

### ISSUE THREAD

**Issue by roland-d** [joomla/joomla-cms#9687]
#### Steps to reproduce the issue
1. Edit a menu item
2. Do not touch the page until your session has expired (it may be useful to set the session to 1 minute)
3. Click on the Save & Close button
4. You now get the login page since session expired
5. Login
6. Login again as needed
7. You now get a Fatal error: Call to a member function getGroup() on a non-object in D:\wamp\www\joomla-cms\layouts\joomla\searchtools\default\bar.php on line 28

Alternatively you can use a direct URL after being logged in to the administrator section:
http://domain/administrator/index.php?option=com_menus&layout=edit&id=233

Replace domain with your own domain and id, with an existing ID.

#### Expected result
That I get the page to edit the menu item.

#### Actual result
A page with notices and a fatal error. Only way to continue is to manually modify the URL to go to the homepage a the backend and then a navigate to the menu item and edit it.

![image](https://cloud.githubusercontent.com/assets/359377/14175947/caa3abc2-f74e-11e5-8e7a-ca3e5e19d625.png)

#### System information (as much as possible)
Joomla! 3.5.1-rc Release Candidate [ Unicorn ] 28-March-2016 22:30 GMT
PHP 5.5.14 / PHP 7.0.4

#### Additional comments

Can anyone else confirm this?

**Comment by andrepereiradasilva** [comment]
isn't this something like this one? https://github.com/joomla/joomla-cms/pull/9371

**Comment by roland-d** [comment]
@andrepereiradasilva Sounds similar huh but in the other PR you don't even have to wait till the session is expired. Now this gave me another idea, using this URL directly also generates the fatal error:
http://localhost/joomla-cms/administrator/index.php?option=com_menus&layout=edit&id=233

So yeah I would say it is basically the same but only for menus.

**Comment by javigomez** [comment]
Tested, I was able to reproduce.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9687">issues.joomla.org/joomla-cms/9687</a>.</sub>

**Comment by infograf768** [comment]
I have a solution that would have to be done all over as I also tested it with Content Languages where the redirection after logging was not creating Errors but was to the installed languages Manager.

Change in ROOT/administrator/components/com_menus/views/item/tmpl/edit.php
`<form action="<?php echo JRoute::_('index.php?option=com_menus&layout=edit&id=' . (int) $this->item->id); ?>" method="post" name="adminForm" id="item-form" class="form-validate">`

to

`<form action="<?php echo JRoute::_('index.php?option=com_menus&view=item&layout=edit&id=' . (int) $this->item->id); ?>" method="post" name="adminForm" id="item-form" class="form-validate">`

i.e. add `&view=item`

For Content languages:
from
`<form action="<?php echo JRoute::_('index.php?option=com_languages&layout=edit&lang_id=' . (int) $this->item->lang_id); ?>" method="post" name="adminForm" id="language-form" class="form-validate form-horizontal">`
to
`<form action="<?php echo JRoute::_('index.php?option=com_languages&view=language&layout=edit&lang_id=' . (int) $this->item->lang_id); ?>" method="post" name="adminForm" id="language-form" class="form-validate form-horizontal">`

i.e. add `&view=language`

We can do this all over core when necessary, but what about 3rd party?

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/9696
@roland-d @andrepereiradasilva @javigomez

**Comment by brianteeman** [comment]
Closed
