### ISSUE TITLE
Enhancement: Module navigation menu title equal to parent menu item title

### ISSUE THREAD

**Issue by ggeorgg** [joomla/joomla-cms#9692]
Let's say, I have a menu set up as follows:

- Menu A (alias: menu_a)
- Menu B (alias: menu_b)
- - Sub Menu B1 (alias: submenu_b1)
- -- Sub Sub Menu B11 (alias: submenu_b11)
- -- Sub Sub Menu B12 (alias: submenu_b12)
- - Sub Menu B2 (alias: submenu_b2)
- -- Sub Sub Menu B21 (alias: submenu_b21)
- -- Sub Sub Menu B22 (alias: submenu_b22)
- - Sub Menu B3 (alias: submenu_b3)
- -- Sub Sub Menu B31 (alias: submenu_b31)
- -- Sub Sub Menu B32 (alias: submenu_b32)

Now I want to display a navigation menu module on my webpage with the name of Sub Menu B1/B2/B3 depending on in which Sub Sub Menu I am. 
So now I could create 3 navigation menu modules with the names Sub Menu B1, Sub Menu B2, Sub Menu B3. 
I know I can display the Sub Sub Menu B11/B12 or Sub Sub Menu B21/B22 with a single navigation menu module with the property base entry: current. But then the modules title, which is shown on my webpage, is the title I choose for the module. 
What I want to be displayed as title for the module on the webpage is the title of the parent menu item.

I don't really want to create a module for each Sub Menu B1/B2/B3 beacause I have 16 of these sub menus...

Would this be possible? Maybe I just overlooked something? Hope you can understand my explanation.

Best regards
Georg

**Comment by brianteeman** [comment]
Yes this is already possible with the default menu module. See https://docs.joomla.org/Creating_a_submenu<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9692">issues.joomla.org/joomla-cms/9692</a>.</sub>

**Comment by brianteeman** [comment]
Ah sorry I misunderstand you want the module title to be unique? Thats not going to be possible but you could use css to format the first item (sub menu b1) to look the same as a title<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9692">issues.joomla.org/joomla-cms/9692</a>.</sub>

**Comment by ggeorgg** [comment]
I want a module title to be displayed but I want it to be named like the parent menu item, not the module title I give when I create the module in backend. 
So currently I have two modules:
http://neu.turnerschaft-lichtenfels.de/images/github/Zwischenablage02.png and
http://neu.turnerschaft-lichtenfels.de/images/github/Zwischenablage03.png

I want to use the first variant, but I don't want "Abteilung" to be displayed as module name on the webpage. 
I want it to look like the second module:
http://neu.turnerschaft-lichtenfels.de/images/github/Zwischenablage01.png

I don't want to create 16 modules with 16 different names ("Allgemeinsport", "Basketball", "Cheerleader", ...)

Hope this makes it a bit clearer.

**Comment by ggeorgg** [comment]
I just changed the code which displays the modul. I think there are better ways to implement it but for now it works. What do you think about this?

**Comment by bembelimen** [comment]
See comment here: https://github.com/joomla/joomla-cms/pull/9705#issuecomment-204510606
