### ISSUE TITLE
joomla 3.5 User Registration page auto redirect to login page. Registration form not showing

### ISSUE THREAD

**Issue by akhtar1985** [joomla/joomla-cms#9694]
#### Steps to reproduce the issue
1: assign menu item : User Registration
but menu link auto redirect to user login page   

#### Expected result
Menu link go to User Registration not for user login page

**Comment by brianteeman** [comment]
Please make sure that you have registration enabled in the user options<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9694">issues.joomla.org/joomla-cms/9694</a>.</sub>

**Comment by akhtar1985** [comment]
thank you brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9694">issues.joomla.org/joomla-cms/9694</a>.</sub>

**Comment by akhtar1985** [comment]
ho to auto redirect "index.php?option=com_users&view=login" to  create login menu setting <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9694">issues.joomla.org/joomla-cms/9694</a>.</sub>

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org

On 1 April 2016 at 11:22, akhtar1985 <notifications@github.com> wrote:

> ho to auto redirect "index.php?option=com_users&view=login" to create
> login menu setting
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9694
> <https://issues.joomla.org/tracker/joomla-cms/9694>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9694#issuecomment-204325488>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
