### ISSUE TITLE
Image Field upload

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9695]
Currently the way to upload an image to use in a field has a useless extra step
1. Select Image to Upload
2. Select the now uploaded image
3. Insert the image

Step 2 really is useless and really time consuming if you have a large number of images to navigate through

We should assume that if you have uploaded an image that you want to use it so it should be pre-selected in the image upload field once uploaded

**Comment by dgt41** [comment]
@brianteeman if you upload one image then what you propose makes sense, but (I might be wrong here as I don't remember the current behaviour) what will happen if you choose to upload multiple files?

**Comment by brianteeman** [comment]
1. I am only suggesting that the image is preselected and not inserted
2. Selecting multiple images reveals another bug that you only get a success message for the first image<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9695">issues.joomla.org/joomla-cms/9695</a>.</sub>

**Comment by infograf768** [comment]
When choosing an image to upload using select for example in article intro, there is no choice afaik to upload multiple images. You can indeed, but one after the other.

**Comment by brianteeman** [comment]
Sorry @infograf768 that is not correct

On 1 April 2016 at 14:58, infograf768 <notifications@github.com> wrote:

> When choosing an image to upload using select for example in article
> intro, there is no choice afaik to upload multiple images. You can indeed,
> but one after the other.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9695#issuecomment-204389434>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
@brianteeman
Indeed, you are right IF, when browsing, one chooses more than one file in the same repository.
In that case I can see for example " 2 files selected " , no file name.

Otherwise, one sees the name of a file chosen, can upload. If browsing again, it is replaced by another file name.
Also the success message displays only a success for the last alphaordered file upoaded when uploading multiple files at the same time.

I guess the UI needs improvements, including a search function.

**Comment by jppcel** [comment]
I am working to make a solution to use if send only a image in this moment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9695">issues.joomla.org/joomla-cms/9695</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for submitting this issue/pull request. The media manager is currently being completely rewritten and I have notified the development team about this issue for their consideration. I am closing this here at this time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9695">issues.joomla.org/joomla-cms/9695</a>.</sub>

**Comment by ZviadPochkhua** [comment]
Do you expect to have an issue above included in next update?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9695">issues.joomla.org/joomla-cms/9695</a>.</sub>

**Comment by brianteeman** [comment]
I can hope<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9695">issues.joomla.org/joomla-cms/9695</a>.</sub>
