### ISSUE TITLE
staitc $declaredJs in tinymce onDisplay function prevents the use of two editor fields with different editor xtd buttons in one form

### ISSUE THREAD

**Issue by avjoomla** [joomla/joomla-cms#9697]
#### Steps to reproduce the issue
create a jform xml definition with two editor fields
for example open file administrator/components/com_content/models/article.xml
Add a new field nodes in the first fieldset above the field with name "articletext"
&lt; field name="test1" type="editor"
	label="Editor_No_Module_Pagebreak"
	filter="JComponentHelper::filterText" buttons="true" hide="module,pagebreak" />
Make sure that tinymce is default editor on the Joomla! installation.
Open file administrator\components\com_content\views\article\tmpl\edit.php and replace

<?php echo $this->form->getInput('articletext'); ?> at line 88 
with
<?php echo $this->form->getInput('test1'); ?>
<?php echo $this->form->getInput('articletext'); ?>
in order to display the new editor field in article edit form.

Open an article in the edit view in the administration

#### Expected result
Display two editor fields in the article edit view. The first one having the editor xtd buttons article, image and readmore, the second one having the editor xtd buttons article, image, readmore, module and pagebreak

#### Actual result
Both editor fields have the same editor xtd buttons (article, iamge and readmore).

#### System information (as much as possible)
Joomla! 3.5.0 on different servers i.e. local host with XAMPP, PHP 5.5.30

#### Additional comments
On Joomla! prior to 3.5.0 it was possible to have multiple editors in a edit view with different buttons. The static varialbe $declaredJs in the function onDisplay in the plugin/editors/tinymce/tinymce.php, which was introduced with code changes made for Joomla! 3.5.0, prevents the plugin from adding the proper editor xtd buttons as defined in the xml file individually for each editor instance.
I have devoloped custom editor xtd buttons for my Joomla! component Visforms. I have multiple editors fields in the administration edit view and I need to display the custom editor xtd button only in some of this editor fields. This feature is broken since Joomla! 3.5.0 and I can see now way to fix it inside the Visforms code.

Regards,
Aicha

**Comment by renekorss** [comment]
@dgt41 Maybe you could provide solution(s)?

**Comment by dgt41** [comment]
Please check and test: #9707

**Comment by ggppdk** [comment]
I confirm the issue
i had noticed a few days ago but did not have time to look it more

Issue effects not only tinyMCE but other editors too
- XTD buttons are same
- furthermore the buttons JS work up to the point that tries to add the code into the textarea

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #9707<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9697">issues.joomla.org/joomla-cms/9697</a>.</sub>
