### ISSUE TITLE
J3.5: SEF-URL in Article to Contact only contains ID, but not Alias of the contact

### ISSUE THREAD

**Issue by jwiesel** [joomla/joomla-cms#9698]
#### Steps to reproduce the issue
1. Create a menu item of type "Contacts » List Contacts in a Category". (e.g. Category: "Persons", URL: /menu-item/child-menu-contactlist)
2. Create a new contact with the category above (e.g. "John Doe" in "Persons")
3. Create a new article (e.g. "Contact Test")
4. In the editor add a link in the fulltext of the article to the contact. (e.g. the result in the Joomla database could look like: index.php?option=com_contact&amp;view=contact&amp;id=40&amp;catid=10&amp;Itemid=100)
5. Save the article and review it in the frontend. The Router creates a SEF link, but without the contact alias ("/menu-item/child-menu-contactlist/40")
6. Check the link to the contact in menu item created in step 1 ("/menu-item/child-menu-contactlist/40-john-doe)
#### Expected result

The link to the contact from the article should be identical to the one of the the contact list. --> (/menu-item/child-menu-contactlist/40-john-doe)
#### Actual result

The alias is missing in the SEF URL, if a contact is linked in an article. Problem: Search engines count the two different links to the same content as duplicate content.
#### System information (as much as possible)

Joomla 3.5.0
PHP 7.0.4
Apache 2
MySQL 5.5.47

**Comment by bembelimen** [comment]
This is normal behavior, the alias is not part of the SEO URL generation. That means, the alias will not be loaded via the router. Just add it by yourself: `index.php?[...]&id=40-john-doe`

> Problem: Search engines count the two different links to the same content as duplicate content.
Ehhh...no

**Comment by jwiesel** [comment]
Hi @bembelimen,
thanks for your quick answer.
However I am wondering, why the router generates different URLs for the same content in articles (`/menu-item/child-menu-contactlist/40`) and in the contact list view (`menu-item/child-menu-contactlist/40-john-doe`).
The problem of duplicate content is, that the canonical tag (`rel=canonical`) in the HTML also shows the two different values, if I visit the contact page from the different locations. By this we tell Google, that these two URLs contain different information. Google sees, that the content is identical and will rate this as duplicate content: https://support.google.com/webmasters/answer/66359?hl=en
I solved my problem for now, by manually manipulating the link id-parameter in the HTML view of the article from (`index.php?[...]id=40[...]`) to (`index.php?[...]id=40:john-doe[...]`)

**Comment by andrepereiradasilva** [comment]
in 3.5.1 joomla core will not generate a canonical URI, except when you add a different canonical domain in the sef system plugin domain field. See https://github.com/joomla/joomla-cms/pull/9565 for more info.

**Comment by jwiesel** [comment]
If anyone else has the same "issue". Here's a workaround:
If you use JCE, there are two different ways to link a contact.

1. Link Browser: Tree, where you can select contacts by Category. These links only contain the article-id without the alias. `index.php?[...]id=40[...]` leads to `/menu-item/child-menu-contactlist/40`
2. Link search: Search field, where you can look for the contact name. These links contain the article-id + the alias and the alias of the category. `index.php?[...]id=40:john-doe&catid=10:persons[...]` leads to `menu-item/child-menu-contactlist/40-john-doe`

I would for now use the search to get the contact alias into the link, but remove the category alias to keep the dependencies on duplicate information as low as possible.

**Comment by franz-wohlkoenig** [comment]
@jwiesel 
- I set a Link in Article-Fulltext `index.php?option=com_contact&view=contact&id=33:super-admin&catid=4&Itemid=107`
- Global Configuration: Search Engine Friendly URLs is `Yes`
- Frontend: Article-Link is `contacts/super-admin`

Article-Options: Tab `Integration: URL Routing "Modern", Remove IDs from URLs: "Yes"`
#### Test on:
Joomla! 3.7.0-staging
macOS Sierra, 10.12.3
Firefox 50.1.0
PHP 7.0.4
MySQLi 5.5.53-0

**Comment by Hackwar** [comment]
This will be fixed in #14322
