### ISSUE TITLE
Module Class Suffix for custom HTML concatenates with "custom"

### ISSUE THREAD

**Issue by newjie** [joomla/joomla-cms#9700]
#### Steps to reproduce the issue
Custom HTML Module -> Advanced -> Module Class Suffix, fill in class name like "myclass"

#### Expected result
the `<div>`'s class should be "custom myclass"

#### Actual result
the `<div>`'s class is "custommyclass"

#### System information (as much as possible)
Joomla 3.5

#### Additional comments
I think this bug has been there since 2.5

**Comment by brianteeman** [comment]
It is not a bug it is by design
please see the documentation at https://docs.joomla.org

On 1 April 2016 at 17:59, vincent <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Custom HTML Module -> Advanced -> Module Class Suffix, fill in class name
> like "myclass"
> Expected result
>
> the <div>'s class should be "custom myclass"
> Actual result
>
> the <div>'s class is "custommyclass"
> System information (as much as possible)
>
> Joomla 3.5
> Additional comments
>
> I think this bug has been there since 2.5
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9700>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by newjie** [comment]
I think this creates confusion for beginners. I can still remember how I lost my hair over this issue several years ago. Wrote some style in .css and fill in the the class name but it just didn't work.
