### ISSUE TITLE
Module Class Suffix for custom HTML being applied to two different places

### ISSUE THREAD

**Issue by newjie** [joomla/joomla-cms#9702]
#### Steps to reproduce the issue

Custom HTML Module -> Advanced -> Module Class Suffix, fill in class name like "myclass"

#### Expected result

class name "myclass" should only appear at one place, either `<div class="custom myclass"></div>` or `<div class="moduletable  myclass">`

#### Actual result

```
<div class="moduletable  myclass">
  <div class="custom myclass"></div>
</div>

```

#### Additional comments

This behavior has been there for a long time since 2.5

**Comment by bembelimen** [comment]
You have this behavior in nearly every module not only in mod_custom.

**Comment by renekorss** [comment]
@bembelimen is right. This is well known (feature?). In my opinion, it dosen't change anything, rather helps styling sometimes. Consider the case if I have selector `.moduletable.myclass .myclass` in my CSS and now we remove one of them. It would break it. Finally, developer can always create custom chrome module. All in all, it dosen't hurt.

**Comment by Bakual** [comment]
Closing as expected behavior
