### ISSUE TITLE
Height of modal windows too small for ease of use

### ISSUE THREAD

**Issue by erikvandoorne** [joomla/joomla-cms#9708]
#### Steps to reproduce the issue
Administrator / ISIS template: select a menu item from one of the menu's in the Menu Manager (tick the checkbox in the left-most column) and click the 'Batch' Button. A modal window opens which has such a small height, that the user can barely scroll down and select a menu item to move or copy the selected menu item to at all.
Many other modal windows' heights are rather small (i,.e. them modal window with menu item types when creating a new menu item) , forcing the user to always have to scroll to some of the most used options (i.e. the Single Article menu item type. 

#### Expected result
The modal window should have a height which is high enough to show as much information as possible and allow for easy scrolling in the contents of the modal window, or to not have to scroll at all, or as less as possible.

#### Actual result
The height of the  modal window is, in many cases, too small (i.e. batch processing in menu items). The user has to scroll too much and/or will experience difficulties and unnecessary steps in selecting the right properties.

#### System information (as much as possible)
Joomla! 3.5.0
ISIS administrator template

**Comment by franz-wohlkoenig** [comment]
Isnt it fixed by https://github.com/joomla/joomla-cms/pull/9683?

**Comment by alikon** [comment]
yes me too think so , and even we are wrong there is a PR #9709 proposed by @erikvandoorne
so this on ca be closed anyway

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9708">issues.joomla.org/joomla-cms/9708</a>.</sub>
