### ISSUE TITLE
Can't upload images in frontend using new TinyMCE drag and drop feature

### ISSUE THREAD

**Issue by jimiero** [joomla/joomla-cms#9711]
#### Steps to reproduce the issue

Make sure you have TinyMCE enabled for your user, then go to joomla frontend, edit an article and try to drag and drop an image inside the article

#### Expected result

Normally it should upload the image and display it

#### Actual result

The images seams it's not uploaded, looking on the browser error console I see:

Uncaught SyntaxError: Unexpected token <o.onload @ plugin.min.js:1

#### System information (as much as possible)
Joomla 3.5
Php 5.5.33
Database Version	5.5.32-31.0-log

**Comment by brianteeman** [comment]
Which web browser are you using?
Which template? Do you also have the problem when you are using protostar?

**Comment by jimiero** [comment]
Using Chrome  49.0.2623.110 (64-bit)

Yes the problem happens on a website with protostar template also, but is strange that I have installed a fresh J3.5 and seams there's does not happens, so this may be a conflict with some other extension installed, do you think the error may be related somehow because of mootools ?

**Comment by jimiero** [comment]
@brianteeman sorry false alarm, seams I found the cause of the problem, once disabling "System - EasySocial" the problem gets solved

**Comment by brianteeman** [comment]
I was pretty sure it would be :)
