### ISSUE TITLE
recaptcha on contact form is incorrectly labelled "optional"

### ISSUE THREAD

**Issue by timrichardson** [joomla/joomla-cms#9715]
#### Steps to reproduce the issue
On Joomla! 3.5 enable recaptcha2
Create a contact form, layout "plain", make it a menu link. 

#### Expected result
The recaptcha field should be compulsory and marked with an asterisk

#### Actual result
The recaptcha field is compulsory and is marked with an asterisk, but it is also labelled "optional"

#### System information (as much as possible)
Joomla 3.5 on ubuntu[systeminfo-2016-04-02T18-46-01-04-00.txt](https://issues.joomla.org/uploads/1/298e2129e5c25aac33f227e1982a28eb.txt)

#### Additional comments
screenshot attached![screen shot 2016-04-02 at 17 44 23](https://issues.joomla.org/uploads/1/371bbda7db6e49f8badef48695582ff0.png)

**Comment by brianteeman** [comment]
Thank you for reporting this. This has already been resolved and the fix will be in Joomla 3.5.1 which is scheduled for release early next week
