### ISSUE TITLE
Update problem

### ISSUE THREAD

**Issue by antonivanov1** [joomla/joomla-cms#9718]
#### Steps to reproduce the issue
Hi! When i want to update Joomla or add JED button to administator panel, i see this erroes:

Update: Could not open update site #1 "Joomla Core", URL: http://update.joomla.org/core/list.xml

Update: :Extension: Не удалось открыть http://appscdn.joomla.org/webapps/jedapps/webinstaller.xml

In internet i'm read that this error because your server not responding for some countrys. I'm from Russia and my server in Russia. Can you help me? :) my site is http://autoprime1.ru and you can lookup ip of this domain. Thanks!

Ошибка подключения к серверу: No HTTP response received

**Comment by brianteeman** [comment]
You will need to speak to your web host to make sure they are not blocking access to those sites
