### ISSUE TITLE
com_installer security hack Joomla 3.0+

### ISSUE THREAD

**Issue by philbertphotos** [joomla/joomla-cms#9720]
[Removed due to security police]

**Comment by philbertphotos** [comment]
178.137.00.132 - - [04/Apr/2016:01:12:34 -0400] "POST /administrator/index.php?option=com_installer&view=install HTTP/1.1" 303 208 "http://example.vi/administrator/index.php" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"
178.137.00.132 - - [04/Apr/2016:01:12:36 -0400] "GET /administrator/index.php?option=com_installer&view=install HTTP/1.1" 200 42401 "http://example.vi/administrator/index.php" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"
178.137.00.132 - - [04/Apr/2016:01:12:37 -0400] "GET /tmp/system.php HTTP/1.1" 404 1315 "http://pr.vide.vi/administrator/index.php" "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.125 Safari/537.36"

**Comment by Kubik-Rubik** [comment]
@philbertphotos Thank you very much for the report. I've created a new ticket with all your details in the security repository, we will investigate this issue as soon as possible!

Please do not share sensitive information in the public repository, you can contact me directly (security(at)joomla.org). Thanks!
