### ISSUE TITLE
Joomla_3.5.1-rc2-Release_Candidate-Full_Package doesn't install on XAMPP PHP 7.0.4

### ISSUE THREAD

**Issue by fvdb06** [joomla/joomla-cms#9721]
Joomla 3.5.1 RC2 will not finish the install procedure on XAMPP v 3.2.2. with PHP 7.0.4.
The installation procedure hangs. The database is installed and also exists but there is no configuration.php in the Joomla root directory (No configuration file found and no installation code available. Exiting...)

**Comment by Kubik-Rubik** [comment]
Please open the console in your browser and check the error output. It sounds like a client side problem. If no errors are displayed, check the server error logs. Thanks!

**Comment by fvdb06** [comment]
Error displaying the error page: Table 'j!3bootstrap_tutorial.#__viewlevels' doesn't exist SQL=SELECT id, rules FROM `#__viewlevels`: Table 'j!3bootstrap_tutorial.#__viewlevels' doesn't exist SQL=SELECT id, rules FROM `#__viewlevels`

**Comment by Kubik-Rubik** [comment]
Could you please try it wihtout the exclamation mark (!) ? Thanks!

**Comment by mahagr** [comment]
Yes, special characters as well as mixing upper case characters to the prefix (JooMlaPreFix_) may cause issues like this.

**Comment by fvdb06** [comment]
** Never use special characters as well as mixing upper case characters to the prefix ** This is the solution, Many thanks!

**Comment by Kubik-Rubik** [comment]
@fvdb06 You are welcome. Have fun with Joomla!

**Comment by mahagr** [comment]
@Kubik-Rubik Though I see this as a bug; installer shouldn't allow you to enter anything else than something like `([a-z_][a-z0-9_]+_)` :)

**Comment by brianteeman** [comment]
Feel free to submit a pull request
