### ISSUE TITLE
Override creation

### ISSUE THREAD

**Issue by gioacchino54** [joomla/joomla-cms#9728]
#### Steps to reproduce the issue
Extension -> Templates ->  Templates ->My template
Create Overrides ->My override
#### Expected result
Editor -> html -> My override ->My content -> My files
#### Actual result
Editor -> html -> My override -> My content -> empty (only dir)
#### System information (as much as possible)
PHP Version	5.5.28
Web Server	Apache/2.4.16 (Win32) OpenSSL/1.0.1p PHP/5.5.28
WebServer to PHP Interface	apache2handler
Joomla! Version	Joomla! 3.5.0 Stable

**Comment by brianteeman** [comment]
Sorry I dont understand<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9728">issues.joomla.org/joomla-cms/9728</a>.</sub>

**Comment by gioacchino54** [comment]
Sorry for my English.
Wanting to create an override of a component for the template in use, only empty folders are created.

**Comment by brianteeman** [comment]
I am guessing that the component is non-standard then and does not have
views in the regular place. Which component is it?

On 5 April 2016 at 11:31, gioacchino54 <notifications@github.com> wrote:

> Sorry for my English.
> Wanting to create an override of a component for the template in use, only
> empty folders are created.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9728#issuecomment-205747287>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by gioacchino54** [comment]
Akeeba subscriptions 5.0.5, But with Joomla 3.4.8 created overrides, So I do not know.

**Comment by brianteeman** [comment]
You will need to check with akeeba subs - it looks like the views are not in the location that the override creator is looking at

**Comment by mbabker** [comment]
The override creation process basically only supports extensions structured like the core components and using the "legacy" MVC structure (3.5 added support for the singular named "view" folder used in places like com_config).  So FOF 3.0 based extensions and the patch tester are not compatible with this process.  Short of mandating every extension ever implements Joomla's MVC layer only, there's no action to be taken here.

**Comment by gioacchino54** [comment]
Ok.
TVM
