### ISSUE TITLE
Invalid Function Call in libraries/cms/application/administrator.php

### ISSUE THREAD

**Issue by gsexton** [joomla/joomla-cms#9733]
I was coding along, and I reversed the order of the args in my page to the property_exists() function. After I fixed my error, I searched for any other instances where I'd done that. The editor found this code in libraries/cms/application/administrator.php at line 421:

```
if (property_exists('JConfig', 'root_user')
	&& (JFactory::getUser()->get('username') == $rootUser || JFactory::getUser()->id === (string) $rootUser))
{
	$this->enqueueMessage(
	JText::sprintf(
	'JWARNING_REMOVE_ROOT_USER',
					'index.php?option=com_config&task=config.removeroot&' . JSession::getFormToken() . '=1'
				),
				'notice'
			);
		}
```

I didn't really dig into what it's supposed to be doing, but it's definitely not correct.

**Comment by mbabker** [comment]
How's it not correct?  [property_exists()](http://php.net/manual/en/function.property-exists.php) lets you check if a property is defined on a class name (string parameter) or an object, so that use is just fine.

**Comment by gsexton** [comment]
My mistake. I didn't see that it takes a class name. I assumed it was an instance.

**Comment by mbabker** [comment]
No problem.  There are more than enough quirks in PHP to make you second guess yourself, I do it every day :laughing:
