### ISSUE TITLE
[com_content] multiple databases config mapping invalid for JTable::getInstance

### ISSUE THREAD

**Issue by nsrsr** [joomla/joomla-cms#9742]
#### Steps to reproduce the issue
0. Connect to another database $db = JDatabaseDriver::getInstance($databaseOptions);
1. use this $db object to get a JTable instance $contentTable = JTable::getInstance('content', 'JTable', array('dbo' => $db));
2. JTable::getInstance will not use $db as specified, but default database

#### Expected result
Use specified database

#### Actual result
JTable Uses same database as in /configuration.php 

#### FIX
look for JTableContent (libraries/legacy/table/content.php) line
// Verify that the alias is unique

//$table = JTable::getInstance('Content', 'JTable', array('dbo',$this->getDbo())); //incorrect
$table = JTable::getInstance('Content', 'JTable', array('dbo'=>$this->getDbo())); //correct

Do a search for 'dbo',$this->getDbo() to find possibly more occurences of this bug which are JTableMenuType,JTableNested, JTableLanguage

#### System information (as much as possible)
Joomla 3.5

#### Additional comments
excerpt from JTable::getInstance:
$db = isset($config['dbo']) ? $config['dbo'] : JFactory::getDbo(); //assoziative array syntax 
bug is obvious, isn't it?

**Comment by nsrsr** [comment]
Can anyone comment this really is a bug or a misunderstanding by myself? I need to inform my customers if this will be fixed in any upcoming release. Thanks

**Comment by chrisdavenport** [comment]
Confirmed. Can you provide a pull request?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9742">issues.joomla.org/joomla-cms/9742</a>.</sub>

**Comment by nsrsr** [comment]
done, thank you, see https://github.com/joomla/joomla-cms/pull/10369<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9742">issues.joomla.org/joomla-cms/9742</a>.</sub>

**Comment by brianteeman** [comment]
Closed as we had a PR and that has been merged.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9742">issues.joomla.org/joomla-cms/9742</a>.</sub>
