### ISSUE TITLE
Login causes fatal error in [mod_related_items] with Menu Assignment: "On all pages except those selected"

### ISSUE THREAD

**Issue by errols** [joomla/joomla-cms#9743]
#### Overview
An invalid login (userid or password) causes a fatal error in Article-Related (_mod_related_items_) with Menu Assignment set to: "_On all pages except those selected_". If the Menu Assignment is changed to: "_Only on the selected pages_" an invalid login gives the expected login error page (component/users/?view=login). In both menu assignment scenarios the same pages are targeted.

#### Steps to reproduce the issue
1) login module on any page
2) Create Article-Related module (_mod_related_items_). Set **Menu Assignment** to: "_On all pages except those selected_"
3) Articles with or without matching Meta Keywords
4) Login in with invalid credentials gives fatal error
5) Change Article-Related module **Menu Assignment** to: "_Only on the selected pages_"
6) Login in with invalid credentials gives expected results

#### Expected result
login error page (component/users/?view=login)

#### Actual result
Fatal error: Call to a member function setState() on a non-object in /var/www/sbx01/modules/mod_related_items/helper.php on line 44

#### System information (as much as possible)
PHP Built On: 	Linux errol-lxm1 3.19.0-32-generic #37~14.04.1-Ubuntu SMP Thu Oct 22 09:41:40 UTC 2015 x86_64
Database Version: 	5.5.47-0ubuntu0.14.04.1
Database Collation: 	utf8_general_ci
Database Connection Collation: 	utf8mb4_general_ci
PHP Version: 	5.5.9-1ubuntu4.14
Web Server: 	Apache/2.4.7 (Ubuntu)
WebServer to PHP Interface: 	apache2handler
Joomla! Version: 	Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
Joomla! Platform Version: 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0 
The same results on local Linux Mint / Apache2 and production hosting site.

#### Additional comments
The Overview covers it.

**Comment by brianteeman** [comment]
Please can you upgrade to 3.5.1 (released just now) as there was a fix for the mod_related_items module (#9519) in that release that may have resolved your issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9743">issues.joomla.org/joomla-cms/9743</a>.</sub>

**Comment by errols** [comment]
Thank you. **Issue resolved after upgrading to 3.5.1.** It also caused Jevents not to work, by the way.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9743">issues.joomla.org/joomla-cms/9743</a>.</sub>

**Comment by Bakual** [comment]
Closing since fixed with 3.5.1

**Comment by errols** [comment]
Brian,

I upgraded and the issue is resolved. For the record and maybe future inquiries: this module caused the same error when using JEvents calendar.

Thanks for the quick resolve!

 

Errol
