### ISSUE TITLE
JHtml boostrap not hide on tpl tpl

### ISSUE THREAD

**Issue by alexonbalangue** [joomla/joomla-cms#9745]
#### Steps to reproduce the issue
JHtml::_('bootstrap.framework', false);

#### Expected result
not hide

#### Actual result
i use alternative

#### System information (as much as possible)
php7+
J3.5

#### Additional comments
i trying this method not work.

thanks you advances regards

**Comment by mbabker** [comment]
Not quite sure what you're trying to say (maybe post in native language and someone can translate?), but calling that method with a boolean false doesn't cause the Bootstrap JavaScript to be hidden.

**Comment by alexonbalangue** [comment]
it's that mind with JHtml::_('bootstrap.framework', false); i know have alternate to hidding boostrap for exemple "unset"
but  i just experimentale and understant now with JHtml::_() how does this function necessary or not.

have error ? JHtml::_('bootstrap.framework', false, there have more params)

**Comment by alexonbalangue** [comment]
i views here the docs https://docs.joomla.org/J3.x:Javascript_Frameworks

**Comment by alexonbalangue** [comment]
Hello, it's solved, i found how to hide Boostrap JS...

If you would likes hidding this f*** boostrap v2.3.2 default?  reading these links https://api.joomla.org/cms-3/classes/JHtmlBootstrap.html
