### ISSUE TITLE
Update package 3.5 or 3.5.1 no Joomla.xml file

### ISSUE THREAD

**Issue by visualtribe** [joomla/joomla-cms#9750]
#### Steps to reproduce the issue
I am trying to update Joomla from 3.4.8 to 3.5. One of my sites for some reason won't connect to the update package, so I downloaded version 3.5 (3.5.1 hadn't come out until today). When installing it comes back to me saying that the xml file is missing. I opened the zip package and there is no Joomla.xml file like there is in 3.4.7 and back as I have checked. I downloaded version 3.5.1 and it too does not have the Joomla.xml file in the update package. Can someone fix this please. 

#### Expected result
Update package installs. 

#### Actual result
Error now xml file. Can't install.

**Comment by ot2sen** [comment]
Sounds like you are trying to install using the joomla installer.
This is no longer possible, see the big bold text at the release page:
https://github.com/joomla/joomla-cms/releases/tag/3.5.1
