### ISSUE TITLE
Joomla 3.5.1 shows en-GB language pack as 3.5.0

### ISSUE THREAD

**Issue by andrepereiradasilva** [joomla/joomla-cms#9751]
#### Steps to reproduce the issue

Update to 3.5.1
Go to Extensions -> Languages -> Installed

#### Expected result

English language pack is version 3.5.1.

#### Actual result

English language pack is version 3.5.0.
![image](https://cloud.githubusercontent.com/assets/9630530/14312767/a7818a74-fbe5-11e5-8f9d-825913464cde.png)

#### System information (as much as possible)

Joomal 3.5.0

#### Additional comments

None.

@infograf768 any ideas why this happens?

**Comment by infograf768** [comment]
Simple: the en-GB.xml(s) have not been updated after 3.5.0 release.

We already should do that for 3.5.2

**Comment by andrepereiradasilva** [comment]
ok

**Comment by andrepereiradasilva** [comment]
Closed as we have a PR.
https://github.com/joomla/joomla-cms/pull/9752
