### ISSUE TITLE
Article saving in joomla 2.5.3 on Data center server and Disaster recovery server having Intrusion privention software

### ISSUE THREAD

**Issue by nidhinmp** [joomla/joomla-cms#9755]

**Comment by nidhinmp** [comment]
screen shots attached for the above problem![screen shot 2016-04-06 at 06 41 02](https://issues.joomla.org/uploads/1/9478f9d18fee88da379a8f0d56825840.png)![screen shot 2016-04-06 at 06 41 06](https://issues.joomla.org/uploads/1/f36e4ebab8a45f017885aab3d02366cf.png)![screen shot 2016-04-06 at 06 41 12](https://issues.joomla.org/uploads/1/ccd89d867b61c56b618f29d9cf4c06e2.png)![screen shot 2016-04-06 at 06 41 17](https://issues.joomla.org/uploads/1/fe4ceb0f1b49018268c4785da9c85193.png)![screen shot 2016-04-06 at 06 41 25](https://issues.joomla.org/uploads/1/b0d16a989ae02ffc68ff34d1626caa6f.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9755">issues.joomla.org/joomla-cms/9755</a>.</sub>

**Comment by brianteeman** [comment]
Joomla 2.5.3 is absolutely not supported any more. Joomla 2.5 was end of
life several years ago and 2.5.3 was even older than that

For support please use the forum http://forum.joomla.org

On 6 April 2016 at 12:41, nidhinmp <notifications@github.com> wrote:

> screen shots attached for the above problem[image: screen shot 2016-04-06
> at 06 41 02]
> <https://camo.githubusercontent.com/5f33c0ada496939a4f925711e37fb6833374aacc/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f39343738663964313866656538386461333739613866306435363832353834302e706e67>[image:
> screen shot 2016-04-06 at 06 41 06]
> <https://camo.githubusercontent.com/8e0e71b33e912ed48c1a65639d666ece0ed23d55/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f66333665346562616238613435663031373838356161623364303233363663662e706e67>[image:
> screen shot 2016-04-06 at 06 41 12]
> <https://camo.githubusercontent.com/b316d676f6d9602a33c949f07a0bb4539dc936a9/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f63636438396438363762363163353662363138663239643963663463303665322e706e67>[image:
> screen shot 2016-04-06 at 06 41 17][image: screen shot 2016-04-06 at 06
> 41 25]
> <https://camo.githubusercontent.com/620352416f3ee65ef8edfee6378e70b381c06b1a/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f62306431366139383961653032666663363866663334643136323663616136662e706e67>
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9755
> <https://issues.joomla.org/tracker/joomla-cms/9755>.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9755#issuecomment-206328535>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/
