### ISSUE TITLE
SmartFormer Gold, redirects to an error page after submitting form

### ISSUE THREAD

**Issue by apelsinskal** [joomla/joomla-cms#9762]
#### Steps to reproduce the issue
Fill in a form, click submit.
Form example: http://saluki.se/index.php/sv/aktivit/utstaellning/onlineanmaelan/landskrona-2016

#### Expected result
Redirect to an URL set in the form (start page on website)

#### Actual result
Shows an error page, but with the same URL as the form.
Error: 0 - Invalid address

#### System information (as much as possible)
Worked fine before upgrading from Joomla 3.5.0 to 3.5.1
Have teste SmartFormer Gold on 2 different websites, both upgraded to 3.5.1, both shows error page.

**Comment by roland-d** [comment]
@apelsinskal You will need to Contact SmartFormer and tell them to fix their code. They are sending an empty or invalid address to PHPMailer and do not catch the exception it throws.

Closing as it is not a core bug.

**Comment by apelsinskal** [comment]
OK thanks (new here) =)

**Comment by roland-d** [comment]
@apelsinskal No problem, thanks for reporting anyway.

**Comment by nacm-admin** [comment]
@apelsinskal What did Smart Former Gold say about the issue? I'm having the same problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9762">issues.joomla.org/joomla-cms/9762</a>.</sub>

**Comment by apelsinskal** [comment]
The "from name" field in the e-mail template must be an e-mail address. I have been using [name], to get the name of the sender in the e-mail sent to me. So now I have to use the [email] field in from name... 
Must be some conflict with the latest Joomla update because I had the same on all of my websites after updating Joomla.
I hope it can help you as well

**Comment by nacm-admin** [comment]
Yes! Your'e a LIFESAVER! Thanks! Works great until they hopefully send out an update!

**Comment by apelsinskal** [comment]
Happy I could help =)
