### ISSUE TITLE
attribute autocomplete off for some forms

### ISSUE THREAD

**Issue by thiagosoara** [joomla/joomla-cms#9767]
#### Steps to reproduce the issue

We can see that com_users doesn't include autocomplete="off" on the form.

#### Expected result

It should have the attribute autocomplete="off", because some sort of virus already get some user credencials from the web browser.

#### Actual result

There is no autocomplete attribute.

#### Additional comments

It's an important update and so simple to do. I already did it in my joomla version. A lot of virus that the users can get on their pendrives contain a lot of virus that can get those informations from the web browser app that stores it on users documents folders.

**Comment by brianteeman** [comment]
Personally I dont agree but thats just my personal opinion. If you submit a Pull Request with the changes then people can review it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9767">issues.joomla.org/joomla-cms/9767</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for your suggestion but it has been decided that this is not something that will be included in the core of Joomla.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9767">issues.joomla.org/joomla-cms/9767</a>.</sub>
