### ISSUE TITLE
Send Test Mail button - Ajax call has always smtpauth = 1

### ISSUE THREAD

**Issue by anibalsanchez** [joomla/joomla-cms#9768]
#### Steps to reproduce the issue

1. Fill all SMTP fields in Mail Settings for a server that requires authentication
2. But, **don't enable SMTP Authentication**

#### Expected result

Mails are **not** sent via SMTP that requires authentication. Because, SMTP Authentication is not enabled.

#### Actual result

Mails are sent via SMTP, even when SMTP Authentication is disabled.

#### System information (as much as possible)

Any browser

#### Additional comments

The radio buton is simply queried but jQuery does not take into account that it is a radio button.

Fix: sendtestmail-uncompressed.js

jQuery(document).ready(function ($)
{
	$('#sendtestmail').click(function ()
	{
		var email_data = {
			smtpauth  : $('input[name="jform[smtpauth]"]:checked').val(),
			smtpuser  : $('input[name="jform[smtpuser]"]').val(),
			smtppass  : $('input[name="jform[smtppass]"]').val(),
			smtphost  : $('input[name="jform[smtphost]"]').val(),
			smtpsecure: $('select[name="jform[smtpsecure]"]').val(),
			smtpport  : $('input[name="jform[smtpport]"]').val(),
			mailfrom  : $('input[name="jform[mailfrom]"]').val(),
			fromname  : $('input[name="jform[fromname]"]').val(),
			mailer    : $('select[name="jform[mailer]"]').val(),
			mailonline: $('input[name="jform[mailonline]"]:checked').val()
		};

**Comment by anibalsanchez** [comment]
Hi,

I tested the fix the uncompressed file. What are the steps to generate the compressed version?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9768">issues.joomla.org/joomla-cms/9768</a>.</sub>

**Comment by zero-24** [comment]
@anibalsanchez

Nothing special. Just one of the varius online js compressors is the last tool i know ;)

**Comment by anibalsanchez** [comment]
Updated from #9685. This issue is solved simply adding :checked to smtpauth value read.

**Comment by brianteeman** [comment]
Closed as we have a PR for testing - #9803<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9768">issues.joomla.org/joomla-cms/9768</a>.</sub>
