### ISSUE TITLE
Update breaks mail sending for RSform, Virtuemart, ticketmaster

### ISSUE THREAD

**Issue by ronaldotto** [joomla/joomla-cms#9769]
#### Steps to reproduce the issue
Install joomla 3.5.0
install latest version virtuemart or rsform version without the bugfix (they made a workarround)
Update to joomla 3.5.1
Send a form

#### Expected result
Form is send

#### Actual result
Rsform complains that the e-mailadres is invalid and shows the from name. It seems that the from name is used as sender e-mailadres

#### System information (as much as possible)
PHP Built On 	Linux webserver 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04) x86_64
Database Version 	5.5.44-0+deb8u1
Database Collation 	utf8_unicode_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.13-0+deb8u1
Web Server 	Apache/2.4.10 (Debian)
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 

#### Additional comments
Not nowing if Joomla is to blame or lazy component builders.
After the update from 3.5.0. a lot of components can't send mail anymore. Ticketmaster, virtuemart and RSform.
Since this is the only thing changed in 3.5.1 conerning e-mail..
It looks like the mails that are created use the from name as the from address.

Setting it to phpmailer, sendmail of SMTP does not solve it.
Sending a testmail from the joomla settings works. Those headers look fine.

**Comment by brianteeman** [comment]
This blog post explains the situation https://michaels.website/blog/joomla-351-mail-changes

I know that rsjoomla have made an updated release already
