### ISSUE TITLE
Unclear update issues when "allow_url_fopen = Off" in /etc/php5/fpm/php.ini

### ISSUE THREAD

**Issue by Robby-** [joomla/joomla-cms#9771]
#### Steps to reproduce the issue
Attempt to update a fresh Joomla 3.5.0 installation to 3.5.1 with `allow_url_fopen = Off` in `/etc/php5/fpm/php.ini`, through the Control Panel.

#### Expected result
Well, obviously this should (and does) fail because of `allow_url_fopen = Off` in `/etc/php5/fpm/php.ini` but I forgot about that at first, and Joomla didn't make it clear that that was the issue, it in fact made it even more confusing because it was logging a successful download of the zip update file.

#### Actual result
You get a popup window saying the file is corrupt/truncated, etc.
Additionally, in `logs/joomla_update.php` this was logged:
`File Joomla_3.5.x_to_3.5.1-Stable-Patch_Package.zip successfully downloaded.`
And in the `tmp` folder this zip file had a file size of 0 bytes.

#### System information (as much as possible)
Debian 8.3 64-bit, PHP 5.6.17-0+deb8u1

#### Additional comments
Setting `allow_url_fopen = On` of course fixed the issue and I could then update without a problem through the Control Panel.

**Comment by brianteeman** [comment]
This is a duplicate report of #7369<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9771">issues.joomla.org/joomla-cms/9771</a>.</sub>
