### ISSUE TITLE
Batch can't move or copy since 3.5.0

### ISSUE THREAD

**Issue by Wilma999** [joomla/joomla-cms#9772]
Since Joomla 3.5.0 it is not possible to use "Batch" anymore.

#### Steps to reproduce the issue
By "menu", "content-categories" and "content-articles", select one or more items and click the "BATCH" button.
The dropdown-list to choose a menu or category to copy/move to is empty.

#### Expected result
Until Joomla 3.4.8 there was a list of menu's or categories to choose from.
After selecting a menu or category you can select "move" or "copy" and process.

#### Actual result
No result, batch is not working anymore.

#### System information (as much as possible)
The dropdown list is gone since update to 3.5.0 and not fixed in 3.5.1.

#### Additional comments
By menu, category and articles batch is not working.
By modules it is working fine.
Batch is also in a lot of components (like redirects, weblinks), I don't know if it is working there.

**Comment by franz-wohlkoenig** [comment]
Seems like https://github.com/joomla/joomla-cms/pull/9683.

Scroll down the Dropdown-List, the Modal-Window is to small. Fixed in 3.5.2

**Comment by brianteeman** [comment]
Closed as a duplicate<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9772">issues.joomla.org/joomla-cms/9772</a>.</sub>

**Comment by Wilma999** [comment]
Not only the window is to small (have seen that topic). Since 3.5.0 there is no data at all in the dropdown-list to select, so is not working anymore. Think this is another problem: not a css for the size of the window, but a connect to database-problem.

But maybe this is also fixed in 3.5.2

**Comment by brianteeman** [comment]
I cannot confirm that

On 7 April 2016 at 20:31, Wilma999 <notifications@github.com> wrote:

> Not only the window is to small (have seen that topic). Since 3.5.0 there
> is no data at all in the dropdown-list to select, so is not working
> anymore. Think this is another problem: not a css for the size of the
> window, but a connect to database-problem.
>
> But maybe this is also fixed in 3.5.2
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9772#issuecomment-207058851>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by franz-wohlkoenig** [comment]
@Wilma999 I thought you don't see the dropdown-list, cause of small Window.

**Comment by Wilma999** [comment]
I'm sorry! At first there is no scrollbar to the right, but after resizing the box the scrollbar shows and then after scrolling the data shows.

Sorry for not thinking about making the box bigger sooner!

**Comment by franz-wohlkoenig** [comment]
Better asking than grumbling.

**Comment by JoomliC** [comment]
@Wilma999 @franz-wohlkoenig a PR is ready to be tested to fix batch dropdown as well as scrolling on iOS and small devices : https://github.com/joomla/joomla-cms/pull/9817 ;-)
