### ISSUE TITLE
Pagination not working on menu item "Tagged Items"

### ISSUE THREAD

**Issue by ketihar** [joomla/joomla-cms#9775]
#### Steps to reproduce the issue
Create a number of articles (more then 5) and give them the same tag.
Create a menu item 'Tagged Items', and change options "Display Select > hide" ,  "Pagination > show" , "Maximum items > 3"
Click on the menu item in the frontend

#### Expected result
Only 3 tags are shown and there is pagination above 3 tags.

#### Actual result
All tags are shown. There is no pagination.

#### System information (as much as possible)
PHP Built On 	Windows NT   (Windows 8 Business Edition) 
Database Version 	5.6.24
Database Collation 	latin1_general_ci
Database Connection Collation 	utf8mb4_general_ci
PHP Version 	5.6.8
Web Server 	Apache/2.4.12 (Win32) OpenSSL/1.0.1l PHP/5.6.8
WebServer to PHP Interface 	apache2handler
Joomla! Version 	Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0 

#### Additional comments
This problem with pagination is happening only with menu item "Tagged items". When i choose menu item "List of all tags" or "Compact list of tags" the pagination is working.

**Comment by haralake** [comment]
I can confirm that issue. There is no pagination on menu item Tagged Items and all settings inside menu item for Maximum Items are ignored. Also global settings for Maximum Items are ignored. Every time you call a tagged item you get all tags assigned and that is unacceptable if you have a lot of tags.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9775">issues.joomla.org/joomla-cms/9775</a>.</sub>

**Comment by brianteeman** [comment]
It is not a 1 to 1 copy of the chosen.css as I can see it has been edited in the past - not sure that was a good idea though<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9775">issues.joomla.org/joomla-cms/9775</a>.</sub>

**Comment by brianteeman** [comment]
oops commented on wrong issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9775">issues.joomla.org/joomla-cms/9775</a>.</sub>

**Comment by brianteeman** [comment]
1. I can not confirm in the current staging that you get no pagination. I have tagged 20 items as red and set the default list limit in global configuration to 5 and created a tagged item menu item with pagination set to show and I have paginations as expected. See screenshot
![screen shot 2016-08-05 at 09 01 40](https://issues.joomla.org/uploads/1/88e635747022eda268d1894bf8d9ab5f.png)

2. Maximum items does not appear to work as expected and I am looking into that<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9775">issues.joomla.org/joomla-cms/9775</a>.</sub>

**Comment by brianteeman** [comment]
The second problem related to Maximum Items is that there is no code to support that parameter. In the only other place that param is used it will select the list limit and not the maximum number of items in total which is what the text implies. Basically that option should not be there and its simply a copy paste error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9775">issues.joomla.org/joomla-cms/9775</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this as pagination is working fine and I have removed the option that should never have been there  with #11477<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9775">issues.joomla.org/joomla-cms/9775</a>.</sub>
