### ISSUE TITLE
Add more options to the sort table count

### ISSUE THREAD

**Issue by jayblaq** [joomla/joomla-cms#9776]
#### Steps to reproduce the issue
The issue is time out's happening when selecting all on a site with alot of users or content etc.  

#### Expected result

There should be some more options than 100 like 500 and 1000.   It would be a nice feature to be able to type in the field as well to set a certain number.

#### Actual result
Time out's when selecting too many 

#### System information (as much as possible)
All of Joomla versions 

#### Additional comments

This is not a mojor BUG just a good suggestion IMO.

**Comment by Bakual** [comment]
The list limit stop at 100 because higher numbers are likely to time out and the list is to big then anyway :)
Adding more options would be simple, just add a new line here: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/model/form/application.xml#L886-L901

**Comment by brianteeman** [comment]
Closed as we have a PR #9800 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9776">issues.joomla.org/joomla-cms/9776</a>.</sub>
