### ISSUE TITLE
TOS in user registration profile is not validated

### ISSUE THREAD

**Issue by mannybiker** [joomla/joomla-cms#9777]
#### Steps to reproduce the issue
Activate the user profile plugin
Choose TOS field as mandatory
Try to register leaving or selecting "no" as choice in the TOS radio button

#### Expected result
The form should be rejected and user should not be created

#### Actual result
The form is accepted and the user is created

#### System information (as much as possible)
Joomla 3.5.0

#### Additional comments
Client side validation seems not expected but also the server side validation is not triggered due to a misspelled com_users component

Here the commit with the simple fix
[TOS fix commit](https://github.com/mannybiker/joomla-cms/commit/8699552daa1e144c655f2a21bad2d2f73e6fb387)

**Comment by brianteeman** [comment]
Please can you submit that as a Pull Request so that it can be tested

On 7 April 2016 at 03:34, mannybiker <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Activate the user profile plugin
> Choose TOS field as mandatory
> Try to register leaving or selecting "no" as choice in the TOS radio button
> Expected result
>
> The form should be rejected and user should not be created
> Actual result
>
> The form is accepted and the user is created
> System information (as much as possible)
>
> Joomla 3.5.0
> Additional comments
>
> Client side validation seems not expected but also the server side
> validation is not triggered due to a misspelled com_users component
>
> Here the commit with the simple fix
>
> https://github.com/mannybiker/joomla-cms/commit/8699552daa1e144c655f2a21bad2d2f73e6fb387l
> <http://url>
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9777>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mannybiker** [comment]
@brianteeman Sure Brian, it is done
[#9792](https://github.com/joomla/joomla-cms/pull/9792)

**Comment by brianteeman** [comment]
Closed as we have a PR for testing
