### ISSUE TITLE
Save a copy of a menu item loses hierarchy on Joomla 3.5.1

### ISSUE THREAD

**Issue by Elnino38** [joomla/joomla-cms#9782]
#### Steps to reproduce the issue

Open a menu item, delete the alias, rename the title and click "Save as Copy"

#### Expected result

You expect to have a duplicate of the previous menu with the same parameters including the same hierarchy (same menu item parent)

#### Actual result

The new menu item is duplicated but to the root level of the menu.

#### System information (as much as possible)

Joomla 3.5.1

**Comment by brianteeman** [comment]
I am not sure I would expect that myself - did it work before?

On 7 April 2016 at 09:50, Elnino38 <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Open a menu item, delete the alias, rename the title and click "Save as
> Copy"
> Expected result
>
> You expect to have a duplicate of the previous menu with the same
> parameters including the same hierarchy (same menu item parent)
> Actual result
>
> The new menu item is duplicated but to the root level of the menu.
> System information (as much as possible)
>
> Joomla 3.5.1
> Additional comments
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9782>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Elnino38** [comment]
I am not sure how it was working on the previous versions.

But what’s the point of duplicating the menu item if it doesn’t keep the same parameters?

If you click “Save as copy”, don’t you expect to have ALL parameters equal to the original, including the hierarchy?

 

  _____  

I welcome VSRE emails. Learn more at  <http://vsre.info/> http://vsre.info/

**Comment by brianteeman** [comment]
I would expect all the params to be the same but I personaly expect to have
to decide where to put the menu

On 7 April 2016 at 10:02, Elnino38 <notifications@github.com> wrote:

> I am not sure how it was working on the previous versions.
>
> But what’s the point of duplicating the menu item if it doesn’t keep the
> same parameters?
>
> If you click “Save as copy”, don’t you expect to have ALL parameters equal
> to the original, including the hierarchy?
>
>
>
> _____
>
> I welcome VSRE emails. Learn more at <http://vsre.info/> http://vsre.info/
>
>
>
> From: Brian Teeman [mailto:notifications@github.com]
> Sent: Thursday, April 07, 2016 2:53
> To: joomla/joomla-cms
> Cc: Elnino38
> Subject: Re: [joomla/joomla-cms] Save a copy of a menu item loses
> hierarchy on Joomla 3.5.1 (#9782)
>
>
>
> I am not sure I would expect that myself - did it work before?
>
> On 7 April 2016 at 09:50, Elnino38 <notifications@github.com> wrote:
>
> > Steps to reproduce the issue
> >
> > Open a menu item, delete the alias, rename the title and click "Save as
> > Copy"
> > Expected result
> >
> > You expect to have a duplicate of the previous menu with the same
> > parameters including the same hierarchy (same menu item parent)
> > Actual result
> >
> > The new menu item is duplicated but to the root level of the menu.
> > System information (as much as possible)
> >
> > Joomla 3.5.1
> > Additional comments
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/joomla/joomla-cms/issues/9782>
> >
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>
>
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub <
> https://github.com/joomla/joomla-cms/issues/9782#issuecomment-206766336> <
> https://github.com/notifications/beacon/AReejFj2qiA_q93rGLarmGrKeI5ZDk13ks5p1MYJgaJpZM4IB2ia.gif>
>
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9782#issuecomment-206769900>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Elnino38** [comment]
Well that’s a personal point of view ;). It is anyway not a critical problem for me. I was just thinking that it is important to let Joomla users know that NOT ALL parameters are duplicated when saving a menu item copy as I think most of people expect (when you copy something in the computer world, it is a perfect copy of the original except the name/title). Maybe a pop up on the parent menu selector should be displayed then when duplicating to make people think about changing it.

Anyway I let the Joomla team decide what`s best!

 

  _____  

I welcome VSRE emails. Learn more at  <http://vsre.info/> http://vsre.info/

**Comment by brianteeman** [comment]
Setting to needs review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9782">issues.joomla.org/joomla-cms/9782</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you for creating this but it would appear that this has been resolved since I can not reproduce it in the current staging state. If this is not correct then this can be re-opened.
