### ISSUE TITLE
Canonical url

### ISSUE THREAD

**Issue by Realnmn** [joomla/joomla-cms#9785]
#### Steps to reproduce the issue

Fill site domain in SEF plugin (without this canonical not write!)
Write to adress some text to request:
site-name/?sdfsfsdfs=
#### Expected result

```
<link href="http://site-name/" rel="canonical" />
```
#### Actual result

```
<link href="http://site-name/?sdfsfsdfs=" rel="canonical" />
```
#### System information (as much as possible)

Joomla 3.5.1, php 5.4
#### Additional comments

All work fine at joomla 3.4.8

**Comment by Realnmn** [comment]
###Expected result

    <link href="http://site-name/" rel="canonical" />

###Actual result

    <link href="http://site-name/?sdfsfsdfs=" rel="canonical" /><hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9785">issues.joomla.org/joomla-cms/9785</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Yes, that's a know problem with Joomla.

Basically, the canonical just repeats the URI you entered.

See https://github.com/joomla/joomla-cms/blob/staging/plugins/system/sef/sef.php#L74

Also you can check some discussion about this here: https://github.com/joomla/joomla-cms/pull/9565

**Comment by Realnmn** [comment]
It's not  right repeats URI. And it's work correct at joomla 3.4.8.

**Comment by andrepereiradasilva** [comment]
read the discussion reggarding the wrong canonicals generated before here https://github.com/joomla/joomla-cms/pull/9565

**Comment by Realnmn** [comment]
Live check
joomla 3.5.1:
m-sumka.ru and m-sumka.ru/?sfdsdfsdf=
joomla 3.4.8:
autotuning-aks.ru and autotuning-aks.ru/?sdfsdfsdf=

At joomla 3.4.8 on url autotuning-aks.ru/?sdfsdfsdf= we get right canonical:
    <link href="http://autotuning-aks.ru/" rel="canonical" />

**Comment by SharkyKZ** [comment]
Autotuning-aks.ru has VirtueMart for homepage which creates its own canonical URL. Try another page on the site.

E.g. no canonical is inserted here http://autotuning-aks.ru/o-kompanii.html?sdfsdfsdf=.
Wrong canonical is inserted here http://autotuning-aks.ru/index.php?option=com_content&view=article&id=5 and here http://autotuning-aks.ru/component/content/article/5
etc.

**Comment by Realnmn** [comment]
All of them use com_content one material on main page.

**Comment by ggppdk** [comment]
@Realnmn 

There is a problem with current cannonical implementation, under some conditions/configurations (i will open an issue for it or post here) the generated canonical URL is broken giving a 404 error, **but that is a different topic**
.
.
- Now about your case:

**what you suggest is wrong** !!
**think what you are you suggesting**  ...


**EXAMPLE 1**
you suggest that this URL
http://autotuning-aks.ru/component/content/article.html?id=5

should have this cannonical
http://autotuning-aks.ru/component/content/article.html
- which is a wrong / bad URL without an article ID and will give 404


**EXAMPLE 2**
http://domain/search/?seachword=test

should have this cannonical !!
http://domain/search/
- which of course again wrong

**Comment by Realnmn** [comment]
@ggppdk 
I wrote that one thing work not propely in new version 
joomla 3.5.1:
m-sumka.ru and m-sumka.ru/?sfdsdfsdf=
joomla 3.4.8:
autotuning-aks.ru and autotuning-aks.ru/?sdfsdfsdf=

I don't think that need cut URI. But need check why in older version work fine.

**Comment by SharkyKZ** [comment]
Do you have a canonical domain set in SEF plugin? Because if not, the (Joomla) canonical shouldn't appear in 3.5.1 at all.

**Comment by brianteeman** [comment]
Sorry I am closing this issue. The canonical option in Joomla is ONLY for the canonical domain and not the url
