### ISSUE TITLE
Joomla 3.5.0 to 3.5.1 update progress-bar not function problem

### ISSUE THREAD

**Issue by sonqor** [joomla/joomla-cms#9802]
#### Steps to reproduce the issue
While trying to update my Joomla I am brought to the "updating" page where the progress bar shows up and a message that says 'Updating your Joomla files. Please wait ...' but nothing happens. I looked in my server log files but found nothing unusual, however I do get an error in the browser console on the 'updating' page that says:
# Uncaught TypeError: window.pingExtract is not a function![screen shot 2016-04-08 at 02 23 49](https://issues.joomla.org/uploads/1/4ba949aebbc0c0c44ebf289ca4068daf.jpg)

**Comment by alexonbalangue** [comment]
myself server updating on local/vps 's passed, purge your cache & cookie also in your browser, maybe before update as possible u can, trying firefox browser, so it's rule,

**Comment by sonqor** [comment]
Hi 
I tried use Firefox and also use my Android phone browser but the result is same.
May I update joomla manually? ?? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by alexonbalangue** [comment]
upload all files by ftp on u server (= same version actual joomla )

purg cache everywhere & then tried updated maybe works, so!! create backup not loose data and beginning new.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by sonqor** [comment]
Thanks. But is this problem global.?? Or it only occurred for me? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by brianteeman** [comment]
Based on the lack of anyone else reporting this it does look like its something in your own installation<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by brianteeman** [comment]
And the only references i can find on google are your own posts :(  Closing as it is an issue on your installation and not a core bug <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by eightdog** [comment]
For the record, I have arrived here as I have the same issue going from 3.5.0 to 3.5.1.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by brianteeman** [comment]
The same issue being the progress bar not moving or the same issue being the message Uncaught TypeError: window.pingExtract is not a function<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by eightdog** [comment]
The same issue with the progress bar not moving. I have not investigated
any further. I am wondering if it might be to do with my SEO or CSS
compression extension.

**Comment by brianteeman** [comment]
I would say its not the same issue then

On 11 April 2016 at 12:17, eightdog <notifications@github.com> wrote:

> The same issue with the progress bar not moving. I have not investigated
> any further. I am wondering if it might be to do with my SEO or CSS
> compression extension.
>
> On 11 April 2016 at 12:14, Brian Teeman <notifications@github.com> wrote:
>
> > The same issue being the progress bar not moving or the same issue being
> > the message Uncaught TypeError: window.pingExtract is not a function
> > ------------------------------
> > This comment was created with the J!Tracker Application
> > <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9802
> > <https://issues.joomla.org/tracker/joomla-cms/9802>.
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/joomla/joomla-cms/issues/9802#issuecomment-208291422
> >
>
> >
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9802#issuecomment-208291977>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sonqor** [comment]
That's mockery to close the topic. This is a BUG and you should responsible for this. Just say: **MOCKERY**.

**Comment by brianteeman** [comment]
Please check that media/com_joomlaupdate/update.js exists

**Comment by sonqor** [comment]
Yes it's exists

**Comment by supermirel** [comment]
Same issue here<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by eightdog** [comment]
Follow the manual install method instead. Works a treat.

**Comment by supermirel** [comment]
Uncaught TypeError: window.pingExtract is not a function; and also the status bar is not moving. Exactly the same issue as **sonqor** <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by brianteeman** [comment]
Re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by brianteeman** [comment]
@supermirel Which browser and operating system<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by supermirel** [comment]
Primary browser Chrome Version 50.0.2661.87 m (64-bit), but in any other browser happens that too<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by alexonbalangue** [comment]
trying updated your browser maybe work and doing all process Patch.
Or mozilla firefox 45.0.2 (latest version)...

**Comment by brianteeman** [comment]
And the operating system?

On 24 April 2016 at 12:55, supermirel <notifications@github.com> wrote:

> Primary browser Chrome Version 50.0.2661.87 m (64-bit), but in any other
> browser happens that too
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9802
> <https://issues.joomla.org/tracker/joomla-cms/9802>.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9802#issuecomment-213947494>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by supermirel** [comment]
Windows 10 x64 PRO<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by supermirel** [comment]
The browser is already up to date.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by alexonbalangue** [comment]
its bizarre! clear cache everywhere and unlock on control panel Joomla (your website)

you did https://docs.joomla.org/J3.x:Upgrading_from_Joomla_3.4.x_to_3.5?

Do this https://www.youtube.com/watch?v=VLt-WQCOCpw same version actual you use version your website and trying again update.

**Comment by supermirel** [comment]
After many failed attempts using Joomla built in Updater, I finally succeeded to upgrade using Method B form the link on the top. But that does not mean I found the problem that caused the issue or that I found a legit solution to it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by expntly** [comment]
Same issue here while trying to update from 3.5.0 to 3.5.1.  Tried both direct and FTP, no success.  Cleared all caches.  Exact same symptoms as @sonqor.

index.php shows a text/javascript fragment, that's where it fails, this function just does not exist on window.  Where does it come from?

> 	jQuery(document).ready(function(){
		window.pingExtract();
		});

**Comment by wilsonge** [comment]
I just tried doing a 3.5.0 to 3.5.1 update in a variety of browsers on my Windows 10 laptop and am unable to replicate this bug.

Looking around on the web it seems to stem from the javascript directory not being created when doing the 3.5.0 update for Joomla Update. Without any more information I can't really debug this any further give you a valid solution :(

**Comment by expntly** [comment]
Is there a way I can create that javascript directory manually?  What's the path?

**Comment by Markkojak** [comment]
I have exactly the same problem on one site. 

I'm not sure what to do to overcome the difficulty.

**Comment by expntly** [comment]
Any updates?  Would it help to upgrade directly to a "post 3.5.1" version?

**Comment by quentin-oyopi** [comment]
Hello,

You can check that you have this Joomla folder : /media/com_joomlaupdate/js
If you don't have a js folder, create one and move the all the js files from /media/com_joomlaupdate/*.js to /media/com_joomlaupdate/js/*.js
(you can add an empty index.html in this new folder for security reasons).

You must have these files here :
/media/com_joomlaupdate/js/default.js
/media/com_joomlaupdate/js/encryption.js
/media/com_joomlaupdate/js/json2.js
/media/com_joomlaupdate/js/update.js

For me, this problem occurred after an error trying to update to 3.5.1 (from 3.4.8) because of a corrupted Joomla_3.5.x_to_3.5.1-Stable-Patch_Package.zip update file.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9802">issues.joomla.org/joomla-cms/9802</a>.</sub>

**Comment by euoceo** [comment]
Interesting, I had the same problem too. The thread above, helped solve it. The directory com_joomlupdate was missing! Copied it from another Joomla website and all worked. Thx for the tip quentin-oyopi. There was an error at the end, didn't copy it down, something about "a manifest error". I suspect due to the com_ directory I used was from a 3.6 website. Cleared cache, site looks fine.

**Comment by andrepereiradasilva** [comment]
this seems to be related to broken installiins with missing files.

> You must have these files here :
> /media/com_joomlaupdate/js/default.js
> /media/com_joomlaupdate/js/encryption.js
> /media/com_joomlaupdate/js/json2.js
> /media/com_joomlaupdate/js/update.js

can this be closed?

**Comment by supergosho** [comment]
I fix this after change .htacces redirects (made by myself) 301, rewrite conditions etc. Suggest to take clear .htaccess file from new installation.
