### ISSUE TITLE
Show title is not observed in blog view for articles that are set access level registered

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#9805]
#### Steps to reproduce the issue

- Create a new category
- Create three new articles  and assign to the new category
- Article 1 with readmore Public
- Article 2 with readmore Registered
- Article 3 without readmore Registered
- Create a menu item Category blog for the new Category 
- Create a 'Article Category' module for the new Category 
- Set 'Show unauthorised' Yes

Test 1
- With the  'Article Category' module 

#### Expected result
Test 1
- The Category blog page should show a hyper-linked Title and intro text of both articles

Test 2
- The Category blog page should show a hyper-linked intro image and intro text of both articles

#### Actual result
Test 1
- The
 Title (of the article that has access set Registered)  displays but is not a hyper-link

Test 2
- The intro image (of the article that has access set Registered) displays but is not a hyper-link

#### Additional comments
http://forum.joomla.org/viewtopic.php?f=708&t=917941

**Comment by rgmears** [comment]
@Webdongle What you describe is not what's happening in my case.

The Title displays on the Blog page. And the Intro Images, which also display, are not linked on the Blog page. 

On the article page, Intro Text displays but not the Intro Image. The text is followed by a readmore button.

This page has a public menu item and a registered article.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9805">issues.joomla.org/joomla-cms/9805</a>.</sub>

**Comment by smz** [comment]
@Webdongle 
if the article is protected (_and the user displaying is "guest_"), then it is normal that the title in "Category Blog" is not linked: the rationale is that the user should click on the _Readmore_ link and been brought to the login page.

If the title was linked, the link will bring directly to the article and then you'll get an "Unauthorized".

The former... **in theory**, as I think I discovered with my recently opened issue  #9746 that this is not the case (_btw, I will appreciate if you could confirm my issue while you're playing with the "Show Unauthorized links" option..._).

In my experience, anyway, the title **is displayed**, although not hyperlinked.

**Comment by smz** [comment]
@rgmears 
`On the article page, Intro Text displays but not the Intro Image`

**I'm not sure**, but I think this too might be related to what I describe in  #9746 (see when I say that in "Single article" view protected articles are displayed "_raw_"...)

**Comment by rgmears** [comment]
@smz 
I commented on your other thread: [#9746](https://github.com/joomla/joomla-cms/issues/9746)

**Comment by Webdongle** [comment]
@smz 

>  then it is normal that the title in "Category Blog" is not linked: the rationale is that the user should click on the Readmore link and been brought to the login page.

acknowledged


> If the title was linked, the link will bring directly to the article and then you'll get an "Unauthorized".

A menu item to the article doesn't get an "Unauthorized"  when Show Unauthorised Links is set Yes... it displays the intro text.  There is no reason that a link from the Title in the blog page.  But yes if Show Unauthorised Links is No ... then it will get an "Unauthorized" .

That leaves 
The title isn't shown in the category blog but the intro image (when one is set).  For consistency either Title or intro image should show .or. neither should show.  Preferably the Title or intro image should show because then the admin has the choice.  Also when the intro image is displayed without a link it throws the text out of line


![blog](https://cloud.githubusercontent.com/assets/1115202/14400756/5e787dbc-fdf5-11e5-972b-505ad2371fa2.jpg)

**Comment by smz** [comment]
@Webdongle 

> A menu item to the article doesn't get an "Unauthorized" when Show Unauthorised Links is set Yes... it displays the intro text. 

Right, I stand corrected!

> That leaves
> The title isn't shown in the category blog but the intro image (when one is set). For consistency either Title or intro image should show .or. neither should show.

I may be thick, but in the above image I see both the titles and intro images for both articles...  :-/

Isn't that one is floated and the other not?

**Comment by Webdongle** [comment]
@smz 

> but in the above image I see both the titles and intro images for both articles

The top image is not a hyper-link and thus throws the introtext to the right.  You do not see the Titles you see the descriptive introtext.

**Comment by smz** [comment]
yes, I see, but are you sure that this is because of the hyperlink and not because (in their respective articles) one of the image is declared as a "float right" and the other not?

**Comment by smz** [comment]
sorry, float left...

**Comment by smz** [comment]
@webdongle:

> A menu item to the article doesn't get an "Unauthorized" when Show Unauthorised Links is set Yes... it displays the intro text.

~~Right, I stand corrected!~~ Actualy not, you can have an "Unauthorized" also with "Show unauthorised links". Try this set: "Show unauthorized links":
* off at the component level
* global at the article level
* Yes at the Blog menu item level

You'll see the intro text in the blog, but if you try to access the article directly (single article menu item or known URL), then you'll get an "Unauthorized"

**Comment by Webdongle** [comment]
Yes the hyper-linked image has different css formatting to the unlinked image.

**Comment by smz** [comment]
Ok, got it... different markup/css in the two "execution paths" for open/restricted articles, then...

**Comment by Webdongle** [comment]
@smz 

>  you can have an "Unauthorized" also with "Show unauthorised links". Try this set: "Show unauthorized links":

    off at the component level
    global at the article level
    Yes at the Blog menu item level

![blog 02](https://cloud.githubusercontent.com/assets/1115202/14401253/ad8c5fec-fe02-11e5-9952-ac8ff833f492.JPG)

Menu setting overrides Global.  Article setting only used with Featured Articles and honoured when 'Use article settings' is is selected.  Category blog used to have those in options as well but not anymore.

**Comment by smz** [comment]
OK, I'll re-check... maybe when I tested I had something wrong...

**Comment by brianteeman** [comment]
Can you check that #8827 doesnt already resolve this<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9805">issues.joomla.org/joomla-cms/9805</a>.</sub>

**Comment by Webdongle** [comment]
Thanks @brianteeman ... yes it is
