### ISSUE TITLE
Overflow is not enabled any more to the batch screens

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#9807]
#### Steps to reproduce the issue

- Login in to a staging / 3.5.1 site
- go to the menu mangaer
- select one category
- hit the batch button
- notice that the dropdown is not overflow the modal

#### Expected result

The Dropdown overflow the modal as this was in the past

#### Actual result

The dropdown is hidden and don't overflow the modal

#### Additional comments

Maybe this is realted to the bach modal changes in 3.5.0? Can you have a look here @dgt41 ?

#### Joomla-Bugs.de Ref

http://www.joomla-bugs.de/forum/index.php/topic,715.0.html

Original report in german by @widmann-it

**Comment by brianteeman** [comment]
This is the same as the existing report which is just waiting an update for
mobile screens

**Comment by zero-24** [comment]
@brianteeman what item do you mean? I don't talk about mobile screen it is on desktop for me see:

![batch_menu](https://cloud.githubusercontent.com/assets/2596554/14395008/836439de-fdcf-11e5-9aa4-d898d3f8c53a.JPG)

**Comment by brianteeman** [comment]
#9709 that PR fixes this but hasnt been merged yet as there is still an issue with the mobile screen<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9807">issues.joomla.org/joomla-cms/9807</a>.</sub>

**Comment by brianteeman** [comment]
or #9683 I forget which one is the best<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9807">issues.joomla.org/joomla-cms/9807</a>.</sub>

**Comment by zero-24** [comment]
Thanks so we can close here and i can get a look into that both PRs later. Thanks :)

**Comment by JoomliC** [comment]
@zero-24 could you test https://github.com/joomla/joomla-cms/pull/9817 it shoudl solve batch dropdown issue (as well as iOS and small devices scrolling ;-) )
