### ISSUE TITLE
AbstractRegistryFormat::getInstance() must be of the type array, string given

### ISSUE THREAD

**Issue by Giorgi625** [joomla/joomla-cms#9810]
#### Steps to reproduce the issue
Install Joomla 3.5.1

Install Easyblog 5.0.34 and Easydiscuss 3.2.9744
try to integrate Easyblog avatar into Easydiscuss from Easydiscuss admin panel on a page settings>>layout problem appears after setting easyblog as an avatar provider for easydiscuss and pressing save button.

#### Expected result

Just set Easyblog as an avatar provider for Easydiscuss.

#### Actual result

> Catchable fatal error: Argument 2 passed to Joomla\Registry\AbstractRegistryFormat::getInstance() must be of the type array, string given, called in /home/kinokore/public_html/georgianhikers.com/libraries/vendor/joomla/registry/src/Registry.php on line 649 and defined in /home/kinokore/public_html/georgianhikers.com/libraries/vendor/joomla/registry/src/AbstractRegistryFormat.php on line 39

#### System information (as much as possible)

Php version does not change anything. Site is hosted on Sitegrounds shared hosting. 
Joomla is intalled via Autoinstaller of Siteground version 3.5.0. then via joomla update from admin updated to 3.5.1 and after installed Easyblog and Easydiscuss. nothing more.

**Comment by brianteeman** [comment]
For issues with easyblog and easydiscuss you should contact stackideas for
support

On 9 April 2016 at 00:23, Giorgi625 <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Install Joomla 3.5.1
>
> Install Easyblog 5.0.34 and Easydiscuss 3.2.9744
> try to integrate Easyblog avatar into Easydiscuss from Easydiscuss admin
> panel on a page settings>>layout problem appears after setting easyblog as
> an avatar provider for easydiscuss and pressing save button.
> Expected result
>
> Just set Easyblog as an avatar provider for Easydiscuss.
> Actual result
>
> Catchable fatal error: Argument 2 passed to
> Joomla\Registry\AbstractRegistryFormat::getInstance() must be of the type
> array, string given, called in /home/kinokore/public_html/
> georgianhikers.com/libraries/vendor/joomla/registry/src/Registry.php on
> line 649 and defined in /home/kinokore/public_html/
> georgianhikers.com/libraries/vendor/joomla/registry/src/AbstractRegistryFormat.php
> on line 39
>
> System information (as much as possible)
>
> Php version does not change anything. Site is hosted on Sitegrounds shared
> hosting.
> Joomla is intalled via Autoinstaller of Siteground version 3.5.0. then via
> joomla update from admin updated to 3.5.1 and after installed Easyblog and
> Easydiscuss. nothing more.
> Additional comments
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9810>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Giorgi625** [comment]
But errors appear in Joomla core files and I had not this problem on same Extensions with same versions in old Joomla builds<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9810">issues.joomla.org/joomla-cms/9810</a>.</sub>

**Comment by brianteeman** [comment]
You should still ask Stackideas as it is using their code that is creating
the error

On 9 April 2016 at 00:40, Giorgi625 <notifications@github.com> wrote:

> But errors appear in Joomla core files and I had not this problem on same
> Extensions with same versions in old Joomla builds
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9810
> <https://issues.joomla.org/tracker/joomla-cms/9810>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9810#issuecomment-207648591>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
No one other than a stackideas customer has access to their code so I cant
even test it

On 9 April 2016 at 00:43, Brian Teeman <brian@teeman.net> wrote:

> You should still ask Stackideas as it is using their code that is creating
> the error
>
> On 9 April 2016 at 00:40, Giorgi625 <notifications@github.com> wrote:
>
>> But errors appear in Joomla core files and I had not this problem on same
>> Extensions with same versions in old Joomla builds
>> ------------------------------
>> This comment was created with the J!Tracker Application
>> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9810
>> <https://issues.joomla.org/tracker/joomla-cms/9810>.
>>
>> —
>> You are receiving this because you commented.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/joomla/joomla-cms/issues/9810#issuecomment-207648591>
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Giorgi625** [comment]
Ok thanks Brian for prompt answer<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9810">issues.joomla.org/joomla-cms/9810</a>.</sub>
