### ISSUE TITLE
Custom TinyMCE width and height

### ISSUE THREAD

**Issue by thekrotek** [joomla/joomla-cms#9812]
It looks like TinyMCE editor HTML area width and height can not be set externally, only via plugin settings. And I'm having this issue like forever.

When I try to set width and height like this:

```php
JEditor::getInstance(JFactory::getConfig()->get('editor'))->display('myeditor', '', '100%', '500', '100', '25');
```

Only textarea element dimensions are affected, but not HTML area. HTML area always takes its dimensions from plugin settings.

I looked into plugin code and everything is passed correctly in onDisplay event. Yet no result in the browser. It seems like width and height can only be customized on init, but not on display.

**Comment by brianteeman** [comment]
If it is correct in your report that you are using 3.4.8 please update to 3.5.1 and confirm that you still have the issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9812">issues.joomla.org/joomla-cms/9812</a>.</sub>

**Comment by thekrotek** [comment]
Yes, exactly the same issue exists since the dawn of time and upto 3.5.1. Just tested on 3.5.1 and it's even worse:

**TinyMCE plugin settings**

Width: 500
Height: 350

**PHP script**

Width: 60%
Height: 550

**Actual dimensions**

Textarea: Width and Height: PHP script inherited
HTML area: Width: 100%, Height: plugin settings inherited

On 3.4.8 HTML area properly takes Width and Height from plugin settings.

**Comment by brianteeman** [comment]
Closing as a duplicate report<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9812">issues.joomla.org/joomla-cms/9812</a>.</sub>
