### ISSUE TITLE
Issues in "Single article" view when the "Show Unauthorized links" option is set

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#9813]
#### Steps to reproduce the issue
* Create an article containing an "intro text" and "full text" (_i.e: it must have a "readmore" break_)
* In the intro text put `{loadposition test}`
* Set "Access" for **Registered** users
* Create a custom HTML module with just `<h1>Hello!</h1>`
* assign it to custom position `test` for all pages
* Create two menu items:
* A "Category Blog" menu item for the category containing the above article
* A "Single Article" menu item, for the above article.

##### IMPORTANT :
* have the **Show Unauthorized links** option in effect (_set it at the global, component, level, to make things easier and check that it is not overriden by settings at the article and menu items level_)

Try accessing the two menu items (_the "Blog" and the "Single article"_) while **not** being logged in.

#### Expected result
The custom HTML module should be displayed, in both views

#### Actual result
The custom HTML module is displayed only in the "Category Blog" view, while in the "Single article" view you'll see the `{loadposition test}` tag, verbatim.

#### System information (as much as possible)
Joomla 3.5.0, Protostar

#### Additional comments

The confirmed (_unless expected_) issue is that in "Single article" view, when an article is **partially displayed** (_intro text only_) as a consequence of it being declared for "Registered" users, the user being "Guest" and the "Show unuathorized links" option being in effect, then the "_intro text_" is displayed "_raw_", with that meaning that certain content plugins (_e.g.: those based on the "onContentPrepare" event_) are not applied to the intro text.

This is a continuation of #9746 (_it was started for a different purpose and thus was littered with too many non relevant comments_)

**Comment by smz** [comment]
@rgmears and @Webdongle, the discussion continues here, if you're interested...

**Comment by Webdongle** [comment]
@smz 

Yep confirmed. loadposition doest show the position when viewed as 'view unauthorised'

**Comment by rgmears** [comment]
Confirmed. Shortcode displays instead of content.

The same for loadmodule.

However, using the [Modules Anywhere](https://www.nonumber.nl/extensions/modulesanywhere) plugin from NoNumber displays the content.

**Comment by smz** [comment]
Modules Anywhere acts **not only** on the `onContentPrepare` event, but also on `onAfterDispatch` and, most important, on `onAfterRender`.

That explains why it works here.

**Comment by brianteeman** [comment]
I cannot confirm in the current staging
> while in the "Single article" view you'll see the {loadposition test} tag, verbatim.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9813">issues.joomla.org/joomla-cms/9813</a>.</sub>

**Comment by brianteeman** [comment]
Closed due to lack of response and unable to replicate - it can always be reopened if updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9813">issues.joomla.org/joomla-cms/9813</a>.</sub>
