### ISSUE TITLE
Error updating to 3.5.1 after uninstalling some components using the Extension Manager

### ISSUE THREAD

**Issue by jlainezs** [joomla/joomla-cms#9818]
#### Steps to reproduce the issue

* Before update uninstall Contacts and Banners components from Extensions > Manage > Extensions.
* Execute the update to 3.5.1 (I was updating from 3.4.8 and those components where removed on 3.2 or before, see note below).

#### Expected result

* A message telling that everything is ok.
* Database tables charset changed to utf8mb4.
* Joomla updated to 3.5.1

#### Actual result

* An error message telling to fix database errors.
* Database tables still using utf8 charset.
* Joomla updated to 3.5.1
* After this error, using Extensions > Manage > Database and clicking fix shows the same error (see attached images).

#### System information (as much as possible)

* Linux vagrant-ubuntu-trusty-64 3.13.0-66-generic
* MySQL 5.5
* PHP 5.6.14
* Apache 2.4.16
* Initial Joomla version 3.4.8

#### Additional comments

The components (contacts and banners) where removed using the default administrator tools, and no hacks of any kind where done to remove them.
This is an old site that I'm updating on a vagrant box (luckly). I think it was built on a 2.5 then migrated to 3 and any updates I did on it went smoothly. I'm sorry to say that I don't remember exactly if contacts and banners where removed before 3.X upgrade or after.

![screen shot 2016-04-09 at 16 02 25](https://issues.joomla.org/uploads/1/f705d0c885706cdc714883ed29648d2f.png)
![screen shot 2016-04-09 at 16 02 28](https://issues.joomla.org/uploads/1/b3835d2a7f95d31be8d065d7505ce0a0.png)

**Comment by Bakual** [comment]
It's a known issue. Basically the only way to deal with that would be to make all core extensions protected except those which are truly decoupled (only weblinks so far)
There are also other issues with uninstalling core extensions like banners, like the files are coming back on an update.

I fear there isn't much that can be done here. I'd recommend to just disable the extensions instead of uninstalling them.

**Comment by jlainezs** [comment]
Oks... I'll try to restore the missing tables to, at least, execute the database fix.
Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9818">issues.joomla.org/joomla-cms/9818</a>.</sub>

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9818">issues.joomla.org/joomla-cms/9818</a>.</sub>
