### ISSUE TITLE
401 Unauthorized Error

### ISSUE THREAD

**Issue by andirons** [joomla/joomla-cms#9820]
While working on my site running Joomla 3.5.1, all of a sudden when I go to save or change something I get an error msg "Unauthorized - This server could not verify that you are authorized to access the document requested. Either you supplied the wrong credentials (e.g., bad password), or your browser doesn't understand how to supply the credentials required. Additionally, a 401 Unauthorized error was encountered while trying to use an Error Document to handle the request." I have the right credentials because I have logged into my Joomla admin acct, but cannot access the admin site.  I've tried logging in on Firefox, Explorer and Chrome and get the same error msg on each browser. I've tried emptying my cache, rebooted my computer, rebooted my modem and nothing seems to get rid of the error msg except to let some time pass (30+ minutes).  Then it seems to reset itself.

I run Joomla 3.3 on another site using the same server and I have no problems.

#### System information (as much as possible)
Joomla 3.5.1,  Prostar template

**Comment by brianteeman** [comment]
That error message comes from the web server and not from joomla.

**Comment by brianteeman** [comment]
Please use the forum for support http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9820">issues.joomla.org/joomla-cms/9820</a>.</sub>
