### ISSUE TITLE
Modal layouts

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9822]
The modal for pagebreak needs some extra space at the top below the title. See screenshots of the difference between the pagebreak and the articles modals

![screen shot 2016-04-10 at 06 01 54](https://issues.joomla.org/uploads/1/7e4a11d09fca0db0cdda4122a200f8ee.png)

![screen shot 2016-04-10 at 06 02 00](https://issues.joomla.org/uploads/1/0645f9f521a265ef2a12752bece21bda.png)

**Comment by andrepereiradasilva** [comment]
@brianteeman reggading the articles/modules/newsletters/banners/contacts modals please test latest staging. it was changed in the last days.

**Comment by JoomliC** [comment]
opened a PR to fix this issue, and add consistency for the editor's modals content https://github.com/joomla/joomla-cms/issues/10013 ;-)

**Comment by brianteeman** [comment]
See #10013<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9822">issues.joomla.org/joomla-cms/9822</a>.</sub>
