### ISSUE TITLE
GitHub issues?

### ISSUE THREAD

**Issue by smz** [joomla/joomla-cms#9829]
Maybe O/T, but I think maintainers should be aware:

Since yesterday trying to look at the "Contributors list" / "Commits" / "Code frequency" and "Punch card" of the joomla/joomla-jcms repo (https://github.com/joomla/joomla-cms/graphs/contributors) doesn't return anyting and there is a curious message stating:
~~~
We need at least one non-empty commit with an email to generate this graph.
~~~

**Comment by mbabker** [comment]
I'd say it's a GitHub issue and should be reported to them.  https://github.com/contact

**Comment by smz** [comment]
Thanks @mbabker 

Wouldn't it be better if one of the repo "owners" does that?

**Comment by mbabker** [comment]
Doesn't necessarily have to be a repo owner as it's not related to anything regarding management of the repo.  If there were some ACL issue or something like that, absolutely it should.  But that's a public page.

**Comment by smz** [comment]
OK, I'll get in touch with them, then and in case report here. OK?

**Comment by smz** [comment]
Done!

**Comment by smz** [comment]
From Rachel Berry (GitHub Staff):

> Hi Sergio,
> 
> That is really odd, sorry about that! I've asked the engineering team to take a look and I'll let you know once I know more information. Thanks for letting us know!
> 
> All the best,
> Rachel

**Comment by smz** [comment]
no news from GitHub, but problem solved as far as I can see...
