### ISSUE TITLE
Help Screens show

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9834]
A lot of the help screens accessed from the Joomla admin display the words < translate> and </ translate> repeatedly throughout the content

![screen shot 2016-04-10 at 10 59 43](https://issues.joomla.org/uploads/1/4799fe796b2e30e51574e03f0c2baaf5.png)

**Comment by mbabker** [comment]
Post to joomla-projects/com_help please.  These aren't coming from core.

**Comment by MATsxm** [comment]
we are worjing on it as those pages needs to be tagged/marked for translation manually

**Comment by MATsxm** [comment]
FYI - Still in progress

**Comment by MATsxm** [comment]
Ok, finally and at this point only for articles under **ALPHABETICAL ORDER**, the issue about the appearance of the `<translate>` tags should be fixed.
Thank you to tell me if I missed some.

FYI, this could still happen on other few HelpScreens and will be fixed during next months.
The content (text and screenshots), dead links (red links) will be done later.

`<translate>` tags for the main articles should be fixed now then this one can be closed.
Thanks

**Comment by chrisdavenport** [comment]
You know we can just filter them out in the code, right?

**Comment by mbabker** [comment]
Someone who speaks better regex than me can do that, just need it added to https://github.com/joomla-projects/help-proxy/blob/master/com_help/site/helpers/help.php and if a new method is added ensure the model calls it.

**Comment by MATsxm** [comment]
@chrisdavenport..... no I don't :wink: 
@mbabker yeah sure :wink:

**Comment by Hutchy68** [comment]
This is because it's still not pulling from the language code from a translated page. If j is en-GB then it should add /en at the end of the url. If /en page 404's then default to no Lang code on end.  The same would apply to any four letter language code used by Joomla. fr-FR would ask for /fr. 404 then ask for /en or no Lang code end. 

In any regard I suppose could regex out the tags and make no code (English) the default fallback.

**Comment by mbabker** [comment]
The lang code isn't getting plugged onto the URL when the request to the docs wiki is getting made (it is sent to the help proxy, just not from there to Mediawiki).  It actually has the error check in place to deal with a 404 for non-translated.  So, I just need to know what to plug onto the URL and where and wham, language context is taken into account.

**Comment by brianteeman** [comment]
Wham? https://www.youtube.com/watch?v=JX_zmcVE0Wc

On 20 April 2016 at 22:27, Michael Babker <notifications@github.com> wrote:

> The lang code isn't getting plugged onto the URL when the request to the
> docs wiki is getting made (it is sent to the help proxy, just not from
> there to Mediawiki). It actually has the error check in place to deal with
> a 404 for non-translated. So, I just need to know what to plug onto the URL
> and where and wham, language context is taken into account.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9834#issuecomment-212613162>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Hutchy68** [comment]
It's tacked onto the end of the page name. 

Help35:Pagename/en

**Comment by Hutchy68** [comment]
Although I did write a REGEX  about an hour ago to deal with the translate tags and   if it defaults back to the pure English version without the /en

**Comment by mbabker** [comment]
And how do you do that through the API?  https://docs.joomla.org/index.php?action=render&title=Help35:Components_Content_Categories_Edit is the URL format we're using on the proxy.

**Comment by mbabker** [comment]
Nevermind, the same /lang works there too.

**Comment by Hutchy68** [comment]
Bingo.  Technically that's not really the API remember we cheated

**Comment by mbabker** [comment]
OK, proxy's updated to process the language code now.

**Comment by Hutchy68** [comment]
I pushed a patch to REGEX out the translation stuff if you want to be extra
cautious. The issue I can see is a page translated to fr-FR for example,
but not another language. If say /es is empty it defaults back to the main
page, not the Pagename/en then they would see the tags again.

It is possible pages are translated, but not to all languages. eg, some
pages in help are translated in Russian, but not all of them.

On Wed, Apr 20, 2016 at 8:42 PM, Michael Babker <notifications@github.com>
wrote:

> OK, proxy's updated to process the language code now.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9834#issuecomment-212671909>
>



-- 
----
Tom Hutchison

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9834">issues.joomla.org/joomla-cms/9834</a>.</sub>
