### ISSUE TITLE
multi category for Joomla article

### ISSUE THREAD

**Issue by sanek4life** [joomla/joomla-cms#9838]
"Tags" not solve problem of Joomla articles, because many web-sites have different structure and different vision for show articles.

**###Problem###**

for Example:
i have on site many categories like:

Lady Gaga > Music Videos
Lady Gaga > Albums
Lady Gaga > Lyrics

and categories with other artists, like:

Beyonce > Music Videos
Beyonce > Albums
Beyonce > Lyrics

at one moment Gaga released new music video "Lady Gaga - Telephone ft. Beyoncé", i'm put this video in category "Lady Gaga > Music Videos", but how i can show this video also in category "Beyonce > Music Videos"??? How???

**###Solution###**

Joomla need add additional categories for Article (for com_content component)

we have one - "primary category", and we want different "additional categories" for Article.

link with "primary category" is our rel="canonical" link

i see how this work on Yoo Zoo component and this is really cool.

**###Why no tags?###**

I can put tags like "Music video" or "Album" for show all content from all artists on my site. i'm no want use other component for "site content", because Joomla - this is CMS (Content management system). i can install third-party different components/modules for "comments" or "user registration" or "forum" or "shopping cart", but CONTENT - this is what Joomla need provide for all who use this system of Content management.

Why is a content management system - it is the weakest part of Joomla CMS now? I think the developers have forgotten what originally created the Joomla why it is called CMS, and not as anything else.

Content Management - is on what should be focused first and foremost the development of Joomla, all other problems like comments or shopping cart - for 3rd party developers.

**Comment by alikon** [comment]
This is not an issue, better, this is a request for a new feature

**Comment by sanek4life** [comment]
@alikon it does not matter which section to GitHub. just need a native multi-category option in Joomla

**Comment by brianteeman** [comment]
Personally I disagree. I look at articles as pieces of paper and there is
not a way that I can put a piece of paper in multiple drawers in my desk at
the exact same time.

In what way does using tags not work for you

On 11 April 2016 at 11:18, Sanek <notifications@github.com> wrote:

> @alikon <https://github.com/alikon> it does not matter which section to
> GitHub. just need a native multi-category option in Joomla
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9838#issuecomment-208269710>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sanek4life** [comment]
@brianteeman that's not work for me.

i'm create site on Joomla 1.0 and after migrate to 1.5 and 2.5 and now on Joomla 3.5

I waited Multicategories add many years to the CMS. It was a tricked, when someone has added the tags because tags are not as important.

I built the structure of the site in 2007, and if I  start to use the tags, I will destroy all the links on the site, will destroy the SEO and the rest, as well as destroy the links from social networking, leading to my site.

if I use tags, all links on my website will change. change links for categories and links for all the articles of the site. it will be a real tragedy for site.

**Comment by brianteeman** [comment]
How were you tricked? I cant remember anyone ever saying multiple
categories would be introduced

On 11 April 2016 at 11:31, Sanek <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> that's not work for me.
>
> i'm create site on Joomla 1.0 and after migrate to 1.5 and 2.5 and now on
> Joomla 3.5
>
> I waited Multicategories add many years to the CMS. It was a tricked, when
> someone has added the tags because tags are not as important.
>
> I built the structure of the site in 2007, and if I start to use the tags,
> I will destroy all the links on the site, will destroy the SEO and the
> rest, as well as destroy the links from social networking, leading to my
> site.
>
> if I use tags, all links on my website will change. change links for
> categories and links for all the articles of the site. it will be a real
> tragedy for site.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9838#issuecomment-208275445>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sanek4life** [comment]
it was the most expected thing on:
http://ideas.joomla.org/forums/84261-joomla-idea-pool/suggestions/1231693-assign-multiple-categories-to-article

"multiple categories" - this is no "Tags"! it is a completely different structure for the site, especially if the site is already running for a long time. if I really needed tags, I would have chosen WordPress. 

Joomla was originally built on the basis of the categories - for the first time, it was just a category, after an category with infinite number of levels and the next step should become Multicategories.

**Comment by brianteeman** [comment]
Unfortunately that is just a list of ideas. If you look at the other top
things I dont think many of them have been done either.

At the end of the day if no one writes the code then it will never happen

On 11 April 2016 at 11:42, Sanek <notifications@github.com> wrote:

> it was the most expected thing on:
>
> http://ideas.joomla.org/forums/84261-joomla-idea-pool/suggestions/1231693-assign-multiple-categories-to-article
>
> "multiple categories" - this is no "Tags"! it is a completely different
> structure for the site, especially if the site is already running for a
> long time. if I really needed tags, I would have chosen WordPress.
>
> Joomla was originally built on the basis of the categories - for the first
> time, it was just a category, after an category with infinite number of
> levels and the next step should become Multicategories.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9838#issuecomment-208278519>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by cenobitz** [comment]
This should be done by TAGS. I personally use it with K2 component and if you got large content segmentation and multicategories I use one category and tag to create something like multicategory content. I agree with @brianteeman that one content should be in one category (canonical URL) and can be accessed by several segmentation using TAGS. Than one category is canonical for URL and You can use TAG structure for showing content using MENU. for example large portal with about 30 000 articles structure TOPIC (category) >COUNTRY (sub category) > article -- this is main structure. If you want to create menu or other links to access sets of article you should create TAGS... In K2 its working fine... I tried to use TAGS the same in Joomla com_content in earlier versions but got issues with SEO... give it a try... the biggest advantaged is to create good menu with logic structure..

**Comment by sanek4life** [comment]
@cenobitz you solve your problems with 3rd party component K2. i'm also can write here - use Yoo Zoo - this component of my dream with multi category, tags and fields.

BUT!

But here we re talk about com_content, about native Joomla categories. native Joomla need multi category.

**Comment by Bakual** [comment]
The way Joomla currently works, multi categories are essentially not possible. Categories are used for building the URL, determining ACL and filtering/grouping content.
What you want is indeed what tags are meant for. What you request isn't anything different from using the current tags imho. I don't see a difference.

**Comment by sanek4life** [comment]
@Bakual my site was created before tags and before multi level for category.

my site was created on Joomla 1.5 and i'm was have plan in 2007 for category structure on my site.

stop lie about URL's. 

for example, my site have categories like:
Lady Gaga > Music Videos (lady gaga - main category, music videos - sub-category)
Lady Gaga > Albums
Lagy Gaga > Singles

and also:
Beyonce > Music Videos
Beyonce > Albums
Beyonce > Singles

i'm use tags for general categories, like "Videos" or "Music"

**links on my site (for example):**
http://site.com/lady-gaga/music-video/telephone
http://site.com/beyonce/music-video/single-lady

**and for tags:**
http://site.com/videos
http://site.com/music

i wanna put 1 Article in 2 categories on my site.

other components have multi category for Joomla. why native component com_content no have this?

this 3rd party component use com_content and 
http://extensions.joomla.org/extensions/extension/structure-a-navigation/multi-categorization/cw-multicategories

why this component no part of Joomla cms?

**Comment by brianteeman** [comment]
> other components have multi category for Joomla. why native component
com_content no have this?

because it is a bad idea to have duplicate content and because there are
already extensions that will do it for you.

On 15 April 2016 at 13:08, Sanek <notifications@github.com> wrote:

> @Bakual <https://github.com/Bakual> my site was created before tags and
> before multi level for category.
>
> my site was created on Joomla 1.5 and i'm was have plan in 2007 for
> category structure on my site.
>
> stop lie about URL's.
>
> for example, my site have categories like:
> Lady Gaga > Music Videos (lady gaga - main category, music videos -
> sub-category)
> Lady Gaga > Albums
> Lagy Gaga > Singles
>
> and also:
> Beyonce > Music Videos
> Beyonce > Albums
> Beyonce > Singles
>
> i'm use tags for general categories, like "Videos" or "Music"
>
> *links on my site (for example):*
> http://site.com/lady-gaga/music-video/telephone
> http://site.com/beyonce/music-video/single-lady
>
> *and for tags:*
> http://site.com/videos
> http://site.com/music
>
> i wanna put 1 Article in 2 categories on my site.
>
> other components have multi category for Joomla. why native component
> com_content no have this?
>
> this 3rd party component use com_content and
>
> http://extensions.joomla.org/extensions/extension/structure-a-navigation/multi-categorization/cw-multicategories
>
> why this component no part of Joomla cms?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9838#issuecomment-210439724>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sanek4life** [comment]
you have no right to say that I made the wrong structure on the site. this is my site and that is my vision for how content should be structured on the site.

forget about the tag and think that you are now in 2007 - how would you do a website, whether you were in my place?

Enough already talking about the tags. in the CMS before there were no tags, but people have websites.

if the CMS can not solve the problem, it does not mean I'm wrong. This means that developers can not do so. and do not need to teach me how to make websites.

**People here do not understand anything in SEO.**

**Comment by sanek4life** [comment]
@brianteeman i'm no see any duplicate content.

everybody use link **rel= canonical** on websites and no have any problem with content!

just see how YooZoo use multi category and it works. 

if I needed tags, I would in 2007 have chosen WordPress. who could me say in 2007 that will make Joomla tags instead of categories and Multicategories?

Why people here - http://ideas.joomla.org/forums/84261-joomla-idea-pool/suggestions/1231693-assign-multiple-categories-to-article say word "multi category"? this people no say TAGS, because everybody know difference between tags and categories!!!

**Comment by roland-d** [comment]
@sanek4life Multi-categories is not implemented in Joomla and won't be implemented any time soon. This is a major change to the core and if this is going to be done it would be for a future major release. As stated before, someone would need to write the code and it has to be approved by the PLT.

So I will close this issue, feel free to discuss this feature on the mailinglist at https://groups.google.com/forum/#!forum/joomla-dev-cms
