### ISSUE TITLE
Backend submenu dropdown changes since 3.5.1 (regression)

### ISSUE THREAD

**Issue by zero-24** [joomla/joomla-cms#9841]
#### Steps to reproduce the issue

- install 3.5.1
- see the submenu dropdowns in the backend
- install staging
- see the submenu dropdowns in the backend

#### Result image

![screen shot 2016-04-10 at 15 13 20](https://issues.joomla.org/uploads/1/eadf2845cf1dc5a88907b9c089c3ac82.png)

**Comment by MATsxm** [comment]
confirmed

**Comment by andrepereiradasilva** [comment]
confirmed

**Comment by zero-24** [comment]
Maybe it is realted to: https://github.com/joomla/joomla-cms/pull/9375 can you have a look here @C-Lodder ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9841">issues.joomla.org/joomla-cms/9841</a>.</sub>

**Comment by C-Lodder** [comment]
Sure. Will take a look at some point today

**Comment by brianteeman** [comment]
Closed as we have a PR for testing #9872 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9841">issues.joomla.org/joomla-cms/9841</a>.</sub>

**Comment by zero-24** [comment]
Great. Thanks @C-Lodder :+1:
