### ISSUE TITLE
Regression: Redirect to profile when Register to Read More

### ISSUE THREAD

**Issue by infograf768** [joomla/joomla-cms#9846]
#### Steps to reproduce the issue
Create an article set as Registered with a Read More.
Create a menu item of type category blog displaying the category of the article. Make sure `Show Unauthorised Links` is set to Yes.
Display the menu item in frontend and click on the Read More for that article. Log in.

#### Expected result
The full article should display

#### Actual result
The user profile displays.

#### System information (as much as possible)
This happens on monolanguage sites as well as multilanguage sites.

#### Additional comments
It looks like `JUri::isInternal` is broken as it works fine when I comment
```
/*if (!JUri::isInternal($data['return']))
			{
				$data['return'] = '';
			}*/
```

**Comment by joomdonation** [comment]
Yes, JUri::isInternal is broken and that is the reason causing the issue. There is a PR to fix this issue https://github.com/joomla/joomla-cms/pull/8698, however, I think we will still have this issue after applying this PR if the site is located in sub-folder

**Comment by infograf768** [comment]
@joomdonation 

Look my comment at: https://github.com/joomla/joomla-cms/pull/8698#issuecomment-208209646

It works then, even if site is located in sub-folder.

**Comment by infograf768** [comment]
@joomdonation 
Could not we just add to the present checks a check to find out if the url is relative?:
```
diff --git a/libraries/joomla/uri/uri.php b/libraries/joomla/uri/uri.php
index 381f61e..96a89f8 100644
--- a/libraries/joomla/uri/uri.php
+++ b/libraries/joomla/uri/uri.php
@@ -277,4 +277,11 @@
 			return true;
 		}
+		
+		$position= stripos($url, '/');
+
+		if ($position === 0)
+		{
+			return true;
+		}
 
 		return false;
```

**Comment by joomdonation** [comment]
@infograf768 It is simpler to check of the url is relative. Please see https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/uri/uri.php#L272

If $host is empty, the URL is relative URL. People said that for security reason, the relative url need to starts with index.php (see the code), that's the reasons we are having this bug these days.

**Comment by infograf768** [comment]
hmm

**Comment by infograf768** [comment]
Therefore the only thing to do would be to correct https://github.com/joomla/joomla-cms/pull/8698#issuecomment-208209646 and then hope for template designers (and all users) to change their overrides...

**Comment by infograf768** [comment]
Closed as we have a patch https://github.com/joomla/joomla-cms/issues/9959<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9846">issues.joomla.org/joomla-cms/9846</a>.</sub>
