### ISSUE TITLE
Need to fix and resubmit the joomla download link to google search

### ISSUE THREAD

**Issue by rakeshmali** [joomla/joomla-cms#9854]
#### Steps to reproduce the issue
"Wrong URL - https://www.joomla.org/download.html?tmpl=component"
Remove the ?tmpl=component from the download link and resubmit the link to google search through google webmaster.

#### Expected result
The download URL should be- https://www.joomla.org/download.html

#### Actual result
https://www.joomla.org/download.html

**Comment by brianteeman** [comment]
Where are you seeing this link?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9854">issues.joomla.org/joomla-cms/9854</a>.</sub>

**Comment by brianteeman** [comment]
Found it. 

This tracker is for issues with the core of Joomla not the joomla.org web site

Please can you post it as an issue here https://github.com/joomla/joomla-websites/issues/new?title=[joomla.org]%20&body=Please%20describe%20the%20problem%20or%20your%20issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9854">issues.joomla.org/joomla-cms/9854</a>.</sub>
