### ISSUE TITLE
Redirect Update Links - Last Updated Date

### ISSUE THREAD

**Issue by brianteeman** [joomla/joomla-cms#9859]
#### Steps to reproduce the issue
The redirect component has a fairly hidden feature to mass update existing links - its at the bottom of the list called Destination URL.
Select some existing links and click on Destination URL
Enter a new Destination URL and a comment
And then update links button to process

#### Expected result
Destination url is changed
comment is added
Last Updated Date is modified

#### Actual result
Destination url is changed
comment is added
Last Updated Date is unchanged

**Comment by brianteeman** [comment]
Closed as we have a PR #9864 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9859">issues.joomla.org/joomla-cms/9859</a>.</sub>

**Comment by polakluk** [comment]
My PR should fix the issue. However, when I looked at the code, one thing startled me - the way "Destination URL" works right now is that it automatically enables the changed URLs (even if they were disabled prior to the operation). I will update documentation to mention this functionality.

**Comment by brianteeman** [comment]
That sounds like another bug to me

**Comment by polakluk** [comment]
Yeah, I looked at the documentation closely and it never mentions it. So I will post another PR to fix that as well. Before that, I need to figure out what happend in Travis with #9864

**Comment by brianteeman** [comment]
178 | ERROR | Whitespace found at end of line

**Comment by polakluk** [comment]
I just found it too (facepalm)

**Comment by brianteeman** [comment]
I can confirm the bug that all updated links are set to published.

**Comment by polakluk** [comment]
Should I create a separate Github issue for that one, or simply fix it and add it to the #9864 PR?

**Comment by brianteeman** [comment]
up to you. but guessing at what the fix is I would do it in the same PR
