### ISSUE TITLE
Undefined property: JUpdate::$downloadurl  when trying to upgrade from 3.4.8 - 3.51

### ISSUE THREAD

**Issue by coupeborgward** [joomla/joomla-cms#9866]
#### Steps to reproduce the issue
1. Install fresh 3.4.8 installation
2. Joomla Update Component detect new version 3.5.1
3. Click update and in the summary you get the above message (dev log level)

#### Expected result
Download 3.5.1 update package and update joomla

#### Actual result
Get following message in summary page

Update package URL 
Notice: Undefined property: JUpdate::$downloadurl in /websites/website.com.au/administrator/components/com_joomlaupdate/views/default/tmpl/default.php on line 103

Notice: Trying to get property of non-object in /websites/website.com.au/administrator/components/com_joomlaupdate/views/default/tmpl/default.php on line 103

Additional Information 
Notice: Trying to get property of non-object in /websites/website.com.au/administrator/components/com_joomlaupdate/views/default/tmpl/default.php on line 113

#### System information (as much as possible)
Joomla 3.4.8
php 5.6

**Comment by andrepereiradasilva** [comment]
could you try with this patch?
https://github.com/joomla/joomla-cms/pull/9612

**Comment by coupeborgward** [comment]
will do.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9866">issues.joomla.org/joomla-cms/9866</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you for creating this but it would appear that this has been resolved elsewhere in the code base. If this is not correct then this can be re-opened.
