### ISSUE TITLE
com_redirect - "Duplicate URL" sets URLs to enabled and replaces empty comments

### ISSUE THREAD

**Issue by polakluk** [joomla/joomla-cms#9873]
#### Steps to reproduce the issue

1. Go to "Redirect" component in back-end and select some URLs (some of them should be disabled)
2. Click on link "Destination URL" (below table)
3. Enter some URL
4. Leave "Comment" field empty
5. Click on "Update links"

#### Expected result

- Selected rows will have new URL
- Their state (Enabled/disabled) will remain the same
- Their comment will remain the same 

#### Actual result
- Selected rows will have new URL
- Their state is set to Enabled
- Their comment is changed to 'Redirected on: {current date}.'

**Comment by teccrow** [comment]
the existing comments are overwritten<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9873">issues.joomla.org/joomla-cms/9873</a>.</sub>

**Comment by polakluk** [comment]
@teccrow , could you please test PR #9864 and check, if it fixes the issue for you? Thank you.
