### ISSUE TITLE
com_redirect - "Batch" button requires selected rows

### ISSUE THREAD

**Issue by polakluk** [joomla/joomla-cms#9875]
#### Steps to reproduce the issue

1. In admin, go to the redirect component (Components > Redirect)
2. Click on button "Batch"

#### Expected result

- Modal lightbox opens up and allows me to add multiple URLs at once

#### Actual result

- I am requested to select a row, even thought the row is not later used in the process

**Comment by zero-24** [comment]
see here by @brianteeman https://github.com/joomla/joomla-cms/pull/9858 This can be closed i guess.

**Comment by brianteeman** [comment]
Closed as a duplicate<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9875">issues.joomla.org/joomla-cms/9875</a>.</sub>
