### ISSUE TITLE
moduleclass_sfx not showing in Articles Category Module

### ISSUE THREAD

**Issue by rgmears** [joomla/joomla-cms#9879]
#### Steps to reproduce the issue
Publish an Articles Category Module.
Add a Module Class Suffix -- yourclasshere -- in the appropriate pane under Advanced.
View the module in the front end. 
Select it with Firebug.

#### Expected result
```
<div class="moduletable yourclasshere">
    ...
</div>
```
#### Actual result
```
<div class="moduletable">
    ...
</div>
```
#### System information (as much as possible)
J! 3.5.1, Protostar
#### Additional comments
I don't know where to look for this in the code.

**Comment by brianteeman** [comment]
IIRC the div is dependant on the module chrome being used

The UL  does get the classsfx (or at least should do according to the code)
https://github.com/joomla/joomla-cms/blob/staging/modules/mod_articles_category/tmpl/default.php#L13

On 12 April 2016 at 21:46, Robert G Mears <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Publish an Articles Category Module.
> Add a Module Class Suffix -- yourclasshere -- in the appropriate pane
> under Advanced.
> View the module in the front end.
> Select it with Firebug.
> Expected result
>
> <div class="moduletable yourclasshere">
>     ...
> </div>
>
> Actual result
>
> <div class="moduletable">
>     ...
> </div>
>
> System information (as much as possible)
>
> J! 3.5.1, Protostar
> Additional comments
>
> I don't know where to look for this in the code.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9879>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rgmears** [comment]
The class suffix does not show up on either the module or the UL.

This is what is displayed:

```
<div class="moduletable">
    <h3> ... </h3>
   <ul class="category-module">
   ...
   </ul>
</div>
```<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9879">issues.joomla.org/joomla-cms/9879</a>.</sub>

**Comment by brianteeman** [comment]
Thats what shows foe me using protostar on a clean install

![rxnz](https://cloud.githubusercontent.com/assets/1296369/14476623/be17e204-0100-11e6-9d68-d07b3eca0839.png)

**Comment by brianteeman** [comment]
And the module settings 
![xfzd](https://cloud.githubusercontent.com/assets/1296369/14476646/f874ea5a-0100-11e6-9c5d-5e5a0b89a80c.png)

**Comment by rgmears** [comment]
I created a new Article Category module and the class suffix shows up; in both places. 

The other one was created with an older version of Joomla. Perhaps something got lost in the upgrade.

Sorry for the bother.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9879">issues.joomla.org/joomla-cms/9879</a>.</sub>

**Comment by rgmears** [comment]
Actually, the plot thickens. I have two Article Category modules with the same name. One displays on selected pages in Position-2, the other on other pages in Position-7. If I change the name of one -- even just with a non-breaking space at the end -- the class suffix displays on both the DIV and the UL. 

I am surprised that I was allowed to make two modules with the same name.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9879">issues.joomla.org/joomla-cms/9879</a>.</sub>

**Comment by brianteeman** [comment]
Having two modules with the same is very common so no problem there

I think you are hitting a different problem that is already on the tracker
- searching for it now

On 12 April 2016 at 23:10, Robert G Mears <notifications@github.com> wrote:

> Actually, the plot thickens. I have two Article Category modules with the
> same name. One displays on selected pages in Position-2, the other on other
> pages in Position-7. If I change the name of one -- even just with a
> non-breaking space at the end -- the class suffix displays on both the DIV
> and the UL.
>
> I am surprised that I was allowed to make two modules with the same name.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9879
> <https://issues.joomla.org/tracker/joomla-cms/9879>.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9879#issuecomment-209124453>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
See https://issues.joomla.org/tracker/joomla-cms/8270

**Comment by rgmears** [comment]
Not sure what to say Brian. I copied one module (4 times) and each subsequent module did not have the class suffix in it. I checked one of the copies regarding the code. I re-opened the copies and added the suffix. Now it's all working; whether I add a non-breaking space or not to the title. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9879">issues.joomla.org/joomla-cms/9879</a>.</sub>
