### ISSUE TITLE
Regression: Language flag file si_lk.gif is missing

### ISSUE THREAD

**Issue by richard67** [joomla/joomla-cms#9893]
#### Steps to reproduce the issue

It seems that one of the commits on staging between 3.5.0 and 3.5.1 has removed file "media/mod_languages/images/si_lk.gif", which once has been renamed from "si_LK.gif" with following commit:

[https://github.com/joomla/joomla-cms/commit/f283733779fc9cac17901c8718b9e70d0fb5b3f3](https://github.com/joomla/joomla-cms/commit/f283733779fc9cac17901c8718b9e70d0fb5b3f3 "https://github.com/joomla/joomla-cms/commit/f283733779fc9cac17901c8718b9e70d0fb5b3f3").

This could have been caused by a contibutor or maintainer working on Windows, where renaming "si_LK.gif" to "si_lk.gif" does not really have an effect because of case-insensivity of filenames, and still having the "si_LK.gif" name when pushing a branch to github. Or maybe a Git/GitHub bug?

#### Expected result

On Linux with Joomla! 3.5.1 or staging in Joomla! root folder:

> ls -al media/mod_languages/images/si_lk.gif

=> File exists.

#### Actual result

File does not exist.

#### System information (as much as possible)

OS = Linux, no other details relevant.

#### Additional comments

@infograf768 Can you check and report back if this really was by mistake or maybe was desired? And if mistake, who shall do a PR? Me? Or do you wanna do it?

@wilsonge Maybe you can check with which commit to staging the file has been removed, and maybe check back with the contributor to find out how that was caused and if such problems can be avoided somehow in future. I once noticed the commit and wanted to make an issue/PR but then later forgot it, and now I do not find it anymore. But I am almost sure that I remember it was not a pure merge of a PR, it was a commit based on a PR but made by you similar to when you do a "fixed in code base" (but am not sure if it had this label or not). Was somewhen between 3.5.0 release and 3.5.1 release.

**Comment by andrepereiradasilva** [comment]
it was here https://github.com/joomla/joomla-cms/pull/9375/files

**Comment by richard67** [comment]
Ah, yes, this was it, I remember now.

**Comment by brianteeman** [comment]
@C-Lodder you broke the internet<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9893">issues.joomla.org/joomla-cms/9893</a>.</sub>

**Comment by wojsmol** [comment]
Please test https://github.com/joomla/joomla-cms/pull/9902

**Comment by C-Lodder** [comment]
@brianteeman ...Are you sure you're not getting me muddled up with @wilsonge ?

**Comment by C-Lodder** [comment]
I don't see any reference to images in my PR

**Comment by richard67** [comment]
Let's say is was Microsoft's fault ... is always a good idea to assume this :smile:

**Comment by C-Lodder** [comment]
@richard67 - Nah let's just say it was @wilsonge.....normally is anyway :P

**Comment by wojsmol** [comment]
@C-Lodder See https://github.com/joomla/joomla-cms/pull/9375/commits/4e5c808d38bfb00936851e4723af089c8a7b3f65

**Comment by C-Lodder** [comment]
@wojsmol - erm...oops

**Comment by mbabker** [comment]
Stop spending so much time around @wilsonge as his tendency to break all the things is rubbing off on you.

**Comment by wilsonge** [comment]
Well as @C-Lodder is responsible for me being involved in Joomla in the first place I'm pretty sure he'll forever be in debt :D

**Comment by brianteeman** [comment]
Didn't George tell you - Brian is always right
