### ISSUE TITLE
buttons (save, close etc.) don't work in articles joomla 3.5.1

### ISSUE THREAD

**Issue by hypnoyanova** [joomla/joomla-cms#9895]
#### Steps to reproduce the issue
update joomla 3.4.8 to 3.5.1

#### Expected result
functioning within normal parameters

#### Actual result
buttons [save], [save & close], [save & new], [save as copy], [close] don't work in articles, though the [versions] button works, at least when clicked it displays [item version history] which is blank (saving history is enabled). also all the tabs like [publishing], [options] etc. have disappeared from the article view as well as buttons [read more], [article], [insert image]

#### System information (as much as possible)
PHP Version: 5.5.31-1+mh1
Web Server: Apache
Joomla! Version: Joomla! 3.5.1 Stable

**Comment by brianteeman** [comment]
Please completely clear your browser cache.

This is not a bug in the core of joomla. If clearing the cache doesnt solve it for you (and it should) then please use the forum for support http://forum.joomla.org<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9895">issues.joomla.org/joomla-cms/9895</a>.</sub>
