### ISSUE TITLE
Joomla! Update - launches Akeeba Default backup function

### ISSUE THREAD

**Issue by jentekk** [joomla/joomla-cms#9903]
#### Steps to reproduce the issue
Joomla! v.3.5.0
Administrator > Components > Joomla! Update > Write Files Directly > click on "Install the Update"

#### Expected result
Expected Joomla! 3.5.0 to update to Joomla! 3.5.1

#### Actual result
Launches Akeeba default backup function and performs a total backup

#### System information (as much as possible)
PHP Built On -	Linux cwh23.xxxxxx.com 2.6.32-604.30.3.lve1.3.63.el6.x86_64 #1 SMP Sun Sep 27 06:34:10 EDT 2015 x86_64
Database Version - 5.6.29
Database Collation - latin1_swedish_ci
Database Connection Collation - utf8mb4_general_ci
PHP Version - 5.4.45
Web Server - Apache
WebServer to PHP Interface - cgi-fcgi
Joomla! Version - Joomla! 3.5.0 Stable [ Unicorn ] 21-March-2016 22:00 GMT
Joomla! Platform Version - Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent - Mozilla/5.0 (Windows NT 6.1; WOW64; rv:45.0) Gecko/20100101 Firefox/45.0

**Comment by Twincarb** [comment]
If you have got Akeeba installed, there is a plugin with it that will activate a backup before installing an update. 
Under plugins search for System - Backup on update and you will find it is enabled.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9903">issues.joomla.org/joomla-cms/9903</a>.</sub>

**Comment by Bakual** [comment]
Closing this as it is a feature of Akeeba Backup, not from core.

**Comment by jentekk** [comment]
Thank you. :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9903">issues.joomla.org/joomla-cms/9903</a>.</sub>
