### ISSUE TITLE
Navigation bar becoming unresponsive

### ISSUE THREAD

**Issue by GABBAR1947** [joomla/joomla-cms#9909]
**Steps to reproduce the issue**
Select any option from the nav bar in the Joomla backend .(i.e. Users, Menus, Content, Components etc.)
For example: Select Menus -> Manage -> Add new menu

Now try clicking on any option of the topmost nav bar.

**Expected result**
Clicking on a specific button cancels the ongoing process of creating a new Menu and redirects accordingly.

**Actual result**
The nav bar becomes unresponsive. One has to either click on save or cancel and redirect himself by clicking on the nav bar.

**Additional comments**
This can be a feature that we can add to the next version of Joomla! . Moreover if the fields are not empty, we can provide an option to the user, that will save the fields for the next time or just delete the current fields and redirect accordingly.

**Comment by SharkyKZ** [comment]
This is done on purpose.

**Comment by brianteeman** [comment]
I am closing this as the expected behaviour<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9909">issues.joomla.org/joomla-cms/9909</a>.</sub>
