### ISSUE TITLE
Moving "Install from Web" to 2nd position on Installer page

### ISSUE THREAD

**Issue by Saurabh1** [joomla/joomla-cms#9916]
#### Steps to reproduce the issue
Currently the position of "Install from Web" on Install page is first position on the Tab which means if it is enabled then it will always load from the web and on slow connection or for any issue it takes time to load and move to second tab "Upload Package File" or other tabs if clicked. 

#### Expected result
I hope this can be changed in the future if it seems legitimate to move the position from first to 2nd tab and team thinks if it's good solution.

**Comment by brianteeman** [comment]
You can already change the position - just check the options in the plugin

**Comment by rdeutz** [comment]
What ever position it is it will always load.

**Comment by brianteeman** [comment]
Yes it will always load but by putting it in the last position you can
still use your site (but I dont have a slow connection to really test on)

On 14 April 2016 at 18:20, Robert Deutz <notifications@github.com> wrote:

> What ever position it is it will always load.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9916#issuecomment-210059246>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Saurabh1** [comment]
Thanks Brian and Robert :+1:
