### ISSUE TITLE
No check on TOS using Profile plugin

### ISSUE THREAD

**Issue by umbcel** [joomla/joomla-cms#9917]
#### Steps to reproduce the issue
Enable  plugin "profile"
Activate new users without accepting TOS

#### Expected result
Without accepted TOS new users shouldn't be created.

#### Actual result
Without accepted TOS new users will be created

#### System information (as much as possible)
I found and solved the problem in /plugins/user/profile/profile.php
At the line number 376 is wrongly indicated "com_user" instead of "com_users"

**Comment by alikon** [comment]
already solved by #9792
