### ISSUE TITLE
Improve JHtml::_('image')

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#9919]
#### Steps to reproduce the issue

Go to frontend, with breadcrumbs enabled, do an audit test with chrome. Then you see that the divider is missing a width and height tag.

#### Expected result

No issue

#### Actual result

Specify image dimensions (1)
A width and height should be specified for all images in order to speed up page display. The following image(s) are missing a width and/or height:
arrow.png
(2 uses)

#### Additional comments

We need to parse the height and width on the JHtml:_('image') side. 

for example this code we use to show the width and height:

````
$location = JUri::root() . $attachment->getUrl();
$data = getimagesize($location);
$width = $data[0];
$height = $data[1];


<img src="<?php echo $attachment->getUrl(); ?>" width="<?php echo $width ;?>" height="<?php echo $height ;?>" alt="" />
````

This is needed for a w3c validation checks, or any other html checks like in the inspector from chrome (audit - ).

Now if you check a clean protostar template. he is showing a dimension notice to fix the height and width tag.

![tests](https://cloud.githubusercontent.com/assets/876623/14545821/5a568e08-02a1-11e6-8ba1-ef9bc0128a69.jpg)

**Comment by brianteeman** [comment]
I dont get that report in my chrome audit but thats not relevant

Your title says that its an issue with JHtml:_('image')
Why do you say that?

If you want to add dimensions using JHtml:_('image') you can do it as stated in the docblock and seen elsewhere in the core

> JHtml::_('image', 'media/dots.gif', '...', array('width' => 22, 'height' => 12), true)

All that is needed for mod_breadcrumbs is to add that array<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9919">issues.joomla.org/joomla-cms/9919</a>.</sub>

**Comment by brianteeman** [comment]
See #9919 for an example<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9919">issues.joomla.org/joomla-cms/9919</a>.</sub>

**Comment by SharkyKZ** [comment]
The image is so small in dimensions, it doesn't really visibly affect page rendering. But in case it is decided to add the dimensions, it should be done in template CSS.

**Comment by brianteeman** [comment]
I am closing this at this time. If code is provided (a pull request) it can always be re-examined.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9919">issues.joomla.org/joomla-cms/9919</a>.</sub>
