### ISSUE TITLE
unTagItem: Syntax error in SQL query

### ISSUE THREAD

**Issue by mrkale** [joomla/joomla-cms#9926]
#### Steps to reproduce the issue
Implement batch untagging function in a custom component. However, the simplest way is to look into the source code. The bug is on the code line _1056_ in the file **\\\libraries\cms\helper\tags.php**. The argument(s) of the SQL clause _IN_ should be enclosed in braces.

#### Expected result
Without SQL syntax error at batch untagging in a component.

#### Actual result
The bug leads to the error message:

> 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '2' at line 3 SQL=DELETE FROM #\_\_contentitem_tag_map WHERE \`type_alias\` = 'com_gfamily.domain' AND \`content_item_id\` = 2 AND `tag_id` IN 2

#### System information (as much as possible)
The line **1056** of the file **\\\libraries\cms\helper\tags.php** is currently
`$query->where($db->quoteName('tag_id') . ' IN ' . implode(',', $tags));`

and should be
`$query->where($db->quoteName('tag_id') . ' IN (' . implode(',', $tags) . ')');`

#### Additional comments
The bug is present in the JoomlaCMS since version 3.4 (maybe sooner or since introducing tagging capabality) and persists in the version 3.5.1 as well.

**Comment by andrepereiradasilva** [comment]
@mrkale can you do a Pull Request (PR) to correct that?

https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/helper/tags.php#L1056

**Comment by mrkale** [comment]
OK, past the weekend.

Bye, mrkale.

**Comment by richard67** [comment]
I think this caqn be closed since there is a PR for that: #9946 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9926">issues.joomla.org/joomla-cms/9926</a>.</sub>
