### ISSUE TITLE
Archived module links to a 500 error

### ISSUE THREAD

**Issue by Elnino38** [joomla/joomla-cms#9927]
#### Steps to reproduce the issue

Create an article, archive it, publish the "Articles - Archived" module and click on the "month + year" showing up in the module.

#### Expected result

See the list of archived articles for this particular month

#### Actual result

500 error. No Apache log on this error on the server.

#### System information (as much as possible)

Joomla 3.5.1, Apache, default .htaccess. No fancy plugins.

#### Additional comments

Tried with the default Protostar template, same issue. Tried with disabling SEF Urls, same issue. Not sure if that comes from Joomla 3.5.1 as I don't use archiving feature very often.

**Comment by brianteeman** [comment]
Please go to Global configuration and set the Error Reporting (in the third
tab) to Development and try again - that wont fix it but it should reveal
the error code

On 15 April 2016 at 10:55, Elnino38 <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Create an article, archive it, publish the "Articles - Archived" module
> and click on the "month + year" showing up in the module.
> Expected result
>
> See the list of archived articles for this particular month
> Actual result
>
> 500 error. No Apache log on this error on the server.
> System information (as much as possible)
>
> Joomla 3.5.1, Apache, default .htaccess. No fancy plugins.
> Additional comments
>
> Tried with the default Protostar template, same issue. Tried with
> disabling SEF Urls, same issue. Not sure if that comes from Joomla 3.5.1 as
> I don't use archiving feature very often.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9927>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Elnino38** [comment]
You’re absolutely right, thanks, I’ve fixed the error thanks to this tip (my mistake I should have thought on that). Now I can access the page, in my example it’s: “/archives/2007/4” but the page is empty. The article is not showing up. Anything I am missing? The article archived on April 2007 doesn’t show up on this page. Same thing with the Protostar template.

 

  _____  

I welcome VSRE emails. Learn more at  <http://vsre.info/> http://vsre.info/

**Comment by brianteeman** [comment]
I am unable to replicate this issue. @Elnino38 if you are still having this issue then I think its best to use the forum for support<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9927">issues.joomla.org/joomla-cms/9927</a>.</sub>
