### ISSUE TITLE
Full Package dont have installer files

### ISSUE THREAD

**Issue by PrestaShark** [joomla/joomla-cms#9933]
#### Steps to reproduce the issue
https://github.com/joomla/joomla-cms/releases/download/3.5.1/Joomla_3.5.1-Stable-Full_Package.zip

#### Expected result
new installation

#### Actual result
no installer files

"No configuration file found and no installation code available. Exiting..."

#### Additional comments
:)

**Comment by mbabker** [comment]
The installation folder is present.  I just downloaded and verified.
