### ISSUE TITLE
Maybe a typo on menu model

### ISSUE THREAD

**Issue by 810** [joomla/joomla-cms#9936]
#### Steps to reproduce the issue

Look at: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/models/items.php#L215

#### Expected result

Should this not be `a.published` ?

**Comment by brianteeman** [comment]
yes - can you do a PR please

On 15 April 2016 at 16:06, Jelle Kok <notifications@github.com> wrote:

> Steps to reproduce the issue
>
> Look at:
> https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_menus/models/items.php#L215
> Expected result
>
> Should this not be a.published ?
> Actual result System information (as much as possible) Additional comments
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9936>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by 810** [comment]
ok 1 sec

**Comment by brianteeman** [comment]
Closed as we have a PR #9937
