### ISSUE TITLE
Database is out of date!

### ISSUE THREAD

**Issue by ahmadm42** [joomla/joomla-cms#9947]
#### Steps to reproduce the issue

Update from Joomla 3.4.8 to Joomla 3.5.1 

#### Expected result

Fixing the database
#### Actual result

When Pressing Fix ....An Internal Error 500 is shown

#### System information (as much as possible)

System Information
Setting	Value
 
PHP Built On	Linux ip-208-109-119-162.ip.secureserver.net 2.6.32-573.1.1.el6.centos.plus.x86_64 #1 SMP Sun Jul 26 00:52:05 UTC 2015 x86_64
Database Version	5.5.44
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.4.21
Web Server	Apache
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.112 Safari/537.36

#### Additional comments

My website is still working properly.

But please check the following thread.

http://forum.joomla.org/viewtopic.php?f=710&t=919659

Thank you for your help.

**Comment by brianteeman** [comment]
This is not a support forum. Sorry I am closing this

**Comment by ahmadm42** [comment]
Please Can you help me?
