### ISSUE TITLE
Problem with new router

### ISSUE THREAD

**Issue by chrisdavenport** [joomla/joomla-cms#9953]
#### Steps to reproduce the issue
Starting with a clean Joomla install, activate the new router for the Contact component only.

Set error reporting to Development in Global Configuration.

Add a contact.

In an article, add the following links (you may need to adjust the ids for your installation):
* index.php?option=com_contact&view=categories
* index.php?option=com_contact&view=category&id=4
* index.php?option=com_contact&view=contact&id=1

When you view the article the links should appear as:
* component/contact/categories?Itemid=101
* component/contact/category/4-uncategorised?Itemid=101
* component/contact/contact/1?Itemid=101

The Itemid is from the menu item pointing to the article.  I don't think they should be there, but leaving that aside for the moment...

Test the links to make sure they go to the expected pages.

So far, so good.  Now activate the new router for the Content (Articles) component and reload the page.

#### Expected result

The links should be unchanged.

#### Actual result

The links now all appear as:
* component/contact?Itemid=101

Clicking on this link takes you to the categories view.

#### System information (as much as possible)

Current 3.6.x branch.

#### Additional comments
~~Any of the previously working SEF links (eg. component/contact/categories) now throw a bunch of warnings and a fatal error:~~
* ~~Notice: Trying to get property of non-object in /path-to-joomla/libraries/cms/component/router/rules/standard.php on line 65~~
* ~~Warning: array_merge(): Argument #1 is not an array in /path-to-joomla/libraries/cms/component/router/rules/standard.php on line 65~~
* ~~Warning: array_merge(): Argument #2 is not an array in /path-to-joomla/libraries/cms/router/router.php on line 350~~
* ~~Fatal error: Unsupported operand types in /path-to-joomla/libraries/cms/router/router.php on line 234~~

The raw non-SEF links continue to work correctly.

**Comment by brianteeman** [comment]
Changing the milestone to 3.7 after the number changes

**Comment by dgt41** [comment]
I guess #11035 solves this one (?)

**Comment by wilsonge** [comment]
Note I've struck out the additional comments as that was a separate bug that has since been fixed. The main issue however is still valid

**Comment by wilsonge** [comment]
This issue seems to be solved with #11035 - the URLs do now link to the correct place (although with different URLs). The original URLs work as well if anyone has got them directly linked.
