### ISSUE TITLE
User ban for a certain time

### ISSUE THREAD

**Issue by sanek4life** [joomla/joomla-cms#9954]
User ban for a certain time.

Now in Joomla you can ban any user forever. This is no right way.

Just put some strings in Joomla code for add field, where admin can set date for unban user.

and field for "reason for user ban"

**### Example ###**

Ban user until: may 1, 2016.
Reason for ban: spam / obscene speech / etc

**Comment by JoshuaLewis** [comment]
Indeed it would be nice to see this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9954">issues.joomla.org/joomla-cms/9954</a>.</sub>

**Comment by pe7er** [comment]
Thank you for your suggestion! However it has been decided that this is not something that will be included in the core of Joomla.

**Comment by zero-24** [comment]
Set to "closed" on behalf of @zero-24 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9954">issues.joomla.org/joomla-cms/9954</a>

**Comment by zero-24** [comment]
Closing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9954">issues.joomla.org/joomla-cms/9954</a>.</sub>

**Comment by sanek4life** [comment]
@pe7er why not included in the core of Joomla? this is a very useful feature.

**Comment by pe7er** [comment]
@sanek4life I understand that it would be a useful feature for you. However this feature is very specific and most websites will probably not use it. 

You can extend Joomla's functionality with 3rd party extensions and you'll probably find extensions for extended user management on http://extensions.joomla.org/.

**Comment by sanek4life** [comment]
@pe7er no extensions does not provide such functionality, so I wrote about it here.

this feature is not very specific, because every site with "news", "comments", etc want this function.

**Comment by sanek4life** [comment]
maybe rename my question - i want move user from "registered" grop to "guest" for certain time.

**Comment by brianteeman** [comment]
If all those sites needed this functionality and it was not available in
the core then I can guarantee that someone wuld have created it as an
extension. The fact that no one has is proof that @pe7er is correct.

It is not going to be created - sorry

On 12 May 2016 at 17:34, s <notifications@github.com> wrote:

> maybe rename my question - i want move user from "registered" grop to
> "guest" for certain time.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9954#issuecomment-218812983>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sanek4life** [comment]
most popular social network in Russia - vk.com have option for community administrators for ban users, for certain time:

![an vk](https://cloud.githubusercontent.com/assets/3662519/15224495/5f4cb9c2-1882-11e6-8a57-7acf4e2c24e2.png)

this is really good option. i also see this option in others CMS.

**Comment by brianteeman** [comment]
yes a social network not   a cms

Anyway it doesnt matter how many times you post the decision has been made

On 12 May 2016 at 18:46, s <notifications@github.com> wrote:

> most popular social network in Russia - vk.com have option for community
> administrators for ban users, for certain time:
>
> [image: an vk]
> <https://cloud.githubusercontent.com/assets/3662519/15224495/5f4cb9c2-1882-11e6-8a57-7acf4e2c24e2.png>
>
> this is really good option. i also see this option in others CMS.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9954#issuecomment-218832851>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by JoshuaLewis** [comment]
Giving site members a time out is a common admin feature on websites with users. Not just social networks or niche sites. Think of it like jail, you don't want them completely out of the game, you just want consequences so that people follow the rules.

**Comment by sanek4life** [comment]
@JoshuaLewis most people coming out of prison. they do not stay there forever. I can not remember all those banned, and I do not remember the reason for the ban.

@brianteeman  This option is needed for any website where there are users.

**Comment by sanek4life** [comment]
@brianteeman 

rename for this issue:

move user to other/guest "user group" for a certain time

**Comment by sanek4life** [comment]
@brianteeman with joomla components i can set, who allow comment my news or do other things on site. (example: JComments, etc)

i'm just want option "move user to guest group for a certain time"

**Comment by 4digitalworld** [comment]
please add this option

**Comment by Bakual** [comment]
Please don't comment on closed issues.
