### ISSUE TITLE
Archived Articles render in the Archived default.php instead of the Article default.php

### ISSUE THREAD

**Issue by Webdongle** [joomla/joomla-cms#9963]
#### Steps to reproduce the issue

- Install Joomla with Test sample data
- Click the 'Archived Articles' menu item
- Click the Title of the Archived Article
- View the source code

#### Expected result
The Article displays
Viewing the source code shows the Article displays in the Article view default.php

#### Actual result
The Article doesn't display
The filter fields show
Viewing the source code shows the Article displays in the Archive view default.php

#### Additional comments
Reported in the forum http://forum.joomla.org/viewtopic.php?f=706&t=921824

Articles with a menu item display but without details 'Written by' etc

**Comment by Webdongle** [comment]
Further investigation shows that if (while using Test sample) you put 'What's New in 1.5?' as 'featured' and log in as SU then it gives a url /featured-articles/9-uncategorised/67-whats-new-in-15

Logging out (or viewing with another browser not logged in) and visiting /featured-articles/9-uncategorised/67-whats-new-in-15 displays the page

The hyperlink in the 'Archived Article' view should route to the same url

**Comment by Webdongle** [comment]
Replacing /components/com_content/router.php fixes the issue.  So it is a change in that file causes the problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9963">issues.joomla.org/joomla-cms/9963</a>.</sub>

**Comment by Joomron** [comment]
Hello Webdongle,

I had the same problem, your input resolved als my problem.

Hope that problem in the next version of joomla is solved! Beause this is a bug.

Are there not more people with this problem/bug? 

regards Ron<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9963">issues.joomla.org/joomla-cms/9963</a>.</sub>

**Comment by Webdongle** [comment]
That is a not a resolution ... I added that comment to help show there is a problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9963">issues.joomla.org/joomla-cms/9963</a>.</sub>

**Comment by Joomron** [comment]
You're right, sorry!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9963">issues.joomla.org/joomla-cms/9963</a>.</sub>

**Comment by Webdongle** [comment]
Closed in favour of #10613
