### ISSUE TITLE
Custom Html Module With Module-Tag 'Article' there is no Edit Button in frontend

### ISSUE THREAD

**Issue by joris85** [joomla/joomla-cms#9973]
#### Steps to reproduce the issue
Place Custom Html Module With Module-Tag Article
Login in the frontend and make sure you can edit modules in frontend.
On all other custom html modules i can see the edit button except for the one with the Tag Article.

#### Expected result
I would expect that i could also edit this one in the frontend.

#### Actual result
There is no edit button if the tag is article

#### System information (as much as possible)
Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT
PHP 5.5.30

**Comment by brianteeman** [comment]
Sorry I am a little confused. What is "Module-Tag Article'

**Comment by joris85** [comment]
In the advanced tab of module settings you can give a module a html 5 tag.
Like article, aside and stuff.
This is usefull for google if you have no article i think. 
So i thought lets try (; 
Bus then the edit button disapear.

Or am i the first that is trying this haha

**Comment by brianteeman** [comment]
Thanks for the explanation. I understand your question now and will take a
look shortly

**Comment by brianteeman** [comment]
I can confirm that when you set the tag the module is not editable<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9973">issues.joomla.org/joomla-cms/9973</a>.</sub>

**Comment by brianteeman** [comment]
Closing as we have a PR for testing #11417<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9973">issues.joomla.org/joomla-cms/9973</a>.</sub>
