### ISSUE TITLE
Compression Problem after update to 3.5.1

### ISSUE THREAD

**Issue by lmrex** [joomla/joomla-cms#9979]
#### Steps to reproduce the issue
Unfortunatelly I dont Know how to reproduce it, just now how to remove it(by cleaning joomla cache).
Sorry, dont know for sure if its due to the update, but i did not install anything after the update and this problem started appearing after the update.

#### Expected result
Simply not have to clean cache to the website starts using the correct compression

#### Actual result
Somehow after a while some of my pages wont open and te browser reports a codification problem, saying the compression type is invalid, it happens randomly in pages, never all of them, this is really bothering me

#### System information (as much as possible)
PHP Built On	Linux server.zibli.com 2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64
Database Version	5.5.31
Database Collation	latin1_swedish_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	5.3.28
Web Server	Apache/2
WebServer to PHP Interface	cgi-fcgi
Joomla! Version	Joomla! 3.5.1 Stable [ Unicorn ] 05-April-2016 22:45 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent	Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.75 Safari/537.36

#### Additional comments

I dont Know if recreating the website would resolve the issue, its becoming very problematic, hope to have this issue in the right place.

Thanks for any comment.

**Comment by ggppdk** [comment]
If you are going to use PHP 5.3.x
- then you need to use PHP 5.3.29 or upgrade to a later PHP version

because PHP 5.3.28 has several bugs that can be related to the issue, new Joomla version maybe more prone to making the PHP 5.3.28 bugs appear

See bug-fix list here:
http://php.net/ChangeLog-5.php#5.3.29

**Comment by pe7er** [comment]
PHP 5.3 is end-of-life for almost 2 years http://php.net/eol.php and this issue seems to be PHP related (thanks @ggppdk !). Please ask your hosting company to upgrade your server to a recent PHP version.
I'll close this issue.
