### ISSUE TITLE
LoadModule editor plugin all too ruthlessly enforces existing module view filter

### ISSUE THREAD

**Issue by Paladin** [joomla/joomla-cms#9981]
#### Steps to reproduce the issue

1.) Go to the modules view and set a filter, for example, set it to show only modules in position 'x' (any position will do, in my experience)
2.) Now go to a content item and click the editor button to insert a module.

#### Expected result

1.) Best outcome is for both processes to use independent filters (be able to set one filter in the module view, another in the editor plug-in, and have both be remembered.

2.) Minimally acceptable outcome is to have a mechanism for resetting/changing the existing filter so you can actually see the module you want to insert via the editor.

#### Actual result

The pop-up list of modules contains only those modules that satisfy the previously entered filter, and note how there is no possible way to change that state from this pop-up. You have to leave the editor and go back to the module manager just in order to make the editor plug-in work properly.

#### System information (as much as possible)

J3.5.1, PHP 5.6.15, apache 2.4.17, using FPM/fcgi

#### Additional comments

Ideally the two filter sets should be independent, but even having the editor plugin ignore existing filters and always start with a full list would be an improvement on existing behavior. The use case I'm coming from is setting up a menu ID, switching over to add modules to that menu item, then switching into the content item to insert a module, sometimes repeating that process 2-3 times depending upon circumstances. It's a manual process, and having to remember to reset the module filter is tedious and bad UX. If there's a filter on the items in the list, the filter should be able to be modified while on that list and not require you to abandon your work and go to a different section of the site to make the filter change, then come back to the content item and do what you wanted to do in the first place.

**Comment by ot2sen** [comment]
Confirm that behaviour. Did set it to position-7 in module filter for postions, and in article edit only see the modules for position-7 with no way to change to view all positions
J3.5.1, PHP 7.0.4

**Comment by wojsmol** [comment]
@Paladin @ot2sen Please test on staging

**Comment by andrepereiradasilva** [comment]
can't reproduce this in latest staging.

please retest with latest staging.

**Comment by brianteeman** [comment]
Yes I seem to recall this being fixed earlier. Cant find the PR right now
but I cannot replicate this either with the current staging

On 19 April 2016 at 16:39, andrepereiradasilva <notifications@github.com>
wrote:

> can't reproduce this in latest staging.
>
> please retest with latest staging.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/issues/9981#issuecomment-211984462>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
@paladin can you retest with staging please or I will be closing this as "resolved elsewhere"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9981">issues.joomla.org/joomla-cms/9981</a>.</sub>

**Comment by ot2sen** [comment]
Problem is solved in latest staging.

**Comment by andrepereiradasilva** [comment]
@brianteeman close?

**Comment by brianteeman** [comment]
I wanted to wait to give the original poster @Paladin to respond

**Comment by Paladin** [comment]
Sounds good. I haven't personally confirmed, but I'll take @otsen's word for it.
