### ISSUE TITLE
Modal window size on batch editing

### ISSUE THREAD

**Issue by Doomfinger** [joomla/joomla-cms#9986]
When using the 'batch' feature in categories, articles and menus, the modal window is not long enough to fully display the access level options.

#### Expected result
Full access to all options

#### Actual result
bottom of drop down menu is limited by bottom of window

#### System information (as much as possible)
(Abyss webserver Windows10 64bit J3.5.1) - Admin using Windows edge, Firefox, IE11.

**Comment by brianteeman** [comment]
Thank you for reporting this. It has however already been reported and fixed and will be resolved with the upcoming release of 3.5.2
