### ISSUE TITLE
Joomla does not allow user to set article order in categories

### ISSUE THREAD

**Issue by kkstf** [joomla/joomla-cms#9989]
#### Steps to reproduce the issue
In 3.5.1 I cannot find any way to assign Global settings to the order in which articles get displayed when I click the link to a category that has subcategories. Irrespective of which subcategory the articles are in I want them to appear chronologically, yet they are defaulting to display articles in alphabetical categories and thus most recent articles are not showing at the top.
There should be an option in:
1) Content
2) Articles
3) Options
4) Blog/Featured Layout

**Comment by brianteeman** [comment]
Was this what you meant?
![hvuu](https://cloud.githubusercontent.com/assets/1296369/14643953/4a4987fe-0648-11e6-87d8-66c9128b72dc.png)

**Comment by brianteeman** [comment]
Closed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9989">issues.joomla.org/joomla-cms/9989</a>.</sub>
